### ISSUE TITLE
Beetle PSX HW Core keeps crashing (Vulkan)

### ISSUE THREAD

**Issue by sourceAida** [libretro/RetroArch#10015]
**The Beetle PSX HW Core keeps crashing when using the Vulkan API. Using other API's such as OpenGL works just fine.**

OS: Win10 1903
Compiler: RetroArch-2020-01-14-x64
GPU: Rx5700-Adrenalin 2020 Edition 20.1.1 [HW Yes]

**Here the log file of the crash:**
[INFO] RetroArch 1.8.3 (Git 98b572d17a)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Jan 14 2020
[INFO] Version: 1.8.3
[INFO] Git: 98b572d17a
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "A:\Games\Game Consoles\RetroArch\saves.srm".
[INFO] Redirecting savestate to "A:\Games\Game Consoles\RetroArch\states.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 1920x1016
[INFO] Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: wgl
[INFO] [Vulkan]: Detecting screen resolution 1920x1080.
[INFO] [Vulkan]: Found GPU at index 0: AMD Radeon RX 5700
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using GPU: AMD Radeon RX 5700
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Swapchain supports present mode: 3.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 1920 x 1016.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1920x1016
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]: Textures:
[INFO] [slang]: Source (#0)
[INFO] [slang]:
[INFO] [slang]: Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]: Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]: MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]: Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [XInput]: Found controller, user #0
[INFO] [XInput]: Pads connected: 1
[INFO] [DINPUT]: Enumerating joypads ...
[INFO] [DINPUT]: Device #0 PID: {02E0} VID:{045E}
[INFO] [DINPUT]: Done enumerating joypads ...
[INFO] [XInput]: Attempting autoconf for "XInput Controller (User 1)", user #0
[INFO] [DINPUT]: Found XInput pad at index 0 (DINPUT index 0)
[INFO] [XInput]: Found VID/PID (045E/02E0) from DINPUT index 0 for "XInput Controller (User 1)", user #0
[INFO] [XInput]: Attempting autoconf for user #1
[INFO] [XInput]: Attempting autoconf for user #2
[INFO] [XInput]: Attempting autoconf for user #3
[INFO] [XInput]: Attempting autoconf for user #4
[INFO] [XInput]: Attempting autoconf for user #5
[INFO] [XInput]: Attempting autoconf for user #6
[INFO] [XInput]: Attempting autoconf for user #7
[INFO] [XInput]: Attempting autoconf for user #8
[INFO] [XInput]: Attempting autoconf for user #9
[INFO] [XInput]: Attempting autoconf for user #10
[INFO] [XInput]: Attempting autoconf for user #11
[INFO] [XInput]: Attempting autoconf for user #12
[INFO] [XInput]: Attempting autoconf for user #13
[INFO] [XInput]: Attempting autoconf for user #14
[INFO] [XInput]: Attempting autoconf for user #15
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: 141 profiles found.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] Found shader "A:\Games\Game Consoles\RetroArch\shaders\retroarch.slangp"
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Autoconf]: selected configuration: A:\Games\Game Consoles\RetroArch\autoconfig\xinput\Xbox_One_Controller.cfg
[INFO] [Menu]: Found menu display driver: "vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0000000000B8D0C0
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "winmm" driver.
[WARN] Input device ID 5 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_history.lpl].
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_music_history.lpl].
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_video_history.lpl].
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_image_history.lpl].
[INFO] Loading favorites file: [A:\Games\Game Consoles\RetroArch\content_favorites.lpl].
[INFO] [Vulkan]: VSync => on
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]: Textures:
[INFO] [slang]: Source (#0)
[INFO] [slang]:
[INFO] [slang]: Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]: Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]: MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]: Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [Vulkan]: VSync => on
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Vulkan]: Do not need to re-create swapchain.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]: Textures:
[INFO] [slang]: Source (#0)
[INFO] [slang]:
[INFO] [slang]: Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]: Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]: MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]: Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] Using content: A:\Games\Game Consoles\RetroArch\downloads\PS1\Suikoden II (USA).cue.
[INFO] arg #0: retroarch
[INFO] arg #1: A:\Games\Game Consoles\RetroArch\downloads\PS1\Suikoden II (USA).cue
[INFO] arg #2: -s
[INFO] arg #3: A:\Games\Game Consoles\RetroArch\saves
[INFO] arg #4: -S
[INFO] arg #5: A:\Games\Game Consoles\RetroArch\states
[INFO] arg #6: -c
[INFO] arg #7: A:\Games\Game Consoles\RetroArch\retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: A:\Games\Game Consoles\RetroArch\cores\mednafen_psx_hw_libretro.dll
[INFO] arg #10: -v
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : A:\Games\Game Consoles\RetroArch\retroarch.cfg
[INFO] RetroArch 1.8.3 (Git 98b572d17a)
[INFO] Redirecting save file to "A:\Games\Game Consoles\RetroArch\saves\Suikoden II (USA).srm".
[INFO] Redirecting savestate to "A:\Games\Game Consoles\RetroArch\states\Suikoden II (USA).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Jan 14 2020
[INFO] Version: 1.8.3
[INFO] Git: 98b572d17a
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "A:\Games\Game Consoles\RetroArch\cores\mednafen_psx_hw_libretro.dll"
[INFO] [Overrides] no core-specific overrides found at A:\Games\Game Consoles\RetroArch\config\Beetle PSX HW\Beetle PSX HW.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at A:\Games\Game Consoles\RetroArch\config\Beetle PSX HW\PS1.cfg.
[INFO] [Overrides] no game-specific overrides found at A:\Games\Game Consoles\RetroArch\config\Beetle PSX HW\Suikoden II (USA).cfg.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] Core requested VFS version >= v1, providing v3
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Remaps]: remap directory: A:\Games\Game Consoles\RetroArch\config\remaps
[INFO] Redirecting save file to "A:\Games\Game Consoles\RetroArch\saves\Beetle PSX HW\Suikoden II (USA).srm".
[INFO] Redirecting savestate to "A:\Games\Game Consoles\RetroArch\states\Beetle PSX HW\Suikoden II (USA).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "A:\Games\Game Consoles\RetroArch\system".
[INFO] [Environ]: SET_DISK_CONTROL_INTERFACE.
[INFO] [Environ]: GET_PERF_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 15.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[libretro INFO] Rumble interface supported!
[INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[libretro INFO] Loading A:\Games\Game Consoles\RetroArch\downloads\PS1\Suikoden II (USA).cue...
[libretro INFO] Checking if required firmware is present.
[libretro INFO] Firmware found: A:\Games\Game Consoles\RetroArch\system\scph5501.bin
[libretro INFO] Firmware SHA1: 0555C6FAE8906F3F09BAF5988F00E55F88E9F30B
[INFO] [Environ]: GET_PREFERRED_HW_RENDER.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting Vulkan context.
[INFO] [Environ]: SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_DISPLAY.
[INFO] [RCHEEVOS]: ext_hash 0b886782 ('cue')
[INFO] [RCHEEVOS]: Load task finished
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: A:\Games\Game Consoles\RetroArch\cheats\Beetle PSX HW\Suikoden II (USA).cht
[INFO] [Audio]: Set audio input rate to: 44143.41 Hz.
[INFO] [Video]: Video @ 1920x1016
[INFO] [Video]: Using HW render, Vulkan driver forced.
[INFO] Vulkan dynamic library loaded.
[INFO] [Vulkan]: App: Beetle PSX (version 0)
[INFO] [Vulkan]: Engine: parallel-psx (version 0)
[INFO] [Vulkan]: Found vulkan context: wgl
[INFO] [Vulkan]: Detecting screen resolution 1920x1080.
[libretro INFO] Found Vulkan GPU: AMD Radeon RX 5700
[libretro INFO] API: 1.1.129
[libretro INFO] Driver: 2.0.122
[libretro INFO] Selected Vulkan GPU: AMD Radeon RX 5700
[libretro INFO] GPU supports Vulkan 1.1.
[INFO] [Vulkan]: Found GPU at index 0: AMD Radeon RX 5700
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using GPU: AMD Radeon RX 5700
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Swapchain supports present mode: 3.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 1920 x 1016.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1920x1016
[INFO] [Vulkan]: Using BGRA8888 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]: Textures:
[INFO] [slang]: Source (#0)
[INFO] [slang]:
[INFO] [slang]: Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]: Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]: MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]: Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [XInput]: Found controller, user #0
[INFO] [XInput]: Pads connected: 1
[INFO] [DINPUT]: Enumerating joypads ...
[INFO] [DINPUT]: Device #0 PID: {02E0} VID:{045E}
[INFO] [DINPUT]: Done enumerating joypads ...
[INFO] [XInput]: Attempting autoconf for "XInput Controller (User 1)", user #0
[INFO] [DINPUT]: Found XInput pad at index 0 (DINPUT index 0)
[INFO] [XInput]: Found VID/PID (045E/02E0) from DINPUT index 0 for "XInput Controller (User 1)", user #0
[INFO] [XInput]: Attempting autoconf for user #1
[INFO] [XInput]: Attempting autoconf for user #2
[INFO] [XInput]: Attempting autoconf for user #3
[INFO] [XInput]: Attempting autoconf for user #4
[INFO] [XInput]: Attempting autoconf for user #5
[INFO] [XInput]: Attempting autoconf for user #6
[INFO] [XInput]: Attempting autoconf for user #7
[INFO] [XInput]: Attempting autoconf for user #8
[INFO] [XInput]: Attempting autoconf for user #9
[INFO] [XInput]: Attempting autoconf for user #10
[INFO] [XInput]: Attempting autoconf for user #11
[INFO] [XInput]: Attempting autoconf for user #12
[INFO] [XInput]: Attempting autoconf for user #13
[INFO] [XInput]: Attempting autoconf for user #14
[INFO] [XInput]: Attempting autoconf for user #15
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: 141 profiles found.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] Found shader "A:\Games\Game Consoles\RetroArch\shaders\retroarch.slangp"
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[INFO] [Autoconf]: selected configuration: A:\Games\Game Consoles\RetroArch\autoconfig\xinput\Xbox_One_Controller.cfg
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating descriptor set layout.
[libretro INFO] Creating pipeline layout.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[libretro INFO] Creating shader module.
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Menu]: Found menu display driver: "vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0000000000B8D0C0
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "winmm" driver.
[WARN] Input device ID 5 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[libretro INFO] Controller 1: PlayStation Controller
[libretro INFO] Controller 2: PlayStation Controller
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_history.lpl].
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_music_history.lpl].
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_video_history.lpl].
[INFO] Loading history file: [A:\Games\Game Consoles\RetroArch\content_image_history.lpl].
[INFO] Loading favorites file: [A:\Games\Game Consoles\RetroArch\content_favorites.lpl].
[INFO] [Vulkan]: VSync => on
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]: Textures:
[INFO] [slang]: Source (#0)
[INFO] [slang]:
[INFO] [slang]: Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]: Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]: MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]: Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[libretro INFO] Creating render pass.
[libretro INFO] Creating render pass.
[INFO] [Vulkan]: Do not need to re-create swapchain.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]: Textures:
[INFO] [slang]: Source (#0)
[INFO] [slang]:
[INFO] [slang]: Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]: Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]: MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]: Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[libretro INFO] Creating compute pipeline.
[libretro INFO] Creating compute pipeline.
[INFO] [Vulkan]: Do not need to re-create swapchain.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]: Textures:
[INFO] [slang]: Source (#0)
[INFO] [slang]:
[INFO] [slang]: Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]: Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]: MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]: Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[libretro INFO] Creating render pass.
[libretro INFO] Creating render pass.
[libretro INFO] Creating graphics pipeline.
[libretro INFO] Creating compute pipeline.
[libretro INFO] Creating render pass.
[libretro INFO] Creating graphics pipeline.
[libretro INFO] Creating graphics pipeline.
[libretro INFO] Creating render pass.
[libretro INFO] Creating render pass.
[libretro INFO] Creating graphics pipeline.
[libretro INFO] Creating render pass.
[libretro INFO] Creating render pass.
[libretro INFO] Creating graphics pipeline.

**Comment by fragmental** [comment]
Do  you have runahead enabled?  Apparently runahead will cause PSX HW to crash, whether using vulkan or gl.  #443 

With vulkan I get the error `Exception code=0xc0000005 flags=0x0 at 0x00000000804F7FAE. Access violation - attempting to read data at address 0x0000000000000DB0`.  With GL I get the error `[libretro ERROR] [rsx_gl_prepare_frame] Renderer state marked as valid but state data is null.`

Runahead without the second instance might work.

This is mentioned under "compatibility" on the docs page https://docs.libretro.com/library/beetle_psx_hw/

**Comment by sourceAida** [comment]
> Do you have runahead enabled? Apparently runahead will cause PSX HW to crash, whether using vulkan or gl. #443
> 
> With vulkan I get the error `Exception code=0xc0000005 flags=0x0 at 0x00000000804F7FAE. Access violation - attempting to read data at address 0x0000000000000DB0`. With GL I get the error `[libretro ERROR] [rsx_gl_prepare_frame] Renderer state marked as valid but state data is null.`
> 
> Runahead without the second instance might work.
> 
> This is mentioned under "compatibility" on the docs page https://docs.libretro.com/library/beetle_psx_hw/

That fix it! Thank so you much. That issue has been plaguing me for at least two weeks now.

**Comment by fragmental** [comment]
I goofed the link to the github issue earlier, but I fixed it.  It's https://github.com/libretro/beetle-psx-libretro/issues/443
