### ISSUE TITLE
why the writing is missing?

### ISSUE THREAD

**Issue by candrapersada** [libretro/RetroArch#10020]
why the writing is missing for core ppsspp?
![game](https://user-images.githubusercontent.com/36833664/72655211-1e20df00-39c6-11ea-8eca-426b26622f0c.PNG)
![game2](https://user-images.githubusercontent.com/36833664/72655330-a1dacb80-39c6-11ea-816a-5467bb2efb16.PNG)

**Comment by ZeROOFALL** [comment]
The PPSSPP core requires assets files to be fully functional. Assets such as fonts and backgrounds that are required for memory card screens.

Read this page to get the files you need figure out where you need to place them

https://docs.libretro.com/library/ppsspp/

**Comment by RobLoach** [comment]
Mind trying the assets fix? If it persists, feel free to create an issue in the core queue instead:
https://github.com/libretro/ppsspp
