### ISSUE TITLE
(Rpi4) Changing the appearance causes the system to brick and requires reflash

### ISSUE THREAD

**Issue by CommandBlock6417** [libretro/RetroArch#10033]
## Description
Changing the appearance of the menu from xmb to anything else causes Lakka to brick and requires entire reflash.

### Expected behavior

Change the appearance from xmb to anything else.

### Actual behavior

The system bricks

### Steps to reproduce the bug

1. Enable advanced settings
2. Go to drivers > display or whatever it's called and change xmb to another option
3. Restart the raspberry
4. Your device is now bricked!

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.8

### Environment information

- OS: Lakka Rpi4

**Comment by RobLoach** [comment]
Mind posting the logs?

**Comment by CommandBlock6417** [comment]
I have upgraded to a nightly version and the bug doesn't appear anymore. Sorry but I don't have these logs. I just wanted to point this out.

**Comment by RobLoach** [comment]
Thanks!
