### ISSUE TITLE
PSP core issues and crashs

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#10039]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb
SSD 60gb

I use Lakka OS's Generic PC nightly build (11/04/2019) 

This issue has been mentioned before but without any fixes or replies so I hope this place would also be appropriate for it to be posted here.

I noticed for Metal Slug XX for **PSP** that it crashes sometimes upon mission completions and will crash if going to the Retroarch menu at times as well. Can someone clarify that PPSSPP assets help with better performance because before I never had that added to the Retroarch system PPSSPP folder before running any PSP games in the past. I do have the **assets** added now but still issues persist.

Another Issue is that movie clips durring BlazBlue **PSP** games would get to the point of having a black screen and the Retroarch/Lakka would then be rendered inoperative. I noticed another game has the same issue with movie clips, the movies are **lagging** as well. Proceeding to press the hotkeys to exit the game did not work when trying to close the content, I end up having to restart the computer.

The past nightly versions also showed missing assets from games. I also had this issue with another game when using a higher resolution. In another Rom there was text overlapping each other as well

![Blazeblue portable](https://user-images.githubusercontent.com/41243135/72722221-a7552480-3b32-11ea-924b-37a08411525f.png)

[Retroarch.log](https://github.com/libretro/RetroArch/files/4085854/Retroarch.log)

[Retroarch.log.2.txt](https://github.com/libretro/RetroArch/files/4085856/Retroarch.log.2.txt)

**Comment by gouchi** [comment]
Please try to [keep one issue](https://github.com/libretro/Lakka-LibreELEC/issues/875) at a time.
