### ISSUE TITLE
Playstation 2 core still not working for Generic PC

### ISSUE THREAD

**Issue by Gitlab1111** [libretro/RetroArch#10036]
CPU: Intel Haswell Intel© Core™ i5-4670 CPU @ 3.40GHz × 4
GPU: N/A
RAM: 4gb
SSD 60gb

Lakka OS nightly build 11/04/2009

Still don't have PS2 core working despite even dumping some bios files to the System folder. I have tried several roms before in the past and the current rom in the log is one that has worked when I had PCSX2 emulator on the Linux Desktop PC.

[Retroarch PS2.txt](https://github.com/libretro/RetroArch/files/4084159/Retroarch.PS2.txt)

[Lakka OS ps2.txt](https://github.com/libretro/RetroArch/files/4084177/Lakka.OS.ps2.txt)

**Comment by hizzlekizzle** [comment]
Play!'s compatibility is much lower than PCSX2's and many games just simply don't work. I've successfully tested Gran Turismo 3, so maybe try that one if you have it.

**Comment by gouchi** [comment]
Please check the [list of Play's compatibility](https://github.com/jpd002/Play-Compatibility/issues?q=is%3Aissue+is%3Aopen+label%3Astate-playable) for your tests.

[One issue](https://github.com/libretro/Lakka-LibreELEC/issues/780) is enough. We should continue there.
