### ISSUE TITLE
(Menu) (Ozone) Input Icons mismatching

### ISSUE THREAD

**Issue by badablek** [libretro/RetroArch#10059]
[Description of the bug]

If you go in Settings > Input > Port 1 Binds (same with Port 2 Binds, Port 3 Binds, etc.), you will see that the graphical icon does not correspond to its input name.

example :

icon = Right D-Pad
input = Left D-Pad

icon should be B, not Y
Retroarch shifts all icons by one line, so graphical icons and input names are not matching.

![image](https://user-images.githubusercontent.com/858929/73110141-9b3bdf00-3f05-11ea-9857-8d141b8b1093.png)

### Expected behavior
input and icon should match

Y icon for Y input
B icon for B input
etc.

### Actual behavior
Y icon for B button
Select icon for Y button
Start icon for Select button
etc.

### Steps to reproduce the bug
(Default settings)
Go to Settings > Input > Port 1 Binds (same with Port 2 Binds, Port 3 Binds, etc.)
Check the mismatch between the graphical icon and its input name

### Version/Commit
RetroArch: 1.8.4
Default settings

### Environment information
Nintendo Switch

**Comment by badablek** [comment]
By comparing with the Windows build, the issue is made by the "Split Joy-con x" that was added to the Switch build.

Just in case you mind...

![image](https://user-images.githubusercontent.com/858929/73119865-0fa76a00-3f68-11ea-998d-0a4a03bab758.png)

**Comment by RobLoach** [comment]
Strange... Mind updating the assets? I'm unable to reproduce on `master`.

**Comment by badablek** [comment]
Thanks for your answer.
My assets were already updated before I opened this bug report, but I did it again, just to be sure.

it comes from the latest stable official Switch release (1.8.4), from [here](https://buildbot.libretro.com/stable/1.8.4/nintendo/switch/libnx/RetroArch.7z)

SHA256 : 85BB71B685C7C25EDBFA2EE71B733F7BEF39C15BEA778C4828B9AB57B4D09E80

Like I did previously, I did not overwrite the old build : I deleted everything ("retroarch" folder at the root of my µSDCard + main retroarch .nro binary in my Switch folder) before putting the latest assets and binary.

Same result : icons and inputs do not correspond. it's shifted by one line

**Comment by jamescastells** [comment]
Same problem here. Using the last version of Retroarch on Switch.

**Comment by rsn8887** [comment]
I just made a PR that fixes the issue. The code is quite simple: PR #11180

**Comment by badablek** [comment]
Thanks rsn8887 for this fix !
