### ISSUE TITLE
Cheevos - Badges don't display?

### ISSUE THREAD

**Issue by chewvodka** [libretro/RetroArch#10053]
I'm running 1.8.4, latest build from source on RetroArena (essentially RetroPie, but running on Odroid N2 and Ubuntu).  Anyway, cheevos trigger like they should, but I don't see any of the badges.  If I go into my cheevo list, all I see are trophies (like they're hidden).  If I go into the cheevo settings, the option to display badges is set to OFF.  If I set it to ON and exit (saving the config), I can verify that the config file DOES say "TRUE" to display them, but once RetroArch starts, the setting some how reverts back to OFF.  Not sure if this is an issue because of my specific build, or if it's a problem existing more fundamentally with RetroArch.  Looking for feedback and a fix.

I can provide logs, settings files, etc, upon request.

Also, I'm not fully proficient with Github, still a newb really.  If this is inadequate information, please ask for more details and I will happily provide!

**Comment by RobLoach** [comment]
Enable Cheevos badges, make sure Menu Widgets is ON.... It should work.

Logs and settings would be helpful. We're unable to diagnose the problem without them.

**Comment by chewvodka** [comment]
I’ll double check when I get home. I’m pretty sure I have widgets on. If I go into retroarch with a game running the badges aren’t on unless I go in and turn it on. They do display if I earn one, but the list doesn’t display.

**Comment by chewvodka** [comment]
I've spent a good amount of time testing various things, and checking config files.  At first I thought the problem might be an override, but none of my config files have anything changing it.  Then I thought it might be a new setting that my default config doesn't contain, but it does.  I renamed the cfg file and let RetroArch create a brand new config, then I went through configuring it.  I can make the changes as they should be, and RetroArch DOES save these settings in the configuration file.  The problem appears to be that when RetroArch loads, it's skipping that line, almost like the program doesn't know to look for it.

I've created a log, but I don't see anything helpful in it.
[retroarch__2020_01_27__16_24_55.log](https://github.com/libretro/RetroArch/files/4119579/retroarch__2020_01_27__16_24_55.log)
Also, here is my config file. I've changed lines to say OMITTED where necessary to prevent hackers.
[retroarch.zip](https://github.com/libretro/RetroArch/files/4119585/retroarch.zip)

One possible important thing to note...  I never had this problem with 1.7.6, the last stable build we used on RetroArena.  I tried to update RetroArch to 1.8.4 to get support for PlayStation cheevos.

Here are the specific steps I'm taking to reproduce...

* Erase or rename retroarch.cfg
* Launch RetroArch (no game).
* Configure from null menu to ozone
* Settings -> Save configs on exit -> On
* Restart RetroArch
* Configure Appropriate Cheevo Settings
  * Cheevos On
  * Username
  * Password
  * Hardcore On
  * Leaderboards On
  * Badges On
  * Unofficial Off
  * Verbose On
  * Screenshot Off
* Verify that User Interface -> Widgets is ON
* Settings -> Save configs on exit -> On
* Restart RetroArch
* See that all cheevo settings are still there BUT with Badges set to OFF....
* Also see that the retroarch.cfg file still contains "cheevos_badges_enable = "true"

When a game is running, I can check the same settings..  
* User Interface -> Widgets is ON
* Cheevos -> Badges OFF (even though retroarch.cfg file is set right.
*
* Setting Badges ON when game is running, badges display correctly.

So like I said, it looks like RetroArch is loading all of the settings in the retroarch.cfg file EXCEPT the line about the badges.  But configuring RetroArch to save on exit with that setting enabled DOES create that line in the cfg file.

**Comment by chewvodka** [comment]
Just another followup.  I played a bit more cheeo stuff today.  NES console, lr-fceumm core.  When a game is playing and a cheevo is unlocked, it pops up the widget with the badge.  This is correct behavior.  But if you activate the RetroArch menu, and go to the cheevo list (to see the locked/unlocked list), this is where it doesn't show the badges.  It only shows Locked or "Hardcore" (if unlocked using hardcore mode).  The badges it shows are just trophies.

Also, is there a way to make the badge/widget display longer?  Seems to go away just a bit to fast for me.  Nothing critical, just something extra.  The big issue is with the badges displaying.

**Comment by Jamiras** [comment]
It definitely seems to be tied to the configuration setting. Badges are only displayed in the list if the setting is enabled, but are always displayed in the popup widget (as long as they've been downloaded). Downloading of badges also appears to be looking at the setting, so you must have previously downloaded the badge with the setting on for it to appear in the popup.

The default value for the setting is off, but you've already indicated that the file is correctly being updated to indicate the change was applied:
> If I set it to ON and exit (saving the config), I can verify that the config file DOES say "TRUE" to display them, but once RetroArch starts, the setting some how reverts back to OFF.

My guess is that you're building without `HAVE_XMB` defined, as the logic to read the value from the config is tied to it: https://github.com/libretro/RetroArch/blob/d3e62c62f2b9f189dd0843bbd9f0855c8d3db389/configuration.c#L1591-L1593

And you'e stated:
> Configure from null menu to ozone

This seems incorrect as both ozone and stripes attempt to handle badges in the menus. The logic to display the option specifically allows ozone:
https://github.com/libretro/RetroArch/blob/d3e62c62f2b9f189dd0843bbd9f0855c8d3db389/menu/menu_setting.c#L15486

I'm going to remove the `HAVE_XMB` check around the configuration definition.

**Comment by chewvodka** [comment]
Hey, hate to ping an old issue (25 days) but I still have this annoying problem.  Any further work being done?

**Comment by Jamiras** [comment]
Changes were made in #10154 to eliminate the dependency on HAVE_XMB. https://github.com/libretro/RetroArch/pull/10154/files#diff-55b11c8dab3e1e8a8a7998e7e9cda4fcL1591

Can you verify that this change has made its way into whatever source you're building from?

**Comment by chewvodka** [comment]
Oh cool.  I'll make a request up the chain to have the latest build available.  Using RetroArena, we'll have to update the install script to use that latest version.  I'll report back once that's done!  Thanks for the notification.

**Comment by chewvodka** [comment]
I'm still waiting to get a working patch built into the build script we use. One of our devs added a patch to fix widgets, but it didn't include anything about cheevo badges.  I tried changing it up a bit by downloading the .diff created with the changes in #10154.  Didn't work.  Iguess I still don't quite understand how all this works.

On the plus side though, it looks like I was able to figured out where the problem _might_ be coming from.  In our build script, there is a section:
'''
function build_retroarch() {
    local params=(
'''
In those params, they have a line saying '--disable_xmb'.  Just for shits and giggles,  changed it to '--enable_xmb'.  After rebuilding, I tested a game with cheevos I've unlocked.  And sure enough, it displays them!  Not sure what purpose having it set to disabled does, but apparently enabling it causes it to build with that 'HAVE_XMB' now defined.

Hopefully the changes added into #10154 will come into play going forward though.  I'm still waiting to see.

**Comment by meleu** [comment]
@chewvodka is this still an issue or can we close it?

**Comment by chewvodka** [comment]
If it's not urgent to get a response, I will check on my next day off when I have some free time.  I'm pretty sure it's solved now, as the problem was related to just the RetroArena build specifically.  But I want to make sure.  I will let you know.

**Comment by meleu** [comment]
Then I'm closing this. Feel free to reopen if it's still happening. :wink:
