### ISSUE TITLE
(Menu) Screenshot of XMB Menu

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#10058]
There have been times when I needed to explain or show something on Retroarch where a screenshot of the menu would have been helpful. The current screenshot feature only works within cores for screenshots of games only.

**Comment by Awakened0** [comment]
You can always press F to go into windowed mode, alt+print screen to capture the window and paste into some image program to save it. That captures the menu.

**Comment by Gitlab1111** [comment]
I was told to post the request here. I use Lakka OS, so I can't screenshot my xmb/retroarch menu.

**Comment by Awakened0** [comment]
Yeah, I guess you can't work around that the same way in Lakka.

**Comment by Nargash** [comment]
Is this a duplicate of #6332 ?

**Comment by sonninnos** [comment]
Yes indeed, and the menu driver should not play any role with the ability anyway, so I'll close this.
