### ISSUE TITLE
Icons of application are not shown for tvOS

### ISSUE THREAD

**Issue by marcmolla** [libretro/RetroArch#10067]
## Description

Retroarch appears without icons at Apple tvOS.

### Expected behavior

App should reference to a set of icons according the tvOS spec.

### Actual behavior

Icons are included in the packet but reference to it is broken. Patch attached for updating the reference to icons.

[diff.txt](https://github.com/libretro/RetroArch/files/4114118/diff.txt)

### Steps to reproduce the bug

1. Compile and run retroarch for tvOS

### Bisect Results

I would say that this happens since commit c24caa8f489a23821938b116f1bd3c81212295d3 (but not sure)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Last one at GitHub (36cbcb12b25f12dcbdb93206adc9f429c60d04ad)

### Environment information

- OS: tvOS
- Compiler: build using Xcode as is

**Comment by bossco79** [comment]
After installing the update, the icon is excellent, and when the application starts, a white screen. (tvOS13.4)
