### ISSUE TITLE
Old Scummvm core being installed

### ISSUE THREAD

**Issue by trebrick** [libretro/RetroArch#10079]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[whenever trying to update/install scummvm core in latest retroarch, it installs version 2.0 instead of 2.1]

### Expected behavior

[Entering core updater and choosing scummvm should download and install scummvm 2.1.0]

### Actual behavior

[Scummvm 2.0 is installing]

### Steps to reproduce the bug

1. [At the main menu select online updater]
2. [Choose core updater and select scummvm]
3. [Once installed, go back to main menu, select load core and choose scummvm ]

### Bisect Results

[Only noticed because retroarch 1.4 on an old phone installs scummvm 2.1]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.8.4]

### Environment information

- OS: [ios 12.4]
- Compiler: [Clang/llvm 11.0.0]

**Comment by RobLoach** [comment]
Mind making an issue in the ScummVM queue? https://github.com/libretro/scummvm/issues

**Comment by trebrick** [comment]
> Mind making an issue in the ScummVM queue? https://github.com/libretro/scummvm/issues

I will but seems theres not much traffic over there. And its not a scummvm issue its a retroarch issue

**Comment by RobLoach** [comment]
It's because the core isn't being built properly on those platforms.

**Comment by trebrick** [comment]
Well at least i finally hav an answer thanks. So the core for scumm 2.1 isnt being built right so it reverts to 2.0? And so just gotta wait till someone fixes it? Thanks
