### ISSUE TITLE
SwitchRes creating modelines on the wrong device with xrandr

### ISSUE THREAD

**Issue by lixoman100** [libretro/RetroArch#10086]
## Description

When using switchres on Linux, the modelines are created on the wrong device.

My computer reports 4 devices on xrandr:
- LVDS-1, connected primary, my laptop screen
- VGA-1, connected, my CRT TV. It has monitor index 2, which is set on RetroArch. RetroArch correctly sends its output to this screen.
- HDMI-1 disconnected
- HDMI-2 disconnected

Whenever I attempt to use SwitchRes, the custom resolutions are added via xrandr to the HDMI-2 device instead of being created on the VGA-1 device, which makes them unusable and the VGA-1 device ends up not being correctly set up.

### Expected behavior

I expected the resolutions to be created on the VGA-1 device, monitor index 2, which is the one set up and in use by RetroArch.

### Actual behavior

The resolutions were created under HDMI-2, which made them not available and not working for the VGA-1 device.

You can see the xrandr output here with the CRT resolution filed under the wrong device:
![Screenshot_2020-01-31_23-54-47](https://user-images.githubusercontent.com/5383882/73586013-8e2f6a80-4486-11ea-89cc-326bc2da0403.png)

The HDMI-2 device has NO registered modelines before RetroArch is run (it looks exactly like the HDMI-1 device listing).

### Steps to reproduce the bug

1. Turn on SwitchRes, or start RetroArch with SwitchRes already on.

### Version/Commit

- RetroArch: 1.8.4, build date Jan 18 2020, Git version 9e25601

### Environment information

- OS: Linux Mint 19.3 Tricia, with all updates installed

**Comment by lixoman100** [comment]
Further testing: If I set my VGA-1 device as primary with xrandr (moving it to monitor index 1 and moving my LVDS-1 screen to monitor index 2) and I select monitor index 1 for RetroArch, it works with no problems. I think there's a problem with SwitchRes that causes it to fixate on the device that has "2" in its name because that is the monitor index selected.

**Comment by Nikoh77** [comment]
Hi @lixoman100, I did as you said but now RA run (on my CRT) very very slowly, unusable... some ideas?

**Comment by alphanu1** [comment]
@lixoman100 they way CRTSwitchRes is setup to use outputs, is the hardware index. So if you have set index 2  it will use your 3rd hardware output. If you choose index 0 it will use your 1st hardware output. 

So, in your case. Looking at the image you vave supplied. It should be the following. however, setting your CRT to be the primary display has always been the goal for CRTSwitchres.

VGA-1 - index 0
HDMI-1 - index 1
HDM1 - index 2

However, this may not be the case as I cannot see is you have any other hardware outputs on your card from that image.

CRTSwitchRes was never designed to work in a multi display enviroment. Every Linux system can be setup in a multitude of ways.

**Comment by Nikoh77** [comment]
It's the same for me, below my xrandr:

Screen 0: minimum 320 x 200, current 3280 x 1440, maximum 16384 x 16384
DisplayPort-0 connected primary 2560x1440+0+0 (normal left inverted right x axis y axis) 553mm x 311mm
   2560x1440     59.95*+
   2048x1152     60.00  
   1920x1200     59.88  
   1920x1080     60.00    50.00    59.94    30.00    25.00    24.00    29.97    23.98  
   1600x1200     60.00  
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.95  
   1200x960      59.99  
   1280x800      59.95  
   1152x864      75.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    60.00  
   800x600       75.00    60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    60.00    59.94  
   720x400       70.08  
HDMI-A-2 disconnected (normal left inverted right x axis y axis)
DVI-D-0 disconnected (normal left inverted right x axis y axis)
VGA-1-1 connected 720x576+2560+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1024x768      60.00  
   800x600       60.32    56.25  
   848x480       60.00  
   640x480       59.94  
   720x576x25.00  50.00* 
   720x288x50.08  50.08  
   700x480_59.941002  59.94  
HDMI-1-1 disconnected (normal left inverted right x axis y axis)
HDMI-1-2 disconnected (normal left inverted right x axis y axis)
  1024x768 (0x70) 65.000MHz -HSync -VSync
        h: width  1024 start 1048 end 1184 total 1344 skew    0 clock  48.36KHz
        v: height  768 start  771 end  777 total  806           clock  60.00Hz
  800x600 (0x72) 40.000MHz +HSync +VSync
        h: width   800 start  840 end  968 total 1056 skew    0 clock  37.88KHz
        v: height  600 start  601 end  605 total  628           clock  60.32Hz
  640x480 (0x78) 25.175MHz -HSync -VSync
        h: width   640 start  656 end  752 total  800 skew    0 clock  31.47KHz
        v: height  480 start  490 end  492 total  525           clock  59.94Hz
  720x576x25.00 (0x6fe) 13.875MHz -HSync -VSync Interlace
        h: width   720 start  744 end  808 total  888 skew    0 clock  15.62KHz
        v: height  576 start  586 end  592 total  625           clock  50.00Hz
  720x288x50.08 (0x6ff) 13.875MHz -HSync -VSync
        h: width   720 start  744 end  808 total  888 skew    0 clock  15.62KHz
        v: height  288 start  293 end  296 total  312           clock  50.08Hz
  700x480_59.941002 (0x700) 13.850MHz -HSync -VSync Interlace
        h: width   700 start  742 end  801 total  867 skew    0 clock  15.97KHz
        v: height  480 start  490 end  496 total  533           clock  59.94Hz

**Comment by Nikoh77** [comment]
Hi @alphanu1 some news? :-(

**Comment by DukeSkinny** [comment]
This seems to be my exact problem as well. Funny thing is, using CRTSwitchres with my dual monitor setup works great in Windows, and actually used to work in my current Manjaro system.

Except I have absolutely no way of making it work. No monitor index value will do the trick.

**Comment by lixoman100** [comment]
This issue is no longer relevant with the new implementation of switchres on https://github.com/libretro/RetroArch/pull/12403. Closing issue.
