### ISSUE TITLE
LZMA zip compressed ROMs not extracted, fail to load

### ISSUE THREAD

**Issue by ner00** [libretro/RetroArch#10083]
## Description

LZMA zip compressed ROMs are not unpacked when launching the engine.
I did a few tests with Genesis games, but I tested 3 different engines and none worked, the ROM was never extracted. I don't know if this task falls on the engine or if it is actually RA which prepares it beforehand, I would assume the latter.

### Expected behavior

Extract the ROM as with Deflate compression, and allow the ROM to be loaded by the engine. 

### Actual behavior

ROM is not extracted from zip archive and engine fails to load it. Oddly, the LZMA archive can be browsed inside RA (Browse Archive). Side note, Pico and Beat engines return to the menu with a 'failed to load' error while Genesis Plus GX shows a black screen and does nothing.

### Steps to reproduce the bug

1. Pack MD/Genesis ROM with LZMA compression;
2. Load content in RetroArch;
3. RA fails to extract ROM, engine cannot load it.

### Bisect Results

Have not tried previous versions, I assume this is either missing by design or because no one ever mentioned it.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.4/f425d8dc8b

### Environment information

- OS: Windows 10 1903

**Comment by bslenul** [comment]
I can't reproduce, I tried compressing a MD rom using 7-zip with LZMA (also tried LZMA2) and the rom is properly extracted and read on load (tested with GPGX, PicoDrive and BlastEm cores).

My version of RA is more recent than yours however (36cbcb12b2), so maybe it was an issue that's already fixed?

**Comment by ner00** [comment]
@bslenul Thanks for your reply. I tried a nightly, but the issue persists. I believe that I wasn't specific enough. I was talking about zip format in particular, not 7z. I only picked up on you having tested with 7z format because you mentioned that you also tried LZMA2, which is not available as a compression method for zip archives in 7zip.

To clarify:

- 7z (LZMA/LZMA2) unpacks and works fine;

- zip (LZMA) does NOT unpack, core fails to load.

Additionally, among all Genesis cores tested, Genesis GX Plus was the only one which didn't seem to have a status information about the unpacking having failed since it freezes and does not return to the menu on its own.

@bslenul Can you test this and give some feedback again? Thanks in advance.

**Comment by bslenul** [comment]
Ah my bad! Tested in .zip format with LZMA and yup, I also get a black screen + no extracted rom in my cache folder.

**Comment by hasenbanck** [comment]
Retroarch uses ZLIB to decompress ZIP files. ZLIB only support DEFLATE. ZIP files that don't use DEFLATE are actually not widely supported, as most implementation only properly implement RFC1950.

If you want to use the LZMA compression, I would suggest you to stick to 7z, since we use the 7zip library to decode those.

**Comment by ner00** [comment]
> Retroarch uses ZLIB to decompress ZIP files. ZLIB only support DEFLATE. ZIP files that don't use DEFLATE are actually not widely supported, as most implementation only properly implement RFC1950.

I knew there had to be a good reason, just wasn't sure why.

I have no issue using 7z if I want to use LZMA/2, it was just a curiosity that came to me because I scratched my head for a while until I found out why this particular ROM was not being loaded. 

Anyway, this answers the question completely, thanks.
