### ISSUE TITLE
Russian translation - some lines are missing

### ISSUE THREAD

**Issue by teorex3** [libretro/RetroArch#10098]
did not find some lines in this file: https://github.com/libretro/RetroArch/blob/master/intl/msg_hash_ru.h

MSG_HASH not found

- Show Desktop Menu
- Opens the desktop menu if closed
- Restart the program
- Install a core from the online updater.
- Install or restore a core from the downloads directory.
- Manual Scan
- Configurable scan based on content filenames. Does not require content to match the database.
- Update Installed Cores
- Update all installed cores to the latest version available.
- Playlist Thumbnails Updater
- Download individual thumbnails for each entry of selected playlist.
- On-Demand Thumbnail Downloads
- Automatically download missing thumbnail images while browsing playlists. Has a severe performance impact.
- CPU Model:
- Metal Support:
- CoreAudio Support:
- CoreAudio V3 Support: 
- mpv Support:
- Reset To Defaults
- Reset the current configuration to default values.
- You can use the following controls below on either you gamepad or keyboard in order to control the menu:
- File Browser
- AI Service
- Change settings for the AI Service (Translation/TTS/Misc).
- Accessibility
- Change settings for the Accessibility narator.
- Power Management
- Change power management settings.
- MIDI driver to use.

and many others, can anyone fix it?

**Comment by RobLoach** [comment]
Feel free to submit a Pull Request with the updates. I don't think anyone is actively maintaining the Russian translation, so have at it. :+1:
