### ISSUE TITLE
Retroarch Crashes on Startup

### ISSUE THREAD

**Issue by jeflinus** [libretro/RetroArch#10105]
Retroarch crashes in Debug mode on startup, regular retroarch hangs for about 3 minutes on a white non responding screen then boots, 

Windows 10 64 bit, Ryzen 7 1700 Eight-Core 3.00 GHz, Nvidia GTX 1080 

Graphics drivers fully updated, tried nightly and stable builds, switched from opengl to multiple other video drivers, the issue still persisted.
-------------------

> Error occurred on Thursday, February 6, 2020 at 16:22:54.
> 
> retroarch_debug.exe caused an Access Violation at location 00000000007D5B5E in module retroarch_debug.exe Reading from location 0000000000000000.
> 
> AddrPC           Params
> 00000000007D5B5E 0000000000000000 0000000000000000 0000000000000000  retroarch_debug.exe!D3D12EnableDebugLayer  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/gfx/common/d3d12_common.h @ 942]
> 00000000007D6056 00000000109AD630 0000000010973629 0000000001226620  retroarch_debug.exe!d3d12_init_base  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/gfx/common/d3d12_common.c @ 167]
> 00000000007D1EC7 000000000A11F550 0000000001226620 0000000001226628  retroarch_debug.exe!d3d12_gfx_init  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/gfx/drivers/d3d12.c @ 940]
> 0000000000427CDE 000000000A11F5EF 0000000000000000 000000000000000B  retroarch_debug.exe!video_driver_init_internal  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 20774]
> 000000000042D3E1 00000000000003FF 00000000011FF348 0000000000CDDA61  retroarch_debug.exe!drivers_init  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 23427]
> 0000000000432612 0000000000000001 000000000EEA0000 0000000000000000  retroarch_debug.exe!retroarch_main_init  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 25578]
> 000000000044E64B 000000000A11FD40 0000000000000000 0000000000000000  retroarch_debug.exe!content_load  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 618]
> 000000000045102E 000000000A11FD40 0000000000000001 0000000000000001  retroarch_debug.exe!task_load_content_callback  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 2041]
> 0000000000451243 0000000000000000 0000000000000000 000000000A11FD40  retroarch_debug.exe!task_push_load_content_from_cli  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/tasks/task_content.c @ 2122]
> 000000000040D70B 0000000000000001 000000000EEA0000 0000000000000000  retroarch_debug.exe!rarch_main  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/retroarch.c @ 8186]
> 000000000057BF97 0000000000000001 000000000EEA0000 000000000A2A2A66  retroarch_debug.exe!SDL_main  [C:/msys64/home/buildbot/buildbot/windows_x64/retroarch/ui/drivers/qt/ui_qt_application.cpp @ 150]
> 0000000000AAED4E 0000000000000000 0000000000000027 0000000001A14038  retroarch_debug.exe!main_getcmdline
> 00000000004013B4 0000000000000000 0000000000000000 0000000000000000  retroarch_debug.exe!__tmainCRTStartup  [E:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 339]
> 00000000004014DB 0000000000000000 0000000000000000 0000000000000000  retroarch_debug.exe!WinMainCRTStartup  [E:/mingwbuild/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c @ 195]
> 00007FFF7B3D7BD4 0000000000000000 0000000000000000 0000000000000000  KERNEL32.DLL!BaseThreadInitThunk
> 00007FFF7C44CED1 0000000000000000 0000000000000000 0000000000000000  ntdll.dll!RtlUserThreadStart
> 
> retroarch_debug.exe
> ntdll.dll   	10.0.18362.418
> KERNEL32.DLL	10.0.18362.329
> KERNELBASE.dll	10.0.18362.535
> apphelp.dll 	10.0.18362.1
> ADVAPI32.dll	10.0.18362.329
> msvcrt.dll  	7.0.18362.1
> sechost.dll 	10.0.18362.267
> RPCRT4.dll  	10.0.18362.476
> comdlg32.dll	10.0.18362.418
> combase.dll 	10.0.18362.449
> ucrtbase.dll	10.0.18362.387
> bcryptPrimitives.dll	10.0.18362.295
> shcore.dll  	10.0.18362.1
> USER32.dll  	10.0.18362.592
> win32u.dll  	10.0.18362.592
> GDI32.dll   	10.0.18362.1
> gdi32full.dll	10.0.18362.535
> msvcp_win.dll	10.0.18362.387
> SHLWAPI.dll 	10.0.18362.1
> SHELL32.dll 	10.0.18362.535
> COMCTL32.dll	5.82.18362.592
> cfgmgr32.dll	10.0.18362.387
> windows.storage.dll	10.0.18362.535
> profapi.dll 	10.0.18362.1
> powrprof.dll	10.0.18362.1
> UMPDC.dll
> kernel.appcore.dll	10.0.18362.1
> cryptsp.dll 	10.0.18362.1
> ole32.dll   	10.0.18362.113
> SETUPAPI.dll	10.0.18362.1
> HID.DLL     	10.0.18362.1
> DINPUT8.dll 	10.0.18362.1
> DSOUND.dll  	10.0.18362.1
> bcrypt.dll  	10.0.18362.267
> WS2_32.dll  	10.0.18362.387
> IPHLPAPI.DLL	10.0.18362.1
> MSIMG32.dll 	10.0.18362.175
> libwinpthread-1.dll	1.0.0.0
> OPENGL32.dll	10.0.18362.387
> WINMM.dll   	10.0.18362.1
> libstdc++-6.dll
> libass-9.dll
> avformat-58.dll	58.29.100.0
> avutil-56.dll	56.31.100.0
> libcaca-0.dll
> avcodec-58.dll	58.54.100.0
> cgGL.dll    	3.1.0.13
> cgD3D9.dll  	3.1.0.13
> cg.dll      	3.1.0.13
> libfreetype-6.dll	2.10.1.0
> libopenal-1.dll
> Qt5Core.dll 	5.13.2.0
> Qt5Network.dll	5.13.2.0
> CRYPT32.dll 	10.0.18362.592
> SDL2.dll    	2.0.10.0
> MSASN1.dll  	10.0.18362.1
> IMM32.dll   	10.0.18362.387
> libssl-1_1-x64.dll	1.1.1.4
> OLEAUT32.dll	10.0.18362.535
> swresample-3.dll	3.5.100.0
> swscale-5.dll	5.5.100.0
> libusb-1.0.dll	1.0.23.11397
> winmmbase.dll	10.0.18362.1
> GLU32.dll   	10.0.18362.387
> libfontconfig-1.dll
> libfribidi-0.dll
> libgcc_s_seh-1.dll
> libharfbuzz-0.dll
> libbluray-2.dll
> libbz2-1.dll
> libmfx-1.dll
> librtmp-1.dll
> libmodplug-1.dll
> libsrt.dll
> zlib1.dll
> libcelt0-2.dll
> libgsm.dll
> liblzma-5.dll	5.2.4.0
> libmp3lame-0.dll
> libopencore-amrnb-0.dll
> libopus-0.dll
> libspeex-1.dll
> libtheoradec-1.dll
> libtheoraenc-1.dll
> libvorbis-0.dll
> libvorbisenc-2.dll
> libwavpack-1.dll
> libvpx-1.dll
> libwebp-7.dll
> libwebpmux-3.dll
> libx264-157.dll	0.157.2970.0
> libpng16-16.dll
> MPR.dll     	10.0.18362.1
> NETAPI32.dll	10.0.18362.1
> USERENV.dll 	10.0.18362.387
> VERSION.dll 	10.0.18362.1
> libicuuc65.dll
> libpcre2-16-0.dll
> libzstd.dll
> libcrypto-1_1-x64.dll	1.1.1.4
> DNSAPI.dll  	10.0.18362.267
> NSI.dll     	10.0.18362.449
> libintl-8.dll	0.19.8.0
> libexpat-1.dll
> USP10.dll   	10.0.18362.476
> libgraphite2.dll
> libxml2-2.dll
> libgmp-10.dll
> libhogweed-5.dll
> WSOCK32.dll 	10.0.18362.1
> libogg-0.dll
> dxcore.dll  	10.0.18362.1
> exchndl.dll 	0.9.2.0
> PSAPI.DLL   	10.0.18362.1
> mgwhelp.dll 	0.9.2.0
> dbghelp.dll 	10.0.18362.1
> dbgcore.DLL 	10.0.18362.1
> Qt5Gui.dll  	5.13.2.0
> Qt5Widgets.dll	5.13.2.0
> libiconv-2.dll	1.16.0.0
> libgnutls-30.dll
> libopencore-amrwb-0.dll
> libopenjp2-7.dll
> libx265.dll 	3.2.0.1
> xvidcore.dll
> libdouble-conversion.dll
> libicuin65.dll
> libglib-2.0-0.dll	2.62.2.0
> libnettle-7.dll
> libicudt65.dll
> libidn2-0.dll
> libtasn1-6.dll
> dwmapi.dll  	10.0.18362.267
> UxTheme.dll 	10.0.18362.449
> CRYPTBASE.DLL	10.0.18362.1
> NETUTILS.DLL	10.0.18362.1
> SRVCLI.DLL  	10.0.18362.1
> libp11-kit-0.dll
> libunistring-2.dll	0.9.10.0
> libpcre-1.dll
> libffi-6.dll
> ncrypt.dll  	10.0.18362.1
> NTASN1.dll  	10.0.18362.1
> rsaenh.dll  	10.0.18362.1
> inputhost.dll	10.0.18362.387
> CoreUIComponents.dll	10.0.18362.207
> PROPSYS.dll 	7.0.18362.267
> wintypes.dll	10.0.18362.449
> CoreMessaging.dll	10.0.18362.1
> ntmarta.dll 	10.0.18362.1
> Start10_64.dll	1.8.0.1
> FencesMenu64.dll	3.0.9.11
> WTSAPI32.dll	10.0.18362.1
> gdiplus.dll 	10.0.18362.592
> MSCTF.dll   	10.0.18362.535
> TextInputFramework.dll	10.0.18362.267
> iertutil.dll	11.0.18362.449
> AppHook64_9C68FAD7-EB58-4A5D-AA05-FCBE25FC6E28.dll	9.6.0.6
> DEVOBJ.dll  	10.0.18362.387
> WINTRUST.dll	10.0.18362.387
> xinput1_4.dll	10.0.18362.329
> d3d12.dll   	10.0.18362.267
> 
> Windows 10.0.18362
> DrMingw 0.9.2
>

**Comment by RobLoach** [comment]
Delete your retroarch.cfg and try again?

**Comment by jeflinus** [comment]
I deleted it, uninstalled and reinstalled and I'm still having the same issue, I searched around and found some people posting about corsair keyboards maybe having to do with this kind of issue

**Comment by twinaphex** [comment]
List the exact keyboard you have.

**Comment by jeflinus** [comment]
Corsair Strafe RGB Mk1

**Comment by twinaphex** [comment]
Yeah that's a bit too expensive for us to purchase for the purposes of debugging it. Perhaps if somebody gifts it we could consider looking at it ourselves.

**Comment by jeflinus** [comment]
Ok, thanks for the non solution

**Comment by twinaphex** [comment]
See above, any dev that owns this hardware can send a PR.
