### ISSUE TITLE
gpSP for GBA roms not working with BIOS 

### ISSUE THREAD

**Issue by narcissubox** [libretro/RetroArch#10103]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[I just don't know why I can not use gpSP in Lakka on raspberry pi zero. They said I need bios in system folder, but I tried and its not work. After I put the bios in sytem folder, I open one GBA rom with gpSP core, then black screen and then back to menu. It's just can not run rom with gpSP. mGBA is working but laggy on raspberry pi zero.]

### Expected behavior

[gpSP should work when we have gba_bios.bin in system folder]

### Actual behavior

[load the rom then black screen then quit to menu.]

### Steps to reproduce the bug

1. [Install brand new lakka]
2. [put bios file into storage/system folder]
3. [open the GBA rom with gpSP emulator]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [Lakka 2.3.2]
- Compiler: [In case you are running local builds]

**Comment by narcissubox** [comment]
I tried many times and now just flash SD to retropie, I can use gpSP with bios file. But I really like lakka, retroarch interface is very easy to use, I hope you can fix the bug, really thank you!

**Comment by narcissubox** [comment]
I found the answer, you need to replace the gpsp_libretro.so file because the original file seems to been broken in Lakka 2.3.2 on raspberry pi zero version.

**Comment by bailey293** [comment]
> I found the answer, you need to replace the gpsp_libretro.so file because the original file seems to been broken in Lakka 2.3.2 on raspberry pi zero version.

What did you replace the file with? I am currently experiencing this issue.
