### ISSUE TITLE
[Android] Latest nightly, all cores crashing/loud white noise

### ISSUE THREAD

**Issue by WindyWinston** [libretro/RetroArch#10101]
## Description

Just updated to the latest nightly (Feb 5th). I have 4 cores on my device, PUAE and Fuse instantly crash when loading content. Vice and Mame2003plus have loud white noise. I last updated Retroarch a few weeks ago and it worked fine.
38b486e I think.
### Expected behavior

Cores run without issues.

### Steps to reproduce the bug

I updated Retroarch to the latest nightly.

### Version/Commit

Retroarch Nightly 5th Feb 51964ee

### Environment information

Android 4.4.4

**Comment by twinaphex** [comment]
You need to report this on the Github issues osge of the libretro cores themselves, not RetroArch.

**Comment by WindyWinston** [comment]
The cores were fine before I updated Retroarch.

**Comment by WindyWinston** [comment]
@twinaphex I've narrowed it down and it seems to be related to the opensl audio driver. Have you changed this recently ? If I set it to rsound I get no sound but it doesn't crash.

**Comment by twinaphex** [comment]
Pushed a commit, either compile from source or wait a day until a new nightly build arrives on the buildbot.

**Comment by WindyWinston** [comment]
Same thing happens i'm afraid (2 cores crash and other 2 have loud white noise for audio). As I say, if I change the audio driver to 'rsound' it stops the crashing but no sound (my default has always been opensl). It worked fine on the build I was using before which I think was https://github.com/libretro/RetroArch/commit/38b486eb6b2c6d1c134c051ca8af3107a91a42ee

**Comment by WindyWinston** [comment]
I've narrowed it down for you. From the buildbot Feb 2nd 28b2a34 works, Feb 3rd onwards don't.

**Comment by twinaphex** [comment]
Tried the latest trunk on an Android phone (S10+) - I get no loud white noise issues with MAME 2003 Plus running killer instinct for instance. 

Can you bisect it further until you find the offending commit? I am unfortunately not able to reproduce here.

**Comment by twinaphex** [comment]
Only thing I can possibly poinpoint is the resampler changes - see if this fixes it -

https://github.com/libretro/RetroArch/commit/dce610747b6c1c8d6aa4c839c0d16b26512f6068

**Comment by WindyWinston** [comment]
Haven't tried yet, waiting for buildbot. @jdgleaver is also experiencing this on Android. I asked him in one of the libretro-uae issues as I thought it was something to do with the latest notifications update he did. Retroarch crashes as soon as you run a game in libretro-uae and libretro-fuse. I don't have any other cores.

**Comment by WindyWinston** [comment]
Seems to be fixed! Thanks.
