### ISSUE TITLE
Savestate freeze Oddworld Abe's Oddysee - Retroarch Switch

### ISSUE THREAD

**Issue by Ataraxia13** [libretro/RetroArch#10113]
## Description

I'm using the latest stable version of Retroarch for Switch
I have an error with the savestate function while playing "Oddworld Abe Oddysee" with PCSX ReArmed
I can normally save the state of the game but everytime I load it, the game freeze leaving only the music going on

### Expected behavior

Loading the save state normally

### Actual behavior
Game freeze after 1s the save is loaded and just leave the music going on in the bg

### Steps to reproduce the bug

1. Emulate the game with PCSX ReArmed
2. Save State
3. Load State
4. Wait 1s
5. Now it's frozen

### Version/Commit
You can find this information under Information/System Information

- Git version: 2e0f921
### Environment information

- OS: Switch CFW -Atmosphere

**Comment by m4xw** [comment]
Use the appropriate repository please.
This isn't a RA Issue.

**Comment by RobLoach** [comment]
https://github.com/libretro/pcsx_rearmed_switch/issues
