### ISSUE TITLE
RFE: Option for the Manual scanner to not add files not on 'arcade dat'.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#10116]
### Description

I scan retroplay whdload (amiga) games with the source dat and manual scan, since they have no name on the lr-database dats.

First, prior to the scan outside RA, i do some bash pre-processing to remove non-english languages. This works fine, and they *all* get removed from the dat.

I expected to be able to ignore the other files, but they get added anyway. Would it be possible to add a default toggle that is disabled if there is no 'Arcade Dat' given (btw, this probably should have a different name) that disables adding 'unknown' files?

### Expected behavior

If you provide a 'arcade dat' there should be a option to only take the names and dir structure from there, filtering all files not there. Since the case where you want to scan 'extra' files when you're giving a dat is the more unusual one, that option should default to true (not a big deal since it would only be active with a dat given).

### Actual behavior

Missing option causes all files not recognized to have original names (not a big deal if you wanted to add them) and no option to not add unrecognized roms (by default when using a dat, if possible).

### Steps to reproduce the bug

1. extract this: [test.zip](https://github.com/libretro/RetroArch/files/4201453/test.zip)
2. perform a manual scan using the dat inside the folder as 'Arcade dat' like so:
![image](https://user-images.githubusercontent.com/757900/74482613-c7b39d00-4eac-11ea-9c24-1ba6fbba4aac.png)
3. verify that `Hugo_v1.0_Es_Spanish_hack_by_K-teto.lha` gets added to the new playlist in spite of not being in the dat

in that zip, the two 'game' files are truncated to 0, so they're not real games.
in that zip, the 'dat' only has info about a single game, that is not 'hugo'.

### Bisect Results

not relevant since this is a RFE

### Version/Commit

- RetroArch: v1.8.4 59d6ad6b05

### Environment information

- OS: Linux AIVAS 5.0.0-38-generic #41-Ubuntu SMP Tue Dec 3 00:27:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Compiler: GCC (8.3.0) 64-bit Built: Feb 13 2020

**Comment by i30817** [comment]
Mmm, i've been looking at the code to implement this and i see i've been misunderstanding the 'Arcade Dat' feature.

For one it appears to be wholly oriented to arcade dats. I *could* adapt the dats i'm thinking off to that scheme and that's probably what i'm going to do to add the feature to 'filter files not on dat' 'minimally'; and i'm probably going to remove the weird filter it has in `if (path_is_compressed_file(content_path)) /*only do it then*/` which is both replaced by a setting to filter out 'files not on the dat'.

**Comment by hizzlekizzle** [comment]
@jdgleaver implemented the manual scanning, IIRC. Do you have any thoughts on this, jdgleaver? (that is, before i30817 spends the time working on it)

**Comment by jdgleaver** [comment]
While this is a feature that I personally don't want (the main point of the manual scanner is to include all content, and I believe that content files should be properly organised/culled at source), @i30817 is not the first to request this - so sure, I will implement it.

I am hugely overworked at the moment, however, and the thought of another feature request is enough to make me cry. Could you please wait a week or so for me make a start on this? I should have some time then.

**Comment by i30817** [comment]
I already have most of the 'plumbing code' code except for the translations. I'm currently blocked on implementing the 'actual feature'. I know what i've got to do, but i want to have a use case ready, so i'm working on transforming the retroplay dats into something 'like' the mame format, to see if it can occur like i want to test it out

I don't think it's a good idea to deviate from that format either.

Anyway that work might actually lead to a script PR to libretro-database, because i'm trying to make it so that the 'description' holds the x-name of (most well named) WHDLoads in the openretro-database, that then can be used (hopefully) to find the 'real name' of the game, and 'images', either by import of the images into libretro-database, or seeing if the openretro-database 'real name' is the same as the 'real name' on the libretro-database amiga images.

**Comment by jdgleaver** [comment]
@i30817 Ah, okay - sounds like you've made a good start there, and a retroplay database would be awesome :)

Could I please make two requests, though?

- I would very much prefer it if the option to *exclude* content not in the dat file were disabled by default. The vast majority of users will be scanning arcade content, and they will want all of their files to be included in the resultant playlist (even if the names are 'wrong'). We don't want to go back to having novice users spamming us with 'where are my games?' bug reports because they didn't change a default option.

- I agree that the 'compressed file' filter is limiting, but the intention there was to reduce the number of lookups in the event the user tries to scan a directory full of junk, or forgets to clear the dat file setting before scanning other types of content (searching that XML file is somewhat expensive). If we're going to make this generic, then it would be good to have a method for knowing in advance what types of file are valid. Maybe this could be added as an extension to the dat file format (a new tag in the header)? i.e. if a user loads a normal MAME or FBNeo dat (without the tag) then it'll fall back to compressed files, whereas your retroplay dat could explicitly state '.lha', '.hdf' or '.hdz'.

**Comment by i30817** [comment]
It's all a bit unoptimal - the main reason i want this is because i want other people to do things like 'dats for only fighting games' or 'dats only for english games on a heterogeneous collection', making things have another required top-level tag is a bit heavy duty for something i'd expect to be 'generic', unless the check can be inverted to 'this is a MAME dat, so it always filters out non-compressed roms'.

Speaking of that If you look at redump dats and MAME dats side by side a pattern emerges:

redump (psp):
```
	<game name="0-Ji no Kane to Cinderella - Halloween Wedding (Japan) (v1.01)">
		<description>0-Ji no Kane to Cinderella - Halloween Wedding (Japan) (v1.01)</description>
		<rom name="0-Ji no Kane to Cinderella - Halloween Wedding (Japan) (v1.01).iso"  .../>
	</game>
```
```
	<machine name="20pacgal" sourcefile="20pacgal.cpp">
		<description>Ms. Pac-Man/Galaga - 20th Anniversary Class of 1981 Reunion (V1.08)</description>
		<rom name="ms_pac-galaga.u14" ..../>
		<rom name="ms_pac-galaga_v1.08.u13" .../>
                ....
	</machine>
```

The check is AFAICT finding 'machine' to match it to the filename of the rom minus extension, and on match, getting the 'description' as a libretro-database key.

If you could transform this to:
```
for all 'descriptions':
   if it has at least 1 'room' neighbor:
        find find the 'parent' name and match it to the filename:
             return the description as label
return nil
```
The requirement of 'this has to be a arcade dat' could be relaxed. If a check could be found which will work (in the headrs) to identify a 'arcade' dat, it could still do those checks and filtering of non-compressed files.

I don't have FBA-neo dats to check... the 'original' mame header is like this:
```
	<header>
		<name>Arcade MAME</name>
		<description>Arcade 0.218 (Jan 29 2020)</description>
		<category>Emulation</category>
		<version>0.218</version>
		<date>29/01/2020</date>
		<author>AntoPISA</author>
		<email>progettosnaps@gmail.com</email>
		<homepage>http://www.progettosnaps.net/</homepage>
		<url>http://www.progettosnaps.net/dats/MAME/</url>
		<comment>-</comment>
		<clrmamepro/>
	</header>
```

'<clrmamepro/>' doesn't prove anything ofc, but maybe the url coming from the mame dat source? Meh.

**Comment by i30817** [comment]
Actually never mind about that 'pattern'. I forgot that redump multi-disc games place the disk as the 'rom' and that holds the 'real' filename (minus the (Disc 1) metadata).

For this to work there, you'd have to either replace the check for the filename to not use the 'parent name' or chop off more than the 'extension' until it matches the 'parent name' or not.

**Comment by i30817** [comment]
So here is my 'tentative' plan for posterity and/or I burn out:

1. get a boolean way up in the callstack where the dat is parsed - so it's only done once - that distinguishes a 'arcade' dat from other systems dats and pass that boolean alongside the dat structure.
Reason is performance, because calling the dat a extra time each file does not sound sane right?
2. On `manual_content_scan_get_playlist_content_label` before the compressed file filter, add a branch for 'is arcade dat or not' using that boolean. The both branches would use the other boolean about 'add everything or filter from dat' default false. The compressed file filter is not a big deal for arcade because its dats only have compressed files, and for the else branch of 'not a arcade dat' it can be ommited.
3. parsing the dat on non arcade case will require a different function in logiqx.c maybe, iterating over roms tags to find filenames to match (without extension again), then finding either the neighbor 'description' or maybe the 'parent' name, which is better will require research.
3. remove references to 'Arcade dat' on the buttons and mark the translations i don't know how they work as needing a update (i don't know how to do this btw).

**Comment by i30817** [comment]
Yeah, i think i'm going to give up on this. The idea requires extra generalization of the dat parsing which introduces hacks because RA never choose the same kind of format for its playlists as everyone else. 

I'm actually getting stressed rethinking about all the things i disagree with in the scanner that would interfere with this. Filenames-as-ids, multiple-cd-in-playlist-not-games, database-massaging-redump-names-that-work-on-linux-to-appease-windows-instead-of-doing-that-at-runtime-on-windows.

**Comment by jdgleaver** [comment]
Yeah, the difficulties here are non-trivial (hence my rather stressed first response to the feature request! I knew it would be hard...)

I do understand your frustrations - there's a lot of legacy stuff here, and only so much manpower to fix things. I already work 35 hours a week on RetroArch (every week for the last 18 months now), and I barely scratch the surface.

I'm still going to implement the 'filter content based on dat' option (straightforward), and I'll think about making the dats more general in scope - at least as an option for advanced users. My schedule is really full at the moment, though, so I'll try to get around to this in a week or two.
