### ISSUE TITLE
Retroarch is not compiling atm in ubuntu 19.04 (disco)

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#10112]
It failed in the link step:

```
LD retroarch
/usr/bin/ld: obj-unix/release/./deps/glslang/glslang/SPIRV/Logger.o: undefined reference to symbol '_ZNSt6localeD1Ev@@GLIBCXX_3.4'
/usr/bin/ld: /lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:201: retroarch] Error 1

```

I had to add `-lstdc++` to the LDFLAGS in the Makefile to make the build complete. Apparently SPIRV sneaked in a C++-ism.

**Comment by twinaphex** [comment]
Do you have a PR for this?

**Comment by i30817** [comment]
No, i'm not confortable modifying the makefile and my 'solution' is a hack anyway.

If you're curious I just added the bold: 	

$(Q)$(LINK) -o $@ $(RARCH_OBJ) $(LIBS) $(LDFLAGS)  **-lstdc++** $(LIBRARY_DIRS)

**Comment by orbea** [comment]
@i30817 You should know better than this. There is not enough information to even tell why you are running into this.

* full configure + build log
* config.mk
* config.log
* config.h

**Comment by i30817** [comment]
Sure... i'll point out first that the configure doesn't present a error so even if i'm missing a library, that's a bug.

1.1. ```./configure --disable-discord --disable-qt  --enable-zlib --disable-7zip --disable-sdl --disable-vulkan --disable-cdrom --disable-sdl2 --disable-xvideo --disable-opengl_core --disable-opengl1 --disable-xinerama --enable-wayland --disable-x11```
1.2. [make.txt](https://github.com/libretro/RetroArch/files/4200998/make.txt)
2. [config.mk.txt](https://github.com/libretro/RetroArch/files/4200905/config.mk.txt)
3. [config.log.txt](https://github.com/libretro/RetroArch/files/4200909/config.log.txt)
4. [config.h.txt](https://github.com/libretro/RetroArch/files/4200913/config.h.txt)

**Comment by orbea** [comment]
I can reproduce it now.
