### ISSUE TITLE
fullscreen causes CPU frequency drop

### ISSUE THREAD

**Issue by hasteech** [libretro/RetroArch#10125]
## Description

When RetroArch switches to fullscreen mode (both windowed and exclusive), the CPU frequency as reported by Task Manager drops from roughly 2GHz at idle to roughly 1.4GHz with fullscreen RetroArch.  This is observable with just the RetroArch menus, but it affects all cores and content.  This is not affected by Windows Power Management settings, and it occurs when Processor Power Management has both the minimum and maximum processor power states set to 100%.  For reference, in normal windowed mode, the CPU frequency is roughly 2.8GHz.

### Expected behavior

CPU frequency should be at least 2GHz.

### Actual behavior

CPU frequency is drops to roughly 1.4GHz.

### Steps to reproduce the bug

1. Have a second display with Task Manager open. Check idle CPU frequency.
2. Start RetroArch
3. Make RetroArch fullscreen
4. Observe CPU frequency

### Bisect Results

before 1.7.5/826c77d523

### Version/Commit
You can find this information under Information/System Information

- RetroArch:
1.7.5/826c77d523
1.8.4/f425d8dc8b

### Environment information

- OS: Windows 10 64-bit
- CPU: AMD Ryzen 3700U

**Comment by twinaphex** [comment]
Must be an OS-level issue, BIOS setup issue or something in your Windows configuration, RetroArch has no logic at all that could dictate anything to your CPU when it comes to a performance profile being taken.
