### ISSUE TITLE
(Database) Headers in RA's compiled .rdb files have incorrect offset

### ISSUE THREAD

**Issue by gordon-fish** [libretro/RetroArch#10140]
Testing with the latest RetroArch release, I have observed that the .rdb files in databases/rdb/ have incorrect offset values (always zero) in the header, which is supposed to point to where the metadata section is:

``00000000: 5241 5243 4844 4200 0000 0000 0000 0000  RARCHDB.........``

When a .rdb is opened, the [header struct](https://github.com/libretro/RetroArch/blob/master/libretro-db/libretrodb.c#L76) is [populated](https://github.com/libretro/RetroArch/blob/master/libretro-db/libretrodb.c#L235) and the offset member is [fed to seek](https://github.com/libretro/RetroArch/blob/master/libretro-db/libretrodb.c#L248) to jump to that offset from the start of the file.

It then [populates](https://github.com/libretro/RetroArch/blob/master/libretro-db/libretrodb.c#L251) the [metadata struct](https://github.com/libretro/RetroArch/blob/master/libretro-db/libretrodb.c#L71) ``md`` which has a single member, ``uint64_t count;``, which is supposed to be the amount of records there are.

But since the offset is zero, it never properly reads the count. This causes ``libretrodb_tool(.exe)`` to crash (typical win32 crash on Windows, segfault on Linux) when using ``list``. It still lists the contents, so it's just reading records until it hits the end.

RetroArch itself doesn't crash from this as far as I can tell, probably due to exception handling, though this really is something that should be addressed. It seems to be a problem with how the database files were compiled.

If I change the first 16 bytes to looks like:

``00000000: 5241 5243 4844 4200 0000 0000 0000 bff8  RARCHDB........``

(where ``bff8`` is at the end in place of ``0000``) then it correctly reads the metadata at the end of the file and count value, confirming that the reading works fine with the expected header, which I can confirm with a debug printfs added to ``libretro-db/libretrodb.c`` [right after it's population](https://github.com/libretro/RetroArch/blob/master/libretro-db/libretrodb.c#L257).

``[DEBUG] [db->count=278] [md.count=278]``

**Comment by gordon-fish** [comment]
Just wanted to add that that debug line at the end of my main post is from running:

``libretrodb_tool.exe "C:\emu\RetroArch\database\rdb\Coleco - ColecoVision.rdb" list``

after having built it using ``make libretrodb_tool`` from inside the ``libretro-db`` subdir of the cloned git repo.

**Comment by RobLoach** [comment]
Thanks for the debugging. I've found similar crashes when using libretrodb_tool . Do you know of a proper fix for this?

**Comment by gordon-fish** [comment]
Apologies for the late reply.

After doing some more checking and testing, I've found that culprit appears to be the use of ``filestream_seek(fd, 0, RETRO_VFS_SEEK_POSITION_CURRENT)`` at in ``libretrodb_create`` in [libretro-db/libretrodb.c](https://github.com/libretro/RetroArch/blob/master/libretro-db/libretrodb.c#L176)

``filestream_seek(fd, 0, RETRO_VFS_SEEK_POSITION_CURRENT)`` returns the success of the call, not the the offset. The problem is that it's being used as it did.

``filestream_tell(fd)`` is what should be used there, as that is what actually returns the offset.

```
header.metadata_offset = swap_if_little64(filestream_seek(
            fd, 0, RETRO_VFS_SEEK_POSITION_CURRENT));
```

should be changed to:

```
header.metadata_offset = swap_if_little64(filestream_tell(fd));
```

Please let me know if you agree and I will submit a pull request if that is ok.

**Comment by gordon-fish** [comment]
I have added a [pull](https://github.com/libretro/RetroArch/pull/10171) request #10171 with this fix.
