### ISSUE TITLE
RetroArch timezone uses UTC instead of system-reported time (UTC -8)

### ISSUE THREAD

**Issue by Jay2645** [libretro/RetroArch#10158]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The system clock for RetroArch seems to be set to UTC instead of using the timezone reported by the OS.

### Expected behavior

The clock in the top right corner and used in games like Pokemon should match the current local time reported by the OS (UTC -8).

### Actual behavior

The clock in the top right corner and used in games like Pokemon is set to UTC.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 9e25601a56

### Environment information

- OS: Arch Linux

**Comment by RobLoach** [comment]
This is not happening for me on Ubuntu 18.04... I'm getting it in EST, as expected.

**Comment by gouchi** [comment]
I can't reproduce your issue running also Arch Linux using [9e25601](https://github.com/libretro/RetroArch/commit/9e25601a56041831f3b2cd6668aa63ec6809a0c3) or latest commit.

We are using `setlocale(LC_TIME, "");`  [Source](https://github.com/libretro/RetroArch/blob/master/menu/menu_driver.c#L2162) [man](https://linux.die.net/man/3/setlocale) for the current locale.

I presume `timedatectl` output is alright.

**Comment by RobLoach** [comment]
No longer able to reproduce on `master`.

**Comment by pouar** [comment]
In my case, it only happens with the Vulkan driver, but not the OpenGL one

**Comment by gouchi** [comment]
@Jay2645 @pouar Is it still an issue or can we close this issue ? Thank you.

**Comment by Jay2645** [comment]
I'll be honest - I haven't used this setup in quite a while! I don't even have the machine I saw this on anymore. I think it's safe to close it.
