### ISSUE TITLE
Mouse unavailable - Retroarch 1.8.4 Mac

### ISSUE THREAD

**Issue by groelk** [libretro/RetroArch#10168]
Hi,
Running RA 1.8.4 on Mac OS 10.5.3, with the PUAE core, there's no way the pointer will move with a mouse or trackpad, only with the keyboard. I think I tried all available settings to get mouse input to work.
It does not seem to be core-related. PUAE works fine with RA on smartphones. No issues with the pointer at all on Android.
Is this a known issue, and are there any ways to fix it?
Many thanks!

**Comment by RobLoach** [comment]
I've seen the same with `master` on Linux/Ubuntu 18.04. Assumed it had been a permissions thing on my machine.

What Input Driver are you using? I'm on `udev`.

**Comment by groelk** [comment]
On OS X the input driver is `cocoa`

**Comment by groelk** [comment]
Any recommendations? Thanks!

**Comment by rsn8887** [comment]
Same here, I cannot move the mouse pointer in any core on MacOS. Tried both touchpad and physical USB mouse. Tried selecting Toggle Mouse Grab, no difference.

**Comment by OctopusButtons** [comment]
I have the same issue. There is no way to get any mouse device working in-game, neither to move to the crosshair nor to fire.

- I tried both PSX Beetle, Nestopia, etc.
- I tried 4 different devices on Mac (MacBook Pro trackpad, wireless Bluetooth trackpad, Bluetooth mouse, standard generic USB mouse)
- I tried every single Mouse Index setting both while repeatedly toggling “Grab Mouse Input” (just in case)
- While doing that I also tried toggling Game Focus on and off (just in case)
- I tried every virtual control setting, e.g. in Time Crisis for PlayStation I tried “Guncon” and other options
- I deleted configs.
- I redid the binds.
- I unbinded and rebinded
- I tried multiple Users, 1 and 2, just in case.
- I read about 100 pages of discussion (https://forums.libretro.com/t/how-to-configure-mouse-as-light-gun-and-light-gun-as-mouse/8970 and similar) and also read through the comprehensive Libreto Docs about controls.
- I also read the original PS1 Time Crisis manual booklet in case it was something inherent to the game’s options itself

There is no way to make the crosshair move at all, even a single pixel, in Time Crisis on PlayStation (Beetle core, also the PCArmed core).  Mouse fire for lightgun Fire doesn’t work either, although the binding of “Lightgun Trigger” and “Lightgun Reload” to Mouse 1 and Mouse 2 seems to work fine in the menu.

All these mouses (Bluetooth mouse, Apple Trackpad, generic USB mouse, built-in MacBook Peo trackpad) work fine in the OS and in the Retroarch front end menu.

As soon as I change to a controller input, I can move the controller cursor with Dpad or keyboard arrows. But mouse movement in-game, I see the crosshair stuck in middle of screen but no movement. But my mouse works OK as a lightgun cursor mover in MAME (outside of Retroarch).

**Comment by OctopusButtons** [comment]
Also this means no mouse/trackpad in DS cores in Retroarch on Mac.  No mouse control for anything at all on Mac currently in RA.

**Comment by groelk** [comment]
Thanks for sharing your experience on this issue for Mac users.
Seems there is no way to solve this, apart from a future RA update that would address it.

**Comment by RobLoach** [comment]
Post logs? https://docs.libretro.com/guides/generating-retroarch-logs/

**Comment by groelk** [comment]
Sorry for the delayed answer.
Found out the Terminal command to generate RetroArch logs:
`/Applications/RetroArch.app/Contents/MacOS/RetroArch  --menu --verbose --log-file ~/retroarch.log`

Below is the generated log. I tried a mouse-based game with PUAE.

`[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Jan 15 2020
[INFO] Version: 1.8.4
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/Users/ben/Documents/RetroArch/saves/.srm".
[INFO] Redirecting savestate to "/Users/ben/Documents/RetroArch/states/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [GL]: Found GL context: cocoagl
[INFO] [GL]: Detecting screen resolution 960x720.
[INFO] [GL]: Vendor: Intel Inc., Renderer: Intel(R) HD Graphics 5300.
[INFO] [GL]: Version: 2.1 INTEL-14.4.23.
[INFO] [GL]: Using resolution 1920x1440
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] Found HID driver: "iohidmanager".
[INFO] [Joypad]: Found joypad driver: "hid".
[INFO] [Video]: Found display server: null
[INFO] Found shader "/Applications/RetroArch.app/Contents/Resources/shaders/retroarch.glslp"
[INFO] [CoreAudio]: Using output sample rate of 48000.0 Hz
[INFO] [CoreAudio]: Using buffer size of 24576 bytes: (latency = 64 ms)
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [LED]: LED driver = 'null' 0x10bf3e278
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[WARN] Input device ID 259 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/Users/ben/Library/Application Support/RetroArch/config/content_history.lpl].
[INFO] Loading history file: [/Users/ben/Library/Application Support/RetroArch/config/content_music_history.lpl].
[INFO] Loading history file: [/Users/ben/Library/Application Support/RetroArch/config/content_image_history.lpl].
[INFO] Loading favorites file: [/Users/ben/Library/Application Support/RetroArch/config/content_favorites.lpl].
[INFO] [GL]: VSync => on
[INFO] [GL]: VSync => on
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[WARN] Error parsing JSON.
[WARN] Error: Invalid JSON at line 11, column 15 (input byte 194) - the input ends in the middle of a token.
[INFO] Using content: /Users/ben/roms/Commodore - Amiga/7 Colors (Europe) (En,Fr,De,Es,It).adf.
[INFO] arg #0: retroarch
[INFO] arg #1: /Users/ben/roms/Commodore - Amiga/7 Colors (Europe) (En,Fr,De,Es,It).adf
[INFO] arg #2: -s
[INFO] arg #3: /Users/ben/Documents/RetroArch/saves
[INFO] arg #4: -S
[INFO] arg #5: /Users/ben/Documents/RetroArch/states
[INFO] arg #6: -c
[INFO] arg #7: /Users/ben/Library/Application Support/RetroArch/config/retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: /Applications/RetroArch.app/Contents/Resources/cores/puae_libretro.dylib
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : /Users/ben/Library/Application Support/RetroArch/config/retroarch.cfg
[INFO] Redirecting save file to "/Users/ben/Documents/RetroArch/saves/7 Colors (Europe) (En,Fr,De,Es,It).srm".
[INFO] Redirecting savestate to "/Users/ben/Documents/RetroArch/states/7 Colors (Europe) (En,Fr,De,Es,It).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Jan 15 2020
[INFO] Version: 1.8.4
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/Applications/RetroArch.app/Contents/Resources/cores/puae_libretro.dylib"
[INFO] [Overrides] no core-specific overrides found at /Users/ben/Library/Application Support/RetroArch/config/PUAE/PUAE.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /Users/ben/Library/Application Support/RetroArch/config/PUAE/Commodore - Amiga.cfg.
[INFO] [Overrides] game-specific overrides found at /Users/ben/Library/Application Support/RetroArch/config/PUAE/7 Colors (Europe) (En,Fr,De,Es,It).cfg.
[INFO] Config: appending config "/Users/ben/Library/Application Support/RetroArch/config/PUAE/7 Colors (Europe) (En,Fr,De,Es,It).cfg"`

**Comment by AlexKornitzer** [comment]
For me this broke (no mouse input in DeSmuME) in 1.7.7, worked fine in 1.7.6. Done a bisect and this seems to be the culprit which would make sense based on the amount of changes within there: https://github.com/libretro/RetroArch/commit/89a6992d0c1705125121d82ab0b2c47e87b7ff08

**Comment by groelk** [comment]
Thanks a lot for checking this out!
Looking forward to a future update allowing to use the mouse with RA!

Would you know where to find earlier RA cores? The stable versions on Libretro aren't available before 1.7.5

**Comment by AlexKornitzer** [comment]
You can probably download the latest nightly, otherwise 1.7.6 should work until they bundle the new release. That is assuming this fixes the issues you have.

**Comment by groelk** [comment]
I encounter a similar issue with the WiiU touchscreen since RA version 1.7.1, the last one which appears to support it.
Before submitting a new post I'd like to test it with different pointer-based cores, such as dosbox or puae, as I could only find the ScummVM core for RA 1.7.1.

I have the source files for that RA version I don't know how to compile cores. Would you?
http://dl.free.fr/wEIHMKRx4

**Comment by AlexKornitzer** [comment]
@groelk before filing a new issue I would try the latest nightly (https://buildbot.libretro.com/nightly/apple/osx/x86_64/) with the cores that have been an issue for you as it should contain the fix.  If the latest nightly is not working for you then I would say this issue tracks the problem already and we would need to triage the issue again.

**Comment by groelk** [comment]
Tested on OSX 10.15.4: neither mouse nor touchpad move the pointer when using cores PUAE and ScummVM. Mouse click, and touchpad click, do work though, with both cores.

**Comment by AlexKornitzer** [comment]
Ah okay, so I think my PR only addressed clicking as this was the only issue I had at the time. If I get some time later today I will test in the ScummVM core and see if I can replicate.

**Comment by AlexKornitzer** [comment]
Right replicated in ScummVM core, can use the arrow keys and mouse click but not mouse move movement, will try and diagnose later this week.

**Comment by AlexKornitzer** [comment]
Right, so been probing a little further, checked out 1.7.0 to see if it was a regression and input still didn't work in ScummVM, so either this is an issue with the core (doubtful if it works on other systems, which I guess it does) or the issue is in the cocoa input driver `input/drivers/cocoa_input.c` as the ui component of cocoa is now reporting the coordinates correctly due to the PR above. But it is a strange one cause other cores seem to be happy. A seasoned contributor would probably be able to isolate the cause of this one pretty quickly, which I am not.

**Comment by groelk** [comment]
Thanks a lot for investigating further!
It might not be a core-related issue as the same happens with the PUAE core for instance.
PUAE and ScummVM work fine with the pointer on other devices, like Android.

**Comment by AlexKornitzer** [comment]
Yeah, I am thinking it is in `input/drivers/cocoa_input.c` I am just not up to speed with how input is handled by retroarch. @RobLoach are there quick wins to debug stuff like this?

**Comment by OctopusButtons** [comment]
AlexKornitzer, thank you for your work on this.  The new 1.8.6 release has a patch note about a change to mouse in Mac OS X.

There’s still a problem though:  the update didn’t fix the issue, but when I change the Beetle PSX HS setting for “Gun Input Mode” to TOUCHSCREEN, now my mouse and my trackpad works.  But I’m not on a touchscreen.  The “Light gun (use mouse-controller light gun)” should be the correct one, but only the Touchscreen setting works correctly despite the fact that I’m not on a touchscreen.

I can’t test SNES Mario Paint, because neither Higan nor nSide codes have an equivalent to the “Light gun: Touchscreen or Mouse” like in Beetle PSX HW.  I’d be glad to test, but I don’t see anything to test, mouse support is still sadly broken, “Retromouse” doesn’t work on SNES cores (or possibly for any core).  I don’t understand why there’s no options for binding Retromouse (for example Axis controls) to anything else, this makes it impossible to do testing of the bug because “Retromouse” is like an invisible blackbox with no user access in the interface.

**Comment by groelk** [comment]
Thanks @AlexKornitzer for the steps forward with this issue.
After updating to 1.8.6 and testing the mouse on OSX with cores Dosbox, P-UAE and ScummVM:
- Mouse click is supported
- Mouse/pointer movements aren't supported

**Comment by AlexKornitzer** [comment]
@OctopusButtons lack of lightgun support is most likely because the case statement for that is missing from the cocoa driver:
<img width="1431" alt="Screenshot 2020-05-10 at 20 11 26" src="https://user-images.githubusercontent.com/2750747/81508184-97886880-92fa-11ea-9e69-cfed83ac45fd.png">

Going to do the scientific approach and shove a load of prints in to see if I can track the state changes, will probably hit a wall though :P

**Comment by AlexKornitzer** [comment]
Right, the above should fix the cursor issue, it is a little rough around the edges but considering this has not worked for so long its better than nothing. Once we know it solves the main problem, then we can iterate on an improved solution.

DOSBox core demonstrates an issue with NSWindow and clipping, so that is next on the list.

**Comment by groelk** [comment]
Many thanks for this fix! Is it already available in a nightly for testing?

**Comment by AlexKornitzer** [comment]
I would assume its in there, yes. Lets see if it works for you :P

**Comment by groelk** [comment]
I have tested with cores PUAE and Dosbox. Mouse click works but the pointer will not move with the mouse (it will only when using keyboard arrows).

Just to make sure: for testing I have only replaced those 2 core files (dylib) using the latest available ones among the available nightlies. Are there any other RetroArch application files to update besides the cores?

**Comment by AlexKornitzer** [comment]
@groelk did you download the latest nightly for retroarch as well? As the changes are in there and not the cores. 

https://buildbot.libretro.com/nightly/apple/osx/x86_64/RetroArch.dmg

**Comment by groelk** [comment]
Hey, it's all fixed! With a full reinstall of yesterday's nightly, the P-UAE and Dosbox cores now fully support the mouse on OSX.
Big thanks!
