### ISSUE TITLE
[Vulkan, glcore] Launching Content Sometimes Minimizes and Freezes RA

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#10185]
I've only encountered this issue with the Mesen-S core, so I originally opened the issue [over there](https://github.com/SourMesen/Mesen-S/issues/103). But @SourMesen doesn't think it's his code, and @Ryunam has had the problem with Beetle PSX software in the past, so it sounds like a frontend issue.

I was able to reproduce this with a nightly Win64 RetroArch.7z extracted to a new folder. I switched the video driver to vulkan or glcore, downloaded Mesen-S with the updater, and launched the 240p test suite SNES ROM with that core.

Sometimes when launching, it will freeze on a white screen. I can't unpause it with p. I can bring up the menu with F1, but trying to resume freezes with the menu still visible. If I press F1 again I can navigate the menu again and pressing Esc twice closes RA normally. If I use my normal RetroArch setup where I launch in fullscreen, when the issue happens it launches minimized. I have to alt tab to RA and then I get a frozen black screen with the pause button.

Here is one log where it [didn't freeze](https://pastebin.com/5QbkdGtu) and one [where it did](https://pastebin.com/GVbarXNx). The diff shows these additional lines in the one where it didn't freeze:

> [INFO] [Vulkan]: Do not need to re-create swapchain.
> [INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
> [INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
> [INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
> [INFO] [slang]: Building pass #0 (N/A)
> [INFO] [Vulkan filter chain]: Not using frame history.
> [INFO] [Vulkan filter chain]: Not using framebuffer feedback.
> [INFO] [Vulkan]: Do not need to re-create swapchain.
> [INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
> [INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
> [INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
> [INFO] [slang]: Building pass #0 (N/A)
> [INFO] [Vulkan filter chain]: Not using frame history.
> [INFO] [Vulkan filter chain]: Not using framebuffer feedback.

That seems less useful than the diff I got with the logs from my fullscreen launching setup ([working](https://pastebin.com/4HGrSdBU), [not working](https://pastebin.com/RZZLs72a)):

![75616285-32a3db80-5b1d-11ea-8e1f-272f996a661c](https://user-images.githubusercontent.com/4565863/75618040-0cd70080-5b36-11ea-87c7-6b80ea995cb7.png)

**Comment by Ryunam** [comment]
Chiming in to further expand on my experience. I encountered this problem on my brother’s Surface Pro 7 device and what happened there was that the content would be launched in a “Paused” state. Literally a “Paused” notification would appear in the bottom-left corner and RA would freeze entirely.

We later discovered that there was one weird way to “un-pause” / un-freeze RA and make it run normally: tapping the Surface Pro screen once. Upon doing that, RA resumed its normal functionality and everything was working as intended.

Another thing I can add is that, as with @Awakened0’s example, this issue occurred unpredictably. Sometimes content would launch normally, some other times the “Paused” state would kick in upon loading the same exact content that worked perfectly before. Finally, I can confirm that so far I have yet to encounter this issue on my desktop Windows 10 system.

**Comment by Awakened0** [comment]
I've only encountered it on a desktop (2500k + GTX 970 latest drivers, Win10) and I haven't found any way to unpause when I run into the problem. Also, I forgot to mention I couldn't get the issue to happen with the gl driver. Only vulkan and glcore. I didn't try the d3d drivers.

**Comment by Awakened0** [comment]
I tried going back in RetroArch commits as far as August, but couldn't find one that didn't exhibit the freeze with the latest Mesen-S core. However, older commits of Mesen-S didn't have the issue and I was able to bisect and find this core commit as the cause: https://github.com/SourMesen/Mesen-S/commit/5f2c502be9908b80ec359d96b09688f6917b8fda

**Comment by twinaphex** [comment]
I will ask if it's possible that this runahead support gets put behind ifdefs so that the Libretro core isn't affected by this. I think typically when emulators like bsnes and Mesen-S have attempted to do runahead in standalone, it has ended up badly for the libretro core and it's typically best if that stuff gets left to the wayside for the libretro core. Perhaps an ifdef can be made for runahead so that this could be baked out for the libretro core.

Just for my general understanding, did runahead work properly before with the libretro core or where there issues back then too?

**Comment by SourMesen** [comment]
There is no direct link to the runahead feature - it is already meant to not affect the libretro core at all.  There is potentially some minor detail somewhere in that commit that is causing an issue, but I haven't figured out the cause (and I haven't been able to reproduce the issue on my end)

**Comment by twinaphex** [comment]
Alright, hopefully we discover the root cause.

To the OP - does this only happen with Vulkan?

**Comment by Awakened0** [comment]
Runahead works OK with 1 frame and secondary instance enabled with a build before that commit. A few sound crackles on my 2500k playing Aladdin. With secondary instance off it's really slow. Running the latest build of the core, secondary instance off is a little bit faster. I still get a few crackles with it on, but it seems like a little less.

It only happens with Vulkan and glcore. I haven't gotten it to happen with gl. Haven't tested the d3d drivers.

**Comment by twinaphex** [comment]
So can you explain the situation that happened before that commit you pinpointed? Did it work fine then?

**Comment by Awakened0** [comment]
Scratch that, I just tested gl with the latest Mesen-S and got the freeze.

Yeah, I tested Mesen-S quite a bit when it was first released. And here and there since then. I didn't run into the issue until after that commit.

**Comment by Awakened0** [comment]
@SourMesen found out there was an [uninitialized value in the core](https://github.com/SourMesen/Mesen-S/issues/103#issuecomment-604755622) causing the issue. I'm going to close this, since it looks like it was a core problem in the end. @Ryunam , you might want to open an issue about this on the Beetle PSX repo. It might be a similar problem in that core, so you could reference this report and/or the one on the Mesen-S repo. I still haven't been able to reproduce the freeze with Beetle PSX and I use it pretty regularly.

**Comment by Ryunam** [comment]
I will make sure to test this again on my brother's Surface Pro and, in case it's happening again, I'll report it on the Beetle PSX repository. Thanks a lot for your thorough tests and findings!
