### ISSUE TITLE
Rich Presence Monitor

### ISSUE THREAD

**Issue by wilhitewarrior** [libretro/RetroArch#10200]
Now that we've had rich presence successfully implemented, the next step is hopefully to implement a rich presence monitor into retroarch so that the player can view it within retroarch itself rather than having to open up a browser or check it in discord or something if they want to see it.
Sometimes the rich presence monitor can reveal information to a player that the game itself doesn't. For example, on Tenchu it will show the player how many kills they've gotten versus how many total there are on a level

In ralibretro the monitor takes the form of a small window that they can open by clicking the retroachievements drop-down menu and clicking the rich presence monitor
![Tenchu RP](https://user-images.githubusercontent.com/25572417/75738803-2ceef700-5cd1-11ea-954b-dfb30bc65cb9.png)

I discussed this with KickMeElmo in discord, he presented the idea of adding it as an overlay option that a player could toggle on and off, similar to the FPS overlay.
![unknown](https://user-images.githubusercontent.com/25572417/75739066-e3eb7280-5cd1-11ea-8545-49d2fc62b84e.png)

 I thought that was a good idea, perhaps with a 'Rich Presence Monitor' in the quick menu as well that could show the information if they just wanted to check it real quick

I also posted a bounty for this, found here:
https://www.bountysource.com/issues/89470228-rich-presence-monitor

**Comment by Jamiras** [comment]
The Rich Presence Monitor was intended as a developer tool for building a rich presence script. It was never intended to augment the player's experience. 

Rich presence is supposed to provide _other players_ with the knowledge that you're playing a specific game, and a rough idea of how well you're doing in the game.

**Comment by wilhitewarrior** [comment]
Regardless of the intent, used creatively it can be an effective tool for adding to the players experience as well

**Comment by natinusala** [comment]
For what it's worth I am working on a Lua addons system for RetroArch (loaded at runtime). For now the API is fairly limited but the end goal is to allow people to write exactly this kind of stuff without digging into C code.

The downside is that the addons are not built-in and will need to be installed separately from RetroArch.
