### ISSUE TITLE
(Core) Quake 1 libretro core: GLQuake3D

### ISSUE THREAD

**Issue by DartPower** [libretro/RetroArch#10235]
The project does not have ongoing maintenance, but there is a place to be. His functions from vanilla are no different, except for cosmetic changes in the stow glow around light sources and improve sound quality. 
If someone has a desire to help, we will be happy to accept help.

https://github.com/dpteam/GLQuake3D

**Comment by RobLoach** [comment]
Looks very young, but promising. Curious to see how it compares to the other source ports. Keep it up!

**Comment by RobLoach** [comment]
Going to close this for now. If you find this to be a good alternative to Tyrquake, feel free to have a hack at a libretro core in the source repo. Thanks a lot!
