### ISSUE TITLE
(OSD) Separate notification widgets from one another

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#10238]
So for awhile now ive had retroarch set up to show only the save(load) state indication (as i have those hotkeyed and like to be certain theyve fired off)

it did not show the configuration override loaded message as I had turned that off (somehow, it was ages ago).

After a nice fat stretch of work taking over my life, tonight was my return to gaming.  Several weeks of RA builds to be upgraded, the swap to ozone etc etc.

First thing i noticed was POOF configuration override showing up again.

Naturally i searched for how i had hidden it before and the only thing that seems to exist at current is a blanket toggle that shuts off everything on screen notification wise.

I think a huge improvement would be the ability to choose what we want to see.   I couch game primarily and i try to make it as polished of an experience as possible.   Those notifications are pretty immersion breaking but some are more necessary than others.

The ability to separately hide the controller popups, the configuration override popups, the save/load state popups, and any others that havent imposed their will on me yet would be a nice addition.

**Comment by Ryunam** [comment]
I definitely agree, having separate toggles for each type of onscreen notification would be great to have. I had actually started working on this years ago, maybe I can take a look at it once again as soon as I get some spare time.

**Comment by Awakened0** [comment]
This is more or less a dupe of [this old issue](https://github.com/libretro/RetroArch/issues/4341), so if selective notification disabling is added both can be closed.

**Comment by jdgleaver** [comment]
By a strange coincidence, natinusala started laying the groundwork for this yesterday (just before this issue was opened). So let's wait and see how things develop  :)

**Comment by Ryunam** [comment]
That's great! The PR I initially sent (which was only partial in its scope and took care of the autoconfig notifications only) was https://github.com/libretro/RetroArch/pull/4354 (more than 3 years ago... wow, time flies).
Okay then, I will wait for further developments and not resume working on it unless something changes.

**Comment by RobLoach** [comment]
Haha, I knew this sounded familiar :laughing:

**Comment by Awakened0** [comment]
The override message and a few others can be disabled now: https://github.com/libretro/RetroArch/pull/11033

**Comment by klepp0906** [comment]
excellent news!  huge improvement to the user experience (for me at least).   Thanks to everyone who made it happen.  You guys are always so accommodating, almost to a fault!

Closing then
