### ISSUE TITLE
(Database) Support for Korea and Asia Playstation Portable discs

### ISSUE THREAD

**Issue by pkos** [libretro/RetroArch#10241]
## Description

Missing disc codes for Korea and Asia in the task_database_cue.c file.
Therefore, some discs are not scanned.

### Expected behavior

Would like to see support added.

### Steps to reproduce the bug

               || (string_is_equal(game_id, "ULKS-"))
               || (string_is_equal(game_id, "ULAS-"))

inserted at line 265 does the trick

those are Korea and Asia codes

**Comment by RobLoach** [comment]
Thanks! Upped a Pull Request for this :+1:
