### ISSUE TITLE
Input Bind Hold functionality broken

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#10276]
## Description

The "Bind Hold" option under Settings -> Input does not seem to function properly. This option allowed to define a certain amount of seconds that users would have to hold a button for when rebinding any input in the Menu. Instead, this is what is happening right now:

- when setting this option to any number above zero, the outcome is exactly the same. Rebinding any input will just require one press of the button, regardless of whichever value was chosen;
- when setting this option to zero, input remapping stops working. You cannot configure any input (pressing A / Confirm does nothing) and you cannot reset bindings to their default state with the Start button either.

### Expected behavior

When ribinding any input, Settings -> Input -> Bind Hold should effectively control the number of seconds that users are required to hold a button for.

### Actual behavior

Inputs can be configured with a simple press of the chosen button, ignoring the Bind Hold option. Also, setting the option to zero breaks all input rebinding.

### Version/Commit

- RetroArch: 1.8.5 / 8794360b65dfe462c9cf6c5a0ab62ff95f656db1

### Environment information

- OS: Windows 10 x64 - build 1909
- Compiler: mingw64

**Comment by Ryunam** [comment]
I did a bisect and https://github.com/libretro/RetroArch/commit/3a1c59d461570ddfeb19d4d2f742df71ca19c250 seems to be first commit that caused this.

There's also another aspect I noticed: in current RA the Bind Hold option is actually affecting (or overlapping with) the input bind timeout ("Bind Timeout" under Settings -> Input). 

That's probably why it prevents all inputs from being remapped when it set to zero: it is being interpreted as giving 0 seconds of timeout.

**Comment by twinaphex** [comment]
Check if this commit fixes it -
https://github.com/libretro/RetroArch/commit/a33353399ffcfdc34392e6a8ad108419e2743b31

**Comment by Ryunam** [comment]
Okay, commit a333533 solves this issue partially:

- it makes it so Bind Hold does not overlap with Bind Timeout anymore;
- setting Bind Hold to zero now allows inputs to be reconfigured;
- setting Bind Timeout correctly sets the amount of seconds given to rebind an input.

However, I think the intended functionality of Bind Hold is still broken (and was probably broken long before commit 3a1c59d461570ddfeb19d4d2f742df71ca19c250). Regardless of the value chosen for this setting, you currently just need one slight press of a button to rebind any input. This should happen only if Bind Hold is set to 0.

**Comment by twinaphex** [comment]
> However, I think the intended functionality of Bind Hold is still broken (and was probably broken long before commit 3a1c59d). Regardless of the value chosen for this setting, you currently just need one slight press of a button to rebind any input. This should happen only if Bind Hold is set to 0.

Can you tell me if these issues are there with the commit prior to https://github.com/libretro/RetroArch/commit/3a1c59d461570ddfeb19d4d2f742df71ca19c250? I need to know the state of the commit exactly before this one.

**Comment by twinaphex** [comment]
I guess what I'm asking is if the behavior now is back to where it was before - before the commit you mentioned. This is important since we want to ship a new stable soon.

**Comment by Ryunam** [comment]
Yes, I can confirm that the only issue left (Bind Hold not affecting how many seconds you need to hold the button to rebind inputs) was there long before commit https://github.com/libretro/RetroArch/commit/3a1c59d461570ddfeb19d4d2f742df71ca19c250. I have tested an old build I had of version 1.7.7 and this issue was already there.

So, the situation is that https://github.com/libretro/RetroArch/commit/a33353399ffcfdc34392e6a8ad108419e2743b31 effectively reverts the behavior back to its original state before https://github.com/libretro/RetroArch/commit/3a1c59d461570ddfeb19d4d2f742df71ca19c250 (thank you for the quick fix by the way!)

I will try to do a more thorough and longer bisect later on, so to understand at which point the functionality of Bind Hold was intially altered.

**Comment by bslenul** [comment]
I think it's related to that issue I posted months ago: #8965 
A commit was reverted or something and then the option just became useless :(

**Comment by sonninnos** [comment]
Yep, for some odd reason only Android is doing the hold requirement by design behind #ifdefs. I tried simply changing the #ifdef so that everything else also uses it, and seems fine so far..
