### ISSUE TITLE
QUIT Network Command Prompts "Press again to quit"

### ISSUE THREAD

**Issue by baclap** [libretro/RetroArch#10319]
## Description

I have two terminal windows open and I am ssh'd into a Raspberry Pi Zero W in both. I start a game from one terminal with the command:

```
DISPLAY=:0 ./retroarch -L /opt/retropie/libretrocores/lr-quicknes/quicknes_libretro.so --config /home/pi/retroarch.cfg -D /home/pi/game.nes
```

I execute the QUIT command from the other terminal with:

```
./retroarch --command QUIT
```

Instead of quitting the game I see a prompt in the bottom left corner of the screen to "Press again to quit". Issuing the command twice in a row will quit the game. I see no way to turn off this behavior in retroarch.cfg.

### Expected behavior

I am able to define some configuration in retroarch.cfg so that Issuing the QUIT command once quits the game.

### Actual behavior

No option exists in retroarch.cfg. The only way to quit via CLI is to issue the QUIT command twice rapidly.

### Steps to reproduce the bug

1. Start game from CLI
2. Attempt to issue the `QUIT` command
3. Observe the "Press again..." prompt on screen

### Environment information

```
$ ./retroarch --version
RetroArch: Frontend for libretro -- v1.8.4 -- 9e25601 --
Compiler: GCC (8.3.0) 32-bit Built: Feb  4 2020
```

**Comment by hizzlekizzle** [comment]
I believe it's: quit_press_twice = "false"

**Comment by baclap** [comment]
@hizzlekizzle Thanks! Confirmed this does work. This is in the default config as well it looks like. I had been using a config file from a previous version. I did look through the default config in my new build but didn't notice this.

**Comment by hizzlekizzle** [comment]
No worries. I'm glad that got you fixed up! :)
