### ISSUE TITLE
[Issue] Problem with ppsspp core in Windows

### ISSUE THREAD

**Issue by Immersion95** [libretro/RetroArch#10313]
Hi,

ppsspp's core in Windows is old (from Oct, 9th). It's strange as https://github.com/libretro/ppsspp is being worked on constantly.

I would have opened the issues there but it is not allowed as the moment, maybe it is being published in the near future ?

The issue I openened there https://github.com/twinaphex/ppsspp/issues/25 has been moved on another branch https://github.com/twinaphex/ppsspp

**Comment by gouchi** [comment]
Hi,

It will be better to open this issue to the [dedicated repository](https://github.com/libretro/libretro-super).

Thank you.

Kind regards,

**Comment by Immersion95** [comment]
Done :)
