### ISSUE TITLE
no Host on vita

### ISSUE THREAD

**Issue by Lmontan-don** [libretro/RetroArch#10336]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

no host room created on netplay with ps vita

### Expected behavior

[that the created game-room shows off under the room list]

### Actual behavior
[my netplay room does not show off]

### Steps to reproduce the bug

1. [netplay]
2. [Host]
3. [Load content from playlist]
4. try to find the room with another device (macbook) 

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.8.5/commit]

### Environment information
- PS Vita henkaku 3.6
- mac osx mojave 10.14.6

**Comment by LibretroAdmin** [comment]
Going to assume this can be closed at this point thanks to @Cthulhu-throwaway 's improvements.
