### ISSUE TITLE
[Switch] Ozone menu doesn't change theme

### ISSUE THREAD

**Issue by ShadowOne333** [libretro/RetroArch#10331]
## Description
By going into Settings -> User Interface and changing the menu theme to anything else doesn't have any effect. I had "Basic Black" as my default theme, and with the latest 1.8.5 stable release, I try changing to Basic White, Gruvbox or Nord, and neither of those take effect.
Upon selecting any other besides "Basic Black" the option just resets back to Basic Black again, despite whatever other theme has been selected.
I have tried deleting the .cfg files and it still refuses to work.

### Expected behavior
Select an Ozone menu theme, and have the proper theme be selected and changed upon restart.

### Actual behavior
Selecting any other Ozone theme doesn't have any effect, simply defaults back to the currently used one.

### Steps to reproduce the bug
1. Start RetroArch
2. Go to Settings -> User Interface
3. Change selected theme to any other than the default one.

### Version/Commit
RetroArch 1.8.5 stable

### Environment information
- OS: Nintendo Switch - Horizon OS

**Comment by jdgleaver** [comment]
Do you have the setting `Use preferred system color theme` enabled? (under `User Interface > Appearance`)

This disables manual theme selection.

**Comment by ShadowOne333** [comment]
That did it.
I thought I did change that one to disabled before setting the theme, but looks like I didn't.
Thanks for that!
I will now close the issue.

**Comment by jdgleaver** [comment]
Great, thanks for confirming this :)

PR #10340 should hopefully clarify the settings here (I agree that it's currently a bit confusing!)

**Comment by ShadowOne333** [comment]
Awesome, that would help other people so they don't make the same mistake I did.
Thanks again! :D
