### ISSUE TITLE
[Feature Request] Option / task under Playlist Manager to sort alphabetically each playlist

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#10359]
Currently RA allows users to decide whether they want to view all Playlists sorted by alphabetical order. This is controlled through the boolean option "Sort playlists alphabetically", located under Settings -> Playlists.

It could be very useful to also have another option for sorting entries of each individual playlist under the Playlist Manager and have it as a task that saves the re-sorted playlist to disk. 

This would make it possible to:
- choose whether you want one specific playlist to be sorted alphabetically, while maybe leaving other playlists set to a personalized order;
- reorganize an LPL file that was modified manually and saving the re-sorted version permanently.

I have tried to work on this and basically did most of the framework, but I am still clueless about how to properly write / edit a RA task. So I would be more than happy to see this feature implemented by someone definitely more experienced than I could be at this point.

**Comment by jdgleaver** [comment]
This would be a useful feature!

It doesn't actually need a task (if a playlist is sorted, then it gets sorted automatically each time it is loaded), but it would need a new item of playlist metadata - this means it could only be enabled for playlists saved using the new format (since we've already used up all the spare space in the old format files). Not an issue for most users, I think.

I currently seem to have gotten myself tied up with some substantial refactoring of the font rendering code, but I can have a look at this issue afterwards.

**Comment by Ryunam** [comment]
I was pretty confident that this suggestion would meet your approval, @jdgleaver :)
Indeed this would be very handy when micro-managing individual custom playlists.

I thought of a task simply because I was looking at  both “Reset core associations” and “Clean playlist”: both features cycle through entries of a specific playlist, do what they need to do through a defined task and update the result to disk.

I was trying to copy (and learn from) those two options respectively, but that’s when I got lost in the code and could not really make much sense of anything else. Looking forward to anything you can devise on the matter.

**Comment by jdgleaver** [comment]
Yeah, the task system isn't beginner friendly ;)

Took me quite a while before I felt confident with it (and even then, I only discovered some super annoying threading issues just a couple of weeks ago, and had to change a bunch of stuff...). It's a great thing to have (ultimately we want everything possible to run on task threads, to prevent locking the user interface) - but if we can do simple things without it then that's the way to go!

I reckon I can get this done without too much trouble - hopefully at the end of next week or so.

**Comment by jdgleaver** [comment]
Okay, I think this should do the trick: #10434
