### ISSUE TITLE
(Menu) "Restart RetroArch" not working if folder name contains a space

### ISSUE THREAD

**Issue by Gildum** [libretro/RetroArch#10351]
## Description

"Restart Retroarch" option in "Main Menu" doesn't restart Retroarch. This happens ony if you rename the RetroArch folder with a space in it, e.g.: "RetroArch 1.8.5"

### Expected behavior

Retroarch should quit and restart automatically after pressing "Restart Retroarch".

### Actual behavior

Retroarch quits.

### Steps to reproduce the bug

Rename the Retroarch folder to include a space, e.g.: "RetroArch 1.8.5"
Start Retroarch and press "Restart Retroarch" in the "Main Menu".

### Bisect Results

I just tested it with RetroArch 1.7.8 and the issue appears here too. So the bug is probably quite older.

### Version/Commit

- RetroArch: 1.8.5

### Environment information

- OS: Windows 7 - 64-bit

-------
So that's a very minor issue, I'm just glad I finally found the cause and a workaround.

**Comment by NilsBloodaxe** [comment]
Still an issue in 1.9.0.  This is also true if the path for RA contains a space, even if the RA folder itself doesn't have a space.

Windows 10

**Comment by nad53** [comment]
I can confirm this happens as well, windows 10 in 2021.

**Comment by gouchi** [comment]
It seems the issue does not appear if you launch it from cmd.

**Comment by gouchi** [comment]
@bslenul I made some test and it seems it is working by changing first parameter to `NULL` from [CreateProcess](https://github.com/libretro/RetroArch/blob/v1.14.0/frontend/drivers/platform_win32.c#L772) call, even if we don't put quoted strings to the path (i.e `args`)

```
CreateProcess( executable_path, args,
      NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi)
```

to 

```
CreateProcess( NULL, args,
      NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi)
```


> The lpApplicationName parameter can be NULL. In that case, the module name must be the first white space–delimited token in the lpCommandLine string. If you are using a long file name that contains a space, use quoted strings to indicate where the file name ends and the arguments begin; otherwise, the file name is ambiguous. 


[Source](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa)

**Comment by goostoy** [comment]
Hi, I have the same problem, if there is Cyrillic in the folder path, then the "restart" item does not work. If the path is completely in Latin letters - it works. Win7x64

**Comment by gouchi** [comment]
@goostoy you should open a new issue with your problem. Thank you.
