### ISSUE TITLE
1.8.5 PPSSPP on Switch crashes upon game load.

### ISSUE THREAD

**Issue by ZeROOFALL** [libretro/RetroArch#10366]
Latest retroarch revision seems to have broken PPSSPP. Tried swapping out the core with last working one in 1.8.4 and still crashes upon loading game. Was working fine before latest revision was released. All assets, bios and fonts were in working order before update. If one could tell me how to save a log after a crash I'll be sure to upload it.

**Comment by m4xw** [comment]
PPSSPP Asset update is mandatory.
