### ISSUE TITLE
Ozone sidebar icons are blurry

### ISSUE THREAD

**Issue by im-4-potato** [libretro/RetroArch#10363]
## Description

The icons in the sidebar of the Ozone driver are blurry, while the icons on the right in the main part of the UI are not.

EDIT: Looks like the RetroArch icon in the top left is blurry as well.
![Screenshot from 2020-03-28 14-28-06](https://user-images.githubusercontent.com/62815710/77834372-7cbeb380-7101-11ea-83a9-7b386774c7c4.png)

### Expected behavior

Consistent icon resolutions.

### Actual behavior

Blurry icons.

### Steps to reproduce the bug

1. Enable the Ozone menu driver.

### Environment information

- OS: Arch Linux
- Display: 4K, unsure if this is relevant, but I would imagine these icons look fine at 1080p.

**Comment by soredake** [comment]
![image](https://user-images.githubusercontent.com/5204968/78128637-e818c600-741e-11ea-8596-5cebb099d4dd.png)
Slightly blurred on 1080p

**Comment by jdgleaver** [comment]
Once this gets merged, updating your assets should fix the issue: https://github.com/libretro/retroarch-assets/pull/353  :)
