### ISSUE TITLE
Recommend installing the RetroArch package for Linux?

### ISSUE THREAD

**Issue by candrapersada** [libretro/RetroArch#10373]
Recommend installing the RetroArch package using Flatpak, Snap or PPA?

**Comment by guoyunhe** [comment]
Whatever works best for you.

**Comment by gouchi** [comment]
>  Only RetroArch bugs should be filed here. Not core bugs or game bugs
>  This is not a forum or a help section, this is strictly developer oriented 

[Source issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md).

@candrapersada It would have been better if you posted your question to our [forum](https://forums.libretro.com/c/retroarch/retroarch-linux/24) or [discord](https://discordapp.com/invite/27Xxm2h) channel.

Thank you.

**Comment by RobLoach** [comment]
Try the PPA. If that doesn't work, try one of the other ones.
