### ISSUE TITLE
[WiiU] DSI exception in strlen

### ISSUE THREAD

**Issue by eku** [libretro/RetroArch#10379]
## Description

When starting an entry from the playlist or even when assigning a core to an entry in the playlist, a DSI exception occurs in strlen.

I checked the playlist file with jsonlint for syntactical correctness.

![screenshot](https://user-images.githubusercontent.com/418685/78169345-84f45700-7451-11ea-807c-eeed67ef3ed3.jpg)

### Expected behavior

Core with game starts.

### Actual behavior

DSI exception in strlen.

### Steps to reproduce the bug

1. Run RetroArch on a WiiU
2. Install the provided [playlist.zip](https://github.com/libretro/RetroArch/files/4416699/playlist.zip).
3. Start an entry from the playlist.

### Bisect Results

Sorry. No bisect.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.5 Git 9729b5a

### Environment information

- OS: WiiU, PAL version

- Compiler: -

**Comment by jdgleaver** [comment]
Could you please check whether this fixes the issue? #10385

**Comment by eku** [comment]
@jdgleaver well, now it crashes within ```strlcpy_retro_``` in ```action_ok_playlist_entry_collection```.

**Comment by jdgleaver** [comment]
Ugh... Okay, the issue is that you have a very broken playlist, but RetroArch absolutely should not crash because of this. I fixed the playlist saving code, but the issue propagates through to many other places as well...

I should be able to sort this out. Got a lot of things piling up at the moment, though - I'll get on it as soon as I can!

**Comment by eku** [comment]
What's wrong with my playlist? Most of the entries with an valid checksum have been auto-generated by RetroArch's scan content function.

**Comment by jdgleaver** [comment]
It's entries like this:

```
    {
      "path": "sd:/roms/scummvm/Loom (FM-Towns, German)/Loom.scummvm",
      "label": "Loom",
      "core_name": "ScummVM",
      "crc32": "8AA8FAED|crc",
      "db_name": "ScummVM.lpl"
    },
```

...where the the `core_path` field is missing entirely (I don't actually know how that can even happen, TBH - this has a CRC, so you didn't edit that yourself, right?)

But in this case, RetroArch should fallback to sensible behaviour rather than crashing  :)

**Comment by jdgleaver** [comment]
Okay, this should fix the broken playlist handling: https://github.com/libretro/RetroArch/pull/10421

Please let me know if there are any remaining issues!
