### ISSUE TITLE
Retroarch freezes immediately on startup.

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#10409]
## Description

Hard freeze on startup. Around 20% of the time at best, it will start correctly. Otherwise, kill process and try again.

### Expected behavior

A momentary stutter when initially starting, but otherwise no issues.

### Actual behavior

Hard freeze on startup.

### Steps to reproduce the bug

1. Start Retroarch.

### Bisect Results

23ba478f821fc895b43766d0be5a8d96e371c6cf is the first bad commit

### Version/Commit

0716fa02d64fafb12c399b973f0ed41b50fb267c

### Environment information

- OS: Linux Mint 19.3
- Compiler: gcc 8.4.0 (Ubuntu 8.4.0-1ubuntu1~18.04)

**Comment by yoshisuga** [comment]
I'm seeing what looks like a thread deadlock on startup as well, on iOS. The deadlock can happen shortly after startup, or after interacting with the UI for a little bit. Reverting the commit locally seems to resolve the issue.

Can we get more background info on what exactly PR #10399 addresses? It looks like a pretty significant change, and it's not clear if the issue being addressed is severe.

**Comment by Sanaki** [comment]
If I had to guess, this may resolve the somewhat rare issue where exiting a game hangs on the achievement load task somehow not being finished.

**Comment by jdgleaver** [comment]
There was an obvious error in PR #10399! Hopefully this should fix the issue (it does at my end): https://github.com/libretro/RetroArch/pull/10412

**Comment by Jamiras** [comment]
> If I had to guess, this may resolve the somewhat rare issue where exiting a game hangs on the achievement load task somehow not being finished.

Exactly. When shutting down the achievements code, if the load task hasn't finished, we cancel it and _wait indefinitely_. 
https://github.com/libretro/RetroArch/blob/ff3b033815f8ffedded34b95faf1ed4a9242fbb5/cheevos-new/cheevos.c#L1314-L1328

The cancel was occasionally not doing anything because the task didn't appear to be in the queue.

**Comment by jdgleaver** [comment]
@Jamiras Yes, that cheevos issue certainly did need fixing! Good work tracking that down.

The regression here was easily solved, so all's well in the end  :)
