### ISSUE TITLE
Citra on Retroarch crashes instantly but not standalone

### ISSUE THREAD

**Issue by BoldWarriorHS** [libretro/RetroArch#10405]
## Description

For a long time I have used Citra to emulate 3ds games as a standalone program. Recently, I installed the Citra core through RetroArch, but upon launching a ROM the program crashes instantly. Standalone Citra, however, does not and runs the game correctly.

### Expected behavior

Retroarch opens Citra and runs the rom.

### Actual behavior

Retroarch immediately crashes upon selecting run. Here is the log:

[retroarch.log](https://github.com/libretro/RetroArch/files/4434701/retroarch.log)

This seems to be some sort of openGL error - I checked to make sure my CPU and GPU (i7-8700k and GTX-1060, respectively) support OpenGL 4.5 (they do) and updated to the latest Nvidia drivers, which did not solve the problem.

### Steps to reproduce the bug

1. Download Retroarch and Citra core, as sell as standalone Citra.
2. Run the ROM on both.
3. Citra standalone runs, Citra on RetroArch doesn't.

### Version/Commit
You can find this information under Information/System Information

Retroarch version 1.8.5

### Environment information

- OS: Windows 10 Home version 1903 x64

**Comment by m4xw** [comment]
That standalone citra works is irrelevant here.
Do other GL cores work? Like Mupen64plus-Next?
If it does I'd like to redirect you to https://github.com/libretro/citra/issues and close this Issue.
However it's currently not much active, but thats your best bet.
The issue will likely get lost here.

**Comment by BoldWarriorHS** [comment]
Both DeSmuMe and mGBA work fine. I believe they are both GL based? Also, I mentioned that Citra standalone works because when creating an issue the issue template claims that 
> Only RetroArch bugs should be filed here. Not core bugs or game bugs.

Mentioning that standalone works shows that this is not a bug with Citra itself but either RetroArch or Libretro.

**Comment by m4xw** [comment]
> Mentioning that standalone works shows that this is not a bug with Citra itself but either RetroArch or Libretro.

This doesnt mean much, like i said.
Both of the cores you quoted run without GL by default iirc.

**Comment by BoldWarriorHS** [comment]
I figured it out: I had to turn on 'Enable Shared Hardware Context' in Settings -> Core after turning on 'Show Advanced Settings' in Settings -> User Interface. Core worked after that. Not sure why this isn't enabled by default since it seems to break the core if it is disabled.

**Comment by Dae-Hang-Sook** [comment]
This did not fix my issue with this. changing the video_driver in the cfg file to d3d makes retroarch unusable. Someone please help figure this out.

**Comment by hizzlekizzle** [comment]
Correct. This core doesn't work with d3d, only OGL. If you have an AMD GPU, it's likely related to this: https://github.com/libretro/citra/issues/110

**Comment by PrivacyFriendlyMuffins** [comment]
> Correct. This core doesn't work with d3d, only OGL. If you have an AMD GPU, it's likely related to this: https://github.com/libretro/citra/issues/110

What is D3D? Also, is there a way to change the core-specific video output type? There doesn't seem to be as far as I can tell, but I might be missing something...
