### ISSUE TITLE
Weird bug with the Ozone sidebar when moving mouse cursor outside of RA window to the left.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10419]
## Description

When using Ozone in window mode, while in a submenu (when the sidebar on the left hides), if you move the mouse cursor outside of the window it begins to act weirdly. It's like the main window is stuck to the current submenu but the cursor is in fact navigating in the sidebar.

### Expected behavior

Completely ignore the sidebar when it's hidden.

### Actual behavior

It seems like you're navigating from the sidebar even if it doesn't show, which confuses RA.

### Steps to reproduce the bug

1. Open RA in window mode.
2. Make sure the cursor is on the window.
3. Navigate to a submenu, so the sidebar hides.
4. Move the cursor outside of the window, to the left.
5. Start navigating using up and down arrows.

Here's a video showing the bug: https://youtu.be/qcfVzecToAI

### Bisect Results

No idea, sorry :x 

### Version/Commit

- RetroArch: 1.8.5 / b01aabf (latest nightly when typing this)

### Environment information

- OS: Windows 10 (edit: just tested on my Linux Mint VM, the bug doesn't happen).

**Comment by jdgleaver** [comment]
Ah, I think I see what's happening here: it looks like Windows reports a negative coordinate when the cursor goes 'off screen', which breaks a comparison. I develop on Linux, where the pointer coordinates are always sane - so I never encountered anything like this  :)

I'll try to get a fix done as soon as possible.

**Comment by jdgleaver** [comment]
Okay, should be fixed once this gets merged: https://github.com/libretro/RetroArch/pull/10426  :)

**Comment by bslenul** [comment]
Just tried your commit, seems like it's working like a charm :D 
Didn't expect a fix so soon, thank you so much for this! ❤️ I have the habit of putting my cursor on the left for whatever reason so it was getting a bit annoying :p 

I'll close the issue as soon as the commit is merged, just to be 200% sure.

**Comment by jdgleaver** [comment]
Hey, no problem, and thanks for testing! I was cleaning up some other Ozone stuff anyway, so it was no trouble to fix this :)
