### ISSUE TITLE
RetroArch crashes with 30 or more playlists using d3d12 & ozone

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#10435]
Hey guys,

## Description

RetroArch crashes with 30 or more playlists using d3d12 & ozone drivers.

Use 29 playlists, it'll run just fine

Use d3d11 or other driver (with more than 30 playlists), it'll run fine. 

### Expected behavior

Not crash

### Steps to reproduce the bug

1. Copy & paste any playlist, so you have 30 in the playlist folder
2. Open RetroArch, use the keyboard arrows to do down, to the lists
3. It'll crash in the third list

![image](https://user-images.githubusercontent.com/5431285/79022499-77775500-7b54-11ea-8837-737400350999.png)

### Version/Commit

- RetroArch 1.8.5 stable release

### Environment information

- OS: Windows 10

**Comment by sergiobenrocha2** [comment]
Exception code=0x80000003 flags=0x0 at 0x00007FFED7B60BB2

**Comment by hizzlekizzle** [comment]
Is it only with Ozone menu?

**Comment by sonninnos** [comment]
No crash here even with 40 playlists.
