### ISSUE TITLE
(Ozone) AI Service menu should adapt to enabled/disabled state

### ISSUE THREAD

**Issue by hhromic** [libretro/RetroArch#10468]
## Description

In Ozone, the AI Service menu always show all the options regardless of the enabled/disabled state of the AI Service itself. Screenshot below:

![image](https://user-images.githubusercontent.com/5802993/79599240-13690980-80dd-11ea-9ea1-ac039605e139.png)

This is in contrast to other similar menus that hide all the related options when the subject of the menu is disabled. For example:

* Settings -> Onscreen Display -> Onscreen Overlay
* Settings -> Onscreen Display -> Video Layout
* Settings -> Onscreen Display -> Onscreen Notifications
* Settings -> Accessibility

All of the above display no further options when disabled:

![image](https://user-images.githubusercontent.com/5802993/79599475-70fd5600-80dd-11ea-8a2b-0b11390dd0cd.png)

And display all relevant options when enabled:

![image](https://user-images.githubusercontent.com/5802993/79599487-79ee2780-80dd-11ea-8f0f-64321d0af91c.png)

The AI Service menu should be consistent with all of these.

Also another minor nitpick, the *AI Service Enabled* option should be the very first in the menu.

### Expected behavior

The AI Service menu to be consistent with other menus of similar configuration options.

### Actual behavior

The AI Service menu does not behave the same as other similar menus. In addition, the enable/disable "master option" is not the first menu item as in other menus.

### Steps to reproduce the bug

1. Go to Settings -> AI Service
2. Observe how the menu does not behave/look like other similar menus such as Settings -> Onscreen Display -> Onscreen Overlay

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `1.8.5` stable

### Environment information

- OS: Windows 7 x64

**Comment by jdgleaver** [comment]
This should solve the issue: #10470  :)

**Comment by hhromic** [comment]
As usual, thanks @jdgleaver for your work!
I knew it would be easy peasy for someone senior with the codebase :) Appreciated!

**Comment by jdgleaver** [comment]
You're welcome!  ;)
