### ISSUE TITLE
Graphical menus are broken on Wii U

### ISSUE THREAD

**Issue by vaguerant** [libretro/RetroArch#10476]
## Description

On Wii U, the graphical menu layouts are tied to the aspect ratio set in the video settings rather than the display's aspect ratio. As an example, here's somebody's photo (not mine) from Reddit describing this issue, where the XMB icons are being positioned according to 4:3 while the rest of the menu is in 16:9.

![Image from Reddit](https://i.redd.it/xliv93095ws41.jpg)

This is not an XMB issue specifically, however, it's common to all graphical UIs. Changing the aspect ratio to 16:9 corrects the icon positioning in the graphical menus, but obviously requires the user to play all their games in 16:9, which is not intended as seen in older builds or on other platforms.

### Expected behavior

The graphical menus working correctly.

### Actual behavior

They're not.

### Steps to reproduce the bug

1. Install the current version (1.8.5 or newer) of RetroArch on Wii U.
2. Set a menu driver that is graphical (the default, Ozone, is a perfect example)
3. Look at the menu.

### Bisect Results

I'll do a jank bisect of the stable versions in a bit and edit it in here. I have no Wii U build environment set up and don't plan to set one up, sorry, so that's as close as I'll get. The issue seems to have occurred some time after mid-January, which I'm ... 85% sure is when I updated previously.

**EDIT:** Well that was fast, 1.8.4 did not have this issue, so it was introduced some time between that and 1.8.5 stable.

**EDIT 2:** While the nightlies don't stretch all the way back to 1.8.4, I tested the earliest one still on the buildbot and it didn't have the issue, so I went ahead and bisected using the available nightly builds. The last good nightly was 2020-03-09 ee2f25b. The first bad nightly was 2020-03-10 e2a7038.

Here's the link to the diff of those two commits, which covers a total of 41 commits: ee2f25b...e2a7038

### Version/Commit
You can find this information under Information/System Information

- RetroArch: d5d4c1a

### Environment information

- OS: Wii U 32GB, PAL region, 5.5.4 firmware

**Comment by hizzlekizzle** [comment]
Thanks for doing the legwork on this. You've narrowed it down very well. It's unfortunate that there were 40(!) commits on that one day, but this is a great start anyway.

**Comment by jdgleaver** [comment]
@vaguerant Excellent detective work!

I don't have a WiiU, but the diff you highlighted contains an obvious error.

I believe this should fix it: #10482

Could you please test once it gets merged?

**Comment by hizzlekizzle** [comment]
merged now, so it should make it down to the buildbot soon.

**Comment by vaguerant** [comment]
Just grabbed the latest nightly and can confirm this issue is completely resolved. Great work, @jdgleaver!

That said, in the process of testing it out, I did find an older issue that seems like it might be similar/related, The basic gist is that video rotation seems to affect the graphical menus when it should only be affecting the loaded content. e.g. In Ozone, the highlight bar indicating which menu item you currently have selected becomes rotated, while the rest of the menu is still upright:

Video Rotation: Normal
![IMG_20200421_155158_hdr](https://user-images.githubusercontent.com/5259025/79832648-3a7d4f00-83ed-11ea-819c-cccf941e6780.jpg)

Video Rotation: 90 deg
![IMG_20200421_155216_hdr](https://user-images.githubusercontent.com/5259025/79831800-77e0dd00-83eb-11ea-9c8a-1148828257ae.jpg)

The effect on XMB is minimal, it seems to rotate the background gradient, which doesn't affect usability at all but is still unintended behavior, of course.

All of this is kind of secondary to the fact that content rotation doesn't function correctly on Wii U anyway. It appears to be identical to my old 3DS issue, #8754, where contents can be flipped on the vertical and horizontal axes, but not rotated. Since rotation doesn't work on Wii U, this cosmetic menu bug is probably unlikely to be encountered in normal use by anybody currently.

Anyway, the menu rotation issue predates the alignment one jdgleaver just fixed, as it already existed in the March 9 nightly. I'll try to get a better idea of when it was introduced and report back. I won't close this issue myself but if you prefer to have the rotation issue filed separately, feel free to close this one and I'll start a new issue.

**Comment by jdgleaver** [comment]
@vaguerant Thanks for testing! Glad the menu text works correctly now  :)

Regarding the rotation bug, that does look kinda related but (as with the 3DS) this involves some low level gfx driver stuff. This is tricky to deal with, and it's not something I can work on 'blind' - it needs a WiiU developer with real hardware for testing. Hopefully someone fitting the bill will notice this issue!

Having said that, if you can bisect the *content* rotation bug, I can have a look for obvious slip-ups in the code :)

**Comment by vaguerant** [comment]
Actually the content rotation might have been something on my end. I just tried renaming my `retroarch.cfg` to get a fresh config and now content rotation is working correctly.

**Comment by hizzlekizzle** [comment]
Awesome job gang. I'm gonna close this one out.

**Comment by vaguerant** [comment]
@hizzlekizzle Just to be clear, the menu rotation bug, as seen in the photo of the Ozone menu's bar turned vertical, is still unresolved. I had mentioned a separate issue that rotation in games themselves didn't work, which was incorrect as it was related to shader usage. But with or without shaders, the graphical menus still have rotation issues.
