### ISSUE TITLE
[feature request] yaml configuration files

### ISSUE THREAD

**Issue by Kallin** [libretro/RetroArch#10499]
Would anyone be interested in using YAML for retroarch configuration instead of the flat .cfg files that are in use currently? Personally I find it a bit unwieldly to have all of those options in the various configs sitting next to each other at the same level. We could probably support both YAML and the original format concurrently if that was desired, though moving strictly to YAML would allow some enhanced structure, such as using a list for the 16 'input_player' configs vs. simply name-spacing them away from everything else. Even the namespacing would be valuable IMO, as I could easily collapse those sections I'm not interested in and make it easier to navigate the options.

**Comment by hizzlekizzle** [comment]
I believe it were to be anything it would need to be JSON.

**Comment by dude1286** [comment]
To human eye, yaml and json are extremely similar. I've been using them both in my profession recently. In the python and ruby languages, yaml readers can load json files correctly, I don't know about C++ yaml libraries.

**Comment by Kallin** [comment]
@hizzlekizzle why would it have to be JSON?  C++ limitation? 
I definitely prefer reading YAML over JSON; it's a bit more user-friendly too for the less technical folk going in and manually editing configs.

**Comment by Kallin** [comment]
https://github.com/jbeder/yaml-cpp . 
I've never made any contributions to this project, but if this is something people were interested in at all I'd be happy to give it a shot. If there's serious resistance from the core committers that would be good to know too :)

**Comment by hizzlekizzle** [comment]
If the only YAML implementations are C++, then that's indeed a problem, but it's mostly because we already standardized on JSON for our other files (playlists, etc.), so we wouldn't want to mix and match.

**Comment by Kallin** [comment]
Fair enough; I saw JSON being used in the playlists. If that's the case, would there be any interest in converting configs to JSON? I love how the default is now to split core-configs into their own files. So much easier to maintain.

**Comment by hizzlekizzle** [comment]
I'm personally ambivalent. There are pretty good reasons to switch, and there are some good reasons not to. Perhaps someone else will have an opinion one way or the other, though.
