### ISSUE TITLE
Player 2 controller only works with random button on player 1 controller pressed (RetroArch-RPI)

### ISSUE THREAD

**Issue by d4m4s74** [libretro/RetroArch#105]
When testing I noticed a problem. When using RetroArch, To be more exact the SNES emulator, and at least some roms (I personally tested Donkey Kong Country, someone else noticed it on Super Mario Kart and NBA Jam) the player 2 controler only functions when someone holds down a button on controller 1. 

The controllers I use are original SNES controllers, in combination with the Gamecon drivers. when I switch the physical controllers, and when I switch the two controllers in the config file the problem persists.

**Comment by booherbg** [comment]
Can confirm -- this problem still exists. I'm using two iBuffalo controllers for SNES.
