### ISSUE TITLE
A12 ios13 failed to load libretro core

### ISSUE THREAD

**Issue by assgod** [libretro/RetroArch#10509]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Big problem! A12 ios13 devices cant load a game propery, it always says “ failed to load libretro core”. I tried 1.77, 1.79, 1.85. 
There is one time I load a MAME game sucessfully on 1.85, but I cant add it into favorite. And when I reopen retroarch, there is no ways to load a game anymore.

My device is ipad mini5 , and my iphone6s always works very well with 1.77 on ios12.  So the problem ocurrs A12 ios13.

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by WeedyWeedSmoker** [comment]
iOS 13.4 solves the issue

**Comment by assgod** [comment]
> iOS 13.4 solves the issue

oh man, we dont want 13.4. we can only jailbreak on ios13-13.3, and 13.4 do not support custom controllers

**Comment by WeedyWeedSmoker** [comment]
So… Do you use the Cydia repo version ?

**Comment by assgod** [comment]
> So… Do you use the Cydia repo version of RetroArch then ?
> 
> _(BTW 13.4.1 has been jailbroken, but we're waiting for Apple to update again before the jailbreak can become public…)_

I downloaded it from retroarch.com

**Comment by WeedyWeedSmoker** [comment]
Download it from here… https://forums.libretro.com/t/ios-tvos-retroarch-1-8-5-and-other-emulators-download-cydia-repo/27503

**Comment by assgod** [comment]
> Download it from here… https://forums.libretro.com/t/ios-tvos-retroarch-1-8-5-and-other-emulators-download-cydia-repo/27503
I try the cydia version a moment ago and the problem is different. the assets extracting failed.

![FD60B225-85FD-4A18-AD3C-9E41180C8885](https://user-images.githubusercontent.com/6192722/80304794-f8884a80-87ea-11ea-9107-6bd6e9bd8662.png)

**Comment by assgod** [comment]
> Download it from here… https://forums.libretro.com/t/ios-tvos-retroarch-1-8-5-and-other-emulators-download-cydia-repo/27503

And I reinstalled 1.77 and it shows”failed to save config ...” too.
![3903CAEF-82E1-46D1-9730-94A06632465C](https://user-images.githubusercontent.com/6192722/80305881-52404300-87f2-11ea-96ce-7085b8ab1d58.png)

**Comment by assgod** [comment]
> Download it from here… https://forums.libretro.com/t/ios-tvos-retroarch-1-8-5-and-other-emulators-download-cydia-repo/27503

I think I may found out the problem from filza: “ipadOS13 use ‘/var/mobile’ instead of ‘/private/var/mobile’, ipadOS dont have ’/pravate’ folder.”

**Comment by WeedyWeedSmoker** [comment]
It's not correctly escaping the sandbox… Try to uninstall RetroArch (all versions) then try the RetroArch Cleaner in Cydia too…

You can then try to reinstall RetroArch from Cydia

**Comment by assgod** [comment]
> It's not correctly escaping the sandbox… Try to uninstall RetroArch (all versions) then try the RetroArch Cleaner in Cydia too…
> 
> You can then try to reinstall RetroArch from Cydia

When I try to install retroarch cleaner in cydia， it seems not supporting ipadOS.
![C2116A7F-60B4-416A-8FD3-0AFDD3A43E60](https://user-images.githubusercontent.com/6192722/80322310-cb718180-8856-11ea-9642-52c2451b3a47.jpeg)

**Comment by WeedyWeedSmoker** [comment]
Ok, I fixed the cleaner by making a separate one for the AppleTV…

**Comment by assgod** [comment]
> Ok, I fixed the cleaner by making a separate one for the AppleTV…

yeah, I can install the cleaner now. But there is a problem with your cydia repo, I tried 7 times and it always tells “md5 mismatch...” and then download failed in a 50%-70% progress.
Downloading the cleaner, dolphineIOS has the same ‘md5’ problem in your cydia repo.

So I install your 185 from https://www.mediafire.com/folder/3b23i8j3tj062/RetroArch_1.8.5  yesterday. I have no ways to install your 185 from cydia.

**Comment by assgod** [comment]
> Ok, I fixed the cleaner by making a separate one for the AppleTV…

ios14 is coming, I would like waiting for a version fot ios14 , this problem may disappear by himself.  Thank you for your support.
