### ISSUE TITLE
[feature request] Allow saving overlays per playlist, in addition "per core" or per content"

### ISSUE THREAD

**Issue by Zephyr-Battiassi** [libretro/RetroArch#10506]
## Description

Currently on 1.8.5 you can only save overlays per core or per content.
When you have a core that allows various system emulation (like Picodrive, that support MS,GG,GEN, CD or 32X), if you store by example, the megadrive overlay per core, 
it will also apply the same to Master System games and 32x games, that should have 
different overlays.

Enabling "overlay per playlist" can solve the issue.
Would you be so kind to consider it for future commits?.
It's a "quality of life" change.

### Expected behavior

Allow saving the selected overlay for the playlist, so all the games in same
playlist will have the same default overlay. Later if you want, you can manually assign
certain overlays for some games that have one made and you may like 
(by example, many snes games have tailor made overlays, like Chrono Trigger, 
Castlevania, etc..).

### Actual behavior

Currently you have to apply the overlay per core (which, as I explained above, 
will apply the same overlay to different systems if your core supports
more than one content type, like Picodrive).

Yes, you can apply the overlay per content, but if you have many games, it's a pain in the ##s to
apply to each one, manually. If there is any trick for this, I don't know it.

### Steps to reproduce the bug

1. Choose Picodrive core for Master system, Megadrive and 32x content.
2. Apply that core to all your sega games.
3. Load a Master System content to play and apply a Master System overlay  .
4. Save the overlay for this core.
5. If you change you mind and now want to play a Megadrive game, 
it will load the Master system overlay.
6. If you store a Megadrive overlay per core, Master System games will now have Megadrive overlay.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.5 stable

### Environment information

- OS: Windows 10 x64
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
I think this is probably going to be a "wontfix", since this is what the 'content directory' overrides and presets are for. That is, put all of your 32x games in a directory and then save a content directory override for your overlay.

**Comment by Zephyr-Battiassi** [comment]
I have my roms organized by directory, and somehow I didn't saw that "content directory" override option.
 
I will use it as it seems good enough, thanks @hizzlekizzle .

**Comment by hizzlekizzle** [comment]
Sounds good. Good luck!
