### ISSUE TITLE
Searching/Browsing long playlist with thumbs crashes on Vita

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#10556]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Searching for a game in a long list with thumbnails crashes on Vita after the playlist jumps to the first entry. Browsing through hundreds of entries with thumbnails also makes the list scrolling slow, then crashes.

It seems to only happen when all the thumbs are present. Without thumbnails, it all works. Maybe it runs out of memory or something?

### Expected behavior

It should not crash

### Actual behavior

It crashes

### Steps to reproduce the bug

1. On Vita, go into Final Burn Neo playlist with all roms and thumbnails present
2. Press triangle to open search keyboard
3. Enter ghoul and press start to find Ghouls'n'Ghosts
4. Observe the playlist jumping to Ghouls'n'Ghosts and then crashing

Alternatively,
2. Scroll downwards through a few hundred titles, observe scrolling becoming slower and slower, thumbnails not showing anymore, then a crash

### Version/Commit
You can find this information under Information/System Information

- RetroArch: buildbot bd319de

### Environment information

- OS: Vita

**Comment by jdgleaver** [comment]
I'm not sure about the search issue, but the fast scrolling is certainly a disk speed/RAM issue.

Every time the menu selection changes, it triggers a thumbnail load task. If this isn't complete by the time you move to the next entry, you get a backlog. On a slow system, the task queue will just keep getting bigger and bigger, until RAM is exhausted.

When implementing the thumbnail handling code, I tried to find an effective way of cancelling unwanted image load tasks, but it's a really difficult and nasty problem... I guess I will have to try again when I get the chance...  :)

In the meantime, glui should be a *little* less susceptible to this issue - or you can use rgui and set `Settings > User Interface > Appearance > Thumbnail Delay (ms)` to 256 to avoid the problem completely.

**Comment by i30817** [comment]
Do you use a queue instead of a list to hold the thumbnail tasks? I've often found that for large backlogs of IO users can often be appeased even without cancelling tasks by making the most recent task go to the head of the queue of tasks to process.

You can also try some kind of view to model query to see if the task is visible, disabling loading while moving or wait until there is no movement for 0.5 seconds to load a thumbnail (this last is probably the simpler alternative?).

**Comment by jdgleaver** [comment]
@rsn8887 Could you please test the playlist scrolling performance on the latest nightly using `glui` with `Settings > User Interface > Appearance > Landscape Thumbnail View` set to `Desktop`?

If it works acceptably, then we may have to think about moving the other menu drivers over to the same thumbnail loading model...

**Comment by u4113057** [comment]
> @rsn8887 Could you please test the playlist scrolling performance on the latest nightly using `glui` with `Settings > User Interface > Appearance > Landscape Thumbnail View` set to `Desktop`?
> 
> If it works acceptably, then we may have to think about moving the other menu drivers over to the same thumbnail loading model...

i just had the same problem and i change to glui and desktop as you said. it work smoothly!!

**Comment by Thiefsie** [comment]
> @rsn8887 Could you please test the playlist scrolling performance on the latest nightly using `glui` with `Settings > User Interface > Appearance > Landscape Thumbnail View` set to `Desktop`?
> 
> If it works acceptably, then we may have to think about moving the other menu drivers over to the same thumbnail loading model...

I found that doing what you suggested also works 100% fine on Vita - apart from glui not the best on Vita. No more GPU crashes at least.

**Comment by jdgleaver** [comment]
It's taken years, but this should finally be fixed once https://github.com/libretro/RetroArch/pull/13947 is merged...

**Comment by LibretroAdmin** [comment]
Reopened, awaiting feedback from person who reported this...
