### ISSUE TITLE
[Feature Request] Add MM/DD/YYYY etc to Style of Date and time

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#10579]
Guys are gonna hate me. 

Many moons ago I ribbed you about getting the imperial/states formats in there, and by and large you did.   Most of the european options have an american counterpart.

however, in seeking out parity with how i have my runtime labels displayed - the date/time option for the UI is missing both of the following

MM/DD/YYYY HH:MM (AM/PM)
MM/DD/YYYY HH:MM:SS (AM/PM)

It has MM-DD-YYYY but that just looks awful, and its certainly not very british of you guys to hog the good looking ui formats all to yourselves ;p

as a bonus, for completions sake if someone gets into addressing the aformentioned and its trivial, adding a parallel to the YYYY options for just YY would flesh it out 100% i think.

**Comment by im4potato** [comment]
Is the issue you're referring to just the use of `-` instead of `/`? I have already submitted a pull request that fixes this, among other inconsistencies with date and time.

PR #10574

**Comment by klepp0906** [comment]
ah, that is likely exactly it then.  A few of the formats had parallels but with the use of - as you mentioned instead of /

I wasnt sure if that was  an intentional thing, or an oversight but i prefer the latter and im sure anyone would prefer that there be some consistency as you put it.

thank you :)
