### ISSUE TITLE
[Windows] RA crashing with xaudio2 audio driver when switching between sound devices while running

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#10571]
## Description

With the current code RetroArch may suddenly crash on certain devices (the hardware I tested was two models of Surface Pro, respectively 6 and 7) whenever headphones are plugged or unplugged from the system while content is running.

The cause of the issue seems to be related to switching between sound devices with the xaudio driver. When headphones are either plugged or unplugged on the Surface Pro, Windows seems to switch to a different sound device with its own volume and name:

- Headphones (Realtek High Definition Audio (SST)) [when they are plugged];
- Speakers (Realtek High Definition Audio (SST)) [when they are unplugged].

As soon as this switch toccurs, RA hangs for a few seconds, then crashes.

### Expected behavior

The shift to another sound device should occur seamlessly and output audio through speakers / headphones, depending on what is the current state (headphones plugged or unplugged).

### Steps to reproduce the bug

1. Start RetroArch on a device with this configuration with headphones plugged on through the headphone port.
2. Start any content
3. While content is running, unplug the headphones from the port.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.5 / 25be09a

### Environment information

- OS: Windows 10 x64 1909
- Compiler: Mingw64

**Comment by Ryunam** [comment]
Seems to be a longstanding issue, as evidenced in this similar thread dating back to 2016: https://github.com/libretro/RetroArch/issues/3392

Perhaps what the xaudio2 driver is missing is a reference to the "Primary Sound Driver" that is listed when using dsound?

**Comment by COMMANDERkev** [comment]
Still having this issue #3392 with xaudio when using a bluetooth speaker and then disconnecting the speaker. 

Build Date: Aug 11 2020
Retroarch: 1.9.0
Git Version: 6388872a54
MinGW 9.2.0 64 bit

**Comment by gouchi** [comment]
Just came across this information from [Xaudio 2.8 changelog](https://docs.microsoft.com/en-us/windows/win32/xaudio2/xaudio2-versions#xaudio-28-windows-8x),

> Device enumeration functionality has been removed from XAudio2; the GetDeviceDetails and GetDeviceCount functions have been removed from the IXAudio2 interface. Apps that want to render to other audio devices on the system must pass a device identifier string to CreateMasteringVoice instead of a device index. The default audio render device can still be created without enumeration.

[Source](https://docs.microsoft.com/en-us/windows/win32/xaudio2/xaudio2-versions)
