### ISSUE TITLE
[feature request] lock the unlocked achievements

### ISSUE THREAD

**Issue by meleu** [libretro/RetroArch#10595]
[this is maybe a note to self, but if another developer would like to work on it before me, be welcome!]

Sometimes cheevos users replay games where they already unlocked some achievements.

As a player, I would like to still receive that dopamine injection that happens when you see the cheevo badge popping on the screen when the conditions for the achievements to trigger are met.

It would be neat to have an option in `Quick Menu` > `Achievement List` to "Relock the unlocked achievements for the current session".

---

@Jamiras @leiradel 
do you think that such feature will require some change on the rcheevos side?

**Comment by Jamiras** [comment]
No `rcheevos` changes would be needed currently. The code in `cheevos-new` parses all achievements, and then deactivates any the user has achieved by clearing the `cheevo->active` flag for them. It should be as simple as resetting that flag and calling `rc_reset_trigger` for each deactivated achievement.

**Comment by meleu** [comment]
Currently if the server has already registered that the user unlocked a cheevo and receives another request to unlock the same cheevo, it responds with an error.

I'm not sure, but I think such behavior together with the feature I'm proposing here would make RetroArch to send a bunch of unnecessary requests to the server.

I think I'm gonna change the server behavior to: if the user has already unlock this achievement, update the timestamp.

**Comment by Jamiras** [comment]
> I think I'm gonna change the server behavior to: if the user has already unlock this achievement, update the timestamp.

If the user really wants their timestamp updated, they can reset the achievement through their profile. If they just want the eye candy, they probably don't care about the timestamps, and keeping the original timestamp makes it easier to calculate stats like "average time per point".

Also, changing this at the server level may impact devs who are activating achievements for debugging purposes in the standalone emulators.

The standalone emulators [simply ignore](https://github.com/RetroAchievements/RAIntegration/blob/02a3a7cc5bcbd20d61711c6ba936084283b5f9c1/src/data/GameContext.cpp#L755-L760) the "error". If you want to change the server, just have it return success on duplicate unlock. The unlock call technically succeeded - the achievement is unlocked after calling it.
