### ISSUE TITLE
It is possible to implement some functions that can be changed dynamically during the session?

### ISSUE THREAD

**Issue by Pietro1994** [libretro/RetroArch#10590]
## Introduction
I want to carry out a project to foresee the realization of some 'on-the-fly' functions, instead of from initial setup, functions that therefore can be dynamically changed during the session.

• Function for dynamic content rotation via hotkey
• Function for dynamic screen rotation (orientation) via hotkey
• Function for horizontal / vertical flipping of contents via hotkey

## Question
it's possible?

## Init
I found a file called 'retroarch.cfg'.
in this file there is a large variety of input types:

- rotation, slowmotion, etc...

where are these commands executed?

**Comment by hizzlekizzle** [comment]
It's possible, but you wouldn't do it through the retroarch.cfg, which is only read from at launch, when it is loaded into memory.

**Comment by Pietro1994** [comment]
how can i do it?

**Comment by hizzlekizzle** [comment]
you would need to implement hotkey triggers for the functions that actually control those things.

**Comment by Pietro1994** [comment]
How could i activate this trigger a level of code?

**Comment by hizzlekizzle** [comment]
That's something you would need to decide/determine as part of your implementation.

**Comment by Pietro1994** [comment]
Here's what I did: I downloaded the retroarch github repository (https://github.com/libretro/RetroArch).
In this repo you can find the entire source code of the program and build it for any system. I did a build for windows, following the guide of libretro, and it worked great! What I can't do is: access the source and find the appropriate file to find the "screen rotate" function. There are several functions in which "rotation" or "rotate" appears, but I cannot find the appropriate function to insert a button to change the state of the screen.
Has anyone done something like this before? Change the hotkeys to start a retroarch function at any time during a game session?
