### ISSUE TITLE
Circular savestates / limit savestates please.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#10593]
###  Description

A short story of my usual behavior when savestates are available: I press that button every 5 minutes, the End.

This makes me a very unhappy boy when i'm playing a core with large emulated memory requirements if i don't remember to reset the value 'from time to time' and a less unhappy boy if i do remember and 'have' to interrupt the game to reset.

### Expected behavior

There should be a option to limit the number of savestates per core or playlist (though this doesn't exist).

### Actual behavior

1.5 gb of savestates in a single play session of PPSSPP or dolphin.

**Comment by hizzlekizzle** [comment]
duplicate of https://github.com/libretro/RetroArch/issues/10471 ? If so, I'll close this one.

**Comment by i30817** [comment]
yes dupl
