### ISSUE TITLE
1.8.6+ Doesn't compile for Wii

### ISSUE THREAD

**Issue by Veritas83** [libretro/RetroArch#10608]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Attempting to compile the latest source per Wii Compilation instructions.

Conflict with ogcsys.h on declaration of nanosleep

<img src="https://i.gyazo.com/702d3a38a2e4d7d60b76c8551516e499.png">

### Expected behavior

Binaries compiled...

### Actual behavior

Makefile.wii.salamander:124: frontend/drivers/platform_gx.o Error 1

### Steps to reproduce the bug

git clone https://github.com/libretro/RetroArch.git retroarch
cd retroarch
make -f Makefile.wii.salamander

### Version/Commit
Whatever is currently on the repo as I post this.

### Environment information

- OS: Debian 4.19.98-1+deb10u1
- Compiler: devkitPPC

**Comment by arthurfreitas96** [comment]
I managed to compile it using devkitppc r29-1.
