### ISSUE TITLE
Opening achievements list crashes retroarch with badges enabled (on new games)

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#10616]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Took me a minute to figure this out!  Ooof.  I just began dabbling with retroarch's achievements.  Outside of some games not displaying them when they should (version issue i imagine) this is the only other hiccup ive ran into.  

Seems if i fire up a game I havent played yet, and go to achievements POOF crash to desktop.   If i restart retroarch, run that same game and look in achievements, now theyre all there fine. 

disable display of badges, this doesnt happen at all.  So its something tied to the badges and how they download or where theyre stored or whatnot id imagine. 

### Expected behavior

The achievements list to open and display badges, minus the crashing part.

### Actual behavior

Badges on = crash on first time loading achievements on new game.   Badges off = business as usual. 

### Steps to reproduce the bug

1. Turn on achievements and display badges
2. find a game you havent played prior that has achievements and run it
3. enter the quick menu, click on achievements and enjoy the desktop shortcut
4. re-open retroarch, return to said game and run it again.  open achievements tab and notice all is well. 

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.86 98daa0d28c

### Environment information

- OS: Win10
- Compiler: [In case you are running local builds]

**Comment by klepp0906** [comment]
does not happen with glcore.  only vulkan

**Comment by Jamiras** [comment]
This is due to accessing uninitialized memory. Apparently glcore just handles it better than vulkan. I'll work on a fix.
