### ISSUE TITLE
Bring j2me as a module in retroarch

### ISSUE THREAD

**Issue by ImanCol** [libretro/RetroArch#10632]
I have seen how Retroarch has expanded more than the emulators. So I would like to be able to enjoy classic phone games of yesteryear made in Java with a module that supports j2me in RetroArch.

It's possible?.

**Comment by gouchi** [comment]
You may try [libretro-JamVM](https://github.com/libretro/libretro-JamVM) core ?

**Comment by ImanCol** [comment]
> You may try [libretro-JamVM](https://github.com/libretro/libretro-JamVM) core ?

I just caught him. I will do it right now.

**Comment by gouchi** [comment]
@ImanCol This issue could be closed as there is [freej2me](https://github.com/hex007/freej2me) ?

Thank you.

**Comment by ImanCol** [comment]
> @ImanCol This issue could be closed as there is [freej2me](https://github.com/hex007/freej2me) ?
> 
> Thank you.

Of course, I'm glad it's over. I'll be playing Edge again. I hope a Symbian solution will come in the future as well.
