### ISSUE TITLE
[Request] Safe area on notched Android devices 

### ISSUE THREAD

**Issue by Loco1911** [libretro/RetroArch#10649]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch does not currently have native support for devices with notch.

### Expected behavior

The application must be configured to add native support for devices with notch according to the documentation, so that the application works in full screen and the notch does not disturb the touch controls: [](https://developer.android.com/guide/topics/display-cutout)

### Actual behavior

Currently only a black bar is seen in the notch part.

### Steps to reproduce the bug

1. Install the retroarch app
2. Open the retroarch app

### Bisect Results

This started when notch phones were released to the market

### Version/Commit

- RetroArch: [1.8.7/f1158b9]

### Environment information

- OS: Android 9 "Pie"

**Comment by ferrazpedro** [comment]
I would also love to see this feature implemented. I know it's basically just eyecandy for the menu, but if would feel a lot more polished, for me.
