### ISSUE TITLE
SRAM auto-save interval not working

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#10644]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I have the save interval set at 10 seconds, however after making a save in game - i watch the save file and after 10 seconds, nil happens.

### Expected behavior

I assumed that after 10 seconds the save would be written to file as a protection against a potential crash or incorrect shutdown taking a save with it. 

### Actual behavior

absolutely nothing.  saves are still not written until i close the content/retroarch. 

### Steps to reproduce the bug

1. Fire up a game (i'm using mesen-s/snes if you want 100% parity) that you have a running save in.
2. Find a save point in said game (i'm using breath of fire) and save
3. watch your srm file and wait.   Nothing happens. 

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.86 82666abbdd

### Environment information

- OS: Win10
- Compiler: [In case you are running local builds]

**Comment by klepp0906** [comment]
added info -  i use retroarch with launchbox fairly often.  (tested both inside and outside of)  I discovered the autosave issue after losing progress as ive always used Process, Close, {{{StartupEXE}}} as part of a quick/clean shutdown ahk script from within the aforementioned.

after discovering the lost save, i tried WinClose, ahk_exe retroarch.exe which did the same job and didnt lose the save.   This has me thinking Process, Close, {{{StartupEXE}}} was always hard-closing RA and thus losing the"on shutdown" save but the autosave interval was saving my rear.  I always made it a habit to wait 10 seconds intentionally. 

With it now not working properly, its ensure a proper shutdown or bust.  

I'm usually relatively apathetic regarding the issues i submit.  I understand the scope of the project and the priorities etc.

I'd like to think this is one is higher up the ladder though.

**Comment by Ryunam** [comment]
Just tested this with the latest RA code on Windows 10, using latest snes9x. Everything seems to be working correctly here: it is saving the SRAM on disk as per the amount set in the interval (not just upon closing) and I can actually see that it's updating the savefile based on the "date modified" column on Windows.

Can you check if you experience the same issue with other cores aside from mesen-s?

**Comment by klepp0906** [comment]
yep, will go check now

**Comment by klepp0906** [comment]
and there you have it.  not happening in beetle psx.  does that mean its a mesen s issue?  Or?

**Comment by klepp0906** [comment]
SourMesen is looking into it!
