### ISSUE TITLE
[Feature Request/Discussion] Rename (or drop) the shader presets folder on fallback directories

### ISSUE THREAD

**Issue by johanbcn** [libretro/RetroArch#10641]
## Description

With the merge of #10627 @jdgleaver raised a concern about the name of the `presets` directory being too generic:

> when saving shader presets to the Menu Config or retroarch.cfg config file directories, would it be possible to name the directory shader_presets? When saving to the Video Shader directory, the meaning of presets is obvious - but a generic presets folder in the user's configuration directory is somewhat unclear (i.e. what manner of preset is this?), and could conflict with other kinds of 'preset' that might be added in the future.

While that is totally feasible, I would like to suggest an alternative: why don't we get rid of the presets directory? After all, the "preset" part is already implied on the filename extension (glsl**p**, cg**p**, slang**p**).

I propose the following:
1. Let's drop the `Video Shader` directory as an option to store user presets.
2. Let's drop the `presets` subdirectory. The root of the `Menu Config` directory would contain the global preset, the temporary retroarch preset and user presets; presets for cores, content directories and games would be stored on a subdirectory named after the core, as it's doing right now. The neat thing about this is that both presets and overrides would end up sharing the same path.
3. Let's disallow the use of "retroarch" and "global" filenames when using the "Save Shader Preset As" menu option to avoid accidental overwrites of the global and retroarch presets.

The directory structure would end up like this:
<target_directory>/retroarch.cfg (when `Menu Config` directory is undefined or not writable)
<target_directory>/<custom_user_configuration>.cfg
<target_directory>/<custom_user_preset>.{glslp,cgp,slangp}
<target_directory>/global.{glslp,cgp,slangp}
<target_directory>/retroarch.{glslp,cgp,slangp}
<target_directory>/<core_name>/<core_name>.opt
<target_directory>/<core_name>/<core_name>.cfg
<target_directory>/<core_name>/<core_name>.{glslp,cgp,slangp}
<target_directory>/<core_name>/<content_directory>.cfg
<target_directory>/<core_name>/<content_directory>.{glslp,cgp,slangp}
<target_directory>/<core_name>/<game_filename>.cfg
<target_directory>/<core_name>/<game_filename>.{glslp,cgp,slangp}

I feel this way the structure is tidier than having a separate `presets` or `shader_presets` directory.

**Comment by johanbcn** [comment]
Tagging @hizzlekizzle for comments, too.

**Comment by jdgleaver** [comment]
I agree with this completely. I've always thought it a little odd how shader presets are treated differently from config overrides and core options. Handling everything in a unified manner like this makes far more sense.

The only potential issue is backwards compatibility - when loading content, we'd still need to check `shaders/presets/` as a fallback (so as not to break users' existing setups). It's actually a bit of a pity that we merged your PR before deciding on this, since users will now have shader presets in `config/presets/` too! But for sanity's sake, we should probably ignore those moving forwards, otherwise the preset loading logic becomes a mess.

So yes - I think doing everything as you suggest is a great idea, with the one addition of checking `shaders/presets/` last when searching for existing preset files.

**Comment by hizzlekizzle** [comment]
Yeah, I like the idea of getting the user presets out of the repo-provided shaders, too.

**Comment by johanbcn** [comment]
Great, I'll get working on this ASAP then 😃.

Yes, for compatibility's sake, the shader autoload would keep looking at the `Video Shader` directory as last option.

I would not worry too much about breaking existing setups, as this is only available now on the nightly, and I'd say breaking changes are expected when using nighlies. If it gets too release though, that's another story.

Anyways, feel free to revert the merged PR if that eases your concerns; I'll just bring it back on another PR.

**Comment by johanbcn** [comment]
> If it gets to release though, that's another story.

I have just seen that version 1.8.7 got tagged yesterday. Oh well 🤷

Guess we can keep checking, and maybe even relocating automatically for a few versions until we reach 1.9...

**Comment by twinaphex** [comment]
Version 1.8.8 will be released next week.

Can you guys make the necessary changes in time for next weekend's release?

**Comment by johanbcn** [comment]
Sure, that's plenty of time.

**Comment by jdgleaver** [comment]
@johanbcn Unfortunate timing regarding the stable :)

But never mind! I think the technical debt of overcomplicated fallback logic is far worse than users having to recreate any shader presets they save over the next few days (i.e. I'd rather have some very temporary pain than slow down content loading in all cases forever). Given that we'll have a new stable next weekend I'd strongly suggest only including `Video Shader/presets` when looking for old files.

Thanks for working on this - the new behaviour will be a very great improvement!

**Comment by johanbcn** [comment]
So I got the change almost ready, but I have detected a drawback. The "Load Shader Preset" submenu is intended to list the contents of the Video Shader directory, so it either lists the shaders downloaded from the online updater, or it lists the shaders saved by the user.

Since we already have a "Save" submenu on the same list, my intention would be to turn the "Load Shader Preset" item menu into a "Load" submenu that splits into two options: "Load Shader Preset" that lists user presets, and "Load Shaders" that lists the Video Shaders directory.

I'm confident I can have it ready in a day or two tops. I'll keep you posted.

**Comment by hizzlekizzle** [comment]
How about changing the name of the 'save' submenu to "User Presets" (or "manage custom presets", etc.) and just throw the 'load user/custom [or whatever nomenclature] preset' in there? That way there's not an additional step in loading a preset each time, and there's a clear separation between the stock/official stuff and the user-created/-assigned stuff?

**Comment by johanbcn** [comment]
That could work too, but then for consistency I think we should throw in there too the "Remove" subset of options (Remove Global Preset, Remove Content Directory Preset, ...).

**Comment by hizzlekizzle** [comment]
To add to @Tatsuya79 's comment about the n/m hotkeys, I think that's actually a good reason to make the change if we also set those hotkeys to cycle through the user-created presets. It currently does nothing for most users, so that would make it actually useful.

**Comment by johanbcn** [comment]
I don't think I understand what you mean. Up until the last release, the n/m hotkeys just cycle through the user-created presets, which are the only ones available at the root of the Video Shaders directory.

Pointing it to the config directory instead will only accomplish the same objective. What I actually intend to do, is to have it search both on the root of the config directories and the shaders directory for compatibility reasons.

**Comment by Tatsuya79** [comment]
I understand why core/game/folder auto presets are best to have into the config folder; they're automated and having everything that changes the default RA behaviour located there makes sense (easier when cleaning/testing).
You don't need direct access to them, they're handled by RA itself.

Now about user made presets, those are usually meant to be kept and accessed easily.
Not having them into the shader folder is really confusing.
I really don't think their place is into a "config" folder, better create a new fallback (user) shader folder if there's a writing permission problem of some kind on some platforms.

**Comment by hizzlekizzle** [comment]
Oh, are user-created presets going to the root video_shaders dir now? I was thinking they went into video_shaders/shader_type/presets

**Comment by johanbcn** [comment]
Not now, it has always been that way (at least until version 1.8.6):
https://github.com/libretro/RetroArch/blob/d3a55ef732a6b128743a3fcc0ba03da70a6e6c44/menu/menu_shader.c#L494

That's the reason "Load Shader Preset" menu option opens up Video Shaders directory by default.

**Comment by johanbcn** [comment]
I think the best compromise we can do, at least for the moment, is to leave the user-created presets with the old behavior:

1. Try to write it into the shader presets directory
2. Failing that, try to write to the config directory
3. And failing that too, try to write to the directory where the retroarch.cfg file is found

And keep the auto-presets on the config directory as it has been modified already.

Finally, the n/m shortcut key feature should be updated accordingly. Since custom-shaders were being saved already on fallback directories, these should be scanned too.

This way, at least we fix shader management for linux distros. On android we would still have the issue of having the user-presets on an unreachable directory, but we can tackle that on another thoroughly tested PR.

**Comment by klepp0906** [comment]
just ran into this guy today noticing that they were moved.  It's not a bad change, but then it begs the question why arent the remaps moved into the core folder as well if you're shooting for any kind of cohesion as far as override storage goes.
