### ISSUE TITLE
[Feature Request] Allow reading saves & states from content dir

### ISSUE THREAD

**Issue by ds22x** [libretro/RetroArch#10659]
Currently, it's possible to write saves and states to the rom directory, but not read from it.
Allowing to read from it would help alleviate the problem where, when having all the saves and states in their respective folders would potentially allow for same name games from different systems (E.G. Aladdin for the SNES and Genesis) to overwrite each others saves and states, while also keeping the option to have different cores for the same system to read the same saves and states, which the current per core option doesn't allow for.

**Comment by bslenul** [comment]
Maybe there's another setting conflicting with this somehow? But I couldn't replicate on W10, Linux Mint and Android phone. I tried with a couple cores, save is properly written in rom folder and if I close RA and reload the game the save is loaded with no issue. No issue with state too, but only tried that on W10.

**Comment by ds22x** [comment]
I think it also still writes it to the saves and states folder when writing to content dir is enabled, meaning it will read from the default folders just fine.
It's again only an issue when you have different system games with the exact same name (like Aladdin, Hook, etc) overwriting each others saves and states

**Comment by bslenul** [comment]
It's only writing and reading the save file in the rom folder for me, no new files are being created in my regular "saves" folder. And even if I put a save in both folders, it will read the one from the rom folder.

That's why I think \*maybe\* there's another setting conflicting with this, but I don't see which one could be causing this :x

**Comment by ds22x** [comment]
Found the conflicting setting.
Having the "sort saves and states by core" options enabled makes it only write to the rom folder, but not read it when the "write to content dir" option is also enabled.

**Comment by Sanaki** [comment]
If you wouldn't mind, could you open another issue about that? That's undesirable behavior and will undoubtedly trip someone else up.
