### ISSUE TITLE
Corsiar iCUE conflicting with RA, causing frame drops and audio popping

### ISSUE THREAD

**Issue by BParks21** [libretro/RetroArch#10650]
## Description
I'm getting very shorts spurs of audio crackle and popping in cores like higan accuracy, snes9x current and mesen. I know that some cores have specific settings to reduce audio popping that occurred on original hardware but this is a different kind. It's similar to what you would hear if gamespeed just dropped slightly below target. 

### Expected behavior
Audio should sound clean and consistent free of popping 
I expect no popping, crackling, or distortion of audio if full game speed is maintained. 
### Actual behavior
Random audio popping followed by tiny dips in the framerate for no apparent reason.
I'm not sure what exaclty is causing this but this just started happening fairly recently. 
### Steps to reproduce the bug

1. Launch a game with snes9x current, like Donkey Kong Country with headphones on.
2. Play the game. 
3. Listen for very minor audio poping and crackling to occur randomly. 

### Bisect Results
I'm not sure when it started. I tried a clean install and I'm able to reproduce the same thing. 

### Version/Commit
- RetroArch: Git Version: d3a55ef732, Build Date: May 16 2020

### Environment information

- OS: Windows 10 Pro 64bit 1909, i78086K, GTX 1080Ti, 32gb DDR4
- Compiler: NA

**Comment by Ryunam** [comment]
Which audio driver are you using (under Settings -> Drivers -> Audio) and what is the amount of audio latency that you have set? Also, check whether you have a high value under Settings -> Audio -> Frame Delay.

It could also be some external application that is interfering.

**Comment by BParks21** [comment]
Xaudio, 64. I'm going crazy trying to resolve this! I've tried clean installing RA, updating my bios, chipset, audio, and nvidia driver. I can't find a solution.

**Comment by Ryunam** [comment]
Okay, can you check whether this happens with the dsound driver as well? Also, which audio device are you using? (Realtek card, a USB DAC, etc.)

I used snes9x extensively yesterday and I did not get any pop or crackle, so I believe there’s something odd happening specifically in your system.

Also, if you can upload your retroarch.cfg file I can take a look and see if there’s anything that catches the eye.

**Comment by BParks21** [comment]
Realtek, It does it on both my sound sytems. One is a bose sytem connected via usb the other is a bose surround sound connected to the optical port on the pc. Unplugging one or the other makes no difference. When i run snes9x it will just drop 1 frame to 59 randomly for no reason and the audio crackles. CPU and GPU utilization are very low. It makes no sense. 
[retroarch.zip](https://github.com/libretro/RetroArch/files/4643730/retroarch.zip)

**Comment by Ryunam** [comment]
Okay, I will take a look at the attached file by the end of the day. What you are describing might be due to the DPC latency in Windows 10 having some unexpected spikes, for reasons that are external to RA. A few more questions:

1) Did it start happening only recently? If that is the case, do you happen to have or remember a specific build of RA that did not exhibit this issue for you?

2) Do you have other applications or services in the background that are more or less intensive? A resource-heavy Antivirus for example.

3) Can you try some software like LatencyMon to see if your DPC latency is indeed spiking? If you perform this test with LatencyMon, make sure to close all software that you may have in the background in order to obtain the most accurate results.

**Comment by BParks21** [comment]
I tested all stable releases from current down to 1.7.5 i was able to reproduce it on all of them. It started recently. I don't understand whats happening? It never did this before. I tested my installation of RA on my brothers system. No audio crackle, no drop to 59 fps. Only RA is doing this for me other emulators are not.

**Comment by BParks21** [comment]
Latencymon says "your system appears to be suitable for handling rea-time audio and other tasks without dropouts."

**Comment by BParks21** [comment]
![Screenshot (121)](https://user-images.githubusercontent.com/12180630/82211840-8255a000-98df-11ea-9b11-a708af328a40.png)

**Comment by Ryunam** [comment]
Did you perhaps update your Nvidia driver recently, or at least at the same time that this popping started to appear? 

One thing you can try is use DDU (Display Driver Uninstaller) to completely remove any trace of your current Nvidia driver, so as to rule out any issue that might derive from prior installations, then re-install the driver from scratch.

**Comment by BParks21** [comment]
I've used ddu twice already. Only with the most recent Nvidia driver though. But my brother is using the same driver on his rig no problems. I guess i can revert a few back but I don't think it's the issue.

**Comment by Ryunam** [comment]
Okay, taking a look at your retroarch.cfg another idea occurred to me. 

Inside RA check the option named "Estimated Refresh Rate" under Settings -> Video -> Output. Let it run for a little bit without doing anything else, until the deviation percentage reaches a very low value (around 0.3% or something like that). Afterwards, press Confirm on that option to set your Refresh Rate in RA based on the estimation.

If this does not yield any result, try reinstalling the GPU driver with DDU and use version 441.87 this time. I know by experience that 441.87 seems to be a particularly stable version among the ones that Nvidia put out lately, so maybe we can try and see if it produces any discernible difference on your system.

**Comment by BParks21** [comment]
Funny thats literally the version i am installing at this moment haha.

**Comment by Ryunam** [comment]
Actually, if you can please try this other suggestion. I've had some issues in the past with multiple monitors, where the default (auto) value in RA would not work properly with Exclusive Fullscreen.

Go into Settings -> Video -> Output, then play with the "Monitor Index" option by changing it from 0 which is the default automatic value to 1 or 2, depending on your setup. See if you still get these crackles this way.

**Comment by BParks21** [comment]
Ok I'll try that thanks.

**Comment by BParks21** [comment]
@Ryunam  Ok this is interesting. I uninstalled the Asus Armoury Crate lighting software and the Corsair iCUE lighting software and did the monitor index switch to 1 and it is fixed. Now i just have to find out what actually fixed it. I'm going to reinstall the iCUE software first then the Armoury Crate. I'll report back.

**Comment by Ryunam** [comment]
That's great to hear! I will be looking forward to hearing more from you on this, though I suspect that the culprit was indeed the Monitor Index option.

**Comment by BParks21** [comment]
@Ryunam It is indeed iCUE. As soon as i reinstalled it and launched Donkey Kong Country in Snes9x the popping and crackle returned. I uninstalled it again and restarted the PC and the popping and crackling are gone. What could iCUE be doing that is conflicting with RA?

**Comment by Ryunam** [comment]
Hmm, that's interesting. It could be something just as simple as a CPU usage spike caused by that application, which is disrupting the very tight synchronization done within RA between audio and video.

**Comment by BParks21** [comment]
Yeah my testing is pretty consistent. iCUE installed is causing it. What can be done about this?

**Comment by twinaphex** [comment]
I don't think it's possible for us to do anything about what thirdparty software is doing to your system's runtime performance. Seems more like it's an issue on their side.

It sucks this kinda thing happens but ultimately I think there's very little we can do about it unless others have some ideas.

**Comment by Ryunam** [comment]
Not much unfortunately! I believe that, from the standpoint of RetroArch, there is nothing inherently wrong with its code with regards to this issue, so your best bet perhaps would be to disable that app from starting automatically with your system. That way you can prevent it from interfering with the synchronization in RA and, when you need it, you can run it again.

**Comment by BParks21** [comment]
Rolling back one version of iCUE improved things but sill getting occasional drops. Doing some googling it seems this could be caused by c states in the bios. I'll have to test. I'll rollback another version to see if things return to normal. If i have to I'll just revert to the Corsair Link software.

**Comment by BParks21** [comment]
This seems to be a very specific bug with my specific gpu ASUS ROG STRIX 1080ti OC Edition. The nvidia drivers and Corsair ICUE drivers. I'm closing this for now.
