### ISSUE TITLE
Retroarch Playlist unsupported filename character(s)

### ISSUE THREAD

**Issue by WindyWinston** [libretro/RetroArch#10652]
I made a playlist of Amiga WHDLoad demos. One of the filenames has an accent above the letter 'a' -

`100MostRememberedGamesOnThe64_v1.01_PerhåkanSundell&RonBirk`

When loading Retroarch and navigating to the new playlist it shows the character as 'garbage'. If you scroll to a different playlist/option then go back to this playlist all the entries are gone after and including this filename.

There are possibly more 'illegal' characters that can corrupt playlists. (This is one '`–`' (En Dash))

**Comment by WindyWinston** [comment]
Just out of interest, why does it delete all entries in the playlist from the point of the suspect character ? It wouldn't be so bad if it replaced it with a garbage character. @jdgleaver would this be your area of expertise as you recently did some playlist work. Note, this is not a new problem as I encountered this sometime last year and didn't know why it happened until now.

**Comment by jdgleaver** [comment]
I'm afraid I can't reproduce this at all (on Linux) using any menu driver and any of the freetype, stb_unicode, stb or bitmap font renderers - in all cases, the entry with special characters is displayed (with special characters replaced with `?` when using drivers that don't support them), and there is never any playlist 'truncation'.

Can you provide more info about your setup - OS, menu driver, etc.? And post your playlist file?

**Comment by WindyWinston** [comment]
I'm using Windows 10 64-bit. Retroarch - Ozone. I make all my playlists using `RetroArch.Playlist.Buddyv1.22_2019-01-09`. This creates them in the old format. Maybe it goofs when Retroarch converts it to the new format ?

**Comment by sonninnos** [comment]
Here with Windows and without playlists if the filename has `å`, `ä` or `ö`, the characters are turned into garbage in `info->path` and thus the core fails to load it.

**Comment by Jamiras** [comment]
The playlist you've attached appears to be encoded in Latin-1. 
![image](https://user-images.githubusercontent.com/32680403/82333066-77fcda00-99a3-11ea-933b-5d18002584c0.png)

When I play a game containing a non-ASCII character, the item added to `content_history.lpl` is UTF-8 encoded:
![image](https://user-images.githubusercontent.com/32680403/82333162-906cf480-99a3-11ea-8a8c-94dc55e5fa25.png)

You might just need to convert your generated file to UTF-8.

**Comment by jdgleaver** [comment]
Yes, Jamiras is absolutely correct - RetroArch can only handle UTF-8.

You could always generate your playlists using the manual content scanner - this will use the correct format.

**Comment by WindyWinston** [comment]
Is there a good playlist maker out there that will use the correct format ? I like to prepare my content before adding it to Retroarch. This way I can also just change the path and copy it over to Android.

**Comment by jdgleaver** [comment]
I don't know of any good playlist makers...

What's wrong with the manual content scanner? It took me less than 5 minutes to generate playlists for my whole collection the last time I prepared a setup from scratch :)

**Comment by WindyWinston** [comment]
OK, thanks.
