### ISSUE TITLE
crt-royale-kurozumi's geometry broken

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#10657]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When trying to apply curve to crt-royale-kurozumi the curve doesnt work at any setting 1/2/3 etc.

### Expected behavior

the geometry to adhere to the setting like the non-kurozumi variant

### Actual behavior

nothing changes

### Steps to reproduce the bug

1. load a rom and apply the kurozumi shader
2. set geometry mode to 2 for example and apply
3. return to the game and notice the screen is still square as can be

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.87 582f967fb0

### Environment information

- OS: Win10
- Compiler: [In case you are running local builds]

**Comment by bslenul** [comment]
Hm no issue here, tested with W10, gl and vulkan, latest RA commit and shaders freshly updated just in case (both glsl and slang).

0:
![Super Mario Bros  (World)-200519-125428](https://user-images.githubusercontent.com/33353403/82318931-f9b72c80-99d0-11ea-97d1-b0d90c3fa073.png)
1:
![Super Mario Bros  (World)-200519-125438](https://user-images.githubusercontent.com/33353403/82318932-fae85980-99d0-11ea-8196-c9cd14e23f2a.png)
2:
![Super Mario Bros  (World)-200519-125447](https://user-images.githubusercontent.com/33353403/82318934-fae85980-99d0-11ea-8afa-2e5f2dd482e2.png)
3:
![Super Mario Bros  (World)-200519-125501](https://user-images.githubusercontent.com/33353403/82318935-fb80f000-99d0-11ea-85f3-7e617c1152d2.png)

**Comment by klepp0906** [comment]
wow, youre totally right.

2 things at play i think. 

A) a recollection of hunterk saying a looong time ago it was broken and assumed it was still the case

B) my old ass eyes and it being incredibly subtle on a 4k screen 

C) mostly this - for some reason, when the preset was loaded the curve radius was set to 3.  when hitting spacebar to reset it, it went back to 2 which i presume is the default (thats what spacebar does right?) and this made it much more visible.

thank you for checking, i never would have looked closer.  I would have moved on to another shader for the majority of my use.
