### ISSUE TITLE
[Feature Request] Ability to hide retroarch version in xmb

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#10660]
Simple request.  As a user interface option, the ability to hide the 1.8.7 - No Core display in the bottom left of the screen.

most of the notifications that happen in the menu end up right over top of this and it looks abysmal.  I experimented with moving them to the other side of the screen, but due to the varying lengths of some of the notifications, you end up with a situation that either A) notifications are going to be cut off by the right side of your display or B) most of the notifications have to pop up somewhere in the middle to be covered from the longer ones being cut off on the right border.

solutions are of course the ability to hide this piece of information and/or the ability for notifications to grow inward if need be.

personally both would be great, more options is win.  But i know my preference would be to continue to have them tucked in the bottom left which would require the ability to hide that info which for me is redundant.   If i somehow forget my build, i can reference it in the information menu.

**Comment by sonninnos** [comment]
This has existed for ages:
![retroarch_2023_02_14_21_05_53_044](https://user-images.githubusercontent.com/45124675/218833220-596756c9-5abc-48a3-93fd-779f98f15119.png)
