### ISSUE TITLE
Auto save state not working when Cheevos Hardcore Mode enabled

### ISSUE THREAD

**Issue by andreycout** [libretro/RetroArch#10669]
- Description: Even though the behavior of RetroAchievements Hardcore Mode has changed so that you CAN Save State, only not Load State while Hardcore Mode is on (and unpaused), it currently only applies to manual Save States. The Auto Save State setting does not save a state when you exit Retroarch or close the current content if Hardcore Mode is enabled.

- Expected behavior: Considering manually using save state while Hardcore Mode is enabled is ok, I don't see why auto saving should be turned off. You might ask "why would the user want to do this if they're playing on hardcore mode". But the same question would apply to manual save states.

For my particular use case, I usually play on Hardcore Mode, but if for whatever reason I accidently close Retroarch or in the case I'm just in a hurry and forget to manually save state, and if that makes me lose significant progress, I'd like to have the option of voiding a "Hardcore" playthrough of the game by loading the auto-saved state. It's why I let auto-save state on anyway, regardless of achievements. It's just convenient and safer to have that -1 slot autosave in case you ever need it.

- What is actually happening: When you have both Auto Save State and Hardcore Mode enabled, Auto Save State does nothing, even though you can still manually Save State.

- RetroArch version: 1.8.7 stable

- OBS: As a suggestion for minor usability improvement, the most convenient way of ensuring clean Hardcore Mode restrictions in regards to Save / Load states, but still offering painless "way out" of Hardcore Mode for the user is not to completely disable Load State when HM is on, but just to notify that Loading a State will void Hardcore Mode and if the user decides to proceed loading any way, just void or "pause" Hardcore Mode from that point on only for that session (for all intents and purposes, it's the same thing as going to the achievements options, pausing hardcore mode and then loading a state, just less convoluted).

**Comment by LibretroAdmin** [comment]
@Jamiras Any thoughts on this?

**Comment by Jamiras** [comment]
> As a suggestion for minor usability improvement, the most convenient way of ensuring clean Hardcore Mode restrictions in regards to Save / Load states, but still offering painless "way out" of Hardcore Mode for the user is not to completely disable Load State when HM is on, but just to notify that Loading a State will void Hardcore Mode and if the user decides to proceed loading any way, just void or "pause" Hardcore Mode from that point on only for that session (for all intents and purposes, it's the same thing as going to the achievements options, pausing hardcore mode and then loading a state, just less convoluted).

We can't interrupt the load process to ask the user if they want to proceed, but we did put the Load State menu item back for hardcore in #13471. If the user tries to load a state in hardcore, a popup will appear telling them that they have to Pause Hardcore first.
