### ISSUE TITLE
Discord 'ask to join' broken

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#10667]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Using the discord rich presence's "ask to join" netplay function is currently broken because the new lobby doesn't report back the room ID to the hoster. It always hits the early return in the function

![image](https://user-images.githubusercontent.com/2805586/82389587-34858880-9a02-11ea-882d-2e117715a86e.png)

### Expected behavior

Users should be able to request to join netplay games via discord rich presence

### Actual behavior

It doesn't actually work

### Steps to reproduce the bug

1. Start a netplay game with discord rich presence enabled
2. try to join them from another machine

### Bisect Results

When the new lobby code was added.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.7 stable

### Environment information

- OS: linux, but applies to all discord-compatible platforms
- Compiler: all

**Comment by almetica** [comment]
Should be fixed with https://github.com/libretro/netplay-lobby-server-go/commit/6e065ab8b481df17e7518d5fe11e6455c42456ae

Please test.

**Comment by hasenbanck** [comment]
Fixed with https://github.com/libretro/netplay-lobby-server-go/commit/6e065ab8b481df17e7518d5fe11e6455c42456ae. 

Please test.
