### ISSUE TITLE
JACK driver failing on 1.8.5 - 1.8.7

### ISSUE THREAD

**Issue by jason-oliveira** [libretro/RetroArch#10675]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
JACK Driver is experiencing a regression, likely due to https://github.com/libretro/RetroArch/commit/7eb41e70571f50bd3541935037b6776335985b3f, which seems to be the last modification to the driver in some time. 

### Expected behavior
JACK driver is supposed to work.

### Actual behavior

RetroArch segfaults on start.

### Steps to reproduce the bug

1. create new ~/.config/retroarch/retroarch.cfg file
2. start retroarch, and set audio driver to jack.
3. restart retroarch, and marvel at the segfault

### Bisect Results

https://github.com/libretro/RetroArch/commit/7eb41e70571f50bd3541935037b6776335985b3f seems to be the commit that caused the regression. 1.8.4 does not experience this problem.
Confirmed both pulse and tinyalsa drivers working just fine.
Have not tested transplanting the old jack source file(s) from 1.8.4 into 1.8.7.

### Version/Commit

- RetroArch: 1.8.5, 1.8.6, and 1.8.7 release versions.

### Environment information

- OS: Gentoo Linux, kernel 5.4.24-gentoo, Libressl, glibc
- Compiler: GCC 9.2.0
[RAdump.txt](https://github.com/libretro/RetroArch/files/4660118/RAdump.txt)

**Comment by twinaphex** [comment]
See if this fixes it -

https://github.com/libretro/RetroArch/commit/4f2566ad507a0a4f72c27f67c8c3ff0080c2f0f0

**Comment by jason-oliveira** [comment]
Confirmed the commit works. Thank you for reverting.
![Catia_Output](https://user-images.githubusercontent.com/11582807/82517916-cca76e80-9ae3-11ea-9cd7-454ef73fda27.png)

**Comment by twinaphex** [comment]
Cool.
