### ISSUE TITLE
Gl drivers switch to glcore automatically even with the "Allow Cores to Switch the Video Driver" option OFF.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10677]
##  Description

Gl drivers switch to glcore automatically even with the "Allow Cores to Switch the Video Driver" option OFF. It makes it impossible to replicate some gl exclusive issues :x Not sure if it can cause issues for normal users however?

### Expected behavior

Stay to "gl".

### Actual behavior

Switch to "glcore".

### Steps to reproduce the bug

1. Set video drivers to "gl".
2. Disable "Allow Cores to Switch the Video Driver" option.
3. Start a game with Beetle PSX HW for example.
4. Check video drivers, should now be "glcore".

### Bisect Results

Started happening with this commit: 7a3ddcd77d819bb3a35ccaa3180deef982bdd5ef

### Version/Commit

- RetroArch: 1.8.7 / a8fdfd77ce

### Environment information

- OS: W10

**Comment by barbudreadmon** [comment]
I can't see this commit being responsible of this behavior since i just copied the switching code from vulkan's, most likely disabling "Allow Cores to Switch the Video Driver" never worked right in the first place ?

Could you try the same with a prior commit by setting d3d11 as default video driver ?

**Comment by bslenul** [comment]
Ok, tested with this previous commit: 63644ac76163ba7e7c4a32519c4dfbd0868f21c8

So with D3D11 and still with Beetle PSX HW:

* "Allow Cores to Switch the Video Driver" ON: I get a `Unable to find or open hardware renderer for frontend preferred hardware context. Falling back to software renderer.` message (drivers stay at "d3d11").
* "Allow Cores to Switch the Video Driver" OFF: `No hardware renderers could be opened. Falling back to software renderer.` (drivers also stay at "d3d11").

**Comment by barbudreadmon** [comment]
With this software renderer, those messages are confusing, could you try again with a core without software renderer ? Like flycast maybe ?

**Comment by bslenul** [comment]
Sure:

ON: drivers switch to Vulkan.
```
[INFO] [Environ]: GET_PREFERRED_HW_RENDER.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting Vulkan context.
[INFO] [Environ]: SET_HW_RENDER_CONTEXT_NEGOTIATION_INTERFACE.
```

OFF: "Failed to load content".
```
[INFO] [Environ]: GET_PREFERRED_HW_RENDER.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting core OpenGL context (3.0).
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting OpenGL context.
[INFO] [Environ]: SET_HW_RENDER.
[INFO] Requesting Vulkan context.
[ERROR] Failed to load content
```

**Comment by barbudreadmon** [comment]
Ok, so from i gather, the expected behavior when this option is set to off, is to fail if the video driver is not compatible with the requested context, which also explains why it's falling back to software renderer for beetle-psx.

Tbh, i don't understand the purpose of that setting, it migh as well be renamed to "break my emulator please". Anyway i'll try to see why beetle-psx is acting like this, i think it's a 2 part fix : 
- retroarch has to say "no" if the requested context is not compatible with the current video driver, so that beetle-psx fallback to software renderer instead of switching to "glcore"
- beetle-psx has to request the right context, in this case if both gl & glcore work it must use the "prefered context" callback to decide if it'll request gl or glcore, instead of blindly asking for glcore even when gl is set as video driver

**Comment by bslenul** [comment]
> Tbh, i don't understand the purpose of that setting

I'm just a regular user so I'm not sure about that either 😅 I just know that before your fix it was a common workaround for Dolphin core crashing in GL. Other than that I'm personally only using it when trying to replicate issues people are having while in a specific driver :p

**Comment by barbudreadmon** [comment]
> I just know that before your fix it was a common workaround for Dolphin core crashing in GL

I think it's currently the other way around : dolphin only works with glcore atm (same as kronos), which is why the commit you linked forces the context to glcore when it's requested (which is the case for dolphin)

**Comment by bslenul** [comment]
Works like a charm now for Beetle PSX with that commit + the one you made for the core 👍

**Comment by barbudreadmon** [comment]
Thanks for confirming, other cores might require the same patch as beetle-psx, let me know if you find one (you can open an issue there and tag me)

**Comment by bslenul** [comment]
So far so good, but Dolphin hasn't been compiled since November for Windows so it still doesn't switch from gl to glcore properly :/ Works fine on my Linux VM however.

There was a workaround for GL with Dolphin which was to turn OFF "Allow Cores to Switch the Video Driver" and turn ON "Hardware Shared Context", but that doesn't work anymore, tbh I'm not exactly sure what that 2nd option does so maybe it's intended behavior with your latest changes?

But the "not compiled since november" part is a known issue so I didn't post on Dolphin repo, but if you prefer I'll open an issue there.

**Comment by bslenul** [comment]
Aaaaaaaand, fixed with your commit for Dolphin! I was able to compile the core on Windows and now everything seems to work like it should. No matter if "gl" is selected, no matter if the "Allow Cores to Switch the Video Driver" is ON or OFF, the core just... works :D 

Thank you again! <3

**Comment by barbudreadmon** [comment]
i'm glad it worked, tbh while fixing the gl context issue on dolphin i had totally forgottten that it wasn't building on windows, thanks for reminding me :)

**Comment by i30817** [comment]
If you want a challenge, try to fix ppsspp in wayland.

**Comment by barbudreadmon** [comment]
Sorry, i won't install a specific environment to debug this. I can try backporting my context management changes from other cores though.

**Comment by i30817** [comment]
If your DE is ubuntu, it has both X11 and Wayland on the login screen, so you might not need to install.

**Comment by barbudreadmon** [comment]
> If your DE is ubuntu

It's not, i have been using gentoo for the last 20 years or so. Reproducing your issue would require too much recompiling, and at the end of the day i'm not even sure it would act the same way because of different patchsets & versions...

**Comment by ner00** [comment]
PPSSPP also does not seem to switch to glcore, which is an issue since my default video driver is gl.

**Comment by i30817** [comment]
I found a way to run ppsspp in wayland without xwayland meanwhile but it's as awkward as before: have a extra retroarch compile that only allows opengles as a graphics driver. Unlike glcore, gl and others it runs on both wayland and KMS.
