### ISSUE TITLE
RetroArch downloading suspicious non deleteable cheat file. (Megaman Battle Network 4) 

### ISSUE THREAD

**Issue by BParks21** [libretro/RetroArch#10690]
## Description
Every time i clean install RA and run the update cheats option in the online updater RA will download and extract the file "Megaman Battle Network 4." The file is at the very bottom of the root of the cheats folder. This file is 0kb and once downloaded it cannot be deleted or copied to another drive. I can reproduce this file every time I download and install RA in a different location on my c drive. I did a clean wipe of Windows 10 re downloaded RA and the file was reproduced every time. I can't delete it in command prompt or with ccleaner. The file has no extension, i can't make changes to it and it can't even be scanned. Any attempt to scan it just results in the scan being done on the previous path.
![Screenshot (12)](https://user-images.githubusercontent.com/12180630/82718326-dc53be00-9c6f-11ea-9f41-14cb0272c080.png)
![Screenshot (14)](https://user-images.githubusercontent.com/12180630/82718328-de1d8180-9c6f-11ea-88de-23e96176c050.png)

 Maybe the file is getting corrupted in the download or extraction process? 

### Expected behavior
Not downloading this file at all.

### Actual behavior
File is being downloaded and extracted and becomes impossible to delete.

### Steps to reproduce the bug
1. Download the latest version of RA and run the cheats updater and the file should be downloaded.
2. Try to delete the file
3. Thats it.

### Bisect Results
I installed RA on a spare cleanly formatted external hardrive with nothing important on it. I ran the update cheats option in the online updater and the extraction process of the cheats folder fails.

### Version/Commit
You can find this information under Information/System Information
Most recent nightly and stable.

### Environment information

- OS: Windows 10 1909]
- NA
![Screenshot (10)](https://user-images.githubusercontent.com/12180630/82717740-2d61b300-9c6c-11ea-883e-b8448c7185e1.png)

**Comment by BParks21** [comment]
On the external hardrive the .zip cheats file was downloaded but not extracted. As you can see the file in question does exist inside the compressed folder before being extracted. 
![Screenshot (11)](https://user-images.githubusercontent.com/12180630/82718139-964a2a80-9c6e-11ea-81be-629ca9323d01.png)

**Comment by BParks21** [comment]
This is what happens when i try to manually extract the individual file from the RA install .zip file on the external hardrive.
![Screenshot (15)](https://user-images.githubusercontent.com/12180630/82718905-be885800-9c73-11ea-8f43-b67a087e7aca.png)

**Comment by cmitu** [comment]
I don't think there's anything suspicious, it's just that on Windows, `:`  is a reserved and cannot be part of a filename (see https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file). Unpacking the file probably produces an invalid filename and Explorer doesn't know how to deal with it. 

The cheat files are part of https://github.com/libretro/libretro-database/. There were a few cheats added with 'incorrect' win32 filenames added recently (having `:` in their name) and most of them were renamed by @RobLoach, but it looks like this one slipped.

**Comment by BParks21** [comment]
I see can't believe i didn't realize that. So is it being corrected? Idk how to get rid of the broken file when it gets extracted.

**Comment by cmitu** [comment]
@BParks21 https://support.microsoft.com/en-us/help/320081/you-cannot-delete-a-file-or-a-folder-on-an-ntfs-file-system-volume

**Comment by RobLoach** [comment]
Thanks for the catch :+1:

**Comment by BParks21** [comment]
> Thanks for the catch 👍

NP

**Comment by Michael188977** [comment]
> @BParks21 https://support.microsoft.com/en-us/help/320081/you-cannot-delete-a-file-or-a-folder-on-an-ntfs-file-system-volume

can someone tell me how to do resolution 1?
