### ISSUE TITLE
Dreamcast cue/bin scanning not working

### ISSUE THREAD

**Issue by br4is** [libretro/RetroArch#10693]
## Description
I have a Dreamcast game collection with correct hashes from redump that is not getting scanned with the folder scan option. If I zip them, they are correctly scanned but none of them works, I think it's because they contain multiple .bin files.

If I manually scan the (Track 1).bin file of every disc/game then Retroarch recognizes them and they play perfectly (after I edit the paylist to reference the .cue instead of the track01.bin).

Here is a log of the Scan:

[INFO] Pruning file referenced by cue: Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA) (Track 1).bin
[INFO] Pruning file referenced by cue: Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA) (Track 2).bin
[INFO] Pruning file referenced by cue: Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA) (Track 3).bin
[INFO] Parsing CUE file 'Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA).cue'...
[INFO] Leyendo la primera pista de datos...
[INFO] Comparando con números mágicos conocidos...
[INFO] Parsing CUE file 'Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA).cue'...
[INFO] CUE 'Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA).cue' primary track: Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA) (Track 3).bin
 (0, 1185760800)
[INFO] Leyendo la primera pista de datos...
[INFO] CUE 'Y:\Juegos\ROMS - RETROARCH\ROMS\DREAMCAST\Crazy Taxi 2 (USA)\Crazy Taxi 2 (USA).cue' crc: 410531db

It seems it checks the CRC of the cue files and ignores the .bin files.

If I change the extension of the .cue files an rerun the folder scan, then all the games are correctly detected (again editing the Playlist to reference the .cue after restoring the extension).

In the libretro database github, in the dreamcast .dat I see the hashes for the track01.bin files.

Are the cue hashes somewhere else?

### Expected behavior

Retroarch correctly detects uncompressed dreamcast cue/bin roms with matching hashes from redump while doing a Folder Scan.

### Actual behavior

They are not detected with the Folder scan.

### Steps to reproduce the bug

Scan a folder containing a Dreamcast bin/cue with multiple .bin tracks.

### Environment information

- OS: Retroarch 1.8.7 Win 10 64 bits

**Comment by bslenul** [comment]
Log in english:
```
[INFO] Pruning file referenced by cue: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 1).bin
[INFO] Pruning file referenced by cue: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 2).bin
[INFO] Pruning file referenced by cue: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 3).bin
[INFO] Parsing CUE file 'F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA).cue'...
[INFO] Reading first data track...
[INFO] Comparing with known magic numbers...
[INFO] Parsing CUE file 'F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA).cue'...
[INFO] CUE 'F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA).cue' primary track: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 3).bin
 (0, 1185760800)
[INFO] Reading first data track...
[INFO] CUE 'F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA).cue' crc: ede401b9
```
So it looks like RetroArch is reading the .cue file then sees the track 3 as the "primary track" so it decides to scan that track instead of track 1, and of course hash doesn't match.

Until it's fixed, if you want you can get the redump .gdi files here: http://redump.org/gdi/dc/ and simply replace the .cue files with those and it'll work fine:
```
[INFO] Pruning file referenced by gdi: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 1).bin
[INFO] Pruning file referenced by gdi: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 2).bin
[INFO] Pruning file referenced by gdi: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 3).bin
[INFO] Parsing GDI file 'F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA).gdi'...
[INFO] GDI 'F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA).gdi' primary track: F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA) (Track 1).bin
[INFO] Reading first data track...
[INFO] GDI 'F:\Roms\Sega - Dreamcast\Crazy Taxi (USA)\Crazy Taxi (USA).gdi' crc: f8bb5b3c
[INFO] Written to playlist file: D:\programmes\RetroArch\playlists\Sega - Dreamcast.lpl
```

**Comment by br4is** [comment]
Thanks! I didn't know redump still had the GDIs in their Web.

**Comment by Immersion95** [comment]
Hi, regarding this issue.

It has the same problem with chd files which can't be solved by adding a gdi file :p 

It would be great to correct RA's behavior there as "Serial Scanning" will help but I'm certain that there would be edge cases where it would need to fallback to CRC check.
