### ISSUE TITLE
Shaders - Everything but "Save Game Preset" crashes RetroArch.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10698]
## Description

RetroArch crashes when trying to save a shaders preset, only "Save Game Preset" doesn't crash. No file is beeing written at all, if you have an existing preset it will load fine, only the saving part is an issue.

### Expected behavior

Not crashing? :p 

### Actual behavior

Crashes RetroArch as soon as you click "Save xxx Preset" (excepted "Save Game Preset"), here's the crash log generated with retroarch_debug.exe: [crash-200524-123823.log](https://github.com/libretro/RetroArch/files/4673331/crash-200524-123823.log)

### Steps to reproduce the bug

1. Start a game.
2. Load a shaders preset.
3. Click Save > Save Global Preset for example.

### Bisect Results

~~I could try bisecting a bit later, but it's pretty recent, and it's somewhere between 9b73f2a38cbf1051a97dcbf2a76983008b5b2a0e (bad) and 6dc758a080fdbd2499168422642b9bb8bc6de618 (good).~~

**edit:** After bisecting, this is the first bad commit: 923dc52f87ffefed410809166f1e45b53ed4c2b9

### Version/Commit

- RetroArch: 1.8.7 / cebc01cb1eca3283b9a83cd0ff7ac9f0cc9fa1a4

### Environment information

- OS: Windows 10 / **edit:** Linux too

**Comment by bslenul** [comment]
Bisecting done, seems to be the first bad commit: 923dc52f87ffefed410809166f1e45b53ed4c2b9

**Comment by Ryunam** [comment]
Can confirm this too. I am experiencing the same crash on Windows 10, by loading any content, then going into the Quick Menu and selecting Shaders -> Save -> Save Core Preset. RA will suddenly crash upon confirming that option.

**Comment by e2zippo** [comment]
Yep, same here.

**Comment by Ryunam** [comment]
Should be fixed as of 64c30610f5c6f4a0f4c61e2b34ac16e6b1395cbc - thanks @twinaphex!

**Comment by bslenul** [comment]
Awesome! 👍 I'm closing this, then.

**Comment by Quest79** [comment]
This is still happening. 1.9.0 & latest nightly as of today.
Crash log empty, it just hangs forever and needs force to quit.

**Comment by alkaris2** [comment]
Bug reintroduced once again, instead of crashing it just hangs until force quit.

OS: Manjaro Linux
RA: 1.17.0 - Core: Snes9x (1.62.3 b931ad0)
