### ISSUE TITLE
"Failed to load content" error when disabling automatic video driver switching and loading content with Mupen64Plus-Next 

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#10701]
## Description

With the latest RA code, loading playlist entries or manually starting any game manually with Mupen64Plus-Next will cause a "Failed to load content" error notification to show up with the following conditions:

- video driver is set to "glcore" (it could also happen with other video drivers though),
- Settings -> Core -> "Allow cores to switch the Video Driver" is set to OFF.

In the log window (at level 0 - Debug), the following messages appear:
```
[libretro ERROR] mupen64plus: libretro frontend doesn't have OpenGL support
[ERROR] Failed to load content
```

If Settings -> Core -> "Allow cores to switch the Video Driver" is set to ON, loading content with the Mupen64Plus-Next works fine.

### Steps to reproduce the bug

1. Set the video driver to "glcore"
2. Set "Allow cores to switch the Video Driver" to OFF
3. Load any content with the latest Mupen64Plus-Next core

### Bisect Results

I did a bisect before opening this issue and 2f57d3cbeacbee5eb492f7531b11746ac533c7ae seems to be causing this. Before this pull request, Mupen worked fine when disabling the video driver auto-switching option.

### Version/Commit

- RetroArch: 1.8.7 / 31ff7e384f6ce750fd7cccd40239129d7ac4d026

### Environment information

- OS: Windows 10 x64 1909
- Compiler: Mingw64

**Comment by barbudreadmon** [comment]
It's not a retroarch bug, see my comment at https://github.com/libretro/RetroArch/pull/10685
