### ISSUE TITLE
Why are the translations not updated?

### ISSUE THREAD

**Issue by TeknoMobil** [libretro/RetroArch#10715]
I have corrected the translations in my language for two months and completed the missing translations. But we cannot see new translations at all.

**Comment by hizzlekizzle** [comment]
Can you link that pull request? Was it merged?

**Comment by TeknoMobil** [comment]
Hi
https://crowdin.com/project/retroarch

https://crowdin.com/project/retroarch/tr#

**Comment by hizzlekizzle** [comment]
Ah, right, the crowdin translations. I'm not sure what's holding those up. I'll look into it.

**Comment by TeknoMobil** [comment]
Thank you for your attention 
Respects
