### ISSUE TITLE
Add new language to CrowdIn

### ISSUE THREAD

**Issue by duduke** [libretro/RetroArch#10721]
The new CrowdIn service is great for contributing language translations.
Can you create a new translation language for Hebrew?

Thanks.

**Comment by WeedyWeedSmoker** [comment]
@guoyunhe Could you handle this?

**Comment by guoyunhe** [comment]
The Hebrew language has been added to crowdin

**Comment by WeedyWeedSmoker** [comment]
@duduke You can now close this issue!

**Comment by duduke** [comment]
Thanks.
