### ISSUE TITLE
Korean Language Lacks Font

### ISSUE THREAD

**Issue by vus7294** [libretro/RetroArch#10722]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Set Language in Korean and Reboot Retroarch(in xmb, ozon gui)

### Expected behavior

xmb and ozon gui Support Korean so No Problem.

### Actual behavior

xmb and ozon Font Lack in Main Screen, Locks on rgui Font that Only Supports English.
But Set to English and Reboot, xmb and ozon Font Return
Same on Android Version

### Steps to reproduce the bug

1. Set Language to Korean (in xmb and ozon)
2. Reboot Retroarch
3. Font Lacks

### Bisect Results

Just Updated to 1.8.8

### Version/Commit
You can find this information under Information/System Information

- RetroArch 1.8.8
  i7 2600K
  GTX 1050 Ti
  16GB DDR3
  240GB SSD(MAIN), 2TB HDD(Games)
  Galaxy S8(Android)

### Environment information

- OS: Windows 10 Pro 20H1

**Comment by sinusinu** [comment]
Seems like all font drivers fail to load when RetroArch is started with language set to Korean. It works if RetroArch is started with English then changed to Korean.
[retroarch__2020_05_28__23_49_01(eng).log](https://github.com/libretro/RetroArch/files/4696332/retroarch__2020_05_28__23_49_01.eng.log)
[retroarch__2020_05_28__23_49_20(kor).log](https://github.com/libretro/RetroArch/files/4696333/retroarch__2020_05_28__23_49_20.kor.log)

**Comment by sinusinu** [comment]
Looks like this problem has been solved in latest nightly builds...
