### ISSUE TITLE
Fill black borders on slang

### ISSUE THREAD

**Issue by noiseshaade** [libretro/RetroArch#10738]
Its cool if u can fill black borders with noise
![35eYo](https://user-images.githubusercontent.com/61594968/83307225-3e617580-a1d2-11ea-8bad-0aadf14aa892.png)
![image](https://user-images.githubusercontent.com/61594968/83307307-6e107d80-a1d2-11ea-9448-9dbe03b7f47b.png)
They looks more natural. How apply slang shader to whole screen or its now impossible?

**Comment by hizzlekizzle** [comment]
You can do it, but you have to set RetroArch's aspect ratio setting to your display's aspect (16:9 or whatever) and then handle the image scaling in the shader. There are a number of border shaders already that you can look at to see how it's done.

**Comment by noiseshaade** [comment]
Yeh i know but im newbie in shaders, and for example in video players there is 2 shaders "before scaling" - for original image and "after scaling" for whole screen

May be developers extend something to make it possible to work with whole screen. It allows keep 'core provided' aspect ratio

**Comment by RobLoach** [comment]
https://docs.libretro.com/development/shader/shader-overview/
