### ISSUE TITLE
Are u crazy? How did u make so unusable bloatwared software? Its possible to be simple, wtf do u do?

### ISSUE THREAD

**Issue by noiseshaade** [libretro/RetroArch#10731]
Whats wrong with retroarch? Everything is wrong! Its terrible, hujnya ebanaya karoche!

btw its my pack. No all borders/icons/whatever , simple shader which improves graphic out of box
https://github.com/noiseshaade/RetroArch-vape

No stupid descriptions, interface fits in screen
![image](https://user-images.githubusercontent.com/61594968/83236221-27cf0600-a161-11ea-822d-83149d470924.png)

Out of box, retroarch is extremely complex even for advanced users. Who thought that F1 is great idea for menu? Why not escape like in usual games/emulators?

The only advantage of ra vs standalone emulators is that it support shader and TECHNICALLY it could be better, but on practice its 100mb of shader folder. Whats wrong with syncronization, why snes has sound crackling out of box? U link syncronization with monitors sync rate but it seems like it changes.  Why you cant do like previous old emulators did and somehow link emulation with stable generator? Its not very bad if u sync game with time, not display

Why sound should lag in 2020?

Why you linked sound control with DB and pression +- returns random volume?

For example, just scaled image with bilinear filter looks extremely clean like this
![image](https://user-images.githubusercontent.com/61594968/83236335-5e0c8580-a161-11ea-952e-9696308c42dc.png)

Color and feelings are not natural

Its possible to fix with some YIQ, blur, black/white point correction, noise for texturization, it gives this effect
![image](https://user-images.githubusercontent.com/61594968/83236413-7ed4db00-a161-11ea-9163-7d076ec77254.png)
Mario looks like
![image](https://user-images.githubusercontent.com/61594968/83236448-88f6d980-a161-11ea-8039-190ef1c86d9c.png)
Not like extra clear
![image](https://user-images.githubusercontent.com/61594968/83236780-13d7d400-a162-11ea-9532-d47b1e38261b.png)

Its also problem that LCD provides unnatural, too juicy color. May be this mario looks more natural, i reduced saturation

![image](https://user-images.githubusercontent.com/61594968/83236857-38cc4700-a162-11ea-9715-e1fd050c8f87.png)

U provide users extremely complex shader pack with AAAAAAA effects for tik tok

Why, if games created for playing, not playing in emulators? I promise that you software makes people VERY angry

A lot of hotkeys assigned on alphabet part of keyboard, why? Stock keyboard buttons sucks. Is it bad if u want just play from keyboard?

as for me, i use

WASD for arrows
QE - start/select
IO-/\O
KL-[]X

JU-L1L2
;P-R1R2

Why does its so necessary to load ffmeg library and crash if u remove this? It needs a lot of memory and huge size of emulator part. Are u really sure that so much users want to record the game or stream on twich?

May be there is some simple fork of retroarch for normal people? Why u cant make simple and ready for use, not so terrible?

**Comment by noiseshaade** [comment]
These CRT shaders how does they works? They are very complex but at least out of box they provide ugly dark scanlines, no noise, no blur, thats all

![image](https://user-images.githubusercontent.com/61594968/83237679-4b934b80-a163-11ea-826d-bbab8fabdbe3.png)

Look and ducktales gradients, do u really wanna say that crt method is 'narural'?

![image](https://user-images.githubusercontent.com/61594968/83237790-767d9f80-a163-11ea-96e2-07a4a0f72afe.png)

**Comment by noiseshaade** [comment]
Your project exist about 10 years and there is still not usable interface out of box, even no guide which explain how make this shit normal, explain what do u need to restore graphic etc

**Comment by noiseshaade** [comment]
U are so mad about graphic sync and ideal sync, that forgot about sound interpolation

If u link this with some stable realtime generator, it could give some frames offset like 60.4hz vs 59.8hz, but who cares on PC ~_~

As for me, i changed emulation speed on nestopia to 150% and its okay for fun. And if somebody so geeky that wants ideal sync, he can create custom resolution with 59.94hz

**Comment by berturion** [comment]
I am sure you didn't read the contributing guidelines before posting...
As for every open source and free projects, maintained by people on there spare time, you are free to contribute, or use something else.

**Comment by Tatsuya79** [comment]
![medecin-famille-masque_23-2148168455](https://user-images.githubusercontent.com/6266038/83276270-a44cfd80-a1d0-11ea-93d2-dc5004f4d889.jpg)
