### ISSUE TITLE
Retroachievements on Android doesn't like CRLF end of lines for .m3u files.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10732]
## Description

Found thanks to [this reddit thread](https://www.reddit.com/r/RetroArch/comments/gsqijk/m3u_retroachievements_problem/), when trying to load a .m3u with CRLF end of lines on Android, achievements won't work (the game itself and disc switching work perfectly fine however), example with Driver 2 on PS1 using PCSX ReARMed core:
```
[RCHEEVOS]: ext_hash 7c9557cf ('cue
')
[RCHEEVOS]: no method for file extension, trying core supported extensions: bin|cue|img|mdf|pbp|toc|cbn|m3u|chd
```
See how `('cue')` is cut with a new line?

**I'm not sure if it's an Android only issue or not** but I tested on a Linux Mint VM and no issue there, it didn't seem to care.

### Expected behavior

Read the .m3u while ignoring the end of lines format.

### Actual behavior

Retroachievements won't work if the .m3u was created on Windows.

### Steps to reproduce the bug

1. Create a .m3u file using CRLF end of lines (for a game with achievements, of course...).
2. Open RetroArch on Android and enable achievements.
3. Load the .m3u then go to `Quick Menu > Achievements` and admire the empty list!

### Bisect Results

No idea when it started, sorry :/

### Version/Commit

- RetroArch: 1.8.8 / 56619d7

### Environment information

- OS: Android

**Comment by Jamiras** [comment]
The CRLF is correctly stripped on Windows. The code looks for the first LF, then if removes the preceding CR (if present):
https://github.com/libretro/RetroArch/blob/13be887d2dc3e2c693315ed1459df7c83a334e5c/cheevos/cheevos.c#L3002-L3007

Note that line 3005 is incorrect - it should be `tmp > m3u_contents`. Would Android be arranging its stack memory differently? I'll submit a PR under that assumption.

**Comment by bslenul** [comment]
Thanks! No clue how to compile RA for Android so I'll wait for the next nightly and I could confirm if it's fixed or not!

**Comment by jdgleaver** [comment]
Oh, I already fixed this differently before noticing this issue: #10734

I think my way is more robust, since it uses a proper M3U handling library :)

**Comment by bslenul** [comment]
Hey, just to confirm it now works properly, cheevos now appear even with a CRLF .m3u :) 

Thank you to both of you! ❤️
