### ISSUE TITLE
Retroarch On Vita Wont Scan Or Play Games

### ISSUE THREAD

**Issue by DrumMaster777** [libretro/RetroArch#10742]
I have trouble with the scanning, it will scan, say 100% successful then nothing will show up. In this particular example I tried 2 TurboGrafx 16 games, this would be the 1st time adding games for this console, both successfully scanned nd retroarch didn't even make a new game list, nothing happened. I tried the new manual scan, basically create your own playlist nd it finally made a viewable list of the 2 games, neither of them load, I just get a black screen. Previous systems nd games already on a playlist are working fine. I even tried a tg16 bios file, still a black screen when loading with either core

[Description of the bug]

Wont scan nd generate any new game lists or systems like TG16. Black screen when loading games.

### Expected behavior

Scan, Display, Load, Play 

### Actual behavior

Scan "Successful", Doesn't Display Any New Game Lists, Doesn't Load New TG16 Games with or without Bios on either Core just shows Black screen

- Retroarch 1.8.8

- OS: PSVita TV Henkaku 3.6+

**Comment by StoppingBuck** [comment]
Might be this? https://www.reddit.com/r/emulation/comments/3koq8k/retroarch_doesnt_recognize_all_my_roms/cuz9kot/
