### ISSUE TITLE
[Request] Solarized Light Theme for Ozone (w/ bounty!)

### ISSUE THREAD

**Issue by anthonyajumelles** [libretro/RetroArch#10747]
https://www.bountysource.com/issues/91590110-request-solarized-light-theme-for-ozone-w-bounty

**Comment by Ryunam** [comment]
I would like to work on this, together with some other colored themes for Ozone that I had already drafted. Hopefully I find some time soon to dedicate myself to it fully.

**Comment by ofsaleem** [comment]
hello @anthonyajumelles , this PR should address this request https://github.com/libretro/RetroArch/pull/13126
