### ISSUE TITLE
[Feature Request] Add an "Include Subfolders - ON/OFF" option to the manual scanner.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10765]
Hey!

The manual scanner is an awesome feature (especially for arcade games) and I think it would be even better if an option to scan subfolders or not could be added, it would avoid getting unwanted entries in the playlist.

A quick example: my FinalBurn Neo folder has a "samples" subfolder, the samples inside have the same filenames as the roms (e.g. Donkey Kong samples are in a dkong.zip file, which is also the filename of the game), so if I scan that folder I get 2 entries for each game having samples.

Could be also useful for other systems, like if you're having a "romhacks" or a "translations" subfolder, etc.

**Comment by jdgleaver** [comment]
Sure, I'll try to find time for this next week (it's pretty quick and easy to do, but I'm all bogged down in heavy stuff at the moment - it's hard to break off and do something else mid-flow...)

**Comment by bslenul** [comment]
Haha, you again! Just take a break already! :p 

More seriously, there's absolutely no rush for this, it would be really helpful but meanwhile you can simply move folders, scan, move folders back, it's not that bad ;)

**Comment by jdgleaver** [comment]
@bslenul Here you go:  #10844  :)

**Comment by bslenul** [comment]
Oooh that's awesome, thank you so much (AGAIN :p) ❤️

**Comment by jdgleaver** [comment]
You're very welcome!

Thanks for testing :)
