### ISSUE TITLE
Discord rich presence on macOS?

### ISSUE THREAD

**Issue by devnoot** [libretro/RetroArch#10766]
This is more of a question really, but does discord rich presence work on macOS? I don't see it in the menu where it would normally be.

**Comment by hizzlekizzle** [comment]
It's probably not compiled in. I had issues getting it to compile properly with the linux snap package, so it might be a situation of it being purposely disabled, or it might just be an omission. That is, you might check the xcodeproj and see if it's being explicitly disabled or not.

**Comment by LapisLazulis** [comment]
Bumping this, still no way to activate this?

**Comment by LapisLazulis** [comment]
This just got fixed in https://github.com/libretro/RetroArch/commit/df98bca9ae5971980172076acf84fd0ed7c7c10f. Thank you for fixing it!
