### ISSUE TITLE
Atari 5200 x Retroarch x Atari800 Core

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#10784]
when i try to run an atari 5200 game this screen appears in all games (attached photo).
I already added the bios.
What am I doing wrong?

![20200603_202628](https://user-images.githubusercontent.com/16063712/83699079-82d98080-a5d9-11ea-8be4-2d57b372eef4.jpg)

**Comment by hizzlekizzle** [comment]
From what I've heard, the problem with 5200 is that the .atari800.cfg file doesn't seem to update after 1st launch, so if you start the core without 5200.rom for example the ROM_5200= line will stay empty on next launches, even if you add the bios later so usually you just want to delete .atari800.cfg so it recreates a proper one and it should be fine (and don't forget to select 5200 in core options)

**Comment by AlanRibas** [comment]
Thank you for your help.
But I followed the steps of this video here: 

https://www.youtube.com/watch?v=6yoons4SrCQ&feature=youtu.be

 adapting for use in retroarch.
after that screen appears ... press F1 ... and in the options of the emulator I choose the rom for which it has to restart (5200.rom).
all right now.
