### ISSUE TITLE
RetroArch x Obscure Video Game

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#10805]
Hi guys. I recently started configuring my retroarch. Through the website, access the information needed to get everything working. However, there are some more obscure video games that are not listed with instructions, such as:
- AMSTRAD GX-4000
- BALLY ARCADE
- CASIO PV-1000
- CASSETTE VIEW
- PHILIPS CDI
- CREATIVISION
- FM TOWNS MARTY
- SUPER ACAN

Could you add information about these systems specifically?
Because it is very complicated to find out for yourself where the error is. I don't find information on configuring these systems on the internet.

All of the systems listed above run through the MAME emulator. Unfortunately when adding a game from any of the video games shown above, retroarch does not tell us what type of bios is needed to run it. We are basically in the dark in this situation.
I tried several different cores but the result is always the same. The game does not start.

If you can add such configuration information as it exists for other systems, I would appreciate it very much.

**Comment by hizzlekizzle** [comment]
This isn't really a RetroArch issue, as such, but rather a documentation issue, so it should probably be addressed at https://github.com/libretro/docs instead.

**Comment by AlanRibas** [comment]
thank you. Register my case there.
