### ISSUE TITLE
Reliable segfault on exiting retroarch

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#10806]
### Behavior

On exit, RetroArch segfaults. Without watching logs this wouldn't be obvious. It appears to occur after the config autosaves.

### Bisect Results

c79966bd620aed2d79e430b4f14b42e50d0a4ef6 is the first bad commit
(this specific commit also segfaults on start)

### Stack Trace

```
write(2, "[INFO] Unloading core..\n", 24[INFO] Unloading core..
) = 24
write(2, "[INFO] Unloading core symbols..\n", 32[INFO] Unloading core symbols..
) = 32
munmap(0x7fec285a6000, 2569576)         = 0
munmap(0x7fec28314000, 2691456)         = 0
munmap(0x7fec280a0000, 2569576)         = 0
munmap(0x7fec08b10000, 33181696)        = 0
munmap(0x7fec08326000, 8298496)         = 0
munmap(0x7fec29c65000, 217360)          = 0
munmap(0x7fec29c2f000, 217360)          = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x28} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

### Version/Commit

- RetroArch: 1.8.8 fdf9f8259375352667dce73fdb241f8237351b4f

### Environment information

- OS: Linux Mint 19.3 x86_64, kernel 5.3.0
- Compiler: GCC 9.3.0

**Comment by bslenul** [comment]
Same thing on Windows 10 it seems (50e522c9ce): [crash-200607-155335.log](https://github.com/libretro/RetroArch/files/4742179/crash-200607-155335.log)

**Comment by twinaphex** [comment]
I think this commit should have fixed this -
https://github.com/libretro/RetroArch/commit/df8df6c18bddf4fc6ab743bc0fa21e358e6c2330

**Comment by bslenul** [comment]
Yup, seems to fix it for me on W10, I will be able to test later on my Linux VM if Sanaki or someone else haven't already confirmed it by then.

**Comment by Sanaki** [comment]
Confirmed fixed.
