### ISSUE TITLE
Touchscreen support discontinued (Wii U)

### ISSUE THREAD

**Issue by groelk** [libretro/RetroArch#10819]
Wii U touchscreen was supported until RA version 1.7.1 (included) but has been unavailable since then.

The Wii U would be an even better retrogaming device - maybe the best! - if this issue can be fixed. It would allow to play pointer/mouse based games with such cores as ScummVM, P-UAE or Dosbox.

This post echoes #10168 which has been solved thanks to @AlexKornitzer.

**Comment by groelk** [comment]
Anyone to explore this issue? This is not about implementing a new feature, but fixing one that was lost in previous updates.
Many thanks!

**Comment by hizzlekizzle** [comment]
Hmm, it doesn't look like there were very commits that touched wiiu inputs between 1.7.1 and 1.7.2, which was, thankfully, only about 2 months.

Seems like it could be related to @gblues series of HID commits that happened around here: https://github.com/libretro/RetroArch/commit/89c1ba7929c78dfbf828a2d07e6c3d2d75fdacb0

Any thoughts on this, @gblues ?

**Comment by twinaphex** [comment]
Yeah, I'd be happy to bring it back if we can. But ultimately I think we will indeed need @gblues ' help for that, since he's one of the few active WiiU coders left.

**Comment by gblues** [comment]
@groelk by any chance, are you able to load any specific ScummVM games in the latest version? Because when I try to load games, I get a neat DSI error. It may simply be an issue with the particular games I'm trying.

Once I can actually load a game, I can start digging into this.

**Comment by groelk** [comment]
Thanks for your replies!
@gblues Day of the Tentacle and Beneath a Steel Sky run fine with the latest 1.8.9 ScummVM WiiU core

**Comment by gblues** [comment]
@groelk I am not having luck getting Beneath a Steel Sky to run.

on my SD card, I have /roms/scummvm/sky which holds these files:
- sky.dsk
- sky.dnr
- sky.cpt
- SKY.CFG
- beneath.wiiu.ini

The file `beneath.wiiu.ini` takes the GOG `beneath.ini` and modifies it slightly:

```
[scummvm]
fullscreen=true
updates_check=0

[beneath]
description=Beneath a Steel Sky (v0.0372 cd)
music_driver=adlib
subtitles=true
sfx_mute=false
gameid=sky
speech_mute=false
language=en
guioptions=lang_English
path=sd:/roms/scummvm/sky
savepath=sd:/roms/scummvm/sky/saves
```
(yes, the sd:/roms/scummvm/sky/saves path exists)

After loading the scummvm core, I navigate to sd:/roms/scummvm/sky and try to open beneath.wiiu.ini, which gives me this lovely error:

![scummvm-wiiu-crash](https://user-images.githubusercontent.com/1912149/89382357-8fe51f80-d6af-11ea-871f-366908eebadd.png)

**Comment by groelk** [comment]
@gblues On the SD card I have the same game files without the .ini and the .CFG
The entry in my ScummVM playlist points to
` "path": "sd:/roms/SCUMMVM/Beneath a Steel Sky/Beneath.scummvm"`
That file contains nothing but the ScummVM ID for the game: `sky`

**Comment by gblues** [comment]
Thanks! That did the trick and I got the game to load.

Now I can actually start digging in...

**Comment by gblues** [comment]
Small update: I still haven't figured out the bug, but I've at least found the commits that broke it!

**Comment by gblues** [comment]
@twinaphex 👀  got a PR to fix this issue open.

**Comment by WeywardRoy** [comment]
Looks like this topic hasn't been touched in years, but as someone who's pretty new to the modding community, I'm having the same issue of a dsi error. I saw the response of how to fix it, but I don't quite understand what it means. Would anyone be able to guide me to fix this issue? I also want to state that I'm running Retroarch on my Wii U, so I'm not sure if the issue stems from that or not.

**Comment by hizzlekizzle** [comment]
Lots of things can cause a DSI error, unfortunately, so probably not specifically related to this.
