### ISSUE TITLE
Screenshots cause segfaults

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#10814]
## Description

Screenshots cause segfaults a few seconds after being taken.

### Bisect Results

69bdf581f48588a5270c241d35f194dfcc7f0707 is the first bad commit

### Version/Commit

- RetroArch:  v1.8.8 -- e7082d3e5b

### Environment information

- OS: Linux Mint 19.3 x86_64, kernel 5.3.0
- Compiler: GCC 9.3.0

**Comment by Ryunam** [comment]
I can confirm this is also happening on Windows 10. RetroArch with the latest code crashes right after the screenshot notification appears on screen.

Moreover, the screenshots saved as playlist entries under the Images tab are not loading anymore. When selecting Run to view those screenshot inside RA, this notification appears: "File could not be loaded from playlist".

**Comment by jdgleaver** [comment]
> Moreover, the screenshots saved as playlist entries under the Images tab are not loading anymore. When selecting Run to view those screenshot inside RA, this notification appears: "File could not be loaded from playlist".

@Ryunam Oops, my bad - I just PR'd a fix: #10815

I don't know what's happening with the screenshots - let me investigate...

**Comment by Ryunam** [comment]
Thank you as usual! :)

**Comment by jdgleaver** [comment]
Okay, crash is fixed: #10816

https://github.com/libretro/RetroArch/commit/69bdf581f48588a5270c241d35f194dfcc7f0707 was indeed the bad commit - the variable naming/usage was confusing, so I can see why that might have happened... :)
