### ISSUE TITLE
RetroAchievements Sign-In Failure

### ISSUE THREAD

**Issue by FDinolfo** [libretro/RetroArch#10813]
## Description
When setting up RetroArch with RetroAchievements account it is impossible to sign-in if the password begins with 3 period characters. Logging into the site itself with this password works fine, but RA can't seem to parse it. There is no error given when this happens, only the Achievement lists end up blank.

### Expected behavior
A successful Sign-In to RetroAchievements.org and populated Trophy lists.

### Actual behavior
RA doesn't say any error happened during Sign-In, but the Trophy Lists are all blank for games that do have them.

### Steps to reproduce the bug

1. Create retroachievements.org account with a password beginning with 3 periods.
2. Associate this account with RA under Achievements and User/Accounts.
3. Note that You don't get Trophy Lists, but there's no Sign-In error.
4. Change the account password to begin with a letter or number.
5. Re-associate that new password with RA.
6. Sign-In should work normally and trophy lists should populate.

### Version/Commit
- RetroArch: 1.8.6 x64

### Environment information
- OS: Windows 10 2004

**Comment by meleu** [comment]
I confirm this, but it's an issue on RetroAchievements.org website (already being addressed, btw).

It responds with an `403` HTTP status and nothing more.

Regarding the error message, I may be wrong, but it was probably addressed in #10774 (although, again, in this case it wouldn't help, as the server is not responding any JSON).

Finally: if you really like the RetroAchievements feature, consider updating to the latest stable (v1.8.8), as it has some new features and fixes.

**Comment by Jamiras** [comment]
>  in this case it wouldn't help, as the server is not responding any JSON

Correct. In fact, as the server is not responding with any content (just the 403), the client will retry the request thinking it's a network error. After four retries, it _should_ display a generic "error contacting server" message.

**Comment by FDinolfo** [comment]
Thanks for the responses. I'm glad to know it's not just me I spent a lot of time trying to get it to work, and I don't know what made me think to try changing my password.

I'll be updating RA today. It hadn't been that long since I'd installed this version, so I didn't think to check for a newer one. I don't like running Nightlies if I can help it.

**Comment by meleu** [comment]
@twinaphex 
as this is not a RetroArch's problem, this issue can be closed.
