### ISSUE TITLE
Android inscreen fingerprint area issue 

### ISSUE THREAD

**Issue by hohommx2015** [libretro/RetroArch#10822]
## Description
RetrArch overlay(probably touchscreen behavior) issue with my phones inscreen fingerprint touch area

### Expected behavior
When touching fingerprint area,nothing should happen

### Actual behavior
Whenever i touch fingerprint area RA would toggle layouts automaticlly and show ‘Netplay will start when content is loaded’
Heres a screen recording: https://streamable.com/cifov3

### Steps to reproduce the bug
Other users probably cant reproduce it since it's a rare situation:i have a Meizu 16T with a custom rom

Here's log screenshot:https://forums.libretro.com/uploads/default/original/2X/3/33f7c82683a52c9a99cdfb943acb6db81cc42a8e.jpeg

### Bisect Results
Since i flashed the custom rom(Mokee based on LineageOS17.1),but RetroArch is the only emulator has issue with my phones fingerprint touch area

### Version/Commit
All version,not specific version issue

### Environment information
A phone that has inscreen fingerprint sensor which is on custom rom Android 10

**Comment by hohommx2015** [comment]
I decided reopen this,i'm not only one https://forums.libretro.com/t/retroarch-keeps-starting-netplay-automatically/32249/3

**Comment by MinZe25** [comment]
I  can  confirm this with lineage os 18.1 dipper on  mi 8

**Comment by leandrodeassis** [comment]
2022 and i'm having this issue. Xiaomi Mi 9 (cepheus) with PixelExperience 12.1.

Any way to get around this problem?

**Comment by markklarsen** [comment]
Same here, Motorola x30 edge ultra, fingerprint in screen, so can't Play with overlay controller

**Comment by Spottyfriend** [comment]
Me too, also brings up stats.

**Comment by calichii** [comment]
Same bug here. Mi 10 Lite 5G with custom ROM Evolution X (Android 13)

**Comment by sonninnos** [comment]
In other words it sends "unknown" or rather null key, which means it presses all hotkeys that are bound to nothing, as in "unknown" key.. Windows driver had the same issue some time ago, and it wasn't hard to fix.

**Comment by calichii** [comment]
Same here. 
I tried to fix it assigning al the hotkeys to some key. But then fingerprint is used to fire L button.  
This bug is so annoying that I can not use RetroArch on my Android phone. 
BTW the issue is duplicated on Github (https://github.com/libretro/RetroArch/issues/10071) and also on https://forums.libretro.com/t/retroarch-keeps-starting-netplay-automatically/32249

**Comment by TwinTusks** [comment]
Is there any update with this issue?

**Comment by sonninnos** [comment]
I can't even reproduce it on my phone. Nothing happens when touching the fingerprint.

**Comment by TwinTusks** [comment]
> I can't even reproduce it on my phone. Nothing happens when touching the fingerprint.

This is really strange, I have recently updated my rom (xiaomi 9, sparkos 13.7 > 13.8) and this issue occurs, it didn't any time before. 

I have tried to set up hotkeys and it didn't solve the problem.

**Comment by vytyls** [comment]
Also experiencing this on Nokia 7.2. I can't stand it, makes app unusable. Happens with nightly build, stable, and play store versions. Please please fix.

**Comment by Domyras** [comment]
This problem is STILL not solved after years!
Stop CLOSING the issue!

This is a disgrace to github and opensource etiquette.
Either leave it open as a sign of defeat
Or close it when it's fixed.

Disgraceful.

**Comment by m4xw** [comment]
> This problem is STILL not solved after years! Stop CLOSING the issue!
> 
> This is a disgrace to github and opensource etiquette. Either leave it open as a sign of defeat Or close it when it's fixed.
> 
> Disgraceful.

Not as disgraceful as this entilted user trying to educate us on opensource etiquette.

You can fuck off with that attitude from our Issue tracker

**Comment by Domyras** [comment]
So you think it's acceptable to claim a bug is fixed when dozens still
report it? Cuz i ended up here last.
Check ddg or google.

**Comment by TacoGuyAT** [comment]
telling user to "fuck off" is definitely not acceptable too, just like calling developers disgraceful 
> You can fuck off with that attitude from our Issue tracker

i still agree that issue should not be marked as resolved if there's no fix for it, at least because users will be confused and contributors won't even find it to make a fix, however i want to note that it is resolved for me when using latest nightly build, which may also be caused by an OS update

**Comment by m4xw** [comment]
We arent gonna play code slaves for them, strong language is perfectly acceptable to deal with entitled endusers.
