### ISSUE TITLE
Xenogears crashes in open space (when battle starts), in pcsxr not

### ISSUE THREAD

**Issue by noiseshaade** [libretro/RetroArch#10828]
[Xenogears.CD1.Russian.RGR-Megera.srm.zip](https://github.com/libretro/RetroArch/files/4755354/Xenogears.CD1.Russian.RGR-Megera.srm.zip)
Save is attached, first save

**Comment by noiseshaade** [comment]
rearmed, windows

**Comment by Ryunam** [comment]
You should probably report this in the PCSX-Rearmed repo, as it's a core-related issue: https://github.com/libretro/pcsx_rearmed/issues
