### ISSUE TITLE
pcsxr from libretro team

### ISSUE THREAD

**Issue by noiseshaade** [libretro/RetroArch#10834]
why not, may be for example gamepad plugin with autodetecting of gamepads, usability improvements, some experience

u can think its something like promotion of your team

**Comment by hizzlekizzle** [comment]
Most of the plugins someone would want to use with this would be Windows-only and/or closed-source, so not really anything we can work with. IIRC, the dynarecs for it aren't PIC-compliant, either, so we can't use them, and we have lightrec now, anyway.

So, just not really a good fit, unfortunately.
