### ISSUE TITLE
Keep the Hotkey button working on a gamepad.

### ISSUE THREAD

**Issue by illando** [libretro/RetroArch#10848]
If you assign the Hotkey button in "Input > Hotkey Binds" to a gamepad button, it looses the chance to work as a normal button.
It would be great to assign the Hotkey to the "Select" button of a Joypad (for example) and have it working as Hotkey button only when it's not pressed in combination with other buttons, otherwise it should keep works as "Select".

I don't understand why this is not possible with the Mac or iOs port of RetroArch but it's perfectly working with the Libretro cores of Retropie.

Could you extend this behavior to all the RetroArch ports?

**Comment by hizzlekizzle** [comment]
This was fixed a few days ago: https://github.com/libretro/RetroArch/pull/10801

It has been patched to work this way for a couple of years in Retropie and Recalbox, but those were downstream patches until now.
