### ISSUE TITLE
Bound keyboard inputs aren't usable in menu or games after cleanups

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#10840]
## Description

Two noted issues from this. First, all keyboard bindings mapped to controller buttons now pass confirm, rather than their standard mapped functionality. This extends to both menu and game inputs. Second, connecting a bluetooth controller (on Linux, udev) now disables the repeat delay for keyboard input, making it extremely difficult to navigate precisely. This part may be related to #10408 and thus won't be discussed further in this issue.

### Expected behavior

Search functionality in particular should be available via keyboard, as well as thumbnail switch. In-game inputs should be functional via keyboard.

### Actual behavior

All keyboard bindings to game inputs pass confirm in both the menu and games. Alternate bindings to the noted menu functions don't seem to exist.

### Steps to reproduce the bug

(Fastest check)
1. Open Retroarch
2. Press S on keyboard (default binding for "search" previously)

(Game)
1. Open Retroarch
2. Load any game
3. Press any button bound to something other than confirm/A/1 on a screen where that input would be functional.

### Bisect Results

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
f12ac354381e0244e7b40c5752b71a9d03c0a343
42984968f2730f8d295052e22d2be2945c06f122
dee0c5dbca542ed53d84031849bb6fffd3da35d1
11520f9704fe5aec7d20888bf592ed81b7b9bd9a
We cannot bisect more!

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.8.8 a7ab21ac15

### Environment information

- OS: Linux Mint 19.3 x86_64, kernel 5.3.0
- Compiler: GCC 9.3.0

**Comment by jdgleaver** [comment]
@Sanaki This should fix the issue: #10845

Could you please test?

(BTW - thanks very much for keeping track of regressions like this - I find it hard to keep up with all the changes sometimes...)

**Comment by Sanaki** [comment]
Caught me while I was asleep, but that does appear to have resolved the issue fully, including the odd bit about keyboard input delay being removed with bluetooth controllers attached. Thanks!

**Comment by jdgleaver** [comment]
Great - thanks for testing!
