### ISSUE TITLE
Android - More than one achievement crashes Retroarch

### ISSUE THREAD

**Issue by Cepheidsong** [libretro/RetroArch#10856]
Description

When gaining achievements of any kind for any core, if you gain more than one achievement at the same time, Retroarch will crash and force close.  This occurs with Graphics Widgets turned on.  If you turn off Graphics Widgets, it will not crash. as a temporary solution.

### Expected behavior

Retroarch should not crash, and has not in previous versions.

### Actual behavior

Retroarch will cease to function and shut down.

### Steps to reproduce the bug

Play a game that you can gain more than one achievement at once, for example if you beat a boss, and that boss also has conditions that would gain you other achievements.
Soon as you gain them, Retroarch will freeze within 3 seconds.

### Bisect Results

Tested with different games, different cores, different systems.

### Version/Commit

Android, using stable builds.  This happened with 1.8.7, and when upgraded 1.8.8 still continues to happen.  Tested on 1.8.6 and 1.8.5 and they both crash still.  Went back to 1.8.0, problem does not occur.

**Comment by Jamiras** [comment]
1.8.5 introduced the ability to queue multiple popups when multiple achievements were unlocked at the same time (#10175). 

An easy way to trigger multiple popups is to enable the "Start Active" achievements feature and collect the hidden 1-UP in stage 1-1 of Super Mario Bros. This will trigger "Fancy Mushrooms Picker" and "1-Up". If you're quick you can then jump across the gap and collect the fire flower to also trigger "Now You're Playing with Fire!", which will be added to the queue.

I am able to reproduce on my phone. The first widget comes out about halfway onto the screen, then the process hangs. After a few seconds, it "crashes to desktop". It does not occur if I turn off "Threaded Video".

I've been trying to reproduce with threaded video on Windows, and I've had a couple issues just drawing the normal notifications that I'm going to try to fix, but no issues with the multiple achievement popups.

**Comment by Jamiras** [comment]
I managed to reproduce the same behavior I saw on my phone with threaded video on Linux.
```
#0  0x00007f41574279f3 in futex_wait_cancelable (private=<optimized out>, 
    expected=0, futex_word=0x55df88f25ebc)
    at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55df88f25e00, 
    cond=0x55df88f25e90) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55df88f25e90, mutex=0x55df88f25e00)
    at pthread_cond_wait.c:655
#3  0x000055df86fbd87c in video_thread_send_and_wait_user_to_thread ()
#4  0x000055df86fc1625 in video_thread_texture_load ()
#5  0x000055df86fdd79a in gl2_load_texture ()
#6  0x000055df86d478d9 in video_driver_texture_load ()
#7  0x000055df86d92a1e in gfx_display_reset_textures_list ()
#8  0x000055df873194dc in cheevos_get_badge_texture ()
#9  0x000055df86fad0f2 in gfx_widgets_push_achievement ()
#10 0x000055df873180b2 in rcheevos_award.isra ()
#11 0x000055df8731840c in rcheevos_test_cheevo_set ()
#12 0x000055df87319083 in rcheevos_test ()
#13 0x000055df86d659ad in runloop_iterate ()
#14 0x000055df86d6670d in rarch_main ()
```
deadlock with 
```
#0  __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f4157424023 in __GI___pthread_mutex_lock (mutex=0x55df890da2d0)
    at ../nptl/pthread_mutex_lock.c:78
#2  0x000055df86faa466 in gfx_widgets_frame ()
#3  0x000055df86fd9838 in gl2_frame ()
#4  0x000055df86fbf8ee in video_thread_loop ()
```
The video thread is trying to draw the widget while the main thread is trying to queue another one. For reasons that are unclear to me, while queueing the second achievement, the video thread must be locked to load the badge texture. I'm going to move the badge texture loading outside of the achievement queue lock.

Unfortunately, I could not reliably reproduce on Linux. It happened twice in about 30 attempts before I made the changes, and no times in about 20 attempts after.
