### ISSUE TITLE
Android- Achievement says 'Locked' when 'Unlocked'

### ISSUE THREAD

**Issue by Cepheidsong** [libretro/RetroArch#10857]
## Description

When you earn an achievement in Hardcore, the achievement list will say 'Hardcore'.  When you earn one in softcore/normal mode, it should say 'Unlocked'.  The achievement does indeed unlock, but the text on the list still says 'Locked'.  This did not occur in earlier versions.  

### Expected behavior

When you earn achievement in softcore/normal mode, the list should say 'Unlocked'

### Actual behavior

The achievement is unlocked and earned, but it remains saying 'Locked'

### Steps to reproduce the bug

Earn achievement with softcore on (where you can use save states).  Will still say Locked.

### Bisect Results

Happens with any game and any core.

### Version/Commit

Happens on version 1.8.5, 1.8.6, 1.8.7, and 1.8.8.  Perhaps other versions.  Problem does not occur on 1.8.0

### Environment information

Stable version builds for Android.

**Comment by Jamiras** [comment]
> When you earn one in softcore/normal mode, it should say 'Unlocked'. The achievement does indeed unlock, but the text on the list still says 'Locked'. This did not occur in earlier versions.

I see this behavior when hardcore mode is paused, but not when I disable hardcore mode. Please confirm that you are using the Pause Hardcore feature.

**Comment by Cepheidsong** [comment]
> > When you earn one in softcore/normal mode, it should say 'Unlocked'. The achievement does indeed unlock, but the text on the list still says 'Locked'. This did not occur in earlier versions.
> 
> I see this behavior when hardcore mode is paused, but not when I disable hardcore mode. Please confirm that you are using the Pause Hardcore feature.

Sorry to be late back to you, it's showing Unlocked when in softcore yes, but when you have Hardcore turned on, it will usually say 'Hardcore' for Hardcore unlocked, and 'Unlocked' if unlocked in softcore- but it still has the behavior of showing Locked for unlocked achievement when Hardcore is on.  (It didn't use to be like this in earlier versions).  Just tested on 1.8.8 and 1.8.9, it still says Locked for Unlocked (but Hardcore for Hardcore unlocked is working proper) when Hardcore is turned on.

**Comment by Jamiras** [comment]
This changed in 1.8.5 when the string was updated to show percentages for achievements that track progress. For an achievement that tracks progress and has been unlocked in softcore, but not hardcore, should it show "Unlocked - 50%"?

I'll look into restoring the behavior at least for achievements where progress is not tracked.

**Comment by Cepheidsong** [comment]
> This changed in 1.8.5 when the string was updated to show percentages for achievements that track progress. For an achievement that tracks progress and has been unlocked in softcore, but not hardcore, should it show "Unlocked - 50%" when working towards unlocking it in hardcore?
> 
> I'll look into restoring the behavior at least for achievements where progress is not tracked.

That makes sense for that behavior, ok!  Thank you for the reply.
