### ISSUE TITLE
request : Search

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/RetroArch#10860]
Could we see a search bar in RetroArch? It would be easier to find the game i'm looking for.

**Comment by bslenul** [comment]
You can use the top face button on your controller (X on Nintendo controller, Y on Xbox controller or Triangle on PS controller), or `/` key on your keyboard (I believe? I'm on AZERTY so it's `!` for me :p ).

It should bring a virtual keyboard that you can use to search. What would be really useful is a "find next" button however :D

**Comment by i30817** [comment]
Devil's advocate says a search bar would be useful for when retroarch gets more complex metadata to search, which is probably never to be fair (except what was inherited from the other parent db like the studio).

**Comment by Cibomatto2002** [comment]
Thanks alot.
