### ISSUE TITLE
Random freeze main menu on android oreo 32bit arm7

### ISSUE THREAD

**Issue by 3XistencE** [libretro/RetroArch#10872]
Good day,
I experience some random freeze on the main menu after updating retroarch to 1.8.8
Controls become unresponsive, it start with some delay in the input and interface until it freeze totally.

Also there is some kind of problem related to the menu music audio mixer. 
Leaving it on seems lead to RA crash when loading some games.
Practical Example: menu mixer music on, loading flycast rom mbaa.zip = crash, It runs without problems only if the menu mixer audio is off.

Cores with problems on Android Oreo 32bit on arm7:
Openlara (after the last core update I have a sprite sheet in front of the rendering graphic and the rendered graphic is just black with some white polygons. It worked fine before)
GME: recognize the vgz songs informations but doesn't reproduce any sound, it stops the playback at 6 seconds
Hatari: rumors says the core is not updated and doesn't compile the last update on Android arm7. Recognize the tos image but crash ra. Never able to run anything with it.

**Comment by twinaphex** [comment]
Outdated version, we don't support anything except for the latest version and nightlies. Please try this again with version 1.8.9 and later instead.

**Comment by 3XistencE** [comment]
I just noticed yesterday the update. I will check and confirm if the problem persist, thank you @twinaphex
