### ISSUE TITLE
Can't use keyboard keys for analog inputs anymore.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10884]
## Description

Binding left or right analog in Settings > Input to keyboard keys doesn't work anymore. You can bind them but they don't respond ingame.

### Expected behavior

Keys working as left/right analog inputs if bound as such.

### Actual behavior

Doesn't do anything ingame.

### Steps to reproduce the bug

1. Go to Settings > Input > Port 1 Binds.
2. Bind some numpad keys for example for left analog inputs.
3. Start Super Mario 64 and try to move with the numpad keys.

### Bisect Results

Started with this commit: c7cd327b5bb5da6295fa7c93e478b3f3a1dfc8b2

### Version/Commit

- RetroArch: 1.8.9 / 857b0da555

### Environment information

- OS: Windows 10

**Comment by bslenul** [comment]
Ah, seems to only happen when a controller is plugged, with no controller the keys respond properly.

**Comment by twinaphex** [comment]
Try to see if this solves the issue -

https://github.com/libretro/RetroArch/commit/35c55c4b50105a6107f4754585a2c68995d9174d

**Comment by bslenul** [comment]
Yup, tested with both my DS4 (with and without DS4Windows) and my 8bitdo, no issue anymore, thanks for the fix!
