### ISSUE TITLE
Its most awful software

### ISSUE THREAD

**Issue by noiseshaade** [libretro/RetroArch#10898]
I met some 12yo guy and he played in Megaman, it was very hard for him. Not only megaman, even Duck Tales
And... Out of box your software is totally unusable, especially for kids

These AI, wtf is this? Why even cheap old chinese consoles with shitty hardware can just launch games and play without fucking with settings, but your software can not?

You have tons of shaders, but no shader preview. With paint.net u can preview changes, in your AAA software u cant. Very slow navigation, it does not remember position
Extremely huge interface
My config is this
![image](https://user-images.githubusercontent.com/61594968/85333850-4e563780-b4a8-11ea-97f7-b730b2c5f262.png)
Your is this
![image](https://user-images.githubusercontent.com/61594968/85333927-70e85080-b4a8-11ea-86c7-f9e45bac2f7f.png)
Why you describe wtf does 'audio' means? Can u make it fit in screen

Ozone has no scrollbar, no mouse support, if u try to scroll, actually its equal to up/down button

People dont wait that software does not work with mouse

U cant explain even default configuration, what button u need to press for some effect
![image](https://user-images.githubusercontent.com/61594968/85334229-e0f6d680-b4a8-11ea-8ee7-44cdc1c33a8b.png)
U can draw something like normal games if gamepad is not connected like 'L - ok', 'O - cancel'
How to reset settings with start button u dont descibe too

Why do u draw licence? It takes much space
![image](https://user-images.githubusercontent.com/61594968/85334410-3501bb00-b4a9-11ea-962d-8b9ed949ca50.png)
Why not organize cores like

NES\
Snes\

U just give people huge list of all cores. What difference between then - there is no description. But u can see that lisense is GPL v3, very important information haha

Your software with 'release' has >13000 of files, size is bigger than 600mb and out of box it even does not have any core

Alphabet keys are assigned on emulator functions. If u wanna make keyboard gamepad like
wasd iokl it will conflikt, and no highlight. WTF, why F1 calls menu? Do u know that many people use laptop, they can assign something on F keys by default

And they have to press Fn+F1 to call menu, who wait that?

Your bloatwared AAAAAA software is extremely glitchy, unusable for NORMAL people

Even your buttons numeration
![image](https://user-images.githubusercontent.com/61594968/85335010-48615600-b4aa-11ea-83fc-caddb6418469.png)
Like BY...some keys...AX is wtf

On 1st place u put very strange settings like bind timeout, duty cycle

![image](https://user-images.githubusercontent.com/61594968/85335123-747cd700-b4aa-11ea-8d85-c3affaf220d2.png)

If user wanna change settings, on 1st place u need to have Port1, just tune control

I dont know how after 10 years of development u still have so glitchy and unusable software

**Comment by noiseshaade** [comment]
And ra eats cpu even if emulation is on pause. nestopia or epsxe do not do this, it continues to render and heat laptop even if it in fullscreen and u switch from ra to windows

**Comment by noiseshaade** [comment]
For normal people on windows u can make small version without these bloatwared things, simple structure of folders, no tons of files in root, some cores are included out of box

**Comment by noiseshaade** [comment]
As for me, to make interface usable, i just reduce scale to 0.6x and disable sublabels
If I need some description, i can press select button, btw font size in this is very small
![image](https://user-images.githubusercontent.com/61594968/85336082-105b1280-b4ac-11ea-9a05-117d092eacb4.png)

**Comment by noiseshaade** [comment]
For normal view as for me i need some calibration, its possible to make it very simple

From this
![image](https://user-images.githubusercontent.com/61594968/85336237-49938280-b4ac-11ea-9db4-30048a378ff7.png)
To this
![image](https://user-images.githubusercontent.com/61594968/85336254-53b58100-b4ac-11ea-8f56-0c2f357b90fb.png)
YIQ boost, levels correction, some blur (coz CRT TV does not provide clean lines), some noise for texturization

Its not correct to just draw black lines or crt subpixels, coz when u played from tv, it was no huge subpixels from typical distance

These crt shaders have too strong settings and its a parody

**Comment by hizzlekizzle** [comment]
I appreciate you taking the time to assemble these suggestions and pics. I deleted the pic of your friend, as we don't want any pictures of people (esp anyone 12 or under) for various international liabilities.

While I/we don't agree with all of your suggestions (or with how you've expressed them lol), some of them are valid and helpful, so thanks for that. As long as you want to keep your suggestions in this thread, I won't close/lock it.

**Comment by noiseshaade** [comment]
vashe pofig

**Comment by noiseshaade** [comment]
But u should know that for normal people, not crazy linuxoids, especially for kids, your software is nightmare in everything what u did. Any normal guy i thing can tune classic emulator, but retroarch looks like u hate people and kidding them

**Comment by negativeExponent** [comment]
your ranting is misplaced. You should know this is not the place of such.

**Comment by askotx** [comment]
Chill out men!! kids under 10 can use retroarch confirmed, aside from that, your attitude it's so bad, you could read retroarch docs to how to make a plesant UI, also you could use kiosk mode to hide advanced settings, you can customize retroarch to your own flavor, but have respect to the devs, also you could make a PR to contribute, instead of just spittings scorpions from your keyboard, this is an open source project, help them, not sink them.

**Comment by noiseshaade** [comment]
Oh okay where is place :)?
Its just my thoughts

People says that u need to be correct, but actually retroarch is not correct of anything. It has some logic, ok, but this logic works only for developers and geeks

Who wait from gaming software that F1 calls menu? Or there is mouse, but actually mouse does not work like normal mouse. Does making scrollbars or mouse support is more difficult that AI discord twitch?

Why am I see that video button changes 'video output settings'
Does user so stupid that he does not know what video means? But this stupid user must know that F1 calls menu

Base mission of emulators is providing people play in games. Just install and play, whats wrong with this logic? May be it needs some delays, but retroarch as i know is crazy about strange ultra super zero latency. Sound could lag on not super PC, but its okay, coz there is super zero latency is activated

For most cases laptop is enough. ps1 emulators worked on pentium 3
psp with 333mhz cpu and 32mb ram has emulators of snes gba, whatever, fullspeed no lags even with some delays buffer size whatever

But retroarch...

**Comment by Zephyr-Battiassi** [comment]
As non-native english speaker, I recognice that I have taken a lot of time to be able to express myself in a proper, polite way, I think that @noiseshaade is a non-english native, so I recognize his writing as my own of the first years, and I feel it not like a rant, but as an struggle to express his point of view. I found that @hizzlekizzle was very cool and polite to accept it. 

Retroarch is an incredible piece of software, powerful but complex to master. To be constructive, 
I would suggest that maybe all @noiseshaade frustration, and probably many others could be solved with an option to launch a "first time launch wizard" that allows less savvy users to get retroarch up and running with a few clicks here and there: Just basically downloading a few cores depending on the system you want to emulate, setting up the gamepad, enable kiosk mode, and you are good to go. With that you cover the bare basics to have it up and running and you can later prettify or tweak the output to your liking. 

I also found nice the shader preview suggestion (and also a notification of "resource intensive shader" would be good). I had some struggles finding out , by example, which was the highest level of XBRz shader my HTPC could handle without getting sluggish. Sometimes it got so slow that I had to kill retroarch because it was faster to relaunch it than waiting to reach the shader menu again.
  
Not everyone will agree with me, that's just my two cents.

**Comment by noiseshaade** [comment]
Its poweful... But powerful for who?
What 'zero latency' means?
For example, u can reduce audio buffer size from 64ms to 1ms. Latency is 64x time less, but actually normally u will not see any difference. And it needs as i know extremely powerful hardware

On normal hardware it will be extremely laggy as i know

Its possible to make these 'ultra small latencies' so small that comfortable SNES emulation needs intel i9 10900k 6GHz DDR6 128Gb ram quantum pc neural AAA networks whatever, but its not fun

**Comment by noiseshaade** [comment]
For example, people can buy low-end laptops if they just need some internet
Modern games are AAA shit, overloaded with special effects, its not magic, its not fun, they just eat resources. People or kids do no wanna play in 'modern' games

its nothing wrong if by default retroarch does not eat many resources, if somebody needs these zero latency or what these guys use, he can activate it

retroarch focused on mobile phones, but actually playing in old games from touchscreen is awful

there is some cool things for phones which turn them to psp like console
https://www.youtube.com/watch?v=b3-Ua8ZQc84

but retroarch 'shop' sells t-shirts, iphone cases... https://teespring.com/stores/retroarch ... very very strange

**Comment by hizzlekizzle** [comment]
@Zephyr-Battiassi Yes, I agree that an optional first-run wizard would be nice. Unfortunately, it's one of many things that very difficult for us to do within our UI vs with a single-platform native GUI toolkit.

@noiseshaade we don't have anything invested in the teespring merchandise. It's just a free service that sells stuff with your logo/designs for a cut of the proceeds. In contrast, it's very expensive and labor-intensive to produce, market and sell your own electronics hardware. It's something we've wanted to do for a very long time, but it has very high up-front costs (upwards of $20k for the controllers we were looking at a few years ago) and we would have to store the stock, mail out orders (internationally), deal with refunds, etc.

**Comment by keithbowes** [comment]
> Extremely huge interface

`./configure --disable-menu`

Problem solved!

**Comment by noiseshaade** [comment]
oh for me 0.6x scale and disable sublabels solve interface problems, even no real scrolling is no critical
Instead of this
![image](https://user-images.githubusercontent.com/61594968/85346749-6cca2c00-b4c4-11ea-9c37-5b78b2e7f189.png)

 when gamepad is not connected, it could be something like this
![image](https://user-images.githubusercontent.com/61594968/85346774-7d7aa200-b4c4-11ea-8341-6820bf9917b8.png)

If u just launch emulator, u dont know what this means
![image](https://user-images.githubusercontent.com/61594968/85346827-a8fd8c80-b4c4-11ea-9266-1762bb8ed733.png)

**Comment by noiseshaade** [comment]
I dont know how retroarch is popular on mobile phones or consoles, may be a lot of people use it, but actually they do not have much choice

If there is regular windows user

For example u wanna just play one old game like megaman

Download nestopia, ntsc filter and set up controller fastly

With retroarch

Download 200mb installer with thousands of files, unpack them. download core, forget about previous user experience, even calling menu

And after it... Same thing, but after tons of manipulations and time 

Even somebody wanna try discord/twich/ai achivements whatever, they have to spend A LOT of time and energy. And mental health

**Comment by noiseshaade** [comment]
> Chill out men!! kids under 10 can use retroarch confirmed, aside from that, your attitude it's so bad, you could read retroarch docs to how to make a plesant UI, also you could use kiosk mode to hide advanced settings, you can customize retroarch to your own flavor, but have respect to the devs, also you could make a PR to contribute, instead of just spittings scorpions from your keyboard, this is an open source project, help them, not sink them.

Hmm. I do not need 'pleasant ui'
Project exist 10 years. Classic emulator like nestopia snes9x was created with very small team, or with only one person
Or, for example, there is zsnes it has its own 'driver' like retroarch does, but its intuitive
![image](https://user-images.githubusercontent.com/61594968/85352867-eff37e00-b4d4-11ea-8f27-e45e43a1a67b.png)
only one 1 file, size is 580kb

It just works. Its not 'ideal', but its very easy to understand.

Ntsc 'shader' exists too
![image](https://user-images.githubusercontent.com/61594968/85353582-95f3b800-b4d6-11ea-854a-7c129d5f45e1.png)

Simple sliders
![image](https://user-images.githubusercontent.com/61594968/85353636-ba4f9480-b4d6-11ea-9f52-2611cbb05f7c.png)
Retroarch has **54** crt shader presets. No preview. No remember position. How does they work... Usually they are very strong or complex, some of them can lag nes on intel hd4000. No sliders or any visualisation
![image](https://user-images.githubusercontent.com/61594968/85353837-30ec9200-b4d7-11ea-914f-5bfb68c2a67c.png)
After 10 years of development with huge team...


For me as 'normal' user retroarch has only 1 advantage, i can calibrate image

I dont know all these ntsc crt things, just some colors changing, noise, blur...

**Comment by devinprater** [comment]
I mean, Retroarch is more complex than single emulators. Retroarch is a flexible front-end to these emulators, not a 1:1 representation of them. It's a bit like that multi-emulator from Byuu.

**Comment by noiseshaade** [comment]
Man

There is a lot of chinese multi emulator handheld consoles google it on youtube
https://www.youtube.com/watch?v=9mSvczcgS9c
https://www.youtube.com/watch?v=TX7igfC8wgs

They emulates ps1

U can put them in pocket

Just launch game and play it.

Whats wrong with retroarch on PC?

**Comment by noiseshaade** [comment]
Rk2020 3.5 ips screeen 
It emulates psp well

https://www.youtube.com/watch?v=CsxWApj5xmw

RockChip RK3326 (4cores ARM Cortex-A35 1.3 GHz)

In **2020** year i still have troubles on 2.6Ghz intel i5 to emulate ps1, oh no. its after 10 years of retroarch development...

**Comment by askotx** [comment]
Do it by yourself and stop complaing, pay to new developers to make it like you want, all of your issues have of somekind of hate, stop being pasive-aggresive with your comments, and mainly agressive.

**Comment by noiseshaade** [comment]
I mean... I think its huge team. Huge team which do nothing. They just promise that they fix something... But they cant do this. If they make ready out of box software, there is no growth... No growth means degeneration, people say. They should growth. Bigger size. More icon pack. More borders. More shaders. More system requments. More cores. They can write 100 of cores for every platform. Its 'job'

For example, Microsoft has >151000 of people, Apple >137000

What does these people do actually? Win 10 vs Win 7 has no much difference

In modern world its normal situation that billions of people do nothing. And retroarch team...

**Comment by negativeExponent** [comment]
do nothing geez. can we see what you've done aside from rambling? did you pay anything? were you forced to pay if so? stop rambling and get a life.

**Comment by noiseshaade** [comment]
U should know that now we live in the 'end of time'. All these events 😼. There is no school, no job or predictions anymore :)

**Comment by noiseshaade** [comment]
8)
![image](https://user-images.githubusercontent.com/61594968/85360995-b3ca1880-b4e8-11ea-9511-189c695159c8.png)
![image](https://user-images.githubusercontent.com/61594968/85361005-b7f63600-b4e8-11ea-95d7-1ded806d5615.png)

**Comment by hizzlekizzle** [comment]
>There is a lot of chinese multi emulator handheld consoles google it on youtube

Yes and some of them use RetroArch lol

> huge team

There are quite a few people who contribute to libretro as a whole (cores, cheats, etc.), but for RetroArch itself, there's usually only a handful. I think the most active contributors at one time was like 6 and it's currently ... 2.

**Comment by andiandi13** [comment]
I agree with you on at least one thing : Ozone should have a proper touch interface, for :

- Scrolling
- Going backward without having to touch the tiny "Back" button on the bottom righ hand corner (e.g. using the back button of the phone, make sense.)

**Comment by noiseshaade** [comment]
Oh some guys make core. There is a lot of cores for snes for example
In old days people who made core - they make interface too. Its art work too, by the way. Snes9x has its own interface, zsnes, nestopia

Its nothing wrong if people who make cores make usable interface. Or they can share retroarch build with included core

People actually have their own taste. If somebody likes classic emulators, he never make build with such huge scale for pc and dont assign function on alphabet keys. Or something like F1 calls menu

Its possible to make build for yourself or your friend

**Comment by negativeExponent** [comment]
its time for you to stop rambling and use something else. no one is forcing you to keep using the most awful software ever.

**Comment by noiseshaade** [comment]
Yeh, but in my opinion retroarch destroys whole emulation party :). For example, u wanna play in game and enjoy it, but u cant enjoy it, coz of
I spent about 4 month to tune retroarch

For my side it looks like

Play in usual emulator
When boring, launch retroarch
Catch another AAHAH WTF IS THIS
Return to normal emulator

I just know that i can calibrate picture using shaders, for me advantages of ra vs epsxe-like emulators is only framerate counter - it means i can generate dynamic noise. And there is gaussian blur preset, im not shader coder

Then it can be used on nes or any console

I had some practice with shader on videoplayers like potplayer and in retroarch its very glitchy

![image](https://user-images.githubusercontent.com/61594968/85433773-ed376e00-b552-11ea-9371-98a9fd97b136.png)

For players its like 'before scaling' and 'after scaling', it possible to use fullscreen as surface. It allows u hide (apply levels correction) black borders and apply noise for them too

Ra has strange behaviour. For example if u wanna work with screen as surface, u have to use bilinear filter. Imho if u use just blur instead of bilinear filter, it gives better results

For example i wanted to try

Its original
![image](https://user-images.githubusercontent.com/61594968/85434412-07258080-b554-11ea-8dd7-286e23c670b2.png)
Its bilinear
![image](https://user-images.githubusercontent.com/61594968/85434616-523f9380-b554-11ea-838e-5d9ceeb74aa2.png)
Its nearest algo + gaussian blur
![image](https://user-images.githubusercontent.com/61594968/85434653-5e2b5580-b554-11ea-9ad9-6d40daaf10a8.png)

But u cant get 'clean' pixels for nearest algo, it should works like integer upscale roundup(displayres/consoleres), then bilinear or whatever downscale to fit in windows

But its not possible, u have to apply blur after bilinear filter... Okay, it works, but less accurate

**Comment by noiseshaade** [comment]
Shaders is like 'killer feature' of ra, but actually...
No preview, no remember position, tons of strange effects, no visualization (sliders) like reshade

There is a tons of ra features but they do not work well. They spend a lot of time for documentation, porting, web site, youtube preview, whatever. No usability

**Comment by noiseshaade** [comment]
Maybe its user feedback. Or 'its open source, anybody can fix it'
But retroarch has reputation of ugly unusable bloatwared software

They share people 200mb installer for windows with thouthands of files

Usual people do not approve it, if they have fun with classic emulators
For third part developers its no much reason to help retroarch, they continue share this 200mb installer with 190mb debug exe, tons of files

Its 'universal' politics of universal gui with same scale on phones, PC, whatever, universal borders and pngs

Normal people who stay on PC i think know about retroarch, but users and coders who can fix something should hate retroarch

**Comment by hizzlekizzle** [comment]
Alright, you've moved from constructive feedback to pointless complaining, so I think we're done here.
