### ISSUE TITLE
[Windows/Bug]Guide/Home button on Xinput controller bug with explorer.exe terminated

### ISSUE THREAD

**Issue by Immersion95** [libretro/RetroArch#10890]
Hi,

I have this exact same issue which is bothering me : https://www.reddit.com/r/RetroArch/comments/ensw3o/i_think_i_discovered_a_bug_with_retroarch_anyone/

Pressing the Guide button when explorer.exe is off make Retroarch start a server, it then becomes extremely slow and I have to restart it

**Comment by bslenul** [comment]
Just tried out of curiosity and can confirm this oO 

> [ERROR] [dispserv]: HrInit of ITaskbarList3 failed.
...
[INFO] [netplay] Waiting for client ...
[INFO] [CONTENT LOAD]: CRC32: 0x3337ec46 .
[INFO] [netplay] You have joined as player 1
[INFO] [netplay] Port Mapping Successful: xx.xx.xx.xx:55435
[INFO] [DISCORD]: Netplay room details: ID=78806, Nick=bslenul IP=xx.xx.xx.xx Port=55435
[INFO] [DISCORD]: Join secret: 78806|xxxxxxxxxx
[INFO] [DISCORD]: Party ID: 78806

Not sure what the "Join secret" is, so I preferred to hide the 2nd part of that line.

If no content is loaded you get that notification: `Netplay will start when content is loaded`. Steam completely closed, I even closed DS4Windows just in case... It's like it's pressing the "Netplay Hosting" hotkey, except it's not bound to anything for me 😅

**Comment by corgana** [comment]
I have had this issue for a long time. A developer on Reddit once told me it was Steam, not Retroarch causing the problem (however I didn't have Steam at the time). I actually just tried the new Retroarch for Steam beta assuming it would be fixed (because Steam uses the guide button to access it's menu) and it STILL brings up the netplay stuff and slows down the game.

**Comment by hizzlekizzle** [comment]
This is a related issue: https://github.com/libretro/RetroArch/issues/10855

**Comment by bslenul** [comment]
Any news on this? Looks like it happened to other users with different setups:

* This user had the issue but with a normal button, he apparently had to unbind volume hotkeys (I guess? He never replied): https://www.reddit.com/r/RetroArch/comments/ho10t8/when_i_press_this_specific_button_on_my_arcade/
* This user has the issue when pressing L2+R1: https://www.reddit.com/r/RetroArch/comments/k0jbl2/l2r1_hotkey_exit/
* This one with a P2 button: https://www.reddit.com/r/RetroArch/comments/m1nuo9/weird_behavior_with_p2_arcade_side/
* Someone on Discord had the same issue but WITH explorer.exe running few months ago:

![image](https://user-images.githubusercontent.com/33353403/110619539-3c343a80-8198-11eb-9066-bd1c93114c9d.png)

**Comment by Immersion95** [comment]
Any news on that ? This still happens on latest Win 11 x64.
