### ISSUE TITLE
is 32 bit version better than 64 for pcsx core?

### ISSUE THREAD

**Issue by noiseshaade** [libretro/RetroArch#10899]
I cant test it, coz 32 bit crashes on my laptop, but 64 not
But people say that at least on android 32bit rearmed works better

pcsx/epsxe is 32bit too... or i dont know, i have sound lags on laptop (intel i5-3317u 2.6ghz turbo), is it possible to fix that, may be increase some latency, which latency ¯\_(ツ)_/¯

**Comment by noiseshaade** [comment]
Why re**ARM**ed core for x86-x64 exists, but just pcsx core does not..

**Comment by hizzlekizzle** [comment]
ReARMed is just a name. It's ultimately PCSX, it's just a fork of a fork.

As far as this core is concerned, 32- or 64-bit doesn't matter on x86. 32-bit is faster on ARM only.

**Comment by RobLoach** [comment]
I'd recommend moving this discussion to either the forums, or as an issue on the PCSX core issue queue.

Audio being chopping could mean performance issues. Try frameskipping? Closing for now. Thanks!
