### ISSUE TITLE
Retroarch deleted saves after update

### ISSUE THREAD

**Issue by XKCorp** [libretro/RetroArch#10891]
Hello

I have lost my saves and states after updating Retroarch :(

RetroArch: updated from 1.8.8 to 1.8.9

OS: Ubuntu 20.04 64bit

Updated using apt-get update && apt-get upgrade
PPA repo: deb http://ppa.launchpad.net/libretro/stable/ubuntu focal main

Retroarch and Cores configurations are still here.

**Comment by bslenul** [comment]
Are you sure it's not just using a different path for your saves folder (and maybe states)? `Settings > Directory > Savefile` to double check.

**Comment by cmitu** [comment]
The defaults for Linux save paths (states/game) have been changed in 1.8.9 (with [this PR](https://github.com/libretro/RetroArch/pull/10723)). 
As @bslenul said, check if your saves are loaded/saves from/to the right location.

**Comment by XKCorp** [comment]
You are right, before version 1.8.9 Retroarch saved saves/states in the ROM directory by default, they were not deleted when upgrading.
Thank you!
