### ISSUE TITLE
[OZONE/Android] Menu Scale Factor doesn't work

### ISSUE THREAD

**Issue by andiandi13** [libretro/RetroArch#10907]
## Description

When you increase or decrease the menu scale factor, nothing happen, while it's working on PC or Nintendo Switch.

### Expected behavior

The UI size changes.

### Actual behavior

Nothing changes

### Steps to reproduce the bug

1. Go to Settings > User Interface > Appearance > Menu Scale factor
2. Reduce or increase the factor
3. See that nothing is happening

- RetroArch: 1.8.9 Android

### Environment information

- OS: Android Nougat 7.1.1

**Comment by askotx** [comment]
Previous versions worked?

**Comment by andiandi13** [comment]
@askotx Sorry I forgot to mention that, but no I never managed to reduce ozone scale.
Maybe it also depends of devices...

**Comment by DerpStation** [comment]
I can also confirm this bug, Ozone is scaled larger than I would like by default. All of the scaling options change nothing (even after restarting RetroArch).

**Comment by andiandi13** [comment]
@DerpStation It works for me on Win 7 x64 1.8.9. What version of Windows do you have

**Comment by askotx** [comment]
Works fine in v1.8.8 in Linux Debian ARM 32 (Retropie custom compilation)

**Comment by andiandi13** [comment]
Nice. It'd be great to know if it works on some Android devices/firmwares too.

**Comment by MANGOM1LK** [comment]
For me it scales down, but not up (Galaxy S9 Plus as well as Windows). The default Android UI driver feels like crap to use and it's unfortunate this is the only other option designed for touch controls

**Comment by andiandi13** [comment]
@MANGOM1LK Thank you. Yes GLUI is bad, especially it's touch sensivity :/

I think ozone could fit Android devices so we'll with scale factor and proper touch controls.

**Comment by Tromzy** [comment]
It still does not work on Android.

**Comment by Tromzy** [comment]
On my GPD XD+, scaling works from value 0.01x to 0.66x ; above that value, scaling stays the same as 0.66x.

**Comment by raidenii** [comment]
1.9.14 on Win and Linux both have the issue. On Windows 4K screen, the scale factor does not do anything beyond 1.0x. on Linux (OGA), the scale factor does not work beyond 1.5x. Is there some implicit limit in place?

**Comment by Kahmenah** [comment]
RetroArch 1.11.0 on my android 11.0 RG353P - Menu scale factor doesn't work either.  
Just adding my voice/experience.

**Comment by zsjdddfw** [comment]
RetroArch 1.12.0 on RG353P Android - ozone menu scale factor does not work. But glui, xmb scaling both work.

**Comment by sonninnos** [comment]
The maximum scale related to screen width is limited on purpose, because it would be unusable otherwise.
