### ISSUE TITLE
Retroarch CLI does not handle tilde (~) expansion properly for `--libretro` argument

### ISSUE THREAD

**Issue by malefice** [libretro/RetroArch#10905]
## Description

Retroarch CLI does not handle tilde (~) expansion properly for `--libretro` argument. I have not thoroughly checked other arguments, but `--config` does also seem affected. Using `-L` instead of `--libretro` works as expected.

### Expected behavior

It should handle tilde expansions properly. 

### Actual behavior

Commands used:

```
# This craps out
/usr/bin/retroarch --libretro=~/.config/retroarch/cores/mednafen_psx_hw_libretro.so psxgame.iso

# This works perfectly
/usr/bin/retroarch --libretro=/home/user/.config/retroarch/cores/mednafen_psx_hw_libretro.so psxgame.iso

# This also works
/usr/bin/retroarch -L ~/.config/retroarch/cores/mednafen_psx_hw_libretro.so psxgame.iso
```

This is the error log: 

```
[ERROR] Frontend is built for dynamic libretro cores, but path is not set. Cannot continue.
[ERROR] Fatal error received in: "init_libretro_symbols()"
```

### Steps to reproduce the bug

Run retroarch on the command line with `--libretro` argument and specify a "tilde-d" path within your home directory. Please refer to the commands I used above.

### Version/Commit

- RetroArch: Frontend for libretro -- v1.8.8 -- 9552f87 --

### Environment information

- OS: Pop!_OS 20.04 LTS 5.4.0-7634-generic
- Compiler: GCC (9.3.0) 64-bit Built: Jun  1 2020

**Comment by i30817** [comment]
Parameter expansion is supposed to be the shell job so i have little clue why yours is screwing up. It probably shouldn't.

**Comment by hhromic** [comment]
The problem of this case:

    # This craps out
    /usr/bin/retroarch --libretro=~/.config/retroarch/cores/mednafen_psx_hw_libretro.so psxgame.iso

Is that there is a `=` symbol directly in front of the `~`. The tilde only works when there is a blank before it:

    $ echo ~/
    /home/user/
    $ echo =~/
    =~/

Perhaps you want this?

    /usr/bin/retroarch --libretro ~/.config/retroarch/cores/mednafen_psx_hw_libretro.so psxgame.iso

**Comment by i30817** [comment]
Does retroarch expand paths in the config files btw?

**Comment by malefice** [comment]
I know that the shell is the one handling expansion, and I am aware of the alternatives recommended by @hhromic, but I was under the impression that the actual parsing of command line arguments and values are up to the programmers' discretion as well.

In any case, my mistake was my false memories of instances like `--arg=~/value` working as expected. When I tried it on other commands, they did not work, so I guess it is normal for programmers not to support the handling of tilde's in those cases. Anyway, thank you for your help. I will close this issue now.
