### ISSUE TITLE
Performace impact after reloading a core/game using FBdev on MALI G31/G52 gpus

### ISSUE THREAD

**Issue by shantigilbert** [libretro/RetroArch#10918]
## Description
When loading a game from the command line or launcher everything works as expected, but as soon as I open the RA menu, close the content and open a new (or the same) core/game the performance drops significantly

Video here: https://www.youtube.com/watch?v=F7P7iY2V1AE

This seems to affect 3D cores (Flycast, Yabasanshiro, Mupen64plus, etc) more than 2D cores (nestopia, genesis-plus-gx, mgba, etc) but this might be because of how demanding the cores are. 

I tested this on several devices:

Mali G31:
Odroid C4
Beelink GT-Mini-A
Beelink GT1-MINI 2

Mali G52:
Odroid N2
Beelink GT-King
Beelink GT-King PRO
Beelink Gs-King X

Note that this seems to only happen with FBDEV, some of these devices I tried with DRM (GBM) and they do not present this issue 

And also this issue is not present on Mali 400/450 devices I have tested using FBdev. 

### Expected behavior
Same performance after reloading

### Actual behavior
halves performance

### Steps to reproduce the bug

1. Run retroarch from command line with /usr/bin/retroarch -L /core.so game.zip (or just run Retroarch as usual and load a core from the menu)
2. Open RA menu and close content
3. Open new content (or just the same)
4. now performance is half of what it used to be

### Version/Commit
- RetroArch: 857b0da555da6fe259734956a06430d3cc187baa
Although this has been happening for a while now, I just wanted to make sure it was not something else causing it, I cannot find any other info and this seems to only happen on Retroarch, so hopefully I am asking in the right place

I have an issue on EmuELEC regarding this: https://github.com/EmuELEC/EmuELEC/issues/76
and there is more general information of what we have tried to fix it here: https://forum.odroid.com/viewtopic.php?f=181&t=34827&p=276367 but this might not be related as the overlapping was fixed already, just adding as much info as I can.  

### Environment information

- OS: EmuELEC Linux ARM 32 and ARM64
- Compiler: GCC 8.3.0 (cross-compiling)

**Comment by shantigilbert** [comment]
Adding more info to this, in this video you can clearly see the screen tearing, https://youtu.be/m_AOPy6X0Vs

And also using top:

Normal RA:
``` 
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
7370 root      20   0  908576 142384 112688 S  30.5   3.6   0:07.46 retroarch    
 ```
 
 After launching a game from the menu: 
 ```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
 7370 root      20   0 1232188 179052 122884 S 115.3   4.6   0:37.41 retroarch
 ```
 
 As you can see the CPU usage goes from 30% to 115.3%
 
 I am not sure what is going on, but does anyone have an idea on how I could potentially debug this?

**Comment by emuchicken** [comment]
It seems that when exiting to retroarch on even non-demanding games, this occurs also.  I tried it with Streets of Rage on an s905x3 2gb ram / Picodrive - and retroarch slows to a crawl.  This only really happens in arm64 tho, so perhaps the memory isn't clearing as it should?

**Comment by shantigilbert** [comment]
For me it happens on both, arm64 and arm32
