### ISSUE TITLE
[Nintendo Switch] psp problem with audren driver

### ISSUE THREAD

**Issue by Tomato-92** [libretro/RetroArch#10912]
After updating with online updater psp core has stopped working properly. Any game starts fine, but after about 10-15 minutes it freezes, and Reatroarch doesn't respond, only Home Button can help.

I tried latest nightly builds, latest stable builds, as well as deleting cfg files. Games still stop working.

Steps to reproduce the bug:

1. Use RA online updater (maybe);
2. Run psp game;
3. Wait or play for 10-15 minutes.

I think it started after some update, I haven't done anything else, my settings were the same.

- RetroArch: 1.8.9

- OS: OFW 10.0.4 Atmosphere 0.12.0

**Comment by m4xw** [comment]
First this is the completely wrong repo, 2nd it wasn't updated since over a month.
You can try switching to switch_thread audio driver in RA tho, audren is currently prone to freezes.

**Comment by Tomato-92** [comment]
If it's not a core problem, why is this repo wrong? Something happend to RetroArch with some update, I didn't notice it at once.

I'll try what you suggested, thank you.

**Comment by Tomato-92** [comment]
> First this is the completely wrong repo, 2nd it wasn't updated since over a month.

If it's not a core problem, why is this repo wrong? Something happend to RetroArch with some update, I didn't notice it at once.

I'll try what you suggested, thank you.

**Comment by m4xw** [comment]
>If it's not a core problem, why is this repo wrong? 

Its not determined yet and issues like this will usually not get much attention.
I just saw it by chance.
Also the driver wasn't changed since it was written either (over a year!), the bug exists since we wrote it, so its weird anyway but we are aware of the issue if it turns out to be this.

**Comment by Tomato-92** [comment]
> Its not determined yet and issues like this will usually not get much attention.

Btw, PPSSPP standalone works just fine, if it matters. So I guess it is something with RetroArch. But the problem appears only with psp games, I tested some other platforms and had no problems.

**Comment by m4xw** [comment]
Yea there are a few conditions that will tend to trigger it.
If standalone is fine it's not a ppsspp issue at least, my standalone port uses quite a lot of the libretro code.

**Comment by Tomato-92** [comment]
> You can try switching to switch_thread audio driver in RA tho, audren is currently prone to freezes.

It actually solved the problem. But I didn't chose audren in driver settings, I guess it happened with RA update. 
Will test other psp games if they work longer than 10 munites with switch_thread audio.

**Comment by m4xw** [comment]
@Tomato-92 What are the results?

**Comment by Tomato-92** [comment]
> @Tomato-92 What are the results?

I have no problem with psp games with switch thread audio. If I set audren my games work only for 10 minutes, or even freeze before that, RA can also freeze in menu.
