### ISSUE TITLE
Gampad analog stick causes "Floating point exception"

### ISSUE THREAD

**Issue by nurdwerks** [libretro/RetroArch#10923]
## Description
When attempting to use gamepad GPWiz40 in retroarch the interface crashes with "Floating point exception". This only occurs when the analog stick is moved. The buttons register correctly and are recognized.

### Expected behavior
Analog stick input is registered

### Actual behavior

retroarch crash

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

Other gamepads work, this behavior is on Raspberry Pi. Windows is not affected, have not tested with Ubuntu

### Version/Commit
Retroarch 1.8.9 on raspberry pi.

### Environment information

- OS: Raspberry pi OS 10.04

**Comment by twinaphex** [comment]
We need a stack trace, otherwise this is like trying to find a needle in a haystack.
