### ISSUE TITLE
Not working on Ubuntu 20.04 through the apt-get or snap store

### ISSUE THREAD

**Issue by weyzax** [libretro/RetroArch#10925]
## Description

Not working on Ubuntu 20.04 through apt-get or snap and crashes immediately.

### Expected behavior

Was supposed to start up.

### Actual behavior

Does not connect to Wayland server and returns "Segmentation fault (core dumped)"

### Steps to reproduce the bug

1. Install RetroArch on Ubuntu 20.04 through the apt-get or snap store (same error on both)
2. Run RetroArch

### Bisect Results

Tried to run this on a fresh install of Ubuntu with the latest updates.
Running "retroarch --verbose" the following:

```
[INFO] RetroArch 1.7.3 (Git b2ceb50)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Feb 11 2020
[INFO] Version: 1.7.3
[INFO] Git: b2ceb50
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ 960x720
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [GL]: Found GL context: x-egl
[INFO] [GL]: Detecting screen resolution 1366x768.
[INFO] [X/EGL]: Window manager is GNOME Shell.
[INFO] [X/EGL]: X = 0, Y = 0, W = 960, H = 720.
[INFO] [EGL]: Current context: 0x5572b1223260.
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2).
[INFO] [GL]: Version: 3.0 Mesa 20.0.4.
Segmentation fault (core dumped)
```

### Version/Commit
You can find this information under Information/System Information

- RetroArch 1.7.3 (Git b2ceb50)

### Environment information

- OS: Ubuntu 20.04 LTS

**Comment by twinaphex** [comment]
We dont provide support for such old versions. Please try this again with the latest version instead.

**Comment by hizzlekizzle** [comment]
I use Ubuntu Mate 20.04 (and just reinstalled 2 days ago) and both the snap and the v1.7.3 from the Ubuntu repos works fine here.

**Comment by keithbowes** [comment]
1.7.3 doesn't work in Wayland compositors (including GNOME) that don't support the deprecated wl_shell protocol (it works fine in X, KMS, and Wayland compositors that still support wl_shell (like Weston)).  You need at least 1.7.6 for xdg_shell support.  Though, I'm not sure why it wouldn't work in Xwayland (older versions don't for me because I don't have the X11 locale files installed, so XOpenIM() fails with the message `[ERROR] [X11]: Failed to open input method.`; actually, 0.9.8 works fine for me in Xwayland, but nothing after that does).
