### ISSUE TITLE
"Log to File" option doesn't redirect everything to the log file.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10947]
## Description

Depending on the core, some infos are still displayed on the console window instead of the log file. An example with Mupen64Plus-Next (using ParaLLEl-RDP, with other plugins it only shows `plugin_start_gfx`):

![image](https://user-images.githubusercontent.com/33353403/86143659-01501200-baf5-11ea-89bf-49c7901e8b4f.png)

You can see that some infos are still displayed on the console window. I also noticed it with PCSX ReARMed, Gambatte, VICE x64 and others, sometimes it's only like 2 or 3 lines, sometimes it's much more.

### Expected behavior

Redirects EVERYTHING in the log file. Just like when you use `retroarch > retroarch.log 2>&1` for example.

### Actual behavior

Some infos are absent from the log file because they're redirected to the console window.

### Steps to reproduce the bug

1. Go to `Settings > Logging` and enable both "Verbose" and "Log to File".
2. Start one of the cores affected by this, PCSX ReARMed for example.
3. Check the console window, these lines will be missing from the log file.

### Bisect Results

Just went back to 1.7.7 stable, it was already happening, so I'd say it always acted like this.

### Version/Commit

- RetroArch: 1.8.9 / 6fcb97e

### Environment information

- OS: Windows 10, **edit:** Linux Mint too (if you start RA from terminal, otherwise there's no console window and you have no idea if you're missing something).

**Comment by i30817** [comment]
I would like to say this is simple, but it probably isn't. Expecting to pass a file redirection to deeply embedded code in often bitrotted cores is a lot of work and somethings programs do weird things with hacks using stdout or replace it themselves, so i wouldn't be surprised if a core breaks that even if RA put in its own stream wrapper that redirected to file.
