### ISSUE TITLE
[WIN][cheevos] Access violation crash when achievement is unlocked

### ISSUE THREAD

**Issue by coldacid** [libretro/RetroArch#10966]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch crashes when unlocking and awarding an achievement.

### Expected behavior

The achievement should be awarded and RetroArch should continue to run.

### Actual behavior

`Exception code=0xc0000005 flags=0x0 at 0x0000000000764E3C. Access violation - attempting to read data at address 0x000000260000004E`

The read address remains constant through different runs of RetroArch, at least so long as it's with the same core and game selected. (In this case, it's bsnes2014 playing the unofficial English translation of Ys V.)

- [RetroArch log file](https://github.com/libretro/RetroArch/files/4874320/retroarch__2020_07_04__21_59_40.log)
- [Console log output](https://github.com/libretro/RetroArch/files/4874319/console_log_2020_07_04__21_59_40.txt)
- [Configuration](https://github.com/libretro/RetroArch/files/4874328/retroarch.cfg.txt)

### Steps to reproduce the bug

1. Start a game.
2. Perform an action which awards an achievement for the first time.
3. Boom.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.9 Windows x64, commit 4c6b13919c (also happens with 1.8.8 Windows x64)

### Environment information

- OS: Windows 10 20H1 19041.330
- Compiler: N/A

**Comment by coldacid** [comment]
I've tried running retroarch_debug.exe to get better logs for what's going on, but it crashes whenever it tries to start the core on my machine.

**Comment by coldacid** [comment]
Okay, by changing video driver to d3d11 I was able to get retroarch_debug.exe to *not* crash on game start. Location and read address are different now, though.

- [crash-200704-225814.log](https://github.com/libretro/RetroArch/files/4874355/crash-200704-225814.log)
- [retroarch__2020_07_04__22_58_08.log](https://github.com/libretro/RetroArch/files/4874356/retroarch__2020_07_04__22_58_08.log)

**Comment by twinaphex** [comment]
I don't see an obvious issue here really. Perhaps it's a NULL pointer dereference, but if so, that would be weird since it would have been an issue much earlier in the function stack.

**Comment by coldacid** [comment]
I tried it again with a different game (this time Sonic the Hedgehog) with very similar results.

- [crash-200704-233139.log](https://github.com/libretro/RetroArch/files/4874381/crash-200704-233139.log)
- [retroarch__2020_07_04__23_31_31.log](https://github.com/libretro/RetroArch/files/4874382/retroarch__2020_07_04__23_31_31.log)

Based on the stack traces, it looks like it's trying to show an achievement notification, even though as far as I can tell I've disabled on-screen notifications.

**Comment by twinaphex** [comment]
@Jamiras any ideas here?

**Comment by coldacid** [comment]
Looks like when I changed driver to d3d11 it re-enabled the on-screen notifications. Strangely, disabling them again switched the driver back to d3d12 again, although changing it back to d3d11 and then going back to the notifications and disabling them before saving configuration, quitting, and starting again seems to work around that particular bit of configuration spaghetti.

Having gone through all that, I played a bit of Sonic again and this time was able to get achievements without crashing. It looks like this issue is very much related to the on screen notification widget for achievements.

- [retroarch__2020_07_04__23_39_11.log](https://github.com/libretro/RetroArch/files/4874388/retroarch__2020_07_04__23_39_11.log)

**Comment by Jamiras** [comment]
It's an incorrect cast of a `void*`. When I moved the achievements widget into its own file (#10870), the `userdata` variable got a new meaning. In `gfx_widgets_frame`, it's assigned to `video_info->userdata`. In `gfx_widget_achievement_popup_frame`, it's passed in as a parameter. Both are void pointers, so they're interchangable. It looks like I didn't get one of the `userdata` references changed to `video_info->userdata` in the new file, so when the void pointer is cast to a driver-specific implementation, the fields are incorrect.

I'll have a PR soon. I'm surprised this was limited to D3D11/Windows.

**Comment by coldacid** [comment]
@Jamiras it's probably the same with D3D12/Windows, it's just that retroarch_debug.exe dies when starting the core when using the D3D12 driver so I couldn't get proper logging with that driver.

**Comment by Jamiras** [comment]
Verified the problem/fix also applies to D3D12.

Normally there wouldn't be any visible achievements when "starting the core", but your log does suggest it's possible:
```
[INFO] Loading state: "C:\Tools\retroarch\states\Ys V - Kefin, The Lost City of Sand.state".
[INFO] State size: 384040 bytes.
[INFO] [RCHEEVOS]: awarding cheevo 41800: Defeat Agnihume (Defeat the Fire Beast Agnihume)
```
Apparently, the auto-resume state is triggering an achievement.

**Comment by coldacid** [comment]
Without monitoring the log file as it changes I can't be sure of that, but I don't believe that it's triggering on resume state. Generally it would unlock the achievement and then crash; "Defeat Agnihume" in Ys V and "Newbie Collector" in Sonic the Hedgehog appear to be outliers in that Retroarch crashed ahead of the unlock preventing further progress in the games. (I had a number of achievements in Ys V unlock despite the crash.)

Having just run retroarch_debug.exe with the D3D12 driver selected again, and choosing a game I've been able to play in other emulators but haven't run in Retroarch before, it CTD'd again when I said to run that game. (In this case, Sub-Terrania.) It definitely looks like the D3D12 debug build crash is a different issue.
