### ISSUE TITLE
RetroArch x Compressed games

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#10962]
Some cores do not recognize the game if it is compressed in some way (.zip or. Rar).

An option to choose to unzip the rom before playing could be added to RetroArch.

**Comment by i30817** [comment]
The reason this happens is because the library needed is not linked in the build for the platform you're writing about. There may be valid or invalid reasons for it.

Personally i wouldn't bother with compression in many resource limited platforms.

**Comment by AlanRibas** [comment]
> The reason this happens is because the library needed is not linked in the build for the platform you're writing about. There may be valid or invalid reasons for it.
> 
> Personally i wouldn't bother with compression in many resource limited platforms.

I understood. I try to compress a good part of my games for two reasons. First "organization", sometimes a single game has more than one file, and second is to save space on the HD drive.
If you happen to know any way to fix this problem I have please tell me what I can do.
The point is that a lot of my games are compressed ... about 90%.
So if there is a way to avoid having to unzip them I will go that way.

**Comment by i30817** [comment]
I don't. I don't actually care about multiple files (i place each game in a dedicated directory because of patches, readmes, etc); and i use external (operating system) read-only compression, which isn't exactly convenient (you can't update the filesystem), but it's faster than most.

**Comment by keithbowes** [comment]
> Some cores do not recognize the game if it is compressed in some way (.zip or. Rar).
> 
> An option to choose to unzip the rom before playing could be added to RetroArch.

Do any cores actually support .rar files?  RetroArch itself supports .zip and .7z archives (unless compiled with --disable-zlib and --disable-7zip, respectively) and will temporarily extract the contents (seemingly so the core itself doesn't have to deal with compressed files).  I doubt it would be worth it to support the ancient proprietary RAR format (and it seemingly requires explicit permission to do so legally, as the license forbids reverse engineering the format).

BTW, ancient versions of RetroArch (< 0.9.8) had a retroarch-zip script that would extract the contents of .zip, .7z, and .rar files (with unzip, 7z, and unrar, respectively), but that seems to have disappeared as soon as builtin support for extracting .zip and .7z files was implemented.

**Comment by AlanRibas** [comment]
> > Some cores do not recognize the game if it is compressed in some way (.zip or. Rar).
> > An option to choose to unzip the rom before playing could be added to RetroArch.
> 
> Do any cores actually support .rar files? RetroArch itself supports .zip and .7z archives (unless compiled with --disable-zlib and --disable-7zip, respectively) and will temporarily extract the contents (seemingly so the core itself doesn't have to deal with compressed files). I doubt it would be worth it to support the ancient proprietary RAR format (and it seemingly requires explicit permission to do so legally, as the license forbids reverse engineering the format).
> 
> BTW, ancient versions of RetroArch (< 0.9.8) had a retroarch-zip script that would extract the contents of .zip, .7z, and .rar files (with unzip, 7z, and unrar, respectively), but that seems to have disappeared as soon as builtin support for extracting .zip and .7z files was implemented.

thank you very much for your explanation. And thanks also to the others who came forward to clarify my doubt.
What you said made me question the compression mode that some systems I have. Most of these systems had been compacted by me. However, a few do not.
I did a test here using two compressed roms. One I downloaded from the internet and the other compressed by myself.
Conclusion: The rom compressed by me was perfectly initialized through RetroArch. It had not occurred to me that any additional configuration could hinder the unpacking of the game in this way.
What was commented on by you is something that I didn't even realize existed.

Thank you again. Thanks to you I now know what to do.
