### ISSUE TITLE
how to set default Configuration to RetroArch-0706-140137.cfg

### ISSUE THREAD

**Issue by candrapersada** [libretro/RetroArch#10974]
when starting RetroArch directly to RetroArch-0706-140137.cfg not to retroarch.cfg?
![Capture](https://user-images.githubusercontent.com/36833664/86565303-cab14600-bf91-11ea-8721-d60d2216b350.PNG)

**Comment by bslenul** [comment]
Via command line: `retroarch -c path\to\RetroArch-0706-140137.cfg`, I could be wrong but AFAIK there's no option to automatically load a specific config file, so without command line it will always load retroarch.cfg.

But this place is for bug reports, for help please use the forums, reddit or discord ;)
