### ISSUE TITLE
Retroarch not quitting "gracefully" when sent the TERM signal

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#10987]
## Description

Retroarch is not quitting "gracefully" when sent the TERM signal with the following settings : 
```
video_driver = "null"
input_driver = "udev"
```

### Expected behavior

When sent the TERM signal, RA should go through the "normal" exit sequence, meaning it's supposed to go through core's `retro_unload_game` and `retro_deinit` calls, then save its configuration files

### Actual behavior

It just stops abruptly instead.

### Steps to reproduce the bug

1. Launch Retroarch with or without a game
2. Send the TERM signal (`kill -s TERM <pid>`)

### Environment information

- OS: Linux
- Compiler: gcc-8.4.0

**Comment by hhromic** [comment]
Hi, here is some diagnostics info about the issue for the record.

Seems that RetroArch correctly implements signal handling for `SIGTERM` (as well as `SIGINT`):

https://github.com/libretro/RetroArch/blob/aa40dbd33741d284d92a72a55594eddae1427341/frontend/drivers/platform_unix.c#L2152-L2162

However the signal handler just does *nothing*, `exit()` or `abort()` (depending on how many times the signal is handled):

https://github.com/libretro/RetroArch/blob/aa40dbd33741d284d92a72a55594eddae1427341/frontend/drivers/platform_unix.c#L2139-L2150

Graceful shutdown should be implementable in line 2146 above, however I'm not sure if this was left empty intentionally or is just forgotten implementation. Perhaps more senior RA developers can chime in.

Also can confirm that the issue happens in Windows as well where there is no signal handling implemented:

https://github.com/libretro/RetroArch/blob/aa40dbd33741d284d92a72a55594eddae1427341/frontend/drivers/platform_win32.c#L1133-L1136

**Comment by twinaphex** [comment]
Forgotten implementation I think.

**Comment by hhromic** [comment]
I will do some tests then to implement a call to a graceful quit and report back.

**Comment by hhromic** [comment]
I just setup a Debian VM to test this and to my surprise RetroArch is reacting correctly to `SIGTERM`:

![VirtualBox_Debian_09_07_2020_21_57_54](https://user-images.githubusercontent.com/5802993/87090210-8216b880-c22f-11ea-890c-4d18175af07d.png)

@barbudreadmon how are you launching RetroArch exactly?
In the above example I just launch it from a terminal.

**Comment by hhromic** [comment]
Alright, I managed to reproduce it now with:

    video_driver = "null"
    input_driver = "udev"

Is that the configuration you are using?
Looks like the null video driver indeed is preventing the call to the cleanup routines.

**Comment by barbudreadmon** [comment]
that's my settings indeed, i didn't think this issue was setting related

**Comment by hhromic** [comment]
Thanks for confirming. I'll take a look as I'm also fixing crashes when using the null input driver. Will report back.

**Comment by hhromic** [comment]
@barbudreadmon found the problem and made a simple fix now in the referenced PR. It should work for you now :+1:

**Comment by barbudreadmon** [comment]
Thanks !
