### ISSUE TITLE
RetroArch crashes when loading content with D3D11 drivers and shaders.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#10986]
## Description

With D3D11 drivers selected, as soon as you load content RetroArch crashes, or as soon as you apply a shader pass/preset.

[crash-200708-125354.log](https://github.com/libretro/RetroArch/files/4890208/crash-200708-125354.log)

**edit:** from Stenzek on Discord:
```
doesn't seem to be crashing here when switching from dx11->something else
Ah, only happens with shaders
SLANG_NUM_BINDINGS is 32, D3D11 only supports 16 samplers/textures per stage
dunno how you'd need more than 16 textures anyway :stuck_out_tongue: use a texture array
hm there's also SLANG_MAX_TEXTURES
meh, I'm not sure what the difference between them is, it's not obvious based on cross-references
but, that's the problem anyway - either the D3D code has to be changed to use SLANG_MAX_TEXTURES, or the global SLANG_NUM_BINDINGS limit reduced to 16
```

### Steps to reproduce the bug

1. Switch drivers to D3D11.
2. Launch a game.
3. If it didn't crash yet, add a shader preset.

### Bisect Results

Started happening with this commit: 6df4e7778f3082700c74a268db7b87793629fea4

### Version/Commit

- RetroArch: 1.8.9 / 6df4e77

### Environment information

- OS: W10

**Comment by HyperspaceMadness** [comment]
Thanks for logging this, I'll fix this today and set SLANG_NUM_BINDINGS to 16.  

I'm pretty sure SLANG_MAX_TEXTURES is just the max which can be read out of the preset file, so I think it's the SLANG_NUM_BINDINGS  which is what an individual shader can use.

**Comment by hizzlekizzle** [comment]
Now that #10988 is merged, is this issue resolved?

**Comment by HyperspaceMadness** [comment]
Yes, I tested loading a shader in D3D11 and it is now working. 

Is this the something I should be setting to resolved if my fix is in?

**Comment by bslenul** [comment]
Issue fixed, yup! I'll close this.

Thanks for the fix 👍
