### ISSUE TITLE
Typo:  Tringle -> Triangle

### ISSUE THREAD

**Issue by BugReportering** [libretro/RetroArch#10991]
![RetroArch_typo_Tringle_Triangle](https://user-images.githubusercontent.com/66106762/86988643-bbcfbc80-c166-11ea-883a-e1fff8bee006.png)

**Comment by bslenul** [comment]
Damn, you could have spent 5 more seconds to at least tell us it was with Play! core...

**Comment by BugReportering** [comment]
> Damn, you could have spent 5 more seconds to at least tell us it was with Play! core...

That should have been obvious, since no other controllers use triangles for a button.

**Comment by ds22x** [comment]
Except for PPSSPP, as well as all the PS1 cores.

**Comment by gouchi** [comment]
@BugReportering please close this issue as the [fix has been merged upstream](https://github.com/jpd002/Play-/pull/924). Thank you.

**Comment by BugReportering** [comment]
> Except for PPSSPP, as well as all the PS1 cores.

Well, it probably wouldn't hurt to check if it was spelled correctly there too.
