### ISSUE TITLE
Mac Metal build can't load cores

### ISSUE THREAD

**Issue by Herdinger** [libretro/RetroArch#10995]
If I try to load a core in RetroArch Metal 1.8.9 on MacOS 10.15.5 with SIP enabled dlopen fails.

The reason for this is that the build uses hardened runtime, since we need to get notarized.

This commit reverts the necessary exceptions that Retroarch needs to run, I guess the metal build has been broken since then:
https://github.com/libretro/RetroArch/commit/df0f334b9734219248c67368b00562eee06e3cd4

I hope there is going to be a hotfix, since the metal build is basically unusable except for the menu

**Comment by twinaphex** [comment]
We need Mac coders onboard to help us out with these things. We don't have any dedicated Mac people currently.

If you'd like to volunteer, by all means.

**Comment by twinaphex** [comment]
IIRC there were issues with that entitlements file where Travis could no longer build it or something, I dunno. Again, I keep having to stress the point - we need more Mac coders submitting PRs and helping out, and we needed them yesterday.

**Comment by Herdinger** [comment]
I promise I'll think about it in general, even tho I'm not a Mac dev by trade.
To me it seems as if the build Failure was a spurious one.
I guess I'm going to try opening a pull request with the exact same changes and see if it fails.
