### ISSUE TITLE
[Nightly] How to disable the splashscreen?

### ISSUE THREAD

**Issue by awsms** [libretro/RetroArch#10998]
Since the latest update (git version 375d6b9), there is an annoying splash screen at the beginning of each game. Is there any way to disable it? I couldn't find an option in the settings.
![Screenshot from 2020-07-10 06-25-43](https://user-images.githubusercontent.com/48278661/87116608-7ef2eb00-c276-11ea-9ba8-9862f9b823c6.png)

**Comment by twinaphex** [comment]
On-Screen Display -> Onscreen Notifications -

![image](https://user-images.githubusercontent.com/1075274/87118364-7cdf5b00-c27b-11ea-98d0-c2e62d928b1d.png)

**Comment by awsms** [comment]
Thank you!
