### ISSUE TITLE
RetroAchievments + Auto-Save/Load = Freeze

### ISSUE THREAD

**Issue by adventureFAN** [libretro/RetroArch#11004]
## Description
When I activate RetroAchievments (log in) and activate auto-saving/loading-feature RetroArch freezing when I exit the game (Games with Achievments).

This happens when the command line is executed.

Example:
/usr/bin/retroarch -v -L /tmp/cores/snes9x_libretro.so --config /storage/.config/retroarch/retroarch.cfg "/storage/roms/snes/Super Mario All-Stars (USA).zip"

### Expected behavior
No freeze and auto-savestate

### Actual behavior
System freeze

### Steps to reproduce the bug
1. Activate Wifi
2. RetroAchievments login
3. Activate Auto-Save/Loading Feature in the "Settings"/"Saving" menu
4. Start a game with Achievments like Super Mario All-Stars
5. Exit the game -> Freeze happens

### Bisect Results
With 1.8.8. this combination works but not with 1.8.9 
Without RetroAchievments Auto-save/load works fine.
Or RetroAchievments activated but auto-save/load off works also fine.

### Version/Commit
Build date: Jul 8 2020
Git Version: d748b37e6b

### Environment information
Device: Odroid Go Advance
OS: EmuELEC 3.6 (and latest Test-Release)
https://github.com/EmuELEC/EmuELEC
https://github.com/EmuELEC/EmuELEC-tests/releases

**Comment by shantigilbert** [comment]
It seems this commit is the one that causes the issue: 6083450d4e2c49da74d0c4a4a1a4833a2a6a66fa
anything below that will work fine, anything above that will cause a hang with cheevos+auto save enabled

**Comment by shantigilbert** [comment]
Also this seems to be the same issue as #10943

**Comment by Jamiras** [comment]
I agree. This seems to be a duplicate. Thanks for identifying the bad commit.

**Comment by adventureFAN** [comment]
Duplicated Issue
