### ISSUE TITLE
Crash switching between .png files in ImageViewer Core

### ISSUE THREAD

**Issue by HyperspaceMadness** [libretro/RetroArch#11013]
###  Description

When using Imageviewer core and stepping through a series of .png files retroarch gives a hard crashe and disappears.

### Steps to reproduce the bug

1. Load Image Viewer Core (In my case I have retroarch set as the application to read .pngs so I just double click the .png from windows explorer)
2. Load "0 1 White.png"
3. Step forward to "0 12 White avspu.png" which should make it crash
Attached are the images to test with

### Bisect Results

I did a bunch of local builds to see where it starts happening and it's somewhere between:

#6085ed35 June 27 15:09 

and 

#1a625f32 June 28th 14:40 

### Environment information

- OS: Windows
- Compiler: MSYS2 MingW64

![0 1 White](https://user-images.githubusercontent.com/19496582/87253237-99c88980-c447-11ea-883c-128552e5fe0e.png)
![0 12 White avspu](https://user-images.githubusercontent.com/19496582/87253238-99c88980-c447-11ea-8bb8-de423e5b72a1.png)

**Comment by Ryunam** [comment]
Are you using the Vulkan video driver? If that's the case, this might be a duplicate of another issue I posted: https://github.com/libretro/RetroArch/issues/10954

**Comment by HyperspaceMadness** [comment]
I think you're right, I'm using Vulcan too, closing as duplicate.
