### ISSUE TITLE
Cannot change to Simplified Chinese Language on Windows 10, but works fine on linux with WINE

### ISSUE THREAD

**Issue by Zalica** [libretro/RetroArch#11028]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When I change to Simplified Chinese,it seems to be working fine before restart. but when I restart retroarch ,the program just crash before it can show any user interface.I tried Japanese and Traditional Chinese,they both work fine.

### Expected behavior

retroarch should restart nornally

### Actual behavior

retroarch cannot initiate when using Simplified Chinese language file。according to the log:
[INFO] RetroArch 1.8.9 (Git 4c6b13919c)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
[INFO] 容量:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
[INFO] Built: Jun 19 2020
[INFO] Version: 1.8.9
[INFO] Git: 4c6b13919c
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Overrides]: 重定向游戏存档文件至 "H:\PortableApps\RetroArch\saves\.srm".
[INFO] [Overrides]: 正在重定向状态存储至 "H:\PortableApps\RetroArch\states\.state".
[INFO] libretro API 版本: 1
[INFO] 未按照 API 编译: 1   (this line says something like not comlied according to the API)
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [SoftFilter]: Found plug: 2xBR (2xbr).
[INFO] [SoftFilter]: Found plug: 2xSaI (2xsai).
[INFO] [SoftFilter]: Found plug: Blargg NTSC SNES (blargg_ntsc_snes).
[INFO] [SoftFilter]: Found plug: Darken (darken).
[INFO] [SoftFilter]: Found plug: EPX (epx).
[INFO] [SoftFilter]: Found plug: LQ2x (lq2x).
[INFO] [SoftFilter]: Found plug: Normal2x (normal2x).
[INFO] [SoftFilter]: Found plug: Phosphor2x (phosphor2x).
[INFO] [SoftFilter]: Found plug: Scale2x (scale2x).
[INFO] [SoftFilter]: Found plug: Scanline2x (scanline2x).
[INFO] [SoftFilter]: Found plug: Super2xSaI (super2xsai).
[INFO] [SoftFilter]: Found plug: SuperEagle (supereagle).
[INFO] Using 1 threads for softfilter.
[INFO] [Video]: Video @ 960x720
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1920x1080.
[ERROR] [WGL]: win32_set_video_mode failed.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"

### Steps to reproduce the bug

1. change language to simplified Chinese.
2. reboot
3. program doesn't start normally

### Bisect Results

Far as I could remember,it should work fine when using 1.8.8.  however,the problem happened about 4 days ago,and I was using 1.8.9 then.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: RetroArch 1.8.9 (Git 4c6b13919c)

### Environment information

- OS: Windows 10 build 2004  x86_64,the system language is zh-cn
- Compiler: [In case you are running local builds]

**Comment by Zalica** [comment]
Test again on Linux with WINE,the problem is gone.But back on Windows 10,the problem comes back again.

**Comment by soarqin** [comment]
Met this issue too, and found that it should be recently fixed by commit 3c6552ba4dbf5c8777f38e81e6b9af14b4b07e08
Note: the same problem as #10963 and #11254
