### ISSUE TITLE
No exit on error when launched with command line arguments

### ISSUE THREAD

**Issue by bkg2k** [libretro/RetroArch#11020]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Running Retroarch v1.8.9 on RPi from the command line does not exit when the core exits for some reasons (missing bios, cannot load content, ...)

### Expected behavior

When launched from the command line to execute a single task, Retroarch must quit on error. This is the default behavior up to v1.8.8 (tested).

### Actual behavior

Retroarch's menu opens. Only the keyboard is active. Configured pads/joysticks are all inactive.

### Steps to reproduce the bug

Run a core with content it can't open:
/usr/bin/retroarch --verbose -L /usr/lib/libretro/whatever_core.so --config whatever_config.cfg whatever_invalid_rom.ext

### Version/Commit

Issue happened in Retroarch v1.8.9. Everything was fine until this version.

### Environment information

- OS: Buildroot Linux (Recabox) on multiple platforms: RPi, Odroid Xu4, x86/x64, ...
- Compiler: Cross compiler GCC 7.5.3

**Comment by cmitu** [comment]
The behavior was changed in https://github.com/libretro/RetroArch/pull/10874.

**Comment by bkg2k** [comment]
That means retroarch can no longer be launched from a top-level frontend.

We will have to patch to revert the "fix" from https://github.com/libretro/RetroArch/pull/10874 or keep the 1.8.8. Both solutions are not what I was expecting for :(

**Comment by hizzlekizzle** [comment]
the third option would be to make a case for the old behavior and discuss how we might reconcile the benefits of that commit with the need to exit-on-error.

**Comment by bkg2k** [comment]
Adding a new command line argument, say '--exit-on-error' for example, to get the old exit-on-error behavior, could be an elegant third solution, I agree.

**Comment by jdgleaver** [comment]
#10874 did not cause this...

Could you please bisect and find the actual commit that changed this behaviour?

**Comment by bkg2k** [comment]
Not easy with buildroot, but yes, I'll do it asap (even manually)

**Comment by bslenul** [comment]
Looks like it started happening here: b74b8b6a6cacf1b09dba850b727b2d7279c4f753

**Comment by jdgleaver** [comment]
Ah, that's great - thanks! I can see why that would change things.

I'll see if I can rework that as a command line option.

**Comment by jdgleaver** [comment]
Okay, this should solve the problem: https://github.com/libretro/RetroArch/pull/11063 :)
