### ISSUE TITLE
(Windows) "Display Memory Usage" option shows "free" memory instead of "used" memory.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#11038]
## Description

When enabling "Display Memory Usage" option, the notification shows "free" memory instead of "used" memory.

### Expected behavior

It should display `MEM: used / total`.

### Actual behavior

It shows `MEM: free / total`.

### Steps to reproduce the bug

1. Turn ON "Display Memory Usage".
2. Check in your OS the memory usage and you'll see that RA is displaying the "free" memory.

### Bisect Results

Started here with the "Notifications Visibility" menu: 75b3b5350c6904d7ca492c47adcc2a00d4e6a27b

### Version/Commit

- RetroArch: 1.8.9 / 3983a19281

### Environment information

- OS: Windows 10 ~~and Linux Mint~~ **edit:** nope, I derped, it displays properly on Linux (and was wrong before).

**Comment by hhromic** [comment]
Did you try latest RetroArch?

From #11033:
> The display of 'system memory' in the menu is now correctly shown as used / total (it was always meant to be thus, but due to typos/inconsistencies it previously displayed free / total)

**Comment by bslenul** [comment]
Oh, I missed that part in the description of the commit, so thanks anyway for mentioning it! But this is weird, for me it's the opposite, it showed "used" before this commit, and now it shows "free" 🤔

**Comment by hhromic** [comment]
Looks like the frontend driver is expected to provide functions to get **total** and **free** memory:

https://github.com/libretro/RetroArch/blob/8b078662cd88e54df06af1a03fa8449c96fab6a2/frontend/frontend_driver.h#L97-L98

With that the **used** memory is now just computed as the difference of these two.

However, the `win32` driver is providing functions to get **total** and **used** memory:

https://github.com/libretro/RetroArch/blob/8b078662cd88e54df06af1a03fa8449c96fab6a2/frontend/drivers/platform_win32.c#L1131-L1132

Leading to the miscalculations.

I'm not sure if this is a limitation of the Win32 API, but the function is clearly violating the driver contract. If the Win32 API indeed cannot return **free** memory, what can be done is simply to return `total - used` internally and the calculations should then work.

I can try to fix this later tonight if no one does it first :)

**Comment by hhromic** [comment]
Oh actually the Win32 `frontend_win32_get_mem_used()` function **is** getting **free** memory and doing the substraction to obtain **used** memory already:

https://github.com/libretro/RetroArch/blob/8b078662cd88e54df06af1a03fa8449c96fab6a2/frontend/drivers/platform_win32.c#L644-L659

So the solution is simply to undo that internal substraction and return the available memory directly (**free** memory).
