### ISSUE TITLE
legality of wii common key in source

### ISSUE THREAD

**Issue by Littlemac123** [libretro/RetroArch#11051]
hello libretro dev team, I wish to just worn you if you ever think about adding Dolphin emulator to steam
Dolphin emulator sense 3.0 I think or sooner has had copyrighted code from the wii system.
you see wii games are encrypted and the dolphin devs thought it would be fine to just put the wii common key on there with out any worry
the wii u emulator does not even do this with its common key
they make you have to put it in your self when you first load it
its the same thing
your dolphin core should require a bios of the wii common key if you ever do
and remove it from the core
it really is illegal

**Comment by Littlemac123** [comment]
and this has nothing to do with Gamecube games so no worry about that

**Comment by hollop90** [comment]
Here from MVG's Dolphin video. Looks like you were on the right track

**Comment by dezraj** [comment]
> Here from MVG's Dolphin video. Looks like you were on the right track

Yes, but this has been in the code for so many years now that I wonder if Nintendo didn't just hire someone to find an excuse for the copyright claim. 🤦
