### ISSUE TITLE
[Bug][Win 10 x64] Refresh rate problem

### ISSUE THREAD

**Issue by Immersion95** [libretro/RetroArch#11066]
There is a problem with how RetroArch handles 59.940 Hz refresh rate.

I don't have VRR so I wanted to have core overrides for PSX and choose 59.940 Hz instead of 60 Hz.

The thing is that RetroArch only change the refresh rate with the "Vertical Refresh Rate" setting but this causes the following issue :

-RetroArch only displays 59.940 Hz when "59" is chosen in that setting (and not "59.940" which would trigger 60Hz refresh rate instead)
-RetroArch then syncs the Video/Audio to 59.000 instead of 59.940, there are stutters in that situation

I think the solution would be to allow RetroArch to accurately read the frequencies with its decimals.

**Comment by hizzlekizzle** [comment]
You can still sync to exact content framerate even without a VRR monitor. If you're running in full screen, though, and the 59.940 modeline exists, you should be able to snap to it using the video_fullscreen_x/y and video_refresh_rate settings.

**Comment by Immersion95** [comment]
> You can still sync to exact content framerate even without a VRR monitor. If you're running in full screen, though, and the 59.940 modeline exists, you should be able to snap to it using the video_fullscreen_x/y and video_refresh_rate settings.

**Comment by Immersion95** [comment]
Hi, the thing is that I don't want to sync to the exact framerate as PSX is 59.83. I want to force it to 59.94.
"video_refresh_rate" only outputs 59.94 when "59" is chosen thus my problem.
video_refresh_rate=59.94 --> Outputs 60hz
video_refresh_rate=59.00 --> Outputs 59.94Hz but syncs to 59.00

**Comment by hizzlekizzle** [comment]
Could this be related? https://support.microsoft.com/en-us/help/2006076/screen-refresh-rate-in-windows-does-not-apply-the-user-selected-settin

**Comment by Immersion95** [comment]
I don't know, the thing is that selecting 59 switches to the correct resolution/refresh rate so RetroArch is able to do that. The problem is that Retroarch uses this exact value to sync the audio/video.

Maybe RA should have 2 separate settings :
-1 for the actual video refresh rate
-1 for the value that the user wants RA to sync the video/audio with

**Comment by drpaneas** [comment]
My screen is 144Hz butit still point to 59.977 inside retroarch. Is there any way to change this?
