### ISSUE TITLE
Video Filter can't be removed once a filter is selected

### ISSUE THREAD

**Issue by RexBorova** [libretro/RetroArch#11067]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Video Filter can't be removed once a filter is selected

### Expected behavior

Should be an option to clear filter, or choose none.

### Actual behavior

There isn't.... Once selected, it cannot be unselected unless reseting RA settings (uninstallnig/new .cfg file. This is an issue cause it will cause slowdowns on other Cores that require more CPU usage, and there's no way of turning filters off unless user resets the settings.

### Steps to reproduce the bug

1. Select filter from Settings > Video > Video Filter - *select any filter here*
2. Get stuck like a dummy with a filter always on without having an option to remove or select "No" filter
3. Wait for bparker and any other dev team member to say I'm wrong and that it's not a glitch or issue, and that it was completely intended

### Version/Commit
You can find this information under Information/System Information

- RA 1.8.9 Stable

### Environment information

- OS: Everything single one (I've tried Win10 and Android)
- Compiler: [In case you are running local builds]

End note: This is an issue because it will cause slowdowns on other Cores that require more CPU usage, and there's no way of turning filters off unless user resets the settings. Yes you can go into RA's config file and delete the selection manually, but that's tedious and sloppy. Not to mention RA by default on Android sets the .cfg location to non accessible locations where users need root access to access the file.

**Comment by hizzlekizzle** [comment]
Hover over it and press retropad-start or spacebar. This is not intuitive, I know. It's normal RetroArch behavior, but perhaps it should be added to the sublabel anyway, as it's a fairly common problem.

**Comment by RexBorova** [comment]
@hizzlekizzle Thanks for your reply man. It might be normal behavior in RA's current wacky structure, but hell if I ever knew about the mapped start button or spacebar doing that. I'm not on KB anyway on my phone nor Shield TV, and my phone is touch screen only. An option here to maybe have enable and then disable video filter, and if enabled then select filter (similar to how shaders is set up right now) might help mobile users, and save a lot of headaches for most users.

**Comment by twinaphex** [comment]
Usually press and holding touch on an entry does the same thing as pressing Start on a gamepad. You could try that.

**Comment by RexBorova** [comment]
@twinaphex Would be great to know in any description in RA anywhere. Closing this topic since there is a solution. Hopefully this info will help others.
