### ISSUE TITLE
Add neogen emulator

### ISSUE THREAD

**Issue by dudu9999** [libretro/RetroArch#11060]
# First of all, consider this:
- ----------
- ----------

## Description

[Do you intend to add a neogen emulator? As an emulator suggestion you have MAME (Multiple Arcade Machine Emulator) or Kawaks.]

### Expected behavior

[Being able to play favorite neo geo games, like The king of fighters!]

### Actual behavior

[Do not have a neo geo emulator.]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [Windown 10 pro]
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
NeoGeo games run through the various MAME cores and FBNeo/Alpha cores, and NeoCD core covers NeoGeo CD games.
