### ISSUE TITLE
[qt] settings widget, missing icons

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#11079]
## Description

In qt menu bar, view>settings, icons aren't displayed anymore.

![Untitled-1](https://user-images.githubusercontent.com/6266038/88467851-c5ce1b00-cedb-11ea-8b9b-f9ede3b70b04.png)

### Bisect Results

Started with that PR: https://github.com/libretro/RetroArch/commit/80763e0376db98cea4ad419d99cc4144540e3c96

No clue why... some list iteration issue?

### Environment information

- OS: win7 x64
- Compiler: gcc 9.2 MSYS2

In qt the icons are grabbed here https://github.com/libretro/RetroArch/blob/f94b5864b21fd6741955fcb9b4d3b9b5eb01ff88/ui/drivers/qt/viewoptionsdialog.cpp#L193

**Comment by Ryunam** [comment]
That is very strange. I did not specifically touch anything Qt-related with that PR, so it is weird that it is originating from there. I'll try to take a look, but admittedly I am a bit clueless regarding this...

**Comment by Ryunam** [comment]
Okay, I've performed a few more tests:

- commenting out the "Screenshot Flash" from all RA files restores the icons;
- however I also did another attempt by commenting out yet another uint option, "Screenshot Notification Persistence", that I had added with https://github.com/libretro/RetroArch/pull/11046, while leaving Screenshot Flash untouched. 
- By doing that, Qt icons show up again.

So it appears that the issue is not related to one specific option. Maybe, by adding the "Screenshot Flash" option, it is hitting now some kind of maximum limit of items that is affecting the Settings icons as a result.

**Comment by jdgleaver** [comment]
I can only add that this issue does not affect Linux at all - so it looks like this may be caused by a data type having different bit widths on different platforms... Very hard to debug, though, since I cannot reproduce it... :(

**Comment by Tatsuya79** [comment]
I hardcoded the assets path instead of grabbing it with
```cpp
QIcon getIcon(OptionsCategory *category)
{
   settings_t *settings        = config_get_ptr();
   const char *path_dir_assets = settings->paths.directory_assets;
   QPixmap pixmap              = QPixmap(QString(path_dir_assets) 
         + "/xmb/monochrome/png/" 
         + category->categoryIconName() 
         + ".png");
   return QIcon(getColorizedPixmap(pixmap, getLabelColor("iconColor")));
}
```

...and icons got back :thinking: 
![Untitled-1](https://user-images.githubusercontent.com/6266038/88546621-f073bd00-d01c-11ea-8097-8964608333ad.png)

**Comment by jdgleaver** [comment]
Can you printf() `settings->paths.directory_assets` there? i.e.:

```c
QIcon getIcon(OptionsCategory *category)
{
   settings_t *settings        = config_get_ptr();
   const char *path_dir_assets = settings->paths.directory_assets;

   if (path_dir_assets)
      printf("path_dir_assets: %s\n", path_dir_assets);
   else
      printf("path_dir_assets is NULL!\n");

   QPixmap pixmap              = QPixmap(QString(path_dir_assets) 
         + "/xmb/monochrome/png/" 
         + category->categoryIconName() 
         + ".png");
   return QIcon(getColorizedPixmap(pixmap, getLabelColor("iconColor")));
}
```

**Comment by Tatsuya79** [comment]
```
path_dir_assets: teurs\RetroArch64\assets
path_dir_assets: teurs\RetroArch64\assets
path_dir_assets: teurs\RetroArch64\assets
path_dir_assets: teurs\RetroArch64\assets
path_dir_assets: teurs\RetroArch64\assets
path_dir_assets: teurs\RetroArch64\assets
```
