### ISSUE TITLE
Freely associating physical devices to Retroarch ports seems not possible anymore (used to work)

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#11088]
## Description

I used to be able to assign port 1 and port 2 to the same device index, and control both players with one controller in some cores. This doesn't work anymore. Only player 1 moves, even though port 1 and 2 are set to the same device index.

Another example: When I go to settings->input->port 2 binds->device index and choose "Switch controller 1" then my first controller should control player 2 in the emulator cores, because it is assigned to Retroarch port 2. This used to work a couple months ago, but now doesn't work anymore.

EDIT: This seems to be core specific. On FBNeo core from April 21 with Retroarch from April 21 it works, on latest FBNeo from July 27 with Retroarch from July 27 it doesn't work.

On latest PUAE July 27 with latest Retroarch July 27 it works.

FBNeo latest doesn't care at all what port assignments I do in port binds it always controls player 1 with controller 1, even if port 1 device is disabled. I just set all port binds to "Switch Controller 8" and in FBNeo, I am still controlling player 1 with Switch Controller 1!!! On older FbNeo from April 2020, it works correctly I can assign a controller to port 1, 2 or both, and it controls 1, 2 or both players.

Maybe different cores read input differently, and only one way of reading input broke?
 
### Expected behavior

Freely be able to associate my devices to Retroarch ports without any restrictions.

Most importantly for Dosbox cores, it should be possible to assign the same physical controller to port 1 as device type joystick, and to port 2 as device type keyboard+mouse, to be able to make keyboard input like ESC and space in addition to mouse and joystick input with the same controller. This always used to work to control Dosbox comfortably on a console without a keyboard. The way it is now, I can still set several ports to my "Switch Controller 1" simultaneously, as I used to, but now only the input from one assignment (the first one) is processed.

### Actual behavior

It seems if only one controller is connected, it can only be assigned to port 1. Retroarch seems to not even look at the other ports anymore. This used to be different, and used to work to assign controllers to ports freely. This is a problem if for example your first enumerated controller is one you don't want to use. More importantly, assigning Switch Controller 1 to both ports 1 and 2 simultaneously was the only way to control both keyboard, mouse and joystick in Dosbox cores with a single controller. Now this functionality has been lost somehow.

### Steps to reproduce the bug

1. Go to settings->input->port 2 binds->device index. Select your first (or only) controller here
2. Boot any core that supports two players, tested using FBNeo latest.
3. Observe that your controller does NOT control player two
4. Observe that no mapping using quickmenu->controls->port two allows you to control anything in the emulator, even though your controller is assigned to this port.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: git c13c045

###Bisect

I tested July 7 2020 build and it was already broken there. Not sure when exactly it broke.

I works in April 21 build.

### Environment information

- OS: Switch

**Comment by Sanaki** [comment]
The first bad commit could be any of:
285b0ec0bb4627baad5a8d19adead187be0100d3
d97e590aafe6b6cdb0f74c3eb232752748c672fb
b1a6b35379ca34584232ca83df775a5ce9ed957a
We cannot bisect more!

Tested using Zero Wing 2P on x86_64 Linux.

**Comment by rsn8887** [comment]
Testing with Bomb Jack Twin on FBNeo I also get this problem on Windows 64bit build, using input: dinput or raw, and Controller: dinput or xinput driver settings.

**Comment by twinaphex** [comment]
That supposed culprit is no longer how that code is now currently though.

Just find a fix to this solution please. I cannot test on these platforms and the multi-button state changes were necessary in the long run. Finding a 'culprit' commit doesn't help in this case because the code has changed afterwards regardless.

**Comment by rsn8887** [comment]
This is confirmed to happen on Windows, Linux and Switch by multiple user now. It is easy to test usecase. At the moment I have no clue how to fix it.

In case anyone wants to test (quoting a message on Discord):

* I've been using Zero Wing 2P (zerowing) in FBNeo, but any 2+ player FBNeo game should work, on any platform (Windows, Linux, Switch, whatever).
* I have a game override containing these lines:
```
input_player1_joypad_index = "0"
input_player2_joypad_index = "0"
```
* Load the game, press select once the cabinet's loaded. If it adds one coin every time, it's not fixed. If it adds two, it's fixed. You can also hit start if it makes you feel better about a more comprehensive test. If the second player doesn't spawn, not fixed.

**Comment by twinaphex** [comment]
We'll need a pull request to fix this.

**Comment by rsn8887** [comment]
This commit fixes the problem on Switch: https://github.com/rsn8887/RetroArch/commit/da0a40e06d926e641bf74e69f04ff47107dab859
```(diff)
diff --git a/input/drivers/switch_input.c b/input/drivers/switch_input.c
index 76eabeac0f..cc2b7fd55d 100644
--- a/input/drivers/switch_input.c
+++ b/input/drivers/switch_input.c
@@ -394,14 +394,32 @@ static int16_t switch_input_state(void *data,
    {
       case RETRO_DEVICE_JOYPAD:
          if (id == RETRO_DEVICE_ID_JOYPAD_MASK)
-            return sw->joypad->state(
-                  joypad_info, binds[port], port);
-
-         if (binds[port][id].valid)
-            if (
-                  button_is_pressed(sw->joypad, joypad_info, binds[port],
-                     port, id))
-               return 1;
+         {
+            unsigned i;
+            int16_t ret = 0;
+            for (i = 0; i < RARCH_FIRST_CUSTOM_BIND; i++)
+            {
+               if (binds[port][i].valid)
+               {
+                  if (
+                        button_is_pressed(sw->joypad, joypad_info, binds[port],
+                           port, i))
+                     ret |= (1 << i);
+               }
+            }
+
+            return ret;
+         }
+         else
+         {
+            if (binds[port][id].valid)
+            {
+               if (
+                     button_is_pressed(sw->joypad, joypad_info, binds[port],
+                        port, id))
+                  return 1;
+            }
+         }
          break;
       case RETRO_DEVICE_ANALOG:
          break;
```

But it is present on all the platforms where such a change was made.

**Comment by rsn8887** [comment]
I found the real fix here:
https://github.com/libretro/RetroArch/pull/11095
