### ISSUE TITLE
Retroarch Android versions no more ?

### ISSUE THREAD

**Issue by WindyWinston** [libretro/RetroArch#11083]
Hi, I went to download the lastest builbot version for my Amazon Firestick 4K (32bit). There is no longer any choice for `armeabi-v7a` etc. which my device needs. I downloaded the `2020-07-26-RetroArch.apk` and installed but now when I start any game/core I can hear the audio but get a black screen. What's going on ? Did I miss something ?

**Comment by Ryunam** [comment]
The fact that you're getting a black screen with the latest nightly might be related to this other issue: https://github.com/libretro/RetroArch/issues/11080

**Comment by WindyWinston** [comment]
Yep, seems fixed now.
