### ISSUE TITLE
The pref for disabling content-load animations is badly named

### ISSUE THREAD

**Issue by keithbowes** [libretro/RetroArch#11082]
I've been thinking about creating a PR, but considering it might be rejected and that would thus be wasted effort, I thought I'd allow a conversation here.

Currently, the pref is menu_show_load_content_animation, which is incongruent with the existing menu_show_\* prefs, which indicate if an item appears in the menu (there's no "Load Content Animation" menu item).  It seems to me that it would be much more reasonable to put it as a notification_show_\* option (perhaps notification_show_content_load); in fact, it took me ages to find the pref, because I assumed it would be a notification_show_\* option.

- RetroArch: 1.8.9/75a764c668
- OS: Linux (v5.6)
- Compiler: GCC (8.4.0) 64-bit

**Comment by hizzlekizzle** [comment]
That's a fair point. I support it.

**Comment by twinaphex** [comment]
Sounds reasonable, go ahead and make the PR.

**Comment by jdgleaver** [comment]
The original intention was that there would be a menu-based fallback animation for systems without widget support - hence the `menu` prefix was used as a catch-all.

But I certainly have no objection at all to changing the variable name - `notification_show_content_load` is perfectly sensible :)

(However, I'm not sure of the implications of changing the ENUM name, now that the translations are handled via Crowdin...)
