### ISSUE TITLE
[regression] Postprocessing shader support passed away

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#11080]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Postprocessing shader support passed away

### Expected behavior

Shaders should work.

### Actual behavior

No postprocessing shaders.

### Steps to reproduce the bug

1. Start any core.
2. Go to Quick Menu.
3. No shaders at all.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 3108df009e5d9576609a2a152329c771b5d91c55

### Environment information

- OS: Windows 8.1 x64 Enterprise
- Compiler: [In case you are running local builds]

**Comment by bslenul** [comment]
Started here: cd1d760a3852258e9cab78d455c00f81193635e9
Also seems to break "gl" driver, RA starts fine but as soon as you start a game you'll get a black screen, including RA menus.

**Comment by hhromic** [comment]
Having the issue as well exactly as @bslenul described. The error seen when launching content is:
```
[INFO] [GL]: Default shader backend found: glsl.
[ERROR] [GL]: Couldn't find any supported shader backend! Continuing without shaders.
```

**Comment by Ryunam** [comment]
Looks like, with the "glcore" video driver, RA starts and plays content fine, but the Shaders option has disappeared from the Quick Menu.

**Before:**

![Annotation 2020-07-26 202524](https://user-images.githubusercontent.com/17614150/88486567-e56a4f80-cf7e-11ea-8c78-785f934cd0d8.png)

**After:**

![Annotation 2020-07-26 202931](https://user-images.githubusercontent.com/17614150/88486580-f915b600-cf7e-11ea-889c-360313c724e6.png)

**Comment by pa-august** [comment]
Also experienced this with Vlucan in WIn10, Shaders go bye bye.

**Comment by bslenul** [comment]
Yeah, the "Shaders" menu is missing with gl1, glcore and vulkan (can't check with gl due to the black screen :p), it's still here with d3d12/11/10/9 however, haven't tried the other drivers.

**Comment by hhromic** [comment]
Can confirm that this issue is now resolved with the recent reverts in the repository 👍
