### ISSUE TITLE
[iOS/tvOS] CHD not loading achievements

### ISSUE THREAD

**Issue by trebrick** [libretro/RetroArch#11099]
## Description

chd roms do not load achievements, though said roms load them fine on pc

### Expected behavior

Expect achievements list to load in quick menu

### Actual behavior

achievements arent loaded. “No achievements to display”

### Steps to reproduce the bug

1. load chd rom  
2. Click achievements in quick menu

### Version/Commit
- RetroArch: [1.8.9]

### Environment information

- OS: [ios/tvos]

**Comment by trotsky40** [comment]
This is still present in current iOS nightlies.

**Comment by trebrick** [comment]
Yah. I believe it might be same issue

**Comment by trebrick** [comment]
Yah i believe its same issue here. https://github.com/libretro/RetroArch/issues/10841

**Comment by trebrick** [comment]
Any fix for this yet?

**Comment by LibretroAdmin** [comment]
Is this still ongoing or has it been resolved?

**Comment by trotsky40** [comment]
I can confirm this is still an issue with the latest nightlies.
