### ISSUE TITLE
(Windows) Some cores don't like special characters in the rom and/or system path.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#11100]
## Description

---

I'm posting here because:

1. I'm not sure if this is a core issue or if it's part of the RA "main code".
2. Maybe someone knows about this issue for cores that I haven't mentioned.

But if that's not OK, I'll copy/paste an issue in each repo I guess...

---

The problem might be a Windows only thing, I tried on my Linux VM and my Android phone, no issue.

If you have special characters (àçéè, etc. or Chinese, Japanese, Russian, etc.) in your path for roms or system folder, some cores will fail to load content, so far I noticed the issue with these cores:

* FCEUmm, Mesen and Nestopia: special characters in rom path seem to be OK, but not in system folder path (for "disksys.rom" for FDS games for example).
* DeSmuME: fails to load roms with special characters in path, with "use real BIOS" and "boot to BIOS" options ON (and yes, in "interpreter" mode) it just ignores the real BIOS and boot straight to the game.
* PicoDrive: fails to load content (Sega CD games) if any of the rom or BIOS have special characters in their path.

For zipped roms, if you have a cache folder set in RA settings without special characters, they will load fine.

Here's a log from [someone on Reddit having issue with FDS](https://www.reddit.com/r/RetroArch/comments/hyy26n/problem_with_disk_system_emulation_c/): https://pastebin.com/AT85zkDt

And 2 others from [this person on Reddit too](https://www.reddit.com/r/RetroArch/comments/hbk3cc/failed_to_load_content_fbneo/): https://pastebin.com/pUyVPyfC (PicoDrive) and https://pastebin.com/sQ9Bb2X6 (DeSmuME)

It does NOT affect every cores, for example Beetle PSX just doesn't care and loads games properly no matter what.

### Expected behavior

Should load content, no matter which characters are used in the path.

### Actual behavior

"Failed to load content" with absolutely no hint on why it's failing.

### Steps to reproduce the bug

1. Create a "à" folder anywhere you want and put "disksys.rom" in it.
2. Start RA and change "System/BIOS" path to that folder.
3. Try running a FDS game with FCEUmm/Mesen/Nestopia.

### Bisect Results

Already happening in 1.7.5 stable.

### Version/Commit

- RetroArch: 1.8.9 / 6ccb758

### Environment information

- OS: Windows 10

**Comment by bslenul** [comment]
Another core affected, Flycast: https://github.com/libretro/flycast/issues/1068
The games boot to BIOS when using special characters.

**Comment by hizzlekizzle** [comment]
AFAIK, this is a core issue that used to be an issue in RetroArch but was fixed, and each core with the issue would need to be fixed, as well. IIRC, Desmume has the same problem.

**Comment by bslenul** [comment]
OK, I guess I'll close this then, for reference:

* DeSmuME: https://github.com/libretro/desmume/issues/70
* PicoDrive: https://github.com/libretro/picodrive/issues/123
* Flycast: https://github.com/libretro/flycast/issues/1068
* Mesen: https://github.com/libretro/Mesen/issues/5
* FCEUmm: https://github.com/libretro/libretro-fceumm/issues/448
* Nestopia: https://github.com/libretro/nestopia/issues/33

**Comment by hizzlekizzle** [comment]
@negativeExponent mentioned to me that he's getting the issue on a firmware path check, which suggests the problem has returned in RA, so probably worth investigating, even if it's just to confirm.

**Comment by bslenul** [comment]
So should I re-open this? 😅 

And shouldn't it affect all cores if it was a RA issue? For example no issue with Beetle PSX and SwanStation cores, BIOS is seen and games work fine (PCSX ReARMed doesn't see it tho, and uses HLE).

**Comment by skysbird** [comment]
![Image](https://github.com/user-attachments/assets/a2200f81-910a-47b1-a890-72091d1e49bd) try this config.
