### ISSUE TITLE
[BUG] Enabling "Menu Sounds" consistently crashes Retroarch while playing content with bsnes_libretro

### ISSUE THREAD

**Issue by andreycout** [libretro/RetroArch#11104]
## Description

When some Menu Mixer Sounds are toggled "on", bsnes will crash Retroarch if you toggle the menu on and try to resume gameplay by pressing the confirm key while highlighting "Resume" option from the Quick Menu.

### Expected behavior

Retroarch should resume gameplay normally.

### Actual behavior

Retroarch closes abruptly.

### Steps to reproduce the bug

1. On a fresh Retroarch install, go to Settings, Audio, then Menu Sounds. Turn On the following settings:
Mixer ON
Enable 'OK' Sound ON
Enable 'Cancel' Sound ON
Enable 'Notice' Sound ON
Then save config file. Might need to close Retroarch and reopen.

2. Check that navigation sounds are working. Then, load any valid content using the most recent bsnes_libretro core.

3. While playing the game, press F1 to open the menu. Move around the quick menu a bit, then return to "Resume" and press the 'Z' key (or equivalent gamepad button) to resume gameplay.

Retroarch will hang and then close.

### Bisect Results

Bsnes has been crashing for me like this for a loooong time. It's been at least 6 months. Pretty much ever since I enabled menu sounds, but I couldn't figure out what was causing the crashes. Debug logs got me nothing. So I downloaded a fresh install and did some testing, comparing the default cfg with my own and changing settings one by one. I finally managed to nail it down to the menu sounds. Who would've thought? Not sure if others cores are affected by this as well, but I've been getting some random crashes here and there. Nothing as consistent as mainline bsnes core though. It'd be prudent to investigate what's causing it on bsnes, because whatever it is, it might affect other cores as well. For now, I suggest turning navigation sounds off just to be on the safe sound. Thankfully, that's the default setting, which is why I don't think others noticed it sooner.

### Version/Commit

28/07/2020 nightly build

- RetroArch: [version/commit]

### Environment information

- OS: Windows 10 Home 64bit

**Comment by Jamiras** [comment]
I can confirm the behavior. When "resume"ing the game, the OK sound plays. 

For what's it worth, the problem doesn't seem to occur when using an `ok.wav`, but does with the default `ok.ogg` and renaming the `notify.ogg` to `ok.ogg`.
