### ISSUE TITLE
Can't use Subsystems menu properly anymore.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#11141]
## Description

On Windows when trying to load stuff using the "Subsystems" menu, you're stuck on the RetroArch main folder (displayed as `.\` on top of the screen), if you click "Parent Directory" it just reloads the same folder again. `Settings > Directory > File Browser` is completely ignored.

On Linux "File Browser" is also ignored, but it opens `/` so it's less problematic.

### Expected behavior

Open "File Browser" location by default and being able to change folder on Windows.

### Actual behavior

"File Browser" path is ignored on both Windows and Linux for default path, and on Windows the RetroArch folder is basically considered as root folder, so you can't get out of it :/

### Steps to reproduce the bug

1. Load Mupen64Plus-Next, FBNeo or any other core with subsystems.
2. Try to load something from the Subsystems menu.

### Bisect Results

Started tp happen here: 8656b3d6f8752b33aac8cd11e37aaaf8ec5f79e5

### Version/Commit

- RetroArch: 1.8.9 / e2e502f

### Environment information

- OS: Windows and Linux Mint.

**Comment by twinaphex** [comment]
Hi there,

see if this fixes it for you -

https://github.com/libretro/RetroArch/commit/36808042175f8eb7f8b5d6740c1bd27a68ca2635

**Comment by bslenul** [comment]
Yup, works fine with that commit! Thank you 👍
