### ISSUE TITLE
Video Filter or Shader?

### ISSUE THREAD

**Issue by guoyunhe** [libretro/RetroArch#11164]
I saw in RetroArch (1.9.0) menu there is Settings > Video > **Video Filters**.

But in other places, it is called **shaders**. Like the page https://www.retroarch.com/index.php?page=shaders

Should it be unified with the same term?

**Comment by hizzlekizzle** [comment]
Those are different things. The video filters run on the CPU and are pre-compiled (i.e., not really adjustable by users), while shaders are run on the GPU and are compiled at runtime and can be modified on the fly.
