### ISSUE TITLE
Ozone custom icons not loading and result in default icon

### ISSUE THREAD

**Issue by praypraynohate** [libretro/RetroArch#11197]
## Description

When attempting to create a custom icon (or duplicating existing icons in the ozone icons assets folder) for a playlist in ozone, it does not load, and results in the default icon. The same created files do load using xmb menu driver

### Expected behavior

Custom icons for my custom named playlist to load under ozone

### Actual behavior

The default system icon loads instead of any system icon

### Steps to reproduce the bug

1. create a playlist with a name that does not have an associated icon present in the assets dir
2. duplicate any icon in /assets/ozone/png/icons and name it the same as the playlist just created
3. restart retroarch and look. default icons are loaded using the ozone theme
4. if you switch to xmb menu driver, the icon you set will load over the playlist

### Bisect Results

This started happening after I started building a new retroarch build.
I took my configs and retroarch build folder from my switch and took it to Windows x64.
I downloaded the latest nightly, assets bundles, cheats, thumbnails, everything available in public repositories for the windows build. after creating playlists, I noticed playlists with custom names did not load it's custom icon

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Build Date: Aug 14 2020
Git Version 18cb55e207

### Environment information

- OS: Windows x64
- Compiler: [In case you are running local builds]
![unknown](https://user-images.githubusercontent.com/55568980/90293468-b9d5d900-de49-11ea-9c7e-c5e286ada7c7.png)

**Comment by bslenul** [comment]
Not entirely sure where these icons are used in Ozone but to modify playlist icons I always had to do it in `assets/xmb/monochrome/`.

**Comment by praypraynohate** [comment]
Oh wow. That does work. Thank you. custom icons for ozone do indeed load if put in this location.
