### ISSUE TITLE
AI Service crashes the emulator when reading a text

### ISSUE THREAD

**Issue by IlDucci** [libretro/RetroArch#11199]
## Description

After setting up the translation AI Service in RetroArch, using a ZTranslate account as some of the tutorials located in the site explain, there are times when hitting the AI Service hotkey will cause the emulator to freeze and crash. This bug doesn't happen all the times, I've managed to play for 5-10 minutes translating elements before the next translation call crashed the emulator.

I've enabled the logging feature to see if the crash popped up there, with the log level 0, and there's nothing. The last thing that's being said is "[INFO] AI Service Called..."

### Expected behavior

Every time that the AI Service hotkey is pressed, the translation will appear sooner or later.

### Actual behavior

At a random number of times (there's plenty of times where this is the first time, but there's other times where it happens after 5-10 reads), the AI Service hotkey freezes and crashes the emulator.

### Steps to reproduce the bug

1. Enable the AI Service feature.
2. Use the following settings: Enable AI Service ON, AI Service Output Text Mode, URL Ztranslate, Pause during translation Off (the issue also happened with this option enabled), Source Language Japanese, Destination Language English.
3. Boot a game. In my case, I was playing with the PlayStation title Aconcagua, using a M3U playlist.

### Bisect Results

The issues happened as this was the first time I ever used the AI Service.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Git version 18cb55e207

### Environment information

- OS: Windows 10 x64 version 1809

**Comment by BarryJRowe** [comment]
Thanks for posting this IlDucci.  Does this still happen when source language is set to “Don’t Care?”

**Comment by IlDucci** [comment]
Yes, after a couple of AI Calls, it happened again.

**Comment by BarryJRowe** [comment]
Hmm, I've been trying this on linux, and I haven't been able to reproduce it, which makes me think that this is a seg fault issue.  Are you able to test this on a previous build?  Like v.1.8.0?

**Comment by IlDucci** [comment]
I don't have any older versions and I can't get them with the BuildBot down. I'll try to search for one.

**Comment by IlDucci** [comment]
I've located a portable 1.8.0 Windows x64 installation here: https://www.emutopia.com/index.php/emulators/item/389-multi-system/615-retroarch

After setting it up and loading the same game with the same cores (I copypasted them from my latest version), the AI Service hotkey just paused the game. No translation is being displayed at all, but at least the emulator is not crashing. It's like I was just pausing the game (and I made sure that the Pause and AI Service hotkeys were not binded to the same key).

**Comment by BarryJRowe** [comment]
What's the ZTranslate URL being used exactly?  There used to be problems with some of the formatting for it, like the / at the end for a localhost one, or https vs http.

**Comment by IlDucci** [comment]
http://ztranslate.net/service?api_key=APIKEY . I just tried changing the http part to https and it tried to work twice, but then crashed.

I kinda have the feeling that, every time I change something in the Settings, it's like the AI Service has less chances to crash... at the first call. After a crash, the emulator seems to crash after the first press of the hotkey.

**Comment by BarryJRowe** [comment]
As reported by @alphacomp, it seems to happen from v1.8.6 onwards.  Perhaps related to paylists (empy playlists tend to not create the problem).
