### ISSUE TITLE
[1.9.0] controllers not being recognised correctly on Windows (8bitdo SN30 mis-identified as M30)

### ISSUE THREAD

**Issue by sota24** [libretro/RetroArch#11198]
#7818  Description

As of version 1.9.0, RetroArch 64 bit on Windows 10 is mis-identifying controllers that 1.8.9 and earlier successfully recognise.

### Expected behavior
When the 8bitdo SN30 controller is connected by Bluetooth, a message should pop up saying that the 8bitdo SN30 has connected, and its buttons should be correctly mapped in the menus (SNES B button for Yes, SNES A button for back) and games.

### Actual behavior
When the 8bitdo SN30 controller is connected by Bluetooth, a message should pop up saying that the 8bitdo M30 has connected, which is a 6 button Sega pad. The input mappings are therefore wrong as the 8bitdo SN30 is a 4-button SNES pad.

I have not changed the firmware of my 8bitdo controllers between RetroArch 1.8.9 and 1.9.0. The file autoconfig/xinput/8Bitdo_SN30_BT.cfg has the same hash in 1.9.0 as in 1.8.9. The change that causes the bug must therefore be in the executable/dll files rather than this text config file.

I also noticed that my Xbox One bluetooth controller shows up under a different name than before, though its mappings still work. I think that there is a more general problem with controller mapping in 1.9.0, it is not just the SN30 that has an issue.

### Steps to reproduce the bug

1. Start RetroArch 1.9.0 on Windows (I used the 64-bit zip file download)
2. Connect the SN30 controller.

### Bisect Results

The problem does not occur in 1.8.9, it has newly occurred in 1.9.0.

The file autoconfig/xinput/8Bitdo_SN30_BT.cfg has the same hash in 1.9.0 as in 1.8.9. The change that causes the bug must therefore be in the executable/dll files rather than this text config file.

### Version/Commit

Build date 11 Aug 2020
Git version 6388872a54

### Environment information

Windows 10 Pro 64-bit version 2004

**Comment by bslenul** [comment]
Some changes have been made with autoconfigs recently, yeah. Since your controller is probably connected in dinput mode, you could try copy/pasting `autoconfig/xinput/8Bitdo_SN30_BT.cfg` in `autoconfig/dinput/` then restart RetroArch, that *might* fix it for you.

**Comment by sota24** [comment]
Thanks @bslenul, that has fixed it in this particular case. (I guess the fix may not work for other controllers if they have different button mappings in dinput and xinput mode.) I use the SN30 in dinput mode as the xinput mode maps the dpad to a virtual analog stick, which isn't ideal for me.
