### ISSUE TITLE
retroarch ppa still defaults to xmb

### ISSUE THREAD

**Issue by soredake** [libretro/RetroArch#11206]
## Description

RetroArch ppa still defaults to using xmb as default menu driver https://git.launchpad.net/~libretro/libretro/+git/RetroArch-debian/tree/retroarch.cfg.in#n113, but retroarch switched to using ozone by default
https://www.libretro.com/index.php/retroarch-ozone-becomes-the-default-menu-ui-plus-touchscreen-and-scaling-updates/
@hunterk 

### Expected behavior

Ozone menu driver by default

### Actual behavior

Xmb menu driver is default.

### Steps to reproduce the bug

1. Install retroarch from ppa.
2. Launch it.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0 from stable ppa

### Environment information

- OS: Kubuntu 20.04
- Compiler: [In case you are running local builds]

**Comment by anthonyajumelles** [comment]
You need to file a bug with the maintainers. Ultimately they control the defaults.

Flatpak avoids this.

**Comment by soredake** [comment]
Pinging again.... @hunterk

**Comment by hizzlekizzle** [comment]
alright, I commented that line:
https://git.launchpad.net/~libretro/libretro/+git/RetroArch-debian/tree/retroarch.cfg.in#n113
so it should just use the regular default now, I think.

**Comment by soredake** [comment]
@hizzlekizzle can you also publish retroarch for groovy?

**Comment by hizzlekizzle** [comment]
Looks like it's not wanting to parse the commit properly: https://launchpadlibrarian.net/503317679/buildlog.txt.gz

It just decides to do this sometimes and then magically fixes itself. I'll try it again in a few days, but you may just have to wait for the next stable release.
