### ISSUE TITLE
Can't download cores - neither through RetroArch nor through the download link

### ISSUE THREAD

**Issue by aisopos72** [libretro/RetroArch#11204]
## Description

[Description of the bug]
I can't download the cores, be it from directly inside RetroArch or manually through the below download link in the config.
http://buildbot.libretro.com/nightly/windows/x86_64/latest/

I've checked the root folder by going to the link below and it seems there's only a folder/link for the stable build, and the nightly folder/link simply no longer exists at all.
http://buildbot.libretro.com/

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0

### Environment information

- OS: Windows 10 64bit

**Comment by s1nka** [comment]
Some error with "http://buildbot.libretro.com/nightly/linux/x86_64/latest/"
in log:
`[ERROR] Download of 'info.zip' failed: Download failed.`

**Comment by horusty** [comment]
Can also confirm this fault. 
even browsing through the stable you get a 404 after selecting a OS.

**Comment by horusty** [comment]
From what I can see on the discord the update server was hacked and will take time before its back up.

**Comment by aisopos72** [comment]
> From what I can see on the discord the update server was hacked and will take time before its back up.

Ah so it isn't just a problem on my side - glad to know. Thanks for the news! :)

**Comment by guoyunhe** [comment]
I got email notifications that @hizzlekizzle closed all PRs and emptied the repos I was working on...
