### ISSUE TITLE
Error launching retroarch in Pi4 using KMS or Legacy video driver

### ISSUE THREAD

**Issue by rtomasa** [libretro/RetroArch#11220]
## Description

I'm trying to compile retroarch for using the same in a Raspberry Pi4 using the legacy driver or the new experimantal KMS one but I've got an error related with video driver.

Please do note that I explicitly require avoid using fkms driver since is not capable of running some custom software that I'm also using in the system.

### Expected behavior

Retroarch works and launches rgui with no errors.

### Actual behavior

```
pi@raspberry:~/RetroArch $ ./retroarch --verbose
[INFO] RetroArch 1.9.0 (Git 8324a03a5e)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Aug 20 2020
[INFO] Version: 1.9.0
[INFO] Git: 8324a03a5e
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Overrides]: Redirecting save file to "/home/pi/.config/retroarch/saves/.srm".
[INFO] [Overrides]: Redirecting save state to "/home/pi/.config/retroarch/states/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ 6309x720
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[ERROR] [KMS]: Couldn't find a suitable DRM device.
[WARN] [SDL_GL]: Failed to initialize SDL gfx context driver: The video driver did not add any displays
[INFO] [GL]: Found GL context: null
[INFO] [GL]: Detecting screen resolution 320x240.
[INFO] [GL]: Vendor: (null), Renderer: (null).
[INFO] [GL]: Version: (null).
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
```

### Steps to reproduce the bug

1. Download and install 2020-05-27-raspios-buster-lite-armhf
2. Install the same in a Raspberry Pi 4
3. `sudo update`
4. `sudo upgrade`
5. Install required packages `sudo apt install git build-essential libxkbcommon-dev zlib1g-dev libfreetype6-dev libegl1-mesa-dev libgles2-mesa-dev libgbm-dev libavcodec-dev libsdl2-dev libsdl-image1.2-dev libxml2-dev yasm libavformat-dev libavdevice-dev libswresample-dev libavresample-dev libswscale-dev libv4l-dev libgl*-mesa-dev`
6. `git clone https://github.com/libretro/RetroArch/`
7. `cd RetroArch`
8. `CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --enable-opengles --enable-opengles3 --enable-kms --disable-videocore --enable-plain_drm --disable-opengl1 --enable-neon --enable-floathard --enable-alsa --enable-udev --disable-x11 --disable-pulse --disable-oss`
9. `make`

Now before trying to execute retroarch I've tried to boot up with the following drivers in `config.txt`:

**KMS**

```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
dtoverlay=vc4-kms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
```

**Legacy**

```
[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d

[all]
#dtoverlay=vc4-fkms-v3d
```

### Version/Commit

- RetroArch 1.9.0 (Git 8324a03a5e)

### Environment information

- OS:
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Comment by cmitu** [comment]
Do other KMS applications work ? Are the `/dev/dri/cardXYZ` nodes present and do you have the proper access rights to them ?

**Comment by rtomasa** [comment]
I have `/dev/dri/card0` with `666 `permissions so no issues here.
I don't know about any other KMS application for testing... I'm open for suggestions (mode test is not available in raspbian and I have no idea how to install the same).
I've tried to compile retroarch again with the same parameters but removing `--disable-videocore` and I've got the following compilation error:
```
...
CC led/drivers/led_rpi.c
LD retroarch
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_shader::Framebuffer::init()':
shader_gl_core.cpp:(.text+0xc24): undefined reference to `glTexStorage2D'
/usr/bin/ld: shader_gl_core.cpp:(.text+0xd40): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_shader::Pass::build_semantic_uint(unsigned char*, slang_semantic, unsigned int)':
shader_gl_core.cpp:(.text+0x1aa0): undefined reference to `glUniform1ui'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x1ad4): undefined reference to `glUniform1ui'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x1aec): undefined reference to `glUniform1ui'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x1b14): undefined reference to `glUniform1ui'
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_shader::Pass::build_commands(gl_core_shader::Texture const&, gl_core_shader::Texture const&, gl_core_viewport const&, float const*)':
shader_gl_core.cpp:(.text+0x29a0): undefined reference to `glBindBufferBase'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x2b5c): undefined reference to `glBindBufferBase'
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_cross_compile_program':
shader_gl_core.cpp:(.text+0x5dd0): undefined reference to `glGetUniformBlockIndex'
/usr/bin/ld: shader_gl_core.cpp:(.text+0x5dec): undefined reference to `glGetUniformBlockIndex'
/usr/bin/ld: obj-unix/release/gfx/drivers_shader/shader_gl_core.o: in function `gl_core_filter_chain_create_from_preset':
shader_gl_core.cpp:(.text+0x82d0): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl.o: in function `gl2_load_texture_image':
gl.c:(.text+0x624): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl.o: in function `gl2_renderchain_read_viewport':
gl.c:(.text+0x3588): undefined reference to `glMapBufferRange'
/usr/bin/ld: gl.c:(.text+0x3600): undefined reference to `glUnmapBuffer'
/usr/bin/ld: obj-unix/release/./libretro-common/gfx/gl_capabilities.o: in function `gl_query_extension':
gl_capabilities.c:(.text+0xdc): undefined reference to `glGetStringi'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_deinit_fences':
gl_core.c:(.text+0x71c): undefined reference to `glDeleteSync'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_fence_iterate':
gl_core.c:(.text+0xc44): undefined reference to `glFenceSync'
/usr/bin/ld: gl_core.c:(.text+0xc78): undefined reference to `glClientWaitSync'
/usr/bin/ld: gl_core.c:(.text+0xc88): undefined reference to `glDeleteSync'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_destroy_resources':
gl_core.c:(.text+0x17dc): undefined reference to `glBindVertexArray'
/usr/bin/ld: gl_core.c:(.text+0x1800): undefined reference to `glDeleteVertexArrays'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_init_hw_render':
gl_core.c:(.text+0x1b64): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_init':
gl_core.c:(.text+0x37f0): undefined reference to `glGenVertexArrays'
/usr/bin/ld: gl_core.c:(.text+0x3800): undefined reference to `glBindVertexArray'
/usr/bin/ld: gl_core.c:(.text+0x3808): undefined reference to `glBindVertexArray'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `video_texture_load_gl_core':
gl_core.c:(.text+0x39b4): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_read_viewport':
gl_core.c:(.text+0x4788): undefined reference to `glMapBufferRange'
/usr/bin/ld: gl_core.c:(.text+0x4818): undefined reference to `glUnmapBuffer'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_update_cpu_texture':
gl_core.c:(.text+0x49f8): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_frame':
gl_core.c:(.text+0x4f5c): undefined reference to `glBindVertexArray'
/usr/bin/ld: gl_core.c:(.text+0x54b4): undefined reference to `glBindVertexArray'
/usr/bin/ld: obj-unix/release/gfx/drivers/gl_core.o: in function `gl_core_set_texture_frame':
gl_core.c:(.text+0x5afc): undefined reference to `glTexStorage2D'
/usr/bin/ld: obj-unix/release/gfx/drivers_font/gl_core_raster_font.o: in function `gl_core_raster_font_upload_atlas':
gl_core_raster_font.c:(.text+0x204): undefined reference to `glTexStorage2D'
collect2: error: ld returned 1 exit status
make: *** [Makefile:201: retroarch] Error 1
```

**Comment by gouchi** [comment]
You may try also [kmscube](https://gitlab.freedesktop.org/mesa/kmscube).

Sidenote, if you can try our [Lakka nightly build](http://nightly.builds.lakka.tv/2020-08-23/RPi4.arm/) for testing purpose.

If you want to check [our build options](https://github.com/libretro/Lakka-LibreELEC/blob/master/packages/libretro/retroarch/package.mk#L98-L100) for RA.

Thank you.

**Comment by rtomasa** [comment]
Sure, I'll try using kms driver with the nightly build and let you know the results

**Comment by rtomasa** [comment]
@gouchi I've tested lakka nightly build Pi4 with rgb-pi and vga666 and I've got the same results:
- FKMS: system loads and I can also load games but neither CRT switchres nor vcgencmd are able to change timings anymore.
- KMS and LEGACY: the system is not able to boot up.

So it seems that GPIO add-ons are not managed properly in Pi4

**Comment by cmitu** [comment]
> FKMS: system loads and I can also load games but neither CRT switchres nor vcgencmd are able to change timings anymore.

That's expected, since the Pi4 doesn't use the legacy (Broadcom) drivers anymore. As mentioned in https://github.com/raspberrypi/firmware/issues/1456, the resolution switch needs to be done via KMS/DRM with the new drivers.

**Comment by rtomasa** [comment]
@cmitu Unfortunately the issue raspberrypi/firmware#1456 that I myself closed is not correct, and I'll reopen the same because my test was not correct due to that I assumed that using `dtoverlay=vc4-kms-kippah-7inch` alone was actually also loading the kms driver but that was not the case, and when loaded timings do not change either.

Also this does not explains why retroarch is not working with KMS or Legacy in CLI.

Also this does not make clear to me why CRT Switchres creator is claiming that X11 is not required and that v2.0 of the CRT switchres is based on vcgen API which AFAIK is the same as manually using vcgencmd which it is supossed that only works with Legacy driver.

Sorry but there is a bunch of things and spare threads caliming things working in one way and another but I was not able to make anything work nor get a full explnation on the whole scenario.

**Comment by cmitu** [comment]
Regardless, of your setup, RetroArch works fine with KMS. The seems to be the KMS driver - or its setup - in your installation.

> Also this does not make clear to me why CRT Switchres creator is claiming that X11 is not required and that v2.0 of the CRT switchres is based on vcgen API which AFAIK is the same as manually using vcgencmd which it is supossed that only works with Legacy driver.

Yes, but on the Pi4 the legacy driver is no longer working. CRT Switchres will not work with KMS.

**Comment by rtomasa** [comment]
@cmitu FYI using the KMS driver, I confirm you that the root cause was indeed the fact that when sending the video trough GPIO using RGB-Pi or VGA666, there is no display nor any available resolution reported (as seen from modetest), so retroarch is not able to launch.
I've tested using a HDMI to VGA adapter and modetest reported all display information properly and retroarch worked fine. So this points me out to the lack of EDID info when using GPIO adapters. Why Pi2/3 worked OK but now is not? maybe the way KMS works internally requires EDID information, I don't know.
Regarding CRT Switchres and vcgencmd I also confirm that it is not working with KMS as you said, so I'm not sure how @alphanu1 managed to make it work in all the tests using a Pi4 in CLI with no X11...

**Comment by alphanu1** [comment]
HI All,

From all my testing I found that the RPis video is not very good when using CRTSeitchRes. Even using full kms with opgles and a full X11 enviroment showed poor results. 

Using X11 you can switch resolutions but only the virtual framebuffer would change size. Leading to scalled and or I correct video outputs. 

CLI mode using legacy video driver only works when using dispmanx video output. Even in this state switching resolutions was not perfect. The tvservice command does not work. So we are unable to rrlead the video output with the new resolution. 

CLI using full KMS. I beleave I was able to use vcgencmd to add the modeline. Some user arr saying this should not work but it does. However, the tvservice command would not work leaving the user with a blank screen. This is whats used to refresh the vidoe output and display the new resolution. On some occasions I was able to switch tty from and back to tty1 showing the switch resolution. However, this would be CLI not retoarch. As it seems RA crashes at this point.

I have been holding off on implimentation. Hoping a working full legacy driver will be released. I assume though this will not be happening.

I hope this information helps out.

**Comment by rtomasa** [comment]
@alphanu1 Thanks for the input. Sadly based on all my tests, all infor provided by @cmitu, and now your comments on this specific switchres topic, it seems that people using CRTs for emulation are now stuck in Pi3 forever and ever. As you said, all efforts seem to be dedicated to standard KMS driver making vcgencmd, tvservice and fbset commands also deprecated in a non-working status with KMS driver.

So thank you all guys for making all this topics more clear and preventing me from wasting more time on the same.

**Comment by rtomasa** [comment]
@cmitu I forgot to ask you one question before closing the issue. Do you know why retroarch is not working using the legacy driver via standard HDMI in Pi4?

```
[INFO] RetroArch 1.8.8 (Git 9552f87)
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/megadrive/Aladdin (USA).srm".
[INFO] Redirecting save state to "/home/pi/RetroPie/roms/megadrive/Aladdin (USA).state".
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun  9 2020
[INFO] Version: 1.8.8
[INFO] Git: 9552f87
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/opt/retropie/libretrocores/lr-genesis-plus-gx/genesis_plus_gx_libretro.so"
[INFO] [Overrides] no core-specific overrides found at /home/pi/.config/retroarch/config/Genesis Plus GX/Genesis Plus GX.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /home/pi/.config/retroarch/config/Genesis Plus GX/megadrive.cfg.
[INFO] [Overrides] no game-specific overrides found at /home/pi/.config/retroarch/config/Genesis Plus GX/Aladdin (USA).cfg.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] Core requested VFS version >= v1, providing v3
[INFO] [Remaps]: remap directory: /home/pi/.config/retroarch/config/remaps
[INFO] Redirecting save file to "/home/pi/RetroPie/roms/megadrive/Aladdin (USA).srm".
[INFO] Redirecting save state to "/home/pi/RetroPie/roms/megadrive/Aladdin (USA).state".
[INFO] [Environ]: PERFORMANCE_LEVEL: 1.
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: PERFORMANCE_LEVEL: 7.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] Frontend supports RGB565 - will use that instead of XRGB1555.
[WARN] SYSTEM DIR is empty, assume CONTENT DIR /home/pi/RetroPie/roms/megadrive/Aladdin (USA).zip
[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/pi/RetroPie/roms/megadrive/".
[libretro INFO] Game Genie ROM should be located at: /home/pi/RetroPie/roms/megadrive//ggenie.bin
[libretro INFO] Action Replay (Pro) ROM should be located at: /home/pi/RetroPie/roms/megadrive//areplay.bin
[libretro INFO] Sonic & Knuckles (2 MB) ROM should be located at: /home/pi/RetroPie/roms/megadrive//sk.bin
[libretro INFO] Sonic & Knuckles UPMEM (256 KB) ROM should be located at: /home/pi/RetroPie/roms/megadrive//sk2chip.bin
[libretro INFO] Mega Drive TMSS BOOTROM should be located at: /home/pi/RetroPie/roms/megadrive//bios_MD.bin
[libretro INFO] Game Gear TMSS BOOTROM should be located at: /home/pi/RetroPie/roms/megadrive//bios.gg
[libretro INFO] Master System (PAL) BOOTROM should be located at: /home/pi/RetroPie/roms/megadrive//bios_E.sms
[libretro INFO] Master System (NTSC-U) BOOTROM should be located at: /home/pi/RetroPie/roms/megadrive//bios_U.sms
[libretro INFO] Master System (NTSC-J) BOOTROM should be located at: /home/pi/RetroPie/roms/megadrive//bios_J.sms
[libretro INFO] Mega CD (PAL) BIOS should be located at: /home/pi/RetroPie/roms/megadrive//bios_CD_E.bin
[libretro INFO] Sega CD (NTSC-U) BIOS should be located at: /home/pi/RetroPie/roms/megadrive//bios_CD_U.bin
[libretro INFO] Mega CD (NTSC-J) BIOS should be located at: /home/pi/RetroPie/roms/megadrive//bios_CD_J.bin
[libretro INFO] Mega CD (PAL) BRAM is located at: /home/pi/RetroPie/roms/megadrive//scd_E.brm
[libretro INFO] Sega CD (NTSC-U) BRAM is located at: /home/pi/RetroPie/roms/megadrive//scd_U.brm
[libretro INFO] Mega CD (NTSC-J) BRAM is located at: /home/pi/RetroPie/roms/megadrive//scd_J.brm
[libretro INFO] Sega/Mega CD RAM CART is located at: /home/pi/RetroPie/roms/megadrive//cart.brm
[libretro INFO] INFORMATION - Loading 2097152 bytes ...
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /home/pi/.config/retroarch/cheats/Genesis Plus GX/Aladdin (USA).cht
[INFO] [Audio]: Set audio input rate to: 44156.86 Hz.
[INFO] [Video]: Video @ 879x576
[ERROR] [KMS]: Couldn't find a suitable DRM device.
[INFO] [SDL_GL] SDL 2.0.10 gfx context driver initialized.
[INFO] [GL]: Found GL context: sdl_gl
[INFO] [GL]: Detecting screen resolution 1280x720.
* failed to add service - already in use?
```

**Comment by alphanu1** [comment]
@rtomasa from what I found. You have to disable videocore disable gles disable opengl and enable dispmanx as this is the only video driver that seems to work with the legacy driver.

You may need to add video diver = dispmanx to the RA CFG

**Comment by rtomasa** [comment]
@alphanu1 unfortunately I've tried to compile retroarch with --enable dispmanx to make it available and I got an error which I was able to rapidly find in issue #9727 which also confirms that dispmanx is not available in Pi4 anymore.
