### ISSUE TITLE
(Bluetooth) Dualshock 4 and Xbox one controller doesn't respond in macOS Catalina

### ISSUE THREAD

**Issue by bluedev93** [libretro/RetroArch#11228]
## Description

Xbox one controller (model 1708) and Dualshock 4 controller not responding with bluetooth (retroarch menu and games). Input monitoring is turned on and I updated the Joypad profiles. I can map the buttons but in the interface and games it doesn’t respond

I tested these controllers with the official mGBA emulator and there they work.

### Expected behavior

After I mapped the controls that I can use these controllers

### Actual behavior

The controllers do map them but they don't work

### Steps to reproduce the bug

* pair the controller
* start retroarch
* test the controller

### Bisect Results

-

### Version/Commit

- RetroArch: GIT_VERSION Aug 8 2020

### Environment information

- OS: macOS Catalina 10.15.6
- Compiler: -

**Comment by Cee123** [comment]
There is a bug on the regular Wii as well, where the wiimote and nunchucks won't respond on certain emulators. I've been having the same trouble with unresponsive controls on the latest version of RetroArch 1.9.0 and all nightlies for that version. Emulators such as Mgba, Snes9x, Mednafen VB, Mednafen pce fast, NXEngine etc all have an issue with the controllers don't respond.

**Comment by bluedev93** [comment]
It seems fixed on the last nightly build for macOS. I will close this issue. After opening it try mapping again and you will see that it works.

**Comment by Cee123** [comment]
> It seems fixed on the last nightly build (Aug 28 2020) for macOS. I will close this issue. After opening it try mapping again and you will see that it works.

Nice!
