### ISSUE TITLE
[WIIU] Disconnecting a Wii Classic Controller while RetroArch is running breaks all Wiimote/CC input.

### ISSUE THREAD

**Issue by vaguerant** [libretro/RetroArch#11234]
## Description

If a Classic Controller (the controller type which plugs into the extension port on the bottom of a Wii Remote) ever becomes disconnected from RetroArch, either in menus or gameplay, it becomes permanently non-functional until RetroArch is restarted. At the same time, the Wiimote it is attached to *also* ceases to function. This disconnection can be either physical (unplugging the Classic Controller from the Wii Remote) or wireless (allowing the Wiimote to time out from inactivity, or removing a battery).

Wiimote input can be restored by disconnecting the Wiimote (either waiting for the timeout or yanking a battery works) then reconnecting it **with nothing in the EXT port**. This however does **not** restore Classic Controller input. If the CC is at any time plugged into the Wiimote (either before or after power-up), input enters the same non-functional state requiring a complete power off of the Wiimote to get it back.

### Expected behavior

The Classic Controller/Wiimote combo should be able to be unplugged, replugged, disconnected and reconnected without input breaking.

### Actual behavior

Wiimote/CC input breaks if you unplug, replug, disconnect or reconnect the controllers.

### Steps to reproduce the bug

Route 1:
1. Have a Wiimote & CC connected to RetroArch
2. Unplug the Classic Controller
3. Note that all input has stopped working

Route 2:
1. Have a Wiimote & CC connected to RetroArch
2. Disconnect the Wiimote & CC combo from the Wii U (timeout or battery yank)
3. Reconnect the Wiimote & CC combo to the Wii U
4. Note that all input has stopped working

### Bisect Results

I never encountered this issue before updating to 705b281, but I am **not** certain that the issue didn't exist, I may just not have triggered it. Helpfully, I am also unsure what version I updated from. I'm not set up for compiling RetroArch Wii U currently, and the buildbot has obviously been cleared of old nightly and stable builds as a result of the hack. I could probably be convinced to try to get set up if this issue proves difficult enough to track down.

### Version/Commit

- RetroArch: 705b281

### Environment information

- OS: Wii U, System Menu 5.5.4, PAL

**Comment by Cee123** [comment]
There is a bug on the regular Wii as well, where the wiimote and nunchucks won't respond on certain emulators. I've been having the same trouble with unresponsive controls on the latest version of RetroArch 1.9.0 and all nightlies for that version. Emulators such as Mgba, Snes9x, Mednafen VB, Mednafen pce fast, NXEngine etc all have an issue with the controllers don't respond.

**Comment by willianholtz** [comment]
Pro control doesn't work in any other build, since version 1.8.9.

**Comment by vaguerant** [comment]
I was able to downgrade back to [1.8.9 via archive.org](https://web.archive.org/web/20200621223915/https://buildbot.libretro.com/stable/1.8.9/nintendo/wiiu/RetroArch_rpx.7z). I can confirm that the Classic Controller disconnection issue doesn't occur here, I can hotplug Wiimotes and Classic Controllers at runtime and change controllers on the fly.

I don't know whether this is the right place to be looking, but there have only been [eight commits to `wiiu_hid.c`](https://github.com/libretro/RetroArch/commits/master/input/drivers_hid/wiiu_hid.c) since the 1.8.9 stable, so those commits might be worth looking at.

**Comment by vaguerant** [comment]
Closing this now that #12676 has been merged, resolving the issue. Thanks, quarky!
