### ISSUE TITLE
"Set/Reset Core Association" options are broken.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#11244]
## Description

"Set/Reset Core Association" options don't work and can prevent you from launching games from playlists.

**edit:** ah, looks like it's because the `core_name` field stays empty (`"core_name": "",`) in the .lpl file.

When clicking "Set Core Association" the `core_name` is empty.
When clicking "Reset Core Association" it's set to "DETECT", but then if you click "Run" and select the core, `core_name` becomes empty.

I tried to replace `"core_name": "",` with `"core_name": "bleh",` and it worked :p So basically as long as it's empty it will not launch or crash. 

### Expected behavior

Be able to select/change core normally.

### Actual behavior

Shows "Core set:" (I mean literally just that) on the notification on Windows and Android, and you can't start game :/ Unless you have a default core selected for the playlist.
Segfault on Linux.

### Steps to reproduce the bug

1. Go to History tab and select a game.
2. Click "Set/Reset Core Association".
3. Try to start the game...

### Bisect Results

Started here it seems: 8a479e6006755d3dc8eee1931436cb4bb11afcde

### Version/Commit

- RetroArch: 1.9.0 / e67cdb3

### Environment information

- OS: Windows 10 / Linux Mint / Android

**Comment by bslenul** [comment]
For Linux segfault I compiled RA with `make DEBUG=1 GL_DEBUG=1 -j4` and ran it with gdb: https://pastebin.com/jSAJp1NV

I hope I did this correctly.

**Comment by jdgleaver** [comment]
@bslenul I really appreciate your efforts in reporting these bugs! It's incredibly helpful - there are so many little things we would miss otherwise :)

I just pushed a fix: #11246

...and yes, your gdb usage is fine :)

But if you want to generate stack traces like a pro, just compile like this:

```
make clean && make -j4 DEBUG=1 SANITIZER=address,undefined
```

...and then run as normal (no gdb)

**Comment by bslenul** [comment]
Hey, no problem, love the work you're all doing so I'm happy to help when I can :D 

Tried your fix on Linux, works like a charm! I'll test on Windows in a few minutes (crazy to me that RA builds much, MUCH faster on a VM than on MSYS2 :p But maybe that's normal...).

And thanks for the debug tip, I'll note it somewhere! 👍
