### ISSUE TITLE
Retroarch 1.9.0 missing features on iOS 13.6.1

### ISSUE THREAD

**Issue by hernan43** [libretro/RetroArch#11242]
## Description

On iOS 13.6.1, using Retroarch 1.9.0 some features have gone missing. Specifically cheats, rewind support, and the ability to take screenshots. If I downgrade to a 1.8.x release the features return. 

In the case of Rewind the setting for the feature no longer even appear in the frame throttle settings menu.

As another test, I built the latest version Retroarch in XCode and the features are not there either.

### Steps to reproduce the bug

 1. Open Retroarch 1.9.0 in iOS and play a game
 2. Bring up Retroarch quick menu
 3. See that the cheats options are gone
 4. Try and take a screenshot using the hotkey+defined screenshot button
 5.  No screenshot is taken
 6. Try and use rewind via the hotkey+defined rewind button
 7. No rewind

### Version/Commit
- RetroArch: 1.9.0 stable release (installed via Altstore.io)

### Environment information

- OS: iOS 13.6.1
- Compiler: Xcode

**Comment by trebrick** [comment]
@hernan43 also soft patching is broken for ios/tvos in 1.9.0.

**Comment by trebrick** [comment]
@hernan43 issues discussed towards the end of this post and all fixed! 

https://forums.libretro.com/t/ios-tvos-retroarch-1-9-0-and-other-emulators-download-cydia-repo/29817

**Comment by hernan43** [comment]
Yeah it looks like the change are detailed in this comment:

https://forums.libretro.com/t/ios-tvos-retroarch-1-9-0-and-other-emulators-download-cydia-repo/29817/32

**Comment by yoshisuga** [comment]
I made a PR awhile back to add back cheats and made a PR (#11271) to add
back screenshots, rewind and patching.

I created a new Xcode project to support Metal and some flags didn't get
brought over for some reason. This should be fixed in 1.9.1.
