### ISSUE TITLE
(cheevos) no badges in Achievement List with GLUI

### ISSUE THREAD

**Issue by 6lackmag3** [libretro/RetroArch#11261]
Hello. I've noticed that badges are not displayed in achievement list when using GLUI and there's no such option in Achievements settings. Is this supposed to be so?
Using Android nightlies.

**Comment by Jamiras** [comment]
Currently, badges are specifically limited to xmb and ozone. I don't know if there's a historical reason for this, or if it was just overlooked when adding GLUI. GLUI is older than ozone, so that seems unlikely.

**Comment by LibretroAdmin** [comment]
@Jamiras is this still an issue?

**Comment by Jamiras** [comment]
Yes, I can confirm that badges are not displayed in the GLUI achievements menu.

`rcheevos_menu_get_badge_texture` is only called from the xmb and ozone menu files:
```
menu/drivers/ozone.c:2168:      uintptr_t badge_texture = rcheevos_menu_get_badge_texture(index);
menu/drivers/xmb.c:3181:      uintptr_t badge_texture = rcheevos_menu_get_badge_texture(index);
```
