### ISSUE TITLE
Netplay cannot connect (different core reported)

### ISSUE THREAD

**Issue by mase76** [libretro/RetroArch#11263]
[Description]
I am not able to connect to Netplay, even on the same platform. Tested with Linux x86_64 and Android.

[Description of the bug]
I tried hosting a Netplay service on each system. The cores have been updated online on all systems. The roms are all the same. The Netplay server is visible in the list. A password is not set.

### Expected behavior
Netplay connects and I can play.

### Actual behavior
I am told, that the peer is using a different core, and it cannot connect.

### Steps to reproduce the bug

1. Update all cores with the online updater
2. Bring the same roms to all devices
3. Set an empty password on all systems
4. Start hosting a Netplay server (Linux or Android, the same behaviour)
5. Join the Netplay session either via the Server list or manually
6. When joining manually, I load the same rom with the same core.

### Version/Commit
- RetroArch: Release 1.9.0 compiled from git under Linux, Android Version from Retroarch F-Droid Repo

### Environment information

- OS: Debian Gnu / Linux Bullseye and Android LineageOS 16.0
- Compiler: GCC 10.2.0

**Comment by mase76** [comment]
Did further tests:
Linux to Linux - works
Linux to Android - does not work
Android to Linux - does not work
Android to Android - does not work

**Comment by PeeJayBonobo** [comment]
Can confirm that PC (Windows 10 Pro x64) to Android (10) and vice versa don't work either. Others have also reported on the libretro Discord that Windows to Windows doesn't work.

In addition, while using the nightlies on both PC and Android results in two warnings and three errors popping up on the client side:

1. WARNING: A netplay peer is using a different RetroArch version. If problems occur, use the same version.

Usually when I run those tests, I update both versions of RetroArch and their installed cores.
2. WARNING: A netplay peer is using a different version of the core. If problems occur, use the same version.
3. Content CRC32s differ. Cannot use different games.

As per common sense, I normally make sure that both parties are trying to connect with the exact same game down to the byte.
4. Incorrect Password

The host party did not have a password set for their lobby.
5. Netplay Disconnected
________________________________________________

Now, if I have 1.9.0 Stable installed on both devices, it functions, but client input isn't recognized by the host.

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway Closing this as it's so old.
