### ISSUE TITLE
Explore menu has a big stutter

### ISSUE THREAD

**Issue by nfp0** [libretro/RetroArch#11285]
## Description

When navigating the XMB menu (haven't tested the other menus), everything is smooth, except when we select the (new in version 1.9.0) "Explore" menu, where a big stutter is felt, before it goes back to normal.
This is only felt a single time after starting Retroarch. After going out of the "Explore" menu, going back is smooth.

### Expected behavior

Menu navigation keeps smooth across all main menu options in the crossbar.

### Actual behavior

Stutter when going into "Explore" menu for the first time after opening Retroarch.

### Steps to reproduce the bug

1. Open Retroarch on XMB menu 
2. Press right until you go into the "Explore" menu
3. Notice the stutter the moment the selection enters the "Explore" menu

### Bisect Results

Started happening on 1.9.0 only, as there was no "Explore" menu before.

### Version/Commit

- RetroArch: 1.9.0

### Environment information

- OS: Windows 10 x64

**Comment by i30817** [comment]
The explorer stuff should be done and cached on RA startup not the first time the tab is seen.

**Comment by nfp0** [comment]
@i30817 Agree. I believe the rest of the menu is cached at startup, as the whole experience is silky smooth in everything else, with the Explore menu being the only exception.

**Comment by i30817** [comment]
They can also start with it off in platforms where it's obviously going to be hefty.

**Comment by gouchi** [comment]
@nfp0 I can't reproduce the issue with latest version.

So you can close this issue.

Thank you.

**Comment by nfp0** [comment]
Sorry for the delay!
It is indeed fixed. Thanks for the heads-up!
Closing this.
