### ISSUE TITLE
Manually setting video driver per-core (PPSSPP)

### ISSUE THREAD

**Issue by ner00** [libretro/RetroArch#11327]
I am not sure if this is possible as of now, but I don't think so.

The reason why I'm asking for this is because in my current setup PPSSPP core has no image when running with gl video driver, it only works with glcore video driver. 

The thing is that I prefer using gl for every other core since it is less taxing on the hardware. For example, I play Flycast fine with gl, but not PPSSPP (only has sound). 

Can I set PPSSPP to be the only core switching the video driver to glcore? 

I suppose this could be handy for other cores aswell.

**Comment by hizzlekizzle** [comment]
This was solved on the forum via use of a core override: https://forums.libretro.com/t/manually-setting-video-driver-per-core-ppsspp/30108/6

As such, this ticket can be closed.
