### ISSUE TITLE
Trying to make the glcore driver force gles 3.0+ and the gl driver use opengl 2.0+ fails

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#11329]
### Description

Removing the noise (removal of x11, enabling of wayland, disabling opengl1 etc), i tried this:

`./configure --enable-opengl --enable-opengles3 && make`

Because i wanted to make a configuration where the 'gl' driver forced opengl and the 'glcore' forced opengles or vice-versa (i want one of them using gles to make the ppsspp core work, because it's only working with gles here, and i don't want a entirely different RA compile just for ppsspp).

This configuration fails with:
```
In file included from gfx/drivers/gl.c:59:
gfx/drivers/gl.c: In function ‘gl2_recreate_fbo’:
gfx/drivers/../common/gl_common.h:127:33: error: ‘GL_BGRA’ undeclared (first use in this function); did you mean ‘GL_RGBA’?
  127 | #define RARCH_GL_TEXTURE_TYPE32 GL_BGRA
      |                                 ^~~~~~~
gfx/drivers/gl.c:344:13: note: in expansion of macro ‘RARCH_GL_TEXTURE_TYPE32’
  344 |          0, RARCH_GL_TEXTURE_TYPE32,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
gfx/drivers/../common/gl_common.h:127:33: note: each undeclared identifier is reported only once for each function it appears in
  127 | #define RARCH_GL_TEXTURE_TYPE32 GL_BGRA
      |                                 ^~~~~~~
gfx/drivers/gl.c:344:13: note: in expansion of macro ‘RARCH_GL_TEXTURE_TYPE32’
  344 |          0, RARCH_GL_TEXTURE_TYPE32,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
gfx/drivers/gl.c: In function ‘gl2_wrap_type_to_enum’:
gfx/drivers/gl.c:735:17: error: ‘GL_CLAMP_TO_BORDER’ undeclared (first use in this function); did you mean ‘GL_CLAMP_TO_BORDER_NV’?
  735 |          return GL_CLAMP_TO_BORDER;
      |                 ^~~~~~~~~~~~~~~~~~
      |                 GL_CLAMP_TO_BORDER_NV
In file included from gfx/drivers/gl.c:59:
gfx/drivers/gl.c: In function ‘gl2_create_fbo_texture’:
gfx/drivers/../common/gl_common.h:127:33: error: ‘GL_BGRA’ undeclared (first use in this function); did you mean ‘GL_RGBA’?
  127 | #define RARCH_GL_TEXTURE_TYPE32 GL_BGRA
      |                                 ^~~~~~~
gfx/drivers/gl.c:871:13: note: in expansion of macro ‘RARCH_GL_TEXTURE_TYPE32’
  871 |             RARCH_GL_TEXTURE_TYPE32, RARCH_GL_FORMAT32, NULL);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
gfx/drivers/gl.c: In function ‘gl_load_texture_data’:
gfx/drivers/../common/gl_common.h:127:33: error: ‘GL_BGRA’ undeclared (first use in this function); did you mean ‘GL_RGBA’?
  127 | #define RARCH_GL_TEXTURE_TYPE32 GL_BGRA
      |                                 ^~~~~~~
gfx/drivers/gl.c:1704:43: note: in expansion of macro ‘RARCH_GL_TEXTURE_TYPE32’
 1704 |          (use_rgba || !rgb32) ? GL_RGBA : RARCH_GL_TEXTURE_TYPE32,
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~
gfx/drivers/gl.c: In function ‘gl2_pbo_async_readback’:
gfx/drivers/gl.c:2470:18: error: ‘GL_BGRA’ undeclared (first use in this function); did you mean ‘GL_RGBA’?
 2470 |    GLenum fmt  = GL_BGRA;
      |                  ^~~~~~~
      |                  GL_RGBA
In file included from gfx/drivers/gl.c:59:
gfx/drivers/gl.c: In function ‘gl2_set_texture_fmts’:
gfx/drivers/../common/gl_common.h:128:33: error: ‘GL_BGRA’ undeclared (first use in this function); did you mean ‘GL_RGBA’?
  128 | #define RARCH_GL_TEXTURE_TYPE16 GL_BGRA
      |                                 ^~~~~~~
gfx/drivers/gl.c:3328:23: note: in expansion of macro ‘RARCH_GL_TEXTURE_TYPE16’
 3328 |    gl->texture_type = RARCH_GL_TEXTURE_TYPE16;
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:206: obj-unix/release/gfx/drivers/gl.o] Error 1

```
There is no `#define GL_BGRA ???` in the codebase except for `libretro-common/include/glsym/switch/nx_gl.h` so i don't even know what i should do in this case.

When i tried the opposite, `./configure --enable-opengl --enable-opengles && make`, which was to try to setup 'gl' driver to use gles 2.0+ and 'gl_core' driver to use opengl 3.3+, the configure warned me that the opengl_core driver was disabled because i dared to enable opengles (2.0) instead of opengles3 so i didn't even try to build this config.

### Expected behavior

Just that it was possible to setup one of the gl drivers to force opengles instead of opengl and vice-versa for the other driver. Alternatively seperate the drivers into 4, though (though i doubt this will happen).

### Version/Commit
You can find this information under Information/System Information

- RetroArch: ef8f51dbbc6a29a10020202a1c3104706c621a0b

### Environment information

- OS: Linux AIVAS 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Compiler: gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Comment by i30817** [comment]
Ok, it appears GL_BGRA is defined in the GL headers.

My `/usr/include/GL/glext.h` does have it, but my `/usr/include/EGL/eglext.h` does not (configure says EGL is version 1.5). Might this be the problem?

**Comment by i30817** [comment]
Ok i think i figured out what's wrong here. Basically user error from ppsspp being built with by default this ifdef in `libretro/LibretroGLContext.h`

(btw the last fallback has a blackscreen in glcore driver, though it works in the gl driver here)
```
**#ifdef USING_GLES2
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGLES2)**
#elif defined(HAVE_OPENGL_CORE)
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGL_CORE, 3, 1)
#else
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGL)
#endif
```
instead of this:
```
#ifdef USING_GLES2
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGLES2)
**#elif defined(HAVE_OPENGL_CORE)
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGL_CORE, 3, 1)
**#else**
		: LibretroHWRenderContext(RETRO_HW_CONTEXT_OPENGL)
#endif**
```
So, ppsspp compiled straight off the b.sh with `./b.sh --libretro --release --no-package` attempts to use GLES even on a desktop. And I should use `HAVE_OPENGL_CORE=1; USING_GLES2=0; ./b.sh --libretro --release --no-package` or something.

**Comment by clort81** [comment]
I use retroarch configure/make and get this too
```
In file included from gfx/drivers/gl.c:60:
gfx/drivers/gl.c: In function ‘gl2_set_texture_fmts’:
gfx/drivers/../common/gl_common.h:129:33: error: ‘GL_BGRA’ undeclared (first use in this function); did you mean ‘GL_RGBA’?
  129 | #define RARCH_GL_TEXTURE_TYPE16 GL_BGRA
      |                                 ^~~~~~~
gfx/drivers/gl.c:3337:23: note: in expansion of macro ‘RARCH_GL_TEXTURE_TYPE16’
 3337 |    gl->texture_type = RARCH_GL_TEXTURE_TYPE16;
      |                       ^~~~~~~~~~~~~~~~~~~~~~~
```
I cannot find any configure options that avoid this error.

**Comment by i30817** [comment]
Try to build with the libretro makefile instead of the ppsspp cmake file.

Ie: go into the build_dir/libretro then

`make -j2 DEBUG=0 DYNAFLAGS="-DHAVE_OPENGL_CORE"`

If you want gles2 use -DUSING_GLES2 instead of -DHAVE_OPENGL_CORE.

**Comment by i30817** [comment]
I'm fact, i'm going to close this issue because it seems quite naive to me now. RA fallsback to any damn driver it wants at any time anyway, so trying to 'force' libretro_ppsspp.so to support both wouldn't even work even if it could, which i suspect it can't with how i ended up with a building .so (which i don't even use anymore because there is no point if i can't make it work on KMS - it gives no advantage over the buildbot).
