### ISSUE TITLE
within last week, xinput/dinput no longer working on windows

### ISSUE THREAD

**Issue by medievil1** [libretro/RetroArch#11330]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I updated nightly last night (9/11 for me) and xinput stopped working, no controller at all, tried dinput, still the same thing, no controller.. I was able to get sdl2 to configure(see's the xbox 360 controller) but of course sdl2 lacks rumble in RA

### Expected behavior

as before, controller is seen and auto mapped per the autoconfig

### Actual behavior

controller is not seen(or not listed)

### Steps to reproduce the bug

1. update RA nightly
2. plugin a xinput 360 controller

### Bisect Results

[Try to bisect and tell us when this started happening]
I've no setup to do this or I would

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
nightly 1.9.0 60b26bd490
### Environment information

- OS:Win 10 64b 20h2 build 19042.508
- Compiler: [In case you are running local builds]

**Comment by Ryunam** [comment]
I can't reproduce this. I'm on Windows 10 x64 2004, running the latest RA code updated 10 minutes ago (commit ba9ad10) and my Xbox One Elite 2 controller using xinput is working perfectly fine so far.
Perhaps it might be a driver issue. Or maybe something caused by a recent Windows update?

**Comment by medievil1** [comment]
dunno,  it was working fine, all the standalone emu's seem to work fine....let me update the nightly and see

**Comment by medievil1** [comment]
***UPDATE***
Resolved... dunno what installed it (maybe xpadder or x360ce) but something installed hidgaurdian and that had it blocked
