### ISSUE TITLE
[PS2] Aspect ratio setting doesn't work

### ISSUE THREAD

**Issue by floppyD** [libretro/RetroArch#11339]
It doesn't matter if you select 4:3, 8:7, core provided, etc. It will always output at 1:1.

Version: Nightly from 16/09/2020.

**Comment by notimp** [comment]
Same here. Also on stable builds. And the latest nightly.

If there ever was a version, where this worked, please inform us. Thank you.

**Comment by AKuHAK** [comment]
@floppyD aspect ratio should work in the latest version, I tested some settings, all works flawessly
