### ISSUE TITLE
Title does not register on playlist search

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#11359]
### Description

Not sure if you're interested @jdgleaver , but since you were the last to add a major feature here i thought of you (i didn't do a regression test).

The NDS has a title supposedly called `Theresia` but named as this on the rdb/no-intro:
```
game (
	name "Theresia.. (USA)"
	description "Theresia.. (USA)"
	region "USA"
	serial "YJAE"
	rom ( name "Theresia.. (USA).nds" size 67108864 crc 535C621C md5 F158AA2E808061A5334F87E98FAFB633 sha1 55C846E3EACEF50E89E54F226DA782D9875F1622 serial "YJAE" )
)
```
Note the two dots, which are the only reason i can think to when using 'Theresia' as search or even 'T' it doesn't appear. It *does* appear in the list produced by the manual scanner, so that's get the correct 'extension zone'.

I renamed it to be without the 'dots', moved to another playlist and back then searched again and bam working again.

### Expected behavior

Dots not at the start not to influence the ability to search. In fact forget it, since there is not correlation between what the playlist names a rom has and what it's named in the filesystem anymore, a dot at the start of the playlist name should not influence the search, or anything else.

There is in fact another bug here where if you 'rename' a game to '.' or something starting with '.' it will be removed from the playlist with prejudice probably because retroarch really wants hidden files not to appear anywhere.

### Actual behavior

Dots in any part of the name influencing the ability to search.

### Steps to reproduce the bug

1. Rename a playlist game to add 2 dots - I didn't test if 1 is enough - in any part of the name... except at the start of the name because there is another bug where the playlist hides those games and you have to go edit it manually...
2. Search for the part of the name that is not '.'; in my case 'Theresia'.
3. Find nothing changed like if it didn't exit.
4. Search for '.'
5. Find the rom.

### Bisect Results

Dunno, probably forever.

### Version/Commit

- RetroArch: 6234036d5d

### Environment information

- OS: Linux AIVAS 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Compiler: gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Comment by i30817** [comment]
Lol no, this is user error (except maybe the rename.

'The' is a very common word. I was simply not scrolling down enough.

**Comment by jdgleaver** [comment]
Glad you got the search issue sorted - that's a very easy mistake to make :)

Not sure about the `Z` key, though - search is normally mapped to the `/` key, and also to `s` when using the RetroPad bindings...

**Comment by i30817** [comment]
Yes, i'm using the retropad bindings and use S for search. Z works fine for the retropad (on the input selection) but appears as 'x1' if i start a search and press z. I think it's the onscreen keyboard that appears, but how z is getting replaced i have no clue except perhaps due to 'z' being 'cancel' in by configuration for the retropad menu bindings.

I tried it right now with a recent compile and it's now like I didn't press the 'z' (so it's being deleted)...

**Comment by i30817** [comment]
Actually it's not all keys that cause that 'zx'. Just x.

And guess what, i tab out and tabbed in and no 'z and x' is doing 'x1'. And if i move the focused onscreenkeyboard key i get 'x2'.

**Comment by jdgleaver** [comment]
Oh wow - that's incredibly strange...

I can't reproduce any of this on my Linux systems, but then I don't use wayland or KMS... :(

**Comment by i30817** [comment]
No big deal, i usually run RA in KMS anyway. Just a data point if someone comes complaining of the same next time.
