### ISSUE TITLE
NetPlay not working

### ISSUE THREAD

**Issue by KalebPlayz** [libretro/RetroArch#11367]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

NetPlay Not working

### Expected behavior

NetPlay Works

### Actual behavior

Player 2 Connects and disconnects after a few seconds

### Steps to reproduce the bug

1. Host NetPlay, i did it on Mario Party 2
2. Other person joins using same rom and core (Using Relay and no relay, no relay doesn't work at all, Relay worked once and then disconnected the other player) 

### Bisect Results

When i first tried to look into Netplay

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0

### Environment information

- OS: Windows 10 64 bit
- Compiler: [In case you are running local builds]

**Comment by mbroers** [comment]
+1 experiencing this as well

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway Closing this networking issue, seems long obsolete.
