### ISSUE TITLE
Settings with differing default states

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#11363]
In light of #11362 I decided to make a clean config and test which settings have "defaults" that differ from the new profile default state. This is with self-built (via the libretro-buildbot-recipe.sh script) on x86_64 Linux.

| Setting | Clean Default | Reset Default |
| :-- | :-- | :-- |
| Menu Driver | xmb | ozone |
| Recording Quality | Lossless | Medium |
| Streaming Quality | Low | Medium |
| UDP Stream Port | 56400 | 1 |
| Dynamic Background | Off | On |
| Animation Horizontal Icon Highlight | Easing Out Quad | Easing In Sine |
| Animation Move Up/Down | Easing Out Quad | Easing Out Expo |
| Animation Main Menu Opens/Closes | Easing Out Quad | Easing Out Circ |
| File Browser (Directory) | $HOME | \<Default\> |
| Video Filter (Directory) | /usr/lib/x86_64-linux-gnu/retroarch/filters/video/ | \<Default\> |
| Audio Filter (Directory) | /usr/lib/x86_64-linux-gnu/retroarch/filters/audio/ | \<Default\> |
| Recording Output (Directory) | \<Default\> | $XDG_CONFIG_HOME/retroarch/records |
| Recording Config (Directory) | \<Default\> | $XDG_CONFIG_HOME/retroarch/records_config |
| Cache (Directory) | /tmp | \<None\> |

I excluded the setting fixed by the above PR.

```
RetroArch: Frontend for libretro -- v1.9.0 -- b59c5f6ff9 --
Compiler: GCC (9.3.0) 64-bit Built: Sep 21 2020
```

**Comment by bslenul** [comment]
I checked the same settings on Windows (`:` being RetroArch folder, lines removed are exact same behavior mentioned by Sanaki above):

Setting | Clean Default | Reset Default
-- | -- | --
Menu Driver | ozone | ozone
File Browser (Directory) | \<Default\> | \<Default\>
Video Filter (Directory) | :\filters\video\ | :\filters\video\
Audio Filter (Directory) | :\filters\audio\ | :\filters\audio\
Recording Output (Directory) | \<Default\> | :\recording\
Recording Config (Directory) | \<Default\> | :\config\record\
Cache (Directory) | \<None\> | \<None\>

**Comment by Sanaki** [comment]
The directories may not have a good solution, not sure. I'm entirely unsure why Linux would default to xmb though, and the other settings seem like unintentional desyncs. Especially things like the UDP Stream Port.
