### ISSUE TITLE
Retropad Input configuration has a gotcha with the keyboard.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#11374]
##  Description

Some keys may be filtered and inoperative. I've only found this with enter, where i mapped enter to start in the main input retropad menu and then it never registered in games.

### Expected behavior

Either enter works as start or it is not allowed to be chosen.

### Actual behavior

Games without the start shortcut when using the keyboard.

### Steps to reproduce the bug

1. Use the keyboard to configure the input driver
2. map start to enter there
3. run one of the many games that say 'press start to enter' and try it. I tried it with both beetle and duckstation, on fear effect 2 and deception III, just to see if it wasn't a emulator problem. I also may have encountered it on dolphin or Eternal Darkness (start opens the menu, though there is another button that does for a limited feature only, enchanting).

**Comment by jdgleaver** [comment]
This one was a real devil to track down, but it turned out to be quite simple in the end :)

#11389 should fix it
