### ISSUE TITLE
Achievements don't save

### ISSUE THREAD

**Issue by Kryos1** [libretro/RetroArch#11384]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When I open a game the previous achievements that I have unlocked are locked

### Expected behavior

To see the previous achievements unlocked 

### Actual behavior

The previous achievements unlocked are locked

### Steps to reproduce the bug

Get an achievement in a game, restart retroarch, open the same game and go to achievement

### Bisect Results

The bug has always been there
### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0

### Environment information

- OS: Windows 10
Compiler: MinGW (9.2.0) 64-bit Aug 11 2020

**Comment by Jamiras** [comment]
Please confirm that you have "Start Active" disabled in the achievement settings:
![image](https://user-images.githubusercontent.com/32680403/94350644-7310fc80-000d-11eb-8eb5-d0828598a49b.png)

**Comment by Kryos1** [comment]
It was enabled indeed, thanks a lot !
