### ISSUE TITLE
Can I delete retroarch_debug.exe?

### ISSUE THREAD

**Issue by xmha97** [libretro/RetroArch#11410]
Hi,
Can I delete retroarch_debug.exe?

**Comment by hizzlekizzle** [comment]
Sure. You won't be able to do some troubleshooting, as it will no longer have debug symbols, but you could always re-download it in the future if needed.

**Comment by xmha97** [comment]
> 
> 
> Sure. You won't be able to do some troubleshooting, as it will no longer have to debug symbols, but you could always re-download it in the future if needed.

OK, Thanks.
