### ISSUE TITLE
(Windows) Russian translation issue

### ISSUE THREAD

**Issue by 6lackmag3** [libretro/RetroArch#11439]
Since 1.9.0 update Russian translation is totally messed up.
It's been reported on Discord and confirmed by me on [Crowdin](https://crowdin.com/project/retroarch/discussions/20/0/home).
I mostly use RetroArch for Android and there's no such issue.

**Comment by IlDucci** [comment]
It seems all language assets based in Crowdin have not been updated in over a month.

I think the assets should be updated from Crowdin before starting to find out possible issues.

@guoyunhe

**Comment by Psycho-A** [comment]
I can confirm Russian localization problem. It's totally broken now; all strings are mixed or shifted by positions. I just downloaded last Retroarch stable version yesterday.

**Comment by guoyunhe** [comment]
Android version is daily build from master branch, so it is newer than the Windows version. If Android version is okay, then it should have been fixed in master. Maybe you can ask @twinaphex to release a new version of RetroArch. Then your issue will be solved.

**Comment by teorex3** [comment]
![_002_RetroArch](https://user-images.githubusercontent.com/35883258/98034452-12ed5180-1e28-11eb-99d2-86c7c330cdf5.png)
![_004_RetroArch](https://user-images.githubusercontent.com/35883258/98034455-141e7e80-1e28-11eb-9f01-8e162a085b3c.png)
![_001_RetroArch](https://user-images.githubusercontent.com/35883258/98034457-14b71500-1e28-11eb-9a4b-3b03bde025c5.png)
Translation broke, wrong placement

**Comment by soredake** [comment]
Any progress on this?
