### ISSUE TITLE
[Feature Request] Always grab the mouse automatically when in fullscreen

### ISSUE THREAD

**Issue by masaklaw** [libretro/RetroArch#11443]
## Description

There is no reason for the mouse not to be grabbed when in fulscreen. Currently un-grabbed mouse does not work correctly under _Linux_ under any driver, however the effects are somewhat different for dirrerent drivers (see e.g. https://github.com/libretro/RetroArch/issues/10780 and its comments).

Grabbing the mouse seems to at least work for the `x` driver.

### Expected behavior

When RetroArch is in fullscreen, the mouse should always be grabbed.

### Actual behavior

The user has to press the `F11` every time to grab the mouse.

### Steps to reproduce the bug

For the un-grabbed mouse problems see: e.g. https://github.com/libretro/libretro-uae/issues/321 or https://github.com/libretro/RetroArch/issues/10780.

### Bisect Results

None.

### Version/Commit

    RetroArch: Frontend for libretro -- v1.8.5 Compiler: GCC (9.3.0) 64-bit

Tested additionally on:

    RetroArch: Frontend for libretro -- v1.9.0 -- 5e551dd92b --
    Compiler: GCC (9.3.0) 64-bit Built: Aug 10 2020

### Environment information

- OS: Linux

**Comment by sonninnos** [comment]
Is the situation same even if starting straight to fullscreen or only when toggling fullscreen?

Toggling seems to only show/hide mouse cursor, so that will be simple and desirable to change to grab instead (which also shows/hides).

**Comment by masaklaw** [comment]
In my case - I start in fullscreen and the mouse is not in the `grabbed` state by default.

Pressing `F11` then grabs the mouse and everything seems to work correctly after this.

I have not tested windowed mode and then toggling fullscreen thoroughly - but I just checked and it seems that toggling fullscreen doe not change the desired `grabbed` state.

Also - playing with windowed mode - there seems to be some difference beween the _desired_ grab state (controlled by `F11`) and the _current_ grab state, but I have not investigated this behaviour too deeply.

**Comment by sonninnos** [comment]
Could you please try updating RA to a more recent one, like 1.9.0 or nightly?

**Comment by masaklaw** [comment]
Tested additionally on:
```
RetroArch: Frontend for libretro -- v1.9.0 -- 5e551dd92b --
Compiler: GCC (9.3.0) 64-bit Built: Aug 10 2020
```
The mouse remains ungrabbed when starting RetroArch in fullscreen and the cursor behavior is the same.

A good way to reproduce it with PUAE core: move the real mouse to the lower right corner before starting RetroArch in fullscreen. The emulated mouse cursor should start in the upper left corner of the emulated screen and should laready be restrained in the right-down movement direction (since the real mouse cursor can not move any further to right or down at this point).

**Comment by bslenul** [comment]
I mentioned an issue on Linux with mouse grab yesterday on Discord, where the cursor always goes back to the center of the screen by itself in menus. I thought it was an issue with VMware but @sanaki and @negativeExponent on Discord both said it was acting like this for them too on a real Linux machine. And it's also happening in some games/cores! Like Yoshi's Safari with Snes9x if you use controller 2 as a light gun for example.

It's not really an issue with the PR itself, it was already happening before but you had to press F11 or enter the game focus mode first to trigger the bug, now it automatically grabs the mouse on startup so you'll noticed it right away and it can be really problematic.

**Comment by sonninnos** [comment]
Well that stinks since I can't reproduce it with any input driver on Windows..

The same thing happens with all drivers then?

**Comment by bslenul** [comment]
Yeah I don't have the issue on Windows either, seems to be exclusive to Linux for once :D 

On my VM it happens with x/sdl2/linuxraw input drivers, udev doesn't seem affected.

**Comment by sonninnos** [comment]
Ok, this should deal with that: https://github.com/libretro/RetroArch/pull/11496

**Comment by bslenul** [comment]
Yup, the cursor automatically re-centering itself is now fixed, thank you for that! 👍 

However, now #10780 seems to be back, like I said in one of my latest replies on the issue, if the cursor BEFORE launching the game isn't in the same position of the ingame cursor, the mouse is blocked by invisible "borders" (this is on Linux too, I'm unable to reproduce on Windows).

**Comment by sonninnos** [comment]
Well, due to multi-monitor reasons I had to remove automatic grabbing on fullscreen toggle and startup if using windowed fullscreen. Exclusive fullscreen will grab automatically.

**Comment by bslenul** [comment]
Yeah that's the thing, even in exclusive it seems to happen too.

Basically this is what's happening:

* Imagine 2 areas before launching the game, delimited by your cursor:

  ![image](https://user-images.githubusercontent.com/33353403/97365509-16bc2980-18a6-11eb-8665-11501945b273.png)

* When launching the game, these areas will be moved to match ingame cursor position, like this:

  ![image](https://user-images.githubusercontent.com/33353403/97365626-44a16e00-18a6-11eb-9027-251ee3892fc3.png)

* And then you can't get past the yellow area, your cursor will be blocked (represented here by the red area):

  ![image](https://user-images.githubusercontent.com/33353403/97365722-6c90d180-18a6-11eb-9ac9-f4d3dc67d776.png)

I hope this makes sense, I'm struggling to explain the issue properly, sorry :/

**Comment by sonninnos** [comment]
Sure it makes sense, but I can't seem to reproduce it at all. Not with windowed nor exclusive, not with grabbed nor ungrabbed.. Only testing PUAE though.
