### ISSUE TITLE
[macOS] Enable HAVE_COMMAND / HAVE_NETWORK_CMD

### ISSUE THREAD

**Issue by CGamesPlay** [libretro/RetroArch#11459]
## Description

These two compiler flags aren't enabled for this build configuration. I have done extensive searching of the internet and the commit history and I can't find any explanation why. Unfortunately, I can't seem to get the source code to build on my own system, so I can't actually submit a pull request, but there doesn't seem to be any glaring reason why this platform can't have these features enabled.

If it's not possible to enable this flag, at least this issue will serve as documentation that the feature does not work on macOS, because there doesn't seem to be any other documentation about that.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: master and 1.9.0

### Environment information

- OS: darwin

**Comment by bloodstrike** [comment]
Any word on this? 1.9.2 seems to behave the same way - regardless of the 'network command' settings in RA, network commands do not work on macOS due to the compiler flags not being correctly set. Would love to see this fixed.

**Comment by warmenhoven** [comment]
These flags are included now.
