### ISSUE TITLE
Playstation Classic USB Controller is not beeing detected in new releases of RetroArch - PlayStation_Classic_Controller.cfg is missing

### ISSUE THREAD

**Issue by spamsool** [libretro/RetroArch#11470]
## Description

RetroArch will not automaticaly detect Playstation Classic USB Controller in the latest release 1.9.0 (maybe in a previous as well).
It displayes the message: 'Controller 1356/3290 not configured'. It was working in the previous releases like 1.8.1 and instead displayed: 'Playstation Classic Controller configured in port #1' 

### Expected behavior

It should automaticaly detect Playstation Classic controller like in  previous versions and retroarch should display the following message: Playstation Classic Controller configured in port #1

### Actual behavior
Retroarch would not automaticaly detect the controller and it displays:  'Controller 1356/3290 not configured'

[What is actually happening]

Configuration file is missing in Retroarch 
PlayStation_Classic_Controller.cfg file should be present in the folder \autoconfig\dinput but it is not in the latest release.
When PlayStation_Classic_Controller.cfg copied to dinput directory - the controller is beeing automaticaly detected again.

### Steps to reproduce the bug

1. Connect PS Classic Controller to usb port
2. Run retroarch.exe

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0

### Environment information

- OS: Windows 10

**Comment by bslenul** [comment]
Update controller profiles via the online updater menu, it should be fixed since yesterday, the profile is now correctly in dinput folder as you can see: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/dinput/PlayStation_Classic_Controller.cfg

**Comment by spamsool** [comment]
Thank you very much for your help!. It is working now. Closing.
