### ISSUE TITLE
[PS VITA] BUG -  Retroarch keeps crashing c2-12828-1 after tried loading an NES game

### ISSUE THREAD

**Issue by madmax2** [libretro/RetroArch#11520]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch crashes on psvita with error code c2-12828-1, after trying to run an NES game
### Expected behavior 

Able to start retroarch

### Actual behavior

Retroarch keeps crashing with error c2-12828-1 on the PS Vita

### Steps to reproduce the bug

1. Load content > NES game on the Vita UX: drive
2. Retroarch will crash with error c2-12828-1, press OK to close
3. Try to start Retroarch again will cause the crash c2-12828-1

### Bisect Results

This started to happen after I tried to load an NES game.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.90 [stable]

### Environment information

- OS: PS Vita
- Compiler: [In case you are running local builds]

**Comment by AlexKidd29** [comment]
Same issue here on Nestopia UES

- PS Vita - Firmware 3.65
- RetroArch 1.9.0

- FCEUmm => Working
- QuickNES => Working
- Nestopia UES => Issue C2-12828-1 => error log available in attachment.

Thanks

[psp2core-1604912928-0x0000672923-nestopia_libretro.self.psp2dmp.zip](https://github.com/libretro/RetroArch/files/5509327/psp2core-1604912928-0x0000672923-nestopia_libretro.self.psp2dmp.zip)

**Comment by dlowhorn** [comment]
Exact same scenario here - as soon as I tried Nestopia UES RetroArch crashed and now refuses to start, showing the same error.

**Comment by dcmaradiaga** [comment]
In my case, I was trying to load a game with a different core. This led to RetroArch crashing and then subsequent starts would immediately crash. I think Retroarch was trying to auto-load the buggy core (in my case the GBA gpSP core) so I deleted the content history (not sure this helped) and renamed the `retroarch-salamander.cfg` file to `retroarch-salamander.cfg` (this latter part is what I think fixed it) and I was able to get back in to RetroArch.

**Comment by Saboton** [comment]
So comparing the retroarch.cfg that caused the crash to the default generated retroarch.cfg, the main difference is libretro_path being set to whatever core caused the crash (in this case app0:/nestopia_libretro.self). Changing that back to the default of app0:/2048_libretro.self and deleting content history let me back in without having to completely delete my retroarch.cfg.

**Comment by madmax2** [comment]
@Saboton is there any NES core/s on retroarch vita that does not cause this crash?

How do you delete content history?
