### ISSUE TITLE
Analog stick control of menu not working right for controllers not assigned device index 1

### ISSUE THREAD

**Issue by NilsBloodaxe** [libretro/RetroArch#11549]
## Description

When using more than one controller I can only navigate the menu with the analog stick on the controller assigned to device index 1.  Setting any other controller to port 1 allows for navigation of the menu with only the d-pad unless I manually rebind the left analog stick on that controller rather than use the autoconfig.  This is even true if the device index 1 controller and the other controller are the same controller with the same autoconfig.  I have no problems in-game using the analog sticks. 

I noticed this because I have a HOTAS connected to my computer and so when I connected one of my wireless XBox One controllers it was assigned to device 2 in Retroarch and the throttle for the HOTAS was device 1.  I put the Xbox controller as port 1 and couldn't use the stick for the menu.  I went into a N64 game and was able to use the stick, despite it not working in menu.  Rebinding the buttons manually (all of them) fixed the menu problem, so I saved my config file, but the created config file was put in the dinput folder with the name of the HOTAS throttle (so maybe another bug here).  Thinking this might be the problem, I disconnected the HOTAS system and deleted all my autoconfig files and redownloaded.  Using just the standard autoconfig file for the XBox One controller (connected wirelessly), it worked normally.

I decided to test further and connected 2 XBox One wireless controllers.  Using device 1, it worked normally.  Using device 2, it did not unless I rebound the stick.  Disconnecting both controllers and reconnecting in reverse order showed the same behavior, but switched, so it wasn't the controllers.  This was true even if I restarted RA, restarted my computer, or even when I uninstalled and reinstalled RA, whichever one of the two XBox controllers was hooked up first could control the menu with the analog stick out of the box, but the 2nd had to be rebound to work.

So then I tried with another controller, this a SN30 Pro connected via Bluetooth and again, the same behavior, regardless if I connected the SN30 Pro in dinput or xinput mode.  If it was the only device the analog stick worked, but if at least one of the Xbox controllers was hooked up it did not, unless rebound.  I could not test if it would work if it was device 1 and at least one Xbox controllers was connected as device 2, since connecting an Xbox controller pushes the SN30 Pro out of device 1.  That is, even if I connected the SN30 Pro first (and so was initially assigned device index 1), connecting Xbox controllers would change the device indices.  Connecting one Xbox controller would push the SN30 Pro to device 2 and the Xbox controller would be 1. 
 Connecting a second XBox controller would push the SN30 Pro to device 3 and the new Xbox controller to 2 (with the first remaining as 1).  As mentioned above, in this situation the SN30 Pro's analog stick would work in the menu when alone, but once the first Xbox controller was connected, the SN30 Pro's analog stick would stop working in the menu (unless rebound), while that Xbox controller's analog stick would work in the menu.  The 2nd Xbox controller's analog stick would also not work in menu, unless rebound, if all three were attached.

After writing all this up, I realized I never tested with the controllers using a wired connection.  With 2 Xbox One controllers, both connected via USB, I get the exact same behavior, only the analog stick on device 1 works normally.

One more little quirk associated with this.  For the controllers that are not device 1, rebinding just a single direction on the left stick will not allow any movement in the menu.  However, rebinding 2 (or more) directions on that stick will allow for movement in the rebound directions.  For example, rebinding Y-axis down does nothing by itself, but if you rebind X-axis right, then both down and right will work (but not up or left), this works with any combination of 2 or more rebound directions.

Sorry for the length, but I wanted to describe all the testing I had done on this issue.

### Expected behavior

Whatever controller I have set up in Port 1 should control the menu using either the analog stick or the d-pad to move.

### Actual behavior

Any controller other than Device Index 1 only the d-pad will work unless the analog stick is manually rebound.

### Steps to reproduce the bug

1. Connect two or more controllers
2. Set any controller to Port 1 other than the controller assigned device index 1
3. Try to navigate the menu with the analog stick
4. Manually bind the analog stick
5. It now works to move in the menu

### Bisect Results

I recently upgraded to 1.9.0 from 1.8.5.  I never noticed this on 1.8.5 (but I can't be certain).

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0 64-bit, Git version: 6388872a54

### Environment information

- OS: Windows 10
- Controllers used XBox One (wired and wirelessly connected via an XBox WIreless Adapter) and SN30 Pro (both dinput and xinput via BT used)

**Comment by NilsBloodaxe** [comment]
Using the latest nightly build for Lakka (1661013) on my Raspberry Pi 4 and two wired XBox One controllers produces the same issue, so it is not platform specific.  My Pi 3 that still has version 1.8.4 on it does not have this issue (with the now removed "All Users Control Menu" option off), the left analog stick on the controller set to Port 1 works as expected, regardless of device index.

**Comment by bslenul** [comment]
Bisected, first bad commit is 4bc39ee1cfa4e3b1b28ce79f70217aa21d308da3.

**Comment by NilsBloodaxe** [comment]
@bslenul Thanks for the bisect!

**Comment by Zkyo42** [comment]
I'd like to add that this issue still occurs in the most recent stable release (1.10.3 Windows x64). If I use quick menu>controls>Port 2/3/4/5 Controls and change the mapped of any of them to 1, I can control games fine, but the analog stick does not work in menus. All buttons and the D-Pad appear to work, so the menu is still fully usable, but it'd be nice to be able to use the analog stick too. This is with Settings>Input>Menu Controls>All Users Control Menu enabled.

**Comment by prmbittencourt** [comment]
This still happens on RetroArch 1.12.0 x64 on Arch Linux, with and without a core loaded. Analog input works fine in-game both with "Analog to Digital Type" set to "Left Analog" on platforms that have no analog input (Game Boy Advance and SNES) and to "None" on platforms that do support analog input (Nintendo 64, PSP). But the analog stick input is not recognized in the menu. Tested with a wired Xbox 360 controller and Nintendo Switch Pro Controller via Bluetooth.
