### ISSUE TITLE
Series X Dev Mode Icons not showing

### ISSUE THREAD

**Issue by fixx1983** [libretro/RetroArch#11555]
I installed latest Retroarch Xbox One build from the website us dependencies on my Series X running in dev mode, but XMB is not showing icons. I tried also to download and install assets, and they're here, in the right folder, but nothing. Tried to reboot, delete config, anything, but icons are always missing.

I also tried to switch menu driver to Ozone and icons are missing here too.

**Comment by gitaroobear** [comment]
It looks like changing the video driver to direct x12 works. Mine was set to x11 and it improved when I switched.

**Comment by Gamr13** [comment]
This issue can be closed.
