### ISSUE TITLE
Remote RetroPad network functionality is broken (since the addition of BearSSL it seems).

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#11557]
## Description

Using a phone as a controller doesn't work properly anymore, now basically RetroArch is froze until it receives an input, which will advance to 1 frame then it will freeze again until next input, etc.

### Expected behavior

It should act as a normal controller, with fluid movements and all.

### Actual behavior

Each input sent via Remote RetroPad will advance RetroArch and/or the content to a single frame.

### Steps to reproduce the bug

1. Start RetroArch on your PC.
2. Go to `Settings > Network` and enable "Network RetroPad" and "User 1 Network RetroPad".
3. Close RetroArch on your PC.
4. Start RetroArch on your phone and load Remote RetroPad core.
5. Go to `Quick Menu > Options`, enter the local IP of your PC, close and restart the core.
6. Start RetroArch on your PC again.
7. It should be frozen, send an input in Remote RetroPad from your phone and you should see RetroArch on PC moving by a single frame.

### Bisect Results

From the bisect, it seems to be happening since the addition of BearSSL: 18f46e65ea048f79ddecde76536ec78399f03984

### Version/Commit

- RetroArch: 1.9.0 / a80b40fb8a

### Environment information

- OS: Windows 10 / I couldn't get it to work at all on my Linux Mint VM, the port might be blocked or something I'm not sure, I'll check later.
**edit:** Well, no clue about Linux, can't get it to work at all, so no idea if it even worked before the "bad" commit or if it's something on my end, sorry!

**Comment by hizzlekizzle** [comment]
Oh, interesting.Well that certainly makes it easier to figure out what went wrong, now that we know *when* it went wrong!

**Comment by Alcaro** [comment]
oops, my bad. I hate that you have to set nonblocking behavior, not blocking - 'not nonblocking' is a double negation, easy to get confused.

https://github.com/libretro/RetroArch/pull/11583

**Comment by bslenul** [comment]
Just to confirm (if needed :p) that it works fine with that PR! Thank you! 👍
