### ISSUE TITLE
[VITA] Menu scale is too small by default

### ISSUE THREAD

**Issue by Jaffacakelover** [libretro/RetroArch#11587]
On PS Vita, the Ozone menus are too small on the 5" screen. Menu items are hard to read, and the subtext descriptions are miniscule!

![2020-11-17-202315](https://user-images.githubusercontent.com/3490850/99452236-354c9800-291b-11eb-8231-aa52d8121073.jpg)

I know that you can change the menu scale factor in appearance settings, but for new users and fresh installs, I feel it would be better for the Vita's default config to set the scale around `x1.60`.

![2020-11-17-212810](https://user-images.githubusercontent.com/3490850/99452974-27e3dd80-291c-11eb-9ff5-7a91ce03dd70.jpg)

Also, can menu factor be set per driver in configs? For example, `x1.60` is a good scale for Ozone, but too much for XMB (which would be better set around `x1.20`).

**Comment by Ted-bissada** [comment]
https://github.com/libretro/RetroArch/pull/11510
