### ISSUE TITLE
Buildbot server down!

### ISSUE THREAD

**Issue by Destroyer5150** [libretro/RetroArch#11598]
Been down since yesterday
Error 521
Ray ID: 5f4f8e3c5c0ae7f5 •
2020-11-20 04:51:24 UTC
Web server is down
You
Browser Working
Los Angeles
Cloudflare Working
buildbot.libretro.com
Host Error
What happened?
The web server is not returning a connection. As a result, the web page is not displaying.

What can I do?
If you are a visitor of this website:
Please try again in a few minutes.

If you are the owner of this website:
Contact your hosting provider letting them know your web server is not responding. Additional troubleshooting information.

Cloudflare Ray ID: 5f4f8e3c5c0ae7f5
Your IP: ***.***.***.***
Performance & security by Cloudflare

**Comment by bslenul** [comment]
https://www.libretro.com/index.php/buildserver-migration-buildbot-server-offline-for-two-day-maintenance-period-starting-11182010/
