### ISSUE TITLE
[Feature Request] Separate X/Y Overlay Scaling Options

### ISSUE THREAD

**Issue by raptir** [libretro/RetroArch#11592]
This is most relevant on Android but could apply to other platforms. With phones having seemingly arbitrary aspect ratios these days, one frustration has been that onscreen overlays end up stretched on modern phones with an aspect ratio wider than 16:9.

I noted that there is already an option to scale overlay elements generally. If this could be split into allowing a discrete X and Y scaling value it would allow us to use the "standard" 16:9 overlays on any aspect ratio device.

**Comment by hizzlekizzle** [comment]
The nightly builds have significantly improved handling of overlay scaling. If you've only tried 1.9.0, try a nightly build and see if it fills your needs.

**Comment by raptir** [comment]
Thanks! I see the buildbot is under maintenance so I will take a look when it's up again and close the issue if this resolves it.

**Comment by raptir** [comment]
It appears this was already implemented in the nightlies!
