### ISSUE TITLE
[Feature request] Allow recording with "copy" codecs for video/audio

### ISSUE THREAD

**Issue by iax2RqPZbq** [libretro/RetroArch#11603]
When specifying "copy" as the codec for video/audio, I get a segfault. Would be nice to have retroarch supply "lossless" video/audio in the format it renders it, instead of needing an additional encoding step.

**Comment by hizzlekizzle** [comment]
I don't think I understand the point.

**Comment by iax2RqPZbq** [comment]
I think I explained poorly... Basically I wanted to know if we can get a "raw" dump from retroarch's recording. Instead of having to pass it through a codec.

If you have a video file, you can use ffmpeg's `-vcodec copy` flag to simply copy the video data, without encoding it again. I want to know if we can do the same within retroarch; specifying `vcodec = copy` in the recording configuration file gives a segfault.

**Comment by hizzlekizzle** [comment]
Ah, I see. So, you have to use a codec of some sort, even if it's something very basic, like mjpeg. That is, there's nothing to "copy".

If you're just wanting lossless encoding, that's already supported, and the h.264 variation that it uses was added to ffmpeg by a former RetroArch developer specifically for this purpose.

**Comment by iax2RqPZbq** [comment]
Thanks @hizzlekizzle. With `video_preset = ultrafast` CPU overhead is low enough; retroarch sets `vcodec = libx264rgb` and `qp = 0` automatically if you omit `vcodec`.
