### ISSUE TITLE
playstation vita nightly builds broken on buildbot

### ISSUE THREAD

**Issue by yamspy** [libretro/RetroArch#11620]
the playstation vita nightly builds are broken and come out at 7 mb while the last "correct" vpk on the buildbot was built on 2020-11-14 and is 252.8mb

**Comment by foxp4v** [comment]
PS Vita Builds have several cores that crashes the program, Stella, Stella2014, FBA2012, Picodrive, also on 1.9.0 stable version.

**Comment by yamspy** [comment]
fixed by 2020-12-27, the bubble name is wrong but the cores are there, closing
