### ISSUE TITLE
(UWP) Feature request. Ability to manually clear temporary gamefiles from within Retroarch.

### ISSUE THREAD

**Issue by Ploggy** [libretro/RetroArch#11626]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Would it be possible to add the ability to manually clear files in a cache folder (cache path set in Retroarch Directory settings) with an option within Retroarch.. Such as a "Clear cached content" option?

### Expected behavior

Create a folder called Cache in the RA directory
Open RetroArch, goto Settings 
Select option Clear cached content from cache folder
Whatever content was in the cache folder will be deleted

### Actual behavior

There is no option to manually clear cached content. 

-----
I believe Retroarch does clear cached files when you close content. but it doesn't seem to delete those files if a Core crashes or Game fails to boot (on UWP RA anyway)

**Comment by i30817** [comment]
Retroarch main 'cache trash' is caused by extracting large compressed files into /tmp and retroarch doesn't have a dedicated cache directory.

In fact, the best way to avoid this is... not to use compression with retroarch, or at least use system level compression where the very very bad implementation of 'compression support' retroarch gives (extracting everything to /tmp) doesn't butt in.

**Comment by Ploggy** [comment]
I should have been more clear.. When I say "UWP" I meant the Xbox One UWP port. On Xbox, installed apps in dev mode have a 2GB limit. So any Games that pass that limit fail to load. 
We also don't have access to the Retroarch install directory by default (unless we pay for a specific 3rd party Xbox file manager app from the Xbox store that can access the Retroarch install directory. 

On xbox, if a Core crashes or a Game (large compressed file/iso) closes without using the close content option it gets left in the Retroarch install directory, if this happens a few times (especially with larger Games) the 2GB limit gets ate up pretty quickly.

This is why I was hoping it would be possible to add an option in Retroarch itself to clear a cache folder (once a path is set in Retroarch's directory settings)

**Comment by i30817** [comment]
Wow that sucks. You definitely are right to ask for a xbox setting to remove any iso file uncompressed in that case. And maybe investigate a way that ridiculous limit can be shortcircuited.

**Comment by Ploggy** [comment]
Our Games are originally selected from an external usb drive but due to another Xbox UWP limitation when the Game is loaded its transferred to the Retroarch install folder then booted from there. 

In short bigger Games (iso's) NEED to be booted from inside the Retroarch install directory for them to work on Xbox.

**Comment by tunip3** [comment]
This is now done automatically so this issue can be closed
