### ISSUE TITLE
[Feature] Deleteding saves and games in retroarch

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/RetroArch#11634]
Is there a way to delete saves and games in retroarch? If not could it be added?

**Comment by hizzlekizzle** [comment]
We have historically avoided deleting things from inside of RetroArch because it's a dangerous thing to give users access to. That is, we already get people complaining that RetroArch deleted $whatever, and that would only get worse if it were actually possible.

**Comment by Cibomatto2002** [comment]
I can see how that could be a problem. what gave me the idea to ask for that feature was windows in windows you can just go to the retroarch directory and delete whatever you want.

**Comment by Nitrousoxide** [comment]
> Is there a way to delete saves and games in retroarch? If not could it be added?

Just to give you a workaround, loading up an empty save slot and then saving over the ones you want to clear should do it.

**Comment by Cibomatto2002** [comment]
Ok thank you do I need to close this?

**Comment by Nitrousoxide** [comment]
it's already closed so you should be fine
