### ISSUE TITLE
Wii U RPX Retroarch Broken Online Updater

### ISSUE THREAD

**Issue by AshleyPikachu** [libretro/RetroArch#11638]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

### Description
This is multiple interrelated bugs that have to do with the frontend of Retroarch on a Wii u.

1.When using the online updater Assets.zip refuses to unzip once downloaded on Wii U. It does indeed download but refuses to unzip.

2. Since the online updater for the front end does not work, one currently needs to download bundle.zip, cheats.zip and all boxart they want themselves. After the download they must be Unzipped on a computer and installed manually.

3. After creating all the missing folders some directories on Wii u need to be set so it can find them.
Dynamicbackgrounds
sd:/retroarch/assets/wallpapers

Thumbnails
sd:/retroarch/thumbnails

Cheat File
sd:/retroarch/cheats

Video Filter
sd:/retroarch/filters/video

Audio Filter
sd:/retroarch/filters/audio

Video Shader
sd:/retroarch/shaders

Overlay
sd:/retroarch/overlays

Screenshot
sd:/retroarch/screenshots

### Expected behavior

The online updater updating and installing retroarch's needed frontend contents. So that the user can all functions properly.
### Actual behavior

Assets.zip is never extracted and any content besides cores will not update itself with in the Retroarch app on Wii u.
This means cheats, playlist, any graphical assets and boxart will not function without a manual install.

### Steps to reproduce the bug

1. Install Retroarch on Wii u.
2. Run the Online updater.
3. Nothing will update after the download is finished and a assets.zip can be found on the SD card.

### Bisect Results

This bug is very old and has at least been going on since 1.7.9, it has is currently 1.9.0

### Version/Commit
You can find this information under Information/System Information

Retroarch Wii u RPX 1.9.0 Stable

### Environment information

Wii u

**Comment by EustaceCS** [comment]
'Wii U > Haxchi > RetroArch installed through WUP' user here.
Never had such problems with my setup - even box arts did loaded properly (albeit really, really slowly even for small quantities of titles at once).

Can't recall exact RetroArch version (the console is still somewhere around the house, will have to look for it). But it totally wasn't 1.9.0 .

I know it sounds stupid but are you completely sure that:
- there're enough free space on your SD card?
- the install method (for both RetroArch and... ahem... homebrew bridge application) you used didn't messed up anything app permission related?

**Comment by MrScottyTay** [comment]
Clicking download thumbnails doesn't even start a scan, nothing happens.
