### ISSUE TITLE
Adding finnish translation

### ISSUE THREAD

**Issue by styxnix** [libretro/RetroArch#11632]
Hi!
First time on Github, so sorry if doing this wrong.

We have been working on RetroArch Finnish translation for some time now and it's about 45% ready, and we could start testing this translation on RetroArch, but the translation needs to be added to it.

Can you guys (@guoyunhe ?) add it or is our job to add it?

Thanks

**Comment by styxnix** [comment]
- https://github.com/libretro/RetroArch/blob/a3da521083d5b3714b79cdb15e2af5d3de468fab/msg_hash.c#L37
- https://github.com/libretro/RetroArch/blob/a3da521083d5b3714b79cdb15e2af5d3de468fab/msg_hash.c#L114
- https://github.com/libretro/RetroArch/blob/a3da521083d5b3714b79cdb15e2af5d3de468fab/msg_hash.c#L174
- https://github.com/libretro/RetroArch/blob/c3e9593022b2d37b0b0f8dd6ae2582938721247a/libretro-common/include/libretro.h#L259
- https://github.com/libretro/RetroArch/blob/8921d3124774a9d2ba04936cfede6f54e7b12f8a/frontend/drivers/platform_win32.c#L118

**Comment by guoyunhe** [comment]
Hello, if you have some C knowledge, you can make a PR by yourself. Here is an example I did before #10787

I used to live in Finland :smile: but just moved to China. My access to the "internet" is so limited. Even with VPN, I can barely open any foreign websites, including my web email... So I am not very active on GitHub anymore.
