### ISSUE TITLE
Wii U Save Slot Console Hardlock

### ISSUE THREAD

**Issue by AshleyPikachu** [libretro/RetroArch#11637]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Entering the Save Slot list and leaving or pushing any button besides movement crashes the Wii u.

Pressing the home button can get someone out of it but reopening the Retroarch menu after will then crash the console anyways. 

Pushing left and right to change slots outside the menu does not crash it.

### Expected behavior

Entering the save slot menu should not crash upon any setting changes.

### Actual behavior

The Wii u console will freeze if one pushes any buttons inside the save slot area besides movement.

### Steps to reproduce the bug

1. Load any game
2. Push the home button, go to Save Slot
3. Push A to pick a Save slot or just try to leave the Save slot page and the Wii U will crash.

### Bisect Results

This has been tested on NES and SNES. The core does not appear to matter, FCE, SNES9x Current and Nestopia UE were all tested with the same results.

### Version/Commit
This is on Retroarch 1.9.0 Stable.

### Environment information

Wii U 1.9.0 Stable Release

**Comment by LibretroAdmin** [comment]
I'm going to assume this issue has been fixed by now.
