### ISSUE TITLE
(Windows 10) Retroarch crashes to menu after starting netplay by itself.

### ISSUE THREAD

**Issue by oraichu** [libretro/RetroArch#11641]
## Description

Retroarch either crashes or freezes randomly during gameplay, seems to start netplay by itself. I have made sure there are no netplay shortcuts. 

### Expected behavior

Just playing.

### Actual behavior

1) Random freeze, it seemingly starts netplay by itself and says "joined as player 1" and other messages popping up all of a sudden, as the emulation starts going really slow, before eventually freezing. Have to reboot the program to solve this.
2) Random crash that initially freeze the emulation, then boots you back to main menu, having unloaded the game + core. A message pops up right away saying the controller (Xbox One via dongle) has connected. 

### Steps to reproduce the bug

Unsure. But as mentioned, I think this is related to the Xbox One Controller, and the dongle connection. Possibly also how other programs interfere with it.

### Bisect Results

This originally started happening about a month ago, essentially when I started using Retroarch more. First happened on Beetle PSX HW, and later with Citra Canary. Now I have been able to reproduce it on several cores. Seems to strike at random. I could play 2 hours before it happens, or just 10min. I read online people mentioning Explore.exe or Steam interfering with the controller, and have made sure to close Steam before playing - which didn't fix it. 

### Version/Commit
Retroarch 1.9.0
Windows 10 Pro
All latests updates of windows and cores.

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway Given how long ago this was, I will just close this one, but just pinging you regardless in case there is anything of merit to be worth reading here.

**Comment by NovaCyntax** [comment]
I've run into the same issue as above. Playing a game, it crashes, and it sends you back to menu stating that netplay is being hosted. Upon relaunching the game, the video statistics regarding frame rate and performance have also been automatically enabled. I'm running RetroArch on Windows 10 and also using a Dualshock 4 as an XBOX 360 controller via Windows Bluetooth connection. Unsure if this relates to a specific core or not, for me it's on snes9x current.

**Comment by oraichu** [comment]
The problem turned out to be Caffeine (https://www.zhornsoftware.co.uk/caffeine/), a mini software to keep the machine awake and screen on. Reading up on it, it generates a F15 keystroke input randomly, so I guess the key input interfered with the controller input and made the thing crash. After removing this software, I haven't had this problem anymore. 

I now just use the Microsoft PowerToys to achieve the same thing.
