### ISSUE TITLE
[Feature] Support PlayStation Classic USB controllers

### ISSUE THREAD

**Issue by aybe** [libretro/RetroArch#11658]
## Description

The PS1 classic controllers can be plugged on PCs and work rather well.

But Retroarch doesn't know about them, you have to remap everything:

<img width="509" alt="retroarch_2020-12-04_00-42-24" src="https://user-images.githubusercontent.com/1537591/101103621-989c2280-35c9-11eb-8895-77a129287fd0.png">

XB1 controller is well-known however:

<img width="509" alt="retroarch_2020-12-04_00-41-57" src="https://user-images.githubusercontent.com/1537591/101103538-87531600-35c9-11eb-9b75-5984f88452d5.png">

Is this what RetroArch looks for identifying a particular controller ?

<img width="300" alt="mmc_2020-12-04_00-40-07" src="https://user-images.githubusercontent.com/1537591/101102799-51ae2d00-35c9-11eb-87db-ed1555e98a28.png">

**Comment by aybe** [comment]
FWIW this is the config for the device:

```
input_driver = "xinput"
input_device = "Controller (Xbox One For Windows)"
input_vendor_id = "1118"
input_product_id = "767"
input_b_btn = "2"
input_y_btn = "3"
input_select_btn = "8"
input_start_btn = "9"
input_up_axis = "-1"
input_down_axis = "+1"
input_left_axis = "-0"
input_right_axis = "+0"
input_a_btn = "1"
input_x_btn = "0"
input_l_btn = "6"
input_r_btn = "7"
input_l2_btn = "4"
input_r2_btn = "5"
```

<img width="510" alt="retroarch_2020-12-04_01-03-22" src="https://user-images.githubusercontent.com/1537591/101104927-88397700-35cc-11eb-8b63-0ae466f5f097.png">

Oddly enough, it's saved in `RetroArch\autoconfig\xinput\Controller (Xbox One For Windows).cfg` but indeed it's the right config.

Note, I do have a XB1 pad as well.

And even though RetroArch complains about it configured, it does work:

<img width="510" alt="retroarch_2020-12-04_01-02-46" src="https://user-images.githubusercontent.com/1537591/101104886-70fa8980-35cc-11eb-91f1-efaec105cf16.png">

**Comment by bslenul** [comment]
Main Menu > Online Updater > Update Controller Profiles, there's already an existing profile for the PSC controller, it should work fine after updating ;)

**Comment by aybe** [comment]
Amazing, thank you !
