### ISSUE TITLE
RetroArch keeps erasing RetroAchievements password at random

### ISSUE THREAD

**Issue by EustaceCS** [libretro/RetroArch#11664]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

Yessir.

## Description

RetroArch keeps kicking me out of RetroAchievements account at random

### Expected behavior

Entered the password once - good to go for as long as you don't change the password at RetroAchievements side.

### Actual behavior

Entered the password once - it erases itself after a number of game launches.
Literally.

### Steps to reproduce the bug

I run RetroArch, I check Settings > Achievements - password is present.
I load the core (any), I run the game (any) - with uncertain chance, the password disappears, throwing a notification about impossibility to login to RetroAchievements.
A number of tries over a day or two can be necessary.

### Bisect Results

No idea. I'm suffering from it for quite a while (a year or so) - it wasn't as irritating earlier since I didn't used RetroArch as often (once a month).

Right now, once a day, it became a problem.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.x, 1.8.x, 1.9.0 .

### Environment information

- OS: Win10 x64
- Compiler: -- using 'retail' version, not self-assembled.

I don't mind running debug version with logging enabled for awhile - just tell me if usual logs (which are enable'able through RetroArch's options) would suffice (or how I may provide needed intel otherwise).

**Comment by jared6502** [comment]
I'm having an issue with RetroArch losing the RetroAchievements login as well on 1.9.4. I'm not quite sure if it's the same issue or not.

**Comment by SentaiBrad** [comment]
I have this issue as well. The Password is there in every scenario, but when I go to load games, most of the time it will not log in. 

I used to be able to open the RA menu, input the password again (even though it is still there), save core override, close RA down, launch the game and it would be good. This used to make things good for that entire core. Changing games was no issue.

Recently, I now have to do the above method per game, and I am not saving per game overrides either. This happens on any core, with any game that has Retro Achievements for me.

**Comment by LibretroAdmin** [comment]
@Jamiras can this issue be closed?

**Comment by Jamiras** [comment]
I assume so. Every case where I've debugged this issue it's been because of a setting stored in one of the override files. #12960 addresses that _for new override files_. Existing override files will still exhibit the behavior as the override contains the interfering value.
