### ISSUE TITLE
3DS - Date and Time settings stuck at default HH:MM

### ISSUE THREAD

**Issue by Syko7956** [libretro/RetroArch#11668]
# Description

Style of Date and Time is forced HH:MM no matter what preference you select
Date Separator also doesn't work
### Expected behavior

MM-DD-YYYY HH:MM (AM/PM) displaying 12/6/2020 1:25PM

### Actual behavior

MM-DD-YYYY HH:MM (AM/PM) displaying 13:25

### Steps to reproduce the bug

Settings\User Interface\Menu Item Visibility\Style of Date and Time = MM-DD-YYYY HH:MM (AM/PM)

### Bisect Results

- RetroArch: 1.9.0 December 3rd 2020 nightly build

### Environment information

- Compiler: GCC (7.1.0) 32-bit

**Comment by MrHuu** [comment]
When using ```RGUI``` as menu driver, date won't display.
Date with separator is shown correct on other menu drivers.

Doesn't seem to be specific to the 3DS platform.

**Comment by Syko7956** [comment]
Oh, that's intended? Never knew. I only play Retroarch on 3DS. Kinda wish it didn't show up on rgui. Bit misleading

**Comment by mpalomas** [comment]
I'm not a contributor, but I believe it's intended: rgui has a default time mode of HH:MM.
Using rgui, at the very bottom, you have the date to the right, but there is also the tooltip for the selected item taking quite a lot of room. If it's too long it can scroll smartly. 
A too long date format would take too much space leading to tooltips always scrolling and being hard to read, I guess, from a UX perspective.

**Comment by Syko7956** [comment]
That makes sense
