### ISSUE TITLE
UWP cert link goes to 404 page

### ISSUE THREAD

**Issue by d0x360** [libretro/RetroArch#11662]
UWP cert link goes to 404 page so Retroarch cant be installed

**Comment by Bitcion** [comment]
me too

**Comment by hizzlekizzle** [comment]
Try this one: https://cdn.discordapp.com/attachments/434713532341288961/786575596796117033/RetroArch-msvc2017-UWP_1.9.0.0_x64_ReleaseANGLE.cer

**Comment by d0x360** [comment]
Thanks, I appreciate it

**Comment by kaosushijin** [comment]
This workaround is no longer effective.  The certificate linked has an expiration of 12/22/2020.

**Comment by johnfried** [comment]
Whats the solution now? Hoping to run Retroarch on Windows 10x with UWP

**Comment by Cristian2737** [comment]
still getting a 404 error
