### ISSUE TITLE
(qt) simple shader issues

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#11672]
Loading a shader from the qt panel and selecting "save as core preset" with "simple shader" enabled makes a preset with a wrong path. (same issue with save as game/path/global)

I get:
```
#reference "../../../../../E:/Emulateurs/RetroArch64/shaders/03-crt-guest_ntsc-color.slangp"
```
while in RA shader menu it's right:
```
#reference "../../shaders/03-crt-guest_ntsc-color.slangp"
```

Another issue when using N/M hotkeys to reach a shader preset in your shader directory, then using "save as" to overwrite it will cause an auto-reference of itself killing the preset.

@HyperspaceMadness

**Comment by HyperspaceMadness** [comment]
Thanks for posting this, I'll be looking into this very soon
