### ISSUE TITLE
Unused QT plugins cleanup

### ISSUE THREAD

**Issue by Psycho-A** [libretro/RetroArch#11698]
I found that Qt plugins like "bearer", "iconengines", "imageformats", "styles", "platforms" and "Qt5Svg.dll" are totally unused by RetroArch and are succesfully removable. I suggest to remove these files from releases to prevent bloating distributive that is already bloated enough (also I can't see the reason to carry 160 mb retroarch_debug.exe in stable public releases).

**Comment by LibretroAdmin** [comment]
OK, this has been implemented for nightlies now, and it should be ready for the next stable now.

The only file that remains is platforms/qwindows.dll. since without that file, the Qt interface won't start up anymore.
