### ISSUE TITLE
XMB UI goes very laggy on large playlists

### ISSUE THREAD

**Issue by Psycho-A** [libretro/RetroArch#11696]
I'm using latest 32-bit RetroArch and 64-bit Windows 7, and when I'm choosing XMB driver instead of Ozone on my configured settings and playlists, it's really laggy. CPU loads over 90%, framerate goes low, and if I'm spend many time in XMB menus, resource load gets even higher, and animations turns to "slideshow"...

**Comment by mpalomas** [comment]
Out of curiosity, how large is large ? Which system ?
I see no lag at all with average-size playlists (~500 to 900 items) with XMB, on Windows 10.

**Comment by Psycho-A** [comment]
I use NES/SNES/SMS/SMD playlists from No-Intro roms set which has from 400 to 4000 items. Even adding one of that playlists makes XMB UI slower and slower just during a couple of minutes of work, even if we don't go into playlists themselves or just do nothing.
