### ISSUE TITLE
[Bug] Russian is broken...

### ISSUE THREAD

**Issue by PavelDurov1488** [libretro/RetroArch#11711]
Oh no...
![image](https://user-images.githubusercontent.com/74456272/102507719-8a68fe80-40bf-11eb-8017-92807b227d24.png)
![image](https://user-images.githubusercontent.com/74456272/102507824-a66ca000-40bf-11eb-95bd-d82074b0e8d3.png)

**Comment by gouchi** [comment]
Hi,

If it is a translation issue, please check this [readme](https://github.com/libretro/RetroArch/tree/master/intl#for-translators).

Thank you.

**Comment by PavelDurov1488** [comment]
In night builds there is no changes. Maybe some russian guy with ra compilator can check whats wrong
Or maybe manually generate files with Crowdin. Now russian is unusable

**Comment by 6lackmag3** [comment]
@PavelDurov1488 of course, since latest nightly's been build 2020-11-18. Have patience and wait for update.

**Comment by PavelDurov1488** [comment]
![image](https://user-images.githubusercontent.com/74456272/102678711-1fb1e300-41e5-11eb-8792-ab2e26d640b2.png)

**Comment by 6lackmag3** [comment]
@PavelDurov1488 what're you trying to say by posting this? You wont see changes until newer builds appear on buildbot.

**Comment by PavelDurov1488** [comment]
I dont know how it works, but it seems like your changes was accepted in Dec 16...
Oh...
![image](https://user-images.githubusercontent.com/74456272/102700984-55120b80-428d-11eb-928b-fd4acc343829.png)

2020-11-18 its November

Okay....

**Comment by gouchi** [comment]
The time the new infra for CI/CD is ready, please make a test with this [build](https://github.com/hizzlekizzle/RetroArch-AppImage/releases/tag/Nightlies).

Thank you.

**Comment by PavelDurov1488** [comment]
Not better
![image](https://user-images.githubusercontent.com/74456272/102783313-b04f1580-43d5-11eb-87a5-0e9d7255540c.png)

Maybe codepage is broken

Actually, as I know, it's not after this commit https://github.com/libretro/RetroArch/commit/8da2563b87f30390071454584d5fd6c202dec58b

Some guy from forum said that modern retroarch has ???? eveywhere too

there is some notification
![image](https://user-images.githubusercontent.com/74456272/102783633-30757b00-43d6-11eb-90ed-9d85bfc367b7.png)

**Comment by PavelDurov1488** [comment]
In normal behaviour it uses freetype font rendering
![image](https://user-images.githubusercontent.com/74456272/102783983-b42f6780-43d6-11eb-8655-106bfcc1656f.png)
With your build it uses stb font rendering...
![image](https://user-images.githubusercontent.com/74456272/102784111-dfb25200-43d6-11eb-9bc5-7a2ec53b223b.png)

**Comment by gouchi** [comment]
Unfortunately, I am not so familiar with Windows build.

I made a test on Linux with latest commit, is it ok ?

![ra-russian](https://user-images.githubusercontent.com/7869503/102791004-a2ce6700-43a6-11eb-8e66-e89de61d7a53.png)

**Comment by PavelDurov1488** [comment]
Yeah, it works well

Threre is windows build troubles only. Android looks fine too without this commit

Anyway, it does not help in Windows
![image](https://user-images.githubusercontent.com/74456272/102791478-06c25100-43e2-11eb-9480-cf4553c10063.png)

For example, in first line in Settings you see 'Драйверы', with this icon
![image](https://user-images.githubusercontent.com/74456272/102791648-49842900-43e2-11eb-86ad-0777eabb0798.png)
In Windows we see "Профили контроллеров" instead of 'Драйверы', 'Драйверы' are on second line and a lot of mistakes inside menu

Numbers of characters are match on both screenshots
![image](https://user-images.githubusercontent.com/74456272/102791733-6caed880-43e2-11eb-8e04-86a1e3bb9739.png)

**Comment by PavelDurov1488** [comment]
Hmm.... On your screenshot left side is broken
![image](https://user-images.githubusercontent.com/74456272/102792774-e98e8200-43e3-11eb-9716-df0b6d0ae246.png)

It should be
![image](https://user-images.githubusercontent.com/74456272/102792860-05922380-43e4-11eb-9d92-beb514560878.png)

May be we need generate language file again....

**Comment by gouchi** [comment]
Last Crowdin fetch has been made [28 days ago](https://github.com/libretro/RetroArch/commit/6d57819ade8deb7155199f0ed75b74546f5ac47e).

**Comment by 6lackmag3** [comment]
Looks like Russian translation's been fixed. Thanks guys!

**Comment by gouchi** [comment]
Thank you for the feedback.

Surely because of #11855 thanks to @guoyunhe.

If it is ok for you, @PavelDurov1488 please close this issue.

**Comment by PavelDurov1488** [comment]
Oh cool!
Molodsy!

**Comment by 6lackmag3** [comment]
@gouchi 
> Surely because of #11855 thanks to @guoyunhe.
It must've been something else since that commit didn't add nothing new to Russian language files.
Anyway thanks to everyone involved!
