### ISSUE TITLE
[Core Updater] Flycast - RetroArch 1.9.0 has updated the core to an older version

### ISSUE THREAD

**Issue by LukasThyWalls** [libretro/RetroArch#11723]
## Description

Like explained here https://github.com/libretro/flycast/issues/992 we found Retroarch has updated Flycast core from an new version to an older version. Flycast core version 0.1 `b783996` is from 25 November, and it was updated recently with the version 0.1 `ca2fa42` which is from 16 November, and that version introduced some bugs, mainly the save games (VMUs) used with that version are permantely corrupted.

You can see the commits here https://github.com/libretro/flycast/commits/master

### Expected behavior

Retroarch should be using the last working or tested version, or at least the last version at the moment in https://github.com/libretro/flycast (Or whatever it takes the source code)

### Actual behavior

Retroarch is not updated with the correct version and is taking and old and with known bug cores.

### Bisect Results

* By now, if you download Flycast core, it downloads the 0.1 `ca2fa42`, which have some issues, that doesn't have a newer version.
* If you have the previous version 0.1 `b783996`, it is updated with the "newer" version 0.1 `ca2fa42`, but looking https://github.com/libretro/flycast/commits/master, it's not newer.

### Version/Commit

- RetroArch: 1.9.0 (6388872a54 Aug 11 2020)

### Environment information

- OS: Windows 10 Pro 20H2 x64. 

### Notes

In addition, i want to ask why the Libreto Buildbot https://buildbot.libretro.com/nightly/windows/x86_64/ has only the lastest core from every core, although there are a bunch of folders with dates. If you have luck and Retroarch saved the previous core, you can use it, but if not, you only option now is compile yourself the core, and for testing reasons is far from optimal.

Also i'm seeing a los of core are compiled directly from development source, like the Flycast one, and except for the 0.1 number in the version name, it's not pointed out anywhere. That should be warned somehow?

**Comment by afjara** [comment]
I think all the builds currenty available at the libretro buildbot server are dated from november 18, 2020. When migration finishes to the new server, newer core builds will be available.

This situation is extended to all cores/systems.

[https://www.libretro.com/index.php/buildserver-migration-buildbot-server-offline-for-two-day-maintenance-period-starting-11182010/](url)

I'm currently running `b783996` if you need a copy.

**Comment by LukasThyWalls** [comment]
> I'm currently running `b783996` if you need a copy.

Thanks! i didn't lost it because the RetroArch's built-in backup system, but for now, the actual Flycast core download is a pretty broken version.

Maybe there is some issues related to the migration, because the old broken build that RetroArch is downloading now it's from 16 Nov, when the newer build it was downloading before it's from 25 Nov, when the maintenance period began in 18 Nov... something is going on there. Anyway, it is here noted that this happened.

Also, if there is or was recently a buildbot migration, better to see how it ends, because i see weird there isn't, at least, a few official older cores dlls to download somewhere, only for testing purposes they should be very useful.

**Comment by afjara** [comment]
@LukasThyWalls Yes, I remember that cores were updated regularly at the buildbot until december 1st, and then they were reverted to november 18, and since then they are updated... to the past XD

As you said, maybe the migration process broke some parts. For now, it's a good idea to backup all cores from all platforms on a regular basis.

**Comment by LukasThyWalls** [comment]
Yesterday the core updated to the last version which is the same as the actual last commit from the repository.

Maybe the buildbot is now working normal and this can be closed. Thanks.
