### ISSUE TITLE
Error in shader (with easy fix)

### ISSUE THREAD

**Issue by AlvaroBurnett** [libretro/RetroArch#11741]
## Description

The Neo Geo Pocket shaders at:

`shaders\shaders_glsl\handheld\console-border\ngpc-3x.glslp`

and

`shaders\shaders_slang\handheld\console-border\ngpc-3x.glslp`

display the console border with the wrong zoom.

### Expected behavior

The console border should have the appropriate size for the game display.

### Actual behavior

The console border is displayed smaller than it should be and with the wrong aspect ratio, hiding partially the game display.

However this is easy to fix. Edit the ngpc-3x shader and replace:
```
border_zoom_x = "0.70"
border_zoom_y = "0.79"
```
with:
```
border_zoom_x = "0.33"
border_zoom_y = "0.62"
```

### Steps to reproduce the bug

1. Run any Neo Geo Pocket game and enable the ngpc-3x shader.

### Bisect Results

This bug has been there forever. 

### Version/Commit

- RetroArch: 1.9.0

### Environment information

- OS: Windows 10

![Baseball Stars - Pocket Sports Series (Japan, Europe) (En,Ja)-201223-213900](https://user-images.githubusercontent.com/15902444/103035317-5bdb9f80-4567-11eb-80ee-981d3233dfa5.png)

**Comment by BlinkBlank** [comment]
Thanks for the working fix! I've sent PRs to the correct repos.
