### ISSUE TITLE
I can't import folders

### ISSUE THREAD

**Issue by Toadfield** [libretro/RetroArch#11754]
## Description
So if I scan a folder in the "Import Content" tab it doesn't appear [here](https://i.imgur.com/oR78NOD.png)
I have to go into the wimp gui to add it.
### Expected behavior
That it gets added [here](https://i.imgur.com/oR78NOD.png)
### Actual behavior
That this doesn't happen
### Steps to reproduce the bug
Go to "import Content" then "Scan folder" then select the folder with your roms
### Bisect Results
Since I installed Retroarch
### Version/Commit
- RetroArch:1.9.0-1
### Environment information
- OS:Manjaro Kde

**Comment by Toadfield** [comment]
Also another problem is that if I import a folder with the wimp gui and add an game to that folder,then it doesn't show up in Retroarch.

**Comment by hizzlekizzle** [comment]
Have you tried the "manual" scan?

The regular scan compares files' checksums against our databases, so if they don't match those databases exactly, they won't be added to playlists. The manual scan skips the database check and just adds them directly if they match the user-specified criteria (file extension, etc.).

**Comment by Toadfield** [comment]
Thanks,that works
