### ISSUE TITLE
Add retroarch to unistore (Nintendo 3DS)

### ISSUE THREAD

**Issue by wuniversales** [libretro/RetroArch#11759]
Universal store is a store for nintendo 3ds.

Add retroarch to unistore link: https://github.com/Universal-Team/db/issues

Can you request the insert in the 3ds store?

Thanks greetings

**Comment by twinaphex** [comment]
Hi, has this already been added?

**Comment by wuniversales** [comment]
Yes, it was added.
https://db.universal-team.net/3ds/retroarch

It has a bug, but the bug has already been reported here.
https://github.com/Universal-Team/Universal-Updater/issues/64
So I closed this issue.
