### ISSUE TITLE
[Core Updater]update the Duckstation core that is on the libretro servers.

### ISSUE THREAD

**Issue by darkxex** [libretro/RetroArch#11767]
Hello friends, the truth is I don't know who I should talk to about this, what happens is that the version of duckstation that is on the retroarch server is too old, and I wanted to know who I should talk to so that they update the duckstation core for which it's on the official duckstation github servers.

here you can find the daily versions.
https://github.com/stenzek/duckstation/releases

**Comment by twinaphex** [comment]
We will come up with a solution.
