### ISSUE TITLE
If I pause with P and then go into the Retroarch menu with F1,the game is automatically unpaused and muted and if I press P again in that menu nothing happens

### ISSUE THREAD

**Issue by SlushThorsten** [libretro/RetroArch#11776]
## Description
So if I pause and then go into the Retroarch Menu,it's suddenly unpaused and the game is muted and I don't want that,I just want it paused until I unpause it manually.
### Steps to reproduce the bug
Press P and F1 in a game
### Bisect Results
Since I installed Retroarch,some weeks ago
### Version/Commit
- RetroArch:1.9.0-1
### Environment information
- OS:Manjaro Kde

**Comment by briaguya-ai** [comment]
https://github.com/libretro/RetroArch/blob/be650a790ca7d61eedb500aabf72d63de648fe50/retroarch.cfg#L692-L694

https://github.com/libretro/RetroArch/blob/412c79862ce2f54ea11b0c8247ff8d1e735d035c/runloop.c#L3106

looks like this logic makes it so having `menu_pause_libretro` set to `false` will lead to unpausing when opening the menu

**Comment by briaguya-ai** [comment]
after setting some breakpoints (and running into issues) i've been unable to figure out where the cores are getting unpaused

seems like there might be something here?

https://github.com/libretro/RetroArch/blob/412c79862ce2f54ea11b0c8247ff8d1e735d035c/runloop.c#L7390-L7400

#### setup
* pause core when menu open set to false
* pause when lose focus set to false
#### repro steps
* press "p" to pause core
* press "f1" to bring up menu
#### current behavior
* core is unpaused when menu is opened
#### expected behavior
* core stays paused

**Comment by briaguya-ai** [comment]
asked on discord, this has been explored before

there was a fix suggested [here](https://discord.com/channels/184109094070779904/876520593636335646/915737701238583386)

```
diff --git a/runloop.c b/runloop.c
index ead689e0b5..2f281c29d4 100644
--- a/runloop.c
+++ b/runloop.c
@@ -6312,7 +6312,7 @@ static enum runloop_state_enum runloop_check_state(
       {
          BIT256_CLEAR_ALL(current_bits);
          if (runloop_paused)
-            BIT256_SET(current_bits, RARCH_PAUSE_TOGGLE);
+            video_driver_cached_frame();
       }
    }
 #endif
@@ -6711,7 +6711,8 @@ static enum runloop_state_enum runloop_check_state(
          bool menu_pause_libretro    = settings->bools.menu_pause_libretro;
          bool libretro_running       = !menu_pause_libretro
             && runloop_is_inited
-            && (runloop_st->current_core_type != CORE_TYPE_DUMMY);
+            && (runloop_st->current_core_type != CORE_TYPE_DUMMY)
+            && !runloop_st->paused;
 
          if (menu)
          {
```

https://github.com/libretro/RetroArch/blob/412c79862ce2f54ea11b0c8247ff8d1e735d035c/runloop.c#L6730-L6732

after adding the  `&& !runloop_st->paused` from the patch locally the core stays paused when entering the menu, but it still unpauses when leaving the menu

not sure if unpausing when leaving the menu should be rolled into this issue or spun out into a separate one

**Comment by briaguya-ai** [comment]
[cthulhu mentioned](https://discord.com/channels/184109094070779904/723004014140325949/939713216735494155) that a `&& !runloop_st->paused` check could be added here
https://github.com/libretro/RetroArch/blob/master/runloop.c#L6173
