### ISSUE TITLE
[3DS] Enable Core Updater

### ISSUE THREAD

**Issue by MrHuu** [libretro/RetroArch#11787]
I've been successfully been able to test out the `Core Updater` functionality for the 3DS platform.
Using a private server to host the cores in a similar fashion as the WiiU and Vita cores.

The .3dsx builds are fully functional as-is. (downloading, extracting, backing-up, restoring, deleting)
The .cia builds only update the .cia file located on the sd-card, which still needs to be installed manually. 

To make this work with libretro's buildbot, a few additions need to be made to the way the buildbot is serving the current 3DS builds.
The buildbot needs to serve the latest builds in a similar fashion as other platforms (WiiU, Vita).

### Preperation: ###
PR: https://github.com/libretro/RetroArch/pull/11788
This PR enables the `Core Updater` and sets the default server location.

The `DEFAULT_BUILDBOT_SERVER_URL` is set to:
`http://buildbot.libretro.com/nightly/nintendo/3ds/latest`

During runtime, only on initial setup, either `3dsx/` or `cia/` is appended to the server url.
Which allows us to use a custom address without appending the environment by default.

### Buildbot changes required: ###
Additionally to the builds currently hosted, this would require:

Having the .3dsx and .cia core builds in separate locations, like this:
`http://buildbot.libretro.com/nightly/nintendo/3ds/latest/3dsx`
and
`http://buildbot.libretro.com/nightly/nintendo/3ds/latest/cia`

Cores should be compressed to, respectively:
`stella2014_libretro.3dsx.zip`
and
`stella2014_libretro.cia.zip`

On both locations index files must be available:
`.index` which contains a list of filenames.
`.index-extended` which contains a list containing: `date crc filename` for each core.

### Request: ###
@twinaphex @jdgleaver 
Is it possible the required changes can be made to the buildbot and underlying structure?
I was hoping this would be rather trivial looking at the current ongoing migration.

Thanks!

**Comment by twinaphex** [comment]
We can certainly discuss this, we are setting up the new server as of this moment anyway.

**Comment by jdgleaver** [comment]
@MrHuu Yes, what a good idea!

This should be no problem at all to set up on the buildbot - I'll try to get it done this morning.

**Comment by jdgleaver** [comment]
@MrHuu All done: https://buildbot.libretro.com/nightly/nintendo/3ds/latest/

Please test, then we can merge #11788 :)

**Comment by MrHuu** [comment]
That was fast, thanks!

I've tested clean set-ups for both .3dsx and .cia builds.
Both seem to be functioning properly.

Listing all cores, and being able to download them.

I think we're set, and ready to merge.

**Comment by jdgleaver** [comment]
Excellent!

This is a splendid new feature - thank you for setting it up :)

**Comment by MrHuu** [comment]
Thanks should go to everyone making this possible and for the ongoing support.
I merely enabled an unexplored feature, which was just screaming to be enabled.

I do like to look into having .cia files installed as-well.
Retroarch is already capable of installing them. If the core is not already installed, it will install the .cia upon loading the core.

Since the `core updater` is capable of simultaneously downloading and installing (extracting) new cores, while .cia files have to be installed one at a time. Either a task queue for installing .cia's or an option to just manually re-install a .cia could be added.

This would be a goal for the upcoming year, best of wishes to you all.

**Comment by jdgleaver** [comment]
Hmm... In theory, if we could pass the core version to pkg/ctr/tools/makerom* when building the CIA file:

```
pkg/ctr/tools/makerom-linux -help
...
CIA/CCI OPTIONS:
 -content       <file>:<index>      Specify content files
 -ver           <version>           Title Version
```

...then it should automatically install the new core the next time content is loaded.

Otherwise, just pulling out the `installCia()`-related code from `exec_cia()` and adding it as an extra (ifdef'd) step in the existing core updater task could be a possibility.

This does indeed sound like a worthwhile goal for the New Year!

**Comment by MrHuu** [comment]
Yes, that seems like a great approach!

The .cia file already gets installed upon launch if the version differs (not necessarily incrementing).
It's just the versioning which isn't implemented yet.

There are a few limitations using the NCCH/CIA versioning:
https://3dbrew.org/wiki/Makerom#NCCH_configurations_for_CIA

We can use either: 
`-ver` Any value between 0-4095
`-micro`  Any value between 0-15
or
`-major`  Any value between 0-63
`-minor`  Any value between 0-63
`-micro`  Any value between 0-15

Generating random value's already has the desired result.

Here's a working solution.
PR:

**Comment by jdgleaver** [comment]
@MrHuu Very nice! Your random version number PR works very well - updating cores on 3DS is a breeze now :)

One small thing I noticed: in #11788, the buildbot URL is set correctly by `config_set_defaults()` on first run - but if you already have a config file with a 'blank' URL (or if you set the URL to default via RetroPad 'start'), then the string never gets corrected (so you have to enter it by hand). Would you like to look into fixing this? (or I could have a go next week)

**Comment by MrHuu** [comment]
fixed!

With the .cia builds automatically installing, i do notice some regression since ?? .

Currently, the installing goes without any indication. There is a warning message printed to the console. But the bottom screen gets cleared / de-initialized before showing the message.

I think, some sort of indication of the .cia being installed should be shown in retroarch itself.
Rather than printing to the console on the bottom screen.
(keeping in mind, the bottom screen should be used for other purposes than the console)

**Comment by jdgleaver** [comment]
Thanks for the fix!

> Currently, the installing goes without any indication. There is a warning message printed to the console. But the bottom screen gets cleared / de-initialized before showing the message.

You're right! Hmm... I wonder if this is a consequence of moving over to the lasted devkitpro toolchain...?

We certainly do need some kind of on-screen notification. I'll try to investigate what's happening here sometime next week...
