### ISSUE TITLE
Brand New Vita Install Doesn't Work Update ASAP

### ISSUE THREAD

**Issue by DrumMaster777** [libretro/RetroArch#11781]
I've officially been unable to play any retro games since the 1.9.0 update. I've lost all hope with this nd the hundreds of hours over probably half of this entire year has been wasted setting up 12+ consoles in retroarch, making tons of constant alterations to game lists nd reasearching potential new games on unknown or obscure consoles only to update bcuz "hey guys we have a new nd better version out Smilerz", that makes RA close when I try to load content on the VITA. This is extremely frustrating, I've even done a fresh new install deleting everything including all my roms, thumbnails, bios, savestates nd save files nd downloaded new Roms, they don't even show up in scan directory option, I got 400+ games I can't even do anything with for months since this garbage update. Fix asap

**Comment by rsn8887** [comment]
Try the latest build which can be downloaded from VitaDB, it might work better for you: https://vitadb.rinnegatamante.it/#/info/186

**Comment by twinaphex** [comment]
We are working our ass off right now on the new buildbot infrastructure. We were hoping to make it before New Year but that is looking increasingly more unlikely. Use stables for now until we make the announcement that the new server is ready.

**Comment by rsn8887** [comment]
I just tested latest nightly from VitaDB and it works for me. Also, when you update RetroArch Vita, sometimes it helps to try to rename your ux0:data/retroarch/RetroArch.conf file to see if starting from a fresh start makes things work again.

**Comment by twinaphex** [comment]
@rsn8887 Can you test the latest nightly on our buildbot? The dated one?

**Comment by rsn8887** [comment]
It works! But the app name is different than it used to be. It used to be called „RetroArch“, now it is called „retroarchvita_salamander“
![Uploading 5A076F1B-480E-4BFB-84AD-448B635AE3E8.jpeg…]()

**Comment by frangarcj** [comment]
> It works!
> 
> Just a small thing: The app name is different than it used to be. It used to be called “RetroArch”, now it is called “retroarchvita_salamander.”
> 
> ![FCBBB660-076D-4808-9F93-0824B93331ED](https://user-images.githubusercontent.com/13071547/103375637-4ce17980-4aa0-11eb-8610-72d872b2d7d3.jpeg)

Fixed with 87ebd720edc29024867e4d31d9b6b0024d31cad0

**Comment by rsn8887** [comment]
I think this can be closed?
