### ISSUE TITLE
Reicast broken graphics gl

### ISSUE THREAD

**Issue by ruffonetas** [libretro/RetroArch#11786]
## Description

flycast show graphics issues  after core update, if you use "gl" or "glcore" on nvidia drivers  469.89 (lastest). With vulkan works perfect
Windows 10 core i7 4770 32gb ram NVIDIA 1650 4gb Gddr6

gl
![Nvidia glcore](https://user-images.githubusercontent.com/21963233/103366625-210ac780-4a91-11eb-9436-a42600a66afe.png)

glcore
![Nvidia gl](https://user-images.githubusercontent.com/21963233/103366628-223bf480-4a91-11eb-8c20-7a95bfdb78c1.png)

I test the flycast core in a  amd hd7500 serias and work great in gl or glcore whit a very old drivers 15.201 
Windows 10 Phenom X4 8GB Ram AMD HD7570 1GB Gddr5
gl
![AMD old drivers](https://user-images.githubusercontent.com/21963233/103366647-29fb9900-4a91-11eb-99b7-3766f498b761.png)

**Comment by b1scu1t** [comment]
What libretro core are you using? Flycast?
Also, which version is the core?

**Comment by ruffonetas** [comment]
Sorry, is flycast not reicast my bad 
Flycast (0.1 853adf9)

**Comment by Tasosgemah** [comment]
Which game is this so we can test it ourselves?

**Comment by snow344** [comment]
> 
> 
> Which game is this so we can test it ourselves?

Hokuto no Ken
