### ISSUE TITLE
[Windows x64] Installing RetroArch says that "ResampleDmo.DLL was not found."

### ISSUE THREAD

**Issue by aloshTM** [libretro/RetroArch#11790]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When installing RetroArch for the first time, it gives an error when attempting to run it.

### Expected behavior

RetroArch should have ran normally

### Actual behavior

A file is not found (ReSampleDmo.DLL to be exact)

### Steps to reproduce the bug

1. I really don't know how to re-produce because I think it's something on my end and not RetroArch's fault

### Bisect Results

This first started happening when I just wanted to try to play some DS games. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Stable 1.9.0

### Environment information

- OS: [Windows x64] (don't think I have to specify x64)
- Compiler: None

**Comment by theproblemmaker** [comment]
And yes, I have reinstalled the program many times

**Comment by aloshTM** [comment]
lmao this was a me issue
