### ISSUE TITLE
QT Desktop Menu won't launch in the 12/30/20 nightly.

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/RetroArch#11791]
As of build date 12/30/20, version c01b2de (possibly sooner than this, but when I noticed it) this won't launch from menu bar ->window -> toggle desktop menu nor does there seem to be a way to access it within ozone.  Is this feature going away?  To be honest the only reason I used it was to update RA itself as it wasn't possible through the normal UI.  Using Win10 20H2, 2060S, Ryzen 3700X

**Comment by hizzlekizzle** [comment]
This is known. It's not being compiled in at the moment, but it will return very soon.

**Comment by n1ghttrap** [comment]
Seems good now in newer builds.
