### ISSUE TITLE
[Android] Auto Scale Overlay = On results in misaligned gamepad buttons

### ISSUE THREAD

**Issue by Son-Vegitto** [libretro/RetroArch#11809]
## Description

When using '720-med' overlays->gamepad, the on screen buttons do not align with actual input locations, if On screen display setting, Auto Scale Overlay = On.  To actually register an input for the 'a' button, for example, one must move the touch to the right of the actual on screen button and a quarter of an inch. 

I believe this applies to any on screen gamepad.

### Expected behavior

The device should accept input/touch, where the 720-med buttons display (e.g. 'a' button), even when Auto Scale Overlay = On. This should function and on screen buttons and input fields should align, regardless of setting. 

### Actual behavior

The device does not accept input/touch, where the 720-med buttons display (e.g. 'a' button), when Auto Scale Overlay = On. If the setting equal Off, the on screen button and input field align. 

### Steps to reproduce the bug

1. Start any game (used SNES Mario Kart)
2. Set the on screen display/gamepad to 720-med
3. Toggle Auto Scale Overlay to On
4. Attempt to use the on screen controller

### Bisect Results

This started when I updated to the nightly build of 1.9.0 for android. I updated from the stable 1.9.0 build because my non-play version was picked up by the play store with an available 'update'. 

### Version/Commit

- RetroArch: 4c0ee0d

### Environment information

- OS: Android 8.1
- Compiler: Clang/LLVM (9.0.8); downloaded from the official website

**Comment by RobLoach** [comment]
This is likely an error in the overlay configuration itself. You'll find a few other options you can apply to the overlay when changing it, may need to play with those.

Alternatively, mind moving this to the common-overlay repository?
