### ISSUE TITLE
[Vita][GL1] Rendering issue 

### ISSUE THREAD

**Issue by jooozek** [libretro/RetroArch#11829]
## Description

When using the GL1 video driver everything outside of rendered viewport seems to be baking in which is an issue for OLED models of Vita.

### Expected behavior

Expected it to be black all around when not using overlays, marquee, etc.

### Actual behavior

Everything done outside of the viewport bakes in

[https://cdn.discordapp.com/attachments/777596995401285642/796037307542011904/unknown.png](https://cdn.discordapp.com/attachments/777596995401285642/796037307542011904/unknown.png)

### Steps to reproduce the bug

1. Select GL1 video driver
2. Launch core with content
3. Open menu
4. Close menu and all stays baked in

### Version/Commit

- RetroArch: nightly build from 4th January 2021

### Environment information

Vita, Enso 3.60

**Comment by frangarcj** [comment]
This will be fixed in future nightlies when this commit is added to official vitaGL
https://github.com/Rinnegatamante/vitaGL/commit/6e9e26722e4ba3f1da3929fed9267c255a9dd240

**Comment by frangarcj** [comment]
Fixed
