### ISSUE TITLE
Retroarch crashes on launch for 2021-01-04-RetroArch onwards

### ISSUE THREAD

**Issue by Panderner** [libretro/RetroArch#11842]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch Crashes on launch when I use 2021-01-04-RetroArch build onwards

### Expected behavior

2021-01-03-RetroArch build works fine though

### Actual behavior

2021-01-04-RetroArch build crashes on launch

### Steps to reproduce the bug

1. Install 2021-01-04-RetroArch.apk
2. Launch the game
3. And then crashes on launch

### Bisect Results

The last build is working is 2021-01-03-RetroArch build but 2021-01-04-RetroArch crashes onwards

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0 nightly
- Xiaomi POCO M3

### Environment information

- OS: Android 10
- Compiler: 2021-01-04-RetroArch.apk

**Comment by bslenul** [comment]
Can you retry with latest nightly? I had the same issue but it's fixed now thanks to #11846 :)

**Comment by Panderner** [comment]
It's now fixed in 2021-01-08-RetroArch build closing now
