### ISSUE TITLE
[Feature Request] Add option to hide CRT SwitchRES-related notifications on the "Notification Visibility"-section

### ISSUE THREAD

**Issue by Daddu3** [libretro/RetroArch#11848]
While "Notification Visibility"-settings have been quite swell, I seem to catch still some not being removable, mainly pertaining to CRT SwitchRES-related notifications about setting refresh rate to whatever hertz at that time, per ever booting of RA or any frontend leading to it. Depending how small I had set the desktop resolution to force 15khz or 31Khz, the graphical widget-type notifications become easily obstructive due their huge default size, and block good sum of the menu or game screen during bootup.

![20200816_115230](https://user-images.githubusercontent.com/53014019/103982766-d3771480-518c-11eb-92be-cd72708fcb9b.jpg)

So yeah. Please, can any of you add in "Hide SwitchRES Notifications"-option to the Notification Visibility-section? Thanks for all your current contributions so far!

**Comment by Ryunam** [comment]
I believe this can be closed. @Daddu3 has confirmed over on Discord that the new visibility toggle is working as expected.

**Comment by Daddu3** [comment]
Can confirm, the new "Refresh Rate Notifications"-option is very useful.
