### ISSUE TITLE
RetroArch not resolving playlists' paths, handing relative paths to cores

### ISSUE THREAD

**Issue by ner00** [libretro/RetroArch#11859]
## Description

RetroArch does not resolve relative paths if they're used in the playlist, instead that burden is handed off to the core. This works in most cases, but in some situations it can be tricky, like the one I faced a few days ago (https://github.com/libretro/dosbox-svn/issues/69). Centralizing that in RetroArch would spare issues in similar situations where a core hasn't planned for a relative path or can't due to technical reasons.

### Expected behavior

I'll quote @realnc as he put it on the issue referenced above:
> This is only working by accident basically. What RetroArch should really do is resolve relative paths to absolute paths when passing them to the core, because only RA actually knows which directory the playlist file is in. The [DOSBox]-core and [DOSBox]-SVN cores change the current working directory to directory the `.conf` file is in, so that mount commands in `.conf` files can be relative to the `.conf` file itself. (This is for making it possible to keep `.conf` files together with the game itself and be able to copy the whole directory somewhere else.)

### Actual behavior

RetroArch hands the path to the core as it is in the playlist, in some instances this leads a core to not being able to resolve a relative path to the intended absolute path. 

### Steps to reproduce the bug

1. Set a DOS playlist with a relative path to it's config in the playlist (ex: `"path": "roms\\DOS\\Battle Chess\\Battle Chess.dosbox.conf",`)
2. Use DOSBox-SVN core (which hasn't had a workaround implemented for this) to load that playlist entry
3. DOSBox-SVN will fail to load the target file, supposedly because the working dir was changed and the resulting absolute path doesn't match.

### Bisect Results

This has been present all along I asusme, it is typically not an issue with the majority of cores, but in some cases, like the one demonstrated, it is. Ideally, the path resolution should be centralized in RetroArch regardless of the amount of cores that it affects or their popularity.

### Version/Commit

- RetroArch: v1.90/6388872a54

### Environment information

- OS: Windows 10 x64 Build 19042

**Comment by realnc** [comment]
Btw, if this is implemented, then one needs to decide what relative paths in playlists are actually relative to. The RA config directory, or the directory the playlist file is in?

**Comment by ner00** [comment]
I would say the playlist directory would probably be best as starting point, for one because the paths are specified inside the playlist and from a logical standpoint it would possibly make more sense, also it has a better chance of being closer to the target content defined in the path. There might be reasons to assume another directory, or even conflicting approaches, not sure.

**Comment by ner00** [comment]
Apparently the `Portable Playlists` setting, which I wasn't aware of, already addresses this.
