### ISSUE TITLE
Online Updater tries to get non-existent file

### ISSUE THREAD

**Issue by thatsprettygood** [libretro/RetroArch#11853]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When running the Online Updater, RetroArch tries to download "RetroArch_update.zip" when the file on the server is "RetroArch_update.7z".

### Expected behavior

The correct file is downloaded and extracted.

### Actual behavior

It fails to get the non-existent file and it 404s out.

### Steps to reproduce the bug

1. Open the desktop menu
2. Click Tools and go to Online Updater
3. Click Update RetroArch (Nightly)
4. See that it fails with a 404.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Build Date: Jan 8 2021 Git Version: 36b0ffd

### Environment information

- OS: Windows 10, 64-bit.
- Compiler: [In case you are running local builds]

**Comment by snow344** [comment]
Can confirm, also happens to me.
<img src=https://cdn.discordapp.com/attachments/434713532341288961/797245513862610984/retroarch_trzj2sgwMl.png>

**Comment by cascardian** [comment]
Also still happens here.

**Comment by Apocalypse612** [comment]
Allowed the retroarch.exe in windows firewall and it also doesn't work. same error.

**Comment by thatsprettygood** [comment]
UPDATE: The "Online Updater" has been completely removed from retroarch.
I don't know why this change happened, because this was a very easy way to update.
I hope it returns.

**Comment by LibretroAdmin** [comment]
What do you mean it has been completely removed? Should still be there.

Also, does this issue still happen?

**Comment by thatsprettygood** [comment]
@LibretroAdmin
I'm talking about the one that allowed users to update their nightly versions, this was removed a while ago. As such, unless this updater is being brought back, this issue is not longer relevant.
