### ISSUE TITLE
Alt-tab is required after loading content for retroarch to register input

### ISSUE THREAD

**Issue by soredake** [libretro/RetroArch#11886]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

> INPUT MAPPING/REMAPPING: Major bugfix - Remap file having a different device type requires manual intervention after loading for the core to register the type properly

This bug is back, unfortunately.

### Expected behavior

Input working right away.

### Actual behavior

Input requires alt-tab to be registred.

### Steps to reproduce the bug

1. Install retroarch from ppa:libretro/testing
2. Start content
3. Oh no input is not registered!

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch:  1.9.0-r202101151220-6726538971-109~ubuntu20.10.1 

### Environment information

- OS: Kubuntu 20.10
- Compiler: [In case you are running local builds]

**Comment by sonninnos** [comment]
The "manual intervention" mentioned in the bug fix is no way related to alt-tabbing. It was a left+right action on a menu item regarding remapping. The application not being focused for input is something else entirely.

**Comment by soredake** [comment]
And more, after pressing f1 menu does not register input, needs alt-tab, and after returning to game no input is registered either, another alt-tab.

**Comment by soredake** [comment]
Setting this option to "On" from default "Detect" seems to fix input in cores, but retroarch menu in game still needs alt-tab to register input
![изображение](https://user-images.githubusercontent.com/5204968/105959901-2dc90e00-6085-11eb-9ed7-55693d9507f0.png)

**Comment by soredake** [comment]
When i use sdl2 joypad driver i see that gamepad is disconnected at start, which is not normal i think
![Screenshot_20210127_095940](https://user-images.githubusercontent.com/5204968/105960816-661d1c00-6086-11eb-8a4a-0043042fe41d.png)

**Comment by soredake** [comment]
https://github.com/libretro/RetroArch/issues/11888#issuecomment-780605196
