### ISSUE TITLE
"Press again to quit" message shown too many times for no reason

### ISSUE THREAD

**Issue by soredake** [libretro/RetroArch#11888]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

"Press again to quit" message shown too many times for no reason.

Video:

https://user-images.githubusercontent.com/5204968/104807564-8e845b00-57e8-11eb-92d5-0e02edfe2eb1.mp4

### Expected behavior

Not show this message when it's not needed.

### Actual behavior

Messages shown for no reason many times.

### Steps to reproduce the bug

1. Install retroarch from ppa:libretro/testing
2. Start retroarch
3. You will see a message.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch:  1.9.0-r202101151220-6726538971-109~ubuntu20.10.1 

### Environment information

- OS: Kubuntu 20.10
- Compiler: [In case you are running local builds]

**Comment by soredake** [comment]
I've found what caused this issues:
https://github.com/libretro/RetroArch/issues/11886
https://github.com/libretro/RetroArch/issues/11530
https://github.com/libretro/RetroArch/issues/11887
https://github.com/libretro/RetroArch/issues/11888

It's my keyboard, my keyboard have broken escape that presses itself on start and randomly, i have .Xmodmap file with this:
```
keycode 9 = NoSymbol
keycode 127 = Escape
```
Absolutely all other apps don't receive input from broken escape, but not retroarch, which caused all this issues. Blocking input from keyboard by setting input driver to udev and controller driver to sdl2 workaround this problem, with the cost of loss of keyboard input.

**Comment by Szunti** [comment]
Using NoSymbol doesn't disable the key. If you check with xev, key events are still sent. Actually, in the x protocol key events are sent by keycode and modifier state. It's the job of the clients, if needed to translate the keycode and modifier state to a keysym. 

Maybe VoidSymbol works. Else I don't think there is a way to completely disable the key in the X server. You could map it to another keycode though.

### The easiest way to modify xkb layout:
```
xkbcomp $DISPLAY -o hacky_layout.xkb   # saves the current XKB description into the given file
# now edit it
vim hacky_layout.xkb
# first change to an unused keysym, eg. F18
# look for the line that is similar to     key <ESC> { [Escape] }
# change it to       key <ESC> { [F18] }

# then add an action that rewrites the keycode
# look for the lines that start with        interpret ....
# insert after the last one    
interpret F18+AnyOfOrNone(all) {
        action= RedirectKey(keycode=<FK18>);
};
# now save and keep this file
# everytime the x server starts, load the modified layout back (run this instead of the xmodmap)
xkbcomp hacky_layout.xkb $DISPLAY
```
And then instead of Escape that button will behave as F18, and probably everything will ignore that.
