### ISSUE TITLE
RetroArch Plus - Android - Google Play Store version - cores not loading or/and missing

### ISSUE THREAD

**Issue by m1s13k** [libretro/RetroArch#11895]
## Description

Latest version of RetroArch Plus (2021-01-17) don't work.
90% of cores are missing on the download list. Can't start any ROM.
On previous version everything works fine.

### Expected behavior

1. 127 cores available
2. can run ROMs 

### Actual behavior

1. 13 cores available
2. no core can be loaded 

### Steps to reproduce the bug

1. download version "2021-01-17" from Google Play Store
2. try to run any core or rom

### Bisect Results

Started today after update "2021-01-17".

### Version/Commit

- RetroArch (Android phone): 1d4ff9b
- RetroArch (Android TV): 1d4ff9b

Both affected.

### Environment information

- OS: Android 9 (Xiaomi Mi A1)
- OS: Android TV 9 (NVIDIA Shield PRO 2019)

**Comment by calinorg** [comment]
Same issue - older version from website works great, when google play store update kicks in, there is just handfull of cores available.
![IMG_20210117_224755](https://user-images.githubusercontent.com/4256777/104857036-0ef4aa00-5916-11eb-8ada-bc49d39e7a86.jpg)

**Comment by m1s13k** [comment]
Fixed in 2021-01-18, thank You. Closing issue.
