### ISSUE TITLE
Fast Forward WASAPI audio issue

### ISSUE THREAD

**Issue by ichee** [libretro/RetroArch#11891]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

While using the WASAPI audio driver with exclusive mode enabled, toggling fast forward will result in a constant audio tone or buzzing that will not stop until the current core is unloaded.

### Expected behavior

Audio to return to normal after disabling fast forward.

### Actual behavior

Fast forwarding indefinitely messes up the audio until core is closed.

### Steps to reproduce the bug

Set audio driver to WASAPI then restart Retroarch. Then enable exclusive mode under audio\ouput. (should be enabled by default with newer builds)

Load any game on any core.

Toggle fast forward.

### Bisect Results

Oldest version I have to test with is stable 1.8.9, which also exhibits the issue.

### Version/Commit

- RetroArch: 1.9.0 stable and latest nightly as of 01-16-21

### Environment information

- Windows 10 64-bit
- Nvidia GTX 1080 TI

### Note:

This issue does not occur with xaudio.

Also, different video drivers or different audio latency values do not fix issue.

Frame delay and RunAhead are not in use.

### Additional Info:

Creating a savestate after issue occurs then loading the state after closing and reloading the core first does not restore the audio issue with it.

**Comment by ichee** [comment]
Issue can also be caused by toggling audio sync, which I'm assuming fast forward also does.
I don't know if that will help with finding the root cause, but it is an additional finding.

**Comment by twinaphex** [comment]
This is indeed an issue. Unfortunately, we don't know yet how to fix it.
