### ISSUE TITLE
Retroarch 1.9.0 crashes upon content loading - PSTV

### ISSUE THREAD

**Issue by toolmanwill** [libretro/RetroArch#11909]
## Description

Retroarch 1.9.0 crashes upon content loading without error

### Expected behavior

Loading roms starts game

### Actual behavior

loading rom shuts down retroarch instantly

### Bisect Results

Started happening at verison 1.9.0. 
1,8,9 works fine

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0 stable

### Environment information

PSTV (Playstation TV)

**Comment by Tantris55** [comment]
See 11949 for the same Issue. Error occurs when Retroarch has to load a different core than the one currently loaded.

**Comment by FinixFighter** [comment]
It happens to me too on Linux. Never happened before. Even if I close RA and restart it, I can't load any content anymore.

**Comment by dverbeeck** [comment]
This happens to me as well w/ 1.9.0. I need to upgrade to 1.9.1 and see if it still happens. I am running the same build and same cores on my handled Vita without issue.

**Comment by frangarcj** [comment]
can you check if it is fixed?
