### ISSUE TITLE
[Linux] Mouse cursor MUST be inside RetroArch window for keyboard inputs to be registered.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#11908]
## Description

On my Linux Mint VM, if I'm using RetroArch in windowed mode, the mouse cursor must be inside the RA window or the keyboard inputs won't register, it happens with every input drivers but udev (so in my case: x, sdl2 and linuxraw).

No issue on Windows 10 with the 3 choices I get (dinput, sdl2 and raw).

### Expected behavior

Keyboard inputs should work even if the mouse isn't inside the RA window.

### Actual behavior

Not registering any input from the keyboard until you move the cursor inside the RA window.

### Steps to reproduce the bug

1. Start RA in windowed mode.
2. Have input driver set to anything but udev.
3. Move the mouse cursor outside the RetroArch window and try to use your keyboard.

### Bisect Results

Started with b1ee5a2421871eb6eefb430771baaf6017a313df

### Version/Commit

- RetroArch: 1.9.0 / 6011ebd31157c4c37ab103f67f1e9ba53a504c5e

### Environment information

- OS: Linux Mint

**Comment by soredake** [comment]
[Related?](https://github.com/libretro/RetroArch/issues/11886)

**Comment by jdgleaver** [comment]
@bslenul Apologies! That was basically a copy/paste error in the X11 input driver (I put the keyboard polling after the 'cursor in window' check, instead of before....), and since I always have 'focus follows mouse' enabled in my desktop environment I didn't notice the problem. This fixes it for X11: https://github.com/libretro/RetroArch/pull/11910

`sdl2` and `linuxraw` are another matter, though - not sure how to fix them...

**Comment by bslenul** [comment]
Hey! No need for apologies :D Tested your PR and it works properly again! 👍 

For sdl2 and linuxraw I'm a bit confused, maybe my VM handles this stuff differently than a "real" machine? It was working before and... it's working again with your PR for me :p

Thank you! ❤️

**Comment by jdgleaver** [comment]
Oh, that's so strange... Changing the X11 driver shouldn't affect `sdl2` and `linuxraw` at all - and those drivers don't even have any focus checking...

Then again, RA input can be inscrutable (e.g. The gfx driver initialises the input driver. Why? No one seems to know...) - so I guess I'll just be happy and count this as a win :)
