### ISSUE TITLE
Audio gets out of sync and is stretched when using pulse driver on Linux via PipeWire

### ISSUE THREAD

**Issue by Sonickyle27** [libretro/RetroArch#11926]
## Description

When using PipeWire as an audio driver on Linux and using RetroArch's `pulse` audio driver, the audio from RetroArch can fall out of sync, become stretched out and lower in pitch whenever the content in RetroArch is paused or the RetroArch window is not focused.

### Expected behavior

Audio should stay in sync with the content when using the `pulse` driver and the PipeWire audio server.

### Actual behavior

Whenever the content is paused (either by the user or because the core is stuttering), or the RetroArch window is not in focus, the audio falls further and further out of sync, is lower in pitch and is stretched. With enough time, the audio's pitch increases over time and catches up to the content. Menu sounds also fall out of sync, but are not affected by the pitching and stretching.

### Steps to reproduce the bug

1. Replace PulseAudio with PipeWire and install the `pipewire-pulse` package from your software repo.
2. Open RetroArch and set the audio driver to `pulse` if it isn't already.
3. Restart RetroArch.
4. Load up any content, like PS1, Mega Drive, etc..
5. Press F1 to bring up the menu for a few seconds, then hit F1 again
6. The audio will be out of sync, lower pitched, and stretched.
7. Press F1 once more to open the menu and the content audio will continue playing for a while.

### Bisect Results

I haven't had time to bisect this yet. Sorry.

### Version/Commit

- RetroArch: 1.9.0/2520337ddc

### Environment information

- OS: Manjaro Linux

### Notes:

I have tried using the `jack` `alsa` and `alsathread` audio drivers, but those for whatever reason crackle more than `pulse` does at the same audio buffer size.

Using X11 or Wayland makes no difference.

Here's an upload of the audio I hear when opening a PS1 game and hitting F1 a few times: https://drive.google.com/file/d/1TCqs_DNiLVFoigpDdSR2_yMU0uy4q6Zh/view?usp=sharing

**Comment by rijnhard** [comment]
I think this is actually a bug in the pipewire-pulse package, it's not a fully stable replacement yet and Pulseeffects users are also experiencing this

**Comment by Clownacy** [comment]
That could be right: I switched back to PipeWire after a recent update and the issue no longer seems to be there. I'm on Arch, so the update might take a while to reach other distributions. Is @Sonickyle27 able to confirm this?

**Comment by Sonickyle27** [comment]
@Clownacy I'll give this a try again once I receive the update to that. Thanks.

**Comment by Sonickyle27** [comment]
Yep, I'm no longer getting this issue with the `pulse` driver and pipewire version 1:0.3.22-1!

**Comment by nyanpasu64** [comment]
I'm getting the same issue again in PipeWire git (between 0.3.40 and 0.3.41) and 0.3.41. A similar issue is tracked in the PipeWire repo at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1903.
