### ISSUE TITLE
[Windows] Grabbed mouse can actually leave the RetroArch window.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#11932]
## Description

When using windowed mode, if you grab the mouse (F11/Scroll Lock), the cursor can actually leave the window, you don't see it on the OS but it's clearly not inside the RA window anymore.

https://user-images.githubusercontent.com/33353403/105615318-e82feb00-5dcf-11eb-8373-40b866ddaf8b.mp4

I've only recorded in RA main menu but it also happens ingame. I actually noticed it while testing Arkanoid on NES with the mouse, the cursor stopped moving at some point because of this.

Tried on my Linux VM and the cursor properly stops when reaching the borders/corners of the window.

### Expected behavior

The mouse shouldn't be able to leave the RA window when grabbed.

### Actual behavior

The cursor can leave the RA window.

### Steps to reproduce the bug

1. Open RetroArch in windowed mode.
2. Press F11 to grab the mouse.
3. Go to the top-left corner for example, instead of being stopped, the cursor will leave the RA window.

### Bisect Results

Since forever it seems, tried with RA 1.3.2 and it was already happening.

### Version/Commit

- RetroArch: 1.9.0 / 6167f8c

### Environment information

- OS: Windows 10.

**Comment by sonninnos** [comment]
Seems to be fine with `dinput`, but indeed not with `raw`.

**Comment by bslenul** [comment]
Weird 🤔 For me it happens with both "dinput" and "sdl2", with "raw" the cursor doesn't even appear when mouse is grabbed inside the RA window... but it appears when it goes outside -_-

**Comment by sonninnos** [comment]
I got it to behave the same with all drivers, as in you can't click outside the window, but the cursor still appears to be able to travel outside. No idea yet if that can be done.
