### ISSUE TITLE
[UI Input/Controls] Listed buttons for Xinput controllers not ordered in a logical sense

### ISSUE THREAD

**Issue by pokeshark** [libretro/RetroArch#11937]
## Description

Listed buttons for Xinput controllers are not grouped/ordered in a logical sense.
Found in these menu sections (with menu drivers Ozone/XMB):
- Settings -> Input -> Port X Controls
- Quick Menu -> Controls -> Port X Controls

### Actual behavior
Current button order is not grouping A B X Y with Shoulder/Triggers.
We have intercalated buttons that are rarely changed by the user (Select, Start, D-pad..)

B
Y
Select
Start
D-Pad Up
D-Pad Down
D-Pad Left
D-Pad Right
A
X
...

Screenshot: https://i.imgur.com/PRGs3CR.png

### Expected behavior
A B X Y should be followed by the Left/Right Shoulder/Triggers, since they are the main buttons that you'd want to change 99% of the time. This could be improved with an order similar to this:

Select
Start
D-Pad Up
D-Pad Down
D-Pad Left
D-Pad Right
A
B
X
Y
...

**Comment by bslenul** [comment]
There's probably a good reason for this specific order but I have to agree, I always found it weird to have B/Y and A/X separated like this :D 

> A B X Y should be followed by the Left/Right Shoulder/Triggers, since they are the main buttons that you'd want to change 99% of the time.

For this same reason, it would probably better to have them at the top when you enter the menu, maybe like this?:

```
A
B
X
Y
L
R
L2
R2
L3
R3
Select
Start
D-Pad
Left Analog
Right Analog
```

**Comment by Ryunam** [comment]
This is an interesting suggestion. I agree that the grouping and order of the inputs could be revisited to make it all a bit more logical. 

I think if I were to submit a PR about this I would go for the following approach, with the idea of the “RetroPad” and its configuration in mind:

```
D-Pad Up
D-Pad Down
D-Pad Left
D-Pad Right
Select
Start
A
B
X
Y
L
R
L2
R2
Left Analog Up
Left Analog Down
Left Analog Left
Left Analog Right
Right Analog Up
Right Analog Down
Right Analog Left
Right Analog Right
L3
R3
```

What do you think?

**Comment by pokeshark** [comment]
any grouping would be better than current disjointed one.
