### ISSUE TITLE
No bundle.zip for RetroArch Web Player

### ISSUE THREAD

**Issue by Damix48** [libretro/RetroArch#11947]
## Description

404 of https://buildbot.libretro.com/assets/frontend/bundle.zip

### Expected behavior

Download https://buildbot.libretro.com/assets/frontend/bundle.zip

### Actual behavior

404

### Steps to reproduce the bug

1. Go to https://buildbot.libretro.com/assets/frontend/bundle.zip
2. 404

- RetroArch: RetroArch Web Player

**Comment by m4xw** [comment]
What exactly requires this?
The Web player makes no use of that file.

**Comment by m4xw** [comment]
Deprecated.

**Comment by Damix48** [comment]
https://github.com/libretro/RetroArch/tree/master/pkg/emscripten

**Comment by m4xw** [comment]
https://buildbot.libretro.com/assets/frontend/assets.zip

And ready-to-go full bundles https://buildbot.libretro.com/nightly/emscripten/

**Comment by Damix48** [comment]
Thanks

**Comment by m4xw** [comment]
I guess feel free to open a issue for updating the readme's tho..

**Comment by Damix48** [comment]
I will do
