### ISSUE TITLE
[Feature request] adding Atari 2600 emulator and odyssey 2 emulator to dingux

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/RetroArch#11957]
just wanted to say i am enjoying all the emulators we have now on dingux I would like to see Atari 2600 emulator and odyssey 2 emulator sometime in the future.

**Comment by john-parton** [comment]
I believe there is an Atari 2600 Emulator, https://docs.libretro.com/library/stella/

Should be included in the latest release, I believe.

**Comment by john-parton** [comment]
o2em is the Odyssey 2 emulator, and I believe it is also included in the latest release https://github.com/libretro/libretro-o2em

**Comment by john-parton** [comment]
@twinaphex Consider closing as resolved.
