### ISSUE TITLE
[Android] Sideloaded app gets updated by the Google Playstore with Retroarch Plus 

### ISSUE THREAD

**Issue by masid101** [libretro/RetroArch#11963]
## Description

Sideloaded 64bit app from the website gets updated by the Retroarch Plus version by the Google Playstore.

### Expected behavior

Google Playstore not updating a sideloaded app!

### Actual behavior

Causes weird bugs like this one ...
https://github.com/libretro/pcsx_rearmed/issues/488

### Steps to reproduce the bug

1. Sideload the 64bit app on the Nvidia Shield (maybe every other android device) and look at the updates from the Playstore.

### Bisect Results

I think after releasing the Retroarch Plus app.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0

### Environment information

- OS: Android

**Comment by briaguya-ai** [comment]
had you previously installed the play store version? I never installed the play store version and the sideloaded app has remained untouched by play store updates

**Comment by masid101** [comment]
Fixed with some former update.
