### ISSUE TITLE
Translated sentneces in wrong places (Polish)

### ISSUE THREAD

**Issue by SZYM0NEK** [libretro/RetroArch#11974]
Hi, since RetroArch v1.8.9 (Win64) **POLISH** translation has wrong sentences in wrong places.

In RetroArch v1.8.8 everything is fine, but since v.1.8.9 in Main Menu "Load Core" appears in english (it should be "Załaduj Rdzeń" in polish) and most of the other sentences are in wrong places all over RetroArch menus.

For example, in Main Menu "Dump Disc" says "Load Disc" in polish (Załaduj dysk), or "Show Desktop Menu" says "Close Content" in polish (Zamknij zawartość).

It looks like a logic error in strings of translation file.

This error is present even in latest nightly build.

Thank You for amazing work on RetroArch. I hope this error can be easily fixed.

Cheers

**Comment by 6lackmag3** [comment]
Hello.
Go to page 17 and 18 of [Polish translation on Crowdin](https://crowdin.com/translate/retroarch/all/en-pl?filter=basic&value=0) and look for all strings with hotkeys (ampersand sign '&'). As you can see there's a bunch of lines with shortcuts assigned to the same letter (e.g. letter 'W'). Mark letters with ampersand so they wont cross with each other. Delete old translations and ask @guoyunhe to fetch updated strings to source.
I think that helped me to fix the same issue with Russian translation.
Regards!

**Comment by mard** [comment]
RetroArch 1.9.4 is still affected.

Per @6lackmag3 's instructions, I've just updated Crowdin with the following translations containing ampersands:

* &Load Core... `&Załaduj rdzeń...` &rarr; `Z&aładuj rdzeń...`
* &Unload Core `&Wyładuj rdzeń` &rarr; `Wyła&duj rdzeń`
* &View `&Widok` &rarr; `W&idok`
* &Help `&Pomoc` &rarr; `Pomo&c`
* &Choose... `&Wybierz...` &rarr; `Wy&bierz...`

I see no collisions with other hotkeys.

@guoyunhe , if you're kind enough to delete old translations and fetch the new ones to the source. I really do hope that resolves the issue.

Have a good day!

**Comment by 6lackmag3** [comment]
@mard
Hi! Unfortunately, guoyunhe is hard to reach out to nowadays. You may want to ask nice folks from #retroarch-translations on Discord or just wait for translation to be synchronized later.

**Comment by DisasterMo** [comment]
Hey there! We are currently working on getting translation updates rolling (#12494).
It won't be much longer! Please bare with us!
