### ISSUE TITLE
Compiling on Raspberry Pi 4

### ISSUE THREAD

**Issue by Langerz82** [libretro/RetroArch#11971]
## Description
Compiling Error:
```
gfx/drivers_context/vc_egl_ctx.c: In function ‘gfx_ctx_vc_destroy’:
gfx/drivers_context/vc_egl_ctx.c:184:10: warning: implicit declaration of function ‘gfx_ctx_vc_bind_api’; did you mean ‘gfx_ctx_vc_destroy’? [-Wimplicit-function-declaration]
          gfx_ctx_vc_bind_api(data, vc_api, 0, 0);
          ^~~~~~~~~~~~~~~~~~~
          gfx_ctx_vc_destroy
gfx/drivers_context/vc_egl_ctx.c: At top level:
gfx/drivers_context/vc_egl_ctx.c:459:13: error: conflicting types for ‘gfx_ctx_vc_bind_api’
 static bool gfx_ctx_vc_bind_api(void *data,
             ^~~~~~~~~~~~~~~~~~~
gfx/drivers_context/vc_egl_ctx.c:184:10: note: previous implicit declaration of ‘gfx_ctx_vc_bind_api’ was here
          gfx_ctx_vc_bind_api(data, vc_api, 0, 0);
          ^~~~~~~~~~~~~~~~~~~
make: *** [Makefile:206: obj-unix/release/gfx/drivers_context/vc_egl_ctx.o] Error 1
```

### Expected behavior
Compile Success

### Actual behavior
Not Compiling

### Steps to reproduce the bug
make

### Version/Commit
- RetroArch: [version/commit]
v1.9.0

### Environment information
Raspberry PI

### Solution
modify: retroarch/gfx/drivers_context/vc_egl_ctx.c
add line 84:
`static bool gfx_ctx_vc_bind_api(void *data,
      enum gfx_ctx_api api, unsigned major, unsigned minor);`

also in terminal install missing library:
`sudo apt install libx11-xcb-dev`

**Comment by cmitu** [comment]
Isn't this fixed already in https://github.com/libretro/RetroArch/pull/11171 ?

**Comment by edrozenberg** [comment]
Same issue with 1.9.0 trying to build on Raspberry Pi 3.

Don't know if #1117 fixes it - maybe, but I also failed to build master earlier today due to a different error (will have to report that one later I guess), so having to stay on 1.8.9 for now.

I'll try again next time there's an official release (1.9.1 or 2.0.0 etc) because trying various random things is too painful due to the long compile time on RPi's.

**Comment by cmitu** [comment]
@edrozenberg Current master compiles fine on a RPI 3, as long as you're using the right options (i.e. use the VC drivers and disable opengl_core, etc.).

**Comment by neilmunday** [comment]
I can confirm that on the current master (9086d241a7f20208cf279f6a7e877ae7bdca325d) RetroArch compiles fine on the Raspberry Pi 3 using GCC 10.
