### ISSUE TITLE
[XSS/X] RetroAchievements causing framerate to plummet on some games

### ISSUE THREAD

**Issue by TreeBranches** [libretro/RetroArch#11988]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Enabling RetroAchievements on Xbox Series S (and possibly X) causes the framerate to plummet to 2fps on certain games (confirmed to happen on Tomb Raider 2 for PlayStation, any Core), even during the PS1 BIOS bootup screen.

### Expected behavior

For the framerate to not drop. Tomb Raider 1 does not suffer from this when having RetroAchievements enabled. Tomb Raider 2 is perfectly playable when disabling RetroAchievements.

### Actual behavior

FPS drops to 2fps, even during the PS1 BIOS boot up introduction.

### Steps to reproduce the bug

1. Sign in to and enable RetroAchievements
2. Load Tomb Raider II in any of the PS1 Cores available on Xbox Series S/X (I typically use Beetle PSX)
3. Turn the volume up and hear the stammering during the PS1 boot screen. I'll be surprised if you even make it to TR2's title screen :)

### Bisect Results

This is always been a problem.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0
- Build Date: Jan 7 2021
- Compiler MSVC (1928) 64 bit

### Environment information

- Xbox Series S, Retail Mode.

**Comment by Jamiras** [comment]
Tomb Raider II's achievement code has ~6000 unique memory references. Several of these are pointers that are not initialized during the boot sequence. As the achievement code tries to evaluate these uninitialized pointers, it sees the core doesn't expose the required address and attempts to disable any achievements using the invalid addresses. However, the only references to the invalid addresses are pointer references, so the achievements are not disabled, causing the same thing to happen for every achievement using the pointer every frame until the pointer is properly initialized. This effectively traverses all ~6000 memory references looking for items to prune for every achievement using the uninitialized pointers for each frame. The result is that processing the achievements takes ~100x longer than normal, noticeably impacting the framerate.

Ideally, a failed pointer lookup shouldn't attempt to disable the achievements, but the place where the disabling is occurring doesn't know the address is associated to a pointer. I've chosen to simply skip the disabling code if the address is not in the valid range of supported addresses for the system.
