### ISSUE TITLE
[iOS] Cheats not working

### ISSUE THREAD

**Issue by Dantasstic** [libretro/RetroArch#11995]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

"Update Cheats" under Online Updater appears to do nothing, and even with Menu Item Visibility turned on for "Show Cheats" under the Quick Menu, the Cheats menu is not visible at all.

### Expected behavior

I should be able to turn on and use Cheats for supported cores.

### Actual behavior

No cheats are currently working at all.

### Steps to reproduce the bug

1. Open Quick Menu in a game
2. Scroll through the list of options
3. See that there is no option for Cheats available

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0 - Build date August 9, 2020

### Environment information

- OS: iOS 14.4
- Device: iPhone 12 Pro Max
- IPA installed via AltStore
- Compiler:

**Comment by Cibomatto2002** [comment]
What emulator are you trying the cheats on?

**Comment by Dantasstic** [comment]
Snes9X - Current is my main, but this issue is not confined to just that core.

**Comment by Dantasstic** [comment]
> 
> 
> What emulator are you trying the cheats on?

Snes9X - Current is my main, but this issue is not confined to just that core.

**Comment by Cibomatto2002** [comment]
Try a nightly build and see if it works for you.

https://buildbot.libretro.com/nightly/apple/

**Comment by Dantasstic** [comment]
> 
> 
> Try a nightly build and see if it works for you.
> 
> https://buildbot.libretro.com/nightly/apple/

Seems like only cores there, no build for RetroArch itself that I can find.

**Comment by Cibomatto2002** [comment]
I was thinking it was like windows sorry about that.

**Comment by warmenhoven** [comment]
I've tried this with Mesen and Snes9x and both seem to be working now.
