### ISSUE TITLE
Linux: Different cores crash to desktop if video driver is set to Vulkan

### ISSUE THREAD

**Issue by Kupo91** [libretro/RetroArch#12004]
I first noticed it with Dolphin. If you try to open a game with dolphin, retroarch immediately crashs to desktop.
Today I noticed it with PPSSPP aswell. I tested the games Flatout and Crazy Taxi. The core starts normal but everytime I try to start a race it crashs to desktop.
This only happens if Vulkan is enabled (glcore works) and only with linux (ubuntu). Windows is fine.
I installed from ppa as it is described on the retroarch homepage. I've read various posts on reddit where other users reported the same behavior.
[retroarch-dolphin.log](https://github.com/libretro/RetroArch/files/5940875/retroarch-dolphin.log)
[retroarch-ppsspp.log](https://github.com/libretro/RetroArch/files/5940877/retroarch-ppsspp.log)

**Comment by Kupo91** [comment]
Today I tested the flycast core. Again after loading screen -> Crash to desktop.
Changig the video driver from vulkan to glcore fixed the issue.
[retroarch-flycast.log](https://github.com/libretro/RetroArch/files/6251860/retroarch-flycast.log)

**Comment by gouchi** [comment]
@Kupo91 is it still an issue with latest RA and latest cores ?

Thank you.

**Comment by gouchi** [comment]
@Kupo91 Is it still an issue or can we close this issue ? Thank you.

**Comment by Kupo91** [comment]
Cant reproduce it with my current setup

**Comment by gouchi** [comment]
Thank you for your test.

So if you don't reproduce the issue, please close this issue.

Thank you.
