### ISSUE TITLE
UWP VFS Creation of default directories causes exception

### ISSUE THREAD

**Issue by vertexmachina** [libretro/RetroArch#12013]
## Description

On initial startup when the default directories are being created in AppData, an exception is thrown when it attempts to create `filters/audio` because the `filters` parent directory has not been created yet.

If I create the `filters` folder manually, it happens again when `database/rdb` creation is attempted.

It also does the same when it goes to create `assets/ozone` and everything underneath that directory.

### Expected behavior

It should create `filters/audio`, `filters/video`, and `database/rdb` empty directories.

### Actual behavior

It attempts to create `filters/audio` but fails because `filters` is not created, falls through to the WinRT catch, which then throws an exception.

```
Exception thrown at 0x00007FFC73AFD759 in RetroArch-msvc2017-UWP.exe: Microsoft C++ exception: Platform::COMException ^ at memory location 0x0000000EAA8F5590. HRESULT:0x80070002 The system cannot find the file specified.
WinRT information: The system cannot find the file specified.
```

### Steps to reproduce the bug

1. Delete all AppData for RetroArch so that no config directory exists.
2. Launch RetroArch
3. Watch as it hangs because an exception is thrown and not caught.

### Bisect Results

Unknown - I've never built/run from master before.

### Version/Commit

- RetroArch: 170b3e3

### Environment information

- OS: Windows 10.0.19042
- Compiler: Visual Studio 2017; Windows SDK 10.0.17763.0

**Comment by vertexmachina** [comment]
I'm unsure if there is something wrong with WinRT here (since apparently this has been the method of directory creation for a long time now).

**Comment by vertexmachina** [comment]
If I just tell Visual Studio to ignore the exception then everything carries on. Is that expected behavior?

**Comment by driver1998** [comment]
There is something odd in Visual Studio, looks like it insists on breaking into exceptions even though we have a try-catch block outside.
Or maybe this is AsyncOperation related... From what I tested it only happen when debugging.

**Comment by tunip3** [comment]
I think this issue should have already been fixed, can you try to recreate this error with the latest source so I can know if this still needs to be investigated?

**Comment by vertexmachina** [comment]
I no longer have an Xbox or the means to test this. I will close it out.
