### ISSUE TITLE
Unable to compile on M1 ARM due to zlib error

### ISSUE THREAD

**Issue by fayep** [libretro/RetroArch#12020]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

With zlib 1.2.11 installed from MacPorts, building on MacOS 11.2.1 ARM64:
deps/libz/adler32.c:49:10: error: conflicting types for 'adler32'
uint32_t adler32(uint32_t adler, const uint8_t *buf, size_t len)
         ^
/opt/local/include/zlib.h:1688:23: note: previous declaration is here
ZEXTERN uLong ZEXPORT adler32 OF((uLong adler, const Bytef *buf, uInt len));

### Expected behavior

Clean compile

### Actual behavior

Compile fails due to incorrect type resolution.

### Steps to reproduce the bug

1. git clone...
2. ./configure --prefix=/opt/local --enable-metal
3. make

### Bisect Results

Ignoring as this code hasn't changed since 2014 (that may be the problem)

### Version/Commit
You can find this information under Information/System Information

- RetroArch:v1.2-33177-g269523d42b
(from git describe)

### Environment information

- OS:MacOS 11.2.1
- Compiler: Apple Clang 12 (OSX 11.2 CLI toolchain)

**Comment by twinaphex** [comment]
You should now be able to build this with RetroArch_Metal.xcodeproj for ARM Mac.
