### ISSUE TITLE
Playlist does not add unknown roms

### ISSUE THREAD

**Issue by borrelnoten** [libretro/RetroArch#12039]
The issue:

I can't put my atari ST roms in a playlist. I tried to scan manualy but still no luck. They are not original games but hacked menu from crack scene (compressed multiple games onto a disc decompression when loading a game).
I want to have a list of my Atari discs so that I can play them without having ot select them manualy (loading the entire directory with roms every time I select one).

Same goes for the amiga discs (HDR extention) which are not picked up for some reason. The manual scan does not work. Also I have tried to make the LPL file manualy and that works! But not for long because after selecting and playing a disc on the list, the list is upaded and is empty after returning from the emulated game to the retroarch menu / playlist.

What I want/expect:

I really would love to see Atari ST and Amiga discs in the playlist because they are truely historic value for me.
I do not understand why that is so difficult because it is simply a simple file list without extention. I do not care about auto detection at all. Also, why not just accept the manual crafted playlist? Why distroy it after selecting an item in it? I love retroarch but the playlist thing is really not logical for me.

Option:

1: Accept a manually build (json / text based) lpl playlist file (and do not destroy it after selecting an item in it)
2: Add a scan option to accept a rom by filename only (no auto detect anything, just a name of the file)

I know this issues has 2 related issues already and still there is no solution for this issue even though boths issues are closed.

**Comment by hizzlekizzle** [comment]
The manual scan exists to do exactly this stuff.

**Comment by borrelnoten** [comment]
Found the critical playlist setting that allow me to.build.manual playlists with items that do.not match the.database. solved both issues for me.
