### ISSUE TITLE
Cheats not Working

### ISSUE THREAD

**Issue by Corpyo** [libretro/RetroArch#12051]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[When I go to update cheats nothing happens]

### Expected behavior

[That the cheats would be updated and I could input them in the cores]

### Actual behavior

[Nothing happens and when I go to the cores there is no cheats option]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[This has happened on every attempt I habe downloaded Retroarch]

- RetroArch: [1.9.0]

### Environment information

- OS: [IOS 14.0]
-

**Comment by Dantasstic** [comment]
https://github.com/libretro/RetroArch/issues/11995
