### ISSUE TITLE
Cheats don’t seem to work on IOS phone

### ISSUE THREAD

**Issue by Corpyo** [libretro/RetroArch#12064]
I click update and there is no response. I play every core and there is no cheats options on Quick Menu.

**Comment by Dantasstic** [comment]
This doesn't seem to concern anyone here, as I opened this 18 days ago:

https://github.com/libretro/RetroArch/issues/11995

**Comment by Corpyo** [comment]
But how do the nightly builds work? I tried it and I can’t find it anywhere on Retroarch.

**Comment by Dantasstic** [comment]
You can't find any because there aren't any nightly builds for iOS; if there were, this cheat issue probably would have been fixed by now.
