### ISSUE TITLE
RPG Maker muting and misc errors

### ISSUE THREAD

**Issue by Rstation4** [libretro/RetroArch#12075]
Raspberry Pi 4b 4gb
Lakka Os, Nightly build rpi4 arm- Feb 20,2021  http://nightly.builds.lakka.tv/2021-02-20/RPi4.arm/

Some of the games have a red error screen that will freeze the lakka os. For example it occured on Lisa, and Yume Nikki (english fan translation Uboachan). OneShot when run from the RPG_rt.ldb file it will give an error about needing to run from the .exe file 

Im not well veresed and it doesnt help due to lack of documentation but is there a way to get them to run from a .exe file? Some of the games wont work and a few are only found in a .exe installer, which may not work if i install on a pc and then copy/paste them into my roms folder on lakka os.

There was even sound being muted in some of the games.

edit: I went ahead and tried again with a different download source.

![RPG Maker emulator](https://user-images.githubusercontent.com/73009731/109742602-4322e200-7bc7-11eb-81b2-783b580207ef.png)

**Comment by gouchi** [comment]
Please close this issue.

[One issue](https://github.com/libretro/Lakka-LibreELEC/issues/1189) is enough and it should have been better to open it to the [dedicated repository.](https://github.com/EasyRPG/Player/issues)

Thank you.

**Comment by Ghabry** [comment]
@twinaphex please close this one, is in the wrong repo. thanks.
