### ISSUE TITLE
Dunnos & Suggestion (Probably Feature Request Too)

### ISSUE THREAD

**Issue by inukaze** [libretro/RetroArch#12080]
Hi there, i am going write this very fast before i forget all things i need to tell. and sorry for my bad english (i had test all this on 6 different machines with Windows 7 and/or GNU/Linux [Multiples distros]).

i had download and compile RetroArch 1.9.0 from Git and compile under Slackware 14.2 (32 Bits) & Slackware64 14.2 (64 Bits) native version both

I had download precompiled version of RetroArch v1.9.0 for Windows 7, for 32 Bits and 64 Bits. 

me and three of my friends we don't have any gamepad and/or joystick, just keyboard and mouse. because of that using retroarch we need 

1 - Change the shortcut keys and make default for example Hold Down Super (Win Logo Key) and the another key or just make the default combinations like Alt+Enter for toggle between Windowed/Full Screen Mode.

Because we just had keyboards and mouse, and in some cores, like N64 (Mupen64Plus, Mupen64Plus-Next, ParaLLEI N64) we ever assign the follow keys

W = Analog Left , D = Analog Right , W = Analog Up , S = Analog Down
I = C-Up , K = C-Down , J = C-Left , L = C-Right 
Enter = Start , T = B, G = A , Z = H

But the defaults keys like H for restart game, is a very annoying default key for a keyboard/mouse user.

2 - Someone can add options like : 
Load Content -> Latest Folder
History -> Entry -> Use the same last core
History -> Entry -> Use another core

During Game, when press F1 -> Control -> Input
Can press enter in the button i want to reassing and just press the key, or button i want to use like that emulated button. Because need to assing in the Main Menu for Whole core is not very confortable when i just want reassing controls for one specific game for example Mortal Kombat Trilogy for N64.

I mention things like that on my before post -> https://github.com/libretro/RetroArch/issues/12073

3 - NetPlay 
From that day and still today i just still testing things in retroarch, for example i put on a Live USB with Lubuntu 16.04. and i make it work the version i had compile under Slackware 14.2

i notice various things with the NetPlay.
A) You must use the same exact reported version of core for use NetPlay. i try to use Precompiled cores for GNU/Linux and Microsoft Windows, in a Cross-NetPlay and RetroArch reported are not the same core. 

B) The ROM must be exactly the same for make it work
C) The ParaLLEI N64 core, when connect, the emulated controller input does not work any more in precompiled Windows-7 Versions (32 Bits & 64 Bits)

With the 32 Bits in Windows 7 (64 Bits) take a lot of time start the emulation on a core.

Well right now i am thinking in the follow things
A) Change the default shortcut keys, because is very conflicting with custom controls of users just use keyboard/mouse for play. 

B) For the netplay i think is better, if for example the host (incluide on intranet) wait in a lobby, and the host put on the creation of lobby the client limits, and in the some parts of screen put the information like : 

Game -> HomeBrew-Game.md
Checksum (CRC32) -> bc887366
Checksum (MD5) -> 86aa5ea440fdb8d7cf8f2847550609b5
Core -> Genesis Plus GX

UserList, each user on the list had a Negative Emblem if not had the exactly same rom, and Possitive Green when the rom is exactly the host had, and Interrogation Emblem when the user does not had the rom. 

Or the core don't need to be included if retroarch had a way for detected which core are using the host. in the lobby, the host should be a option for share the loaded game (but the core not started) and the client should had a checkbox option for check if that rom must be deleted when retroarch finish normally. 

In the netplay the game never must start if does not connected 1 client. well in this point i don't know if better the user with a button can set "Ready" the retroarch try to make best sync can for netplay. and after launch the core with all clients connected.

Finally i don't know if RetroArch had Intranet Options like the PC-Games when someone start a server, show a list in NetPlay when the user access to NetPlay Menu, and just press Enter/Button to Join and retroarch put in a lobby meanwhile the hosts and clients chats preparing the things need for start the netplay, and that server can be added to a favorite server lists.

Dunno : Why the core must be the exactly reported version ? i know the try of NetCrossPlay i try using 
RetroArch (64 Bits) for GNU/Linux with for example FCEUmm svn 987bcd &
RetroArch (64 Bits) for Windows with for example FCEUmm svn 987cde

does not work because are different cores for retroarch.

Not should be better if the cores had "Netplay Version" in their functions, by this way had a method for not required a very strict version of core for netplay, just the retroarch detect for example "Core Netplay Version : 1.0" independent if the user are using "FCEUmm svn 987bcd" or "FCEUmm svn 987cde".

Another thing i think can be improve is the standardisation of the chd format, specially if i can put a structure like : 

Requiered :
PS1 - Gran Turismo (Euro-Pal M5) [SCES-00984].bin -> Game
PS1 - Gran Turismo (Euro-Pal M5) [SCES-00984].cue -> Cue Sheet

Optionals Files :
Anuncio.jpg or Advert.jpg
ContraPortada.jpg or Back.jpg
Disco.jpg or Disc.jpg or Disc1.jpg
Portada.jpg or Front.jpg or Cover.jpg
Pantallazo.jpg or Screenshot.jpg
PS1 - Gran Turismo (Euro-Pal M5) [SCES-00984].md5 -> Optional File for make
comparation to know if the checksum is correct with internal files.

SCES-00984.sbi -> Sub-Channel Fix for Emulators (Game like Spyro 2 PAL Version need it for the game can be full playable or when you try to enter to certain worlds the game just give an error, like fail opcode or something like that)

Some Games need audio tracks should be specify in the cue file like Overboard! or Mortal Kombat Trilogy, Well i prefer all that required and optional files inside in just one compress file in chd format

and load directly the compress image file without need uncompressed temporally

Finally add the "Netplay" option in the "F1" Menu, and add the user can add "Favorite Server" to a list because when i had trying i must start the server each time, and in client by core and game write again the IP or the Alias of the specific IP (this work fine if the user had manually configuration of hosts file)

Well i am going to making test with cores and netplay. i does not understand why ever i see messages like : 
Server : Errors Assigns Ports 
Client : Session Error in Net Game

Some cores report " Errors Assings Ports" but work fine and sync : 
Bettle PCE 
FCEUmm
Mesen
QuickNes
Snes9x 2002
Bettle SuperFaust

But the follow when i try Netplay the client is inmediatly disconnected if you does not start the game first : 
NestopiaUE
ParaLLEI N64 

When you start a N64 game with ParaLLEI N64 and after start the Netplay Server, 
and after join the client, in a few minutes (between 2 and 5) the controller emulated input stop working.

The sync with ParaLLEI N64 in AdHoc Wifi or with Router/Switch intranet wired, is slow. i try under Windows 7 with Mupen64Plus-Next but well the precompiled core, crashed on 6 Different machines when i try to load a game with that core.

i wait you like minimal just one of this suggestions i made, for improve the retroarch and the users experience.

Well thanks for read all, i need to tell this because i think retroarch is the very best multi-core suite. But some options like default keyboard shortcuts are very bad implement, is like the interface and cores are just for the people had gamepads or joystick. but in the whole world the acquisitive power are very different in each country and because of that not everyone can buy a gamepad/joystick.

**Comment by RobLoach** [comment]
> Change the shortcut keys and make default for example Hold Down Super (Win Logo Key) and the another key or just make the default combinations like Alt+Enter for toggle between Windowed/Full Screen Mode.

Not everyone has the same ideas as you on what the default keys should be. I use different keys than what you had suggested above, for instance. You can generate your own config, save it, and use that config across all your installs. 

> Someone can add options like :
> Load Content -> Latest Folder
> History -> Entry -> Use the same last core
> History -> Entry -> Use another core

Each playlist entry has its own Core setting. You can use different cores for each game.

> Can press enter in the button i want to reassing and just press the key, or button i want to use like that emulated button. Because need to assing in the Main Menu for Whole core is not very confortable when i just want reassing controls for one specific game for example Mortal Kombat Trilogy for N64.

There are Game Overrides for Inputs, allowing you to have different control settings for each game.

> NetPlay

There can be inconsistencies across games and cores which will break states when in Netplay. This setting can be changed in the Netplay settings. Lots have changed over the past year.

> "Favorite Server" to a Netplay list

That would be neat, but IPs do have a tendancy to change, and the netplay list changes pretty often. I'd recommend making a new focused issue for this.

> Well i am going to making test with cores and netplay. i does not understand why ever i see messages like :

I'd recommend reading through the Netplay documenation. You'll need to set up port forwarding to ensure your host is available: https://docs.libretro.com/guides/netplay-faq/

> But the follow when i try Netplay the client is inmediatly disconnected if you does not start the game first NestopiaUE, ParaLLEI N64

As the docs state.....

Does PSX / N64 / Dreamcast / GameCube / Wii / 3DS netplay work?

No, the performance requirements make the current model unsuitable for those.


I'm going to close this, as it can be difficult to parse when there's so many suggestions in one. I'd suggest going on the [Forum](https://forums.libretro.com/) and getting some feedback from the community.
