### ISSUE TITLE
PLEASE MAKE AN WEBCAM OVERLAY (WITH USB WEBCAM ON ANDROID TV DEVICE WITH PROJECTOR, FOR EXAMPLE SOME EPSON PROJECTOR), I PROMISE YOU BUNCH OF HOT CHICKS STREAMING RETROARCH NEXT DAYS

### ISSUE THREAD

**Issue by darvin** [libretro/RetroArch#12089]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by DartPower** [comment]
WHAT???
![image](https://user-images.githubusercontent.com/2005369/109729459-f17b5700-7bc8-11eb-9270-f9904bcbd6ce.png)

**Comment by m4xw** [comment]
We have enough hot chicks.
