### ISSUE TITLE
Mac OS Accessibility: No narration in "metal" build

### ISSUE THREAD

**Issue by pitermach** [libretro/RetroArch#12082]
## Description
Attempting to turn on menu narration in the "metal" build of Retroarch 1.9.0, either by passing --accessibility on the command line or by setting accessibility to true in retroarch.cfg has no effect. This works fine in the regular build.
### Expected behavior
This feature should work fine in both versions

### Actual behavior
No speech.

### Steps to reproduce the bug
Do either of the following:

- install and run retroarch metal at least once so the configuration gets created.
- Edit ~/Library/Application Support/RetroArch/config/retroarch.cfg and set accessibility_enable = "true"
- Alternatively, run the retroarch binary and pass the --accessibility parameter

A third way to reproduce this would be to navigate to accessibility in settings and enable it there, but according to [this post](https://groups.io/g/blind-gamers/message/123356) where I first heard about this bug the option doesn't even show up. I'm not able to verify this myself as I'm completely blind.

### Version/Commit

Confirmed broken in [this build](https://buildbot.libretro.com/stable/1.9.0/apple/osx/x86_64/RetroArch_Metal.dmg), confirmed working in [this one](http://buildbot.libretro.com/stable/1.9.0/apple/osx/x86_64/RetroArch.dmg)

### Environment information

Mac OS 11.3 Public Beta 2 on MacBook Air 2020 (Apple M1 CPU)

**Comment by LibretroAdmin** [comment]
Definitely works fine on latest nightly. Closing.
