### ISSUE TITLE
Unicode pathname support is broken in playlist

### ISSUE THREAD

**Issue by tcbbd** [libretro/RetroArch#12103]
## Steps to reproduce the bug

1. Start a gba rom with VBA-M core
2. Exit the game
3. Check the history playlist, try to open the latest played rom
4. It won't start. The path name is wrong, containing "???".

## Description

The actual behavior is strange:

- If pathname of the ROM contains extended latin, it's fine.
- If pathname of the ROM contains CJK characters, it will only fail in some cases:
    - I've tried a rom named "最终幻想.gba" (final fantasy), the pathname recorded in history becomes "最终幻???gba"
    - But if I rename it to "幻想.gba", the pathname is correctly recorded as "幻想.gba", and I can open it from history playlist
    - I've also tried japanese and korean
        - "ファイナルファンタジー.gba" becomes "ファイナルファンタジ???gba", but  "ファイナルファンタジ.gba" works fine
        - "한국어.gba" becomes "한국???gba", but "한국.gba" works fine
- I've also tried some other scripts, even arabic works fine but thai script will break sometimes.

I've checked the source code to find which piece of code outputs the "???". Now I suspect the unicode support in the json library used by retroarch is broken so it considers some characters as invalid unicode and outputs an "?" for each invalid byte.

### Version/Commit

- RetroArch: Git commit 9086d24

### Environment information

- OS: Windows 10 20H2 (System language: Simplified Chinese)

**Comment by toshixm** [comment]
PR #12459 had been merged yesterday.
Could you confirm using the latest version of nightly build or next stable release?
And if the problem is solved, please close the issue.

**Comment by tcbbd** [comment]
I can confirm this is fixed on nightly build. Close it.
