### ISSUE TITLE
Netplay crashing on Android

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#12139]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Crashes while joining netplay

[Description of the bug]

### Expected behaviour
To run the netplay

[What you expected to happen]

### Actual behavior

[What is actually happening]
It crashed even if i have exact same rom whenever i try to Play netplay it crashes
### Steps to reproduce the bug

1. [First step] go to netplay
2. [Second step] find compatible rom
3. [and so on...] Click and it Will crash I don't this is only happening to me or others also but im using a 6gb ram phone galaxy m51

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch:  latest

### Environment information

- OS: Android
- 
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
We need more information on what core you're doing this with, which game, etc.

**Comment by greyhathacker008** [comment]
Snesx2010
