### ISSUE TITLE
[Suggestion] Option to disable CRC checking in Retroarch menu

### ISSUE THREAD

**Issue by neowitchy** [libretro/RetroArch#12143]
I'm unable to play hacked and homebrew games in Retroarch, fails with incorrect CRC using FBNeo core, original FBNeo works perfectly and has a disable CRC checking option. https://github.com/finalburnneo/FBNeo/pull/721

Even without using this option, FBNeo just throw an error and loads the game, while in Retroarch it don't load.

Version: 1.9.0
OS: Windows 10

**Comment by michaelburgardt** [comment]
Uhm, doesn't a manual scan already do that? (Import Content -> Manual Scan)

**Comment by hizzlekizzle** [comment]
This would need to be exposed by the FBNeo libretro core rather than RetroArch itself. That is, it would need to be a core option that hooks into that same standalone functionality.

**Comment by neowitchy** [comment]
Oh, i assumed it was Retroarch that checked the CRC before loading any core/game. I will post a new issue on https://github.com/libretro/FBNeo

**Comment by neowitchy** [comment]
Moved to https://github.com/libretro/FBNeo/issues/673
