### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#12159]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Can u add an option to load a walkthrough while playing just like in magic dosbox eg any txt or png file so its easy to play eg while playing legend of Zelda its hard to find if u have walkthrough if u can Just add it so it appears there magic dosbox have this feature so pls add it
![IMG_20210316_101236](https://user-images.githubusercontent.com/75823631/111256924-2b744080-8640-11eb-99bd-8c1f152937c4.jpg)

[Try to bisect and tell us when this started happening]

### Version/Commit
You

- RetroArch: [version/commit]
Retroarch Plus latest version
### Environment information

- OS: [The operating system you're running] Android
- Compiler: [In case you are running local builds]

**Comment by eadmaster** [comment]
possible duplicate: 

https://github.com/libretro/RetroArch/issues/5238
