### ISSUE TITLE
[Feature Request] SPen support for menu/cores

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#12172]
## Description

At least on Note 8 (and from searching, all the other pen capable models), spen input doesn't work as expected. Hover is interpreted as a click and drag, and clicking does nothing. 

https://youtube.com/shorts/_-NHSe4c4IA

### Expected behavior

Pen input on Galaxy devices working in RetroArch

### Actual behavior

Mostly ignored save for erroneous hover drags.

### Steps to reproduce the bug

1. Install RetroArch on pen capable Galaxy device
2. Run RetroArch
3. Use SPen and observe behavior

### Bisect Results

From what I can tell from searching, this has never worked correctly in RA.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 4806a34 (buildbot aarch64 nightly)

### Environment information

- OS: Android 9
- Compiler: CLang/LLVM 11.0.5

**Comment by parkerlreed** [comment]
Three years later and I don't know why it's working but it is working.


https://github.com/libretro/RetroArch/assets/841440/9d3196e0-4964-470a-a6c7-e4c884838212

**Comment by sonninnos** [comment]
Excellent, let's close this then.
