### ISSUE TITLE
[Feature Request] screensaver or blanking on rgui

### ISSUE THREAD

**Issue by coredump** [libretro/RetroArch#12185]
## Description

Running rgui as the menu driver on a CRT arcade cabinet is the only way to get an usable 320x240 interface. Unfortunately CRTs are prone to burn-in of images that sit on the screen too much, so having an option to put something moving on the screen after a certain timeout (a screensaver) or blanking the screen would help to alleviate that.

There are the moving menu background animation that helps, but the text still there. Even a way to disappear with the menu text after a certain period would be a good solution.

Currently there is no such feature on the Lakka retroarch. I was told that maybe @jdgleaver would be interested in this one @ the discord chat.

**Comment by jdgleaver** [comment]
I rather like this idea :)

I have a full schedule this week, but I will put it on the TODO list. I need to have a think about the most practical implementation...

**Comment by jdgleaver** [comment]
This should do the trick: https://github.com/libretro/RetroArch/pull/12217
