### ISSUE TITLE
Input overlays touchscreen issue with scaled display

### ISSUE THREAD

**Issue by JonnyMe** [libretro/RetroArch#12205]
## Description

On postmarketOS, when running a game with input overlays on a scaled screen, overlays are correctly drawn but input doesn't adapt to display scale. This result in impossibility to interact with the game.

### Expected behavior

Pressing an overlay button triggers input.

### Actual behavior

When running a game with input overlays, pressing an overlay button doesn't trigger any input. I tried building RetroArch on postmarketOS with Phosh UI and got this behaviour. Looking a bit at the code I found that applying this change to `retroarch.c` touch is correctly binded to the overlay graphic:

```diff
@@ -21465,6 +21465,9 @@ static void input_overlay_poll(
    x /= ol->active->mod_w;
    y /= ol->active->mod_h;
 
+   x = x * DISPLAY_SCALE_FACTOR;
+   y = y * DISPLAY_SCALE_FACTOR;
+
    for (i = 0; i < ol->active->size; i++)
    {
       float x_dist, y_dist;
```

Where `DISPLAY_SCALE_FACTOR` is the scale factor set in Phosh settings (https://wiki.postmarketos.org/wiki/Phosh#Screen_Scaling).

### Steps to reproduce the bug

On a postmarketOS device run `retroarch -L PATH_TO_YOUR_CORE -c PATH_TO_CFG --appendconfig custom.cfg YOUR_ROM`, where `custom.cfg` is something like:

```
input_overlay = "PATH_TO_OVERLAY"
```

### Version/Commit

- RetroArch: `be3960e2be7d5bcfe4f10666020d6a40897b3f18`

### Environment information

- OS: postmarketOS
- Compiler: compiling with `retroarch-build.sh` script from `libretro-super`

**Comment by FlexingTiger** [comment]
Same on android. You can pull request to source.

**Comment by JonnyMe** [comment]
I'll work on a patch today then, thank you!

**Comment by JonnyMe** [comment]
I just noticed the same happens for the menu, changed pull request status to draft, I'd like to use the same scaling option for menu too, I guess that probably setting a more generic key is better for this issue.

**Comment by JonnyMe** [comment]
Closing this as related pull request got merged, thank you!
