### ISSUE TITLE
Display issues on iPhone 6 Plus

### ISSUE THREAD

**Issue by andonuts** [libretro/RetroArch#1221]
(using RetroArch 1.0.0.2.1 from the libretro Cydia repo)

When using RetroArch on my iPhone 6 Plus (this issue may also occur on an iPhone 6, can't verify), the in-emulation display looks like this:

![img_0365](https://cloud.githubusercontent.com/assets/6581437/4896511/67e3a362-63fb-11e4-9881-6db25941d18e.PNG)
The overlay's visuals do not scale to the screen, but the touch areas do for everything but the directional pad.

Tested with various cores for a few different systems, and various overlays getting the same results for all.

**Comment by twinaphex** [comment]
Can you try again from source?

**Comment by Mateusz-Winnov** [comment]
Same issue for me, should be easy to fix via Xcode. I wouldn't mind a separate version of Retroarch exclusively for iPhone 6 Plus.

I think the only temporary solution is to buy some kind of blue tooth wireless controller.

**Comment by twinaphex** [comment]
Should now be fixed thanks to some help from @maddox.

**Comment by maddox** [comment]
:dancer:

**Comment by warmbear666** [comment]
hey there !!

take the solution for retroarch (:


INSTRUCTIONS:
1: Open Retroarch
2: load up a game on any emulator
3. Press the down arrow on the top middle of the screen.
4. Press "Core"
5. Scroll all the way down and press video
6: Change Aspect Ratio Index to 7
7: Make sure Integer Scale is off
8: Change custom viewport X to 5
9: Change custom viewport y to -190
10: Change custom viewport width to 1475
11: Change custom viewport height to 840
