### ISSUE TITLE
Launching the gpSP Core Breaks the App (Vita)

### ISSUE THREAD

**Issue by FraneloGorriky** [libretro/RetroArch#12218]
## Description

Launching the gpSP core causes RetroArch to crash and opening the app again leads to an error screen stating that there was an 'undefined instruction exception.' The only way to get the app to launch is to delete retroarch.cfg

### Steps to reproduce the bug

1. Select the content to load
2. Select the gpSP core

### Version/Commit

- RetroArch: 1.9.1

### Environment information

- OS: Playstation Vita

**Comment by Oroborus420** [comment]
Im getting a similar error when Launching the gpSP core in RetroArch. Opening Retroarch again leads to an error screen stating (C2-12828-1) Saved Core File Succeeded
ux0:data/psp2core- 1617369504-0x0000162273-gpsp_libreto.self.psp2dmp 
I have not deleted the retroarch.cfg file as of yet. hoping there is another fix for this. 

**Steps to reproduce**

Select the content to load
Select the gpSP core

**Version/Commit**
RetroArch: 1.9.1

**Environment information**
OS: Playstation Vita

**Comment by Girotin** [comment]
Did u added the GBA bios file to the "system" folder?
