### ISSUE TITLE
Disabling "input_remap_binds_enable" breaks input in 1.9.1

### ISSUE THREAD

**Issue by mpharoah** [libretro/RetroArch#12228]
## Description

In RetroArch 1.9.1, if `input_remap_binds_enable` is set to `false`, then most inputs fail to bind. In the case of N64, only the C buttons are bound, and nothing else works, even when using keyboard controls. Reverting to RetroArch 1.9.0 fixes the issue, as does enabling `input_remap_binds_enable` and pointing it to an empty directory.

### Expected behavior

Input should still work normally, but just ignore any rebinds. This is the behaviour in 1.9.0

### Actual behavior

Most inputs do not bind at all.

### Steps to reproduce the bug

 * Change `input_remap_binds_enable` from `true` to `false` in `retroarch.cfg`
 * Open any N64 ROM in either ParallelN64 or mupen64plus-next
 * Press anything that isn't a C button and observe nothing happen

### Environment information

Both Linux and Windows 64-bit

**Comment by twinaphex** [comment]
Hi, see if this fixes it -

https://github.com/libretro/RetroArch/commit/66ad300515b2e849f2f2ad3f3a07b2ca236e7a59

**Comment by pyromancer5** [comment]
same i rerolled to 1.9.0 because of this...help

**Comment by mpharoah** [comment]
I built from master on Linux, and can confirm that the fix is working

**Comment by pyromancer5** [comment]
what do you mean with you built from master? sry but am a normal user doesnt understand alot tell me how to fix am using win 10 download it again or go to some setting ?

**Comment by hizzlekizzle** [comment]
@pyromancer5 it's been added to the RetroArch codebase as of yesterday, so the latest nightly build should have it in there already, if you can try that.

**Comment by pyromancer5** [comment]
still wont work :( am using the zip 64 bit one so i can unzip and put it on the old one to update and remain my setting been doing this all time...just tried it still controllers broke and wont work with n64 games

**Comment by pyromancer5** [comment]
think am going to wait for next update 1.9.2 or 2.0 since 1.9.0 works perfect still i must say thank you retroarch team for this rly rly rly awsome emulator

**Comment by mpharoah** [comment]
If you're mainly interested in just N64, you can try [Parallel Launcher](https://parallel-launcher.ca/), which is a launcher I made for N64 games that uses RetroArch as a backend and is how I originally discovered this bug. It has a workaround for this bug, so it works with 1.9.1

**Comment by twinaphex** [comment]
OK so the issue is fixed for @mpharoah but not for @pyromancer5 ? Where is the discrepancy coming from here?

**Comment by mpharoah** [comment]
Doesn't look like operating system should matter at all. Might not be in the Windows nightly build or pyro accidentally downloaded the stable one instead of the nightly one?

**Comment by pyromancer5** [comment]
i download this one  https://buildbot.libretro.com/stable/1.9.1/windows/x86_64/RetroArch.7z   
unzip copy past on old one folder...i use retro for alot of platform n64 ps1 nes snes mame etc... 1.9.1 doesnt work with n64 games anymore its like the half right of the controller working but dpad left analog almost half left doesnt i was using sdil driver for input on 1.9.0 with ds4 window and worked like charm...but in 1.9.1 i have to change the driver to xinput to be able to make controller to work ofc am using it in bluetooth not wired... am not using the installer retroarch

**Comment by mpharoah** [comment]
I tested by building master from source on Linux using the SDL input driver for gamepad and the X input driver for keyboard. If changing the input driver fixed it, then it might be a different defect than this one, since this bug also affected keyboard input.

**Comment by pyromancer5** [comment]
i know retro can be used without ds4 windows but i like to use ds4 windows since am using my emulators with bigbox ds4 windows make my controller work with all emulators retroarch / dolphin/ rpcs3/ yuzu etc...u just set it up with all of them and thats it ...it was working so good with 1.9.0 but n64 input doesnt with 1.9.1 wish it get fixed so i can enjoy the new stuff in 1.9.1..thanks anyway

**Comment by twinaphex** [comment]
@pyromancer5 Yeah so you tested the wrong version, you need to test the latest nightlies instead.

**Comment by mpharoah** [comment]
Oh yeah, you downloaded the stable version which doesn't have this fix. Try this one instead:
https://buildbot.libretro.com/nightly/windows/x86_64/2021-04-07_RetroArch.7z

**Comment by pyromancer5** [comment]
ok how can i get nightlies but the one wich i unzip and drop not install cant find it on the website? link plz

**Comment by pyromancer5** [comment]
oh ty brb trying it

**Comment by pyromancer5** [comment]
hi again..well sry still no luck tried everything with ds4 windows without ds4 windows changed every driver still the same n64 game cant use half the controller

**Comment by twinaphex** [comment]
At this point I'm inclined to believe you are just testing the wrong thing or reporting on something unrelated, and you should probably wait until the next stable.

**Comment by pyromancer5** [comment]
@mpharoah dude plz just updated to 1.9.2 from 1.9.0 hoping this n64 half input got fixed but still nope...i want it to work just like in 1.9.0 since the new 1.9.2 look so cool...i want to fix it without using any third softwere...did u able to make it work? if you did then help plz
