### ISSUE TITLE
Auto-scan does not work (PC Linux)

### ISSUE THREAD

**Issue by Rstation4** [libretro/RetroArch#12221]
Linux Mint 20.1 Cinnamon
Cinnamon Version 4.8.6
Retroarch: (Flatpak) 1.9.0 and 1.9.1

Ive tried updating the database via the online updater and still not getting any roms that are scanned added to the playlists. roms for systems are MAME2015,FBNeo,GBA.

**Comment by hizzlekizzle** [comment]
Scanning works for me in Linux using a regular package from the PPA and the snap package.

Note: arcade scanning is always weird and you're best off doing a manual scan and feeding it a DAT instead of doing a database scan for these games.

**Comment by Rstation4** [comment]
Should I close this issue, I ended up updating  RA and using a app image in which the scan function works.

**Comment by hizzlekizzle** [comment]
You can, or maybe rename it to include 'flatpak', since that seems to be the only one that's affected.

**Comment by RobLoach** [comment]
Make sure the cores are installed? The Flatpak has gone through some updates since 1.9.0 too... Going to transfer this one.
