### ISSUE TITLE
[Core] Can't load latest Genesis GX Core

### ISSUE THREAD

**Issue by cnoizem** [libretro/RetroArch#12237]
## Description
Downloading latest .dll core for windows 10 x64 or x86 

### Expected behavior

Core should load
### Actual behavior

Can't load core
1. https://bitbucket.org/eke/genesis-plus-gx/src/master/builds/
2. Load core using window view or placing .dll inside core folder

1.9.1 - Windows 10 64bit

**Comment by cnoizem** [comment]
P.S: It doesn't work on 32-bit version either

**Comment by bslenul** [comment]
You should move that issue to Eke's GitHub/Bitbucket, the core from the online updater/buildbot loads perfectly fine ;)
And you should probably include the error in your issue:
```
[ERROR] Error(s): %1 is not a valid Win32 application.
```
