### ISSUE TITLE
Overlay and Button remapping cause conflicting input.

### ISSUE THREAD

**Issue by laserlambert** [libretro/RetroArch#12240]
## Description

Playing on 1.9.1 on android. if you swap two buttons A and B in the controls then when pressing the overlay A button, both an A button press and the remapped B button will register, instead of just the A and, and the same goes for the B button, registering both an A and B button. effectively making remapping useless when using any overlay, and across all cores.

### Expected behavior

remap A to B. and B to A. Press B on the overlay expecting to register an A input

### Actual behavior

A and B are both registered as the same input from the overlay button.

**Comment by laserlambert** [comment]
I guess I can also point out that you can't unmap buttons from overlays either, not that big a deal, but the original part was. Is this not a game breaking "uninstall the 1.9.1 and install 1.9.0 again" issue for others  on android? It kinda sucks.

**Comment by hizzlekizzle** [comment]
I was under the impression remapping never worked with overlays...?

**Comment by laserlambert** [comment]
It definitely works on whatever nightly version that I put on my phone back in november of last year. but whatever happened between then and now has made it not work.
