### ISSUE TITLE
Implement a "previous frame" button

### ISSUE THREAD

**Issue by geajack** [libretro/RetroArch#12251]
RetroArch has rewind support. I can assign a key to rewind the emulator when I hold it. However, if I want to rewind just one frame at a time, I find I have trouble holding the button for a short enough period of time for it to only do one frame. I'd like a separate hotkey mapping to rewind exactly one frame (or rather, to the previous frame stored by RetroArch). So that it rewinds one frame when the key is *released*, not while it's pressed.

**Comment by sonninnos** [comment]
This happens currently when mixing pause with rewind, just like frame stepping forward.
