### ISSUE TITLE
Segmentation fault (core dumped) when loading control remaps

### ISSUE THREAD

**Issue by zcal** [libretro/RetroArch#12258]
## Description

RetroArch crashes when loading a control remap file.

### Expected behavior

RetroArch should load the control remap file and continue functioning as normal.

### Actual behavior

RetroArch crashes immediately upon loading a control remap file.  It happens regardless of the core being used.  Those I've tested and use regularly are Beetle PSX, Beetle Saturn, Mupen64Plus-Next, and bsnes-mercury Accuracy.

The console reports only the following: 
`Segmentation fault (core dumped)`

### Steps to reproduce the bug

1. Load a game in any core (I'm experiencing this in Beetle PSX, Beetle Saturn, Mupen64Plus-Next, and bsnes-mercury Accuracy).
2. Open the RetroArch menu, go to Quick Menu > Controls > Load Remap File, select a file and press Enter.

### Bisect Results

This appears to have begun happening on upgrade from version 1.9.0 to 1.9.1

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.1
- Git Version: cf6ca2a47f

### Environment information

- OS: Arch Linux

**Comment by twinaphex** [comment]
Try to see if this fixes it -

https://github.com/libretro/RetroArch/commit/aa0a9f18d552c572c034d04c5735b75dbf7d5435

**Comment by zcal** [comment]
@twinaphex Haven't had a chance to test yet, but will do so in the next couple of days.  Thanks!

**Comment by zcal** [comment]
@twinaphex Confirmed fixed.

Git Version: 6b021f8d14
Build Date: April 17 2021
