### ISSUE TITLE
Vulkan API won't switch resolutions (Output)

### ISSUE THREAD

**Issue by PlayNeth** [libretro/RetroArch#12269]
## Description

Vulkan won't switch resolutions properly

### Expected behavior

Switch to desired resolution

### Actual behavior

It does it for 3 seconds then goes back to the previous resolution

### Steps to reproduce the bug

1. Settings
2. Output>choose Vulkan
3. Try to change the resolution to a different one that you are on

### Bisect Results

Started happened ever since i updated to RA 1.9.1, it wasn't an issue on 1.9.0

### Version/Commit

- RetroArch: 1.9.1

### Environment information

- OS: Windows 10

**Comment by twinaphex** [comment]
I can confirm this issue. This is rather bad.

@alphanu1 Got any ideas on what might have changed on the display server end that could cause this?

**Comment by alphanu1** [comment]
@PlayNeth is this while using CRTSwitchRes or just manually choosing a resolution from within the the video options.

@twinaphex from a dispserv point of view everything seems as though its working fine. It seems that the video state changes are not updating after a resolution change. This did work before. CRTSwitchRes is working with OpenGL but after a resolution change RA does not update its video state. Instead it stays the same width, height and aspect ratio. So, you end up with only part of RA on the screen, depending on the systems starting resolution.

**Comment by PlayNeth** [comment]
@alphanu1 The latter

**Comment by alphanu1** [comment]
@twinaphex Its looks like there might possible be a video driver issue for both GL and Vulkan

**Comment by twinaphex** [comment]
I have bisected the issue and I found this causes the issue -

https://github.com/libretro/RetroArch/commit/dea73a5595b171807ca584e9d278d2fe327699dc

would be great if @sonninnos could provide a fix.

**Comment by twinaphex** [comment]
So these two here - 

'Reinit after selecting, which fixes Vulkan not changing Hz in fullscreen
Stop Vulkan from crashing after successfully changing Hz below the current running core fps (60 -> 50), or when no core is running, by creating a new swapchain on mode change'

I have never been able to reproduce on Windows. But it seems this PR that attempts to fix these causes its own issues which did not exist before.

**Comment by twinaphex** [comment]
I've decided to revert this for now until a better PR is submitted that fixes this issue. Hope it won't be too long for that.

**Comment by alphanu1** [comment]
@PlayNeth are you able to check this? I am unable to use Vulkan my end.

**Comment by PlayNeth** [comment]
@alphanu1 just did, same outcome still

**Comment by alphanu1** [comment]
@PlayNeth just checking but did you download and compile the latest build?

**Comment by PlayNeth** [comment]
@alphanu1 latest nightly pretty sure

**Comment by alphanu1** [comment]
@twinaphex doesn't look like this PR is the issue after all. 

I would bisect myself. However, I do not have a Vulkan compatible card. So I would not be able to test or reproduce this issue.

**Comment by PlayNeth** [comment]
Oh yeah little update: I think the nightly build i was using was the one from the 17th which didn't have the reversion implemented. Tried out the 19th one and it seems to be fixed now, Vulkan has been working flawlessly again

**Comment by sonninnos** [comment]
Looks like this can be closed.
