### ISSUE TITLE
Something doesn't work well (Lord of the Sword)

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#12276]
Hey guys.
There is a game I like a lot. his name is : "Lord of the Sword" (Master System).

I tried to finish this game my whole childhood. But the game is difficult, there was no map and I was a very bad player !!! Hahahaha

I decided to play it! I searched among the cores of the retroarch which would be ideal for the Master System.
The result was that I chose the "Genesis-Plus-GX" core.

However I started to play the game but something was not right. I started to pay a little more attention and realized that  In the Master System video game I had, when hitting the opponent he blinked on the screen quickly, indicating that he was hit and then disappeared.
Using the "Genesis-Plus-GX" emulator this does not happen. Which makes the whole experience bad, because the impression of a downed opponent does not exist like that. Something is missing. Whoever played the original video game knows what I'm talking about.
Out of curiosity I downloaded the Mednaffen emulator. And I was very happy when the game ran exactly the way I had experienced it in my childhood.

https://user-images.githubusercontent.com/16063712/114954740-94162f00-9e31-11eb-9450-b48726557059.mp4
<img width="800" alt="A" src="https://user-images.githubusercontent.com/16063712/114954750-95dff280-9e31-11eb-8a16-81431f3fed85.png">

https://user-images.githubusercontent.com/16063712/114955305-cf652d80-9e32-11eb-9021-21a9d0f2f8bb.mp4

I got in touch with the "Genesis-Plus-GX" core developer and he sent me this vídeo above where he plays using this emulator. But not within Retroarch. And the game worked the way I remembered it was. He said the issue could be resolved through some configuration in the retroarch menus. Neither he or I know what it could be.

For if you are curious to play the game for 2 minutes in both "Genesis-Plus-GX" and "Mednaffen" emulators you will see what I am talking about. .

Could someone help me?

**Comment by hizzlekizzle** [comment]
I tried it with GenPlusGX, GearSystem and Picodrive via RetroArch. GenPlusGX and GearSystem both acted the same here, with most enemies flashing after getting hit but the sword guys on the ground disappearing immediately (usually). In re-watching the video from eke, it looks to be the same as what I'm seeing here.

I'm not really sure what setting could be interfering here. I guess maybe something related to vsync?

**Comment by AlanRibas** [comment]
In the tests I did here using all the emulators you commented on, they all behaved the same way.
You said that the enemies that are in the air when hit disappear the right way but I know the game and I know it wasn't like that. Really the enemies when they are in the air and are hit blink a little but not the same as the video game master system showed. If you play using the "GenPlusGX" emulator and then Mednaffen you will see what I meant. The difference is subtle but it exists.

I tried to change the VSync settings here and there was even a small improvement for the enemies that are in the air. But those present on the ground are not.

**Comment by bslenul** [comment]
That's how it looks for me on RetroArch with Genesis Plus GX core:

https://user-images.githubusercontent.com/33353403/115033987-4f3ed680-9ecb-11eb-8583-c9b0e53c17a2.mp4

I don't know the game so no idea if this is correct, but it feels normal.

**Comment by AlanRibas** [comment]
> That's how it looks for me on RetroArch with Genesis Plus GX core:
> 
>  2021-04-16.15-45-18.mp4 
> I don't know the game so no idea if this is correct, but it feels normal.

Except for the sound part, that to stay the same you have to leave the chip of the master system deactivated that's right !!!
Is correct!!!
That's the way it should be !!!
Would we have a comparison of configurations to find out what differs between my configuration and yours ??

**Comment by AlanRibas** [comment]
Good afternoon ekeeke.
I was doing some more comparisons between the emulation of "Genesis Plus GX" in RetroArch and the emulator alone called "mednafen".
And I realized the following.

Using "Genesis Plus GX":
When we walk with the character, the scene that passes by moves in a locked way. I can see the picture of the scene walking in a non-fluid way.

Using Mednafen:
The background scenario moves smoothly. The only thing I noticed was that the vegetation that we found right when we left the first city, it becomes a darker color during the character's movement and returns to normal color when the scenery stops walking.

Could you test it out there and tell me if you find the same phenomenon?

> That's how it looks for me on RetroArch with Genesis Plus GX core:
> 
>  2021-04-16.15-45-18.mp4 
> I don't know the game so no idea if this is correct, but it feels normal.

Good afternoon.
I was doing some more comparisons between the emulation of "Genesis Plus GX" in RetroArch and the emulator alone called "mednafen".
And I realized the following.

Using "Genesis Plus GX":
When we walk with the character, the scene that passes by moves in a locked way. I can see the picture of the scene walking in a non-fluid way.

Using Mednafen:
The background scenario moves smoothly. The only thing I noticed was that the vegetation that we found right when we left the first city, it becomes a darker color during the character's movement and returns to normal color when the scenery stops walking.

The video you uploaded is very short and there is no time to see if the same thing happens in it.

Could you test it out there and tell me if you find the same phenomenon?

**Comment by hizzlekizzle** [comment]
> it becomes a darker color during the character's movement and returns to normal color when the scenery stops walking

That sounds like interframe blending / motion-blur.

**Comment by AlanRibas** [comment]
> > it becomes a darker color during the character's movement and returns to normal color when the scenery stops walking
> 
> That sounds like interframe blending / motion-blur.

But how could I fix this?
