### ISSUE TITLE
Linux mice not detected with udev input driver

### ISSUE THREAD

**Issue by Delerme** [libretro/RetroArch#12279]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When using udev input drivers, no mice are detected and printed out in `--verbose` mode

### Expected behavior

As explained in [this retropie guide](https://retropie.org.uk/docs/Spinners,-Trackballs,-Lightguns,-and-other-Mouse-Devices/), using the `--verbose` flag, all mice connected should be added and logged

### Actual behavior

The verbose output says `udev` input driver is found, but no statements for mice or keyboard are printed. If a joystick is plugged in, a line is printed for pad 0

The mice are present in /dev/input, confirmed working with `cat`, can be used for the desktop and split into separate pointers with `xinput`. Permissions are set up according to [the docs](https://docs.libretro.com/guides/input-joypad-drivers/)

Verbose log is attached:
[out.txt](https://github.com/libretro/RetroArch/files/6328000/out.txt)

### Steps to reproduce the bug

1. Set input driver to udev, ensure permissions are correct
2. Plug in multiple mice, confirm /dev/input entries and `cat` to confirm functionality
3. Execute retroarch with `--verbose` flag, note no mouse or keyboard lines are printed

### Bisect Results

(skipping this unless requested)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.1 (udev input driver, vulcan display driver, tested w/ gl too)

### Environment information

- OS: Arch linux
- Display server: X
- WM: i3

**Comment by markwkidd** [comment]
This pending PR may address your issue, or at least improve the usefulness of the logs being generate: https://github.com/libretro/RetroArch/pull/12536

**Comment by markwkidd** [comment]
@Delerme that PR has been merged.

Are you compiling RetroArch from source? If so could you update and recompile to try this with the latest build?

**Comment by Sanaki** [comment]
Was in the neighborhood, so I tested this myself on Mint 19.3. Can confirm no mouse support via udev input driver.
```
[INFO] [udev]: Added Device Keyboard G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD (/dev/input/event8).
[INFO] [udev]: Added Device Keyboard G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD (/dev/input/event13).
[INFO] [udev]: Added Device Keyboard USB Laser Game Mouse (/dev/input/event15).
[INFO] [udev]: Added Device Keyboard Valve Software Steam Controller (/dev/input/event18).
[INFO] [udev]: Added Device Keyboard  (/dev/input/mouse3).
[INFO] [udev]: Added Device Keyboard AT Translated Set 2 keyboard (/dev/input/event4).
[INFO] [udev]: Added Device Mouse G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD (/dev/input/event9).
[INFO] [udev] udev_input_add_device SKIPPED : /dev/input/mouse1 (Inappropriate ioctl for device).
[INFO] [udev]: Added Device Mouse USB Laser Game Mouse (/dev/input/event14).
[INFO] [udev] udev_input_add_device SKIPPED : /dev/input/mouse2 (Inappropriate ioctl for device).
[INFO] [udev]: Added Device Mouse Valve Software Steam Controller (/dev/input/event18).
[INFO] [udev] udev_input_add_device SKIPPED : /dev/input/mouse3 (Inappropriate ioctl for device).
[INFO] [udev]: Added Device Mouse DELL0802:00 06CB:7E92 Mouse (/dev/input/event30).
[INFO] [udev] udev_input_add_device SKIPPED : /dev/input/mouse4 (Inappropriate ioctl for device).
[INFO] [udev]: Added Device Mouse DELL0802:00 06CB:7E92 Touchpad (/dev/input/event31).
[INFO] [udev] udev_input_add_device SKIPPED : /dev/input/mouse5 (Inappropriate ioctl for device).
[INFO] [udev]: Added Device Mouse SynPS/2 Synaptics TouchPad (/dev/input/event7).
[INFO] [udev] udev_input_add_device SKIPPED : /dev/input/mouse0 (Inappropriate ioctl for device).
```

**Comment by grant2258** [comment]
> [INFO] [udev]: Added Device Mouse G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD (/dev/input/event9).
> [INFO] [udev]: Added Device Mouse USB Laser Game Mouse (/dev/input/event14).
> [INFO] [udev]: Added Device Mouse Valve Software Steam Controller (/dev/input/event18).
> [INFO] [udev]: Added Device Mouse DELL0802:00 06CB:7E92 Mouse (/dev/input/event30).
> [INFO] [udev]: Added Device Mouse DELL0802:00 06CB:7E92 Touchpad (/dev/input/event31).
> [INFO] [udev]: Added Device Mouse SynPS/2 Synaptics TouchPad (/dev/input/event7).

you acutally have 7 mice detected you need to set the index to the appropriate one in the port controls or the first mouse listed will be used

**Comment by Sanaki** [comment]
I don't use `udev` for input myself, I basically just did driveby testing between other tasks. With `x` as my input driver, I can click/right click/scroll to navigate the UI via xmb. Soon as I change it to udev, no input goes through. And no, I can't post anything from xinput, since it doesn't exist on Linux.

**Comment by grant2258** [comment]
Ah x as input driver doesn't uses multi mouse so all mice are on port 0 you would need to set the right index for udev  to work on Linux. I'm using Linux myself xinput just lists your devices thanks for info.

**Comment by Sanaki** [comment]
Ah, apologies, I thought you were asking for me to run a check with the xinput driver. Wasn't aware of the xinput utility. Manually setting mouse index to 1 does indeed allow it to control the menu, so we're good there. Just for the sake of completeness, here you go:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD	id=12	[slave  pointer  (2)]
⎜   ↳ G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD Consumer Control	id=13	[slave  pointer  (2)]
⎜   ↳ USB Laser Game Mouse                    	id=16	[slave  pointer  (2)]
⎜   ↳ USB Laser Game Mouse Consumer Control   	id=18	[slave  pointer  (2)]
⎜   ↳ Valve Software Steam Controller         	id=19	[slave  pointer  (2)]
⎜   ↳ DELL0802:00 06CB:7E92 Mouse             	id=21	[slave  pointer  (2)]
⎜   ↳ DELL0802:00 06CB:7E92 Touchpad          	id=22	[slave  pointer  (2)]
⎜   ↳ SynPS/2 Synaptics TouchPad              	id=27	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Sleep Button                            	id=10	[slave  keyboard (3)]
    ↳ G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD	id=11	[slave  keyboard (3)]
    ↳ G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD System Control	id=14	[slave  keyboard (3)]
    ↳ G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD	id=15	[slave  keyboard (3)]
    ↳ USB Laser Game Mouse                    	id=17	[slave  keyboard (3)]
    ↳ Integrated_Webcam_HD: Integrate         	id=20	[slave  keyboard (3)]
    ↳ Intel HID events                        	id=23	[slave  keyboard (3)]
    ↳ Intel HID 5 button array                	id=24	[slave  keyboard (3)]
    ↳ Dell WMI hotkeys                        	id=25	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=26	[slave  keyboard (3)]
    ↳ G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD Consumer Control	id=28	[slave  keyboard (3)]
    ↳ USB Laser Game Mouse Consumer Control   	id=29	[slave  keyboard (3)]
    ↳ Valve Software Steam Controller         	id=30	[slave  keyboard (3)]
```
```
[INFO] [udev]: Added Device Keyboard#0 G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD (/dev/input/event8) .
[INFO] [udev]: Added Device Keyboard#1 G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD (/dev/input/event13) .
[INFO] [udev]: Added Device Keyboard#2 USB Laser Game Mouse (/dev/input/event15) .
[INFO] [udev]: Added Device Keyboard#3 Valve Software Steam Controller (/dev/input/event18) .
[INFO] [udev]: Added Device Keyboard#4  (/dev/input/mouse3) .
[INFO] [udev]: Added Device Keyboard#5 AT Translated Set 2 keyboard (/dev/input/event4) .
[INFO] [udev]: Added Device mouse#0 G.SKILL Corporation G.SKILL RIPJAWS KM780 MX GAMING KEYBOARD (/dev/input/event9) .
[INFO] [udev]: Added Device mouse#1 USB Laser Game Mouse (/dev/input/event14) .
[INFO] [udev]: Added Device mouse#2 Valve Software Steam Controller (/dev/input/event18) .
[INFO] [udev]: Added Device mouse#3 DELL0802:00 06CB:7E92 Mouse (/dev/input/event30) .
[INFO] [udev]: Added Device mouse#4 DELL0802:00 06CB:7E92 Touchpad (/dev/input/event31) .
[INFO] [udev]: Added Device mouse#5 SynPS/2 Synaptics TouchPad (/dev/input/event7) .
```

**Comment by grant2258** [comment]
Thanks for the confirmation it's working for you appreciated

**Comment by Delerme** [comment]
> 
> 
> @Delerme that PR has been merged.
> 
> Are you compiling RetroArch from source? If so could you update and recompile to try this with the latest build?

I wasn't, but I can try that sometime this week and confirm

**Comment by Delerme** [comment]
Works perfectly, thanks!

**Comment by markwkidd** [comment]
Excellent, please close this issue when you have a chance.
