### ISSUE TITLE
Overrides applying fastforward_ratio disable fast forward

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#12280]
## Description

When fastforward_ratio is 0 (uncapped) in the base config and non-0 in an override, fast forward stops functioning (equivalent to fastforward_ratio of 1) on game load. When fastforward_ratio is non-0 in the base config, the override value is ignored.

### Expected behavior

Preferred:
fastforward_ratio in overrides applies correctly.

Alternative:
fastforward_ratio is unable to apply in overrides and is simply ignored.

### Steps to reproduce the bug

1. Set Settings > Frame Throttle > Fast-Forward Rate to 0.0x
2. Save base configuration.
3. Load a game.
4. Change the same setting to anything non-0 (other than 1.0x, which would hide the issue) and save an override.
5. Close and reopen the game.
6. Attempt to fast forward and observe no change in speed.

### Version/Commit

- RetroArch: 1811bd6885
* Also tested with stable 1.9.1 (PPA, cf6ca2a47f).

### Environment information

- OS: Linux Mint 19.3 x86_64, kernel 5.4.0-72-generic
- Compiler: GCC 10.1.0

**Comment by Jamiras** [comment]
Probably related to #11300.

**Comment by Sanaki** [comment]
This is indeed the same issue. Nicely spotted. Closing as duplicate.
