### ISSUE TITLE
compressed isos x RetroArch

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#12289]
Is it possible, through configurations inside RetroArch, to make compressed isos uncompressed the moment we choose them to play?
I have some systems here on my computer, games for PS1, PS2 and several others. However, all games were compressed with Winrar (* .zip).
If it is possible to enable this function I would like. If this function does not exist, would it be possible to implement it?
I also use another frontend for games run by an emulator called "GameEx". This Gameex has in its settings the option to activate the decompression of games of a certain system. When this option is checked in advance, at the moment we choose a compressed game, the decompression is done before the file is taken to the emulator to run it.

**Comment by hizzlekizzle** [comment]
RetroArch can/will decompress zipped single-file optical discs, but it decompresses them to your disk drive (which takes time--quite a bit in the case of multi-GB games--and puts wear-and-tear on your hardware) and then cleans up after itself on exit, which can be a problem if the core crashes, as it will never clean up after itself.

Most cores that support optical disc images also support compression in some form, usually CHD (PCSX2 supports CISO and dolphin supports some weird dolphin-specific compression) as a safer and faster alternative.

**Comment by AlanRibas** [comment]
And where is this configuration in Retroarch ???  Well, I don't think it's automatic, right?  since the systems I have here with games in iso and compressed in .zip do not start.

**Comment by hizzlekizzle** [comment]
It should work with the 'browse archive' option from 'load content'. If it's failing, you may need to go to settings > directory and set a cache directory.

**Comment by AlanRibas** [comment]
> It should work with the 'browse archive' option from 'load content'. If it's failing, you may need to go to settings > directory and set a cache directory.

I tried here but the emulation didn't start ... I took some pictures of my settings ... could you tell me what's wrong?
I tried to run a "playstation 1" game using the "PSX HW beetle".

First I checked the cache:


<img width="480" alt="1" src="https://user-images.githubusercontent.com/16063712/115468623-b9c47f00-a209-11eb-890d-aada106bb552.png">


I selected the "Action Man" game and i clicked "upload file":

<img width="482" alt="2" src="https://user-images.githubusercontent.com/16063712/115469065-5ab33a00-a20a-11eb-8a2b-87dd4f46c88d.png">


Then I chose the core ("PSX HW beetle"): But he did not open the game by showing the message "FAILURE TO LOAD CONTENT".

What did I forget to do?

**Comment by hizzlekizzle** [comment]
> I chose the .cue file 
Multi-file images, such as bin/cue, will always fail, which is one of the reasons we suggest using CHD, etc. if you need compression instead of archives like zip.

**Comment by AlanRibas** [comment]
> > I chose the .cue file
> 
> Multi-file images, such as bin/cue, will always fail, which is one of the reasons we suggest using CHD, etc. if you need compression instead of archives like zip.

Understand.
Does compression for CHD cause any kind of incompatibility? No matter how small?


Which program do you suggest for converting to .CHD?

**Comment by AlanRibas** [comment]
I downloaded the program "chdman_m2k".

I will use it to convert the isos of the Ps1, Ps2, TURBO GRAFX CD and DREAM CAST systems.

Thank you very much anyway.
