### ISSUE TITLE
SaveState not working with Dosbox Pure Core on Version 1.9.1

### ISSUE THREAD

**Issue by TradeDraft** [libretro/RetroArch#12293]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Save States comes up with Error Message

### Expected behavior

It would save the Save State

### Actual behavior

Comes up with Error and does nothing else

### Steps to reproduce the bug

1. Load Up Dosbox Game into Dosbox Pure Core
2. Enter Game
3. Press Save Sate Hotkey or do it thru the Menu

### Bisect Results

Soon as I started using 1.9.1 from 1.9.0 Stable Releses
### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.1

### Environment information

- OS: [Windows 10]

Error Messages:

> 
> [INFO] [GLCore]: VSync => OFF
> [INFO] [WGL]: wglSwapInterval(0)
> [ERROR] [State]: Failed to save state to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\states\Jagged Alliance (1994).state".
> [ERROR] [State]: Failed to save state to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\states\Jagged Alliance (1994).state".
> [ERROR] [State]: Failed to save state to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\states\Jagged Alliance (1994).state".
> [ERROR] [State]: Failed to save state to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\states\Jagged Alliance (1994).state".
> [ERROR] [State]: Failed to save state to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\states\Jagged Alliance (1994).state".
> [ERROR] [State]: Failed to save state to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\states\Jagged Alliance (1994).state".
> [ERROR] [State]: Failed to save state to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\states\Jagged Alliance (1994).state".
> [INFO] [Core]: Paused.

and

> [INFO] [CORE]: Using content: E:\Video Games\PC Games\eXoDOS\Games\Jagged Alliance (1994).zip.
> [INFO] [Cheats]: Save game-specific cheatfile: E:\Video Games\RetroArch\Cheats\Cheats for RA (30-11-2020)\DOSBox-pure\Prince of Persia (1990).cht
> [INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 05 seconds.
> [INFO] Saving runtime log file: E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\playlists\logs\DOSBox\Prince of Persia (1990).lrtl
> [INFO] [Core]: Unloading game..
> [INFO] [Core]: Unloading core..
> [INFO] [Core]: Unloading core symbols..
> [INFO] [Core Options]: Saved core options file to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\config\DOSBox-pure\DOSBox-pure.opt"
> [INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
> [INFO] RetroArch 1.9.1 (Git cf6ca2a)
> [INFO] === Build =======================================
> [INFO] CPU Model Name: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
> [INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
> [INFO] Built: Mar 28 2021
> [INFO] Version: 1.9.1
> [INFO] Git: cf6ca2a
> [INFO] =================================================
> [INFO] [Input]: Found input driver: "dinput".
> [INFO] [Core]: Loading dynamic libretro core from: "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\cores\dosbox_pure_libretro.dll"
> [INFO] [Overrides]: No core-specific overrides found at "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\config\DOSBox-pure\DOSBox-pure.cfg".
> [INFO] [Overrides]: No content-dir-specific overrides found at "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\config\DOSBox-pure\Games.cfg".
> [INFO] [Overrides]: No game-specific overrides found at "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\config\DOSBox-pure\Jagged Alliance (1994).cfg".
> [INFO] [Environ]: GET_LOG_INTERFACE.
> [INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
> [INFO] [Remaps]: Remap directory: "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\config\remaps".
> [INFO] [Overrides]: Redirecting save file to "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\saves\Jagged Alliance (1994).srm".
> [INFO] [Overrides]: Redirecting save state to "E:\VCD\Jagged Alliance (1994).state".
> [INFO] [Environ]: SET_KEYBOARD_CALLBACK.
> [INFO] [Environ]: SET_FRAME_TIME_CALLBACK.
> [INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
> [INFO] [Environ]: SYSTEM_DIRECTORY: "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\system".
> [INFO] Core requested VFS version >= v3, providing v3
> [INFO] [Environ]: SET_CORE_OPTIONS.
> [INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
> [INFO] [Environ]: SET_PIXEL_FORMAT: XRGB8888.
> [INFO] [Environ]: GET_PERF_INTERFACE.
> [libretro INFO] [DOSBOX LOG] 64 is outside the allowed range 1-63 for variable: memsize.
> It has been set to the closest boundary: 63.
> [INFO] [Environ]: SYSTEM_DIRECTORY: "E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\system".
> [libretro INFO] [DOSBOX LOG] Memory sizes above 31 MB are NOT recommended.
> [libretro INFO] [DOSBOX LOG] Stick with the default values unless you are absolutely certain.
> [libretro INFO] [DOSBOX STATUS] Program: DOSBOX - Cycles: -1 - Frameskip: 0 - Paused: 0
> [libretro INFO] [DOSBOX STATUS] Program: DOSBOX - Cycles: 3000 - Frameskip: -1 - Paused: 0
> [libretro INFO] [DOSBOX LOG] MIDI: Opened device:tsf
> [libretro INFO] [DOSBOX LOG] DOS keyboard layout loaded with main language code US for layout us
> [INFO] [Environ]: GET_SAVE_DIRECTORY.
> [libretro INFO] [DOSBOX STATUS] Program: PUREMENU - Cycles: -1 - Frameskip: -1 - Paused: 0
> [INFO] [Environ]: SET_MEMORY_MAPS.
> [INFO] ndx flags ptr offset start select disconn len addrspace
> [INFO] 001 M1A1bc 000000001951e950 00000000 00000000 00000000 00000000 0009E6F0
> [INFO] 002 M1A1bc 000000001951d040 00000000 0009E6F0 00000000 00000000 00001910
> [INFO] 003 M1A1bc 00000000195bd040 00000000 000A0000 00000000 00000000 03E60000
> [INFO] [Environ]: SET_SUPPORT_ACHIEVEMENTS: yes.
> [INFO] [Environ]: SET_CONTROLLER_INFO.
> [INFO] [Environ]: SET_INPUT_DESCRIPTORS:
> [INFO] Version of libretro API: 1
> [INFO] Compiled against API: 1
> [INFO] [Cheats]: Load game-specific cheatfile: E:\Video Games\RetroArch\Cheats\Cheats for RA (30-11-2020)\DOSBox-pure\Jagged Alliance (1994).cht
> [INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
> [INFO] [Video]: Video @ 1411x795
> [INFO] [GLCore]: Found GL context: wgl
> [INFO] [GLCore]: Detecting screen resolution 1920x1080.
> [INFO] [WGL] extensions: WGL_ARB_buffer_region WGL_ARB_create_context WGL_ARB_create_context_no_error WGL_ARB_create_context_profile WGL_ARB_create_context_robustness WGL_ARB_context_flush_control WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_multi[INFO] [WGL]: Adaptive VSync supported.
> [INFO] [WGL]: wglSwapInterval(0)
> [INFO] [GLCore]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 1050/PCIe/SSE2.
> [INFO] [GLCore]: Version: 4.6.0 NVIDIA 456.71.
> [INFO] [GLCore]: Using resolution 1411x795
> [INFO] [Joypad]: Found joypad driver: "dinput".
> [INFO] [GLCore]: Loading stock shader.
> [INFO] [slang]: Building pass #0 (N/A)
> [INFO] [GLCore]: Not using frame history.
> [INFO] [GLCore]: Not using framebuffer feedback.
> [INFO] [Video]: Found display server: win32
> [INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
> [INFO] [Display]: Found display driver: "glcore".
> [INFO] [Font]: Using font rendering backend: freetype.
> [INFO] [Font]: Using font rendering backend: freetype.
> [INFO] [Font]: Using font rendering backend: freetype.
> [INFO] [Font]: Using font rendering backend: freetype.
> [INFO] [Font]: Using font rendering backend: freetype.
> [INFO] [Font]: Using font rendering backend: freetype.
> [INFO] [SRAM]: SRAM will not be saved.
> [INFO] [Playlist]: Loading history file: [E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\content_history.lpl].
> [INFO] [Playlist]: Loading history file: [E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\content_music_history.lpl].
> [INFO] [Playlist]: Loading history file: [E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\content_video_history.lpl].
> [INFO] [Playlist]: Loading history file: [E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\content_image_history.lpl].
> [INFO] [Playlist]: Loading favorites file: [E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\content_favorites.lpl].
> [INFO] [GLCore]: VSync => OFF
> [INFO] [WGL]: wglSwapInterval(0)
> [INFO] [Playlist]: Written to playlist file: E:\Video Games\RetroArch\RetroArch 1.9.1 (64 Bit)\content_history.lpl
> [DOSBOX] Resolution changed 320x200 @ 60.000Hz AR: 1.33333 => 640x400 @ 60.000Hz AR: 1.60000
> [INFO] [Environ]: SET_GEOMETRY: 640x400, aspect: 1.600.
> [WARN] [Environ]: SET_MESSAGE_EXT: Unable to save/load state while start menu is open
> [INFO] Core does not support save states.
> [WARN] [Environ]: SET_MESSAGE_EXT: Unable to save/load state while start menu is open
> [INFO] Core does not support save states.
> [WARN] [Environ]: SET_MESSAGE_EXT: Unable to save/load state while start menu is open
> [INFO] Core does not support save states.
> [WARN] [Environ]: SET_MESSAGE_EXT: Unable to save/load state while start menu is open
> [INFO] Core does not support save states.
> [WARN] [Environ]: SET_MESSAGE_EXT: Unable to save/load state while start menu is open
> [INFO] Core does not support save states.
> [WARN] [Environ]: SET_MESSAGE_EXT: Unable to save/load state while start menu is open
> [INFO] Core does not support save states.
> [WARN] [Environ]: SET_MESSAGE_EXT: Unable to save/load state while start menu is open
> [INFO] Core does not support save states.
> [INFO] [Core]: Paused.

**Comment by RobLoach** [comment]
Is `states` directory existing and writable?
