### ISSUE TITLE
Resolution is not saved (Mesen Core)

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#12291]
I was configuring the core of the MESEN emulator in the retroarch.
I made several changes and saved them in the end. But the resolution refuses to change.
More than once I changed the resolution that is currently 1920x1080 to 1280x720.
The moment the game is open the resolution is changed. But just leaving retroarch to lose that configuration.

**Comment by twinaphex** [comment]
Can you try turning off Windowed Fullscreen Mode? Settings -> Video -> Fullscreen Mode. I think when this mode is enabled, it acts a 'borderless fullscreen mode', so it will use your desktop's resolution at startup.

**Comment by AlanRibas** [comment]
I tried it here ... Several times .... But the game starts at the same resolution as the one my monitor supports. 1920x1080.
In fact RetroArch starts at that resolution. I believe the game only accompanies ..... hahahaha

**Comment by AlanRibas** [comment]
I talked to a person called "Sanaki". In a post related to the MESEN core. He told me that the Mesen emulator has no resolution change setting. Perhaps then the resolution established by RetroArch will not influence the Mesen core.
