### ISSUE TITLE
3DS: Graphics widgets support

### ISSUE THREAD

**Issue by civwar** [libretro/RetroArch#12309]
Hi. Installed the latest retroarch on my 3ds and can't activate graphics widgets.This option is missing in on-screen notification menu.
How to do it?

**Comment by hizzlekizzle** [comment]
I don't think it supports it. The screen isn't really high enough res to do them properly, I don't think.

**Comment by civwar** [comment]
Thanks for your answer, but this is indicated in the features of the new version of retroarch:

1.9.1
3DS: Graphics widgets support
3DS: On error, only init gfx on salamander build. This prevents graphical issues if the gfx is already initialized. Which should always be the case if called from a running core
3DS: Update error applet
3DS: Enable online Core Updater
3DS: Guard threading
3DS: Allow sideways screen rotation
3DS: Enable threading and add a threaded audio driver..............

**Comment by hizzlekizzle** [comment]
Hmm, yeah, looks like it was merged here:
https://github.com/libretro/RetroArch/commit/b9849f78f7b026fb69843b15a30718013c0244b9

**Comment by civwar** [comment]
it's hard),thanks for finding this.

**Comment by MrHuu** [comment]
The feature hasn't been enabled yet.
It can be enabled as-is, but it will show the wrong colors for loaded images (achievement badges).

Overlays had the same issue. https://github.com/libretro/RetroArch/commit/8df97a0c75addddf574a1ae916158bc0cc78cc1b
It can be solved by calling `video_driver_set_rgba()`, which will swap red and blue colors.

This is added, but guarded by `HAVE_OVERLAY`. Currently both features have to be enabled to display properly.

**Comment by hizzlekizzle** [comment]
ohhh, mystery solved. Thanks for chiming in, @MrHuu :)
