### ISSUE TITLE
Add system in RetroArch

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#12316]
Please add the "Amstrad GX4000" system so that instead of a folder it has the picture of the video game.

<img width="960" alt="A" src="https://user-images.githubusercontent.com/16063712/115973749-cad4ff00-a52d-11eb-9c5c-ebffa650b591.png">

**Comment by hizzlekizzle** [comment]
Please open this issue at the assets repo: https://github.com/libretro/retroarch-assets

**Comment by AlanRibas** [comment]
> Please open this issue at the assets repo: https://github.com/libretro/retroarch-assets


I did as you suggested. Thanks.
