### ISSUE TITLE
Auto Shader Delay Is not working in update 1.91

### ISSUE THREAD

**Issue by spikeyxx** [libretro/RetroArch#12314]
## Description

Auto Shader Delay Is not working in update 1.91

### Expected behavior

When set to a number, there should be a delay, then shader presets should automatically load.

### Actual behavior

Shader presets do not load at all when any value is set other than "0"

### Steps to reproduce the bug

1. Set Shader Delay to anything other than 0.
2. Load Content

### Version/Commit

- RetroArch: 1.91 Stable Release

### Environment information

- OS: Windows 10 21H2

**Comment by hizzlekizzle** [comment]
Yeah, confirmed. This is frustrating, as we *just* fixed this a couple of weeks before releasing 1.9.1 and it apparently re-broke in that short amount of time. :/

**Comment by spikeyxx** [comment]
Still broken on 1.9.2

**Comment by hizzlekizzle** [comment]
Hmm, yeah, doing it for me too again. I'll look into it.
