### ISSUE TITLE
MAME2015 core

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/RetroArch#12322]
What happen to the MAME2015 core?  I can't download it is it ever coming back?

**Comment by hizzlekizzle** [comment]
It still exists, but I don't know if anyone is planning to start building it again or not: https://github.com/libretro/mame2015-libretro

**Comment by Cibomatto2002** [comment]
Thanks for the link I hope someone one day will bring it back it even if it never gets updated

**Comment by Cibomatto2002** [comment]
All I see is the source code. I hope someone brings it back it was a good core even if it never gets updated as long as it keeps working in retroarch that would be fine.

**Comment by hizzlekizzle** [comment]
AFAIK, it should still work fine. It's just not being built on our buildbot.

**Comment by Cibomatto2002** [comment]
Ok thank you
