### ISSUE TITLE
Compile issue on Linux - cheevos error

### ISSUE THREAD

**Issue by alphanu1** [libretro/RetroArch#12330]
## Description

Unable to compile on Linux (Ubuntu 20.04)

[What you expected to happen]

Compile without issues.

[What is actually happening]

Compile fails with the following error.

```
make: *** No rule to make target 'cheevos/../deps/rcheevos/include/rconsoles.h', needed by 'obj-unix/release/cheevos/cheevos.o'. Stop.
make: *** Waiting for unfinished jobs....
```

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.1
- fresh Pull from git as of 28/04/2021 10:20 UTC
- 8466a213e8

### Environment information

- OS: Ubuntu 20.04

### Workaround

Compile with cheevos disabled

`./configure --disable-cheevos`

@twinaphex

**Comment by gouchi** [comment]
I can't reproduce the issue using commit [2702ce6](https://github.com/libretro/RetroArch/commit/2702ce693b95f6b2656ad72b947a029f65716eb1) and gcc 10.2.0.

**Comment by Jamiras** [comment]
`rconsoles.h` was renamed `rc_consoles.h`. You probably just need to do a clean build (`make clean && make`).

I'm assuming "fresh pull" doesn't mean "new clone".

**Comment by alphanu1** [comment]
@Jamiras I did just that and all is working.
