### ISSUE TITLE
READ_CORE_MEMORY returns READ_CORE_RAM

### ISSUE THREAD

**Issue by bmarwell** [libretro/RetroArch#12344]
## Description

sending READ_CORE_MEMORY returns READ_CORE_RAM.

### Expected behavior

returns READ_CORE_MEMORY

### Actual behavior

returns READ_CORE_RAM

### Steps to reproduce the bug

1. send `READ_CORE_MEMORY 40FFC0 32`
2. wait for packages

Response bytes: [82,69,65,68,95,67,79,82,69,95,82,65,77,32,48,32,48,48,10]
`READ_CORE_RAM 0 00`

### Bisect Results

new feature since 1.9.1

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.0/d232c6e from flatpak

### Environment information

- OS: Ubuntu 20.04
- Compiler: flatpak build

Slightly related to https://github.com/libretro/RetroArch/issues/12262

**Comment by bmarwell** [comment]
Must have been fixed.
In a more recent version it returns

response: [82,69,65,68,95,67,79,82,69,95,77,69,77,79,82,89,32,52,48,102,102,99,48,32,45,49,32,110,111,32,100,97,116,97,32,102,111,114,32,100,101,115,99,114,105,112,116,111,114,10]
`READ_CORE_MEMORY 40ffc0 -1 no data for descriptor`

**Comment by Jamiras** [comment]
git doesn't recognize `d232c6e` as a valid commit, but `d06bd7f` (when the feature was first added) does return `READ_CORE_MEMORY` as expected, so I'm not sure what would have been fixed, or when it would have been fixed.

```
(HEAD detached at d06bd7fffd):~/source/RetroArch$ echo -n "READ_CORE_MEMORY 7e04ee 1" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 7e04ee 00
```

```
master:~/source/RetroArch$ echo -n "READ_CORE_MEMORY 7e04ee 1" | nc -u -w1 localhost 55355
READ_CORE_MEMORY 7e04ee 00
```

You've also commented that it "must have been fixed". Is there an issue here, or can it be closed?

**Comment by bmarwell** [comment]
Yup, can be closed, sorry -- hit the wrong button.
