### ISSUE TITLE
Updated to Version 1.9.2, but Retroarch on PS Vita Shows Version 1.9.1 Installed

### ISSUE THREAD

**Issue by dothackjhe** [libretro/RetroArch#12343]
## Description

A glitch whereby an installed version of Retroarch misrepresents what version it actually should be, e.g., instead of 1.9.1, it should be 1.9.2. This is under the context of installing the latest version of Retroarch in VPK format (1.9.2, 300+ Mb big).

### Expected behavior

Version installed should appear as "1.9.2."

### Actual behavior

It shows version 1.9.1 instead.

### Steps to reproduce the bug

1. Install Retroarch 1.9.2 VPK.
2. Run the emulator.

### Version/Commit

- RetroArch: 1.9.2

### Environment information

- OS: PS Vita

**Comment by danielristic** [comment]
Same here on my Vita, and also on a PSP. Does not seem to be the case on a mac installation, though.
