### ISSUE TITLE
Autofire

### ISSUE THREAD

**Issue by Cibomatto2002** [libretro/RetroArch#12357]
i know on autofire you have to set up a hot key then press the button you want the autofire to be on could we see a way to set it without having to hit the hotkey everytime we want autofire?  i don't really want to hold the hot key every time i want autofire on i'm having to hold to buttons to get autofire. 

Windows 10

rg-351

**Comment by jedinjapan** [comment]
You can release the hotkey once Turbo Mode is started. For instance if L was your hotkey, pressing A and tapping L would switch to Turbo Mode until you release A.

However, some cores also offer Turbo as a control function of the core itself, so check the Controls remap function when content is loaded to see if binding the retropad to a core-specific turbo option is available. This is present in some NES, Arcade, and Genesis cores I believe.

**Comment by Cibomatto2002** [comment]
Thanks for the replay I know some emulators have autofire I  wondered if someone could add a option in retroarch to always have turbo when pressed without the hotkey always needed to be press every time something like how game controllers do it press the turbo button then press what button you want turbo on the button would always be turbo when pressed until you turned off the turbo with the turbo button.

There is no Super Nintendo emulator that I know of that has turbo. I use snes9x current on the RG-351

**Comment by eadmaster** [comment]
classic turbo is now available https://github.com/libretro/RetroArch/pull/16239
