### ISSUE TITLE
Import content is broken in version 1.9.2

### ISSUE THREAD

**Issue by dezraj** [libretro/RetroArch#12366]
## Description
I've downloaded the portable (zip) version of Retroarch 1.9.2 and unzipped it to a new folder, that is, I made a clean install. When I look for content in my computer, nothing is found in my directories, even though they are the same ones I use in my previous version of Retroarch (v. 1.9.0). I've tried it with different folders and different video game systems.

It looks like this feature seems to have been broken somehow in latest version.

### Expected behavior
Retroarch was supposed to populate the playlists with the games it found in the directories.

### Actual behavior
No playlists are created.

### Steps to reproduce the bug
Load content -> Playlists -> Import content -> Scan directory, point to a directory to be scanned, let the scan end.

### Bisect Results
It started with version 1.9.2. Don't know if it would happen with 1.9.1 though because I skipped this one.

### Version/Commit
I currently don't have access to the laptop which I was trying it to check the commit info, but I downloaded from the Retroarch download page, here: https://buildbot.libretro.com/stable/1.9.2/windows/x86_64/RetroArch.7z 

### Environment information
- OS: Windows 10

**Comment by hizzlekizzle** [comment]
Do you have a core that can run the content you're scanning installed and/or have updated the databases?

**Comment by dezraj** [comment]
> Do you have a core that can run the content you're scanning installed and/or have updated the databases?

No, I haven't any cores installed. Wasn't it supposed to create the playlists regardless of the installed cores?

As for the database, I'm regularly updating them through the "update" option when using Retroarch 1.9.0. But for this particular version, I just used the one which is sent within the emulator in the zip version.

Thank you so much for your reply.

**Comment by hizzlekizzle** [comment]
AFAIK, you *do* need the cores installed, as that was one of the optimizations made to avoid having to check every single database for every scan.

**Comment by dezraj** [comment]
> AFAIK, you _do_ need the cores installed, as that was one of the optimizations made to avoid having to check every single database for every scan.

That's new to me. So the way this feature is currently it's not so intuitive for new users. I guess Retroarch could display a warning message about the absence of cores before the scanning process so we understood the results.

Thank you so much again.
