### ISSUE TITLE
how to update?? (noob)

### ISSUE THREAD

**Issue by nr1995** [libretro/RetroArch#12360]
Hi!  Noob here.
I'm on v1.9.1 here and just wondering
how the heck to update to v1.9.2
since the menu option disappeared.
At least I think it did.
Am I missing something here?
Thanks,
N

**Comment by hizzlekizzle** [comment]
If you used the installer, just install the new version over the top. If you use the "portable" 7zip bundle, unzip it and then copy/paste on top of your existing installation directory, merging and overwriting any conflicts. It should be pretty painless, but make sure you backup your install directory first, in case anything goes pear-shaped.

**Comment by nr1995** [comment]
> If you used the installer, just install the new version over the top. If you use the "portable" 7zip bundle, unzip it and then copy/paste on top of your existing installation directory, merging and overwriting any conflicts. It should be pretty painless, but make sure you backup your install directory first, in case anything goes pear-shaped.

No more integrated updaters?

**Comment by hizzlekizzle** [comment]
Not at the moment, no. We plan to make a new update routine from within the application that's not dependent on the Qt desktop interface, but it's not implemented yet.
