### ISSUE TITLE
Retroarch is assigning a wrong IP through upnp when I use netplay

### ISSUE THREAD

**Issue by markkkun** [libretro/RetroArch#12361]
## Description

I can activate netplay and it started without any problem but anyone could connect to my server in Windows 10. 

### Expected behavior

To play online through netplay without any problems

### Actual behavior

No one can connect to my server.

### Steps to reproduce the bug

1. Start the rom
2. Activate netplay
3. Try to play online

### Bisect Results

When netplay server starts, it starts OK. So I tried to monitorize the port assignation by upnp.... I've download miniupnp client to windows to do it.

When I list open ports through upnp, I could check that the port assignation was against a wrong IP. As you can check, LAN ip is different than the IP that is assosciated to port 55435. In fact, this IP doesn't exists in my system.

Here's the upnp client log.

```
upnpc : miniupnpc library test client, version 1.9.
 (c) 2005-2014 Thomas Bernard.
Go to http://miniupnp.free.fr/ or http://miniupnp.tuxfamily.org/
for more information.
List of UPNP devices found on the network :
 desc: http://192.168.0.1:80/RootDevice.xml
 st: urn:schemas-upnp-org:device:InternetGatewayDevice:1

Found valid IGD : http://192.168.0.1:80/WANIPConnection
Local LAN ip address : 192.168.0.90
Connection Type : IP_Routed
Status : Connected, uptime=412735s, LastConnectionError : ERROR_NONE
  Time started : Sat May 01 01:18:31 2021
MaxBitRateDown : 100000000 bps (100.0 Mbps)   MaxBitRateUp 100000000 bps (100.0 Mbps)
ExternalIPAddress = X.X.X.X
 i protocol exPort->inAddr:inPort description remoteHost leaseTime
 -------
 --------
 2 TCP 55435->169.254.84.35:55435 'retroarch' '0.0.0.0' 3600
GetGenericPortMappingEntry() returned 713 (SpecifiedArrayIndexInvalid)
```

I tried other applications that uses upnp too, like transmission and it associates correctly the IP:PORT.

I've disabled Windows Firewall and problem persists.
I tried in other Windows 10 laptop and I have the same problem.

If I delete via upnpclient the port assignation, and then I create the correct rule (with correct ip:port) it works ok!

I can reproduce it in 1.9.2 and 1.9.1. I haven't tried old versions.

### Version/Commit

- RetroArch: [1.9.2/bc23d07]

### Environment information

- OS:Windows 10 Home 20H2

**Comment by Cthulhu-throwaway** [comment]
@LibretroAdmin Outdated as hell and I don't even need to tell you how so. Should be closed as fixed.
