### ISSUE TITLE
Incorrect 'aspect_ratio_index' saved in override with RGUI's 'Lock Menu Aspect Ratio' set

### ISSUE THREAD

**Issue by cmitu** [libretro/RetroArch#12387]
When RetroArch is configured with the RGUI menu driver and RGUI's configuration for _Lock Menu Aspect Ratio_ is set to `Integer Scale`, then saving a core/game override will save the wrong `aspect_ratio_index` (without the `aspect_ration_index` actually being changed).

With the default settings RetroArch,`aspect_ratio_index` is _Core provided_ (22), opening the RGUI seems to change the `aspect_ratio_index` to _Custom_ (23) for the period when the RGUI menu is opened. Seems this is done intentionally in the  **rgui_toggle** function:

https://github.com/libretro/RetroArch/blob/66c77af4a6083eef4bbee81c02d98b235010b0f8/menu/drivers/rgui.c#L6815-L6824

While the original video aspect ratio is restored when the RGUI menu is closed, using the menu to save an override will save an incorrect `aspect_ration_index` (i.e. _Custom_ instead of _Core Provided_).

### RetroArch: [version/commit]
Tested with RetroArch 1.9.2, tested also with older versions (1.9.1 or 1.8.8)
The RGUI options controlling the menu display (aspect ration, screen size, etc.) were initially introduced by @jdgleaver in https://github.com/libretro/RetroArch/pull/8211.

### Environment information

- OS: Raspberry Pi OS 10 (based on Debian Buster)
- Compiler: [In case you are running local builds]

**Comment by jdgleaver** [comment]
Hell's bells... This is a very serious issue, and I can't believe no one has ever noticed it before....

The aspect ratio changes are a necessary evil - there is literally no other way to make the `Lock Menu Aspect Ratio` setting work (not without rewriting the gfx drivers for every platform, which is entirely impractical). But this bug/oversight is not acceptable. I will try to think of a workaround. Please bear with me - this is tricky/ugly stuff to deal with...

**Comment by cmitu** [comment]
> Please bear with me - this is tricky/ugly stuff to deal with...

No rush, I understand the limitations imposed by the gfx drivers (and the way RGUI is implemented) and that's not an easy fix.
Thank you for taking a look.

**Comment by jdgleaver** [comment]
This turned out to be not so tricky after all: #12393 :)
