### ISSUE TITLE
CRTSwitchRes broken in 1.9.2

### ISSUE THREAD

**Issue by LarsenDX** [libretro/RetroArch#12391]
## Description
Enabling CRTSwitchRes (15kHz or 31 kHz) has no effect at all.

### Expected behavior
Expected behavior should be as per version 1.9.0 where it worked as advertised. In fact, restoring the 1.9.0 binary from my backups and running it restores the feature in its entirety.

### Actual behavior
Monitor index set to 0 (auto). CRTSwitchRes set to 15kHz. RA does not switch resolution. It is like it is not calling xrandr at all. The log does not show any messages related to xrandr/randr calls. Also tried with a clean retroarch.cfg config as well. No dice. Tried different monitor indices. No dice.

### Version/Commit
1.9.2

Package: retroarch
Version: 1.9.2-r202105021336-bc23d070de-110~ubuntu20.10.1
Priority: optional
Section: otherosfs
Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>

### Environment information
OS:
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy

Kernel:
Linux 5.8.0-53-generic
DC disabled: GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amdgpu.dc=0"

GPU: 
[GL]: Vendor: X.Org, Renderer: AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.38.0, 5.8.0-53-generic, LLVM 11.0.0).

Screen: 
Sony BVM 2010p 

Hookup:
DVI-I ->VGA adapter -> UMSA - Ultimate SCART Adapter

DisplayPort-0 disconnected (normal left inverted right x axis y axis)
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 connected primary 700x480+0+0 (normal left inverted right x axis y axis) 0mm x 0mm

retroarch log:

[INFO] RetroArch 1.9.2 (Git bc23d070de)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: May  2 2021
[INFO] Version: 1.9.2
[INFO] Git: bc23d070de
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 2560x240.
[INFO] [GLX]: Window manager is Openbox.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 2.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 700, H = 480.
[INFO] [GLX]: Using windowed fullscreen.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [GL]: Vendor: X.Org, Renderer: AMD Radeon (TM) R9 380 Series (TONGA, DRM 3.38.0, 5.8.0-53-generic, LLVM 11.0.0).
[INFO] [GL]: Version: 4.6 (Compatibility Profile) Mesa 20.2.6.
[INFO] [GL]: Using resolution 700x480
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [udev]: Pad #0 (/dev/input/event3) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event3) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[ERROR] [DBus]: Failed to suspend screensaver via DBus.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [SRAM]: SRAM will not be saved.
[INFO] [Playlist]: Loading history file: [/home/ra-eval/.config/retroarch/content_history.lpl].
[INFO] [Playlist]: Loading history file: [/home/ra-eval/.config/retroarch/content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [/home/ra-eval/.config/retroarch/content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [/home/ra-eval/.config/retroarch/content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [/home/ra-eval/.config/retroarch/content_favorites.lpl].
[INFO] [GL]: VSync => ON
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [GL]: VSync => ON
[INFO] [GLX]: glXSwapInterval(1)
[INFO] [PulseAudio]: Pausing.
[INFO] [Video]: Setting refresh rate to: 60.000 Hz.
[INFO] [Video]: Setting refresh rate to: 60.099 Hz.
[INFO] [PulseAudio]: Unpausing.
[INFO] [Config]: Saved new config to "/home/ra-eval/.config/retroarch/retroarch.cfg".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [PulseAudio]: Pausing.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 2.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

**Comment by LarsenDX** [comment]
Looking into this I see it is adding 15kHz modlines but they are either wrong or it does not tell xrandr to run them.


lubuntu@lubuntu:~$ xrandr 
Screen 0: minimum 320 x 200, current 1024 x 768, maximum 16384 x 16384
DisplayPort-0 disconnected primary (normal left inverted right x axis y axis)
HDMI-A-0 disconnected (normal left inverted right x axis y axis)
DVI-D-0 disconnected (normal left inverted right x axis y axis)
DVI-I-1 connected 1024x768+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1024x768      60.00* 
   800x600       60.32    56.25  
   848x480       60.00  
   640x480       59.94  
  CRT1 (0x72e) 49.799MHz -HSync -VSync
        h: width  2560 start 2666 end 2859 total 3180 skew    0 clock  15.66KHz
        v: height  240 start  242 end  245 total  261           clock  60.00Hz

**Comment by LarsenDX** [comment]
Booted _without_ amdgpu.dc=0 and hooked up a screen to the HDMI port. Same result. Adds a bunch of modelines that look wrong and doesn't switch to any of them. 

$ xrandr 
Screen 0: minimum 320 x 200, current 1920 x 1440, maximum 16384 x 16384
DisplayPort-0 disconnected primary (normal left inverted right x axis y axis)
HDMI-A-0 connected 1920x1440+0+0 (normal left inverted right x axis y axis) 316mm x 237mm
   1920x1440     60.00* 
   1920x1080     60.00    59.94  
   1600x1200     70.00  
   1280x1024     85.02    75.02  
   1280x960      85.00  
   1152x864      75.00  
   1280x720      60.00    59.94  
   1024x768      85.00    75.03    70.07    60.00                                                                                                                                            
   832x624       74.55                                                                                                                                                                       
   800x600       85.06    72.19    75.00    60.32                                                                                                                                            
   720x480       60.00    59.94                                                                                                                                                              
   640x480      102.18    75.00    72.81    60.00    59.94                                                                                                                                   
   720x400       70.08                                                                                                                                                                       
DVI-D-0 disconnected (normal left inverted right x axis y axis)                                                                                                                              
DVI-D-1 disconnected (normal left inverted right x axis y axis)                                                                                                                              
  CRT1 (0x742) 49.799MHz -HSync -VSync                                                                                                                                                       
        h: width  2560 start 2666 end 2859 total 3180 skew    0 clock  15.66KHz                                                                                                              
        v: height  240 start  242 end  245 total  261           clock  60.00Hz                                                                                                               
  d_mo (0x743) 13.850MHz -HSync -VSync Interlace                                                                                                                                             
        h: width   700 start  742 end  801 total  867 skew    0 clock  15.97KHz                                                                                                              
        v: height  480 start  490 end  496 total  533           clock  59.94Hz                                                                                                               
  CRT2 (0x744)  6.139MHz -HSync -VSync                                                                                                                                                       
        h: width   320 start  330 end  357 total  392 skew    0 clock  15.66KHz                                                                                                              
        v: height  240 start  242 end  245 total  261           clock  60.00Hz                                                                                                               
  CRT3 (0x745) 74.698MHz -HSync -VSync                                                                                                                                                       
        h: width  3840 start 4000 end 4289 total 4770 skew    0 clock  15.66KHz                                                                                                              
        v: height  240 start  242 end  245 total  261           clock  60.00Hz                                                                                                               
  CRT4 (0x746)  6.139MHz -HSync -VSync                                                                                                                                                       
        h: width   320 start  330 end  357 total  392 skew    0 clock  15.66KHz                                                                                                              
        v: height  240 start  242 end  245 total  261           clock  60.00Hz                                                                                                               
  CRT5 (0x747) 31.116MHz -HSync -VSync                                                                                                                                                       
        h: width  1600 start 1666 end 1787 total 1987 skew    0 clock  15.66KHz                                                                                                              
        v: height  240 start  242 end  245 total  261           clock  60.00Hz
  CRT6 (0x748)  6.139MHz -HSync -VSync
        h: width   320 start  330 end  357 total  392 skew    0 clock  15.66KHz
        v: height  240 start  242 end  245 total  261           clock  60.00Hz

**Comment by LarsenDX** [comment]
For those seeing the same issue and wanting a working CRTSwitchRes, I recommend building 1.9.2 with the 1.9.0 dispserv_x11.c code.

# add-apt-repository ppa:libretro/stable
# apt-get update
# apt-get install git build-essential

$ git clone https://github.com/libretro/RetroArch.git retroarch
# apt-get build-dep retroarch

$ git fetch --tags
$ git checkout tags/v1.9.2

Fetch v1.9.0 dispserv_x11.c and replace gfx/display_servers/dispserv_x11.c .

$ cd retroarch
$ ./configure
$ make clean
$ make -j4

**Comment by AlexFolland** [comment]
I see the pull request that fixes this has been merged, and I read the details in there, and it sounds good.  Is this ready to be closed?

**Comment by LibretroAdmin** [comment]
I'm going to assume this can be closed.
