### ISSUE TITLE
Crash on flatpak & alpine install on postmarket acer-picasso

### ISSUE THREAD

**Issue by arthurlutz** [libretro/RetroArch#12415]
First off congrats to the project for running on such a diverse spectrum of platforms ! 

## Description

On https://wiki.postmarketos.org/wiki/Acer_Iconia_Tab_A500_(acer-picasso)

with flatpak : 
```
acer-picasso:~$ flatpak run org.libretro.RetroArch
libGL error: failed to create dri screen
libGL error: failed to load driver: tegra
Unable to find target for this triple (no targets are registered)
```

with apk alpine package (a window appears and vanishes) : 
```
acer-picasso:~$ retroarch
libGL error: failed to create dri screen
libGL error: failed to load driver: tegra
sh: xdg-screensaver: not found
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
'+d16' is not a recognized feature for this target (ignoring feature)
Illegal instruction
```

### Expected behavior

start and run retroarch

### Actual behavior

Crashes before starting

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.9.2 
- RetroArch flatpak : 1.9.3

### Environment information

- OS: alpine/postmarketos

**Comment by arthurlutz** [comment]
Sorry for the noise I think this is simple because there is no 3D accelleration (or it's partial with llvmpipe) reading https://wiki.postmarketos.org/wiki/Nvidia_Tegra_2_(tegra20) and https://gitlab.com/postmarketOS/pmaports/-/issues/884 it seems that this is not an issue with retroarch. 

Closing this, but if there is a way to run retroarch without 3D acceleration I'd take the tip... read some stuff about gl1 etc, but can't seem to find a way to configure that without starting retroarch (yet).

**Comment by gouchi** [comment]
You can try to run launch it with 

`DRAW_USE_LLVM=0 retroarch`

You can check other [mesa environment variables](https://docs.mesa3d.org/envvars.html) if you wan to experiment ;)

Hope the [grate driver](https://github.com/grate-driver) will be reintegrated soon to pmOS  ;)
