### ISSUE TITLE
RetroArch 1.9.3 doesn't boot on my PlayStation 2 Slim

### ISSUE THREAD

**Issue by SilverKnight-Z** [libretro/RetroArch#12418]
## Description

I downloaded the latest stable version of Retroarch for PS2 to my USB drive, when I open raboot.elf from ULaunchELF, it just doesn't boot and stays on a black screen. Previous versions booted and worked fine, especially 1.9.1 and 1.9.2.

### Expected behavior

raboot.elf starts and runs RetroArch normally.

### Actual behavior

When loading raboot.elf with ULaunchELF the screen goes black with no response.

### Steps to reproduce the bug

1. Copy the contents of RetroArch_elf.zip to the root of the USB drive.
2. Insert the USB drive into the PlayStation 2.
3. Run ULaunchelf from your preferred method (FreeDVDBoot, Free MCBoot, Fortuna, etc).
4. Press circle to go to the file explorer.
5. Go to mass://, locate the retroarch folder and open it.
6. Run raboot.elf

### Bisect Results

This started happening since version 1.9.3

### Version/Commit

- RetroArch: 1.9.3

### Environment information

- OS: Playstation 2 Slim -SCPH 790001

**Comment by KoMiKoZa** [comment]
Hi there. I would just like to report this exact thing happens to me and in general seems to be pretty widespread (as per YT videos comments), happens on the latest and 1.9.2 (I tried it as per your comment about 1.9.3) version of RA for PS2. I have **SLIM-SCPH-77008**. I tried about 5 builds, and none work. Am I missing anything here?
