### ISSUE TITLE
[iOS] N64 game does not work on 1.9.1 or later

### ISSUE THREAD

**Issue by babi-jkr** [libretro/RetroArch#12412]
Mupen64plus-Next core included in ver.1.9.0 does not appear in the list after 1.9.1.
If I choose rom directly without loading the core, ParaLLEl N64 will still not work, so it will go black and the core will freeze.
Is MupenN64plus-Next core no longer available for some reason?
If not, I hope the core will come back.

I'm sorry if this way of writing is not appropriate. I couldn't think of any other place to report.

**Comment by yoshisuga** [comment]
Mupen64plus-Next needs to be added to the iOS build pipeline for the nightly cores. Will look into adding it - it does build when built manually so it should be included soon.

**Comment by mmcomic** [comment]
there is still some issue on ra 1.9.0 to play zelda mask .when will the core be added to nightly build for ios ?

**Comment by tannerellen** [comment]
I just downloaded the latest version of RetroArch for iOS and it looks like the Mupen64 core is still missing. I’m using 1.9.0 in the meantime. 

Any update on this core being included in future builds?

**Comment by tannerellen** [comment]
Just installed version 1.15.0 and the Mupen64 next core is now included. So looks like this is no longer an issue and this could probably be closed.
