### ISSUE TITLE
RetroArch (32-bit) 1.9.3 uses both default and remapped inputs simultaneously. Using touchscreen controls on Android device

### ISSUE THREAD

**Issue by leoevc** [libretro/RetroArch#12422]
## Description

Updated from RA (32-bit) 1.9.0 to RA (32-bit) 1.9.3 non-Play Store on Android phone, loaded content for which I had a 'core remap' and noticed the game character was performing 2 actions simultaneously upon one button press, I deleted the remap file, resumed content and pressed the same button again and noticed the 2nd unexpected action was the default one. I created the core remap again and the problem persisted. Since the 'Load remap file' entry was still empty I entered it to have it load the .rmp file, but that didn't solve the problem. This happened with FBA 2012 Neo Geo.

Next, I tried with a content for which I had a 'Game remap' on a different core (mGBA). I did everything as described before except that now with a game-specific remap.

I've already tried fresh installs of RetroArch without luck.

### Expected behavior

Only use the remapped inputs and ignore the default inputs until I delete the .rmp

### Actual behavior

Both default and remapped inputs are being used. Upon one button press the character performs 2 actions: 1 determined by the default input and the other determined by the remapped input.

### Steps to reproduce the bug

1. Open RetroArch
2. Launch content
3. Go to Quick Menu -> Controls -> Port 1 and remap inputs.
4. Make sure 'Remap controls for this core' is ON (under 'Input' main settings). If it's turned OFF the remap is completely ignored
5. At this point, the remapped inputs are already active. Resume content and press overlay buttons. (The problem persist regardless of Saving and Loading the .rmp file for Core/Game)

### Version/Commit
RetroArch (32-bit) 1.9.3 Stable
Downloaded from [here](https://www.retroarch.com/?page=platforms)
(the 32-bit specific download for Android)

### Environment information

- OS: Android 4.4

**Comment by leoevc** [comment]
RetroArch log of steps to reproduce the bug

[retroarch.log](https://github.com/libretro/RetroArch/files/6518502/retroarch.log)

**Comment by bslenul** [comment]
Can confirm, just tried with Super Mario 64, remapped B to Y (so Mario should be punching instead of jumping) and when pressing B it presses both B and Y :/

Already happening in 1.9.1 stable (cf6ca2a), working properly in 1.9.0 stable (6388872), there's a huge gap between the 2 versions tho so it might be a PITA to find when it started exactly...

**Comment by leoevc** [comment]
Thanks for confirming @bslenul. I was wondering if my phone was the problem. And also for commenting about 1.9.1 before I started downloading and installing APKs like crazy :)
