### ISSUE TITLE
Choppyness in Sound and FPS (RA 1.9.3) (Linux)

### ISSUE THREAD

**Issue by Rstation4** [libretro/RetroArch#12428]
OS: Linux Mint 20.1 Cinnamon Edition
Retroarch version: 1.9.3  (App Image for Linux)
Hardware: 4K Monitor
Desktop PC (64 bit OS) 

Even with the non app image version of RA, I get this choppy and laggy gameplay. Even if the Screen is not fullscreen I still get poor performance.

Logs:
[retroarch linux.log](https://github.com/libretro/RetroArch/files/6525795/retroarch.linux.log)

**Comment by gouchi** [comment]
Can you check if you have still the issue using alsa audio driver ?

Thank you.

**Comment by Rstation4** [comment]
I have not done any deep testing but my monitor display settings may have been the culprit. It was at 30.00 Hz Recommended Vsync which could not have been changed any higher. It was my mistake that the HDMI cable was not of a 4k 60 Hz capability. After switching the cable I was able to up the  Refresh rate up to 60.00 Hz.

I did a very short test and it quickly showed no audio or visual choppyness.

**Comment by hizzlekizzle** [comment]
Ah, yeah, that's an easy trap to fall into. If that got you all fixed up, you can go ahead and close the issue.
