### ISSUE TITLE
French translation issue

### ISSUE THREAD

**Issue by Jaylinx** [libretro/RetroArch#12440]
## Description

On Network informations, the french word for network is réseau with a é, but é is not recognized in RA and is replaced by a japanese or chinese letter

### Expected behavior

réseau

**Comment by toshixm** [comment]
@Jaylinx I have fixed the issue at #12446.
Could you confirm it if you can try to built from git or to use nightly build?

**Comment by gouchi** [comment]
@Jaylinx Please close this issue as it has been fixed.
