### ISSUE TITLE
wish: possibility to connect a configuration to a core

### ISSUE THREAD

**Issue by 20Phoenix** [libretro/RetroArch#12447]
Hello :)
I wish it could be possible to connect a configuration to a core.
So it wouldn't be necessary to load a needed config again and again.
Instead a core should load it's own config it got connected with before starting.
That would be immensely helpful.
So I wouldn't need to load special settings for Dolphin or PCSX2 again and again.

I hope my intention is clear, English isn't my native 😅

**Comment by hizzlekizzle** [comment]
That's the purpose of config overrides: https://docs.libretro.com/guides/overrides/

**Comment by 20Phoenix** [comment]
Oh, so my wish was already realize. Thanks 😃
