### ISSUE TITLE
Can't load cores on tvOS 14.6

### ISSUE THREAD

**Issue by wodinga** [libretro/RetroArch#12449]
AppleTV 4k 2nd gen
tvOS: 14.6

I am unable to play any games because cores won't load.

I followed the instructions in the documentation and I placed the precompiled cores in `RetroArch/pkg/apple/tvOS/modules`. The cores appear on on RetroArch, but when I select a core it still says "no core" on the bottom left of the screen and when I run a game it says `Failed to open libretro core`.

According to the documentation these cores shouldn't need to be code signed because XCode should handle code signing, so I'm not sure what to do next.

When I run `codesign -dvv *.dylb` I always get an error similar to `2048_libretro_ios.dylib: No such process`

**Comment by wodinga** [comment]
My bad, I had to compile the cores for tvOS. I was using iOS cores.

**Comment by joaodforce** [comment]
@wodinga where did you get the tcOS cores? I seem t be having the exact same issue. The tvOS build instructions are a little bit lacking.
