### ISSUE TITLE
Version.all not bumped to latest release

### ISSUE THREAD

**Issue by stobb3s** [libretro/RetroArch#12451]
I compiled the latest version 1.9.4 from source today. I noticed that the main menu still shows version 1.9.3. I looked and the version.all file was not bumped for the new release 1.9.4.

**Comment by gouchi** [comment]
It should be fixed now with this [commit](https://github.com/libretro/RetroArch/commit/5cf7b57064eaa263f64a643978e60207f4cf264c#diff-1ee6bc2902cffb3e95eff4bfca332163bbccafb8700dc24561ceb1abec1511dd) which is now for the [new release 1.9.4](https://github.com/libretro/RetroArch/releases).

**Comment by stobb3s** [comment]
I compiled the update release and it shows correctly now. Thanks.
