### ISSUE TITLE
Wrong version?

### ISSUE THREAD

**Issue by leoxxx** [libretro/RetroArch#12453]
https://buildbot.libretro.com/stable/1.9.4/android/RetroArch_ra32.apk
It's 1.9.3.

**Comment by gouchi** [comment]
It should be fixed now with this [commit](https://github.com/libretro/RetroArch/commit/5cf7b57064eaa263f64a643978e60207f4cf264c#diff-1ee6bc2902cffb3e95eff4bfca332163bbccafb8700dc24561ceb1abec1511dd) which is now for the [new release 1.9.4](https://github.com/libretro/RetroArch/releases).

**Comment by leoxxx** [comment]
Still 1.9.3
