### ISSUE TITLE
[Windows] 9x, 2000 and XP versions don't work straight out of the box!

### ISSUE THREAD

**Issue by DoctorWarez** [libretro/RetroArch#12455]
I don't know what the actual msvc versions are, so i apologise.

Files are either missing or required, which don't come included.

Setup documentation is required to actually run RetroArch on a complete fresh install of these Windows versions.

**Comment by gouchi** [comment]
Which version did you use ? You did check the [documentation](https://docs.libretro.com/guides/install-windows-2000-me-98SE/) ?

Thank you.

**Comment by DoctorWarez** [comment]
"complete fresh install of these Windows versions."

Obviously RetroArch won't work "as is", as wont it come with errors.

nothing works exactly out of the box, without directx or anything else that may be missing like the manifest file?
