### ISSUE TITLE
[VITA][1.9.4] GPSP core crashes retroarch in various ways

### ISSUE THREAD

**Issue by spriteice** [libretro/RetroArch#12461]
As per title, my issue is present on the VITA 1.9.4 stable build

My device is a PSVITA Slim 3.60 henkaku enso, using sd2vita and max overclock via PSVshell

I am using clean dumped md5 verified roms.

Md5 verified bios file is present.

I updated retroarch by deleting the previous app and installing 1.9.4 in it's place.

[ISSUE]

All issues present after updating to 1.9.4 

When loading a game using the GPSP core the game loads and runs fine.

When exiting the game within retroarch, the GUI loads fine. However, if I try to load a different game through another core Retroarch crashes.

Retroarch also crashes if I have a game loaded within GPSP and try to exit Retroarch directly from that state.

I have since rolled back to 1.9.3 and the issue is completely gone, everything is working as expected again.

1.9.4 GPSP core = 261b2db

1.9.3 GPSP core = cc1a074

Thanks again devs for all your hard work and passion on this project. Retroarch is an amazing peice of software to have on a device such as a PSVITA.

**Comment by frangarcj** [comment]
It is fixed
