### ISSUE TITLE
[VITA] Per game/specific ROM settings not saving

### ISSUE THREAD

**Issue by bielgiroto** [libretro/RetroArch#12460]
## Description

No mather what core you are running, you can't save specific game configs anymore ~ things like custom bezels, or specific button layouts for example don't keep saved anymore after the 1.9.1 update and beyond.

### Expected behavior

Having the config save files system correctly working just like it was in the 1.9.0 version and below.

### Actual behavior

The configs don't save anymore for specific games.

### Steps to reproduce the bug

1. Simply run a ROM file and change whatever settings you want;
2. Try to save your settings via the quick menu on the section "config override options" choosing the "save custom game setting" option
3. Close and open your ROM again and see that it didn't saved anything.

### Bisect Results

Started happening on 1.9.1 version from what I remember, and still is a thing at the recent 1.9.4 release as well. 
It's a problem that didn't existed on the 1.9.0 version.

### Environment information

- OS: [ PS Vita 2000 ~ 3.65 Enso modded Firmware ]
Versions tried: 1.9.1 / 1.9.2 / 1.9,3 / 1.9.4

Latest version tried: 1.9.4
Version I'm actually using after making the tests: 1.9.0

**Comment by frangarcj** [comment]
Can you try with nightly?

**Comment by bielgiroto** [comment]
Fixed in the nightly builds, thx
