### ISSUE TITLE
[Windows] [D3D11] [D3D12] Fast-forward not working (apparent V-Sync enforcing)

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#12475]
## Description

Currently, whenever using the D3D11 video driver with any of the available cores, the fast-forward functionality does not seem to work, or at the very least seems to be limited to the refresh-rate of the monitor, as if V-Sync was forced ON all the time. @sonninnos also reported that the D3D12 driver is exhibiting the same problem.

Seeing that the volume widget is showing up on Windows 10 when using the D3D11 driver, I suspect that the problem stems from flip-model fullscreen, which was implemented for D3D11 with this commit: https://github.com/libretro/RetroArch/commit/7d313647ae75afe9ccd7456d46ac9aef033159b6. What this does is create a borderless fullscreen mode that also retains the benefits of exclusive fullscreen, such as lower input latency.

This seems to be confirmed also by @Awakened0 here: https://github.com/libretro/RetroArch/issues/7430#issuecomment-808968807

It would be great if we had an option allowing to toggle between traditional Exclusive Fullscreen and the flip-model functionality for these two drivers.

### Expected behavior

Fast-forward should work with the D3D11 and D3D12 video drivers. More generally, it would be great to either enable or disable flip-model fullscreen as per one's preference.

### Actual behavior

Fast-forward is not working properly with the D3D11 and D3D12 video drivers. Maximum framerate speedup when fast-forwarding appears to be limited to the screen refresh rate.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.4 / 6443d6f

### Environment information

- OS: Windows 10 x64
- Compiler: MSYS2 / Mingw64

**Comment by Awakened0** [comment]
> Seeing that the volume widget is showing up on Windows 10 when using the D3D11 driver, I suspect that the problem stems from flip-model fullscreen, which was implemented for D3D11 with this commit:

Have you tested to see if fast forward works in D3D11 before that commit? I assumed it wasn't flip model's fault, just that NVidia's drivers had more control over forcing Vsync with D3D than Vulkan. And Vulkan used to have fast forward issues too before themaister implemented mailbox for it, IIRC. He talks about the mailbox stuff in [this article](https://themaister.net/blog/2018/09/09/the-state-of-window-system-integration-wsi-in-vulkan-for-retro-emulators/), though I'm unsure if that is what would need to be implemented in the D3D drivers for working FF regardless of driver Vsync setting.

**Comment by sonninnos** [comment]
Looks like I found the missing pieces, as in simply adding `DXGI_SWAP_CHAIN_FLAG_ALLOW_TEARING` and `DXGI_PRESENT_ALLOW_TEARING` where needed.

**Comment by Ryunam** [comment]
@sonninnos saves the day! Thanks for working on this.

Perhaps while you’re at it could you take a look at another issue that may (or may not) be related? With both D3D11 and 12 right now the “Take Screenshot” option in RA is not working with hardware-rendered cores such as Duckstation and PPSSPP (these are the ones I tested, at least). It does work with software cores like snes9x for some reason.

**Comment by Awakened0** [comment]
GPU Screenshot doesn't work in the D3D drivers (https://github.com/libretro/RetroArch/issues/6427), so software cores only get native res screens and hardware cores get nothing.
