### ISSUE TITLE
Feature request netplay support for n64 cores

### ISSUE THREAD

**Issue by merrychrishna** [libretro/RetroArch#12487]
## Description

please can you add support for netplay for n64 cores in a future update of retroarch? Ive been seeing other emulators have just added this feature and seems to work well for games like mario kart 64.

### Expected behavior

support for netplay for n64 cores for retroarch

### Actual behavior
.
hosting n64 games with netplay on retroarch crashes retroarch and kicks me out of the game.

### Steps to reproduce the bug

start a netplay host for mario kart 64

### Environment information

- OS: 351ELEC - 20210603 Crazy Hedgehog (Hotfix1)
- Compiler: unkown
- Device: anbernic handheld rg351p

**Comment by Cthulhu-throwaway** [comment]
@LibretroAdmin core needs to support deterministic savestates for netplay support to be even an option. None of the current N64 cores do.

Writing a new and less reliable netplay system just to support these exceptions is out of the question for me, and I really doubt anyone else will bother either.

Close this as "won't fix", if you want to.
