### ISSUE TITLE
N64 Roms

### ISSUE THREAD

**Issue by 24floppystack** [libretro/RetroArch#12492]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

N64 ROMS

### Expected behavior

Controller input, surround sound and video patch

### Actual behavior

Without those patches it can't produce real output

### Steps to reproduce the bug

Sluggish controller
Low Res video
Bad sound

### Bisect Results

Latest Nvidia drivers 466.63

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.4

### Environment information

Windows 10
Player and Updates
https://drive.google.com/file/d/1jyw57r4aLzo4taUAZFJr9Ps8-3nE467h/view?usp=sharing
In case of problems with Windows Update and Security Defender install
manually Security Updates and  Cumulative Preview KB5001391. (STABLE)

Windows 10
https://drive.google.com/file/d/1aWz_RGM53EKvnc9wiTEFQ4IzY0gndkYm/view?usp=sharing
Windows Server 2019
https://drive.google.com/file/d/16oEX6uj_UqXXEIKqpoItXXN1iD3Tn8NP/view?usp=sharing

MOT64
https://drive.google.com/file/d/1fa67F24BcD-HccdB1hTdCUamN0pDi_un/view?usp=sharing

32BITSBMP
https://drive.google.com/file/d/1BAJ5fZCl3g9OoLl44kFXVc4tOsRHlFQn/view?usp=sharing

Visual Studio 2013 redists
DirectX August 2007 redists
DirectX June 2010 redists

Install DirectX 11.2 Player and prerequisites
Install 32BITSBMP
Plug controller and start MOT64 before starting RetroArch.

**Comment by hizzlekizzle** [comment]
This is not an actionable report.

**Comment by mudlord** [comment]
whut.

**Comment by 24floppystack** [comment]
Thank you and have fun.
