### ISSUE TITLE
Custom inputs don't work for me

### ISSUE THREAD

**Issue by Kirbystarallies1** [libretro/RetroArch#12517]
## Description

Whenever I try to use custom inputs, they never save and it goes back to default. I can't save them because there's always an error. I did get it to work with one game but I can't get it to work with the other 2 I have.

### Expected behavior

I thought it didn't work for one game but it turns out it doesn't work at all.

### Actual behavior

I can't use custom inputs 

### Steps to reproduce the bug

1. I change the controls
2. Launch the game
3. Inputs get reset to default

### Bisect Results

This started happening ever since I got Retroarch

### Version/Commit

- RetroArch: 1.9.1

### Environment information

- OS: ?
- Compiler: Don't know

**Comment by hizzlekizzle** [comment]
Github issues aren't great for general tech support questions like this, but are you making the changes in quick menu > controls or settings > input? If the latter, those inputs shouldn't be fiddled with on a per-core/game basis. You should set them once to get your physical controls mapped to the retropad abstraction and then never touch them again (or, if your pad is recognized and autoconfigured, never even go in there in the first place).

To change your controls on a per-core/game basis, make your changes in quick menu > controls and then use the 'save core/game remap' option from that same menu to make your changes persistent across sessions.

**Comment by Kirbystarallies1** [comment]
I don't see save core/game remap anywhere

**Comment by hizzlekizzle** [comment]
While a game is running, go into quick menu > controls and it should be right there.

**Comment by Kirbystarallies1** [comment]
I got it to work, thanks

**Comment by hizzlekizzle** [comment]
Sweet. If you're all set, would you mind closing out the ticket?

**Comment by Kirbystarallies1** [comment]
Right after I got it working the controls decided to become messed up again

**Comment by Kirbystarallies1** [comment]
Nevermind I got it to work again
