### ISSUE TITLE
Feature Request: Add mouse support to Xbox Dev Mode UWP

### ISSUE THREAD

**Issue by danprice142** [libretro/RetroArch#12518]
Please add mouse to 1.9.5 and above

**Comment by danprice142** [comment]
this would be good for dos and lightgun roms

**Comment by Tommy2jackets** [comment]
Agreed, I would love some mouse support for the uwp version for the series x. The xbox natively has mouse support in dev mode, so maybe it wouldn't be too difficult? Although I don't know of course

**Comment by sokratisg** [comment]
Not sure why this has been closed. This is still not working by either using uwp or xinput in the input driver on latest Retroarch UWP build.

Is lack of mouse support something caused by the UWP build or merely a build time flag that no one tinkered with so far?

**Comment by danprice142** [comment]
``

> Not sure why this has been closed. This is still not working by either using uwp or xinput in the input driver on latest Retroarch UWP build.
> 
> Is lack of mouse support something caused by the UWP build or merely a build time flag that no one tinkered with so far?

I closed it because its not possible to use a USB/Bluetooth mouse in UWP on Xbox without special permissions from Microsoft which they never really granted to any one other than themselves for like 2/3 things on Xbox, however its possible over network if/when this gets merged https://github.com/libretro/RetroArch/issues/3372
