### ISSUE TITLE
[Ozone] Pressing Confirm and Cancel in rapid succession causes left sidebar to disappear

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#12510]
## Description

When using the Ozone menu driver, selecting any option that leads to a sub-menu (like "Load Core" or "Load Content") and then pressing the Confirm and Cancel buttons in rapid succession will cause some visual oddities, namely the disappearance of the left sidebar and respective cursor.

This is easily reproducible by using the keyboard and pressing "Z" and "X" on the keyboard very quickly one after the other, while "Load Core" is being selected. If done right, the result will be akin to this screenshot:

![Screenshot 2021-06-09 224549](https://user-images.githubusercontent.com/17614150/121427643-402d4f80-c975-11eb-9833-745d0f96c917.png)

### Bisect Results

I have yet to perform a bisect, but I believe it is a long-standing issue, possibly one that has existed forever. At the very least, it is happening with a build dating back to March 2021.

### Version/Commit

- RetroArch: 1.9.4 / 08481e2

### Environment information

- OS: Windows 10 x64
- Compiler: MSYS2 / Mingw64

**Comment by jdgleaver** [comment]
This should fix it: #12524 :)

(Wish I'd had time to look at this before the 1.9.5 stable release, but oh well...)

**Comment by Ryunam** [comment]
What can I say, other than “you’re the man” :) Thank you for working on this!
