### ISSUE TITLE
Retroarch not reading .dat format files.

### ISSUE THREAD

**Issue by Slim934** [libretro/RetroArch#12523]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

While attempting to create a custom directory for a Final Burn Neo ROMSET, retroarch will not read the arcade .dat file for the romset.

### Expected behavior

Expected to load .dat file while generating ROM scan and for retroarch to generate a playlist based on the .dat file.

### Actual behavior

Retroarch generates an error message stating "Failed to load Arcade DAT file (invalid format?)"

the DAT file came from the following location: https://github.com/libretro/FBNeo/tree/master/dats

The file utilized was the "FinalBurn Neo (ClrMame Pro XML, Arcade only).dat" file.

### Steps followed
The steps followed can be found on this forum post relating to arcade based ROMS.

https://neo-source.com/index.php?topic=3725.0

### Bisect Results

First attempted this process on June 13, 2021

### Version/Commit
Retroarch 1.9.4

- RetroArch: [version/commit]

Retroarch 1.9.4

- OS: [The operating system you're running]

Windows 10 Pro.

- Compiler: [In case you are running local builds]
N/A

**Comment by RobLoach** [comment]
RetroArch reads .rdb files, that are parsed through libretro-database https://github.com/libretro/libretro-database

**Comment by bslenul** [comment]
> the DAT file came from the following location: https://github.com/libretro/FBNeo/tree/master/dats

GitHub can be confusing for downloading files, from that link you posted DO NOT right click > save as on the .dat directly or it will be saved in a weird format and it won't work in RA. So open the link then (left) click on the .dat, click on either "Download" or "View raw" and then right click anywhere on the page and "save as".

When you open it with a text editor, if it looks like this, it is correct:
![image](https://user-images.githubusercontent.com/33353403/121926095-e2668200-cd3d-11eb-960b-fecf814d6445.png)

Like this, it is wrong:
![image](https://user-images.githubusercontent.com/33353403/121926118-ebefea00-cd3d-11eb-88b4-53d219ec4456.png)
