### ISSUE TITLE
DirectX 11 broken in UWP builds

### ISSUE THREAD

**Issue by JustMeDaFaq** [libretro/RetroArch#12548]
## Description
Retroarch as UWP crashes when selecting DirectX11 driver and restarting the application

### Version/Commit
Its happening since https://github.com/libretro/RetroArch/commit/946d87cf8919a8cf7141a4be9960c5306de73325

**Comment by GABO1423** [comment]
Dude, duplicate issue of #12542.

**Comment by JustMeDaFaq** [comment]
Closed since it's a duplicate
