### ISSUE TITLE
can not find libopenal-1.dll

### ISSUE THREAD

**Issue by hiwoshixiaoyu** [libretro/RetroArch#12547]
I complied code use msys64.
when I complied sucess,I try to run retroarch.exe.
It does not work,I move ffmpeg to it,but it also has error can not find libopenal-1.dll
what should I do to run it on windows 10.
Thank you~

**Comment by bslenul** [comment]
I had the same issue, either copy your dll from your msys setup (it's in `msys64/mingw64/bin/` IIRC) to your RetroArch folder, or add "--disabled-al" when running configure. I had to do the same thing for cg and libusb as well (so I'm running `./configure --disable-al --disable-cg --disable-libusb`).

I don't know why RA isn't build with these anymore tho.

**Comment by hiwoshixiaoyu** [comment]
Thank you very much, I use  ./configure --disable-al --disable-cg --disable-libusb this command.
I can debug  by qt creator.
Qt Creator、msys64、minggw64、gdb。

**Comment by gouchi** [comment]
@hiwoshixiaoyu So this issue can be closed ?

Thank you.
