### ISSUE TITLE
 How to run javajme on retroarch? 

### ISSUE THREAD

**Issue by Shimmer2** [libretro/RetroArch#12546]
How to run javajme on retroarch? （mobile phone jar game）

**Comment by gouchi** [comment]
Please read the issue template

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
**This is not a forum or a help section**, this is strictly developer oriented

You should check [SquirrelJME project](https://squirreljme.cc).

And moreover you already post an [discussion](https://github.com/SquirrelJME/SquirrelJME/discussions/121) on the SquirrelJME project...

Please close this issue.

Thank you.
