### ISSUE TITLE
[Steam] Few things not being properly sent to Steam cloud

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#12553]
Not sure where to post Steam issues, I guess here is fine?

So I was messing a bit with the Steam version ("Playtest" only since I don't have access to the regular one) to see what's being sent to the cloud or not, looks like there are a few issues when looking at this: https://steamdb.info/app/1472070/ufs/

* .cfg are not sent (tested with an override and with `retroarch.cfg`), I'm guessing `path: *` is incorrect, maybe it should be `path: .` instead? Or maybe it needs 2 separate paths like `path: .` (for root folder) + `path: config` (for overrides)? Idk, but in any case it's not working right now, for both root and config folders.
* For the regular version (https://steamdb.info/app/1118310/ufs/) it says `pattern: .cfg` instead of `pattern: *.cfg`, I'm assuming this is incorrect?
* `pattern: *.glsl` and `pattern: *.cg` instead of `pattern: *.glslp` and `pattern: *.cgp` for presets. It is properly set up for slang presets however.

**edit:** Oh and not an issue but more of a suggestion: adding `path: config/remaps/` with `pattern: *.rmp` would be nice! :D

**Comment by fpscan** [comment]
Hi, based on the changes I made yesterday, can we close this issue or is it need to be improved?

**Comment by bslenul** [comment]
Hey!

There are still some issues and differences between regular and Playtest versions! Shouldn't it be identical between both versions?

Playtest is still using `2/path: *` for *.cfg.

Regular has `4/path:` (empty) for *.lpl, it's still says *.cg and *.glsl instead of *.cgp and *.glslp for shaders presets, and *.rmp wasn't added to this version.

Both versions don't backup *.opt and overrides *.cfg, probably needs the recursive flag like you added for remaps in the Playtest version. And this is probably harmless but the *.opt lines appear 2 times in both versions also.

**Comment by fpscan** [comment]
Hi,

I just made changes and pushed, could you take a look on your end now?

**Comment by bslenul** [comment]
![image](https://user-images.githubusercontent.com/33353403/126366347-53e4c962-0f80-4319-ae9d-5a2731440db3.png)

^ Content of my cloud storage for the regular version, much better 👍 Only thing missing is the "config" folder with recursive for *.cfg files (overrides) and it should be good :) And maybe add recursive for shaders presets (cgp/glslp/slangp) as well? Since per-game/dir/core presets are saved in subfolders.

**Comment by fpscan** [comment]
Yeah, it should be fine now, if things works fine for you could you cloe this issue?

**Comment by bslenul** [comment]
Oof no, don't do root + recursive :D It just uploaded ALL of the autoconfigs, overlay presets, etc. 😅 

Just use 2 differents things:

> 2/path: .
2/pattern: *.cfg

For retroarch.cfg (so without the recursive)

then

> XXXX/path: config
XXXX/pattern: *.cfg
XXXX/recursive: 1

for overrides ;)

**Comment by Sanaki** [comment]
The need to delete things mid-run is part of why I'm concerned about retroarch.cfg being backed up. Bad settings cause a crash and then the user's in a bind.

**Comment by bslenul** [comment]
Yeah it's kind of a double edged sword, it can be useful but it can be a pain as well :/ For retroarch.cfg the only solution I've found to start fresh is to delete its content, not the file.

Basically: can't get rid of an override? Delete it while RA is running. Can't get rid of retroarch.cfg? Delete its content only.

I wish there would be a way to delete specific files from the cloud tho, that'd make things so much easier :/ But if it's really an issue, fpscan can always remove the problematic backups, it seems to delete automatically the "non-matching" files from the cloud (it removed the 800+ presets and autoconfigs .cfg I had yesterday :p).

Or to avoid any confusion: we could backup only saves and states + anything that can be deleted **from inside** RetroArch directly (remap files, shaders presets, core options, playlists), so we get rid of retroarch.cfg (you can reset it to default from RA, but if you can't boot that doesn't really help... 😅 ) and the overrides (still can't be deleted from RA itself).

**Comment by WarpedSavior** [comment]
Hi. Is there any reason in particular why recursion was disabled for the 'saves' directory? I don't really see any downsides to it, because that directory will only contain save files, and that would give users a bit more flexibility, letting us sort saves into folders by core name for instance.

**Comment by fpscan** [comment]
> Hi. Is there any reason in particular why recursion was disabled for the 'saves' directory? I don't really see any downsides to it, because that directory will only contain save files, and that would give users a bit more flexibility, letting us sort saves into folders by core name for instance.

Sure I can add recursive flag for saves folder as well. Thanks.

**Comment by WarpedSavior** [comment]
No, thanks to you for taking the time to do it :)

**Comment by Sanaki** [comment]
> Hi. Is there any reason in particular why recursion was disabled for the 'saves' directory?

So long as there's an extension filter that should be fine, but some cores store other contents there as well. A few examples:
* DuckStation: Shader cache
* PPSSPP: Texture packs (potentially huge), real system fonts (user-supplied), cheats
* Dolphin: Texture packs (potentially huge), shader cache

**Comment by 1337haXXor** [comment]
I was wondering if we could also get the playlist logs added to the cloud saves? That way it can keep track of content playtime between devices, which would be great.
