### ISSUE TITLE
Can't input an analog left command in PPSSPP on Final Fantasy Tactics, War of the Lions

### ISSUE THREAD

**Issue by jvook** [libretro/RetroArch#12551]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- - _I don't know where else to post this, there is no issue tracker on liretro/ppsspp, and the issue has shown on the retroarch forums for several years_

## Description
This is a simple yet long-standing issue that you cannot input an left-stick analog left command in Final Fantasy Tactics, War of the Lions, on PPSSPP core.  This issue does not exist in master and as far as I know it never has been an issue in master .  Further info here: https://forums.libretro.com/t/controller-issue-in-ppsspp-core-with-fft-wotl/5180

- OS: Windows 10

**Comment by bslenul** [comment]
> I don't know where else to post this, there is no issue tracker on liretro/ppsspp

The core is maintained upstream so you'll have to report the issue there directly: https://github.com/hrydgard/ppsspp/issues ;)

**Comment by jvook** [comment]
Reported at https://github.com/hrydgard/ppsspp/issues/14551
