### ISSUE TITLE
RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL crashes the core unless passed by reference

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#12554]
If a core uses the RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL callback with a literal or passes by value, the core crashes and sometimes RA crashes completely.

My guess is that this is not the intended behavior.

When searching for RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL across the github organization, it's easy to see that every core is passing by reference -- maybe we have all copied off of each other.

https://github.com/search?q=org%3Alibretro+RETRO_ENVIRONMENT_SET_PERFORMANCE_LEVEL&type=code

That implies RA has behaved like this for a long time. I would be glad to provide more information. I have a test build of mame2003-plus that demonstrates the issue.

**Comment by markwkidd** [comment]
Also, could anyone clarify what the expected range of values is for this callback? Is it 0-10? 0 to INT_MAX?

**Comment by jdgleaver** [comment]
As with *all* environment callbacks, the libretro API *demands* that any value be passed by reference (check here: https://github.com/libretro/RetroArch/blob/7b47f5f49a2cc64a04a70e282647140b240522e6/libretro-common/include/libretro.h#L528-L544 - the passed value is `const unsigned *`)

Using a literal or passing by value is a violation of the libretro API, so crashes are to be expected!

> Also, could anyone clarify what the expected range of values is for this callback? Is it 0-10? 0 to INT_MAX?

Unfortunately, it's a rather half-baked feature, with no formal definition of range (I don't know who implemented it...). But I believe most devs consider [0,10] to be the correct limits.

**Comment by markwkidd** [comment]
Ah hah, thanks. `The levels are "floating"` indeed. :)
