### ISSUE TITLE
Please add gfx-rs portable to support Vulcan on Xbox dev mode 

### ISSUE THREAD

**Issue by danprice142** [libretro/RetroArch#12567]
https://github.com/gfx-rs/portability

**Comment by danprice142** [comment]
https://www.khronos.org/blog/khronos-announces-the-vulkan-portability-initiative

**Comment by danprice142** [comment]
This can be used to route Vulkan & higher versions of OpenGL to DirectX to allow use of more Cores this could benefit a lot of users not just xbox

**Comment by hizzlekizzle** [comment]
I tested this on my work machine, which lacks Vulkan, and it worked for the menus and shaders but did not seem to handle Beetle-PSX-HW or ParaLLEl-RDP. I wasn't able to test any other cores, but if any that don't have native d3d11 renderers can use it, I'd say it's an improvement. I think Flycast and Citra(?) would be the most likely benefactors.
