### ISSUE TITLE
Feature Request: RS-90 OpenDingux Support

### ISSUE THREAD

**Issue by john-parton** [libretro/RetroArch#12569]
I have started work on porting RetroArch and the Gambatte core to a new device, the RetroMini or CoolBaby RS-90.

I already have rgui completely working as far as I can tell, and Gambatte can load roms and play them, but with poor audio performance.

@jdgleaver Helped me out immensely over Discord.

I have a branch here that I'm working on: https://github.com/john-parton/RetroArch/tree/feature/rs90

It's a very under-powered device. It has a very weak mips CPU and only 32MB of RAM. Also the IPU has very limited functions. Finally, the screen is only 240x160 pixels.

https://jzwiki.gameblabla.nl/doku.php?id=retromini

But there's a lot to love!

Firstly it's a $30 device, so the fact that it can do anything is sort of amazing.

Secondly, *a huge amount of the work is already done*. I only had to modify 8 files to get RetroArch with rgui started, and the Gambatte port only took __14 lines__ of boilerplate in the Makefile.

![PXL_20210624_160257947](https://user-images.githubusercontent.com/2071543/123369129-c5526000-d542-11eb-910e-b71c23bd1ab1.jpg)
![PXL_20210624_165239332](https://user-images.githubusercontent.com/2071543/123369133-c6838d00-d542-11eb-9322-8224dd69c745.jpg)

**Comment by jdgleaver** [comment]
This is really great!

The required changes are pretty non-invasive, and we can definitely work with them.

I would propose the following: if we can demonstrate that at least 1-2 cores can run fullspeed on this device (i.e. that RetroArch is a practical option on these things!), then I'll see if we can get the libretro project to purchase one for me - and if so, I will certainly help with integrating your work into the official codebase, and get build targets added to our build infrastructure.

**Comment by gouchi** [comment]
That is cool to see a new device for OpenDingux ;)

I was wondering what is the status of [tinyalsa](https://github.com/libretro/RetroArch/blob/master/qb/config.params.sh#L114) audio driver, did you have the opportunity to make some test ? As I saw you [re-enabled alsa audio driver](https://github.com/libretro/RetroArch/pull/12568) ?

**Comment by john-parton** [comment]
TinyAlsa definitely works on the OpenDingux beta. I can open a new PR.
