### ISSUE TITLE
"Add to Favorites" shown when item chosen in Favorites tab

### ISSUE THREAD

**Issue by Brunnis** [libretro/RetroArch#12594]
## Description

When a game is selected in the Favorites menu/tab, the "Add to Favorites" menu item is visible. That doesn't seem to make sense and I'm guessing it's not the intended behavior. I've confirmed this in Ozone, XMB and RGUI.

### Expected behavior

Since the item clearly has already been added to the Favorites list, the "Add to Favorites" item should not be shown.

### Actual behavior

"Add to Favorites" is always shown when selecting an item in the Favorites list.

### Steps to reproduce the bug

1. Add game to the Favorites list.
2. Go to the Favorites and choose the item, i.e. to get into the item's menu.
3. The "Add to Favorites" item is available, along with "Run", etc.

### Version/Commit

I believe this bug has "always" been there. I just tested and confirmed it on 1.9.5.

**Comment by Brunnis** [comment]
@jdgleaver I was told on Discord to mention this to you, as you seem to have a handle on the UI related stuff.

**Comment by jdgleaver** [comment]
Yes, this should be fixable. I'm busy with (real life) work stuff this week, but should have some time to look at this on Friday.

**Comment by jdgleaver** [comment]
This is the best I could do: #12606

It hides the "Add to Favorites" option in the favorites playlist - but the option will still be shown if you access a 'favorited' item via a different playlist. Unfortunately the additional performance overheads of searching the contents of the favorites playlist to exclude matches in all cases were too high (for various reasons it requires actual file system access every time the quick menu is opened, which is highly undesirable...)

**Comment by Brunnis** [comment]
Great! I think the slight compromise you had to do is perfectly acceptable. The main ugliness is showing “Add to favorites” when you’re already in that playlist.
