### ISSUE TITLE
Can't unbind analog triggers core inputs from the real controller triggers

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#12596]
## Description

So atm with cores that can handle analog triggers (Flycast, Dolphin, FBNeo, Saturn cores, etc.), if you bind something else to your controller triggers or even if you unbind them completely, they will keep sending their "original" inputs. Tested with dinput, xinput and sdl2 drivers, on Windows 10.

Here's an example with Flycast:

https://user-images.githubusercontent.com/33353403/123987333-628c1900-d9c7-11eb-9004-fc74be5d8f39.mp4

^ Here I rebind my L2 and R2 to some dpad directions, you can see it sends both the dpad AND the triggers inputs.
Then I completely unbind L2 and R2 and you can see it still sends the triggers inputs.

However Flycast has a very useful "Digital Triggers" core option which can be used as a workaround, but AFAIK it's the only core with that option.

### Expected behavior

Stop sending the core triggers inputs when it's bind to something else or unbind.

### Actual behavior

It's pretty much impossible to rebind/unbind analog triggers.

### Steps to reproduce the bug

1. Go to the online updater and grab `ControllerTest-DJ.cdi` for Dreamcast.
2. Launch it and mess with L and R triggers.
3. Go to `Quick Menu > Controls > Port 1 Controls` and unbind your triggers.
4. See the program still recognizing triggers inputs.

### Bisect Results

No idea, but it was already happening in 1.7.5.

### Version/Commit

- RetroArch: 1.9.6 / 2e215bd

### Environment information

- OS: Windows 10

**Comment by barbudreadmon** [comment]
It's still happening (i discovered this in FBNeo yesterday).

I believe it has to do with the fact the cores declare those triggers's descriptors like this : 
```
retro_input_descriptor descriptor;
descriptor.port = port;
descriptor.device = RETRO_DEVICE_JOYPAD;
descriptor.index = 0;
descriptor.id = RETRO_DEVICE_ID_JOYPAD_R2;
descriptor.description = description;
```
Considering the way you poll them, the proper way to declare their descriptors should be like this : 
```
retro_input_descriptor descriptor;
descriptor.port = port;
descriptor.device = RETRO_DEVICE_ANALOG;
descriptor.index = RETRO_DEVICE_INDEX_ANALOG_BUTTON;
descriptor.id = RETRO_DEVICE_ID_JOYPAD_R2;
descriptor.description = description;
```
But if you do that the descriptors simply won't appear anymore in `Quick Menu > Controls`.

Also note that my ds4 triggers don't even seem to properly return analog values (goes directly from 0 to 32767), so i'm wondering if there is any worth in keeping that analog button stuff in my core...

**Comment by barbudreadmon** [comment]
note that "fixing" the descriptors didn't change anything about the actual issue, i tried fixing it but retroarch's remapping code is just way too confusing for me, i hope someone more knowledgeable about retroarch remapping can figure it out.

**Comment by bslenul** [comment]
Haha yeah, every time I hear about the input code it sounds like a dark place where no one wants to go :D 

Still, thank you for your interest on this issue, really appreciated 👍

**Comment by jdgleaver** [comment]
Should be fixed by https://github.com/libretro/RetroArch/pull/13913

(Unfortunately any remapped analog buttons become digital, but the underlying code is too bad to rectify this...)

**Comment by bslenul** [comment]
Thank you! <3 Even if it's remapped as digital, it'll be 100x better than previous behavior :D
