### ISSUE TITLE
Feature Request - Turbo D-Pad Directions

### ISSUE THREAD

**Issue by bcrew1375** [libretro/RetroArch#12599]
This may sound like a useless feature, but I've run into at least one instance where being able to rapidly press the D-Pad would come in handy. The example I found is Kirby Super Star on the SNES, which has a copy ability that can be charged only by rapidly pressing a direction on the D-Pad and can lead to blisters pretty easily after some time(Plasma). This is the only example I've found so far, but I'm sure there are other games where it would come in handy.

**Comment by bkaufx** [comment]
Is this possible yet?  I'd like to use this for Dr. Mario because I think you can get out to the edges quicker of you rapidly tap the arrows rather than holding.
