### ISSUE TITLE
Cores selectable in Load Core menu but "No Cores Available" after selecting ROM

### ISSUE THREAD

**Issue by TechiRef** [libretro/RetroArch#12627]
## Description

When I go to select a core in the Load Core menu, all of the cores that I expect to be there are there, and after selecting the core, it is identified in the bottom left corner. Then when I go to select an N64 ROM, it says No Cores Available. This happens regardless of core. I've had this setup work fine for months before some recent update likely screwed something up, but even after a (what I can only assume is) fresh reinstall, it still isn't loading the cores at all. The 2048 core plays fine, so I can only assume that it's something with the ROM loading menu that is acting up. I got a couple of logs with the --verbose flag so that maybe something could be gathered from it, but from what I can tell there aren't any major errors from it.

### Expected behavior

After I select a core, it is expected that the ROM will be able to be loaded after selecting it.

### Actual behavior

As the menu after selecting a core shows "No Cores Available" despite the cores being readily selectable in the Load Core menu, I cannot go any further.

### Steps to reproduce the bug

1. Go to Load Core menu
2. Select the respective core for the ROM to be loaded
3. Go to the Load Content menu
4. Select a ROM that corresponds to the Core that I have loaded

### Bisect Results

It's been a couple of months since I last opened RetroArch, but back then it worked just fine. I'm using Arch Linux, so my install should be up to date.

### Version/Commit

- RetroArch: 1.9.6 (2.0-rc2 0a67445)

### Environment information

- OS: Arch Linux
- Installed from the standard Arch Repositories (not the AUR)

Log from the attempted loading of a core and a ROM: https://pastebin.com/yCg8kKWY
Log from the attempted (and successful) loading of the 2048 core: https://pastebin.com/zsLh0kCt

**Comment by renderman21** [comment]
I am guessing it has something to do with the ROM itself than the core. In this log, [https://pastebin.com/yCg8kKWY](url), doesn't show any errors so I presume that you are just loading the N64 core, since it doesn't get log there. I would suggest in checking the file of the ROM or change the N64 core (there are two of them if I remember). Hope this helps.

**Comment by bslenul** [comment]
Hm that usually means you're missing .info files (when you go to "Load Core", do you see proper names like "Mupen64Plus-Next" or "mupen64plus-next_libretro.so"?) or incompatible extension for the rom file.

**Comment by TechiRef** [comment]
> Hm that usually means you're missing .info files (when you go to "Load Core", do you see proper names like "Mupen64Plus-Next" or "mupen64plus-next_libretro.so"?) or incompatible extension for the rom file.

Yeah, all I see are the filenames for the shared object. What's weird is that even after I redownload the cores, it still gives the same issue. I had a feeling something was up with a missing file or something, given the subsection of License under each object saying N/A. What's the best way of forcing these .info files to generate again?

**Comment by bslenul** [comment]
I don't know anything about Arch Linux, can't you update info files from the online updater directly? If not you can download them manually: https://buildbot.libretro.com/assets/frontend/info.zip then extract in your core info folder, if you don't know where's it's located, check the path in RetroArch in `Settings > Directory > Core Info` ;)

**Comment by TechiRef** [comment]
And that's an issue that can be marked as closed! That's really weird that it only now caused issues, since it had been just fine with how it was before. Maybe just something that got depreciated along the way. Anyways, thanks for the help!
