### ISSUE TITLE
[Windows] File name contain unicode show garbled when ruan a game

### ISSUE THREAD

**Issue by LetCodeGo** [libretro/RetroArch#12629]
**the show text is garbled, but the screenshot png file name is correct.**
**other prompt like save memery card to {filename}_1.mcd, the filename is garbled too, but the actual mcd file name is correct.**
**i guess every prompt text contain unicode will be garbled when the windows codepage is not utf8, and need a convert.**
**version 1.9.6.**

![恶魔城 - 月之轮回 施珂昱 (简)(JP)(64Mb)-210709-162627](https://user-images.githubusercontent.com/7180923/125051690-c99b8300-e0d5-11eb-86ce-33c54160d595.png)
![Snipaste_2021-07-09_16-53-42](https://user-images.githubusercontent.com/7180923/125052229-521a2380-e0d6-11eb-930b-a4dcfbcf4506.png)

**Comment by toshixm** [comment]
I guess that you don't specify "On-Screen Notification Font" (Settings -> On-Screen Display -> On-Screen Notifications -> Notification Font).
The default font for notification is "DejaVu Sans Mono" (assets/pkg/osd-font.ttf), it doesn't contain Chinese glyphs.
Could you try to specify the font that contains Chinises glyph,? (For example, assets/pkg/chinese-fallbak-font.ttf)

**Comment by LetCodeGo** [comment]
> specify

Thanks, you are right. I just set the menu font and don't know the notification font.
Thank you again for your reply.
