### ISSUE TITLE
Android app icon

### ISSUE THREAD

**Issue by artemvodorez** [libretro/RetroArch#12636]
I noticed for a long time that the application icon on Android does not follow Google's guidelines and contains transparency, or a frame inside the icon (which should not be).

![Screenshot_2021-07-10-22-38-13-743_com miui home](https://user-images.githubusercontent.com/54878948/125174793-8114c000-e1d0-11eb-9b81-07559c97864a.jpg)

I suggest fixing the icon.

This icon follows all guidelines:
![retroarch](https://user-images.githubusercontent.com/54878948/125175341-241b0900-e1d4-11eb-9553-ec28002850a6.png)

the archive contains png and psd for future use.
[retroarch.zip](https://github.com/libretro/RetroArch/files/6795899/retroarch.zip)

**Comment by john-parton** [comment]
Submitted a PR to fix. https://github.com/libretro/RetroArch/pull/12649

I know basically nothing about android, so that might not work.

**Comment by fpscan** [comment]
https://github.com/libretro/RetroArch/pull/13035#event-5359464275
