### ISSUE TITLE
RetroArch ignores keyboard with a plugged PS3 joystick

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1265]
I can't use keyboard until I turn the PS3 joystick ON by pressing the PS/home button. The joystick was connected to my laptop before I open RetroArch.

**Comment by sergiobenrocha2** [comment]
Why it was closed? It seems someone has the same issue... http://libretro.com/forums/showthread.php?t=4284

And I have this issue yet, it's not fixed.

**Comment by sergiobenrocha2** [comment]
RA is stucking now with joysticks...

I plug the PS3 joystick while RA is opened, press the PS button and it works. Then I enter a game, and both keyboard and joystick stop respond, I have to unplug the joystick to get the keyboard back.

If I connect the joystick before open RA, it'll stuck too.

**Comment by sergiobenrocha2** [comment]
Found what was causing the last issue: **input_axis_threshold option**

For some reason it had "0.000000" value, if you change to default "0.500000" it'll not stuck the keyboard anymore. I don't remember messing around with this option recently...

The first issue reported here remains.

**Comment by fr500** [comment]
@sergiobenrocha2 is this still happening?

**Comment by twinaphex** [comment]
Going to close this, reopen if it is still an issue.

**Comment by sergiobenrocha2** [comment]
Still an issue.

**Comment by nightsky30** [comment]
Seems this is still an issue.
