### ISSUE TITLE
Analog Sticks not working when I turn on netplay(Only in game)

### ISSUE THREAD

**Issue by VainDash** [libretro/RetroArch#12667]
## Description

When I play Nintendo 64 games I cannot use my joysticks/analog sticks when I turn on netplay. But when I turn it back off I can use it again.

### Expected behavior

When I turn on netplay I should be able to use my analog stick in game.

### Actual behavior

Analog sticks not working when I turn on netplay. (The sticks still works in the menu)

### Steps to reproduce the bug

1. Choose ParaLLEI N64 or Mupen64Plus-Next as core
2. Choose game (I tried Super Smash Bros and Mario Kart 64)
3. Get in game
4. Turn on netplay host
5. Everything works except the joystick no matter what

### Bisect Results

Happened yesterday when me and a friend wanted to try to play some N64 games using netplay.

### Version/Commit

- RetroArch: 1.9.6

### Environment information

- OS: Windows 10, Version 21H1
- Compiler: MinGW (10.2.0) 64-bit

**Comment by Cynthius** [comment]
Same issue here, both N64 cores. Simply turning netplay on kills both control sticks. Turning it back off immediately returns control. Tested netplay with PCSX ReARMed and Snes9x - Current for comparison, and both of those receive control stick input fine regardless of netplay being active.

RetroArch 1.10.3
OS: Windows 10 Pro build 19044

**Comment by hizzlekizzle** [comment]
If you roll back to an earlier stable release, does it ever work? E.g., 1.9.0: http://buildbot.libretro.com/stable/1.9.0/windows/x86_64/RetroArch.7z

**Comment by Cynthius** [comment]
> If you roll back to an earlier stable release, does it ever work? E.g., 1.9.0: http://buildbot.libretro.com/stable/1.9.0/windows/x86_64/RetroArch.7z

Just tested on 1.9.0, same issue. Would've tried out some earlier builds as well, but couldn't find official downloads for any legacy versions.

**Comment by Cthulhu-throwaway** [comment]
Unsupported core. With the newer nightly builds you can't even start netplay with those cores anymore.

Should be closed.

**Comment by Cthulhu-throwaway** [comment]
@LibretroAdmin see above. Should be closed as "won't fix".
