### ISSUE TITLE
Multiple retropad buttons to the same core button

### ISSUE THREAD

**Issue by eadmaster** [libretro/RetroArch#12670]
## Description

Allow multiple retropad buttons to be assigned the same core button in the remap menu.

([Also asked here](https://forums.libretro.com/t/controller-config-2-buttons-that-do-the-same-input/9129/2).)

### Expected behavior

Use 2 different controller button for the same emulated button (e.g. use both Y and RB on an XB360 controller as Y on a SNES core)

### Actual behavior

Only one of the assigned buttons is working.

### Steps to reproduce the bug

1. start the emulation with any core
2. open the menu and go into Quick Menu -> Controls -> Port 1 Controls
3. assign "R Button (Shoulder)" to Y

### Bisect Results

Only the originally assigned button is working.

### Version/Commit

- RetroArch: 1.9.6

### Environment information

- OS: Ubuntu 18.04.2 LTS

**Comment by bslenul** [comment]
That's weird, working fine here on Windows 10 and on my Linux Mint VM, tested with udev and sdl2 drivers there, with a DS4 and a X1 controller (both plugged if it matters). Tested with Contra III on Snes9x and bsnes, RetroArch 1.9.6 (e5bbd9488f).

Does it happen with every core? Have you tried a different controller driver? And with a different controller?

The only way I can reproduce is by turning OFF `Settings > Input > Remap Controls for This Core`, so make sure you have that ON.

**Comment by eadmaster** [comment]
> The only way I can reproduce is by turning OFF Settings > Input > Remap Controls for This Core, so make sure you have that ON.

Indeed this was my problem, thank you for suggesting that! 

What confused me was the fact that the remapped controls simply stopped working instead of keeping the default association... shouldn't they keep the default with this option turned off?

**Comment by bslenul** [comment]
Yeah I'm honestly super confused about this option, the only thing it seems to do is making your buttons stop working if you remap anything... 🤔 I'm probably missing something obvious about it, but idk what :D
