### ISSUE TITLE
Pre-install Retroarch to Android's /STSYEM/APP/

### ISSUE THREAD

**Issue by clondy999** [libretro/RetroArch#12689]
I have copied the lib in retroarch32.apk to system/lib.
But I still get a crash when I open Retroarch. Did I miss something?

**Comment by hizzlekizzle** [comment]
wat? I don't understand what you're trying to do or why.

**Comment by DerpStation** [comment]
He's trying to make RetroArch a System app. Although I'm not sure why.

But to answer OP's question. Did you set the permissions of the newly moved system/app like [this?](https://images.app.goo.gl/KJb3zt2QsZvGXdWX6) and reboot?

**Comment by clondy999** [comment]
Yes, I have set permissions, including my other applications

**Comment by clondy999** [comment]
My other applications are working well

**Comment by LibretroAdmin** [comment]
Not sure if this is a valid request or something we can help with.
