### ISSUE TITLE
RawInput absolute coordinates messing up after a resolution change. (Regression)

### ISSUE THREAD

**Issue by F0xH0L3** [libretro/RetroArch#12687]
## Description

After a game has changed resolution, for example, switching from the ps1 bios (480i) to the game (240p),
the RawInput Absolute coords will not update to the new resolution, resulting in messed up coordinates. 

### Expected behavior
What is supposed to happen is that RA will update the coords upon a resolution change.

### Actual behavior

the RawInput Absolute coords will not update to the new resolution, resulting in messed up coordinates. 

### Steps to reproduce the bug
This applies to a crt 15khz setup, since with fixed resolution displays, there's no need to change resolution mid-game.
In order to reproduce this, you just need to have switchres setup correctly, run a ps1 game like time crisis or die hard trilogy with a lightgun, and when it switches from the bios screen to 240p, the coordinates will not update, resulting in completely messed up coordinates. 

### Bisect Results

This issue was fixed with the help of Alphanumu and Calamity, but started appearing again after this: 
[Link](https://github.com/libretro/RetroArch/pull/12556)
### Version/Commit

[Link](https://github.com/libretro/RetroArch/pull/12556)

### Environment information

- OS: Win 7 Ultimate

**Comment by Redemp** [comment]
Would be great to see this merged before 1.9.7 👍

**Comment by alphanu1** [comment]
@F0xH0L3 the fix for this is merged now. You can close this issue 😎

[PR](https://github.com/libretro/RetroArch/pull/12556)
