### ISSUE TITLE
Nintendo Switch - Only first player controller is detected

### ISSUE THREAD

**Issue by asier-ochoa** [libretro/RetroArch#12685]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When connecting 2 or more controllers to retroarch, only the controller assigned to player 1 in the switch OS is actually read by RetroArch. 

### Expected behavior

Every controller should be read in each corresponding slot

### Actual behavior

Only player 1's controller is read.

###This Doesn't happen on RetroArch 1.9.4 on the switch, haven't tried 1.9.5

### Steps to reproduce the bug

1. Use RetroArch 1.9.6 on the switch
2. Connect a second controller on switch os
3. Try to use it

- RetroArch: 1.9.6

### Environment information

- OS: Atmosphère 19.5 with OFW 11.0

**Comment by R-YaTian** [comment]
Same issue with V1.9.6.
V1.9.5 works fine.

**Comment by Abro61209** [comment]
Same here. They broke something. Can't find any archives for older versions so guess I'm stuck with V1.9.6 until the next revision.
