### ISSUE TITLE
The core info cache file stores absolute paths, which prevents portability on Windows

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#12697]
## Description

Hey!

So I've seen 2 or 3 persons already having issues while moving/renaming their RetroArch folder on Windows. They get an error saying it couldn't load the core while mentioning the previous path they used:
```
[ERROR] Failed to open libretro core: "C:\previous\path\for\cores\core_libretro.dll"
[ERROR] Error(s): The specified module could not be found.
```
and it was REALLY confusing because `Settings > Directory > Core` was pointing to the proper location.

Turns out the cause was because `core_info.cache` stores the absolute path for the cores. So these persons had to either turn OFF the feature or delete the file to re-generate a new one.

### Expected behavior

If a core fails to load because it wasn't found, the core info cache file should be "refreshed".

### Actual behavior

Content will fail to load until core info cache is turned OFF or deleted.

### Steps to reproduce the bug

1. Make sure `Settings > Core > Cache Core Info Files` is ON.
2. Move or simply rename your RetroArch folder.
3. Try to load a game.

### Environment information

- OS: Windows, I don't think that would be an issue on other OSes?

**Comment by twinaphex** [comment]
Hi, have you looked at this option before?

Settings > Playlists > Portable Playlists

It might do what you want.

**Comment by jdgleaver** [comment]
Oops... The core path shouldn't have been cached anyway....

Should be fixed by #12855

**Comment by bslenul** [comment]
Awesome, thanks for the fix! 👍 I wonder if that could be pushed (silently) as a hotfix for 1.9.8 :D

**Comment by jdgleaver** [comment]
Ah, looks like this one will go in the next release, since we're setting up proper development 'milestones' now (trying to do things by the book) - and this issue already got assigned. But I guess the next release is only 2 weeks away, so it's not too long to wait... :)
