### ISSUE TITLE
[Android] Mupen64Plus black screen when switching apps

### ISSUE THREAD

**Issue by kp8888** [libretro/RetroArch#12722]
## Description
While using Mupen64Plus-Next, switching apps and then returning to RetroArch results in a black screen or (rarely) a force close. Using default settings, shaders disabled. 

### Steps to reproduce the bug
1. Open RetroArch, load and run N64 rom. 
2. Switch to another app (e.g. phone dialer or web browser). 
3. Switch back to RetroArch. 

### Expected behavior
The game should be able to continue where it left off, like the rest of the cores do.

### Actual behavior
Display is black when resuming a game. Audio continues to play as it should and controllers still work. Sometimes RetroArch will crash as soon as it opens. 

### Version/Commit
RetroArch Plus (1.9.8) from Play Store
Mupen64Plus-Next GLES3 (2.3-Vulkan ecfc77e) 

### Environment information
OxygenOS 11.2.7.7 (Android 11)
battery optimization disabled

**Comment by twinaphex** [comment]
I think this is a core bug unfortunately, not a RetroArch bug. Core bugs belong in their own separate repos.
