### ISSUE TITLE
Core information is broken in current master (v1.9.7 -- 09d496b534)

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#12731]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

No information actually shows, just a submenu with the core name.

### Expected behavior

At least the previous information (and maybe extra information that you can see in the online downloader that explains what the core is good for if there are multiple versions of the core).

### Actual behavior

Nothing visible

**Comment by i30817** [comment]
Hey, it's possible i'm missing some part of the build process since i haven't built RA in a while, so if you can't reproduce, don't hesitate to close (and tell me what i'm doing wrong). I inited the submodules.

**Comment by twinaphex** [comment]
Hi there,
We will investigate if we can reproduce.

**Comment by sonninnos** [comment]
Core info working as usual here.

**Comment by i30817** [comment]
This is what i have after building and downloading with the online updater the current assets and core files:


https://user-images.githubusercontent.com/757900/128252535-bc1e93d4-a495-43a0-8e1d-3e766fb1f356.mp4

**Comment by sonninnos** [comment]
That is not core information, but content information. Core information is under Main Menu > Infromation once a core is loaded.

**Comment by i30817** [comment]
Oh. Then could you maybe add a 'no content loaded' string in this case? I was very confused.

**Comment by sonninnos** [comment]
How about this, since it was very simple to include:

![retroarch_2021_08_05_17_24_10_392](https://user-images.githubusercontent.com/45124675/128367013-6862e78d-4854-41c2-9409-9e2c37d10ade.png)
