### ISSUE TITLE
[WiiU] L3 and R3 doesn't work on WiiUGamepad or WiiU ProController

### ISSUE THREAD

**Issue by Ploggy** [libretro/RetroArch#12747]
The L3 and R3 buttons on the WiiU Gamepad do not work and cant be set as binds

The last stable version where the buttons worked as expected was 1.8.8 (I couldn't find a 1.8.9 stable for WiiU)

**Comment by GABO1423** [comment]
This also occurs with a Wii U Pro Controller (Wii Classic Controllers don't have L3 and R3 buttons to begin with), either way the inputs just don't work.

**Comment by gblues** [comment]
Well, that's pretty easy to reproduce.

I'm starting a bisect now to find exactly where it broke.

**Comment by Ploggy** [comment]
Thank You @gblues this has been confirmed fixed by @GABO1423 thankyou :)

Time to close.
