### ISSUE TITLE
[Android] port MacOS controller duplication fix PR to android

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#12760]
Android bluetooth controls seem to exhibit the same behavior as on MacOS. I am hoping the MacOS HID driver fix at https://github.com/libretro/RetroArch/pull/12757 will hold the solution for Android as well.

Related issues:
#12561
#11294
https://github.com/libretro/RetroArch/issues/3414

**Comment by twinaphex** [comment]
Android does not use the HID system though.

**Comment by markwkidd** [comment]
Ahh, the symptoms are so similar I assumed it must be a near copy of the OS X code. Dang.
