### ISSUE TITLE
[Feature suggestion] Make it possible to open a rom from command line without specifying the core

### ISSUE THREAD

**Issue by axredneck** [libretro/RetroArch#12773]
## Description

I want to open roms in RetroArch by double-clicking them in file manager, so i would double-click a rom and then RetroArch asks what core i want to use.

### Expected behavior

Ability to execute e.g. `retroarch contra.nes` command without `-L` option so RetroArch would ask for core in pop-up window (as it usually does when i open a rom from RetroArch WIMP GUI), so it would be possible to assign roms to RetroArch in file manager.

### Actual behavior

Currently command like `retroarch game.nes` does nothing, `retroarch -L core.so game.nes` kind of command needed which is not very friendly to external file managers, especially if user is unsure what core .so file they need for particular rom and where this core is located in file system.

### Version/Commit

- RetroArch: 1.9.7

### Environment information

- OS: Arch Linux

**Comment by arrowgent** [comment]
seems like you could do this with `Open With` in your file manager

make a script in `~/.local/bin` or `~/.local/games/retro`
making sure that in `~/.bashrc` you have set `export PATH="$HOME/.local/bin:$HOME/.local/games:$PATH"`


```
#!/bin/bash
retroarch -L $HOME/.config/retroarch/cores/core.so "$@"
```

your file manager should recognize different file types such as .nes, .smc, .sms, .smd, .n64, .gdi etc

for .iso an open with would allow you to have different cores ready to go

dont know about you, but most of mine are in .7z or .zip format to save space and containerize multiple file documents
which thankfully retroarch can open and read into memory


```
  -L, --libretro=FILE   Path to libretro implementation. Overrides any config setting.
      --subsystem=NAME  Use a subsystem of the libretro core. Multiple content
                        files are loaded as multiple arguments. If a content
                        file is skipped, use a blank ("") command line argument.
                        Content must be loaded in an order which depends on the
                        particular subsystem us
```

**Comment by arrowgent** [comment]
alternatively in terminal you can query which core you want to use
example:

```
#!/bin/bash
while true; do
    read -p "Choose Core: A)core B)core C)core Q to exit > " abc
    case $abc in
        [Aa]* ) echo A Core;retroarch -L $HOME/.config/retroarch/cores/Acore.so "$@";;
        [Bb]* ) echo B Core;retroarch -L $HOME/.config/retroarch/cores/Bcore.so "$@";;
        [Cc]* ) echo ACCore;retroarch -L $HOME/.config/retroarch/cores/Ccore.so "$@";;
        * ) exit;;
    esac
done
```

**Comment by axredneck** [comment]
Such solutions are a bit hacky, especially
> especially if user is unsure what core .so file they need for particular rom and where this core is located in file system

**Comment by eadmaster** [comment]
possible duplicate of https://github.com/libretro/RetroArch/issues/746

**Comment by axredneck** [comment]
@eadmaster , yes, it is.

**Comment by inf0rmix** [comment]
I have something similar working:

#!/bin/bash
COREDIR='/usr/lib/x86_64-linux-gnu/libretro'
function detect_core_arg() {
myrom="$1"
case $myrom in
*.gg|*.GG)                     mycore='genesis_plus_gx_libretro.so' ;;
*.smd|*.SMD)               mycore='genesis_plus_gx_libretro.so' ;;
*.gb|*.GB|gbc|*.GBC)       mycore='gambatte_libretro.so' ;;
*.gba|*.GBA)               mycore='mgba_libretro.so' ;;
*.nes|*.NES)               mycore='nestopia_libretro.so' ;;
*.smc|*.SMC)               mycore='snes9x_libretro.so  ' ;;
esac
myargs="-L ${COREDIR}/$mycore"
echo $myargs
}

retroarch $(detect_core_arg "$1") "$1"


--

I think I could even add autodetection of iso files if you are interested (I have abandoned the script but recovered it now :D )
