### ISSUE TITLE
NTSC Composite Shaders Not Working Properly

### ISSUE THREAD

**Issue by PlayNeth** [libretro/RetroArch#12778]
## Description

NTSC composite shaders have a purple/magenta tint all over them no matter the API i choose (i use Vulkan 99% of the time)

### Expected behavior

For the shaders to display composite properly without the abnormal tint

### Actual behavior

When i enable a composite shader, everything on the screen looks purple/magenta-ish

### Steps to reproduce the bug

1. Launch game
2. Pick a composite shader
3. Apply

### Bisect Results

Ever since i first downloaded retroarch, i could never really get the composite shaders to work. I made sure it was not a driver issue as everything is up to date, but the outcome is always the same, literally all of the composite shaders have this tint over the image.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.7

### Environment information

- OS: Windows 10

-Screenshot showing off the issue: ![unknown](https://user-images.githubusercontent.com/82559127/128913715-bc331f55-bd06-4489-91c7-df65370f2640.png)

**Comment by hizzlekizzle** [comment]
I can't reproduce this. Is it with any specific cores, maybe?

**Comment by PlayNeth** [comment]
> I can't reproduce this. Is it with any specific cores, maybe?

Every core has the same outcome on my end, i have no clue what is causing it

**Comment by hizzlekizzle** [comment]
Not having access to float framebuffers can cause a magenta tint, but your shot looks more purple than that, and any driver that can run vulkan should support that... Are you loading presets (e.g., ntsc/ntsc-adaptive.slangp) or bare shader passes (e.g., ntsc/shaders/ntsc-adaptive/ntsc-pass1.slang)?

**Comment by PlayNeth** [comment]
> Not having access to float framebuffers can cause a magenta tint, but your shot looks more purple than that, and any driver that can run vulkan should support that... Are you loading presets (e.g., ntsc/ntsc-adaptive.slangp) or bare shader passes (e.g., ntsc/shaders/ntsc-adaptive/ntsc-pass1.slang)?

Oooooooh, yeah i was using the latter. I loaded the preset you mentioned and now it works flawlessly. Much obliged dude
