### ISSUE TITLE
Issues pointed out for Xbox Series S/X

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#12782]
1.9.0 build 6 from dominater was the last version # with working fast forward

NOTE: The CHD loading issues have been resolved thanks to tunip3's commits.

**Comment by twinaphex** [comment]
Some more info posted by this person on Discord -

Player1Login
Here is the dolphin ini. 2 player support in dolphin was non functional in the build posted on RetroArch.com
https://discord.com/channels/184109094070779904/469974542299955210/871787986231119902

**Comment by tunip3** [comment]
I have fixed the beetle cores already in a fork, there is one more issue with arcade dat files not loading that I wanted to fix before sending a PR

**Comment by GABO1423** [comment]
> Some more info posted by this person on Discord -
> 
> Player1Login
> Here is the dolphin ini. 2 player support in dolphin was non functional in the build posted on RetroArch.com
> https://discord.com/channels/184109094070779904/469974542299955210/871787986231119902

This is not a Series X/S specific issue, it's a Dolphin core issue: https://github.com/libretro/dolphin/issues/217

**Comment by twinaphex** [comment]
I've been told these issues have been resolved.

@GABO1423 I will add this to the milestones.

**Comment by twinaphex** [comment]
On-screen keyboard display bug should be fixed now as of this commit -

https://github.com/libretro/RetroArch/commit/54ae219302f01903725d38e51cb3b3fd89b4adac

**Comment by twinaphex** [comment]
Please reopen if these problems will reoccur, closing for now.
