### ISSUE TITLE
PS2 version Sega Genesis/NES sound crackling

### ISSUE THREAD

**Issue by Ever17lab** [libretro/RetroArch#12791]
Hey. PS2 version has some sound problem, it's crackling a little.
Standalone versions of PicoDrive or fceumm dont have these problem.

I hope you fix it or somebody cares about PS2 version of RA and make some kind of optimization like delete or change some code

It's fceumm version I used https://github.com/infval/Fceumm-PS2/

They just work, no sound latency/sync settings, no external resampler (in RA core you can set your own sample rate and then change it in RA settings)

**Comment by arrowgent** [comment]
what are your system specs?
whats the cpu load when this happens?
what are your settings in the emulator?

^ factors here determine the emulation of the audio

**Comment by Ever17lab** [comment]
>what are your system specs?
it's PS2 90008. 299 MHz MIPS CPU... Regular PS2
>whats the cpu load when this happens?
I don't know, it's real hardware, can't check it
>what are your settings in the emulator?
Attached
[retroarch.zip](https://github.com/libretro/RetroArch/files/6984706/retroarch.zip)

I mean, probably PS2 needs it's own optimization to make RA more usable.

**Comment by twinaphex** [comment]
@Ever17lab any reason why you can't just use QuickNES? it'd be way faster than FCEUmm.

Also, which specific Genesis/NES games run too slow for you? I don't think you can reasonably expect every game to run at fullspeed on a PS2, but I will ask @fjtrujy regardless.

**Comment by fjtrujy** [comment]
Hello,
@Ever17lab based in my experience both FCEUMM and Picodrive stand alone apps are slower than RA ones.
You can ask @AKuHAK, how is the current “owner” for the standalone FCEUMM.

Picodrive one, from core option offer 3 different renders, use fastest if you want to have a better performance.

**Comment by Ever17lab** [comment]
@fjtrujy 
> @Ever17lab based in my experience both FCEUMM and Picodrive stand alone apps are slower than RA ones.

Try to launch Sonic 1, for example, and hear good. RetroArch has microlags, especially in 'Green Hill Zone'. Actually, sound's microlags are everywhere

Retroarch
https://user-images.githubusercontent.com/74456272/129461772-85559be7-66d5-4cc4-95d1-cb8e998f2c5f.mp4

PicoDrive

https://user-images.githubusercontent.com/74456272/129461874-27060cee-dd76-4c66-9dd4-92ed24971290.mp4

@twinaphex games do not run slow, they are fullspeed, but sound is laggy.

**Comment by fjtrujy** [comment]
@Ever17lab So if I'm right this is something, totally different else.
First of all, it is NOT a PS2 issue.

These audio differences you notice, are probably happening in other platforms as well, it is probably an issue in the `core` itself.

The standalone Picodrive version is from 5 years ago (version 1.51), and during that time Picodrive has changed a lot, including new features, fixing bugs, and maybe other bugs appear, like the one you mention.

Anyway, they aren't "micro-lags", it is just probably some error emulating audio.

Pinging @irixxx, which is the main maintainer of Picodrive nowadays

**Comment by Ever17lab** [comment]
@fjtrujy 
>First of all, it is NOT a PS2 issue.

:D yeah... It's RetroArch meme. 
![image](https://user-images.githubusercontent.com/74456272/129469819-e7099f85-d4e9-4eee-a007-bcbe08723fec.png)
I had crackling sound when installed RA on my laptop. Until sync it with refresh rate of display, just in case - Maximum Timing Skew 0.10(from 0.05) and Dynamic Audio Tate Control 0.010 (from 0.005).

It does not helps on PS2.

### It's standalone MegaMan III, Fceumm, no audio lags
https://user-images.githubusercontent.com/74456272/129469877-6036dc0b-d2dd-4c5f-a94b-8fd52a54c354.mp4

**Comment by Ever17lab** [comment]
### RetroArch's MegaMan III, QuickNES core
https://user-images.githubusercontent.com/74456272/129469965-4acedd05-9ea9-42fe-aca7-1dbe8a8de4dd.mp4

**Comment by AKuHAK** [comment]
I don't see much difference between RetroArch and standalone fceumm-ps2 implementation in terms of coding. It can be that it uses fewer resources, cause Fceumm-ps2 is hardcoded to MONO, while retroarch is STEREO. Audio buffer also filed slightly different, I am not sure why
` audsrv_play_audio(buf, size);` - retroarch
` audsrv_play_audio(buf, size << 1);` - fceumm-ps2, maybe this is fceumm core feature, which is different for retroarch.

And yes, this can be related to the video mode and sync. Currently, RetroArch is forced into NTSC mode, @Ever17lab I hope you tested NTSC versions of the games, cause the PAL version can be just out of sync.

**Comment by Ever17lab** [comment]
https://user-images.githubusercontent.com/74456272/129470065-4c6e206d-9042-46d0-80b9-d20bf34bd1f4.mp4

@AKuHAK 
>@Ever17lab I hope you tested NTSC versions of the games, cause the PAL version can be just out of sync.
Yeah. FCEumm has more hearable crackling

https://user-images.githubusercontent.com/74456272/129471945-ba661908-c085-4b22-b348-5d6a154b3178.mp4

I mean, RetroArch is **frontend** of emulator, and it could be heavy for PS2. You can set Sample Rate in core, but also in RetroArch itself, resampler works and maybe it eats CPU or...

**Comment by AKuHAK** [comment]
@Ever17lab for best comparison, you should use NTSC version of the game, and set up both: RA and core sample rate to 11025Hz.
In fceumm-ps2 you also should use the NTSC version of the game, set the sample rate to 11025Hz, and also set up NTSC video mode.
This will give the cleanest results.

**Comment by Ever17lab** [comment]
@AKuHAK 

Yeah, I use NTSC version... And with 11025 sample rate in **resampler** sound is much more crackling
https://user-images.githubusercontent.com/74456272/129472664-26325f9e-2fe0-491d-94a0-8e4bc5ab6498.mp4

May be resampler works wrong, is it possible to skip resampler and passthrough sound which is provided by core?

**Comment by fjtrujy** [comment]
> @fjtrujy
> 
> > First of all, it is NOT a PS2 issue.
> 
> :D yeah... It's RetroArch meme.
> ![image](https://user-images.githubusercontent.com/74456272/129469819-e7099f85-d4e9-4eee-a007-bcbe08723fec.png)
> I had crackling sound when installed RA on my laptop. Until sync it with refresh rate of display, just in case - Maximum Timing Skew 0.10(from 0.05) and Dynamic Audio Tate Control 0.010 (from 0.005).
> 
> It does not helps on PS2.
> 
> ### RetroArch's MegaMan III, QuickNES core
>  RetroArch_VID_20210815_100707.mp4 
> ### It's standalone MegaMan III, Fceumm, no audio lags
>  FCEUltra_VID_20210815_100903.mp4

You're mixing totally different issues between RA, Picodrive and FCEumm.

So let's go step by step, as I said again, what you post for Picodrive is not "crackling" or whatever you want to call it, this is an error in the core "Picodrive" interpreting emulation audio note.

Then regarding the other FCEUmm and QuickNes, indeed yes, resampler consumes a lot of CPU, so I have always the option disabled.

The additional, menu effects and so on, I'm not sure but it could affect as well.
Here you have how it behaves for me, with a clean installation, without any change at all.


https://user-images.githubusercontent.com/10010409/129474513-95d86e35-1a77-4408-bce6-a05130f2caa8.mov

I hope it helps for you

**Comment by irixxxx** [comment]
Are you saying this also occurs with the standalone versions of Picodrive?

**Comment by irixxxx** [comment]
I've checked a generic linux standalone build. I can't here any stuttering. If the bug is in the core it must be in the libretro interfacing.

**Comment by fjtrujy** [comment]
Hi there!
It isn't a shuttering it is wrong "sound notes" during intro of Sonic 1

**Comment by irixxxx** [comment]
Hmm, the sound update check seems fishy. Could you please apply this an tell me if it's better?
Are there other games having this problem? I would like to test that comparison limit against other cases.

```--- a/pico/sound/sound.c
+++ b/pico/sound/sound.c
@@ -237,7 +237,7 @@ PICO_INTERNAL void PsndDoFM(int cyc_to)
   len = (cyc_to * Pico.snd.clkl_mult) - Pico.snd.fm_pos;
 
   // don't do this too often (about once every scanline)
-  if (len >> 16 <= PicoIn.sndRate >> 10)
+  if (len >> 16 <= PicoIn.sndRate >> 12)
     return;
 
   // update position and calculate buffer offset and length
```

**Comment by fjtrujy** [comment]
> Hmm, the sound update check seems fishy. Could you please apply this an tell me if it's better?
> Are there other games having this problem? I would like to test that comparison limit against other cases.
> 
> ```
> +++ b/pico/sound/sound.c
> @@ -237,7 +237,7 @@ PICO_INTERNAL void PsndDoFM(int cyc_to)
>    len = (cyc_to * Pico.snd.clkl_mult) - Pico.snd.fm_pos;
>  
>    // don't do this too often (about once every scanline)
> -  if (len >> 16 <= PicoIn.sndRate >> 10)
> +  if (len >> 16 <= PicoIn.sndRate >> 12)
>      return;
>  
>    // update position and calculate buffer offset and length
> ```

Hello,
I have just tried it, and the intro of Sonic 1, now it sounds as expected.

Thanks

**Comment by irixxxx** [comment]
thanks for trying. I'll wrap up a fix.

**Comment by AKuHAK** [comment]
@irixxxx can you check https://www.romhacking.net/hacks/1059/ this hack (Track version) ? This hack has something wrong with sounds too.

**Comment by Ever17lab** [comment]
Hello everybody, @irixxxx @fjtrujy 

Thanks for answering. 

Yeah, when you asked me to try 'clean' installation, it was better. Looks like menu effects eats CPU.
The best combination is '22050 Hz' in core options, yeah.

But imho retroarch for ps2 needs optimizations/investigations. If you change some settings, like hide onscreen overlay, it could start shuttering again.

>Then regarding the other FCEUmm and QuickNes, indeed yes, resampler consumes a lot of CPU, so I have always the option disabled.

If you set 'null' in resampler, you get no sound.

I dont know how resampler works, maybe it could be some kind of 'passthrough'
Even Sonic sound is okay, there is some tiring.

It's another example of sound crackling - mGBA core & Link's Awakening. 
https://user-images.githubusercontent.com/74456272/130118755-51d7df52-eb56-4423-8555-f69ca4e3f507.mp4

Gambatte core is more optimized for PS2, but maybe RetroArch could be optimized too

**Comment by Ever17lab** [comment]
@twinaphex i found the problem, but as I know, it could not be changed via GUI

By default, audio_rate_control = "false", if key is true, there are microlags

https://user-images.githubusercontent.com/74456272/130134070-e4b01f0a-28ac-42c9-b5b4-d3216c3269ea.mp4


https://user-images.githubusercontent.com/74456272/130134094-97008bbf-239f-4ca6-9ffa-749e90d0cdd2.mp4

**Comment by irixxxx** [comment]
> @irixxxx can you check https://www.romhacking.net/hacks/1059/ this hack (Track version) ? This hack has something wrong with sounds too.

Could you possible give some detail about where the sound is off?

**Comment by AKuHAK** [comment]
> > @irixxxx can you check https://www.romhacking.net/hacks/1059/ this hack (Track version) ? This hack has something wrong with sounds too.
> 
> Could you possible give some detail about where the sound is off?

Sure:

https://user-images.githubusercontent.com/621640/130211279-e75f3a96-c817-4669-bf78-b3807afd073d.mov

**Comment by irixxxx** [comment]
@AKuHAK there's a fm sound fix in my repo. If you could compile from that you could try if it fixes the problem.

**Comment by AKuHAK** [comment]
@Ever17lab could you please test if this problem disappears if you choose the same video mode as it is in the game ROM. For example, if the game was designed for the PAL region, then set up RetroArch in PAL video mode. Previously RetroArch PS2 was forced always into NTSC, maybe this caused crackling issues.

**Comment by Ever17lab** [comment]
I could, but my brother gave PS2 to his friend. I hope that fix is worked ^_^

**Comment by AKuHAK** [comment]
Oh, this should be checked, cause this problem can be causes by many other reasons. Sound crackling problem can still be on. Maybe ps2 sound driver is too heavy and we need to lower quality (for example mono and 8-bit), maybe retroarch itself has something wrong, maybe something wrong with video sync, maybe this particular core has issues, maybe these games have issues. One possible solution, incorrect PAL-NTSC conversion should be solved, but problem can still be herw.
