### ISSUE TITLE
Quest 64 Pink Text Glitch

### ISSUE THREAD

**Issue by helladamnleet** [libretro/RetroArch#12800]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The text in Quest 64 is outlined in pink

### Expected behavior

For the text to look normal

### Actual behavior

The text is pink

### Steps to reproduce the bug

1. Open Quest 64 in any core
2. 
### Bisect Results

When you start the game.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: All of them
- 
### Environment information

- OS: Windows 11
- Compiler: [In case you are running local builds]

Works just fine in other programs supposedly, so this is absolutely a Retroarch specific problem.

**Comment by twinaphex** [comment]
> Only RetroArch bugs should be filed here. Not core bugs or game bugs

This is unfortunately not a RetroArch bug. Would need to be moved over to the relevant core repo.

**Comment by helladamnleet** [comment]
Yeah, only it literally only does it in Retroarch

**Comment by LibretroAdmin** [comment]
Use Parallel RDP in Mupen64Plus Next for the most accurate graphics reproduction. With GlideN64, assume that bugs can occur and that some of it is dependent on your GPU drivers.
