### ISSUE TITLE
Cycle text overlaps date

### ISSUE THREAD

**Issue by sakethray** [libretro/RetroArch#12807]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Bad cutting off on top cycling title when looking at full screen thumbnail.

### Expected behavior

The cycling text should end before the date.

### Actual behavior

The cycling text overlaps the date
![image_2021-08-16_145712](https://user-images.githubusercontent.com/21297955/129615455-fae7081b-a3eb-45ad-98c5-f3f098908815.png)

### Steps to reproduce the bug

1. go to playlists
2. select a game
3. look at full screen thumbnail
4. look up

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

b837e053

### Environment information

- OS: Windows 10

- Compiler: [In case you are running local builds]

**Comment by sonninnos** [comment]
This was fixed with https://github.com/libretro/RetroArch/pull/14342
