### ISSUE TITLE
Option to show notifications only in-menu, hide when in-game. (Feature Request) [Bounty]

### ISSUE THREAD

**Issue by jayare5** [libretro/RetroArch#12814]
Notifications are really useful sometimes when using the menu so that you can see if some action has been completed, or if there are errors, or knowing what kind of errors. I like to disable them so I can play games with none of these showing on top of the game, but using the menu without these can become troublesome.

**Comment by twinaphex** [comment]
What kind of notifications were you thinking of?

**Comment by jayare5** [comment]
When core configs or controller configs load together with the game, or when unplugging a controller and connecting it back (or connecting a different controller). These are things I would be fine seeing while in-menu, but while outside the menu (in-game).

I think I may have seen others, like when writing to a save file in mid-game.

**Comment by twinaphex** [comment]
OK, these are all fair things to point out.

**Comment by jayare5** [comment]
Thank you :)
And yeah the main idea is to make the games look more like the real thing. And after about 3 years of playing games with them turned off, I realized that the menu just not good to use like this.

**Comment by hexagonrecursion** [comment]
Findings so far:
* The documentation for reading and updating the settings menus can be found here: https://docs.libretro.com/development/retroarch/new-menu-options/
* The display of notifications is currently controlled by `settings->bools.video_font_enable`
https://github.com/libretro/RetroArch/blob/621c3a7b7e97f55b37a09620e73526ceabf51a6d/configuration.h#L549
* There are two mechanisms for displaying the notifications: OSD and widgets

**Comment by hexagonrecursion** [comment]
What does OSD stand for?

**Comment by jayare5** [comment]
> What does OSD stand for?

Isn't that On Screen Display?
