### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#12848]
## Description

Retorarch isn't letting me use certain hotkeys. I'm clicking F1 to open the menu and nothing happens. I also binded mouse 2 to rewind but it doesn't do anything when I click.

### Version/Commit

- RetroArch: 1.9.1

**Comment by i30817** [comment]
You might have turned on 'Auto Enable 'Game Focus' Mode' by accident, a setting which exists in the input options for cores which require the hotkeys to be disable to use the mouse.
