### ISSUE TITLE
Missing RetroArch-Joyconfig

### ISSUE THREAD

**Issue by brando56894** [libretro/RetroArch#1284]
When I clone the repository and compile everything in Arch Linux, I'm missing the binary file retroarch-joyconfig so I can't get the controllers configured. These are the only files that it gives me:

/etc/retroarch.cfg
/home/bran/.retroarch.cfg
/home/bran/retroarch-content-history.txt
/home/bran/retroarch-core-options.cfg
/usr/bin/retroarch
/usr/bin/retroarch-cg2glsl

**Comment by Alcaro** [comment]
If it's not useful, why is the package still in the repo? It confuses people.

**Comment by Kivutar** [comment]
retroarch-joyconfig is building fine for me in Arch Linux @brando56894

**Comment by fr500** [comment]
same for me in win32 and windows x64
it should output under the tools subfolder

**Comment by fr500** [comment]
Closing this for the time being, if it fails again reopen the issue.
