### ISSUE TITLE
404 Not Found: Unable to download 1.9.8 Windows 10/8/7 64-bit portable from website

### ISSUE THREAD

**Issue by mrmatteastwood** [libretro/RetroArch#12854]
## Description
When attempting to download the latest version of RetroArch from retroarch.com, the 64-bit portable version for Windows 10 cannot be downloaded. There's a 404 error.

### Expected behavior
Users should be able to download the RA 1.9.8 from the website.

### Actual behavior
"404 - Not found" when attempting to access https://buildbot.libretro.com/stable/1.9.8/windows/x86_64/RetroArch.7z

### Steps to reproduce the bug

1. Navigate to retroarch.com
2. Click on "Download"
3. Scroll down to Windows 10 / 8 / 7
4. Click on "Download (64-bit)"

**Comment by m4xw** [comment]
Works here

**Comment by mrmatteastwood** [comment]
Works for me now, too! Thanks!
