### ISSUE TITLE
Hissing/Crackling noise on Android/Vita with Resampler set to lower (default settings)

### ISSUE THREAD

**Issue by farfenkugell** [libretro/RetroArch#12869]
Hissing/Crackling noise on Android/Vita with Resampler set to lower (default settings)

Install RetroArch on Android or Vita.
Configure RetroAchievements.
Enable Unlock Sound

Receive achievements, hissing and crackling will begin.
Either disable Unlock Sound or set resampler to Normal to avoid the problem

*Might happen with other RetroArch sounds, but it is simplest for me to get.
**It impacts other platforms too, but requires to have resampler value changed from default to lower aka Windows

https://cdn.discordapp.com/attachments/434713532341288961/879747491858382868/resampler-lower.mp4
https://cdn.discordapp.com/attachments/434713532341288961/879742050453577738/Vid_20210824_175623_1-1.webm
https://cdn.discordapp.com/attachments/434713532341288961/879743968714313748/Vid_20210824_180639-1.webm

**Comment by sonninnos** [comment]
Confirmed garbage sound output also with Windows using `sinc` with `lower` or `lowest` only.

Menu sounds enabled reveals it quickly:

https://user-images.githubusercontent.com/45124675/130645877-a1616a0c-4b46-4d32-a7ab-6d6475a7c67b.mp4

**Comment by gouchi** [comment]
> Confirmed garbage sound output also with Windows using `sinc` with `lower` or lowest `only`.
> Menu sounds enabled reveals it quickly:

Same on Linux.

**Comment by twinaphex** [comment]
hi @Themaister , any clues on this? Perhaps a bug in the resampler to do with lanczos windowing function? Seeing as normal and higher uses kaiser
