### ISSUE TITLE
[Wii U] PS3 Controller Home Button and Right Analog Stick don't work

### ISSUE THREAD

**Issue by eddgar014** [libretro/RetroArch#12876]
Hi, I recently upgraded from 1.8.8 to 1.9.8 on my Wii U (I made a fresh install on a second SD Card for testing purposes), since i use a lot my PS3 controllers on Retroarch I noticed after the upgrade that the Right Analog stick and the Home button just won't work, i have no idea why, I can't even bind them, they were working flawlessly on 1.8.8.

Thank you

**Comment by Ploggy** [comment]
https://github.com/libretro/RetroArch/pull/12991

This issue is now fixed :)

**Comment by eddgar014** [comment]
Thank you very much :)
