### ISSUE TITLE
RetroArch + Popstarter = Cool PS1 emulator?

### ISSUE THREAD

**Issue by Ever17lab** [libretro/RetroArch#12879]
Heyhey. Do you know, that PS2 can launch PS2 games from USB O.o?!

RetroArch on PS2 can emulate NES, SEGA, even Neo Geo Pocket, but can't open PS1 games.

Sooo... Maybe somebody add this feature...

Instead of OPL from Jay Jay.

**Comment by AKuHAK** [comment]
@Ever17lab POPS is closed source emulator, so it cannot be used with any open source projects like ipl, or retroarch

**Comment by Ever17lab** [comment]
@AKuHAK there is uLaunchElf for launching PS1 games https://www.ps2-home.com/forum/viewtopic.php?t=5128 .
All it needs, just popstarter.elf in POPS folder.

So it's possible to send command with some light 'core' to popstarter.elf like 'open this vcd file, please'

**Comment by AKuHAK** [comment]
Sorry. This will never happen.

1. Retroarch only includes open-source cores. There is no source code for Popstarter. For example, epsxe emulator also isn't part of RA for the same reason.
2. Reotrarch only includes core, which owners allow the RA team to include. Most of the cores are developed under licenses, which allows to use their source codes as they wish. Unfortunately, Popstarter owner is sony and it will never allow to use their closed emulator.
3. While it is technically possible to hack Retroarch and popstarter to work together, no one will do it cause it can make RA less stable, and also the one who will make such a hack will be banned from the developer field. Too risky with no gain.

Sorry, such a step will cause many legal problems for all who are involved in that process. While in Russia old game piracy can be something that is not dangerous, but things differ in the whole world.

**Comment by Ever17lab** [comment]
@AKuHAK okay. Maybe somebody from community will be interested in 3rd case.

Maybe it's possible to create 'core' that could be used as postarter launcher. It's not about 'piracy', Not big problem to buy games officially, it shows respect what developers does. If developers start to create good commercial PS1 games, why don't buy it, it means that platform continues to live.

**Comment by AKuHAK** [comment]
@Ever17lab yes, but you will lose a significant part of RA. You will not be able to pause the game and call the RA menu. Most of the settings that are set inside RA will be skipped or ignored, this will make RA mostly useless. It will be almost the same as launching POPS from wLaunchELF. The only possible way, port some other ps1 emulator into ps2, but this will be an extremely hard task.

**Comment by Ever17lab** [comment]
@AKuHAK, PS1 on PS2 does not need a lot of settings, maybe some compatibility fixes. There is PS2 gamepad, it absolutely like PS1.
>this will make RA mostly useless. It will be almost the same as launching POPS from wLaunchELF
LaunchELF is not game interface, just file browser with tiny font. RA browser is much more better, it has History section.
OPL is not absolutely comfortable too, cause it needs some trick with special file names.
