### ISSUE TITLE
PS2 version supports only 'mass://retroarch/' folder

### ISSUE THREAD

**Issue by Ever17lab** [libretro/RetroArch#12884]
Can't move or create different copy of RetroArch.
Wy?

May be for different profiles or versions. But now it supports only 'mass://retroarch' folder

**Comment by AKuHAK** [comment]
@Ever17lab 
Are you sure that it supports only `mass://retroarch` ? Actually, it can be launched from everywhere. You can place `raboot.elf` and 2 folders: `cores` and `info` in any folder, the only thing you need: these 2 folders and main executable should be placed in 1 folder. For example:
```
mass://TEST/TEST2/TEST3/
|---raboot.elf
|---cores/
|---info/
```
on first boot, it will create folder `retroarch` as third folder. You also need to download assets.zip from `retroarch` main site and extract its content into `retroarch` folder. So finally you will get such a folder structure:
```
mass://TEST/TEST2/TEST3/
|---raboot.elf
|---cores/
|---info/
|---retroarch/
    |---assets/
    ...
    |---retroarch.cfg
```
You now can move the TEST3 folder anywhere keeping its internal folder structure.

of course you can change any folder location in RetroArch settings. The only path, you cannot change - path to the `retroarch.cfg`.

Please explain what exactly doesnt work for you, cause I didnt face such a problem.

**Comment by LibretroAdmin** [comment]
Guess this can be closed given the last post.
