### ISSUE TITLE
PS2 version CRT position wrong

### ISSUE THREAD

**Issue by Ever17lab** [libretro/RetroArch#12886]
Retroarch has some offset from left side (it's not centered) and could be too big in vertical

There is black vertical border in left side (in game it exists too)
![image](https://user-images.githubusercontent.com/74456272/131054328-73c46b55-c89f-4fcc-a890-3b01e4f40c16.png)

Picodrive  don't have this line

![image](https://user-images.githubusercontent.com/74456272/131054502-60b2e0fa-2f0f-42da-854a-e4ce1323de64.png)

![image](https://user-images.githubusercontent.com/74456272/131054591-9a157ac8-c421-4656-b680-da9e89cb6901.png)

Image dont fit as it should, so some pixels are cropped

![image](https://user-images.githubusercontent.com/74456272/131054788-bb8c8b4e-3f8a-4b2a-9d3b-554587f86304.png)

If activate 'only integer scale', you can see more pixels

![image](https://user-images.githubusercontent.com/74456272/131054894-dfd5ecab-4136-49a1-86dd-9e77bf36d03e.png)

So, it needs some kind of calibration for CRT or something like overscan settings.

Also, especially for really old tv, it could be useful to have internal levels or gamma control, if it does not cost perfomance. 

In pxshader formula for black point changing looks like

FragColor = FragColor *white/255.0+black/255.0-FragColor*black/255.0

Some games have brightness control

![image](https://user-images.githubusercontent.com/74456272/131055469-888ebe4e-0118-43ea-a770-f96119231a12.png)

**Comment by AKuHAK** [comment]
@Ever17lab last build has an option to calibrate the overacan, so this issue sgould ve fixed now

**Comment by Ever17lab** [comment]
@AKuHAK, cool! 
Bt the way for better PS2 experience with CRT TV it also needs color correction, at least brighness/gamma or color level calibration. CRT TVs could be burnout, so some games has brighness correction.

**Comment by AKuHAK** [comment]
@Ever17lab please close this particluar issue, if you tested it and can confirm that now it is fixed.

As regarding Brightness/Contrast - RetroaArch doesn't have this option at all. Dont mix these things. More information in this issue: https://github.com/libretro/RetroArch/issues/13213

**Comment by Ever17lab** [comment]
@AKuHAK I can close :). Brighness/gamme control mostly relative to PS2 branch, developers for CRT TV could use some optimizations.
