### ISSUE TITLE
Retroarch crashes on M1 iMac after updating

### ISSUE THREAD

**Issue by raulradio** [libretro/RetroArch#12899]
## Description

After a few tests myself this week, on the M1 MacOS version it appears that every time I update the installed cores via the online updater within Retroarch, the app crashes when trying to run anything after. A full restart of my Mac fixes things though.

### Expected behavior

Update stuff via the updater and continue on continuing on.

### Actual behavior

Crash!
[RetroArch_2021-08-27-121437_Rauls-iMac.txt](https://github.com/libretro/RetroArch/files/7068654/RetroArch_2021-08-27-121437_Rauls-iMac.txt)
[RetroArch_2021-08-27-121454_Rauls-iMac.txt](https://github.com/libretro/RetroArch/files/7068655/RetroArch_2021-08-27-121454_Rauls-iMac.txt)

### Steps to reproduce the bug

1. Open Retroarch
2. Use the online updater to update installed cores
3. In this instance, try running a version of MAME.

### Bisect Results

This definitely started once I updated to 1.9.8.

v. 1.9.8 (x64)
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: macOS Big Sur (11.5.2)
- M1, 2021, iMac

**Comment by twinaphex** [comment]
I can't help but think you are trying to update cores from one version of RetroArch (Rosetta, intel) to the other and then getting these crashes. As I said before on Twitter, right now RetroArch writes both cores to the same folder, so if you try to use both versions on the same machine, architecture mismatches can occur where you try to read Intel x86 cores on an ARM/AArch64 binary and vice versa (ARM/AArch64 cores on an Intel x86 binary).

Proper solution to this will have to be that both versions of RetroArch on Mac will start writing to their own cores dir by default so they don't overlap.
