### ISSUE TITLE
Android: Buttons don't do anything

### ISSUE THREAD

**Issue by ShlomiToren** [libretro/RetroArch#12891]
## Description

The arrow buttons don't affect the menu suddenly, A and B work, but nothing else does.
Tested using an overlay and a bluetooth gamepad.

### Expected behavior

The arrow buttons should affect the menu. I had it set up to do that for months.

### Actual behavior

The arrow buttons don't affect the menu
### Steps to reproduce the bug

1. Open RA on Android. 

### Bisect Results

It started happening yesterday. I opened a thread on reddit and someone suggested this which fixed a part of the issue:
https://www.reddit.com/r/RetroArch/comments/pbylsq/android_arrows_dont_work/haiozku/?context=3

The fix is editing retroarch.cfg, this line specifically:
input_player1_analog_dpad_mode

And changing the value from 1 to 0. This made it possible to navigate the menus, but as soon as I load any core, the buttons stop working altogether. I assumed the issue is that I have a remap for basically every core, so I tried using Notepad++ to replace every instance of this line from 1 to 0 and it seemed to have worked.
I think this should be automatic.

### Version/Commit
Build: Aug 25 2021
RetroArch: 1.9.8
Git Version: 619df7e1

### Environment information

- OS: Android 10, Samsung Galaxy Note 9

**Comment by ThunderDragonRandy** [comment]
In other words (and I'm having the same/similar issue), there is something wrong with Analog to D-Pad where if turned on in the newest version, causes all D-Pad inputs to register. With a controller overlay on, it'll show the entire D-Pad highlighted white and if I were to, let's say, start a new game in The Legend of Zelda: A Link to the Past for Super NES, the game's cursor will continually scroll downright through the letters/numbers non-stop with Analog to D-Pad turned on. But turning off Analog to D-Pad will fix the issue. An issue that occurred in the newest update.

**Comment by hizzlekizzle** [comment]
@ThunderDragonRandy I believe that was fixed yesterday if you can try the latest nightly build.
