### ISSUE TITLE
I can't start a game

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#12893]
## Description

Just now I tried to start Sonic Colors and it doesn't start, it just closes Retroarch

### Version/Commit

- RetroArch: 1.9.1

**Comment by Kirbystarallies1** [comment]
I use the dolphin core and what is an SO?

**Comment by nickmafra** [comment]
I wrote wrong. I meant OS (Operating System).

**Comment by Kirbystarallies1** [comment]
64-bit operating system, x64-based processor

**Comment by gouchi** [comment]
Hi @Kirbystarallies1 

As written in the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md),

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

So you should better first open your request in the [forum](https://forums.libretro.com).

If it is confirmed there is an issue, you should open an issue here and provide some logs.

Thank you.

**Comment by Kirbystarallies1** [comment]
I changed the driver and it still isn't working
