### ISSUE TITLE
Feature Request: remap RetroPad buttons

### ISSUE THREAD

**Issue by jprjr** [libretro/RetroArch#1289]
For example, the FCEUmm core uses RetroPad "B" for NES "B", and RetroPad "A" for NES "A"

I keep FCEUmm options in a specific file, and load it with --appendconfig. I'd really like to specify in that file that I'd rather use RetroPad "Y" for NES "B" and RetroPad "B" for NES "A" - this feels way more normal to me.

I don't think there's any way to do that while still taking advantage of the joypad_autoconfig_dir - if I can remap RetroPad buttons, then I can jump between different controllers without any problems.

**Comment by twinaphex** [comment]
This is implemented now.
