### ISSUE TITLE
core_options_path parameter not working

### ISSUE THREAD

**Issue by rtomasa** [libretro/RetroArch#12901]
## Description

`retroarch.cfg` `core_options_path` parameter only works for the very first time when a core is loaded. After the first run, a core configuration file is created (i.e. `/config/FCEUmm/FCEUmm.opt`) and that file will take preference over `core_options_path`.

### Expected behavior

core configuration file specified in `core_options_path` should take preference over all existing files as in previous versions of RetroArch (up to 1.9.0)

### Actual behavior

When you use a user config file via CLI `--appendconfig` and this file contais the parameter `core_options_path`, it is not applying/overriding other existing core config files. 

### Steps to reproduce the bug

1. Create a user config file (i.e. `user_retroarch.cfg`)
2. Add a user core config file into `user_retroarch.cfg` (i.e. `core_options_path="user_core.cfg"`)
3. Load retroarch from CLI (i.e. `retroarch -L genesis_plus_gx_libretro.so --appendconfig="user_retroarch.cfg" "sonic.zip"`
Please note that I've not used full paths in the examples above for ease of reading.

### Version
Retroarch 1.9.8

### Environment information

- OS: Raspbian Buster

**Comment by cmitu** [comment]
Do you have `global_core_options` set to `true` in your config ? Otherwise the default behavior is to save the core options in a separate (per-core) file.

**Comment by rtomasa** [comment]
You are right, after setting global_core_options = true the core_options_path param takes preference again.
Closing the issue now.
