### ISSUE TITLE
Feature Request: input device "friendly name"

### ISSUE THREAD

**Issue by jprjr** [libretro/RetroArch#1290]
This is kind of dumb - but I'd love it if there was some directive like:

`input_label = "Some text"`

Some input devices have terrible and/or confusing device names (like [my joypad](https://github.com/jprjr/retroarch-joypad-autoconfig/blob/mp-8800/udev/MP-8800_Quad_USB_Joypad.cfg) shows up as "WiseGroup.,Ltd MP-8800 Quad USB Joypad"), I would love to create a "display name" with something friendlier.

**Comment by fr500** [comment]
It's implemented already
