### ISSUE TITLE
Retroarch v1.9.8: segmentation fault accessing the audio settings menu when built with '--disable-audiomixer'

### ISSUE THREAD

**Issue by metchebe** [libretro/RetroArch#12909]
## Description

Retroarch v1.9.8 crashes when trying to access the audio settings menu when built with the '--disable-audiomixer' configuration settings.

Retroarch v1.9.7 is not affected.

### Steps to reproduce the bug

1. Compile with '--disable-audiomixer' as a configuration option.
2. Run Retroarch and try to access the audio settings (Settings > Audio).
3. Crash with segmentation fault.

### Version/Commit

Retroarch v1.9.8 is the stable version where this happens, v1.9.7 is not affected.

### Environment information

- OS: Kubuntu 20.04, Raspberry Pi OS Buster (aarch64 and armhf versions).
- Compiler: GCC 9.3 and GCC 8.3

**Comment by Ntemis** [comment]
Please take it here https://github.com/libretro/RetroArch/issues

**Comment by metchebe** [comment]
So this was probably already fixed by PR #12861.
