### ISSUE TITLE
RetroArch crashes when getting screen size in mm. (UWP)

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#12926]
## Description

When getting the system info in the UWP version of RetroArch, the app crashes. This happens when getting the screen width in mm, this is due to the fact that getting the raw dpi for the screen fails and returns with 0. RetroArch then tries to use that in division causing a crash. This happens when RetroArch is compiled with ANGLE, however ANGLE is not used at all, with D3D11 being used as the video driver instead. This does not occur when compiling RetroArch without ANGLE (both with the Debug and Release configurations).

### Expected behavior

RetroArch displays the correct System Information.

### Actual behavior

RetroArch crashes as soon as System Information is selected.

### Steps to reproduce the bug

1. Open RetroArch.
2. Go to Information, and then System Information.
3. Watch it crash.

### Bisect Results

Unknown.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Could tell you if I could see it. RA version is 1.9.8 however.

### Environment information

- OS: Windows
- Compiler: MSVC2019

**Comment by Gamr13** [comment]
Whilst I can't replicate this issue, there's another issue with System Information I've noticed:

- Display Width & Display Height do not change between 1080p or 4K.
- Display DPI does not change between 1080p or 4K.
