### ISSUE TITLE
retroarch.cfg comment values for input_menu_toggle_gamepad_combo incorrect

### ISSUE THREAD

**Issue by jcuga** [libretro/RetroArch#12928]
## Description

Looking at the comments in retroarch.cfg for the commented out `input_menu_toggle_gamepad_combo` option, I found that the documented values are incorrect.

The comments say:
```
# RetroPad button combination to toggle menu
# 0 = none, 1 = L + R + Y + D-Pad Down, 2 = L3 + R3, 3 = Start + Select
# input_menu_toggle_gamepad_combo = 0
```

### Expected behavior

Value `3` would  mean `Start`+`Select` brings up the menu.  Expect values `3` and `4` (and if there are any others...) to be documented in the config comments.

### Actual behavior

For me, I have to press `L` + `R` + `Select` + `Start`.

Only if I trial-and-error and use undocumented value of `4` does `Select` + `Start` work.

### Steps to reproduce the bug

1. Uncomment and assign a value of `input_menu_toggle_gamepad_combo=3`
2. While playing a ROM with gamepad controller, try to bring up the menu.
3. `Start` + `Select` does not work.
4. From trial and error, it looks like `3` really means `L` + `R` + `Select` + `Start`, this brought up the menu.
5. Exit, change config to use `4` instead of `3`
6. Try accessing menu, now with a value of `4` the `Start` + `Select` works now.

### Bisect Results

Happens whenever un-commenting out the config line and assigning value `3` or `4`.

### Version/Commit

The version used was:
```
RetroArch: Frontend for libretro -- v1.9.7 -- 8373ac6 --
Compiler: GCC (8.3.0) 32-bit Built: Jul 29 2021
```

FWIW I was using an 8BitDo Zero2 controller, using this retroarch-joypad config:
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/8BitDo_Zero2_gamepad_BT.cfg

And pair it with `B` + `Start`.

However it looks like this may be miscommented for a while.

### Environment information
raspberry pi 4 / raspian

**Comment by bslenul** [comment]
PR made with the new combos available and adjusted values:
```
0: None
1: Down + Y + L1 + R1
2: L3 + R3
3: L1 + R1 + Start + Select
4: Start + Select
5: L3 + R1
6: L1 + R1
7: Hold Start (2 seconds)
8: Hold Select (2 seconds)
9: Down + Select
10: L2 + R2
```
