### ISSUE TITLE
openal on OpenDingux sometimes experiences thread deadlock on exit

### ISSUE THREAD

**Issue by anderbubble** [libretro/RetroArch#12946]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

openal on OpenDingux sometimes experiences thread deadlock on exit.

### Expected behavior

"Quit retroarch" from the menu causes the program to exit.

### Actual behavior

"Quit retroarch" from the menu (and with shortcut key combos) causes retroarch to hang indefinitely. Grepping around with strace, and looking around in /proc/<pid>/task indicates that there are two threads stuck in futex wait.

### Steps to reproduce the bug

1. Run RetroArch on an RG280v or similar using audio_driver="openal"
2. Quit RetroArch
3. Repeat until you lose the race

I've found that quitting after rapidly switching between emulation and the UI increases the likelihood of a hang.

### Bisect Results

unable.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: b2c87baa

### Environment information

- OS: OpenDingux Beta (via ADAM image, see https://github.com/eduardofilo/RG350_adam_image/issues/3)
- Compiler: GCC (10.2.0) 32-bit

**Comment by anderbubble** [comment]
@jdgleaver, in case you're the right person to be looking at likely-OD-related issues. ☝️

**Comment by jdgleaver** [comment]
Oh, that's a nasty one...

I'm not able to reproduce on either stock OD or regular OB Beta (not ADAM image), but since thread races are tricky/random this might just be down to bad luck on my part. There are no issues with OpenAL on desktop Linux, however. It is quite possible that there is a defect in the OpenAL library shipped with OD Beta (e.g. I see that iOS had some threading issues with its OpenAL library at some point: https://developer.apple.com/forums/thread/103727)

Since OpenAL on OD Beta has markedly worse performance than ALSA (which appears to be 'safe' in all cases), I think we might be best off just disabling OpenAL entirely on this platform...

**Comment by anderbubble** [comment]
@jdgleaver I'm nervous about assuming I'm correct in my observations. Given that I can reproduce the error somewhat reliably, is there something I can give you off my device (e.g., a gdb backtrace or some such) that would let you confirm what's happening on the stuck threads? I tried pulling one myself, but gdb said that it couldn't find the start of the functions that the threads were running. But maybe that's only because I don't have any debug symbols?

I'm a sysadmin, so I know my way around linux processes; but I'm not much of a developer, and certainly not a firmware of RA developer; so I don't want to have unmeritedly influenced dev here.

Thanks for your attention, though!

**Comment by jdgleaver** [comment]
@anderbubble We already had a request to remove the (essentially redundant) OpenAL driver on OD Beta: https://github.com/libretro/RetroArch/pull/12929, so you needn't worry too much :)

If you do want to test this further, then a gdb backtrace should be fine. The binaries that we distribute indeed have no debug symbols (and they are stripped for good measure), but here is a `DEBUG=1` build that gdb should be able to read: [retroarch_rg350.zip](https://github.com/libretro/RetroArch/files/7116779/retroarch_rg350.zip) (there's both an OPK and a normal binary there, whichever you prefer to use)

**Comment by anderbubble** [comment]
Here's what I was able to get. I expect it's not super useful yet; but tell me what to change and I'll try again.

[retroarch-odbeta-hang-bt.txt](https://github.com/libretro/RetroArch/files/7117109/retroarch-odbeta-hang-bt.txt)

**Comment by jdgleaver** [comment]
Okay - the way you want to run this is probably as follows:

- Copy the 'raw' `retroarch` binary to your home directory
- Log in via SSH (and put the device in terminal mode)
- Run:
```
$ cd ~
$ gdb ./retroarch
(gdb) run
```
- Play with RetroArch until you trigger a hang
- Back in the terminal, hit `Ctrl+C` to terminate the process
- Enter `thread apply all bt` to get a full backtrace
