### ISSUE TITLE
[3DS] Have the option between "Tap the Touchscreen" and Status screen

### ISSUE THREAD

**Issue by DarkSide1305** [libretro/RetroArch#12951]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Theres is no option (as far as im aware, did ask for help on the Discord, Moderator hunterk told me to open a feature request here) to switch between the old Status Screen, which shows FPS etc. and the new, useless "Tap the Touchscreen". In my opinion the best way to solve this would be: Allow the user to change between the old Status screen and the "Tap the Touchscreen", but always show the "Resume game", "Create Restore" point when the Game is Paused and the RetroArch Overlay is up.

### Version/Commit
RetroArch: [version/commit]
1.9.9 Stable

- OS: 3DS

**Comment by MrHuu** [comment]
@bulzipke Did look into the feature as mentioned in this issue, as i quote ( from PR: https://github.com/libretro/RetroArch/pull/12470 ):

>
> I wanted to allow this to be turned on and off as an option, but it appears to be an  unsupported feature.
> devkitPro/libctru#476
>

So to my knowledge this behavior cannot be implemented.

There are a few other options which may satisfy your needs:

* There is an option to display statistics such as fps available here:
```Settings -> On-Screen Display -> On-Screen Notifications -> Notification Visibility ``` 

* The console was mainly there for debugging. If you still need the logging, you could enable ```Setting -> Logging -> Log to File```.

* If you want to debug, you could build the project with the console enabled. For this, build with ```CONSOLE_LOG``` enabled in the makefile.

**Comment by DarkSide1305** [comment]
Ah, damn. Well, I actually didnt really care for anything BUT the FPS, but it was just neat to have the FPS in a place that doesnt obstruct the main screen and on a Screen that isnt used. Well, thank you either way

**Comment by MrHuu** [comment]
Adding an fps counter on the bottom screen could definitely be an option.
I'll keep this in mind with future development of the bottom screen functionality.
