### ISSUE TITLE
RetroArch 1.9.9 (09-06-21) loading 7Z files are being decompressed in disk temp

### ISSUE THREAD

**Issue by Augusto7743** [libretro/RetroArch#12957]
Loading Genesis, Supergrafx and some others cores ROMs 7Z files are being extracted in temp folder.
Have cores that not extract in temp folder example mednafen pce fast. 
In previous versions not was need extract to temp folder.

**Comment by LibretroAdmin** [comment]
Not enough info. Which platform, etc.
