### ISSUE TITLE
[Linux, udev input] mouse devices are duplicated on core change

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#12959]
## Description

When using the udev input driver (which enables multi-mouse handling), mouse device indices are re-registered on each core change, including dummy core loading. Issue was requested by @markwkidd.

### Expected behavior

Mouse indices are registered once on initial load, and possibly as new devices are added.

### Actual behavior

Mouse indices are duplicated with each core change, with all duplicates being non-functional.

### Steps to reproduce the bug

1. Start retroarch with udev input driver active
2. Observe mouse indices (Settings > Input > Port 1 Controls > Mouse Index)
3. Load any content
4. Observe mouse indices, which are now duplicated in previously empty slots
5. Close content
6. Observe mouse indices, which have duplicated yet again.
Ad infinitum...

### Version/Commit

- RetroArch: 1.9.9 c9e587a5a7

### Environment information

- OS: Linux Mint 19.3 x86_64, kernel 5.4.0-81
- Compiler: gcc 11.1.0

**Comment by gouchi** [comment]
I reproduce the issue.

`static int` is needed for the [index](https://github.com/libretro/RetroArch/blob/master/input/drivers/udev_input.c#L1231-L1232) of keyboard and mouse ?

**Comment by grant2258** [comment]
These variables are only used in this function for logging nothing else.
