### ISSUE TITLE
[3DS] Save RAM state to file on 'Close Content'

### ISSUE THREAD

**Issue by MrHuu** [libretro/RetroArch#12950]
## Description
@bulzipke 

Save-states held in RAM are not getting written to a file when content is closed through the 'Quick Menu'.

### Expected behavior

The save-state written to the RAM while a core is running, should be saved to the SD card on closing content with: ```Quick Menu -> Close Content```

### Actual behavior

Currently the save-state only gets written to the SD card when either the lid closes or when the video driver gets de-initialized (exit / restart).

When selecting ```Close Content```, the video driver remains active so the save does not get triggered.

### Steps to reproduce the bug

- Create a save-state using the 3ds's bottom screen
- Close the game through the quick menu: ```Quick Menu -> Close Content```

### Related PR:
https://github.com/libretro/RetroArch/pull/12470

**Comment by bulzipke** [comment]
Thank you for letting me know the issue :)
I'll fix it.

**Comment by MarioKartFan** [comment]
I notice that sometimes the save state does not get “permanently” written if I select the command to restart retroarch or if I quit retroarch with the home button. It’s strange because sometimes I will play, save a save state, die and reload that save state and it works fine. Then I close retroarch or hit the restart retroarch command and the new save state has been replaced by an older save state. It’s almost as if the save state was kept in ram but not written to disk. 

The save state screenshot saves but the updated save state disappears. Is that related to this bug?

**Comment by MrHuu** [comment]
@bulzipke 
In ```ctr_gfx.c``` we already keep track if there's a savestate in RAM with: ```ctr->state_data_on_ram```.

```
if (!rarch_ctl(RARCH_CTL_CORE_IS_RUNNING, NULL)) && ctr->state_data_on_ram)
{
   save_state_to_file(ctr);
   ctr->state_data_on_ram = false;
}
```
Maybe something like this? This should save when using: ```Quick Menu -> Close Content```

@MarioKartFan 
Yes that would be a similar issue. I do believe most cases should be accounted for, with the case above solved.
I'll keep an eye out for similar cases, thanks for mentioning.

**Comment by bulzipke** [comment]
@MrHuu 
Your suggestion is simple and cool!

I'm sorry, but I implemented it in a different way.
I'd appreciate it if you could review it when you have time :)

**Comment by MrHuu** [comment]
That's even better than my 'quick fix'!
This should cover just about every case for writing the save-state to the sd.

I'll leave this issue open for now, until we made sure every case is covered including the ones @MarioKartFan mentioned.

**Comment by MarioKartFan** [comment]
The changes that @bulzipke pushes seem to have addressed the problem of disappearing save states. But there is another issue. I am not sure whether it is related. Probably not. I opened it as an issue on the libretro GPSP core GitHub as well. I have pasted it below too. 

Testing the latest nightlies on my N3DS, I have found save states with the GPSP are erratic at best. Sometimes they save and load flawlessly. Other times they load, but with a loss of user control.  Other times they load, but with a loss of all sound.  Still other times they crash with a fatal system error, requiring a reboot. 

All other cores seem to have working save state support without these issues.  I do not know whether these issues occurred prior to the PR that reworked save states on the 3DS.

**Comment by bulzipke** [comment]
I checked that the sound was mute when Save -> Load using a hot key.
Using hotkey is a function that existed(not ram states), so it's different from the function I PR.

This seems to have to be a separate issue.

But @MarioKartFan, thank you for your sharpness!
