### ISSUE TITLE
[Linux] Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by TPO100Cofficial** [libretro/RetroArch#12967]
## Description
A: whenever I download a Core, it won't show up in the "Load Core" option.
B: whenever I select the "Load Content" option, RetroArch immediately crashes.
C: whenever I close RetroArch, or RetroArch crashes, all of my settings are reset.
Including,
D: by default, the "download cores" option is missing, and must be turned on manually.

### Expected behavior
Normal app functionality to ensue, e.g. not crashing.

### Steps to reproduce the bug
1. Download RetroArch on Linux. (AppImage version, x64)
2. Open RetroArch from a terminal.
3. Go to Online Updater. "Download Cores" will be missing.
4. Go to settings, and enable the option to show "Download Cores".
5. Go back and download any Core.
6. (optional) Look at the "Load Core" option. It will be empty, aside from an error that reads, "Directory Not Found", and the options to Start Video Processor and Start Remote RetroPad.
7. Attempt to load the "Load Content" option.
8. RetroArch crashes. Look at the terminal. The text reads,
`Segmentation fault (core dumped)`

### Bisect Results
I have no clue why this happens. It's just always been here for me. Well, aside from the outdated 1.7.3. version on Linux Mint's repo, which works, but has an entirely different interface skin, and is also wildly unstable.

### Version/Commit
RetroArch 1.9.9.

### Environment information
Linux Mint 20.2 Uma, Cinnamon.

**Comment by hizzlekizzle** [comment]
It sounds like your configs are getting mixed up between the AppImage and the distro package (which normally hides the core downloader and uses distro packages for cores instead). Try purging the RetroArch and libretro packages from your package manager and then re-download the AppImage, or else use the portable home directory that comes with the AppImage.

**Comment by TPO100Cofficial** [comment]
yep! that worked, thank you!
..how do i switch from the switch-like theme to the playstation-like theme now?

**Comment by gouchi** [comment]
@TPO100Cofficial Please close issue as it is fixed.

Please bear in mind as written in the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md),

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
    This is not a forum or a help section, this is strictly developer oriented

>  ..how do i switch from the switch-like theme to the playstation-like theme now?
Go to Settings->Driver settings->Menu Driver, switch to the menu driver of your choice.

Thank you.
