### ISSUE TITLE
[Wii] - audio is crackling.

### ISSUE THREAD

**Issue by tomudo** [libretro/RetroArch#12965]
## Description

v1.9.x audio is crackling. It has a little static noise noticeable by earphone. I tested v1.5.0, not have this issue. Standalone snes9x also has no audio issue.

### Version/Commit

- RetroArch: Stable 1.9.9

### Environment information

- OS: Wii

**Comment by tomudo** [comment]
Use compiled v1.7.9 with no sound issue
```
cd
wget "https://github.com/libretro/libretro-toolchains/blob/master/wiiu.tar.xz?raw=true" -O "wiiu.tar.xz"
export DIR=$PWD
export PATH="$DIR/tools/devkitpro/devkitPPC/powerpc-eabi:$PATH"
export DEVKITPPC="$DIR/tools/devkitpro/devkitPPC"
export DEVKITPRO="$DIR/tools/devkitpro"

git clone https://github.com/libretro/libretro-super.git
cd libretro-super
git checkout v1.7.9 
./libretro-build-wii.sh
cp dist/wii/*.a retroarch/dist-scripts
cd retroarch/dist-scripts
./dist-cores.sh wii
#compliled files store in ~/libretro-super/retroarch/pkg/wii
```

with a bit modify -Os flag in Makefile.griffin to run some memory hog core successfully.


Hope it will fix sound problem in future.

**Comment by gingerbeardman** [comment]
@tomudo can you provide compiled 1.7.9?

**Comment by tomudo** [comment]
I could not find my compiled 1.7.9 in my computer now.

[gingerbeardman](https://github.com/gingerbeardman) , you can download 1.7.4 and 1.8.1 compiled by lib version r29 / r30 from -> https://drive.google.com/drive/folders/1J4ANLMZQLfhNtHltcA_WUY42W-zeDeOU?usp=sharing
