### ISSUE TITLE
[Linux, x input] Mouse indices are all marked N/A, but only index 0 functions.

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#12975]
## Description

The x input driver can't identify mice separately, so all mice will register under the same index. Unfortunately, this isn't well-indicated. Only mouse index 0 functions, but all indices are marked N/A. 

### Expected behavior

Preferably, all mouse indices would function the same for any input driver that can't distinguish between them. Alternatively, at least labeling the one functional index would be sufficient to reduce confusion for users.

### Actual behavior

Mouse index 0 works, indices 1-15 do nothing at all, all indices share a (lack of) label.

### Steps to reproduce the bug

1. Change input driver to x (or presumably any other driver that doesn't distinguish between mice).
2. Change mouse index to any index other than 0 and start a game.
3. Attempt to use the mouse for input.

### Version/Commit

- RetroArch: 1.9.9 b5138b6122

### Environment information

- OS: Linux Mint 19.3 x86_64, kernel 5.4.0-81
- Compiler: gcc 11.1.0

**Comment by sonninnos** [comment]
How about simply like this?

![retroarch_2021_09_16_00_20_08_577](https://user-images.githubusercontent.com/45124675/133511167-359daacc-ef78-4bbf-9a26-be2b9aab18b0.png)

I picked "Default" because the string already exists, and can't think of a better string..

**Comment by Sanaki** [comment]
Sure, that'd alleviate confusion to a reasonable degree. Honestly, almost any (understandable) string would probably suffice. I assume making them all work the same instead isn't actually feasible?
