### ISSUE TITLE
Manual scanner playlists are taking their name from the directory scanned not the custom system name

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#12993]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I think this is a regression.

### Expected behavior

Custom system name, or just system name if that was chosen was the name of the playlist. 

### Actual behavior

The name is the directory name of the scan directory.

### Steps to reproduce the bug

1. just manual scan

### Bisect Results

I was feeling lazy so i didn't do one.x\x\

### Version/Commit
You can find this information under Information/System Information

- RetroArch:  v1.9.9 -- 78858a9474 --

### Environment information

- OS: linux x86-64, ubuntu 20.04.something.
- Compiler:  GCC (9.3.0) 64-bit Built: Sep 15 2021

**Comment by i30817** [comment]
I'm pretty sure this is a regression because i don't remember having to manually change the names. I think that the there was supposed to be a fallback and if the user didn't give a system name (either a invented one or one of the normal ones), the directory name was used, but i never ended up in that situation because i'm always using a custom system name and a xml file.

Might have been a refactor recently.

**Comment by i30817** [comment]
Also, right i forgot since it was you doing the refresh new stuff, @jdgleaver

**Comment by jdgleaver** [comment]
I'm not sure I understand the issue!

Everything is working fine on my end, and the behaviour is exactly the same as it's always been. Content directory name is only used as the playlist name if `System Name` is set to `<Content Directory>`. If you do this:

![Screenshot_2021-09-15_10-40-20](https://user-images.githubusercontent.com/38211560/133411447-b3914644-0148-4555-9e33-77d911f5a9e2.png)

...then the playlist will be output as `my playlist.lpl`

Everything depends on the `System Name` setting - these all work correctly:

![Screenshot_2021-09-15_10-40-30](https://user-images.githubusercontent.com/38211560/133411660-fdbfab36-d848-4043-8170-57e377978e94.png)

**Comment by i30817** [comment]
It's not possible to screen shot in a single file, but here is my experience:![image](https://user-images.githubusercontent.com/757900/133415032-197cbf6d-4056-46cc-af77-d901c30a385e.png)
![image](https://user-images.githubusercontent.com/757900/133414983-5ffb833c-43b2-4cf8-a807-22ad038d6e97.png)


At first i thought the portable playlists setting would be influencing this but i turned it off and on and it didn't make a difference.

**Comment by i30817** [comment]
Edit: i get it. There is a new 'Content directory' option on the system name and it's on by default.

False alarm i guess, just a slight change in behavior.

**Comment by jdgleaver** [comment]
> Edit: i get it. There is a new 'Content directory' option on the system name and it's on by default.
> False alarm i guess, just a slight change in behavior

That's how it's always been, right from the start: https://github.com/libretro/RetroArch/pull/9795

Anyway, I'm glad you got it working :)
