### ISSUE TITLE
Everything Wrong With Retroarch?! A massive complaint to why people think it fucking sucks. 

### ISSUE THREAD

**Issue by dawnbomb** [libretro/RetroArch#12995]
Inspired by the steam forum topic "Convoluted" by Chelle, and a prompt by Developer Gadsby to post feedback,
this is a Quality Assurance Write-up Complaint about everything bad, unintuitive, convoluted, and otherwise
in need of serious QA (Quality Assurance) love. Retroarch NEEDS to up their QA to be able to act as a platform
for emulators. This post is meant to be intentionally hyper-critical and nitpicky but also it's easy because retroarchs end user experience is just that fucking bad, seriously point out many real problems with the Retroarch experience, and help bring it up to the next level, if taken seriously, should help retroarch hit console or platform level quality it is so desperately missing.

==================Chapter 0: I Didn't Even Launch It Yet And I Have Complaints=================

I'm going to start by looking at retroarchs website and steam page, and boy, before we even launch retroarch
for the first time, is there a lot to talk about already. Infact, to even do this write to attempt to
talk about it, the issues section on github i was pointed to, to do this write-up says bug reports only.
Currently, i'm under the assumption i'm already somehow breaking the rules by doing what i was told.
Not a good start.

Lets look at the Website and steam page front pages. I kind of whats to talk about them both at once.
I'll start with the opening description on both. It's to technical. Retroarch as i see it, is looking to be
a platform, like steam, to access things. Like the playstation XMB, or switch home screen. For a description,
on the site we get "RetroArch is a frontend for emulators, game engines and media players." and on steam 
"RetroArch is an open source and cross platform frontend/framework for emulators, game engines, 
video games, media players and other applications"

This actually tells a user very little about what retro arch is, and isn't. Even people emulaitor savvy won't
be able to parse the jargon being thrown at them. a 'frontend' for emulaitors? lets google frontend. 
"frontend can refer to any hardware that optimizes or protects network traffic." People aren't playing these
online, or it's not their first thought. They don't need protection from the net when playing mario. Okay,
maybe a smart person will think it has multiple definitions, and google more accurately. lets google Frontend Program
"A Front End developer (dev) works with designers and Back End devs to create a website" Well, retroarch
isn't a website, it's a program itself. Already, using the term frontend is so much. And no, i won't rest
on these things, if you want retroarch to really suceed, to shine, you need to make it marketable and 
understandable. when people say convoluted, you shouldn't need an hour of research to even read your 
opening sentences.

it also says 'game engines, and media players'. Why? Lets be honest, retroarch runs emulators. Thats what it
does. Why do you need to complicate this? why can't you speak english? the steam page says emulators,
so someone knew that word, why aren't these two sources on the same page for their advertising? Unfortunately
the steam page then says game engines, video games, media players, and other apps.
What fucking goon is downloading retroarch just to play music. This is not a good use of advertising space.
the human being looking at your steam page can see the music menu in your advertising images. Use your text
space better!!! Seriously, why is this so hard! also, it says emulators, then game engines, then video games.
pick ONE! these are all synonyms in practicality. People also don't need to know it's open source
in your intro, you can say that later. 

Here is a good opener. "RetroArch is a all in one platorm for Emulation  that enhances the games you play
and other Cores. From retro era to modern games, you can even play online with friends!" 

This is a fantastic, easy to digest, explanatory, to the point advertisement that tells people what
retroarch is, what it DOES (Enhances games), and avoid words like "nintendo" or "platstation" while still
getting the "old to current" idea across. Make your text readable to people! If they want more
they can hit up a FAQ. Note: Going forward, i will be referring to a reasonable way to read something, or
a problem with text that is to jargin-driven as "Readability" as a unbrella term. This will come up A LOT
and will be a serious problem with retroarch in nearly every part of anyones experience. Please remember this.

Lets move on. in the websites next section, it says you can run original game discs, but steam says 
the feature isn't out yet. These are literally giving conflicting information. Seriously? ITS YOUR FRONT PAGE!

Next, lets look at some visuals here. For the website, i want to look at the "A polished Interface" Slide.
This makes it look like playstation, cool. Except this isn't what it looks like in retroarch by default.
Make it clear this is a skin. Also, ironically, the interfact is excessively NOT polished, but
i will be getting to that as a major complaint in another chapter. But right now, it's a skin, say it's
a skin. The very idea their not showing the default skin here, implies someone who it was terrible and
tried to hide it. Maybe ask why they needed to hide your real interface? We will get to that later...

Moving back to steam, lets look at the slides/image roll. First is the trailers. All three are really fucking bad.
Trailer 1: its a fun logo (sure, fine) then shows the menu with garbage readability that makes a person
want to flee just looking at it, followed by showing what has GOT to be one of the WORST POSSIBLE game examples.
like, you CANNOT be serious. the website slides show mario, and this trailer has a level ID called zero / 
megaman129. Show us a actual video game. Make the trailer show like 8+ games of diffrent genres. 
Make it CLEAR that retroarch plays VIDEO GAMES, and not, whatever the fuck that is. Bad advertising affects
end user readability to understand what retroarch is and is not. and this is confusingly bad.

Trailer 2: Literally a logo. Why is this here? Remove it.
Trailer 3: This feels like a meme. Seriously, this is cruel, it hurts. It's like someone took what 
makes a good intro vieo and butchered it to the max. No BGM, no person explaining things, no examples
of games being played, it's super fast (Epilepsy enducing even?). So fast you can't even read all the text
without pausing the video. Please make a real trailer. Look at like, any nintendo direct. Do that, but 
for retroarch. Show off and explain lots. I'll help QA it if you need someone. You need help.

Then the steam slides, their mostly the exact same menu. Why? Show off various parts of retroarch? 
Actually make people interested. Your telling me you create all of retroarch, and the only part
you want people to know about is 2 screens? wtf? 

Now i can go on, but the pre-retroarch experience is getting comically long at this point.
I'll move onto artual retroarch, but rest assured, i can REALLY go on about whats wrong before even downloading.

In summary
1: Very poor readability
2: Poor advertising
3: Bad use of space
4: inconsistent between steam and website
5: Doesn't actually say what retroarch does in words people can understand let alone google. 

================Chater 1: "A Polished Interface"? Actually It's Really Fucking Garbage=========================

Before i actually talk about the REAL first impression, i want to point out i downloaded website and steam
both, to check for diffrences. Guess what? The first impression is diffrent. Inconsistent again? Ugh.
From website, it launched windowed, and you lack the cool cursor, and get the ultra low quality windows
menu that feels like a 2005 program with file/command/windows dispite that retroarch has it's own in-app menus.
This doesn't happen on steam, it launches in fullscreen on first boot. The diffrence here is very important.
Not everyone knows you can Alt+Enter programs to fullscreen them. Infact, this is semi-rare info. 
This is made worst by F11 being the windows default to fullscreen, but boy do i wish complaining ended here.

If a non-steam user tries to fullscreen by hitting F11, retroarch hotkeys this to swapping between the windows
and custom cursor. Now, the custom one looks good, but it locks you into the windows. Surely you can
make your cursor not get locked, come on. But even worse, is when someone wants out and presses F11 again. 
I CANNOT BELIEVE how bad this is. If you are multi-moniter, your cursor is now locked to the moniter
retroach was in itself, untill you move retroarch. Clickin on it, pressing hotkeys ect won't fix this.
I don't mean using the retro cursor, i mean normal windows cursor, you can't leave your moniter. 
what the actual fuck? what a joke! I haven't even talked about retroarch contents directly, and
i can barely type up this QA review because retroarch literally won't let my cursor go click on notepad. >:(

it gets worse. If your fullscreen and press F11, your cursor doesn't change, but your mouse still can't
leave the moniter. The user would have no idea why and think retroarch is just a bad program. How can
you have this many errors and i'm not even talking about retroarch itself yet?????

OKAY, actual retroarch time. So, we boot into the main menu that is...lacking readability at best. 
"Load Core"? Why? these thing are called emulators, call them emulators. "Load Emulator" is perfectly
reasonable english, i genuinely don't care if theres a technical reason to call them cores. You want to be
a marketable, understandable program? speak in words people actually understand. Change Load content to 
Load Game. However, it's my understanding the team personally wants 'Core' as they want to do more then emulators.  In counter to this, i suggest splitting the menu between Emulators, and other Cores.Also, this menu is bloated.

So, 
1: Split the cores menu, between "Cores", and a new one called "Emulators"
2: In addition to Load Content, add a new menu called Load Game right under Emulaitors.
3: Change Esc defaulting to exiting the program, to a back button. This is semi-common, and straight up default
in nearly every PC game. If your a platform on a PC for people gaming on a PC, use a PC control scheme. wtf?
there is a quit button if needed, and Alt+F4 or Alt+Enter, we don't need to troll PC users with a comically
bad default control scheme.

"Bloated" i'm going to define, as to many things being in one menu, or things being in the wrong location.
Here, we have the main menu showing config, info, and help. But we have a left side bar. whats the 
diffrence between config and settings? this is already a readability problem, their synonyms. 

Now, i'm gonna be going all over unfocused here, because there is so many problems their all interwoven.
The Config file menu, why is this a menu? 

1: Delete the Config menu entry
2: Move the contents of the config menu, to the top of the settings menu. 
3: Why is help a menu with only 1 content? Literally delete this menu.
4: Move Menu Controls and it's icon to the bottom left of retroarch below the white line. This menu is 
first of all stupid and should probably be removed entirely, however...
4.5: Rename Menu Controls to Controller and have this lead directly to the input menu. If you really want,
include the Menu controls in Controller, but really it's common sense, and people can customize this,
so the stated controls in Menu Controls can literally lie to the user, this is dumb.
5: on first startup, maybe do a first time setup that asks the user what menu icons they would like.
let them pick from switch, xbox, playstation, ect. Its also kinda bad to display Switch by default, but
use american playstation input scheme, and not having a switches A button actually be A. Readability issues!!!!!

Now we have a nice (enough) looking home. Onward to settings. The entire thing is bloated. There is also a lot
of 2-menus required trolls. There are so many times you look in one menu and need to google to find another
menu, it's not even funny. 

1: First up, just like the white line at the bottom of retroarch, i recommend a new break line in the middle
of settings. Things below it will be advanced settings, and title the section Advanced. Alternatively, if
this won't translate well to alternate skins, instead have a menu in here called Advanced at the bottom of settings.
Rename Saving to Saving Games (Readability, this seems like save Retroarch settings when it's here like this!)
2: Throw logging, File Browser, On-Screen Display, AI Service, Latency, into Advanced.
3: Delete the entire power management menu. wtf is this? It's literally empty. LITERALLY, USELESS. WHO????
4: Rename Network to Online, or Online Multiplayer. (Readability!)
5: Rename Input to Controllers

6-1: On the left bar, Rename Import Content to "Create Playlist" (Because that is literally what it does)
6-2: Move the playlists menu into the now named "Create Playlist" menu, de-bloat settings, so only people 
who care about the playlist menus are forced to see and scroll past this option. 
6-3: Add a button named "More Information on Playlists" or maybe "Playlists Tutorial" or similar as well
to explain what is a 'Playlist', how to set them up, needing cores/emulators, ect.
6-4: if a Scan to create a playlist in a directory comes up empty, have a pop up explaining why. (Missing cores, ect)

7: I cannot believe you have a menu called configuration here, when i earlier talked about configuration in
the main menu. Why do you have 2 config menus, and a settings menu? HELLO? This is SO OMEGALUL TROLL, the
config options in settings/config effect your stuff in main menu/config. Why the fuck are they not together?
Who designed this? *Phew* now that thats done. 
7-1: In this submenu, move 'Use Global Core Options File' to the 'Load Core' Menu we are renaming to 
'Load Emulator'.
7-2: We are also renaming this option "Use Global Emulator Options".
Readability is very important! 
7-3: Finally, If (hopefully) Main menu config is moving to settings, either delete this Configuration menu, 
and move its only remaining option (Save Config on Quit) to settings, or move the config stuff from 
main menu, inside this config sub-menu. 

8: AGAIN with the 2 menus needed trolls. Inside Directory we have a lot of playlist stuff, why?
8-1: In playlist menu (that we are moving to the Music Menu) create a new menu called Playlist Directories
8-2: Move everything playlist related from settings/Directory to Music/Playlist Directories. 

9: Speaking of multiple same named menus, we have achievements, and a users achievements. STOP DOING THIS!!!!
why do you want people to need to google one menu doesn't work without the other menu! THIS IS SO TROLL, STOP IT!
9-1: Rename User to Account Settings & Achievements
9-2: Move the achievements menu into this newly named menu to de-bloat settings, and put this in a reasonable spot.
9-3: The Accessability menu only has 1 option in it. Stop having troll 1 option menus. Delete this menu
9-4: Rename the Sub-menu "Accessibility Enable" To "Text to Speech"
9-5: Move "Text to Speech" to the Account Settings & Achievements, so one user can use it, and
another diffrent user doesn't have to deal with troll text to speech in their ears. 
10: Continueing from 9, we have streaming options in account, and them in recording. WHY.
10-1: Rename "Recordng" to "Recording & Live Streams"
10-2: move the the content of the now "Account Settings & Achievements" / Account  / Retroachievements to
the Achievements menu that was moved here in part 9. 
10-3: The Youtube/Twitch/Facebook Gaming sub-menus only have 1 content, STOOOP FUCKINGGG DOOOING THIIIIS. >:((((
we are deleteing these sub-menus. 
10-3: Move Youtube/Twitch/Facebook Gaming sub-menu stream key options from here, to the now 
named "Recording & Live Streams" menu. 
10-4: in the "Recording & Live Streams" menu/Streaming Quality, give one of those grey sub-descriptions.
Something like "Suitable for 720P Streams" "For 1080P Streams" Ect. 
10-5: Also rename the menu to Stream Quality.

Oh boy, onto input (that we said we are renaming to Controller)
11-1: Move Maximum Users to...somewhere. Wtf even is this menu? If this actually means users, move it to the
relevant online menu. If it means locally, rename this to "Maximum Controllers". 
11-2: If the later, Create one of those Advanced Options line breaks again at the bottom, and move this
down there, along with every other option in this menu untill we get to Menu Controls. 
11-3: MENU CONTROLLS? HELLO? Why does main menu get help on menu controlls, BUT WE HAVE A ACTUAL MENU CONTROLLS
MENU? HELLLOOOO? PUT RELeVANT MENUS IN RELEVANT PLACES THANK YOU.
11-4: Move the Automatic Mouse Grab option to the Video menu in Settings. This is something usually in that
menu on other programs, stop being unintuitive!!! How can you make so many mistakes!!!

Speaking of the Video menu, lets tackle that next.
12-1:in Fullscreen Mode, rename Windowed Fullscreen to "Borderless Fullscreen" or just "Borderless",
and change the description appropriately.
12-2: Rename Fullscreen Width & Height to "Custom Width" (& Height). It's already in the fullscreen sub-menu, 
you don't need to remind them what menu they are in, it's at the top of the screen!
12-3: Move CRTSwitchRes and Output below the Fullscreen and Windowed sub-menus. Order matters! Most important
things go on top!

I can keep going, but i'll stop here. This is a Serious Checklist of Readability improvements across the 
entire settings menu. However, if i reconsider, i may suggest adding Controller to the left bar as a major
menu instead, as it's reasonab;y so important, it should be a major menu, rather then some garbage like Music.

=====================Chater 2: A Smoothe Gameplay Experience? Or A Troubleshooting Nightmare?=====================

Before i get into further details on games, i strongly recommend a new setting somewhere, on by default, that
makes it so when you load a game, and pick a emulaitor (Remember, we are calling these Games and Emulaitors, NOT
Cores and Content) that it associates that game to that emulaitor by default. In the future, you should be
able to Load game -> Pick the game -> it just boots up without needing to pick a emulaitor. 

I...HOPE i don't have to explain how bad it is that steam retroarch is missing a download button. I will skip
over the easy wall of text on this and move forward.

1: For steam users, there should still be a download emulaitor button, but as a submenu. 
1-1: In here, There should be a link to your website with a list of emulaitors to download.
1-2: There should be a setting here, or in the Install Emulaitor menus to set the directory for cores.
This is because this options is only useful & relevant right at this moment, and never again, so it
does not need to be in the directroies menu elsewhere.

2: When in-game, move the Command/Menu button to the top of the list. 
I also feel a menu rename is in order, but can't think of one right now, and want to move on.
3-1: Add save state and load state to the Command menu. Yes i know they are in the F1 menu. Make them accessable.
3-2: In the F1 menu, move State slot below load state

And oh boy, lets get into the F1 menu. In no particular order...
4-0: Make it WAY more obvious to assign a button or combo to open this menu from controller.
probably include it in the quick menu directly at the bottom, even if the option exists somewhere else,
just duplicate it. 
4-00: Also, Escape should open the quick menu by default
4-1: Rename Information to Game Information
4-2: Move thr Controller menu to right below Close Content
4-3: Also rename that to Close Game
4-4: Adding something to favorites and you can't remove it? WHY? 
Make this menu change to Remove from Favorites if it's a favorite >_>
4-5: Remove the descriptions for Resume, Restart, and Close game. This screen has lots the player wants
to see and not enough screen space even when in fullscreen. 
4-6: Also remove descriptions on save state, load state, Take Screenshot, Cheats, Achievements, and Rewind.
4-7: Rename Rewind to "Rewind Settings"
4-8: Make it so if the player presses cancel in the F1 to go to Main Menu, Then cancel again, it resumes the game.
4-9: move Show Desktop Menu from Main Menu while ingame to somewhere else (Probably settings).

With that out of the way, once ingame, there is no menu option to go back!
Add a button in windowed mode to open back the retroarch menu. If you tell me it's a hotkey, i don't care.
thats not intuitive! Make a button to go back to the retroarch menu!!!

Finally, this SHOULD be obvious, but it's not, so i will say it here.
I assume this is a major feature, but really, let people access that emulaitors settings when using it.
if we can't do that, retroarch is just worse then every emulaitor, because they have settings you NEED to even
run some games. If this option DOES exist, it's EXTREMELY hidden!

Moving on, post gameplay, your recent games don't show up in load content / load game.
Why isn't there a recent games list? And why can't you set a content / game directory in directories? 
If you can, that option should 100% be in the load content / Load Game menu, as this is where
it's actually relevant!!!

=======================Ending==================

I'll stop here, it's been 3 hours of complaints, but retroarch is riddles with terrible quality.
Why would anyone want to use this? 
1: An unfun troubleshooting experience in exchange for playing games in the worst quality possible 
without access to emulaitors settings. 
2: Some games are literally unplayable in retroarch because you can't access emu settings
3: The menus are bloated, and lie / decieves / give half truths by hiding relevant other options in other menus
for no other reason then to troll you
4: it's a pain to setup even for simple emulaitors
5: you can't even understand what retroarch is or isn't from inconsistent and contradictory messages,
to near moon-rune levels of advertising.
6: unintuitive menus and lacking default settings mean you need to go over everything before even attempting
to test a single title.
7: Using it via steam is a whole extra nightmare that could be made easy if anyone actually fucking cared.

It's easy to see why people don't recommend recroarch. The real question is if anyone is going to actually
do anything about it, or delete this post / no reply / no one for me to directly work with in a timely fashon /
stick their head in the clouds and ignore why people don't enjoy their product. 

My discord is Dawnbomb#3408, and i'm open to any actual developer contacting me and working hand in hand for
some actual quality assurance before the steam deck launches, but considering how obvious, easy, and
near intensionally-troll the levels of design are here, i expect no contact and noone willing to work to make
retroarch not be complete fucking bullshit bloatware on a PC, and i only scratched the surface of this QA nightmare.

**Comment by MrHuu** [comment]
I think this rant belongs in the forums or any other social channel of libretro. Not on the github issue tracker.

If you're serious in your offer to help out with 'quality assurance', that would be great. But i think the best approach would be contacting the developers on the libretro forums or discord and discuss your suggestions.

Forum: https://forums.libretro.com/
Discord: https://discord.com/invite/C4amCeV

**Comment by sonninnos** [comment]
Repeated fowl language, capslock cruising, know-it-all attitude, and giving thumbs up to their own posts should be bannable offenses.

**Comment by m4xw** [comment]
I appreciate the time you took to write this up but we don't appreciate your wording.
However, I will let this slip because you called it, but please not again.

While I agree on _some_ parts, in the end its a matter of time and money.
Everyone here does this in their free time, so unless you can come up with 20k in funding at minimum to work on these, I dont see the codebase reaching proper production-grade quality anytime soon.
If i have the choice between a full stomach and catering to anonymous dickheads, well the choice is obvious.
You can reach out to us anytime if you want to get involved and donate your time working on QoL issues, but then use Discord so it can be coordinated.
I can tell you tho, these issues are like the last of our problems with the codebase.. Theres way more fundamental/bigger fishes to fry first.
I recommend you split up your post into several seperate issues, completely reword it and try talking like a normal person.

**Comment by m4xw** [comment]
Also: >near intensionally-troll the levels of design are here

What design _laughs_

**Comment by dawnbomb** [comment]
It doesn't take 20000$ funding to reword some menu options. you can do some of this in like 10 minutes if someone really cared. Stop hiding behind excuses to shut perfectly valid changes down. Another contributor could take up the mantle, all you did was make sure no one looking over open issues would be able to see this topic, and implement any of these meaningful changes.

**Comment by m4xw** [comment]
Like I said: I recommend you split up your post into several seperate issues, completely reword it and try talking like a normal person.
Your post is harder to navigate than retroarch xmb without assets, not to mention it makes my eyeballs itch.

You underestimate the cost it takes for doing everything over what we are already doing because it means time needs to be taken from office hours at our dayjobs, which are expensive. For 20k you get about a month worth of fulltime work for one person.
So why care about low priority issues when theres way bigger issues? Your reading comprehension is lacking.

In your words: Get your shit together

**Comment by eddlang** [comment]
10 Minutes? Alright then, you claim to be a dev. Stop moaning and start coding. Pull requests are a thing. See how easy it is.

**Comment by TeamSoldierNub2** [comment]
or yknow you could just use some pull requests, or better yet

fork retroarch and do your own thing with it instead of putting an essay on the issue tracker
