### ISSUE TITLE
RetroArch Online Updater doesn't work at all (clean install)

### ISSUE THREAD

**Issue by fabiorzfreitas** [libretro/RetroArch#12992]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Core updater doesn't even fetch the index, all other Update options under Online Updater display Task Failed. All this is happening on a nightly (and on a stable as well) downloaded today.

### Bisect Results

I already checked my firewall settings to allow `retroarch.exe`, ran it as administrator and confirmed I can reach `http://buildbot.libretro.com/nightly/windows/x86_64/latest` and `http://buildbot.libretro.com/assets` on my browser. I also ran `ipconfig /flushdns` just in case and rebooted my PC

### Version/Commit
You can find this information under Information/System Information

- RetroArch Build Date: 2021/09/14, Git version 868a4bf3

### Environment information

- OS: Windows 10 21H1, build 19043.1165

**Comment by hizzlekizzle** [comment]
Online updater is down for the day. It should be back tomorrow.

**Comment by fabiorzfreitas** [comment]
It's working again today, thanks
