### ISSUE TITLE
simultaneous button presses not working for Android

### ISSUE THREAD

**Issue by clondy999** [libretro/RetroArch#13011]
I had a weird problem using retroarch on Android TV
Pressing two keys at the same time did not produce the expected effect.
For example, iron fist 3, press two keys at the same time, and it is expected that the grasping action will occur, but it does not occur
I've tried to increase the polling delay, but it still doesn't work

**Comment by fr500** [comment]
settings / latency / input block timeout, increase it to 1 or so
The retroarch input driver on android is weird and has this behavior

**Comment by hizzlekizzle** [comment]
I think this issue can be closed, @LibretroAdmin . That input block timeout option is the solution.
