### ISSUE TITLE
[Android] Using touch overlay with analog controls heavily decreases performance when threaded video is enabled

### ISSUE THREAD

**Issue by micechal** [libretro/RetroArch#1301]
I noticed on my Android device,  that using any touch overlay featuring analog controls is a huge performance hit.
According to my own tests, the difference in speed can be as high as 7,25 times slower than when not displaying an analog stick control.
The issue only happens with threaded video enabled. I already tried reinstalling the latest Android nightly,  but the issue still happens even on default settings.
Log: http://hastebin.com/lokimisumi

**Comment by twinaphex** [comment]
Can't be helped with Android, especially big-little cores.

I'd happily be proven wrong though, hopefully in the form of a PR. Reportedly 32bit surfaces are now slower on Android 5.0 Lollipop than before, and of course the analog stick overlay is always going to be slower than a regular overlay.
