### ISSUE TITLE
Android app closes when running a game in sameboy

### ISSUE THREAD

**Issue by teddblue** [libretro/RetroArch#13015]
Retroarch and retroarch plus close when running a game on sameboy core

### Expected behavior

It used to just play the game

### Actual behavior

You press 'run' and after a second the app closes

### Steps to reproduce the bug

(this happened on android, don't know about other platforms)
1. Select a game and go into its menu
2. Click 'run '
3. Wait 1 seccond

### Bisect Results

Seemed to have started about a week ago

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Google play store app, latest update (plus and normal)

### Environment information

- OS: android, kindle fire
- Compiler: none

**Comment by hizzlekizzle** [comment]
Try the 1.9.10 stable release (should be hitting your device any minute if it hasn't already). That should contain a fix for this issue.

**Comment by teddblue** [comment]
sorry it took so long to respond! this did work, thanks
