### ISSUE TITLE
[Input] Do not react on gamepad input when minimized

### ISSUE THREAD

**Issue by reyaz006** [libretro/RetroArch#13025]
When minimized or unfocused it doesn't react on keyboard, so it shouldn't react on gamepad either.

**Comment by kimimaru4000** [comment]
I would prefer if this were an option. Having gamepad input in the background is very useful for co-op play with multiple instances.

**Comment by gouchi** [comment]
Duplicate of #5004

**Comment by reyaz006** [comment]
Closing since it's a duplicate.
