### ISSUE TITLE
[XMB] Another icon behind icons

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1302]
Load content (detect core), and come back to XMB twice, an icon will appear behind:

![screenshot - 28122014 - 18 48 55](https://cloud.githubusercontent.com/assets/5431285/5564957/1fa4d6f0-8ec3-11e4-8208-f3116e514890.png)

**Comment by twinaphex** [comment]
Yeah this is a known issue. I mentioned it to kivutar a couple of times.

**Comment by Kivutar** [comment]
This bug will disappear by itself when I will add a new feature to this driver soon. That's why I don't fix it.

**Comment by twinaphex** [comment]
I think this issue is solved by now. I think we can close it. Reopen it in case you come across it again. (not likely though).
