### ISSUE TITLE
Retroarch doesn't launch on steam

### ISSUE THREAD

**Issue by MB-Barros-dot** [libretro/RetroArch#13030]
Description

Retroarch doesn't launch on Steam

 Expected behavior

Retroarch should launch after clicking play on Steam

Actual behavior

Retroarch doesn't launch after clicking play on Steam

Steps to reproduce the bug

1. Launch steam
2. Launch Retroarch on steam

 Bisect Results

This started happening since i download Retroarch on steam and tried to launch, curiously if try multiples times appears a pop up of AppImage saying if i want to integrate the app or run once, when i run once Retroarch starts but without steam overlay. Also, if i manually start the AppImage of Retroarch in the app folder it works. I launched Steam on terminal and pasted the results here, https://pastebin.com/Af09fqHb

 Version/Commit

- RetroArch: 1.9.10

 Environment information

- OS: Manjaro Linux 21.1.3

**Comment by hizzlekizzle** [comment]
looks like a 32/64-bit issue:
```
ERROR: ld.so: object '/home/mateus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
ERROR: ld.so: object '/home/mateus/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/mateus/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
```
