### ISSUE TITLE
(Nintendo Switch) Minus (-) and Plus (+) buttons don't work on split joy-cons

### ISSUE THREAD

**Issue by DerinQyu** [libretro/RetroArch#13034]
Description

Hello. Commit 931eb3221bad772d1ffb9012fd90e28d1fab613f fixed button combos on split joy-cons, but now retroarch does not detect presses from the _minus_ and _plus_ buttons you can't even rebind them. Buttons are unusable

Steps to reproduce the bug

-Do fresh install of retroarch
-Deattach any of the Joycons
-Open a game like super mario bros
-Try to press start

Tested on OFW 12.0.1 / atmosphere 20.1

**Comment by m4xw** [comment]
woopsie

**Comment by m4xw** [comment]
Fixed (should be up within next 3h)
