### ISSUE TITLE
[Wayland] Certain cores ignore user input

### ISSUE THREAD

**Issue by kirbykevinson** [libretro/RetroArch#13036]
## Description

When RetroArch is ran on Wayland, certain cores ignore user input, rendering the emulated game unplayable.

### Expected behavior

All of the cores take input as intended.

### Actual behavior

The following cores were found to be working as intended:

* NES - Mesen
* SNES - bsnes

And the following cores were found to be broken:

* Game Boy - Gambatte
* Game Boy - Gearboy
* Game Boy - SameBoy
* Game Boy - TGB Dual
* NES - FCEUmm
* NES - Nestopia UE
* NES - QuickNES

I haven't checked all of the cores, so possibly more are broken.

### Steps to reproduce the bug

1. Make sure you're running a Wayland compositor
2. Make sure you're not running RetroArch under XWayland
3. Launch RetroArch and install one of the broken cores
4. Launch the game and try to do anything

### Bisect Results

The following Flatpak commit is the last version this bug is not present in:

```
    Commit: 4a1d4c79964ea64ac984f8cc0a68adff609ed38047e45808cb4e1836ca3308be
   Subject: v1.9.7 (8f2479e0)
      Date: 2021-08-02 06:10:01 +0000
```

And the following Flatpak commit is the first version this bug is present in:

```
    Commit: d3b0ab6eb81c8d5bfd2d62777ef04e5be5df730ef6088f316eb0d6aacaeaacc6
   Subject: v1.9.8 (77bcc6e8)
      Date: 2021-08-27 19:31:24 +0000
```

### Environment information

* OS: Fedora 34
* Display server: GNOME on Wayland, Sway
* Package manager: Flatpak

**Comment by kirbykevinson** [comment]
I just ran a `git bisect` and it seems like the first commit that has this bug is 109f4fafec7110db208b11dbfe23f68f05a04706.

@markwkidd, as the one who wrote the commit, perhaps you may know what causes the issue.

**Comment by grant2258** [comment]
Are you using a controller or a keyboard?

**Comment by kirbykevinson** [comment]
I'm using a keyboard.

**Comment by grant2258** [comment]
I thought thats was the case just making sure before we proceed the joypad is actually working fine. I can confirm the keyboard not functional in quicknes or FCEUmm. Ill wait for mark to chime in as I dont want to walk all over his work on this.

**Comment by grant2258** [comment]
The fix is sime either remove all this 

https://github.com/libretro/RetroArch/blob/714cfc581d64c34218a079232cc7f746e4f8d729/input/drivers/wayland_input.c#L172-L181

the return 0 should be commented out in fact its safe to remove it all looks like an oversight by ending the comment too soon thats easily done. Ive tested is working

**Comment by grant2258** [comment]
@markwkidd  is there any  put test cores to check things out on different drivers?

**Comment by markwkidd** [comment]
@grant2258 there is a test core which is very basic, and it's not on the buildbot so limited usefulness working with end users: https://github.com/libretro/libretro-samples/blob/master/tests/test/libretro-test.c

I am away from keyboard for a few more hours but I'll put together a PR to fix this. Thanks for all your help with it

**Comment by grant2258** [comment]
Thanks Mark appreciated I think I'll drum up a small core myself this helps a template cheers

**Comment by kirbykevinson** [comment]
I opened a pull request with a quick dirty fix. Feel free to ignore it if you find a more elegant solution.
