### ISSUE TITLE
Sound crackles when fast forwarding

### ISSUE THREAD

**Issue by bobbybudnick** [libretro/RetroArch#13040]
## Description
When doing PSX emulation at fast forward speed of only 2x I cannot stop the audio from crackling.  I have turned off all enhancements.  I have tried increasing sound latency to 512 and I have tried all of the audio drivers.

### Expected behavior

The sound plays at a sped up rate but does not crackle.

### Actual behavior

The sound plays at a sped up rate but emits crackling noises.

### Version/Commit

- ebe0d89

### Environment information

- OS: Windows 10

**Comment by briaguya-ai** [comment]
which PSX core are you using? Have you tried using a standalone emulator and seeing if the problem exists there too?

**Comment by LibretroAdmin** [comment]
Weird bug report.
