### ISSUE TITLE
[Linux] Symlinks are not followed

### ISSUE THREAD

**Issue by 3XC4L1B3R** [libretro/RetroArch#13042]
## Description

Symlinking to an existing emulator bios folder causes a `Could not find valid BIOS files!` error. Copying the relevant BIOS folder/files to be directly in the system folder does not cause this error.
Full log: 
[retrolog.txt](https://github.com/libretro/RetroArch/files/7256257/retrolog.txt)
The last few lines show the error.
The build-in file browser also seems unable to follow symlinks. Opening a symlink'd directory results in the UI showing a "Directory Not Found" entry.

### Expected behavior

I expected RetroArch to follow the symlink to my existing bios folder.

### Actual behavior

RetroArch throws an error saying that it can't find my BIOS files.

### Steps to reproduce the bug

1. Download a core
2. ~~Download~~ Responsibly obtain the matching BIOS and place it in its own folder
3. Create a symlink in the RetroArch system folder pointing to the bios folder (otherwise respecting expected folder structure)
e.g `$ mkdir ~/retroarch/system/pcsx2 && ln -s ~/pcsx2/bios ~/retroarch/system/pcsx2/bios`
4. Attempt to load content using that core

Or...

1. Within RetroArch, open the "Load Content" menu, or another menu that uses the built-in file browser
2. Navigate to a symlink which points to a directory
3. See the "Directory Not Found" entry

### Bisect Results

This has been happening since I first installed RetroArch two days ago.

### Version/Commit

- RetroArch: 1.9.10 (Git a64fa9c8d7)

### Environment information

- OS: Linux Pop!_OS 21.04
- Compiler: GCC (9.3.0) 64-bit (Installed with snap)

**Comment by grant2258** [comment]
The usual path for the retroarch dirs are ~/.config/retroarch/system/pcsx2/bios I see from your logs its set too.

[INFO] [Environ]: SYSTEM_DIRECTORY: "/home/username/snap/retroarch/831/.config/retroarch/system

Either change the directory in ra or fix the symlink

**Comment by gouchi** [comment]
You are using RetroArch snap package so please bear in mind it is [confined](https://snapcraft.io/docs/snap-confinement).

You should try to use  [$SNAP_USER_DATA](https://snapcraft.io/docs/environment-variables).

**Comment by gouchi** [comment]
Using self compiled RetroArch I can't reproduce your issue

```
ln -s ~/.config/retroarch/system ~/rasystem
grep system_directory ~/.config/retroarch/retroarch.cfg
system_directory = "~/rasystem"
```

So it must be because of the snap package confinement.

**Comment by 3XC4L1B3R** [comment]
Compiling from source and using the .config directory fixed this issue. Thanks for your help.
