### ISSUE TITLE
RPI/VIDEOCORE: Add hardware upscaling (improvement)

### ISSUE THREAD

**Issue by gizmo98** [libretro/RetroArch#1304]
Some cores slow down if higher display resolutions are used. Is it possible to use dispmanx for hardware upscaling? According to this thread (http://www.raspberrypi.org/forums/viewtopic.php?t=14770&p=287664) it should be possible to select an source and destination resolution. The GPU will scale the source image to the actual screen resolution. It is also possible to set different scaling kernels (https://github.com/raspberrypi/firmware/issues/104).

The current vc_egl_ctx.c resolution of dst_rect and src_rect is equal:  
https://github.com/libretro/RetroArch/blob/master/gfx/context/vc_egl_ctx.c#L212

Wouldn't it be nice to set the native system resolution as source and the display resolution as destination? Of course the resolution will be too low for shaders like HQ2X.

**Comment by gizmo98** [comment]
I just changed the resolution of src_rect:
src_rect.width = 640 << 16;
src_rect.height = 480 << 16;

Something is upscaled. Retroarch still renders in Full HD but only the lower left half of the image (640x480) is upscaled to the display resolution. How can modify the render resolution?

**Comment by gizmo98** [comment]
It is working! I just modified vc_egl_ctx.c a little bit. If g_settings.video.fullscreen_x and g_settings.video.fullscreen_y is 0 the fb resolution will be used. Otherwise the fullscreen settings of retroarch.cfg will be used.  https://github.com/gizmo98/RetroArch/commit/e699f7e46e770307f15fd5bc01e19f7bc0643b86

**Comment by Kivutar** [comment]
Did you notice any performance improvement?

**Comment by gizmo98** [comment]
Definitely. I tested two setups:
FB_RES 1080p + Pocketsnes-Libretro + Secret of Mana + HQ2X shader --> too slow!
FB_RES 1080p + retroarch.cfg (WVGA: video_fullscreen_x = 800
 video_fullscreen_y = 480) + Pocketsnes-Libretro + Secret of Mana + HQ2X shader --> playable!
