### ISSUE TITLE
[Wii] cannot load roms from 7z in 1.9.10

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#13050]
## Description

cannot load roms from 7z in 1.9.10

### Expected behavior

- should be able to choose a 7z and have the contained rom load

### Actual behavior

- crash
- black screen
- have to power cycle

### Steps to reproduce the bug

1. install 1.9.10
2. choose load content, I use a .md rom and PicoDrive core
3. choose a 7z
4. confirm
5. wait for game to not load (or not in this case)

### Bisect Results

- 1.9.9 works OK
- 1.9.10 crash

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- Wii
- stable versions from buildbot
- PicoDrive core

**Comment by twinaphex** [comment]
Can you check some of the nightlies before 1.9.10 released and pinpoint when it started happening?

**Comment by gingerbeardman** [comment]
Sure can

**Comment by gingerbeardman** [comment]
Unfortunately, I'm too late - the buildbot nightlies don't go back past the release date of 1.9.10

**Comment by gingerbeardman** [comment]
Also happens with the Gearsystem (SG-1000) core

**Comment by twinaphex** [comment]
I assume a bisect is not something you are capable of doing?

**Comment by gingerbeardman** [comment]
"Normally" I'd have a go, but we've just had a new baby so my time is limited.

If there's a guide let me know and I'll read about it when baby is napping 😅

**Comment by LibretroAdmin** [comment]
Version is too old at this point, we can only support the latest stable and nightlies.

**Comment by gingerbeardman** [comment]
I'll reopen it if there's an issue with the latest nightly.
