### ISSUE TITLE
Confusing code and more robust rewrite

### ISSUE THREAD

**Issue by nhasabni** [libretro/RetroArch#13056]
Hi,

We have developed a tool, named [ControlFlag](https://github.com/IntelLabs/control-flag), that assist software developers in detecting coding anomalies in their programs. We found an anomaly described below, which we think can be corrected with a better rewrite.

## Description

This is a not a bug, but a possible enhancement to code that can improve its robustness.

Expression `(init1 | init2 | init3)` used in line 137 of brcmjpeg.c ([here](https://github.com/libretro/RetroArch/blob/5a40d28f8f4b8ced08f1ba1bd5d4ebc837970ee4/gfx/include/userland/interface/mmal/client/brcmjpeg/brcmjpeg.c#L134-L141)) is confusing. It is not clear exactly what it is checking, but based on the code, it seems to check that all three variables, which represent status codes, are not success code. All three variables are `int` type in the code, but the functions `vcos_mutex_create` and `vcos_semaphore_create` return values of type `VCOS_STATUS_T` (declared [here](https://github.com/libretro/RetroArch/blob/0ddfbd976c478f154100fababa3aea76270d12be/gfx/include/userland/interface/vcos/generic/vcos_latch_from_sem.h#L48)), which is of type enum (defined [here](https://github.com/libretro/RetroArch/blob/0ddfbd976c478f154100fababa3aea76270d12be/gfx/include/userland/interface/vcos/vcos_types.h#L85)).

### Expected behavior

Clearer and more robust code is:
```
VCOS_STATUS_T init1, init2, init3;
if (init1 != VCOS_SUCCESS || init2 != VCOS_SUCCESS || init3 != VCOS_SUCCESS)
```

Also, since the code is checking for failure cases, better name for the variables would be `init1_failure`, etc.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.9.10/5a40d28f8f4b8ced08f1ba1bd5d4ebc837970ee4]

**Comment by twinaphex** [comment]
To clarify, this is a dependency from another project. It's not actual code from RetroArch itself. Thanks for your interest though. I agree the variable declaration naming leaves something to be desired but such is the case usually with dependencies that fall outside of the scope of our project...
