### ISSUE TITLE
Android Wear Core Manager crash

### ISSUE THREAD

**Issue by BlackLotus** [libretro/RetroArch#1306]
I know android wear won't really be a main concern but still.
If you have retroarch with cores baked into it ,,everything" works fine.If you try to use a nightly version and start the core manager retroarch crashes.
You can see
https://gist.github.com/BlackLotus/eaafaee8567e6433265a
for a logcat paste

**Comment by twinaphex** [comment]
This should no longer be an issue now that we no longer use the Java code.

**Comment by BlackLotus** [comment]
It isn't the only problem now is that android wear can't use the normal android functions to download things since every request gets tethered over the phone.
So the core/update manager doesn't work. But I think android wear isn't a priority right now (wouldn't even know how to correctly implement it).
