### ISSUE TITLE
Cannot set internal_resolution in video setting with Flycast core for Switch . With solution to solve this problems.

### ISSUE THREAD

**Issue by koy168hk** [libretro/RetroArch#13072]
All the below issues are with the Flycast core for Switch.

## Description:
Video setting cannot set the internal resolution.

[What you expected to happen]:
User should able to change the internal_resolution ourself in video setting. Suggest team should add the internal_resolution setting for user with Flycast core.

### Version:
- RetroArch: [1.9.10- Flycast (0.1 4a913e0)]

Solution:

There are no setting we can find in the retroarch emulator setting menu even video setting. ( i cannot find it), we can only change the scale, but even you change the scale, the internal resolution still not change.

We need to open the file system via computer. the location path is retroarch/config/Flycast/Flycast.opt. use the notepad to open this file Flycast.opt and find the internal_resolution inside. The default is **reicast_internal_resolution = "640x480"**. we need to change it to **reicast_internal_resolution = "1920x1440"**. After that restart a game, you will find a very nice game display!!!!

I suggest to set 1920x1440, i tested. game play still very smooth. If upscale to higher resolution, you may got lag in game play. ( but you can try it and let us know your best setting).

**Comment by bslenul** [comment]
"Internal Resolution" option should be available while you have a game running with the core, in `Quick Menu > Options`.

**Comment by koy168hk** [comment]
> "Internal Resolution" option should be available while you have a game running with the core, in `Quick Menu > Options`.

Oh yes.  I found it.  Thank you!!!
