### ISSUE TITLE
[Suggestion] Get rid of `Settings > Input > Port N Controls > Device Type`

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#13083]
Hey!

So recently on Discord and Reddit there are a lot of people having issues with controller not working in-game because they have "Device Type" set to "RetroPad with Analog" globally, and that device type isn't supported by many cores.

For example, having "RetroPad with Analog" globally (`input_libretro_device_pN = "5"`) and starting a game with Beetle PSX, you won't get any inputs, because it is not a valid device type (DualShock being `input_libretro_device_pN = "517"`, not "5").

IMO the best solution would be to remove `Settings > Input > Port N Controls > Device Type` entirely (keep it in `Quick Menu > Controls > Port N Controls` only) and to force "RetroPad" (`input_libretro_device_pN = "1"`) when no core is loaded so the cores never start with an incompatible device type.

When no core is loaded "RetroPad with Analog" makes no sense and it only adds confusion for the users since they imagine it will allow them to use the analogs in-game while in reality it may prevent them from getting any inputs at all.

**Comment by jdgleaver** [comment]
@bslenul It's a few months late, but this should fix the issue: https://github.com/libretro/RetroArch/pull/13749

(Looking into this also made me realise that the existing remap save/load menu stuff is pretty wonky - since this is somewhat more important now that device type can only be recorded via remaps, I'll clean that up next...)

**Comment by bslenul** [comment]
Oh that's awesome, that will avoid a ton of confusion! Thank you so much as usual ❤️
