### ISSUE TITLE
[Linux] Titlebar missing in Ubuntu 21.04

### ISSUE THREAD

**Issue by matteodev8** [libretro/RetroArch#13094]
## Description

I installed RetroArch via Snap and then it didn't have a title bar and I couldn't move the window. Then I tried compiling it, it didn't work either

### Expected behavior

Titlebar should show noirmally.

### Actual behavior 

Titlebar doesn't show

### Steps to reproduce the bug

1. Install/Compile RetroArch on Ubuntu
2. Start
3. See Error

### Bisect Results

Tried different menu drivers, Reboots, etc... didn't wprk

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.11

### Environment information

- OS: Ubuntu 21.04
- Compiler: make

**Comment by matteodev8** [comment]
Okay thanks, I could try using X since I don't really care about the Graphics Server

**Comment by Ashvith10** [comment]
Can this issue be re-opened and the issue title be edited? This has still not been resolved. Titlebar still does not exist on Wayland. I'm on NixOS 23.11-beta, using RetroArch 1.16.0.

**Comment by amethystgosling163** [comment]
I can reproduce on Fedora 42 Workstation - Wayland.
