### ISSUE TITLE
input_enable_hotkey per input device

### ISSUE THREAD

**Issue by gizmo98** [libretro/RetroArch#1310]
Retroarch does only respect input_enable_hotkey_btn if there is a input_enable_hotkey. Is it possible to separate hotkey_enable_settings for keyboards and gamepads?

There seems to be another problem. If input device zero (keyboard?) has no RARCH_ENABLE_HOTKEY, use_hotkey_enable is always false:

   static const struct retro_keybind *bind = 
      &g_settings.input.binds[0][RARCH_ENABLE_HOTKEY];

   // If we haven't bound anything to this, always allow hotkeys.
   use_hotkey_enable = bind->key != RETROK_UNKNOWN ||
      bind->joykey != NO_BTN ||
      bind->joyaxis != AXIS_NONE;

https://github.com/libretro/RetroArch/blob/1ec8099789fe16b99437d7244e7d1672be603b19/runloop.c#L545

**Comment by gizmo98** [comment]
I added a check for the first autoconf_bind. It's working fine now. Is it possible to add this change? 

static void check_block_hotkey(bool enable_hotkey)
{
   bool use_hotkey_enable;
   static const struct retro_keybind *bind = 
      &g_settings.input.binds[0][RARCH_ENABLE_HOTKEY];
   static const struct retro_keybind *autoconf_bind = 
      &g_settings.input.autoconf_binds[0][RARCH_ENABLE_HOTKEY];

   /* Don't block the check to RARCH_ENABLE_HOTKEY
    * unless we're really supposed to. */
   driver.block_hotkey = driver.block_input;

   // If we haven't bound anything to this, always allow hotkeys.
   use_hotkey_enable = bind->key != RETROK_UNKNOWN ||
      bind->joykey != NO_BTN ||
      bind->joyaxis != AXIS_NONE ||
      autoconf_bind->key != RETROK_UNKNOWN ||
      autoconf_bind->joykey != NO_BTN ||
      autoconf_bind->joyaxis != AXIS_NONE;;

   driver.block_hotkey = driver.block_input ||
      (use_hotkey_enable && !enable_hotkey);

   /* If we hold ENABLE_HOTKEY button, block all libretro input to allow 
    * hotkeys to be bound to same keys as RetroPad. */
   driver.block_libretro_input = use_hotkey_enable && enable_hotkey;
}

**Comment by fr500** [comment]
Why not offer a pull request instead of this? then it can be reviewed
properly
