### ISSUE TITLE
RetroArch 1.9.11 build fails with --enable-sdl

### ISSUE THREAD

**Issue by jason-oliveira** [libretro/RetroArch#13115]
## Description

RetroArch 1.9.11 build fails with --enable-sdl

### Expected behavior

RetroArch builds and does not have an error in libretro-common/vulkan/vulkan_symbol_wrapper.c that makes gfx/drivers_context/sdl_gl_ctx.c:58:13 scream that sdl_api has an initializer but an incomplete type.

### Actual behavior

[RetroArchNowHatesSDL.txt](https://github.com/libretro/RetroArch/files/7341796/RetroArchNowHatesSDL.txt)

### Steps to reproduce the bug

1. Install Gentoo. (I've always wanted to say that)
2. Add [my repo](https://gitlab.com/jason.oliveira/retroarch) to portage and emerge --sync retroarch
3. `sudo env USE="-sdl2 sdl" emerge retroarch`

or
1. Install Gentoo.
2. Download RA 1.9.11 from source
3. `./configure --enable-sdl --disable-sdl2 && make`

### Bisect Results

Was informed of the bug by a repo user, and had the same break when use flags were set the same. 

### Version/Commit
- RetroArch: 1.9.11

### Environment information

- OS: (Gentoo) Linux (v5.14)
- Compiler: GCC (10.3.0) 64-bit

**Comment by jason-oliveira** [comment]
Build still fails, but failure is at least new:
[build.log](https://github.com/libretro/RetroArch/files/7383576/build.log)

**Comment by gouchi** [comment]
Using latest commit, I still reproduce the issue if I compiled with 
`./configure --enable-sdl `

But if you have also sdl2 installed, strangely enough ? it is compiling with
`./configure --enable-sdl `

**Comment by LibretroAdmin** [comment]
Built it on Ubuntu with `./configure --enable-sdl --disable-sdl2`, no issues. Going to consider the situation resolved until further notice.
