### ISSUE TITLE
retroarch crash right after starting a normal sega cd or sega cd 32x game with picodrive. normal 32x games are working without problem. 

### ISSUE THREAD

**Issue by gabberhead** [libretro/RetroArch#13129]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

retroarch crash right after starting a normal sega cd or sega cd 32x game. normal 32x games are working without problem. and the normal segacd games are working with genesis plus gx also without problems. i have 2 us bioses with 2 different md5 hashes. both hases are identical to the ones which are listet on the libretro site. jp and eu have the same md5 hashes for genesis plus gx and picodrive. only the us bioses are different for picodrive and genesis gx plus. but with both its not working.

### Expected behavior

normal behavior would be the game starts ^^

### Actual behavior

retroarch crash after 1 or 2 seonds

### Steps to reproduce the bug

1. choose a segacd or segacd 32x game
2. start the game with picodrive core
3. retroarch crash

### Bisect Results

i dont know when it happend. 2 years ago i get the same images working with retropie on pi 3b+. now i try to get the same image working on my laptopt via retroarch.

### Version/Commit

1.9.11 stable (retroarch)
1.98 (picodrive) newest. updated 1 hour ago.

### Environment information

- Windows 11

i made a debug log of a game start:

[INFO] RetroArch 1.9.11 (Git a9125ff)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
[INFO] Fähigkeiten:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Oct  9 2021
[INFO] Version: 1.9.11
[INFO] Git: a9125ff
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version der libretro-API: 1
[INFO] Kompiliert gegen API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [WGL] extensions: WGL_EXT_depth_float WGL_ARB_buffer_region WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_pixel_format WGL_ARB_pbuffer WGL_EXT_extensions_string WGL_EXT_swap_control WGL_ARB_multisample WGL_ARB_pixel_format_float WGL_ARB_fram[INFO] [GL]: Vendor: Intel, Renderer: Intel(R) UHD Graphics.
[INFO] [GL]: Version: 4.6.0 - Build 27.20.100.9565.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [SRAM]: SRAM wird nicht gespeichert.
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_history.lpl].
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_music_history.lpl].
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_video_history.lpl].
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_image_history.lpl].
[INFO] [Playlist]: Favoritendatei wird geladen: [C:\Program Files\RetroArch\content_favorites.lpl].
[INFO] [CONTENT LOAD]: Updating firmware status for: C:\Program Files\RetroArch\cores\picodrive_libretro.dll on C:\Program Files\RetroArch\system
[INFO] [CORE]: Using content: F:\--=[Spiele]=--\Night Trap (32X) (US - Disc 1).cue.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.9.11 (Git a9125ff)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
[INFO] Fähigkeiten:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Oct  9 2021
[INFO] Version: 1.9.11
[INFO] Git: a9125ff
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "C:\Program Files\RetroArch\cores\picodrive_libretro.dll"
[INFO] [Overrides]: No core-specific overrides found at "C:\Program Files\RetroArch\config\PicoDrive\PicoDrive.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "C:\Program Files\RetroArch\config\PicoDrive\--=[Spiele]=--.cfg".
[INFO] [Overrides]: No game-specific overrides found at "C:\Program Files\RetroArch\config\PicoDrive\Night Trap (32X) (US - Disc 1).cfg".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "4".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE.
[INFO] [CONTENT OVERRIDE]: File Extension: 'gen' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [CONTENT OVERRIDE]: File Extension: 'smd' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [CONTENT OVERRIDE]: File Extension: 'md' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [CONTENT OVERRIDE]: File Extension: '32x' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [CONTENT OVERRIDE]: File Extension: 'sms' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [CONTENT OVERRIDE]: File Extension: '68k' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [CONTENT OVERRIDE]: File Extension: 'sgd' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [Remaps]: Remap directory: "C:\Program Files\RetroArch\config\remaps".
[INFO] [Overrides]: Speicherdaten umleiten in "D:\--=[Spiele]=--\RetroArch\--=[Saves]=--\Night Trap (32X) (US - Disc 1).srm".
[INFO] [Overrides]: Spielstand umleiten in "C:\Program Files\RetroArch\states\Night Trap (32X) (US - Disc 1).state".
[INFO] [Environ]: PERFORMANCE_LEVEL: 0.
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_DISK_CONTROL_INTERFACE.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_VARIABLE picodrive_sound_rate:
	44100
[INFO] [Environ]: GET_VARIABLE picodrive_input1:
	3 button pad
[INFO] [Environ]: GET_VARIABLE picodrive_input2:
	3 button pad
[INFO] [Environ]: GET_VARIABLE picodrive_sprlim:
	disabled
[INFO] [Environ]: GET_VARIABLE picodrive_ramcart:
	disabled
[INFO] [Environ]: GET_VARIABLE picodrive_region:
	Auto
[INFO] [Environ]: GET_VARIABLE picodrive_aspect:
	PAR
[INFO] [Environ]: GET_VARIABLE picodrive_overscan:
	disabled
[INFO] [Environ]: GET_VARIABLE picodrive_overclk68k:
	disabled
[INFO] [Environ]: GET_VARIABLE picodrive_drc:
	enabled
[INFO] [Environ]: GET_VARIABLE picodrive_audio_filter:
	disabled
[INFO] [Environ]: GET_VARIABLE picodrive_lowpass_range:
	60
[INFO] [Environ]: GET_VARIABLE picodrive_frameskip:
	disabled
[INFO] [Environ]: GET_VARIABLE picodrive_frameskip_threshold:
	33
[INFO] [Environ]: GET_VARIABLE picodrive_renderer:
	accurate
[INFO] [Environ]: GET_VARIABLE picodrive_sound_rate:
	44100
[INFO] [CONTENT LOAD]: Laden des Inhalts übersprungen. Die Implementierung wird ihn selbst laden.
[INFO] [Environ]: RETRO_ENVIRONMENT_GET_GAME_INFO_EXT.
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[libretro INFO] detected BIN Sega/Mega CD image with USA region
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\Program Files\RetroArch\system".
[libretro INFO] using bios: C:\Program Files\RetroArch\system\bios_CD_U.bin
[libretro WARN] warning: wanted to map @02000000, got 0000000007400000
[libretro INFO] 00000:000: Track  1: 00:02:00    263441 DATA  F:\--=[Spiele]=--\Night Trap (32X) (US - Disc 1).bin
[libretro INFO] 00000:000: Track  2: 58:22:05       936 AUDIO 
[libretro INFO] 00000:000: End CD -  58:34:41

[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "B"
[INFO] 	RetroPad, Port 1, Button "Y (left)" => "A"
[INFO] 	RetroPad, Port 1, Button "Select" => "Mode"
[INFO] 	RetroPad, Port 1, Button "Start" => "Start"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "C"
[INFO] 	RetroPad, Port 1, Button "X (up)" => "Y"
[INFO] 	RetroPad, Port 1, Button "L" => "X"
[INFO] 	RetroPad, Port 1, Button "R" => "Z"
[INFO] 	RetroPad, Port 2, Button "B (bottom)" => "B"
[INFO] 	RetroPad, Port 2, Button "Y (left)" => "A"
[INFO] 	RetroPad, Port 2, Button "Select" => "Mode"
[INFO] 	RetroPad, Port 2, Button "Start" => "Start"
[INFO] 	RetroPad, Port 2, Button "D-Pad Up" => "D-Pad Up"
[INFO] 	RetroPad, Port 2, Button "D-Pad Down" => "D-Pad Down"
[INFO] 	RetroPad, Port 2, Button "D-Pad Left" => "D-Pad Left"
[INFO] 	RetroPad, Port 2, Button "D-Pad Right" => "D-Pad Right"
[INFO] 	RetroPad, Port 2, Button "A (right)" => "C"
[INFO] 	RetroPad, Port 2, Button "X (up)" => "Y"
[INFO] 	RetroPad, Port 2, Button "L" => "X"
[INFO] 	RetroPad, Port 2, Button "R" => "Z"
[INFO] [Environ]: SET_MEMORY_MAPS.
[INFO]    ndx flags  ptr              offset   start    select   disconn  len      addrspace
[INFO]    001 M1A1bc 00007ff9ea679800 00000000 00FF0000 FFFF0000 00000000 00010000 68KRAM
[INFO]    002 M1A1bc 0000000007420000 00000000 80020000 FFF80000 00000000 00080000 PRGRAM
[INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
[INFO] [SRAM]: Überspringe Laden des SRAM..
[INFO] Version der libretro-API: 1
[INFO] Kompiliert gegen API: 1
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [RCHEEVOS]: no hook registered for cdreader_absolute_sector_to_track_sector
[INFO] [RCHEEVOS]: no hook registered for cdreader_absolute_sector_to_track_sector
[INFO] [RCHEEVOS]: Could not locate primary executable
[INFO] [RCHEEVOS]: no hook registered for cdreader_absolute_sector_to_track_sector
[INFO] [RCHEEVOS]: Could not locate primary executable
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [RCHEEVOS]: no hook registered for cdreader_absolute_sector_to_track_sector
[INFO] [RCHEEVOS]: Not a PC Engine CD
[INFO] [RCHEEVOS]: Not a 3DO CD
[INFO] [RCHEEVOS]: Largest track only supported for CHD, using first data track
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: checking 383c946949c880740dceb4f967a8f756
[INFO] [WGL] extensions: WGL_EXT_depth_float WGL_ARB_buffer_region WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_pixel_format WGL_ARB_pbuffer WGL_EXT_extensions_string WGL_EXT_swap_control WGL_ARB_multisample WGL_ARB_pixel_format_float WGL_ARB_fram[INFO] [GL]: Vendor: Intel, Renderer: Intel(R) UHD Graphics.
[INFO] [GL]: Version: 4.6.0 - Build 27.20.100.9565.
[INFO] [GL]: Using resolution 1920x1080
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: WARNING: 1:2: '' :  #version directive missing

[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] [RCHEEVOS]: got game id 0
[INFO] [RCHEEVOS]: this game doesn't feature achievements
[INFO] [RCHEEVOS]: Load task finished
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_history.lpl].
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_music_history.lpl].
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_video_history.lpl].
[INFO] [Playlist]: Lade Verlaufs-Datei: [C:\Program Files\RetroArch\content_image_history.lpl].
[INFO] [Playlist]: Favoritendatei wird geladen: [C:\Program Files\RetroArch\content_favorites.lpl].
[INFO] [Input]: Game Focus => ON
[ERROR] Failed to write to playlist file: C:\Program Files\RetroArch\content_history.lpl
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.
[INFO] [Environ]: SET_GEOMETRY: 320x224, aspect: 1.429.

**Comment by irixxxx** [comment]
@twinaphex  Please close this, it's not related to retroarch.

**Comment by sonninnos** [comment]
This seems to be sorted already.
