### ISSUE TITLE
No Imports of 7z on linux

### ISSUE THREAD

**Issue by 91rl** [libretro/RetroArch#13127]
## Description

Retroarch does not successfully detect and import games stored in .7z archives using file or directory import options.

### Expected behavior

Importing of games in .7z archives.

### Actual behavior

Import process completes without any .7z archived games being imported.

### Steps to reproduce the bug

1. Select Import
2. Select Import file or directory
3. Choose .7z file or directory that contains .7z games.

### Bisect Results

Immediately after first install on a fresh OS install.

### Version/Commit

Build: Oct 13 2021
Git Version: c19b04e

### Environment information

Files are stored on NTFS drive in case filesystem has any significance...
Using nvidia proprietary 460 but doubt that matters

Operating System: Debian GNU/Linux 11
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.0-9-amd64
OS Type: 64-bit
Processors: 16 × Intel® Core™ i7-10700 CPU @ 2.90GHz
Memory: 15.4 GiB of RAM
Graphics Processor: GeForce RTX 2070 Super/PCIe/SSE2
 
### Misc

Fanks in advance to everyone contributing to this awesome project <3

**Comment by LibretroAdmin** [comment]
Is this still an ongoing issue or has it been resolved by now?

**Comment by 91rl** [comment]
> Is this still an ongoing issue or has it been resolved by now?

Hey there, I haven't tried to use the feature for a while, I'll test it and get back to you with an update soon.

**Comment by 91rl** [comment]
> Is this still an ongoing issue or has it been resolved by now?

Just tested it and it seems to be working fine now :)
