### ISSUE TITLE
Multiple issues when using Wayland on Linux

### ISSUE THREAD

**Issue by Ahmed-E-86** [libretro/RetroArch#13132]
## Description
1- The Memory usage increases 100mb every few seconds after I open RetroArch under Wayland.
2- The default UI flickers every few seconds.
3- I can not scroll down using my mouse wheel.

All of these issues do not happen when I use Xorg instead of Wayland on KDE Plasma 5.22.5.

### Version/Commit
- RetroArch: 1.9.11

### Environment information
- OS: Kubuntu 21.04
- Desktop Environment: KDE Plasma 5.22.5
- Linux kernel: 5.11.0-37
- CPU: Intel Core I5 4200M
- GPU: AMD Radeon HD 8750M
- GPU driver: 21.2.4

**Comment by i30817** [comment]
Sometimes, when people think they're using 'wayland' support in retroarch they're actually using xwayland.

The only way to be sure, is sadly, to build without x11 and with wayland support. Once i did that, a bunch of problems disappeared (back when ubuntu was briefly on wayland by default).

**Comment by nfp0** [comment]
> The only way to be sure, is sadly, to build without x11

@i30817 You can check the `Information->System Information->Video Context Driver` menu to see if you're using a Wayland or X driver. For example in my case it shows: `vk_wayland`

**Comment by i30817** [comment]
Well, i didn't mean 'make sure you're using' but 'make sure you're building'.

Because sometimes projects manage to have runtime detection for features like these, although i've never seen it for wayland, probably because of the encouragement of 'xwayland exists, so we don't have to care'.

**Comment by nfp0** [comment]
Yeah, fortunately RetroArch detects Wayland at runtime too.

**Comment by i30817** [comment]
Last time i checked (back on ubuntu 18) it didn't detect at runtime (eg: run without xwayland in wayland if built with both x11 and wayland support). Maybe that changed meanwhile.

**Comment by nfp0** [comment]
I have an AMD Radeon and from what I see in the console output, RetroArch first tries to see if it's in a Wayland environment, and if it fails, it falls back to X.

When I open RetroArch normally, it opens in Wayland mode, but when I run it with `WAYLAND_DISPLAY="" retroarch`, to hide Wayland from it, I get this message on the console:
`[ERROR] [Wayland]: Failed to connect to Wayland server.` and then it proceeds to open in Xwayland.

**Comment by zoltanvb** [comment]
This should be resolved nowadays. Wayland support is in general working OK, including scroll wheel support.

**Comment by nfp0** [comment]
Yes, none of these issues happen to me on Wayland right now.
I'm on KDE Plasma 5.27.9
