### ISSUE TITLE
Compilation failed on RPI 3B+

### ISSUE THREAD

**Issue by PCX-LK** [libretro/RetroArch#13147]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When I compile RetroArch in raspberry pi 3b+ according to the normal linux compilation process, an error occurs

### Expected behavior

Compile RetroArch normally

### Actual behavior

The terminal throws the following

usr/bin/ld: //lib/arm-linux-gnueabihf/libGLESv2.so.2: error adding symbols: DSO missing from command line

### Steps to reproduce the bug

1. Execute “NOCLEAN=1 ./retroarch-build.sh”
1. Wait for compilation to complete
2. see the error

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.12

### Environment information

- OS: Raspberry pi OS （armhf）
- Compiler: gcc (Raspbian 8.3.0-6+rpi1) 8.3.0

**Comment by genpfault** [comment]
Happens back on the `v1.9.9` tag too.

**Comment by genpfault** [comment]
Hmm, some set of these `configure` options fixed it on my end:

```
./configure --enable-floathard --enable-kms --enable-egl --enable-opengles --disable-opengl
```

It was throwing the missing DSO when built from a plain, zero-argument `./configure`.
