### ISSUE TITLE
Feature request : udev autoconfig relying only on exact names and not on id_vendor/id_product

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#1314]
I see several issues with that : 

- The first issue (and i think the tinyest) is with PS3 BT controller, i have to add a new file for every new controller i want to use, because PS3 BT controllers have their HMAC address in their names (ex. PLAYSTATION(R)3 Controller (00:06:F5:B5:E8:86) , PLAYSTATION(R)3 Controller (00:07:04:1A:6B:23), ...), perhaps you could implement the use of regular expression.

- The second issue is with "HuiJia  USB GamePad", there are tons of controllers/adapters using this name, all with different id_vendor/id_product/mapping, and retroarch autoconfig can't tell them apart even with input_vendor_id and input_product_id filled in config files.

I know there are ways to partially fix this with udev rules, for example i have a rule that write a new autoconfig file for every new PS3 controller i connect with bluetooth, and another that overwrite my huijia autoconfig file depending on id_vendor/id_product of the adapter i plug, but this is limited. I can't use, let's say, 2 dual saturn adapter, 1 dual PS adapter and 2 dual GC adapter to play 10 players bomberman saturn that way, that's a big issue for me.

**Comment by Kivutar** [comment]
So you're saying that vendor_id/product_id matching is failing? It should not. If so, the bug is there.

Also for your PS3 BT controller, what's the problem if the name contains the mac address, since the matching is supposed to be done on vendor_ir/product_id instead?

**Comment by barbudreadmon** [comment]
Yes it fails, i rebuilt retroarch from git yesterday to make sure. It seems autoconfig load the first file matching input_device without a care about id_vendor/id_product. About PS3 bluetooth controller, i think they don't have id_vendor/id_product when they are in bluetooth mode.

**Comment by barbudreadmon** [comment]
Seems like i just had to remove the line 'input_device = "HuiJia  USB GamePad"' from all my config files to get product_id/vendor_id matching to work.
Thanks for the help !

**Comment by Kivutar** [comment]
That's not good, vendor_id/product_id should take precedence over input_device

**Comment by gizmo98** [comment]
@Kivutar Is this line working for bluetooth joypads like PS3 controllers as well? https://github.com/libretro/RetroArch/blob/master/input/drivers_joypad/udev_joypad.c#L361

Shouldn't there be a extra line for bluetooth devices or a test for the used subsystem?

**Comment by fr500** [comment]
Should be fixed by now with the config scoring implemented a whie ago
