### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by inukaze** [libretro/RetroArch#13145]
Hi there, i just want make a Feature Request for Netplay

1 - Does not requiere the same rom for example with « Pokemon » Games, like :
Yellow, Blue, Red, Green, Gold, Silver, Crystal, Ruby, etc . . .

Because if i want trade or fight with another person via Intranet or Internet, is high probably the another person play another pokemon game version, from the same generation, and for example Pokemon Games in Second Generation, had a « Time Travel » this allow the second generation change pokemons or fight with player using the first generation of games.

2 - Address Book, for add IP Address and alias for not ever need to write down the IP, and allow the fast change of IP Server.

3 - Someone can verify why i try to play in Netplay (Intranet), using ParalleiN64 games like SuperSmash Brothers, none controller respond ? i can't use Mupen64Plus Core for that because ever gave a Segmentation Fault closing RetroArch from version 1.7.7 until 1.9.11 the same error persist with Mupen64Plus core.

And well under Microsoft WIndows 7 i don't know which tool are requiere for debug, for generate files and share here on issues for the devs fix it. thanks for readme

**Comment by Cthulhu-throwaway** [comment]
@LibretroAdmin non-supported cores.

Can be closed.
