### ISSUE TITLE
[WIIU] Regression: Updating assets.zip fails 10% into extraction.

### ISSUE THREAD

**Issue by vaguerant** [libretro/RetroArch#13152]
## Description

When selecting Update Assets from the Online Updater on Wii U, things start out normally with the download progressing as normal, but then extraction fails at 10%.

### Expected behavior

`assets.zip` should be extracted successfully.

### Actual behavior

Shortly after reaching 10%, the extraction notification is replaced by a new notification, `Extracting assets.zip: Task failed.` This notification comes with a check or tick mark (☑️), which seems like it might also be an issue, as that's a very misleading symbol to associate with something that has failed.

The log contains only one message relevant here:
`[ERROR] Failed to deflate sd:/retroarch/assets/ozone/png/solarized_dark/.` 

### Steps to reproduce the bug

1. Select Online Updater from the Main Menu
2. Select Update Assets

### Bisect Results

I've been unsuccessful in finding when this worked, as I updated and no longer have any old compatible builds around. @QuarkTheAwesome has confirmed that this was something they had working back in August.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.12 6b7f287

### Environment information

- OS: Wii U System Menu 5.5.5 (PAL)

**Comment by LibretroAdmin** [comment]
@vaguerant Has this been fixed by now with latest nightlies or is this still an ongoing issue?

**Comment by gblues** [comment]
I don't recall this ever working on wiiu... but I think we found the culprit.

I used a test build from working on #14490 and found that the zip successfully downloaded and extracted.

Keep in mind, the extract is slow (because SD card) and the UI is not great at conveying progress.

My PR was merged a couple hours ago, so it should be fixed in the next batch of nightlies or so.

**Comment by Ploggy** [comment]
I've tested out downloading assets with this fix, it now downloads and says extracting assets.zip (no % tho so can tell if it gets past 10%) it stays like that for a few minutes then says task failed.

**Comment by Ploggy** [comment]
This issue is now fixed, thanks @gblues :)

It takes about 10 mins due to WiiU slow io and there still isnt a % but it does work just fine :)
By chance I had FPS notifications on while it was extracting. the FPS dropped as low as 1 FPS :P 
but again, it does work so this can be closed.
