### ISSUE TITLE
[GNU/Linux/Debian11] Build fails when using the system slang compiler headers

### ISSUE THREAD

**Issue by vanfanel** [libretro/RetroArch#13163]
## Description

Linking fails on Debian 11 when the `--disable-builtinglslang` option is passed to the configure script.
This is caused by undefined symbols, these are a couple of them:

```
/usr/bin/ld: (.text+0xf74c): undefined reference to `glslang::TIntermediate::getMemberAlignment(glslang::TType const&, int&, int&, glslang::TLayoutPacking, bool)'
/usr/bin/ld: (.text+0xfe14): undefined reference to `glslang::TIntermediate::getMemberAlignment(glslang::TType const&, int&, int&, glslang::TLayoutPacking, bool)'
/usr/bin/ld: (.text+0xfe5c): undefined reference to `glslang::TIntermediate::improperStraddle(glslang::TType const&, int, int)'

```

### Expected behavior

Retroach builds and links.

### Actual behavior

Undefined references on the final linking phase:

```
/usr/bin/ld: (.text+0xf74c): undefined reference to `glslang::TIntermediate::getMemberAlignment(glslang::TType const&, int&, int&, glslang::TLayoutPacking, bool)'
/usr/bin/ld: (.text+0xfe14): undefined reference to `glslang::TIntermediate::getMemberAlignment(glslang::TType const&, int&, int&, glslang::TLayoutPacking, bool)'
/usr/bin/ld: (.text+0xfe5c): undefined reference to `glslang::TIntermediate::improperStraddle(glslang::TType const&, int, int)'

```

### Steps to reproduce the bug

1. Configure the sources with  `--disable-builtinglslang` 
2. make
3. Wait for the final linking phase

### Bisect Results

It started happening when updating from Debian 10 to Debian 11 (which is the actual STABLE Debian version).]

### Version/Commit

- RetroArch: Latest stable (1.9.12) and latest GIT version.

### Environment information

- OS: Debian 11
- Compiler: gcc version 10.2.1

**Comment by LibretroAdmin** [comment]
I can reproduce on Ubuntu 5.15.0 (GCC 11.2.0),.

**Comment by LibretroAdmin** [comment]
This fixed it for me -

https://github.com/libretro/RetroArch/commit/5d36d803183f887016f7fd8380bb150c3c30d0b9

Please confirm.

**Comment by vanfanel** [comment]
@LibretroAdmin Fix confirmed! Now builds and links with no errors at all :)
