### ISSUE TITLE
Crt-royale shader requires vsync to be off to render correctly (at least for SNES cores).

### ISSUE THREAD

**Issue by JordanAnthonyKing** [libretro/RetroArch#13164]
## Description
Sorry if this belongs in the shader repo, it's hard to place as it requires input from both shader settings and retroarch video settings.

Using the crt-royale shader, by default the screen flickers up and down a pixel. Many guides tell you to disable interlacing to correct this. Doing so has two issues, firstly, this setting is apparently not actually a disable for interlacing, only a disable for interlacing detection (see: https://www.reddit.com/r/RetroArch/comments/ehw7te/stop_suffering_with_the_crtroyale_shader/fco9mh5/), second, it breaks rendering of the image, see the attached zoomed in screenshot, and note that there are two scanlines per pixel:

![image](https://user-images.githubusercontent.com/58787893/139312847-777c86e5-0e9f-42b2-a473-e176a955fdb4.png)

If we now set the shader setting `Interlacing - Toggle` to true, the image renders properly but flickers, then disabling vsync we get a nice clear image with no flickering as expected from the scenario in the first image:

![image](https://user-images.githubusercontent.com/58787893/139314649-6cf8e2f4-aba1-4c78-8551-bc1675102410.png)

### Expected behavior
An image as shown in the latter screenshot but with interlacing disabled and vsync enabled.

### Actual behavior
The shader does not render correctly.

### Steps to reproduce the bug
1. Enable vsync
2. Enable CRT-royale
3. disable the `Interlace - Toggle` setting in the shader settings

### Version/Commit
- RetroArch: e2b7c23

### Environment information
- OS: Windows

Some extra info if it's relevant:
- I am using the vulkan display driver as is required for crt-royale
- I have an Nvidia GPU with up-to-date drivers
- I have a 165hz refresh monitor and the gsync option enabled in the video settings, although this doesn't seem to matter. The behaviour is the same if I set retroarch to 60, 120, or 165hz manually, or enable/disable gsync.

**Comment by JordanAnthonyKing** [comment]
None of the passes seem to accept 0.5 scale as an input, only 1x-5x

**Comment by hizzlekizzle** [comment]
I meant in the preset file. The menu only works in integers, as you've noticed.
