### ISSUE TITLE
won't load anything over 2gb

### ISSUE THREAD

**Issue by Blaze269** [libretro/RetroArch#13160]
Cant put any iso over 2gb, it says it cant be found. Xbox series x . Everything worked fine in version 1
.9.10

# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by Gamr13** [comment]
This issue can now be closed. [#13348](https://github.com/libretro/RetroArch/pull/13348)

**Comment by aymeric-giraudet** [comment]
Built a UWP version myself with @tunip3's fixes and it indeed does work like a charm ! Just make sure you quit RetroArch before reloading another game for the cache to be flushed an it'll load instantly even for a 4.5gb iso
Thanks a ton !
