### ISSUE TITLE
Offer Minimal RetroArch Builds for Windows [Request]

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#13175]
I'm not sure if many users besides me would like this, but I think it'd be nice to have a minimal RA Windows package with a few features that require many .dll dependencies disabled. Primarily FFMPEG and qt. I imagine there are many users who don't use video/audio file playback or the desktop menu, and those require the most .dlls. I'd be open for suggestions for other lesser used features that would make the .exe smaller and/or remove .dlls.

When I've done my own minimal builds, I've disabled all this stuff:
`./configure --disable-overlay --disable-networking --disable-video_filter --disable-video_layout --disable-glsl --disable-bsv_movie --disable-dsp_filter --disable-cheats --disable-rewind --disable-accessibility --disable-translate --disable-cdrom --disable-imageviewer --disable-qt --disable-ffmpeg --disable-sdl2 --disable-blissbox --disable-xmb --disable-materialui --disable-rgui --disable-d3d9 --disable-d3d10 --disable-wasapi --disable-libretrodb --disable-audiomixer --disable-dsound --disable-flac --disable-dr_mp3 --disable-rtga --disable-rjpeg --disable-rbmp --disable-freetype --disable-langextra --disable-cc_resampler --disable-nearest_resampler --disable-crtswitchres --disable-chd --disable-7zip --disable-patch`

That's probably going too far since most of those probably only remove a few kb from the .exe at most. Maybe SDL2, since it's .dll is one of the largest at 10MB. If you do go that hard with disabling features you get a very small (6.6MB) exe with just three .dlls.

If a minimal download is made available, the unavailable features could just be added in parenthesis next to it, ie (audio/video file playback and desktop menu disabled). If it's too much strain on the buildbot, it could only be made for point releases, but I'd love to have minimal nightlies too. Not sure if Linux or other OS's would be worth having minimal builds too since dependencies are different there, I think.

**Comment by gouchi** [comment]
You should try to open this issue in [libretro super repository](https://github.com/libretro/libretro-super) ?

**Comment by Awakened0** [comment]
Sure, I've moved it here: https://github.com/libretro/libretro-super/issues/1581
