### ISSUE TITLE
No Japanese system language for PCSX2

### ISSUE THREAD

**Issue by krizalidzero** [libretro/RetroArch#13174]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

PCSX2 Core has no "System Language: Japanese" option

### Expected behavior

It should have a Japanese option

### Actual behavior

The core is openable, but Japanese ISOs fail to load (they load normally on stand alone PCSX2 1.6, so ISOs and BIOS are not the issue).

### Steps to reproduce the bug

1. Start PCSX2 core
2. Go to its configuration
3. Check System Language setting and see that Japanese is not available

### Bisect Results
From the start
[libretro INFO] Bios Found: Japan   v01.00(17/01/2000)  Console
[libretro INFO] Detected BIOS: Japanv01.00(17/01/2000)Console 
[libretro INFO] No injection data found for Bios "biosfilename" - language: English 
[libretro ERROR] Could not open File: ��L
[ERROR] [CONTENT LOAD]: コンテンツのロードに失敗しました

### Version/Commit

- RetroArch: Oct 9 2021

### Environment information

- OS: W10

**Comment by gouchi** [comment]
Hi,

This issue should be better in [libretro pcsx2 repository](https://github.com/libretro/pcsx2/issues) ?

Thank you.

**Comment by krizalidzero** [comment]
Thank you! Sorry, I did not realize I was in the wrong Git.
