### ISSUE TITLE
Linux - Unable to detect (DIY) USB light gun

### ISSUE THREAD

**Issue by SeongGino** [libretro/RetroArch#13189]
## Description

When using the `udev` general input device, RetroArch either fails to parse or intentionally ignores the pointer device generated by an Arduino/RP2040-based light gun, making it unavailable to select as a mouse for gun games.

### Expected behavior

The light gun should be detected as a mouse and available to use as a mouse device with the `udev` driver.

### Actual behavior

The gun's mouse event (in this case, `event10`) is unable to be loaded in RetroArch's startup process.

### Steps to reproduce the bug

0. Running user needs to be in `input` group for *udev* input driver to work without root privileges.
1. Start RetroArch with verbosity enabled: `retroarch -v`
2. Observe this line in the startup process:
```[INFO] [udev] udev_input_add_device error : /dev/input/event10 (Success).```
3. Compare the event device number ignored/error'd by RetroArch to the list of devices detected in X's input hierarchy with `xinput-gui`, and observe the light gun's mouse's device node (highlighted in blue for demonstrative purposes here) to verify it's the right device being skipped:
![ksnip_20211105-162125](https://user-images.githubusercontent.com/7321839/140573718-c580e7a2-f3e8-466f-aafa-c361093abe8f.png)

If desired, [see the logfile attached for details.](https://github.com/libretro/RetroArch/files/7488771/retroarch_log.txt)

### Bisect Results

AFAIK, this is in all current RetroArch releases, but has only been observed in stable releases 1.9.11 and 1.9.12.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.12 (Git e2b7c23902) from Arch Linux's community (stable) repositories, ver. `1.9.12-1`

### Environment information

- OS: EndeavorOS / Arch Linux

### Other Information

This gun device works in `x` general input driver, so this issue only pertains to `udev` input driver.
Said device also works properly in MAME standalone once setup for use with Linux/X11 gun devices, a'la Aimtraks.
DIY project in question is based on the [SAMCO](https://github.com/samuelballantyne/IR-Light-Gun) DIY Light Gun system; I'm unable to verify if this affects [GUN4IR](https://github.com/JayBee-git/GUN4IR) devices as they use similar Arduino-based boards but different bootloaders (Arduino vs. custom).

**Comment by grant2258** [comment]
There was an issue with the detection that has been updated now sorry for any inconvenience. Im starting to look into making pointer devices work a little better. I didnt anticipate an abs device without a touch button so the default behavior is to log if there is no buttons detected. if you can try teh latest master and let me know if you have any issues commit was added here. https://github.com/libretro/RetroArch/commit/1ae36ee9a7b6737affdcf17026c5f7c4d4d023c8

**Comment by SeongGino** [comment]
> There was an issue with the detection that has been updated now sorry for any inconvenience. Im starting to look into making pointer devices work a little better. I didnt anticipate an abs device without a touch button so the default behavior is to log if there is no buttons detected. if you can try teh latest master and let me know if you have any issues commit was added here. [1ae36ee](https://github.com/libretro/RetroArch/commit/1ae36ee9a7b6737affdcf17026c5f7c4d4d023c8)

Thanks, and no hard feelings!
I've managed to build from master and it does indeed recognize the device just fine.
Though, I'm noticing that the cursor or calibration seems to behave like MAME, where it assumes the content spans across the entire display rather than taking the content's actual emulated display size into account--i.e. 4:3 on 16:9 display--like the X driver or Windows' rawinput usually does?

Apologies if that may be a separate issue; if it is, then I'll consider _this_ issue fixed and make another regarding this cursor behavior.

**Comment by grant2258** [comment]
It would be best to create an issue as i dont have windows installed on any of my boxes I couldnt tell you how they behave or should be behaving thats something that should be clarified on the api side to be honest. I havent changed any of the code relating to that though its was always this way.

**Comment by SeongGino** [comment]
Fair enough. Closing this for now.
