### ISSUE TITLE
[Windows] Vulkan driver crashes RetroArch in AMD Radeon iGPU / Nvidia dGPU systems

### ISSUE THREAD

**Issue by zachlutz** [libretro/RetroArch#13196]
## Description

On Windows 10, RetroArch crashes to the desktop on launch when the Vulkan driver is enabled. This issue seems isolated to systems with hybrid graphics, and possibly unique to systems with NVIDIA GPUs. Workarounds include disabling and re-enabling the integrated GPU in Device Manager (which is temporary, and does not survive restarting Windows), or using an alternate video driver in RetroArch such as glcore.

This issue is further documented with crash logs in the forums here: [https://forums.libretro.com/t/retroarch-crash-to-desktop-if-i-use-vulkan-video-driver/30351/12](https://forums.libretro.com/t/retroarch-crash-to-desktop-if-i-use-vulkan-video-driver/30351/12) and on the Discord help channel in the exchange between Flynn58 and pnill on 4/20/21. It is postulated the issue may relate to the enumeration / ordering of GPUs, and may be resolved by directing Vulkan which GPU to use.

### Version/Commit

- RetroArch: 1.9.12 / e2b7c23

### Environment information

- OS: Windows 10 21H1 build 19043.1288
- Driver: GeForce Game Ready Driver, Version 496.49 / Release Date: 10/26/2021

**Comment by eimfach** [comment]
I also have this issue on windows 10/ amd rx 480 (Adrenalin 21.10.2 Recommended), Intel core i5 6660k, also dx9-10 and dx12 are crashing, except dx11, gl, glcore ...

It crashes when I start a game with e.g. Dolphin. I also can't find any logs in the logs folder ...

**Comment by zachlutz** [comment]
Closing issue. Upon further investigation, the Vulkan crashing was the result of a now-resolved bug in AMD drivers. More info is as follows:

On an affected system, typing vulkaninfo at the command prompt in Windows results in the following error:

vulkaninfo
WARNING: [Loader Message] Code 0 : ReadDataFilesInRegistry: Registry lookup failed to get layer manifest files.
The selected gpu (0) is not a valid GPU index. The available GPUs are in the range of 0 to 18446744073709551615.

The issue is documented here: https://github.com/KhronosGroup/Vulkan-Loader/issues/552

And acknowledged by AMD here: https://github.com/GPUOpen-Drivers/AMDVLK/issues/196

And fixed in the AMD Radeon 2021.Q2.1 release: https://github.com/GPUOpen-Drivers/AMDVLK/issues/196#issuecomment-815423841

Despite resolution, some users with a fully updated system may continue to experience the error if their system manufacturer has yet to release an updated AMD driver. If you are experiencing this issue, you have two options:

Workaround (untested by me): As detailed in https://github.com/KhronosGroup/Vulkan-Loader/issues/552, at the command prompt, enter the string: set DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1=1

Resolution: Install latest AMD Radeon graphics drivers directly from AMD. It is recommended that you do the optional factory reset in the installation options. However, installing the latest Radeon driver from AMD may cause unintended side effects on your system, as this driver will not be fully tested by your computer manufacturer.

Note: Before installing the latest driver directly from AMD, you may wish to visit your system manufacturer's driver download page, to see if an updated driver is available that was not made available via auto-update means.

**Comment by watson1423** [comment]
Hello just to note 

CPU rysen 5800x
Gpu0 rx 7900 xt
Gpu1 gtx 1070

I am having this issue when rx 7900 xt is selected as vulkan render on gtx it works fine only in vulkan and dx12 I found issue on gl it runs fine I am using the emulators on gl for now.
