### ISSUE TITLE
Segfault when no next audio resampler driver is found

### ISSUE THREAD

**Issue by micechal** [libretro/RetroArch#1319]
It happens when you try to select next audio resampler driver in rgui, but there is no next driver of such kind. At the writing of this, that means:
- Pressing left, when the current driver is `sinc`.
- Pressing right, when the current driver is `nearest`.

Relevant log part: http://hastebin.com/ifucococam

**Comment by micechal** [comment]
It only happens audio is disabled.

**Comment by twinaphex** [comment]
I can't reproduce this so far.

**Comment by micechal** [comment]
I still can, using today's nightly on Android:
1. Disable audio
2. Quit Retroarch
3. Back in Java menu; resume content
4. Try changing audio resampler driver beyond `nearest`
It still crashes.
