### ISSUE TITLE
1.9.13 - Crash on content load w/ Cheevos On

### ISSUE THREAD

**Issue by Son-Vegitto** [libretro/RetroArch#13202]
##Description

After updating from 1.9.12 Android to 1.9.13, content crashes on load. If I turn Achievements (cheevos) off, content loads fine.

### Expected behavior

Content to load successfully, without crash, when cheevos is On.

### Actual behavior

Content crashes when loading, when cheevos is On.

### Steps to reproduce the bug

1. Update to 1.9.13
2. Load content (any core. I used mGBA and Snes9x - Current)
3. First frame of content displays, then retroarch freezes and crashes

### Bisect Results

After installing 1.9.13. No other changes were made. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: a93a2e3

### Environment information

- OS: Android 8.2
- Compiler: Clang/LLVM (RetroArch website)

**Comment by Jamiras** [comment]
There seems to be a problem reinitializing rewind after the achievements have been activated. Can you verify whether you have rewind on and achievements hardcore off?

**Comment by Son-Vegitto** [comment]
I can confirm I have rewind on and hardcore off.

**Comment by Jamiras** [comment]
Thank you. I'm working on a fix for that. In the meantime, you should be able to disable rewind or enable hardcore to get around the issue.

**Comment by Son-Vegitto** [comment]
Super - thank you, very much!
