### ISSUE TITLE
[PS VITA] Crash when launching just one specific game on gpsp core

### ISSUE THREAD

**Issue by circa-0** [libretro/RetroArch#13218]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The whole app crashes when loading the game “Star Wars A New Droid Army” when using the gpsp core. All other games work perfectly fine, just not this one game.

### Expected behavior

The game to play.

### Actual behavior

Crash with error:
“An error has occurred in the following application.
(C2-12828-1)
Saved Core File Succeeded.
uxO:data/psp2core-1636590913-0x0000442bed-gpsp_libretro.self.psp2mp”

### Steps to reproduce the bug

1. Find rom in directory
2. load it with gpsp core

### Version/Commit
You can find this information under Information/System Information

- RetroArch: build Nov 9 2021
- Git version: a68b956
- gpsp version v0.91 e8eb753

### Environment information

- OS: PS Vita
- Compiler:

**Comment by circa-one** [comment]
This is a game I have had issues with in gpsp-based emulators. I’ve had to add this to the game_config.txt which may be part of the issue. If this could be added to that and tested to see if that fixes it, that would be awesome.
`# Star Wars: A New Droid Army
game_name = STAR WARS: T
game_code = A2WE
vender_code = 78
iwram_stack_optimize = no `
