### ISSUE TITLE
AI Service Image Mode overlay not appearing when language set to Japanese

### ISSUE THREAD

**Issue by michael-myers** [libretro/RetroArch#13224]
## Description

I would like to be using the AI Service translation feature, which almost works as described (configuration seems to work, Google Cloud OCR works, Google Cloud Translate works), but text overlays within RetroArch do not appear.

FWIW, in Information > System Information within RetroArch, `Overlay Support` says `Yes`.

### Expected behavior

Little black boxes with white text containing the translation, to appear around the screen on the emulated display (the RetroArch window).

### Actual behavior

The translation is being returned successfully by `vgtranslate` but not displayed on screen. I can see it in the `vgtranslate` terminal window outside of RetroArch.

<img width="1422" alt="Screen Shot 2021-11-07 at 2 21 30 AM" src="https://user-images.githubusercontent.com/5177188/141361210-5b60e8aa-bf60-496c-8138-134347b6210b.png">

### Steps to reproduce the bug

1. In Settings > AI Service, set `AI Service Enabled` to `On`, `AI Service Output` to `Image Mode`, and `Pause During Translation` to `On`. Bind a hotkey in RetroArch to AI Service. Source language set to `Japanese - 日本語`.
2. [Set up vgtranslate and a Google Cloud API account and configure that, launch it]
3. Hit the AI Service hotkey during gameplay, and observe that the emulator core pauses, the translation is returned in the `vgtranslate` terminal, but nothing is on screen in RetroArch. Unpause, still nothing.

### Bisect Results

Reportedly, it used to work as recently as RetroArch version 1.7.8. I didn't regression test historical versions of RetroArch.

### Version/Commit

- RetroArch Metal: 1.9.12

### Environment information

- OS: macOS 12.0.1
- Compiler: n/a

**Comment by michael-myers** [comment]
Update: still happens in 1.9.13.

If source language is set to `Default`, the overlay appears correctly. I am going to use this as the workaround for now, but this seems like something that could be fixed.

**Comment by sbloom85** [comment]
Still not working as of 1.16.0. I have the service URL pointing to ztranslate.net
