### ISSUE TITLE
Really tired of netplay issues. See inside.

### ISSUE THREAD

**Issue by PlasmicRedX** [libretro/RetroArch#13228]
Log of RetroArch, Netplay stuff:
>[INFO] [Netplay]: Connecting to 192.168.0.80:55435 (direct)
*hanging forever*
>me typing: disconnect please
>me typing: you retarded idiot you are supposed to disconnect after enough time elapses
>me typing: God please do something.
>my friend hosts server
*OH HELLO*
>[ERROR] Failed to connect to host 192.168.0.80 on port 55435.
>[ERROR] Failed to set up netplay sockets.
>[WARN] Failed to initialize netplay.
+try again+
>[INFO] [Netplay]: Connecting to 192.168.0.80:55435 (direct)
>[ERROR] The netplay peer is running an old version of RetroArch. Cannot connect.
>[INFO] Netplay disconnected

We're connecting over a LAN, or trying to, using Linux Mint 20.2 64bit Xfce, me, desktop gaming computer, and him, Windows 10 desktop gaming computer.

I have downloaded and built from source code, he has installed from RetroArch website. We can't manage to get the same github version and play together, despite having the same exact version number Version 1.9.13 and we tried also with 1.9.13-1.

In normal times would be sorry but this isn't normal for programs to normally shut out people with different versions even slightly off by one line of code which may or may not even be comment lines.

**Comment by PlasmicRedX** [comment]
Another issue (slightly off subject here) is that after you build Retroarch from source, all the directories point to /usr/local/ and /usr/bin/libretro and a bunch of other folders. We're being asked to literally supply our own install of super-libretro. So I usually just have to compile RetroArch from source and then point, one at a time painfully, each directory to the folders in the original compiled directory I compiled it from. Which takes a long time.

**Comment by twinaphex** [comment]
I'll pass it forward to a netplay developer that is helping us improve netplay.

**Comment by hizzlekizzle** [comment]
> all the directories point to /usr/local/ and /usr/bin/libretro and a bunch of other folders

I have not experienced this, and I compile from source all the time. Default locations are all in ~/.config/retroarch for me. Are you using a pull from github or downloading the source from the Mint repos?

**Comment by twinaphex** [comment]
Hi, I have been told the following by Cthulhu:

[5:25:47 AM] <Cthulhu88> the long hanging time is because the socket is in blocking mode at that point
[5:26:00 AM] <Cthulhu88> so it's OS_dependent the timeout for a failed connect
[5:26:17 AM] <Cthulhu88> i change it to non-blocking and use select to add a custom timeout if you want
[5:27:08 AM] <Cthulhu88> as for the error
[5:27:12 AM] <Cthulhu88> "old version"
[5:27:22 AM] <Cthulhu88> it's because it's protocol 6 on github
[5:27:25 AM] <Cthulhu88> while 1.9.13 is protocol 5
[5:27:38 AM] <Cthulhu88> bump it back to 5 if you need to test
[5:31:00 AM] <Cthulhu88> you can reply with what i said
[5:31:04 AM] <Cthulhu88> i think i covered everuthing
[5:31:18 AM] <Cthulhu88> github repo is the netplay code being worked for 1.10
[5:31:21 AM] <Cthulhu88> so it wont work with 1.9.13
[5:31:43 AM] <Cthulhu88> tell him to compile the source code from 1.9.13 instead

We will need to do a hard break in netplay compatibility in order for it to support all future improvements that we plan on doing this. I tried postponing this as much as possible but alas, them's the breaks.

**Comment by PlasmicRedX** [comment]
Thanks, he managed to find the right version on Windows and we got it working.



> > all the directories point to /usr/local/ and /usr/bin/libretro and a bunch of other folders
> 
> I have not experienced this, and I compile from source all the time. Default locations are all in ~/.config/retroarch for me. Are you using a pull from github or downloading the source from the Mint repos?

The configuration text files and stuff goes there. But for cores, core info files, overlays, video filters, audio filters, shaders, and more stuff that is very cool like that all goes to the folders I mentioned. Some of them go to something called ~(guessing from memory)~~64_linuxgnu or something with libretro in the name. To get around this problem, I used catfish to fish for the directories in the compiled retroarch folder. I also asked my friend to stream where his directories are pointing. So then we got my cores and stuff fixed.

**Comment by PlasmicRedX** [comment]
> Hi, I have been told the following by Cthulhu:
> 
> [5:25:47 AM] the long hanging time is because the socket is in blocking mode at that point [5:26:00 AM] so it's OS_dependent the timeout for a failed connect [5:26:17 AM] i change it to non-blocking and use select to add a custom timeout if you want [5:27:08 AM] as for the error [5:27:12 AM] "old version" [5:27:22 AM] it's because it's protocol 6 on github [5:27:25 AM] while 1.9.13 is protocol 5 [5:27:38 AM] bump it back to 5 if you need to test [5:31:00 AM] you can reply with what i said [5:31:04 AM] i think i covered everuthing [5:31:18 AM] github repo is the netplay code being worked for 1.10 [5:31:21 AM] so it wont work with 1.9.13 [5:31:43 AM] tell him to compile the source code from 1.9.13 instead
> 
> We will need to do a hard break in netplay compatibility in order for it to support all future improvements that we plan on doing this. I tried postponing this as much as possible but alas, them's the breaks.

Also I downloaded https://github.com/libretro/RetroArch/tree/v1.9.13.1 in zip and extracted it over my retroarch folder to force a merged compile to skip having to spend 2 hours compiling super-libretro cores and all that and that's how we managed to get up and running today after being stuck since November 6 when we first tried RetroArch. Also I been learning to build from source for the first time using github, so it's all new to me.

**Comment by PlasmicRedX** [comment]
Ok my friend just tells me all he did to get the same version as me is he just downloaded the newest version over again, so I guess it was just a special case of us running into basic problems like when we install retroarch somehow we wound up with different versions only slightly. His firewall in windows (in the beginning) was on November 6. Stuff like that. Thanks for understanding. Sorry for not remembering all the exact details of the directories it routed to at first. Again though it's something in that ~/usr/ general direction. I wish that the cores and content could just be included without issue. Seems kinda dumb that Nintendo is still making money off stuff we already paid for 20+ years ago and still own. And it keeping our desktops back from doing what they can do. ;) :( ;(

**Comment by twinaphex** [comment]
We are not in control of what distributions push in their package manager versions of RetroArch. Usually they make changes to it that I personally would disagree with, like excluding the Online Updater, Core Updater, or certain paths. Unfortunately it is what it is, they make all these weird arbitrary changes based on how well it fits in with their package management system of installing software. Outside of compiling your own build, you could also the flatpak or flathub builds that @hizzlekizzle and @RobLoach provide for a more out of the box experience that we personally put our stamp of approval on.

**Comment by RobLoach** [comment]
Also note that if you're hosting a netplay game, you'll have to open your TCP port on your Firewall/router in Settings > Network :wink: 

> me typing: you retarded idiot you are supposed to disconnect after enough time elapses

Take caution on using language like this. It goes against our [Code of Conduct](https://github.com/libretro/RetroArch/blob/master/CODE_OF_CONDUCT.md). Thanks!

**Comment by PlasmicRedX** [comment]
Cool, I like to hear it! :D Tyvm, friends.
Yes, packages are quite the problem. Staying with a good package Manager, that is. I ran into an issue with a deprecated package called the OBS NDI plugin. Ever heard of that one? It was preventing me from even sudo apt-get install and update. Aptitude would simply not let me tell it to ignore it. So I talked to someone who knew Linux more than me, and he told me whenever he has package manager problems he usually just tries to avoid them and only build from source. So I am in this mode right now. Just building everything I find from source. It has been hard but I am finding out that it is rewarding me. I didn't know that existed before. I did run RetroArch from flatpak and I liked that one better, but I wound up uninstalling it and I think it was because my friend had his firewall on and we couldn't connect, so I thought building it from source would fix it. :hand_over_mouth: 
But we're in an even BETTER position now than we were due to all the tolerance for building it. I heard it's on Steam, too, my friend tried to get me to install that one.


> Also note that if you're hosting a netplay game, you'll have to open your TCP port on your Firewall/router in Settings > Network wink
> 
> > me typing: you retarded idiot you are supposed to disconnect after enough time elapses
> 
> Take caution on using language like this. It goes against our [Code of Conduct](https://github.com/libretro/RetroArch/blob/master/CODE_OF_CONDUCT.md). Thanks!
It's called using a phrase to entertain people. That isn't against any code of conduct to the human race. Humanities are part of github.

**Comment by RobLoach** [comment]
Would love to clean up [RetroArch's Launchpad PPA](https://launchpad.net/~libretro/+archive/ubuntu/stable), but PPAs and apt packages go way over my head :upside_down_face:

**Comment by RobLoach** [comment]
> It's called using a phrase to entertain people. That isn't against any code of conduct to the human race. Humanities are part of github.

While you may intend it to entertain, it is easy to misunderstand sentiments online. It is a code of conduct we adopt within the libretro community to ensure an open and welcoming space. GitHub itself has its own [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) that we abide by too. There's no problem with this instance, we're just careful about it :+1:

**Comment by PlasmicRedX** [comment]
I'm very welcoming. The netplay code was not, though. So you either take the side of the code or the human, who is just focusing on the proper spirit of the law. The law is that retroarch is a program that serves me.
So be awesome and accept that. You're welcome.

**Comment by RobLoach** [comment]
Sounds like you figured out the netplay issue. Glad it got resolved.
