### ISSUE TITLE
how to add a thumbnails to Favorites section?

### ISSUE THREAD

**Issue by nictse2013** [libretro/RetroArch#13236]
https://docs.libretro.com/guides/roms-playlists-thumbnails/

I follow this rules, create a folder named 'Favorites' under Thumbnails folder.Put thumbnails file under thumbnails\Favorites\Named_Boxarts.

but display under RA

**Comment by gouchi** [comment]
Hi,

Please follow the [issue guidelines](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md) as stated

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

You should better add first your question in the [forum](https://forums.libretro.com).

For your case, please first scan your game then from the the list select one game and from the context menu Add it to Favorites.

You will have now favorite section and from there you can select Download Thumbnails.

Thank you.

**Comment by nictse2013** [comment]
1. THX I will ask in the forum next time.
2. I googled, like ur said need create list first.but if u create a list on xbox version RA,u move to list section,RA will freeze.
So seems no answer for now.

**Comment by RobLoach** [comment]
The thumbnail file name has to match what's listed in the playlist, as you linked in the documentation. Check Custom Thumbnails section.
