### ISSUE TITLE
Nintendo Switch Pro Controller not working on MacOS

### ISSUE THREAD

**Issue by GenesisGreen** [libretro/RetroArch#13237]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Nintendo Switch Pro Controller does not work on MacOS

### Expected behavior

Being able to control menus and games with Pro Controller

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. Connect Nintendo Switch Pro Controller to Mac
2. Open RetroArch
3. Configure controller

### Bisect Results

Not sure, but the first time I tried using a Pro Controller the issue started and I haven't been able to resolve it. It used to work when I used Steam to connect it but the analog sticks never worked, and now it doesn't work with either situation.
### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.13

### Environment information

- OS: MacOS Big Sur 11.4

**Comment by Shimmer2** [comment]
Me too

**Comment by gouchi** [comment]
Please provide some [log](https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-os-x) also did you try with other controller drivers (Settings tab > Drivers > Controller) ?

Thank you.

**Comment by Shimmer2** [comment]
![Uploading 截屏2022-06-03 上午11.21.44.p
<img width="1393" alt="截屏2022-06-03 上午11 21 31" src="https://user-images.githubusercontent.com/79088619/171780034-14d05e06-4bfd-4802-baa9-72f59794c6e1.png">
ng…]()

**Comment by Shimmer2** [comment]
<img width="780" alt="截屏2022-06-03 上午11 28 21" src="https://user-images.githubusercontent.com/79088619/171780888-ed0e4683-4288-4556-b354-ac029ee55ba3.png">
<img width="1393" alt="截屏2022-06-03 上午11 25 56" src="https://user-images.githubusercontent.com/79088619/171780898-b5f675c4-ca6e-4489-9857-e10c6c5f4741.png">
<img width="1393" alt="截屏2022-06-03 上午11 26 31" src="https://user-images.githubusercontent.com/79088619/171780902-601dc79f-e666-40e6-b138-1159e002bb0a.png">

**Comment by Shimmer2** [comment]
![未命名](https://user-images.githubusercontent.com/79088619/171781153-7cb27531-39de-43c6-90df-04220c64d0da.png)

**Comment by Shimmer2** [comment]
The Switch pro controller can control cursor movement at the launcher, but does not work in the ratroarch and input cannot be detected when setting the key

**Comment by Shimmer2** [comment]
Switch pro controller works working on Mac os 10.14 mojave and not available on Mac os 12 and my mac has not installed drivers for other controllers

**Comment by pedrochamberlain** [comment]
I'm also having the same problem.

I'm using macOS Ventura 13.0

**Comment by Brog33** [comment]
same here. controller works outside of retroarch.

**Comment by Copper280z** [comment]
I was having this issue with an M2 MacBook air, and still am to some extent. I got the controller working in the menu by manually giving RetroArch access under accessibility in privacy settings. It still doesn't work in an emulator (pcsx, specifically).

It does work in an emulator if I launch from Steam as a non-steam game.

**Comment by fooness** [comment]
The Switch Pro Controller seems to be natively supported on macOS Ventura, and it’s been quite some time since I had any problems at all with that controller on macOS Ventura. I was very much surprised when I installed and opened retroarch (metal as well as non-metal) and the controller is not working at all, even though the controller is recognized and shown correnctly via input 01.

> I got the controller working in the menu by manually giving RetroArch access under accessibility in privacy settings.

This does not work for me.

Any idea which problems we’re facing here? When it comes to drivers, there’s only `hid` available in my retroarch install.

**Comment by Brog33** [comment]
Yes, macos supports the controller natively. Two emulators I use the Pro Controller in are Atari800MacX and Dolphin. No problems there.

**Comment by fooness** [comment]
For me, the controller flawlessly worked/works in the following emulators:

- [x] Dolphin Beta `5.0-18498` (latest) and `5.0-17995` (previous)
- [x] OpenEmu `2.3.3`
- [x] mGBA `0.10.1`

The controller also works in some standalone games, like Celeste or Tunic.

Maybe an interesting detail: This machine never had Steam installed.

_On other machines with Steam installed, the controller worked in/via Steam._

**Comment by LibretroAdmin** [comment]
@fooness Please use the latest nightlies instead of stables (or any kind of online repository like brew), 1.14.0 is quite out of date now and doesn't enjoy any of the new features @warmenhoven has been adding recently that have improved the macOS port by a lot, including MFi support.

**Comment by fooness** [comment]
@LibretroAdmin Thank you, I didn’t think about the nightly builds; will try immediately and report back.

When it comes to compiling from source, in fact I wanted to try this, but I did not find any build/compile instructions here on GitHub or in the libretro docs; maybe you could help out by pointing me to some valid and current resources, please?

**Comment by Agusum** [comment]
I've downloaded the latest nightly of the Mac Intel version, manually enabled the app under the Privacy settings for both Accessibility and Input Monitoring. The controller gets detected but it doesn't work.

It does work on other apps such as Steam, Dolphin or OpenEmu.

Is there anything else I can try?

<img width="942" alt="image" src="https://user-images.githubusercontent.com/4369698/221408187-3478ef24-e345-49e6-bc2e-156f8934d267.png">

**Comment by warmenhoven** [comment]
@Agusum Which input driver are you using (mfi or hid)? Try the other one and see if that works. My suspicion is that mfi should work but it would be nice to confirm.

**Comment by Agusum** [comment]
@warmenhoven I only have the hid option available. How can I get mfi to appear?

**Comment by fooness** [comment]
Oh, interesting, I missed that `mfi` is available, though not selected in my case, via: `Settings` -> `Drivers`

<img width="1072" alt="Screenshot 2023-02-27 at 09 45 58" src="https://user-images.githubusercontent.com/11408027/221516085-7b4ed3de-d845-43d5-9b4d-df28cc14a23c.png">
<img width="1072" alt="Screenshot 2023-02-27 at 09 46 02" src="https://user-images.githubusercontent.com/11408027/221516089-a30b5e64-0ab5-42fe-9944-42935f826ba6.png">
<img width="1072" alt="Screenshot 2023-02-27 at 09 46 14" src="https://user-images.githubusercontent.com/11408027/221516092-e2080fd9-69bc-4e54-8e9d-6c6e1ab25041.png">

Once starting some core, e.g. mGBA, the controller name in `Port 1` changes:

<img width="832" alt="Screenshot 2023-02-27 at 09 48 16" src="https://user-images.githubusercontent.com/11408027/221516452-d0b2d76d-4086-49a7-a779-4f63cac260ac.png">

**Comment by Agusum** [comment]
That's where I checked and I only have the hid option:
<img width="949" alt="image" src="https://user-images.githubusercontent.com/4369698/222977974-b6561f4e-0fd7-4ffc-b908-e097983d3151.png">

**Comment by This-will-be-your-username** [comment]
I'm very much having the same issue using the latest nightlies (03.05 and 03.06). Retroarch doesn't prompt me with any option other than hid for an input driver, even after pairing and repairing the controller before Retroarch launch as well as after. No combination provides any change.

**Comment by warmenhoven** [comment]
Please try the Metal nightly.

**Comment by This-will-be-your-username** [comment]
That did it. Thank you

------- Original Message -------

**Comment by Brog33** [comment]
Thanks! Can confirm it works too.

**Comment by Agusum** [comment]
This now works fine in version 1.15.0. The default mapping is not correct but that's a separate issue.

This issue can be closed.

**Comment by gouchi** [comment]
@GenesisGreen Please close this issue.

Thank you.

**Comment by GenesisGreen** [comment]
Oh, I forgot I had opened this issue, thank you all!
