### ISSUE TITLE
1.9.13 ninjafix - Rewind does not function w/ cheevos On

### ISSUE THREAD

**Issue by Son-Vegitto** [libretro/RetroArch#13241]
##Description

After updating from 1.9.12 Android to 1.9.13 ninjafix, rewind is not working. If I turn Achievements (cheevos) off, rewind works fine. Hardcore mode is Off.

Expected behavior
Rewind to work correctly, when cheevos is On.

Actual behavior
Rewind has no effect, when cheevos is On.

Steps to reproduce the bug
Update to 1.9.13 ninjafix
Load content (any core. I used mGBA and Snes9x - Current)
Let content progress a bit, then attempt to rewind. 

Bisect Results
After installing 1.9.13 ninjafix. No other changes were made.

Version/Commit
You can find this information under Information/System Information

RetroArch: b6cd140
Environment information
OS: Android 8.2
Compiler: Clang/LLVM (RetroArch website)

**Comment by Jamiras** [comment]
The fix added to prevent the deadlock when rewind was enabled (#13207) changed the order of things such that the rewind buffer was being initialized before the achievements were marked as ready, so enough space was not being allocated to the individual rewind frames. As a result, if enough achievements were active, the serializer would silently fail.

**Comment by Son-Vegitto** [comment]
Thank you for the info. If I grab a nightly build, it looks like this will be resolved?

**Comment by Jamiras** [comment]
Not until the other PR is closed, and then it could be up to 24 hours before it makes it into a nightly.

**Comment by twinaphex** [comment]
Merged it now.

**Comment by Son-Vegitto** [comment]
Nice! Thank you!

Think this will hit the nightly build today or tomorrow?
