### ISSUE TITLE
[Android 11] In Warioware twisted gyroscope control stops working when I pull down the notifications

### ISSUE THREAD

**Issue by dm699** [libretro/RetroArch#13244]
[Screen recording of the issue](https://imgur.com/a/yLOb7E9)

Expected behaviour:
The gyroscope controls should continue working when the game is unpaused

Steps to reproduce:
1)Pull down the notifications and retroarch is paused
2) get out of the notification bar, retroarch isn't unpaused open recent apps then open retroarch from there then the game is unpaused but gyroscope stops working

Im using the mgba core on rettoarch plus(downloaded it from the google playstore) and the game is Warioware twisted! on Oppo f11(running android 11) 

Gyroscope does start working again when I tap close content and then start the game again. However, I doesn't start working when I use restart.

**Comment by aaronbytes** [comment]
This should be fixed now!
