### ISSUE TITLE
Can't compile gfx/video_crt_switch.c on RPi

### ISSUE THREAD

**Issue by arpruss** [libretro/RetroArch#13259]
## Description

Cannot compile gfx/video_crt_switch.c due to a RARCH_LOG() call at line 134.

### Expected behavior

Should compile.

### Actual behavior

Complains `srm` is undefined in `RARCH_LOG("[CRT]: SR integer scaled  X:%d Y:%d \n",srm.x_scale, srm.y_scale);`. 

And indeed when `VIDEOCORE` is set, as it is on the RPi, `srm` is not defined. The `else` branch should be `ifdef`'ed out for `VIDEOCORE`.

**Comment by twinaphex** [comment]
See if this helps -

https://github.com/libretro/RetroArch/commit/ed437fdd8ea1f28b99011eda660eedb2cd9878c0
