### ISSUE TITLE
Web Player and all emscripten nightlies non functional with RA frontend builds.

### ISSUE THREAD

**Issue by thelamer** [libretro/RetroArch#13252]
Traces to this commit:
https://git.libretro.com/libretro-infrastructure/libretro-build-emscripten/-/commit/4e606616fbe58cb58f7dc491701f9a9c4f3adb15
There is no useful output even with debug enabled, the frontend simply fails to render to the canvas even though it is running.

**Comment by twinaphex** [comment]
Ugh.
