### ISSUE TITLE
Keyboard events not passed when run-ahead enabled (affects puae, dosbox...)

### ISSUE THREAD

**Issue by bidinou** [libretro/RetroArch#13261]
## Description
Hi ! I figured out that when enabling run-ahead, keyboard events were not passed to cores anymore.
That is to say, not macros / buttons, but keys actually passed to computer cores to type some text.
It does affects at least puae and dosbox-pure even though thoses cores do not support run-ahead !

### Expected behavior

When enabling "focus mode", I expect the key I'm typing to be passed directly to the core. 
For instance, typing some text in an interactive fiction.
Regardless of the state of "focus mode", when "run ahead" is enabled, keys are not sent to the core.

### Actual behavior
Nothing happens. 
If I disabled focus-mode, macros are triggered properly.

### Steps to reproduce the bug

1. Enable run-ahead
2. Start puae or dos-box SVN with any content requiring keyboard input
3. Enable focus mode
4. Type some text in a shell, dos prompt, game etc.

### Version/Commit

- RetroArch: GIT version 02898a4a79 / Nov 13 2021
(snap and flatpak packages)

### Environment information

- OS: KDE NEON based on Ubuntu 20.04

**Comment by bidinou** [comment]
I figured out it also affected disk-swapping in puae !
So a common root cause seems to have various unpredictable effects !

**Comment by sonninnos** [comment]
This can be closed.
