### ISSUE TITLE
Disk swapping broken when run-ahead globally enabled but disabled by current core

### ISSUE THREAD

**Issue by bidinou** [libretro/RetroArch#13272]
Hi ! 
This issue is related to https://github.com/libretro/RetroArch/issues/13261 IMHO. 
Both issues are triggered when run-ahead is globally enabled but not supported by the currently running core.

Example : PUAE and DOSBOX-PURE cores do not support run-ahead, thus disable it. But when it's globally set to enabled, some strange unrelated issues occur.

In this bugreport, I'm specifically referring to swapping floppy disks on the Amiga ; but it's not the core's fault apparently (bugreport here : https://github.com/libretro/libretro-uae/issues/469).

What happens is : the disk initially inserted when the core starts is detected. However, when swapping disks while it's running, the new disks are not actually inserted. The issues disappears when... disabling run-ahead ! (just like the keyboard related issue I file too)

Test machine : Ubuntu LTS based (KDE Neon), both snap / flatpak packages. Version 1.9.13.2. Vega 8 (AMD APU). Vulkan / OpenGL.

Best regards

**Comment by bidinou** [comment]
Here is a debug log. I start the Amiga core with Shadow of Sergoth disk 1 (SOS1).
Then I try to swap the disk. It's not taken into account.
https://easyupload.io/yhhjat
(if I restart without run-ahead, it does work)

**Comment by sonninnos** [comment]
This can be closed.

**Comment by bidinou** [comment]
done, thank you :)
