### ISSUE TITLE
Can not load any content on recent RA build(1.9.13) of any Sega DC games with Flycast Core

### ISSUE THREAD

**Issue by DreaMBlazeR** [libretro/RetroArch#13271]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Not sure what causes it, but I can't load any of my Sega Dreamcast games as of the moment on recent retroarch build(1.9.13) using NAOMI/Flycast Core.

### Expected behavior

[I am able to install Sega DC Naomi/Flycast core, update assets. On Nov. 18 I was still able to play Sega DC games]

### Actual behavior

[However ever since I updated my R.A. build and cores, assets, I am unable to load any Sega DC Roms/content. Just shows [retroarch failed]

### Steps to reproduce the bug

1. [install latest R.A. build 1.9.13, install NAOMI/FLYCAST CORE]
2. [update assets/ put optional assets and BIOSes in system/DC]]
3. [load content (any Sega GDI (MvsC2/ Capcom vs SNK 2/ Skies of Arcadia).. just crashes]

### Bisect Results

[Bug compatibility error started on Nov. 18 since updating. I was still able to play DC games before that point. Please note that  Flycast standalone is still working and able to play these games, but R.A. couldn't for some reason, so it must be in the build itself or possibly regression.]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.9.13]

### Environment information

- OS: [Android KitKat, Lenovo A7:3300-GV Quad-core]
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
Can it be that the new core broke backwards compatibility with Android KitKat @flyinghead ?

**Comment by LibretroAdmin** [comment]
RetroArch version too old, closing. Please report back in case there is still an issue using the latest version.
