### ISSUE TITLE
Stretchable custom viewports

### ISSUE THREAD

**Issue by TheDatadrainer** [libretro/RetroArch#13292]
Hello,
Here is a problem I have for my use of retroarch. It is quite annoying and the only solution I found is to create different configuration for each core on multiple machines.

The problem is custom_viewport_--- values are in pixel and does not allow to share a core configuration between multiple machines with different screen resolution. When using custom overlays with especially placed game viewport, the overlay is stretched but not the view port which is quite disturbing.

A solution could be to have a way to define a custom viewport with percentage instead of pixel so it would be stretched accordingly to the resolution of the screen.

Maybe it is doable by creating a shader, but for the average end user making a shader is a lot more difficult than putting 4 values in a configuration file. Or another solution could be for the devs to make a pre-made configurable shader to do that. like what exist for handheld consoles.

Do you think one of this can be done to allow a real portable core configuration? Thanks

**Comment by hizzlekizzle** [comment]
Have you tried the imgborder shader?

**Comment by TheDatadrainer** [comment]
Thanks for your answer @hizzlekizzle.
Yes I looked at it some time ago. And for what I remember I was not able to configure it properly.
The result I'm wanting to get is to have an overlay of a monitor/CRT/LCD picture with the view port placed anywhere on it and to keep the placement independently of the screen resolution, with a configuration by core. I want to keep the ratio of the view port too as there is no distortion when using a screen with a different ratio, I'm using shaders to make the picture on the view port the most similar possible to the screen draw in the overlay [CRT TV, PC Trinitron tube, GameBoy, GameGear, etc] using curvature, blank between scan lines, moiré, etc and I don't want that to apply to the border (overlay).
Maybe it can be done with imgborder as some handheld borders exists that do the border with LCD matrix effect inside, but I don't now how to do it...
Anyway I don't understand why the overlay is stretched. The renderer can auto-detect the desktop size and there is no way to have the view port matching that. That is just very odd to me.
I just think that maybe a good solution would be add a view port area into the overlay configuration file, then the renderer will use this area by default and then to allow adjustment stretching width and height into this area inside the core configuration file with a percentage value.

**Comment by hizzlekizzle** [comment]
That would require some pretty fundamental changes to the way RetroArch handles overlays and aspect ratios. However, the 'video layout' system can do that sort of thing, AFAIK. It's compatible with MAME's old "lay" artwork format (a few months ago they changed their format in apparently incompatible ways, so make sure you look at the older spec). The only catch for pairing with shaders is that the video layouts only work with the "gl" video driver.

**Comment by TheDatadrainer** [comment]
> It's compatible with MAME's old "lay" artwork format
Interesting. I'm used to create MAME artworks and MAME do exactly what I need. That is why I would like to make something similar with RetroArch as I'm using it for the platform MAME cannot handle properly or too demanding in computer resources.
If it is possible to use MAME lay files with RA, can you tell me how to do it, please?

> The only catch for pairing with shaders is that the video layouts only work with the "gl" video driver.
I didn't understand what you mean here. Pairing MAME artworks with RetroArch shaders?
Most of the time I'm using Vulkan with Slang, but if I have to use OpenGL with GLSL that's not a problem except for paraLLEl N64 I think.

**Comment by hizzlekizzle** [comment]
Yes, that's exactly what I meant. I try to use slang whenever possible, myself, so having to use GLSL shaders with the video layouts is a bit of a bummer, IMO.

Nevertheless, if you go to settings > onscreen display > video layout, you should be able to load a *.lay file or a zip bundle, as long as you're using the "gl" driver.

**Comment by TheDatadrainer** [comment]
Thank you very much for your help @hizzlekizzle. I'll go with your solution, it require to manually change the overlay for each hardware, but it's okay I suppose. In the meantime I keep hopping, one day, a new version of RetroArch will have a a more powerful and flexible overlay system. I mean it is actually still quite good, with a lot of a work done, but in my opinion it lack important features and is not very flexible neither practical to use. One other example is to my knowledge, is it's not possible to map core state of disc activity to a layout by using pictures of lights (on and off) on top of a machine picture (eg. SEGA CD). Another more example would be to have gamepad button images pushed and release for touchscreen control.

Although not resolved, I have a way to go. So I'm closing this issue and I'll wait for newer versions of this great frontend to come with I the hope that it will happen in a near future.
