### ISSUE TITLE
[Android?]Freeze when loading from history if file doesn't exist

### ISSUE THREAD

**Issue by Raijinili** [libretro/RetroArch#1330]
Running Lollipop. Jan 7 2015 nightly.

Tested the PCSX ReARMed and SNES9x Next cores.

(This is more of a problem for people who can't edit the history file to remove dead items.)

**Comment by micechal** [comment]
Happens here too. I think this could be solved if we had a way of removing particular history items from rgui. Maybe the start button could do, as it's already used to reset settings to their defaults? No idea if that makes much sense.

**Comment by twinaphex** [comment]
This can be closed now.
