### ISSUE TITLE
"Bad executable" error on iPadOS 15

### ISSUE THREAD

**Issue by frarees** [libretro/RetroArch#13304]
## Description

.ipa file doesn't launch.

### Expected behavior

Launch RetroArch.

### Actual behavior

Crash:

```
Launch failed with Error Domain=NSPOSIXErrorDomain Code=85 "Bad executable (or shared library)" UserInfo={NSLocalizedDescription=Launchd job spawn failed}
```

```
Bootstrapping failed for <FBApplicationProcess: 0x1027aac80; application<com.libretro.dist.ios.RetroArch>:<invalid>> with error: <NSError: 0x283ff5920; domain: RBSRequestErrorDomain; code: 5; reason: "Launch failed."> {
    NSUnderlyingError = <NSError: 0x283ff56e0; domain: NSPOSIXErrorDomain; code: 85>;
}
```

### Steps to reproduce the bug

1. Copy to device via Impactor ([steps](https://docs.libretro.com/guides/install-ios/)).

### Version/Commit

- RetroArch: [Dec 1st nightly](https://buildbot.libretro.com/nightly/apple/ios-arm64/2021-12-01_RetroArch.ipa)

### Environment information

- OS: iPadOS 15.1

**Comment by miwagner1** [comment]
Unfortunately it looks like the instructions needs to be update as Cydia Impactor no longer works with Apple’s code signing changes. Use Sideloadly.

**Comment by frarees** [comment]
Confirming it works using Sideloadly and AltStore. Thanks!
