### ISSUE TITLE
[Feature Request] System-Exclusive Filter/Custom Lists from Filters

### ISSUE THREAD

**Issue by chinagreenelvis** [libretro/RetroArch#13311]
This is probably out of the hands of Libreto, but I'm surprised at the lack of metadata for different ROM sets. Some don't seem to have any data at all (NES) while the others are wildly inconsistent.

Who maintains these tags, is there an ongoing effort, and is there any way to help or volunteer?

**Comment by chinagreenelvis** [comment]
Also: a region filter.

**Comment by i30817** [comment]
https://github.com/libretro/libretro-database
