### ISSUE TITLE
[Windows] Undesired input autoconfig hot-swapping using 2 x360 controllers on one receiver 

### ISSUE THREAD

**Issue by nosh01** [libretro/RetroArch#1332]
2 x360 controllers connected to one receiver = 1 device id. Starting out the x360 controllers are assigned to player 1 and player 2. Then I turn off both controllers and plugin a separate generic dinput controller. I am seeing the dinput controller getting assigned to player 1 and player 2 because the controllers index is 0. What i would like to see is that the dinput controller gets assigned to player 1 only and player 2 becomes unassigned.

Seeing this on yesterdays nightly.

**Comment by fr500** [comment]
Please test on the current code, and reopen if the issue persists
