### ISSUE TITLE
Picodrive Core on Steam is not marked as Linux-supported

### ISSUE THREAD

**Issue by MetalNeo** [libretro/RetroArch#13334]
## Description
Picodrive on Steam does not list itself as compatible with Linux.

### Expected behavior

Picodrive should indicate it is compatible with Linux.

### Actual behavior

Picodrive does not list itself as compatible with Linux. The core can be selected and installed/used on Linux though.

### Steps to reproduce the bug

1. Open link: https://store.steampowered.com/app/1227460/RetroArch__Picodrive/
2. View System Requirements.

### Bisect Results

I believe this has been the case since the core's launch on Steam.

### Environment information

- OS: Linux

**Comment by LibretroAdmin** [comment]
Should be taken care of now.
