### ISSUE TITLE
[Android]Bug: Android GUI "Enable custom path" setting not being passed to RGUI

### ISSUE THREAD

**Issue by Raijinili** [libretro/RetroArch#1333]
If the checkmark is off, the game should save to the ROM folder, but instead it saves to the custom folder anyway.

Tested with Mednafen, PCSX. I'm pretty sure the Play Store version of Mednafen used the ROM's folder.

Nightly 07Jan2015. Lollipop.

**Comment by twinaphex** [comment]
This would no longer be considered safe on Android because of newer Android versions restrictions on writing to the SD card.

So a safer catch all solution is to default to custom directories and preferably inside the sandboxed app directory like how Google/Android prefers such files to be written.

Sorry about this but its simply a matter of an ever-increasingly less useful toy OS forcing our hand todo things in a certain way. If they kept things the way they were in KitKat you could still have this.

**Comment by Raijinili** [comment]
I don't understand. What isn't considered safe? There is a toggle for using a custom directory versus the ROM folder in the Android GUI and it seems to be ignored (uses custom anyway). Does the security of saves and states matter?

**Comment by twinaphex** [comment]
Re-read my post. This is Googles fault, not ours.

**Comment by Raijinili** [comment]
I not only reread your post, but tried to find out what changes have been
made, and what I found was
http://www.androidpolice.com/2014/11/04/android-5-0-makes-sd-cards-great-again-extends-api-to-allow-full-directory-access-automatic-mediastore-and-improves-security/

I still don't know what "This" refers to. What is the security restriction?
What is it forcing, that the option is useless or that the folders aren't
forwarded? Either way, is it not a bug to display ignored settings?

**Comment by twinaphex** [comment]
Now go find me something that works for the NDK. There is almost zero stuff that we do in Java.

**Comment by Raijinili** [comment]
Just so we're clear.

The option says that if disabled, saves and savestate are in the ROM folder: http://m.imgur.com/kFSbvmw

The option (apparently) works in the Play Store version, and not the nightly that I tried.

I am complaining about an option that doesn't do what it says it will. Did you mean to reply to #1328?

**Comment by twinaphex** [comment]
It no longer 'works' because of Google's security restrictions that they implemented on being able to read/write to SD cards. I dont want to play Russian roulette with users and hear a lot of complaints about 'my saves dont save, yadda yadda' so instead sandboxed app dirs for savestates and saveram seem most sensible.

If you know of a better solution then start sending out those PRs really. There is almost zero contributions going on for the Android port when plenty of people could be helping out dev wise if they werent too busy counting their pocket change ad money.

**Comment by twinaphex** [comment]
If you are a developer then come up with a fix that scales from Android 2.3 up to 5.0. 

That's about all I will say on this matter.

Until then forcing save state/save ram to the sandboxed app dir seems most logical to me.

**Comment by Raijinili** [comment]
I am not complaining about the lack of a feature to set paths here. I am complaining about the text being inconsistent with the function (that is, it says that the option will do something it doesn't). This is a bug.

I would be satisfied with a runtime check to make it only display the options if they will actually be used, if the option DOES still work on earlier versions of Android.

**Comment by Raijinili** [comment]
Also, to be clear, there are two related options:
- Toggle:
--- Use ROM folder
--- Use custom folder.
- Set custom folder.

The second one works as expected. The first one is ignored and treated as Use Custom Folder; it does NOT force saves to go into the app folder, but the set custom folder, so I am confused by your comment.

**Comment by Raijinili** [comment]
Also, are you saying that the checkmark CAN'T be respected or that, if it is, then Google will start yelling? For the first, the Play Store version DOES respect the option (just tested on the same device: the RGUI reports that the save dir is "<ROM dir>"), so this is a change from the current Play version.

Issue #1328 is my request for changing the default directories to something other than the app dir. Are you sure you're not confusing this issue with that?

**Comment by fr500** [comment]
Sorry but toggle mapping to rom folder doesn't make any sense either. It's not self explanatory, and actually saving to the ROM folder isn't an option if your roms are on an external SD card and not rooted on 4.4 and up. So it's not a sane default behavior.

**Comment by Raijinili** [comment]
What? The option is already in place and displayed in the Play version and the nightly. It is ignored in the nightly, but works in the Play version. I am asking for the old functionality to be put back OR for the option not to be displayed.

I am simply asking that the app doesn't explicitly say it will do something and then not do it, whether by making it do it or making it stop saying it. I can't see how the current behavior isn't obviously a bug.

**Comment by Qard** [comment]
Unfortunately, the app itself doesn't seem to have permission to write to /data/data/com.retroarch. I just get write failed errors from everything. :(

**Comment by Raijinili** [comment]
Doing what? I have not experienced behavior consistent with that, except when I manually copied files around (because they would be made with me as owner).

I think they agreed that the folders will eventually be in external storage by default.
