### ISSUE TITLE
Linux Steam Version of Retroarch still shows Show Legacy 'Thumbnails Updater' in Menu Item Visibility Settings even though online updater is depreciated

### ISSUE THREAD

**Issue by kbdharun** [libretro/RetroArch#13336]
## Description
When going to Menu Item Visibility Settings there is still an option to **Show Legacy 'Thumbnails Updater'** even when the online updater is removed in Steam Version. But enabling the option does nothing to the menu.

![Screenshot from 2021-12-07 19-36-22](https://user-images.githubusercontent.com/26346867/145046532-690c9ff5-0dfc-424e-a4d6-32581e59eae0.png)

### Actual behavior

It isn't displayed in Menu 

### Steps to reproduce the bug

1. Go to **Settings**
2. Go to **User Interface**
3. Click on "**Menu Item Visibility**"
4. Click on Show Legacy 'Thumbnails Updater'

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.14
- Build Date: Dec 6 2021
- Git Version: 06a2367008

### Environment information

- OS: Ubuntu 20.04
- Compiler: GCC (8.3.0) 64-bit
- Installed through Steam

**Comment by LibretroAdmin** [comment]
Should be resolved now.
