### ISSUE TITLE
[Android TV] Cannot install on Sony KD-43X80J

### ISSUE THREAD

**Issue by ChiFungLam** [libretro/RetroArch#13344]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Cannot install v 1.9.14 onto Sony Smart TV, I tried RetroArch / RetroArch plus (thru Play Store) and failed. I also tried download retroarch.apk, retroarch_ra32.apk from web and install but also failed. Failed happen at near end of installation i.e. near 100%. My TV has 400MB space left.

### Expected behavior
The app can be installed

### Actual behavior
Installation failed for app from Play Store and apk download from retroarch.com
<img width="791" alt="sony2" src="https://user-images.githubusercontent.com/84639815/145389106-f6b8fb1d-daca-4003-ba45-957494c9cd06.png">

### Steps to reproduce the bug

1. Go to Play Store app on Sony KD-43X80J
2. Search RetroArch/RetroArch Plus
3. Select install to install the app 

### Bisect Results

This issue happen on 1.9.14 version from Play Store and file download from retroarch.com (retroarch.apk and retroarch_ra32.apk)3

### Version/Commit

- RetroArch: [1.9.14]

### Environment information

- Android 10, kernel 4.19.75, Sony KD43X80J
<img width="791" alt="sony1" src="https://user-images.githubusercontent.com/84639815/145389042-94528a68-c03c-4a0e-addd-c08256926667.png">

**Comment by RobLoach** [comment]
I was able to install on my Bravia VH2 XR X90J without issue. Did find I needed a lot of space for it though. Try using an SD card? Any way to get the logs?

**Comment by RobLoach** [comment]
For me, "RetroArch" is taking up 895MB. "RetroArch Plus" takes up much more since it has more cores.

**Comment by ChiFungLam** [comment]
> For me, "RetroArch" is taking up 895MB. "RetroArch Plus" takes up much more since it has more cores.

Oh... its quite difficult to reserve so much space from the TV.

**Comment by RobLoach** [comment]
You may be able to install on an SD card using an APK installer or something similar.

**Comment by ChiFungLam** [comment]
> You may be able to install on an SD card using an APK installer or something similar.

Eventually I can install it.
1) need reserve 1.x gb in your tv
2) download retroarch.apk from retroarch.com to install (instead of from play store)
<img width="791" alt="ra2" src="https://user-images.githubusercontent.com/84639815/145678802-c2c9760f-d65f-4300-b20d-a96505c39148.png">
<img width="791" alt="ra1" src="https://user-images.githubusercontent.com/84639815/145678806-796dfa78-0f08-4c16-ace0-a3640c896194.png">

**Comment by RobLoach** [comment]
@ChiFungLam Does the remote work? I added the remote I have, but could do with some testing on the input. If there is a new remote you'd like added, feel free to upload the config.

**Comment by ChiFungLam** [comment]
I didn't do any configuration for the remote, but the left, right, up, down, ok, back, guide buttons are worked. But i still get a gamepad to work with RetroArch.

**Comment by RobLoach** [comment]
Good to hear! Glad it works.
