### ISSUE TITLE
latest git broke support for joypad in fba

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#1334]
This is probably more of a fba issue but i'll mention it here too : 
When i use latest git for retroarch and fba-libretro, input_b_btn trigger a soft reset on every games. Issue does not appear on older version of retroarcn (1.0.0.3-beta) or other cores with latest retroarch.

**Comment by Kivutar** [comment]
I confirm I was able to reproduce this bug

**Comment by Kivutar** [comment]
Ok, I bisected FBA without success, the problem was in RA, since commit https://github.com/libretro/RetroArch/commit/6fb51eb360f4f6566548b8db381d2ccf2d98251e

**Comment by twinaphex** [comment]
Test if this fixes it.

https://github.com/libretro/RetroArch/commit/f87590b355e6a3384995cd0a7314071b10384d22

**Comment by barbudreadmon** [comment]
It fixed it.
