### ISSUE TITLE
Enable networking for OpenDingux

### ISSUE THREAD

**Issue by Shatur** [libretro/RetroArch#13345]
## Description

Networking is currently disabled in official builds for OpenDingux.

### Expected behavior

I would expect to have networking enabled for these devices. Because they can use [Wi-Fi dongles](https://github.com/eduardofilo/RG350_adam_image/wiki/En:-7.-FAQ#q9-is-it-possible-to-use-a-wifi-dongle).

### Actual behavior

Networking is disabled in official builds: `NetPlay (Peer-to-Peer) Support: No` in system information.

### Steps to reproduce the bug

1. Download the official build.
2. Open System Information
3. Navigate to Netplay

### Version/Commit

- RetroArch: c19b04e

### Environment information

- OS: OpenDingux

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway Seems this one consistently pops up as a request. Again, I could provide the hardware if need be and if interested.

**Comment by LibretroAdmin** [comment]
There's sadly a lack of interest in this. Can anyone who does happen to have an interest in this do the deed?

**Comment by Shatur** [comment]
@LibretroAdmin what should I do to enable it?
Simply add `HAVE_NETWORKING=1` to https://github.com/libretro/RetroArch/blob/master/Makefile.rg350_odbeta ?
