### ISSUE TITLE
Games and Thumbnails names not always match

### ISSUE THREAD

**Issue by KrisEnigma** [libretro/RetroArch#13343]
I was updating my playlists on a new installation, and while every game was being found just fine, some thumbnails weren't.

For example, in my Sega 32X folder I had a game for which the thumbnail wasn't found, that's when I noticed that the names in the thumbnail database and the game database had a small difference.

Game name: ""FIFA Soccer 96 (Europe) (En,Fr,De,Es,It,Sv)"
Thumb name: "FIFA Soccer '96 (Europe) (En,Fr,De,Es,It,Sv)"

So, a single character was missing, and this was the cause of why the thumbnail updater wasn't finding the image.

Is there something we users can do to help find these inconsistencies?

Thanks.

RetroArch Build Date: Dec 9 2021, Windows x64

**Comment by RobLoach** [comment]
The thumbnails are managed over at https://github.com/libretro-thumbnails/ . Since No-Intro updates their naming regularily, it does take some work to keep them inline. Would love your help in noticing these and fixing them!

I recommend using [GitHub Desktop](https://desktop.github.com/) to make pushing up changes easier. For 32X the thumbs are over at https://github.com/libretro-thumbnails/Sega_-_32X

Thanks so much!

**Comment by KrisEnigma** [comment]
I'm not used to github at all! I'm just a regular gamer, haha. If you could tell me in more detail how to help, or maybe you have a discord or something, I will do the best I can.

Also, additional question: 

Also in the Sega 32X folder I have a game called "WWF WrestleMania - The Arcade Game (USA)", it gets the title, the screenshot, but not the box art, even if they all share the same name... I really don't know what is up with that.

**Comment by RobLoach** [comment]
No problem! Thanks for having a look.

1. Download [GitHub Desktop](https://desktop.github.com/)
2. Have it check out the Sega 32X thumbnails repository https://github.com/libretro-thumbnails/Sega_-_32X
3. Make updates to the files
4. Push up the changes to your own repository
5. Create a Pull Request... That's how to make the changes :wink:

> Also in the Sega 32X folder I have a game called "WWF WrestleMania - The Arcade Game (USA)", the thumbnail updater gets the title, the screenshot, but not the box art, even if they all share the same name

The box art is likely missing. For new thumbnails, it's possible to upload them directly through the web interface over at https://github.com/libretro-thumbnails/Sega_-_32X/tree/master/Named_Boxarts

**Comment by KrisEnigma** [comment]
I'll try that later, thanks! I'll be glad to help if I can.

About the question, the box art [is not missing](https://github.com/libretro-thumbnails/Sega_-_32X/blob/master/Named_Boxarts/WWF%20Wrestlemania%20-%20The%20Arcade%20Game%20(USA).png), that's why I found it very weird:

**Comment by RobLoach** [comment]
It's the case that didn't match 😉 ... I committed the fixes directly. Hopefully once the thumbnails server updates, it'll come through. Thanks a lot! https://github.com/libretro-thumbnails/Sega_-_32X
