### ISSUE TITLE
Can't import .chd on MacOS ARM.

### ISSUE THREAD

**Issue by Sidma64** [libretro/RetroArch#13342]
## Description

I can't import my .chd from "Import Content" on RetroArch. It scans it, but doesn't import it in the end. The file does work on my Windows PC, so I doubt it's the file.
### Expected behavior

"Dragon Quest IV - Michibikareshi Mono-tachi (Japan).chd" should have appeared after I scanned it with "Scan File" or "Scan Directory".

### Actual behavior

"Dragon Quest IV - Michibikareshi Mono-tachi (Japan).chd" doesn't appear after I scan it with "Scan File" or "Scan Directory".

### Version/Commit
- RetroArch: 1.9.13 / Metal

### Environment information

- OS: MacOS Monterey 12.0.1
- Device: Macbook Air M1

**Comment by RobLoach** [comment]
There's only limited support for serial scanning `.chd` files, so you'll want to use the Manual Scanner instead. This [serial scanner Pull Request](https://github.com/libretro/RetroArch/pull/11719) improves it, would love some of your testing over there: https://github.com/libretro/RetroArch/pull/11719
