### ISSUE TITLE
Friend and i both control 1st player? and her controller wont function in netplay.

### ISSUE THREAD

**Issue by OGDojo** [libretro/RetroArch#13355]
## Description

i boot up retroarch after deleting both the retroarch.cfg and the retroarch_default.cfg files to make sure everything is hunky dory with my settings and had my friend do so as well then we both jumped straight into Goof Troop on super nintendo (easy 2 player game) i have the Rom and she doesnt but it still lets her jump in and play (as it should) however it only lets her use her Keyboard and not her controller (i think she uses 8bitdo or xbox 360 controller) and no matter how many times i try to reset or reinstall it just seems to do this each time.

### Expected behavior

i expect that when i load into the game and invite my friend Via Steam to my game that it defaults her to 2nd player and allow her to use her own controller to play the game.

### Actual behavior

when loading into the game with me hosting the netplay i invite her to the game using steam and after picking the 2 player option in goof troop her and i both control goofy, neither player can control max, and she cant use her controller even tho it says on my end that her controller is plugged in and set to player 2.

### Steps to reproduce the bug

1. current build date (cuz i cant find the build number to save my life) is Dec 6 2021
2. loaded up retroarch through the steam library
3. clicked on host netplay so that i can invite her to a game
4. select start game, and select 2 player.
5. try using the controller on her end and nothing happens and when she moves using the keyboard it moves the 1st player character (Goofy) instead of the 2nd player character (Max)

### Bisect Results

Immediately after downloading it. like downloaded the emulator from steam then tried playing with my friend and it started happening on the first try and every consecutive try afterward

### Version/Commit

Build Date: Dec 6 2021
Git version: 06a2367008
Compiler: MinGW (10.2.0) 64-bit

### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW (10.2.0) 64-bit

**Comment by Cthulhu-throwaway** [comment]
@LibretroAdmin This issue is invalid. User is clearly running Parsec/Steam Remote Play Together, which is not part of RetroArch. 

Can be closed.
