### ISSUE TITLE
Loading or browsing 7z files freezes/crashes RetroArch Plus on Android TV

### ISSUE THREAD

**Issue by denilsonsa** [libretro/RetroArch#13372]
## Description

When trying to play a ROM that is compressed with 7z, RetroArch freezes for several seconds and eventually crashes. It works perfectly fine with zip files.

### Steps to reproduce the bug

1. Get [RetroArch Plus](https://play.google.com/store/apps/details?id=com.retroarch.aarch64) on Android TV.
    * I haven't tested if this behavior is reproducible on a mobile phone.
2. Get the zip file for "Sonic 1: Bouncy Edition".
3. Make a 7z version of the same game:

        unzip Sonic_1_-_Bouncy_Edition.zip
        
        # Note: this 7z command-line is based on the first example from "man 7z"
        7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on Sonic_1_-_Bouncy_Edition.7z s1bouncy.bin
        
        # These are the files:
        ls -sh
        512K s1bouncy.bin
        352K Sonic_1_-_Bouncy_Edition.7z
        372K Sonic_1_-_Bouncy_Edition.zip

4. Open RetroArch (Plus) on the Android TV.
5. Load Content
6. Select the `.zip` file.
7. Pick either *Browse archive* or *Load archive*
    * If picked *Browse*, observe how it instantaneously shows the archive contents.
8. Pick a core (in this case *Sega - MS/GG/MD/CD (Genesis Plus GX)*) 
9. Observe how it loads instantaneously and you can play it flawlessly.
10. Go back to the RetroArch main menu.
11. Load Content
12. Select the `.7z` file.
13. Pick either *Browse archive* or *Load archive*
14. BUG! RetroArch freezes for several seconds, and eventually the system goes back to the main Android TV homescreen.
15. At one time, after waiting for what felt like half minute, it progressed to display the list of cores. However, after picking up a core, it would freeze and crash as usual.

### Expected behavior

I expected it would work just fine, instantaneously, without freezing and without crashes. Just like how `.zip` works flawlessly.

### Actual behavior

7z files don't work.

If I were to guess, RetroArch must be trying to uncompress the 7z into memory, and then freezes or crashes or runs out of memory or something. But this is just a wild guess from my side.

### Bisect Results

Sorry, I didn't do the bisect, and frankly I don't have enough free time to do it. Again, sorry. I hope someone else can reproduce this bug and investigate.

### Version/Commit

You can find this information under Information/System Information

- RetroArch: 1.9.12 (from Google Play) *[Edit: as a mistake, I had originally typed 1.9.2, which is wrong.]*

### Environment information

- OS: Android TV
- System: [Nvidia Shield TV Pro (2019)](https://www.nvidia.com/en-us/shield/shield-tv-pro/) (NVIDIA® Tegra® X1+ processor with a 256-core GPU and 3 GB RAM)
- The game files are mounted through SMB shared folder, using Shield's built-in NAS mount features. (I believe this is not relevant to this issue, but I'm mentioning it anyway.)

**Comment by askotx** [comment]
Is that an unofficial build?

**Comment by denilsonsa** [comment]
That is an official build, it's [the new name of RetroArch64](https://www.libretro.com/index.php/retroarch-android-new-versions-for-play-store-please-read/), officially [published to the Google Play Store as `com.retroarch.aarch64`](https://play.google.com/store/apps/details?id=com.retroarch.aarch64) under the [Libretro developer](https://play.google.com/store/apps/developer?id=Libretro). Version 1.9.12 is from 2021-11-03, has 690MB of size, and supports 127 cores.

**Comment by denilsonsa** [comment]
I did a couple of tests:

* RetroArch 1.9.14 Steam version running on Windows 10 64-bit can open 7z files just fine.
* RetroArch 1.9.12 (both 32-bit and the 64-bit "Plus" versions) for Android, running on Android 9 phone, can open 7z files just fine.

This makes me think the issue could be restricted to the Android TV build.

(Or, very unlikely, a corner case when loading a 7z file via a mounted shared folder on Android. I can't test loading from the local filesystem on my Nvidia Shield TV for now, though.)

**Comment by RobLoach** [comment]
7zip is extremely slow, and judging by 20K file diff, I'd honestly recommend using .zip instead. You are right that it extracts all content when loading.
