### ISSUE TITLE
Cannot use Android native virtual keyboard in emulators like P-UAE

### ISSUE THREAD

**Issue by sprudel79** [libretro/RetroArch#13382]
Hello,
I am using Retroarch 1.9.12 on my Nvidia Shield Tablet with latest available cores installed like P-UAE.
In some situations I don't use any peripherals like an external keyboard and would like to play some games like text adventures directly on the tablet.
When starting a core like P-UAE and I use my tablet in portrait mode and I can see nicely the emulator part at the top and the virtual Gamepad/Joystick controls at the bottom of the screen.

My problem is that in order to enter keyboard commands I need to either plug-in an external keyboard via USB (or of course via bluetooth) or in case of P-UAE I can use the built-in virtual keyboard of the core but this keyboard is displayed as an overlay of the emulator itself (which is perfect in many situations) but I would like to show the standard Android virtual keyboard underneath the emulator view.

I suggest to add an additional button to the virtual Gamepad/Joystick controls like other emulators on Android are doing that would hide the virtual Gamepad/joystick controls and show the Android virtual keyboard instead (it doesn't need to be an emulator specific keyboard which would be of course absolutely awesome but.

Retroarch and the included cores are my preferred way of playing emulated retro games and the only thing that's bringing me back to alternative emulators (on Android e.g. C64.emu) is this keyboard relative topic.
Thank you so much for all the efforts spent in this and thanks in advance to look into my request.

**Comment by hizzlekizzle** [comment]
Unfortunately, the native Android keyboard isn't accessible at all in RetroArch because it is tied to Android's native GUI toolkit libraries, which RetroArch does not use.

**Comment by sprudel79** [comment]
Ok, thank you very much @hizzlekizzle for your reply.
