### ISSUE TITLE
Cannot bind all joystick keys

### ISSUE THREAD

**Issue by neagix** [libretro/RetroArch#1338]
Current master (6374422d1f540d39f2c4acf57b438d8d5e4d4823 when I tested) has broken support of gamepads (Xbox). Some button/axis cannot be mapped, Y for example; it can be checked with retroarch-joyconfig too.

I am using linuxraw/udev on Linux.

I did not completely bisect this issue, but found it works fine on 544f1ba41ed23e2d001d3aeeeb84b7a937de0033

**Comment by twinaphex** [comment]
That commit you showed cant possibly be the cause. Thats the PS3 input driver.

**Comment by neagix** [comment]
Sure, I am saying that it must be between 544f1ba (known good) and 6374422 (known bad) but I have not bisected yet to precisely which one

**Comment by twinaphex** [comment]
Can you do a git bisect then?
