### ISSUE TITLE
build-for-ios error

### ISSUE THREAD

**Issue by xurayg** [libretro/RetroArch#1340]
When I run ./libretro-build-ios.sh . There is an error : 
Undefined symbols for architecture armv7:
  "_audio_convert_float_s16_asm", referenced from:
 _audio_convert_float_to_s16_neon in utils.o
"_audio_convert_s16_float_asm", referenced from:
  _audio_convert_s16_to_float_neon in utils.o
ld: symbol(s) not found for architecture armv7

Anyone can help? thanks very much.

**Comment by xurayg** [comment]
make: *** [mupen64plus_libertro_ios.dylib] Error 1
failed to build Mupen 64 (ARM dynarec)
cp:mupen64plus_libretro_ios.dylib: No such file or directory

**Comment by caiozullo** [comment]
same here
