### ISSUE TITLE
PS Vita nightly builds from buildbot crash at startup on any core

### ISSUE THREAD

**Issue by DerinQyu** [libretro/RetroArch#13403]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Hello, latest nightly builds for the ps vita crash when you try to open retroarch and send the user to the live area. This happens on both the standard and piglet builds, this is happening since the 2021-12-15-retroarch from buildbot.

Founded that latest working commit is 98431a1. Did the testing on aclean install each time

### Expected behavior

Retroarch should open and not crash

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. Do a clean install of either the normal or piglet vpk and the data .zip
2. After install try to open retroarch
3. stuff crashes

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.9.14/anything after 98431a1]

### Environment information

- OS: [PS Vita Slim 3.60 enso]

**Comment by DerinQyu** [comment]
update: retroarch still crashes at boot on latest nightly

**Comment by 16mpx** [comment]
This is a serious issue and still not solved and all the cores in the latest nightlies crashes the Retroarch. 

Something related with the buildbot can be broken.

**Comment by DerinQyu** [comment]
Update: teste today the 2022-01-19_RetroArch_piglet.vpk and this issue is finally fixed, cores load again and I was able to play super mario bros on fceumm.

Only two bugs to report 1. gpsp core is missing 2. PCSX-rearmed chrashes when loading a game. I'll report those issues on their repos and close this issue now
