### ISSUE TITLE
Nestopia UE core automatically not change disk side from B to A.

### ISSUE THREAD

**Issue by Augusto7743** [libretro/RetroArch#13405]
I have played a game (Green Beret) and in begin is displayed message to change disk side to B being automatically changed to side B thus the game start, but after some stages the game need change to side A.
Is displayed message to change to side A, but the emulation core not change the disk side.

**Comment by RobLoach** [comment]
Mind creating an issue in the Nestopia core issue queue?

**Comment by Augusto7743** [comment]
Correct ... closing.
