### ISSUE TITLE
[Xbox/UWP] Cheevos Not Working With CHD Games

### ISSUE THREAD

**Issue by TheRhysWyrill** [libretro/RetroArch#13430]
## Description

When launching any games that have an achievement list, RetroArch will fail to fetch/log in to RetroAchievements if the disc image is CHD.

### Expected behavior

For the game to boot and the achievements list to populate/function as normal.

### Actual behavior

Launching any CHD game (Breath of Fire III for example) with any PS1 core results in the achievement list not being displayed even though I've confirmed this game populates an achievement list (as CHD) on the PC version of RetroArch, might be a UWP exclusive issue.

### Steps to reproduce the bug

1. Ensure you have a RetroAchievements account linked to your RetroArch. 
2. Launch any CHD compressed game that supports achievements. 
3. Check the Achievements tabs where RetroArch will either display a "No Achievements To Display" or "Not Logged In" message.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Xbox/UWP, Version: 1.9.14

### Environment information

- OS: Xbox Series X, OS Version: 10.0.22000.3055

**Comment by Jamiras** [comment]
Probably the same issue as #10841.

The RetroAchievements identification code requires the HAVE_CHD build flag for RetroArch. It's independent of whether or not the core supports CHD.

**Comment by TheRhysWyrill** [comment]
Apologies for creating a duplicate issue.

Explains why the cores all support achievements when the games aren't compressed, is that build flag not currently available for the Xbox/UWP version of RetroArch or something?

As the achievements are working just fine with CHD on PC and I didn't think the PC version was that different/far ahead from the Xbox/UWP version.

**Comment by TheRhysWyrill** [comment]
Recently built RetroArch UWP while including the HAVE_CHD build flag, doesn't seem to have had any effect unfortunately, still getting the same "Not logged in" message as before, there must be something more that needs doing than just adding HAVE_CHD to the list of Definitions.

**Comment by Jamiras** [comment]
Can you capture a log file? It would indicate whether the problem is with the login, the has generation, or the hash resolution.

**Comment by TheRhysWyrill** [comment]
Here is the log file, it seems that hashes aren't being generated, the Cheevo errors (Start on line 524) are identical between the Xbox and PC UWP versions.

[retroarch.log](https://github.com/libretro/RetroArch/files/7833388/retroarch.log)

**Comment by Jamiras** [comment]
```
[INFO] [RCHEEVOS]: Load started, hardcore not active
[INFO] [RCHEEVOS]: Using host: http://retroachievements.org
[INFO] [RCHEEVOS]: Found 7 potential consoles for chd file extension
[INFO] [RCHEEVOS]: Trying console 12
[INFO] [RCHEEVOS]: no hook registered for cdreader_absolute_sector_to_track_sector
[INFO] [RCHEEVOS]: no hook registered for cdreader_absolute_sector_to_track_sector
[INFO] [RCHEEVOS]: Could not locate primary executable
```
Playstation is console 12. Absolute sector addresses are not required for Playstation, so those hook warnings can be ignored.

It's behaving like HAVE_CHD is not defined. The hashing code will call into `cdfs_open_track`, which has an `#ifdef HAVE_CHD` for handling the CHD format. If CHD is not handled, it just opens the file as raw data, and the hasher will not be able to locate the primary executable.

**Comment by Jamiras** [comment]
The "Not logged in" message is a side effect. 
```
[INFO] [RCHEEVOS]: no hashes generated
```
If  a hash cannot be generated for the content, we don't bother logging the user in. I'll make changes to force it to "Unknown Game" instead.

**Comment by TheRhysWyrill** [comment]
So based on your explanation it's acting as if `HAVE_CHD` wasn't defined to begin with, I'm not massively experienced with this so how would one go about debugging/testing the issue or would it be a rather complex task?

Thank you for your time.

**Comment by Jamiras** [comment]
The first step would be to verify that HAVE_CHD is actually defined. You can try the code I added in #13463.

The next thing I would suggest is stepping through the code in `cdfs_open_track` to make sure it's actually recognizing and opening the CHD. If attaching a debugger is not possible, you could use log messages to trace the flow.

The last thing would be to step through `rc_cd_find_file_sector` to make sure it's able to locate the directory record for the disc. tmp[33] should be an ASCII-readable filename for each iteration of the loop.

**Comment by TheRhysWyrill** [comment]
Using the code you added in #13463 I was able to confirm that `HAVE_CHD` is correctly being defined as there is no error being generated in the log.

From stepping through `cdfs_open_track` I believe it's correctly recognizing and opening the CHD, the value of `ext` when opening the CHD however only displays as `hd`, no idea if that's normal behavior or not.

Stepping through `rc_cd_find_file_sector` is where I'm most confused, seems that no matter what I do tmp[33] always displays as `0'\0'`, whether this is actually the issue or just a result of me doing something wrong I couldn't say.

**Comment by Jamiras** [comment]
> From stepping through cdfs_open_track I believe it's correctly recognizing and opening the CHD, the value of ext when opening the CHD however only displays as hd, no idea if that's normal behavior or not.

This seems contradictory to itself. If `ext` is "hd", it should not step into `cdfs_open_chd_track` - it would fall down to `cdfs_open_raw_track`, and that would explain the behavior.

If it is going in to `cdfs_open_chd_track`, then I'm not sure how to further guide you. `rc_cd_read_sector` should eventually call into `chdstream_read`, which will populate the buffer with the decompressed sector data. Assuming that's occurring, it becomes an issue where you'd need to compare the behavior in a working environment against the behavior in the non-working environment and determine what's different. I'm sorry I can't be any more help.

**Comment by TheRhysWyrill** [comment]
Interesting, at the very least it's a lead to look into, no need to apologize, you were a huge help, hopefully someone more experienced than I will be able to use the information you've put forward and hopefully get to the bottom of this issue!

Thanks again.
