### ISSUE TITLE
Implement short relative path for core location parameter on Linux

### ISSUE THREAD

**Issue by sgmihai** [libretro/RetroArch#13442]
On windows you can do `retroarch.exe -L cores\bsnes_libretro.dll game.rom`
On linux you have to use a much longer path if you use the appimage retroarch, something like
`-L RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/cores/pcsx2_libretro.so`

It would be nice, since retroarch already knows where its cores are kept, to be able to specify them without any paths, just using the filename, or even better, just the generic core name, like "pcsx2_libretro".
And still be able to use external cores outside its cores folder if specifying a full path, of course.

It would be cleaner and simplify thing for anyone making script to launch games from the terminal, 3d party apps, etc.

@Sanaki we talked about this on discord.

**Comment by Sanaki** [comment]
Not quite an accurate summary, but after some discussion, I believe the correct implementation here (if viable) would be to attempt loading the file from the specified path first, then on failure, attempt looking in the `libretro_directory` path for the specified file. If desirable, the second part could be skipped if the string contains path delimiters, but it seems harmless to just attempt the second open.

While I wouldn't say it'd be a heavily used feature, it -would- be extremely beneficial for niche use cases and would greatly simplify some debugging instructions from those of us helping on the tech support side.

**Comment by i30817** [comment]
It's not harmless to not test against 'the user thinks this is a path' because it masks user errors.

**Comment by jdgleaver** [comment]
I liked this idea, so I implemented it here:  #13454
