### ISSUE TITLE
video_font_enable=false breaks glui

### ISSUE THREAD

**Issue by Royerson** [libretro/RetroArch#1345]
Setting video_font_enable to false makes no text at all appear in glui.

Ideally, setting it to false would prevent text from being displayed only when not in the menu, or only prevent messages that aren't part of the menu.

**Comment by twinaphex** [comment]
Yeah well, GLUI depends on fonts being enabled in order to work at all since it uses the font subsystem.

I think it'd be very hacky to forcibly turn it on in the display drivers' init function at least.

**Comment by Royerson** [comment]
You could separate the way OSD stuff and glui stuff is called so you could just skip one or the other instead of actually turning off fonts completely.

That would probably be a lot of work though for what is a pretty minor annoyance.

**Comment by twinaphex** [comment]
Should be fixed by now. If there is still an issue, please reopen.
