### ISSUE TITLE
[Feature request] add the ability to easily search & install the platform support

### ISSUE THREAD

**Issue by mikebdp2** [libretro/RetroArch#13458]
Currently it's not obvious how to install even a single platform there...

**Comment by hizzlekizzle** [comment]
I don't understand the request.

**Comment by i30817** [comment]
I guess he's got a unusual platform and doesn't know how to compile or find a compiled executable? I guess he just wants a 'pointer' in the documentation.

**Comment by mikebdp2** [comment]
@hizzlekizzle @i30817 it would be nice if in Retroarch there would be some GUI platform installer, which at least supports getting the more popular platforms in a user-friendly way by a few clicks
