### ISSUE TITLE
Function of left and right d-pad buttons unexpected when browsing playlists in ozone

### ISSUE THREAD

**Issue by jvook** [libretro/RetroArch#13466]
[Description of the bug]
Most menus use left/right to scroll multiple pages, but when using ozone driver, left on d-pad simply backs out of the playlist and right does nothing.

### Expected behavior
Most menus, such as Load Content, use left/right to scroll up or down by a page.  In playlists, left backs out and right does nothing. Scrolling up and down should be given priority over backing out of the playlist because we already have a button to back out of playlists.  

Pressing left/right in RGUI behaves as expected and scrolls multiple items and it would be probably be better if ozone was consistent with RGUI on this point.

You can use L1&R1 to scroll by letter, but it is not precise enough for playlists with many items, like MAME. Additionally when using a real NES controller, for example, there is no way to scroll by multiple items at all. I would assume some arcade setups might have difficulty as well.

[What should happen]
Pressing left and right on d-pad in playlists should scroll by a page in ozone.

[Possible solutions]
*Change the behavior of left and right d-pad to function as page scrollers in ozone.
*Ideally, whether left and right scrolls by page or by letter should be a setting.
*Ideally, whether page up (L1 button) and page down (R1 button) scrolls by page or by letter should be a setting.  This setting would improve the functionality of scrolling in XMB as well as RGUI and ozone.
*These can actually be the same setting: "L1/R1 scrolls by letter or by page --- By Page/By letter" and set left and right to the opposite.

**Comment by i30817** [comment]
The cancel button is overloaded in ozone to also apply to keyboard filter/search cancellation. If ozone took your advice there wouldn't be any way to get out of a playlist and get back with the filters active, which you sometimes want when you're searching for series and the associated metadata is broken, missing or not active because you used the manual scan or it's a translation.

**Comment by jvook** [comment]
I hear you but I have to use rgui on an 85" TV because I can't scroll playlists in ozone
