### ISSUE TITLE
Expected crash OnSuspending state on UWP

### ISSUE THREAD

**Issue by basharast** [libretro/RetroArch#13491]
Hi, I noticed that there might be a minor issue in case the app suspended in the background or during save state on exit.

## Exception:

Windows.Graphics.Display: GetForCurrentView must be called on a thread that is associated with a CoreWindow

## Event: 

`void App::OnSuspending(Platform::Object^ sender, SuspendingEventArgs^ args)`

## Cases:

it will **crash** in these cases:

- Whenever the app _suspended_ in the background
- When app **closed**

## Possible Reproduce

1. Run the app within Visual Studio
2. Close it
3. Exception should be thrown

Or try to send the app to background while browsing folders..etc

## Stack:

1. `App::OnSuspending` _(uwp_main.cpp)_
2. `bool config_save_file` _(configuration.c)_
3. `uint_settings   = populate_settings_uint  (settings, &uint_settings_size)`  _(configuration.c)_
4. `struct config_uint_setting *populate_settings_uint`  _(configuration.c)_  <- issue here

As expected the exception happens with [uwp_get_width](https://github.com/libretro/RetroArch/blob/6d6eca7a9f72718c9ae9bb23014dc5c0f8c5d308/uwp/uwp_main.cpp#L788) and [uwp_get_height](https://github.com/libretro/RetroArch/blob/6d6eca7a9f72718c9ae9bb23014dc5c0f8c5d308/uwp/uwp_main.cpp#L775)   _(uwp_main.cpp)_

_configuration.c_ ([Line](https://github.com/libretro/RetroArch/blob/6d6eca7a9f72718c9ae9bb23014dc5c0f8c5d308/configuration.c#L2133)):

```
SETTING_UINT("video_fullscreen_x", &settings->uints.video_fullscreen_x, true, uwp_get_width(), false); //<- will crash here
SETTING_UINT("video_fullscreen_y", &settings->uints.video_fullscreen_y, true, uwp_get_height(), false);
```

## Possible Solutions:
1. Perform `uwp_get_width` and `uwp_get_height`  at UI thread (Prefered).

OR

2. Run the code in `App::OnSuspending` at **UI Thread**  `async` instead of `create_task`:

```
Windows::ApplicationModel::Core::CoreApplication::MainView - > CoreWindow - > Dispatcher - > RunAsync(
  CoreDispatcherPriority::Normal,
  ref new Windows::UI::Core::DispatchedHandler([this, deferral]() {
    settings_t * settings = config_get_ptr();
    bool config_save_on_exit = settings - > bools.config_save_on_exit;

    if (config_save_on_exit) {
      if (!path_is_empty(RARCH_PATH_CONFIG)) {
        const char * config_path = path_get(RARCH_PATH_CONFIG);
        bool path_exists = !string_is_empty(config_path);

        if (path_exists) {
          if (config_save_file(config_path)) {
            RARCH_LOG("[config] %s \"%s\".\n",
              msg_hash_to_str(MSG_SAVED_NEW_CONFIG_TO),
              config_path);
          } else {
            RARCH_ERR("[config] %s \"%s\".\n",
              msg_hash_to_str(MSG_FAILED_SAVING_CONFIG_TO),
              config_path);
          }
        }

      }
    }
    deferral - > Complete();
  }));
```

Thanks.

**Comment by LibretroAdmin** [comment]
Hi @basharast , can you test if this is an actual issue, and if so, correct the behavior and send a PR? Thanks.

**Comment by basharast** [comment]
Thanks for your reply @LibretroAdmin , yes it's actual issue and still exists in the latest release
I just submitted request with the suggested changes #14372 

https://user-images.githubusercontent.com/3244951/188014820-4da8255a-0c26-4304-a697-a12e95322c93.mp4
