### ISSUE TITLE
[CRT SwitchRes][1.9.14] Closing Flycast content gets RetroArch "stuck" in interlaced mode (regression)

### ISSUE THREAD

**Issue by Kopert** [libretro/RetroArch#13495]
## Description

When closing content loaded with the Flycast core (interlaced on a 15khz screen), CRT SwitchRes refuses to switch back to progressive. If "Use high resolution menu" is disabled, the menu gets squished vertically after closing the content. Trying to load a NES game does not switch to progressive and it runs in interlaced.

The issue did not happen when running other interlaced content such as Gamecube games with the Dolphin core. The problem happens both with GL or Vulkan backends. The issue is not present on 1.9.13.2.

### Expected behavior

The expected behavior is the one presented on v1.9.13.2: once the content is closed, the menu reverts to progressive (if "use high resolution menu" is disabled); running 240p content (such as a NES game) results in the screen being in progressive as well.

### Actual behavior

After closing the content, the screen remains interlaced, the menu gets squished vertically and starting a NES game has it running in interlaced instead of progressive.

### Steps to reproduce the bug

1. Be running RetroArch on tag v1.9.14
2. Make sure `Settings -> Video -> CRT SwitchRes -> CRT SwitchRes` is enabled and set to 15 KHz (or INI with 15 KHz settings)
3. Make sure `Settings -> Video -> CRT SwitchRes -> Use high resolution menu` is disabled (to make the issue more apparent)
4. Run content with the Flycast core
5. While the content is running, open the menu and select `Close Content`
6. **Note that the menu is interlaced, instead of reverting to progressive, and is filling only half the height of the screen**
7. Run NES content
8. **Note that the NES content is running in interlaced instead of progressive**

### Bisect Results

The issue does NOT happen on tag **v1.9.13.2**. The issue DOES happen on tag **v1.9.14**.

### Version/Commit
- RetroArch: Version: `1.9.14`, Git Version: `06a2367008`.

### Environment information

Linux under an X environment.

**Comment by Kopert** [comment]
Additional info: if I compile it myself, the issue does not happen. I think this might be a problem with Arch package for RetroArch (1.9.14-2). [I have opened an issue on their bug tracker](https://bugs.archlinux.org/task/73367) and will report back if I learn anything new.

**Comment by LibretroAdmin** [comment]
@alphanu1 is this issue still happening you think or has it been resolved? What about the OP?

**Comment by Kopert** [comment]
I no longer rely on Arch's package for RetroArch, so I can't say if they have fixed the issue on their build. They have not replied to my issue on their tracker.

I have updated my RetroArch build to 1.10.3 and the Flycast core to its most recent version to check again and the bug does not occur on my build.

At this point I'd consider the problem - if it still exists, unfortunately I can't tell - to be with Arch's package and not with RetroArch or SwitchRes.  This issue can be closed if everyone else also agrees.

**Comment by alphanu1** [comment]
Agreed, I do not believe this is RetroArch. Core or SwitchRes related. I have not be able to reproduce this myself either.

@LibretroAdmin please
Close this off
