### ISSUE TITLE
RFE: Fuzzy title boxart matching a bit with a extra utf character.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#13496]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When retroarch searches for thumbnails it tries to match the filename to the remote server. However it must 'remove' forbidden characters, and you decided to make it 'crossplatform' by removing all the characters in the thumbnail server of that conflict with windows filename rules (or almost all anyway, special character devices are not considered).

This is good for linux, since linux has many many less forbidden characters in filenames. In fact there are only two. The ascii forward slash '/' and the null character '\\x00' (or however it's written). Then, in linux you can have forbidden characters like ':' in playlists files and it works fine. When searching for a thumbnail RA notices there is a 'illegal character' and replaces it by '_', like the rules of the thumbnail database say.

I'd like a enhancement for this where IF the user replaced the ascii forward slash on a launcher file by the utf8 version aka (u"\u2215") which retroarch and the shell shows as a 'forward slash' but isn't that this process of matching to the thumbnail database replaces it by _ too. Since it's a utf8 character it may require another function call in c (in python it's all strings so i'm not sure).

### Expected behavior

That's it, just the fuzzy search of thumbnails accepting u"\u2215" as if it was '_' for the purpose of matching.

### Actual behavior

It prevents matches and 'forces' me to rename launcher files that would have naturally '/' on it by the uglier '_' (i noticed this on a script that i just made to turn scummvm.ini entries into .scummvm files in the games directory to save a lot of time and pain when scanning scummvm). I used the 'description' field as the filename of the .scummvm file and in between replacing illegal characters to windows and linux noticed that linux could 'almost' have the name unaltered and wanted to use this utf character, which breaks the thumbnail matching (not that the majority of thumbnails have names that match this scheme, but at least some do).

**Comment by i30817** [comment]
As a aside, although i only mentioned the utf-8 forward slash because that's 'all' that unix/posix needs, some windows forbidden characters probably have utf-8 replacements that work in filenames like ', \ & / etc. So if this get added for forward slash, why not the others?

**Comment by RobLoach** [comment]
All filename titles are expected to use `_` instead of other characters, rename them yourself, or create a symlink. You will find documentation on this over at https://github.com/libretro-thumbnails/libretro-thumbnails#usage .

**Comment by i30817** [comment]
> All thumbnails are expected to use `_` instead of other characters, rename them yourself, or create a symlink. You will find documentation on this over at https://github.com/libretro-thumbnails/libretro-thumbnails#usage .

You missed the point. Retroarch is the one doing the renaming - i can easily make something that replaces / by _ (that's what the script is doing) but i'd like to have my cake and eat it, and it would be easy if retroarch replace the utf8 character sequence that is utf-8 '/' (which is _not_ ascii '/'  and thus isn't a 'illegal filename' anywhere) by '_'.


Same thing for the other (windows) forbidden characters, they have utf8 equivalents i gather.

**Comment by i30817** [comment]
I've been testing this with windows glyphs and it's more annoying. While with linux you can get away with replacing a single character '/' in windows there are a lot of them and they have 'subtle differences' in most fonts and retroarch's menu font doesn't encode many of them. Annoying.

I could ask for the retroarch font to encode a 'private use are' of unicode with duplicates of the forbidden characters just for this usecase but it would probably be annoying when they're displayed with the unknown glyph unicode symbol in the file explorer. 

Guess it's back to linux specific names.

**Comment by i30817** [comment]
I have a better solution for this where it mattered now, which is 'mostly in the scummvm core'. I make the playlist myself and make sure that the label has the 'complete' name without the forbidden characters so it displays fine in retroarch.

https://github.com/i30817/libretro-mkscumm

So i'm closing this.
