### ISSUE TITLE
(Menu) No default cores for Favorites

### ISSUE THREAD

**Issue by erahhal** [libretro/RetroArch#13504]
When adding a game to favorites from a playlist, the default core should referenced, or at least set for the favorite.

**Comment by RobLoach** [comment]
Last time I tested this, it worked. Could you highlight a step by step list to reproduce?

**Comment by erahhal** [comment]
Version: 1.9.14
Platform: Windows 10
Path: "e:\retrograms\Retroarch"

1. Scan roms in "roms" folder
2. Go to playlist settings, set default core for a particular platform
3. Launch a game in the playlist.  Note that it doesn't ask you to select a core.
4. Add same game to favorites from the playlist.
5. Launch game from favorites - it asks you to select a core.

**Comment by erahhal** [comment]
I've got more specifics for you.  This only happens if you've never launched the game.  If you set a default core for a playlist, launch the game, then add it to favorites, it works.  If you set a default core for the playlist, then directly add the game to favorites, it does not work.  

I don't know how things work behind the scenes, but it seems that setting the default core for a playlist should iterate through all the games and set the default core for them as well, and then when a game is added to a playlist that already has a default core, it should be set then as well.
