### ISSUE TITLE
NDS Roms not loading achievements

### ISSUE THREAD

**Issue by Zuyu-rezu** [libretro/RetroArch#13519]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

NDS RetroAchievements are not working because RetroArch can't recognize any of the games for a reason I think I've identified but don't understand.

### Expected behavior

Here's what happens when I load a GBA game in RetroArch while logged into RA.org:

[INFO] [RCHEEVOS]: Load started, hardcore active
[INFO] [RCHEEVOS]: Using host: https://retroachievements.org
[INFO] [RCHEEVOS]: Found 1 potential consoles for gba file extension
[INFO] [RCHEEVOS]: Trying console 5
[INFO] [RCHEEVOS]: Hashing 33554432 byte buffer
[INFO] [RCHEEVOS]: Generated hash 2100cf6f17e12cd34f1513647dfa506b

### Actual behavior

Here's what happens when I load any NDS game in RetroArch while logged into RA.org:

[INFO] [RCHEEVOS]: Load started, hardcore active
[INFO] [RCHEEVOS]: Using host: https://retroachievements.org
[INFO] [RCHEEVOS]: Found 1 potential consoles for nds file extension
[INFO] [RCHEEVOS]: Trying console 18
[INFO] [RCHEEVOS]: Unsupported console for buffer hash: 18
[INFO] [RCHEEVOS]: no hashes generated

### Steps to reproduce the bug

1. Install RetroArch
2. Download MelonDS core
3. Populate Nintendo DS Playlist
4. Run an nds rom with RA achievement support

### Bisect Results

I think this started happening Tuesday.  Oddly, there seem to be icons in the thumbnails/cheevos/badges folder from a few hours ago, even though I don't remember getting them to work.

### Version/Commit

- RetroArch: 1.9.14 - e954a46

### Environment information

- OS: Windows 11 Version 10.0.22000
- Compiler: MinGW (10.2.0) 64-bit

**Comment by bslenul** [comment]
Fixed in RetroArch 1.10.0, either wait for the stable release or update to nightly: https://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z ;)

![image](https://user-images.githubusercontent.com/33353403/150322046-813d7205-75fc-404d-8bb3-c0be02062c33.png)

**Comment by Jamiras** [comment]
Fixed by/more information here: #13365

**Comment by GABO1423** [comment]
> Oh, thanks! When is the stable version due?

It's out already. 1.10.0.

**Comment by Zuyu-rezu** [comment]
> It's out already. 1.10.0.

It still says 1.9.14 is the current stable version on retroarch.com.

**Comment by GABO1423** [comment]
> > It's out already. 1.10.0.
> 
> It still says 1.9.14 is the current stable version on retroarch.com.

Seems the website is outdated then. Yet, it's already in the buildbot: http://buildbot.libretro.com/stable/1.10.0/

**Comment by Zuyu-rezu** [comment]
> Seems the website is outdated then. Yet, it's already in the buildbot: http://buildbot.libretro.com/stable/1.10.0/

Thanks!  I guess that's everything, then.
