### ISSUE TITLE
Netplay is Broke

### ISSUE THREAD

**Issue by TheRoyalOne2021** [libretro/RetroArch#13534]
Netplay can't connect now even on localhost, my ports are forwarded,and it worked fine with 1.9.14, it says Room can't be connected to from internet
i tried different devices... same thing

Retroarch Version: 1.10.0
OS: Ubuntu Linux-64bit

**Comment by Cthulhu-throwaway** [comment]
1.9.14 stable didn't check whether your room was reachable from the internet at all; you would never get that notification there as it didn't exist.
1.10.0 does as long as you announce it to the lobby server; the lobby server tells RA whether it was able to connect to your room or not, which prompts that notification if it couldnt.

Connecting to 127.0.0.1 or my LAN address works fine too.

This is support-related and as the warning says when opening a new issue, this is not a support section.

**Comment by RobLoach** [comment]
Check your logs too. It will likely tell you why.
