### ISSUE TITLE
[PSVITA] RetroArch Snes9x 2005/plus audio stutter and frame drops

### ISSUE THREAD

**Issue by legolas119** [libretro/RetroArch#13539]
Description

Description
Many games drop to 45-50 fps on PSVITA using the latest Snes9x 2005/plus core. I'm using the latest Retroarch version 1.9.14

Expected behavior

I've tried Snes9x 2002, and it runs fine, but it is old, it shold be better to use the 2005 plus version.

Actual behavior
games are slow, about 48/50 fps and audio issues.

Steps to reproduce the bug

Load Snes9x 2005/plus and run any game: games will be slow and will appears audio issues
Load any non-chip game

- RetroArch: 1.9.14

**Comment by LibretroAdmin** [comment]
Hardware might just not be fast enough. Either that or overclock to 555mhz, or use the non Plus version.
