### ISSUE TITLE
Snes retroarch-ps2 is buggy in my ps2 slim

### ISSUE THREAD

**Issue by dragonball23** [libretro/RetroArch#13535]
---Description

From 1.9.3 to 1.10.0 it runs perfect with the video but ONLY if i run it using an USB stick. If i try to run it from MC0 or an USB FAT32 formatted HDD it doesnt even init. It says "Failed in creating the config file retroarch.cfg" and there it dies

---Expected behavior

1.9.3 - 1.10.0: To run from MC0 and USB HDD

--- Actual behavior

1.9.3 - 1.10.0: General crash if i run it from MC0 or USB HDD

--- Steps to reproduce the bug

Try to run it from an USB HDD drive formatted with FAT32. It will crash

--- OS: PS2 slim

**Comment by AKuHAK** [comment]
Should be fixed in https://github.com/libretro/RetroArch/pull/13752

**Comment by fjtrujy** [comment]
Fixed with https://github.com/libretro/RetroArch/pull/13752
