### ISSUE TITLE
error compiling on odroid u3

### ISSUE THREAD

**Issue by gabpaladino** [libretro/RetroArch#1355]
Hi guys, i'm trying compile retroarch in odroid u3 hardware.... 

Got this error:

audio/drivers_resampler/sinc.c:405:2: error: #error "NEON asm does not support SINC lerp."

can't find a solution, and nothing after search about this online

**Comment by tobiasjakobi** [comment]
You should pass '--enable-neon' to configure.

**Comment by gabpaladino** [comment]
this error with --enable-neon

full params: 
./configure --enable-x11 --enable-al --enable-alsa --enable-oss --enable-neon --enable-udev --enable-egl --disable-ffmpeg --enable-gles --disable-kms --disable-vg --enable-exynos --enable-pulse --enable-xvideo --enable-sdl --enable-gles3 --enable-fbo --enable-floathard

**Comment by tobiasjakobi** [comment]
Grep for 'HAVE_NEON' in config.mk and config.h after the configure step.

**Comment by tobiasjakobi** [comment]
Also, since I noticed that you enabled it, the exynos video backend doesn't work with the vendor kernel (which is odroid-3.8.y). But you probably know if you've read the readme.

**Comment by sergiobenrocha2** [comment]
This should work for you:

./configure --prefix=/usr --disable-ffmpeg --disable-vg --disable-cg --enable-gles --enable-neon --enable-floathard

It's what I'm using to build for ARM platform. Btw, if you are using Ubuntu in U3, you can use PPA, it has retroarch and many cores already compiled.
