### ISSUE TITLE
extreme slow scanning roms

### ISSUE THREAD

**Issue by xuefer** [libretro/RetroArch#13576]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

slow scanning roms for just small *.nes file

### Expected behavior

fast
please read *.rdb into memory and reuse it for the whole batch of scan

### Actual behavior

slow
procmon shows RetroArch re-reading(and re-parsing?) all *.rdb file for each rom to scan

### Steps to reproduce the bug

1. Scan new roms directory containing massive of roms

### Bisect Results

removing unused rdb ini database\rdb improve speed

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.0

### Environment information

- OS: Windows 10
- Compiler:

**Comment by RobLoach** [comment]
Use the Manual Scan for NES. NES roms can be headered, which can not match the database entries.

**Comment by makedir** [comment]
Still not fixed. Why is this programmed so badly with a linear scan of just 1 file after another? Scanning 20000 roms takes hours. Implement a proper multi threaded scan method.

**Comment by RobLoach** [comment]
Thanks for the ideas. You can implement your own playlist builder, or run the scanner via the comand line in off-hours. Performance does depend on hardware, like if you're on a slow USB-drive, for instance.

**Comment by makedir** [comment]
The scan seems to happen in a non multi threaded way one file after another, obviously that is super slow, especially for NES roms. It would be very easy to implement a multi threaded runner.
