### ISSUE TITLE
[Feature Request] UWP - Launch RetroArch from another UWP app

### ISSUE THREAD

**Issue by dbaronica** [libretro/RetroArch#13581]
## Description

RetroArch CLI enables RetroArch to be used with various frontends like LaunchBox, EmulationStation, etc...
In UWP, apps can't be started through command line, so right now there is no easy way to integrate it with other apps on for example Xbox.
However, there is a way for UWP app to start another UWP app through URI activation:
https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-uri-activation

This would open up RetroArch on Xbox to integrate with other 3rd party apps on Xbox.

### Expected behavior

Be able to start RetroArch from another UWP app using aforementioned method. 

### Actual behavior

Currently not possible.

### Version/Commit

- RetroArch: 1.10.0

### Environment information

- OS: Xbox

**Comment by dbaronica** [comment]
Implemented.

**Comment by seanocali** [comment]
Might also be worth adding this:
[https://www.c-sharpcorner.com/article/launch-uwp-app-via-commandline/](https://www.c-sharpcorner.com/article/launch-uwp-app-via-commandline/)
