### ISSUE TITLE
[Issue] Loading an M3U file with achievements enabled causes crash on Windows 10

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#13584]
## Description

Loading a game from a playlist with an M3U file cause RetroArch to crash when achievements are enabled. 

### Expected behavior

The game should load to the last disk used. 

### Actual behavior

RetroArch crashes during the game loading bug. 

### Steps to reproduce the bug

1) Ensure achievements are active
2) Load an M3U file from a playlist
3) Retroarch crashes

### Bisect Results

Last working build was 1/24 Nightly (Github commit 6ee3c14)

### Version/Commit
All builds since 1/24 through the current nightly build (Github commit e301fff)

Logs:
[retroarch__2022_01_31__11_35_39 (achievment disables no crash).log]
(https://github.com/libretro/RetroArch/files/7973738/retroarch__2022_01_31__11_35_39.achievment.disables.no.crash.log)
[retroarch__2022_01_31__11_35_27 (crash).log]
(https://github.com/libretro/RetroArch/files/7973737/retroarch__2022_01_31__11_35_27.crash.log)

Log from last working build:
[retroarch__2022_01_31__11_52_19 (last working build with achievements and no crash).log](https://github.com/libretro/RetroArch/files/7973816/retroarch__2022_01_31__11_52_19.last.working.build.with.achievements.and.no.crash.log)

### Environment information

- OS: Windows 10
- Compiler: Buildbot version

**Comment by TheRhysWyrill** [comment]
This issue also occurs for me on the Xbox/UWP version of RetroArch, however it only seems to occur if the file format of the entries within the m3u file are CHD, if it's an uncompressed bin+cue file for example then it works as normal.

**Comment by trotsky40** [comment]
Good distinction. Confirmed that it only happening with CHD for me as well.

**Comment by TheRhysWyrill** [comment]
Might also be worth mentioning that when launching an uncompressed ISO with achievements enabled with the Dolphin core it also causes RetroArch to crash, whether that is related to this issue or is something else entirely however I'm not sure.

**Comment by Jamiras** [comment]
> Might also be worth mentioning that when launching an uncompressed ISO with achievements enabled with the Dolphin core it also causes RetroArch to crash, whether that is related to this issue or is something else entirely however I'm not sure.

I believe that it's unrelated to RetroAchievements. With Rewind disabled, I can't reproduce. And with Rewind enabled and RetroAchievements disabled, I can still reproduce. I was able to reproduce the behavior at least as far back as 1.9.4.

It seems that the call to `retro_serialize_size()` (within the core) is throwing an exception when trying to determine the size of the Rewind frame.

**Comment by TheRhysWyrill** [comment]
> > Might also be worth mentioning that when launching an uncompressed ISO with achievements enabled with the Dolphin core it also causes RetroArch to crash, whether that is related to this issue or is something else entirely however I'm not sure.
> 
> I believe that it's unrelated to RetroAchievements. With Rewind disabled, I can't reproduce. And with Rewind enabled and RetroAchievements disabled, I can still reproduce. I was able to reproduce the behavior at least as far back as 1.9.4.
> 
> It seems that the call to `retro_serialize_size()` (within the core) is throwing an exception when trying to determine the size of the Rewind frame.

Strange as I don't have Rewind enabled, only RetroAchievements and when loading an ISO it crashes to Dashboard as soon as it starts initializing RetroAchievements, it might just be a UWP/Xbox specific issue, doesn't happen when using a compressed format with Dolphin thankfully.
