### ISSUE TITLE
Duckstation crashing at starting a game.

### ISSUE THREAD

**Issue by RMRubert** [libretro/RetroArch#13596]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Try to load a game using duckstation on RetroArch, retroarch crashes and exit to android TV menu.

### Expected behavior

The game loads, and run more or less fine

### Actual behavior

Retroarch crashes, exiting to the android TV menu.

### Steps to reproduce the bug

1. Use any PSX rom, in this case. GTA2.
2. Select duckstation as a core, instead of Beetle or Rearmed.
3. Click on Start

### Bisect Results

I am new to retroarch, I was trying to get a better performance than with Rearmed, so this has happened always.
SNES works fine, GBA works fine, and PSX rearmed works with terrible audio issues. I haven't tested any further cores.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.12 Android TV

### Environment information

- OS: Android TV

[retroarch__2022_02_03__21_49_09.log](https://github.com/libretro/RetroArch/files/8005872/retroarch__2022_02_03__21_49_09.log)
[retroarch__2022_02_03__20_44_50.log](https://github.com/libretro/RetroArch/files/8005873/retroarch__2022_02_03__20_44_50.log)

**Comment by hizzlekizzle** [comment]
It looks like it's having a problem with the video driver. I don't suppose your device can use vulkan?

**Comment by RMRubert** [comment]
I honestly don't know how to check that. The device is a Mi box S 4k.

Those are the specifications

Specifications

Output Resolution:4K (3840 x 2160)
CPU:Cortex-A53 Quad-core 64bit
GPU:Mali-450
RAM:2GB DDR3
Storage:8GB eMMC
Operating System:Android 8.1

**Comment by LibretroAdmin** [comment]
Inconclusive bug report. Could just be hardware doesn't support Vulkan and should try GL instead.
