### ISSUE TITLE
Cheevos crashing Retroarch

### ISSUE THREAD

**Issue by PeteSteele** [libretro/RetroArch#13597]
Hi, I detected an issue/crash using the latest updated Retroarch v1.10 as of 03/02/2022 on all cores for all Cheevos for Vulkan/OpenGL driver

[Description]:
1.) Cheevos crashing RetroArch no matter which core is used
2.) Also the small picture on the top left of your screen of the cheevo notifying of how many you have unlocked so far, when the game starts up, is the only thing that works so far, strange... it also looks weird twisted/melted/warped like melted candlewax.

Example: NES Mesen "Batman Return of the Joker (U)!" Cheevo picture looks skewed and all the others too. I am using the same shader for all of my games "crt lottes gsl"
![image](https://user-images.githubusercontent.com/36083150/152598687-a5b9667c-e60b-4e4a-8876-dd1db7ce4435.png)
![image](https://user-images.githubusercontent.com/36083150/152600216-831eab6a-9055-4921-8301-40c43a242676.png)

[What you expected to happen]:
Cheevos should just trigger without crashing the emulator

[What is actually happening]:
1.) Read the Cheevo requirement to trigger it
2.) Play the game
3.) At the point where the Cheevo is triggered the emulator crashed to desktop, no errors.

[Try to bisect and tell us when this started happening]:
Exactly from when I updated to RetroArch v1.10
- RetroArch: [version/commit]
![image](https://user-images.githubusercontent.com/36083150/152595930-48911b17-e129-4ce5-91e4-afe7f709552d.png)

Retroarch v1.10 running on Win 10 with Vulkan driver and Beetle PSX HW and it crashes on multiple games and even other cores which means its not the cores.

I noticed RetroArch thinks im running Win8 which I am not.

![image](https://user-images.githubusercontent.com/36083150/152597128-2ceec41f-0e39-4bbd-9baf-dbd062342a26.png)

All Cheevos used to work on all cores for RetroArch prior to V1.10

Please investigate or help, I would appreciate it thanks.

If i posted this in the incorrect plaze plz move it for me, this is my first time.

They also said there is a new shader:
![image](https://user-images.githubusercontent.com/36083150/152599290-f4d70596-b4cd-4330-be64-00bb5af0dafb.png)
But this shader cannot be downloaded with the internal update menu inside the emu and the shader can also not be selected therefore.

**Comment by PeteSteele** [comment]
I noticed RetroArch thinks im running Win8 which I am not.

Here is my version
![image](https://user-images.githubusercontent.com/36083150/152596645-3acf270e-3fb9-4951-ba4c-71aa2349db78.png)

**Comment by Jamiras** [comment]
5f6fc20 is the official 1.10 release. Many people are using it (with achievements) without any crashes. Can you capture a log illustrating the crash? You might also try a fresh install in case it's something in one of your config files.

I'm not sure what the warped images imply, but the crash is probably related to that, and not the achievements themselves.

The version being reported incorrectly is being handled in #13110.

**Comment by PeteSteele** [comment]
Well, the log window closes when RetroArch crashes so I can't provide that.
I will try to log to file instead.
Gimme a few minutes....

**Comment by PeteSteele** [comment]
[retroarch__2022_02_05__01_45_35.log](https://github.com/libretro/RetroArch/files/8006902/retroarch__2022_02_05__01_45_35.log)

1.) I first tried to log to console, it failed the game crashed in resident evil 3 when i picked up the shotgun for the 1st time. The game was in fullscreen mode.

2.) I then enabled log to file. The game crashed again when picking up the shotgun.

3.) I then tried to run the game in a window, to see what the log file shows, it stopped crashing and Cheevos started working again.

These points above were all in consecutive order without reinstalling.

So all I have actually ended up doing in the end was to switch from fullscreen to window and to enable the logs since my logs were disabled by default.

What could have fixed it? What was the cause. I don't know. I posted my log above, it's not very useful since there is not much in it. The logs have 3 settings; info / warning / and errors. Warnings and errors had empty files while info had what I posted.

Thanks for your help.

I love it when things mysteriosly get solved.

**Comment by PeteSteele** [comment]
Would a clean install mean:

Rename retroarch to retoarchbackup
create new retroarch folder
download retroarch and extract into new folder
play game again without copying anything from the backed up folder to see if error recreates

right?

I will try that if it crashes again.

**Comment by Jamiras** [comment]
> Would a clean install mean:

> Rename retroarch to "retoarchbackup"
> create new "retroarch" folder
> download retroarch and extract into the newly created "retroarch" folder
> play game again without copying anything from the "retoarchbackup" folder to see if the error recreates

Basically.

It's just creating a second copy somewhere (you wouldn't necessarily have to move the original) where you haven't made any configuration changes (other than enabling achievements), and see if the problem persists. If not, then you can start applying your changes (shaders/whatnot) and see if you can identify which one is causing the issue.

**Comment by PeteSteele** [comment]
OK thanks I will because the crashing stared today again, it was working fine since 3 days ago playing daily. Ill do a clean install / second copy ad give it 3 days...

**Comment by PeteSteele** [comment]
Everything is running 100% thanks for all your help. Even the skewered popups look fine. Just one last thing, i still cant find that shader that the new version boasted about. Maybe they forgot to include it in the downloads?
