### ISSUE TITLE
[Xbox/UWP] No MSU-1 Sound in Snes9x

### ISSUE THREAD

**Issue by dmspot** [libretro/RetroArch#13603]
## Description

On the Xbox, when a Super Nes game is setup to use MSU-1 with Snes9x, the game loads but there is no MSU-1 sound.

### Expected behavior

MSU-1 sound plays.

### Actual behavior

No MSU-1 sound plays.

### Steps to reproduce the bug

I tried a few different variations with an external HD and no luck on getting sound to work.

1. Folder with *.sfc, *.msu, and *.pcm's and setup/launch playlist configured with Snes9x.  Filter has "sfc msu pcm"
2. Zip with *.sfc, *.msu, and *.pcm's inside and setup/launch playlist configured with Snes9x.  Filter has "zip sfc msu pcm"
3. Ad-hoc load content and pick *.sfc + Snes9x core

NOTE: I have not tried copying the game/files directly to internal storage.

### Bisect Results

My guess is when the game files are copied over to the Xbox Internal storage, the *.msu and *.pcm files are not copied?  Since those are missing, the MSU-1 sound won't play when the game runs.

### Version/Commit
Tested on current version.  Likely an issue since the beginning.

- RetroArch: 1.10.0

### Environment information

- OS: Xbox One X

**Comment by GABO1423** [comment]
This isn't a RetroArch issue, but an issue with the way you have the files set up. If you are using a USB drive, make sure to use a NTFS formatted drive since that's the only way MSU1 hacks can work from it. Otherwise you must load it from the internal storage.

**Comment by dmspot** [comment]
I did some more tests, and it definitely seems like a copying issue from external HD -> internal (local state cache?).

Tests (same folder names/file names/structure of .sfc, .msu, .pcm in all):
  - PC: Run on laptop with Snes9X installed ==> MSU-1 sound plays
  - XBox One X: Put folder in root folder of external hard drive (NTFS) and load content with Snes9X core ==> No MSU-1 sound plays
  - XBox One X: Put folder in LocalState\roms\ folder of internal hard drive and load content with Snes9x core ==> MSU-1 sound plays

**Comment by GABO1423** [comment]
> I did some more tests, and it definitely seems like a copying issue from external HD -> internal (local state cache?).
> 
> Tests (same folder names/file names/structure of .sfc, .msu, .pcm in all):
> 
> * PC: Run on laptop with Snes9X installed ==> MSU-1 sound plays
> * XBox One X: Put folder in root folder of external hard drive (NTFS) and load content with Snes9X core ==> No MSU-1 sound plays
> * XBox One X: Put folder in LocalState\roms\ folder of internal hard drive and load content with Snes9x core ==> MSU-1 sound plays

So your problem is now with the USB Drive itself. It is not behaving as a correctly set NTFS drive should, meaning that it loads instantly without copying to the internal storage in the first place. I recommend you make sure the file permissions (ALL APPLICATION PACKAGES has full control) are correct. Either way, this again is not a RetroArch issue, it's an issue with your setup.

**Comment by dmspot** [comment]
Yah, you could be right.  Possibly relatd, I'm getting some strange behaviour with the " Could not read content file "...". (during copy read or write)" now, which I wasn't yesterday.  Not entirely sure what went wrong, but maybe it's tied to the ALL APPLICATION PACKAGES has full control setting?

I tried setting the "Enable Inheritance" config on the external HD earlier today to troubleshoot the MSU-1 issue, but Win7 has different options/steps than what is described in the official release notes, so I might have mucked something up.  I'll play around with things a bit more and see if I can get the setting correct in Win7.

Let me know if you would like me to close this issue.

**Comment by GABO1423** [comment]
> Found out a few more things (not directly related to MSU-1):
> 
> * After reformating the USB (NTFS) on Windows 7 and re-copying the files over, Retroarch can now copy to cache/unzip/load games from some of the cores it was having problems with (fbneo, dolphin)
> * the "ALL_APP_PACKAGES" item (S-1-15-2-1) doesn't exist in Windows 7 and is not equivalent to "Everyone" (S-1-1-0) like I thought.  so when I changed the security setting/inheritance to "Everyone", it likely caused the cache/unzip/loading issue
> * unfortunately, even with my cache/unzip/loading issue resolved, the MSU-1 doesn't work.  maybe still an indication that the external USB is not quite right (related to "ALL_APP_PACKAGES" above)?  on that note, if someone has MSU-1 working with Xbox on an external HD, could you let me know and I'll close this issue?  otherwise, I'm not entirely sure whether it is really an issue or not

It is an issue, but it's with your drive. Not with RetroArch. Not sure about how Windows 7 is, but with Windows 10 you can easily make ALL APPLICATION PACKAGES have full control over a driver by following these steps:
Go to the Properties of the drive -> Security -> Advanced -> Add -> Select Principal -> Advanced -> Find Now > All App Packages > Ok > Tick Full Control > Ok > Enable Inheritance.

**Comment by GABO1423** [comment]
@twinaphex I think this issue can be closed. It's user error rather than an issue with RetroArch itself.
