### ISSUE TITLE
[Xbox/UWP] Black screen in Mupen64Plus-Next core

### ISSUE THREAD

**Issue by dmspot** [libretro/RetroArch#13604]
## Description

When launching a N64 game with the Mupen64Plus-Next core, there is no video and the screen is black.  Audio plays fine.

### Expected behavior

Video shows.

### Actual behavior

No video shows (black screen).

### Steps to reproduce the bug

1. Setup a N64 playlist with the Mupen64Plus-Next core that looks for "zip z64 v64 files" on an external NTFS hard drive
2. Launch the game

### Bisect Results

I have just installed retroarch on a Xbox One X (retail mode) and haven't really changed any system/core-specific settings (that I know).  I have read in some places that using d3d11 or OpenGL is necessary for Mupen64 on Xbox?  I did try changing the renderer to OpenGL and restarted the game, but there was still no video (the setting seemed to revert back to d3d11).

NOTE: The game runs fine (video and audio are ok) on the "ParaLLEI N64" core.

Playlist: 
[Nintendo - Nintendo 64.txt](https://github.com/libretro/RetroArch/files/8010917/Nintendo.-.Nintendo.64.txt)

### Version/Commit
Current version.  Unsure if it affects other versions.

- RetroArch: 1.10.0

### Environment information

- OS: XBox One X

**Comment by GABO1423** [comment]
Not a RetroArch issue, it's a core issue. Not to mention the core is unofficial as well. And btw, the issue happens with the latest versions of GlideN64 on Xbox One systems only. You have no choice but to use an older version.

**Comment by dmspot** [comment]
Oh, good to know.  Hopefully it gets fixed at some point.  Thanks!

**Comment by GABO1423** [comment]
> Oh, good to know. Hopefully it gets fixed at some point. Thanks!

No problem, can you please close this issue then? It isn't something related to the RetroArch code itself (it's a core issue after all).
Thanks.

**Comment by dmspot** [comment]
Sure thing!
