### ISSUE TITLE
Display image thumbnails also in the Explore section

### ISSUE THREAD

**Issue by porg** [libretro/RetroArch#13610]
## Reproduction
1. Go to the "Explore" section in the main menu.
2. Go further down, i.e. "Show Genre" or "Show all", until you receive a listing of games.

## Actual
- These dynamic playlists do not display the thumbnails (game art, screenshot, startscreen)

## Proposed
- They make use of the thumbnail display as any other platform-specific playlist or the special playlists "Favorites" and "History".

## Screenshots with annotations
![1 playlist gb](https://user-images.githubusercontent.com/737143/152867802-551ae78b-aae4-4baf-a854-728cf09ddcae.png)
![2 explore](https://user-images.githubusercontent.com/737143/152867812-fe5806ec-b8d1-404f-979e-0647d78c7ca5.png)
![2a explore all](https://user-images.githubusercontent.com/737143/152867816-31abe3b6-89a4-485f-87a1-18b6bf4792aa.png)
![2b1 explore by genre](https://user-images.githubusercontent.com/737143/152867820-27aeb0a4-230b-454f-be44-813e64d92927.png)
![2b2 explore genres](https://user-images.githubusercontent.com/737143/152867825-cd93ff96-a5b1-499e-be76-cbe7ed346b17.png)
![2b3 explore genre action](https://user-images.githubusercontent.com/737143/152867826-38ed428e-8af8-4b1f-84ae-ab5a2b976397.png)

**Comment by i30817** [comment]
I'd also request as a tweak that at least in ozone you could 'move down and up' the playlist when the images are in full display instead of closing the window.

**Comment by porg** [comment]
@i30817 I very much wanting that too. This your request is related to the image and browsing experience, but is a different issue. And good news, a feature request for this already exists, see #10958. So please go there. Upvote it. And add comments.

**Comment by Alishajutt** [comment]
I have been using Ozone Imager for long time now i suppose this software to be the best in its rank
thanks for ur info and share
alisha malik
https://crackboxs.com/ozone-imager-crack/

**Comment by Alishajutt** [comment]
I have been using [Ozone Imager ](https://crackboxs.com/ozone-imager-crack/)for long time now i suppose this software to be the best in its rank
thanks for ur info and share
alisha malik
