### ISSUE TITLE
RetroArch running games slowly

### ISSUE THREAD

**Issue by AlanRibas** [libretro/RetroArch#13627]
Good morning people.

Here's the problem:

I decided to play a video game this weekend with my friends. We decided on a 4 player game and therefore chose the game “gauntlet seven sorrows”. Through Retroarch, and using the PCSX2 emulator core we start the game. But right from the start we saw that the speed was not good. As if frame rates per second are capped. Making the game horrible to play.
Initially I thought it was because the emulator still can't run that respective game well.
So I decided to play a game that I had already played several times on RetroArch, a DreamCast game called “Alien Front Online”. To my surprise the game was also slow. And I had played this game several times before at its normal speed.
Finally, just to do a test, I decided to open a super light game, a super nintendo game, called “Aladin” and surprisingly the game Aladin was also slow.

I thought my computer was busy with some unknown processing. I opened the task center but everything was normal. 2% to 4% processor usage.
 I started to imagine that it could be some RetroArch configuration. I don't know if this is inadvisable, but usually in my updates I always install the new version on top of the previous version's folder. That is, I don't do a clean install. I don't know if that could cause problems. But to check if the problem was this reason I installed in a different folder the new version of RetroArch. 1.0.10. I ran all the games mentioned above in this new clean version and all the games behaved in the same way, that is, slowly. That is, the problem at least apparently was not a configuration I made.

The thing is, I have no idea what it could be. My computer ran all PlayStation 2 games very smoothly.
Could anyone tell me what I could do??

Ps. I was even thinking about formatting the computer. But I want to leave this option as a last resort.

Computer:
Windows 10 (Updated).
Processor: i5 6600
Video Card 970 GTX Nvidia.
16 GB of RAM memory.
HD 2TB.

**Comment by hizzlekizzle** [comment]
If a fresh installation of RetroArch didn't help it, it's probably not something internal to RetroArch that's causing the problem. I would suggest checking GPU drivers (maybe roll back to a previous version) and/or GPU control panels and check for anything forcing vsync.

**Comment by AlanRibas** [comment]
Thank you for the tip. As soon as I get home I'll try to do that.

**Comment by AlanRibas** [comment]
> If a fresh installation of RetroArch didn't help it, it's probably not something internal to RetroArch that's causing the problem. I would suggest checking GPU drivers (maybe roll back to a previous version) and/or GPU control panels and check for anything forcing vsync.

Just to make sure I got it right.
Would something forcing vsync be bad?

If I see the Vsync option enabled should I uncheck this option? I thought the Vsync option was a good thing. I remember always leaving it on in the emulators I used.

**Comment by briaguya-ai** [comment]
have you

1. tested standalone emulators, are they having issues too?
2. tried different graphics apis (vulkan/openGL/directx)?
3. tried older versions of retroarch?

**Comment by AlanRibas** [comment]
> have you
> 
> 1. tested standalone emulators, are they having issues too?
> 2. tried different graphics apis (vulkan/openGL/directx)?
> 3. tried older versions of retroarch?

The last few days I was busy with my work. But today I will test. Thanks for the suggestions. I will try them.

**Comment by RobLoach** [comment]
A few tips...

- https://docs.libretro.com/guides/optimal-vsync/
- Play around with your vsync settings
- Try frameskip
- Look through the Core Options, and make sure your focusing for performance
- See the Core documentation https://docs.libretro.com/library/flycast/#performance
- Maybe try a different core?
- Ensure you're using a driver that matches your OS. On Windows, usually DirectX is a good one, but Vulkan may work too.

Closing this one. The forums may have some good tips from others too.

**Comment by AlanRibas** [comment]
I tried emulators alone and they all worked fine. I tried different cores and they all got sluggish.
I decided to go to the options to check the game's refresh rate and saw this (image below).

![A](https://user-images.githubusercontent.com/16063712/162864183-c90be48c-500d-4f50-93eb-559528eb3671.jpg)


The issue is that all the cores I configured I put them to run at 60 fps.

However, for some reason that I have no idea what it is, they run at a maximum of 30.

I have about 50 different systems installed on retroarch. All currently have this limitation of 30 frames per second.

I thought it was a retroarch configuration issue. I installed a new version, in a new folder and still the problem continued.
I checked the windows power options and they are configured to run at maximum performance.

Can anyone tell me what can i do?

**Comment by nightsy** [comment]
Hi Rob how are you? Sorry for coming back here in your topic but I'm currently experiencing the same problem as you. Can you tell me if you managed to solve the problem with the emulators? Or really had to format the PC?

**Comment by nightsy** [comment]
> Good morning people.
> 
> Here's the problem:
> 
> I decided to play a video game this weekend with my friends. We decided on a 4 player game and therefore chose the game “gauntlet seven sorrows”. Through Retroarch, and using the PCSX2 emulator core we start the game. But right from the start we saw that the speed was not good. As if frame rates per second are capped. Making the game horrible to play. Initially I thought it was because the emulator still can't run that respective game well. So I decided to play a game that I had already played several times on RetroArch, a DreamCast game called “Alien Front Online”. To my surprise the game was also slow. And I had played this game several times before at its normal speed. Finally, just to do a test, I decided to open a super light game, a super nintendo game, called “Aladin” and surprisingly the game Aladin was also slow.
> 
> I thought my computer was busy with some unknown processing. I opened the task center but everything was normal. 2% to 4% processor usage. I started to imagine that it could be some RetroArch configuration. I don't know if this is inadvisable, but usually in my updates I always install the new version on top of the previous version's folder. That is, I don't do a clean install. I don't know if that could cause problems. But to check if the problem was this reason I installed in a different folder the new version of RetroArch. 1.0.10. I ran all the games mentioned above in this new clean version and all the games behaved in the same way, that is, slowly. That is, the problem at least apparently was not a configuration I made.
> 
> The thing is, I have no idea what it could be. My computer ran all PlayStation 2 games very smoothly. Could anyone tell me what I could do??
> 
> Ps. I was even thinking about formatting the computer. But I want to leave this option as a last resort.
> 
> Computer: Windows 10 (Updated). Processor: i5 6600 Video Card 970 GTX Nvidia. 16 GB of RAM memory. HD 2TB.


Hi Alan how are you? Sorry for coming back here in your topic but I'm currently experiencing the same problem as you. Can you tell me if you managed to solve the problem with the emulators? Or really had to format the PC?
