### ISSUE TITLE
Controller config fallback appears to be chaotic

### ISSUE THREAD

**Issue by bbbradsmith** [libretro/RetroArch#13633]
I posted an issue earlier about my Logitech F310/F710 controllers not working properly, which got transferred to the autoconfig repository. However, while investigating that, while an autoconfig will help, I think there's an underlying issue with the configuration system itself.

See: https://github.com/libretro/retroarch-joypad-autoconfig/issues/824

What seems to happen is that a controller without a pre-existing autoconfig will "fall back" to something, but what it falls back seems to be frequently corrupted. Often it gets a valid set of XBox 360 configuration, but sometimes other things might happen. A few things I've seen:
- Default input mappings are fine.
- Default input mappings are wrong, but "reset to default" puts them right.
- Default input mappings are keyboard controls, but "reset to default" restores this keyboard control mapping.
- Default input mappings are partially correct, but left stick assigned to receive right stick inputs (axes kinda random, i've seen 3 different assignments).

I believe this has been happening since at least 1.9.1 but due to the random nature of what happens, it might have been happening earlier.

Steps to reproduce:
1. Have Logitech F310 or F710 plugged in as the system's only controller.
2. Download 1.10.0 stable Windows 10 64-bit build ZIP
3. Unzip
_3.5. Delete the autoconfig folder._
5. Run Retroarch.
6. If inputs are fine, switch controller driver to dinput or SDL2, close retroarch, reopen retroarch.
7. If inputs are fine for all of xinput, dinput, SDL2, delete the directory and restart from 3.

On my machine at least, this demonstrates the problem more than 50% of the time. Sometimes all 3 come up okay, but more often at least one of them will do something "bad". Just start Retrorach, and try the d-pad and left stick, and I find that one or both of them usually don't work correctly for at least one of the 3 input drivers. (HID driver never even recognizes these controllers, not sure if it's supposed to.)

Creating autoconfigs for these controllers does seem to prevent the problem for me, but I assume the same issue would come up with other unrecognized controllers.

**Comment by hizzlekizzle** [comment]
I don't have much to add here, unfortunately, other than to confirm that HID doesn't work for me either. I'm not sure why we enable it outside of Apple hardware.

**Comment by LibretroAdmin** [comment]
@hizzlekizzle Alright, I've disabled it for now for both Windows/Linux. Until we have a working backend there is indeed not much point in having it on both those OSes.

https://github.com/libretro/RetroArch/commit/bbdc6d36da885fc36dd990535d804b88b1b94a04

**Comment by gouchi** [comment]
@bbbradsmith Is it ok for you to close this issue ? As HID driver has been disabled for Linux and Windows.

Thank you.

**Comment by bbbradsmith** [comment]
The problem I reported has nothing to do with the HID driver.

**Comment by gouchi** [comment]
Thank you for the feedback.

Yes disabling HID driver was workaround and it seems not enough to fix it so for now we keep this issue opened.

**Comment by gouchi** [comment]
@LibretroAdmin Please remove `input:hid` label. Thank you.

**Comment by bbbradsmith** [comment]
Testing this again with 1.19.0, I am unable to reproduce the problem after several attempts, so it's likely that it's been fixed.

**Comment by gouchi** [comment]
Great news ! 

Please close this issue, if it is working. Thank you.
