### ISSUE TITLE
Pressing an unknown keyboard key triggers all the unbound hotkeys

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#13648]
## Description

So lately we have A LOT of reports from people having statistics showing for apparently no reason in RetroArch. While trying to reproduce I remembered #10890 and indeed I was able to reproduce by killing explorer.exe and pressing the Guide button on my controller.

After more testings my guess is that when you press an unknown key it actually triggers all the unbound hotkeys.

I was able to reproduce without killing explorer.exe and without the Guide button: I used a program called "PowerToys" (https://github.com/microsoft/PowerToys) then I simply remapped my "Numpad 0" key to "Undefined":

![image](https://user-images.githubusercontent.com/33353403/154958755-4aa1fa7f-3f48-4f61-8411-a1ea671403fb.png)

And yeah, pressing it creates a mess:

![image](https://user-images.githubusercontent.com/33353403/154943515-707f704e-dbdd-446b-b28b-b8621b673c10.png)

Only tested on Windows 10 atm, I'll check later if I can find a similar program on Linux to reproduce on my VM.

### Expected behavior

Unknown keys shouldn't have any effect.

### Actual behavior

They actually trigger all unbound hotkeys.

### Steps to reproduce the bug

Windows:

1. Install PowerToys.
2. Remap a key to "Undefined" for example (it works with some other keys as well).
3. Load content and press the key, all unbound hotkeys should activate.

### Bisect Results

No clue but it's an ooooooooold bug, just tested in 1.3.2 and it was already happening.

### Version/Commit

- RetroArch: 1.10.0 / 19a1dbb

### Environment information

- OS: Windows 10 (I'll try Linux later)

**Comment by bslenul** [comment]
Tried on my Linux Mint VM with https://github.com/sezanzeb/input-remapper but couldn't find a similar key to reproduce. I don't think this is enough to say it's a Windows only issue tho, could be happening on other distros or on native installs, etc.

**Comment by hizzlekizzle** [comment]
I've only ever heard reports of it in Windows, FWIW.

**Comment by sonninnos** [comment]
Cheers for the PowerToys trick. I got it sorted for all Windows drivers with rather small changes. SDL2 seems to be using the dinput route though. Did try to find a driver-independent method for ignoring the key, but no cigar..

**Comment by bslenul** [comment]
Seems to work like a charm (tried with both PowerToys and by killing the explorer.exe + Guide button), hopefully that will end all these "statistics" reports. It should also close #10890 and #10855 👍 

Thanks a lot for looking at this! ❤️
