### ISSUE TITLE
(macOS) Universal build with GL driver

### ISSUE THREAD

**Issue by JanJastrow** [libretro/RetroArch#13650]
Hi, I would love to see the OpenGL video driver added to the Metal/Universal build.
I'm confused why this driver is added/working with the iOS build, but not on macOS.

I read the [announcement post](https://www.libretro.com/index.php/retroarch-for-apple-mac-m1-softlaunches-today/) and understand why it is questionable to add it, but I would improve playing with some cores, as **fast forward** does not work with all metal cores.
(And I guess there are other shortcomings too)

> The only disadvantage is that there is no OpenGL support. We might want to include this later on still in the build, but we are not sure yet if this will make sense for the universal build. I guess it all depends on how long Apple will keep it in ‘deprecated’ mode before removing it altogether.

As I could not find another Github issue with this topic, I hope this issue is okay

---

Alternative: If the iOS build would be working on M1 Macs, this would could be a quick-fix for ARM Mac users.
(But I don't know if it's as easy as I wish it could be)

**Comment by LibretroAdmin** [comment]
This has been implemented now for both macOS and iOS/tvOS.
