### ISSUE TITLE
RGUI can't access settings:video:scaling menu

### ISSUE THREAD

**Issue by armadillu** [libretro/RetroArch#13692]
## Description

Can't access settings:video:scaling menu when using RGUI gui.

### Expected behavior

Reach scaling settings screen when selecting it.

### Actual behavior

When trying to access the scaling option in video settings, nothing happens, plus the cursor freezes for a few seconds (ie cant move selected menu item). Pressing the back button allows the cursor to move again.

### Steps to reproduce the bug

Every time you try the above.

### Bisect Results

Happens on Lakka 3.6 and 3.7 releases on my rg351mp device. Note that it only happens when using RGUI. When using Ozone, the scaling section is reachable and is fully functional.

### Version/Commit
git version b71be7efd2 (lakka 3.7 release)

- RetroArch: 1.10.0

### Environment information

- OS: Lakka
- Compiler: using official release, (system info shows GCC 9.4.0)

**Comment by armadillu** [comment]
I also ran Retroarch with the verbose flag from the commandline (ssh into the device), and nothing relevant was printed in the output.

**Comment by keithbowes** [comment]
Works for me.

![screenshot](https://user-images.githubusercontent.com/1697807/157376787-5f7a65d4-6802-4a05-96f8-9ffbf5e693d8.png)

**Comment by armadillu** [comment]
I reset my settings to default and it is no longer happening, closing this issue.

**Comment by armadillu** [comment]
After an update (from lakka 3.7 to lakka 3.7.3) I got the same issue again. Deleting the `retroarch.cfg` file (and thus starting with a clean slate) fixed the issue.

**Comment by ZeusOfTheCrows** [comment]
i don't think this is fixed - i encounter it semi-often.

i'm fairly sure it's related to the "Aspect Ratio" and/or "Lock Aspect Ratio" options under Settings -> User Interface -> Appearance, as messing with those (particularly the latter) often fixes it

**Comment by retropele** [comment]
> i don't think this is fixed - i encounter it semi-often.
> 
> i'm fairly sure it's related to the "Aspect Ratio" and/or "Lock Aspect Ratio" options under Settings -> User Interface -> Appearance, as messing with those (particularly the latter) often fixes it

I am currently encountering this on the most recent version of Retroarch available for Switch Homebrew, and this fixes it (thanks).
