### ISSUE TITLE
odbeta toolchains are somewhat out of date

### ISSUE THREAD

**Issue by john-parton** [libretro/RetroArch#13691]
## Description

I noticed the toolchains for opendingux-gcw0 and opendingux-rs90 haven't been updated here: https://git.libretro.com/libretro-infrastructure/libretro-build-dingux/-/tree/master/toolchain

But there have been updated toolchains here: http://od.abstraction.se/opendingux/toolchain/?C=M;O=D

@jdgleaver Not sure if this is just pointless busy work. I just went to make sure my toolchain was correct and wanted it to exactly match what the build server uses.

**Comment by jdgleaver** [comment]
@john-parton Not pointless at all! Thanks for letting me know about this. I've just updated the toolchains on gitlab to the latest versions.

**Comment by soggyfrefri** [comment]
I've been trying to figure out how to update the toolchain for my rs90 so that I could install the game mode package, but I've had no luck installing any packages at all, is there a proper way to?

**Comment by LibretroAdmin** [comment]
I'm going to assume this issue can be closed now.
