### ISSUE TITLE
[1.10.1] Core info files are not loaded, causing no emulator core to be detected as supporting savestates

### ISSUE THREAD

**Issue by mpharoah** [libretro/RetroArch#13703]
## Description
After updating to RetroArch 1.10.1, attempting to save a load a state in ParallelN64 or Mupen64Plus-Next results in an error saying that the emulator core does not support save states. Reverting to RetroArch 1.10.0 fixes the problem. The emulator cores were not changed-- I used the exact same core version in both; rather, it is an issue with RetroArch itself

### Environment information
Verified on Windows using the standalone mingw build downloaded from buildbot (https://buildbot.libretro.com/stable/1.10.1/windows/x86_64/RetroArch.7z). I haven't tested on Linux because this broken version isn't in Flatpak yet.

**Comment by hizzlekizzle** [comment]
If you haven't done it in a while, try updating your core info files. We added an option to automatically hide/disable certain features if the core doesn't support them (mostly related to savestates at the moment, including rewind and runahead), and that feature is powered by the info files.

**Comment by mpharoah** [comment]
Yes, it looks like RetroArch 1.10.1 didn't update all of the core info files.

**Comment by mpharoah** [comment]
Updating the core info files fixed it. I'll have to make my launcher override those files until the correct ones are updating in the RetroArch download.

**Comment by mpharoah** [comment]
Nevermind, this still isn't working. It was only working before because I had forgot to switch back to 10.10.1. I updated the core info, and it now _does_ have
```
savestate = "true"
savestate_features = "serialized"
```
in the `parallel_n64_libretro.info` file, but it still fails to detect the core as supporting savestates.

**Comment by mpharoah** [comment]
Okay, so I've found the problem. The file directories are completely and utterly broken in this version. Whenever you start RetoArch, it forcibly replaces `assets_directory` and `libretro_info_path` with `:\assets` and `:\info` respectively, which ends up creating a new folder in AppData/Roaming/RetroArch instead of using the one it should be.

**Comment by mpharoah** [comment]
If I go to the Directories section in the Settings menu, it shows the location that RetroArch is _supposed_ to be using:
![image](https://user-images.githubusercontent.com/19809243/156854760-f442dcf1-7d58-4556-9e3f-c752ab01aa10.png)

However, most things seems to _actually_ be looking in `C:\Users\<Username>\AppData\Roaming\RetroArch\info`

**Comment by mpharoah** [comment]
If I revert to `1.10.0`, everything works correctly and there is no `C:\Users\<Username>\AppData\Roaming\RetroArch` directory at all created (which is the correct behaviour-- the portable version should not be putting stuff in roaming data)

**Comment by mpharoah** [comment]
Hmm, no, that doesn't seem to be it either. I think the roaming data must have been from a previous install. I think it's just failing to find the assets and core info, so falls back to a default.

It turns out this is a pre-existing defect, and the change to core info simply revealed it. The assets are broken even on 10.10.0, I just didn't notice since I usually text on Linux which is fine.

**Comment by mpharoah** [comment]
Okay, the filepath changing isn't actually a problem. It's just simplifying the path. It still doesn't seem to be loading the assets or core info though, and I don't know why.

**Comment by mpharoah** [comment]
Test on Mac and the assets load fine there, but the core info files still don't. It's possible that the issues with assets I'm seeing is just a result of running Windows in a virtual machine. But either way, core info is broken on both Windows and Mac, even after running the core info updater

**Comment by mpharoah** [comment]
Running it on my Mac VM has revealed more information:
![image](https://user-images.githubusercontent.com/19809243/156860998-c927e800-8d1d-4b3f-9e6d-4ebe0ae59903.png)

I think it's not detecting my emulator core as a known emulator core, so it isn't matching it with a core info file.

**Comment by mpharoah** [comment]
Finally figured it out. A very poorly named config (the core directory is called `libretro_directory` for some reason) had me setting the core directory one directory higher than it should be. I could still load cores just fine, but apparently it won't detect the core info if its not in that directory.

I'll close this issue and make a new one with just this relevant information
