### ISSUE TITLE
Scanlines shaders are not showing for activation

### ISSUE THREAD

**Issue by dezraj** [libretro/RetroArch#13701]
## Description
Scanlines shaders are not showing for activation. I go to shaders glsl/scanlines/shaders and have "no items" there even though there are some presets if I navigate the folder in Windows explorer.

### Expected behavior

They were supposed to show there for selection.

### Actual behavior

They don't show. I can't select nothing.

### Steps to reproduce the bug

1. I open a rom in FBNeo
2. Go to shaders and enable them
3. Navigate to scanlines GLSL folder

### Bisect Results

I don't know exactly when it started. It's been a while since I've been using Retroarch.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
- Version 1.10.1
- Git Version 35312fe

### Environment information

- OS: Windows 10

**Comment by hizzlekizzle** [comment]
What video driver are you using? The default "gl" video driver works with glsl shaders but everything else uses 'slang' shaders.

**Comment by dezraj** [comment]
Hello! Thank you for your reply. I'm using all the default settings. So, for video driver, it is gl.

I'm guessing that the scanlines shaders don't show in the menu because they are not in the glslp format. It seems that only this format is support for the first shader selection unfortunately.

Is this a bug? If not, how do I generate a glslp format for these shaders?

Thank you in advance for any help.

**Comment by hizzlekizzle** [comment]
Oh, I see what you're asking now. Yeah, the 'load' there only works with presets and the scanline shaders don't have presets made for them in glsl. I made presets for the slang ones, though. I guess I could add some from the glsl ones, too.

**Comment by dezraj** [comment]
> Oh, I see what you're asking now. Yeah, the 'load' there only works with presets and the scanline shaders don't have presets made for them in glsl. I made presets for the slang ones, though. I guess I could add some from the glsl ones, too.

Thank you so much. That would be much appreciated, especially if they produce the same results as the slang (Vulkan) ones. But perhaps we could also be allowed to load the shaders without the presets? Or is this a limitation of the feature?

Anyway, I'll wait for your on these presets. Thank you again for your time.

**Comment by dezraj** [comment]
> You can load them without presets already. Just tick up the number of shader passes from 0 to 1, then where it says 'pass 1 N/A' select the glsl shader pass you want (in this case, the scanline shader you want) and then hit 'apply changes'

It worked! I suppose it isn't as intuitive as a shader preset because you always have to go through this configuration and click on "apply" to see the changes", but it's a good work-around for the time being.

Thank you again for your assistance.
