### ISSUE TITLE
Cant use RetroArch due to it needing Steam Soldier Runtime which is already installed.

### ISSUE THREAD

**Issue by coreybruce** [libretro/RetroArch#13709]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Unable to run game due to it thinking Steam Soldier Runtime not being installed even tho it already is 

[Description of the bug]

### Expected behavior

RetroArch runs

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

Ran RetroArch

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit] 1.10.0

### Environment information

- OS: Manjaro
- Compiler: [In case you are running local builds]

**Comment by m4tsa** [comment]
Ensure you are not launching Steam through some "native" thing that screws up the runtime and that the Steam Soldier runtime is installed in the primary steam library.

**Comment by coreybruce** [comment]
> Ensure you are not launching Steam through some "native" thing that screws up the runtime and that the Steam Soldier runtime is installed in the primary steam library.

Alright I'll try that out, thanks for letting me know!

**Comment by coreybruce** [comment]
Any updates on fixing this?

**Comment by coreybruce** [comment]
Seems like the latest update fixed it so what was the issue exactly?

**Comment by hizzlekizzle** [comment]
I don't think we know. Mats has been working on quite a few things related to the Steam Deck and it sounds like one of those many changes got you fixed up. /shrug

**Comment by coreybruce** [comment]
Yeah oh well thanks for the help!
