### ISSUE TITLE
Windows: retroarch-joyconfig.exe should not be included

### ISSUE THREAD

**Issue by RollingStar** [libretro/RetroArch#1371]
From Google, it looks like lots of people have issues with getting their controllers to work with RetroArch, especially when auto-configuring them through retroarch-joyconfig.exe. I assumed that I had to use retroarch-joyconfig or manually edit the config file. I didn't know that Retroarch.exe already has a more fully-featured configuration UI.

Could a note be added to retroarch-joyconfig.exe explaining that retroarch.exe already has a joyconfig?
>retroarch-joyconfig.exe is included as a fallback in case the built-in configuration in retroarch.exe does not work. Try editing inputs in retroarch.exe before using this tool.

Or maybe renaming the exe to retroarch-joyconfig-fallback.exe? Or not including the tool at all (if it has outlived its usefulness)?

**Comment by twinaphex** [comment]
Yeah I agree,  it might need to be deprecated.

**Comment by fr500** [comment]
This is more of a packaging issue than a code issue anyway

**Comment by RollingStar** [comment]
@fr500, what purpose does retroarch-joyconfig.exe serve? Here is a totally plausible user experience that can happen with the latest RetroArch (1.2.2):

1. Download RetroArch
2. Plug in your favorite joypad. (I used the iBuffalo Classic USB Gamepad, similar in form-factor to a SNES controller)
3. Launch retroarch.exe, ready to play some games.
4. Controller doesn't work.
5. "I guess I have to use retroarch-joyconfig.exe".
6. Launch retroarch-joyconfig, everything goes fine until "my SNES-style controller doesn't have enough buttons for an L3 or R3 or analog stick".
7. Close the program in confusion.
8. Launch retroarch.exe, hoping the joypad settings persisted
9. Joypad still doesn't work.
10. Frustration.

If I'm in the wrong GitHub project, please let me know where I should file this report.

**Comment by fr500** [comment]
Regarding the confussion... You're right, it shouldn't be included anymore I guess since you can map everything from the GUI

In the GUI actually there is a timeout now, so you can select bind all and then for the timeouts for the inputs you don't have.

In your case, the best bet would be:
- Go to input settings
- Select User 1 Default all
- Select User 1 Bind all
- Bind...
- Save autoconf profile
- Select User 1 Default all

**Comment by fr500** [comment]
Oh and then restart

**Comment by RollingStar** [comment]
I figured out your workaround eventually, but what I wrote is almost exactly what I went through when I opened this bug report in January. My point is that the GUI is newer code that handles this edge case better. The GUI also has a hotkey for skipping mapping of buttons, which joyconfig does not have.
