### ISSUE TITLE
Retroarch crashing on iOS when trying to save state

### ISSUE THREAD

**Issue by ysy-888** [libretro/RetroArch#13727]
## Description

Retroarch crashes trying to Save State. 

### Expected behavior

Save State correctly

### Actual behavior

The app immediately crashes 9 times out of 10. 

### Steps to reproduce the bug

Load content > Quick Menu > Save State

### Bisect Results

Since I first installed Retroarch. 

### Version/Commit
iOS 15.3.1
RetroArch 1.9.0

**Comment by LibretroAdmin** [comment]
Version too old. Retry again on latest master
