### ISSUE TITLE
A character icon is not displayed (OUTTRIGGER Dreamcast) 

### ISSUE THREAD

**Issue by Biryuk666** [libretro/RetroArch#13732]
On the level selection screen in versus mode, the player icon is not displayed

Here's a link to the screenshot:
[Character icon](https://cloud.mail.ru/public/dFXk/gNzNB11dE) 

All you need to do to see it, you need to choose vs mode => choose the character => give him a name and when loading the screen with stages, in the upper left corner of the screen there will be a regular colored square without a character icon

- RetroArch: latest steam version

- OS: Windows 10 x64
- System specification: amd ryzen 2700x; amd radeon rx480 8gb; RAM 2x 8GB DDR4 2300MHz

**Comment by gouchi** [comment]
Hi,

You should open this issue to [Flycast repository](https://github.com/flyinghead/flycast/issues) instead.

Thank you.

**Comment by Biryuk666** [comment]
> Hi,
> 
> You should open this issue to [Flycast repository](https://github.com/flyinghead/flycast/issues) instead.
> 
> Thank you.

Done all as you said. Thank you!

**Comment by gouchi** [comment]
Thank you then please close this issue ;)
