### ISSUE TITLE
DosBox Pure UWP: Unable to open file

### ISSUE THREAD

**Issue by jmoleiro** [libretro/RetroArch#13731]
## Description

Using the Dosbox Pure core on RetroArch UWP, i get the error "Unable to open file game.zip". I've tried with IMA, ZIP, ISO or even IMG, but i allways get the same error.

I've been trying on Xbox One X and on Windows 10. On W10 i tried using both the Gamr13 and the official UWP version with the same results.

Using on Windows 10 the x64 version, allows me to run the games withput problem.

### Expected behavior

On the x64 version of RetroAch, i load the content on DosBox Pure and it allows me to choose the executable file.

### Actual behavior

On any UWP version, when i load the content on the DosBox Pure core, i get the error "Unable to open file game.zip" and the options "Goto command line" or "Exit"

### Steps to reproduce the bug

1. On the main Menu, choose Load core
2. Select DosBox Pure
3. Now choose Load Content
4. Choose the game file 
5. The i get the mentioned error 

### Bisect Results

I never was able to use DosBox Pure on any UWP version i've been trying

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.1 msvc2019 (UWP W10 / MSVC 1929 64Bit / March 3 2022)
- RetroArch: 1.10.0 msvc2019 (UWP Xbox One X  / MSVC 1929 64Bit /  January 23 2022)
- RetroArch: 1.10.1 msvc2019 (UWP Xbox One X / MSVC 1929 64Bit / March 3 2022)

### Environment information

- OS: Windows 10 10.0.19043.1526
- OS: Xbox OS  10.0.22000.3832 / Shell 2203.0.2203.3002

**Comment by LibretroAdmin** [comment]
@TheRhysWyrill does this still happen?

**Comment by TheRhysWyrill** [comment]
Nope, it was only in the last few months but DOSBox Pure is now fully usable on Xbox Consoles/UWP.
