### ISSUE TITLE
[windows] trying to select a DSP filter causes vsync on/ vsync off loop

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1374]
If you select the dsp filter menu option it suddenly goes into a loop of vsync on/off, fps counter still refreshes though but you can't do nothing.

RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)
RetroArch: gl_set_nonblock_state: [GL]: VSync => on
RetroArch: gfx_ctx_wgl_swap_interval: [WGL]: wglSwapInterval(1)

**Comment by Monroe88** [comment]
On my end, those messages happen anytime I open the menu, regardless of whether any DSP filters are loaded or not, but I don't notice any issues with vsync.. DSP filters themselves work fine as far as I can tell, but they aren't applied at startup even if one is selected in audio_dsp_plugin, you have to go into the menu and select it again after starting up.

**Comment by fr500** [comment]
Are you on win32 or win64, I know the messages are normal, but not in an endless loop

**Comment by Monroe88** [comment]
I'm on 64-bit Windows 7, I'm using the 1/31 buildbot build at the moment. The endless loop thing isn't happening for me when loading DSP filters.

**Comment by fr500** [comment]
ok this one was a user issue, the audio filter directory didn't exist

**Comment by twinaphex** [comment]
It should now guard against entering this option if path directory cannot be accessed.
