### ISSUE TITLE
Feature Request: accessing ROMs from an SD card that isn't formatted as internal storage

### ISSUE THREAD

**Issue by hombiebearcat** [libretro/RetroArch#13761]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Can't access anything stored on an external SD card (Samsung Galaxy Tab A 8.0" 2019)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.9.12 (the current version of RetroArch Plus available on the Google Play store)

### Environment information

- OS: Android 11 with One UI Core 3.1

**Comment by MikeCedonis** [comment]
https://www.retroarch.com/index.php?page=platforms
1.10.1 side loaded from the official site fixes this. You still can't access a NAS unless you have an NVidia Shield.

**Comment by hombiebearcat** [comment]
Thanks for the quick response, super helpful now I can keep storage-heavy PS1 games on my SD!
