### ISSUE TITLE
Analog to Digital Type Issues. 

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#13768]
## Description

Even when a specific Analog to Digital Type is set using a remap file, if you also use an Override file with a core, this causes the Analog to Digital Type setting used in a remap file to be ignored in favor of the global setting set at Settings > Input. The only solution to this is to delete the override file. 

### Expected behavior

An override shouldn't affect a remap setting. 

### Actual behavior

An override is messing with a remap setting. 

### Steps to reproduce the bug

1. Set a core remap file with a Analog to Digital Type setting that is different than the default at Settings > Input. 
2. Create a core override file. 
3. See how the Analog to Digital Type you set in the remap is overwritten by the default. 

### Version/Commit

- RetroArch: 1.10.1

### Environment information

- OS: Windows 10 x64 Build 22000 Windows.Xbox (10.0) / Xbox Series X. 
- Compiler: MSVC (1929) 64-bit.

**Comment by dalborgo** [comment]
I have this issue just in 1.10.2.
