### ISSUE TITLE
A data race bug

### ISSUE THREAD

**Issue by ryancaicse** [libretro/RetroArch#13795]
Hi, lock gx_stop_dev_thread is used to protect `gx_stop_dev_thread`. However, `while(!gx_stop_dev_thread)` at Line 128 in the method `gx_devthread` is not protected by the lock.

https://github.com/libretro/RetroArch/blob/4a53c6771ca3749dc17fa1f2bcc44f303abdf6c4/frontend/drivers/platform_gx.c#L124-L155

https://github.com/libretro/RetroArch/blob/4a53c6771ca3749dc17fa1f2bcc44f303abdf6c4/frontend/drivers/platform_gx.c#L364-L375

**Comment by Cthulhu-throwaway** [comment]
When reading "gx_stop_dev_thread", the operation *SHOULD BE* atomic, thus no need for a lock primitive there.

**Comment by ryancaicse** [comment]
@Cthulhu-throwaway  Thank you for your reply. 

If the `while (!gx_stop_dev_thread)`  is not protected by the lock, the below time-out situation may happen
```
Thread A  running frontend_gx_deinit                                 Thread B running gx_devthread

                                                                   while (!gx_stop_dev_thread) 
 slock_lock(gx_device_cond_mutex); 
 gx_stop_dev_thread = true; 
 slock_unlock(gx_device_cond_mutex); 
scond_signal(gx_device_cond); // signal first
                                                                   scond_wait_timeout(gx_device_cond, gx_device_cond_mutex, 1000000); // have to wait until the time out

```

The above situation would not happen if

```
slock_lock(gx_device_cond_mutex); 

 while (!gx_stop_dev_thread) 
    { 
       slock_lock(gx_device_mutex); 
  
       for (i = 0; i < GX_DEVICE_END; i++) 
       { 
          if (gx_devices[i].mounted) 
          { 
             if (!gx_devices[i].interface->isInserted()) 
             { 
                char n[8] = {0}; 
  
                gx_devices[i].mounted = false; 
                snprintf(n, sizeof(n), "%s:", gx_devices[i].name); 
                fatUnmount(n); 
             } 
          } 
          else if (gx_devices[i].interface->startup() && gx_devices[i].interface->isInserted()) 
             gx_devices[i].mounted = fatMountSimple(gx_devices[i].name, gx_devices[i].interface); 
       } 
  
       slock_unlock(gx_device_mutex); 
       scond_wait_timeout(gx_device_cond, gx_device_cond_mutex, 1000000); 
    } 
 slock_unlock(gx_device_cond_mutex); 
```

**Comment by Cthulhu-throwaway** [comment]
Your approach will cause a deadlock because once the thread with loop has acquired the lock, it will never release it.

The read on gx_stop_dev_thread should be atomic, but if you absolutely can't execute the loop body without checking for gx_stop_dev_thread first, just include a if (gx_stop_dev_thread) break; after acquiring the lock.

**Comment by ryancaicse** [comment]
`Your approach will cause a deadlock because once the thread with loop has acquired the lock, it will never release it.`
Sorry, I couldn't understand this point. According to [pthread_cond_wait](https://pubs.opengroup.org/onlinepubs/007908799/xsh/pthread_cond_wait.html), it would atomically release mutex and cause the calling thread to block on the condition variable cond. Thus, the lock would be released while waiting.

Yes, `gx_stop_dev_thread` is atomic.

**Comment by Cthulhu-throwaway** [comment]
If scond_wait_timeout wraps around pthread_cond_wait, then you are right; the function is part of libretro-common, so I didn't actually know what it was doing.

I would suggest submitting a PR with your changes if you've it already tested and without deadlocks.

**Comment by LibretroAdmin** [comment]
@ryancaicse I pushed these changes here -

https://github.com/libretro/RetroArch/commit/8f1389c067f35c5c339c6f91a53d04b882e5d2db

See if this resolves your data race bug issues.

**Comment by LibretroAdmin** [comment]
Still have gotten no response, going to assume this is resolved until you respond again.
