### ISSUE TITLE
Core does not support save states

### ISSUE THREAD

**Issue by rtomasa** [libretro/RetroArch#13800]
I've compiled the new 1.10.2 version in PI4 Buster and now all system cores say that "Core does not support save states".
I was previously in 1.10.0, was any kind of parameter or feature introduced in these last 2 versions that caused this issue? Any known workaround?

**Comment by GABO1423** [comment]
Just update your core info files already. That should fix it.

**Comment by i30817** [comment]
The cause is that retroarch recently externalized some core capabilities into the info files to be able to hide the buttons if they're not available.

**Comment by rtomasa** [comment]
Thanks for the clarification. Now question is, if I've compiled my own RetroArch, how can I use the online updater? I mean, core_updater_buildbot_cores_url is empty by default and http://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest is outdated and missing many cores (I was using RetroPie Setup for getting cores but AFAIK this is not retrieving the info files)

**Comment by hizzlekizzle** [comment]
The info files are available from [the same location the buildbot pulls from](http://buildbot.libretro.com/assets/frontend/info.zip), as well as [the libretro-super repo (look in the 'dist/info' subdir)](https://github.com/libretro/libretro-super). These both include all of the info files, whether a core is available for a given platform/device or not. They're just text files, so no real harm in just providing them all at once :)

**Comment by rtomasa** [comment]
Thanks it is now all working fine
