### ISSUE TITLE
shader parameters (current) settings aren't saved

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1380]
If you change something in the (current) menu and then you save a preset it won't store the modified values but rather the original CGP values.

Changing from (menu) and saving works fine.

**Comment by fr500** [comment]
This is still an issue to this day, changing shader parameters (preview) works, but saving such changes is impossible

**Comment by rzumer** [comment]
Should be closed?

**Comment by hizzlekizzle** [comment]
Yeah, think so. Gonna close it but OP or whoever else can reopen if needed.
