### ISSUE TITLE
Mesa based Vulkan drivers get 4 swapchain images instead of 2 on Wayland, causing lag (AMDVLK gets 2 on the same setup)

### ISSUE THREAD

**Issue by nfp0** [libretro/RetroArch#13812]
## Description

Even though the `Max swapchain images` is set to 2, RetroArch is getting 4 swapchain images from RADV on Wayland, as seen on the log:

```
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "AMD RADV SIENNA_CICHLID".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Swapchain supports present mode: 1.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 2560x1440.
[INFO] [Vulkan]: Got 4 swapchain images.
```

When using AMDVLK on Wayland instead, RetroArch is getting the 2 requested swapchain images:

```
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "AMD Radeon RX 6800".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Swapchain supports present mode: 1.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 2560x1440.
[INFO] [Vulkan]: Got 2 swapchain images.
```

This causes more input lag when using RADV, as measured here on the [forums](https://forums.libretro.com/t/an-input-lag-investigation/4407/1006).

Since AMDVLK has much worse performance, and even corruption, when using shaders on RetroArch, and since RADV is the default Vulkan driver on most Linux distributions, I believe it's important to fix this issue and not rely on AMDVLK.

Apologies if this is a MESA problem instead o RetroArch's. If that is the case, please tell me and I will open an issue in MESA instead.

### Expected behavior

RetroArch should use only 2 swapchain images on RADV Wayland.

### Actual behavior

RetroArch gets 4 swapchain images, no matter the `Max swapchain images` setting.

### Version/Commit

- RetroArch: 1.10.2

### Environment information

- OS: Manjaro with KDE Plasma version 5.24.3
- GPU: AMD Radeon RX 6800

**Comment by hizzlekizzle** [comment]
I believe it is indeed out of RetroArch's hands. It can request a certain number of swapchain images, but it's up to the driver to actually hand them out.

**Comment by nfp0** [comment]
Oh I see. Ok, I'll open an issue on the Mesa side then to see if they can fix RADV.
Thank you!

I'll close this as soon as I get some confirmation from their side.

**Comment by nfp0** [comment]
Anyone knows if this is in any way related to this issue?
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/14641

**Comment by nfp0** [comment]
This issue is being discussed here on Mesa:
https://gitlab.freedesktop.org/mesa/mesa/-/issues/6249

I'll close this issue as soon as what to do next is sorted out there.

**Comment by vanfanel** [comment]
The same problem is happening on V3D Vulkan (Raspberry Pi 4).
This is on Wayland:

```

[INFO] [Vulkan]: Found GPU at index 0: "V3D 4.2".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using semaphores for WSI acquire.
[INFO] [Vulkan]: Using GPU: "V3D 4.2".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Got 4 swapchain images.
```

This is on KMS/DRM:
```
[INFO] [Vulkan]: Using GPU: "V3D 4.2".
[INFO] [Vulkan]: Queue family 0 supports 1 sub-queues.
[INFO] [Vulkan]: Got 2 swapchain images.
```

@nfp0 Would you like to change the issue tittle since it's affecting more drivers?

**Comment by nfp0** [comment]
@vanfanel It looks like it affects all Mesa based Vulkan drivers, right?
Alright. I've changed the title!

**Comment by vanfanel** [comment]
@nfp0 Yes, it affects all Vulkan drivers in Wayland. Which is good, because a fix will do for all of them. Thanks for the title change, let's wait and see...

**Comment by nfp0** [comment]
> let's wait and see...

@vanfanel
According to @Themaister, this seems to be the merge we're waiting for:
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/12086

But unfortunately, it seems to be rotting for more than 1 year. :frowning_face:

**Comment by vanfanel** [comment]
@nfp0 Owww... I hope it gets done, seems to me a major defect for Vulkan on Wayland.

**Comment by nfp0** [comment]
>  I don't know how could we speed things up.

@vanfanel I don't know either.
We could use AMDVLK in the meantime, which uses 2 swapchain images, even on Wayland, but back when I tested it, I had some issues with corrupted shaders, but maybe it's better now. If you give it a try please report back!

**Comment by gouchi** [comment]
As there is a now workaround we can close this issue ?

**Comment by nfp0** [comment]
@gouchi I believe so, yes.

Though the change was one I tried previously but was advised against by Themaister.
More discussion here: https://github.com/libretro/RetroArch/pull/15047#issuecomment-1453760233

Not sure if a better solution is in order or not, but right now the workaround works, so I'll close this.
