### ISSUE TITLE
Database: WBFS Scanning

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#13810]
Got a report that WBFS scanning was working, and now after the scanning updates, is no longer in place.

@pkos, do you know if this would've been affected by the scanning upgrade? I can see the .wbfs extension check here:
https://github.com/libretro/RetroArch/blob/bb948e9b810747dd66b0d555b4e7f17bd1cebe59/tasks/task_database.c#L567-L570

**Comment by pkos** [comment]
> Got a report that WBFS scanning was working, and now after the scanning updates, is no longer in place.
> 
> @pkos, do you know if this would've been affected by the scanning upgrade? I can see the .wbfs extension check here:
> 
> https://github.com/libretro/RetroArch/blob/bb948e9b810747dd66b0d555b4e7f17bd1cebe59/tasks/task_database.c#L567-L570

      /* Consider Wii WBFS files similar to ISO files. */
      case FILE_TYPE_WBFS:
      case FILE_TYPE_ISO:
         db_state->serial[0] = '\0';
         intfstream_file_get_serial(name, 0, SIZE_MAX, db_state->serial);
         db->type            =  DATABASE_TYPE_SERIAL_LOOKUP;
         break;

Here it looks like the case for WBFS should be duplicated from ISO.

**Comment by pkos** [comment]
https://github.com/libretro/RetroArch/pull/13816
