### ISSUE TITLE
RetroArch v1.10.2 "Snes9x - Current" core Chrono Trigger sound issue

### ISSUE THREAD

**Issue by whitezombie2000** [libretro/RetroArch#13821]
I updated to RetroArch v1.10.2 and the latest "Snes9x - Current" core and Chrono Trigger now has a static popping sound glitch. Just start a new game, it only takes about 30 seconds to get control, open and close the game menu repeatedly. You will hear a static popping sound.  I'm just using the default settings so xaudio is used and video render doesn't matter. I put two of the older cores back in place in the core folder, "Snes9x - Current" core v1.10.1 and v1.10.0, the popping sound doesn't occur. I played through the whole game on RetroArch v1.10.0 and had no issues.

I could reproduce this on my HP Omen 15-AX250WM laptop and my desktop, Intel Core i5-7500 3.40GHZ, ASRock B250 Pro4, NVIDIA GeForce GTX 1060, 16GB DDR4-2133 using Windows 10.

**Comment by hizzlekizzle** [comment]
This is likely due to a very recent change that is supposed to prevent crackling, oddly enough. @sonninnos @jdgleaver

**Comment by sonninnos** [comment]
Yes I can hear it. Otherwise the sound is clean and buffer stats are ok, but that screen toggle does something odd..

**Comment by realnc** [comment]
I just tested 93d538dfafbe88976ccdbc7a09c4f71a4d34ad1a, which is before any of the audio changes, and the issue is still there but less noticeable. It gets more noticeable if you change audio latency in RA from the default of 64ms to 32ms.

What happens is that for some reason, Chrono Trigger's menu fade results in `S9xGetSampleCount()` having too many samples, and then a few frames later too few. For example:

```text
534
533
1025
718
118
534
```

For some reason, the fade effect of this game's menu throws off the timing in the emulator?

**Comment by realnc** [comment]
Update: I just reproduced the issue with stand-alone snes9x. So this seems to have nothing to do with the libretro core. The audio code change in the core appear to have just exposed a bug in snes9x that just happened to be less noticeable before.

**Comment by realnc** [comment]
I opened a bug report upstream:

https://github.com/snes9xgit/snes9x/issues/755

**Comment by whitezombie2000** [comment]
Wow that's crazy...I can't hear anything with the stand-alone snes9x-x64.

**Comment by realnc** [comment]
> Wow that's crazy...I can't hear anything with the stand-alone snes9x-x64.

I now added a video recording in the upstream bugreport that shows what I see (or rather hear) with stand-alone snes9x.

**Comment by realnc** [comment]
This has been fixed upstream in [this commit](https://github.com/snes9xgit/snes9x/commit/6628042fe386197648334063f70e6a94350b9bf7), but it breaks audio when using runahead, which in turn is fixed in a [PR I submitted[(https://github.com/snes9xgit/snes9x/pull/760) which awaits upstream feedback.

**Comment by realnc** [comment]
This is now fixed, so please close. The fixed core will appear in the core updater at some point.

**Comment by whitezombie2000** [comment]
Thanks for all hard work! Please update the Saturn Core to latest version of Mednafen. I love Retroarch and appreciate everything you guys do!
