### ISSUE TITLE
Retroarch-Metal Homebrew package fails, sha mismatch

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [libretro/RetroArch#13820]
Downloading https://buildbot.libretro.com/stable/1.10.2/apple/osx/universal/
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 36b1efd95f3a113146b2af00da6a71638aa9cca5ea869c18e461158dc2d236d9
  Actual: c2580e719094dd1ef97ac0965e5a167616373981a0620b21893261122a78ce29
    File: ~/Library/Caches/Homebrew/downloads/60de44ad39a58b3047a600fe9d3780c183d52819ea041ce83c22f0271456dc3c--RetroArch_Metal.dmg

**Comment by warmenhoven** [comment]
This was fixed in homebrew a while back:
https://github.com/Homebrew/homebrew-cask/commit/93f8a792a75801a7313a084bf776a31a7b728907
