### ISSUE TITLE
fatal error: VG/openvg.h

### ISSUE THREAD

**Issue by douglasdock** [libretro/RetroArch#13829]
Hi
I'm trying to install retroarch, but the following message appears when I do the "make" command:

"CC gfx/drivers_context/vc_egl_ctx.c
gfx/drivers_context/vc_egl_ctx.c:25:10: fatal error: VG/openvg.h: Arquivo ou diretório inexistente
25 | #include <VG/openvg.h>
| ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:206: obj-unix/release/gfx/drivers_context/vc_egl_ctx.o] Erro 1"

In "rasp-config" there is no option:

"Advanced Options, GL Driver, Legacy, and reboot."

I am using Raspiberry OS 64bit

**Comment by cmitu** [comment]
Are you using a Pi4 ? OpenVG was never supported on this hardware.
The new Bullseye RPI OS also doesn't ship the VG libraries anymore as part of `libraspberrypi-dev` (32 or 64bit).

**Comment by douglasdock** [comment]
Hi, thanks for the reply.
I have the rasp PI4.
I'm using OS 64bits, the problem is that when I compile "RetroArch 1.10" on OS64bits this drive is requested and as it doesn't have it, the compilation fails.
How could I avoid or remove this command at compile time.

**Comment by cmitu** [comment]
Run `configure` with `--disable-videocore --disable-vg` and openVG support shouldn't be included.

**Comment by gouchi** [comment]
Hi,

It would have been better to open this issue in [the forum](https://forums.libretro.com/) first and if there is a bug you could have open an issue here.

As a reminder from the issue template,

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

Thank you.

**Comment by mrcmunir** [comment]
I can confirm detected now openvg header is detected by default on aarch64.
Now needed flag --disable-videocore --disable-vg in non rpi but fail linker cannot find -ludev into retroarch linker but libudev0 or libudev1 and libudev-dev is installed. seems it's not exist libudev.so only libudev.so.0  or libudev.so.1  i'm solved with hardlink with symbolic libudev.so to libudev.so.1
not sure if related with some header or compiler flag detected equal rpi?
I use ubuntu 22.04 now I don't know if that will be the cause
ubuntu 22.04 includes mesa3d drivers which previously didn't.

Regards
Carlos.

**Comment by zoltanvb** [comment]
I think this is resolved nowadays. During creating the RPi specific guide (https://docs.libretro.com/guides/rpi/) I did several compilations, but there was no similar fault, --disable-vg was not needed. HAVE_VG is currently set to "auto", so ./configure would have picked it up.
