### ISSUE TITLE
Device Type not loaded anymore

### ISSUE THREAD

**Issue by rtomasa** [libretro/RetroArch#13825]
Updated to RetroArch 1.10.2. Using RA from a frontend in a Pi4, which means it starts and stop on every new game you launch.
Setting a Device Type in retroarch.cfg (input_libretro_device_pN) makes no effect anymore.
Also tried setting the Device Type from que core options and saving the same as a core remap file and still not takken into consideration when running retroarch (it works during the session only).

[EDIT]
I confirm remap files are working (something weird happened in my prev tests)
So just wanted to confirm if using input_libretro_device_pN is not an option anymore or there is another different way of setting the type from retroarch.cfg

**Comment by sonninnos** [comment]
This should explain everything: https://github.com/libretro/RetroArch/pull/13749

**Comment by rtomasa** [comment]
I see... I understand it but it is unfortunate specially when used from CLI or Frontends where you know exactly what and when you require setting this globally.
I think a good mid-point had been just remove the option from the RA UI but allow setting manually via retroarch.cfg

**Comment by i30817** [comment]
Maybe you should ask for a equivalent of '--config' and '--append-config' for core files that is only valid if you start RA with '--libretro core'.

**Comment by sonninnos** [comment]
But this option has no meaning globally, that is why it was removed. Only core-specific device types matter.

I use command line launching and have zero issues with core remaps.

**Comment by i30817** [comment]
I suppose he meant he wasn't using it globally. Remember he said in the first post he's using a 'frontend that starts and stop on every new game you launch', so he could have been using a global config file for each game (or even a string to be 'echoed' with process substitution), with some being different.

Although yes, i suppose he can use the core or directory overrides and save them on retroarch.

**Comment by rtomasa** [comment]
Yes, the problem in my case is that I had a code that dynamically generates a retroarch.cfg every time I launch a game with very specific options, for example, for configuring lightgun controls. Without this global option I was forced also to dynamically generate remap files per core which also forces me to hardcode the core names in each case, and have different remap paths to avoid conflicts.
Standard remaps options are not useful in this scenario because of the fact that whether they always apply to the core when using core remaps, or don't work when using content remaps if you have subfolders.
Also there is a 3rd worse scenario which is when using same core for different systems/folders like the Genesis Plus GX.

**Comment by jdgleaver** [comment]
@rtomasa Why not use the command line interface for specifying a device type?

```
./retroarch --device=PORT:ID
```

**Comment by rtomasa** [comment]
mmm Interesting. I didn't even recall about this option. Does this method allows you to set more than one PORT:ID?
In any case I will test the same this afternoon after work.

**Comment by jdgleaver** [comment]
Yes, it should work with multiple ports: `./retroarch --device=1:2 --device=2:3` etc. Just remember that `PORT` index here starts from `1` :)

**Comment by rtomasa** [comment]
@jdgleaver thanks a lot. I've tested the same and it works perfectly fine. Super handy and much more easy approach than messing around with files.
