### ISSUE TITLE
(Xbox/UWP) Menu Sounds don't work on any menu driver except for RGUI.

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#13833]
## Description

When enabling the menu sounds in the UWP port after also having downloaded the relevant assets, the menu sounds only work when the menu driver is set to "rgui". On XMB, Ozone, and MaterialUI, these sounds don't play at all.

### Expected behavior

The Menu sounds should work on all menu drivers.

### Actual behavior

The Menu sounds only work on the RGUI driver.

### Steps to reproduce the bug

1. Download the assets from the Online Updater.
2. Enable menu sounds at Settings > Audio > Mixer.
3. Set the menu driver to xmb, glui, or ozone.

### Version/Commit

- RetroArch: 1.10.2/5e85d22

### Environment information

- OS: Windows 10 x64 Build 22000 (Xbox Series X v10)
- Compiler: MSVC (1931) 64-bit

**Comment by supneo** [comment]
It's a pity it doesn't work, for many it would be the icing on the cake to have background music and sounds in the xbox :-)

**Comment by Rebourne07** [comment]
This and cheevo unlock sounds working are my greatest dreams for this platform

**Comment by Rebourne07** [comment]
How do I assign a bounty to this? I'll pay $50 to whoever fixes this. Same for #15028 so if you solve both its $100.
