### ISSUE TITLE
[raw input driver] Remember the position of each mouse cursor

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#13839]
## Description

Hey!

So I was talking with Flyinghead about multiple mice issue with the Flycast core on RetroArch, currently with the raw driver the devices position aren't "memorized", so you can move each mouse individually but not at the same time or else the mouse cursor will be "teleported" to the other mouse position.

Kinda hard for me to explain, so here's a short video:

https://user-images.githubusercontent.com/33353403/162178046-2b49270b-8cd6-4cf5-b7ec-a1fdfcf96467.mp4

Red cursor is mouse 1, blue is mouse 2. First I move mouse 1, no issue, then I move mouse 2 and you can see its starting position "teleporting" to mouse 1 position, then I switch back to mouse 1 and it "teleports" to mouse 2 position. Finally I move both mice at the same time and you can see that you can't separate them :/

So multiplayer light gun games with mice is pretty much impossible currently :( 

### Expected behavior

Each mouse should start at its own position.

### Actual behavior

The cursor starts at the last known position of the last used mouse.

### Steps to reproduce the bug

1. Switch to raw input driver and select the proper mouse indexes.
2. Start a light gun game with Flycast (e.g. House of the Dead 2).
3. Set device type to light gun for players 1 and 2.
4. Turn ON crosshair for both players in core options.
5. Try to play.

You can reproduce with Beetle PSX as well, doesn't have to be Flycast.

### Environment information

- OS: Windows 10

**Comment by sonninnos** [comment]
Seems to be specific to the lightgun type, since two mice work fine in PUAE, but indeed two lightguns in Beetle PSX do not.

**Comment by bslenul** [comment]
Oh thanks for the precision! It didn't even cross my mind to test that on anything else than light gun games :p

**Comment by sonninnos** [comment]
I managed to get the cursors to behave nicely in core, but now I'm stuck with odd behavior in the menu. As in the actual cursor movement speed affects the menu cursor movement. No difference in fullscreen and windowed, and obviously causes harm in windowed mode when mouse is not grabbed.

https://user-images.githubusercontent.com/45124675/162448471-e72e0c48-e239-49f4-9623-8496905b9c53.mp4

Getting this far required ditching the use of `GetCursorPos()`, since all mice affect that result. But that provides accurate results for the menu, and it can't be used only with the first mouse (that only works in the menu anyway), since then the first mouse will follow the second one..

**Comment by sonninnos** [comment]
Hahaa, found out that `ps3_joypad.c` is doing a check for alive menu, so it must mean it is not totally verboten:

Please test if you can find more issues.


```diff
diff --git a/input/drivers/winraw_input.c b/input/drivers/winraw_input.c
index 1aedc7b881..ed7fdc3476 100644
--- a/input/drivers/winraw_input.c
+++ b/input/drivers/winraw_input.c
@@ -35,6 +35,10 @@ extern "C" {
 #include "../../gfx/common/win32_common.h"
 #endif

+#ifdef HAVE_MENU
+#include "../../menu/menu_driver.h"
+#endif
+
 #include "../input_keymaps.h"

 #include "../../configuration.h"
@@ -402,18 +406,36 @@ static void winraw_update_mouse_state(winraw_input_t *wr,
    }
    else if (state->lLastX || state->lLastY)
    {
-      InterlockedExchangeAdd(&mouse->dlt_x, state->lLastX);
-      InterlockedExchangeAdd(&mouse->dlt_y, state->lLastY);
-
-      if (!GetCursorPos(&crs_pos))
-         RARCH_DBG("[WinRaw]: GetCursorPos failed with error %lu.\n", GetLastError());
-      else if (!ScreenToClient((HWND)video_driver_window_get(), &crs_pos))
-         RARCH_DBG("[WinRaw]: ScreenToClient failed with error %lu.\n", GetLastError());
+#ifdef HAVE_MENU
+      if (menu_state_get_ptr()->alive)
+      {
+         if (!GetCursorPos(&crs_pos))
+            RARCH_DBG("[WinRaw]: GetCursorPos failed with error %lu.\n", GetLastError());
+         if (!ScreenToClient((HWND)video_driver_window_get(), &crs_pos))
+            RARCH_DBG("[WinRaw]: ScreenToClient failed with error %lu.\n", GetLastError());
+      }
       else
+#endif
       {
-         mouse->x = crs_pos.x;
-         mouse->y = crs_pos.y;
+         crs_pos.x = mouse->x + mouse->dlt_x;
+         crs_pos.y = mouse->y + mouse->dlt_y;
+
+         if (crs_pos.x < wr->active_rect.left)
+            crs_pos.x = wr->active_rect.left;
+         else if (crs_pos.x > wr->active_rect.right)
+            crs_pos.x = wr->active_rect.right;
+
+         if (crs_pos.y < wr->active_rect.top)
+            crs_pos.y = wr->active_rect.top;
+         else if (crs_pos.y > wr->active_rect.bottom)
+            crs_pos.y = wr->active_rect.bottom;
       }
+
+      InterlockedExchange(&mouse->dlt_x, state->lLastX);
+      InterlockedExchange(&mouse->dlt_y, state->lLastY);
+
+      mouse->x = crs_pos.x;
+      mouse->y = crs_pos.y;
    }

    if (state->usButtonFlags & RI_MOUSE_LEFT_BUTTON_DOWN)
```

**Comment by bslenul** [comment]
Seems to work like a charm with Flycast and Dolphin cores! :+1: Haven't noticed anything weird so far, in game or in menus.
