### ISSUE TITLE
The mouse stopped working after the update Retroarch (OUTTRIGGER Naomi)

### ISSUE THREAD

**Issue by Biryuk666** [libretro/RetroArch#13856]
After retroarch was updated to version 1.10.3 in the OUTTRIGGER game for Naomi, the mouse stopped functioning. Previously, the trackball function was superimposed on the mouse and triggered immediately when starting the game without any settings

RetroArch: 1.10.3

OS: Windows 10 x64

System specification: amd ryzen 2700x; amd radeon rx480 8gb; RAM 2x 8GB DDR4 2300MHz

**Comment by Cthulhu-throwaway** [comment]
Maybe related: https://github.com/libretro/RetroArch/commit/044e1ec655eea7461542371668134d13a58cc5dd

@sonninnos

**Comment by sonninnos** [comment]
Well does it work with dinput driver then? Outtrigger trackball is working here with raw driver, but it is a bit too sensitive though.

**Comment by Biryuk666** [comment]
> 

All I did was update the retroarch version. I did not change any settings or connect other devices

**Comment by sonninnos** [comment]
Well since it still works here there is not much to be done without you providing more information, such as the verbose log.

**Comment by Biryuk666** [comment]
After the last update, everything worked. Thanks!
