### ISSUE TITLE
[3DS] Console crash when attempting to earn RetroAchievements in Pokemon Yellow

### ISSUE THREAD

**Issue by muffinjets** [libretro/RetroArch#13853]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Crashes console when popping a RetroAchievement

### Expected behavior

I expected the correct achievement to pop up and the game to continue to run normally

### Actual behavior

My entire 3DS crashes.  I unfortunately don't know how to attach a Luma crash log, let me know.

### Steps to reproduce the bug

1. Boot Gambette Core on 3DS
2. Load Pokemon Yellow Version (good game dump, my own cartridge) with RetroAchievements enabled
3. Play through the intro, attempt to talk to Pikachu in Oak's Lab as soon as possible to attempt to get the "A N G E R Y" achievement.

### Bisect Results

???

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.12
- Core: Gambette (v0.5.0 9ae0cdf)

### Environment information

- OS: 3DS OS v11.15 (New3DS XL)

**Comment by LibretroAdmin** [comment]
Outdated version of RetroArch. Please retest again on nightly.
