### ISSUE TITLE
Restore old behavior of saving control remaps (or add an option)

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/RetroArch#13868]
In the latest version of RetroArch (1.10.3) there was a change in the way remaps are saved. Basically, they are saved automatically instead of you having to manually save them after you change them.

This causes problems though because you can no longer experiment with the controls without saving them forcibly, which can lead to messed up controls in games, because you forgot to revert your changes... Saving manually meant that your last saved controls were safe from messing them up because you wanted to try something else.

Saving manually is safer. Could there at least be an option, like how the "save on exit" is optional?

**Comment by Tatsuya79** [comment]
I agree it's been a problem for me too to have them saving silently now.

I have an auto remap "FinalBurn Neo.rmp" to change some buttons and disable the dpad mapped to the analog stick.
Sometimes I have to unload it or it would mess up some games that really use the analog stick or a particular setup.
I used to go to the loaded remap and push "start" to unload it but now it's not working and stays on the auto-remap.
If I "reset input mapping" it will automatically save that on the auto remap and delete my default auto-remap binding.

So I'd prefer if I can unload the remap by pushing start on the active remap file and no silent saving.
@jdgleaver
