### ISSUE TITLE
DANGER Black Frame Insertion Steam Deck Behaviour 

### ISSUE THREAD

**Issue by LeakedDave** [libretro/RetroArch#13866]
Disable black frame insertion ASAP. Almost bricked my Deck. Had to do some ninjutsu to reverse the black flickering screen. Multiple Hard resets, screen flicker persisting in desktop mode. Etc. Very scary!

**Comment by hizzlekizzle** [comment]
Thanks for the report. We're going to look into hiding this option on Steam Deck and Switch, which both can get screwy with it on and have not valid reason to ever use it, seeing as the screens are 60 Hz.

**Comment by LibretroAdmin** [comment]
Sadly didn't came in time for 1.11.1 - but we have plugged this now -
https://github.com/libretro/RetroArch/commit/fa407545858dfa0db0356b421ed914e16d86738d

**Comment by Deus-nsf** [comment]
This should work wonders on the OLED models though :)

**Comment by RandomGamingIn144p** [comment]
> This should work wonders on the OLED models though :)

90 hz would still cause pretty noticeable flicker, but its def worth a try there
