### ISSUE TITLE
Retroarch on Android hangs if netplays FUSE core

### ISSUE THREAD

**Issue by trufanov-nok** [libretro/RetroArch#13869]
## Description

The retroarch on Android hangs and not responding anymore if one try to start a netplay with Sinclair Spectrum (FUSE) core. Same core (currently distributed online) and game is netpleyed properly on Linux retroarch (from repository). Also if user is just playing the game (without starting the host or joining it) everything works correctly. So the problem is in netplay.

### Version/Commit

- RetroArch: 4b16b4f

### Environment information

- OS: Android  9.0

**Comment by Cthulhu-throwaway** [comment]
1. Remove the ROM from your post.
2. Could you try running 1.9.14 on both host and client instead of 1.10.X?

**Comment by Cthulhu-throwaway** [comment]
It's probably this one: https://github.com/libretro/RetroArch/issues/13658

Solutions (just pick one):

1. Enable "Allow Pausing" on Settings -> Network.
2. Disable "Pause Content When Menu is Active".
3. Start netplay before loading any content.
