### ISSUE TITLE
Save state images are not viewable from within RetroArch

### ISSUE THREAD

**Issue by chinagreenelvis** [libretro/RetroArch#13863]
### Expected behavior

Screenshots created alongside save states should be viewable from within RetroArch in order to make save state slot selection easier.

### Actual behavior

Generating screenshots for save states creates images that get placed into the savestates folder, but inside RetroArch they serve no purpose.

### Version/Commit
1.10.3

**Comment by Cthulhu-throwaway** [comment]
Ozone doesn't have savestate thumbnails implemented afaik.

**Comment by chinagreenelvis** [comment]
I'm super happy with the default interface. I would suggest this feature be implemented into it.

**Comment by chinagreenelvis** [comment]
Yeah, no, after testing XMB, I don't like it at all. Plus, it doesn't actually do what I'd like.

What I'd like is to see screenshots as you scroll through each save slot, that way you know what save slot you're selecting.

**Comment by chinagreenelvis** [comment]
That's a little confusing, since it's the default theme.

**Comment by chinagreenelvis** [comment]
Okay, so, as a programmer, if I wanted to contribute this function to Ozone, where would I start? Probably a stupid question that I can find the answer to elsewhere, but I may as well ask.

**Comment by chinagreenelvis** [comment]
Are all of the themes in the same GitHub or...?

**Comment by Cthulhu-throwaway** [comment]
https://github.com/libretro/RetroArch/blob/master/menu/drivers/ozone.c

**Comment by chinagreenelvis** [comment]
Thanks.

*cracks knuckles*

**Comment by sonninnos** [comment]
> Yeah, no, after testing XMB, I don't like it at all. Plus, it doesn't actually do what I'd like.
> What I'd like is to see screenshots as you scroll through each save slot, that way you know what save slot you're selecting.

XMB does do that here though..

**Comment by chinagreenelvis** [comment]
I'm not that familiar with the XMB theme, but it appears you only see the image preview when selecting "load" or "save", and not when you're actually scrolling through the save states.

I would like to see that feature implemented in the base theme, which seems logical because it's the _base_ theme. The idea that nobody is working on improving the base theme seems... a bit WTF.

**Comment by sonninnos** [comment]
Scrolling slots:
https://user-images.githubusercontent.com/45124675/163991369-0c1dc678-36b3-4362-bcab-b62b6ec42a8e.mp4

**Comment by chinagreenelvis** [comment]
> 

Oh, I see now - if you hover over "state slot" and move left or right it shows you the preview; not when you select "state slot" and scroll. Functionally, that produces the results I'm looking for, but I *really* do not like the XMB theme.

I assumed that the default them, which I guess is "ozone" was the work of the RetroArch Devs. If not, I understand why the request probably won't be fulfilled, and maybe I'll look into it myself because I really do prefer that theme.

Thanks for clarifying how the functionality does exist in the other theme, I appreciate that.

**Comment by hizzlekizzle** [comment]
The guy who made the ozone menu driver had a lot of big plans for customization features, and savestate previews was at the top of the list. Unfortunately, he got a new job that keeps him from working on it anymore, so it's orphaned now. As it often goes with open source development, it's no one's job to improve it and it's performing its intended functions, so nothing changes unless/until someone comes along who has both the desire to see a new feature implemented and the skillset to make it happen.

If that's you, feel free to step up to the plate! We're happy to help you with any information we can provide, and you should be able to crib quite a bit from the XMB implementation, since the menu drivers all pull from the same backend. We have fairly active programming-focused channels in our discord server, as well.

**Comment by ileathan** [comment]
Hi thank you for this thread. I see this was closed as completed. Does this mean it was implemented? i still cant find how to view save state screenshots in ozone.

**Comment by hizzlekizzle** [comment]
Yes, it's implemented. Make sure you go to settings > saving and set 'Save State Thumbnails' to ON. From that point on, it will take a screenshot whenever you save state, and it will display the screenshot for that state slot in the quick menu, like this:
![image](https://user-images.githubusercontent.com/2805586/207948221-2cf9c9fd-e02c-4d4b-bde6-01e5caf84113.png)

**Comment by ileathan** [comment]
Sorry im on ozone now. I am was on android and I think the default was rgui. It's showing me the images now.

**Comment by hizzlekizzle** [comment]
ozone is the default on many platforms but we default to 'glui' on mobile platforms because it's more touch-friendly.

**Comment by sonninnos** [comment]
GLUI is the only menu where this feature is not yet implemented.
