### ISSUE TITLE
Switch Save States nonfunctional

### ISSUE THREAD

**Issue by Dantasstic** [libretro/RetroArch#13861]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Save states do not work on any core on Nintendo Switch

### Expected behavior

Save states should work on cores that support save states

### Actual behavior

Any attempt to load or save a state is met with a pop that says "Core does not support save states"

### Steps to reproduce the bug

try loading or saving a state on a core that supports in on RA 1.10.3

### Bisect Results

Started after updating to 1.10.3. Issue did not occur in 1.10.1

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.10.3/a597c95]

### Environment information

- OS: Switch 14.0.0, AMS 1.3.1

**Comment by GABO1423** [comment]
Update your core info files and this will fix your error.

**Comment by Dantasstic** [comment]
That was the first thing I tried, but no luck. I also updated all the cores as well.

**Comment by Dantasstic** [comment]
Just deleted and re-added 1.10.3 from scratch. The Save and Load State options do not even appear in the Quick Menu during gameplay, even when set to show them in Menu Item Visibility settings.

**Comment by tenma10** [comment]
hi there , im confused about the solution - can you explain what you did?

**Comment by Mordecai253** [comment]
i have the same problem
