### ISSUE TITLE
No option to manually save core options or remap files

### ISSUE THREAD

**Issue by FolkSong** [libretro/RetroArch#13882]
If you don't have ""Settings->Configuration->Save Configuration on Quit" enabled, there is no way that I can see to save changes to core options or remap files.

Example: In "Quick Menu->Options->Manage Core Options". It shows my active options file is EmuName.opt. There are buttons to save game options or directory options, but no button to overwrite the existing core options file.

Example 2: As above, but I decide to save game options for a certain game. Now my active options file is GameName.opt. Then I decide to change something. However, in the Manage Core Options screen my only option is now to delete game options, there's no way to overwrite the current file. If I delete game options, every option immediately gets restored to the default, so I can't save the changes that way.

Example 3: In "Quick Menu->Controls->Manage Remap Files". My active remap file is GameName.rmp. The only choices are to load, delete or reset.

I'm pretty sure there used to be options to manually save these, but the menus were changed at some point and they were lost. You can still manually save the main configuration from "Main Menu->Configuration Files" and config overrides from "Quick Menu->Overrides".

Proposed solution: Add a save/overwrite function to the "Manage Core Options" and "Manage Remap Files" menus.

(I'm running Retroarch 1.10.2 on Windows with Ozone UI)

**Comment by bslenul** [comment]
"Save Configuration on Quit" is only for RetroArch "global" settings, it shouldn't mess with the core options or remap files saving behavior. When you have an existing options/remap file your changes are automatically saved when you close content.
