### ISSUE TITLE
(Threaded Video) video_thread_wrapper.c has a lot of redundancy

### ISSUE THREAD

**Issue by Cthulhu-throwaway** [libretro/RetroArch#13896]
## Description

Example: https://github.com/libretro/RetroArch/blob/master/gfx/video_thread_wrapper.c#L449-L475
The same condition is tested 5 times in a row.

The source code should be cleaned and optimized.

I am busy at the moment, but if by the next time I've some free time no one has dealt with this, I'll take care of it.

**Comment by twinaphex** [comment]
Would be great if you could go over it yes.
