### ISSUE TITLE
(D3D11) Broken Overlays

### ISSUE THREAD

**Issue by TheRhysWyrill** [libretro/RetroArch#13899]
## Description

When using the D3D11 video driver, no overlays display as intended, doesn't appear to be a platform specific issue as it persists on my UWP Xbox build as well as the PC build.

### Expected behavior

For overlays to display correctly.

### Actual behavior

Upon loading any overlays no overlay appears to load.

### Steps to reproduce the bug

1. Set video driver to D3D11.
2. Restart RetroArch.
3. Turn on On-Screen Overlay as well as the option to show overlay in menu.
4. Select any overlay.

### Bisect Results

From all the testing I've done this appears to have started happening from commit [`7f8a0e3`](https://github.com/libretro/RetroArch/commit/7f8a0e352f78d58f728126c37d1981354deabab1) onwards.

### Version/Commit

RetroArch: 1.10.3, commit [`499ccad`](https://github.com/libretro/RetroArch/commit/499ccad74e3d5ea44a4747bae0802b3a3461aa1c).

### Environment information

- OS: Windows 10 21H2 | Xbox Series X

**Comment by twinaphex** [comment]
Should be fixed now -
https://github.com/libretro/RetroArch/commit/984f857621b0501f90a1c820709786226de2751e

Let me know.

**Comment by TheRhysWyrill** [comment]
> Should be fixed now - [984f857](https://github.com/libretro/RetroArch/commit/984f857621b0501f90a1c820709786226de2751e)
> 
> Let me know.

Yeah, just checked with that commit as well as the latest master and overlays are working as intended with the D3D11 video driver on both.
