### ISSUE TITLE
[Feature Request] Internet Archive Game Launcher Integration

### ISSUE THREAD

**Issue by Slavko-P** [libretro/RetroArch#13903]
Considering that the Internet Archive has a DMCA exemption, what are everyone's thoughts on integrating [IAGL](https://github.com/zach-morris/plugin.program.iagl) into Retroarch?

**Comment by hizzlekizzle** [comment]
IA got a DMCA exemption for very narrow activities related to archiving certain vintage software, not for distributing it. They get (and honor) takedown requests for ROMs all the time.

We will not include any means of illicitly downloading restrictively licensed, commercial games any time now or in the future.

**Comment by Slavko-P** [comment]
> IA got a DMCA exemption for very narrow activities related to archiving certain vintage software, not for distributing it. They get (and honor) takedown requests for ROMs all the time.

The exemption allows it to host out-of-print vintage software, including retro games. 

> We will not include any means of illicitly downloading restrictively licensed, commercial games any time now or in the future.

What about adding a feature that allows the user to download/cache games(/media) from a personal repository/backup? Would that be considered a valid feature request instead?

**Comment by Cthulhu-throwaway** [comment]
> What about adding a feature that allows the user to download/cache games(/media) from a personal repository/backup? Would that be considered a valid feature request instead?

Let's be honest, the main use for this will be people unofficially sharing ROMs without permission; Retroarch/Libretro has plenty of enemies and this is just giving them ammunition to jeopardizes the project.

You can easily do what you want with a script.

**Comment by Slavko-P** [comment]
>Let's be honest, the main use for this will be people unofficially sharing ROMs without permission; 

By that logic: Lets be honest, 99% of people don't dump their own roms from their own legitimate collection...

> You can easily do what you want with a script.

True, but having it directly implemented into the frontend would make for a better user experience.

**Comment by Cthulhu-throwaway** [comment]
> By that logic: Lets be honest, 99% of people don't dump their own roms from their own legitimate collection...

Your point? Retroarch doesn't facilitate obtaining "illegal" ROMs. Your idea in the other hand...

**Comment by Slavko-P** [comment]
> Your point? Retroarch doesn't facilitate obtaining "illegal" ROMs. 

Again, by your logic: Lets be honest, the main use for Retroarch is playing retro games without permission. 

There's no point in debating this anymore.

>Your idea in the other hand...

My suggestion (the 2nd one) is for ease of use, as with many things (e.g. torrenting) can be used for good or bad.

**Comment by twinaphex** [comment]
@Slavko-P Do not make statements like this anymore. Locking this and closing.
