### ISSUE TITLE
Relay server location can't be changed without Desktop menu

### ISSUE THREAD

**Issue by trufanov-nok** [libretro/RetroArch#13905]
It's impossible to change a "Relay Server Location" in NetPlay/Network settings. The default location - NYC might have too big ping for europe users.  
Linux users might press F5 and change this setting in desktop menu. But when I was writing an instruction regarding this I realize that Windows users have no desktop menu in their build of retroarch at all. So only way to change relay server location for them is to edit configure file.  

I'm suggesting to fix  Relay Server Location in NetPlay/Network of default UI.

**Comment by Cthulhu-throwaway** [comment]
It works fine. Just press left and right to cycle through servers instead of pressing enter.

Also, the QT companion UI is available on Windows, if that's what you meant by "desktop menu".

**Comment by trufanov-nok** [comment]
> Just press left and right to cycle through servers instead of pressing enter.

Hmm.. I didn't know about that. All other options allows to select a value from the list if user clicks on them. So I never used left/right. Perhaps it's some kind of inconsistency in UI?

>  the QT companion UI is available on Windows, if that's what you meant by "desktop menu".

Yes, that's what I meant. It seems just MSVC2010 versions of retroarch install files are coming without Qt and Qt UI. Ok.

**Comment by Cthulhu-throwaway** [comment]
> Hmm.. I didn't know about that. All other options allows to select a value from the list if user clicks on them. So I never used left/right. Perhaps it's some kind of inconsistency in UI?

Not all of them. In the case of relay servers, you can't use the default action functions; whoever wrote it, just defined left and right functions.

If you absolutely need a selection submenu:

1. Assign "setting_string_action_ok_netplay_mitm_server" to "action_ok" here: https://github.com/libretro/RetroArch/blob/master/menu/menu_setting.c#L19575-L19591
2. Define a setting_string_action_ok_netplay_mitm_server.

**Comment by trufanov-nok** [comment]
Please check the PR
