### ISSUE TITLE
Touch overlay doesn't respond

### ISSUE THREAD

**Issue by PupDoesThings** [libretro/RetroArch#13909]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The touch doesn't work at all

### Expected behavior

Normally when you touch the UI, it will respond

### Actual behavior

Controls do not respond, occasional random select and back gesture

### Steps to reproduce the bug

1. Open RetroArch
2. Try moving around with the touch controls

### Bisect Results

I have no idea when this started happening, but after the second or third time I played **Sonic Megamix v4.0** for the Mega CD, it stopped working

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 4b16b4f

### Environment information

- OS: Samsung One UI 4.0 // Android 12

### VIDEO
[https://drive.google.com/file/d/1ok9wyouPoHwNDTzbrmHT3TA7-Xr2og07/view?usp=drivesdk](https://drive.google.com/file/d/1ok9wyouPoHwNDTzbrmHT3TA7-Xr2og07/view?usp=drivesdk)

**Comment by PupDoesThings** [comment]
Small update: I think it's because I accidentally switched to the SMB2 overlay, which has no buttons

**Comment by LibretroAdmin** [comment]
So a false positive then?
