### ISSUE TITLE
(Netplay) Snes9x 1.61 host doesn't register client inputs

### ISSUE THREAD

**Issue by Cthulhu-throwaway** [libretro/RetroArch#13910]
## Description

This only happens when I am hosting and it doesn't seem to be an universal problem because plenty of people netplay with this core.

What happens is that the host seems to fail to process the input from the client for whatever reason and then at "netplay check frames", the client sync back to the host, effectively rolling back to whatever state the host is.
Only happens with the current Snes9x core, Snes9x 2010 works just fine.

In the hopes of finding the source of the problem, I would very much appreciate if others could test hosting netplay with the current Snes9x core. None of the current in-place logs are triggered.

### Expected behavior

Current Snes9x core should always work with netplay.

### Actual behavior

Since input from the client is not being processed, the client can only watch the host, despite his input being registered locally.

### Steps to reproduce the bug

1. Load content with the current Snes9x core (1.61).
2. Start hosting netplay.
3. Launch a second Retroarch instance and connect to the first instance.
4. Try to send controller input from the second instance.

### Bisect Results

I reckon Snes9x 1.60 and 1.61 never worked correctly when hosting on my side, even before my netplay changes.

### Version/Commit

- RetroArch: [1.10.0/[5f6fc20](https://github.com/libretro/RetroArch/commit/5f6fc20360e4b4f24b4c0251e498e7b24c0f85c9)]

### Environment information

- OS: Windows 7 (64-bits)

**Comment by Cthulhu-throwaway** [comment]
Setting `input_max_users = "2"` to Snes9x.cfg fixes the issue for me.
My retroarch.cfg's input_max_users is 1 because I am the only one playing locally at this PC and this is the only core that doesn't work correctly with netplay when it's set to 1.
Snes9x current might have a guard checking for this value.

@sonninnos you've more experience than me with Retroarch's input system, could you confirm this is a core issue before I spend some time investigating this?

**Comment by sonninnos** [comment]
Sorry, I'm not familiar enough with it to notice anything obvious when comparing snes9x code to snes9x2010.

Or maybe it is this in 2010: https://github.com/libretro/snes9x2010/blob/c98224bc74aa0bbf355d128b22e4a2a4e94215b0/libretro/libretro.c#L1035

I thought only frontend should be calling that function, and indeed snes9x does not call it at all..

**Comment by Cthulhu-throwaway** [comment]
> Sorry, I'm not familiar enough with it to notice anything obvious when comparing snes9x code to snes9x2010.
> 
> Or maybe it is this in 2010: https://github.com/libretro/snes9x2010/blob/c98224bc74aa0bbf355d128b22e4a2a4e94215b0/libretro/libretro.c#L1035
> 
> I thought only frontend should be calling that function, and indeed snes9x does not call it at all. As in isn't that basically forcing max users to 2..?

Both of them do basically the same thing.

Snes9x 2010: Calls retro_set_controller_port_device for both controllers, which is runs this: https://github.com/libretro/snes9x2010/blob/c98224bc74aa0bbf355d128b22e4a2a4e94215b0/libretro/libretro.c#L769-L770
Snes9x: Calls S9xSetController directly (also for both controllers): https://github.com/snes9xgit/snes9x/blob/master/libretro/libretro.cpp#L1376-L1380

**Comment by OV2** [comment]
My guess would be that retroarch calls retro_set_controller_port_device for all controllers > max players with RETRO_DEVICE_NONE, which then unmaps the controllers (there was an entry in the retroarch changelog "Ensure that ‘retro_set_controller_port_device’ is called when updating ‘Max Users’").

2010 ignores RETRO_DEVICE_NONE, which is why nothing happens.

**Comment by Cthulhu-throwaway** [comment]
@OV2 Thank you very much for the info.

Are you referring to this? https://github.com/libretro/RetroArch/blob/9dd1fb895b43b251e7a1488cb2cef5f433f864d9/command.c#L939-L959
This ends up calling core_set_controller_port_device, which in turn calls retro_set_controller_port_device.

If that's what you truly believe is the source of the issue, what course of action would you think is best here?

**Comment by OV2** [comment]
I'm not sure what the desired purpose of input_max_users is. If it is supposed to limit the number of input devices reported to a core then I'd say it is working as intended. If it is not supposed to affect netplay then I'd say in this case init_controllers needs to increase the limit for all players (and set the same for every user).

You could check what other cores do in this case. But currently this effectively tells the core that all controllers > 1 have been disconnected.

**Comment by Cthulhu-throwaway** [comment]
@OV2 We do a call to core_set_controller_port_device on the client-side netplay code, which probably explains why Snes9x current accepts that input locally.

We could enforce calls to core_set_controller_port_device on the host side at netplay initialization, but we won't be able to report it as "disconnected" until the content is closed.

As for the purpose of  input_max_users, it's to limit the number of local users (and their devices) the frontend will accept (to a maximum of 16).

**Comment by OV2** [comment]
Since both server and client need the same input configuration in the core it would make sense to apply this on the host as well.

**Comment by Cthulhu-throwaway** [comment]
@OV2 again, thank you very much for coming through.

I am currently working on a client ban feature for hosts, but once I am done with that I'll focus on this.
I'll make sure to update you on whether I managed to solve the issue for Snes9x current or not.
