### ISSUE TITLE
Pcsx Rearmed Unstable

### ISSUE THREAD

**Issue by mckimiaklopa** [libretro/RetroArch#1392]
After some testing,I have found out that on FF7-9,the sound will suddenly and  randomly speed up than go to normal speeds on battles sometimes even crashing(something which happened in FF7 for me many times).Speaking of crashes,Loading FF7 will sometimes crash it(right before or during the FMV that plays before the new game screen).Other games that crash are :Castlevania SOTN(similar to ff7) and School rivals(it sometimes refuses to load the gym stage)
Device:Galaxy S Duos 2
1.2 ghz
pcsx rearmed version r21
retroarch nightly build from feb. 2

i noticed that the libretro fork is 16 commita behind and r22 has become available.Maybe the fixes applied to r22 might remove the issues i mentioned

**Comment by twinaphex** [comment]
The latest pull request @notaz made in PCSX ReARMed could have fixed it. Make this issue again in the proper repository (pcsx-rearmed) because this is not a RetroArch issue.
