### ISSUE TITLE
(Xbox/UWP) Broken Builds.

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#13939]
## Description

Commit https://github.com/libretro/RetroArch/commit/201eeae7f1cba8e29c1f14c6c7fec8d330db1d9e broke UWP builds due to it moving essential code to a file that is not included in the UWP build process, leading to link errors.

### Expected behavior

RetroArch to be build.

### Actual behavior

The exact opposite.

### Bisect Results

Commit https://github.com/libretro/RetroArch/commit/201eeae7f1cba8e29c1f14c6c7fec8d330db1d9e is the culprit.

### Environment information

- OS: Windows 10
- Compiler: Visual Studio 2022.

**Comment by LibretroAdmin** [comment]
Should be fixed now.

**Comment by GABO1423** [comment]
Can confirm, thanks!
