### ISSUE TITLE
Discord Rich Presence does not show up in `Settings > User > Privacy` for Mac M1

### ISSUE THREAD

**Issue by vidhanio** [libretro/RetroArch#13941]
## Description

On Windows, there was a Discord Rich Presence option available in `Settings > User > Privacy`. I have recently got a MacBook (Air, M1), and the option no longer exists, and Discord Rich Presence is not possible.

### Expected behavior

I expected the option to be present, as well as the Rich Presence showing up.

### Actual behavior

The option is missing, and the Rich Presence is not shown.

### Steps to reproduce the bug

1. Go to `Settings > User > Privacy`

### Bisect Results

This happened as soon as I instaled

### Version/Commit
You can find this information under Information/System Information

- RetroArch: May 2, 2022

### Environment information

- OS: macOS Monterey, Version 12.2.1
- Compiler: Clang/LLVM (12.0.0 (clang-1200.0.32.27)) 64-bit

**Comment by Cthulhu-throwaway** [comment]
Platform probably doesn't compile with the HAVE_DISCORD macro. https://github.com/libretro/RetroArch/blob/937ad8bfc6b5c79eca7a310c50fc3cbfde31e28d/menu/menu_setting.c#L21086-L21101

**Comment by LibretroAdmin** [comment]
Should be addressed now since 1.11.x.

**Comment by trvrplk** [comment]
Not there for me on 1.13.0, running Ventura 13.1

**Comment by daxoxo** [comment]
Not here for me on 1.15.0, running Sonoma
