### ISSUE TITLE
Retroarch maxing GPU with uncapped menu

### ISSUE THREAD

**Issue by z0z0z** [libretro/RetroArch#13946]
## Description
Retroarch is blasting my GPU with 80-100% load while in the menu.

### Expected behavior
Menu is capped, I have `menu_throttle_framerate = "true" `

### Actual behavior
Blasts my GPU 

### Steps to reproduce the bug
1) Open Retroarch (that's it)

### Version/Commit
v1.10.3

### Environment information
- OS: x86_64 Arch Linux, 5500XT latest mesa 144Hz monitor
- Compiler: gcc (GCC) 12.1.0

**Comment by Cthulhu-throwaway** [comment]
Do you've vsync enabled within RetroArch or force off through your driver?

**Comment by z0z0z** [comment]
> Do you've vsync enabled within RetroArch or forced off through your driver?

It's off in RA, but turning it on doesn't fix it either.

I don't have any environment variable set to disable vsync in the driver either (`vblank_mode=0` for OpenGL, `MESA_VK_WSI_PRESENT_MODE=immediate` for Vulkan)

I also don't want vsync either. I just want the Retroarch menu to not blast my GPU at 100%

**Comment by hizzlekizzle** [comment]
If you disable all throttling, either internally or externally, the menu will run as fast as it can up to whatever bottlenecks (CPU or GPU). Ditto for cores. Remove the throttling and it will spin up until something bottlenecks.

This is working as intended.

**Comment by z0z0z** [comment]
@hizzlekizzle Except I didn't disable any throttling and I in fact have this set

`menu_throttle_framerate = "true"`

**Comment by hizzlekizzle** [comment]
ah, I missed that menu throttle framerate was true and was going by the title saying "uncapped" and that vsync was off. Have you tried any other video drivers (in RetroArch)? Such as glcore?

**Comment by z0z0z** [comment]
@hizzlekizzle 
It doesn't happen with the OpenGL Retroarch drivers, only Vulkan

**Comment by hizzlekizzle** [comment]
Ok, so I guess the next step is to determine whether it works with *other* vulkan drivers (e.g., proprietary vs Mesa drivers) to see whether it's an across-the-board RA issue, a Mesa issue or something else (Mesa+AMD, etc.)

**Comment by z0z0z** [comment]
My bad, the script I wrote to start Retroarch actually was setting `MESA_VK_WSI_PRESENT_MODE=immediate`

**Comment by hizzlekizzle** [comment]
oh lol, awesome. I'm glad it ended up being something simple :D
