### ISSUE TITLE
Cores not showing up in online updater

### ISSUE THREAD

**Issue by thatgirlsarah** [libretro/RetroArch#13940]
I wanted to use Dolphin and PPSSPP  but when I download from the core system files downloader the cores don't show up in online updater. I have the nightly version of retroarch on iPhone 12 Pro running iOS 15.4.1. Also٫ there should be a flycast and play! core since they both have an app for iOS already.

**Comment by thatgirlsarah** [comment]
Ohh ok. I figured there was because they already have iOS apps.

**Comment by hizzlekizzle** [comment]
not to my knowledge. There's a similar project called Provenance that has a functioning N64 emu. Dunno about the others, though.
