### ISSUE TITLE
MEKA On RetroArch

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#13944]
Is it possible to add MEKA core For RetroArch. MEKA is open-source.

**Comment by gouchi** [comment]
It seems Meka is using [Allegro](https://liballeg.org/), there is an attempt to [port it to SDL](https://github.com/ocornut/meka/issues/25).

But they want first to replace UI with [Dear ImGui](https://github.com/ocornut/imgui) then it should be more "easier" to integrate SDL.

Maybe afterwards we could consider [Libretro port](https://docs.libretro.com/development/cores/developing-cores/).

**Comment by LibretroAdmin** [comment]
Not a RetroArch bug/issue.
