### ISSUE TITLE
Mac Metal version Chinese font

### ISSUE THREAD

**Issue by Shimmer2** [libretro/RetroArch#13950]
There is a problem with the Metal version Chinese font

**Comment by Shimmer2** [comment]
Part of the font is confused

**Comment by gouchi** [comment]
Please provide some screenshot of the issue.

**Comment by Shimmer2** [comment]
![Uploading B956BE4E-FA2D-4ECA-83F2-F75AE335121A.jpeg…]()

**Comment by Shimmer2** [comment]
![B87047BB-9D42-4921-8A2D-DCC074F789C7](https://user-images.githubusercontent.com/79088619/169567061-bde8b4f7-9acc-4db8-b402-09f281589a8f.jpeg)

**Comment by LibretroAdmin** [comment]
Looks fine on the latest nightly when changing it to 'Chinese (Traditional)' or 'Chinese (Simplified)'. Make sure like the setting says that after changing from some other language to Chinese, that you restart RetroArch first for the changes to take effect.
