### ISSUE TITLE
better graphic option for PCSX Rearmed disapeared

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#1395]
Hello,

there was an option in the PCSX Rearmed core that gave better graphic, why it is no more available?

Thank you for your answer.

LGDN.

**Comment by Kivutar** [comment]
You're talking about the extended resolution hack? If so, it's still there.

**Comment by legluondunet** [comment]
Could you tell me where they are located now? I'm using the last git and these options are no more in the "Core option" PCSX Rearmed menu:

![capture du 2015-02-08 12 06 02](https://cloud.githubusercontent.com/assets/325405/6096336/b591964c-af8b-11e4-8226-0c6204d91e60.png)

**Comment by twinaphex** [comment]
This is on an ARM or Intel x86 device? 

Intel x86 doesn't have the NEON graphics plugin any longer. It was very buggy and unlikely to be fixed, so @notaz decided to take it out.

**Comment by legluondunet** [comment]
It's a very bad news for X86 users...look at this screenshot compare:

Moto Racer 1 on Retroarch
![capture du 2015-02-07 13 59 30](https://cloud.githubusercontent.com/assets/325405/6114678/19a3ead0-b0a0-11e4-91d8-acf34fad24ab.png)

![capture du 2015-02-07 13 59 14](https://cloud.githubusercontent.com/assets/325405/6114687/263fc82c-b0a0-11e4-94cb-01366f1fa934.png)

Moto Racer 1 on PCSXR
![capture du 2015-02-07 13 28 45](https://cloud.githubusercontent.com/assets/325405/6114690/2a33151a-b0a0-11e4-91b9-7b818a9c9562.png)

![capture du 2015-02-07 13 28 34](https://cloud.githubusercontent.com/assets/325405/6114693/2e5a1e18-b0a0-11e4-84da-ba16b2891a84.png)

Actually, PS1 games emulated with PCSX Rearmed have same graphic than Mednafen.
Notaz think about develop a new plugin for X86 users?

**Comment by twinaphex** [comment]
@notaz didn't make the NEON plugin, Exophase did. And Exophase no longer does open-source development, so it's unlikely ever to get fixed. Hence, no.

**Comment by twinaphex** [comment]
Anyway, this issue doesn't belong in RetroArch, it belongs in PCSX ReARMed repo. Closing again.

**Comment by legluondunet** [comment]
I would like to report this issue on PCSX Rearmed repo, but I  can't: there is no issue button at the right menu...

**Comment by twinaphex** [comment]
Thats because its a fork of a repo. Report it in the original repo.

And anyway high chance its not something notaz is going to do anyway, so just be prepared for him saying no.

**Comment by legluondunet** [comment]
Twinaphex: that doesn't really matter, on Linux I can already use PCSXR. But I don't understand why to develop a PS1 emulator without Opengl plugin...

**Comment by twinaphex** [comment]
Then use PCSXR. It's not something @notaz and others consider important and worth the time investment and you'll have to accept that.

**Comment by legluondunet** [comment]
If PCSXRearmed is a fork of PCSXR, there is already an opengl plugin for X86 users (and others). No big time investment here, why not just make it available? I hope @notaz will answer directly.
