### ISSUE TITLE
(Threaded Video) Bad commit

### ISSUE THREAD

**Issue by Cthulhu-throwaway** [libretro/RetroArch#13960]
## Description

@LibretroAdmin

The following commit should be reverted: https://github.com/libretro/RetroArch/commit/5c6d5b0aa33d0227bf995b07c311bbadc50e281d

Both of those logs are written from the main thread.

Function video_thread_free is the one that terminates and reaps (join) the video thread. It's ALWAYS called from the main thread.
Function video_thread_init_never_call should never be called as the name implies, but if it is called (erroneous), driver init is also ALWAYS called from the main thread.

Those logs are safe and the log at video_thread_init_never_call is pretty useful in tracking down a bad commit that changes the way threaded video operates.

### Version/Commit

https://github.com/libretro/RetroArch/commit/5c6d5b0aa33d0227bf995b07c311bbadc50e281d

**Comment by LibretroAdmin** [comment]
Fine, I will reinstate it.
