### ISSUE TITLE
3DS `CONSOLE_LOG` is broken

### ISSUE THREAD

**Issue by bmaupin** [libretro/RetroArch#13973]
## Description

I'm doing some tinkering with RetroArch on 3DS and I wanted to see the logs in the bottom screen. This functionality was removed as part of https://github.com/libretro/RetroArch/pull/12470.

But the functionality can be restored:

> If you want to debug, you could build the project with the console enabled. For this, build with `CONSOLE_LOG` enabled in the makefile.

https://github.com/libretro/RetroArch/issues/12951#issuecomment-916045252

Unfortunately, this doesn't work as expected.

### Expected behavior

The bottom screen should show the RetroArch logs.

### Actual behavior

The log does briefly show in the bottom screen, and then the screen goes black again before I'm able to read it. Tapping on the bottom screen does nothing.

Going to _Settings_ > _User Interface_  and then toggling _3DS Bottom Screen_ off and then back on again makes the log show again, but once again it only shows briefly and then the screen goes blank.

### Steps to reproduce the bug

1. Set `CONSOLE_LOG             = 1` in Makefile.ctr (I did it in Makefile.ctr.salamander too just to be sure)
2. Compile RetroArch
3. Install the CIA file on a 3DS and observe the above behaviour

### Bisect Results

It looks like 07600392df4d52e975c71ca28c12fc8ee793e03d is the first bad commit:

```
07600392df4d52e975c71ca28c12fc8ee793e03d is the first bad commit
commit 07600392df4d52e975c71ca28c12fc8ee793e03d
Author: MrHuu <MrHuu@users.noreply.github.com>
Date:   Mon Sep 6 01:16:16 2021 +0200

    (3DS) Add bottom screen idle state (#12942)

 gfx/common/ctr_common.h |   4 ++
 gfx/drivers/ctr_gfx.c   | 150 +++++++++++++++++++++++++++++++++++++++++-------
 2 files changed, 133 insertions(+), 21 deletions(-)
```

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 16c0f5e223b4022698481f1ea55391f8c3f7ace2

### Environment information

- OS: 3DS
- Compiler: I'm compiling using the Docker devkitpro/devkitarm image + libretro-super

Thanks!

**Comment by bmaupin** [comment]
@MrHuu This seems to be related to #13964

Maybe I'm using it wrong? The bottom screen log blacks out after a second or two in the RetroArch menu and I can't find any way to turn it on again. Tapping the screen does nothing.

I'm using a New 2DS XL in case it makes a difference.

Thanks!

**Comment by bmaupin** [comment]
... okay, I just noticed a few things:

- If I load a game, the bottom screen is still blank
- If I tap the bottom screen while a game is loaded, the screen stays blank but the RetroArch menu appears
- If I then go into _Settings_ > _User Interface_ and toggle _3DS Bottom Screen_ off and then back on, the log will show

Surely it's not meant to be that difficult to enable? Especially given `CONSOLE_LOG` will only be enabled by developers?

Additionally, the bottom screen log never shows if no core is loaded. But I'm trying to do some debugging before the core is ever loaded. I guess as a fallback I can do all of the above steps, but it seems like a lot of work given I already had to enable `CONSOLE_LOG` and compile RetroArch...

I wonder if this behaviour was intended for the new bottom screen behaviour and not for when `CONSOLE_LOG` was enabled.

**Comment by MrHuu** [comment]
Sorry, this is not intended behavior.
As already indicated, https://github.com/libretro/RetroArch/commit/07600392df4d52e975c71ca28c12fc8ee793e03d does not take the ```CONSOLE_LOG``` flag in account.

Even with ```CONSOLE_LOG``` defined, the bottom screen will be set idle. It fades out and the LCD backlight is disabled.
While no core is running, the bottom display is always idle and disabled.

Some changes in said commit have to be guarded out to display the console on the bottom screen.

Just out of curiosity, any indication on what you're trying to debug?
Could gdb help you out in any case?

**Comment by MrHuu** [comment]
At the very least i could help you out on this one, hope this helps.

**Comment by bmaupin** [comment]
Thanks so much! I took your advice and switched to gdb. But hopefully this will still end up being useful when needing to debug something quickly.
