### ISSUE TITLE
REQUEST:  Port Hypseus-Singe

### ISSUE THREAD

**Issue by johnodon** [libretro/RetroArch#13976]
I made this request on the forum but it didn't get any attention so I figured I would try here.  I would LOVE to be able to use my bezels with Daphne!  :)

https://forums.libretro.com/t/request-port-hypseus-singe-to-a-libretro-core/34872

https://github.com/DirtBagXon/hypseus-singe

**Comment by LibretroAdmin** [comment]
Hi there, we see a mention of a libretro path in that repo but we are unsure of how this is supposed to work in the context of it being a Libretro core?

Would the author be amenable to maybe visiting us on our Discord? We could maybe discuss things then. He can contact hunterk on the Discord, we could then take things from there.

**Comment by johnodon** [comment]
> Hi there, we see a mention of a libretro path in that repo but we are unsure of how this is supposed to work in the context of it being a Libretro core?
> 
> Would the author be amenable to maybe visiting us on our Discord? We could maybe discuss things then. He can contact hunterk on the Discord, we could then take things from there.

Thanks for the attention!  I just dropped the dev a note on his GH page.  Let's hope you guys can collaborate.  :)

Closing this request.

John
