### ISSUE TITLE
Nightly builds are old? At least for Mac? Any other guidance for Mac Builds?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [libretro/RetroArch#1397]
Forgive me if this is the wrong place to ask this (and let me know where the right place is).

According to https://github.com/libretro/RetroArch/blob/master/general.h#L42 the current version is 1.1 . Yet the nightly builds, at least for Mac, are October 2014: http://buildbot.libretro.com/nightly/osx-x86_64/.

I suspect that the Makefile or build process for Mac wasn't completed or broke or something. I'd be happy to try to fix it-- does anyone know the last person who did the Mac builds successfully?

I found https://github.com/libretro/RetroArch/wiki/Compilation-guide-%28OS-X%29, but some of it doesn't seem to match the latest Mac binary at http://buildbot.libretro.com/beta/1.0.0.3/osx-x86_64/

https://github.com/smuckola edited that Doc above, is he a contributor?

Any other guidance for Mac builds would be much appreciated, hoping to find consistent steps, or do it myself and update the doc.

Thanks!

**Comment by fr500** [comment]
this is an issue for the forum.
there are no recent nightlies for mac, and someone is working on it.
If you can help you can always join at #libretro on freenode
