### ISSUE TITLE
Web Player Safari fails to run core.

### ISSUE THREAD

**Issue by patrickcorrigan** [libretro/RetroArch#13982]
## Description

Web Player doesn't launch core on Safari. The RetroArch interface loads eventually but the core won't start. You get an artifacted screen

### Expected behavior

For the core to run

### Actual behavior

Core doesn't run

### Steps to reproduce the bug

Load web player in safari. Load any core. 

I've tried building locally and I get the same issue. I'm currently messing around with different Emscripten flags to try and figure it out. Any ideas?

**Comment by JoeOsborn** [comment]
It sounds like this is resolved, can it be closed?
