### ISSUE TITLE
Enable `LOAD_WITHOUT_CORE_INFO` on 3DS builds?

### ISSUE THREAD

**Issue by bmaupin** [libretro/RetroArch#13992]
## Description

For the 3DS, the cores are provided as standalone CIA files that can be downloaded separately: https://buildbot.libretro.com/nightly/nintendo/3ds/latest/cia/

Prior to RetroArch 1.9.3, any of these standalone cores could be downloaded and installed on a 3DS and used by themselves to load content.

However, now if you install one of the standalone core CIA files, go to _Load Content_, choose the content, when getting to the _Suggested Cores_ page, the following message is shown:

> No cores available

I'm not the only one to notice the change in behaviour:

- [No cores available (3DS)](https://www.reddit.com/r/RetroArch/comments/pko96b/no_cores_available_3ds/)
- [Retroarch standalone CIA cores install](https://gbatemp.net/threads/retroarch-standalone-cia-cores-install-problem.600132/)

I did a bisect, and 50d27fada9ce557be48903fcdbe5ec72dd41ef40 appears to be the first bad commit:

```
# first bad commit: [50d27fada9ce557be48903fcdbe5ec72dd41ef40] (Static Platforms) Ensure 'Always Reload Core on Run Content' setting is applied when loading content via the file browser
```

Based on the commit message, I believe this change was unintended.

I did some deeper digging, and it appears that this functionality was later added back in 6f471e06605c036c2c1f9683945733a3dcf93efc but it doesn't seem to have been intended for 3DS.

A flag (`LOAD_WITHOUT_CORE_INFO`) was added in 9b7270cb6af3971de0a2f9e69f632f598dc46b2f to re-enable the previous behaviour for the 3DS.

Would it be possible to enable that flag by default to restore the previous behaviour?

### Expected behavior

Prior to 1.9.3, it would show the currently loaded standalone core and the content would load as expected.

### Actual behavior

The following message is shown on the _Suggested Cores_ page:

> No cores available

### Steps to reproduce the bug

1. Download any standalone core from https://buildbot.libretro.com/nightly/nintendo/3ds/latest/cia/
2. Install the CIA file on a 3DS
3. Run the core, go to _Load Content_ and choose the content

### Bisect Results

50d27fada9ce557be48903fcdbe5ec72dd41ef40 appears to be the first bad commit:

```
# first bad commit: [50d27fada9ce557be48903fcdbe5ec72dd41ef40] (Static Platforms) Ensure 'Always Reload Core on Run Content' setting is applied when loading content via the file browser
```

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `master`

### Environment information

- OS: 3DS
- Compiler: I'm compiling using the Docker devkitpro/devkitarm image + libretro-super

Thanks!

**Comment by bmaupin** [comment]
... I ran into a potential issue with this. I noticed when enabling `LOAD_WITHOUT_CORE_INFO`, save states don't work in the standalone core. But they worked fine in the standalone cores in 1.9.2.

So I did another git bisect to figure out when save states stopped working; the first bad commit to be 42e03cae8340713040d23a92d3104a70af6cf585

```
# first bad commit: [42e03cae8340713040d23a92d3104a70af6cf585] Disable save states based on save state support level defined in core info files (#13562)
```

I guess prior to that, save states were enabled by default without checking the info file for save state support?

At any rate, I'm not sure how much value there would be in enabling `LOAD_WITHOUT_CORE_INFO` by default if save states aren't going to work.

The only idea I have at the moment would be to add some conditionals to bypass the save state support checks if `LOAD_WITHOUT_CORE_INFO` is enabled, at least to match the pre-1.9.3 behaviour as close as possible...

**Comment by i30817** [comment]
This is probably a makefile problem causing the zip not to contain the core info files.

**Comment by bmaupin** [comment]
> This is probably a makefile problem causing the zip not to contain the core info files. Changing directives to not use the core info is probably ill-advised. I think that one might even be on the path to be deprecated since recently core.info files became more important to disable non-working parts of the UI for cores (as you found out with savestates).
> 
> If you want a hack to solve it yourself while this is not fixed, try to download another port and extract the info file (only) in the same directory as the cia. I think they're not platform specific...
> 
> edit: might also just be outdated core info files from the change to check for the savestate support.

RetroArch from the zip works fine. This issue is specific to installing and running standalone core files. I guess this is only possible on platforms like the 3DS:

> RetroArch on 3DS is statically linked. With statically linked RetroArch, each executable is a separate libretro core instead of the core being separately loaded from a single executable.

The issue I'm having is that these standalone cores used to work fine on their own pre 1.9.3. But since then, changes have been made to RetroArch that break this standalone core functionality. First of all, the standalone cores can't even load content (this issue). But beyond that, save state functionality is disabled because the standalone cores don't load the info files, even when they're there.

**Comment by i30817** [comment]
Ok, but then LOAD_WITHOUT_CORE_INFO is still barking up the wrong tree. If the 3DS supports non-static builds, then 'LOAD_WITHOUT_CORE_INFO' from the name shouldn't 'fix' anything, you're just making the code ignore the code info files the .so/CIA needs to load. It looks like enabling 'LOAD_WITHOUT_CORE_INFO' has some side effects that turn off the static build/allow RA to load the CIA, but also disables reading the important information of the core.info files, causing the savestate menu not be available (it's the menu, right?)

**Comment by MrHuu** [comment]
The files found here:
https://buildbot.libretro.com/nightly/nintendo/3ds/latest/cia/
https://buildbot.libretro.com/nightly/nintendo/3ds/latest/3dsx/

are NOT standalone cores.

These are the cores which are downloaded when using the ```Online Updater```, after retroarch is set-up properly including the .info files (which you could also easily get by using the ```Online Updater```).

If you wish to build a true `standalone` core for 3DS, include the required assets in the binaries ROMFS. Using something like this: [MrHuu:ctr_romfs](https://github.com/libretro/RetroArch/compare/master...MrHuu:ctr_romfs)

Other options available are only really meant for development.

**Comment by bmaupin** [comment]
> The files found here: https://buildbot.libretro.com/nightly/nintendo/3ds/latest/cia/ https://buildbot.libretro.com/nightly/nintendo/3ds/latest/3dsx/
> 
> are NOT standalone cores.

Ah ok, I think that was my main misunderstanding.

I guess it's a bummer that any `.cia` file (from the zip or from that URL) before 1.9.3 could be run as-is as a standalone core. But the changes in 50d27fada9ce557be48903fcdbe5ec72dd41ef40 and 42e03cae8340713040d23a92d3104a70af6cf585 have made it impossible to load content and use save states without the use of external info files.

I guess my thinking was that it's only been a year or so since this behaviour was broken; it would be really nice if, for example, the save state logic could be modified to take `LOAD_WITHOUT_CORE_INFO` into account, so that the old behaviour could be restored with just a simple flag. Otherwise I guess the only way to get this behaviour back is to maintain a separate set of patches.

**Comment by MrHuu** [comment]
It wasn't really a feature, it was a bug which was solved along with other issues.

I personally can't think of any advantages reverting back to undefined behavior which may have worked for some cores, but crashes the other due to enabling features which are unsupported by the core.

Without the default 'retroarch' folder structure, where would savefiles / states go? Where would the much needed video filters be?
Where would it look for the required bios files? Not even mentioning offering support for builds causing issues which shouldn't even exist.

This is just how retroarch (the frontend) was designed, and its behavior should be similar on each available platform in my opinion.

The fact that due to limitations it's not possible to load cores dynamically and have to be distributed with the frontend compiled in the executable should not change this.

The only standalone cores available are cores like ```2048```, which don't need an additional ROM to function. But the frontend still has to be set-up properly for all features to be functional as expected.

Just do a base installation, maybe stripping out files you don't need from the ```retroarch``` folder, and continue to use retroarch as you were doing before.
I really don't see any issues doing this.

**Comment by bmaupin** [comment]
Thanks for the clarification. I agree with your assessment. I'll go ahead and close this.

Thanks!
