### ISSUE TITLE
How to move menu playlists in front of main menu？ Thinks!

### ISSUE THREAD

**Issue by zhy9934** [libretro/RetroArch#14000]
https://wx4.sinaimg.cn/orj360/58aed97ely1h2tz9zjc7uj20p306bgo1.jpg

**Comment by hizzlekizzle** [comment]
Not possible currently. Sorry :(

**Comment by thingsiplay** [comment]
Well, there is a way. But I am not 100% sure if this is a good advice. You can rename the playlist file with the extension ".lpl", in example a number in front of the filename. Then it appears in the beginning. But this only works, if the RetroArch option "Sort Playlists After Name Truncation (Restart Required)" is set to OFF. Alternatively it works by creating a symlink to the playlist file too, but then both the original and link would be displayed.

Is there any good reason not to rename playlist files?

**Comment by hizzlekizzle** [comment]
They'll lose their playlist icon and just get the generic rocket icon, but that's not a big deal.

This trick won't move them in front of the main menu, though, will it?

**Comment by thingsiplay** [comment]
Yes, it loses it's icons, but at least it works fine with bringing it to the front. I tested it and it worked for me. Or I did misunderstand the question: https://i.imgur.com/UPaWSwR.png Games also run for me.

Maybe the icons problem can be solved, I don't know how RetroArch works and where it looks for the icons. I imagine something like creating a symlink would be enough (at least in Linux).
