### ISSUE TITLE
PS1 graphic quality: Retroarch ps1 cores vs PCSXR

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#1401]
Hello,

I obtain a huge difference quality graphic for PS1 emulation between retroarch and PCSXR:

Moto Racer 1 on Retroarch (PCSXRearmed or Mednafen cores)
![capture du 2015-02-07 13 59 30](https://cloud.githubusercontent.com/assets/325405/6114678/19a3ead0-b0a0-11e4-91d8-acf34fad24ab.png)

![capture du 2015-02-07 13 59 14](https://cloud.githubusercontent.com/assets/325405/6114687/263fc82c-b0a0-11e4-94cb-01366f1fa934.png)

Moto Racer 1 on PCSXR
![capture du 2015-02-07 13 28 45](https://cloud.githubusercontent.com/assets/325405/6114690/2a33151a-b0a0-11e4-91b9-7b818a9c9562.png)

![capture du 2015-02-07 13 28 34](https://cloud.githubusercontent.com/assets/325405/6114693/2e5a1e18-b0a0-11e4-84da-ba16b2891a84.png)

Did I have badly compile Retroarch? Forget an option to the compilation?

**Comment by Kivutar** [comment]
On pcsx_rearmed, you have a core option called "extended resolution". This is what makes your 3D model smooth, they are rendered at the resolution of your window.
Mednafen-PSX lacks this hack.

**Comment by twinaphex** [comment]
This is not a RetroArch issue. This is a Mednafen PSX preference issue. Report it in the proper repository.

Closing.

**Comment by legluondunet** [comment]
@Kivutar: this option is no more available in PCSX_Rearmed for Intel86 devices, only for ARM devices...a very bad news for gamers that used Retroarch regurlarly to emulate PS1 games.
