### ISSUE TITLE
(Xbox/UWP) Huge Menu Regression.

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#14018]
## Description

As discovered and discussed in PR #14008, commit https://github.com/libretro/RetroArch/commit/4dc08fad5ca107a97b0753f0385902010e16afcc broke the D3D drivers in a spectacular fashion, with menu navigation being impossible unless you do not have any assets installed. Otherwise you are greeted by a screen like this:

![image](https://user-images.githubusercontent.com/35014183/172248045-7c0f9ece-949e-45bb-8882-c81a7b3943cb.png)

### Expected behavior

I can actually use the menu.

### Actual behavior

Well, it's broken. Very broken.

### Steps to reproduce the bug

1. Open RetroArch.
2. Go to the Online Updater, update the Assets.
3. Behold the pretty background.

### Bisect Results

Commit https://github.com/libretro/RetroArch/commit/4dc08fad5ca107a97b0753f0385902010e16afcc is the culprit.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.3/https://github.com/libretro/RetroArch/commit/8b5b1ce96dcba293c4abb65333687b69757907bc

### Environment information

- OS: Xbox Series X
- Compiler: Visual Studio 2022

**Comment by LibretroAdmin** [comment]
No regression here with UWP on Windows at least. 

I'll revert it just out of precaution I guess although it does annoy me that the behavior across Xbox and Windows appears to be not leading to the same output with the UWP build.

**Comment by GABO1423** [comment]
Yeah, it's very strange. Reverting back to the build just before that commit has the menu working just fine and I built multiple times to ensure everything went correctly.

**Comment by LibretroAdmin** [comment]
See if this fixes it -

https://github.com/libretro/RetroArch/commit/8ec1f3294e5bb53ff0eb084c4ee8954c7138ebf4

**Comment by GABO1423** [comment]
Will make a build and report back.

**Comment by GABO1423** [comment]
Can confirm this resolves the issue, thanks.

**Comment by LibretroAdmin** [comment]
Thanks for helping me resolve this issue!
