### ISSUE TITLE
build failure on darwin with -fno-common toolchains: duplicate symbol '_apple_platform' in: ui_cocoa.o cocoa_common.o

### ISSUE THREAD

**Issue by trofi** [libretro/RetroArch#14025]
## Description

When building with llvm-11 or later (`llvm-11` changed `-fcommon` flag to `-fno-common`) retroarch fails as: https://hydra.nixos.org/log/gcqnaz16l60ks5pl62bfgwrclpn1838z-retroarch-bare-1.10.3.drv :

```
LD retroarch
duplicate symbol '_apple_platform' in:
    obj-unix/release/ui/drivers/ui_cocoa.o
    obj-unix/release/ui/drivers/cocoa/cocoa_common.o
duplicate symbol '_apple_platform' in:
    obj-unix/release/ui/drivers/ui_cocoa.o
    obj-unix/release/gfx/drivers_context/cocoa_gl_ctx.o
ld: 2 duplicate symbols for architecture x86_64
```

I think multiple definition happens in https://github.com/libretro/RetroArch/blob/master/ui/drivers/cocoa/apple_platform.h#L35-L41

```c
#if defined(HAVE_COCOA_METAL) || defined(HAVE_COCOATOUCH)
extern id<ApplePlatform> apple_platform;

id<ApplePlatform> apple_platform;
#else
id apple_platform;
#endif
```

`gcc-10` did a similar change (`-fno-common` section): https://gcc.gnu.org/gcc-10/porting_to.html

The usual fix is to move definitions of globals to `.c` files and leave only `extern` declarations in `.h` files.

### Expected behavior

Build should succeed

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.3

### Environment information

- OS: darwin
- Compiler: llvm-11

**Comment by LibretroAdmin** [comment]
Can you submit a proposed buildfix as a PR?

**Comment by trofi** [comment]
(took me a while to get to the darwin) Proposed possible fix as https://github.com/libretro/RetroArch/pull/14204.

**Comment by gouchi** [comment]
@trofi Fix has been merged so we can close this issue ?

**Comment by trofi** [comment]
Yeah, let's close.
