### ISSUE TITLE
MEKA on RetroArch

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#14043]
Sega - SMS/GG/SG-1000/SC-3000/SF-7000/ColecoVision - MEKA

is it possible to add a MEKA core on RetroArch

MEKA is open-source

**Comment by hizzlekizzle** [comment]
Sure, if it's open source, it's possible, but is there a reason to port it instead of using one of the existing cores?

**Comment by LibretroAdmin** [comment]
We'd always love seeing more libretro cores by external contributors, but it's also unfortunately not a valid RetroArch bug report. So closing.
