### ISSUE TITLE
Retroarch thumbnails

### ISSUE THREAD

**Issue by masanasake** [libretro/RetroArch#14045]
What happened to the retroarch thumbnails repository on github? It's completely disappeared. 
<img width="680" alt="image" src="https://user-images.githubusercontent.com/105944840/174115292-f4b6345f-dec5-4a5b-aab9-19c70e573f8c.png">

**Comment by i30817** [comment]
Github took them down, probably either because they disliked the size. There are other more distasteful possibilities, but since it would just be speculation, not worth thinking about it. Maybe complaining to github will work.

**Comment by LibretroAdmin** [comment]
Github flagged it yeah. They made the implication we were using their services as a CDN and that this was not allowed. So now it's only available for internal use. We'll have to see where to go from here.

**Comment by LibretroAdmin** [comment]
@RobLoach and @kivutar were trying to sort this out. Will leave further commentary up to them.

**Comment by bslenul** [comment]
> That's absolute nonsense since the repositories are not accessed directly by retroarch or any application i'm aware of, just the thumbnails server. Complain with proof.

Seems to be a legit complaint, this morning kivutar said on Discord it was because of stuff like this: https://github.com/libretro/RetroArch/blob/50f65a893fe2e6cd0bd954cc205c8fd0ec78d7b7/ui/drivers/qt/qt_downloads.cpp#L37

**Comment by i30817** [comment]
Well, apparently it's just the QT gui, according to search. Although i know search in github is often incomplete.

**Comment by LibretroAdmin** [comment]
Qt UI code was an independently contracted job, and I guess this was an oversight. Have a PR in waiting that should resolve the issue, hopefully Github can unflag the organization afterwards.

**Comment by masanasake** [comment]
Looks like it's back. Thanks everyone.

**Comment by i30817** [comment]
Back except the record of all the PRs accepted in your personal PR list (at the top of github). Doesn't matter as long as the prs are in the project pages ofc, but some data is lost.
