### ISSUE TITLE
[RetroAchievements] Error awarding achievement on Encore Mode

### ISSUE THREAD

**Issue by Matheus290** [libretro/RetroArch#14041]
## Description

Error display when unlocking achievements (which have been unlocked previously) in Encore Mode.

### Expected behavior

Do not display the error. Because I'm in Encore Mode and expected to unlock achievements that have been unlocked before.

### Actual behavior

During Encore Mode (RetroAchievements), an error is displayed every time an achievement is unlocked (when I already own it).

The error is: "Error awarding achievement #: Player already unlocked this achievement."

Tested on Snes9x 2010, Snes9x, Genesis Plus GX and Stella 2600. The error appears with Hardcore Mode on or off.

### Steps to reproduce the bug

1. Activate RetroAchievements
2. Activate Encore Mode
3. Unlock an achievement

### Bisect Results

It started when I activated encore mode.

### Version/Commit

- RetroArch: 1.10.3

### Environment information

- OS: Windows 10 x64

**Comment by Jamiras** [comment]
Thank you for reporting this. The client is looking for a specific error message to indicate the achievement was previously rewarded, and it looks like that got changed on the server.

**Comment by Jamiras** [comment]
Server has been hot-patched. You should no longer see the error.
