### ISSUE TITLE
1.10.3 (Android) - autoconfig not working

### ISSUE THREAD

**Issue by Son-Vegitto** [libretro/RetroArch#14046]
##Description

After updating from 1.9.14 Android to 1.10.3, autoconfig is not working. 

Expected behavior
Autoconfig to work correctly (using an Xbox One Bluetooth controller).

Actual behavior
Autoconfig uses fallback, instead of the Xbox One Bluetooth profile.  This is displayed in the UI, "Virtual (0/0) not configured, using fallback".

Steps to reproduce the bug
Install 1.10.3 Android
Open and update the autoconfig setting to 'on'
Restart RetroArch
Upon boot, use controller to input one key
"Virtual (0/0) not configured, using fallback"

Bisect Results
I have two devices. On my old device - running Android 8.1 and RetroArch 1.9.14, autoconfig works. On my new device - running Android 11 and RetroArch 1.10.3 and the same settings (copy/pasted them from device to device), autoconfig does not work. 

Version/Commit
You can find this information under Information/System Information

RetroArch: 102abb0
Environment information
OS: Android 11
Compiler: Clang/LLVM (RetroArch website)

**Comment by Son-Vegitto** [comment]
To note, I tried fully removing my autoconfig folder and use RetroArch to download it fresh. That did not seem to result in any different outcome.

**Comment by Dri99** [comment]
> This can be closed.
> 
> I guess there is a bug in Android 11 and Accessibility. I had to disable one app's Accessibility service to get things working.

I stumbled upon the same error, what did you do to fix it? I still have it on android 12
