### ISSUE TITLE
(Wii/GC) Aspect Ratio Index is ignored at start-up

### ISSUE THREAD

**Issue by SuperrSonic** [libretro/RetroArch#1406]
I have gone through 200 commit pages unfortunately I couldn't find the actual commit that changes this behavior because it was working in 0.9.9 but it later stopped working, I made a simple timeline that could help find the commit that causes this by trimming down unrelated commits.

- Current source broken.
- May 31 '14 commits, broken.
- Which commit broke it: 
- May 3 '14 commits, still works.
- March 9 '14, commit marked 1.0.0.2 still works.

I was trying to find the commit that broke it by compiling each time I could but in between May 31 and May 3 compiling just gives a code dump when loading on the Wii or a compile error.

Aspect ratio index only activates when using 'load content' which is undesirable if using an external GUI like WiiFlow or the System Menu to launch games directly.

**Comment by fr500** [comment]
Please test on the current code, and reopen if the issue persists
