### ISSUE TITLE
Build Error When Compiling

### ISSUE THREAD

**Issue by TheRhysWyrill** [libretro/RetroArch#14060]
## Description

Getting a build error relating to `netplay_frontend.c` since commit [7e798d0](https://github.com/libretro/RetroArch/commit/7e798d04ba16fb449df36f44f6808df20030ced9).

### Expected behavior

For RetroArch to build without issue.

### Actual behavior

Gets so far into the build process then errors out with a `potentially uninitialized local pointer variable "connection" used` on line 3394.

### Steps to reproduce the bug

1. Download latest master.
2. Attempt to build in VS.

### Bisect Results

The build error appears to be related to this commit: [7e798d0](https://github.com/libretro/RetroArch/commit/7e798d04ba16fb449df36f44f6808df20030ced9).

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.10.3/[fcf8d2e](https://github.com/libretro/RetroArch/commit/fcf8d2e5b7892b10a701c5ddcc00a77ad80e1611)]

**Comment by Cthulhu-throwaway** [comment]
Odd... Compiled just fine on MinGW and gcc. And all pipelines passed.

I'll take a look.

**Comment by Cthulhu-throwaway** [comment]
Should be fixed. Could you please confirm and update/close this issue?
