### ISSUE TITLE
Cannot compile picodrive on Debian Jessie

### ISSUE THREAD

**Issue by kalehrl** [libretro/RetroArch#1407]
Hello guys
I'm unable to compile picodrive on Debian Jessie.
The error I get is:

80   -c -o cpu/fame/famec.o cpu/fame/famec.c
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
<builtin>: recipe for target 'cpu/fame/famec.o' failed
make: *** [cpu/fame/famec.o] Error 4

I successfully compiled several cores and retroarch.
Do you have any ideas what may be causing it?
Thank you

**Comment by kalehrl** [comment]
I solved it by assigning 2GB of RAM to the virtual machine.
I had 1GB previously which wasn't enough.
Compiling this core is very demanding.
Please mark as solved.

**Comment by Alcaro** [comment]
As you wish.

In the future, please file bugs only related to one core under the repo for that core. This one fits better [here](https://github.com/libretro/picodrive).

**Comment by kalehrl** [comment]
I tried it there but there is no 'Issues' tab on the right.

**Comment by Alcaro** [comment]
What. That's an issue on its own. (Unfortunately that too is hard to report.)

Fixed.
