### ISSUE TITLE
[Feature Request] Better visual uniformity for savestate screenshots in the Ozone UI

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#14077]
## Description

I'm opening this thread to list a few visual nitpicks I have noticed with regards to the savestate screenshots in Ozone, which were implemented with PR https://github.com/libretro/RetroArch/pull/14068 by @sonninnos.

1. As also noted by @bslenul on Discord, when opening any playlist entry with an assigned boxart, highlighting the savestate slot option in the Quick Menu will quickly flash the boxart (for a split second) before revealing the actual savestate screenshot.

2. Right now there is almost no fade-in animation when the sidebar containing the savestate screenshots is displayed, resulting in a very abrupt and jarring transition. The sidebar just appears suddenly when highlighting the savestate options, only to vanish just as suddenly when moving to another menu entry. This feels particularly inconsistent and "jerky" because of it being the only example of the Ozone sidebar popping up without any fading effect.

3. Speaking of consistency, there are several issues with the current alignment and size of the sidebar used for the savestate screenshots. 

Take a look at the following pictures for further reference. These are all taken with:

- Desktop Resolution set to 1920x1080;
- Settings -> User Interface -> Appearance -> Menu Scale Factor set to "0.78x" (my preferred value for my main monitor);
- Settings -> User Interface -> Appearance -> Thumbnail Scale Factor set to "1.50x".

**Normal playlist sidebar** - With the aforementioned settings, sidebar width is about **440px**

![Screenshot 2022-06-20 225519](https://user-images.githubusercontent.com/17614150/174676621-cf4f3e6f-22a2-4fca-a130-f4208132141c.png)

**Savestate Screenshot sidebar** - With the aforementioned settings, sidebar width seems to be at least **500px**

![Screenshot 2022-06-20 224443](https://user-images.githubusercontent.com/17614150/174677337-85be104e-0fba-4cc1-9f05-4dc29b92b2a6.png)

The screenshot is not aligned with the UI header lines (at the top of the interface), contrary to the playlist thumbnails/boxart. It also seems to be positioned strangely relative to the other Ozone UI elements, with lots of padding.

![Screenshot 2022-06-20 224443](https://user-images.githubusercontent.com/17614150/174677432-7a669c55-dd2b-4ba7-a30a-b8024ee94905.png)

**Comment by sonninnos** [comment]
I have 1 and 2 now sorted, but no idea if 3 is plausible yet.

**Comment by sonninnos** [comment]
Right padding and mouse hovering also sorted.

**Comment by Ryunam** [comment]
Thank you so much for working so quickly on this! Very much appreciated as always.
