### ISSUE TITLE
RetroArch freezes my PS3

### ISSUE THREAD

**Issue by Windows10User2** [libretro/RetroArch#14071]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

No matter what I do RetroArch freezes my PS3. I tried formatting the HDD, change it, reinstall CFW, reinstall RetroArch, and even tried another PS3 to no avail.

### Expected behavior

To not freeze the PS3

### Actual behavior

Whenever running RetroArch on the PS3, the latter freezes and doesn't answer to my controller's inputs.

### Steps to reproduce the bug

Just running RetroArch randomly.

### Bisect Results

When I used RetroArch for the first time on the PS3, in 2018.

### Version/Commit
You can find this information under Information/System Information

- RetroArch 1.9.0, RetroArch Community Edition (beta04) and RetroArch CE (unofficial beta updated 2022-03-11).

### Environment information

PS3 CFW Evilnat 4.89.

- Compiler: [In case you are running local builds]

**Comment by LibretroAdmin** [comment]
Version too old, retest with master.

**Comment by Windows10User2** [comment]
> Version too old, retest with master.

What's master? I tested the following two unofficial releases mentioned in Brewology after that and I still had the problem but currently I'm not having it.
