### ISSUE TITLE
Is there are open source Philips CDi emulators

### ISSUE THREAD

**Issue by Squidward22** [libretro/RetroArch#14076]
I don't know is Philips CDi more powerful than Windows, Android, PlayStation Portable, PlayStation Vita, iOS / iPad OS, macOS

Is there are Philips CDi emulators (open source).

![CD-i-910-Console-Set](https://user-images.githubusercontent.com/107685666/174648363-c50d1629-ad6e-4293-9207-c013ce774727.png)

**Comment by hizzlekizzle** [comment]
There are 2 that are both based on MAME's CDi emulation (here is one of them: https://github.com/libretro/same_cdi). This is not a RetroArch issue, though, so this ticket should be closed.
