### ISSUE TITLE
Feature request: Add network support to RetroArch for Open Dingus Beta (OpenDingux (GCW Zero/RG350M/RG280V/others))

### ISSUE THREAD

**Issue by SuperBadger77** [libretro/RetroArch#14083]
# First and foremost consider this:
This is a feature request.

## Description
The Adam image is a hugely popular distro that uses RetroArch at its core. It currently uses the Open Dingus Beta for GCW Zero/RG350M/RG280V/others devices. The distro has support for wifi dongles, but the current buikld of Open Dingus Beta does not have networking built in. COuld I request that networking support to be added to Open Dingus Beta - that would then allow the support for Retro Achievements when users connect to wifi via the GCWConnect app.

https://github.com/eduardofilo/RG350_adam_image/discussions/259 discussion on wifi donlges.
https://github.com/eduardofilo/RG350_adam_image/wiki/En:-7.-FAQ#q9-is-it-possible-to-use-a-wifi-dongle supported dongles.

### Expected behavior

Network support to work and user able to access Retro Achievements via RA.

### Actual behavior

Networking not supported in. RA on Open Dingus Beta.

- RetroArch: [version/commit]

### Environment information
Adam Image v1.0-2.0 on any supported devices: RG350M/RG280V etc.

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway How feasible would this be?

If you lack the hardware necessary, I'd be willing to buy it for you in case the interest is there. A lot of people are buying these handhelds recently, it's a big userbase for us.

**Comment by Cthulhu-throwaway** [comment]
Not interested. Besides, these devices are pretty weak and can't support netplay.

**Comment by LibretroAdmin** [comment]
Actually, a lot of those Anbernic devices are quite more powerful than a PS Vita or 3DS when it comes to CPU performance.

**Comment by zoltanvb** [comment]
Judging from the linked PR, this should be resolved now.
