### ISSUE TITLE
[iOS] Latest nightlies (6/21 onwards) open to an error on iOS when using the metal driver on the ios-arm64 build

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#14094]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Latest nightlies (6/21 onwards) open to an error on iOS using the iso-arm64 build. Issue starts between the 6/20 nightly build and the 6/21 nightly build

### Expected behavior
Using the 6/20 nightly build (and earlier), RetroArch opens as expected:

![IMG_0396](https://user-images.githubusercontent.com/25250513/175317482-27297883-43ca-4e5b-b5d7-977e52148de1.PNG)

### Actual behavior

Using the 6/21 nightly build (and later), RetroArch opens to a black screen with garbled text:
![IMG_0395](https://user-images.githubusercontent.com/25250513/175317663-861393a6-7c75-4ba5-ac72-3aeb477525c9.PNG)

### Bisect Results

Issue begins between the 6/20 and 6/21 nightly builds of ios-arm64. After installing a nighlty from 6/21 onwards, reverting to a 6/20 or earlier build resolves the issue. 

### Environment information

- OS: Both iOS and iPadOS 15.5
- Compiler: From build bot

**Comment by trotsky40** [comment]
Adding screenshot from an iPhone so it is easier to see the garbled text.
![IMG_0564](https://user-images.githubusercontent.com/25250513/175323391-77527425-9b51-4fd9-b685-c4d95e1448cb.PNG)

**Comment by LibretroAdmin** [comment]
See if this fixes it -
https://github.com/libretro/RetroArch/commit/41a073da731c90b5e4369998b3f7fad7de5594bb
