### ISSUE TITLE
[Issue] Thumbnails are squashed in GLUI in latest nightlies

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#14144]
Starting with the 7/3 nightly, thumbnails on all playlists (system, history, favorites) are intermittently squashed (will occasionally appear correctly and then revert to squashed). This can be fixed by reverting to the 7/2 nightly. Potentially related to this commit: https://github.com/libretro/RetroArch/pull/14139

NES playlist using the current nightly:
![IMG_0397](https://user-images.githubusercontent.com/25250513/177180153-1db60417-a770-4b7c-bab8-9e3e0741fc22.PNG)

NES playlist using the 7/2 nightly:
![IMG_0398](https://user-images.githubusercontent.com/25250513/177180199-d2c80cda-ab4b-433b-b3c6-92d44af415fa.PNG)

**Comment by trotsky40** [comment]
The issue is across platforms using the GLUI. I was able replicate with GLUI on Windows and Android  

Andriod example:
![Screenshot_20220704-083820](https://user-images.githubusercontent.com/25250513/177186332-b8ab6240-1b37-4f84-950e-2f863abafede.png)

**Comment by LibretroAdmin** [comment]
@trotsky40 Check if this resolves the issue.

**Comment by trotsky40** [comment]
Confirmed fixed. Thank you!

**Comment by mrmatteastwood** [comment]
Hey @sonninnos, thanks for your awesome work! I'm beyond excited to finally have savestate thumbs in Ozone. It seems like this issue needs to be reopened though. Savestate thumbnails are squashed when using the Mega Bezel shaders. Example using the Glass preset:

![Screenshot from 2022-10-02 12-10-19](https://user-images.githubusercontent.com/22120259/193469897-d1cd9e13-4c93-46aa-b6fe-603b1226c3be.png)

For reference, this is the same screenshot from the actual game:

![Cool Spot (Europe)-221002-121104](https://user-images.githubusercontent.com/22120259/193469917-98a40015-78d3-4a70-8f27-b1d26618151f.png)

RetroArch 1.11.0 on Linux Mint 22.

**Comment by sonninnos** [comment]
Because the thumbnail is using current core pixel aspect, not 1:1, because it is supposed to be the raw output without any post effects. So how can that thumbnail have a part of RA widget visible.. Also the menu driver you are using is not GLUI.

**Comment by mrmatteastwood** [comment]
Ahh, ok. So there's no way to make the thumbnails use the aspect ratio set in RA Settings > Video > Scaling > Aspect Ratio?

Sorry, you're right, this is the wrong issue thread to report this in. Should have opened a new one.

**Comment by sonninnos** [comment]
Nah, the reason is because the thumbnail is saved wrongly, as in it obeys `video_gpu_screenshot` even if it should not.

**Comment by mrmatteastwood** [comment]
Gotcha. Is this something you can address? I'll be happy to open a separate issue for it with proper STR etc.

**Comment by sonninnos** [comment]
Sure, I'm on it.
