### ISSUE TITLE
[Core Info] core_info_current_supports_netplay not working as expected

### ISSUE THREAD

**Issue by Cthulhu-throwaway** [libretro/RetroArch#14159]
## Description

The data required for this function to work seems to be initialized after event_init_content, which is where netplay initializes itself.
Older versions would work as long as the content was loaded before starting netplay, but now that netplay always enforces content reload, we can no longer fail netplay initialization on some unsupported cores.

### Expected behavior

The data for this function should be initialized before or during event_init_content.

### Actual behavior

The data will be uninitialized during init_netplay,  and the function will always return true.

### Steps to reproduce the bug

1. Start netplay.
2. Load an unsupported core with savestate support (MAME, bsnes, etc).
3. Netplay should fail here with a "core not supported" notification, but instead, it completes initialization on an unsupported core.

### Version/Commit

- RetroArch: [1.10.3/ef022ff]

### Environment information

- OS: Windows 7

@jdgleaver If I recall correctly, you were the one who wrote those functions.

**Comment by Cthulhu-throwaway** [comment]
I think the problem is caused by calls to CMD_EVENT_CORE_INFO_INIT deinitializing it without calling core_info_load afterwards.

**Comment by luizaoooobr** [comment]
Please, due to core_info_current_supports_netplay function, core mame2003_plus and fbalpha2012 lost network game support, so we can no longer play network hack roms like street fighter 2 mix and Street Fighter Alpha 3 mix.

**Comment by hizzlekizzle** [comment]
You can always override that by just changing it in your core info file locally.

**Comment by LibretroAdmin** [comment]
> Please, due to core_info_current_supports_netplay function, core mame2003_plus and fbalpha2012 lost network game support, so we can no longer play network hack roms like street fighter 2 mix and Street Fighter Alpha 3 mix.

Hmm any thoughts here @Cthulhu-throwaway ?
