### ISSUE TITLE
Error saving remap files (Wii U Tiramisu)

### ISSUE THREAD

**Issue by WillLem** [libretro/RetroArch#14150]
## Description

"Error saving remap files" on Wii U version of RA. This is in spite of setting the correct Directory for Input Remaps, and checking that the folder exists

### Expected behavior

Remap files can be saved successfully when a folder has been specified in Settings/Directory

### Actual behavior

An error message pops up when trying to save remaps

### Steps to reproduce the bug

1. Load RA from a Wii U
2. Load any game
3. Access RA menu by pressing Home button. Navigate to Quick Menu/Controls
4. Change any controller setting (e.g.Port 2 Controls > Mapped Port from 2 to 1)
5. Go to Manage Remap Files > Save (any) Remap File
6. "Error saving remap file" is displayed

### Bisect Results

This has been happening since I started using RetroArch a few days ago

### Version/Commit

RetroArch 1.10.3 / May 2 2022 / 102abb0

### Environment information

- OS: Tiramisu CFW on Wii U (sorry, not sure which version but it is the latest, downloaded a few days ago (It's 6/7/22)!

**Comment by atmavan** [comment]
any luck on resolving the issue?

**Comment by LibretroAdmin** [comment]
I keep mentioning it to @QuarkTheAwesome and @gblues but alas.

**Comment by WillLem** [comment]
> any luck on resolving the issue?

Yes! If you read this thread on GBATemp from [here](https://gbatemp.net/threads/retroarch-wiiu-wip.447670/post-9873809), there is some useful information on various workarounds, plus a solution that worked for me. Good luck!

**Comment by LibretroAdmin** [comment]
Can you check if this is resolved by the PR @gblues pushed - fixing mkdir on WiiU?

**Comment by Ploggy** [comment]
This issue can be closed :)
