### ISSUE TITLE
[Feature Request] Module Kaillera for NetPlay (EPSXE. PCSX2)

### ISSUE THREAD

**Issue by ZzackKbin** [libretro/RetroArch#14166]
Hello
Can You add support for Kaillera in Retroarch? Is good way to play in internet for PSX/PS2 games using epsxe/pcsx2. 
Or add support like kaillera for PSX/PS2 cores. 

Thx.

**Comment by Cthulhu-throwaway** [comment]
Won't fix (at least from me).

1. ePSXe is not a libretro core.
2. PCSX2 is considered an alpha core in libretro at the moment.
3. Stateless mode was broken, as in, it would not work at all, so I hid the option from the menu. I do not play platforms that do not support rollback netplay and as such, I've little to no interest in rewriting stateless mode.
4. Use a streaming-based service for netplaying on cores that do not support rollback netplay (Parsec, Steam's Remote Play Together, etc).

NOTE: I've considered implementing RetroArch's own streaming netplay through a core so you could use it together with features such as shaders aswell as reducing bandwidth by sending the frame to clients at its internal resolution.
Lack of infrastructure resources and already well established streaming platforms are making me avoid spending a huge amount of time implementing this, while I don't even netplay on cores that do not support rollback.

**Comment by ZzackKbin** [comment]
I tested steam service and streaming is good for pc  but not RPi4 :(
"Open Kaillera Reborn" has also p2p client and now has more then 50 players on servers.
SDK is on https://kaillerareborn.github.io/  Sources I  saw on Discord. 
If you find few free moments look at Open Kaillera Reborn. I miss PSX online for retrorach. 

Have nice day.

**Comment by Cthulhu-throwaway** [comment]
From the page you linked:
`the client is embedded into the emulators`

So not feasible. Each emulator needs to be supported inidivually, in this case, each libretro core (https://krb.myftp.org/src/).

Have you tried parsec? https://support.parsec.app/hc/en-us/articles/115002699012-Setting-Up-On-Raspberry-Pi-Raspbian-

**Comment by ZzackKbin** [comment]
presca is another streaming :(  At this moment for PSX online I stay with windows and kailierra, better input lag and graphics. 

Thx for answer.

**Comment by Cthulhu-throwaway** [comment]
Have you also tried RetroArch's rollback netplay with either Beetle PSX (non-hardware version) or PCSX-ReARMed? Both of these are listed as deterministic in the core info files, which is what is required for netplay. PCSX-ReARMed might be light enough that rollback netplay is not going to impact performance much.

**Comment by ZzackKbin** [comment]
I will test it tomorrow :)

**Comment by ZzackKbin** [comment]
I tested rearmed/swanstation. I can create host and friend can join to my game but retroarch crash or disconnect player. One time I saw even few seconds connection but with big lag :(
PSX online doesn't work.

**Comment by Cthulhu-throwaway** [comment]
Swanstation will not work, it's not deterministic.

Can you enable logging in Settings -> Logging and tell me what error shows up in the log when the disconnection happens with pcsx?

**Comment by ZzackKbin** [comment]
I tested standalone version and steam for windows and now I dont see any file with logs :(
I try do it in next week.

**Comment by ZzackKbin** [comment]
Ps
I see Commodore - Amiga (PUAE)  also doesn't support netplay :(
Winning Eleven and SWOS are the best part of multi games.

**Comment by fr500** [comment]
> Have you also tried RetroArch's rollback netplay with either Beetle PSX (non-hardware version) or PCSX-ReARMed? Both of these are listed as deterministic in the core info files, which is what is required for netplay. PCSX-ReARMed might be light enough that rollback netplay is not going to impact performance much.

I tried this, even on ARM were it's faster and... no way, PCSX-ReARMed worked full speed with 5 seconds hitches every time the states were compared. There was a savestate exchange every single time

**Comment by Cthulhu-throwaway** [comment]
> I tried this, even on ARM were it's faster and... no way, PCSX-ReARMed worked full speed with 5 seconds hitches every time the states were compared. There was a savestate exchange every single time

3D game? I don't think we will ever be able to support an universal rollback implementation on a real 3D game. There are simply way too many variables that can lead to desync (forcing savestate exchanges way too often, as you experienced them yourself), like someone moving the camera with the analog stick.
My suggestion mainly focus on 2D games that have a reasonable sized savestate.

It's also important to note that not even Swanstation's internal runahead works well with 3D games.

**Comment by ZzackKbin** [comment]
Today netplay start working with another person on rearmed core but with high ping. Netcode has teleports.

**Comment by Cthulhu-throwaway** [comment]
> Today netplay start working with another person on rearmed core but with high ping. Netcode has teleports.

"Teleports" are rollbacks. See my comment above.
Also make sure that all peers are running netplay at the same framerate, otherwise slowdowns and rollbacks are going to be a thing.

**Comment by ZzackKbin** [comment]
This netcode looks like blind alley. Today was played in Tekken 3 with open kaillera and works fine but this is only for windows and my rpi4 is still waiting :P

**Comment by Cthulhu-throwaway** [comment]
Obviously, Kaillera isn't rollback based. You are comparing apples and oranges.

There is no rollback service that properly supports PSX as far as I know.
[Mednafen uses savestates](https://mednafen.github.io/documentation/netplay.html), but only on connection, thus, not a rollback system.

**Comment by ZzackKbin** [comment]
I am end-user. I want just play online on my RPi4 in PSX games like Tekken 3 Winning Eleven CTR :)

Mednafen is not easy for many players.

**Comment by Cthulhu-throwaway** [comment]
@ZzackKbin further analysis of the netcode shows that PCSX-ReARMed and/or Beetle PSX (non-hardware version) might work with 3D games, if the host sets "Netplay Check Frames" high enough.

If running at 60 fps, try setting it at 3600; that's syncing every minute.
Alternatively, you can set "Netplay Check Frames" at 0 and savestates will only be sent when someone joins; there won't be any form of syncing though, unless someone joins.

**Comment by ZzackKbin** [comment]
thx for information.

**Comment by ZzackKbin** [comment]
Maybe is stupid question but is fast way to set "Netplay Check Frames" on 3600?

**Comment by Cthulhu-throwaway** [comment]
> Maybe is stupid question but is fast way to set "Netplay Check Frames" on 3600?

Probably not from inside's RetroArch menu.
However, you can open retroarch.cfg and change:
`netplay_check_frames = "3600"`

**Comment by Cthulhu-throwaway** [comment]
https://github.com/libretro/RetroArch/pull/14320

This should make it easier to set higher values through the menu by typing the value out.

**Comment by ZzackKbin** [comment]
thx

**Comment by Doomguard45** [comment]
its possible make RetroArch with kaillera, and it will work with most popular systems (PUAE too if disable random in code).
not keyboard systems or multithread cores

**Comment by ZzackKbin** [comment]
> @ZzackKbin further analysis of the netcode shows that PCSX-ReARMed and/or Beetle PSX (non-hardware version) might work with 3D games, if the host sets "Netplay Check Frames" high enough.
> 
> If running at 60 fps, try setting it at 3600; that's syncing every minute. Alternatively, you can set "Netplay Check Frames" at 0 and savestates will only be sent when someone joins; there won't be any form of syncing though, unless someone joins.

Hi I tested and:
-PCSX Rearmed is total broken out of sync
-Beetle PSX work 

On lan ping is 16 but with internet friend is 360 and we both are from middle Europe.
