### ISSUE TITLE
[Feature Request] Add decaf core

### ISSUE THREAD

**Issue by jonasrhee1208** [libretro/RetroArch#14179]
I want decaf core, and also netplay support with it because I want to play Wii U games that I have lying around, but use retroarch for it.

### Expected behavior

A decaf core with netplay

### Actual behavior

nothing.

**Comment by ichee** [comment]
You may have better luck with a core request in the forums, located at https://forums.libretro.com.

Open topic for core requests is at https://forums.libretro.com/t/core-and-feature-requests/5895.

**Comment by LibretroAdmin** [comment]
Core requests fall out of scope for this issue section. This is about RetroArch-related issues only.
