### ISSUE TITLE
Monitor refresh incorrectly reported on Nvidia Optimus graphics

### ISSUE THREAD

**Issue by vgf89** [libretro/RetroArch#1418]
When Retroarch is started with "High performance NVIDIA processor", the monitor refresh is incorrectly reported (600+ Hz).

That is an issue itself, but there is a very bad side effect which shouldn't exist regardless of this problem: **scrolling acceleration appears to be locked to the framerate/refresh rate** (this might need to be a separate issue, idk). When using Retroarch with Nvidia graphics, scrolling with any controller or keyboard button is incredibly fast which makes the menus nearly impossible to use.

This happens on every build I've tried, including the current stable build, beta build, and current nightlies.

My setup:
Windows 8.1
Lenovo Y510P (integrated intel GPU, discrete Nvidia 750m)
NVIDIA driver 347.09

**Comment by twinaphex** [comment]
Appears to me that there is some setting enabled in your nvidia control panel that is conflicting badly with RetroArch's A/V sync. It probably is a nasty hack that is probably wrongly advertised as an 'optimization'.

**Comment by vgf89** [comment]
I figured out which setting is causing it. V-Sync must be set to On or Application-Controlled in the Nvidia Settings. If V-Sync it turned off in the Nvidia settings is freaks out. Retroarch's V-Sync settings don't seem to change the behavior.
