### ISSUE TITLE
Re: Error in shader (with easy fix)

### ISSUE THREAD

**Issue by jonespianist** [libretro/RetroArch#14194]
## Description

This is a response to [a now-closed thread](https://github.com/libretro/RetroArch/issues/11741) about the Neo Geo Pocket border shaders not being displayed in the correct size and aspect ratio. The supposed fix that was submitted through that thread only concerned the 3x variant of the border, and even then, it didn't work properly for me. (I use the 5x variant instead because the 3x variant is too small on my computer.)

### Expected behavior

The border is displayed at the correct size and aspect ratio, with none of the game image being cut off.

### Actual behavior

The game image isn't cut off, but now the border is too big.

### Steps to reproduce the bug

Change "border_zoom_x = 0.70" to "border_zoom_x = 0.33", and "border_zoom_y = 0.79" to "border_zoom_y = 0.62" in ngpc-3x.slangp or ngpc-3x.glslp, then run any Neo Geo Pocket game.

### Bisect Results

Since there was no equivalent fix for any variants other than 3x, I used a calculators to get approximations for the other variants:
1.05:1.18 to 0.50:0.93 (ngpc-2x)
0.70:0.79 to 0.33:0.62 (ngpc-3x)
0.52:0.59 to 0.25:0.46 (ngpc-4x)
0.42:0.47 to 0.20:0.37 (ngpc-5x)
0.35:0.39 to 0.17:0.31 (ngpc-6x)
The result with the 3x and 5x variants was this:
![Cotton - Fantastic Night Dreams (Europe)-220721-121318](https://user-images.githubusercontent.com/109748293/180273905-48256492-6111-45be-85cb-f31bb7adfd45.png)

![Cotton - Fantastic Night Dreams (Europe)-220721-120704](https://user-images.githubusercontent.com/109748293/180272902-8c7d3ef1-dda6-4858-ad38-b785b62e2499.png)

Once I realized the fix didn't work right for me, I doubled the borders' parameters:
0.50:0.93 to 1.00:1.86 (ngpc-2x)
0.33:0.62 to 0.66:1.24 (ngpc-3x)
0.25:0.46 to 0.50:0.92 (ngpc-4x)
0.20:0.37 to 0.40:0.74 (ngpc-5x)
0.17:0.31 to 0.34:0.62 (ngpc-6x)
This plan almost worked, but then the game image was cut off again--this time by 5 pixels horizontally and 4 pixels vertically.
![Cotton - Fantastic Night Dreams (Europe)-220721-121030](https://user-images.githubusercontent.com/109748293/180274121-9caa71d4-a2c8-4c2f-987a-222419d73c34.png)

![Cotton - Fantastic Night Dreams (Europe)-220721-113046](https://user-images.githubusercontent.com/109748293/180272177-db248998-29e3-4448-b7dd-30d034979822.png)

Until now, no one has reported any problems with the fix mentioned in the original thread since it was closed, which leads me to believe I'm one of the very few people--if there are others--who had any problems with it.

### Version/Commit

- RetroArch: 1.10.3

### Environment information

- Base OS: Windows 11
- Frontend OS: Windows 8 x64 build 9200 (v6.2)
- Native resolution: 2240*1400
- Compiler: MinGW (10.2.0) 64-bit

**Comment by hizzlekizzle** [comment]
This is a shader error rather than a RetroArch one, so probably better to report it at https://github.com/libretro/slang-shaders/issues.

I've been meaning to PR another fix, so I'll just switch these over to the same gb-pass-5 shader that the others use and that should fix it up.

**Comment by jonespianist** [comment]
> This is a shader error rather than a RetroArch one, so probably better to report it at https://github.com/libretro/slang-shaders/issues.
> 
> I've been meaning to PR another fix, so I'll just switch these over to the same gb-pass-5 shader that the others use and that should fix it up.

Thanks for the PR. This has been a problem for who knows how long.
I also appreciate you pointing out that mistake. I only just signed up specifically because of this issue.

**Comment by jonespianist** [comment]
The .files for these shaders have been updated, but not the .glslp or .slangp files.
Why this is the case, I have no idea. The .cgp files weren't available to me; and even if they were, they've been deemed outdated for quite some time now.

**Comment by hizzlekizzle** [comment]
Just FYI, there's a PR ready to go to fix this, but it depends on some changes in RetroArch, so we'll merge it once there's a new stable release of RetroArch.
