### ISSUE TITLE
Automatic frame delay does not work correctly with Mupen64Plus and bsnes

### ISSUE THREAD

**Issue by nfp0** [libretro/RetroArch#14201]
## Description

Automatic frame delay does not adjust correctly with some cores, such as Mupen64Plus and bsnes.
When enabled, and when "video_frame_delay" is set to a high enough value, the effective frame delay gets lowered below the target, but not enough to prevent the game from slowing down and prevent continuous audio crackling. The FPS value also goes down.

The games play at full speed and with perfect audio if frame delay is disabled or set lower, ruling out any lack of processing power.

### Expected behavior

Automatic frame delay should kick in and lower the effective frame delay to a value that can sustain the game at full speed in all cases.

### Actual behavior

Automatic frame delay kicks in, but does not lower the effective frame delay enough, resulting in audio crackling and game slowdown on some cores such as bsnes-mercury and Mupen64Plus-Next.

### Steps to reproduce the bug

1. Enable Automatic Frame Delay and set Frame Delay to a high value, such as 15.
2. Open a heavy scene in a game, such as the first level of 007 Goldeneye or the initial cutscene in Pokemon Snap in Mupen64-Plus-Next set up with ParallelRSP and ParallelRDP. Alternatively, open the start screen of Yoshi's Island on bsnes-mercury.
3. Observe game slowdown and audio crackling.

### Version/Commit

- RetroArch: 1.10.3

### Environment information

- OS: Manjaro Linux

**Comment by Cthulhu-throwaway** [comment]
@sonninnos

**Comment by sonninnos** [comment]
Can't be fixed if the core is offering inconsistent frame times.

**Comment by nfp0** [comment]
@sonninnos I have confirmed that the games I've tested run at full speed with perfect audio when not using any frame delay.
But these same games have slowdown and crackle when I enable Auto Frame Delay, which should not be possible. Auto Frame Delay is not doing it's job in this situation.

Also, I've tested with shaders enabled and disabled, and the situation is the same.

Can you not reproduce this issue on bsnes-mercury (balanced) on Yoshi's Island's title screen? It's pretty noticeable when enabling Auto Frame Delay and increasing Frame Delay to a big value, such as 15.

**Comment by sonninnos** [comment]
Like I said, it crackles for a while until it drops to a safe value.

**Comment by nfp0** [comment]
Not the case here. It never drops to a safe value. The crackling continues indefinitely. I can reproduce it easily every time.
I have both my CPU and GPU at high-power profiles, btw.

**Comment by sonninnos** [comment]
Is it possible that you have some kind of adaptive vsync forced in the drivers? It did not occur to me since vulkan was involved, and since there is no adaptive vsync option in RA for it, but only for gl.

Having it enabled absolutely causes similar results. Also make sure `video_refresh_rate` is as close to display refresh rate as possible.

**Comment by nfp0** [comment]
@sonninnos The adaptive sync (G-Sync/Freesync) option on RetroArch is available for both GL and Vulkan. But no, I'm not using it. And `video_refresh_rate` is set correctly.

Regardless, I'll force-disable adaptive sync on the compositor (I'm using KDE), and see if I get different results.

**Comment by sonninnos** [comment]
VRR is not the same as Adaptive VSync, which only exists with gl and glcore in RA under Video > Synchronization.

**Comment by nfp0** [comment]
My bad. I thought you were talking about VESA's Adaptive-Sync.
I believe Adaptive VSync is an Nvidia specific thing. I have an AMD card and I believe the equivalent is Enhanced Sync.
Regardless, no, I'm not using either. I don't believe those driver settings are available on the Linux drivers, and if they are, I never enabled them.

**Comment by nfp0** [comment]
@sonninnos  Here's an example of the issue:

![image](https://user-images.githubusercontent.com/11202422/200088301-a874bf82-11bc-4eb3-94b1-f83e56162de9.png)

Auto-frame-delay lowered the frame-delay value to 12ms but it should go further down to achieve full speed. Notice that the framerate is stuck at 57 fps. This causes the game to run slower and with lots of audio crackling.

**Comment by sonninnos** [comment]
Ok, then I'm afraid I'm out of ideas what is making the calculation think the rate is solid.. That frame time and rate should absolutely be triggering the delay reduction.

**Comment by nfp0** [comment]
![IMG_20221105_155801](https://user-images.githubusercontent.com/11202422/200128825-d08217a0-74b7-4865-99f1-3d9d979e12d7.jpg)

@sonninnos  Could it be related to this huge frame time deviation? (Sorry for the photo, but taking a printscreen ruins the frametime graph).

Notice how the max frametime is stuck at 26ms and the frame time deviation is 38%. A minimum frametime of 3ms also doesn't look normal. This is with all frame delay features disabled.
Sometimes auto-frame-delay reduces it back to zero, which is kinda expected because 24ms is way higher than 16,6ms.

When that happens get this on the log:
```
[INFO] [Video]: Frame delay decrease by 1 ms to 14 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 13 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 12 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 11 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 10 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 9 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 8 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 7 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 6 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 5 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 4 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 3 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 2 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 1 ms due to frame time: 24999 > 16666.
[INFO] [Video]: Frame delay decrease by 1 ms to 0 ms due to frame time: 24999 > 16666.

```

Other times it just stays at a frame delay value not enough to reach full-speed, as seen on my post above here: https://github.com/libretro/RetroArch/issues/14201#issuecomment-1304332576

I've tested this on Mupen64Plus (with Parallel RDP and RSP), bsnes-mercury balanced, Mesen, and mGBA. This huge frame time deviation is present on all of them.
What is causing this? Is this level of deviation normal on RetroArch?

**Comment by sonninnos** [comment]
That kind of deviation is absolutely not normal. I get a rock solid line with all drivers (vulkan/glcore/d3d11).

Still the delay should decrease when it is not solid, but I did have to add some exceptions for the way different drivers deal with frameskips, because the whole logic is based on frametime averages.. So you must be hitting some kind of sweet spot where the average seems not bad enough.

That basic log won't help, so please do try to compile RA with that debug flag enabled.

**Comment by nfp0** [comment]
Funny thing is the real-life frametime is perfectly smooth. There's absolutely no stutter. I can validate it by looking at the scroll test on the 240p test suite. I also recorded a 480fps (8 frames for each game frame) slow-motion video where you can see the perfect cadence of the frames on the clouds in the background despite the frametime deviation. Those numbers do not correlate at all with what I see on-screen.

https://user-images.githubusercontent.com/11202422/200138970-cd27bbb2-81f1-4868-bc54-3292bade2783.mp4

Tested it on both X and Wayland.

**Comment by nfp0** [comment]
> I get a rock solid line with all drivers (vulkan/glcore/d3d11)

Is that on Windows?

> That basic log won't help, so please do try to compile RA with that debug flag enabled.

@sonninnos Aight, I'll do that as soon as I can.

**Comment by sonninnos** [comment]
Yes I'm using W10. I can't even get vulkan or glcore working in Linux VM, only gl.

**Comment by nfp0** [comment]
Oh, yeah, a VM will have all kinds of problems when it comes to running GPU programs.

So, has anyone tested this feature on Linux? Do you know anyone who has rock-solid frametime lines on Linux?

I believe the issue is that frame-time values might not be accurate. If you think about it, it's not possible to have frame-times of 20ms when all the frames are being delivered perfectly within the 16ms window, or is it?

**Comment by sonninnos** [comment]
No other actual Linux user has complained about it yet, and yes it has been tested on various hardware such as RPi.

And sure, there is no way for the average calculations to be reliable if the frame time values are not reliable. So fixing the frame time issue also fixes the autoframedelay issue. No idea where to start though.

**Comment by nfp0** [comment]
> Most likely something to do with GPU drivers and/or OS compositor.

Quite probably, as I've noticed this "seesaw" frame-time pattern on other games too, even though they're visually smooth.

I would just set the frame delay manually, but using hardcore mode on Retroachievements forces me to have auto-frame-delay on. :disappointed: 

I'll ask around on Discord or on the forums to see if other Linux users have this same issue.

**Comment by sonninnos** [comment]
Let's hope these new changes solve your problems too, since I discovered a few cases for myself that got the delay calculation stuck.

**Comment by nfp0** [comment]
Nice, I'll try it out when I get the chance.
Thanks!

**Comment by sonninnos** [comment]
Something is seriously wrong with the presentation/buffering in your system then. I can't make more exceptions for the frame delay to drop in those cases, if it still won't, especially without the logs I wanted.

**Comment by nfp0** [comment]
Oh I'm sorry, I'm not asking for you to change the behavior anymore. I'm just trying to find the root cause of the problem on my end.

And I'm also sorry for completely forgetting to provide you the logs you asked with the debug flag.
Here you go:
[retroarch.log](https://github.com/libretro/RetroArch/files/11105070/retroarch.log)

Find anything suspicious?

**Comment by sonninnos** [comment]
Nope, because that is just a normal debug log, and not the one with the frame delay debug flag:
>All I need is a log produced when FRAME_DELAY_AUTO_DEBUG is enabled in gfx/video_driver.c.

**Comment by nfp0** [comment]
Oh my bad! I wasn't paying attention. Sorry for the trouble.

Here you go, with FRAME_DELAY_AUTO_DEBUG enabled:
[retroarch.log](https://github.com/libretro/RetroArch/files/11105513/retroarch.log)

I tested on bsnes mercury on Yoshi's Island start screen, where the frametime see-saws between 15 and 20 ms.
Goldeneye is even worse.

**Comment by sonninnos** [comment]
Thanks. Looks pretty nasty, as in the average of every 8 frame block is over the available frame time, but it is not currently averaging the averages, so it stays within the allowed margin for normal spikes..

Not impossible take into account, but might be tricky to simulate without being able to replicate, while also not breaking everything else. I'll have to revisit it at some point.

Does it still stay put the same way if you start with some other more reasonable value like 10 or 8? And what about using max swapchain 2, or a smaller audio buffer?

**Comment by nfp0** [comment]
Thank you for looking into it.
Not sure if you should change anything at all. My frametimes do not seem normal to me.

I just don't understand how can the game motion seem smooth when half the frames take 20 ms. Does this make sense?

> Does it still stay put the same way if you start with some other more reasonable value like 10 or 8? And what about trying max swapchain 2, a different shader, or a smaller audio buffer?

Tried all of those but it made no difference. I even tried the `null` audio driver but the result was always the same seesaw frametime graph.

**Comment by nfp0** [comment]
I think I now understand how it's possible for the picture to be perfectly smooth even with a seesaw frametime graph.
On the default RetroArch syncronization method, the time distance between the current frame and the previous frame is irrelevant, as RetroArch holds on to the frame until the time is right to display it.

Still, it's weird that the frames are being rendered in such an erratic way.
This is not a problem for the default RetroArch synchronization method, but when we enable VRR (Sync to exact content framerate), then the issue becomes apparent and we can see the frames being delivered irregularly. The smoothness is lost.
And it also makes it difficult to use the awesome auto frame delay feature.

So I think I'll open a new separate issue and leave this one alone, as even though it affects the auto frame delay feature, it's unrelated to it.

Thank you for the help!

**Comment by nfp0** [comment]
> That kind of deviation is absolutely not normal. I get a rock solid line with all drivers (vulkan/glcore/d3d11).

@sonninnos Could you please specify your hardware a bit?
I tested on Windows and I get about the same amount of frametime deviation than on Linux (about 14%).
I also tested on a different computer and it also gives me about the same kind of deviation.

I can never get rock solid lines like you do. What software are you using to see the frametime graph?

**Comment by sonninnos** [comment]
i5-9600K + GTX 970. I use MSI Afterburner (RTSS) for frame time graph.

**Comment by nfp0** [comment]
Thank you. I went and installed MSI Afterburner on Windows to see if the frame graph was any smoother and I got 2 different results:

OpenGL:
![IMG_20230331_132800](https://user-images.githubusercontent.com/11202422/229246046-ad5d8661-d05c-4270-9d71-8a9c3e57c6c8.jpg)

Vulkan:
![IMG_20230331_132854](https://user-images.githubusercontent.com/11202422/229246065-e132275c-8649-4f6e-aac1-66dabc6b7b20.jpg)

On OpenGL the graph is a smooth line, but on Vulkan I have the same squiggly line I get on Linux.
But more importantly, notice how the frame time deviation is about the same value on both OpenGL and Vulkan, which means MSI Afterburner might be using different methods for reading frame times between GL and Vulkan. Because of this, I'm more inclined to trust RetroArch's reported value instead.

If it's not too much trouble, could you tell me how much frame time deviation % does RetroArch (not Afterburner) report to you on Yoshi's Island startscreen on bsnes?

**Comment by sonninnos** [comment]
I get the same sawtooth with both glcore and vulkan with that core, with and without frame delay. Frame delay does eventually drop to a level where there are no frame skips or audio crackles, but it takes a while, since it is designed to forgive certain spikes, because otherwise some other cores drop too suddenly.

Snes9x has barely any deviation and frame delay stays high.

**Comment by nfp0** [comment]
>I get the same sawtooth with both glcore and vulkan with that core

Oh, nice! I assume it's working as intended then.
It's weird though, because I thought the cores had absolutely no control about the frame delivery timing.

> Snes9x has barely any deviation and frame delay stays high.

Yes, this only happens on heavier scenes. That's why I was testing with this core on that start screen in particular. And also in Mupen64-Plus.
Using this same core (bsnes-mercury) on lighter scenes even on the same Yoshi game, produces a nice flat frame graph.

So, this big frame time deviation might be normal behavior or not. And I still have no idea why it is like this.
Guess I'll have to dig deeper to find out why.

Anyway, thanks for the help!
Do you know anyone I can talk to that might know the answer?

**Comment by sonninnos** [comment]
No idea. I wouldn't say that it is "normal" even if it is happening no matter what. It for sure should not happen. And btw I used the plain bsnes with default settings, not mercury. Mednafen Saturn has even worse frame times for example in Sega Rally.

**Comment by nfp0** [comment]
Yeah, I feel the same. That's why I was trying to find the source of the problem.
I thought it could be a problem on the Linux AMD drivers, but since Windows shows the same problem, even on your Nvidia, that rules it out. It's probably something on RetroArch itself.

This wouldn't be a problem, because the frame delivery is perfectly smooth (at least on my system) even with the inconsistent frame graphs. But this affects auto frame delay and VRR, so I believe the problem should be pursued.

> I used the plain bsnes with default settings

Yeah I tested the plain bsnes too. Same results.

Glad you found out it also happens on Mednafen. It's definitely not isolated to just a few cores.
