### ISSUE TITLE
iOS RetroArch audio stops after resuming from background

### ISSUE THREAD

**Issue by rockman057** [libretro/RetroArch#14205]
## Description

Audio stops working when resuming iOS RetroArch from the background.

### Expected behavior

Audio should continue to play even after resuming RetroArch from the background.

### Actual behavior

After resuming RetroArch from the background, audio will no longer work until the app is force quit and relaunched.

### Steps to reproduce the bug

1. Open RetroArch on an iOS device.
2. Begin playing a game.
3. Verify audio is working.4. 
4. Return to the Home Screen by either swiping up from the bottom of the screen or pressing the home button, depending on your device.
5. Wait 30 seconds.
6. Reopen RetroArch.
7. The game will resuming playing, but with no audio.

### Bisect Results

I only noticed this happening since the release of iOS 15. I don’t recall it happening in iOS 14, but I don’t have a device on that version to confirm.

Backgrounding the app and reopening immediately will not reproduce the issue. It only happens after a little bit of time, so wait at least 30 seconds if you test it.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.3 (May 2nd 2022)

### Environment information

- OS: iOS 15.6
- Compiler: Compiler: Clang/LLVM (12.0.0 (clang-1200.0.32.27)) 64-bit

**Comment by LibretroAdmin** [comment]
PRs welcome for this issue unfortunately.

**Comment by trotsky40** [comment]
This seems to be resolved in iOS 16, both in my experience and noted here: https://github.com/libretro/RetroArch/issues/14462
