### ISSUE TITLE
RetroArch All Cores License Bug

### ISSUE THREAD

**Issue by AngelofMe** [libretro/RetroArch#14229]
https://youtu.be/ZAlFXTgKZGU

**Comment by Ryunam** [comment]
I can confirm this applies to the Ozone menu driver too. License information in the sublabel is broken right now:

![image](https://user-images.githubusercontent.com/17614150/181235213-39e4111b-ea6b-45f2-9c63-d7cbafe979a0.png)

**Comment by LibretroAdmin** [comment]
Can you do a bisect @Ryunam ? That would help narrow it down.

**Comment by LibretroAdmin** [comment]
This should fix the issue hopefully - at least it does on our end -
https://github.com/libretro/RetroArch/commit/ba752b6364b212161da61dfeea20605eaab103e6

**Comment by AngelofMe** [comment]
v1.10.3 stable is ok
but latest no!!!

**Comment by AngelofMe** [comment]
v1.10.3 stable is ok
but latest no!!!

**Comment by Ryunam** [comment]
Everything's okay now, tested on Ozone. Thanks @LibretroAdmin!

![image](https://user-images.githubusercontent.com/17614150/181293560-e9158a8b-4133-4db8-9e03-401cdd1d38bf.png)
