### ISSUE TITLE
Hardcore mode on games without achievement

### ISSUE THREAD

**Issue by onizuka14** [libretro/RetroArch#14224]
## Description
Hardcore mode is only active if the game has achievement

### Expected behavior
Hardcore mode should always be active if you set it to "ON" even if the game doesnt have any achievements

### Actual behavior
If a game has 0 achievements even with Hardcore mode ON you can use save/load states,
[What is actually happening]

**Comment by hizzlekizzle** [comment]
This is a potato/potahto situation. Personally, I think consistent behavior is more predictable and therefore favorable.

**Comment by Jamiras** [comment]
The behavior you describe is expected, as we didn't want to automatically restrict players playing games on a system that didn't support achievements. The logic is simplistic enough that it also extends to any game that doesn't have achievements.

There's nothing preventing you from not using the restricted features if you're playing a game without achievements. Hardcore is a special **achievement** mode that has to be enforced by the software. How you play games without achievements is up to you.
