### ISSUE TITLE
[Android] Input is broken on Android versions < 4.4 (Gingerbread excepted)

### ISSUE THREAD

**Issue by Googer** [libretro/RetroArch#1423]
The Android input driver attempts to get vendor id and product id for input devices when configuring them, which fails on Android versions before 4.4 since those methods in InputDevice were added at API level 19 (KitKat).  Easiest workaround is probably to simply use the Gingerbread (2.3) method (which simply doesn't attempt to discover these ID's) for any revision of Android < 4.4, especially given the Android autoconfig files (currently) don't specify these ID's anyway...

**Comment by PetePriority** [comment]
I have created a pull request https://github.com/libretro/RetroArch/pull/1437

**Comment by Googer** [comment]
I'll verify this is resolved in the next successful nightly Android build and close once I see it is. :)

**Comment by fr500** [comment]
I'll trigger a manual build ASAP! check the buildbot in a few minutes

**Comment by Googer** [comment]
In that case I'll check it on my Fire TV when I get home this evening. :)  Already verified that it seems OK on my Nexus 5.

**Comment by twinaphex** [comment]
OK, let me know if it works on your Fire TV now. If it does, you can make the decision to close this issue.

**Comment by PetePriority** [comment]
I can confirm it works on the Fire TV

**Comment by Googer** [comment]
Confirmed fixed here as well :)

**Comment by 3miliooo** [comment]
Nightly build 26.02.15 working on my JB S4. 

http://libretro.com/forums/showthread.php?t=1961&page=3 

Thankyou!
