### ISSUE TITLE
Retroarch configured with 'thumbnails' equal to 'Boxart' and 'Second Thumbnail' equal to 'Screenshot' displays screenshot in both slots when you cycle it.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#14236]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

As the title says. I thought the point of cycling the thumbnails would be showing different ones at the same time, since there is not enough space for the 3. So i was very surprised that one of the three configurations possible when you cycle with these settings on the UI config is the screen shot on both top and bottom. Seems like it should be: 'boxart and screenshot' or 'boxart and title' or 'title and screenshot' but i think it might have been broken with the recent updates.

@sonninnos 

RetroArch: Frontend for libretro -- v1.10.3 -- d7a30f2a18 --
Compiler: GCC (9.4.0) 64-bit Built: Jul 27 2022

**Comment by sonninnos** [comment]
True, it is pointless to show the same image twice when cycling with Y, and fixing that was simple, but preventing the user from being able to select the same images via the menu is a different matter.
