### ISSUE TITLE
RFE: Thumbnail Zoom could be more useful if it didn't need to exit to select a new one in a playlist

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#14245]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

As the title says. It would be nice if you could zoom in the playlist thumbnails, like you can with start right now, but still had playlist buttons available and working, so moving down/up L1/L2 R1/R2 still worked, besides exit. And naturally, when you exit, you have another game selected if you moved.

@sonninnos 

Man, i feel bad pinging you again with a non-bug, but you've been on a roll with thumbnails.

**Comment by sonninnos** [comment]
Seems like a duplicate: https://github.com/libretro/RetroArch/issues/10958

**Comment by i30817** [comment]
Close it down. I didn't find it in the first page of search. Although i searched for 'thumbnail' only doh.
