### ISSUE TITLE
Bad graphic errors while playing ps1 game

### ISSUE THREAD

**Issue by Trueetoothetee1** [libretro/RetroArch#14257]
[What you expected to happen]
Game to be actually playable
### Actual behavior
Game unplayable due to graphics errors
[What is actually happening]
Graphic glitches where certain parts of the screen doubling and overlaying ontop of the actual game causing me to not be able to see anything
### Steps to reproduce the bug
Go into any battle on digimon digital card battle. Rest of the game works fine. It's only the battles
1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]
Instantly when the game started. Began to get very bad
### Version/Commit
You can find this information under Information/System Information
Newest
![20220730_140712](https://user-images.githubusercontent.com/110306566/181953465-9a0649f2-0161-4164-98ca-1354e449ef2d.jpg)
![20220730_140712](https://user-images.githubusercontent.com/110306566/181953697-7cc20827-116e-4ee7-b05d-dcfae66df771.jpg)

- RetroArch: [version/commit]

### Environment information
Running windows 10
- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by Ryunam** [comment]
Which core are you using?

**Comment by Trueetoothetee1** [comment]
> using

I'm using the beetle hw ps1 core

**Comment by LibretroAdmin** [comment]
This is not a RetroArch issue, but a Beetle PSX issue (if that is established and it's not just user misconfiguration). File it in the appropriate Github issue tracker, not here.
