### ISSUE TITLE
[all] Bind RetroPad should have a timeout

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1427]
As the title says bind options for a gamepad should have a timeout just like the keyboard counterpart has. Otherwise users can get locked into that dialog

**Comment by GPDP2** [comment]
I agree with this. There's times where for whatever reason RetroArch doesn't recognize a gamepad at first, and there's nothing you can do if you try to map inputs. A timeout is an easy solution in such situations.

**Comment by twinaphex** [comment]
Done now.
