### ISSUE TITLE
WinGet installation target is C:\, please change to Program Files

### ISSUE THREAD

**Issue by loremari** [libretro/RetroArch#14276]
I installed retroarch on Windows 10 with the command `winget install RetroArch`, as per advice in https://www.libretro.com/index.php/retroarch-now-on-windows-package-manager/.

It installed by default in "C:\RetroArch-Win64", no questions asked, which is... untidy.

Is it possible to set the default installation to the appropriate Program Files path?

**Comment by hizzlekizzle** [comment]
Program Files is actually a bad spot for RetroArch and can lead to weird permissions problems. It would be ideal if we could install to somewhere in the User path, but I'm assuming that's not allowed (that's the case with most package managers).

**Comment by loremari** [comment]
> Program Files is actually a bad spot for RetroArch and can lead to weird permissions problems

I can't possibly judge the technical constraints behind this, but isn't this in itself an issue for RetroArch that should at least be tracked?

**Comment by LibretroAdmin** [comment]
Not really. RetroArch has a unique program paradigm where software gets loaded in as modular cores (.dll files).

**Comment by loremari** [comment]
Non wanting to sound confrontational, and by the way thank you for this great software you spend your own time on and I'm enjoying it greatly.

I'm asking out of curiosity now, what you are describing sounds like binary plugins, which would be far form being unique in the software landscape.

**Comment by LibretroAdmin** [comment]
It just makes very little sense for us at this point to change the default install directory and there are likely technical reasons involved as well. It would just needlessly confuse existing users and there is just no good reason for suddenly having to change it.

**Comment by sonninnos** [comment]
Windows version writes to the executable directory, and since normal user can't write to `Program Files`, installing it there is not good, because users would have to use Administrator privileges.

Some time ago I did start working on being able install it there by redirecting writes under the user home path, but lost interest and did not finalize it.

**Comment by Clockwork-Muse** [comment]
> but I'm assuming that's not allowed (that's the case with most package managers).

It is allowed - a number of packages explicitly install to user folders specifically to work for non-admin users.  This is the case for the VS Code installer, at minimum (installs to `C:\Users\<user name>\AppData\Local\Programs\Microsoft VS Code>`).
