### ISSUE TITLE
I have a feature request 

### ISSUE THREAD

**Issue by Yeetboi6364** [libretro/RetroArch#14277]
I would like if retroarch automatically pauses the game when your controller dies

**Comment by bslenul** [comment]
Duplicate of #13307 and #13016 but I agree, that would be a great addition.

**Comment by sonninnos** [comment]
And the issue should be at least somewhat readable in the title..

**Comment by hizzlekizzle** [comment]
We should probably just pick one of these tickets and then close the others.

**Comment by Yeetboi6364** [comment]
Sorry guys didn't know someone already requested this
