### ISSUE TITLE
missing playlist png?

### ISSUE THREAD

**Issue by AngelofMe** [libretro/RetroArch#14273]
![image27](https://user-images.githubusercontent.com/26894447/182393878-c6e69612-394a-4ce7-86e8-752e4a22452d.png)

**Comment by hizzlekizzle** [comment]
You'll have to be more specific. Using the issue template would be ideal.

**Comment by LibretroAdmin** [comment]
This should fix it -
https://github.com/libretro/RetroArch/commit/70ca20fbf91e7c2747e8e5638d0ad4a0a49a0cae

**Comment by cjmanca** [comment]
If you're on steam deck, it may be related to a new issue that just started after yesterday's steam linux runtime -sniper update, where retroarch can no longer see any files in the SD card except for the ones in steamapps. So if you had your icons on the SD card outside of the retroarch directory, they can't be seen by retroarch anymore.
https://steamcommunity.com/app/1118310/discussions/0/3455968575338348211/?tscn=1659414056

**Comment by LibretroAdmin** [comment]
@cjmanca This is not a related issue, it's separate I'm pretty sure. I'm also reasonably confident it has been fixed as of @70ca20f, I just need the OP to finally confirm it is fixed on his end before I'm going to close it. Will wait at least two more days for a response, then will consider the issue closed. The Steam issue is another matter altogether.

**Comment by LibretroAdmin** [comment]
@AngelofMe respond if we can close the issue now, thanks

**Comment by AngelofMe** [comment]
@LibretroAdmin respond if you can close the issue now, thanks
i'm in hospital

**Comment by LibretroAdmin** [comment]
Alright, thanks.
