### ISSUE TITLE
build PS3 version fail

### ISSUE THREAD

**Issue by ZhiWei-Jiang** [libretro/RetroArch#14280]
when i type make -f **Makefile.psl1ght** after sdk setup
it will show :
ppu-g++ -o retroarch_psl1ght.elf -D__PSL1GHT__ -D__PS3__ -mcpu=cell -L. gfx/drivers/rsx_shaders/vpshader_basic.vpo.o gfx/drivers/rsx_shaders/fpshader_basic.fpo.o libretro-common/libco/ps3.o griffin/griffin.o -lretro_psl1ght -laudio -lrsx -lgcm_sys -lnet -lio -lsysutil -lsysmodule -lm -ljpgdec -lpngdec -llv2 -lnet -lnetctl -lsysfs -lfreetype -lcamera -lgem -lspurs
/usr/local/ps3dev/ppu/lib/gcc/powerpc64-ps3-elf/7.2.0/../../../../powerpc64-ps3-elf/bin/ld: cannot find -lretro_psl1ght
collect2: error: ld returned 1 exit status
make: *** [Makefile.psl1ght:117: retroarch_psl1ght.elf] Error 1
rm gfx/drivers/rsx_shaders/fpshader_basic.fpo gfx/drivers/rsx_shaders/vpshader_basic.vpo

i cant find -lretro_psl1ght , who konws this lib how to generate and where locate?

**Comment by ZhiWei-Jiang** [comment]
@OsirizX bro, i guess you know how to figure it out?

**Comment by LibretroAdmin** [comment]
You need to put the statically linked PSL1GHT core into the root dir of RetroArch. So it's not an error, it's normal behavior.

**Comment by ZhiWei-Jiang** [comment]
Thanks,but how to generate this PS1IGHT CORE?  I cant found any clue in PS1IGHT sdk.

**Comment by ZhiWei-Jiang** [comment]
what difference between Makefile.psl1ght and Makefile.psl1ght.Makefile.psl1ght.salamander?

I cd dist-scripts and type "./dist-cores.sh ps1ight" then generate retroarch_psl1ght_salamander.elf in the root dir.
and tyep "make -f Makefile.psl1ght.salamander " and "make -f Makefile.psl1ght.salamander pkg"
finally i found RetroArch.PSL1GHT.pkg in the  ps3/RetroArch/pkg/psl1ght dir,is that correct?

**Comment by ZhiWei-Jiang** [comment]
finally retroarch_psl1ght.pkg is generated, but it will blackscreen and quit to xmb when i launch this app after install.

how can i debug it and figure it out? @LibretroAdmin
