### ISSUE TITLE
[all] text entry dialogs should cancel with "B" or have a timeout

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1428]
If you accidentally hit X in RGUI on a mobile platform you will be locked up at that dialog unless you have a working keyboard overlay setup. Dialogs should cancel with B to be consistent with the rest of the GUI

**Comment by heuripedes** [comment]
Just took a look on this, I managed to make the search dialog close on "B" but it also closes if you press the key mapped to joypad "B". I tried manually querying the joypad driver but it always return false for some reason. It seems the menu system is not able to detect whether a button press came from the joypad or the keyboard. RetroArch already answers to keyboard "/" so maybe we can disable X?

**Comment by fr500** [comment]
search is only good if you have a keyboard so it could be a compromise ...

**Comment by twinaphex** [comment]
We really should get this working with the gamepad also. Just dropping features from being possible with the gamepad is basically against the gamepad centric nature of the menu to begin with.

**Comment by joolswills** [comment]
Just to add (sorry if obvious) is that recent menu changes seem to take input after initial hotkey presses. eg. if the keypad hotkey is select + x, and x would bring up the seach, old code needed an addition press of X. with current code, the hotkey triggers X after the RGUI is loaded which seems to be the major issue behind https://github.com/libretro/RetroArch/issues/1807 (the search dialog doesn't even appear but gets triggered)

**Comment by heuripedes** [comment]
@twinaphex How is one supposed to search with the gamepad? Just by looking at the code it's clear the search feature depends on keyboard input. 
Navigating a virtual keyboard with over a hundred keys using a gamepad just doesn't seem practical to me. It would take much less time to just use <kbd>←</kbd>, <kbd>→</kbd>, <kbd>R1</kbd> or <kbd>L1</kbd> to jump some pages most of the time.

**Comment by fr500** [comment]
Well if you have an osk set triggering search will show the osk.  This is
good at least for mobile devices

**Comment by heuripedes** [comment]
@fr500 Mobile devices have touch/mouse for osk interaction.
