### ISSUE TITLE
PLEASE Restore Retroach's ability use the same input device as easily as just switching input device

### ISSUE THREAD

**Issue by negativeExponent** [libretro/RetroArch#14286]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

All input ports should be able to use the same input device, which can be used to use only one controller or input device to move other players. This was as easy as just switching over to that specific input device on other ports and automatically sets button mappings, but now you cannot...unless it was the intention to MANUALLY add button mappings EVERYTIME!

### Expected behavior

ditto above

### Actual behavior

unable to switch other ports to the same input device

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
https://github.com/libretro/RetroArch/commit/9d939a35d61853fcd7398e1eb20817ea530403c3

- RetroArch: https://github.com/libretro/RetroArch/commit/9d939a35d61853fcd7398e1eb20817ea530403c3

### Environment information

- OS: void
- Compiler: gcc 10.2.1/clang 12.0.1

**Comment by LibretroAdmin** [comment]
Can you bisected when this change you speak of started happening?

**Comment by bslenul** [comment]
Already fixed? I'm on latest nightly (ef551478d34056defd8cf10ef0e45a8ab5dc440d when typing this) and I just tried Contra on the Mesen core, I can switch port 2 device index to the same as port 1 and control both characters with my controller without the need to remap anything. Tested on Windows 10 with Xinput driver if it matters.

**Comment by negativeExponent** [comment]
> Already fixed? I'm on latest nightly ([ef55147](https://github.com/libretro/RetroArch/commit/ef551478d34056defd8cf10ef0e45a8ab5dc440d) when typing this) and I just tried Contra on the Mesen core, I can switch port 2 device index to the same as port 1 and control both characters with my controller without the need to remap anything. Tested on Windows 10 with Xinput driver if it matters.

well, if it works for you, then its probably on my end. its been a long time since i have updated retroarch itself, and strange things happen all the time. just recently i had to delete my config file and redo every setting i had there for years for some issues (uncompressed roms not show in browser, blank page on updater etc).
