### ISSUE TITLE
Ability to delete overrides by core/game/content dir.

### ISSUE THREAD

**Issue by jayare5** [libretro/RetroArch#14282]
There are options to delete shader configs and remaps, but not overrides.
Is it possible to add? (with the 3 options to choose if delete core, game, or content dir overrides) Thank you!

Side note:
There's a missing option to hide/show this as well. There's only 2:
-Show 'Save Core Overrides'
-Show 'Save Game Overrides'

This one is missing:
-Show 'Save Content dir Override' 

That one seems to always be there if one of those 2 is enabled.

**Comment by ethanaobrien** [comment]
Hello! (I'm not a maintainer of this repo, I'm just fairly familiar with some of the code)

This may be what you're looking for.

[`content_directory`](https://github.com/libretro/RetroArch/blob/56f66f68e246d0ff69b7132511ddfd5c57715736/retroarch.cfg#L64) - the content directory option
[`libretro_directory`](https://github.com/libretro/RetroArch/blob/56f66f68e246d0ff69b7132511ddfd5c57715736/retroarch.cfg#L835) - The core directory option

Although this would require editing the `retroarch.cfg` file manually (found in retroarches appdata folder)

Also, I dont know of an option for a game directory, so I cant help with that one, sorry
