### ISSUE TITLE
[Steam Deck] Lost access to SD card folders apart from steamapps

### ISSUE THREAD

**Issue by Crono141** [libretro/RetroArch#14297]
## Description

[Reference this thread on reddit. ](https://www.reddit.com/r/SteamDeck/comments/wf6yz4/weird_folder_access_issue/) 

A few days ago, the steam version of retroarch suddenly no longer could see or access folders on the SD card, except for the steamapps folder. On steam deck my roms are stored in a separate subfolder on the SD card, but retroarch steam cannot access or see them in its built in file browser. The Non-steam version of retroarch does not exhibit this behavior. 

### Expected behavior

File browser should list all files and directories it has proper permissions to access. 

### Actual behavior

Only the steamapps folder is visible in the file browser. 

### Steps to reproduce the bug

Unfortunately I am not sure how to reproduce. This issue wasn't present until the last week, and I can't pinpoint a cause. One day I tried to run a rom from a Playlist and the file wasn't found. Removed the Playlist and went to recreate it and that's when I discovered the behavior. 

### Bisect Results

Like mentioned, something happened within the last week or so to cause this behavior. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Steam version, latest stable. 

### Environment information

- OS: SteamOS 3.3
- Compiler: n/a

**Comment by Ryunam** [comment]
I believe a workaround for this issue was provided here:

> Seems like it impacts both the stable and beta clients on the Steam Deck.
> 
> As a temporarily workaround the launch options can be set to `STEAM_COMPAT_MOUNTS=/run/media/mmcblk0p1/ %command%` to make it accessible again.
> 
> This can be done with any external mount points too (colon delimited) in case desktop Linux users suffers from the same issue.

See here for the whole discussion: https://github.com/libretro/RetroArch/issues/14266

**Comment by kikegarcia** [comment]
I was reproducing this bug but, thanks @Ryunam, the workaround did work.

**Comment by Crono141** [comment]
Confirmed. This solves the issue.

**Comment by smcv** [comment]
Today's "Steam Linux Runtime - soldier" and "Steam Linux Runtime - sniper" releases should make that workaround unnecessary. Please see ValveSoftware/steam-runtime#470 for full details.

This is not a Retroarch bug and can probably be closed.

**Comment by zDEFz** [comment]
Yea but for some reason its still required as Proton Experimental seems to launch the wanted application while "Steam Linux Runtime" does not. Just had to use it for a music application called "MusicBee"

**Comment by smcv** [comment]
> Proton Experimental seems to launch the wanted application while "Steam Linux Runtime" does not

That doesn't seem like it has anything to do with Retroarch or this issue report?

Proton (all versions, including Experimental) runs Windows applications. It cannot run native Linux applications. It uses "Steam Linux Runtime - soldier" internally, so it inherits Steam Linux Runtime limitations around things like access to removable media.

The various Steam Linux Runtime compat tools run native Linux applications. They cannot run Windows applications.

It is not a bug for Proton to be unable to run a native Linux application: that's not what Proton is for, use SLR instead. It is also not a bug for one of the SLR compat tools to be unable to run a Windows application: that's not what SLR is for, use Proton instead.
