### ISSUE TITLE
[android] custom maps don't save (or actually, load) to retroarch.cfg

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1429]
If you set custom mappings for a new controller and then you exit retroarch (cleanly) those mappings won't persist, if you start retroarch again the default mappings will be in place.

If the user instead saves a configuration, and loads it afterwards the map works just fine.

I've opened the cfg file in /data/data/com.retroarch to check the values and I can confirm the values are stored correctly so I don't really know why it is not loading them.

**Comment by Googer** [comment]
Probably related to this since this is some sort of initialization issue, but I find it's the exact same deal with shader configuration as well.  retroarch.glslp is created and modified in the shaders_glsl directory according to whatever changes you make in the shader coinfiguration but it's not automatically loaded when Retroarch starts.

**Comment by PetePriority** [comment]
Should be fixed by https://github.com/libretro/RetroArch/pull/1455

**Comment by fr500** [comment]
I don't see why that would fix it but I'll give it a shot, thanks for the heads up

**Comment by blockfeed** [comment]
I'm using the Mar 5 nightly and the gamepad mappings aren't being loaded properly at startup. The configuration file is created and the values are persistent across restarts, but aren't being loaded at startup. Running on a Nexus 6 (5.0.2) the path is /storage/sdcard0/Android/data/com.retroarch.

**Comment by fr500** [comment]
The issue seems to be that driver detection and input mapping are done on the same function. I think separating these in two flags so we can have detection even without automapping would be the best

**Comment by fr500** [comment]
Should be fixed by now
