### ISSUE TITLE
[Switch]Wrong core display and info files reset

### ISSUE THREAD

**Issue by ImRyley** [libretro/RetroArch#14291]
## Description

Bug1- Banner that displays used core on game launch shows a previously used core. (I was using mGBA and VBAnext) 

Bug2- Core info files reset disabling save states until downloaded again (sometimes requires multiple downloads)

Both started on update 1.10.3 for me

### Expected behavior

Bug1- Banner on launch shows the currently used core.

Bug2- Save states consistantly available without downloading core info files a few times.

### Actual behavior
Bug1- Banner inconsistent

Bug2- Save states unavailable (requires core info files to be downloaded a few times)

### Steps to reproduce the bug

Bug1-
1. Update to 1.10.3
2. Launch a ROM from its own nsp
3. Launch second ROM that uses different core from its own nsp
4.Bug appears

Bug2-
1. Update to 1.10.3
2. Launch RetroArch
3. Launch a ROM 
4. Try save state
5. Bug appears

### Bisect Results

Both started after update 1.10.3

### Version/Commit

- RetroArch: 1.10.3

### Environment information

- Switch
- Firmware: 14.1.0
- Atmosphere: 1.3.2

**Comment by kartana** [comment]
This still happens and in some cases it shows a previously used core on the banner when you start a game from the playlist but it still loads the right specified core and the game works including save states but the log (for playtime etc) gets put into the wrong folder (the core log folder shown on the banner).

**Comment by m4xw** [comment]
Resolved in #14875
