### ISSUE TITLE
Configuration files are broken right now

### ISSUE THREAD

**Issue by Cthulhu-throwaway** [libretro/RetroArch#14307]
## Description

I've been warning about pointless bad edits for a while now and have pointed multiple issues with past bad edits, but they still keep coming.
Just load the latest nightly and compare its retroarch.cfg with the one generated by 1.10.3 stable.

I don't agree at all with those edits but I also don't want to keep arguing over this (and being labeled names).
However, I can't keep working with a codebase like this (I can't even publicly test my latest changes right now), so I am now on hiatus (something that I've been needing and wanting for a while).

**Comment by LibretroAdmin** [comment]
What if we were to reverse it all back and this time we don't touch this anymore? Would this make you reconsider?

**Comment by LibretroAdmin** [comment]
OK, I see the issue. Alright, it was foolhardy going down this path, will roll it all back and not touch it again. Hopefully you want to reconsider. I will take this on the chin, lesson learned.

**Comment by Cthulhu-throwaway** [comment]
I am burnt out at the moment and only kept working because stuff kept popping up every time I wanted to take a break.

I am socially human garbage (won't even deny that) and need some time off; I don't want to be the new contributor who keeps dictating rules.
With that being said, I also need RetroArch nightly to remain relatively functional because I need to do public netplay testing often to see what needs my attention next (corrupting retroarch.cfg is a pretty serious problem).
It's too hard to keep track of these changes because they don't add anything new to the table, but most of them have been introducing problems either discovered by myself or by the rest of the community.
There are also technical issues that could arise in the future by getting rid of safe functions, like strlcat.

I don't want any more arguing, which is why I am taking a break, but my opinion is that for a large C project like RetroArch, changes should require some reasonable motives, be polished to a certain extent and be readable (this is what I've been aiming in all of my PRs), bothering with optimizations only when clearly performing badly. There is about 50% of the netplay code that I haven't touched because I either don't have a reason to or because I don't have enough knowledge of the code to make changes.
I've changed PS Vita's netplay status from "never worked before" to "working" without even having access to the platform or any sort of meaningful documentation, so my phisolophy must hold some validity.

**Comment by LibretroAdmin** [comment]
You are 100% right. Please accept my sincere apology, and I am 100% certain I can undo the ill advised changes and we wont' do this again.

Changes to be made can be brought up for discussion first so that we don't do ill advised and time consuming dumb stuff that goes nowhere.

>  I don't want to be the new contributor who keeps dictating rules.

We absolutely want contributors that care and that push the project forward. Without people like you, this project is nothing.

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway I created this PR -

https://github.com/libretro/RetroArch/pull/14308

Can you let me know if this resolves the issues or if there are more things we have to change back? I'd welcome your participation in this. I'm as serious as you are in restoring things.

**Comment by LibretroAdmin** [comment]
I think it was just down to this -

https://github.com/libretro/RetroArch/commit/3c8f73985bf6b8711710dfb23744d7c1eb975f4a

Would be nice to have it confirmed if this resolves the issue for now.

**Comment by LibretroAdmin** [comment]
See comment in https://github.com/libretro/RetroArch/pull/14308 - I went through the entire codebase and can confirm no similar mistakes happened. I think we're safe and stable now.

**Comment by LibretroAdmin** [comment]
Should be resolved for now, but will keep the key lessons in mind and not continue going down a further path that could cause long lasting detrimental issues later on
