### ISSUE TITLE
Dpad config is not saved

### ISSUE THREAD

**Issue by arthabus** [libretro/RetroArch#14306]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When I configure controller, dpad shows the following values in RetroArch UI: "-1" for up, "+1" for down, "-0" for left, "+0" for right
It works well in games but those values are not saved and when I close and then open RetroArch I need to reconfigure the dpad again and again.

### Expected behavior

dpad values are saved in a config file just like any other buttons

### Actual behavior

[What is actually happening]

dpad config is not saved so I need to reconfigure dpad every time I launch RetroArch

In the retroarch.cfg the respective fields are still holds "null"
input_player1_down_btn = "null" // should be something like "+1", but if I put it manually in the config, it doesn't stick.

### Steps to reproduce the bug

1. Lauch RetroArch
2. Insert controller (mine is this: https://www.amazon.de/-/en/gp/product/B07X9Q9DYX/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1)
3. Go to settings -> input -> port 1 controls
4. Configure all buttons including dpad
5. dpad gives "-1", "+0", "+1", "-0" for up, right, down, left buttons
6. save config
7. close RetroArch and relaunch it
8. Go again to settings -> input -> port 1 controls 
9. see that dpad buttons are not preserved.

### Bisect Results

Immediately after installing it.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Version 1.10.3 (1.10.3)

### Environment information

- OS: MacOS Monterey 12.0.1
- Compiler: using stable installer

**Comment by LibretroAdmin** [comment]
You have to manually select 'Save Controller Profile' for the changes to take effect.

**Comment by arthabus** [comment]
Thanks @LibretroAdmin, yes, I tried that before multiple times with no difference. It still resets dpad back to "unset". 

Note that the rest buttons saves as expected. 

Dpad works well right after setting it up, but resets to "unset" after RetroArch restart.

Any other suggestions?

**Comment by kp8888** [comment]
I had a similar problem before with an offbrand controller. Try hitting "reset to default controls" after saving the controller profile, and then restart RetroArch to let it load the autoconfig profile. Otherwise your main config file might be screwed up somehow.

**Comment by arthabus** [comment]
thanks @kp8888. Just tried that and it didn't help unfortunately. Tried to reinstall the entire RetroArch, tried setting it with save/restore in different combination with no success - the dpad still resets to "unset" after restarting RetroArch.

Looks like a bug to me?

Any other thoughts on that?

**Comment by Cthulhu-throwaway** [comment]
Your report says you are on stable, but it's the nightly which had broken configs: https://github.com/libretro/RetroArch/issues/14307

Had you mentioned that you were on nightly, I would've pointed you to that issue yesterday (this is why it's important to add the commit version to your bug reports).

**Comment by arthabus** [comment]
@Cthulhu-throwaway thanks man, I just re-downloaded the stable from the website and it worked.

Btw, the version I've posted was everything listed in the "about" menu of RetroArch which usually includes all information needed - I assumed what you put in the parenthesis provides enough context.
