### ISSUE TITLE
The "Hotkey Enable Delay" feature breaks when "All Users Control Menu" is enabled

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#14322]
## Description

When "All Users Control Menu" is enabled, the "Hotkey Enable Delay" feature breaks, it only works when set to "0", any other value never blocks the input from being passed to the core.
And even at "0" it doesn't always work properly, if you spam the hotkey it sometimes still sends the input to the core.

### Expected behavior

If set to anything but "0", the inputs sent to the core should be blocked after that number of frames.

### Actual behavior

Unless it's set to "0", the inputs will keep getting sent to the core.

### Steps to reproduce the bug

1. Turn ON `Settings > Input > Menu Controls > All Users Control Menu`
2. Set a "Hotkey Enable" hotkey in `Settings > Input > Hotkeys` to Select.
3. Set "Hotkey Enable Delay" to anything but "0".
4. Boot a game.
5. Hold Select and notice that you can still move.

### Bisect Results

If I bisected properly 1ef78d3e3d8e8463790b1fb527510be51a38793a is the first bad commit.

### Version/Commit

- RetroArch: 1.10.13 / c180560

### Environment information

- OS: tested on Windows 10 and on a Linux Mint VM

**Comment by hizzlekizzle** [comment]
oh wut? that PR wasn't long after block delay feature was added in the first place... I wonder if it's been broken for the retropie(?) downstream folks, too, since they've been patching it in forever.

**Comment by bslenul** [comment]
> that PR wasn't long after block delay feature was added in the first place...

~1.5 year later (feature was added in Jun 2020 and the guilty commit is from Nov 2021). It's not a big deal honestly since you can still use both the hotkey and the core inputs (as long as it's not set to "0"), but it makes the setting pretty much useless...

No idea about RetroPie 🤷

**Comment by bslenul** [comment]
Hm seems to be an issue on my end, I tried with a fresh install and the setting works completely fine. I'll try to find what's conflicting with it.

**Comment by LibretroAdmin** [comment]
Yes, 'All Users Control The Menu' has always been buggy from its inception. That's why we took it out at some point hoping someone would do a better implementation. Instead, what happened is that people would just complain about wanting it back with noone wanting to do the actual effort of implementing a version that would be better without all the issues, so instead the old code just got brought in.

So, PRs welcome here.

**Comment by bslenul** [comment]
It's not a big deal tbh, that "All Users Control Menu" does more good than harm, I'm glad it was added back in ;) That bug it introduces is very minor.

**Comment by bslenul** [comment]
Recent changes in "Hotkey Enable" made me revisit this issue, I can't tell if it's related to these changes but the issue seems to be fixed! 👍 

Closing!
