### ISSUE TITLE
Double L3 buttons is showed in settings-input-port controls, when I use simple chinese language.

### ISSUE THREAD

**Issue by panjp-git** [libretro/RetroArch#14324]
## Description
Double L3 buttons is showed in settings-input-port controls, when I use Simple Chinese language.
But, when I use English language, L3 and R3 buttons is no problem in there.
I think this is a translation bug.
### Expected behavior
Settings->Input->Port * Controls：
...
L3键（摇杆）<L3 Button(Thumb)>
R3键（摇杆）<R3 Button(Thumb)>
...

### Actual behavior
Settings->Input->Port * Controls：
...
L3键（摇杆）
L3键（摇杆）
...

### Version/Commit
- RetroArch: [v1.10.3 & nightly(2022-08-16)]

### Environment information
- OS: Windows 10 & Android

**Comment by bslenul** [comment]
Here you can vote for the correct translation (and downvote the wrong one): https://crowdin.com/translate/retroarch/11735/en-zhcn#2061838

**Comment by bslenul** [comment]
I thought the votes would make it automatic but I was wrong, I asked yesterday on Discord about this and someone forced the correct translation, this is now fixed with ab57d3cab7d870b5dd55ddf9d9c584775bcdf03d
