### ISSUE TITLE
[Regression] Core Option Categories not being detected anymore

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#14331]
## Description

RetroArch is not detecting core option categories anymore, regardless of whether the feature in question is enabled or not under Settings -> Core. 

As a result, core options are currently displayed without any grouping whatsoever.

### Expected behavior

if “Core Option Categories” under Settings -> Core is enabled, core options categories should be detected and displayed as normal in the menu for any of the compatible cores.

### Actual behavior

The option defined in Settings -> Core is currently being ignored.

### Bisect Results

Commit https://github.com/libretro/RetroArch/commit/90e0d0bb7079ec9159fc471a04fccc8af059cd7c by @LibretroAdmin seems to have introduced this issue.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.3 / https://github.com/libretro/RetroArch/commit/90e0d0bb7079ec9159fc471a04fccc8af059cd7c

### Environment information

- OS: RA self-compiled on both Windows 11 and Steam OS (Steam Deck)
- Compiler: MSYS2/Mingw64 on Windows

**Comment by Cthulhu-throwaway** [comment]
https://github.com/libretro/RetroArch/commit/90e0d0bb7079ec9159fc471a04fccc8af059cd7c#diff-7f843788228481d54c4b3f46fc85b41a855afc14d603caeb5b7a73d746d17667L1208-R1209

Missing CORE_OPTION_MANAGER_MAP_DELIM

**Comment by Ryunam** [comment]
Thanks! That change does indeed fix the issue, so I just pushed a commit for it.

**Comment by LibretroAdmin** [comment]
Whoops, my bad for that oversight. Should have been more careful. Thanks for the quick correction.
