### ISSUE TITLE
[PS2] No Internal HDD Suppprt

### ISSUE THREAD

**Issue by petePESTILENCE** [libretro/RetroArch#14346]
Any chance of the devs doing a pass to enable internal harddrive usage on ps2. Because the usb drive on ps2 is 1.1 and its really stupid to have that as the only option to run retroarch as it is soooo slow.

It should be a simple load module, for hdd access, that was never implemented (for some reason)

**Comment by AKuHAK** [comment]
Hdd is working, but currently it has limitations, ao you need to start retroarch from the hdd.

**Comment by petePESTILENCE** [comment]
I had a broken fhdb install that was probably causing issues. I have since fixed this and retroarch is booting from hdd fine. So I will close this now. Thank you
