### ISSUE TITLE
CRT-Royale Hardware Resize Sample Mode Looks Off

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#1435]
In the latest nightly I noticed this shader looks slightly off, like a pass is missing or something. Here are comparison shots of the Sega screen from Sonic 2:

How it used to look (2015-02-13 nightly): http://i.imgur.com/hoDpv9F.png
How it looks in the newest nightly (2015-02-21): http://i.imgur.com/m07Ymka.png

The white background of that makes it easier to see the difference. In trying to track down when this issue started, I found out that both 2015-02-19 and 2014-02-20 builds crash at "RetroArch: gl_load_luts: Loading texture image from: "./Shaders/./crt-royale/TileableLinearApertureGrille15Wide8And5d5SpacingResizeTo64.png"..." as seen in this screenshot: http://i.imgur.com/ugxzVDM.png

2015-02-18 and earlier nightlies work and look fine.

For reference, I'm loading crt-royale.cgp and using this user-settings.h file: http://pastebin.com/Hz9ZRRAi

**Comment by Awakened0** [comment]
I did some testing with different Royale settings. It seems like you only get visual differences between builds when using "static const float mask_sample_mode_static = 1.0". That mode is described as:

    //  1.) Hardware-resize to the desired dot pitch (ugly/fast/flexible).  This
    //      is halfway decent with LUT mipmapping but atrocious without it.

The 0 sample mode option looks the same in both pre 02-19 and post 02-20 builds. I've never been able to get sample mode 2 to work right.

**Comment by fr500** [comment]
Please test on the current code, and reopen if the issue persists
