### ISSUE TITLE
Add soft reset to genesis cores (Genesisplusgx and blastem)

### ISSUE THREAD

**Issue by joepogo** [libretro/RetroArch#14357]
Some games on the genesis system relied on a soft reset to finish. Well one, in particular.

Xmen on retroarch (on genesisplusgx and blastem) is currently unable to be beaten until there is an option implemented to soft reset the system. You cannot get to the final level without soft resetting the system, the current reset for these 2 is the equivalent of a hard reset. 

Genesisplusgx has soft reset and so does blastem, is there a way to pull these options forward from these emus to fix this issue?

**Comment by hizzlekizzle** [comment]
It appears to already be a soft-reset: https://github.com/libretro/Genesis-Plus-GX/blob/master/libretro/libretro.c#L3552

This change was made back in 2016: https://github.com/libretro/Genesis-Plus-GX/issues/39

**Comment by joepogo** [comment]
Hey hizzlekizzle, thanks so much for the response! :) Is there a way to activate it because as of now when you play this level retroarch genesisplusgx treats it like a hard reset instead and you lose all progress, unless i am crazy or missing something lol. :P

**Comment by hizzlekizzle** [comment]
Hmm, Blastem's reset appears to explicitly call out a soft reset, as well: https://github.com/libretro/blastem/blob/libretro/libblastem.c#L188

**Comment by joepogo** [comment]
whaaaat?! ok, i must really be crazy heh.  :P :O Thanks again hizzlekizzle, it's Monday and i must be REALLY off my game or something. haha. When my shift is over i will try these 2 cores again in particular, i am not sure how i could miss this, i just played this yesterday with a friend and we couldn't get it to work. 

If i am wasting your time, apologies for this issue report, i'll go back and retest this again. Thanks again for your help with this. I guess even us old gaming vets can still sometime look like a noob hahaha. :)

**Comment by hizzlekizzle** [comment]
No problem! It's not putting me out :)

**Comment by LibretroAdmin** [comment]
So is there still an issue here or can this be closed?

**Comment by joepogo** [comment]
I think it was something on my end. Closed. :)
