### ISSUE TITLE
[Xbox One Series S] Final Burn Neo running slow only when netplay is enabled

### ISSUE THREAD

**Issue by d-apps** [libretro/RetroArch#14364]
## Description

When I try to play any arcade game using **Final Burn Neo (v1.0.0.03 ff5f099)**, games are working fine. 

https://user-images.githubusercontent.com/20110433/187489664-6a0f6d96-69c8-4c0c-94e2-2e2970051e34.mp4

When I enable netplay or join any room that uses Fb Neo, the game runs very slow.

https://user-images.githubusercontent.com/20110433/187489908-7006d4f1-3bd1-47ff-acfb-7c30bb66fb6a.mp4

### Expected behavior

Games running in decent fps with Final Burn Neo core while netplay is enabled.

### Actual behavior

Games are running slow only with Final Burn Neo and netplay enabled.

### Steps to reproduce the bug

1. Run some arcade game with Final Burn Neo.
2. Enable netplay.

### Bisect Results

I just installed retroarch on my xbox, was a fresh install.

### Version/Commit
v1.0.0.03 ff5f099

- RetroArch: 1.10.3 msvc2019 Build Jul 10 2022

### Environment information

- OS: Windows 10 x64 Build 22000 Windows.Xbox (v10.0)
- Compiler: MSVC (1929) 64-Bit

**Comment by LibretroAdmin** [comment]
Not a bug and not a RetroArch issue, file it on the FBNeo issues repo instead.

**Comment by barbudreadmon** [comment]
>file it on the FBNeo issues repo instead

Netplay performance is the only thing we can meddle with at the core level, and even a pi3 can handle netplay on neogeo games, so except if that xbox is worse than a pi3, there is no way it could be a performance limitation on our side, and even then it still wouldn't be our problem tbh.

@Cthulhu-throwaway any thoughts about this ?

**Comment by LibretroAdmin** [comment]
Alright, should the issue be closed?

**Comment by d-apps** [comment]
Sorry for not uploading logs.

[logs.txt](https://github.com/libretro/RetroArch/files/9471950/logs.txt)

**Comment by Cthulhu-throwaway** [comment]
Log is pointless because this is not an error; None of the things that I've mentioned as possible cause would show any meaningful information about performance degradation in the logs.

You are better off just enabling rewind and setting rewind frames to 1 (if it isn't there already) and then try to play the game without netplay. If it still slows down, it's 100% not a netplay problem.

**Comment by barbudreadmon** [comment]
>If the core's serialization size is 1 MB

savestate size is around 400k for neogeo games

**Comment by d-apps** [comment]
> Log is pointless because this is not an error; None of the things that I've mentioned as possible cause would show any meaningful information about performance degradation in the logs.
> 
> You are better off just enabling rewind and setting rewind frames to 1 (if it isn't there already) and then try to play the game without netplay. If it still slows down, it's 100% not a netplay problem.

I did that, it didn't slow down, 60 fps with that settings you said.

One thing that I realized was if the game is running and I start netplay, the game resets automatically, it doesn't happen when I try in other devices like arm64, pc.

**Comment by d-apps** [comment]
> Did you try rewinding with the rewind hotkey? Some features (hardcore achievements, netplay, maybe some others) implicitly disables rewinding, even if you've the setting enabled.
> 
> Restarting content when starting netplay with content already loaded is the current intended behavior that didn't exist in previous versions. It happens on ALL platforms starting with #14117 (client) and #14157 (host).

I tried the rewind option, it does not made any change to the slow down and with rewind enable or disabled didn't impact with netplay disabled, game still running well.

![16620802511873536738962790987482](https://user-images.githubusercontent.com/20110433/188036738-011e9a37-90b2-4572-9290-d7ab9b6ceb0e.jpg)

One thing that I forgot to say is that all other emulators work fine even with netplay enabled, only fbneo have the issue.

**Comment by Cthulhu-throwaway** [comment]
Yes, but did you try to actually rewind with the hotkey?

**Comment by d-apps** [comment]
> Yes, but did you try to actually rewind with the hotkey?

Yes, I set the hotkey, when I press the hotkey to rewind without netplay enabled I can see an arrow top right of the screen and the game starts rewinding if I hold the button, but when I press the hotkey with netplay enabled it doesn't work, not arrow at top right.

**Comment by Cthulhu-throwaway** [comment]
I don't know what to tell you since I can't reproduce the issue on my PC and I've played neo geo games with people running RetroArch on Xbox.

Better try the official stable build on dev mode, and if that works, just compile this repo by building pkg/msvc-uwp/RetroArch-msvc2019-UWP.sln into Visual Studio.
