### ISSUE TITLE
[all] force libretro pause to enabled when in netplay

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1436]
when in a netplay session, calling the menu with libretro pause disabled still pauses the other side causing an instant desync.

It would be desirable to have libretro pause enabled during netplay OR to make sure it doesn't pause the client

**Comment by fr500** [comment]
I tried forcing this but it doesn't work, pausing means no keepalives are sent either, what we actually need is to negotiate connection parameters and send keepalives when the menu is active

**Comment by RobLoach** [comment]
I believe I read that this was fixed in a recent version.
