### ISSUE TITLE
PS3's RetroArch doesn't save Aspect Ratio setting

### ISSUE THREAD

**Issue by Windows10User2** [libretro/RetroArch#14370]
After changing a RetroArch core's "Aspect Ratio" setting from the default "4:3" to "Custom" in RetroArch 1.9.0 CEX and running games with a different RetroArch core, I have to change the latter's "Aspect Ratio" setting from "4:3" to "Custom" because I have a white screen when running games with them since the "Aspect Ratio" setting is blank for some reason insted of being set to "Custom".

**Comment by Windows10User2** [comment]
It looks like RetroArch is now automatically saving the Aspect Ratio setting after exiting RetroArch from the app.

**Comment by Windows10User2** [comment]
Anyone?

**Comment by sonninnos** [comment]
Never witnessed settings changing by itself in any "official" platform, so pretty sure it can't be fixed from here either.

**Comment by Windows10User2** [comment]
> Never witnessed settings changing by itself in any "official" platform, so pretty sure it can't be fixed from here either.

Should I manually save the settings (I think RetroArch already does that) after setting them or even so they'll change by themselves? Also, when will RetroArch be officially released again? The official site says "Coming soon" for years.

**Comment by Windows10User2** [comment]
> Never witnessed settings changing by itself in any "official" platform, so pretty sure it can't be fixed from here either.

I already had this problem with the version that appeared in RetroArch's official version (I don't know why it was removed from it).
