### ISSUE TITLE
Cannot start any PS game, thank you.Old versions works. Now - nope.

### ISSUE THREAD

**Issue by deathxxx123** [libretro/RetroArch#14379]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]
No PS game can be started. I have other emus and no problem. I have experience with old version retroarch - no problem. What are you done guis?

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by LibretroAdmin** [comment]
Insufficient information provided.

**Comment by deathxxx123** [comment]
https://youtu.be/0oa_qZjJeF0

**Comment by deathxxx123** [comment]
Yea... i manage to play some PS1 games, but with PS2 - good luck!
There is no "how to" on linux, thank you.
Just cannot start any PS2 game with PCSX2 core and BIOSE.
I have one question:
How to expect someone to use this when is too complicated to set up and use?
Not all of us are gurus. Why you make this software?
With PCSX2 program is all so easy! Just install, browse for iso's, select BIOS folder and run!
That program was good before, but now is so difficult and crashing to use it.
How to expect someone regular user to play games with this? The menu is so confusing and some options are repeating in menu's.
I try distro's RetroArch, Qt version, appimage and all is so unplayable.
For now i will keep using DuckStation and PCSX2 for PS1/2 games.

**Comment by LibretroAdmin** [comment]
Unhelpful issue report and then a huge rant talking bad about our software. Not interested in pursuing this further, sorry. Keep your emotional outbursts out of technical reports.

**Comment by LibretroAdmin** [comment]
You probably just forgot to add the BIOS file to the system directory and then proceed to blame our software for user error. Regardless, always check docs.libretro.com before issuing a bug report here.
