### ISSUE TITLE
[3DS] bottom_menu.png not found

### ISSUE THREAD

**Issue by Mcoogle** [libretro/RetroArch#14375]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Loading any core results in error:

“bottom_menu.png not found” while the file exists under /assets

### Expected behavior

Bottom screen should show a UI

### Actual behavior

No UI loads for bottom screen on 3ds

### Steps to reproduce the bug

1. Launch Retroarch
2. Load any content using any core (mGBA core for example)
3. Look at bottom menu

### Bisect Results

Occurred after updating to latest version. Clean install (removed all files from SD including uninstalling all .CIA

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Build Date: Sep 2 2022

### Environment information

- OS: 3DS
- Compiler: GCC (10.2.0) 32-bit

**Comment by LibretroAdmin** [comment]
@MrHuu any ideas here? Did he just forget to update assets?

**Comment by MrHuu** [comment]
The default location for the ```bottom_menu.png``` is ```/assets/ctr/```.
You mention having it in ```/assets```?

https://buildbot.libretro.com/nightly/nintendo/3ds/
Distributed files have them in the default location.
Did you copy the included ```retroarch``` folder from there?

**Comment by Mcoogle** [comment]
Correct the file is under sdmc:Retroarch/assets/ctr 

I didn’t change any default file locations.

**Comment by Mcoogle** [comment]
Maybe related, but Retroarch crashed the first time I loaded a rom using mGBA because the rom was too large. The standalone mGBA runs the rom fine but the latest core does not. I’ll try  a fresh install and run a compatible rom to see if that fixes it.

**Comment by Mcoogle** [comment]
Fixed Bottom_Menu.png error by going to Settings > User Interface > 3DS Bottom Screen Appearance > then changing Bottom Screen Asset Directory from “default” to “retroarch/assets/ctr”

**Comment by LibretroAdmin** [comment]
> Maybe related, but Retroarch crashed the first time I loaded a rom using mGBA because the rom was too large. The standalone mGBA runs the rom fine but the latest core does not. I’ll try a fresh install and run a compatible rom to see if that fixes it.

Which 3DS? New 3DS or 3DS? When you turn on Show Memory Usage, how much RAM does it report being available before you load the game? Also, how big was this ROM? 

It's a constant struggle keeping enough of a RAM footprint on these underpowered consoles. Often times it's best not to add new features to console ports that lack enough RAM headroom, because that could shut the door on certain large ROMs from being able to be loaded into memory (and the alternative, virtual memory, is often times too slow to be worth bothering with).

**Comment by LibretroAdmin** [comment]
> Fixed Bottom_Menu.png error by going to Settings > User Interface > 3DS Bottom Screen Appearance > then changing Bottom Screen Asset Directory from “default” to “retroarch/assets/ctr”

So what does this mean @MrHuu ? That the 'Bottom Screen Assset Directory' has not been set up correctly by default? Can you fix this?

**Comment by Mcoogle** [comment]
> > Maybe related, but Retroarch crashed the first time I loaded a rom using mGBA because the rom was too large. The standalone mGBA runs the rom fine but the latest core does not. I’ll try a fresh install and run a compatible rom to see if that fixes it.
> 
> Which 3DS? New 3DS or 3DS? When you turn on Show Memory Usage, how much RAM does it report being available before you load the game? Also, how big was this ROM?
> 
> It's a constant struggle keeping enough of a RAM footprint on these underpowered consoles. Often times it's best not to add new features to console ports that lack enough RAM headroom, because that could shut the door on certain large ROMs from being able to be loaded into memory (and the alternative, virtual memory, is often times too slow to be worth bothering with).
> 
> Also, RGUI should consume less RAM than either XMB or Ozone. I'd honestly recommend for systems like 3DS you stay on RGUI, XMB/Ozone can eat up additional RAM with all the texture usage, and the 3DS simply doesn't have enough RAM headroom to get away with it.

New 3DS. I’m using RGUI


From my limited understanding, the problem is the ROM I loaded is 33mb. Before Endrift released mGBA 0.9 he was silently truncating larger ROMs because of the buffer cap which broke 64 MiB GBA Video ROMs. I don’t know what he did in later releases, perhaps returned to truncating between ROMs 32-64mb but they are working on standalone. I love Retroarch I just can’t load that specific rom with the mGBA core, unfortunately.

**Comment by Mcoogle** [comment]
> > > Maybe related, but Retroarch crashed the first time I loaded a rom using mGBA because the rom was too large. The standalone mGBA runs the rom fine but the latest core does not. I’ll try a fresh install and run a compatible rom to see if that fixes it.
> > 
> > 
> > Which 3DS? New 3DS or 3DS? When you turn on Show Memory Usage, how much RAM does it report being available before you load the game? Also, how big was this ROM?
> > It's a constant struggle keeping enough of a RAM footprint on these underpowered consoles. Often times it's best not to add new features to console ports that lack enough RAM headroom, because that could shut the door on certain large ROMs from being able to be loaded into memory (and the alternative, virtual memory, is often times too slow to be worth bothering with).
> > Also, RGUI should consume less RAM than either XMB or Ozone. I'd honestly recommend for systems like 3DS you stay on RGUI, XMB/Ozone can eat up additional RAM with all the texture usage, and the 3DS simply doesn't have enough RAM headroom to get away with it.
> 
> New 3DS. I’m using RGUI
> 
> From my limited understanding, the problem is the ROM I loaded is 33mb. Before Endrift released mGBA 0.9 he was silently truncating larger ROMs because of the buffer cap which broke 64 MiB GBA Video ROMs. I don’t know what he did in later releases, perhaps returned to truncating between ROMs 32-64mb but they are working on standalone. I love Retroarch I just can’t load that specific rom with the mGBA core, unfortunately.
> 
> As for ram usage: 68/255 MB The file size for the rom is 32,770 KB

@LibretroAdmin off-topic but do you know a workaround for this?

**Comment by LibretroAdmin** [comment]
@Mcoogle Best split this off in a new issue. I think we can close this one now that the PR has been merged.
