### ISSUE TITLE
windows 2000 version does not launch

### ISSUE THREAD

**Issue by gibs75** [libretro/RetroArch#14403]
Windows 2000 version uses GetAdaptersAddresses from iphlpapi.dll which is not available on Windows 2000 (only GetAdaptersInfo according to SDK documentation)

Have tried with W2000 SP4, and then W2000 udpate rollup1 + IE6 installed

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway Looks like we might have unintentionally broken the Windows 2000 version. Do you happen to remember what we used before GetAdaptersAddresses, and can we add a fallback path for Win2000 and earlier?

**Comment by LibretroAdmin** [comment]
@gibs75 can you maybe figure out the commit that broke win2000 support?

**Comment by gibs75** [comment]
Sorry. First time I try to use RetroArch :$
If I well understood MS Windows SDK doc, it seems only GetAdaptersInfo is supported on W2000.
GetAdaptersAddresses since Windows XP

**Comment by Cthulhu-throwaway** [comment]
It never had any code for older versions of Windows to begin with: https://github.com/libretro/RetroArch/blob/v1.9.0/libretro-common/net/net_ifinfo.c#L153-L201
This is from 1.9.0 and I didn't start contributing until around 1.9.11/1.9.12.

If those older Windows versions have their own unique project/make files, just get rid of HAVE_IFINFO for them, if not, wrap any code that require _WIN32 to be defined with this aswell:
`defined(_WIN32_WINNT) && _WIN32_WINNT >= 0x0501`

I won't refactor stuff from platforms that I don't work with, unless there is enough existing code to begin with.

**Comment by LibretroAdmin** [comment]
All I could find about pre-GetAdaptersAddresses functionality for Windows 2000 and lower is this -
https://stackoverflow.com/questions/2214488/equivalent-information-from-getadaptersaddresses-in-windows-2000-win2ksp4

Not sure if that is enough info to build a fallback for though.

**Comment by Cthulhu-throwaway** [comment]
Set these to 0:

https://github.com/libretro/RetroArch/blob/master/Makefile.griffin#L418
https://github.com/libretro/RetroArch/blob/master/Makefile.griffin#L474

Get rid of all HAVE_IFINFO in these files:

https://github.com/libretro/RetroArch/blob/master/pkg/msvc/msvc-2003/RetroArch-msvc2003.vcproj
https://github.com/libretro/RetroArch/blob/master/pkg/msvc/msvc-2005/RetroArch-msvc2005.vcproj

If someone ever implements ifinfo support for those archaic builds, he can then set those back in.

**Comment by LibretroAdmin** [comment]
Pushed this change -
https://github.com/libretro/RetroArch/commit/b32b1f277b82c6da05380a0ae18fea86b6e22ad5

**Comment by gibs75** [comment]
It launches now :) Thanks
