### ISSUE TITLE
(XMB) Option to remove Header in top left

### ISSUE THREAD

**Issue by oRuin** [libretro/RetroArch#14417]
Thisnis more of a feature request for XMB than a bug.
Would it at all be possible to have an option in the XMB settings to:

Hide the Header Text in the top left of the screen.
Hide the Game/Rom count in the bottom right of the screen while on a playlist.

The reason I am asking is that I personally enjoy designing Dynamic System Wallpapers and feel it would be nice to have the option of clearing these areas of text.

**Comment by sonninnos** [comment]
Bottom right one can already be removed via Playlists > Show Playlist Entry Index.
