### ISSUE TITLE
When zlib is not available, trying to take a screenshot will throw an error

### ISSUE THREAD

**Issue by ethanaobrien** [libretro/RetroArch#14422]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When trying to take a screenshot and zlib is not supported (or disabled when compiling) an error will be thrown and the screenshot will not be saved. I turned off zlib because I want to speed up save states, but this also broke screenshots.

### Expected behavior

The screenshot is expected to save. If zlib is turned off or not supported a warning should tell you that it is not supported rather than doing nothing.

### Actual behavior

Nothing

### Steps to reproduce the bug

1. Turn off zlib compiling flag
2. Boot the application
3. Try to take a screenshot

### Bisect Results

After some dissecting, this is happening because of this line: https://github.com/libretro/RetroArch/blob/83ce6f42d9720f9ce3dbfeca21a73322f49a20c8/libretro-common/formats/png/rpng_encode.c#L323

because you cannot initialize a stream from a library that does not exist. See this: https://github.com/libretro/RetroArch/blob/83ce6f42d9720f9ce3dbfeca21a73322f49a20c8/libretro-common/formats/png/rpng_encode.c#L230

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Linux/Windows/Chrome OS/MacOS/etc...
- Compiler: emscripten (so, web based)

**Comment by Cthulhu-throwaway** [comment]
You can disable save state compression through a setting (Settings -> Saving -> Save State Compression).
Take note that writing a larger uncompressed save state to disk might take longer than compressing and writing a smaller save state.

As for the bug in question, should be fixed by changing the line to:
```c
#if HAVE_ZLIB
   stream_backend = trans_stream_get_zlib_deflate_backend();
#else
   stream_backend = trans_stream_get_pipe_backend();
#endif
```

**Comment by ethanaobrien** [comment]
>Take note that writing a larger uncompressed save state to disk might take longer than compressing and writing a smaller save state.

I actually just read all my save states from memory (from the JavaScript side) so that parts not a problem for me

Should there be a thing where if zlib is not defined, that png should not be defined too? It was a little inconvenient to be debugging for an hour to find out it was because zlib was disabled

**Comment by Cthulhu-throwaway** [comment]
Why not just use the setting to not compress save states?

For platforms that use the configure script, you can add a check to disable HAVE_RPNG if HAVE_ZLIB is not enabled. For platforms which compile directly from their makefile, either the features need to be disabled manually together with HAVE_ZLIB or a check can be added to each makefile in order to disable some features, if we don't have HAVE_ZLIB.

**Comment by LibretroAdmin** [comment]
Our implementation of PNG (called RPNG) relies on zlib for the implementation. I think this is industry standard.

**Comment by ethanaobrien** [comment]
I'm saying, if the user disabled zlib, compiles the app, runs it, and tried to take a screenshot it fails without any error messages. Could we add an on screen error message so the user knows what happened

**Comment by LibretroAdmin** [comment]
Just enable rbmp support then, it should be enabled by default already. And 'rbmp' (our implementation of BMP) is not dependent on zlib, so it should fall back to that and just work.

**Comment by ethanaobrien** [comment]
Ok, thanks
