### ISSUE TITLE
[Regression] File browser menu header showing repeated strings

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#14455]
## Description

The menu header text shown when:

1. configuring the desired folders for any of the options under Settings -> Directory; or
2. selecting Import Content -> Manual Scan -> Content Directory 

seems to display repeated and/or meshed together strings. 

Parts of the filesystem path seem to be appended to the header text string. This is even more noticeable when browsing through a longer path, with multiple subfolders.

See here:

**(The hard-drive letter V is repeated here)**
![image](https://user-images.githubusercontent.com/17614150/193423035-000614af-8d07-4b08-b041-06a0ee50ae13.png)

**(When navigating to Folder 1, the text repetition gets worse)**
![image](https://user-images.githubusercontent.com/17614150/193423078-cfa02a0a-7ac3-4b0a-a772-97dd57097f8a.png)

### Bisect Results

@LibretroAdmin The commit that introduced this issue is 625e63c3cc71731968cc0687758c1d502fba41b3.

### Environment information

- OS: Windows 11 x64
- Compiler: Mingw64

**Comment by Cthulhu-throwaway** [comment]
strlcat requires a null-terminated string.
This isn't showing repeated strings, but rather concatenating at the first null character found. In my case it shows "s[only final part of path][path]".

I've given plenty of warnings about these pointless tinkering in the past, but was pretty much ignored. I am expecting new problems to be reported now that a new stable was released.
