### ISSUE TITLE
[Netplay] "Core does not support netplay"

### ISSUE THREAD

**Issue by michael-myers** [libretro/RetroArch#14457]
## Description

Tested with Genesis Plus GX v.1.7.4 on macOS x86-64. With RetroArch 1.10.3, Netplay was working. With an update to RetroArch 1.11.0, an attempt to connect to a Netplay host results in an interface notification "Core does not support netplay" on the client.

My workaround was to revert to RetroArch 1.10.3.

Filing this issue here because it does not seem to be a core bug, if the core is the same on both versions.

### Expected behavior

A netplay session to begin.

### Actual behavior

A message appears about the core not supporting netplay, which I believe to be an error.

### Steps to reproduce the bug

1. Set Netplay host
2. Load content, choosing the core Genesis Plus GX
3. Receive error

### Bisect Results

Started happening with an update to RetroArch 1.11.0. Does not happen with version 1.10.3.

### Environment information

- OS: macOS 12, x86-64

**Comment by Cthulhu-throwaway** [comment]
Update your core info files.
