### ISSUE TITLE
State slot screens get covered by the overlay

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/RetroArch#14451]
## Description

Screens are displayed below overlays, so they get covered

### Expected behavior

Would be better if the screens would be displayed on top

### Steps to reproduce the bug

Just load an overlay and try to load a save state if you have state screenshots enabled.

### Version/Commit
All versions

![309625657_1846898615641986_25689415396214002_n](https://user-images.githubusercontent.com/12124465/193377874-e7b5f81d-ef16-478f-9f45-3f299fe54c75.jpg)

**Comment by MrHuu** [comment]
I don't think the thumbnail should be seperated from the menu in this case.
Depending on the platform you're running, there's an option to show the overlay behind the menu.

```Settings > On-Screen Display > On-Screen Overlay > Show Overlay Behind Menu```

If not supported on your platform, disable the overlay while in menu.

```Settings > On-Screen Display > On-Screen Overlay > Hide Overlay in Menu```

**Comment by Tasosgemah** [comment]
> I don't think the thumbnail should be seperated from the menu in this case. Depending on the platform you're running, there's an option to show the overlay behind the menu.
> 
> `Settings > On-Screen Display > On-Screen Overlay > Show Overlay Behind Menu`
> 
> If not supported on your platform, disable the overlay while in menu.
> 
> `Settings > On-Screen Display > On-Screen Overlay > Hide Overlay in Menu`

Thank you, i wasn't aware about these options.
