### ISSUE TITLE
[Feature Request] Add a "Remove Core option"

### ISSUE THREAD

**Issue by Unounited** [libretro/RetroArch#14450]
Doing it manually is a bit okay to remove the core but It would be great to have an option in retroarch just incase we accidently downloaded a core that you didn't want

**Comment by hizzlekizzle** [comment]
There are 2 ways to do this already: either by loading the core and going to main menu > information > core information > delete core, or by going to settings > core > manage.

**Comment by LibretroAdmin** [comment]
Already implemented. It could perhaps be exposed in a more intuitive way but there are already 2 ways to do it as mentioned before.

**Comment by Mch81** [comment]
Hi, I tried both ways but none of them works. All seems to be OK but after double check core is not deleted. I run the latest RetroArch on the latest ipadOS.
Any help.

**Comment by MagicCat28** [comment]
I’m on iOS and these don’t show up. It looks like there is no way to delete cores on iOS at all because the files are hidden. Please help.

**Comment by hizzlekizzle** [comment]
@MagicCat28 yes, that's correct. Apple doesn't allow us to do things that would disrupt the integrity of the application after it's installed.
