### ISSUE TITLE
Wrong version number in retroarch/retroarch-metal macOS download 1.11.0 (stable)

### ISSUE THREAD

**Issue by suschizu** [libretro/RetroArch#14468]
## Description

downloads 
https://buildbot.libretro.com/stable/1.11.0/apple/osx/x86_64/RetroArch.dmg
https://buildbot.libretro.com/stable/1.11.0/apple/osx/universal/RetroArch_Metal.dmg

still contain version 1.10.3 instead of 1.11.0 

looks like the `info.plist` wasn't updated - it shows:

```
CFBundleShortVersionString:
1.10.3

CFBundleVersion:
1.10.3

```

### Steps to reproduce the bug
<img width="391" alt="Screenshot 2022-10-03 at 20 22 13" src="https://user-images.githubusercontent.com/16004333/193651717-d60d4254-8758-482e-9455-1d4aa2bba6e8.png">

- RetroArch: [version/commit]
1.11.0

### Environment information

macOS 12.6

**Comment by core-code** [comment]
i can confirm the problem

**Comment by LibretroAdmin** [comment]
Should be fixed in this commit - https://github.com/libretro/RetroArch/commit/389ef31a8f4a505f255e9bfebe882750d22ab490

We're releasing a new stable (1.11.1)

**Comment by suschizu** [comment]
great thanks for the fast fix

**Comment by core-code** [comment]
thanks!


one other thing i noted is that the metal download link links to the nightly version. all other links point to the latest stable
 release. is this on purpose?

<img width="709" alt="Screenshot 2022-10-04 at 15 57 34" src="https://user-images.githubusercontent.com/1261954/193839421-270672b7-3ed3-4f1c-9214-26d1454cb18d.png">

**Comment by LibretroAdmin** [comment]
OK, we will fix that link.
