### ISSUE TITLE
ios Audio Issue 1.11.0 version

### ISSUE THREAD

**Issue by zhouyun2020** [libretro/RetroArch#14462]
when i leave the retroarch to another app and then come back, the sound of the games disappears, unless close the retroarch and relaunch it, the sound comes back. Is it a bug?

**Comment by yoshisuga** [comment]
Yes, this is a known issue on iOS 15. I don't know why this is happening and wasn't able to nail down the cause of it.

After updating to iOS 16 though, I haven't encountered this much in practice. Will continue to test.

**Comment by stijnie2210** [comment]
Bit late to the party, but this has been happening to me on iOS 18 and 26 again
