### ISSUE TITLE
./configure --enable-network_video option fails to build

### ISSUE THREAD

**Issue by jason-oliveira** [libretro/RetroArch#14460]
## Description

when trying to run `./configure`, the `--enable-network_video` option causes the subsequent `make` compilation of [gfx/drivers/network_gfx.c](https://github.com/libretro/RetroArch/blob/master/gfx/drivers/network_gfx.c) to fail.

### Expected behavior

Compilation of [gfx/drivers/network_gfx.c](https://github.com/libretro/RetroArch/blob/master/gfx/drivers/network_gfx.c) succeeds.

### Actual behavior
![20221002_011500 - Screenshot](https://user-images.githubusercontent.com/11582807/193440713-8b2a4f78-1d73-4d56-b9f8-4007ad962ac9.png)
[RABrokenMake.txt](https://github.com/libretro/RetroArch/files/9691907/RABrokenMake.txt)

### Steps to reproduce the bug

1. Install a working build environment in your linux distribution.
2. download and extract RetroArch v1.11.0 source
3. run `./configure --enable-network_video`
4. run `make` (I prefer ````make -j`nproc` ```` )

### Bisect Results

`./configure --help` provided no information. 

### Version/Commit
- RetroArch: v1.11.0

### Environment information

- OS: Gentoo Linux
- Compiler: ```
gcc (Gentoo 11.3.0 p4) 11.3.0 ```

**Comment by LibretroAdmin** [comment]
See if 7df0157af5d735a3c7704f287eb90be9f0ff6a8a fixes it

**Comment by jason-oliveira** [comment]
confirmed fixed.
