### ISSUE TITLE
Display only black screen in window, on MacOS 13 ventura

### ISSUE THREAD

**Issue by djhan** [libretro/RetroArch#14474]
## Description

Retroarch(metal) display black screen in window from startup, on development builds of macOS ventura.

### Expected behavior

Retroarch display menu in window from startup. Also window fill full screen when I toggle [video>fullscreen mode] to on.

### Actual behavior

When I launch Retroarch, it display only black screen in window, and cursor will be disappeared. But only titlebar button(close/minimize/maximize) was work. If I click maximize button, window will be maximized and display menu.
If I toggle [video>fullscreen mode] to on, nothing was changed. Retroarch still in winodw mode. Also I re-launch retroarch, it'll started as window mode.

### Steps to reproduce the bug

1. Update to latest MacOS ventura (beta 9)
2. Install Retroarch(metal) nightly build
3. Run Retroarch

### Bisect Results

This symptom wasn't show in previously openGL version of Retroarch

### Version/Commit

- RetroArch: nightly build

### Environment information

- OS: MacOS ventura beta 9 / Mac Studio

**Comment by LibretroAdmin** [comment]
No issues whatsoever here, but then again I'm not using a MacOS beta version.

I'm on MacOS Monterey (version 12.5.1), video outputs just fine. MacBook Pro (13-inch, M1, 2020).

**Comment by djhan** [comment]
> No issues whatsoever here, but then again I'm not using a MacOS beta version.
> 
> I'm on MacOS Monterey (version 12.5.1), video outputs just fine. MacBook Pro (13-inch, M1, 2020).

Yes. you're right. It's no problem on MacOS Monterey.

**Comment by jaildesigner** [comment]
I have the exact same problem. Retroarch can't go fullscreen on macos ventura. It's not working with retroarch 1.11.1 nor the nighties 1.12.0

**Comment by LibretroAdmin** [comment]
I can reproduce this issue on the final public release (Ventura). Did something fundamental change with regards to fullscreen toggling that has to be addressed now specifically for Ventura?

**Comment by jabu10245** [comment]
I can confirm this behavior. After the upgrade to macOS Ventura today, I get only a black window after starting RetroArch and fullscreen mode is not working. Toggling fullscreen on/off does not seem to change anything. In the system menu "Window" the menu item "Enter Full Screen" is disabled.

**Comment by LibretroAdmin** [comment]
I do get a picture in windowed mode with the Metal version, but fullscreen toggling is not properly working.

We'll need an Apple/Metal expert of some sorts to tell us what happened from Monterey to Ventura that would cause such issues with our code.

**Comment by LibretroAdmin** [comment]
Can you guys confirm if the PR fixes it?

**Comment by jabu10245** [comment]
Yes that fixed it on my end. RetroArch opens in fullscreen mode again.

**Comment by LibretroAdmin** [comment]
Awesome to hear. How about you @djhan ?

**Comment by djhan** [comment]
> Awesome to hear. How about you @djhan and @jaildesigner ?

Hello, I downloaded nightly build. It works well in fullscreen mode on MacOS Ventura.
Thanks your support.

**Comment by jaildesigner** [comment]
> Awesome to hear. How about you @djhan and @jaildesigner ?

Works again! macos ventura on M1 chip. Thanks for the quick fix!!
