### ISSUE TITLE
(Wii U) Can't log in to Retroachievements in 1.11.0

### ISSUE THREAD

**Issue by dekgear** [libretro/RetroArch#14471]
After updating to v.1.11.0 on Wii U, it attemped to log in to Retroachievements once, failed, and now it won't attempt to log in anymore. This makes it impossible to obtain any achievements.

My username and password are correct, as I tried to log in in v.1.10.3 afterwards and it logged in just fine. I also tried it on Steam v.1.11.0 and it also worked, so it seems to be an issue on the Wii U version.

**Comment by LibretroAdmin** [comment]
Could be a regression, a lot of major netplay changes were made. Unfortunately this could prove quite tricky to solve if at all. Would be nice if you could do a bisect and go over most of the netplay related commits and figure out at what point it broke down.

**Comment by LibretroAdmin** [comment]
@dekgear Can you check if this PR fixes this for you on WiiU? Nightlies should be up on the buildbot for WiiU before the end of the day. https://github.com/libretro/RetroArch/pull/14483

**Comment by dekgear** [comment]
Ok, I'll test it ASAP.

**Comment by dekgear** [comment]
It's fixed in the lastest nightly, it's connecting to the Retroachievements page again and achievements are working properly! Thanks for looking into the issue and the quick fix!

**Comment by LibretroAdmin** [comment]
Awesome, thanks for letting us know.
