### ISSUE TITLE
D3D12 driver - Everything becomes distorted when resizing the window

### ISSUE THREAD

**Issue by PoloniumRain** [libretro/RetroArch#14473]
When using the D3D12 video driver with RetroArch 1.11.1, resizing the window will make everything look stretched and distorted (example below). This includes both the RetroArch user interface and any core/game that i've tried so far. It only happens with the D3D12 video driver. All other drivers do not have this behaviour, and this problem doesn't exist with 1.10.3.

![Stretched](https://user-images.githubusercontent.com/50634894/193932777-7e862a07-dee6-4dde-a5fa-b744a82b6e86.jpg)

The OS used is Windows 10, with a clean install of RetroArch 1.11.1.
GPU is a RTX 3080 with driver version 517.48 (currently the latest).

**Comment by LibretroAdmin** [comment]
I don't have this issue, it auto-adjusts itself after you let go of the left mouse button to resize.
