### ISSUE TITLE
Runtime error on Windows XP SP3

### ISSUE THREAD

**Issue by PseudoDistant** [libretro/RetroArch#14479]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Runtime error on Windows XP SP3

> The procedure entry point WSAPoll could not be located in the dynamic link library WS2_32.dll

I am using the Windows XP/Vista build from the Retroarch website

### Expected behavior

Retroarch starting

### Actual behavior

Retroarch doesn't start, instead opening a dialog window stating "The procedure entry point WSAPoll could not be located in the dynamic link library WS2_32.dll"

### Steps to reproduce the bug

1. Install Retroarch on Windows XP SP3 (Installer or download, happens with either)
2. Attempt to start Retroarch

### Environment information

- OS: Windows XP SP3 (Version 5.1.2600)

**Comment by LibretroAdmin** [comment]
This should deal with the issue I hope -

https://github.com/libretro/RetroArch/commit/d832ce15d6eccdd40953213321142a2fcca91b3b

What I have done, is only selectively define NETWORK_HAVE_POLL for platform builds that target Vista and above. So the regular Mingw-w64 version, MSVC2012, 2013, 2015, 2017, 2019, and UWP versions should all have poll support through WSAPoll. Anything below (VC6/MSVC2003/MSVC2005/MSVC2008/MSVC2010) will resort to select() instead.

**Comment by LibretroAdmin** [comment]
Made a new implementation that is less problematic I think -
https://github.com/libretro/RetroArch/commit/b3bb62881a8b0bfc42bce0501ff55cd6dfe07d96

**Comment by LibretroAdmin** [comment]
Get the latest nightly on the buildbot.

**Comment by PseudoDistantViaXP** [comment]
Can confirm
