### ISSUE TITLE
[Vulkan] Getting a lot of validation errors when using PCSX ReARMed (and possibly other cores?)

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#14484]
## Description

First, I'm not entirely sure if this is a RetroArch issue or a PCSX ReARMed one, so far I've only managed to get these validation errors with this core but maybe others are affected, I'll try to test more cores later.

Anyway, the issue! When starting a game with PCSX ReARMed with RA built with VK debug it spams a lot of validation errors when loading a game: [logs.zip](https://github.com/libretro/RetroArch/files/9723850/logs.zip)

Basically it spams this error:

`[ERROR] [Vulkan]: Validation Error: Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-04150 ] Object 0: handle = 0x93013d000000066e, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xf72a82b8 | vkUpdateDescriptorSets() pDescriptorWrites[0] failed write update validation for VkDescriptorSet 0x93013d000000066e[] with error: Write update to VkDescriptorSet 0x93013d000000066e[] allocated with VkDescriptorSetLayout 0x3399850000000669[] binding #2 failed with error message: Attempted write update to combined image sampler descriptor failed due to: Descriptor update with descriptorType VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER is being updated with invalid imageLayout VK_IMAGE_LAYOUT_UNDEFINED for image VkImage 0x58baf50000000676[RetroArch image (463)] in imageView VkImageView 0x9aa73c0000000677[]. Allowed layouts are: VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL, VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL, VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER the imageLayout member of each element of pImageInfo must be a member of the list given in Combined Image Sampler (https://vulkan.lunarg.com/doc/view/1.3.224.1/windows/1.3-extensions/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-04150)`

on ~500 lines, the only difference being different addresses. After that initial spam it doesn't seem to show up anymore until I close content and start the game again (the errors don't show up again with a simple Quick Menu > Restart).

That's with a GTX 970 and drivers 516.94 if it matters.

### Steps to reproduce the bug

1. Build RetroArch with `VULKAN_DEBUG=1`.
2. Set Vulkan as video driver.
3. Start a game using PCSX ReARMed core.

### Bisect Results

No idea.

### Version/Commit

- RetroArch: 1.11.1 / 8e9d19568cf2feeb2fd992bfe667c6978a640a39

### Environment information

- OS: Windows 10
- Compiler: gcc version 12.2.0 (Rev1, Built by MSYS2 project)

**Comment by LibretroAdmin** [comment]
PCSX ReARMed does not have a GPU API hardware renderer or anything, the only peculiar thing it might do is duped frames.

**Comment by bslenul** [comment]
Just noticed today by launching a game with a FMV with PCSX ReARMed that disabling frame duping may remove the validation errors but it makes the FMVs super glitchy:

https://user-images.githubusercontent.com/33353403/195898920-31f8fa1d-17c5-4738-9c04-2819ae09b9b5.mp4

Only happening with VK. Is this a VK/RA issue or should I open one in the PCSX repo?

**Comment by bslenul** [comment]
Closing in favor of #15950
