### ISSUE TITLE
Fullscreen not working on Wayland

### ISSUE THREAD

**Issue by nfp0** [libretro/RetroArch#14481]
## Description

When running RetroArch in Wayland mode, and having it set to fullscreen, it opens in fullscreen, as expected. But when I go and run a game on a core, it reverts back to a small window.

This does not happen when forcibly running RetroArch on X11 mode, where fullscreen works as expected.
From the cores I tested, it happens on Mesen, bsnes-mercury and Mupen64Plus-Next. It does NOT happen on Genesis Plus GX, mGBA and SameBoy.

I've tried Vulkan, GL and GLCore but they all have the same behavior. The `Windowed Fullscreen Mode` setting makes no difference.

Pressing F makes the window resize to a different sized window, and pressing F a second time makes it finally go fullscreen.

### Expected behavior

RetroArch should respect the fullscreen option.

### Actual behavior

RetroArch returns to a small window when starting a game.

### Steps to reproduce the bug

1. Open RetroArch on Wayland.
2. Enable `Start in fullscreen mode` and save your settings.
3. Start a game on Mesen, bsnes-mercury or Mupen64Plus-Next.
4. Observe RetroArch going back to windowed mode.

### Bisect Results

I know it was happening at least as far back as 1.10.2, but probably before that too.

### Version/Commit

- RetroArch: 1.11.1

### Environment information

- OS: Manjaro KDE

**Comment by ColinKinloch** [comment]
What desktop do you use?

**Comment by nfp0** [comment]
I'm using KDE Wayland.
I'll test your PR in a bit.

**Comment by nfp0** [comment]
After discussion on https://github.com/libretro/RetroArch/pull/14485 it has become apparent this is an issue related to Kwin and not RetroArch, so I'm closing this.
