### ISSUE TITLE
Steam store version will not install on Steam Deck; locks up device.

### ISSUE THREAD

**Issue by Dahak66** [libretro/RetroArch#14480]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I am no longer able to install the Steam store version on a Steam Deck. Even so much as accessing the Retroarch installation page will prevent the "steam" and "..." keys from working, will prevent starting any other software, and will not allow the device to shut down cleanly. Even factory resetting the Steam Deck will not allow this to install. I have also filed a bug report with Valve/Steam in case it is a "them" issue rather than an RA one.

### Expected behavior

RetroArch should install and be accessible from Steam Deck menu. All buttons should remain active, and steam deck should be able to turn off properly.

### Actual behavior

When trying to click or press the "install button" on the RetroArch steam store page (specifically on the Steam Deck) it will not do anything, but the "steam" and "..." keys will stop working, no other software starts, wifi ceases (any active downloads are frozen in place), and the device will not shut down cleanly

### Steps to reproduce the bug

1. Search out Retroarch in the Steam store or access the Retroarch "page" from your steam library.
2. Try to install it by pressing the "Install button."

### Bisect Results

Sometime after September 20th. I had previously installed it successfully on Sept. 14. On the 20th I removed the store version to install the flatpack version of Retroarch. I tried to reinstall the Steam store version on October 1st with no luck.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.10.3 at first attempt, 1.11.0 at last attempt.

### Environment information

- OS: SteamOS
- Compiler: n/a

**Comment by LibretroAdmin** [comment]
Seems to update and work fine on my Steam Deck.

Asked Mats to test too and seemed to work fine for him too.

**Comment by Dahak66** [comment]
Not update... I'm not talking about an already installed copy (I have no way of knowing if that would work as I didn't have the problem prior to uninstalling it.)  Did you uninstall it and try to install it again?

**Comment by Dahak66** [comment]
Great. That is truly puzzling then. It's absolutely an issue on my side. And just tried it again after factory resetting yet again, with no change in my symptoms as listed.

**Comment by LibretroAdmin** [comment]
Maybe do a factory reset if you are on a beta version of SteamOS. I don't think it's a problem even to do with RetroArch.

**Comment by Dahak66** [comment]
I'm using a stable version of SteamOS, and as mentioned in the ticket and the last post, I have factory reset twice. Are you using a beta or preview version? There has to be a reason that I'm getting different results than you. RetroArch is literally the only app out of 160+ in my library that is having these symptoms. I do have a ticket open with Valve/Steam as well, so I'll wait on their response.

**Comment by LibretroAdmin** [comment]
@Myaats cannot reproduce either. Dunno what to tell you.

**Comment by Myaats** [comment]
@Dahak66 Will it download without issues on a PC? It will let us narrow it down to account or device.

**Comment by Dahak66** [comment]
@Myaats Yes, I installed it recently on a PC to confirm. I suspect it's a steam store issue of some sort, but as you both aren't experiencing it, I'm perplexed. Myself and one other user on Reddit are the only ones who have said anything about it. With most people only discussing the flatpack version, it's hard to figure out if no one else is experiencing it or if it's just no one else using it.

**Comment by Myaats** [comment]
I assume a factory reset only resets some Steam state but leaves the library alone, I suspect there might be an issue with your Steam Library (games on disk) on the Deck since RetroArch depends on having `Steam Linux Runtime - Sniper` installed, in short it is a dependency managed by Steam. If you go inside the steam library folders both on the SSD/eMMC on the Deck and SDCard (if you have one) and delete RetroArch and SteamLinuxRuntime_sniper and then reboot.

Are you still able to reproduce the issue when trying to install?

**Comment by Dahak66** [comment]
Okay, it turns out that Sniper was not installed at all (Soldier is, along with one runtime with no military title). RetroArch has no remnants installed, nor does Sniper. Unfortunately, it's still not installing (accessing the store page for RetroArch in either game or desktop mode partially locks things up, as described in the initial ticket.) 

I then tried installing Sniper, and tried to access RetroArch but had the same results. Does anything else use Sniper? I think that it did download the sniper dependency back in mid September when I first installed RetroArch on the Deck, but nothing (else) seems to be requiring that dependency now, just soldier and the unnamed one.

**Comment by Myaats** [comment]
At this point it seems like a Steam Client issue on your unit, you'll probably have to wait for Valve that will hopefully ask for the correct logs to investigate.

**Comment by Dahak66** [comment]
Thanks for giving a shot! It does seem more likely to be something on the steam client side, so hopefully they can get it sorted for me. Thanks, again!

**Comment by Dahak66** [comment]
Okay, wouldn't you know, third time's a charm. I factory reset a third time. The only thing I did different was install RetroArch first, before anything else. It installed sniper then RA without issue. Not sure what happened the other times, but I'll get out of your hair. Thanks again for all the troubleshooting!

**Comment by Ciocolici** [comment]
I just wasted 4 hours troubleshooting, thinking my Steam Deck was faulty, instead it was all RetroArch! I uninstalled it, and wanted to reinstall it. Everytime I clicked to install it it would bug my Steam Deck and make it full unrespensive that most buttons wouldn't work anymore, and neither the Steam Deck UI. Only hard resetting "fixes" it. Just so you know, the issue the OP @Dahak66 had, I just had as well. So it still is an issue today.

**Comment by Ciocolici** [comment]
> Works fine on a Steam Deck here. Your mileage may vary. 
> 
> Not sure what you want us to do about this when we can't reproduce it on our end.

What you gonna do or not do about it is your choice. Take my comment only as a report that this issue still occurs, but installing it through desktop mode "fixes" it.

**Comment by LibretroAdmin** [comment]
But installing it through regular SteamOS works for me here.

**Comment by Ciocolici** [comment]
> But installing it through regular SteamOS works for me here.

I don't know how you can reproduce this issue. All I can say is that I had the folder form RetroArch opened while uninstalling, then trying to install it through the Gaming Mode would start this issue. I tried deleting the RetroArch folder, did not help. But installing it in desktop mode worked. That is all I can say :D Maybe it is a SteamOS issue at its core, I don't know

**Comment by breadone** [comment]
Still happening in 2025! First time installing it on this specific Deck, but I did install it on another Deck previously.

Simply switching into desktop mode and installing it from there worked perfectly, and it launches now with no issues.
