### ISSUE TITLE
Fullscreen thumbnail display bug when browsing playlist.

### ISSUE THREAD

**Issue by JustDevs** [libretro/RetroArch#14493]
## Description

Whenever you press start on a game with no thumbnail art (whether it's a screenshot or boxart of the game) and then move the selection to a game with thumbnail art, the art of the game shows up fullscreen.

### Expected behavior

I expected that the artwork won't go fullscreen when I moved the selection.

### Actual behavior

The artwork shows up by itself once you move the selection on a game with thumbnail.

### Steps to reproduce the bug

1. Place the selection to the game without thumbnail.
2. Press start key on controller or whatever the "fullscreen thumbnail" key on keyboard is.
3. Move the selection to a game with downloaded thumbnail.

Here is a video preview of the bug, I used a dualshock overlay to show the inputs.

https://user-images.githubusercontent.com/22374647/194512367-81ccc472-dd68-4807-9c1b-f6499e6b9769.mp4

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit

- RetroArch: 1.11.1

### Environment information

- OS: Windows 10

**Comment by sonninnos** [comment]
Why is this a bug exactly? Fullscreen toggle stays in fullscreen mode. It would be a mess if it would toggle itself off on every item that does not have thumbnails. Sure it might be more clear if it can't be enabled when there is no thumbnails, but getting that information at the right moment in the menu driver can be tricky.

**Comment by JustDevs** [comment]
> Why is this a bug exactly? Fullscreen toggle stays in fullscreen mode. It would be a mess if it would toggle itself off on every item that does not have thumbnails. Sure it might be more clear if it can't be enabled when there is no thumbnails, but getting that information at the right moment in the menu driver can be tricky.

It's fine if it doesn't toggle off when going through the playlist. What I'm saying is that it shouldn't go fullscreen when pressing start on a game without thumbnail and then scrolling on a game that has one. It just feels awkward.
