### ISSUE TITLE
[windows x64 nightly builds] savefile / statefile paths revert to default

### ISSUE THREAD

**Issue by SedrynTyros** [libretro/RetroArch#1449]
Whether you change them manually in the cfg file or through RGUI the changes make no difference.  :\savefile and :\statefile are always used as the paths.

**Comment by fr500** [comment]
This doesn't happen. Are you sure config autosave is enabled? are you using any third party launcher?

**Comment by SedrynTyros** [comment]
Example.  Right now for my bsnes config, here are the settings in my cfg file:

savefile_directory = ":\savefile\bsnes-balanced"
savestate_directory = ":\savestate\bsnes-balanced"

It doesn't use either of those paths though.  It always uses :\savefile and :\savestate.  I tried changing them in RGUI and saving the change as a new config.  In the new cfg file shows those bsnes-balanced paths but it doesn't actually use them.  It always uses :\savefile and :\savestate

**Comment by fr500** [comment]
That hasn't changed in forever. That's how it works.
If you use different configs for different cores then use per-core configs of use the appendconfig option.

Retroarch always saves to the specified cfg file (if none, then retroarch.cfg)

**Comment by SedrynTyros** [comment]
Okay, working as intended then.  Thanks for the help.
