### ISSUE TITLE
Duckstation core crash when open a CHD game on 1.11.0 and 1.11.1

### ISSUE THREAD

**Issue by eclaircs** [libretro/RetroArch#14496]
## Description

[Description of the bug]
When using Duckstation core to play CHD game, retroarch will crash when game start.

### Expected behavior
Same core work correctly on 1.10.3 and older version.

### Steps to reproduce the bug

1. Open Retroarch 1.11.0 or 1.11.1
2. Dowload Duckstation core, and load it.
3. Using Duckstation core open  a CHD format PS1 game.

### Version/Commit
- RetroArch: 1.11.0, 1.11.1

### Environment information

- OS: Windows 7 Ultimate 64bit
- Thinkpad X240, Core i5 4300U, 8GB RAM

**Comment by LibretroAdmin** [comment]
We don't support that core. We do support SwanStation though.
