### ISSUE TITLE
Strange file name spacing and redundant file naming for certain controller profiles. 

### ISSUE THREAD

**Issue by BParks21** [libretro/RetroArch#14507]
Using the online updater to download the latest controller profiles contains some oddly named controller profiles. Some of these profiles contain strange spacing before the file extension .cfg or a redundant name like, 8Bitdo NES30 Pro   8Bitdo NES30 Pro.cfg
I made a list of the files that seem to be named incorrectly. 

Some of these are found in more than one sub folder within the auto config folder. 

List:

USB GAME Controller
SPEEDLINK COMPETITION PRO Game Controller for Android
SPEED-LINK Competition Pro
NES PC Game Pad
SNES PC Game Pad
GAMESAIKE USB GAME Controller 

8Bitdo NES30 Pro   8Bitdo NES30 Pro

GAMESAIKE USB GAME Controller
Generic   USB  Joystick
Microntek              USB Joystick
SNES PC Game Pad    SNES PC Game Pad

**Comment by cmitu** [comment]
This would be better reported in [retroarch-joypad-autoconfig](https://github.com/libretro/retroarch-joypad-autoconfig/issues) repo, which hosts those assets.
The explanation is simple - the file names are created based the name reported by the joystick/controller itself, which contains those spaces (or redundant names). When creating a auto-configuration profile from RetroArch, the filename generated followed the naming reported by said controller.

**Comment by BParks21** [comment]
I see. Well if that's normal behavior I'll just close then.
