### ISSUE TITLE
retroarch-joyconfig: Wait a second after btn/axis detection

### ISSUE THREAD

**Issue by gizmo98** [libretro/RetroArch#1451]
retroarch-joyconfig reacts to fast with some joypads. If you press a button/axis joyconfig adds this button/axis to multiple targets. Could you please add a pause of 0.5/1s between every button/axis detection?

**Comment by fr500** [comment]
Same for the in-menu mapper, it would be good to have a delay yeah.

**Comment by twinaphex** [comment]
retroarch-joyconfig is removed now, closing this.

Use the built-in menu to map gamepads now.
