### ISSUE TITLE
Steam Deck - Shader presets dont load, when video driver is set to glcore

### ISSUE THREAD

**Issue by notimp** [libretro/RetroArch#14528]
Flatpack version, current release ( RetroArch 1.11.1 ).

Load game, set shader preset with any slang shader. Save as game preset. Exit core. If video driver is set to vulkan, upon loading the game shader preset will be loaded.

If its set to glcore, shader passes will always default back to 0 and the shader will not load.

Seems like a fairly new regression.

**Comment by hizzlekizzle** [comment]
Ok, I was able to reproduce it, bisected it and it seems to be caused by this commit:
9e39abcd0026fe3ffca674e6b27b10a949f63621
and for once, it's a perfectly logical commit to have caused it lol

**Comment by LibretroAdmin** [comment]
Very ironic, that's all I can say...

I'll try to see what we can do. Hopefully we can do a partial revert leaving the innocuous bits in.

**Comment by hizzlekizzle** [comment]
I tried reverting the 2 sections that mention anything about shaders but that didn't appear to fix it. The whole file won't revert cleanly, either, it seems, since there's been a few other commits that have touched it since then. :/

**Comment by notimp** [comment]
> @notimp Can you try a nightly build and see if it's fixed for you?

Not fixed in 1.12.0 flatpak (sorry I'm reliant on Discovery store updates on the steamdeck. :) )

But I will try it with future versions. :)

**Comment by hizzlekizzle** [comment]
> Not fixed in 1.12.0 flatpak

That's to be expected. It won't be reflected in a stable release until we put out the next one.
