### ISSUE TITLE
[ALL] core information not showing up of the last selected core

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1453]
On startup if you hit core information it's empty, even though a core info file exists. If you select the core manually it works on PC at least. On PSP the information panel is never populated

**Comment by Awakened0** [comment]
It does this when I load a game directly from the command line when specifying the core in the config I load.

**Comment by fr500** [comment]
because you already loaded the core at that point

**Comment by twinaphex** [comment]
This has been changed now. The last selected core will no longer be retained, fixing the problem itself. I might add an option to remember the last selected core later on.
