### ISSUE TITLE
[3DS] GLUI Menu Driver is missing assets

### ISSUE THREAD

**Issue by Jaffacakelover** [libretro/RetroArch#14544]
`Warning: Missing assets, use the Online Updater if available`

Retroarch 3DS complains about missing assets if the menu driver is switched to GLUI, prompting the user to download assets... but there's no Update Assets option in the Online Updater menu.

I tried adding the Ozone assets in manually: First using Universal Updater (which is _incredibly_ slow and saves the assets into `sdmc:/retroarch/media` instead of `sdmc:/retroarch/assets`), then by putting the SD card into a computer and adding `sdmc:/retroarch/assets/ozone` from the buildbot.
Sadly, it still complains about missing assets. They must have to go in a differently named folder / file structure. I tried `sdmc:/retroarch/assets/glui`, and moving everything out of subfolders into `sdmc:/retroarch/assets/glui`. Neither worked.

The buildbot for Retroarch was recently tweaked to only include the XMB Monochrome Assets by default (https://github.com/libretro/RetroArch/issues/12141#issuecomment-1242789019), which could have caused this side effect.

Options to solve this issue in Retroarch 3DS builds:
- Remove/Disable the GLUI menu driver.
- Rewrite GLUI to use XMB Monochrome assets instead of Ozone assets.
- Include Ozone assets in the package?
- Add/enable the 'Update Assets' option in the Online Updater menu.

**Comment by Yrouel** [comment]
1.11.0 is the latest with the full complement of xmb themes and there was no "ozone" or "glui" folder inside assets just "ctr" "menu_widgets" "rgui" and "xmb".
I'd try first if that version also gives you the same error just in case it was preexisting and you happened to notice it now after the xmb theme pruning

**Comment by Jaffacakelover** [comment]
I've checked all the stable 3DS versions between 1.12.0 and 1.9.0 (the buildbot only goes back to 1.9.0), and GLUI assets were missing from all of them. So they disappeared before August 2020?

(`media` folder renamed to `assets` = 1.9.2)
(`ctr` folder added = 1.9.9)
(bottom screen gui added / bottom screen log removed = 1.9.9)

I've found a backup on my PC of the `assets/glui` folder and its matching `src` folder! I couldn't tell you which version they're taken from, but they work when I add them to my 3DS. I could put them into a pull request to get them reinstated?

**Comment by Yrouel** [comment]
> I've checked all the stable 3DS versions between 1.12.0 and 1.9.0 (the buildbot only goes back to 1.9.0), and GLUI assets were missing from all of them. So they disappeared before August 2020?

I don't know, I'm suggesting to check 1.11.0 to verify if the problem could be related to the pruning of the themes or not. In other words if it still happens in 1.11.0 it means it's not caused by having removed all the themes but monochrome from xmb

**Comment by Jaffacakelover** [comment]
Yes it still happened in 1.11.0, so it's not related to the xmb themes pruning. The fluid theme is a separate set (like Ozone) that was pruned in some earlier version.

**Comment by Yrouel** [comment]
It seems more likely this is not a bug per se but just a forgotten menu option

**Comment by LibretroAdmin** [comment]
Pushed this commit so far which just removes the warning - I never quite liked this warning message anyway and the asset system needs a complete revamp, but it will take probably longer than a month, so for now just removing the message during the interim period is a good enough hotfix -

https://github.com/libretro/RetroArch/commit/3c7e4b032edda6eef694b6f3558a43add50b4ea6

**Comment by Yrouel** [comment]
> Pushed this commit so far which just removes the warning

Shouldn't the better fix be to remove the problematic leftover glui option from the menu?
Like won't this fail silently now?

**Comment by LibretroAdmin** [comment]
> > Pushed this commit so far which just removes the warning
> 
> Shouldn't the better fix be to remove the problematic leftover glui option from the menu? Like won't this fail silently now?

What problematic leftover glui option are you talking about?

LIke try to explain more clearly what you think the issue is.

**Comment by LibretroAdmin** [comment]
@MrHuu Got any idea what is going wrong here?

**Comment by Yrouel** [comment]
> What 'problematic leftover glui option' are you talking about?

First sentence from OP:

"Retroarch 3DS complains about missing assets if the menu driver is switched to GLUI"

If you just remove the warning won't selecting GLUI just fail silently now?
Which means shouldn't you just remove the option to select GLUI in the first place given that seems to be broken anyway?

**Comment by LibretroAdmin** [comment]
I see no reason to jump to that conclusion. It would just simply not render certain missing assets, but those assets are probably not even ones that are important for the default theme.

**Comment by LibretroAdmin** [comment]
Removed MaterialUI as per @MrHuu 's recommendation -
https://github.com/libretro/RetroArch/commit/6176b6a7646b2bf36ccfc128eca71b59c8873183
