### ISSUE TITLE
[Linux/Vulkan/Wayland] Visual and audible stuttering when playing games using vulkan

### ISSUE THREAD

**Issue by jonulrich** [libretro/RetroArch#14547]
## Description

Excessive demand on gpu during gameplay when using vulkan on wayland, causing games to stutter.

### Expected behavior

Same or similar performance whether game is running at 1 to 1 resolution in window mode or scaled to fullscreen.

### Actual behavior

Gameplay is smooth when run in window mode at its original resolution and up to 3x, but stutters visually and audibly when scaled any higher and especially when scaled to fullscreen.

### Steps to reproduce the bug

1. Run any (3d?) game using the vulkan video driver.

### Bisect Results

Just started trying to run PS1 games for the fist time since switching to wayland so not sure if this is something that worked well before, but I did make sure that everything works as expected with xorg on the same system, and it did indeed. And I found that the problem persists on ParaLLEI 64 when configured to use vulkan. I ran intel_gpu_top and when playing a heavy 3d scene in beetle psx hw in window mode with window scale set to 1 the load was about 6-7% but scaled to fullscreen(2256 x 1504) it averaged around 57-60%. Incrementally raising the window scale does indeed also raise the gpu load incrementally and substantially. 

### Version/Commit

- RetroArch: 415925c5dc

### Environment information

- OS: Arch Linux
- DE: Gnome
- Hardware: Framework Laptop / intel i5 1135g7

**Comment by ColinKinloch** [comment]
This may be resolved by #15065

**Comment by jonulrich** [comment]
Can confirm resolution
