### ISSUE TITLE
RetroArch in BlackBerry 10 stops to work when connect Moga Pro gamepad

### ISSUE THREAD

**Issue by leandroal** [libretro/RetroArch#1456]
RetroArch works great, but when I connect my Moga Pro controller, open RetroArch and try to select a ROM by click on the proper button nothing happens.

BlackBerry OS 10.3.1 build 1538

Tested versions:
   1.0.0.1
   1.0.0.28
   1.0.0.29

**Comment by fr500** [comment]
Please test on the current code, and reopen if the issue persists

**Comment by leandroal** [comment]
@fr500  How to compile for BlackBerry 10 and/or download the .bar file? Thanks for your support...
