### ISSUE TITLE
Messy BIOS/system directory..

### ISSUE THREAD

**Issue by tbone2k-git** [libretro/RetroArch#14564]
## Description
The directory which contains all the BIOS dumps is a total mess, don't you agree? Some files are located within folders already, which is good, but folder names are very hard to tell apart (or do you know what system is behind a folder "dc" or "ume" or "np2kai"?
How is it, that file names of various BIOS files did not already clash? Is it by coincidence?
(The directory in which the core libraries a stored seems equally messy and is indirectly related, please read on.)

![image](https://user-images.githubusercontent.com/1089383/198851275-8e00acfb-0a7e-490b-881c-0698321ba539.png)

### Expected behavior
I expect **all** BIOS files to reside in a system specific subfolders with speaking names. I don't mind if a folder is named like "psx", any playstation 1 user knows this, but many do not, so despite the issue, that many systems do not have a subfolder collecting all the BIOS files, maybe also name folders like this, so even very new users new to a retro system can understand what's going on.
../system/**psx_playstation1**/scph5500.bin
../system/**psx_playstation1**/scph5501.bin
../system/**psx_playstation1**/scph5502.bin

../system/ **[system-id] _ [friendly-name]**/.. 

OR..

I expect BIOS files to reside at core library location in a subfolder for each core (and I would not mind having duplicates of the (small) BIOS files for different cores emulating the same system) - unfortunately all the core libraries are also mixed together in a single folder.
Instead of having a single core library located here:
../RetroArch-Win64/cores/mednafen_psx_hw_libretro.dll**
Why not have it similar to this:
../RetroArch-Win64/cores/ **psx_playstation1_mednafen_hw** /mednafen_psx_hw_libretro.dll
../RetroArch-Win64/cores/ **psx_playstation1_mednafen_hw/ bios** /scph5500.bin
../RetroArch-Win64/cores/ **psx_playstation1_mednafen_hw/ bios** /scph5501.bin
../RetroArch-Win64/cores/ **psx_playstation1_mednafen_hw/ bios** /scph5502.bin

../RetroArch-Win64/cores/ **[system-id] _ [friendly-name] _ [core-name]** /..

You get the idea. This way cores emulating specific systems would line up and give a clue on what cores a there for each system.
In a perfect world, these core libraries would also be named like they are named in the RetroArch GUI and not totally different. (Think of "mednafen_psx_hw_libretro.dll" which is "Beetle PSX HW" in the GUI for whatever reason? Makes me scream! o)).

### Actual behavior
All BIOS files are mixed together. It's impossible to know what BIOS file belongs to what system and what core makes use of which files.

### Steps to reproduce the bug
Just look into your BIOS folder.. o)

Thank you! o)

**Comment by hizzlekizzle** [comment]
I think it would be good to enable cores to find BIOSes in system/[corename] for optional organization. However, the more directories we put in the mix, the more opportunities users have for getting the path wrong (is it case-sensitive? does it have a hyphen or a space or an underscore? etc).

**Comment by alexstreltsov** [comment]
This issue is related to #14561 issue.

**Comment by alexstreltsov** [comment]
> I think it would be good to enable cores to find BIOSes in system/[corename] for optional organization. However, the more directories we put in the mix, the more opportunities users have for getting the path wrong (is it case-sensitive? does it have a hyphen or a space or an underscore? etc).

@hizzlekizzle, @tbone2k-git, this problem, I think,  can be easily solved by means that are already present for sorting game saves and states. Now RA is able to automatically detect the scanned game and, after checking it with the database of games, determine its title. It also automatically detects a suitable gaming system to run the game, a suitable emulator core, as well as a suitable BIOS image, for example. With all this information, RA sorts the game's saves and states into folders by game system, core, and game title.

**In this case, the sorting feature should work in exactly the same way:** the user should simply put the BIOS images or boot ROMs in the `.../RetroArch/system` directory, and then the first time the corresponding gaming system is started, RA should create a folder for these BIOS images or boot ROMs. For example, in the case of PlayStation: `.../RetroArch/system/Sony — PlayStation`.

**Comment by tbone2k-git** [comment]
@hizzlekizzle 
I think more directories (an actual structure) does help. A core or some part of RA already has the knowledge of what BIOS files are required and optional. As long as there is an easy way to copy and paste these paths from somehwere, spelling and case-sensitivity issues should be easily resolvable by the person placing/naming BIOS files?

If BIOS files would reside at core location like cores/my_core/bios/.. **it would emphasize the "plugin" idea of cores**. I could easily throw in a handful of pre-populated "core-directories" with *.dll, *.cfg and BIOS-files and be good to go. Removing and backing up of cores would also be possible easily from filesystem, no supervising GUI required. 

@alexstreltsov 
Yes, BIOS files in "../system/Sony - Playstation" would be a step forward, but still does not meet my understanding of a core being a plugin, which should have all its required resourced to run in a single place. But yes, better than having the BIOS files all mixed together.. o)

What did you mean with "and then the first time the corresponding gaming system is started, RA should create a folder for these BIOS images or boot ROMs."? And then.. you have the system-specific BIOS folder with no files in them? Should RA move BIOS files there? That does not sound right either to me. I actually think, that each core should have it's own BIOS files, they should not be re-used by several cores (as it makes it basically impossible to know, what core requires what BIOS files and I also cannot inject specific BIOS files (revisions/region-specific etc) to specific cores.

Thank you for replying, appreciated! o)

**Comment by tbone2k-git** [comment]
I found another issue regarding this topic:
[[Feature request] Add option to save by BIOS by core or content folder](https://github.com/libretro/RetroArch/issues/13427#top)
#13427

**Comment by alexstreltsov** [comment]
> What did you mean with "and then the first time the corresponding gaming system is started, RA should create a folder for these BIOS images or boot ROMs."? And then.. you have the system-specific BIOS folder with no files in them? Should RA move BIOS files there?

@tbone2k-git, thank you for your reply. Yes, I lost my thought while writing the explanation. I have corrected that comment:

> **In this case, the sorting feature should work in exactly the same way:** a user should simply put the BIOS images or boot ROMs in the `.../RetroArch/system` directory, and then the first time the corresponding gaming system (its core) is started, RA should create a folder for these BIOS images or boot ROMs, moving them (BIOS images / boot ROMs) to the new folder. For example, in the case of PlayStation: `.../RetroArch/system/Sony — PlayStation` (`.../RetroArch/System/Sony — PlayStation`).

> I actually think, that each core should have it's own BIOS files, they should not be re-used by several cores, as it makes it basically impossible to know, what core requires what BIOS files and I also cannot inject specific BIOS files (revisions/region-specific etc) to specific cores without affecting other cores.

On this I disagree with you. **Why duplicate the same file for different cores?** For example, in the case of PlayStation, there are officially only three BIOS images. Each core of PlayStation, when starting the game, analyses which geographic region the game belongs to and, based on the result of the analysis, selects the correct BIOS image. All BIOS images have different names and different hashes. You don't need to know which BIOS image you need, selected core chooses for you.

**Comment by morovlin** [comment]
I'm glad someone got around to raising the issue. I have a suggestion of my own, though: have RA ignore filenames and directory structure entirely, and match firmwares by their content. This will allow users to organize their folders however they want, and get rid of file name problems, at the expense of RA doing some more record keeping. I'll even take a shot at implementing this, should there be no strong objections.
