### ISSUE TITLE
[Switch] 1.12+ duplicate entries showing up in history

### ISSUE THREAD

**Issue by melterx12** [libretro/RetroArch#14560]
## Description

[Description of the bug]
Since updating to 1.12 on switch any game I start shows two entries in the history playlist. Both have the same name but one seems like an invalid entry and cannot be used to start the game.

### Expected behavior
Only one entry should I appear in the history playlist.

### Actual behavior
Two entries appear.

### Steps to reproduce the bug
1. Start any game on retroarch 1.12 switch. 
2. Check the history playlist.

### Bisect Results
Started happening on 1.12. Did not see this issue on 1.11.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.12.0 840c448

### Environment information

- OS: Switch HOS 15.0 / Atmosphere 1.4.0

**Comment by imagochan** [comment]
you should label this issue,

**Comment by melterx12** [comment]
cant seem to modify the labels

**Comment by Instandhaltung** [comment]
I have the same problem on Switch, plus the one with the save state option disappearing. I think the only option is to revert back for now.

**Comment by melterx12** [comment]
Issue persists on 1.13

**Comment by Nephiel** [comment]
Still able to reproduce this on 1.14.

**Comment by purekimwater** [comment]
I have the same issue on my PS vita. the issue persists even if I downgrade to 1.10.

**Comment by purekimwater** [comment]
I have noticed that this has something to do with the configuration save settings.
This happens on 1.12 and above, and when in Settings - Configuration, the first two settings with "Save" are OFF.
So, if you downgrade to 1.11 and have those two settings turned ON, the problem no longer appears.
However, even if you are on 1.11 and below with the two save switches OFF, it will appear with a wrong core, just not duplicates.

**Comment by DerinQyu** [comment]
Hello, I did a clean install of _2023-01-21_RetroArch_ nightly on my nintendo switch & ps vita and the issue is gone. History playlist is working good, savestates are also working on nintendo switch

**Comment by purekimwater** [comment]
> Hello, I did a clean install of _2023-01-21_RetroArch_ nightly on my nintendo switch & ps vita and the issue is gone. History playlist is working good, savestates are also working on nintendo switch

Sorry, I have tried the build, but the issue is still there with double entries.

**Comment by Nephiel** [comment]
> Hello, I did a clean install of _2023-01-21_RetroArch_ nightly on my nintendo switch & ps vita and the issue is gone. History playlist is working good, savestates are also working on nintendo switch

A clean install of the Jan 29th nightly also fixed both issues for me.

**Comment by DerinQyu** [comment]
This should be closed, things are working fine on latest stable.

**Comment by melterx12** [comment]
Indeed
