### ISSUE TITLE
[Android] RA messing configuration files

### ISSUE THREAD

**Issue by rapiertg** [libretro/RetroArch#1457]
Android 4.4.4 / Ouya/ Nightly RetroArch from 1 march

Tried to configure input on my Ouya and found out, that RA is randomly (or just didn’t find what is the cause) saving or not configuration file.

On first start after configuring only menu toggle button, RA exits, and saves it in /storage/sdcard/Android/data/com.retroarch/files/retroarch.cfg. This button is working after starting RA again.

But when I configure all my bindings and exit on next RA start only D-Pad  and menu toggle seems to be configured.

In addition, after manually saving configuration to file I get some RatroArch-XXX-XXXX.cfg in /storage/sdcard/Android/data/com.retroarch/files/retroarch.cfg. When I load it from RA my bindings are working. But when I switch this file with retroarch.cfg it is messed up on next run and no bindings after all.

Because of this my only way of running RA configured is to load .cfg from custom config file.

**Comment by PetePriority** [comment]
Maybe autoconfiguration of your input device is messing with your settings. Try disabling it.

**Comment by twinaphex** [comment]
The Android Java code is a horrendous piece of junk. I'd really like to get rid of as much code in the Java launcher menu as possible. I don't want a totally separate launcher with totally separate code that I will have to maintain in addition to the C codebase. 

Given all the problems people are having with it, I think perhaps it might be best to just kill it off altogether gradually. It's slow, it doesn't work really all that well anyway. What we need for the real RA menu is gesture support and then it would be a suitable substitute.

**Comment by rapiertg** [comment]
OK, everything I try below is inside RA, not the Android Launcher:
After disabling autoconfiguration, I can't find Ouya Game Controller on Device Index. When I choose 'User 1 Bind All', the only buttons that are accepted are the hats. RA is not reacting when I press anything else. While I'm binding all the buttons to my hats (can't do anything else anyway) device index is randomly changing.

**Comment by rapiertg** [comment]
This 'bug' was unfortunate coincidence of several things:
1. Edited files were saved as root owned (RA couldn't read it) - my bad.
2. Android GUI was messing with RA - this was rather causing misunderstanding nor a bug itself about how to edit cfg manually and why it doesn't save.
3. My OUYA controller has different keymap than one on RA git repo - dont know why, maybe its some faulty batch (eg. touchpad is not working after first restart) - manually editing OUYA keymap worked for me.
