### ISSUE TITLE
[3DS] There is a button combo that quits RetroArch despite not being set to do so.

### ISSUE THREAD

**Issue by DominoBright** [libretro/RetroArch#14571]
The button combo L1+R1+Select+Start quits RetroArch to the 3DS main menu, despite having no button combination set in Settings > Input > Hotkeys > Quit Controller Combo. This combo will continue to be used to quit RA even if it's set to open the RA menu or if a different combo is set to quit RA. This is able to happen with no prior configurations and can be done whether on the RA menu or during gameplay.

I've encountered this issue on the latest Stable and the latest Nightly builds. using a New 2DS XL. I tried this on Switch and PC and it didn't quit RA, meaning it's the 3DS build that's affected.

**Comment by MrHuu** [comment]
https://github.com/libretro/RetroArch/blob/b2e2330ed785034f537d87e327b65ee66f0b9501/input/drivers_joypad/ctr_joypad.c#L193-L198

Added during early development. Can be removed i guess.

**Comment by LibretroAdmin** [comment]
OK, I'll get rid of that.

**Comment by LibretroAdmin** [comment]
Removed -
https://github.com/libretro/RetroArch/commit/aeef3d6220c09caf2923d7bf38163194fd5f8e84

**Comment by DominoBright** [comment]
Unfortunately, that didn't solve the issue: the button combo still causes RA to quit. Tested with the 2002-11-01 nightly created less than an hour from this post.
