### ISSUE TITLE
[Vulkan + HDR] Many shaders oversaturate / burn / darken colors

### ISSUE THREAD

**Issue by aitorciki** [libretro/RetroArch#14582]
## Description

After (and including) Retroarch 1.11, many shaders (e.g. crt-easymode-halation or newpixie.crt) render an oversaturated and dark image when using Vulkan and HDR on Windows 10 + Nvidia. The problem affects all cores.

The issue can not be reproduced on 1.10 or prior, and thus seems related to https://github.com/libretro/RetroArch/commit/a058c78fd04398c0c83c7e5925a178bacf265fff.

RetroArch 1.10.1 (clean install), bsnes + crt-easymode-halation:
![RetroArch bsnes 115 2022-11-03 01_04_40](https://user-images.githubusercontent.com/428243/199624786-ff1ce8b8-b373-4350-ac99-107e145ba9fc.png)

RetroArch 1.11.1 (clean install), bsnes + crt-easymode-halation:
![RetroArch bsnes 115 2022-11-03 01_03_15](https://user-images.githubusercontent.com/428243/199624734-af947b39-0f24-472f-b732-d8bebd3ede31.png)

**Comment by LibretroAdmin** [comment]
What happens on D3D11/D3D12/D3D10?

**Comment by aitorciki** [comment]
D3D11 and D3D12 are both unaffected and render as expected, in line with the first screenshot.

**Comment by LibretroAdmin** [comment]
What about the GLCore video driver? Does it have similar issues as Vulkan, or is that more in line with D3D10/11/12?

**Comment by aitorciki** [comment]
AFAICT GLCore doesn't support HDR, and the issue only shows up with HDR enabled.

**Comment by LibretroAdmin** [comment]
Yes, you're right, sorry for bringing it up.

**Comment by Themaister** [comment]
Is this a shader that relies on tonemap to HDR, or is this a shader that is emitting HDR10 on its own?

**Comment by hizzlekizzle** [comment]
easymode-halation shouldn't be doing any tonemapping of its own and should be outputting the regular R8G8B8A8_UNORM.

**Comment by Themaister** [comment]
![bilde](https://user-images.githubusercontent.com/163683/199830193-f436cbbe-3446-4d18-8a1a-e22a4486700a.png)

I reproduced this. inverse_tonemap = 0.0 and hdr10 = 0.0. So there is no tonemap to PQ happening here on Vulkan for some reason.

**Comment by LibretroAdmin** [comment]
hi there @aitorciki , do you know how to compile / build RetroArch from a PR?

https://github.com/libretro/RetroArch/pull/14587

If you could test this PR and let us know if this resolves your issues, thanks.

If you cannot do this, we could always opt to merge this and then ask you to test a nightly build later on to see if it fixes the issue.

**Comment by LibretroAdmin** [comment]
Guess I'll go ahead and merge this so you can test it in the next nightly, and so it will be ready for the next stable.

**Comment by LibretroAdmin** [comment]
@aitorciki Let us know your results.

**Comment by aitorciki** [comment]
Hi there! Nightly tested, I can't reproduce the color issue anymore testing with many of the previously offending shaders 👍
