### ISSUE TITLE
RetroArch 1.12 - Fedora 36 - Segmentation fault with video_driver gl

### ISSUE THREAD

**Issue by mvrk69** [libretro/RetroArch#14589]
Hi,

When i try to run retroarch with video_driver = "gl" i get Segmentation fault (core dumped).
It runs fine if i change to vulkan.

- RetroArch: 1.12.0
- OS: Fedora 36 (x86_64)
- Package: RetroArch-1.12.0-1.fc36.x86_64
- Laptop Model: HP 15 5100np
- CPU: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
- Graphics Cards: Intel(R) HD Graphics 4600 (HSW GT2) / NVIDIA GeForce GTX 960M (OPTIMUS)
[retroarch_coredump.zip](https://github.com/libretro/RetroArch/files/9938100/retroarch_coredump.zip)

**Comment by gouchi** [comment]
Is it working with ?

`DRI_PRIME=1 retroarch -v ` or `prime-run retroarch -v` ?

Thank you.

**Comment by mvrk69** [comment]
> Is it working with ?
> 
> `DRI_PRIME=1 retroarch -v ` or `prime-run retroarch -v` ?
> 
> Also it will be better to use `glcore` instead of `gl` video driver.
> 
> Thank you.

Actually prime rendering nowadays its executed lke this
__NV_PRIME_RENDER_OFFLOAD=1 retroarch

Regarding glcore, it shows it doesn't exist:

__NV_PRIME_RENDER_OFFLOAD=1 retroarch -v                                                                                                                                                                          master 
[INFO] [Config]: Looking for config in: "/home/maverick/.config/retroarch/retroarch.cfg".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Oct 25 2022
[INFO] Version: 1.12.0
[INFO] =================================================
[ERROR] Couldn't find any video driver named "glcore"
[INFO] Available video drivers are:
[INFO] 	gl
[INFO] 	gl1
[INFO] 	vulkan
[INFO] 	sdl2
[INFO] 	xvideo
[INFO] 	drm
[INFO] 	x11
[INFO] 	caca
[INFO] 	null
[WARN] Going to default to first video driver...
[INFO] [Input]: Found input driver: "x".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[ERROR] Couldn't find any video driver named "glcore"
[INFO] Available video drivers are:
[INFO] 	gl
[INFO] 	gl1
[INFO] 	vulkan
[INFO] 	sdl2
[INFO] 	xvideo
[INFO] 	drm
[INFO] 	x11
[INFO] 	caca
[INFO] 	null
[WARN] Going to default to first video driver...
Segmentation fault (core dumped)

with gl:
__NV_PRIME_RENDER_OFFLOAD=1 retroarch -v                                                                                                                                                                          master 
[INFO] [Config]: Looking for config in: "/home/maverick/.config/retroarch/retroarch.cfg".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Oct 25 2022
[INFO] Version: 1.12.0
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
Segmentation fault (core dumped)

**Comment by gouchi** [comment]
May you try to make a test using ?

```
git clone https://github.com/libretro/RetroArch.git
cd RetroArch
./configure && make -j$(nproc)
__NV_PRIME_RENDER_OFFLOAD=1 ./retroarch
```

You can look in this documentation for the [dependencies for Fedora](https://docs.libretro.com/development/retroarch/compilation/linux-and-bsd/#satisfying-additional-dependencies-under-fedora-33) and adapt it for Fedora 36.

**Comment by mvrk69** [comment]
Building from source works fine with gl and glcore, i guess there is some problem with the version distributed by Fedora 36

**Comment by mvrk69** [comment]
Building from source works fine with gl and glcore.

Thanks

**Comment by mvrk69** [comment]
Building from source (master or release 1.12.0) works fine with gl and glcore, i guess there is some problem with the version distributed by Fedora 36

Thanks
