### ISSUE TITLE
Feature Request: Please support 32bit linux Flatpak

### ISSUE THREAD

**Issue by Littlemac123** [libretro/RetroArch#14597]
Flatpak repo only has 64bit retroarch and currently there is no support to get a updated pre compiled retroarch for Debian 32bit

**Comment by gouchi** [comment]
Hi,

It seems possible using [multiarch](https://docs.flatpak.org/en/latest/multiarch.html) but @RobLoach might shed some light about it.

In the time being, you can try [AppImage](https://buildbot.libretro.com/nightly/linux/x86/).

P.S = There is a [dedicated repository](https://github.com/flathub/org.libretro.RetroArch) for RetroArch Flatpak package.

**Comment by Littlemac123** [comment]
ohhh okay thanks

**Comment by RobLoach** [comment]
Thanks! Sounds like a great suggestion :+1: .... Made the issue in the flatpak repo https://github.com/flathub/org.libretro.RetroArch/issues/237
