### ISSUE TITLE
Retroarch needs a Reboot to use different Refreshrate (Windows)

### ISSUE THREAD

**Issue by CaptainCoward** [libretro/RetroArch#14604]
When changing the Windows Refreshrate of a Display and then starting Retroarch, Retroarch will change the Windows Refreshrate back to where it was before.

Steps to reproduce:
1. Start your computer with a certain Refreshrate set,  lets say 120hz - then start Retroarch. The Refreshrate will stay on 120hz (Borderless Fullscreen) just as expected. 

2. Now close Retroarch, go to Windows Displaysettings and set Refreshrate to something else, lets say 60hz - then start Retroarch again. Retroarch will then switch your windows refreshrate back to 120hz. No matter what - even when deleting retroarch.cfg before.

3. Only fix i found is. Change windows Refreshrate to 60hz. Then Reboot and after that you can start retroarch and it will accept your new refreshrate.
 
This happens on  Retroarch version 1.12. 0 but also on previous versions.

Windows 10 21H1 Pro
AMD RX 6700

**Comment by sonninnos** [comment]
Exclusive fullscreen switches to `video_refresh_rate` on startup, and windowed fullscreen does not.

**Comment by CaptainCoward** [comment]
As mentioned. I have set up windowed fullscreen and it still happens. Though i also have Freesync (which i disabled for Retroarch). Don't know if it is still related.  I don't manually switch Refreshrate that often so this isn't any issue for me. Though i think it's odd that i would basically need to change refreshrate, then reboot, then start retroarch to prevent my refreshrate from being changed when starting retroarch. I just wanted to report it somewhere in case it's a bug. But if you're telling me that isn't RA Fault there isn't much we can do .

**Comment by sonninnos** [comment]
I meant that RA isn't responsible for doing it, as in it is not designed to do so, but it may still be responsible for not preventing it. Somebody who can reproduce it would need to investigate.
