### ISSUE TITLE
(UWP) Broken Builds, once again.

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#14616]
## Description

Either https://github.com/libretro/RetroArch/pull/14592 or https://github.com/libretro/RetroArch/pull/14600 broke UWP builds with this error:

![image](https://user-images.githubusercontent.com/35014183/201486740-1e9e9524-36bb-4733-9dd5-36f92c971116.png)

@sonninnos Since you are the author of both PRs, do you have any idea of what the problem is?

### Expected behavior

RetroArch to build.

### Actual behavior

The exact opposite.

### Bisect Results

Either https://github.com/libretro/RetroArch/pull/14592 or https://github.com/libretro/RetroArch/pull/14600 caused this error.

### Environment information

- OS: Windows 10
- Compiler: Visual Studio 2022

**Comment by sonninnos** [comment]
Yes, simply need to move the function back where it was.
