### ISSUE TITLE
Fullscreen mode not working properly on macOS Ventura (13.0.1)

### ISSUE THREAD

**Issue by Phwanky** [libretro/RetroArch#14614]
## Description

Fullscreen mode not working properly on macOS Ventura (13.0.1)

### Expected behavior

RetroArch should be displayed fullscreen with the usual interface.

### Actual behavior

When starting RetroArch on macOS Ventura in fullscreen mode a small black window with the RetroArch logo is displayed.

### Steps to reproduce the bug

1. Install RetroArch v1.12.0 (Universal Metal)
2. Start RetroArch
3. Change the settings for RetroArch to start in fullscreen
4. Quit and restart RetroArch

### Bisect Results

It started with macOS Ventura. Prior version of macOS was ok.

### Environment information

- OS: macOS Ventura 13.0.1
![RetroArch trying fullscreen](https://user-images.githubusercontent.com/13786665/201422929-b87ac722-270c-422e-bada-785d7144042a.png)

**Comment by LibretroAdmin** [comment]
This is resolved on the latest nightly and the upcoming stable version will not have this issue.

**Comment by LibretroAdmin** [comment]
This should be resolved now in 1.13.0
