### ISSUE TITLE
[Wii 1.0.0.3 nightly] Cannot assign analog stick values as key presses

### ISSUE THREAD

**Issue by Possum412** [libretro/RetroArch#1461]
Attempted to assign save state slots to the left analog stick left/right.  Unable to do so.  Mapping of analog stick to joypad is set to off.  Occurs both inside cores and without a core loaded.

**Comment by fr500** [comment]
which nightly? nightlies started just recently

**Comment by fr500** [comment]
If you have additional information feel free to reopen this

**Comment by Possum412** [comment]
Hi sorry--the most recent one I have downloaded is 3-25.  It still displays this behavior.
