### ISSUE TITLE
[iOS] No PC Engine / Mednafen / Beetle core

### ISSUE THREAD

**Issue by Lodovik** [libretro/RetroArch#1462]
I've successfully downloaded and built the latest RetroArch for iOS. Everything works fine but I noticed that there is no core for running PC Engine / TurboGFX ROMs. Before, I used the Mednafen core but it seems to have been renamed to Beetle and I can't see neither of those in the generated dylibs nor I can't see an error about them in the build summary after the IOS build script has finished.

Will these cores return in a later build for iOS?

Thanks!

**Comment by Lodovik** [comment]
OK, I've found a temporary solution: In the libretro-build.sh script, replace those lines

	libretro_build_core beetle_lynx
	libretro_build_core beetle_gba
	libretro_build_core beetle_ngp
	libretro_build_core beetle_pce_fast
	libretro_build_core beetle_supergrafx
	libretro_build_core beetle_pcfx
	libretro_build_core beetle_vb
	libretro_build_core beetle_wswan

with these:

	libretro_build_core mednafen_pce_fast
	libretro_build_core mednafen_lynx
	libretro_build_core mednafen_gba
	libretro_build_core mednafen_ngp
	libretro_build_core mednafen_pce_fast
	libretro_build_core mednafen_supergrafx
	libretro_build_core mednafen_pcfx
	libretro_build_core mednafen_vb
	libretro_build_core mednafen_wswan

and now they build correctly.

**Comment by fr500** [comment]
They are in the latest folder as they should
http://buildbot.libretro.com/nightly/ios/latest/

Dated folders only contain new and updated cores

**Comment by Lodovik** [comment]
Thank you for adding another workaround to this problem. I'm sure it will be corrected on the Github as it should or else this issue would have not been closed. Keep up the good work.
