### ISSUE TITLE
[RetroPie][RA 1.12] "Configuration override loaded" message appear.

### ISSUE THREAD

**Issue by abj00** [libretro/RetroArch#14620]
## Description

- RPi3b+
- RetroPie 4.8.2 (Debian Buster Lite, 32bit)
- RetroArch 1.12.0

When i am trying to start a game this message appear in the corner `Configuration override loaded`. It's happening with all emulators and games. I don't have overrides, i try also with a clean install of the OS to be sure it is not my setup. 

### Expected behavior
The message to not appear if a override don't set.

### Steps to reproduce the bug

Just start any game.

### Bisect Results

This start to happen with Retroarch v 1.12.0

- RetroArch: [version/commit]

RetroArch 1.12.0 (Git ed68be8)

### Environment information

- OS:RetroPie 4.8.2 (Debian Buster Lite, 32 bit)

[verbose.log.txt](https://github.com/libretro/RetroArch/files/9996685/verbose.log.txt)

**Comment by sonninnos** [comment]
It is caused by the recent change which treats `--appendconfig` like overrides to make it work with overrides. The override notification can be hidden.

**Comment by abj00** [comment]
Thanks for the reply! 

So, it looks that it is not a issue then.

**Comment by sonninnos** [comment]
Perhaps it still could be refined so that it acts more like before.

**Comment by cmitu** [comment]
@sonninnos it would certainly be a welcome change.

RetroPie uses a runtime generated `.cfg` with `--appendconfig` when starting `retroarch` and the the new info messages about the configuration override are a bit puzzling for users which have not saved such an override.
