### ISSUE TITLE
[PS2] RetroArch doesn't start with an usb mass storage device connected formated with exFat

### ISSUE THREAD

**Issue by jhonathanc** [libretro/RetroArch#14635]
## Description

RetroArch doesn't start if an usb mass storage device formated with exFat is connected.

### Expected behavior

RetroArch should, at least, start.

### Actual behavior

RetroArch freezes on startup.

### Steps to reproduce the bug

1. Plug an exFat formated usb mass storage on PS2.
2. Start retroarch using wLaunchELF, or using a burned CD.
3. Retroach will freeze on startup.

### Bisect Results

I tried with RA 1.12, 1.11.1 and nightly builds. None worked.

### Enviromental Information

OS: PS2 platform
Devices: I used a Sandisk SDCZ60-032G 32GB thumb drive and also, a rocketec usb card reader with a micro sd card formated to exFat. Both works with wLaunchElf and OPL.

**Comment by INDRAPhilip** [comment]
For now, they are not yet using the new Drive fats nor the new retroach sdk enhancements, so it has no support for exfat.

**Comment by INDRAPhilip** [comment]
For now, they are not yet using the new Drive fats nor the new ps2 sdk enhancements for retroach, so it has no support for exfat.

**Comment by jhonathanc** [comment]
I tried to change the bdmfs_vfat to bdmfs_fatfs on RA code, but I was not able to compile it :(. I'm almost sure it's a Makefile problem (because I'm not very skilled on it). I was trying to use only the CI to build it because  I didn't want to install all the ps2sdk but I think I'll.

**Comment by jhonathanc** [comment]
Finally, I was able to compile RA (raboot.elf) with the bdmfs_fatfs driver and it works, but I don't know how to compile the cores, because every core I build don't work. (I think it's because it's not using the core defs).

**Comment by jhonathanc** [comment]
@INDRAPhilip the changes to RA were easy. Maybe @fjtrujy could help with the cores. And the CI script (I checked it twice, but I didn't find why it doesn't work with my changes).

**Comment by fjtrujy** [comment]
I need to update implementation and use the ps2_drivers library that I have created.
It is on my todo list

**Comment by fjtrujy** [comment]
Once this PR is merged you will have `exFat` support
https://github.com/libretro/RetroArch/pull/14724
