### ISSUE TITLE
gfx_ctx_go2_drm not impement get_video_size

### ISSUE THREAD

**Issue by sunxuold** [libretro/RetroArch#14656]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
i found in drm_go2_ctx.c not implemented get_video_size so may cause  codedump in some case

[Description of the bug]
need added this function (gfx_ctx_go2_drm_get_video_size)

static void gfx_ctx_go2_drm_get_video_size(void *data,
      unsigned *width, unsigned *height)
{
   gfx_ctx_go2_drm_data_t *drm = (gfx_ctx_go2_drm_data_t*)data;

   if (!drm)
      return;

   *width  = drm->fb_width;
   *height = drm->fb_height;
}

const gfx_ctx_driver_t gfx_ctx_go2_drm = {
   gfx_ctx_go2_drm_init,
   gfx_ctx_go2_drm_destroy,
   gfx_ctx_go2_drm_get_api,
   gfx_ctx_go2_drm_bind_api,
   gfx_ctx_go2_drm_swap_interval,
   gfx_ctx_go2_drm_set_video_mode,
   gfx_ctx_go2_drm_get_video_size, /* get_video_size */

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by LibretroAdmin** [comment]
OK, not sure why you couldn't submit a PR, but I implemented what you suggested here -
https://github.com/libretro/RetroArch/commit/623b9252561a2f97be2d8123f3f3c5ba6d172b86

Hope that works out for you.

**Comment by sunxuold** [comment]
Fine i will use PR next time.

**Comment by LibretroAdmin** [comment]
OK, in any case, does this fix the issue?

**Comment by sunxuold** [comment]
Yes  it solved

**Comment by LibretroAdmin** [comment]
Thank you, I will close this issue then. Thanks for letting us know about this issue.
