### ISSUE TITLE
Manual RetroArch 1.13.0 3DS build crashes on launch 

### ISSUE THREAD

**Issue by SirFluffDev** [libretro/RetroArch#14669]
## Description
When building RetroArch myself, it compiles successfully. However, when installing and running the CIA file on 3DS, it crashes immediately.

### Expected behavior
RetroArch build functions as normal.

### Actual behavior
RetroArch build immediately crashes.

### Steps to reproduce the bug
1. Download RetroArch 1.13.0 source code
2. Compile any core to obtain the libretro_ctr.a file
3. Compile Makefile.ctr.salamander with the option USE_CTRULIB_2=1
4. Compile Makefile.ctr with the option USE_CTRULIB_2=1
5. Install the retroarch_3ds.cia file to your 3ds
6. Launch the app

### Version/Commit
- RetroArch: 1.13.0 (Source)

### Environment information
- OS: Pop!_OS
- Compiler: [In case you are running local builds]

I beleive the libretro_ctr.a file may be the culprit. I've obtained it by compiling the pcsx_rearmed core. Let me know if I've done something wrong.

**Comment by RobLoach** [comment]
Could you provide the logs?

**Comment by SirFluffDev** [comment]
Sorry for leaving the issue open - I found out that I had to compile it using the core compilation bash files. Those gave me the files just fine.
