### ISSUE TITLE
(Mac) Metal shader support seems poor (seems to be Clang/LLVM's fault)

### ISSUE THREAD

**Issue by ballo** [libretro/RetroArch#14670]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

I searched the issues for "mac shader" and didn't find anything apropos

## Description

A great deal of the shader presets fail to load on my M1 mac using the Metal release (tried stable and nightly)

### Expected behavior

All shaders load

### Actual behavior

Few of the Bezel shaders load

### Steps to reproduce the bug

If you try to load a shader like
`/Users/ball/Library/Application Support/RetroArch/shaders/shaders_slang/bezel/Mega_Bezel/Presets/Base_CRT_Presets/MBZ__1__ADV__EASYMODE.slangp`

it will fail. The errors are numerous, but a common one is:

```
[ERROR] [Metal]: unable to compile fragment shader: Compilation failed:

program_source:1607:277: fatal error: bracket nesting level exceeded maximum of 256
program_source:1607:277: note: use -fbracket-depth=N to increase maximum nesting level
```

There are other errors, a few documented here
https://forums.libretro.com/t/mega-bezel-on-m1-macs/39641

### Bisect Results

It's repeatable; just start loading shaders and most won't work.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.13.0

### Environment information

- OS: Mohave
-

**Comment by hizzlekizzle** [comment]
How about non-Mega Bezel shaders?

**Comment by ballo** [comment]
Some do, some don't. 
crt-pi.slangp fails for example

**Comment by LibretroAdmin** [comment]
Read the Libretro forums post, apparently this is not our fault.

> [hunterk](https://forums.libretro.com/u/hunterk)
[7h](https://forums.libretro.com/t/mega-bezel-on-m1-macs/39641/25?u=twinaphex)
It seems to be a clang thing, and it’s a fairly recent change that’s bothering more people than us, it seems: [https://github.com/llvm/llvm-project/issues/48973 3](https://github.com/llvm/llvm-project/issues/48973)

**Comment by hizzlekizzle** [comment]
> crt-pi.slangp fails for example

Ah! That's a good test case, since it's a very straightforward, single-pass shader. It doesn't have any loops in it, but it does have a fair bit of branching and a lot of pre-processor directives. Is it failing with the same error? That is, about too many nested brackets? If so, glslang may still be getting overzealous with the brackets, but it still seems to be coming to down to that overly-cautious default clang setting (one of the commenters on the llvm issue suggests it may be set so low to remove a fuzzing target, which, if so, is pretty lame IMO).

**Comment by ballo** [comment]
Looks different
```
[INFO] [slang]: Compiling shader: "/Users/ball/Library/Application Support/RetroArch/shaders/shaders_slang/crt/shaders/crt-pi.slang".
[ERROR] [Metal]: unable to compile fragment shader: Compilation failed:

program_source:90:12: error: redefinition of 'param' with a different type: 'float2' (vector of 2 'float' values) vs 'const constant Push &'
    float2 param = texcoord;
           ^
program_source:84:103: note: previous definition is here
fragment main0_out main0(main0_in in [[stage_in]], constant UBO& global [[buffer(0)]], constant Push& param [[buffer(1)]], texture2d<float> Source [[texture(2)]], sampler SourceSmplr [[sampler(2)]])
                                                                                                      ^
program_source:91:19: error: no matching function for call to 'Distort'
    float2 _140 = Distort(param, CURVATURE_DISTORTION, barrelScale);
                  ^~~~~~~
program_source:39:8: note: candidate function not viable: no known conversion from 'const constant Push' to 'float2 &' for 1st argument
float2 Distort(thread float2& coord, thread float2& CURVATURE_DISTORTION, thread float2& barrelScale)
       ^

```

**Comment by ballo** [comment]
Yeah, I'm not sure why the clang peeps are doing this. It's basically burying problems instead of solving them.

**Comment by hizzlekizzle** [comment]
@ballo 
can you try this slightly modified version to see if it treats you any better? https://gist.github.com/hizzlekizzle/2bc42db8aa1016a3f6dc4a78e9be9613

**Comment by ballo** [comment]
Failed:
`[WARN] [Shaders]: Root preset is not a valid shader chain because it has no shaders entry: "/Users/ball/Library/Application Support/RetroArch/shaders/shaders_slang/crt/crt-pi2.slangp".
`

**Comment by ballo** [comment]
I don't see the option

**Comment by hizzlekizzle** [comment]
on the shader menu:
![image](https://user-images.githubusercontent.com/2805586/205507841-6f9731c1-17e1-49a9-bbe1-406b58119ec0.png)

**Comment by ballo** [comment]
If I make that selection, your shader disappears from the menu and cannot be selected

**Comment by ballo** [comment]
<img width="1009" alt="Screen Shot 2022-12-13 at 2 32 29 PM" src="https://user-images.githubusercontent.com/631311/207448322-4053a05a-425e-4e5d-9392-7aa4d6c14484.png">
/shaders_slang/crt/ after selecting "Shader #0"

**Comment by warmenhoven** [comment]
It works with the Vulkan/MoltenVK graphics driver. I don't think it's as simple as a clang bug. At the very least if there is a clang bug there might be a workaround.

**Comment by warmenhoven** [comment]
I believe #14850 fixes this.

**Comment by ballo** [comment]
> I believe #14850 fixes this.

Sweet! Going to try this out soon. Thank you!
