### ISSUE TITLE
Add PSX emulation to RetroArch for PSP

### ISSUE THREAD

**Issue by Farooq87** [libretro/RetroArch#14674]
Some PSX games unfortunately don't run correctly or don't run at all on PSP resources using any POPs loader. It would be very nice to have alternative like owners of Vita have with PSX support in RetroArch. 
For example, X-Files: the Game is unplayable both on PSP and Vita due to issues with video, but RetroArch on Vita made it possible to play this game. I assume some other titles with issues such as Egypt 1, Psychic Detective etc could be finally playable for PSP owners in RetroArch just like in Vita. 
Could you please add PS1 emulation in new version of RetroArch for PSP?

**Comment by hizzlekizzle** [comment]
Unfortunately, the PSP isn't powerful enough for any of the available PS1 cores. PCSX-ReARMed is very fast, but it requires an ARM processor to work its magic. The Vita has such a processor while the PSP does not.

**Comment by LibretroAdmin** [comment]
Not a RetroArch issue. Also unlikely to happen - no fast MIPS dynarec for pcsx rearmed, and itd be probably impossible to match or beat popstation anyway in terms of performance.
