### ISSUE TITLE
this will  cause an heap-buffer-overflow

### ISSUE THREAD

**Issue by MistyDreams** [libretro/RetroArch#14698]
https://github.com/libretro/RetroArch/blob/91b77cf14abd5456210e5bdf267631c6b659ed8e/core_info.c#L1917

length calloc needs a +1 asan picked this up.

**Comment by LibretroAdmin** [comment]
I think your link is wrong. Can you correct it? It's impossible to tell which line you are referring to right now.

**Comment by LibretroAdmin** [comment]
Just send a PR, you are still not linking to the actual calloc line that is supposed to be changed/fixed.

**Comment by LibretroAdmin** [comment]
I think this can be closed now.

https://github.com/libretro/RetroArch/commit/440c7a5ddfa66c3bbd48e4c32601867bd995f8f4

Reopen if it still happens, and if it does, just send a PR already if you have the fix.
