### ISSUE TITLE
Button hotkey interferes with keyboard

### ISSUE THREAD

**Issue by RobG66** [libretro/RetroArch#14690]
## Description
 Button hotkeys apply to keyboard commands after core and game are loaded.  Shouldn't there be a separate keyboard hotkey for keyboard commands?  There seems to be a config entry for that:  

input_enable_hotkey = "nul"
as opposed to
input_enable_hotkey_btn = "nul"

### Expected behavior
 Button hotkey for buttons.  Keyboard hotkey for key commands.  If I have a button hotkey set, I should still be able to press escape on keyboard to quit retroarch.

### Actual behavior
 Keyboard commands do not work unless button hotkey is pressed while game and core are loaded.  

### Steps to reproduce the bug
Set button hotkey
Set key quit retroarch = escape
Load a core and game
Cannot quit retroarch by pressing escape on keyboard

### Version/Commit
- RetroArch: 1.13.0

### Environment information
- OS: Win11

**Comment by RobG66** [comment]
I guess retroarch expects a key hotkey.  So setting one manually in the config file to something like 'shift' is a bit of a work around.

**Comment by sonninnos** [comment]
I think I have this soon sorted so that keyboard won't require pressing the hotkey if only joypad has the hotkey bind.

**Comment by sonninnos** [comment]
Except turning out to be a bit of a nightmare to get it perfect, because `input_keyboard_event` can get fired before `input_keys_pressed` decides what needs to be blocked and allowed..
