### ISSUE TITLE
[Feature Request] [Steam] Add option to disable .opt syncing through Steam Cloud

### ISSUE THREAD

**Issue by ds22x** [libretro/RetroArch#14716]
## Description

Having an option to disable syncing .opt files would be nice for situations where on, for example on a Steam Deck, I'd want to use something like 1x or 2x resolution scale for Mupen64Plus-Next or Beetle PSX, but want to bump it up to 4x on my Windows PC.
Right now, when syncing is enabled, there's no possible way to have different .opt files between setups.
Having an option to disable tracking .opt files would therefore be a nice way to allow for different settings between setups, while retaining save file and state syncing.

**Comment by Chrismettal** [comment]
How can we help getting this feature added?

For me, syncing the core settings results in shaders that work on a 4k TV being horribly off on the Steam Deck. I like the option of having settings synced if multiple similar PCs are used, but when swapping between vastly different systems (Where Steam Cloud usually shines) it does not help a lot.

**Comment by ds22x** [comment]
Changing the configuration files path inside the directory submenu does exactly what I requested.
