### ISSUE TITLE
Haptic Feedback/Vibration not working on iOS

### ISSUE THREAD

**Issue by BigBadThanos** [libretro/RetroArch#14734]
There is an option "Vibration Strength" in "Haptic Feedback/Vibration" but it's not working on any core. 

I expected haptic feedback from my phone while playing games on cores which both support it.

It's not giving any haptic feedback while it's giving it on Android with the same options.

### Steps to reproduce the bug

1. Set Device Type in Port 1 Controls to Dualshock.
2. Set "Vibration Strength" in "Haptic Feedback/Vibration" to 100%.
3. Play game with supported rumble.

It never worked.

- RetroArch: [version/commit]
Every version, 1.14 included

iOS 15-16

**Comment by LibretroAdmin** [comment]
It is only implemented for Android thus far. It'd be nice if someone could implement it for iOS as well
