### ISSUE TITLE
The Retroarch I downloaded has a technical problem I guess.Sometimes when I completely power off my device Retroarch restores default settings by itself in version 1.13.0 Please could you solve this problem for me please 

### ISSUE THREAD

**Issue by Vini182837** [libretro/RetroArch#14739]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
i'm afraid this isn't an actionable report, and it falls more into "tech support" than "bug report", which is what the github issue tracker is more suited for.

I think you'll have better luck at one of the tech support channels, including our discord, subreddit or forum.
