### ISSUE TITLE
[iOS] AltStore sideloading directories

### ISSUE THREAD

**Issue by DarkPaladin125** [libretro/RetroArch#14736]
I don't know if this is the right place for me to ask, but here goes nothing.

I've sideloaded BizHawk on iOS using AltStore, but I've noticed it can only access its application folder on **On My Phone**.
Is it possible to access **iCloud Drive**? Yes, I'm aiming for easy syncing.
Or any other simple sync solutions?

Thanks a lot.

**Comment by RobLoach** [comment]
May be better to ask in the Discord. There's likely a way to use iCloud, but this is likely not the place to ask. Thanks!
