### ISSUE TITLE
WinKawaks core request or WinkKawaks compatible romset core request

### ISSUE THREAD

**Issue by anonyme-x22** [libretro/RetroArch#14745]
I'm using winkawaks rom set for neogeo game on windows.
Seams that i currently have no alternative to load my roms in linux as no winkawaks core available and don't know if there is one compatible.

Thanks in advance,
Have a good day,
Rgds,

**Comment by hizzlekizzle** [comment]
WinKawaks is closed-source and Windows-only, so no libretro core exists or can exist (unless the WinKawaks developers decided to make it themselves, which isn't likely).

**Comment by anonyme-x22** [comment]
Is there a libretro core which handle winkawaks rom, my roms are burned into cdrom, as winkawaks where the moste stable one.

Thanks in advance,
Have a good day,
Rgds,

**Comment by anonyme-x22** [comment]
Hi seems that final burn neo is compatible with winkawaks roms.
