### ISSUE TITLE
PPSSPP Core & Vulkan Render !

### ISSUE THREAD

**Issue by metagondria** [libretro/RetroArch#14769]
Hello,

From what i have found about this subject, it seems to be an old pain in the development of ppsspp.  Poeple reporting this still is an issue !!

And , i just want to report this issue to confirm this.

So, running games in fullscreen using ppsspp core in RA with Vulkan render setting is an no show !!
As soon i hit alt+enter (fullscreen) , RA can't handle it anymore and it crashes to desktop !!!

Window-Fullscreen however works ( no crash), also OpenGL (Not GLcore !?) seems to work stable in exclusive fullscreen...
Using up-to-date RetroArch 1.14 with all cores updated aswell..

My system is lightning fast to emulate psp.
It only utilizes the cpu between 10-20% (at most) , and gpu max 10% 👍  

my system specs:
Mobo: Asus Sabretooth FX-990 R2.0
Cpu: FX-8350@4,7Ghz
Gpu: RX-6600 
Ram: pc-15000 16GB
SSD: Samsung Evo 850

So that can't be it... me thinks.

As for an comparising note, i have tried out PPSSPP (rev 1.14.1) stand alone variant, and fullscreen works just great using Vulkan settings ..  In short, AUDIO + VIDEO works perfect on EVERY GAME ..

If you need any debug logs , let me know...

cheers,

**Comment by sonninnos** [comment]
Hmm, vulkan non-windowed fullscreen works fine here with GTX 970 when it starts to fullscreen, but if I toggle fullscreen afterwards it will crash at once..

**Comment by metagondria** [comment]
> Hmm, vulkan non-windowed fullscreen works fine here with GTX 970 when it starts to fullscreen, but if I toggle fullscreen afterwards it will crash at once..
> 
> Other cores using HW vulkan like Mupen64, and software cores do not crash when toggling fullscreen.
> 
> Anyway looks like a core issue and not a frontend issue.


Yep, EXACTLY ↑ ...!   When RA starts in fullscreen, ppsspp play's nice, but hit Alt+enter (toggle) boom .. shutdow 👎  using vulkan!

Not only that, but when trying to load game save in a game i get Black screen with 2 horizontal white lines on screen... -_- !!

Check this out !!
[url=https://postimg.cc/kR2jKGqy][img]https://i.postimg.cc/mkw0x1nK/black-screen-load-save.png[/img][/url]

Must say, psp and pscx2 cores leave much to be desired compared to the stand alones unfortunately !!
Pity, cuz RA implementation of shaders and able to stack em in any order looks very awesome and polished on older games  ...

cheers,

**Comment by sonninnos** [comment]
Those save screens work fine when the core system files are in place.

![retroarch_2022_12_27_02_44_13_684](https://user-images.githubusercontent.com/45124675/209591846-a2c99f9e-7108-4b0f-a43f-dbbff31e0eb0.png)

![retroarch_2022_12_27_02_44_17_538](https://user-images.githubusercontent.com/45124675/209591875-5c74c9e5-c09a-4298-9565-2c5b41e06dd3.png)

https://docs.libretro.com/library/ppsspp/#bios

**Comment by metagondria** [comment]
Thanks for that usefull info onnions..

Iam baffled..  So psp core doesn't need any additional steps to play an new game... but to just save & load and god what not ... it needs additional system files like the bios ?

I mean, ppsspp stand alone doesn't need any additional system/bios for the game to function right !? 
How does that even translate?

I don't get that! 
Whats up with that ?


Cheers,

**Comment by metagondria** [comment]
> The issue tracker is not intended for tech support. These sorts of questions are better suited to the forum, subreddit, discord, etc.
> 

So, the issue iam having and appearantly others too with the vulkan renderer is an "Tech Faq" and not an Bug suitable for reporting in the development section ?


>  but they are included with the program there rather than being a separate download 

My point ↑ iam trying to make exactly.  

It doesn't make sense one need to grab / search / config and go through additional steps to get the core / base function of an Emu/Console to work..  

It makes sense to me that an emu is not meant to use the following by default → cheats/scripts/macro's and therefor its up to the end-user to add the requested files/settings..


 


> The issue tracker is not intended for tech support. These sorts of questions are better suited to the forum, subreddit, discord, etc.
 

> However, you can download them in RetroArch by going to main menu > online updater > core system file downloader > PPSSPP.zip and it will automatically put them in the right spot.


i have already thought of that and used Online Updater... But it doesn't always work that easy, the files aren't always there to choose from !!!   For some reason, RA didn't updated → ADDED all of shaders in the past too!!!  I had to grab that specific shader from an user at an forum who shared it with me !?!   

Cheers,

**Comment by gouchi** [comment]
You should close this issue as there is already an [issue opened](https://github.com/hrydgard/ppsspp/issues/15381) about the fullscreen problem with Vulkan.

Thank you.

**Comment by metagondria** [comment]
> You should close this issue as there is already an [issue opened](https://github.com/hrydgard/ppsspp/issues/15381) about the fullscreen problem with Vulkan.
> 
> Thank you.

I know, hence me posting again to confirm it...  to let yall know, it is STILL happening !

The 1 milion dolar answer i like to know is, where O where can i find older builds of mednafen_psx_hw.dll cores ?
Seems to be an BIG secret online !!!   Only latest version is available to grab!?  

cheers,

**Comment by metagondria** [comment]
Oh..before i forget...

Has this glitch ↓ been reported yet ...? 
<a href='https://postimg.cc/K1gz59Nd' target='_blank'><img src='https://i.postimg.cc/K1gz59Nd/Green-aura.png' border='0' alt='Green-aura'/></a>

**Comment by sonninnos** [comment]
This should be now sorted with https://github.com/hrydgard/ppsspp/pull/19203
