### ISSUE TITLE
[Feature Request] Delete Save State Thumbnails automatically.

### ISSUE THREAD

**Issue by maliquem** [libretro/RetroArch#14763]
With the option to put a limit in the Auto-Increment Save States, we need one option to delete the correspond Thumbnail too.
Playing in 4K, they got pretty big fast.

It will be nice, if the Thumbnails has an option to be smaller too.

**Comment by upcboy** [comment]
I would also like to see an option to remove save state screen shots that no longer have a valid save state associated with it.
