### ISSUE TITLE
Minor RetroAchievements Pop-up Display Issue

### ISSUE THREAD

**Issue by TheRhysWyrill** [libretro/RetroArch#14786]
## Description

Might be exclusive to UWP but with this #14777 PR when the Achievement Widget is set to anything but Top/Bottom Left then the pop-up text will bug out slightly and overlap with the game/cheevo badge when displaying the initial achievement pop-up on game load and achievement pop-ups.

### Expected behavior

For the pop up to display properly and the text to not overlap with the badges.

### Actual behavior

https://user-images.githubusercontent.com/27123572/210099912-acc8c10c-cfaa-49ee-a2d4-a280f96cd6b6.mp4

### Steps to reproduce the bug

1. Enable Achievements.
2. Change alignment to either top/bottom center/right.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.14.0/[d24cdbf](https://github.com/libretro/RetroArch/commit/d24cdbfb15c14dfb3430bf19ba79530aea997acc)]

### Environment information

- OS: Xbox Series X

**Comment by retroNUC** [comment]
Thanks, I can take a look. Looks like the scissoring (hiding things outside a set bound) isn't working properly during those _start and _dismiss functions.

Not seeing on Windows, so could be either a UWP issue or a custom font issue.

**Comment by TheRhysWyrill** [comment]
> 
Thanks, I think it's unfortunately more likely to be a UWP issue as I experienced the same behavior when testing the UWP version on PC with a default font, no rush for a fix, just thought it'd be wise to bring it to your attention.

**Comment by retroNUC** [comment]
Seems to be an underlying problem with the scissoring implementations on GL/Vulkan (working) vs D3D (broken). Can be reproduced on any platform by settings video driver to D3D10/11/12.

**Comment by retroNUC** [comment]
Old fixed issue that seems related: https://github.com/libretro/RetroArch/issues/8570

**Comment by TheRhysWyrill** [comment]
> Seems to be an underlying problem with the scissoring implementations on GL/Vulkan (working) vs D3D (broken).
> 
> Can be reproduced on any platform by settings video driver to D3D10/11/12.

That is unfortunate, any idea why it seems to work just fine when the alignment is set to either top/bottom left?

**Comment by retroNUC** [comment]
> That is unfortunate, any idea why it seems to work just fine when the alignment is set to either top/bottom left?

Nah, it's something I'll have to dig into and see if I can fix properly. 

Dev Notes: Looks like the GL implementation is correct (whenever we need to during the frame, we set a rect, enable test, draw, disable test, clear rect), but there's not really a D3D equivalent that works like that - Certainly not the `RSSetScissorRects` call it's currently using, which expects an array of rectangles to work with multiple viewports.

**Comment by TheRhysWyrill** [comment]
PR #14793 fixes this issue, thanks @retroNUC
