### ISSUE TITLE
Pressing Multiple Buttons is only Registered as 1 Button on Retroarch Android Using Dualshock 4

### ISSUE THREAD

**Issue by yudhiyou** [libretro/RetroArch#14791]
Why is on dualshock 4 on retroarch android it can't press multiple buttons on same time? It is only registered as 1 button.
But it is working on ipega gamepad.

**Comment by hizzlekizzle** [comment]
there is an android-specific input setting that blocks on input for a short time to make pressing multiple buttons on the same frame easier.

**Comment by yudhiyou** [comment]
Which setting is that? Why if I am using ipega gamepad no need such of that setting?

**Comment by yudhiyou** [comment]
Ok, I have found that setting already on latency setting and it is working.
Thank you very much for the help.
