### ISSUE TITLE
[iOS] RetroAchievement default display broken

### ISSUE THREAD

**Issue by Coloradohusky** [libretro/RetroArch#14801]
### Description
In 1.13.0, the RetroAchievement notifications display "normally" (aligned to the top left of the screen), as shown below.
<img src="https://user-images.githubusercontent.com/45430066/210622163-dc521b44-2d89-4363-86be-e8b214593576.JPG" width="200" />
However, after updating to 1.14.0, they are offset incorrectly from the edge of the screen.
<img src="https://user-images.githubusercontent.com/45430066/210621533-5fc4018b-db20-4b03-a5d6-6a14c56d8873.jpg" width="200" /> <img src="https://user-images.githubusercontent.com/45430066/210621529-95031029-fc9a-4cf1-8f18-bfd6411db884.jpg" width="200" />
The appearance is the same when Aligned Padding is off, and both Manual Paddings are 0.00. I tried adjusting the offset manually, to see if I could negative offset it, but the current dot adjuster thingy doesn't appear to allow for negative offset, or for me to type in an offset - it only works by sliding from the dot left to right.
Related to https://github.com/libretro/RetroArch/pull/14777
### Version/Commit
You can find this information under Information/System Information

- RetroArch: Jan 4 2023, 1.14.0

### Environment information

- OS: iOS 16.2, on an iPhone 13
- Compiler: Clang/LLVM (14.0.0 (clang-1400.0.29.102)) 64-bit

**Comment by LibretroAdmin** [comment]
@retroNUC Perhaps you might be able to hazard a guess as to what might be going on here.

**Comment by retroNUC** [comment]
I suppose 'correctly' is a loose term, I'll remember to consider width clamping for narrow portrait-style screens when I get around to the scaling options.

Correct behaviour should be that 'Aligned Padding' uses the same offset as the standard message queue (correct, as seen in second screenshot), but with that disabled and padding values set to 0.0, we should be seeing the old behaviour where it's directly against the screen edge. Will check the logic.

**Comment by Coloradohusky** [comment]
Yeah, correctly is a loose term, updated description to be more accurate - I suppose that the offset would be fine if we could scale down the achievement box to fit within the screen borders, instead of getting cut off at the sides like it does now, but with the current behavior it definitely looks odd, imo

**Comment by retroNUC** [comment]
I'll get it back to existing behaviour first so that Manual Padding works, then we'll deal with proper scaling in a future change/update 👍

**Comment by retroNUC** [comment]
Spent a while trying to reproduce or figure out what could be going wrong, but no luck. Tried different video/menu drivers on Windows and Android, and at narrow resolutions like this, and don't have an IOS device to check.

@Coloradohusky - Do 'Auto Padding' off and different values within Manual Padding do absolutely nothing to the position? As in, does it always stay slightly offset from the screen edges, same distance from edges as the bottom message popups?

**Comment by Coloradohusky** [comment]
Retested, and Manual Padding works as it should - 0.00 and 0.00 have it aligned as it was in 1.13.0, and changing those values works as intended. Thanks for the help, and thanks for your work on adding this feature, and the others that are planned!
