### ISSUE TITLE
No issue tracker for libretro / Stella; the pre7.0 core does not allow in-game input in aftermarket game Elevator Agent

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/RetroArch#14802]
You can start the game, but as soon as the game begins you can't move or fire. The game works correctly in the 6.7 derived core from the stable 1.10.3 core pack.  Of note, when the game starts up in the pre7.0 core, it shows "gamepad" as the input type, but in 6.7 it shows "joystick", so it is like the game's being fed the wrong input somehow.  Talked to Stella devs as I accidentally made a core report there due to the link leading to their project, and they say it's fine in 7.0 standalone.

**Comment by LibretroAdmin** [comment]
> You can start the game, but as soon as the game begins you can't move or fire. The game works correctly in the 6.7 derived core from the stable 1.10.3 core pack. Of note, when the game starts up in the pre7.0 core, it shows "gamepad" as the input type, but in 6.7 it shows "joystick", so it is like the game's being fed the wrong input somehow. Talked to Stella devs as I accidentally made a core report there due to the link leading to their project, and they say it's fine in 7.0 standalone.

Well, I don't know why they want you to report it to us since the libretro core is literally part of their upstream project. The only libretro Stella core we maintain by ourselves is the Stella 2014 core.

**Comment by n1ghttrap** [comment]
> > You can start the game, but as soon as the game begins you can't move or fire. The game works correctly in the 6.7 derived core from the stable 1.10.3 core pack. Of note, when the game starts up in the pre7.0 core, it shows "gamepad" as the input type, but in 6.7 it shows "joystick", so it is like the game's being fed the wrong input somehow. Talked to Stella devs as I accidentally made a core report there due to the link leading to their project, and they say it's fine in 7.0 standalone.
> 
> Well, I don't know why they want you to report it to us since the libretro core is literally part of their upstream project. The only libretro Stella core we maintain by ourselves is the Stella 2014 core. They'd be best situated to know what is wrong.

Fun.  Well, they said they'll get in touch with you per https://github.com/stella-emu/stella/issues/949, I'll use the old core and deal for now.  Thank you.

**Comment by hizzlekizzle** [comment]
I assume they just mean that they don't use the libretro core and therefore don't know what would cause a problem that's not present in the standalone emulator, which I/we get.

As with any issue, the first step is going to be finding out if it ever worked, and, if so, when it broke. That will usually get us on track to finding a solution.

**Comment by LibretroAdmin** [comment]
We don't know anything about their emulator core internals though. They would know more about it than we do. If it works in the Stella 2014 core, then there must be something on the core side that is being implemented wrongly, and it'd be something they'd know more about than us.

**Comment by n1ghttrap** [comment]
It does work in the 6.7 core from 1.10.3 stable.  Game detects a joystick.  Game detects a "gamepad" in the 7.0 core.  There is no gamepad option in the input types (joystick, analog, etc but no gamepad) so somehow 7.0 is telling the game or the game is interpreting the wrong input type from the core.

**Comment by n1ghttrap** [comment]
> We don't know anything about their emulator core internals though. They would know more about it than we do. If it works in the Stella 2014 core, then there must be something on the core side that is being implemented wrongly, and it'd be something they'd know more about than us.

The game will not boot in 2014, it requires 6.7 or later as I presume it emulates something pretty low level, advanced, or a new chip.

**Comment by LibretroAdmin** [comment]
> It does work in the 6.7 core from 1.10.3 stable. Game detects a joystick. Game detects a "gamepad" in the 7.0 core. There is no gamepad option in the input types (joystick, analog, etc but no gamepad) so somehow 7.0 is telling the game or the game is interpreting the wrong input type from the core.

What happens if you use that older core in 1.14.0 stable or the latest nightly? Does it still work as expected? If so, it's not a frontend/RetroArch issue, but a core issue.

**Comment by n1ghttrap** [comment]
I used the older core in 1.14 and it worked, so yes it's something wrong with the newer core.

**Comment by LibretroAdmin** [comment]
@n1ghttrap Are there any more recent versions inbetween 6.7 and 7.0 that you can test? Core-wise that is? Someone would have to start bisecting to see when this issue happened and then report it to Stella upstream devs.

**Comment by n1ghttrap** [comment]
Ah, anything beyond the 1.10.3 core pack uses 7 and that seems to be where the problem lies. 1.11.0 and beyond have the problem core.  That's the best I can do for now.

**Comment by hizzlekizzle** [comment]
Ok, 1.10.3 was released April 15 2022, so I'll compile from git hash 11ff4aca4f794a13a9945245cf9092822b90d216 (April 2) and verify that it works and then bisect from there.

**Comment by n1ghttrap** [comment]
fyi using the free demo from https://champ.games/downloads

**Comment by hizzlekizzle** [comment]
Ok, looks like this is the commit that broke it:
https://github.com/stella-emu/stella/commit/73ffb94d43e7b8320a27423475e70b53b8f4206f

FAKEDIT: luckily, it was a super-easy fix, so I went ahead and put a PR in for it upstream: https://github.com/stella-emu/stella/pull/950

**Comment by n1ghttrap** [comment]
Neat, thanks.

**Comment by hizzlekizzle** [comment]
Looks like they merged it upstream, so we should be good. The new core should show up in the online updater soon if it's not there already.

**Comment by n1ghttrap** [comment]
Yep, fixed, thanks again.
