### ISSUE TITLE
MacOS: Windowed move doesn't save position

### ISSUE THREAD

**Issue by personaone** [libretro/RetroArch#14806]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

MacOS windowed mode position doesn't get saved, every time RA launches it's in the default position

### Expected behavior

Expected behaviour same as on Windows, but I think the option to save window position on MacOS is absent?

### Actual behavior

Every time the window launches in the same position

### Steps to reproduce the bug

1. Settings -> Output -> Windowed mode 
2. Either custom size or multiple sizes - doesn't matter, will start in default position (sometimes off screen)
3. [and so on...]

### Bisect Results

Has been there for as long as I can remember

### Version/Commit
You can find this information under Information/System Information

[INFO] RetroArch 1.14.0 (Git GIT_VERSION)

### Environment information

- OS: MacOS Ventura 13.1
- Compiler: [In case you are running local builds]

**Comment by estefan3112** [comment]
Yes, same here as long as I remember.
