### ISSUE TITLE
[Feature Request] Option to detect and change to native refresh/resolution on startup; useful for migrating between displays

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/RetroArch#14819]
## Description

When I take my Retroarch folder from one display to another it will use the previously saved/initially detected resolution from the display it made the config file with.  This is less than ideal when another display's native resolution differs.

### Expected behavior

An option, not default/mandatory behavior, for Retroarch to auto-detect and switch to a display's maximum/native refresh and resolution as it does on initial use.

### Actual behavior

1080p will appear small on a 4K display on startup til modified, or 4K will be massively cropped scaling back to 1080p causing usability issues til config is manually modified outside of app, or blindly changed in the UI.

### Steps to reproduce the bug

As said above.

### Bisect Results

As said above, and has been stock Retroarch behavior for as long as I can remember.

### Version/Commit

As said above.

### Environment information

Win10, Geforce cards.

**Comment by sonninnos** [comment]
Use windowed fullscreen and it will always stay at native resolution and rate.

**Comment by n1ghttrap** [comment]
This doesn't seem to be happening to me anymore.  Switched between 1080 and 4K displays seamlessly recently.  Maybe it's because I'm using Vulkan now.  Anyway, don't want to waste your time with it.  Closing.
