### ISSUE TITLE
Retroarch default paths

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#14826]
I have a few programs that read retroarch.cfg for various reasons.

I always thought that retroarch cfg files entries with paths had either complete paths or 'default'.

However i got a bug report (https://github.com/i30817/libretro-mkscumm/issues/2) that indicates some paths in windows start with ':/retroarch_dir' like ':/playlists'.

Is this a _bug_ or a actual thing, and accepted alternative? The reporter seems to indicate that restarting retroarch reset these which indicates it's retroarch itself writing them.

In _my_ config file there are a bunch of lines called 'default' which i expected would serve the same purpose as the above. So what is happening here?

**Comment by hizzlekizzle** [comment]
I think it's just for playlists. There's a setting for "portable playlists", which has the sublabel:

> When enabled, and 'File Browser' directory is also selected, the current value of parameter 'File Browser' is saved in the playlist. When the playlist is loaded on another system where the same option is enabled, the value of parameter 'File Browser' is compared with the playlist value; if different, the playlist entries' paths are automatically fixed.

**Comment by sonninnos** [comment]
All relative paths indicating RA directory has started with `:\` for as long as I can remember, and surely not by accident. Sure they could be more clear that it would only apply for `*_path` and not `*_directory`, but might to be too late to change that randomness now.

**Comment by i30817** [comment]
What is "default" then?

Right now my cfg has 'runtime_log_directory = "default"' among others.

**Comment by i30817** [comment]
If one is supposed to be just for directories and the other for file paths there are cases like 'content_database_path' too.

I'm going to handle both in my program but it's kind of weird.

**Comment by i30817** [comment]
@sonninnos I just want to ask before closing this. Are ':\somedir' default paths supposed to be _windows only_? I need to know this before i convert the paths to a linux for in my program.

If they're windows only  (which they should because they're using '\' as first separator), then if they have 2 or more subdirs after ':\' like for instance ':\databases\rdb' they need to convert the second part to databases/rdb before i try to joint it on a unix enviroment for instance

**Comment by sonninnos** [comment]
By checking out `frontend/drivers/` files and `fill_pathname_expand_special() `it seems it is Windows only.

**Comment by i30817** [comment]
Ok, i think my code will work then. Thank you, i'll close this.

I still find it strange that 'default' exists for some and this construct for windows only. But it's your decision and you may want to keep it for backwards compatibility anyway.
