### ISSUE TITLE
Main window is blank on MS WinXP 32-bit

### ISSUE THREAD

**Issue by Agvantibo** [libretro/RetroArch#14830]
## Description

Main window is blank

### Expected behavior

When I launch RetroArch, I get an empty console window and a small blank window. It essentially retains whatever picture was under it the moment it was opened. As far as I understand, this is supposed to be the main RetroArch UI, because pressing F makes it go fullscreen and double tapping Esc makes the window go away, while single Esc presses do nothing.

### Actual behavior

When I launch RetroArch, I get an empty console window and a small window containing the configured RetroArch UI.[
The verbose console output](https://pastebin.com/ShApdPiG)

### Steps to reproduce the bug

Run RetroArch

### Bisect Results

Right after installation

### Version/Commit

- RetroArch: v1.14.0, Compiler: MSVC 1600 32-bit Built: Dec 13 2022

### Environment information

- OS: Windows XP 32 Bit SP3
- [`systeminfo` command output](https://pastebin.com/FQ4hSML3)

### Attempted Troubleshooting

I’ve tried all the listed available video drivers (gl, gl1, d3d8, null), to no avail. I’ve also cycled between rgui, xmb and ozone for every driver. That didn’t help. None of the configurations worked, all drivers except null showed the same blank window.
Rebooting several times and reinstalling DX9 didn’t help, too.

**Comment by LibretroAdmin** [comment]
Try d3d9_hlsl

**Comment by Agvantibo** [comment]
> Try d3d9_hlsl

Unfortunately, didn't help.
d3d9_hlsl is not available. Here's what happens when I enter that into the config: 
```
C:\RetroArch-MSVC10-Win32>retroarch.exe -v
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Pentium(R) M processor 2.13GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] =================================================
[ERROR] Couldn't find any video driver named "d3d9_hlsl"
[INFO] Available video drivers are:
[INFO]  gl
[INFO]  gl1
[INFO]  d3d8
[INFO]  null
[WARN] Going to default to first video driver...
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[ERROR] Couldn't find any video driver named "d3d9_hlsl"
[INFO] Available video drivers are:
[INFO]  gl
[INFO]  gl1
[INFO]  d3d8
[INFO]  null
[WARN] Going to default to first video driver...
[INFO] [GL]: Found GL context: "wgl".
[INFO] [GL]: Detecting screen resolution: 1680x1050.
[INFO] [WGL]: Extensions: WGL_ARB_extensions_string WGL_ARB_make_current_read WGL_ARB_multisample WGL_ARB_pbuffer WGL_ARB_pixel_format WGL_ARB_render_texture WGL_ATI_pixel_format_float WGL_EXT_extensi
ons_string WGL_EXT_swap_control WGL_ATI_render_texture_rectangle
[INFO] [GL]: Vendor: ATI Technologies Inc., Renderer: MOBILITY RADEON X600 x86/SSE2.
[INFO] [GL]: Version: 2.0.5698 WinXP Release.
[INFO] [GL]: Using resolution 960x720.
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Linker log:  Link successful. The GLSL vertex shader will run in hardware. The GLSL fragment shader will run in hardware.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Linker log:  Link successful. The GLSL vertex shader will run in hardware. The GLSL fragment shader will run in hardware.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Linker log:  Link successful. The GLSL vertex shader will run in hardware. The GLSL fragment shader will run in hardware.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [XInput]: Found XInput v1.3.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Video]: Found display server: "win32".
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "gl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-MSVC10-Win32\content_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-MSVC10-Win32\content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "C:\RetroArch-MSVC10-Win32\content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "C:\RetroArch-MSVC10-Win32\content_favorites.lpl".
```

**Comment by LibretroAdmin** [comment]
This build does not seem to include the d3d9_hlsl driver. Which version did you download from the site again?

**Comment by Agvantibo** [comment]
![image](https://user-images.githubusercontent.com/68030524/211541897-a95a286e-07d5-4897-9e74-c020bd669ef9.png)
WinXP 32-bit installer. The downloaded file was tagged RetroArch-MSVC10-Win32-setup.exe

**Comment by Agvantibo** [comment]
Would it be possible to additionally install the required video driver, or should I try another build?  Did I download the wrong one?

**Comment by zibijani** [comment]
Up to version "v1.10.3" everything works ok, but from version "v1.11.0" to "v1.14" 
the video does not work and by that also the gui. No settings (video) help. 

My system:     XP-SP3
test soft:     RetroArch (XP 32 bits)
Graphics card: Ati Mobility Radeon X700

**Comment by SnowshoeIceboot** [comment]
Can also confirm this blank screen on XP SP3 32-bit with RetroArch-MSCVC10-Win32-setup.exe version 1.14.0.

CPU: AMD GX-415GA Quad-Core
RAM: 4GB DDR3
Graphics card: NVIDIA GeForce GT 730 (1GB VRAM)
NVIDIA Driver version: 340.99
NVIDIA Cg Toolkit: Yes
DirectX support: 9.0c
OpenGL support: 4.6
Vulkan support: N/A

My setup is hardware accelerated and on _real_ hardware. If you need to test Windows XP SP3 with DX9 hardware acceleration, you can install VirtualBox 5.4 (with Guest Additions) and disable Hyper-V.

**Comment by Intercato** [comment]
Had exactly the same problem. I can confirm that v.1.10.3 works fine.

**Comment by szr8** [comment]
I am seeing the same thing, no matter what drivers I specify in `retroarch.cfg`.

I just get an unrendered window with an empty console window behind it. I tried both the latest stable 1.14 and nightly msvc2010 builds.

Versions before 1.11 worked fine.

**Comment by LibretroAdmin** [comment]
Can anyone track it down to a specific commit?

**Comment by MarkusProkott** [comment]
+1: Same problem here. Tried stable versions (= v1.14.0) for XP & 98. Version 1.10.3 seems to work fine.

My system: XP-SP3
test soft: RetroArch (XP 32 bits)
Graphics card: NVIDIA GeForce 9500 GT

**Comment by wontonanimalchin** [comment]
I also have the same issue.
Windows xp service pack 3

**Comment by bslenul** [comment]
After bisecting the first bad commit seems to be fcbd72d, with this commit:

![image](https://github.com/libretro/RetroArch/assets/33353403/c51a69cd-ebc8-43fe-aabd-e3e92a64429f)

and with the previous one (fcbd72d):

![image](https://github.com/libretro/RetroArch/assets/33353403/b916c8e7-c3e8-4a13-a3a9-e282b8c2fbcf)

I even installed a Windows XP VM just for this! So I really hope it will help solving this long standing issue!

**Comment by vailkyte** [comment]
I confirm same bisect result on a native Windows XP environment.

**Comment by vailkyte** [comment]
Appears to be from ```video_st->active``` ==> ```video_st->flags & VIDEO_FLAG_ACTIVE``` but not sure where.

**Comment by vailkyte** [comment]
```
bool video_driver_active = (video_st->flags & VIDEO_FLAG_ACTIVE) ? true : false;
```

Must explicit typecast to bool. PR sent.

**Comment by bslenul** [comment]
Awesome! Glad to see I didn't bisect for nothing :D 

Thank you for the fix! 👍

**Comment by vailkyte** [comment]
@LibretroAdmin has fixed a lot of 2010 RA issues - it was pretty buggy besides the display problem.

Using the latest git build, very fluid on native - feels about the same as 2017 (xp) and 2019 (7). XP users will be excited their favorite frontend is back. :)
