### ISSUE TITLE
 Pressing dpad cancel others pressed buttons on Nvidia Shield with Xbox 360 wireless controller

### ISSUE THREAD

**Issue by cyrilpicard** [libretro/RetroArch#14836]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

On Nvidia Shield with wireless Xbox 360 controller, pressing dpad cancel others pressed buttons as if they were released. For exemple, in a racing game, if I hold the accelerator button, then press a direction, the accelerator button is released whereas I am still pressing it.

The bug don't occurs on Nvidia Shield with a Nintendo Switch Pro controller.
The bug don't occurs on Samsung Galaxy S8 with a wireless Xbox 360 controller.

### Expected behavior

Pressing dpad shouldn't interfer with other buttons

### Actual behavior

Pressing dpad cancel others pressed buttons

### Steps to reproduce the bug

1. Launch a racing game (tested with Sega Rally on Yaba Sanshiro core), start a race
2. Press and hold B button on Xbox 360 controller, the car accelerate
3. Press left or right direction on dpad without releasing B button
4. The car don't accelerate anymore, as if B button was released

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
Reproduced in Retroarch 1.14.0 from retroarch.com and Retroarch 1.9.12 from Google Play store

### Environment information

- OS: Android on Nvidia Shield

**Comment by cyrilpicard** [comment]
Same issue with Geforce Now and MD.emu. Most likely an Android/Shield issue.

**Comment by kanjieater** [comment]
Anyone ever figure out how to workaround this?
