### ISSUE TITLE
Screenshots not saved to Content Directory when set

### ISSUE THREAD

**Issue by christianhaitian** [libretro/RetroArch#14840]
## Description
When taking screenshots in the retroarch menu, it creates a directory in the user home directory with some extended ASCII characters.

### Expected behavior

The screenshots should be saved to the respective content directory as set in the retroarch configuration.

### Actual behavior

When taking screenshots in the retroarch menu, it creates a directory in the user home directory with some extended ASCII characters.

### Steps to reproduce the bug

Access quick menu
Select "Take Screenshot"
1 directory per game is created in the user's home folder with malformed ascii characters instead of the content directory.

### Bisect Results

Unfortunately, I'm not sure when this started to occur.

### Version/Commit
Retroarch 1.14.0 (Commit 932b4ad)

### Environment information

- OS: Ubuntu 19.10 for Arm64
- Compiler: GCC 8.5

**Comment by gouchi** [comment]
What it the output of ?

`grep -E '^screenshots_|^screenshot_' ~/.config/retroarch/retroarch.cfg`

Thank you.

**Comment by christianhaitian** [comment]
```
ark@rg353v:~$ grep -E '^screenshots_|^screenshot_' ~/.config/retroarch/retroarch.cfg
screenshot_directory = "default"
screenshots_in_content_dir = "false"
ark@rg353v:~$
```

**Comment by christianhaitian** [comment]
I tried settings `screenshots_in_content_dir = "true"` and the results are still the same.

**Comment by christianhaitian** [comment]
Nevermind, the emulator I tried was a 32bit retroarch one that saves to a different folder.  I tried a proper 64bit retroarch emulator and screenshots save to their respective content folder they should with `screenshots_in_content_dir = "true"`.  Thank you for the pointer.
