### ISSUE TITLE
Crash when closing content with hotkey after being inside a core option category

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#14851]
## Description

I noticed getting a lot of crashes on close content lately but I struggled to reproduce as it seemed random, but I noticed today it was related to the "Close Content" hotkey AND the core options categories.

Basically if you go inside a core options category, toggle quick menu to return to the game then close content with the hotkey, RetroArch will crash.

GDB output: https://pastebin.com/C9Yisd6v

### Steps to reproduce the bug

1. Set a key/button for `Settings > Input > Hotkeys > Close Content`.
2. Start a game with Genesis Plus GX (or any core with core options categories).
3. Go to `Quick Menu > Core Options > System` or any other category.
4. Press F1 to return to the game.
5. Press your "Close Content" hotkey.

### Bisect Results

Already bisected, it started to happen with d5f58fd4357ba6e18abdf00cd4f753f45d348257, so I hope you don't mind me pinging you about this @sonninnos as you're most likely the best person to know what's happening here 😳 

### Version/Commit

- RetroArch: 1.14.0 / f347c2d

### Environment information

- OS: Windows 10 / Linux Mint VM

**Comment by sonninnos** [comment]
Oops, fixed, and thanks for the log, it helped getting straight to the jugular.

**Comment by bslenul** [comment]
Works like a charm, thank you for the quick fix! ❤️
