### ISSUE TITLE
Broken UWP Builds, we missed you (not)

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#14866]
## Description

Either PR https://github.com/libretro/RetroArch/pull/14850 or https://github.com/libretro/RetroArch/pull/14853 broke UWP builds.

These are the errors:

![image](https://user-images.githubusercontent.com/35014183/213079381-b0694821-c5b9-492e-a141-eabee5ef7083.png)

@warmenhoven Since you were behind both PRs, do you have any thoughts about these errors?

### Expected behavior

RetroArch to build

### Actual behavior

Build errors

### Bisect Results

Either PR https://github.com/libretro/RetroArch/pull/14850 or https://github.com/libretro/RetroArch/pull/14853 were the culprits.

### Environment information

- OS: Windows 10
- Compiler: Visual Studio 2022

**Comment by warmenhoven** [comment]
```
3 matches for "std::max" in buffer: spirv_msl.cpp
   2367:			num_components = std::max(num_components, get_target_components_for_fragment_location(locn));
   3849:							location_meta.num_components = std::max(location_meta.num_components, component + type.vecsize);
   7209:		last_significant = std::max(last_reference, last_pointer);
```

Looks like that should instead be something more like:

```
4 matches for "max<" in buffer: spirv_msl.cpp
   4518:					array_stride /= max<uint32_t>(array_size, 1u);
   4725:			array_stride /= max<uint32_t>(to_array_size_literal(mbr_type, dim), 1u);
  15923:		value_size *= max<uint32_t>(array_size, 1u);
  16034:			return get_declared_type_array_stride_msl(type, is_packed, row_major) * max<uint32_t>(array_size, 1u);
```

**Comment by warmenhoven** [comment]
https://github.com/KhronosGroup/SPIRV-Cross/pull/2089

**Comment by GABO1423** [comment]
@warmenhoven Your commit did fix the errors... but new ones came up:

![image](https://user-images.githubusercontent.com/35014183/213332827-899039e0-2c8c-4ada-a951-bcbe6cb2549c.png)

Visual Studio also shows up some code errors in the file:

![image](https://user-images.githubusercontent.com/35014183/213332894-a8ec966e-031d-4516-9e8c-9e22b33abb6b.png)

**Comment by LibretroAdmin** [comment]
Should be fixed by this now -
https://github.com/libretro/RetroArch/commit/993d4ee64f1ca040e87065535c5e4e50ef31d7e5

**Comment by GABO1423** [comment]
Can confirm it's fixed. Closing
