### ISSUE TITLE
screenshot not working on D3D video drivers.

### ISSUE THREAD

**Issue by LuanVSO** [libretro/RetroArch#14868]
# First and foremost, consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

when you try to take a screenshot while using any of the DirectX drivers on windows, nothing will happen.
this will also render the ai service unusable. 

### Expected behavior

screenshot is taken and saved.

### Actual behavior

nothing

### Steps to reproduce the bug

1. set d3d12 as the video driver.
2. save and exit Retroarch
3. start a game and try to take a screenshot.
4. no notification will appear, and no file will be saved in the screenshot directory.

### Bisect Results

as far as i can tell, this is a known issue by the community for quite some time, but i didn't find an issue for it:
[example of the bug being discussed](https://www.reddit.com/r/RetroArch/comments/oy75xd/comment/h7s9ubs/?utm_source=share&utm_medium=web2x&context=3)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.14.0/e3c92b0]

### Environment information

- OS: [Windows 11 10.0.22621.1105]

**Comment by LuanVSO** [comment]
yep, i wonder why GitHub didn't find it when i was searching for it

**Comment by hizzlekizzle** [comment]
heh, no worries. Github's search function is... not great.
