### ISSUE TITLE
Opening retroarch gives me X error. It closes directly.

### ISSUE THREAD

**Issue by SosseHD** [libretro/RetroArch#14878]
## Description
I just installed the Retroarch packages, and the libretro packaged on my Artix machine. When I open retroarch, by typing it into the command line, the window opens, is black and closes directly in under 1 second. And I get the following output:
```

sosse-artix:[sosse]:~$ retroarch
X Error of failed request:  BadValue (integer parameter out of range for operation)
 Major opcode of failed request:  152 (GLX)
 Minor opcode of failed request:  24 (X_GLXCreateNewContext)
 Value in failed request:  0x0
 Serial number of failed request:  43
 Current serial number in output stream:  44
sosse-artix:[sosse]:~$
```

I expected it to open, so that I can start configuring the settings and try to play a first game.

### Steps to reproduce the bug

1. As I said I have Artix, added the Arch repos to the /etc/pacman.conf file I added universe, and the arch community, extra and multilib repos.
2. I installed the packages in this way. 
> doas pacman -S retroarch retroarch-assets-glui retroarch-assets-ozone retroarch-assets-xmb
>doas pacman -S libretro

### Version/Commit
sosse-artix:[sosse]:~$ pacman -Q --info retroarch
Name            : retroarch
Version         : 1.14.0-1
Description     : Reference frontend for the libretro API
Architecture    : x86_64
URL             : http://www.libretro.com/
Licenses        : GPL
Groups          : libretro
Provides        : None
Depends On      : alsa-lib  ffmpeg  flac  libass.so=9-64  libdrm
                  libfreetype.so=6-64  libgl  libpulse  libudev.so=1-64
                  libusb-1.0.so  mbedtls  mesa  openal  qt5-base  sdl2  spirv-tools
                  v4l-utils  zlib
Optional Deps   : gamemode: GameMode support
                  libdecor: Wayland decorations
                  libretro-overlays: Collection of overlays [installed]
                  libretro-shaders: Collection of shaders [installed]
                  libxinerama: X11 support [installed]
                  libxrandr: X11 support [installed]
                  python: retroarch-cg2glsl [installed]
                  retroarch-assets-ozone: Ozone menu assets [installed]
                  retroarch-assets-xmb: XMB menu assets [installed]
                  wayland: Wayland support [installed]
Required By     : retroarch-assets-glui  retroarch-assets-ozone
                  retroarch-assets-xmb
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 13.01 MiB
Packager        : Maxime Gauduin <alucryd@archlinux.org>
Build Date      : Mon 12 Dec 2022 11:44:11 PM CST
Install Date    : Fri 20 Jan 2023 12:31:17 PM CST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

---
The libretro packages I installed (wanted every core as im not sure what games i wanna play)
warning: libretro-beetle-pce-1161-1 is up to date -- reinstalling
warning: libretro-beetle-pce-fast-1203-1 is up to date -- reinstalling
warning: libretro-beetle-psx-2646-1 is up to date -- reinstalling
warning: libretro-beetle-psx-hw-2646-1 is up to date -- reinstalling
warning: libretro-beetle-supergrafx-967-1 is up to date -- reinstalling
warning: libretro-blastem-2052-2 is up to date -- reinstalling
warning: libretro-bsnes-1:3075-1 is up to date -- reinstalling
warning: libretro-bsnes-hd-51-1 is up to date -- reinstalling
warning: libretro-bsnes2014-1:577-2 is up to date -- reinstalling
warning: libretro-citra-9294-2 is up to date -- reinstalling
warning: libretro-core-info-1.14.0-1 is up to date -- reinstalling
warning: libretro-desmume-6349-1 is up to date -- reinstalling
warning: libretro-dolphin-33042-1 is up to date -- reinstalling
warning: libretro-duckstation-2105-2 is up to date -- reinstalling
warning: libretro-flycast-5390-1 is up to date -- reinstalling
warning: libretro-gambatte-982-1 is up to date -- reinstalling
warning: libretro-genesis-plus-gx-1974-1 is up to date -- reinstalling
warning: libretro-kronos-7016-2 is up to date -- reinstalling
warning: libretro-mame-85763-1 is up to date -- reinstalling
warning: libretro-mame2016-44430-1 is up to date -- reinstalling
warning: libretro-melonds-2012-1 is up to date -- reinstalling
warning: libretro-mesen-2903-2 is up to date -- reinstalling
warning: libretro-mesen-s-916-3 is up to date -- reinstalling
warning: libretro-mgba-8704-1 is up to date -- reinstalling
warning: libretro-mupen64plus-next-1:440-1 is up to date -- reinstalling
warning: libretro-nestopia-1:100-1 is up to date -- reinstalling
warning: libretro-overlays-237-1 is up to date -- reinstalling
warning: libretro-parallel-n64-5243-1 is up to date -- reinstalling
warning: libretro-picodrive-2270-1 is up to date -- reinstalling
warning: libretro-play-7480-1 is up to date -- reinstalling
warning: libretro-ppsspp-35342-1 is up to date -- reinstalling
warning: libretro-retrodream-1104-2 is up to date -- reinstalling
warning: libretro-sameboy-1720-2 is up to date -- reinstalling
warning: libretro-scummvm-93205-2 is up to date -- reinstalling
warning: libretro-shaders-slang-1146-1 is up to date -- reinstalling
warning: libretro-snes9x-2170-1 is up to date -- reinstalling
warning: libretro-yabause-3342-1 is up to date -- reinstalling
warning: retroarch-1.14.0-1 is up to date -- reinstalling
warning: retroarch-assets-glui-1:439-1 is up to date -- reinstalling
warning: retroarch-assets-ozone-1:439-1 is up to date -- reinstalling
warning: retroarch-assets-xmb-1:439-1 is up to date -- reinstalling

### Environment information

- OS: Artix

**Comment by hizzlekizzle** [comment]
Does it give you any more info if you add the --verbose flag when you launch?

Do any of our "universal" packages--that is, AppImage, FlatPak or Snap--work for you?

**Comment by SosseHD** [comment]
> Does it give you any more info if you add the --verbose flag when you launch?
> 
> Do any of our "universal" packages--that is, AppImage, FlatPak or Snap--work for you?

Yes, following is the new information:
```
sosse-artix:[sosse]:~$ retroarch --verbose
[INFO] [Config]: Looking for config in: "/home/sosse/.config/retroarch/retroarch.cfg".
[WARN] [GameMode]: GameMode cannot be enabled on this system ("dlopen failed - libgamemode.so: cannot open shared object file: No such file or directory.") https://github.com/FeralInteractive/gamemode needs to be installed.
[WARN] [Config]: GameMode unsupported - disabling...
[INFO] RetroArch 1.14.0 (Git ad89b0c655)
[INFO] === Build =======================================
[INFO] CPU Model Name: 11th Gen Intel(R) Core(TM) i9-11900F @ 2.50GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: ad89b0c655
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 960x720.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GLX]: GLX_EXT_swap_control_tear supported.
[INFO] [GL]: Found GL context: "x".
[INFO] [GL]: Detecting screen resolution: 2560x1440.
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  43
  Current serial number in output stream:  44
sosse-artix:[sosse]:~$ 
```
And no they dont work, I tried AppImage even firstly, but i had the same problem. I didnt think of why it wouldnt work i just wanted to have it per package as I hate appimages. What I love about linux is i dont have so many "exe" files and such lying around everywhere, appimages just need to be somewhere. Anyways, no appimage doesnt work either. I dont think the problem can be solved by trying flatpak or snap right?

**Comment by hizzlekizzle** [comment]
No, probably wouldn't help. I mainly suggested it just to see if there was a lib/dependency problem afoot, but that doesn't seem to be the case.

Can you open your retroarch.cfg and see what video_driver it's using? (it's normally located in ~/.config/retroarch)

**Comment by SosseHD** [comment]
> No, probably wouldn't help. I mainly suggested it just to see if there was a lib/dependency problem afoot, but that doesn't seem to be the case.
> 
> Can you open your retroarch.cfg and see what video_driver it's using? (it's normally located in ~/.config/retroarch)

No video driver at all 0.o. This is the content:
 ```
1 assets_directory = "/usr/share/retroarch/assets"
  2 audio_filter_dir = "/usr/lib/retroarch/filters/audio"
  3 config_save_on_exit = "true"
  4 libretro_directory = "/usr/lib/libretro"
  5 libretro_info_path = "/usr/share/libretro/info"
  6 menu_show_core_updater = "false"
  7 video_filter_dir = "/usr/lib/retroarch/filters/video"
  8 video_shader_dir = "/usr/share/libretro/shaders"

```

**Comment by hizzlekizzle** [comment]
hmm that's weird. Can you try adding it manually? video_driver = "gl" would be the first thing to try, but if that doesn't work, "glcore" or "vulkan" would be good to try, too.

**Comment by SosseHD** [comment]
> hmm that's weird. Can you try adding it manually? video_driver = "gl" would be the first thing to try, but if that doesn't work, "glcore" or "vulkan" would be good to try, too.

basically same thjing after gl, after glcore it says segmentation fault, after vulkan, currently writing this while doing holy shit this shit works! IT WORKS :D weird AF to use because i dont have a controller but it opens!

**Comment by hizzlekizzle** [comment]
haha, great! I'm glad that's working for you.

Are you using wayland, by chance? I think our vulkan driver usually plays nicer with it.

**Comment by SosseHD** [comment]
> haha, great! I'm glad that's working for you.
> 
> Are you using wayland, by chance? I think our vulkan driver usually plays nicer with it.

Nope! after i switched from fedora 37 to artix, im using Xorg

**Comment by hizzlekizzle** [comment]
hmm, weird. oh well, I'm glad vulkan works, at least.
