### ISSUE TITLE
N64 roms crash

### ISSUE THREAD

**Issue by Tashton2013** [libretro/RetroArch#14880]
Any game I try crashes no matter what verison or what website I use, playlist is set up correctly wrc 

### Steps to reproduce the bug

1. Have retroarch n64 playlist set up and games downloaded and everything updated in retro arch 
2. Load a N64 game up 
3. Crashes instantly 

- RetroArch: version 22.10.17.70

Series s console 

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
Can you post a verbose log of the crash?

However, this sort of thing is usually better handled on our forums, discord or subreddit. If you wouldn't mind moving it to one of those, we'll do some troubleshooting to verify whether an actual bug is at work.

**Comment by Tashton2013** [comment]
Could you possibly write how to find that sorry I'm new to retroarch

**Comment by hizzlekizzle** [comment]
This doc explains the process: https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-via-menu

Once you reproduce the behavior with logging enabled, it will create a text file in your 'logs' directory. You can open that file with a text editor and post the contents somewhere we can view it easily, as per these instructions: https://docs.libretro.com/guides/generating-retroarch-logs/#posting-logs-in-the-forum-and-github

**Comment by DerinQyu** [comment]
This does not happen to me on nintendo switch, android and windows.
