### ISSUE TITLE
Using RetroArch_Metal on Mac OS and running Dreamcast roms with FlyCast core changes driver from Metal to Vulkan, which crashed Retroarch on next launch 

### ISSUE THREAD

**Issue by Sethur** [libretro/RetroArch#14888]
## Description

Using RetroArch Metal on Mac OS 12.6.2 Monterey with an Intel Mac and Intel GPU and running a DreamCast Rom on the FlyCast core changes the video driver from "Metal" to "Vulkan". The ROM then runs fine, but on the next launch of RetroArch, the Vulkan driver causes RetroArch to crash directly on launch.

This crash also happens when the Vulkan driver is selected directly via settings and RetroArch is restarted.

### Steps to reproduce the bug

1. Launch RetroArch_Metal on Mac OS Monterey with Intel Mac and Intel GPU with default settings (i.e. Metal video driver)
2. Load any Dreamcast ROM
3. Restart Retroarch to trigger crash. config/retroarch.cfg now contains `video_driver = "vulkan"`

### Version/Commit

- RetroArch: Nightly from 2023-01-22

### Environment information

- OS: Mac OS 12.6.2 Monterey. Intel CPU, Intel GPU

**Comment by Sethur** [comment]
Update: It appears that the issue only happens when you exit Retroarch from within the Dreamcast emulation (via double ESC) without closing the content first.

**Comment by LibretroAdmin** [comment]
Can be closed according to @warmenhoven with the latest PR merged.
