### ISSUE TITLE
RetroArch from version "v1.11.0" to "v1.14" - video problem

### ISSUE THREAD

**Issue by zibijani** [libretro/RetroArch#14892]
Up to version "v1.10.3" everything works ok, but from version "v1.11.0" to "v1.14.0" 
the video does not work and by that also the gui. No settings (video) help. 

My system:     XP-SP3
test soft:     RetroArch-MSVC10-Win32  (XP 32 bits)
Graphics card: Ati Mobility Radeon X700

**Comment by RobLoach** [comment]
Which video driver in RA are you using?

**Comment by zibijani** [comment]
With running versions of RA, I mainly use :
video_driver = "d3d8"

**Comment by gouchi** [comment]
Duplicate of #14830 ?

According to this [post](https://forums.libretro.com/t/retroarch-on-winxp-32-bit-transparent-window/40195/6), it should work as fallback with video driver `gdi` and menu driver `rgui`.

**Comment by RobLoach** [comment]
Does look similar to the other issue. Thanks zibijani and gouchi!
