### ISSUE TITLE
RetroArch 1.14.0 nightly on Mac OS Monterey with Intel CPU and GPU crashes when using Vulkan video driver

### ISSUE THREAD

**Issue by Sethur** [libretro/RetroArch#14894]
## Description

When using the RetroArch "Metal" 1.14.0 nightly build from Jan 22nd on an Intel Mac with Mac OS 12.6.2 Monterey using an Intel HD GPU, a crash to desktop without any error message happens on launch when using the "Vulkan" video driver. Vulkan itself (using MoltenVK) works great with other standalone emulators (like Dolphin).

### Expected behavior

RetroArch should not crash on launch when using the Vulkan driver.

### Actual behavior

RetroArch crashes on launch without error message when using the Vulkan driver (and otherwise default settings on a fresh install).

### Steps to reproduce the bug

1. Install the latest nightly build of RetroArch Metal
2. Go to `Settings->Video` and select the vulkan video driver
3. Restart RetroArch and observe crash to desktop.
[retroarch__2023_01_23__14_41_32.log](https://github.com/libretro/RetroArch/files/10480299/retroarch__2023_01_23__14_41_32.log)

### Bisect Results

I have included a log file of a crashed launch with log level `debug` for everything, but it does not seem very helpful.

### Version/Commit

- RetroArch: 1.14.0 Nightly Build from 2023-01-22

### Environment information

- OS: Mac OS 12.6.2 Monterey

**Comment by LibretroAdmin** [comment]
Can be closed now with the latest PR merged according to @warmenhoven
