### ISSUE TITLE
Bug concerning onscreen overlay

### ISSUE THREAD

**Issue by bishbo1234** [libretro/RetroArch#14909]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
The onscreen overlay has an arrow button on the bottom right corner, which when touched, hides or unhides the overlay. This works fine. However, in the latest nightly build I downloaded (1-25-2023), there is a new bug. If you map a hotkey under the HotKey Enable feature within Inputs -> Hotkeys, this breaks the show/hide overlay button. Once a hotkey button is enabled, the overlay button no longer hides and unhides the overlay.

Previous to using this nightly build, I was using a December nightly build which worked fine. So the bug may have been introduced sometime within the past month.

[Description of the bug]

### Expected behavior

[What you expected to happen]
The show/hide overlay button should always work, regardless of whether or not you have a hotkey enabled.
### Actual behavior

[What is actually happening]
Once a HotKey is set in the “HotKey enable” toggle under Inputs -> Hotkeys, the overlay show/hide button no longer works. 
### Steps to reproduce the bug

1. [First step]
Goto inputs, Hotkeys, and toggle on the HotKey enable and set a hotkey button (for example, the select button on a wireless controller)
3. Start any game, and try to hide the onscreen overlay by pressing the onscreen button in the bottom right corner. 
4. You will notice the button does not work anymore. It’s function can be restored by restoring Retroarch’s configuration to default. 

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
Using nightly build 1-25-23, version 1.14.0.

### Environment information
On iOS 16.3. 

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by Tatsuya79** [comment]
@sonninnos Probably something to add to the menu button exception.
