### ISSUE TITLE
Configuration file is not saved when '--appendconfig' is used

### ISSUE THREAD

**Issue by cmitu** [libretro/RetroArch#14917]
## Description

When `--appendconfig` is used and a core + game are loaded from the CLI, saving the configuration file fails. On 1.14.0  a _fail to save configuration /path/to/config_ message is logged, while with the current _master_ an empty info message is shown.

![error copy](https://user-images.githubusercontent.com/31816814/215258998-bb947b95-fbde-4c9d-bfae-fee3f9fedf27.png)

### Expected behavior

Configuration file should be saved, either when called explicitly or on RetroArch's exit (the default _save_on_exit_ behavior).

### Actual behavior

The configuration file is not saved.

### Steps to reproduce the bug

1. Start a game from the cli with `-L /path/to/core /path/to_file --apendconfig /path/to/additional.cfg`, then try to save the configuration from the menu.

or

2. Start a game from the cli with `-L /path/to/core /path/to_file --apendconfig /path/to/additional.cfg`, ensure `save_on_exit` is enabled and exit the game.

### Bisect Results

I think this started before 1.12.0, when `--appendconfig` was modified to load the config similarly to overrides. In https://github.com/libretro/RetroArch/pull/14624 (added by @sonninnos), the extra _override loaded_ was removed, but I guess internally the configuration from `--appendconfig` may still use `config_load_override` and probably the `RUNLOOP_FLAG_OVERRIDES_ACTIVE` flag is set, which prevents the configuration being saved.

### Version/Commit
[INFO] Built: Jan 28 2023
[INFO] Version: 1.14.0
[INFO] Git: 482c8ccf35

### Environment information

- OS: Linux `armhf`, Raspberry Pi OS 11 (_bullseye_) 
- Compiler: `gcc`, 10.2

**Comment by sonninnos** [comment]
The flag was indeed the culprit. Fixed some other essential things too while at it.

**Comment by cmitu** [comment]
@sonninnos thank you !
