### ISSUE TITLE
Steamdeck: Corrupted Icons using glcore and xmb

### ISSUE THREAD

**Issue by notimp** [libretro/RetroArch#14913]
Please, please fix.

I'm dependent on using glcore for a bunch of my shader/filter combinations, and this just kills me being able to use retroarch.

Video for reference.

It takes me a while to find back to the appearance menu, so please bare with me, I eventually do.

Latest discover store version. It wasnt an issue a few days ago - and I think there was a build version update in between.

In the video I'm first switching between xmb themes using vulkan (to show that this works), and then using glcore. and as soon as glcore is loaded the xmb icons corrupt. same on restart. in the video I didnt restart, because switching themes also refreshes the renderer, and then renders the theme using glcore.

https://user-images.githubusercontent.com/47777453/215212661-3505961a-fb47-46c4-bbc9-e69a592a2d07.mp4

Please look into this. Please find a way to fix it.

Thank you.

**Comment by hizzlekizzle** [comment]
Someone on discord reported a similar problem using the FlatPak on a Pop!OS installation. It appears the flatpak's assets are messed up:
![image](https://user-images.githubusercontent.com/2805586/215216955-d166cf81-b6f7-4b10-a7b6-68a26402f25d.png)

**Comment by notimp** [comment]
Thank you very much for the response. Only happens with the renderer set to glcore though.

Tried an uninstall/reinstall already, no difference.

**Comment by notimp** [comment]
Retroarch issue seems fixed by downloading the latest updates from the discover store, not retroarch related, so system stuff. That and or downloading assets.zip in the past, via the online updater.

I swear that after downloading assets.zip I opened retroarch again, and it still was messed up, so it likely was a system level file that might have broken image decoding in glcore here? 

System update apparently also broke and fixed Citra in the same time window. According to Emudeck maintainers. (Unrelated?)

So the good and the bad news is, that for now - I cant reproduce it anymore. :)

I'll leave the ticket open in case this changes in the recent future, or others want to add to It, but if nothing changes, I'll close it in a few days myself.

**Comment by notimp** [comment]
Looks good so far on all ends, I think I can close the ticket. :)
