### ISSUE TITLE
Impossible to run FFIX Japan (but the files seem fine)

### ISSUE THREAD

**Issue by vdegenne** [libretro/RetroArch#14958]
## Description

I am reporting here because it seems that RetroArch is struggling running a specific game (FFIX Japan).
I have all the required files :
- the game's 4 discs (united in a single folder + m3u file creation)
- scph5001.bin (RetroArch asks for this file when I launch the game)
- Beetle PSX HW Core

I checked all the md5 sums and nothing is corrupted, also FFIX (USA) works fine.
When I start the game I have the PS loading screen but immediately after I get the main menu screen and the game doesn't load.
<img width="120" alt="image" src="https://user-images.githubusercontent.com/2827383/217234514-d91f6e54-0c31-43ef-b69c-6baeb13d7ebe.png">

I never had this problem before with other games.
I tried to track the issue using Error Level logging, there are few errors I don't know if it's related to this problem, here's the dump:

```
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 9 5900HS with Radeon Graphics
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Dec 13 2022
[INFO] Version: 1.14.0
[INFO] Git: e3c92b0
[INFO] =================================================
[libretro ERROR] TOC first(99)/last(98) track numbers bad.
[libretro ERROR] TOC first(99)/last(98) track numbers bad.
[libretro ERROR] TOC first(99)/last(98) track numbers bad.
[libretro ERROR] TOC first(99)/last(98) track numbers bad.
[libretro ERROR] Not ISO-9660
[libretro ERROR] Not ISO-9660
[libretro ERROR] Not ISO-9660
[libretro ERROR] Not ISO-9660
[libretro ERROR] Not ISO-9660
[libretro ERROR] Not ISO-9660
[libretro ERROR] Not ISO-9660
[libretro ERROR] Not ISO-9660
```

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.14.0

### Environment information

- OS: Windows 11

**Comment by vdegenne** [comment]
Another thing that comes to confirm it's an issue with RetroArch, I tried to load the game in another emulator (Duck) and it runs without any issues.
Kinda sad since I would prefer to use RetroArch.

**Comment by vdegenne** [comment]
Another thing that comes to confirm it's an issue with RetroArch, I tried to load the game in another emulator (Duck) and it runs without any issues.
Kinda sad since I would prefer to use RetroArch.

**Comment by Sanaki** [comment]
This is an issue with your dump of the game. I just verified using a copy of the game verified against Redump's hashes and it boots fine in Beetle PSX HW, without those errors.

I recommend validating your md5 hashes against the ones shown here:
http://redump.org/disc/1968/

**Comment by vdegenne** [comment]
@Sanaki Thanks for your help.
The hashes are valid, also I am pretty sure the cues are fine but if there is anyway could you please tell me where I can *legally* download them (you could also use my email address on my profile to send me them directly if this is not bothering you).

**Comment by vdegenne** [comment]
@Sanaki nvm there were in fact something wrong with  the cues ... Thanks
