### ISSUE TITLE
Atari ST emulator on EmuDeck

### ISSUE THREAD

**Issue by darkgothmog001** [libretro/RetroArch#14952]
Hello,

I wanted to emulate the Atari ST so since I was using Amiga on retroarch I wanted to check for the Atari ST and it looks like there is no option (i.e. no folder) for Atari ST.

Is Atari ST supported on emu deck ? if so how ? If not, can it be ?

thanks

**Comment by gouchi** [comment]
As written in the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md),

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

So it will be better your post your request on the [dedicated repository](https://github.com/dragoonDorise/EmuDeck/issues).

Thank you.

**Comment by darkgothmog001** [comment]
I was asked on the emudeck > retro arch forum to fill an issue here

**Comment by zoltanvb** [comment]
There is one core: https://github.com/libretro/hatari
