### ISSUE TITLE
Compiler error in `gl3.c` if `GL_DEBUG` is enabled

### ISSUE THREAD

**Issue by JesseTG** [libretro/RetroArch#14962]
## Description

When compiling with the `GL_DEBUG` flag enabled, RetroArch fails to build.

### Expected behavior

A successful build.

### Actual behavior

Fails because of missing struct fields.

### Steps to reproduce the bug

1. Run `./configure --enable-debug`
2. Run `make DEBUG=1`
3. Watch for the build error.

### Bisect Results

No need, it happened with this commit. This part of the file wasn't changed:

https://github.com/libretro/RetroArch/blob/master/gfx/drivers/gl3.c#L1036-L1052

**Comment by gouchi** [comment]
Fixed with this [commit](https://github.com/libretro/RetroArch/commit/d5dc405ac1e58410b02de49e12e63450c253ea2d).
