### ISSUE TITLE
Black Screen (No RGUI) on gl to analog monitor on linux

### ISSUE THREAD

**Issue by jimson-jimson** [libretro/RetroArch#1497]
I'm using an NVIDIA 5200 FX with Nvidia-173 on Xubuntu 14.04 connected to an old trinitron via s-video. Retroarch starts to a black screen on gl, SDL2 works, and OpenGL works in everything else (GLX gears is fine, 2000 frames). When running retroarch on the terminal, I get this warn:

RetroArch [WARN] :: gfx_ctx_glx_set_video_mode :: [GLX]: Cannot find swap interval call.

Found another similar issue here, but upon running glxinfo, that guy found that he didn't have this mode in his driver. I DO have this mode in my driver upon running glxinfo, but it's having issues with Retroarch. I repeat, upon running glxinfo, I do have gfx_ctx_glx_set_video_mode

I previously had multiple kernels and nvidia only built for some of them. I've removed all kernels that Nvidia won't work with, and rebuilt nvidia-173 afterwards, no luck.

**Comment by twinaphex** [comment]
I added this commit - 

https://github.com/libretro/RetroArch/commit/9803f62f02a7214cf9797e3bb79b879fd4e44037

Test if this works with your Nvidia GPU. This is assuming it will work with the glXSwapIntervalSGI function that I added in this commit.

**Comment by jimson-jimson** [comment]
Nope. Compiled up fresh and it gives the same error. I'll mess with it more on the weekend. It's probably a problem with the NVIDIA driver.

**Comment by fr500** [comment]
Please test on the current code, and reopen if the issue persists
