### ISSUE TITLE
Updated RetroArch and now keeps saying "Failed to open libretro core" on when I attempt to launch anything.

### ISSUE THREAD

**Issue by liftedterps** [libretro/RetroArch#14985]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

"Failed to open libretro core"

### Expected behavior

Launch the game as it did prior to the update. 

### Actual behavior

Gives me error "Failed to open libretro core" anytime I attempt to run any game.

### Steps to reproduce the bug

1. Launch ANY game for ANY system.
2. Watch it not launch and be disappointed
3. "Failed to open libretro core" 

### Bisect Results

After an update. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: e3c92b0

### Environment information

- OS: Windows 10 64x bit 
- Compiler: [In case you are running local builds]

**Comment by gouchi** [comment]
Hi,

Please provide some [log](https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-windows).

Thank you.

Kind regards,

**Comment by liftedterps** [comment]
I deleted that version. I just did a complete reinstall and transferred my saves. I originally updated because a core wasn't working properly. But the update basically broke all of RetroArch for me as nothing would launch. Maybe it should be a little bit easier to update RA as whole, no?

**Comment by atirage21** [comment]
[ERROR] Failed to open libretro core: "/storage/.kodi/addons/script.retroarch.launcher.Amlogic-no.aarch64/lib/libretro/uae4arm_libretro.so"
[ERROR] Error(s): libmpg123.so.0: cannot open shared object file: No such file or directory

**Comment by LibretroAdmin** [comment]
I think this is a very weird old thread to necropost in
