### ISSUE TITLE
vk_wayland ignores KDE Plasma's screen orientation/rotation.

### ISSUE THREAD

**Issue by luluco250** [libretro/RetroArch#14995]
## Description

Certain portable x86-based devices use screens that report rotated resolutions, such as 1080x1920 rather than 1920x1080. This can be mitigated by using `video=efifb fbcon=rotate:1` kernel parameters to rotate the Linux console/tty, then individual desktops can be set to rotate.

It seems RetroArch's `vk_wayland` video context driver ignores the screen orientation when fullscreen while running under KDE Plasma. 

The OpenGL on Wayland video context driver `wayland` does not present this issue nor does `vk_x` (Vulkan on X11, through `WAYLAND_DISPLAY='' retroarch`).

I have tested this on both GNOME Shell (Wayland0 and Sway as well, neither of which present the issue (with both rotated through their respective settings).

### Expected behavior

RetroArch on Vulkan on Wayland in fullscreen should respect the screen orientation set in KDE Plasma, as is the case with OpenGL on Wayland, Vulkan on X11 as well as Vulkan on Wayland in GNOME Shell (Wayland) and Sway.

### Actual behavior

RetroArch, when using the Vulkan video driver on Wayland in fullscreen running under KDE Plasma, ignores desktop orientation settings.

### Steps to reproduce the bug

1. Run RetroArch in a device with a native portrait resolution with KDE Plasma.
2. Set the display orientation to landscape in KDE's settings.
3. Start RetroArch, set the video driver to `vulkan` and restart the application.
4. Change RetroArch to fullscreen mode.
5. RetroArch will launch rotated compared to the desktop.
6. Change the video driver to `glcore` and restart.
7. RetroArch will launch in the expected orientation.
8. Change the video driver back to `vulkan` and restart with the environment variable `WAYLAND_DISPLAY=` to force RetroArch to run on XWayland.
9. RetroArch will launch in the expected orientation.
10. Possibly test that `vk_wayland` works in GNOME Shell (Wayland) and Sway for debug purposes.

### Bisect Results

I have not bisected the Git history yet, I am looking over previous commits to the Wayland Vulkan context to see if anything fishy pops up. It's possible this was always an issue and was never caught simply because it's so obscure.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: ad89b0c855

### Environment information

- OS: Arch Linux
- Compiler: GCC (12.2.0) 64-bit

**Comment by ColinKinloch** [comment]
Could you reproduce it with `WAYLAND_DEBUG=1` and upload the log as a file?
Something like this:
```
WAYLAND_DEBUG=1 ./retroarch 2>&1 | tee >(gzip --stdout > ./ralog.txt.gz)
```
and upload `ralog.txt.gz`

**Comment by luluco250** [comment]
Looks like some update to KDE fixed it, I tried replicating it again and it worked fine.

Gonna close it for now, thanks anyway!
