### ISSUE TITLE
Mac RetroArch is built with HAVE_BSV_MOVIE=0

### ISSUE THREAD

**Issue by JoeOsborn** [libretro/RetroArch#15012]
Since Windows and Linux builds seem to default to HAVE_BSV_MOVIE=1, so should Mac OS builds.  Is that something that needs to be changed in an xcodeproj file somewhere, or will a change to Makefile.apple do it?  I don't have a Mac to test changes on right now and I'm not sure how RA builds on Mac.

**Comment by LibretroAdmin** [comment]
This hopefully takes care of it -
https://github.com/libretro/RetroArch/commit/8c47aa41bd07e86bbc66909c2a45231c4f1c6707
