### ISSUE TITLE
(UWP) D3D12 Regression

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#15037]
## Description

PR https://github.com/libretro/RetroArch/pull/15025 broke D3D12 support in the UWP builds, when using this driver now, all content now just renders a black screen, although the menus still work fine. D3D11 is not affected by this issue on the other hand.

@sonninnos Any thoughts on what could have gone wrong?

### Expected behavior

To see some actual video.

### Actual behavior

Black screen.

### Steps to reproduce the bug

1. Boot up a game
2. Enjoy the void

### Bisect Results

PR https://github.com/libretro/RetroArch/pull/15025 is the culprit

### Environment information

- OS: Xbox Series X
- Compiler: Visual Studio 2022

**Comment by sonninnos** [comment]
Only one block comes to mind which did nothing on my end, and it had a comment about it "not making sense", so I removed it.
