### ISSUE TITLE
Windows- Retroarch lagging in fullscreen

### ISSUE THREAD

**Issue by CarrioTine** [libretro/RetroArch#1504]
I've done multiple tests and no matter what, retroarch lags when it's in full-screen, but not when it's in windowed mode. This is a big issue to me as I prefer to play games in full-screen in general. I was wondering if I could get assistance with this.

**Comment by twinaphex** [comment]
Are you using an Nvidia GPU? There have been other reports that seem to mesh with this.

**Comment by CarrioTine** [comment]
Yes, I am. Is there a solution to this? As I'm on a laptop I also have the
option to run it on a intel graphics chip, would that work?

**Comment by fr500** [comment]
what kind of GPU?, what's your hardware?

**Comment by twinaphex** [comment]
Can you try it out with the Intel GPU activated instead of the nvidia GPU? Just to be able to narrow down what the issue is further?

**Comment by CarrioTine** [comment]
Summary
Operating System
Windows 8.1 64-bit
CPU
Intel Core i3/i5/i7 4xxx @ 1.70GHz 49 °C
Haswell ULT 22nm Technology
RAM
8.00GB Dual-Channel DDR3 @ 798MHz (11-11-11-28)
Motherboard
ASUSTeK COMPUTER INC. X550LN (SOCKET 0) 50 °C
Graphics
Generic PnP Monitor (1920x1080@60Hz)
Intel HD Graphics Family (ASUStek Computer Inc)
2047MB NVIDIA GeForce 840M (ASUStek Computer Inc) 48 °C
Storage
931GB Seagate ST1000LM014-1EJ164 (SATA) 36 °C
Optical Drives
HL-DT-ST DVDRAM GUA0N
Audio
Realtek High Definition Audio
Operating System
Windows 8.1 64-bit
Computer type: Notebook
Installation Date: 12/7/2014 1:33:14 AM
Serial Number: 4J2QN-GR8H6-7K2J7-QVG82-9P9F3
Windows Security Center
User Account Control (UAC) Enabled
Notify level 2 - Default
Firewall Enabled
Windows Update
AutoUpdate Not configured
Windows Defender
Windows Defender Disabled
Antivirus
Windows Defender
Antivirus Disabled
Virus Signature Database Up to date
AVG AntiVirus Free Edition 2015
Antivirus Enabled
Virus Signature Database Up to date
.NET Frameworks installed
v4.5 Full
v4.5 Client
v3.5 SP1
v3.0 SP2
v2.0 SP2
Internet Explorer
Version 11.0.9600.17690
PowerShell
Version 4.0
Java
Java Runtime Environment
Path C:\Program Files (x86)\Java\jre1.8.0_25\bin\java.exe
Version 8.0
Update 25
Build 18
Environment Variables
USERPROFILE C:\Users\Carrio Tine
SystemRoot C:\Windows
User Variables
FR_CUSTOMDATA_PATH C:\Program Files
(x86)\Steam\steamapps\common\FaceRig\Mod\VP\PC_CustomData\
TEMP C:\Users\Carrio Tine\AppData\Local\Temp
TMP C:\Users\Carrio Tine\AppData\Local\Temp
Machine Variables
ADSK_3DSMAX_x64_2015 C:\Program Files\Autodesk\3ds Max 2015\
CM2015DIR C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\
ComSpec C:\Windows\system32\cmd.exe
FP_NO_HOST_CHECK NO
ILMDIR C:\Program Files (x86)\Common Files\Autodesk Shared\Materials\
NUMBER_OF_PROCESSORS 4
OS Windows_NT
Path C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\ProgramData\Oracle\Java\javapath
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files\Common Files\Autodesk Shared\
C:\Program Files (x86)\Autodesk\Backburner\
PATHEXT .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE AMD64
PROCESSOR_IDENTIFIER Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
PROCESSOR_LEVEL 6
PROCESSOR_REVISION 4501
PSModulePath C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
retroarch F:\Emu\RetroArch\retroarch.exe
TEMP C:\Windows\TEMP
TMP C:\Windows\TEMP
USERNAME SYSTEM
windir C:\Windows
Device Tree
ACPI x64-based PC
Microsoft ACPI-Compliant System
ACPI Fixed Feature Button
ACPI Lid
ACPI Sleep Button
ACPI Thermal Zone
Intel Core i5-4210U CPU @ 1.70GHz
Intel Core i5-4210U CPU @ 1.70GHz
Intel Core i5-4210U CPU @ 1.70GHz
Intel Core i5-4210U CPU @ 1.70GHz
Microsoft Windows Management Interface for ACPI
Motherboard resources
Unknown Device
PCI Express Root Complex
Intel Management Engine Interface
Microsoft AC Adapter
Microsoft ACPI-Compliant Control Method Battery
Microsoft Windows Management Interface for ACPI
Motherboard resources
Motherboard resources
Motherboard resources
PCI Data Acquisition and Signal Processing Controller
PCI Data Acquisition and Signal Processing Controller
PCI Express standard Root Port
PCI standard host CPU bridge
SM Bus Controller
System board
Unknown Device
Intel(R) HD Graphics Family
Generic PnP Monitor
Intel(R) USB 3.0 eXtensible Host Controller - 0100 (Microsoft)
USB Root Hub (xHCI)
USB Composite Device
USB Camera
USB Composite Device
USB Input Device
HID-compliant mouse
USB Input Device
HID Keyboard Device
HID-compliant consumer control device
HID-compliant system controller
HID-compliant vendor-defined device
HID-compliant vendor-defined device
HID-compliant vendor-defined device
Generic Bluetooth Adapter
Bluetooth Device (Personal Area Network)
Bluetooth Device (RFCOMM Protocol TDI)
Microsoft Bluetooth Enumerator
Microsoft Bluetooth LE Enumerator
High Definition Audio Controller
Realtek High Definition Audio
Microphone (Realtek High Definition Audio)
Speakers (Realtek High Definition Audio)
PCI Express standard Root Port
PCI Device
Realtek PCIe GBE Family Controller
PCI Express standard Root Port
Realtek 8821AE Wireless LAN 802.11ac PCI-E NIC
Microsoft Wi-Fi Direct Virtual Adapter
PCI Express standard Root Port
NVIDIA GeForce 840M
Intel(R) 8 Series USB Enhanced Host Controller #1 - 9C26
USB Root Hub
Generic USB Hub
USB Composite Device
USB Input Device (Logitech Download Assistant)
HID Keyboard Device
USB Input Device
HID-compliant consumer control device
HID-compliant mouse
HID-compliant system controller
HID-compliant vendor-defined device
USB Input Device
HID-compliant vendor-defined device
HID-compliant vendor-defined device
HID-compliant vendor-defined device
PCI standard ISA bridge
Direct memory access controller
High precision event timer
Intel 82802 Firmware Hub Device
Microsoft ACPI-Compliant Embedded Controller
Microsoft PS/2 Mouse
Motherboard resources
Motherboard resources
Motherboard resources
Motherboard resources
PC/AT Enhanced PS/2 Keyboard (101/102-Key)
Programmable interrupt controller
System CMOS/real time clock
System timer
Standard SATA AHCI Controller
HL-DT-ST DVDRAM GUA0N
ST1000LM014-1EJ164
ASUS Wireless Radio Control
HID-compliant wireless radio controls
CPU
Intel Core i3/i5/i7 4xxx
Cores 2
Threads 4
Name Intel Core i3/i5/i7 4xxx
Code Name Haswell ULT
Package Socket 1168 BGA
Technology 22nm
Specification Intel Core i5-4210U CPU @ 1.70GHz
Family 6
Extended Family 6
Model 5
Extended Model 45
Stepping 1
Revision C0
Instructions MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, Intel 64, NX,
VMX, AES, AVX, AVX2, FMA3
Virtualization Supported, Enabled
Hyperthreading Supported, Enabled
Fan Speed 2500 RPM
Bus Speed 99.8 MHz
Stock Core Speed 2400 MHz
Stock Bus Speed 100 MHz
Average Temperature 49 °C
Caches
L1 Data Cache Size 2 x 32 KBytes
L1 Instructions Cache Size 2 x 32 KBytes
L2 Unified Cache Size 2 x 256 KBytes
L3 Unified Cache Size 3072 KBytes
Cores
Core 0
Core Speed 798.1 MHz
Multiplier x 8.0
Bus Speed 99.8 MHz
Temperature 50 °C
Threads APIC ID: 0, 1
Core 1
Core Speed 798.1 MHz
Multiplier x 8.0
Bus Speed 99.8 MHz
Temperature 48 °C
Threads APIC ID: 2, 3
RAM
Memory slots
Total memory slots 4
Used memory slots 1
Free memory slots 3
Memory
Type DDR3
Size 8076 MBytes
Channels # Dual
DRAM Frequency 798.1 MHz
CAS# Latency (CL) 11 clocks
RAS# to CAS# Delay (tRCD) 11 clocks
RAS# Precharge (tRP) 11 clocks
Cycle Time (tRAS) 28 clocks
Command Rate (CR) 1T
Physical Memory
Memory Usage 43 %
Total Physical 7.89 GB
Available Physical 4.43 GB
Total Virtual 12 GB
Available Virtual 7.54 GB
SPD
Number Of SPD Modules 1
Slot #1
Type DDR3
Size 4096 MBytes
Manufacturer Samsung
Max Bandwidth PC3-12800 (800 MHz)
Part Number M471B5173QH0-YK0
Serial Number 1629AAED
Week/year 19 / 14
Timing table
JEDEC #1
Frequency 381.0 MHz
CAS# Latency 5.0
RAS# To CAS# 5
RAS# Precharge 5
tRAS 14
tRC 19
Voltage 1.350 V
JEDEC #2
Frequency 457.1 MHz
CAS# Latency 6.0
RAS# To CAS# 6
RAS# Precharge 6
tRAS 16
tRC 22
Voltage 1.350 V
JEDEC #3
Frequency 533.3 MHz
CAS# Latency 7.0
RAS# To CAS# 7
RAS# Precharge 7
tRAS 19
tRC 26
Voltage 1.350 V
JEDEC #4
Frequency 609.5 MHz
CAS# Latency 8.0
RAS# To CAS# 8
RAS# Precharge 8
tRAS 22
tRC 30
Voltage 1.350 V
JEDEC #5
Frequency 685.7 MHz
CAS# Latency 9.0
RAS# To CAS# 9
RAS# Precharge 9
tRAS 24
tRC 33
Voltage 1.350 V
JEDEC #6
Frequency 761.9 MHz
CAS# Latency 10.0
RAS# To CAS# 10
RAS# Precharge 10
tRAS 27
tRC 37
Voltage 1.350 V
JEDEC #7
Frequency 800.0 MHz
CAS# Latency 11.0
RAS# To CAS# 11
RAS# Precharge 11
tRAS 28
tRC 39
Voltage 1.350 V
Motherboard
Manufacturer ASUSTeK COMPUTER INC.
Model X550LN (SOCKET 0)
Version 1.0
Chipset Vendor Intel
Chipset Model Haswell-ULT
Chipset Revision 0B
Southbridge Vendor Intel
Southbridge Model ID9C43
Southbridge Revision 04
System Temperature 50 °C
BIOS
Brand American Megatrends Inc.
Version X550LN.301
Date 4/14/2014
PCI Data
Graphics
Monitor
Name Generic PnP Monitor on Intel HD Graphics Family
Current Resolution 1920x1080 pixels
Work Resolution 1920x1040 pixels
State Enabled, Primary
Monitor Width 1920
Monitor Height 1080
Monitor BPP 32 bits per pixel
Monitor Frequency 60 Hz
Device \\.\DISPLAY1\Monitor0
Intel HD Graphics Family
Manufacturer Intel
Model HD Graphics Family
Device ID 8086-0A16
Revision C
Subvendor ASUStek Computer Inc (1043)
Current Performance Level Level 0
Voltage 0.775 V
Driver version 10.18.10.3496
Count of performance levels : 1
Level 1 - "Perf Level 0"
GPU Clock 598 MHz
NVIDIA GeForce 840M
Manufacturer NVIDIA
Model GeForce 840M
Device ID 10DE-1341
Revision A3
Subvendor ASUStek Computer Inc (1043)
Current Performance Level Level 1
Current GPU Clock 405 MHz
Current Memory Clock 405 MHz
Voltage 0.775 V
Bus Interface PCI Express x4
Temperature 48 °C
Driver version 9.18.13.4752
BIOS Version 82.08.13.00.1e
Physical Memory 2047 MB
Virtual Memory 2048 MB
Count of performance levels : 3
Level 1 - "2D Desktop"
GPU Clock 405 MHz
Memory Clock 405 MHz
Level 2 - "Default"
GPU Clock 405 MHz
Memory Clock 800 MHz
Level 3 - "3D Applications"
GPU Clock 540 MHz
Memory Clock 900 MHz

Optical Drives
HL-DT-ST DVDRAM GUA0N
Media Type DVD Writer
Name HL-DT-ST DVDRAM GUA0N
Availability Running/Full Power
Capabilities Random Access, Supports Writing, Supports Removable Media
Read capabilities CD-R, CD-RW, CD-ROM, DVD-RAM, DVD-ROM, DVD-R, DVD-RW,
DVD+R, DVD+RW, DVD-R DL, DVD+R DL
Write capabilities CD-R, CD-RW, DVD-RAM, DVD-R, DVD-RW, DVD+R, DVD+RW,
DVD-R DL, DVD+R DL
Config Manager Error Code Device is working properly
Config Manager User Config FALSE
Drive D:
Media Loaded FALSE
SCSI Bus 1
SCSI Logical Unit 0
SCSI Port 0
SCSI Target Id 0
Status OK
Audio
Sound Cards
NVIDIA Virtual Audio Device (Wave Extensible) (WDM)
Realtek High Definition Audio
VB-Audio Virtual Cable
Playback Devices
CABLE Input (VB-Audio Virtual Cable)
Speakers (Realtek High Definition Audio) (default)
Recording Devices
Microphone (Realtek High Definition Audio) (default)
CABLE Output (VB-Audio Virtual Cable)

**Comment by CarrioTine** [comment]
Somehow it fixed itself. If it happens again I'll try it with the intel
chip.
