### ISSUE TITLE
Mesen Crashes on 1.15.0

### ISSUE THREAD

**Issue by Freakservo** [libretro/RetroArch#15076]
What the topic-title says.  Mesen just crashes now.  Any game.  Both header and headerless.

### Expected behavior

To work without incident, as it has with every prior RetroArch build.

### Actual behavior

Freezes on launch, shuts RetroArch down entirely.

### Steps to reproduce the bug

Just run a game.

### Bisect Results

As explained above, started with the release of 1.15.0

### Environment information

-Windows 11 used (Most-recent updates and drivers installed)

Note - Mesen-S not affected.

**Comment by gouchi** [comment]
It should be fixed on [latest commit](https://github.com/libretro/Mesen/pull/30).

Try to update the Mesen core.

**Comment by Freakservo** [comment]
I'm seeing no improvement.

Mesen updated, re-installed 1.15.0.  Even tried again with nightly build.

I admit I do not understand the explicit details of the 'Move_Console and_keyManager' dialogue.  If an unwarranted setting was altered somewhere when I updated RetroArch I'm oblivious to it.

**Comment by LibretroAdmin** [comment]
Reverted the PR, after that it worked. 

Will be resubmitting stables due to this last minute PR that unfortunately did not get tested on RetroArch beforehand by the PR author when it should have. Sorry about that.

**Comment by Freakservo** [comment]
No apologies necessary, sir.

I'm just relieved it wasn't the result of a non-default setting I may have changed at one point.
