### ISSUE TITLE
RetroArch v1.15.0" - video problem (Windows XP)

### ISSUE THREAD

**Issue by zibijani** [libretro/RetroArch#15080]
Up to version "v1.10.3" everything works ok, but from version "v1.11.0" to "v1.15.0"
the video does not work. I have tested all available video drivers for XP.

My system: XP-SP3
test soft: RetroArch-MSVC10-Win32 (XP 32 bits)
Graphics card: Ati Mobility Radeon X700

**Comment by vailkyte** [comment]
Tagging here as they're the same problem. And both tickets now fixed.
https://github.com/libretro/RetroArch/issues/14830
