### ISSUE TITLE
(Mac) v1.15 crash when launched

### ISSUE THREAD

**Issue by whiteblue3** [libretro/RetroArch#15085]
## Description
RetroArch v1.15 always crash when launched. v1.14 was working.
Both stable version of GL and Metal all same.

### Version/Commit
- RetroArch: 1.15

### Environment information
- OS: Mac OS X 10.15.7 Catalina (iMac Pro, Intel Xeon W)

**Comment by vus7294** [comment]
https://github.com/libretro/RetroArch/issues/15171#issue-1659383298

Same Problem as My Windows

**Comment by whiteblue3** [comment]
#15425
