### ISSUE TITLE
xmb: Jumping menu descriptions

### ISSUE THREAD

**Issue by Diskutant** [libretro/RetroArch#15084]
## Description

In the RetroArch Menus, in XMB interface, longer menu descriptions are scrolling upwards, but that scrolling is jumping weirdly, making it hard to read.
See attached Video

### Expected behavior

Text should just scroll smoothly

### Actual behavior

Text lines are jumping 

### Steps to reproduce the bug

1. Start RetroArch with XMB 
2. Select an option with longer text description for example Settings -> User Interface -> Menu Item Visibility -> Show 'Contentless Cores'

### Bisect Results

It happened in 1.14 and still happens in 1.15

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15 

### Environment information

- OS: macOS 13.2.1
- MacBook Air M1 (2020)

https://user-images.githubusercontent.com/898220/224543439-70a10aec-1d16-47c5-9a1f-8e1e901b51f2.mov

**Comment by sonninnos** [comment]
Not happening on Windows with any video driver.

**Comment by Metal-Snake** [comment]
still happens on 1.16.0 stable.
