### ISSUE TITLE
Crash when selecting Catalan (Valencian) locale

### ISSUE THREAD

**Issue by Woundorf** [libretro/RetroArch#15097]
## Description

RetroArch crashes immediately after launch if the Catalan (Valencian) locale is selected. It works immediately after the change but crashes on next launch.

The following messages are displayed in the terminal if launched from there:

> Fontconfig warning: ignoring ca_valencia: not a valid region tag
> Violació de segment (s'ha bolcat la memòria)

The second line means a segmentation fault.

The fontconfig warning is the clue. It does not recognize "ca_valencia". After inspecting [fontconfig source code](https://github.com/freedesktop/fontconfig/blob/master/src/fclang.c#L207) I think it should be "ca@valencia" or "ca_ES@valencia" (or maybe all in lower case). This matches with available locales in my system.

### Expected behavior

The program opens and the UI is displayed in Valencian.

### Actual behavior

The program crashes immediately.

### Steps to reproduce the bug

1. Change UI language to Catalan (Valencian) from UI or config file (user_language = "28").
2. Close RetroArch if it is open.
3. Launch RetroArch.

### Bisect Results

I have not done a bisect but from the fontconfig warning I am fairly convinced that the problem was introduced in pull request #14504.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.14.0

### Environment information

- OS: Fedora 37

**Comment by zoltanvb** [comment]
Does not happen on Ubuntu 22.04, I'll try to reproduce on Fedora.

**Comment by zoltanvb** [comment]
(It does happen, I just did not have fontconfig enabled.)

Setting it to ca@valencia works for the fontconfig part. There is another place where it is referred, can you let me know the value for your "LANG" environment variable?

**Comment by Woundorf** [comment]
My LANG is ca_AD.UTF-8.

**Comment by zoltanvb** [comment]
This should be fixed nowadays.
