### ISSUE TITLE
No access to any cores on Steam version (macOS)

### ISSUE THREAD

**Issue by huhhtm** [libretro/RetroArch#15091]
## Description

The summary of the problem can be found in my review on Steam:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/127781514/224790765-44c13176-0460-44ad-9a81-cf832f3d3c82.png">

### Expected behavior

The expected behaviour is for a downloaded core to, at least, show up in the 'load cores' section. Ideally, I should also be able to use said to core to run compatible ROMs with it.

### Actual behavior

The cores do not show up at all.

Example:
![image](https://user-images.githubusercontent.com/127781514/224791295-b468e710-24d4-4f76-a757-fc8ca37b2a69.png)
![image](https://user-images.githubusercontent.com/127781514/224791375-269aecbd-2a3b-412d-96a6-5486744c289e.png)
![image](https://user-images.githubusercontent.com/127781514/224791429-d9e4e152-03d3-45e5-ab81-8ec3b2772a7a.png)
Here bsnes is used, but no cores show up.

### Steps to reproduce the bug

1. Download & Install Retroarch (Steam)
2. Download any core using 'Manage Cores'
3. 'Installed successfully' pop-up message appears
4. Attempt to load the downloaded core
5. It does not appear (even after a restart)

### Version/Commit
**RetroArch:** Official 1.15.0 Release (Steam)

### Environment information
![image](https://user-images.githubusercontent.com/127781514/224792901-a5ba66c2-f6a4-4620-afac-c2813c9e377e.png)

**Comment by warmenhoven** [comment]
Should be fixed by #15158
