### ISSUE TITLE
Small issue with XMB new release 1.15 (windows)

### ISSUE THREAD

**Issue by Hari-82** [libretro/RetroArch#15090]
I found this small issue with the new release, I’m on Windows x64, XMB menu driver.

So, I try to explain: while navigating the menu, Icons enlarge when selected,if you are on “Settings”  the Icons with the cogwheels correctly enlarge.

However, after opening and then closing a content the enlarging animations stops and it remains “stuck” on the last Icon selected before launching a content,

I test this on my current set up and also on a fresh install. The only thing I changed in the fresh install was setting full-screen and, obviously, XMB as menu driver.

**Comment by hizzlekizzle** [comment]
Here's the forum thread with related screenshots and info: https://forums.libretro.com/t/small-issue-with-xmb-new-release-1-15-windows/40913
