### ISSUE TITLE
Reverb DSP crashing on Linux as of latest commit (a03587d)

### ISSUE THREAD

**Issue by milesrotaru** [libretro/RetroArch#15096]
## Description

As of the last change to reverb.c a few days ago, Reverb.dsp and ChipTuneEnhance.dsp which both depend on the former immediately crash RetroArch when activated.

Environment: SteamOS 3.4.6 on Steam Deck

Log: NA, the log doesn't show anything after the DSP is selected, crashes too early?

**Comment by LibretroAdmin** [comment]
We reverted it to the last known version before mudlord's changes, so it should be OK again? 

Are you 100% certain you are using a build from latest sources and that you have recompiled the audio filters again?

**Comment by milesrotaru** [comment]
I could actually be mistaken about the version. I've installed the Flatpak of RetroArch 1.15.0 and refreshed everything with the online updater, so whatever build is currently in the wild is the one causing me problems.
