### ISSUE TITLE
ld: undefined reference to `state_manager_frame_is_reversed`

### ISSUE THREAD

**Issue by theflyingape** [libretro/RetroArch#15100]
Starting with `1.15.0` release and fresh git clone, many **task_save.c** undefined references during link, starting function `content_deserialize_state`.

Using Pi 400 Ubuntu Bullseye:
```
CFLAGS='-O2 -march=armv8-a -mcpu=cortex-a72 -mtune=cortex-a72' \
CXXFLAGS="${CFLAGS}" \
./configure --prefix="${HOME}/.local" \
	--disable-floathard --disable-ffmpeg --disable-neon --disable-rewind \
	--disable-caca --disable-cheats --disable-langextra \
	--disable-parport --disable-winrawinput \
	--disable-dispmanx --disable-opengl1 --disable-opengl --disable-sdl \
	--disable-vg --disable-videocore --disable-wayland --disable-xvideo \
	--disable-jack --disable-mpv --disable-oss --disable-tinyalsa \
	--enable-cheevos --enable-command --enable-lua --enable-networking \
	--enable-materialui --enable-ozone --enable-qt --enable-rgui --enable-xmb \
	--enable-egl --enable-kms --enable-opengl_core --enable-x11 --enable-xshm \
	--enable-opengles --enable-opengles3 --enable-opengles3_1 --enable-opengles3_2 \
	--enable-sdl2 --enable-vulkan --enable-vulkan_display \
	--enable-alsa --enable-bluetooth --enable-crtswitchres --enable-pulse \
	--enable-dbus --enable-hid --enable-libusb --enable-udev \
	--enable-networkgamepad --enable-ssl --enable-systemd --enable-wifi \
	--enable-thread_storage --enable-threads --enable-zlib \
|| exit
make -j4 && make install
```

**Comment by LibretroAdmin** [comment]
Give us a full log output of all the undefined references.

**Comment by LibretroAdmin** [comment]
@JoeOsborn tagging you here.

**Comment by JoeOsborn** [comment]
My bad! I caught some of these issues thanks to CI but I’ll take another pass this morning.

**Comment by LibretroAdmin** [comment]
@theflyingape Pushed this -
https://github.com/libretro/RetroArch/commit/2902d11b1aeed8e9863f5e82ae011c4b8570da65

Check if this works out for you.

@JoeOsborn So basically make certain from this point on to respect the ```HAVE_REWIND``` compile-time define. There are targets where we want to build without rewind support, but that should then not result in broken compilation for other subsystems. I.e. the 'replay' code should not have a 'hard' dependency on the 'rewinding' code if that makes sense. Both have to be able to work independently of one another.

**Comment by JoeOsborn** [comment]
Oh thanks for fixing it, I’ll be sure to test different combinations next time.

**Comment by theflyingape** [comment]
I can confirm the patched code builds (and runs) -- thanks for the quick turnaround!
