### ISSUE TITLE
[BUG] Cannot save game/core overrides

### ISSUE THREAD

**Issue by crashGG** [libretro/RetroArch#15107]
Platform / OS : win10 x64

Github hash: newest

Hardware: intel i3 + hd 5300 + dx11

Issue:

Cannot save game/core overrides in full screen, but if swithes to window,it works fine.

**Comment by crashGG** [comment]
This issue occurs in the latest 1.15, when use 1.14 everything works fine.

**Comment by sonninnos** [comment]
Works here in regardless of window state.

**Comment by crashGG** [comment]
fullscreen:
<img width="960" alt="2023-03-19_104434" src="https://user-images.githubusercontent.com/80488411/226161213-40bb132b-495f-4614-bd53-3f3dfa1ac5a0.png">

swith to window:
<img width="450" alt="2023-03-19_104533" src="https://user-images.githubusercontent.com/80488411/226161237-17fcb6c7-4a4e-4988-bc34-15119241cb0e.png">

Already restored RA to default settings.This issue is not only me, but also reproduced on multiple computers of my friends.we are using the Chinese version of the win10 x64. I don't know if it has anything to do with this.

**Comment by sonninnos** [comment]
Well what is saved to the file when it saves? "Nothing to save" means the override config would be identical to the main config, therefore it won't save.

**Comment by crashGG** [comment]
Yes,it works as intended.The override logic of 1.15 has changed slightly compared to 1.14.Thank you for your answer.
