### ISSUE TITLE
Second screen severe performance issue (Windows 8.1/GL)

### ISSUE THREAD

**Issue by PJL101** [libretro/RetroArch#1510]
Hi,

As soon as I put Retroarch onto my second screen in full screen, the interface slows to a crawl (30+ seconds to register a button press).

Switching to D3D does fix the issue as does running on the main screen in GL. Tried with latest Nightly and Stable and problem still happens. Happy to provide whatever needed to help fix.

System specs:

3.2 GHz Intel Core i5
24 GB 1600 MHz DDR3
NVIDIA GeForce GTX 680MX 2048 MB
Windows 8.1

**Comment by fr500** [comment]
We have found out lots of GL issues with nvidia lately, it seems threaded optimization can't be disabled on anything newer than winxp.

That said, we haven't found that kind of slowdown. Are you using rewind or hard gpu sync?

**Comment by Monroe88** [comment]
I've always had poor vsync performance on the secondary screen. Setting the second screen as primary in Windows is the best solution, because it seems Windows or Nvidia doesn't handle the secondary screen well for OpenGL.

**Comment by PJL101** [comment]
@Monroe88 Thanks, your suggestion worked, as does switching to d3d.

@fr500 rewind and hard gpu sync are off.

**Comment by aliaspider** [comment]
did you also take a look at the single/multi display performance mode option in the nvidia control panel ?

**Comment by PJL101** [comment]
@aliaspider I'll have a look and get back to you. That's a good suggestion I hadn't thought of to be honest.

**Comment by fr500** [comment]
Please test on the current code, and reopen if the issue persists
