### ISSUE TITLE
Wayland splashscreen alternatives?

### ISSUE THREAD

**Issue by vanfanel** [libretro/RetroArch#15112]
@ColinKinloch I saw you added the wayland splash screen that gets called here: https://github.com/libretro/RetroArch/blob/master/gfx/common/wayland_common.c#L686

That splash screen appears on the center of the screen, then re-appears on the upper-left corner, and then RetroArch starts. Not very aesthetically pleasant process :)

I have been looking at the SDL2 code in https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvideo.c and https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylandvulkan.c, and I see no splash screen for display auto-assign, and no SDL2 program seems to need it.

I do my own RetroArch builds with the splash screen call disabled, and it works perfectly well. 

So, would it be possible to look at what SDL2 does and do the same, instead of using the hacky splash-screen solution? What do you think?

**Comment by ColinKinloch** [comment]
It is to allow for setting which monitor to use for fullscreen.
If we maintain a connection to the wayland compositor and reuse the `wl_surface` (window) we could avoid the window showing up on fullscreen transition.
Also maybe it can be skipped when it's not going to be fullscreen?

There's more info here: https://github.com/libretro/RetroArch/issues/14408

**Comment by vanfanel** [comment]
@ColinKinloch I had forgotten about https://github.com/libretro/RetroArch/issues/14408
I will close this one and we can continue the discussion there, as there's a lot more info in that thread. Is that OK?
