### ISSUE TITLE
Video file audio becomes gradually out of synch when using the recording feature

### ISSUE THREAD

**Issue by xmat123x** [libretro/RetroArch#1511]
It happens with a couple of cores I tried such as desmume, MAME and mupen64plus.
Recording with bsnes, vba-m and ffmpeg works well though so it's probably a core issue.

Video reference 
https://www.youtube.com/watch?v=0TcRLL4fz38

Everything seems to work well at the beginning but skipping to the 5 minute mark and there's a noticeable delay.

**Comment by fr500** [comment]
Yes, most likely the cores aren't reporting the correct framerate

**Comment by fr500** [comment]
It's a core issue not a frontend issue, closing this for now, feel free to add any information you might find in the future.
