### ISSUE TITLE
Core selection by Nintendo Switch RetroArch front-end nro building

### ISSUE THREAD

**Issue by MegaBunLi** [libretro/RetroArch#15142]
# Description

In Nintendo Switch Development Guide, it refers "Each NRO of RetroArch has one and only one core, and each core is a standalone homebrew by itself. That means that building multiple cores means building RetroArch multiple times, once for each core."

- Does that mean even the front-end nro in the path “/switch/retroarch_switch.nro” has a built-in core?
- Then which core does this nro select to build?
- And if I changed the retroarch sourcecode to build a front-end nro, should I build all the cores I need with the same modified sourcecode? Since each core also has a built-in retroarch too...

**Comment by hizzlekizzle** [comment]
I believe it has a "dummy" core, yes.

Yes, if you have modified RetroArch, you will need to statically link each core against the modified RetroArch.

**Comment by MegaBunLi** [comment]
Really thx! I just tried to compile the retroarch nro file, but the compilation terminated and showed that:
```
switch_font.c
In file included from gfx/drivers_font/../common/switch_common.h:8,
                 from gfx/drivers_font/switch_font.c:30:
c:\users\floyd\retroarch\gfx\common\egl_common.h:23:10: fatal error: EGL/egl.h: No such file or dire
ctory
   23 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [/opt/devkitpro/devkitA64/base_rules:19: gfx/drivers_font/switch_font.o] Error 1
```
It seems the program couldn't locate the EGL/egl.h, how could I fix this?

**Comment by hizzlekizzle** [comment]
Are you following the Switch compile guide here? https://docs.libretro.com/development/retroarch/compilation/switch-libnx/

**Comment by MegaBunLi** [comment]
> Are you following the Switch compile guide here? https://docs.libretro.com/development/retroarch/compilation/switch-libnx/
Step by step, and I succeed to compile a sample nro supported by the devkitPro, the environment should be complete.
- Tried to reinstall all version of angle project to get the <EGL/egl.h>, but it seems the program just inquires the header files under retroarch directory
- Tried to simply copy all the header files to inside directory, not worked: didn't terminate but produce nothing
- Tried to edit <Makefile.libnx> from  <HAVE_EGL = 1>  to  <HAVE_EGL =0>, not worked also
Since I am really fresh to compilation and the official development guide is too short, can't figure it out what's going on now...

**Comment by MegaBunLi** [comment]
Solved by reinstalling all the environment! Thx dude!

**Comment by MegaBunLi** [comment]
> I believe it has a "dummy" core, yes.
Yes, if you have modified RetroArch, you will need to statically link each core against the modified RetroArch.

I reinstalled all the environment and problem solved! But when I tried to generate an nro file, error occured pointing I didn't put a core file `libretro_libnx.a` in the directory:
```
linking retroarch_switch.elf
c:/users/floyd/app/devkitpro/devkita64/bin/../lib/gcc/aarch64-none-elf/12.2.0/../../../../aarch64-no
ne-elf/bin/ld.exe: cannot find libretro_libnx.a: No such file or directory
collect2.exe: error: ld returned 1 exit status
make: *** [/opt/devkitpro/libnx/switch_rules:80: retroarch_switch.elf] Error 1
```
Then I put a renamed core file under the directory，it worked. Hence how could I get the neat version of retroarch nro with "No Core" label on the left lower corner?

**Comment by wings110** [comment]
@MegaBunLi how to build the front-end nro in the path “/switch/retroarch_switch.nro” ?
