### ISSUE TITLE
Can't build Flycast and PPSSPP core `libretro_libnx.a` file for Nintendo Switch RetroArch

### ISSUE THREAD

**Issue by MegaBunLi** [libretro/RetroArch#15148]
Tried all methods and counldn't find why, for other cores I can successfully output `<corename>_libretro_libnx.a`, but for these two cores I have no idea.

Noticed these two cores has stopped updates for a while for libnx version, I changed the fetch address to the original github address `https://github.com/libretro/flycast` and `https://github.com/m4xw/ppsspp`, but it didn't work.

Did someone know where could I find the `[4c293f3]` version `flycast_libretro_libnx.a` and `[8e24692]` version `ppsspp_libretro_libnx.a` file? I just wanna modify the retroarch without changing cores, but I must get the `<corename>_libretro_libnx.a` first to compile an nro file! 

Really thx!

**Comment by gouchi** [comment]
Please don't "crosspost" and this issue should not be on RetroArch issue tracker as it is not related to RetroArch.

But better in the [libretro-super repository](https://github.com/libretro/libretro-super/issues/1718) where you posted it also.

I am not familiar with Libretro core build for Switch but they are  still building 
https://buildbot.libretro.com/nightly/nintendo/switch/libnx/latest/

So please close this issue.

Thank you.

**Comment by MegaBunLi** [comment]
Thx for your kindness! I'm not quite familiar with the libretro repositories, really sorry if I made a mistake bothering you! The buildbot doesn't provide the file I need by the way. I will close the issue now, hope there would be some update under libretro-super!
