### ISSUE TITLE
NP2Kai core missing on Apple silicon (self-build OK)

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#15156]
## Description

NP2Kai core missing on Apple silicon

### Expected behaviour

- NP2Kai present in online updater core downloader

### Actual behaviour

- NP2Kai missing

### Steps to reproduce the bug

1. use an Apple silicon Mac
1. Run RetroArch > Online Updater > Core Downloader
1. NP2Kai?

### Bisect Results

- it's possible for me to self-build the core

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15.0

### Environment information

- OS: macOS
- MacBook Pro Apple silicon

**Comment by gingerbeardman** [comment]
I just built the core myself on arm64

[np2kai_libretro.dylib](https://github.com/libretro/RetroArch/files/11162955/np2kai_libretro.dylib.zip) arm64 [ZIP]

https://github.com/AZO234/NP2kai/issues/164

**Comment by warmenhoven** [comment]
https://github.com/libretro/NP2kai/pull/52
