### ISSUE TITLE
Suggestion: add terminal command option to select video filter for Retroarch on Linux

### ISSUE THREAD

**Issue by XAUTHORITY** [libretro/RetroArch#15150]
## Description

Retroarch on Linux manual does not explain how to select a video filter when opening a game from terminal. Grateful we have a native build at all and I hope this suggestion to select a video filter from terminal command is some kind of help to future builds. Video filters can be applied from within the gui but not from a terminal command.

### Expected behavior

I had expected way more terminal options for how full-featured the Linux gui retroarch is, such as the ability to select a video filter from terminal command.

### Actual behavior

Not many terminal options on Linux retroarch though the program's gui has way more.

### Steps to reproduce

1. `man -k retroarch`
2. `man retroarch` from Linux terminal
3. (search) `/filter`  

### Bisect Results

Noticed no option for opening retroarch with a desired filter as I began adding more options to my game launching script. I can just use sed to edit the config for my desired video filter though it will definitely bloat up the script a lot as I continue to add more to it. I would also like to note that the Linux man page is quite brief for a man page and how many types of features can be found in the gui and config.

### Version/Commit

RetroArch: Frontend for libretro -- v1.15.0 -- 6616b807ed --

### Environment information

OS: Manjaro Linux x86_64
Kernel: 5.15.104-2-MANJARO
Compiler: GCC (12.2.1) 64-bit Built: Mar 16 2023

**Comment by bazuzu-hype** [comment]
> We typically put our efforts into shaders rather than video filters, and we have the ability to load shaders from CLI.

I see, thank you for the tip, I now see the CLI shader option with `retroarch --help | grep shader` - the man page makes no mention of the word shader. Noting another issue that when inside the GUI app shaders are not being detected even though I have the directory pointing to the shaders I have installed from my OS repository `libretro-shaders-slang 1180-1` - the GUI shows `No Items` while the directory is full of shader files named `<shader-name.slangp>`.  Furthermore CLI does open my game but unfortunately using the CLI `--set-shader` parameter also loads no shader at all. Here is the `--verbose` result of my CLI command:

`retroarch -v -f -L /usr/lib/libretro/snes9x_libretro.so './FF6 (Mato) T-Edition A6 3.05.sfc' --set-shader=/usr/share/librietro/shaders/shaders_slang/ntsc/ntsc-256px-composite.slangp --record /home/user/_my-streams/ --recordconfig /home/user/.config/retroarch/twitch.cfg`

I should mention that I am using the retroarch package from Manjaro's pacman repository and I am going to try other repositories out in the meantime, what is the most recommended package you can think of?

**Comment by hizzlekizzle** [comment]
The deb packages from our PPAs are known-good (I use them daily). The AppImage should also be reliable.

The slang shaders are compatible with every video driver except for the default/legacy-compatibility "gl" driver, which uses our glsl shaders instead (we're thinking of changing the default drivers for the desktop platforms partially for this reason). If you switch to the 'glcore' or 'vulkan' drivers, the slang shaders should populate and load as expected.

**Comment by XAUTHORITY** [comment]
That change to glcore got those shaders working with Manjaro package thank you very much! 

Yeah the Manjaro repository only had slang shaders that apparently belongs with libretro, hmm, I will take time and see if I can locate some glsl shaders very helpful I will look it up have a great evening, comment closed!

**Comment by hizzlekizzle** [comment]
Nice, I'm glad that got you fixed up.

Don't worry, none of the drivers are going away, and if we make any change, it would be to make glcore the default instead of the current "gl".

You can find the glsl shaders at https://github.com/libretro/glsl-shaders

**Comment by XAUTHORITY** [comment]
Thanks! The glsl shaders look the same pathologically as slang do you know if they look any different? Can't hurt to git clone and gather my own opinion.  yeah not only did the glcore fix me up but I even managed to manipulate slang shaders to resemble my old composite CRT this is quite wonderful!

I think, I am not certain but before I put a dedicated graphics card on my board I think I could not use the glcore, I could be wrong. If that is the case then some users wont be able to see the GUI at all until manually editing the config or unless you `set a failsafe in place to automatically change the config to gl if glcore happens to crash.` I say do that and `set glcore as the GNU Linux default`. That combined with `adding some GUI informational notes when browsing the video drivers as to what shader types each driver can run` would smooth things out well for users I think. Well no huge deal obviously as I was previously content using filters though if all of the above was to be completed I think you would be in a fine position to remove filters at some point.

**Comment by hizzlekizzle** [comment]
The glsl shaders should look identical (ideally), but the shaders are much harder to program, so a lot of the more advanced shader effects (like the Mega Bezel shaders) are not possible there.

We'll keep the filters around for all of the platforms that lack a programmable pipeline altogether (like many of our older console targets, dingoo-based hardware, etc.).

Glcore requires OpenGL v3.3+ support, which was apparently released back in 2010. The regular "gl" driver is OpenGL v2, which is from 2004. So, I think requiring a GPU that's 13 yrs old or less seems reasonable vs the current situation, which is: making everyone use suboptimal shaders by default to avoid complicating things for people using 19-yr old GPUs.

**Comment by XAUTHORITY** [comment]
nice, good call on the filters, anytime something affects many people it deserves just as much care to keep those people content with their program. 

I would be interested to help test any gl upgrade if you guys have it. I see opengl.org has a 4.6 feedback thread though for reference my `glxinfo | grep "OpenGL version"` reports version 4.3 though I did just have a rolling release update with mesa and vulkan packages and I'm not entirely sure what package opengl itself would come with, probably video drivers and that looked like a video driver update.
