### ISSUE TITLE
[Bug] Favorites label display mode reverting to 0

### ISSUE THREAD

**Issue by Hotair10** [libretro/RetroArch#15151]
## Description

If you edit the `content_favorites.lpl` file to filter the displayed labels, it works great, exactly as you would expect it to in any other playlist. However, if you add another game to your favorites, `label_display_mode` immediately reverts to `0`, causing there to no longer be a filter. Completely reproducible.

### Expected behavior

The `label_display_mode` should stay at what it is set to.

### Actual behavior

The `label_display_mode` reverts back to `0` every time.

### Steps to reproduce the bug

1. Edit `content_favorites.lpl`'s `label_display_mode` value to the preferred filter. In my case I use `1`.
2. Navigate to your favorites within RetroArch and note that the filter is successfully applied.
3. Add a new game to your favorites within the application.
4. Notice the designated filter is no longer in effect, and `content_favorites.lpl`'s `label_display_mode` value is reset back to `0`.

### Additional Information

I use the `xmb` menu driver.

### Version/Commit

Running latest stable version provided by Steam
Build Date: March 17, 2023
Git Version: 6616b807ed

### Environment information

- OS: Windows 10

**Comment by sonninnos** [comment]
I'm not able to reproduce. The label display mode stays as it was after adding or removing.
