### ISSUE TITLE
[Bug] Can't load a second N64 game after closing the first one without restarting RetroArch

### ISSUE THREAD

**Issue by Agusum** [libretro/RetroArch#15165]
## Description
After closing content in a N64 game, I'm unable to open a second N64 game. This doesn't happen with any other system, only with N64.

I'm using macOS 13.3.

### Expected behavior
Ability to open as many N64 games in a row as I want.

### Actual behavior
"Failed to load content" error after trying to open a second N64 game

### Steps to reproduce the bug

1. Open N64 game
2. Close content
3. Try opening a second N64 game (it can be the same as the first time)

A "Failed to load content" error will appear. I need to quit RetroArch in order to be able to open another N64 game.

The issue is also described in [this video](https://youtu.be/NuXMf-8bmNA?t=460) (minute 7:40)

### Bisect Results

I believe this wasn't happening in RetroArch 1.14

### Version/Commit
<img width="948" alt="image" src="https://user-images.githubusercontent.com/4369698/230559930-3078f08b-fa1a-4ede-8067-d5891f56dad1.png">

### Environment information

- OS: macOS 13.3

**Comment by retropieuser** [comment]
Same for me. Using a MacBook pro M1 with Mac OS 13.3

**Comment by retropieuser** [comment]
I downloaded the 08.05.2023 nightly of Metal and this problem seems to be fixed. Can open and load second or third n64 game with no crash or issues

**Comment by Slarky** [comment]
I still get an "Application Not Responding" when closing a N64 game.
Using Metal Nightly from Jun 21 2023; Ventura 13.4.

**Comment by sonninnos** [comment]
Pretty sure this is a core issue and not frontend.

**Comment by Agusum** [comment]
The issue is now fixed for me in RetroArch 1.16.
