### ISSUE TITLE
[Bounty Feature Request] Fix audio crackling during fast forward

### ISSUE THREAD

**Issue by hilltop804** [libretro/RetroArch#15160]
## Request Outline
When using fast forward in RA, the audio becomes a crackly mess regardless of speed or hardware. I'm requesting a fix that would at least allow games to be played between 1-2x speed on modest hardware (Steam Deck) without crackling audio. This is possible on other standalone emulators, so I think it should be possible within RA.

## Guidelines
- This should not introduce a significant amount of lag or frame skip
- If the solution limits maximum fast forward speed, it should include a settings toggle (e.g. Fast Forward Audio Sync On/Off). Some users may not care about the audio and just want maximum speed.

**Comment by hilltop804** [comment]
https://app.bountysource.com/issues/118858006-bounty-feature-request-fix-audio-crackling-during-fast-forward

**Comment by felipetavares** [comment]
@hilltop804 can you give me a concrete example of what you are trying to play?

**Comment by hizzlekizzle** [comment]
a lot of people run pokemon games at 2x+ speed because it's just so slow, in general.

**Comment by hilltop804** [comment]
@felipetavares - Mostly retro RPGs: Golden Sun on GBA, Pokémon on GBA, Chrono Trigger on SNES, Shining Force II on Genesis.

**Comment by felipetavares** [comment]
@hilltop804 are you able to test the fix?

**Comment by felipetavares** [comment]
@hilltop804 There's one uninitialized variable in my current patch, the crashes might be related. Do you know if it happens the first time you try enabling fast-forward in the run or can you get it to work a few times before the crash?

**Comment by felipetavares** [comment]
@hilltop804 Added another small patch to my PR, can you check if it makes any difference?

**Comment by hilltop804** [comment]
@felipetavares I did some more testing with the updated PR and haven't encountered any additional bugs. I think this might be it!

**Comment by hilltop804** [comment]
> I experience heavy crackling while using fast forward in every just about every core on Android (Fold4). Is this related?

Are you using the setting added in the related PR? Without that, the audio is basically guaranteed to be a mess when using FF. Also, just as a heads-up, the stable release hasn't been updated with this patch yet. You have to install the nightly version to get it.
