### ISSUE TITLE
Retroarch after 1.15.0 Fast Crash

### ISSUE THREAD

**Issue by vus7294** [libretro/RetroArch#15171]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

[Clean Install](https://github.com/libretro/RetroArch/files/11182529/clean.install.txt)
[Current CFG](https://github.com/libretro/RetroArch/files/11182528/log.txt)

Current CFG is my Custom CFG, Clean Install is After Install, Nothing Touched.
1.14.0 before Update, I Played with No Problem.

[Description of the bug]

Fast Crash

[What you expected to happen]

Normally Turned on Retroarch

[What is actually happening]

Execute and after 3sec, Crashed

1. [First step]
2. [Second step]
3. [and so on...]

1. Updated 1.15.0
2. Turn on Retroarch
3. Fast Crash
4. It happened at Clean install, Same Result

[Try to bisect and tell us when this started happening]

i7 2600K + GTX1050Ti + 16GB DDR3
You can find this information under Information/System Information

- RetroArch: [version/commit]

1.15.0

- OS: Windows 10

**Comment by litaniast** [comment]
That behavior is when connect the xinput gamepad in Windows system. occurs on both Windows 10/11.
When I disconnect xinput gamepad (for me, PDP wired controller), 1.15 runs and when I connect while running RetroArch, it immediately shutdown.

Same in latest nightly.

**Comment by litaniast** [comment]
It works with disable input auto detect.

**Comment by litaniast** [comment]
It's related for Korean language pack. when I enabled auto detect input with English language, It works.

**Comment by litaniast** [comment]
This issue is solved in latest nightly due to fix of translation string.
