### ISSUE TITLE
MelonDS: BIOS files corrupts save data

### ISSUE THREAD

**Issue by 03bgood** [libretro/RetroArch#15180]
⁴Okay, so in order to get Castlevania: Order of Ecellsia to work, I need the DS BIOS file or else the game gets stuck on a screen with a bat flying over the castle in an endless loop and the music glitches out. However when adding the files to the "systems" folder (Arm7, Arm9, and Firmware.bin), it corrupts the save data to Castlevania: Dawn of Sorrow. How the hell do I fix this? Is there a way to get past this issue? Why is the save data not working when I add the DS BIOS files? It just says the save data is corrupt when I boot up Cv:DoS. Removing the BIOS files seems to restore my save and it works fine, but whenever I add the BIOS files, it just corrupts the save data.

**Comment by odditude42** [comment]
This isn't a bug; the DoS saves were written incorrectly when you were using the built-in HLE BIOS instead of the real thing, further demonstrating how the HLE BIOS behaves inaccurately in some ways.
