### ISSUE TITLE
Web player has broken Patreon banner

### ISSUE THREAD

**Issue by andreas-jonsson** [libretro/RetroArch#15185]
## Description

The web players Patreon banner is broken. The image link is incorrect.

### Expected behavior

The banner should show some picture or logo.

### Actual behavior

Shows a distracting broken image on the bottom of the window. It is not a major thing, but it looks bad and it is an easy fix. There will likely not be any users going through a link like that, preventing contributions to the project.

![image](https://user-images.githubusercontent.com/4725590/231756630-5f9f4591-d0bf-4ec3-9bcb-47e7a9887869.png)

### Steps to reproduce the bug

Visit: https://web.libretro.com/ 

### Version/Commit

Public web version

**Comment by LibretroAdmin** [comment]
Just decided to remove it instead.
