### ISSUE TITLE
dutch translation

### ISSUE THREAD

**Issue by bobrosspainting** [libretro/RetroArch#15209]
Hello

I want to help translate to Dutch language.
I'm not a developer, don't know any tools or compilers.
I just can translate from English to Dutch.

Am I in the position to translate in this way?
If yes, please explain the steps I need to do!

Bob Ross
The joy of painting

**Comment by gouchi** [comment]
First of all, as written in the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md) 

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

So it would have been better to post on [our forum](https://forums.libretro.com/) or check our [documentation](https://docs.libretro.com) first.

You can check our documentation about helping for the translation :

https://docs.libretro.com/development/retroarch/new-translations-crowdin/

Please close this issue if it is fixed.

Thank you.

**Comment by bobrosspainting** [comment]
DONT UNDERSTAND ANYTHING OF THIS SHIT

**Comment by bobrosspainting** [comment]
Thanks! I created an account to help translate!

**Comment by bobrosspainting** [comment]
Can I ask when a translation is actually moved from Crowdin to RetroArch next version?
Do I have to make an issue here when the translation is finished or are partially finished translations automatically added to RetroArch for each new version that is released?

thx
Bob

**Comment by gouchi** [comment]
Hi,

The translation is updated everyday, you can check the [history](https://github.com/libretro/RetroArch/commits/master) with the entry `Fetch translations from Crowdin`.

If you have more questions, you can ask them on [Discord](https://discord.gg/2E8pNrCR)  in `#retroarch-translations` channel.

[Source](https://docs.libretro.com/development/retroarch/new-translations-crowdin/#fnref:2)

Thank you.

**Comment by bobrosspainting** [comment]
A last question here, then i go to discord for more questions :)

On Crowdin there is written "approved", see screenshot. What does this mean?

![afbeelding](https://user-images.githubusercontent.com/130948185/233685026-4e39691f-12dd-46e8-a45a-4eb595200e50.png)

**Comment by zoltanvb** [comment]
There is a possibility for proofreaders to mark translations as approved. It can help the process when there are multiple translators working on the same language. But it is not mandatory, daily update will fetch all current translations for RetroArch and cores, including not approved ones.

**Comment by bobrosspainting** [comment]
Final question: I found some already translated strings but very badly translated (1 word is just used wrong).
How to indicate I want to change that word in an already translated string on Crowdin and how to change it?
