### ISSUE TITLE
button sounds

### ISSUE THREAD

**Issue by bobrosspainting** [libretro/RetroArch#15208]
Hi

On android the buttons A, B, ... Give sounds when pressed.
Is there a way to disable those sounds?

**Comment by gouchi** [comment]
First of all, as written in the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md) 

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

So it would have been better to post on [our forum](https://forums.libretro.com/) or check our [documentation](https://docs.libretro.com) first.

Anyway, check Settings tab > Audio > Menu Sounds.

Please close this issue if it is fixed.

Thank you.

**Comment by bobrosspainting** [comment]
DOESNT WORK
STUPID SHIT
