### ISSUE TITLE
(XMB) Background Opacity and Menu Color Theme setting is broken if Menu Shader Pipeline is turned off.

### ISSUE THREAD

**Issue by SapphireDrew** [libretro/RetroArch#15206]
## Description

When using the XMB menu, the Menu Color Theme setting doesn't work properly if the Menu Shader Pipeline is turned off. At `1.00` Background Opacity, the default background doesn't change color at all _(I'm assuming this is expected given the behavior of past versions)_, while reducing the opacity to `0.00` allowed the color themes to show vividly. After upgrading to 1.15.0, this no longer works, as setting the Background Opacity to `0.00` causes the background to become completely black regardless of the selected color theme, thus acting more like a "background brightness" setting, with inbetween settings like `0.50` resulting in a very dull, washed out version of the selected color theme.

### Expected behavior

Color Themes should display properly when the Menu Shader Pipeline is disabled and the Background Opacity is reduced.

### Actual behavior

The Background Opacity setting now acts as a brightness setting instead, preventing the color themes from displaying properly at any opacity.

### Steps to reproduce the bug

1. Set Menu / Menu Driver to XMB
2. Navigate to `Settings > User Interface > Appearance`
3. Set `Menu Shader Pipeline` to `Off`
4. Cycle through the Menu Color Themes and observe how washed out they are.
5. Set `Background Opacity` to `0.00`
6. Observe total darkness instead of pure color with no background.

### Bisect Results

~~The last unaffected build I used before upgrading to 1.15.0 was 1.10.3 (*102abb0*). I apologize in advance knowing that large of a version gap probably doesn't help much.~~

I performed a slightly more thorough bisect using the buildbot stable builds archive.

Last unaffected stable build was 1.13.0 (*ce9051f*)

The first stable build to present the issue was 1.14.0 (*e3c92b0*)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15.0 (*1581ece*)

### Environment information

- OS: Windows 10 Home (22H2)
- Compiler: N/A

**Comment by sonninnos** [comment]
I can't reproduce, or don't understand how or why should it work otherwise. Pipeline off and opacity at 0 shows the raw core output image as background. Color theme affects the pipeline, so no pipeline, no theme, and background opacity applies to the background image.

**Comment by sonninnos** [comment]
This is no longer the case, since shader pipeline is now separate.
