### ISSUE TITLE
Core path not stored

### ISSUE THREAD

**Issue by mase76** [libretro/RetroArch#15215]
Hi,
when I change the core path in the settings, it is not stored in the config and resetted to default with the next application start.

**Comment by gouchi** [comment]
Hi,

Please try provide some [logs](https://docs.libretro.com/guides/generating-retroarch-logs/) otherwise it will be difficult to help and verify if it is a bug or not.

Thank you.

**Comment by LibretroAdmin** [comment]
Please resubmit this issue when it's clearer what you're actually asking about or talking about.
