### ISSUE TITLE
N64 Mupen64Plus-Next core on M1 with 2x upscaling become slow until restart

### ISSUE THREAD

**Issue by erikmartinessanches** [libretro/RetroArch#15213]
## Description
N64 games upscaled 2x become slow after approximately 20 minutes. After restarting RetroArch, the game is back to running smoothly for a few minutes. See time and temp measurement in comment below.

### Version/Commit
- RetroArch: [version/commit] 1.15.0
- Mupen64Plus-Next (2.5-Vulkan 4353b0a).
- ParaLLEI-RDP plugin

### Environment information

- OS: Ventura 13.2

**Comment by hizzlekizzle** [comment]
Could this be related to thermal throttling?

**Comment by erikmartinessanches** [comment]
Some temperature measurements:
Time 0 minutes: when starting RetroArch before lag, CPU temp 62 C.
Time +20 minutes: RetroArch lags, CPU temp 73 C.
Time +1 minute: immediately after restarting RA, _no lag_: CPU temp 70 C.
Time +15 minutes:  RetroArch lags, CPU temp 75 C.

**Comment by retropieuser** [comment]
I've found this as well on ParaLLEI-RDP video plugin for MacBook air M1

**Comment by retropieuser** [comment]
I've found with the nightly dated 08.05.2023 this issue doesn't happen. I left games a few games turned on with 2x and 4x and the slowdown didn't appear.

However, I am finding a separate issue with upscaling using ParaLLEI-RDP, for certain games you get this shading effect on the textures, here's Mario 64 for example:-

<img width="1440" alt="Screenshot 2023-05-08 at 12 22 11" src="https://user-images.githubusercontent.com/73472027/236811377-d2e6b829-ef52-4e46-9065-e379b39d3914.png">

<img width="1440" alt="Screenshot 2023-05-08 at 12 22 19" src="https://user-images.githubusercontent.com/73472027/236811482-5925c0e0-bab8-4553-b4c4-75ca372ab565.png">

**Comment by erikmartinessanches** [comment]
> I've found with the nightly dated 08.05.2023 this issue doesn't happen. I left games a few games turned on with 2x and 4x and the slowdown didn't appear.
> 
> However, I am finding a separate issue with upscaling using ParaLLEI-RDP, for certain games you get this shading effect on the textures, here's Mario 64 for example:-
> 
> <img alt="Screenshot 2023-05-08 at 12 22 11" width="1440" src="https://user-images.githubusercontent.com/73472027/236811377-d2e6b829-ef52-4e46-9065-e379b39d3914.png">
> 
> <img alt="Screenshot 2023-05-08 at 12 22 19" width="1440" src="https://user-images.githubusercontent.com/73472027/236811482-5925c0e0-bab8-4553-b4c4-75ca372ab565.png">

Can confirm on the build from 20203-03-17 (March 17th 2023).

**Comment by retropieuser** [comment]
> > I've found with the nightly dated 08.05.2023 this issue doesn't happen. I left games a few games turned on with 2x and 4x and the slowdown didn't appear.
> > However, I am finding a separate issue with upscaling using ParaLLEI-RDP, for certain games you get this shading effect on the textures, here's Mario 64 for example:-
> > <img alt="Screenshot 2023-05-08 at 12 22 11" width="1440" src="https://user-images.githubusercontent.com/73472027/236811377-d2e6b829-ef52-4e46-9065-e379b39d3914.png">
> > <img alt="Screenshot 2023-05-08 at 12 22 19" width="1440" src="https://user-images.githubusercontent.com/73472027/236811482-5925c0e0-bab8-4553-b4c4-75ca372ab565.png">
> 
> Seems like I'm unable to find nightly builds for Mac arm, as the download page only offers downloads for mac intel. Can confirm the graphics issue you mentioned in the comment above. I also noticed slowing down, after approx 20 mins, on the non-nightly build from 2023-03-17 (March 17th 2023) on mac metal arm.

The nightly for Mac is the universal build which my understanding is it supports Intel and Silicon (arm) based Macs. I can't see the 08.05.2023 build now https://buildbot.libretro.com/nightly/apple/osx/universal/ it goes about 10 days back.

Anyway someone has fixed something, I updated to the most recent build and the texture issues are gone, the slowdown is gone (on Mario 64 anyway, I'll try some other games too)

<img width="1552" alt="Screenshot 2023-06-18 at 17 27 06" src="https://github.com/libretro/RetroArch/assets/73472027/3d505f81-d4d2-434c-926b-7cfd7d1728db">
<img width="1552" alt="Screenshot 2023-06-18 at 17 27 26" src="https://github.com/libretro/RetroArch/assets/73472027/240c692b-51e2-4e26-9201-0d5fb4f88ec3">

**Comment by erikmartinessanches** [comment]
> > > I've found with the nightly dated 08.05.2023 this issue doesn't happen. I left games a few games turned on with 2x and 4x and the slowdown didn't appear.
> > > However, I am finding a separate issue with upscaling using ParaLLEI-RDP, for certain games you get this shading effect on the textures, here's Mario 64 for example:-
> > > <img alt="Screenshot 2023-05-08 at 12 22 11" width="1440" src="https://user-images.githubusercontent.com/73472027/236811377-d2e6b829-ef52-4e46-9065-e379b39d3914.png">
> > > <img alt="Screenshot 2023-05-08 at 12 22 19" width="1440" src="https://user-images.githubusercontent.com/73472027/236811482-5925c0e0-bab8-4553-b4c4-75ca372ab565.png">
> > 
> > 
> > Seems like I'm unable to find nightly builds for Mac arm, as the download page only offers downloads for mac intel. Can confirm the graphics issue you mentioned in the comment above. I also noticed slowing down, after approx 20 mins, on the non-nightly build from 2023-03-17 (March 17th 2023) on mac metal arm.
> 
> The nightly for Mac is the universal build which my understanding is it supports Intel and Silicon (arm) based Macs. I can't see the 08.05.2023 build now https://buildbot.libretro.com/nightly/apple/osx/universal/ it goes about 10 days back.
> 
> Anyway someone has fixed something, I updated to the most recent build and the texture issues are gone, the slowdown is gone (on Mario 64 anyway, I'll try some other games too)
> 
> <img alt="Screenshot 2023-06-18 at 17 27 06" width="1552" src="https://user-images.githubusercontent.com/73472027/246677512-3d505f81-d4d2-434c-926b-7cfd7d1728db.png"> <img alt="Screenshot 2023-06-18 at 17 27 26" width="1552" src="https://user-images.githubusercontent.com/73472027/246677518-240c692b-51e2-4e26-9201-0d5fb4f88ec3.png">

Thanks for the link to nightly build, I had trouble finding it. The slowness issue seems resolved.
