### ISSUE TITLE
Broken Assets. And "Online Updater -> Update Assets" not available

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#15210]
### Ubuntu 22.04 main repo (retroarch 1.7.3)
![image](https://user-images.githubusercontent.com/6416073/233334634-f55dcc25-8664-487d-ac8f-08aeb7554a79.png)

![image](https://user-images.githubusercontent.com/6416073/233334758-6eed1f2f-8251-4692-808a-7118a898694c.png)

```
sudo apt-get install retroarch

$ sudo apt-cache show retroarch-assets
Package: retroarch-assets
Architecture: all
Version: 1.4.1+git20170209+dfsg1-1
Priority: optional
Section: universe/otherosfs
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 44074
Depends: fonts-roboto | fonts-roboto-hinted, fonts-mplus
Filename: pool/main/r/retroarch-assets/retroarch-assets_1.4.1+git20170209+dfsg1-1_all.deb
SHA512: 2c8daaa04a563c668c3bc1e2384e1e97e3db67ec2ff1c151ad2846f2a86a8e31afa8a22f74ff2607110893de8b7bad99c5beab7145b87ade20fe4b0b5f0e6b9f
Homepage: http://www.libretro.com
Size: 28925940
SHA256: 9e0ad7f6c80947f4378c55ed5f4b0d4a28b6446d76a84e12ae2eee8709f89e63
SHA1: 62f70061a5300abdeb426021c90e78bf86ff49a7
MD5sum: 3382a94c71e564870ee7c074f88d3ef9
Description: RetroArch assets for XMB, GLUI and Zarch
 This package installs RetroArch assets for XMB, GLUI and Zarch menu drivers.
Description-md5: 302d4dcf7f3e672e6e5376eedd5650ac

$ sudo apt-cache show retroarch
Package: retroarch
Architecture: amd64
Version: 1.7.3+dfsg1-1.1build1
Priority: optional
Section: universe/otherosfs
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Games Team <pkg-games-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 4823
Depends: fonts-dejavu-core, libretro-core-info, retroarch-assets, libasound2 (>= 1.0.18), libavcodec58 (>= 7:4.2), libavformat58 (>= 7:4.2), libavutil56 (>= 7:4.0), libc6 (>= 2.29), libdrm2 (>= 2.4.17), libegl1, libfreetype6 (>= 2.2.1), libgbm1 (>= 8.1~0), libgcc-s1 (>= 3.0), libgl1, libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125, libminiupnpc17 (>= 1.9.20140610), libopenal1 (>= 1.14), libpulse0 (>= 0.99.1), libqt5core5a (>= 5.15.1), libqt5gui5 (>= 5.2.0) | libqt5gui5-gles (>= 5.2.0), libqt5widgets5 (>= 5.11.0~rc1), libsdl2-2.0-0 (>= 2.0.12+dfsg1), libstdc++6 (>= 4.1.1), libswresample3 (>= 7:4.0), libswscale5 (>= 7:4.0), libudev1 (>= 183), libusb-1.0-0 (>= 2:1.0.16), libv4l-0 (>= 0.5.0), libwayland-client0 (>= 1.9.91), libwayland-cursor0 (>= 1.0.2), libwayland-egl1 (>= 1.15.0), libx11-6, libxext6, libxinerama1, libxkbcommon0 (>= 0.5.0), libxv1, libxxf86vm1, zlib1g (>= 1:1.1.4)
Filename: pool/universe/r/retroarch/retroarch_1.7.3+dfsg1-1.1build1_amd64.deb
Size: 1382468
MD5sum: 669ac775f88b0dccea174583d7337f6d
SHA1: 36f5c63a82ed2c6e94c7de4c93833930bf55235e
SHA256: 508e54aba4376451b9a42f3ce64f04146a3335bb124bc17e9358a18b40333ded
SHA512: ceeebd8092ad3b9a8b33139afd651b5ccb7188390b0fdf4520b4f57b89630f658b8c4989a2c3f7f6127a7421da869e86b29f28bce06ec60759f5f6e2be15592c
Homepage: https://www.libretro.com/
Description-en: Simple frontend for the libretro library
 RetroArch is an open source, multi-platform frontend for the libretro API.
 It can be used as a modular multi emulator system, game engine, media player
 and 3D technical demonstration. These features are available through
 libretro cores.
 .
 It provides three built-in GUI: RGUI, XMB and GLUI.
Description-md5: 3dde528dcf9a3ec987b90319552fca63
```

Open retroarch, and open the Online Updater, it has these entries:
* Thumbnails Updater
* Content Downloader
* Update Joypad Profiles
* Update Cheats
* Update Databases
* Update Overlays
* Update GLSL Shaders

Close retroarch

```
$ sudo apt-get remove --purge retroarch
```

### Ubuntu 22.04 stable PPA repo (retroarch 1.15.0)
![image](https://user-images.githubusercontent.com/6416073/233345240-cb0c6701-4347-4b9e-a22e-4760fb0b206b.png)
![image](https://user-images.githubusercontent.com/6416073/233345851-b5ebaabf-cde6-4a72-87be-9782a9db7abd.png)
![image](https://user-images.githubusercontent.com/6416073/233346576-6e32c9a4-02df-42ef-bfd5-f01866d6d10d.png)

```
$ sudo add-apt-repository ppa:libretro/stable && sudo apt-get update && sudo apt-get install retroarch # from https://www.retroarch.com/index.php?page=linux-instructions
$ sudo apt-cache show retroarch
Package: retroarch
Priority: optional
Section: games
Installed-Size: 19931
Maintainer: Libretro Team <libretro@gmail.com>
Architecture: amd64
Version: 1.15.0-r202303110511+666fbdcb38-167~ubuntu22.04.1
Provides: retroarch-dbg
Depends: libx11-dev, libxrandr-dev, fonts-dejavu-core, libqt5waylandclient5, libvulkan1, libasound2 (>= 1.0.18), libass9 (>= 1:0.13.6), libavcodec58 (>= 7:4.4), libavformat58 (>= 7:4.4), libavutil56 (>= 7:4.4), libc6 (>= 2.34), libcaca0 (>= 0.99.beta17-1), libdbus-1-3 (>= 1.9.14), libdrm2 (>= 2.4.62), libegl1, libflac8 (>= 1.3.0), libfontconfig1 (>= 2.12.6), libfreetype6 (>= 2.2.1), libgbm1 (>= 8.1~0), libgcc-s1 (>= 3.3.1), libgl1, libjack-jackd2-0 (>= 1.9.10+20150825) | libjack-0.125, libopenal1 (>= 1.14), libpulse0 (>= 0.99.1), libqt5core5a (>= 5.15.1), libqt5gui5 (>= 5.2.0) | libqt5gui5-gles (>= 5.2.0), libqt5network5 (>= 5.14.1), libqt5widgets5 (>= 5.15.1), libroar2 (>= 1.0~beta12), libsdl2-2.0-0 (>= 2.0.12), libsixel1 (>= 1.10.3), libstdc++6 (>= 11), libswresample3 (>= 7:4.4), libswscale5 (>= 7:4.4), libudev1 (>= 183), libv4l-0 (>= 0.5.0), libwayland-client0 (>= 1.20.0), libwayland-cursor0 (>= 1.12), libwayland-egl1 (>= 1.15.0), libx11-6, libx11-xcb1 (>= 2:1.7.5), libxext6, libxinerama1 (>= 2:1.1.4), libxkbcommon0 (>= 0.5.0), libxrandr2 (>= 2:1.2.99.2), libxv1, libxxf86vm1, zlib1g (>= 1:1.1.4)
Filename: pool/main/r/retroarch/retroarch_1.15.0-r202303110511+666fbdcb38-167~ubuntu22.04.1_amd64.deb
Size: 4478254
MD5sum: 8732f6fff4c1278d063a058cb91e218b
SHA1: 8ff0a9f1f6a712b59086843b7362451e196bc9dd
SHA256: 8d367a7d47d11fa26fe9cd21a106b849b5f55f76dcd7dc77e6154f46b2d3b765
Description-en: Simple frontend for the libretro library
 RetroArch is an open source, multi-platform frontend for the libretro API. It
 can be used as a modular multi-emulator system, game engine, media player and
 3-D technical demonstration. These features are available through libretro
 cores.
 .
 It provides four built-in graphical user interface flavors: RGUI, XMB, Ozone
 and GLUI.
Description-md5: e613142faf77960dc78429e0f68a6ea3
```

Open retroarch, and open the Online Updater (and Update Assets to make it easier to read if you want), it has these entries:
* Core Downloader
* Update Installed Cores [-- A core must be installed for this entry to appear]
* Core System Files Downloader
* Content Downloader
* On-Demand Thumbnail Downloads
* Playlist Thumbnail Updater
* Update Assets
* Update Controller Profiles
* Update Cheats
* Update Databases
* Update Overlays
* Update GLSL Shaders

### Expected behavior
retroarch-1.7.3 is missing:
* Core Downloader
* Core System Files Downloader
* On-Demand Thumbnail Downloads
* Playlist Thumbnail Updater
* Update Core Info Files
* Update Assets

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Ubuntu 22.04 (Jammy), upgraded

**Comment by davidhedlund** [comment]
* Is it now mandatory to install cores from the package manager in Ubuntu (for example `sudo apt-get install libretro-bsnes-mercury-accuracy`)?

*How do I update the assets?

**Comment by hizzlekizzle** [comment]
Those entries should be there in the PPA builds (which I use and maintain). I suspect the distro package has set those values to hidden in the config file and those values are being re-used by the PPA build once you installed it. That is, if you `rm -rf ~/.config/retroarch/retroarch.cfg`, I suspect they will show up for you in the PPA build.

If you use the distro package for RetroArch, you're expected to use the distro packages for cores, etc. The distro package sets default locations pointing to root-owned locations, which breaks the online services (such as: updating assets). Once you clear out the distro package's config, I think you'll be good to download them via the online updater.

**Comment by davidhedlund** [comment]
> Those entries should be there in the PPA builds (which I use and maintain). I suspect the distro package has set those visibility values to hidden in the config file and those values are being re-used by the PPA build once you installed it. That is, if you `rm -rf ~/.config/retroarch/retroarch.cfg`, I suspect they will show up for you in the PPA build.

Thank you very much for quick, and helpful answers. I'm sorry, but I was wrong that these entries did not occur in the PPA build (just tried a virtual machined), so I have removed that issue from the top post. I'm sure that the menu was corrupt for me because the old ~/.config/retroarch/retroarch.cfg from the main repo package version (1.7.3) was not removed, and re-used when I installed your PPA build. Furthermore, I will find out if it's possible to show "Update Assets" by configure 1.7.3.

> If you use the distro package for RetroArch, you're expected to use the distro packages for cores, etc. The distro package sets default locations pointing to root-owned locations, which breaks the online services (such as: updating assets). Once you clear out the distro package's config, I think you'll be good to download them via the online updater.

That is what I suspected. I'll check it out, thanks.


Also, thank you for your work on the PPA build, it has helped me to use RA when I failed with the main repo package!

**Comment by davidhedlund** [comment]
@hizzlekizzle Regarding the main repo package (1.7.3): I've spent a lot of time finding a setting that possibly hide the "Update Assets" without any luck.

Also, I cannot find anything in retroarch.cfg that is related to that:
```
$ cat ~/.config/retroarch/retroarch.cfg | grep assets
assets_directory = "~/.config/retroarch/assets"
bundle_assets_dst_path = ""
bundle_assets_dst_path_subdir = ""
bundle_assets_extract_enable = "false"
bundle_assets_extract_last_version = "0"
bundle_assets_extract_version_current = "0"
bundle_assets_src_path = ""
core_assets_directory = "~/0-personal/rofs/home/blues/.config/retroarch/downloads"
core_updater_buildbot_assets_url = "http://buildbot.libretro.com/assets/"
```

**Comment by hizzlekizzle** [comment]
Glad I could help :)

Those menu entries might be disabled at compile time if they're not showing up even with a clean config. You could check the patches being applied downstream and see if that's included.

**Comment by davidhedlund** [comment]
> Glad I could help :)
> 
> Those menu entries might be disabled at compile time if they're not showing up even with a clean config. You could check the patches being applied downstream and see if that's included.

That's very complicated for me. If you have time, could you please ask someone to have a look at this issue?

**Comment by davidhedlund** [comment]
https://github.com/libretro/retroarch-assets/issues/446

**Comment by davidhedlund** [comment]
> Glad I could help :)
> 
> Those menu entries might be disabled at compile time if they're not showing up even with a clean config. You could check the patches being applied downstream and see if that's included.

* Can you please ask someone to have a look at why the "Update Assets" entry does not exist in the "Online Updater"?



Related: I just submitted issues for the broken asset package:
* https://github.com/libretro/retroarch-assets/issues/446
* https://github.com/libretro/retroarch-assets/issues/447

**Comment by RobLoach** [comment]
> Can you please ask someone to have a look at why the "Update Assets" entry does not exist in the "Online Updater"?

On installers that use package-manager managed assets, the Online Updater is disabled. You'll want `retroarch-assets` , and reset the .cfg file.

As an alternative, I'd recommend trying out the Snap or the Flatpak installs.
