### ISSUE TITLE
Protocol error message

### ISSUE THREAD

**Issue by hokata** [libretro/RetroArch#1521]
Just a point not very important because everything is working well but I've got this message each time I launch retroarch (tested with nestopia, gambatte, bsnes_mercury, genesis_plus_gx and even with the --menu cli option) :

Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1449275654 (0x56623106)
 at -e line 15

I got a retroarch uptodate an hour ago.

**Comment by twinaphex** [comment]
At the very least specify which video context driver you're trying to run, this is totally insufficient information to provide on its own.

**Comment by hokata** [comment]
Sure, so i'm on debian wheezy + backports and I tried with gl and sdl2 video_driver.
By the way, everything is working as expected.

When I used --verbose, the order is : 

RetroArch: gl_set_nonblock_state: [GL]: VSync => on
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1483866712 (0x58720258)
 at -e line 15
RetroArch: x11_query_screens: [X11]: Xinerama version: 1.1.

If you want some more info, don't hesitate.

**Comment by fr500** [comment]
Please test on the current code, and reopen if the issue persists

**Comment by modeler** [comment]
I'm getting exactly the same issue on Arch Linux now, using either the stable 1.2.2 release or the current git version:

[code]$ retroarch
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 411517808 (0x18874370)
 at -e line 15.[/code]

Strangely, it causes Chromium to hang, i.e. no tabs can be opened or closed, no input into the window at all. When I close RetroArch it's okay again.

This only happens when I'm logged in as myself; if I run RetroArch as root it's okay. DBUS issue?

**Comment by hokata** [comment]
It's seems resolved on my side (long time without tested)

I got new problem (nestopia core too quick) but may try to do some more test and post a new issue.

**Comment by modeler** [comment]
This issue is only showing in GNOME. Prior to this appearing I ran a system update and got the following when running RetroArch:

retroarch: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory

So I rebuilt from source (stable branch) and RetroArch would run again and this came up (but it does run):

Can't locate Net/DBus.pm in @INC (you may need to install the Net::DBus module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at -e line 5.
BEGIN failed--compilation aborted at -e line 5.

I installed perl-net-dbus to provide this file, then I got:

Can't locate X11/Protocol.pm in @INC (you may need to install the X11::Protocol module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at -e line 6.
BEGIN failed--compilation aborted at -e line 6.

I installed perl-x11-protocol, then I get the message I reported earlier:

Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 622221350 (0x25165826)
 at -e line 15.

Hope this helps narrow it down a little. Please let me know if there's anything I can do.

**Comment by gizmo98** [comment]
I get exactly the same error message if i try to run reicast-libretro from within ubuntu unity. Every other core is running fine.

**Comment by Kivutar** [comment]
Possibly the same bug or related https://github.com/libretro/RetroArch/issues/1926

**Comment by harkor** [comment]
Same problem on Fedora 23

**Comment by barraponto** [comment]
I still see this issue with 1.7.5

**Comment by orbea** [comment]
Can you please make a new issue report and follow the template to the best of your ability? Thanks!

**Comment by julianxhokaxhiu** [comment]
Same under Gnome 3.32 on Arch Linux, using Vulkan driver with Intel/nVidia combination laptop.

```
➜ yay -Qs vulkan-intel
local/vulkan-intel 18.3.4-1
    Intel's Vulkan mesa driver

➜ yay -Qs nvidia      
local/lib32-libvdpau 1.2-1
    Nvidia VDPAU library
local/libvdpau 1.2-1
    Nvidia VDPAU library
local/nvidia 418.43-7
    NVIDIA drivers for linux
local/nvidia-utils 418.43-2
    NVIDIA drivers utilities
local/opencl-nvidia 418.43-2
    OpenCL implemention for NVIDIA

➜ retroarch  
[INFO] [recording] twitch streaming key empty
[INFO] RetroArch 1.7.6 (Git 9750719074)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Mar 18 2019
[INFO] Version: 1.7.6
[INFO] Git: 9750719074
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/home/julian/.config/retroarch/savefile/.srm".
[INFO] Redirecting savestate to "/home/julian/.config/retroarch/savestate/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ fullscreen
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] Vulkan dynamic library loaded.
[INFO] [Vulkan]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: Window manager is GNOME Shell.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [GLX]: Using Xinerama on screen #0.
[INFO] [GLX]: X = 0, Y = 0, W = 1920, H = 1080.
[INFO] [GLX]: Using windowed fullscreen.
[INFO] [Vulkan]: Using GPU: GeForce MX130
[INFO] [Vulkan]: Queue family 0 supports 16 sub-queues.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Swapchain supports present mode: 3.
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 1920 x 1080.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1920x1080
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]:   Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [udev]: Keyboard #0 (/dev/input/event2).
[INFO] [udev]: Mouse #0 (/dev/input/event9).
[INFO] [udev]: Mouse #1 (/dev/input/mouse0).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x558dd5ab9500
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/julian/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/julian/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/home/julian/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/julian/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/julian/.config/retroarch/content_image_history.lpl].
[INFO] [Vulkan]: VSync => on
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]:   Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [PulseAudio]: Unpausing.
[INFO] [Vulkan]: VSync => on
[INFO] [PulseAudio]: Pausing.
**Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 15.**
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Vulkan]: Do not need to re-create swapchain.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
[INFO] [slang]: Building pass #0 (N/A)
[INFO] [slang]: Reflection
[INFO] [slang]:   Textures:
[INFO] [slang]:      Source (#0)
[INFO] [slang]:
[INFO] [slang]:   Uniforms (Vertex: yes, Fragment: no):
[INFO] [slang]:   Push Constants (Vertex: no, Fragment: no):
[INFO] [slang]:      MVP (Offset: 0)
[INFO] [slang]:
[INFO] [slang]:   Parameters:
[INFO] [Vulkan filter chain]: Not using frame history.
[INFO] [Vulkan filter chain]: Not using framebuffer feedback.
[INFO] [PulseAudio]: Unpausing.
[INFO] [Vulkan]: VSync => on
[INFO] [PulseAudio]: Pausing.
[INFO] [PulseAudio]: Unpausing.
[INFO] [PulseAudio]: Unpausing.
[INFO] [Config]: Saved new config to "/home/julian/.config/retroarch/retroarch.cfg".
[INFO] Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
```

**Comment by RealOrko** [comment]
I am also seeing this on Fedora 31 after compiling RetroArch from master. It only happens when I try to launch PSX games using beetle.

**Comment by RulerOf** [comment]
I ran into this problem. It wasn't enough to turn off Vulkan—I had to uninstall the Intel Vulkan driver to resolve the issue. This was on an i5 3470.

I decided that I'll just buy an nVidia card and use Vulkan with that if I need Vulkan for some reason.

**Comment by kwyxz** [comment]
Interestingly enough, I just encountered this very bug after building RetroArch on a fresh new install of Solaris 11.4, which now ships with GNOME3 as the default desktop environment.

I also encountered the following:

> Can't locate Net/DBus.pm in @inc (you may need to install the Net::DBus module) (@inc contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at -e line 5.
> BEGIN failed--compilation aborted at -e line 5.

and

> Can't locate X11/Protocol.pm in @inc (you may need to install the X11::Protocol module) (@inc contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl .) at -e line 6.
> BEGIN failed--compilation aborted at -e line 6.

which are missing from Solaris 11.4 and had to be installed from CPAN. After these were installed and RetroArch rebuilt, I got this:

> Protocol error: bad 3 (Window); Sequence Number 5
> Opcode (20, 0) = GetProperty
> Bad resource 622221350 (0x25165826)
> at -e line 15.

Now trying to install another desktop environment to see if I can still reproduce the issue.

**Comment by twinaphex** [comment]
I've narrowed this down to xdg_screensaver_inhibit being the culprit. I have no idea how to fix it yet though.

**Comment by cklinkbeil** [comment]
Has anyone got a fix for this? I am running into it on Ubuntu as well. I tried changing all sorts of video/display settings in retroarch and it still does not fix anything.

**Comment by sonninnos** [comment]
The output here on Ubuntu was 
```
Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 16.
```

And indeed `suspend_screensaver_enable = "false"` stopped it.
