### ISSUE TITLE
tvOS unable to launch games or set cores

### ISSUE THREAD

**Issue by AnthonySibl** [libretro/RetroArch#15234]
## Description

Go to launch a game, doesn't matter which core is trying to be used, it will fail to open the core.

### Expected behavior

Should be able to run a core/run a game by using a core

### Actual behavior

Core refuses to open/Unable to open core when loading content

### Steps to reproduce the bug

1. Compile cores
2. Place in appropriate folder
3. Compile RetroArch in Xcode
4. Upload content using webserver
5. Go to run content/Try loading content - Core fails to load

### Bisect Results

Problem started after commit [11a7cc9](https://github.com/libretro/RetroArch/commit/11a7cc9d23ce4962a4ee3a5773b8a6aab48b8492) or PR #15197.

There is another commit that changed the project file [295e5f0](https://github.com/libretro/RetroArch/commit/295e5f06823d48e4e393228b93b33af4faec582d) or PR #15224.

Was able to fix issue by reverting both commits.

Everything up to date or commit [c400fa7](https://github.com/libretro/RetroArch/commit/c400fa761c80ede03494445d5ca8fe0d214896fa) did not fix this issue but compiling without the 2 commits from above allows RetroArch to work as intended.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.15.0]

### Environment information

- OS: tvOS 16.4.1
- Compiler: Xcode 14.3

**Comment by warmenhoven** [comment]
Sorry. #15238.

**Comment by AnthonySibl** [comment]
All good, it happens.

**Comment by AnthonySibl** [comment]
> Sorry. #15238.

All good, it happens
