### ISSUE TITLE
[Android] Link failed because of missing fragment shader

### ISSUE THREAD

**Issue by micechal** [libretro/RetroArch#1523]
I'm having such issue when trying to run the mupen64plus core (and most likely other "3D" cores) on one of my phones, namely Jiayu S3.
You can see the verbose log here:
http://pastebin.ca/2961661

The issue occurs when loading a ROM and not a single frame is drawn before it gets back to the Java menu.

**Comment by micechal** [comment]
Standalone Mupen64Plus for android works alright, and so does the DeSmuME core in RetroArch (albeit slow), which potentially makes this a mupen64plus-libretro issue rather than a RetroArch one. I yet have to try some other cores, such as ppsspp.

**Comment by twinaphex** [comment]
This is not really a RetroArch problem but a Mupen64 libretro core issue.

Can you try this again on your phone? A lot of changes were made since March 20 to Glide64 and other plugins.

**Comment by micechal** [comment]
I just tried it on the 28.05 nightly with the latest mupen64plus-libretro and it works perfectly fine. I guess I can now close the issue.
