### ISSUE TITLE
"Delete ... Remap" annoying behaviour

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [libretro/RetroArch#15245]
## Description

![Tue May  2 00:52:35 -04 2023](https://user-images.githubusercontent.com/11010067/235582039-afaffaec-c70e-4277-8fe7-e6096e5bffd8.png)

Pressing "Delete Core/Game/Directory Remap" not only deletes the remap, but returns all inputs of the core to default as well. 

My experience: I was configuring core remaps one by one, only to realize at the end of the process this was happening. A lot of remaps were saved, then deleted, then saved again, thinking I'd only made a small edit and without realizing that on the first delete action all of the inputs had in fact returned to default. It's especially hard to notice it since for a lot of inputs you have to scroll down to see what they're mapped to.

There's currently no way to further edit a core remap from RetroArch after it being saved without resetting all inputs to default and starting again. I suggest having the `set all input remapping options to default values` part of the action be a separate entry on the menu.

**Comment by sonninnos** [comment]
They are saved automatically by default if the remap exists, so no deleting and saving is necessary. There is a separate option which will not save without manually pressing the appearing "update" item.

**Comment by 2V3EvG4LMJFdRe** [comment]
The issue really comes down to, how can one edit a remap after having saved it? Naturally, one would think deleting the remap deletes the remap file, while keeping the remap loaded up on the ra frontend until the program is closed. At least that's hot it seemed it should behave to me. This way you could delete a remap, make a quick edit, and save it again.

**Comment by sonninnos** [comment]
Like I said, just edit as usual and it will save automatically by default. And sure, deleting really should not reset the mapping, since there is a separate item for reset.
