### ISSUE TITLE
Netplay crash Retroarch when auto savestate is enabled

### ISSUE THREAD

**Issue by schmurtzm** [libretro/RetroArch#15248]
## Description

Running a game and then starting a Netplay session often crash  or freeze Retroarch if auto savestate is enabled.

Running RA, starting netplay first AND THEN launching a game works better but it's not the most common way : often players are loading their game from a list and then start their Netplay session.

This behavior is similar on linux ARM and Windows x86.

### Expected behavior

Whatever the save state settings Retroarch should not crash when starting a Netplay session after the game is launched.

### Actual behavior

**Depending your RA configuration you can expect different behavior when launching a Netplay host session :** 

always working : 
```savestate_auto_save = "false"```

Working (sometime): 
```
savestate_auto_save = "true"
savestate_file_compression = "true"
savestate_thumbnail_enable = "false"
```

Freeze :

```
savestate_auto_save = "true"
savestate_file_compression = "false"
savestate_thumbnail_enable = "true" 
```

Freeze :
```
savestate_auto_save = "true"
savestate_file_compression = "false"
savestate_thumbnail_enable = "false"
```

crash : 

```
savestate_auto_save = "true"
savestate_file_compression = "true"
savestate_thumbnail_enable = "true"
```

Edit: 
Interesting fact : with same settings (all at "true"), it's not crashing if you run the Netplay host from command line, for example : 
`retroarch -H -v -L /cores/picodrive_libretro.so "$1"`
But if you stop and restart the Netplay host session then it crash again.

### Traces
Traces from WinDGB and Time Travel Debugging (TTD.exe) : 
https://we.tl/t-gmULG5l0iq

### Steps to reproduce the bug

1. choose a configuration with auto save states enabled
2. launch a game
3. start a netplay session

### Version/Commit
- RA v1.15.0

### RetroArch: [version/commit]
- RA v1.15.0 (4d8db0b)

### Environment information

- OS: Linux arm (Miyoo Mini handheld) & Windows X86

**Comment by Johnnylokz** [comment]
I just installed the latest beta update which now has a hotspot feature. I went ahead and disabled autosave function on both devices & the netplay feature will now connect both devices together but it does not recognize a second player during gameplay. I am playing "streets of rage 2" on genesis platform powered by picodrive.

**Comment by schmurtzm** [comment]
Traces  from WinDGB and Time Travel Debugging added 🤞.
