### ISSUE TITLE
RetroArch 

### ISSUE THREAD

**Issue by DLSuS23** [libretro/RetroArch#15269]
_Es para Android?... Bro. __

**Comment by DLSuS23** [comment]
Que?..... Si me apareció la página allí, pero todo en inglés y no decía que era para Android.... 
Por cierto como carajos hace uno par ejecutar todos los emuladores de esta app, por qué apenas da pa usar 2 o 3 emuladores el resto no da para instalarlos.

**Comment by askotx** [comment]
Primero, es en inglés cualquier solicitud.
Second, this is an issue tracker, not a chat. 
There are a lot of online tutorials or videos that you could use to start retroarch on your preferred search engine.
@hizzlekizzle would you mind to close?

**Comment by DLSuS23** [comment]
> Primero, es en inglés cualquier solicitud.
> Second, this is an issue tracker, not a chat. 
> There are a lot of online tutorials or videos that you could use to start retroarch on your preferred search engine.
> 

Que dice allí no me da para traducir.

**Comment by DLSuS23** [comment]
> Primero, es en inglés cualquier solicitud.
> Second, this is an issue tracker, not a chat. 
> There are a lot of online tutorials or videos that you could use to start retroarch on your preferred search engine.
> 

De echo ay demaciado pocos tutoriales que digan cómo usarlo.
