### ISSUE TITLE
remap the joystick to use the numpad

### ISSUE THREAD

**Issue by drrak** [libretro/RetroArch#15263]
_Translator:_
Hi,
how do I remap the Joystick to use the number keys? I'm using a [Keyrah](http://wiki.icomp.de/wiki/Keyrah_V2) adapter that turns a C64 keyboard into a USB keyboard, and the two DB9 (joystick) ports use a numpad:
<html>
<body>
<table class="wikitable sortable jquery-tablesorter" border="1" cellpadding="2" cellspacing="0" style="font-size: 12.8px; background-color: rgb(171, 188, 200); color: rgb(4, 35, 48); margin: 1em 1em 1em 0px; border: 1px solid rgb(170, 170, 170); border-collapse: collapse;"><thead style="color: rgb(4, 35, 48); font-family: Font-Normal, sans-serif; font-size: 12.8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tr><th colspan="2" class="headerSort" title="Sort ascending" style="background-color: rgb(154, 171, 183); color: rgb(4, 35, 48); border: 1px solid rgb(170, 170, 170); padding: 0.2em 21px 0.2em 0.2em; text-align: center; background-image: url(&quot;data:image/gif;base64,R0lGODlhFQAJAIABAAAAAAAAACH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS4wLWMwNjAgNjEuMTM0Nzc3LCAyMDEwLzAyLzEyLTE3OjMyOjAwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjAxODAxMTc0MDcyMDY4MTE4OEM2REYyN0ExMDhBNDJFIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjdCNTAyODcwMEY4NjExRTBBMzkyQzAyM0E1RDk3RDc3IiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjdCNTAyODZGMEY4NjExRTBBMzkyQzAyM0E1RDk3RDc3IiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzUgTWFjaW50b3NoIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6MDE4MDExNzQwNzIwNjgxMTg4QzZERjI3QTEwOEE0MkUiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MDE4MDExNzQwNzIwNjgxMTg4QzZERjI3QTEwOEE0MkUiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4B//79/Pv6+fj39vX08/Lx8O/u7ezr6uno5+bl5OPi4eDf3t3c29rZ2NfW1dTT0tHQz87NzMvKycjHxsXEw8LBwL++vby7urm4t7a1tLOysbCvrq2sq6qpqKempaSjoqGgn56dnJuamZiXlpWUk5KRkI+OjYyLiomIh4aFhIOCgYB/fn18e3p5eHd2dXRzcnFwb25tbGtqaWhnZmVkY2JhYF9eXVxbWllYV1ZVVFNSUVBPTk1MS0pJSEdGRURDQkFAPz49PDs6OTg3NjU0MzIxMC8uLSwrKikoJyYlJCMiISAfHh0cGxoZGBcWFRQTEhEQDw4NDAsKCQgHBgUEAwIBAAAh+QQBAAABACwAAAAAFQAJAAACF4yPgMsJ2mJ4VDKKrd4GVz5lYPeMiVUAADs=&quot;); cursor: pointer; background-repeat: no-repeat; background-position: right center; width: 150pt;">Joystick</th><th class="headerSort" title="Sort ascending" style="background-color: rgb(154, 171, 183); color: rgb(4, 35, 48); border: 1px solid rgb(170, 170, 170); padding: 0.2em 21px 0.2em 0.2em; text-align: center; background-image: url(&quot;data:image/gif;base64,R0lGODlhFQAJAIABAAAAAAAAACH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS4wLWMwNjAgNjEuMTM0Nzc3LCAyMDEwLzAyLzEyLTE3OjMyOjAwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjAxODAxMTc0MDcyMDY4MTE4OEM2REYyN0ExMDhBNDJFIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjdCNTAyODcwMEY4NjExRTBBMzkyQzAyM0E1RDk3RDc3IiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjdCNTAyODZGMEY4NjExRTBBMzkyQzAyM0E1RDk3RDc3IiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzUgTWFjaW50b3NoIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6MDE4MDExNzQwNzIwNjgxMTg4QzZERjI3QTEwOEE0MkUiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MDE4MDExNzQwNzIwNjgxMTg4QzZERjI3QTEwOEE0MkUiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4B//79/Pv6+fj39vX08/Lx8O/u7ezr6uno5+bl5OPi4eDf3t3c29rZ2NfW1dTT0tHQz87NzMvKycjHxsXEw8LBwL++vby7urm4t7a1tLOysbCvrq2sq6qpqKempaSjoqGgn56dnJuamZiXlpWUk5KRkI+OjYyLiomIh4aFhIOCgYB/fn18e3p5eHd2dXRzcnFwb25tbGtqaWhnZmVkY2JhYF9eXVxbWllYV1ZVVFNSUVBPTk1MS0pJSEdGRURDQkFAPz49PDs6OTg3NjU0MzIxMC8uLSwrKikoJyYlJCMiISAfHh0cGxoZGBcWFRQTEhEQDw4NDAsKCQgHBgUEAwIBAAAh+QQBAAABACwAAAAAFQAJAAACF4yPgMsJ2mJ4VDKKrd4GVz5lYPeMiVUAADs=&quot;); cursor: pointer; background-repeat: no-repeat; background-position: right center; width: 250pt;">Switch Middle Position (normal)</th><th class="headerSort" title="Sort ascending" style="background-color: rgb(154, 171, 183); color: rgb(4, 35, 48); border: 1px solid rgb(170, 170, 170); padding: 0.2em 21px 0.2em 0.2em; text-align: center; background-image: url(&quot;data:image/gif;base64,R0lGODlhFQAJAIABAAAAAAAAACH/C1hNUCBEYXRhWE1QPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS4wLWMwNjAgNjEuMTM0Nzc3LCAyMDEwLzAyLzEyLTE3OjMyOjAwICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtbG5zOnhtcD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wLyIgeG1wTU06T3JpZ2luYWxEb2N1bWVudElEPSJ4bXAuZGlkOjAxODAxMTc0MDcyMDY4MTE4OEM2REYyN0ExMDhBNDJFIiB4bXBNTTpEb2N1bWVudElEPSJ4bXAuZGlkOjdCNTAyODcwMEY4NjExRTBBMzkyQzAyM0E1RDk3RDc3IiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjdCNTAyODZGMEY4NjExRTBBMzkyQzAyM0E1RDk3RDc3IiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzUgTWFjaW50b3NoIj4gPHhtcE1NOkRlcml2ZWRGcm9tIHN0UmVmOmluc3RhbmNlSUQ9InhtcC5paWQ6MDE4MDExNzQwNzIwNjgxMTg4QzZERjI3QTEwOEE0MkUiIHN0UmVmOmRvY3VtZW50SUQ9InhtcC5kaWQ6MDE4MDExNzQwNzIwNjgxMTg4QzZERjI3QTEwOEE0MkUiLz4gPC9yZGY6RGVzY3JpcHRpb24+IDwvcmRmOlJERj4gPC94OnhtcG1ldGE+IDw/eHBhY2tldCBlbmQ9InIiPz4B//79/Pv6+fj39vX08/Lx8O/u7ezr6uno5+bl5OPi4eDf3t3c29rZ2NfW1dTT0tHQz87NzMvKycjHxsXEw8LBwL++vby7urm4t7a1tLOysbCvrq2sq6qpqKempaSjoqGgn56dnJuamZiXlpWUk5KRkI+OjYyLiomIh4aFhIOCgYB/fn18e3p5eHd2dXRzcnFwb25tbGtqaWhnZmVkY2JhYF9eXVxbWllYV1ZVVFNSUVBPTk1MS0pJSEdGRURDQkFAPz49PDs6OTg3NjU0MzIxMC8uLSwrKikoJyYlJCMiISAfHh0cGxoZGBcWFRQTEhEQDw4NDAsKCQgHBgUEAwIBAAAh+QQBAAABACwAAAAAFQAJAAACF4yPgMsJ2mJ4VDKKrd4GVz5lYPeMiVUAADs=&quot;); cursor: pointer; background-repeat: no-repeat; background-position: right center; width: 250pt;">Switch Down Position (emu)</th></tr></thead><tbody style="color: rgb(4, 35, 48); font-family: Font-Normal, sans-serif; font-size: 12.8px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><tr><td rowspan="5" style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Port 1</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">up</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">cursor up</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 9</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">down</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">cursor down</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 3</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">left</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">cursor left</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 7</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">right</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">cursor right</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 1</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">fire</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">space</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 0</td></tr><tr><td rowspan="5" style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Port 2</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">up</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 8</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 8</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">down</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 2</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 2</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">left</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 4</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 4</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">right</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 6</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 6</td></tr><tr><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">fire</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 5</td><td style="border: 1px solid rgb(170, 170, 170); padding: 0.2em;">Numpad 5</td></tr></tbody><br class="Apple-interchange-newline">
</body>
</html>

**Comment by RobLoach** [comment]
https://docs.libretro.com/guides/input-and-controls/
