### ISSUE TITLE
ppsspp bug

### ISSUE THREAD

**Issue by hunter1026** [libretro/RetroArch#15279]
when going into sleep mode and turning back on the screen, its like the game is in turbo mode everythings super fast . on iphone.

**Comment by hunter1026** [comment]
it only does it if you lock the screen with the menu open. if i disable "pause content when menu is active" option then lock the phone and unlock it its fine.

**Comment by Retroism** [comment]
> when going into sleep mode and turning back on the screen, its like the game is in turbo mode everythings super fast . on iphone.

Mine crashes instantly. Do you also experience black screen on N64 after going to sleep mode or going to task manager?

**Comment by hunter1026** [comment]
its not just on ppsspp, on other cores this happens. ive noticed it also on dosbox pure.

**Comment by Retroism** [comment]
> its not just on ppsspp, on other cores this happens. ive noticed it also on dosbox pure.

Lemuroid doesn't have this bug using the same cores so I think this is purely on Retroarch's side.
