### ISSUE TITLE
[Feature Request] "System Files are in Content Directory" improvements

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#15272]
Right now I think the "System Files are in Content Directory" setting could use some improvements:

* When it's ON and no content is loaded there should be a warning in "Core Information", something to warn that the setting is enabled so the "Present/Missing" stuff can be incorrect, because of course RA can't guess in advance what will be the correct folder. Something like this for example:

  ![image](https://github.com/libretro/RetroArch/assets/33353403/26123dd4-0ab1-4717-b424-b156b62006c2)

* When it's ON and content is loaded, the correct system folder should be checked in "Core Information", to avoid confusing situations like this where it says "Present" but the core says that the BIOS is missing:

  ![image](https://github.com/libretro/RetroArch/assets/33353403/78805927-d174-4397-973f-0e2f62135ddb)

* When it's ON `SYSTEM_DIRECTORY` should be updated accordingly in logs, so for example instead of showing
  > [INFO] [Environ]: SYSTEM_DIRECTORY: "C:\RetroArch-Win64\system".

  it should show
  > [INFO] [Environ]: SYSTEM_DIRECTORY: "D:\Games\Sony - PlayStation".

~~* Lastly, it's more of a nitpick but I think it's not super intuitive to have this setting in `Settings > Saving`, but tbh I'm not sure where it could be moved... `Settings > Core` maybe? 🤔~~ **edit:** the setting is now in `Settings > Core`.

Anyway, I'm just throwing a bunch of suggestions but I have no idea how hard it would be to implement... :p

**Comment by hizzlekizzle** [comment]
I think these are all good suggestions, yeah, settings > core seems at least reasonably appropriate.
