### ISSUE TITLE
Custom System Name Breaks Playlist Thumbnails Updater

### ISSUE THREAD

**Issue by Fai1edMit0sis** [libretro/RetroArch#15284]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Using the Custom System Name makes the playlists unrecognisable for the Thumbnails Updater to grab the boxart of their entries. For example, changing the default `Nintendo - Nintendo Entertainment System` to `NES` will render the entire playlist boxartless.

### Expected behavior

The Playlist Thumbnails Updater recognises the playlist/system and grabs the boxart for its entries.

### Actual behavior

The Playlist Thumbnails Updater looks up the entries but doesn't get the boxart.

### Steps to reproduce the bug

1. Using the xmb interface, go to Import Content and choose Manual Scan.
2. Point Retroarch to the ROMs of one of the mentioned systems, set System Name as <Custom> **_and_** type in your custom name and start scanning.
3. After scan is done, head back to the Main Menu>Online Updater>Playlist Thumbnails Updater>Your Custom System Name.

### Bisect Results

This is my first time using it, so I can't tell.

### Version/Commit

- RetroArch: v1.15.0

### Environment information

- OS: Windows 10 Build 19045.2965

**Comment by hizzlekizzle** [comment]
This is intended behavior. The thumbnail/boxart matching is all based on names and we don't have fuzzy matching or aliases, so if they don't match exactly, RetroArch doesn't know where to find things.

**Comment by Fai1edMit0sis** [comment]
This leaves me with two questions:
1. What's the point of this option if it contradicts with another?
2. Is it possible to make it also match with similar keywords, e.g. NES, PS1, Dreamcast etc.?

**Comment by Hari-82** [comment]
@Fai1edMit0sis Hi, I'm not a dev but I solved this by replacing all the lines, using a text editor (I use notepad++) with funcion of find & replace, in the playlist file.

"db_name": "custom_named_list.lpl"

with

"db_name": "correct_name.lpl"

In my case I have 2 different playlist for PS1, one named correctly "Sony - PlayStation" with swanstation as associated core and another one named "Sony - PlayStation - Native" that use BeetlePsx. So in my custom named playlist file I replaced:

"db_name": "Sony - PlayStation - Native.lpl"

with

"db_name": "Sony - PlayStation.lpl"

Now both have Boxart and Screenshot. it takes just few seconds and it seems to work.

**Comment by Fai1edMit0sis** [comment]
@Hari-82 Okey, this works, thanks, but only after Retroarch grabs boxart for the default playlist; if you did it before this happens or if you later added a new file to that playlist, it would have no boxart. Anyway, I'll close the issue as I don't want to waste the devs time with what's a mild annoyance rather than a real issue. That being said, it'd be a nice addition if this got addressed at some point.
