### ISSUE TITLE
content downloader and core files downloader broken on nightly.

### ISSUE THREAD

**Issue by LuanVSO** [libretro/RetroArch#15306]
## Description

content downloader and core files downloader broken on nightly

### Expected behavior

download homebrew successfully.

### Actual behavior
download fails and menu is broken.

[What is actually happening]

### Steps to reproduce the bug

https://github.com/libretro/RetroArch/assets/43626415/351c8e3b-d9c6-41b0-9df3-edc66a69cd79

### Bisect Results

this build is the first one to include the bug:
https://buildbot.libretro.com/nightly/windows/x86_64/2023-05-11_RetroArch.7z

### Version/Commit

- RetroArch: 1.15.0 d2e4dc0

### Environment information

- OS: windows 11 and android 13

**Comment by ToniBC** [comment]
Yes, the Core System Files Downloader option does not work, apparently it is related to something in the languages.

You enter Retroarch, for example in Spanish, to the option and it comes out empty, you go to the language, change it to English, you go to the option and it remains empty, but you return to the language in Spanish, and now the content comes out and it works. All without leaving Retroarch.

All this in the Nightly, in the stable it works.

**Comment by sonninnos** [comment]
I managed to fix this at least by forcing the ok callback to refresh the entries. Indeed now the data somehow comes too late, as in the menu always shows the previous state. No idea yet what is the proper approach.
