### ISSUE TITLE
Auto controller config is bugged on Android

### ISSUE THREAD

**Issue by makedir** [libretro/RetroArch#15314]
How to reproduce:

Install latest stable on Fire TV 4k max stick, use firetv remote and a xbox controller through bt. open retroarch through remote. if you press a controller button it correctly switches to controller, but if you use the remote again, it switches to remote, and now controller doesnt work anymore until you close retroarch and open it again.

There need to be an option, so that controller #2 also can navigate the menu, and a way to switch back between controller #1 and #2.

**Comment by RobLoach** [comment]
Try using "All Users Control Menu".

**Comment by makedir** [comment]
@RobLoach where is that option I cant find it. This reddit post says it was removed some years ago: https://www.reddit.com/r/RetroArch/comments/mpucvj/all_users_control_menu/

**Comment by lostmsu** [comment]
@RobLoach can this be enabled by default on Amazon devices?

**Comment by RobLoach** [comment]
Had made a Pull Request to enable this for all devices, but I'm unsure what issues it causes: https://github.com/libretro/RetroArch/pull/6635
