### ISSUE TITLE
[Netplay] systematically freezing on server host creation if quit_on_close_content = "1"

### ISSUE THREAD

**Issue by schmurtzm** [libretro/RetroArch#15313]
## Description

When `quit_on_close_content = "1"` in retroarch.cfg then Netplay will systematically freeze on server host creation.
As Retroarch restart the game when running a Netplay host, this option has a bad effect.
This can be hard for users to diagnose this freeze as this option to close Retroarch when closing content is pretty common.

### Expected behavior

Net server creation should not freeze whatever the current setting on `quit_on_close_content`.

### Actual behavior

Retroarch is frozen, impossible to go in the menu again.

### Steps to reproduce the bug

1 - turn on "quit on close content" : `"Settings" ->  "User interface" -> "quit on close content"`
2 - run a SNES (snes9x2005 plus) or MD (Pico) game (but probably any core / any game will do the same)
3- start a Netplay Host -> retroarch is frozen, impossible to go in the menu again.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

RetroArch v1.15.0

- OS: 

same behavior on Windows x86 and linux arm

**Comment by davidgfnet** [comment]
I think this is now fixed right @schmurtzm  ?

**Comment by schmurtzm** [comment]
> I think this is now fixed right @schmurtzm ?

Yes fixed thanks to  #16014 ! Tested on Windows and Linux (Miyoo Mini).

thanks a lot !
