### ISSUE TITLE
Where is the File Browser, and Show Hidden Files and Directories option?

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#15348]
Entries in RA 1.15.0:
* Settings -> File Browser
* Settings -> File Browser -> Show Hidden Files and Directories, 

I cannot find them in RA 1.7.3. Where are they? Any help is appreciated.

**Comment by davidhedlund** [comment]
@hizzlekizzle Can you please help me?

**Comment by hizzlekizzle** [comment]
Dunno, they might not even exist in that version, which is >5 yrs old at this point. I'm afraid we can't provide support for versions that are that old.

**Comment by davidhedlund** [comment]
show_hidden_files still exists in retroarch.cfg for RA 1.7.3 and it is working, I just tried it. So I want to document where the GUI path is to switch it on/off.

**Comment by davidhedlund** [comment]
Finally I found it: Hit F5 (to open theFile Browser): View -> Options -> Show Hidden Files and Folders

**Comment by davidhedlund** [comment]
> Finally I found it: Hit F5 (to open the File Browser): View -> Options -> Show Hidden Files and Folders

Sorry, that only modified retroarch_qt.cfg, not retroarch.cfg

**Comment by davidhedlund** [comment]
Found it: Main Menu -> Load Content -> Settings -> Show Hidden Files and Folders

**Comment by davidhedlund** [comment]
> Finally I found it: Hit F5 (to open the File Browser): View -> Options -> Show Hidden Files and Folders

When press F5 in RetroArch appimage 1.16.0, nothing happens. Do you know how to access the File Browser in this version? @hizzlekizzle

**Comment by davidhedlund** [comment]
> Dunno, they might not even exist in that version, which is >5 yrs old at this point. I'm afraid we can't provide support for versions that are that old.

I guess it has been removed.

**Comment by hizzlekizzle** [comment]
There should be 2 AppImages, one of which has the F5 desktop menu enabled (the Qt version) and one that does not, since Qt libs can cause conflicts with certain distros.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16099

**Comment by davidhedlund** [comment]
> There should be 2 AppImages, one of which has the F5 desktop menu enabled (the Qt version) and one that does not, since Qt libs can cause conflicts with certain distros.

Thank you very much for the explanation!

**Comment by davidhedlund** [comment]
> There should be 2 AppImages, one of which has the F5 desktop menu enabled (the Qt version) and one that does not, since Qt libs can cause conflicts with certain distros.

Speaking of "browsers": Settings -> Directory -> Configs ("Set start directory for the menu configuration browser") <-- do you know where that browser is located?
