### ISSUE TITLE
iPadOS : Flycast cannot open the ROM 

### ISSUE THREAD

**Issue by ansinerd** [libretro/RetroArch#15341]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[in retroarch the roms are shown in Flycast/Dreamcast folder and when JIT is enabled, i click on the game and it says “ fails to load, whereas If i go to load content option and manually select the rom from the folder, it opens the game. ]

### Expected behavior

[Dreamcast should be able to load the rom from rom list instead of manually loading rom and selecting core to play it]

### Actual behavior

[I have to manually load the content and rom in order to play]

### Steps to reproduce the bug

1. [add flycast bios and roms in retroarch]
2. [go to retroarch dreamcast and try open the rom it will fail to load it]
3. [go to load content and manually open the rom, it will work...]

### Version/Commit

- RetroArch: [1.15/30th May]

### Environment information

- OS [iPad OS 16.2]

**Comment by warmenhoven** [comment]
I think #15372 fixes this. Before it's merged, you should be able to confirm by resetting the core association in the content playlist. After the association is reset, it should continue to work until the next time the app is reinstalled.

**Comment by LibretroAdmin** [comment]
Closing this, if it's still not fixed then let us know.
