### ISSUE TITLE
(UWP) Broken Builds 4: The Comeback

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#15357]
## Description

Commit https://github.com/libretro/RetroArch/commit/938d60d0f4589a3c6982838176475f077df640a4 broke UWP builds.

@JesseTG Your input would be appreciated here.

### Expected behavior

RetroArch to build.

### Actual behavior

You can guess. Here's the Visual Studio Error List:

![image](https://github.com/libretro/RetroArch/assets/35014183/78ed8e0c-1ba4-4901-9a23-ae7afa7758dd)

### Bisect Results

Commit https://github.com/libretro/RetroArch/commit/938d60d0f4589a3c6982838176475f077df640a4 broke things.

### Environment information

- OS: Windows 11
- Compiler: MSVC

**Comment by odditude42** [comment]
common/mmdevice_common.h:24 should likely be:

`void *mmdevice_list_new(const void *u, enum EDataFlow data_flow);`

note that if correct, this will likely reveal more similar syntax errors.

source: https://stackoverflow.com/questions/26978315/compile-as-c-code-in-visual-studio-2010

**Comment by JesseTG** [comment]
Oh, Hell. We need to move these build pipelines to GitHub so they run _before_ the PR is merged.

I'll take a look, thank you for bringing this to my attention.

**Comment by JesseTG** [comment]
@GABO1423 Which solution file is that? `RetroArch-msvcUWP`?

**Comment by GABO1423** [comment]
> @GABO1423 Which solution file is that? `RetroArch-msvcUWP`?

That's the one, it can be located in the `pkg/msvc-uwp` directory.
