### ISSUE TITLE
Rename "Update Joypad Profiles" to "Update Joypad Profiles (requires restart)"

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#15362]
The menu entry `Main Menu -> Online Updater -> Update Joypad Profiles` requires restart but it's not indicated when you are running the update so it's easy to think it's broken. I think it should be renamed to "Update Joypad Profiles (requires restart)".

**Comment by sonninnos** [comment]
Or perhaps rather make them work after update without restart.

**Comment by davidhedlund** [comment]
> Or perhaps rather make them work after update without restart.

Agreed. I was thinking about that This is a starting task though.

**Comment by davidhedlund** [comment]
Main Menu -> Online Updater -> Update Joypad Profiles should ideally:
* Download the files
* Reload the controller based on the driver and corresponding config file.

**Comment by davidhedlund** [comment]
Thank you!

But will it inform that RA will be restarted? I mean, RA must be restarted for settings to take effect. So if someone has made changes in the settings in other areas but are not finished, they might lose control since they are not warned about an automatic restart.

**Comment by sonninnos** [comment]
No. It just reinits stuff just like toggling fullscreen.

**Comment by davidhedlund** [comment]
> No. It just reinits stuff just like when toggling fullscreen.

Ah, great, so there's no need to restart.
