### ISSUE TITLE
The xvideo gfx driver is broken

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#15360]
## Description
Here's what the xvideo gfx driver looks for me:

![xvideo_bug](https://github.com/libretro/RetroArch/assets/135624069/48f44bd7-fb15-4681-8974-b7a84f1c1813)

Am I alone in this? I've tried the master branch, then v1.15.0.

The v1.8.0 just prints this then quits:
`[ERROR] [XVideo]: Failed to find valid XvPort or format.`

The problem is, again, that if you trip yourself by selecting a faulty video driver in the Drivers menu, you can't get your RA working without editing the config file. Some people will even ragequit over something like this.

### Environment information
- OS: Ubuntu 22.04.2 x64
- Compiler: gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1)

**Comment by hizzlekizzle** [comment]
which menu are you using? I think it may only work with RGUI? though I admit I haven't tried it in years.

**Comment by hizzlekizzle** [comment]
Yes, you're right. Pressing F3 makes it go away/return. Looks like I'm getting ~2000 FPS, too...

I guess the next step is going to be to bisect it -_-

FAKEDIT: welp, tried some revisions all the way back to 2017 and it still doesn't work, so it seems something has broken outside of RetroArch (also/instead?).
