### ISSUE TITLE
SCUMMVM change language with *.scummvm file

### ISSUE THREAD

**Issue by Benman2785** [libretro/RetroArch#15371]
# First and foremost consider this:
i use OnionOS on Miyoo Mini Plus
as RetroArch hands info to ScummVM via game.scummvm file - so it should be relevant

## Description

cant play "Beneth the Steel Sky" in german because i cant switch language

### Expected behavior

to set in *.scummvm a 2nd line with language=de

### Actual behavior

cant switch language in via cfg (using OnionOS on Miyoo Mini Plus) = game is still in english
yet when i add the game manually via launcher and set it to german it works - but i have to load the game - then go into launcher and load the game from there

### Steps to reproduce the bug

1. ./scummvm/bass/bass.scummvm = sky
2. start game
3. [and so on...]

### Bisect Results

using latest onion 4.2 beta (yet i guess not implemented yet)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: BuildDate May 29 2023

### Environment information

- OS: OnionOS
- Compiler: GCC (8.3.0) 32-bit

**Comment by sonninnos** [comment]
This issue belongs in the core repo, since RA don't and can't care about the launch file contents.

**Comment by i30817** [comment]
https://github.com/i30817/libretro-mkscumm

**Comment by Benman2785** [comment]
i should rtfm (if there was one) - its now working

https://github.com/i30817/libretro-mkscumm/issues/3
