### ISSUE TITLE
[Steam Cloud] Track *.state1 through *.state9 & *.state.auto files recursively in states folder

### ISSUE THREAD

**Issue by ds22x** [libretro/RetroArch#15375]
Currently, only *.state files are tracked recursively inside of the states folder, whereas the files mentioned in the header are only tracked when placed inside the states folder.

**Comment by hizzlekizzle** [comment]
Is this still an issue? I went to check on it and it seems to already be set to search for these files recursively from the top-level 'states' directory:
![image](https://github.com/libretro/RetroArch/assets/2805586/bb7a01ef-73d1-4c47-b227-73289fba491e)

**Comment by ds22x** [comment]
It seems to have been fixed since I first opened this issue.
