### ISSUE TITLE
F_ typo desktop menu

### ISSUE THREAD

**Issue by ShalokShalom** [libretro/RetroArch#15373]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

F_ - There is no specific F key specified

### Expected behavior

F2, F12 ..

### Actual behavior

F 

### Steps to reproduce the bug

1. Open Desktop Menu for the first time
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Linux
- Compiler: [In case you are running local builds]

![Screenshot_20230613_161608](https://github.com/libretro/RetroArch/assets/6344099/1802000d-e603-4a92-817e-bed7ff9b1dc2)

**Comment by sonninnos** [comment]
Actual behavior is correct. Sure it does not sit well between those others that are Fx keys.

**Comment by ShalokShalom** [comment]
Aaaah. So its the F key? Honestly, this is so clumsy, it appears as if somebody did this on purpose :D

**Comment by sonninnos** [comment]
I changed the order a bit, but let me know if it still looks funny or could be more clear.
