### ISSUE TITLE
Version 1.15.0 Does Not Output Mouse Index in Logs. Version 1.14.0 did

### ISSUE THREAD

**Issue by jdeath** [libretro/RetroArch#15389]
## Description
Previous version (1.14.0) of retroarch outputted the index of the mouse in the log file. This allowed people to parse the logs to automatically set the mouse index. This often happens if you have a mouse and a lightgun. The mouse index will change depending on how the OS detects the mouse order. It was a work around to Issue: https://github.com/libretro/RetroArch/issues/7638

Please enable a way to output this information in the log again

A better fix would be to have retroarch allow setting the mouse index by name, instead of an index that changes often. A user has posted a Multi-Mouse Sofware, but this does not fix this issue of having two mice you want to work separately. That software just merges separate mice into a single virtual mouse.
 
### Expected behavior

I would expect entries in the log that look like this:
[INFO] [udev]: Waring REL pointer device (HID 0838:8918) has no mouse button
[INFO] [udev]: Waring REL pointer device (evmapy) has no mouse button
[INFO] [udev]: Keyboard #0: "Sleep Button" (/dev/input/event0).
[INFO] [udev]: Keyboard #1: "Power Button" (/dev/input/event1).
[INFO] [udev]: Keyboard #2: "Power Button" (/dev/input/event2).
[INFO] [udev]: Keyboard #3: "HP WMI hotkeys" (/dev/input/event3).
[INFO] [udev]: Keyboard #4: "Video Bus" (/dev/input/event4).
[INFO] [udev]: Keyboard #5: "evmapy" (/dev/input/event13).
**[INFO] [udev]: Mouse #0: "HID 0838:8918" (REL) /dev/input/event10
[INFO] [udev]: Mouse #1: "evmapy" (REL) /dev/input/event13**
[INFO] [udev]: Pad #0 (/dev/input/event11) supports 0 force feedback effects.
[INFO] [udev]: Pad #1 (/dev/input/event12) supports 0 force feedback effects.

### Actual behavior

The above entry is not present. Only udev entry in 1.15.0 is:
[INFO] [udev]: Pad #0 (/dev/input/event11) supports 0 force feedback effects.
[INFO] [udev]: Pad #1 (/dev/input/event12) supports 0 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".

### Steps to reproduce the bug

1. Run Retroarch 1.15.0
2. Start game - no log entry
3. Run Retroarch 1.14.x
4. Start game - no log Entry is present

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 

[INFO] Built: Mar  6 2023
[INFO] Version: 1.14.0

[INFO] Built: Jun 11 2023
[INFO] Version: 1.15.0

### Environment information

- OS: Linux

**Comment by sonninnos** [comment]
For some reason those are now outputting to debug level, which is not good, but very easy to fix.
