### ISSUE TITLE
Viewport positioning in portrait mode in recent Android nightlies

### ISSUE THREAD

**Issue by pressRtowin** [libretro/RetroArch#15401]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Installed a recent nightly release to test out some features and discovered that when using integer scaling in portrait orientation, the viewport was centered vertically on my display much like it would usually be when in landscape mode. Unfortunately this means halving the amount of space we have for on screen controls. Was this an intended change? If so, it's a very negative one, especially with no option (I could find) to revert the behavior, besides disabling integer scaling and setting up a custom viewport, which is not a suitable workaround due to RetroArch having no option to set separate viewport settings for portrait and landscape orientations, leaving the automatic sizing the only viable choice to maintain rotational freedom.

### Expected behavior

The viewport stays locked to the top of the display, regardless of the settings used, unless explicitly setting a custom viewport (or we have the option to enable/disable this behavior).

### Actual behavior

The viewport centers itself vertically when integer scaling is enabled.

### Steps to reproduce the bug

1. Enable integer scaling

### Bisect Results

Sometime between 1.15.0 and now

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 2023-06-17 nightly release for Android

### Environment information

- OS: Android 13/One UI 5.1

**Comment by warmenhoven** [comment]
That was me, it wasn't supposed to do that. It was supposed to be that if you provide a custom aspect ratio (viewport position) it will respect that instead of pinning high, so that you can move it down gently (presumably only a hundred pixels or so). I thought I had put it in a place where it would only be affected by the custom viewport setting but it seems I missed. I'll take a look soon. In the mean time you can move it back up by changing the Aspect Ratio to Custom.

**Comment by KINGLIFER** [comment]
Maybe one day they will do what people been asking for years.
https://apps.apple.com/us/app/delta-game-emulator/id1048524688
