### ISSUE TITLE
Menu_cbs_get_value.c:662 error: redeclaration of '_len' with no linkage

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/RetroArch#15429]
## Description

Compilation issue when compiling on commit "d4fc6c7ce66aa3a4317c39b866b0706a7d5e019b" I'm compiling against Emuelec 4.6 latest commit for odroid n2+ toolchain

It seems menu:cbs_get_value has a bug. 

CC tasks/task_overlay.c
menu/cbs/menu_cbs_get_value.c: In function 'menu_action_setting_disp_set_label_cpu_policy':
menu/cbs/menu_cbs_get_value.c:662:11: error: redeclaration of '_len' with no linkage
  662 |    size_t _len                    = snprintf(s2, len2, "%s %d",
      |           ^~~~
menu/cbs/menu_cbs_get_value.c:658:11: note: previous declaration of '_len' with type 'size_t' {aka 'long unsigned int'}
  658 |    size_t _len;
      |           ^~~~
make: *** [Makefile:209: obj-unix/release/menu/cbs/menu_cbs_get_value.o] Error 1
make: *** Waiting for unfinished jobs....
menu/menu_displaylist.c: In function 'menu_displaylist_ctl':
menu/menu_displaylist.c:11795:46: warning: '%d' directive output may be truncated writing between 1 and 3 bytes into a region of size 2 [-Wformat-truncation=]
11795 |                                        "Mode %d", toc->track[i].mode);

### Expected behavior

To compile

### Actual behavior

CC tasks/task_overlay.c
menu/cbs/menu_cbs_get_value.c: In function 'menu_action_setting_disp_set_label_cpu_policy':
menu/cbs/menu_cbs_get_value.c:662:11: error: redeclaration of '_len' with no linkage
  662 |    size_t _len                    = snprintf(s2, len2, "%s %d",

### Steps to reproduce the bug

1. PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH=aarch64 DISTRO=EmuELEC ./scripts/build retroarch

### Bisect Results

This issue starting after RetroArch commit d4fc6c7ce66aa3a4317c39b866b0706a7d5e019b

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.15.0/d4fc6c7ce66aa3a4317c39b866b0706a7d5e019b]

### Environment information

- OS: Linux 5.15.90.1-microsoft-standard-WSL2 1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Compiler: Emuelec Toolchain make

**Comment by LibretroAdmin** [comment]
Hopefully this solves your compilation issue-
https://github.com/libretro/RetroArch/commit/7105e0508cb2dc3d87dcfe3884fc28ef26b2ff0e

**Comment by Kelvfimer** [comment]
Yes it solved the issue. Thx so much!!!!
