### ISSUE TITLE
[FEATURE] Additional options in Menu Settings

### ISSUE THREAD

**Issue by RagnaStrife** [libretro/RetroArch#1542]
To select between detect core at content load or not and history size
So load content commands would look like this:

Load Content (History) * with whatever size limit was set in Menu Settings *
Load Content (Path) * which would detect core if selected in Menu Settings *

Additionally this other Menu Settings option for loading content from last path: https://github.com/libretro/RetroArch/issues/1438

**Comment by fr500** [comment]
I see a lot of "Feature Requests" that would be just catering to a particular use case... feature bloat is not really what we want to do

**Comment by RagnaStrife** [comment]
I thought it would be helpful and would make more sense than 3 different load content options.
I have worked in many applications/programs with large feature-sets and I don't think this small thing is precisely feature bloat.
How is the active RA team size in numbers? I hope it's not you alone >_<

**Comment by SAKUJ0** [comment]
Hey, help is even appreciated if you are *not* familiaried with the source code or don't have the time!
