### ISSUE TITLE
Nintedo Switch retroarch bluemsx core not working

### ISSUE THREAD

**Issue by suww37** [libretro/RetroArch#15440]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

It's been a very long time since it didn't work on the Nintendo Switch's retroarch bluemsx core. When running rom or dsk images, it crashes and generates an error. Why don't the developers think of improving this? I have no choice but to use the fmsx core, which is too outdated and often has roms or dsks that don't work. Who has no idea to solve this?

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by m4xw** [comment]
> Only RetroArch bugs should be filed here. Not core bugs or game bugs

Also bluemsx is not supported for switch.

**Comment by suww37** [comment]
Why retroarch in switch do not support bluemsx core? I know  the core foder has blumsx core.
