### ISSUE TITLE
overlay bugged

### ISSUE THREAD

**Issue by hunter1026** [libretro/RetroArch#15465]
some inputs on the on screen overlay touchscreen gamepad wont work in certain circumstances on ios. for example holding a button on the top left of the screen in landscape you cant press anything on the top right of the screen. ive tried different overlays and its the same. but this is happening on latest nightly build. retroarch 1.9.0 doesn’t have these issues i tested it.

**Comment by hunter1026** [comment]
also the keyboard is messed up with question marks instead of symbols![image](https://github.com/libretro/RetroArch/assets/122758962/61a6a41b-a4b4-4987-8e37-4ef0432e36ff)

**Comment by warmenhoven** [comment]
I fixed the question marks.

**Comment by hunter1026** [comment]
to fix this i just turned on enable fullscreen over notch now im not having any problems with overlay inputs on ios
