### ISSUE TITLE
Volume levels fluctuate based on amount of sound when using built-in volume adjustment.

### ISSUE THREAD

**Issue by pressRtowin** [libretro/RetroArch#15474]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Note: how easy this is to observe seems highly game-dependent (probably based on how the audio is layered and mixed). I've so far tested this on both GBA and NDS on Android using multiple cores. 

If you have the RA volume set *very* low, and your system volume set very high (essentially if you want to max your system volume and use only RA volume) audio constantly ducks in and out based on how much sound is playing. If little sound is playing, it'll be quiet, when more sounds play, it'll suddenly grow louder. It's definitely not the game audio itself doing this, as setting the volumes in reverse (100% RA, low system sound) doesn't reproduce this.

Two games that I found this effect to be easily observed in are Kirby: Nightmare in Dreamland (GBA) and Kirby: Squeak Squad (NDS). You can hear the background music get louder whenever you use an ability. 

### Expected behavior

Volume level should not fluctuate. 

### Actual behavior

Volume fluctuate based on content playing. 

### Steps to reproduce the bug

Quickest way to observe this effect is to max out your system volume and then set the RA volume to a quiet but audible level (probably around 2-3%). Then load up Nightmare in Dreamland or another game (how easy this is to hear depends on the game and how the audio is mixed as mentioned before). In Nightmare in Dreamland, you simply have to pay attention to the volume of the background music, then press/hold B, release B, and repeat, and you'll notice the music volume fluctuates with your ability (pick one that makes a good amount of sound, or just use inhale).

You can reverse the volumes as mentioned before to see that this does not happen when RA volume is at 100%

### Bisect Results

--

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15.0

### Environment information

- OS: Android 13/One UI 5.1
- Compiler: --

**Comment by sonninnos** [comment]
Sounds like the operating system mixer is to blame then. Maybe try finding the sweet spot between minimum and maximum where it does not happen.
