### ISSUE TITLE
regression: automatic hotkey configuration no longer works correctly

### ISSUE THREAD

**Issue by mrbumpy409** [libretro/RetroArch#15482]
## Description

I use the following hotkey mappings with my controller:

- Hotkey Enable: Select
- Load State: R shoulder
- Save State: L shoulder
- Next Save State Slot: Dpad right
- Previous Save State Slot: Dpad left

However, since I variably use different controllers with RetroArch, the button numbers for these hotkeys changes. For example, with my Logitech controllers, Select is "8", but with my Xbox One controller, it is "6".

In the past, I have managed the changing button numbers by editing each controller's autoconfig file with the necessary button mappings, like so:

```
input_enable_hotkey_btn = "8"
input_load_state_btn = "5"
input_save_state_btn = "4"
input_state_slot_decrease_btn = "h0left"
input_state_slot_increase_btn = "h0right"
```

This, combined with setting the corresponding entries in retroarch.cfg to "nul", sets the hotkey buttons automatically based on whichever primary controller was plugged in.

However, in current RetroArch (1.15.0), this no longer works properly. The hotkeys appear to be getting set correctly from the autoconfig file (it will say "8 (Auto)" in the hotkeys menu), but once I load a game on any core, it acts as if the hotkey is always being pressed. This means that pressing Dpad right or left will change slots even if I'm not actually holding down Select.

### Expected behavior

Hotkeys should only activate if the "Hotkey Enable" button is pressed.

### Actual behavior

Hotkeys activate regardless even when the "Hotkey Enable" button is not pressed.

### Steps to reproduce the bug

Hopefully this should be clear enough from the description.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15.0 (666fbdcb38)
- Installed from [Libretro Stable PPA](https://launchpad.net/~libretro/+archive/ubuntu/stable).

### Environment information

- OS: KDE neon 5.27

**Comment by sonninnos** [comment]
Please try nightlies first before reporting issues. Pretty sure this is already fixed, and I can't reproduce.

**Comment by mrbumpy409** [comment]
I can confirm that the bug does not happen in the latest nightly.
