### ISSUE TITLE
malloc(): invalid next size (unsorted) in all 32 Bit emulators starting on commit 40049274b2bfee3554c399ecf5296d340129ac2a

### ISSUE THREAD

**Issue by MSHectorCM** [libretro/RetroArch#15488]
## Description

[Description of the bug]

Starting on commit https://github.com/libretro/RetroArch/commit/40049274b2bfee3554c399ecf5296d340129ac2a all 32 bit compiled emulators pcsx_rearmed, mupen64 or flycast are crashing with the message

malloc(): invalid next size (unsorted)

### Actual behavior

malloc(): invalid next size (unsorted)

Expected behaviour they should work

### Steps to reproduce the bug

Compile https://github.com/libretro/RetroArch/commit/40049274b2bfee3554c399ecf5296d340129ac2a onwards and use a 32 bit compilation of emulators pcsx_rearmed, mupen64 or flycast. 64 bit versions of those emulators run fine.

### Bisect Results

Logs
[emuelec.log](https://github.com/libretro/RetroArch/files/12071310/emuelec.log)
[retroarch.log](https://github.com/libretro/RetroArch/files/12071311/retroarch.log)
[emuelec1.log](https://github.com/libretro/RetroArch/files/12071312/emuelec1.log)
[emuelec2.log](https://github.com/libretro/RetroArch/files/12071329/emuelec2.log)

### Version/Commit

https://github.com/libretro/RetroArch/commit/40049274b2bfee3554c399ecf5296d340129ac2a and onwards

- RetroArch: [version/commit]

### Environment information

- OS: EMUELEC 4.6 Odroid n2+ SDL 2.28.1
- Compiler: Emuelec Toolchain

**Comment by LibretroAdmin** [comment]
Alright, this should deal with it -
https://github.com/libretro/RetroArch/commit/8aa0679cbd02db4cfcdbe94cebb5e77335a08500

**Comment by Kelvfimer** [comment]
Thx so much fixed :)

**Comment by MSHectorCM** [comment]
Thx so much fixed :)
