### ISSUE TITLE
[BUG] Changing Disk Index or Appending Disk does not work

### ISSUE THREAD

**Issue by RagnaStrife** [libretro/RetroArch#1548]
What the title says, basically. It doesn't work either when using ".m3u" content lists.
But hey! At least it enters the menu now (didn't in the 2015-03-18 version),
so I guess it is something being refactored/developed recently.

My only doubt is if it's a bug on RA or Mednafen-PSX, since I can't test it with other cores with the same functionality. But I guess this feature belongs to RA, so...

**Comment by fr500** [comment]
It works fine,
You need to cycle the tray. Have you ever changed a disk on a real console without opening the tray?
Cycle tray, change index, cycle tray.

Works with hotkeys too.

**Comment by RagnaStrife** [comment]
Yeah you were right.
I assumed it didn't work since before the menu refactoring it worked automatically at disk append.
It worked differently back then.
There was no need to make me look silly, though.

**Comment by twinaphex** [comment]
@RagnaStrife I don't think radius is trying to make you look silly or trying to downplay your issues. We're just trying to help in our spare time, that is all.

**Comment by fr500** [comment]
I didn't mean to make you look silly. Otherwise I would have stopped at that. Actually we were talking about relabeling those options.

It was just an analogy.

**Comment by RagnaStrife** [comment]
No problem, maybe I got the wrong impression, probably due to the impersonal nature of the internet.
I hope you too don't get the wrong impression with me either. I just love this project, and want to see it evolve, as I don't have the time to look at the code and submit anything if that is something you even approve, of course.

Still RA could do with an automatized or simplified way to swap discs, similar to the old options, or at least add a little info when you press SELECT on those options, for those who might not figure out how it works.
