### ISSUE TITLE
Shader menu bug

### ISSUE THREAD

**Issue by jayare5** [libretro/RetroArch#15494]
## Description

Trying to adjust shader settings does not work properly anymore since RA version 1.15.0.

### Expected behavior

Go into the shader menu, load any shader preset, make adjustments, apply changes and it should all work fine.

### Actual behavior

When you apply changes, all filter settings get set to default if they were set to linear or nearest. This means you can no longer properly configure shaders from this menu anymore.
Most shaders seem to load fine if you don't change anything, but at least 1 shader preset I made that used to work in 1.14.0 or prior, no longer works in 1.15.0 stable or the latest nightlies.

**Comment by jayare5** [comment]
1. Load any game in almost any core.
2. Go into the Quick menu / Shaders.
3. Load any shader preset. (Specifically any that has a filter mode that's either Linear or Nearest).
4. Try changing any of these settings (shader filter or scale).
5. Apply changes.
6. Everything that said Linear or Nearest now says Default, which breaks the configuration

Alternatively, sonninnos found out that you can just skip step 4, but apply changes twice, and it will break the configuration too.

**Comment by LibretroAdmin** [comment]
@jayare5 Can you check if sonninnos' PR solves the issue?

**Comment by jayare5** [comment]
> @jayare5 Can you check if sonninnos' PR solves the issue?

Tested the latest nightly, everything is perfect!!
