### ISSUE TITLE
inconsistencies in config

### ISSUE THREAD

**Issue by huwpascoe** [libretro/RetroArch#1549]
There's not really any standard when it comes to defining paths and the config file is kind of a dumping around in general at the moment, probably needs a cleanup.

```
cheat_settings_path
content_history_path
core_options_path
font_path
libretro_info_path
remapping_path
shader_path

autoconfig_dir
filter_dir
joypad_autoconfig_dir
shader_dir

assets_directory
content_history_directory
core_assets_directory
cursor_directory
extraction_directory
input_remapping_directory
libretro_directory
menu_config_directory
menu_content_directory
playlist_directory
resampler_directory
screenshot_directory
system_directory
```

**Comment by fr500** [comment]
_path is used for the full path of related files, as in retroarch-content-history.txt
dir/directory.. well yeah I agree

**Comment by huwpascoe** [comment]
I think libretro_info_path maps to a dir too

**Comment by RagnaStrife** [comment]
Yeah, I agree too. But it doesn't end at that.
It's all mixed up, and it even creates at first start a 16 player input settings bloat, or so it seems (48KB config file anyone?).

Trimmed example of mixed settings:

```
input_max_users = "1"
input_axis_threshold = "0.500000"
input_remap_binds_enable = "true"
netplay_client_swap_input = "true"
input_descriptor_label_show = "true"
autoconfig_descriptor_label_show = "true"
input_descriptor_hide_unbound = "false"
load_dummy_on_core_shutdown = "true"
fps_show = "false"
ui_menubar_enable = "true"
suspend_screensaver_enable = "true"
fps_monitor_enable = "true"
libretro_path = ":\cores\mednafen_psx_libretro.dll"
libretro_directory = ":\cores"
libretro_info_path = ":\coreinfo"
cheat_database_path = ":\cheats"
cursor_directory = ":\database\cursors"
rewind_enable = "false"
audio_latency = "64"
audio_sync = "true"
audio_block_frames = "0"
rewind_granularity = "1"
video_shader = ":\shaders\mednafen_psx_libretro.dll.cgp"
video_shader_enable = "true"
video_aspect_ratio = "-1.000000"
video_aspect_ratio_auto = "true"
video_windowed_fullscreen = "true"
video_scale = "3.000000"
autosave_interval = "0"
video_crop_overscan = "true"
video_scale_integer = "true"
video_smooth = "true"
video_threaded = "false"
video_shared_context = "true"
video_force_srgb_disable = "false"
video_fullscreen = "true"
video_refresh_rate = "59.950001"
video_monitor_index = "0"
video_fullscreen_x = "0"
video_fullscreen_y = "0"
video_driver = "gl"
menu_driver = "glui"
menu_pause_libretro = "true"
menu_mouse_enable = "false"
menu_timedate_enable = "true"
video_vsync = "true"
video_hard_sync = "false"
video_hard_sync_frames = "0"
video_frame_delay = "0"
video_black_frame_insertion = "false"
video_disable_composition = "false"
pause_nonactive = "false"
video_swap_interval = "2"
video_gpu_screenshot = "true"
video_rotation = "0"
screenshot_directory = ":\screenshots"
aspect_ratio_index = "22"
```

I could devise a way to sort options into clean categories, even with separate config files for each, like:
retroarch_paths.cfg
retroarch_video.cfg
...etc. The same with per core configs.

That would help people like me who maintains config files regularly until a point of ReadOnly is reached.
Not really much of a problem now, but would be of great help in the future.

**Comment by huwpascoe** [comment]
On topic, what do the colons mean when it comes to the directories? ```:\screenshots``` how come it isn't the standard ```./```?

**Comment by fr500** [comment]
```./``` will work to, ```:\``` and ```:/``` are just an internal convention for relative to RetroArch dir

**Comment by RagnaStrife** [comment]
> **On topic**, what do the colons mean when it comes to the directories? :\screenshots how come it
> isn't the standard ./?

Sorry, I thought your issue was more general, according to the title: "*inconsistencies in config*".
Should I just open an issue for that, @fr500?

**Comment by fr500** [comment]
No point opening another issue for something so similar. Anyway I don't think big changes to the configuration scheme will happen anytime soon

**Comment by RagnaStrife** [comment]
Just as I thought.
No problem, but just don't forget this if a config refactoring ever gets near the top priority list (lol) as it would be very helpful and even *"classy"* (though that's something uncommon on this kind of projects). :pray:

**Comment by huwpascoe** [comment]
@RagnaStrife I don't mean the colon thing is bad, I just wanted to know what it means and this seemed like a convenient place to ask!

**Comment by RobLoach** [comment]
A few things have happened in the configs...

1. Renamed a few variable names
2. I believe it's sorting alphabettically now? Could be wrong....
3. Added a bunch of new docs to the default config too

Feel free to re-open with a clearer desired outcomes and the issue template if these three things don't satisfy your needs. Thanks!
