### ISSUE TITLE
Online Updater doesn't download cheats for Nintendo Gamecube/Wii.

### ISSUE THREAD

**Issue by jalemann** [libretro/RetroArch#15524]
## Description

Online Updater doesn't download cheats for Nintendo Gamecube/Wii.

### Expected behavior

Online Updater > Update Cheats fetches cheats for dolphin emulator as it does for other platforms.

### Actual behavior

`dolphin-emu` cheats directory is empty.

### Steps to reproduce the bug

1. Online Updater
2. Update Cheats
3. Check `dolphin-emu` cheats directory.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15.0

### Environment information

- OS: Windows 10 x64 Build 22621 Windows.Xbox (v10.0)

**Comment by hizzlekizzle** [comment]
I think this is to be expected, as the core does not support frontend cheats, only the core's own built-in cheats.
