### ISSUE TITLE
[feature request] - Show background image behind render pipeline in XMB.

### ISSUE THREAD

**Issue by djL01** [libretro/RetroArch#15537]
**Description:**
- I'd like to be able to choose a background to show behind, for instance, the ribbon pipeline (or any of the others), in XMB.

**Expected behavior:**
- "Render pipeline opacity %:"
  - would reduce the visibility of the render pipeline in relation to the wallpaper image

**Actual behavior:**
- There is no render pipeline opacity option, just a selection of any of the options or toggled off completely.

**Steps to reproduce the scenario:**
1. Settings > User Interface > Appearance > Background Image > set image
2. ... > Appearance > Menu Shader Pipeline > [any]
3. No background is shown, only the render pipeline is visible

**Bisect Results:**
 - As far as I'm aware this has never not been a thing.

**Version/Commit:**
- RetroArch: 4b16b4f / Build: Nov 3 2021

**Environment information**
- OS: Android 11
- Frontend/Device name: SHIELD Android TV

**Comment by sonninnos** [comment]
"Menu Alpha Factor" seems to be doing that, but only when content is running. Indeed also the Appearance menu list itself could use some cleanup.

**Comment by sonninnos** [comment]
While this does not completely remove the issue, it should at least make it more bearable: https://github.com/libretro/RetroArch/pull/15556
