### ISSUE TITLE
v1.16.0 code release

### ISSUE THREAD

**Issue by theflyingape** [libretro/RetroArch#15541]
Current System Information version shows as **1.16.0** with an extensive changelog, but there is no GitHub source code 1.16.0 release to baseline for its features nor regressions.

**Comment by hizzlekizzle** [comment]
yes, it hasn't actually been released yet. There's a lot that goes into a release, and one is upcoming, but we're still prepping. A proper tag and tarball will be in github when that time comes.

**Comment by RobLoach** [comment]
![2bc66a80-b230-4717-b6e9-0d2d8f3a5101_text](https://github.com/libretro/RetroArch/assets/25086/578546ed-b7b9-403b-9ff6-09289e1b5ba5)

**Comment by theflyingape** [comment]
lmao -- terrible gif, not relevant to the thread. :-1: 
https://en.wikipedia.org/wiki/Software_versioning
