### ISSUE TITLE
Frame-Throttle Fractions

### ISSUE THREAD

**Issue by h4ckerman69** [libretro/RetroArch#15540]
I greet you my fellows. I'd like to make a request to introduce fractions into the Frame-Throttle settings so that my mind can play in peace.

## Description

Many people want to play games at 1.3x or 1.5x speed, but not 2.0x (too fast already) or just 1.0x (too slow imho). They don't care if the music and sounds get distorted, incl. me. 

### Expected behavior

Menu should allow to set in 0.1 bits until 3.0x

### Actual behavior

Menu allows only 1.0x fractions.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 6616b807ed (Apr 29 2023)

### Environment information

- OS: any

### Things I have considered

I edited the config, but this causes weird behaviors on Android, i.e. when restroring the config, because of any other change, it will be reset, I have to reedit again and reload again. I need to change Frame-Throttle too often, because sometimes I want it to run as fast as it's possible, so cfg-editing is a pain.

This is the last inconvenience for me when using RetroArch and I think it doesn't need to be the case. Right?

Keep goin' folks. Shall my spell motivate you.

**Comment by hizzlekizzle** [comment]
It's something we've discussed in the past but determined that it's niche enough that leaving it as config-only is preferred.

**Comment by atava** [comment]
If I can chime in, a more sensible option would be showing 0.1 ranges for low values (say from 1.0 to 2.0), then stepping by 0.5 for later values (2.0 to 4.0) and then by 1.0 for even higher values (5.0 to whatever).

This is one of those cases where the usefulness of a value decreases the more the value increases. Who would ever want so many choices for values above x3.0? (While so many users, actually the majority, would want to try x1.n speeds.)

Editing the config file is a less user-friendly option for Steam users like me (with Steam Cloud active etc), and in general forces one to reboot the app, if I'm not mistaken (so one cannot try the speeds live).

**Comment by willowilson44** [comment]
Strange decision. And I really doubt this is all that niche. Bizarre to not be able to choose even 1.5x, which bridges an enormous gap between 1x and 2x, yet 49x is there, which would probably be used once in the lifetime of our universe.

**Comment by hizzlekizzle** [comment]
I changed it to tick by 0.1 instead of 1.0 now, so you guys should be all set.
