### ISSUE TITLE
Feature request: Make thumbnails tied with ROMs by a different identifier than game name

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [libretro/RetroArch#15543]
Now, let's say I didn't like a ROM name (names like AdvanceWars (E) (En,Fr,De,Us,It) look pretty ugly to me) and renamed it

I wouldn't be able to properly match and download thumbnails anymore unless by manually renaming them and yadda yadda

Could you match thumbnails with something univocal? I'd suggest either tying them with the CRC32 hash OR keeping a sort of "realname" in the playlist metadata

**Comment by sonninnos** [comment]
Duplicate https://github.com/libretro/RetroArch/issues/10093

**Comment by TanyaEleventhGoddess** [comment]
> Duplicate #10093

Gotcha I'll close it myself

**Comment by TanyaEleventhGoddess** [comment]
> Duplicate #10093

Gotcha I'll close it myself
