### ISSUE TITLE
[Flatpak] udev as input driver doesn't work

### ISSUE THREAD

**Issue by matteodev8** [libretro/RetroArch#15560]
## Description

Installing the RetroArch flatpak and setting the input driver to udev will result in a non-working input.

### Expected behavior

Input in the menu should be working

### Actual behavior

Input does not work 

### Steps to reproduce the bug

1. Download & install the RetroArch flatpak
2. Set the input method to udev
3. Restart
4. See bug

### Bisect Results

Setting the input method to udev

### Version/Commit
1.15.0 (6616b80) Build Date May 16 2023

- RetroArch: [version/commit]

### Environment information

- OS: Ultramarine Linux 38 (based on Fedora 38) (`Linux bluewave 6.4.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 27 20:01:18 UTC 2023 x86_64 GNU/Linux`)
- Display server: X11
- Desktop environment: GNOME 44.3

---

![image](https://github.com/libretro/RetroArch/assets/59450459/f54c624f-1b5b-4f10-929e-52939ff87546)

I have already tried giving myself the `input` group and creating the udev rule under `/etc/udev/rules.d/99-evdev.rules`.
I also tried giving the flatpak more permission using Flatseal which didn't work either.

**Comment by gouchi** [comment]
Hi,

There is already an [issue opened](https://github.com/flathub/org.libretro.RetroArch/issues/194) in the dedicated repository.

So you should close this issue and continue the discussion there.

Thank  you.

**Comment by RobLoach** [comment]
Closing as a duplicate. Thanks for checking out the flatpak distribution! Would love more help in testing there, if you're up for it. Issues are over at https://github.com/flathub/org.libretro.RetroArch/issues .
