### ISSUE TITLE
(UWP) Checking Network Info Crashes the App

### ISSUE THREAD

**Issue by GABO1423** [libretro/RetroArch#15565]
## Description

On UWP Builds used on Xbox (not sure if this happens on Windows), trying to check the network information causes the app to crash. This was caused by commit https://github.com/libretro/RetroArch/commit/d7f2bd6ce7c1581c00a32416d55e639384c3cc0f.

Here's the call stack:

![image](https://github.com/libretro/RetroArch/assets/35014183/920826fc-d1d2-4725-8fe2-0972909f231c)

@sonninnos Does this tell you anything about a possible cause?

### Expected behavior

To be able to see my Network Information.

### Actual behavior

App crashes.

### Steps to reproduce the bug

1. Go to Main Menu > Information
2. Click Network Information
3. Bam, crash.

### Bisect Results

Commit (https://github.com/libretro/RetroArch/commit/d7f2bd6ce7c1581c00a32416d55e639384c3cc0f) caused this.

### Version/Commit

- RetroArch: 1.16.0/09e4719

### Environment information

- OS: Xbox Series X OS
- Compiler: MSVC (1937) 64-bit

**Comment by sonninnos** [comment]
Looks like it is a bad way of achieving the result then, even though "it works on my machine" ™️
