### ISSUE TITLE
[Bug] Hardcore Mode isn't paused offline

### ISSUE THREAD

**Issue by AltPlus30** [libretro/RetroArch#15574]
### Description

As the title says, Hardcore Mode doesn't turn itself off when you encounter a network error so rewind/savestates/cheats don't work until you disable HC in settings menu.

### Expected behavior

Automatically pause Hardcore Mode when there's no connection with RetroAchievements.

### Actual behavior

Achievements menu shows nothing but "Network error" or "Not logged in" so there's no button to pause Hardcore Mode. Not sure if the issue persists if a game doesn't have achievements at all.

### Steps to reproduce the bug

1. Enable Hardcore Mode
2. Lose internet connection
3. Try loading a savestate
4. Get an error saying Hardcore Mode is enabled
5. Go to Achievements menu to pause it
6. Get an empty list with no options

### Bisect Results

I guess it started happening with the latest update since it worked as expected in previous versions.

### Version/Commit

- RetroArch: 1.15.0

Environment information

- OS: Windows 7, Windows 10, PS Vita

**Comment by hizzlekizzle** [comment]
I believe this is intentional behavior. Otherwise, someone could just turn off their wifi, save/load states, then reconnect to earn the hardcore achievements, right?

**Comment by AltPlus30** [comment]
> I believe this is intentional behavior. Otherwise, someone could just turn off their wifi, save/load states, then reconnect to earn the hardcore achievements, right?

How would someone earn hardcore achievements if hardcore mode gets automatically paused for the while session when there's no connection?
Also, you can't earn most achievements for something you did in the past so loading a savestate won't help you at all (It wouldn't count)
Moreover, RA won't reconnect until you reset the game. It basically can't do so at runtime

**Comment by Jamiras** [comment]
Hardcore mode should be automatically disabled if we fail to find achievements for the loaded content. There's probably a whole in the logic for when a network error occurs. I don't think there have been any recent changes that would have caused this. Will investigate.
