### ISSUE TITLE
Retro VFS remove command fails to remove directory on Windows

### ISSUE THREAD

**Issue by bbbradsmith** [libretro/RetroArch#15578]
Though some standards dictate that `remove` should be equivalent to `unlink` on a file and `rmdir` on a directory, Microsoft's version of `remove` deliberately gives a permission error (EACCES) if you try it on a directory.

[Open Group standard](https://pubs.opengroup.org/onlinepubs/9699919799/functions/remove.html):
> If path does not name a directory, remove(path) shall be equivalent to unlink(path).
> If path names a directory, remove(path) shall be equivalent to rmdir(path).

[Microsoft standard](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/remove-wremove?view=msvc-170):
> Each of these functions returns 0 if the file is successfully deleted. Otherwise, it returns -1 and sets errno either to EACCES to indicate that the path specifies a read-only file, specifies a directory, or the file is open, or to ENOENT to indicate that the filename or path wasn't found.

Therefore in the current implementation of Libretro's virtual file system, `remove` cannot remove a directory in the Windows version.

I believe the relevant code is here: [libretro-common/vfs/vfs_implementation.c - line 739](https://github.com/libretro/RetroArch/blob/717f79773cd3e5f52ea1eb0bd936a849bf056d45/libretro-common/vfs/vfs_implementation.c#L739)

What the implementation should probably do is check if the path is a directory first, then either dispatch to [`_remove`/`_wremove`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/remove-wremove?view=msvc-170) as it currently does, or instead to [`_rmdir` / `_wrmdir`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/rmdir-wrmdir?view=msvc-170) in the case of the directory.

**Comment by LibretroAdmin** [comment]
Great catch, thanks for letting us know. Well, that certainly will complicate things in the code implementation.

**Comment by LibretroAdmin** [comment]
@bbbradsmith See if this addresses and resolves the issue -
https://github.com/libretro/RetroArch/commit/10c60cdd4d028c4433b8c7430dfd26dcac808ca5

**Comment by bbbradsmith** [comment]
That looks like a valid solution. I tried [this Windows-x64-MXE artifact](https://github.com/libretro/RetroArch/actions/runs/5915192300) and I was able to remove directories through the VFS.

**Comment by bbbradsmith** [comment]
Closing this because it was resolved in 10c60cd
