### ISSUE TITLE
[Linux ARM] No cores in buildbot since 2020-08-27

### ISSUE THREAD

**Issue by askotx** [libretro/RetroArch#15582]
## Description

Title said everything

### Expected behavior

[What you expected to happen]

No cores in buildbot

[What is actually happening]

You could check https://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest/

[Try to bisect and tell us when this started happening]

### Version/Commit

Last compiled cores are from  2020-08-27

- RetroArch: [version/commit]

### Environment information

- OS: Debian ARM

**Comment by hizzlekizzle** [comment]
Yes, we do not have any ARM runners on our buildbot and have not set up cross-compile environments. For now, this unofficial github repo is probably your best bet for getting cores for ARM: https://github.com/christianhaitian/retroarch-cores

**Comment by hizzlekizzle** [comment]
You can still use the 'install a core' routine, right? I *think* you can also use RetroArch as a 'storage provider' with a compatible file browser/manager app, such as FX (IIRC) to access its owned directories, including /data/data/com.retroarch/cores.

But yes, Google's "security" policies suck.

**Comment by askotx** [comment]
Thanks @hizzlekizzle getting a way to get cores for my old arm device it's enough!!

Closing.

**Comment by nerozzero5** [comment]
thanks , this post was useful for me ifound it from google
