### ISSUE TITLE
[Feature Request/iOS] Desmume Core Touch Screen Support For Mobile

### ISSUE THREAD

**Issue by schnedi** [libretro/RetroArch#1558]
I've had no luck in using any part of the touchscreen emulation the Desume core has available under OSX; any suggestions? 
Or if the iOS/Android ports just aren't working with any touch input.

Tested On IPhone 6 (unjalibroken) iOS 8.3 b3

**Comment by fr500** [comment]
I think this is a core issue so it should be opened in the core issue tracker
