### ISSUE TITLE
Remaps and Overrides menu - Small QoL additions

### ISSUE THREAD

**Issue by jayare5** [libretro/RetroArch#15591]
I don't know if it's planned but I would like to see some features in the Remap Files and Overrides menus, that already exist in the Shader menu, which feels really complete with all the saving and loading options! In particular I want see these added:

Remap:
- Save Remap File as...

Overrides:
- Save Overrides as...
- Save Content Directory Overrides (nevermind, already included)

With these additions, all 3 menus (remaps/overrides/shaders) would be fully consistent and powerful!
Thanks in advance. (And thank you so much to those of you who have added the options that have been added to these menus recently!!!)

**Comment by sonninnos** [comment]
Content dir override already exist though. Just missing that "save as".

**Comment by jayare5** [comment]
> Content dir override already exists though. Just missing that "save as".

My apologies, I accidentally had this hidden when I checked ...
Thanks!
