### ISSUE TITLE
[Android 13] Retroarch crashes when resuming application from background

### ISSUE THREAD

**Issue by SpagoAsparago** [libretro/RetroArch#15628]
## Description

Running the latest nightly build on a OPPO A76, OS is Android 13.0:
When exiting the application without closing it trough either the home button or the recent apps button, once the application is reopened it will always crash, regardless of core loaded

### Expected behavior

From my experience on different Android systems, the application should resume correctly once reopened

### Actual behavior

Freeze of 1-2 seconds followed by crash to home screen

### Steps to reproduce the bug

1.Launch Retroarch
2.Press the home button
3.Launch Retroarch again 

### Version

- RetroArch: 1.16.0

### Environment information

- OS: Android 13.0, Device: OPPO A76
- Compiler: [In case you are running local builds]

**Comment by Jamiras** [comment]
Probably a duplicate of #14209.

Can you verify that threaded video is on, and the problem is fixed when disabling threaded video?

**Comment by SpagoAsparago** [comment]
Can confirm that disabling threaded video solves the issue, thanks
