### ISSUE TITLE
[Android] Gyro causes netplay activation

### ISSUE THREAD

**Issue by VoSed** [libretro/RetroArch#15626]
## Description
Tilting or rotating the device activates netplay

### Expected behavior

Tilting does nothing unexpected

### Actual behavior

Tilting or rotating the device activates netplay

### Steps to reproduce the bug

1. Launch RetroArch
2. Tilt or rotate the device

### Bisect Results

I encountered this problem back as soon as I first installed RetroArch on the device. I thought software updates would fix it. But they didn't

### Version/Commit

- RetroArch: 1.14 / 1.15 / 1.16_GIT

### Environment information

- OS: Android 13
- Device: Nokia G50 (TA-1361)

**Comment by ichijiyujin** [comment]
I have the same issue on the same device and Android version, RetroArch 1.20. 

After looking around, I've found that other phones have a similar issue but connected to the fingerprint sensor. The explanation I found in that case is that the fingerprint sensor "sends "unknown" or rather null key, which means it presses all hotkeys that are bound to nothing, as in "unknown" key". It seems the same thing happens for our device for the gyroscope. 

As a workaround, I managed to connect a keyboard via USB OTG and remap every unmapped hotkey and RetroPad bind to a key on the physical keyboard (I used divide key on numpad). I haven't done extensive testing with this workaround, but it seems to work ok for now. Hope this helps.

**Comment by mdemoss** [comment]
I see this issue with the fingerprint reader in 1.16.0 too. When my finger brushes against the reader on the back of the phone I see a message about the keyboard overlay, it toggles the display of technical statistics, and there is the netplay message. On IRC I was told that there had previously been an issue on windows where it would "fire all unassigned hotkeys if unknown device inputs were triggered" and that seems exactly what's happening here.

**Comment by mdemoss** [comment]
`HOTKEY_CHECK` and `HOTKEY_CHECK3` macros may need review.

**Comment by sonninnos** [comment]
Very much related: https://github.com/libretro/RetroArch/issues/10071

**Comment by mdemoss** [comment]
Tried the nightly build, can confirm it fixed the problem with the rear fingerprint reader triggering all unbound hotkeys.
