### ISSUE TITLE
Some keys don't work (depends on driver)

### ISSUE THREAD

**Issue by nicobat87** [libretro/RetroArch#15648]
OS Windows 10
RetroArch 1.15.0

Like ([15513](https://github.com/libretro/RetroArch/issues/15513)), some keys are not functionals.

With dinput/sdl2:
tilde
equals
leftbracket
rightbricket
quote
backslash
oem102
ralt (return: ctrl)
print_screen (no return)

With dinput/raw/sdl2:
function/menu (no return)
see https://en.wikipedia.org/wiki/Menu_key

**Comment by sonninnos** [comment]
All of those keys working here with all of those drivers on Windows 10..

**Comment by nicobat87** [comment]
Sorry, not on my computer. If I map this keys with Show FPS (toggle) they doesn't dispay the FPS.
tilde
equals
leftbracket
rightbricket
quote
backslash
oem102
ralt (return: ctrl)

print_screen & function/menu are not recognize (except print_screen with raw driver).

**Comment by sonninnos** [comment]
No issues doing that either here with any keys and driver.

Impossible to guess what might be wrong without a log, and probably still impossible with a log.

**Comment by nicobat87** [comment]
Ok, to bad for me. Thanks for your attention.
