### ISSUE TITLE
 Retroarch With Sound Problem On ps2

### ISSUE THREAD

**Issue by Renner15032000** [libretro/RetroArch#15655]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[after some system update, I don't know when I did this update, the retroarch no longer had the audio working, I already updated until the August 21st version but nothing caused the problem to be corrected.]

### Expected behavior

[hopefully the issue will be fixed in a new update.]

### Actual behavior

[after some system update, I don't know when I did this update, the retroarch no longer had the audio working, I already updated until the August 21st version but nothing caused the problem to be corrected.]

### Steps to reproduce the bug

1. [open a game with a core]
2. [after the game is opened right away you can see that the game is without sound.]

### Bisect Results

[about 2 3 weeks ago.]

### Version/Commit
Retroarch version: 1.16.0
Build date: AUG 21 2023
Compiler: GCC (11.3.0) 32-bit
CPU Features: VFPU
CPU Architeture: MIPS
CPU Cores: 1 

- RetroArch: [version/commit]

### Environment information

- OS: [Ps2 Slim series: 90000]
- Compiler: [GCC (11.3.0) 32-bit]

**Comment by zoltanvb** [comment]
Thanks for reporting this, fix is being submitted.
