### ISSUE TITLE
Conflicting keys when entering menu (ignore entering button)

### ISSUE THREAD

**Issue by BlueMax** [libretro/RetroArch#15659]
## Description
When entering the **menu** with L2 (user-defined) the cursor also jumps to next alphabetical entry. This is caused by conflicting key binding. L2 is **jump to next alphabetical entry** and **enter menu** in this case.

### Expected behavior
The menu should **ignore this L2 button press** and keep the cursor at the same position. 

Either add an option to disable/remap internal Lx/Rx navigation buttons or give it some kind of intelligent approach like ignoring input commands for a short time when entering menu to prevent this issue.

### Version/Commit
- RetroArch: 1.15.0 / 6616b807ed
- OS: Arch Linux 6.4.12
- Compiler: GCC 13.1.1

**Comment by sonninnos** [comment]
Already fixed in https://github.com/libretro/RetroArch/pull/15646

**Comment by BlueMax** [comment]
Confirmed. Works on 078df8ba39.

Thanks!
