### ISSUE TITLE
BUG: Going in, out fullscreen crashes RetroArch

### ISSUE THREAD

**Issue by ZHassanQ** [libretro/RetroArch#15661]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
    - i don't know if it's a RetroArch bug or a Core bug.
- This is not a forum or a help section, this is strictly developer oriented.

## Description

[Going in or out of fullscreen while playing PSP game, crashes RetroArch.]

### Expected behavior

[Normally exit or enter fullscreen]

### Actual behavior

[When going in, or out fullscreen while playing a PSP game. RetroArch crashes.]

### Steps to reproduce the bug

[I don't know how or why.]

### Bisect Results

[When playing with PSP games.]

### Version/Commit

- RetroArch: [The latest from Steam]

### Environment information

- OS: [Windows10]
- Compiler: [NO]

**Comment by sonninnos** [comment]
Well if it only happens with this core, then it most likely is a core issue. So far indeed no other core does this on my machine. Vulkan and d3d11 just crash at once when toggling fullscreen, glcore does not crash but loses image forever.

**Comment by ZHassanQ** [comment]
> Well if it only happens with this core, then it most likely is a core issue. So far indeed no other core does this on my machine. Vulkan and d3d11 just crash at once when toggling fullscreen, glcore does not crash but loses image forever.
> 
> 

Thanks for your help. I will close this issue since it's most likely a core issue. And this repository is only for RetroArch.
