### ISSUE TITLE
[1.15.0] Playlist Thumbnail Updater super slow / stuck

### ISSUE THREAD

**Issue by d-apps** [libretro/RetroArch#15660]
## Description

When I use the Playlist Thumbnail Updater to scrap my roms, it is super slow and it gets stuck in 0% or 1%, I already scrapped this same roms before and it always scraped fine but I don't have a backup of these thumbnails.

### Expected behavior

The Updater be faster like before.

### Steps to reproduce the bug

1. Open Online Updater
2. Open Playlist Thumbnail Updater
3. Try to scrap some system.

- RetroArch: 1.15.0 / commit: 1581ece

### Environment information

- OS: Windows 10
- Compiler:

**Comment by sonninnos** [comment]
Server issues are not code issues, and especially not ~6 month old code issues.

**Comment by d-apps** [comment]
> Server issues are not code issues, and especially not ~6 month old code issues.

But is there another place to report server issues? or nobody can check server issues?

Anyway, for those who have this issue, this beautiful soul uploaded to github and we can download there:

https://github.com/libretro-thumbnails/libretro-thumbnails

**Comment by RobLoach** [comment]
We're aware that the server is not up. Looking into it. They're still available outside of RetroArch via github luckily. Stay tuned.
