### ISSUE TITLE
[Android] [BUG] 4:3 screen touch control issue

### ISSUE THREAD

**Issue by zzedmore** [libretro/RetroArch#15672]
I'm using a handheld device with a 4:3 screen. I recently updated Retroarch and now i'm getting weird issues with the overlay. I am using an invisible overlay that has a pause section (because this issue https://github.com/libretro/RetroArch/issues/14200 still hasn't been fixed). Before the update it worked fine but now i've updated Retroarch it sort of works but if I go to the Retroarch menu then back to game, the overlay completely stops working !? I have also tried with a fresh Retroarch.cfg and it does the same thing.

I tried the PUAE Amiga emulator and it also seems to make the mouse jump a bit when I touch the screen like it's always starting from the same point.

**Comment by zzedmore** [comment]
It's nothing to do with overlays it seems. It happens on the Retroarch menu too. If I scroll my finger up the screen, the Retroarch menu jumps down first everytime I touch the screen. When pressing an overlay control it seems to stick like it's holding the button. This happens from a fresh new retroarch.cfg. This only happened when I updated to the latest nightly.

**Comment by zzedmore** [comment]
Any help with this please ? I can't remember the version of Retroarch Nightly I had previously that didn't have this issue (maybe a month ago). The nightlies only go back to 23 August (which also has the touch scrolling problem). The latest stable version works fine. Is there a way to download Android nightlies before 23 August or maybe fix the issue ?

**Comment by zzedmore** [comment]
@LibretroAdmin Please could you help me with this ? Retroarch on Android is broken for me. It feels like it may be something to do with Touch Scale. I've tried a new retroarch.cfg and it happens. The latest stable works fine and a Nightly from a couple of months ago worked but I no longer have it and there's no way to download it.

**Comment by zzedmore** [comment]
https://github.com/libretro/RetroArch/assets/79696530/e5245310-762b-45ba-bfba-7f9a40b1a403

**Comment by starjunn99** [comment]
Seems like this is not a samsung exclusive issue , still exist almost a year not fixed please help

here list of same issues with different phone and tablet models this issue starts with 1.16.0

https://www.reddit.com/r/RetroArch/comments/1clj6va/android_app_unusable_starts_completely_frozen/
https://www.reddit.com/r/RetroArch/comments/16tuahr/pressing_touch_screen_in_my_phone_not_working/
https://www.reddit.com/r/RetroArch/comments/16x6uqt/after_updating_to_1160_touch_navigation_on/
https://www.reddit.com/r/RetroArch/comments/1773tcj/touchscreen_not_working_on_a_fire_8_plus/

**Comment by arnaullv** [comment]
This commit broke the touchpad input, see https://github.com/libretro/RetroArch/issues/15757

It has been already reverted, check latest nightly

https://github.com/libretro/RetroArch/commit/abcd42777f7c17559cf6eb509dc86aca63e48527 refactor: rewrite input handling to better support AINPUT_SOURCE_STYLUS (https://github.com/libretro/RetroArch/pull/15597)

**Comment by zzedmore** [comment]
Confirmed fixed, only took 9 months!
