### ISSUE TITLE
[Feature Request] Increase maximum FPS value on "PAL Threshold" option

### ISSUE THREAD

**Issue by DaniloPMiguel** [libretro/RetroArch#15671]
Hello, first i apologize if this is not the correct place for this. 

I would like to ask if it's possible to increase the max FPS value from "56" to "60" on the "PAL Threshold" option (added at commit ab1e5c3), so only games that runs above 60Hz would have their speed adjusted (Ex. Donkey Kong and Namco arcade games that runs at 60.60Hz and Crystal Castles which runs at 61.01Hz), without affecting others that runs below 60Hz (Ex. Neo-Geo games that runs at 59.18Hz, Chain Reaction/Magical Drop at 58Hz, Space Invaders at 59.54Hz, Cool Riders at 57Hz and many other games that are having a little boost on framerate).

Sorry for the poor english and thank you for taking the time to read this.

### Version/Commit

 RetroArch 1.16.0/83ae187

### Environment information

- OS: Microsoft Windows 7 Home Basic SP1 x64

**Comment by sonninnos** [comment]
Are you absolutely sure you want the display to switch to 50hz even with 60hz content..? This option does not adjust any speeds, but simply decides whether to switch to 50hz or 60hz, since there is no in-between values in TV-standard land.

**Comment by DaniloPMiguel** [comment]
Sorry, i misinterpreted the description of the commit, please close this issue. Thanks for answering.
