### ISSUE TITLE
Shader pipeline effect looks worse than before in xmb menu

### ISSUE THREAD

**Issue by KamiLordus** [libretro/RetroArch#15682]
Hi. I am using xmb menu, along with shader pipeline - ribbon.
I noticed that this effect is much less noticeable than before.
Previously, the effect was more visible and blended less with the background (more white color?).
I also tried other backgrounds (gray for example) and it's the same problem.
P.s. I'm not 100% sure but I think the background color has also changed.

This is what it looks like now
![2](https://github.com/libretro/RetroArch/assets/123302593/8656416e-4e85-45c6-b763-943bf64a317b)

And this is what it looked like before
![1](https://github.com/libretro/RetroArch/assets/123302593/acc0e3e2-abe0-45c0-99c8-6db78fbea2c4)

RA 1.16 ca7231f
Win 11
Rtx 3070ti

**Comment by gouchi** [comment]
Yes it's normal, there's been a change recently.

>Changed ribbon blending mode to be a bit more subtle so that "Color Theme Alpha Factor" matters also to it

[Source](https://github.com/libretro/RetroArch/pull/15556)

**Comment by KamiLordus** [comment]
But why? Previously it looked much better in my opinion.

**Comment by sonninnos** [comment]
Well this new one looks better for me.. It also makes text less unreadable when overlapping with the effect.

**Comment by hizzlekizzle** [comment]
Wasn't there a way to make it look the same by adjusting the background alpha value or something like that?

**Comment by sonninnos** [comment]
No. Nothing made any difference to the effect.

**Comment by KamiLordus** [comment]
Okay, let's close this. Maybe I look at it too often :)

**Comment by KamiLordus** [comment]
I noticed one more problem when it comes to the background shade.
After turning off the game and returning to the retroarch menu, you can clearly see vertical cuts on both sides of the screen (the background shade).
![Zrzut ekranu 2023-09-10 205252](https://github.com/libretro/RetroArch/assets/123302593/c980a531-3432-4f28-b5e9-cc7744030dbb)
