### ISSUE TITLE
[BUG] Load core option

### ISSUE THREAD

**Issue by KamiLordus** [libretro/RetroArch#15697]
After loading/closing the game, the "Load Core" option is no longer available. Only restarting Retroarch restores the option.

![Zrzut ekranu 2023-09-13 224641](https://github.com/libretro/RetroArch/assets/123302593/f0d59f1a-42f5-4596-a59d-848d2142d57b)

XMB menu
Os - Win 11
RA 1.16 ca7231f

**Comment by sonninnos** [comment]
This is happening because for some reason after core is uninited and `RUNLOOP_FLAG_CORE_RUNNING` is cleared, runloop is run once more in core mode instead of menu mode, which sets the flag back..

**Comment by KamiLordus** [comment]
Now it works without any problem. Thank you.
