### ISSUE TITLE
No pictures

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [libretro/RetroArch#15706]
I add more games to my collection, I scan them, RetroArch recognizes them, but I’m unable to get the pictures for the box art and gameplay.
![IMG_0272](https://github.com/libretro/RetroArch/assets/79031143/d5c4bc8c-732d-4e58-8db4-c499a3f0a6c0)

**Comment by Metal-Snake** [comment]
Same problem here on stable RA 1.15.0 macOS 13.5.2

**Comment by sonninnos** [comment]
Server issues affect every version and platform.

**Comment by Metal-Snake** [comment]
Images are loading now. Thanks!
