### ISSUE TITLE
Is buildbot build for 1.16 compromised?

### ISSUE THREAD

**Issue by seanat280** [libretro/RetroArch#15714]
## Description

As of yesterday afternoon, release 1.16 was published to the Winget registry with a download link of https://buildbot.libretro.com/stable/1.16.0/windows/x86_64/RetroArch-Win64-setup.exe (Don't click).  This setup.exe appears to be infected with the Wacatac malware.  As as far as I can tell 1.16 isn't even formally released yet, so it seems odd that it would even be registered in Winget or hosted on buildbot.

Maybe this is all just a false positive on my machine, but just wanted to raise the issue just in case.

**Comment by hizzlekizzle** [comment]
Just a false-positive, yeah. The release is imminent, and the version number has been bumped in the source code for a couple of weeks now.
