### ISSUE TITLE
[3DS BUG] paused games continue to try and play audio

### ISSUE THREAD

**Issue by Trickiy** [libretro/RetroArch#15711]
When I tap the bottom screen to pause the game with audio playing the audio will stutter the last second of sound endlessly. I think just muting audio when bottom screen is tapped would fix the issue and pls fix this bug it is so annoying.

**Comment by Maesejesus** [comment]
Yes, I have tried the current one and happens on every core I tried. 
This did not happen on the previous version. I'll roll back to the previous release in the meanwhile...

**Comment by dmaglio** [comment]
> Yes, I have tried the current one and happens on every core I tried. This did not happen on the previous version. I'll roll back to the previous release in the meanwhile...

which version? with 1.16.0 i have the same bug

**Comment by Maesejesus** [comment]
Sorry, I did not see the response.

I've been using cores from 2023-03-17, so I guess 1.15. You can download them here: 
https://buildbot.libretro.com/stable/1.15.0/nintendo/

**Comment by Trickygamers** [comment]
thanks but the issue existed in 1.15 as well and sorry for the really late reply.

**Comment by Anonymous941** [comment]
Should I preform regression testing on this?

**Comment by sonninnos** [comment]
Enabling menu sounds mixer even without any specific sounds should work as a band-aid for the time being.

**Comment by Anonymous941** [comment]
@sonninnos Thank you so much for fixing this!  I've been annoyed with this for so long, and `ozone` isn't available for the 3DS so I couldn't even enable mixer sounds

**Comment by sonninnos** [comment]
Good that it solved it, but menu sounds are completely menu driver agnostic. The option not being there therefore has nothing to do with the menu driver itself.

**Comment by Anonymous941** [comment]
Is this a bug or is there some reason for it being disabled on CTR?

**Comment by sonninnos** [comment]
A quick glance at `Makefile.ctr` looks like `HAVE_AUDIOMIXER` is accidentally not included in griffin build, since it is there in non-griffin build.. And not having that flag should be the only reason why menu sounds are not included, along with other audio mixer related features.

Perhaps someone knows better, and perhaps it is not enabled on purpose.

**Comment by Anonymous941** [comment]
I'll try to compile it and see if there are any adverse effects

**Comment by Ninoh-FOX** [comment]
the fixed break the audio drivers with the fuction RARCH_NETPLAY_CTL_USE_CORE_PACKET_INTERFACE

**Comment by FayeReagan** [comment]
This issue happens again in stable version 1.21.0
Band-aid fix by enabling mixer just like sonninnos said is working

**Comment by causalmask** [comment]
I just upgraded to 1.21.0 from 1.19.1 and am still experiencing this issue.  When using retroarch emulation pause, the last couple hundred milliseconds of audio loop endlessly.  For some reason, the workaround of enabling the Menu Sounds Mixer doesn't work for me.
