### ISSUE TITLE
Abysmal DS performance S22

### ISSUE THREAD

**Issue by UnveilingCoyote** [libretro/RetroArch#15715]
Nintendo DS games won't keep steady 60fps on S22
There are frequent frame drops during gameplay

**Comment by hizzlekizzle** [comment]
This is not a bug, but even if it were, it'd be a core bug, not a frontend bug. Also, as an aside, the issue template is there for a reason, so deleting it won't make anyone want to address your problem.

**Comment by UnveilingCoyote** [comment]
Jeez, I didn't expect that kind of answer, I am not an advanced user

**Comment by hizzlekizzle** [comment]
I wasn't trying to jump down your throat or anything. We have a lot of different ways to get more casual tech support (forum, discord, reddit, IRC) but the issue tracker here is intended for developer attention for actual bug reports, and that's stated at the start of the issue template.
