### ISSUE TITLE
Technical Statistics are broken in native AppleSilicon

### ISSUE THREAD

**Issue by Metal-Snake** [libretro/RetroArch#15726]
## Description

The technical statistics display is all squashed to the left side when using native AppleSilicon.
When the "open with Rosetta" setting in the Finder info is checked it shows up fine.

### Expected behavior

should look like this (taken with the "open with Rosetta" option:
<img width="2560" alt="Bildschirmfoto 2023-09-23 um 09 38 11" src="https://github.com/libretro/RetroArch/assets/898220/645ffcc6-d858-4d9e-a6b5-46c888ecd8a8">

### Actual behavior

looks like this (only few pixels on the very left are visible)
<img width="2560" alt="Bildschirmfoto 2023-09-23 um 09 37 45" src="https://github.com/libretro/RetroArch/assets/898220/7152f2c0-d084-40f0-b5bc-8719f72d5a0e">

### Steps to reproduce the bug

1. Open RetroArch on an AppleSilicon Mac
2. Display Statistics (might need to start a game or restart RetroArch if it wasn't on)
3. Quit RetroArch
4. Set the option to run RetroArch using Rosetta (in the Finder info window)
5. Start RetroArch and see correct technical statistics

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.15 Stable
- Build Date: Mar 11 2023
- Git Version: GIT_VERSION 

### Environment information

- OS: macOS 13.5.2
- MacBook Air M1

**Comment by sonninnos** [comment]
This has been fixed ages ago. Please use the current version.

**Comment by Metal-Snake** [comment]
huh? 1.15.0 is the current version.

**Comment by sonninnos** [comment]
Nightly is the current version, and also 1.16.0 is the current version.

**Comment by Metal-Snake** [comment]
oh lol, the news didn't arrive everywhere, like github
I checked the blog last night and the last post was a few months old. 
Now there is a new version. :D 

<img width="182" alt="Bildschirmfoto 2023-09-23 um 11 27 41" src="https://github.com/libretro/RetroArch/assets/898220/02eb36cc-8857-4558-802f-392bbf81ee47">
