### ISSUE TITLE
"rgui_browser_directory" Config Value Should be Renamed and Moved Out of rgui ifdef

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#15728]
"rgui_browser_directory" is a menu agnostic config value that saves the File Browser's default directory. It should be renamed "file_browser_directory" to match what it's called in the GUI.

Also, it was moved under an rgui ifdef in commit 34b71339dea032bb3d0fd5f23339be595b05052e so if you compile RetroArch with "./configure --disable-rgui" the value isn't read or written to the config file.

**Comment by zoltanvb** [comment]
Good catch, thank you! Renaming a config file entry is complicated business, but rest of the code already uses directory_menu_content (and directory_menu_config), so this confusion is not likely to occur elsewhere in RA codebase.

**Comment by Awakened0** [comment]
Thanks!

**Comment by i30817** [comment]
Did you change the config key name? Just asking to check if I have to refactor projects that use the config file to check that value.

**Comment by sonninnos** [comment]
The commit clearly moves only one `#endif` around.

**Comment by i30817** [comment]
I was lazy. Ok.
