### ISSUE TITLE
Remap 

### ISSUE THREAD

**Issue by Dako9767845** [libretro/RetroArch#15736]
I Just reinstalled RetroArch and immediately tried to remap my controls but it's not cooperating. my keyboard works fine and my Dualshock 4 works fine as well. 

RetroArch: 1.16.0

system:

![Capture](https://github.com/libretro/RetroArch/assets/102679943/1318ec9c-34ed-42b9-9fd6-6b09ddf33c33)

**Comment by Dako9767845** [comment]
I've downgraded to version 1,15,0.

**Comment by sonninnos** [comment]
How is that a solution, and why even need to remap anything at first, and what does "not cooperating" means?

**Comment by Dako9767845** [comment]
1. it lets me remap my controls of a simple button, but 1.16.0 I can't. 

2. Because I wanted to get comfortable with my play style

**Comment by sonninnos** [comment]
Weird since no one else hasn't complained, and I can still remap just like always.
