### ISSUE TITLE
[3DS BUG] most rom hacks are skipped after import content scan

### ISSUE THREAD

**Issue by Trickygamers** [libretro/RetroArch#15734]
when I try to import the rom hacks they are just ignored. I think a way to fix this is to put the roms in manually into the playlist of choice and or manually make a new playlist dedicated to the hacks.

**Comment by hizzlekizzle** [comment]
This isn't a bug; it's working as intended. See this entry from our FAQ on r/RetroArch for more details: https://www.reddit.com/r/RetroArch/comments/15c5qfn/comment/jtuagcr/?context=3

**Comment by Trickygamers** [comment]
Oh ok still is annoying though.

**Comment by Trickygamers** [comment]
oh ok didn't know also there needs to be a toggle to remove the database check

**Comment by hizzlekizzle** [comment]
That's essentially what the manual scan is/does.
