### ISSUE TITLE
Unable to use gamepad 2 without connecting gamepad 1 first (Xbox Series Controller)

### ISSUE THREAD

**Issue by phantomsixthplayer** [libretro/RetroArch#15732]
## Description
I use two Controller (Xbox One For Windows) connected via the Xbox Wireless Adapter for Windows. The issue I am experiencing is that when connecting gamepad 1 first then gamepad 2 and if gamepad 1 disconnects (sleep/suspend) gamepad 2 will get the Instance Guid of gamepad 1 and this will cause gamepad 2 to not work in RetroArch. The solution is to turn gamepad 1 back on.

I tried to find a unique identifier for the gamepads to resolve the issue outside of RetroArch by using the Instance Guid. However, gamepad 1 will always be {170c5400-59e9-11ee-8001-444553540000} and then the gamepad 2 {55ae4380-59e9-11ee-8001-444553540000} with the Xbox Wireless Adapter for Windows. So when gamepad 1 disconnects the Instance Guid of gamepad 2 will become the Instance Guid of gamepad 1 and won't work in RetroArch unless you turn gamepad 1 back on.

I then tried to utilise the Device Instance Path however, the values after HID\VID_045E&PID_0B12&IG_00\<Id> are not unique and change constantly.

```
Xbox Wireless Adapter for Windows 10:
  Display Name: Xbox Wireless Adapter for Windows
  Device Instance Path: USB\VID_045E&PID_02FE\200142
  Driver Version: 1.0.46.1

Gamepad 1:
  Model No: 1914 (QAS-00003) - Xbox Wireless Controller - Robot White
  Display Name: XINPUT compatible HID device
  Device Instance Path: HID\VID_045E&PID_0B12&IG_00\7&1E02870D&10&0000
  Driver Version: 10.0.19041.3031
  Joystick Id: 0
  Product Name: Controller (Xbox One For Windows)
  Instance Guid: {170c5400-59e9-11ee-8001-444553540000}
  Vendor Id: 1118
  Product Id: 2834

Gamepad 2:
  Model No: 1914 (QAS-00003) - Xbox Wireless Controller - Robot White
  Display Name: XINPUT compatible HID device
  Device Instance Path: HID\VID_045E&PID_0B12&IG_00\7&3A2C557E&E&0000
  Driver Version: 10.0.19041.3031
  Joystick Id: 1
  Product Name: Controller (Xbox One For Windows)
  Instance Guid: {55ae4380-59e9-11ee-8001-444553540000}
  Vendor Id: 1118
  Product Id: 2834
```

### Expected behavior
If you turn off gamepad 1 (Port 1 Controls), then gamepad 2 (Port 2 Controls) should still work without having to turn on gamepad 1 again.

### Actual behavior
If you have both gamepads connected, then gamepad 1 (Port 1 Controls) disconnects (sleep/suspend/turned off to save battery), then gamepad 2 (Port 2 Controls) won't work unless you turn gamepad 1 back on.

### Steps to reproduce the bug
1. retroarch.cfg is set as input_player1_joypad_index = "0" and input_player2_joypad_index = "1"
2. Connect gamepad 1 (Port 1 Controls) then gamepad 2 (Port 2 Controls)
3. RetroArch menu says Port 1 Controls is "Xbox Series Controller (1)" and Port 2 Controls is "Xbox Series Controller (2)"
4. Disconnect gamepad 1 "Xbox Series Controller (1)". Now gamepad 2 becomes "Xbox Series Controller" under Port 1 Controls and does not work
5. Solution, turn gamepad 1 back on

### Bisect Results
Unknown

### Version/Commit
You can find this information under Information/System Information
RetroArch Version: 1.16.0
Git Version: 041ae30

### Environment information
```
Edition: Windows 10 Pro
Version: 22H2
Installed on: 9/‎01/‎2022
OS build: 19045.3448
Experience: Windows Feature Experience Pack 1000.19044.1000.0
```

**Comment by FishOrBear** [comment]
I guess I encountered the same problem.
I use moonlight, but when the moonlight is disconnected, the gamepad is lost, causing the RA controller to become unusable.

**Comment by FishOrBear** [comment]
@sonninnos
https://github.com/libretro/RetroArch/pull/14691
I saw there is a similar PR, can you fix this problem

**Comment by FishOrBear** [comment]
I have fixed this BUG 
https://github.com/libretro/RetroArch/pull/15819
