### ISSUE TITLE
XMB Background Has Shader Effects Applied to it if Shader is Enabled at Startup

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#1573]
If you have a shader enabled at startup (video_shader_enable = "true"), it affects how the XMB background image looks. I use a black background with alpha transparency so I can see the game behind the UI, but it just shows up as pure black. If I use the default red background, it appears to have the shader's effects applied to it. So with crt-easymode it looks like this: 

![0001](https://cloud.githubusercontent.com/assets/4565863/6974913/b3a2216e-d964-11e4-9c31-b25d47f16f50.png)

Turning off the shader enable setting in my config fixes it.

**Comment by Kivutar** [comment]
This should be fix now, can you check please? and close if it's fixed?

**Comment by Awakened0** [comment]
Forgot I had opened this, it's been fixed for a while.
