### ISSUE TITLE
[BUG] Joystick input is immediately remapped to D-pad in v1.16 (Switch Pro Controller)

### ISSUE THREAD

**Issue by djinnalexio** [libretro/RetroArch#15743]
## Description

Since updating to v1.16, the D-pad on my controller stopped working. The left stick now acts as the D-pad like with the analog to digital mode with the actual D-pad not doing anything both in-game and in the Retroarch menu. It's especially noticeable on platforms that use both stick and D-pad where the left stick instead of controlling player motion is activating whatever the D-pad is used for, leaving no way to move too.

I first checked the `input_player1_analog_dpad_mode` variable and it was still set to `0` both in main and core settings. I then looked at the mapping and noticed that the D-pad was mapped to axis 0 and 1 (left stick) instead of 4 and 5 (controller D-pad). I tried to correct it but as soon as I used the left stick to move down the menu, I could see the values change back to 0 and 1. Each time I make the D-pad work again, It immediately reverts the moment I move the stick.

I'm on Fedora Silverblue. I use the package from Flathub with a wired PowerA Switch Controller. 

### Expected behavior

When setting controller mapping, it stays as I configured.

### Actual behavior

After setting controls, the left stick is assigned to D-pad buttons, leaving the physical D-pad unassigned. Also, the left stick is not being used for its purpose.

### Steps to reproduce the bug

1. Update to Retroarch v1.16
2. Go to driver settings and set the controller driver to `linuxraw`
3. Go to input settings and set controls for the controller
4. Move around with the D-pad, then the left stick, then the D-pad again. You'll notice that it no longer works and its options have been remapped to the left stick.

### Bisect Results

I noticed the problem after the update to v1.16. Reverting back to v1.15 fixed it. I've been using `linuxraw` because half of the buttons are not recognized with `sdl2` which is a separate issue.

### Version/Commit

- RetroArch: v1.15.0 from Flathub
- Git commit:`041ae30`

### Environment information

- OS: Fedora 38 Silverblue
- Windowing System: Wayland
- Desktop Environment: Gnome 44.5
- Controller: USB wired PowerA Enhanced Nintendo Switch Controller Wired Spectra

**Comment by hizzlekizzle** [comment]
Could be related to changes to the autoconfig profiles to coincide with the 'nintendo-hid' kernel driver changes: https://github.com/libretro/retroarch-joypad-autoconfig/commit/b6e0a288b13faeed07538796253b12dddff1817b
