### ISSUE TITLE
(Documentation) Add list of cores supported by iOS

### ISSUE THREAD

**Issue by nighto** [libretro/RetroArch#15750]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The page [LibRetro Docs - Downloading, Installing and Running RetroArch for iOS and tvOS devices](https://docs.libretro.com/guides/install-ios/) state that "You cannot add or update cores after installation as they are signed executables and can only be updated by updating and resigning the entire application. The IPA files linked above contain all of the available iOS/tvOS cores.". I think it would be helpful adding a list of what cores are included on the IPA files.

**Comment by hizzlekizzle** [comment]
The problem with adding static lists like that is they inevitably fall out of date. We could potentially add a link to the buildbot page that has all of the iOS core builds, like this: http://buildbot.libretro.com/nightly/apple/ios/latest/

**Comment by nighto** [comment]
I think that's a good idea, something like "you can check the cores available here" with the mentioned link.

**Comment by RobLoach** [comment]
Docs are over at https://github.com/libretro/docs/ ... Feel free to make a pull request for suggestions :+1:

**Comment by nighto** [comment]
Created PR: https://github.com/libretro/docs/pull/880
