### ISSUE TITLE
RetroArch 1.16...and 2 errors

### ISSUE THREAD

**Issue by zibijani** [libretro/RetroArch#15753]
- When you press (Pause)-> (P key) a white screen appears instead of the stopped game!
- When you press (minimize) from the title bar, it doesn't minimize just shuts down RetroArch!

System: XP
Tested on core: sega genesis

**Comment by RobLoach** [comment]
Use the issue template, and submit logs https://docs.libretro.com/guides/generating-retroarch-logs/
