### ISSUE TITLE
Retroarch doesn't work well in Wayland

### ISSUE THREAD

**Issue by TAforever** [libretro/RetroArch#15760]
For some time now there have been problems with the work of retroarch in wayland, namely: the ozone theme breaks and many shaders do not work. Tested in sway and hyprland.

OS: archlinux
retroarch version: 1.15

![retroarch_wayland](https://github.com/libretro/RetroArch/assets/52626363/0d3f7dc6-4544-43f8-b24d-6fbc7abf5c8e)

**Comment by gouchi** [comment]
Will it possible to provide some [log](https://docs.libretro.com/guides/generating-retroarch-logs/) to have some information about which video driver you are using ?

Also steps to reproduce your issue.

When [Archlinux provides RA 1.16.0.3](https://archlinux.org/packages/extra/x86_64/retroarch/), can you make some new test ? Or if you can using latest commit ?

**Comment by TAforever** [comment]
I tried retroarch master and the result was the same
[retroarch.log](https://github.com/libretro/RetroArch/files/12782549/retroarch.log)
[retroarch2.log](https://github.com/libretro/RetroArch/files/12782551/retroarch2.log)

**Comment by TAforever** [comment]
Regarding the video driver, I use amdgpu and vulkan-radeon, I also tried amdvlk, the result is the same

**Comment by TAforever** [comment]
@gouchi The problem is very strange, I rolled back the system, tried the default config and even created a new user, no changes. I would be grateful to you sir if you could point out the source of the problem.

**Comment by TAforever** [comment]
I figured out the problem was in the libdecor package

**Comment by nfp0** [comment]
@TAforever The weirdness is probably being caused by this issue:
https://github.com/libretro/RetroArch/issues/15756

It ruins the config file.
We have also just arrived at the conclusion that it's libdecor.

**Comment by nfp0** [comment]
This issue has now been fixed on libdecor with this Merge Request:
https://gitlab.freedesktop.org/libdecor/libdecor/-/merge_requests/132
