### ISSUE TITLE
[BUG] XMB - Background Image broken

### ISSUE THREAD

**Issue by Manfred282** [libretro/RetroArch#15767]
## Description

Since RetroArch 1.16.0 setting up a wallpaper doesnt work anymore. I did a update like every time from 1.15.0 and my wallpaper didnt show up anymore. Just to make a test i made a fresh RetroArch-Win64 (without installer). Its the same behavior, setting up a wallpaper doesnt work anymore. I did a downgrade to 1.15.0 and it works fine. So i stay with 1.15.0 until the bug is fixed.

### Expected behavior

when setting the wallpaper, it should display it

### Actual behavior

nothing, the wallpaper doesnt set

### Steps to reproduce the bug

1. change driver to xmb (Settings -> Drivers -> Menu -> xmb
2. go to Settings -> User Interface -> Appearance -> Background Image
3. under "Background Image" select a Image File

### Version/Commit

- RetroArch: 1.16.0

### Environment information

- OS: Win 10 Pro

**Comment by sonninnos** [comment]
Not a bug. Set the color theme to "Background Image".
