### ISSUE TITLE
Retroarch 1.16.0 new citra issue (win64)

### ISSUE THREAD

**Issue by 007mesen** [libretro/RetroArch#15766]
Using Citra core on pre 1.16.0 the save folder was

RetroArch-Win64\saves\Citra\

post 1.16.0 RetroArch-Win64\saves\Citra\Citra

Not a big deal but the doubling of the citra folder must not be on purpose?

If I go on a new machine use retroarch 1.15.0 works as expected

1.16.0 double citra folder easy to duplicate.

**Comment by RobLoach** [comment]
Do you have Core Directory Save Folders enabled? Does this happen on other cores?

**Comment by 007mesen** [comment]
> Do you have Core Directory Save Folders enabled? Does this happen on other cores?

Wow, this helped me. False bug/alarm sorry.

**Comment by RobLoach** [comment]
:rocket:
