### ISSUE TITLE
RetroArch rounding config values to integers and saving them with commas instead of periods

### ISSUE THREAD

**Issue by nfp0** [libretro/RetroArch#15775]
## Description

This only started happening after a recent Manjaro Linux update.
I don't know exactly what's the package that causes this to happen.

When a system locale is set in which the comma is the decimal separator (such as most of Europe), RetroArch is rounding the decimal values in the config up to the nearest integer, and saving them like that, replacing the period with a comma.
This completely breaks lots of settings in the config file.

For example, on my system, where `LC_NUMERIC=pt_PT.UTF-8`, if a line that looks like this is on the config file:
`audio_rate_control_delta = "0.005000"`

When you open and exit RetroArch it gets saved as:
`audio_rate_control_delta = "0,005000"`

And the next time you open and exit RetroArch it gets rounded to zero:
`audio_rate_control_delta = "0,000000"`

If I force a locale where the period is the decimal separator, such as by running `LC_NUMERIC=en_US.UTF-8 retroarch` this problem does not occur. So it is related to the LC_NUMERIC environment variable.

This is on RetroArch compiled from the v1.16.0.3 tag. The RetroArch version was not changed when I updated the system.
I also tested on v1.15.0 but the problem is the same.

### Steps to reproduce the bug

1. Open and close RetroArch on a system which uses commas as decimal separator (for example: LC_NUMERIC=pt_PT.UTF-8).
2. Observe commas being saved on decimal values in the config file.
3. Open and close RetroArch again.
4. Observe the decimal values being rounded to the nearest integer, ruining the config.

### Version/Commit

- RetroArch: Tested on 1.15.0 and 1.16.0

### Environment information

- OS: Manjaro Linux
- Compiler: GCC 13.2.1

**Comment by zoltanvb** [comment]
Similar issue in https://github.com/libretro/RetroArch/issues/15756

**Comment by nfp0** [comment]
@zoltanvb Indeed, looks like exactly the same issue. Thanks!

Closing this as duplicate.
