### ISSUE TITLE
(Menu) Make "Clean Playlist" also delete obsolete thumbnails

### ISSUE THREAD

**Issue by 007mesen** [libretro/RetroArch#15770]
if you have lets say a big playlist, with thumbnails, and you remove multiple roms and run the thumbnail update.

can if be made that obsolete thumbnails be removed?

**Comment by RobLoach** [comment]
This could be potentially dangerous, as deleting files can cause unwanted harm on systems. I'd vote for a `NO` for this one.

**Comment by 007mesen** [comment]
> This could be potentially dangerous, as deleting files can cause unwanted harm on systems. I'd vote for a `NO` for this one.

Hmmm, maybe a bad idea then.
