### ISSUE TITLE
Amiga Game Selector "AGS" On Nintendo Switch not launching in Retroarch v1.14.0 

### ISSUE THREAD

**Issue by CommodoreCowboy** [libretro/RetroArch#15785]
Retroarch not loading AGS HDF file on Nintendo Switch through PUAE

Not sure if it's a bug or if I am not configuring it correctly

**Comment by sonninnos** [comment]
Core issues are not RA issues, and surely this one is enough: https://github.com/libretro/libretro-uae/issues/635
