### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [libretro/RetroArch#15792]
...because it does not see any **new** version: https://github.com/libretro/RetroArch/blob/v1.16.0.3/pkg/android/phoenix/AndroidManifest.xml#L5-L6

So please bump versionCode and versionName before tagging a release

**Comment by gouchi** [comment]
ping @LibretroAdmin

**Comment by viachaslavic** [comment]
Looks irrelevant and should be closed. 
@licaon-kter maybe you are interested in a new other [build issue](https://github.com/libretro/RetroArch/issues/17220)?
