### ISSUE TITLE
[PS2] PicoDrive core doesn’t work since RetroArch 1.14.0

### ISSUE THREAD

**Issue by HeavyHeart2012** [libretro/RetroArch#15800]
## Description

Hello. Since version 1.14.0 PicoDrive core shows version as 1.99-unknown and after launching any game just “crash” to PS2 browser.

### Expected behavior

Games should run properly as they did with version 1.13.0 and below.

### Actual behavior

Games "crash" to PS2 browser.

### Steps to reproduce the bug

1. Launch PicoDrive ELF
2. Launch any MegaDrive/Genesis game

### Bisect Results

Since retroarch 1.14.0.

### Version/Commit

1.14.0, 1.15.0, 1.16.0

### Environment information

PlayStation 2 90008. Also tested on PCSX2 emulator.

![9830ecda5352be9f74d9534babfdb39a09b460ed](https://github.com/libretro/RetroArch/assets/147956815/cbd8a3d9-ed1f-446a-9a58-caae14c0b3e2)

**Comment by zoltanvb** [comment]
I have found the reason for the "unknown" version issue, and will submit a pull request, but that is probably less important.

But I can not reproduce the crash with current versions on PCSX2. I have experienced strange things when config file was shared between versions, but in a fresh install (when there is only raboot.elf, cores/ and info/ in the respective directory), it has worked always.

Maybe it is still content related, can you name a few ROMs that exhibit the fault?

**Comment by HeavyHeart2012** [comment]
I've played with some settings and disabling "Always Reload Core on Run Content" in core settings partially solved the problem. Now games work but without sound...

**Comment by HeavyHeart2012** [comment]
Works fine with no sound problem on version 1.15.0 but again you need to disable "Always Reload Core on Run Content".

**Comment by HeavyHeart2012** [comment]
Okay. After more than hour of testing (on real PS2) I figured out what was the issue. First of all file "retroarch-salamander.cfg" was missing although 1.13 no need it to play. Secondly you need to disable "Always Reload Core on Run Content" in Settings - Core. Only after that games launch as they did at 1.13 BUT on version 1.16 there is no sound at all so I stay on 1.15.

**Comment by zoltanvb** [comment]
Thanks for the check. The sound fix is awaiting merge: https://github.com/libretro/RetroArch/pull/15827

**Comment by HeavyHeart2012** [comment]
Cool. What about hiding folder "System Volume Information" on flash drive in RA browser? Older RA versions didn't show it.

**Comment by HeavyHeart2012** [comment]
The problem is missing "retroarch-salamander.cfg" file and you need to disable "Always Reload Core on Run Content" in core settings.
(Sorry I accidentally delete my previous comment about this solution)
