### ISSUE TITLE
Add mGBA core

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#1580]
mGBA 0.2 was released this morning. The dev has already made a libretro core. It just needs added in. It's a fantastic GBA emulator that doesn't require a BIOS file and has local multiplayer support. http://endrift.com/mgba/

**Comment by hizzlekizzle** [comment]
We're already including builds in the buildbot when possible, actually:
http://buildbot.libretro.com/nightly/win-x86_64/latest/mgba_libretro.dll.zip

I agree it's an awesome emulator already with tons of exciting prospects on the horizon.
