### ISSUE TITLE
Retroarch Playstation 2 urgently needs repairs 

### ISSUE THREAD

**Issue by andres0021** [libretro/RetroArch#15815]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
I wanted to know if there are plans to repair the sound problem that Retroarch PS2 has on a console, it turns out that the new updates do not contain sound, nor any game. 
and the other is, I wanted to know if you think it is possible that they can repair the gba core, unfortunately even though it is very fluid a few minutes into the game the games freeze and you have to restart the PS2 console, all this happens to me on the console 
[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by zoltanvb** [comment]
Please do not open new issues of the same problems. I'll respond to the original issue.
