### ISSUE TITLE
The L3+R3 control for opening the menu coincides with the list jumping function.

### ISSUE THREAD

**Issue by NicNamSam** [libretro/RetroArch#15823]
When L3+R3 are selected as the controls to open/close the Retroarch menu, the next time the menu is opened, the selection of whatever list you are on is likely to be either at the top or bottom, rather than what you left it on. This is because of the implementation of using L3 and R3 (pressing the thumbsticks) to jump to the top or bottom of the current list. Almost every time the menu is closed or opened, I now have to scroll back up/down to where I was.

A solution would either be to simply allow the individual list jumping controls to be toggleable, or for there to be a small delay after pressing one of the thumbsticks before the list scrolls up or down, in order to wait for the second thumbstick to be pressed before the delay ends, which would thus open/close the menu *instead* of scrolling. This is how most programs and games handle the possibility of simultaneous button presses.

- RetroArch: 1.16.0
- Git Version 14cb373
- OS: Windows 10

**Comment by Megaframeman** [comment]
Agreed! I've noticed this too, it's really driving me up the wall, I thought it was something I did, it's so annoying.

**Comment by Daddu3** [comment]
I'm also dealing with this problem and it's making it hard to try using L3 + R3 as the menu hotkey combo. Pretty surprised it hasn't still been dealt with.

**Comment by Daddu3** [comment]
> I was also disappointed by the lack of progress in this issue, so I resorted to using the center Guide button on my Xbox 360 controller to toggle the menu. It's actually better, but the problem should still be fixed. Not all controllers have that extra button.

You're more than right - for example, I'm using an earlier model of 8Bitdo's SNES Pro-controller that doesn't have a working button to input menu toggle to.
