### ISSUE TITLE
Save State screenshots persist when i go to a different game in the playlist without closing content first

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/RetroArch#15832]
## Description

When you load a game that has a save state (and a screenshot) and you highlight the "load" for the screenshot to appear, and then go to a different game in the playlist, you can see that last screenshot from the previous game in the new game's menu.

### Expected behavior

There is no reason for an unrelated save screenshot from an unrelated game to appear in a different game's menu.

### Steps to reproduce the bug

1. Load a game that has a save state.
2. Highlight or load the save state so you can see the screenshot
3. Press F1 to go to the menu and go to a different game in your playlist (without closing the content)
4. Press the selection button to open the new game's menu so you can load it
5.  The State screenshot from the last game will appear here

### Version/Commit
1.16.0 Git Version 535898d

### Environment information

- OS: Windows 10

**Comment by sonninnos** [comment]
I can't replicate with any menu driver that support savestate thumbnails..
