### ISSUE TITLE
[PS2] Disabling "Show Hidden FIles and Directories" don't hide "System Volume Information" folder on USB flash drive

### ISSUE THREAD

**Issue by HeavyHeart2012** [libretro/RetroArch#15831]
## Description

Disabling "Show Hidden FIles and Directories" don't hide "System Volume Information" folder on USB flash drive in RetroArch file browser.

### Expected behavior

"System Volume Information" folder shouldn't be visible.

### Actual behavior

"System Volume Information" folder visible.

### Steps to reproduce the bug

1. Stick USB flash drive with "System Volume Information" hidden folder on it into PS2
2. Select Load Content - mass:/ to open USB flash drive

### Bisect Results

At least on RA 1.13.0 this folder wasn't visible

### Version/Commit

1.15.0, 1.16.0

### Environment information

PlayStation 2 90008

**Comment by zoltanvb** [comment]
I did a few tests and it looks as if earlier RA versions on PS2 never showed hidden/system dir, and later ones always displayed it. Do you recall any version where it would work as expected (hidden by default, shown when the option is disabled)? It could help in locating the problem.

**Comment by HeavyHeart2012** [comment]
Tested. I've used 3 hidden objects to test - empty folder and game ROM in zip format which was hidden manually. And "System Volume Information" (SVI) folder which is hidden by default.
On version 1.13 "Show Hidden FIles and Directories" option do nothing. Empty folder and ROM always visible but SVI folder invisible.
On version 1.14. 1.15 and 1.16 option also do nothing but SVI folder always visible too.
I just wanna get rid of "SVI" folder like it was on 1.13 🙂

**Comment by HeavyHeart2012** [comment]
Here we go. I've used 3 hidden objects to test - empty folder and game ROM in zip format which was hidden manually. And "System Volume Information" (SVI) folder which is hidden/system by default.
On version 1.11 - 1.13 "Show Hidden FIles and Directories" option do nothing. Empty folder and ROM always visible but SVI folder invisible.
On version 1.14 - 1.16 option also do nothing but SVI folder always visible.
For at least a year this option has not been working correctly. I really don't care about manually hidden files/folders. Just wanna get rid of "SVI" folder like it was before 1.14 🙂

**Comment by HeavyHeart2012** [comment]
Here we go. I've used 3 hidden objects to test - empty folder and game ROM in zip format which was hidden manually and "System Volume Information" (SVI) folder which is hidden/system by default.
On version 1.11 - 1.13 "Show Hidden FIles and Directories" option do nothing. Empty folder and ROM always visible but SVI folder invisible.
On version 1.14 - 1.16 option also do nothing but SVI folder always visible.
For at least a year this option has not been working correctly. I really don't care about manually hidden files/folders. Just wanna get rid of "SVI" folder like it was before 1.14 🙂

**Comment by zoltanvb** [comment]
Thanks for the check, I'll look into it.

**Comment by zoltanvb** [comment]
Can you check if the nightly build from 2023-10-31 or later solves the issue?
http://buildbot.libretro.com/nightly/playstation/ps2/

**Comment by HeavyHeart2012** [comment]
I checked  2023-10-31 build and SVI folder is hidden and "show hidden folders and directories" switch also works.

**Comment by zoltanvb** [comment]
Great, can you please close this issue? :)
