### ISSUE TITLE
Dynamic backgrounds require color theme to be set to BackgroundImage to function

### ISSUE THREAD

**Issue by C0rn3j** [libretro/RetroArch#15878]
## Description

Dynamic Background requires ColourTheme to be set to BackgroundImage.

If this is on purpose and not a bug, this is extremely bad UI/UX and should at the very least be a huge red warning in the label of DynamicBackground.

Found this out only thanks to https://www.reddit.com/r/RetroArch/comments/176sl0o/help_getting_dynamic_backgrounds_working/

### Expected behavior

Turning on Dynamic Background works without issues.

### Actual behavior

They do not work unless ColourTheme is set to BackgroundImage.

### Steps to reproduce the bug

1. Enable Dynamic backgrounds
2. Set ColourTheme to anything else than BackgroundImage
3. Selecting Playlist does not change the background

### Bisect Results

Did not do a bisect.

### Version/Commit
- RetroArch: 1.16.0.3

### Environment information
- OS: Arch Linux

**Comment by sonninnos** [comment]
Yes it is on purpose, because otherwise there will be ugly color combinations by default, because icon themes have their own background images.

**Comment by sonninnos** [comment]
Ok, I changed the logic a bit, so please try it out after it is merged.

**Comment by C0rn3j** [comment]
I skimmed the issue and that looks to solve much more than I initially had a problem with, thanks a lot for fixing it!

**Comment by sonninnos** [comment]
Let's close this since it seems to be done.
