### ISSUE TITLE
Remapping question

### ISSUE THREAD

**Issue by gizmo98** [libretro/RetroArch#1593]
If i add a remapping file with the following content both buttons will be mapped to button b:
input_player1_b = input_player1_a
input_player1_a = input_player1_b

Is there anything wrong or do i equal input_player1_b and input_player1_a with "="? Is there any example file? Don't know why, but "save remap file as.." hangs as any other keyboard input dialog. (Okay, i could update retroarch....)

**Comment by SAKUJ0** [comment]
You can set up your core remapping files from inside RGUI and save them.

**Comment by gizmo98** [comment]
I know. But RGUI hangs always if i try to type a file name. Issue persists on RPI since some (months/)weeks. Could you post a example remapping file?

**Comment by fr500** [comment]
Hangs?  You need a kb or at least a kb overlay and a mouse.  It's not
hanging it's waiting for you to input the filename.

Anyway I'll add an option to save a core remap and another one to save a
game remap without entering filenames

**Comment by gizmo98** [comment]
Yeah, i have a keyboard and it hangs. I recompiled tetrarch today and the issue persists... And i have not posted an issue until know. Sorry. Just wanted to remap some buttons today ;-)

**Comment by SAKUJ0** [comment]
[Here](http://hastebin.com/abikunobek.ini) you go, @gizmo98.

**Comment by gizmo98** [comment]
Thank you! I will close this issue and reopen another issue if i find no solution for my RGUI hangs problem.

**Comment by fr500** [comment]
how is it hanging, is the dialog there but no input works? if that's the
case that's an issue with your input driver I guess

**Comment by knonderful** [comment]
I had the same problem with the file name input dialog on RetroPie (v3.0 beta 3). Even with a keyboard connected I could enter anything or get out of it. However, after looking into the RetroArch source code, I did figure out the format of the mapping file, so it can be written by hand.

In the retroarch.cfg, set the variable "input_remapping_path" to the (full?) path of the file in which you will define your mapping.

Then write the mapping file in the following format:

     input_player1_b = 0
     input_player1_a = 6
     input_player1_x = 1

The digits on the right are the internal constants used for the RetroPad. Which digit maps to which RetroPad button can be retrieved by running the RetroArch joystick tool. The tool asks for input in the internally defined order (I believe; I haven't explicitly tested it), with the first button (B) starting at 0. 

To confirm the mapping (without trying it out in the game), just launch RetroArch and go to the button mapping and you should see the changes applied (and it should show which file the settings are loaded from).

I am not sure this is all correct, but it is more information than I could find anywhere else on teh netz.
