### ISSUE TITLE
RFE: Use the new JSON playlist format to add more core and format contextual data, for savestate and boot loading.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#15948]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The usecase is m3u files launched in playlists remembering the last cd they loaded and loading that on start instead of the first.  I think there is one for diskettes in the pc98 emulator core and puae, but I don't remember the extension. I think they're equivalent to m3u (puae extends m3u though for... something...). Although this idea doesn't depend on the contents of the launcher file or modify them.

It could be done as a playlist setting on the libretro interface (for instance, 'm3u reload last entry') by making loading a core keep a callback that would rewrite the entry containing the 'loaded_entry' if that playlist setting was active when the change cd callback occurred if the original entry was a m3u (or another container like format).

### Expected behavior

Everytime you restart a multicd or multi diskette game on RetroArch, the last savestate or last save entry being loaded (if the game supports loading saves from the menu and doesn't require boot from a specific disc\diskette), just continues the game regardless of the cd it was in.

### Actual behavior

Difficult to reload savestates belonging to the last used cartidge\cd\diskette if it's different than the first loaded, need to change manually before reloading savestate.

Similar situation for saves, but some platforms are more polite than others (consoles usually allow loading saves and booting from all cds, but older pc-like devices usually force a bootdisk then request a disk change later.... main usecase is savestates though, especially with autosaveonexit\autoloadonstart which don't have this issue).

**Comment by i30817** [comment]
That's wiped once you quit the game afaik? Unless there are new developments, but I don't know how it could be done without affecting the 'entry point'. 

A special file in the saves directory for when you load a m3u\m3u equivalent maybe, which is practically the same idea, just not centralized to JSON.

**Comment by hizzlekizzle** [comment]
Ah, here's the commit for remembering disk index: https://github.com/libretro/RetroArch/pull/10045

**Comment by i30817** [comment]
I could have sworn this didnt happen, but I guess I'm wrong. Just tried with fear effect 2.

**Comment by sonninnos** [comment]
Hmm, why not save that disc index data directly in the playlist file though.. Since if savestate index remembering would be added, it would also have to be in a separate file.

**Comment by i30817** [comment]
It makes sense actually, I've seen 65mb playlists (someone had the complete tosec commodore 64 in a playlist).
