### ISSUE TITLE
Gba shader

### ISSUE THREAD

**Issue by Shimmer2** [libretro/RetroArch#15940]
The gba shader displays pixel offset, which is not very accurate. The screen resolution has been set to an integer multiple of gba

**Comment by Shimmer2** [comment]
![Uploading IMG_4976.jpeg…]()

**Comment by Shimmer2** [comment]
![IMG_4976](https://github.com/libretro/RetroArch/assets/79088619/dcd75938-f358-437e-8954-edd7d754d9f5)
![IMG_4977](https://github.com/libretro/RetroArch/assets/79088619/d7230936-3d71-404f-b54d-cece1d79d368)

**Comment by hizzlekizzle** [comment]
I'm not sure I follow. What's offset?

**Comment by Shimmer2** [comment]
Please pay attention to the logo of Baokemeng Hospital, which is offset by one pixel to the left

**Comment by Shimmer2** [comment]
Please note that the logo of Pokémon Hospital is offset by one pixel to the left

**Comment by hizzlekizzle** [comment]
Ah, I think that's an illusion caused by the simulated RGB subpixels. Wherever there's a solid red color, only the red subpixels will be lit, so it will look like it is off-center.

**Comment by Shimmer2** [comment]
Is there a solution?

**Comment by Shimmer2** [comment]
When running gb/gbc cassette games on the gba game console, the LR button can scale the screen size. I'm not sure if the emulator can add this feature to achieve a more realistic restoration effect. Thank you!!

**Comment by hizzlekizzle** [comment]
I'm afraid the only solution would be to use a different shader. There are some that will simulate a pixel grid without simulating the RGB subpixels, and that should avoid this issue.

**Comment by Shimmer2** [comment]
Okay, thank you very much! May I ask if it is possible to add brightness adjustment function to overlays? And support for larger magnification

**Comment by hizzlekizzle** [comment]
Increasing the max size should be doable. Adding brightness control would be harder.
