### ISSUE TITLE
MAME Current doesn't Support 7z archive?

### ISSUE THREAD

**Issue by vus7294** [libretro/RetroArch#15956]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch MAME(0.260)'s Bug

### Expected behavior

Load Game Normally

### Actual behavior

Crashed and Put out [retroarch.log](https://github.com/libretro/RetroArch/files/13470834/retroarch.log)
![스크린샷 2023-11-27 160557](https://github.com/libretro/RetroArch/assets/13133961/0b2c4fa2-3409-46c9-ada9-c605b0c1cf1e) Game Rom 7z

### Steps to reproduce the bug

1. Turn on
2. Load Game 7z
3. Does not load

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

1.16.0 with MAME Current x64

- OS: Windows 11

**Comment by bslenul** [comment]
Works fine, but the "cybrcyccj.7z" romset you're trying to load is a clone and you need "cybrcycc.7z" (the parent romset) for it to work properly.

https://docs.libretro.com/guides/arcade-getting-started/

And yeah, for support use the Discord server or the Libretro forums instead! 👍

**Comment by vus7294** [comment]
> Works fine, but the "cybrcyccj.7z" romset you're trying to load is a clone and you need "cybrcycc.7z" (the parent romset) for it to work properly.
> 
> https://docs.libretro.com/guides/arcade-getting-started/
> 
> And yeah, for support use the Discord server or the Libretro forums instead! 👍

I Tried same as android x64 and works fine.(Mr. Driller 2 JP ver) is it windows MAME's Bug?

**Comment by vus7294** [comment]
> or 

And also tried with original rom(cybercycc) and got same Result

**Comment by sonninnos** [comment]
https://github.com/libretro/mame ..
