### ISSUE TITLE
input bindings are broken (with some gamepads?) unless `input_bind_hold = "0"`

### ISSUE THREAD

**Issue by l3iggs** [libretro/RetroArch#15969]
Hi, I couldn't bind buttons on my gamepad unless I changed an obscure cfg file setting to
```
input_bind_hold = "0"
```
tested with a USB connected google stadia controller.

Here's a link to some chat about it in discord:
https://discord.com/channels/184109094070779904/469974542299955210/1180183172391112858

**Comment by hizzlekizzle** [comment]
I think @sonninnos moved the default hold to 0 in nightly builds (FAKEDIT: ah, [here we go](https://github.com/libretro/RetroArch/pull/15909)) but I'm not sure if this is a end solution to it or not, so this issue is helpful for tracking that.

**Comment by l3iggs** [comment]
I should have mentioned the issue is here on arch linux package version 1.16.0.3-1
