### ISSUE TITLE
xd3_decode_memory expected 'usize_t *' {aka 'unsigned int *'} but argument is of type 'uint64_t *' {aka 'long long unsigned int *'}

### ISSUE THREAD

**Issue by MSHectorCM** [libretro/RetroArch#15963]
## Description

Building retroarch I'm facing the error 

tasks/task_patch.c: In function 'xdelta_apply_patch':
tasks/task_patch.c:695:25: warning: passing argument 6 of 'xd3_decode_memory' from incompatible pointer type [-Wincompatible-pointer-types]
  695 |            *targetdata, targetlength, *targetlength, 0))
      |                         ^~~~~~~~~~~~
      |                         |
      |                         uint64_t * {aka long long unsigned int *}
tasks/../deps/xdelta3/xdelta3.h:1163:43: note: expected 'usize_t *' {aka 'unsigned int *'} but argument is of type 'uint64_t *' {aka 'long long unsigned int *'}
 1163 |                            usize_t       *output_size,
      |                            ~~~~~~~~~~~~~~~^~~~~~~~~~~
make[1]: Leaving directory '/***/build/lib32-retroarch-0ffd3030bf6d76edfa9155bdacffcf81d009fbdf'

### Expected behavior

To Compile with no errors

### Actual behavior

error due to mismatch of types

### Steps to reproduce the bug

Compiling against Emuelec toolchain

### Bisect Results

The issue started on this commit https://github.com/libretro/RetroArch/commit/cbf49a0b77b636f35e145a1bd7e0efbbb4ee06d3

### Version/Commit

Starting commit https://github.com/libretro/RetroArch/commit/cbf49a0b77b636f35e145a1bd7e0efbbb4ee06d3 and onwards

### Environment information

- OS: EMUELEC 4.7 toolchain compiling on Ubuntu 20.04 WSÑ2
- Compiler: gcc 12

**Comment by JesseTG** [comment]
Are you trying to produce a 32-bit build, per chance?

**Comment by MSHectorCM** [comment]
The system is 64 bit but there is a part that is 32 bit and it is failing due to the uint64. Is it possible having uint32 or any other workaround?

thx!!!

**Comment by JesseTG** [comment]
If I understand correctly, you're trying to build a 32-bit instance of RetroArch to run on a 64-bit system? If that's the case, is there a reason you can't use a native 64-bit build?

**Comment by MSHectorCM** [comment]
yes it is, but I don't why it is failing with that type. It should work.

**Comment by Kelvfimer** [comment]
I need to check @JesseTG :) thx for your support

**Comment by MSHectorCM** [comment]
Hello @JesseTG  thx it is solved :)
