### ISSUE TITLE
Cannot start pcsx2/lrps2 core because of: (!) Missing, Required 'pcsx2/bios' folder.

### ISSUE THREAD

**Issue by proudhon** [libretro/RetroArch#15978]
# First and foremost consider this:

## Description
Cannot start lrps2 or pcsx2 because of the following error:
(!) Missing, Required 'pcsx2/bios' folder.

I do indeed created the requested folder under /home/$user/.config/retroarch/system/pcsx2/bios.
Is this the correct path?

### Expected behavior

RetroArch recognizing existence of the specified path

### Actual behavior

Won't start the core with Failed to Load Content pop-up

### Steps to reproduce the bug

1. Open retroarch
2. Load Core
3. Start Core

### Bisect Results
Fresh install

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 6c2cc45628

### Environment information

- OS: Arch Linux

**Comment by proudhon** [comment]
It works.
Sorry for bothering.

**Comment by AngeloRubens** [comment]
Hi All, where i found a correct bios for ps2?

**Comment by hizzlekizzle** [comment]
We can't help you find BIOS images, which are protected by copyright just like game ROMs. We can only suggest you dump them from your own console in accordance with your local laws.
