### ISSUE TITLE
[Bug] Hotkeys cannot be modified in v1.16.0

### ISSUE THREAD

**Issue by ZucriyAmsuna** [libretro/RetroArch#15988]
## Description

Hotkeys cannot be changed in the menu.

Workaround: The retroarch.cfg can be modified directly (when RetroArch is closed) to make hotkey changes.

### Expected behavior

You click a hotkey option, see the prompt, and press the button you want as the new hotkey. The hotkey is changed.

### Actual behavior

You click a hotkey option, see the prompt, and try to press anything at all on a controller, mouse, or keyboard. It does not take the input. The prompt's timer counts down, and the hotkey does not change.

### Steps to reproduce the bug

1. Settings > Input > Hotkeys
2. Click a hotkey to change
3. When the prompt tells you to press a button, try pressing a button
4. Watch the prompt count down, as no input has been registered

### Bisect Results

The issue seems to have begun in version 1.16.0.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 / 14cb373

### Environment information

- OS: Windows 10 Home 22H2
- New RetroArch installation (on a non-C drive)
- Logitech mouse, Razer keyboard, PS4 controller

### External sties

- [Redditors with the same issue](https://www.reddit.com/r/RetroArch/comments/16xiq6t/cannot_change_hotkeys_or_any_input_settings_at/)

**Comment by sonninnos** [comment]
Works fine here with W10.

**Comment by sonninnos** [comment]
Well does it say "release all keys" or not? If so, just set "Bind Hold" to 0, which has been the default in nightlies for a while already.

**Comment by mauricioreis9** [comment]
Thanks a lot for the help!
