### ISSUE TITLE
[PS3?] Content history writing broken

### ISSUE THREAD

**Issue by nattycleopatra** [libretro/RetroArch#1600]
Regardless of core used, core_path is set to fb_alpha_libretro_ps3.SELF (alphabetical "first core") in retroarch-content-history.txt. core_name, however, is set correctly for each entry.

Tested on PS3 cd4371f

**Comment by fr500** [comment]
Can you do a bit bisect?

**Comment by fr500** [comment]
Ok I think I know what cause this, can you build yourself an re-test? I guess you built yourself in the first place..

Just revert this line:
https://github.com/libretro/RetroArch/commit/e71940ff341aee98b66eb5d0ac6c597789bc69d5#diff-55b11c8dab3e1e8a8a7998e7e9cda4fcL2133

**Comment by nattycleopatra** [comment]
You were right indeed, the path now gets set correctly.

**Comment by fr500** [comment]
Ok Ill push a fix ASAP
