### ISSUE TITLE
[iOS][Feature request] Support universal links

### ISSUE THREAD

**Issue by nighto** [libretro/RetroArch#16002]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch for iOS could have support for [universal links](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content), either (easiest way) to only open the app or (not so easy) to open directly a game.

### Expected behavior

That a link to (for instance) `retroarch://start` would start the application, or `retroarch://[ROM filename]` would start RetroArch and open the given ROM.

By doing so, users or developers of other apps could open the emulator directly from other apps or websites pinned to the homescreen. This could be helpful to, for instance, create a horizontal launcher, which would be good for using the iPhone with controllers such as Backbone and the like, because iOS launcher is restricted to vertical mode, similar to how Backbone app launches apps. If you try to add RetroArch to the Backbone's app it won't work because the app does not have a [universal link](https://developer.apple.com/documentation/xcode/allowing-apps-and-websites-to-link-to-your-content) set up.

**Comment by warmenhoven** [comment]
Can you walk me through in much more detail how you are anticipating getting RetroArch to show up in the Backbone app? The way I understood what you're saying, I don't think it works that way, which makes me think I might have misunderstood you.

**Comment by nighto** [comment]
Found out a way to do it without changing anything on RetroArch app. Thanks anyways :)

Documenting here for future reference (copying my post on reddit): https://www.reddit.com/r/Backbone/comments/18hdb8q/how_to_open_retroarch_or_other_emulator_from/

> Hi there, I got the Backbone recently and my main goal was to play RetroArch and PPSSPP on the iPhone. I won't discuss here how to install them - you can use [AltStore](https://altstore.io/) - but those sideloaded apps cannot be added to the Backbone menu, so every time you need to unlock your phone and navigate with it sideways to open the emulator.
> 
> Turns out there is a way, which I found buried within this subreddit as a comment by [u/mdrockwell](https://www.reddit.com/u/mdrockwell/) - link to the original post: https://www.reddit.com/r/Backbone/comments/11qy9lh/comment/jcv9crf/?utm_source=share&utm_medium=web2x&context=3. The workaround is to create a Shortcut to open the emulator when another game is launched. Thanks for the idea mdrockwell!
> 
> I am simply creating a post so it can be easily found, and describing how to create the shortcut. Here is what you need to do:
> 
> 1. Open Backbone app, click on See all the games, then App Store, then install a lightweight game that is supported by Backbone. I chose "Retro Bowl", because it seemed lightweight enough and has "Retro" on its name :)
> 
> 2. Open Shortcuts, click on second tab Automation, top right + button, search for "App", choose the app "Retro Bowl", make sure "When it opens" is checked, then mark "Execute immediately", leave "Notify when run" unchecked, click Next. Then, on the following page, choose "New Blank Automation", choose "Open App" (if it is not suggested, click on Add Action, then search for "Open App" and choose Scripts > Open App), click on "App" and choose RetroArch. Optionally, add a second task to put the phone in Do Not Disturb to stop receiving notifications, to do so search for "Focus", click on "Define focus", click on "Deactivate" and change it to "Activate", and then choose "Do Not Disturb" (or whatever other Focus mode you might want to use). Finally, click OK to save.
> 
> 3. Repeat the process if you want to the the same with PPSSPP or other emulators.
> 
> 4. That's it, now go back to the Backbone app, open the Retro Bowl game and it will open and then it will quickly open RetroArch.
> 
> Here is a video: https://giphy.com/gifs/FqBzNlBleDZ6e3q9bL

**Comment by ioslife** [comment]
I don't think this should be closed as your workaround doesn't really accomplish how this could work. You should be able to link to a specific game. This would allow for some awesome integrations with third party apps.

**Comment by trexguo** [comment]
+1

**Comment by warmenhoven** [comment]
> You should be able to link to a specific game
Yes, I agree, and I have been thinking a lot about exactly how to do this, but it ends up being very complicated trying to decide what types of inputs to accept (only matching names in the database? what about for people who have manually scanned?) and how to translate that into the users' library. RetroAchievements has the advantage of having a hash of the rom but that's after applying patches. I can build a 20% solution pretty easily and it will be fine for some people but really not work at all for most.

**Comment by daveycodez** [comment]
We should be able to simply put the path to the ROM file in the documents folder, when it opens it scans it then plays it
