### ISSUE TITLE
[Linux][Wayland] Mouse cursor appears to have a deadzone on Wayland

### ISSUE THREAD

**Issue by spagootie** [libretro/RetroArch#16015]
## Description

When I use RetroArch on Wayland with a DS core (**either desmume or melonDS**), the cursor for the bottom screen will not move if I'm not moving my mouse rapidly, and doesn't respond at all to slower movements. To illustrate this, I've included a video of the problem. **This does not appear to be a problem with the cores**, because I can cause the issue to happen outside of any cores by pressing F11 or enabling Automatic Mouse Grab in the Input Settings menu.
The issue happens on both KDE Plasma and Sway for me.

https://github.com/libretro/RetroArch/assets/39144253/55e4069d-b0d3-44a7-ae93-ca7b2dd46fee

### Expected behavior
I expected the cursor to follow all mouse movements normally, and this is how the mouse works when I force RetroArch to use XWayland rather than Wayland.

### Steps to reproduce the bug

1. Open RetroArch on Wayland
2. Use any input driver
3. Open a DS ROM or press F11
4. See that the mouse cursor does not work properly

### Version/Commit
I'm currently running RetroArch version 1.16.0 and git version 0c1ee70ca0, although I've observed this bug on git version 6c2cc45628 as well.

### Environment information
Arch Linux x86_64, KDE Wayland and Sway.
I have two monitors and an AMD GPU.

**Comment by ColinKinloch** [comment]
The "deadzone" behaviour is a result of accelerated mouse motions that are less than 1 being rounded down to zero by `wl_fixed_to_int`.

**Comment by spagootie** [comment]
> Thanks for the report, the video was pretty useful. The "deadzone" behaviour is a result of accelerated mouse motions that are less than 1 being rounded down to zero by `wl_fixed_to_int`.

I just built retroarch using your wayland_unaccel_pointer branch and the bug is fixed :) 
Thanks!
