### ISSUE TITLE
RFE: add a per playlist setting to disable .ldci files image index switch when loading .m3u files

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#16018]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The .ldci format is used by RetroArch to remember the index of a the last switched to m3u content, so the next run, autoload of savestates, or just normal loadstate works correctly.

If however you don't plan to use savestates on a set, they get in the way in the case of booter or boot disk games, because those kind of diskette games rarely have the feature to load a savegames by booting from all diskettes. This isn't a problem from the ps1 on when Sony wised up about this and demanded all disks have a load menu on boot, but for the diskette era no one did this afaik.

I'm actually unsure if this should be set by game ( in the ldci files ) or by playlist (in the playlist file) actually.

### Expected behavior

A setting to disable this behavior when it's irritating (don't plan to use savestates, the game is a old multiple diskette game).

Alternatively, and even better because the user wouldn't have to care, make certain cores opt out of this setting unless the user turns it on, or the other cores that use cds with load menus on all cds, opt in.

### Actual behavior

I _presume_ (didn't test atm) that the diskette is moved to last switched to. Might be possible I'm scaremongering without basis if the cores involved (cores that accept diskettes) opt out of the behaviour (or alternatively, cores that benefit from .ldci files opt in to them).
 
@sonninnos

**Comment by gravelfreeman** [comment]
I'm having the exact same issue.

I'm using LaunchBox as my frontend for RA and I've setup an AHK script to swap discs in RA. Basically it's

1. toggle tray hotkey
2. cycle next disc hotkey
3. toggle tray hotkey

When I change the disc it creates a `GAMENAME.ldci` file under `RetroArch\saves\SwanStation\`.

It has the following line which instructs the latest chosen disc.

`"image_path": "M:\\library\\games\\sony-playstation.1\\D (USA)\\D (USA) (Disc 3).cue"`

This file loads every time I reboot the game.

I've searched everywhere in the options and I couldn't find an option to disable the creation of the `.ldci` file per core/game.

I think it would be a great addition to add this option in the GUI.

**Comment by zoltanvb** [comment]
There is no option currently for disabling it, but it should not be very complicated to add one (normal option, which can be saved in core override or content override).
Technically, the core could also reject changing the initial image, but I checked a few and could not find any such possibility among the core options.

**Comment by gravelfreeman** [comment]
How can we get this option to stable? I'm not a programmer and can't help myself. Thank you for replying.

**Comment by gravelfreeman** [comment]
I installed the v17 and couldn't find the new option. Anyone could help me find it out? Thank you!

**Comment by zoltanvb** [comment]
It did not make it in time for RA 1.17.0 stable, but any recent nightly build should have it already.

**Comment by gravelfreeman** [comment]
Do you know how much time the next stable will be out? Approximatively? I don't like updating to nightly :p

**Comment by gravelfreeman** [comment]
Np. I can wait 1-6 months, thank you!
