### ISSUE TITLE
[Core Request] Citra - Nintendo 3DS emulator

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16028]
[Citra](https://github.com/citra-emu/citra)'s is a free Nintendo 3DS emulator. It is ported for both OSes (including GNU/Linux), and the mobile OS Android.

Nintendo 3DS was discontinued in 2020, so it would be nice to integrate Citra into a RetroArch core and be ported to mobile devices too!

This is a big task and I have no time to contribute to it. I just opened this issue when I realized that no one else did.

**Comment by hizzlekizzle** [comment]
It [already exists](https://github.com/libretro/citra), and it's [already available on Android](http://buildbot.libretro.com/nightly/android/latest/arm64-v8a/citra_libretro_android.so.zip).

**Comment by i30817** [comment]
It exists, but doesn't run in a lot of systems (and systems) because of driver nonsense.

There is a rebase in the works, its currently blocked because of some linker nonsense in android, if you want to help and can compile\test\code @davidhedlund 

https://github.com/libretro/citra/pull/127

**Comment by davidhedlund** [comment]
> It [already exists](https://github.com/libretro/citra), and it's [already available on Android](http://buildbot.libretro.com/nightly/android/latest/arm64-v8a/citra_libretro_android.so.zip).

Oh sorry, and thank you for the links!

**Comment by davidhedlund** [comment]
> It exists, but doesn't run in a lot of systems (AMD systems) because of driver nonsense.
> 
> There is a rebase in the works, its currently blocked because of some linker nonsense in android, if you want to help and can compile\test\code @davidhedlund
> 
> [libretro/citra#127](https://github.com/libretro/citra/pull/127)

Noted. Thank you.
