### ISSUE TITLE
[Core Request] Vita3K - PS Vita emulator

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16027]
[Vita3K](https://github.com/Vita3K/Vita3K)'s has been distributed as free software for both desktop OSes including GNU/Linux, and this year also to [Android](https://github.com/Vita3K/Vita3K-Android/releases/).

PS Vita was discontinued in 2019, so it would be nice to integrate it into a RetroArch core and be ported to mobile devices too!

This is a big task and I have no time to contribute to it. I just opened this issue when I realized that no one else did.

**Comment by RobLoach** [comment]
Would definitely be cool. Feel free to collaborate with someone in Discord or the Forum on brainstoming ideas on how to make it happen. This is the RetroArch issue queue, and core ideas are likely best elsewhere. Thanks!

**Comment by InfusedStormblessed** [comment]
What is the general process of making a core, and I can try to make it?

**Comment by davidhedlund** [comment]
> What is the general process of making a core, and I can try to make it?

To port an emulator to the [libretro API](https://www.libretro.com/index.php/api/), you adapt the emulator’s code to use libretro’s standard functions and callbacks for video, audio, and input, replacing any platform-specific code.

**Comment by paulo101977** [comment]
> [Vita3K](https://github.com/Vita3K/Vita3K)'s has been distributed as free software for both desktop OSes including GNU/Linux, and this year also to [Android](https://github.com/Vita3K/Vita3K-Android/releases/).
> 
> PS Vita was discontinued in 2019, so it would be nice to integrate it into a RetroArch core and be ported to mobile devices too!
> 
> This is a big task and I have no time to contribute to it. I just opened this issue when I realized that no one else did.

I started a port of Xemu, but unfortunately I couldn't adapt it to libretro as I wanted; it only works for my Reinforcement Learning training. I could even work on a Vita3k port, but the problem is that these more modern console emulators don't implement save-state, and for me that's unfeasible (my goal in porting is to have a machine learning training option).

**Comment by paulo101977** [comment]
> What is the general process of making a core, and I can try to make it?

It's a process similar to what's done with Python DLLs/SOs: you have to expose some functions, in this case, from the Libretro API. I did something similar with Xemu, but only for Reinforcement Learning, since I would have to remove its window implementation, which was a difficult task.

**Comment by davidhedlund** [comment]
> I started a port of Xemu, but unfortunately I couldn't adapt it to libretro as I wanted; it only works for my Reinforcement Learning training.

That's cool! I linked to your repo in:
* https://github.com/libretro/RetroArch/issues/13165

Please introduce yourself in that issue.

**Comment by paulo101977** [comment]
> > I started a port of Xemu, but unfortunately I couldn't adapt it to libretro as I wanted; it only works for my Reinforcement Learning training.
> 
> That's cool! I linked to your repo in:
> 
> * [[Core Request] Xemu #13165](https://github.com/libretro/RetroArch/issues/13165)
> 
> Please introduce yourself in that issue.

Thanks. But as I said, the core only works for Reinforcement Learning. It still retains traces of the graphical interface, but hides them and depends on the OpenGL context created by the core itself, since I couldn't remove it properly.
