### ISSUE TITLE
Android: "Failed to install core"

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16037]
## Description
"Online Updater -> Core Downloader" is not downloading anything for me. A few weeks ago I could download cores, a few of them is installed. But now I get the message "Failed to install core: [core]".

All "Online Updater -> Update [entry]" (for example Update Joypad Profiles) entries are downloaded as expected.

### Expected behavior

Being able to download the cores as normal

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug
* Online Updater → Update Core Info Files
* "Online Updater -> Core Downloader -> [any core]" -- "Failed to install core: [core]"

I even get "Failed to install core: [core]", even after:
* Android -> Apps -> Retroarch -> Data storage -> Clear data/Clear cache -- interestingly the cores are not removed from /data/user/0/com.retroarch/cores/, when I open RetroArch and navigate to Online Updater ->  Core Downloader, they are still marked as installed.
* RetroArch: Settings -> Directory -> Cores: Set it to /storage/emulated/0/RetroArch/core (after I have created the directory first)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.9.12

### Environment information

- OS: Android 10

**Comment by i30817** [comment]
I suspect there is a reason why the RetroArch android default core dir is inside the sandbox. It might be that that's the only way to load or even download executable dlls in the android sandbox.

Ie: reset `RetroArch: Settings -> Directory -> Cores` and try again.

I get you probably changed this because you wanted to try cores that are not supported by the default downloader, but ....

**Comment by davidhedlund** [comment]
> Ie: reset `RetroArch: Settings -> Directory -> Cores` and try again.

Doesn't work

**Comment by i30817** [comment]
Damn. The log says nothing?

**Comment by davidhedlund** [comment]
> Damn. The log says nothing?

unfortunately only "Failed to install core: [core]"

**Comment by davidhedlund** [comment]
> * Android -> Apps -> Retroarch -> Data storage -> Clear data/Clear cache -- interestingly the cores are not removed from /data/user/0/com.retroarch/cores/, when I open RetroArch and navigate to Online Updater ->  Core Downloader, they are still marked as installed.

@RobLoach @hizzlekizzle I'm blocked from evaluating game pads in Android. If you know how to really factory reset RA in Android, please let me know.

**Comment by i30817** [comment]
One way you can reset is to move (or delete if you don't care about the settings) the retroarch.cfg

It's usually in `/storage/emulated/0/Android/data/com.retroarch/files`

But can also be in (if you installed the older versions of the android RetroArch) `/storage/emulated/0/Android/data/com.retroarch.aarch64/files`

**Comment by davidhedlund** [comment]
> One way you can reset all settings is to rename (or delete if you don't care about the settings) the retroarch.cfg

I know, but I need to wipe the installed cores as I pointed out. I know how to do that manually. I'm just looking for a simple way to remove everything so my disk look in the same stat that it was _before_ I installed RA.

**Comment by i30817** [comment]
RetroArch android cores are supposed to be in the sandbox (although the path you showed wasn't, which is why I know you probably changed it), so the only way to reset those is to uninstall RetroArch.

At least the RetroArch android installed from the site, not sure how the situation on the playstore is.


But why do you want to do that, the online updater should update android cores (again, in the site version, it's quite possible that the playstore has that disabled because playstores dislike dlls updates in programs).

**Comment by davidhedlund** [comment]
> so the only way to reset those is to uninstall and reinstall RetroArch.

That did the trick. I just Removed it from android before and/or used both F-Droid and Google Play version, so I'm pretty confused about the actual cause.

**Comment by davidhedlund** [comment]
@hizzlekizzle @RobLoach Solved, I'm able to continue my evaluation of RetroArch for Android.

**Comment by elektrinis** [comment]
I'm having the same issue. Tried to uninstall and reinstall, same issue.

**Comment by davidhedlund** [comment]
> I'm having the same issue. Tried to uninstall and reinstall, same issue.

We figured out how to solve it. Just read the whole post.
