### ISSUE TITLE
[Feature Request] Automatically download assets on first boot (Android)

### ISSUE THREAD

**Issue by guoyunhe** [libretro/RetroArch#16033]
## Description

I am using the F-Droid version 1.16. My Android system language is Chinese. When I run RetroArch, the default UI is full of "???" because it miss the fonts from assets. This state makes it impossible to use.

![Screenshot_2023-12-23-19-57-39-386_com retroarch](https://github.com/libretro/RetroArch/assets/5836790/d5a42924-72d5-4613-9edc-7ffbdccb4ef3)

So I suggest, when first run and assets are missing, RetroArch on Android should try to download assets. This can solve language displaying issue, for Chinese, Korean, Japanese, etc.

### Expected behavior

Assets should be automatically downloaded and UI will be refreshed.

### Actual behavior

The UI is full of "???". Assets are not automatically downloaded.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16 (F-Droid)

### Environment information

- OS: Android
- Compiler: No

**Comment by RobLoach** [comment]
Thanks! https://github.com/libretro/RetroArch/issues/16126
