### ISSUE TITLE
Quit on Close Content CLI no longer working 

### ISSUE THREAD

**Issue by Jetup13** [libretro/RetroArch#16048]
## Description

Quit on Close Content (CLI) no longer works on Android when launching from adb or frontends such as Daijishou. Quit on Close Content (ON) works as intended. 

### Expected behavior

When Quit on Close Content CLI is set RetroArch is supposed to close on Close Content if it was opened from command but not when RetroArch itself is launched a game

### Actual behavior

RetroArch heads back to the main menu. 

### Steps to reproduce the bug

1. Change RetroArch option: RetroArch > Settings > User Interface > Quit on Close Content > CLI
2. Launch game from external frontend or adb session
3. RetroArch Quick Menu > Close Content

### Bisect Results

Seems to have started happening around a week ago in the nightly builds. Maybe #16014

### Version/Commit

- RetroArch: 1.16.0/3ce56c5

### Environment information

- OS: Android

**Comment by hizzlekizzle** [comment]
yeah, seems a likely culprit. Any thoughts, @davidgfnet ?
