### ISSUE TITLE
RetroArch soft-hangs after a while

### ISSUE THREAD

**Issue by alecov** [libretro/RetroArch#16043]
## Description

RetroArch soft-hangs (loops on an `ioctl()` and stays into a D-state -- strace attached) eventually after a while, on any core. RetroArch does not leave this loop and must be killed.

It's a bit difficult to reproduce, but consistently happens after running any core for some amount of time (a couple hours mos). Can be reproduced more quickly by using fast-forward on the joystick; it typically happens on a few minutes then.

Attached is a strace of RetroArch when the issue happens. Seems like audio related (audio driver = tinyalsa). Also attached config file.

### Steps to reproduce the bug

1. Boot RetroArch 1.16 (does not happen in 1.15 or lower);
2. Boot any core;
3. Use fast-forward for a few minutes;
4. Eventually the core hangs and stays so forever. No other action is possible in RetroArch.

### Bisect Results

Will do it later if an obvious cause is not found by devs.

### Version/Commit

RetroArch 1.16
Does not seem to happen on 1.15 and previous versions.

### Environment information

Raspberry Pi 4B
- OS: ArchLinuxARM 64-bit (aarch64)
- Kernel: 6.1.69-1-rpi-ARCH
[retroarch.txt](https://github.com/libretro/RetroArch/files/13773198/retroarch.txt)
[strace.log](https://github.com/libretro/RetroArch/files/13773200/strace.log)

Cores tested: Nestopia, GenesisPlusGX, Snes9X... all builds from Lakka 4.3 (all of them work normally under 1.15-, so not a core issue).

**Comment by hizzlekizzle** [comment]
Are you using 1.16.0 stable or a nightly build? if the former, can you try the latter to see if it's already been caught?

**Comment by alecov** [comment]
Using stable. Will try with nightly soon (not today though, it's SNES night for the kids, so rolling back to 1.15 for now :)

**Comment by alecov** [comment]
Fixed on latest version. Way to go, lads.
