### ISSUE TITLE
(iOS) Menu bug - message boxes

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#1604]
Message boxes are not implemented. This means that when a dialog box is shown (either through the 'select button' or some other means), this is not shown right now.

It also means that the 'Help' action in the menu right now renders nothing.

**Comment by jeapostrophe** [comment]
I need to have a function that I write that is called by RA when it wants to display a message box. I can't tell how the menu system is supposed to know that a box should be popped up.
