### ISSUE TITLE
(iOS) Menu bug - core updater 

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#1605]
The problem with the iOS menu is that it tries to render the next view too quickly when pressing 'Core Updater'. 'Core Updater' in the background needs to do the following -

1 - FIrst it goes back to the menu loop and tries to do a 'deferred' action.
2 - It needs to get the URL first to the buildbot server, then it needs to generate a listing of all those URLs and populate the list view with it.
3 - Then it's done and the 'view' can be generated.

The problem right now is that the iOS menu tries to render the 'core updater' list before that list has actually been generated. This is why the Core Updater list sometimes shows nothing at all in the iOS menu while if you try the same action in RGUI/XMB/GLUI it actually shows something.

I've tried to come up with solutions for this before and at some point the iOS menu did render the core updater list correctly after one or more unsuccessful tries but this seems to have not been good enough.

**Comment by jeapostrophe** [comment]
I can provide a function pointer that RA can call when the current menu needs to be refreshed. If you could make it so that this was done, then all the ObjC would do is [self.mainmenu menuRefresh] in the cocoa touch UI.
