### ISSUE TITLE
RetroArch display version behind current release

### ISSUE THREAD

**Issue by TrevorSayre** [libretro/RetroArch#16065]
Looking at https://github.com/libretro/RetroArch/blob/v1.16.0.3/version.all#L12 it seems that it shows 1.16.0 when the current version is 1.16.0.3

Is it intentional to not include the full current version string or is this something reasonable to open a PR to update?

**Comment by sonninnos** [comment]
Those were simply ninja hotfixes which were done out of necessity, so no need to worry about it anymore.
