### ISSUE TITLE
(iOS) Menu bug - Core Options - no controls

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#1607]
Basically anything that is currently subdivided into the category 'Options' doesn't have working controls.

This includes:
 - Core Options 
- Shader Options
- Video Options

Therefore right now it's impossible to actually change any core options. This is a big usability problem right now and it forces people to go back to RGUI/XMB/GLUI again in order to be able to do this.

**Comment by jeapostrophe** [comment]
I believe that if RA is giving the right kind of menu structure, it would be fine. What makes these different?
