### ISSUE TITLE
[tvOS] No shaders available

### ISSUE THREAD

**Issue by kerberjg** [libretro/RetroArch#16083]
## Description & Steps to reproduce

I'm unable to activate any shaders when running RetroArch on tvOS.
Once in a game, I do the following:

1. Quick Menu
2. Shaders
3. Video Shaders -> ON
4. Load Preset
5. Folder "shaders_slang" (the only folder available)
6. Any of the subsequent subfolders (eg. "crt/shaders") are empty

I've tried this with the following video backends: gl, metal, vulkan

### Version/Commit
I've tried both the latest stable and nightly:

- RetroArch: 1.16.0 (stable)
- RetroArch: 1.16.0 74453fb (nightly, Jan 6 2024)

### Environment information

- OS: tvOS 17.2
- Device: Apple TV 4k (A2843)

Please let me know if this is intended behavior (no support yet?), and if not if there's anything I can do to help with troubleshooting.

Cheers ✨

**Comment by warmenhoven** [comment]
Did you download the shaders from the Online Updater in the Main Menu?

**Comment by kerberjg** [comment]
Yes and no. I was downloading the "Slangp" shaders while in "Metal" mode, but the problem was that every time I'm starting emulation, it forcefully switches the renderer to "gl", so the .slangp shaders don't show up.

When I download the shaders after I manually switch the renderer to "gl", I can see the .glslp shaders and apply them.

The force-switch to GL seems to be an issue with the Mupen core (could be related to https://github.com/libretro/mupen64plus-libretro-nx/pull/508, as we spoke about it?).
It's a bit unusual because I'm using the same core with Metal and .slangp shaders on my M1 Macbook, but probably not an issue with Retroarch itself.

Either way, downloading GL shaders seems to fix the issue, so I'll close this. Thanks for the help 😊

**Comment by warmenhoven** [comment]
On the GLideN64 core only works on GL so it would make sense that it's switching to gl. On the MacBook as it already has the parallel rdp/rsp plugins it would stick with Vulkan. (Incidentally, why use Metal at all? It's effectively forcing everything to prefer software rendering, as no core implements a native metal renderer. The libretro API doesn't even allow for that right now, even if there was a core that could.)

Glad you got it sorted!

**Comment by kerberjg** [comment]
Ah makes sense! Honestly I don't have any particular reason for using Metal directly, might as well just stick to Vulkan on everything whenever possible.

So I guess for the other issue I could hope to see Vulkan/Metal work when your changes get merged in
