### ISSUE TITLE
Android: Run "Update Core Info File" automatically for "Core Downloader" if the "cores" directory is empty

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16087]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

### Expected behavior

1) If you go to "Main Menu -> Online Updater -> Update Core Info Files" and 2) if you have not executed "Main Menu -> Online Updater -> Update Core Info Files" before first[1] it should be automated.

1: many people don't know that you have to do this in Android since it's not needed in GNU/Linux for example because packages are downloaded from the terminal

### Actual behavior
Main Menu -> Online Updater -> Update Core Info Files -- the list is empty

### Steps to reproduce the bug
* In Android: Clear data for RetroArch first (this will wipe everything, do it at your own risk)

In RetroArch:
* Main Menu -> Online Updater -> Update Core Info Files -- the list is empty
* Main Menu -> Online Updater -> Core Downloader
* Main Menu -> Online Updater -> Update Core Info Files -- the list is populated now

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 (F-Droid)

### Environment information

- OS: Android
- Compiler: -

**Comment by hizzlekizzle** [comment]
This is equally an issue (or not) regardless of which platform you're on. I think it's a decent idea, myself.

**Comment by RobLoach** [comment]
Rather than having it download them on runtime, could we package the .info files with the .apk?

**Comment by warmenhoven** [comment]
The .info files are packaged with the .apk. I'm not sure why it's not seeing them properly. I think what happened was at some point the android packaging got updated in a way that wasn't entirely compatible with the current `bundle_assets` handling.

**Comment by warmenhoven** [comment]
Unrelated to Android, I've started working on this for tvOS. tvOS has a completely different problem with the current `bundle_assets` handling that is probably best served by having it downloaded at runtime due to other limits on the .ipa size. That handling will probably end up covering this case as well.

**Comment by warmenhoven** [comment]
https://github.com/libretro/RetroArch/pull/16088

**Comment by RobLoach** [comment]
Optimally it would ship both the assets and .info files with the package, and be accessible. RetroArch should be usable if you don't have an internet connection :upside_down_face:

**Comment by warmenhoven** [comment]
Yeah, I see your point. I've tweaked the PR so it still prefers assets.zip but if it can't open it for whatever reason it will fall back to downloading what it needs.

On tvOS it's sort of assumed that there's always a network connection as the device isn't really usable without one.

**Comment by davidhedlund** [comment]
> # First and foremost consider this:
> 
>     * Only RetroArch bugs should be filed here. Not core bugs or game bugs
> 
>     * This is not a forum or a help section, this is strictly developer oriented
> 
> 
> ## Description
> ### Expected behavior
> 
>     1. If you go to "Main Menu -> Online Updater -> Update Core Info Files" and 2) if you have not executed "Main Menu -> Online Updater -> Update Core Info Files" before first[1] it should be automated.
> 
> 
> 1: many people don't know that you have to do this in Android since it's not needed in GNU/Linux for example because packages are downloaded from the terminal
> ### Actual behavior
> 
> Main Menu -> Online Updater -> Update Core Info Files -- the list is empty
> ### Steps to reproduce the bug
> 
>     * In Android: Clear data for RetroArch first (this will wipe everything, do it at your own risk)
> 
> 
> In RetroArch:
> 
>     * Main Menu -> Online Updater -> Update Core Info Files -- the list is empty
> 
>     * Main Menu -> Online Updater -> Core Downloader
> 
>     * Main Menu -> Online Updater -> Update Core Info Files -- the list is populated now
> 
> 
> ### Bisect Results
> 
> [Try to bisect and tell us when this started happening]
> ### Version/Commit
> 
> You can find this information under Information/System Information
> 
>     * RetroArch: 1.16.0 (F-Droid)
> 
> 
> ### Environment information
> 
>     * OS: Android
> 
>     * Compiler: -

You don't need to run `Update Core Info Files` before `Core Downloader` with retroarch.apk (200 MB) downloaded from https://retroarch.com/ since it already comes bundled with the core info files.

But I the F-Droid apk is only 23.5 MB and is not bundles with the core info files. So if a package comes without the core info files, it would be nice if RetroArch detected this and downloaded them automatically.

**Comment by RobLoach** [comment]
> But I the F-Droid apk is only 23.5 MB and is not bundles with the core info files.

Where is the F-Droid package source? The package maintainer should add the assets, .info files, shaders, everything.

**Comment by davidhedlund** [comment]
> > But I the F-Droid apk is only 23.5 MB and is not bundles with the core info files.
> 
> Where is the F-Droid package source? The package maintainer should add the assets, .info files, shaders, everything.

Thank you. I copy/pasted that to https://gitlab.com/fdroid/rfp/-/issues/1933#note_1719595052

**Comment by licaon-kter** [comment]
> Where is the F-Droid package source? 

https://f-droid.org/packages/com.retroarch/ -> build metadata -> https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.retroarch.yml#L52-L83

> The package maintainer should add the assets, .info files, shaders, everything.

Really? I've literally interacted for 6 months with this community asking how to build this ,and getting feedback and advice all the way, about WHAT to include: https://github.com/libretro/RetroArch/issues/11922 and the conclusion is: _I did it wrong_????

C'mon :disappointed:

**Comment by davidhedlund** [comment]
> > Where is the F-Droid package source?
> 
> https://f-droid.org/packages/com.retroarch/ -> build metadata -> https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.retroarch.yml#L52-L83
> 
> > The package maintainer should add the assets, .info files, shaders, everything.
> 
> Really? I've literally interacted for 6 months with this community asking how to build this, and getting feedback and advice all the way, about WHAT to include: #11922 and the conclusion is: _I did it wrong_????
> 
> C'mon 😞

Your time and contributions are deeply appreciated. But can you please complement it to make it more useful?

**Comment by licaon-kter** [comment]
I've asked continuously WHAT and HOW to include.

IF you have the answers please don't keep them secret :shrug:

**Comment by licaon-kter** [comment]
> Let's continue the conversation at https://github.com/libretro/RetroArch/issues/11922 @RobLoach

Maybe better here as that one is huge

**Comment by davidhedlund** [comment]
> > Let's continue the conversation at #11922 @RobLoach
> 
> Maybe better here as that one is huge

This issue is dedicated to something else. Feel free to open a new issue and send the link here.

**Comment by davidhedlund** [comment]
> > Let's continue the conversation at #11922 @RobLoach
> 
> Maybe better here as that one is huge

Here you go: https://github.com/libretro/RetroArch/issues/16126

**Comment by RobLoach** [comment]
> I've asked continuously WHAT and HOW to include.

That's excellent! Thanks for linking the F-Droid package. Hopefully we can help out in packaging these assets 👍

**Comment by davidhedlund** [comment]
> > I've asked continuously WHAT and HOW to include.
> 
> That's excellent! Thanks for linking the F-Droid package. Hopefully we can help out in packaging these assets 👍

Can we help out with that here?:
* https://github.com/libretro/RetroArch/issues/16126

**Comment by davidhedlund** [comment]
* This issue was resolved in RetroArch version 1.20.0, where `Main Menu -> Online Updater -> Core Downloader` is properly populated.
* The issue persisted in RetroArch version 1.19.0, where `Main Menu -> Online Updater -> Core Downloader` remained empty by default (note: do not run `Main Menu -> Online Updater -> Update Core Info Files`, as this will invalidate the test).
