### ISSUE TITLE
Fast Forward Toggle turns off when entering menu

### ISSUE THREAD

**Issue by cepheiduck** [libretro/RetroArch#16086]
In past iterations, Fast Forward toggle stays on when entering the Quick Menu or Menu screen.  Now it turns off and needs to be pressed again.

Last time functioning as expected was early November build of 1.16.0.3, got most recent built on 1/6/24

Expecting Fast Forward to stay toggled on after entering the RetroArch menu screen, but it toggles off instantly.
Using ozone menu.  Retroachevements are on (softcore mode).  Same behavior on any core.

This is on the Android build, from the most recent github master branch

Let me know if more is needed, thanks!  I'm not sure what changed since early November and now that could affect.

**Comment by Nightfire391** [comment]
Same issue on the pc/linux version being used on a steamdeck been this way since it was updated

**Comment by sonninnos** [comment]
It was done on purpose.

**Comment by Nightfire391** [comment]
> It was done on purpose.

Why though?

**Comment by Nightfire391** [comment]
> So that there is no need to make special exceptions for slowing down menu or toggling FF off and back on in all cases when menu does not pause the core.

And we really needed this? it was fine before the update now having to toggle the FF on again every time i open the menu its just annoying

**Comment by sonninnos** [comment]
Well it was less annoying to me to switch it back on if needed, instead of panicking to turn it off first.

**Comment by Nightfire391** [comment]
What ended the conversation the mention of Pokemon - most GBA games are slow and require FF and some people make mistakes and need to undo a state either way FF shouldn't be turned off every time the user accesses the menu imo

**Comment by Nightfire391** [comment]
1.17.0 update still the same. I guess its permanent

**Comment by cepheiduck** [comment]
I had not been able to find any notes about this feature being removed so I wasn't sure if this was on purpose.  If so, it would be nice to be able to be returned in some fashion.

**Comment by Nightfire391** [comment]
> I had not been able to find any notes about this feature being removed so I wasn't sure if this was on purpose. If so, it would be nice to be able to be returned in some fashion.

Im not sure if you understand correctly no feature is being removed

Fast Forward turns off when ever the user enters the menu this is the reason

>So that there is no need to make special exceptions for slowing down menu or toggling FF off and back on in all cases when menu does not pause the core. Quote by sonninnos

i personally find this annoying as i use FF when playing GBA games such as pokemon if i find a shiny and accidentally load state i got to go into the menu undo load state and turn on FF again.

>Well it was less annoying to me to switch it back on if needed, instead of panicking to turn it off first. Quote by sonninnos

Before the 1.16.3 patch i do not recall anyone having an issue with this and no one panicked about having to turn it off before entering the menu so my perspective is why fix what isn't broken we didn't need this change imo

>1.17.0 update still the same. I guess its permanent. quote by Nightfire391(me)

1.17.0 update happened and its not been reverted so I'm guessing its permanent
