### ISSUE TITLE
(iOS) Menu bug - doesn't autostart core that doesn't require a game ROM loaded

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#1608]
Certain cores (like 2048, ScummVM) have a certain flag enabled that allows these cores to be directly booted without loading a ROM. So as soon as you select a core from the 'Core List', if this 'flag' is set, the core should be directly booted. RGUI/GLUI/XMB right now does this, but the iOS menu does not so far.

These cores like 2048 and ScummVM normally have a built-in GUI or the 'game assets' are baked into the core itself so they don't require you to load some ROM to be able to use them.

**Comment by jeapostrophe** [comment]
I believe that the action associated with the Load Core menu entry needs to do more and then make sure that ui_companion_cocoatouch_notify_content_loaded is called
