### ISSUE TITLE
Settings -> User Interface -> Menu: Add "requires restart" to the description text

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16104]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

* Settings -> User Interface -> Menu. The entry description text "Menu driver to use" could be improved by adding "Menu driver to use, requires restart"
* Even better: Switch to the new driver right away

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

![image](https://github.com/libretro/RetroArch/assets/6416073/c9a8df6b-3843-4980-9ba0-fa258aebe4ab)

The new driver is not used when the value is changed:

![image](https://github.com/libretro/RetroArch/assets/6416073/dbc61b69-a08c-428e-83c5-68edb756937b)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 Appimage

### Environment information

- OS: GNU/Linux
- Compiler: [In case you are running local builds]

**Comment by davidhedlund** [comment]
Related: https://github.com/libretro/RetroArch/pull/15611

**Comment by davidhedlund** [comment]
@sonninnos What do you think?

**Comment by sonninnos** [comment]
Very complicated the last time I checked, since menu driver is so central. Drivers like audio can already be changed without restarting by doing reinit (for example with fullscreen toggle), but menu driver will go apeshit with that trick..

**Comment by davidhedlund** [comment]
> Very complicated the last time I checked, since menu driver is so central. Drivers like audio can already be changed without restarting by doing reinit (for example with fullscreen toggle), but menu driver will go apeshit with that trick..

Aiite. So perhaps we can start with my first suggestion?:
* Settings -> User Interface -> Menu. The entry description text "Menu driver to use" could be improved by adding "Menu driver to use, requires restart"
