### ISSUE TITLE
Random menu driver, and assets are randomly not used

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16102]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The fonts and the icons are missing.

See also: https://www.reddit.com/r/RetroArch/comments/10w2oeo/problem_with_interface_fonts_in_retroarch/

### Expected behavior

Shouldn't XMB be used by default?

### Steps to reproduce the bug

Extract RetroArch.7z that contains a directory called RetroArch-Linux-x86_64 with the following content:
* RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/
* RetroArch-Linux-x86_64.AppImage

* Execute RetroArch-Linux-x86_64.AppImage

The menu drivers are changed randomly, and sometimes the fonts and icons are not used from the assets directory

#### Random 1
![image](https://github.com/libretro/RetroArch/assets/6416073/1a146a84-754a-4bfb-8910-457436dce5db)

#### Random 2
![image](https://github.com/libretro/RetroArch/assets/6416073/d8fa92c6-9268-455d-81a1-dd6a6199a42f)

#### Random 3
I changed the menu driver to ozone, but a few hours later I deleted the RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/ directory, but it still started with ozone.

![image](https://github.com/libretro/RetroArch/assets/6416073/3ff238df-8d67-4e1b-9497-a0563b86d83b)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 Appimage

### Environment information

- OS: GNU/Linux
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment]
Something is really wrong with your setup. Try compiling from source, or fix the appimage install you're using. Online Updater > Update Assets will download the assets and re-load the menu.

> Shouldn't XMB be used by default?

Depends on the platform. Some hardware doesn't have the power to run ozone.

**Comment by davidhedlund** [comment]
> Something is really wrong with your setup. Try compiling from source, or fix the appimage install you're using. Online Updater > Update Assets will download the assets and re-load the menu.
> 
> > Shouldn't XMB be used by default?
> 
> Depends on the platform. Some hardware doesn't have the power to run ozone.

When this happens, I delete the `RetroArch-Linux-x86_64` directory and extract `RetroArch.7z` to start all over, but it still happens. I agree that this is odd. I just installed my distro from scratch, so I'm sure nothing is wrong with it.

**Comment by davidhedlund** [comment]
> Something is really wrong with your setup. Try compiling from source, or fix the appimage install you're using. Online Updater > Update Assets will download the assets and re-load the menu.
> 
> > Shouldn't XMB be used by default?
> 
> Depends on the platform. Some hardware doesn't have the power to run ozone.

I just solved it, for some reason the assets directory is set to "/usr/share/libretro/assets/" instead of "[...]/RetroArch-Linux-x86_64/RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/assets" in the Appimage.

**Comment by davidhedlund** [comment]
* https://github.com/hizzlekizzle/RetroArch-AppImage/issues/7
