### ISSUE TITLE
"Main Menu -> Online Updater -> Update Assets": assets.zip is not extracted

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16101]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
"Main Menu -> Online Updater -> Update Assets" exist in the Appimage, but it failed to extract assets.zip.

### Expected behavior

The assets should be applied.

### Actual behavior

"Extracting 'assets.zip'"

### Steps to reproduce the bug

Extract RetroArch.7z that contains a directory called RetroArch-Linux-x86_64 with the following content:
* RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/
* RetroArch-Linux-x86_64.AppImage

* Main Menu -> Online Updater -> Update Assets
* "Downloading assets.zip"
![image](https://github.com/libretro/RetroArch/assets/6416073/45781cf1-3f6e-47d4-9754-cd498fa870f9)

* But assets.zip is not extracted. RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/assets/ is empty.

#### "Main Menu -> Online Updater -> Update Controller Profiles" (control)
* Main Menu -> Online Updater -> Update Controller Profiles
* "Downloading autoconfig.zip"

![image](https://github.com/libretro/RetroArch/assets/6416073/871d5618-803d-4cd3-8fd5-a7fb6ce44c78)

* "Extracting 'autoconfig.zip'"

![image](https://github.com/libretro/RetroArch/assets/6416073/991d701b-fbbc-4695-8cb4-5f490773e848)

* The files have been extracted to .config/retroarch/autoconfig/

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 Appimage

### Environment information

- OS: GNU/Linux
- Compiler: [In case you are running local builds]

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16102

**Comment by RobLoach** [comment]
You don't need to use that option since the appimage ships with all the assets already. We should likely disable that menu item, but I'm unsure we're able to do that currently.

**Comment by davidhedlund** [comment]
> You don't need to use that option since the appimage ships with all the assets already.

Oh, but what if you want to just update the assets to the latest version?

> We should likely disable that menu item, but I'm unsure we're able to do that currently.

The Appimage also comes with the autoconfig directory, so is it likely that the "Update Controller Profiles" also will be disabled?

**Comment by RobLoach** [comment]
> Oh, but what if you want to update the assets to the latest version?

Then work with the distro maintainer to update them, or change the location of the assets directory in your .cfg.

**Comment by davidhedlund** [comment]
> > Oh, but what if you want to update the assets to the latest version?
> 
> Then work with the distro maintainer to update them, or change the location of the assets directory in your .cfg.

Do you want to open a new issue titled something like: [Menu] Remove "Update Assets", and "Update Controller Profiles"?

**Comment by RobLoach** [comment]
No, thank you. If you have questions like this, you'll likely get better responses in the Forum or on Discord.

**Comment by davidhedlund** [comment]
> ...or change the location of the assets directory in your .cfg.

That's correct. I had to modify `assets_directory = "/usr/share/libretro/assets/"` to `assets_directory = "~/.config/retroarch/assets/"`. After that, `Main Menu -> Online Updater -> Update Assets` extracted the assets.zip file.

I opened this issue for the appimage:
* https://github.com/hizzlekizzle/RetroArch-AppImage/issues/7
