### ISSUE TITLE
HTML embed: Getting sent to home page

### ISSUE THREAD

**Issue by The-silly-goose** [libretro/RetroArch#16117]
### The bug

When I embedded the html code for the site, everything worked just fine until I tried to select a core. When I select any core, it sends me to my sites home page.

### Expected result

Core selects just fine.

### Actual result

I get sent to the home page

### Steps to reproduce the bug

1. Go to the selector
2. Select a core

### Bisect Results

I just tried it today and I found this bug

### Version/Commit
Couldn't start the machine because of this bug

- RetroArch: ?

### Environment information

- OS: N/A
- Compiler: Found html code on github

**Comment by The-silly-goose** [comment]
> What HTML code?

The code in the github files, look harder

**Comment by RobLoach** [comment]
k
