### ISSUE TITLE
Please document "Content dir"

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16111]
In RetroArch 1.7.3 these entries in Settings -> Directory has the value `<Content dir>` by default:
* "System/BIOS"
* "Save States"
* "Save Files"

The `<Content dir>` is the directory where you run Main Menu -> Load Content -> [any directory] -> Any game.

Example for the Wipout PlayStation game: Main Menu -> Load Content -> /home/karl/Games/WipEout (USA).cue
* You have to dump the BIOS at: /home/karl/Games/Desktop/scph5500.bin
* The save states will be saved at /home/karl/Games/Desktop/
* The saved files will be saved at /home/karl/Games/Desktop/

I didn't get any sane results by web searching: https://docs.libretro.com/ "content dir"

I think the exact term "Content dir" that is used in RetroArch, should be documented at https://docs.libretro.com/guides/change-directories/

Luckily, "Content dir" have been replaced with these values in RA 1.16.0 (appimage tested):
* "System/BIOS": retroarch/system
* "Save States": retroarch/states
* "Save Files": retroarch/saves

**Comment by gouchi** [comment]
Hi,

If the issue is related to documentation, please open an [issue in the dedicated repository](https://github.com/libretro/docs/issues).

Thank you.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/docs/issues/908
