### ISSUE TITLE
[Menu] Have "Save Controller Profile" say: Saved "[Controller driver directory]/[File]" in the Controller Profile Directory.

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16121]
# Current
`Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile` says `"Controller profile saved successfully."`, see bottom left on the screenshot:

![image](https://github.com/libretro/RetroArch/assets/6416073/5e84a5da-1645-4781-b549-0b240e284a48)

# Feature request
I suggest that `Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile` should say `"Saved new controller profile to [controller profile directory]/[device driver]/[$input_device].cfg."`.

Image manipulate example of the bottom of the screenshot:

This will make sure that people find the .cfg file, which is needed if they want to upload it for [retroarch-joypad-autoconfig](https://github.com/libretro/retroarch-joypad-autoconfig).

I spent about 24 hours coding a bash script used to generate dedicated autoconfig files, since I thought that "Save Controller Profile" was saved to retroarch.cfg. My script is useless since "Save Controller Profile" is actually already generating dedicated autoconfig files. However, this could have been prevented if the pop-up notification included the file path name. With that said, it's important that this issue becomes fixed to prevent other people from being confused in that want to upload autoconfig files. This issue is listed in:
* https://github.com/libretro/RetroArch/issues/16146

`Main Menu -> Configuration -> Save Current Configuration` displays [directory/file] so its source code can be reused.

## Proposed 1 (new)

Example:
* Saved "udev/Sony Interactive Entertainment DualSense Wireless Controller.cfg" in Controller Profile directory.

![image](https://github.com/libretro/RetroArch/assets/6416073/f037cca5-da8d-4df0-bc2f-6687ca33c916)

## Proposed 2 (old)

![image](https://github.com/libretro/RetroArch/assets/6416073/c2a8ef40-a760-4c35-9d1a-101d781a1b8f)

## Related issues

Smartphones with average screen size are too narrow, so this issue must be solved to make display the full text:
https://github.com/libretro/RetroArch/issues/16147

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by davidhedlund** [comment]
* https://github.com/libretro/docs/issues/909

**Comment by davidhedlund** [comment]
@RobLoach Since it costed me at least 24 hours of development time to make a script that turned out to be useless since RA already can do this, can we please implement this ASAP?

Also, it will help all users to find where the generated .cfg file is, which will prevent them from creating .cfg files from scratch by scraping variables from retroarch.cfg.

**Comment by RobLoach** [comment]
It saves the controller profile autoconfigs when you select Save to Controller Profile.

![Screenshot_20240115-080520.png](https://github.com/libretro/RetroArch/assets/25086/0f8c85bb-82f0-4cfd-844d-1260dcc7bfe6)

Configuration File > Save config will save RetroArch.cfg, with your controller settings.

**Comment by davidhedlund** [comment]
> It saves the controller profile autoconfigs when you select Save to Controller Profile.
> 
> ![Screenshot_20240115-080520.png](https://private-user-images.githubusercontent.com/25086/296763434-0f8c85bb-82f0-4cfd-844d-1260dcc7bfe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjQzNjAsIm5iZiI6MTcwNTMyNDA2MCwicGF0aCI6Ii8yNTA4Ni8yOTY3NjM0MzQtMGY4Yzg1YmItODJmMC00Y2ZkLTg0NGQtMTI2MGRjYzdiZmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEzMDc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MDViYTNmNjJlNDdjZWI4MTYxM2QwMzdiMTliZTUxYTg1ZjBhYmY2NDMyNTFhZWEyY2JiY2IxNzRmYjdjNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NXu0BFUQcoMl9QQ62z2tKHkSb4_p257MxEGqDcOiuXE)
> 
> Configuration File > Save config will save RetroArch.cfg, with your controller settings.

Thank you! Can you please delete this message to avoid confusion. I asked you what "Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile" did before but I figured it out, but "Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile" does not tell where the file will be saved, which is why I opened this issue.

**Comment by davidhedlund** [comment]
> We could add the file that it saves in the description too.

"Main Menu -> Configuration File -> Save Current Configuration" already show where the file is saved:

![image](https://github.com/libretro/RetroArch/assets/6416073/83bb8ecc-3164-4437-b02f-669e3c8e5018)

However, "Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile" does not mention where the file is saved, so I propose that. This is what this issue is about.

> Is there anything that appears in the console logs when run with --verbose?

No

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/15993

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16146

**Comment by davidhedlund** [comment]
@zoltanvb It should be very easy to display the saved file name to begin with. What do you think about it?

This will help people to find the autoconfig, so they can modify and upload it to https://github.com/libretro/retroarch-joypad-autoconfig

**Comment by zoltanvb** [comment]
I am investigating the issue, but got a bit stuck when trying to find out why sublabels do not appear in normal binds, only in quick menu :) Anyway, it is not forgotten, I just want to explore a few options for displaying it, as the popup messages are fading quick and may not help a casual user too much identifying a possibly quite long file name.

**Comment by davidhedlund** [comment]
> @zoltanvb It should be very easy to display the saved file name to begin with. What do you think about it?

Sorry, the directory path must be included _as well_, in order to distinguish it if the same config file name occur in multiple directories, which sometimes happen. This should be commented in the source code specifically for the "Save Controller Profile".

Do you know which responsible source code files that are involved when "Save Controller Profile" is activated? @zoltanvb

**Comment by zoltanvb** [comment]
The message display is here: https://github.com/libretro/RetroArch/blob/b209a26ebb9702459aaa8f09bb7ca269d85ff07d/menu/menu_setting.c#L2531

**Comment by davidhedlund** [comment]
> The message display is here:
> 
> https://github.com/libretro/RetroArch/blob/b209a26ebb9702459aaa8f09bb7ca269d85ff07d/menu/menu_setting.c#L2531

Thank you.

**Comment by davidhedlund** [comment]
@zoltanvb Does your commit add "[dir]/[file]" to the pop-up notification message seen at the bottom of the screenshot (copied from the top post)?:

![image](https://github.com/libretro/RetroArch/assets/6416073/8cd7d62b-7596-48e6-bacb-21dc99f43db3)

**Comment by davidhedlund** [comment]
`Main Menu -> Configuration -> Save Current Configuration` does that, so its source code could be reused for `Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile`

**Comment by zoltanvb** [comment]
No, it does not. I want to get some feedback with the PR before building on top of it.

Unfortunately it is not simple to reuse that, config saving is implemented via command structure, controller profile saving is direct.

**Comment by davidhedlund** [comment]
> No, it does not. I want to get some feedback with the PR before building on top of it.
> 
> Unfortunately it is not simple to reuse that, config saving is implemented via command structure, controller profile saving is direct.

Oh, I see.

Once this has been fixed, I'll take a screenshot of the pop-up notification message and upload it to https://www.retroarch.com/index.php?page=controller-autoconfig, in order to visually guide people how to find the generated autoconfig file (since this issue killed 72 working hours for me).

I deeply appreciate your contributions to solve this issue!

**Comment by odditude42** [comment]
recommendation (if this isn't already implemented elsewhere) - i'd suggest generally using "saved %file% to %path%" instead of "saved %path%/%file%" - this way, the most significant info is at the front of the notification.

**Comment by davidhedlund** [comment]
> recommendation (if this isn't already implemented elsewhere) - i'd suggest generally using "saved %file% to %path%" instead of "saved %path%/%file%" - this way, the most significant info is at the front of the notification.

Yeah, but that could be scaled for all settings. See:
* https://github.com/libretro/RetroArch/issues/16222

**Comment by RobLoach** [comment]
File paths often get really ugly as demonstrated in https://github.com/libretro/RetroArch/issues/16121#issuecomment-1947482785 . Could we keep this user-friendly and say "...in the Controller Profiles Directory" instead? If people want to know where that is, they can visit the Directory Settings.

**Comment by davidhedlund** [comment]
> File paths often get really ugly as demonstrated in [#16121 (comment)](https://github.com/libretro/RetroArch/issues/16121#issuecomment-1947482785) . Could we keep this user-friendly and say "...in the Controller Profiles Directory" instead? If people want to know where that is, they can visit the Directory Settings.

Multiple files with identical filenames exist in the autoconfig directory, as I pointed out in this [comment](https://github.com/libretro/RetroArch/issues/16121#issuecomment-1945087700).

**Comment by davidhedlund** [comment]
> File paths often get really ugly as demonstrated in [#16121 (comment)](https://github.com/libretro/RetroArch/issues/16121#issuecomment-1947482785) . Could we keep this user-friendly and say "...in the Controller Profiles Directory" instead? If people want to know where that is, they can visit the Directory Settings.

I just suggested that all pop-up text can be put in a text form here:
* https://github.com/libretro/RetroArch/issues/16147

**Comment by davidhedlund** [comment]
I suggest that `Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile` say: "Saved [Controller driver]/[File name]"

For example: "Saved udev/Sony Interactive Entertainment DualSense Wireless Controller.cfg"

**Comment by davidhedlund** [comment]
> File paths often get really ugly as demonstrated in [#16121 (comment)](https://github.com/libretro/RetroArch/issues/16121#issuecomment-1947482785) . Could we keep this user-friendly and say "...in the Controller Profiles Directory" instead? If people want to know where that is, they can visit the Directory Settings.

I suggest that `Settings -> Input -> RetroPad Binds -> Port 1 Controls -> Save Controller Profile` say: "Saved [Controller driver]/[File name] to the Controller Profiles Directory."

Example:

![image](https://github.com/libretro/RetroArch/assets/6416073/54a7bc73-f64b-43dc-a070-1e35e9df5c2d)

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16769
