### ISSUE TITLE
[Feature request] "Settings -> Core -> Manage Cores": Add the options seen at "Quick Menu -> Core Options"

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16125]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Please also read my slightly different solution of my feature request:
* https://github.com/libretro/RetroArch/issues/16127

I think it should be possible to configure the cores without having to _load games_ first to make it convenient. Also, this will help developers to quickly experiment with settings in RA configurations without games.

### Expected behavior

Here's an example of Core Options:
* Main Menu -> Load Content -> [Any game] -> [Any core] -- needed to access the Quick Menu 
* Quick Menu -> Core Options -- Here's the example of bsnes-hd beta:

![image](https://github.com/libretro/RetroArch/assets/6416073/d1e62bb6-5458-46b5-b2b5-68e871bec0a4)

### Actual behavior

Example for `bsnes-hd beta`

![image](https://github.com/libretro/RetroArch/assets/6416073/ac9399ac-d6df-4247-a4a7-4017f740b1d6)

### Steps to reproduce the bug

* Settings -> Core -> Manage Cores -> [Select a any core]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0

### Environment information

- OS: Any
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment]
Very similar to the other issue. Its been discussed, and there is technical complexity behind accomplishing it. 

Please slow down on making issues, it's very difficult to keep up and groom them. I suggest asking in Discord before resulting in making issues.
