### ISSUE TITLE
Cannot load cores that I've downloaded manually

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16128]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I cannot load any core that I have manually downloaded and extracted to the core directory.

### Expected behavior

Should it not be listed? What have I missed?

### Actual behavior

The `bsnes hd` is not listed in `Load Core`

### Steps to reproduce the bug

* Downloaded http://buildbot.libretro.com/nightly/linux/x86_64/latest/bsnes_hd_beta_libretro.so.zip
* Extracted bsnes_hd_beta_libretro.so.zip
* Moved bsnes_hd_beta_libretro.so to ~/Downloads//RetroArch-Linux-x86_64/RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/cores/
* Opened ~/Downloads//RetroArch-Linux-x86_64/RetroArch-Linux-x86_64.AppImage
* In RetroArch: `Load Core`

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by davidhedlund** [comment]
@RobLoach Can you please give me a minute on this?

**Comment by RobLoach** [comment]
Logs

**Comment by davidhedlund** [comment]
> Logs

The logs directory is empty. What do you want me to do specifically?

**Comment by RobLoach** [comment]
Enable verbose logging and post the logs https://docs.libretro.com/guides/generating-retroarch-logs/

**Comment by davidhedlund** [comment]
> Enable verbose logging and post the logs https://docs.libretro.com/guides/generating-retroarch-logs/

[retroarch.log](https://github.com/libretro/RetroArch/files/13968021/retroarch.log)

**Comment by davidhedlund** [comment]
* https://github.com/libretro/docs/issues/912

**Comment by RobLoach** [comment]
When you go to Load Core, it doesn't appear? It's likely because the info file isn't there or something. Try passing it as an command line argument.

```
retroarch -L mycore.so mycontent.zip
```
As for AppImage, make an issue for the repo over at https://github.com/hizzlekizzle/RetroArch-AppImage

AppImage uses its own set of libraries to my knowledge, so there's likely a missing library that bsnes-hd expects if it errors out when loading.

**Comment by davidhedlund** [comment]
> When you go to Load Core, it doesn't appear? It's likely because the info file isn't there or something. Try passing it as an command line argument.
> 
> ```
> retroarch -L mycore.so mycontent.zip
> ```
> 
> As for AppImage, make an issue for the repo over at https://github.com/hizzlekizzle/RetroArch-AppImage
> 
> AppImage uses its own set of libraries to my knowledge, so there's likely a missing library that bsnes-hd expects if it errors out when loading.

Rob, you made my day! 😁 It's working with the commands (I added them to the proposed documentation sample).

**Comment by davidhedlund** [comment]
This is not an Appimage issue for me specifically. I just reproduce the issue for the retroarch package for GNU/Linux. Should the issue be re-opened @RobLoach ?

**Comment by RobLoach** [comment]
I believe you need the associated .info file. Either that or RetroArch is unable to load the file for the data itself.

**Comment by davidhedlund** [comment]
"[I can't reproduce this issue. I downloaded the appimage and put a core (bsnes-hd_beta) into the portable home's .config/retroarch/cores directory and it popped right up in 'load core'.](https://github.com/hizzlekizzle/RetroArch-AppImage/issues/6#issuecomment-1897770510)" - @hizzlekizzle 

* Which distro did you use?

**Comment by davidhedlund** [comment]
> I believe you need the associated .info file.

* cores/bsnes_hd_beta_libretro.info -- this files is shipped with the Appimage
* cores/bsnes_hd_beta_libretro.so -- this is the file that I downloaded/extrected, the file name match the info file

> Either that or RetroArch is unable to load the file for the data itself.

Yeah. I'm running Trisquel 11 (a distro based on Ubuntu 22.04).

I really want to solve this. Why don't you think that the issue should be re-opened?

**Comment by davidhedlund** [comment]
> When you go to Load Core, it doesn't appear? It's likely because the info file isn't there or something. Try passing it as an command line argument.
> 
> ```
> retroarch -L mycore.so mycontent.zip
> ```

It works as I said before, but it's very inconvenient to include the file path to the game file every single time. I rather load the game from the file browser in RetroArch. But apparently it's not possible to run just:

`retroarch -L mycore.so`

man retroarch says:

```
       -L PATH, --libretro PATH
              Path to a libretro implementation which is to be used.  This option will override any setting in a config file.  This option is only available  if  RetroArch  is  compiled
              with dynamic libretro loading.
```

It does not say anything that the file to a game must be passed. Have I missed something?

**Comment by i30817** [comment]
Info files currently have their own user settable directory. Check if your core info file is in the setting your RetroArch install has as the info directory in settings > directory.

**Comment by davidhedlund** [comment]
"[Something is going on somewhere in your system, then, because it should definitely work for a regular linux install (self-compile or whatever). And, of course, "works on my machine"](https://github.com/hizzlekizzle/RetroArch-AppImage/issues/6#issuecomment-1899223195)" - @hizzlekizzle

I just merged the discussion here so I have everything gathered in one place.
