### ISSUE TITLE
"Device Type" is not always visible

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16133]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

"Device Type" is not always visible

### Expected behavior

`Device Type` should always be listed. There are no options to permanently change the Device Type setting, so you are dependent to access it, since you have set it to DualAnalog to use both thumb sticks for Sony PlayStation controllers.

### Actual behavior

`Device Type` is not always listed.

### Steps to reproduce the bug

* Open `Settings -> Input -> RetroPad Binds -> Port 1 Binds`. `Device Type` is not listed.
* Load a game, then open `Settings -> Input -> RetroPad Binds -> Port 1 Binds`. `Device Type` is sometimes listed, sometimes not.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 Appimage

### Environment information

- OS: GNU/Linux
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment]
This is intended. The device type depends on the core that's loaded.

**Comment by davidhedlund** [comment]
> This is intended. The device type depends on the core that's loaded.

Well, as I initially reported:
> * Load a game, then open `Settings -> Input -> RetroPad Binds -> Port 1 Binds`. `Device Type` is sometimes listed, sometimes not.

This is for the `libretro-beetle-psx` GNU/Linux package. Whe I load a game with that core (known as `PlayStation (Mednafen PSX)` in RA) sometimes I don't get access to the "Device type" which makes it impossible to set it to "DualAnalog".

**Comment by sonninnos** [comment]
No, the option is never there in global input settings anymore. Only under Quick Menu Controls, because it is the emulated device type, which is core dependent.

**Comment by davidhedlund** [comment]
> No, the option is never there in global input settings anymore. Only under Quick Menu Controls, because it is the emulated device type, which is core dependent.

Oh, now I understand why I only say "Device Index" "randomly". Thank you very much!
