### ISSUE TITLE
Keyboard LED driver only partially working in X11

### ISSUE THREAD

**Issue by rdagger** [libretro/RetroArch#16141]
## Description
The keyboard LED driver for linux X11 only works for scroll lock.  The num lock and caps lock do not function properly.  However, I verified that all 3 work correctly in Windows.

### Expected behavior
In mame 2003 plus, many games will flash LED 1 when player 1 coin is inserted and LED 2 when player 2 coin is inserted.  This allows you to illuminate the start player buttons when coins are inserted.  The [RA keyboard driver](https://docs.libretro.com/guides/led-drivers/#keyboard-driver) allows you to route LED 1 and LED 2 to num lock, caps lock and scroll lock.
For example, the following configuration should map LED 1 to num lock and LED 2 to caps lock.
```
led_driver = "keyboard"
led1_map = "0"
led2_map = "1"
```

### Actual behavior
No LED's blink with the above configuration.  Changing either led1_map or led2_map to 2 will flash the scroll lock LED correctly.
I verified that the /sys/class/leds/ keyboard brightness settings for scroll lock are toggling but not for num lock or caps lock.

### Steps to reproduce the bug
1. Set retroarch.cfg as follows:

```
led_driver = "keyboard"
led1_map = "0"
led2_map = "1"
```

2. Play Asteroids in mame 2003 plus on a Linux system with X11 support. 
3. Insert coins.
4. Check keyboard num lock and caps lock LED's (nothing happens).
5. Change led1_map as follows and the scroll lock will flash:
`led1_map = "2"`

### Bisect Results
Not sure if this ever worked correctly in X11
 
### Version/Commit
RetroArch Version: 1.15.0
Build Date: Oct 14, 2023
Mame 2003-Plus (32fa606)

### Environment information
Batocera 38oc2023/10/14 21:43

**Comment by sonninnos** [comment]
Pretty sure some of those leds require some kind of permission things to set first, and then they work. Probably should have documented it when adding the feature..

**Comment by rdagger** [comment]
Thanks, I got it working.  I was unable to use xkbcomp in Batocera so I did the following:

ssh into Batocera

```
mount -o remount,rw /
nano /usr/share/X11/xkb/compat/ledcaps
```

modify line !allowExplicit to allowExplicit
save and exit nano

`nano /usr/share/X11/xkb/compat/lednum`

modify line !allowExplicit to allowExplicit
save and exit nano

`batocera-save-overlay`

**Comment by rdagger** [comment]
![image](https://github.com/libretro/RetroArch/assets/106355/d4a44af3-3dcf-4d20-910e-f58fc26ea073)
