### ISSUE TITLE
In-game saves is a mess.

### ISSUE THREAD

**Issue by clorophilla** [libretro/RetroArch#16148]
I use RetroArch stable version 1.16 on Windows, Linux and Android. Changes were made to some cores which made saving inside the games not sync across devices.

I'll use Genesis Plus GX as an example.
I'm playing Sonic CD and its save is expected by Android to be here: RetroArch -> saves -> Sonic CD.brm
But Windows and Linux use this path instead: RetroArch -> saves -> Genesis Plus GX -> Sonic CD.brm

For now I'm resorting to make links to where Windows/Linux wants the saves, but they should all be either inside their core name folders or not.

**Comment by bslenul** [comment]
Before it was saving everything in saves folder directly, but there was a change recently that made subfolders the new default (which makes sense when games can share the same name across different platforms).

Either enable `Settings > Saving > Sort Saves into Folders by Core Name` on Android and move your saves in subfolders, or disable it on Windows and move your saves in the "saves" folder, then you'll have the same behavior on both devices.

**Comment by sonninnos** [comment]
New defaults won't change with old configs, but you simply can't be using the same version with all platforms if the current default is not the same.

**Comment by clorophilla** [comment]
@sonninnos This is with freshly installed RetroArch on both devices.

I applied @bslenul 's setting on Android and while it solves my problem it's not the default behavior across devices and OSs.

**Comment by hizzlekizzle** [comment]
I'm not seeing any ifdefs here, which is where the default setting is defined, AFAIK: https://github.com/libretro/RetroArch/blob/master/config.def.h#L854

For Android, are you using the version from the Play Store? Or did you sideload the apk from our website? If the former, it hasn't been updated in 2+ yrs due to Google "scoped storage" API requirement.

**Comment by clorophilla** [comment]
It is the Play Store version, yes. So that's the source of the conflict here. Its version is 1.9.12, which was uploaded in November 3, 2021. I'll keep this in mind and grab RetroArch from the website next time. I think it's okay to close this.
