### ISSUE TITLE
(ios)build error.RetroArch/apple/iOS/platform.m:23:10: '../../input/drivers_hid/mfi_hid.h' file not found

### ISSUE THREAD

**Issue by jiaxianhua** [libretro/RetroArch#1614]
RetroArch/apple/iOS/platform.m:23:10: '../../input/drivers_hid/mfi_hid.h' file not found

15df50939699122c9e738a69925fdc4e898eb38d

**Comment by twinaphex** [comment]
should be fixed now.

**Comment by twinaphex** [comment]
should be fixed now.

**Comment by twinaphex** [comment]
should be fixed now.
