### ISSUE TITLE
The AI service section has disappeared on the iOS system.

### ISSUE THREAD

**Issue by CottonWoolee** [libretro/RetroArch#16149]
[Description of the bug]
Even if the 'Show 'Accessibility'' and 'Show 'AI Service'' options are enabled in Settings->User Interface->Menu Item Visibility->Settings, the AI Service still does not appear in the settings.

[What you expected to happen]
In previous versions, there used to be a separate AI Service section in the top-level menu of settings ,and it functioned properly. I speculate that in a later version, AI Service was integrated under Accessibility. However, the Accessibility section was hidden in the iOS version(even if you enable it in User Interface), leading to the occurrence of this error.

[What is actually happening]
AI Service section is missing from the settings, neither appearing independently in the top-level menu nor under any other sections.

### Steps to reproduce the bug
1. [First step] Enable Show 'Accessibility'' and 'Show 'AI Service‘’ in Settings->User Interface->Menu Item Visibility->Settings
2. [Second step] Access the Settings Menu
3. [and so on...] Unable to find AI Service

### Bisect Results
This issue started appearing from some version after 1.16, but I cannot confirm the exact version. I can only say that the issue was not present in versions 1.14 and 1.15."

### Version/Commit
RetroArch Version: 1.16.0(nightly)
Git Version: 74453fb
Build Date: Jan 13 2024

### Environment information
OS: iPadOS，RetroArch is the ios-arm64 version.

**Comment by sonninnos** [comment]
Smells like https://github.com/libretro/RetroArch/issues/15718
