### ISSUE TITLE
[Feature request] Quick Menu -> Settings -- to make it possible to Save/Load Core Remap File for any settings

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16167]
## Description

Only a few `Quick Menu` options exist to save settings:
* `Core Options -> Manage Core Options -> Save Game Options / Save Content Directory Options`
* `Controls -> Manage Remap Files -> Save Remap File as / Save Game Remap File / Save Content Directory Remap File / Save Core Remap File`

So most settings in `Main Menu -> Settings` cannot be saved from the Quick Menu. For example:
* `Settings -> Video -> Scaling -> Aspect Ratio`
* `Settings -> Input -> Hotkeys`

So for example, each time a typical user with the most type of common controller (D-PAD, 4 face buttons, 4 L/R buttons, and dual sticks, and a menu button) is playing NES/SNES games they have to set the Hotkeys, and the Aspect Ratio, manually. And then they have to remove these settings when they want to use the default mappings for the controller for PlayStation games.

Personally, I'm modifying the responsible file, retroarch.cfg, file with a custom Bash script GNU/Linux. However, this is not convenient for simple users, especially not on Windows.

### Feature request

`Quick Menu -> Settings` and `Quick Menu -> Manage Configuration Options` does not exist. However, it would be useful. In this particular example, one could set this for SNES:
* Load a SNES game.
* Set `Quick Menu -> Settings -> Input -> Hotkeys: Rewind = , Fast-Forward = R2, Save State = L3, Load State = R3
* Set `Quick Menu -> Settings -> Video -> Scaling -> Aspect Ratio: Core provided` to `1:1 PAR (8:7 DAR`
* `Quick Menu -> Settings -> Manage Configuration Options -> Save Core Remap File`

### Actual behavior

It is inconvenient to change the settings every time you switch the cores.

#### Optimize DualShock controller for SNES
* Change `Settings -> Input -> Hotkeys: Rewind = , Fast-Forward = R2, Save State = L3, Load State = R3
* Change `Settings -> Video -> Scaling -> Aspect Ratio: Core provided` to `1:1 PAR (8:7 DAR` (https://github.com/libretro/bsnes-libretro/issues/35)
* Load a SNES game.

#### Reset the setting for PS1 games
* Reset all settings that you changed in the previous section.
* Load a PS1 game.

**Comment by sonninnos** [comment]
Somehow you missed overrides in Quick Menu, which is designed to do exactly that. Remaps are separate. Not really super useful to be able to access the whole settings under Quick Menu when backing out and going there normally is rather simple and fast.

**Comment by davidhedlund** [comment]
> Somehow you missed overrides in Quick Menu, which is designed to do exactly that. Remaps are separate. Not really super useful to be able to access the whole settings under Quick Menu when backing out and going there normally is rather simple and fast.

I'll take a look...

**Comment by davidhedlund** [comment]
> Somehow you missed overrides in Quick Menu, which is designed to do exactly that. Remaps are separate. Not really super useful to be able to access the whole settings under Quick Menu when backing out and going there normally is rather simple and fast.

I just tried this:
* Loaded a SNES game with bsnes-mecrury
* Change `Settings -> Video -> Scaling -> Aspect Ratio: Core provided` to `1:1 PAR (8:7 DAR)`
* `Quick Menu -> Overrides -> Save Core Overrides` -- It saved `RetroArch-Linux-x86_64.AppImage.home/.config/retroarch/config/bsnes-mercury/bsnes-mercury.cfg` but the file does not contain `aspect_ratio_index`.

**Comment by davidhedlund** [comment]
> Somehow you missed overrides in Quick Menu, which is designed to do exactly that. Remaps are separate. Not really super useful to be able to access the whole settings under Quick Menu when backing out and going there normally is rather simple and fast.

Sorry, it works now.
