### ISSUE TITLE
Conflict between the iPEGA PG-9083 and PG-9021 gamepads

### ISSUE THREAD

**Issue by Ramaddan** [libretro/RetroArch#16164]
## Description

** Sorry if this is not how this issue should be written, but I was not sure where to report it. **

I could not for the life of me get the iPEGA PG-9068 gamepad to recognize or work properly

I tried all the different modes on the gamepad and all the different input controller drivers, and modesetting or udev settings and anything else I could find.

But got it to work in the end.

Partial solution for my problem is included below

I say partial because I got retroarch to autoconfigure the keys properly, so the gamepad works now.

However, it still refused to detect any keys when trying to manually input keys, in case I want to change or correct the mapping, and the solution I used is more like a workaround because I had to essentially disable another file.

### Expected behavior

I expected retroarch to recognize the gamepad and autoconfigure.

### Actual behavior

What actually happened is that it recognized it as a 9021 instead of a 9083

The different naming is not a problem, but some keys were not working, and retroarch reused to let me input my own keys

### Steps to reproduce the bug

1. Connect bluetooth gamepad device with first normal gamepad mode
2. Run retroarch
3. First sign of problems, name that is recognized is for the PG-9021
4. The gamepad does not have all buttons working
5. Retroarch does not recognize any key when trying to manually set keys

### Bisect Results

Tried to fix the problem through process of elimination, such as problems with the linux drivers, or ubuntu settings, and so on, until I was convinced the problem lied in retroarch itself, its driver files specifically

Found the files that give the settings for the PG-9068 and PG-9021 in ~/.config/retroarch/autoconfig/udev/, namely:
- iPEGA_PG_9021_BT.cfg
- iPEGA_PG_9083S.cfg

The identification numbers of the 9083S and 9021 were identical, so I commented out the ones present in the 9021 file, since that was the ID number that was being recognized for the 9083 as well.

I was not sure what the proper settings for the 9021 should be, since I do not own one, but I just commented it out.

Interestingly, the IDs in the 9083S file provided by retroarch were commented out, which means someone saw this conflict before.

I am assuming some extra string for identification should be added in order to stop the conflict if both share the same IDs.

So the ID strings that were commented out in the 9021 file, and uncommented in the 9083S file were:

input_vendor_id = "6473"
input_product_id = "1026"

I am assuming since these settings are specific to the gamepad itself, then this problem might be cross platform, and not just linux.

Also, the problem of not being able to make any manual key mapping remains.

### Version/Commit

- RetroArch: [1.16.0/085c2aaf9a]

### Environment information

- OS: [Ubuntu Linux 22.04.3]
- Installed from launchpad retroarch repo:  Libretro Stable

**Comment by hizzlekizzle** [comment]
Yes, unfortunately, there's not a whole lot we can do about companies reusing the same vid/pids for devices.

**Comment by bslenul** [comment]
Hm, if `input_vendor_id` and `input_product_id` are identical then RetroArch should prioritize the file with the correct `input_device` field, but if there's no match maybe they were filled incorrectly before being submitted... 🤔

**Comment by Ramaddan** [comment]
Thank you for your replies.

I also have another controller that is not autoconfiguring, PG-9078, and I would like to try to get it to work.

Can you point me to the tools that are required to extract the required information?

Also, does retroarch read more than the input_vendor_id and input_product_id, such as the input_device_display_name, to be able to differentiate, as an extra parameter, so is that one just the name given by retroarch after getting the vendor and product id?

I would like to look more into this, and understand more the parameters that can be extracted, and how they can be used.

They maybe I can give back, even if just a little, and help a bit, as a small thank you for the work and effort.

**Comment by bslenul** [comment]
It checks these 3 things: 
![image](https://github.com/libretro/RetroArch/assets/33353403/8241d8e9-3b64-448b-baf0-5d87f0d83ef2)
To find the proper `input_device` name I believe you can use `dmesg` for example on Linux.

**Comment by Ramaddan** [comment]
thanks, but already tried dmesg

Does not give enough info or I don't seem to know how to use it properly

Even though the files already have different inpute_device, it seems to ignore it.

**Comment by bslenul** [comment]
> Even though the files already have different inpute_device, it seems to ignore it.

Yes, because they probably don't match the "real" name of the device. Not sure how you can get the real name properly, you could try `dmesg | grep -i "ipega"` maybe (with the controller connected)? Then paste the output here if it finds anything.

**Comment by Ramaddan** [comment]
Did not get anything with "ipega", but you can get something with "PG" with an ipega PG-9078

input: PG-9078 Keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/bluetooth/hci0/hci0:256/0005:1949:0403.0003/input/input33
input: PG-9078 Mouse as /devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/bluetooth/hci0/hci0:256/0005:1949:0403.0003/input/input34
input: PG-9078 as /devices/pci0000:00/0000:00:14.0/usb1/1-14/1-14:1.0/bluetooth/hci0/hci0:256/0005:1949:0403.0003/input/input35
hid-generic 0005:1949:0403.0003: input,hidraw1: BLUETOOTH HID v1.1b Keyboard [PG-9078] on 74:d8:3e:23:df:d8

**Comment by bslenul** [comment]
OK so from that output it looks like it would be `input_device = "PG-9078"`, then I'm assuming "1949:0403" are the VID/PID so converted to decimal that would be `input_vendor_id = "6473"` and `input_product_id = "1027"`.

**Comment by Ramaddan** [comment]
Ok. Now I am learning how to read this :-)
So you converted it back to decimal from?

I hope I am getting the rational correctly here.

It seems that retroarch tries to use the input_device first, and if it cannot find it, then it goes with the input_vendor_id and input_product_id

Thus, the conflict was happening because the iPEGA_PG_9021_BT.cfg and iPEGA_PG_9083S.cfg did not have the correct input_device name, but they both had the same input_vendor_id and input_product_id, so it chose one of them.

I am assuming alphabetically? Because it always chose the 9021

I made a copy of the 9083S config file, and removed the "S" in the file name and input_device name.

The conflict went away, so it just needed a similar file to the 9083S config file, but without the "S".

I wonder if this can be averted by asking the user a question in case such a similar conflict occurs, and let the user decide, and maybe even make a copy of one of them and add the detected input_device instead.

This does open the idea of having a more laid out option for detecting and managing controllers in the GUI, because I can't seem to do that right now.

All I have so far is the ability to make my own cfg file, and figure out the correct values.

From the GUI, it seems I am also supposed to be able to change key bindings manually, but once it finds and loads the cfg file, I can't seem to be able to do that.

Maybe it is just a problem on my side.

**Comment by bslenul** [comment]
> So you converted it back to decimal from?

From hex, I used this: https://www.rapidtables.com/convert/number/hex-to-decimal.html

> It seems that retroarch tries to use the input_device first, and if it cannot find it, then it goes with the input_vendor_id and input_product_id

It's like a points system, if VID and PID match it's +3pts, if input_device matches +2pts, the file with the most points "wins" and is used for the controller, if they have the same amount of points I believe it will use the first that was scanned, so alphabetically as you said.

> From the GUI, it seems I am also supposed to be able to change key bindings manually, but once it finds and loads the cfg file, I can't seem to be able to do that.

That's definitely not normal, autoconfig or not you should be able to rebind your buttons. What happens when you try? Button presses aren't detected or something?

**Comment by Ramaddan** [comment]
Yes, it does not detect anything. It just prompts for a keypress with the time interval, but it does not take any input, whether keyboard or pad.

**Comment by bslenul** [comment]
Hm weird 🤔 Do you have Settings > Input > Bind Hold set to anything above 0? Because if that's the case RetroArch expects you to hold the button/key for that amount of seconds.

**Comment by Ramaddan** [comment]
Bind hold is set to 2 and bind time out is set to 5, but nothing

The pad and keyboard work fine, but cannot change anything

**Comment by davidhedlund** [comment]
@Ramaddan Plesase move this issue to https://github.com/libretro/retroarch-joypad-autoconfig/issues

**Comment by bslenul** [comment]
> Bind hold is set to 2 and bind time out is set to 5, but nothing
> 
> The pad and keyboard work fine, but cannot change anything

And you hold the button/key for 2 seconds when binding it? Have you tried with "Bind Hold" set to "0"?

**Comment by Ramaddan** [comment]
> > Bind hold is set to 2 and bind time out is set to 5, but nothing
> > The pad and keyboard work fine, but cannot change anything
> 
> And you hold the button/key for 2 seconds when binding it? Have you tried with "Bind Hold" set to "0"?

Yes, it works.

That is very odd. Why would it work by setting it to zero but not otherwise?

Thanks a lot. Very Appreciated.

**Comment by Ramaddan** [comment]
> @Ramaddan Please open this issue in https://github.com/libretro/retroarch-joypad-autoconfig/issues and close this one.

Is there a way to move it, or just open a new issue and retype everything?

Thanks

**Comment by davidhedlund** [comment]
> > @Ramaddan Please open this issue in https://github.com/libretro/retroarch-joypad-autoconfig/issues and close this one.
> 
> Is there a way to move this specific part, or just open a new issue and retype everything?
> 
> Thanks

You need help from an admin to do that: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

Do you have privileges to move it @hizzlekizzle ?

**Comment by bslenul** [comment]
If the "Bind Hold" option doesn't work for OP it might be a RetroArch issue, so no need to move anything.

As to "why" it doesn't work, no idea sorry :/

**Comment by Ramaddan** [comment]
Thank you all for your help
