### ISSUE TITLE
Localization support?

### ISSUE THREAD

**Issue by Holzhaus** [libretro/RetroArch#1617]
How about localization support? I'd be happy to add some german translations.

**Comment by Alcaro** [comment]
#634 contains some prior discussion on this topic. I think most of Themaister's comment still applies.

**Comment by twinaphex** [comment]
I'm kinda wary of having gettext as a dependency - maybe we can come up with a NIH alternative instead?

**Comment by Oggom** [comment]
@Holzhaus 
It's now possible to translate the menu entries into several languages under https://github.com/libretro/RetroArch/blob/master/menu/menu_hash.c
I'll give the German translation a look later on, but feel free to check it out too if you like.

**Comment by twinaphex** [comment]
This is being worked on now. It's far from perfect (translations are welcome, Unicode text font support right now is iffy), but things will sort themselves out.

In the meantime, translators are welcome.
