### ISSUE TITLE
Both "Audio mute toggle" and "Next shader" are assigned "Key m"

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16173]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

### Expected behavior

These entries should not have the same value:
* Audio Mute: Key m
* Next shader: Key m

### Steps to reproduce the bug

Open `Settings -> Input -> Hotkey`. These are the default values
* Audio Mute: Key m
* Next shader: Key m
* Previous shader: Key n -- listed just to inform why "Next shader" is assigned "Key m"

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 appimage, 1.7.3 ubuntu package

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by sonninnos** [comment]
But audio mute default is F9.. M is not used anywhere else than next shader.

Testing and reporting about some ancient 1.7.3. version is fruitless, and it for sure does not apply to 1.16.0.

**Comment by davidhedlund** [comment]
> But audio mute default is F9.. M is not used anywhere else than next shader.
> 
> Testing and reporting about some ancient 1.7.3. version is fruitless, and it for sure does not apply to 1.16.0.

`Audio Mute` is still set to "Key m" for the 1.17.0 Appimage that was released today.

@hizzlekizzle Should I merge this issue to https://github.com/hizzlekizzle/RetroArch-AppImage ?

**Comment by davidhedlund** [comment]
> But audio mute default is F9.. M is not used anywhere else than next shader.
> 
> Testing and reporting about some ancient 1.7.3. version is fruitless, and it for sure does not apply to 1.16.0.

Let me apologize, I just discovered that my Bash script modified this value.
