### ISSUE TITLE
Unpaused video refresh does not restore core fps

### ISSUE THREAD

**Issue by oncemailtime** [libretro/RetroArch#16182]
1. Run Handy Lynx core, games run at 75 fps.
2. Pause Retroarch by losing focus or single-step throttle.
3. After unpause, core runs at native vsync (60) instead of correct 75.
4. Fast-forward throttle and un-throttle restores core 75 fps.

@sonninnos 
https://github.com/libretro/RetroArch/commit/bcb804f3f22ca3440214927f706c6c8fa44984e3#diff-3082ed9563ae0070650b649c04091334e4b144d8af21a52a81c405853ff738f2L6943-R6948

Reverting this change fixes issue. The new refresh code is nice, just this one last problem. 👍

**Comment by sonninnos** [comment]
Whoops, this should cover it.
