### ISSUE TITLE
HDR on Linux working on Steam but not on Standalone

### ISSUE THREAD

**Issue by kin-patsu** [libretro/RetroArch#16186]
## Description

On Linux, HDR won't show up as a toggle nor work when manually set from the config file of standalone Retroarch, while it instead does on the Retroarch version. Vulkan is enabled for both.

### Expected behavior

HDR shows up and works on both standalone and Steam versions

### Actual behavior

What's written in the description

### Steps to reproduce the bug

1. Open Retroarch Standalone
2. Under Video, no HDR appears
3. Open Retroarch Steam
4. Under Video, HDR does appear

### Version/Commit

- RetroArch: 1.16.0
### Environment information

- OS: Steam OS 3.5.7

**Comment by jbaiter** [comment]
If this is on a Steam Deck, are you running the standalone version from Game Mode or from Desktop Mode?
For HDR to be detected, applications need to be run in Game Mode (or more precisely, in Gamescope), and Gamescope's Vulkan layer needs to be loaded (which means copying the layer in to Flatpaks and AppImages to be loaded there).

If I may ask, when you enable HDR in the Steam Version, do you get a glitchy screen or does it work as expected? I just tried ith with a [custom HDR-enabled Flatpak build](https://github.com/jbaiter/org.libretro.RetroArch/tree/steamdeck-hdr) and I got a glitchy unresponsive screen when enabling HDR :-/

**Comment by kin-patsu** [comment]
> If this is on a Steam Deck, are you running the standalone version from Game Mode or from Desktop Mode? For HDR to be detected, applications need to be run in Game Mode (or more precisely, in Gamescope), and Gamescope's Vulkan layer needs to be loaded (which means copying the layer in to Flatpaks and AppImages to be loaded there).
> 
> If I may ask, when you enable HDR in the Steam Version, do you get a glitchy screen or does it work as expected? I just tried ith with a [custom HDR-enabled Flatpak build](https://github.com/jbaiter/org.libretro.RetroArch/tree/steamdeck-hdr) and I got a glitchy unresponsive screen when enabling HDR :-/

Tried both Game Mode and Desktop Mode, in this case I'm talking about Game Mode, as for the latter I know it's expected for it not to work, since from my understanding Desktop Mode has no HDR support at all.

About the glitchy screen, that happens to me as well, but that's expected as well since Windows does the something similar when HDR is enabled on fullscreen Vulkan, as soon as you close and reopen Retroarch it should just work

**Comment by jbaiter** [comment]
> About the glitchy screen, that happens to me as well, but that's expected as well since Windows does the something similar when HDR is enabled on fullscreen Vulkan, as soon as you close and reopen Retroarch it should just work

Thanks, that did indeed fix it!

**Comment by kin-patsu** [comment]
> Thanks, that did indeed fix it!

Glad to have helped! Since apparently that seems to be the fix, is there anything I can do myself at this point, or should I just wait for that to be pushed, whenever that may be?

**Comment by jbaiter** [comment]
> > Thanks, that did indeed fix it!
> 
> Glad to have helped! Since apparently that seems to be the fix, is there anything I can do myself at this point, or should I just wait for that to be pushed, whenever that may be?

Sorry, I meant that restarting RetroArch fixed the glitchy screen. I'll create a PR for the Flatpak, might take a while for it to hit Flathub, if it gets merged.

**Comment by kin-patsu** [comment]
Fixed build is now available in flathub so I'm closing the issue, thanks again @jbaiter !
