### ISSUE TITLE
[Linux/KDE/Wayland] RetroArch always starts with a tiny window, cannot remember last time window size

### ISSUE THREAD

**Issue by guoyunhe** [libretro/RetroArch#16198]
## Description

Whenever I launch RetroArch, the window looks tiny (compared to the Google logo in background):
![图片](https://github.com/libretro/RetroArch/assets/5836790/eb9c1875-53a6-4ac0-8f50-12849dde5db4)

It cannot remember that previous window size when I quit RetroArch.

### Expected behavior

Should launch with a reasonable window size. And remember last window size when quitting.

### Actual behavior

Launch with a tiny window size. Cannot remember window size when quitting.

### Steps to reproduce the bug

1. Install Linux with KDE Wayland desktop.
2. Install RetroArch
3. Lauch RetroArch

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.17.0

### Environment information

- OS: openSUSE Tumbleweed, KDE Wayland desktop
- Compiler: GCC 13

**Comment by ColinKinloch** [comment]
I've reproduced on Gnome by running:
```bash
systemd-run --user --pty --same-dir -p CPUQuota=1% ./retroarch
```

**Comment by guoyunhe** [comment]
@ColinKinloch I updated to KDE 6 and the problem has gone.

**Comment by Sunderland93** [comment]
@ColinKinloch in KDE Plasma 5.25 this problem is still in place, if RetroArch compiled with `--disable-libdecor`

**Comment by guoyunhe** [comment]
@Sunderland93 Try KDE Plasma 6 maybe?

**Comment by ColinKinloch** [comment]
I can reproduce it.
Only on the GL.
I'll see what I can do.
