### ISSUE TITLE
(android)Unexpected situations when sliding the screen

### ISSUE THREAD

**Issue by sssssttttttjs** [libretro/RetroArch#16200]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When sliding to a certain position on the screen in landscape mode,two notifications appears.When it happened in pause menu the game will reset or crash.
Notifications:
![Screenshot_20240205-235458_RetroArch (AArch64)](https://github.com/libretro/RetroArch/assets/107304259/48d0061d-0e51-4fc7-8722-606fbc248c20)
![Video_20240206_121448_32](https://github.com/libretro/RetroArch/assets/107304259/bf0e8f5f-a00f-4f70-b3a7-79bb9c0b0db7)

Approximate location:
![未命名](https://github.com/libretro/RetroArch/assets/107304259/dbcdf885-ab8e-407a-9563-342c44f18abc)

### Expected behavior

Nothing extra would happen when sliding.

### Actual behavior

[What is actually happening]
"Keyboard overlay is not set."
“Netplay will start when content is loaded."

### Steps to reproduce the bug

1. Launch the application
2. Slide the screen

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.16.0 (Git 14cb373)
- (stable version for android from retroarch.com)

### Environment information

- OS: Android 13
- Compiler: [In case you are running local builds]

**Comment by sonninnos** [comment]
Already fixed. Try the latest version.

**Comment by sssssttttttjs** [comment]
> Already fixed. Try the latest version.

Thanks.You're right
