### ISSUE TITLE
[ MAC OS ] Problem trying to open retroarch 

### ISSUE THREAD

**Issue by EddyStalin** [libretro/RetroArch#16205]
First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented
 Description

Problem trying to open retroarch in its latest version (1.17) doing a clean install

 Expected behavior

Retroach should open normally
 Actual behavior

Retroarch doesn't open as it normally should (retroarch closed unexpectedly)
 Steps to reproduce the bug

1. Install Retroarch version 1.17 with a clean install
2. Retroarch Shuts Down for No Reason
3. It then shows that Retroarch closed unexpectedly

Bisect Results

The error started after the 1.17 update since in the 1.16 update everything was normal
Version/Commit
iMac (21.5-inch, Mid 2011)
Prosesador 2,5 GHz Intel Core i5
Memory 8 GB 1333 MHz DDR3
Graphics AMD Radeon HD 6750M 512 MB
Mac Os High Sierra 10.13.6
- RetroArch: 1.17.0
 Environment information

- OS: Mac Os High Sierra 10.13.6
- Compiler: (Not Supported)

**Comment by sonjoelatexrougebatlike** [comment]
sorry for being new here but I'm encountering the same problem but this time the version is 1.20.0 for mac os mac mini on 7 year old machine which runs mac os 15 but i have not ditched intel for apple silicon yet and also get a metal 2 thing yet. i know apple has rebrand/rebadged method of nvidia or intel or whatevers before but nothing is new today currently. but it happend again on mac os steam version.

**Comment by luciandf** [comment]
same problem for me too! I have a mac mini running sonoma 14.7.2. it has intel graphics. I am not a mac guy but I wanted to see if I can run some retro games on it. I actually purchased this thing for another project that barely works. god I hate macs
