### ISSUE TITLE
"Android disconnect workaround"s description is not being used

### ISSUE THREAD

**Issue by unixatch** [libretro/RetroArch#16204]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

This feature (android disconnect workaround) has a description in the code
https://github.com/libretro/RetroArch/blob/fed6cc0ab220e2f984ea058b0fd57cadcc804af0/intl/msg_hash_us.h#L3434-L3441
but it's not actually being used in any default menu drivers.

Besides the fact that it took me an embarrassingly amount of time to understand what it did,
this is also bad because: 
in the description it's written why you might not want to enable this feature potentially if you're playing alongside a friend.

### Expected behavior

Seeing the description alongside the name of the option in question.

### Actual behavior

It's not there
![Screenshot_2024-02-07-13-11-43-86_a845f06d2c9842610668be6995f9e34f](https://github.com/libretro/RetroArch/assets/76928074/18cea76a-0dbd-4a03-8ce8-6a86ef4a269f)

### Steps to reproduce the bug

1. Go inside `Settings > Input`
2. See that there's no description

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.17.0/79e43e2

### Environment information

- OS: Android 12

**Comment by zoltanvb** [comment]
Thanks for the report, problem located.

**Comment by unixatch** [comment]
> Thanks for the report, problem located.

Thank you for the pull request! I'll close the issue once it gets merged.

**Comment by unixatch** [comment]
It works now but it doesn't use the translations

![Screenshot_2024-02-12-17-27-25-44_a845f06d2c9842610668be6995f9e34f](https://github.com/libretro/RetroArch/assets/76928074/348b1662-f375-4c93-ba99-8361f7c9b922)

Example from my mother language:
https://github.com/libretro/RetroArch/blob/8dd26faf51bd19585bb7f35ec3628b7ee91e318f/intl/msg_hash_it.h#L3370-L3377

And doing a quick gprep I've found out which ones may be missing:
![Screenshot_2024-02-12-17-41-53-44_84d3000e3f4017145260f7618db1d683](https://github.com/libretro/RetroArch/assets/76928074/6dd3b9c7-ebdb-45fd-9b6d-7ef214015ff6)

**Comment by zoltanvb** [comment]
Thank you for checking! Since I had to change the label identifier, it has appeared in Crowdin as a new string today. Crowdin will offer the previous translation, but a translator needs to accept it (for each language) and then the nightly job will transfer it to RA codebase. It shall appear in a few days.

**Comment by unixatch** [comment]
> Thank you for checking! Since I had to change the label identifier, it has appeared in Crowdin as a new string today. Crowdin will offer the previous translation, but a translator needs to accept it (for each language) and then the nightly job will transfer it to RA codebase. It shall appear in a few days.

No problem, I can wait for sure.
It's just that I didn't know about the whole procedure, that's it.
Thank you again for the fix.
