### ISSUE TITLE
Holding R3 not input from any other button

### ISSUE THREAD

**Issue by Augusto7743** [libretro/RetroArch#16215]
Hello.
Thanks for reading my topic.

Ubuntu 20.04.6 and PS4 DS4 Controller.
In recent version 1.17 has an issue in inputs.
If input autoconfig is enabled so the R3 is mapped to R3.
The problem is if holding R3 not any input from other buttons and dpad ir R3 is being mapped to the controller R3.
I use R3 for hotkey fast forward.
The temporary solution is edit the retroarch.cfg and use an high value for button removing the auto map.
input_player1_r3_btn = "99"

Have an nice day.

**Comment by zoltanvb** [comment]
Reproduced on Linux with other controller. When mapping fast-forward hold to R3, no input is detected while holding it. Mapping same hotkey to e.g. L1 does not do this, and the 1.15.0 version I could quickly find, did not have this problem.

**Comment by zoltanvb** [comment]
Bisected to #16163

**Comment by Augusto7743** [comment]
Thanks for sharing linkg and pointing the PR doing that issue.
Strange is the not happen that issue using the gearcoleco core.
That issue happen in more than half of all cores.
I say half because i not use all cores.

**Comment by Augusto7743** [comment]
Tested 1.17 cfd79a9 2024-02-17. Error fixed. Thanks.

Have another error in inputs happening in 1.17.
I have used Retroarch for more than an year not happening the issue below.
Using Controller Autoconfig option enabled if the user want map button only for gamepad controller only need in input bind press keyboard key delete in each input so only will read input from controller and the GUI show each button option being the controller button without errors in gameplay.
In 1.17 doing that same action the GUI show each button option only being the controller, but without input from controller. If press delete want remove keyboard key for each button is removed both keyboard key and controller key. The temporary solution is press delete for each button and after manually configure each button bind for gamepad controller so breaking autoconfig controller option.

Is as if now pressing delete internally remove all mapping for each button and the GUI show error message having mapping for gamepad controller.
Also if pressing delete for each controller button want to remove keyboard key break all hotkeys.
Another error is never was possible configure in hotkeys "menu toggle" for only keyboard key. Always is used an button in gamepad controller. If using PS4 DS4 controller that hotkey "menu toggle" will be the controller button "PS guide", but i not want that hotkey using that controller button. I want use controller button "ps guide" for other action or hotkey. The temporary solution is edit manually retroarch.cfg with an other number
input_menu_toggle_btn = "99"

Now is possible use the controller button "ps guide" for other hotkey.

I need create another topic for all errors above or continue using that topic ? Please reopen that topic if is possible continue using here and you want fix.
Have an nice day.
