### ISSUE TITLE
input_exit_emulator = "nul" when I try to change it to a number.

### ISSUE THREAD

**Issue by aidan1kitty** [libretro/RetroArch#1621]
I am trying to set the exit emulator key to 3, but whenever I run retroarch, it changes it back to "nul" and I have to use alt + f4 to quit.

**Comment by fr500** [comment]
it's working fine here. Do you have overrides or is config_save_on_exit
disabled?
What version?

**Comment by aidan1kitty** [comment]
I reinstalled the latest nightly build last night and now it works fine. So I guess its fixed.
