### ISSUE TITLE
Genesis Plux GX 1.7.5

### ISSUE THREAD

**Issue by pyrsmk** [libretro/RetroArch#16216]
The last version of Genesis Plus GX 1.7.5 has been released 4 days ago with many improvements : https://github.com/ekeeke/Genesis-Plus-GX/blob/master/HISTORY.txt

It has been 11 years since 1.7.4.

It would be great to have the core updated ! I could handle this if someone points me out some documentation to help on what to do to bring the new version to supported platforms.

**Comment by bslenul** [comment]
The core has been updated 4 days ago: https://github.com/libretro/Genesis-Plus-GX/commit/ecb956d914d6bc4e5deb49384bc929939e9a19e5 and is currently up-to-date with upstream. I guess the version bump was just an oversight ;)

**Comment by pyrsmk** [comment]
Indeed. Or maybe he's adding features but did not planned for the release yet. Libretro seems to be plugged to the live chanes on the repo.
