### ISSUE TITLE
Outstanding issue list

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#1622]
I've compile a list of issues from reports and my own experience, I'll keep this up-to-date
https://gist.github.com/fr500/41aed3436d625a981175

**Comment by Monroe88** [comment]
>[all] working shader preset is always retroarch.cgp so it's impossible to have per-core shader presets (unconfirmed)

From what I've seen, it's [configfilename].cgp. e.g if I switch to using /config/480p.cfg, the working shader preset is now 480p.cgp.
