### ISSUE TITLE
[Android] Touchscreen issues when using the Backbone One PlayStation Edition controller [Fixed 2024-06-10]

### ISSUE THREAD

**Issue by ThunderDragonRandy** [libretro/RetroArch#16227]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

While I'm using the Backbone One PlayStation Edition controller (and I don't know if it's an issue with this specific version of the controller or if the original Backbone One also has this issue). EDIT (March 3, 2024): This also occurs when I'm using the GameSir G8 Galileo or 8bitdo SN30 Pro 2, but some controllers like Razer Raiju are fine.

### Expected behavior

To be able to use the Backbone One PlayStation Edition (EDIT: and GameSir G8 Galilleo controller) controller and touchscreen controls as normal with no issues like with any other Android controller, USB or not.

### Actual behavior

While the Backbone One PlayStation Edition telescopic controller is plugged into an Android device (before or while using RetroArch AArch64), the first thing that occurs is the message "✓ Backbone Labs, Inc. Backbone One PlayStation® Edition (13706/516) not configured, using fallback". After that, tapping inputs of the touchscreen stop working after one tap (whether it be on RetroArch's menu options or on a controller overlay's virtual buttons). The first tap of the touchscreen does register but any further taps do not. However, I can still scroll up and down through the RetroArch frontend menu but as long as I have the Backbone One PlayStation Edition telescopic controller connected, tapping menu options does not work after the first tap.

### Steps to reproduce the bug

1. Insert an Android device (with USB-C connection) into the Backbone One PlayStation Edition telescopic controller. If you have the regular Backbone One, you can also test that. If the regular Backbone One works fine and no touchscreen issues occur, then it is an issue specific to the PlayStation Edition. I don't know if this issue also exists on iOS but if anyone has an iPhone 15 as the Backbone One PlayStation Edition (USB-C) is compatible with it, test that too if the issue also exists on iOS or just Android.
2. Use the touchscreen on your Android (or iOS) device. At least on Android, you might be able to tap something once but no further taps will be registered but you can still scroll through the menus with the touchscreen.

### Bisect Results

I first got the Backbone One PlayStation Edition on July 11, 2023 (during RetroArch v1.15). It seemed fine back then with no issue to what I remember. I think the issue started happening since v1.16. <I>[I am now testing this while writing this]</i> Yeah, testing previous releases right now, the touchscreen worked fine with this controller in v1.15 when I first got the Backbone One PlayStation Edition with no issues despite the controller "fallback" message appearing back then too, but as of v1.16, the touchscreen has tapping issues with this controller inserted. No other Android controller I have has this touchscreen issue when I'm using them in v1.16, v1.17, EDIT (March 22, 2024, June 9, 2024): or v1.18, v1.19, v1.19.1.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.16, v1.17, v1.18, v1.19, v1.19.1

### Environment information

- OS: Android 14 (Samsung Galaxy S22 Ultra)
- Compiler: N/A

### Screenshots
![Screenshot_20240211_130820_RetroArch (AArch64)](https://github.com/libretro/RetroArch/assets/6454220/241e3294-6e72-4c08-add9-41847f41b207)
![Screenshot_20240211_130845_RetroArch (AArch64)](https://github.com/libretro/RetroArch/assets/6454220/e5ca7f61-14aa-4b3c-a0f4-66a82f67ad83)
![Screenshot_20240211_131016_RetroArch (AArch64)](https://github.com/libretro/RetroArch/assets/6454220/8048d6a6-bbf7-4d7c-b42c-35eddeb2fdc4)
![20008825](https://github.com/libretro/RetroArch/assets/6454220/6d4588aa-6af6-4e03-a843-76d31cd2a48d)

## Fixing the issue (discovered June 9, 2024):

https://github.com/libretro/RetroArch/issues/15757#ref-commit-c23b5e7 Hunterk made a [build](https://github.com/hunterk/RetroArch/actions/runs/9437129093/artifacts/1583131332) of the latest RetroArch build [reverting](https://github.com/hunterk/RetroArch/commit/abcd42777f7c17559cf6eb509dc86aca63e48527) https://github.com/libretro/RetroArch/commit/abcd42777f7c17559cf6eb509dc86aca63e48527 and touchscreen + controller issue is fixed. EDIT (1 day later): This fix has been implemented in the June 10, 2024 (2024-06-10) main nightly build. Now that can use the touchscreen again on my phone while using my computers, I'll close my topic.

**Comment by DJM75** [comment]
This is a regression introduced recently (older RetroArch versions didn't have this problem) and it happens with every phisical controller connected to an Android device (even on all those chinese Android handhelds). Now it's not possibile to use gamepad overlays with a phisical controller connected, after the first "touch" the overlay becomes unresponsive.

**Comment by ThunderDragonRandy** [comment]
> This is a regression introduced recently (older RetroArch versions didn't have this problem) and it happens with every phisical controller connected to an Android device (even on those chinese Android handhelds). Now it's not possibile to use gamepad overlays with a phisical controller connected, after the first "touch" the whole overlay becomes unresponsive.

Yeah, I recently got the GameSir G8 Galileo and that issue happens with that too. So far, among the Android controllers I have tested (I also tested 8Bitdo SN30 Pro 2 that is also having touchscreen issues), the Razer Raiju controller so far is the only one that doesn't have this issue.

I may as well downgrade back to v1.15 for now.

**Comment by arnaullv** [comment]
This commit breaks the touchpad input, see https://github.com/libretro/RetroArch/issues/15757

https://github.com/libretro/RetroArch/commit/abcd42777f7c17559cf6eb509dc86aca63e48527 refactor: rewrite input handling to better support AINPUT_SOURCE_STYLUS (https://github.com/libretro/RetroArch/pull/15597)
