### ISSUE TITLE
[3DO] Several bugs in 3DO core Opera

### ISSUE THREAD

**Issue by rrrcabral** [libretro/RetroArch#16231]
I tried to run 2 games on the retroarch core, and both gave errors,
The first "FIFA International Soccer" appears in the menu but when you click to start the match it apparently resets the game, returns to the opening credits as if you had just opened the game.
I also tried playing "Lost Files of Sherlock Holmes" and it has graphical bugs with random colored pixels where an initial video/animation should be playing.
I tried running Sherlock in both .chd and .bin/cue and the bugs persist so it can't be the rom's fault. the core is updated. I reset the core options too, and tried with 2 different bios, and everything is still buggy.
I tried running Sherlock on the standalone 4DO emulator (the base of Opera) and everything WORKED PERFECTLY! The animation appears beautifully without bugs.
what should be the problem?

In Retroarch Opera Core:
![Lost Files of Sherlock Holmes, The (USA)-240213-104355](https://github.com/libretro/RetroArch/assets/89989258/4623b1e8-fd5c-4428-9162-94c0c301a3c5)

In standalone 4DO:
![stanalone](https://github.com/libretro/RetroArch/assets/89989258/c3ff7314-3476-4aa5-a91e-3f8d08f11f12)

retroarch version: 1.16.0
running in Windows 11, cpu: amd ryzen 1600AF, gpu: Nvidia GTX 960 2GB,

**Comment by trapexit** [comment]
Opera has a git repo. Please submit new issues there.

**Comment by rrrcabral** [comment]
ill do that
