### ISSUE TITLE
Save State Thumbnails are not cleaned up when Maximum Auto-Increment Save States to Keep is set 

### ISSUE THREAD

**Issue by Real-Gecko** [libretro/RetroArch#16238]
## Description

Whenever you enable `Save State Thumbnails`, `Increment Save State Index Automatically` and set `Maximum Auto-Increment Save States to Keep` to value other than zero, thumbnails of deleted saves are not deleted with them.

### Expected behavior

Save state thumbnail must be deleted with save state.

### Actual behavior

Thumbnails remain in `states/<system name>`

### Steps to reproduce the bug

1. Enable `Save State Thumbnails`
2. Enable `Increment Save State Index Automatically`
3. Set `Maximum Auto-Increment Save States to Keep` to something greater than zero, like 2
4. Launch the game and save a few times
5. Navigate to save states directory, see that only last 2 saves exist, but the number of thumbnails is much bigger 

### Bisect Results

I guess it always was like this

### Version/Commit

- RetroArch: 1.17.0

### Environment information

- OS: Arch Linux

**Comment by vonmillhausen** [comment]
I just spotted this tonight - was checking out the save state folder, I have auto increment turned on and maximum 10 states, but found hundreds of screenshots sitting in there for saves that no longer exist!
