### ISSUE TITLE
Microphone support on iOS

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [libretro/RetroArch#16241]
DS games use microphone support, and I would like to play DS games on my phone that require the microphone like kids games and warioware.

**Comment by trotsky40** [comment]
Even with the latest nighlty on iOS, I am unable to get either a prompt or manually turn on microphone permissions in iOS.

**Comment by warmenhoven** [comment]
You're loading a game that uses the microphone in a core that supports it (are there any other than melonDS DS?), and set the core options for the microphone input mode to be the microphone?

**Comment by trotsky40** [comment]
Yes. Using Pokemon- White Version, which has a mic test in the main menu. Tried with all the microphone options: hold, toggle, and always.

**Comment by warmenhoven** [comment]
Hm, it's not working for me either. I'll take a look.
