### ISSUE TITLE
[feature request] Controller configuration test core

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16258]
https://www.retroarch.com/index.php?page=controller-autoconfig says that you should try the controller in a game to make sure that all button mappings are working. It would be helpful if we offered a core in "Main Menu -> Online Updater -> Core System Files Downloader" that can be used to verify that the whole controller configuration works as expected.

**Comment by sonninnos** [comment]
The "Remote RetroPad" core is already doing that, mostly.

**Comment by davidhedlund** [comment]
> The "Remote RetroPad" core is already doing that, mostly.

But it's a remote tool, so it requires two devices. An on-screen display of the RetroPad (shown at https://youtu.be/bzom8OZ-HAk?t=126) use for a single instance of RetroArch should fulfill the feature request.

**Comment by sonninnos** [comment]
But it works alone for testing the RetroPad.

**Comment by davidhedlund** [comment]
> But it works alone for testing the RetroPad.

Sorry, can you please tell me how to set it up without the need of an extra device?

**Comment by sonninnos** [comment]
Uhh just load it..

**Comment by davidhedlund** [comment]
This is what I did:
* Settings -> Network -> Enable: Network RetroPad
* Settings -> Network -> Enable: User 1 Network RetroPad
* Main Menu -> Load Content -> a SNES game with bsnes-mercury

The RetroPad is not displayed on the screen when the game starts.

**Comment by sonninnos** [comment]
That is not how it is supposed to work. Just select the core in the bottom of the "Load Core" list.

**Comment by davidhedlund** [comment]
> That is not how it is supposed to work. Just select the core in the bottom of the "Load Core" list.

Thank you very much! I'll document this in https://www.retroarch.com/index.php?page=controller-autoconfig
