### ISSUE TITLE
Remote RetroPad: 11 of 24 buttons does not work

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16263]
## Description

Tested with PlayStation DualSense in Ubuntu 20.00 based distro.

* 24 of 24 buttons works in the games.
* but only 11 of 24 buttons worked with the Remote RetroPad.

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

* Start RetroArch. 
* [Sony Interactive Entertainment DualSense Wireless Controller.cfg](https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Sony%20Interactive%20Entertainment%20DualSense%20Edge%20Wireless%20Controller.cfg) is loaded
* Open `Main Menu` -> `Load Core` -> `Start Remote RetroPad`

These controllers don't work with the "udev" controller driver:
* L2
* R2

#### Solved

The thumb sticks didn't work at all, but they have now been added:
* L3 up (now solved in 1.18.0)
* L3 down (now solved in 1.18.0)
* L3 left (now solved in 1.18.0)
* L3 right (now solved in 1.18.0)
* R3 up (now solved in 1.18.0)
* R3 down (now solved in 1.18.0)
* R3 left (now solved in 1.18.0)
* R3 right (now solved in 1.18.0)
* Menu button (now solved in 1.18.0)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.17.0 Appimage

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by zoltanvb** [comment]
In current RetroArch, remote retropad should be able to display also analog sticks, can you check if this brings an improvement?
I have not changed actual packet transfer (i.e. the remote part), but analog axes were sent also earlier, just not displayed.

**Comment by davidhedlund** [comment]
> In current RetroArch, remote retropad should be able to display also analog sticks, can you check if this brings an improvement? I have not changed actual packet transfer (i.e. the remote part), but analog axes were sent also earlier, just not displayed.

Thank you very much for fixing most of this. The thumb sticks are working 100%, but these buttons don't work for controller driver "udev":
* L2
* R2

It should work because I can map them in Hotkeys. Also, both L2, and R2 are working with controller driver "sdl2".

**Comment by zoltanvb** [comment]
How is L2/R2 mapped in (auto)config? (Note that remote retropad behaves as a core, so it may have remap file.)

**Comment by davidhedlund** [comment]
> I can't make sense of this, may be driver+device dependent quirk, I can register R2/L2 with udev and another controller. R2/L2 is frequently set up as an axis, but it should still work, I tried checking if for some reason only the analog button part is being sent in that case, but nope.

I wish I could help, but I don't know C, and I don't really know Git.

> If you try to bind R2/L2 with udev, does it still end up with buttons 6 and 7?
Yes. Actually I submitted the [PR specifically for this](https://github.com/libretro/retroarch-joypad-autoconfig/pull/1068/commits/b45c10be7db50bc7a27841a1978773bb2cd14eb0) that is responsible for the "6" and "7" values.

> And does L2/R2 work in games with the DS controller + udev?
Yes.

**Comment by davidhedlund** [comment]
> I can't make sense of this, may be driver+device dependent quirk, I can register R2/L2 with udev and another controller. R2/L2 is frequently set up as an axis, but it should still work, I tried checking if for some reason only the analog button part is being sent in that case, but nope.

I wish I could help, but I don't know C, and I don't really know Git.
 
> If you try to bind R2/L2 with udev, does it still end up with buttons 6 and 7?
Yes. Actually I submitted the [PR specifically for this](https://github.com/libretro/retroarch-joypad-autoconfig/pull/1068/commits/b45c10be7db50bc7a27841a1978773bb2cd14eb0) that is responsible for the "6" and "7" values.
 
> And does L2/R2 work in games with the DS controller + udev?
Yes.

**Comment by davidhedlund** [comment]
Do you have a controller with L1 and R1?

Are the working in Remote RetroPad for you?

**Comment by zoltanvb** [comment]
Yes and yes.
I have a PR waiting that would show also the analog values for the triggers, once it gets merged it may be interesting to see if there is anything detected differently.

**Comment by zoltanvb** [comment]
The analog trigger display has been merged since a while, can you try what it shows for L2/R2 with your controller?

**Comment by davidhedlund** [comment]
> > In current RetroArch, remote retropad should be able to display also analog sticks, can you check if this brings an improvement? I have not changed actual packet transfer (i.e. the remote part), but analog axes were sent also earlier, just not displayed.
> 
> Thank you very much for fixing most of this. The thumb sticks are working 100% in 1.18.0, but these buttons don't work for controller driver "udev":
> 
>     * L2
> 
>     * R2
> 
> 
> They are working fine with controller driver "sdl2".

The L2/R2 issue for the DualSense controller was that the controller file was incorrectly generated by Retroarch, so it had to be fixed manually:
https://github.com/libretro/retroarch-joypad-autoconfig/pull/1135

**Comment by davidhedlund** [comment]
> The analog trigger display has been merged since a while, can you try what it shows for L2/R2 with your controller?

It's working now, with the new controller file for DualSense. Can you please make sure that you didn't add unnecessary code? I'm sorry but it was really just an issue with the controller file.

This issue should be fixed to prevent RetroArch from generating wrong autoconfig files:
* https://github.com/libretro/RetroArch/issues/6920

**Comment by zoltanvb** [comment]
No code was harmed while investigating this issue :) analog trigger test was added to remote retropad for generic use.

**Comment by davidhedlund** [comment]
> Yes and yes. I have a PR waiting that would show also the analog values for the triggers, once it gets merged it may be interesting to see if there is anything detected differently.

So should we not revert this PR?

**Comment by zoltanvb** [comment]
I was referring to #16390, it is merged and should remain in the code. I can't close the issue, but eventually someone with the necessary rights will swing by.

**Comment by davidhedlund** [comment]
> I was referring to #16390, it is merged and should remain in the code. I can't close the issue, but eventually someone with the necessary rights will swing by.

Thank you very much for your help! People can now evaluate their controller configurations with RetroPad, which is great for evaluating new autoconfig files before they are uploaded.

**Comment by davidhedlund** [comment]
@zoltanvb I just tried a controller in android and the L2/R2 buttons didn't work -- the .

# Android issue
I'm experimenting with a Data Frog P02 controller.

## Analog triggers does not work
Remote RetroPad works (response for both L2 and R2) with:

```
input_driver = "android"
input_device = "Wireless Controller"
input_vendor_id = "1356"
input_product_id = "1476"
input_b_btn = "96"
input_y_btn = "99"
input_select_btn = "109"
input_start_btn = "108"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "97"
input_x_btn = "100"
input_l_btn = "102"
input_r_btn = "103"
input_l2_btn = "104"
input_r2_btn = "105"
input_l3_btn = "106"
input_r3_btn = "107"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
input_menu_toggle_btn = "110"
input_b_btn_label = "Cross"
input_y_btn_label = "Square"
input_select_btn_label = "Create"
input_start_btn_label = "Options"
input_a_btn_label = "Circle"
input_x_btn_label = "Triangle"
input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_btn_label = "L2"
input_r2_btn_label = "R2"
input_l3_btn_label = "L3"
input_r3_btn_label = "R3"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_l_x_plus_axis_label = "Left Analog X+ (Right)"
input_l_x_minus_axis_label = "Left Analog X- (Left)"
input_l_y_plus_axis_label = "Left Analog Y+ (Down)"
input_l_y_minus_axis_label = "Left Analog Y- (Up)"
input_r_x_plus_axis_label = "Right Analog X+ (Right)"
input_r_x_minus_axis_label = "Right Analog X- (Left)"
input_r_y_plus_axis_label = "Right Analog Y+ (Up)"
input_r_y_minus_axis_label = "Right Analog Y- (Up)"
input_menu_toggle_btn_label = "PS"
```

## Analog triggers does not work
Analog triggers works with udev, but not android.
Remote RetroPad doesn't work (no response at all for both L2 and R2) with:

Modify the digital triggers to analog (https://github.com/libretro/RetroArch/issues/6920):
```
input_l2_btn = "104"
input_r2_btn = "105"
```

To
```
input_l2_btn = "+6"
input_r2_btn = "+7"
```

File:
```
input_driver = "android"
input_device = "Wireless Controller"
input_vendor_id = "1356"
input_product_id = "1476"
input_b_btn = "96"
input_y_btn = "99"
input_select_btn = "109"
input_start_btn = "108"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "97"
input_x_btn = "100"
input_l_btn = "102"
input_r_btn = "103"
input_l2_btn = "+6"
input_r2_btn = "+7"
input_l3_btn = "106"
input_r3_btn = "107"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
input_menu_toggle_btn = "110"
input_b_btn_label = "Cross"
input_y_btn_label = "Square"
input_select_btn_label = "Create"
input_start_btn_label = "Options"
input_a_btn_label = "Circle"
input_x_btn_label = "Triangle"
input_l_btn_label = "L1"
input_r_btn_label = "R1"
input_l2_btn_label = "L2"
input_r2_btn_label = "R2"
input_l3_btn_label = "L3"
input_r3_btn_label = "R3"
input_up_btn_label = "D-Pad Up"
input_down_btn_label = "D-Pad Down"
input_left_btn_label = "D-Pad Left"
input_right_btn_label = "D-Pad Right"
input_l_x_plus_axis_label = "Left Analog X+ (Right)"
input_l_x_minus_axis_label = "Left Analog X- (Left)"
input_l_y_plus_axis_label = "Left Analog Y+ (Down)"
input_l_y_minus_axis_label = "Left Analog Y- (Up)"
input_r_x_plus_axis_label = "Right Analog X+ (Right)"
input_r_x_minus_axis_label = "Right Analog X- (Left)"
input_r_y_plus_axis_label = "Right Analog Y+ (Up)"
input_r_y_minus_axis_label = "Right Analog Y- (Up)"
input_menu_toggle_btn_label = "PS"
```

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16791

**Comment by davidhedlund** [comment]
Remote RetroPad: Analog trigger indicator disappears on release for L2/R2 buttons
* https://github.com/libretro/RetroArch/issues/16793

**Comment by davidhedlund** [comment]
Sony DualSense (the PS5 controller) does still not work with Remote RetroPad, I just tried it with RetroArch 1.20.0:
* https://github.com/libretro/RetroArch/issues/16791
