### ISSUE TITLE
SwitchRes issues on 1.17 in Linux Mint 

### ISSUE THREAD

**Issue by petran79** [libretro/RetroArch#16262]
I use Linux Mint laptop and have a CRT monitor connected via an hdmi to vga converter. I also modified xorg.conf to bypass monitor EDID values and added custom resolutions.

Problem is the same in both the regular, ppa, flatpak and appimage version of version 1.17. 
Whenever  I activate SwitchRes, CRT monitor becomes black.
On 1.16 there is no such issue. SwitchRes is recognised automatically even after resetting settings. If I activate SwitchRes, menu is left as it is. 
But 1.17 refuses to run with SwitchRes and monitor becomes black just by clicking the option. I have both set to NATIVE resolution

On 1.16 the verbose command shows this output

/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=retroarch org.libretro.RetroArch

[INFO] [Config]: Looking for config in: "/home/petros/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg".
[INFO] RetroArch 1.16.0 (Git 6c2cc45)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.16.0
[INFO] Git: 6c2cc45
[INFO] Built: Jan 22 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Core]: Geometry: 320x240, Aspect: 1.333, FPS: 0.00, Sample rate: 48000.00 Hz.
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_x".
[INFO] [Vulkan]: Detecting screen resolution: 600x240.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [X/Vulkan]: Using Xinerama on screen #0.
[INFO] [X/Vulkan]: X = 0, Y = 0, W = 600, H = 240.
[INFO] [X/Vulkan]: Using windowed fullscreen.
[INFO] [Vulkan]: Found GPU at index 0: "NVIDIA GeForce GTX 1060".
[INFO] [Vulkan]: Found GPU at index 1: "llvmpipe (LLVM 17.0.6, 256 bits)".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "NVIDIA GeForce GTX 1060".
[INFO] [Vulkan]: Queue family 0 supports 16 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 600x240.
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Joypad]: Found joypad driver: "sdl2".
[INFO] [Video]: Found display server: "x11".
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [ALSA] Using ALSA version 1.2.9
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: Loading history file: "/home/petros/.var/app/org.libretro.RetroArch/config/retroarch/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/petros/.var/app/org.libretro.RetroArch/config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/petros/.var/app/org.libretro.RetroArch/config/retroarch/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/petros/.var/app/org.libretro.RetroArch/config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/home/petros/.var/app/org.libretro.RetroArch/config/retroarch/content_favorites.lpl".
[INFO] [X/Vulkan]: Resized fullscreen resolution to 600x240.
[INFO] [CRT]: Requested Resolution: 320x240@60.000000 orientation: normal
[INFO] [CRT] Video context is: vk_x
[INFO] [CRT]: CRT Mode: 3 - pc_31_120 
[INFO] [CRT]: Monitor Index Auto: auto
[ERROR] XRANDR: <1> (xrandr_timing) [ERROR] missing X11_LIBRARY library
[ERROR] sr_init_disp: error, couldn't init the display
[INFO] [CRT]: SR rtn -1 
[ERROR] [CRT]: error at init, CRT modeswitching disabled
[INFO] [CRT]: Aspect ratio forced by user: 2.500000
[INFO] [X/Vulkan]: Resized fullscreen resolution to 600x240.
[INFO] [Config]: Saved new config to "/home/petros/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [PulseAudio]: Pausing.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

however 1.17 gives me this message. Both have exactly the same config. CRT monitor shows the menu for a second and then turns black and the Linux OS wall paper appears on laptop monitor. I have to press Esc for Retroarch to close and CRT OS picture to appear. But it switches resolution back too. 

retroarch --verbose
[INFO] [Config]: Looking for config in: "/home/petros/.config/retroarch/retroarch.cfg".
[INFO] RetroArch 1.17.0 (Git r202402032131~ad8975cb5a)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
[INFO] Capabilities: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE42 AES AVX AVX2 
[INFO] Version: 1.17.0
[INFO] Git: r202402032131~ad8975cb5a
[INFO] Built: Feb  3 2024
[INFO] =================================================
[INFO] [Input]: Found input driver: "x".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Core]: Geometry: 320x240, Aspect: 1.333, FPS: 0.00, Sample rate: 48000.00 Hz.
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: fullscreen.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: "vk_x".
[INFO] [Vulkan]: Detecting screen resolution: 2944x1080.
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 2.
[INFO] [X/Vulkan]: Using Xinerama on screen #0.
[INFO] [X/Vulkan]: X = 0, Y = 0, W = 1024, H = 768.
[INFO] [X/Vulkan]: Using windowed fullscreen.
[INFO] [Vulkan]: Found GPU at index 0: "NVIDIA GeForce GTX 1060".
[INFO] [Vulkan]: Found GPU at index 1: "llvmpipe (LLVM 17.0.6, 256 bits)".
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using fences for WSI acquire.
[INFO] [Vulkan]: Using GPU: "NVIDIA GeForce GTX 1060".
[INFO] [Vulkan]: Queue family 0 supports 16 sub-queues.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [Vulkan]: Using resolution 1024x768.
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Vulkan]: Loading stock shader.
[INFO] [Joypad]: Found joypad driver: "sdl2".
[INFO] [Video]: Found display server: "x11".
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Audio]: Started synchronous audio driver.
[INFO] [ALSA] Using ALSA version 1.2.6.1
[INFO] [Microphone]: Initialized microphone driver.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Playlist]: Loading history file: "/home/petros/.config/retroarch/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/petros/.config/retroarch/content_music_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/petros/.config/retroarch/content_video_history.lpl".
[INFO] [Playlist]: Loading history file: "/home/petros/.config/retroarch/content_image_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/home/petros/.config/retroarch/content_favorites.lpl".
[INFO] [X/Vulkan]: Resized fullscreen resolution to 1024x768.
[INFO] [CRT]: Requested Resolution: 320x240@60.000000 orientation: normal
[INFO] [CRT] Video context is: vk_x
[INFO] [CRT]: CRT Mode: 3 - pc_31_120 
[INFO] [CRT]: Monitor Index Auto: auto
[INFO] [CRT]: SR rtn 0 
[INFO] Switchres: Calculating best video mode for 320x240@60.000000 orientation: normal
[INFO] Switchres: Modeline "320x240_120 31.440000KHz 120.000000Hz" 12.764640 320 329 363 406 240 243 246 262   -hsync -vsync
[INFO] sr_set_mode: successfully switched to 320x240@120.000000
[INFO] [CRT]: Aspect ratio forced by user: 1.333333
[INFO] [Video]: Video refresh rate changed to 120.000 Hz.
[INFO] [Vulkan]: QueuePresent failed, destroying swapchain.
[INFO] [Vulkan]: Got 3 swapchain images.
[INFO] [X/Vulkan]: Resized fullscreen resolution to 320x240.
[INFO] [Config]: Saved new config to "/home/petros/.config/retroarch/retroarch.cfg".
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [PulseAudio]: Pausing.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 2.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

Does this mean that Switchres does not work on 1.16 either? Because I use it for the 120hz option and the vsync interval set at 2 for smoother scrolling at 60hz games and it seems to work. Or is it enough just to set vsync interval at 2? 
1.17 refuses to resize the desktop to 600x240 like 1.16 so that I can activate refresh rates above 120 hz and surpass the 31khz vertical frequency limit

**Comment by substring** [comment]
Do you still have the issue in 1.19.1 ?

**Comment by petran79** [comment]
no it switches automatically now
