### ISSUE TITLE
Upside-down image sent to AI translation service when using HW renderer

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#16275]
## Description

When using the AI translation hotkey with a HW rendered core, the screenshot is sent upside-down to the translation server, making the translation impossible.

For example this is my RetroArch window:

![image](https://github.com/libretro/RetroArch/assets/33353403/42e164f1-8c65-4153-8a1c-697ab795b6b7)

and this is what the translation server received:

![image](https://github.com/libretro/RetroArch/assets/33353403/91dac11f-bf88-4922-a6aa-c488ce32f19f)

AFAICT it doesn't happen with software rendered cores.

### Expected behavior

Send screenshot in the correct position.

### Actual behavior

Send screenshot upside-down.

### Steps to reproduce the bug

1. Set AI translation stuff (AI service and a AI hotkey).
2. Start a game with a HW rendered core (I was able to reproduce with Beetle PSX HW, SwanStation and Flycast).
3. Press the AI hotkey, translation should be gibberish.
4. Check your last screenshot sent on the AI translation website you used.

### Bisect Results

Bisected to 274d47f957c917b2139d7248cd0589c25725f656

### Version/Commit

- RetroArch: 1.17.0 / 0f36082

### Environment information

- OS: Windows 10 but @Sanaki confirmed it happening on Linux as well

**Comment by zoltanvb** [comment]
Tagging the original PR #15640 in hope of more attention - maybe this will ring a bell to someone.

**Comment by hizzlekizzle** [comment]
Did the translation service work with HW-rendered cores before this was merged? I was thinking it didn't, though I don't know if this is the reason why.

**Comment by bslenul** [comment]
Yes it used to work fine, the same Ikaruga screenshot with stable RA 1.16.0 for example:

![image](https://github.com/libretro/RetroArch/assets/33353403/3d0a1fbb-2793-4c3c-bd50-0901482956b7)

It doesn't work with D3D11 tho, but that's because the driver doesn't support screenshots.

**Comment by PCdasala** [comment]
orque fechada se não resolveu?

**Comment by bslenul** [comment]
> orque fechada se não resolveu?

What?

@Cpod12 @xunkar any idea about the issue?

**Comment by xunkar** [comment]
I do actually. I will not be able to look to much into it right away but off the top of my head I remember that the frame was returned upside down by the rendered, so we had to manually invert it before sending it to the AI service. It would seem that this particular renderer configuration causes the frame to be capture in the correct position from the start, if we can detect the renderer being used we can simply ignore this step.

**Comment by viachaslavic** [comment]
@xunkar here also another case is described for GNU/Linux, when retroarch crashes when using the hw-rendered core. 
I tried to debug a little and found that the crash occurs after `read_viewport()`  call at  https://github.com/libretro/RetroArch/blob/ac694145f03c7c87edf4942075f3a8d593d4ffdf/tasks/task_translation.c#L1250  This call executes successfully in the main loop, but may not have access to the viewport resource after being moved to the task context.
```log
X Error of failed request:  BadAccess (attempt to access private resource denied)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  26 (X_GLXMakeContextCurrent)
  Serial number of failed request:  3684
  Current serial number in output stream:  3684
 double free or corruption (!prev)
 Aborted (core dumped)
```

### Env

* Arch Linux
* X11 (amdgpu)
* RetroArch: 1.17.0 / https://github.com/libretro/RetroArch/commit/ac694145f03c7c87edf4942075f3a8d593d4ffdf
* SwanStation : GPU Renderer - Hardware (OpenGL)

**Comment by whoiamwhy** [comment]
the same problem with Citra and any 3ds game
![image](https://github.com/libretro/RetroArch/assets/131746105/7ba69fc3-1019-4224-afa4-d0f9327dc720)

**Comment by LibretroAdmin** [comment]
@xunkar We have to ship a stable release soon. Since you seem to be unable to fix it at this time, can I revert the PR for now so we can at least ship a stable 1.18.0 out? You can then send a followup PR that has this particular bug fixed.

**Comment by LibretroAdmin** [comment]
Looks like it can't even be reverted anymore, too much stuff has changed.

So it looks like 1.18.0 will have this regression in it.

**Comment by Cpod12** [comment]
Hey, I'm sorry about this and replying so late on this thread. I can try to take a look at this too since I did some work on that PR

**Comment by LibretroAdmin** [comment]
That'd be awesome yes if this issue can be fixed.

**Comment by xunkar** [comment]
Wait, something's toubling me here. OP showed that Ikaruga was flipped vertically, but with Citra it's flipped horizontally? I'm confused.

I've found the part of the code I mentioned earlier. It's legacy code from Beaker that I left as is. He said as a comment: "Returned output from the png processor is an upside down RGBA image, so we have to change that to RGB first. This should probably be replaced with a scaler call." https://github.com/libretro/RetroArch/blob/06fa5325f8b3cd42e6fba3d57835d5924c9ea2e7/tasks/task_translation.c#L768

As it stands, a simple conditional statement on this block to filter out the problematic renderers should be enough. But the question about the difference in cores is most important, it might require much more in-depth testing.

**Comment by LibretroAdmin** [comment]
@xunkar Could it be that some cores use 32-bit color and others 16bit color? For 32bit it's XRGB8888 and for 16bit RGB565

**Comment by bslenul** [comment]
> Wait, something's toubling me here. OP showed that Ikaruga was flipped vertically, but with Citra it's flipped horizontally? I'm confused.

Yeah idk, just tried Citra and for me it's upside-down just like the other affected cores:

![images](https://github.com/libretro/RetroArch/assets/33353403/b7f97cdc-39ce-40ae-baa3-94b76de3f551)

**Comment by BarryJRowe** [comment]
Firstly, is it verified that screenshots themselves are not flipped upside down in these cases? If that’s the case then we should not fix it at the ai service level.

@xunkar The op stated that the image the server gets is upside down. The code for decoding pngs is used in the callback after getting the response back from the server since pngs are naturally bottom to top encoded and have to be flipped for rendering.

**Comment by hizzlekizzle** [comment]
Sending BMPs of hardware-accelerated cores could end up with some very large files, right?

**Comment by xunkar** [comment]
The frames are grabbed as native core resolution, so for the most part it makes little difference. Before the refactoring only BMP was supported and there wasn't much complain, I still added PNG support to be safe.

**Comment by LibretroAdmin** [comment]
This is still not fixed isn't it?

I don't see the point of postponing 1.18.0 for much longer if there is no real incentive or drive to get this fixed anytime soon. Either someone comes forward with a workable solution within the next two days or we just press on with 1.18.0 release instead and leave this issue to be fixed for the next release.
