### ISSUE TITLE
EditorConfig support or not?

### ISSUE THREAD

**Issue by kokoko3k** [libretro/RetroArch#16278]
https://github.com/libretro/RetroArch/commit/85dbd1d2b2414b0ebf581c79e3150964210d097f

My editor keep stripping trailing white spaces because it correctly supports this configuration.
However not all "committers" editors support this and the code has trailing white spaces here and there, so often my commits ends up stripping trailing white spaces making the commit itself difficult to read.

How should this be handled?

Strip trailing white spaces once for all from all cpp/cxx/h files?
Delete EditorConfig file from retroarch tree?
Remove trim_trailing_whitespace = true from it?
Ideas?

**Comment by zoltanvb** [comment]
Quick check, about 20% of .c files and 10% of .h files (outside of deps/) seems to have trailing whitespace. But some are not really touched.
My 2c: keep the setting, and maybe do one separate update for the files you are modifying / planning to modify.

**Comment by RobLoach** [comment]
While it can be annoying, feel free to submit pull requests with the whitespace changes included. We're not that strict on changesets. GitHub also provides a "ignore whitespace" option when reviewing PRs.

While it does add noise to the diff, cleaning up the whitespace is always appreciated.
