### ISSUE TITLE
Can't install cores on Android 14

### ISSUE THREAD

**Issue by RuralAnemone** [libretro/RetroArch#16300]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I cannot install cores.

### Expected behavior

Cores download and install.

### Actual behavior

I get a notification saying, "Failed to install core: [core]"

### Steps to reproduce the bug

1. Download RetroArch from Aurora Store (should be no different than play store install?)
2. Go to core download list
3. Select a core to download
4. ):

### Bisect Results

I have never been able to download any core

### Version/Commit

Latest Play Store version as of 2024-02-26
the store page says it was last update Nov 10, 2021, so `v1.9.13`?

### Environment information

Android 14

### verbose logs

[retroarch.log](https://github.com/libretro/RetroArch/files/14421146/retroarch.log)
[retroarch__2024_02_27__07_39_47.log](https://github.com/libretro/RetroArch/files/14421147/retroarch__2024_02_27__07_39_47.log)

**Comment by RuralAnemone** [comment]
oh wow that logged a lot less than I thought it would

**Comment by sonninnos** [comment]
Forget the store version and install the proper current version from the website.

**Comment by RuralAnemone** [comment]
OH I see
thank you (:
I'll see if that works (I don't see why it wouldn't)

**Comment by RuralAnemone** [comment]
solved, thank you
apologies for the stupidity (:
lol
