### ISSUE TITLE
[Feature Request] Add Citra support for Raspberry Pi 4/5

### ISSUE THREAD

**Issue by Lolothepro** [libretro/RetroArch#16318]
You need :
Update Citra to add Vulkan support
This PR: https://github.com/citra-emu/citra/pull/7384

**Comment by gouchi** [comment]
Please don't "crosspost", one [issue](https://github.com/libretro/citra/issues/128) is enough.

You should close this issue.

Thank you.

**Comment by Lolothepro** [comment]
It seems preferable to make a feature request on the general repository, rather than on the Citra fork repository.

**Comment by gouchi** [comment]
If it is related to the core, it should be opened to dedicated repository not RA.
