### ISSUE TITLE
AI graphics 'super resolution'

### ISSUE THREAD

**Issue by romulasry** [libretro/RetroArch#16328]
Windows want to enable this:  Windows 11: Enable NEW AI Super Resolution feature for game upscaling https://www.youtube.com/watch?v=ygqlJWD1xXo

**Comment by hizzlekizzle** [comment]
What's the question, exactly?

**Comment by hizzlekizzle** [comment]
If this is happening at the OS level, is there something we need to do to support it? it sounds like it just happens and is transparent to the software, right?

**Comment by romulasry** [comment]
It sounds like Microsoft needs to support it.

**Comment by RobLoach** [comment]
Sounds like this is something on the OS-side. In the meantime, using a shader is likely a good way to head towards something you're looking for.
