### ISSUE TITLE
linuxraw: "Save Controller Profile" says "Error saving controller profile."

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16320]
It's not possible to generate linux raw autoconfig files, so they cannot be uploaded to https://github.com/libretro/retroarch-joypad-autoconfig/tree/master/linuxraw

# Steps to reproduce the bug

* Change "Settings -> Drivers -> Controller" to "[linuxraw](https://docs.libretro.com/guides/input-controller-drivers/#linuxraw-controller-driver)".

"Settings -> Inpute -> RetroPad Binds -> Port 1 Controls":
* Change a button with the controller (required for "Save Controller Profile" to work).
* Click on "Save Controller Profile".
* "Error saving controller profile."

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Flatpak 1.17.0. Appimage 1.17.0

### Environment information

- OS: Trisquel GNU/Linux version 11

**Comment by zoltanvb** [comment]
Reproduced. Is "Device index" filled correctly in your case, or does it stay as N/A?

**Comment by davidhedlund** [comment]
> Reproduced. Is "Device index" filled correctly in your case, or does it stay as N/A?

Interesting finding! It N/A for me:

![image](https://github.com/libretro/RetroArch/assets/6416073/d752a2e0-2b55-4ff9-9ac2-351c7ab8517b)

**Comment by davidhedlund** [comment]
Thank you, I'm looking forward to upload linuxraw autoconfig files!

To complement the fix of this issue, to make it convenient for people to upload autoconfig files to https://github.com/libretro/retroarch-joypad-autoconfig/tree/master/linuxraw

Add " (Restart required)" to the sub-label of "Settings -> Drivers -> Controller"

**Comment by davidhedlund** [comment]
> Thank you, I'm looking forward to upload linuxraw autoconfig files!

* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1141

**Comment by davidhedlund** [comment]
# Flatpak 1.19.1 (does not work)
Can you please re-open this issue? @LibretroAdmin  I get the same error message ("Error saving controller profile.") with Flatpak.

Also, this is how RetroArch looks when I
* Open RetroArch
* Settings -> Drivers -> Controller: linuxraw
* Settings -> Restart RetroArch

![image](https://github.com/libretro/RetroArch/assets/6416073/5ac7875e-5da2-42ed-a30f-ed72da8b24f6)

# Appimage 1.19.1 (works)
It works fine with the Appimage (thank you for the contribution!) so I uploaded a controller file here:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1141

**Comment by davidhedlund** [comment]
@zoltanvb I invite you to Subscribe to this long-term project to make it convenient for end users to upload new autoconfig files, and most importantly to make them correct!:
* https://github.com/libretro/retroarch-joypad-autoconfig/issues/1143

Your expertise could significantly improve the RetroArch experience for users across various platforms.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16828
