### ISSUE TITLE
Fullscreen mode issue for XMB

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16321]
## Description

My fullscreen screenshots were taken with 1920x1080 on a 32" monitor.

"Settings -> Video -> Fullscreen Mode -> Enable: Start in Fullscreen Mode" increases the font-size. 

All menu entries are visible in the default Ozone theme:

Default windows size:
![image](https://github.com/libretro/RetroArch/assets/6416073/a969f7e6-21a6-4a29-8a5f-3803569a16d1)

Fullscreen:

![Screenshot at 2024-03-03 15-40-08](https://github.com/libretro/RetroArch/assets/6416073/93d05f5d-8651-4706-99ad-385d9dd3c5cd)

### Expected behavior

I expect that all menu entries that are visible by default in XMB, are also visible when fullscreen mode is enabled. Like seen in this workaround:

* Settings -> User Interface -> Apperance -> Scale Factor: 70
*Go to "Settings" and observe that all menu entries that were visible in the default window size, are now visible in fullscreen mode:

![image](https://github.com/libretro/RetroArch/assets/6416073/a1d39b08-feb1-41a4-8c67-37f7ffb0c65c)

Perhaps we need a setting that is detecting the screen resolution and screen size and set appropriate Scale Mode for it.

### Steps to reproduce the bug

* "Settings -> User Interface -> Menu: XMB" (requires restart)
* "Main Menu -> Restart"
* Go to "Settings" and observe how many menu entries that are visible:

![image](https://github.com/libretro/RetroArch/assets/6416073/56342329-1809-4d75-83c5-09084cd643f9)

* Settings -> Video -> Fullscreen Mode -> Enable: Start in Fullscreen Mode
* Go back to the Main Menu

![image](https://github.com/libretro/RetroArch/assets/6416073/d35d6fc0-5a15-44c4-9987-3e8278458bbf)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.17.0 Appimage

### Environment information

- OS: Trisquel GNU/Linux version 11

**Comment by RobLoach** [comment]
Since your window-view, and fullscreen-view, are different aspect ratios, you're able to see a different number of menu items. I'm unclear on what the problem you're demonstrating here is.
