### ISSUE TITLE
[Core Request] Ryujinx

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16339]
* https://github.com/Ryujinx/Ryujinx/issues/973

**Comment by hizzlekizzle** [comment]
Looks like they're not into it, so probably not gonna happen.

**Comment by davidhedlund** [comment]
> Looks like they're not into it, so probably not gonna happen.

The only avalible Switch emulator currently is Ryujinx, since Yuzu has been taken down:

![image](https://github.com/libretro/RetroArch/assets/6416073/3ad56c93-d327-4f71-95c8-4718464f9933)

**Comment by RobLoach** [comment]
Ryujinx is still very young, so while having a port could be possible, time may be better spent making it super solid. That doesn't mean someone couldn't port it themselves though.

If you have ideas about new cores, feel free to ask about them in the forum, or work with someone on Discord to start work on a new one.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/13331
