### ISSUE TITLE
Display [core].so in "Main Menu -> Information -> Core Information"

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16337]
### Expected behavior

The .so file name should be displayed, because it is not always identical to the core name. For example, the LRPS2 core is stored in pcsx2_libretro.so.

### Actual behavior

The .so file name is not displayed

### Steps to reproduce the bug

* Load a game
* Open `Main Menu -> Information -> Core Information`

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.17.0

**Comment by RobLoach** [comment]
I don't believe showing the filename here is that useful for 99.999% of end users.

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16684
