### ISSUE TITLE
ubuntu: 24.04 daily unmet dependencies installing from ppa:libretro/stable

### ISSUE THREAD

**Issue by cscd98** [libretro/RetroArch#16341]
## Description

I am testing Ubuntu 24.04 (8/3/24) which is due out next month.

Following installation as per instructions:
sudo add-apt-repository ppa:libretro/stable && sudo apt-get update && sudo apt-get install retroarch

You end up with a number of errors.

```
Errors were encountered while processing:
 mali-g610-firmware
 libgl1-mesa-dri:arm64
 libglx-mesa0:arm64
 libglx0:arm64
 libgl1:arm64
 retroarch
 qtwayland5:arm64
 libqt5gui5:arm64
 libqt5svg5:arm64
 libqt5widgets5:arm64
 qt5-gtk-platformtheme:arm64
 libqt5waylandclient5:arm64
 libqt5waylandcompositor5:arm64
 libqt5quick5:arm64
```

### Expected behavior

Install retroarch

### Actual behavior

https://pastebin.com/p2fQfb7n
(comment is too long)

### Steps to reproduce the bug

1. Setup Ubuntu 24.04 daily on a arm64 device (Orange PI 5b)
2. Follow instructions above to add ppa and install retroarch

### Version/Commit

- RetroArch: retroarch arm64 1.17.0

### Environment information

- OS: Ubuntu 24.04 noble daily arm64

**Comment by cmitu** [comment]
AFAIL there is no Ubuntu official image with:

>  24.04 daily on a arm64 device (Orange PI 5b)

I think you're actually using a distro based on Ubuntu, but not an official Ubuntu image (perhaps https://github.com/Joshua-Riek/ubuntu-rockchip). One of the packages that triggers the errors is 'mali-g610-firmware', which is not an Ubuntu package, but something added by the distro maintainer - you're most likely to get a solution if you ask the distro's packager and show the errors you posted.
