### ISSUE TITLE
The L trigger and R trigger on iOS build can only be recognized as buttons and cannot be identified as analog triggers.

### ISSUE THREAD

**Issue by CottonWoolee** [libretro/RetroArch#16377]
[Description of the bug]

Regardless of using an Xbox Wireless controller or DualSense on iOS build of RetroArch, the L trigger and R trigger can only be recognized as buttons and cannot function as analog triggers.

### Expected behavior

In Dreamcast games like “F355 Challenge - Passione Rossa (USA)”, the L and R triggers can perform analog function, allowing of inputting continuous values in the “analog calibration” section of the option.

The following is an example of testing I conducted in the native Flycast app on iOS.
![RPReplay_Final1711004156](https://github.com/libretro/RetroArch/assets/43591230/5dc6bc10-7304-406c-8f74-c9eefb05e168)

### Actual behavior

In the RetroArch iOS build, L and R triggers can only be treated as buttons. Even if remapped them within RetroArch settings, they will only be recognized as button inputs.

The following is an example of testing I conducted in RetroArch with Flycast core, we can see the input values only jump between 0 and 100.
![RPReplay_Final1711004512 2](https://github.com/libretro/RetroArch/assets/43591230/a5f816e8-fc0f-45db-b70d-79e752760af4)

### Steps to reproduce the bug

1. Connect a game controller compatible with analog triggers for use on iOS, such as the Xbox Wireless Controller or DualSense. Note that the Switch Pro Controller does not meet this criterion as it only has digital shoulder buttons.
2. Let autoconfig automatically recognize the controller, then load a core whose native controller with analog triggers, such as flycast(dreamcast)"
3. Load a games support analog triggers, such as “F355 Challenge - Passione Rossa (USA)”, then proceed to 'Options -> Analog Calibration' to test if the input values are reasonable.

### Bisect Results

I have installed versions 1.13、1.15 and conducted the same tests, RetroArch exhibited the same behavior in both versions. Perhaps this is a logic established from the inception of the iOS build. (When using an Xbox Wireless Controller on the Fire HD 10 tablet, the analog triggers function properly.)

### Version/Commit

RetroArch Version: 1.17.0
Git Version: 5452999b
Build Date: Mar 19 2024

### Environment information

- OS: iPadOS 16.5

Lastly, it must be emphasized that I am very grateful to the developers who have put effort into the iOS version, and I fully understand that the current mechanism doesn't pose an issue for emulation the consoles before the fourth generation, as we all know that consoles like the Mega Drive and SNES don't have analog trigger😆

It's just that starting from the fifth generation, peripheral like Sega Saturn's 3D Control Pad began utilizing analog triggers and were applied in dedicated games, and over the past year, cores such as Flycast (Dreamcast) and Play! (PS2), gradually added to iOS, have started to support analog triggers on native controllers. Therefore, we have reason to believe that the necessity of analog trigger functionality in implementing a faithful reproduction of the gaming experience is increasing.

To be honest, I am unaware of the method and technical difficulty involved in implementing analog triggers. I have only conducted tests to the best of my ability, confirming that both the DolphiniOS and Flycast apps support inputting continuous values using analog triggers on iOS. Hopefully, if some talented developers consider prioritizing this matter in future development schedules, this information can provide some assistance.🙂

**Comment by warmenhoven** [comment]
Can you please clarify if you are talking about the shoulder or trigger buttons? https://developer.apple.com/documentation/gamecontroller/gcextendedgamepad

**Comment by CottonWoolee** [comment]
Hello, Warmenhoven, first of all, I want to thank you for looking into this issue.

I'm referring to that the triggers on the physical controller are only recognized as buttons when inputted, even though I've manually attempted to change the 'input_l2_btn =' text in MFi_Controller.cfg to 'input_l2_axis =', when remapping, the iOS version of RetroArch still only recognizes the triggers on the physical controller as buttons. However, if I map the right analog stick of the physical controller to 'input_l2_axis', it is recognized as axis input correctly.

It's worth mentioning that through my testing, in the native apps of Flycast or DolphiniOS, these physical triggers can indeed provide continuous values of analog input, but only when using default configurations. If we attempt to remap the controller, something interesting happens: the triggers on the physical controller are once again only recognized as buttons, just like on RetroArch.

Since my understanding of how programs handle these controller is extremely limited, I refrain from making inferences. Nonetheless, I hope these observations provide some assistance. Additionally, it must be noted that my iPadOS is stuck on 16.5 due to jailbreaking. If this is an issue that has already been fixed in later versions of iOS/iPadOS, that's great, and we can move on from it.😅

**Comment by warmenhoven** [comment]
Looks like it's just a core integration issue, not specific to iOS. It works fine in other cores.

**Comment by CottonWoolee** [comment]
Due to my desire to help this project progress more efficiently, please allow me to provide some additional explanation. As shown in the figure 1, on the iOS version of RetroArch, after opening the app and without loading any core, navigate to Settings -> Input -> RetroPad Binds -> Port1 Controls. Then, proceed to map the physical controller, we can observe that the L and R triggers can only be recognized as Button 12 and Button 13. On the other hand, on the Fire HD 10 tablet (which runs the Android-based Fire OS, sold by Amazon), the L and R Triggers of the Xbox Wireless Controller can be correctly identified as 'Axis +6' and 'Axis +7' respectively, as shown in the figure 2.

figure 1
![IMG_2723](https://github.com/libretro/RetroArch/assets/43591230/c00c60d4-4ddf-4518-8d37-9ca7567e6c92)
figure 2
![IMG_2724](https://github.com/libretro/RetroArch/assets/43591230/44cc4ae1-88e3-4f03-b693-7d1c4693378f)

To be honest, as I don't play mobile games much, I used to think this situation was due to inherent limitations of iOS, It wasn't until I played games on GeForce Now and found that it supports continuous values of analog input, then I began to further investigate whether analog triggers have full functionality in various emulators.😊

**Comment by warmenhoven** [comment]
Ah, I see what you are saying now, thank you.
