### ISSUE TITLE
atari paddle support gone now?

### ISSUE THREAD

**Issue by ZombieNoSleep** [libretro/RetroArch#16383]
There used to be a paddle device type in retroarch stella core, but it appears to be no longer listed, using latest version

**Comment by sonninnos** [comment]
It is up to the core, so no point posting this here.

**Comment by ZombieNoSleep** [comment]
It is only not working in retro arch and im under /libretro/retroarch so thought it was the right place, can you please direct me to where to post this please

**Comment by hizzlekizzle** [comment]
Upstream has requested that _we_ add more input devices if anyone requests them, as they don't know enough about libretro to do it themselves. I fixed whatever problem they had at the time but I wasn't able to get the paddles hooked up myself.

**Comment by ZombieNoSleep** [comment]
Ya i asked over there where i was directed to in above post and they said "Sorry, we cannot help here. You have to ask the people who are responsible for Retro Arch and/or Libretro."

The thing is, Retro Arch used to have paddles listed in device type and they worked fine, but now there is no option, not sure why it was removed? See pic plz thanks
![nopaddles](https://github.com/libretro/RetroArch/assets/162681799/e1b63f90-38f5-4029-9f62-82658201780f)

**Comment by hizzlekizzle** [comment]
I believe the 2014 version has/had paddles. Is that no longer the case? FAKEDIT: yeah, seems it's still there. It is one of the glaring omissions from the new version, so if anyone wants to duplicate the functionality there, that would be tops.

**Comment by ZombieNoSleep** [comment]
They just said over on stella: "We did not change anything here, so I have no idea how to help you. Also, we do not have the resources to support Retro Arch problems. Sorry."

**Comment by hizzlekizzle** [comment]
Yes, that's to be expected. You don't need to bug them about it.

The 2014 version is based on a 10-yr old snapshot of their codebase, so what we did there would need to be reimplemented with the new codebase. Or, you could use the old 2014 core for games that require the paddles until we can do it.
