### ISSUE TITLE
Can't click right stick and use the dpad at the same time

### ISSUE THREAD

**Issue by fartboygh** [libretro/RetroArch#16382]
On any core. 1.17.0

Tested on other programs on my computer and there are no issues. Checked if there were input conflicts in retroarch and there are none.

Clicking the left stick while using the dpad is fine.

**Comment by fartboygh** [comment]
I went back to 1.16.0 and everything works fine.

**Comment by zoltanvb** [comment]
Works here, so let's dig deeper. Can you test by starting remote retropad from Start Core, and trying R3+dpad? Also, what is the controller driver?

**Comment by fartboygh** [comment]
Dinput and it actually works in remote retropad.

**Comment by fartboygh** [comment]
It's fixed in the nightly.

**Comment by zoltanvb** [comment]
Thank you for checking!
