### ISSUE TITLE
RA crash and cannot connect to libretro source

### ISSUE THREAD

**Issue by vuproone** [libretro/RetroArch#1639]
few months ago I downloaded RetroArch with cydia but it does not support plus ip6 screen so I tried looking for a different version better but not found :( . trouble is I can not begin to reload RA 1002 on cydia because no server connection libretro ( why ? ) people can give me link download the latest version and set screen optimized ip6 plus
thank you

**Comment by micechal** [comment]
You can try there for latest builds: http://buildbot.libretro.com/nightly/ios/
