### ISSUE TITLE
Nightly ios-arm64 ipa from buildbot crashes when loading content since 2024-03-19 build

### ISSUE THREAD

**Issue by trotsky40** [libretro/RetroArch#16397]
## Description

Recent iOS ipas from buildbot crash when loading content (either directly or from playlist).  

### Bisect Results

The last build that works is the 2024-03-18 nightly build from buildbot. That build was based on commit 57530ac5

### Environment information

- OS: iOS 17.4.1 on an M2 iPad Pro. 
- Compiler: N/A from Buildbot

**Comment by trotsky40** [comment]
Here is a log from the first build that crashes
[retroarch__2024_03_31__10_28_16.log](https://github.com/libretro/RetroArch/files/14817088/retroarch__2024_03_31__10_28_16.log)

**Comment by warmenhoven** [comment]
Probably just need to update the controller profiles.

**Comment by warmenhoven** [comment]
Sorry, should have checked the date/commit closer. I just assumed it was my change.

I think I see which commit might have caused it but don't see where it's crashing or how to reproduce it yet.

**Comment by trotsky40** [comment]
I did a full reset of my config file. On default settings, it works. Stepping through my custom configurations, the option to store saves in folders by content directory is what is causing it to crash (see below). Leaving on the default (folders by core name) works. I use the “saves in folder by content directory” setting on all of my installs (iOS, windows, and Linux) and it is only crashes on iOS. 

![IMG_1716](https://github.com/libretro/RetroArch/assets/25250513/79549573-ace2-4cea-857e-c8fb79709c4d)
