### ISSUE TITLE
network commands `READ_CORE_RAM` and `WRITE_CORE_RAM` are broken

### ISSUE THREAD

**Issue by beauxq** [libretro/RetroArch#16392]
### Bisect Results

The network commands `READ_CORE_RAM` and `WRITE_CORE_RAM` are broken since this was merged:
https://github.com/libretro/RetroArch/pull/15912
(cheevos) use rc_client for state management (#15912)
bbe7afcd824a9c127b12a1f501bc3590f0b76b03

It's working in the previous commit:
936ff84204a4bccd7827be523524b581e506bf7c

### Steps to reproduce the bug

To test, I'm using a Sega Master System game in cores "Genesis Plus GX" or "SMS Plus GX"
With "Network Commands" enabled, I'm sending "`READ_CORE_RAM 0140 10`" to the UDP port 55355

### Expected behavior

Before this change, I get the response:
`READ_CORE_RAM 140 01 60 00 60 00 00 00 01 00 00`

### Actual behavior

After this change, I get the response:
`READ_CORE_RAM 140 -1`

### Environment information

I'm building on Linux.
I'm receiving problem reports from lots of users on Windows over the past few weeks too.

**Comment by Jamiras** [comment]
`READ_CORE_RAM` and `WRITE_CORE_RAM` are tied to the RetroAchievements memory mapping scheme, and do seem to be working as expected if a game with achievements is loaded. For non-achievement related functionality, you should be using `READ_CORE_MEMORY` and `WRITE_CORE_MEMORY`.
https://github.com/libretro/RetroArch/blob/a7d5026c8926ffe7407b58dfaae41618fb9d90ca/command.h#L437-L444

**Comment by beauxq** [comment]
`READ_CORE_MEMORY` and `WRITE_CORE_MEMORY` don't work with Sega Master System.
So I've been using the only thing I've found that does work.

Do you know how I can get `READ_CORE_MEMORY` and `WRITE_CORE_MEMORY` to work with Sega Master System?

**Comment by Jamiras** [comment]
Because the default RetroAchievements addressing scheme is just SYSTEM_RAM followed by SAVE_RAM, `READ_CORE_RAM` works with both the `retro_get_memory_data` functions and the `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` call.

`READ_CORE_MEMORY` requires the `RETRO_ENVIRONMENT_SET_MEMORY_MAPS` callback so it can map the addresses correctly. I'm guessing whichever core you're using doesn't implement `RETRO_ENVIRONMENT_SET_MEMORY_MAPS`.
