### ISSUE TITLE
please help me !Key conflict of xbox controllers

### ISSUE THREAD

**Issue by xuedongyoci** [libretro/RetroArch#16402]
hello，thank you verymuch  for creating such good app。 
now I have some problems：
when I use retroarch on iPhone,the newest version 1.18。and my controller is xbox controller。 using the mfi driver.
when I input L1+START,together press down.then the input will become l1+select. the key "start" changes to "select"
and there is another issue,when I input L2+START ,together press down.then the input will become l2+L3. 
I have tried close the autoconfig.but noting help.
This situation is  very strange，both in the menu or in game。
when I test this,i keep retropad on the screen,so I can see which keys are pressed down。 
so now  I can’t use the combo hotkey “l1+r1+start+select”,it’s not working. 
but，when I use retroarch on my android tv，the same controller，There won’t be the same problem occurring，everything is ok。 plese help me，thank you ，sorry for my poor English。

**Comment by warmenhoven** [comment]
Confirmed. It seems to only affect the start button, and only when one of L1/L2/R2 are pressed.

Thanks for posting this in both the forum and here. I don't always check the forum regularly.
