### ISSUE TITLE
Manual thumbnail downloads require two attempts

### ISSUE THREAD

**Issue by InterClaw** [libretro/RetroArch#16425]
## Description

When manually downloading thumbnails, with the title filename matching the thumbnail filenames, there are two activations of the download required before the download starts. This is regardless of the setting "Use Filenames for Thumbnail Matching".

Also, see discussion here: https://discord.com/channels/184109094070779904/469974542299955210/1226974683673530480

### Expected behavior

Suggestion is that the manual downloader is "smarter" and attempts to find an exact match based on the filename on the first attempt, or at least do so when "Use Filenames for Thumbnail Matching" is enabled.

### Actual behavior

Two manual download attempts are required to download based on the title filename.

### Steps to reproduce the bug

1. Ensure the title's filename is exactly matching available thumbnails.
2. In RetroArch, go into the title and select "Download Thumbnails". The onscreen notification shows, but doesn't download anything.
3. Select "Download Thumbnails" again. The .zip file with the thumbnails downloads.

### Bisect Results

It seems this started with version 1.17.0. See this PR:
https://github.com/libretro/RetroArch/pull/16174

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.17.0 ad8975c

### Environment information

- OS: Windows 11 Enterprise
- Compiler: n/a

**Comment by eltharynd** [comment]
First attempt givers an error file not found, second one downloads it.

Details:
- automatic downloads will not work (most likely because it has a cooldown and doesn't try to download it again soon enough
- you have to press "download thumbnails" right after the first time for it to work, if you go about the menu and stuff it won't work.

my guess is before attempting a download it tries to delete the existing thumbnail but if it doesn't exist it just throws an exception

**Comment by zoltanvb** [comment]
Checked the situation, and I have a partial solution already, but ran into a problem. Not sure how to handle compressed ROMs - the file name for those will be something like "zipname.zip#romname.bin". I tend to prefer the rom name instead of the zip name, but it needs a bit of extra processing.

**Comment by zoltanvb** [comment]
Scratch that, compressed file names are handled correctly already now.
