### ISSUE TITLE
Feature request: Xbox line and PS3 cores

### ISSUE THREAD

**Issue by WindowsNinetyTen** [libretro/RetroArch#16432]
I think that it would be nice to have cores for the Xbox consoles, based on the following:

Xbox original - CEMU
Xbox original - XEMU
Xbox 360 - Xenia
PlayStation 3 - RPSC3

**Comment by RobLoach** [comment]
These are still new emulators. Ports to libretro take a lot of work and dedication. If you'd like to help out, get familiar with their code-base, and support the emulators themselves. While we appreciate your excitement, we prefer not to have lingering core request issues open. Thanks!
