### ISSUE TITLE
Updated version?

### ISSUE THREAD

**Issue by bremaya** [libretro/RetroArch#16440]
[Description of the bug]

It's actually not a bug, but rather a question, which version is the most up-to-date? The one from Google PlayStore or F-Droid?

Why when installing the F-Droid version asks to update on the PlayStore, but the version is 1.9.12 (2021-11-03)

**Comment by sonninnos** [comment]
Obviously a version from 2 years ago isn't up-to-date.

**Comment by bremaya** [comment]
> Obviously a version from x years ago isn't up-to-date.

Ok, but why don't you correct the PlayStore version to be an earlier version?

**Comment by hizzlekizzle** [comment]
As of Android v11, Google has mandated that all apps in the Play Store need to implement support for their "scoped storage" API, and anyone who doesn't (or in our case, can't) do so can no longer update their apps.

We have an open PR to hopefully correct this after all this time, but it's not quite ready to merge and we aren't even 100% sure that's going to let us through (though we obviously hope it does) https://github.com/libretro/RetroArch/pull/16393

**Comment by RobLoach** [comment]
What hizzlekizzle said. In the meantime, use the APK from https://retroarch.com/?page=platforms . Thanks all!
