### ISSUE TITLE
[Feature Request] Frame doubling/tripling with "Sync to Exact Content Framerate"

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#16469]
## Description

It would be nice to have an option to natively double/triple the framerate of games through frame duplication. 

Some VRR monitors either have really crappy LFC implementations, or they just behave weirdly at certain refresh rate ranges (anecdotally speaking, one of my older IPS displays tends to have worse image retention issues with VRR at lower refresh rates). Having the option to duplicate frames (ex: `60.01Hz` -> `120.02Hz`) would be nice just to avoid some of these headaches without trading away the frame pacing benefits that combining "Sync to Exact Content Framerate" and VRR provides. The only tradeoff I can think of is that frame duping would probably lead to a slight increase in input latency and system requirements, but that's about it.

**Comment by hizzlekizzle** [comment]
Does setting vsync swap interval to 2 not do this? Or setting the subframe feature to 2?
