### ISSUE TITLE
ios app broken ?

### ISSUE THREAD

**Issue by hunter1026** [libretro/RetroArch#16471]
1.17 and 1.18 crashes for me as soon as you click on the app, it wont even open. i have to stay at 1.16

im on the latest ios version and i sideload it. 1.16 works but anything higher doesnt

**Comment by warmenhoven** [comment]
I really don't have enough information to debug this. What iOS version are you on? Do you delete the app before upgrading? Have you tried deleting the retroarch.cfg file? If deleting the config file fixes the problem, if you keep a copy of it, it can be used to debug the problem.

**Comment by RobLoach** [comment]
Use the issue template.
