### ISSUE TITLE
IOS version crashes on startup

### ISSUE THREAD

**Issue by hunter1026** [libretro/RetroArch#16485]
the app shows the retroarch icon for a second and then crashes to home screen. 

retroarch version 1.18.0 nightly
ios version 17.4.1
iphone 12 pro

i deleted retroarch.cfg to try to fix it but it doesnt. 

also my previous issue was closed because i didnt use the issue template but i dont see how to do that here

**Comment by hunter1026** [comment]
and latest version 1.17 does this too. the latest version i can get working is 1.16

**Comment by warmenhoven** [comment]
What did you use to sideload it?

**Comment by hunter1026** [comment]
i always use appdb

**Comment by warmenhoven** [comment]
When you say the latest stable 1.17, can you please tell me exactly which url you used for the IPA? The Download link on the website points at the nightly 1.18 build.

Could you try using sideloadly and see if that works better?

**Comment by hunter1026** [comment]
![image](https://github.com/libretro/RetroArch/assets/122758962/1540cdb8-e373-42ba-9bb1-da23d6a8112c)

![image](https://github.com/libretro/RetroArch/assets/122758962/e6eea7e4-1641-4d18-851b-9f940d65bb11)

**Comment by hunter1026** [comment]
do you think it could be appdb causing the problem? i can try another signing service but id have to pay for it because i dont have a pc

**Comment by warmenhoven** [comment]
With 1.18 possibly but not 1.17, there shouldn't be too much difference between 1.16 and 1.17 when it comes to side loaders.

Do you have plenty of disk space on your phone?

**Comment by hunter1026** [comment]
yes i have like 75 gb free

**Comment by hunter1026** [comment]
![image](https://github.com/libretro/RetroArch/assets/122758962/4ce8d562-bc9d-40a6-8785-b31cc7470cd0)
![image](https://github.com/libretro/RetroArch/assets/122758962/127c06f0-4e97-46cc-8d03-7f6edf725263)
@warmenhoven

**Comment by hunter1026** [comment]
https://github.com/libretro/RetroArch/assets/122758962/846e9b33-a4f7-4c7d-8c30-a30c63060f88

**Comment by warmenhoven** [comment]
Thanks for posting the log, that's very helpful. I still think it's most likely that there's something left around on disk that is causing it to crash; if it's not the config file, my next guess is that it's a playlist file. Can you try removing all of the .lpl files in the config directory, as well as the playlists directory, and see if it works after that? If that does work, could you narrow down to which playlist file is causing the problem and send it to me (either attach it here or email it to me, eric@warmenhoven.org)?

**Comment by hunter1026** [comment]
any more ideas? i really want this to work as i have always installed the latest versions and now i cant.

**Comment by warmenhoven** [comment]
Only two other ideas, you let me know which you prefer. The first is to delete and reinstall the app entirely. The second, I'd like to create a build for you to try out that has additional crash logging.

**Comment by hunter1026** [comment]
ok nice! second one bc ive deleted and installed multiple times and multiple versions

**Comment by hunter1026** [comment]
@warmenhoven just send me the ipa ill sideload it, try it out and send you the log

**Comment by warmenhoven** [comment]
Thanks very much. GitHub isn't letting me attach the IPA, but you can download it from here: https://www.warmenhoven.org/retroarch/builds/hunter1026/RetroArch.ipa

It comes from this branch: https://github.com/warmenhoven/RetroArch/tree/warmenhoven/dev/kscrash, which is current master plus one commit to add the KSCrash crash reporting library. I've also opted to exclude all cores from the build as it makes it considerably smaller and I don't think they are relevant here.

When you run it, I expect it will still crash. Please run it a few times. After, there should be a new directory in the RetroArch application folder called KSCrash; please send me that entire directory.

**Comment by FhenrisGit** [comment]
Same issue here, app worked for a day or two and now it crashes on startup exactly like in the video, installed it from the app store, no update available

**Comment by warmenhoven** [comment]
@FhenrisGit that sounds like a different issue then. Can you try deleting the retroarch.cfg file and see if it fixes it?

**Comment by FhenrisGit** [comment]
> @FhenrisGit that sounds like a different issue then. Can you try deleting the retroarch.cfg file and see if it fixes it?

Thx ! This fixed it, don't know what caused my retroarch.cfg to make it crash tho. I was trying to configure WebDAV but counldn't paste URL or PASSWORD so I stopped mid config.

**Comment by warmenhoven** [comment]
Sounds like there's a bug in the url parser then. If you happen to recall what the url was I can try to fix it so it doesn't crash like that anymore.

**Comment by FhenrisGit** [comment]
I don't think it's an issue with the URL. Actually, I stopped configuring WebDAV because you can't paste text in the RetroArch iOS app, which makes setting up a URL and password complicated since everything has to be entered manually. But that's a different bug, so I'll probably open a ticket for that issue
