### ISSUE TITLE
`Save Current Configuration` doesn't save retroarch.cfg to `Settings -> Directory -> Configuration files`

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16490]
### Expected behavior

`Main Menu -> Configuration File -> Save Current Configuration` should save retroarch.cfg to `Settings -> Directory -> Configuration files`

### Actual behavior

`Settings -> Directory -> Configuration files`
* Applies to `Main Menu -> Configuration File -> Save New Configuration`, and `Main Menu -> Configuration File -> Load Configuration`
* But not to `Main Menu -> Configuration File -> Save Current Configuration`

### Steps to reproduce the bug

Pre-configuration for Android: You need to change this to see the notification widget text on typical smartphones due to their narrow screen width: `Setting -> Video -> Output -> Screen Orientation: 90 deg` + `Main Menu -> Quit` to save the configuration + Restart RetroArch for the setting to take effect.

For any all OSes including Android:
* Change `Settings -> Directory -> Configuration files`
* `Main Menu -> Configuration File -> Save Current Configuration`

### Version/Commit
You can find this information under Information/System Information

- RetroArch: apk 1.17.0, Appimage 1.18.0, Flatpak 1.18.0

### Environment information

- OS: Android, GNU/Linux (Flatpak, Appimage)

**Comment by davidhedlund** [comment]
* https://github.com/libretro/RetroArch/issues/16491

**Comment by davidhedlund** [comment]
Cannot reproduce. `Main Menu -> Configuration File -> Save Current Configuration` is saving retroarch.cfg to `Settings -> Directory -> Configuration files`

**Comment by iBurley** [comment]
It appears I'm having the same issue on 1.22.2 installed on NixOS via nixpkgs 26.05. As you can see from my screenshots I've set my config directory to `/mnt/Games/RetroArch/config/` and even loaded a configuration file from inside that directory manually, but when I change any settings and hit save current configuration, it still tries to save to `~/.config/retroarch/`. As the original post mentions, if I hit save new configuration it does go to the defined location. 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/03aa490f-615a-4da2-b6a1-76709137fcda" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/42cec63e-2faa-4e9b-8470-ff533821e403" />

**Comment by davidhedlund** [comment]
@iBurley

I have submitted these issues to avoid confusion:
* https://github.com/libretro/RetroArch/issues/19211
* https://github.com/libretro/RetroArch/issues/19200
