### ISSUE TITLE
Request to get a Acorn Atom \ Acorn Archimedes Core added to RetroArch

### ISSUE THREAD

**Issue by ChristopherEccleston2024** [libretro/RetroArch#16505]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Hi, Is It Possible to request the addition of a Acorn Atom Emulator and An Acorn Archimedes Emulator core emulator such as Pantheon and Arculator and ArcEm

**Comment by hizzlekizzle** [comment]
Please don't open duplicate issues: https://github.com/libretro/RetroArch/issues/16505
