### ISSUE TITLE
feature request working microphone for ios and melonds ds is missing from appstore version?

### ISSUE THREAD

**Issue by hunter1026** [libretro/RetroArch#16517]
i cant use my devices microphone for the melonds ds core even though the option is turned on in core options. i checked in drivers for microphone but there is no microphone driver in retroarch for ios. also, on the app store version of retroarch it says melonds ds is included but after installing the only ds core on there is desmume

**Comment by lkjhnsn7** [comment]
Using retroarch version 1.19.1, 
IOS version 18.0.1,
MelonDS core

I have never been asked for microphone access. None of the current settings allow me to access the microphone though the core claims to allow it.

**Comment by warmenhoven** [comment]
It's not in 1.19.1, it will be in the next released version. No ETA on that. In the meantime if you'd like you can join the TestFlight, which is just a nightly build of the upcoming App Store version.
