### ISSUE TITLE
Crashing on Fullscreen and Exit (Windows 7)

### ISSUE THREAD

**Issue by chinagreenelvis** [libretro/RetroArch#16526]
## Description

I'm having issues with Retroarch in Windows 7, both 64-bit and 32-bit. I'm running it on a Presario C700 laptop which has an Intel HD Graphics X3000 series onboard. If I try to go fullscreen or exit the program, it crashes.

### Expected behavior

I expect it to not crash.

### Actual behavior

It crashes.

### Steps to reproduce the bug

1. Be on Windows 7
2. Install Retroarch 1.17
3. Go fullscreen or exit the program

### Version/Commit

- RetroArch: 1.17

### Environment information

- OS: Windows 7

**Comment by gouchi** [comment]
Hi,

Can you try to provide some log using [Dr. Mingw](https://github.com/jrfonseca/drmingw) if we can have some information about the crash ?

As we don't provide anymore [retroarch_debug.exe](https://github.com/libretro/RetroArch/issues/14615). 

Thank you.

**Comment by chinagreenelvis** [comment]
I was able to get it running by reinstalling the latest build of Win7 Ultimate 64-bit and getting it fully updated, then switching the driver to DirectX 10. GL doesn't like the older hardware apparently and will still crash, however.
