### ISSUE TITLE
[iOS version] melonDS cannot be selected as a core

### ISSUE THREAD

**Issue by commandcontrolQ** [libretro/RetroArch#16533]
The option to select melonDS as a Nintendo DS/DSi core does not exist, even though the actual .info file is present in the Retroarch/info folder.

**Comment by hizzlekizzle** [comment]
Yes, the core is not included in the initial release. We hope to add it in soon.

**Comment by RobLoach** [comment]
https://github.com/libretro/RetroArch/issues/16531
