### ISSUE TITLE
[iOS Version] Catalan locale by default 

### ISSUE THREAD

**Issue by AaronMT** [libretro/RetroArch#16534]
* iOS 17.5
* iPhone 14 
* Region: Canada
* Language: English

Installed the newly released iOS version of Retroarch. On launch, I think it's Catalan. Expected English. 

It's possible that the app is mistakenly interpreting the region code "CA" for Canada as the language code for Catalan. This can happen if the app's localization logic incorrectly prioritizes language codes over region codes.

![image](https://github.com/libretro/RetroArch/assets/102331/9fc67262-f609-4efd-bcdc-87036c4243c3)

**Comment by hizzlekizzle** [comment]
Ah, yes, the region code. That explains it.

**Comment by warmenhoven** [comment]
Can you delete the app and try again with the new 1.8.1 from the App Store?

**Comment by AaronMT** [comment]
Thanks for the quick fix. Confirmed English.
