### ISSUE TITLE
Quick Menu Doesn't Work (null)

### ISSUE THREAD

**Issue by Lornardizzi** [libretro/RetroArch#16537]
So i have recently reset and updated retroarch through Emudeck

After that i tried opening the quick menu to change language settings and i couldn't

### Expected behavior

Well After pressing the Hotkey i expected the quick menu to open

### Actual behavior

Instead a text box appears on the bottom left corner saying "null" and nothing else happens.

### Steps to reproduce the bug

1. Open a game
2. Try to open Quick Menu
3. A text box saying "null" happens
4. Nothing Happens

### Bisect Results

[So i was having trouble using the touch screen of my Steam Deck because the mouse appeared, so i tried resetting to base options and updated retroarch and then the issue began, tried to reinstall everything etc...]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.18.0

### Environment information

- OS: Steam Deck 3.5.19
- Compiler: Emudeck

**Comment by Lornardizzi** [comment]
Thanks it was basically that, the Hotkey was basically unused i add to add it manually.

**Comment by zoltanvb** [comment]
I think this can be closed.
