### ISSUE TITLE
[Request] Yabause Sega Saturn emulation with OpenGLes3 

### ISSUE THREAD

**Issue by eddiebrook** [libretro/RetroArch#1654]
Running so much faster than the retroarch core! This opengles 3.0 + the NvS has increased performance a ton.
The main github changes to Yabause are included in Retroarch Nightly builds, but it doesn't have the OpenGLes3 render changes yet.

here examples: https://www.youtube.com/watch?v=2suJ8OOCSG4

**Comment by hizzlekizzle** [comment]
Yeah, we're aware of it. It would require changing it over to a libretro-gl core, rather than the software-rendered core that it is now. So, lotta work. It may happen sometime in the future but there are other things that are more pressing right now.

**Comment by twinaphex** [comment]
This should be moved to the Yabause libretro repo. I'm going to close it here so that you can open it there since there is no way to transfer issues from one repo to another.
