### ISSUE TITLE
[iOS/iPadOS] Nintendo Switch Pro Controller ABXY layout is not respected

### ISSUE THREAD

**Issue by jamescastells** [libretro/RetroArch#16543]
## Description

I have a Nintendo Switch Pro Controller and have applied a layout consistent to its design, eg. "B Button (Down)" is assigned to the Controller's B Button, "A Button (Right)" is assigned to the Controller's A Button, and so on.

![Screenshot 2024-05-17 at 3 19 10 PM](https://github.com/libretro/RetroArch/assets/5696029/542bcb4a-8baf-43fd-a9cd-37711f2e0c3b)

When loading any game, from any platform, I don't have any controller override. In this example, using SMB3 for NES, the core's configuration shows that if I press "B Button (Down)" (which is my controller's B button) it will send the signal to the game as the  NES' "B button":

![IMG_2E31169B5CC2-1](https://github.com/libretro/RetroArch/assets/5696029/a7b15c98-461d-426e-8d7d-6ed841a08c96)

### Expected behavior

If I press my controller's B button, the game's action for the B button should launch; in the case of SMB3, the item box should appear.

### Actual behavior

The B button action is not launching; it instead launches the action for the A Button. Pressing the A button launches the action of the B button. This is backwards from what the configuration says.

https://youtube.com/shorts/LZqyt0PhrHY?feature=share

### Steps to reproduce the bug

1. Connect a Switch Pro Controller to the iPad via bluetooth
2. Configure the controller normally (B button is B, A button is A, etc.)
3. Play any game

Version: 1.18.0 from the App Store

- RetroArch: [version/commit]

### Environment information

- OS: iPadOS 17.5

**Comment by jamescastells** [comment]
Testing this a bit more; whatever I set up on Retroarch controller's configuration as ABXY, this will not carry over into the games. For example, I setup that B = L2 and A = R2, but still SMB3 read the A and B buttons in the controller.

**Comment by jamescastells** [comment]
I just confirmed that whatever configuration with the Switch Pro Controller I put on the main controller's configuration will not carry over the games. I just set up **all the emulated buttons** as L1 in the controller:

![IMG_330368C0CCAB-1](https://github.com/libretro/RetroArch/assets/5696029/e16b395d-02fa-4c3c-a5cf-b958f0eb845c)

However, the game still reads all of my buttons, when it only should read L1. And since I can't change that, the layout is not being respected.

**Comment by hizzlekizzle** [comment]
I'm not clear on what you've done vs what you expect to happen. Did you go into settings > input > retropad binds > port 1 controls and map all retropad buttons to your physical L button?

**Comment by jamescastells** [comment]
Yes. And yet all the buttons on the controller Gamepad function when playing a game, when only L1 should function. I also noticed this happens with every controller, not just the Nintendo one.

**Comment by jamescastells** [comment]
I'm closing this issue since I opened [a new one](https://github.com/libretro/RetroArch/issues/16552) which attacks this problem in a more general way.
