### ISSUE TITLE
Wii playlist search hangs

### ISSUE THREAD

**Issue by Conan179** [libretro/RetroArch#16558]
## Description

I have the problem that I can't use the search on my Windows PC to get my Wii games into Retroarch's Wii playlist. The search process just hangs, no error message, on my Steamdeck the search works, with the same files.

### Steps to reproduce the bug

I go to “scan directory” or “scan file” and both behave the same.

### Version/Commit
2024-05-16_RetroArch.7z
1.18.0
Git ec8358c

### Environment information

- OS: Windows 11 x64
- Compiler: MinGW (10.02.0) 64-bit (retroarch system info)

**Comment by zoltanvb** [comment]
Is the version on Steam Deck the same? There was a similar error between last stable release (1.17.0) and recent nightly builds, that was fixed just yesterday (#16553 ), current nightly build should have the fix already for that.

**Comment by Conan179** [comment]
No, I don't have the same version on my Steamdeck, it's not even the same platform (Windows-Linux) I just wanted to say that it's not the image.
This b37debf fixed my error.

**Comment by zoltanvb** [comment]
Thank you for taking the time to report it!
