### ISSUE TITLE
Netplay disconnects when Android is server

### ISSUE THREAD

**Issue by rahbari** [libretro/RetroArch#1655]
When the android device is server Netplay connects and disconnects immediately with this error (Netplay has disconnected. Will continue without connection ...), But if pc is server and android is client it works. I tried it on multiple android devices and the result was the same! I compiled the code today and also checked the latest nightly build.

I did some debugging and found out that sendto in send_chunk in netplay.c fails with error 22 (invalid arguments).

update -------------------------------
I Just changed the sizeof(struct sockaddr) to sizeof(struct sockaddr_in6) and now it's working well.

**Comment by 6lackmag3** [comment]
Can you send a pull request? This issue hasn't been resolved yet.

**Comment by fr500** [comment]
fixed, works in my case, tried android vs android, androis vs windows, android vs linux
https://github.com/libretro/RetroArch/commit/690cb138e98f6c9414e65a765eb8affcbc683342

**Comment by fr500** [comment]
I'll try to actually validate the address family and use the correct struct later on

**Comment by 6lackmag3** [comment]
Can you share your settings for Android netplay, please? I just can't get it to work. Tried with latest nestopia, fceumm and snes9x cores. Here's my network setup for server and client:

![screenshot_2015-09-14-11-46-17](https://cloud.githubusercontent.com/assets/13922742/9845779/49a1221c-5ad6-11e5-879e-5fcaf4273075.jpeg)
![screenshot_2015-09-14-11-00-56](https://cloud.githubusercontent.com/assets/13922742/9844998/8448d6c2-5ad0-11e5-94ed-f6856e8fbafb.png)

If I join a server it starts playing content and shows 'got connection from "client" (::fff:192.168.100.6)" (#0)' while a client device says 'connected to "server"' but shows black/grey screen depending on a core. Few seconds later both server and client report 'Netplay has discontinued. Will continue without connection' and a game starts normally on a client device.
I'm on 09-13 nightly currently. Roms are identical on both devices. No firewalls or antivirus apps being used. I've also tried forwarding 55435 port in router settings but it gave nothing. Any help appreciated.

**Comment by fr500** [comment]
It looks all good.
Try the 14th nightly and make sure you update the cores so they match too

**Comment by 6lackmag3** [comment]
Yay! It works now! Thank you all, guys. RetroArch is awesome!
