### ISSUE TITLE
Combining Game Focus with Menu

### ISSUE THREAD

**Issue by chinagreenelvis** [libretro/RetroArch#16550]
## Description

In version 1.15, I set up the menu and game-focus hotkeys to be scroll_lock so that I'm able to bring up the menu when auto game-focus mode is on (necessary for Dosbox Pure). Pressing the button once disables game-focus and brings up the menu; pressing it again exits the menu and brings back game-focus.

In all versions after 1.15, the game-focus is not restored when exiting the menu this way.

### Expected behavior

When both menu and game-focus are bound to a single key, pressing that key twice (to exit the menu) should restore game-focus.

### Actual behavior

Game focus is not restored.

### Steps to reproduce the bug

1. Bind menu and game-focus to scroll_lock
2. Start a text-based game in Dosbox
3. Press scroll_lock twice
4. attempt to type

### Bisect Results

After updating from 1.15 to 1.18; the behavior was changed in 1.16

### Version/Commit

- RetroArch: 1.16, 1.17, 1.18

### Environment information

- OS: Windows 10 64bit

**Comment by hizzlekizzle** [comment]
This is less of a bug and more a case of making clever use of undefined/unintentional behavior. Unfortunately, that sort of thing is always at risk of being wiped out by changes to the underlying feature.

It was probably @sonninnos who changed/fixed the behavior, in which case it'd likely be up to him whether to try and restore this unintended (but, again, quite clever) behavior or not.

**Comment by chinagreenelvis** [comment]
Either that or an option to exempt the menu hotkey from game-focus would be helpful, just so much more convenient to hit one button rather than two each time I want to enter the menu for save states.

**Comment by chinagreenelvis** [comment]
Is there any chance of working out a solution for this? I've tried setting up a workaround in AHK but apparently AutoHotKey does not work with Retroarch... ?

**Comment by sonninnos** [comment]
Uhh, here it behaves exactly as expected, as in Game Focus is re-enabled as menu toggles off:

![retroarch_2024_11_06_03_04_57_853](https://github.com/user-attachments/assets/748d3cb6-6fff-419e-9bb7-dc4473e4c218)

**Comment by sonninnos** [comment]
I figured out a way, but I'll do a bit more testing to see if I can figure out a better way.

**Comment by chinagreenelvis** [comment]
> I figured out a way, but I'll do a bit more testing to see if I can figure out a better way.

Well, I know it's been a while since I posted this issue but I want to say thanks so much for taking a look into it.
