### ISSUE TITLE
Feature request iCloud sync

### ISSUE THREAD

**Issue by frootloop88** [libretro/RetroArch#16566]
Syncing save games with webdav is kind of a nightmare, especially for noobs.
Please add iCloud sync for safe games so we can have synced save games on all devices like Apple TV and iPhone.

**Comment by mikalcallahan** [comment]
This would be a huge improvement to UX

**Comment by MajorTomDE** [comment]
+1
best also syncing ROMs and settings

**Comment by TariqMK** [comment]
Also adding my vote - having saves across all my devices would be incredible.

**Comment by jbiznes** [comment]
This would awesome. Then I could sync to my Apple devices and my Windows devices.
