### ISSUE TITLE
blueMSX core not working in AppleTV app

### ISSUE THREAD

**Issue by TrevEB** [libretro/RetroArch#16569]
When attempting to run a colecovision title the error "Libretro core failed to open" occurs. This problem is unique to the appleTV app version.

**Comment by warmenhoven** [comment]
Yeah this is already fixed in git and will be part of the next App Store build.

**Comment by TrevEB** [comment]
Thanks for the update!
Glad to know I'm not the only one seeking a colecovision fix. ;)

**Comment by warmenhoven** [comment]
1.18.2 just got approved and should be available now.
