### ISSUE TITLE
Android UI Deprecated - Savefiles and Savestates Directories

### ISSUE THREAD

**Issue by chris062689** [libretro/RetroArch#1656]
This is not currently an issue, but will be once the Android UI is deprecated. 

# Overwritten Settings
Currently, specifically in the Android version of Retroarch available on the Play Store and the nightlies as of 4/22, some settings are being forced upon users when they hit the "Launch Retroarch" button in the main menu.

The setting have currently been identified as:  
* Savefile Directory     -  ```/data/data/com.retroarch/savefiles```
* Savestate Directory  - ```/data/data/com.retroarch/savestates```

Despite settings being changed in RGUI, these settings will be overwritten the next time the Android UI launches. 

# Migration Path
Once the Android UI is dropped, RetroArch will fallback to using the RGUI default settings, which have been identified as: 
* Savefile Directory     -  ```<Content dir>```
* Savestate Directory  -  ```<Content dir>```

This presents a problem for users that will be upgrading, as their savefiles will *appear* to be gone, as the directory is no longer the same.

### Proposals 
The purposed migration path is currently to present the user a popup informing them that their savefiles have been placed in a specific folder on their sdcard, and to move their .srm files into the same location as their roms.

**Comment by fr500** [comment]
I think this is irrelevant by now.
