### ISSUE TITLE
[Android] Touch controls break in RetroArch menu's/cores/games while using Backbone gen 2 usb c xbox edition controller

### ISSUE THREAD

**Issue by Makusugi** [libretro/RetroArch#16575]
## Description

when the Backbone USBC 2nd Generation Xbox version controller is connected, the touch controls in the RetroArch get all wonky. Without the controller connected the touch screen acts as normal. When its connected and you try to navigate the RetroArch menu's with touch controls, its almost as if they become uncalibrated or misaligned, and the tapping to select an option just refuses to work entirely.

 So for instance if i go to click on Load Core with the controller connected but using touch screen controls, its almost as if its registering my finger an inch or so away from where im actually touching, and tapping gestures on the screen to select an option doesnt register at all, only this broken version of swiping around, & of course the controller itself works fine for navigating the menu, and also when the controller is disconnected the touch screen controls in both the RetroArch menu's & games ive tried in Melon DS DS core work as they should.

 In the melon ds ds core itself with a game launched & the controller connected, it either refuses touch inputs alltogether, or gives me a single touch until it stops working entirely. Swiping to navigate to my android menu's & everything else is working fine while the controller is connected. Im not sure if this is a bug with RetroArch itself (i think it may be), the core, or my Samsung Galaxy S24 ultra being too new, or the backbone controller doing something odd to RetroArch. 
Id also like to mention the controller itself works fine in retroarch, it can navigate the menu's & do everything just fine in the games, it just breaks the touch inputs for some reason. Setting the touch inputs to the right stick & R3 to select works fine but id obviously rather use the legitimate touch controls as it should be. The odd thing is this doesnt happen anywhere else that ive tried; including the Standalone Melon DS Nightly build apk from their github. The touch screen controls remain intact using that while the controller is connected.

### Expected behavior

When backbone 2nd generation usb c xbox edition controller is connected to my Samsung Galaxy S24 Ultra I expect the RetroArch menu & cores within to respond to the controller inputs & also the touch screen inputs.

### Actual behavior

When my backbone 2nd generation usb c xbox edition controller is connected to my Samsung Galaxy s24 Ultra the touch screen controls don't work correctly anymore within RetroArch menu's & cores/games. Swiping/scrolling still responds in the menu but in a misaligned/broken manner where its not aligned to where you are actually touching the screen with your finger, its about an inch away from where you are actually touching, & tap/select gestures do not work at all, only this broken manner of swiping. The controller itself navigates the menu & games/cores just fine though.

### Steps to reproduce the bug

1. Plug in Backbone 2nd generation USB C xbox edition controller into Samsung Galaxy S24 Ultra's USB C port.
2. Open RetroArch app
3. Try to use the touch control gestures in the menu while the controller is connected. Controller works fine, Touch gestures/controls within RetroArch break entirely until backbone is disconnected

### Bisect Results

I have only used this latest version of RetroArch, so for me it has started here.

### Version/Commit

1.18.0_GIT

- RetroArch: 1.18.0_GIT

### Environment information

- OS: Android 14

**Comment by ThunderDragonRandy** [comment]
I also made a report about this months ago. https://github.com/libretro/RetroArch/issues/16227 I have the PlayStation Edition of the Backbone One controller, which has this issue. Galileo G8 too. However, no issues with Razer Raiju from what I remember when I last tested various controllers on these updates.

Other topics with this issue or similar issue include:

- https://github.com/libretro/RetroArch/issues/16210
- https://github.com/libretro/RetroArch/issues/15757
- https://github.com/libretro/RetroArch/issues/16091

This issue has occurred during development for v1.16 (around June 2023, I'm certain) so I recommend using v1.15 if you are gonna use Android controllers that are having touchscreen issues with RetroArch v1.16 and newer.

**Comment by RenanSD007** [comment]
The same thing happens here, using a GameSir T3s controller

**Comment by cepheiduck** [comment]
I've used a few different 8bitdos, all act in this way: the first time you touch a screen, it does a zap.  They no longer work after that.  Also same thing with the menus actually- first menu touch works, no menu touch taps work after that.

**Comment by hizzlekizzle** [comment]
Can you guys check whether this is fixed in the latest nightly build?

**Comment by ThunderDragonRandy** [comment]
> Can you guys check whether this is fixed in the latest nightly build?

Testing this, YES! This fix is available in the main RetroAch builds as of Nightly Build 2024-06-10. (Yay, we no longer have to use v1.15 anymore!)

**Comment by Makusugi** [comment]
Fixed for me as well on Samsung Galaxy S24 using Backbone 2nd generation usb C xbox edition controller! Thank you Hizzlekizzle!!!!

**Comment by RenanSD007** [comment]
I tested it on the last build and it worked perfectly :) thanks for the fix

**Comment by hizzlekizzle** [comment]
Great news! Thanks everyone. @Makusugi , would you mind closing this ticket out for us?
