### ISSUE TITLE
Audio issues with Atari XL/XE games

### ISSUE THREAD

**Issue by RyFeR26** [libretro/RetroArch#16596]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Tested on an iPad Pro, all Atari XL/XE games have audio issues, volume needs to be turned up to almost max, then there is sound but it's very distorted

### Expected behavior

Started game has normal audio

### Actual behavior

Started game has distorted audio

### Steps to reproduce the bug

1. Select game in RetroArch
2. Start game
3. Play, issue is there from the start

### Bisect Results

From memory, first version I installed from the app-store did not have the issue (1.18.1) but not 100% sure. 1.18.2 and 1.18.3 do show this behavior. 

All games from other systems are working perfectly, no sound issues at all.

### Version/Commit
Currently on 1.18.3 which has the issue

- RetroArch: [version/commit]
Currently on 1.18.3 which has the issue

### Environment information

- OS: iPadOS 17.5.1
- Compiler: n/a, using app-store version

**Comment by RyFeR26** [comment]
Did some more investigations after I updated my Android box to RetroArch 1.18.0 and updated all cores as I had the same issue after the update...

Turns out that the latest Atari800 core version (Atari800 3.1.0 8bfa3b8) has the sound issue on both Android and iOS. 
On Android I could revert back to a previous core (Atari800 3.1.0 20d59af) which works perfectly with sound for all Atari games.

On iOS the Atari800 core is within the install package and can't be changed as far as I know. Is there a way to use the previous core (Atari800 3.1.0 20d59af) or use this one in a future RetroArch for iOS build?

**Comment by gouchi** [comment]
If it is related to the core, please open an [issue](https://github.com/libretro/libretro-atari800/issues) to the dedicated repo.

Thank  you.

**Comment by RyFeR26** [comment]
Will do, thanks for the link!

**Comment by amiroff** [comment]
I am having the same problem on ios, tvos and Macos. Previous core is not avaliable for download so I cannot revert back.

**Comment by gouchi** [comment]
@RyFeR26 It will be better to close this issue in favor to the other [issue](https://github.com/libretro/libretro-atari800/issues/96).

@amiroff Thank you for the feedback. It will be better to continue on the [dedicated issue](https://github.com/libretro/libretro-atari800/issues/96).

**Comment by RyFeR26** [comment]
If that's preferred then by all means close this one... only hope something happens in the other tread (core seems to be kind of abandoned unfortunately)

**Comment by gouchi** [comment]
@RyFeR26 Please close this issue. Thank you.

**Comment by RyFeR26** [comment]
Cosing by request. This is not solved, all environments I've tested (iOS, Android, Windows) have the sound issue with the Atari800 3.1.0 8bfa3b8 core version.

Hoping that this will be picked up / resolved in the core repo ( [issue](https://github.com/libretro/libretro-atari800/issues/96) )
