### ISSUE TITLE
Compilation error in vg.c

### ISSUE THREAD

**Issue by GoldenCrystal** [libretro/RetroArch#1661]
While trying to compile RetroArch, I noticed two errors in vg.h. Fortunately, those were easy to patch:
• in function vg_calculate_quad, the line "global_t *global     = global_get_ptr();" should be moved to the top, outside of the if block.
• in function vg_frame, the line "global_t *global     = global_get_ptr();" should be added somewhere before the call to vg_copy_frame.

**Comment by twinaphex** [comment]
Check if this commit addresses the issues you mentioned -

https://github.com/libretro/RetroArch/commit/0ba4e81e634680ce30fbb83f1bc11b9d8f405372

**Comment by GoldenCrystal** [comment]
Seems to be perfect. Thanks !
