### ISSUE TITLE
[LINUX KMS] Refresh rate switching does not work (debugged)

### ISSUE THREAD

**Issue by kokoko3k** [libretro/RetroArch#16613]
I'm trying kms modes and refresh rate switching does not work. for reasons I fail to understand.

I modified the code to output some useful info:
the file is: gfx/drivers_context/drm_ctx.c

i modified the snippet as follows:
```
static bool gfx_ctx_drm_set_video_mode(void *data,
      unsigned width, unsigned height,
      bool fullscreen)
{
```
[..]
```
   if ((width == 0 && height == 0) || !fullscreen)
   {
      if (width == 0 && height == 0)
         RARCH_WARN("[KMS]:w or h is zero\n");
      if (!fullscreen)
         RARCH_WARN("[KMS]:not fullscreen\n");      
      
      RARCH_WARN("[KMS]:koko w and h are %dx%d\n", width, height);
      RARCH_WARN("[KMS]:not fullscreen\n");       
      
      RARCH_WARN("[KMS]: Falling back to mode 0 (default)\n");
      g_drm_mode     = &g_drm_connector->modes[0];
   }
```
Then started a game at 50Hz and got that in the log:

```
[INFO] [Video]: Timings deviate too much. Will not adjust. (Target = 60.00 Hz, Game = 50.00 Hz)
[INFO] [Video]: Set video size to: 1536x864.
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: yes
[INFO] [DRM]: Connector 1 has 20 modes.
[INFO] [DRM]: Connector 1 assigned to monitor index: #1.
[INFO] [DRM]: Connector 2 connected: yes
[INFO] [DRM]: Connector 2 has 20 modes.
[INFO] [DRM]: Connector 2 assigned to monitor index: #2.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 59.995499 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 75.002274 Hz
[INFO] [DRM]: Mode 2: (1920x1080) 1920 x 1080, 71.996422 Hz
[INFO] [DRM]: Mode 3: (1920x1080) 1920 x 1080, 49.995480 Hz
[INFO] [DRM]: Mode 4: (1680x1050) 1680 x 1050, 59.883251 Hz
[INFO] [DRM]: Mode 5: (1600x900) 1600 x 900, 60.000000 Hz
[INFO] [DRM]: Mode 6: (1280x1024) 1280 x 1024, 75.024673 Hz
[INFO] [DRM]: Mode 7: (1280x1024) 1280 x 1024, 60.019741 Hz
[INFO] [DRM]: Mode 8: (1152x864) 1152 x 864, 75.000000 Hz
[INFO] [DRM]: Mode 9: (1280x720) 1280 x 720, 60.000000 Hz
[INFO] [DRM]: Mode 10: (1280x720) 1280 x 720, 59.940201 Hz
[INFO] [DRM]: Mode 11: (1024x768) 1024 x 768, 75.028580 Hz
[INFO] [DRM]: Mode 12: (1024x768) 1024 x 768, 60.003841 Hz
[INFO] [DRM]: Mode 13: (832x624) 832 x 624, 74.551270 Hz
[INFO] [DRM]: Mode 14: (800x600) 800 x 600, 75.000000 Hz
[INFO] [DRM]: Mode 15: (800x600) 800 x 600, 60.316540 Hz
[INFO] [DRM]: Mode 16: (640x480) 640 x 480, 75.000000 Hz
[INFO] [DRM]: Mode 17: (640x480) 640 x 480, 60.000000 Hz
[INFO] [DRM]: Mode 18: (640x480) 640 x 480, 59.940475 Hz
[INFO] [DRM]: Mode 19: (720x400) 720 x 400, 70.081665 Hz
[INFO] [GLCore]: Found GL context: "kms".
[INFO] [GLCore]: Detecting screen resolution: 1920x1080.
[WARN] [KMS]:not fullscreen
[WARN] [KMS]:koko w and h are 1536x864
[WARN] [KMS]:not fullscreen
[WARN] [KMS]: Falling back to mode 0 (default)
```

Somehow instead of picking the nearest refresh rate, which appears to be Mode 3:
[INFO] [DRM]: Mode 3: (1920x1080) 1920 x 1080, 49.995480 Hz

It tries to syng to
[INFO] [DRM]: Mode 8: (1152x864) 1152 x 864, 75.000000 H

Then it detects it as not fullscreen.

Is the mode selection logic somehow flawed?

**Comment by kokoko3k** [comment]
Uhm, i entered Xorg, switched to fullscreen, exited retroarch, went back to kms console and restarted retroarch there.

Refresh rate switching still wont work, but this time the log is clearer without warnings.

I'm kinda clueless.

```
[INFO] [Audio]: Set audio input rate to: 48000.00 Hz.
[INFO] [Video]: Set video size to: 1920x1080.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: yes
[INFO] [DRM]: Connector 1 has 20 modes.
[INFO] [DRM]: Connector 1 assigned to monitor index: #1.
[INFO] [DRM]: Connector 2 connected: yes
[INFO] [DRM]: Connector 2 has 20 modes.
[INFO] [DRM]: Connector 2 assigned to monitor index: #2.
[INFO] [DRM]: Mode 0: (1920x1080) 1920 x 1080, 59.995499 Hz
[INFO] [DRM]: Mode 1: (1920x1080) 1920 x 1080, 75.002274 Hz
[INFO] [DRM]: Mode 2: (1920x1080) 1920 x 1080, 71.996422 Hz
[INFO] [DRM]: Mode 3: (1920x1080) 1920 x 1080, 49.995480 Hz
[INFO] [DRM]: Mode 4: (1680x1050) 1680 x 1050, 59.883251 Hz
[INFO] [DRM]: Mode 5: (1600x900) 1600 x 900, 60.000000 Hz
[INFO] [DRM]: Mode 6: (1280x1024) 1280 x 1024, 75.024673 Hz
[INFO] [DRM]: Mode 7: (1280x1024) 1280 x 1024, 60.019741 Hz
[INFO] [DRM]: Mode 8: (1152x864) 1152 x 864, 75.000000 Hz
[INFO] [DRM]: Mode 9: (1280x720) 1280 x 720, 60.000000 Hz
[INFO] [DRM]: Mode 10: (1280x720) 1280 x 720, 59.940201 Hz
[INFO] [DRM]: Mode 11: (1024x768) 1024 x 768, 75.028580 Hz
[INFO] [DRM]: Mode 12: (1024x768) 1024 x 768, 60.003841 Hz
[INFO] [DRM]: Mode 13: (832x624) 832 x 624, 74.551270 Hz
[INFO] [DRM]: Mode 14: (800x600) 800 x 600, 75.000000 Hz
[INFO] [DRM]: Mode 15: (800x600) 800 x 600, 60.316540 Hz
[INFO] [DRM]: Mode 16: (640x480) 640 x 480, 75.000000 Hz
[INFO] [DRM]: Mode 17: (640x480) 640 x 480, 60.000000 Hz
[INFO] [DRM]: Mode 18: (640x480) 640 x 480, 59.940475 Hz
[INFO] [DRM]: Mode 19: (720x400) 720 x 400, 70.081665 Hz
[INFO] [GLCore]: Found GL context: "kms".
[INFO] [GLCore]: Detecting screen resolution: 1920x1080.
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x57001353d910.
[INFO] [KMS]: New FB: 1920x1080 (stride: 7680).
[INFO] [GLCore]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2).
[INFO] [GLCore]: Version: 4.5 (Core Profile) Mesa 21.3.9-arch.6 Amber.
[INFO] [GLCore]: Using resolution 1920x1080.
```

**Comment by kokoko3k** [comment]
Issue is that under xorg the window was NOT set to fullscreen, so KMS detects its wrong size and thinks it is not fullscreen.

Is there really need to check if a window is fullscreen under KMS? there is no window concept, everything is fullscreen there.

Can we just pretend fullscreen is always true? Also, under kms there is no fullscreen menu item at all (as expected) to be switched.

**Comment by gouchi** [comment]
Related  [issue](https://github.com/libretro/RetroArch/issues/8663) and [PR](https://github.com/libretro/RetroArch/pull/15301).

**Comment by gouchi** [comment]
@zoltanvb you might have some input ;)

Thank you.

**Comment by zoltanvb** [comment]
KMS and XOrg in the same install is rare, probably this is why it did not come up so far. Indeed it looks like it tries to set a windowed resolution. Maybe adding VIDEO_DRIVER_FORCE_FULLSCREEN flag would be the easiest way out of this, without inheriting the fullscreen settings next time RA is launched again from XOrg.

For workarounds, config file editing, CLI option, or maybe even the hotkey could toggle the fullscreen setting.

**Comment by kokoko3k** [comment]
JFYI, Hotkey does nothing, I tried :)

What's VIDEO_DRIVER_FORCE_FULLSCREEN?

**Comment by zoltanvb** [comment]
It is a flag set inside the video driver. I'll eventually get to set up a suitable test environment, hopefully the change will be small.

**Comment by kokoko3k** [comment]
Great, thanks!

**Comment by chcore** [comment]
Thanks for this. KMS refresh rate switching works for me on 1.20.0 with glcore, but not vulkan. Is vulkan not supported @zoltanvb ?

**Comment by zoltanvb** [comment]
The level of support is lower indeed. #15326 added some flexibility, but it is limited to changing the refresh rate on startup. I have a half-baked attempt at doing the same thing for the Vulkan khr_display context driver, but ran into some problems, maybe I can resume that.

**Comment by chcore** [comment]
> The level of support is lower indeed. [#15326](https://github.com/libretro/RetroArch/pull/15326) added some flexibility, but it is limited to changing the refresh rate on startup. I have a half-baked attempt at doing the same thing for the Vulkan khr_display context driver, but ran into some problems, maybe I can resume that.

Thank you, I have raised issue #17437 for tracking purposes if/when you decide to take a look.

**Comment by kokoko3k** [comment]
@zoltanvb 

Unfortunately the issue is back somehow.
It is mandatory to set RA to fullscreen in Xorg, for the refresh to be switched in console/KMS.

It's interesting that this time log shows that it changed the reported state to "fullscreen for this session".
```
[DEBUG] [GLCore] Config requires windowed mode, but context driver does not support it. Forcing fullscreen for this session.
```
[out.log](https://github.com/user-attachments/files/26324208/out.log)


it seems this time fullscreen is set but WxH is 0x0

@chcore does it still work for you?
