### ISSUE TITLE
Refresh Rate switching needs better checking on refresh rates

### ISSUE THREAD

**Issue by kokoko3k** [libretro/RetroArch#16615]
## Description
I think the current check for matching vertical refresh rate needs some adjustments

[Description of the bug]
Due to my refresh rate and current implementation, auto switching can't work.
I've set a fullscreen mode, disablet CRT switchres and went into a KMS console.
Started a PAL Amiga game, a 49.95hz, naive resolution modeline is available.

### Expected behavior
Retroarch to switch to 49.95hz modeline

### Actual behavior
Retroarch does not switch, stay at 60hz.

### Bisect Results
Since commit b8188baeafbbc364d01705064d31e2136793c42f

@sonninnos probably.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.18 / 3a56b73a31282f24ff3b00dd507c40cf2a83e6d8

### Environment information
- OS: Linux+KMS
- Compiler: GCC 13.2.1-3 Archlinux Package

### Notes
I identified the problematic code which was later moved to video_driver.c:
in:
```
bool video_display_server_has_refresh_rate(float hz)
```
...there is a check to match hz, like this:
```
video_list[i].refreshrate == floor(hz)
```
Now, since my modeline falls under 50hz, it would never be picked.

Could that be changed to something equivalent like the following?
```
abs(video_list[i].refreshrate - floor(hz)) <=1.0

```

Thanks!

**Comment by sonninnos** [comment]
This non-CRT refresh rate changer has never even worked outside of Windows, since other display servers don't have `get_resolution_list` hooked up, and it was not intended outside the use of standard PAL and NTSC on modern displays.

Pretty sure the reason for the `floor` there is to make sure that 59.94 won't round up to 60, since it is 59 integer in OS level. So perhaps getting under 50 to match as 50 then might need a special case. But might be easier to just make the exact 50 mode available.

**Comment by zoltanvb** [comment]
If you want, give a try to this branch: https://github.com/zoltanvb/RetroArch/tree/refresh_rate_float3
I still need to work on it, to make sure Windows side stays intact, but KMS-wise it should work already.

**Comment by kokoko3k** [comment]
Sure, thanks, I'll do tomorrow!

**Comment by kokoko3k** [comment]
> If you want, give a try to this branch: https://github.com/zoltanvb/RetroArch/tree/refresh_rate_float3 I still need to work on it, to make sure Windows side stays intact, but KMS-wise it should work already.

It works fine, thank you very much!
