### ISSUE TITLE
1.18.0: double-free crash with truncated 7z file

### ISSUE THREAD

**Issue by rofl0r** [libretro/RetroArch#16626]
## Description

i was scanning my games directory, and retroarch crashed (note - using musl libc which has a hardenend allocator detecting double-free).
turns out that one of the .7z files was only half-downloaded, or truncated for another reason.
p7zip prints:

```
Open ERROR: Can not open the file as [7z] archive
ERRORS:
Unexpected end of archive
```

[Description of the bug]

```
Thread 2 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff7d5425d in get_meta (p=0x7fffee45b2f0 "")
    at src/malloc/mallocng/meta.h:132
132             int offset = *(const uint16_t *)(p - 2);
(gdb) bt
#0  0x00007ffff7d5425d in get_meta (p=0x7fffee45b2f0 "")
    at src/malloc/mallocng/meta.h:132
#1  0x00007ffff7d54ad7 in __libc_free (p=0x7fffee45b2f0)
    at src/malloc/mallocng/free.c:105
#2  0x00007ffff7d53570 in free (p=0x7fffee45b2f0) at src/malloc/free.c:5
#3  0x0000000000bf2f4b in sevenzip_parse_file_free (context=0x7fffeee45e00)
    at ./libretro-common/file/archive_file_7z.c:128
#4  0x0000000000bf2002 in file_archive_parse_file_iterate (
    state=0x7ffff7fa2830, returnerr=0x0, file=0x0, valid_exts=0x0, 
    file_cb=0x0, userdata=0x0) at ./libretro-common/file/archive_file.c:243
#5  0x0000000000bf1e8d in file_archive_parse_file_iterate_stop (
    state=0x7ffff7fa2830) at ./libretro-common/file/archive_file.c:188
#6  0x0000000000bf2a02 in file_archive_get_file_crc32 (
    path=0x7fffeee47fa0 "/tmp/bug/corrupt.7z")
    at ./libretro-common/file/archive_file.c:692
#7  0x00000000005f1dd0 in task_database_iterate_crc_lookup (
    _db=0x7fffeed9c2c0, db_state=0x7fffeed9c2e0, db=0x7fffee3b0360, 
    name=0x7fffeee47fa0 "/tmp/bug/corrupt.7z", 
    archive_entry=0x0, path_contains_compressed_file=false)
    at tasks/task_database.c:924
#8  0x00000000005f2676 in task_database_iterate (_db=0x7fffeed9c2c0, 
    name=0x7fffeee47fa0 "/tmp/bug/corrupt.7z", 
    db_state=0x7fffeed9c2e0, db=0x7fffee3b0360, 
    path_contains_compressed_file=false) at tasks/task_database.c:1180
#9  0x00000000005f2baf in task_database_handler (task=0x7fffef3e7160)
    at tasks/task_database.c:1320
#10 0x0000000000505e21 in threaded_worker (userdata=0x0)
    at ./libretro-common/queues/task_queue.c:511
#11 0x00000000007a2075 in thread_wrap (data_=0x7ffff288ce30)
    at ./libretro-common/rthreads/rthreads.c:148
#12 0x00007ffff7dafe8a in start (p=0x7ffff7fa2a98)
    at src/thread/pthread_create.c:207
#13 0x00007ffff7db44c0 in __clone () at src/thread/x86_64/clone.s:22
Backtrace stopped: frame did not save the PC
```
### Expected behavior

no crash

### Actual behavior

crash

### Steps to reproduce the bug

1. compile retroarch with address sanitizer or use musl libc
2. put a rom into a 7z, then truncate the file in the middle. store in an otherwise empty dir for easier debugging
3. scan the dir

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.18.0

### Environment information

- OS: linux
- Compiler: not relevant

i was actually trying to fix the bug myself, but the battery status updater task interfered with my breakpoint on free so often, that i lost interest. i'd suggest changing the interval it runs to at most every 30 seconds. it's not only annoying when debugging, but the constant polling also produces cpu load.

**Comment by warmenhoven** [comment]
THANK YOU for this, this was the top crash on iOS last version and I couldn't figure out how to reproduce it.

**Comment by rofl0r** [comment]
nice, let's hope the same bug isn't in the zip code too. ;)

**Comment by warmenhoven** [comment]
Ha, I actually had to go check because of your comment. All of the state/context fields seem to be getting reset appropriately, so I'm pretty sure there's not a similar bug in the zip code.
