### ISSUE TITLE
Touchscreen doesnt work on Samsung Phones (Android 14)

### ISSUE THREAD

**Issue by starjunn99** [libretro/RetroArch#16632]
## Description

Edit = My phone is brand new , clean settings with nothing custom to break retroarch.

I installed and tested 1.16.0 , 1.17.0 , 1.18.0 and 1.19.0 on samsung phones/tablets simply not recognize touchscreen (pre 1.16.0 works as intended and fine 1.15.0). **I need to clarify this NO EXTRA USB or anything Plugged just phone itself , so please dont confuse this topic with other usb plug bugs comes after 1.16.0**

### Expected behavior

Normal working touchscreen (same behavior pre 1.16.0 , 1.15.0 touchscreen works fine)

### Actual behavior

When i open Retrorach first tap actualy works i click quick menu for example but nothing beyond after that i can only slide down and up. (Every config is default fresh install , nothing imported or exported)

Pretty much same issue like this video here 
https://github.com/libretro/RetroArch/issues/15672#issuecomment-1709879276

### Steps to reproduce the bug

Testing on any samsung phone or tablet will bring same results

This topic also mentions same problems on samsung S series phones and Tablets
https://github.com/libretro/RetroArch/issues/15757#issuecomment-1968019590

### Bisect Results

After One UI 6 update , before i had no issue when i first installed phone , table was already updated so i assume same issue.

Someone mentioned in the topic plugging bluetooth devices may fix the issue but i tested 2 different smartwatch to see any changes or not nope touchscreen still same (tried input on off trick doesnt work)

Edit = I did copy 1.19.1 default working settings cfg to my phone cfg still doesnt work should be 100% code related.

### Version/Commit
Stable version Android 1.16.0 , 1.17.0 , 1.18.0 and 1.19.0 x64 and latest 1.19.0 nighlty build same issue.

**Update = 1.19.1 Still not fixed.**

### Environment information

- OS: Samsung A05s / Android 14 / One UI 6
_Samsung A9+ Tablet both simply doesnt work (1.19.1 works on tablet)_

**Comment by starjunn99** [comment]
A small update this issue exist on all 32bit and 64bit versions after 1.15.0 , read someone mention touch controls changed after 1.15.0 so this could be core change not simple bug

**Comment by arnaullv** [comment]
This commit breaks the touchpad input, see https://github.com/libretro/RetroArch/issues/15757

https://github.com/libretro/RetroArch/commit/abcd42777f7c17559cf6eb509dc86aca63e48527 refactor: rewrite input handling to better support AINPUT_SOURCE_STYLUS (https://github.com/libretro/RetroArch/pull/15597)

**Comment by starjunn99** [comment]
Latest nightly version fixes this issue once for all thanks hunterk

https://github.com/libretro/RetroArch/pull/16673
