### ISSUE TITLE
HAVE_LAKKA_SERVER and HAVE_LAKKA_PROJECT values compilation error

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/RetroArch#16636]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Starting commit https://github.com/libretro/RetroArch/commit/c4f84094c2c569a8ee4410f6043f19ad48129be2

It is needed to add HAVE_LAKKA_SERVER and HAVE_LAKKA_PROJECT but I don't see any documentation about the potential values.

### Expected behavior

Know the values to compile it right.

### Actual behavior

Error compiling due to not knowing the values for those variables

make[1]: Entering directory '/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/retroarch-8b213d3c0daaac99d8fec9b85f5337383c8600e2'
Makefile.common:1067: *** You asked for Lakka, but you did not specify update server in HAVE_LAKKA_SERVER.  Stop.
make[1]: Leaving directory '/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/bui

make[1]: Entering directory '/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/retroarch-8b213d3c0daaac99d8fec9b85f5337383c8600e2'
Makefile.common:1062: *** You asked for Lakka, but you did not specify a target device name in HAVE_LAKKA_PROJECT.  Stop.
make[1]: Leaving directory '/home/kelv/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/retroarch-8b213d3c0daaac99d8fec9b85f5337383c8600e2'
FAILURE: scripts/build retroarch:target during make_target (package.mk)
*********** FAILED COMMAND ***********

### Steps to reproduce the bug

Use latest commit

### Bisect Results

(https://github.com/libretro/RetroArch/commit/c4f84094c2c569a8ee4410f6043f19ad48129be2)

### Version/Commit
[You can find this information under Information/System Information](https://github.com/libretro/RetroArch/commit/c4f84094c2c569a8ee4410f6043f19ad48129be2)

- RetroArch: [version/commit]

https://github.com/libretro/RetroArch/commit/8b213d3c0daaac99d8fec9b85f5337383c8600e2

### Environment information

- OS: emuelec 4.8 linux

**Comment by gouchi** [comment]
Hi,

It would be better to open this issue to the [dedicated repository](https://github.com/libretro/Lakka-LibreELEC/issues).

Thank you.

**Comment by ToKe79** [comment]
It's not an issue, that is intented behavior for building RetroArch for Lakka. Instead of having those values hardcoded and change the header files in case a change of the server URL is needed, the update server base URL (HAVE_LAKKA_SERVER=...) is provided at build time. Also to have full path to the update for the current device, during runtime the DEVICE.ARCH string was parsed from file system, which is not bullet proof and caused issues for some naming conventions, the DEVICE.ARCH is passed (HAVE_LAKKA_PROJECT=...) during build time.

**Comment by Kelvfimer** [comment]
Thx
