### ISSUE TITLE
Typo in a keymap code? XVFK instead of XFVK

### ISSUE THREAD

**Issue by rapenne-s** [libretro/RetroArch#16631]
In https://github.com/libretro/RetroArch/blob/master/input/input_keymaps.c#L1206 a keymap is named `XVFK_HOMP` but all keymaps around that code start with `XFVK` and not `XVFK`, it looks like a typo?

**Comment by zoltanvb** [comment]
Can't exactly remember how I generated the corresponding header, may have been a typo. 
https://github.com/libretro/RetroArch/blob/47dd4e7e75e897450b88d3f3f0d30fac9cf0bbfe/input/include/xfree86_keycodes.h#L185

**Comment by odditude42** [comment]
"XFVK" implies XFree Virtual Key.

**Comment by rapenne-s** [comment]
Seems it may be a typo but there are no associated issues because the name is consistent across all the files. I don't think the efforts to fix and test the fix are worth...

**Comment by odditude42** [comment]
@zoltanvb is it a good idea to correct it to make sure it's not missed in any future refactoring activities?

**Comment by zoltanvb** [comment]
There is no reason for it to be different, I'll submit a fix eventually. Thank you for reporting!
