### ISSUE TITLE
retroarch crash when enter psp  game if enable auto load sate

### ISSUE THREAD

**Issue by HowQuitVim** [libretro/RetroArch#16642]
## Description

retroarch crash when enter psp  game if enable auto load sate

### Expected behavior

enter game normally

### Actual behavior

retroarch will crash ,and back to ios launhcer

### Steps to reproduce the bug

1. enable auto load state 
2. enter a psp game

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.19.0/e2f91d8b5f

- OS: IOS 17.5.1

**Comment by HowQuitVim** [comment]
https://github.com/libretro/RetroArch/assets/28687659/128aa177-a897-4205-8582-a3300e39bc7a

**Comment by HowQuitVim** [comment]
[retroarch__2024_06_03__21_29_58.log](https://github.com/user-attachments/files/15534511/retroarch__2024_06_03__21_29_58.log)
this my log

**Comment by hizzlekizzle** [comment]
>or frontend must wait until x frames from start before punching the load in.

This seems like a reasonable move, just to be safe.

**Comment by sonninnos** [comment]
Luckily threaded tasks already have `when` available, so it seems like the easiest route for now, even though the success will depend on the speed of the loading since it is purely time based, since changing ppsspp to finalize init already in `retro_load_game()` instead of current `retro_run()` isn't looking simple due to the way when the frontend does the hw context reseting, which is required for the init to proceed..

**Comment by sonninnos** [comment]
The core is fixed to fail nicely instead of crashing. The notification widget shows success even though unserialize returns false.. Next stop is to find the best way to postpone the loading just a bit on startup.

**Comment by gouchi** [comment]
@HowQuitVim @bslenul Can you confirm it is working using latest update ?

Thank you.

[Source](https://github.com/hrydgard/ppsspp/pull/19250)

**Comment by bslenul** [comment]
Yup, doesn't crash for me anymore.

**Comment by gouchi** [comment]
@HowQuitVim  If it is ok for you, please close this issue.

Thank you.

**Comment by HowQuitVim** [comment]
i can not test for now，but i believe problem has been resolved，i will close this issue，thanks
