### ISSUE TITLE
RetroArch 1.19 Android crashing to home screen on Retroid Pocket 4 Pro when loading NES game TMNT 2 The Arcade Game w/achievements enabled

### ISSUE THREAD

**Issue by ejleslie** [libretro/RetroArch#16648]
## Description

If RetroAchievements are enabled when loading NES ROM "Teenage Mutant Ninja Turtles 2: The Arcade Game" with any NES core on the Android version of RetroArch 1.19, the game will begin to load but then immediately crash to the Android home screen. If achievements are disabled, the game will load and play normally.

### Expected behavior

The ROM should load and play properly whether achievements are enabled or not.

### Actual behavior

If achievements are enabled, RetroArch crashes to the Android home screen.

### Steps to reproduce the bug

1. Enable achievements in the Android build of RetroArch 1.19 (in my case done on the Retroid Pocket 4 Pro).
2. Load the NES ROM "Teenage Mutant Ninja Turtles 2: The Arcade Game" using any NES core.
3. RetroArch will crash to the Android home screen.
4. Disable achievements, and the ROM will then load properly.

### Bisect Results

I saw this behavior in 1.18 before updating my RetroArch to 1.19 in hopes that it had been corrected, but it was still happening. I do not know if it behaved this way prior to 1.18.

### Version/Commit
You can find this information under Information/System Information

- RetroArch Version 1.19.0
- Git Version 00b8a5f
- Build Date 5/30/24

### Environment information

- OS: Android 13
- Device: Retroid Pocket 4 Pro software version 1.0.0.58

**Comment by ejleslie** [comment]
This bug also discussed (and confirmed by another user) on the [Retroid subreddit](https://www.reddit.com/r/retroid/comments/1d7ia3x/retroarch_crashing_when_loading_just_one_nes_game/).

**Comment by gouchi** [comment]
May you try to provide some [log](https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-android) ?

Thank you.

**Comment by ejleslie** [comment]
Sure - here's are two logs showing an attempt to run the game with Vulkan and OpenGL output. In both cases you can see the log ends (because RetroArch has crashed) right after the RCHEEVOS log lines indicating it is trying to start the session.
[retroarch__2024_06_03__03_24_11.log](https://github.com/user-attachments/files/15545055/retroarch__2024_06_03__03_24_11.log)
[retroarch__2024_06_03__03_26_49.log](https://github.com/user-attachments/files/15545056/retroarch__2024_06_03__03_26_49.log)

**Comment by ejleslie** [comment]
The problem is also being discussed by folks on the [RetroAchievements page for the game](https://retroachievements.org/game/2114) (scroll to bottom), where users indicate they've seen this behavior since June 1.

**Comment by Jamiras** [comment]
This is a problem with bad data on the server being exposed differently by the recent RAWeb release. It's not a RetroArch problem. We'll get the data cleaned up and the server patched. I'll reply again once it's been addressed.

**Comment by Jamiras** [comment]
The bad data has been corrected. I've also opened a PR to prevent this from happening again in the future. I believe this can be closed.

**Comment by ejleslie** [comment]
Looking good on my end now! Thanks for the quick turnaround.

**Comment by odditude42** [comment]
I'd argue this is still a bug that should be resolved - bad data from the retroachievements server shouldn't cause a local crash, rather an exception that should be handled gracefully.
