### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Fulanito0** [libretro/RetroArch#16664]
The quick save does not work and closes the app.
The cheat update stays unzipping until you exit the app and the message is removed.

I was playing zelda ocarina of time when I tried to do a quick save and using all the settings I could think of to make it work and it still never worked, just crashing. 

Version:1.19.1

**Comment by hizzlekizzle** [comment]
This is not enough information to act on your report, I'm afraid. The issue template exists to ensure we get the information we need.
