### ISSUE TITLE
Switchres has incredibly poor documentation.

### ISSUE THREAD

**Issue by chinagreenelvis** [libretro/RetroArch#16662]
## Description

Switchres doesn't work because I don't know how to make it work. All tutorials are outdated by years, and the documentation explains extraordinarily little about how to actually get it to function properly.

### Expected behavior

I expect to be able to find a resource that can explain to me very clearly how to get switchres to work on any television CRTs or VGA monitors I have connected to my computer.

### Actual behavior

I've spent an entire week trying to get it to work. On an RTX 3080, switchres does nothing. On a Radeon 5450 and CRTEmudriver, it causes Retroarch to crash.

### Steps to reproduce the bug

Literally just go here and read it and come away still knowing nothing: https://docs.libretro.com/guides/crtswitchres/

**Comment by gouchi** [comment]
Hi,

If the issue is related to documentation, please open it to the [dedicated repository](https://github.com/libretro/docs).

Thank you.
