### ISSUE TITLE
[Windows] "Failed to install core" message 

### ISSUE THREAD

**Issue by RQkaiju2** [libretro/RetroArch#16667]
## Description
when trying to install a core from both the core downloader  and the "install a core" feature, it will give me a message that says it failed to install the core.

![Screenshot 2024-06-07 182023](https://github.com/libretro/RetroArch/assets/145053001/fdd07997-6e54-4e7e-b586-d50677277450)

### Expected behavior

i was expecting it to download the core.

### Actual behavior

instead of downloading the core, it shows a message that looks like a "sucess" message but instead says "Failed to install core: [core name]".

### Steps to reproduce the bug

all i have to do is go to online updater, try to install any of the cores, and it brings up the message.

### Bisect Results

its been happening ever since i installed retroarch, and even if i reinstall it nothing will work.

### Version/Commit

- RetroArch: 1.19.1

### Environment information

- OS: Windows 11, 64 but

**Comment by sonninnos** [comment]
No problem here:
![retroarch_2024_06_08_02_48_18_041](https://github.com/libretro/RetroArch/assets/45124675/b513fbf9-f3ef-49af-b5a2-2187a4172486)

**Comment by hizzlekizzle** [comment]
Did you install to a location that requires elevated privileges to write to? Such as "Program Files"?

**Comment by RQkaiju2** [comment]
> Did you install to a location that requires elevated privileges to write to? Such as "Program Files"?

just checked, its in C:\RetroArch-Win64, that could be causing the issue

**Comment by RQkaiju2** [comment]
ok, i've managed to solve the issue by running it as an administrator. problem solved
