### ISSUE TITLE
Crash when play recording file with 96000 Hz audio sampling frequency

### ISSUE THREAD

**Issue by viachaslavic** [libretro/RetroArch#16674]
### Description

RetroArch crash when I try to run game recordings in High Quality with 96kHz sound sample rate.

### Expected behavior

Normal playback

### Actual behavior

Segmentation fault.

[backtrace](https://github.com/user-attachments/files/15779200/gdb.txt)

### Steps to reproduce the bug

1. Create recorded mkv (Recording Quality → High) file with 96kHz sample rate on `Mesen` core (most likely, the frequency is set in the core settings, in Mesen the default is 96k)
2. Try playing this file from the video playlist

### Bisect Results

Don't bisecting. but with version 1.17.0 it is the same

### Version/Commit

- RetroArch 1.19.1 (Git 65e8871250)

### Environment information

- OS: ArchLinux x86_64
- Compiler: gcc (GCC) 14.1.1 20240522
- Pipewire 1.0.7

**Comment by gouchi** [comment]
Strange, I can't reproduce the issue using latest [6e057ab](https://github.com/libretro/RetroArch/commit/6e057abc8e31e50ad84d24925f4616faa76ad4d2).

I got the error [File could not be loaded from playlist](https://github.com/libretro/RetroArch/blob/6e057abc8e31e50ad84d24925f4616faa76ad4d2/menu/cbs/menu_cbs_ok.c#L2851) no crash.

Thank you.

**Comment by viachaslavic** [comment]
@gouchi I'm sorry, you're absolutely right! I updated the description. Probably the issue is related to the sound sample rate

**Comment by gouchi** [comment]
The default sample rate I have for Mesen is 48kHz  from which I can't reproduce the issue.

But indeed, if I try to play a recording with audio using 96Khz sample rate,  it crashes

```
#0  0x00007ffff44a8e44 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff4450a30 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff44384c3 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff4439354 in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff4536259 in __fortify_fail () from /usr/lib/libc.so.6
#5  0x00007ffff4537514 in __stack_chk_fail () from /usr/lib/libc.so.6
#6  0x0000555555fa2919 in libretro_ffmpeg_retro_run () at cores/libretro-ffmpeg/ffmpeg_core.c:980
#7  0x0000000000000000 in ?? ()
```
