### ISSUE TITLE
building with mbedtls v3 fails

### ISSUE THREAD

**Issue by markand** [libretro/RetroArch#16672]
## Description

Currently, RetroArch requires the old mbedtls v2 to build correctly, at [Alpine](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/67243) we are in the process of removing this old version in favor of mbedtls v3. It seems that a few C declarations conflict with:

### Actual behavior

```
In file included from libretro-common/net/net_socket_ssl_bear.c:23:
./libretro-common/include/net/net_socket_ssl.h:38:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
   38 | ssize_t ssl_socket_send_all_nonblocking(void *state_data, const void *data_, size_t size, bool no_signal);
      | ^~~~~~~
      | size_t
./libretro-common/include/net/net_socket_ssl.h:42:1: error: unknown type name 'ssize_t'; did you mean 'size_t'?
   42 | ssize_t ssl_socket_receive_all_nonblocking(void *state_data, bool *error, void *data_, size_t size);
      | ^~~~~~~
      | size_t
libretro-common/net/net_socket_ssl_bear.c: In function 'process_inner':
libretro-common/net/net_socket_ssl_bear.c:191:18: warning: operand of '?:' changes signedness from 'int' to 'size_t' {aka 'long unsigned int'} due to unsignedness of other operand [-Wsign-compare]
  191 |                : -1);
      |                  ^~
libretro-common/net/net_socket_ssl_bear.c: At top level:
libretro-common/net/net_socket_ssl_bear.c:254:9: error: conflicting types for 'ssl_socket_receive_all_nonblocking'; have 'ssize_t(void *, _Bool *, void *, size_t)' {aka 'long int(void *, _Bool *, void *, long unsigned int)'}
  254 | ssize_t ssl_socket_receive_all_nonblocking(void *state_data,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./libretro-common/include/net/net_socket_ssl.h:42:9: note: previous declaration of 'ssl_socket_receive_all_nonblocking' with type 'int(void *, _Bool *, void *, size_t)' {aka 'int(void *, _Bool *, void *, long unsigned int)'}
   42 | ssize_t ssl_socket_receive_all_nonblocking(void *state_data, bool *error, void *data_, size_t size);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libretro-common/net/net_socket_ssl_bear.c:339:9: error: conflicting types for 'ssl_socket_send_all_nonblocking'; have 'ssize_t(void *, const void *, size_t,  _Bool)' {aka 'long int(void *, const void *, long unsigned int,  _Bool)'}
  339 | ssize_t ssl_socket_send_all_nonblocking(void *state_data,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./libretro-common/include/net/net_socket_ssl.h:38:9: note: previous declaration of 'ssl_socket_send_all_nonblocking' with type 'int(void *, const void *, size_t,  _Bool)' {aka 'int(void *, const void *, long unsigned int,  _Bool)'}
   38 | ssize_t ssl_socket_send_all_nonblocking(void *state_data, const void *data_, size_t size, bool no_signal);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:207: obj-unix/release/./libretro-common/net/net_socket_ssl_bear.o] Error 1
```

### Steps to reproduce the bug

1. Install mbedtls v3
2. Build with --enable-systemmbedtls

### Version/Commit

- RetroArch: 1.19.1

### Environment information

- OS: Alpine Linux 3.20
- Compiler: gcc 13

If there is no pending work on that matter and that it's okay to migrate to mbedtls v3 I can try to submit a PR with required changes. But what are your thoughts on mbedtls v2? I mean would RetroArch require building with both versions?

**Comment by hizzlekizzle** [comment]
We would definitely appreciate PRs to get it working, but yeah, we'd need to maintain backward compatibility since v2 will probably hang around for quite some time.

**Comment by keithbowes** [comment]
> We would definitely appreciate PRs to get it working, but yeah, we'd need to maintain backward compatibility since v2 will probably hang around for quite some time.

Version 2 is going EOL at the end of the year, so I don't know why you'd need backwards-compatibility. The bundled version is of course ancient and I can only imagine the security problems it has. Though, I don't know what the reporter did to get it that far; when I tried to compile against mbedtls 3, the configure script told me that it couldn't find mbedtls/config.h and would disable mbedtls support. Since the errors are in libretro-common/net/net_socket_ssl_bear.c, I'm guessing it's using bearssl instead of mbedtls and you'd have to pass --disable-builtinbearssl (which my build script does) too. I'd guess that even though it can't find mbedtls/config.h, it still defines HAVE_SYSTEMMBEDTLS and thus creates conflicts with bearssl.
