### ISSUE TITLE
(Win32) Image is skewed after RETRO_ENVIRONMENT_SET_GEOMETRY

### ISSUE THREAD

**Issue by leiradel** [libretro/RetroArch#1667]
gw-libretro allows the user to zoom-in the LCD screen by pressing Select. The screen is zoomed in/out with calls to the environment callback passing `RETRO_ENVIRONMENT_SET_GEOMETRY`.

On Windows, some games appear skewed when zoomed-in, but the same games on a Samsung Galaxy S3 appear just fine.

![ra-win32](https://cloud.githubusercontent.com/assets/357536/7442780/3631a034-f0f6-11e4-94aa-dcc5cec83528.png)
![ra-android](https://cloud.githubusercontent.com/assets/357536/7442781/36332eea-f0f6-11e4-8f28-ceb00da4ccfb.png)

**Comment by fr500** [comment]
@leiradel is this still happening?

**Comment by leiradel** [comment]
Yes, I've just downloaded 1.2.2 and the problem is still there.

**Comment by fr500** [comment]
but what about a recent nightly?

**Comment by leiradel** [comment]
I tried with 2015-10-10_RetroArch.7z and the problem is still there. The archive didn't have the DLLs in it so I used the ones from RetroArch_1.2.2.7z.

**Comment by fr500** [comment]
@leiradel can you try yet again, this is quite old now and I can't repro
