### ISSUE TITLE
N64 buttons Z + C are not registering (iOS)

### ISSUE THREAD

**Issue by zero2029** [libretro/RetroArch#1672]
Now that the audio is essentially fixed for the n64 core you can pretty much play n64 roms without a problem. However, there is one little problem. Pressing the Z button combined with any of the C yellow buttons does nothing..... Nothing happens when pressed at the same time. Some games require you to press the Z button in combination with the C buttons.... Like Donkey Kong 64 for example. If anyone knows a solution or how to fix it.... Please let me know. Hopefully it gets fixed in the very near future. Other than that the n64 core is looking great.

**Comment by fr500** [comment]
please reopen this on the correct repository (mupen64plus libretro)
