### ISSUE TITLE
Save files should be per core

### ISSUE THREAD

**Issue by robcross** [libretro/RetroArch#1673]
I just had a very frustrating experience. I've put a few hours into Ys III and coming back to it, I've accidentally loaded the rom with the 3DO core. Because of this, my save file got overwritten.

Why aren't save files saved with a per core suffix or in a core specific folder?

**Comment by fr500** [comment]
it's an edge case, it's just the way it is, and changing paths after
loading the core is not trivial anyway

**Comment by chris062689** [comment]
To mitigate this, in the future, you could use per-core Savefile paths.
Though an issue is currently open on that. https://github.com/libretro/RetroArch/issues/1541

**Comment by robcross** [comment]
Not sure how this is an edge case. What if I have a game (say, a port) with the same name on two systems? Every time I switch between them it will overwrite the save file.

**Comment by fr500** [comment]
It's an edge case because in all this time we've only seen two or three reports of this. 
If there were hundreds of users then yeah it would be urgent.

I already said it's not trivial to reinit paths when reloading the core, tried many different approaches for that and none worked so it will have to wait for someone more knowledgeable than me to change it or be made optional.

**Comment by chris062689** [comment]
There really isn't a good solution I've been able to think of. 
There are multiple cores per system, so often, it would cause problems if a user loaded a different core to play a specific game.

**Comment by fr500** [comment]
Overrides and per-core options already provide a lot of flexibility, I guess it will be possible to do this as requested eventually.

**Comment by chris062689** [comment]
Isn't the RetroArch default to save them in <Content Directory>, solving this issue if the user kept the default settings?

**Comment by fr500** [comment]
yes by default it will save in "content directory"

**Comment by robcross** [comment]
I don't really want my save files to be littered in my rom directories. It looks like #1541 needs to be fixed before that can work. It would just be nice to have a config flag that will ensure that a save file is tied to a certain core to avoid conflicts :(

**Comment by fr500** [comment]
I sent a PR here https://github.com/libretro/RetroArch/pull/1675
please test and report back, from what I can see it's working fine with and without overrides

**Comment by fr500** [comment]
btw this approach is rather clumsy and works only with overrides.  If it works I'll ask it to be merged and then work on something automated that can be enabled from global config.  Something akin to remap auto loading.

**Comment by chris062689** [comment]
In yes of configuration, in the paths menu below savefiles and save states, have a boolean yes / no option "Include core in savefile / save state path"

**Comment by fr500** [comment]
What??

**Comment by robcross** [comment]
I'm hoping he meant he is in favor of having a simple option :)

It's a pain in the butt compiling all the core names and creating an override for every single one...

I need to got some work done, then I'll try and do some testing later tonight.

**Comment by robcross** [comment]
Oh, I just thought of a good solution to that problem. What if upon core discovery (when it reads an info file), retroarch could create a blank $CONFIGDIR/$CORE/$CORE.cfg? That would make it trivial to loop over the files in a bash loop or something.

**Comment by fr500** [comment]
No again...  We can't depend on info files for functionality and the
library name is retrieved from the core itself.  Anyway the option is even
easier to implement than this I just need to know if there are any quirks
with this implementation

**Comment by fr500** [comment]
ok, I updated the PR, now it's no longer needed to use overrides to use this functionality, just enable the toggle in general settings.

One condition is that the subfolder must exist beforehand, I'll fix that later.
Please test with as many cores as possible (weird cores like dosbox, mame, ppsspp specially), let me know.
