### ISSUE TITLE
is posible add cheat.db support like other emulators?

### ISSUE THREAD

**Issue by eddiebrook** [libretro/RetroArch#1674]
is possible add support for cheat.db?

i tried to covert codes for desmume but not working.

desmume code 

Max Rupies After Getting Some
920a878c 000011b0
020a878c e1c0c1b0
d2000000 00000000

i try to convert to libretro parameter: but not work.

cheat0_desc = " Max Rupies"
cheat0_code = "920a878c-000011b0+020a878c-e1c0c1b0+d2000000-00000000"
cheat0_enable = false

**Comment by twinaphex** [comment]
Most likely cheat codes are not yet hooked up for the Desmume libretro core.

**Comment by fr500** [comment]
Please open this in the desmume repo

**Comment by eddiebrook** [comment]
sure.thx
