### ISSUE TITLE
Unable to read external files

### ISSUE THREAD

**Issue by Gl17chV** [libretro/RetroArch#16746]
## Description

Only the directories `data/user/0/com.retroarch` and `Android/data/com.retroarch` are empty; even the internal storage is devoid of content. The only way is to save files in `Android/data/com.retroarch` which I won't do because most of my ROMs are on external storage. Additionally, if I were to uninstall RetroArch, the ROMs would be deleted as well.

### Steps to reproduce the bug

1. Load Content
2. Any folder off: `Android/data/com.retroarch` `data/user/0/com.retroarch`

### Bisect Results

Since this #16393 

### Version/Commit

RetroArch: 1.19.1_GIT 1719824211

### Environment information

OS: Android 8

**Comment by hizzlekizzle** [comment]
Yes, bear with us for a bit. We're having to do a big overhaul on permissions and access to try and get back on the Play Store. We may have to revert that commit, or we may be able to restore some permissions through Storage Provider access, etc.
