### ISSUE TITLE
Retroarch crashes when I go to the "Explore" category.

### ISSUE THREAD

**Issue by Deadfalt999** [libretro/RetroArch#16757]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch crashes when I go to the "Explore" category.

### Expected behavior

For Retroarch not to crash

### Actual behavior

When I open Retroarch (Win64) and go to the explore section on the UI, "Initializing List" appear instead of the other options and the app crashes and closes down.

### Steps to reproduce the bug

1. Scan a folder with roms in it
2. Go to the "Explore" section
3. Retroach crashes

### Bisect Results

After I scanned a folder for the roms inside of it.

### Version/Commit

- RetroArch: 1.19.1 / 57c7906

### Environment information

- OS: Windows 10 22H2 build 19045.4598

**Comment by jbreitweiser** [comment]
Bug confirmed.  Error from code committed to libretro-common/include/array/rhmap.h on commit "Try to avoid strdup to avoid portability issues".  Committed by @LibretroAdmin

**Comment by zoltanvb** [comment]
Thank you for reporting. Tested now, I believe it is fixed by https://github.com/libretro/RetroArch/commit/7c6054573ea3ccb6040c041ec06ce74e89d80b10.

**Comment by Deadfalt999** [comment]
Thanks for confirming the issue. How would I fix this on my end now ? Simply download Retroarch and install again ?

**Comment by zoltanvb** [comment]
Yes, that should work, download a recent nightly (built on July 7 or later).

**Comment by Deadfalt999** [comment]
Yup that fixed it, thank you very much for everything ! I'll close the issue.
