### ISSUE TITLE
(GLUI)(Win-x86_64) Font size is ignored

### ISSUE THREAD

**Issue by bugreport1** [libretro/RetroArch#1676]
Since the 2015-04-22 [nightly build](http://buildbot.libretro.com/nightly/win-x86_64/2015-04-22_RetroArch.7z) the font size setting for GLUI is being ignored and text is displayed at an illegibly small size.
 
2015-04-22 (remains the same as of 2015-05-06)
![2015-04-22](http://i.imgur.com/VKgltGM.png)
 
2015-04-21:
![2015-04-21](http://i.imgur.com/gWYfnud.png)
 
OS is Windows 8.1 if it matters at all.

**Comment by fr500** [comment]
try the dpi override setting it's working alright here

**Comment by Kivutar** [comment]
Yes, this is the intended behaviour for now. Since we use GLUI on touch screens, the font size if driven by the dpi. Some platforms does not have dpi detection yet, for those, override the dpi.

**Comment by bugreport1** [comment]
Got it, thanks.
 
If I set the DPI to '192' I get something similar to the old font size, which worked well when displayed full-screen on my TV.
There is a lot of padding around the menu items now, which means that requires a lot more scrolling off-screen to find options, but I guess that was done to accommodate touchscreen users.
 
That said, the font size still seems to be getting ignored, rather than scaled with DPI.
A point is 1/72 of an inch, so 72pt text should be exactly one inch tall when DPI is set correctly.
As my display for RetroArch is a 46″ 1080p television, its DPI is 48.
 
When I set the font size to 72pt and DPI to 48 I am still getting very small text, rather than text which is 1″ tall.

**Comment by twinaphex** [comment]
bugreport1 - Go to System Information and tell me what the DPI value there is.

**Comment by bugreport1** [comment]
It is listed as 30 though I am currently overriding that with 192 to get a reasonable size of text on my TV. (even though the TV is physically 48 DPI)
 
But DPI controls should not replace the font size options.
Fonts are supposed to have a physical size. 72 points = 1 inch.
 
They are not some arbitrary value for sizing text.
72 *pixels*, rather than *points* could be any size, depending on the size and resolution of the screen for example.
 
Font size appears to have a fixed value in the latest build (the setting is ignored) with DPI being used as the only control to scale the font.
72pt text should appear 1 inch tall on any display of any pixel density, as long as the DPI value is set correctly for that display.
 
You shouldn't have to play around with the numbers until you find a value which is a reasonable size.

**Comment by twinaphex** [comment]
show me a screenshot of System Information with the values for the metrics (width/height/dpi).

**Comment by Kivutar** [comment]
This point unit is something of typography, and have use in software only when you have to print something on paper. (Correct me if I'm wrong)

30 and 48 are very low values, means the pixels are very big physicaly. It can be the case of a TV screen though.

Don't forget there is something we can never mesure: the distance between your screen and your eyes. It varies a lot between a TV and a phone, or a cinema screen.

**Comment by bugreport1** [comment]
> show me a screenshot of System Information with the values for the metrics (width/height/dpi).

Certainly:
![System Information](http://abload.de/img/sysinfoxyqbo.png)
 
I have no idea why it thinks my display is "1600mm x 900mm" or "30 DPI". That would be roughly a 72" 1080p display.
Note: this is with the override of "192" DPI active.
 
It's actually a 3DTV that I have connected, so it should be reporting its physical size to the PC - though I am not too concerned about detection for things like that.
 
> This point unit is something of typography, and have use in software only when you have to print something on paper. (Correct me if I'm wrong)

It is useful whenever you want something to have a physical size, that does not have to be print.
If you are adding DPI scaling to the text, font values should be representing a physical size.
 
As I've tried to explain, 72pt should be one inch in height no matter what you are viewing it on.
It should be 1" tall on a phone, 1" tall on a monitor, and 1" tall on a 200" projection screen once you input the correct DPI value for that display.
 
Now of course maybe you don't care about that, but it's backwards that I have to set the DPI value very large, in order to get text of a reasonable size to be displayed on the TV, since the physical resolution of that is only 48 DPI.
 
The DPI setting currently seems to be used as a "menu scale" option, rather than actually correcting for DPI.

**Comment by Kivutar** [comment]
The font values in RetroArch are in pixel unit, because that's what the underlaying font drivers (freetype, corefonts, etc) are all expecting.

This font size setting has effect on the OSD messages. It has no effect on any menu (RGUI, GLUI, XMB) and it's a choice. I don't want to let the user change the font size of the menu. The font size in the menu should fit the size of the rows. And the size of the rows should be the size of a human fingertip on a touchscreen.

> The DPI setting currently seems to be used as a "menu scale" option, rather than actually correcting for DPI.

The DPI settings override the DPI value. This value is then used as a scale factor for the row height (and thus the font height). I don't see any difference between correcting a DPI and scalling the menu, since we use the DPI as a menu scale, as it should be.

If the real DPI of your TV is 48, then try to set the DPI override to 48, and touch your screen. You will see that the row height is the size of your fingertip : 1/3 inch, or 0,7cm. This is the behaviour we want for touch screens.

The problem with the current behaviour, is that your TV is not a smartphone : it is very far from your eyes, and you don't need to touch it. So we need to have two behaviour : one for tablets/smartphones, one for TVs.

This is why I wanted some time ago to have a "touch menu driver" separated from GLUI. But there are other ways to do. We can try to detect if your screen is a touchscreen, we can check if touch is enabled and read the dpi only if that setting is true. We can also let the user declare what time of hardware is in use, a TV, a phone, something else.

**Comment by bugreport1** [comment]
Thank you for the explanation, I understand what's happening now.
You are correct that when I set my display to 48 DPI, each row height is 1/3 of an inch.
 
What I still don't understand is that you are apparently specifying font sizes in "pixels" yet scaling them to have a fixed physical size. Pixels are not supposed to have a physical size, but points do.
 
1/3 of an inch is exactly 24 points.
The number of pixels used to draw 24pt text may vary depending on the size and resolution of the display, but 24pt text should always have a height of 1/3 of an inch.

Text defined as "24 pixels tall" would be different on every screen you view it on.
 
But that distinction doesn't really matter much, since fonts are just specified with a number and are neither "24px" *or* "24pt"
 
 
I don't really like that the menu size is now separate from the OSD message size.
Previously (2015-04-21) the font size adjusted both, keeping them of equal size.
 
If you were to define the row height in points as well as the text (technically it's the row height which is 1/3 of an inch, not the text) you could scale all three by adjusting a single "font size" value which would keep the UI looking more consistent.
 
 
But it's mainly the logic for adjusting the font size when you don't like the default "1/3 of an inch" that I find confusing.
DPI is a fixed specification for a display. There are physically that many dots per inch and you can't change it.
So there is really only one correct value for DPI with any display.
 
Using the wrong DPI value to change the text size doesn't feel like the right approach.
Changing the "font size" to adjust the size of the text (and scaling the row height appropriately) seems like a more obvious fit?
 
For example, to make the text 3x larger, increasing it from 24pt at 1/3 of an inch (however that is currently defined behind the scenes) to 72pt text with a height of 1 inch, I have to tell it that my display is "144 DPI".
Increasing the font size from 24 to 72 seems to make a lot more sense.
 
 
Please don't misunderstand though, having this DPI scaling is great and I appreciate the work being done.
From a users perspective though, adjusting the DPI value to change the text size is confusing - especially when there is also a "font size" option.

**Comment by Kivutar** [comment]
OK I understand your point: setting font size is more natural than overriding a dpi.

If we let the font size be the source of all scaling in GLUI, then what about a menu based on icons like here <http://www.lakka.tv/articles/2014/07/30/graphical-contributions/> ? It would feel less natural to have to adjust font size to scale those icons, right? So we will end up with 3 behaviours:
 * font size driven (what you want for glui)
 * dpi driven (the current behaviour, needed for iOS and Android)
 * proportionnal to screen height (our fallback when dpi is not detected)

I would like to avoid to have so much behaviours for doing just one thing: scalling.

Some platforms, like DRM/KMS cannot get the DPI of the screen. And some platforms like X11 provide a wrong DPI (always return 96 unless you set it manually). Also, some screens will report the wrong DPI like your screen. For these 3 reasons, the DPI override setting is needed anyway.

From the touch UI point of view, it is natural to adapt the hitbox to the dpi to ensure that the hitbox is big enough. Then, you don't want to have big fonts in a small button, or very small fonts in a big button, so adapting the font size to the button size will make it look harmonious.

Let's try to find a solution that
 * works for touch phones, tablets
 * works for big TVs
 * works for platforms without any way to detect dpi
 * works for platforms reporting a wrong dpi
 * is overridable anyway to fit user taste
 * has a limited number of settings
 * has intuitive settings
 * is easy to implement
 * could apply to other menu drivers

Here is my proposal:
 * One setting menu_scale_mode, with two values: *proportional to screen size* or *dpi driven*
 * One dpi override setting
 * No font size setting for the menu

On touch devices, we choose dpi driven. On all other platforms, the default will be proportional to screen size.

What do you think about it? Can you come with a better proposal?

**Comment by bugreport1** [comment]
I'm certainly not bothered about whether there is specifically a "font size" control.
I actually think that "font size" complicates things when you also have DPI specified for the display.
 
It sounds like that control would be better replaced with a "menu size" or "menu scale" control which scales everything together.
I had originally thought "Why not scale everything proportionally to the font size?" but after thinking about it some more, no-one actually needs to know what the font size is.
People just want the menus to be clear and easy to use.
 
I like your proposal, though I wonder if it could be further simplified from an end-user's perspective:
 
* DPI Scaling:     On/Off
* DPI:            0 (auto)
* Menu Scale:     100%
 
The only other thing is that some users may want a separate OSD Scale option so that they could display the framerate while playing a game, but keep that at a smaller size than the rest of the menus to avoid covering it up.

I would also change that from being a "font size" option to a scale, so that you could have the default be "100%" which would always match the menu size and scale with DPI.
 
Having DPI Scaling on or off by default based on the platform seems like a good idea.
 
I don't know that DPI scaling should override the menu scale though.
What I would suggest is that enabling DPI scaling and having a menu scale of 100% would always result in items that have a height of 1/3 of an inch.

But while that may work well as a good minimum size for a phone, some people may want to scale that up on a larger device such as a tablet, or because they have difficulty reading it.
 
And to simplify how that works on your end, perhaps when you switch DPI scaling off, what that actually means is that it will use a fixed value of "96" for DPI, rather than having separate "modes" for scaling the menus. (since 96 is the default for every desktop OS)
 
Now personally I still find that 96 is a bit small for a television, but it seems like a reasonable default since it is still legible, and as a user all that I would have to do is increase menu scale from 100% to 150% or 200% without having to think about DPI values or font sizes.

**Comment by fr500** [comment]
Feel free to reopen this if it
