### ISSUE TITLE
D3D11 GPU screenshots are cropped in certain aspect ratios

### ISSUE THREAD

**Issue by miguedevel** [libretro/RetroArch#16776]
I tried a fresh RetroArch build with this but my d3d11 shots are pushed over to the right for some reason.

vulkan:
![Mega Man X vulkan](https://github.com/user-attachments/assets/5f41424c-5315-4b94-a48b-a781b03e50c6)
![Sonic Adventure vulkan](https://github.com/user-attachments/assets/7b3fedb4-fac2-4f07-8a8a-ce13783168b6)

d3d11:
![Mega Man X d3d11](https://github.com/user-attachments/assets/a622fab2-68e9-493e-bd89-9a70fec66318)
![Sonic Adventure d3d11](https://github.com/user-attachments/assets/60d708a2-c2a3-423d-b49c-8369b6edc0af)

Using a GTX 4080 on Windows 11. Here's my retroarch.cfg: https://pastebin.com/dZ7yRSGY

I tried defaulting some of the video settings like shader enable, the window position/size, aspect ratio and crop overscan. But the screenshots still came out pushed to the right under d3d11.

_Originally posted by @Awakened0 in https://github.com/libretro/RetroArch/issues/16760#issuecomment-2226403206_

**Comment by Awakened0** [comment]
Tested with the latest commits and my d3d11 GPU screenshots look correct now, just like with vulkan. Both from fullscreen and windowed.
