### ISSUE TITLE
Compilation fails due to extra path in includes

### ISSUE THREAD

**Issue by otonoton** [libretro/RetroArch#16785]
The lines here:

https://github.com/libretro/RetroArch/blob/b5024348390890b04af406503219c073ed28eeff/save.c#L31-L45

Cause errors during compilation if the user happens to have an unrelated file with the same name as one of those files in the parent directory.

Seems to be a regression caused by ea87495 when the code was moved up out of the `tasks` folder.

**Comment by zoltanvb** [comment]
Good catch, thank you for taking the time to report and bisect. Just for reference, the problem is hidden during usual compilation since ../???.h will be valid at least from deps/:

```
ROOT_DIR          := .
DEPS_DIR          := $(ROOT_DIR)/deps
LIBRETRO_COMM_DIR := $(ROOT_DIR)/libretro-common
[...]
INCLUDE_DIRS += -I$(LIBRETRO_COMM_DIR)/include -I$(DEPS_DIR)
```
