### ISSUE TITLE
winmm_midi driver: Issue initializing instruments (SC-55, MT-32, GM)

### ISSUE THREAD

**Issue by negativeExponent** [libretro/RetroArch#16790]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

long story short, im doing the testing trying to implement MIDI support for PX68K and  the linux midi driver has been working fine, but the windows midi driver cannot properly set instruments, and causes notes to be held longer than it should. This has been reported years ago.

### Expected behavior

play midi music!

### Actual behavior

just to repeat, the midi driver works in linux for the core's implementation. but the windows driver (winmm_midi.c) does not. 

In general midi/ SC-55 mode, there is noticeable lack of pitch bends, so notes does sound right. other than that, the notes are being held longer and in returns overlaps with all other notes being played.

when using with MT-32, that has a different issue since instruments are not getting initialized at all.

a quick workaround for this issue, was to manipulate winmm_midi_write_long_event() in winmm_midi.c to send long_midi_msg as single byte messages. this work as workaround but ofcourse this is incorrect as per implementation, as the buffer for sysex are suppose to be sent in blocks. my limited midi understanding limits me in finding actual solution, but just point out something is wrong, and probably is just within the midi driver implementation on windows. 

### Steps to reproduce the bug

Just setup your midi device(GM/SC-55/MT-32) using the libretro api. for this test Akumajou Dracula is a good example.  If used with MT-32, the notes should be clearly wrong from the start. In SC-55/GM mode, the loading music after the mt-32/cm55 selection screen should have a note bending part in the end of it but its not there. other than that if you cancel anything that is playing, some notes will linger and wont release. or just load the game,  You can also goto music mode and play LOAD BGM if you missed the part in the intro.
(btw, a PR in px68k has to be merged first or midi will remain pianos all the time regardless of midi types)

### Bisect Results

happens since commit

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit] latest master

### Environment information

- OS: [The operating system you're running] Windows 11
- Compiler: [In case you are running local builds] msys2 14.1.0

Related issue and some relevant discussion:
https://github.com/libretro/px68k-libretro/issues/164

just for comparison, i have crudely implemented midi handling directly in px68k using winmm (midiOutOpen, midiOutLongMsg, midiOutShortMsg etc) and this works fine with Windows GS Synth, MT-32, or SC-55 synths (munt and nuke). but like the libretro api to work and use it instead:
here is the repo if anyone wants to check or confirm:
https://github.com/negativeExponent/px68k-libretro/tree/midi_direct_using_winmm

**Comment by negativeExponent** [comment]
@LibretroAdmin is there someone we can get hold about this? im sure with someone who knows midi and winmm would surely see the issue in less time than i did.

**Comment by zoltanvb** [comment]
Do you happen to have a log where RA was compiled with -DDEBUG? There are a couple of extra logs hidden behind that compiler switch.
It seems that sysex reception is not implemented in the winmm driver, that may have effect on MT-32 if patch setup includes sysex messages from the device, not sure. In any case, General Midi should work without sysex and bends are also standard.

**Comment by negativeExponent** [comment]
Thanks for the reply. Windows general is also affected by issue, similar case when using nuke ac-55 synth where notes are held long and not released and no bends.

Sadly my PC is too slow to have all the debug logs shown. RA freeze just after a few lines of the midi messages.

As far as seeing if the msg send from the core, it appears to be correctly receive. These is a log in that issue page in px68k for the receive midi msg.

**Comment by zoltanvb** [comment]
The messages look OK at first glance (0xE_ for bends, 0xF0 for sysex). There are no "note off" messages, though, so the lingering notes may be unrelated.
Logs are from the core side, right? It may be enough to remove all #ifdef #endif declarations from winmm_midi.c, should not  produce considerably more log writes than in the attached log.

**Comment by negativeExponent** [comment]
heres the log with DEBUG defined in winmm_midi.c and the midi section in retroarch.c

[retroarch_midi_debug.zip](https://github.com/user-attachments/files/16325708/retroarch_midi_debug.zip)

**Comment by zoltanvb** [comment]
Oh wow. Sysex produces error 11, which is MMSYSERR_INVALPARAM, invalid parameter, probably there is something wrong in the buffer setup. But the bend looks weird, this value is not in any reference:
`[ERROR] [MIDI]: midiStreamOut failed with error 68.`

**Comment by zoltanvb** [comment]
Hm, it can happen apparently:
https://stackoverflow.com/questions/2107831/problem-using-midi-streams-in-windows

**Comment by negativeExponent** [comment]
according to midiOutGetErrorText, error codes means:

```
[ERROR] [MIDI]: midiStreamOut failed with error 11.
[ERROR] midiStreamOut error: An invalid parameter was passed to a system function.
```

```
[ERROR] [MIDI]: midiStreamOut failed with error 68.
[ERROR] midiStreamOut error: The current MIDI Mapper setup refers to a MIDI device that is not installed on the system.  Use MIDI Mapper to edit the setup.
```

**Comment by negativeExponent** [comment]
dwParam is practically not already included in short message. but why dwParam[2] for long msg?

```
   buf->data[i++] = delta_time;
   buf->data[i++] = 0;
   buf->data[i++] = MEVT_F_LONG | MEVT_LONGMSG << 24 | data_size;

   memcpy(&buf->data[i], data, data_size);
   buf->header.dwBytesRecorded += sizeof(DWORD) * 3 + data_size;
```

**Comment by negativeExponent** [comment]
i could have jumbled things abit trying to get logs here. but something seems incorrect happening in winmm_midi_write_long_event.

using RARCH_BUFFER_LOG to get output of the buffer, the input data is this:
```
[INFO] INPUT dwDeltaTime = 0 data_size: 19
[INFO] == 19-byte buffer ==================
[INFO] f041101612100004  0404040404040400
[INFO] 044cf7ffffffffff  ffffffffffffffff
[INFO] ==================================
```

but what is getting written to main stream buffer, including MIDIEVENT* is this:(ignore the deltatime value, i intentionally set it 8 just for visuality)
```
[INFO] OUTPUT dwDeltaTime = 0 data_size: 19
[INFO] == 31-byte buffer ==================
[INFO] 0800000000000000  08000080f07f7f04
[INFO] 017f7ff700000000  00000000b17900ff
[INFO] ==================================
```

the data after the first 0xF0 is totally incorrect.

heres another one with 19 bytes data size:
```
[INFO] INPUT dwDeltaTime = 0 data_size: 19
[INFO] == 19-byte buffer ==================
[INFO] f041101612100004  0404040404040400
[INFO] 044cf7ffffffffff  ffffffffffffffff
[INFO] ==================================
```

heres what was written:
```
[INFO] OUTPUT dwDeltaTime = 0 data_size: 19
[INFO] == 31-byte buffer ==================
[INFO] 0000000000000000  b179000000000000
[INFO] 00000000b2790000  00000000000000ff
[INFO] ==================================
```
maybe a delay in how RARCH_BUFFER_LOG works but where did it got b179 just right after the log above it?

same with some 266 data size:
```
[INFO] INPUT dwDeltaTime = 0 data_size: 266
[INFO] == 266-byte buffer ==================
[INFO] f041101642080000  506f776572204869
[INFO] 742008050f00244b  1001002f00070000
[INFO] 0000000000323232  3232000000000003
[INFO] 0007000000000000  0000000000000064
[INFO] 461b0c6702020001  2e2d1f4c645d3200
[INFO] 24241001002f6407  0000000c0201003d
[INFO] 363232320000013a  000a1e093e000000
[INFO] 082f232d291e2a22  0564471b0c670202
[INFO] 0000245f22556461  4b0118321001002f
[INFO] 0007000000000000  0032323232320000
[INFO] 0000000300070000  0000000000000000
[INFO] 00000064461b0c67  02020000332d194c
[INFO] 645e320030481001  002f000700000000
[INFO] 0000003232323232  0000000000030007
[INFO] 0000000000000000  000000000064481b
[INFO] 0c6702020000332f  644c645e4c490000
[INFO] 0000000000000000  2af7ffffffffffff
[INFO] ==================================
```

and its output written to buffer is:
```
[INFO] OUTPUT dwDeltaTime = 0 data_size: 266
[INFO] == 278-byte buffer ==================
[INFO] 0800000000000000  0d000080f0410016
[INFO] 4008000001000077  0800000000000000
[INFO] 0a010080f0411016  42080000506f7765
[INFO] 7220486974200805  0f00244b1001002f
[INFO] 0007000000000000  0032323232320000
[INFO] 0000000300070000  0000000000000000
[INFO] 00000064461b0c67  020200012e2d1f4c
[INFO] 645d320024241001  002f64070000000c
[INFO] 0201003d36323232  0000013a000a1e09
[INFO] 3e000000082f232d  291e2a220564471b
[INFO] 0c6702020000245f  225564614b011832
[INFO] 1001002f00070000  0000000000323232
[INFO] 3232000000000003  0007000000000000
[INFO] 0000000000000064  461b0c6702020000
[INFO] 332d194c645e3200  30481001002f0007
[INFO] 0000000000000032  3232323200000000
[INFO] 0003000700000000  0000000000000000
[INFO] 0064481b0c67ffff  ffffffffffffffff
[INFO] ==================================
```

the next byte value written after f0410016 is suppose to be 4208, yet its 4008 in the main buffer.

full log attached:
[retroarch_log.zip](https://github.com/user-attachments/files/16327638/retroarch_log.zip)

**Comment by negativeExponent** [comment]
@zoltanvb  i think i got the issue fix. turns out buffer size in sysex has to be aligned. please check
