### ISSUE TITLE
CRT-Royale shader broken in Vulkan as of the 7/22/2024 nightly

### ISSUE THREAD

**Issue by boomercore** [libretro/RetroArch#16808]
## Description

While rendering with Vulkan, loading any Royale slangp preset or my modified ones, results in either a black or blurry screen.  D3D12  still works fine.

### Expected behavior

Royale loads fine in Vulkan as it does in a July 10th build I rolled back to.  Not 100% sure on when it broke.

### Steps to reproduce the bug

1. Selected the Vulkan display driver
2. All shaders seem to work except for Royale and any presets that rely on it, even when I update the slangp shaders from the repo.

### Bisect Results

Happened upon updating to the latest nightly as of 7/23/2024, rolling back to the 10th fixes it

### Version/Commit

RetroArch: 1.19.1 Git Version 2c31de5 Build Date  Jul 23 2024

### Environment information

Win11 / 4070 / Zen 3 platform

To further confirm the issue I unzipped the newest build into its own folder with stock settings, downloaded the Mesen core (happens regardless of core), flipped to the Vulkan driver, and downloaded the slang shaders.  This is what CRT-royale from slangp/crt/ gives me:

![Minus Infinity-240723-191648](https://github.com/user-attachments/assets/a84ec02c-c1de-477b-8106-c3582f19d797)

This is what the Jul 10 version gives me and is expected:

![Minus Infinity-240723-192118](https://github.com/user-attachments/assets/df109521-b2cb-4b0d-b3ea-64238b90b0c1)

**Comment by hizzlekizzle** [comment]
Can you try a few more nightlies to see if you can pinpoint when it broke for you? There were some vulkan-related commits 2 days ago, so if you could try the nightly from 3 days ago and then the one from 2 days ago, that should narrow it down significantly.

**Comment by boomercore** [comment]
Definitely as of 7/22 for me.  7/21 and earlier are fine.

**Comment by hizzlekizzle** [comment]
I put in a PR that fixes my segfaults, so perhaps it will help with this, as well.

**Comment by boomercore** [comment]
Fixed as of the latest update.  Thanks a lot.

**Comment by hizzlekizzle** [comment]
Np! Thanks for confirming :)
