### ISSUE TITLE
Wrong audio driver used by default

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#1681]
Hello,

When I try to use RetroArch on my Xubuntu installation, it says that init_audio failed and that it  will continues without sound.

I investigated and found out that RetroArch is actually trying to use OSS, which I don't have on my computer. If I force alsa by editing the source it works fine.

I think that the HAVE_OSS define may be broken or that the detection is not working well.

**Comment by sergiobenrocha2** [comment]
Default audio driver is Alsa, and if you are using package from PPA it's PulseAudio.

**Comment by natinusala** [comment]
Okay, so why do I have HAVE_ALSA on 1 and RetroArch still wants to use OSS ?

**Comment by sergiobenrocha2** [comment]
We need some more info, like xubuntu version, if you are using from PPA or compiled yourself... the commit number

**Comment by fr500** [comment]
is this still an issue? it's been some time it might have been fixed already, reopen if it hasn't
