### ISSUE TITLE
[IMPORTANT] linuxraw: Mapping variables are ineffective

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16856]
## Description

The `linuxraw` input driver currently only utilizes the following variables in the autoconfig files:
- `input_driver`
- `input_device`
- All the `_label` variables

### Expected Behavior

The `linuxraw` input driver should also utilize the mapping variables to allow for proper remapping of controller inputs.

### Actual Behavior

The `linuxraw` input driver does not use the mapping variables, rendering them ineffective for remapping purposes.

### Steps to Reproduce the Bug

1. Generate a `linuxraw` autoconfig file.
2. Test the controller in RetroArch by navigating to Main Menu -> Load Core -> Start Remote RetroPad.
3. Close RetroArch.
4. Modify the autoconfig file by copying a variable value to another button. For example, copy the `input_up_axis` variable value to `input_down_axis` for testing purposes.
5. Start RetroArch.
6. Test the controller again in Main Menu -> Load Core -> Start Remote RetroPad.
7. Observe that pressing the DPAD down button still registers as a down button, despite being remapped to DPAD up.
8. Close RetroArch.
9. Remove all mapping variables from the autoconfig file.
10. Start RetroArch.
11. Test the controller in Main Menu -> Load Core -> Start Remote RetroPad. All buttons are indicated as normal, confirming that the mapping variables are not being used.

### Version/Commit

- RetroArch: 1.19.1 Flatpak. 1.19.1 Appimage

### Environment Information

- OS: Ubuntu MATE 20.04, 23.04 (and likely all versions)

**Comment by davidhedlund** [comment]
@zoltanvb

**Comment by zoltanvb** [comment]
Cannot reproduce. I tested with an autoconfig profile, swapped input_up_axis and input_down axis values (also for left-right), and d-pad changed directions both in menu and in Remote Retropad.

**Comment by davidhedlund** [comment]
> Cannot reproduce. I tested with an autoconfig profile, swapped input_up_axis and input_down axis values (also for left-right), and d-pad changed directions both in menu and in Remote Retropad.

Thank you for reviewing the issue. I am no longer able to replicate it myself and am unsure of what caused it initially. However, I am pleased that the linuxraw driver is functioning correctly, especially since I have submitted five pull requests related to PlayStation and Nintendo Switch controllers.
