### ISSUE TITLE
Sony PlayStation Controllers: Device Index mislabeling in Flatpak

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16868]
### Description

In the Flatpak version of RetroArch, Sony PlayStation controllers are incorrectly labeled as "PS[X] Controller" ("Save Controller Profile" generates [controller name].cfg with content `input_device = [controller name]`) regardless of the Linux kernel version. This issue does not occur with the Appimage version.

For comparison, other controllers such as the Nintendo Switch Pro Controller are correctly identified and saved as "Nintendo Switch Pro Controller.cfg" across sdl2, udev, and linuxraw drivers.

#### Ubuntu MATE 23.04

On Ubuntu MATE 23.04 with Linux kernel 6.2.0, udev, and linuxraw correctly identifies the DualSense and DualShock 4 v2 controllers as "DualSense Wireless Controller" and "Wireless Controller" respectively.

So with sdl2:
* When a DualSense controller is connected and "Save Controller Profile" is clicked, it should save as "DualSense Wireless Controller.cfg".
* When a DualShock 4 v2 controller is connected and "Save Controller Profile" is clicked, it should save as "Wireless Controller.cfg".

#### Ubuntu MATE 22.04 and Ubuntu MATE 24.04

On Ubuntu MATE 22.04 with Linux kernel 5.19.0 and Ubuntu MATE 24.04 with Linux kernel 6.8.0, udev, and linuxraw correctly identifies the DualSense and DualShock 4 v2 controllers as "Sony Interactive Entertainment DualSense Wireless Controller" and "Sony Interactive Entertainment Wireless Controller" respectively.

So with sdl2:
* When a DualSense controller is connected and "Save Controller Profile" is clicked, it should save as "Sony Interactive Entertainment DualSense Wireless Controller.cfg".
* When a DualShock 4 v2 controller is connected and "Save Controller Profile" is clicked, it should save as "Sony Interactive Entertainment Wireless Controller.cfg".

### Steps to Reproduce the Bug

1. Follow the [controller guide](https://github.com/libretro/docs/blob/master/docs/guides/controller-autoconfiguration.md#flatpak-configuration) to change the Controller Profiles directory.
2. Go to Settings -> Drivers -> Controller and set it to "sdl2".
3. Connect a PlayStation 4 or PlayStation 5 controller.
4. Navigate to Settings -> Input -> RetroPad Binds -> Port 1 Controls.
5. Connect a DualSense controller and click "Save Controller Profile". It will save as "PS5 Controller.cfg".
6. Disconnect the DualSense controller.
7. Connect a DualShock 4 v2 controller and click "Save Controller Profile". It will save as "PS4 Controller.cfg".

### Version/Commit

- RetroArch: 1.19.1 Flatpak

### Environment Information

- OS: Ubuntu MATE 22.04, 23.04 (likely not OS-specific)

**Comment by gouchi** [comment]
It seems it is the name given by the [SDL2 Game controller community database](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt). You can check it using [SDL2 Gamepad Mapper](https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/releases).

So I am not sure we can change it.

**Comment by RobLoach** [comment]
What gouchi said. The filename that is saved is determined by the input driver, and not a symptom of RetroArch itself. Feel free to rename the file to what you want it to be and send it in a PR to https://github.com/libretro/retroarch-joypad-autoconfig/

**Comment by davidhedlund** [comment]
> What gouchi said. The filename that is saved is determined by the input driver, and not a symptom of RetroArch itself. Feel free to rename the file to what you want it to be and send it in a PR to https://github.com/libretro/retroarch-joypad-autoconfig/

As I said in the top post:
> This issue does not occur with the Appimage version.

Should I file a bug report to the Appimage repo?

**Comment by gouchi** [comment]
>  This issue does not occur with the Appimage version.
> 
> Should I file a bug report to the Appimage repo?

It should give the same result using SDL2 driver for the Flatpak and AppImage.

So you might open an issue but we don't have AppImage repo just [Flatpak](https://flathub.org/apps/org.libretro.RetroArch) and [snap](https://github.com/libretro/retroarch-snap).

Thank you.

**Comment by davidhedlund** [comment]
> Feel free to rename the file to what you want it to be and send it in a PR to https://github.com/libretro/retroarch-joypad-autoconfig/

Thank you. Can you please give me 1-2 weeks to fulfill all PRs? I will tell you when I'm ready.

**Comment by davidhedlund** [comment]
Do **not** reject the PRs. I've spent over a whole working week on them.

**Comment by davidhedlund** [comment]
You can merge all my Android, and all my linuxraw PRs, rob. I'm done with them.

**Comment by davidhedlund** [comment]
> There is an [issue with udev on Flatpak](https://github.com/flathub/org.libretro.RetroArch/issues/194) so they switch to SDL2.
> 
> It seems it is the name given by the [SDL2 Game controller community database](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt). You can check it using [SDL2 Gamepad Mapper](https://gitlab.com/ryochan7/sdl2-gamepad-mapper/-/releases).
> 
> So I am not sure we can change it.

Thank you very much for the database reference.

**Comment by davidhedlund** [comment]
> So you might open an issue but we don't have AppImage repo just [Flatpak](https://flathub.org/apps/org.libretro.RetroArch) and [snap](https://github.com/libretro/retroarch-snap).

Are you aware of this?:
* https://github.com/hizzlekizzle/RetroArch-AppImage/issues

**Comment by davidhedlund** [comment]
* https://github.com/hizzlekizzle/RetroArch-AppImage/issues/12

**Comment by gouchi** [comment]
> Are you aware of this?:
>  https://github.com/hizzlekizzle/RetroArch-AppImage/issues

Yes I know it. But we are using [Gitlab CI/CD](https://github.com/libretro/RetroArch/blob/fab86199a8bc150b3aa755d262acca0b4c63693f/.gitlab-ci.yml#L244-L329) to build the AppImage package.

I meant we don't have dedicated repo for the AppImage package so you might open an issue in this repo.

Thank you.

**Comment by davidhedlund** [comment]
> > Are you aware of this?:
> > https://github.com/hizzlekizzle/RetroArch-AppImage/issues
> 
> Yes I know it. But we are using [Gitlab CI/CD](https://github.com/libretro/RetroArch/blob/fab86199a8bc150b3aa755d262acca0b4c63693f/.gitlab-ci.yml#L244-L329) to build the AppImage package.
> 
> I meant we don't have dedicated repo for the AppImage package so you might open an issue in this repo.
> 
> Thank you.

Thanks back.
