### ISSUE TITLE
Google TV: Controller port increment issue when reconnecting via BlueTooth

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16873]
## Description

This bug is related to the RetroArch application available at [RetroArch APK](https://buildbot.libretro.com/stable/1.19.1/android/RetroArch.apk). The issue is reproducible on Google TV 12 for _Chromecast with Google TV (HD)_. Controllers reconnects fine on Android smartphones that I've tried.

### Expected behavior

It should say "[Controller name] configured in port **1**".

### Steps to reproduce the bug

1. Connect the controller to BlueTooth in Google TV.
2. Start RetroArch
3. Press any key on the controller to activate it in retorarch "[Controller name] configured in port 1".
4. Turn off the controller BlueTooth connectivity from the controller.
5. Reactivate the BlueTooth connectivity from the controller.
6. Press any key on the controller to connect it to RetroArch
7. RetroArch will now say "[Controller name] configured in port **2**", and the controller cannot be used.
8. Repeat step 4-6
7. RetroArch will now say "[Controller name] configured in port **3**", and the controller cannot be used.
9. Repeat step 4-6
10. RetroArch will now say "[Controller name] configured in port **4**", and the controller cannot be used.

**Notes:**
- The controller is locked in RetroArch. To unlock yourself:
  - Press the Home button on the voice remote that is shipped with the Google TV device.
  - Navigate to Settings -> Apps -> RetroArch
  - Press "Force stop"

- The following workaround did not resolve the issue:
  - Settings -> Input -> Maximum Users: 1
  - Main Menu -> Quit (to apply the setting)

### Version/Commit

- RetroArch: [RetroArch APK 1.19.1](https://buildbot.libretro.com/stable/1.19.1/android/RetroArch.apk)

### Environment information

- OS: Google TV 12
- Hardware: Chromecast with Google TV (HD) + Sony DualShock 4 v2 Controller

**Comment by zoltanvb** [comment]
Is the behavior different, when "Android disconnect workaround" option is enabled?

**Comment by davidhedlund** [comment]
> Is the behavior different, when "Android disconnect workaround" option is enabled?

Where is that located specifically (looked around for 10 minutes)?

**Comment by davidhedlund** [comment]
> Is the behavior different, when "Android disconnect workaround" option is enabled?

I can't express enough how grateful I am for your help. Thank you so much for taking the time to assist me. Your guidance made a significant difference, and I genuinely appreciate your expertise and support. It's always a pleasure to work with someone as knowledgeable and helpful as you. Thank you once again for your invaluable assistance!
