### ISSUE TITLE
MS-DOS core should be in the list as MS-DOS, next MS-X not just DOS

### ISSUE THREAD

**Issue by filevans** [libretro/RetroArch#16891]
DOS should be under MS-DOS not "DOS" , and be uniform with the rest of the cores which always have the manufacturer prefix, it should be next to MS-X

# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by zoltanvb** [comment]
Fair point I guess (though technically there were other DOS'es, just not very widespread). I checked the No-Intro status for this, they seem to refer to this as "IBM - PC and compatibles" which is another approach.
But rolling out the change would be painful, as the databases and the info files are handled very much independently of RetroArch releases. Let's see if there are other thoughts on this.

**Comment by hizzlekizzle** [comment]
I think the reasoning on this was indeed that there are other DOS flavors, including FreeDOS, such that specifically calling out MS-DOS would be inaccurate.

**Comment by filevans** [comment]
nonsense, there are multiple emulators / cores for lots of systems, snes, psx etc, they are still stored under their manufacture name!
it should be:
MS - DOS (DOSBox)
MS - DOS (DOSBox Pure)
etc etc

just like it is:
Super Nintendo (Snes9x)
Super Nintendo (bsnes) 
etc etc.

**Comment by hizzlekizzle** [comment]
You're looking at it from the wrong direction. It's not an issue that there are multiple cores, but rather that there were multiple DOSes. Microsoft was not the only maker of DOS, and the various DOS cores are not confined to just MS' flavor of it.

That is, there was only one Super Nintendo vs many DOSes.

Another example is the 3DO. Multiple companies made 3DO consoles. We used to list it under "Panasonic - 3DO" because that was the most common one, but now we list it under "The 3DO Company - 3DO" because that was a more accurate umbrella that covered all of the manufacturers.

**Comment by odditude42** [comment]
Specifically, with DOSBox you could use MS-DOS, PC-DOS, DR-DOS, or FreeDOS, and that's just some of more well-known DOS variants.

**Comment by filevans** [comment]
no because everyone uses MS-DOS to play games

**Comment by odditude42** [comment]
personally, i use FreeDOS - so no, not "everyone".
