### ISSUE TITLE
[IMPORTANT] Unnecessary `input_vendor_id`, and `input_product_id` in autoconfig files generated by udev

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16904]
## Description
Until this issue has been solved it will be impossible to duplicate files and modify the input_device, to make controllers compatible with linuxraw, or udev for with multiple Linux kernel versions, or BlueTooth/USB:
* https://github.com/libretro/RetroArch/issues/16907

In RetroArch, the linuxraw and udev drivers rely on input_device instead of input_vendor_id and input_product_id. These drivers automatically select the autoconfig file that matches the name used by the active Linux kernel.

However, when using udev, RetroArch still generates input_vendor_id and input_product_id, even though they aren't necessary. This behavior is not present in linuxraw. The issue with udev creates the impression that users need to comment or uncomment these IDs to choose which udev autoconfig file to use, especially when multiple autoconfig files are available—a common scenario for both non-HID and HID autoconfig files.

### Expected behavior

The configuration should be as follows:
```
input_driver = "udev"
input_device = "Pro Controller"
```

Also, input_driver and input_device should not be required by PR checks for udev (they are not required by linuxraw)

![image](https://github.com/user-attachments/assets/7c3337cb-2300-4ed5-a98d-77e5ae9b2391)

### Actual behavior

udev: The configuration currently includes unnecessary vendor and product IDs: 
```
input_driver = "udev"
input_device = "Pro Controller"
input_vendor_id = "1406"
input_product_id = "8201"
```

linuxraw
```
input_driver = "linuxraw"
input_device = "Pro Controller"
```

### Steps to reproduce the bug

* Change the controller profile directory.
* Navigate to Settings -> Drivers -> Controller, and select "udev".
* Restart RetroArch to apply the new setting.
* Go to Settings -> Input -> RetroPad Binds -> Port 1 Controls, and click on "Save Controller Profile".
* Repeat step 1-3 but select "linuxraw" in step 1

### Todo list

After resolving the issue, please remove input_driver and input_device from the following autoconfig files that I am maintaining:
* DualSense
* Nintendo Switch Pro Controller
* Nintendo Switch Pro Controller (non-HID)
* DualShock 4 v2

Newly created PRs that can be used to diagnose this issue:
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1140
* https://github.com/libretro/retroarch-joypad-autoconfig/pull/1186

### Version/Commit

- RetroArch: 1.19.1

**Comment by zoltanvb** [comment]
Hello,

I'd like to ask about this statement:
_In RetroArch, the linuxraw and udev drivers rely on input_device instead of input_vendor_id and input_product_id._
Linuxraw driver has no way of retrieving vendor/product ID, as we have concluded under an earlier ticket. But udev seems to retrieve it and supply it for the autoconfig matching logic, so why would it be unnecessary?
https://github.com/libretro/RetroArch/blob/585e70ec6d00c7f09902533324b651e2d0e76913/input/drivers_joypad/udev_joypad.c#L211
and
https://github.com/libretro/RetroArch/blob/585e70ec6d00c7f09902533324b651e2d0e76913/input/drivers_joypad/udev_joypad.c#L279

**Comment by davidhedlund** [comment]
> Hello,
> 
> I'd like to ask about this statement: _In RetroArch, the linuxraw and udev drivers rely on input_device instead of input_vendor_id and input_product_id._ Linuxraw driver has no way of retrieving vendor/product ID, as we have concluded under an earlier ticket. But udev seems to retrieve it and supply it for the autoconfig matching logic, so why would it be unnecessary?
> 
> https://github.com/libretro/RetroArch/blob/585e70ec6d00c7f09902533324b651e2d0e76913/input/drivers_joypad/udev_joypad.c#L211
> 
> and
> 
> https://github.com/libretro/RetroArch/blob/585e70ec6d00c7f09902533324b651e2d0e76913/input/drivers_joypad/udev_joypad.c#L279

Could you please review and confirm the following steps?

* Remove input_vendor_id and input_product_id from a udev autoconfig file associated with your controller.
* Launch RetroArch.
* RetroArch should successfully connect to your controller, correct?
* Close RetroArch.
* Modify input_device in the autoconfig file.
* Launch RetroArch again.
* This time, RetroArch will not connect to your controller, correct?

I am curious about what the code does in the lines you mentioned.

If input_vendor_id and input_product_id are essential, we should include this information in our [joypad user guide](https://github.com/libretro/docs/blob/master/docs/guides/controller-autoconfiguration.md) by adding something like : _The udev controller uses the input_vendor_id and input_product_id variables. While they are not required for RetroArch to connect the controller, they are used for [arguments]._

**Comment by zoltanvb** [comment]
Doing the above, I get the following with my controller:
- after step 1, I get the new autoconfig file (created by me) during connection
- after removing the input_vendor_id and input_product_id from the autoconfig file generated by me, I get another match (this is an XBox One pad, there is already a suitable autoconfig with same vid/pid, but slightly different name)
- if I remove the other autoconfig files, but keep the one generated by me, it will be found even with vendor and product ID removed

All in all, it works according to the affinity rules: https://github.com/libretro/RetroArch/blob/329b16d267acdb0c8be0146b6837379620975366/tasks/task_autodetect.c#L104

**Comment by davidhedlund** [comment]
> Doing the above, I get the following with my controller:
> 
>     * after step 1, I get the new autoconfig file (created by me) during connection
> 
>     * after removing the input_vendor_id and input_product_id from the autoconfig file generated by me, I get another match (this is an XBox One pad, there is already a suitable autoconfig with same vid/pid, but slightly different name)
> 
>     * if I remove the other autoconfig files, but keep the one generated by me, it will be found even with vendor and product ID removed
> 
> 
> All in all, it works according to the affinity rules:
> 
> https://github.com/libretro/RetroArch/blob/329b16d267acdb0c8be0146b6837379620975366/tasks/task_autodetect.c#L104

* Thank you for providing a helpful reference for our guide. I assume the same principles apply to the issue discussed at https://github.com/libretro/RetroArch/issues/16920. Could you please post something there? I'll review these issues tomorrow and update our guide accordingly.

**Comment by davidhedlund** [comment]
* Documented: https://github.com/libretro/docs/pull/984

Thank you very much for taking the time to assist Zoltanvb!
