### ISSUE TITLE
Retroarch Stable 1.19.1 Linux Core Downloader Empty

### ISSUE THREAD

**Issue by theofficialgman** [libretro/RetroArch#16916]
## Description

No cores are available in retroarch stable

### Expected behavior

Expect the cores to be available as listed https://buildbot.libretro.com/nightly/linux/x86_64/latest/

### Actual behavior

No cores are available

### Steps to reproduce the bug

1. Fresh install of Kubuntu Noble 24.04 on x86_64
2. Fresh install of retroarch via official ppa
3. Enter Main Menu -> Online Updater -> Core Downloader -> No Entries to Display

### Attempted workaround

I attempted to "Run update core info files" but this did not fix the issue

### Version/Commit
- RetroArch: 1.19.1

### Environment information

- OS: Ubuntu Noble 24.04 x86_64

**Comment by theofficialgman** [comment]
enabling experimental cores seems to work as a workaround

**Comment by theofficialgman** [comment]
This issue is caused by a leftover of RetroPie (which I previously had installed but uninstalled) that left over a symlink from `~/.config/retroarch` to `/opt/retropie/configs/all/retroarch` that no longer existed

**Comment by hizzlekizzle** [comment]
thanks for following up with your solution!

**Comment by theofficialgman** [comment]
To add to this issue, all cores could not be installed even once this was fixed

This issue is due to an actual bug with the ppa where the default cores directory is

```
libretro_directory = "/usr/lib/x86_64-linux-gnu/libretro"
```

instead of something like

```
libretro_directory = "~/.config/retroarch/cores"
```
```

**Comment by hizzlekizzle** [comment]
Yeah, this is known behavior, rather than a bug. The PPAs are (currently) becoming more like regular distro packages. You can see my forum post here for more context on it: https://forums.libretro.com/t/solved-ppa-reinstall-assets-dont-work-uses-usr-share-libretro/45777/11

I hope this lets us exert a little more influence on the various distro packages floating around by being a good example.

**Comment by theofficialgman** [comment]
> Yeah, this is known behavior, rather than a bug. The PPAs are (currently) becoming more like regular distro packages. You can see my forum post here for more context on it: https://forums.libretro.com/t/solved-ppa-reinstall-assets-dont-work-uses-usr-share-libretro/45777/11

@hizzlekizzle Retroarch is broken on the official first recommended installation method https://www.retroarch.com/index.php?page=linux-instructions . By definition that's a bug.
