### ISSUE TITLE
.opt files stored in `${XDG_CONFIG_HOME:-$HOME/.config}/retroarch/config/`

### ISSUE THREAD

**Issue by theofficialgman** [libretro/RetroArch#16918]
## Description

retroarch is storing `.opt` files for cores in a core folder name in the path

```
/home/gman/${XDG_CONFIG_HOME:-$HOME/.config}/retroarch/config/
```
No that is not a typo, the folder is literally called `${XDG_CONFIG_HOME:-$HOME` inside the home folder (~) and then `.config}`

eg: `/home/gman/${XDG_CONFIG_HOME:-$HOME/.config}/retroarch/config/Gambatte/Gambatte.opt`

It is functioning it seems but the path is very strange.

All retroarch settings default except for this bug fixed: https://github.com/libretro/RetroArch/issues/16916#issuecomment-2305296474

### Expected behavior

use the path
```
/home/gman/config/retroarch/.config/retroarch/config/Gambatte/Gambatte.op
```

### Actual behavior

```
`/home/gman/${XDG_CONFIG_HOME:-$HOME/.config}/retroarch/config/Gambatte/Gambatte.opt`
```

### Steps to reproduce the bug

1. save a config with an emulator that uses a `.opt` config

### Version/Commit

- RetroArch: 1.19.1

### Environment information

- OS: Ubuntu Noble x86_64
- Install: Official PPA

**Comment by hizzlekizzle** [comment]
Someone mentioned this a couple of weeks ago and I completely forgot to follow up on it.

Looks like the guy who committed it expected it to get evaluated as if it were in a bash command, but instead it's just used as-is.

I reverted that part and the next nightly should be back to normal.

**Comment by theofficialgman** [comment]
> I reverted that part and the next nightly should be back to normal.

This report is for the stable ppa (haven't tested nightly). Is there a plan to fix it there?

**Comment by hizzlekizzle** [comment]
I can trigger a new build.

**Comment by theofficialgman** [comment]
> I can trigger a new build.

this would be much appreciated.

**Comment by theofficialgman** [comment]
Closing as this has been resolved in the PPA defaults and I have updated my retroarch.cfg to match

**Comment by hizzlekizzle** [comment]
Nice. thanks for confirming and closing the issue!
