### ISSUE TITLE
[IMPORTANT] Document that `input_device` is utilized by the android, and sdl2 controller drivers

### ISSUE THREAD

**Issue by davidhedlund** [libretro/RetroArch#16920]
## Description

The `input_device` is utilized by the udev and linuxraw controller drivers, while `input_vendor_id` and `input_product_id` are not used by these drivers. Conversely, the `input_vendor_id` and `input_product_id` are used by the Android and SDL2 controller drivers, where `input_device` is not utilized. This discrepancy is highlighted in the related issue [#16904](https://github.com/libretro/RetroArch/issues/16904).

### Expected behavior

The "Save Controller Profile" feature should not add `input_device` to the autoconfig file when using Android or SDL2 drivers.

### Actual behavior

Currently, "Save Controller Profile" adds `input_device` to the autoconfig file, which is unnecessary for Android and SDL2 drivers.

### Steps to reproduce the bug

1. Navigate to: Settings -> Drivers -> Controller.
2. Change the controller driver to "android" or "sdl2".
3. Restart RetroArch to apply the setting.
4. Navigate to: Settings -> Input -> RetroPad Binds -> Port 1 Controls.
5. Click on "Save Controller Profile".
6. Close RetroArch.

Example of a Sony DualSense generated file called "PS5 Controller.cfg":
```
input_driver = "sdl2"
input_device = "PS5 Controller"
input_vendor_id = "1356"
input_product_id = "3302"
```

7. Open RetroArch. It will pop-up: "PS5 Controller configured on port 1"
8. Close RetoArch
9. Rename "PS5 Controller.cfg" to "test.cfg" and delete "input_device" from it
```
input_driver = "sdl2"
input_vendor_id = "1356"
input_product_id = "3302"
```

10. Open RetroArch again. It still displays: "PS5 Controller configured on port 1", indicating that `input_device` is redundant.

### Version/Commit
- RetroArch: 1.19.1 flatpak

**Comment by zoltanvb** [comment]
SDL joypad driver seems to handle name along with vendor / product IDs:
https://github.com/libretro/RetroArch/blob/329b16d267acdb0c8be0146b6837379620975366/input/drivers_joypad/sdl_joypad.c#L155

Android also fills the name, it even has some extra processing for that field:
https://github.com/libretro/RetroArch/blob/329b16d267acdb0c8be0146b6837379620975366/input/drivers/android_input.c#L1330

These drivers are operating the same way as udev in #16904, adding all possible identification info for the structure, so it seems to be correct.

**Comment by davidhedlund** [comment]
* Documented: https://github.com/libretro/docs/pull/984

Thank you very much for taking the time to assist Zoltanvb!
