### ISSUE TITLE
The text "Press any key to return to start menu" obscures the error message and is displayed in the screenshot

### ISSUE THREAD

**Issue by Korb** [libretro/RetroArch#16935]
## Description

If there is a problem with starting the game, I would prefer to see the last line of the console output. Instead, the bottom of the screen is occupied by the inscription "Press any key to return to start menu", which makes it difficult to read the text of the running application.

![CHESSWAR-240827-134542](https://github.com/user-attachments/assets/b3be534a-65a7-475c-a3d9-713e61636f17)

### Expected behavior

I would prefer to see the RetroArch message outside the running app's screen. Or, at the very least, I would prefer to see the notification only in the overlay (like the subtitles or fps data in the Steam client). That is, this message, which is not part of the running application, should not be displayed in the screenshot created by the RetroArch application.

### Actual behavior

See Description section.

### Steps to reproduce the bug

1. Remove the critical file from the MS-DOS application
2. Launch the application using RetroArch
3. Wait for the message to appear, obscuring the launch log. Take a screenshot.

### Version/Commit

- RetroArch: 1.19.1

### Environment information

- OS: Microsoft Windows 10.0.19045.4780

**Comment by hizzlekizzle** [comment]
RetroArch is not making that error message, the core is. I know that distinction may seem esoteric, but changes to RetroArch will not fix it, so the request will need to happen at the core's repo instead.
