### ISSUE TITLE
Double Entry - Super Puzzle Bobble (Taito G-NET)

### ISSUE THREAD

**Issue by NeoArcade1** [libretro/RetroArch#16945]
I'm looking to hide a CHD file that has the same name as a ZIP file.

I have chd files that I need scanned, so when I do a manual scan, I add chd to the file extensions area.

However, I also need to hide a chd file that has the same name as a zip file. 

With Super Puzzle Bobble I must rename coh3002t.zip to spuzbobl.zip for it to function.

However, "spuzbobl" is also the same name as the chd file that is used for the game so the dat file is populating both.

Here is what I have currently:

`Game Folder`
`spuzbobl / spuzbobl.chd`
`spuzbobl.zip`

DAT FILE
_________________________
machine name="spuzbobl">
		description>Bust-A-Move, Super (World)</description
		comment>Renamed coh3002t.zip File - new file name - spuzbobl.zip</comment
	/machine>
	
game isbios="yes" name="spuzbobl">
		comment>Trick to believe its a bios file to Hide CHD - file name - spuzbobl.chd</comment
		description>Bust-A-Move, Super CHD</description
	/game>
_________________________

Can someone recommendation a DAT file edit to hide this CHD file?
Here are my results from the DAT config above. It populates both the ZIP and CHD files with the following name.

Bust-A-Move, Super (World)
Bust-A-Move, Super (World)

**Comment by sonninnos** [comment]
Indeed for some reason both the core and the info file has `chd` extension added in the extension list, which does not really make any sense, since those aren't supposed to be launched alone, because the core can't know what system to use with it anyway..

**Comment by sonninnos** [comment]
With new info files chds are no longer included in the scan.
