### ISSUE TITLE
Update Cheats not showing

### ISSUE THREAD

**Issue by Kelvfimer** [libretro/RetroArch#16943]
## Description

Running Retroarch the update cheat option is not appearing

![20240830_121644](https://github.com/user-attachments/assets/52550b78-c01c-465f-8e48-391aa3ae6512)

### Expected behavior

To appear

### Actual behavior

Lack of the option

### Steps to reproduce the bug

1.- Enable advanced settings
2.- Enable core updater.
3.- go to core updater

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

19.1/3d272d4714214c8001065d0f6bde2f909f838f55

- OS: Linux 4.9 odroid n2+ aarch64
- Compiler: gcc  12

**Comment by gouchi** [comment]
Hi,

From where did you get RetroArch as we don't provide RetroArch Linux binary for aarch64 ?

Perhaps you did use a Linux distro ? How was it compile ?

Thank you.

**Comment by Kelvfimer** [comment]
> Hi,
> 
> From where did you get RetroArch as we don't provide RetroArch Linux binary for aarch64 ?
> 
> Perhaps you did use a Linux distro ? How was it compile ?
> 
> Thank you.

Yep I'm building EMUELEC https://github.com/EmuELEC/EmuELEC . These are the building parameters https://github.com/EmuELEC/EmuELEC/blob/dev/packages/sx05re/libretro/retroarch/package.mk

**Comment by gouchi** [comment]
Thank you for the information.

It will be better if you open an issue to [EmuELEC repository](https://github.com/EmuELEC/EmuELEC/issues) first as it might be a choice of EmuElec.

**Comment by Kelvfimer** [comment]
thx @gouchi

**Comment by kingthomasjr** [comment]
@Kelvfimer did you ever figure out how to get around this issue with retroarch?
