### ISSUE TITLE
RetroAchievements not working with PPSSPP core with CSO and DVD CHD

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#16953]
## Description

Posting here instead of the PPSSPP repo because AFAICT this is a RetroArch issue.

RetroAchievements don't work with the PPSSPP core depending on the format of the game:

* .iso: works.
* .chd (createcd): works.
* .chd (createdvd): doesn't work.
* .cso: doesn't work.

They all work properly with standalone PPSSPP.

Logs with .chd (createdvd):
```
[INFO] [RCHEEVOS]: Identifying game: F:\Emulation\_tools\chdman\Jeanne d'Arc (USA)_dvd.chd
[INFO] [RCHEEVOS]: Found 9 potential consoles for chd file extension
[INFO] [RCHEEVOS]: Trying console 12
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 21
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 40
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 9
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 41
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 76
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 43
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 56
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Trying console 49
[INFO] [RCHEEVOS]: Could not open track
[INFO] [RCHEEVOS]: Load failed (-25): hash generation failed
[INFO] [RCHEEVOS]: RetroAchievements game load failed: hash generation failed
```

Logs with .cso:
```
[INFO] [RCHEEVOS]: Identifying game: F:\Emulation\_tools\maxcso_v1.12.0_windows\Jeanne d'Arc (USA).cso
[INFO] [RCHEEVOS]: Found 0 potential consoles for cso file extension
[INFO] [RCHEEVOS]: Trying console 4
[INFO] [RCHEEVOS]: Opened Jeanne d'Arc (USA).cso
[INFO] [RCHEEVOS]: Hashing first 67108864 bytes (of 769807047 bytes) of Jeanne d'Arc (USA).cso
[INFO] [RCHEEVOS]: Generated hash 92349eceb1704b2ecda70978988413d9
[INFO] [RCHEEVOS]: Identified game: 0 (92349eceb1704b2ecda70978988413d9)
[INFO] [RCHEEVOS]: Load failed (-29): Unknown game
[INFO] [RCHEEVOS]: Game not recognized, pausing hardcore
```

### Steps to reproduce the bug

1. Convert a compatible game to .cso or .chd (with the createdvd command).
2. Make sure achievements are enabled and that you're logged in.
3. Load game

### Version/Commit

- RetroArch: 1.19.1 / 585e70e

### Environment information

- OS: Windows 10

**Comment by Jamiras** [comment]
The "createdvd" issue is discussed here: #16145. Basically, the libchdr dependency that RetroArch uses to read CHDs doesn't support "createdvd" formatted CHDs. And even if it did, someone would have to upgrade the dependency before RetroArch would be able to support it.

RetroAchievements doesn't understand what a CSO is, so it relies on the client (RetroArch) to decode it. RetroArch doesn't inherently support CSO files (see also #13735). CSOs support is internal to the PPSSPP core. For RetroArch to understand it, some library that would have to be integrated into RetroArch (like the libchdr referenced above).

**Comment by bslenul** [comment]
Thank you for the explanation! I just assumed RetroAchievements basically had the required code to be able to get the hash from these formats, it makes more sense now 👍 

I'll close since there are already 2 related issues, sorry about that btw, no idea how I missed these 🤔
