### ISSUE TITLE
[Feature Request] Toggle Scroll Lock LED when Game Focus is toggled or run script when Game Focus is toggled.

### ISSUE THREAD

**Issue by TakahashiNZ** [libretro/RetroArch#16976]
Description
Pushing Scroll Lock toggles game focus On/Off, but the Scroll Lock LED isn't switched On/Off

Expected behaviour
When pushing Scroll Lock to disable game focus RetroArch should send a command to the keyboard to turn the Scroll Lock LED on.

Actual behaviour
Toggling game focus has no effect on Scroll Lock LED

Steps to reproduce the bug
Start RetroArch
Launch a game
Press Scroll Lock to disable Game focus
Observe no change in Scroll Lock LED.

Notes:
Executing the command "kbd_mode -f -u" will cause the Scroll Lock LED to respond to pressing the Scroll Lock key, but if Scroll Lock is on when the game is launched, then the meaning of the Scroll Lock LED becomes inverted.
Scroll Lock LED can be manually toggled On/Off using the commands "setleds +scroll" and "setleds -scroll".

Having the ability to make the Scroll Lock LED represent game focus has two key benefits, firstly you get a visual indicator of whether game focus is enabled or not and secondly, it allows keyboard emulators to behave differently depending on whether game focus is enabled or not.

I'm trying to make a physical exit button on my arcade that will exit the game regardless on the game focus state. If the Scroll Lock LED represents game focus, then it should be simple to make the Arduino send the key combination to disable game focus, then send the key combination for the hotkey, and then send the key combination to reenable game focus (if the hotkey wasn't exit).

Any help would be much appreciated, I'm new to RetroArch and don't know where to start. I realise this is a pretty niche request, but if it can't be implemented easily, could someone at least point me in the direction of somewhere I can modify a script or hook the game focus toggle event?

**Comment by zoltanvb** [comment]
The most practical place for such a function would probably be in the input driver. But the input driver selection is actually quite much controlled by the video context, i.e. the windowing environment (and the change is maybe not even visible from the GUI), so the first step would be to define what the input driver will be used.

Linuxraw driver seems to have one special case for Ctrl+C:
https://github.com/libretro/RetroArch/blob/42f66adbf27f54f54dacb4015298d19b4e6714b8/input/drivers/linuxraw_input.c#L181

**Comment by sonninnos** [comment]
I do not want Scroll Lock to represent the Game Focus state, since I have Game Focus bind elsewhere, therefore it should be totally optional, or rather only behave like that if the bind is in that key.

**Comment by zoltanvb** [comment]
@TakahashiNZ : you can send me DM on libretro discord if you need more pointers for a custom implementation.
