### ISSUE TITLE
PS2 Retroarch does not allow searching for roms 

### ISSUE THREAD

**Issue by andres0021** [libretro/RetroArch#16975]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]
Hi, RetroArch for PS2 has been updating for several years and it has not been able to search for your games. When you press "mass" or any other button, RetroArch completely freezes, without being able to do anything. This has continued for several updates. I tried with a 16 GB USB, and it still doesn't work. 

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by andres0021** [comment]
Hi, now it works, I tried the new update yesterday and it was fixed. Thanks
:))

**Comment by fjtrujy** [comment]
Nice to know!
