### ISSUE TITLE
retroarch freezes when notification_show_autoconfig = "true" with joystick plugged in

### ISSUE THREAD

**Issue by theflyingape** [libretro/RetroArch#16983]
Latest `git pull` won't run retroarch with a joystick plugged in with the feature `notification_show_autoconfig = "true"` enabled. At least under wayland, I can close its window. :+1: but have to hit the power off button the Pi console to reboot.
Keeping the joystick unplugged or setting its notification to false runs.

**Comment by hizzlekizzle** [comment]
Can you try to bisect and find which commit started it?

**Comment by theflyingape** [comment]
If it helps, I can confirm that it is working with my September 7th build off git version c0715fc420 but it is currently failing off today's git version 5892551f75

**Comment by gouchi** [comment]
@theflyingape Can you provide some log ? I can't reproduce this issue using latest https://github.com/libretro/RetroArch/commit/5892551f75ce04b3d631e7070f2f4ad600851491  on  Linux x86_64.

**Comment by theflyingape** [comment]
I just pulled latest d4e5f7ac4b and recompiled without encountering this issue - thanks!
