### ISSUE TITLE
MacOS Nightlies since 10 September 2024 crash for me with complex shaders (koko-aio, Mega_Bezel)

### ISSUE THREAD

**Issue by estefan3112** [libretro/RetroArch#16999]
## Description
RetroArch Nightly Builds for MacOS Metal crash with me since 10 September 2024 if I activate complex shaders, such as koko-aio and Mega_Bezel. Ligher shaders, such as crt-geom, still work. The developer of the koko-aio shader sees no issues on his non-MacOS builds. I tested the 9 September 2024 build without issues. In the 10 September 2024 build, this commit seems to change shaders: "Downsize big char arrays in shader structs".

The crash happens for me in any core, I tested FinalBurn Neo, MAME current and PPSSPP.

### Steps to reproduce the bug

1. Launch a MacOS Metal Build starting from 10 September 2024
2. Launch a game, activate any preset of either koko-aio or Mega_Bezel -> crash
3. Activate crt-geom -> works

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Mightly MacOS Metal Build starting from 10 September 2024

### Environment information

- OS: MacOS Sonoma 14.6.1

**Comment by hizzlekizzle** [comment]
This should get fixed by: https://github.com/libretro/RetroArch/pull/16998

**Comment by estefan3112** [comment]
Tested successfully with todays Nightly Build in several cores and koko-aio. Save enough to close. Many thanks.
