### ISSUE TITLE
iOS App Store version crashes on startup

### ISSUE THREAD

**Issue by emeraldsucksss** [libretro/RetroArch#17005]
Was trying to change the font, then it crashed. It wouldn't reopen. I was trying to get it to open again but i can't. I offloaded it, reinstalled it, nothing works. I didn't have a config file too so deleting a nonexistent file would probably not do anything. Is there a fix for this?

iPhone 11 Pro Max
iOS 18.0 RC

**Comment by warmenhoven** [comment]
I tried the current App Store version on my iPhone 13 Pro running iOS 18.0 RC and couldn't figure out how to reproduce a crash, even after changing the font multiple times.

> I didn't have a config file

I don't understand what this means. RetroArch creates a config file the first time it runs. You have a config file.

I also couldn't see how to change the font from the default menu driver, glui, and had to change to xmb to change the font. Did you do similar? If so... you not only have a config file, you have a config file that is different from the defaults.

**Comment by emeraldsucksss** [comment]
> I tried the current App Store version on my iPhone 13 Pro running iOS 18.0 RC and couldn't figure out how to reproduce a crash, even after changing the font multiple times.
> 
> 
> 
> > I didn't have a config file
> 
> 
> 
> I don't understand what this means. RetroArch creates a config file the first time it runs. You have a config file.
> 
> 
> 
> I also couldn't see how to change the font from the default menu driver, glui, and had to change to xmb to change the font. Did you do similar? If so... you not only have a config file, you have a config file that is different from the defaults.

Yes i changed the theme to xmb. Where can i locate the config file?

**Comment by warmenhoven** [comment]
In the Files app, in the Browse tab there is an On My iPhone item; in there is a RetroArch folder with the RetroArch icon. From there it is RetroArch/config/retroarch.cfg.

**Comment by emeraldsucksss** [comment]
> In the Files app, in the Browse tab there is an On My iPhone item; in there is a RetroArch folder with the RetroArch icon. From there it is RetroArch/config/retroarch.cfg.

Ight thanks. Deleted it and that fixed the issue

**Comment by warmenhoven** [comment]
If you're able to reproduce it, please upload the retroarch.cfg here and I'll see if I can reproduce it.

**Comment by RobLoach** [comment]
Thanks all... Likely problematic when a font or theme is incompatible.
