### ISSUE TITLE
Check for libusb 1.0.16

### ISSUE THREAD

**Issue by duganchen** [libretro/RetroArch#1702]
input/drivers_hid/libusb_hid.c uses *libusb_hotplug_callback_handle*, which was added to libusb as of version 1.0.16. That means that libusb 1.0.16 or newer is a build-time dependency.

Reference:

http://libusb.sourceforge.net/api-1.0/group__hotplug.html#ga4868157346bbf2c70b6af0cb0a6c0094

The configure script should refuse to continue if libusb 1.0.16 or newer is not available.

**Comment by twinaphex** [comment]
I don't want hard build-time dependencies. At best it should be an optional build-time dependency.

**Comment by duganchen** [comment]
Sure. Pull request submitted. I've tested it with both libusb 1.0.9 and 1.0.16 and it builds in both cases.

**Comment by twinaphex** [comment]
Thanks.

Hopefully it fixes this issue here too - https://github.com/libretro/RetroArch/issues/1602
