### ISSUE TITLE
Add the Big Picture Mode switch-off option in the Windows client

### ISSUE THREAD

**Issue by Korb** [libretro/RetroArch#17037]
## Description

Big Picture Mode is very convenient for gaming video consoles: you get on the sofa, your hands are busy with a controller, on which there are only a few buttons, and the interface, which will, in this case, will be convenient for you, are characterized by a number of requirements that are fully consistent with all four distributions Retroarch profiles. However, Big Picture Mode (in Steam terms) is convenient only for the described situations, as well as for mobile game consoles with similar controls, and, most often, is not convenient for the game launches from Valve, GOG, EPIC and Microsoft.

I play, like most players on the PC, sitting at the table, in front of the monitor; I have a comfortable chair, a large UW monitor and the corresponding GPU, but when setting up the application and gaming, I have to constantly use scrolling and observe full-screen visual transitions where it is enough to place several interdependent blocks of variable width.

I understand that it is easier to force PC users to use Big Picture Mode than users of TVs and mobile devices - use the window interface. However, at least, please provide, among the initially available interface profiles, at least one profile, using which there is no feeling that I opened a mobile version of the site on a computer.

Perhaps this profile even make a profile by defending Retroarch for Windows.

### Expected behavior

I don’t know what this interface is depicted on this screenshot, but it seems to me much more convenient than four available:

![Va3ouyz](https://github.com/user-attachments/assets/12cc1c8a-aeec-45b3-b16b-cebdf7c18c74)

### Actual behavior

![2024-09-25_18-31-50 2](https://github.com/user-attachments/assets/6f7a7c31-e199-47bc-a6a4-1466fe4484f8)

### Version/Commit

- RetroArch: 1.19.1 _(absurd, that you have to write instructions where to find a version of an advanced application. Because it should always be at least in the last menu item, "Help"/"About")._

### Environment information

- OS: Microsoft Windows 10.0.19045.4957

**Comment by hizzlekizzle** [comment]
That picture is the Qt "desktop menu", which you can get by pressing F5 (by default). You can set that to come up on launch but you can't get rid of the "big picture" window because that's the "real" RetroArch process. The desktop menu simply builds on top of it.
