### ISSUE TITLE
When I load "Retroarch.rpx" it wont load

### ISSUE THREAD

**Issue by OneSuperCad** [libretro/RetroArch#17034]
## Description

When I load "Retroarch.rpx" it wont load

### Expected behavior

I expected it to just, ya know, LOAD LIKE NORMAL

### Actual behavior

It just loads with a white screen and it shows the app image in the middle and the name below the image.

### Steps to reproduce the bug

I downloaded it from "https://wiiu.cdn.fortheusers.org/zips/retroarch.zip" and I put it on my SD card, like normal, idk if it might bug for yall tho

It started when I just loaded it for the first time, and I tried it like, 3 times and it just won't load :(

### Environment information

- OS: Windows 10 (to install it)
- version of Retroarch: 1.19.1
- Using Aroma

**Comment by viachaslavic** [comment]
> I downloaded it from "https://wiiu.cdn.fortheusers.org/zips/retroarch.zip" and I put it on my SD card, like normal, idk if it might bug for yall tho

Have you tried installing the build from [the official site](https://retroarch.com/?page=platforms)? Also you can try [nightly build](https://buildbot.libretro.com/nightly/nintendo/).

**Comment by OneSuperCad** [comment]
Oh, yeah, thanks, lol, it worked (I'm kinda stupid XD)

**Comment by viachaslavic** [comment]
Please, close issue if this is solved.
