### ISSUE TITLE
.gitignore unclear lines

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#1705]
Hi,

In the gitignore, there is `/retroarch.*` and `/tools/retroarch-joyconfig.*`, why ? The only thing it does for me is ignoring `retroarch.h`, `retroarch.c`, `retroarch.cfg` and `/tools/retroarch-joyconfig.c`, which is obviously breaking my repo.

**Comment by twinaphex** [comment]
Check if the PR by @heuripedes fixes this.
