### ISSUE TITLE
Symbian OS, N-Gage and Java Me Cores in RetroArch (EKA2L1, J2ME)

### ISSUE THREAD

**Issue by Gabrielcnnunes** [libretro/RetroArch#17066]
The old cellphones are with a good progress in emulating its systems, emulators like EKA2L1 (Symbian OS and N-Gage) and J2ME (Java ME) are emulating a lot of games with a good quality.

 Is the devs working on these emulators to add to RetroArch? If not, I'd like to request cores from EKA2L1 (Symbian OS and N-Gage) and J2ME (Java ME), will be a great addition to emulating old phone systems.

There is a core for Java ME for RetroArch called SquirrelJME but can't run it correctly, I think it's not ready yet. We need another core to supply this demand.

**Comment by gouchi** [comment]
Hi,

Duplicate issue for [EKA2L1](https://github.com/libretro/RetroArch/issues/15184).

If there is an issue with SquirrelJME, please open an [issue](https://github.com/SquirrelJME/SquirrelJME/issues) to the dedicated repository.

Thank you.

**Comment by gouchi** [comment]
Hi,

Please close this issue.

Thank you.
