### ISSUE TITLE
[bug] wayland - can't interact with overlays via mouse

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#17078]
## Description

I was trying to test some overlay behavior in wayland and can't click on any virtual buttons/analogs. I tried clearing my config and using older versions of RetroArch in case there was a regression but it appears to be longstanding/always this way. I also tried using different input and gamepad (just to be thorough) drivers (udev, sdl2, x) with no change. However, switching to Xorg fixes it instantly.

### Expected behavior

click on buttons with the mouse to trigger the button functions

### Actual behavior

the overlay is completely unresponsive

### Steps to reproduce the bug

1. use wayland
2. enable an overlay
3. click on it (nothing happens)

### Bisect Results

tested back to v1.16.0

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.19.1 c43bc65c7e

### Environment information

- OS: Ubuntu Linux 24.04.1 LTS
- Compiler: 13.2.0

**Comment by grant2258** [comment]
The overlay works fine in wayland. I suspect its permissions causing your issue(if this is the case the mose wont work on any cores either but will probably work fine in the UI).  Its easy to test if that is the case just run retroarch as root with sudo retroarch if you choose udev as the input driver it will show you the mouse name X11 and wayland wont.

**Comment by hizzlekizzle** [comment]
Ah, yeah, seems to be related to permissions, indeed.

**Comment by grant2258** [comment]
Have you tested its working with kms to do that issue a "sudo telinit 3" make sure the the udev driver is selected. If your mouse shows up its wayland end permissions only.
