### ISSUE TITLE
Add option to remove "Core remap file loaded." Notification

### ISSUE THREAD

**Issue by AlanEight** [libretro/RetroArch#17083]
Hello. I am new to posting stuff here on Github, let alone asking for changes to be made to RetroArch.

Could we get the ability to turn off the notification for "Core remap file loaded."? I am running my GameBoy and GameBoy Color roms through Gambatte, and turned off the hotkey for using R2 for Fast Forward. I didn't want the ability to just enable Fast Forward without holding my Hotkey button first. So I disabled that hotkey in the core and saved it as a core override so it doesn't happen on GameBoy games either. But now every time I open any games using Gambatte I get that notification telling me the core remap file was loaded, and I can't see any toggle to disable that notification. I don't want to turn off all notifications, so I can still see my Retro Achievement notifications, but the "Core remap file loaded." notification is bugging me.

Thank you!

**Comment by sonninnos** [comment]
It already exists:
![retroarch_2024_10_09_07_26_33_912](https://github.com/user-attachments/assets/6e233899-6a66-474b-9ffb-b360e3b59cd4)

**Comment by AlanEight** [comment]
I swear, I turned off every notification, including this one, and it was still popping up. Trying it again this morning, it was that one. Thank you! ❤️
