### ISSUE TITLE
i can not run successfull with this rom？ （ fba games）

### ISSUE THREAD

**Issue by lt1023** [libretro/RetroArch#17107]
EDIT: Don't post links to copyrighted material again. This causes issues for us.

**Comment by gouchi** [comment]
Hi,

As written in the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md),

> Only RetroArch bugs should be filed here. Not core bugs or game bugs
> This is not a forum or a help section, this is strictly developer oriented

So please read the [documentation](https://docs.libretro.com/guides/arcade-getting-started/#step-3-use-the-correct-version-romsets-for-that-emulator) , and if you still don't succeed ask help in the [forum](https://forums.libretro.com/) or [discord](https://ra-link.web.app/discord) with [logs](https://docs.libretro.com/guides/generating-retroarch-logs/).

Please close this issue.


Thank you.
