### ISSUE TITLE
break audio drivers with the patch #16467 in RARCH_NETPLAY_CTL_USE_CORE_PACKET_INTERFACE fuction

### ISSUE THREAD

**Issue by Ninoh-FOX** [libretro/RetroArch#17104]
## Description

audio is pause or not work with netplay with RARCH_NETPLAY_CTL_USE_CORE_PACKET_INTERFACE in RA 1.19.1, in 1.18.0 works fine

or is problem of netplay or is problem the new start/stop audio menu code in https://github.com/libretro/RetroArch/pull/16467/files

### Steps to reproduce the bug

1. set audio driver in SDL for example
2. load a GBA game with GPSP core
3. set host netplay

### Bisect Results

the audio not work, it is pause, if you close the network the audio is start again.

### Version/Commit

- RetroArch: 1.19.1

### Environment information

- OS: linux arm 32bits
- Compiler: 1.19.1 for arm7

**Comment by zoltanvb** [comment]
I assume this is fixed by #17105 ?

**Comment by Ninoh-FOX** [comment]
Oh, yes... Sorry
