### ISSUE TITLE
SaveRAM needs to have a default autosave interval

### ISSUE THREAD

**Issue by XorOwl** [libretro/RetroArch#17128]
## Description

Retroarch, by default, appears to not save any data to disk, such as save states and memory card files, until you "safely exit" Retroarch.
This means that crashes after extended play sessions, or using devices with a sleep mode like a Switch, all your data is lost with no means of recovery. Any hiccup in the devices performance can cause catastrophic data loss.
Reading elsewhere, it appears like this was somehow a deliberate decision, but i think a very bad one. The average user is not going to understand this esoterica, and needing to perform these steps. Most people will save their game, and believe it has been written to disk, not that it's floating in memory still.

SaveRAM needs to be default on, even if it's saving interval is very long, 1 minute, 5 minute, 30 minute, it doesn't matter, but something must be turned on by default. 

### Expected behavior

Retroarch to actually save data to disk occasionally, instead of holding everything in volatile memory

### Actual behavior
retroarch will dump all data from the entire session if it is not exited properly, and if a crash or power loss occurs, all data in the session is lost

### Steps to reproduce the bug

Install Retroarch
Play game for 40 hours
get crash
loose all 40 hours of progress, as all save files and save states are missing or corrupt

### Bisect Results

This issue:
https://github.com/libretro/RetroArch/issues/16237
Implies this has been going on since issue #4837
this apparently has always been the case

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.19.1
git version 9c7919d 
build date oct 18 2024

### Environment information

- OS: Switch/Hecate/Atmosphere
- Compiler: not a local build, but it's listed in options as GCC (11.1.0) 64-bit

**Comment by cmitu** [comment]
> Retroarch, by default, appears to not save any data to disk, such as save states and memory card files, until you "safely exit" Retroarch.

It's disabled only on specific platforms, like SBC where storage wearing by writing too often is a concern. It's enabled by default on [most](https://github.com/libretro/RetroArch/blob/cb7cd6ef3b7f021e6e8f4a29ec9de514964a7132/config.def.h#L1292-L1300) platform, with a 10 sec autosave interval.
You can, of course, enable it from the settings by setting an non-zero interval.

**Comment by XorOwl** [comment]
I see! Thanks for the clarification!

So the switch is considered a SBC by the back end. If one wanted a switch port that defaulted to something expected, we would either need to make the system spoof something else, or update the code to include the switch condition. 

What would be the recommended path to have a device registered as a different category?
Would there be any chance of a third condition, where the autosave interval was very long, for a sort of middle ground on some devices? something like saving every 5 minutes on devices with SD cards for example....

**Comment by cmitu** [comment]
> What would be the recommended path to have a device registered as a different category? 

Not sure what the Switch build options are, maybe something similar to the _Dingus_ platform definition is available and can be added to the list of platforms for which the `autosave_interval` is non-zero.

> Would there be any chance of a third condition, where the autosave interval was very long, for a sort of middle ground on some devices? something like saving every 5 minutes on devices with SD cards for example....

Maybe, but since it's configurable maybe it's easier for a platform package maintainer to set these things in the configuration file included in the distributed package ?

**Comment by XorOwl** [comment]
I see! So it can be handled at the distribution level.
Thanks for taking the time to explain this. I'll be looking into my upstream, or making my own distribution with better default configurations.
