### ISSUE TITLE
(MacOS + Windows 11) Since 26 October Nighlty: enabling HDR turns output 90° counter-clockwise

### ISSUE THREAD

**Issue by estefan3112** [libretro/RetroArch#17125]
## Description

Since the 26 October 2024 nightly build (MacOS Universal and Windows 64), the screen of all vertical arcade games is turned 90° degree counter-clockwise IF you enable HDR. I tested this in FinalBurn Neo, MAME (current) and MAME 2003 (regular and plus) with identical behavior.

Disabling HDR provides a correct output. The latest stable Retroarch build and the 25 October 2024 nightly build does not provide this behavior.

I identified the error by switching back to a clean retroarch.cfg, and this option change made the difference.

### Steps to reproduce the bug
(tested only on Macs and Windows 11)
1. Download a nightly build as of 26 October 2024 or later, install FinalBurn Neo
2. In a clean retroarch.cfg, activate HDR and save the config
3. Launch a vertical game, such as 1942 or amidar (no shader needed)
4. The output is flipped 90 degrees anti-clockwise.
5. Close and de-activate HDR, launch, correct output.

### Version/Commit
Retroarch Nightly build as of 26 October 2024 

### Environment information
MacOS Sonoma 14.7, Windows 11

**Comment by estefan3112** [comment]
<img width="800" alt="Bildschirmfoto 2024-10-27 um 11 28 13" src="https://github.com/user-attachments/assets/3cf77e09-563c-45f4-8a5e-498b147a6c30">
<img width="750" alt="Bildschirmfoto 2024-10-27 um 11 29 11" src="https://github.com/user-attachments/assets/bd5f1937-c55e-49da-a58a-19a781306a3a">

**Comment by warmenhoven** [comment]
Bisect blames #17118.

**Comment by estefan3112** [comment]
I took the extra mile: Same problem in Windows 11 with today's nightly.

**Comment by sonninnos** [comment]
I don't have HDR to test, and have no idea how those changes could affect it.

**Comment by estefan3112** [comment]
Also tested now under iPadOS with an iPad Air3, identical result. Just for the notes.

**Comment by warmenhoven** [comment]
It's as a result of this line:

```
@@ -3804,6 +3804,9 @@ static void vulkan_set_projection(vk_t *vk,
       matrix_4x4_multiply(tmp, rot, vk->mvp_no_rot);
    }
    matrix_4x4_multiply(vk->mvp, trn, tmp);
+
+   /* Required for translate_x+y / negative offsets to also work in RGUI */
+   matrix_4x4_multiply(vk->mvp_no_rot, trn, tmp);
 }
 
 static void vulkan_set_rotation(void *data, unsigned rotation)
```

If I revert that one it works again. I'm also not sure how it would affect HDR.

**Comment by sonninnos** [comment]
Good to know that it is vulkan only then, and that it is not that critical in the big picture, as in that could be just pretty easily removed, but sure would be nice to have a proper fix for both.

**Comment by warmenhoven** [comment]
Yep, that works. Thanks.
