### ISSUE TITLE
[HELP] How to config for Xiaomi Android TV?

### ISSUE THREAD

**Issue by BleemIs42** [libretro/RetroArch#17121]
I install RetroArch on Xiaomi Android TV, and I use remote controller open the app, then I can't control it by press `up`, `down`, `left`, `ok`, `back` and `right` to select menu item.
so I want to change the config file `retroarch.cfg` with `input_player1_up/down/left/right` match to the remote controller document value, but still can't work.
what I missed?

Here is the remote controller document: https://dev.mi.com/distribute/doc/details?pId=1329

**Comment by zoltanvb** [comment]
Those keys should already be mapped in a default RetroArch installation, input driver for Android will do the conversion to RetroArch internal codes:
https://github.com/libretro/RetroArch/blob/be92b974d21f6648fc3eb7ac77c41ef023b7f3f8/input/input_keymaps.c#L1469

I can think of 2 options. If you can connect another device temporarily that can navigate in the menu, it is easier:
- try to configure the remote as a controller - there is already autoconfig file for "Xiaomi Remote", but maybe it is a different model: https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/Xiaomi_Remote.cfg
- or, try to define the remote as a physical keyboard device (`input_android_physical_keyboard`) in the hope that keymaps will take effect.

**Comment by BleemIs42** [comment]
@zoltanvb Thanks! I found the `input_product_id` not matched. but I can't find where I can modify it after apk installed. I only find the config file `/sdcard/Android/data/com.retroarch.ra32/files/retroarch.cfg`

**Comment by BleemIs42** [comment]
@Oibaf66 Could you help this? I saw you create the Xiaomi_Remote.cfg in [retroarch-joypad-autoconfig #379](https://github.com/libretro/retroarch-joypad-autoconfig/pull/379)

**Comment by zoltanvb** [comment]
Autoconfig profiles are saved to private storage, and normally it is visible only inside the app. Try changing the controller profile directory in Settings/Directories to a new location.

**Comment by ISeekTruth** [comment]
Issue solved!

I use `adb connect` to TV and trigger the navigation by `adb shell input keyevent [keycode]`, then save the D-pad config in app, it will generate a new config file named `小米蓝牙语音遥控器.cfg`

keycode mapping:
```
Up: 19
Down: 20
Left: 21
Right: 22
Back: 52
Select/Ok: 66
```
`小米蓝牙语音遥控器.cfg`
```config
input_driver = "android"
input_driver = "android"
input_device = "小米蓝牙语音遥控器"
input_device_type = "remote"
input_device_display_name = "小米蓝牙语音遥控器"
input_vendor_id = "10007"
input_product_id = "12984"

input_up_btn = "19"
input_down_btn = "20"
input_left_btn = "21"
input_right_btn = "22"

input_a_btn = "4"
input_b_btn = "23"

input_start_btn = "23"

input_up_btn_label = "Up"
input_down_btn_label = "Down"
input_left_btn_label = "Left"
input_right_btn_label = "Right"

input_a_btn_label = "Center"
input_b_btn_label = "Back"

input_start_btn_label = "23"
```

**Comment by zoltanvb** [comment]
Good thinking! Glad you got it solved.

**Comment by WongPaul** [comment]
@ISeekTruth 请问具体是怎么解决的？配置文件.cfg应该放在哪个目录？文件名是否有要求？目前在电视上进RetroArch应用，按遥控器上的方向键无效，并提示：XIAOMI Smart TV IR Receiver未配置（13975/1），使用备用设置。

**Comment by ISeekTruth** [comment]
> [@ISeekTruth](https://github.com/ISeekTruth) 请问具体是怎么解决的？配置文件.cfg应该放在哪个目录？文件名是否有要求？目前在电视上进RetroArch应用，按遥控器上的方向键无效，并提示：XIAOMI Smart TV IR Receiver未配置（13975/1），使用备用设置。

@WongPaul  方向键无效是没有配置, 请使用 `adb shell input keyevent [keycode]`, keycode 是上下左右的键值, 可以参考下面这个试试, 不对用其他数字试试
```
input_up_btn = "19"
input_down_btn = "20"
input_left_btn = "21"
input_right_btn = "22"
```
进入控制器配置, 完了保存会自动生成配置文件. 请仔细看前面的解决流程.
官方文档在这 https://docs.libretro.com/guides/controller-autoconfiguration/#generating-a-joypad-profile

**Comment by WongPaul** [comment]
@ISeekTruth 好的，感谢回复！我再试一试。
