### ISSUE TITLE
[iOS] AltStore/SideStore JSON is malformed

### ISSUE THREAD

**Issue by DJtheMan2101** [libretro/RetroArch#17161]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The buildbot contains a JSON file (https://buildbot.libretro.com/nightly/apple/ios-arm64/altstore.json) that can be added as a "source" in the iOS apps AltStore and SideStore, allowing the nightly build of RetroArch to be sideloaded without manually downloading its IPA file.

Currently, there are errors in the formatting of the nightly JSON file that prevent it from being loaded in the two apps. Compared to the stable JSON (which still works), the "bundleIdentifier" and "minOSVersion" fields appear to have extraneous new lines, affecting the structure of the text.

### Expected behavior

I should be able to add the link as a source in AltStore/SideStore.

### Actual behavior

I receive the following error from SideStore:
![IMG_1047](https://github.com/user-attachments/assets/16fce5c6-c29e-4908-ba46-11940e324bbe)

The JSON for the stable build (https://buildbot.libretro.com/stable/altstore.json) still works as usual.

### Steps to reproduce the bug

1. Copy the link to the JSON file from the buildbot.
2. Open SideStore, then go to "Browse > Sources > +"
3. Paste the link into the textbox.
4. Receive an error about the JSON.

### Bisect Results

I last had version 3c93054f from September 2, 2024 installed before noticing the issue, so it started occuring sometime after that.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.19.1

### Environment information

- OS: iOS 17.7.1
- Compiler: N/A

**Comment by warmenhoven** [comment]
I believe this is fixed now.

**Comment by warmenhoven** [comment]
It's built by a packaging script in the gitlab CI infrastructure. Unfortunately that repo is protected or I'd link to the change there.
