### ISSUE TITLE
[PSTV/Vita] Analog L2/R2 does not work using a Dualshock 3

### ISSUE THREAD

**Issue by techsrus** [libretro/RetroArch#17162]
## Description

Trying to manually remap for analog L2/R2, but there are no working axis numbers that maps the Dualshock 3's analog triggers to RetroArch on PlayStation TV.

### Expected behavior

Should be able to map the Dualshock's L2 and R2's axis numbers to "input_l2_axis" and "input_r2_axis" and get the pressure sensitive triggers, as it says in the libretro document.

### Actual behavior

I've tried axis numbers up from -0 to -40 (+axis numbers got the buttons stuck on PC, I tried + on vita as well) and none seem to be the ones attached to L2 and R2 on the Dualshock 3 for the Playstation TV (it is supported).

### Steps to reproduce the bug

1. PlayStation TV with genuine Dualshock 3
2. Configure the RetroPad Binds with the Dualshock 3
3. Save the controller profile
4. Must manually edit the config file to get around the [Analog L2/R2 remapping bug](https://docs.libretro.com/guides/controller-autoconfiguration/#manual-analog-l2r2-remapping)
5. You can observe that L2 and R2 analogs are working using [reVita](https://github.com/MERLev/reVita). When enabled press Start+Square to open up the menu, go down to Developer and then Show buttons.

### Bisect Results

This issue exists on PC with a workaround, but I guess hasn't come up yet for the Vita version. By mapping any other analog axis like the Right Analog stick to L2 or R2, I found that I was able to get the the intended analog function to come from RetroArch. So it's just RetroArch not being able to bind to the L2 or R2 analog axis.

On PC I was easily able to fix it with the manual remap for dinput, and I think since RetroArch has to define what Vita inputs are seen through its 'vita' input driver, maybe it still needs the axes for L2 and R2 to be defined before I am able to manually remap it.

[File I believe is relevant (vita input driver)](https://github.com/libretro/RetroArch/blob/master/input/drivers_joypad/psp_joypad.c)

### Version/Commit

- RetroArch: Version 1.19.1

### Environment information

- OS: Playstation TV
- Compiler: GCC (10.3.0) 32-bit

Thank you.

**Comment by zoltanvb** [comment]
The guess sounds about right, L2/R2 analog values are not mapped, they are just read from the on/off button structure:
https://github.com/libretro/RetroArch/blob/bb808dfc699eac406fb98ff4d1efab5fe844e05d/input/drivers_joypad/psp_joypad.c#L341

Now, it may be possible to get the analog value, using the dedicated `lt/rt` part of the [structSceCtrlData](https://docs.vitasdk.org/group__SceCtrlUser.html#structSceCtrlData). I do not have PSTV, but if you are willing to install a few test builds, maybe it can be achieved.

**Comment by techsrus** [comment]
I'll be glad to test!

**Comment by zoltanvb** [comment]
[retroarch_vita.zip](https://github.com/user-attachments/files/17787934/retroarch_vita.zip)
Here's a test build with pcsx_rearmed. L2 is mapped to axis 4, R2 is mapped to axis 5.

**Comment by techsrus** [comment]
This one got further than the previous one but this time it crashes when launching the game, like the nightlies. It seems that it was caused by the pcsx self as noted by the error message. I uploaded the crash dump file, if it helps.

[psp2core-1732007466-0x0000be3397-pcsx_rearmed_libretro.self.psp2dmp.zip](https://github.com/user-attachments/files/17813463/psp2core-1732007466-0x0000be3397-pcsx_rearmed_libretro.self.psp2dmp.zip)

**Comment by zoltanvb** [comment]
Here is one try that is build with stable RA (1.19.1 version):
[pcsx_with_stable.zip](https://github.com/user-attachments/files/17966627/pcsx_with_stable.zip)

**Comment by techsrus** [comment]
[psp2core-1733045894-0x0001b82ed7-pcsx_rearmed_libretro.self.psp2dmp.zip](https://github.com/user-attachments/files/17968446/psp2core-1733045894-0x0001b82ed7-pcsx_rearmed_libretro.self.psp2dmp.zip)

I was surprised it crashed! There is also a weird problem that happened in this one that doesn't happen in actual 1.19.1. From what I can gather, it's that having a saved controller profile/autoconfig file makes it so that on boot or restart, no inputs are registered for some reason. A few ways I found that can make it so I can move around again are: turning the controller off and on, unplugging it from usb and making it going into wireless (causing disconnect and reconnect like off and on), opening RA and immediately turning of the controller then turning it on after the ports are loaded, and finally switching from player 1 to player 2 back to player 1.

**Comment by zoltanvb** [comment]
One more attempt. This one does load for me, I built the pcsx_rearmed core from early June as somewhere down the line it has got some changes which cause it to crash, but let's focus on 1 thing first.
[test3.zip](https://github.com/user-attachments/files/18137161/test3.zip)

**Comment by techsrus** [comment]
You nailed it. Everything just works. The game boots. The analog L2/R2 works like a charm. I even found out how to set the analog buttons without having to manually edit the file by using reVita. There is one thing to note and that is that the retroarch.cfg made from the stable release was not compatible with this one, it was giving me the controller issue I mentioned in my last comment, but if I deleted that and had your build make the fresh retroarch.cfg, everything worked as intended, inputs working at all times. Great job!

**Comment by zoltanvb** [comment]
PCSX related problem investigated a bit, let's see if it gets fixed.
https://github.com/libretro/pcsx_rearmed/issues/856
