### ISSUE TITLE
(Menu/Inputs) Being able to bind input_menu_toggle to a controller button

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#1717]
Hello,

It would be nice to be able to bind `input_menu_toggle` to a controller button, for instance on a Xbox360 controller you could press the central X button to open and close the menu.

Is that possible ? If yes, how ? I've tried to do this (where 8 is the controller button id) :
`input_menu_toggle = "8"`

But RA says that 8 is not a valid key ; I checked and RA excepts a keyboard key, how can I make it a joypad button ? I didn't find in the code where is the "this config entry is for a button and this config entry is for a keyboard key".

Thanks !

**Comment by twinaphex** [comment]
Use

input_menu_toggle_btn

**Comment by natinusala** [comment]
It works, thanks
