### ISSUE TITLE
[Data loss] Mario Tennis save exception

### ISSUE THREAD

**Issue by Aepoh** [libretro/RetroArch#17172]
Mario Tennis 64 and Mario Tennis GBC are both called Mario Tennis and both save to Mario_Tennis.srm indiscriminately. What this means is if you play Mario Tennis 64 and then play Mario Tennis GBC Retroarch will overwrite your 64 save with the GBC one, and vice versa. If you load both games back to back you will lose all your data for both games in this way. This is a fringe scenario that needs special attention specifically for these two games. I recommend simply changing the way Retroarch names the saves for these two games specifically.

**Comment by Aepoh** [comment]
This same issue would apply to Mario Golf 64 and GBC as well.

**Comment by cmitu** [comment]
There are a lot of games with identical names that would lead to an identical SRM file. However, by default, RetroArch saves the `.srm` files inside a folder named after the core name, this behavior being controlled by the 'Sort Save files' option.

Did you specifically modified the location of the save files or disabled the sorting option ?

**Comment by Aepoh** [comment]
_**I**_ didn't. However I am using EmuDeck on my Steam Deck so perhaps it is an issue with EmuDeck's configuration of RetroArch and I should try crossposting to their repo.

**Comment by cmitu** [comment]
> However I am using EmuDeck on my Steam Deck so perhaps it is an issue with EmuDeck's configuration of RetroArch and I should try crossposting to their repo.

You should and also close this issue.
