### ISSUE TITLE
[Settings][Video][Scaling] Custom Aspect Ratio (Width and Height) not showing.

### ISSUE THREAD

**Issue by Langerz82** [libretro/RetroArch#17176]
## Description

When try to set:
Settings, Video >> Scaling, Apect Ratio value Custom, 
Aspect Ratio (Width) and Aspect Ratio (Height) are NOT showing.

### Expected behavior

Settings, Video >> Scaling, Apect Ratio value Custom, 
Aspect Ratio (Width) and Aspect Ratio (Height) to show in Config Values.

### Actual behavior

Settings, Video >> Scaling, Apect Ratio value Custom, 
Aspect Ratio (Width) and Aspect Ratio (Height) are NOT showing.

### Steps to reproduce the bug

1. Settings, Video >> Scaling, Apect Ratio value Custom.
2. Asepct Ratio Width and Height should appear.

### Version/Commit
OS: EmuELEC Version 4.8 TEST Version.

Retroarch Version:
Version: https://github.com/libretro/RetroArch/commit/1e1b24c35996436e6cf0fe50ec046e2e03a0dbfa

Did not occur from in last Version bump:
Version: https://github.com/libretro/RetroArch/commit/37ccb5c6e0d63228823e18883dbc298f2828a0a2

Hardware:
Beelink GT King Pro (Amlogic s922x 4GB RAM)

**Comment by sonninnos** [comment]
Shows fine here with current version, and there is no reason to test with that months old version anyway, and there is also no reason why that old version would be any different with these menu items.

![retroarch_2024_11_08_21_25_51_496](https://github.com/user-attachments/assets/137ecf19-11f7-4f99-9d65-33e1bef113c3)

**Comment by Langerz82** [comment]
The version is only about 5-6weeks old lol. But I wonder why it's not showing, maybe it's something in my config file....

**Comment by sonninnos** [comment]
The only reason I can see from the code that is able to hide them is this entry tag `SD_FLAG_LAKKA_ADVANCED`, which should not even exist here, since they are hidden based on the current selection.. So make sure "Show Advanced Settings" is enabled.

**Comment by Langerz82** [comment]
@sonninnos 
Ah wish I read your reply earlier haha. Yes the issue was menu_show_advanced_settings = "false", menu_show_advanced_settings = "true" fixed the issue. Thanks heaps, I will close the issue as it does not need to remain open. 

All the best and cheers!!
