### ISSUE TITLE
[libretro] How long to display a frame?

### ISSUE THREAD

**Issue by matthewbauer** [libretro/RetroArch#1720]
I've been working on Node.JS bindings for libretro over at [node-retro](http://github.com/matthewbauer/node-retro). Mostly it's been working fine, but I've run into some issues with timing. Right now, I'm just targeting SNES but I plan to add more core support later.

Basically, I've got a timer in C that runs a frame ever n milliseconds. n is calculated based by taking the FPS number in getSystemAVInfo and dividing 1000. At first, I thought this was working okay, but recently I've noticed that it is much faster than other emulators. I've looked through RetroArch, but haven't been able to figure out how it determines how long to display a frame. I don't know if this is the right spot to ask this but I'm hoping you all can give some pointers.

**Comment by Alcaro** [comment]
Yeah, that's not going to work very well. Rounding to milliseconds means your framerate is going to end up at either 62.5 or 58.8. Multimedia applications like this generally don't like timer-based loops.

A better solution would be to push audio and/or video through a blocking interface.

For audio, AudioContext.createBufferSource() seems inappropriate; not only are you creating about eight buffer sources per frame (Snes9x calls the audio callback once per 64 or 65 samples; given a sample rate of 32040.5, this yields ~500 calls per second), but I suspect they'll play all over each other in ugly ways. The docs on MDN are quite unfinished, but I think AudioContext.createMediaStreamDestination() is the one you want.

For video, there is no vsync in WebGL; for browsers, I'd suggest requestAnimationFrame, but I'm not sure if Node supports that. Alternatively, I've found that syncing on only audio is generally satisfactory.

This will ignore the fps counter, but fps is almost always nearly equal to 60, so vsync will do the right thing. The audio sample rate doesn't care what you do to video, either.

**Comment by matthewbauer** [comment]
Ok, cool.

The reason I was using the timer-based loop was to try to conform to Node's nonblocking APIs. I'm thinking now I'll just have to force blocking.

But, am I correct in thinking that it should display 60fps means that retro_run() should be called 60 times in one second?

**Comment by Alcaro** [comment]
>Node's nonblocking APIs

Nonblocking is a good idea for event-driven server stuff, but makes less sense for things with rapid, predictable and long-running timers.

>But, am I correct in thinking that it should display 60fps means that retro_run() should be called 60 times in one second?

Yes, that is correct. I don't think it's guaranteed, but everything I know of calls the video callback once per retro_run.

The official support channel for this kind of activities is Freenode, #libretro; it doesn't really belong in issues. I'll close this one (this is not an issue with RetroArch, unless you're implying it needs more comments or something), but I'll respond if you prefer to post here.
