### ISSUE TITLE
Fix the flickering screen on fullscreen game loading and unloading

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#1722]
Hello,

When I run RA in fullscreen and load a game, there is a few flickering frames where we can see the desktop and the windows behind RA before the game actually starts. This is the same when I unload the game (using `EVENT_CMD_UNLOAD_CORE`).

RA is using `gl` as a video driver and `glx` as a context driver.

I know it's not important, but could you fix this ?

**Comment by fr500** [comment]
I think the window is destroyed and re-created so it's probably not trivial to fix

**Comment by natinusala** [comment]
I looked at the code, I think the part to look for is ‘gfx_ctx_glx_set_video_mode‘ in glx_ctx.c, this is where the X window is (re)created

**Comment by RobLoach** [comment]
Could you test again, and re-submit a new issue with the issue template if it persists? Thanks!
