### ISSUE TITLE
[Feature Request] Limit the number of Save State Thumbnails according to Max Auto-Increment Save States

### ISSUE THREAD

**Issue by 1nert0rdnance** [libretro/RetroArch#17230]
## Description

Saved State thumbnails associated with the oldest auto-increment save state are not deleted along with the save state file.

Possible solution would be to add the oldest save state deletion logic to the PNG files as well so it also follows the *"Maximum Auto-Increment Save States to keep"* setting.

### Steps to reproduce

1. Configure Retroarch settings:
	- Save State Thumbnails: **ON**
	- Increment Save State Index Automatically: **ON**
	- Maximum Auto-Increment Save States to keep: **10**
1. Launch a game and create save states until you reach the "Max Auto-increment states to keep"
	- The saves folder at this point will contain *10 save state files*, and 1*0 thumbnail .png files*.
1. Trigger another save state
	- The number of *save state files will remain 10* due to the max auto-increment setting, but *there are now 11.png files* since the oldest thumbnail was not deleted alongside the save state file.

### Expected behavior

The thumbnail.png associated with the oldest save state should be deleted along with the oldest save state.

```
Game.state3
Game.state3.png
Game.state4
Game.state4.png
Game.state5
Game.state5.png
```
### Actual behavior

The thumbnails are not deleted, leaving a bunch of .png files in the save state directory. 

```
Game.state0.png
Game.state1.png
Game.state2.png
Game.state3
Game.state3.png
Game.state4
Game.state4.png
Game.state5
Game.state5.png
```
### Version

- RetroArch: 1.19.1

### Environment information

- Device: Anbernic RG35xxH
- OS: muOS 2410.1 BANANA (Linux 4.9.170)

**Comment by zoltanvb** [comment]
Thanks for reporting. This has been solved with https://github.com/libretro/RetroArch/pull/16836 , in August, so any recent nightly build should have the fix. There was no stable version since that time, but whenever it comes, this fix will also be included.

**Comment by 1nert0rdnance** [comment]
Oh, I should've did a more thorough search through the past issues before creating this.

Thanks! That's good to hear.
