### ISSUE TITLE
Lots of issues

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [libretro/RetroArch#17244]
There are a lot of weird things that have happened since the latest update for nightly altstore RetroArch. No game icons, slow controller loading, and improper rom scan names. Is there a reasoning for that and can it be fixed in a later nightly build?
https://github.com/user-attachments/assets/ecc53e62-ad5f-41af-bd44-e77047ea035e

**Comment by hizzlekizzle** [comment]
most of that is related to the thumbnail server being down. You can disable on-demand thumbnail loading and a lot of it should improve.

**Comment by gouchi** [comment]
@Iamthebestintheworld222 Please close this issue as there is a workaround and an [issue](https://github.com/libretro/RetroArch/issues/17242) has already been opened.

Thank you.

**Comment by gouchi** [comment]
@Iamthebestintheworld222 Yes for now the workaround is disabling thumbnail updates.
