### ISSUE TITLE
core remapping messing up controls for p2, p3, etc

### ISSUE THREAD

**Issue by entitled44** [libretro/RetroArch#1726]
tested: nestopia
description: using core input remapping options for players other than 1 cause controls to be messed up for such player. The file looks ok, bindings are exactly the same as P1 but the actual inputs are all over the place

**Comment by fr500** [comment]
Hmm, can you test if this happens before https://github.com/libretro/RetroArch/commit/0cd7562fb86f8a477d3e9d04022be9ad0da9425b ?

**Comment by fr500** [comment]
confirmed, it was that commit 
@ToadKing it seems to load manually generated remap files correctly and P1 works fine indeed, but for some reason remapping for P2, P3, etc is acting weird. Even without remapping, the labels for anything other than P1 are incorrect in the input remapping menu

**Comment by fr500** [comment]
Fixed by
https://github.com/libretro/RetroArch/commit/c7a6b85817b2e3b5d738e7fb19dd644795d15fc4
