### ISSUE TITLE
RetroArch 1.0.0.3 on Ubuntu 15.04 64bit: Xbox 360 wireless controller crashes RetrochArch

### ISSUE THREAD

**Issue by melo0187** [libretro/RetroArch#1727]
Hey there,

I installed RetroArch 1.0.0.3 from the official stable ppa on Ubuntu 15.04 64bit. My Xbox 360 wireless controller (using xboxdrv) is being detected and I can bind all keys in rgui. However after binding the keys, things get strange. I can start navigating around rgui with the controller, but not as expected. The button on the right for example enters a menu entry instead of going up one menu. Also pressing the button on the left reproducibly crashes (or maybe just quits?) both rgui and RetroArch cores (tested with snes9x_libretro.so).

No matter what input/joystick driver I choose or whether I use just Retropad or Retropad w/ analog, the problem with messed up mapping and crashing/quitting the entire thing by pushing the left button persists.

I switched log_verbosity to true in retroarch.cfg and run retroarch from terminal. There are several outputs, few errors which seem to be handled by fallbacks, but nothing obviously related to the problem.
Find the output in this gist: https://gist.github.com/melo0187/ef0a030be46d18bb25c3

I believe my controller and the xboxdrv setup is fine, since it works in Steam Big Picture and several Steam games, EmulationStation and Dolphin-Emu.

Any help is much appreciated and I would be glad to provide further information to help fix this.

**Comment by sergiobenrocha2** [comment]
It's a know issue, take a look at libretro/retroarch-joypad-autoconfig#38

RetroArch thinks it's another joypad, which already has a config file.

**Comment by melo0187** [comment]
@sergiobenrocha2 Thanks for the reply. 
So I read issue #38, but I'm not sure if I understand correctly. From what I got it seems there is no solution to this problem yet or did I just misinterpret what your wrote in #38? I have a wireless receiver and 1 wireless xbox 360 controller and would be glad to test and help however I can to get this working.

**Comment by sergiobenrocha2** [comment]
Man, don't reference another issue in this one...

The issue is that retroarch doesn't know to differentiate your receiver from another one. I already tried here, it's a mess.

**Comment by melo0187** [comment]
Sorry, for referencing the wrong issue. I did correct the references.

So there is no solution to this problem apparently... pitty.

**Comment by sergiobenrocha2** [comment]
There is, config it yourself on Settings --> Input Settings

**Comment by melo0187** [comment]
But that is what I did! 
I start RetroArch/rgui, go to Settings --> Input Settings, bind everything for my controller, which seems to work fine, but after binding things get weird. The bottom button gets me up one menu hierarchy instead of entering a menu, the right button enters the highlighted menu entry and the left button just crashes/quits retroarch...

**Comment by fr500** [comment]
Reopen this if it's still an issue but I can't reproduce

**Comment by Marc34** [comment]
Unresponsive on Linux Mint 17.3. Keyboard is desactived when the controller is connected. This controller works fine with all other emulators.

**Comment by sergiobenrocha2** [comment]
I don't know what you guys are doing, it's working here (kernel 3.13). Are you using the xboxdrv? Don't use that, you don't need it.

**Comment by Marc34** [comment]
I didn't know that. Works fine now. It is probably difficult to obtain this information, in particular when English is not your native language. So, thank you very much for your answer that was very helpful.

**Comment by fr500** [comment]
the problem might be if you're still on 1.0.0.3
