### ISSUE TITLE
XMB CRASHES WHEN TRYING TO LOAD CONTENT

### ISSUE THREAD

**Issue by eiidrovo** [libretro/RetroArch#17287]
### Is there an existing issue for this?

- [X] This is a bug in RetroArch frontend
- [ ] I have searched the existing issues

### Description

Arch linux install with assets from AUR.
change interface to xmb from config driver options
Click on load content
Program closes.

### Expected behavior

To load content keeping the xmb active, this problem only occurs with xmb gui.

### Steps to reproduce the bug

Arch linux install with assets from AUR.
change interface to xmb from config driver options
Click on load content
Program closes.

### Version/Commit

1.19.1

### Check in the nightly version

I don't know

### Platform & operating system

Arch Linux 6.12.6

**Comment by LibretroAdmin** [comment]
When you go to Information -> System Information, what GIt version and Build Date does it show?

**Comment by gouchi** [comment]
@eiidrovo 

You should provide some [log](https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-linux).

> Arch linux install with assets from AUR.

Why do you need to install old [assets](https://aur.archlinux.org/packages/retroarch-assets-git) from AUR ? Why don't you use the one from the [main repository](https://archlinux.org/packages/?q=retroarch-assets) ?

To check [nightly build](https://buildbot.libretro.com/nightly/linux/x86_64/RetroArch.7z) you can try to use AppImage.

Thank you.

**Comment by eiidrovo** [comment]
> When you go to Information -> System Information, what GIt version and Build Date does it show?

This version:
![image](https://github.com/user-attachments/assets/35247e8f-591d-42a1-9971-2f5dd6366f13)

**Comment by eiidrovo** [comment]
> @eiidrovo
> 
> You should provide some [log](https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-linux).
> 
> > Arch linux install with assets from AUR.
> 
> Why do you need to install old [assets](https://aur.archlinux.org/packages/retroarch-assets-git) from AUR ? Why don't you use the one from the [main repository](https://archlinux.org/packages/?q=retroarch-assets) ?
> 
> To check [nightly build](https://buildbot.libretro.com/nightly/linux/x86_64/RetroArch.7z) you can try to use AppImage.
> 
> Thank you.

Oh thank you, the problem was the assett, I'm ysing now the ones from the repository and that fixed the problem.
