### ISSUE TITLE
Override shader preset using --set-shader no longer takes effect?

### ISSUE THREAD

**Issue by theflyingape** [libretro/RetroArch#17285]
### Is there an existing issue for this?

- [X] This is a bug in RetroArch frontend
- [X] I have searched the existing issues

### Description

--set-shader does not override any automatic shader preset.

### Expected behavior

**--set-shader** says "Effectively overrides automatic shader preset" and indeed it had been working great for when my "attract mode" using an old flickering screen shader.  Something very recently has changed.

### Steps to reproduce the bug

The cfg contains `auto_overrides_enable = "false"` and I launch with:
`retroarch -v --set-shader=/retroarch/shaders/shaders_slangp/film/technicolor.slangp -L mame duckhunt.zip`
Output shows example:
`[INFO] [Shaders]: Specific shader preset found at "/home/pi/.config/retroarch/config/MAME/MAME.slangp"`
... or if I reluctantly remove MAME.slangp, it drops to:
`[INFO] [Shaders]: Specific shader preset found at "/home/pi/.config/retroarch/config/global.slangp"`

### Version/Commit

RetroArch 1.19.1 (Git 7887719d42)

### Check in the nightly version

I don't know

### Platform & operating system

Linux aarch64

### Affected Cores

all

### Environment information

Attempted to use glcore and vulkan to no effect.

**Comment by hizzlekizzle** [comment]
I believe this is the offending commit: https://github.com/libretro/RetroArch/commit/b3e5c578b38603362de9e88c41e8602907bbf4b6

Confirmation would be great, if you can swing it.

**Comment by LibretroAdmin** [comment]
This should fix it -
https://github.com/libretro/RetroArch/commit/95f0297e7f9ff370cd9807125a280f6248d77b04

**Comment by theflyingape** [comment]
:100:  - thank you!
