### ISSUE TITLE
Window closes when using vulkan

### ISSUE THREAD

**Issue by Ar4m1s** [libretro/RetroArch#17297]
### Is there an existing issue for this?

- [X] This is a bug in RetroArch frontend
- [X] I have searched the existing issues

### Description

A line which initializes a variable is missing in gfx/video_driver.c/video_driver_frame. After playing games or using the menus the window closes usually with the log that the swapchain was destroyed followed by a lot of log messages saying got 3 swapchain images. The process continues to run just without a window. Other device crashes with bogus present modes.

### Expected behavior

Either game window or interface window should not close when doing certain actions.

### Steps to reproduce the bug

Use rgui menu theme, switch to ozone in settings and restart.
Another way is to use the xmb theme and move downwards in the main menu.

### Version/Commit

1.19.1 (Git b8c9665753)

### Bisect Results

92f134fb8753bd8785a4051b281c5abc580a7051 is the first bad commit

### Check in the nightly version

I don't know

### Platform & operating system

Linux x86_64

### Environment information

Wayland compositor: dwl
Video driver: vulkan

### Relevant log output
[retroarch.log](https://github.com/user-attachments/files/18264484/retroarch.log)

**Comment by hizzlekizzle** [comment]
thanks for tracking this down!
