### ISSUE TITLE
[Android] Please re support Directinput mode gamepad

### ISSUE THREAD

**Issue by duskgao** [libretro/RetroArch#1731]
My Xinput mode gamepad work fine with RetroArch android nightly build,

But all my Directinput mode gamepad only work in GUI not in game,PLZ help ,these gamepad works in offical v1.0.0.2

**Comment by fr500** [comment]
So you want dinput on android? are you sure that's a thing?

**Comment by duskgao** [comment]
@fr500 thx for your reply:)

I don't know the differents of Xinput and DirectInput,but my android handhelds (GPD G58/Q9) only have DirectInput mode.

Directinput mode gamepad only work in android GUI not in game(RGUI XMB glui) -- this bug was found by many user
eg.http://libretro.com/forums/showthread.php?t=1806&p=23486&viewfull=1#post23486

PLZ help us~~~~

**Comment by twinaphex** [comment]
What? DirectInput/XInput on Android?

Are you really sure this is Android you're talking about and not a Windows 8 tablet or something?

**Comment by duskgao** [comment]
@twinaphex  Sorry my bad english.

I have a usb gamepad can switch between DirectInput/XInput mode,I use it on an android TVbox with Retroarch.

In XInput mode,the gamepad be identified as a Xbox360 controller and work fine.
But in DirectInput mode ,the gamepad be identified as a USB controller,and only work in android GUI not in game(RGUI XMB glui).

**Comment by duskgao** [comment]
fixed by @daveshah1  #1884

**Comment by djhyperdrum** [comment]
Hello, I have a tv box mxq rockchip board and I have the same problem, the xinput controls work well, already the directinput no, did not understand how this helped you, could explain?
