### ISSUE TITLE
[Android] ScummVM Core - almost usable (controller sensitivity)

### ISSUE THREAD

**Issue by harlekinrains** [libretro/RetroArch#1733]
Today I tried out the ScummVM Core on Retroarch (Android nightly) and its very close to functioning with only two minor issues that holds it back.

ScummVM uses its own GUI overlay, which is supported in the RetroArchs implementation - but the emulated mouse sensitivity for Controller Analog Stick movement is WAY to high in the ScummVM GUI overlay. So high in fact, its unusable. In game - once its launched, its actually almost perfect. (A minor edition that could be added is to modify analog stick emulation in game as well, to make the movement even slower, when X (Xbox layout), or a trigger is held (movement modifier).)

edit: The second issue turns not to be one - the save path can be changed in the ScummVM Overlay and saving/loading works from then on. ~~[The second issue is, that the ScummVM Core fails to save the games - Scummvm has an auto save feature enabled by default, so just play a game and wait for it to pop up an error message (after a couple of minutes).]~~

The rest of the implementation already seems to work just fine - with many games that would open up and be playable - if this one bug was squished. If someone could put this up on a priority list - its literally almost usable as is.

**Comment by harlekinrains** [comment]
Might be related:
https://bbs.archlinux.org/viewtopic.php?id=122425

**Comment by fr500** [comment]
Please reopen this on the scummvm repo
