### ISSUE TITLE
(iOS) MFI gamepad not responding on latest build

### ISSUE THREAD

**Issue by Lodovik** [libretro/RetroArch#1737]
Last month, I downloaded the Libretro-Super, executed the scripts to fetch the iOS files and build the emulators from scratch. My MFI gamepad (Madcatz micro CTRLi) was not recognized. I've tried to remap the buttons in the settings but nothing respond... My gamepad works OK on other apps.

Yesterday, I started from scratch again and redownloaded all the files and the gamepad still does not respond. I'm pretty sure that MFI controllers are one of the first things that get tested. So, I must be doing something wrong.

My current working version of RetroArch is dated March 5th, 2015 and this one works with my gamepad.

Has something changed after this date that would interfere with MFI controllers?

**Comment by twinaphex** [comment]
I cant test MFi gamepads because I dont have one.

**Comment by rasterico** [comment]
MFI controller support is definitely broken in the 1.2 beta build for iOS thats floating round on Cydia, such a shame as the mupen64Plus core is working flawlessly in this version with no graphical glitches whatsoever :( Any chance of an update soon?

**Comment by twinaphex** [comment]
Will be looked at. More iOS developers helping would be VERY HELPFUL though - just saying.

**Comment by rasterico** [comment]
I'm not a developer or coder unfortunately, just a mere mortal reporting bugs! Another bug I've noticed is I can't seem to get the overlay preset to change to n64, every time I load a game it resets back to Retropad default?

**Comment by twinaphex** [comment]
As of this commit - it is possible to bind the MFI gamepad's buttons again from the menu.

https://github.com/libretro/RetroArch/commit/6c6a293388c45261479c9bfaa62cacf9148a2c34

I'll have to add axes support too - that is probably a very quick commit to add after this. If you are in a position to test/compile, please try it out on your end. Tested it with Controllers 4 All and a PS3 pad and it worked.

**Comment by rasterico** [comment]
Awesome work! I have an iMac with Xcode 7 so I'll try and build it later today :) thank you for your speedy effort in getting it fixed :)

**Comment by rasterico** [comment]
getting an error whilst building with Xcode I've posted the log to pastebin below if you can help at all?

Thanks in advance :)
http://pastebin.com/6BKd0CvV

**Comment by rasterico** [comment]
Still haven't been able to build this :( after googling it seems like there maybe extra lines of code that are conflicting but I wouldn't know where to start? Can anyone point me in the right direction please?

**Comment by twinaphex** [comment]
Yeah this seems to be happening ever since Xcode 7.

**Comment by rasterico** [comment]
So how are you guys building it? Obviously you've managed to build it for testing?! It's a bit of a head scratcher!

**Comment by twinaphex** [comment]
No I haven't been able to build it yet. Last time I managed to build it was with the previous iOS version.

I'm getting a bit fed up of having to jump to Apple's hoops each time with their planned obsolescence fetishes everytime a new SDK/IDE rolls out the door. But whatever, I'll torture myself some more for a bit I guess.

**Comment by rasterico** [comment]
Oh I see :( Apple don't make things easy do they? Such a shame as I love their products, I use Xcode 7 as it allows mere mortals like me to build and side load stuff without a fully fledged developers account, hopefully a workaround will be discovered soon :)

**Comment by rasterico** [comment]
Have you managed to sort out the axis as well as the buttons on MFI controllers yet? I still haven't managed to build it but there is now a fully fledged version of Xcode 7 out so I may update the beta I've been using and see if that cures the build problem, if you've tried and are still having issues then could you let me know please as I don't want to update if I don't have to as I know the beta works for building other projects :)

**Comment by twinaphex** [comment]
I think we can close this now.
