### ISSUE TITLE
Retroarch does not work when in a folder containing the character "#"

### ISSUE THREAD

**Issue by SixWingedFreak** [libretro/RetroArch#1746]
I think I brought up this issue a couple years ago and it was fixed, but it would appear it's broken again. I'm using nightly 2015-06-03 but will check with a newer one in a moment. I wanted to move to this new release because of the parameters for shaders!

I use emuControlCenter as a frontend and it creates folders called "#_GLOBAL" and "#_AUTO_UNPACKED" (it would appear there's no way for me to change the unpacked folder name). I always put Retroarch in "#_GLOBAL" as it's my main program. When I do this it cannot read or write to the retroarch.cfg file (loads defaults every time). If I rename "#_GLOBAL" to "_GLOBAL" it works perfectly fine.

When I go to play a rom, when ECC unzips the rom to the "#_AUTO_UNPACKED" folder, some systems (Genesis/genplusgx, Game Boy Advance/vbam to name a couple off the top of my head) won't load the rom and Retroarch crashes. Some systems (NES/nestopia) will load the rom though. Basically it can't parse the "#" character.

Edit: Same behavior w/ nightly 2015-06-04
Edit 2: Same behavior w/ nightly 2015-06-05

**Comment by fr500** [comment]
well, # is now used for archives so yes indeed it's an issue but you're expecting retroarch to cater to your specific use case

**Comment by SixWingedFreak** [comment]
This used to work fine though, around 2014 and prior. I doubt I'm the only person in the world that uses emuControlCenter... probably one of few now, but sure. I don't have the HDD space for Hyperspin and all it's modules -- plus it's not exactly a "fast" way of launching a game -- thus I use eCC. I don't find it unreasonable to expect a program to be able to parse folders with a "#"

**Comment by shad00m** [comment]
I'd be happy to see it fixed as well after confirming in irc that it is indeed a mistake due to "badly programmed compression code".

**Comment by markwkidd** [comment]
This seems to be solved per https://github.com/libretro/RetroArch/issues/3273

**Comment by lasers** [comment]
Close this? No problem loading `WEW#LAD#` here.
```
./Sony - Playstation/WEW#LAD#/WEW#LAD#.bin
./Sony - Playstation/WEW#LAD#/WEW#LAD#.cue
```

**Comment by SixWingedFreak** [comment]
Haven't tested yet, but going to assume it's fixed now. We have [#3273](https://github.com/libretro/RetroArch/issues/3273) and all the reports of it working again. Thank you! Will be fixing my ECC setup when the holiday madness passes. :+1:
