### ISSUE TITLE
Alternative netplay:

### ISSUE THREAD

**Issue by Hydro5** [libretro/RetroArch#1747]
The GGPO-like code for two player netplay is pretty good. But it uses a lot of CPU power, and it can only work for two players. So there should be another kind of netplay, a more standard kind, like what mednafen has. Is this possible?

**Comment by heuripedes** [comment]
RetroArch provides a netplay implementation that is core agnostic, it only depends on working savestate support by the core. Providing a Mednafen-style netplay would require the netplay code to be rewriten and to include per-core code and that's unsustainable in the long run.

The best solution in this case might be exposing the core's own netplay features to the frontend, but that's not yet supported by the libretro api.

**Comment by RobLoach** [comment]
Closing this one for now, if you have a direct idea of how netplay could improve, feel free to re-open with the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md) in place. Thanks a lot.
