### ISSUE TITLE
X86 broken sounds with picodrive and genesis plus gx playing sega cd

### ISSUE THREAD

**Issue by shinemu** [libretro/RetroArch#1756]
There's an issue playing sega cd with picodrive or genesis plus gx on x86,the sounds broken on picodrive especially music and only hear sfx.i play the roms directly without cue but i think it doesn't have problem.so please tell me did i miss something like playing right from the cue or maybe it was x86 problem? Btw i'm using asus zenfone ZE551ML 2.3 ghz 4 gb ram 64 bit lolipop 5.0.i play both on nightly with picodrive and genesis plus and stable with genesis plus but the result still the same..thanks and keep up the good work ^_^

**Comment by shinemu** [comment]
Can't play nintendo 64 with mupen64plus,just give black screen and also make retroarch not responding.broken animation on yabause when load the game with gui on update 2015-6-26...btw can we have compatibility with asus ime? I'm dizzy to remap over and over everytime i play with my ipega :( guys if you think this post the same with other please merged :) thanks

**Comment by shinemu** [comment]
Dear sir,sorry if don't know where to post but if this make thing slower to fix i apologize and please merge with other post so i can report something..btw till now i still can't play a game with mednafen psx and mupen64 core,it can't detect any type of file for psx and crash when i run mupen64 also desmume become laggy very bad now but usually runs fine on old core..i hope it can be fix :) thanks

**Comment by shinemu** [comment]
Reporting...desmume runs alot better now but pcfx and yabause become so laggy

**Comment by shinemu** [comment]
Core issue
- VBA next now laggy/drop performance
- yabause laggy
- Pcfx laggy
 It seems all core becomes laggy now :( but i still put hope on retroarch cuz it was the ultimate multi emulator on the planet..hope it can be fix soon for zenphone user,this is my last report and if you found this unproper please delete the thread :) thanks and keep up the good works!

**Comment by fr500** [comment]
all of these are core issues and should be open in the specific issue trackers
