### ISSUE TITLE
[Wii] Big issue in nightly builds, retroarch crashes every time you go back in menus.

### ISSUE THREAD

**Issue by netux79** [libretro/RetroArch#1757]
As the title said, no matter which menu you get into if you try to go back to previous one the screen blackouts and you need to reset the Wii.

I tested some nightlies from May and by May 15 it was still working fine. The Wii version has a ton of bugs but this one doesn't allow to continue.

**Comment by fr500** [comment]
@ToadKing tested the nightly today and it's working fine for him

**Comment by netux79** [comment]
Did you tried the Settings menu? I think I forgot it is in any of the settings menus...

Also this have been also reported in the forums, not the only one... now, I see there are some changes to the menus yesterday (changes by Toadking) so it may me that it has been fixed.

Let me try today and reported it back. Thanks!!

**Comment by netux79** [comment]
Hi guys,
Were you able to replicate the issue? I think it is still crashing.. please see my EDIT from previous post. Thanks

**Comment by twinaphex** [comment]
@ToadKing could maybe take a look at it once he has his Wii development toolchain setup again on his PC.

**Comment by ToadKing** [comment]
I wasn't able to reproduce it in a nightly build myself but will look at it in a couple days.

**Comment by netux79** [comment]
Great, thanks guys. really appreciated :)
