### ISSUE TITLE
[Android] Scummvm core unusable, because of menu sensitivity issues.

### ISSUE THREAD

**Issue by harlekinrains** [libretro/RetroArch#1758]
Latest nightly.

Menu sensitivity for mouse emulation with a controller is so high - the scummvm menu is not usable at all. This impacts - adding a game, starting a gam, saving a game, loading a game, configuring a game - you know, its at a level where you could ask "why on earth are they still promoting Scummvm support, when they messed up its implementation so spectacularly".

I have brought this to your attention earlier, in a more polite manner - with issue #1733 - and just got  informed, that this issue was closed, because you (user Andrés) found, that it would be a good idea to play the old blame game - where the problem is never your projects responsibility - but should be tackled by the counterpart (Scummvm) - well literally anyone else - BUT retroarch.

Then closed the issue - so no one could comment on it anymore.

Fact is, that Scummvm in their own builds are running the Menu at a low resolution (because mouse emulation was optimized for low resolution games), while Retroarch is actively choosing to run it in the displays resolution (1080p in most cases) - which CAUSES this problem.

So let me but this in a way it is easier to understand for your guys - ITS RETROCARCHS FAULT, ITS RETROARCHS FAULT, ITS RETROARCHS FAULT;

So no - I will not venture out and promote a fix on the Scummvm issue tracker - when it is a implementation issue. You profit from solving it as much as I do - because currently you are implementing a core that is entirely broken. And thats not normal. If you want to remove it out of spite, you are welcome to do so also - but keep your project in a state where a person at least could argue that you are trying out rational decision making.

Before I do anything - I like a comment from you, that you have looked into the issue - and werent able to do what Scummvm does in all their releases - and THEN I might open a ticket with them to implement resolution dependent mouse emulation sensitivity.

Thank you so much.

I hope I was concise enough this time.

**Comment by fr500** [comment]
This is not the correct repository, I closed it because it is not on the correct repository, it's still related to libretro but in the wrong place. 
https://github.com/libretro/scummvm
