### ISSUE TITLE
Linux: windowed mode tries to use the native desktop resolution

### ISSUE THREAD

**Issue by chungy** [libretro/RetroArch#1770]
Running Arch Linux x86_64, using GNOME 3.16 as the desktop.

This makes play pretty much impossible:
![Windowed](https://dl.dropboxusercontent.com/u/13513277/retroarch-windowed.png)

IRC asked for it, my system information screens look like:
![System Info 1](https://dl.dropboxusercontent.com/u/13513277/retroarch-sysinfo1.png)
![System Info 2](https://dl.dropboxusercontent.com/u/13513277/retroarch-sysinfo2.png)
![System Info 3](https://dl.dropboxusercontent.com/u/13513277/retroarch-sysinfo3.png)
![System Info 4](https://dl.dropboxusercontent.com/u/13513277/retroarch-sysinfo4.png)

**Comment by Kivutar** [comment]
Hi, I'm also using GNOME 3.16.2 on Arch x86_64, but I was not able to reproduce this.

**Comment by chungy** [comment]
Using a clean config still produces this problem as of commit 89d8b24 for me.
