### ISSUE TITLE
Adding input_player1_analog_dpad_mode="1" disables dpad on snes controller

### ISSUE THREAD

**Issue by michaelkleinhenz** [libretro/RetroArch#1780]
As described in #609, adding the analog-to-dpad mode to the config disables the dpad on an snes controller. The setup works fine when an Xbox360 controller is plugged in as controller#0, but when the same config is used with an snes config (and a different autoconfig of course), the dpad does not work. 

Took me some time to find out that everything is ok with my dpad, just the analog option disables it.

In #609 is described that this is not the supposed behaviour, so it seems to be a bug (or a hint to add it to autoconfig).

**Comment by duckspunches** [comment]
Same issue here using wired Xbox 360 controller and Mayflash 2 port SNES USB adapter (detected as HuiJia USB Gamepad) and Tomee NES USB adapter (detected as " NES PC Game Pad     NES PC Game Pad   ")

**Comment by gizmo98** [comment]
@michaelkleinhenz 
Could you check if the issue can be closed now?

**Comment by fr500** [comment]
closing this, if the issue is still this, reopen
