### ISSUE TITLE
RA exits when changing the windowed scale

### ISSUE THREAD

**Issue by leiradel** [libretro/RetroArch#1792]
Start RA without any config files (the Welcome to RetroArch screen will appear); go directly to Window -> Windowed Scale -> 1x; RA will exit.

If you press a button to close the welcome screen, before changing the scale, the issue doesn't occur.

MinGW64 build, can't reproduce inside gdb.

**Comment by leiradel** [comment]
Update: actually it also exited when changing the scale *after* closing the welcome screen.

**Comment by heuripedes** [comment]
Is this still happening? I can't reproduce on Linux.

**Comment by leiradel** [comment]
Yes it is. Happens in the MinGW64 build, I don't have a Linux box to test.

**Comment by fr500** [comment]
This isn't happening for me, please reopen if it's still happening on your side
