### ISSUE TITLE
[Lakka] Enabling/disabling services from RetroArch settings interface

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#1797]
This ticket is part of a serie feature proposals for RetroArch that would improve the user experience in Lakka.

Currently, enabling services like **ssh** in Lakka is done by adding a word in the kernel cmdline, in the bootloader config. There is an alternative way consisting in touching /storage/.cache/services/sshd.conf.

The systemd service looks like that:

    [Unit]
    Description=OpenSSH server daemon
    ConditionKernelCommandLine=|ssh
    ConditionPathExists=|/storage/.cache/services/sshd.conf
    After=network.target
    
    [Service]
    EnvironmentFile=-/storage/.cache/services/sshd.conf
    ExecStartPre=/usr/bin/ssh-keygen -A
    ExecStart=/usr/sbin/sshd -D $SSH_ARGS
    ExecReload=/bin/kill -HUP $MAINPID
    TimeoutStopSec=1s
    
    [Install]
    WantedBy=multi-user.target

However, some platforms like WeTek Play does not support bootloader config. This means the users have to be write to access the ext4 partition to create that sshd.conf

We could add a boolean setting in RetroArch, with a kind of hook that would touch this file. Like KODI does: 

![KODI SSH](http://www.htpcbeginner.com/images/2013/12/openelec-enable-ssh-500x293.png)

This would work also for the other services provided by the OS like Samba.

**Comment by gouchi** [comment]
#2810 implementation of ssh service.

**Comment by gouchi** [comment]
#2816 Update with Samba and Bluetooth services.

**Comment by Kivutar** [comment]
Done. Now changing those switches take effect without a reboot.
