### ISSUE TITLE
[Lakka] Display the IP in the menu

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#1798]
This ticket is part of a serie feature proposals for RetroArch that would improve the user experience in Lakka.

When Lakka users want to access **ssh**, they need to know the IP of the device. For now, they use some external tools, like arp-scan on linux, to find the IP. This makes our documentation complicated, we have to explain for each OS how to read the arp cache to find the IP. Also, the name of the network card displayed by those tools vary depending on the ARM board used.

The idea here would be to display the IP (at least the first IP) in System Information, or somewhere else in the menu.

**Comment by twinaphex** [comment]
This is implemented now and is shown under Information -> Network Information.

Currently only Windows still has a problem where it shows the network adaptor's name but not the IP address yet, but for Linux/Android/iOS/OSX it is fully working.
