### ISSUE TITLE
[Lakka] Choosing the audio_device from a list

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#1799]
This ticket is part of a serie feature proposals for RetroArch that would improve the user experience in Lakka.

Configuring the audio device is often a problem for NUC users. The default alsa audio device is almost never the HDMI one. So they have to connect Lakka through ssh and use aplay -L and set audio_device.

This process could be improved by having each audio driver in RA able to provice a list of audio device, and the settings interface would allow looping over this list to choose one entry.

**Comment by gouchi** [comment]
Fixed by #2909
