### ISSUE TITLE
Weird dependency rules

### ISSUE THREAD

**Issue by Alcaro** [libretro/RetroArch#1805]
Tested on Linux Mint 17 live CD.
* ./configure requires g++ for whatever reason; I think @twinaphex said some platforms need RetroArch to be linked with g++, but this is obviously not the case for a normal sane Linux.
* ./configure sets HAVE_OPENGL to true even if GL/gl.h and -lGL are absent.

**Comment by twinaphex** [comment]
Check how many of these issues are still relevant now, and whether or not you can close this issue now.

**Comment by Alcaro** [comment]
mint@mint ~/RetroArch $ ./configure
[...]
Checking existence of -lGL ... no
Forced to build with library -lGL, but cannot locate. Exiting ...

Better than a bunch of build failures, but I'm pretty sure that's not the solution you're thinking of.
