### ISSUE TITLE
Menu Shader Parameters doesn't work at first.

### ISSUE THREAD

**Issue by Hyllian** [libretro/RetroArch#1835]
I just installed latest nightly (21/06) and entered Shader menu.

Then, without chosing any shader or preset before, firstly I loaded a SNES game, then entered the "Menu Shader Parameters (Menu)" and from there I couldn't exit anymore. The back button stopped working,

Had to close retroarch and open again for it to work properly.

**Comment by fr500** [comment]
I tried it and it's working fine, feel free to reopen if you still have issues
