### ISSUE TITLE
Screenshot feature doesn't work for offscreen parts of the image

### ISSUE THREAD

**Issue by Hyllian** [libretro/RetroArch#1836]
If a game is run in a resolution which crops parts of its edges, the screenshot feature doesn't take screens correctly.

Here's an example of a screen grabbed by RA when a game has offscreen parts:

http://i.imgur.com/Ayup0RB.png

Look at up and down parts of the image to see the artifacts.

**Comment by heuripedes** [comment]
This happens because of the way glReadPixels is implemented on each platform/driver. I recommend using smaller values for the `Custom Ratio`/`Windowed Scale`/`Aspect Ratio Index` settings.

**Comment by Kivutar** [comment]
This happens even if you disable GPU screenshots?

**Comment by heuripedes** [comment]
I haven't checked but this should happen with GPU screenshot disabled if you are running mupen or ppsspp and your screen is smaller than the core's output. Non-GPU screenshots of other cores are unscaled dumps of the frames AFAIK.

**Comment by orbea** [comment]
This doesn't occur for me, has it since been fixed?

**Comment by hizzlekizzle** [comment]
Screenshots still only show what's on the actual screen and black everywhere else, but at least it doesn't do the weird repeated pixel thing. Gonna close this.
