### ISSUE TITLE
[Feature Request]Change default hardware filter to POINT sampling.

### ISSUE THREAD

**Issue by Hyllian** [libretro/RetroArch#1841]
I'll give you three strong reasons to change default hardware sampling to POINT from BILINEAR in RA:

1- it's more consistent with Retro philosophy;

2- almost 100% of shaders work with it;

3- new users don't know bilinear hardware sampling is the cause most shaders "don't work".

**Comment by Kivutar** [comment]
Yes I think you're right

**Comment by Hyllian** [comment]
Twinaphex, check libretro@gmail.com, please.

I sent you something.

**Comment by duduke** [comment]
...or maybe change hardware sampling to Point automatically when selecting a shader?

**Comment by hizzlekizzle** [comment]
There are some shaders, like quilez and sharp-bilinear, that don't work with point filtering, so either way, there's going to be some breakage. I think ideally there would be some way to specify the filtering method from within the shader, like a #pragma or something. I guess maister would probably say that's what the cgps are for...

**Comment by Hyllian** [comment]
Ok. I did some tests and the hizzlekizzle suggestions are right. It's possible to take precedence by editing cgps.

So I did a major change in common-shaders today, adding many cgps for the main shaders so that they control how samplings are done.
