### ISSUE TITLE
New emulator core recommendation - Raine

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/RetroArch#1842]
I was told by Twinaphex to post this here in the issues section so here we go.

http://rainemu.swishparty.co.uk/
http://rainemu.swishparty.co.uk/cgi-bin/gitweb.cgi?p=raine;a=summary

It is a various arcade system and Neogeo CD emu that has some nifty features .

Iv used it for a long time and it has alot of great ideas implemented and has a very nice interface and customization .

Think we can please see this in RA?

**Comment by duskgao** [comment]
I don't think RAINE would been ported to libretro core easily.Most games RAINE supported also supported by MAME/FBA already.

Yes,RAINE has the NGCD core, but FBA/MESS has it too,sadly the FBA NGCD emu hadn't been ported to libretro and the MESS port just crash when you load CHD...It is really strange that there is no native NGCD emu on android platform for such a long time.

**Comment by fr500** [comment]
ngcd should work fine in mess

**Comment by duskgao** [comment]
@fr500 Have you tested it? I tested the CHD in UME 2015 core with neocd.zip (BIOS) ,just crash. If you can run neocd CHD with MESS successfully...please post some clue like the path setting, THX a loooot! :D

I also test cdi/pippin CHD in UME, they all crashed.but I run GP32/supervision/super a'can with UME successfully! It is AWESOME!

**Comment by fr500** [comment]
hmmm to load games that only have chds (no roms) you could create an empty file and make it .zip, the libretro mame OSD loads games basically by parsing the path into commandline parameters.

So, if the game is game1.chd you need:

romdir
|
|----game1.zip
|----game1
|-------|-------game1.chd

That should work till we figure a better method

**Comment by duskgao** [comment]
@fr500r I think I still missed something with your conduct.

I can run MAME with CHD very well like in this way:

load core:MAME2015
load content:
roms(dir)
|
|---mamechd(dir)
|---------|------game.chd(eg:shikigam.chd)

it does run on my GPD Q9 (gamepad with rk3288)

But if I test with MESS

load core:MESS2015
load content:
roms(dir)
|
|---mess(dir)
|-------|-----roms（dir）
|-------|-------|------neocd(dir)
|-------|-------|------game.zip(eg:samsprpg.zip a empty zip file )
|-------|-------|------game(dir)(eg:samsprpg)
|-------|-------|---------|------game.chd(eg:shinsetsu samurai spirits - bushidohretsuden (1997)(snk)(jp)[!][ngcd-0850 mt a01].chd or rename to samsprpg.chd )

hashfile in systemdir\mess\hash\neocd.xml
BIOSfile in roms\mess\roms\neocd.zip

when I load the samsprpg.zip or the samsprpg.chd,RA return the No items screen.
But I can run GP32 roms with this hashfile set.

So does MESS/UME in RA really support CHD files? Could you take some minutes to test it? PLZ & THX!!!

**Comment by fr500** [comment]
Reopen this in the MAME tracker please
