### ISSUE TITLE
Split menu_hash.c into one file per language?

### ISSUE THREAD

**Issue by Holzhaus** [libretro/RetroArch#1843]
The `menu_hash.c` file is already a bit long. Why not split it into one file per language, i.e.:

```
menu_hash.c           # English
menu_hash_german.c    # German
menu_hash_portugese.c # Portugese
...
```

That would avoid endless scrolling.

**Comment by twinaphex** [comment]
Done.

https://github.com/libretro/RetroArch/commit/468b7e46c09ee2e7847f719735aa469496f31d61
