### ISSUE TITLE
(menu/cbs/menu_cbs_title.c) Hardcoded strings untranslatable

### ISSUE THREAD

**Issue by Holzhaus** [libretro/RetroArch#1854]
The strings in [`menu/cbs/menu_cbs_title.c`](https://github.com/libretro/RetroArch/blob/master/menu/cbs/menu_cbs_title.c) are not translatable at the moment. As far as I can see, the menu titles are auto-generated from these strings via the `sanitize_to_string()` function.

Because of that all menu titles and the top left "BACK" button in RetroArch are still displayed in English, regardless of language setting.

I'm not that familiar with the RetroArch menu implementation, so I'm unable to add their hashes myself.

**Comment by twinaphex** [comment]
Should be addressed now.
