### ISSUE TITLE
Thread in here closed down - then 23 days without an answer or commit

### ISSUE THREAD

**Issue by harlekinrains** [libretro/RetroArch#1882]
Lets start slow.

Hey - one of the cores you implemented is jacked. Totally unusable. Figured that this would grab some attention a month ago - but on the contrary.

Hey - your moderators in here were very quick to BAN this issue from any plattform that gets any kinds of views, because its bad publicity, right? Their reasoning was, that this was the wrong sub sub, of sub subs, sub - so please dont post it in here, post it somewhere else, where no one looks.

Hey -  of course the moderators didnt move the issue - they closed it down, because eff user participation, oh and if you are interested at all about us getting our act together, you will open the issue again - where we told you. And were no one looks.

Hey - since yesterday there is more than one person complaining about the issue - well, how very unexpected, since an entire core you implemented is broken.

HEY - you can read this as a desperate attempt to get any recognition AT ALL. You know what, Retroarch is not so much a running project - it is institutionalized mismanagement, until the people that bother you, give up on their own.

23 days and no reaction. Thats a record for me on github.

https://github.com/libretro/scummvm/issues/9

Get some Eyeballs onto this - why wont you? It is a biggie.

Sincerely, and so on and so forth..

h.

**Comment by twinaphex** [comment]
Github is meant for developers who want to contribute. This is a collaborative open source project. Being entitled and demanding things will not pressure us to immediately drop everything we are doing and switch over to this issue that you deem important.

There are far too many people who complain and sit on the sidelines and dont do anything, vs. the people who actually take time out to build things up. This is getting rather annoying.

**Comment by harlekinrains** [comment]
And there is the management issue of you implementing a broken core, then not finding the time for 23 days to address or even comment on it. This has nothing to do with a lack of developers. This is mismanagement.

If you arent able to address issue reports, after 23 days - at a level where you are putting out there broken implementations of entire cores - then shut down the project and call it failed already.

This isnt an issue of "it is enoying that we have so few people actually helping" - because dreaming your way towards a solution isnt productive either. So at what point does this become severe neglect and management missuse -- because HEY the entire core would work if this implementation problem would be addressed.

But for you - shipping it broken is much more exeptable - because?

YOU DREAM OF MORE DEVELOPERS FOR YOUR PROJECT INSTEAD.

I hope you get my disconnect here.

Again, I have never experienced anything like this on github. Eff self entitlement. Im not entitled to a solution, but if this project would still work, which is dosnt (lets not talk about delays) 23 days without even a reaction is unacceptable. Much less for a high priority problem.

You know it - but lets shut down the critical voice thats addressing it.

At some point you lose al motivation that is brough forward - because most signs that come out of the problem is sever neglect and lack of direction.

Feel free to share this with your developer community.  


Am Donnerstag, 02. Juli 2015 um 12:11 schrieb Twinaphex:

**Comment by fr500** [comment]
The issue was closed because it doesn't belong here. 

We're not running a company you know.  This is people working in their spare time on an open source project. 

There is no mismanagement,  there isn't a manager heck most of the work is done by a single dev. 

Core work is on the backburner now.  If you don't like it...  Well you don't like it.

**Comment by phly95** [comment]
This is actually kind of a shock for me. These developers are putting time and effort in the project as a hobby. If you think that it's a simple fix, why not fix it yourself. Sure you must have time to learn coding on your own and add your own commits to fix the issue considering what you just said. If something doesn't work properly, just mention the bug and what game you are trying to play. You didn't even mention a game leading me to believe that you think cores are games themselves or that because you don't play a game that uses ScummVM, no one should. That's like saying, "oh, well I don't play atari games, so why have an Atari emulator." 
The recent work on the UI they are doing is amazing and I wish the devs the best of luck. I would donate money, but the devs aren't even taking donations, that's how nice they are. 
Well, I hope you learned not to act entitled as it is not a way to get attention.

**Comment by Kivutar** [comment]
Letting an issue 23 days without reply is not a big problem.

Twinaphex is working full time on this project, he can't spend more time on it because there are only 24 hours in one day. When you hit that limit, you need more developpers in the team.

I understand that it is frustrating to see that issue being closed without being moved to the right repo. After all, reporting issue is a good first contribution to a project.

But what you can't do, is expecting us to reply in a short delay, because we don't take the money of users.

**Comment by harlekinrains** [comment]
What I can do - is to expect a reply - after tree weeks. When reporting a core breaking bug. You know this whole think about reporting bugs that you find - openly -- is entirely to produce a willingness to get them fixed. Its built into the project management system.

What you dont want as a tester (which I have been forced to become, but more on that later) is to get no feedback on the contributions you have made, and being met with a project management that is more likely to close down a contribution than to react to it.

Curiously enough - there still is no response on the ticket. Factually.

Also in general I dont care much about swallowing accusations that kissing up to our lovely devs is a default that is worth to honor, or that I must not know what I am talking about - probably even mistaking concepts, because someone else has a hard time comprehending the wording.

If I can say anything - when I choose to escalate a situation, I better make sure that my position is sound. When I report something, you can count on it being the way I reported it.

So what is the problem here?

The project management is jacked. Testers dont get responses on tickets in a timely fashion. Tickets get deleted when the are deemed popping up in the right spot.

Developers dont look into certain subsections of this project for months.

Core breaking issues are getting treated like they are nothing and bumped to the bottom of the line behind UI and even cosmetic changes within this project.

Now for the "I was forced to become a tester" part - and the reasoning for this project being jacked.

There was no stable release of Retroarch for about a year now.

The lovely dev excuses his actions with "the ratio of devs to "annoying bug reporting people"" is really "not very motivating" -- thats great to hear, but wishfull thinking wont solve any problems here.

There was an entire major release scraped - in favor of a version bump in the development tree - which again - shows jacked priorities. If your feature freezes cant be held up - again, you have management issues.

There are entire systems that have changed - with entire features this emulator needs to stay current, that people literally cant access without becoming testers - so what DO you expect?

Instead you guys chose to split your resources, by establishing another skinjob project that is aimed at the three major Desktop plattforms, in an age - where litereally no one buys a PC anymore - and any 35USD android device is fully capable of doing the job.

So my reaction - naturally - was, If you cant keep up - literally with any part of the project. Bug report handling, development, and strategical direction -- be honest, say so and close the project.

Thereby freeing the interest of people to contibute to maybe a new project that actually has a chance of going somewhere.


So far - purely logical. Not pleasent to read maybe - but there is an arguable standpoint here.
-

Now for the notions in the last reply.

No - 23 days without a reaction really, isnt normal, for any active project - much less on a core breaking issue.

No - I dont deserve a fix. I simply was reporting the issue. I dont feel entitled. Still, there is a problem here.

No - I dont want to feel bad, because I can read, that the dev "reacting" to all of this is a major contributor to this project who really doesnt have more hours in the day to contribute even more. And if it is really just the management structure of this project that is broken - this is still a valid criticism that has to be adressed by you guys.

HEY - currently you are peddling a product that doesnt get to a release stage anymore, where some of your cores are broken by implementation, and you are not reacting to tickets addressing A-list bugs within three weeks.

Open source projects are not an app economy where you can count on people to "switch the app" if they have an issue. You are bundling limited sources, based on limited good will - and by doing so, and by having gotten yourself a name as a project, you have a responsibility to the user to, be at least in a functional state.

So ask yourself one question. What is your failstate? What are the minimal cornerstones you have to fulfill? Hey - having a functional issue reporting system. Relasing stable builds once in a while. Not reacting with indifference to having entire cores broken in implementation.

You have fulfilled none of those.

Go on - complain again, that people are so demanding nowadays.

Why won't you find more helping hands for your project, I wonder.

I'm out - thats for sure.  


Am Dienstag, 07. Juli 2015 um 20:58 schrieb Jean-André Santoni:

**Comment by fr500** [comment]
For you the core is important.
For us RetroArch is important. Management again? We're like 5 people what management? This isn't a company it's people working on their free time to achieve their goals. THEIR. Yeah it might be annoying to not get a response. Deal with it.

RetroArch and the cores are separate entities. The focus is now on RetroArch.

BTW we released 1.2 3 days ago

**Comment by Kivutar** [comment]
RetroArch has many usages. Mine is using it with Linux on the $35 devices you were talking about. So I will contribute to that specific part when I feel I want to code.

I'm not very interested in the other aspects, such as iOS, Android, PS3, etc. So I will rarely contribute to that parts.

Keyboard driven cores are completely out of my taste. So I will probably never contribute to them.

You're issue being a combo of Android and ScummVM, it's not going to change my life if it never gets fixed. I would look at it if there wasn't already a list of 100 issues with higher priority for me.

If you love ScummVM, Android, libretro, and you know how to code C, please fork this repo and take a look at the code.

This one year of unstable releases was needed to refactor the code, and make it ready for the future. Now, we are in a kind of feature freeze state where the focus is to release RA on all supported platforms are fix the remaining bugs. Cores will come later.
