### ISSUE TITLE
Scanning directories fails to unload scanned files from memory, massive memory leak

### ISSUE THREAD

**Issue by The-MAZZTer** [libretro/RetroArch#1894]
In today's 1.2 stable release for x64 Windows, scanning directories causes RetroArch to consume memory without limit; my observation was about 15MB/s increase is usage.

This can easily be observed by scanning a series of large files. In my case it was 25GB worth of ZIP files... this ended up consuming about 22GB of memory. Memory is not freed when scanning is finished.

Symptoms I observed match general low memory symptoms:

- System will experience massive slowdown as memory is paged to disk.
- Windows may disable desktop composition in an attempt to save memory.
- Windows may advise users to close retroarch.exe due to low memory conditions.
- Applications may crash randomly due to low memory conditions or sudden change in desktop composition state.

I attempted to see if I could observe this on the Android build, however Settings > Apps > Running failed to show an entry for Retroarch as a running application so I could not get a memory reading.

Side note: I was unable to locate a log file for attachment. The directions for submitting bugs seem to be out of date as there is no log menu option, nor is there a log file on disk that I can find.

**Comment by twinaphex** [comment]
This PR should fix the issues:

https://github.com/libretro/RetroArch/pull/1901

Are you in an ability to test this yourself by building from source or should I just close this and you'll wait until we push out 1.2.1 later this Sunday? If it still persists, you can reopen this issue then.

**Comment by The-MAZZTer** [comment]
I'll pass on building from source (I always find it hit-or-miss on Windows for whatever various projects I try to build) and just try 1.2.1 and report back. I definitely have a good test case with my 22gb of zip files :)

**Comment by fr500** [comment]
Here you go 
https://dl.dropboxusercontent.com/u/149537/retroarch.exe

**Comment by The-MAZZTer** [comment]
Yup, seems to be fixed. Memory before and after a scan of the same 25gb of zip files is 87mb.
