### ISSUE TITLE
RA should have default/dummy folders to cores, database, cht, downloaded contents, ...

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1895]
RA should have default folders to cht, database, downloaded contents and others, inside ~/.config/retroarch/, for example:

~/.config/retroarch/downloads/
~/.config/retroarch/cores/
~/.config/retroarch/cht/
~/.config/retroarch/databases/
~/.config/retroarch/playlists/
[...]

Extracting the online stuff in the home folder is not very nice, linux users tend to dislike pollution in their ~/ (and I almost deleted my game/rom folders, which has the same name of "Games" cht folder)

I know you can change default dirs, just do a dummy default place for this kind of stuff.

**Comment by fr500** [comment]
I agree but not completely, this could be achieved easily during packaging. I'll try to set some hardcoded defaults

**Comment by sergiobenrocha2** [comment]
Yeah, the packer can workaround it, putting everything in ~/.config/retroarch/

The problem comes when you download cheat stuff, and games to GW core, you'll have lot of folders from cht/ "hiding" the downloaded games. Take a look:

![retroarch - bug 3](https://cloud.githubusercontent.com/assets/5431285/8510466/2be50772-22bc-11e5-9d83-853e4021721a.png)

So you'll have a lot of different stuff in only one folder.

**Comment by sergiobenrocha2** [comment]
#1892 is related. That would never happened if there was folders for each thing (playlist_directory and for content_history_path)

**Comment by sergiobenrocha2** [comment]
@fr500 I like the changes, only a few issues:

Extraction Dir should be at /tmp instead rom folder
Input Device Autoconfig Dir should be at ~/.config/retroarch/autoconf/udev
Boxarts Dir should have its folder too
File Browser Dir should be ~/  ?

**Comment by fr500** [comment]
Extraction dir is fine at content dir by default, it's always cleaned up.
Input device autoconf is fine, it looks at the subfolders and at the autoconf folder
Boxarts are user data

**Comment by fr500** [comment]
Is this ok now? am I missing any folders?
This has to be implemented on a per-platform basis but I think Linux is done aleady

**Comment by sergiobenrocha2** [comment]
There's screenshots folder now, but in the settings dir it's in the Content Dir.

It's missing a folder for boxarts yet.

Dynamic Wallpapers Dir should be set too, ~/.config/retroarch/assets/wallpapers/bichromatic pads/1440x900 ?

**Comment by sergiobenrocha2** [comment]
Eh, screenshots is OK, sorry :p

**Comment by fr500** [comment]
~/.config/retroarch/assets/wallpapers/bichromatic that's a bit too specific for a default but yeah could be done
