### ISSUE TITLE
Hide Recording dirs in Directory Setting if compiled with --disable-ffmpeg

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1897]
RA should hide Recording dirs in Directory Setting if compiled with --disable-ffmpeg, there's no sense to have these options without ffmpeg support.

**Comment by sergiobenrocha2** [comment]
It should hide Rewind Settings too

**Comment by fr500** [comment]
Rewind doesn't need ffmpeg, it only needs serialization

**Comment by sergiobenrocha2** [comment]
Nice, it's working. There's Driver Settings --> Record Driver yet, but I think it's not a problem. Fixed in af916cc
