### ISSUE TITLE
Linux: Xbox 360 controller analog sticks always negative

### ISSUE THREAD

**Issue by ddg1** [libretro/RetroArch#1900]
Using the latest git version, RetroArch detects all analog stick movements as negative, making the controller unusable.
I've tracked down the issue to commit [97f818](https://github.com/libretro/RetroArch/commit/97f818896910b53893429bd3ac0dba2262788d33), it's the first one in which it starts to fail. Could somebody please take a look?

**Comment by twinaphex** [comment]
Test if this fixes it -

https://github.com/libretro/RetroArch/commit/425948c70693c34bc6b2f212fe1f382807aa23c3

**Comment by Kivutar** [comment]
I get the same bug (even after 425948c) on X11 and KMS, using udev for input driver and joypad driver.

The strangest thing here, is that this bug does not occur on Lakka. I can reproduce it just on Arch.

**Comment by ddg1** [comment]
It works fine for me now. Thank you!

**Comment by sergiobenrocha2** [comment]
Since when is it broken? I know at least one joypad config was wrong merged maybe because this issue
