### ISSUE TITLE
[Feature Request] [Android] Use system bound buttons

### ISSUE THREAD

**Issue by BlackLotus** [libretro/RetroArch#1903]
On android it can happen quite easily that you get a button that has already a function mapped to it appears.
Since you normally don't want to go back,open a men, app list or home screen it would be nice if you could suppress the actual functions of those buttons and eventually remap them.

**Comment by Kivutar** [comment]
What about remapping those buttons in the input binds and hotkeys settings?

**Comment by BlackLotus** [comment]
If I press the back or home button I will get back or to the home menu.
Retroarch has the function to not open the menu with the back button, but at least on the fire stick it doesn't work for me

**Comment by fr500** [comment]
no, the home button cannot be overriden (or at least shouldn't)
back button can be overriden just fine

**Comment by fr500** [comment]
You should try the latest builds with the fire stick, I made the remote work well with RA
