### ISSUE TITLE
XMB stuck if you try to download stuff while it's not connected

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1907]
If it's disconnected, XMB will stuck in the downloadable option with this behavior, and you can't return to the main options.

![retroarch - bug 6](https://cloud.githubusercontent.com/assets/5431285/8514287/03d709b4-2362-11e5-8f10-55571d6f63a2.png)

Big problem to smartphones (normally I'm offline).

**Comment by Kivutar** [comment]
Also affects GLUI and RGUI.

**Comment by Great-Dragon** [comment]
Actually it stucks even if you use VPN.
XMB stucks on all menus that pull list from the sever: Core Updater, Download Content.

**Comment by BlackLotus** [comment]
At least when there is no server to connect to or no connection

**Comment by twinaphex** [comment]
Should be fixed now.
