### ISSUE TITLE
Shader settings are missing in RetroArch menu in new version

### ISSUE THREAD

**Issue by Pulfer** [libretro/RetroArch#1917]
In RetroArch 1.0 I could configure shaders from Setting -> Shader Options.

In RetroArch 1.2 I don't see Shader Options anywhere in menu. Still I can switch shaders with hotkeys.

Cg is properly detected with configure:

HAVE_CG = 1
CG_CFLAGS = 
CG_LIBS = -lCg -lCgGL

From RetroArch System Information:

Cg support: yes
GLSL support: yes

**Comment by hizzlekizzle** [comment]
They're still there. Load some content and then go into the menu. It will take you to the 'quick menu' where you can get to the familiar shader settings menu.

**Comment by Pulfer** [comment]
Indeed, shader settings are there. Thanx.
