### ISSUE TITLE
Multi disc pbp files

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#1920]
Does this work? I want to have my games in a single file and a flat directory hierarchy and this is the only format that will provide this for me. However almost no psx emulator will support the multidisc version, because all of their GUI expect the switch iso operation to choose a new filesystem file instead of treating pbp as a specialized container file, so what happens is that they all choose the first cd of the pbp over and over again (except windows version epsxe, which is the only one that shows a popup - this doesn't work on linux because the gui wasn't updated).
PCSXR adds insult to the injury of having a single GUI based on gtk for both windows and linux and still having this problem - even if looking at the code it **looks** like it's filling entries from all the image files into a array.

**Comment by fr500** [comment]
RetroArch doesn't support any filetypes per-se, in most cases it reads the file and passes it as a memory object to the core. In other cases it just passes the file location to the core.

It's the core job to handle this in one way or another.

**Comment by i30817** [comment]
I just wrote the core (PCSXR in this case) always selects the first because passing a single filename to open is not enough to actually select the correct image. It needs a different interface or actually going into the structs of the core to choose one of the possibilities.

**Comment by twinaphex** [comment]
This is core territory, not RetroArch territory.

Going to close this since it doesn't seem likely anything is going to emerge in the here and now.

**Comment by Qard** [comment]
Seems to me like it might be more a core issue. The concept of disk changing as changing the file is baked into retroarch, but PBPs store all the disks in one file. In most cases, it's not really possible for the core to "know" when it's waiting for a disk change, so the user needs the control to do that switch manually. The current UI controls for that don't work though, as it does not provide a way to select disc number within the PBP file.
