### ISSUE TITLE
Core updater needs some organization

### ISSUE THREAD

**Issue by phly95** [libretro/RetroArch#1924]
The core updater should have categories for each console are there are times when there are like 5 different emulators for the same consoles but start with a different letter (ex. mGBA is not together with VBA-M or Gambatte and TGB Dual).

**Comment by phly95** [comment]
What would make things even easier is if you add content first and when you select the game and there are no cores available, show a list of downloadable cores just for that console. It sure would be helpful for newcomers if they don't know how to use the online updater.

**Comment by RobLoach** [comment]
The core names have been updated by system now....

![screenshot at 2018-07-29 15-49-39](https://user-images.githubusercontent.com/25086/43370102-1046e1a8-9347-11e8-83c6-27651ea9e325.png)

When attempting to load content without an active core, it also prompts you to get one.

Closing this issue. Feel free to create a new issue if what's there doesn't satisfy your needs. Thanks!
