### ISSUE TITLE
Some freezes on GNOME

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#1926]
When using GNOME, with RetroArch in windowed fullscreen mode, if I press alt+tab or change the audio volume using xorg keyboard shortcuts, RetroArch freezes.

No messages in the log, no segfault, no prompt, I have to xkill.

**Comment by twinaphex** [comment]
Does this happen only with GLUI/XMB or does it happen to RGUI too?

**Comment by Kivutar** [comment]
It happens only in GLUI/XMB, and only if threaded data runloop is enabled.

**Comment by twinaphex** [comment]
Can you retest this again?

**Comment by Kivutar** [comment]
Fixed! Thank you.

**Comment by Kivutar** [comment]
Finally, it still happens (but more rarely, like one time out of 10).

**Comment by fr500** [comment]
Is this still happening, reopen this if it is the case

**Comment by Kivutar** [comment]
Yes, it's still hapenning.

**Comment by chadversary** [comment]
I get freezes in the same situation as @Kivutar:
> When using GNOME, with RetroArch in windowed fullscreen mode, if I press
> alt+tab or change the audio volume using xorg keyboard shortcuts, RetroArch
> freezes.
>
> No messages in the log, no segfault, no prompt, I have to xkill.

The freeze is 100% reproducible for me when pressing Alt+Tab or a media key
when using the bnes core and xmb.

Versions:
  - retroarch 182d691
  - https://github.com/libretro/bnes-libretro/commit/88deae8cff50fb1ea561f875eb63970c8a3679cb

I caught a backtrace by sending SIGINT to retroarch while it was frozen. I
repeated this 3 times, and frames 0-4 of the backtrace were the same each time.
Frame 4 is in retroarch's input_poll().

Backtrace:
```
#0  0x00007ffff6a4bb10 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ffff633215d in _XReply () from /lib64/libX11.so.6
#2  0x00007ffff6328211 in XQueryKeymap () from /lib64/libX11.so.6
#3  0x00000000004d9ed5 in x_input_poll (data=0x7fffe82b81c0) at input/drivers/x11_input.c:501
#4  0x00000000004104c9 in input_poll () at libretro_version_1.c:210
#5  0x00007fffe73f1a51 in NES::PPU::frame_edge() () from /home/chadv/lib/retroarch/cores/bnes_libretro.so
#6  0x00007fffe73f209c in NES::PPU::ly_increment() () from /home/chadv/lib/retroarch/cores/bnes_libretro.so
#7  0x00007fffe73d1f60 in NES::PPU::main() () from /home/chadv/lib/retroarch/cores/bnes_libretro.so
#8  0x00007fffe73f7c60 in co_swap () from /home/chadv/lib/retroarch/cores/bnes_libretro.so
#9  0x0000000000000000 in ?? ()
```

**Comment by twinaphex** [comment]
bnes is an abandoned core though, I wouldnt recommend you to use it at all.

**Comment by fr500** [comment]
is this still going on? reopen if so

**Comment by Kivutar** [comment]
Yes, it still happens, whatever core I use (even without cores)

**Comment by twinaphex** [comment]
I don't use Fedora, Ubuntu or even GNOME altogether, have somebody who does look into it, can't be of much help here I'm afraid, things work just fine with openbox and Arch Linux.

**Comment by hadess** [comment]
@twinaphex would be good to test on at least one GL compositing window manager. mutter is probably the simplest to get running.

**Comment by Kivutar** [comment]
I'm not 100% sure that RA is still affected with this bug. At least, the number of occurences have drastically reduced. @hadess were you able to reproduce it?

**Comment by hadess** [comment]
No, I'm still in the process of setting things up right now. I was looking for another bug/installation problem (I was missing assets) and stumbled upon this bug.

The main difference between openbox and something like gnome-shell is the fact that the latter is a GL compositor. If this problem doesn't happen any more, feel free to close it.

**Comment by twinaphex** [comment]
Closing this, reopen it in case it still happens.

**Comment by Thav** [comment]
This issue was still present for me, but I was able to work around with https://bugs.launchpad.net/unity/+bug/1511835/comments/6

Running Ubuntu 16.04 with Unity rather than Gnome, but I believe the common denominator is Compiz for compositing. It is apparently an issue with GL and full screen programs. Exceptions in the workaround above are already present for VLC, Chrome and some others.
