### ISSUE TITLE
Scan subfolders in directory

### ISSUE THREAD

**Issue by phly95** [libretro/RetroArch#1929]
I have my games set up in a folder which then has many subfolders such as psx, SNES, GBA, etc. Scanning each folder is somewhat cumbersome, but the new scanning feature is a step in the right direction. It would just be nice to scan once and done.

**Comment by sergiobenrocha2** [comment]
It would be nice if this option is optional. You may have hack or prototypes roms inside your main rom, and you don't want to read that too (maybe).

**Comment by Kivutar** [comment]
@phly95 I would like it too. It would allow scanning a whole collection in one step.

**Comment by phly95** [comment]
@sergiobenrocha2 or you can just remove it from your library afterwards

**Comment by markwkidd** [comment]
This seems to have been solved with https://github.com/libretro/RetroArch/pull/3412

**Comment by sergiobenrocha2** [comment]
Related to #3966.

**Comment by RobLoach** [comment]
Can be closed.
