### ISSUE TITLE
Retroarch crash when unloading a Dinothawr core

### ISSUE THREAD

**Issue by Nukotan** [libretro/RetroArch#1931]
audio callback hasn't been initialized?

RA v1.2
Dinothawr v1.0 (git cf90f3b)
Windows 7 x64

**Comment by twinaphex** [comment]
This commit fixed this for me - check it out on your end -

https://github.com/libretro/RetroArch/commit/3aff5a3ee2b32afcffc1e6003cc66e2887a10ad4

**Comment by Nukotan** [comment]
Thank you very much. works fine :)
