### ISSUE TITLE
Joystick axis problems with udev input driver

### ISSUE THREAD

**Issue by Jcw87** [libretro/RetroArch#1932]
I'm using RetroArch on the Raspberry Pi 2 via the retropie setup script. Everything was working fine back in March, but when I updated everything today, I started having input problems. No inputs were working at all. After disabling joypad autoconfig, keyboard input resumed working. I then found that during manual config of the joypad, some of my axes would not bind at all, as if I was doing nothing on the controller, in both RetroArch and the RetroArch joypad config utility. The autoconfig was likely causing problems due to using these broken axes. The problems in RetroArch went away when I switched the input driver to linuxraw.

The affected axes on my controller were the control sticks. For both of them, the X axis wouldn't bind anything, and the Y axis always bound the negative direction.

My joypad is a "Logitech Gamepad F310"
Left X is axis 0
Left Y is axis 1
Right X is axis 3
Right Y is axis 4

I also tried installing RetroArch from source. It did not fix the problem with the udev input driver.

**Comment by Jcw87** [comment]
My issue may be related to #1900

**Comment by sergiobenrocha2** [comment]
update your source, there's a commit may fix your problem.

**Comment by Jcw87** [comment]
This appears to be fixed now. Thank you!
