### ISSUE TITLE
The wrong autoconfig file is matched

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#1933]
Depending in what order the input autoconfig files are read, you will get a wrong config.

For example, if Xbox_360_Wireless_Receiver.cfg is read before Microsoft_X-Box_360_pad.cfg, you will get the Xbox_360_Wireless_Receiver for your Microsoft_X-Box_360_pad. Because input_autoconfigure_joypad_from_conf_dir will get the first config with a matching vid:pid, and those two config files share the same vid:pid.

To fix that, we must give priority to the file that matches the **name:vid:pid** triplet, and then fallback to file that matches just **vid:pid**, and finally to file that matches just the **name**.

Every config file that does not match the input_driver must be ignored, as it is already the case.

**Comment by sergiobenrocha2** [comment]
Xbox_360_Wireless_Receiver has no more the same id, I think that one was from the joystick recharger, not from the receiver.

**Comment by fr500** [comment]
kivutar, check it now, I made a weighted score system it works nicely here

**Comment by Kivutar** [comment]
@fr500 your weighted score system fixes that bug. Thanks.
@sergiobenrocha2 are you sure? Your receiver is the official one?

**Comment by sergiobenrocha2** [comment]
@Kivutar take a look at libretro/retroarch-joypad-autoconfig#38, I posted some photos there. I think it's the official, but I'm not sure.

```
Bus 008 Device 003: ID 045e:0719 Microsoft Corp. Xbox 360 Wireless Adapter
```

**Comment by sergiobenrocha2** [comment]
My receive is getting the config from both Xbox_360_Wireless_Receiver.cfg and Xbox_360_Wireless_Receiver_Chinese01.cfg (I mv one, and it get from the other)

**Comment by sergiobenrocha2** [comment]
With both config installed, it get from the wrong one (Chinese01, which has product id = 657)

my receiver has product ID = 1817

**Comment by fr500** [comment]
the pid/vid must be expressed in decimal format

**Comment by fr500** [comment]
If you can paste a verbose log I can try to figure out why it's picking the wrong one

**Comment by sergiobenrocha2** [comment]
I git pull, it's working now, sorry.

Btw, 1817 is the decimal of 0719.

**Comment by sergiobenrocha2** [comment]
I removed the Xbox_360_Wireless_Receiver.cfg, and it's fallbacking to Xbox_360_Wireless_Receiver_Chinese01.cfg. Is it right?

**Comment by Kivutar** [comment]
Falling back is normal, because both config files and devices share the same input_device.

If you compare the two files, you will see that the only difference is the pid and the L and R recognized either as axis or buttons. As you expressed on the other topic.

Most important, is it working now?

**Comment by sergiobenrocha2** [comment]
Yup, it's working fine now.
