### ISSUE TITLE
search dialog is triggered when entering gui when menu hotkey includes X

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#1938]
When triggering the RGUI menu with Select+X when in a game, the search dialog is triggered (although it isn't actually visible) so you have to press B before pressing A to close the initial information dialog. I can confirm this by disabling the search dialog

eg

```
diff --git a/menu/menu_entry.c b/menu/menu_entry.c
index ca37ca4..ff78c9a 100644
--- a/menu/menu_entry.c
+++ b/menu/menu_entry.c
@@ -496,10 +496,6 @@ int menu_entry_action(menu_entry_t *entry, unsigned i, enum menu_action action)
             disp->msg_force = true;
          break;

-      case MENU_ACTION_SEARCH:
-         menu_input_search_start();
-         break;
-
       case MENU_ACTION_SCAN:
          if (cbs && cbs->action_scan)
             ret = cbs->action_scan(entry->path, entry->label, entry->type, i);
```

this a continuation from #1807 as the issue first manifested itself as a "freeze" before it was possible to exit dialogs with the B button.

**Comment by RobLoach** [comment]
Closing this one for now, if the problem still persists, feel free to re-open with the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md) in place.
