### ISSUE TITLE
Core Input Remapping limitations

### ISSUE THREAD

**Issue by SleepyMan** [libretro/RetroArch#1939]
Currently (v1.2), the remapping implementation has a few limitations, like:

- impossible to remap RetroPad analog sticks to actual buttons like D-pad UP,DOWN,LEFT,RIGHT (VERY useful in PPSSPP, where games use the D-pad to control the camera)
- impossible to remap multiple RetroPad buttons to a single core button (keep D-pad working as D-pad, but also make the right analog stick act like the D-pad, VERY useful in PPSSPP again) (other valid use-cases would be to remap BOTH RetroPad button A and Y as core button A, and RetroPad button B and X as core button B, in a NES core, or any other combination)

If there is a way to do that through manual editting the remapping file, please enlighten me. But currently,  in the remapping screen, there is no way to select multiple RetroPad buttons, nor select actual buttons for the analog sticks or vice-versa.

**Comment by fr500** [comment]
No, there is not way to do this currently and it would require a huge
refactor of the input subsystem

**Comment by Papermanzero** [comment]
This feature would be brilliant.
I would like to use the real dpad and the real analog stick as retropad dpad.
But unfortunately I can only map either the dpad or the analog stick to the retropad.

**Comment by ReaperMantis** [comment]
I agree this would be extremely useful, especially for something like remapping a controller with dual analog joysticks to the virtual boy controller's dual d-pads.  I think it would also make remapping the N64 C buttons to the right analog a little less confusing than having the 'modes' and remappings for each mode all displayed at once.  This may mean losing the remap mode functionality, but maybe down the road, a list of remap files can be specified that can be cycled through as modes.

**Comment by Papermanzero** [comment]
It's currently the most disadvantage of libretro and/or retroarch.

If it would support multiple mapping of buttons/sticks, it could easily replace every other emulator.
I really like the feature in PPSSPP, VBA-M, and other emulators to map the virtual dpad to the real left stick and at the same time on the real dpad on my 360 controller. Also to map buttons on the additional shoulder buttons is great.

Makes it much more easier to play games.

**Comment by fr500** [comment]
You can remap the dpad to the stick just fine

**Comment by fr500** [comment]
So, a way to improve this would be:
Swap the fields in the UI, so all RetroPad buttons are on the left

![Uploading Screenshot 2016-05-23 23.20.13.png…]()

**Comment by fr500** [comment]
new issue https://github.com/libretro/RetroArch/issues/3028

**Comment by DewOnTheGrass** [comment]
What would it take, code-wise, to simply add a second d-pad to the RetroPad?
