### ISSUE TITLE
Weird font rendering with XMB driver

### ISSUE THREAD

**Issue by jbaiter** [libretro/RetroArch#1942]
I just compiled and installed RetroArch from the master branch on Debian sid/unstable. With the XMB driver, font rendering looks pretty messed up:

![Example](http://i.imgur.com/YuFCud0.png)

The fonts in the RGUI and GLUI drivers look great.

Here is the verbose log from starting up RetroArch: http://paste.debian.net/281077/

**Comment by heuripedes** [comment]
Post your `retroarch.cfg`

**Comment by jbaiter** [comment]
Here it is: http://paste.debian.net/281222/
It's pretty much the default config, with the exception of the libretro and asset paths, as well as the input mapping.

**Comment by fr500** [comment]
Is this still happening? If so please reopen
