### ISSUE TITLE
Playlist (lpl) files limited to only 6000 lines

### ISSUE THREAD

**Issue by SqueezeMyMonkey** [libretro/RetroArch#1946]
When trying to scan large collection like Game Boy, the playlist (lpl) file is trimmed to not exceed 6000 lines and I only get the last half of the games on the list.  So instead of getting the whole list from A-Z, I only get games starting from M to Z.

**Comment by twinaphex** [comment]
This should hopefully take care of this arbitrary limit and make the 'next' arbitrary limit a bit more  difficult to reach:

https://github.com/libretro/RetroArch/commit/9185d37710b86a446762c597e5898b3b5ce2fd44

**Comment by fr500** [comment]
Please reopen if the issue persists.
