### ISSUE TITLE
[GX] Wii build broken with this commit: e2d510e

### ISSUE THREAD

**Issue by netux79** [libretro/RetroArch#1949]
Starting with these changes e2d510e, the Wii/GC nightly build is broken.

It seems to be some input changes. When trying to start retroarch it goes to a black screen and returns to the HBC after some seconds.

**Comment by twinaphex** [comment]
input_driver_get_ptr might be wrong. I'll look into that after I'm done with some input overlay issues first.

**Comment by twinaphex** [comment]
See if this commit fixes it -

https://github.com/libretro/RetroArch/commit/0107be2485c088b5ce48c38b65b46f50e464ca1e

**Comment by netux79** [comment]
Sure, let me test it and I will report my findings, thanks!

**Comment by netux79** [comment]
Good & Bad News. It now starts RA and everything seems to work but... The RARCH_MENU_TOGGLE is broken. If you press any HOME button nothing happens, you cannot return to menu once you start a game. I think something with the lifecycle_state var is wrong. Before all these changes it was a pointer to the global lifecycle_state but now it doesn't seem to get its value from any place...

**Comment by twinaphex** [comment]
It should get its value from here -

https://github.com/libretro/RetroArch/blob/master/input/drivers_joypad/gx_joypad.c#L204

**Comment by twinaphex** [comment]
This commit should fix it -

https://github.com/libretro/RetroArch/commit/23348f41ac76858de77f0782376220ecc965e742

**Comment by netux79** [comment]
It is working fine now... please close this issue :), Thanks!!
