### ISSUE TITLE
(Menu) Add an "Update Everything" button in Core Updater

### ISSUE THREAD

**Issue by jeapostrophe** [libretro/RetroArch#1957]
It is inconvenient to go through all the Cores. I also find that if I repeatedly do "X, down, X, down, ..." and then look at the core list, most of the cores were not downloaded, presumably because only one is downloaded at a time and they are not queued?

**Comment by phly95** [comment]
yeah, also, I would like if the core updater was organized by consoles as I hate having something like Gambatte so far away from TGB-Dual when they both emulate the same system. It's also hard to find cores if you don't know the name and only know the console.

**Comment by RobLoach** [comment]
Done.
