### ISSUE TITLE
Does not recognize .z64 versions of No-Intro games

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#1963]
I byte swapped my No-Intro collection of N64 games to use with Cen64. Apparently this was enough to not recognize the games in the RetroArch library anymore.

**Comment by hizzlekizzle** [comment]
Yes, RA's detection is based on CRC checksums, so swapping byte order will indeed break it, as the checksums will no longer match.

**Comment by tony971** [comment]
So, in the future, users will have to choose bettwen Cen64 compatibility and RA detection? That could become a big issue if @tj90241 gets Cen64 to fullspeed.

**Comment by hizzlekizzle** [comment]
Heh, that's a pretty big 'if'. However, if that comes to pass, we can add additional databases pretty easily. We'll just need a working set to run CRC hashes on.

**Comment by fr500** [comment]
This is not really a RetroArch issue anyway, no-intro is the defacto standard now (not byte-swapped no-intro). They aren't doing everything right but it's pretty much what people will use and keep using going forward.

CEN64 should support no-intro I guess, as for scanning in RetroArch, we'd just need a db of "byteswapped no-intro" crcs.
