### ISSUE TITLE
When entering a search word, hitting F toggles fullscreen.

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#1964]
To reproduce:
type /
type f

**Comment by heuripedes** [comment]
I can reproduce this.

**Comment by twinaphex** [comment]
I can no longer reproduce it after pushing this commit -

https://github.com/libretro/RetroArch/commit/8162b77baee70dfb48c06b98cbd4e8b578005813

**Comment by Kivutar** [comment]
Fixed for me too

**Comment by sergiobenrocha2** [comment]
It fixed for f, but not for z

**Comment by lasers** [comment]
I came here to file a bug report about "z" -- Open this or I file a new one?
