### ISSUE TITLE
Question about retroarch cores

### ISSUE THREAD

**Issue by Fadi5555** [libretro/RetroArch#1967]
Hi there.

I just asking if there will be a core of gamecube on retroarch
I mean play gamecube games through core on retroarch.
For example we could play GameCube games on our ios/android devices through retroarch.

I think this will be a great idea if you could port GameCube or dolphin as a core on retroarch.

**Comment by Fadi5555** [comment]
Please can anyone reply on my question?

**Comment by HerbFargus** [comment]
http://libretro.com/forums/showthread.php?t=2414

**Comment by Fadi5555** [comment]
@HerbFargus thank you so much for your fast reply.
Well do you think we will ever see the dolphin as a core on retroarch?

**Comment by HerbFargus** [comment]
Hopefully one day, its in the works. Your question is probably best for the forums though as github is primarily for issues and bug reports. You can follow the development here https://github.com/libretro/dolphin and the releases on this site: http://www.libretro.com/

**Comment by Fadi5555** [comment]
This is our hope I'm sure if they could port a dolphin core on retroarch we will get a high performance.
Because the retroarch is much more portable.
Other things which is more important as you know the iOS devices are still not having a port of dolphin like android version. So android and iOS are sharing the same program which is (retroarch) I mean if thye could port a dolphin on retroarch the iOS will enjoy too with it.
So all platforms will like this step.
I hope they did their best to make it happen.
