### ISSUE TITLE
[GLUI] Menu elements are restrained too much in regards to available horizontal space

### ISSUE THREAD

**Issue by micechal** [libretro/RetroArch#1969]
As you can see, there's plenty of space left black that could be used to display more characters for each menu element:
![screenshot](https://cloud.githubusercontent.com/assets/3483746/8709108/72388bb8-2b40-11e5-811f-d49a2376abff.jpeg)

**Comment by twinaphex** [comment]
This PR should hopefully address these issues in 1.2.2 -

https://github.com/libretro/RetroArch/pull/1975

**Comment by micechal** [comment]
Doesn't occur in 1.2.2.
