### ISSUE TITLE
[GLUI] Scrolling animation persists between screen changes

### ISSUE THREAD

**Issue by micechal** [libretro/RetroArch#1970]
If touch support is enabled and a swipe is made so that the movement doesn't stop after the touch has been released (inertia), the movement will not stop regardless of menu screen changes or even going back to loaded content and again into the menu.
The easiest way to reproduce is to simply make such a swipe and tap the `BACK` button afterwards.

**Comment by fr500** [comment]
Is this still happening? Reopen if so

**Comment by micechal** [comment]
Seems fixed.
