### ISSUE TITLE
Onscreen overlay doesn't always come back after returning to content

### ISSUE THREAD

**Issue by micechal** [libretro/RetroArch#1973]
If the `Hide overlay in menu` option is enabled (the default), the overlay won't reappear upon either saving state, loading it or resuming content.
Additionally, if RetroArch is minimized while the overlay is hidden, the overlay will reappear upon un-minimizing. This one most likely only happens on Android, but I haven't checked that yet on other platforms.

**Comment by twinaphex** [comment]
This should hopefully address all these issues - should appear in 1.2.2 now.

https://github.com/libretro/RetroArch/commit/f938c75e0b6de47130a232b34f3a159d7db4d281

**Comment by micechal** [comment]
Fixed.

**Comment by micechal** [comment]
That was too fast I think. The overlay will still come back after unminimizing.

**Comment by orbea** [comment]
@micechal Is this still an issue?

**Comment by micechal** [comment]
@orbea it's not, as far as I can tell. Just tested it using the latest Android nightly and everything seemed in order.
