### ISSUE TITLE
Joypad configuration not reading xbox360 analogs correctly

### ISSUE THREAD

**Issue by J-Swift** [libretro/RetroArch#1977]
(thank you for the software, it really is awesome!)

I'm running RetroArch via RetroPie-Setup (HEAD is 58508cb) on a raspberry pi 2. I have xboxdrv setup (in non-daemon because that gave me issues) running for a single 3rd party wired Xbox360 controller.

When I try to configure the controller, everything reads correctly except the two analog sticks. It assigns both directions as 'negative', so instead of 0- and 0+ for left/right, they both are set to 0-. This happens for both sticks, and in both directions. It occurs when attempting to configure through the in-emulator RetroArch menu (via Settings > Input User 1 Binds) as well as when running via the CLI retroarch-joyconfig.

When I run jstest on /dev/input/js0 everything is read fine.

Here is the logged output of retroarch-joyconfig. The only interesting bit to me is the 0000:0000. My `lsusb` shows the id as 0e6f:0401.
```
RetroArch [INFO] :: [udev]: Plugged pad: Xbox Gamepad (userspace driver) (0000:0000) on port #0.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event0) supports 0 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
Found joypad driver: udev
Using joypad: Xbox Gamepad (userspace driver)

...
[configuration follows]
...
```

Let me know what more info would help in debugging.

**Comment by joolswills** [comment]
Did you try building retroarch from source via menu 5 in RetroPie-Setup to get the very latest version ? There was an issue with 360 analog sticks that was resolved recently

https://github.com/libretro/RetroArch/issues/1900

**Comment by J-Swift** [comment]
My apologies, I looked through the closed issues and completely missed that. I'll try it out later and let you know if it fixes it. It probably will.

**Comment by J-Swift** [comment]
Yep, that did the trick. Thanks!
