### ISSUE TITLE
Bios Directory Resetting 1.2.1

### ISSUE THREAD

**Issue by AlertDOTEXE** [libretro/RetroArch#1980]
As the title says, the bios path in the directory menu resets randomly.

**Comment by fr500** [comment]
It only happens when loading from the cli or an external frontend.  It's
fixed already.

**Comment by Kivutar** [comment]
This can happen when launching the retroarch while the executable is right in the parent folder of the system folder. This will override all your paths with relative paths. This feature is usefull on windows, where people want to move their RA folder around while keeping their paths working.

But it can be misleading on Linux, when your bin is in /usr/bin, then you use another bin placed in your home directory for debugging purposes. And you end up with all your paths changed.

**Comment by twinaphex** [comment]
I think this was related to the issue we just fixed. Closing.
