### ISSUE TITLE
input_enable_hotkey_btn being ignored

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#1982]
Something has broken in the last few days. RGUI menu is appearing when just pressing input_menu_toggle_btn despite input_enable_hotkey_btn being set (in controller configuration)

bisecting now

**Comment by joolswills** [comment]
5d87c697bbbb3a14be9a4aced1e40fe6b40b6208 is the first bad commit

```
commit 5d87c697bbbb3a14be9a4aced1e40fe6b40b6208
Author: twinaphex <libretro@gmail.com>
Date:   Sun Jul 12 09:08:27 2015 +0200

    Optimize input_driver_keys_pressed and make it possible to
    pass more 'keys' to the input key pressed callback than just
    the standard buttons

:040000 040000 9fa28d323a738aa6a1c735b5f85d2334f9fc8623 8952a956dbb0dbbd0e2762fbfeb7795cb86ae276 M	input
```

**Comment by twinaphex** [comment]
Test if the latest two commits fix this issue for you.

**Comment by joolswills** [comment]
Sorry, still broken :(

**Comment by joolswills** [comment]
(same behavior)

**Comment by twinaphex** [comment]
Then that commit couldn't have caused it then.

**Comment by joolswills** [comment]
afraid not.

63582f83b189afb84139877e85edd98a0f069fc5 is fine (the revert) but f1d8f98c90d91c7426beb9cdbaa6759ccb82824a breaks it again.

**Comment by twinaphex** [comment]
Well, I need to be able to send more keys to the input driver now than just the regular 16-button libretro gamepad keys. Perhaps we need to whitelist only MENU_TOGGLE so that we can at least check that, that might put an end to these issues.

**Comment by joolswills** [comment]
it affects other hotkeys too. I have select + start to exit (select is hotkey enable button) and start is exit. It will exit with start with the above issue.

**Comment by twinaphex** [comment]
Try this out -

https://github.com/libretro/RetroArch/commit/8162b77baee70dfb48c06b98cbd4e8b578005813

**Comment by joolswills** [comment]
Most hotkeys are fine - but menu toggle is triggered without pressing input_enable_hotkey_btn

**Comment by twinaphex** [comment]
Sigh - this input system is garbage legacy code seriously. 

Alright, I'll add a different workaround so that I can access 'menu toggle' state changes without it affecting keys_pressed.

**Comment by joolswills** [comment]
Your efforts are much appreciated thanks.

**Comment by twinaphex** [comment]
OK, try this commit -

https://github.com/libretro/RetroArch/commit/450c6656193ef58abe2393332dbb871ec652b26a

Micro-performance wise it should be slower but it should work at least.

**Comment by joolswills** [comment]
Looks good - all hotkeys working as they should with input_enable_hotkey_btn pressed / not pressed

**Comment by twinaphex** [comment]
OK, so can we close this?

**Comment by joolswills** [comment]
yep. Thanks again. 1.2.3 tagging time? :)

**Comment by twinaphex** [comment]
1.2.2 rather.
