### ISSUE TITLE
pcsx_rearmed: freezes game restart

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#1984]
Try restart a game in pcsx_rearmed in the Quick Menu, it freezes with "ari64_reset". You have to kill retroarch.

Tested on odroid u3, lubuntu, RA last git.

**Comment by Holzhaus** [comment]
You might want to close this and open a new issue at the proper location:
https://github.com/libretro/pcsx_rearmed

**Comment by sergiobenrocha2** [comment]
It's not possible to open a new issue there...

**Comment by fr500** [comment]
I'll ask twinaphex to enable the issue tracker there
