### ISSUE TITLE
1.2 Wii version corrupting flash drive

### ISSUE THREAD

**Issue by 47iscool** [libretro/RetroArch#1985]
Was running nestopia with ra on USB and tried to load smb3 and went back to the hbc. The device was a 16 GB Sandisk cruzer glide.

**Comment by twinaphex** [comment]
I could maybe ask @ToadKing to try looking into this issue if he can.

**Comment by 47iscool** [comment]
Thanks.

**Comment by twinaphex** [comment]
https://github.com/libretro/RetroArch/commit/45e9055a63ba31d39b552e41ce7dc221a91c9aaa

This issue should probably be fixed by now. You will be able to test if this is the case in RetroArch 1.2.3.

**Comment by 47iscool** [comment]
Thanks for looking into it.

**Comment by fr500** [comment]
Can you test on the current nightlies and reopen if it still happens?

**Comment by 47iscool** [comment]
I downloaded a newer svn of it a nothing would load. It just keeps giving me a DSI execption.
