### ISSUE TITLE
Quick Menu > Core Input Remapping now available in all cores?

### ISSUE THREAD

**Issue by dankcushions** [libretro/RetroArch#2000]
Hi,

I'm trying to resolve this issue I have with the way that the FBA-lr core handles mapping neogeo buttons on a snes pad: http://blog.petrockblock.com/forums/topic/different-controller-configs-for-retroarch-menugames/

Essentially I can get a configuration that works right in games, but then it makes the buttons do different things in the RGUI - I want it to be correct in both, ideally! :) I'm told that the 'Quick Menu > Core Input Remapping', would solve this issue, but it doesn't appear in the quick menu of this core - why? It DOES appear in other cores, although I don't have issues with those :)

I'm running v1.2.2, with this core: https://github.com/libretro/fba-libretro

**Comment by twinaphex** [comment]
My guess is that core does not have input descriptors hooked up. If a core does not implement descriptors, then 'Core Input Remapping' will not show up.

**Comment by fr500** [comment]
Yes this is a core issue, the old fba core doesn't have descriptors.
