### ISSUE TITLE
[Netplay] All the error messages now print the  same message

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2003]
Instead of the correct message

**Comment by fr500** [comment]
Also netplay seems to be failing more than before for some reason

**Comment by thatcadguy** [comment]
I can confirm this on both Windows and Android platforms. Using fresh installs from buildbot and simply trying to use netplay results in a "movie playback has started" error on the client side usually.

**Comment by fr500** [comment]
While it's true that this happens, (the message is incorrect) netplay is working on all the scenarios I have tested

**Comment by twinaphex** [comment]
Closing this, if it still happens, reopen this issue and we can look at it.
