### ISSUE TITLE
ipv6 broken

### ISSUE THREAD

**Issue by bazzinotti** [libretro/RetroArch#2004]
I am an OSX Yosemite user and I have been netplaying with Win7 x64 users the past couple of days.. All was working fine until I started having problems with the connections today.. I narrowed the problem down to when my RA server / OS chooses to use ipv6. 

In my case, the disconnection issues were all mitigated by using `networksetup -setv6off Wi-Fi` -- but disabling ipv6 for my whole user/OS is obviously a temporary solution. 

----- personal note ------
instructions for disabling ipv6 on mac or re-enabling ipv6 @ http://osxdaily.com/2014/04/18/disable-ipv6-mac-os-x/

`lsof -i :[port]` was used to debug the server listener

**Comment by twinaphex** [comment]
What is the status on this?

**Comment by twinaphex** [comment]
Closing this due to lack of response, assuming issue fixed until noted otherwise.
