### ISSUE TITLE
Chinese path garbled

### ISSUE THREAD

**Issue by ssc19940105** [libretro/RetroArch#2007]
Chinese path garbled.

**Comment by twinaphex** [comment]
We don't have a Chinese translation yet.

Also, this would make Unicode text rendering necessary. If you know Chinese (simplified or traditional), you can give us the translation in advance in some text file, but it would just take us some time to come up with the necessary code that would allow us to render these characters.

**Comment by Alcaro** [comment]
I'm pretty sure that is not the bug he's reporting. Instead, I believe he's thinking of this:
![archjap](https://cloud.githubusercontent.com/assets/5085186/8849623/68f09f62-3141-11e5-9743-010a3b18d64f.png)
(text used: れとおあく.zip)

But the solution is the same: We need proper Unicode support.

**Comment by ssc19940105** [comment]
YES. I think the proper Unicode support is Needed. The solution is the same as Alcaro‘s.
I will try translate it into simplified chinese.

**Comment by tlanks** [comment]
R U using bitmapsfont on linux ?

**Comment by gouchi** [comment]
I know you are not in favour of using library but we can check this tiny library called [libraqm](https://github.com/HOST-Oman/libraqm), a library for complex text layout,  at least to be inspired by.

**Comment by neunenak** [comment]
As an addition to this, not even rendering the character ê works in the select file UI. I'd definitely like to see proper unicode support.

**Comment by bparker06** [comment]
@neunenak This should now work as the first 256 codepoints are supported as of last month... but we still need a proper solution for expanding the Unicode support with regard to how the font rendering works currently... a 60MB+ bitmap texture isn't really an option.

**Comment by gouchi** [comment]
This issue should be closed.
