### ISSUE TITLE
Compile error on RetroArch from Arch on Banana Pi

### ISSUE THREAD

**Issue by anauj0101** [libretro/RetroArch#2010]
I’m having issue compiling using Arch Linux on my Banana Pi. I’m 95% positive I have everything extra and all dependencies installed. I think this is a linking issue, but have no clue how to correct it. I have mostly been following your tutorials so I figured I would ask you first. I get these errors after compile. I have also posted the config line I am using. Please help.I'm sure its something simple I am overlooking.  Thanks in advance
<code>
./configure --enable-gles --disable-oss --disable-sdl --disable-netplay

obj-unix/input/drivers/udev_input.o: In function `udev_input_hotplug_available':
/root/retroarch/RetroArch/input/drivers/udev_input.c:267: undefined reference to `udev_monitor_get_fd'
obj-unix/input/drivers/udev_input.o: In function `udev_input_handle_hotplug':
/root/retroarch/RetroArch/input/drivers/udev_input.c:352: undefined reference to `udev_monitor_receive_device'
/root/retroarch/RetroArch/input/drivers/udev_input.c:364: undefined reference to `udev_device_get_property_value'
/root/retroarch/RetroArch/input/drivers/udev_input.c:365: undefined reference to `udev_device_get_property_value'
/root/retroarch/RetroArch/input/drivers/udev_input.c:366: undefined reference to `udev_device_get_property_value'
/root/retroarch/RetroArch/input/drivers/udev_input.c:367: undefined reference to `udev_device_get_action'
/root/retroarch/RetroArch/input/drivers/udev_input.c:368: undefined reference to `udev_device_get_devnode'
/root/retroarch/RetroArch/input/drivers/udev_input.c:405: undefined reference to `udev_device_unref'
/root/retroarch/RetroArch/input/drivers/udev_input.c:405: undefined reference to `udev_device_unref'
obj-unix/input/drivers/udev_input.o: In function `open_devices':
/root/retroarch/RetroArch/input/drivers/udev_input.c:615: undefined reference to `udev_enumerate_new'
/root/retroarch/RetroArch/input/drivers/udev_input.c:620: undefined reference to `udev_enumerate_add_match_property'
/root/retroarch/RetroArch/input/drivers/udev_input.c:621: undefined reference to `udev_enumerate_scan_devices'
/root/retroarch/RetroArch/input/drivers/udev_input.c:622: undefined reference to `udev_enumerate_get_list_entry'
/root/retroarch/RetroArch/input/drivers/udev_input.c:641: undefined reference to `udev_device_unref'
/root/retroarch/RetroArch/input/drivers/udev_input.c:624: undefined reference to `udev_list_entry_get_next'
/root/retroarch/RetroArch/input/drivers/udev_input.c:626: undefined reference to `udev_list_entry_get_name'
/root/retroarch/RetroArch/input/drivers/udev_input.c:630: undefined reference to `udev_device_new_from_syspath'
/root/retroarch/RetroArch/input/drivers/udev_input.c:631: undefined reference to `udev_device_get_devnode'
/root/retroarch/RetroArch/input/drivers/udev_input.c:644: undefined reference to `udev_enumerate_unref'
obj-unix/input/drivers/udev_input.o: In function `udev_input_init':
/root/retroarch/RetroArch/input/drivers/udev_input.c:718: undefined reference to `udev_new'
/root/retroarch/RetroArch/input/drivers/udev_input.c:725: undefined reference to `udev_monitor_new_from_netlink'
/root/retroarch/RetroArch/input/drivers/udev_input.c:728: undefined reference to `udev_monitor_filter_add_match_subsystem_devtype'
/root/retroarch/RetroArch/input/drivers/udev_input.c:729: undefined reference to `udev_monitor_enable_receiving'
obj-unix/input/drivers/udev_input.o: In function `udev_input_free':
/root/retroarch/RetroArch/input/drivers/udev_input.c:591: undefined reference to `udev_monitor_unref'
/root/retroarch/RetroArch/input/drivers/udev_input.c:593: undefined reference to `udev_unref'
/root/retroarch/RetroArch/input/drivers/udev_input.c:591: undefined reference to `udev_monitor_unref'
/root/retroarch/RetroArch/input/drivers/udev_input.c:593: undefined reference to `udev_unref'
obj-unix/input/drivers_joypad/udev_joypad.o: In function `udev_add_pad':
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:230: undefined reference to `udev_device_get_parent_with_subsystem_devtype'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:234: undefined reference to `udev_device_get_sysattr_value'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:237: undefined reference to `udev_device_get_sysattr_value'
obj-unix/input/drivers_joypad/udev_joypad.o: In function `udev_hotplug_available':
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:162: undefined reference to `udev_monitor_get_fd'
obj-unix/input/drivers_joypad/udev_joypad.o: In function `udev_joypad_handle_hotplug':
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:412: undefined reference to `udev_monitor_receive_device'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:419: undefined reference to `udev_device_get_property_value'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:420: undefined reference to `udev_device_get_action'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:421: undefined reference to `udev_device_get_devnode'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:438: undefined reference to `udev_device_unref'
obj-unix/input/drivers_joypad/udev_joypad.o: In function `udev_joypad_destroy':
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:403: undefined reference to `udev_monitor_unref'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:406: undefined reference to `udev_unref'
obj-unix/input/drivers_joypad/udev_joypad.o: In function `udev_joypad_init':
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:533: undefined reference to `udev_new'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:537: undefined reference to `udev_monitor_new_from_netlink'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:540: undefined reference to `udev_monitor_filter_add_match_subsystem_devtype'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:541: undefined reference to `udev_monitor_enable_receiving'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:544: undefined reference to `udev_enumerate_new'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:548: undefined reference to `udev_enumerate_add_match_property'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:549: undefined reference to `udev_enumerate_scan_devices'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:550: undefined reference to `udev_enumerate_get_list_entry'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:554: undefined reference to `udev_list_entry_get_name'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:555: undefined reference to `udev_device_new_from_syspath'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:556: undefined reference to `udev_device_get_devnode'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:560: undefined reference to `udev_device_unref'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:552: undefined reference to `udev_list_entry_get_next'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:563: undefined reference to `udev_enumerate_unref'
obj-unix/input/drivers_joypad/udev_joypad.o: In function `udev_joypad_destroy':
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:403: undefined reference to `udev_monitor_unref'
/root/retroarch/RetroArch/input/drivers_joypad/udev_joypad.c:406: undefined reference to `udev_unref'
collect2: error: ld returned 1 exit status
Makefile:103: recipe for target 'retroarch' failed
make: *** [retroarch] Error 1
</code>

**Comment by Kivutar** [comment]
Maybe you are missing some udev dependancy?
Try to check our retroarch package in Lakka, it contains compilation instructions, and works well on bananapi.

**Comment by Kivutar** [comment]
Compilation works well on Banana Pi. We should close this bug.
