### ISSUE TITLE
Manual Config Overriding AutoConfig

### ISSUE THREAD

**Issue by Taconut** [libretro/RetroArch#2018]
I set up a couple of controllers and saved them as autoconfigs using the built-in GUI, but the only way to actually get the AutoConfigs to work is manually deleting the Input lines in the cfg file. Could you add an option to make AutoConfig take higher precedence over Manual Configuration or at least add a way to clear all the the input configs directly from the GUI?

**Comment by fr500** [comment]
No it makes no sense whatsoever, we actually moved away from this a few weeks ago. Manual should always take precedence even if autoconfig is enabled..

There is a user # default all to reset user binds for a particular user.

**Comment by Taconut** [comment]
I was unaware that "Default" _cleared_ the config. I was under the impression that it chose default options for the selected controller (as if it were recognized by autoconfig). Sorry about that.

**Comment by fr500** [comment]
lol, no need to be sorry, yes it clears the manual binds, so it will move back to autoconf defaults.
