### ISSUE TITLE
Multiple controllers on retroarch 

### ISSUE THREAD

**Issue by Fadi5555** [libretro/RetroArch#2019]
Hi there:

I have an iPad Air 2 and used retroarch for long time. for that I like it so much.

Well, is there any method to play 2 PS3 or ps4 controllers on retroarch like play crash team racing on it?
Specially I saw on settings on retroarch there is 4 controller ready to mapping but  I don't how to connect two controllers on it. So please help me.

Other thing: when the new update will come with XMB support (v1.2 or so)?
The repo on cydia is breakdown.so Ipif the update come how we can download it?
Thanks

**Comment by fr500** [comment]
Hi, this belongs in the forum not here.
I'm closing this but feel free to discuss here, I know there are issues with forum registration, I just don't want this marked as an issue.
