### ISSUE TITLE
(libretro) Run multiple instances of the same game

### ISSUE THREAD

**Issue by arthurlutz** [libretro/RetroArch#2024]
This is a far fetched issue I'm submitting, but it's a way to start discussing this idea.

The idea would be to enable a multiplayer mode for single player games where players would play side by side the same game. For example a 2 player launch would launch two windows side by side with an instance of retroarch configured for player1's gamepad on the left and an instance of retroarch configured for player2's gamepad on the right. The players would then manually synchronize and play together (for speed or points, or anything the imagination can think of). 4 players would split the screen in four. With the size of flat screen TVs and the small resolution of retro games, this would be visually feasible right ?

I've submitted this idea to the recallbox project which could use multiple running instances of RetroArch (cf discussion on https://github.com/digitalLumberjack/recalbox-os/issues/332 with a window manager). But maybe this could be a RetroArch feature and benefit other users.

**Comment by hizzlekizzle** [comment]
I believe it would have to be achieved through multiple instances currently. Such a thing has been discussed as a capability with libretro 2.0, though.

**Comment by arthurlutz** [comment]
@hizzlekizzle thanks for your answer, any references (urls) of the discussions you are referring to ?

**Comment by hizzlekizzle** [comment]
I think the discussion occurred on IRC, so no real record of it, but plans for libretro 2.0 happen on the ARB repo:
https://github.com/libretro/libretro-arb

**Comment by RobLoach** [comment]
Mind creating an issue in the ARB repository for this? I've been wanting to have a `libretro_instance_t* context` be passed around to each core call :wink:
