### ISSUE TITLE
[Feature Request] "Cloudify" Roms and saves

### ISSUE THREAD

**Issue by BlackLotus** [libretro/RetroArch#2028]
I know that there was actually some talk about this and I just wanted to open an official request.
I sometimes play on different devices (at home,on the go,at my parents house,...) and I usually have different devices which have only one thing in common, retroarch with internet access.
So it would be pretty neat to be able to just load a rom from an ftp server/google drive/owncloud/whatever or at least keep my save states in sync between all those devices.
Most of my roms don't take that much space and save states normally even less so this would be a pretty nifty feature.

**Comment by fr500** [comment]
Honestly I think that's just bad design, trying to add OS features to an application has led us to this very place, a pdf reader in a browser that can leak personal information.
Apps should do their thing and nothing else. 
That said, even as I speak I've been working into implementing Google SAF into the android port.

**Comment by Lasborg** [comment]
I would love to see cloud support primarily for saves.

**Comment by RobLoach** [comment]
Offloading this to something like Google Drive, Dropbox, [OwnCloud](https://owncloud.org/), [Syncthing](https://syncthing.net/), or something similar will save us lots of work and time.

**Comment by fr500** [comment]
Yeah supporting one platform by ourselves would  mean "why no other platform" and endless bitching like that.
Sadly supporting any of these services would need SSL as a bare minimum and that's a big dependency for us to drag around.

**Comment by Alcaro** [comment]
SSL is a big deal on consoles, yes. But the other platforms have either OpenSSL or SChannel preinstalled already, and we don't mind dependencies on things that already exist.

I've got a few SSL library wrappers [here](https://github.com/Alcaro/Arlib/tree/master/arlib/socket). Feel free to copy whatever you want, though do note that some of them are broken.

...actually, I think TLSe may be small enough to include on consoles.

**Comment by CanadianJeff** [comment]
duplicate: #3269
duplicate: #3848

**Comment by CammKelly** [comment]
There's a $100 bounty on this linked to #6875 that will need to be moved over to this on bountysource.

https://www.bountysource.com/issues/59506367-feature-native-cloud-saving

**Comment by RobLoach** [comment]
@CammKelly Thanks for the heads up. Let's just move this discussion over there. :+1:
