### ISSUE TITLE
Bluetooth gamepad activated during Mupen64 core crashes, and activating it while using HID gamepad driver does same

### ISSUE THREAD

**Issue by FMArthur** [libretro/RetroArch#2035]
I've got an iPega PG-9025 connected to an LG G3.

The crash is unique to the Mupen64Plus core within Retroarch as far as I can tell (have used SNES9x, Genesis Plus GX, PCSX-reARMed, Gambette, Meteor, PPSSPP), and does not happen in standalone (Mupen64Plus AE). None of the core options can prevent it.

Some relevant info:
- If Mupen64Plus content is started *after* the gamepad activates within the RA menu (pressing a button, making the little yellow text appear acknowledging it), RA exits instantly and saves no configs (ie crashes).
- If the gamepad is activated *during* gameplay of Mupen64Plus content, the same happens.
- If Mupen64Plus content is started and then I go to the Retroarch menu and activate the gamepad while there, *the game can be resumed and played with the gamepad*.
- Non-Mupen64Plus: If Retroarch is restarted after switching the gamepad driver to HID (instead of Android), it will crash in the exact same fashion as Mupen64Plus as soon as the gamepad is activated.

Given the last two points above I think the first thing to check is whether the core is overriding the gamepad driver to be HID. I've heard of similar crashes from people with other bluetooth gamepads so it sounds like the same issue, but I don't know if all gamepads suffer from it.

**Comment by fr500** [comment]
Are you running lollipop? I only managed to reproduce this on my 5.1 devices

**Comment by Steveice10** [comment]
Relevant: https://github.com/libretro/mupen64plus-libretro/issues/259

**Comment by fr500** [comment]
This is a really really really weird issue.
Some JNI function is returning null instead of what it should only when this core is being loaded, I think it could be due to libco.

Sadly fixing this is beyond my abilities.

**Comment by fr500** [comment]
It's probably solved by now.
