### ISSUE TITLE
Load from Collection opens the wrong item

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#2036]
Trying to open a game from a playlist opens the wrong game with GLUI.
Same playlist works without problem with XMB.

Tested on Win7 x64.

**Comment by Tatsuya79** [comment]
I'm still trying to figure out what is wrong here.
I made a scanning of a No-Intro PC-Engine/SGX set folder under XMB.
Then opened it, works fine.

I switch to GLUI, Load Content -> Select from Collection -> NEC - PC Engine - TurboGrafx 16.lpl
Works fine.

I do the same for NEC - Super Grafx.lpl: wrong roms, 1941 opens Granzort, Aldynes opens Daimakai Mura...

I tried to make a MAME.lst with a script, I suspect something strange happening with the ordering of the names, if they start with ' or something else...

**Comment by Tatsuya79** [comment]
Ok, sorry figured it a bit better, has nothing to do with GLUI.

If on XMB you don't use the playlists (left-right motion in the menu) but do Load Content -> Select from Collection, just like with GLUI the Super Grafx.lpl exhibits the same problem.

**Comment by Kivutar** [comment]
> I tried to make a MAME.lst with a script, I suspect something strange happening with the ordering of the names, if they start with ' or something else...

I think the source of the bug can be that

**Comment by Tatsuya79** [comment]
That can't be just that.
How can it work in XMB Playlist mode (pushing right at Retroarch start) and not with "Load Content from Collection"?
Aren't those 2 actions using the same functions?

**Comment by Kivutar** [comment]
Yes they use the same functions. And the bug does not happen for me, with my ROM names.

**Comment by Tatsuya79** [comment]
It also happens for Game Gear No-Intro set, no name changed.

Load Content -> from Collection = opens the bad file
XMB horizontal playlist = works OK

**Comment by Tatsuya79** [comment]
Checking old issues, this one fixed itself.
