### ISSUE TITLE
New to RetroArch having bizarre issues 

### ISSUE THREAD

**Issue by HahPagan** [libretro/RetroArch#2039]
I can use almost any emulator in retroarch with no problem except for mupen64 and DeSmuME anytime I load a ROM they immediately crash. Also I can't seen to find PPSSPP in the Updater so I can play PSP games, is there a way for me to manually add it. If anyone can help me with these issues it would be greatly appreciated. I'm using the 1.2.2 stable build.

**Comment by fr500** [comment]
Please use the forum for end-user issues
