### ISSUE TITLE
[Android] Better behavior when you press the keyboard icon in the overlay

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2041]
Press the keyboard icon in the joypad overlay, on android, and you'll be stuck without any overlay. I know you can workaround it if you set some keyboard overlay at Settings --> Onscreen Overlay --> Keyboard Overlay Preset, but it should be set by default, or simply use a default overlay without this keyboard button.

**Comment by fr500** [comment]
It only needs a default set much like we have a default for the gamepad

**Comment by fr500** [comment]
Should be fixed here http://git.io/vGLm3

**Comment by thatcadguy** [comment]
Most of the time on my Note II running 1.2.2, the keyboard won't appear when the keyboard button is pressed anyway. Yes, the keyboard preset has been set.

**Comment by fr500** [comment]
It is fixed upstream
