### ISSUE TITLE
[Android] Menu is gone in GLUI, after downloaded some cores

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2046]
Get this after I downloaded some cores and tried to back to the previous menus, using 2015-08-18 nightly.

![screenshot_2015-08-17-23-04-01](https://cloud.githubusercontent.com/assets/5431285/9320814/a3a451f6-4534-11e5-81fd-679d7ee78126.png)

**Comment by twinaphex** [comment]
Yeah, this seems to happen on some phones with a specific DPI, @heuripedes has never been able to reproduce it and I can't reproduce it on my devices so we're kinda stuck here.

**Comment by sergiobenrocha2** [comment]
Mine is 960x540 - 240 dpi btw

**Comment by fr500** [comment]
I don't think it happens on a particular DPI, I think it happens when you "rush" the core updater (example, press B before the list loads).
