### ISSUE TITLE
[Android] Very small font on XMB

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2047]
The XMB font size on Android is too small since 1.2.1 I think, take a look:

960x540 (240 dpi) Android:
![screenshot_2015-08-17-19-36-07](https://cloud.githubusercontent.com/assets/5431285/9320453/b7d71888-4530-11e5-829a-dafdc566d4ce.png)

960x540 linux laptop:
![display font size_x_1](https://cloud.githubusercontent.com/assets/5431285/9320454/bf1534b8-4530-11e5-809d-d90800e01b8e.png)

Testing with the nightly.

In the 1.2 release, it was much better:

![screenshot_2015-08-17-22-50-22](https://cloud.githubusercontent.com/assets/5431285/9320640/be501406-4532-11e5-9817-27cb434d565d.png)

**Comment by sergiobenrocha2** [comment]
@Kivutar

**Comment by Kivutar** [comment]
If I understand it well, the font renderer on android and the font renderer on linux doesn't output the same font size?

**Comment by sergiobenrocha2** [comment]
Yup, do they should be equal?
