### ISSUE TITLE
RetroArch Overwrites Mupen64Plus Core Options Back to Default

### ISSUE THREAD

**Issue by newoski** [libretro/RetroArch#2049]
I'm using latest 1.2r2 release and the latest Mupen64Plus core. When I change per-core-options for Mupen (deadzone=5) it automatically reverts back to the default 15, every time RetroArch loads the per core options.

**Comment by fr500** [comment]
so, this is with core-specific settings enabled?

**Comment by newoski** [comment]
For my mupen related config, yes:

core_specific_config = "true"

**Comment by newoski** [comment]
Should I change that to "false? I can share my full config + core options if you'd like...
