### ISSUE TITLE
Force load of game on current selected core regardless of file extension?

### ISSUE THREAD

**Issue by liddo** [libretro/RetroArch#2055]
The File browser doesn't show any files in a zip and won't load games with different file extensions. Needs to be a way to force feed these cores with games that don't have the extension as defined in the core's info. I'm working around this by renaming games I want to play, so I know they're working. The games wont even load even after it is scanned and shows up in the Content browser.

You might think that I need to clean my game collection and use more standard file extensions, well the MAME (previously MESS) sets have all sorts of different file extensions (for GBC there is bin and u2 for example). So its kind of hard right now to share a single rom collection between MAME and RA right now.

**Comment by fr500** [comment]
You can show files with unsupported extensions just fine, it's under menu settings.

**Comment by liddo** [comment]
That settings effects the file browser, but not inside zips or the content browser. Unless its a separate issue altogether or I'm doing it wrong.
