### ISSUE TITLE
[MAC] Several issues when using a second display

### ISSUE THREAD

**Issue by Trevor-Z** [libretro/RetroArch#2057]
If I move the Retroarch window to the second display, and press F for fullscreen, the second display goes blank, and the contents appear fullscreen on the primary one. To have it fullscreen on the second one, I have to press the green maximize button.

However, after having Retroarch go fullscreen on the second display, the contents don’t scale properly, the whole GUI follows the 1x, 2x, 3x scale option, not just the games. Also both the GUI and the games appear in the lower left corner, instead of in the center of the screen. To get the games to appear properly centered, I have to load them in a window, and then maximize by pressing the green button. And if I try to load another game, by pressing F1, again the GUI and the next game will appear in the lower left corner of the screen, in the wrong scale.

I’m using an early 2011 MacBook Pro, 13 inches, with OS X 10.10.5.

Compiled Retroarch myself, but can’t quite tell which version is it. I downloaded the source on Aug 22, around 00:40.

**Comment by Trevor-Z** [comment]
Hi, sorry for the late answer, I forget to check the mail account I use for Github.

Well, I don't know, my MacBook went kaput and I'm using a Windows laptop for now. 

But I did notice a similar issue on Windows a while ago, but didn't pay much attention to it. Perhaps I should try to reproduce it and file another bug report.

**Comment by orbea** [comment]
Okay, given that this is a 4 year old issue I am not sure anyone can reproduce anymore I am going to close this. If anyone can reproduce this in the future please let us know!
