### ISSUE TITLE
[Android] Overlay persists over UI when temporarily leaving the app and returning to it, even if "Hide Overlay In Menu" is set to Off 

### ISSUE THREAD

**Issue by georaldc** [libretro/RetroArch#2058]
Behavior fixes itself when resuming a running core but exiting to android while something is running and bringing retroarch back up will show the overlay again on top of the Retroarch Menu.

**Comment by sergiobenrocha2** [comment]
Happens with me too.

**Comment by fr500** [comment]
Yes it happens when switching, I think the value of the hide overlays variable is resetting

**Comment by thatcadguy** [comment]
I can confirm this as well.

**Comment by orbea** [comment]
@georaldc , @sergiobenrocha2 and @fr500 Is this still an issue?
