### ISSUE TITLE
SNES9X Next- Mega Man X Chill Penguin reset bug (on Wii)

### ISSUE THREAD

**Issue by RockmanYoshi** [libretro/RetroArch#2059]
When you reach the boss fight for Chill Penguin in Mega Man X, the boss will usually spawn these ice penguin statues sometime during the fight. When you hit one with your buster it will then go to the "Weapon Acquired" screen, then it'll force you to go replay the intro stage repeatedly. It's a well known ROM glitch but this only happens frequently in Next as opposed to GX.

**Comment by Alcaro** [comment]
Cores issues should be raised on [the core repo](https://github.com/libretro/snes9x-next).
