### ISSUE TITLE
error: no member named 'osk_overlay'

### ISSUE THREAD

**Issue by eduo** [libretro/RetroArch#2062]
I'm getting this error with most recent version, after download of master and cores, and compilation and move of all cores.

From directory [..]/RetroArch-master/apple compiling with script/build

> In file included from /Users/eduo/Downloads/RetroArch-master/griffin/griffin.c:602:
> /Users/eduo/Downloads/RetroArch-master/griffin/../configuration.c:793:29: error: no member named  'osk_overlay' in 'struct
>      settings::(anonymous at ../../gfx/../input/../configuration.h:202:4)'
>     if (!*settings->input.osk_overlay)
>           ~~~~~~~~~~~~~~~ ^
> 1 error generated.
>
> ** BUILD FAILED **
>
>The following build commands failed:
>	CompileC build/RetroArch_iOS.build/Release-iphoneos/RetroArch.build/Objects-normal/armv7/griffin.o /Users/eduo/Downloads/RetroArch-master/griffin/griffin.c normal armv7 c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)

I was surprised since I fully expected an error in the cores or something related to provisioning of signing, but this seems to be in the core source yet I don't see any issues reported for it (which convinces me that the error is mine, but I can't figure out why).

**Comment by eduo** [comment]
I think I've found what it is. Script fetch-submodules.sh is not mentioned in the instructions, but according to https://github.com/libretro/RetroArch/issues/1486 it should be run for non-jailbroken installations.

I'll check after and close the issue myself if this fixes it.

**Comment by fr500** [comment]
Should be fixed already
