### ISSUE TITLE
Some cores appear to be missing from Online Updater -> Core Updater on some architectures

### ISSUE THREAD

**Issue by sylverpyro** [libretro/RetroArch#2063]
Some cores, such as bnes, are missing from the Core Updater menu in the Online Updater from the Linux version of RetroArch.  It is present in the OS X version however.  Is this because bnes is not available on Linux or is it a filtering problem?  If it is intentional, is there somewhere that someone can check what cores are available on what platform?

**Comment by fr500** [comment]
Of course not all the cores build for all platforms. It's not intentional but it's not really an issue, it's more like wysiwyg.

We're quite shorthanded
