### ISSUE TITLE
Enhancement Request: Allow users to change what core is used to open a rom

### ISSUE THREAD

**Issue by sylverpyro** [libretro/RetroArch#2064]
After a ROM is opened for the first time, the core used to do so appears to be recorded in the playlist (.lpl) file.  Every time the ROM is selected after this it is launched with the same core.  The only method I've found to change the 'stored' core for that ROM is to edit the .lpl file and replace the core name and path with DETECT.  After that I'm able to select a different core.  

Normally this not an issue, unless a ROM gets launched with a core that immediately crashes on load or on load state.  

Some option to 'reset' or chose a different core to launch the ROM with would help with this.

**Comment by Kivutar** [comment]
I agree. Having to select the core for each rom is boring. We could have a setting to set a default core per system.

**Comment by fr500** [comment]
I don't think we can do per system, there is no "system" concept, but we could do per collection

**Comment by Kivutar** [comment]
Yes, collections, rdb, and systems map almost 100% (there are one or two exception but we can live with that)

**Comment by fr500** [comment]
Closing, moving discussion to #2959 since it's related.
