### ISSUE TITLE
Input from Xbox 360 Wireless Receiver ignored (Linux)

### ISSUE THREAD

**Issue by sylverpyro** [libretro/RetroArch#2065]
A 'ID 045e:0719 Microsoft Corp. Xbox 360 Wireless Adapter' is being detected and autoconfigured properly by RetroArch.  However, all input from a controller connected to the receiver is being ignored by the RetroArch menu, emulators, and the command line retroarch-joyconfig.  However jstest (from joyutils) on /dev/inputs/js1 shows output from the controller.  Keyboard input and input from a wired Xbox controller however work just fine.  

Running RetroArch compiled from git on Arch Linux with the stock xpad kernel driver.

**Comment by sergiobenrocha2** [comment]
This is the same I use here, and it's working very well last time I checked. You don't need to bind the inputs, there's already an auto config for it (0719h = 1817 --> https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Xbox_360_Wireless_Receiver.cfg)

It's probably a kernel issue.

**Comment by sergiobenrocha2** [comment]
What's the kernel you are using? It seems 4.2 has better support.

Take a look at this thread: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1272765

I had to follow the tip from comment 32.

**Comment by sylverpyro** [comment]
4.2 Just officially dropped, so it will probably be in Arch in a week or
two.  I'll update this issue if that resolves the issue or not.  Thanks!

**Comment by christ776** [comment]
Hi, I'm having a similar issue on OS X Yosemite with RetroArch 1.2.2 and also using some of the latest commits, but in my case it's just the right analog stick who's being ignored, should I open a new bug ?

**Comment by parkerlreed** [comment]
Happening here too. Both xpad and xboxdrv inputs are ignored. It finds the auto config but the buttons do nothing. 

Arch 
4.1.8-1

**Comment by parkerlreed** [comment]
If you're on 4.2 seriously just relink the controller. Mine was working in other games but I was still getting the blinking light in xpad. Relinked the controller and now it no longer blinks and retroarch sees it.

**Comment by christ776** [comment]
Hi ! Regarding OS X, is there a workaround? 

thanks,

**Comment by MoochMcGee** [comment]
For me, even a wired Xbox 360 controller doesn't work on latest git in Arch Linux.

**Comment by orbea** [comment]
This issue is basically that when you controller matches an existing config, but the buttons are incorrect the buttons will either be incorrect or it won't work at all.

The solution is remove the offending autoconfig file and then rebind it manually, this is either because the controller's VID:PID number matches unrelated gamepads or that the autoconfig file is just wrong.

The other possibility are OS and kernel driver issues which is not surprising with xpad.

**Comment by orbea** [comment]
For the former issue I am going to close this in favor of the older and more general issue. https://github.com/libretro/RetroArch/issues/3914

For the latter issue, take it upstream to the kernel / driver devs.
