### ISSUE TITLE
Playstation 4 Controller - Dinput

### ISSUE THREAD

**Issue by TheDrifter363** [libretro/RetroArch#2092]
Hello,

I have a request, if I may. It seems as if the latest stable release of retroarch doesn't have an autoconfig file for the ps4 controller. I saw a cfg file in the HID folder, but that doesn't seem to work under Windows 7 64 bit. So I created a dinput cfg file. I thought it might be helpful if I uploaded it somewhere, so here it goes. Please let me know if this is satisfactory.

File name: "Wireless Controller.cfg"

input_driver = "dinput"
input_device = "Wireless Controller"
input_vendor_id = "1356"
input_product_id_id = "1476"
input_b_btn = "1"
input_y_btn = "0"
input_select_btn = "8"
input_start_btn = "9"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_left_btn = "h0left"
input_right_btn = "h0right"
input_a_btn = "2"
input_x_btn = "3"
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "7"
input_l3_btn = "10"
input_r3_btn = "11"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+5"
input_r_y_minus_axis = "-5"

**Comment by fr500** [comment]
This is the correct repo:
https://github.com/libretro/retroarch-joypad-autoconfig
Please send a pull request and don't forget to add descriptors too like in this example
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/8Bitdo%20NES30%20GamePad%20Joystick.cfg
