### ISSUE TITLE
(Linux, Windows, maybe all platforms supporting shaders) Cannot change shader params

### ISSUE THREAD

**Issue by netux79** [libretro/RetroArch#2093]
When adding a shader that support params, the params appear with its default values but cannot be changed, left, right are not working... however if a press start it reset the param to its default value (in the case I'm loading a preset)... it start failing when updating RA from 1.2.2-r226 to 1.2.2-r228 (Ubuntu 15.04). I also use RA on Windows and the same problem is present with latest nightly.

**Comment by twinaphex** [comment]
Describe what it did before vs. what it does not now.

Also, r226 does not really mean anything to me, which git hash?

**Comment by netux79** [comment]
It's simple, just try using a shader that accepts params like image-adjustment in the latest build. Then try to adjust the params of the shaders from rgui and you will see that the params are no longer editable from the menu. If you press LEFT or RIGHT to adjust them, nothing happens. Before the issue you can adjust the params of the shader and then apply the changes and notice the changes in game.. (like adjusting the contrast, brightness, etc. depending on the shader).

As I used the Linux version updating from the (test/nightly) PPA repository I cannot define exactly which commit hash is the one giving the problem as this repository is not actually updated daily... however I will use the Windows version that is also failing so I can give you more details on this...

Also, I know this is not the best place to ask but I will take the chance: is the wiiusb_hid driver already working for the RA Wii version? I tried it but it was not successful, I just got an unusable RA as I cannot move in the menus.

Thanks

**Comment by twinaphex** [comment]
The HID driver needs autoconfig files for any pad to be detected. You'd have to copy the retroarch-autoconfig directory to your Wii's SD card (or whatever storage device it is), point Autoconfig Directory in RA to that dir, and then restart to apply the changes.

**Comment by fr500** [comment]
should I bundle autoconf with the nightlies then?

**Comment by twinaphex** [comment]
@fr500 I guess.

@netux79 - are you talking about 'Preview Shader Parameters' or 'Menu Parameters'? I'd like for us to be specific about the specific issue so that I can fix this easier.

**Comment by netux79** [comment]
@twinaphex - Talking about "Menu Parameters", I also can edit them in "preview shader parameters" but these are not permanent, "Menu Parameters" are permanent and cannot be longer editable in the latest build. Sorry if I didn't specify the exact name before but when I reported it I was not in my PC to get into RA and see the right name. 

BTW, thanks about the explanation about the HID driver :)

**Comment by twinaphex** [comment]
Check if this commit fixes it -

https://github.com/libretro/RetroArch/commit/46ee5efbca65ef610e2b52299f3156ddc14437e2

**Comment by netux79** [comment]
Yes, it works now... consider this issue fixed!! :)

BTW, I tried again the HID driver in RA Wii with a twin usb controller and it didn't work. It even corrupted the autoconfig folder with some garbage files that I had to format my SD. Did it work for you? I'm not sure but I saw in the code that it initilizes the usb when using it, not sure it if is needed as it was causing issues (with loading games from usb) when I did the sixasis support some time ago and King Toad fixed it by commenting the initialization and de-initialization. Should I open a separate issue for this? Thanks!!

**Comment by twinaphex** [comment]
What is this twin usb controller? I believe we don't support this pad yet. Right now with the current implementation, each pad needs a separate implementation (you can find them in input/drivers_hid) and needs to be baked into RA.

**Comment by netux79** [comment]
It's an adapter of the ps1 controller to the PC... I see it is supported within the autoconfig list as TWIN_USB_JOYSTICK.cfg however maybe my mistake is that I use the autoconf files I have from my RA copy in Linux. I also tried a ps3 controller thru usb. But I will give it a try as I have just notice that there are different autoconf sets depending on the platform, etc. Thanks

**Comment by twinaphex** [comment]
The HID joypad driver only uses autoconfigs found in hid/ dir.

**Comment by netux79** [comment]
Yeah, now I tried using the HID autoconfig files in both locations autoconfig and autoconfig/hid with no luck... the cfg files here had the driver set to "hid"... I dont know why I'm unable to make it work. I used the ps3 controller thru usb as you mentioned... any other idea why it should not be working? thanks!

**Comment by netux79** [comment]
Closing this issue and it was fixed with this commit 46ee5ef. Thanks!
