### ISSUE TITLE
[CTR/ 3DS] Crash when loading large cores.

### ISSUE THREAD

**Issue by shutterbug2000** [libretro/RetroArch#2099]
When attempting to load large cores
, the top screen becomes garbled, and the bottom screen stays red. This happens on NH 2.0 and IH, not sure about NH 1, and it works on an emulator.

![img_0039](https://cloud.githubusercontent.com/assets/8000700/9750424/5acb65f2-565d-11e5-9924-46b39bf84bc4.JPG)

**Comment by aliaspider** [comment]
what do you mean by large cores ?
that screen is displayed by NH2.0 when it is launching a 3dsx, if you are stuck there it just means that it failed to start it.
I can run retroarch+gambatte on NH2.0 here, what core did you test ?

**Comment by shutterbug2000** [comment]
Well, I tried to compile dosbox, and it gets stuck there. It happens after the "debug screen"(getting services I believe). Would you like me to send over the .3dsx?

**Comment by aliaspider** [comment]
there is no 'ctr' target set for the dosbox core so I guess you added one yourself.
this is a dosbox issue then and not a retroarch one.
besides dosbox doesn't even link for me so I'm not sure how you managed to build it.

**Comment by shutterbug2000** [comment]
Ah, ok. Could it perhaps be related to endianess? Is there any way to tell the compiler to use little/ big endian?

**Comment by fr500** [comment]
feel free to keep discussing this here, but this is not really a RetroArch bug as far as I can see
