### ISSUE TITLE
Blackberry 10 Release?

### ISSUE THREAD

**Issue by xiaclo** [libretro/RetroArch#2100]
I'm not sure if this belongs here, but I can't seem to find an answer.

How can I download or build a BB10 release of retroarch?

The latest release I can find is https://github.com/AampApps/RetroArch/commits/master, but that's over a year and a half old.  There is nightly builds of the cores for BB, but I can't find a bar file to install.

There was a blog post 2 months ago about 1.2.2 mentioning Blackberry 10 support, but nothing more recent than that.  Also a twitter post around the same time saying it would be soon.

I realize these things take time, and I'm just wondering about the current status and if I've missed something.

**Comment by fr500** [comment]
Not a bug
