### ISSUE TITLE
[Improvement] Some ideas about the LPL files

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#2102]
Hello,

I thought that it would be a good idea to :
- automatically replace paths by relatives paths in the LPL files (./content/... instead of /home/.../content/...) when scanning
- support the ':' prefix for relative paths in the LPL like in the config files
- have a "Scan a directory recursively" option in the Add content menu

**Comment by lasers** [comment]
Close this?

**Comment by RobLoach** [comment]
> have a "Scan a directory recursively" option

Done!

Other issues could be done with file and replace, possibly.
