### ISSUE TITLE
[Issue] Can't scan PSX files

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#2103]
Hello,

I can't manage to scan PSX files (.bin, .cue). The mednafen core is present aswell as the three mandatory BIOS files, but RA seems to ignore them as if they were not games. The scanning works well for other consoles.

**Comment by Kivutar** [comment]
Known issue, but good to have it in the tracker yes.

**Comment by natinusala** [comment]
If I create the LPL by myself and specify the PSX core, will it work ? Will the XMB menu recognize it and show it with the other consoles on the main list ?

**Comment by Kivutar** [comment]
Yes, I tried this with Cave Story's exe.
Reference the .cue, not the .bin, and it should work. Give it a try.

**Comment by natinusala** [comment]
I'll try that tomorrow and let you know if it worked.

**Comment by natinusala** [comment]
Okay, so I tried it and RA detects the LPL, but when I go to the PlayStation tab (in the XMB menu) and try to launch the game it shows me an "Empty playlist" message. 

I think this comes from the name of the game in the LPL that doesn't match the one in the ROM (because I have the same issue if I rename my SNES games in the SNES LPL). How can I get the exact game name ?

**Comment by Kivutar** [comment]
I suspect that you need the CRC, not the name, let me check

**Comment by natinusala** [comment]
Do I really need to scroll through the whole database to find the game name ? Because I have six games to add to the LPL so... I'll try with one to see if it works.

**Comment by natinusala** [comment]
Okay now I have the correct game name, however it still doesn't work, there is not the option to launch the game when I open it from the playlist (it shows the database informations about the game but there is no "Launch content" option).

**Comment by natinusala** [comment]
Sorry to bump this, but I would need to have a working LPL for thursday, could you tell me how to make it work please ?

**Comment by hizzlekizzle** [comment]
check this thread:
http://libretro.com/forums/showthread.php?t=3599&highlight=scan
They cover what's necessary and have some scripts for automated scanning.

**Comment by natinusala** [comment]
I managed to get it working by replacing each `Sony - PlayStation.lpl` line of my LPL to a blank line, thanks !

**Comment by sergiobenrocha2** [comment]
eh, it's working here with Sony - PlayStation.lpl line

**Comment by natinusala** [comment]
That's super weird... I also noticed that when we remove the `Sony - PlayStation.lpl` line, the game launches directly without opening the DB infos and using the Launch content option

**Comment by sergiobenrocha2** [comment]
RA has support now for PSX scan, should it be closed now?
