### ISSUE TITLE
How to clear core input configs in Retroarch?

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/RetroArch#2117]
I've use Retroarch quite a bit over the years, but maybe I am missing something obvious, so please excuse me. In newer builds/packages of Retroarch, we obviously have the "lakka look," which is great, but I'm having trouble trying to find where to clear the core configuration. I remapped A to B, X to Y (as retroarch autoconfig swaps them SNES-style), but before I did this I configured the MAME-157 core inside the emulator, changing select/cancel.

Now I am in a situation where I can call the menu with LT in MAME-157, but I can only cancel, with no seeming option on the keyboard to OK/Accept. The question is then, how can I clear this MAME-157 configuration? I saw the retroarch-core-options.cfg file, but this does not specify input. Should I run the core updater to "freshen" the core?

Thank you for the great work.

**Comment by hizzlekizzle** [comment]
If you configured it through the MAME OSD, you'll need to delete the MAME configuration stuff that I think is created in your BIOS/system directory.

**Comment by ProfessorKaos64** [comment]
In `retroarch.cfg`, I have "system_directory = ~/.config/retroarch". I only have `retroarch-core-options.cfg` in there. That file has some options for mame, but nothing about input. I did try removing the lines in there this morning only pertaining to mame. They fill back in, and input is still not defaulted. My fallback, if i don't have a "normal" way here, will likely to try removing the core library, and adding it back, or updating the core via the build bot in the menu.

**Comment by hizzlekizzle** [comment]
Depending on the MAME core, apparently it may save them in savedir/mame, so that's the next place I would look.

**Comment by fr500** [comment]
This is not a RetroArch issue but a libretro_mame issue in any case
