### ISSUE TITLE
[Latest libretro/stable PPA] Save state bug

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/RetroArch#2122]
I found that I can save state fine with a fresh game, no saves, using a button, but loading fails. If I use the overlay, save and load work perfect. Is this due to the default save slot not being set? After the initial overlay save/load, I can use the gamepad state save/load just fine. In summary, I must first save from the OSD Retroarch menu (pressing guide on my Xbox controller), or it will not be loaded. Every time after works fine, so it seems it matches what you are saying.

I noticed there is a period after the message, not sure if that means anything

failed to load state from "/path/save/file.state".

I don't think it's enumerating the save file initially.  Metroid fusion below as an example, but it's the same no matter what core. After each attempt I wiped the save folder.  Why is one saving the state with no prefix, and one isn't? Would I be able to avoid this by setting `state_slot = "0"`  to 1 to enumerate it?

Attempt with hotkey/button save/load
```
desktop@steamos:/home/steam/retroarch/saves$ ls
Metroid Fusion.state1
```

Through the overlay:
```
desktop@steamos:/home/steam/retroarch/saves$ ls
Metroid Fusion.state
```

**Comment by fr500** [comment]
Can you provide a bisect so we can know when did this first happen? 
I can't reproduce the issue

**Comment by ProfessorKaos64** [comment]
How can I produce that for you? I'd be glad to.

**Comment by fr500** [comment]
http://git-scm.com/docs/git-bisect
You'd have to build several commits, test them and determine in which commit it happens first

**Comment by fr500** [comment]
I even tried to remove this 
state_slot = "0"

And it still works

**Comment by ProfessorKaos64** [comment]
I didn't build from source this time, just used the PPA package from libretro/stable's official launchpad. I can most certainly build the latest source from here to see if this persists. I have a script ready to go to do that. I'll see if it's the same behavior with the current master tree.

**Comment by ProfessorKaos64** [comment]
This is my fault, it's an issue with the config file I have. If you don't mind, would you be able to see what path setting is throwing this off?

**Comment by fr500** [comment]
you can paste the config in a pastebin but I don't think it's a pad...

**Comment by ProfessorKaos64** [comment]
I merely removed retroarch.cfg and started fresh, the hotkey save/load worked fine.  See: http://pastebin.com/WhFVc6N9.  I suppose I will start with a blank config and go one by one setting things.
