### ISSUE TITLE
(Android) No Mouse/Keyboard Support

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2128]
I tried several mice, keyboard, keyboards are detected as controllers (each key with a keycode but no real keyboard input)

And mice work as touch which makes it impossible to use one for zapper or other lightgun unless the core implements pointer support

**Comment by diablodiab** [comment]
From looking in:
/input/drivers/android_input.c

It would seem that keyboard and mouse input is not implemented in the android input driver. Are there any plans to implement this in the near future?

**Comment by fr500** [comment]
@diablodiab I think this is fixed right?
btw there is still one minor niggle, shift doesn't seem to work, pressing shift on a text entry field on RA produces a ? symbol

**Comment by Brianvgplayer** [comment]
I couldn't get the virtual keyboard working in a few of the cores. There's no way to start some games in the MSX core. I couldn't get Zapper working in the Nestopia core, with mouse or touchscreen. In the Genesis Plus GX core, the cursor shows up on the touchscreen when the option is selected for lightgun games, but there is no way to fire the lightgun. Mouse buttons don't work either.

**Comment by fr500** [comment]
That's more related to this https://github.com/libretro/RetroArch/issues/2767
Thank this bug.

**Comment by fr500** [comment]
Duplicate: https://github.com/libretro/RetroArch/issues/2901

**Comment by twinaphex** [comment]
Keyboard and mouse support have been implemented on Android now, right? If so, I think this can be closed.

If not, this can be reopened.
