### ISSUE TITLE
RetroArch always generates empty directories

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#2129]
Thank you for making RetroArch better.
I'm using the latest RetroArch-git on Linux x64.

I changed the settings in ~/.config/retroarch/retroarch.cfg:
> libretro_directory = "~/emulators/retroarch/cores"
> libretro_info_path = "~/emulators/retroarch/cores"
> core_assets_directory = "~/emulators/retroarch/downloads"

But RetroArch always generates the system default directories on startup:
> ~/.config/retroarch/cores
> ~/Downloads

I don't need "Downloads" in my home directory...

Maybe RetroArch checks /etc/retroarch.cfg first, 
then it makes the system default directories.
RetroArch should check ~/.config/retroarch/retroarch.cfg first.

**Comment by fr500** [comment]
does it create them again after you remove them?

**Comment by heathross** [comment]
Yes.

$ rm -rf ~/Downloads
$ cp ~/.config/retroarch/retroarch*.cfg ~
$ rm -rf ~/.config/retroarch/**
$ cp ~/retroarch*.cfg ~/.config/retroarch
$ dir ~/.config/retroarch
> retroarch-core-options.cfg  retroarch.cfg

$ retroarch
$ dir ~/.config/retroarch
> assets	  cheats  database  playlists  retroarch-core-options.cfg  shaders
> autoconf  cores   overlay   remap      retroarch.cfg

It generates ~/Downloads too. :-/

**Comment by fr500** [comment]
Yes I've found the issue, actually I plan to make downloads go into
.config/retroarch too, it's not such a great idea to use the home folder
Downloads.
I'm working on a solution so it doesn't create anything if other paths are
set already.

**Comment by heathross** [comment]
> I'm working on a solution so it doesn't create anything if other paths are set already.

Thanks!

I made a temporary fix to change the default "Downloads" directory.
```
--- frontend/drivers/platform_linux.c
+++ frontend/drivers/platform_linux.c.new
@@ -1926,13 +1926,13 @@
                         "overlay", sizeof(g_defaults.dir.overlay));
                   fill_pathname_join(g_defaults.dir.osk_overlay, base_path,
                         "overlay", sizeof(g_defaults.dir.osk_overlay));
+                  fill_pathname_join(g_defaults.dir.core_assets, base_path,
+                        "Downloads", sizeof(g_defaults.dir.core_assets));
 
                   if(home)
                   {
                      fill_pathname_join(g_defaults.dir.screenshot, home,
                            "Pictures", sizeof(g_defaults.dir.screenshot));
-                     fill_pathname_join(g_defaults.dir.core_assets, home,
-                           "Downloads", sizeof(g_defaults.dir.core_assets));
                   }
                   else
                   {
```

**Comment by twinaphex** [comment]
What is the state of this now? Is this still an ongoing issue?

**Comment by twinaphex** [comment]
Closing until somebody confirms this is still an ongoing issue.

**Comment by dizine** [comment]
I’m using the latest retroarch 1.8.1 release on the PS3 and changed settings in SSNE10000/retroarch.cfg but noticed retroarch is still creating the original default directories on boot.

Thanks for your help.
