### ISSUE TITLE
SDL input driver for Mac OS X Retroarch

### ISSUE THREAD

**Issue by neosquid** [libretro/RetroArch#2134]
In the input drivers for Mac, there is no SDL option, only HID. Unfortunately, my arcade stick won't work with HID, only SDL. 

Is it possible an SDL input driver be added to Mac Retroarch in the future?

Thanks!

**Comment by twinaphex** [comment]
SDL is a horrible dependency on something like the Mac. A much better use of one's time would be making the arcade stick work with the HID driver.

I won't ever accept any kind of forced dependency for the OSX version. That is a line I won't ever cross. Zero dependencies here is the goal.

**Comment by neosquid** [comment]
Out of interest, I wonder how OpenEmu handles joystick input - my stick works with zero issues using their. 

Is there anything that could be utilized from their code for Mac Retroarch?

**Comment by twinaphex** [comment]
I don't see anything special in their handling of input at least. It'd probably help if you would tell us which arcade stick this is.

**Comment by neosquid** [comment]
From Mac's system profiler:

Generic USB Joystick:

Product ID: 0x0006
Vendor ID: 0x0079
Version: 1.07
Speed: Up to 1.5 Mb/sec
Manufacturer: DragonRise Inc.
Location ID: 0xfa510000 / 3
Current Available (mA): 500
Current Required (mA): 500

(there's an exisiting .cfg of this device in retroarch autoconfig/udev folder which seems to match my product and vendor id) 
 
DragonRise_Inc.___Generic___USB__Joystick__.cfg )

**Comment by twinaphex** [comment]
Yeah but that one is for the udev input API, which is linux-based.

We could probably get it to work with the HID input driver one way or another.

**Comment by neosquid** [comment]
Eternally grateful if anyone has the time to get it up and running one day! thx!

**Comment by neosquid** [comment]
Hey, 1.3.0 now recognises my stick!!! 

Thanks!
