### ISSUE TITLE
[CTR/3DS] Weird frame rate behavior

### ISSUE THREAD

**Issue by bserafm** [libretro/RetroArch#2143]
Apparently the 3DS' proper refresh rate is 59.834Hz, but when "Audio Sync" is turned ON, it forces the refresh back to between 59,90Hz - 60Hz, ignoring the "Refresh Rate" settings completely. This causes stuttering and audio "scratching".

When Audio Sync is turned OFF, the frame rate runs at the correct 59.834fps at all times. Audio runs fine, but it crackles a bit from time to time (not that much perceptible, but it happens).

This has been confirmed to affect both 3DS and 2DS models. Not sure abut 3DSXL (which should be the same) and N3DS.

**Comment by fr500** [comment]
known, DRC is still not implemented

**Comment by aliaspider** [comment]
fixed.
