### ISSUE TITLE
machine/cpu-features.h missing

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#2144]
building from https://github.com/libretro/RetroArch/commit/507c6833982c22236b92a47afd1e2c5d617fefba 
on Raspbian Wheezy (on rpi2)

```
Makefile:120: recipe for target 'obj-unix/frontend/drivers/platform_linux.o' failed
make: *** [obj-unix/frontend/drivers/platform_linux.o] Error 1
make: *** Waiting for unfinished jobs....
CC frontend/drivers/platform_linux.c
frontend/drivers/platform_linux.c:35:34: fatal error: machine/cpu-features.h: No such file or directory
```

can't find missing machine/cpu-features.h - looks like this is included with linux kernel headers - but it isn't pathed for use by retroarch. Is this include supposed to be included in the retroarch repo or should this only be included for android and not for Linux on arm ?

**Comment by joolswills** [comment]
Moving the include inside the ANDROID define fixes it for me, but I'm not sure if this is correct . But can submit a pull request if you think it's ok

```
diff --git a/frontend/drivers/platform_linux.c b/frontend/drivers/platform_linux.c
index c769439..5ef893c 100644
--- a/frontend/drivers/platform_linux.c
+++ b/frontend/drivers/platform_linux.c
@@ -30,10 +30,10 @@
 
 #ifdef ANDROID
 #include <sys/system_properties.h>
-#endif
 #ifdef __arm__
 #include <machine/cpu-features.h>
 #endif
+#endif
 
 #include <boolean.h>
 #include <retro_dirent.h>
```

**Comment by fr500** [comment]
that makes no sense whatsoever... did you clean, configure and make?

**Comment by joolswills** [comment]
Yep. The header is not needed / missing on my system - I was "guessing" it might not be needed for arm linux but android only.

**Comment by joolswills** [comment]
well, i say guess, I have seen that header referenced in the android documentation.

**Comment by joolswills** [comment]
You say it "makes no sense whatsoever" - please could you explain why ? That doesn't give me much info :)

git sected to 7bd5ec0ffe6b6a5886cce2e8b5cabfffa7a36266 is the first bad commit

```
commit 7bd5ec0ffe6b6a5886cce2e8b5cabfffa7a36266
Author: twinaphex <libretro@gmail.com>
Date:   Tue Sep 15 22:32:08 2015 +0200

    Refactor performance_android.c to performance_linux.c - compile it in for Linux too
```

so it does look to me like this header should only be included on android as it was previously in an andoird only file - performance/performance_android.c

**Comment by twinaphex** [comment]
It might serve a purpose on ARM Linux devices too.

**Comment by joolswills** [comment]
It doesn't compile on arm Linux without my patch above. I believe it is a correct fix (including that only for Android - or at least it replicates previous behaviour when it was in an Android only file)

**Comment by twinaphex** [comment]
https://github.com/libretro/RetroArch/commit/f22436e39f878e9039c492dc4b352e1e144b8573

Pushed it through, try it out on your end.

**Comment by johnfraney** [comment]
@twinaphex I can confirm that `make` works for me (ODroid-XU4, Ubuntu 15.04, armv7l) with that fix

**Comment by joolswills** [comment]
@twinaphex works here - thanks.
