### ISSUE TITLE
(Wii) Performance degradation in 1.2.2

### ISSUE THREAD

**Issue by therandomizer85** [libretro/RetroArch#2164]
16-bit emulator cores have an obvious degradation in performance compared to the previous milestone release, which was 1.0.0.2. Both Snes9x Next and Genesis Plus GX have an issue where frames drop where they're not supposed to be, a great example is any fast-paced game such as Sonic the Hedgehog 3. Effects such as the strobe effect (flickering at 60 frames per second), are not rendered perfectly or consistent, this issue is akin to v-syncing issues; Sky Sanctuary Zone is a great place to test this issue. The section where Sonic is transported via the light beam flickers at 60 fps, but you can see where the frames drop and strobe effect is not consistent.  Now, with 1.0.0.2, the smooth framerate in Genesis Plus or Snes9x Next does not occur (unless they are the few games that don't run 60 fps due to performance issues like SA-1 ROMs), Sky Sanctuary Zone has a perfect 60 fps and there are no signs of performance degradation. 

This issue has been confirmed by Libretro forum user retrogamer. I don't know what changes were implemented in the actual 1.2.2 RA GUI itself, but the core works far better on 1.0.0.2 than it did on 1.2.2. I monitored the FPS counter, not sure if it can be logged though. If you need more information, please let me know.

**Comment by twinaphex** [comment]
Build from source and see if it's better, a couple of things changed since.

**Comment by therandomizer85** [comment]
So try one of the nightly builds and report back (I see one that was compiled today, will try a few nightly builds)? Okay, I'll let you know after testing. Thank you.

**Comment by fr500** [comment]
RetroArch for consoles is a two step process:
- Build the core
- Build retroarch and link it statically with the core

The simplest method to achieve this is:
- build the core
- copy the .a file to the retroarch repository / dist-scripts
- run dist-cores.sh $platform (wii in this case)

This is assumming you have the toolchain configured correctly. It should put everything you need under pkg/wii

**Comment by therandomizer85** [comment]
I tested Genesis Plus cores (most up to date) with 1.0.0.2, and 1.2.2 and both performed without speed degradation or dropped frames; which leads me to assume that cores that come with 1.2.2 (not including nightly builds) are outdated and broken.

**Comment by twinaphex** [comment]
So you are telling me that with the latest Genesis Plus GX core and the latest RetroArch compiled from source, speed is good again?

I want to be sure that I'm getting this right because I am not sure what you are referring to as '1.2.2'.

**Comment by therandomizer85** [comment]
Yes,1.2.2 as in the plain version and not a nightly derivative of 1.2.2. The cores were compiled by Retrogamer on the forums for me to test

1.2.2 Genesis Plus
https://anonfiles.com/file/1a58efcf0f09923e14128f123d489701

1.0.0.2 Genesis Plus
https://anonfiles.com/file/f2ce03ffe1e72bebd9041d880215081e

I tested Sonic 3 as it is a fast game and uses the strobe effects a lot, never once dropped frames. What recent source Genesis Plus was built from, I don't know, but it is the most up to date and does not have issues. I assume other cores need to be compiled similarly (as in being updated). I hope this info is useful.

**Comment by twinaphex** [comment]
No this info is not useful. I specifically asked you to test the latest source, not some old version that is no longer current. This does not help us at all.

**Comment by therandomizer85** [comment]
Well, Retrogamer has specified that the 1.2.2 dol is exactly up to date in both cases, the core and RA source, the 1.0.0.2 dol is the latest genesis plus core source and RA is the old one.

**Comment by twinaphex** [comment]
Again I have no idea what you are actually trying to confirm.

All I want to know is results with latest RA source and latest cores. Anything else - combining latest cores with RA 1.0.0.2 - is not something that is going go help.

**Comment by therandomizer85** [comment]
What I'm trying to confirm is with the original build of 1.2.2, the cores that came with it had performance issues, dropping frames. 

With the compiled cores compiled with the latest 1.2.2 nightly, the issue no longer remains as again, the cores were compiled with the latest build. Vanilla 1.2.2 is the one with the unstable cores, I don't understand what it is about my wording that's confusing. 

Original 1.2.2 Genesis, Snes9x Next, etc cores had framerate drops/performance degradation
Nightly compiled cores for the aforementioned emulators do not have this issue. 

That is all I'm trying to explain.

**Comment by twinaphex** [comment]
Alright, so what you are telling me that with the current source, things are back to normal.

Alright then, that is all that I wanted to know.

**Comment by therandomizer85** [comment]
My apologies for wasting your time. Okay.

**Comment by twinaphex** [comment]
Well the wording was confusing and I couldn't really get what you are getting at and it was geting a little frustrating, that is all. No hard feelings intended.. If you can confirm that with the latest sources and the latest RetroArch performance is back to normal, that is a relief indeed. Thanks for confirming that if that is the case.
