### ISSUE TITLE
[PSP] path_mkdir no longer works

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2165]
Like the title says, path_mkdir no longer works, causing RA to always save in content dir on a new installation, I think other directory based operations may be failing too because even if the dir exists it's saving in content dir

**Comment by fr500** [comment]
Indeed, it seems like path_is_directory always returns false now.

**Comment by fr500** [comment]
I added a small function to a "debug panel / testing panel" I'm implementing, I plan to add a few important tests (platform specific and otherwise to the panel)

One of these is trying to create a directory, (in this case I hardcoded the default save directory that doesn't exist) and the second one, checks if a dir exists (in this case, the core dir which in fact exists), both fail.

![screenshot_2015-07-26-16-35-17](https://cloud.githubusercontent.com/assets/1721040/10065405/0db13216-624b-11e5-8496-9d0a8ba42d10.png)

**Comment by fr500** [comment]
path_is_directory is now working fine
path mkdir always going till ./ for some reason:

path_mkdir("ms0:/PSP/GAME/RA/cores/savefiles") produces this output:

    Failed to create directory: ".".
    Failed to create directory: "./".
    Failed to create directory: "ms0:/".
    Failed to create directory: "ms0:/PSP/".
    Failed to create directory: "ms0:/PSP/GAME/".
    Failed to create directory: "ms0:/PSP/GAME/RA/".
    Failed to create directory: "ms0:/PSP/GAME/RA/cores/".

path_mkdir("ms0:/PSP/GAME/RA/cores/savestates") produces this output:

    Failed to create directory: ".".
    Failed to create directory: "./".
    Failed to create directory: "ms0:/".
    Failed to create directory: "ms0:/PSP/".
    Failed to create directory: "ms0:/PSP/GAME/".
    Failed to create directory: "ms0:/PSP/GAME/RA/".
    Failed to create directory: "ms0:/PSP/GAME/RA/cores/".

**Comment by twinaphex** [comment]
Is this issue fixed now or not?

**Comment by fr500** [comment]
yes apparently it is
