### ISSUE TITLE
Cg/cg.h is missing

### ISSUE THREAD

**Issue by NerosTie** [libretro/RetroArch#2169]
I can't compile because an include is missing.

This is what I get (fresh `git clone` and after a `./configure`)

```
 ➜  RetroArch git:(master) make
CC git_version.c
CC gfx/drivers_shader/shader_gl_cg.c
gfx/drivers_shader/shader_gl_cg.c:25:19: erreur fatale: Cg/cg.h : Aucun fichier ou dossier de ce type
compilation terminée.
Makefile:123: recipe for target 'obj-unix/gfx/drivers_shader/shader_gl_cg.o' failed
make: *** [obj-unix/gfx/drivers_shader/shader_gl_cg.o] Error 1
```

There is a `cg.h` in `gfx/inc/Cg/` but the compilater doesn't find it...

I'm on Linux, Fedora 22 with GCC 5.1.1.

**Comment by fr500** [comment]
you need to have nvidia cg toolkit installed, feel free to discuss this here but I don't think this is an issue

**Comment by NerosTie** [comment]
That's right! Thanks!
