### ISSUE TITLE
[3DS] Save screenshot does not work

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#2182]
I'm using CPS2 core.

New 3DS on 9.9.0-26E

I see noise&black instead of a proper screen grab.

**Comment by Smoker1** [comment]
Same happens with 9.2 Gateway

**Comment by gingerbeardman** [comment]
Still not working. 

Choosing screenshot just dismisses the Quick Menu.

**Comment by meepingsnesroms** [comment]
I can also verify this is still an issue in 1.7.4 nightly.

**Comment by Jaffacakelover** [comment]
New 3DS on 11.14.0-46E
Retroarch 1.9.0
CPS2 core

The screenshot function's working for me!

![xmcota-201119-100353](https://user-images.githubusercontent.com/3490850/99646333-421ada00-2a48-11eb-998e-f75a29d68a74.png)


Anyone else want to test?
