### ISSUE TITLE
Pausing emulation causes retroarch to constantly switch between fullscreen and windowed

### ISSUE THREAD

**Issue by chungy** [libretro/RetroArch#2189]
I can open the GUI menu and it will stop switching, but when it's closed, the cycle resumes and I can't even unpause to stop it. Only option is to quit RetroArch

Running on x86_64 Linux

git bisect shows the first commit with the problem is bae9abb525a1ff954d8ca573746035369158096f

**Comment by twinaphex** [comment]
I don't see anything that could possibly be wrong there. @Alcaro you want to take a secondary look to see if I overlooked something?

**Comment by twinaphex** [comment]
This should correct the bug -

https://github.com/libretro/RetroArch/commit/a91a326c0fa0bf6c6d1bb20779c8d343a091eb43

The cached frame still doesn't seem to work upon toggling fullscreen in pause mode but that is a separate issue to this I believe.

**Comment by Alcaro** [comment]
That's a lot of weird stuff going on with fullscreen recently? #2186 is also about fullscreen.

Yeah, that commit seems to fix something, at least. I can no longer reproduce the following:
```
==7307== Conditional jump or move depends on uninitialised value(s)
==7307==    at 0x419090: rarch_main_ctl (runloop.c:406)
==7307==    by 0x419655: rarch_main_ctl (runloop.c:353)
==7307==    by 0x41A79B: rarch_main_iterate (runloop.c:993)
==7307==    by 0x410316: rarch_main (frontend.c:346)
==7307==    by 0x97CAEC4: (below main) (libc-start.c:287)
==7307==  Uninitialised value was created by a stack allocation
==7307==    at 0x418FAB: rarch_main_ctl (runloop.c:310)
```

**Comment by chungy** [comment]
a91a326 fixed it. Thanks :)
