### ISSUE TITLE
[Raspberry Pi] Mouse doesn't work in-game but does in RGUI

### ISSUE THREAD

**Issue by davidj1987** [libretro/RetroArch#2192]
I am having a very similar issue to this user below, except he's having the issue on android so it is unfair to say it is completely the same:

https://github.com/libretro/RetroArch/issues/2128

The emulator in question (Genesis Plus GX) I posted an issue here:

https://github.com/libretro/Genesis-Plus-GX/issues/31

The mouse works fine when enabled in the GUI, however in game I cannot move the mouse around at all - the buttons work fine. Because I had a spare SD card, I tried Lakka and again the same thing - mouse doesn't move but the buttons work fine. Quick game to try is Gangster Town for the SMS.

**Comment by fr500** [comment]
Did you select the appropiate controller? can you try snes9x? otherwise it might as well be a core issues

**Comment by davidj1987** [comment]
I did select the appropriate device and here's where it gets odd...after further testing I did find that Body Count (A genesis game) works fine if you select the mouse (not the menacer), but no other game works with the mouse that supports it.

**Comment by fr500** [comment]
Then it's probably an issue with GPGX and it doesn't belong here

**Comment by ekeeke** [comment]
As explained in the above linked issue, this is not a core issue since it only happens on Raspberry Pi. 

Again, it's either caused by missing RETRO_DEVICE_POINTER support in RPi port of Retroarch or incompatibility of the physical mouse driver used on RPi with that libretro device. There does not seem to be any specific Retroarch port for RPi so I guess it's the latter, which means it's something to be fixed on RPi side.

RETRO_DEVICE_POINTER requires the mouse driver to return **absolute** x/y position so this is probably what does not work here. Other libretro devices relying on physical mouse use the **relative** x/y movement information, which explains why some devices work fine but not others.

**Comment by twinaphex** [comment]
@davidj1987 Should tell us then which input driver he is using.

**Comment by ekeeke** [comment]
Well, I have done my homework and it seems RETRO_DEVICE_POINTER is missing from the udev driver which can be used on RPi.
https://github.com/libretro/RetroArch/blob/master/input/drivers/udev_input.c#L521

**Comment by twinaphex** [comment]
Yes I see.

Thanks for letting me know. I will be looking into ways to provide support for it if possible.

**Comment by davidj1987** [comment]
I am using Retropie, and the option to install via source, I took an extra microSD card, installed Retropie and updated retroarch and no dice.

**Comment by twinaphex** [comment]
You might have to set chmod permissions on the device nodes before the mouse will start to work in non-X11 mode.

**Comment by davidj1987** [comment]
I have no idea what I am doing. Maybe one of the Retropie devs can look at
this?

**Comment by joolswills** [comment]
permissions are be correct and mice do work - the pi user is a member of the input group (which /dev/input are all writable for).

**Comment by davidj1987** [comment]
Is there a way I can enable this?

**Comment by joolswills** [comment]
The permissions are correct in RetroPie - there is nothing to enable on the system side of things. Must be some other reason why this is not working. I've yet to test myself.

**Comment by davidj1987** [comment]
Thank you for looking into this!

**Comment by ekeeke** [comment]
Looking at commit 8fc33b3, it does not seem it's going to work.

udev->mouse_x & udev->mouse_y seem to be relative position (raw report from mouse device) while input_translate_coord_viewport expects absolute position 

In some other drivers (X11 for example), the x & y positions reported by the OS driver are **absolute** position but that's not the case with udev apparently.

This is with a quick look at the code in retroarch/input though and I'm by no mean an expert with retroarch code so I might be missing something.

**Comment by dankcushions** [comment]
stumbled upon this issue. i thought of way to possibly spoof a RETRO_DEVICE_POINTER in the udev device, but haven't got round to trying it yet. see https://github.com/libretro/Genesis-Plus-GX/issues/31#issuecomment-242426869

> i reckon we could spoof an absolute coord from a relative coord in the RA udev driver. eg https://msdn.microsoft.com/en-us/library/windows/desktop/ee418779(v=vs.85).aspx
> ie, take 0,0 to be the start value and use the relative coords passed in by the mouse to move from that.

if no actual pointer was detected, perhaps you could fallback to this approach. needs prototyping...
