### ISSUE TITLE
Retroarch 2015-10-02 crashed when starting. Windows 8 Professional x64

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#2200]
Tested in "fresh install" (extracted 2015-10-02_Retroarch.7z in new folder, extract redist-x86_64.7z in same folder). Just crashed too, no additional error reported :(

OS: Windows 8 Professional x64.

**Comment by stevenstrike** [comment]
Same, starts with build from 30 September. (nothing unusual in the log)

**Comment by fr500** [comment]
Hmmm, I just tried RetroArch_full and it works fine here, I'll try the nightly + redist but it is the same files packed separately

**Comment by fr500** [comment]
Tried nightly + redist and it works fine too in Windows 8.1

**Comment by fr500** [comment]
Tried on windows 10 too and it still works.

**Comment by ofry** [comment]
Please try it in Windows 8 (not 8.1)

**Comment by ofry** [comment]
I tried to do x64 build by self via MinGW-x64 as https://gist.github.com/heuripedes/b6da0fea68b648bdd2ae

./configure --enable-glui --enable-xmb
make

After that I tried to launch Retroarch. Got this error:
![retroarch_error](https://cloud.githubusercontent.com/assets/11790863/10261086/7f614ee6-698f-11e5-8083-2b0675533561.png)

**Comment by ofry** [comment]
Translation:

Entry point in function ... not found in DLL library ...

**Comment by ofry** [comment]
gdb log of 201faccff9ae10e4a45d24d5671b7ebab2c1cb88

$ gdb ./retroarch
GNU gdb (GDB) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./retroarch...done.
(gdb) start
Temporary breakpoint 1 at 0x519f20: file C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c, line 17.
Starting program: C:\msys64\home\ofry\RetroArch\retroarch.exe
[New Thread 82360.0x140e0]
gdb: unknown target exception 0xc0000139 at 0x7ff9225cc4e0
During startup program exited with code 0xc0000139.
(gdb) cont
The program is not being run.
(gdb) start
Undefined command: "".  Try "help".
(gdb) start
Temporary breakpoint 2 at 0x519f20: file C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crt0_c.c, line 17.
Starting program: C:\msys64\home\ofry\RetroArch\retroarch.exe
[New Thread 75796.0x14250]
gdb: unknown target exception 0xc0000139 at 0x7ff9225cc4e0
During startup program exited with code 0xc0000139.
(gdb)

**Comment by ofry** [comment]
It works with latest git version ^^. Will wait next buildbot version.

**Comment by stevenstrike** [comment]
Can confirm, no more crashes since Build October 3rd

**Comment by ofry** [comment]
Huh, another crash in 2015-10-03 build :( But I think, it's another problem. Because change video driver to "d3d" or "sdl2" doesn't help.

**Comment by ofry** [comment]
Huh, I found the problem. If I enable any audio filter (BassBoost,dsp, Chorus.dsp, etc) application will instantly crash...

**Comment by ofry** [comment]
2015-10-04 build fixed this error. I think I can close the issue now.
