### ISSUE TITLE
[3DS, CIA builds] Resuming RetroArch after pressing home makes the top screen go black

### ISSUE THREAD

**Issue by thedax** [libretro/RetroArch#2207]
I imagine all cores are affected by this, but when the user presses the HOME button to go back to the home menu, and then later on returns to RetroArch (the time spent in the menu doesn't matter), the top screen will be black (backlight stays on, so it's not a case of the entire screen powering down) until the user exits RetroArch and relaunches it. Going back to the home menu while the top screen is black does not result in any abnormalities in the home menu; I think RetroArch isn't saving or restoring certain graphical information needed to resume properly (as for what that information is, I don't really know, I haven't really delved into graphical programming on the 3DS yet).

Test environment:
New 3DS XL on 9.0 system firmware, emuNAND 9.5
Used this commit to test (the issue has always been here though, as far as I know): https://github.com/libretro/RetroArch/commit/7798be9f6e698939dc6fed2a4120ddc3edd810ab
Gambatte core, CatSFC Plus core, Genesis Plus GX core, PCSX ReARMed core

**Comment by Chocobubba** [comment]
This issue still persists in 1.3.3 of PCSX-ReArmed, mGBA, and possible others.

N3DSXL, 10.7 Firmware, .cia version.
