### ISSUE TITLE
[iOS 9] Cannot build?

### ISSUE THREAD

**Issue by Jesskas** [libretro/RetroArch#2213]
I cloned the most recent master build. I'm using xCode 7.0.1 on OS X 10.11 El Capitan, trying to build to an iPad Air 2 using iOS 9.0.2. (Non-jailbroken)

I don't see what I'm missing; I can follow the instructions given in the iOS folder, but have the same problem as https://github.com/libretro/RetroArch/issues/245. I can build [some] of the cores fine, but whether they are copied over to the ios/modules folder or not, I run into the exact same issue when trying to build through script/build.

That thread claims that, whether script/build works or not, it builds in xCode fine, so I just decided to do that. After changing the code signing to get things working in my name for my device, it began to build and run into this error after running through a few scripts:

Undefined symbols for architecture armv7:
  "_menu_iterate", referenced from:
      -[RAMenuBase alertView:clickedButtonAtIndex:] in griffin_objc.o
     (maybe you meant: _menu_iterate_render, _generic_menu_iterate )
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I eventually found the function definition for alertView:clickedButtonAtIndex in cocoatouch_menu.m, but no mention of _menu_iterate.

Granted, I'm new to iOS development so I apologize if I'm dense and missing a point or two, but I have successfully built Nitrogen (nds4ios) to my new iOS device and it works fine, so I'm wondering what's wrong here. Help appreciated.

**Comment by twinaphex** [comment]
I pushed a buildfix:

https://github.com/libretro/RetroArch/commit/b7c8ea67d847d20cc6ec74455875d1f4c0483b56

**Comment by Jesskas** [comment]
Fixed that part in the build, but now I'm having another error:
error: /Users/jesscat/Emulators/RetroArch-master/media/shaders_glsl: No such file or directory

**Comment by hizzlekizzle** [comment]
The easiest thing is just to remove the shaders, database stuff and other assets from the project in XCode. I think it's already been done for the OS X project but i guess not for the iOS one.

**Comment by twinaphex** [comment]
@hizzlekizzle Yeah, I think DarkFire or somebody else put them back again. Guess I will remove the references again since it is not really a base requirement to have it be there and we are mainly going to be the ones compiling and packaging it up anyway. And that build script he wrote previously that would convert all the shaders from Cg to GLSL took around 5 minutes for each compile, it was so painful I just removed it altogether.

**Comment by Lodovik** [comment]
@Jesskas Click on the Retroarch project at the upper left, select Build Phases tab at the right, expand Copy Bundle Resources and then remove the first line with the GLSL shaders reference. Then, it will compile.

**Comment by Jesskas** [comment]
Building and deploying worked! Thanks! :)
Also had to remove from the Copy Bundle Resources: /assets, /autoconfig, /overlays, /cht, /cursors, /rdb.

Now just to use google-fu to determine why loading any core seems to not work. (Results in "No Core" at the bottom)

**Comment by Lodovik** [comment]
@Jesskas How did you resolve the "No Core" problem?

**Comment by Jesskas** [comment]
I apologize - the "Cannot build" problem is resolved. :p
the "No Core" problem continues to plague me.

**Comment by Lodovik** [comment]
Same here...
