### ISSUE TITLE
[3DS, CIA & 3DSX, Unimplemented Feature] Nestopia core only supports 32-bit colour, resulting in the display not showing correctly.

### ISSUE THREAD

**Issue by thedax** [libretro/RetroArch#2215]
Every game that I've tried looks like this, regardless of video settings/aspect ratio/etc.:

![top_0000](https://cloud.githubusercontent.com/assets/4482745/10275148/230eb3ec-6b13-11e5-9637-0d01448b7aa3.jpg)
![top_0001](https://cloud.githubusercontent.com/assets/4482745/10275147/230cd400-6b13-11e5-96d8-14fa6b2835b8.jpg)

I tested with the October 5 nightly build, but ever since I started playing around with RArch on 3DS around the 24th or so, I've not noticed any improvements (note that that's not me asking for any, I'm just saying). If it matters, the console says "Video @768x672".

New 3DS XL with 9.0 firmware, emuNAND 9.5, CIA build (not sure about the 3dsx build)
Nestopia v1.47-WIP core
All default video settings except for Integer Scaling and 1:1 PAR

**Comment by GPDP2** [comment]
Can confirm this also happens on 3dsx build.

**Comment by fr500** [comment]
It's a known issue,  the front-end doesn't support that pixel format yet

**Comment by thedax** [comment]
Yeah, aliaspider told me Nestopia only supports 32-bit colour, and the 3DS front-end is only using 16-bit colour. Let me update the issue title so it's more specific.

**Comment by twinaphex** [comment]
In specific, it's XRGB8888. It would be relatively trivial for anybody to implement in gfx/drivers/ctr_gfx.c, but I imagine aliaspider right now has bigger fish to fry.

**Comment by thedax** [comment]
Thanks @aliaspider!
