### ISSUE TITLE
Can't get to menu on shield tv

### ISSUE THREAD

**Issue by Qard** [libretro/RetroArch#2228]
I've been using retroarch on my shield tablet for awhile, and the shield controller seemed to work fine. But now I'm trying to get it running on a shield tv and the back button doesn't open the menu. I also tried setting the button combo to open the menu and that doesn't seem to work either. I'm using the current release on Google Play store, not sure if it's fixed in nightlies, but I don't see any related issues on here.

**Comment by fr500** [comment]
Hmm I don't think the current version would be listed on playstore for Shield ATV so I guess you sideloaded.

That being the case, just try a nightly, the nvidia button toggles the menu just fine in newer versiones

**Comment by fr500** [comment]
Feel free to keep discussing this here

**Comment by Qard** [comment]
It must've been listed at some point, as I haven't yet looked into how to sideload stuff onto the shield tv. I believe I browsed to it on my laptop and set it to install from there. Not sure if that works differently from finding it in the store *on* the device. I just searched on the device and I'm not finding it there now.

I'll look into sideloading a nightly.
