### ISSUE TITLE
[Android] Emux (GB/GBC) lib doesn't seem to work.

### ISSUE THREAD

**Issue by Brottweiler** [libretro/RetroArch#2232]
Installing the `Game Boy / Game Boy Color (Emux)` core, then when looking for GBC ROMs it will not detect any ROMs to play. If I install the **Gambette** core however, I see ROMs and can play these using the Gambette core.

So, the **Emux** core doesn't seem to work.

**Comment by fr500** [comment]
Please open this in the respective repo.
Emux is a new emulator and it's not supposed to be very compatible, it just happens to have a libretro implementation
