### ISSUE TITLE
[PC]Crash when accessing ROMs from unmounted drive

### ISSUE THREAD

**Issue by pyroesp** [libretro/RetroArch#2236]
Hello,

I have my ROMs on my (2nd) HDD, which isn't always mounted.
Whenever I try to load a game from the XMB and the HDD isn't mounted, the application closes.

The XMB shows all the ROMs I have scanned for all the different platforms even though the drive isn't mounted. This is probably not the issue. I don't mind having all the ROMs listed.

But maybe there's no check for the validity of the pointer returned from the open ROM function (not sure where it is in the source code or if it even is in retroarch frontend) when trying to load the ROM.
The program looks like it tries to open the ROM, or at least start the core with the selected ROM, and the screen goes gradually black, then just closes.
Maybe it's a check retroarch can do before starting the core with the selected ROM, and prompt a "file not found / does not exist" error ?

I've tried it with GBA, SMS, SMG and N64 (also tried a couple of cores, not just one) and they all fail to load and they all stop retroarch abruptly.

Not sure if there's a log file somewhere or something I have to enable to log what happens.

PS: My PC runs on a Ubuntu 14.04

**Comment by pyroesp** [comment]
So I've been digging around the code and I think I've found where the ROM path check can be done, though I'm not sure how to set up a messagebox of some sort to appear.
In playlist.c, function `content_playlist_t *content_playlist_init(const char *path, size_t size)`, after the call to `content_playlist_read_file(playlist, path);`, you can try adding this :

```C
   // Check if ROMs in playlist exist
   unsigned int idx;
   for (idx = 0; idx < playlist->size; ++idx)
   {
      FILE *rom = fopen(playlist->entries[idx], "r");
      if (!rom)
         goto error;
      fclose(rom);
   }
```

As it is, I think it would simply not show any roms in the XMB.
I can't test this right now, maybe tomorrow, if I can get everything to compile.

**Comment by fr500** [comment]
Don't show a messagebox, just use the OSD message queue to alert the user.

**Comment by pyroesp** [comment]
I've been digging around again and found `void rarch_playlist_load_content(void *data, unsigned idx)` in `retroarch.c`, which looks like the function loading the ROM with the core. A path check can be added in here to avoid to launch the core with an invalid path.
Well it's just a guess for now, until I can test this.

**Comment by pyroesp** [comment]
I've done the file check inside `rarch_playlist_load_content` and retroarch doesn't crash anymore. It just turns black for a fraction of a second as if to load something but returns to the XMB playlist.

I just have to get the OSD messages to work now.

**Comment by pyroesp** [comment]
This is what I currently have:
```C
void rarch_playlist_load_content(void *data, unsigned idx)
{
   const char *path             = NULL;
   const char *core_path        = NULL;
   content_playlist_t *playlist = (content_playlist_t*)data;
   menu_handle_t *menu          = menu_driver_get_ptr();
   settings_t  *settings        = config_get_ptr();

   if (!playlist)
      return;

   content_playlist_get_index(playlist,
         idx, &path, NULL, &core_path, NULL, NULL, NULL);

   FILE *fp = NULL;
   fp = fopen(path, "r");
   if (!fp)
   {
      struct font_params params;

      params.x           = 0.5f;
      params.y           = 0.5f;
      params.scale       = 1;
      params.color       = 0xFFFFFFFF;

      video_driver_set_osd_msg("File failed to load.\n", &params, NULL);
      RARCH_LOG("File at %s failed to load.\n", path);
      return;
   }
   fclose(fp);

   strlcpy(settings->libretro, core_path, sizeof(settings->libretro));

   if (menu)
      menu->load_no_content = (path) ? false : true;

   rarch_environment_cb(RETRO_ENVIRONMENT_EXEC, (void*)path);

   event_command(EVENT_CMD_LOAD_CORE);
}
```
I'm not sure how the OSD messages work or how to get it to display something.
If I include menu_display and use `menu_display_ctl(MENU_DISPLAY_CTL_FONT_BUF, &disp_buf);` to get the font I get a segmentation fault, that's why I left is to NULL.

(My OSD settings are: OSD enabled, font set to FreeSans, size set to 32, x and y pos set to 0.200.)

**Comment by fr500** [comment]
Hey, didn't catch you earlier, but:

<pyroesp> Anyone know how the OSD messages work ?
<pyroesp> I've tried using video_driver_set_osd_msg from within retroarch.c
but with NULL as font and nothing gets displayed (which I suppose is
normal, no font ...)
<pyroesp> I then tried using menu_display_ctl to get the font, then use the
font in video_driveset_osd_msg but I get a segmentation fault
<pyroesp> video_driver_set_osd_msg *
<radius> rarch_main_msg_queue_push("Message", 1, 100, true);
<radius> you don't need to initialize the font driver or anything
<radius> also you should use a builtin function to check if the path is
valid, I don't think it would be merged as it is
<radius> and he's not even here ...

**Comment by pyroesp** [comment]
Hello fr500,

Sorry about the IRC, I should have waited a bit for someone to reply.
Anyways, I'm going to try the rarch_main_msg_queue_push this afternoon. 
I've also found retro_fopen/retro_fclose, which has everything setup for crossplatform fopen/fclose, so I'm going to try using that instead of the standard fopen/fclose.
Hopefully that's what you mean by builtin function.

**Comment by pyroesp** [comment]
Ok, got it to work with retro_fopen, retro_fclose and rarch_main_msg_queue_push.
I had to include retro_file.h though.
