### ISSUE TITLE
IOS9/Pangu: Instant Crash

### ISSUE THREAD

**Issue by thecoreyburton** [libretro/RetroArch#2240]
I'm running the Pangu jailbreak on IOS 9.0.2 and it seems no matter which version of Retroarch I get (or where I get it from), the problem is the same: The app installs fine, but when I tap it it loads for a split second and then returns me to my icons. I tap the home button and it's running in the background, switch to it, and I'm returned (once again) to my icons. I'm assuming it's a problem due to the new IOS + Jailbreak but I'm not entirely sure.

This happened on 1.0.0.1 from the ZoDTTD repo, 1.0.0.2 from the buildbot page and both versions from the Kromite repo (http://kromite.github.io).

I've heard a lot of ranting about date / time, but this had no effect on the outcome.

**Comment by brujo5** [comment]
@twinaphex 


Actually, I think what's happening here is in fact not just JIT being potentially broken (maybe if we're lucky, it's not broken at all? — doubt it, though)

But rather... the fact that PPSSPP is an unsandboxed 32-bit binary.

Maybe -Wl,-segalign,4000 needs to be added to the linker flags?

See: https://twitter.com/saurik/status/654198997024796672

**Comment by fr500** [comment]
@brujo5 that's cool info... but why are you discussing random stuff on an issue that's not related to what you're discussing?

**Comment by brujo5** [comment]
I saw that this information could be of help and decided to put it here. credits are for @ angelxwind

**Comment by thecoreyburton** [comment]
A lot of similar information is here: https://github.com/hrydgard/ppsspp/issues/8066

**Comment by brujo5** [comment]
![image](https://cloud.githubusercontent.com/assets/4172898/10516725/e88777b6-7316-11e5-966a-81e8417deb5e.png)

@fr500 Andrés mira esto. Gracias

**Comment by brujo5** [comment]
from what i read in other sites: all bynaries need to be recompiled for 64 bit devices because they cause 32 bit third party Apps to crash in ios 9.

**Comment by brujo5** [comment]
Ppsspp fixed the app crash at lauch for add iOS 9 compatibily, homeweber crash at lauch any game (jit broken for pangu or someting).

The god news here is that retroarch will run faster in cache/pure interpreter mode in any ARM64 up.
So the point here is an New nightly build for iOS 9 whit new idevices like iphone 6S. iOS 8 is dead now

**Comment by twinaphex** [comment]
I'll ask radius to make iOS 9-only cores and put them on the buildbot. We will also begin working on nighty versions of RetroArch iOS/OSX. 

As for myself, I am not going to use iOS 9 jailbreak until I hear of at least one instance where an emulator with a dynarec/JIT works again. But we can make the interpreters work so far I guess.

**Comment by brujo5** [comment]
Yeah specially for New devices. The A9. Chip is an beast and 2 GB of RAM will make huge difference. Thx

**Comment by brujo5** [comment]
more info posted in reddit.

in iOS 9, applications that aren't natively capable of supporting 64-bit have to be recompiled due to a change in the way binaries work.
binaries can't be appropriately mapped to memory due to restrictions imposed by the instruction set architecture. Because of this, the applications can't be loaded into memory, and thus, cannot be ran. To make these applications work again, the creators need to recompile with these linker flags: -Wl,-segalign,4000

**Comment by brujo5** [comment]
is posible compiling retroarch via iphone + mobile terminal using theos for arm64 devices?

https://www.reddit.com/r/jailbreak/comments/3pcppx/update_coolstar_has_built_perl_for_arm64_device/

**Comment by niemandag** [comment]
I cannot get mobile terminal to work.

**Comment by brujo5** [comment]
ios 9.1 released . update to 9.0.2. you only have a few hours left until the signing window closes

**Comment by Francesco149** [comment]
Same issue here. I'd try compiling it for ios9 myself if I had a mac or an osx virtual machine, but I guess I'll be waiting for a ios9 version of the app. Let me know if you need any testing, I am on ios 9.0.2 jailbroken with Pangu

**Comment by Francesco149** [comment]
just tried compiling the latest git version with the supposed iOS9 flags on a virtual machine, still crashes on startup

**Comment by fr500** [comment]
can you try changing deployment target to 9.0?

**Comment by fr500** [comment]
I added an ios9 version to cydia, still untested, just changed deployment target, can you give it a try?

**Comment by Francesco149** [comment]
Sure. Which repo are we talking about though? Because libretro.com/cydia doesn't work for me.

**Comment by brujo5** [comment]
@fr500 

los ultimos builds que subieron para ios 9 tienen algunas incoherencias por ejemplo
la APP bundle RetroArch_iOS9
el binario/executable RetroArch iOS9 ------->sin el guion bajo

y si te fijas dentro del info plist los nombres de estas no coinciden pues todos son RetroArch por eso es que no aparece ningun icono al instalarlo.

**Comment by fr500** [comment]
@brujo5 please try again

**Comment by brujo5** [comment]
Size mizmatch, still waiting for complete upload

![image](https://cloud.githubusercontent.com/assets/4172898/10835082/21ecfdaa-7e5c-11e5-9493-b02477cb818c.png)

**Comment by fr500** [comment]
ugh this thing hates me, it's rebuilding now, so try again in 20 or so

**Comment by fr500** [comment]
Ok, go now

**Comment by brujo5** [comment]
Lo descargue del buildbot del foro pero sigue teniendo incoherencia en los nombres. La informacion no checa con la del info.plist por eso sigue sin aparecer

Te recomiendo renormbrar de RetroArch_iOS9.app a RetroArch9.app y hacer lo mismo con el ejecutable. Pues algunos signos y guion bajos no van.
Tambien revisa el info.plist y fijate que los nombres coincidad

**Comment by fr500** [comment]
Cual foro?, cual link? es el mismo buildbot, Y ya cambie el nombre del app en el bundle todo concuerda

**Comment by brujo5** [comment]
Este lo descargue hace como 10min

![image](https://cloud.githubusercontent.com/assets/4172898/10836450/f17a605e-7e6a-11e5-8078-3582559d6f7b.png)

Y estos errores me refiero 
![image](https://cloud.githubusercontent.com/assets/4172898/10836461/07897100-7e6b-11e5-9fe5-35b382d16af5.png)
![image](https://cloud.githubusercontent.com/assets/4172898/10836462/07a55df2-7e6b-11e5-8715-81295373eb79.png)

Y en el info plist varias veces dice RetroArch en varias partes

![image](https://cloud.githubusercontent.com/assets/4172898/10836476/316daf5e-7e6b-11e5-9333-6db0a98c15df.png)

**Comment by angelXwind** [comment]
@twinaphex Hi, I'm an iOS developer/maintainer/person for PPSSPP (and reicast) — here's a super-tl;dr version of what happened: Pangu9 (`fuxiqin`) doesn't patch the kernel anymore (due to CSR/SIP/KPP), so `VM_PROTECT` is untouched.

I made a rather lengthy post about why this happens and how to fix it (along with another iOS 9 issue) — give it a read, I suppose: https://github.com/hrydgard/ppsspp/issues/8122

**Comment by fr500** [comment]
ok, so basically for the startup crash, we have to sign the builds, period.
Can't do this now since my net is too slow where I'm latelety but it can be done, I'm not really familiar with the process but it shouldn't be too hard, hopefully most of it can be done from the command line

**Comment by fr500** [comment]
@brujo5 I know the build doesn't work, but does it install and appear on the springboard at least?

**Comment by brujo5** [comment]
@fr500

El build de ios 9 tiene ese problema que te explique arriba y por eso el icono no aparece en el springboard.

Usa los mismos nombres que la version para ios 8 ya que esa si se instala correctamente.

O en pocas palabras hagan un build universal que funcione tanto en ios 9 y anteriores.

**Comment by fr500** [comment]
En mas facil decir que hacer.
En todo caso creo que ya esta... esta compilando ahora, con los nombres corregidos y firmado, puedes venir a IRC?

**Comment by brujo5** [comment]
Una vez que hayas compilado retoarch para ios 9,extrae el deb con 7zip e instala plist editor ahora busca el info plist del archivo que extraiste y revisa los nombres que bienen ahi y notaras que son diferentes alos de la app bundle y ejecutable.
Este problema solo lo tienen los build que compilas para ios 9.

Todo eso asumiendo que estas en windows

**Comment by fr500** [comment]
Puedes venir a IRC o no?

**Comment by fr500** [comment]
The build is ready on cydia but the CDN cache might take a while to refresh, the names match too

**Comment by brujo5** [comment]
Haber checa estor en freenode #retroarch

**Comment by brujo5** [comment]
No puedo configurar lo proncipal
![image](https://cloud.githubusercontent.com/assets/4172898/10840694/05702c22-7e9f-11e5-9162-28244bb162c8.png)

**Comment by fr500** [comment]
@angelXwind thanks a lot, the frontend launches now at least

**Comment by brujo5** [comment]
![image](https://cloud.githubusercontent.com/assets/4172898/10841140/fd9cf818-7ea3-11e5-92b2-9bce98bb42a2.png)
![image](https://cloud.githubusercontent.com/assets/4172898/10841141/fdbe8118-7ea3-11e5-985e-b0c90a2ab42d.png)
![image](https://cloud.githubusercontent.com/assets/4172898/10841142/fdc00e98-7ea3-11e5-988a-eb6913a0bf80.png)

Si hacen funcionar el driver GLUI  con eso basta para mi

**Comment by brujo5** [comment]
Tested ios 8 cores like desmume (interprete mode) and other in retroarch for ios 9 and. It working perfect..
@twinaphex @fr500

**Comment by fr500** [comment]
Thanks, I'll close this but feel free to keep discussing here

**Comment by brujo5** [comment]
Dude any idea why MAME 2014 is the only core that still crashes in retroarch 9??

That wired because dont use JIT
All others cores from ios 8 working.

O nesesito agregar ala configuracion mame2014 cpu_mode = interprete?

**Comment by fr500** [comment]
No idea, and no there is no JIT or anything on mame

**Comment by brujo5** [comment]
A falta de una version reciente fel FBA como la de windows sin el MAME no podre pobrar los ultimos juegos agregados de PGM the gladiator.

Lacking a recent version FBA fel like windows, without the MAME not be able to test the latest games added PGM the gladiator.

**Comment by brujo5** [comment]
Andrés, compile MAME is complicated for you? I do not believe that ikarit is the only to do

**Comment by fr500** [comment]
All the cores are built by my scripts.
MAME doesn't build for iOS9 because apple deprecated some C++ stuff, it's nothing I can fix

**Comment by brujo5** [comment]
I did not know it.
posible add an more recent FBA core Android/iOS in near future?

tambien me aparecio una actualizacion del retroarch para ios 9 pero me da error size mismatch al instalarla.

y se podria actualizar el desmume a una version mas reciente? por que la de ios de hace varios meses atras?

thx

**Comment by fr500** [comment]
building is failing, if someone fixes it it will just reappear.

**Comment by fr500** [comment]
can you try reinstalling now? I purged the cache

**Comment by brujo5** [comment]
dame unos minutos y te digo.

**Comment by brujo5** [comment]
ya se arreglo gracias

**Comment by brujo5** [comment]
@fr500 

Andres las bios de psx y el pligin rice para mupen64, van en la carpeta system o configs?

porque antes todo esta en la carpeta .Retroarch

**Comment by brujo5** [comment]
@fr500 no me ahabia dado cuenta que ahora iOS tiene el fba core mas reciente. muchjisimas gracias por fin puedo jugar ther gladiator y sprectas vs generations de la placa pgm.

**Comment by brujo5** [comment]
Ahora que cambiaron la direccion de descarga del core updater hay algunos cores que no estan disponibles en la carpeta latest de ios 8 que a la que dirige.
Ya que aparecieron en la seccion de ios 9 un ejemplo es la version reciente del FBA core. Y con el cambio reciente no aparece en la lista.

**Comment by danyjl94** [comment]
Retroarch still crashes on iOS 9.0.2 iPhone 6 even on PlayStation (PCSX ReARMed) [Interpreter] when  you load a rom.

**Comment by fr500** [comment]
@brujo5 please use english so everyone can understand.
did the URL change? I don't see it change anywhere I asked last night on the forum and they said it's using iOS not iOS9.

If something isn't available it means it's not building for the platform.

**Comment by brujo5** [comment]
Yeap still use the folder for ios 8 cores (latest)
In this folder the latest FBA and other new core inst available.

**Comment by fr500** [comment]
but you said it was changed it was never changed please try to be clear

**Comment by brujo5** [comment]
Ios 9 folder have  3 FBA cores

![image](https://cloud.githubusercontent.com/assets/4172898/10864548/9debb7fe-7fae-11e5-885c-486c3a561c0a.png)

Ios 8 folder have 2 FBA cores (this URL comes in retroarch by default)

![image](https://cloud.githubusercontent.com/assets/4172898/10864552/c6a3ada0-7fae-11e5-90e3-87a3ab19ea66.png)

**Comment by brujo5** [comment]
For that razon the latest fba are not available via core updater inside RA.

![image](https://cloud.githubusercontent.com/assets/4172898/10864566/21d1dd82-7faf-11e5-83be-ef815b08788b.png)

**Comment by fr500** [comment]
Yes but your previous post says:
"Ahora que cambiaron la direccion de descarga del core updater hay algunos cores que no estan disponibles en la carpeta latest de ios 8 que es a la que dirige."

Now that you changed the core updatar URL there are some cores that are not available.
And we haven't changed it.

**Comment by brujo5** [comment]
That true was my fault, sorry. Any way is easy to fix.

Only need to copy/paste the other URL in the updater settings

**Comment by twinaphex** [comment]
Pushed a commit here -

https://github.com/libretro/RetroArch/commit/f8fae2914ff5dfedf494702c5fa3ed9b63c590f9

It should now detect if the OS is iOS 9 or later and then it should set the correct URL.

NOTE: You might need to uninstall and reinstall RetroArch first for these changes to take effect. If you want to know if it worked correctly, the URL should be:

http://buildbot.libretro.com/nightly/apple/ios9/latest/

**Comment by brujo5** [comment]
yeap it works after deleting retroarch.cfg in configs folder. thanks

@twinaphex 

could you fix the desmume makefile script?

**Comment by danyjl94** [comment]
Does Retroarch run ps1 roms on iOS 9.0.2 iPhone 6 yet.

**Comment by brujo5** [comment]
Core updater still use the ios 8 folder. Why not RA ios8/ios9 could use the same URL for ios 9 core folder (latest). 
Anyway is easy to fix

![image](https://cloud.githubusercontent.com/assets/4172898/10875300/268703f8-80ee-11e5-9f03-c0bb955c7aff.png)

Also noticed that the general settings (driver,video,sound,etc) using the default cocoa menu disapear. (But can go after press switch to GL driver
This is simple but i like.
![image](https://cloud.githubusercontent.com/assets/4172898/10875322/6e102830-80ee-11e5-9e88-6f73173d7692.png)

Is MAME 0.167 available for Android??

**Comment by brujo5** [comment]
When i enabled video treaded the onscreen overlay appear and touch interface stop working

![image](https://cloud.githubusercontent.com/assets/4172898/10886540/af04246c-813f-11e5-905a-c97b0b23a526.png)

Whit option is better for mobile?

![image](https://cloud.githubusercontent.com/assets/4172898/10886566/cf745ec4-813f-11e5-863e-6b68c814caa3.png)

**Comment by danyjl94** [comment]
Tried to install I keep getting size mismatch

**Comment by twinaphex** [comment]
@brujo5 - To get touch input back then, first you need to disable the overlay. 

But yeah this should not appear either way. I will attempt to fix it.

**Comment by brujo5** [comment]
Ok thanks.

**Comment by brujo5** [comment]
Here another simple thing.

Cant add a new URL for the updater using glui driver 

![image](https://cloud.githubusercontent.com/assets/4172898/10897536/792f87ba-817f-11e5-8df7-99125bc92f20.png)

But its fine using the default 

![image](https://cloud.githubusercontent.com/assets/4172898/10897549/a3589bbc-817f-11e5-9f28-0244012a1094.png)

**Comment by fr500** [comment]
You need to set an OSK overlay, then it will appear for you to type

**Comment by brujo5** [comment]
that makes sense, thanks

**Comment by fr500** [comment]
Size mismatch means you need to refresh your sources before reinstalling, that's all there is too it, just refresh and reinstall.
Please let this "thread die" and use the forum for any further discussion.

**Comment by Pierro21** [comment]
Normally I agree with you fr500 but i tried yesterday to do that like 10 times and it doesn't worked. I only can update with this morning update!

**Comment by brujo5** [comment]
sometimes size mismatch is from server side, corrup upload or cache not cleared.

**Comment by fr500** [comment]
@Pierro21 @brujo5 is correct, it's a cache issue, we are publishing builds very often, but we don't have unlimited bandwidth so we use cloudfare.

So at certain times you might download over and over the same package list but the package may not be cached or viceversa

**Comment by Pierro21** [comment]
Ok I understand! Thanks for the explanation!

**Comment by brujo5** [comment]
@twinaphex 

Just found the mame2003 core They do not match the name for the core info

![image](https://cloud.githubusercontent.com/assets/4172898/10931290/68cba84a-8283-11e5-9db8-094b2a07658a.png)
![image](https://cloud.githubusercontent.com/assets/4172898/10931291/68eea048-8283-11e5-94df-f10b3b1153a1.png)

**Comment by brujo5** [comment]
glui is broken in the last update.

![image](https://cloud.githubusercontent.com/assets/4172898/11024677/43b06774-864f-11e5-9362-b24dbb0995ee.png)

**Comment by twinaphex** [comment]
Reverted the last commit, let me know if it's fixed in the next nightly.

**Comment by brujo5** [comment]
Sorry for the delay, yes is fixed now. Thanks
