### ISSUE TITLE
Update Readme.md in "Playstation 3" part

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#2245]
> PlayStation3
>
> RetroArch PS3 needs to be compiled in the following order:
>
> 1) Compile RetroArch Salamander
>
> make -f Makefile.ps3.salamander
>
> 2) Compile the RGL video driver
>
> make -f Makefile.ps3.rgl
>
> 3) Compile RetroArch as a library
>
> make -f Makefile.ps3.retroarch

I not have Makefile.ps3.rgl. Please clarify Readme.md and update wiki pages, because I found none information about it.

Yes, I got PS3 SDK v3.40

**Comment by twinaphex** [comment]
Done - 

https://github.com/libretro/RetroArch/commit/dbd119674eb6cdd8239c3603d81af15caf66453d

**Comment by ofry** [comment]
Next question. How I can obtain libretro_ps3.a ?
