### ISSUE TITLE
[PS3] Can't build libretro_ps3.a

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#2255]
I built cores for PS3.

Next I copied all *.a files to /dist-scripts/,
went back to retroarch,
run:
`configure`

went to /dist-scripts/ and run:

`dist-cores.sh dex-ps3/cex-ps3 2>&1 | tee retroarch-build-ps3-19-10-2015.log`

Result is there:

http://pastebin.com/6FWbBNsf

After it make.exe occupied one core by full without new output...

**Comment by ofry** [comment]
I have PS3 SDK v3.40.

**Comment by ofry** [comment]
If I build only cex-ps3, I got:

http://pastebin.com/yzbc5pb6

**Comment by ofry** [comment]
Huh, some cores doesn't link. So I built some cores only for dex-ps3.

Next I put
`make -f Makefile.ps3.salamander`

next:

`make -f Makefile.ps3 pkg-signed`.

I got this:
http://pastebin.com/84dSQv0A

**Comment by twinaphex** [comment]
Pushed a commit for this -

https://github.com/libretro/RetroArch/commit/502843f35c31431e527ef723862f7bb958226357
