### ISSUE TITLE
[Pi 2] All cores run slower than they should

### ISSUE THREAD

**Issue by Gruncher** [libretro/RetroArch#2258]
I'm running a Pi 2 with Arch Linux and trying to compile RetroArch myself.

My issue is that no matter which core I use, it runs slower than it should. I can't get the on-screen FPS display to work, but I feel as though it's about 90% full speed, along with slow/crackling audio.

I've tried recompiling RetroArch several times with different options to no avail, and I've messed around with the settings (disabling audio, vsync, etc) and nothing helped.

All reports say that many RetroArch cores should run near-flawlessly on a Pi 2, so I'm sure this is down to some error of mine.

Does anyone have any ideas or suggestions as to what the problem could be? I'm at my wits end here.

**Comment by joolswills** [comment]
It's not possible to advise without any information - eg configure options etc. Not sure if this issue tracker is the best place for general support though.

There is a known issue with the FPS display.

**Comment by Kivutar** [comment]
I got a similar issue with some TVs, can you try to enable threaded video output, or disable vsync (or both) ?

**Comment by Gruncher** [comment]
Kivutar, I enabled threaded video and it fixed the slowdown as far as I can tell! I did have vsync disabled but it didn't help.

You're such a lifesaver! I've been struggling with this problem for days and never thought of that setting. I even went as far as to order a new power supply last night, because I do sometimes get the low voltage warning in the corner.

Unfortunately, now it seems as though my audio lags behind about 250ms (roughly) in all emulators and I do have audio sync enabled.

Any ideas?

**Comment by joolswills** [comment]
Good idea to get the new PSU also - a poor PSU can affect performance I believe too. You can see some of the default settings (changed over the chipped retroarch.cfg defaults) for RetroPie which may be useful to you - https://github.com/RetroPie/RetroPie-Setup/blob/master/scriptmodules/emulators/retroarch.sh#L68

Changing the render resolution can help with performance too - especially when using shaders etc. On retropie we default to 640x480 (video_fullscreen_x / video_fullscreen_y) but it is configurable

**Comment by hizzlekizzle** [comment]
This kind of discussion really belongs on the forum, not in a github issue, which is supposed to be strictly related to development.

**Comment by Gruncher** [comment]
After messing around with it, I discovered that my monitor was running at 50hz - I set retroarch to reflect that, and my speed issues went away.

However, now I discovered that my audio lags about 1/4 of a second behind the gameplay, and I can't figure out how to fix that. Even setting audio sync does nothing.

**Comment by Gruncher** [comment]
I fixed it! The emulators seem to all work perfectly now.

I solved the audio lag by uninstalling the packages: pulseaudio and pulseaudio-alsa

For whatever reason, pulseaudio was giving me lots of audio latency that I couldn't fix, but uninstalling those made it perfect.

Hopefully this helps someone on google at some point! Getting RetroArch to run properly has been insanely frustrating!

**Comment by twinaphex** [comment]
Unfortunately I can do nothing about PulseAudio being bad for gaming purposes compared to ALSA. 

If it were up to me I'd recommend people on a Linux distro to completely uninstall it but based on whatever distro you are using and the hard dependencies on it by other software that you have installed from your package manager, that might not be an option.
