### ISSUE TITLE
[iOS] RetroArch 1.2.2 some issues.

### ISSUE THREAD

**Issue by brujo5** [libretro/RetroArch#2263]
installed latest RA 1.2.2 thx to @ Zero2029 for provide build.

have some minor UI problems but is full usable/playable (i like the gl driver + touch screen) finally work in iOS.

is posible to set for default tread data runloop  OFF.? this never work and cause crashes/UI issues.

Alll cores compiled for iOS 9 working fine (some in interpreter like mupen64, pcsxreamed)

those cores missing from buildbot:
desmume
pcsx
mame 2014/2015  (remember this was tested before and work perfect in ios (based in libco)
tested the old one for ios 8 but it crash because need ios 9 support)I miss so much this Core:(
UME
ppsspp

thx

**Comment by thecoreyburton** [comment]
Can you provide a link to the build you're using?

**Comment by brujo5** [comment]
Is available in the forum, homwever developer says nightly buildbot will be available today vía buildbot 
http://libretro.com/forums/showthread.php?t=4201&page=3

**Comment by CoreCreator** [comment]
I'm trying to compile using Xcode 7 however my first 2 errors are 

CpResource /Users/administrator/Downloads/RetroArch-master/media/shaders_glsl /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app/shaders_glsl
    cd /Users/administrator/Downloads/RetroArch-master/pkg/apple
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/administrator/Downloads/RetroArch-master/media/shaders_glsl /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app

error: /Users/administrator/Downloads/RetroArch-master/media/shaders_glsl: No such file or directory

and

CpResource /Users/administrator/Downloads/RetroArch-master/media/assets /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app/assets
    cd /Users/administrator/Downloads/RetroArch-master/pkg/apple
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/administrator/Downloads/RetroArch-master/media/assets /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app

error: /Users/administrator/Downloads/RetroArch-master/media/assets: No such file or directory

... how can i use a highly build to install using Xcode 7's side loading feature? or how do i fix these?

**Comment by fr500** [comment]
so, how do I build for iOS < 9?
I want to start providing builds for iOS but I'm new to XCODE, all I can see is that I have the iOS 9 SDK but I want to provide builds for 9 and for < 9

**Comment by brujo5** [comment]
@fr500 

dont know if help
http://stackoverflow.com/questions/30874352/ios-9-not-supported-on-xcode-6-3


 is there an script  for MAME 2014/2015 for ios or the core will not be available?
all other platforms have it:(

**Comment by fr500** [comment]
I can build for iOS 9 just fine, I have XCODE 7
I want to know if the iOS version will work on 8, and 7 too

MAME is not building, I dunno why, it's just failing

**Comment by brujo5** [comment]
i think you cant.

Just note that anything that was introduced with iOS9 will not work on iOS 8,7,6 phones or lower.

or try to run the ios simulator in xcode

**Comment by brujo5** [comment]
@fr500 

an user in forum sucefully compiled RA for ios9

try to compare 

https://gist.github.com/brujo5/5f0693fa454208590b92

**Comment by CoreCreator** [comment]
I fixed the issue by referencing #2213. It ended up fixing the issue. I am currently running it on iOS 8.4.1, however my device is not jail broken so I have to CONSTANTLY rechose "system", "saves", and "states" folder as the retro arch folders every time I close and reopen the app. I will test once I change the directories(again) whether it crashes or not an edit this post. However for just the run part it runs fine.

**Comment by CoreCreator** [comment]
Currently i tried ff5 and it crashed when I tried snes 9 after updating everything. I'm not in the mood to reconfigure everything AGAIN(I can't save config cuz it tries to save to the app not the app data, and I'm not jail broken so I can't) currently ff5 doesn't work on snes 9 iOS 8.4.1... That could be the device or just the not jail broken or just the snes version... But I'm guessing it's 8.4.1 or that I'm not jail broken... If your on a 64-bit iOS 8.4.1 I would suggest using Yalu to jailbreak it(Google, an any further questions Google Luca todesco Twitter[not me, just the guy who made it and helped me]) and perhaps it will work on a jail broken device. I'm also on a 4s, doubt that's what's causing the instant crash when I load a game... But it could be.

I take no claim over any of the above mentioned names or software and am not the creator or developer for the above mentioned names or software

**Comment by CoreCreator** [comment]
OMG BRUNO5 TYVM! I was wondering why it kept crashing... It's because the cores aren't signed! TYTYTYTY! I will try this then post again when I'm near the computer!

**Comment by fr500** [comment]
Please don't treat the bug tracker like a forum.

**Comment by brujo5** [comment]
@fr500 

Come here please http://libretro.com/forums/showthread.php?t=4221&p=29716#post29716

**Comment by brujo5** [comment]
and if you contact @ angelxwind

she managed the ppsspp buildbot for ios https://twitter.com/angelXwind

**Comment by brujo5** [comment]
@fr500 

Maybe we should make an iOS 9 target, we have an iOS 6 target already.


did you try make one ios 9 target for me?

i can test right now.

**Comment by brujo5** [comment]
@fr500 @twinaphex 

Please try to contact angelxwind she is already aware of this.

Read here
https://www.reddit.com/r/jailbreak/comments/3psssd/news_retroarch_dev_need_help_in_how_add_ios_9/

**Comment by brujo5** [comment]
@twinaphex 

What about http://iphonedevwiki.net/index.php/Updating_extensions_for_iOS_9

**Comment by brujo5** [comment]
@angelxwind

this is the same issue as ppsspp?

thanks

**Comment by brujo5** [comment]
Here better explanation for compiling for ios 9 thx to zero. 

http://libretro.com/forums/showthread.php?t=4201&page=12&p=29883#post29883

**Comment by twinaphex** [comment]
Can you ask him to come on #retroarch? I can't really tell from that guide what we are missing. Maybe he can help us get the current Cydia build we have running on iOS 9 devices if it works for him on non-jailbroken as well.

**Comment by brujo5** [comment]
Sure!!

**Comment by brujo5** [comment]
Some users post new info about building

http://libretro.com/forums/showthread.php?t=4239&p=30072#post30072
