### ISSUE TITLE
no shaders or assets in media. iOS build.

### ISSUE THREAD

**Issue by CoreCreator** [libretro/RetroArch#2266]
CpResource /Users/administrator/Downloads/RetroArch-master/media/shaders_glsl /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app/shaders_glsl
    cd /Users/administrator/Downloads/RetroArch-master/pkg/apple
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/administrator/Downloads/RetroArch-master/media/shaders_glsl /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app

error: /Users/administrator/Downloads/RetroArch-master/media/shaders_glsl: No such file or directory

and

CpResource /Users/administrator/Downloads/RetroArch-master/media/assets /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app/assets
    cd /Users/administrator/Downloads/RetroArch-master/pkg/apple
    export PATH="/Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode-beta.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/administrator/Downloads/RetroArch-master/media/assets /Users/administrator/Library/Developer/Xcode/DerivedData/RetroArch_iOS-axanqwjsooseuxeyqyuvxvbhcsrb/Build/Products/Debug-iphonesimulator/RetroArch.app

error: /Users/administrator/Downloads/RetroArch-master/media/assets: No such file or directory

**Comment by CoreCreator** [comment]
nvm i followed an older thread #2213

**Comment by fr500** [comment]
Yes, packaging is not part of the build process.
