### ISSUE TITLE
how to change location of retroarch.cfg to app data "system"?

### ISSUE THREAD

**Issue by CoreCreator** [libretro/RetroArch#2269]
I'm on a non jailbroken phone and got retroarch side loaded on my iPhone... however i have to rechose the directories for the cores etc every time i load it and i can't save and load config because it keeps attempting to rewrite retroarch.cfg in retroarch.app/(even when i change the config location) which it can't of course since i don't have root access. does anyone know how to change a file in the build to point retroarch.cfg to the app data system/ folder before i sideload it with xcode?

**Comment by fr500** [comment]
Should be fixed already, can you confirm?
