### ISSUE TITLE
"Add Content" not working in latest build-bot nightly

### ISSUE THREAD

**Issue by Nerdy314159265** [libretro/RetroArch#2277]
Title explains most of it. I was testing the Add content feature in the latest nightly and it seems completely non-functional. I set it to scan a directory, which it proceeds to do and it doesn't create a playlist nor any menu entry to select it.

I am running on Windows 10 x86_64

**Comment by twinaphex** [comment]
Which platform? Please mention these things in the issue.

**Comment by Nerdy314159265** [comment]
Apologies, sometimes I can be a bit air-headed.

Windows 10 x86_64

**Comment by fr500** [comment]
It's working fine here, make sure you have the databases, update them and make sure you have a playlist dir.

I use no-intro roms mostly. Feel free to keep discussing the issue.

**Comment by Nerdy314159265** [comment]
Apologies. I thought that the database file was already included with the nightly build download. Manually updating the databases fixed it. Man I feel like an idiot, sorry about that.
