### ISSUE TITLE
RetroArch doesn't increase asynchronous audio consumption rate when sped up

### ISSUE THREAD

**Issue by julianko** [libretro/RetroArch#2279]
when using asynchronous audio (via retro_audio_callback), RetroArch doesn't increase the rate at which it consumes audio samples when the game is sped up by unlocking the frame rate.

this has the effect that the gameplay runs considerably faster (as it should) while the audio continues to play at normal speed.

interesting to note is that when slowing down instead of speeding up, it seems to work as it should.

**Comment by Alcaro** [comment]
Possibly relevant discussion: http://libretro.com/forums/showthread.php?t=4217

**Comment by twinaphex** [comment]
@Themaister Any thoughts here as to whether this issue is valid?
