### ISSUE TITLE
final fantasy 8 disk 3 on ios pcsx rearemed new verison doesnt fix 

### ISSUE THREAD

**Issue by asbel123** [libretro/RetroArch#228]
i got a bug on final fantasy 8 disk 3 when on after lunar cry video finsh it froze my charcter not moving and sound doesnt work

**Comment by davcri** [comment]
__Solution found__ :smile: 

1. Menù -> core option -> enable InuYasha Sengoku Battle Fix
2. Play as usual

Works with RetroArch 1.3.0 - PCSX-ReARMed r22

PS: I know that this issue is 3 years old, but this is one of the firsts link that google gives, so it's useful to have it here.
