### ISSUE TITLE
looking for correct aspect settings on vertical shmups rotated 90 (or 270). tate mode shmups...

### ISSUE THREAD

**Issue by frenchfriess** [libretro/RetroArch#2316]
trying to play vertical shmups in FBA

dodonpachi, ketsui, dragon blaze, gunbird 2, battle garegga. those kinds of games. I have a monitor set up on its side to be able to play full screen in these types of games.

When I set the screen to rotate 90 degrees. I cannot figure out a setting that stretches to full screen properly. unless it's a FULL 1080p stretch and I dont want that. just looking for correct auto stretch for my vertical shmups with FBA and mame and UME and such... in tate mode. rotated. you get the idea... vertical shmups. screen rotated 90 for full screen. need correct aspect ratio please... 

first play one of those games on regular non rotated setting... then imagine what it should look like rotated 90 degrees... then rotate it 90 degrees and see what happens

**Comment by fr500** [comment]
Please don't use the issue tracker as a forum, we have a forum too
www.libretro.com

**Comment by Kivutar** [comment]
When the aspect ratio is provided by the core, why not having it follow the rotation?
A 16:9 game, when rotated 90 degrees, should become a 9:16.

**Comment by frenchfriess** [comment]
Yea thats what I'm saying. It's an issue... Not just settings I'm looking for. Im pretty sure they aint there...
