### ISSUE TITLE
[iOS] RetroArch Crashes on ROM Load

### ISSUE THREAD

**Issue by EmilSayahi** [libretro/RetroArch#2327]
Hello, I've been searching around for a possible fix to this but haven't found one. I cannot load any ROMs (More specifically I'm mostly trying to load N64 games) and no matter what core I use (I'm on iOS 9, even iOS 9 versions don't fix it) it just crashes the RetroArch app immediately after I select the ROM. Is this a common issue? What could be causing this? Do you think it is a Pangu issue or due to the changes in iOS 9?

**Comment by fr500** [comment]
Did you build retroarch and the cores yourself?

**Comment by brujo5** [comment]
i dont have any issue.

Is because Dynarec doesnt work for 64 bit devices, have to change the core option to Cache Interpreter.

Load a N64 game.

At the middle top, is a transparent button that takes you to another menu. So, when you load a rom, you have to push that button as fast as possible, and then if you did it in time, you will be able to change the core options. After that, you have to return no main menu. Have to push back and press something else, u til it takes you back, when done. Press on close content, and you are good to go!

**Comment by ssangkong** [comment]
Desmume core crashes after ROM load.
Even if I set desmume_cpu_mode = "interpreter"

**Comment by brujo5** [comment]
Nope.
It work perfect for me!!.

![image](https://cloud.githubusercontent.com/assets/4172898/10894314/2777313e-816b-11e5-803a-29e178f61a03.png)

![image](https://cloud.githubusercontent.com/assets/4172898/10894374/6c99a666-816b-11e5-8507-570aa59ff6d6.png)

i only wish an recent version of MAME/UME core for ios to match Android:)

**Comment by EmilSayahi** [comment]
I can't access the menu to change the interpreter and I can't build RetroArch for iOS myself as I don't have a Mac and I'm not willing to use a virtual machine.

**Comment by EmilSayahi** [comment]
Could you guys perhaps provide a .cfg that has it setup correctly?

**Comment by ssangkong** [comment]
Thx @brujo5 .
I tried over and over again.
Finally, I can run desmume. (very slowly, because broken dynarec)

**Comment by brujo5** [comment]
Speed depends of the device: an iphone 6S can run desmume at 50+ fps in normal mode. In low power mode at 25-30fps all time. Remember that interprete mode is CPU intensive.

**Comment by ssangkong** [comment]
My device is iPad Air 2. 
Maybe it depend on ROM file.

**Comment by silvercomet** [comment]
@brujo5 I tried to run Professsor Layton nds game on retroarch and it doesn't let me have enough time to press the middle button to switch to change the cpu mode at all. It just stands there then crashed. I ran it on ipad mini, ios 9. 
I tried to compile the retroarch ios 9 in the github directory but can't change the bundle identifier, retroarch branch works fine but can't even play the roms that I want. You have any suggestion? I removed it on my iphone 6. Might try that but it didn't work earlier. What ios are you having @brujo5 ?

**Comment by silvercomet** [comment]
Can anyone be kind provide me a nds rom that works for them? I am using ip 6 non jail broken. I added the line desmume_cpu_mode = "cached_interpreter" but could not get it to load the rom professor Layton and the curious village. I tested the mupen64 core and add the core option to be cached intepreter and it just worked. So I'm stuck with the desmume core. When i loaded the rom, it crashed immediately.
@ssangkong, could you tell me what you did try to make the desmume to work? Thank you very much

**Comment by silvercomet** [comment]
I forgot to mention, I'm on ios 9.1

**Comment by brujo5** [comment]
@silvercomet 

change cached_interpreter for interpreter.

desmume dont have cache inerpreter.

**Comment by fr500** [comment]
@silvercomet don't ask for roms here, and in any case this is a core issue and it doesn't belong here.
Please stop treating the issue tracker as a forum.

**Comment by zimou131** [comment]
have you ever scrambled to find your shopping list on your old clunky smartphone?  well no more!"  6:16 this scene should have been in black and white﻿ .... :)

see   : https://9apps.ooo/ 
https://vidmate.vip/ 
https://getmobdro.com/
--
