### ISSUE TITLE
Cheevos causing RetroArch to crash

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2343]
@leiradel 
happens on content load, stacktrace:

>(gdb) back
#0  0x00007ffe96e114e0 in strncpy () from C:\WINDOWS\system32\msvcrt.dll
#1  0x0000000000514eff in cheevos_get_value (length=32,
    value=0x613d28 <cheevos_locals+40> "", key_hash=237878566,
    json=<optimized out>) at cheevos.c:317
#2  cheevos_login (timeout=timeout@entry=0x22dc40) at cheevos.c:1181
#3  0x00000000005151a8 in cheevos_login (timeout=0x22dc40) at cheevos.c:225
#4  cheevos_playing_activity (game_id=game_id@entry=232,
    timeout=timeout@entry=0x22dc40) at cheevos.c:1381
#5  0x0000000000516d4f in cheevos_load (info=<optimized out>)
    at cheevos.c:1779
#6  0x000000000040f0c8 in load_content (content=0x9c9c9b0, content=0x9c9c9b0,
    special=<optimized out>) at content.c:522
#7  init_content_file () at content.c:670
#8  0x0000000000407c81 in event_init_content () at command_event.c:698
#9  event_init_core () at command_event.c:751
#10 event_command (cmd=cmd@entry=EVENT_CMD_CORE_INIT) at command_event.c:1378
#11 0x0000000000403a72 in rarch_main_init (argc=164415072, argv=0x9ccad00,
    argv@entry=0x232460) at retroarch.c:1193
#12 0x00000000004019d1 in main_load_content (argc=argc@entry=0,
    argv=argv@entry=0x0, args=args@entry=0x0,
    environ_get=environ_get@entry=0x477c00 <menu_environment_get>,
    process_args=0x0) at frontend/frontend.c:252
#13 0x0000000000477d65 in menu_load_content (type=type@entry=CORE_TYPE_PLAIN)
    at menu/menu.c:100
#14 0x0000000000405157 in rarch_ctl (
    state=state@entry=RARCH_ACTION_STATE_LOAD_CONTENT, data=data@entry=0x0)
    at retroarch.c:1358
#15 0x00000000004228d1 in rarch_environment_cb (cmd=cmd@entry=131073,
    data=0x2d8cb90) at dynamic.c:1236
#16 0x000000000040570d in rarch_playlist_load_content (data=<optimized out>,
    idx=<optimized out>) at retroarch.c:1548
#17 0x00000000004b5965 in action_ok_playlist_entry (path=<optimized out>,
    label=<optimized out>, type=<optimized out>, idx=<optimized out>,
    entry_idx=0) at menu/cbs/menu_cbs_ok.c:554
#18 0x000000000049188a in menu_entry_action (entry=entry@entry=0x237af0,
    i=<optimized out>, action=action@entry=MENU_ACTION_OK)
    at menu/menu_entry.c:381
#19 0x00000000004cafe7 in generic_menu_iterate (action=MENU_ACTION_OK)
    at menu/drivers/menu_generic.c:280
#20 0x000000000040c05d in rarch_main_iterate (
    sleep_ms=sleep_ms@entry=0x23fdac) at runloop.c:990
#21 0x0000000000401e20 in rarch_main (argc=<optimized out>,
    argv=<optimized out>, data=0x0) at frontend/frontend.c:342
#22 0x0000000000521aea in console_main ()
#23 0x0000000000521ba1 in WinMain ()
#24 0x00000000004013ed in __tmainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:332
#25 0x000000000040152b in mainCRTStartup ()
    at C:/repo/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:212

Also the same happens when starting a netplay server with cheevos enabled.
I've got to mention, my personal builds use a newer toolchain (the buildbot toolchain is no longer available on MSYS2)

**Comment by leiradel** [comment]
fixed by #2344?

**Comment by fr500** [comment]
It seems so yes
