### ISSUE TITLE
Special Characters in Controller Name

### ISSUE THREAD

**Issue by smcdougall** [libretro/RetroArch#2346]
I opened this bug already with [InputStation](https://github.com/petrockblog/InputStation), however RetroArch seems to suffer from the same problem.  If I try to "Save Input AutoConfig" for this controller, I receive an "Error saving AutoConfig" message.

From the [issue](https://github.com/petrockblog/InputStation/issues/3) I opened for InputStation:

Recently purchased a [Logitech Cordless Precision](http://support.logitech.com/product/cordless-precision-controller-for-playstation3) (a controller they never should have stopped making) for my Retropie. After a bit of fumbling around, I realized why my controller wasn't being picked up by Retroarch: Logitech put a "/" into the controller name.

The controller labels itself as "PS3/USBCordlessGamepad". When InputStation tries to move and rename the config file to "/opt/retropie/configs/all/retroarch-joypads/", it interprets that "/" as another directory and fails to move to the non-existent folder "PS3".

Although rare, I'm sure there could be other cases out there of controllers with special characters which would mess with this naming method. My suggestion would be to search the name string for special characters first and replace them with another character like "_" before the actual move.

**Comment by RobLoach** [comment]
I could be wrong, but I think that it replaces the special characters now.

**Comment by orbea** [comment]
Yes, this is fixed.
```
input_driver = "udev"
input_device = "raphnet.net GC/N64 to USB, v2.9"
input_vendor_id = "10395"
input_product_id = "12"
```
Note I can't add this gamepad to the autoconfig repo because the vid/pid numbers match for both the GC and N64 controllers, but the buttons do not match...
