### ISSUE TITLE
Try to preserve playlists core assignations for playlists that doesn exists

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2352]
I start with this settings, and 0 LPL in my playlists dir

    playlist_names = "Sega - SG-1000.lpl;Nintendo - Game Boy Advance.lpl;"
    playlist_cores = "/usr/lib/libretro/genesis_plus_gx_libretro.so;/usr/lib/libretro/vbam_libretro.so;"

I scan some GBA roms and restart RA, the settings are not lost:

    playlist_names = "Sega - SG-1000.lpl;Nintendo - Game Boy Advance.lpl;"
    playlist_cores = "/usr/lib/libretro/genesis_plus_gx_libretro.so;/usr/lib/libretro/vbam_libretro.so;"

I visit the Settings->Playlist, and quit RA. My settings become:

    playlist_names = "Nintendo - Game Boy Advance.lpl;Nintendo - Game Boy.lpl;"
    playlist_cores = "/usr/lib/libretro/vbam_libretro.so;DETECT;"

A value is lost

**Comment by fr500** [comment]
I think the playlist stuff could use a few enhancements, something like this could work:
- Press "Y" on the playlist name to select a default (then loop accross the playlist entries to set the core)
- Press "Y" on a playlist entry to change the core, even better, press Y to show a contextual menu to change core, delete entry
- Fix playlists on GLUI/RGUI, the playlist order is reversed or somethig, on XMB it's working fine

**Comment by Kivutar** [comment]
The playlists have settings now, so hopefully using Y will not be needed.

**Comment by twinaphex** [comment]
This can be closed now I think.
