### ISSUE TITLE
alias# = "" in a cgp results in a segfault on Linux

### ISSUE THREAD

**Issue by BPaden** [libretro/RetroArch#2353]
See http://libretro.com/forums/showthread.php?t=3998 for the shader pack. Note that the cgp's mix Windows and Linux filesystem seperaters (an issue I believe the author is working on) so for testing on Linux you'll need to do a search and replace %s:\:/:g

This is on Linux 4.2.5 with radeonsi, Mesa 11.0.4 (with OpenGL 4.1), and nvidia-cg-toolkit 3.1

```
(gdb) run
Starting program: /usr/bin/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe4575700 (LWP 24754)]
[New Thread 0x7fffdbb56700 (LWP 24755)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe4575700 (LWP 24754)]
0x00007ffff395adf0 in ?? () from /usr/lib/libCg.so
(gdb) bt
#0  0x00007ffff395adf0 in ?? () from /usr/lib/libCg.so
#1  0x00007ffff394f006 in ?? () from /usr/lib/libCg.so
#2  0x00007ffff38ec817 in ?? () from /usr/lib/libCg.so
#3  0x00007ffff38f3d57 in ?? () from /usr/lib/libCg.so
#4  0x00007ffff38f3f22 in ?? () from /usr/lib/libCg.so
#5  0x00007ffff38bc427 in cgCreateProgramFromFile () from /usr/lib/libCg.so
#6  0x000000000050c3ba in load_program (cg=cg@entry=0x7fffdc1f7fb0, idx=idx@entry=1, 
    prog=0x7fffdc2c28c0 "/data/roms/shaders/Analog Shader Pack/VINTAGE TV/ntsc/shaders/ntsc-pass1-composite-2phase.cg", path_is_file=path_is_file@entry=true)
    at gfx/drivers_shader/shader_gl_cg.c:480
#7  0x000000000050c9c6 in load_shader (i=0, cg=0x7fffdc1f7fb0) at gfx/drivers_shader/shader_gl_cg.c:619
#8  load_preset (path=<optimized out>, cg=0x7fffdc1f7fb0) at gfx/drivers_shader/shader_gl_cg.c:676
#9  gl_cg_init (data=<optimized out>, path=<optimized out>) at gfx/drivers_shader/shader_gl_cg.c:937
#10 0x00000000004f9612 in gl_shader_init (gl=0x7fffdc0008c0) at gfx/drivers/gl.c:278
#11 gl_init (video=0x8c1060, input=0x7e8b88 <g_driver+40>, input_data=0x7e8c08 <g_driver+168>) at gfx/drivers/gl.c:2535
#12 0x00000000004e7dbb in thread_handle_packet (incoming=0x7fffe4572d20, thr=0x8c1040) at gfx/video_thread_wrapper.c:138
#13 thread_loop (data=0x8c1040) at gfx/video_thread_wrapper.c:382
#14 0x00000000004e523f in thread_wrap (data_=0x8664a0) at libretro-common/rthreads/rthreads.c:90
#15 0x00007ffff65254a4 in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007ffff0b2013d in clone () from /usr/lib/libc.so.6
```

**Comment by hizzlekizzle** [comment]
Looks like it's choking on the 'alias' lines. If you remove them, it stops segfaulting but the colors are messed up. Not sure why.

**Comment by BPaden** [comment]
Obviously glitched, or just different? The shaders do effect the color, so to see if there is an issue I'll have to check the Windows version as well (which I'll do when I can) and see if there is any difference. AFAICT, though, the shaders work as indented if you remove the alias lines.

**Comment by hizzlekizzle** [comment]
They're super-glitched on my end. As long as it works for you, though, case closed.

**Comment by BPaden** [comment]
Well I wouldn't say that. If there's an issue, it should definitely be brought to the devs attention. That doesn't sound like a retroarch problem, though — not that I know exactly what retroarch is doing as far as graphics are concerned. Could be a driver thing.

For the sake of the retroarch folks' sanity, I'll keep this issue focused on the alias thing, since that seems to be what caused the issue I reported on.

**Comment by orbea** [comment]
I think this is an upstream nvidia issue, but they deprecated cg many years ago so I suppose this will never be fixed (If its still an issue?). Given that I'm going to close this.
