### ISSUE TITLE
[Feature Request] Apple TV 4 Support

### ISSUE THREAD

**Issue by me4502** [libretro/RetroArch#2359]
Hi,

Support for the Apple TV 4 would be great, although it would require the user to compile it themselves with XCode.

**Comment by kaikai1234** [comment]
+1 hopefully it wont be very hard to port as  Apple TV 4 seems to be based on ios9, also sideloading with xcode is now free for everyone and is very easy to do.

**Comment by twinaphex** [comment]
Kivutar will have to send the Apple TV 4 devkit he was sent to me, currently he lives in Vietnam and it was left in his apartment in France. So his brother likely will have to send it over.

Last time I heard shipping was going to cost 60 Euros. Quite expensive, I guess I will just have to take that on the chin.

**Comment by kaikai1234** [comment]
thanks for your hard work, if you guys open up donations, I'm will be happy to donate and I'm sure others will also.

**Comment by me4502** [comment]
I'd be willing to donate as well, also if you need any help, I can assist with development once my USB C cable arrives.

**Comment by fuzhuo** [comment]
Any update for this case. jasarien/Provenance may as a replacement on tvOS. But still hope for RetroArch_tvOS.
I tried port, but the dependency is really very hard to solve..

**Comment by twinaphex** [comment]
No, there is no update, unless you are going to pay the 50 euros its going to take for sending the package out of your own pocket.

Also, stop mentioning Provenance. I dont care about it and no amount of 'comparing' to it is going to do anything.

**Comment by Platypus2** [comment]
"No, there is no update, unless you are going to pay the 60 euros its going to take for sending the package out of your own pocket."

Is that still a possibility? Is there some way to donate/pay it? Would you be willing to attempt creating a port if you had one?

**Comment by twinaphex** [comment]
I think @kivutar was going to send it over now, so I'm waiting for that.

**Comment by Platypus2** [comment]
Great :)

But if you do need funds to get it shipped, happy to help out!

**Comment by zzyyfff** [comment]
also happy to donate some. :blush:

**Comment by Mkaay83** [comment]
Any updates yet?! 😊

**Comment by appletv4** [comment]
is the dream dead ?

**Comment by Mkaay83** [comment]
Hope not!! 😓

**Comment by Kivutar** [comment]
I sent the apple TV 4 to @twinaphex
He should receive it tomorrow or monday.

**Comment by Mkaay83** [comment]
Nice one!!! Thank you very much. I appreciate all of you coders out there making this happen!! U'r the best!!!

**Comment by RobLoach** [comment]
You guys are so cool.

**Comment by twinaphex** [comment]
Yes, I did receive it today.

**Comment by Kivutar** [comment]
Ah good :)

**Comment by appletv4** [comment]
On the Apple TV  4 you can only use MFI. Controllers 
Without a jailbreak is that going to be the only option for retroarch on TVOS ?

**Comment by twinaphex** [comment]
It will probably be comparable when all is said and done to what you can do with regards to controller support with Provenance.

**Comment by appletv4** [comment]
@twinaphex with the news today about the next update to TVOS having Bluetooth  keyboard support 
Does this mean non MFI controllers will work ? Like 8bitdo controllers

**Comment by twinaphex** [comment]
I'll look into that soon.

I'm about to release RetroArch 1.3 either today or tomorrow for iOS and the other platforms. After I release it, I will begin porting to tvOS. We will see how soon we will have something to release.

**Comment by Mkaay83** [comment]
👍👍👍👍

**Comment by appletv4** [comment]
@twinaphex @Kivutar any progress update on the Apple TV ?

**Comment by fr500** [comment]
things are ready when they are ready, please don't be pushy about this.

**Comment by twinaphex** [comment]
going to just close this, it serves no purpose anyway and you will see for yourself when the tvOS port starts to materialize.
