### ISSUE TITLE
[Feature Request] core unique save folders?

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#2361]
the save folder should really be core specific so have the user choose a root save folder and put all the saves inside a folder that has the name of the core
example might be
```/foo/bar/mGBA/Donkey Kong Country (USA).srm```
and
```/foo/bar/snes9x/Donkey Kong Country (USA).srm```
I thought of this because both systems have the same game name

**Comment by fr500** [comment]
It's already implemented,  check under settings/ saving
