### ISSUE TITLE
auto overrides enable "True" -> immediate crash on iOS

### ISSUE THREAD

**Issue by ajmi982** [libretro/RetroArch#2379]
when enabling Auto Overrides Enable (whether a core is loaded or not) then reloading RA, RA will crash immediately.

Change the value back to FALSE in Filza, RA will load like normal.

**Comment by twinaphex** [comment]
Does this still happen with the most recent nightly or source build?

**Comment by ajmi982** [comment]
Yes. Immediate crash

**Comment by fr500** [comment]
just to be clear, you're just enabling the setting right? you don't have actual overrides

**Comment by fr500** [comment]
Ok I think I might have found the culprit, pushing a fix

**Comment by ajmi982** [comment]
Enabling the setting to true. Crash. Have to change back to false in configuration file manually.

**Comment by fr500** [comment]
thanks I think it may be fixed on the next build
