### ISSUE TITLE
Directory Scanning is significantly slower than 1.2.2 and lags the interface.

### ISSUE THREAD

**Issue by Nerdy314159265** [libretro/RetroArch#2381]
In the latest test builds scanning a rom directory happens at around 1/5th to 1/10th the speed of scanning in 1.2.2. Also it seems to cause the interface to lag and framerate to drop. By default it starts up running at 120 fps but as soon as I start scanning it drops to around 60 and gets very laggy.

System Info:

Build was made on November 11, 2015
Windows 10 Professional 64bit

**Comment by Kivutar** [comment]
I confirm. Looks like something is broken in the data runloop.

**Comment by twinaphex** [comment]
Can you check the most recent source? @heuripedes has been pushing some patches that should help increase the performance of scanning.

**Comment by Nerdy314159265** [comment]
I've downloaded the latest nightly from the buildbot and tested it. Scanning is still slow and it drops my fps to sub-60 (and I run at 120fps).

**Comment by twinaphex** [comment]
Yeah this is the Windows build, where memmap support is currently not enabled. Although that might not be the only issue.

**Comment by Nerdy314159265** [comment]
When I first discovered this issue I tried to test the rest of the builds that were available at that time. I wasn't (and am still not) certain on how the older buildbot builds work. What I did was took the oldest build (10/10) and added the redist to it. Doing that it didn't have the framedrops. Then I went through every build after that and applied them like a patch the previous build. (I figured that the reason there were so few files was because they were meant to overwrite the older versions). When I built up to the latest (10/29), it still had no framedrops.

Hopefully, that's enough information to hunt down the source of the framedrops.

Also during this testing I realized something. The builds without the framedrops would scan at about 1/5th the speed of 1.2.2, but the ones where the framerate was cut in half scanned at 1/10th the speed. I just wanted to point that out because I thought it was somewhat odd that it seems the scan rate is tied to the framerate.

**Comment by Kivutar** [comment]
Is the scanning linked to the "threaded data runloop" setting?

**Comment by Nerdy314159265** [comment]
@Kivutar I couldn't tell if that comment was directed at @twinaphex or me but I can say that disabling the "threaded data runloop" setting seemed to have no effect.

**Comment by Kivutar** [comment]
Found this:

 * start scanning a big directory, let say all SNES roms
 * launch a NES rom
 * hit space

Scanning speed unlocked.

**Comment by Nerdy314159265** [comment]
@Kivutar I'd love to confirm that way around the bug but I've been having trouble with an error that is preventing scanning recently and that I just posted about. As soon as the error disappears as randomly as it came I'll work to see if that also fixes it for me.

While I could test I found that attempting to enable threaded video instantly crashes the program for me. Also I had one scan that without having any of the fixes enabled didn't drop the framerate; that run is a mystery though and I can't tell what caused it to perform better.

**Comment by Kivutar** [comment]
Now the scanning is significantly faster.

**Comment by Nerdy314159265** [comment]
@Kivutar That seems to be confirmed here. I just loaded up the latest nightly and it scanned without lagging the interface and seemed much faster. However, when compared to 1.2.2 it's still much slower. I can start a scan of a directory in the latest nightly, let it scan for awhile and then start 1.2.2; 1.2.2 will then catch up and pass the latest nightly in scanning.

**Comment by twinaphex** [comment]
Test it again today with the latest sources.

**Comment by Nerdy314159265** [comment]
@twinaphex Testing today didn't seem to have any changes to my previous test. There was no UI lag and the scanning speed seems improved, however, it's still not as fast as 1.2.2 scans for me.

**Comment by Kivutar** [comment]
The new threading code is clearly not as fast as the original one. But it causes no segfaults.

**Comment by twinaphex** [comment]
Going to depromote this from being a bug.

**Comment by Kivutar** [comment]
Launching a game and using space doesn't improve the speed anymore. So I guess the threaded data runloop is really fixed.
