### ISSUE TITLE
Retroarch does not show Rom files, does not have option to 'select file and detect core' after upgrading to v1.30

### ISSUE THREAD

**Issue by silvercomet** [libretro/RetroArch#2382]
I successfully ran Retroarch 1.2.2 on my ip 6 without any issue. When I downloaded the newest ver 1.3 from the source, there was an extra folder called Retroarch_iOS besides the current Retroarch. I built it successfully on my ipad mini yet after everything is done correctly, there is no option to Select file and detect core or Select file from Downloads from the Load Content from the menu.
![file nov 11 10 44 48 pm](https://cloud.githubusercontent.com/assets/6569263/11095158/35922500-88c6-11e5-91e2-d21eccb37445.png)
Please see the picture. Will there be a fix for this?

Many thanks

**Comment by silvercomet** [comment]
So when I go to Select file and navigate to the ROMs folder, it shows no items. I can load the core without any problem since I codesigned it

**Comment by silvercomet** [comment]
P.S. Im running ios 9.1 on both devices and chose the retroarch on the top left of xcode7, not the retroarch ios 9

**Comment by fr500** [comment]
you're missing the info files

**Comment by silvercomet** [comment]
Do you mean I am missing the Core Info Files? I already copied all the info files I have from my iphone to ipad so everything is exactly the same on my iphone which is currently running fine. However, I will update everything again using the Online Updater to see if it fixes. Lately the download speed from the server is much slower than 4 days ago so that's why I just simply copied the files from my Phone instead of downloading from the direct server

**Comment by silvercomet** [comment]
@fr500 : I might just give up on getting retroarch on the ipad. I tried the update core info file multiple times yet the download hang at 76% for 15 min and would not go through. Updating other components also took really long. A quick check on my iphone 6 only takes 3 sec to show download complete. I dont know if it's actually the ipad mini system is not fully compatible with retroarch or not. 

My whole experience with getting retroarch on the ipad mini is 100% opposite of the smooth, easy one with my iphone 6, following the exact way that Zero2029 has instructed for compiling on ios 9 using xcode7

**Comment by twinaphex** [comment]
Then give up.

This is not a user-oriented forum. If you are not a developer, stay away from here.

**Comment by fr500** [comment]
@silvercomet I don't have downloads failing at all, and since you're building for yourself we can't tell what you're doing wrong. For starters you stated you're not building the iOS9 variant, I don't see why you would do this, seems rather silly.

Anyway, iOS nightlies just re-started, they need a lot of work and we know, it should be considered an alpha on that platform.

And yeah as @twinaphex said, this isn't a forum, please use the forum for this.

**Comment by silvercomet** [comment]
Thank you @fr500 & @twinaphex, I will be mindful next time and use the forum instead, I am sorry guys, I just newly joined in the github so I just simply thought that if there is a bug, I could post it on here. My apology guys!

**Comment by twinaphex** [comment]
Are you on a non-jailbroken iPad/phone? Otherwise, you should use the latest Cydia builds instead of trying to compile it yourself.

**Comment by silvercomet** [comment]
Unfortunately I am on both non-jailbroken ipad and iphone but I don't use my ipad much. I will attempt to jailbreak it with SemiJB and play around with it to get the Cydia build, if it could do since I can no longer downgrade to 9.0 when Apple has stopped signing it . Thank you @twinaphex

**Comment by twinaphex** [comment]
I think right now the development process is made not to be really easy for people compiling it manually for deployment to their non-jailbroken phones/tablets. I could improve that later on but my first priority is getting the iOS port in general out of the alpha stage. Development will come fast though during this crucial holiday period so hang in there, the intention is there to get most of it covered soon.

**Comment by silvercomet** [comment]
Awesome, greate to here that @twinaphex ! 

I know that you are working so hard to get this implemented so everyone could enjoy it and that is just awesome. At least now I could still enjoy it on my non-jailbroken ip6, not sure why it went so smooth on it, maybe my luck? I did exactly what Zero2029 shared on the forum just almost 3 weeks ago.

Anyway, I look forward to that Twinaphex and thank you so much for such hard and great work putting in this to perfect it everyday!
