### ISSUE TITLE
Fullscreen uncentered with integer scaling enabled

### ISSUE THREAD

**Issue by Bracket-** [libretro/RetroArch#2386]
Since 2015-11-10 RetroArch nightly, enabling integer scaling along with fullscreen causes RetroArch to render near the bottom left portion of screen instead of centering the image.

OS: Windows 10
RetroArch: 2015-11-12 x86_64
Video driver: gl
Cores tested: Mednafen PSX

**Comment by knight2087** [comment]
hello,
same problem here but on a PI2. Updated yesterday.
Regards

**Comment by twinaphex** [comment]
Report when this got broken.

The exact commit, not the date from the nightly version.

**Comment by Bracket-** [comment]
I don't currently have a build environment set up for RetroArch. I'll attempt to bisect when I have time.

**Comment by Monroe88** [comment]
http://pastie.org/10555882#23

`# first bad commit: [36d5cc890b37a3f351877bb6b83851e4c5af57dd] (GL) Cleanups`

Commit 36d5cc890b37a3f351877bb6b83851e4c5af57dd is what caused the issue. The immediate parent commit does not have the off centered viewport when using integer scaling with the gl driver. Reverting the bad commit fixed the issue for me.

**Comment by twinaphex** [comment]
OK, reverted it.

**Comment by Bracket-** [comment]
Confirmed fixed. Thanks for bisecting
