### ISSUE TITLE
[ios9] 1.3.0 UI buttons show as black

### ISSUE THREAD

**Issue by fuzhuo** [libretro/RetroArch#2387]
All the icons are show as black, did I miss copy some resource when I build it?
Before build, I git clone retroarch-assets to media/assests.
![img_2731](https://cloud.githubusercontent.com/assets/4716508/11138374/43a9b8a6-89fc-11e5-86e7-e47ffbe5a33b.PNG)

**Comment by fr500** [comment]
Well that is exactly what happens when assets are missing

**Comment by fuzhuo** [comment]
Seems there is no guide to build for iOS. Where can I get the correct assets?
What I did is below.
cd media
git clone https://github.com/libretro/retroarch-assets.git assets

**Comment by fr500** [comment]
just use the builtin updater to install the assets

**Comment by fuzhuo** [comment]
@fr500 Thanks, it works.
