### ISSUE TITLE
[Linux] missing retroarch-joyconfig

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#2388]
Hello,

I just compiled retroarch and I can not find retroarch-joyconfig.
Is it normal? There is no trace of the compile instructions in the makefile file.

Thank you for your help.

LGDN

**Comment by fr500** [comment]
it's deprecated and removed

**Comment by andematt** [comment]
I left a comment on b199f53f too but the mappings don't come out right from the ES gui. People were using joyconfig to get the mapping correct for retroarch. What should we be using as an alternate mapping utility?

**Comment by fr500** [comment]
just retroarch.
