### ISSUE TITLE
[Feature request] Automatic delay frames for netplay

### ISSUE THREAD

**Issue by thatcadguy** [libretro/RetroArch#2389]
It'd be nice if at the beginning of the start of a netplay game the client and server pinged each other, allowing delay frames to be calculated and set accordingly.

**Comment by twinaphex** [comment]
@ctult Forwarding this to you, I'll let you be the judge as to whether you think this feature is interesting enough to implement or not.

**Comment by ctult** [comment]
This should be easy as soon as I get around to implementing the ping command.

**Comment by thatcadguy** [comment]
Might be better as a separate ticket, but in general, anything that can be done/thought of to make netplay a friendlier experience would be great. Netplay is a headache when trying to play across devices, or basically anything outside of a local network for almost all emulators.

**Comment by ctult** [comment]
The RetroArch netplay code hasn't been touched for years, so it's *very* featureless compared to every other section of RetroArch. As the unofficial new netplay programmer, I completely agree with that request.
