### ISSUE TITLE
Steam controller

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#2390]
Hello,

could you add Steam controller support for Retroarch?

Thank you for your help.

LGDN

**Comment by fr500** [comment]
RetroArch already supports dinput/xinput, it should just work granted you can configure it.
I would add a profile if I had one but I don't.

**Comment by legluondunet** [comment]
I have one and I could make a profile, but I don't know how.

**Comment by fr500** [comment]
http://libretro.com/forums/showthread.php?t=3550

**Comment by fr500** [comment]
Not really an issue, it's just up to a user to make a profile
