### ISSUE TITLE
[iOS] Crash when loading a rom on either Snes9X or Snes9X Next

### ISSUE THREAD

**Issue by sticksstones** [libretro/RetroArch#2405]
<img width="830" alt="screen shot 2015-11-16 at 1 31 27 am" src="https://cloud.githubusercontent.com/assets/906668/11178617/bd8809d6-8c02-11e5-8659-d99b5f5177bd.png">

**Comment by twinaphex** [comment]
@leiradel - seems related to async_job_processor there. The user is not using any achievements and he is not logged in, but the async job thread is still being spawned regardless.

Also, I don't see async_job_free being called anywhere. I think that constitutes as a leak. We should always have proper bookkeeping where we free something when it's no longer needed.

**Comment by sticksstones** [comment]
False alarm. Bad code on my end.
