### ISSUE TITLE
XMB Freezes if History List Is Disabled

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#2409]
When the history list is disabled, if you move over to the history tab in XMB it blinks once and you can no longer navigate the interface. I'm guessing that tab shouldn't show up when history is disabled.

**Comment by CanadianJeff** [comment]
I can reproduce +1

**Comment by Kivutar** [comment]
Reported here too http://libretro.com/forums/showthread.php?t=4559

**Comment by Awakened0** [comment]
I think the freeze has been fixed for a bit, but this was fixed nicely with a commit that shows "No history available." when selecting that tab with history disabled now.
