### ISSUE TITLE
Salamander broken for Wii

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#2411]
@ToadKing: The most recent version of Salamander for the Wii seems to be broken. We have to revert to an older version of boot.dol to get things back to work again.

Could you please take a look at this when you have time?

BTW, it would greatly help me if I could debug these issues myself with the USB Gecko since you seem to be having less and less time available as time goes on. Would it be possible to send this over to me so that I can at least support this platform better? Having to debug this stuff with printf logging is just a total disaster as you are well aware.

**Comment by ToadKing** [comment]
In what way is it broken? A quick test shows it working for me.

Send me an email with your address and I'll ship out my USB Gecko.

**Comment by twinaphex** [comment]
Thanks a lot.

Anyway, I think Salamander might be broken, or at least something related to the boot process. When you start up RA with no old config files, it just shows like that and stays a black screen. It does not boot up RA.

**Comment by ToadKing** [comment]
I don't think salamander is the root cause. I've gotten the black screen, but I believe that the emulator is running underneath it. If you press up once then A, the emulator will exit as if you pressed the quit menu item.

When did this start happening? Was something done to the Wii video code recently?

**Comment by ToadKing** [comment]
Yeah, launching the "broken" salamander then exiting that way creates a full retroarch.cfg file. So salamander is working, it's the core that is having video issues. My guess is old versions of salamander set up video correctly and the broken cores happen to work since they piggy-back off that initialization.

**Comment by twinaphex** [comment]
It's hard to pinpoint exactly when it started happening. I have been bisecting locally here and things were still fine around August 30 (https://github.com/libretro/RetroArch/commit/f95049e99c5b0e3c0a9e27cc325). I'm now going to try and see if I can get it narrowed down a bit more.

There have been some people who made some contributions to the Wii video code to do with the VI modes, like SuperSonic. Other than that just basic changes I think.

**Comment by twinaphex** [comment]
ToadKing - should we change this:

https://github.com/libretro/RetroArch/blob/f95049e99c5b0e3c0a9e27cc32505a3966f51bf7/frontend/drivers/platform_gx.c#L262

into #if defined(IS_SALAMANDER) based on this then? You think that might solve the broken video initialization?

**Comment by ToadKing** [comment]
No, that is debug code so the VI subsystem can get initialized without having to init the entire gx driver. So you can see terminal text in salamander. It might not work anymore though.

I'm looking at stuff that might be the cause.

**Comment by ToadKing** [comment]
37b4735c4cb963796b253152803cd0085021bbf5 is the commit that broke stuff.

A lot of those variables are things that should persist across video driver inits. (Like the GX FIFO and the display lists for one). They shouldn't be in the gx_video struct.

**Comment by twinaphex** [comment]
My bad.

Let me revert that and see if it fixes everything.

**Comment by twinaphex** [comment]
I think we can close this now. Thanks again @ToadKing.
