### ISSUE TITLE
Retroarch crash at load some Roms (iOS)

### ISSUE THREAD

**Issue by brujo5** [libretro/RetroArch#2415]
This happend in all build starting from 2015/11/15 up

So an commit from 11/15 cause the crash

The crash is caused for this cores
Pcsx
Mupen64
Desmume
Mame 0.78/2003
All FBA cores
Etc............

Of curse tested in iOS 9 jalibroken.

**Comment by fr500** [comment]
Try this, go to settings, configuration, and disable "use per-game core options...", and try again.
I want to know if this new function is causing the problems

**Comment by brujo5** [comment]
fixed in the latest nightly, thx

**Comment by brujo5** [comment]
@twinaphex 

Awesome, massive perfomanse/fps up in the latest nightly.

all cores run smooth now, thx
