### ISSUE TITLE
[Android] Some cores don't load at all and roms don't load anymore despite doing it in v1.0.0.2

### ISSUE THREAD

**Issue by inafking** [libretro/RetroArch#2417]
Hi, I've downloaded retroarch v1.2.2 for Android and I've downloaded some cores though the Core Updater: 
- Arcade (MAME 2003)
- mame2003_libretro_android.so
- NES / Famicom (QuickNES)
- bsnes performance
- Nintendo 64 (Mupen64Plus)

1) With both MAME 2003 cores, I've tried loading the core with Load Core option but it didn't work. I've also tried to load contents (roms) that were previously working with retroarch v1.0.0.2 (airwolf.zip and umk3.zip) and when loading them with the MAME 2003 core retroarch just crashes and I'm back again at the first menu (the one that says "Load Retroarch" and "Quit Retroarch")

2)  With the QuickNES core and bsnes performance everything goes smooth. The core is loaded correctly with Load Core and the rom starts flawlessly when choosing load content (Adventure Island III). bsnes core takes longer to load, but does the work.

3) With Mupen64Plus I can load the core correctly, but when I try to load a rom with "Load content" retroarch crashes in the same fashion as the mame 2003 cores.

Could this be caused because of a lack of memory? When I try to load the ROM retroarch gets stuck for a while and then it crashes.

I hope you can enlighten me to find out at least what is the problem.
Thanks a lot for all your effort to make this project possible

Greets!

**Comment by inafking** [comment]
I've tried with the latest build too (the build of this date). The GUI is different (white IIRC) but the problem persists with the exact results.

I hope you can help me.
Greets!

**Comment by fr500** [comment]
- MAME 2003: the toolchain might not be exporting symbols for something older than lollypop, we've had that for a bit, if you select the core and it says "No Core" that's the case

- Mupen, try what I said about MAME.

**Comment by duskgao** [comment]
NES / Famicom (QuickNES)
bsnes performance
Nintendo 64 (Mupen64Plus)

working on lastest nightly build

older MAME/MESS/UME (2003/2014?) cores only working on android 5.0 above

**Comment by Quickgold74** [comment]
"the toolchain might not be exporting symbols for something older than lollypop"..can you recompile the cores with and older toolchain for older android builds? maybe I asking too much with this, thanks for your work!

**Comment by inafking** [comment]
Hi, I've downloaded the source, which file should I modify to tell the compiler I'm using an older android version? the core Makefile? The global Makefile? libretro-build-android-armeabi_v7a.sh? some obscure command line argument when compiling?

I've Android 4.2.2 (Jelly Bean) on my android console.
I hope you can shed me some light
Greets.

**Comment by fr500** [comment]
It depends on the core, some cores are build with a jni makefile, others with plain make, what core do you want to build?

**Comment by inafking** [comment]
I want to build the mame2003 core along with the retroarch application. Please tell me where should I put the lines to compile it for Android 4.2.2 or less

Do I need the android SDK and NDK to execute the libretro-build-android-armeabi_v7a.sh file?

Thanks in advance!
Greets!

**Comment by fr500** [comment]
these issues should be opened on the respective issue trackers
