### ISSUE TITLE
Input problems with GPD XD device

### ISSUE THREAD

**Issue by enodr** [libretro/RetroArch#2420]
The new version 1.2.2 has introduced some bugs with the gui and input devices. The issues below apply to the GPD XD device (android portable gaming device with built-in gamepad and physical android buttons).

The GPD XD can have its controller set with two different modes: Playstation 3 or Xbox 360 (default). 

Note: test were done with the current Google Play version and current nightly (nov 17th 2015).

1/ When gamepad is set as Xbox 360, retroarch does detect an Xbox controller but it is not configured and cannot be used at all. The gamepad overlay is displayed but is totally unusable (one press up will scroll the menu randomly for several seconds, button press are not recorded, etc)

2/ When configured as Playstation 3, the gamepad is recognized in port 1. When a game is launched the gamepad overlay is displayed even though the gamepad is used. The overlay should be disabled by default if a gamepad is found.

3/ The android physical buttons are recognized as rk29-keypad in port 0 but are not working. Back button does no return to retroarch menu. Trying to remap "menu toggle" does not recognize this button (option "back as menu toggle enable" is enabled)

4/ In general, with the overlay touch screen input is very erratic. Multiple input / retries on the touch screen are needed in order for the input to be recorded

Thanks a lot for the work and time spent on this great tool. I feel current version was not ready to go mainstream on the store, but I hope it will get better quickly.

Side question: is there an option to go back to the older GUI?

**Comment by fr500** [comment]
Don't use 1.2.2, use nightlies, we do not support that anymore and many issues have been fixed already.

1. It needs an autoconf profile, we do not have one of those, follow this guide to make one
http://libretro.com/forums/showthread.php?t=3550
2. Use nightlies
3. Each device is hooked up to a RetroArch port, it's not really our fault that manufacturers make controllers that are separate hid devices acting as one, it would need a device specific hack to add that behavior.
4. Use nightlies

No

**Comment by fr500** [comment]
2. the overlay showing up sometimes when switching activities

3. needs a per-device hack I can look at it since I added one for the shield. Other emus don't support up to 16 players and don't map one device per port as we do

5. no idea of this it certainly doesn't happen on my gear

**Comment by enodr** [comment]
Ok I am trying to make an autoconf for the Xbox controller but the touchscreen GUI isn't registering "click" events. I scan scroll up and down but cannot go to the settings tab nor can enter any menu.

**Comment by fr500** [comment]
is the overlay showing, overlays and touch are mutually exclusive

**Comment by enodr** [comment]
No the overlay is not showing. As I wrote I can scroll up and down with the touchscreen but "click" does not work.

I have made some more tests and the two showstoppers bug are:
- the touchscreen input "click" problem 
- the back button not working (could that be because it's recognized as "rk29-keypad in port 1" and thus is de-registered as the android back button?)

Of course there are workarounds (use PS3 controller driver, map l3+r3 as back button, disable overlays in configuration) but I wish I could help you fix these bugs to improve retroarch.

**Comment by fr500** [comment]
* the click event... no idea, what menu driver are you using? make sure to use GLUI
* no, it's because of what I said before, your device has 2 controllers and RA always binds controllers to a port, it's probably binding that rk29 thing to player two and it needs a device specific hack, I think I can try to fix it later.

**Comment by enodr** [comment]
Yes I am using GLUI of course.

Tell me if I can provide any usefull debug info for these 2 bugs.

**Comment by fr500** [comment]
Ok I need this:
- The device names printed when you press a button in either mode (exact device name)
- The device names printed when you hit other buttons (back, volume, etc)

**Comment by enodr** [comment]
Here are the exact names:

For the back button:
rk29-keypad

For the gamepad (in playstation or xbox mode):
PlayStation3
XBOX (726/35301)

**Comment by legione** [comment]
Hello, I have the same device and the same problem, but also the menu button doesn't work. Is it by design? With the old version, while playing a game, pushing the menu button called the menu of retroarch with the current core options.

When I try to call the menu (long press on the multitask button) it says:
`Virtual (0/0) not configured`

I did a little more troubleshooting also for the back button that proves that @fr500 is right:
  1. if I load retroarch and push any gamepad related button (D-pad, A,B etc) it prints:
   `playstation3 configured in port #0`
    then if I press the volume buttons or the back button it prints:
`rk29-keypad configured in port #1`
  2. if I load retroarch and the first button I push is volume or back, it prints: `rk29-keypad configured in port #0` and then when I press the gamepad buttons, it prints `playstation3 configured in port #1` and the those don't work (can't go up or down or confirm etc).
In __both cases__ the back button doesn't work

I have the 2015-12-03 nightly, from the 2015-12-04 and on whichever button I push retroarch crashes.

**Comment by fr500** [comment]
Can either of you come into #retroarch in freenode?

**Comment by legione** [comment]
I'm on freenode right now.

Yes, if I press first a gamepad button I can navigate the GUI. I cannot navigate only if I press first the rk29-keypad. Sorry, but I don't know  what you mean with GameMID.

I don't know if this could be helpful (probably you changed everthing), but with the old retroarch 1.0.0.2-r34 everything works fine.

**Comment by enodr** [comment]
Tested current nigthly build (2015-12-26) and GPD XD support is almost working good. Still one bug remaining. Steps to reproduce:
- Load a core and load content.
- Start emulation
- While in emulation hit the android "back button" to enter retroarch menu
- Choose "resume" in quick menu
-> gamepad input does not work anymore unless you go back for example to the android home menu or any other app and then swith back to retroarch.

**Comment by fr500** [comment]
does some text print when you press the back button?

**Comment by enodr** [comment]
- When launching retroarch upon key press and when hitting the back button there is message "GPD XD gamepad detected in port #0".
- When going from the menu back to emulation ("resume content" option in quick menu), no message is displayed.
- When switching to android task manager then back in retroarch "GPD XD gamepad detected in port #0" is displayed again as if the gamepad was detected again. It then works again.

**Comment by fr500** [comment]
I would need a full logcat to debug this, I don't have such a device.
My aim with the hack I implemented was to combine rk29-keypad and the joystick. I didn't pay attention at all to the gpio keys

**Comment by enodr** [comment]
Yes it seems your hack is almost working perfectly. Maybe a logic bug where the input mapping is "cleared" when going back to retroarch menu and re-entering emulation instead of keeping the current setting?

I will run a logcat and post results here.

**Comment by enodr** [comment]
[gpd_xd.txt](https://github.com/libretro/RetroArch/files/72825/gpd_xd.txt)

**Comment by cpages** [comment]
I just installed retroarch from fdroid (I understand it's the nightly) and the dpad is not working, only the buttons. Is this a regression or I might be missing something?

**Comment by cpages** [comment]
It does work with ps3 mode, sorry for the noise.

**Comment by brandon-arnold** [comment]
An alternative is to hook a keyboard to the GPD XD ([needs a micro USB to USB type A female](https://www.amazon.com/gp/product/B00YOX4JU6/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1)). Then page over to the input bindings with the keyboard and set the bindings with the GPD XD set in Xbox mode. This worked for me.

**Comment by fr500** [comment]
Xbox mode should work too now I fixed that recently

**Comment by brandon-arnold** [comment]
Must be because I'm not on the nightly despite all your insistence before ;) 

I'm using the latest stable 1.3.4 from Google Play. The user 1 d-pad was certainly not mapped to Hat 0 by default.

**Comment by nokiot9** [comment]
I think I'm having this issue. My controls wig out randomly in the menus. Only a hard factory reset fixes it. I'm not understanding this fix with the autoconf tho. Is that in the RA Settings menu?

**Comment by nokiot9** [comment]
And that link at the beginning doesn't work. Or I'd just look at it
