### ISSUE TITLE
[Wii] Unusual behaviors when using 240p modes

### ISSUE THREAD

**Issue by 44100hertz** [libretro/RetroArch#2427]
I have the latest nightly on my SD card, and I load games from my flash drive or SD card. I've experienced this issue on every version that I've used in the last few months. I'm using a standard definition CRT with component cables, capable of 480i or 240p at max.

Upon loading a core, retroarch will sometimes do one of two things:

1. Condense the 240p signal into 480i
This causes the signal to occupy only the top part of the screen, and can look very buggy depending on resolution. The only way to see the game properly is to set the video mode to 480i from video settings. I cannot get it to display a 240p signal after this happens.

2. Enter a system state of color rotation and lag
Sometimes this happens after number 1. The console will run at half speed with heavy audio stutters, and blue and red colors appear to be switched. Even after exiting retroarch, the homebrew menu and even wii menu will continue to be in this state until I reboot.

After saying this, let me just mention that mednafen has a wii implementation that can display 240p modes on multiple systems perfectly. It's also open source, so perhaps a glance at their code would prevent this issue in the future.

**Comment by 44100hertz** [comment]
Okay, so the video backend of wii mednafen seems to be based on SDL. I guess that's where to look.

**Comment by twinaphex** [comment]
> After saying this, let me just mention that mednafen has a wii implementation that can display 240p modes on multiple systems perfectly. It's also open source, so perhaps a glance at their code would prevent this issue in the future.

Well I'm fine with looking at how other emulators does it. However, be warned that I am not going to accept any kind of ugly hacks like 'if NES system == do this, if PCE == do this', it will have to be generic solutions that make sense and are not bound to any kind of console system-specific shenanigans.

**Comment by 44100hertz** [comment]
I'm not asking for automatic modesetting. That's a separate issue. This isn't a feature request, it's a bug.

The part that matters is that the wii can either no longer use a mode other than 480i, or it can enter a system-wide state of rotated colors and lag. I can make a video of it if needed.

**Comment by twinaphex** [comment]
Going to close this, you will be able to test this again with the upcoming v1.3.1.
