### ISSUE TITLE
[UI Bug] in XMB mode dynamic wallpaper won't change in the NES column 

### ISSUE THREAD

**Issue by bronnel** [libretro/RetroArch#2428]
In XMB mode when you navigate to NES (Nintendo Entertainment System ) tab, the dynamic wallpaper doesn't change, I tested about 9 other cores all were showing up just fine , only on NES column it doesn't change (instead it shows the neighboring core wallpaper). I already made sure the corresponding png image is available in assets folder (Nintendo - Nintendo Entertainment System.png), and defined the path properly 
Here is what I'm talking about 
http://youtu.be/bED5SDBDfcA

**Comment by bronnel** [comment]
I just noticed this is a part of a bigger issue, I was wrong to think it was related to NES tab.
If you notice the first item in NES tab (super mario bros) have boxart, so if you delete its boxart png file or turn off (display boxart) in settings, then the wallpaper will show up, so this means there is a conflict between dynamic wallpaper and boxart.

I already reproduced this bug for Playstation tab

How to reproduce this bug
0- get in XMB mode
1- enable boxart 
2- enable dynamic wallpaper 
3- off course set the path for wallpaper and boxart
4- make sure the first item (game) in each tab (core) have a boxart and displayed properly 
5- when you navigate to that tab (core) in which the first item have a boxart, then the dynamic wallpaper will not change ( won't show up ), instead it shows the neighboring wallpaper.

**Comment by bronnel** [comment]
![image](https://cloud.githubusercontent.com/assets/15629916/11253134/c9fadce4-8e4a-11e5-980e-217699f663db.jpg)
![image](https://cloud.githubusercontent.com/assets/15629916/11253136/ca429336-8e4a-11e5-834d-37f3f7795191.jpg)
![image](https://cloud.githubusercontent.com/assets/15629916/11253137/ca4814f0-8e4a-11e5-82a6-83d9a0d1b166.jpg)

**Comment by bronnel** [comment]
This issue was available throughout all recent (oct-nov) builds

**Comment by bronnel** [comment]
I reproduced this bug multilpe times and on different platforms it's the same

**Comment by fr500** [comment]
It will be looked at eventually

**Comment by Kivutar** [comment]
It is a real bug in our msg_queue code. When we push two msg with DATA_TYPE_IMAGE at the same time, the first one will be ignored and will lead to an empty texture. We **need** to fix this.

**Comment by bronnel** [comment]
Well thank you I cannot wait  for you to fix this, you're an amazing developer

**Comment by Kivutar** [comment]
@heuripedes just fixed this bug with his recent commits.

**Comment by bronnel** [comment]
I installed the latest build the wallpaper shows up now but the boxart doesn't show

**Comment by Kivutar** [comment]
Now you have to follow this naming convention:

    boxarts/Nintendo - Game Boy/Named_Snaps/Zool - Ninja of the 'Nth' Dimension (Europe).png

You can grab image packs from there: https://screenshotpalace.wordpress.com/no-intro-screenshot-reloaded/

For now, the "Named_Snaps" string is hardcoded, but soon I will either remove it, or build a selection list with the following options: Named_Snaps, Named_Titles, Named_Boxarts.

We need to find a good source of Boxarts named after the no-intro rom names.

**Comment by bronnel** [comment]
great work , now both the wallpaper and the boxart showing up just fine. One million thanks to you

**Comment by Kivutar** [comment]
Can somebody close this issue please?
