### ISSUE TITLE
Libretro: Mednafen PSX & Beetle PSX crashes when opening 7zip & zip archives

### ISSUE THREAD

**Issue by deldiablo** [libretro/RetroArch#2437]
Error opening file No such file or directory
Requests termination

Opens fine if .cue and .bin is unzipped

**Comment by fr500** [comment]
of course, the core doesn't support them and it would require us to parse the cue to extract the related files (which would take a long time)

**Comment by twinaphex** [comment]
This issue can be closed since it is not really a bug and it is not a reasonable expectation.
