### ISSUE TITLE
Directory Scan occasionally ends with "Scanning of directory finished" immediately without scanning

### ISSUE THREAD

**Issue by Nerdy314159265** [libretro/RetroArch#2441]
I've found that occasionally scans will finish immediately when started with the message "Scanning of directory finished" and doesn't actually scan the directory (seemingly at least). This has happened on several builds lately and doesn't seem to follow a pattern of what causes it. I can have a build that was scanning just fine that I'm running tests on and on a fresh unzip of the file suddenly fail every attempt at scanning.

Running:

Windows 10 Professional 64-bit
Latest Nightly from the Buildbot

**Comment by Kivutar** [comment]
It can happen if your scan a directory that is empty, or contains just directories, or if you don't have any core that can handle the extension of the files contained in that directory.

**Comment by Nerdy314159265** [comment]
@Kivutar I'm running the scan on directories that are definitely full and not of more directories. I'm scanning folders that have zip files inside of them but no cores installed. However, I believe I've also had it fail with cores installed.

I don't know why cores would affect the scanning because I thought that was a separate portion entirely. However, I'll try scanning again and when the error creeps up, I'll check my cores and see if that resolves the issue and update here with the result.

**Comment by CanadianJeff** [comment]
can close this too looks like its working again in recent commits
