### ISSUE TITLE
RA messing up with symlinks

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2442]
RA is messing up when you have symlinks in a folder. For example, /usr/lib/libretro/ has symlinks for /usr/lib/x86_64-linux-gnu/libretro/ and RA shows the cores as folders, you can even enter it.

![screenshot - 21112015 - 20 29 17](https://cloud.githubusercontent.com/assets/5431285/11320848/b484007a-908e-11e5-9590-b9feacd0c7ee.png)

![caekmukl png](https://cloud.githubusercontent.com/assets/5431285/11320862/83488016-908f-11e5-9e30-566af794c05e.jpeg)

I have some symlinks on my ROM folder too, RA only sees relatives symlinks like ../MAME/roms_cps1, absolute ones does not appears in the browsing (maybe it's a different issue?).

**Comment by fbis251** [comment]
+1 I can also reproduce this on ubuntu 15.10 with the latest retroarch files from the testing PPA

    retroarch --version
    RetroArch: Frontend for libretro -- v1.3.0Compiler: GCC (5.2.1) 64-bitBuilt: Nov 20 2015

**Comment by sergiobenrocha2** [comment]
5a28266 broke it. Both issues are related.

**Comment by fr500** [comment]
is this still happening? please reopen if so

**Comment by sergiobenrocha2** [comment]
Yeah, this still happens for cores and my mame symlink dirs.

**Comment by Kivutar** [comment]
Maybe related, RA fails to extract zips (like core info files) in a folder that is the result of a union mount of fuse-unionfs.

**Comment by sergiobenrocha2** [comment]
@Kivutar I bissected until that commit.

**Comment by sergiobenrocha2** [comment]
6ff544b fixed it, thanks.

**Comment by Kivutar** [comment]
Sadly, this doesn't fix the problem with unionfs.

**Comment by fr500** [comment]
@kivutar, is that major? where do you use unionfs?

**Comment by orbea** [comment]
Is this still a problem with unionfs?

**Comment by LibretroAdmin** [comment]
Closing this until we get a further confirmation whether or not this still happens.
