### ISSUE TITLE
Packaging errors with retroarch.desktop under v.1.2.2 release tag

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/RetroArch#2443]
Hi, in packaging this for SteamOS-Tools, I modeled the debian/ folder set from the stable PPA. This works just fine on the master branch, but building against v1.2.2 complains about a missing desktop file. Placing the missing retroarch.desktop file into the source folder after checking out that release does not fix this, due to how the retroarch.install (I presume, I am still learning packaging everyday) not copying the desktop file to the `debian/tmp/usr/share/applications/retroarch.desktop` temporary build directory. 

See the adjusted file I have [here](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/retroarch/retroarch/retroarch.install). This allows the package to build. Also seems if I don't assign steam as the owner of /usr/lib/libretro and /usr/share/libretro, cores/assets do not install after downloading. My full build script is [here](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/retroarch/build-retroarch.sh)

Is this purely my fault? If there is a better way to correct this, please let me know. I am building with `debuild -b -uc -us`

**Comment by sergiobenrocha2** [comment]
Wait, /usr/lib/libretro and /usr/share/libretro are on the root, you know it's for the packages from the PPA, not for the Online Update right? Unless you have root access, you can't write things there, as a normal user.

If v1.2.2 has the *.desktop or not, it's pointless, just use the master or wait for the next release.

You can put the retroarch.desktop in the debian/ folder, and change the retroarch.install from just "usr/share/applications/retroarch.desktop" to "debian/retroarch.desktop  usr/share/applications/". If you put it in the root source folder and it does not work, you probably have a missing dev package in your system, probably desktop-file-utils.

**Comment by sergiobenrocha2** [comment]
Why you have this bzr-builder.manifest file? It's not from the packaging, see: http://bazaar.launchpad.net/~libretro/libretro/RetroArch-debian/files

You should close this issue, it has nothing to do with the upstream.

**Comment by ProfessorKaos64** [comment]
Yes it does work if I move in the desktop file into the source folder before packaging. If that's intentional, fine, but I just thought it was odd that one file is missing from the release tag archive. It seemed intentional, as previous release archives have this as well. I build off of stable targets when I can, not the latest git source. 

>Wait, /usr/lib/libretro and /usr/share/libretro are on the root, you know it's for the packages from the PPA, not for the Online Update right?

Ok, if that is the case, since I am new to packaging this, could you explain the online updater? Everyone I read, it downloads and installs what you ask it to, such as a new core. If it is owned by root, then what does the online updater do if not download and install core/assets etc.? 

I will remove the bzr file, it was left behind, same for all the others I am working on.

**Comment by sergiobenrocha2** [comment]
"but I just thought it was odd that one file is missing from the release tag archive"

Well, the PR for this file happened after the 1.2.2 release.

**Comment by ProfessorKaos64** [comment]
Ok, i'll then close. The other issue I have with the online updater is outside of this scope, agreed.

**Comment by sergiobenrocha2** [comment]
The Cores and Assets in the PPA are there for convenience, so the user can install them with apt-get and they can be updated automatically by the system. Also, the Online Updater is not so reliable, it has issues with big files and slow internet access, this is why there's a package for the assets yet (and I doubt the users figures that he needs to go to Online Updater --> Update Assets with the XMB gui all black without icons, this is why this package is a hard dep for RA).

When you use Online Updater and your Core folder is in the root, the cores you downloaded just go to the limbo, because RA does not have access to that folder.

**Comment by sergiobenrocha2** [comment]
I thought I was clear in the forum... http://libretro.com/forums/showthread.php?t=1556&page=4&p=24822&viewfull=1#post24822
