### ISSUE TITLE
CPU usage drastically increased since commit becf83a

### ISSUE THREAD

**Issue by vanfanel** [libretro/RetroArch#2446]
CPU usage on Raspberry Pi has dramatically increased +30% since this commit ("Reimplement sleeping").
Last good commit was 6f0425bdc3fd84b80c4cf0d5fb9787d7ac60979e

**Comment by sergiobenrocha2** [comment]
I'm having this issue too, 100% of cpu usage.

**Comment by vanfanel** [comment]
Back to normal CPU usage with the revert in 228bb54.

**Comment by twinaphex** [comment]
I think we can close this now then until further notice.
