### ISSUE TITLE
UI problem in game (iOS)

### ISSUE THREAD

**Issue by brujo5** [libretro/RetroArch#2453]
In the recent nightly the UI is not loaded in game (GL driver) 
Also when i hit the close content the emulator crash.

![image](https://cloud.githubusercontent.com/assets/4172898/11356742/f40ec4ba-921d-11e5-89ad-789ae59dfeb2.png)

**Comment by brujo5** [comment]
also noticed speed down after revert some changes that cause high CPU usage in raspberry.
I didn't noticed high CPU usage in my device.

**Comment by fr500** [comment]
the increased usage was for threaded data runloop only I think

**Comment by brujo5** [comment]
In this build have speed up in all cores

com.libretro.retroarch9_1.2.2.2015.11.23.13.28.18_iphoneos-arm.deb

After that noticed speed down.

It sounds strange but true. I made a backup of this build

**Comment by brujo5** [comment]
For example before that i experience choppy sound and slowndowns  in FBA core playing PGM games.

But in the build mencioned above, working perfect in all aspect (no choppy sound and full speed)

**Comment by brujo5** [comment]
Is the fix for task overlay and unload content crash available for iOS?

Because i update again and still have the problem mencioned before. Thx

**Comment by twinaphex** [comment]
If you have to ask, then you answered your own question. WAIT.

**Comment by brujo5** [comment]
Ok thanks
it is not my intention to bother you.

**Comment by brujo5** [comment]
ok fixed in latest update. thx

**Comment by brujo5** [comment]
@twinaphex 

https://github.com/WilliamLCobb/iNDS

This port of desmume is 40x or more faster (optimized for ARM). Its ideal for ios/android

An libretro port will be good.
