### ISSUE TITLE
[Windows / GL] very high CPU usage

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2454]
This problem has been present for a while, and it seems it only happens on NVIDIA hardware (I think 700 series in particular) although it would be good to get some more tests to confirm.

Idle CPU usage is... well VERY high with the GL driver, I tested different hW configuations and all of them showed the same patterns, then I tested one pattern in different scenarios and got some stats

GPU: Nvidia GTX 770
CPU: Intel Core i5 2500k
OS: Windows 8.1 x64

For a baseline I decided to run RGUI/D3D in Windowed and Fullscreen mode:

![rgui_idle_windowed_d3d](https://cloud.githubusercontent.com/assets/1721040/11357868/4cfde3aa-923a-11e5-9487-564aabc3bab7.png)
![rgui_idle_fullscreen_d3d](https://cloud.githubusercontent.com/assets/1721040/11357870/50154cd6-923a-11e5-9566-bbccdd4ea955.png)

CPU usage is nice and low, then I changed the driver to GL and did the same experiment:

![rgui_idle_windowed_gl](https://cloud.githubusercontent.com/assets/1721040/11357903/b74dcd88-923a-11e5-8d01-510cc53a1bc8.png)
![rgui_idle_fullscreen_gl](https://cloud.githubusercontent.com/assets/1721040/11357878/73ae6b14-923a-11e5-955e-a7429f6eeca4.png)

As you can see, CPU usage is already higher, now I switched to a GL menu driver:

![xmb_idle_windowed_gl](https://cloud.githubusercontent.com/assets/1721040/11357887/90247716-923a-11e5-985a-797e1603f55e.png)
![xmb_idle_fullscreen_gl](https://cloud.githubusercontent.com/assets/1721040/11357909/c1f5504e-923a-11e5-88a9-26adf18a6de7.png)

And lastly, I enabled hard gpu sync which weirly enough caused CPU usage to drop!

![xmb_idle_fullscreen_gl_hardsync_0](https://cloud.githubusercontent.com/assets/1721040/11357899/aa30f6ca-923a-11e5-982d-d5d6429832f9.png)

So I decided to profile this last config that seems promising, a weird thing is that even on idle there seems to be 9 threads that belong to retroarch.exe:

![vsidle_last](https://cloud.githubusercontent.com/assets/1721040/11357919/e2e84fa4-923a-11e5-88de-e085b15e5cb0.png)

**Comment by fr500** [comment]
The profiling results:
https://dl.dropboxusercontent.com/u/149537/Temp/capture.csv
https://dl.dropboxusercontent.com/u/149537/Temp/capture.sleepy

![screenshot 2015-11-23 23 42 32](https://cloud.githubusercontent.com/assets/1721040/11358014/e8a10c50-923b-11e5-9d2e-71bce75d2f89.png)

Not sure how to interpret these

**Comment by fr500** [comment]
I was able to get some extra info with a debug build after I tweaked the makefile to include:
OPTIMIZE_FLAG = -gdwarf-2 -fno-omit-frame-pointer

First of all, the heaviest hitter in RetroArch is this:
![screenshot 2015-11-24 00 24 53](https://cloud.githubusercontent.com/assets/1721040/11358598/04412ffc-9242-11e5-82e6-893a14c630db.png)
![screenshot 2015-11-24 00 24 34](https://cloud.githubusercontent.com/assets/1721040/11358593/f45c326c-9241-11e5-86ae-e961c1e2a91d.png)

	void scond_wait(scond_t *cond, slock_t *lock)
	{
	#ifdef _WIN32
	   WaitForSingleObject(cond->event, 0);
	   
	   SignalObjectAndWait(lock->lock, cond->event, INFINITE, FALSE);
	   slock_lock(lock);
	#else
	   pthread_cond_wait(&cond->cond, &lock->lock);
	#endif
	}

Another interesting thing, even though ffmpeg is active there are some calls to ffmeg_retro_cheat_set, not sure if really important though:

![screenshot 2015-11-24 00 27 02](https://cloud.githubusercontent.com/assets/1721040/11358606/23504202-9242-11e5-9d76-65df81ba69b6.png)

If anything from my limited understandig it would seem that it's a problem on the nvidia GL driver. 
These two captures show the time spent on the most called functions:

![screenshot 2015-11-24 00 32 11](https://cloud.githubusercontent.com/assets/1721040/11358671/d29b6e9e-9242-11e5-9616-3b411d6fbab1.png)
![screenshot 2015-11-24 00 32 14](https://cloud.githubusercontent.com/assets/1721040/11358672/d2a33ba6-9242-11e5-9213-7b587a2c90a5.png)

Most of the calls are not called from RetroArch itself (but I profiled retroarch.exe) so I think the GL driver is doing something weird... (but I don't know for sure)

**Comment by fuzhuo** [comment]
It's the same on iOS. RetroArch taken 100% CPU on background and device got very hot.

PID COMMAND      %CPU   TIME   #TH #PRTS #MREGS  RPRVT  RSHRD  RSIZE  VSIZE
15915 RetroArch  102.1%  5:19.70   7   113      0      0      0    72M+  953M
15300 backboardd  15.5% 20:21.54  17   999      0      0      0    10M+  836M
15926 top          1.9%  0:05.48   1    18      0      0      0  1308K   534M
15303 SpringBoar   1.3%  5:32.65  15   858      0      0      0    49M  1032M
15222 mediaserve   0.8%  1:48.57  11   342      0      0      0  5696K   733M
14840 DataMeterD   0.4%  1:39.61   4    47      0      0      0   908K   691M
  122 UserEventA   0.0% 58:41.37  14   903      0      0      0  3688K   749M

**Comment by twinaphex** [comment]
Use the latest version on Cydia or compile the latest sources, these issues happened only for a brief few hours yesterday and they should not happen anymore.

**Comment by fr500** [comment]
@fuzhuo please don't go crossposting unrelated issues everywhere, this is some reaserch trying to get to the bottom of a very specific issue. 
The issue tracker is not a forum for people to go "me too"

**Comment by fr500** [comment]
It seems to be an issue with threaded optimization on NVIDIA drivers, windowed tests:

Mode: windowed
Threaded Optimization: auto (nvcpl)
Hard GPU Sync: off

![windowed_threaded_auto_hardsync_off](https://cloud.githubusercontent.com/assets/1721040/11381319/59a623f8-92c9-11e5-9aa5-fa7224462590.png)

Mode: windowed
Threaded Optimization: auto (nvcpl)
Hard GPU Sync: on

![windowed_threaded_auto_hardsync_on](https://cloud.githubusercontent.com/assets/1721040/11381325/62f61cce-92c9-11e5-91c7-eb03ab9c5fcb.png)

Mode: windowed
Threaded Optimization: off (nvcpl)
Hard GPU Sync: off

![windowed_threaded_off_hardsync_off](https://cloud.githubusercontent.com/assets/1721040/11381330/6b373f44-92c9-11e5-8bf9-d83ce81ef635.png)

Mode: windowed
Threaded Optimization: off (nvcpl)
Hard GPU Sync: on
![windowed_threaded_off_hardsync_on](https://cloud.githubusercontent.com/assets/1721040/11381334/7267b730-92c9-11e5-8a66-bd41bb8c5ee4.png)

For starters, it seems hard gpu sync does nothing in windowed mode, also notice the dramatic reduction in CPU usage with threaded optimization off, I'm running windowed full screen and fullscreen tests now

**Comment by fr500** [comment]
In windowed fullscreen the results are less conclusive, but threaded optimization off does help a bit:

Mode: windowed fullscreen
Threaded Optimization: auto (nvcpl)
Hard GPU Sync: off

![fswindow_threadedauto_hardoff](https://cloud.githubusercontent.com/assets/1721040/11381558/ae4249a4-92ca-11e5-93a2-acb6d219c358.png)

Mode: windowed fullscreen
Threaded Optimization: auto (nvcpl)
Hard GPU Sync: on

![fswindow_threadedauto_hardon](https://cloud.githubusercontent.com/assets/1721040/11381564/b3a6044e-92ca-11e5-9208-856cde918533.png)

Mode: windowed fullscreen
Threaded Optimization: off (nvcpl)
Hard GPU Sync: off

![fswindow_threadedoff_hardoff](https://cloud.githubusercontent.com/assets/1721040/11381572/c094f070-92ca-11e5-9370-ec953e9b660b.png)

Mode: windowed fullscreen
Threaded Optimization: off (nvcpl)
Hard GPU Sync: on

![fswindow_threadedoff_hardon](https://cloud.githubusercontent.com/assets/1721040/11381580/c9de854c-92ca-11e5-837a-22b5e67f2054.png)

**Comment by fr500** [comment]
In exclusive fullscreen the tests again seem less conclusive but still, threaded optimization on the driver seems to be doing some harm:

Mode: fullscreen
Threaded Optimization: auto (nvcpl)
Hard GPU Sync: off
![fs_tauto_hoff](https://cloud.githubusercontent.com/assets/1721040/11381995/5aa59992-92cd-11e5-8500-4e6f3d73be74.png)

Mode: fullscreen
Threaded Optimization: auto (nvcpl)
Hard GPU Sync: on
![fs_tauto_hon](https://cloud.githubusercontent.com/assets/1721040/11382007/653658b0-92cd-11e5-9244-f355028968e8.png)

Mode: fullscreen
Threaded Optimization: off (nvcpl)
Hard GPU Sync: off
![fs_toff_hoff](https://cloud.githubusercontent.com/assets/1721040/11382014/6c92dfde-92cd-11e5-9a92-c484af2ca355.png)

Mode: fullscreen
Threaded Optimization: off (nvcpl)
Hard GPU Sync: on
![fs_toff_hon](https://cloud.githubusercontent.com/assets/1721040/11382022/7386486c-92cd-11e5-8e84-8d22825f21ab.png)

It would be interesting to see similar tests of other people with nvidia and with other hardware too, for now my advice is to disable threaded optimization.

BTW, game performance seems unaffected by this issue.

**Comment by aliaspider** [comment]
threaded optimisation seems to use an even "harder" gpu sync for windowed mode than retroarch's "Hard GPU Sync" implementation, that doesn't use sleep at all.
and yeah this doesn't affect game performance negatively, actually it might even slightly increase game performance since the main thread is garanteed to resume after the vsync, it might make sense for applications that are already at >90% cpu usage, but not for retroarch.

**Comment by fr500** [comment]
@aliaspider I think we tried a few months back, you tried on XP and I did on Windows 8.1 and the setting didn't affect the results so it's at least it's possible to work around it now

**Comment by fr500** [comment]
it seems this is not really specific to RetroArch but more like a GPU driver issue

**Comment by fr500** [comment]
this is mostly a driver issue and while it's not 100% fixed it really does depend on GPU drivers, and whether threaded optiomization is on/off so closing this.
