### ISSUE TITLE
[XMB] Last icon drawing in the wrong position when it would be cutoff

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2466]
@Kivutar I don't think this was happening on XMB, it does happen with the toggle icons on GLUI too, when an icon would be cutoff it seems to draw "just next" to the last one

https://photos.google.com/photo/AF1QipMXVb2xAuOWgd-owcukkNXRomKF_6IZvvExst8

**Comment by Kivutar** [comment]
Hi @fr500 , the photo link is broken :o

**Comment by fr500** [comment]
Works for me,  its a video

**Comment by Kivutar** [comment]
I get a 404

**Comment by fr500** [comment]
https://photos.google.com/share/AF1QipMOMR-zu1gbFY2Z34IrA1QHp_gcLtQyBEW39SeOTnOwWVSR0CpBpbRRVbAn_5dkfA?key=eDB3UERZb3pkeXd4QVZWQ3U5N3ZKZzNub0Q5Q2dR

Try that URL, I tried now on a browser were I'm not logged in
