### ISSUE TITLE
[Windows 7] Turning on Threaded Video instantly crashes RA in windows 7 64 bit

### ISSUE THREAD

**Issue by Warriors-Blade** [libretro/RetroArch#2493]
I updated to the latest build which currently is 11/28/2015
and once I attempt to turn threaded video on it instantly crashes Retroarch.

It was working fine a few builds ago, I can try to backtrack and see which build it works on.

Windows 7 64
Intel chipset laptop

**Comment by twinaphex** [comment]
User reported on IRC that this is fixed now, closing.
