### ISSUE TITLE
Required files for PPSSPP not downloaded when core is downloaded

### ISSUE THREAD

**Issue by thatcadguy** [libretro/RetroArch#2500]
http://libretro.com/forums/showthread.php?t=4304

When the PPSSPP core is downloaded on Android (and probably other platforms), the required files apparently aren't there to properly use it. These should be downloaded/installed automatically when the core is.

**Comment by fr500** [comment]
No...
Those are pretty much user data, like ROMS or BIOS.

**Comment by thatcadguy** [comment]
Well, regardless of what you think, it's not intuitive. There's no message in RetroArch that says you have to download these; I had to go to the forum to find this out. At the very least there should be an error message that comes up. Nothing comes up when I try to play Metal Slug XX, you see the loading page then it goes blank when it goes to show the system message about save data. PPSSPP itself (standalone Windows and Android versions) have these included, why shouldn't the RA core include these?

**Comment by fr500** [comment]
Because the core is just a .so file, cores can't have any dependencies.
RetroArch is meant to function independently from the core. Heck RetroArch doesn't know PPSSPP exists.

I agree, some feedback would be good but bundle them with RetroArch... nope.

**Comment by thatcadguy** [comment]
Could there be another menu option in the online updater section, e.g.
"Download dependencies" or something like that?

**Comment by fr500** [comment]
I still think this is a user issue, and I would vote for a "won't fix"

**Comment by Kivutar** [comment]
Yes, the current core updater is not meant to handle things that are not cores.

Why not backing these files into PPSSPP itself? In the non shallow fork at least. They are just fonts, iirc?
