### ISSUE TITLE
7zip support broken

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2501]
When trying to browse an archive as a folder it shows no items.
Expected result: it should show a list of the files within the 7z

First broken commit: 6f50187b56c63cb1991f0db55032c410c96392c2

**Comment by fr500** [comment]
Bisect log for reference:

$ git bisect log
git bisect start
# bad: [22d64ae3dc957946c71a3c6cbaa6a7a4a9ac6884] move driver->remote and driver->command to input_driver.c
git bisect bad 22d64ae3dc957946c71a3c6cbaa6a7a4a9ac6884
# good: [7f164647a2d2d89d8ec71628297a85fd3ee110d3] (jsonsax) Preventing more namespace / symbol collisions in the future
git bisect good 7f164647a2d2d89d8ec71628297a85fd3ee110d3
# good: [9aaababd056990950e2e9bab29052f9c998b95d9] Merge pull request #2383 from aliaspider/master
git bisect good 9aaababd056990950e2e9bab29052f9c998b95d9
# bad: [ddde58caf45c346c99aa73bb0628adf90f555f0d] Simplify video_driver_get_ptr
git bisect bad ddde58caf45c346c99aa73bb0628adf90f555f0d
# skip: [7394913f111564ba478b2b4eb14fba4ba7743670] (360) WNDCLASSEX not available
git bisect skip 7394913f111564ba478b2b4eb14fba4ba7743670
# bad: [e202966a49e8bb3f9d5b15fca6690e6d9b32a705] Merge pull request #2404 from Ezio-PS/master
git bisect bad e202966a49e8bb3f9d5b15fca6690e6d9b32a705
# good: [5fc267d24a0b004356ea303d608eec44151a26a4] (OSX/iOS) get_chosen_screen buildfixes
git bisect good 5fc267d24a0b004356ea303d608eec44151a26a4
# good: [f089fff42f7554423c5e9dce3368684fe1be57d7] Revert "Fix warnings"
git bisect good f089fff42f7554423c5e9dce3368684fe1be57d7
# good: [e882709e63006818c874e465e5634b39b2f1d9f4] (mfi_joypad.m) Indenting nits
git bisect good e882709e63006818c874e465e5634b39b2f1d9f4
# good: [170b4bbbe28e4457706d160ad9a8ef63842572cb] (btstack_hid.c) Add Cocoa ifdef
git bisect good 170b4bbbe28e4457706d160ad9a8ef63842572cb
# good: [2fe29f56be842c6d19aa67d5e2c940d7b8e346eb] remove useless forward declaration
git bisect good 2fe29f56be842c6d19aa67d5e2c940d7b8e346eb
# bad: [6f50187b56c63cb1991f0db55032c410c96392c2] Create utf16_conv_utf8 - recycled code - should probably be cleaned up
git bisect bad 6f50187b56c63cb1991f0db55032c410c96392c2
# good: [8918df95e126878c13f32dea66b2b58f8c9bb394] Add encoding_utf to libretro-common
git bisect good 8918df95e126878c13f32dea66b2b58f8c9bb394
# good: [d69aa24f287197f275ba38f63beb005edbfe685d] Add encoding_utf to Griffin
git bisect good d69aa24f287197f275ba38f63beb005edbfe685d
# first bad commit: [6f50187b56c63cb1991f0db55032c410c96392c2] Create utf16_conv_utf8 - recycled code - should probably be cleaned up

**Comment by twinaphex** [comment]
Should be fixed with this commit:

https://github.com/libretro/RetroArch/commit/cb0c8497c9efbceb0727fa3f8af8caca1e73561b

We should really rewrite that code though. It is quite ugly to say the least.
