### ISSUE TITLE
font driver broken on android

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2504]
In the latest build this happens:
https://photos.google.com/photo/AF1QipNP66IZstDQvgWtSlbL3y2DgZEmMrKz_bdjqS4
I suspected it could be just the OSD interface but in XMB/GLUI it's even worse and the interface gets corrupted by hitting buttons or other actions

**Comment by fr500** [comment]
The gui is fully workable with touch, every setting can be toggled, and you can navigate with the overlay too.

Only when physical controls are applied this happens.
Another interesting thing, toggling threaded video with touch works, but if you toggle with a gamepad retroarch it's like the button press locks up and it starts toggling on/off, I think there is some bug with GL/fonts, and something else with the input driver.

**Comment by twinaphex** [comment]
This should fix the issue -

https://github.com/libretro/RetroArch/commit/d0340d0f80a4130022e0ba69ba7fc3e5c7ab335d
