### ISSUE TITLE
Input bug on latest build

### ISSUE THREAD

**Issue by bronnel** [libretro/RetroArch#2505]
In the latest build the entries of [Input User # binds] has been replaced with the entries of Input hotkey binds, now I don't know how to map the buttons, the buttons register just fine but the entries have been replaced and you won't know which buttons are being mapped.
I tested on ios and android, I also updated autoconfig profiles
![image](https://cloud.githubusercontent.com/assets/15629916/11499556/e5540d48-9837-11e5-946d-613b29ee1c8f.jpg)
![image](https://cloud.githubusercontent.com/assets/15629916/11499557/e59cb110-9837-11e5-85f8-d33d1fc73f17.jpg)

**Comment by twinaphex** [comment]
This should fix it:

https://github.com/libretro/RetroArch/commit/eb512d0cafeaac11755dc47c16c7273148bf5c5d

**Comment by bronnel** [comment]
Thank you sir it's perfect now
