### ISSUE TITLE
Inconsistent initial position of Quick Menu

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2506]
There's some inconsistency in the initial position of quick menu, if you:

Load content by playlist it'll be at Resume Content

If you use Load Content --> Select File and Detect Core, ~~it'll be at Close Content~~ it'll be at Restart

~~If you load by history, it can be at Restart Content, State Slot, Load State, Core Options or Shaders~~ seems it's fine now when loading by history

**Comment by Kivutar** [comment]
A navigation clear have to be called after each push of the quick menu, to reset the position of the navigation ptr to 0.

**Comment by fr500** [comment]
yeah I noticed this too, it's confusing

**Comment by sergiobenrocha2** [comment]
Maybe it's somewhat related to #1891 ?

The icon from the last position overlaps the current position, i.e., if the last initial position was Restart Content, then the correspondent icon overlaps the Close Content (current initial position).

**Comment by orbea** [comment]
@sergiobenrocha2 I submitted PR https://github.com/libretro/RetroArch/pull/7794 which seems to fix this and the related issue https://github.com/libretro/RetroArch/issues/5595.

When you have a chance please let me know if I missed anything.

**Comment by orbea** [comment]
I am going to reopen this issue as I found a new case of this.

1. Proceed to any playlist.
2. Select any content.
3. Load any core that is not the first one in the list.
4.  The quick menu position will not be initially reset to `Run`.
