### ISSUE TITLE
GLUI corruption in latest build

### ISSUE THREAD

**Issue by objectchris** [libretro/RetroArch#2507]
Hi! I seem to have some corruption with the GLUI in the latest build. Normally I'd expect it to be a transparent black background with smooth (green?) text, and now it's a white background with black pixelated text, and some sort of tabbing system, but the tabs have no visible titles (presume they should have?). Looks like this new tabbing system isn't quite displaying right with my setup?

Here is a shot of what I'm seeing:

![fullsizerender](https://cloud.githubusercontent.com/assets/13054748/11519417/e8b4afb0-9891-11e5-9c99-6ab3cbfeff3b.jpg)

I'm running on a Rasperry Pi 2 with RetroPie. Not sure if this could have anything to do with it, but the GLUI looked fine with the 1.2.2 binaries, just not when I rebuilt from the latest source. I did this a couple of weeks ago with the same issue, but retried today and got the same thing.

**Comment by twinaphex** [comment]
You are missing the assets, that is why the tab icons are not showing. So this is not a bug at all.

To make installing the assets easy, go to Online Updater, and select 'Update Assets'. Once the assets have finished downloading, it should refresh RA and you should be able to see the menu in its full glory.

**Comment by objectchris** [comment]
thanks! that looks better :) but it's still a totally white background rather than the translucent from before - not sure if this is intentional or not?
