### ISSUE TITLE
When going back from a submenu it sends you to the first parent menu option instead of the one you were in

### ISSUE THREAD

**Issue by kivutar** [libretro/RetroArch#2510]
Reported here: http://libretro.com/forums/showthread.php?t=4559

And I was able to reproduce it, in some settings groups, but not all.

**Comment by orbea** [comment]
@kivutar Can you still reproduce this? The forum link is dead.

**Comment by RobLoach** [comment]
I remember this happening, but I think it's fixed.

**Comment by orbea** [comment]
Given the lack of activity, information and since neither of us can reproduce any issues I'll close this.
