### ISSUE TITLE
When configuring a directory the folder chooser always starts from the root folder instead of the one you already had configured

### ISSUE THREAD

**Issue by kivutar** [libretro/RetroArch#2511]
Reported here: http://libretro.com/forums/showthread.php?t=4559

I could reproduce.

And yes, it would be an improvement to start from the folder we already set, I think.

**Comment by zoltanvb** [comment]
I believe this is fixed nowadays, tested quickly but all directory choosers seem to start from the previous setting.

**Comment by sonninnos** [comment]
Yes: https://github.com/libretro/RetroArch/pull/15199
