### ISSUE TITLE
I could find no option to use no shader after selecting a shader

### ISSUE THREAD

**Issue by kivutar** [libretro/RetroArch#2513]
Reported here: http://libretro.com/forums/showthread.php?t=4559

Users just have to use the start button to reset the number of shader passes to 0. But looks like it's not obvious enough?

**Comment by fr500** [comment]
Set passes to zero an apply, yeah it could be more obvous

**Comment by zach-morris** [comment]
I'd like to add a suggestion of having a "No Shader" preset.  That would allow the user to save a core / game override and have No Shader when desired.  It doesn't seem like a 0 pass shader can be saved as an override (at least right now).

**Comment by hizzlekizzle** [comment]
The Cg shaders have the "bilinear" and "nearest" presets, which just apply the stock shader with the corresponding sampling method. I could add those same presets to the GLSL and slang repos, if that would be sufficient. We could also consider renaming them to "no-shader_sharp/soft", if that would be more descriptive.

**Comment by Pixelnarium** [comment]
Tested RetroArch on Android a couple of minutes ago and was unable to disable the shader when you have no controller. I could not figure out how to set passes to 0. So even if I search for it and find out "set passes to zero" I am unable to do it.

It should be more obvious.

**Comment by Aethyrion** [comment]
I think this one can be closed now there is a Quick Menu option to disable shaders.

**Comment by hizzlekizzle** [comment]
agreed. closing.
