### ISSUE TITLE
Why are NVIDIA Shield Controllers hard coded to port 0?

### ISSUE THREAD

**Issue by HakShak** [libretro/RetroArch#2522]
Was trying to take a look at this: https://github.com/libretro/RetroArch/blob/c0a1a6a3fe5f8b0953ea08bc67f006cb0893431e/input/drivers/android_input.c#L696

What is the context of this hack? Was curious if there are any hints before I dive in.

Thanks!

**Comment by fr500** [comment]
Well the shield controllers are two hid devices, the actual gamepad and the "nvidia button" that is mapped as an android back button.

If we didn't have this hack and someone pressed the nvidia button then you'd be locked unable to navigate the UI, basically it makes possible to use that button, and then forces the actual controller to be bound again to port 0 when you hit one of the buttons.

I do the same for the remote, it gets bound to port 0 and when an actual controller button is pressed it overrides that binding.

I think a better solution would be to have a dedicated port for "non-common" devices, but that needs digging deep into the input driver.

**Comment by fr500** [comment]
Btw, if you use two shield controllers it should work fine.

**Comment by fr500** [comment]
Should be fixed and we haven't received any other feedback from you

**Comment by HakShak** [comment]
Just making a note, as of 1.2.2 win x64 two wired XBox 360 controllers over moonlight do not work. RetroArch recognizes an "NVIDIA SHIELD" controller, but even with manual mapping doesn't detect button presses from the second controller. Both controllers work fine with the exact same moonlight environment and Steam. I even tried testing them both in Steam and start RetroArch through steam. Again, both controllers worked in Steam and RetroArch detected "NVIDIA SHIELD", but RetroArch would not detect button presses from the second controller.

Is there a nightly I should try?

**Comment by fr500** [comment]
This is not RetroArch's fault.
Gamestream forwards inputs to some sort of virtual josytick that is not being enumerated correctly by dinput.

I understand it works on steam but as I said, when enumerating only one XBOX 360 controller appears.
