### ISSUE TITLE
[windows] crashes with GL driver

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2527]
Lately it's crashing on the following scenarios:

- Loading RetroArch with a shader preset loaded
- Selecting a shader preset
- Task switching when in-game when a shader preset is loaded (via per-core configs or overrides, loading shaders in any other way crashes retroarch immediately)

**Comment by Monroe88** [comment]
I have some backtraces for this

Starting RA with video_shader already set
http://pastie.org/10612724

Loading a preset from the menu
http://pastie.org/10612735

**Comment by fr500** [comment]
This is the first bad commit:
e735f84baa8e193d55d1a63bf0643a207eae1c16

**Comment by twinaphex** [comment]
Well honestly, youll just have to figure out how to make it work. We are not going to be reverting this commit, you will have to figure out the actual cause and fix it.

**Comment by twinaphex** [comment]
I got the same problem when I went into Preview Shader Parameters.

This fixed the issue for me:

https://github.com/libretro/RetroArch/commit/38a7338592c02c1a9f5a190a65616bcf41fcc768

Test on your end if it fixes these issues for you guys as well.

**Comment by fr500** [comment]
Fixed

**Comment by fr500** [comment]
Acually no, I just re-cloned because there were some merge conflicts on my fork and rebuilt and it's still crashing.
