### ISSUE TITLE
Buttons artifacts on Android

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2530]
Sometime this happens with XMB on Android. Try to access other app and then come back to RA, you'll see all the overlay buttons like this:

![screenshot_2015-12-05-23-20-49](https://cloud.githubusercontent.com/assets/5431285/11614602/62098c9c-9c2e-11e5-94d3-f9b6374b5b81.png)

**Comment by fr500** [comment]
I don't get this anymore, reopen if the issues persits.

**Comment by sergiobenrocha2** [comment]
I'm getting this sometimes in other situation: when I switch the overlay index, from overlay0 to overlay1 for example (landscape to portrait or whatever). It happens sometimes, not always, and it's very fast (it does not stuck).

**Comment by sergiobenrocha2** [comment]
@fr500 could you open it again?

**Comment by fr500** [comment]
@sergiobenrocha2 sure, but can you test on the latest code?

**Comment by sergiobenrocha2** [comment]
Still happens with the latest commit
