### ISSUE TITLE
Overlay buttons get unresponsive

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2531]
Overlay buttons get unresponsive on android after some time you keep it pressed. It's very hard to play shoot up and race games.

You notice it get unpressed after some time you are holding it, then you try to press the same button again, and it's unresponsive for a time.

**Comment by fr500** [comment]
I can't confirm, it doesn't happen on my device

**Comment by sergiobenrocha2** [comment]
I can reproduce it sometimes, It takes 6 seconds more or less to get unresponsive. I don't know what's triggering it.

**Comment by sergiobenrocha2** [comment]
I can reproduce one thing here:

Try gba games in the portrait mode, with flat gba overlay, then press & hold the button A, then press many times the left button, you'll notice you can't hold the button A, i.e. it is unpressed when you press the left button.

**Comment by meepingsnesroms** [comment]
Tested, doesnt happen on my phone, although the a button and left are on the same horizontal lines and I have had phones with defective multitouch when multiple touches are exactly horizontal of vertical from each other.
