### ISSUE TITLE
Boxart not showing up

### ISSUE THREAD

**Issue by quikbeam** [libretro/RetroArch#2533]
Set a box art directory to /sdcard/Android/data/com.retroarch/files/boxart

Copied over SNES box art to test.  Not seeing any box art when going to collection through: Load Content -> Select From Collection -> Super Nintendo Entertainment System.lpl

Does box art work on this version?

**Comment by Kivutar** [comment]
They work, but you have to follow a specific naming scheme, like

    /sdcard/Android/data/com.retroarch/files/boxart/Super Nintendo Entertainment System/Named_Snaps/Super Mario World (U).png

**Comment by quikbeam** [comment]
Thanks Kivutar.

Is this documented anywhere?  Just curious about how other cores would be configured for boxart.

Does the code look at the boxart directory in the configuration?

Also, does the folder in the example above have to be named after the playlist?  I tried creating the folder structure above but it didn't work for me.

**Comment by Kivutar** [comment]
We haven't documented it yet. The feature is still unfinished. But I will.

The code does look at the boxart directory.

The folders inside this boxart directory have to be named after the playlist.

Unzipping one of these https://www.dropbox.com/sh/8xuhgxahhk6pfk4/umSNUhRGC0 and fixing the folder name should work.

You have to enable **display boxarts** in the menu settings.

And use the XMB menu driver.

**Comment by quikbeam** [comment]
I still can't seem to get the box art to show up.  I've probably missed something.

-cleared app settings, set everything back to default settings
-updated core Snes9x Next
-set menu driver to xmb
-set configuration per core 'on'
-turned on display boxart and dynamic wallpaper
-set boxart directory to /storage/emulated/0/Android/data/com.retroarch/files/boxart
-copied over folder from the dropbox link above, renamed to 'Nintendo - Super Nintendo Entertainment System' to match playlist
-exit and relaunched
-scanned directory for SNES roms, playlist created
-load content -> select from collection -> Nintendo - Super Nintendo Entertainment System.lpl

I'm on a Nvidia Shield TV and I'm loading my roms through a mapped network drive if that makes a difference.

**Comment by Kivutar** [comment]
Can you show me the full path of one of your boxarts?

**Comment by quikbeam** [comment]
/sdcard/Android/data/com.retroarch/files/boxart/Nintendo - Super Nintendo Entertainment System/Named_Titles

/sdcard/Android/data/com.retroarch/files/boxart/Nintendo - Super Nintendo Entertainment System/Named_Snaps

**Comment by Kivutar** [comment]
By full path I mean really full path, including the image name.

**Comment by quikbeam** [comment]
Here is an example:

/sdcard/Android/data/com.retroarch/files/boxart/Nintendo - Super Nintendo Entertainment System/Named_Snaps/2020 Super Baseball (USA).png

**Comment by quikbeam** [comment]
Which version is this supported on?  I installed a nightly and I was able to show named_snaps but not named_titles. Version 1.3.0 2015-12-11. But I had problems updating cores or loading them

**Comment by glitchninja2000** [comment]
I had the same issue, but I figured out you have to 'Add Content' first.

**Comment by fr500** [comment]
So this seems to be a usage issue, feel free to discuss, closing.

**Comment by Celes-Eternal** [comment]
Just to be sure, it's not possible to add boxart from the rom directory?

**Comment by ElHave247** [comment]
Im having the same issue, on pc, setting right the boxart name and directory , still dont show.
