### ISSUE TITLE
Switching languages

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2534]
Switching languages was working well two month ago. It looks like we got some important regressions in this field.

On RGUI and GLUI, switching language will remove all settings groups except 3, until retroarch is restarted.

On XMB, it prevent users to go back to the settings groups, which ruins the feature on Lakka.

Ideally, we should be able to come back to the previous behaviour where changing the language takes effect directly without breaking the menus.

**Comment by fr500** [comment]
is this still going on? reopen if so
