### ISSUE TITLE
Working MAME romset

### ISSUE THREAD

**Issue by quikbeam** [libretro/RetroArch#2536]
How would I go about finding out which romset is supported.  I tried a scan of the MAME 0152 romset I have but the playlist isn't being created properly.

**Comment by Kivutar** [comment]
The scanning process lacks support for some systems, including arcade ones, due to the structure of roms.

**Comment by quikbeam** [comment]
Any clues as to what I need to look for in this case?  Would the Nvidia Shield TV be one of those systems?

**Comment by sergiobenrocha2** [comment]
The systems he told are the arcade systems, such as CPS-1/2, Neo Geo... it's not your device.

You can manually make the playlist for mame, like this:

```
/home/your-user/path/to/roms/captcomm.zip
Captain Commando (World 911202)
/path/to/mame_libretro.so
MAME Git
00000001|crc
MAME.lpl
/home/your-user/path/to/roms/dino.zip
Cadillacs and Dinosaurs (World 930201)
/path/to/mame_libretro.so
MAME Git
00000001|crc
MAME.lpl
/home/your-user/path/to/roms/19xx.zip
19XX: The War Against Destiny (USA 951207)
/path/to/mame_libretro.so
MAME Git
00000001|crc
MAME.lpl
```

**Comment by fr500** [comment]
Please report issues in the correct trackers
You can find a list of the repositories here https://github.com/libretro
