### ISSUE TITLE
Decreasing the shader passes segfaults RetroArch

### ISSUE THREAD

**Issue by MoochMcGee** [libretro/RetroArch#2540]
Okay, so I loaded CRT-Royale, then I decreased the shader passes twice. On the second time, RetroArch immediately segfaults.

**Comment by MoochMcGee** [comment]
Here's a stack trace:
#0  0x00007ffff0a41875 in __GI__IO_vfscanf () from /usr/lib/libc.so.6
#1  0x00007ffff0a56397 in vsscanf () from /usr/lib/libc.so.6
#2  0x00007ffff0a50e37 in sscanf () from /usr/lib/libc.so.6
#3  0x000000000044a378 in video_shader_resolve_parameters (conf=0x0, shader=0xd5e3e0) at gfx/video_shader_parse.c:402
#4  0x00000000004c1f2b in action_left_shader_num_passes (type=0, label=0x7fffffffc640 "video_shader_num_passes", wraparound=false)
    at menu/cbs/menu_cbs_left.c:270
#5  0x00000000004a78c3 in menu_entry_action (entry=0x7fffffffb640, i=5, action=MENU_ACTION_LEFT) at menu/menu_entry.c:389
#6  0x00000000004d871c in generic_menu_iterate (action=MENU_ACTION_LEFT) at menu/drivers/menu_generic.c:291
#7  0x0000000000485ad7 in menu_driver_iterate (action=MENU_ACTION_LEFT) at menu/menu_driver.c:269
#8  0x000000000041d9ab in runloop_iterate (sleep_ms=0x7fffffffe7dc) at runloop.c:1261
#9  0x000000000041202d in rarch_main (argc=1, argv=0x7fffffffe918, data=0x0) at frontend/frontend.c:306
#10 0x00000000004120a4 in main (argc=1, argv=0x7fffffffe918) at frontend/frontend.c:327

**Comment by Monroe88** [comment]
It seems to be related to the number of runtime shader parameters. Most shaders have few parameters and they don't appear to trigger a segfault when changing the number of passes, but anything with a large number of runtime parameters like CRT Royale seems to trigger it.

**Comment by fr500** [comment]
Is this fixed?

**Comment by twinaphex** [comment]
Going to close this until OP can confirm this still happens.
