### ISSUE TITLE
UStealth support for Wii U

### ISSUE THREAD

**Issue by cucholix** [libretro/RetroArch#2541]
Replacing by this libfat library
http://www.mediafire.com/?9d1ffxo16kc1gmq

UStealth hides HDD from Wii U OS to avoid getting the format messages upon boot.
More info:
http://gbatemp.net/threads/ustealth-wii-u-format-disk-nag-workaround.352786/page-12#post-4988611

**Comment by WizLizard** [comment]
Yes Please!

**Comment by TheMaxiP4D** [comment]
And allows to connect two external drives to the WiiU at the same time! It's an essential!

**Comment by cucholix** [comment]
Already added
