### ISSUE TITLE
No input is being registered (Wii)

### ISSUE THREAD

**Issue by zerofalcon** [libretro/RetroArch#2547]
Since this commit every compiled core have no input registered at all:
https://github.com/libretro/RetroArch/commit/0b9df5a069d9cbf6ca2d1683acdf711dd90a3d8d

Last working commit:
https://github.com/libretro/RetroArch/commit/fdfcbaa04284cc2f4cf83420614f45454fd06083

**Comment by twinaphex** [comment]
Is  fdfcbaa truly the last working commit or is there a more recent commit too that still worked?

**Comment by zerofalcon** [comment]
Yes, that was the last working. More recent commits until https://github.com/libretro/RetroArch/commit/0b9df5a069d9cbf6ca2d1683acdf711dd90a3d8d cant be compiled, this is the error showed when compiling:

In file included from griffin/griffin.c:346:0:
griffin/../input/drivers_joypad/gx_joypad.c: In function 'gx_joypad_poll':
griffin/../input/drivers_joypad/gx_joypad.c:527:4: error: 'check_menu_toggle' un
declared (first use in this function)
    check_menu_toggle = (*state_p1 & (UINT64_C(1) << GX_GC_HOME));
    ^
griffin/../input/drivers_joypad/gx_joypad.c:527:4: note: each undeclared identif
ier is reported only once for each function it appears in
make: *** [griffin/griffin.o] Error 1
