### ISSUE TITLE
[Mac, Configuration] Cores won't configure separate from menu

### ISSUE THREAD

**Issue by glitchninja2000** [libretro/RetroArch#2560]
I set up my RetroArch to work with NES, which was nice because it didn't conflict with the menu. But after setting it up for my SNES games, whenever I use the **Quick Menu** it controls like the SNES controls, even though I have *Configuration Per Core* on. I am using a **Wiimote** right now, so I have to set them up very differently.
![cfg per core](http://i67.tinypic.com/2ex25nq.png)

**Comment by fr500** [comment]
Can you clarify? your wording is confusing

**Comment by Kivutar** [comment]
Are you talking about input remapping?

**Comment by yahreen** [comment]
I'm having an issue with a fresh install of 1.3.0. on Windows x64 where setting "Configuration Per-Core" is not being honored. I wonder if this is the issue @glitchninja2000 is referring to?

Create a new 1.3.0 install
Download a core
Set file path to roms
Load a content file to ensure everything is working
Use hot-button to close content

Back at main menu, repeat steps above with a new core.
Make sure to set a separate path for the new core's roms.
Start the 2nd core with a file to make sure it works.
Use hot-button to return to menu, close content.

Now load the first core you setup.
Select "Load content"
Note the files that are brought up.

The result for me is the file path associated with the 2nd core is now associated with the first core, despite having "Configuration Per-Core" set to "On"

**Comment by christ776** [comment]
Hi, sorry if this is a bit Off Topic, but, how do get to sync the Wiimote? While RetroArch detects it's connected, the lights on the Wiimote don't stop flashing.

**Comment by fr500** [comment]
configurations per-core are removed now so this is irrelevant
