### ISSUE TITLE
[Linux, Rasberry Pi] Dispmanx video driver causes instability in RGUI

### ISSUE THREAD

**Issue by objectchris** [libretro/RetroArch#2562]
Using latest build from source.

Using a Rapsberry Pi 2 and the dispmanx video driver, I appear to getting instability when displaying the RGUI. The display appears to crash, showing a blank screen (and a 'no signal' message on my HDTV), with the game running in the background. If I use hotkeys to close the menu, the display returns. This is all very inconsistent, though - right now after a reboot, I can load a retoarch core, and the RGUI will work fine. If I exist retroarch, and repeat the process, the RGUI will do the crash as detailed above. Perhaps some sort of memory leak? If I don't trigger the RGUI the games work fine (I can't use other menu drivers as they require the GL display driver)

Below is my verbose log with FCEUMM - the display crash occurred after I loaded the game and triggered the RGUI with hotkeys. And then after the crash I used my quit hotkeys to exit. I've done the same with other cores and get similar log files - I don't think they show anything relevant :(

[runcommand.log.txt](https://github.com/libretro/RetroArch/files/60546/runcommand.log.txt)

**Comment by twinaphex** [comment]
The dispmanx graphics driver was written by @Vanfanel.

**Comment by vanfanel** [comment]
@objectchris : I can't reproduce it here. 
Let's say I do:
./retroarch -L cores/fceumm_libretro.so nintendo/mario.nes

the game loads fine, I can play as long as I want, I can enter the RGUI menu by pressing F1, exit back to the game, enter the RGUI menu again with F1, go back to the game... I did it like 100 times in a row and nothing goes wrong here.

What you describe is what happens when dispmanx resources are not freed, but they are being freed everytime the RGUI element and corresponding resources are destroyed because you exit the menu.

So, are you building from git? Or what version or RetroArch are you using?

**Comment by objectchris** [comment]
@vanfanel I should say that I'm quitting retroarch entirely - if load the game once and go in and out of the menu, it works fine every time, but if I quit terminate retroarch (using the proper exit hotkeys or via the menu), it does this issue.

I tried running directly from the command line as per your example, and it worked fine every time! So it must be something to do with my setup:

I'm running https://github.com/RetroPie, which uses emulationstation as a GUI to trigger various cores. The script used to trigger the cores is: https://github.com/RetroPie/RetroPie-Setup/blob/6ad02443704c46d142dd7673895e1be9cd1e7805/scriptmodules/supplementary/runcommand/runcommand.sh

I can rule out emulationstation by exiting to command line, and running the script directly:
`/opt/retropie/supplementary/runcommand/runcommand.sh 0 _SYS_ nes /home/pi/RetroPie/roms/nes/mario.nes`
If I run this once, exit, and then run again and trigger the RGUI, I get the display crash.

I echo'd out the command within the runcommand script used to launch retroarch, but it's not doing anything particularly special:
`/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-fceumm/fceumm_libretro.so --config /opt/retropie/configs/nes/retroarch.cfg "/home/pi/RetroPie/roms/nes/mario.nes" --appendconfig /tmp/retroarch.cfg`

The /tmp/retroarch.cfg file is setup by the script at runtime, and contains these entries:
```
video_refresh_rate = 60
video_fullscreen_x = 0
video_fullscreen_y = 0
```

I copied this to another location, rebooted and ran this command:
`/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-fceumm/fceumm_libretro.so --config /opt/retropie/configs/nes/retroarch.cfg "/home/pi/RetroPie/roms/nes/mario.nes" --appendconfig /home/pi/retroarch2.cfg`
that works fine!?

There must be something else going on in the script that I'm not seeing - perhaps I should pass this issue to the retropie people as that seems to be the issue somehow!

BTW, I rebuilt yesterday from git.

**Comment by objectchris** [comment]
Cracked it! At the very end of the script it does the function restore_fb - this restores the framebuffer to how it was previously. I'm not sure why that causes the issue, though - perhaps the script is doing this in a way that doesn't clean up after itself?

**Comment by HerbFargus** [comment]
These are the relevant lines of code for that function: https://github.com/RetroPie/RetroPie-Setup/blob/6ad02443704c46d142dd7673895e1be9cd1e7805/scriptmodules/supplementary/runcommand/runcommand.sh#L504-L511 perhaps @joolswills may have some input on it.

**Comment by vanfanel** [comment]
It seems to be mangling with the tvservice command. I also do it here for 50Hz systems like the ZX Spectrum 128K core (FUSE) and I don't see things crashing on me because of that.

**Comment by fr500** [comment]
is this still happening?

**Comment by objectchris** [comment]
I will grab the latest RA build and retest when I'm back on the 28th December.

Still not entirely clear if the issue is with retroarch's dispmanx/RGUI implementation or the way retropie resizes the framebuffer in-between RA launches.

**Comment by objectchris** [comment]
Retested using the latest build and still seems to be an issue.

**Comment by objectchris** [comment]
this is resolved by https://github.com/RetroPie/RetroPie-Setup/commit/db09ea97500f8ca123a66933d934e49e4db3b65c - looks like restoring the framebuffer caused the instability. perhaps the driver could handle this but not sure if it's ever likely to come up! happy to close :)
