### ISSUE TITLE
Estimated monitor framerate gone wild.

### ISSUE THREAD

**Issue by mac1202** [libretro/RetroArch#2563]
Hello I got a issue with latest retroarch. The monitor framerate isn't properly detected my tv only do 59.96 (from xrandr). Some core detect the proper framerate other dont so i got a lot of craking sound. Plus retroarch can't properly set the detected framerate see the [screenshot](http://i.imgur.com/crwjG46.jpg).
I only got this problem with opengl driver xvideo i got the proper framerate and sound play perfectly.
I use retroarch since several year never got this problem before.

**Comment by twinaphex** [comment]
Thanks for reporting the bug.

https://github.com/libretro/RetroArch/commit/b50350a71129068b6387ef23cc79a7e512a1423b

This commit should fix it.

**Comment by mac1202** [comment]
fixed the part with wrong framerate applied but still have the weird issue with cracking sound and detected monitor framerate changing between core.

**Comment by twinaphex** [comment]
I don't know what you expect me to do about that.

It is a problem with your environment, not RA. The refresh rate you set when you press 'OK' on 'Estimated Monitor Refresh Rate' is the refresh rate it will use for your games. The monitor refresh rate that you see in 'Estimated Monitor Refresh Rate' is just a refresh rate monitor that tries to sample what the refresh rate of your output device is. It resets itself after every core change obviously. This is the way it has always worked.

Again, I'm not sure what you are expecting here.

**Comment by mac1202** [comment]
previously i didnt have cracking sound in retroarch, but maybe the problem didnt come from retroarch (videocard driver or something else). If you think so you can close this issue.

**Comment by twinaphex** [comment]
Are you using Pulseaudio? Pulseaudio does extra software audio mixing/resampling. Even if you go through ALSA, it is usually still a wrapper around Pulse, thus you still incur the extra overhead. 

Tons of external factors can negatively influence things like this. There is no telling without properly running down the LInux distro you are using, the software used, etc.

Anyway, the information you provided so far is not sufficient for narrowing down these performance problems anyway.

**Comment by twinaphex** [comment]
Some things you can try:

if you get crackled sound then usually the video refresh rate that RA uses is not in sync with your display's refresh rate. You need to let the framerate monitor run for at least 2048 frames, then you need to press on it so that it uses this refresh rate from there on.

Alternatively:

If you have an Intel CPU, look into ways to manually configure the pstates. Pstates are power management states. The CPUs try to downthrottle to as low a power state as possible when they are idle. For RA you'd want to try setting these to max performance.

**Comment by mac1202** [comment]
Thank for your tip the problem was from the crt lottes shader switching to another shader i get the proper framerate for my tv and cracking sound is gone. I dont understand i had always used this shader a didnt have any problem before.
