### ISSUE TITLE
input_exit_emulator = "nul" exits RetroArch when Windows key is pressed

### ISSUE THREAD

**Issue by blackwind** [libretro/RetroArch#2564]
I don't want an exit hotkey, so I set it to "nul". Now, whenever I press the Windows key on my keyboard while RetroArch is focused, it exits. I'm able to reproduce with a new config, and binding input_exit_emulator again restores the correct behavior. This occurs in both v1.2.2 and the latest nightly.

**Comment by glitchninja2000** [comment]
Try putting an invalid value in the .cfg file.
I would try it myself, but I run OSX so it may behave differently.

**Comment by blackwind** [comment]
I tried binding "menu toggle" to btn -1 in retroarch.cfg when I was experimenting with "enable hotkey", and it seems invalid values are a great way to get the program to crash on save. For now, I've set input_exit_emulator to a key there's no danger of me ever pressing, but it'd be great to see a proper fix for this either way.

**Comment by RollingStar** [comment]
Could not reproduce in Retroarch 1.3.0 on Windows 10 x64. http://pastebin.com/HxGHEwPp

`input_exit_emulator = "nul"` is one of the only settings in RetroArch I have changed. Wild guess: are you using consistent line endings? (Windows uses one end of line format and Linux / Mac uses another).

**Comment by blackwind** [comment]
Confirmed still an issue in v1.3.0, and even confirmed with a brand new config. Keep pressing the Windows key until it happens. You might need to manually refocus RetroArch after each press.

I'm using consistent line endings. Windows 10 x64 here as well.

**Comment by RollingStar** [comment]
Still could not reproduce.

1. Started RA in full screen (borderless disabled)
2. Pressed Windows key
3. Clicked on RetroArch window to refocus

I repeated 2&3 around 10-15 times.

Have you tried with my config?

**Comment by blackwind** [comment]
Tracked this down to a compatibility issue with the Keyboard plugin from [EventGhost](http://www.eventghost.org/) (<= v0.4.1r1710). I've gone ahead and rewritten that plugin (ugh, what a mess) and can no longer reproduce the issue, but previously, it blocked presses of the Windows key until it knew what to do with them, and RetroArch is the one and only program I've ever used that apparently doesn't like that.

Note that while it's unlikely you'll get any further reports about this, it still indicates a larger problem with input handling in RetroArch. Whether or not it's worth installing EventGhost and pulling out a debugger is up to you guys -- just know that, while I'm no longer experiencing the symptoms of this issue, it's definitely not resolved.
