### ISSUE TITLE
"Enable hotkeys" should apply only to the corresponding device

### ISSUE THREAD

**Issue by blackwind** [libretro/RetroArch#2565]
In a perfect world, RetroArch would support the binding of key combinations; until then, it'd be great if input_enable_hotkey was distinct from input_enable_hotkey_btn and input_enable_hotkey_axis. If I set input_enable_hotkey_btn to my Xbox controller's guide button, for example, I don't want to have to hold the guide button to then access keyboard bindings. Likewise, if I bind input_enable_hotkey to Shift, I don't want to have to hold Shift to access gamepad bindings.

**Comment by glitchninja2000** [comment]
I never run into this problem.

    input_enable_hotkey = "rshift"
    input_enable_hotkey_btn = "13"
    input_enable_hotkey_axis = "nul"

**Comment by blackwind** [comment]
Apparently this is no longer an issue in nightly. Should've retested before posting.
