### ISSUE TITLE
RetroArch should provide a way to unbind keys

### ISSUE THREAD

**Issue by blackwind** [libretro/RetroArch#2566]
I'm sure this must be a popular request, but I wasn't able to find anything on the issue tracker. In any case, there needs to be a way to remove bindings other than digging into retroarch.cfg. Aside from the Windows key bug (#2564), unbinding keys I've changed my mind about has definitely been the most frustrating part of my RetroArch experience thus far.

**Comment by glitchninja2000** [comment]
I find this frustrating also. It would be nice if clicking on something with the mouse could remove a keybind. Or instead of pressing menu_ok you could press the "y" button, since it has zero use in the menu. It isn't even in the .cfg as a menu_(function)_btn. So I'd like to see in the future a "delete" button option:

    menu_ok_btn = "8"
    menu_cancel_btn = "0"
    menu_delete_btn = "1"
    menu_search_btn = "9"
    menu_info_btn = "2"
    menu_default_btn = "3"
    menu_scroll_down_btn = "11"
    menu_scroll_up_btn = "10"

**Comment by Kivutar** [comment]
Using the start button doesn't reset the binding?

**Comment by fr500** [comment]
it resets to default, doesn't unbind

**Comment by blackwind** [comment]
Start = reset is news to me. I tried all my gamepad buttons when I was trying to unbind "menu toggle" (which was already at its default at the time), so it never occurred to me to run through the buttons again on any other binding. Good to know. Start seems like a weird choice (why not Back?), and this doesn't diminish the need for an unbind key, but good to know.

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/2568
Related

**Comment by abyssonym** [comment]
Being able to unassign the hotkey would be much more useful than resetting it to the default, IMO. But ideally I wouldn't have to manually edit the config file to do either.

**Comment by fr500** [comment]
We have discussed long press "start" to reset.
No decisions yet though.

**Comment by urielsd** [comment]
Was going to report this issue when I found this. Yes, I agree Retroarch should let the user unbind assigned keys

**Comment by Jimmy-Z** [comment]
Still no way to clear, seriously, still have to edit config file manually?

**Comment by fr500** [comment]
yes

**Comment by shinmai** [comment]
And seems in the latest nightlies even the "Start to reset" isn't working, pressing start on a binding just prompts for a new assignment now.

**Comment by twinaphex** [comment]
Hi there,

I implemented this now -

https://github.com/libretro/RetroArch/commit/e75633064a1a17249baa40cb5ee954f11b144001

Press Y button to 'clear'/'unbind'.

**Comment by georaldc** [comment]
Does this apply to the android version as well? On the latest nightly, it looks like hitting X on my Shield Portable does clear out any assigned key, but it still brings back the default "Auto Assigned" value. I was trying to unbind the volume button from opening the menu but I can't seem to unbind auto set inputs.

**Comment by MeisterLLD** [comment]
Works great on the Wii U, didn't know about that ! Great solution :)

**Comment by isugimpy** [comment]
I think there might be a problem with how this is implemented, at least on Linux.  Pressing Y does cause keys to unbind, but if it's a controller button, and you have an autoconfig profile for that controller, instead of going to null, it goes to Auto: <button>.  In this case, I'm trying to unbind the Square and Triangle keys to override my FCEUmm config so there's no Turbo buttons at all, and when I try to unmap them it simply goes to Auto: Square and Auto: Triangle.  I've tried disabling autoconfig, and still got the same result.  Is there something further I might be missing on how this is implemented?

**Comment by Sumea** [comment]
Amazing @twinaphex - somehow you implemented the unbind key but on android it unbinds the keyboard hotkey, I want it to unbind the hotkey from select/back button which you guys KNOW is used by SNES, NES, and I am pretty sure quite many other game systems, while you also provide few combos like L3+R3 which work much better. Android version should not have back - BACK BUTTON ALONE mapped to this feature as it can be highly intrusive to gameplay and you seemed to already figure out few much less intrusive options. Only reason I can think the bind is there is for those USB SNES pads or similar retro USB pads but then you should let user figure out best mapping or shortcut (like L R down Y) or whatever.

And yeah, what @isugimpy said, I agree. 

Well, I am not mad, I am just trying to use a Shield Tablet in awesome way (being portable TV connectable Nin Switch of Emulation, retro games and stuff)

**Comment by MrxBeex** [comment]
Hbbubbub b . I . mbybbbbhbbyhbhvmbnhbhbubbbbynubbhbjby7hbb hbnbubh ubbuuhbb
6bhbnbubbunmhbhbbubjh5bjbhbn the same
buhbbbbubbuhbbuujbhjubjbbbbubgjbbbbyntvbyhhbhbhhbbbumbbuybjhunubbbbbnuj
nbbhmbhjbhb6mubhubhb6vhhnb bb7hubhubbubububbbbhbhbhhbhbjhbnukuum7v . and
this I jkooombmmnjhk and i

**Comment by shinra358** [comment]
Broken. Clears keyboard key but not gamepad key. Also clears the entry below your highlighted selection instead of the highlighted selection.

**Comment by fr500** [comment]
Not broken, it was never meant to clear keys and it's clearing the proper binding here on android and windows

**Comment by fr500** [comment]
Hmmm, actually you might be onto something, it works fine in input hotkey binds, but not on user input binds.

**Comment by fr500** [comment]
It won't clear autoconf binds, that's perfectly fine. If you don't want autoconfs... well disable them. Even if it cleared them for you it would set them AGAIN once content is loaded or you add another gamepad.

I'll fix the offset value. It's hardcoded to 6 and there are 7 entries now

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/pull/5460

**Comment by shinra358** [comment]
when I turn autoconfig off, gamepad no longer works. I also can't use keyboard keys for confirmations.

**Comment by shinra358** [comment]
When I turn autodetect off, controller doesn't work.

**Comment by fr500** [comment]
Obviously,  if you turn autoconfig off you have to configure the pad
manually, that's the whole idea

**Comment by shinra358** [comment]
how, when the controller has no buttons to begin with in order to do that? once upon a time, it never use to work like this. the dpad, confirm, and back buttons should at least be mapped so that it can still be done with a controller.

**Comment by Fredi125** [comment]
Hello guys!

The quick solution I found that did not require manual editing was to bind any key you don't want to use by mistake to the same button as the "Exit" key.
