### ISSUE TITLE
[request] Add menu_delete_btn

### ISSUE THREAD

**Issue by glitchninja2000** [libretro/RetroArch#2568]
In the menu, the button "1"/"y" which is assigned to the 'a' key on a keyboard has no purpose. It would be much quicker to remove keybinds, delete files, and remove cores with the UI; adding a "menu_delete_btn" option to the .cfg files would be handy:

    menu_ok_btn = "8"
    menu_cancel_btn = "0"
    menu_delete_btn = "1"
    menu_search_btn = "9"
    menu_info_btn = "2"
    menu_default_btn = "3"
    menu_scroll_down_btn = "11"
    menu_scroll_up_btn = "10"

**Comment by fr500** [comment]
actually I'm pretty sure X and Y do something, we should make one of those "context aware" to be able to do certain actions depending on the  context

**Comment by fr500** [comment]
Let's discuss this on the related bug above
