### ISSUE TITLE
Regression in dual shock 3 support

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2569]
Looks like a recent change caused a regression in dualshock 3 support: https://github.com/libretro/Lakka/issues/251

**Comment by twinaphex** [comment]
No idea what he is talking about, I can use a DualShock 3 just fine on Arch Linux with RA.

Try testing it yourself, it might be that it is a local problem on his end.

**Comment by Kivutar** [comment]
You're right, I was able to reproduce only on Lakka. I upgraded udev very recently, but didn't rebuild the whole OS. I certainly need to rebuild some packages linked against udev to get all working again.

**Comment by Kivutar** [comment]
It was really a retroarch bug, but you can reproduce it only in KMS mode. I bisected it : 2db119794269fcb98ddaef470afff3e211ea77f8

**Comment by sergiobenrocha2** [comment]
weird, it was working on KMS desktop here.

**Comment by Kivutar** [comment]
We can close this now. The last commit fixes this.
