### ISSUE TITLE
Option to name saves after archive rather than ROM

### ISSUE THREAD

**Issue by blackwind** [libretro/RetroArch#2573]
Currently, switching between different ROM versions is a chore due to the need to rename your save. I personally have never encountered a scenario where saves weren't compatible between different versions, but I'm sure someone will chime in with an edge case, so I won't request this become the default; could we get an option, though, to name saves after the archive rather than the ROM?

States, obviously, are a different beast, and wouldn't apply to such an option.

**Comment by hizzlekizzle** [comment]
I don't think I understand the request. Can you give an example of how it works now vs how you would like it to work?

**Comment by fr500** [comment]
I think he means goodsets.
Goodsets have an structure like this

Terranigma.zip
 |
 | --- Terranigma (US).smc
 | --- Terranigma (EU).smc
 | --- Terranigma (JAP).smc

He wants SRAM to be Terranigma.srm
I think this is awfully specific.

**Comment by blackwind** [comment]
Sorry, shouldn't have assumed everyone uses Goodsets, but @fr500 nailed it. One could make the argument that disabling the "sort saves in folders" option probably causes more issues than it would solve as well (playing the SNES, then the GBA version of the same game, which would have the same filenames in a Goodset = bye-bye saves!), but that's the great thing about options -- those they benefit are glad they're there. As for the option I'm requesting, I would argue this is a very simple one to implement with huge benefits for those who'd use it, making it something of a no-brainer for inclusion. Hopefully someone on the devteam feels the same way.

**Comment by fr500** [comment]
That's the thing, it's not very simple to implement, there are at least 4 codepaths that would need to be modified for this to work:

- Core uses SRAM interface, loading from archive, sort in folders off
- Core uses SRAM interface, loading from archive, sort in folders on
- Core doesn't use SRAM interface, loading from archive, sort in folders off
- Core doesn't use SRAM interface, loading from archive, sort in folders on

It's not just a setting, it's a value that has to change when we load content and there are lots of edge cases with cores that don't implement the SRAM interface but save using their own implementation.

**Comment by blackwind** [comment]
> there are lots of edge cases with cores that don't implement the SRAM interface

That I hadn't considered. In any case, the feature request stands. If it gets implemented at some point, great; if not, well, I tried.

**Comment by fr500** [comment]
Seems like a won't fix, it's way too specific for my taste although it may not be really difficult to implement. Feel free to discuss the idea here
