### ISSUE TITLE
RetroArch throws warning when reading /sys/devices/system/cpu/present / possible

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#2574]
Happens on a Raspberry Pi on Raspbian Jessie - 

Didn't read whole file: /sys/devices/system/cpu/present.
Didn't read whole file: /sys/devices/system/cpu/possible

everything works though.

Something to do with it checking file size and seeing if it read as much as the file size ?

```
# ls -l /sys/devices/system/cpu/present
-r--r--r-- 1 root root 4096 Dec 18 14:13 /sys/devices/system/cpu/present
# cat /sys/devices/system/cpu/present
0-3
```

**Comment by objectchris** [comment]
I get the same thing (on raspian wheezy)

**Comment by vanfanel** [comment]
Same here on Raspbian.

**Comment by twinaphex** [comment]
Everybody with the Linux version gets this. I think for now you can just ignore this warning unless you want to take steps to get rid of the warning.

**Comment by fr500** [comment]
I think it's fixed, reopen if it's not

**Comment by objectchris** [comment]
it is fixed now! awesome thanks :)
