### ISSUE TITLE
Overlay scale doesn't stay bound to edges

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#2575]
When I scale the overlay I would expect the buttons to stick to their respective edges and just shrink. Adjusting the scale makes them scrunch towards the center of the screen. Is it possible to edit the overlay manually and achieve this?

![oenpejd](https://cloud.githubusercontent.com/assets/841440/11916365/d4573e5c-a6a1-11e5-86ec-d4b823f34a9f.png)

**Comment by sergiobenrocha2** [comment]
For what resolution you need this overlay?

**Comment by sergiobenrocha2** [comment]
It's possible to edit manually yeah.

These flat overlays are optimized for smartphones, I'm using a S4 mini for reference, 4.3", 960x540 pixels. It should work for bigger screen like 5.1" from S5 I guess (with the "B" overlays, which have smaller buttons).

I'll need to make new overlays for tablets (>= 7") I guess. Give me your specs, I can try make a new one for you. Or you can try edit it: https://github.com/libretro/common-overlays/blob/master/gamepads/flat/retropad-fast.cfg

The coords are normalized, so you'll have to get the position in pixels you want and divide by your resolution (1368x768 ?).

**Comment by parkerlreed** [comment]
Yeah it's a 10.1" tablet at 1366x768.

**Comment by fr500** [comment]
This is working as intended so this is more like a feature request than a bug

**Comment by parkerlreed** [comment]
I think this can be closed as the auto scale seems to work as expected (and I don't see a manual overlay scale option)
