### ISSUE TITLE
When loading zip roms, retroarch leaves temporary files around

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#2588]
When loading zipped roms, Retroarch extracts them to the rom folder, and then does not always delete the extracted roms afterwards.

A suggested remedy would be to extract the roms to memory instead of disc, as all other emulators do.

**Comment by sergiobenrocha2** [comment]
If you are at Linux, change the Settings Tab --> Directory --> Cache Dir to /tmp
