### ISSUE TITLE
Visual C++ "runtime terminated in an unusual way" error for Mednafen PSX

### ISSUE THREAD

**Issue by plusfuture** [libretro/RetroArch#2589]
I am specifically using the 1.3.0 build with the Mednafen PSX core downloaded via the RetroArch GUI. I have placed three requisite bios files for Mednafen (MD5 checksum confirmed) in the `bios` subfolder in the RetroArch directory.

The crash happens immediately upon attempting to run a `.cue` file in the same directory as the `.bin`. I have confirmed that there is no directory listed in the `.cue` file; instead, it is simply the filename of the `.bin` file.

What can explain this error?

**Comment by fr500** [comment]
Please open this in the correct repository 
https://github.com/libretro/beetle-psx-libretro/
