### ISSUE TITLE
RA gets unresponsive if unplug joypads on Odroid U3

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2597]
RA gets unresponsive if I unplug joypads on Odroid U3 and exit RA with ESC, it stuck the desktop and I can't even switch the tty.I notice the fps continues to run.

I can do a bisect later.

@Kivutar is it happening with lakka?

**Comment by Kivutar** [comment]
I didn't noticed it with Lakka. You're using X? Does it also happen in fbdev?

**Comment by sergiobenrocha2** [comment]
Yeah, I'm using X. I didn't test fbdev yet.

**Comment by sergiobenrocha2** [comment]
It's odroid fault. I was playing super mario 64, had some bad connection in the joypad (connect in and connect out many times), then ban! It stuck all my USB devices, none of them are responding. Even the "ANALOG" red led from the joypad is not responding, nor my keyboard/touchpad.
