### ISSUE TITLE
Open Archive as Folder should not have ".."

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2604]
Open Archive as Folder should not have ".." , there's no above directory at all in a zipped rom. Try select it and you'll stuck at the same place.

**Comment by orbea** [comment]
I can confirm this is still a problem with the master.

**Comment by bparker06** [comment]
@orbea I cannot reproduce... can you provide some steps? I've never seen ".." inside a zipped file.

**Comment by orbea** [comment]
@bparker06 It now shows `Parent Directory` where it used to be `..`. Regardless the problem remains the same.

To reproduce:

1. `Load Content`
2. Navigate to a directory containing compressed content.
3. Select `content.zip`.
4. `Browse Archive`.
5. Select `Parent Directory`.

However I think I have a working solution, let me test it more and then I'll make a PR or share it here.

**Comment by orbea** [comment]
@bparker06 I made a PR to resolve this, I would appreciate if you could review it.

https://github.com/libretro/RetroArch/pull/7826
