### ISSUE TITLE
Strange screen when "Load RetroArch" is tapped

### ISSUE THREAD

**Issue by DarnedUrchin** [libretro/RetroArch#2606]
Hello, I am on Android Ice-Cream Sandwich. When "Load RetroArch is tapped, it shows "1.2.2 - No Core" in the bottom-left hand side and the date in the bottom-right, and random white pixels around the top that are probably words that have been cut off. After a few seconds it goes back to the Load/Quit RetroArch menu. Is there anyway to solve this?

Tablet: Sony Tablet S

**Comment by fr500** [comment]
Is this still happening? if so please reopen
