### ISSUE TITLE
[Linux Raspberry Pi] Build fail gfx/drivers/sdl_gfx.c: In function ‘sdl_gfx_set_handles’

### ISSUE THREAD

**Issue by joaodriessen** [libretro/RetroArch#2609]
Building 1.2.2.3433a515-1 with ./configure --prefix=/usr --enable-neon --enable-dispmanx --enable-floathard --enable-udev

gfx/drivers/sdl_gfx.c: In function ‘sdl_gfx_set_handles’:
gfx/drivers/sdl_gfx.c:236:44: error: ‘SDL_SysWMinfo {aka struct SDL_SysWMinfo}’ has no member named ‘info’
    video_driver_display_set((uintptr_t)info.info.x11.display);
                                            ^
gfx/drivers/sdl_gfx.c:237:43: error: ‘SDL_SysWMinfo {aka struct SDL_SysWMinfo}’ has no member named ‘info’
    video_driver_window_set((uintptr_t)info.info.x11.window);
                                           ^
Makefile:126: recipe for target 'obj-unix/gfx/drivers/sdl_gfx.o' failed
make: *** [obj-unix/gfx/drivers/sdl_gfx.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by fr500** [comment]
Reopen if the issue is still there
