### ISSUE TITLE
Can't open from Command Line directly to rom [OSX][RetroArch 1.2.2]

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#2610]
The instructions for using Command Line with RetroArch seem to not work for 1.2.2 on OSX. 

I've tried going directly into the RetroArch.app/Contents/MacOS directory and then running the following:

```
Mac-mini:MacOS futurepr0n$ ./RetroArch -L /Applications/RetroArch%202.app/Contents/Resources/cores/picodrive_libretro.dylib  /Users/futurepr0n/Emulation/ROMs/Genesis/Beavis\ and\ Butt-head\ \(U\)\ \[\!\].gen 
```

But this didn't do the trick, it just loads up RetroArch and I have to select a core, and load the rom manually. I then tried to use a config that I saved with the PicoDrive core already loaded and tried to run it from Terminal:

```
Mac-mini:MacOS futurepr0n$ ./RetroArch --config /Applications/RetroArch%202.app/Contents/Resources/configs/picodrive_libretro.cfg -L /Applications/RetroArch%202.app/Contents/Resources/cores/picodrive_libretro.dylib /Users/futurepr0n/Emulation/ROMs/Genesis/Beavis\ and\ Butt-head\ \(U\)\ \[\!\].gen 
```

Nodda.. 

Is there a way to get a Rom to open directly from Terminal/CommandLine? 
# 

Update, realised that in the settings I was able to see Command Interface was not supported for my Version. I guess I will need to look elsewhere! Thank you for the hard work, love libretro and RetroArch!

**Comment by frranck** [comment]
Hi, same problem for me,  how do you load core from the command line with the latest version ?

**Comment by futurepr0n** [comment]
Unfortunately command line launch is not a feature available to osx users. So we are boned when it comes to that

**Comment by frranck** [comment]
@futurepr0n There must a be a different front end for developers, that's really not convenient for developing...

**Comment by Alcaro** [comment]
No, there is no alternate libretro frontend for developers. Most of us are on Linux.

But yes, this is a valid bug report. I'm reopening it.

**Comment by morgangiraud** [comment]
Hi,

Just discover this thread.
I'm using command line launching on OSX and it works so far.
I'm using this line:
`cd /Applications/RetroArch.app/Contents/MacOS && ./RetroArch -L ../Resources/cores/mycore_libretro.dylib  ~/Library/Application\ Support/RetroArch/downloads/my-game.zip`

**Comment by orbea** [comment]
Given the above report of how it works and the lack of activity I am going to close this, please let us know if this is mistaken.
