### ISSUE TITLE
Hitting ENTER in KMS quits RetroArch

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2613]
Tested on Arch Linux, with a blank config, and many cores.
Tested on Lakka for PC too.

Happens only with keyboard.

**Comment by twinaphex** [comment]
This should be fixed now:

https://github.com/libretro/RetroArch/commit/ef7a786527d5da6208ff5236f4c040972792b1c2

**Comment by Kivutar** [comment]
I confirm that the bug is fixed.
