### ISSUE TITLE
Steam Controller Support

### ISSUE THREAD

**Issue by Aidoboy** [libretro/RetroArch#2615]
I saw another issue about this, but it was dismissed because the Steam Controller supports XInput. Hover, the steam controller actually has 2 extra buttons on the back and a gyro over typical controllers, and the D-Pad and left joystick are also touchpads. I think Retroarch could really take advantage of these.

**Comment by fr500** [comment]
If the inputs are dinput buttons it should work just fine in dinput mode

**Comment by RobLoach** [comment]
Without Steam running, I believe we may need the [Standalone Steam Controller Driver](https://github.com/ynsta/steamcontroller). I have a Steam controller handy, may try this out.

**Comment by fr500** [comment]
The user didn't even state his platform.

**Comment by Aidoboy** [comment]
I didn't think it was relevant at the time.

It's Windows.

**Comment by Ferk** [comment]
You can configure the 2 extra buttons on the back and the gyro to send any keyboard event. Just like any other Steam Controller supported game or app.

This is already done by the driver (and by Steam). Just launch Retroarch from within Steam in Windows and set up a configuration layout like the rest of the Steam games.

**Comment by Aidoboy** [comment]
You can only get so far with the configurator like that.

Funnily enough, a dev posted an article about why using Steam Configurator support is good a few days ago: http://www.gamasutra.com/blogs/LarsDoucet/20170125/289904/The_Steam_Controller_Configurators_Untapped_Power.php

**Comment by RobLoach** [comment]
@fr500 The problem is that the Steam Controller doesn't work in RetroArch, unless yodu're running Steam in the background. When you're running RetroArch from Steam, you have the ability to change the way the controller behaves.

Without Steam, I've tested with https://github.com/kozec/sc-controller and it worked well. Still needs some tweaking, but it is a good alternative to running Steam.
