### ISSUE TITLE
retroarch not building with --enable-mali_fbdev on ubuntu 14.04

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#2619]
odroid-c1 - ubuntu 14.04 downloaded from http://odroid.in/ubuntu_14.04lts/ubuntu-14.04.3lts-lubuntu-odroid-c1-20151020.img.xz

I have the odroid package mali-fbdev installed (v20151015-r5p0-31d5c21-17)

configuring with

```
./configure --disable-x11 --disable-ffmpeg --disable-oss --disable-pulse --disable-al --disable-jack --enable-floathard --enable-mali_fbdev --enable-gles --enable-sdl2 --enable-neon
```

```
gfx/drivers_context/mali_fbdev_ctx.c:35:30: error: field ‘native_window’ has incomplete type
    struct mali_native_window native_window;
make: *** [obj-unix/gfx/drivers_context/mali_fbdev_ctx.o] Error 1
```

6f5d09b2359ae788f8e06e692c0ab46c4b914804 seems to be the cause from #2567 - @Kivutar - do you know if this due to a mali-fbdev related include change or something ?

reverting 6f5d09b2359ae788f8e06e692c0ab46c4b914804 allows it to build.

**Comment by Kivutar** [comment]
Hello @joolswills 

It depends on the mali headers you are using. On Allwinner platforms like the Cubieboard/Cubietruck/BananaPi/OrangePi and on the OdroidXU3 they all use the sunxi headers.

On OdroidC1, the headers are differents. Fix it on one platform, it breaks on another :(

So in Lakka, I let the source of RA untouched for Allwinner and XU3, which are very widely used. And I apply this patch https://github.com/libretro/Lakka/blob/lakka/projects/OdroidC1/patches/retroarch/retroarch-02-fix-mali-fbdev.patch for the C1.

But maybe that anybody who knows C better than me could find a patch to make it work in any circumstances.

**Comment by fr500** [comment]
As far as I understand this is not a bug in RetroArch, feel free to discuss the issue here.

**Comment by joolswills** [comment]
@Kivutar sorry - missed your reply before - thanks very much for the info.
