### ISSUE TITLE
Bad Video Quality

### ISSUE THREAD

**Issue by michael2256** [libretro/RetroArch#2620]
Are there any plans to add support for GPU and video settings to improve the graphics? Like set 1080p upscaling, anti aliasing, texture smoothing etc? I've tried using the shaders but they don't have much effect. These options are in the standalone version of the emulators. Will these same features make it to the retroarch/libretro version?

**Comment by Kivutar** [comment]
These features already exist. You can tweak the aspect ratio of the output, enable the hardware biliear filter, or use shaders like XBR.

**Comment by michael2256** [comment]
Is there a guide on shaders that you know of that explains what each one is and how to use them? I've never used shaders before and I havn't got the sweetest clue what the abbreviations mean.

**Comment by michael2256** [comment]
BTW all you developers of this project are doing an awesome job and I hope to see even more cores added and more features. This is the best thing going for emulation.

**Comment by Kivutar** [comment]
As far as I know, they are no complete guides.

I suggest you to try the **CRT** shaders, that will look like old TVs.

You can try the **XBR** shaders that will look smooth.

And **border** shaders will look like the borders of handheld consoles like the GameBoy or the PSP.

**Comment by hizzlekizzle** [comment]
The ps1 cores we use don't do hardware accelerated rendering, which is where you get things like 1080p internal resolution and texture smoothing. PCSX-ReARMed--which is only available on ARM devices--can do double internal res but mednafen/beetle-psx--which is what you would use on x86/64--is confined to native resolution.

PPSSPP-libretro, for example, does have those options and you can set them from the 'core options' menu.

**Comment by michael2256** [comment]
thanks guys
