### ISSUE TITLE
Per-Core Configuration not honored

### ISSUE THREAD

**Issue by yahreen** [libretro/RetroArch#2625]
I am having an issue with a fresh install of 1.3.0. on Windows x64 where setting "Configuration Per-Core" is not being honored.

Steps to reproduce:

Create a new 1.3.0 install
Set "Configuration Per-Core" to "On"
Create two folders in your "roms" directory called `core-1-roms` and `core-2-roms` with roms for 2 respective cores.

Download a core (`Core 1`).
Go to "Settings > Directory" and set file path to `core-1-roms`
Load a content file to ensure core is working
Press F1 to open menu, select "Close Content"

Back at main menu, repeat steps above with a new core, `Core 2`.
Make sure to set a separate path to `core-2-roms`.
Start `Core 2` with a file to make sure it works.
Use F1 to return to menu, select "Close Content".

Now load `Core 1` again.
Select "Load content"
Note the files that are referenced.

The result for me is the file path associated with `Core 2` are now associated with `Core 1`, despite having "Configuration Per-Core" set to "On".

I am using 4DO and Yabause.

**Comment by fr500** [comment]
Can you try other settings?
Some settings are just hard to do per-core but I'm fairly certain that most
work. Maybe this particular setting doesn't

**Comment by yahreen** [comment]
Nothing appears to save, it's odd.

If I navigate to `/config/4do_libretro.dll.cfg`, I see `rgui_browser_directory = "C:\Emu\Roms\3DO"` which is correct.

But When I load the 4DO core, it defaults to the last value I set in the GUI, which in this case is Yabause (`rgui_browser_directory = "C:\Emu\Roms\Saturn`). That is also the value saved in `retroarch.cfg`.

**Comment by fr500** [comment]
if this is still happening, please reopen
