### ISSUE TITLE
Building retroarch in cubian

### ISSUE THREAD

**Issue by Archangl7** [libretro/RetroArch#2626]
I cant get it to build using cubian x1. I started by using a preconfigured sd card image, and after the installation on sd card, ran apt-get install gcc so i can compile, and then...
 git clone git://github.com/libretro/libretro-super.git
cd libretro-super
./libretro-fetch.sh

when i run ./retroarch-build.sh i get to this message:
CC gfx/common/egl_common.c
In file included from gfx/common/egl_common.c:20:0:
gfx/common/egl_common.h:21:21: fatal error: EGL/egl.h: No such file or directory
compilation terminated.
CC deps/7zip/7zIn.c
make: **\* [obj-unix/gfx/common/egl_common.o] Error 1
make: **\* Waiting for unfinished jobs....
Failed to build RetroArch
cubie@Cubian:~/Desktop/libretro-super$

i also tired adding  sudo apt-get install pkg-config libc6-dev libpulse-dev libsdl2-dev libxml2-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libv4l-dev x11proto-xext-dev libxxf86vm-dev libxinerama-dev libudev-dev libasound2-dev libxv-dev libopenal-dev libfreetype6-dev libgbm-dev libdrm-dev libegl1-mesa-dev libopenvg1-mesa-dev python3-dev zlib1g-dev python3
but that seemed to make it worse with wayland.h not being configured. Sorry, i dont know enough to get this working.

**Comment by fr500** [comment]
try building it normally I guess
cd retroarch
./configure
make

**Comment by Archangl7** [comment]
Doesn't retroarch-build.Sh do that already?


Sent from my Sprint Samsung Galaxy Note5.-------- Original message --------From: Andrés <notifications@github.com> Date: 1/7/2016  4:53 PM  (GMT-05:00) To: libretro/RetroArch <RetroArch@noreply.github.com> Cc: Archangl7 <michael@respectablepcservices.com> Subject: Re: [RetroArch] Building retroarch in cubian (#2626) 
try building it normally I guess

cd retroarch

./configure

make

**Comment by fr500** [comment]
It doesn't run configure

**Comment by Archangl7** [comment]
ok, tried that got a similar error. This time i only downloaded retroarch by itself on a clean sd card

CC gfx/drivers_shader/shader_null.c
In file included from ./libretro-common/include/glsym/rglgen.h:30:0,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from gfx/drivers_shader/../common/gl_common.h:26,
                 from gfx/drivers_shader/shader_null.c:34:
./libretro-common/include/glsym/rglgen_headers.h:27:21: fatal error: EGL/egl.h: No such file or directory
compilation terminated.
make: *** [obj-unix/gfx/drivers_shader/shader_null.o] Error 1

**Comment by fr500** [comment]
You are missing EGL headers that you need to build on your platform

**Comment by Archangl7** [comment]
i did install the requirements for retroarch from the page https://github.com/libretro/RetroArch instead of using https://github.com/libretro/libretro-super.
i have found egl.h from mesa pages. Im such a noob though in this regard.
I dont know where to put/install it

**Comment by Archangl7** [comment]
ok, i got the egl.h installed now the errors are these:

CC cheevos.c
CC libretro-common/utils/md5.c
LD retroarch
obj-unix/gfx/common/egl_common.o: In function `egl_report_error':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:34: undefined reference to `eglGetError'
obj-unix/gfx/common/egl_common.o: In function `egl_destroy':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:82: undefined reference to `eglMakeCurrent'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:85: undefined reference to `eglDestroyContext'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:88: undefined reference to `eglDestroyContext'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:91: undefined reference to `eglDestroySurface'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:92: undefined reference to `eglTerminate'
obj-unix/gfx/common/egl_common.o: In function `egl_set_swap_interval':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:145: undefined reference to `eglGetCurrentContext'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:149: undefined reference to `eglSwapInterval'
obj-unix/gfx/common/egl_common.o: In function `egl_report_error':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:34: undefined reference to `eglGetError'
obj-unix/gfx/common/egl_common.o: In function `egl_get_video_size':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:167: undefined reference to `eglQuerySurface'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:168: undefined reference to `eglQuerySurface'
obj-unix/gfx/common/egl_common.o: In function `egl_init_context':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:197: undefined reference to `eglGetDisplay'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:204: undefined reference to `eglInitialize'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:209: undefined reference to `eglChooseConfig'
obj-unix/gfx/common/egl_common.o: In function `egl_create_context':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:222: undefined reference to `eglCreateContext'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:231: undefined reference to `eglCreateContext'
obj-unix/gfx/common/egl_common.o: In function `egl_create_surface':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:245: undefined reference to `eglCreateWindowSurface'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:251: undefined reference to `eglMakeCurrent'
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:254: undefined reference to `eglGetCurrentContext'
obj-unix/gfx/common/egl_common.o: In function `egl_get_native_visual_id':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:262: undefined reference to `eglGetConfigAttrib'
obj-unix/gfx/common/egl_common.o: In function `egl_get_proc_address':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:64: undefined reference to `eglGetProcAddress'
obj-unix/gfx/common/egl_common.o: In function `egl_bind_hw_render':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:119: undefined reference to `eglMakeCurrent'
obj-unix/gfx/common/egl_common.o: In function `egl_swap_buffers':
/home/cubie/Desktop/RetroArch/gfx/common/egl_common.c:131: undefined reference to `eglSwapBuffers'
collect2: ld returned 1 exit status
make: *** [retroarch] Error 1
cubie@Cubian:~/Desktop/RetroArch$

**Comment by Archangl7** [comment]
Ok, so i got a little further. I decided to switch versions of the debian distro. I am now using cubieez, and to my suprise both retroarch and emulationstation compiled without errors first try with the recommended libraries. However, it does give me a couple errors when i try to launch either. Retroarch opens a window but is supper slow. the error is  "ligl error: unable to load driver : mali_drm_dri.so" if found some info on this site as well as others http://forum.lemaker.org/thread-3432-1-1.html. Do you think it relates to fb drivers being needed instead of x11 drivers?

**Comment by orbea** [comment]
This sounds like a distro problem or a problem with your specific install. Given the lack of activity I am going to close this, please complain if you can still reproduce this with a fully upgraded OS / RetroArch.
