### ISSUE TITLE
Don't Automatically Start A Core - Ignored

### ISSUE THREAD

**Issue by CrispyXUK** [libretro/RetroArch#2628]
Using the latest nightly (1.3.0) this setting is ignored, next boot will load previously used core.

**Comment by fr500** [comment]
That's totally unrelated, that setting is for "gameless cores"

**Comment by CrispyXUK** [comment]
Oh, apologies.  So I assume tetrarch will always load the core loaded on previous exit then?

**Comment by fr500** [comment]
yeah on some platforms, it's not really loaded into memory, it's just peeked for the name and the supported extensions. I agree it would be good if it wasn't loaded at all.

**Comment by jvook** [comment]
This is causing me major headaches on input configuration across multiple cores with "per-core-configuratrion" set to on.  It is loading input config from the last used core on startup instead of the defaults in retroarch.cfg

**Comment by fr500** [comment]
Yes, actually I fixed this today but it was reverted since we think there was a reason for us to re-enable this.
Maybe on consoles or something I don't remember, I'm all up for removing it but I think we need more testing first.

**Comment by twinaphex** [comment]
Go ahead and make the change I guess, I will just deal with any potential issues that might pop up on the console side.

**Comment by fr500** [comment]
ok, I'll readd this

**Comment by orbea** [comment]
@fr500 Was this fixed?

**Comment by fr500** [comment]
it was more of a behavioral change, yeah I think you can close it
