### ISSUE TITLE
--config broken in Windows nightly

### ISSUE THREAD

**Issue by blackwind** [libretro/RetroArch#2629]
Currently, passing --config on the command-line appears to do nothing in Windows. With retroarch.exe, the process starts and quickly exits. With retroarch_debug.exe, it immediately crashes. Yes, I'm using a valid path to a valid config file.

**Comment by fr500** [comment]
It works for me, that's how I havr launched since 1.0.0.3

**Comment by blackwind** [comment]
retroarch.exe --config C:\Emulation\RetroArch\user\retroarch.cfg
    retroarch.exe --config C:/Emulation/RetroArch/user/retroarch.cfg
    retroarch.exe --config user\retroarch.cfg
    retroarch.exe --config user/retroarch.cfg
    retroarch.exe --config .\user\retroarch.cfg
    retroarch.exe --config ./user/retroarch.cfg
    retroarch.exe --config "C:\Emulation\RetroArch\user\retroarch.cfg"
    retroarch.exe --config "C:/Emulation/RetroArch/user/retroarch.cfg"
    retroarch.exe --config "user\retroarch.cfg"
    retroarch.exe --config "user/retroarch.cfg"
    retroarch.exe --config ".\user\retroarch.cfg"
    retroarch.exe --config "./user/retroarch.cfg"

For me, none of the above work.

**Comment by fr500** [comment]
This is how I've launched RA for a year at least
D:\Games\Emulators\RetroArch\retroarch.exe --config
config\windows\retroarch.cfg  --menu --verbose --log-file retroarch.log

**Comment by blackwind** [comment]
Alright, so, it works if I include --menu. --help says the following about --menu:

> Do not require content or libretro core to be loaded, starts directly in menu. If no arguments are passed to program, it is equivalent to using --menu as only argument.

Wouldn't a saner way to handle this be to always imply --menu when content isn't passed?

**Comment by fr500** [comment]
I don't know, I like the current way

**Comment by blackwind** [comment]
Doesn't it stand to reason, though, that if I only pass --config user\retroarch.cfg, I probably don't want RetroArch to open and then immediately close?

If you're not willing to alter this questionable behavior, at minimum, the [wiki](https://github.com/libretro/RetroArch/wiki/Using-the-command-line) should be updated to mention the need for --menu when passing --config. As someone who isn't a RetroArch developer, I'm not familiar with all the ins and outs of the system -- I just pop what I want to accomplish into Google, and I follow the instructions that come up. In this case, those instructions were incomplete.

**Comment by fr500** [comment]
It's quite simple, it's from time it was cli driven.
This is a community project, of people working on their spare time, the wiki is public although I think registration is broken, I'm not sure but we can always use more hands.

**Comment by blackwind** [comment]
I've gone ahead and updated the wiki.

**Comment by twinaphex** [comment]
What's the status of this issue now? Can this be closed, does something still remain to be done, etc?

**Comment by blackwind** [comment]
Technically, --config isn't broken as I had thought, but this probably won't be the last time you see a bug report like this until something is done about --menu. Should I open another issue for that so you can close this one? Or is user experience not a priority at this time?

**Comment by twinaphex** [comment]
I'd rather you push a pull request to be honest with you so we can get another issue closed and so that I can move onto other things that are far higher on the priority list.

**Comment by blackwind** [comment]
Fair enough. Go ahead and close this issue, and I'll see if I can throw together a few pull requests in a month or two when I have more time.
