### ISSUE TITLE
glslp gba border shader presets (hunterk) have wrong screen size

### ISSUE THREAD

**Issue by pepedopolous** [libretro/RetroArch#2631]
I'm trying to use all the nice shaders but want to run in KMS mode so cg shaders aren't available. I'm on Arch Linux with Intel HD graphics.

The preset gba_4x.cgp looks fantastic "~/.config/retroarch/shaders/shaders_cg/handheld/console-border/dmg-4x.cgp"
![24268365085_91ccf51595_z](https://cloud.githubusercontent.com/assets/16622246/12215802/ed8a42c2-b6cb-11e5-8c1a-46e13ed097d2.jpg)

But the glslp version has the wrong size "~/.config/retroarch/shaders/shaders_glsl/hunterk/handheld/console-border/dmg-4x.glslp"
![23641556233_4f74539f24_z](https://cloud.githubusercontent.com/assets/16622246/12215804/092595e0-b6cc-11e5-8859-1df340dd6245.jpg)

As does the 5x version

![23641562653_2d50e61528_z](https://cloud.githubusercontent.com/assets/16622246/12215806/1579ee54-b6cc-11e5-8125-068fe16e4484.jpg)

**Comment by hizzlekizzle** [comment]
Ah, yeah, I missed the video_scale parameter in that one. It should be fixed in git now but I'm not sure how long it'll take to trickle down to the online updater.

You can fetch it manually from my repo at https://github.com/hizzlekizzle/glsl-shaders

**Comment by pepedopolous** [comment]
Wow, that was quick! Thanks. Works perfectly as far as I can see. So why not out these in the main folder instead of the hunterk one?

**Comment by hizzlekizzle** [comment]
Glad to hear it's working :)

Yeah, I don't suppose there's any reason to keep the others around. I'll talk to @fr500 about just copying those into the main folder and overwriting the non-parameterized ones instead of the current process.
