### ISSUE TITLE
Bluetooth controller support, iOS 9

### ISSUE THREAD

**Issue by moeiscool** [libretro/RetroArch#2632]
After updating from iOS 8, support for controllers had been lost

**Comment by twinaphex** [comment]
We support only MFi gamepads for now, although BTStack support might be coming back and working again.

**Comment by Hanterdro** [comment]
iCade for the upcoming AppleTV release would be great (8bitdo controllers :-) )

**Comment by t-paul** [comment]
Both 8bitdo zero and 8bitdo sfc39 work fine in iCade mode on non-jailbroken iPhone6 (iOS 9.2.1) and the latest dev version of RetroArch.

**Comment by Hanterdro** [comment]
nice, than I have hope for the AppleTV Version. :-)

**Comment by kiwanowski** [comment]
+1 for the btstack support
