### ISSUE TITLE
Wrong Gamepad Binding Settings

### ISSUE THREAD

**Issue by cra0zy** [libretro/RetroArch#2633]
So, while binding gamepad you provide information like:
 - [B button (down)]
 - [Y button (left)]
 - [A button (right)]
 - [X button (top)]

But this information is wrong because:
 - B is right
 - Y is top
 - A is down
 - X is left

This creates a problem, where if you bind it by the way it says PPSSPP will work correctly, but something like Nestopia won't work, that is the controls will be messed up, and the menu would use b for select and a for back, while if you bind it the way bellow, reverse happens, Nestopia works correctly while PPSSPP has messed up controls.

Tested with Nightly and Stable. I don't mind building from source if this has been fixed.

**Comment by sergiobenrocha2** [comment]
It's right: http://wiki.libretro.com/index.php?title=RetroPad

"In terms of button layout and functionality, the RetroPad is based on a PlayStation/Super Nintendo joypad." i.e., A is in the right and B is down.

**Comment by cra0zy** [comment]
Oh, I see what you did there... my mistake...
