### ISSUE TITLE
"Select File and Detect Core" from the Command Line

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#2634]
When running RetroArch from the command line, you can pass `-L /path/to/core.so` to tell RetroArch which libretro core to use. An example of this would be with the SNES9x core:

```
retroarch -L "/usr/lib/libretro/snes9x_next_libretro.so" path/to/file.zip
```

It would be nice if there as an option for `-L` to tell it to detect the core, much how the menu gives you that option:

![selectfiledetectcore](https://cloud.githubusercontent.com/assets/25086/12226321/276fd296-b7e8-11e5-925f-ad21bf1d35b7.png)

```
retroarch -L "detect" path/to/file.zip
```

Or use the detect method when `-L` is not provided.

**Comment by RobLoach** [comment]
```
retroarch path/to/file.zip
```

Should detect the core, and launch the file.

**Comment by Ferk** [comment]
This would be the best command line improvement.
Though it's a duplicate of #746 (and #1704)

**Comment by RobLoach** [comment]
Thanks, closing in light of https://github.com/libretro/RetroArch/issues/746 .
