### ISSUE TITLE
Forum is not functional

### ISSUE THREAD

**Issue by xantari** [libretro/RetroArch#2638]
The Libretro forum is not functioning. No emails on account registration or forgot password are emailing.

Tried several email vendors.

This means that no one is able to get their verification link to post to the forum.

Please fix, and re-send all the verification links users have not received.

Here is the forum link I am refering too: http://libretro.com/forums/forum.php

**Comment by fr500** [comment]
This is a place for developers to discuss development issues

**Comment by xantari** [comment]
WHere would one go to discuss non functional forum issues?

**Comment by fr500** [comment]
the comment section, twitter, reddit, whatever but here
also I know about these, I don't have time now.
