### ISSUE TITLE
There is a bug in the recently added keyboard support in the Android version

### ISSUE THREAD

**Issue by diablodiab** [libretro/RetroArch#2640]
There is a bug in the keyboard support functionality added to the Android version that crashes Retroarch after about 45 keystrokes on the keyboard. I'll find a solution to this, but this is just a heads up to those who might be wondering.

I have keyboard support fully working in a different implementation where I've completed several SCI games, so it is doable, but it is difficult to combine with the current implementation of how gamepad consisting of more than one device is handled.

**Comment by twinaphex** [comment]
@diablodiab What is the status of this issue? Was it resolved or is it still ongoing?

**Comment by diablodiab** [comment]
It is resolved.
