### ISSUE TITLE
Retroarch is slow only when launched from big picture mode. It works fine and fast from steamos desktop.

### ISSUE THREAD

**Issue by aaronbond** [libretro/RetroArch#2643]
Retroarch and its emulators run horribly slow when launched via the steamOS big picture mode, but when launched from the Desktop mode they run full speed. this is true of the retroarch menu and of the emulation itself.

This may be something to do with steam overlay? retroarch itself uses a kind of overlay. or perhaps the way retroarch does video / monitor syncing.

I have checked the framerate to confirm this issue.

My system: i7 960 8GB RAM AMD 7790 2GB GPU

this is crossposted in the steamOS issue tracker here:

https://github.com/ValveSoftware/SteamOS/issues/466

**Comment by fr500** [comment]
RetroArch doesn't use an overlay like steam, steam intercepts the calls and stuff like that, RA's menu and overlays are native.

I've seen something similar on windows, does it fix after alt-tabbing?

**Comment by aaronbond** [comment]
I'm not sure steamOS does alt-tabbing or anything similar (which is what i'm using) i've tried things like restarting, rebooting, settings.

**Comment by fr500** [comment]
you can't press alt-tab to switch to another app and then back?

**Comment by aaronbond** [comment]
steamOS boots into steam big picture mode, it's a debian distro designed for couch use with a controller. it has a desktop mode (if you enable it) for doing some more advanced stuff, it just drops you into gnome.

In the desktop mode retroarch runs perfectly, however within the steam launcher which runs under a different X instance (is that the correct term? ctrl alt f8 is steamOS and f7 is your normal gnome desktop)

**Comment by RobLoach** [comment]
Which video driver are you using? I've found some faster than others.

**Comment by fr500** [comment]
any more light into this?
maybe it's steam hogging resources?

**Comment by RobLoach** [comment]
Also, try changing the Frame Throttling to 1.0x. I've found RetroArch can slow down background processes if set to anything else. Depends on your system, I suppose.

**Comment by aaronbond** [comment]
I was using AMD drivers (i realise they're the worst on linux) so it could have been the culprit.

as retroarch was the point of my tv machine, i moved away from steamOS to windows and launching big picture mode on boot. running retroarch works fine now.

i noticed there's been an update to steamOS so i will experiment with it when i get the chance.

**Comment by fr500** [comment]
Closed due no further reports or information
