### ISSUE TITLE
[glui] menu colour settings are ignored and produce a segmentation fault on change

### ISSUE THREAD

**Issue by BrainDamage** [libretro/RetroArch#2650]
glui menu colour settings are ignored and produce a segmentation fault on change from the menu itself
tested on both android and linux, same behaviour, version 1.3 for linux, today's buildbot for android
stacktrace on the segfault:

>Program received signal SIGSEGV, Segmentation fault.
>0x0000555555615496 in menu_input_st_hex_callback (userdata=<optimized out>, str=0x5555568d21a0 "0000000") at menu/menu_input.c:369
>(gdb) bt
>0  0x0000555555615496 in menu_input_st_hex_callback (userdata=<optimized out>, str=0x5555568d21a0 "0000000") at menu/menu_input.c:369
>1  0x000055555557f87a in input_keyboard_line_event (state=0x555556c47310, character=<optimized out>) at input/input_keyboard.c:121
>2  0x000055555557fb1f in input_keyboard_event (down=down@entry=true, code=13, character=<optimized out>, mod=mod@entry=0, device=device@entry=3) at input/input_keyboard.c:271
>3  0x000055555565478d in x11_handle_key_event (event=event@entry=0x7fffffffd6d0, ic=<optimized out>, filter=<optimized out>) at input/drivers_keyboard/keyboard_event_x11.c:82
>4  0x0000555555653ed8 in x11_alive (data=data@entry=0x555555bbe8e0) at gfx/common/x11_common.c:434
>5  0x0000555555653fdc in x11_check_window (data=0x555555bbe8e0, quit=0x7fffffffd8ee, resize=0x7fffffffd8ef, width=0x7fffffffd8f0, height=0x7fffffffd8f4, frame_count=<optimized out>)
    at gfx/common/x11_common.c:457
>6  0x000055555565c07d in gfx_ctx_check_window (quit=quit@entry=0x7fffffffd8ee, resize=resize@entry=0x7fffffffd8ef, width=width@entry=0x7fffffffd8f0, height=height@entry=0x7fffffffd8f4)
    at gfx/video_context_driver.c:242
>7  0x000055555565f533 in gl_alive (data=0x555555bbdd20) at gfx/drivers/gl.c:2690
>8  0x0000555555593f9a in video_driver_ctl (state=state@entry=RARCH_DISPLAY_CTL_IS_ALIVE, data=data@entry=0x0) at gfx/video_driver.c:1580
>9  0x0000555555585d2d in runloop_iterate_time_to_exit (quit_key_pressed=false) at runloop.c:1187
>10 runloop_iterate (sleep_ms=0x7fffffffda38) at runloop.c:1346
>11 0x000055555557b868 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:312
>12 0x00007ffff0871610 in __libc_start_main () from /usr/lib/libc.so.6
>13 0x0000555555578349 in _start ()

**Comment by meveric** [comment]
seeing the same issue ever since 1.3.0~dev (also on Linux - ARM devices)

**Comment by fr500** [comment]
The settings you're changing for RGUI (still it shouldn't crash)

**Comment by fr500** [comment]
Reopen if this is still an issue
