### ISSUE TITLE
Open Archive as Folder shows "no items" when archive contains folder that in turn contains files

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#2653]
I would expect Open Archive as Folder to show Directories within the archive, allowing them to be browsed also until I can see files of matching type.

Otherwise, I have to process all my zip files to make sure they do not contain folders.

**Comment by fr500** [comment]
The whole thing was done to support goodsets, and it's really horrible
already.
I guess if someone wants to make this work it can be done but I don't think
there will be any volunteers

**Comment by gingerbeardman** [comment]
Thanks for the info.

**Comment by fr500** [comment]
closing this but feel free to discuss about implementing this as a feature
