### ISSUE TITLE
segfault when starting mupen64plus from command line

### ISSUE THREAD

**Issue by meveric** [libretro/RetroArch#2655]
When I start N64 games directly from command line
`retroarch -L ./mupen64plus "./GoldenEye 007.V64"`
retroarch crashes with a segfault.

If instead i start retroarch itself, and load core + game from retroarch menu, it works fine.
Using retroarch 1.2.2 is working fine from command line, but ever since 1.3.x it fails do load N64 games directly from command line.

System is Linux running on ARM hardfloat board (ODROID XU3)

Last entries I see with strace are that it's loading all core information files and crashes right after that:

```
munmap(0xb6ee3000, 4096)                = 0
stat64("/usr/share/libretro/info/vecx_libretro.info", {st_mode=S_IFREG|0644, st_size=384, ...}) = 0
open("/usr/share/libretro/info/vecx_libretro.info", O_RDONLY) = 14
fstat64(14, {st_mode=S_IFREG|0644, st_size=384, ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6ee3000
read(14, "display_name = \"Vectrex (vecx)\"\n"..., 1024) = 384
read(14, "", 1024)                      = 0
close(14)                               = 0
munmap(0xb6ee3000, 4096)                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault
```

**Comment by RobLoach** [comment]
Worked here....

```
retroarch -L "/usr/lib/libretro/mupen64plus_libretro.so" test.n64
```

**Comment by meveric** [comment]
I also noticed that retroarch doesn't seem to be able to find NEON CPU features anymore on 1.3.x
```
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: [OpenAL]: Using 10 buffers of 1024 bytes.
RetroArch [INFO] :: [CPUID]: Features:
```

vs 1.2.2

```
RetroArch [INFO] :: [CPUID]: Features: NEON
RetroArch [INFO] :: [OpenAL]: Using 10 buffers of 1024 bytes.
RetroArch [INFO] :: [CPUID]: Features: NEON
```

Not sure if that's related though.

**Comment by Kivutar** [comment]
According to @twinaphex on IRC,

    <Twinaphex> if it showed neon before, it was hardcoded
    <Twinaphex> with a compile-time ifdef

So don't worry about the NEON flag not showing.

I didn't notice the segfault you get with mupen on my XU3.

**Comment by sergiobenrocha2** [comment]
It's loading here too, .n64 and .zip files.

**Comment by meveric** [comment]
I did some more testing. Right now I figured out the issue is within the retroarch.cfg
Apparently my old retroarch.cfg is no longer compatible with retroarch 1.3.x
And retroarch was unable to "update" my existing retroarch.cfg to a "correct" version.

I'm gonna try to find out what config option is causing this.

**Comment by Reznnate** [comment]
On Android, this issue is related to a bug with GLUI.  Switching menu driver to RGUI fixes this for me with GL-related cores such as mupen64 and ppsspp

**Comment by meveric** [comment]
Haven't tested GLUI vs RGUI again, but I found that
```
video_threaded = "true"
```
now causes mupen64 core to crash if you try to stat it from command line.
Right now everything seems to work again without video_threaded.

But the UI really dropped in speed ever since retroarch 1.3.x
previously I got (due to a bug in the video drviers) about 120 FPS in RGUI or GLUI (retroarch 1.2.2)
With 1.3.x it's only about 40~50 FPS or so and feels a little sluggish.
Still games itself do not seem to be affected, since I can still get 60 FPS for them.

I'm still wondering about that missing NEON
```
<Twinaphex> if it showed neon before, it was hardcoded
<Twinaphex> with a compile-time ifdef
```
Even if it was hardcoded, doesn't that mean it was used?
And if now it's not hardcoded anymore, why issn't it found? The system definitely supports NEON extensions, so wouldn't that mean that the detection is broken?
```
cat /proc/cpuinfo
Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
```
It clearly says "neon" in the CPU feature list, so why isn't it detected?

**Comment by twinaphex** [comment]
On an x86_64 LInux desktop PC, running Linux, with the latest sources, I can execute Mupen64 with a ROM from the command line just fine (with threaded_video enabled).

Just in case anybody wanted to know the command I'm using (not that it'll help you locally) - here goes -

retroarch -L dist/unix/mupen64plus_libretro.so ~/roms/sin.n64

**Comment by bparker06** [comment]
I have been researching this but unable to figure out a fix... here's what I know so far:

RGUI is not affected, but XMB and GLUI is.

When threaded video is on and the content/core is specified on the command-line:

video_init_thread() is skipped in video_driver.c because video_driver_is_hw_context() is true.

then when the menu is toggled after the game is running, video_init_thread still hasn't been called, but the menu tries to draw anyway and the resulting segfault is because of this line in menu_display.c:

`565	   b = (math_matrix_4x4*)menu_disp->get_default_mvp();`

which evaluates to 0 and is then dereferenced. It is 0 because menu_disp is set to the null driver which has no MVP matrix.

When running RA without any arguments (but threading still on), video_init_thread is called and the menu driver is properly set to gl so there is no issue.

**Comment by orbea** [comment]
This doesn't seem to crash anymore, instead I get this black text in the menu.

![1](https://i.imgur.com/uMQaBfa.png)

It seems to occur with any gl core including parallel-n64, mupen64plus, beetle-psx, reicast and ppsspp. It doesn't occur with vulkan as tested with beetle-psx and ppsspp.

**Comment by RobLoach** [comment]
Tested mupen64plus and it seemed to work okay here... Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

![screenshot at 2019-01-13 01-06-45](https://user-images.githubusercontent.com/25086/51082156-bc050e00-16cf-11e9-97e8-1e8d60ee0c50.png)

**Comment by orbea** [comment]
This is with threaded video enabled? What video card and driver?

**Comment by winny-** [comment]
I  think I've ran into this issue. Hard to tell because not much logging and backtrace text is available in this issue. I have also posted additional information in [this gist](https://gist.github.com/winny-/48fbfe2fd5753dc24cfc8bcb37c90199), including `backtrace full`, complete list of all software installed on my system, and some retroarch logs.

### software/hardware

- Retroarch v1.8.8
- mupen64plus-libretro-nx commit 81a58df0263c90b10b7fc11b6deee04d47e3aa40 [link to the tree on GitHub](https://github.com/libretro/mupen64plus-libretro-nx/tree/81a58df0263c90b10b7fc11b6deee04d47e3aa40)
- llvm 9.0.1
- mesa 19.3.5
- AMD Radeon RX 580 using radeonsi
- kernel: Linux snowcrash 5.6.12 #1 SMP PREEMPT Sun May 24 19:25:14 CDT 2020 x86_64 AMD FX(tm)-8350 Eight-Core Processor AuthenticAMD GNU/Linux
- X.Org X Server 1.20.7

### testing methodology and crashes

Tested with both xmb and rgui. Got the same crash when running `retroarch -v -L /usr/lib64/libretro/mupen64plus_next_libretro.so ~/retro/roms/Super\ Mario\ 64 \ \(USA\).n64` *with* `video_threaded = "true"`. Crash goes away with threaded video disabled. Here is the backtrace:

```
#0  __strchr_sse2 () at ../sysdeps/x86_64/multiarch/../strchr.S:32
#1  0x00007ffff5b9339c in __strstr_sse2 (haystack=<optimized out>, needle=0x7fffe469d441 "OpenGL ES") at ../string/strstr.c:84
#2  0x00007fffe448a8ef in opengl::GLInfo::init() (this=0x5555581b97c0)
    at GLideN64/src/Graphics/OpenGLContext/opengl_GLInfo.cpp:30
#3  0x00007fffe4484d70 in opengl::ContextImpl::init() (this=0x5555581b9740)
    at GLideN64/src/Graphics/OpenGLContext/opengl_ContextImpl.cpp:39
#4  0x00007fffe441056b in graphics::Context::init() (this=0x7fffe4c15790 <gfxContext>) at GLideN64/src/Graphics/Context.cpp:31
#5  0x00007fffe43c488e in DisplayWindow::start() (this=0x7fffe48071c0 <DisplayWindow::get()::video>)
    at GLideN64/src/DisplayWindow.cpp:18
#6  0x00007fffe43ffe94 in PluginAPI::RomOpen() (this=0x7fffe4c15128 <PluginAPI::get()::api>)
    at GLideN64/src/common/CommonAPIImpl_common.cpp:210
#7  0x00007fffe4504339 in gln64RomOpen() () at GLideN64/src/MupenPlusPluginAPI.cpp:18
#8  0x00007fffe45b589e in main_run () at mupen64plus-core/src/main/main.c:1272
#9  0x00007fffe457882a in CoreDoCommand (Command=M64CMD_EXECUTE, ParamInt=0, ParamPtr=0x0)
    at mupen64plus-core/src/api/frontend.c:176
#10 0x00007fffe466de5c in EmuThreadFunction () at libretro/libretro.c:464
#11 0x00007fffe4692e8f in co_init () at libretro-common/libco/amd64.c:116
#12 0x0000000000000000 in  ()
```

Additionally the following crash occurs when threaded video enabled, but the core (mupen 64 plus next) & (the above rom) is instead started from the GUI, instead of from the command line:

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff5b2a56b in __GI_abort () at abort.c:79
#2  0x00007ffff5b2a43f in __assert_fail_base (fmt=0x7ffff5c8aa98 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7fffeb931564 "!bo->sparse", file=0x7fffeb931048 "../mesa-19.3.5/src/gallium/winsys/amdgpu/drm/amdgpu_bo.c", line=272, function=<optimized out>) at assert.c:92
#3  0x00007ffff5b390b2 in __GI___assert_fail (assertion=assertion@entry=0x7fffeb931564 "!bo->sparse", file=file@entry=0x7fffeb931048 "../mesa-19.3.5/src/gallium/winsys/amdgpu/drm/amdgpu_bo.c", line=line@entry=272, function=function@entry=0x7fffeb931878 <__PRETTY_FUNCTION__.18412> "amdgpu_bo_map") at assert.c:101
#4  0x00007fffeb1565d5 in amdgpu_bo_map (buf=<optimized out>, rcs=<optimized out>, usage=<optimized out>) at ../mesa-19.3.5/src/util/futex.h:43
#5  0x00007fffeafa8faa in driUnbindContext (pcp=0x7fffec034e80) at ../mesa-19.3.5/src/mesa/drivers/dri/common/dri_util.c:617
#6  0x00007ffff1110fbd in MakeContextCurrent (dpy=0x555556cd83c0, draw=65011715, read=65011715, gc_user=0x55555674fd40) at ../mesa-19.3.5/src/glx/glxcurrent.c:206
#7  0x00007ffff598bb42 in InternalMakeCurrentVendor () at /usr/lib64/libGLX.so.0
#8  0x00007ffff598d73a in CommonMakeCurrent () at /usr/lib64/libGLX.so.0
#9  0x000055555578ab2f in gfx_ctx_x_set_video_mode (data=0x555556cd7cc0, width=<optimized out>, height=<optimized out>, fullscreen=<optimized out>) at gfx/drivers_context/x_ctx.c:877
#10 0x0000555555795f50 in gl2_init (video=0x7fffffff85b0, input=0x555555e70d18 <current_input>, input_data=0x555555e70d10 <current_input_data>) at gfx/drivers/gl.c:3647
#11 0x00005555555ee3a4 in video_driver_init_internal (video_is_threaded=<synthetic pointer>) at retroarch.c:21915
#12 drivers_init (flags=1023) at retroarch.c:24716
#13 0x00005555555f4d1a in retroarch_main_init (argc=10, argv=argv@entry=0x7fffffff9690) at retroarch.c:26917
#14 0x0000555555605f08 in content_load (info=info@entry=0x7fffffff9900, p_content=<optimized out>) at tasks/task_content.c:611
#15 0x0000555555606a41 in command_event_cmd_exec (p_content=0x555555eaf300 <content_st>, launched_from_cli=false, content_ctx=<synthetic pointer>, error_string=<synthetic pointer>, data=<optimized out>) at tasks/task_content.c:1482
#16 task_push_load_content_from_playlist_from_menu (core_path=core_path@entry=0x7fffffffaa60 "/usr/lib64/libretro/mupen64plus_next_libretro.so", fullpath=fullpath@entry=0x7fffffff9a60 "/home/winston/retro/roms/Super Mario 64 (USA).n64", label=0x55555673b600 "Super Mario 64 (USA)", content_info=content_info@entry=0x7fffffff9970, cb=cb@entry=0x0, user_data=user_data@entry=0x0) at tasks/task_content.c:1705
#17 0x0000555555738ce4 in default_action_ok_load_content_from_playlist_from_menu (_path=_path@entry=0x7fffffffaa60 "/usr/lib64/libretro/mupen64plus_next_libretro.so", path=path@entry=0x7fffffff9a60 "/home/winston/retro/roms/Super Mario 64 (USA).n64", entry_label=<optimized out>) at menu/cbs/menu_cbs_ok.c:1902
#18 0x000055555573eaff in action_ok_playlist_entry_collection (path=<optimized out>, label=<optimized out>, type=<optimized out>, idx=<optimized out>, entry_idx=<optimized out>) at menu/cbs/menu_cbs_ok.c:2194
#19 0x0000555555709443 in generic_menu_entry_action (userdata=<optimized out>, entry=<optimized out>, i=<optimized out>, action=MENU_ACTION_OK) at menu/menu_driver.c:540
#20 0x00005555557099e8 in menu_entry_action (action=MENU_ACTION_OK, i=0, entry=0x7fffffffc960) at menu/menu_driver.c:1246
#21 generic_menu_iterate (data=0x555556957df0, action=MENU_ACTION_OK, current_time=<optimized out>, userdata=<optimized out>) at menu/menu_driver.c:448
#22 0x000055555570a325 in menu_driver_iterate (iterate=<optimized out>, current_time=<optimized out>) at menu/menu_driver.c:2735
#23 0x00005555555f1e68 in runloop_check_state (current_time=3793891393) at retroarch.c:28782
#24 0x00005555555f3875 in runloop_iterate () at retroarch.c:29335
#25 0x00005555555f470d in rarch_main (argc=2, argv=<optimized out>, data=0x0) at retroarch.c:9036
#26 0x00007ffff5b2be1b in __libc_start_main (main=0x5555555caf30 <main>, argc=2, argv=0x7fffffffd8b8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffd8a8) at ../csu/libc-start.c:308
#27 0x00005555555cb5da in _start () at retroarch.c:9065

```

**Comment by winny-** [comment]
I updated my comment noting that I was using the gl driver. I was unable to crash with threaded video when using the vulkan driver as mentioned [previously](https://github.com/libretro/RetroArch/issues/2655#issuecomment-453718193).

**Comment by meveric** [comment]
> @meveric Is it still an issue ?

I'll need some time to retest this.
Haven't build retroarch and mupen64plus in quite a while anymore normally I use mupen64plus standalone emulator for this instead. So give me some time to retest.

**Comment by meveric** [comment]
I've retested with arm64 and armhf the issue seems to be solved.
In fact I had a hard time reproducing the original error and was only able to do so in old retroarch versions > 1.5.0.
