### ISSUE TITLE
Issue with Hide Overlay in Menu on Android

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2656]
I was using XMB with joypad overlays and then out of curiosity I tried Glui, so I tried to get this setting "Hide Overlay in Menu" ON. But RA gets an weird behavior and start to change this setting between ON - OFF - ON many times like crazy.

It get this behavior only if you try to change it using the overlay d-pad. Using Start to reset the setting will give you the expected behavior.

**Comment by fr500** [comment]
yeah it seems when you press left or right to disable/enable overlays a context reset is triggered and for some reason the button press gets stuck

**Comment by fr500** [comment]
This is pretty major, it affects a few more settings
- threaded video (when it doesn't crash)
- hide overlay in menu 
I think this happens when the toggle causes a context reset

**Comment by Kivutar** [comment]
I confirm that this bug is this there.
