### ISSUE TITLE
Resuming Content on GPD XD Causes Controls to Not Function

### ISSUE THREAD

**Issue by escape209** [libretro/RetroArch#2659]
After downloading and using the latest version of Retroarch, I noticed that none of the controls or the touch screen worked in Retroarch except for the four face buttons, rendering the application unusable. A re-install did not fix the problem.

I encountered the problem when I was remapping the face buttons, so it seems like a configuration file issue. I'm not sure which version this started to occur on (or if the issue has been present all along, though I'm fairly confident it has.)

**Comment by fr500** [comment]
Not sure about this, I just received this:
<Shinkamui> radius not sure if you were telling me that you fixed the xd in 1.3
<Shinkamui> but it looks like the back button issue is gone

**Comment by DPersonalized** [comment]
I can pretty much confirm that it's pressing the back button during emulation that's causing the problem. Looks like it's not fixed, then. And this is with the latest nightly.

**Comment by fr500** [comment]
they are telling me it's fixed

**Comment by DPersonalized** [comment]
¯\_(ツ)_/¯

Anyway, here are steps to reproduce the issue (reproduced it literally every single time for me):

1. Load Retroarch
2. Load a core
3. Load a game
4. Press back
5. Hit Resume Content
6. Retroarch is Kill

**Comment by duskgao** [comment]
my gpd xd work fine with 2016-1-18 nightly build. change your  keymap mode to PS3

**Comment by DPersonalized** [comment]
I've been using the PS3 keymap mode this whole time. Would it be anything to do with the fact that I'm using the regular Android GUI and not the default one that comes with the XD?

**Comment by DPersonalized** [comment]
@fr500 Who is "they"? I'm just curious.
