### ISSUE TITLE
Retroarch crashed when select "system information"

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#2661]
Hello,

Retroarch crashes when I go to  "System information".
This the crash log:

>$ ./retroarch
RetroArch [INFO] :: Config: loading config from: /home/legluondunet/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Threaded rarch_task started
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: [SDL]: Available renderers (change with $SDL_RENDER_DRIVER):
RetroArch [INFO] :: 	opengl
RetroArch [INFO] :: 	opengles2
RetroArch [INFO] :: 	software
RetroArch [INFO] :: [SDL]: Available displays:
RetroArch [INFO] :: 	Display #0 mode: 1920x1080@60hz.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event2 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event3 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse1 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event2 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/event3 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse1 as type ID_INPUT_MOUSE.
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 964974852 (0x39845904)
 at -e line 15.
RetroArch [INFO] :: [udev]: Plugged pad: Microsoft X-Box 360 pad (045e:028e) on port #0.
RetroArch [INFO] :: Autodetect: 95 profiles found
RetroArch [INFO] :: Autodetect: selected configuration: /home/legluondunet/.config/retroarch/autoconf/udev/Microsoft_X-Box_360_pad.cfg
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event16) supports force feedback.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event16) supports 16 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: [PulseAudio]: Requested 24576 bytes buffer, got 18432.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [/home/legluondunet/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [PulseAudio]: Pausing.
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
retro_read_file: Failed to open /sys/class/power_supply/ACAD/online: No such file or directory
Erreur de segmentation (core dumped)

> -

Thank your for your help.

config:
Ubuntu 15.10 Wily 64 bits
NVIDIA  GeForce GTX 770
official Ubuntu Nvidia drivers 352.63 resolution 1920x1080
Processor Intel i5-3570 3,4 Ghz
8 Go RAM
Retroarch/Libretro compiled from git 13/01/2016

**Comment by twinaphex** [comment]
Run it through gdb, and when it crashes, do bt and give us the stack dump.

**Comment by legluondunet** [comment]
voilà:

http://pastebin.com/3vVqdPxk

**Comment by twinaphex** [comment]
Does it still happen with the current source? If so, can you give me a new backtrace?

**Comment by legluondunet** [comment]
The bug does not happen anymore with the last git version. Thanks.
