### ISSUE TITLE
MAME core labelling by year and not version number is confusing

### ISSUE THREAD

**Issue by neosquid** [libretro/RetroArch#2662]
There are multiple cores for each year, 2010, 2014, 2003 etc.

Is it possible they can be labelled by version number? e.g 0.154, 0.169 

This makes it less confusing loading compatible rom files.

Also, in the core updater menu list, the list of emulated systems is quite large. 

Could the core updater menus be grouped by system, then press x to move to the list of available cores?

**Comment by fr500** [comment]
Not a retroarch issue but a core issue, and it's just a bit of nitpicking in my opinion.
In any case, open this in the core repo.

The ordering thing is known yeah, I guess it's just been ignored since there are many more important issues atm.

**Comment by twinaphex** [comment]
Versioning by year is here to stay for MAME cores, anyway we still quite clearly state which MAME version this is based on anyway so you can easily remember which MAME version goes with what year.
