### ISSUE TITLE
Cannot disable shader on iOS

### ISSUE THREAD

**Issue by duduke** [libretro/RetroArch#2665]
There is no way (aside from using a keyboard or controller) to reduce shader passes and thus remove a shader after a preset had been loaded.

**Comment by fr500** [comment]
What about if you increase till 12 or 16 I don't remember, doesn't it loop back to 0?

**Comment by duduke** [comment]
I will try that. 
Are there plans to fix that? I assume this is an issue for all touch based devices (Android, iOS, etc). 

Thanks.

**Comment by fr500** [comment]
Well not sure if there are plans but this should be definitely fixed

**Comment by hizzlekizzle** [comment]
I believe we now have ways to handle this, so I'm going to close this issue. Feel free to reopen if needed.
