### ISSUE TITLE
Can't set input values to "nul" / nothing within GUI

### ISSUE THREAD

**Issue by RollingStar** [libretro/RetroArch#2669]
By editing `retroarch.cfg`, I can set inputs to `nul` and disable that line's functionality. I have used this for `input_exit_emulator`. But I had to set this manually within the config; I could not do it in the RetroArch GUI.

**Comment by fr500** [comment]
Agreed, we need a clear setting hotkey

**Comment by twinaphex** [comment]
This is implemented by now.
