### ISSUE TITLE
input_remapping_path ignored when supplied in an external config file (--appendconfig)

### ISSUE THREAD

**Issue by ReaperMantis** [libretro/RetroArch#2671]
When providing the input_remapping_path in an external config file specified by --appendconfig in the command line, the remapping is ignored.

After entering the GUI for RetroArch, selecting the remapping manually works.

This is in the windows x64 nightly from 1/24/2015.

**Comment by ReaperMantis** [comment]
My console output is as follows:
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX
RetroArch [INFO] :: Config: appending config "C:\EMULATION\CONFIG\RETROARCH\XBOXone\N64-Remap.cfg"
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
RetroArch [INFO] :: Config: loading config from: C:\EMULATION\SOFTWARE\RetroArch\retroarch.cfg.
RetroArch [INFO] :: Loading dynamic libretro core from: "C:\EMULATION\SOFTWARE\RetroArch\cores\mupen64plus_libretro.dll"
... ... ... ...
RetroArch [INFO] :: Environ SET_INPUT_DESCRIPTORS:
RetroArch [INFO] ::     RetroPad, User 1, Button "B (bottom)" => "B Button (C-Down)"
RetroArch [INFO] ::     RetroPad, User 1, Button "Y (left)" => "(C-Left)"
RetroArch [INFO] ::     RetroPad, User 1, Button "Select" => "Change Controls"
... ... ... ...

Contents of my Config file are as follows:
input_libretro_device_p1 = "5"
input_player1_analog_dpad_mode = "2"
input_libretro_device_p2 = "5"
input_player2_analog_dpad_mode = "2"
input_libretro_device_p3 = "5"
input_player3_analog_dpad_mode = "2"
input_libretro_device_p4 = "5"
input_player4_analog_dpad_mode = "2"
input_libretro_device_p5 = "5"
input_player5_analog_dpad_mode = "2"
input_libretro_device_p6 = "5"
input_player6_analog_dpad_mode = "2"
input_libretro_device_p7 = "5"
input_player7_analog_dpad_mode = "2"
input_libretro_device_p8 = "5"
input_player8_analog_dpad_mode = "2"
input_remapping_path = "C:\EMULATION\CONFIG\RETROARCH\XBOXone\Controllers\N64.rmp"

The rmp file can be loaded manually after entering the interface and works correctly.  It appears the values after SET_INPUT_DESCRIPTORS take priority over the remapping specified in the config file.

The "input_libretro_device" and "input_player_analog_dpad_mode" properties are correctly set through the external config file.

**Comment by fr500** [comment]
hmmm, while this is an issue, why do you need to do this? you can have per-core and even per-game remaps without touching the config

**Comment by ReaperMantis** [comment]
For me, per-core is too broad and per-game is too specific.  Mainly, I have a central location where I keep all my configurations that gets synced across my computers, and use more than just RetroArch.  I also do not use the front-end (as beautiful as it is) much and launch everything from command line. I suppose I could remap the config directories to point to my synced folders, but then i'm left with figuring out how to get my maybe 3 remaps for a particular system applied to select games without making a mapping for each game.  Or maybe there's a way to do that that i'm not aware of, but (until now) this has been working very well for me.

**Comment by orbea** [comment]
This was fixed and the setting is now called `input_remapping_directory`, however `--appendconfig` seems to overwrite the existing main `retroarch.cfg` which maybe should be fixed. This is a different issue so I am going to close this.
