### ISSUE TITLE
BSNES cores fails fails when loading from the commandline with some games.

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2672]
This issue is really really weird.
For starters, the offending commit:
https://github.com/libretro/RetroArch/commit/c779a1cf8f3b35f531abd9b05339bb4fc17a639a

The issue seems exclusive to windows, and only when loading games from the commandline, and even then, only with some games.

This works:

   D:\Emulators\RetroArch>retroarch-debug --config config\windows\retroarch.cfg -L libretro\bsnes_mercury_balanced_libretro.dll "d:\Games\Console\
Super Nintendo Entertainment System\Donkey Kong Country (USA).zip"

This doesn't

   D:\Emulators\RetroArch>retroarch-debug --config config\windows\retroarch.cfg -L libretro\bsnes_mercury_balanced_libretro.dll "d:\Games\Console\
Super Nintendo Entertainment System\Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr).zip

If I checkout one commit before the one mentioned, everything works.
Confirmed here: http://www.neogaf.com/forum/showpost.php?p=193209804&postcount=2785
And here: http://libretro.com/forums/showthread.php?t=4986

**Comment by Monroe88** [comment]
This is the stack trace I got when I launched that game using command line arguments:

http://hastebin.com/lodikonofo.tex

**Comment by Alcaro** [comment]
I think this is fixed as of https://github.com/libretro/bsnes-libretro/compare/11f869fd2cf9...9a18ef0125a6.

Weird indeed.

**Comment by Awakened0** [comment]
Tested the latest Balanced core with the latest RA nightly and everything launches fine again for me.
