### ISSUE TITLE
[Android] "Open Archive As Folder" does not work for some Cores

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2673]
Seems this "Open Archive As Folder" feature is broken on Android, but only for some Cores like Gen Plus and PicoDrive. It's affecting playlists as well

It was working in the 1.3.0 stable release.

**Comment by sergiobenrocha2** [comment]
Steps:

-- Go Load Content
-- Choose "Select File and Detect Core"
-- Choose a zipped genesis rom for example
-- Then try to open it as "Open Archive As Folder"
-- You'll get a black screen

**Comment by twinaphex** [comment]
Try it again with the latest source, it should be fixed now. I could confirm the issue on desktop too and it got fixed after my changes.

**Comment by sergiobenrocha2** [comment]
Fixed, thanks!
