### ISSUE TITLE
Cannot add more than one game to the playstation playlist

### ISSUE THREAD

**Issue by Hypnotoad90** [libretro/RetroArch#2679]
For whatever reason, I cannot add more than one game to the Playstation playlist using the windows x64 build. I have verified my psx roms with redump, and if I delete the playlist and add any one image individually it will show up, but any other images I add after that wont show up in the playlist - likewise scanning a whole directory, only one of the images will be added to the playlist.

I'm using the Jan 27th nightly build.

**Comment by twinaphex** [comment]
Radius posted a fix for this yesterday. Let me know if this issue is resolved with the latest nightlies.

**Comment by Hypnotoad90** [comment]
Appears to be mostly fixed, however I still cannot add the game Ape Escape (USA) for some reason, I don't know if that's related to this issue. I verified the md5 of the bin with redump.org and then downloaded the cue file directly from there, but it still doesn't add it to the playlist (runs fine if I load it manually however).

**Comment by fr500** [comment]
Fixed
