### ISSUE TITLE
D3D video driver crashes retroarch when starting any game.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#2681]
Using stable 1.3 on windows 7 64

**Comment by fr500** [comment]
I can't seem to reproduce this issue, please reopen if it's still happening. Try to get a backtrace of the issue or try without shaders to narrow it down.

**Comment by blackman91** [comment]
The issue still persist and I dont have any shaders on, I am using an intelhd3000 videocard with latest direct3d drivers and the backend works in all other emulators perfecly like dolphin and ppsspp. running windows 7.
