### ISSUE TITLE
Mystical ninja crashes on mupen64plus core when controller memory pack is active (this does not happen when I run rom on mupen64plus 2.5 directly)

### ISSUE THREAD

**Issue by Hypnotoad90** [libretro/RetroArch#2682]
As the title says, make sure a memory pack is active on controller 1, then load Mystical Ninja Staring Geomon, wait for the title screen and select 'start' - it will crash on the screen where it asks if you want to use a controller pack.

This does not happen when I run rom on mupen64plus 2.5 directly.

edit: this should probably be moved to github.com/libretro/mupen64plus-libretro/issues , my bad.

**Comment by fr500** [comment]
Core issues should go in the respective bug trackers
https://github.com/libretro/mupen64plus-libretro/
