### ISSUE TITLE
The text in the help menu gets cut off

### ISSUE THREAD

**Issue by Hypnotoad90** [libretro/RetroArch#2684]
Go to the help menu and look at the entries there, only part of the message is shown.

**Comment by RobLoach** [comment]
Screeny?

**Comment by Hypnotoad90** [comment]
https://i.gyazo.com/d3aa9247054b1c4b3d069418b3060a9f.png
https://i.gyazo.com/528196eb641e3e48865c453080aec839.png

This happens for every help entry by the way.

**Comment by twinaphex** [comment]
Should be fixed now as of this commit:

https://github.com/libretro/RetroArch/commit/6623bdc054972f1ad521c7a5d9cc08d4e227f989
