### ISSUE TITLE
Android app: Wireless controller inputs bound, but ignored.

### ISSUE THREAD

**Issue by ClausiusClapeyron** [libretro/RetroArch#2685]
Recently the RetroArch GUI changed from green/black to blue/white. Since this update, my wireless Gamestop controller no longer works. The controller still pairs and connects properly with my Droid Ultra and RetroArch still allows me to bind buttons to user 1's input, but I can neither navigate menus with my controller as I previously could or play games with it. The inputs are still bound, but ignored.

I'd also like to know why the slow button does not function like the fast forward button and simply toggle on/off. Is this just a technical limitation?

**Comment by diablodiab** [comment]
Please try the latest nightly and see if this problem is fixed.

**Comment by ClausiusClapeyron** [comment]
This fixed it, thanks.
