### ISSUE TITLE
Switching shaders does not respect subdirs

### ISSUE THREAD

**Issue by gizmo98** [libretro/RetroArch#2688]
common-shaders repo has sorted shaders in subdirs (CRT, handheld, xbr and so on).  If you switch shaders with shader_next/shader_prev hotkey only shaders located in top level are respected. common-shaders has only three shaders there at the moment (quilez.cg, scanline.cg, stock.cg). Please at functionality to switch between shaders in subdirs as well.

https://github.com/libretro/common-shaders

**Comment by zoltanvb** [comment]
This one works in current RetroArch (probably since long time), can be closed.
