### ISSUE TITLE
D3D crashes retroarch.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#2691]
Using retroarch latest stable  on windows 7 with an intel hd card 3000, when selecting the D3D driver in the driver options then opening a rom makes retroarch crash, using the latest drivers and other emulators like dolphin and pcsx2 work great with D3D in full speed. Not sure what is the problem.

**Comment by twinaphex** [comment]
Works here when launching the 2048 core with the D3D9 driver. This is on a Windows 8.1 laptop with an ATI Mobility Radeon HD 4300 GPU.

Try the latest nightly and see if that works.

**Comment by blackman91** [comment]
The nightlies won't open in my computer for some reason when opening retroarch exe it just keeps loading but never opens and I can see the background processes in the task manager but they can't be closed. I am downloading from here: http://buildbot.libretro.com/nightly/windows/x86_64/
This does not happen in the stable version.

here is more info on my pc:
http://i1312.photobucket.com/albums/t539/talos910/windows7pc_zpsc8zrn5tg.png

**Comment by twinaphex** [comment]
You are probably missing the redists. @fr500 doesn't package it in the most noob-friendly way I'm afraid because it would bloat up binary sizes of nightlies too much.

**Comment by fr500** [comment]
This is just not true
http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z
Contains everything but directx (that the user has to install anyway)

**Comment by twinaphex** [comment]
Alright. that sounds good then. Ni idea why the nightlies wouldnt work for him though on Windows.

**Comment by blackman91** [comment]
That is exactly the file I downloaded RetroArch.7z but when opening retroarch.exe it just won't open and you can see the retroarch.exe process in the background. The stable open just fine.

**Comment by fr500** [comment]
Works for me, both in D3D and in GL.
Of course for D3D I have to switch the menu driver to RGUI but that's it

**Comment by blackman91** [comment]
So you have to use the RGUI for D3D to work?

**Comment by fr500** [comment]
yes the other drivers are GL only

**Comment by blackman91** [comment]
it works now using the stable thanks a lot, the issue i am having with the nightlies not working on my pc still remains though.

**Comment by fr500** [comment]
This is a nightly 
http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch.7z
Not a stable release, didn't you say you're using that?

**Comment by blackman91** [comment]
Yes I am using the stable, what I meant was that when trying to use the nightly (Retroarch.7z) and opening retroarch exe it never opens, that doesnt happen with the stable downloaded from here:
http://buildbot.libretro.com/stable/1.3.0/windows/x86_64/

**Comment by fr500** [comment]
no clue, works for pretty much everyone else.
