### ISSUE TITLE
[Feature Request/Issue] Multiple Controller Support - Better Controller Profiling

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#2694]
I am using RetroArch 1.2 on OSX, and it has been amazing. The updated interface is a dream, mapping a controller configuration is a breeze, however I find that when I am using 2 controllers - only P1 input ever works. It looks like the P1 controller ends up being the control for both P1 & P2. I am not sure why this is the case, and Im not sure how to help with diagnosing it but if you would like me to try - I can provide as many details as possible and/or help where applicable!

- Using Bluetooth Controllers
- Both are Dualshock 4's

I think that the issue might be that they are both named "Wireless Controller" as far as OSX is concerned. I think this might be the issue because RetroArch might not be differentiating between the MAC Addresses, and instead relying on the Controller Name for the mapping. 

Would it be possible to build in a way to Name a controller based on its MAC, and then you can set the Controller Name or something? I think that could help.. 

I have gone in the menus, and mapped the inputs successfully using both controllers individually, but as soon as I boot the game up - only P1's Controller seems to be recognized, and both P1 and P2 are controlled by that device.

Edit:
I'm not sure if this is a real issue, or something that is just because of my set up. I will try to update this ticket tonight after trying a few more attempts.. I just came across a way to name the controller in OSX,  https://support.apple.com/en-ca/HT205348, so maybe after explicitly changing the device names, I won't have a conflict when mapping the controllers in RetroArch's config.

**Comment by fr500** [comment]
Weird, I don't have a mac for sure so I think it could be driver specific. I have tried several identical in windows and android and they are working fine.

What input driver are you using?

**Comment by fr500** [comment]
Please re-open if this is still an issue.

**Comment by futurepr0n** [comment]
On Mac- I am using the default driver that supplies the bluetooth connection. Do you mean the Retroarch input Driver?
