### ISSUE TITLE
RetroArch 1.3.0 Wii: Yoshi's Island Crash

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#2698]
RetroArch version: 1.3.0 official (no nightly builds used)
Wiibrew channel: 1.1.2
Wii system version: 4.3
Emulator core used: Snes9x Next

Issue: Loading Super Mario World 2: Yoshi's Island, results in complete crash of the emulator, a DSI exception, the program times out after eight seconds and returns to the Wiibrew Channel menu.  At first glance, I assumed that the Super FX2 (GSU-2-SP1) emulation being broken, but I loaded up Star Fox 2, one of the very few other games to use the second revision of the co-processor. Every other Super FX game launches fine, this one is the only one to cause a DSI exception and I can reproduce it every time. Is there a reason that this particular ROM image is being problematic?

If you need more information, please let me know. 

Addendum: I should note that the same ROM image runs in Snes9x GX 4.3.3 (modded version to run faster than 4.3.2)

**Comment by roflcopter777** [comment]
Screenshot of error

http://i.imgur.com/HM0eVWh.jpg

**Comment by fr500** [comment]
@twinaphex tested this on his wii and it doesn't seem to happen, please reopen if the issue persists.
