### ISSUE TITLE
Extraction_Directory

### ISSUE THREAD

**Issue by Omnija** [libretro/RetroArch#2700]
I've been having issues setting the Extraction_Directory = not extracting in the directed folder? 
No matter the directory used it just extracts in rom dir?

**Comment by fr500** [comment]
Can you re-test on a current build?

**Comment by Omnija** [comment]
Yes i recompiled from source this morning, and still has the same issue on the (raspberry pi 2)

**Comment by joolswills** [comment]
libretro-common/file/file_archive.c still references extraction_directory - but yeah - 0dc9c8df95414c638306f8bd89abfbcea19b22c9 changed the name of the variable, but the example retroarch.cfg configuration was not updated.

**Comment by twinaphex** [comment]
Let me know if this is sufficient - 
https://github.com/libretro/RetroArch/commit/5e4e30abe9abee5cb7be1044e17026a16b9efb6f

**Comment by twinaphex** [comment]
Closing for now. If this is still an issue, please reopen.
