### ISSUE TITLE
iOS Version of Reicast

### ISSUE THREAD

**Issue by mk8itra1n** [libretro/RetroArch#2701]
Wanted to know about the progress of Reicast iOS on RetroArch. Any pictures, videos or anything of it. Better yet, has anyone got anything like games to boot. I only got the bios working with no touch screen controls and was able to activate Widescreen

**Comment by mk8itra1n** [comment]
![image](https://cloud.githubusercontent.com/assets/12947869/12869946/29af94fa-ccfc-11e5-967d-a5f7b482165c.jpeg)
![image](https://cloud.githubusercontent.com/assets/12947869/12869950/30665392-ccfc-11e5-8139-38bb5b3aa754.jpeg)
![image](https://cloud.githubusercontent.com/assets/12947869/12869951/308f9914-ccfc-11e5-8115-fa493f6cea10.jpeg)

**Comment by twinaphex** [comment]
Please wait patiently for the next versions of RetroArch and Reicast iOS. This is not a development issue and is also not related to RetroArch, the Reicast core is a separate entity. You can open an issue in the reicast-libretro repository instead.
