### ISSUE TITLE
[Android] Problems saving settings manually, Issues with assets, weird crash using RGUI menu

### ISSUE THREAD

**Issue by Quickgold74** [libretro/RetroArch#2702]
Hi, since the last nightly version I detect and issue when you try to save a config for any core manually, RA shows Failed to save to.....(the only config that you can save is a retroarch.cfg without issue) with the stable version you don't have this problem you can save manually a config for any core.

With the assets (depends of the nightly version) the assets extract thing in the beginning is very annoying, because sometimes when you launch RA starts extracting again (sometimes fast, sometimes slow or sometimes stuck) I don't have this issue with the stable version.

With the RGUI menu selected if you show the notifications and the clock in android RA crash, this issue is happening to me since the 1.3.0 stable version on android jelly bean 4.1

**Comment by supaplex2** [comment]
I have the same problem with RGUI on the latest version of marshmallow. I'm using the latest version of retroarch from the F-Droid repository.
Whenever retroarch goes "out of focus" by android it crashes.

**Comment by twinaphex** [comment]
Do you get crashes with going out of focus with GLUI/MaterialUI? Because I can't on the Android devices I test on.

**Comment by twinaphex** [comment]
Hi,

with the current source I no longer get this problem. So I think the past few commits I've pushed the issue has been resolved.

If any of you two can compile from source, I'd like to know if you can confirm the current code fixed this issue.

**Comment by twinaphex** [comment]
@supaplex2 - Can you confirm if this issue is gone for you with the latest source? It is for me so I'd like to confirm it by somebody else before closing this.

**Comment by Quickgold74** [comment]
Hi, now RGUI it works for me without issues, RA keep the focus and I don't have any crash.

The assets thing resolve for me after reinstall RA.

I can't still save config manually for any core (even if i left the default folder for store configs), RA saves automatically the per core configs fine and if you choose to save a new copy of retroconfig.cfg it saves fine too ,but, it fail to save manually config for me in the nightly (works fine in the stable version)

**Comment by supaplex2** [comment]
Updated it from F-Droid. RGUI doesn't crash anymore!

**Comment by twinaphex** [comment]
Nice. Guess we can close this issue. @QuickGold74 Can you make a separate Github issue for that remaining issue? I'll close this one then.
