### ISSUE TITLE
[XMB] Several glitches. Affects cores.

### ISSUE THREAD

**Issue by supaplex2** [libretro/RetroArch#2704]
Hi,
I'm running the latest stable version of Lakka on a Raspberry Pi 2 with a 1280x1024 monitor. I haven't changed any configuration from Retroarch, the only non-standard thing I have is the resolution.
Everything works fine when using RGUI but XMB has glitches.
1. Background sometimes goes black and remains like that until rebooted. Changing the background to one with a 1280x1024 resolution fixed this.
2. Sometimes when scrolling from playlist to playlist, a playlist won't show any text, only the icons. Selecting something and pressing the button to go to the next menu works.
3. When using the cores Nestopia and Genesis Plus GX (with any rom) the game screen will flicker. When going back to XMB it will be slower and may start glitching randomly. A couple of times it went back to the game on its own and stayed stuck in it. The same cores work perfectly when using RGUI.
4. When making a new playlist sometimes the icons of one or more playlists start showing as a black square and remain like that until rebooting.

Anyways, thanks for all your work!

**Comment by Kivutar** [comment]
Ouch. I have not access to my RPi2 here, so I can't debug it right now. This is terrible :(

Did you notice anything similar with a previous build?

**Comment by supaplex2** [comment]
Yes, I mentioned some of this stuff in the forum, with the build from november 26th, together with other bugs. You moved the issues to this tracker back then. I didn't keep testing at the time because more stable builds came out but I didn't try them. Here I explained it better and, as I said, I believe it's caused by the resolution I'm using causing XMB to act funny since everything else is standard.

**Comment by duduke** [comment]
I can confirm that on 1080p I don't have this behavior on RPi2.

**Comment by Kivutar** [comment]
@supaplex2 What is your resolution please?

**Comment by supaplex2** [comment]
As I said in the first post, it's 1280x1024.
Here's my config.txt for the Raspberry Pi 2, just in case
`hdmi_drive=2
hdmi_group=2
hdmi_mode=35
disable_overscan=1
hdmi_ignore_edid=0xa5000080
hdmi_ignore_edid_audio=1
hdmi_ignore_cec=1
hdmi_force_hotplug=1
disable_audio_dither=1`

**Comment by RobLoach** [comment]
Mind testing this out again, and if it still persists, creating an issue over at https://github.com/libretro/lakka-libreelec ?

I haven't had this issue come up on my RPi2.
