### ISSUE TITLE
[3DS] Hangs when closed

### ISSUE THREAD

**Issue by Car0b1nius** [libretro/RetroArch#2707]
I'm using an old 3DS, and when using "Quit Retroarch" it hangs, saying "Press Start." No further input has any effect, and the only way to close it is to hard-reset the console.

The issue exists in nightly release Jan 27 2016, but not in stable release 1.3.0. The Homebrew Launcher used is v. 1.1.0.

**Comment by fr500** [comment]
Can you re-test on a current nightly?

**Comment by Car0b1nius** [comment]
It's fixed in nightly Feb 18.
