### ISSUE TITLE
Joypad will not autoconfigure anymore

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/RetroArch#2708]
I noticed the `retroarch-joypad-autconfig` package was superceded / deleted in the PPA.

I am getting this error when running a ROM.

```
"Xbox 360 Receiver (1118/1817) not Conifgured"
```

This is the command being used to execute the retroarch

"/usr/bin/retroarch" -f -L "/usr/lib/libretro/fceumm_libretro.so" "/home/steam/ROMs/NES/Bubble Bobble (U).nes"

I can see the "Xbox_360_Wireless_Receiver.cfg" in "/usr/share/libretro/autoconfig" and the

```
input_device = "Xbox 360 Wireless Receiver"
input_driver = "udev"
input_vendor_id = 1118
input_product_id = 1817
...[snip]
```

**Comment by RobLoach** [comment]
https://github.com/libretro/retroarch-joypad-autoconfig

Status: Deleted. Know if it's coming back?

**Comment by fr500** [comment]
@ProfessorKaos64 can you paste the full log of your retroarch run? if the files are there and the folder is correct it should still work

I think it's not coming back
We have a bundle with all the assets RA could ever need 
http://buildbot.libretro.com/assets/frontend/bundle.zip

If you are packaging for a distro you could always make a script that downloads the bundle and installs the files in the correct locations.

The problem with assets in the PPA is that the assets are then not user writable and then the user can't use the builtin updater or anything.

This is something packagers need to figure out for their respective platforms. Alternatively we could auto-download and extract on the first run. That could work for all distributions.

**Comment by ProfessorKaos64** [comment]
I fixed it by setting the path. See recent [commit](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/commit/edbedec636b158869b8bc317f15103b28bd0e6ff) I made to my SteamOS package. This restored autoconfigure for me. I understand the reason to push people to the updater, but this made me scratch my head. Retroarch is awesome, but there are multiple front ends which use your awesome cores, such as HyperSpin, Ice, EmulationStation, and more.

For me this is closed. Maybe I missed the memo since I don't follow the forums as closely. I checked the changelogs on the PPA, simple said "Autobuild." For my purposes, I package the assets and joypad profiles, and maintain them. For SteamOS users, and alternative front-end users, this is something I think that is preferred. SteamOS uses unattended upgrades, which I have configured for my SteamOS repository. When a new update for the profiles is synced to my repo, it is upgraded without intervention (hence the console experience of SteamOS). 

I understand the changes now and see where your team meant to go with this. In the past, I though user education solved "I can't use this directory," but I suppose this is for the better for user that have no little knowledge of their platform and rwx attributes.

**Comment by fr500** [comment]
Glad it's solved for you.

The alternative frontends you mention are just launchers anyway. They don't run the cores, they just launch RA instead.

**Comment by RobLoach** [comment]
> Alternatively we could auto-download and extract on the first run.

Would be nice to have the Online Updater do its thing on first run if it doesn't see any assets as available. Either that, or ship with the latest set, and "installing" (ie copy/pasta into config) that set on first launch.
