### ISSUE TITLE
[ios - but seems others as well] PCSX REARMED not recognising iso format anymore

### ISSUE THREAD

**Issue by bsauvage1** [libretro/RetroArch#2712]
-was perfectly recognised as of retroarch 0.9.9 (both manual and automatic)
-now crashing to desktop when loading an iso
-iso format not autorecognised (as well) by the frontend

ios 8.1.2 on ipad air 2

**Comment by bsauvage1** [comment]
some more info:
-both PSX Mednafen and PCSSX Rearmed crash to desktop when loading any rom, even bin/cue format that is normally recognised
-fwiw, all other cores (every single one apart from the PSX cores) are working perfectly

**Comment by fr500** [comment]
Regarding mednafen:
http://wiki.libretro.com/index.php?title=Beetle/Mednafen_PSX#Usage

In any case, this is a problem with mednafen OR PCSX-ReARMed, not a problem with RetroArch so reopen in the respective repositories if you think it's a developer issue (I think it's a user issue)

**Comment by twinaphex** [comment]
You are likely trying a dynarec version of PCSX ReARMed on a newer iOS version than what it was originally written against.

**Comment by bsauvage1** [comment]
It is indeed possible. I'll post also in the user forums to check if any
other similar experience, thank you for your advice.

Where on GitHub can I raise this issue in order to get the attention of the
appropriate dev team please?

**Comment by twinaphex** [comment]
There is no dev team really, there is only us at this point and I think dynarecs for iOS are a waste of time  (especially ones with lots of ASM code) since Apple just breaks ABI for every new version anyway and all the Apple lemmings always need to update at Day 1 to the newest OS, so it's a case of too much pain for too little gain.

**Comment by bsauvage1** [comment]
OK so just to add to this: crash occurs for PSX Mednafen, PCSX REARMED, and PCSX REARMED Interpreter. (while all other cores are fine - only PSX experiences the issue)
One thing that is strange: in the previous 0.9.9 version, the included PSX core was working perfectly fine, And I believe that core was different. Would it be worth/possible trying to reintegrate that old core in 1.3.0 for us unlucky Apple lemmings?

**Comment by fr500** [comment]
If Mednanfen is crashing it's not likely a bios issue. Or you're trying to
load an ISO instead of a cuesheet. Most likely user error than anything.

**Comment by bsauvage1** [comment]
Sorry to clarify: I am trying both iso, bin and cue. None works all crash
to desktop

Will post in user forums and revert if other people experience same thanks

**Comment by fr500** [comment]
Mednafen requires a BIOS (and it's definitely not the same it needed back then in 0.9.9)
Also the BIOS needs to be in the system folder (or content folder depending on your configuration).
http://wiki.libretro.com/index.php?title=Beetle/Mednafen_PSX#Usage

**Comment by bsauvage1** [comment]
Yes I am aware, thanks - all 3 required bios are in there already. Will do
more testing this weekend and revert

**Comment by bsauvage1** [comment]
OK so indeed there was an issue: bad scph5002.bin -> now game loads on mednafen (calling a cue sheet pointing to the iso file). Thank you very much for the link you provided which allowed me to find out I had the wrong mdsum...
Tried working game on PCSX REARMED Interpreter and all working well.

However PCSX REARMED (the normal, non interpreter version) still crashes to desktop when loading the same game -> seems a genuine issue with dynarec as you pointed out ?

[changed titke of the issue and reopened it]

**Comment by seadil** [comment]
As I said here, there's a quite stable way to implement a dynarec for iOS:
https://github.com/libretro/pcsx_rearmed/issues/42#issuecomment-243077042
