### ISSUE TITLE
[3DS, CIA builds] Pressing "Load Content" freezes the console

### ISSUE THREAD

**Issue by thedax** [libretro/RetroArch#2713]
Ever since 9d96e9e452859dc0b236e4f59af675ecbbb5cc53, the newest nightly builds on the 3DS are unusable. I'm not exactly sure what in that commit causes it yet, but I'll try to find out.

**Comment by twinaphex** [comment]
I reverted this commit, let me know if it brings any change for the 3DS port. I don't own a 3DS so I can't test that. If that doesn't fix it, we will have to wait for @aliaspider to look into it I suppose.

**Comment by thedax** [comment]
That "fixes" it, yes, but I put it in quotes, since I'm sure that's not the desired solution.

**Comment by thedax** [comment]
Minor update to this: the buildbot is spitting out builds from February 9th and nothing newer, at least for the CIA builds, so that is why it continues to persist. Something is wrong with the buildbot.

**Comment by thedax** [comment]
The buildbot is now producing builds correctly, but the real solution to the problem (i.e. not reverting it, and having the 3DS accept the changes that were reverted) is yet to be fixed (just a minor status update, not demanding anything).

**Comment by twinaphex** [comment]
Going to close this since it seems there is no longer an issue here.
