### ISSUE TITLE
[Android] Gambette- Is colorization broken?

### ISSUE THREAD

**Issue by SuperL2** [libretro/RetroArch#2714]
I have spent the last couple of days, in vain, trying to get a custom palette working in Gambette for Retroarch android. Specifically, a pea-green GB palette so I don't have to rely on the battery-taxing shader. 

Apparently, users of Retroarch on other systems have gotten colorization to work fine. But on Android, I'm fairly certain it's broken. The Special palettes fail to load anything, and choosing custom does not load the proper .pal file, and the palette defaults to whatever the last internal palette was.

My palette files are located in /data/data/com.retroarch/system/palettes, and read/write/execute privileges have been granted to all files and folders. But still nothing. I must thus add this issue.

**Comment by twinaphex** [comment]
Can you report that issue here?

https://github.com/libretro/gambatte-libretro

The issue is likely not related to RetroArch if there is an issue at all, so the issue should be raised there instead.

**Comment by SuperL2** [comment]
I reported it at gambette-libretro. However, it looks like no one has responsed to any issues in a long time, so I don't hold out much hope I will get a response.
