### ISSUE TITLE
Android GUI some issues with intel mesa driver 

### ISSUE THREAD

**Issue by mrcmunir** [libretro/RetroArch#2715]
with the new GUI have some problem letter view small  and resize menu are bad

![screenshot_20160211-103710](https://cloud.githubusercontent.com/assets/1274014/12974403/7ba04946-d0ab-11e5-8d79-8359a5c6d944.png)

![screenshot_20160211-102911](https://cloud.githubusercontent.com/assets/1274014/12974302/c8227394-d0aa-11e5-9184-508e4f93faad.png)

**Comment by maximu** [comment]
For the more information view better letter is build 27 january 2016 after this letter view very small.
![screenshot_20160211-104642](https://cloud.githubusercontent.com/assets/1274014/12974572/d71a01d0-d0ac-11e5-9e3a-9b6a74f40c24.png)

**Comment by fr500** [comment]
For starters, on the second shot you don't have assets, not sure why, did you build yourself?
If so, go to updater and select update assets.

Regarding the small font. I guess your driver doesn't report DPI, you can just go to settings/menu and select a DPI override.

**Comment by maximu** [comment]
I use buildbot nightly download from https://buildbot.libretro.com/nightly/android/

**Comment by maximu** [comment]
Ok I Solved with DPI Override enable and up to 160 
![screenshot_20160211-144900](https://cloud.githubusercontent.com/assets/1274014/12979404/b319bc54-d0ce-11e5-8410-b03f42ffd87c.png)

Maybe need change to 160 DPI by default and not 72dpi :P

**Comment by fr500** [comment]
I guess a better default is in order but the real problem is that your driver doesn't seem to report the metrics correctly

**Comment by twinaphex** [comment]
Huh? You're running Android on PC hardware?

**Comment by maximu** [comment]
Yes I am using PC Hardware With Intel mesa driver to debug x86 and x86_64 binary under android.
.
My test are based
* Kernel 4.4 or 4.5rc 
* mesa driver https://cgit.freedesktop.org/mesa/mesa/tree/Android.mk
* Android 6.0.1 

I can going to upload will help developers to depurate this but i'm bad upload conection

**Comment by fr500** [comment]
Then I guess it's safe to assume that the drive is not giving you actual display metrics

**Comment by maximu** [comment]
@fr500 @twinaphex here I Upload rom android x86_64 with mesa 11.2 http://1drv.ms/21E6FCa

From Shell linux you can burn in any usb 
dd bs=4M if=/path/to/.iso of=/dev/sdx status=progress && sync

This iso are supported hibrid ISO UEFI and legacy boards  

See if it happen to you too and some developer depurate propose fix this

**Comment by mrcmunir** [comment]
Close That issue Not sure if fixed by mesa3d or news Retroarch has better this but actually rescale Ok
![screenshot_20170125-094327](https://cloud.githubusercontent.com/assets/1274014/22308482/3bebe4dc-e39b-11e6-8d9d-20a9ef513850.png)
