### ISSUE TITLE
[IOS 9 Jailbreak] Mupen64/Other cores crashing on start up of rom from latest builds on cydia repo.

### ISSUE THREAD

**Issue by AirChandler** [libretro/RetroArch#2716]
Not sure if any changes have been made to the core configs in the latest build, but seems like a dynarec issue again with pangu jailbreak?

**Comment by twinaphex** [comment]
Use the mupen64 interpreter core instead and leave cpu core at cached interpreter. It is unlikely the necessary changes will be made to mupen64 to get the dynarec to work with iOS9.

**Comment by AirChandler** [comment]
Where can I find the interpreter core, since there is only one avaliable on buildbot currently, tried setting cached interpreter to that and crashed so I presume it isn't the core currently on buildbot.

**Comment by AirChandler** [comment]
Update: Now working using build from 18th jan, latest build i found with cores being able to boot, perhaps some commits made since then have caused the issue?

**Comment by twinaphex** [comment]
Sorry but I can't really help you unless you point me to a specific commit that broke it.

**Comment by AirChandler** [comment]
Ok cheers for the response anyway, ill check through commits since 18th jan see if i can relate anything to crashlogs and get back to you on the subject.

**Comment by twinaphex** [comment]
OK thanks.
