### ISSUE TITLE
[ios] - PCSX REARMED crash (ios 8.1.2 ipad air 2 jailbroken with TAIG)

### ISSUE THREAD

**Issue by bsauvage1** [libretro/RetroArch#2718]
as described in old (now closed) issue below:
https://github.com/libretro/RetroArch/issues/2712

PSX cores Mednafen and PCSX REARMED interpreter work well, however the non-interpreter version crashes to desktop.

**Comment by fr500** [comment]
Open this here instead 
https://github.com/libretro/pcsx_rearmed/issues

This is an issues tracker for RetroArch.
Thanks.
