### ISSUE TITLE
Debian 8 Jessie Stable

### ISSUE THREAD

**Issue by inukaze** [libretro/RetroArch#2722]
Hi i have Debian 8 Jessie Stable , with just repos "main contrib and non-free" no anothers .

$ uname -r
3.16.0-4-amd64

$ cd /media/Compartido/Videojuegos/Emuroms/RetroArch
i installed my RetroArch on that path , but when i try to test

$ ./2048_libretro.so
Segmentation Fault

$ ./3dengine_libretro.so
Segmentation Fault

$ ./4do_libretro.so
Segmentation Fault

$ ./81_libretro.so
Segmentation Fault

$ ./bluemsx_libretro.so
Segmentation Fault

$ ./bsnes_accuracy_libretro.so
Segmentation Fault

$ ./bsnes_balanced_libretro.so
Segmentation Fault

$ ./bsnes_cplusplus98_libretro.so
Segmentation Fault

$ ./bsnes_mercury_accuracy_libretro.so
Segmentation Fault

$ ./bsnes_mercury_balanced_libretro.so
Segmentation Fault

$ ./bsnes_mercury_performance_libretro.so
Segmentation Fault

$ ./bsnes_performance_libretro.so
Segmentation Fault

$ ./catsfc_libretro.so
Segmentation Fault

$ ./desmume_libretro.so
Segmentation Fault

$ ./dinothawr_libretro.so
Segmentation Fault

$ ./dosbox_libretro.so
Segmentation Fault

$ ./fb_alpha_libretro.so
Segmentation Fault

$ ./fceumm_libretro.so
Segmentation Fault

$ ./fmsx_libretro.so
Segmentation Fault

$ ./fuse_libretro.so
Segmentation Fault

$ ./gambatte_libretro.so
Segmentation Fault

$ ./genesis_plus_gx_libretro.so
Segmentation Fault

$ ./gpsp_libretro.so
Segmentation Fault

$ ./gw_libretro.so
Segmentation Fault

$ ./handy_libretro.so
Segmentation Fault

$ ./hatari_libretro.so
Segmentation Fault

$ ./lutro_libretro.so
Segmentation Fault

$ ./mame2003_libretro.so
Segmentation Fault

$ ./mame2010_libretro.so
Segmentation Fault

$ ./mame2014_libretro.so
Segmentation Fault

$ ./mame_libretro.so
Segmentation Fault

$ ./mednafen_gba_libretro.so
Segmentation Fault

$ ./mednafen_lynx_libretro.so
Segmentation Fault

$ ./mednafen_ngp_libretro.so
Segmentation Fault

$ ./mednafen_pce_fast_libretro.so
Segmentation Fault

$ ./mednafen_pcfx_libretro.so
Segmentation Fault

$ ./mednafen_psx_libretro.so
Segmentation Fault

$ ./mednafen_snes_libretro.so
Segmentation Fault

$ ./mednafen_supergrafx_libretro.so
Segmentation Fault

$ ./mednafen_vb_libretro.so
Segmentation Fault

$ ./mednafen_wswan_libretro.so
Segmentation Fault

$ ./meteor_libretro.so
Segmentation Fault

$ ./mgba_libretro.so
Segmentation Fault

$ ./mupen64plus_libretro.so
Segmentation Fault

$ ./nestopia_libretro.so
Segmentation Fault

$ ./nxengine_libretro.so
Segmentation Fault

$ ./o2em_libretro.so
Segmentation Fault

$ ./pcsx_rearmed_libretro.so
Segmentation Fault

$ ./picodrive_libretro.so
Segmentation Fault

$ ./ppsspp_libretro.so
Segmentation Fault

$ ./prboom_libretro.so
Segmentation Fault

$ ./prosystem_libretro.so
Segmentation Fault

$ ./quicknes_libretro.so
Segmentation Fault

$ ./scummvm_libretro.so
Segmentation Fault

$ ./snes9x_libretro.so
Segmentation Fault

$ ./snes9x_next_libretro.so
Segmentation Fault

$ ./stella_libretro.so
Segmentation Fault

$ ./stonesoup_libretro.info
Segmentation Fault

$ ./stonesoup_libretro.so
Segmentation Fault

$ ./tgbdual_libretro.so
Segmentation Fault

$ ./tyrquake_libretro.so
Segmentation Fault

$ ./vbam_libretro.so
Segmentation Fault

$ ./vba_next_libretro.so
Segmentation Fault

$ ./vecx_libretro.so
Segmentation Fault

$ ./virtualjaguar_libretro.so
Segmentation Fault

$ ./yabause_libretro.so
Segmentation Fault

And well , someone have a fix for this ?
and i got another question , this software have a GUI , Front-End ?

**Comment by gouchi** [comment]
You need to launch a frontend first not a core directly.

If you launch it with the command line please type retroarch.

Please read this introduction to get used to the vocabulary
http://www.libretro.com/index.php/getting-started-with-retroarch

**Comment by RobLoach** [comment]
```
retroarch --libretro="path/to/snes9x_next_libretro.so" path/to/filetorun.zip
```

**Comment by inukaze** [comment]
Thank you for the answer . well this software , i can download themes for it ?
Because i really dont like the colors with "xmb" but i like the style

You can view "[Here](http://s25.postimg.org/fo16df4j3/retroxmb.png)

**Comment by fr500** [comment]
Lol that theme is just broken XMB (ie: XMB without assets)

**Comment by inukaze** [comment]
Sorry for that i try solve in the terminal with :

```
cp -TRvf "/media/Compartido/Linux/src/libretro-super/retroarch/media/assets" "$HOME/.config/retroarch/assets"

cp -TRvf "/media/Compartido/Linux/src/libretro-super/retroarch/media/android/" "$HOME/.config/retroarch/android"

cp -TRvf "/media/Compartido/Linux/src/libretro-super/retroarch/media/libretrodb/cht/" "$HOME/.config/retroarch/cheats"

cp -TRvf "/media/Compartido/Linux/src/libretro-super/retroarch/media/libretrodb/cursors" "$HOME/.config/retroarch/database/cursors/"

cp -TRvf "/media/Compartido/Linux/src/libretro-super/retroarch/media/libretrodb/rdb" "$HOME/.config/retroarch/database/rdb/"

cp -TRvf "/media/Compartido/Linux/src/libretro-super/retroarch/media/overlays/" "$HOME/.config/retroarch/overlay/"

cp -TRvf "/media/Compartido/Linux/src/libretro-super/retroarch/media/shaders_cg/" "$HOME/.config/retroarch/shaders/"
```

i don't know the target of the files on the folder :
.../libretro-super/retroarch/media/libretrodb/dat/
.../libretro-super/retroarch/media/libretrodb/metadat/

Because during the compilation and installation , that files are not copy to some path use by the retroarch XD

i hope this solve the mayor part of the default configurations on RetroArch XD . well now i have the theme , you can see [Here](http://s25.postimg.org/52hb1ey7j/retroxmb.png

**Comment by sergiobenrocha2** [comment]
Why don't you just use the Online Updater ?

**Comment by inukaze** [comment]
Ready i install the things using the Online Updater . 

Is normal , when i use "xmb" or "zarch" oridyce a segmentation fault for emulate : sega master system , nintendo nes , nintendo snes , nintendo gameboy , nintendo gameboy advance ? if i use glui or another the emulators loads fine .

if i set sdl2 instead gl , segmentation fault . 

if i try to use xvideo 
RetroArch [INFO] :: Video @ 960x720
RetroArch [INFO] :: Starting threaded video driver ...
RetroArch [INFO] :: XVideo: Found suitable XvPort #505
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  151 (XVideo)
  Minor opcode of failed request:  13 ()
  Serial number of failed request:  21
  Current serial number in output stream:  22

RetroArch , can be configure to load some "default cores" , follow the file extension ?
for example

for .gba -> "Mednafen VBA"
for .nes -> "FCEUmm"
for .smc / .sfc -> "Snes9x"
for .z64 / .v64 / .n64 -> "Mupen64plus"

and customize some extension files because i ever rename my backups from Sony PlayStation 1 from ".iso / .bin + cue" to ".ps1" , the PSP backups to ".psp" or i leave ".cso" , for "Sega Saturn" i use ".sgs" , for WonderSwan/color ".wsc" ???

Why i turn on "Netplay" this automatic turn off ? or must be configure for every core ?

and the last question this software have a default path for "bios" files ?
because some emulators is better with bios files , for example playstation 1 , and gameboyadvance, but is really necesary bios for MAME Emulators except maybe for homebrew roms ,

**Comment by fr500** [comment]
Are you using configuration per-core?
if you are and you have different menu drivers it will try to switch drivers on the fly and that could be causing the crashes.

**Comment by inukaze** [comment]
Yes i am using configuration per-core , let me test

**Comment by twinaphex** [comment]
You cannot use zarch, xmb or materialui with the SDL2 video driver. You need the GL driver in order for that to work.

**Comment by inukaze** [comment]
Translation "Violación de segmento" = "Segmentation Fault"

i delete all cfg $HOME/.config/retroarch

1 ) Start RetroArch Clean

2 ) i set to sdl2
$ ./retroarch
Violación de segmento

3 ) i try with xvideo
$ ./retroarch
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  151 (XVideo)
  Minor opcode of failed request:  13 ()
  Serial number of failed request:  21
  Current serial number in output stream:  22

4 ) just works with "gl"

**Comment by twinaphex** [comment]
the sdl2 video driver would only really work with the rgui menu driver and nothing else.

xvideo should work but it's an even more pointless driver than the SDL2 video driver and it doesn't even support rgui. So honestly, just stick to gl unless you have a specific reason for not wanting to use it.

**Comment by inukaze** [comment]
Translation "Violación de segmento" = "Segmentation Fault"

i delete all cfg $HOME/.config/retroarch

1 ) Start RetroArch Clean

2 ) i set to sdl2
$ ./retroarch
Violación de segmento

3 ) i try with xvideo
$ ./retroarch
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  151 (XVideo)
  Minor opcode of failed request:  13 ()
  Serial number of failed request:  21
  Current serial number in output stream:  22

4 ) just works with "gl"

**Comment by fr500** [comment]
Closing this, opened an issue regarding the actual problem
