### ISSUE TITLE
Missing cores

### ISSUE THREAD

**Issue by ItachiSan** [libretro/RetroArch#2723]
Hello,
I'm using RetroArch on my ArchLinux, Windows 10, Android and iOS devices.

I noticed that some cores are not available on some devices; for example, the **ffmpeg** core is available on Windows but not on the other devices.
For PS1, on Linux the core **PCSX Rearmed** is available, while it is not on Windows (**Mednafen PSX** still is available).

I don't know if this is the intended way or not, as the buildbot seems to have all the cores.

*Notice*: this **missing core part** refers to the internal online downloader in RetroArch (which I use to download the nightly builds of the cores).

**Comment by twinaphex** [comment]
Those cores are not there on those platforms for various reasons.

Open up an issue about this in the respective cores' issue tracker. This is not a RetroArch issue.
