### ISSUE TITLE
(N3DS) Retroarch Bug "Load Content" Freezes the 3DS

### ISSUE THREAD

**Issue by Guilokito** [libretro/RetroArch#2727]
Hello. Recently i've put the Retroarch archives in my 3ds folder, (For example: Catsfc have "catsfc_libretro.3dsx" and "catsfc_libretro.smdh") i can enter in the retroarch menu in the menu have "Start Core" "Load Content" .
But when i press "Load content" the 3DS freezes and i have to restart. I tried to delete retroarch config and i tried old versions. Can anyone help me? (Sorry if have any gramatical errors, english is not my native language)

**Comment by thedax** [comment]
Dupe of https://github.com/libretro/RetroArch/issues/2713. However, I guess it's still happening, according to this issue and GBATemp. I haven't looked into it further yet. Maybe tomorrow.

**Comment by twinaphex** [comment]
unfortunately I don't own a 3DS so I have no idea how to fix it. I'll leave this in @aliaspider 's hands. I am sorry about some of the refactorings that brought this about but it was either having a bunch of platforms be perpetually broken for a long time or do a one-time change that might introduce some small-time breakage on some platforms but once fixed can ensure lesser issues happen over time. And the refactorings are kinda close to being all finished at this point so stability from this point on will be a priority.

**Comment by thedax** [comment]
It's fine, it's not like Retroarch is perpetually broken/it's never been usable.

**Comment by Guilokito** [comment]
I tried to delete the .smdh file and it worked!! Thanks for the attention.

**Comment by Guilokito** [comment]
I tried to delete the .smdh file and it worked!! Thanks for the attention.

**Comment by Guilokito** [comment]
I tried to delete the .smdh file and it worked!! Thanks for the attention.

**Comment by Guilokito** [comment]
I tried to delete the .smdh file and it worked!! Thanks for the attention.

**Comment by Guilokito** [comment]
I tried to delete the .smdh file and it worked!! Thanks for the attention.
