### ISSUE TITLE
[Android] Menu doesn't work with last nightly

### ISSUE THREAD

**Issue by pihug12** [libretro/RetroArch#2737]
Hello,

I'm using the last nightly with F-Droid. The menu doesn't work on my 7" tablet (Android 4.3 / CyanogenMod 10.2).
When i select an item, the one that is in the middle of the height of the screen ("Load Configuration" on the main menu or "Logging" on the setting tab) is highlighted and nothing happened next.

**Comment by twinaphex** [comment]
I can confirm this issue, however unfortunately I don't know yet when it happened. Do you know when it last worked correctly?

**Comment by pihug12** [comment]
I would say 4 days ago top, but I'm not really sure.

**Comment by twinaphex** [comment]
I think somebody tried out a local PR on the buildbot and this PR then got itself applied to the f-droid build too, leading to the issues you are experiencing. Apparently the PR is still completely broken then on mobile and does more harm than it's good. I'm going to ask @fr500 to revert the PR on the buildbot and go back to current master (in case this is the issue).

**Comment by fr500** [comment]
should be fixed, reopen if not
