### ISSUE TITLE
Per Core Configuration Input Remapping

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#2749]
I have a similar problem that someone on Reddit also shares. I thought I would submit the question here in case I could get some feedback from the developers to assist me with having set this up properly - or possibly with having the feature added in case its not available.

here is the guys [reddit ](https://www.reddit.com/r/emulation/comments/46xdrf/is_there_a_way_for_retroarch_to_make_my_remapped/)post:

> Sorry if my title doesn't make sense, I'm still fairly new to Retroarch.
> I'm tired of constantly having to remap my buttons for NES and Turbografx-16 games whenever I restart Retroarch. Even though I save the remap file and then save the new configuration, it still goes back to the default inputs. So is there a way to make it so it will load Retroarch with the custom remapping for certain cores?

There was a commenter who mentioned this was still a bit of an issue with current builds. I also seem to have the same issue, and am constantly remapping inputs after selecting a core after loading a core and content and seeing that the previously "saved" configuration has not been restored after loading it all.

**Comment by hizzlekizzle** [comment]
You should probably be using _either_ per-core configs _or_ input remaps but not both. My guess is that the various core configs don't have the 'automatically load remap files' option enabled, so once you load the core and it switches configs, it stops looking for them.

**Comment by fr500** [comment]
Related to this I think
https://github.com/libretro/RetroArch/issues/2628#issuecomment-186994043

Basically the core is being loaded at startup and I think it's causing these mixups.
Anyway for core input remapping (I mean the builtin functionality, not remapping the actual controllers) you should use the automatic loading of remaps instead.

Basically:
- enable auto loading of remap files (settings/configuration)
- load content
- go to core input options
- remap stuff
- save the remap per-game or per-core
- profit

**Comment by twinaphex** [comment]
Per-core configs are now removed since they and overrides were mutually exclusive, and per-core configs were just a huge hack and overcomplication on top of a foundation which should have been kept simple. I'm not sure what the remaining issue here is about but I am pretty sure that if you just use overrides and remaps, it will do what you want it to do.

Anyway, closing. Reopen if there is still an issue.
