### ISSUE TITLE
Estimated monitor refresh rate bug

### ISSUE THREAD

**Issue by rz5** [libretro/RetroArch#2752]
OS: Windows 10
GPU: GTX 970 (Nvidia 356.59 driver with vulkan support)

The following bug is present on a 'RetroArch full' archive available from the buildbot.

When RetroArch is in fullscreen or windowed (and window has focus), the estimated refresh rate goes down to 60Hz despite my monitor having a refresh rate of 77Hz.

When windowed and the window has no focus, you can see the estimate go up to the correct 77Hz.
This affects the feel of the xmb menu as I browse it; I can tell things are being drawn at a lower rate than my monitor's refresh rate. This also affects the rgui menu driver.

I don't often update retroarch proper (only the cores/shaders); today I did and I noticed the bug straight away. The last retroarch version I was running was from the 3rd of February. So the bug is at most that old, hope this helps in bisecting the bug.

![unfocus](https://cloud.githubusercontent.com/assets/8117159/13256350/3d2b5732-da42-11e5-82fa-5d9ca57bbf1e.png)

![focus](https://cloud.githubusercontent.com/assets/8117159/13256058/07272d92-da41-11e5-8d8c-7531108bcc09.png)

**Comment by rz5** [comment]
@twinaphex and @hunterk have mentioned that this might bug might actually be a wokaround to help people with high refresh rate monitors navigate the menus.

Which suggests that the menu refresh rate is tied to how fast the keys are polled. If so, then that's another more important bug and this issue can be closed.

**Comment by twinaphex** [comment]
I will bring it back as a setting you can turn on/off.

**Comment by twinaphex** [comment]
Can't think of a better way to fix this other than introducing yet another setting:

https://github.com/libretro/RetroArch/commit/2f98073fc180907c368ca477b9840fd1796f4c0c

I added this to 'Frame Throttle'. By setting 'Menu Throttle Framerate' to OFF, you can get the old behavior back again.

Let me know if we can close the issue with this.

**Comment by rz5** [comment]
Yes, this setting definitely fixes my personal issue. Although the underlying issue still stands - and should be tracked as a separate github issue.
