### ISSUE TITLE
XMB unresposive under Vulkan (Intel Haswell)

### ISSUE THREAD

**Issue by pepedopolous** [libretro/RetroArch#2753]
Intel Haswell i74500U, HD Graphics 4400

Vulkan works with glui but not with xmb. It seems really unresponsive with some tabs completely inaccessible. Not sure if this is an issue with input or display. I can get in-game where everything runs OK and the responsiveness to input is normal.

**Comment by MoochMcGee** [comment]
Haswell Vulkan drivers are currently broken. Don't expect much to work.

**Comment by twinaphex** [comment]
I'm using the Ivy Bridge Mesa Vulkan driver and I can't get it to work with XMB, it trips over an assertion. @Themaister tells me it works fine on Broadwell, nVidia and ARM Mali drivers though. I think Ivy Bridge and Haswell are in the same premature alpha state and it's only Broadwell and Skylake that will actually work with XMB and RGUI right now.

There are also some other bugs that still manifest themselves even with MaterialUI/GLUI but it's less severe and it seems to be related to how many on/off icon labels get drawn on a tab - if too many of them are on a page, then it just won't go to that page and you have to go 'back' in order for the menu graphics to restore themselves again. I get a lot of warning messages then to the tune of 'VK_ERROR_OUT_OF_MEMORY' or some related enum error message like that.

**Comment by twinaphex** [comment]
Let's assume these are Vulkan driver issues with preliminary drivers for now and not actual RetroArch bugs. Reopen if it's becoming apparent this isn't the case.

**Comment by pepedopolous** [comment]
XMB works for me now under Vulkan on Haswell and Skylake.
