### ISSUE TITLE
[Feature request] Track used cores and hot list for selective updating

### ISSUE THREAD

**Issue by finalsliver** [libretro/RetroArch#2754]
At present if you want to keep your cores up to date you have to enter the client and download them. however there are no markers indicating which cores users are actually using so they may end up updating incorrect cores or downloading more then needed.

Tracking used cores and either marking them or adding them to an additional 'used' list would indicate to users which cores they are using. 
Further, by indicating used cores this reduces the number of downloads, therefore reducing any possible strain on distributing hardware. (While I assume not a problem, may help at some point).
Another benefit is a reduced amount of space used on the users device. While not a priority these days, it will make things slightly tidier

As this will reduce the number of cores to update and segregate used cores to a separate list, a download all feature could then be applied to the 'used' list to update all  applicable cores. 

This could also be a good addition to be used until a core versioning system is set up for core downloads.

A further feature would be to print a 'last updated' & 'last used' date on the core download page. this would at least help with manual updates.

**Comment by fr500** [comment]
We could get the used cores from the history list already if we wanted.
Anyway I don't see how it would reduce the number of downloads or reduce space usage, if the user just clicks everything at random it will still use a lot. What we really need is a way to delete cores that we no longer want on the device. 

I --do-not-- want an update all option until we have a versioning mechanism. Not sure what @twinaphex thinks about this but it would make our server expenses higher and we are just volunteers here.

All these suggestions seems like a unnecessary complication. The only real fix is to have versioning.

**Comment by finalsliver** [comment]
Noted.

Will wait for the versioning to be in place then :)
