### ISSUE TITLE
Linux, Ivy Bridge, Retroarch segfaults on startup when attempting to use the Vulkan driver

### ISSUE THREAD

**Issue by MoochMcGee** [libretro/RetroArch#2756]
#0  vulkan_init (video=video@entry=0x7fffffffad50, 
    input=0x90dee8 <current_input>, 
    input_data=input_data@entry=0x90dee0 <current_input_data>)
    at gfx/drivers/vulkan.c:948
#1  0x000000000042f9ae in init_video () at gfx/video_driver.c:776
#2  video_driver_ctl (state=state@entry=RARCH_DISPLAY_CTL_INIT, 
    data=data@entry=0x0) at gfx/video_driver.c:1540
#3  0x0000000000431c28 in init_drivers (flags=127) at driver.c:339
#4  driver_ctl (state=state@entry=RARCH_DRIVER_CTL_INIT, 
    data=data@entry=0x7fffffffaf40) at driver.c:460
#5  0x000000000041a977 in rarch_main_init (argc=1, argv=0x7fffffffe8a8)
    at retroarch.c:1258
#6  0x000000000041a44d in rarch_ctl (state=state@entry=RARCH_CTL_MAIN_INIT, 
    data=data@entry=0x9cefb0) at retroarch.c:1398
#7  0x0000000000424ef8 in content_load (info=info@entry=0x7fffffffd7a0)
    at content.c:873
#8  0x0000000000425b28 in content_ctl (state=state@entry=CONTENT_CTL_LOAD, 
    data=data@entry=0x7fffffffd7a0) at content.c:1762
#9  0x0000000000418165 in rarch_main (argc=1, argv=0x7fffffffe8a8, data=0x0)
    at frontend/frontend.c:129
#10 0x00007fffefa4d710 in __libc_start_main () from /usr/lib/libc.so.6
#11 0x0000000000415939 in _start ()

**Comment by Themaister** [comment]
Likely caused by lack of DRI3 in xorg-server.
