### ISSUE TITLE
Prevent using non-compatible menu drivers

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#2757]
It would be good if we had checks in place so the following are prevented:
- Menu driver switched by per-core configurations
- Select a menu driver incompatible with the current context driver

Both of these lead to crashes so I think we must guard against these.

**Comment by fr500** [comment]
Related:
https://github.com/libretro/RetroArch/issues/2722

**Comment by twinaphex** [comment]
I believe we address this now finally?
