### ISSUE TITLE
[XMB] On/Off icons issue in core config

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#2758]
In bsnes_mercury_balanced core config:
Respect accuracy-impacting settings choice is "ON" or "Yes".

It should be "No" (default) or "Yes", as you can see using RGUI.

So "OFF" default / "ON" in XMB probably?

win7 x64.

**Comment by twinaphex** [comment]
I don't know what you're trying to say here, you will have to explain it more clearly.

**Comment by Kivutar** [comment]
@twinaphex XMB will display the switch if the value is ON or OFF. But this core options have Yes/No instead.

We fix that on the core side, or in XMB?

**Comment by twinaphex** [comment]
I'd say we change it core-side to maintain some uniformity.

**Comment by fr500** [comment]
will be fixed on the core side
