### ISSUE TITLE
Snes core keeps saying this game doesn't support achievements

### ISSUE THREAD

**Issue by kryptalivian** [libretro/RetroArch#2760]
I know the games have achievements, but they all say the same message

**Comment by Kivutar** [comment]
Hello, what exact core are you using?

**Comment by kryptalivian** [comment]
Snes9x(I think that's how you spell it) I've tried other cores and some say the same message and others say core not supported for retro achievements

**Comment by kryptalivian** [comment]
Upon further testing, all systems are giving me this error, except Gameboy advanced. 

I've tried this is retropies and recalbox, both with sane results

**Comment by twinaphex** [comment]
Achievements simply have not been implemented yet for most cores beyond SNES9x.

All this stuff doesn't grow on trees and the code to support it doesn't write itself. Please exercise some patience here.

**Comment by kryptalivian** [comment]
I think my message came across in a manor different from what I intended. These all seem to have worked a month ago(if my memory serves me right), which is why I was trying to bring it to your attention. I wanted to make sure you were aware and see if an update broke this.

I do appreciate everything you and your team brings to the table. I'm just in the learning phase of programing, and hope to one day help you and your project.

**Comment by twinaphex** [comment]
Which cores worked fine a month ago with achievements?

**Comment by kryptalivian** [comment]
I haven't tried genesis/mega drive yet, but can confirm Gameboy, Gameboy color, and snes aren't working and they had a month ago. They all display this games doesn't support achievements, but I know they do.

**Comment by fr500** [comment]
Genesis never worked.
Snes9x (non next) still works

http://retroachievements.org/Achievement/24574

**Comment by kryptalivian** [comment]
Genesis works for me. I have a bunch of games with achievements

**Comment by kryptalivian** [comment]
Well it did last month

**Comment by kryptalivian** [comment]
Worst case, I have it on a 4gb micro SD card, and I can make a backup image and attach a link

**Comment by fr500** [comment]
Genesis Plus GX doesn't support the interface so it could only have worked with picodrive and I don't see any commits that could have broken that.
https://github.com/libretro/picodrive/commits/master

@leiradel is not too active nowadays but I guess he could take a look.

**Comment by kryptalivian** [comment]
changed some emulators around and all are working except snes.

SNES EMULATORS- PocketSNES CATSFC, and SNES9X_Next - Those are my options right now, but it looks like I need to secure a copy of SNES9x instead of the next version.

**Comment by leiradel** [comment]
@kryptalivian Could you post the exact RA version, core version, and error message? Also, the game name and the log messages that begin with CHEEVOS it would be great.

@fr500 I'm having problems with my ISP since last Thursday >:-O

**Comment by DSkywalk** [comment]
@fr500 picodrive now support cheevos :)
https://github.com/libretro/picodrive/pull/22

I added support in fceumm too but need some core work...
https://github.com/libretro/libretro-fceumm/pull/37

enjoy :+1:

**Comment by robertybob** [comment]
@DSkywalk Thank you!!!! Are you able to sort out the other systems too? :D (Master System, Game Boy/Color, 32x, PC Engine etc)?

**Comment by kryptalivian** [comment]
Sorry, got really sick and forgot all about my post. I did find out that the No Intro Rom Set was causing the issue. I was able to fix the issue by using a normal rom you would find on a rom site.

**Comment by DSkywalk** [comment]
@robertybob your welcome!

After a cup of coffee, finally NES roms achievements are working with this pull: https://github.com/libretro/RetroArch/pull/2784 :coffee: :yum: 

enjoy again! :video_game:

**Comment by fr500** [comment]
Feel free to keep discussing this, anyhow most of these issues should be fixed core side
