### ISSUE TITLE
"audio_device" option doesn't work for Windows

### ISSUE THREAD

**Issue by nateify** [libretro/RetroArch#2761]
Using the [Core Audio Powershell Module](https://github.com/xenolightning/AudioSwitcher/blob/master/AudioSwitcher.PowerShell.CoreAudio/README.md), this is the result of `Get-AudioDevices Playback`

`Id                            : 84a7c253-f070-4418-b34d-44f5298e894b`
`RealId                        : {0.0.0.00000000}.{84a7c253-f070-4418-b34d-44f5298e894b}`
`InterfaceName                 : AMD High Definition Audio Device`
`Name                          : AMD HDMI Output`
`FullName                      : AMD HDMI Output (AMD High Definition Audio Device)`

I have tried all possible names for my audio device in the `retroarch.cfg` option for `audio_device`, but none work. I have tried each possible name with each of the available audio drivers, `xaudio`, `dsound`, and `sdl2`.

In the GitHub wiki for Lakka it suggests device naming schemes, but only for Linux audio drivers. The `aplay` command is also not available on Windows.

**Comment by berkuteagle** [comment]
Run retroarch.exe --verbose in cmd console. In outpu you can see sound devices indexes:
`...`
`RetroArch [INFO] :: Using font rendering backend: freetype.`
`RetroArch [INFO] :: DirectSound devices:`
`RetroArch [INFO] ::     0: ╧хЁтшўэ√щ чтєъютющ фЁрщтхЁ`
`RetroArch [INFO] ::     1: ─шэрьшъш (VIA HD Audio)`
**`RetroArch [INFO] ::     2: SAMSUNG (└єфшю Intel(R) фы  фшёяыххт)`**
`RetroArch [INFO] ::     3: SPDIF Interface (TX1) (VIA HD Audio)`
`RetroArch [INFO] :: [DirectSound]: Setting buffer size of 12288 bytes`
`...`

**`2: SAMSUNG...`**  its my HDMI TV
I used the device index in retroarch.cfg:
`audio_driver="dsound"`
`audio_device="2"`

and for output video to TV:
`video_monitor_index = "2"`

PS: Toggle verbosity log level can in retroarch.cfg:
`log_verbosity = "false"`

**Comment by orbea** [comment]
Given the lack of recent activity and the instructions in the previous comment I am going to close this. Please complain if this is still a problem that the previous comment did not resolve.
