### ISSUE TITLE
Retroarch not picking up input from certain devices

### ISSUE THREAD

**Issue by asimonf** [libretro/RetroArch#2765]
I have an ir remote that has a linux driver and it is exposed as another input in alongside the joystick in /dev/input using evdev. The remote works fine and sends correct keycodes (KEY_ESCAPE) for example, but Retroarch is not picking it up. When I try to assign hotkeys it doesn't pick it up either. I'm at a loss here, I don't know if there's any more configuration that needs to be done.

**Comment by orbea** [comment]
@asimonf Is this still an issue? I haven't tried recently, but I have experienced similar with keyboards. I think RetroArch has to actually know about the keys before they can be bound?

**Comment by RobLoach** [comment]
Feel free to report logs with `--verbose`. It'll display the device ID and input details.

Closing for now, feel free to re-open if you find the logs. Thanks!
