### ISSUE TITLE
[vulkan] submodule glslang not compiling 

### ISSUE THREAD

**Issue by pepedopolous** [libretro/RetroArch#2766]
glslang had a bug which was fixed with this commit: https://github.com/KhronosGroup/glslang/commit/fd3e09fefe4dd09c2515ea117983ceedbce26f8b

However, I still can't compile Retroarch if I do 'git submodule init && git submodule update' to enable the vulkan build.

I get the same error: 'error: ‘isinf’ was not declared in this scope' which should be fixed by the commit mentioned above and is fixed in the standalone glslang-git AUR package.

**Comment by twinaphex** [comment]
I updated the submodule. Let me know if this is still an issue.

**Comment by fr500** [comment]
reopen if you still have the problem
