### ISSUE TITLE
keyboard key bindings not working on some menu drivers on Linux

### ISSUE THREAD

**Issue by vanfanel** [libretro/RetroArch#2767]
Keypresses are ignored by RetroArch when trying to bind a key to a RetroPad button, or when trying to bind a key to a hotkey.
Simply to to Settings->Input->Input Hotkey Binds and chose whatever hotkey you want, and try to assing a keyboard key to that: you will see no matter what key you press, it's ignored.
The same happens in Settings->Input->Input User 1 Binds.

Other than that, GUI navigation using keyboard arrows and Z/X to accept/cancel has always been working fine.

Also, keyboard input in DosBox core seems to be affected by this since keyboard presses are ignored and not sent to the emulator.

According to R-Type in this thread:

http://libretro.com/forums/showthread.php?t=5182

...the bug is related to RETRO_ENVIRONMENT_SET_KEYBOARD_CALLBACK and he has to use polling instead.
It seems to be an old bug, but renders keyboard-dependant cores unusable like DosBox.
On the Pi and X-less ARM/Linux systems, udev driver is used. It works fine except for this bug.
On Linux/X86 shows "stuck keys", no matter what driver is chosen. Look at the same thread for R-Rype's replication of this issue on his own Linux/X_86 system.

**Comment by Kivutar** [comment]
I also noticed this, on my ARM boards, I can't use the keyboard anymore to type values in the settings. It may be related.

**Comment by fr500** [comment]
@vanfanel is this still happening or was it fixed?

**Comment by vanfanel** [comment]
@fr500: It was fixed, sorry, forgot to report here!
@Kivutar: can you test, please?

**Comment by Kivutar** [comment]
I'm still unable to use / to trigget the search in Lakka.
