### ISSUE TITLE
Possibility to not display hidden directories and files …

### ISSUE THREAD

**Issue by fooness** [libretro/RetroArch#2769]
It would be very good, if you could choose to not display hidden directories and files (the ones with the dot inbefore). Hidden files and folders really make choosing a directory or file a hassle.

**Comment by madig** [comment]
Please turn it off by default.

1) Hidden files should be hidden
2) It makes traversing the filesystem more tedious than it already is, because RA never remembers the previous dir of any path option.

**Comment by fr500** [comment]
Can I close this now?

**Comment by madig** [comment]
Yes. Turning it off by default is probably a different bug report ;)

**Comment by RobLoach** [comment]
Hiding hidden files by default makes sense. Here's the PR https://github.com/libretro/RetroArch/pull/5085

**Comment by RobLoach** [comment]
This can be closed.

**Comment by orbea** [comment]
@hizzlekizzle Can you close this one too?
