### ISSUE TITLE
wii: loading zip files causes retroarch to crash and reset

### ISSUE THREAD

**Issue by filevans** [libretro/RetroArch#2772]
zips wont work at all on the new nightly build 3-3-16, i can load in uncompressed files like smc ok

ive tested this for zips stored on usb and on the sdcard, using all the snes cores, and also nes cores, and fba cores

i dont get this bug on nes for older versions of retroarch, like 1.2.2

**Comment by fr500** [comment]
can you try setting an extraction/cache directory and try again?
