### ISSUE TITLE
XMB bug: If 'Help' is displayed, icon display is glitched/overlaps.

### ISSUE THREAD

**Issue by dankcushions** [libretro/RetroArch#2773]
![xmb-bug2](https://cloud.githubusercontent.com/assets/13054748/13544607/e1618c92-e26f-11e5-8bf0-449b859f399b.gif)

Illustrated above. To recreate, load the XMB, hit the help button/key, close the displayed message, and then navigate up/down the menu. The icons from the previous option will remain displayed even when you navigate away.

**Comment by Kivutar** [comment]
This has been fixed now.

**Comment by dankcushions** [comment]
I can't seem to get the menu_info_btn to work at all now - no help comes up! however that might be something messed up in my config.

**Comment by Kivutar** [comment]
Maybe yes. But I don't remember we changed anything about this button or action recently.
I tested on the latest master, and I don't see this icon overlap anymore.
