### ISSUE TITLE
RGUI: Playlist truncation

### ISSUE THREAD

**Issue by jamesclarke555** [libretro/RetroArch#2776]
The full width of the window is not used and rom names are truncated unnecessarily.

![rgui](https://cloud.githubusercontent.com/assets/17701640/13633182/5c032e2e-e5e5-11e5-97af-6c05d6310b5a.png)

**Comment by bparker06** [comment]
I'm not able to reproduce this on the latest version under Linux.

**Comment by orbea** [comment]
I can reproduce this. There is a lot of wasted space to the right and the rom names do not have to be truncated so much.

**Comment by jdgleaver** [comment]
I didn't notice there was an open issue for this until after I fixed it, but anyway: PR #8293 should close this little old thing :slightly_smiling_face:
