### ISSUE TITLE
Compiling and running on Wayland (without Xorg).

### ISSUE THREAD

**Issue by ApostolosB** [libretro/RetroArch#2779]
Hello. 
I try to run retroarch 1.3.1 on wayland (weston to be exact) and hit a few bumps. I am using arch on a 32 bit atom machine (i915) and compiled it by modifying the PKGBUILD found in AUR. 

In order to remove xorg stuff i used --disable-xorg --disable-xvideo --disable-xinerama as compile options. It compiles but when i try to run it with retroarch from the command line (weston terminal) i get: 

wl_drm@11: error 2: invalid name

and nothing appears on the screen. 

Is it something i have to configure differently in order to run or it is a bug?

**Comment by fr500** [comment]
I think @twinaphex has a similar setup

**Comment by orbea** [comment]
Other users mentioned wayland as working recently so I am going to close this given the lack of recent activity. Please complain if its still a problem.
