### ISSUE TITLE
Saving core input remaps only works for player 1.

### ISSUE THREAD

**Issue by jorimp** [libretro/RetroArch#2780]
I have been messing with core input remapping and can't ever get it to save for player 2. I saw #2749 and followed the suggestions of 1.) Don't use BOTH per-core configurations and core input remapping and 2.) Make sure and have auto loading of core input mapping files ON.

Here is what I have tested and the outcome:

1. Start a core + content via retropie.
2. Make sure "Load Remap Files Automatically" is ON.
3. Under "Core Input Options" make changes to mappings for "User 1" and for "User 2".
4. Save core remap file.
5. Close retroarch.
6. Start a core + content via retropie.
7. It shows "core remap file loaded" in the bottom left of the screen.
8. Open "Core Input Options".
9. Observe that all changes made to User 1 are persistent/were loaded, all User 2 changes reverted back to default.

I also tracked down the core input mappings file located in /opt/retropie/configs/nes/FCEUmm/ and found that after making changes to User 2 and saving, this is all that was in there:

input_player1_b = "8"
input_player1_y = "9"
input_player1_a = "0"
input_player1_x = "1"
input_libretro_device_p1 = "1"
input_player1_analog_dpad_mode = "1"
input_libretro_device_p2 = "1"
input_player2_analog_dpad_mode = "1"
input_libretro_device_p3 = "1"
input_player3_analog_dpad_mode = "0"
input_libretro_device_p4 = "1"
input_player4_analog_dpad_mode = "0"
input_libretro_device_p5 = "1"
input_player5_analog_dpad_mode = "0"
input_libretro_device_p6 = "1"
input_player6_analog_dpad_mode = "0"
input_libretro_device_p7 = "1"
input_player7_analog_dpad_mode = "0"
input_libretro_device_p8 = "1"
input_player8_analog_dpad_mode = "0"
input_libretro_device_p9 = "1"
input_player9_analog_dpad_mode = "0"
input_libretro_device_p10 = "1"
input_player10_analog_dpad_mode = "0"
input_libretro_device_p11 = "1"
input_player11_analog_dpad_mode = "0"
input_libretro_device_p12 = "1"
input_player12_analog_dpad_mode = "0"
input_libretro_device_p13 = "1"
input_player13_analog_dpad_mode = "0"
input_libretro_device_p14 = "1"
input_player14_analog_dpad_mode = "0"
input_libretro_device_p15 = "1"
input_player15_analog_dpad_mode = "0"
input_libretro_device_p16 = "1"
input_player16_analog_dpad_mode = "0"

I tried manually adding in the player2 configuration, and it still didn't load the mappings. Here is what I manually changed the file to:

input_player1_b = "8"
input_player1_y = "9"
input_player1_a = "0"
input_player1_x = "1"
input_player2_b = "8"
input_player2_y = "9"
input_player2_a = "0"
input_player2_x = "1"
input_libretro_device_p1 = "1"
input_player1_analog_dpad_mode = "1"
input_libretro_device_p2 = "1"
input_player2_analog_dpad_mode = "1"
input_libretro_device_p3 = "1"
input_player3_analog_dpad_mode = "0"
input_libretro_device_p4 = "1"
input_player4_analog_dpad_mode = "0"
input_libretro_device_p5 = "1"
input_player5_analog_dpad_mode = "0"
input_libretro_device_p6 = "1"
input_player6_analog_dpad_mode = "0"
input_libretro_device_p7 = "1"
input_player7_analog_dpad_mode = "0"
input_libretro_device_p8 = "1"
input_player8_analog_dpad_mode = "0"
input_libretro_device_p9 = "1"
input_player9_analog_dpad_mode = "0"
input_libretro_device_p10 = "1"
input_player10_analog_dpad_mode = "0"
input_libretro_device_p11 = "1"
input_player11_analog_dpad_mode = "0"
input_libretro_device_p12 = "1"
input_player12_analog_dpad_mode = "0"
input_libretro_device_p13 = "1"
input_player13_analog_dpad_mode = "0"
input_libretro_device_p14 = "1"
input_player14_analog_dpad_mode = "0"
input_libretro_device_p15 = "1"
input_player15_analog_dpad_mode = "0"
input_libretro_device_p16 = "1"
input_player16_analog_dpad_mode = "0"

I could have a lack of understanding regarding how this should work, but I think this is a bug. I have tried steps 1-9 on both snes9x and fceumm cores with the same results. I only tried modifying the .rmp file on fceumm.

**Comment by fr500** [comment]
What version are you running, I fixed this a couple of weeks ago.
Reopen if you're sure you're on the latest git.
