### ISSUE TITLE
raspberry pi 3 compile error

### ISSUE THREAD

**Issue by Dr-Death** [libretro/RetroArch#2781]
Hi, i got error when compiling retroarch on raspberry pi 3

> obj-unix/gfx/video_context_driver.o: In function `gfx_ctx_init_first':
> video_context_driver.c:(.text+0x188): undefined reference to `gfx_ctx_videocore'
> obj-unix/gfx/video_context_driver.o: In function `gfx_ctx_ctl':
> video_context_driver.c:(.text+0x780): undefined reference to `gfx_ctx_videocore'
> obj-unix/gfx/video_context_driver.o:(.rodata+0x0): undefined reference to `gfx_ctx_videocore'
> obj-unix/gfx/drivers/dispmanx_gfx.o: In function `dispmanx_surface_free':
> dispmanx_gfx.c:(.text+0xc8): undefined reference to `vc_dispmanx_resource_delete'
> dispmanx_gfx.c:(.text+0xfc): undefined reference to `vc_dispmanx_update_start'
> dispmanx_gfx.c:(.text+0x108): undefined reference to `vc_dispmanx_element_remove'
> dispmanx_gfx.c:(.text+0x110): undefined reference to `vc_dispmanx_update_submit_sync'
> obj-unix/gfx/drivers/dispmanx_gfx.o: In function `dispmanx_surface_setup':
> dispmanx_gfx.c:(.text+0x2a4): undefined reference to `vc_dispmanx_rect_set'
> dispmanx_gfx.c:(.text+0x2c0): undefined reference to `vc_dispmanx_rect_set'
> dispmanx_gfx.c:(.text+0x2dc): undefined reference to `vc_dispmanx_rect_set'
> dispmanx_gfx.c:(.text+0x314): undefined reference to `vc_dispmanx_resource_create'
> dispmanx_gfx.c:(.text+0x338): undefined reference to `vc_dispmanx_update_start'
> dispmanx_gfx.c:(.text+0x374): undefined reference to `vc_dispmanx_element_add'
> dispmanx_gfx.c:(.text+0x38c): undefined reference to `vc_dispmanx_update_submit_sync'
> obj-unix/gfx/drivers/dispmanx_gfx.o: In function `dispmanx_gfx_free':
> dispmanx_gfx.c:(.text+0x438): undefined reference to `vc_dispmanx_display_close'
> dispmanx_gfx.c:(.text+0x43c): undefined reference to `bcm_host_deinit'
> obj-unix/gfx/drivers/dispmanx_gfx.o: In function `dispmanx_surface_update':
> dispmanx_gfx.c:(.text+0x544): undefined reference to `vc_dispmanx_resource_write_data'
> dispmanx_gfx.c:(.text+0x54c): undefined reference to `vc_dispmanx_update_start'
> dispmanx_gfx.c:(.text+0x55c): undefined reference to `vc_dispmanx_element_change_source'
> dispmanx_gfx.c:(.text+0x56c): undefined reference to `vc_dispmanx_update_submit'
> obj-unix/gfx/drivers/dispmanx_gfx.o: In function `dispmanx_gfx_init':
> dispmanx_gfx.c:(.text+0x5c0): undefined reference to `bcm_host_init'
> dispmanx_gfx.c:(.text+0x5c8): undefined reference to `vc_dispmanx_display_open'
> dispmanx_gfx.c:(.text+0x5e0): undefined reference to `graphics_get_display_size'
> collect2: error: ld returned 1 exit status
> Makefile:124: recipe for target 'retroarch' failed
> make: *** [retroarch] Error 1

**Comment by fr500** [comment]
Is this still happening, if so, reopen
