### ISSUE TITLE
crash when disabling threaded video

### ISSUE THREAD

**Issue by Speedvicio** [libretro/RetroArch#2782]
On Android 5.1.1 when you disable video threaded option the GUI crash

**Comment by HerbFargus** [comment]
Can confirm this happens on the X86 build of windows as well (tested on latest stable 1.3.2)

**Comment by twinaphex** [comment]
Should be fixed by now in 1.3.3 Open this if it still happens for you with the 1.3.3 nightly.

**Comment by HerbFargus** [comment]
Thanks, will test when I get the chance.

**Comment by RetroUp** [comment]
I tested in the latest nightly.

WIn x86 with threaded video enabled and video driver gl crashes.

Change either and it launches. Win 64 has no problem.
