### ISSUE TITLE
XMB Theme switching

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2786]
Since we're going to have 3 XMB themes soon, we could start implementing an XMB theme setting.

The current way to switch the theme is by redefining XMB_THEME, this is not very convenient for users.

We could just list the directories in assets/xmb, or hardcode them if it's better, and add a new setting for that in the Menu setting group.

**Comment by fr500** [comment]
I already had this implemented but I didn't commit it since the other theme was very incomplete, I think we can safely hardcode it, I was basically doing settings->assetsdirectory + "xmb" + "monochrome|flatui"

**Comment by hizzlekizzle** [comment]
Another option would be to do it in standard RA style and have a plaintext file ending in *.cfg/*.theme/*.whatever which includes all of the asset locations. For example:
display_name = "RetroArt" //totally hypothetical name :P
wallpaper = "retro/retro-wallpaper.png"
icon_dir = "retro/retro-icons"
etc.
This would make it easier for end-users to craft themes without compiling them into the program and to mix-and-match assets between different themes.

**Comment by fr500** [comment]
since the image names are most likely gonna remain hardcoded maybe using all the dirs inside assets/xmb/themes would be enough

**Comment by Kivutar** [comment]
Icons names are linked to playlist names. So if we go for the dirs inside assets/xmb/, when a user want to add a custom playlist, adding an icon with the same name will do the job, without having to edit any configuration file. It's simpler.

**Comment by lollo78** [comment]
Maybe I could help to chage the posterized theme with a better quality theme (but different from the actual posterized) and platform complete. 
I have some idea. I'll do some test images and I'll share here. If you like it I'll continue :D

**Comment by Kivutar** [comment]
@lollo78 we were working about icon themes here, not wallpaper themes. However, go ahead, it's a good idea to improve the quality of the wallpapers. (Just keep in mind that they have to be lightweight to load fast)

**Comment by lollo78** [comment]
ok, sorry :smile:

**Comment by lollo78** [comment]
About the new posterized theme (to substitute the actual one that is incomplete) I done an "alpha test":
![atari-2600](https://cloud.githubusercontent.com/assets/6298682/13893613/502a6234-ed60-11e5-8f2e-5b46b6f54d46.png)
If you like it I can optimize it (for a more clear text on the GUI) and start to create all the other platforms with a different gradient colors.

**Comment by Kivutar** [comment]
Ah nice! Can you try something with less contrast? (to improve readability of the icons and text that will overlap)

**Comment by lollo78** [comment]
I'll try some solutions ;)

**Comment by Kivutar** [comment]
First implementation here https://github.com/libretro/RetroArch/pull/2809
