### ISSUE TITLE
libretro --verbose always crashes

### ISSUE THREAD

**Issue by BPaden** [libretro/RetroArch#2788]
If libretro_path is not set, libretro fails with:

```
RetroArch [ERROR] :: RetroArch is built for dynamic libretro cores, but libretro_path is not set. Cannot continue.
RetroArch [ERROR] :: Fatal error received in: "init_libretro_sym()"

```

This doesn't make sense to me. If RetroArch is built for dynamic cores, why would libretro_path need to be set? The core can be set at runtime, and that's how it works when --verbose is not set.

Of course, if libretro_path is set, retroarch tries to run retro_load_game, and because no game is specified, it immediately segfaults.

**Comment by fr500** [comment]
--verbose -L path/to/your/core_libretro.so|dll|dylib
If you want to open the menu
--verbose --menu

**Comment by BPaden** [comment]
Oh, I see what you mean. In that case, I think `retroarch --verbose` with no other arguments should also open the gui automatically as the default behavior. You wouldn't typically expect --verbose to change any behavior other than the log output.

**Comment by BPaden** [comment]
For example, does something like this make sense:

```
   current_core_type                  =  CORE_TYPE_DUMMY;
   if (argc < 2)
   {
      return;
   }
   ...
```

**Comment by twinaphex** [comment]
This should be fixed now.

Test again.

**Comment by gouchi** [comment]
Fixed !

 ./retroarch --verbose
RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3
MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 Built: Mar 22 2016
RetroArch [INFO] :: Version: 1.3.3
RetroArch [INFO] :: Git: 2323cef
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3 SSSE3
RetroArch [INFO] :: Looking for config in: "/home/gouchi/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Config: loading config from: /home/gouchi/.config/retroarch/retroarch.cfg.
RetroArch [ERROR] :: RetroArch is built for dynamic libretro cores, but libretro_path is not set. Cannot continue.
RetroArch [ERROR] :: Fatal error received in: "init_libretro_sym()"
