### ISSUE TITLE
How do I enable CPU filters?

### ISSUE THREAD

**Issue by SuperrSonic** [libretro/RetroArch#2792]
Using today's nightlies for android and Wii.
On android I select a *.filt and nothing changes in the video.
On Wii I select a *.filt and black screen, so I edited the cfg to add the path in "video_filter=" and shows on rgui but there's no change in output image.

What am I missing? It's a bit hard to find info on this, I always end up on shader threads.

**Comment by fr500** [comment]
Filters are specific to certain pixel formats so they probably don't work
on all cores.
On android I'd just use shaders instead.

On the Wii there is no real alternatives, it either works, or it doesn't

**Comment by SuperrSonic** [comment]
So I am doing it right?

And is that a recent change, though? Because I used those filters on older versions of retroarch.

**Comment by fr500** [comment]
No that isn't recent, maybe you tried with a different core?

**Comment by SuperrSonic** [comment]
I tried scale2x on cps2 core, this was working in the previous version I had. Selecting the filt there was a black screen, so I wrote the path in the config file, but no change.
I will try darken later.

**Comment by RobLoach** [comment]
Recommend upgrading RetroArch, deleting your retroarch.ini config, and try again? Going to close this one for now, but feel free to re-open if you're still running into it.
