### ISSUE TITLE
save new config filename/location

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#2793]
RetroArch 1.3.1 / 7d8ad3e

Launching with

```
/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mame2003/mame2003_libretro.so --config /opt/retropie/configs/all/retroarch.cfg ~/RetroPie/roms/mame-libretro/rom.zip
```

retroarch.cfg - http://pastebin.com/rQYAkBX5

on launch it flashes up the error "failed to save config /opt/retropie/configs/all/retroarch.cfg (why is it trying to save the config on launch? or is this just a false error). The file is writeable.

when entering RGUI and choosing "Save New Config" it tried to save a file called ".cfg" in the current folder (rather than the location of the config file which would be preferable). if doing it again it chooses the name -1.cfg, then -2.cfg

I believe this used to work (it would choose a more sensible filename) and used to use the config folder location.

**Comment by joolswills** [comment]
verbose log

http://pastebin.com/R1peKKu7

**Comment by joolswills** [comment]
There have been a few changes since this version, so rebuilding to check.

**Comment by joolswills** [comment]
just tested with `RetroArch: Frontend for libretro -- v1.3.2 -- 0a613c0 --`

Still has the same problem.

**Comment by twinaphex** [comment]
@fr500 - Please look into this. I too have noticed that for some reason it tries to write the config file now at startup which is definitely wrong. 

Unfortunately I know nothing about these per-core/per-game configuration codepaths, so I assume there is some issue there which has crept in.

**Comment by fr500** [comment]
It has always saved on startup with configurations per-core. It was just
not visible because there was no OSD message on that function

**Comment by twinaphex** [comment]
And configuration per-core is enabled now by default? Is this desirable for all platforms or should we only enable it for some like Android?

**Comment by fr500** [comment]
I don't think so.  I don't use that feature either because it's a bit
unpredictable

**Comment by efraimsangil** [comment]
What source file contains the code for this function?

**Comment by fr500** [comment]
@joolswills it's not failing to save new config or current config anymore on any of my systems.
The OSD message should only appear if you have configurations per-core enabled, can you confirm if that's the case?

**Comment by fr500** [comment]
Also, this is a problem with core-specific configs because RetroArch is loading the core at startup, that is what causes the most issues with core-specific configs as far as I can tell

**Comment by joolswills** [comment]
My config is linked above - it contains `core_specific_config = false`

save new config works if the current folder is writable, but it doesn't include a filename just the extension as described above. It used to save the configs to the location of the currently loaded config and it used to give it a filename.

**Comment by fr500** [comment]
Are you on the latest master?

**Comment by joolswills** [comment]
I wrote that above also - just tested with RetroArch: Frontend for libretro -- v1.3.2 -- 0a613c0 -- :)

**Comment by fr500** [comment]
I don't see any reason for it to be writing the config at startup.
I can't reproduce it in linux now.
You could try to revert this I guess:
https://github.com/libretro/RetroArch/commit/5f3b27417b866c1e38bb197fd85c9f03d89492cf

Or this:
https://github.com/libretro/RetroArch/commit/7cc72520f754607d120e7306c8565b8162d41ece

But before I made these two commits the Save New Configuration entries on the menu was broken

**Comment by fr500** [comment]
Tried loading from the CLI to see if there was any weird behavior and it's still working as expected:
http://www.hastebin.com/xixoyovubu.coffee

**Comment by fr500** [comment]
@twinaphex no configurations per-core are not enabled by default, not even on android (thankfully)
It's enabled by default on RARCH_CONSOLE though

**Comment by joolswills** [comment]
Sorry, I can see why it failed to save on start in my case - there was a permissions error, my bad - the config save name is still wrong though. Why does it need to save the config on start ?

**Comment by fr500** [comment]
it's not saving at startup for me.
Why is the name wrong (ie, what is it saving as, what is it expected to save as)

**Comment by joolswills** [comment]
it says it is in your log.

**Comment by joolswills** [comment]
```
RetroArch [INFO] :: Saving config at path: "../../.config/retroarch/retroarch.cfg"
RetroArch [INFO] :: Saved new config to "../../.config/retroarch/retroarch.cfg".
```

**Comment by fr500** [comment]
That was after selecting exit

**Comment by joolswills** [comment]
aah sorry.

**Comment by joolswills** [comment]
hmm i corrected the permissions problem I thought I had, and made sure I can write the file and it's still trying to write on start and still failing. odd

```
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [ERROR] :: Failed saving config to "/opt/retropie/configs/all/retroarch.cfg".
```

I will debug further then.

**Comment by joolswills** [comment]
in regards to the "save new config". it is saving to the "current working directory" rather than the location of current config as filename ".cfg" and then if you do it again it saves to "-1.cfg" -

**Comment by fr500** [comment]
oh... really odd, I'll try to fix it

**Comment by joolswills** [comment]
some more information regarding the failing to save config error message - it is triggered when `config_save_on_exit = false` - when `config_save_on_exit = true` it doesn't throw the error on start.

**Comment by joolswills** [comment]
So I guess event_save_current_config is being called on startup and the changes made in https://github.com/libretro/RetroArch/commit/7cc72520f754607d120e7306c8565b8162d41ece cause the issue as ret will be false if config_save_on_exit = false and the error will be shown.

**Comment by joolswills** [comment]
the check for return value needs to be inside the `if (settings->config_save_on_exit && *global->path.config)`

**Comment by fr500** [comment]
You're right, otherwise it will always print the message even though it's not actually trying to save

**Comment by fr500** [comment]
So, this is what I propose:
http://hastebin.com/jekefibobo.coffee

**Comment by joolswills** [comment]
Looks good to me.

**Comment by fr500** [comment]
Ok, pushed 
https://github.com/libretro/RetroArch/commit/9b6e97f967233a8cf536f2a832bcd4ccc4f350cf
Btw saving on exit does happen, but only on the first run. It's required by android/iOS to  make sure it extracts the latest asset bundle.

**Comment by joolswills** [comment]
The original issue is still not addressed though - which was the saving new config filename etc

**Comment by joolswills** [comment]
Or has it been ?

**Comment by lionking03** [comment]
juste rebuild retroarch from source based on a retropie 3.6 and "failed to save config /opt/retropie/configs/<emulator>/retroarch.cfg" message not showing anymore, this fix seems to be ok, thanks for that

but when accessing GUI and tried "Save new Config", "failed saving config to .cfg" appear and obviously there is no new config file created

doesn't help  I know just a quick test

**Comment by fr500** [comment]
I don't get that though.
Save new config works fine for me

**Comment by fr500** [comment]
ok, can you try again, and if it's still bad, can you paste the log?

**Comment by lionking03** [comment]
rebuild from source minutes after your message same issue on the osd, i tried to get more logs :

```
RetroArch [INFO] :: null: [/opt/retropie/configs/nes/content_history.lpl].
RetroArch [INFO] :: Using core name for new config
RetroArch [INFO] :: Saving config at path: "-6.cfg"
RetroArch [INFO] :: Saved new config to "-6.cfg".
RetroArch [INFO] :: Using core name for new config
RetroArch [INFO] :: Saving config at path: "-7.cfg"
RetroArch [INFO] :: Saved new config to "-7.cfg".
```

I just get one thing. When I launch from emulationstation a game (tetris for nes in the example) and try a save new config I always get the "failed saving config to .cfg"
then I quit emulationstation to launch the game through command line to add the verbose option and the message change to "saved config file to .cfg" then -1.cfg -2 and so on, but I can't find the files are they aren't in the nes configs directory

It seems that it can't get the core name when it tried to get it, hope it helps

**Comment by fr500** [comment]
Hmm I really don't know, try logging the value of settings->libretro at line 688 
I can't reproduce this so I can't fix it

**Comment by joolswills** [comment]
@fr500 have you tried it using the config I posted earlier (http://pastebin.com/rQYAkBX5) - maybe it is triggered by a particular setting like the other issue. I will try and debug it further though also.

**Comment by fr500** [comment]
I'm on windows so I can't really reproduce your setup

**Comment by joolswills** [comment]
I have debugged the problem.

>        C99 and POSIX.1-2001 specify that the results are undefined if  a  call
       to  sprintf(), snprintf(), vsprintf(), or vsnprintf() would cause copy‐
       ing to take place between objects that overlap  (e.g.,  if  the  target
       string  array and one of the supplied input arguments refer to the same
       buffer).  See NOTES.

fix:

diff --git a/command_event.c b/command_event.c
index fa2db47..d086050 100644
--- a/command_event.c
+++ b/command_event.c
@@ -702,7 +702,7 @@ static bool event_save_core_config(void)
          else
             strlcpy(tmp, ".cfg", sizeof(tmp));
 
-         snprintf(config_path, sizeof(config_path), "%s%s", config_path, tmp);
+         strlcat(config_path, tmp, sizeof(config_path));
          if (!path_file_exists(config_path))
          {
             found_path = true;

I'll do a PR
