### ISSUE TITLE
Netplay stopped working in 1.3.2

### ISSUE THREAD

**Issue by Brottweiler** [libretro/RetroArch#2795]
In `1.3.1`, I went into `Network` settings, enabled `Netplay Enable` and loaded the ROM. RetroArch launched in some kind of "daemon mode", waiting for client to join. When client connected, it worked as expected.

Updated to `1.3.2`, doing the same procedure above launches the ROM this time, and does not go into this "daemon mode" to wait for client. Client cannot connect when the ROM has started, it seems like it **ignores** the `Netplay Enable` option.

Any ideas?

**Comment by twinaphex** [comment]
Currently looking at it.

**Comment by fr500** [comment]
fixed
