### ISSUE TITLE
Games are not saved in the console playlist

### ISSUE THREAD

**Issue by ItachiSan** [libretro/RetroArch#2796]
**Version used**
iOS9 RetroArch, from the Cydia repository

**The issue**
Doing a scan in the directory, in order to add the content to RetroArch, does not work properly.

**Step to reproduce**
- install RetroArch
- inside RetroArch, install any core
- drop the ROM inside any folder of your iPad
- in RetroArch, do **Add content -> Scan directory** and choose the directory where the ROMs are present

**What is expected**
The ROMs are added to the console tab, as on Android devices.

**What happens**
No console playlist is created.

**Additional information**
ROMs path is _/var/mobile/Media/Downloads/ROMs_

**Comment by ItachiSan** [comment]
The bug is still present in actual releases.
I want to point out that the problem is maybe related to the fact it is the Cydia package.

**Comment by orbea** [comment]
@ItachiSan Is this still a problem? If so please make sure you have the core info and database files from the online updater before scanning.

**Comment by ItachiSan** [comment]
Hey @orbea, I don't have anymore that device so I can't test it.

**Comment by orbea** [comment]
Oh well, thanks for the report. Given the lack of activity and age of this issue report I am going to close it, but please let us know if you or anyone else can reproduce it again in the future or feel free to make a new issue!
