### ISSUE TITLE
[Feature Request] Default support for NESPAD by Xgaming?

### ISSUE THREAD

**Issue by Hedda** [libretro/RetroArch#2813]
Please consider adding default support for the "NESPAD", which is a new cross-platform gamepad in extended SNES/NES/N64 retro-style combo by Xgaming of X-Arcade fame.

http://shop.xgaming.com/products/nes-wireless-gamepad-ios-android-mac

I know that Shawn Walters <shawn@xgaming.com> from Xgaming donated an Tankstick (XArcade) to developers before and bet they donate NESPADs too if asked ;)

**Comment by gouchi** [comment]
You shouldn't crosspost, [one post](https://github.com/libretro/Lakka/issues/334) is enough ;-)

**Comment by fr500** [comment]
it's just an 8bitdo nes30 pro, I have one already

**Comment by HerbFargus** [comment]
This was already answered multiple places:

https://github.com/RetroPie/RetroPie-Setup/issues/1399
