### ISSUE TITLE
Retroarch 1.3.2 Segfaults on Debian 8

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/RetroArch#2815]
Made a package, using the same [debian set](https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/retroarch/retroarch/debian) I used for 1.3.1, even manually built to try, but retroarch will segfault. What may help determine the cause, an strace? Maybe run retroarch-dbg?

**Comment by sergiobenrocha2** [comment]
Are you using the 1.3.2 tarball? Or last commit? 1.3.2 was a buggy release, twinaphex reverted several commits

**Comment by ProfessorKaos64** [comment]
I was using the release tag / tarball. If it was buggy, I'll just stay patient then.

**Comment by sergiobenrocha2** [comment]
Use last commit, or 1.3.0 release.

**Comment by ProfessorKaos64** [comment]
1.3.1 functions fine since it's release, but will take note. Thank you Sergio
