### ISSUE TITLE
Visual Studio 2015 build

### ISSUE THREAD

**Issue by anon78768** [libretro/RetroArch#2817]
How do I build this in Visual Studio 2015? I didn't see any instructions for building with VS2015 on the wiki.

**Comment by Themaister** [comment]
As far as I know, MinGW-w64 is the preferred way to build for Windows. I think there's a MSVC 2010 build which might work in VS2015.

**Comment by bparker06** [comment]
Link to msvc 2015 solution here:

https://github.com/libretro/RetroArch/blob/master/pkg/msvc/RetroArch-msvc2015.sln
