### ISSUE TITLE
Close Content crashes RA on Android

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2828]
Close Content crashes RA on Android 4.4.2 (S4 mini GT-I9195), updated to the last commit. It was not happening last week (or 2 weeks ago, can't remember the last time I updated it).

I'm getting the pop-up window "RetroArch stopped".

**Comment by fr500** [comment]
Could be related to the @Themaister commits I think, I don't see anything else that might cause this.
In my case it doesn't show the RetroArch stopped window, but it just closes, I was about to open this

**Comment by Themaister** [comment]
I would be surprised if that commit affects this, but something is clearly funky on Android side. Can we get some indication where it is crashing?

**Comment by Themaister** [comment]
Should be fixed now.
