### ISSUE TITLE
Retroarch 9.0

### ISSUE THREAD

**Issue by soerser1** [libretro/RetroArch#2829]
I have just installed retroarch 9.0 version but for some reason when I try to open the application it crashes immediately. I am running iOS 9.0 as well.

**Comment by RobLoach** [comment]
Only Retroarch 1.3.2 is out.

**Comment by jorgetorresny** [comment]
I'm having the same issue I Install 1.3.3.1459346899  RetroArch GIT IOS9 it crashes immediately. on 9X ios

**Comment by twinaphex** [comment]
This should be resolved now. Try again and tell me if it's fixed so I can close this issue.

**Comment by soerser1** [comment]
Yes the application is working now but none of the cores are loading up. Every time I download a core and then select it, it tells me there is no core. Also when I use said core on a rom it closes the whole application.

**Comment by twinaphex** [comment]
It works just fine here. I'm not sure what your problem even is.

**Comment by soerser1** [comment]
It's working now. Thank you very much for your time and help.

**Comment by twinaphex** [comment]
OK, closing this then.
