### ISSUE TITLE
Failed to initialize audio driver - PulseAudio 8.0

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2830]
Could anyone confirm if the pulse driver is working yet with libpulse 8.0 ? On debian it seems it's not working anymore (I tested only in a VM).

Arch Linux updated pulse too.

**Comment by Themaister** [comment]
Works for me:
Name            : libpulse
Version         : 8.0-3
Description     : A featureful, general-purpose sound server (client library)
Architecture    : x86_64

**Comment by twinaphex** [comment]
Going to close this until @sergiobenrocha2 can tell me this issue still happens.
