### ISSUE TITLE
1.3.3.1459346899 RetroArch GIT IOS9 it crashes immediately

### ISSUE THREAD

**Issue by jorgetorresny** [libretro/RetroArch#2832]
I Install 1.3.3.1459346899 RetroArch GIT IOS9 it crashes immediately. on 9X ios. 
I have try to install by file without cydia and it does the same thing. also have try to install the ios 1.3.2 via command line since we only have a deb file and looks like the app gets install because I see I on ifile but there is no executable or icon in the screen,

**Comment by twinaphex** [comment]
This should be resolved now.

**Comment by twinaphex** [comment]
I'm closing this. reopen if it still is an issue.
