### ISSUE TITLE
haptic feedback option for mobile versions

### ISSUE THREAD

**Issue by idowolf** [libretro/RetroArch#2834]
Please add an option to enable haptic feedback (vibration when touching on-screen overlay) to the Android/iOS versions.

**Comment by elgiraffe** [comment]
This would be great.  It's the only reason I don't use retroarch on my android.

**Comment by blackman91** [comment]
Now that Retroarch is on Patreon could you guys add this feautre as a goal? Most android emulator have it, makes touchscreen controls more tolerable.
https://libretro.com/forums/showthread.php?t=565

**Comment by twinaphex** [comment]
The bounty system will start this month. Wait for further details to arrive from @hizzlekizzle

**Comment by blackman91** [comment]
Hi guys any news on this? Are there bounties for this feature?

**Comment by blackman91** [comment]
Nice! the bounty system started, hope this feature gets considered.

**Comment by pedrofleck** [comment]
Haptic feedback would be nice. And what about rumble? Is it planned or possible?

**Comment by blackman91** [comment]
I noticed you can now post bounties for issues, awesome! Haptic feedback and the ability to change the position of the controller overlays easily like in other emulators are very wanted features formobile.

**Comment by blackman91** [comment]
Bounty added!

**Comment by whs** [comment]
Added bounty on bountysource a few months ago. Seems the issue title is still not updated

**Comment by blackman91** [comment]
Wow so this finally got added? Amazing job guys, how do you enable it?

**Comment by blackman91** [comment]
Hmmm it doesn't seem to be under input options, I am using latest Android nightly and I am on Android 7 using the xmb ui.

**Comment by blackman91** [comment]
Definitely a bug the option is showing on Windows version under input settings.
