### ISSUE TITLE
Are there interest in making a shaders' cross-platform library/framework?

### ISSUE THREAD

**Issue by timofonic** [libretro/RetroArch#2836]
ReShade is quite popular in Windows. Unfortunately, it's not multtiplatform and is a too big codebase to modify.

@LifeIsStrange's [Add Linux support ? #18](https://github.com/crosire/reshade-shaders/issues/18)

@crosire says making it multiplatform would be a very hard effort. I would like to know if there's enough interest in the FOSS community (RetroArch, Wine?, Dolphin?, etc) to make it happen.

https://github.com/aras-p/hlsl2glslfork
https://github.com/gviau/Hlsl-To-Glsl

[Athena](https://github.com/Philpax/athena): A Shader Model 4 decompiler.

[HLSLCrossCompiler](https://github.com/James-Jones/HLSLCrossCompiler): Tons of forks, not so updated.

Google's [ANGLE](https://github.com/google/angle).A multtiplatform shader language. It's used by Google, Firefox, game developers and others.

[Gamma](https://github.com/kovasb/gamma)

[Open Shading Language](https://github.com/imageworks/OpenShadingLanguage/): It has big ones from the film industry, it seems.

[MojoShader](https://hg.icculus.org/icculus/mojoshader/)

There's interest in [HLSL to SPIR-V compiler](https://www.reddit.com/r/vulkan/comments/460d91/hlsl_to_spirv_compiler/), but nobody did it. [Krafix](https://github.com/KTXSoftware/krafix) does the opposite (SPIR-V to others).

Other projects like [OBS Studio](https://github.com/jp9000/obs-studio) might be interested on this.

**Comment by Themaister** [comment]
I don't see how this is related to RetroArch?

**Comment by Alcaro** [comment]
We've got our shader system, I guess he thinks we're interested in everything shader-related?

While a cross-platform ReShade would be nice to have, it does indeed not have anything to do with us. You're welcome to reuse our code, but I don't see why that'd be a issue here.

(oh, and ANGLE is not a shader language; it's an OpenGL->Direct3D translator, including GLSL->HLSL. All languages it uses already existed.)

**Comment by LifeIsStrange** [comment]
Interest should growing if steamOS is a success 

Also maybe that you can ask to a mesa developper ?
