### ISSUE TITLE
Display aspect ratios on NES emulators make no sense

### ISSUE THREAD

**Issue by arromdee** [libretro/RetroArch#2837]
FCEUMM core renders a 240x224 area and claims 4:3 core provided display aspect ratio. Nestopia renders a 256x224 area and also claims a 4:3 core provided DAR. It is impossible, of course, for these areas with different numbers of pixels to both have the same DAR.

NES pixels are 8:7 PAR, so a 240x224 area should have 240 * 8/7 / 224 = 1.224 DAR and a 256x224 area should have 256 * 8/7 / 224 = 1.306 DAR. Since the 8/7 figure is not exact anyway, reasonable values to use are 5:4 for FCEUMM and 4:3 for Nestopia.

**Comment by hizzlekizzle** [comment]
I think the difference you're describing is related to overscan cropping. If you disable all of that stuff and set the aspect ratio to 1:1 PAR (16:15 DAR), both cores produce 256x240 frames, and both stretch to a core-provided aspect ratio of 4:3, which is the nominal CRT aspect that we apply to all cores that were TV-based.

**Comment by arromdee** [comment]
Actually I was wrong about 8:7 being approximate.  It's exact.

http://wiki.nesdev.com/w/index.php/Overscan

The problem is that because there is such a thing as overscan and the emulator can choose to show it or not, the correct display aspect ratio varies depending on how much overscan you show.  You can't just have a single aspect ratio and stretch everything to it regardless of how much or how little overscan you show.

If you're displaying 280x240, the display aspect ratio should be exactly 4:3 (and the pixel aspect ratio 8:7).  If you are displaying the 90% safe area of 252x216, the display aspect ratio should also be exactly 4:3.  Emulators normally don't do either of these, however.

If you're displaying 256x224, the ratio should be 1.306 and if you're displaying 240x224 the ratio should be 1.224, for the reason stated above.  If you're displaying 256x240, the ratio should be 256 * 8/7 / 240 = 1.219.  Displaying 256x240 but stretching it to a display aspect ratio of 4:3 is visibly way off from correct.

There are several ways to get this correct.  For instance, you could have two sets of values
-- core-provided "aspect ratio with all the overscan" (4:3)
-- core-provided "resolution with all the overscan" (280x240)
Then, to get the correct display aspect ratio, you should compute it from these.  For instance, if you are displaying 256x240, you should be computing (256 / 240 * (4/3) / (280/240)) = (256/240) * (8/7) = 1.219.

**Comment by hizzlekizzle** [comment]
There's no one true aspect ratio. NES palettes and aspect ratio are both contentious topics. rdanbrook maintains Nestopia and the libretroization (he's the one who put in the overscan cropping core options, too), so you could try opening the issue in his repo to see what he has to say about it. I'll try to ask him to pop in here and comment, as well.

From that NESdev wiki article, "The NES PPU always generates a 256x240 pixel picture." This is what you get with nestopia core with overscan cropping disabled. You can then stretch that however you like.

**Comment by arromdee** [comment]
The NES generates a 256x240 picture, yes.  But it doesn't generate it with equal amounts of overscan on all sides.  If you want to stretch it to fit a 4:3 screen, you have to stretch the 280x240 area that includes it to a 4:3 screen.  Stretching the 256x240 to a 4:3 screen is absolutely the wrong thing to do.

**Comment by fr500** [comment]
In any case, these aren't retroarch issues, more like core issues.
Closing, feel free to open on the nestopia and the fceumm repos.
