### ISSUE TITLE
3ds banners should name the core

### ISSUE THREAD

**Issue by arromdee** [libretro/RetroArch#2839]
The icons and banners on the 3DS are just images.  Usually the icon is an image of the controller for the emulated system and the banner is a libretro logo.  This is bad for usability because it makes it hard to see what particular emulator a particular icon/banner is for.  In some cases it's actually impossible without starting the emulator to see what it is; for instance, two NES emulators that both use an image of a NES controller cannot be told apart.  The banner should include text naming the emulator and system that apply, rather than just a libretro logo.

**Comment by Chocobubba** [comment]
I highly agree with this. If we can't unify everything into a single file and just use core files in a romfs folder or something, then this is critical in my opinion.

**Comment by aliaspider** [comment]
fixed with #3714
