### ISSUE TITLE
PC version crashes on input_netplay_swap_players keypress (1.3.0)

### ISSUE THREAD

**Issue by poisson** [libretro/RetroArch#2844]
In my config file, input_netplay_swap_players is bound to 'i' by default despite showing up nowhere in any menus. When 'i' is pressed during netplay, on either host or client, RetroArch crashes.

Looking at the code, it looks like it just calls into itself forever, overflows the stack, and crashes.

In netplay.c/netplay_driver_ctl:

```
 case RARCH_NETPLAY_CTL_FLIP_PLAYERS:
         {
            bool *state = (bool*)data;
            if (*state)
               event_cmd_ctl(EVENT_CMD_NETPLAY_FLIP_PLAYERS, NULL);
         }
```

In command_event.c/event_cmd_ctl:
```
case EVENT_CMD_NETPLAY_FLIP_PLAYERS:
#ifdef HAVE_NETPLAY
         netplay_driver_ctl(RARCH_NETPLAY_CTL_FLIP_PLAYERS, NULL);
#endif
         break;
```

I'm guessing the netplay side of this should either call netplay_flip_users or copy what netplay_get_cmd does since that does seem to have some kind of user-flipping support. Or at the very least stub out some code so that pressing 'i' doesn't crash the program anymore.

**Comment by twinaphex** [comment]
Pushed a possible fix.

https://github.com/libretro/RetroArch/commit/6a814229e1c865424e6a3cd09e46ecfe7283b7b6

**Comment by fr500** [comment]
@poisson reopen if it's still crashing, thanks.
