### ISSUE TITLE
bilinear integer prescaling

### ISSUE THREAD

**Issue by phly95** [libretro/RetroArch#2846]
As seen on the forum http://libretro.com/forums/showthread.php?t=1162 Bilinear filtering can be improved. It would be good to have an integer prescaling above bilinear filtering so the pixels are multiplied X amount of times and then scaled down through bilinear filtering to make a sharper image.

This would be without the use of shaders because many consoles do not support the use of GPU shaders like the 3ds, wii, psp, etc.

**Comment by SuperrSonic** [comment]
https://github.com/libretro/RetroArch/issues/656

Unfortunately it takes platform specific effort to do this without performance drop, I know it's possible to do on GameCube/Wii; Enhanced mGBA does it (it even does Scale2x and Eagle2x this way!).

On 3DS it's also likely possible, GBA VC titles that use agb_firm have it, the internet browser also has it for zoom.

On the CPU side it's very easy to do because of the soft filters. [Example](https://github.com/SuperrSonic/RA-SS/blob/master/gfx/filters/normal2x.c)

**Comment by Themaister** [comment]
This is also trivial to do with shaders. Just have a prepass that scales N times with nearest filter and let final bilinear do the rest.

**Comment by Hyllian** [comment]
Or use Quilez or Smoothstep shaders.

**Comment by phly95** [comment]
Are there any CPU filters that do this?

**Comment by matcarfer** [comment]
This would be great as some users like me hate the blurry image that bilinear produces.

**Comment by Hyllian** [comment]
Why would someone make cpu filters if there are a bunch of shaders
available that do the same effect?

**Comment by phly95** [comment]
Because this bug report focuses on portable devices and consoles that don't support shaders. Shaders work great on PC, and I'm all for it, but it doesn't do much good when I'm on my 3DS.

**Comment by Hyllian** [comment]
Ok, my bad. I didn't see you're referring to 3ds.

**Comment by 44100hertz** [comment]
Wouldn't a 2x nearest CPU video filter be enough?

**Comment by phly95** [comment]
Likely, maybe even add 4x to 8x filters just to have added flexibility

**Comment by SuperrSonic** [comment]
mGBA just got this feature for 3DS and Wii, tested on Wii and there's no fps drops. Could these changes be potentially ported to their respective ports?

Wii https://github.com/mgba-emu/mgba/commit/8dbef1f0e33cec18552573c1e907588b98a1b0ee
3DS https://github.com/mgba-emu/mgba/commit/526f86d08529aa8f501cb015c1e442aa743940da

**Comment by hizzlekizzle** [comment]
We now have some prescaling CPU filters for use with platforms that don't support shaders, so I think we can close this.
