### ISSUE TITLE
RetroArch Wii VBA Next crashes at certain points in certain games

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [libretro/RetroArch#2847]
RetroArch Wii version - 1.3.2

Homebrew Channel version - 1.1.0

Wii version: 4.3U

Issue(s): So far two games I have played on the VBA Next emulator for the Wii that I am having issues with are as follows:

Mega Man Zero 2: When I enter the boss room at the Temple of Wind, a DSI exception error occurs and the whole thing reboots.

Castlevania: Harmony of Dissonance: In the Skeleton Cave, I enter a certain room and the screen goes black, freezes up, and makes a whistling sound,

I've tried turning off cheat codes but I don't know what the problem is.  I want to play these on mGBA but cheats don't work for that yet.  Please help me, I'm going crazy.  If I have any similar issues with other games I will let you know

**Comment by fr500** [comment]
Please open this in the correct repo
https://github.com/libretro/vba-next
