### ISSUE TITLE
Pressing back button crashes in menu screen

### ISSUE THREAD

**Issue by FeRcHuLeS** [libretro/RetroArch#2848]
This happens in my Sony Xperia X10a, and doesnt affect while playing, I think you should give this button the function to go back in menu options screen.

**Comment by fr500** [comment]
It's actually mapped like that but idk about a 2.3 device it's too old by now

**Comment by FeRcHuLeS** [comment]
Actually every button but the home button freezes the xperia x10a, I've just noticed it.

**Comment by fr500** [comment]
Feel free to comment, not much we can do on a 2.3 device but any further info would be appreciated, until then this qualifies as unconfirmed
