### ISSUE TITLE
Dualshock 3 controller is configured as 8k_handset 

### ISSUE THREAD

**Issue by FeRcHuLeS** [libretro/RetroArch#2849]
The original DS3 controller I tested is recognized as 8k_handset and pressing any button only pause the game and It can be unpaused by pressing the screen, I'm using latest sixaxis controller apk, Sony Xperia X10a, android version 2.3.3

**Comment by fr500** [comment]
It's mapping correctly on my end.
Android 2.3 lacks the ability to check VID/PID or device name so who knows what it's using.

While it still works on 2.3 none of us have a 2.3 device to test your setup.

**Comment by FeRcHuLeS** [comment]
I succeded working the ds3 controller by emulating a keyboard but often disconnects...

**Comment by fr500** [comment]
Feel free to comment, not much we can do on a 2.3 device but any further info would be appreciated
