### ISSUE TITLE
retropie not saving name changes?

### ISSUE THREAD

**Issue by sms5138** [libretro/RetroArch#2858]
Hi everyone!

I'm pretty new to raspberry pi, but am having a great time with it so far. I loaded up retropie, and i'm getting an odd issue. When i change the name of a game by editing the metadata it works fine, but the system restarts it doesn't seem to keep the change. 

an example would be changing "&amp;" to just "&", but on reboot it goes back to "&amp;".

I've found some articles about an issue with the scraper, but i'm not quite sure if this is the same thing as i'm trying to make a few simple changes to the title itself.

thanks in advance for any advice, or resources, you may have.

**Comment by joolswills** [comment]
This is neither the RetroPie issue tracker nor the EmulationStation tracker - you could mention this either https://github.com/Herdinger/EmulationStation (new fork of ES), or on the RetroPie forum.

**Comment by sms5138** [comment]
oh my apologies. thanks for the advice. i'll move my request over there!

**Comment by joolswills** [comment]
Please close this ticket also. Thanks.
