### ISSUE TITLE
System freezes if put into sleep mode with Retroarch suspended

### ISSUE THREAD

**Issue by Chocobubba** [libretro/RetroArch#2882]
Tested on: New 3DS, latest Retroarch nightly
If you suspend retroarch and go into sleep mode the entire system freezes and needs to be rebooted. Issue does not occur if retroarch is closed or resumed.

**Comment by FateForWindows** [comment]
This is a libctru issue. Newer versions don't have this problem.

**Comment by gingerbeardman** [comment]
Sleep whilst running RetroArch on N3DS works fine in 1.7.2

So this can be closed?

**Comment by twinaphex** [comment]
@meepingsnesroms says this can be closed now.
