### ISSUE TITLE
EXC_I386_DIV crash on starting craft core - OSX 10.11.3 

### ISSUE THREAD

**Issue by johanvdb** [libretro/RetroArch#2889]
I get a consistent crash on every start of the Minecraft core. I tried the x86_64 non-CG downloads for 1.3.0, 1.3.1, 1.3.2, 1.3.3.

I copy the .app to a user-writable folder on my desktop, run the app, make no configuration changes apart from installing the Minecraft core, load the core then start it. I get a white window, approx 100x100 for about 100ms, then the crash.

EXC_I386_DIV (divide by zero) on craft_libretro.dylib main_run + 3510

Test and TestGL cores run fine.

http://pastebin.com/eHaUJ1H5

**Comment by twinaphex** [comment]
There seem to be nasty segfaults indeed with this core. Unfortunately I have no idea what causes them.

**Comment by fr500** [comment]
In any case this is a core issue, so closing it here for the time being
You could reopen it here: https://github.com/libretro/Craft/
