### ISSUE TITLE
de-hardcode menu search keyboard assignment

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#2902]
It seems the menu search hotkey can be remapped on the gamepad but there doesn't seem to be any way to change the default assignment of fwd-slash on the keyboard. This can be a problem for people using joysticks that present as keyboards, etc.

**Comment by zoltanvb** [comment]
Forward slash as a menu hotkey is part of the "non-unified" menu hotkeys:
https://github.com/libretro/RetroArch/blob/a0bcf7945d4e46e4088ca36ba2fe9c2877036c6d/input/input_driver.c#L7021

There is indeed no configuration option for any of those in the list, but normal keypad bindings can be redefined, including button X, default key "s", so maybe it is not a limitation any more.

**Comment by hizzlekizzle** [comment]
There's an option to disable search now, which I think fixes the issue as it was reported to me (that is, old keyboard encoder that uses fwd-slash for something or other... maybe some P2 action?), so I think we're good to close it out.
