### ISSUE TITLE
RetroArch 1.3.3 crashes when closing or re-opening Mame ROMs

### ISSUE THREAD

**Issue by M3TALHEAD** [libretro/RetroArch#2903]
There seems to be an issue when closing or opening a different rom in mame causing RetroArch to crash for Windows PC.
If I open any mame rom with latest version "mame_libretro.dll" version .172 then hit F1, and close the rom or open a different rom RetroArch crashes.

Only Mame cores seem to be affected by this, mame, mame2000, mame2010 and mame2014.

Here is my setup:
Win 10 v1511 x64 Home (latest)
RetroArch 1.3.3 x64 (latest nightly)  and  RetroArch 1.3.2 x64
Mame 0.172 x64 (latest)  and  Mame 0.170 x64

**Comment by fr500** [comment]
It's not crashing,  it's shutting down and I think its fixed ready and of not I'm sure there's an issue already,.

**Comment by francogp** [comment]
I'm having the same problem... it start to load the rom and then crash to desktop with any mame core
