### ISSUE TITLE
Core detection not working with playlists "no cores available"

### ISSUE THREAD

**Issue by M3TALHEAD** [libretro/RetroArch#2904]
Playlists do not load the correct corresponding core(s).
Here is how to re-enact the issue.
1. Fresh install of RetroArch 1.3.2 or 1.3.3
2. Update core
3. Scan directory for Rom
4. Navigate to Playlist that gets generated, try to run it but displays "no cores available".

The cores are available so the detect feature is not working.
Playlist looks good but the auto core detection functionality seems broken in this release with any core.

**Comment by fr500** [comment]
As stated in numerous posts on the forums, the info files are missing in those two bundles,  human mistake. 

Set an info dir and update info files. 
Not a dev issue.

**Comment by M3TALHEAD** [comment]
Even when setting the info setting to the correct folder, I am getting "no
cores avaialbe".
The playlist file seems to be swapping around the detect features.
Here is a sample list of my SNES playlist file with two games.

D:\RetroArch\ROMS\Street Fighter II Turbo - Hyper Fighting (USA).sfc
Street Fighter II Turbo (USA)
D:\RetroArch\cores\snes9x_libretro.dll
Snes9x
A45CADD6|crc
Nintendo - Super Nintendo Entertainment System.lpl
D:\RetroArch\ROMS\Super Mario All-Stars + Super Mario World (USA).sfc
Super Mario All-Stars + Super Mario World (USA)
DETECT
DETECT
F84305B1|crc
Nintendo - Super Nintendo Entertainment System.lpl

When you load a game, somehow the playlist file is being written, and
detect detect lines are there again after loading a game.
The screen flashes too indicating something is buggy.
Please re-open ticket as this is not resolved and is a major bug.

On Mon, Apr 25, 2016 at 9:57 PM, Andrés <notifications@github.com> wrote:

> As stated in numerous posts on the forums, the info files are missing in
> those two bundles, human mistake.
>
> Set an info dir and update info files.
> Not a dev issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/libretro/RetroArch/issues/2904#issuecomment-214616579>
>



-- 
*Tony Yengo*
yengoman@hotmail.com

**Comment by fr500** [comment]
It is not,  you're using outdated code and we can't reproduce. As I said,
set a core dir and update the info files it WILL work after that. And
download cores of course.

We've had numerous reports of this.
