### ISSUE TITLE
cannot load many cores in recent ios9 builds

### ISSUE THREAD

**Issue by Jenyang** [libretro/RetroArch#2905]
Hi developers, first thanks for all your hard work, I would like to report that I find recent ios9 retroarch builds cannot load mednafen psx, pcsx_rearmed_interpreter, MAME2003 and MAME cores, but 2048 and FBA cores still work fine. As I remember mednafen psx and pcsx rearmed work perfectly in Febuary io9 build, but somehow it doesn't work now. Below are the reproduce steps:
1. Download the latest ios9 retroarch build from Cydia
2. Online update to download mednafen psx, pcsx_rearmed interpreter version, MAME2003 and MAME cores
3. Online update to download overlay
4. Place all the required BIOS into retroarch system folder
5. Click load cores for above four cores, but none of them work, retroarch always shows "no cores" (but from system information, I can see those cores' info)

**Comment by oliviercharavel** [comment]
I went through a similar issue but the difference is my devices are not jailbroken. Maybe these cores for the Online Updater are no longer built for iOS 9 ?

What worked for me: Clone the libretro-super repo (https://github.com/libretro/libretro-super) and build them for iOS 9 with the proper command " ./libretro-build-ios9.sh ". 😊

**Comment by Cepheidsong** [comment]
Ah that makes sense if the cores are not for iOS 9 version.  All the broken cores are like updated within the past month and a half, but the older, non-updated cores still work, wrong ones maybe put in.

**Comment by Cepheidsong** [comment]
I'm unable to build cores on my own as I still can't get around this error (I'm brand new to figuring out git bash), but I got a set of old cores from a year ago- but they were compiled properly for ios9.  They all work, so it seems to confirm the solution to the issue even more.

**Comment by adespoton** [comment]
The best solution is probably using libretro-super to build your own cores.  Failing that, there's a repository that keeps ios9-built cores available for download.  To use them on a non-jailbroken device, you'll have to sign them before you install them.

**Comment by hizzlekizzle** [comment]
I believe this is fixed, so I'm going to close this issue.
