### ISSUE TITLE
Playlist won't Run a game the first time

### ISSUE THREAD

**Issue by M3TALHEAD** [libretro/RetroArch#2907]
Let me first state that I am only trying to help shed light on two bugs.
These issues can be replicated **every** time and if I have to submit a video I would be more then happy to.

The issue is once a new playlist is generated, you cannot run a rom the first time.
The screen flashes and does not load the core or Rom.
The playlist file does reflect the correct core for that particular Rom but it does not load.
RetroArch is editing the playlist correctly in the background which I have verified, but no core or rom gets loaded.
There are two suggestions that I would like to make when handling playlists and cores:

**Suggestion 1**: After scanning a directory for roms, have the playlist file generate all supported cores then instead of saving the playlist with "DETECT, DETECT" for each Rom.
**Suggestion 2**: After a new or updated playlist is created, you should be able to run a Rom / core the first time instead of having the screen flash and no roms or cores get loaded.
As of now, you have to run a rom once for every rom in the playlist in order for RetroArch to save the core information for that particular Rom which is very time consuming.

Yes I am using the latest build exe from nightly.
Yes I have updated the info folder and pointed RetroArch settings to the correct folder.

**Comment by sergiobenrocha2** [comment]
Related to #1893 

You can workaround it choosing a core for each database/list in:

Settings tab --> Playlists

**Comment by fr500** [comment]
You said auto detection wasn't working, is it or not?
Load Content (Detect) is working fine in all my devices

**Comment by M3TALHEAD** [comment]
In order for the Playlist settings to show in Settings --> Playlists, you need to have a playlist generated and is an unnecessary step.

At the end of the day, users should be able to scan a directory and have a playlist generated that can open the correct core and rom instantly. That is the point of playlists if I am not mistaken. To add a quick method to load roms and cores with a nice interface.

fr500, I can generate a playlist just fine, but I cannot load a rom from the playlist the first time. The screen flashes and nothing happens. In the back end, the playlist file gets written with the correct core name and path.

My suggestion is that the playlist should work on the first try, and the list should be auto generating the correct cores given the Roms name.

**Comment by fr500** [comment]
There are several core choices and you might want to run some games with a different core.
So until there is a way to change the core for a particular rom from within the gui this can't be implemented.

**Comment by M3TALHEAD** [comment]
Let me know of a different core for the N64 playform and I'll try it.

**Comment by fr500** [comment]
What? How is that related. We don't cater to the more specific usecases, we cater to common use cases.
Now you're arguing for no reason.

**Comment by M3TALHEAD** [comment]
Please don't turn this into a stereotypical flame battle, that is not my intent.
I do not argue and will not argue in a forum in which I am trying to help make a great product even better.

This is a universal RetroArch issue, and not specific to any core.
Playlists as they sit right now do not work 100% and could use some help.
My suggestions can help improve the intent of the UI which is an easier navigation between various cores and roms.

Sergio offered a viable work around however I think my findings can help improve on the next build to help the general public with their RetroArch UI frustration.

**Comment by Kivutar** [comment]
The thing is since users can create their own playlists, like "All Final Fantasy Games.lpl", we can't know the name of the playlist before they create it.

**Comment by sergiobenrocha2** [comment]
For SNES you have dozen cores.

2016-04-26 13:27 GMT-03:00 M3TALHEAD <notifications@github.com>:

**Comment by Kivutar** [comment]
He's still right that the current playlist status can generate frustration.

For example, we could launch the game directly after the core is assignated to the playlist entry. This would avoid an extra step.

**Comment by M3TALHEAD** [comment]
Yes, I am trying to avoid those extra steps if possible.
That is the point of this thread or at least it was supposed to.
The more automation, the better.

**Comment by fr500** [comment]
@Kivutar that part I agree, yes, that is a bug and I think it's open already

But we can't realistically assign a default core automatically, it's not impossible but very difficult to determine a default core via heuristics and it SHOULD NOT be done until we have a way to change the core for an entry via GUI. Also we can't ask after scanning, remember that the scanning process is async an non-blocking, and you wouldn't want a "Select core" pop-up appearing at random at any given moment.

So we either make the process blocking, and ask for a default core (which is problematic, you might want to use another core for a specific game)  or we fix the real issues, add a submenu to change the default core or we add a "clear core" action or something like that.

There are issues regarding these problems already, and we have discussed the problems already.

https://github.com/libretro/RetroArch/issues/2434
https://github.com/libretro/RetroArch/issues/2731

**Comment by Kivutar** [comment]
Yes, I agree that we should avoid tricky things that will make the situation even worse.

**Comment by M3TALHEAD** [comment]
Awesome, thanks for the response man.

**Comment by orbea** [comment]
Closing this in favor of the older issue https://github.com/libretro/RetroArch/issues/1893.
