### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#2912]
Pretty straight forward feature request. I'd eventually hope to see an option to have the online updater run automatically for main retroarch files and any cores you have installed. Low priority, obviously. This could either happen at launch or whenever the files aren't currently in use.

**Comment by fr500** [comment]
No ETA, it's an enhancement, and not one without complications depending on the platform.

**Comment by fr500** [comment]
Closing, newer issue covers the same topic leaving that one open instead for visibility.
