### ISSUE TITLE
Cannot specify ips patch on command line

### ISSUE THREAD

**Issue by escondida** [libretro/RetroArch#2920]
The manual suggests that --ips=path/to/some/file.ips should load that fileas a patch for the specified game, but the flag does not seem to do anything. 

Tried: passing absolute and relative paths, running retroarch from same directory as emulated game, renaming patch to same name as game but with extension ".ips", rearranging the command-line order, and combinations of all these things.

strace recognizes that the file is passed on the command line, but reports that no attempt whatsoever is made to open it.

To reproduce: retroarch -L /path/to/some_libretro.so /path/to/a/game --ips=/path/to/a/patch.ips

**Comment by escondida** [comment]
My mistake; it turns out that the implementation specifies need_fullpath, blocking the patch.

**Comment by fr500** [comment]
it should be made to work in that case too I guess pre-patching the rom or something we'll have to think about it

**Comment by orbea** [comment]
I am going to close this issue in favor of https://github.com/libretro/RetroArch/issues/2878 which has more discussion.
