### ISSUE TITLE
Auto config broken on OSX

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2925]
The folder in the bundle is called **autoconf** while the autoconfig dir is set to **autoconfig**.

**Comment by Kivutar** [comment]
I can't find anything wrong about this in the platform_drawin.m

However, I can see that platform_win32.c is using **autoconf** while platform_darwin.m is using **autoconfig**. And platform_linux.c have references to both **autoconf** and **autoconfig**!

libretro-buildbot-recipe.sh is also using **sometimes one, sometimes the other**, depending on the platform.

fetch-submodules.sh is using **autoconfig**

**Comment by twinaphex** [comment]
we should standardize this yes.

lets go for autoconfig.

**Comment by Kivutar** [comment]
Ok, a first PR here https://github.com/libretro/RetroArch/pull/2929
Another one will come on libretro-super

**Comment by Kivutar** [comment]
Here https://github.com/libretro/libretro-super/pull/283

Are there other places where these changes should happen?

**Comment by Kivutar** [comment]
Fixed
