### ISSUE TITLE
XBOX 360 Controller not recognized by OSX

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#2926]
My dualshock 3 works out of the box on OSX. While my XBOX 360 pad doesnt. It doesn't even show up in RetroArch.

I'm not sure if it is a RetroArch bug or simply an OSX bug.

**Comment by twinaphex** [comment]
OSX does not support xbox 360 pads out of the box.

it is also quite convoluted to get it to work, unlike the low level dualshock3/4 drivers we have written so far.

**Comment by gouchi** [comment]
@Kivutar  you may try this [driver](https://github.com/360Controller/360Controller) ?

**Comment by Kivutar** [comment]
Ok thanks
