### ISSUE TITLE
Numpad ('keypad') bindings incorrect under Xorg

### ISSUE THREAD

**Issue by Veyrdite** [libretro/RetroArch#2932]
## Problem

I am using my keyboard numpad as my A B X Y buttons.  The Linux modeset framebuffer environment uses the expected names for these keys whilst the Xorg environment does not.

| Description in rgui | Physical key on numpad | Keyname when using Xorg | Keyname when using framebuffer |
| --- | --- | --- | --- |
| B button (down) | 2 (bottom) | keypad1 | keypad2 |
| Y button (left) | 4 (left) | keypad2 | keypad4 |
| A button (right) | 6 (right) | keypad3 | keypad6 |
| X button (top) | 8 (top) | keypad0 | keypad8 |
### System

Kernel: Linux Shyarenris 4.5.2_1 #1 SMP PREEMPT Wed Apr 20 08:16:49 UTC 2016 x86_64 GNU/Linux
Distro: Void Linux
Graphics: Open-source ATI (in-kernel, not fglrx)
### Retroarch

val@shy ~ $ retroarch --version
RetroArch: Frontend for libretro -- v1.3.2Compiler: GCC (4.9.3) 64-bitBuilt: Mar 17 2016

**Comment by orbea** [comment]
This has improved since this issue has been made, now the keycodes seem right with both input drivers, but they can only be bound to the buttons with udev. Binding them to the d-pad works fine with both.
