### ISSUE TITLE
1.3.4 --enable-nuklear compile fails

### ISSUE THREAD

**Issue by Geyup** [libretro/RetroArch#2938]
In Linux when I enabled --enable-nuklear and tried to compile 1.3.4 it fails with this output;

CC menu/drivers/nk_common.c
In file included from menu/drivers/nk_common.h:25:0,
                 from menu/drivers/nk_common.c:28:
menu/drivers/../../deps/zahnrad/nuklear.h:2790:15: warning: ‘nk_to_upper’ defined but not used [-Wunused-function]
 NK_INTERN int nk_to_upper(int c) {return (c >= 'a' && c <= 'z') ? (c - ('a' - 'A')) : c;}
               ^
In file included from menu/drivers/nk_common.h:25:0,
                 from menu/drivers/nk_common.c:28:
menu/drivers/../../deps/zahnrad/nuklear.h: In function ‘nk_end’:
menu/drivers/../../deps/zahnrad/nuklear.h:12503:10: warning: ‘state’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     else nk_draw_scrollbar(out, *state, style, &scroll, &cursor);
          ^
menu/drivers/../../deps/zahnrad/nuklear.h:15680:22: note: ‘state’ was declared here
             nk_flags state;
                      ^
CC menu/drivers/nk_menu.c
menu/drivers/nk_menu.c: In function ‘nk_menu_wnd_test’:
menu/drivers/nk_menu.c:356:16: warning: variable ‘size’ set but not used [-Wunused-but-set-variable]
       unsigned size;
                ^
CC menu/drivers/nuklear.c
menu/drivers/nuklear.c: In function ‘nk_menu_init’:
menu/drivers/nuklear.c:327:53: error: ‘settings_t’ has no member named ‘assets_directory’
    fill_pathname_join(nk->assets_directory, settings->assets_directory,
                                                     ^
menu/drivers/nuklear.c: In function ‘nk_menu_context_reset’:
menu/drivers/nuklear.c:388:41: error: ‘settings_t’ has no member named ‘assets_directory’
    fill_pathname_join(iconpath, settings->assets_directory,
                                         ^
menu/drivers/nuklear.c:398:45: error: ‘struct <anonymous>’ has no member named ‘wallpaper’
    rarch_task_push_image_load(settings->menu.wallpaper, "cb_menu_wallpaper",
                                             ^
make: *** [obj-unix/menu/drivers/nuklear.o] Error 1

**Comment by twinaphex** [comment]
Pushed a fix - 
https://github.com/libretro/RetroArch/commit/93df66ea2fa3804086fd0b9764e7b5d3e77f70bd

**Comment by Geyup** [comment]
I created a patch and applied it, it now compiles ok... :)

But when I start RetroArch and put it on nuklear, this is what I see below, should this work, or is this still in the works?

![nuklear](https://cloud.githubusercontent.com/assets/13072581/15003666/bfd3b822-119d-11e6-90be-d97a3078bb4e.jpg)

**Comment by fr500** [comment]
it's just a very early WIP.
There were many other more functional windows but I had to ditch most of that when rebasing zahnrad into nuklear.

I'll start working on that again next month hopefully

**Comment by Geyup** [comment]
Ahh ok no worries.... I really like xmb

**Comment by fr500** [comment]
This will be THE menu driver, in a year or so.
:+1:

**Comment by Geyup** [comment]
xmb flatui icons missing...
