### ISSUE TITLE
Saves are not working

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2940]
Maybe saves are not working on android, probably external card? VBA Next is ok on linux

It's working on my android device, but it's rooted...

https://www.reddit.com/r/RetroArch/comments/4hhg0q/when_i_save_in_game_it_doesnt_work/

**Comment by fr500** [comment]
It's saving for me,

**Comment by sonic65101** [comment]
Saves are not working for me either. My phone is running Android 6.0 and is not rooted. I can't get it to create save files on my SD card, the phone's internal memory, or the part of the SD card formatted as internal memory.

**Comment by fr500** [comment]
Is there a RetroArch folder in the internal SDcard? ti should have some internal folders.
If there is then RetroArch can in fact write to that partition and you can set the save dirs to that.

**Comment by sonic65101** [comment]
I found a RetroArch folder, I'll try it and see if it works.

**Comment by sonic65101** [comment]
Thanks. It worked like a charm.

**Comment by orbea** [comment]
This seems resolved in the previous comment, please complain if this is still a problem.
