### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#2941]
I can confirm this in a VM, but it's not crashing.

```
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 656812408 (0x27262978)
 at -e line 15.
```

https://www.reddit.com/r/emulation/comments/4hllqh/retroarch_134_released/d2rhe85

**Comment by orbea** [comment]
@sergiobenrocha2 Is this still a problem?

**Comment by mrcmunir** [comment]
Still happen under nvidia jetson nano when ./Retroarch
Protocol error: bad 3 (Window); Sequence Number 13
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 16.
Only warning not crash .

**Comment by hizzlekizzle** [comment]
I believe this is a normal error caused by the program trying and failing to suspend the X11 screensaver. I'm going to close this issue as "wontfix"
