### ISSUE TITLE
"No items" in sshfs directory

### ISSUE THREAD

**Issue by drschwabe** [libretro/RetroArch#2946]
Am trying to access content from a drive mounted via sshfs

I can browse the files fine in my OS (Ubuntu 16.04) but they do not appear in RetroArch.  

When you Load Content > Select File > and point to the sshfs folder RetroArch just says "No items." as if nothing is there. 

I mount with just: 
```
sshfs remoteSystem:/home/drschwabe/roms roms 
```
Using latest RetroArch master branch commit 400f50d but also have tried previous commits same problem. 

Is anyone, or can someone try, mounting an sshfs folder with Linux build?   

Thanks in advance.

**Comment by bmbob** [comment]
Noticed the same issue today, folders inside fuse filesystem (smbnetfs or sshfs) not detected as folders.
Had some old archives from ubuntu ppa and for me r329 works while r331 does not work.

Seems like the change happened between these:
retroarch_1.3.0+r329~34~ubuntu15.10.1_amd64.deb (local file date 18. apr)
retroarch_1.3.0+r331~34~ubuntu15.10.1_amd64.deb (local file date 22. apr)

**Comment by fr500** [comment]
thanks for the bisect

**Comment by fr500** [comment]
Can you guys test with this commit?
https://github.com/zeromus/libretro-common/commits/fix_dirent

**Comment by drschwabe** [comment]
Tried but using that libretro-common/commit my system fails to compile RetroArch: 
```
$ make
make: *** No rule to make target 'libretro-common/include/compat/../../../config.h', needed by 'obj-unix/input/drivers/linuxraw_input.o'.  Stop.
```

**Comment by sronsse** [comment]
Try calling "make clean" beforehand and redoing it (possibly re-running ./configure beforehand as well).

**Comment by drschwabe** [comment]
Thanks, that yielded different results; though it seems my system won't build the latest RetroArch commit 400f50ddac72741cd4f3e21aac79013cdcdaf862

```
$ make
CC input/drivers/linuxraw_input.c
CC input/common/linux_common.c
CC input/common/epoll_common.c
CC input/drivers_joypad/linuxraw_joypad.c
CC frontend/drivers/platform_linux.c
CC git_version.c
CC frontend/frontend.c
CC frontend/frontend_driver.c
CC frontend/drivers/platform_null.c
CC ui/ui_companion_driver.c
CC ui/drivers/ui_null.c
CC core_impl.c
CC retroarch.c
CC input/input_keyboard.c
CC command.c
command.c: In function ‘command_event’:
command.c:1630:12: error: ‘CMD_EVENT_LOAD_CONTENT_FFMPEG’ undeclared (first use in this function)
       case CMD_EVENT_LOAD_CONTENT_FFMPEG:
            ^
command.c:1630:12: note: each undeclared identifier is reported only once for each function it appears in
Makefile:130: recipe for target 'obj-unix/command.o' failed
make: *** [obj-unix/command.o] Error 1
```

So I did git reset --hard HEAD^, ran make clean, ./configure and make on each commit going back until I could get a successful compile; and found 5ad45ea17f49c4735d3f0d71d1849e4209651bf5 which worked; it's only a handful of commits back. 

Anyway, with that commit confirmed working I proceeded to test the zeromus fix_dirent https://github.com/zeromus/libretro-common/commit/187985000a0117c18b4b79bbffa6f203adcbbf9f as suggested.  Ran make clean, removed/replaced with the new libretro-common, and then ./configure but got this similar error: 

```
make -j8
CC input/drivers/linuxraw_input.c
CC input/common/linux_common.c
CC input/common/epoll_common.c
CC frontend/drivers/platform_linux.c
CC input/drivers_joypad/linuxraw_joypad.c
CC git_version.c
CC frontend/frontend.c
In file included from input/drivers/../../configuration.h:24:0,
                 from input/drivers/linuxraw_input.c:26:
input/drivers/../../gfx/video_driver.h:25:22: fatal error: libretro.h: No such file or directory
compilation terminated.
Makefile:130: recipe for target 'obj-unix/input/drivers/linuxraw_input.o' failed
make: *** [obj-unix/input/drivers/linuxraw_input.o] Error 1
make: *** Waiting for unfinished jobs....
CC frontend/frontend_driver.c
In file included from input/common/../../verbosity.h:24:0,
                 from input/common/epoll_common.c:24:
./libretro-common/include/compat/strl.h:30:29: fatal error: ../../../config.h: No such file or directory
compilation terminated.
Makefile:130: recipe for target 'obj-unix/input/common/epoll_common.o' failed
make: *** [obj-unix/input/common/epoll_common.o] Error 1
In file included from frontend/frontend_driver.c:19:0:
./libretro-common/include/compat/strl.h:30:29: fatal error: ../../../config.h: No such file or directory
compilation terminated.
Makefile:130: recipe for target 'obj-unix/frontend/frontend_driver.o' failed
make: *** [obj-unix/frontend/frontend_driver.o] Error 1
In file included from frontend/drivers/platform_linux.c:41:0:
./libretro-common/include/compat/strl.h:30:29: fatal error: ../../../config.h: No such file or directory
compilation terminated.
In file included from input/drivers_joypad/../../general.h:22:0,
                 from input/drivers_joypad/linuxraw_joypad.c:28:
./libretro-common/include/compat/strl.h:30:29: fatal error: ../../../config.h: No such file or directory
compilation terminated.
Makefile:130: recipe for target 'obj-unix/frontend/drivers/platform_linux.o' failed
make: *** [obj-unix/frontend/drivers/platform_linux.o] Error 1
Makefile:130: recipe for target 'obj-unix/input/drivers_joypad/linuxraw_joypad.o' failed
make: *** [obj-unix/input/drivers_joypad/linuxraw_joypad.o] Error 1
In file included from frontend/frontend.c:31:0:
frontend/../system.h:20:22: fatal error: libretro.h: No such file or directory
compilation terminated.
Makefile:130: recipe for target 'obj-unix/frontend/frontend.o' failed
make: *** [obj-unix/frontend/frontend.o] Error 1
```

**Comment by bmbob** [comment]
Used fresh RetroArch master and patch from https://github.com/zeromus/libretro-common/commit/187985000a0117c18b4b79bbffa6f203adcbbf9f. Added `#include <retro_miscellaneous.h>` to retro_dirent.c to get it to compile (missing PATH_MAX_LENGTH).

Got this error on trying to browse any folder:
```
Assertion failed at libretro-common/file/file_path.c:569.
Aborted
```

gdb gave this:
```
Program received signal SIGABRT, Aborted.
0x00007ffff3307cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

```

**Comment by bmbob** [comment]
Reading sshfs and exfat (fuse) works again after commit 377f09f12a51a6a50e31decf68f54bd0cf9eab39. Thanks!
