### ISSUE TITLE
Downloading multiple updates at once crashes Retroarch

### ISSUE THREAD

**Issue by IamCarbonMan** [libretro/RetroArch#2956]
Selecting to update an item in the online updater menu without allowing the previous download to finish will cause Retroarch to crash, with command line output showing the download and extracting of the two updates simultaneously, and then quickly crashing with "Bus error."

**Comment by twinaphex** [comment]
Are you trying this with the latest source? I believe @sronsse has already fixed this issue and it should appear in the next stable version.

**Comment by IamCarbonMan** [comment]
I am using the PPA on Ubuntu 15.04. Output of `retroarch --version`: `RetroArch: Frontend for libretro -- v1.3.4Compiler: GCC (4.9.2) 64-bitBuilt: May  4 2016`

**Comment by sronsse** [comment]
Hi, would you mind testing from source? Just clone github's repository, then call ./configure && make. I experienced that issue on a similar setup and fixed it two days ago, it is now included in master, but it would be helpful if you could check it as well. Thanks!

**Comment by IamCarbonMan** [comment]
Just built from cloned repo. It looks for all the drivers and cannot find any, so it aborts.
I will actually be away from my PC for now, but I would also point out that `apt-get dist-upgrade` gets me an upgrade for retroarch nearly every day. So if you pushed something two days ago, it should be coming to me very soon.

**Comment by sronsse** [comment]
I am surprised you get RetroArch updates as often - my understanding is that the Ubuntu PPA was just updated with 1.3.4 and the previous version was 1.3.0. Regarding the drivers not being found, my guess is that you might be missing some development libraries. In any case, I would suggest waiting for the next version and give us your feedback in regards to this issue (unless you get the chance to figure out why the latest master is not running on your system).

**Comment by sergiobenrocha2** [comment]
The testing PPA is updated at least once a week (for the retroarch package)

**Comment by IamCarbonMan** [comment]
Yeah, I'm on testing. Anyways, I'll report back when I get an update through there.

**Comment by IamCarbonMan** [comment]
Sure enough. Just got pushed an update with the fix, the files in question will not be downloaded if selected more than once, but instead the console will print a message along the lines of "file x is already being downloaded".

**Comment by sronsse** [comment]
Nice, thanks for testing again. Yep - this message was in place before but there was a deeper multi-threading issue we had to fix to actually make it function, glad it worked out!
