### ISSUE TITLE
CG-shaders not working via gui in Retroarch 1.3.4 stable [Possibly multiplatform issue]

### ISSUE THREAD

**Issue by amnesiac-kid** [libretro/RetroArch#2963]
I am using Ubuntu 64 bit 16.04 LTS with Retroarch 1.3.4 stable from the ppa
These problems occured after the update to 1.3.4: 
If you try to add a cgp file or a cg file via the gui it isn't working.
Also the new xmb animation shows no difference between ribbon and ribbon simplified. 
The moment you try to add a cg shader it stops working like no shader is applied to the image, but the xmb changes to the enhanced ribbon animation. You also can't switch to another cgp or manually add another pass with a cg file. The only thing that works are glsl shaders. If you add a glsl shader it works again and the xmb animation switches back to ribbon simplified. The only shader that doesn't work even as glsl seems to be hyllian-crt.
This issue was discussed on two threads in the libretro forum [http://libretro.com/forums/showthread.php?t=5554](http://libretro.com/forums/showthread.php?t=5554) and [http://libretro.com/forums/showthread.php?t=5681](http://libretro.com/forums/showthread.php?t=5681 )

The only temporary fix I found is to open the core config files and look for the parameter "video_shader_enable" and set it to "true" if it was set to "false" by the gui malfunction. Secondly change the parameter "video_shader" to the shader you want to use. That is how I change my shaders at the moment. That way cg shaders work again.
For Windows there seems to be a solution if you switch the exe files with exes from the nightly build.

**Comment by fr500** [comment]
As you said it's fixed in nightlies

**Comment by amnesiac-kid** [comment]
How long will it approximately take to get fixed in stable?
