### ISSUE TITLE
Vulkan doesn't work on Windows

### ISSUE THREAD

**Issue by Lithium64** [libretro/RetroArch#2965]
I'm trying to use vulkan on my desktop, but it doesn't work, even setting on retroarch.cfg video_driver = "vulkan" the api running is OpenGL.

I'm a R7 260X gpu and Windows 10 user, but the retroarch identifies my system as Windows 8 and that doesn't support vulkan api.
![retro1](https://cloud.githubusercontent.com/assets/10705488/15096274/1af00616-14c8-11e6-966f-835b0046ca8e.png)
![retro2](https://cloud.githubusercontent.com/assets/10705488/15096275/1af8b5cc-14c8-11e6-816e-0920337a26c3.png)

**Comment by fr500** [comment]
We don't build with vulkan support yet, that's about it.

**Comment by Lithium64** [comment]
@fr500 Thanks, I read the news about the release of the retroarch 1.3.4 that vulkan is working on windows so I decided to test.

**Comment by twinaphex** [comment]
I didnt know radius didnt bake it in on the buildbot side yet, so the blog post was inaccurate. It has been confirmed to work though.

**Comment by Themaister** [comment]
It is kinda in limbo until vsync issues are resolved. I have no way to test on Windows myself sadly. The Windows backend was implemented blind.

**Comment by twinaphex** [comment]
I merged the Vulkan driver into master now for Windows. Hopefully this way we can get anybody experienced AND who likes to use Windows to help us with the remaining issues. Letting it stay in limbo in some branch (ignored) is not achieving our goals to get this matured I think.

**Comment by twinaphex** [comment]
Should work on Windows now.
