### ISSUE TITLE
On open: Instant crash to desktop on iPad Air 2, since updating to 1.3.4 from previous stable

### ISSUE THREAD

**Issue by bsauvage1** [libretro/RetroArch#2966]

**Comment by fr500** [comment]
We need more information than that

**Comment by bsauvage1** [comment]
please let me know what I need to provide to help

**Comment by fr500** [comment]
well, a stacktrace if possible, does it happen if you remove and install again?
can you possibly launch with a debugger?

**Comment by Cepheidsong** [comment]
I'm having the same issue on my iphone6 9.0.2 jailbreak, tried uninstall-reinstall, tried deleting every file possible for a fresh install, cleaned up as much memory as possible.

App loads for a second, then crashes.  You can see the menu for a split second.  Sometimes when it crashes the graphics on the screen look a bit torn.  I wonder if it's a graphics issue with the fancier menu it loads with and the lower memory of i-devices?  (That's just a theory, not sure)

**Comment by twinaphex** [comment]
I only have one device on iOS 8.4 jailbreak, the other one is on iOS 9 non-jailbroken. 

I cannot test this. An iOS dev that can at least debug the issue in Xcode would be needed with the necessary hardware (jailbroken iOS 9).

**Comment by bsauvage1** [comment]
to add: my ipad air 2 is on 8.1.2. jailbroker with TAIG, I believe.

So @Twinaphex you should be seeing the same behaviour on your 8.4
jailbroken device?

Sorry I can't be of much further help here as I don't have a dev account.

**Comment by Cepheidsong** [comment]
The builds for 9 are different than anything below, I can't remember the reason, I think it's a 32-64 bit issue or something.  I know it affects the cores, can't load any cores built for below ios9.

I signed up for a dev account but I have no idea what I'm doing, haha.  But I'm going to try to help.  Trying to get xcode loaded and all.

**Comment by Jenyang** [comment]
Same here, I just try the latest ios9 nightly build from cydia, retroarch still crash instantly to desktop. My device is iPhone6s with 9.0.2 JB, I believe the nightly build in later April works fine.

**Comment by twinaphex** [comment]
Can you retest this again?

**Comment by bsauvage1** [comment]
Working for me now, for the past 2 days.

**Comment by twinaphex** [comment]
Nice.
