### ISSUE TITLE
Retroarch 1.3.4 can't read from a exfat microsd card

### ISSUE THREAD

**Issue by duskgao** [libretro/RetroArch#2969]
I update form retroarch 1.3.3 to 1.3.4 ,I found RA can't read my 128G microsd card(ra display :no items),but another 32g microsd card work fine.

It seems 1.3.4 can't support a exfat format sd card,but 1.3.3 does support it.

**Comment by fr500** [comment]
Did you test 1.3.3 again on the same fact setup just to be sure?

**Comment by bmbob** [comment]
I think this is related to https://github.com/libretro/RetroArch/issues/2946, as android use fuse for exfat.

**Comment by duskgao** [comment]
@fr500  yep, i rollback to 1.3.3,my 128g tf card work again...

**Comment by fr500** [comment]
Can you guys test with this commit?
https://github.com/zeromus/libretro-common/commits/fix_dirent

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/2946

**Comment by twinaphex** [comment]
@ duskgao Check if the latest nightly fixes this.

**Comment by twinaphex** [comment]
I'm going to assume this was fixed. Reopen in case it's not with the latest nightly.

**Comment by duskgao** [comment]
@twinaphex Great Work! I have tested nightly build 2016-5-13,my 128g tf card works again! thank you so much!!
