### ISSUE TITLE
SG-1000 Titles in 3DS Retroarch 1.3.4 Not Functioning

### ISSUE THREAD

**Issue by KubbaYioka** [libretro/RetroArch#2985]
Hi there.

I'm using the 1.3.4 stable build of the Genesis Plus GX core on an N3DS with a9lh. As far as I know, this particular core should work with sg-1000 titles, but I get a black screen after loading with no crash (menu still accessible via bottom screen).

**Comment by fr500** [comment]
Please report this in the correct repo. This is not a RetroArch issue.
https://github.com/libretro/Genesis-Plus-GX/
