### ISSUE TITLE
spir2cross submodule still referenced

### ISSUE THREAD

**Issue by hadess** [libretro/RetroArch#2987]
Fetching the submodules using git itself fails.

```
$ git clone https://github.com/libretro/RetroArch.git 
Cloning into 'RetroArch'...
remote: Counting objects: 182390, done.
remote: Compressing objects: 100% (265/265), done.
remote: Total 182390 (delta 150), reused 0 (delta 0), pack-reused 182108
Receiving objects: 100% (182390/182390), 97.96 MiB | 1.27 MiB/s, done.
Resolving deltas: 100% (135058/135058), done.
Checking connectivity... done.
$ cd RetroArch/
$ git submodule update
fatal: no submodule mapping found in .gitmodules for path 'deps/spir2cross'
$ git submodule status
-44ef367141f9935bc719c9cc25693a9055f61efa deps/SPIRV-Cross
-5ace09a75be02bd32505f1f94b1b49a6aa3498b8 deps/glslang/glslang
fatal: no submodule mapping found in .gitmodules for path 'deps/spir2cross'
```

**Comment by Themaister** [comment]
Try removing it from .git/config, it's probably just a stale reference locally.

**Comment by Alcaro** [comment]
Should be fixed as of 7a0ff59.

**Comment by hadess** [comment]
@Themaister the reproducer above was clone a clean tree, so it wasn't that.

@Alcaro yep, that fixed it, thanks!

**Comment by Alcaro** [comment]
git has WAY too many failure modes. Rebase in progress, detached HEAD, bisect in progress, merge conflict in progress, and now this... and then people wonder [why git is considered hard to use](https://xkcd.com/1597/). Someone should add a 'git panic' command that wipes all local changes and resets the repo to upstream.

...okay, a panic button wouldn't help for this subrepo issue, but it'd save me from a lot of google sessions elsewhere.

**Comment by Themaister** [comment]
@Alcaro thanks. Missed that one.
