### ISSUE TITLE
Screenshots inverted on Retroarch 1.3.4 OS X

### ISSUE THREAD

**Issue by davmanypsp** [libretro/RetroArch#2993]
With two different cores, taking a screenshot of a game produces a vertically inverted screenshot on OS X.
![retroarch-0512-153252](https://cloud.githubusercontent.com/assets/16816664/15216477/803c8048-1857-11e6-86dd-94f77d3622db.png)

**Comment by Kivutar** [comment]
Duplicate of this bug https://github.com/libretro/RetroArch/issues/2979 and fixed in master ;)

**Comment by fr500** [comment]
Are you certain it's the same? 
Is the screenshot BMP?

**Comment by davmanypsp** [comment]
Yes, it is BMP. I don't know how to choose the PNG format for the screenshots.

**Comment by fr500** [comment]
Ok, then in fact it's fixed
