### ISSUE TITLE
Scanning the same directory twice results in duplicate entries

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#2997]
yep.

**Comment by fr500** [comment]
Unless you are using an ancient version this doesn't happen. I personally fixed it a few months back.
I just tried on the current build, hitting Y 10 times in a row and.... nothing, the scan took a while due several scanning processes running at once and still, no duplicates.

Yep is not enough explanation. We need OS verison, RetroArch version and even the current commit if possible.

If you can reproduce this on a current build and can enumerate the steps to replicate reopen.
