### ISSUE TITLE
Donkey Kong 2: Jumpman Returns crushes when loaded with FBA cores

### ISSUE THREAD

**Issue by Fortranm** [libretro/RetroArch#2998]
dkongx.zip works fine with MAME cores but RetroArch crushes when the same file is loaded under FBA cores.

**Comment by Kivutar** [comment]
Arcade ROMs have what we call "sets". When you use FBA, you have to use the FBA rom set. When you use MAME, you have to use the MAME rom set.

And rom sets have versions too. So for FBA v0.2.97.38, you need the FBA rom set v0.2.97.38.

**Comment by Fortranm** [comment]
The same zip can run on the newest FBA release though.

**Comment by fr500** [comment]
Please reopen this on the FBA repo.
