### ISSUE TITLE
Crash on Android 6.0.1 (AArch64)

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#2999]
https://buildbot.libretro.com/nightly/android/2016-05-14-RetroArch.apk

logcat http://ix.io/Eb6

tombstone_05 http://ix.io/Eb7

Nexus 5X running 6.0.1 (MHC19Q)

**Comment by fr500** [comment]
this was fixed right? reopen if not

**Comment by parkerlreed** [comment]
Yeah fixed by https://github.com/libretro/RetroArch/commit/cd0b925fa12df0e13ed97d239870c927186d9ece
