### ISSUE TITLE
Playlists don't work in a subfolder

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#3000]
I've got that big Mame playlist generated with a script that is slow to open, so I try to keep it in a different place.
Then I could open it with "load from collection" manually when I want, I thought.
But nothing to do, it will always show "no playlist entries available".

I tried with a standard playlist generated by retroarch = same issue.
Anything in a subfolder of the playlists folder isn't working.

**Comment by Kivutar** [comment]
Load from collection will only list the playlists in your playlist_dir.
If you want to do like that, you need to switch your playlist_dir each time..

**Comment by Tatsuya79** [comment]
Big playlists got a lot faster to load now so I suppose I can close that up.
