### ISSUE TITLE
Mupen64 has some graphical issues on the last (1.3.4) RetroArch version for OS X.

### ISSUE THREAD

**Issue by ddnava** [libretro/RetroArch#3002]
I've had RetroArch for 2 years and I always liked it was the best emulator for N64 games, and it always got better on every update, being updated very frequently. (Unlike some other multi-emulator. Cough, OpenEmu, Cough).
But lately I updated RetroArch to the version that has the XMB-like menu (1.3.4) and I got some issues on some N64 games (and a slightly noticeable performance hit).

Here are some pics of Conker's Bad Fur Day. Issues are pretty clear (most of them being screen transitions; also present in other games like Mario Party 3)
![Pic 1](https://cloud.githubusercontent.com/assets/6321933/15272501/9e499c84-1a40-11e6-9820-cda65d54067b.png)
![Pic 2](https://cloud.githubusercontent.com/assets/6321933/15272503/9e57a45a-1a40-11e6-8e41-1da430522510.png)
![Pic 3](https://cloud.githubusercontent.com/assets/6321933/15272502/9e5005d8-1a40-11e6-8531-3c454082f99f.png)
![Pic 4](https://cloud.githubusercontent.com/assets/6321933/15272504/9e60fc3a-1a40-11e6-9b1e-0b723644b76c.png)
![Pic 5](https://cloud.githubusercontent.com/assets/6321933/15272505/9e69aee8-1a40-11e6-8e9f-fcbaa8e98d8f.png)

The previous version I had was 1.3.2 (I think. Can't remember for sure) and it didn't have these graphical bugs. Or maybe it was a core update that messed it up? Last time I updated before 1.3.4 was like 1 month ago. I tried this same version on a Mac Mini and it had the same issues.

Don't know if it helps, but I'm on a Macbook Pro 13" (2012).
Intel Core i5 @2.5 GHz
Intel HD Graphics 4000
4 GB RAM

Also, about the performance hit. Now I can't get full original speed on some parts of Mario 64 with a 640x480 resolution (let alone true full speed)

**Comment by twinaphex** [comment]
Which graphics plugin is this? Glide64?

**Comment by ddnava** [comment]
It is Glide64. Rice had less problems (no blue triangle on splash screen and correct transitions), but it still had that black box in the top-left corner whenever the FrameBuffer was supposed to be used (Yeah, and the drunken camera is black on both plugins, and maybe the matrix camera).
![Black box](https://cloud.githubusercontent.com/assets/6321933/15275181/20a72496-1a8a-11e6-8c4b-c97c732acb88.png)

**Comment by Kivutar** [comment]
I also noticed a slowdown in glide64 on wetek play, when I was testing the release 2 or 3 weeks ago. Super Mario used to be full speed and is no more.

**Comment by twinaphex** [comment]
The Rice graphics errors are just Rice being Rice, they will go away eventually once I am further along with my graphics plugin hybridization plans.

As for Glide64, it should not be showing serious graphical errors like that, and it certainly does not on Linux. I guess I will have to debug it more on OSX, unfortunately no GL driver is the same at the implementation level and often enough bugs show up on one implementation but not the other. Nevertheless, I think we can nail some of these issues down. I will let you know more once I start taking a look at it.

**Comment by ddnava** [comment]
Yeah, I know Rice has always been Rice.
Hope it will be fixed soon

**Comment by GPDP2** [comment]
I have the same model of Macbook Pro. I can confirm these problems.

**Comment by twinaphex** [comment]
Test the latest buildbot build (should be uploading in a few hours).

This commit should have fixed the Mario Kart 64 fade in/fade out bugs at least.

https://github.com/libretro/mupen64plus-libretro/commit/ad0664ede1cc9f2aad6bbc472e8738edec2b8878

**Comment by ddnava** [comment]
Tried it. It did fix transitions in Mario Kart 64. I'll try some more games to see if it fixed any other

**Comment by twinaphex** [comment]
@ddnava Got any status update so we can maybe close this?

**Comment by twinaphex** [comment]
I'm closing this for now and assuming the bugs got fixed. If you still experience these problems, you can reopen this issue.
