### ISSUE TITLE
Fix Vulkan issues

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#3005]
Vulkan issues on Android:

- Wrong display viewport sizes in-menu and -ingame. Might be context driver related.

Vulkan issues on Windows:

- V-Sync issues.

**Comment by AlexFolland** [comment]
In Windows, the main Vulkan vsync issue (stuttering/frame drops consistently) was an Nvidia driver bug that is now fixed on their end.

The second Windows Vulkan vsync issue, which is fast-forward not working when vsync is enabled, I am not sure if it's on Nvidia's end or RA's.  It is still outstanding.

**Comment by Awakened0** [comment]
Swap interval and black frame insertion aren't working on the Vulkan driver. Tested on Nvidia 365.10 Win10 driver.

**Comment by Themaister** [comment]
Android should be closer to fully working now in Vulkan with the latest PR.

**Comment by twinaphex** [comment]
I think all of these are fixed now except for orientation changing. Closing this issue at least.

**Comment by AlexFolland** [comment]
I just re-built RA and tested fast-forward in Vulkan in Windows.  It did not unlock the frame rate, still.  Here is the output: http://lex.clansfx.co.uk/dump/6066ae4e0f8c2f1f6026d219ea1e2bc8/00000188.txt

**Comment by Ryunam** [comment]
Yeah, I can confirm that on my Win7 x64 system with nVidia GPU (latest drivers) and the latest nightly Vulkan does not seem to support fast-forward.

**Comment by Brunnis** [comment]
I'd like to add the following regarding Vulkan stuttering issues:

http://libretro.com/forums/showthread.php?t=5428&p=44578&viewfull=1#post44578

There are obvious and very distracting frame drops going on with Vulkan on my setup (Windows 10 x64, see link above for system specs), even in the XMB menu. No such issues seen with OpenGL.

**Comment by Awakened0** [comment]
Nvidia's 372.54 driver includes Vulkan 1.0.13 which fixes the stuttering I was noticing in Symphony of the Night with Vsync on.

**Comment by Brunnis** [comment]
I'll keep an eye out for new AMD drivers and re-run my tests if I see an updated Vulkan runtime.

**Comment by JacobAL** [comment]
Any 2d game has awful stutter for me when using vulkan. Very choppy but works fine in GL.
This is annoying because 3d cores such as mednafen-hw benefit from vulkan.
Per core video drivers could fix this, not sure if that's a thing yet?

**Comment by twinaphex** [comment]
Yeah this choppiness seems to be some Windows-only specific issue, it does not happen on Linux with Wayland context driver.

@JacobAL What GPU do you have?

@Themaister I have gotten immense benefits lately on X11 by using the GLX_OML_sync_control extension. It seems to nearly completely eradicate any potential tearing that could happen, and it's MUCH better at least than the traditional glXSwapBuffers function. There is also a WGL extension available for it but unfortunately nobody supports it on Windows. If there is truly this amount of tearing on Vulkan for Windows as-is right now, would there be any extensions similar to this that we could maybe use for Vulkan Windows?

**Comment by JacobAL** [comment]
Sorry, should have posted my specs:
http://i.imgur.com/zr2CAir.png

GTX970. NVIDIA's memecard biting me in the arse again?

**Comment by Awakened0** [comment]
I'm using a 970 too, but like I mentioned above, if you're on the 372.54 driver or above you should get smooth vsync, just like in GL. I'm on the 376.33 one now. I just tested FF Dawn of Souls with mGBA in fullscreen and the scrolling is still smooth. Using a 1.4.0 nightly.

**Comment by JacobAL** [comment]
I'm on the same driver. On the 1.4.0 from the stables section.

**Comment by Awakened0** [comment]
Stable is smooth for me too. I'm testing with windowed fullscreen disabled, if it makes a difference.

**Comment by JacobAL** [comment]
I only ever play in fullscreen.

**Comment by AlexFolland** [comment]
By "windowed fullscreen disabled", he means the option called "windowed fullscreen" is disabled, which means that RA should be using exclusive fullscreen.

**Comment by JacobAL** [comment]
Thanks, found it now. That didn't have any effect though.
