### ISSUE TITLE
Error entering true fullscreen on custom resolutions

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/RetroArch#3009]
I've tried creating a 3840x480 resolution setup for a CRT monitor on the version from Arch Linux's repos, but I'm getting a "[GLX]: Entering true fullscreen failed. Will attempt windowed mode." error. I've [discussed](http://libretro.com/forums/showthread.php?t=4228&p=39048&viewfull=1#post39048) it a bit in the topical thread, but now I've realized this probably qualifies as a bug.

Here's [the log](https://github.com/libretro/RetroArch/files/267564/log.txt) and [the config file](https://github.com/libretro/RetroArch/files/267566/retroarch.txt).

**Comment by GeneralFailer** [comment]
Quoting my update from the thread.
> Apparently the recent builds produce a detailed error message. Is this supposed to be a driver bug?

>> X Error of failed request: BadValue (integer parameter out of range for operation)
>> Major opcode of failed request: 152 (XFree86-VidModeExtension)
>> Minor opcode of failed request: 10 (XF86VidModeSwitchToMode)
>> Value in failed request: 0x4aa
>> Serial number of failed request: 31
>> Current serial number in output stream: 33

**Comment by GeneralFailer** [comment]
Summoning @hunterk because he hasn't been replying to both the thread and PM for almost a month.

**Comment by hizzlekizzle** [comment]
That looks like an X/driver problem to me.

**Comment by GeneralFailer** [comment]
I've [opened](https://bugs.freedesktop.org/show_bug.cgi?id=96766) an issue report on radeon bugtracker and found out that this doesn't just affect ultrawide resolutions.

**Comment by GeneralFailer** [comment]
It seems to be a RetroArch bug after all.
https://bugs.freedesktop.org/show_bug.cgi?id=96766#c6

**Comment by hizzlekizzle** [comment]
RetroArch shouldn't be trying to set the video mode at all, just using whatever mode you currently have selected. The only time it tries to set a mode is if you enter values into video_fullscreen_x and video_fullscreen_y lines in your retroarch.cfg, and in that case it can only switch to existing modes (that is, it can't create new ones).

**Comment by twinaphex** [comment]
Is this issue fixed or not? If not, why close it?

**Comment by GeneralFailer** [comment]
Yeah, I've mentioned it in the bug report on Freedesktop.
