### ISSUE TITLE
Close Core does not return to the main config

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#3013]
I have some config overrides here, for the game pad overlays, and I noticed that this week update kinda broke it. I load a core, it loads the override, then when I close the core it stuck with the game pad overlay of last core, instead of the retropad overlay I use for the main config.

- Load an overlay, like flat retropad overlay
- Load a content, gba games for example, with an override (gba flat overlay)
- Close the Core, you'll notice that it'll stuck in the gba overlay

Tested only on Android

**Comment by fr500** [comment]
Does it happen with any other setting? or just overlays?

**Comment by fr500** [comment]
Ugh you're right, something broke

**Comment by fr500** [comment]
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
e13bb23ea0b9265404e61e44c1a458eaf47f61c7
43b88cfba99329ba01e94235e8bd60de87c886ef
We cannot bisect more!

**Comment by fr500** [comment]
Sadly there are about 15 commits that don't build so bisecting is really difficult. Dunno what to tell you @sergiobenrocha2, @twinaphex overhauled content handling last week

**Comment by fr500** [comment]
It seems it's loading the dummy core before doing core_deinit (which is wrong I guess)

**Comment by fr500** [comment]
NVM, I think I fixed it, please confirm, tested all the relevant codepaths

**Comment by sergiobenrocha2** [comment]
@fr500 it's working for overlays, but not with shaders.

**Comment by fr500** [comment]
Uh, it's all or nothing. The shader thing you mention is a change in recent retroarch behavior, basically it's now always saving the current shader as retroach.cgp/glsp and it always defaults to that.

So even if there is a problem with it, it's not related to overrides at all.

**Comment by sergiobenrocha2** [comment]
I have this as my override

```
input_overlay = "/data/data/com.retroarch/overlays/gamepads/flat/gba.cfg"
video_shader = "/storage/extSdCard/RetroArch/CONFIG/mGBA/retroarch.glslp"
video_shader_enable = "true"
```

It does not make sense for me to maintain a shader that was called by a override. Even if I close RA and open again, the shader in loaded. Bad behavior/design here

**Comment by fr500** [comment]
it's not the overrides system failing here.
It's retroarch, it's always saving the current shader to retroach.glsp and using that by default

**Comment by sergiobenrocha2** [comment]
Bad design like I said then :/

**Comment by sergiobenrocha2** [comment]
Could we reopen it?

**Comment by fr500** [comment]
No, because overrides is not what's causing, it's the new retroarch behavior regarding shaders, I don't really understand it yet.

**Comment by sergiobenrocha2** [comment]
Should I open another bug report then?

**Comment by fr500** [comment]
yes but I'm not totally clear on the issue, it seems that it always flushes to retroarch.glsp but I'm not sure that's a bad thing...

**Comment by sergiobenrocha2** [comment]
Moving to #3097
