### ISSUE TITLE
Directories and symlinks to them are bizarelly threated as files on XFS partitions

### ISSUE THREAD

**Issue by v-fox** [libretro/RetroArch#3017]
I just heard about RetroArch, [made and published fresh rpm-package for it](https://build.opensuse.org/package/show/home:X0F:branches:Emulators/retroarch) but even after hours of fiddling couldn't make it load anything from my rom collection unless I copy those files on home partition. What's happening is almost indescribable.

I use BTRFS for root, ext4 for /home but keep my roms under /media/storage-w1T-primary/games_consoles (let's call it "the rom folder") where /media/storage-w1T-primary is a XFS partition and games_consoles is a directory which holds subdirectories for roms for various systems. If I open RA with any GUI and try to navigate its rom browser to the rom folder it works fine until /media/storage-w1T-primary where it lists all content, including games_consoles, as files.
If I symlink the rom folder as ~/.config/retroarch/games and try to navigate to it the result is even worse: it refuses to acknowledge the symlink as openable folder too. If I force it to open the symlink by setting it as default directory in the RA's config, it opens it but still ignores its content.
What is the most insane: if I bind-mount the rom directory as ~/.config/retroarch/games (which is transparent redirection which application shouldn't even see unless they explicitly check for it in kernel's mount list) the result is the same.

In fact, it is the same for all XFS partitions while it lists fine (not counting crapping out on names with '#' or any non-latin characters as if it doesn't use UTF) on NTFS and ext4 partitions. How's that even possible ? It shouldn't even know about filesystems.

I thought that maybe I could force it load by launching with filename as argument in console but it silently fails, with '-v' option it says:

```
RetroArch [INFO] :: Config: loading config from: /home/fox/.config/retroarch/retroarch.cfg.
RetroArch [ERROR] :: RetroArch is built for dynamic libretro cores, but libretro_path is not set. Cannot continue.
RetroArch [ERROR] :: Fatal error received in: "init_libretro_sym()"
```

Regardless of "libretro_path" option's existence. It even fails that way on real directory under /home from where I managed to launch one NES rom from GUI in the end.

**Comment by fr500** [comment]
When you load from the CLI you have to specify a core of course
retroarch -v -L mysuperamazingcore.so|dll|dylib romname

**Comment by orbea** [comment]
I suppose this has been fixed, no issues found with the XFS partitions here where both directories, symlinks and roms work as expected.
