### ISSUE TITLE
Windows: Fresh RetroArch has input_joypad_driver = "winxinput" and \autoconfig\xinput\ directory is ignored!

### ISSUE THREAD

**Issue by paalfe** [libretro/RetroArch#3018]
Fresh RetroArch installation (1.3.4 x86_64 and 2016-05-21 x86_64) on Windows 10 has input_joypad_driver = "winxinput" in RetroArch-config and looks for winxinput-autoconfigs in ...\retroarch\autoconfig\winxinput\ directory. If input_joypad_driver = "winxinput" then ...\retroarch\autoconfig\xinput\ directory is ignored!

**Comment by paalfe** [comment]
Manually changing input_joypad_driver to "xinput" solves the problem.

**Comment by fr500** [comment]
fixed 
https://github.com/libretro/libretro-super/commit/d9cdd06b7c34d53b1c35ed27d81ec6897a02262a
