### ISSUE TITLE
1.3.4 Segfault on Debian Jessie / SteamOS due to libEGL.so.1

### ISSUE THREAD

**Issue by ProfessorKaos64** [libretro/RetroArch#3024]
I have no idea why EGL is throwing this. I honestly don't know if it is caused by any changes to Retroarch. If you need system package information, please let me know. Is this really a noob mistake, or is there an obvious issue here? Anything to do with wayland or any of the APIs?

```
    (gdb) r
    Starting program: /usr/bin/retroarch
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7fffea982700 (LWP 5664)]
    [New Thread 0x7fffea181700 (LWP 5665)]
     
    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff45c9b62 in eglBindAPI ()
       from /usr/lib/x86_64-linux-gnu/libEGL.so.1
    (gdb)
```

# Links

* [build log](http://sprunge.us/iRSX)
* [gdb trace](http://slexy.org/view/s20DXNI6le)
* [debian files](https://github.com/ProfessorKaos64/LibreGeek-Packaging/tree/brewmaster/retroarch/retroarch/debian)
* [stack trace](http://sprunge.us/WGKX)
```

**Comment by ProfessorKaos64** [comment]
The question is, why was this installation of nvidia-smi necessary?

**Comment by ProfessorKaos64** [comment]
Seems as if libEGL_nvidia.so.0 isn't provided by a Debian package, or something...

**Comment by ProfessorKaos64** [comment]
Got it, required installation of libegl-nvidia0 on SteamOS. not sure about Jessie.

**Comment by twinaphex** [comment]
@ProfessorKaos64 Was this issue resolved?

**Comment by ProfessorKaos64** [comment]
Yes. I am not sure why libegl-nvidia0 is required now, possibly wayland support using EGL. Whatever the case, I added this as a run-time dependency in my package I distribute. From my end, yes.
