### ISSUE TITLE
Core Input Remapping Enhacements

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3028]
So, a way to improve this would be:
- Swap the fields in the UI, so all RetroPad buttons are on the left and the mappings on the right
- Add an "extra retropad button" that stands for "UNBOUND" 
- Add descriptors for every single input a core may require (101 keys or whatever)

Left side would list the RetroPad buttons (with their autoconf descriptors)
Right side would list the descriptors from the core

SImilar to what I implemented on dosbox:

![screenshot 2016-05-23 23 20 13](https://cloud.githubusercontent.com/assets/1721040/15492137/bd9d68f0-213d-11e6-8e7e-394d2f36d6b1.png)

The current implementation for reference:

![screenshot 2016-05-23 23 39 05](https://cloud.githubusercontent.com/assets/1721040/15492329/ccef1cca-213f-11e6-854c-a692f8401a3a.png)

**Comment by fr500** [comment]
In addition to lying about the pressed button like we do now we would need to lie about what device is being emulated.
https://github.com/libretro/RetroArch/blob/master/libretro-common/include/libretro.h#L280

**Comment by fr500** [comment]
This would require adding a sort of dummy button to the retropad unless you guys have another idea.
Right now the amount of descriptors is limited by the amount of buttons in the retropad.

**Comment by Papermanzero** [comment]
This could be supportive to map different keys/buttons to one retropad button.
A one-to-one button mapping is pretty outdated for a modern emulator. Many games have a better usability if the original buttons e.g. from the snes can be mapped to more buttons on a modern controller (like SNES/Button X can be mapped on 360/Button Y and at the same time on 360/ Button LB)
