### ISSUE TITLE
Add 2 new save state related options

### ISSUE THREAD

**Issue by rz5** [libretro/RetroArch#3029]
EDIT: After talking to a Dolphin dev (phire), it seems like Undo Save State is poorly named. @fr500 has already done done an initial implementation of my request. This issue was edited to reflect all of the above.

In Dolphin, the Wii emulator, there are two save state options currently not available in libretro/RetroArch.

These are the "Undo Save State" and "Undo Load State".
Their behavior should be as follows:

Undo Save State
---------------------
Reverts a slot to how it was before being overwritten.
Relies on a file generically called "content_name.last#". This file is created and changed whenever we save the core's state to a slot which was not empty.
Pseudo code:

```
/* Only possible if the currently selected slot is occupied and there's a backup */
if (content_name.state# exists  && content_name.last# exists) {
    /* Flip the states around so the user can undo this as well */ 
    temp = content_name.last#;
    content_name.last# = content_name.state#
    content_name.state# = temp;
    
    print_in_osd("Reverted save sate slot # back");
} else {
    print_in_osd("Nothing to undo");
}
```

Load Overwritten State
-----------------------
This name could be better.
Loads the state stored in a file generically called "content_name.last#". 

Pseudo code:
```
if (content_name.last# exists) {
    /* This is a load state operation. Save the current state first before loading any other
    such that Undo Load State can undo this operation */
    save_state("content_name.undo");
    load_state(content_name.last#);

    print_in_osd("Loaded slot #'s old state");
} else {
    print_in_osd("There is no backup for slot #");
}
```

Undo Load State
---------------------
Loads the state stored in a file generically called "content_name.undo". This file should be created/ovewritten before any load state operation is done. 

Pseudo code:

```
...
/* Before a load state operation, change the .undo file*/
save_state("content_name.undo");
load_state( WHATEVER );
...

if (content_name.undo exists) {
    load_state(content_name.undo);
    /* We delete the backup so the user cannot undo what was undone */
    delete_file(content_name.undo);

    print_in_osd("Undid load state");
} else {
    print_in_osd("Nothing to undo");
}
```

**Comment by fr500** [comment]
addressed by https://github.com/libretro/RetroArch/pull/3069

**Comment by twinaphex** [comment]
We added this now.
