### ISSUE TITLE
Vulkan issue on Android - Nexus 5X

### ISSUE THREAD

**Issue by zxcvbad** [libretro/RetroArch#3030]
Wrong display view sizes, in-menu and in-game. 
Could be driver related?

1. Noticed gui layout quite broken after setting Vulkan backend (fceumm) though it remains scrollable

2. in-game visually - same behavior: left upper corner portrait/stretched in landscape

in-menu portrait: http://i.imgur.com/GqH45RZ.png
in-menu landscape: http://i.imgur.com/Lq3sWFEh.jpg
in-game portrait: http://i.imgur.com/4HeniRh.png
In-game landscape: http://i.imgur.com/lWGBFS0h.jpg

Other issues: 

minimizing > loading app from background to gui = white screen unresponsive
to the game = black screen unresponsive + sound

**Comment by parkerlreed** [comment]
Question: How are you trying Vulkan on the 5X? I have one on the latest 6.0.1 rooted. First I've heard of Vulkan on it.

**Comment by zxcvbad** [comment]
@parkerlreed N developer preview 3

**Comment by parkerlreed** [comment]
Thanks

**Comment by Themaister** [comment]
I think this is an issue with the WSI implementation on Android somehow. It works fine on Linux (which is what I can test myself atm).

**Comment by twinaphex** [comment]
These issues should be fixed now. The only remaining issues should be changing orientation.
