### ISSUE TITLE
Achievement support got broken

### ISSUE THREAD

**Issue by ReasonanC** [libretro/RetroArch#3032]
Somewhere along the way cheevos stopped working - it looks as if the retroachievement server is not getting any information about game played or achievements unlocked - it used to recognize the game [even stuff like PC Engine games] and add them to recently played - now there is no change whatsoever.

Retroarch behaves as if everything works correctly, displays unlock messages etc - yet it simply isn't broadcasted to the server (or accepted by it)

Tested on latest nightly and 1.3.4 stable, on windows 10x64 on NES Castlevania, log excerpt
[cheevo.txt](https://github.com/libretro/RetroArch/files/283134/cheevo.txt)

It gets info from the profile correctly [achievements unlocked] so it doesn't seem to be authentication related

**Comment by leiradel** [comment]
@ReasonanC Could you attach the complete log here please? Thanks!

**Comment by ReasonanC** [comment]
@leiradel Here you go
[log.txt](https://github.com/libretro/RetroArch/files/283819/log.txt)
That one is far longer, I tried stuff with few games and cores

Oh, and BTW as I've seen that you've tried to make cheevos work in gambatte, vba-m and mGBA - well, there seems to be no change - games get detected but it never awards any achievements at right moment - sometimes it gives some unrelated achievements on first boot - see Wario Ware Inc. - something is not right with memory comparison I'd guess

As a second aside, there's some problem with detection of some SNES games [Sim City, Yoshi's Island, both Lost Vikings games etc.] Attached is a second log with Wario Ware and some of those problematic SNES games, ignore audio errors, I forgot I had foobar2000 running in WASAPI mode at the same time.
[log2.txt](https://github.com/libretro/RetroArch/files/283838/log2.txt)

**Comment by leiradel** [comment]
@ReasonanC Yes, the cheevos module was having trouble sending awards and statuses to the server. All is good now, thanks for the report.

Could you make sure it works for you before we close this issue?

**Comment by robertybob** [comment]
@leiradel Sorry to hijack this issue, but out of the 11 systems supported by retroachievements, are there any that Libretro does not yet support?

**Comment by leiradel** [comment]
Of the 11 systems, four don't have any games with achievements: N64, SCD, S32X, and MS

All others are supported by at least one libretro core: MD, SNES, GB, GBC, GBA, NES, and PCE

**Comment by ReasonanC** [comment]
Okay it works at least as well as it used to when it comes to NES, SNES and Picodrive
Also GBA now works [very well from what I've seen]
PCE [Mednafen Fast - tested on R-Type] and Gambatte recognize roms but they don't award anything

And those weird issues with SNES recognition persist [Sim City, Yoshi's Island, Lost Vikings]

Thanks for great work

**Comment by leiradel** [comment]
@ReasonanC There a pull request for the PCE core that adds achievement support, it'll be updated soon.

Gambatte should work just fine, I've just tested it with The Legend of Zelda - Link's Awakening DX and Gargoyle's Quest - Ghosts'n Goblins and could get achievements in them.

**Comment by ReasonanC** [comment]
@leiradel 
Yep, it worked on a different game, maybe I've got a wrong revision of Super Mario Land or something like that.

**Comment by ahstro** [comment]
I have this exact problem. How was this fixed before? There hasn't been any releases since this issue; do I need to build RetroArch from source to get the fix?
