### ISSUE TITLE
Option to switch A and B; X and Y on Retropad

### ISSUE THREAD

**Issue by ReasonanC** [libretro/RetroArch#3035]
I really like the idea of Retropad and it works really well... except for someone like me who is way too used to Xbox style of button placement - so I constantly hit back instead of accept in anything with that traditional Nintendo layout

In my experience binding Retropad A to X-box One B leads to some irritating confusion during attempts to remap controls for a core ["I want to bind something to A so it's Retropad B" - not helped by the way it usually lists A and B before other face buttons in the remap menu - which gets really confusing on pc engine -  so I currently bound my Retropad so that Retropad buttons match my actual button labels - and need to remap all the cores at first run [which is fine]

I'd love a toggle in general input configuration switching between Western and Japanese face button layouts [or maybe even - "Reverse Face Button Layout" - which would be a great boon for everyone pathologically used to that layout - there is a reason why Sony keeps on inverting X and Circle while bringing games over.

It could also be yet another step in simplifying the setup for many people

**Comment by fr500** [comment]
There is no point at all.
The Xbox 360 controller in particular has an autoconf profile (you don't need to map it) and that profile has descriptors (so it shows the actual controller labels on the GUI).

In the input remapping screen we use those labels too when available.
If it is a PS3/4 pad with a Xinput emulator you can could the descriptors in the autoconf file so it reads cross, triangle, square, etc.

You can do so with any pad.

![screenshot 2016-05-26 09 23 55](https://cloud.githubusercontent.com/assets/1721040/15577803/a019112a-2323-11e6-993f-0922b56c16d0.png)

The only part of this I agree with is an A/B switch toggle on the GUI

**Comment by ReasonanC** [comment]
Tested it on fresh installation - never realized how to load an autoconfig file actually - maybe there should be load config option in the input menu, like with shaders - it looks like I need to manually import it into my main config as loading just the autoconfig profile overrode everything

I was actually talking only about switching  A and B, and X and Y - if labels can get correct via autoconfig descriptors then the rest is okay

Eh, can't really get autoconfig to working - can't load it without destroying my configuration

**Comment by fr500** [comment]
You don't have to load an autoconfig.
It's auto for a reason.

What platform?

**Comment by ReasonanC** [comment]
Windows 10 x64, Xbox One Controller - it autoconfs as Xinput Controller

**Comment by fr500** [comment]
RetroArch version?

**Comment by ReasonanC** [comment]
latest nightly

**Comment by fr500** [comment]
Ok, the issue is probably with your pad, none of use have an XBONE pad, (mine is on the mail) so it's used the builtin profile (hardcoded, no descriptors).

You can just autoconfigure your pad, save a profile and copy/paste the descriptors to the file it generates.
This is how it looks OOTB with a XBOX 360 controller

![screenshot 2016-05-26 10 29 04](https://cloud.githubusercontent.com/assets/1721040/15580058/d35689f6-232c-11e6-91ca-57395b2c4cf6.png)

The system is quite flexible, and you can even map hotkeys with autoconfg (manually, not from the gui) Here is my custom profile with hotkeys;

http://hastebin.com/fuhamuxecu.md

I'll add a XBONE profile with descriptors when my pad arrives.

**Comment by ddelella** [comment]
This is still an issue with version 1.6.7 and I think it should be addressed or a new profile added in addition to RetroPad which says Xbox or PlayStation and the proper mapping.  The only saving grace in the current version is that it says "User 1 B button (down)" where the direction is key to mapping.  It is not a must have but would be a nice touch to align these with what the user sees on modern controllers.

**Comment by fr500** [comment]
Once the pad is mapped and there are descriptors you don't get B A X Y, you get Triangle Circle, Cross, Square.

I don't really see the problem...
