### ISSUE TITLE
[Android] NVIDIA Shield menu button is mapped wrong

### ISSUE THREAD

**Issue by Steveice10** [libretro/RetroArch#3039]
Using my NVIDIA Shield Portable, even though the option for the back button to function as the menu button is enabled, it doesn't work, and for some reason, pressing the volume button opens the menu instead.

**Comment by fr500** [comment]
The back as menu button only works when back is not mapped to anything.  On
the shield it's mapped as select.

The volume button is mapped as menu intentionally since it's the only extra
button we have. Not really issues as you can see and if you any like the
map you can change it.
