### ISSUE TITLE
RetroArch Compiled in iOS 7 - icade 

### ISSUE THREAD

**Issue by thededman** [libretro/RetroArch#304]
edit - this is was resolved many version ago. 

I have downloaded the latest build this evening, and compiled in Xcode with iOS 7. I updated my ipad to iOS 7 GM and downloaded the newest Xcode and iTunes 11.1 beta. 
So this version will compile in Xcode 4.6 and works on iOS 7 - no icade support in non-jailbroken.
Tried again in Xcode 5 with new SDK, and no icade support in non-jailbroken ipad or iphone. @meancoot is this something with in the new iOS?

**Comment by HashieTwoShoes** [comment]
How do you add roms?
