### ISSUE TITLE
"Failed to initialize netplay"

### ISSUE THREAD

**Issue by Substance12** [libretro/RetroArch#3040]
I'm using Arch Linux, trying with the retroarch package, with the snes9x core. I've forwarded the ports correctly but netplay just doesn't want to work.

From the console output, I get "Failed to set up netplay sockets" and then "Failed to initialize netplay". I haven't found any solution.

**Comment by fr500** [comment]
Most likely a network issue, I tried android vs windows netplay on my LAN and it's working fine
