### ISSUE TITLE
Option to use PS/Xbox button scheme with retropads on menu

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#3041]
RetroArch uses the Nintendo-style button configuration on its menu, in which the A button is to the right, the B button is at the bottom, etc. This is counter-intuitive when using a xinput or dualshock based controller. I know I can setup per-core configurations and then change retroarch.cfg, but a UI option to change the behavior on the menu while maintaining default retropad mappings would be helpful.

**Comment by fr500** [comment]
You can change the cfg, there is menu_ok and menu_cancel just invert the values

**Comment by ReasonanC** [comment]
@fr500 BTW what do numbers behind those menu_<function> refer to? It doesn't seem to be joypad key codes or anything like that - I'm trying to map L2 and R2 for scrolling up and down - according to pad config file it's +4 and +5

Also, menu_navigation_wraparound_enable = "true" doesn't work, might 'cause crashes while trying to scroll through vertically out of bounds menu

**Comment by fr500** [comment]
I don't get the aforementioned crashes. And we have debated the control scheme to death.
For now invert menu-ok and menu-cancel
