### ISSUE TITLE
[ Windows - Nightly 28-May-2016 ] Focus is lost sometimes

### ISSUE THREAD

**Issue by julianxhokaxhiu** [libretro/RetroArch#3045]
Hi,

I'm currently using RetroArch on Windows 10 in Fullscreen Mode. Sometimes when I close a session of gaming, through the normal RetroArch menu ( `center button of my pad -> Close` ) I get the Windows Taskbar on top of RetroArch fullscreen Window. How is it possible? Isn't RetroArch taking exclusive output of the monitor like Games are doing?

Any possible fix or mis-configuration that I may have?

Thanks in advance,
Julian

**Comment by fr500** [comment]
Reopen if this is still an issue, can't repro here.
