### ISSUE TITLE
Are there any efforts to implement PPAPI?

### ISSUE THREAD

**Issue by LukasBombach** [libretro/RetroArch#3047]
Hey, are there any efforts to interface RetroArch with [Google's Native Client](https://developer.chrome.com/native-client) / PPAPI. This would allow to bring high performance to the web and applications built with Electron or nw.js. To me this would be awesome because web technology makes it so easy to build nice, cross platform user interfaces.

**Comment by fr500** [comment]
Nope

**Comment by LukasBombach** [comment]
i see 👍

**Comment by hizzlekizzle** [comment]
Going to close this as a wontfix, since:

> In January 2020, Google announced that support for PPAPI would be removed from Google Chrome and Chromium in June 2021
