### ISSUE TITLE
Problem in the setup menu and zelda game majora's mask

### ISSUE THREAD

**Issue by AndersonFirmino** [libretro/RetroArch#3051]
Hello world developers.
First I would like to congratulate them for the emulator.

And also report some bugs in my experience with him.

In my computer I use Linux Mint in its latest version.
And the Retro-arch emulator in the last version 1.3.4

The bug I'm finding is as follows.

I set in the emulator, the directories where are the roms
I changed the wallpaper and set up the controls

I use USB control, USB Twin controller (PS2 gamepad).

And when I open the Zelda, in the middle of the game when I open the menu I can not access the menu items. The game simply skips the items and go to the next menu screen.

I return the settings to see if I can configure the controls, but the emulator crashes and there have to close and restart it.

And the problem persisted, unless I delete the file retroarch.cfg making me have to reconfigure everything again;
I can set it only once, then the problem returns.

thanks for any help. :)

**Comment by sergiobenrocha2** [comment]
Try download the joypad autoconfig files first, maybe your joypad config is already there, Online Updater --> Update Autoconfig Profiles.

I didn't understand very well the other problem, what menu are you talking about? The Quick Menu (where you find Resume, Restart, Save State...)?

**Comment by AndersonFirmino** [comment]
Menu bugs are:
The main menu has a settings option. Depending on where I set up or put any value when I try to exit the menu it gets stuck it.
Having to leave and re-enter the retro arch to return to work, and there the controls options start to freeze the emulator.

And the problem of control in Nintendo64 only happens with Majora's Mask I did several tests.

Another problem I found is that in a PS2 control when I put it to the control to vibrate (rumble pak mode)
it vibrates in the first seconds of the game but then stops working.

The solution to play Majora's Mask I found was to use the m64py.

I'll take a look at the suggestion that you passed. Thank you so much. :)

**Comment by sergiobenrocha2** [comment]
I still don't understand. Do you speak Portuguese by any chance?

**Comment by AndersonFirmino** [comment]
Yes, and my English is not very helpful. lol

**Comment by fr500** [comment]
Can't really understand this and it seems abandoned.
The Majora issue should go into the mupen bug tracker.
