### ISSUE TITLE
Horitzontal scrolling graphics tearing, jerkiness with MAME when using rotated screen (MAME 0.174)

### ISSUE THREAD

**Issue by neosquid** [libretro/RetroArch#3059]
Playing the game "Starforce" - which is a scrolling vertical shoot em up; it also has the feature of being able to scroll the playfield horizontally. 

The game is smooth while scrolling upwards, but very jerky when you move the ship from left to right. 

This only happens when I have rotated my monitor, then set the rotation option in Retroarch to correctly display the game on the monitor.

Seems to be present in both the Mac OS X retroarch, and Windows. 

Turning off Vsync has no effect.

**Comment by twinaphex** [comment]
Did you try with the Vulkan video driver? Have you also tried enabling GPU Hard Sync with OpenGL?

With OpenGL, the vendor of your GPU controls the swap chain, and usually the drivers dictate the buffer swap method. With Vulkan, we can control this on an application level, leading to much better results for RetroArch.

**Comment by neosquid** [comment]
Tried all suggested - no success.

Out of interest, Varth (Capcom) has similar problems, vertical scrolling is jerky too.

Openemu seems much smoother rotated 270 degrees in portrait view, for both games. 

Retroarch runs similar games like Raiden very smoothly.

**Comment by orbea** [comment]
@neosquid Is this still an issue with the nightlies?

**Comment by hizzlekizzle** [comment]
My guess is that this was related to nearest neighbor with noninteger scaling, but since we haven't heard anything about it in 4 yrs, i'm going to close it.
