### ISSUE TITLE
Pressing hotkey enable button causes button B to stop being pressed.

### ISSUE THREAD

**Issue by matalog** [libretro/RetroArch#3064]
Pressing the hotkey enable button in retroarch on retropie and i believe on a raspberry pi in general, causes button B to be released even though it is being held down the whole time.

This is not how it acts on retroarch on a PC.

I noticed this holding a shell and rewinding in SMB 3 on NES but i checked and it's the same in SMW on SNES. If you rewind holding a shell on retropie, you will let go of the shell whether or not you are holding B down when you are finished rewinding. If you hold B while rewinding on a PC, in retroarch (at least using fceumm) you will hold onto the shell when you are finished rewinding.

This suggests that the rewinder releases B upon finishing rewinding, maybe only for a small length of time, but long enough to register and make you drop the shell.

This can be a problem when experimenting in these type of games - obviously the original creators of the rewind feature took care that is wasn't like that on PC.

I have since noticed that pressing the hotkey enable button as Fire Mario with B held down, he will shoot a fireball - this suggests that B is actually released then pressed again, even though it is being pressed the whole time.

It has been discussed here https://github.com/RetroPie/RetroPie-Setup/issues/1499#issuecomment-223406783

**Comment by fr500** [comment]
This is by design actually, hotkey enable disables all inputs, it happens everywhere.

**Comment by matalog** [comment]
One less problem then :-)
