### ISSUE TITLE
Save Directory Is Ignored When Launching Game From Command Line

### ISSUE THREAD

**Issue by jloutsenhizer** [libretro/RetroArch#3072]
To start this is using the version of RetroArch from: https://launchpad.net/~libretro/+archive/ubuntu/testing for Ubuntu 14.04
```
$ retroarch --version
RetroArch: Frontend for libretro -- v1.3.4Compiler: GCC (4.8.4) 64-bitBuilt: Jun  4 2016
```

launching with the following command to run a mednafen game directly ignores savefile_directory configuration:
```
$ "/usr/bin/retroarch" --fullscreen --libretro=/usr/lib/libretro/mednafen_psx_libretro.so "/home/justin/ROMs/PS1/Crash Team Racing.cue"
```
Output: http://pastebin.com/NJZdeffv
In particular:
```
RetroArch [INFO] :: Config: loading config from: /home/justin/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Loading dynamic libretro core from: "/usr/lib/x86_64-linux-gnu/libretro/mednafen_psx_libretro.so"
RetroArch [INFO] :: Overrides: core-specific overrides found at /home/justin/.config/retroarch/Mednafen PSX/Mednafen PSX.cfg
RetroArch [INFO] :: Overrides: game-specific overrides found at /home/justin/.config/retroarch/Mednafen PSX/Crash Team Racing.cfg
...
RetroArch [INFO] :: Environ SAVE_DIRECTORY: "/home/justin/ROMs/PS1/".
...
```
SAVE_DIRECTORY should be: `/home/justin/.gdrive/Game Saves/PS1`

The save directory is being ignored, here's the three configs loaded:
retorarch.cfg: http://pastebin.com/YCss9TiZ
Medafen PSX.cfg:
```
system_directory = "~/.retroarch/psx/system"
savefile_directory = "/home/justin/.gdrive/Game Saves/PS1"
```
Crash Team Racing.cfg:
```
input_libretro_device_p1 = "517"
input_player1_analog_dpad_mode = "0"
```

I have tried setting the save directory in all of the configs as well as using the commandline flag `--save="/home/justin/.gdrive/Game Saves/PS1"` but all yield the same results.

Launching RertroArch and then loading the game correctly overrides the SAVE_DIRECTORY

**Comment by fr500** [comment]
I just tried on windows and it seems to be working fine:
http://hastebin.com/funeyiwipe.tex

Check lines 9, 68, 69 and 72

**Comment by fr500** [comment]
Ok, I've reproduced it now without savefile sorting...
Interesting...

I had fixed all of these usecases like a year ago, I think a possible culprit would be this https://github.com/libretro/RetroArch/pull/3025/commits/07b3a081c04bdf56210eabe0a9dee8ba55e82e47

**Comment by jloutsenhizer** [comment]
Thanks for looking into this. It looks like enabling save sorting causes the SAVE_DIRECTORY to be set as expected on my system as well.

I was able to reproduce the issue on a build from the [stable ppa](https://launchpad.net/~libretro/+archive/ubuntu/stable/+index?batch=75&memo=150&start=150) which was built on May 5th so I believe the issue was introduced before then.

**Comment by fr500** [comment]
Yeah it's not that commit

**Comment by fr500** [comment]
sent a PR https://github.com/libretro/RetroArch/pull/3075
