### ISSUE TITLE
Post-Processing Documentation.

### ISSUE THREAD

**Issue by ADormant** [libretro/RetroArch#3074]
Could you update the documentation of shader specification, in a a similar vein to https://github.com/Tinob/Ishiiruka/wiki/Post-Processing-Shaders 
I know there is this https://github.com/libretro/RetroArch/wiki/Cg-shaders but it seems  very outdated.

**Comment by RobLoach** [comment]
Mind creating an issue over at https://github.com/libretro/docs ? That's where the docs live.
