### ISSUE TITLE
input_device_p1 Config File Option Doesn't Work (Windows)

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#308]
I have a separate cfg file for analog games for PSX and tried turning on config_save_on_exit so I could save my Device Type in RGUI to Joystick w/ Analog, but it always changes input_device_p1 to 0. I assume 1 would be the analog option. Editing the cfg manually to 1 doesn't work either.

**Comment by meleu** [comment]
Hey guys, sorry for bumping such an old issue... But I have a doubt about the diferences between `input_libretro_device_pN` and ` input_device_pN`.
The @Themaister answer makes me think that both options are the same but the `input_device_pN` is a deprecated one. Am I right?
