### ISSUE TITLE
Input binding broken in non-English languages

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#3082]
Input binding doesn't seem to work in any language except for English. To reproduce, change the language to anything non-English and then go to settings > input and try to bind some controls.

Forum thread for more info:
http://libretro.com/forums/showthread.php?t=5978

**Comment by twinaphex** [comment]
I think I fixed this now with this commit -

https://github.com/libretro/RetroArch/commit/b43620088738c58d8615d4f8d7c8243f56cc3fa5

**Comment by gouchi** [comment]
Yes now you can bind when the ui is not in english.
