### ISSUE TITLE
Two-player arcade controller kit's joysticks not reporting as separate sticks

### ISSUE THREAD

**Issue by kevinfishburne** [libretro/RetroArch#3084]
I originally submitted this as a Lakka bug, but it was requested that I resubmit it here.

https://github.com/libretro/Lakka/issues/395

I'm using Lakka in my arcade cabinet, which uses a 16-button, two-joystick kit and USB controller. Previously it worked fine on the same hardware in MAME under Mint 17. In Lakka everything works fine except the joysticks report as the same two axes when mapping the directions for player one and player two. So moving player one moves player two, and vice-versa. I tried clearing the digital stick mappings, mapping the sticks as analog, enabling the option to convert analog to digital, and using the left joystick as the left analog and right joystick as the right analog but it exhibits the same behavior. Retroarch treats the two joysticks as the same joystick no matter what I do.

The USB controller board for the button/joystick kit reports in Retroarch as "THT Arcade console 2P USB Player (#0)".

**Comment by mikebutash** [comment]
I found this last night working with retroarch as well on ubuntu 16.04.  I had my logitech f310 joypad connected, as well as my saitek hotas controller, and it only wanted to work with the saitek.  I had to disconnect the saitek and logitech, and connect back the logitech, then it detected it for setup.

It doesn't seem to enumerate them individually, but those are the only two I have at the moment to test with.

**Comment by mikebutash** [comment]
This might be a methodology issue, I had issues with Descent Underground that the UE4 engine had issues figuring which controllers were which, something about needing a newer method of enumerating the devices at the dev level with xinput via sdl in linux.  Sadly a year later they still haven't figured it out, but they just blame UE instead of working around it.

**Comment by linjoe2** [comment]
having the exact same problem, hope it gets solved quickly!

**Comment by dunderdotten** [comment]
Same here (i think) Running Windows 7 and 10 and have a 2 player fight stick that only shows as one. Tried clearing all binding and start from scratch but it did not work. One stick controls both players :)

**Comment by danpowpow** [comment]
I have this exact same problem. Weirdly,  i have found a workaround.  I have an xbox 360 for windows reciever, and when a pad is active, and is the prime controller in retroarch,  the twin usb problem vanishes and both sets of controls are assignable. If the xbox pad tines out, it all goes wrong and stick one plays as player two, stick two goes unrecognised, and I have to quickly slam the button on the xbox pad!
Very strange.

**Comment by kevinfishburne** [comment]
At some point someone posted a workaround where a "quirks" file/flag was edited, but I think it was in the other bug report (https://github.com/libretro/Lakka/issues/395) which now 404's. I have my cab set up again and would like to test to see if the workaround works. Does anyone remember what it was?

**Comment by mosky17** [comment]
same problem here. Any update or workaround?

**Comment by kevinfishburne** [comment]
Here's the workaround, which worked for me. Depending on your distro, you'll either need to edit extlinux.conf or cmdline.txt on the boot partition (may be in /flash). You'll see a line something like this:

boot=/dev/mmcblk0p1 disk=/dev/mmcblk0p2 quiet  vt.global_cursor_default=0 loglevel=2

append the following to the line and save the file: usbhid.quirks=0x16c0:0x05e1:0x040

Here's the weird part. It still won't work until you do this in RetroArch:

Go to Settings -> Input -> Input User 1 Binds and choose "User 1 Bind All", setting all your buttons for player 1 (need to be fast as it has a timer). Then do the same thing for user 2 and you should be good to go.

**Comment by mosky17** [comment]
Thanks kevinfishburne but I'm afraid it's still not working, sticks are recognized as one.

this is my /flash/extlinux.conf:

`# cat extlinux.conf
DEFAULT linux
PROMPT 0

LABEL linux
 KERNEL /KERNEL
 APPEND boot=LABEL=System disk=LABEL=Storage  quiet vt.global_cursor_default=0 loglevel=2 usbhid.quirks=0x16c0:0x05e1:0x040`

rebooted and binded again both users but still the same. Any further suggestions?

PD: The /flash might be in read-only state, if so just remount by doing:
`mount -o remount,rw /flash`

**Comment by kevinfishburne** [comment]
I'm using Lakka 2.0 on a RPi which uses cmdline.txt, though previous versions of Lakka used extlinux.conf. Other than that my only thought is that the device ID may be slightly different for your controller. Try the lsusb command to see if the numbers match those in the appended line (0x16c0:0x05e1:0x040). And if anyone else has any ideas, please chime in.

**Comment by mosky17** [comment]
this is the output of lsusb:

`Bus 003 Device 002: ID 0810:e001 Personal Communication Systems, Inc.`

do you think the line should be:
APPEND boot=LABEL=System disk=LABEL=Storage  quiet vt.global_cursor_default=0 loglevel=2 usbhid.quirks=**0x0810:0xe001:0x81**

I'm not sure about that last section (0x81), this is the full detailad output:

```
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.00
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0         8
  idVendor           0x0810 Personal Communication Systems, Inc.
  idProduct          0xe001
  bcdDevice            1.06
  iManufacturer           0
  iProduct                2 Twin USB Gamepad
  iSerial                 0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           34
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode           33 US
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     178
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval              10
```

**Comment by mosky17** [comment]
Ok, got it working. In my case I'm using a Twin USB Gamepad with the following Ids:

idVendor           0x0810 Personal Communication Systems, Inc.
  idProduct          0xe001

So I had to add **usbhid.quirks=0x810:0xe001:0x040** instead.

One important thing is that it's important to unplug and plug the gamepad USB after reboot.

**Comment by gouchi** [comment]
So we can closed this issue as it is related to usb quirks ?

Thank you.

**Comment by mosky17** [comment]
Fine by me @gouchi

**Comment by denser** [comment]
usbhid.quirks=0x2563:0x0555:0x040

This is my device. Have to dig deep to find out why my controllers stop work as two after i update lakka from 2.2 to 3.6.

What happen if i have to add this now?

**Comment by denser** [comment]
lakka 2.2 see both controllers.
But 3.6 see only one and act really weird.. Pad is copy but A, B, X and Y wont work as well as select and start and other...
