### ISSUE TITLE
Have to press "input_menu_toggle" twice for the menu to toggle the first time

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#3085]
After launching a game, the first time I want to show the menu I have to press the `input_menu_toggle` key/button twice for it to work. Once opened a first time, I can toggle it by pressing once like intended until I open another game.

I'm on a Rpi3, it does this regardless of the controller/key and menu used. I've got a build from one or two days ago, so it's quite fresh.

**Comment by Kivutar** [comment]
I also noticed this. But i'm unable to reproduce with the latest master on linux and a keyboard.

**Comment by natinusala** [comment]
Do you want me to dive into the code to see where it could come from ? I would need a quick overview of the input processing stack (what calls what and when) not to be lost

**Comment by Kivutar** [comment]
I just tried with a gamepad, and the bug isn't there on the latest master. I think it is worth trying.

**Comment by natinusala** [comment]
It looks like "RARCH_MENU_CTL_TOGGLE" is fired twice. I don't know why yet, I'll search.

**Comment by sergiobenrocha2** [comment]
I think it's fixed now.

**Comment by fr500** [comment]
reopen if this re-surfaces
