### ISSUE TITLE
RetroArch Bus Error when attempting to stream Super Mario World via built-in ffmpeg

### ISSUE THREAD

**Issue by RalphORama** [libretro/RetroArch#3088]
I'm on a Raspberry Pi 3 Model B running Raspbian, all packages are up-to-date.

Basically, I'm attemping to stream via rtmp over the local network using a custom build of RetroArch with ffmpeg included. My stream settings are the same as those outlined in the [streaming guide](https://github.com/libretro/RetroArch/wiki/FFmpeg-recording-and-live-streaming) (namely under the "Live streaming" header). 

I got the stream to work once (watched it on my phone via VLC), but since then it always throws a "Bus error" when I attempt to start the game up in streaming mode. I'll run some more tests, but I hope someone here will be able to help.

Here is the full log file: [rarch-log.txt](https://github.com/libretro/RetroArch/files/303453/rarch-log.txt). This is the output of `retroarch --record rtmp://10.1.10.19/live/test --recordconfig ~/.config/retroarch/config/live.cfg --verbose > rarch-log.txt 2>&1`

**Comment by RobLoach** [comment]
There has been many additions to the recording system since 2016. Mind testing and re-open if this is still an issue?

I've been able to stream with both rtmp and twitch.
