### ISSUE TITLE
Can't enable "Sort saves in folders" from GUI

### ISSUE THREAD

**Issue by KreativeKrise** [libretro/RetroArch#3093]
Everytime I change `Sort saves in folders` in `Savings` to `On`, go one menu level and back into `Savings` it's `Off` again. I have the same behaviour with e.g. `Loggin Verbosity`.
Tested with Windows 64bit stable 1.3.4 and latest nightly build.

**Comment by fr500** [comment]
It saves correctly here.
Are you using configurations per-core or something.
I'm on the latest trunk and can't reproduce

**Comment by KreativeKrise** [comment]
Seems to be fixed! :+1:
