### ISSUE TITLE
Can't download thumbnails (download resets to 0%)

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#3096]
On my Rpi3, I can't succeed to download the thumbnails using the online updater. The download always resets to 0% at a given percentage (for SNES it's 13%, for N64 it's ~10%), ans starts over to reset again in an infinite loop.

I'm using a build made from the latest sources as of the date of this issue.

**Comment by twinaphex** [comment]
You are possibly running out of memory, these thumbnail packs can become very big and I doubt it fits into RAM.

The current implementation has some big limitations, we might be moving to a more scraping-like implementation later on but that is still dependent on a server becoming available which we are also working on.

**Comment by natinusala** [comment]
Okay, I see. Should I download them manually on my PC and extract them to the thumbnails folder ? What is the directory structure ?

**Comment by Kivutar** [comment]
I get the same bug. Or something similar. The counter get reset, but the download continues, and finally I get the boxarts. For example, it will reset around 20% five times, and then extract.

**Comment by natinusala** [comment]
Okay, I'll try it then and tell you
