### ISSUE TITLE
Option to disable triple buffering for intel KMS driver

### ISSUE THREAD

**Issue by larskj** [libretro/RetroArch#3100]
The motivation here being to decrease input latency from controller input to screen update.

Would it be possible to introduce a triple buffering setting on/off, so when set to Off, we get a regular buffer swap at vsync instead of triple buffering?

For those who (like me) value low input lag and don't need the potential cpu performance increase offered by triple buffering.

We have settings like "Frame Delay" which can decrease input latency by basically making the cpu wait ("idle") until the last possible moment before rendering the next frame and be done just in time for vsync. Unless I have misunderstood something, isn't triple buffering going against this strategy of how to utilize the Frame Delay setting? We don't need an additional buffer in the case we are anyway forcing the cpu to be idle most of the time when using the frame delay setting.

Ideally you would just let the cpu be idle until just before vsync, then render frame just in time and swap it at vsync - we don't want triple buffering in this case?

The background for suggesting this is measurements with high speed camera showing a consistent 1 frame of extra delay when running RetroArch in KMS compared to Win10. Is it plausible this is caused by the triple buffering of the intel KMS driver in RetroArch, which we currently have no setting to disable?

Any critique of the above is welcome, perhaps I have misunderstood something.

Thanks,

Lars

**Comment by Kivutar** [comment]
@twinaphex or @Themaister could reply

**Comment by aliaspider** [comment]
I don't think that triple buffering is used in the first place.
also frame delay is just what it says, it displays the frame later and not earlier. it doesn't decrease latency but increases it, which can be helpful to sync the display latency to the audio latency.

**Comment by Themaister** [comment]
I think I see what you mean.
This would essentially mean waiting for page-flip after queueing it up.
Try to skip the check to gbm_surface_has_free_buffers and see if it helps.

```   waiting_for_flip = gfx_ctx_drm_queue_flip();

   if (gbm_surface_has_free_buffers(g_gbm_surface))
      return;

   /* We have to wait for this flip to finish. 
    * This shouldn't happen as we have triple buffered page-flips. */
   RARCH_WARN("[KMS]: Triple buffering is not working correctly ...\n");
   gfx_ctx_drm_wait_flip(true); 
```

**Comment by larskj** [comment]
Thanks for the input - can you please elaborate a bit more of what you suggest and then I will try it.

Do you mean to just remove the if-statement and always return, or delete both the if-statement and the return statement so we always enter the lower part of the code?

Any elaboration you can provide of the current page-flipping source code handling would be very much appreciated.

Thanks.

**Comment by Themaister** [comment]
Delete the if and the return, so you always hit the drm_wait_flip(true) path.

**Comment by larskj** [comment]
Well, that was pretty awesome and shaved half a frame of delay off on average.

I'm now down to 3.5 to 4 frames of delay in Nestopia and it is very consistent.

Is this something you are open for making a setting for and implementing upstream?

**Comment by Themaister** [comment]
I'll probably implement a setting at some point for Vulkan swapchain image count where this toggle would be trivial to hook up, but if you want it done fast, a PR is faster.

**Comment by larskj** [comment]
Would it be an acceptable solution for now to use the HAS_LAKKA define to disable those two lines of code? Or would you prefer a new setting? (Which would then only be applicable for KMS)

**Comment by Themaister** [comment]
Ifdef would not be acceptable, no. Needs a new setting for number of swapchain images. Minimum 1, Maximum 4, default, 3. If <= 2, the "fix" here can be applied.

**Comment by larskj** [comment]
Ok thanks again for the input.

**Comment by twinaphex** [comment]
I can create such a new setting.

**Comment by larskj** [comment]
That would be greatly appreciated, thanks.

**Comment by Kivutar** [comment]
And if you can't, we can still have a patch that would be applied at build time in Lakka. (But this kind of patch have a maintainance cost, and I prefer to avoid it)

**Comment by twinaphex** [comment]
OK, implemented this and pushed a commit.

https://github.com/libretro/RetroArch/commit/8a8fadc5b2e615fec0961d2e62e21cc731d653d1

Implemented it first for DRM/KMS, I'll leave it up to maister to implement this for the Vulkan context driver.

@larskj @Themaister Let me know if this works as expected.

**Comment by larskj** [comment]
Ok I will try it.

**Comment by larskj** [comment]
It worked perfectly.

If I set the swapchain images to 3, then I get the normal triple buffering behaviour.
Setting it to below 3 removed half a frame which is the same as what I saw.

Image still looks sharp with no tearing.

Thanks.

**Comment by parkerlreed** [comment]
Is this the "Vsync Swap interval" under video settings?

**Comment by AlexFolland** [comment]
No, it's "Maximum swapchain images".

**Comment by larskj** [comment]
Setting of 1 is currently the same as 2.
Setting of 4 is currently the same as 3.

So if you want to try the difference, you should just alternate between a setting of 2 and 3.

**Comment by parkerlreed** [comment]
I'm not seeing it when running in KMS on Intel (Under Settings > Video) I'll try updating again and see if it shows.

**Comment by parkerlreed** [comment]
Aha it's there now, thanks!

**Comment by Themaister** [comment]
Implemented for Vulkan as well.

**Comment by AlexFolland** [comment]
Oh!  Nice!  Just as I made the new issue!  Haha.  :)
