### ISSUE TITLE
RetroArch crashes when loading some Capcom pre - CPS1 roms

### ISSUE THREAD

**Issue by christ776** [libretro/RetroArch#3103]
This happens in RA 1.3.3 and 1.3.4. Upon scanning roms, some of them detected as compatible with FB Alpha like for instance, Tiger Road. However, when trying to load it, Retroarch crashes.

<img width="1072" alt="screenshot 2016-06-12 19 20 42" src="https://cloud.githubusercontent.com/assets/1869205/15994151/cd3d2602-30d2-11e6-8ad8-3d0e3e2207c2.png">

**Comment by fr500** [comment]
Most likely a faulty romset.
In any case this should be reported here https://github.com/libretro/libretro-fba

**Comment by christ776** [comment]
thanks !
