### ISSUE TITLE
RetroArch segfaults when scanning any directory for games

### ISSUE THREAD

**Issue by kevinfishburne** [libretro/RetroArch#3105]
I tried this with current builds in both the stable and testing PPA's on Linux Mint 17.3 amd64. It even crashes scanning an empty directory, so it's not bad ROMs. I also deleted the config file in ~/.config/retroarch, so it's not a settings file issue. RetroArch worked on my system a couple of weeks ago until reinstalling it from PPA tonight. Any ideas on how to gather more information about the crash? The terminal simply outputs "Segmentation fault". dmesg reports "error 4 in retroarch".

**Comment by hizzlekizzle** [comment]
Launching from a terminal with --menu --verbose will give you a full output to the console. You can also try running it through gdb for more information.

**Comment by kevinfishburne** [comment]
--menu --verbose display a lot of output, but nothing just before the crash:

kevinfishburne@codex:~$ retroarch --menu --verbose
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Jun 12 2016
RetroArch [INFO] :: Version: 1.3.4
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Looking for config in: "/home/kevinfishburne/.config/retroarch/retroarch.cfg".
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
RetroArch [INFO] :: Config: loading config from: /home/kevinfishburne/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [ERROR] :: Failed to connect to Wayland server.
RetroArch [INFO] :: Found GL context: x
RetroArch [INFO] :: Detecting screen resolution 3840x1080.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 960, H = 720.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalEXT.
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 750/PCIe/SSE2.
RetroArch [INFO] :: [GL]: Version: 4.4.0 NVIDIA 340.96.
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => exists
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 960x720
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: [GL]: Using GL_RGB565 for texture uploads.
RetroArch [INFO] :: [udev]: Plugged pad: Logitech Logitech Dual Action (046d:c216) on port #0.
RetroArch [INFO] :: Autodetect: 0 profiles found
RetroArch [INFO] :: Autodetect: no profiles found for Logitech Logitech Dual Action (1133/49686)
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event4) supports 0 force feedback effects.
RetroArch [INFO] :: [udev]: Plugged pad: USB Gamepad  (0079:0011) on port #1.
RetroArch [INFO] :: Autodetect: 0 profiles found
RetroArch [INFO] :: Autodetect: no profiles found for USB Gamepad  (121/17)
RetroArch [INFO] :: [udev]: Pad #1 (/dev/input/event15) supports 0 force feedback effects.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 768 frames
RetroArch [INFO] :: ALSA: Buffer size: 3072 frames
RetroArch [INFO] :: ALSA: Can pause: yes.
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [/home/kevinfishburne/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapIntervalEXT(1)
Segmentation fault

Running it in gdb only displays this when it crashes:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000424184 in ?? ()

**Comment by kevinfishburne** [comment]
Turns out the retroarch package in synaptic fails to install as dependencies or even recommend the installation of any of the libretro packages. Issuing "sudo apt-get install libretro*" solves the problem, however after the ROMs are scanned RetroArch fails to add the relevant systems to the menu, so there's no way to access the scanned ROMs. Ideas?

**Comment by kevinfishburne** [comment]
Perhaps there is a discrepancy between the way Lakka configures RetroArch versus a vanilla RetroArch installation. Lakka automatically adds a system icon after ROMs are scanned, but vanilla RetroArch does not, requiring me to use "Load Content", "Select File And Detect Core", then manually browse to the ROM.

**Comment by Kivutar** [comment]
Lakka uses vanilla retroarch, but we provide the database and the core infos out of the box. While in the vanilla retroarch you have to download those through the online updater, which is not very intuitive.

**Comment by kevinfishburne** [comment]
Not intuitive, but it works. Thank you. I may now be able to forgo Lakka and do a proper distro with the NVIDIA drivers for good output on my CRT television with RetroArch. Good information, but the "unintuitive" part should be modified so the user is prompted if they want to update the games database on first run or something.

**Comment by Kivutar** [comment]
If you still like Lakka, you can learn how to compile it by yourself and customize it to suit your needs. For example, this pull request shows how to build Lakka with the proprietary NVIDIA drivers and X11 https://github.com/libretro/Lakka/pull/391/files

**Comment by kevinfishburne** [comment]
I do like Lakka; I reinstalled it yesterday after getting poor performance on the same machine using Mint 17.3 with the binary NVIDIA drivers, surprisingly. This question is probably beyond the scope of this bug report (which should be under PPA dependency recommendations), but is there a script to create a "testing" Lakka .img with 391's X11 and/or proprietary driver additions? All I need is xrandr but I don't know how to compile Lakka from source or create a bootable image. The nouveau driver works amazingly well in Lakka. Nouveau and X11 with xrandr could control over/underscan compensation easily and it would be awesome.

**Comment by Kivutar** [comment]
Yes, clone lakka, apply this PR, https://github.com/libretro/Lakka/pull/391 and compile it following the instructions on the wiki.

**Comment by kevinfishburne** [comment]
@Kivutar Okay, I suck at git. I've cloned Lakka and have a Lakka directory full of files. What command do I issue to apply the pull request, and do I issue it from within the Lakka directory (containing CHANGELOG, config, CONTRIBUTING.md, etc.) or some other directory?

**Comment by kevinfishburne** [comment]
Not too much code was changed, so I manually edited the source files to remove and add lines as necessary and am compiling now. Will report findings.

**Comment by kevinfishburne** [comment]
Got "checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool" during compilation. Tried this to install perl "XML::Parser" module and am reattempting compilation:

http://mynixworld.info/2014/02/17/xmlparser-perl-module-required-intltool/

**Comment by kevinfishburne** [comment]
Failed the second time after burning 8 cores for nearly two hours with:

Resolving us.download.nvidia.com (us.download.nvidia.com)... 23.205.120.114, 23.205.120.128
Connecting to us.download.nvidia.com (us.download.nvidia.com)|23.205.120.114|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38511679 (37M) [application/octet-stream]
Saving to: 'sources/xf86-video-nvidia/NVIDIA-Linux-x86_64-340.96-no-compat32.run'

100%[====================================================================================================================================================================================================>] 38,511,679  6.59MB/s   in 6.3s   

2016-06-21 01:42:45 (5.86 MB/s) - 'sources/xf86-video-nvidia/NVIDIA-Linux-x86_64-340.96-no-compat32.run' saved [38511679/38511679]

  UNPACK   xf86-video-nvidia
Creating directory build.Lakka-Generic.x86_64-devel/xf86-video-nvidia-340.96
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 340.96.........................................................................................................................................................................................................
      APPLY PATCH (common)   /home/kevinfishburne/Lakka/Lakka/packages/x11/driver/xf86-video-nvidia/patches/xf86-video-nvidia-kernel-3.18.patch
patching file kernel/nv-drm.c
Hunk #1 succeeded at 17 with fuzz 2.
Hunk #2 succeeded at 119 with fuzz 2 (offset 4 lines).
  BUILD    xf86-video-nvidia (target)
make[1]: Entering directory '/home/kevinfishburne/Lakka/Lakka/build.Lakka-Generic.x86_64-devel/xf86-video-nvidia-340.96/kernel'
The kernel you are installing for is a PREEMPT_RT kernel!

The NVIDIA driver does not support real-time kernels. If you 
are using a stock distribution kernel, please install 
a variant of this kernel that does not have the PREEMPT_RT 
patch set applied; if this is a custom kernel, please 
install a standard Linux kernel.  Then try installing the 
NVIDIA kernel module again.

*** Failed PREEMPT_RT sanity check. Bailing out! ***

nvidia-modules-common.mk:201: recipe for target 'build-sanity-checks' failed
make[1]: *** [build-sanity-checks] Error 1
make[1]: Leaving directory '/home/kevinfishburne/Lakka/Lakka/build.Lakka-Generic.x86_64-devel/xf86-video-nvidia-340.96/kernel'
make: *** [image] Error 2
kevinfishburne@codex:~/Lakka/Lakka$

Complete terminal output from both failures is here:

http://eightvirtues.com/lakka/Lakka%20-%20Two%20Compile%20Fails%20in%20Mint%2017.3

**Comment by Kivutar** [comment]
Ok, that's a problem. You need to revert the Real Time kernel patch we applied last week. Try to use git revert with the commit id, and launch compilation again.

**Comment by kevinfishburne** [comment]
There are five RT-related commits when I look here: https://github.com/libretro/Lakka/commits/lakka I ran the command "git checkout bd067b2db6a984857f841f08a70a8fc5537a8e69" which hopefully will "revert" the code back to the "Gamegirl, finalize inputs" commit on June 14th, just before all the RT commits. I checked a file and it appears to have worked (yes, I barely know what I'm doing). Compiling now; will report findings.

**Comment by kevinfishburne** [comment]
Here's the terminal output of compile failure three: http://eightvirtues.com/lakka/Lakka%20-%20Compile%20Fail%20Three

Everything works until attempting to build the image, after which it gives "No space left on device" errors. When I try to boot a pen drive using the resulting image it fails. I just merged my root and home directories on my workstation to ensure I had enough disk space locally, so this seems to be some other error, perhaps related to how it creates the image file. Here's the end of the terminal output:

```
mkimage: boo. now root access (sudo) is required...
mkimage: see scripts/image and scripts/mkimage if you dont trust us :)
[sudo] password for kevinfishburne: 
image: creating image: /home/kevinfishburne/Lakka/Lakka/target/Lakka-Generic.x86_64-devel-20160622011755-r21471-gbd067b2.img...
292+0 records in
292+0 records out
306184192 bytes (306 MB) copied, 0.277069 s, 1.1 GB/s
image: creating partition table on /home/kevinfishburne/Lakka/Lakka/target/Lakka-Generic.x86_64-devel-20160622011755-r21471-gbd067b2.img...
image: creating part1 on /home/kevinfishburne/Lakka/Lakka/target/Lakka-Generic.x86_64-devel-20160622011755-r21471-gbd067b2.img...
image: creating part2 on /home/kevinfishburne/Lakka/Lakka/target/Lakka-Generic.x86_64-devel-20160622011755-r21471-gbd067b2.img...
image: writing mbr...
1+0 records in
1+0 records out
440 bytes (440 B) copied, 0.000240637 s, 1.8 MB/s
image: creating filesystem on part1...
tune2fs 1.42.9 (4-Feb-2014)
e2fsck 1.42.9 (4-Feb-2014)
/dev/loop0: clean, 11/65536 files, 18527/262144 blocks
image: mounting part1 on /tmp/tmp.Gc7HtatCJl...
image: creating bootloader configuration...
image: installing extlinux to part1...
/tmp/tmp.Gc7HtatCJl is device /dev/loop0
image: copying files to part1...
cp: error writing '/tmp/tmp.Gc7HtatCJl/SYSTEM': No space left on device
cp: failed to extend '/tmp/tmp.Gc7HtatCJl/SYSTEM': No space left on device
cp: error writing '/tmp/tmp.Gc7HtatCJl/splash.png': No space left on device
cp: failed to extend '/tmp/tmp.Gc7HtatCJl/splash.png': No space left on device
cp: error writing '/tmp/tmp.Gc7HtatCJl/vesamenu.c32': No space left on device
cp: failed to extend '/tmp/tmp.Gc7HtatCJl/vesamenu.c32': No space left on device
cp: error writing '/tmp/tmp.Gc7HtatCJl/libcom32.c32': No space left on device
cp: failed to extend '/tmp/tmp.Gc7HtatCJl/libcom32.c32': No space left on device
cp: error writing '/tmp/tmp.Gc7HtatCJl/libutil.c32': No space left on device
cp: failed to extend '/tmp/tmp.Gc7HtatCJl/libutil.c32': No space left on device
image: unmounting part1...
image: creating filesystem on part2...
tune2fs 1.42.9 (4-Feb-2014)
e2fsck 1.42.9 (4-Feb-2014)
/dev/loop0: clean, 11/8192 files, 5530/32768 blocks
image: mounting part2 on /tmp/tmp.Gc7HtatCJl...
image: unmounting part2...
image: compressing...
image: cleanup...
kevinfishburne@codex:~/Lakka/Lakka$ ^C
kevinfishburne@codex:~/Lakka/Lakka$ 

```

**Comment by kevinfishburne** [comment]
Holy shit, may have figured it out. I edited the /scripts/mkimage file and changed "SYSTEM_SIZE=256" to "SYSTEM_SIZE=512" and didn't get the errors on next compile. Will test booting to the resulting image and report.

**Comment by kevinfishburne** [comment]
I can boot to the image but X and RetroArch fail to start. I'm modifying local code to try to change the NVIDIA driver version to 304.131 for my older video card. I'm not sure if the codebase dynamically downloads string-specified driver versions like that, but I'm testing just in case. Compiling now to see.

**Comment by kevinfishburne** [comment]
I can compile and boot to the image now and modifying Lakka/packages/x11/driver/xf86-video-nvidia/package.mk does cause it to download the correct driver version, however during compilation it displays this, which may be a problem (no idea):

      GET      xf86-video-nvidia
--2016-06-22 02:38:21--  http://us.download.nvidia.com/XFree86/Linux-x86_64/304.125/NVIDIA-Linux-x86_64-304.125-no-compat32.run
Resolving us.download.nvidia.com (us.download.nvidia.com)... 104.70.123.9, 104.70.123.11
Connecting to us.download.nvidia.com (us.download.nvidia.com)|104.70.123.9|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 41547370 (40M) [application/octet-stream]
Saving to: 'sources/xf86-video-nvidia/NVIDIA-Linux-x86_64-304.125-no-compat32.run'

100%[====================================================================================================================================================================================================>] 41,547,370  7.11MB/s   in 6.5s   

2016-06-22 02:38:28 (6.11 MB/s) - 'sources/xf86-video-nvidia/NVIDIA-Linux-x86_64-304.125-no-compat32.run' saved [41547370/41547370]

      CLEAN    xf86-video-nvidia
          * Removing build.Lakka-Generic.x86_64-devel/xf86-video-nvidia-340.96 ...
      UNPACK   xf86-video-nvidia
Creating directory build.Lakka-Generic.x86_64-devel/xf86-video-nvidia-304.125
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 304.125...................................................................................................................................................
          APPLY PATCH (common)   /home/kevinfishburne/Lakka/Lakka/packages/x11/driver/xf86-video-nvidia/patches/xf86-video-nvidia-kernel-3.18.patch
patching file kernel/nv-drm.c
Hunk #1 succeeded at 17 with fuzz 2.
Hunk #2 succeeded at 75 with fuzz 1 (offset -40 lines).
      BUILD    xf86-video-nvidia (target)
make[1]: Entering directory '/home/kevinfishburne/Lakka/Lakka/build.Lakka-Generic.x86_64-devel/xf86-video-nvidia-304.125/kernel'
NVIDIA: calling KBUILD...
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\

When I boot into Lakka it shows this:

systemctl reports this:

![0622161900](https://cloud.githubusercontent.com/assets/19770207/16287005/251b320a-38ae-11e6-8a6d-63758eeacc4e.jpg)

Lakka:~ # systemctl status xorg.service
● xorg.service - Xorg Server
   Loaded: loaded (/usr/lib/systemd/system/xorg.service; disabled; vendor preset: enabled)
   Active: activating (start) since Wed 2016-06-22 23:05:27 UTC; 4s ago
 Main PID: 1281 (xorg-launch-hel)
   CGroup: /system.slice/xorg.service
           └─1281 xorg-launch-helper vt01 -s 0 -noreset -allowMouseOpenFail

Jun 22 23:05:27 Lakka xorg-launch[1281]: (EE)
Jun 22 23:05:27 Lakka xorg-launch[1281]: Fatal server error:
Jun 22 23:05:27 Lakka xorg-launch[1281]: (EE) no screens found(EE)
Jun 22 23:05:27 Lakka xorg-launch[1281]: (EE)
Jun 22 23:05:27 Lakka xorg-launch[1281]: Please consult the The X.Org Foundation support
Jun 22 23:05:27 Lakka xorg-launch[1281]: at http://wiki.x.org
Jun 22 23:05:27 Lakka xorg-launch[1281]: for help.
Jun 22 23:05:27 Lakka xorg-launch[1281]: (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
Jun 22 23:05:27 Lakka xorg-launch[1281]: (EE)
Jun 22 23:05:27 Lakka xorg-launch[1281]: (EE) Server terminated with error (1). Closing log file.

Any ideas what's going on? Perhaps I need to create an xorg.conf file?

**Comment by kevinfishburne** [comment]
I'm "moving" this thread to the forums, as it's become off-topic. Here's the forum link: http://libretro.com/forums/showthread.php?t=6143

**Comment by Alexandre-Garcia** [comment]
@kevinfishburne 
Today I removed the RT kernel patch of my fork for now, until I get compile the Nvidia driver with RT.
You can clone my fork of Lakka and compile by this.
git clone https://github.com/Alexandre-Garcia/Lakka.git
I changed the variable NVIDIAX11 to X11SERVER, then must compile this way.
DISTRO=Lakka PROJECT=Generic ARCH=x86_64 X11SERVER=yes make image
Currently this with the Nvidia driver 340, however you can switch to 304 in the same way you already did. I already test with 304 driver and a 6200 LE card and works fine.
After the first boot you can customize your xorg.conf file and put in the config folder.
