### ISSUE TITLE
Unload Core, without quitting RetroArch

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#3112]
From the game/core, have the ability to quit the game, without shutting down the entire frontend.

### Problem

Currently, there is the RETRO_ENVIRONMENT_SHUTDOWN command that you can send as an environment callback. This will close RetroArch. There is no way, however, to have the Core unload without having RetroArch completely shutdown.

#### Example
1. Run RetroArch
2. Load the ScummVM Core
3. Start the core
4. Click on Quit
5. RetroArch will then Close
  - Expected result is to return back to the RetroArch menu

### Proposed Solution

Introduce a RETRO_ENVIRONMENT_SHUTDOWN_CORE command, that will have RetroArch unload the core and return to the RetroArch menu.

**Comment by Alcaro** [comment]
Why is the core allowed to shut down the frontend at all? Why not just repurpose that env?

**Comment by RobLoach** [comment]
So, `RETRO_ENVIRONMENT_SHUTDOWN` in RetroArch would then just unload the core and return to the RetroArch menu? I like that idea.

**Comment by Alcaro** [comment]
And even if there are cores that have valid reasons to shut down the entire program, we don't need to add a new env for that. The shutdown env is currently documented as "argument must be NULL"; we could replace that with "argument is int*; if pointed-to value is 0, shuts down core; if 1, shuts down front; for backwards compatibilty reasons, NULL is treated as pointer to 1".

Could be a config option too...

**Comment by tony971** [comment]
Sounds like a technical version of #3006

**Comment by RobLoach** [comment]
Another good use of this would be to safely unload the core when the system's BIOS is not found, and inform the user to install the BIOS correctly.

**Comment by orbea** [comment]
Personally I would use both use cases, sometimes I just want to close RetroArch + core all at once  and this should be easy to do quickly without any additional work. Other times I would like to shut off the core without killing retroarch or perhaps even swap it for another core in one step.
