### ISSUE TITLE
NES: Turbo A/B as separate buttons

### ISSUE THREAD

**Issue by eugene-s-nesdev** [libretro/RetroArch#3114]
Hey.
I have an request.
Can you add ability to set "Turbo A" and "Turbo B" as separate buttons with NES cores?

Will be nice to able set "X" as "turbo A" and "Y" as "turbo B" on RetroPad:
![cv](https://cloud.githubusercontent.com/assets/13199529/16099221/d626f632-335f-11e6-8015-871f5d2cecb6.jpg)

like NES emulators and some pirate controllers has:
![joy](https://cloud.githubusercontent.com/assets/13199529/16099229/e5849076-335f-11e6-8bd7-de387bdc5728.jpg)

Preferred default keyboard set:
X - NES A button
Z - NES B button
S - NES turbo A button
A - NES turbo B button

---
Thank you.

**Comment by fr500** [comment]
This could be handled by input remapping in the future, in the meantime, some cores (fceumm) already have this, we don't add hacks per-core in RA itself.

**Comment by eugene-s-nesdev** [comment]
Ok, thank you.
Need to wait input remapping because this feature is out-of nestopia core:
https://github.com/rdanbrook/nestopia/issues/187

**Comment by Sega-Zero** [comment]
@fr500 any ETA on input remapping feature? would weally like to have this when playing with classic snes gamepad

**Comment by hizzlekizzle** [comment]
@Sega-Zero Input remapping is already in, in the 'controls' submenu on the 'quick menu'.

**Comment by Sega-Zero** [comment]
@hizzlekizzle can you please post a screenshot of it? Couldn't map X/Y buttons on my usb snes gamepad as turbo buttons for nes games. They work only with FCEUMM, but as a single A/B. Not sure if I've set it correctly in recalbox environment.

**Comment by hizzlekizzle** [comment]
@Sega-Zero [here you go](https://i.imgur.com/imKfGs5.png). That's the 'controls' menu, [located on the in-game 'quick menu' alongside the save/load state and shader options](https://i.imgur.com/ADnAzmn.png).

**Comment by Sega-Zero** [comment]
@hizzlekizzle thank you so much for your screens! With Nestopia core everything works perfectly!
