### ISSUE TITLE
Netplay loads save data from client, not server; saves to server only.

### ISSUE THREAD

**Issue by SlordNorb** [libretro/RetroArch#3115]
When using netplay, the game will sync the client's srm file to the server (client srm overwrites server srm); then, if you save in-game, the server's srm file will be updated but not the client's. This causes the newer save to get overwritten by the older one when the two connect again. I have started the game separately between netplay sessions to confirm the state of each srm file.

**Comment by fr500** [comment]
Netplay is being revamped, review after the next release and report back
