### ISSUE TITLE
Bind All timer

### ISSUE THREAD

**Issue by brandleesee** [libretro/RetroArch#3118]
Suggestion: Bind All timer to be extended.

Since I am not exactly conversant with the names given to the specific buttons on a gaming pad with actually realising which button is being referred to, I found the timer very unhelpful. Too fast!

In the end I configured my gaming pad's buttons individually.

**Comment by gouchi** [comment]
You can change the bind timeout [here](https://github.com/libretro/RetroArch/blob/master/menu/menu_driver.h#L54) but you will need to recompile your own version.

**Comment by brandleesee** [comment]
That would be rather difficult for one not familiar with recompiling.
Can this setting be increased by default?

**Comment by twinaphex** [comment]
I could turn it into a setting I guess where you can increase the timeout value.

**Comment by brandleesee** [comment]
Yes, please!
I would really find a longer timer useful.
Hopefully, others would too, thanks.

**Comment by twinaphex** [comment]
Added a setting for adjusting the bind timeout - 

https://github.com/libretro/RetroArch/commit/f9b535ea91bd9137ba0ae61950e77bda63274200
