### ISSUE TITLE
Savestates can't be overwritten outside of encrypted /home partition

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/RetroArch#3122]
I'm using the latest git build from AUR and the savestates outside the dm-crypt encrypted _/home_ partition can't get overwritten. Here's the log of the error:
`RetroArch [INFO] :: Error -1 renaming file /mnt/files/Vidya roms/TruRetro/Contra (Japan).state1RetroArch [INFO] :: Failed to save undo information "/mnt/files/Vidya roms/TruRetro/Contra (Japan).state1".`

**Comment by fr500** [comment]
That is dead code by now, there is a different implementation pending a
merge that doesn't flush the undo information to disk.

**Comment by GeneralFailer** [comment]
So I gather that as per #3098 merge this should now be fixed?

**Comment by fr500** [comment]
yes

**Comment by GeneralFailer** [comment]
OK, works fine now.
