### ISSUE TITLE
Missing core

### ISSUE THREAD

**Issue by OptionK9** [libretro/RetroArch#3125]

**Comment by OptionK9** [comment]
Iphone 6 plus, iOS 9.1 
Retroarch version: retroarch git iOS 9 

I can't find any core for mupen64plus
I've run all the updates, is this because I'm on 9.1 or is this core missing or do I need to get it from another repo?

**Comment by RobLoach** [comment]
http://buildbot.libretro.com/nightly/apple/ios9/latest/

Looks like BuildBot didn't push forwards? http://buildbot.libretro.com/log/osx-bot/2016-06-18/

**Comment by fr500** [comment]
a missing core only means it's failing to build for a while, when it builds it will be uploaded.
Not a RetroArch issue in any case.

http://buildbot.libretro.com/log/osx-bot/2016-06-17/2016-06-17_mupen64plus_ios9.log
