### ISSUE TITLE
Build failure with making a debug version of RetroArch

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3129]
OS: `Slackware64-current`
`gcc-5.3.0_multilib-x86_64-3alien`

When building a debug version of the RetroArch git master it fails, this does not occur with the stable 1.3.4 release.

Here is a full log of the build. http://pastebin.com/F3UtzrCn
```
LD retroarch
obj-unix/cores/libretro-ffmpeg/fft/fft.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
Makefile:126: recipe for target 'retroarch' failed
make: *** [retroarch] Error 1
```
I am building a debug version of RetroArch like this.
```
CFLAGS="-O0 -g" \
CXXFLAGS="-O0 -g" \
./configure --prefix=/usr \
--with-man_dir=/usr/man

make GL_DEBUG=1
```

**Comment by Alcaro** [comment]
Google suggests that means you're missing -lstdc++, but we shouldn't need that at all.

`make V=1` shows the full compiler invocations, rather than shortening them to `CC foobar.c`. Do that so I can check if there's any hidden g++ invocations in there.

**Comment by orbea** [comment]
Sorry, I missed that option otherwise I would of included it. Here is a new log.

http://pastebin.com/27abnzwr

**Comment by Alcaro** [comment]
Not sure if it's documented anywhere, I only found it in the source.

> g++ [...] cores/libretro-ffmpeg/fft/fft.cpp
> /usr/bin/gcc -o retroarch [...]

Yeah, bad combination.

**Comment by orbea** [comment]
Thanks! However that doesn't seem to have been the last one...
```
obj-unix/gfx/drivers_context/drm_ctx.o: In function `gfx_ctx_drm_egl_set_video_mode(gfx_ctx_drm_data*)':
/tmp/SBo/RetroArch/gfx/drivers_context/drm_ctx.c:603: undefined reference to `egl_init_context(egl_ctx_data_t*, gbm_device*, int*, int*, int*, int const*)'
/tmp/SBo/RetroArch/gfx/drivers_context/drm_ctx.c:614: undefined reference to `egl_create_surface(egl_ctx_data_t*, void*)'
collect2: error: ld returned 1 exit status
Makefile:126: recipe for target 'retroarch' failed
make: *** [retroarch] Error 1
```
Log: http://pastebin.com/0jvLEkU4

**Comment by Alcaro** [comment]
apparently CXX_BUILD causes some completely incomprehensible issues on @twinaphex's system.

**Comment by twinaphex** [comment]
I can build with GL_DEBUG=1 fine now. Reopen if there is still an issue on your end.
