### ISSUE TITLE
Core setting - hardware shared context enabled - turns off in Linux

### ISSUE THREAD

**Issue by Geyup** [libretro/RetroArch#3130]
I compiled 1.3.4 in Slackware 14.1 x86_64

When I access the core section and turn on ```hardware shared context enabled``` If I access the core section again after setting it to on it will turn to off, but if I don't go back into core it stays on.

hmm odd

**Comment by twinaphex** [comment]
This was an issue actually related to this - 

https://github.com/libretro/RetroArch/issues/3148

It should be fixed now.

**Comment by Geyup** [comment]
thanks...
