### ISSUE TITLE
MaterialUI/GLUI text disappears after backing out of certain menu

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#3136]
Android 6.0.1

RetroArch 1.3.4_GIT from Fdroid repo (6/21/2016)

I load RetroArch, go to Add Content > Download Content > lutro, download a game or two, and then when I hit the back button in the upper left all text disappears.

**Comment by twinaphex** [comment]
Should be fixed now as of this commit -

https://github.com/libretro/RetroArch/commit/f5fcd45a3f08ec39f19ee339447ddcf1ecfe1557

**Comment by parkerlreed** [comment]
All good! Thanks.
