### ISSUE TITLE
XMB fancy ribbon glitches on AMD GPU

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#3137]
Arch x86_64
retroarch-git 2:1.3.1.r3132.8a8fadc-1
Latest assets

https://www.youtube.com/watch?v=XeM5J2d7BAs When it happened to me before.

https://www.youtube.com/watch?v=4vFZ1Mjg3hw Just now.

A couple of the lines seem to glitch out of place in the animation. I initially thought this had been fixed but it turns out this does not happen on my work machine (Intel i3 CPU with i915 driver). Only on my home desktop (AMD R7 260x using RadeonSI)

Here's the console output on the AMD machine

```
[parker@x3720 Downloads]$ retroarch -vvv
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 
Built: Jun 21 2016
RetroArch [INFO] :: Version: 1.3.4
RetroArch [INFO] :: Git: 8a8fadc
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Looking for config in: "/home/parker/.config/retroarch/retroarch.cfg".
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
RetroArch [INFO] :: Config: loading config from: /home/parker/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ fullscreen
RetroArch [ERROR] :: Failed to connect to Wayland server.
RetroArch [INFO] :: Found GL context: x
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [X11]: Xinerama version: 1.1.
RetroArch [INFO] :: [X11]: Xinerama screens: 1.
RetroArch [INFO] :: [GLX]: Using Xinerama on screen #0.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 1920, H = 1080.
RetroArch [INFO] :: [GLX]: Using windowed fullscreen.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalMESA.
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: X.Org, Renderer: Gallium 0.4 on AMD BONAIRE (DRM 2.43.0 / 4.6.2-1-ARCH, LLVM 3.9.0).
RetroArch [INFO] :: [GL]: Version: 3.0 Mesa 12.1.0-devel (git-48593ea).
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => exists
RetroArch [INFO] :: Querying GL extension: ARB_sync => exists
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => exists
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => exists
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 1920x1080
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: [GL]: Using GL_RGB565 for texture uploads.
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Suspending screensaver (X11).
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 768 frames
RetroArch [INFO] :: ALSA: Buffer size: 3072 frames
RetroArch [INFO] :: ALSA: Can pause: yes.
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [/home/parker/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: Saving config at path: "/home/parker/.config/retroarch/retroarch.cfg"
RetroArch [INFO] :: Saved new config to "/home/parker/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: [X11]: Xinerama version: 1.1.
RetroArch [INFO] :: [X11]: Xinerama screens: 1.
RetroArch [INFO] :: [X11]: Saved monitor #0.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
```

@Kivutar

**Comment by parkerlreed** [comment]
Also confirmed on my laptop with an R4 GPU. Seems to be an issue with Radeon in general.

**Comment by RobLoach** [comment]
Seems pretty smooth to me, on integrated graphics.

**Comment by parkerlreed** [comment]
Does it not have the same behavior as the videos I posted? It's smooth for me also it's just that some of the lines jerk out of place.

**Comment by RobLoach** [comment]
No Jerking around. I could be testing wrong though. Latest build of master.

**Comment by parkerlreed** [comment]
Yeah all I did was a fresh compile of master and pulled the assets in the online updater. @twinaphex pointed out on IRC

````
<Twinaphex> it sounds like a glitch to do with GLSL partial derivatives for AMD GPUs
<Twinaphex> maybe precision related ?
<Twinaphex> try compiling from source and changing precision to high for floatp
<Twinaphex> for that shader
<Twinaphex> https://github.com/libretro/RetroArch/blob/master/gfx/drivers/gl_shaders/modern_pipeline_xmb_ribbon_simple.glsl.vert.h#L4
<Twinaphex> should have to be added somewhere at the beginning here
<Twinaphex> you might have to use a different macro
<Twinaphex> or create a new one
<Twinaphex> since GLSL( will likely define precision to low
````

**Comment by parkerlreed** [comment]
FWIW this is now happening with the Vulkan backend and vulkan-radeon from Mesa 13.0.

**Comment by retrotails** [comment]
Can confirm it happens on my RX480, but only with open source drivers. Closed source drivers don't have the issue. It happens with BOTH the normal and simplified ribbon, since they use the same random function. Judging by the magic number in the vertex shader, it looks like it's its from a well-known psuedorandom GLSL function that's been floating around the internet. I think it's dependant on GPU quirks. Here's just the noise function on my desktop and tablet. Notice it compiles on the tablet, yet it's completely black.
https://imgur.com/ouxLbsl
And the shader
http://glslsandbox.com/e#36617.0
One solution is to use a more complicated noise function. I tried this one
https://github.com/ashima/webgl-noise/blob/master/src/noise3D.glsl
Here's a screenshot of it, it's slightly different but it doesn't have the glitch and seems to get 60fps at 4k with no issues still.
https://imgur.com/U8KMflI

**Comment by Kivutar** [comment]
Ok it's good enough, I'm for switching to it.

**Comment by Kivutar** [comment]
@retrotails So I used the noise you gave us, with some tweaks http://hastebin.com/gotavuxobi.c

![capture du 2016-11-08 20-42-43](https://cloud.githubusercontent.com/assets/442722/20114291/eee08222-a5f3-11e6-850b-b050b75afacc.png)

**Comment by twinaphex** [comment]
Hi there @retrotails,

are you the author behind that snow shader video on Youtube?

Mind if you gave us a source snapshot or a diff showing the changes so we can incorporate this into RetroArch? Don't worry if it's not cleaned up or polished, we can take care of the integration.

**Comment by retrotails** [comment]
@twinaphex Yes I am. Originally I used a shader with no license found on glslsandbox.com, but I wrote my own from scratch based on a different noise function (credited in the source)
http://pastebin.com/UiLC4ZJ3
I tried adding a menu option for snow, but straight-up could not do it. I added that shader where the other shaders were but I have no clue how to get it to actually use them. The existing thing is a hack that overrides the xmb_init_ribbon() function in xmb.c to be only 4 vertices so it fills the screen, then I replaced the simple ribbon fragment shader with the snow one. Here's a diff, it's a total hack.
http://pastebin.com/2hFJqYsf
Oh by the way, the shader is set up to loop. When I wrote shaders for a mobile game a while back, I ran into precision issues with things looping for too long, so this loops exactly every 11.2 minutes. If you just send the shader a time variable, it'll still work, but looping the time variable on the CPU would be better.
Also the resolution is just baked in. Ideally it should scale based on the actual rendering resolution min(res.x, res.y) Of course you can scale it to whatever but it looks a bit silly when it's too big/small.

**Comment by retrotails** [comment]
So the changes to the snow shader use the same function that makes the ribbon shader problematic, apparently for speed reasons. Which is reasonable, the other option is relatively slow especially for targeting lower-end hardware. Would it be possible to use a lookup texture instead? Like 512x512 tilable perlin noise maybe? That could be helpful for both the snow and ribbon shaders.

**Comment by hizzlekizzle** [comment]
Yeah, that would be good/nice. Unfortunately, the menu shaders don't expose as many features as the regular, in-game shader backend, including lookup textures.

**Comment by OGWillikers** [comment]
I was searching for previously known glitches that I'm experiencing and found one that may be related.  I see this on my Intel Bay Trail-based Celery processor, model J1800, onchip GPU.  Happens sometimes when I run OpenGL cores.  Running Lakka, no idea if it's specific to that or RetroArch.

http://imgur.com/tRknGZE

**Comment by Q3CPMA** [comment]
Hello, is this still supposed to happen on 1.6.1?

**Comment by hizzlekizzle** [comment]
Yeah, we haven't fixed it yet. We probably just need to wrap the noise function in a mod() so that it resets every so often. This will cause a stutter in the animation, but we can make it happen only once every 5 min or whatever, where it's unlikely to be seen/noticed.

**Comment by Kivutar** [comment]
But we fixed the same issue on MALI, it was a pecision issue. Can we do the same for other gpu?

**Comment by hizzlekizzle** [comment]
AFAIK, you can't set precision for desktop OGL, only GLES (well, you can set it, but it doesn't do anything).

**Comment by RobLoach** [comment]
Mind re-testing and opening this issue up again with the issue template if it persists? A lot of changes have happened to the shader pipeline since last year.... Thanks!
