### ISSUE TITLE
Make Scan Directory Recursive

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#3139]
This has been discussed in a few different issues:
- https://github.com/libretro/RetroArch/issues/3038 Different suggestions for playlists
- https://github.com/libretro/RetroArch/issues/2102 Some ideas about LPL files
- https://github.com/libretro/RetroArch/issues/2033 Alternative scanning method

I thought I'd have specific issue, with a distinct goal to **make Scan Directory go into sub-folders recursively**.

### Problem

When you add your collection, you use Scan Directory, and have to select each folder for every system. This takes time, and can be confusing when you see 10 different async actions running at the same time.

### Proposed Solution

Make Scan Directory recursively go into child directories. Then to add your whole collection, you just have to select the parent folder, and it'll add all files and child folders' files to your playlists. To accomplish this, when scanning through and it files a folder, it would add the folder to the task queue, similar to just selecting Scan Directory on each child folder from the menu.

**Comment by yisraeldov** [comment]
This is something I have also wanted, and really  seems like a trivial thing to implement ( although I haven't tried it myself ).

**Comment by brandleesee** [comment]
I am also in favour of recursive searches. It minimises confusion with newcomers and makes the task less tedious to those who have already used RA.

**Comment by mikebutash** [comment]
I'll vote for this as well, something of a pain adding directories individually.

Either way, it really needs a queuing mechanism for directory scans so they don't all pile one atop the other as you select directories.  Doing so on a remote cifs/nfs share just dogs everything down on large directories all at the same time as I found it begins doing.  

Getting enough scans going it seems to bug out and stop displaying progress of any of them until some finally complete, a global progress against said queue of items to be scanned would be better here, especially with the recursive that take a while.

**Comment by shinra358** [comment]
would love this feature.

**Comment by RobLoach** [comment]
This works! Thanks a lot, @bparker06.... For those following along, this was done at https://github.com/libretro/RetroArch/pull/3412 .

**Comment by sergiobenrocha2** [comment]
This is a interesting feature, but it should be optional... I have some beta/hack roms inside each console folder, and I don't like to see them in the playlist. But yeah, it's a interesting feature for newcomers.

**Comment by RobLoach** [comment]
> I have some beta/hack roms inside each console folder, and I don't like to see them in the playlist.

Move them into a different location then? clrmamepro, or similar, would read them as part of the No-Intro DAT.

**Comment by sergiobenrocha2** [comment]
Yup, that's my problem. I guess I'll get used with this new feature. At least people will complain less.

**Comment by RobLoach** [comment]
But, it does seem like it could be an option in the settings. Create a new issue in the queue! Have Scan Recursively be optional.

**Comment by Kivutar** [comment]
I love recursive scanning :o
