### ISSUE TITLE
Fast-rewinding regression

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#3140]
Fast-rewinding (non-blocking rewinding by holding rewind and fast-forward simultaneously) no longer works.  It was an feature intentionally added by @Themaister in 2011 or 2012.

I haven't checked when it stopped working, but I believe it was quite a while ago; at least a year.  Over the past year or so since I've been back to testing RA every once in a while, I have been trying to fast-rewind and when it didn't work, putting it on the backburner in my mind, since I was always testing other issues, which is why I'm only bringing it up now.  Sorry about lateness!

**Comment by parkerlreed** [comment]
What game/core are you trying with? Genesis Plus GX and Sonic the Hedgehog 2 for me rewinds normal speed and if I continue to hold rewind and press fast-forward it's a faster rewind. Linux x86_64.

**Comment by AlexFolland** [comment]
Maybe this is limited to Windows.  I just tested Genesis Plus GX with Sonic 2 and holding both results in the core running forward at normal speed, as if I'm holding neither.

WAIT!  Maybe these binds I have are stupid.  Let me check something.

**Comment by AlexFolland** [comment]
Yup.  I figured out the problem and it's not a bug with RA.  I have rewind bound to L2 and fast-forward bound to R2.  With the PS4 controller I'm using and the ScpToolkit which allows me to use it with Windows, L2 and R2 are opposing ends of 1 axis, so when I hold both, they cancel out at zero.  No wonder it wasn't working!  What a stupid situation.

Closing this issue!

**Comment by parkerlreed** [comment]
Good to hear. I have a suggestion for Windows: ds4window http://ds4windows.com/

Acts as a Xbox controller by default but you can customize any of the button to do whatever. So R2 and L2 could emulate a keyboard button or I think (Don't quote me because I'm not sure) they can each be their own axis.
