### ISSUE TITLE
Load Recent menu ignores the core used

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/RetroArch#3145]
I'm using a recent build from git. If I choose the file currently loaded with a different core in the Load Recent menu, RetroArch just opens the current core's quick menu. This may turn out being convenient in some rare cases, but overall doesn't seem logical.

**Comment by fr500** [comment]
Just close content beforehand

**Comment by GeneralFailer** [comment]
Umm, okay. Just seemed like a weird behavior.
