### ISSUE TITLE
Error while compiling on Debian 8.5 

### ISSUE THREAD

**Issue by Moonl1ghter** [libretro/RetroArch#3147]
I got a compile error on Debian 8.5 stable, x86-64. 

This is the output of the compiler:

audio/drivers/roar.c: In function ‘ra_init’:
audio/drivers/roar.c:47:7: warning: implicit declaration of function ‘RARCH_ERR’ [-Wimplicit-function-declaration]
RARCH_ERR("RoarAudio: \"%s\"\n", roar_vs_strerr(err));
^
audio/drivers/roar.c: In function ‘ra_stop’:
audio/drivers/roar.c:89:11: error: ‘roar_t’ has no member named ‘is_paused’
roar->is_paused = true;
^
audio/drivers/roar.c: In function ‘ra_alive’:
audio/drivers/roar.c:98:16: error: ‘roar_t’ has no member named ‘is_paused’
return !roar->is_paused;
^
audio/drivers/roar.c: In function ‘ra_start’:
audio/drivers/roar.c:113:11: error: ‘roar_t’ has no member named ‘is_paused’
roar->is_paused = false;
^
audio/drivers/roar.c: In function ‘ra_alive’:
audio/drivers/roar.c:99:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
Makefile:130: recipe for target 'obj-unix/audio/drivers/roar.o' failed
make: *** [obj-unix/audio/drivers/roar.o] Error 1
make: *** Waiting for unfinished jobs....
Failed to build RetroArch

The output of **./configure** was this:

Checking operating system ... Linux
Checking for suitable working C compiler ... /usr/bin/gcc works
Checking for suitable working C++ compiler ... /usr/bin/g++ works
Checking for pkg-config ... /usr/bin/pkg-config
Checking for availability of switch -std=gnu99 in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-result in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-variable in /usr/bin/gcc ... yes
Checking function bcm_host_init in -lbcm_host ... no
Checking function sd_get_machine_names in -lsystemd ... no
Checking presence of package egl ... 10.3.2
Checking function ass_library_init in -lass ... no
Checking function pthread_create in -lpthread ... yes
Checking function dlopen in -ldl ... yes
Checking function socket in -lc ... yes
Checking function getaddrinfo in -lc ... yes
Checking function fcntl in -lc ... yes
Checking function getopt_long in -lc ... yes
Checking presence of package alsa ... 1.0.28
Checking presence of header file sys/soundcard.h ... yes
Checking presence of header file soundcard.h ... no
Checking existence of -lossaudio ... no
Checking function alcOpenDevice in -lopenal ... yes
Checking presence of package rsound >= 1.1 ... no
Checking presence of package libroar ... 1.0.11
Checking presence of package jack >= 0.120.1 ... 1.9.10
Checking presence of package libpulse ... 5.0
Checking presence of package sdl >= 1.2.10 ... 1.2.15
Checking presence of package sdl2 >= 2.0.0 ... 2.0.2
Notice: SDL drivers will be replaced by SDL2 ones.
Checking presence of package libusb-1.0 >= 1.0.16 ... no
Checking presence of header file GL/gl.h ... yes
Checking existence of -lGL ... yes
Checking function cgCreateContext in -lCg ... yes
Checking presence of package zlib ... 1.2.8
Checking presence of package libavcodec >= 54 ... 56.1.0
Checking presence of package libavformat >= 54 ... 56.1.0
Checking presence of package libswresample ... no
Checking presence of package libavutil >= 51 ... 54.3.0
Checking presence of package libswscale >= 2.1 ... 3.0.0
Checking presence of header file libavutil/channel_layout.h ... yes
Notice: FFmpeg recording disabled due to missing or unsuitable packages.
Checking function dlopen in -ldl ... yes
Checking presence of package gbm >= 9.0 ... 10.3.2
Checking presence of package libdrm ... 2.4.58
Checking presence of package libxml-2.0 ... 2.9.1
Checking presence of package vg ... no
Checking existence of -lOpenVG ... no
Checking presence of package libv4l2 ... 1.6.0
Checking function glFramebufferTexture2D in -lGL ... yes
Checking presence of package freetype2 ... 17.1.11
Checking presence of package x11 ... 1.6.2
Checking presence of package xcb ... 1.10
Checking presence of package wayland-egl ... 10.3.2
Checking presence of package xkbcommon >= 0.3.2 ... 0.4.3
Checking presence of package xext ... 1.3.3
Checking presence of package xxf86vm ... 1.1.3
Checking presence of package xinerama ... 1.1.3
Checking presence of package xv ... 1.0.10
Checking presence of package libudev ... 215
Checking presence of header file linux/parport.h ... yes
Checking presence of header file linux/ppdev.h ... yes
Checking function strlcpy in -lc ... no
Checking function strcasestr in -lc ... yes
Checking function mmap in -lc ... yes
Checking function vkCreateInstance in -lvulkan ... no
Creating make config: config.mk
Creating config header: config.h

I compiled RetroArch on an other machine, but maybe you can fix this!

**Comment by Alcaro** [comment]
Looks like that driver broke in [October 2014](https://github.com/libretro/RetroArch/commit/a35c61ec90f7530364c3b21afe8c3534a6ee7639) and has been dead ever since. And nobody noticed.

Fun.

**Comment by Moonl1ghter** [comment]
I now this is not the place for these kinds of question. But why did didn't it build? On my other machine with Debian it build fine.

**Comment by Alcaro** [comment]
Because only one of your computers have package libroar installed, so the other computer didn't try to use the broken code that tries to use that package.

**Comment by Moonl1ghter** [comment]
I didn't even now I had roar installed and I don't now why I should need it. I only use alsa and pulse. But thanks anyway! Wil try to compile again tomorrow.
