### ISSUE TITLE
[LINUX] System/BIOS Dir

### ISSUE THREAD

**Issue by lollo78** [libretro/RetroArch#3148]
On Ubuntu 16.04 I can change all the path in Directory menu, except fot the System/BIOS.
It remain always on the default "content dir". 
In using 
https://launchpad.net/%7Elibretro/+archive/ubuntu/testing/+index?field.series_filter=&batch=75&direction=backwards&start=300

**Comment by twinaphex** [comment]
Shoudl be fixed now with this -

https://github.com/libretro/RetroArch/commit/e91136017ea997bcb348ca3014b9a32ad37b49e3
