### ISSUE TITLE
[Request] Dark mode for MaterialUI/GLUI

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#3149]
Was just using it on my phone today when I finally realized what was missing, a dark mode/night theme for MaterialUI. Maybe located next to the color options under Settings > Menu.

**Comment by rz5** [comment]
@parkerlreed, if you know how to code, https://github.com/libretro/RetroArch/blob/master/menu/drivers/materialui.c is the source file you want to look at.
@Kivutar, the author of it, can probably do what you asked in less than an hour. I tried hacking at it and the maximum I could achieve was a gray chinbar. It's not immediately apparent to me what sets the foreground (text), background, active and inactive colors in that file.

I'll add that this feature would have the benefit of consuming significantly less power in devices with OLED displays.

**Comment by Kivutar** [comment]
Colors are here https://github.com/libretro/RetroArch/blob/master/menu/drivers/materialui.c#L719-L782

**Comment by rz5** [comment]
Here's what I got so far: 
![image](https://cloud.githubusercontent.com/assets/8117159/16554478/0df9489c-41c7-11e6-93be-bcfac2f1c354.png)

**Comment by Kivutar** [comment]
That's already nice!

**Comment by rz5** [comment]
@parkerlreed: Check out a nightly version of RetroArch. There should be a new menu option that will expose a couple of of new light colors and at least 1 darkish theme.

Remember to close the ticket.

**Comment by twinaphex** [comment]
Yeah, I'm fine with adding even more color themes later on.

**Comment by parkerlreed** [comment]
:D love it http://i.imgur.com/VUUW4BT.png

Nice touch with the transparency under the bottom bar.
