### ISSUE TITLE
Don't show "maximum swapchain images" with most video backends

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#3153]
https://github.com/libretro/RetroArch/issues/3100

The linked issue resulted in @Twinaphex implementing a "maximum swapchain images" option.  This nice option for DRM/KMS currently doesn't work with any other video backends, including all that are usable on most platforms, which may cause some users confusion as they try to adjust the setting and it does nothing.

I see there being decent solutions here: @Themaister hooks it up for Vulkan (as @Twinaphex has said in IRC that he is not confident that he would do this properly), and/or it is somehow hidden when incompatible video backends are in use.

Is hiding options that are only available with certain video and/or audio backends possible and/or trivial right now?

**Comment by Themaister** [comment]
Video context drivers would have to expose "caps" bits in some way.

**Comment by AlexFolland** [comment]
I see you've just implemented the option for Vulkan, so that's done.  Thanks!  I guess the other part of this issue is still relevant.

**Comment by twinaphex** [comment]
Yeah, there is a caps bit set/get function for each video context driver. Right now its only used for setting one particular capability, cant recall which. In either case, we can definitely start adding a swapchain cap to it and then using it from the menu driver to selectively show or hide it depending on whether its available.

**Comment by twinaphex** [comment]
Its the function callbacks get_flags and set_flags for the video context driver interface.

**Comment by Ryunam** [comment]
Could this option be compatible and / or useful with the OpenGL renderer?

**Comment by Themaister** [comment]
Only KMS. It is not possible to control this in regular GL. GPU Hard Sync is similar, but the hacky version.

**Comment by twinaphex** [comment]
This should be the case now. Reopen if things are still unsatisfactory.
