### ISSUE TITLE
Changes to Input Hotkey Binds do not stick anymore in the latest Nightly

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#3155]
How to reproduce:
- From Settings -> Input -> Input Hotkey Bind, assign a controller button to any function (for instance, "Fast-forward hold" to RT on xinput controller)
- Press F1 / Guide Button to go back to gameplay. The corresponding function does not work when pressing the assigned button (does not fast-forward on hold).
- Press F1 / Guide Button again to go back to Settings -> Input -> Input Hotkey Binds. The previously assigned controller button didn't stick. It only shows default keyboard binds.

Possibly related to **[this](https://github.com/libretro/RetroArch/commit/e91136017ea997bcb348ca3014b9a32ad37b49e3)**?

**Comment by twinaphex** [comment]
Yes, it was related.

Had to revert it unfortunately since there's no easy way to get it to work.
