### ISSUE TITLE
[Android] Per-core input binding configuration does not cycle

### ISSUE THREAD

**Issue by markikollasch** [libretro/RetroArch#3158]
I'm using the Android version of RetroArch, which identifies itself as the May 3 2016 build, on a Nexus 7 2013.

I'm experiencing an issue related to binding controls per-core. It's present with every core I've tried that has a Controls setting, so I don't believe it's an issue with the core itself.

Steps to reproduce:
1. Load a core and some content, then start the core.
2. Open the Quick Menu, then navigate to Controls.
3. Tap on one of the user input bindings options, for instance, "User 1 B :" in the core for a system with a B button. It will step forward through the available RetroPad buttons.
4. Continue tapping the input until it reaches whichever RetroPad button is the "last" (in my case, "RetroPad R3 Button"). After reaching this state, tapping the list item again will no longer change the binding.

User impact:
The UI appears to provide no way to change a per-core input binding to a button in the list that's prior to the current or default binding.

Ideally, the core Controls menu would work like the main Input > Binds configuration menu, in that it would respond to the bound inputs directly. But at least, the interaction of tapping to cycle through the bindable inputs should cycle back to the start of the button list after reaching the end.

**Comment by UncleDaddySwiss** [comment]
Same issue here, Pretty big over-sight.

**Comment by fr500** [comment]
This isn't really fixed but since configurations per-core doesn't exist anymore this doesn't apply.
