### ISSUE TITLE
Retroarch crashes when changing Overlay scale

### ISSUE THREAD

**Issue by Brhoom93** [libretro/RetroArch#3159]
As simple as the title, although it only happens with a nightly build, a stable build doesn't crash but a nightly build does. It's not an instant crash but as soon as I change the scale Windows tell me Retroarch stopped working.

**Comment by JippC** [comment]
Dont think it did this on 1.3.4 but on 1.3.6 it does this for me.

**Comment by hizzlekizzle** [comment]
I can confirm this. Here's a backtrace via gdb:
http://pastebin.com/K6sQzNgX

**Comment by orbea** [comment]
This doesn't crash in linux, @hizzlekizzle, @Brhoom93  and @JippC is this still a problem for you?

**Comment by ofry** [comment]
Can't reproduce this on Windows 8.1 x64, display_driver="gl", menu_driver="xmb"

**Comment by ofry** [comment]
If you're still have this problem, please give more info (which overlay, which settings etc)

**Comment by orbea** [comment]
This was probably fixed a while ago when other issues with the overlays were fixed so until someone else can reproduce this and provide more info I am going to assume its good now.
