### ISSUE TITLE
Feature request: Display DS3/4 battery level

### ISSUE THREAD

**Issue by phuque99** [libretro/RetroArch#3167]
Sony wireless DualShock controller's battery status is found in the following path when connected on bluetooth:

/sys/class/power_supply/sony_controller_battery_(mac address)/

And the battery capacity is reported in the "capacity" file in that folder above. Can you add a feature to display the controller's battery capacity in one of the "Information" menu item?

libretro/Lakka#414

**Comment by neher** [comment]
+1 for wiimotes

You can find the battery capacity for wiimotes in /sys/class/power_supply/wiimote_battery_(mac address)/capacity

**Comment by syepes** [comment]
+1

**Comment by jedinjapan** [comment]
If Retroarch could add a battery display option, the path could be defined by the automatic configuration file and would be trivial to update in the future as new devices are added down the road. For those that don't use bluetooth like Xbox and the DS4 Dongle, that is beyond the scope of the project, but this would be useful for other third party gamepads as well.

**Comment by toto99303** [comment]
any updates on this?

**Comment by nwildner** [comment]
Since data collected at `/sys/class/power_supply/sony_controller_battery_(mac address)/` will always have the values `100`, `75`, `50` and `25`, a battery icon with 4, 3, 2 or 1 bars would be awesome.

+1 to this.

**Comment by toto99303** [comment]
I hope that this feature will be implemented and not forgotten :)

**Comment by klepp0906** [comment]
just tossing my hat in on this one.  the ability to see controller battery level would be cool.   understandably not high priority im sure.   I just came across the "show battery level" setting and that coupled with this leads me to believe thats related to "device" battery like if youre running on something other than a pc.

**Comment by gouchi** [comment]
It should work, you did enable in Settings tab > User Interface > Views > Show battery level ?

**Comment by klepp0906** [comment]
i did, does it require usb connection or does it work over bluetooth as im always connected ala bluetooth?

support steam controller/dualshock4/xbox one?

**Comment by gouchi** [comment]
It will look for 

`/sys/class/power_supply/*battery*/capacity`

So if it exists, it will display battery level.

**Comment by klepp0906** [comment]
huh well, on windows ive just checked on two pc's with retroarch installed and that toggled on.   not showing the battery indicator.

unless it only pops up when its low battery or something as mines likely full atm. 

also realize how stupid my assertion about a usb requirement was considering.   its early, coffee hasnt had an opportunity to work yet ;p

**Comment by gouchi** [comment]
This issue was targeting Linux/Unix environment not Windows.

I tried on DS4 and it is working.

This issue should be closed and another issue should be opened for Windows case.
