### ISSUE TITLE
RetroAchievements display behaviour altered in recent nightly

### ISSUE THREAD

**Issue by telanus** [libretro/RetroArch#3168]
the last week the display of retroachievements that are unlocked is no longer displaying the achievement that's unlocked just a generic "downloading 'dorequest.php?r=awardachievement&u=...." 

Tested on retroarch 1.3.4+r385~42~ubuntu14.04.1 from the testing PPA, but also happening on Windows and Android (see linked thread)

Also reported here: http://libretro.com/forums/showthread.php?t=6145 and in lesser detail here: http://retroachievements.org/viewtopic.php?t=2457&o=90

**Comment by yisraeldov** [comment]
This also happens on OSX. Previously achievements were not being reported
to the server. Now they are but they are not being displayed correctly in
game.

**Comment by twinaphex** [comment]
I don't know how to fix this. @leiradel would probably be able to determine the cause.

**Comment by leiradel** [comment]
Fixed: https://github.com/libretro/RetroArch/pull/3170

**Comment by meleu** [comment]
RetroAchievements seems to be broken again... :cry: 
Recently (2016-08-30) I can't earn cheevos in NES games. Sometimes the Achievements list shows nothing, sometimes it shows all the achievements for the game as "Unlocked"...
Is there somebody else experiencing problems with it?

**Comment by leiradel** [comment]
@meleu could you open a new issue with a more detailed description of the problem and the steps to reproduce it? Please specify the core you're using, the game name, and its MD5 hash (it appears in the log).

Thanks.

**Comment by meleu** [comment]
well, I did nothing and today it is working fine. Maybe RetroAchievements servers were overloaded last night, I don't know. It happened with SNES (TNMNT 4), MegaDrive (Castlevania Bloodlines) and NES (Little Nemo), but they all are working fine today. Sorry for bothering here.

**Comment by leiradel** [comment]
No bother, it's much better to hear about false positives than it is to have a broken feature no one notices :)
