### ISSUE TITLE
All inputs get ignored if there was no gamepad when RetroArch was starting

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/RetroArch#3171]
I'm using a recent git build on Arch Linux. This happens when an input device for the 1st user is set. I've tested this with a Xbox 360 gamepad with xboxdrv and DualShock 4.

**Comment by sergiobenrocha2** [comment]
Why are you using xboxdrv? It should work out-of-box with newer kernel.

**Comment by GeneralFailer** [comment]
I've just mentioned it because its service is up, so nevermind that detail.

**Comment by sergiobenrocha2** [comment]
It's not a detail. Try use the controller without this xboxdrv. I remember I was having weird issues with it.

**Comment by GeneralFailer** [comment]
As I expected because of DualShock 4 also causing this issue, with xpad the issue persists.

**Comment by sergiobenrocha2** [comment]
I can't confirm this issue, my xbox controller is working here, kernel 3.13.0-91 on ubuntu 14.04. Purge the xboxdrv and it's config I guess, then try again.

**Comment by fr500** [comment]
No feedback and @sergiobenrocha2 couldn't repro, feel free to reopen if the issue persists.

**Comment by GeneralFailer** [comment]
I switched to the new version from the repos and it seems work fine.

**Comment by GeneralFailer** [comment]
I was wrong. It only works if the Xbox 360 gamepad is the one missing. 
I found out that this issue with the DS4 exists with the uinput joypad driver but not with the SDL2 one.

**Comment by GeneralFailer** [comment]
I don't have privileges to reopen the issue, BTW.

**Comment by GeneralFailer** [comment]
Summoning @fr500.

**Comment by GeneralFailer** [comment]
Seems to be working now.
