### ISSUE TITLE
"RetroPad Remote" core settings skips 34, 134, and 234

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#3173]
I'm configuring on Android in GLUI/MaterialUI. My computer's IP is 192.168.1.234. I noticed while cycling through numbers it skips 34, 134, and 234.

**Comment by parkerlreed** [comment]
Setting it manually in the core option cfg file doesn't work either. It gets set to 0 when opening RA back up.

**Comment by twinaphex** [comment]
@fr500 for your information.

**Comment by parkerlreed** [comment]
This has been resolved as of 88784aa
