### ISSUE TITLE
Save shortcuts to retropad buttons instead of physical button numbers

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#3180]
On consoles that don't take advantage of the full retropad button set, free buttons can be used for shortcuts like save/load states. The only issue is that these are saved to, say, button "3" instead of retropad X. This works if you're using a single controller type, but if you use controllers with different button numbering, this will cause headaches.

**Comment by fr500** [comment]
I think this would be pretty painful to implement.

**Comment by fr500** [comment]
Feel free to keep discussing this enhancement here.

**Comment by tony971** [comment]
Well that isn't exactly an ideal solution, either. If you map it to an autoconfig file, the button will ALWAYS be used for the shortcut. Whether the core needs it as a button or not. So if you map buttons X and Y as shortcuts for Gameboy use, they'd mess up the controls for PS1.

**Comment by fr500** [comment]
And if it used the retropad instead of button numbers it will mess up whenever input remapping is active.

**Comment by tony971** [comment]
If someone's using a core input remap, it's because they exclusively use one controller type for that core.

**Comment by fr500** [comment]
No, core input remap's usecase is actually the opposite, I use remaps with my xbox controller to make it use X/A instead of A/B, that's the main use case.

My point stands.
