### ISSUE TITLE
Onscreen Overlay settings menu contains items from Menu settings menu

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#3184]
Retroarch-GIT from FDroid on Android 6.0.1

![screenshot_20160703-131912](https://cloud.githubusercontent.com/assets/841440/16546710/feed19b0-4120-11e6-86a8-94ffe41cd049.png)

![screenshot_20160703-131924](https://cloud.githubusercontent.com/assets/841440/16546712/03d24b76-4121-11e6-9122-db33a365cb5e.png)

**Comment by twinaphex** [comment]
Fixed.

https://github.com/libretro/RetroArch/commit/cdc7c1283bc53e3f45693f84a6eb6e7aa5e9b59d
