### ISSUE TITLE
[Feature request] set disc index by config file

### ISSUE THREAD

**Issue by alec4** [libretro/RetroArch#3185]
Hi guys,

i'm just playing final fantasy viii with the pcsx_rearmed core and since i arrived disc 2 i have always to change the virtual disc before i can load my saved game. It would be great if i could set the disc index in the config file so i just change the file once per disc.

thank you
alec4

**Comment by fr500** [comment]
Doesn't seem like something we want in the main config. It's not a retroarch setting, it's a variable that only exists whilst a core that supports the disk interface is loaded.
I think this is a won't fix.
