### ISSUE TITLE
Error running on old video card

### ISSUE THREAD

**Issue by scorninpc** [libretro/RetroArch#3186]
Hello, 

I have the same error on different distros: ubuntu, debian, and now on lbuntu

I have tryed with another nvidia video card and works fine, but on MX 4000 video card, I got the follow error. I need to use this video card because it has s-video output for my old tv

can anyone give-me some advise for run retroarch? 

> :~$ retroarch -v --menu
RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3
MMX MMXEXT SSE1 SSE2 SSE3 Built: May  4 2016
RetroArch [INFO] :: Version: 1.3.4
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3
RetroArch [INFO] :: Looking for config in: "/home/scorninpc/.config/retroarch/retroarch.cfg".
RetroArch [WARN] :: screenshot_directory is not an existing directory, ignoring ...
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
RetroArch [INFO] :: Config: loading config from: /home/scorninpc/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [ERROR] :: Failed to connect to Wayland server.
RetroArch [INFO] :: Found GL context: x
RetroArch [INFO] :: Detecting screen resolution 1024x768.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 960, H = 720.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalMESA.
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Nouveau, Renderer: Mesa DRI nv18 x86/MMX/SSE2.
RetroArch [INFO] :: [GL]: Version: 1.2 Mesa 11.2.0.
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_texture_non_power_of_two => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_fragment_program => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_sync => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => doesn't exist
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => doesn't exist
RetroArch [INFO] :: GL: Using resolution 960x714
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [ERROR] :: Failed to compile vertex shader #0
RetroArch [ERROR] :: Failed to link program #0.
RetroArch [ERROR] :: GLSL stock programs failed to compile.
RetroArch [ERROR] :: [GL]: Failed to initialize shader, falling back to stock.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [ERROR] :: Failed to compile vertex shader #0
RetroArch [ERROR] :: Failed to link program #0.
RetroArch [ERROR] :: GLSL stock programs failed to compile.
RetroArch [ERROR] :: [GL]: Shader initialization failed.
RetroArch [ERROR] :: Cannot open video driver ... Exiting ...
RetroArch [ERROR] :: Fatal error received in: "init_video()"
 :~$

**Comment by hizzlekizzle** [comment]
Are you using the default XMB menu? If so, can you try changing menu_driver to "rgui" in your retroarch.cfg?

**Comment by scorninpc** [comment]
Thank you for fast reply

Same error with rgui:

> RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3
MMX MMXEXT SSE1 SSE2 SSE3 Built: May  4 2016
RetroArch [INFO] :: Version: 1.3.4
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Vendor: GenuineIntel
RetroArch [INFO] :: [CPUID]: Features: MMX MMXEXT SSE SSE2 SSE3
RetroArch [INFO] :: Looking for config in: "/home/scorninpc/.config/retroarch/retroarch.cfg".
RetroArch [WARN] :: screenshot_directory is not an existing directory, ignoring ...
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
RetroArch [INFO] :: Config: loading config from: /home/scorninpc/.config/retroarch/retroarch.cfg.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [ERROR] :: Failed to connect to Wayland server.
RetroArch [INFO] :: Found GL context: x
RetroArch [INFO] :: Detecting screen resolution 1024x768.
RetroArch [INFO] :: [GLX]: X = 0, Y = 0, W = 960, H = 720.
RetroArch [INFO] :: [GLX]: Found swap function: glXSwapIntervalMESA.
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Nouveau, Renderer: Mesa DRI nv18 x86/MMX/SSE2.
RetroArch [INFO] :: [GL]: Version: 1.2 Mesa 11.2.0.
RetroArch [INFO] :: Querying GL extension: ARB_ES2_compatibility => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_texture_non_power_of_two => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_fragment_program => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_sync => doesn't exist
RetroArch [INFO] :: Querying GL extension: ARB_texture_float => doesn't exist
RetroArch [INFO] :: Querying GL extension: EXT_texture_sRGB => doesn't exist
RetroArch [INFO] :: GL: Using resolution 960x714
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [ERROR] :: Failed to compile vertex shader #0
RetroArch [ERROR] :: Failed to link program #0.
RetroArch [ERROR] :: GLSL stock programs failed to compile.
RetroArch [ERROR] :: [GL]: Failed to initialize shader, falling back to stock.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [ERROR] :: Failed to compile vertex shader #0
RetroArch [ERROR] :: Failed to link program #0.
RetroArch [ERROR] :: GLSL stock programs failed to compile.
RetroArch [ERROR] :: [GL]: Shader initialization failed.
RetroArch [ERROR] :: Cannot open video driver ... Exiting ...
RetroArch [ERROR] :: Fatal error received in: "init_video()"

**Comment by hizzlekizzle** [comment]
Ok, try changing your video_driver from "gl" to "sdl2" or "xvideo". You'll still need to use RGUI instead of XMB with these drivers, as XMB only works with GL.

**Comment by scorninpc** [comment]
very nice, run perfectly
