### ISSUE TITLE
Video Filters won't work

### ISSUE THREAD

**Issue by mckimiaklopa** [libretro/RetroArch#3187]
Even on cores where it's supposed to work, setting a soft video filter does nothing

**Comment by twinaphex** [comment]
I just tried the 'darken' video filter on prboom and it works there.

One thing to keep into mind: video filters can either support RGB565 color format, XRGB8888, or both. If a core requires 32-bit color format (XRGB8888) and the video filter does not support this yet for whatever reason, then the filter will not work. Vice versa with RGB565.
