### ISSUE TITLE
(Raspbian) drm_gfx compilation error

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#3191]
I am having a compilation error on my Rpi3 (running Raspbian) because of a missing header file for the `drm_gfx` driver. Here is the output of `make` : 

    CC gfx/drivers/drm_gfx.c
    In file included from gfx/drivers/drm_gfx.c:15:0:
    /usr/include/xf86drm.h:40:17: fatal error: drm.h: Aucun fichier ou dossier de ce type
     #include <drm.h>
                     ^
    compilation terminated.
    Makefile:133: recipe for target 'obj-unix/gfx/drivers/drm_gfx.o' failed
    make: *** [obj-unix/gfx/drivers/drm_gfx.o] Error 1

The package `libdrm-dev` is installed on the system, but the `drm.h` file is not present in the `/usr/include/` directory.

What is the `drm` driver for ? Is it even used on a Raspberry Pi (I don't have X, RA runs on the framebuffer) ?

Here is the configuration command that I used : 
`./configure --disable-cheevos --enable-neon --disable-netplay --disable-networkgamepad --disable-oss --disable-pulse --disable-x11 --disable-sdl --disable-sdl2 --enable-floathard --disable-ffmpeg`

**Comment by twinaphex** [comment]
drm.h should be found inside /usr/include/libdrm

**Comment by natinusala** [comment]
You're right. The folder may not be correctly included then ? The problem appeared after commit d53cbfbdfba131354cd33fc570f67a46a57b9b05, when you backported the DRM driver.

**Comment by twinaphex** [comment]
Can you check out if you have that header file there in /usr/include/libdrm ?

**Comment by natinusala** [comment]
Yes, I have it, that's why I don't understand why the compiler doesn't see it as it seems that the folder is included in the `DRM_CFLAGS` (I have `DRM_CFLAGS = -I/usr/include/libdrm` in `config.mk`)

**Comment by natinusala** [comment]
It works by disabling KMS using the `--disable-kms` configuration fly. It's more like a workaround than a fix, that would be better to find out why isn't the library included when the DRM is enabled.

**Comment by twinaphex** [comment]
You'll have to figure this issue on your own end, the paths are correctly set here.

**Comment by natinusala** [comment]
Okay, I'll look at it. Thanks for your help

**Comment by RobLoach** [comment]
I had this error with libdrm...

```
/usr/bin/ld: obj-unix/gfx/drivers/drm_gfx.o: undefined reference to symbol 'drmModeGetPlane'
//usr/lib/x86_64-linux-gnu/libdrm.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```

**Comment by dukesilverfan** [comment]
@twinaphex, I have also been unable to compile Retroarch from Source using Retropie-Setup since the d53cbfb commit. I compiled without problem on 7/2, and ever since it fails to compile on the drm.h call. Here is a piece of log:

```
CC gfx/drivers/drm_gfx.c
In file included from gfx/drivers/drm_gfx.c:16:0:
/usr/include/xf86drm.h:40:17: fatal error: drm.h: No such file or directory
 #include <drm.h>
                 ^
compilation terminated.
```

I am running a RP3 with Retropie on 4.0beta-2. I verified that drm.h is in the /usr/include/libdrm/ 

Again, no problems before this commit. Since more than one of us are having an issue with drm.h, is it worth looking into more?
