### ISSUE TITLE
Can't change paths on System Dir setting

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#3192]
It's not possible to change paths on System Dir setting anymore, there's no < Use this directory >

**Comment by parkerlreed** [comment]
None of the directory settings have it. Also "Scan directory" and "Add content". It's just missing entirely.

**Comment by twinaphex** [comment]
Yes, I'm going to look into this today. The menu system got an overhaul and this part has yet to be ironed out.

**Comment by twinaphex** [comment]
Should be fixed now.
