### ISSUE TITLE
PCSX_ReARMed core doesn't work on RPi's

### ISSUE THREAD

**Issue by chewvodka** [libretro/RetroArch#3196]
The compiled core on buildbot doesn't work with the Raspberry Pi 2/3.  When you go to launch a game, it crashes RetroArch.  Google research shows that the core needs to be compiled with an ARM flag.  Buildbot apparently isn't going this.  So using the built in "Online Updater" does nothing really.  I'm really eager to get PSX compatibility working on my system.  If I can be of any help, let me know!

**Comment by cudencuden** [comment]
update to the latest nightly? core update is already disabled in online updater.

**Comment by chewvodka** [comment]
That's what I mean.  Using the latest nightly build of the core doesn't work.  I've updated it daily and the problem still exists.

**Comment by chewvodka** [comment]
This is my log when I try to launch a PSX game...

`RetroArch [INFO] :: === Build =======================================RetroArch [INFO] :: [CPUID]: Features:
Built: Mar 19 2016
RetroArch [INFO] :: Version: 1.3.2
RetroArch [INFO] :: Git: 4146350
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: [CPUID]: Features:
RetroArch [INFO] :: Config: loading core-specific config from: /storage/.config/retroarch/config/lr-pcsx-rearmed.so.cfg.
RetroArch [INFO] :: Loading dynamic libretro core from: "/storage/.config/retroarch/cores/lr-pcsx-rearmed.so"
RetroArch [ERROR] :: Failed to open libretro core: "/storage/.config/retroarch/cores/lr-pcsx-rearmed.so"
RetroArch [ERROR] :: Error(s): libpng12.so.0: cannot open shared object file: No such file or directory
RetroArch [ERROR] :: Fatal error received in: "load_dynamic()"
RetroArch [INFO] :: Saving config at path: "/storage/.config/retroarch/config/lr-pcsx-rearmed.so.cfg"
RetroArch [INFO] :: Saved new config to "/storage/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.`

**Comment by dankcushions** [comment]
is it this issue? https://github.com/RetroPie/RetroPie-Setup/issues/502

**Comment by chewvodka** [comment]
I'm not sure?  I am just using the RetroArch Online Updater, which downloads the already compiled .so file.  I'm not sure how to compile my own, or if I even should.  I thought this was all set and ready to go.  Is OpenELEC even able to compile things?  I thought that OS is pretty much locked up.

Also, I found a newer version of RetroArch in my GameStarter folder, and tried running with that instead.  I still have PCSX_ReARMed crashing after doing a Core Updater.  If I run the Mednafen_PSX (HW) core it also crashes.  If I run Mednafen_PSX it'll run ok, but extremly slow.  PCSX_ReARMed seems to be everybody's favorite core on the Pi 2/3, so that's what I'm trying to get working.

**Comment by joolswills** [comment]
you are running lakka ? if so, you should report this issue to them I guess ?

**Comment by chewvodka** [comment]
I'm running OpenELEC.  It autoloads Kodi.  From there, I'm using the GameStarter addon script to execute closing Kodi and launch RetroArch.  Lakka is an OS like OpenELEC right?  This isn't what I'm using.

**Comment by joolswills** [comment]
I can't advise then. openelec probably has that lib, but perhaps it can't find it, or it was built against another version.

**Comment by joolswills** [comment]
This isn't a retroarch bug though imho.

**Comment by hizzlekizzle** [comment]
Correct, this should probably be re-opened over in the libretro-pcsx-rearmed repo:
https://github.com/libretro/pcsx_rearmed
To correct the OP, it probably just needs some tweaks to the Makefile.libretro. I didn't see any references to libpng in there, so I'm not sure where that dependency is coming from.

**Comment by chewvodka** [comment]
Thanks guys.  I'll try and send it over there...  here's the latest error I'm getting:

RetroArch [INFO] :: Loading dynamic libretro core from: "/storage/.config/retroarch/cores/pcsx_rearmed_libretro.so"
RetroArch [ERROR] :: Failed to open libretro core: "/storage/.config/retroarch/cores/pcsx_rearmed_libretro.so"
RetroArch [ERROR] :: Error(s): /storage/.config/retroarch/cores/pcsx_rearmed_libretro.so: undefined symbol: gteNCLIP_arm
RetroArch [ERROR] :: Fatal error received in: "load_dynamic()"

**Comment by fr500** [comment]
Please use the PCSX ReARMed libretro bug tracker instead
