### ISSUE TITLE
Games run too fast

### ISSUE THREAD

**Issue by alec4** [libretro/RetroArch#3200]
Hi guys,

i installed just retroarch on a iPad Air 2 over sideload and every game that i tried runs faster as expected. Maybe it has something to do with, i tried only EU Version PAL Games.
Please fix this.

Thank you
alec4

**Comment by fr500** [comment]
Can you try NTSC games then?
Is VSYNC enabled?

**Comment by RobLoach** [comment]
Is Fast Forward enabled? Retest?

**Comment by RobLoach** [comment]
Closing this one for now, if it still persists, feel free to re-open with the [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md) in place.
