### ISSUE TITLE
FBA rom scans only picking up Neo Geo games

### ISSUE THREAD

**Issue by Mojohamster** [libretro/RetroArch#3201]
Last tested on the 07-07 nightly build.

Confirmed working on 1.3.4 android and PC with same core/rom files.

**Comment by Kivutar** [comment]
Try the v0.2.97.38 ROMset with merged ROMs.

**Comment by cudencuden** [comment]
there's a merged set? i only have split set

**Comment by Kivutar** [comment]
The difference can be in the database too. Not just in the code. @Mojohamster 

@cudencuden according to @lollo78 who updated the FBA database, yes

**Comment by lollo78** [comment]
The actual FBA database is based on v0.2.97.38 merged romset. You can find it on mamemaniaforever forum.
