### ISSUE TITLE
Please make easier to people find out radius' tutorial

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#3203]
There's this tutorial radius made:

http://www.libretro.com/index.php/getting-started-with-retroarch/

It should be nice to have a link in the homepage to it, and pin it up on twitter too. There are lot of people asking about a tutorial, they don't even know it already exists

**Comment by twinaphex** [comment]
Done.

http://www.libretro.com/index.php/getting-started-with-retroarch/
