### ISSUE TITLE
Can't Apply Shader Presets through GUI

### ISSUE THREAD

**Issue by reppard** [libretro/RetroArch#3205]
I'm using a fresh build off master and I can't apply shaders.  I've tried multiple cores. I can navigate to a cgp file but selecting it does nothing.  Nothing in the logs either.

Thanks

**Comment by twinaphex** [comment]
Try using the latest sources as of right now. I think I fixed this issue earlier today. I just tested loading a shader preset with 'Load Shader Preset' and it definitely works as of this very moment.

**Comment by reppard** [comment]
K, I'll refetch, rebuild, and give it a go.  I did confirm that I could set the shader via the video_shader option in my config.  Will update and/or close PR if all is well.  Thanks!

**Comment by reppard** [comment]
Totally works now.  Thanks again :+1:
