### ISSUE TITLE
Randomly freezes when RGUI menu is toggled in-game

### ISSUE THREAD

**Issue by alkaseltzerspadt** [libretro/RetroArch#3206]
Hello.  I use my Wii Classic Controller as my gamepad for RetroArch.  Sometimes, when opening the RGUI menu, using either the home button or F1, I will no longer be able to press any buttons at all.  The game itself is still running, like normal, but inputs will not be detected.  If I need to do anything for more information, I will gladly oblige.  I appreciate any help and give my thanks.  Have a good one.

**Comment by orbea** [comment]
Given the lack of recent activity or information crucial to debug this I am going to close this issue.

If this is still a problem please open a new issue and fill out the issue template to the best of your ability, thanks!
