### ISSUE TITLE
Feature: No "None" selection on Audio DSP Plugin Options

### ISSUE THREAD

**Issue by aparks5** [libretro/RetroArch#3208]
Version: 1.3.4

Observed Behavior: Once an audio DSP plugin is selected in Audio options, from the GUI there is no option to turn the Audio DSP plugin off. 

Feature Request: "None" or "Off" selection is made available.

**Comment by rz5** [comment]
@aparks5: That does suck. Currently the only way to get it off is to press keyboard 'Enter' or gamepad 'Start' while you're highlighting the audio DSP option - that will reset it to the default setting (off).

**Comment by fr500** [comment]
It's a file picker, why would it have a "none" DSP?
Press start to reset it to defaults

**Comment by aparks5** [comment]
Good to know, as a noob I did not intuit pressing start or enter to reset to defaults. Thanks. It may be a file picker but it looks like an options menu. In the DSP world, most DSP selections will have a "Bypass" or "Off" mode.
