### ISSUE TITLE
drm_gfx compilation error; fails on drm.h

### ISSUE THREAD

**Issue by dukesilverfan** [libretro/RetroArch#3211]
I have been unable to compile Retroarch using Retropie-Setup since the d53cbfb commit. I compiled without problem on 7/2, and ever since it fails to compile on the drm.h call. Here is a piece of log:

```
CC libretro-common/gfx/math/vector_3.c
CC libretro-common/gfx/math/matrix_4x4.c
CC libretro-common/gfx/math/matrix_3x3.c
CC gfx/drivers/drm_gfx.c
In file included from gfx/drivers/drm_gfx.c:16:0:
/usr/include/xf86drm.h:40:17: fatal error: drm.h: No such file or directory
 #include <drm.h>
                 ^
compilation terminated.
```

And here is a snippet of log of it working on 7/2, in the same section before the drm driver was added:
```

CC libretro-common/gfx/math/vector_3.c
CC libretro-common/gfx/math/matrix_4x4.c
CC libretro-common/gfx/math/matrix_3x3.c
CC gfx/drivers/gl.c
CC gfx/common/gl_common.c
CC gfx/drivers_font/gl_raster_font.c
CC libretro-common/glsym/rglgen.c
```

This seems similar to a closed issue regarding the same commit: https://github.com/libretro/RetroArch/issues/3191

I am running a RP3 with Retropie on 4.0-beta2. I verified that drm.h is in the /usr/include/libdrm/

Again, no problems before this commit. Since more than one of us are having an issue with drm.h, is it worth looking into more?

**Comment by twinaphex** [comment]
Great backwards compatibility the DRM guys ensured really.

**Comment by twinaphex** [comment]
Since it is still causing problems and not ready for general roll-out it seems, I will hide it behind an explicit configure switch for now. This kind of bullshit is why we cannot have nice things in the Linux scene and why everything has to be such a huge clusterfuck.

**Comment by twinaphex** [comment]
There,

it should no longer try to bake in the DRM video driver by default if it finds DRM headers.

https://github.com/libretro/RetroArch/commit/3f29e731e2efbe079a68a00bf38226d26835834c

To enable it now, you have to do configure --enable-plain_drm

**Comment by dukesilverfan** [comment]
Thanks for the super fast modification! I will compile when I get out of work before closing this.

**Comment by RobLoach** [comment]
```
./configure --disable-ffmpeg
make
```

Now works, well done Twinaphex. :+1:

**Comment by Heffer-Wolfe** [comment]
Is it possible to disable the bilinear filtering when using the DRM driver?
