### ISSUE TITLE
Setting Audio Mute = ON causes games to move at "turbo" speed

### ISSUE THREAD

**Issue by ItalianPlumbo47** [libretro/RetroArch#3212]
I just wanted to turn off the audio in the menu to listen to something else while I play, but doing that causes the game to move at "turbo" speed, you know, the fast forward toggle. I tested this in mGBA, VBA, PCSXR-ReARMed and FCEUmm and all of them are stuck on fast forward.

Additionally running from a commandline has mGBA spew

Invalid video register: 0x056
Invalid video register: 0x04E

over and over again. VBA says nothing but is also stuck on fast forward.

The fast forward key does nothing, changing the vsync and GPU sync options does nothing (in fact I have never seen them do anything) and this doesn't happen at all when Audio Mute = OFF.

**Comment by Kivutar** [comment]
I don't have this with Audio Mute, I have this when Audio is disabled, which is not the same. The cores are syncing to audio, so disabling audio removes the frame limit. This is the intented behaviour.

**Comment by zero17333** [comment]
I see. How do I mute this but keep it synced up?

**Comment by hizzlekizzle** [comment]
There are a few options. The first one is to enable vsync. If that's broken for some reason (which it sounds like it is; that's probably worth exploring), go to settings > frame throttle and set 'limit maximum run speed' to 1. Last option is to go into settings > audio and just drop the volume as much as it'll go (I'm not sure if this will actually work, but it's worth a shot).

**Comment by zero17333** [comment]
Thank you. Dropping the volume seems good enough for now

**Comment by Themaister** [comment]
One long standing issue with mute is that the audio driver is not started, this is not intuitive since unmuting won't unmute properly while in-game if RA started as muted.

**Comment by fr500** [comment]
Can't we just change mute from whatever it does now to set volume to the absolute minimum?

**Comment by Palatosino** [comment]
I have this problem too. I don't have audio disabled, i have it MUTED (keybinding to toogle_mute, and in settings -> audio, audio is enabled).

When I have the audio muted games goes faster than when I have audio (that goes a normal speed).

Is very annoying.

**Comment by Awakened0** [comment]
This was fixed awhile back: https://github.com/libretro/RetroArch/commit/154b98394b10f6ebbb05096144f870fae5e468f7
