### ISSUE TITLE
Use the game Description in the Menu

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#3214]
Currently, the  menu uses the `name` from the rom to display the name of the game. Using the "Description" may be a bit more helpful, particularly for the newly proposed ScummVM DAT: https://github.com/libretro/libretro-database/pull/221

![scummvm](https://cloud.githubusercontent.com/assets/25086/16829190/abd61cf8-4964-11e6-8b8e-790c37733eb6.png)

![scummvm2](https://cloud.githubusercontent.com/assets/25086/16829214/d0eaef82-4964-11e6-9c3f-983ba7bcf02e.png)

**Comment by RobLoach** [comment]
https://github.com/libretro/RetroArch/pull/3215

**Comment by t-paul** [comment]
How will that look now?

https://github.com/libretro/libretro-database/blob/master/dat/Sinclair%20-%20ZX%2081.dat#L6077
