### ISSUE TITLE
[XMB] Fresh RetroArch compile and asset pull results in missing icons/wrong font

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#3217]
![1468518612](https://cloud.githubusercontent.com/assets/841440/16849884/85027e6c-49ca-11e6-82e9-0fd150896c57.png)

Linux x86_64

Settings > Menu > XMB theme is set to "Custom" (This is a fresh retroarch directory and asset pull)

Setting the theme to "Monochrome" fixes the issue.

So the issue seems to be the wrong theme is set by default.

@Kivutar

**Comment by twinaphex** [comment]
Should be fixed with this commit - 

https://github.com/libretro/RetroArch/commit/fabf68e4413d2646e0edb9cac75e00450f9c4d04

**Comment by parkerlreed** [comment]
Just noticed I got this in the terminal

````
[parker@e73 ~]$ retroarch
Failed to open /home/parker/.config/retroarch/assets/xmb/custom/font.ttf: No such file or directory
Failed to open /home/parker/.config/retroarch/assets/xmb/custom/font.ttf: No such file or directory
````

Not sure if related.

**Comment by CoalaJoe** [comment]
Same issue here.
I have no xmb folder in ~/.config/retroarch/assets/

**Comment by parkerlreed** [comment]
@CoalaJoe If you just pull the assets once it should load fine. Fresh install with no config dir will look like that until you Online updater > Update Assets.

**Comment by hick007** [comment]
![captura de tela_2017-04-09_20-40-00](https://cloud.githubusercontent.com/assets/27170498/24841875/c7f0073a-1d64-11e7-8932-18e46108d889.png)
Fix error .config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
Download of the folder assent [https://buildbot.libretro.com/assets/frontend/assets.zip](url)
![captura de tela_2017-04-09_20-43-18](https://cloud.githubusercontent.com/assets/27170498/24841894/328678c2-1d65-11e7-8a13-5dfe4e592aac.png)

**Comment by Vulto** [comment]
https://buildbot.libretro.com/assets/frontend/assets.zip  Page is broken

**Comment by twinaphex** [comment]
It's not broken at all, I can download it just fine.

**Comment by Vulto** [comment]
It doesn't work to me :/

**Comment by retro-wertz** [comment]
link works fine here.

**Comment by cirelli94** [comment]
If I start retroarch as sudo I can download assets and now see icons.
If I try to dowload assets without sudo it says:
mkdir(/usr/share/retroarch/) error: Permission denied.                               │
Failed to create directory: "/usr/share/retroarch/".                                 │

Even if after have dowloaded assets, with the normal user I can't see icons. Whit sudo, yes!

**Comment by parkerlreed** [comment]
Question: Why is your install not just using the local `~/.config/retroarch`? A fresh git compile pulls them into the local directory and I don't have any issues.

**Comment by cirelli94** [comment]
I used pacaur!

**Comment by parkerlreed** [comment]
Huh I did the same. Weird.

**Comment by DestyNova** [comment]
Same problem here (latest commit: 5fe9a613f9555e32d5456ae3054fcb0a83418ce1).

**Comment by parkerlreed** [comment]
Check to make sure you don't have a ~~retarded~~ misconfigured /etc/retroarch.cfg

In some cases the config file either via packager/maintainer will have the assets directory and the like mapped to a place in /usr/. This isn't good for running as a normal user (The default packaging in Arch does this and makes me angry) I understand it's done for the packaged cores but it seems like there should be a better way than overriding the setting to save to ~/.config/retroarch.

**Comment by DestyNova** [comment]
Sorry, my fault. I didn't run the "Update assets" -- it's fine now 🤐

**Comment by b1scu1t** [comment]
If you are running Arch, you must install 'retroarch-assets-xmb' package available in the community repo.
It would help if the aforementioned package was listed as an optional dependency for Retroarch.

**Comment by edivanteixeira** [comment]
:headphones: Try this. 
`sudo pacman -S retroarch-assets-xmb retro-gtk `

**Comment by darksectordds** [comment]
> If I start retroarch as sudo I can download assets and now see icons. If I try to dowload assets without sudo it says: mkdir(/usr/share/retroarch/) error: Permission denied. │ Failed to create directory: "/usr/share/retroarch/". │
> 
> Even if after have dowloaded assets, with the normal user I can't see icons. Whit sudo, yes!
> 
> To use the link above, don't click but copy and paste... Or [DOWNLOAD ASSETS](https://buildbot.libretro.com/assets/frontend/assets.zip)
> 
> Edit: I fixed doing: sudo chmod -R 755 /usr/share/retroarch/

Thanks for assets.

I used [install instructions for Ubuntu 22.04.3 LTS](https://retroarch.com/index.php?page=linux-instructions) and got same issue. 
When I start looking a problem i was found location assets in config.

**/home/\<name\>/.config/retroarch/retroarch.cfg**
```
assets_directory = "~/.config/retroarch/assets"
```

Then i was found empty assets. 
Your assets helped me. Ty.
