### ISSUE TITLE
When binding controller, rebinds keyboard without presaing a key on the keyboard.

### ISSUE THREAD

**Issue by NihilisticEevee** [libretro/RetroArch#3219]
I have a 4play multi controller adaper, which i can get detected to work with linux raw driver, but when i start to map it, it starts maping the keyboard too. It maps a to down making me rebind the keyboard manually by editing the config, i have to do this multiple time just to bind one controller.  This is a major bug for me as when i swap to a diffrent controller on the 4play i have to rebind the controller again.
Also, im runing a arm based computer called the odroid xu4 and its running a debian based os.

I'll check if this bug is present in my normal controllers or if it just happends with my 4play adapter.

**Comment by NihilisticEevee** [comment]
Just tested my lts psx/usb pad, which is a playstation to usb adapter, the same problem is present in the device.

**Comment by NihilisticEevee** [comment]
The only occurs for me if i bind each seperatly. If i do bind all, it does not occur.

**Comment by fr500** [comment]
I think this is solved already. Reopen otherwise.
