### ISSUE TITLE
[i915 Linux] Crash when trying to start retroarch

### ISSUE THREAD

**Issue by neagix** [libretro/RetroArch#3223]
Retroarch was built from ce6f3f955c450c28f04c42f0f79657ef28ec12b5; attempting to start from X11.

This crash has been happening for a while now.

```
$ ./retroarch
get chip id failed: -1 [13]
param: 4, val: 0
[intel_init_bufmgr:1069] Error initializing buffer manager.
DRM_IOCTL_I915_GEM_APERTURE failed: Permission denied
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [13]
param: 4, val: 0
[intel_init_bufmgr:1069] Error initializing buffer manager.
Segmentation fault
```

User is in `video` group:

```
$ ls -lasth /dev/dri/
total 0
0 drwxr-xr-x  18 root root      4.6K Jul 16 14:41 ..
0 crw-rw----+  1 root video 226,   0 Jul 16 14:41 card0
0 crw-rw----   1 root video 226,  64 Jul 16 14:41 controlD64
0 crw-rw----+  1 root video 226, 128 Jul 16 14:41 renderD128
0 drwxr-xr-x   2 root root       100 Jul 16 14:41 .
```

Possible upstream (Intel) bug: https://bugs.launchpad.net/ubuntu/+source/intel-gpu-tools/+bug/783610
This is on Ubuntu 14.04

**Comment by sergiobenrocha2** [comment]
You mean launch RA on tty1 for example? No issue here, same OS.

**Comment by neagix** [comment]
@sergiobenrocha2 it's on the very first line of OP, "from X11". Not a VT. I know it works from VT.

**Comment by sergiobenrocha2** [comment]
Have you tried the PPA package? It's working here in any situation.

**Comment by bparker06** [comment]
I had the same problem when testing the new Vulkan API code. Try deleting ~/.config/retroarch/retroarch.cfg. If that doesn't help, try rebooting the machine. That did it for me.

**Comment by neagix** [comment]
@sergiobenrocha2 regardless I am testing master, not the PPA

@bparker06 same issue by doing both

**Comment by elslander-cedric** [comment]
@neagix same issue here, did you find any solution?

**Comment by neagix** [comment]
@elslander-cedric I have to say this is not happening anymore, tested with 617ce26 and 76a2499. Tip of master should be the same.

My configure is:
```
./configure --enable-alsa --disable-pulse --enable-kms --enable-sdl --disable-sdl2 --disable-materialui --disable-xmb --enable-rgui
```

Closing.

**Comment by neagix** [comment]
Reopening because I am using a different video card now -.- had missed that.

**Comment by elslander-cedric** [comment]
Sorry, I posted to quickly, just forgot to use xinit ...

running: "xinit /usr/bin/retroarch" dit the trick

**Comment by neagix** [comment]
@elslander-cedric in that case one could say it was a permissions issue

**Comment by RobLoach** [comment]
Interesting... I *think* this isn't an issue anymore? Feel free to re-open if it's still a problem. Thanks a lot.
