### ISSUE TITLE
Vulkan driver causes immediate app crash

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#3229]
GPU: nVidia GTX 660 (Vulkan API supported)
OS: Windows 7 64-bit Pro
RetroArch version: 1.3.6 vanilla

Issue: When changing to the Vulkan graphics driver in the driver settings, saving and closing the emulator, the emulator immediately crashes upon loading, no matter what.  The user is forced to remove the config files and start anew, but using the API will cause the program to crash 100% of the time, despite the machine supporting the feature. 

Linked below is a video showing the steps I'm doing to get my GPU to run the famed Vulkan-optimized N64 emulator, but I guess that's impossible at this point. 

https://youtu.be/Ebk0v4kgkXI

**Comment by alex34567** [comment]
Try setting the menu driver to rgui.

**Comment by roflcopter777** [comment]
Doesn't that kind of defeat the purpose of having a Vulkan API driver as an option? It seems that my machine probably can't run it.

**Comment by Themaister** [comment]
It could be related to this: https://github.com/libretro/RetroArch/issues/3225. It might be fixed now.

**Comment by fr500** [comment]
@roflcopter777 rgui is a menu driver, vulkan is a video driver it doesn't defeat the purpose, he asked you to test because the default menu driver (xmb) is more complex so it may be part of your supposed problem.

The vulkan driver is good and working:
https://www.youtube.com/watch?v=-K5PQzBqaYY

**Comment by roflcopter777** [comment]
It...was a driver issue, the N64 emulator works *sigh* Well I'm an idiot.
