### ISSUE TITLE
Menu Input sometimes gets stuck when the GUI takes several frames to react.

### ISSUE THREAD

**Issue by bootsector** [libretro/RetroArch#3232]
KMS mode, Linux 64-bit, sixad daemon

Lots of covers/thumbnails (mainly MAME ones).

When using a PS3 pad (bluetooth) and try to scroll rapidly between playlists, interface lags and controller gets crazy, sometimes it's necessary to turn it of (via home button 10 seconds long press) in order to get back to normal.

When using USB controller, interface lags but controller gets back to normal, eventually.

**Comment by fr500** [comment]
I think this is reproducible in emscripten when loading from "online downloads"
When the interface takes more than a frame to refresh input gets somewhat stuck if the button was held.

**Comment by hizzlekizzle** [comment]
Does this still happen?
