### ISSUE TITLE
Changing Configuration with different video driver makes RA crash

### ISSUE THREAD

**Issue by Morku** [libretro/RetroArch#3233]
Hardware: Nvidia SHIELD K1 1.3 with RetroArch 1.3.6 Playstore version.

When starting RetroArch with default retroarch.cfg and e.g. OpenGL driver, now Loading a Configuration (which I prepared before) with e.g. Vulkan video driver makes RetroArch crash.
First I thought, my device don't like Vulkan, but when I changed video driver to Vulkan in retroarch.cfg and now change my to my specific cfg with same Video Driver, it doesn't crash anymore.

Conclution: Changing Configuration only works when same Video Driver will be loaded.

**Comment by fr500** [comment]
It's a known issue and while we agree it would be good to have changing drivers on the fly is pretty complicated.

It won't be "fixed" soon in any case it's a big undertaking

**Comment by orbea** [comment]
Closing this in favor of issue https://github.com/libretro/RetroArch/issues/4804.
