### ISSUE TITLE
Switching to Vulkan API crashes on nVidia Shield Lollipop

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#3235]
Updated emulator to version 1.3.6 via Google Play store, changed driver from default to Vulkan, saved config and sure enough, the app crashes. 

Tablet: nVidia Shield K1 2015 model
OS: Lollipop 5.1.1
RA version: 1.3.6 vanilla

I take it this is either an issue on my end, or the fact that people on Lollipop are SOL and will be forced to update to Marshmallow (which I think would be trivial). Reasoning would be that I've heard nothing but negative things regarding 6.x.x and having piss-poor performance for apps like emulators. Top that off with the fact I would lose all my data that's not on my microSD card. 

Is there no way to get this to work, is it truly a bug with the version I'm using? nVidia states that Vulkan runs on the K1 tablet, the Tegra K1 processor, no?

**Comment by parkerlreed** [comment]
I thought Vulkan support was only on Marshmallow and above? (Mainly in the N dev previews) So isn't it just crashing because you aren't capable of using Vulkan?

**Comment by roflcopter777** [comment]
Well that's bullshit, so now I have to update to some shitty OS with even worse performance. How was I supposed to know that?   Top that off with the fact that emulators will not only run worse, but that I've heard nothing but bad things about it, that MM is not emulator-friendly or battery efficient. Would've been nice if the Libretro Blog had that in a disclaimer stating that Vulkan was Marshmallow only.  Absolute bullshit.

**Comment by AlexFolland** [comment]
You can always use a previous version.  The fact is that this is not a RetroArch issue.

**Comment by roflcopter777** [comment]
The problem is that performance is not as good as it could be, i.e. I have rotten luck getting full speed on 5.1.1 despite having a K1 processor in said tablet, Snes9x has a lot of audio crackling on RetroArch 1.x.x, and I may as well update.  The things that worry are getting losing data, RetroArch running even slower and with more crackling audio on MM, the list goes on. Is the OS update truly worth it?

**Comment by fr500** [comment]
RetroArch is perfectly fine on lollipop as we established on the forum
thread. Just make sure to set the power policy accordingly

**Comment by roflcopter777** [comment]
@fr500  See, that is a good option (and admittedly, I almost forgot about it), the downside is that it comes at a cost at faster battery draining; would updating to 6.0.1 be a good alternative to take advantage of the Vulkan API though? Or is an OTA update not worth it for one app?
