### ISSUE TITLE
start + select exit

### ISSUE THREAD

**Issue by erfg12** [libretro/RetroArch#3239]
I have a PC with multiple SNES/NES/GENESIS controller ports. I plan on making this system able to run all kinds of roms. I have separate configuration files for all my controllers, but exiting is an issue on anything other than SNES.

In SNES I would do:
input_enable_hotkey_btn = "6"
input_exit_emulator_btn = "7"

But in NES it is:
input_enable_hotkey_btn = "2"
input_exit_emulator_btn = "3"

I tried making 2 configuration files with these defined, but the default.cfg file over takes these 2 configurations. I tried removing these 2 variables from the default.cfg but it makes a new configuration file become generated because these 2 lines are required.

**Comment by fr500** [comment]
If you have different pads then you should use autoconf profiles instead. These profiles allow the gamepads to be autoconfigured when connected.
