### ISSUE TITLE
All RetroAchievements listed as "Unlocked" even though they're not.

### ISSUE THREAD

**Issue by cityeyes** [libretro/RetroArch#3240]
In 1.3.6, all achievements in the core/achievements menu are showing up as unlocked, even if they're not. They do "unlock" properly and report to retroachievements, so it doesn't seem to have anything to do with how their status is submitted to the website.

At first, I updated from an older version and brought my config files over. In an effort to take out any possible variables, I also tried starting with a blank slate to the same result.

**Comment by fr500** [comment]
It's fixed on nighties already

**Comment by cityeyes** [comment]
Awesome, thanks! Sorry to bother you with the issue then, I'll move to the newest nightly.
