### ISSUE TITLE
Posibility Streaming Netplay

### ISSUE THREAD

**Issue by dan83sama** [libretro/RetroArch#3246]
I saw the previous https://github.com/libretro/RetroArch/issues/2486 , and I found a good idea.

https://openload.co/f/xSfoAfzNLBM/VID_20160719_165619.mp4
In this clip, retroarch is on the left, and player (mpchc) on right, down is tablet with windows10 and player mpchc.(sorry by low quality).

https://openload.co/f/qc814P32FxM/2016-07-19_16-21-03.mp4
In this clip as the previous video had low quality, I record desktop.

https://openload.co/f/BPGTQNslgR8/2016-07-19_17-49-45.mp4
and support web browser.

In android tried with mxplayer and works.
I tried it with ffmpeg+dshow and works too with desktop and pc games.

I'm sorry for my english xP.

**Comment by fr500** [comment]
No need to open another issue
