### ISSUE TITLE
(PS3) When closing a rom from quick menu RA v.1.3.6 comes back ps3 xmb

### ISSUE THREAD

**Issue by Ezio-PS** [libretro/RetroArch#3249]
Load a rom with a core (except gambatte, mednafen lynx, virtual-jaguar and maybe stella) on RA v.1.3.6 and press l2+r2 for quick menu, then try to close the rom from quick menu, RA get closed and it comes back ps3 xmb.

**Comment by twinaphex** [comment]
This issue should be fixed now. If not, reopen.
