### ISSUE TITLE
Emulation runs at very high speeds

### ISSUE THREAD

**Issue by JippC** [libretro/RetroArch#3251]
For all of the cores I tried to run on 1.3.6 (bsnes, Genesis Plus GX, mednafen) games run at really high rates. I have a 144hz monitor, and tried a lot of different settings (turning vsync on, setting the refresh rate to 60, turning on and off gpu sync) and nothing really worked. I was going to try Black Frame Insertion, except that it just makes the whole thing black for some reason (tried setting refresh rate to 60 while monitor was at 120hz)
Running 1.3.4 now, I was able to get mednafen to run fine on just the stock settings.
I have Win7 64bit and a BengQ XL2430T (144hz)

**Comment by RobLoach** [comment]
You may want to enable Audio sync.

**Comment by fr500** [comment]
This seems more like a configuration issue, feel free to discuss but since there hasn't been any activity I'm closing this
