### ISSUE TITLE
Black square icon bug on the main menu

### ISSUE THREAD

**Issue by Ezio-PS** [libretro/RetroArch#3259]
Loading RA v.1.3.6 on Windows and on PS3 (cex build), a black square icon bug is appearing on the main menu.

Below the black icon it's possible to read 'No playlist entry available', it seems a kind of 'cloned playlist'.

![bug](https://cloud.githubusercontent.com/assets/15854706/17076535/29bbbf04-50b5-11e6-8059-69cc4123f6d2.JPG)

**Comment by Axiphel** [comment]
It's because there is an empty file in the playlist directory.

**Comment by Ezio-PS** [comment]
On PS3 just now playlist doesn't work, but on Windows it works.

I just loaded a rom and get it in playlist column, but black icon is still there.

![screen2](https://cloud.githubusercontent.com/assets/15854706/17076589/44a018b4-50b6-11e6-8329-8446515b647b.JPG)


Maybe scanning content can solve it on Windows?

**Comment by twinaphex** [comment]
I think this issue should be fixed as of this commit - 

https://github.com/libretro/RetroArch/commit/7bfa254c67e79bf09f961193b59cb5a16ac5943a

Test it out on your end.

**Comment by micochops** [comment]
I can also confirm that this bug exists in the OS X port of RA (I'm using 1.3.6 on my El Capitan 10.11.6)
![screen shot 2016-07-23 at 8 34 57 pm](https://cloud.githubusercontent.com/assets/19629312/17077893/137047c8-5115-11e6-86bd-c7b624932b47.png)

**Comment by Ezio-PS** [comment]
I can confirm that the commit indicated by Twinaphex fixed the issue, well done.
