### ISSUE TITLE
[OS X RA 1.3.6] History Tab showing Main Menu Options

### ISSUE THREAD

**Issue by micochops** [libretro/RetroArch#3261]
Hello!

Would like to report this as a possible bug in the RA 1.3.6 OS X port.
When the History List is disabled (turned "Off") in the Playlists Settings tab, the History tab mirrors the options in the Main Menu tab.

Note: History playlist must be empty (for those trying to recreate this bug).

Please see screenshot below.

Thank you!
![screen shot 2016-07-23 at 8 46 43 pm](https://cloud.githubusercontent.com/assets/19629312/17077959/6f03b424-5117-11e6-92c2-c37fdf5cfb49.png)

**Comment by RobLoach** [comment]
To recreate...

1. Run RetroArch
2. Visit Settings -> Playlists, disable History List
3. Close RetroArch
4. `rm ~/.config/retroarch/content_history.lpl`
5. Run RetroArch, you'll then see the main menu in the history playlist

**Comment by Axiphel** [comment]
Happens on Windows too

**Comment by Awakened0** [comment]
Today's nightly includes a fix for this where it says "No history available." when you go to that tab with history disabled.

**Comment by twinaphex** [comment]
Yeah, this should be fixed now. Reopen in case it still happens with the latest source (but it shouldn't).

**Comment by dankcushions** [comment]
Fixed! However, should the icon + message "No history available" appear at all, when history is disabled? Seems like maybe the whole menu should be hidden?

**Comment by twinaphex** [comment]
This is the best we can do for now I think until the horizontal menu starts becoming more dynamic so we can add / remove items from it at will.
