### ISSUE TITLE
[Vulkan] Fast-Forward Screen Flickering

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#3268]
A few others mentioned this happening on NVidia hardware (https://github.com/libretro/RetroArch/issues/3005) and the same happens for me with a 970 on Win10 with the 368.39 drivers. @hizzlekizzle mentioned he thought he had it not working on his Radeon, so it might not be just an NVidia bug.

**Comment by AlexFolland** [comment]
I can confirm that this is true.  I have an Nvidia GTX 690 with the latest driver (368.81) and am using Win7-64.

**Comment by hizzlekizzle** [comment]
Yeah, I just checked it and vsync is always forced on my Radeon GPU.

**Comment by Themaister** [comment]
I don't think will be fixed until someone on Windows steps through and have a look at what's going on. I can't test anything on Windows these days.

**Comment by Awakened0** [comment]
I noticed it does work with anything in the WonderSwan core, or certain games like Gradius or Donkey Kong in MAME. I think that's just because those have Vsync disabled though.

**Comment by AlexFolland** [comment]
Still broken with latest Windows Nvidia driver (376.19).

**Comment by Awakened0** [comment]
This works after the latest commit by @Themaister, but is pretty wonky. The screen flickers when it's first enabled and everything's wavy when you move.

**Comment by JacobAL** [comment]
This seems to work for me as of 1.4

**Comment by fr500** [comment]
Afaik what's happening is that an old framebuffer flickers for a sec and then the real one draws on top.

**Comment by Awakened0** [comment]
With the newest nightly and driver 390.77, I no longer get a flicker when engaging fast forward in the Vulkan driver. However, after I let off the fast forward hold hotkey, sometimes the game starts running slowly. Sometimes I get horizontal black lines across the screen. It's like the sync gets messed up. Usually you only have to hit fast forward a few times for this to start happening. I've gotten it happening in Mesen and MAME so far. In MAME I get a small hitch when engaging and disengaging FF too (was testing Batsugun).

If swap interval is set to 2, when the game slows down I also get flickering. And the framebuffer seems to get weird; sometimes I get what looks like a copy of the screen running at native res in the top left corner. I tried to take a screenshot of this but it showed up normal.

**Comment by Awakened0** [comment]
If I launch content directly from RA instead of the command line, the hitch at the beginning and end of fast forwarding goes away. There also seem to be less issues when running at 60hz with swap interval 1. But even at that refresh the game still slows down, fast forward stops working and you get horizontal lines if you launched in fullscreen (borderless or true). 

I also found out it's consistent; fast forward always messes up on the fifth time I press the fast forward hold hotkey.

**Comment by twinaphex** [comment]
did this always happen?

can you try and see if this happens with threaded video mode? that one should not be reliant on 5he monitor refresh rate. i think that is what this is likely to be about - whenever you do a fullscreen or windowed toggle, it resets the monitor. refresh rate calculation and starts over from scratch.

**Comment by Awakened0** [comment]
I've had issues with fast forward in Vulkan since it was first implemented. The problems have changed slightly over time as I've updated my NVidia drivers and RetroArch. Some of my old comments in this thread describe some of the older behavior.

Turning on threaded video does fix the issues even when running at 120hz. Threaded video makes scrolling all stuttery though.

**Comment by Awakened0** [comment]
The Vulkan fast forward flickering was fixed with a workaround by @Themaister :D

**Comment by oryxcallotis** [comment]
Was this actually fixed? I've had it since forever on nVidia RTX 2070. Toggling 'f' to go to windowed and back to fullscreen fixes it until Retroarch is restarted though.

**Comment by Awakened0** [comment]
I still use Vulkan as my primary driver and launch in exclusive fullscreen. Haven't seen the flickering issue come back when fast forwarding. I haven't tested with Gsync and sync to exact content framerate off in awhile though, so maybe it happens with those off?

**Comment by AlexFolland** [comment]
Yes, this does seem to be fixed.  I've tested recently on Windows 7-64 with an Nvidia GTX 960 and the issue did not occur.
