### ISSUE TITLE
Feature Request: Cloud Sync

### ISSUE THREAD

**Issue by hazrpg** [libretro/RetroArch#3269]
I'm not sure if this has been asked already... but here we go.

I just thought, since RetroArch is multi-platform and interfaces with libretro... and libretro can be used not just for emulation but also for development of applications and games... that maybe cloud syncing/integration would be a great idea and beneficial for all! For example S3, Google Drive, Dropbox, (S)FTP, SSH, etc. That way you could select to save state to a remote directory and continue on a different device.

**Comment by fr500** [comment]
duplicate: https://github.com/libretro/RetroArch/issues/2028

**Comment by Axiphel** [comment]
Put your save folder into google drive and point Retroarch to it. Voila!
