### ISSUE TITLE
Minecraft (Craft Core) Crashes on Windows 10 Pro x64

### ISSUE THREAD

**Issue by jrbilodeau** [libretro/RetroArch#3271]
I installed retroarch 1.3.6 and installed the Minecraft core last night, but it crashes on windows 10 pro x64 when i try to load it.

I was however able to play it by setting compatability mode to windows 7 for retroarch

**Comment by RobLoach** [comment]
Confirmed on latest Linux....

```
...
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [GLX]: glXSwapInterval(1)
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR 
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "".
[1]    6834 floating point exception (core dumped)  retroarch --verbose
```

Should this issue live over at https://github.com/libretro/craft .
