### ISSUE TITLE
(Joypad autoconfig) Fails to autoconfig controllers properly when they are not the first usb device.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3274]
OS: `Slackware64-current`
`eudev-3.1.5-x86_64-8`
`RetroArch-1.3.6-x86_64-1_SBo`

When trying to autoconfigure a gamepad that is not the first usb device the created .cfg file will use the `input_device`, `input_vendor_id` and `input_product_id` of the first usb device (keyboard) while the input buttons will match the gamepad.

To work around this I have found I either need to swap the keyboard and gamepad temporarily or manually edit the .cfg file with the correct device name, vid and pid. Neither of these workarounds are all that ideal.

**Comment by fr500** [comment]
is it listing the keyboard as if it was a controller?
What input driver are you using?

**Comment by orbea** [comment]
In the RetroArch input configuration it will list and use the desired gamepad when it is selected in the `User Device Index` while this issue only occurs when trying to save an autoconfig file. Both the keyboard and gamepads are using udev (eudev).

**Comment by fr500** [comment]
It shouldn't list the kbd at all. It doesn't do so in the other drivers.

**Comment by orbea** [comment]
It has always defaulted to the keyboard for me with the udev input driver since at least `RetroArch-1.3.1` where I first started using RA.

**Comment by fr500** [comment]
hmmm... well that sucks, I thought the idea was to have the kbd as an always available device.
In windows I can use a Pad and the keyboard for user 1 at the same time

Maybe it detects some keyboards, not all of them?

**Comment by orbea** [comment]
Its a cheap generic microsoft keyboard, here is a default autoconfig file for it.
```
input_driver = "udev"
input_device = "Microsoft Wired Keyboard 600"
input_vendor_id = "1118"
input_product_id = "1872"
```

**Comment by fr500** [comment]
I can't reproduce this, on windows I  connected an unrecognized pad, I went to port 3 (which was the first available port that wasn't configured), Selected bind all and save autoconf. 

It saved the correct data.

**Comment by orbea** [comment]
My current hypotheses are that this is restricted to eudev and/or is a result of my keyboard being recognized as a gamepad. Unfortunately I do not have any other keyboards to test nor do I have any installs with systemd/udev to try.

**Comment by orbea** [comment]
As was discussed in #retroarch @ freenode this is rather an issue of when the `User Device Index`  has been changed from its default setting and then trying to save an autoconfig. Trying to make an autoconfig with user 2 where the desire gamepad is default will work as expected.

As RetroArch is designed with the intent of being like a console this works fine except for that sometimes keyboards will be recognized as gamepads when they shouldn't.

**Comment by orbea** [comment]
This is not really a bug, so I will close this and replace it with a new issue for the keyboard.
