### ISSUE TITLE
Random Freezing/Crashing on GBA Games (N3DS)

### ISSUE THREAD

**Issue by Olorin92** [libretro/RetroArch#3279]
This might be the wrong place to put this (could you redirect me to the correct repo if that is the case), but the gPSP emulator on Retroarch seems to experience random crashing/freezing while in game. This seems to only occur when Dynarec is enabled, so I'm led to believe it is an issue with this.

**Comment by fr500** [comment]
You really need to state your platform at the very least.
Most likely a gPSP issue anyhow

**Comment by Olorin92** [comment]
Sorry I'm on a n3DS using CFW through Luma 3DS (and yes, this is through gPSP)

**Comment by twinaphex** [comment]
This should be moved to the gPSP repo, it's not a RetroArch issue.

Oh and also, with only one guy developing for 3DS and this guy steadfastly ignoring us whenever we ask him to look at the 3DS port again, there is not much I can do here, sorry. I am not going to be spending my own money on a 3DS, sorry.

**Comment by Olorin92** [comment]
Sorry twinaphex, didn't see this last comment. I'd be happy to contribute (fully) to getting you up and running with a CFW 3DS IF it means gPSP on 3DS can be made stable. Just tell me what you need

**Comment by twinaphex** [comment]
Well, I need a CFW 3DS. gpSP can be looked at then among other things.

**Comment by Olorin92** [comment]
Out of curiosity, where is the code for gPSP (and more specifically the Dynarec implementation) located?

**Comment by twinaphex** [comment]
https://github.com/libretro/gpsp

**Comment by Olorin92** [comment]
Great thanks for that twinaphex. I might spend the weekend going over the code in there to wrap my head around it. Not saying I'll be any use by any means, but I have got programming experience, so if I'm lucky I might be able to understand some of it ;)

Out of curiosity, how does one debug a CIA? Or do you normally just dump messages out into a text file or something similar when hitting certain points?
