### ISSUE TITLE
Audio becomes distorted after 30 or so minutes of gameplay

### ISSUE THREAD

**Issue by Olorin92** [libretro/RetroArch#3280]
Using gPSP, the audio becomes distorted after around 30 minutes of gameplay, with the only way to fix it being to restart gPSP.

**Comment by Olorin92** [comment]
And this is on a n3DS running CFW through Luma 3DS

**Comment by twinaphex** [comment]
Sounds like a dynarec issue.

**Comment by FateForWindows** [comment]
The audio can become distorted in any core if you put the console in sleep mode.

**Comment by orbea** [comment]
@FateForWindows Is this still a problem? Are other cores affected?

**Comment by FateForWindows** [comment]
> @FateForWindows Is this still a problem? Are other cores affected?

Only with csnd. DSP doesn't seem to be affected at all.
