### ISSUE TITLE
Emulating three controllers on one system (two for O3DS/2DS)

### ISSUE THREAD

**Issue by RocketRobz** [libretro/RetroArch#3284]
With input redirecting to PC (with controller) possible, it would be nice if RetroArch for 3DS could support emulating three controllers (two for O3DS/2DS). Just set Max Users to 3 (or 2) in Input Settings for it to work.

For example, when emulating NES games, the controls follow:
2P D-Pad = Circle Pad
2P A button = X button
2P B button = Y button
2P Start button = L button
2P Select button = R button

The input redirection program will redirect the 3DS inputs to three or two controllers connected to a PC.

**Comment by fr500** [comment]
I don't think this would be implemented, it's way too impractical and cumbersome...
Tagging as won't fix for now

**Comment by hizzlekizzle** [comment]
This appears to be fixed by #10488 . closing
