### ISSUE TITLE
Hotkeys in both keyboard and controller

### ISSUE THREAD

**Issue by NelsonRosenberg** [libretro/RetroArch#3285]
When I configure my controller to use hotkeys with, for example:

input_enable_hotkey_btn = "8"
input_menu_toggle_btn = "9"
input_load_state_btn = "5"
input_save_state_btn = "3"

The keys in my keyboard that serve the same function (F4, for load state, for example) stop working unless I press the controller hotkey.
 
I think the hotkeys from controller shouldn't affect those from keyboard so maybe that is an issue?

**Comment by fr500** [comment]
It's a global setting, to work around it set a hotkey enable keyboard key too, then you can do ctrl-f4 or whatever.

Not really a bug, it's working as designed, RA treats all devices equally

**Comment by NelsonRosenberg** [comment]
I guess there is no intention to make the keyboard behave diferently then?

Alright, thanks for the info!
