### ISSUE TITLE
Emscripten cant compile

### ISSUE THREAD

**Issue by jcampbell05** [libretro/RetroArch#3286]
I am getting this error
ERROR:root:libretro_emscripten.bc: No such file or directory ("libretro_emscripten.bc" was expected to be an input file, based on the commandline arguments provided)

**Comment by Alcaro** [comment]
Emscripten (and most console ports, and some other platforms) can't load cores dynamically; the binary will contain both RetroArch and a core of your choosing.

For these platforms, the core must be compiled before RetroArch, and placed so our build scripts can find it.

Looks like you forgot this step (or we forgot that step in the manual). The error tells you where to put the core.

**Comment by jcampbell05** [comment]
@Alcaro Okay just so I understand - A libRetro.js file can only be compiled as a single backend and a single frontend due to technical limitations.

In order to fix this I need to compile the particular backend I need before I compile the frontend which pulls it in (In this case RetroArch).

I notice RetroArch has the cores as a sub-folder, how do I go about telling it to compile one of the cores ? 

If I can get this to work then I will have a few PRs ready to get this working :)
