### ISSUE TITLE
(Menu) Add more Help messages

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#3288]
We still need help messages for some of these settings -

Configuration -> Use per-game core options if available

Configuration -> Load Override files automatically

Configuration - Load Remap files automatically

Saving - Sort Saves In Folders

Saving  -> Sort Savestates in folders

Frame Throttle -> Throttle Menu Framerate

Onscreen Display -> OSD Message Font

**Comment by fr500** [comment]
Configuration -> Use per-game core options if available --- I guess for uniformity we should make this one "Load Content core options automatically"
Load content specific core options automatically if found

Configuration -> Load Override files automatically
Load override configurations automatically if found

Configuration - Load Remap files automatically
Load input remapping files automatically if found

Saving - Sort Saves In Folders
Sort save files in folders named after the core used

Saving -> Sort Savestates in folders
Sort save states in folders named after the core used

Frame Throttle -> Throttle Menu Framerate
Not sure?

Onscreen Display -> OSD Message Font
Changes the font that is used in the OSD

**Comment by Axiphel** [comment]
I think "Load Content core options automatically" would read better as "Load Content specific core options automatically". The former doesn't really get across that the option is for per-game(content) core options, I feel.

And for:
Frame Throttle -> Throttle Menu Framerate
Keeps menu from running too fast?

**Comment by twinaphex** [comment]
OK, I implemented these messages now.

The next entries for which we're missing help messages:

Onscreen Overlay -> Autoload Preferred Overlay

**Comment by RobLoach** [comment]
I believe we have sublabels for the majority of these now?

**Comment by hizzlekizzle** [comment]
we have sublabels for pretty much everything now. closing.
