### ISSUE TITLE
Retroarch Emscripten Freezes

### ISSUE THREAD

**Issue by jcampbell05** [libretro/RetroArch#3291]
I have this log in the html and the canvas doesn't let me use the menu moving cursors etc.

```
RetroArch [INFO] :: === Build =======================================
Capabilities: 
Built: Jul 30 2016
RetroArch [INFO] :: Version: 1.3.6
RetroArch [INFO] :: Git: 6932d20
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Looking for config in: "/home/web_user/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Looking for config in: "/home/web_user/.retroarch.cfg".
RetroArch [WARN] :: Config: using skeleton config "/etc/retroarch.cfg" as base for a new config file.
RetroArch [WARN] :: Config: Created new config file in: "/home/web_user/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Config: loading config from: /home/web_user/.config/retroarch/retroarch.cfg.
RetroArch [WARN] :: Active core path not set, cannot load core-specific config file...
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29975.00 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0xf234.
RetroArch [INFO] :: [EMSCRIPTEN/EGL]: Dimensions: 800x600
RetroArch [INFO] :: Found GL context: emscripten
RetroArch [INFO] :: Detecting screen resolution 800x600.
RetroArch [INFO] :: [GL]: Vendor: WebKit, Renderer: WebKit WebGL.
RetroArch [INFO] :: [GL]: Version: WebGL 1.0 (OpenGL ES 2.0 Chromium).
bad name in getProcAddress: glDebugMessageControlKHR,glDebugMessageControlKHR
bad name in getProcAddress: glDebugMessageInsertKHR,glDebugMessageInsertKHR
bad name in getProcAddress: glDebugMessageCallbackKHR,glDebugMessageCallbackKHR
bad name in getProcAddress: glGetDebugMessageLogKHR,glGetDebugMessageLogKHR
bad name in getProcAddress: glPushDebugGroupKHR,glPushDebugGroupKHR
bad name in getProcAddress: glPopDebugGroupKHR,glPopDebugGroupKHR
bad name in getProcAddress: glObjectLabelKHR,glObjectLabelKHR
bad name in getProcAddress: glGetObjectLabelKHR,glGetObjectLabelKHR
bad name in getProcAddress: glObjectPtrLabelKHR,glObjectPtrLabelKHR
bad name in getProcAddress: glGetObjectPtrLabelKHR,glGetObjectPtrLabelKHR
bad name in getProcAddress: glGetPointervKHR,glGetPointervKHR
bad name in getProcAddress: glEGLImageTargetTexture2DOES,glEGLImageTargetTexture2D
bad name in getProcAddress: glEGLImageTargetRenderbufferStorageOES,glEGLImageTargetRenderbufferStorage
bad name in getProcAddress: glGetProgramBinaryOES,glGetProgramBinary
bad name in getProcAddress: glProgramBinaryOES,glProgramBinary
bad name in getProcAddress: glMapBufferOES,glMapBuffer
bad name in getProcAddress: glUnmapBufferOES,glUnmapBuffer
bad name in getProcAddress: glGetBufferPointervOES,glGetBufferPointerv
bad name in getProcAddress: glTexImage3DOES,glTexImage3D
bad name in getProcAddress: glTexSubImage3DOES,glTexSubImage3D
bad name in getProcAddress: glCopyTexSubImage3DOES,glCopyTexSubImage3D
bad name in getProcAddress: glCompressedTexImage3DOES,glCompressedTexImage3D
bad name in getProcAddress: glCompressedTexSubImage3DOES,glCompressedTexSubImage3D
bad name in getProcAddress: glFramebufferTexture3DOES,glFramebufferTexture3D
bad name in getProcAddress: glIsVertexArrayOES,glIsVertexArray
RetroArch [INFO] :: Querying GL extension: ARB_texture_non_power_of_two => doesn't exist
RetroArch [INFO] :: Querying GL extension: OES_texture_npot => doesn't exist
RetroArch [INFO] :: Querying GL extension: BGRA8888 => doesn't exist
RetroArch [WARN] :: [GL]: GLES implementation does not have BGRA8888 extension.
32-bit path will require conversion.
RetroArch [INFO] :: Querying GL extension: GL_EXT_unpack_subimage => doesn't exist
RetroArch [INFO] :: Querying GL extension: EXT_sRGB => exists
RetroArch [INFO] :: GL: Using resolution 800x600
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Using font rendering backend: bitmap.
RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [ERROR] :: Cannot resolve application path! This should not happen.RetroArch [INFO] :: Saved new config to "/home/web_user/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: null: [/home/web_user/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: [GL]: VSync => off
Looks like you are rendering without using requestAnimationFrame for the main loop. You should use 0 for the frame rate in emscripten_set_main_loop in order to use requestAnimationFrame, as that can greatly improve your frame rates!
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: Querying GL extension: ARB_framebuffer_object => doesn't exist
```

**Comment by fr500** [comment]
it's not frozen, input isn't working.

**Comment by jcampbell05** [comment]
@fr500 does anyone know the input is broken and what could I do to fix it ?

**Comment by jcampbell05** [comment]
@fr500 cool, so I really want to help fix this. Is there any places you can point me to ? Where in the code is the input handled ? Which areas do you think could effect it ?

**Comment by fr500** [comment]
I think it's here:
https://github.com/libretro/RetroArch/blob/master/input/drivers/rwebinput_input.c

**Comment by jcampbell05** [comment]
@fr500 did some experimenting with inserting alerts into the library_webinput.js file in the `RWebInputInit` method to check if the events for key presses are registered.

It appears from my initial experimentation that this method is never called:
https://github.com/libretro/RetroArch/blob/master/emscripten/library_rwebinput.js#L96

**Comment by jcampbell05** [comment]
So I've found emscripten now has native bindings for the key methods which I am going to use instead

http://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html#how-to-use-this-api

**Comment by dalter** [comment]
Compile with SDL2 support on last Emscripten 1.3.6
in RetroArch setting set sdl2 input driver

**Comment by jcampbell05** [comment]
@dalter Cool so use SDL instead of RWebInput ?

**Comment by dalter** [comment]
I fixed RWebInput and add to Makefile.emscripten SDL2 flags.
Now input SDL2 and RWebInput work fine
But need more test with SDL2 !

**Comment by fr500** [comment]
Cool stuff gonna try today.
@dalter have you looked into implementing gamepad support by any chance?
https://kripken.github.io/emscripten-site/docs/api_reference/html5.h.html#gamepad

**Comment by dalter** [comment]
@fr500 not traing add gamepad support with RWebInput.
But SDL2 alredy have html5 support and gamepads working , but onli Xbox 360 and PS3 (ps3 with xbox emuletion set) in google Chrome and Chromium (all webkit browsers).
My older gampad "logitech rumbel pad 2" work not properly in chrome (all webkit browsers), miss some buttoms.
Hi works properly only in Firefox

**Comment by jcampbell05** [comment]
@dalter  Do you have a version with these fixes I can use ?

**Comment by fr500** [comment]
Doesn't seem to work here
http://hastebin.com/ripahuyoge.coffee

**Comment by jcampbell05** [comment]
Compiling with SDL2 doesn't work for me either, it seems for me that the event callbacks aren't being allowed to be fired by RetroArch therefore no input can be processed.

**Comment by dalter** [comment]
You are using the latest version of emscipten 1.36.5?
you add the flag -s USE_SDL = 2 LDFLAGS:?
emscripten must load a necessary library SDL2 himself when to begin compiling js.

Here is a working example (SDL2 and Rwebinput): http://game-gear.ru/retroarch/RetroArch.html 

What erorrs compilation c using SDL2?

RetroArch starts and runs in the menu control both SDL2 and c Rwebinput but after loading the kernel emulator freezes
I checked the assembly without my fix when launching rom RetroArch start and it also hangs .
I think that the problem in EGL
I test my fix an old version RetroArch 1.3.2 emulator and worked fine

**Comment by jcampbell05** [comment]
@dalter Compiling with SDL2 enabled with RWebInput still doesn't fix input for me. This is on Chrome and on the latest `master` of RetroArch.

When trying to fix this by modifying the code, I used the native emscripten bindings rather than RWeb and the callbacks weren't being fired.

**Comment by r-type** [comment]
Working at least for me for testcore ,with RWebInput ,Last RetroArch (1 day ago) and last Emscripten .

I have input in menu and no freeze using
```
arguments: ["-v",""],
```
instead of 
```
arguments: ["-v", "--menu"],
```
in the html file.

![retrojs](https://cloud.githubusercontent.com/assets/3614417/17280538/2cdfb94a-5792-11e6-9a44-9d5a4400c2f0.png)

**Comment by fr500** [comment]
Ok, input is working now but it's hanging at startup unless we change audio driver from rwebaudio to null

**Comment by r-type** [comment]
Yes sound to null fix the freeze pb .
BTW if you launch game directly instead to boot to --menu (without change audio to null)  ,it works also as expected (but no sound too).

![screen](https://cloud.githubusercontent.com/assets/3614417/17322781/7f2f4ce8-589f-11e6-981f-723f38052498.png)

**Comment by jcampbell05** [comment]
Tried compiling and I just got an exception.

**Comment by r-type** [comment]
Using SDL2 for sound 
```
config += "audio_driver = sdl2\n";
```
also solve the freeze pb at start , but have no sound in game after

**Comment by r-type** [comment]
Any chance sound ingame and freeze at start get fixed ?
here a cap32 sample core http://dl.free.fr/vvif5yR4L

**Comment by dalter** [comment]
@r-type I fix audio driver and now all work fine !! (all fix in master)

**Comment by r-type** [comment]
Nice, thanks !
sound now play fine for me (at least for cap32).
and no freeze when launch with  --menu .

on side note , i notice that close content works but freeze if reload another content.

**Comment by fr500** [comment]
Been working on a little something
http://190.130.222.178:9080/emscripten/webplayer.html

Data should persist across sessions (start retroarch first, upload second) and settings should be retained (use save current config)

**Comment by r-type** [comment]
@fr500 nice it's cool to have persistence, 
I’m not familiar with js so could you explain , did you use NODE FS ? where a the file locally ?

Actually i build with  --preload-file to embedded some data need for emulators ,
like data/ folder for vice C64 . ( result is 2 files .js with .data ) but it's restrictive and tedious .
So i would be happy if i can easily have persistent files (data,ra config/coreoptions...).

on side note ,i finally success to build a vice C64 without using libco , so after it was easy to build an rough emscripten version .

![vice](https://cloud.githubusercontent.com/assets/3614417/17370390/2cdf8914-599c-11e6-906e-e43b007bbf70.png)

 http://dl.free.fr/fs0WErjaz

**Comment by fr500** [comment]
@r-type I used a browser based filesystem (browserfs) it has several backends. I'm only using local storage (browser cache) atm but it has backends for dropbox and others.

I commited the changes to master already but you probably need the memory map files from here: https://github.com/jvilk/BrowserFS/releases/tag/v0.5.12

**Comment by r-type** [comment]
@fr500  thanks for the explanation and link , I'll look at .
for the record i never keep cache or anything in my browser!

BTW your idea to fetch at startup look really nice !

**Comment by fr500** [comment]
@r-type well I plan to add the dropbox backend too, but if you don't save browser cache I reckon you don't use dropbox either.

**Comment by fr500** [comment]
I added some rudimentary dropbox support
https://buildbot.libretro.com/.radius/webplayer.html
https://www.youtube.com/watch?v=nNMbIRE2HBI

**Comment by RobLoach** [comment]
This is coming along pretty nicely! Unfortunately did not work here, with or without Dropbox. Likely something I'm doing wrong on my end.

**Comment by fr500** [comment]
@RobLoach it's still quite fragile, maybe you hit the buttons in the wrong order.
For local storage:
- Start Retroarch
- Upload

For dropbox:
- Use Dropbox
- Start RetroArch
- Upload (or copy to your dropbox/apps/retroarch web player/web_user/content)

Also, load archive with core causes this port to crash. The zip code seems wrong, it creates a 0 byte file.

@All, this is working nicely but I have a weird issue maybe someone here can help me with.
Now that we have a persistent configuration I have discovered that vsync and hotkey input die on firefox after the first run.

I messed with the config a lot, ordered the config alphabetically and then I discovered that removing the line:
aspect_ratio_index = "21" 

tested about 10 times readding/removing the line and the same happened, made no sense but at least I knew which setting caused the issue.
but then I decided to try again from scratch, reproduced, removed the line (without sorting the file) and... nothing, it didn't help.

I checked the template: https://github.com/libretro/RetroArch/blob/master/emscripten/webplayer.html#L201

And noticed the first entry is still at the first line of the config, so I removed that one
And it got fixed again.

Tried removing that from the template, but then the culprit became audio_latency

Soo, I'm wondering if there is something wrong with the way I'm creating the base config.
I guess I'll have to add these defaults to the platform driver instead (which would be good regardless) but the issue confuses me a lot.

Maybe some hidden character or something... I really don't understand.

BTW: the issue doesn't appear on chrome.

**Comment by fr500** [comment]
feel free to mantain the discussion.

**Comment by RobLoach** [comment]
@fr500 

> it's still quite fragile, maybe you hit the buttons in the wrong order.
For local storage:
- Start Retroarch
- Upload

That did it. Worked with Kirby, wasted 10 minutes playing and I want my 10 minutes back. I do love the music though.

> I checked the template

Being a web developer/designer, I can assist with improving this template. Not sure how far you want to go with the emscripten webplayer template shipped with RetroArch though. We could turn this into a really slick web application, with file management and everything.

**Comment by fr500** [comment]
Well I wouldn't want to overdo it, I want to keep it a single file at least so people bundling it in their sites don't have to go hunting for too many deps.
After all you can manage the files via the dropbox app and they have some drop-in upload/download widget IIRC.

That said, I'm not against making it better, here's the list of things I'd like
- Make it nice... it's horrible now
- Hide the console, maybe we can make it an accordion or something collapsible and eliminate all the checkboxes once the platform driver can set defaults correctly
- Loading takes a while, not too much with gambatte but it does with other cores like fba, so having a circle progress overlaid on top of the canvas area while it downloads the core would be nice
- Syncing dropbox takes a while too, so the same...
- I'd like the canvas area to be like this: https://archive.org/details/msdos_Oregon_Trail_The_1990 or this https://endrift.github.io/gbajs/ (but better ofc!)

Instead of the power button overlaid on top it should have a libretro logo or an invader
- Have fullscreen, mute, and other buttons laid out on top of the image like on the Internet Archive page
