### ISSUE TITLE
JIT (dynarec) on IOS 9.3.3

### ISSUE THREAD

**Issue by hotyute** [libretro/RetroArch#3292]
With the new Pangu Jailbreak, isnt dynarec supposed to worked with iOS 64 bit devices? I'm not sure if I'm the only one experiencing this issue, but dynarec doesn't work on any apps for me.

**Comment by Fadi5555** [comment]
Whe hope we could do anything to implement JIT on jailbroken 64-bit devices.

**Comment by fr500** [comment]
hmmm the dynarecs themselves are parts of the cores, not RetroArch. As such the issue doesn't belong here.
