### ISSUE TITLE
Android - v1.3.6 from Google Play Store - Stuck at menu screen

### ISSUE THREAD

**Issue by tomgar** [libretro/RetroArch#3295]
Motorola Moto G 2
Android 6.0

It downloads the assets, uncompresses base.apk and then I can't interact with the menu. It's not responding to touch events:

![screenshot_20160731-150754](https://cloud.githubusercontent.com/assets/3766148/17277024/f1d7f67a-5730-11e6-8868-7bbdc25199dd.png)

**Comment by twinaphex** [comment]
We don't have a Moto G2. We have got numerous reports that there is an issue with Moto G2 but unfortunately with no developer onboard who owns it, we don't know what the problem is or how to fix it.

**Comment by PalebloodSky** [comment]
The same thing happened when I installed it on my OUYA (my old, but not quite forgotten Android 4.1.2 box). I plugged a USB keyboard in and had to go in and manually bind all my PS3 controller buttons, then it worked fine. So it wasn't frozen, just nothing responded but the keyboard. Give that a try.

**Comment by tomgar** [comment]
You're right, @PalebloodSky . After connecting a keyboard to my Moto G2 I can drive the menu with it. 

I was inspecting the code to see if I can help, but I saw that it's a bit complex :). 

In the logcat, it says: "RetroArch: Found joypad driver: "android", so I guess the problem is that the touchscreen isn't detected... I think that responsibility resides in (or part of) input/drivers/android_input.c, at least.

I managed to compile Retroarch for Android in my system and I'm willing to help the one who wrote the Android input system for Retroarch to pinpoint what the problem is and fix the bug, if you want to.

**Comment by fr500** [comment]
Duplicate: https://github.com/libretro/RetroArch/issues/3003

**Comment by r2rangel** [comment]
Well, I´m a Total noob on coding, but i have a Moto G2, Thea, with retroarch installed, touch does not work at all, but joystick works, i have sixaxes app installed and a ps3 pad, works fine, is not frozen on menu, I actually got to play around a bit, it wont read the external SD card, i guess is a permission issue ? not sure, but i know is OS related, but yeah works with a Joystick. I have no clue on how i can help, if someone could guide me i could send info on this, i have CM 14 installed on my Moto G2 - xt1078(Thea).
