### ISSUE TITLE
Video playback crashes with recent NVIDIA drivers

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/RetroArch#3313]
Any NVIDIA driver that's more recent than 359.00 or 359.06 will cause video playback to crash after 10-15 seconds. Sometimes instead of crashing, the top stripe of the screen freezes and the bottom 2/3 of the video continue to play.

The problem persists in all video driver modes. It also persists even if you change the video driver from "ffmpeg" to "null".

**Comment by Tasosgemah** [comment]
Problem still persists with the latest drivers (372.54)

**Comment by Tasosgemah** [comment]
Video playback still crashes on 372.70

**Comment by jvook** [comment]
Works with Vulkan driver

**Comment by twinaphex** [comment]
This should be fixed now with the GL driver. Can you try it again @Tasosgemah ?

**Comment by Tasosgemah** [comment]
I tried it with the latest nightly using GL, it now works for me too.

**Comment by twinaphex** [comment]
See this commit - 

https://github.com/libretro/FFmpeg/commit/e7e77116f6306993d710cd978e2175ccde2c9052

**Comment by Tasosgemah** [comment]
Thank you.
