### ISSUE TITLE
DRM Driver on RPi can't disable bilinear filtering or use overlays/shaders.

### ISSUE THREAD

**Issue by Heffer-Wolfe** [libretro/RetroArch#3325]
Can't disable bilinear filtering and doesn't support overlays or shaders when using the DRM driver on Raspberry Pi.

Edit:  Also seems to possibly have a memory leak or something when in rgui.  Games play fine for extended periods but when in the rgui after just 15-30 seconds it starts locking up.

**Comment by gizmo98** [comment]
Is this still an issue?

**Comment by orbea** [comment]
Given the lack of recent activity or feedback I am going to close this, please respond if this is still an issue.
