### ISSUE TITLE
Question about retroarch (vita port)

### ISSUE THREAD

**Issue by Fadi5555** [libretro/RetroArch#3331]
hi there. First of all I want to thanks developers who created HENkaku on vita. This makes porting hombrews and emulators much easier than rejuvenate hack.
So my question is:
Can you please add psx core (pcsx reARMed) on vita version. The best part is the HENkaku is now support JIT (dynarec) which is extremely important to enhancing emulators speed. So you have to implement (adding) dynarec on your project code of vita version of retroarch.

That's all. Thanks for your hard works. We really appreciate.

**Comment by Fadi5555** [comment]
any answer please?

**Comment by twinaphex** [comment]
not ready yet.

**Comment by fr500** [comment]
Core requests don't belong in the issue tracker
