### ISSUE TITLE
Auto Save Not Working When Exiting Retroarch From a Game

### ISSUE THREAD

**Issue by Dagnillo** [libretro/RetroArch#3335]
I'm running Retroarch on a Shield Android TV.  I have a hotkey set to exit Retroarch.  When I exit from within a loaded game/ROM, that game does not automatically save state as it would when closing the game only.  This happens independently of cores.

**Comment by bparker06** [comment]
This should be fixed now, if there's no objections can we close the issue?

**Comment by Dagnillo** [comment]
Thanks guys.
