### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3336]
The emscripten port has improved a lot, you can sample it here:
https://github.com/libretro/RetroArch/blob/master/emscripten/webplayer.html#L201

It's still quite fragile, you need to hit the buttons in the correct order.
For local storage:
-    Start Retroarch
-    Upload

For dropbox:

 -   Use Dropbox
 -   Start RetroArch
-    Upload (or copy to your dropbox/apps/retroarch web player/web_user/content)

As for the issues:

Issue 1:
- Load archive with core causes this port to crash. The zip code seems wrong, it creates a 0 byte file.

Issue 2:

This is a baffling one.
Now that we have a persistent configuration I have discovered that vsync and hotkey input die on firefox after the first run.

I messed with the config a lot, ordered the config alphabetically and then I discovered that removing the line:
aspect_ratio_index = "21"

tested about 10 times readding/removing the line and the same happened, made no sense but at least I knew which setting caused the issue.
but then I decided to try again from scratch, reproduced, removed the line (without sorting the file) and... nothing, it didn't help.

I checked the template: https://github.com/libretro/RetroArch/blob/master/emscripten/webplayer.html#L201

And noticed the first entry is still at the first line of the config, so I removed that one
And it got fixed again.

Tried removing that from the template, but then the culprit became audio_latency

Soo, I'm wondering if there is something wrong with the way I'm creating the base config.
I guess we'll have to add these defaults to the platform driver instead (which would be good regardless) but the issue confuses me a lot.

Maybe some hidden character or some encoding issue or something like that... I really don't understand.

BTW: the issue doesn't appear on chrome.

@twinaphex can you help me by making the platform driver set these defaults instead of relying in an autogenerated file:

https://github.com/libretro/RetroArch/blob/master/emscripten/webplayer.html#L201

**Comment by fr500** [comment]
@RobLoach said he would like to help with the js side of things, reposting this here so it doesn't get lost

I want to keep it a single file at least so people bundling it in their sites don't have to go hunting for too many deps.
After all you can manage the files via the dropbox app and they have some drop-in upload/download widget IIRC.

That said, I'm not against making it better, here's the list of things I'd like

- Make it nice... it's horrible now
- Hide the console, maybe we can make it an accordion or something collapsible and eliminate all the checkboxes once the platform driver can set defaults correctly
- Loading takes a while, not too much with gambatte but it does with other cores like fba, so having a circle progress overlaid on top of the canvas area while it downloads the core would be nice
- Syncing dropbox takes a while too, so the same...
- I'd like the canvas area to be like this: https://archive.org/details/msdos_Oregon_Trail_The_1990 or this https://endrift.github.io/gbajs/ (but better ofc!)

Instead of the power button overlaid on top it should have a libretro logo or an invader

- Have fullscreen, mute, and other buttons laid out on top of the image like on the Internet Archive page

So if you can help with any of these I'd appreciate it, I want to keep working on the filesystem stuff (I want roms to be volatile, only userdata to be persistent)

**Comment by RobLoach** [comment]
Thanks for the ping in this issue. With the bundled emscripten webplayer, we should keep it as simple as possible. A nice basic example of how to use it in the browser.

Once that's up, we could build a new one in its own repo, complete with all the bells and whistles. Bring dependencies in with npm, compile all the CSS, etc.

**Comment by fr500** [comment]
@RobLoach https://bot.libretro.com/web/ it's out now
Now we need a way to change the core, now it's only loading gambatte since it's hardcoded in the html

**Comment by twinaphex** [comment]
I guess we can close this issue now?

**Comment by RobLoach** [comment]
:+1:
