### ISSUE TITLE
Snes Savestate doesn't work.

### ISSUE THREAD

**Issue by Liger0** [libretro/RetroArch#3340]
Hi, I use a New 3ds (11.0). Nes emulators work perfectly, but Snes doesn't work really well.
Using Snes9x, It doesn't do savestates, because it permanently crashes.
Using Pocket Snes, It crashes for some seconds but then it does save states: It works but it is very annoying, because in Nes emulator (QuickNES) there isn't any delay doing save states so it would be wonderful if Poket Snes did the same. 
Another thing is that snes emulator doesn't load the last savestate at the start of the game, when Nes emulator does it.
I also noticed Pocket Snes isn't added in the Core Software Library http://wiki.libretro.com/index.php?title=Main_Page

**Comment by RobLoach** [comment]
I believe PocketSNES is https://github.com/libretro/snes9x2002 
http://wiki.libretro.com/index.php?title=Snes9x_2002

**Comment by twinaphex** [comment]
PocketSNES has been renamed to Snes9x 2002 now, which is a more accurate description of what it really is.

**Comment by Liger0** [comment]
Oh, thanks. Anyway I hope that Snes9x, and the auto loading savestate feature will be fixed; also, with pocketsnes, sometimes I do savestates, the app crash and I only can switch off the console. Then in the 3.1.6 release there isn't any resolution and aspect ratio settings, I'll wait these will be added.
At the end, can you tell me what are the other emulator with different names?
Like PocketSNES is Snes9x 2002, but what are 2005 and 2010?
Thanks, and I want to say to the developers: good work. :)

**Comment by Alcaro** [comment]
2005 is catsfc, 2010 is snes9x-next.

**Comment by fr500** [comment]
Please open the issue in the respective repository
