### ISSUE TITLE
GLSL shader regression

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#3342]
A lot of shaders fail to convert to GLSL.

A good example is xbr-mlv4-pass4.cg

I bisected RetroArch and the guilty commit is f272431b5d7b79f391567f2b04201874d9891a8b

@erbridge do you have any idea of what can cause this?

**Comment by erbridge** [comment]
Hrmmm. I'm not sure. Those changes should have been pretty innocuous. The most likely candidate is the refactoring of `fix_samplers` out of `hack_source_vertex` and `hack_source_fragment`. I'll take a look, when I get a chance.
