### ISSUE TITLE
Ios prboom unable to save game

### ISSUE THREAD

**Issue by voji** [libretro/RetroArch#3343]
I using the latest retroarch (1.3.6) on ipad air 2 with jailbreaked ios 8.4. Prboom core updated with online updater, and official doom 1 wad added (steam version). When i want to save game, doom says: failed to save game.

I using the default save game dir: var/mobile/Documents/RetroArch/saves

I think this problem isn't a permission issue, because other cores can create saved games there (for example gba game saves)

**Comment by fr500** [comment]
prBoom doesn't save using the SRM interface, it saves with the content so it's most likely a permissions issue.

**Comment by voji** [comment]
I modified the folder permission containing the wad files, and prBoom can create save game files there. Thank you the information, it's a permission issue.
