### ISSUE TITLE
Retrolink SNES adapter not recognized at all

### ISSUE THREAD

**Issue by sjdeal** [libretro/RetroArch#3346]
I am on a Raspberry Pi 2 B+ and have not been able to get RetroArch to recognize controllers with my RetroLink SNES adapter. It shows up in `/dev/input` as `js0` and `js1` (It has two inputs, so that's expected) and I can read the inputs correctly using `jstest`. I can even use the controller when navigating the RetroPie config menus. However, RetroArch doesn't even show the standard 'controller not configured' blurb when booting up, and it doesn't show up in the Input menu. I have used it successfully on my PC, though not through RetroArch. 

Apologies if this isn't the place to post this, but I haven't been able to find anyone else with this problem and I'd like to avoid buying another adapter if possible. I've read in several places that this adapter doesn't work well with the Pi, but most of the issues I've seen regard up and left not working. I've tried doing [this fix](https://github.com/retuxx/hid-retrobit) but it didn't do any good. The fact that `jstest` can see it makes me think it should be possible, but I don't know enough about input drivers and how RetroArch configures controllers to fix it on my own. I'd greatly appreciate any help; let me know if you need more information.

**Comment by fr500** [comment]
What input driver are you using?

**Comment by fr500** [comment]
No further information... 
Closing
