### ISSUE TITLE
Windows - Pitfall - Mayan Adventure not working with Genesis Plus GX 

### ISSUE THREAD

**Issue by shinra358** [libretro/RetroArch#3351]
Pitfall - Mayan Adventure not working with Genesis Plus GX 1.7.4

**Comment by Axiphel** [comment]
Works for me.

**Comment by shinra358** [comment]
Well, doesn't for me. Obvioiusly. Do I need all 3 bioses or can I just use the USA one? Any kind of setting that would make the game not work. Something else to add?

**Comment by Axiphel** [comment]
I'm going to assume you're talking about the Sega CD version because you mentioned bioses. How exactly doesn't the game work for you? Crash? Black screen?

**Comment by shinra358** [comment]
Yes, I do mean the sega cd version. Just a black screen for me. It works with the other emu. Just not with this one. I would like to use just 1 emu.

**Comment by saftle** [comment]
Once you've loaded up a core, go to the Information, and then Core Information. It will show you what bios files are necessary and how the files have to be named in order to load content. In this case, Sega CD needs a US, EU, and JP Sega CD bios file in the System directory.

**Comment by shinra358** [comment]
K, did that but it still has a black screen for that game.

**Comment by saftle** [comment]
Have you played other Sega CD games successfully, and within the same region?

**Comment by fr500** [comment]
This is clearly not a retroarch issue but a configuration/roms issue, feel free to discuss but I'm closing it

**Comment by shinra358** [comment]
That's the only game I have for that system and it works just fine with the pico core.

**Comment by saftle** [comment]
It's possible that picodrive is expecting different labeled Sega CD bios files, which is why it might work with Picodrive. In the Core Information, I'd double check to see if your bios files match up.

**Comment by shinra358** [comment]
They state the same bios files.
