### ISSUE TITLE
Vulkan Backend Crashes RetroArch on Game Scan and Custom XMB Platforms

### ISSUE THREAD

**Issue by shinra358** [libretro/RetroArch#3353]
With Genesis Plus gX, Sega CD games cannot be viewed in the xmb list in its respective category.

**Comment by markwkidd** [comment]
There is no DAT file yet in RetroArch's database for Sega CD. Redump images should work.

**Comment by markwkidd** [comment]
I logged an issue in the database tracker. Please feel free to hop over to this one: https://github.com/libretro/libretro-database/issues/232

**Comment by shinra358** [comment]
![clipboard01g5](https://cloud.githubusercontent.com/assets/3978291/17466201/526076c8-5cd8-11e6-9c95-d8481d6f1790.jpg)

Got this error when I tried to do that. This is what I made in a Sega - CD.lpl file:

`.\Games\SegaCD Games\Ecco - The Tides of Time\Ecco - The Tides of Time.cue
Ecco - The Tides of Time 
DETECT
DETECT
0602E29C|crc
Sega - CD.lpl
.\Games\SegaCD Games\Ecco the Dolphin\Ecco the Dolphin.cue
Ecco the Dolphin 
DETECT
DETECT
A13CD4C4|crc
Sega - CD.lpl
.\Games\SegaCD Games\Final Fight CD\Final Fight CD.cue
Final Fight CD
DETECT
DETECT
289AA991|crc
Sega - CD.lpl
.\Games\SegaCD Games\Snatcher\Snatcher.cue
Snatcher
DETECT
DETECT
22A6422A|crc
Sega - CD.lpl`

**Comment by markwkidd** [comment]
Could you post your a log showing the time of the crash?

To get a log, run from a command line:
`retroarch_debug.exe --menu --verbose >> log.txt 2>&1`
then, take the contents of that file and zip it so it can be attached to a message here.

**Comment by shinra358** [comment]
Isn't that error because of it not being in the database as stated in the linked thread and is expected behavior when games arent located in it? Also, this thread is continued in said thread too correct?

**Comment by markwkidd** [comment]
Games do not need to be in the database to play. The database only makes sure that the game ROM (or cue/bin) is the version most likely to work correctly, and then adds it to a playlist. If you create your own playlist and the game ROM is correct it should play for you.

**Comment by shinra358** [comment]
The purpose here is trying to get it to show in the xmb. It actually plays when I seek it out manually. But playing it manually is too much nagivating. That error came from me manually trying to put it in the playlist for it to be able to show but as the guy said in the other thead, doesn't work that way (I guess).

**Comment by markwkidd** [comment]
Your approach is correct, and should result in your manually-created playlist showing up in XMB and launching games correctly.

I wonder if the DETECT line in the playlist is choosing the wrong core, as opposed when you are choosing it manually which means the core is correct. That's why a log would help.

**Comment by shinra358** [comment]
okay, cool. I will provide that for you when I get off work. Until then, would you mind creating a .bat file for me that would automate the cmdline process?

**Comment by markwkidd** [comment]
This should do the trick. It just takes that line I sent you earlier and makes a batch file from it.

You may need to run this as an administrator, I'm not all that familiar with Windows RetroArch.

[generate log.zip](https://github.com/libretro/RetroArch/files/407165/generate.log.zip)

**Comment by shinra358** [comment]
[log.txt](https://github.com/libretro/RetroArch/files/407784/log.txt)

Ok, I put the Sega - CD.lpl with the above contents back into the playlists folder and ran the .bat. These are the results.

**Comment by markwkidd** [comment]
Nice! I'm glad there was a positive ending.

If and when Sega CD gets added to the playlist database, this will become much simpler.

**Comment by shinra358** [comment]
Would this be a prob with vulkan implementation, just a glitch, or a problem with vulkan install on my end?

**Comment by markwkidd** [comment]
Unfortunately my knowledge is more on the playlist and database end of things. I know there are quite a few bugs with Vulcan right now, with it being so new.

On one hand this might get fixed as part of the overall Vulcan process by the time the Sega CD database comes online in another RetroArch version or two.

On the other hand, you might think about renaming this issue to help make sure that someone is aware of it. Now that you have a better idea of the cause maybe you can work in the words Vulcan and Crash into the title. That might help attract a developer who could move things along. :)

**Comment by shinra358** [comment]
#3350

**Comment by orbea** [comment]
@shinra358 Is this still an issue?

**Comment by shinra358** [comment]
i dont know, I stopped using game scan because it was so troublesome to get games to show in the xmb. I just go str8 to them or use a frontend. I gave up. You can close if you want.

**Comment by orbea** [comment]
Okay, please let us know if you or anyone else can ever reproduce it in the future.
