### ISSUE TITLE
Same name for all PSX EBOOT mcr, srm and config files 

### ISSUE THREAD

**Issue by JuanVCS** [libretro/RetroArch#3356]
As per the [database for PSX eboots](https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation%20Portable%20(PSX2PSP).dat), all games are expected to be named EBOOT.PBP.
Problem is that the same filename is used for saves and configuration files of different games.

Not sure if this is the expected behaviour; the workaround I found was to make m3u playlists with an unique filename for each game and load that instead.

I stitched up a script to make m3u files out of a directory containing eboots in a structure like
"Descriptive game name/GAMESERIAL/EBOOT.PBP"

```
#!/bin/bash
 
# $1 - games dir
 
cd "$1"
find . -name '*.PBP' -print0 |
while IFS= read -r -d $'\0' line; do
pbp=$(realpath "$line")
ruta=$(dirname "$pbp")
juego=$(cd "$ruta"; cd ../; basename "$PWD")
echo -e "$pbp" > "$ruta/$juego.m3u"
done
```

**Comment by fr500** [comment]
I don't see as a bug, retroarch is working as expected
I don't see any suggestions either...

**Comment by Awakened0** [comment]
Can't you rename the pbp files, move them in your root PSX game folder and still have the scanner work? Since it uses CRCs to match the database, the filenames and location shouldn't matter...

**Comment by JuanVCS** [comment]
First thing that comes to mind as a suggestion is to use the serial number of the game (folder name), maintaining compatibility with Sony's file structure.
Another way would be for the scanner to generate m3u files with different names (like the script I posted).

**Comment by fr500** [comment]
To do that RetroArch itself would have to be hacked to read the serial or the folder name and it would mean to have a special use case for some particular cores which is not gonna happen

**Comment by Axiphel** [comment]
Just rename the pbp to the game name? RetroArch doesn't care what the files are named when it just checks the crc.
