### ISSUE TITLE
[Question] Can't Get Mednafen Saves to work with Retroarch Mednafen Saves

### ISSUE THREAD

**Issue by shinra358** [libretro/RetroArch#3361]
Normal mednafen saves a save file like this:
Virtual Boy Wario Land (Japan, USA).fb4dc9f4ebd506702eb49e99a62bd803.sav

Retroarch VB saves a save file like this:
Virtual Boy Wario Land (Japan, USA).sav

But if I try rename the first file to what the 2nd file looks like, it reads as a brand new untouched save (losing all progress).

How do I rectify this issue without just starting over?

**Comment by fr500** [comment]
Not a retroarch issue
https://github.com/libretro/beetle-vb-libretro
