### ISSUE TITLE
Settings - Audio Latency stepping

### ISSUE THREAD

**Issue by RePod** [libretro/RetroArch#3363]
Settings - Audio - Audio Latency

Stepping (in intervals of 16) down to 16 then 8 and going back up results in a non-original value of 24, although 16 might be expected:

> 64 ... 16, 8, 24 ... 72

Resetting the value to default works as intended.
The step size never changes, but the alignment does as it clamps to 8.

**Comment by twinaphex** [comment]
Yeah this is known. Not sure how to fix it with the current menu setting code, this is literally the only setting on which the current code seems to produce this undesirable side effect with.

**Comment by RePod** [comment]
While you may know your way around the repo, I don't so these are more for assisting me.
- [menu/menu_setting.c#L5737](https://github.com/libretro/RetroArch/blob/master/menu/menu_setting.c#L5737) (add range)
- [menu/menu_setting.h#L377](https://github.com/libretro/RetroArch/blob/master/menu/menu_setting.h#L377) (actual call)

----

My ideas:
 - Make 8ms a separate boolean option, if enabled disable/override the range (clamped to 16~512).
  - Unfortunately adds another list option, which is really arbitrary.
  - Probably by the time *settings->audio.latency* is determined, figure out what to use.
 - Instead of an auto-generated range, make it pre-populated by the time it's available to modify.
  - For instance, populate an array of 16~512 in desired interval then push 8 to the start.
     - Or push 16~512 to an array already containing 8. Whichever.
  - Potential minor rewrite to the range to prepend/append custom values to the list.
 - Decouple what the range shows and what it means.
   - It may display "8" but internal it is considered "0" (for stepping purposes). As above, determine what it should be at a later point.
 - Change the step size to 8.
   - Probably the worst fix considering it 16 to begin with. The config comments state some instances may not respect the latency setting if it's not possible, so this may lead to more applicable cases.

**Comment by LibretroAdmin** [comment]
I think having a range between 0 and 512ms as a dropdown list is probably sufficient regardless of any stepping. It's just a latency hint anyway, the audio driver can choose to disregard it or honor it as it sees fit.
