### ISSUE TITLE
Separate Gamepad Settings for Gamepad and RetroArch Menu

### ISSUE THREAD

**Issue by shinra358** [libretro/RetroArch#3365]
I would like to have the Gamepad Game config and the Menu Gamepad config separated. Currently, I can't complete my configs per game for Virtualboy games. When I try to map the right vb dpad to the face buttons, it results in me not being able to press and confirm within the Retroarch menu resulting in me overwriting the entire retroarch.cfg to fix the gamepad back.

If this isn't the correct section, I apologize.

**Comment by fr500** [comment]
We already provide core input remapping, overrides and autoconf that can help you in this regard.
I don't think adding an extra layer of complexity is worth it.

Not sure of your particular use case but I see no reason for this not to work with core input remapping.

**Comment by shinra358** [comment]
For example, games like teleroboxer cant be played like other games. It's impossible to play this game using the normal controls for the rest of the other games.

Also, it is very difficult to see what buttons to change because the config doesn't report the actual controls of the emulators but instead provides an overall button scheme. I can't even figure out how to map the 2nd dpad to my analog stick or to the face buttons.

**Comment by fr500** [comment]
That is a core problem not really a retroarch problem. It means it's badly implemented in the core.
I still don't think adding yet another method to remap controls is gonna fly and I'm totally against implementing this suggestion.

**Comment by shinra358** [comment]
by you saying it's a core problem, does that mean cores are supposed to be able to manipulate the control scheme in the retroarch controller options section for us to be able see what we're changing in an easier way (by giving us layouts of that particular console instead of the default retroarch scheme)?

**Comment by fr500** [comment]
RetroArch is supposed to have ONE pad configuration, think of it as a console.
You should try to map your controller as closely as possible to the retropad abstraction.

Cores have an internal wiring to that gamepad, so for example NES cores B/A are wired to RetroPad B/A.
Some people don't like this so we have core input remapping which you can use to change B/A from RetroPad B/A to RetroPad Y/B (which is X/A in my xbox gamepad)

So yes, the core has an internal mapping and it "publishes" a list of inputs it needs to be used by core input remapping.

The only limitations this subsystem has is that it doesn't support analog <=> digital remapping, and it doesn't support keyboards but other than that it should "just work"

**Comment by shinra358** [comment]
So in order to get 2 configs I need for VB, I would just need to request them in the vb core section?

**Comment by fr500** [comment]
Not sure, have you actually tried core input remapping (controls under quick menu)

**Comment by shinra358** [comment]
No I haven't. I'll see how that goes right now.

**Comment by shinra358** [comment]
Unfortunately, there isn't a 'Controls' option in the Quick Menu.

**Comment by fr500** [comment]
then that core doesn't have descriptors and it doesn't support remapping at all.

**Comment by shinra358** [comment]
Wait, found a different quick menu when you press the ps button during game. The controls are there. Pretty much hidden. Didn't know there were 2 quick menus.
