### ISSUE TITLE
PS3 Retroarch port of Atari 7800-Prosystem not referencing Database.c values when loading games

### ISSUE THREAD

**Issue by underball** [libretro/RetroArch#3376]
@twinaphex 

Although the Prosystem flags, region, pokey and type values from the Database.c source file are being processed via MD5 hash file detection and passed to the emulator core in the Windows and Android ports of Retroarch, this is not happening in the PS3 1.3.6 beta. This causes any games with non-standard Type, Flags, Pokey, or Region values to either crash Retroarch, or not function properly.

Games to test this include:

Commando (Atari - Doesn't load, crashes PS3 console and requires manual restart of console)
Double Dragon (Activision - game doesn't load, black screen, however, you can return to the RA menu)
Kung Fu Master (Activision - graphics are garbled, game is unplayable)

This is a known issue with the original version of Prosystem on Windows and Linux (non-Retroarch) if you remove the Prosystem.dat file from the install folder, so that the emulator can't reference the database and pass the appropriate values, per game. 

All these games are working on the Windows and Android ports of Retroarch (and every other port of Prosystem in existence, when the Prosystem.DAT file is present in the install folder alongside the executable.)

Roms of these games can be found here for testing purposes: http://www.atariage.com/system_items...ItemTypeID=ROM

**Comment by fr500** [comment]
This isn't a retroarch issue, the core should look in the standard locations instead of looking at the application dir.
Use this repo instead
https://github.com/libretro/prosystem-libretro

**Comment by underball** [comment]
No, This IS a Retroarch issue. In every other version of Prosystem, The Prosystem.DAT db file is a separate support file packaged alongside the executable. In Retroarch, whoever ported Prosystem to Libretro "baked in" the Prosystem.dat file into Database.c, so it's no longer a separate support file, and gets complied as part of the emulator core. So in Retroarch, endusers no longer have the ability to point to this file, so if it's not working, the problem is in the Core SELF file. 

The problem is this isn't working in the PS3 port of Retroarch, but it is working in the Windows and Android ports of Rrtroarch. The problem isn't with the Prosystem source. The problem is with the PS3 port of Retroarch, ONLY. 

It's a Retroarch issue, not a source issue.

**Comment by twinaphex** [comment]
If it's in the core SELf file, then the problem is in the core, not in RetroArch itself. 

These are two separate entities. Reopen this issue in the Prosystem issue tracker.

**Comment by underball** [comment]
The problem isn't in the cores of other ports of Retroarch, though. Just the PS3 port. I'm not sure that it's the core, since the Atari 7800 core works fine in the Windows port of Retroarch.

**Comment by fr500** [comment]
Even moreso if it isn't an external file. Most likely Database.c isn't
being compiled on PS3 or something.
RA doesn't have a single hack for a particular core in the codebase.

**Comment by underball** [comment]
ok, that makes sense. so where do I post an issue about something not being compiled on one port of Retroarch, but working fine on all others? There is no separate PS3 Retroarch GIT where I can post issues related only to that port. If it's just the PS3 port not compiling the database.c, then it's possibly something with the makefile target of the PS3 port? or an includes list is skipping it on PS3 compile?
