### ISSUE TITLE
Auto Archive Save State

### ISSUE THREAD

**Issue by thorst** [libretro/RetroArch#3378]
**Is there an event that gets fired when a user saves a games state.** I'd like to auto archive the states and keep the most recent 5 for each slot. My reasoning is that its easy to overwrite a slot by accident when im first starting. Im so used to saving state that I get into a game and immediately press save when i should be pressing load.

Im using retropie, but as they dont deal directly with the emulators I was referred here.

If there isnt an event, I can just write a file system watcher that will back up states as they come in. I prefer either of these two scenarios over a cron job with nightlies since you could potentially progress a lot in one day, and of course your machine would need to be on in order for the cron to run.

**Comment by fr500** [comment]
People wanted unlimited saves, we gave them unlimited saves.
To avoid overwriting (or rather recover from such event) we have undo save state and undo load state

And you have savestate auto index so it automatically increments the slot.
I think that's enough for 90% of the use cases

**Comment by thorst** [comment]
The undo save state is what I'm looking for. I'll see if they have that in RetroPie
--
Sent from Mail.Ru app for Android Thursday, 11 August 2016, 11:02AM -04:00 from Andrés  notifications@github.com :

**Comment by fr500** [comment]
If they don't have it, it should just be a matter of updating to the latest trunk.
Feel free to discuss the request further. Closing.
