### ISSUE TITLE
Sega Saturn controller via Mayflash adapter not recognized in Windows Retroarch (But recognized in Lakka)

### ISSUE THREAD

**Issue by neosquid** [libretro/RetroArch#3379]
I can get the pad to show up in Retroarch using some forum bindings advice to get the gamepad recognized. Despite this, the Saturn pad has six main control buttons, but the pad options in Retroarch only have four buttons that can be assigned in the bindings options.

In Lakka TV, it's auto recognized on startup with all of the ABC, XZY buttons configurable. 

Thanks.

**Comment by fr500** [comment]
Lakka IS RetroArch. There is not one difference in gamepad mapping between Lakka and standalone RetroArch.
This just means you're using a different driver with no autoconf profile for your pad.
There are at least 10 buttons you can assign to a physical input (A B X Y L R L1 L2 R1 R2 L3 R3)
