### ISSUE TITLE
Android- 8bitdo SNES30 not working via USB

### ISSUE THREAD

**Issue by Dagnillo** [libretro/RetroArch#3380]
I'm using Retroarch on a Shield Android TV.  The Bluetooth SNES30 gamepad has the ability to also function as a USB gamepad, but when I connect it, it works in the Leanback Launcher and other emulators, but is not detected in Retroarch. 

The gamepad also functions normally via the Bluetooth connection.

**Comment by fr500** [comment]
it's working fine here, update your gamepad firmware

**Comment by Dagnillo** [comment]
I will try that.
