### ISSUE TITLE
Android- 8bitdo SNES30 unable to assign hotkeys to triggeds

### ISSUE THREAD

**Issue by Dagnillo** [libretro/RetroArch#3381]
On a Shield Android TV, I cannot assign any hot keys to the L and R triggers on my SNES30 gamepad.  I can assign them to the face buttons without issue.  The triggers function properly in games.

**Comment by fr500** [comment]
it's working fine here, update your gamepad firmware I guess

**Comment by Dagnillo** [comment]
It says it's assigned but if I try to save state with Select being my modifier, it does nothing.
