### ISSUE TITLE
.ips soft patch support for 8/16bit Sega consoles

### ISSUE THREAD

**Issue by bigboo3000** [libretro/RetroArch#3383]
Hi
It seems that ips soft patching doesn't work in genesis-plus-gx
https://github.com/libretro/Genesis-Plus-GX/issues/54

I tested with picodrive and it doesn't work either.

Is it a bug or an unsupported feature for theese cores?

**Comment by Alcaro** [comment]
It's theoretically possible. It's up to the core whether it can actually be done.

I'll post the technical details over there.
