### ISSUE TITLE
[nuklear] Undefined reference to sbi_load and stbi_image_free

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#3384]
When trying to compile RA with nuklear support (using `--enable-nuklear`), it fails when linking because of undefined references to the `stb_image` library in the `nk_common.c` file (lines 50 and 66, functions `stbi_load` and `stbi_image_free`). The `stb_image` library seems to be included by `nk_common.h` but somehow isn't loaded properly.

Did I forget something or is it a bug ? Thanks !

**Comment by fr500** [comment]
not sure but the backend is not ready for usage so it doesn't really matter at the moment.

**Comment by natinusala** [comment]
Isn't there anything to test yet ? It looks quite advanced

**Comment by fr500** [comment]
happens here too... IDK it was working when I last worked on it

**Comment by amit56** [comment]
ay howd u end up fixing it

**Comment by natinusala** [comment]
I didn't, however now that I know what I am doing I know how to fix it

I'm pretty sure nuklear is not supported anymore anyway (is the code even still here?)

**Comment by twinaphex** [comment]
No we removed it.

I think we should focus right now instead on further developing Ozone, MaterialUI and XMB instead. Otherwise our efforts are spread too thin.
