### ISSUE TITLE
 no activation mail sent to my mailbox from libretro forum

### ISSUE THREAD

**Issue by bigboo3000** [libretro/RetroArch#3385]
Hi
I'm sorry to post that here but I can't post on the forum...

The libretro forum doesn't send me an activation mail so I can't post there.

I tested with two created account (one two weeks ago and one today) and I'm sure I have correctly typed my email adress.

Can you fix it please?

**Comment by fr500** [comment]
Go into IRC, #retroarch @ freenode and ask there please. 
This is a dev issue tracker.
