### ISSUE TITLE
[improvement] Add gamepad combo for speed toggle

### ISSUE THREAD

**Issue by jvook** [libretro/RetroArch#3387]
It would be great to have combo for speed toggle for grinding in RPG games.  Maybe we can use one of the unused combos from menu combo?  

Maybe the combo system will expand in the future but it would be nice to have a speed toggle combo in the meantime.

**Comment by fr500** [comment]
You can already use the hotkey modifier and the fast-forward toggle for this

**Comment by jvook** [comment]
For a combo?  How do you do it?  I just get whichever button  I hit first.  Is it because Im using rgui?

**Comment by Dagnillo** [comment]
Set a key as the hotkey modifier first (select for example), then set another button (x for example)  to Fast Forward.   Then you press select+x to fast forward

**Comment by fr500** [comment]
We already have that for all hotkeys.
Look for hotkey enable.

We won't be adding different combos for each hotkey

**Comment by jvook** [comment]
Thanks it works

**Comment by jvook** [comment]
How do I set it so that keyboard hotkeys still work without holding hotkey enable?

**Comment by fr500** [comment]
it's all or nothing
inputs are not separate for one device or the other

**Comment by jvook** [comment]
Keyboard shortcut works if i set input_enable_hotkey to left shift.  If it's all or nothing, wouldn't it be preferable to make null setting work as activation hotkey? Then users who don't use hotkey would see no change (their hotkey is always enabled as its defaulted to keyboard null) but users who enable a gamepad hotkey would still work as well.

**Comment by jvook** [comment]
OK I see what you mean.

**Comment by jvook** [comment]
Well, inputs are separate because there is input_hot_enable and input_hotkey_enable_btn.  But you are saying retroarch doesn't differentiate between these, that they are both seen as an input of hotkey_enable, right?  So retroarch could differentiate between these, but it doesn't.
