### ISSUE TITLE
Mouse axis is limited

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#3408]
I tried to play TyrQuake some time ago selecting "keyboard + mouse" in quick menu controls.
Strangely I can't turn around myself: it's limited to something like 90° in each direction.

Recently I was playing Forgotten World with Mame core. 
I tried to assign "Dial Analog" to my Mouse X axis in Mame GUI to turn the weapon around with the mouse: again it's limited to something like 180° in each direction.

Mame standalone has no problem: you can just turn around in circles.
Looks like a Retroarch problem?

**Comment by Tatsuya79** [comment]
I noticed when my pc mouse is on a fast setting like 1600dpi the movement range is short, when switching to 800dpi sensitivity the pointer can go a bit further.

**Comment by Awakened0** [comment]
With nightlies right now, sometimes RetroArch doesn't hide the Windows cursor in fullscreen mode. When this happens I notice in MAME dial games that the mouse input stops when the cursor hits the edge of the screen. Maybe RA needs a way to "grab" the mouse cursor for input so it doesn't have that limitation.

**Comment by Monroe88** [comment]
Press the Grab Mouse toggle hotkey (Default: F11) to hide the cursor.

I think the mouse cursor showing up is due to the Game Focus toggle hotkey (Default: Scroll Lock) that was added to block all hotkeys and RetroPad keybinds for cores that use the keyboard directly.

**Comment by Awakened0** [comment]
Thanks for the tip! 

The cursor won't autohide anymore if I press F to enter windowed mode then F again to go back to fullscreen. It also tends to show up in fullscreen when launching MAME games from Steam or just launching games in general from XMB.

Even with the mouse grabbed the mouse input bound issue persists.

**Comment by Tatsuya79** [comment]
It happens with doom on SNES (snes9x).
It's there in Linux too.

**Comment by gudlyf** [comment]
Experiencing this problem with latest RetroArch Beta (1.4.1) on Windows using the X-Arcade Tankstick. Attached same thing to a RetroPi and it works fine there.

It does seem to behave as though movement in any direction for the game character stops when the logical mouse pointer would be hitting against the screen border.

**Comment by gudlyf** [comment]
FWIW: Installing this program on Windows "solves" the issue, proving RetroArch (or the underlying core?) is reading cursor position rather than mouse input: http://www.door2windows.com/unlimited-mouse-dont-let-your-screens-border-stop-your-mouse-cursor/

**Comment by Tatsuya79** [comment]
Sadly it's not helping for FPS game.
If you try TyrQuake you'll see your aiming range is still limited to 90°.
Reaching one end starts you from the other end.

**Comment by Tatsuya79** [comment]
Same issue with a mouse connected by an OTG cable on android: range is limited by the screen resolution.
You can not turn around yourself in TyrQuake.

But you can if you use the touchscreen as a mouse.

**Comment by Tatsuya79** [comment]
The range is dependant of retroarch resolution: I cover 90° in 1080p, 180° in 4k in TyrQuake as an example.
This should probably be relative by default and then the cores give a limit or not.

**Comment by Tatsuya79** [comment]
Through bisect hell, I found the origin:
https://github.com/libretro/RetroArch/commit/7755277b87eb6e8f56174fee96eaa9c8e26d7d14

**Comment by twinaphex** [comment]
'Following system mouse cursor in windowed mode' should probably be avoided when we are not inside the menu.

**Comment by gudlyf** [comment]
How do we add a bounty to this sucker? I'll pay to have it fixed!

**Comment by twinaphex** [comment]
Hi @gudlyf,

due to a bug in Bountysource, only new issues work properly for posting bounties to it.

So I will do that, and I will add $10 to it just to get it started. From that point on, you will be able to add additional bounty money to it.

**Comment by bparker06** [comment]
Hi @gudlyf,

The usual approach is to click on the "Post a bounty on it" link under the initial description at the top of the issue. Another method is to paste the issue URL into the search box at bountysource.com. ~There is currently an unresolved bug~ What Twinaphex said... after the new issue is created, then you can use one of the two methods I mentioned to add money to the pot.

**Comment by twinaphex** [comment]
@gudlyf,

I opened this just now and added $10 to it -

https://github.com/libretro/RetroArch/issues/4788

You can go to this Bountysource page and add more bounty money there -
https://www.bountysource.com/issues/43539031-bounty-mouse-axis-is-limited

**Comment by Tatsuya79** [comment]
Retroarch 1 commit before the bug for windows x64 + dll for testing:
[Download win x64](https://mega.nz/#!89FUGaLQ!NkHaG8-sIjxS7jsG-0bIXNSxm0sQTkcv7SBIR9_Vtqo)

**Comment by retro-wertz** [comment]
this older commit/version does seem to work better. i've been trying to make zapper work in fceumm and crosshair is stuck near the middle or lower and seems to reset at random area each run of the core.

using this old commit is able to make crosshair move freely(as long as within the game's viewport) and each time core is restarted crosshair always starts at upper-left corner(fceumm sees this as axis 0,0 when not using "use_overscan")
![retroarch-0331-063858](https://cloud.githubusercontent.com/assets/23315382/24529238/1669cc32-15dd-11e7-99ed-9e51900d8c14.png)
![retroarch-0331-063843](https://cloud.githubusercontent.com/assets/23315382/24529239/16715e70-15dd-11e7-96d9-121c92980e5d.png)

**Comment by Tatsuya79** [comment]
I compiled today nightly for win x64 [with that fix](https://github.com/Tatsuya79/RetroArch/commit/5649f084e33651de479278b856cc8739cde35033):
https://mega.nz/#!ZsVnVaCT!6cuMaihNAM7VJw5nkjY9QezJv-i2uI9eLYEf9707Df0

I can't find any downside: tried to use glui in windowed/fullscreen modes and the mouse is still working for navigation.
Mouse movement is relative again in cores.

**Comment by Awakened0** [comment]
Looks good to me on Win10. Like you said, mouse menu input seems to work the same as it does without the fix. Tested some spinner and trackball games in MAME and everything works well with mouse input again. Desmume's touchscreen cursor too.

**Comment by gudlyf** [comment]
Confirmed the linked binary works on Win10 for me as well. Worth the bounty!

**Comment by Tatsuya79** [comment]
Lol I don't know about the bounty.
The problem seems fixed for windows but Linux and Android input drivers would need a fix too.
Perhaps Mac too?

If some money comes my way [you can put it on top of that directly.](https://github.com/libretro/RetroArch/issues/4792)

**Comment by cgmartin** [comment]
I am having this same issue on Ubuntu linux with the following package:
```
retroarch/artful,now 1.6.9-r201711212140-e8b10d3-72~ubuntu17.10.1 amd64 [installed]
```

**Comment by bfalese-navent** [comment]
still happening in android!

**Comment by JamesIV4** [comment]
Hey guys, don't mean to necro this, but this is still happening on Linux (Steam Deck). It makes using the trackpads useless for FPS games.
