### ISSUE TITLE
Rename controllers

### ISSUE THREAD

**Issue by blm07** [libretro/RetroArch#3416]
So I have a somewhat elaborate setup where I have a bunch of different console to PC adapters plugged into a USB hub. It would be nice if we could rename each controller something different, for instance, for the SNES controllers, I'd like to rename one "SNES Controller" and the other "Super Famicom Controller." Or maybe "NES Controller (Port 1)" and "NES Controller (Port 2)." I have them renamed in the Windows registry, but that ends up being messy.

**Comment by fr500** [comment]
if the controllers are being configured with autoconf there is a display name parameter there to change the name to something user friendly but those adapters often have the same string, vid and pid which makes it impossible to differentiate them programatically.

**Comment by fr500** [comment]
https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/android/NVIDIA_SHIELD_Portable.cfg#L2
