### ISSUE TITLE
Android - RetroArch does not scan zip archives on current nightlies

### ISSUE THREAD

**Issue by ReasonanC** [libretro/RetroArch#3417]
As of right now [I tested nightlies from 21st and 22nd] RetroArch ignores archived roms during the scanning process - I can load them easily from those zips via Load Content, they work fine. Also, they scan properly in the most recent Windows nightly.

Roms are on an external sd card, on a Lollipop [5.1.1] smartphone.
PSX .cue+bin in the same folder scan just fine.

**Comment by RobLoach** [comment]
There was a recursive PR that was just merged. https://github.com/libretro/RetroArch/pull/3412 ... Maybe a regression?

**Comment by ReasonanC** [comment]
Just try to scan any folder with zipped roms - they won't be included in a playlist [did so on external sd card, but it shouldn't be storage specific - after all it can access and play those roms via select content

**Comment by bparker06** [comment]
Zip scanning is still working for me on Linux even after the PR #3412.

**Comment by fr500** [comment]
I just scanned my whole collection on android too, mixed zipped and not and it worked as expected.
Feel free to add to the conversation but unless someone else can repro this seems like an issue on your end.
