### ISSUE TITLE
Thumbnails for Sony PSX, N64, Sega Saturn, Sega CD not properly scraping/adding to Games list.

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#3421]
Hi RetroArch,

I am trying to add a bunch of games for their thumbnails and have ran into some problems. I aim to understand these problems better and then document them for the Wiki to help other struggling fans of RetroArch set up their libraries all nice!

Presently, I have had no issues when adding Sega Master System, SNES, NES, and TBGF16 - but when trying to add in libraries for PSX, N64 etc -I am not getting the behaviour I expect.

First - I have my directory structure as follows:
ROMS
|------NES
|------SMS
|------PSX
|          |-----Amazing SpiderMan
|------N64
|------Sega CD
|          |-----Sonic CD

So as you may note, in the PSX and Sega CD directories, there are sub dirs that contain the bin/cues. These are also named in full and resemble the titles to the BoxArt in the thumbnails directory. I found that "searching" the directory at the root level to "Sega CD", would not scrape the sub  dirs. I then would scrape the sub directory - but this did not add the game to my collection. In the case of PSX however, I was able to add the games, and they show in XMB - however none of the box arts are showing.

I tried searching for more info on the website and other tutorials, requesting help on the retroarch subreddit, and finally now decided to request help as an issue to Git - so that I may help contribute in documenting this more thoroughly and aid other users through the process.

Please let me know if we can talk a bit about this, or if you can help lead me in the right direction.

Thanks!

**Comment by RobLoach** [comment]
Mind giving CRCs for the Spierman and Sonic games? Can check if they match in the DB.

**Comment by cudencuden** [comment]
rob also started https://github.com/libretro/RetroArch/issues/3139 to look into the recursive scan

**Comment by futurepr0n** [comment]
How could I check those? Sorry.. I know how to run md5 against files, but never done a CRC check myself.

Is there anything else you can comment on - regarding the directory structure? it would see that RetroArch might not scan through SubDirs (I am using OSX version if that helps) - I tend to get no scan result, and have to go one level down into the folder (named the same as the bin/cue) and only then does it seem to scan. 

For  PSX games, as mentioned this successfully added them to a "library" but did not pair them to any Thumbnail art. Kinda strange.. I also had issues if I kicked off multiple thumbnails to be downloaded through the updater - that I had I guess a service lockup if one was unzipping while another concluded its download. I would check the Thumbnails directory and see the package didnt properly download and extract - and had to retry one at a time. Perhaps there is a way to queue these so that one does not extract if another is currently locking up the service?

**Comment by futurepr0n** [comment]
cksum Amazing_Spider-Man_Vs_The_Kingpin\(US-Genesis\).bin 
152349360 555815232 Amazing_Spider-Man_Vs_The_Kingpin(US-Genesis).bin

**Comment by bparker06** [comment]
I submitted a patch that implements recursive scanning per issue #3139 and it was merged on Sunday. This should be available in the next 1.3.7 release, or if you download the latest nightly you should be able to test it out. Recursive scanning is always on by default now.

**Comment by futurepr0n** [comment]
Great @bparker06  - any info on how I can maybe check my own CRC's against 'a' or 'the' database which pairs them to the BoxArt? no sense in having someone else check on my behalf (as offered by @RobLoach ) when I am perfectly capable of doing such a thing!

Appreciate the patch you worked on as well - but still curious about a few things - not sure if you can help...

If ROM's are scanned and added to a library in the XMB, is it possible to remove them? I have a lil Nintendo Satellaview library added now - but no Game Art is available for these, and for that reason I'd like to hide or delete them from the quick launch - or whatever that section would be referred to - in the XMB?

Also individual roms within a collection - for instance, I have a few JPN games that I also have USA versions - instead of deleteing them from the ROM directory and rescanning, now that they have been picked up by the Game Library, if I wanted to select an individual game/rom in the list and "remove" it - is this possible?

**Comment by bparker06** [comment]
As far as I'm aware, playlist entries cannot be modified from within the GUI, you would have to manually edit the files in ~/.config/retroarch/playlists or your relevant config directory.

I believe the databases are saved in a custom format, but they are derived from the DAT files here https://github.com/libretro/libretro-database/tree/master/dat which you can check individual CRC/MD5/etc. checksums from.

**Comment by RobLoach** [comment]
@futurepr0n Mind running a `crc32 *` on them instead? As @bparker06 explained, that's what it uses to match.

**Comment by futurepr0n** [comment]
No problem, I am a CRC n00b, my bad. Thank you.

```
b79bddd8	WWF No Mercy (E) (V1.0) [!].z64
43ba9e7e		WWF No Mercy (E) (V1.1) [!].z64
b33f44f0		WWF No Mercy (U) (V1.0) [!].z64
```

```
Sega CD
a009d981		Amazing_Spider-Man_Vs_The_Kingpin(US-Genesis).bin
152d19d0	Amazing_Spider-Man_Vs_The_Kingpin(US-Genesis).cue
```

```
PSX
961b3eba	Apocalypse (USA) (Track 1).bin
9d424890	Apocalypse (USA) (Track 2).bin
1fc2f0b6	Apocalypse (USA).cue
```

**Comment by RobLoach** [comment]
- Sega CD
  - Uses Redump, TOSEC, or Trurip. If you rip them using their documented methods, it'll work. As an alternative, you could download the Amazing Spiderman CUE sheet from [Redump](http://redump.org/), and name the .bin file to what it expects, and it'll load correctly.
- N64
  - Looks like [one of the GoodTools sets](https://github.com/libretro/libretro-database/blob/master/metadat/goodtools/Nintendo%20-%20Nintendo%2064.dat#L17713). They unfortunately don't have the No-Intro naming convention, so the thumbnail filenames don't match up.
- PSX
  - The PSX database currently only does single-image Serial-based reading. There is a PR over at https://github.com/libretro/libretro-database/pull/251 to switch it to use Redump/TOSEC/Trurip. Would appreciate your thoughts on that in the PR.

**Comment by Axiphel** [comment]
The PSX box art library is not complete and those games you listed do not have a box art added yet. So of course you won't see box arts for them in menu.

**Comment by futurepr0n** [comment]
Sorry, not sure I follow @RobLoach  - the GoodTools set is compatible, but I dont have a matching name convention? I couldnt really gather from the link whether there is anything I can do to make them compatible. Perhaps thats not the case.

For Sega CD and PSX - lil bit beyond my comprehension but looks like you have a pull request that could correct this issue - and I could possibly test it? Or you are asking other contributors for their feedback on the linked PR. 

Thanks @Axiphel - I did see some of the thumbnails for the PSX though, but didn't post those particular ones I guess. Family Fued for instance. Anyways - it looks like Rob has addressed my issue as well, and I have bad romsets/dumps. Thank you for helping as well!

**Comment by RobLoach** [comment]
> Sorry, not sure I follow @RobLoach - the GoodTools set is compatible, but I dont have a matching name convention?

Good64 works, just the thumbnails don't share the same names. The thumbnails follows No-Intro. We'd have to rename all the titles in this DAT to match No-Intro names:
https://github.com/libretro/libretro-database/blob/master/metadat/goodtools/Nintendo%20-%20Nintendo%2064.dat

> For Sega CD and PSX - lil bit beyond my comprehension but looks like you have a pull request that could correct this issue - and I could possibly test it?

For Sega CD, you'll just have to download the .cue file from Redump.org , and use that instead of the one you have.

For PSX, the fix is up over at https://github.com/libretro/libretro-database/pull/251 . You could post your thoughts or just say +1 over there :wink:

**Comment by futurepr0n** [comment]
Thanks @RobLoach  hah - now is there anyway I can run a batch rename on my Good64 Romsets so that the names match and boxart will grab? Is there any chance you guys would like someone to help document this as part of the site wiki? or github wiki? I could take some time to compile this info into a section/faq... I appreciate the help!

**Comment by RobLoach** [comment]
It's not your N64 roms that are named wrong, it's the libretro-database goodtools DAT:
https://github.com/libretro/libretro-database/blob/master/metadat/goodtools/Nintendo%20-%20Nintendo%2064.dat

Would be neat to have a script to rename them all automatically somehow.

**Comment by futurepr0n** [comment]
Any chance I can help here? Still not understanding thoroughly, but I did a quick compare:

```
43ba9e7e        WWF No Mercy (E) (V1.1) [!].z64 
```
from my rom set - is equal to the entry in the database:
```
game (
	name "WWF No Mercy (E) (V1.1) [!]"
	description "WWF No Mercy (E) (V1.1) [!]"
	rom ( name "WWF No Mercy (E) (V1.1) [!].z64" crc 43BA9E7E )
)
```

It matches on complete name and CRC. What am I missing here? I've gotten fairly proficient with Python, wouldn't mind working towards some sort of solution / script. I just need to ramp up my understanding of how everything works within RetroArch, I haven't really familiarized myself with the source.

**Comment by bparker06** [comment]
He is saying that your filenames match the goodtools DAT... but the thumbnail uses the NoIntro DAT... which have different names and CRCs.

**Comment by cudencuden** [comment]
rob mentioned that thumbnails are based of no-intro..which in your example, no-intro has:

game (
	name "WWF No Mercy (Europe)"
	description "WWF No Mercy (Europe)"
	rom ( name "WWF No Mercy (Europe).n64" size 33554432 crc EEB166B4 md5 F58F64A8AD952459B2EE37F07004272B sha1 CADBCD5361DFFAF2AA17F0CB4C4CC799BDC8350A )
)

**Comment by RobLoach** [comment]
To fix this, you would....

1. Go to the GoodN64 DAT over at https://github.com/libretro/libretro-database/blob/master/metadat/goodtools/Nintendo%20-%20Nintendo%2064.dat
2. Find the `WWF No Mercy (E) (V1.1) [!]` entry
3. Change the name and description to match the No-Intro naming scheme: `WWF No Mercy (Europe)`
4. Rebuild the database
5. Copy the new rdb in
6. Delete your `./.config/retroarch/playlists`
7. Rescan the directory
8. See the new thumbnail appear for WWF

Again, I'm unsure of actually changing it in that DAT because we would loose those changes when updating GoodN64 in the future. Hence, having a script automagically update from GoodTools naming scheme to No-Intro would be pretty nice.

**Comment by Axiphel** [comment]
It would just be way simpler to replace your roms with those from the No-Intro rom set...

**Comment by futurepr0n** [comment]
@Axiphel  - it would seem that way.. Is there not a benefit to an end user if maybe some of the thumbnail pairing was relaxed a bit so that you could select based on name criteria alone? I have the issue where I need to go to redump for some of my cue files and that might be a pain in the arse.

**Comment by cudencuden** [comment]
thumbnails detection is based on names...but no-intro names

**Comment by futurepr0n** [comment]
@cudencuden But the SegaCD checks require me to download new .CUE files - and that would probably mean I need to edit those .cue files to load up the .bin files I already got that for some reason my present .cue files are not being identified? So that would be a PITA no? I mean, I gotta go into every file and then replace the .bin file name or I gotta rename the .bin file to match the redump .cue

**Comment by RobLoach** [comment]
1. Download the CUE file
2. Rename the .bin image that you have to match the filename that the CUE file has specified

**Comment by futurepr0n** [comment]
Yeah - but doing this 100+ times @RobLoach ... Also was curious why the reason for such strict checking against files. What problem is it, if someone wanted to have boxart associated with a hacked rom that included a trainer, or or some other tweak/mod?

**Comment by bparker06** [comment]
It would be nice to be able to have boxart no matter what you might have done to your rom that's different from the checksum in the database... but I don't know of a sane way to accomplish that short of just fuzzy checking the name somehow, which seems error prone.

**Comment by RobLoach** [comment]
The [Alternative Scanning Method](https://github.com/libretro/RetroArch/issues/2033) feature has been suggested before. Would make it a lot easier if you don't want to match CRC data, just simply match a Folder up to a Core.

Benefits of CRC scanning:
- It gives clean titles for when you files arn't named correctly
- Allows detection of which system/core to use, no matter what folder/files you scan

Cons of CRC scanning:
- You need to make sure you have the right file
- Optical media (like Sega CD, PSX, PCFX-CD, etc), get tricky since there's a million different ways to rip a CD, all resulting in different CRC data. That's why there are projects out there like Redump, which documents a standard way to rip the media.

> It would be nice to be able to have boxart no matter what you might have done to your rom 

It will work, no matter how you've named your files. As long as the CRC matches the No-Intro DAT, then BoxArts wil work. GoodTools doesn't share the same naming convention, so we have to update the DAT to fit No-Intro naming scheme.

**Comment by Kivutar** [comment]
Just name your boxart with the same name as your playlist entry, and it will display. You can write playlists manually or use a 10 lines script to generate them. Without CRC matching. Thumbnails are not dependant on the CRC or the database, they are just fetched using <name of the playlist>/<name of the entry>.png

**Comment by futurepr0n** [comment]
@RobLoach I was going to try testing your Commit with the PS1 Thumbnail scanning, but am wondering is there any precompiled builds or do I need to have my whole environment set up so I can build for each platform I wanted to test on?

Thanks
