### ISSUE TITLE
"video_font_size" setting is configured twice in retroarch.cfg!

### ISSUE THREAD

**Issue by TheDcoder** [libretro/RetroArch#3425]
The `video_font_size` setting/key is defined twice in `retroarch.cfg`. I have discussed this issue with Lakka developer @Kivutar and he said that he did not see anything which causes this in RetroArch or Lakka.
> kivutar: I'm not sure
> kivutar: I don't see anything in lakka or retroarch that causes it

I have only tested this in Lakka and not RetroArch in general. [Here](https://ghostbin.com/paste/mu3mz) is my `retroarch.cfg`, `video_font_size` is present in [Line no. 116](https://ghostbin.com/paste/mu3mz#L116) and [Line no. 159](https://ghostbin.com/paste/mu3mz#L116)

**Comment by dankcushions** [comment]
might have found the issue?
https://github.com/libretro/RetroArch/blob/616f517de796a4af598540d016a61093a10000f3/configuration.c#L3016
and
https://github.com/libretro/RetroArch/blob/616f517de796a4af598540d016a61093a10000f3/configuration.c#L3028

seems redundant, at least.

**Comment by twinaphex** [comment]
Should be fixed now I hope -

https://github.com/libretro/RetroArch/commit/3bbf2a74baa80336662011f2df1f25506486f35d

**Comment by TheDcoder** [comment]
Wow, that was fast! :grinning:

**Comment by TheDcoder** [comment]
Small question, will the older version of RetroArch without the bug fix work with a single entry of `video_font_size`?

**Comment by TheDcoder** [comment]
Small question, will the older version of RetroArch without the bug fix work with a single entry of `video_font_size`?

**Comment by Kivutar** [comment]
Yes

**Comment by TheDcoder** [comment]
Thanks @Kivutar :smile:
