### ISSUE TITLE
Auto Save-State doesn't happen if exiting Retroarch via hotkey (Windows, latest stable)

### ISSUE THREAD

**Issue by andreycout** [libretro/RetroArch#3432]
Self explanatory. The "Auto Save State" doesn't work if you quit by using the hotkey (Esc by default). It doesn't make a state snapshot before closing Retroarch. Manually choosing "Quit" from the GUI is the only way of ensuring it saves the state before quitting.

**Comment by Axiphel** [comment]
This should have been fixed with https://github.com/libretro/RetroArch/pull/3411 days ago.

**Comment by andreycout** [comment]
Just downloaded nightly. Indeed working as intended. Great job.
