### ISSUE TITLE
Can't select folder for menu wallpaper

### ISSUE THREAD

**Issue by DerekRoth** [libretro/RetroArch#3436]
In Settings > Menu > Menu Wallpaper the file browser does not provide a "\<Use this directory\>" entry like [mentioned in the wiki](https://github.com/libretro/Lakka/wiki/Dynamic-Wallpapers)  and requires to select a file in the directory instead of the directory itself.

Tested on latest Lakka for RPi3 and OSX.

**Comment by bparker06** [comment]
Are you sure you are trying to change the "dynamic wallpapers" directory and not just set a single "menu wallpaper"? The latter will only let you choose a single file as it is not dynamic.

**Comment by DerekRoth** [comment]
Aww, yes i was searching for this configuration option in the "Menu" panel where you can select a single wallpaper instead of the "Directory" panel where you can select a folder. So it's more like a user experience issue actually.
