### ISSUE TITLE
Take Screenshot gets stuck in a loop

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3438]
OS: `Slackware64-current`
`RetroArch-2016.08.27_dcf818b_master-x86_64-1_git.tgz`
`beetle-psx-libretro-2016.08.19_ec5fa68_master-x86_64-1_git`

When using the `Take Screenshot` option in the menu occasionally RetroArch will get stuck in a temporary loop taking the same screenshot repeatedly while taxing the CPU. This can be as few as two images or up to ~10. This has been an issue since at least the `1.3.6` release and I have experienced this with the OpenGL renderer in beetle-psx-libretro, but have not tested other cores enough to see if it occurs with them too.

Backtrace: http://pastebin.com/nMwbEbfb

**Comment by orbea** [comment]
So far I can reproduce it with GLupeN64plus and beetle-psx, but maybe not with bsnes-mercury-accuracy. Maybe it has something to do with the higher system requirements of some cores?

**Comment by bparker06** [comment]
So far I'm unable to reproduce this.

**Comment by orbea** [comment]
It has to be something specific to my system, but what?

**Comment by fr500** [comment]
it seems to happen on emscripten too

**Comment by orbea** [comment]
It seems I can no longer reproduce this.

@fr500 Can you still reproduce this on emscripten?

**Comment by orbea** [comment]
I'm just going to close this until someone can reproduce it again.
