### ISSUE TITLE
Retroarch iOS version buttons issue 

### ISSUE THREAD

**Issue by Fadi5555** [libretro/RetroArch#3453]
Hi there. I just want to tell you there is an issue on buttons.
I play retroarch by ps3 controller through cydia tweak called (controllers for all).
Anyway I can remapping all buttons correctly except start button. (Start and select buttons are mapping as same button) i mean if you can remapping this two buttons to be different.
To could mapping them correctly. Thanks

**Comment by Fadi5555** [comment]
Any answer please

**Comment by fr500** [comment]
The mfi spec doesn't have start / select. CFA emulates a mfi gamepad.
It's an Apple issue not a RetroArch issue.
