### ISSUE TITLE
RetroArch takes time to launch

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#3454]
I did a git pull today, and since then RetroArch takes a few seconds to launch, which was not the case a few days ago.

It also happens width rgui and no retroarch.cfg.

**Comment by twinaphex** [comment]
Track it down to a specific commit.

**Comment by bparker06** [comment]
I had a similar problem but after doing a make clean and rebuilding I cannot reproduce it anymore. Can you try fetching the latest commit and recompiling from scratch?

**Comment by fr500** [comment]
Is this still happening? if so please re-open
