### ISSUE TITLE
Allow controller autoconfigs in core overrides folder

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#3457]
I use controllers with different button numberings on multiple cores. I also setup hotkeys on unused buttons in each core. Currently, I can set up retroarch to either use "button 3" as a hotkey in a core override (which messes up controllers with a different button 3), or I can set it up as an autoconfig option for the specific controller (which messes up cores that map button 3 to actual game controls).

The only two solutions I can think of for this is to either allow hotkeys to be mapped to retropad buttons instead of physical button numbers or to allow controller autoconfigs in core override folders. The second seems more equipped to handle edge cases.

**Comment by meleu** [comment]
What a coincidence! Me and @Dagnillo were talking exactly about it in #3014 !
I think that linking hotkeys to the retropad buttons would be nice!

**Comment by Dagnillo** [comment]
Yes RetroPad buttons seem like the obvious choice to me, I third this suggestion.

**Comment by fr500** [comment]
The original request doesn't make any sense whatsoever.

**Comment by Dagnillo** [comment]
You don't understand it so you close the issue?

**Comment by fr500** [comment]
Because controller autoconfigs in the overrides folder will not solve anything.

**Comment by Dagnillo** [comment]
Fair enough, what about using Retropad buttons?

**Comment by tony971** [comment]
Autoconfigs in core overrides would essentially work as a core remap but controller specific and with hotkey support

**Comment by fr500** [comment]
Sure if you implemented the mechanism.
I don't want any more complication added to the mix so for the original request it's still NO

**Comment by tony971** [comment]
I wasn't refuting the complexity. You just said that it made no sense and wouldn't solve anything. It would. It's just a complicated procedure for edge cases.

**Comment by fr500** [comment]
I think the other suggestion even if difficul may be acceptable, so please make the other suggestion (retropad binds for hotkey)s in another ticket.
