### ISSUE TITLE
IOS Dynarec(JIT) 64 bit devices

### ISSUE THREAD

**Issue by hotyute** [libretro/RetroArch#3468]
Over at PPSSPP they accomplished Dynarec(JIT) on 64 bit IOS devices. I am wondering if we can accomplish this on some cores over here at retro arch? Particularly the Mupen64 core.. How would I go about doing this?

Reference this thread on its implementation:
https://github.com/hrydgard/ppsspp/issues/8122

**Comment by Kivutar** [comment]
Would be great for Odroid C2

**Comment by hrydgard** [comment]
The actual code is in https://github.com/hrydgard/ppsspp/pull/8937

In summary, you need to:

    * Call syscall(SYS_ptrace, 0 /*PTRACE_TRACEME*/, 0, 0, 0); on startup, to pretend to be a debugger. This lets you map pages PROT_EXEC. This seems to require an "entitlement" of some sort.

    * In the JIT implementations, make sure to never map a page PROT_WRITE and PROT_EXEC at the same time. Whenever you need to change code, make the page PROT_WRITE using mprotect, then change it back to PROT_EXEC.

And that's pretty much it.

**Comment by hotyute** [comment]
@hrydgard Thanks a lot. Wish I had a MAC, or a PC that can handle virtualization well. Otherwise I'd do it myself.

**Comment by twinaphex** [comment]
HI @hrydgard, thanks for sharing this.

I have not forgotten about returning back to a mainline libretro port again, updated this time. Let me get back to you quickly on that.

**Comment by Fadi5555** [comment]
@twinaphex also please don't forget to fix crashes on pcsx_rearmed that use dynarec not interpreter on iOS.
Thanks a lot.

**Comment by twinaphex** [comment]
@Fadi5555 It's probably best to take that up with @notaz since he still maintains the PCSX ReARMed repo and I don't think he would like it if I started hard forking.

**Comment by hotyute** [comment]
@twinaphex What about the Mupen64 core?

**Comment by Fadi5555** [comment]
@twinaphex don't worry about that. Because it was work when we was on iOS 8 so it just need to be rework again on iOS 9. I know it's his work. But he will never be sad if you implement dynarec on this core again. I'm sure he will like that and appropriate as well.

**Comment by Fadi5555** [comment]
@twinaphex I talked to @notaz and said no problem if you want to implement dynarec back to pcsx core on ios.
This is image from his write:
![image](https://cloud.githubusercontent.com/assets/10546081/18134010/7c4598bc-6fa5-11e6-8d32-b7eec4b2aef0.jpeg)
 For more details go to that link above.
Thanks.

**Comment by Fadi5555** [comment]
@twinaphex anything new about supporting pcsx dynarec core please?
@notaz said there is no problem at all and will happy if you help him as well.
Thanks.

**Comment by Alex793** [comment]
Hi, in fact if it's possible can we have a dynarec fix also for Picodrive (not perfect emulation for 32X Emulation on my Ipad Pro 9.7, on my Ipad Air 1 iOS 8 it's perfect with dynarec) and also N64 emu.

;)

**Comment by hotyute** [comment]
Just checking up on the N64 core as well. Any updates?

**Comment by Fadi5555** [comment]
We just waiting for @twinaphex to update the cores to support dynarec again.
To could play in fullspeed. Pcsx as well as n64.

**Comment by Alex793** [comment]
Hope Picodrove too and all other core using dynarec ;)

**Comment by Fadi5555** [comment]
@twinaphex please start work on supporting dynarec on retroarch cores on ios.
We really miss that so much.

**Comment by Fadi5555** [comment]
@twinaphex when you'll start on supporting dynarec cores for iOS please?

**Comment by fr500** [comment]
@Fadi5555 we are all volunteers here.
There is no iOS work being done ATM, iOS is not really convenient because of the cat and mouse game (updates, changes breaking compatibility, etc.)

Please stop badgering.

**Comment by Fadi5555** [comment]
Hi there. I have great news.
@notaz is finally could get JIT dynarec work again on iOS. So you need only to merge his work.
For more details see this link please:
https://github.com/notaz/pcsx_rearmed/issues/74

**Comment by hotyute** [comment]
Thats great that they got pcsx's jit working.. just need it for mupen64 now

**Comment by notaz** [comment]
I've only implemented what I think is needed without having the hardware, AFAIK nobody reported it actually working yet.
