### ISSUE TITLE
[vulkan] add a way for cores to enable instance layers

### ISSUE THREAD

**Issue by julianko** [libretro/RetroArch#3480]
As far as I can tell, it is not possible with the current libretro vulkan API to use the validation layers because they need to be enabled on instance creation, which is done automatically by the frontend.

Or maybe I missed something?

**Comment by Themaister** [comment]
If frontend is built with make VULKAN_DEBUG=1, debug layers and callbacks are automatically added.

**Comment by julianko** [comment]
alright, that helps. thanks.

**Comment by julianko** [comment]
nvm, I figured it out.
had a problem with my vulkan SDK installation.
