### ISSUE TITLE
(Android) snes9x2010 [and perhaps other cores] missing

### ISSUE THREAD

**Issue by dr0id123** [libretro/RetroArch#3482]
http://libretro.com/forums/showthread.php?t=6755

As posted in the above forum, snes9x2010 is not available on Android devices (i.e. Shield).  This was available, though no longer is.  There are potentially other cores missing as well. 

Via BuildBot, the binary is missing:
http://buildbot.libretro.com/nightly...t/armeabi-v7a/

If I should post this somewhere else, please let me know.  Thanks!

**Comment by fr500** [comment]
If a core is not building, then it's not present.
It's not really a bug.
