### ISSUE TITLE
directory setting changes don't save

### ISSUE THREAD

**Issue by vickyorlo** [libretro/RetroArch#3493]
Whenever I change the directory where saves/savestates should be from content to something else from RetroArch and then quit, when I load it up back again it's back to the default. I ended up having to edit the .cfg file manually to get it to work.

**Comment by fr500** [comment]
saving on the last published nightly was broken and now buildbot is dead, wait a few days and try again.

**Comment by vickyorlo** [comment]
Ah, I see. Thanks.
