### ISSUE TITLE
Command line argument --save is ignored 

### ISSUE THREAD

**Issue by ReaperMantis** [libretro/RetroArch#3501]
Hello,
I believe the --save command line argument in RetroArch is broken on Windows.  SRM files will no longer be saved to the directory specified in the --save argument.  Instead, SRM files are saved to the same directory as the rom file even if the --save argument is specified..

Here are some relevant lines from the output illustrating the issue:
`C:\test\RetroArch>retroarch_debug.exe --verbose -L cores\fceumm_libretro.dll --save C:\test\saves "C:\test\roms\Kirby's Adventure (USA).zip"
RetroArch [INFO] :: Redirecting save file to "C:\test\roms\Kirby's Adventure (USA).srm".
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Sep  4 2016
RetroArch [INFO] :: Version: 1.3.6
RetroArch [INFO] :: Git: 2445931
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Config: loading config from: C:\test\RetroArch\retroarch.cfg.
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Loading dynamic libretro core from: "C:\test\RetroArch\cores\fceumm_libretro.dll"
RetroArch [INFO] :: [overrides] no core-specific overrides found at C:\test\RetroArch\config\FCEUmm\FCEUmm.cfg.
RetroArch [INFO] :: [overrides] no game-specific overrides found at C:\test\RetroArch\config\FCEUmm\Kirby's Adventure (USA).cfg.
RetroArch [INFO] :: Shaders: preset directory: C:\test\RetroArch\shaders\presets
RetroArch [INFO] :: Shaders: no game-specific preset found at C:\test\RetroArch\shaders\presets\FCEUmm\Kirby's Adventure (USA).cgp.
RetroArch [INFO] :: Shaders: no game-specific preset found at C:\test\RetroArch\shaders\presets\FCEUmm\Kirby's Adventure (USA).glslp.
RetroArch [INFO] :: Shaders: no core-specific preset found at C:\test\RetroArch\shaders\presets\FCEUmm\FCEUmm.cgp.
RetroArch [INFO] :: Shaders: no core-specific preset found at C:\test\RetroArch\shaders\presets\FCEUmm\FCEUmm.glslp.
RetroArch [INFO] :: Environ SET_VARIABLES.
RetroArch [INFO] :: Remaps: remap directory: C:\test\RetroArch\config/remaps
RetroArch [INFO] :: Remaps: no game-specific remap found at C:\test\RetroArch\config/remaps/FCEUmm/Kirby's Adventure (USA).rmp.
RetroArch [INFO] :: Remaps: no core-specific remap found at C:\test\RetroArch\config/remaps/FCEUmm/FCEUmm.rmp.
RetroArch [INFO] :: Redirecting save file to "C:\test\roms\Kirby's Adventure (USA).srm".
RetroArch [INFO] :: Redirecting savestate to "C:\test\RetroArch\states\Kirby's Adventure (USA).state".
...
RetroArch [INFO] :: Saving RAM type #0 to "C:\test\roms\Kirby's Adventure (USA).srm".
RetroArch [INFO] :: Saved successfully to "C:\test\roms\Kirby's Adventure (USA).srm".
...`

This is occurring on multiple cores.

If the full output is needed, please let me know.  I do not have access to a linux system at the moment to test it there.

**Comment by fr500** [comment]
The option is deprecated and most likely gonna be removed soon.
Use the config files instead

**Comment by ReaperMantis** [comment]
Thanks for the quick reply!

If the option is truly deprecated and will be removed in the future, it should be removed from the 'help' message and from the wiki for the next release, especially since it's not working :)

I can confirm that setting the save directory in a config file works correctly.  I rely heavily on launching from the command line and can use --appendconfig to attach a config containing the save directory.
