### ISSUE TITLE
PSP testing

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3502]
I think it's important to have a template for testing, specially on static linked and salamander platforms.
I'll keep adding stuff to the original post and the actual results on the comments.

Static linked platform testing template:
[template.txt](https://github.com/libretro/RetroArch/files/454338/template.txt)

**Comment by fr500** [comment]
Info files
- [x] Files are in the wrong location
- [x] Detect core doesn't work
- [ ] System information doesn't work

Archive support

- [ ] Browse archive shows no items
- [ ] Load from archive says no cores if using detect
- [ ] Load from archive doesn't seem to work with the cores tested so far

Core testing
Core testing has to be done in several ways due to the nature of the issues

1. cold boot

- [x] catsfc works fine
- [x] catsfc+ works fine
- [ ] nxengine crashes PSP
- [ ] gambatte crashes PSP
- [ ] fceumm crashes PSP, crashes unless another core/game was loaded previously
- [ ] quicknes crashes PSP or goes back to menu, about 50% / 50%
- [x] picodrive works
- [ ] mednafen pce crashes the PSP with cd games or cart games unless another core was loaded previously, edit: sometimes if the core is loaded manually it works
- [x] prboom takes a while to load, then works, quitting retroarch crashes the PSP afterwards
- [x] tempgba works



It would be important to review these issues on other platforms to try and fix them.

**Comment by twinaphex** [comment]
This is a good checklist template, that will be very handy thanks.

**Comment by fr500** [comment]
**Core support**
Core: FCEUmm
- [ ] load unzipped content works (core loaded) 
**black screen and then psp reboots**
- [ ] load archive works (core loaded) 
**boots back to psp xmb**
- [ ] browse and load from archive works (core loaded) 
**no items**
- [x] load unzipped content works (autodetect)
**works with small games, bigger games like Kirby crash the PSP, tried subsequent switching between MM1 and SMB1 and it worked fine**
- [ ] load archive works (autodetect)
**no cores available**
- [ ] browse and load from archive works (autodetect)
**no items**
- [ ] loading works (history)
**No playlist entries available after closing content**
- [ ] loading works (cores without content)
**n/a**

Notes: for some reason it seems loading ZELDA.NES causes crashing 90% of the time. Loading  "Legend of Zelda.nes" works fine (with detect core, the other codepaths seem to be broken on this platform)

**General core functionality**
Core: FCEUmm
- [ ] sram saving works
**save files are created**
- [ ] sram loading works
**doesn't load**
- [x] save state works
**save files are created**
- [ ] load state works
** says it failed to load even though the state is there**
- [ ] closing content works

Notes:

**Comment by fr500** [comment]
**Core support**
Core: Gambatte
- [ ] load unzipped content works (core loaded) 
**back to RGUI, no input 50% of the time**
- [ ] load archive works (core loaded) 
**boots back to psp xmb**
- [ ] browse and load from archive works (core loaded) 
**no items**
- [x] load unzipped content works (autodetect)
**black screen, home button works so PSP isn't crashed but game doesn't work**
- [ ] load archive works (autodetect)
**no cores available**
- [ ] browse and load from archive works (autodetect)
**no items**
- [ ] loading works (history)
**No playlist entries available after closing content**
- [ ] loading works (cores without content)
**n/a**

Notes:

**General core functionality**
Core: Gambatte
- [ ] sram saving works
- [ ] sram loading works
- [ ] save state works
- [ ] load state works
- [ ] closing content works

Notes: content loading doesn't work so we can't test other features

**Comment by fr500** [comment]
**Core support**
Core: Snes9x 2005 (CatSFC)
- [x] load unzipped content works (core loaded) 
- [ ] load archive works (core loaded) 
**boots back to psp xmb**
- [ ] browse and load from archive works (core loaded) 
**no items**
- [x] load unzipped content works (autodetect)
- [ ] load archive works (autodetect)
**no cores available**
- [ ] browse and load from archive works (autodetect)
**no items**
- [ ] loading works (history)
**No playlist entries available after closing content**
- [ ] loading works (cores without content)
**n/a**

Notes:

**General core functionality**
Core: Snes9x 2005 (CatSFC)
- [x] sram saving works
**save files are created**
- [ ] sram loading works
**doesn't load**
- [x] save state works
**save files are created**
- [ ] load state works
**says it failed to load even though the state is there**
- [x] closing content works

Notes: content loading doesn't work so we can't test other features

**Comment by fr500** [comment]
**Core support**
Core: Snes9x 2005+ (CatSFC plus)
- [x] load unzipped content works (core loaded) 
- [ ] load archive works (core loaded) 
**boots back to psp xmb**
- [ ] browse and load from archive works (core loaded) 
**no items**
- [x] load unzipped content works (autodetect)
- [ ] load archive works (autodetect)
**no cores available**
- [ ] browse and load from archive works (autodetect)
**no items**
- [ ] loading works (history)
**No playlist entries available after closing content**
- [ ] loading works (cores without content)
**n/a**

Notes:

**General core functionality**
Core: Snes9x 2005 (CatSFC)
- [x] sram saving works
**save files are created**
- [ ] sram loading works
**doesn't load**
- [x] save state works
**save files are created**
- [ ] load state works
**says it failed to load even though the state is there**
- [x] closing content works

Notes:

**Comment by fr500** [comment]
**Core support**
Core: TempGBA
- [x] load unzipped content works (core loaded) 
- [ ] load archive works (core loaded) 
**boots back to psp xmb**
- [ ] browse and load from archive works (core loaded) 
**no items**
- [x] load unzipped content works (autodetect)
- [ ] load archive works (autodetect)
**no cores available**
- [ ] browse and load from archive works (autodetect)
**no items**
- [ ] loading works (history)
**No playlist entries available after closing content**
- [ ] loading works (cores without content)
**n/a**

Notes:

**General core functionality**
Core: TempGBA
- [x] sram saving works
**save files are created**
- [ ] sram loading works
**doesn't load**
- [x] save state works
**save files are created**
- [ ] load state works
**says it failed to load even though the state is there**
- [x] closing content works

Notes:

**Comment by fr500** [comment]
**Core support**
Core: Picodrive
- [x] load unzipped content works (core loaded) 
- [ ] load archive works (core loaded) 
**boots back to psp xmb**
- [ ] browse and load from archive works (core loaded) 
**no items**
- [x] load unzipped content works (autodetect)
- [ ] load archive works (autodetect)
**no cores available**
- [ ] browse and load from archive works (autodetect)
**no items**
- [ ] loading works (history)
**No playlist entries available after closing content**
- [ ] loading works (cores without content)
**n/a**

Notes:

**General core functionality**
Core: TempGBA
- [x] sram saving works
**save files are created**
- [ ] sram loading works
**doesn't load**
- [x] save state works
**save files are created**
- [ ] load state works
**says it failed to load even though the state is there**
- [x] closing content works

Notes:

**Comment by fr500** [comment]
This may shed some light into these issues:

> 36:32:287 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)
36:32:339 user_main    E[FileSys]: FileSystems\DirectoryFileSystem.cpp:571 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
36:32:339 user_main    E[IO]: HLE\sceIo.cpp:1387 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/PSP/RETROARCH/CONFIG/Gambatte/Gambatte.cfg, 00000001, 000001b6) - file not found
36:32:340 user_main    E[FileSys]: FileSystems\DirectoryFileSystem.cpp:571 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
36:32:340 user_main    E[IO]: HLE\sceIo.cpp:1387 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/PSP/RETROARCH/CONFIG/Gambatte/Legend of Zelda, The - Oracle of Ages (USA).cfg, 00000001, 000001b6) - file not found
36:32:341 user_main    E[FileSys]: FileSystems\DirectoryFileSystem.cpp:571 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
36:32:341 user_main    E[IO]: HLE\sceIo.cpp:1387 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/PSP/RETROARCH/retroarch-core-options.cfg, 00000001, 000001b6) - file not found
36:32:369 user_main    E[FileSys]: FileSystems\DirectoryFileSystem.cpp:571 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
36:32:369 user_main    E[IO]: HLE\sceIo.cpp:1387 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/PSP/RETROARCH/CONFIG/REMAPS/Gambatte/Legend of Zelda, The - Oracle of Ages (USA).rmp, 00000001, 000001b6) - file not found
36:32:372 user_main    E[FileSys]: FileSystems\DirectoryFileSystem.cpp:571 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
36:32:372 user_main    E[IO]: HLE\sceIo.cpp:1387 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/PSP/RETROARCH/CONFIG/REMAPS/Gambatte/Gambatte.rmp, 00000001, 000001b6) - file not found
36:32:436 user_main    W[FileSys]: FileSystems\MetaFileSystem.cpp:116 RealPath: inPath "psp" is relative, but current directory "umd0:" is all prefix and no path. Using "/" as path for current directory.
36:32:436 user_main    W[KERNEL]: ppsspp\Core/HLE/sceKernel.h:457 Kernel: Bad object handle -2147418110 (80010002)
36:32:436 user_main    W[FileSys]: FileSystems\MetaFileSystem.cpp:80 RealPath: inPath is empty
36:32:436 user_main    W[FileSys]: FileSystems\MetaFileSystem.cpp:80 RealPath: inPath is empty
36:32:437 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:1975 291=sceKernelCreateThread(audioMainLoop, 08810384, 00000008, 65536, 00000000, 00000000)
36:32:437 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2064 0=sceKernelStartThread(291, 4, 09fbdfc8)
36:32:437 audioMainLoo W[AUDIO]: HLE\__sceAudio.cpp:333 Switching audio frequency to 48000
36:32:438 user_main    E[FileSys]: FileSystems\DirectoryFileSystem.cpp:571 DirectoryFileSystem::OpenFile: FAILED, 2 - access = 1
36:32:438 user_main    E[IO]: HLE\sceIo.cpp:1387 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(umd0:/custom.ini, 00000001, 000001b6) - file not found
36:32:471 audioMainLoo I[KERNEL]: HLE\sceKernelThread.cpp:2119 sceKernelExitThread(0)
36:32:471 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)
36:32:474 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)
36:32:503 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)
36:32:521 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)
36:32:537 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)
36:32:555 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)
36:32:570 user_main    E[HLE]: HLE\HLE.cpp:491 Unknown syscall: Module: (unknown)

**Comment by fr500** [comment]
Juan did some testing, it seems the problem started between 1.3.3 and 1.3.4
https://paste.kde.org/pp5dbewjm

**Comment by Fighter19** [comment]
btw. NXEngine is crashing when getting into the main menu, is this to be reported here, do a new issue or don't report at all?

**Comment by JuanVCS** [comment]
Tried current nightly after a while (2017-05-02) and all of radius testing remains the same.

There's also a weird bug when activating framerate display, where it appears duplicate like so:

![img_20170502_184259691](https://cloud.githubusercontent.com/assets/3089037/25644997/aba2cd3c-2f80-11e7-98cd-d5fcc6722b6f.jpg)

**Comment by fr500** [comment]
sucks... I was gonna test, thanks for sparing me the work

**Comment by ItachiSan** [comment]
Would like to work on it, especially on Nintendo cores. I do have a PSP 2xxx.
RetroArch boots properly.
So, what tools do I need to have a working developing environment? Is the PSP toolchain enough? @fr500

**Comment by fr500** [comment]
Updated 12/10/2017
**Core support**
Core: FCEUmm
- [x] load unzipped content works (core loaded) 
- [x] load archive works (core loaded) 
- [x] browse and load from archive works (core loaded) 
- [x] load unzipped content works (autodetect)
- [x] load archive works (autodetect)
- [x] browse and load from archive works (autodetect)
- [x] loading works (history)
- [ ] loading works (cores without content)

Notes: for some reason it seems loading ZELDA.NES causes crashing 90% of the time. Loading  "Legend of Zelda.nes" works fine (with detect core, the other codepaths seem to be broken on this platform)

**General core functionality**
Core: FCEUmm
- [x] sram saving works
- [x] sram loading works
- [x] save state works
- [x] load state works
- [ ] closing content works
**NO, it turns of the PSP**

**Notes:**
Sound is horrible
Selecting registration mode

**Comment by fr500** [comment]
@Fighter19 I can confirm the NXengine issue, seems input triggers the crash.

**Comment by fr500** [comment]
Updated 12/10/2017
**Core support**
Core: PCE Fast
- [x] load unzipped content works (core loaded) 
- [x] load archive works (core loaded) 
- [x] browse and load from archive works (core loaded) 
- [x] load unzipped content works (autodetect)
- [x] load archive works (autodetect)
- [x] browse and load from archive works (autodetect)
- [x] loading works (history)

**General core functionality**
Core: PCE Fast
- [x] sram saving works
- [x] sram loading works
- [x] save state works
- [x] load state works
- [x] closing content works

**Comment by fr500** [comment]
prboom doesn't work anymore

**Comment by fr500** [comment]
Updated 12/10/2017
**Core support**
Core: Prboom
- [x] load unzipped content works (core loaded) 
- [x] load unzipped content works (autodetect)
- [x] loading works (history)

**General core functionality**
Core: Prboom
- [x] closing content works

Crashes at level startup

**Comment by fr500** [comment]
Snes9x2005 doesn't work at all, it was the only core that worked before

**Comment by BenMcLean** [comment]
> Snes9x2005 doesn't work at all, it was the only core that worked before

For any PSP owners concerned about SNES emulation, I'd like to share the news that [snes9xTYL](https://github.com/esmjanus/snes9xTYL/releases) is one of the few PSP projects still receiving active development. It even supports Star Fox 2 although with a terrible framerate. But most of the SNES classics should work.

Personally, the two things I'd be most excited to see from RetroArch PSP would be the FCEUmm core, because it supports more mappers and thus more games than other NES cores, and some Gameboy Color support. I'd appreciate making those things a priority. :)

**Comment by Fighter19** [comment]
I just wanted to point out that the current version of psptoolchain has bugs, afaik. (I think some float operations aren't executed properly).
Nobody really fixed the recent GCC. I'd either revert to an older version (before the recent GCC Patch) (most of the cores are in C anyway, so C++11 support and the likes are not really required) or fix the GCC bugs on the PSP. Although I have to say I ran into issues even with the less newer GCC versions as well (It seems to work flawlessly though, as soon as no C++ code is involved). 
The only really working one, in my opinion is the one that comes with the Minimalist PSPSDK for Windows (comes with GCC 4.3.5) which lacks many features such as C11.

**Comment by BenMcLean** [comment]
> I just wanted to point out that the current version of psptoolchain has bugs, afaik. (I think some float operations aren't executed properly).

Well that explains why my attempts at getting into PSP development a few months back were failing so miserably. Thanks for the info. I'd love to find out if/when there's a version of the full psptoolchain which is fixed.

**Comment by twinaphex** [comment]
Hi there @Fighter19, thanks for the feedback. Could you tell us the exact SDK which in your findings is the most reliable stability-wise?

**Comment by Fighter19** [comment]
https://github.com/pspdev/psptoolchain/issues/85


It seems my information is slowly outdated again.
You might give his version a try. It should fix the double-precision float issue.
(The PR he opened).

Else I'd point you to a really really old version obtainable from SF (which yields the best results stability wise, imo,  but can't easily be installed on current Linux environments):
https://sourceforge.net/projects/minpspw/files/SDK%20%2B%20devpak/pspsdk%200.11.2/

**Comment by Fighter19** [comment]
Else I'd give this commit a try:

https://github.com/pspdev/psptoolchain/commit/820386024b06bb31b72ae95209a835a9f6c37a51

**Comment by fr500** [comment]
@Fighter19 I don't think we have updated the toolchain for about two years though..

**Comment by ItachiSan** [comment]
@fr500 I mostly try to use TempGBA and I had no success in loading any content.
Does it require any configuration? Would be good to make a small README for that, if needed.
I could do that, in case.

@ all: also, I can't find any instruction for installation on the website for the PSP version; would be great to report it (*e.g.* within the documents).

If I can help in any way, tell me.

**Comment by bmaupin** [comment]
I've tried a number of cores in RetroArch on the PSP and I've noticed the performance is pretty bad compared to native emulators. For example, SNES (snes9x2005), Genesis (picodrive, and even NES (only tried with FCEUmm, quicknes wouldn't run) games run very poorly.

Because this is such an old device with such a low powered CPU, is this something that can even be fixed? I'd imagine native emulators have special optimisations just for the PSP which is why they're able to run well, but I don't know enough about libretro to know whether such optimizations could be added to the cores without negatively impacting other devices.

> I mostly try to use TempGBA and I had no success in loading any content.
Does it require any configuration?

@ItachiSan Yes, it requires a GBA BIOS to be copied to /PSP/RETROARCH/SYSTEM/gba_bios.bin. It's actually one of the few cores that runs decently on the PSP, I'm guessing since it's specific to the PSP. Although even then it still has issues with some games that the native versions of TempGBA don't have (https://github.com/libretro/TempGBA-libretro/issues/4).

Thanks!

**Comment by Fighter19** [comment]
You could always backport the changes made to work on PSP so nicely to the newer versions. You can also tweak everything. The question is just if someone has the time and will to do this.
I think usually the problem is rather maintaining something like this.
I personally would love to see updated versions of emulators working properly and also performing well.

**Comment by twinaphex** [comment]
Needs to be redone again, no longer relevant.

**Comment by ItachiSan** [comment]
@twinaphex, just for curiosity, what do you mean by redone again?

**Comment by twinaphex** [comment]
These reports are from years ago and ever since we have new contributors that have taken the PSP port to new heights.

Most of the issues here need to be re-tested to see if they are still relevant or if they are issues that have long since been resolved.

Hope that clarifies it.

**Comment by ItachiSan** [comment]
@twinaphex yes, it fully does~
I think then that a new testing issue should be opened and linked to this one 😄

**Comment by bmaupin** [comment]
I don't have much free time or expertise, but I've tried to make some small improvements for PSP:

- Vice (too slow to be playable last I checked, but not something I intend to work on)
    - [Got it compiling for PSP](https://github.com/libretro/vice-libretro/pull/106)
- QuickNES (now playable at full speed on PSP)
    - [Got it working again on PSP](https://github.com/libretro/QuickNES_Core/pull/70) (had been broken for over a year)
    - [Fixed audio crackling on PSP](https://github.com/libretro/RetroArch/pull/9443) (may affect other cores as well)
- gpSP (still needs some work to be playable)
    - [Got it compiling for PSP](https://github.com/libretro/gpsp/pull/55)
    - [Got dynarec working again for PSP](https://github.com/libretro/gpsp/pull/56)
- Picodrive (mostly playable near full speed with the fast renderer)
    - [Added option for fast renderer](https://github.com/libretro/picodrive/pull/116) (makes some games playable near full framerate)

A couple others I tested:
- mGBA is too slow on the PSP to be playable and from what I understand that will probably never change due to the way it's written and the low processing power of the PSP.
- FCEUmm ran slowly as well, although I don't know enough about it to know whether it could ever run at full speed on the PSP.

I also made a couple small changes to TempGBA but I've more or less abandoned that in favour of gpSP since TempGBA is PSP only.

My only remaining plans at the moment are to get gpSP playable on the PSP. After that I'll take a break and work on something else.

**Comment by bmaupin** [comment]
I don't have much free time or expertise, but I've tried to make some small improvements for PSP:

- Vice (too slow to be playable last I checked, but not something I intend to work on)
    - [Got it compiling for PSP](https://github.com/libretro/vice-libretro/pull/106)
- QuickNES (now playable at full speed on PSP)
    - [Got it working again on PSP](https://github.com/libretro/QuickNES_Core/pull/70) (had been broken for over a year)
    - [Fixed audio crackling on PSP](https://github.com/libretro/RetroArch/pull/9443) (may affect other cores as well)
- gpSP (still needs some work to be playable)
    - [Got it compiling for PSP](https://github.com/libretro/gpsp/pull/55)
    - [Got dynarec working again for PSP](https://github.com/libretro/gpsp/pull/56)
- Picodrive (mostly playable near full speed with the fast renderer)
    - [Added option for fast renderer](https://github.com/libretro/picodrive/pull/116) (makes some games playable near full framerate)

A couple others I tested:
- mGBA is too slow on the PSP to be playable and from what I understand that will probably never change due to the way it's written and the low processing power of the PSP.
- FCEUmm ran slowly as well, although I don't know enough about it to know whether it could ever run at full speed on the PSP.

I also made a couple small changes to TempGBA but I've more or less abandoned that in favour of gpSP since TempGBA is PSP only.

My only remaining plans at the moment are to get gpSP playable on the PSP. After that I'll take a break and work on something else.

**Comment by ItachiSan** [comment]
@bmaupin how can I test the full set of cores? 😄 
May get some time now, thanks/due to the virus pandemic 😅 🤣

**Comment by bmaupin** [comment]
@ItachiSan 

In addition to the changes above, I recently made a few other small changes:

- gpSP: Add [manual](https://github.com/libretro/gpsp/pull/63) and [automatic](https://github.com/libretro/gpsp/pull/66) frame skipping
- Picodrive: [Add option to change sound quality](https://github.com/libretro/picodrive/pull/117)

The latest release of RetroArch won't have the most recent changes, but I would guess that they should be in the nightly releases:

http://buildbot.libretro.com/nightly/playstation/psp/

Stay safe!

**Comment by ItachiSan** [comment]
@bmaupin I downloaded last RA release, which was released yesterday.
Are those cores having the required fixes or not?
Also, would like to get in touch with you via other communication channels; would Discord be ok?
I feel that we are necroposting here :smile:

**Comment by Fighter19** [comment]
@ItachiSan 
As bmaupin wrote, try the nightly builds to be sure the changes are in there.
The newest release is 1.8.4 which is from January, so it probably won't have the changes.

**Comment by ItachiSan** [comment]
@Fighter19 
I think it's 1.8.5 from yesterday?
https://buildbot.libretro.com/stable/1.8.5/playstation/psp/
