### ISSUE TITLE
New user impressions using the GUI

### ISSUE THREAD

**Issue by neunenak** [libretro/RetroArch#3523]
Mentioned some of these in IRC, adding them as an issue here:
- it's possible to use the "bind default all" to screw up your keybindings such that you can no longer edit your keybindings, because you've unbound the retropad key that does this. I did this by accident trying to back out of that menu, and I ended up having to wipe my retroarch.cfg file to fix it.

-some settings don't have a help dialog that pops up when you hit select (for instance, Analog to Digital Type). also it's difficult to figure out that hitting select will open up this additional information dialog box.
- when using a keyboard and configuring core-specific keybindings, it's kind of annoying that you have to remember which virtual retropad buttons a keyboard key is bound to, and also remember what retropad buttons bind to which console controller buttons. for instance, if I want to make a certain set of keys control the the N64 analog control stick, I have to first bind those keys to some retropad control stick in the global menu, and then go into the n64-specific menu and bind those retropad keys to the analog stick. this is unergonomic.

**Comment by neunenak** [comment]
One more thing, it's super-annoying that nothing tells you if you've remapped a key to an input that also does something in the GUI. For instance I accidentally bound the same key that was being used to toggle speed to one of the C buttons, and it would've been really annoying to figure that out if I didn't happen to remember which key I had bound

**Comment by RobLoach** [comment]
There's been some improvements to the User Input settings menu. There still could be some improvements, however. Radius was working on getting a picture of the gamepad in place on there during the mapping process.

Closing this one for now, feel free to try out the updated mapping system in 1.7.3 and if you have more ideas for improvements, feel free to open up a new issue. Thank you!
