### ISSUE TITLE
Set Keybinding to Nothing

### ISSUE THREAD

**Issue by neunenak** [libretro/RetroArch#3524]
I can't use the GUI to entirely clear a keybinding, just set it to the defualt. For instance, if I wanted to make it so that no key was used to for fast forward toggle, I don't know how I would do that.

**Comment by fr500** [comment]
It's impossible atm you're right

**Comment by zoltanvb** [comment]
This is possible nowadays: controller Y, default keyboard bind 'a', or if unified menu control is not enabled, 'del' key also works.
