### ISSUE TITLE
ffmpeg compatibility issues

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#3525]
While the codecs are supported, MPG and VOB files aren't working in Retroarch.
If you change the container to something like MP4 it works.

WMV are showing only some frames (key frames?) or sometimes just crash.

MOV files have their ADPCM audio not working, playing a noise instead.

RM & RAM don't show.

**Comment by bparker06** [comment]
This is due to retroarch not associated those extensions with the ffmpeg core... I'll add those and probably some more.

**Comment by Tatsuya79** [comment]
Thanks MPG and VOB are working now.
But still I have to put "Filters unknown extensions" to OFF to see them.

**Comment by bparker06** [comment]
That would be due to the core info file needing updating with the new extensions, I'll add that as well.

**Comment by bparker06** [comment]
created pull request libretro/libretro-super#329

**Comment by Tatsuya79** [comment]
Thanks I can see them all now!
Strange as I tried to add them in the info file before but that didn't work...

**Comment by Tatsuya79** [comment]
Could animated gifs be added too? 
I know ffmpeg can convert them to videos, but can it display them in retroarch?

WMV are still problematic but perhaps that's a ffmpeg issue outside of retroarch too?

**Comment by hooby3dfx** [comment]
Was this issue fixed?
> MOV files have their ADPCM audio not working, playing a noise instead.

That may be the same as: https://github.com/libretro/RetroArch/issues/3388

**Comment by Tatsuya79** [comment]
Nope, mov sound still beeps here.
