### ISSUE TITLE
GLupeN64 fails to start due to RetroArch commit

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3529]
With the recent RetroArch master GLupeN64 will immediately crash without any error messages or log. Git bisect reveals the following RetroArch commit as the culprit.
```
$ git bisect bad
73a1cd4631ca10ca3833c8b050e083b999e44117 is the first bad commit
commit 73a1cd4631ca10ca3833c8b050e083b999e44117
Author: mudlord <mudlord@mail.com>
Date:   Tue Sep 6 15:42:16 2016 +1000

    greatly optimized modern vertex shader for ribbon.

:040000 040000 2ef14c0aedcc14c8e68fd8316a1133e1fa211e00 60929693de0c2b3dfec6a8cac9cc69bb2d1ce497 M	gfx
```
https://github.com/libretro/RetroArch/commit/73a1cd4631ca10ca3833c8b050e083b999e44117

Related issue for GLupeN64: https://github.com/loganmc10/GLupeN64/issues/39

**Comment by loganmc10** [comment]
mupen64plus-libretro seems to still work, but I suspect the difference is that GLupeN64 uses -DCORE.

The logfile shows this:
```
Shader log: 0:4(773): error: too many parameters to `vec4' constructor
```

**Comment by loganmc10** [comment]
The issue is this line:
https://github.com/libretro/RetroArch/blob/73a1cd4631ca10ca3833c8b050e083b999e44117/gfx/drivers/gl_shaders/modern_pipeline_xmb_ribbon.glsl.vert.h#L39
```
gl_Position = vec4(pos, 0.0, 1.0);
```
pos is a vec3, so vec4 should only have 2 arguments, not 3.

**Comment by loganmc10** [comment]
@mudlord

**Comment by mudlord** [comment]
https://github.com/libretro/RetroArch/pull/3531

**Comment by orbea** [comment]
Fixed, thanks.
