### ISSUE TITLE
Retroachievements not unlocking with fceumm 

### ISSUE THREAD

**Issue by Akezhar** [libretro/RetroArch#3543]
Most achievements are working fine but some wont unlock for some reason e.g.

First Hidden Treasure (Vampire Killer) 
Concealed Gold Bag (Vampire Killer) 
Concealed Meat (Vampire Killer) 

for Castlevania.

The achievements unlock properly using the RANes emulator from the Retroachievements site, there are probably more achievements that don't work, it would be great if someone could look into it.

**Comment by fr500** [comment]
Please open in the FCEumm libretro repo
