### ISSUE TITLE
core profile + CG shader is broken

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#3545]
When I try to use a CG shader (Windows with Nvidia card), with GLupeN64, which uses the OpenGL core profile (compiled with -DCORE)

I get this message:
```
[GL debug (High, API, Error)]: GL_INVALID_ENUM error generated. Operation is not valid from the core profile
```
And then:
```
RetroArch [ERROR] :: Invalid profile type
```

**Comment by fr500** [comment]
It's not broken, CG doesn't support that.

**Comment by loganmc10** [comment]
CG doesn't support OpenGL 3.1+?

**Comment by twinaphex** [comment]
Nvidia abandoned Cg at a time when core context support had yet to be added, so yeah, it's never going to work in core context mode.

This is also the reason why @Themaister is working on a new shader spec that will work for both Vulkan and OpenGL, we are living on borrowed time with the current Cg shader spec.

**Comment by loganmc10** [comment]
Hm interesting, thanks!
