### ISSUE TITLE
context_reset not being called in Windows

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#3549]
Here is a good test case:

with mupen64plus_libretro, when you toggle full screen in Linux, every time you hit "f" in the console output you'll see `context_reset.`

In Windows that doesn't happen. It should happen so that the "context_reset()" function can be called.

The result:

In Linux, toggling full screen works. In Windows, with Glide64 I just get a black screen, with gln64 it crashes.

**Comment by twinaphex** [comment]
The context_reset callback gets called here -

https://github.com/libretro/RetroArch/blob/master/driver.c#L313

I see no platform-specific code here at all that would prevent it from being called on Windows. The only way it could possibly skip calling context_reset is if video_driver_is_video_cache_context_ack returns true.

**Comment by loganmc10** [comment]
Are you able to reproduce the issue though? Try toggling full screen on Windows with mupen64plus-libretro, it doesn't work, but it works on Linux

**Comment by twinaphex** [comment]
I don't use Windows much. I rely on others to test that version.

**Comment by Monroe88** [comment]
I can only reproduce this on Windows 7 x64 with a debug build of RetroArch (make DEBUG=1 GL_DEBUG=1). The normal build does not exhibit any fullscreen toggling issues. Both builds were built with the same toolchain (MSYS2 Mingw-w64 5.3.0)

It doesn't actually crash so I can't get a gdb backtrace.

**Comment by bparker06** [comment]
@Monroe88 If it's actually exiting cleanly you could try to break on the exit or exit_group syscalls to see why it quit in the first place. I have also seen (on Linux) where no segfault seemed visible (app quit without an error message) unless it was actually run under gdb.

**Comment by loganmc10** [comment]
Ok perform this test:

Open mupen64plus in RetroArch in Windows (debug build so you can see the console output).

When you toggle fullscreen it should perform a context_reset, you should see ```context_reset.``` printed to the console output

https://github.com/libretro/mupen64plus-libretro/blob/master/libretro/libretro.c#L991

That doesn't happen in Windows. Forget the OpenGL aspect of it, the ```context_reset()``` function is obviously never even being run, since ```printf("context_reset.\n");``` is never executing.
