### ISSUE TITLE
Retroarch android compilation

### ISSUE THREAD

**Issue by Skylark13** [libretro/RetroArch#3556]
Hello,

I've been following the instructions to compile retroarch android on the wiki ( https://github.com/libretro/RetroArch/wiki/Compilation-guide-(Android-from-Linux) ) and I'm hitting errors when running `ant debug`. Output is below. Seem to be related to GLSL support -- I don't know if they're caused by a missing dependency in my build environment, or by an error in the build scripts, or something else.

I am attempting to build from a Virtualbox VM running Linux Mint. I have android-sdk-24.4.1 and android-ndk-r12b

```
$ ant debug
Buildfile: /home/guayj/Dev/libretro-super/retroarch/pkg/android/phoenix/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 25.1.7
 [checkenv] Installed at /home/guayj/android-sdk-linux

-setup:
     [echo] Project Name: retroarch
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:
     [exec] [armeabi-v7a] Compile++ arm  : retroarch-activity <= glslang.cpp
     [exec] [armeabi-v7a] Compile++ arm  : retroarch-activity <= griffin_cpp.cpp
     [exec] make: *** No rule to make target 'jni/../../../../deps/glslang/glslang/SPIRV/SpvBuilder.cpp', needed by 'obj/local/armeabi-v7a/objs/retroarch-activity/__/__/__/__/deps/glslang/glslang/SPIRV/SpvBuilder.o'.  Stop.
     [exec] make: *** Waiting for unfinished jobs....
     [exec] cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
     [exec] cc1plus: warning: command line option '-std=gnu99' is valid for C/ObjC but not for C++
     [exec] /home/guayj/android-ndk-r12b/build/core/build-binary.mk:474: recipe for target 'obj/local/armeabi-v7a/objs/retroarch-activity/__/__/__/__/deps/glslang/glslang.o' failed
     [exec] jni/../../../../deps/glslang/glslang.cpp:18:24: fatal error: ShaderLang.h: No such file or directory
     [exec]  #include "ShaderLang.h"
     [exec]                         ^
     [exec] compilation terminated.
     [exec] make: *** [obj/local/armeabi-v7a/objs/retroarch-activity/__/__/__/__/deps/glslang/glslang.o] Error 1
     [exec] /home/guayj/android-ndk-r12b/build/core/build-binary.mk:474: recipe for target 'obj/local/armeabi-v7a/objs/retroarch-activity/__/__/__/__/griffin/griffin_cpp.o' failed
     [exec] In file included from jni/../../../../griffin/griffin_cpp.cpp:176:0:
     [exec] jni/../../../../griffin/../gfx/drivers_shader/slang_reflection.cpp:16:27: fatal error: spirv_cross.hpp: No such file or directory
     [exec]  #include "spirv_cross.hpp"
     [exec]                            ^
     [exec] compilation terminated.
     [exec] make: *** [obj/local/armeabi-v7a/objs/retroarch-activity/__/__/__/__/griffin/griffin_cpp.o] Error 1

BUILD FAILED
/home/guayj/Dev/libretro-super/retroarch/pkg/android/phoenix/build.xml:102: exec returned: 2

Total time: 7 seconds
```

At a minimum, the problems are:
```No rule to make target 'jni/../../../../deps/glslang/glslang/SPIRV/SpvBuilder.cpp'```
```ShaderLang.h: No such file or directory```
```spirv_cross.hpp: No such file or directory```

Looking around, seems ShaderLang.h should come from KhronosGroup/glslang ( https://github.com/KhronosGroup/glslang ). I guess this should have been checked out into retroarch/deps/glslang/glslang ? That directory is empty in my case, which also explains why it can't build deps/glslang/glslang/SPIRV/SpvBuilder.cpp ... Should KhronosGroup/glslang have been fetched as a submodule by libretro-fetch.sh ?

I hope this is the right place to ask about this. In case the problem is in the current build scripts, this issue will lead to actual fixes in the repo, but if the problem is I was missing steps in setting up my build environment, I can update the wiki page to specify what was missing at the top of the page.

Thanks in advance.

**Comment by fr500** [comment]
You are forgetting the submodules
Try 
git submodule update --init in RetroArch's source dir.

**Comment by Skylark13** [comment]
That was exactly what was missing. I've added this to the instructions on the wiki ( https://github.com/libretro/RetroArch/wiki/Compilation-guide-(Android-from-Linux) ).

Thanks!

**Comment by Alcaro** [comment]
> Should KhronosGroup/glslang have been fetched as a submodule by libretro-fetch.sh ?

Isn't this one still an issue?

And the scripts not disabling Vulkan if submodules are gone is also an issue.

**Comment by Skylark13** [comment]
If we added fetching the submodules by libretro-fetch that would simplify the process a bit, of course. I just added a step to the instructions for android, but if this is an issue for all platforms and you can remove a step then great.

Looking into it, libretro-fetch.sh runs retroarch/fetch-submodules.sh after having fetched retroarch itself. That does:

```bash
[...]
echo "Fetching RetroArch's submodules..."
fetch_git "https://github.com/libretro/common-shaders.git" "media/shaders_cg"
fetch_git "https://github.com/libretro/common-overlays.git" "media/overlays"
fetch_git "https://github.com/libretro/retroarch-assets.git" "media/assets"
fetch_git "https://github.com/libretro/retroarch-joypad-autoconfig.git" "media/autoconfig"
fetch_git "https://github.com/libretro/libretro-database.git" "media/libretrodb"
```

No sign of glslang there. I think we could just add ```git submodule update --init``` to that script. I'll do it and submit a PR.
