### ISSUE TITLE
"leftbracket" is rendered as a "rightbracket".

### ISSUE THREAD

**Issue by neurohacked** [libretro/RetroArch#3557]
For example: 

In my *retroarch.cfg* I have assigned `input_player2_r = "leftbracket"` **[**. In RetroArch, `input_player2_r` is instead triggered by pressing **]** "rightbracket".

---
I noticed this issue while remapping keys for my X-Arcade Tankstick

I'm sure this is probably known, but for reference:

![X-Arcade Tankstick Default Keys Layout](http://i.imgur.com/Zi5nXXT.png)
*X-Arcade Tankstick Default Keys Layout*

Using the remap I mentioned above, the **[** button, right of the **E** button does not work, but pressing the **]** button, left of the **6** button, does without any mention of "rightbracket" in **retroarch.cfg**. All other remapped keys work flawlessly.

I've also confirmed the issue is not only limited to some weird incompatibility with the X-Arcade Tankstick. If I press **[** on my keyboard it does not work but **]** does, using the aforementioned `input_player2_r` remap.

**Comment by bparker06** [comment]
I assigned player2 R button to [ and used a gamepad as player 1, then ran a game with bsnes; I am unable to reproduce the issue. [ works as expected and ] (unassigned) does nothing.

**Comment by fr500** [comment]
Please reopen if there is any more information to reproduce the issue.
