### ISSUE TITLE
DETECT setting inside .lpl files for cores should be kept as is by default

### ISSUE THREAD

**Issue by bootsector** [libretro/RetroArch#3558]
I wanna be able to always select the desired core from my playlists if the entry for the core path and/or core name are set as DETECT. The thing is that retroarch updates my .lpl file with the last selected core, thus, not giving me the chance to select a new core next time for that selected game. RetroArch, could you please not touch/save my .lpl files by default? Thanks! :D

**Comment by bootsector** [comment]
Submitted a pull request that seems to fix this:
https://github.com/libretro/RetroArch/pull/3562

**Comment by fr500** [comment]
It doesn't fix it, it changes it.
It wasn't broken it was working as designed.

**Comment by bootsector** [comment]
Lazy approach. Agreed! If that's acceptable, I might come up with a new configuration option in order to make those updates optional...
