### ISSUE TITLE
(PC) Scanning directories does not add all compatible scanned games to "Game" list

### ISSUE THREAD

**Issue by RockyGateway** [libretro/RetroArch#3575]
When I scan a directory for games for any console I've tried (So far Genesis, Sega CD, 32x, Game Gear, Super Nintendo, PS1) it will pick up most of my games (For most consoles), and store them in their own library, but leave a few games out. There doesn't seem to be any sort of obvious reason for this, but these games still work if I pick the game directly from the scan menu*.

This issue is worse with the Sega CD and Game Gear games. None of the games scanned are added into their own library, but are 100% playable if I select them right after scanning.

I'm not sure if it's just me and I'm doing something wrong, or if it's a known thing. If I'm not just doing it wrong, I don't believe this to be a libretro problem. Though I don't really know a proper way to test that.

*This is another issue in itself. I have to click "No items." below the "<Scan This Directory>" option to get another toggle option named "Filter by supported extensions" in the previous menu for some reason, instead of it just being there always. Only then will games actually populate this directory, but only this directory. Should I submit another issue detailing this?

**Comment by hizzlekizzle** [comment]
We only have databases for games from the No-Intro and ReDump sets, so if your games are from other sets, they won't show up. For example, the GoodSets will likely have a lot of overlap, so many games will be found but not all of them are in the No-Intro sets, so those will be skipped. I don't think there is a Sega CD database at all currently (but I'm not 100% sure about that).

The thing about the missing filter option is indeed another issue that's worth reporting.

**Comment by RockyGateway** [comment]
Thanks for the response, I'll close this one down and open a new one with the filter issue.
