### ISSUE TITLE
Windows OpenGL context not returning the highest it can.

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#3577]
On Linux, if I use the core profile, and request and OpenGL 3.1 context:

```
hw_render.context_type       = RETRO_HW_CONTEXT_OPENGL_CORE;
hw_render.version_major      = 3;
hw_render.version_minor      = 1;
```

Then in the core if I check the OpenGL context I get:
```
OpenGL version string: 3.3 (Core Profile)
```

This is as it should be, OpenGL should provide the "best" context it can (in my case, 3.3)

On Windows if I do the exact same thing I get:

```
OpenGL version string: 3.1.0
```

On Windows, it gives you "exactly what you asked for", but it should be giving you the highest backwards compatible context that it can.

**Comment by Alcaro** [comment]
...why? If the core asks for the 3.1 feature set and gets something that supports the 3.1 feature set, what's the problem?

**Comment by loganmc10** [comment]
The requested context should be the minimum. You might have a program/core that needs at least OpenGL 3.3, but if the user can support 4.3, then you can use better features/do fancier things.

**Comment by Alcaro** [comment]
Sounds valid.

Not sure if giving the core something is the optimal solution, though; if GL 4.3 doesn't support every feature of GL 3.3, then the front can't hand out GL 4.3 even if the core would understand that.

Better solution: Add a way for the core to say "I support multiple rendering backends; give me the first available of GL 4.3, Vulkan 1.3.37, GL 4.1, Direct3D 4, none" ('none' would be softrenderer, ffmpeg supports that but GPU-accelerated colorspace conversion is faster).

**Comment by loganmc10** [comment]
I guess my point is that it should already be doing this (it works in Linux), according to https://www.opengl.org/registry/specs/ARB/wgl_create_context.txt:

```
 If version 3.1 is requested, the context returned may implement
    any of the following versions:

      * Version 3.1. The GL_ARB_compatibility extension may or may not
        be implemented, as determined by the implementation.
      * The core profile of version 3.2 or greater.
```
```
If version 3.2 or greater is requested, the context returned may
    implement any of the following versions:

      * The requested profile of the requested version.
      * The requested profile of any later version, so long as no
        features have been removed from that later version and profile.
```

I'm not sure why it doesn't work in Windows, and it's hard to find information on the Internet to suggest why it might not be. It does happen the same way for Nvidia and ATI cards though.

**Comment by Alcaro** [comment]
That spec says a request for a 3.1 context is allowed to return a 3.1 context.

We could ask for 3.3-core and fall back to 3.1 if that fails, but that feels like a rather ugly hack. And it's a complete waste of time for cores that only use the version they ask for, which I'd expect to be most of them.

**Comment by loganmc10** [comment]
True enough, I guess I'll just have it request a compatibility profile on Windows since that seems to work.
