### ISSUE TITLE
Second 3 Button controller being detected as 6 Button.

### ISSUE THREAD

**Issue by coorg** [libretro/RetroArch#3585]
I have my original 3 button controllers hooked up to a mayflash adapter.I have Retroarch (1.3.6) set to 3 button mode via the quick menu. When loading a 6 button game like street fighter II, it detects the second controller as a 6 button.
If I go back into the quick menu, and "disconnect it" by selecting a different controller option that is not supported (MD menacer), then go back to street fighter with f1, verify it is not connected, bring up the quick menu again and change it back to 3 button - it shows up as 3 button again in street fighter II.

I brought this up to Eke from Genesis Plus GX who pointed out... (https://bitbucket.org/eke/genesis-plus-gx/issues/426/bug-detecting-3-button-controllers)

> That would actually be a bug in retroarch, the core will emulate whatever controller device the libretro frontend tells him to pick through calls of retro_set_controller_port_device API() function.
> By default (i.e if the frontend does not call this function or if "Joypad Auto"is set for the input port), the core will emulate a 6-button controller for MD games that support it (there is a field in ROM header that can tell if the game support special controllers) or 3-button controller otherwise
> If a 3-button controller is emulated on port 1 and a 6-button controller on port 2 for this game, it means retroarch called retro_set_controller_port_device function for port 1 but not for port 2 or that input port 2 is set to "Joypad Auto" in input menu.
> 
> 

Both ports are not set to Joypad auto, so it seems that is the case unless there is some configuration issue I am overlooking.

**Comment by fr500** [comment]
Please specify your platform and test on current nightlies.

**Comment by coorg** [comment]
Windows > x86_64> 9/22

I've tried the latest nightly, but I can't seem to set the controller pad to md 3 button in the nightly's which makes it hard to recreate the problem. Only options for core specific controllers in the quick menu are none>retropad>unknown.

**Comment by coorg** [comment]
I've been able to upgrade a copy of my existing build to the latest nightly and can still recreate the problem. Even with 3 button selected, six button is detected. Is there some configuration I should double check?

![image](https://cloud.githubusercontent.com/assets/1631739/18771815/e3c3c29a-810f-11e6-9227-734b38c68d89.png)

![image](https://cloud.githubusercontent.com/assets/1631739/18771837/1ffbd95a-8110-11e6-9845-110179ec5b92.png)

**Comment by ekeeke** [comment]
I was wrong actually, this was a core issue, now fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/8b909e40350ffe7a85176912c60f869221f57510
