### ISSUE TITLE
Sega CD consistently loading wrong bios?

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#3598]
Hi - recently ran into an issue where my Sega CD cores will not load roms properly.

Genesis Plus EX will tell me a weird msg
![image](https://cloud.githubusercontent.com/assets/478986/18558679/f6b5401e-7b41-11e6-9d62-32d4c9583e05.png)

Pico Drive shows all bios are there,
![image](https://cloud.githubusercontent.com/assets/478986/18558564/a139f314-7b41-11e6-8c6d-86e5ac60108b.png)

![image](https://cloud.githubusercontent.com/assets/478986/18558614/c9a2b7b4-7b41-11e6-8b65-76f0f0b2cbce.png)

![image](https://cloud.githubusercontent.com/assets/478986/18558627/d96ae04a-7b41-11e6-9928-72a4326ce830.png)

I have tried a TOSEC and DW set in testing and both end up loading to this for the same USA roms.

**Comment by RobLoach** [comment]
What is the CRC of the BIOS roms you're using?

**Comment by bparker06** [comment]
Do your bioses match the suggested md5sums in your screenshot?

**Comment by futurepr0n** [comment]
Yes they do - that's why I provided the screens indicating they were present. In the core info it shows the md5 and I also checked for the wiki while getting my bios to make sure they matched on md5 as well.

**Comment by futurepr0n** [comment]
Yep 

MD5 (bios_CD_E.bin) = e66fa1dc5820d254611fdcdba0662372
MD5 (bios_CD_J.bin) = 2efd74e3232ff260e371b99f84024f7f
MD5 (bios_CD_U.bin) = 278a9397d192149e84e820ac621a8edd

**Comment by cudencuden** [comment]
hello, what game did you try with? i will try to see if i get same issue

**Comment by futurepr0n** [comment]
I have tried dark water and tosec rips of the adventures of Batman and Robin (USA) and also NHL '94. I can post my md5 or crcs but others who run them through mame seem to have no problem.

**Comment by futurepr0n** [comment]
```
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)(Track 1 of 7)[!].iso) = ef882cf89c056bdd676f7c14bdb526d0
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)(Track 2 of 7)[!].wav) = 8265156eb3741b9e90daefbc8c428a31
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)(Track 3 of 7)[!].wav) = f43cd76bb2baf9950cf37f882313fde0
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)(Track 4 of 7)[!].wav) = 9f8874465e686e4d97d5e7f4454959be
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)(Track 5 of 7)[!].wav) = 8e3e84c20d453093ee363c620bcd486e
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)(Track 6 of 7)[!].wav) = c02e8bd529d1a9c4e5cc0f0e0c44feb0
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)(Track 7 of 7)[!].wav) = fba9b62c426e1858e3b3de6550d48ee2
MD5 (Adventures of Batman & Robin, The (1995)(Sega)(NTSC)(US)[!].cue) = 094952fd53e1497891d33a71706b4191
```

and 

`MD5 (Adventures of Batman & Robin, The (USA) (DW0028).bin) = 773306bc347bd1580fc35cac9efdae02
MD5 (Adventures of Batman & Robin, The (USA) (DW0028).cue) = 979255a1af9cd41f22177ecc531a6e27
`

But this is just two different rips of the same rom and neither load

**Comment by fr500** [comment]
Feel free to keep discussing but in any case this is a core issue, not a retroarch issue.

**Comment by futurepr0n** [comment]
How is this a core issue not a RetroArch issue and what is the difference?

**Comment by futurepr0n** [comment]
I don't understand, the cores are part of RetroArch and they aren't loading properly in this case. This makes it not a RetroArch issue though?

Other emulators load the Roms properly. Would be appreciated if I could figure out how to do so through RetroArch

**Comment by fr500** [comment]
This issue tracker is about RetroArch.
This is a Genesis Plus GX issue
https://github.com/libretro/Genesis-Plus-GX/issues

**Comment by cudencuden** [comment]
on my rpi2, september 16th nightly, i launched adventures of Batman and Robin (USA) and also NHL '94 using both pico drive and genesis plus GX w/o any issue...my game is from redump set. One thing, NHL 94 keeps failing to extract...so i had to manually extract the zip archive, after that i loaded cue file fine with both core

**Comment by futurepr0n** [comment]
@fr500 thank you. I will try maybe just updating retroarch and starting from scratch again with the settings/configurations. Maybe its something that will correct itself on a reinstall.

Thanks!

**Comment by futurepr0n** [comment]
@cudencuden, I actually just tried with redump set of Batman and Robin on both Pico and Gen plus and again same wrong reigion loading issue. I wonder why this is happening. I am on OSX, using 1.3.6

 @fr500  added for fyi, in case you can help me with any direction
