### ISSUE TITLE
menu regression: phantom boolean selector is visible

### ISSUE THREAD

**Issue by bparker06** [libretro/RetroArch#3599]
Commit 3a663ba seems to be the culprit:

https://i.imgur.com/sj0cPHI.png

The extra 'off' option appears on many screens but not all of them, and it never moves or changes state.

**Comment by twinaphex** [comment]
This should fix it -

https://github.com/libretro/RetroArch/commit/9726de615bf13c8c15fbcda47c5e1f0b30b17e3a

**Comment by bparker06** [comment]
That fixes it for me, thanks.
