### ISSUE TITLE
Applying Overlay or switching the Menu Wallpaper crashes application (Retroarch Vita)

### ISSUE THREAD

**Issue by andreycout** [libretro/RetroArch#3612]
Latest nightly, all cores. Trying to apply an Overlay immediately crashes retroarch. Error message: "An error has occurred in the following application. (C2-12828-1) Saved Core File Succeeded. ux0:data/psp2ore-1474176042-0x00008b2d51-eboot.bin.psp2dmp"

Same error and crash occurs if you try to apply a Menu Wallpaper (on the GUI, go to Menu > Menu Wallpaper > Select an image > crash).

**Comment by fr500** [comment]
Applying major bug tag, all crashes are to be classified as major bug.

**Comment by frangarcj** [comment]
#3708 

I think this fixes the problem
