### ISSUE TITLE
Nestopia NTSC-filter always shows horizontal overscan

### ISSUE THREAD

**Issue by pantra64** [libretro/RetroArch#3619]
If "Blargg NTSC filter" is enabled in the Nestopia core-options, then the "Mask Overscan (horizontal)" option has no effect anymore. Even if enabled you still see the horizontal overscan area.

**Comment by Monroe88** [comment]
This is a Nestopia issue, not a RetroArch issue.

It has to do with how the NTSC filter is hardcoded to output a certain resolution. If you want a more flexible NTSC simulation, use Themaister's NTSC shader instead.
