### ISSUE TITLE
Configure script fails when compiling for OpenGL ES

### ISSUE THREAD

**Issue by escalade** [libretro/RetroArch#3626]
Using "./configure --enable-opengles --disable-kms":

`Checking function glFramebufferTexture2D in -lGL ... no
Forced to build with library -lGL, but cannot locate. Exiting ...`

From config.log:

`.tmp.c:1:19: fatal error: GL/gl.h: No such file or directory
compilation terminated.
/home/trondah/LibreELEC.tv/build.LibreELEC-RPi2.arm-8.0-devel/toolchain/lib/gcc/armv7ve-libreelec-linux-gnueabi/5.4.0/../../../../armv7ve-libreelec-linux-gnueabi/bin/ld.gold: error: cannot find -lGL
/tmp/ccBiuwBH.o:.tmp.c:function main: error: undefined reference to 'glFramebufferTexture2D'
collect2: error: ld returned 1 exit status
`

Traced it back to https://github.com/libretro/RetroArch/commit/7e87ba4dcbb655c45ddd0047066a419e24de8b9a and https://github.com/libretro/RetroArch/commit/e3c560014c6c616cccbb9d29ae565ce502991a20, with those reversed I can compile fine.

**Comment by twinaphex** [comment]
Check if this fixes anything on your end -

https://github.com/libretro/RetroArch/commit/8831d1900854930f331cb4a14aef2d155fbb7a6e

**Comment by escalade** [comment]
That fixed it, thanks :)
