### ISSUE TITLE
Load state crashes retroarch

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3633]
Tested with mgba, snes9x and nestopia.
Doesn't seem to happen on windows at least.

Tried saving a fresh state of course, loading still crashes.

**Comment by fr500** [comment]
> /RetroArch(30351): Loading state: "/storage/emulated/0/RetroArch/States/mGBA/Legend of Zelda, The - The Minish Cap (USA).state".
I/RetroArch(30351): State size: 397312 bytes.
I/RetroArch(30351): Blocking SRAM Overwrite.
I/RetroArch(30351): Saving state: "RAM".
I/RetroArch(30351): State size: 397312 bytes.
F/libc    (30351): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x4 in tid 30389 (Thread-1818)

**Comment by orbea** [comment]
`RetroArch-2016.09.21_5f9a54a_master-x86_64-1_git`

It occurs with at least snes9x and mgba on Linux too.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00000000004288da in content_flush_save_blocks (blocks=0x0, num_blocks=2)
    at tasks/task_save.c:396
396       if (blocks[i].data)
```

Full gdb log: http://pastebin.com/bBatu2xt

**Comment by fr500** [comment]
Seems to happen only when 
"Don't overwrite SaveRAM on loading"
Is enabled.

**Comment by orbea** [comment]
I have the same result, disabling `Don't overwrite SaveRAM on loading` allows me to load save states.

**Comment by orbea** [comment]
The segfault is a little different now.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff1dfcba0 in __memcpy_ssse3 () from /usr/lib64/debug/libc.so.6
```
GDB log: http://pastebin.com/v1RYbmqh

**Comment by orbea** [comment]
The latest commit fixed this here on Slackware, I'm not sure about android or windows.

**Comment by fr500** [comment]
seems fixed here.
