### ISSUE TITLE
Built-in autoconfigs no longer working

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3652]
I just tried this in windows, unzipped a fresh bundle, renamed autoconf dir. No input even though it said controller was detected.
I checked the settings and it was actually putting the settings in place but the controls don't work.
Renamed autoconf dir back and it works again.

It would be important to test this on other platforms like psp, vita, et al

**Comment by twinaphex** [comment]
I think this fixes it -

https://github.com/libretro/RetroArch/commit/b3d4fe398be5a137b80ba69ca7a7f0928e2bb07e

Builtin- autoconfigs were not broken but I accidentally used the Xbox default binds instead of the PC XInput 2 ones.

**Comment by lasers** [comment]
Close this?
