### ISSUE TITLE
emscripten: large ROMs don't work

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#3654]
When I try to load an N64 ROM only 8MB files work, anything larger and I get a "reached end of file" error

**Comment by fr500** [comment]
Yes, localStorage runs out of space.
I actually had fixed that before by switching to inMemoryFileSystem for roms but I think we need to increase the stack size, some cores stopped working when I did that.

**Comment by fr500** [comment]
should be fixed now please confirm

**Comment by loganmc10** [comment]
Yep looks good thanks!
