### ISSUE TITLE
Build failure with --enable-opengles3

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3658]
OS: `Slackware64-current`
`gcc-5.4.0`
`Max GLES[23] profile version: 3.1`

After testing `./configure --enable-opengles3 && make` I recieved this build error.
```
CC libretro-common/gfx/scaler/scaler_int.c
In file included from gfx/drivers_shader/shader_null.c:31:0:
gfx/drivers_shader/../common/gl_common.h: In function ‘gl_wrap_type_to_enum’:
gfx/drivers_shader/../common/gl_common.h:162:17: error: ‘GL_CLAMP_TO_BORDER’ undeclared (first use in this function)
          return GL_CLAMP_TO_BORDER;
                 ^
gfx/drivers_shader/../common/gl_common.h:162:17: note: each undeclared identifier is reported only once for each function it appears in
Makefile:137: recipe for target 'obj-unix/gfx/drivers_shader/shader_null.o' failed
make: *** [obj-unix/gfx/drivers_shader/shader_null.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by orbea** [comment]
Is this an issue or is it something I'm missing on my system?

**Comment by loganmc10** [comment]
I believe for it to work right you need to do ```./configure --enable-opengles --enable-opengles3```

**Comment by orbea** [comment]
Thanks for the reply. However that does not work either, but it errors differently.
```
CC gfx/drivers/gl_capabilities.c
gfx/drivers/gl_capabilities.c: In function ‘gl_check_capability’:
gfx/drivers/gl_capabilities.c:122:14: error: ‘glEGLImageTargetTexture2DOES’ undeclared (first use in this function)
          if (glEGLImageTargetTexture2DOES != NULL)
              ^
gfx/drivers/gl_capabilities.c:122:14: note: each undeclared identifier is reported only once for each function it appears in
Makefile:134: recipe for target 'obj-unix/gfx/drivers/gl_capabilities.o' failed
make: *** [obj-unix/gfx/drivers/gl_capabilities.o] Error 1
make: *** Waiting for unfinished jobs....
CC gfx/drivers/gl_renderchains/render_chain_gl_legacy.c
gfx/drivers/gl.c: In function ‘gl_copy_frame’:
gfx/drivers/gl.c:725:10: warning: implicit declaration of function ‘glEGLImageTargetTexture2DOES’ [-Wimplicit-function-declaration]
          glEGLImageTargetTexture2DOES(GL_TEXTURE_2D, (GLeglImageOES)img);
          ^
make: *** wait: No child processes.  Stop.
```

**Comment by loganmc10** [comment]
Ya this is a tricky thing with GLES3. I'm not sure how to properly deal with this. Basically there are no functions defined in "gl3ext.h" (GLES3 extensions). That function is defined in gl2ext.h, but it can be used with GLES3.

Essentially you can fix this by editing https://github.com/libretro/RetroArch/blob/master/libretro-common/include/glsym/rglgen_headers.h, and replacing ```#include <GLES3/gl3ext.h>``` with ```#include <GLES2/gl2ext.h>``` under the HAVE_OPENGLES3 define.

You may also need to go into RetroArch/libretro-common/glsym

and run ```./glgen.py /usr/include/GLES2/gl2ext.h glsym_es3.h glsym_es3.c``` and then move the generated glsym_es3.h file into RetroArch/libretro-common/include/glsym

Here is the reason why it's hard to deal with this: every platform does this differently.

On Android, inside gl2ext.h, they include gl2.h, so if you include gl2ext.h, you get gl2.h, but you actually want gl3.h + gl2ext.h (no other platform I've come across does this).

On emscripten, they actually put gl2ext.h inside the GLES3 folder, so ```#include <GLES3/gl2ext.h>```, again, they are the only platform I've seen that does this...

**Comment by loganmc10** [comment]
I guess the emscripten situation is just an #ifdef to point it to the right file, but the Android situation is quite tricky, since you can't include gl2ext.h without include gl2.h, which breaks everything, because you need gl3.h (conflicting definitions and whatnot happen)

**Comment by orbea** [comment]
Errors a little differently again.
```
CC gfx/drivers/gl_capabilities.c
gfx/drivers/gl.c: In function ‘gl_copy_frame’:
gfx/drivers/gl.c:725:10: warning: implicit declaration of function ‘glEGLImageTargetTexture2DOES’ [-Wimplicit-function-declaration]
          glEGLImageTargetTexture2DOES(GL_TEXTURE_2D, (GLeglImageOES)img);
          ^
CC gfx/drivers/gl_renderchains/render_chain_gl_legacy.c
CC gfx/common/gl_common.c
gfx/drivers/gl_capabilities.c: In function ‘gl_check_capability’:
gfx/drivers/gl_capabilities.c:124:14: error: ‘glEGLImageTargetTexture2DOES’ undeclared (first use in this function)
          if (glEGLImageTargetTexture2DOES != NULL)
              ^
gfx/drivers/gl_capabilities.c:124:14: note: each undeclared identifier is reported only once for each function it appears in
Makefile:134: recipe for target 'obj-unix/gfx/drivers/gl_capabilities.o' failed
make: *** [obj-unix/gfx/drivers/gl_capabilities.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by loganmc10** [comment]
I'm not sure why it didn't work for you, you can see/try the changes I was describing in this branch:

https://github.com/loganmc10/RetroArch/tree/gles3

That compiles for me. But again, that wouldn't compile on Android.

**Comment by orbea** [comment]
Your branch worked, I guess it was something I did wrong juggling too many tasks at once. Thanks.

I will leave this open until a good solution is found that doesn't break another platform.

**Comment by orbea** [comment]
@loganmc10 

Does this patch applied to your branch work on android? I can't test it, but it works here in Slackware.
```
diff -ur RetroArch/libretro-common/include/glsym/rglgen_headers.h RetroArch/libretro-common/include/glsym/rglgen_headers.h
--- RetroArch/libretro-common/include/glsym/rglgen_headers.h	2016-09-26 14:10:11.746988934 -0700
+++ RetroArch/libretro-common/include/glsym/rglgen_headers.h	2016-09-26 14:08:08.881162018 -0700
@@ -49,6 +49,8 @@
 #include <GL3/gl3ext.h>
 #elif defined(HAVE_OPENGLES3)
 #include <GLES3/gl3.h>
+#include <GLES3/gl3ext.h>
+#define __gl2_h_
 #include <GLES2/gl2ext.h>
 #elif defined(HAVE_OPENGLES2)
 #include <GLES2/gl2.h>
```

**Comment by loganmc10** [comment]
I'll test that in a bit but ya, that will definitely solve it, good thinking.

**Comment by loganmc10** [comment]
Well actually it should still include GLES2/gl2ext.h shouldn't it?

**Comment by orbea** [comment]
I'm not sure, I read its a potential work around here, but as I can't test it...

https://stackoverflow.com/questions/31003863/gles-3-0-including-gl2ext-h

**Comment by loganmc10** [comment]
I just tested that workaround and it does work, but your patch has:

```
#include <GLES3/gl3ext.h>
#define __gl2_h_
```

It should have:
```
#include <GLES2/gl2ext.h>
#define __gl2_h_
```

As described in the answer to that post you shared.

**Comment by loganmc10** [comment]
And actually the ```#define __gl2_h_``` needs to come first

**Comment by orbea** [comment]
So rather like this? Either way seems to work here and I admittedly just copy pasted the stackoverflow post.
```
#define __gl2_h_
#include <GLES2/gl2ext.h>
```
```
diff -ur RetroArch/libretro-common/include/glsym/rglgen_headers.h RetroArch/libretro-common/include/glsym/rglgen_headers.h
--- RetroArch/libretro-common/include/glsym/rglgen_headers.h	2016-09-26 14:10:11.746988934 -0700
+++ RetroArch/libretro-common/include/glsym/rglgen_headers.h	2016-09-26 14:25:47.973968628 -0700
@@ -49,7 +49,9 @@
 #include <GL3/gl3ext.h>
 #elif defined(HAVE_OPENGLES3)
 #include <GLES3/gl3.h>
+#include <GLES3/gl3ext.h>
 #include <GLES2/gl2ext.h>
+#define __gl2_h_
 #elif defined(HAVE_OPENGLES2)
 #include <GLES2/gl2.h>
 #include <GLES2/gl2ext.h>
```

**Comment by loganmc10** [comment]
Are you doing a ```make clean``` after you test this? make won't re-run probably when just a header file is changed. the ```#define __gl2_h_``` won't make a difference for you since that is an Android workaround, but I'm not sure how it was working with just gl3ext.h included.

**Comment by orbea** [comment]
Can you send a PR? I'm not in a good position to test compiling android or emscripten.

**Comment by orbea** [comment]
I always run `make clean` when recompiling stuff out of force of habit.

**Comment by loganmc10** [comment]
I submitted a pull request with the required changes. By the way I'm just curious, what are you working on that leads you to compile for GLES3 on the desktop?

I ran into this stuff when I was porting glupen64 to Android/GLES3, so I was testing it out on my laptop first (since compiling and testing on Android is a lengthier process) I'm just surprised anyone else has even tried this lol

**Comment by loganmc10** [comment]
I actually briefly dabbled in getting emscripten to work with GLES3 (WebGL2), to see if it would fix the issues that Smash Bros has in Glupen64, but I decided I had had enough with emscripten for a week or two...

**Comment by orbea** [comment]
The support exists so I was curious to see how well it worked with nouveau and additionally as I maintain the RetroArch slackbuild I have been considering adding functionality to the script to build with opengles in case anyone has a device where that is useful.

**Comment by loganmc10** [comment]
Makes sense, I use it quite a bit to test the GLES2/GLES3 code paths in glupen64 since it is a pain to test it on Android. I've never really run into any issues.

RetroArch GLES2 mode (./configure --enable-opengles) can actually run GLES3 cores, like glupen64 (you can compile glupen64 in GLES2 or GLES3 mode by settings "FORCE_GLES" or "FORCE_GLES3" in the Makefile).

That's how the GLES3 version of glupen64 works on Android, which is compiled for GLES2, just FYI

**Comment by orbea** [comment]
Thanks for the explanation, I noticed this behavior where GLES3 GLupeN64 worked with GLES2 RetroArch, but I know the details until now. :)
