### ISSUE TITLE
Retroarch needs a way to calibrate the analog sticks

### ISSUE THREAD

**Issue by BlackLotus** [libretro/RetroArch#366]
I know this is mainly a Gamepad bug, but we can't hope that every driver get's fixed and some sticks are more, or less sensitive than the next.But if you want to play a N64 game and you can't run (Super Mario/Zelda/...) it's really game breaking (did you ever try to walk up a little slope in Super Mario 64?)

**Comment by gyates100895** [comment]
Anyone have some luck here? Im trying to use the mayflash n64 to usb adapter but have this issue. My current idea is either add in the jscal binary to be run by udev, or to use an autoconfig to somehow tell retroarch that the analog peak is not one, but some other value (my controller peaks around .7)
