### ISSUE TITLE
Asset downloader not extracting/restarting on Linux

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#3661]
Arch x86_64
retroarch-git 1.3.6.r1585.0d95e28-1
Fresh config folder

When I go to Online Updater > Update Assets (to get the icons and fonts) it downloads according to the heads up overlay but never says extracting and never restarts to apply the assets. Manually restarting shows that the assets were in fact not extracted.

**Comment by parkerlreed** [comment]
Enabling verbosity shows why...

````
Failed to create directory: "/usr/share/libretro/assets/".
RetroArch [ERROR] :: Download of 'assets.zip' failed: Failed to create the directory.
````

**Comment by parkerlreed** [comment]
It's the AUR maintinaer :| 

https://aur.archlinux.org/cgit/aur.git/tree/default-paths.patch?h=retroarch-git

Why are the paths being hardcoded? Just consistency for the packages? This breaks the online updater.

**Comment by RobLoach** [comment]
Submit an issue to the AUR?

**Comment by t-paul** [comment]
The packager couldn't do much more than disable the update feature. A nice solution would be to have a (read-only) system and (writable) user folder, similar to what #3237 requests for the cores folder.

**Comment by parkerlreed** [comment]
@RobLoach I did :)

Also while I have you here... You sent me a memo on IRC saying my issue with Lutris was fixed. I don't remember what issue I was having. :D

**Comment by RobLoach** [comment]
Hah, glad it's fixed,whatever it was. Do you enjoy Arch? Been considering trying it out.

**Comment by parkerlreed** [comment]
@RobLoach Yeah. I mainly just use it for the more upstream software and customization (building the system how you want it)
