### ISSUE TITLE
Allow buttons to be individually configured as c-buttons in n64 cores

### ISSUE THREAD

**Issue by jvook** [libretro/RetroArch#3670]
Retroarch can't map separate buttons to the c-buttons for n64 cores.

N64 handles c-buttons with a mode switch for the A, B, X, and Y buttons, and/or mapping the right analog to C-buttons as x-axis and y-axis.  However, controllers with sufficient face buttons (including a genuine n64 controller) are not possible to configure as real c-buttons in the Quick Menu> Controls menu.

A workaround exists by setting the Right Analog stick to the face buttons in Settings>Controls>User 1, but this breaks controller settings for other cores, or requires use of a custom config or a core override.

One possibility is that If the right-analog default mappings were broken out into X+, X-, Y+, and Y-, instead of "Right Analog X" and "Right Analog Y," it would be possible to reconfigure with a core remap.

**Comment by fr500** [comment]
The real problem is that remapping doesn't work with analog sticks (no analog stick to button remapping)
Gonna close this issue and open an issue to track the problems with remapping
