### ISSUE TITLE
RetroAchievements descriptions incorrect in nightlies

### ISSUE THREAD

**Issue by Hitoshura** [libretro/RetroArch#3677]
When you access the achievements list for any game in the recent nightly builds and select any of the achievements, it only shows you the description for the first achievement, for example:

Super Mario World's first achievement is "I Believe I Can Fly - Collect a feather".  Selecting any of the other achievements for a description will still yield "Collect a feather".

Final Fantasy V Advance's first achievement is "The Chosen Warriors - Obtain the crystals from Wind temple".  Selecting any of the other achievements will still yield "Obtain the crystals from Wind temple".

The issue does not seem to occur in the latest stable build, selecting any achievements yields the proper description.  Sorry if this issue isn't of great concern!  I didn't see any relevant issues, but apologies if there is one somewhere else!

**Comment by meleu** [comment]
It's already solved. I think this issue can be closed.
