### ISSUE TITLE
SNES Achievements generating hashes that are different than RASnes9x

### ISSUE THREAD

**Issue by kabili207** [libretro/RetroArch#3678]
It seems that RetroArch is generating hashes for some SNES ROMs that don't match ones RASnes9x generates, which is causing RetroArch to fail the game id lookup. So far the only ROMs I've managed to replicate this behavior with are the BS Zelda translations (http://bszelda.zeldalegends.net/)

[BS Zelda - Third Quest](http://bszelda.zeldalegends.net/zips/thirdquest.zip)
RASnes9x: ae762f397a03fbb49a868a9204e15c0d 
RetroArch: 4e6ad56731dc15ed67df02a141178f36 

[BS Zelda - Fourth Quest](http://bszelda.zeldalegends.net/bs1m2zips/fourthquest.zip)
RASnes9x: e10907028cc97b8e8a7de73dec6dbef0 
RetroArch: 201d74a0f44d48f0d95f0153a3788c3c

[BS Zelda MottZilla ROM v0.95](http://bszelda.zeldalegends.net/rh/rh_eng.zip)
RASnes9x: 928b5c2150a48e8a66a7c193727803f0 
RetroArch: f3cc362542088fb831d584d87cc950d8 

[Ancient Stone Tablets](http://bszelda.zeldalegends.net/sekibanfiles.shtml)

Official Week 1
RASnes9x: 86a7b1f5f46821c88ae9f3521805ae25 
RetroArch: 6e39e125a98a990e5f6ee6646b122b81 

Official Week 2
RASnes9x: bc7b89f27ea46acbef8e5b97acc2c5ce 
RetroArch: 27bb88964d975f1466dcdaa00cd249f7 

Official Week 3
RASnes9x: 555ecc92f2d31dcd2483eea0f1192847 
RetroArch: e4fe9ba43bf9a7b1ac8aa396502a1011 

Official Week 4
RASnes9x: 3dbc3edc73db781c9b0ece847b442ca9 
RetroArch: f26bcdd71a9f7b7aee8c809c1cfdf815

**Comment by leiradel** [comment]
@kabili207 could you test again? There were some changes to the ROM detection code recently.

**Comment by leiradel** [comment]
I'll take a look later today.

**Comment by kabili207** [comment]
They've uploaded new translations for Ancient Stone Tablets since I originally posted the issue. Attached is a zip containing the version I used.


[bszelda_ast.zip](https://github.com/libretro/RetroArch/files/561775/bszelda_ast.zip)

**Comment by kabili207** [comment]
No longer an issue. Closing as resolved.
