### ISSUE TITLE
(3DS) Controller Swapping Strangely for Snes9x 2002, 2005, and 2005+

### ISSUE THREAD

**Issue by cheatfreak47** [libretro/RetroArch#3689]
In some games, such as Super Mario All-Stars seem to randomly swap what controller port it think's is "P1" if that makes sense. This issue I've only experienced on the 3DS, but it may actually extend to other ports of the core as well, I just haven't gotten around to checking.

For Snes9x2002, you can't really swap controller to port 2 easily (it just doesn't seem to work) 
but for 2005/2005+ you can in the menu, which enables input in the game again, but this shouldn't be necessary.

To detail how to reproduce the issue:
You open Snes9x2002,2005, or 2005+ on a 3DS,
Load a Super Mario All-Stars ROM,
Start on of the games included in the pack,
You'll noticed the game will stop receiving input.
From there, if you can change the controller in the settings to Port 2, it will begin receiving input again.

This obviously shouldn't happen, so something has to be amiss with either the emulator or the core.
Sorry if my explanation isn't particularly great, it's a rather strange issue to describe, feel free to query me for more details if needed.

**Comment by dankcushions** [comment]
this is an old issue, but IIRC it's a bug with the original game rather than emulation. see https://github.com/RetroPie/RetroPie-Setup/wiki/FAQ#does-super-mario-all-stars-work

**Comment by cheatfreak47** [comment]
@dankcushions Either way it's still not correct behavior for the game, on a real SNES the controller stays port 1, this should probably be fixed or have a workaround implemented somewhere along the line.

Other cores, such as Snes9x2010 treat the game normally, which makes this issue all the more odd.

**Comment by dankcushions** [comment]
If it works in Snes9x2010 then it can't be a retroarch issue, which is where you are now. you should log it instead against the cores themselves eg https://github.com/libretro/snes9x2002/issues
looks like it's already logged in 2005: https://github.com/libretro/snes9x2005/issues/15
no idea what 2005+ is.

**Comment by cheatfreak47** [comment]
2005 Plus is what CATSFC Plus became.

Alright I'll comment over there then
