### ISSUE TITLE
RetroArch freeze while loading save states + Corrupt stack

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3694]
OS: `Slackware64-current`
`RetroArch-2016.09.30_9392fca_master-x86_64-1_git`
`mupen64plus-libretro-2016.09.28_8528439_master-x86_64-1_git`
`GLupeN64-2016.09.29_5476ed3_master-x86_64-1_git`

I tried to open a save state made with GLupeN64 in mupen64plus-libretro and found that not only did it not work, it froze up RetroArch and caused a single cpu core to run at 100% until RetroArch was killed. A save state not working is fine, but the freeze should not happen. Loading the save state with GLupeN64 works as does loading save states made by mupen64plus-libretro in mupen64plus-libretro.

Attempting to get a backtrace of the freeze results in a corrupt stack.
```
Reading symbols from retroarch...done.
(gdb) run
Starting program: /usr/games/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/debug/libthread_db.so.1".
[New Thread 0x7fffebd17700 (LWP 9155)]
[Thread 0x7fffebd17700 (LWP 9155) exited]
[New Thread 0x7fffebd17700 (LWP 9287)]
ReadSpecialSettings: DEFAULT
ReadSpecialSettings: DEFAULT
ReadSpecialSettings: DONKEY KONG 64
^C
Thread 1 "retroarch" received signal SIGINT, Interrupt.
0x00007fffe88dd7da in ?? ()
(gdb) bt full
#0  0x00007fffe88dd7da in ?? ()
No symbol table info available.
#1  0x0000000002138e60 in ?? ()
No symbol table info available.
#2  0x00007fffdcc3c853 in add_interupt_event_count (
    type=<error reading variable: Cannot access memory at address 0xfedc>, 
    count=<error reading variable: Cannot access memory at address 0xfed8>)
    at mupen64plus-core/src/r4300/interupt.c:207
        event = <error reading variable event (Cannot access memory at address 0xfee8)>
        e = <error reading variable e (Cannot access memory at address 0xfef8)>
        special = <error reading variable special (Cannot access memory at address 0xfef4)>
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```
```
(gdb) t a a f

Thread 3 (Thread 0x7fffebd17700 (LWP 9287)):
#0  0x00007ffff6f4847f in pthread_cond_wait@@GLIBC_2.3.2 ()
   from /usr/lib64/debug/libpthread.so.0

Thread 1 (Thread 0x7ffff7fa6c40 (LWP 9151)):
```

**Comment by twinaphex** [comment]
The stacktrace doesn't show much useful info, and I doubt this is a RetroArch issue. It is a mupen64plus core issue probably.

And there are no guarantees between savestate compatibility.

**Comment by orbea** [comment]
Yea, I understand the lack of savestate compatibility, but if the savestate fails then it should do so gracefully. I can move this to the mupen64plus-libretro repo if more testing indicates its core specific.

**Comment by orbea** [comment]
Yes, this is likely a mupen64plus-libretro issue. GLupeN64 can load save states made by mupen64plus-libretro for the same game. I will recreate the issue for mupen64plus-libretro.
