### ISSUE TITLE
XMB retroactive & retroactive_marked filename's incorrect

### ISSUE THREAD

**Issue by phantomsixthplayer** [libretro/RetroArch#3696]
The following files are named incorrectly and because of that the images will display blank.
An update of the two following assets folders with name changes to the files will fix the blank image issue.

RetroArch\assets\xmb\retroactive\
RetroArch\assets\xmb\retroactive_marked\

NEC - PC Engine - TurboGrafx 16-content (E).png
NEC - PC Engine - TurboGrafx 16-content (J).png
NEC - PC Engine - TurboGrafx 16-content (U).png

Nintendo - Nintendo Entertainment System-content (E).png
Nintendo - Nintendo Entertainment System-content (J).png
Nintendo - Nintendo Entertainment System-content (U).png

Nintendo - Super Nintendo Entertainment System-content (E).png
Nintendo - Super Nintendo Entertainment System-content (J).png
Nintendo - Super Nintendo Entertainment System-content (U).png

Sega - Dreamcast-content (E).png
Sega - Dreamcast-content (J).png
Sega - Dreamcast-content (U).png

Sega - Mega Drive - Genesis-content (E).png
Sega - Mega Drive - Genesis-content (J).png
Sega - Mega Drive - Genesis-content (U).png

# Should be:

NEC - PC Engine - TurboGrafx 16 (E)-content.png
NEC - PC Engine - TurboGrafx 16 (J)-content.png
NEC - PC Engine - TurboGrafx 16 (U)-content.png

Nintendo - Nintendo Entertainment System (E)-content.png
Nintendo - Nintendo Entertainment System (J)-content.png
Nintendo - Nintendo Entertainment System (U)-content.png

Nintendo - Super Nintendo Entertainment System (E)-content.png
Nintendo - Super Nintendo Entertainment System (J)-content.png
Nintendo - Super Nintendo Entertainment System (U)-content.png

Sega - Dreamcast (E)-content.png
Sega - Dreamcast (J)-content.png
Sega - Dreamcast (U)-content.png

Sega - Mega Drive - Genesis (E)-content.png
Sega - Mega Drive - Genesis (J)-content.png
Sega - Mega Drive - Genesis (U)-content.png

**Comment by bparker06** [comment]
Hi @phantomsixthplayer, can you move this issue to libretro/retroarch-assets? That is where these files are stored.

**Comment by phantomsixthplayer** [comment]
no problem, i'll close this one here.
