### ISSUE TITLE
Softpatching doesn't work with cores that set need_fullpath = true

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#3702]
First i tried some ips on the same dir as the (not compressed) roms. Didn't work. Then i tried another ds game with bps also unzipped in the same dir. Also didn't work. Then the same with ups, ditto, then i tried command line:
retroarch -L /usr/lib/x86_64-linux-gnu/libretro/desmume_libretro.so  7th\ Dragon\ (Japan)\ [b].nds --bps ./beat.bps

Loaded the game... in japanese, didn't even try to output a error to console (all output is Desmume actually, shouldn't there be a log?)

Anyway, i can only conclude from this that this is completely broken.

**Comment by orbea** [comment]
Was this tested with the latest git master? If so can you compile again and retest?

**Comment by orbea** [comment]
It works from the menu for me, but I can't get the CLI command to work.

**Comment by i30817** [comment]
Neither from the menu or from the cli for me - with the additional information that i'm using this on linux and loading the desmume core. My version is the ppa stable one:
RetroArch: Frontend for libretro -- v1.3.6Compiler: GCC (5.4.0) 64-bitBuilt: Jul 18 2016

**Comment by orbea** [comment]
Can you try the git version to see if its been since fixed? You can do so with.
```
git clone https://github.com/libretro/RetroArch/
cd RetroArch
./configure && make
```

**Comment by i30817** [comment]
It errors out:
https://gist.github.com/i30817/e95ba53173027076b30d20eeb90a5b60

**Comment by i30817** [comment]
I'm going to ppa-purge and install the unstable packages from the other ppa instead. I'll tell you soon.

**Comment by i30817** [comment]
tried with the unstable repository, same result. To be clear i'm running this from the cmd line in the same dir as the game and the patch and both exist with these filenames and the core was installed and runs the game (just doesn't apply the patch).

retroarch -L /usr/lib/x86_64-linux-gnu/libretro/desmume_libretro.so  7th\
 Dragon\ \(Japan\)\ \[b\].nds --ups ./7th\ Dragon\ \(Japan\)\ \[b\].ups

**Comment by i30817** [comment]
Aha, with the snes9x core, from the interface it works (desmume is the same, not working). It seems only some cores are allowing it. Or maybe their inbuilt support for that is being used. But the cmd line version that is external to cores (i hope) is not working.

Also can confirm that even ips from the cmd line and on the snes9x core doesn't work.

**Comment by twinaphex** [comment]
A core has to have need_fullpath set to false. In short, a ROM needs to be completely loaded into memory by the frontend (RetroArch), only then will IPS/UPS/BPS softpatching work on the frontend level.

Cores that only receive a 'full path' instead of a pointer to a ROM buffer will need to handle IPS/BPS/UPS patching themselves inside the core if that is something they want. 

I am pretty sure Desmume is need_fullpath = true since ROMs for that system are much bigger than say NES/SNES ones.

**Comment by Alcaro** [comment]
> will need to handle IPS/BPS/UPS patching themselves inside the core if that is something they want

...how do you do that? --bps isn't passed to the core.

> I am pretty sure Desmume is need_fullpath = true

so --bps should throw error on that core, rather than getting ignored.

**Comment by twinaphex** [comment]
> "...how do you do that? --bps isn't passed to the core."

I didn't consider CLI I guess and only considered it from the perspective of starting it up from the menu.

**Comment by i30817** [comment]
I'd want a override for that 'you shall not pass' thing. It's simply false advertisement to announce a feature and then turn around and disable it silently, i don't really care if it's unwise, make it a fake config option.


There are computers being sold with 16 and 32 gb man.

**Comment by twinaphex** [comment]
Renamed it so that I don't get confused by the title, since it didn't really make sense.

**Comment by ofry** [comment]
Maybe if core have setting need_fullpath = true, but cache dir is set, try to softpatch rom/iso/smth else with output to cache dir, then load patched rom (or iso or smth like it) from cache dir?

We will not limited by size of RAM then.

**Comment by Alcaro** [comment]
Copying a 512MB file took 7 seconds on my machine. Not sure if that's an acceptable delay on every ROM load.

But it's better than nothing.

**Comment by ofry** [comment]
Not every ROM load, only if patch exist :)

**Comment by i30817** [comment]
If you do use the cache thing, a linux user can put the cache on /dev/shm and get a transparent volatile in-memory patch...
It's max limited to half the total available memory of the machine if you're worried about that. I just want a option to force the patching.

Anyway, i wasn't clear about it, there is another bug, of the cmd line version of the ips patches not working even on 'supported' cores like snes9x.

**Comment by i30817** [comment]
I also had a somewhat crazy idea that probably is unfeasible now and probably impossible with some patch formats: a overlay filesystem that transparently patches read bytes when requested so it doesn't need to be done all at once.

I'm pretty fascinated by the linux support for pluggable,composable filesystems. Overlayfs is pretty cool.

**Comment by orbea** [comment]
I'm going to close this in favor of issue https://github.com/libretro/RetroArch/issues/2878 which has less noise and was made first.
