### ISSUE TITLE
Small problem if you make your "file browser dir" a directory on a filesystem that can be unmounted 

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#3703]
Retroarch will show no options to go elsewhere until you configure a new dir or mount it. 
Not even back to a 'default' dir so you can navigate ($HOME for example).

On the file browser screen you can only cancel (and it's good that you can at least cancel, otherwise the bug would be much worse).

**Comment by bparker06** [comment]
fixed in de3081b.

**Comment by i30817** [comment]
fixed.
