### ISSUE TITLE
Question about Pcsx rearmed on vita (eboot.pbp)

### ISSUE THREAD

**Issue by Fadi5555** [libretro/RetroArch#3706]
Hi there. Well I have many ps1 games on eboot (PBP) extension. So how make retroarch (pcsx) run these pbp files or at least how can we show this manu please.

![image](https://cloud.githubusercontent.com/assets/10546081/19020308/dd67d756-88ad-11e6-9165-b0a155760195.png)

I also saw a video on YouTube about playing PBP games on pcsx but it didn't show PBP files on me
This is a video:
https://m.youtube.com/watch?v=4Qi_EAN51Ss
Thanks

**Comment by twinaphex** [comment]
No idea what you're talking about, PBP files can be loaded just fine.

Also, RetroArch version 1.1 is very old by now. I'd recommend upgrading, the latest version is 1.3.6

**Comment by Fadi5555** [comment]
I have the latest version of pcsx on my vita and this video is like example about what I want from you to see.
I have many PBP files (ps1 games) but retroarch is not recognized them. What is the method to show them please?

**Comment by dankcushions** [comment]
your video shows .PBP games in your list and then you load one??

**Comment by Fadi5555** [comment]
This is not my video. I took it from YouTube. The pcsx is on the latest version but unfortunately it didn't show my PBP files at all.
Can you help me please?
