### ISSUE TITLE
64bit-portability-issue

### ISSUE THREAD

**Issue by krysanto** [libretro/RetroArch#3718]
Hello, after compiling retroarch v.1.3.6 and v.1.3.5 using the opensuse build service I get the following error: E: retroarch 64bit-portability-issue gfx/drivers_context/xegl_ctx.c:350

The latest version I can successfully compile is v.1.3.4
I couldn't find out more about the error, so here's the build log.

[_log.txt](https://github.com/libretro/RetroArch/files/505690/_log.txt)

**Comment by Alcaro** [comment]
Dear lord, what a huge lot of crap in that log. And I can't find where it fails, warnings are by definition not errors. And it's not a 64bit issue in the first place, 'long unsigned int' is 64 bits.

As far as I remember, EGLNativeWindowType changes depending on which headers are included in which order, making it a pretty nasty mess. I tried cleaning it up, but couldn't figure out what it's doing.

**Comment by krysanto** [comment]
Yes, I figured I'll send the whole log in case in helps you guys more. The only relevant part is line 1326 which simply states: E: retroarch 64bit-portability-issue gfx/drivers_context/xegl_ctx.c:350

I don't think this is meant as a warning, infact warnings are listed in line 1325

**Comment by Alcaro** [comment]
> The only relevant part

Also relevant: 1142-1149, `gfx/drivers_context/xegl_ctx.c:350:40: warning: passing argument 2 of 'egl_create_surface' makes pointer from integer without a cast [-Wint-conversion]`/etc. Clearly your build system is SOMEHOW promoting a warning to an error.

**Comment by krysanto** [comment]
Alright, sorry to bother you then.
