### ISSUE TITLE
For some reason the database is showing some wrong values here

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#3720]
ps1 thousand arms cd 1 (USA) SLUS-00845 is showing up as with name: "Thousand Arms (Japan) (Disc 2) after scanning its directory.

snes Clock Tower (Japan) is outright missing after snes directory 'scan directory'. The rom is not hardpatched and loads (softpatching with the aeon genesis ips file) if loaded from 'Load Content -> Select File and Detect core' instead.

These are the ones i noticed, no doubt there are more.

A question if you will, are you forbidding hardpatch romhacks and patched images from showing in the playlists after 'scan directory'? It doesn't seem so, since my own shows 'Brigantine - Grand Edition' which is a hardpatch. (even if mednafen crashes right away now that i tried it with 'CDIF_ReadSector() invalid sector type at LBA=22' lol).

Also Sega Mega CD are not showing at all.

**Comment by bparker06** [comment]
That title indeed has the wrong serial in the database, the dat file here confirms that: https://github.com/libretro/libretro-database/blob/master/dat/Sony%20-%20PlayStation.dat

Currently for PS1 titles as long as the serial matches, then it should scan without issues.

I made a quick script to check this dat for titles with serials belonging to the wrong region, and here is what it found:

Thousand Arms (Japan) (Disc 2) = SLUS-00845
NBA in the Zone '98 (USA) = SLES-00171
Goal Storm '97 (USA) = SLES-00069
Thousand Arms (USA) (Disc 1) = SLPS-01781

**Comment by RobLoach** [comment]
The Serial matching vs CRCs could likely be a cause as well. Likely a candidate as to why Mega CD doesn't scan.

**Comment by ofry** [comment]
Many items from Sega Dreamcast romset has incorrect data.

Example:

C:\Users\ofry\Downloads\DC_games\90 Minutes - Sega Championship Football v1.009 (2001)(Sega)(PAL)(M5)[!].7z#90 Minutes - Sega Championship Football v1.009 (2001)(Sega)(PAL)(M5)[!].gdi
Treasure Strike (Japan)
DETECT
DETECT
468C1495|crc
Sega - Dreamcast.lpl

etc, etc, etc.

Link to full playlist: https://dl.dropboxusercontent.com/u/97349870/Sega%20-%20Dreamcast.lpl
(pal games only, some entries removed (because I don't know german, french, italian languages xD and I have these games in english language)

**Comment by orbea** [comment]
@i30817 and @ofry Can you please bring up any further database issues in the correct issue tracker so they might get fixed?

https://github.com/libretro/libretro-database/issues

Thanks!

**Comment by i30817** [comment]
This is a old issue that was fixed there, i had forgotten about it.

Though there is still a issue like it open there but that is because one game has a wrong serial from factory and retroarch is using serials to identify instead of checksums (this has other issues like the issue i recently opened about duplicate info).

**Comment by orbea** [comment]
Thanks for the update!
