### ISSUE TITLE
Add "Remove" under recently played games.

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3723]
I played some games. Some games are very short, just too awful, just too hard, unplayable, in different languages, or any another reason for deletion. My suggestion is to add "Remove" under recently played games... Right under Run.

![out](https://cloud.githubusercontent.com/assets/852504/19042235/d7b0153c-8950-11e6-8643-32cf98134855.png)

**Comment by twinaphex** [comment]
We already have this in the nightlies. It's called 'Remove From Playlist'.
