### ISSUE TITLE
RetroArch eats the letter z. 

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3724]
Searching for a game... Typing zelda will only get you elda. It won't let me zzz.

**Comment by twinaphex** [comment]
Yes, this is a bug in the menu system's 'keyboard handling'. z is bound to the RetroPad 'Back' button, but at the same time when we are in key input mode, z should be able to be inputted. So right now the 'retropad' mappings are getting in the way when we are using the keyboard for text input with the menu.

**Comment by lasers** [comment]
RetroArch like to spit out too... When typing `sgx` in a search prompt, it'll spit out `sgx1`.

**Comment by lasers** [comment]
Thank you for fixing this. :-)  Closing.
