### ISSUE TITLE
Choosing "Apply Cheat Changes" Freezes Retroarch (MacOS 1.3.6)

### ISSUE THREAD

**Issue by ninjapocalypse** [libretro/RetroArch#3727]
I'm running MacOS Retroarch 1.3.6 on a 2015 Macbook (I've tried both the stable release and the 10-3-16 nightly). Retroarch freezes after I toggle a cheat to "on" and select "Apply Cheat Changes" (it doesn't seem to matter what game, core, or cheat I select). After freezing, the application can only be closed with Force Quit. 

Logs ([Pastebin](http://pastebin.com/UJ5bqDN6)) don't seem to show anything wrong; it doesn't log anything after I turn a cheat on (nothing is logged when selecting "Apply Cheat Changes").

**Comment by jvook** [comment]
This user also confirmed behavior on latest nightly: https://www.reddit.com/r/RetroArch/comments/55p3n4/cheats_are_not_working/?st=ityvzzxt&sh=eea76eb4
