### ISSUE TITLE
(XMB) Ribbon improvements

### ISSUE THREAD

**Issue by kivutar** [libretro/RetroArch#3732]
The ribbon is currently using a tubular mesh + displacement vertex shader based on a noise function.

What about using a flat mesh, and applying this to create the wave? http://http.developer.nvidia.com/GPUGems2/gpugems2_chapter07.html

This video shows how to do it in Blender: https://www.youtube.com/watch?v=7L8e9FIvCF4

**Comment by Kivutar** [comment]
![simplified](https://cloud.githubusercontent.com/assets/442722/19153462/f71ea464-8bd6-11e6-8609-6936741f407a.png)

I got this result by tweaking the shader, using additive blending, enabling MSAA, and augmenting the number of vertices.

I know we don't want MSAA enabled all the time, so we could use a second pass with FXAA.

You can check the changes there: https://github.com/lakkatv/RetroArch/commit/74cf36dbda22e8f86b6f808c5c0b093492b8a530

**Comment by hizzlekizzle** [comment]
dang, that looks really good, kivutar :O

There's a good GLSL port of FXAA in the slang shaders repo:
https://github.com/libretro/slang-shaders/blob/master/anti-aliasing/shaders/fxaa.slang

**Comment by orbea** [comment]
@kivutar Is there still much room for improvement in the ribbon shaders?

**Comment by hizzlekizzle** [comment]
i'm going to close this, as I think we've done about as much as we can with the ribbon.
