### ISSUE TITLE
Improve the video player on ARM dev boards

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#3742]
Playing videos is a feature shared by many game consoles since the PSP. The software rendered ffmpeg core is too slow to decode videos on plaftorms like the Raspberry Pi.

We can read the code of omxplayer.

Or we can make a core that uses the video player abstraction of KODI, and then use the video backends of KODI.

**Comment by twinaphex** [comment]
Kodi/XBMC is just an mplayer frontend which is just ffmpeg under the hood. We should stick with our ffmpeg core and just add video decoding hardware acceleration support.

**Comment by Kivutar** [comment]
IIRC, they have an abstraction for video players that allows them to use ffmpeg or omxplayer or retroplayer. But I'm not 100% sure about it.

**Comment by deltabeard** [comment]
ffmpeg has support for hardware acceleration on the Raspberry Pi according to this [tutorial](https://github.com/legotheboss/YouTube-files/wiki/(RPi)-Compile-FFmpeg-with-the-OpenMAX-H.264-GPU-acceleration).
Adding a check for compiling for the Raspberry Pi could be added to the ffmpeg libretro core to add the required configure switches.

Apologies if bumping this is not appreciated.
