### ISSUE TITLE
fullscreen toggling malfunctions on dri2 xf86-video-intel driver

### ISSUE THREAD

**Issue by zeromus** [libretro/RetroArch#3752]
I'm attempting to compile a bunch of data into one bug ticket.

dviola is using the dri2 xf86-video-intel driver. He has problems toggling in and out of fullscreen multiple times (using F hotkey). What happens is the first time you try to return from fullscreen, it doesn't actually work; and moreover the video is frozen (but the audio continues.) Toggling again (the user thinks, to return to fullscreen) resumes normal operations. The cycle repeats. Keeping that in mind will help in understanding the following video of the problem:

https://dl.dropboxusercontent.com/u/6005119/VID_20161005_124021.mp4

Reportedly, some users forced to use dri2 on account of their hardware not supporting newer, have enjoyed using retroarch, but they're not sure whether they ever provoked the problem by toggling repeatedly.  I'm not confident they remember which cores they were using all that well, either.

On the affected systems (is it ALL systems with this dri2 driver?) the dri3 driver will work OK. It is difficult to compare retroarch functionality to other retroarch video drivers because "with sdl2 I can't even toggle fs". Using the Using sdl_gl retroarch video driver yields the same problem--but maybe sdl has the same bug?

Other programs which toggle fullscreen don't exhibit this problem: mpv (others?)
But Orbea's seen it happen in other programs (right?)

_ODDLY_, it will be a core like GPGX which exhibits this problem; mupen does not. (a longer list please?). This suggests certain investigatory steps. The set of cores which exhibit this problem haven't been reliably corroborated yet.  For reference, the mupen core uses what's likely to be a large variety of GL apis for 3d rendering, and GPGX uses none. Retroarch is still using them for its main presentation, of course.

Finally, and **importantly**, the problem does not happen unless retroarch has been using vsync!!  This has led to much (unfruitful) speculation that the essential problem is a vsync signal being stuck in the pipeline and gumming up the works. We tried unsuccessfully to turn off vsync before toggling FS/window. I'm not completely satisfied by our efforts.  Note that retroarch does set swap interval to 1 repeatedly when toggling windowmode and fullscreen. Is this redundant or necessary? Don't know.

dviola bisected the driver to find this commit; the driver authors aren't impressed: https://bugs.freedesktop.org/show_bug.cgi?id=96767#c22 (see also https://bugs.freedesktop.org/show_bug.cgi?id=93844 )

Elsewhere, the driver author muttered something enigmatic: "somewhere between the window being destroyed by the client and it actually being unmapped." This led Orbea to do an API trace and discover the following (which enygmata has seen before):

```
17005 @0 glXDestroyWindow(dpy = 0x56324d72fda0, window = 48234499)
17005: warning: unsupported glXDestroyWindow call
17010 @0 glXCreateWindow(dpy = 0x56324e6d06a0, config = 0x56324d838000, win = 41943042, attribList = {}) = 41943043
```

I speculate that if a window were 'mapped' while destroyed, it could cause malfunctions on some drivers (and not others) since it sounds like weird/undocumented behaviour.  That's what this warning would be about. This would be an easy experiment. However we haven't done much experimenting along those lines.

Tried this: http://ix.io/1uiL/diff  (also tried only commenting out the if(!fullscreen))

**Edit**: It seems retroarch is using a windowed fullscreen approach by default. These users may have been using that--true fullscreen might not be involved at all. But by now we have tried it with windowed fullscreen enabled and disabled, though. Also note the problem occurs whether the toggling is in ABABAB order or BABABA order.

**Comment by orbea** [comment]
I've seen it with at least xscreen-saver too, not nearly as consistently as with RetroArch though. I'm sure other things have triggered it, but I've been experiencing it a while and have never really bothered to look into it due to its previous irregularity.

**Comment by zeromus** [comment]
We're evaluating this patch
http://ix.io/1uj4/diff
But with `usleep(1000000/30);` instead.
Rationale:
```
//To work around a bug on xf86-video-intel driver (https://github.com/libretro/RetroArch/issues/3752)
//we can sleep for a while here. Sleeping 1/500 of a second for instance does not suffice.
//Sleeping for what should be 1 refresh on anyone's monitor cures it.
//This is not necessarily the best place for this workaround, but it works here
```

**Comment by diegoviola** [comment]
`usleep(1000000/30);` in `gfx_ctx_x_destroy_resources` makes the problem go away for me.

**Comment by orbea** [comment]
This also worked for me.

**Comment by Themaister** [comment]
How about a full XSync() before teardown?

**Comment by diegoviola** [comment]
@Themaister where should I add the XSync() exactly?

**Comment by diegoviola** [comment]
I tried adding `XSync(g_x11_dpy, False);` in the same place where I had the `usleep` but it didn't work. Same problem.

**Comment by diegoviola** [comment]
@Themaister I tried this, it didn't work, I'm also not sure where you wanted me to add the `XSync()`.

**Comment by zeromus** [comment]
https://dl.dropboxusercontent.com/u/6005119/retroarch/mupen.out.txt
https://dl.dropboxusercontent.com/u/6005119/retroarch/gpgx.out.txt

Here we see valgrind output from doing a fullscreen toggling scenario with both mupen (no bug) and gpgx (bug). Valgrind is showing misbehaviours for the bug case only. We should fix these before proceeding with investigating the driver business.

**Comment by diegoviola** [comment]
If it is of any help, I created this trace with apitrace for reproducing the problem:

https://dl.dropboxusercontent.com/u/6005119/retroarch/retroarch.trace

**Comment by diegoviola** [comment]
https://dl.dropboxusercontent.com/u/6005119/retroarch/retroarch.trace.xz

**Comment by diegoviola** [comment]
So I found the only libretro core that doesn't have this problem is mupen64plus_libretro, which when I toggle fullscreen with F I see this in the output:

context_reset.
GL_ARB_texture_non_power_of_two supported.

I looked for context_reset in the mupen64plus_libretro code and noticed it's implemented here:

https://github.com/libretro/mupen64plus-libretro/blob/master/libretro/libretro.c#L996

Why do the other cores don't implement a context_reset? Could this have anything to do with this problem?

I also tried removing this context_reset from the mupen64plus_libretro but I only got this core to crash when I did that, I was trying to see if I could get mupen64plus to hang like the other cores after taking this function apart.

**Comment by diegoviola** [comment]
So since the only libretro core that doesn't exhibit this problem is mupen64plus_libretro, I noticed this while toggling fullscreen with this core:

```
context_reset.
GL_ARB_texture_non_power_of_two supported.
```

I looked for context_reset in the mupen64plus_libretro code and noticed it's implemented here:

https://github.com/libretro/mupen64plus-libretro/blob/master/libretro/libretro.c#L996

Why do the other cores don't implement a context_reset? Could this have anything to do with this problem?

I also tried removing this context_reset from the mupen64plus_libretro but I only got this core to crash when I did that, I was trying to see if I could get mupen64plus to hang like the other cores after taking this function apart.

**Comment by zeromus** [comment]
As I'm sure I explained to you about 1000 times, the non-3d cores are simpler codepaths and aren't doing anything wrong because there is no need for a non-3d core to have anything to do with 3d.  Looking at the differences in mupen vs the other cores is a good approach for gathering information, but it can't possibly point to something wrong in the other cores.

**Comment by diegoviola** [comment]
Could this be related?

https://github.com/libretro/RetroArch/issues/3549

**Comment by diegoviola** [comment]
Adding a `glXSwapBuffers(g_x11_dpy, x->g_glx_win);` before `glFinish()` cures the freeze also.

https://github.com/libretro/RetroArch/blob/master/gfx/drivers_context/x_ctx.c#L110

**Comment by orbea** [comment]
This was fixed here too, thanks!
