### ISSUE TITLE
(regression) xdg-screensaver does not suspend screensaver properly

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#3753]
OS: `Slackware64-current`

When using RetroArch with `--disable-dbus` and xdg-screensaver it will fail to suspend xscreensaver properly. It will work some of the time, but eventually stop and the screensaver or screen lock will activate when playing a game. This can be reproduced easiest by compiling without dbus and then setting your screensaver to activate after ~1 minute, after a little while it will activate.

I bisected this and found the bad commit.
```
a061b4a80122f252b4529d20080db547ebae725b is the first bad commit
commit a061b4a80122f252b4529d20080db547ebae725b
Author: Bastien Nocera <hadess@hadess.net>
Date:   Fri Sep 16 13:00:43 2016 +0200

    x11: Implement xdg-screensaver uninhibition

:040000 040000 274b2d90b13494902d38845940c3bad6d5c2f481 a5e34c6eaaf1e7d1e7537831f38099f91e02b79f M	gfx
```
https://github.com/libretro/RetroArch/pull/3601/commits/a061b4a80122f252b4529d20080db547ebae725b

Related:
https://github.com/libretro/RetroArch/pull/3601
https://github.com/libretro/RetroArch/pull/3593

@hadess Can you take a look at this?

**Comment by twinaphex** [comment]
Yeah it seems like those changes broke screensaver suspend with xdg, that is definitely very bad and should be resolved.

**Comment by hadess** [comment]
It might be because nobody tested it? I don't even remember compile testing it, and I said as much in the original bug. I think #3601 was pretty clear on that.

**Comment by orbea** [comment]
Yes, that is why it was unnoticed, but how about how to fix it? :)

**Comment by twinaphex** [comment]
Another issue is this adds a noticeable delay to RetroArch startup.

**Comment by orbea** [comment]
You could just revert all the dbus changes entirely and then tell the few gnome3 users who were experiencing the original xdg-screensaver issue to install xprop or use a third party tool such as caffeine-ng. It'd fix this and reduce abstraction in the screensaver disabling code. The dbus code also seems to be working inconsistently for users (?).

**Comment by hadess** [comment]
It would be great if somebody could test it, instead of throwing everything away. I don't have a setup to build or run RetroArch right now, but I'd be happy to assist anyone willing to help with the building/testing.

**Comment by twinaphex** [comment]
Right now it's worse than what was before, you cannot rely on somebody else to debug your code, this should have been done by you instead.

I will give it two days for you to look at this before I will ultimately make a decision.

**Comment by hadess** [comment]
That comment is even worse than the one I received as a mail notification.

> inconveniencing us who had no need for your GNOME 3 shenanigans

That's a freedesktop standard, which I worked on so that people didn't have to rely on xdg-screensaver. It has nothing to do with GNOME 3.

> I will give it two days for you to look at this before I will ultimately make a decision.

I offer code up for review, which you don't even test, and I'm being sent ultimatums? You can revert all that merge, reopen my original one, and ask for help reviewing it.

> tell the few gnome3 users who were experiencing the original xdg-screensaver issue to install xprop

That'll work nicely under Wayland (not).

**Comment by twinaphex** [comment]
I'm not giving you ultimatums. 

But seriously though, why can't you get to the bottom of this yourself? Why must I suddenly get involved here? It was working perfectly fine before. Is the issue that you don't have xdg-screensaver installed?

I am fine with reverting the merge and you sending another PR again where this time you request for comment (add RFC to the original title or something) that way we will know not directly to merge.

**Comment by hadess** [comment]
Typo when adapting the x11_suspend_screensaver_dbus() code it seems. Does that fix it for you?

```
diff --git a/gfx/common/x11_common.c b/gfx/common/x11_common.c
index 41bc6ac..814a49a 100644
--- a/gfx/common/x11_common.c
+++ b/gfx/common/x11_common.c
@@ -347,7 +347,8 @@ void x11_suspend_screensaver_xdg_screensaver(Window wnd, bool enable)
 {
    if (enable)
       xdg_screensaver_inhibit(wnd);
-   xdg_screensaver_uninhibit(wnd);
+   else
+     xdg_screensaver_uninhibit(wnd);
 }
 
 void x11_suspend_screensaver(Window wnd, bool enable)
```

Nothing to do with the D-Bus codepath, or "GNOME 3 shenanigans" in any case.

**Comment by hadess** [comment]
We debugged this on IRC, and I mistakenly thought that the "enable" arguments were to signal whether or not to enable the screensaver inhibition. This is wrong though, "enable" is whether or not the configuration says to try and disable the screensaver.

I don't know whether that value can change at runtime, but I would expect it to be enabled by default, and the old code expected the inhibition to run for as long as the front-end was running.

**Comment by hadess** [comment]
On top of the above, I also made the assumption that this portion of the code was only going to be used by a single caller, the front-end window for example, not by every game/core. So global variables aren't such a great idea.

**Comment by orbea** [comment]
@t-paul seems to have fixed both xdg-screensaver the the start up delay, thanks.

**Comment by hadess** [comment]
> @t-paul seems to have fixed both xdg-screensaver and the start up delay, thanks.

That means that the xdg_screensaver_uninhibit() call was the one creating the hang, not the D-Bus codepath. I'll fix the D-Bus handling of "enabled" separately.

**Comment by orbea** [comment]
Yea, that is what we get for submitting/merging untested code.
