### ISSUE TITLE
XMB confirm button needs to be 'unpressed'

### ISSUE THREAD

**Issue by zeromus** [libretro/RetroArch#3758]
(tested in latest nightly with keyboard in linux and windows x86, and with xinput pad on windows x86)

When using the confirm button in XMB, it needs to be 'unpressed' after each action. For instance, positioning the cursor at Load Content and _holding down_ the confirm button should not result in an unending animation. The menu should see the button pressed, accept it as an action, descend into the submenu, and 'unpress' the button. The button would then need to be pressed again to choose 'select file' or 'select file and detect core' etc.

The same applies to the cancel button. 

Compare to the PS3 XMB.

**Comment by Kivutar** [comment]
I agree. Arrows should be repeatable. OK and CANCEL should not.

**Comment by Tatsuya79** [comment]
I noticed it too on win7 x64.
I keep launching stuff directly instead of seeing this "Run / Remove / Info" step in playlists.

**Comment by bparker06** [comment]
fixed in 2f74324.

**Comment by Kivutar** [comment]
Thanks for the fix. I tried it.
