### ISSUE TITLE
[Feature request] Rescan playlist data

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#3762]
This feature would scan existing items from this playlist only! And it would give them actual info from databases.

Why this feature need? Because databases contain some errors. So, if some errors in referensed databases will fix, I want to rescan my playlist to fix these errors in playlist data.

**Comment by i30817** [comment]
Scanning usually looks for directories or files right? Can't you just reuse the scan function on the affected files? To not have to scan everything again which might be inconvenient for big cd games collections.

**Comment by ofry** [comment]
Test case:

1) Full romset of Sega Dreamcast, each rom in separated *.7z archive.
And weak hardware:
CPU: Intel Core 2 Quad Q9505
HDD: WDC WD20EARX-00PASB0

Scan of this collection take more than 4 hours and my PC isn't responding almost all of this time. Active time of HDD when running scan was 100% almost all of time.

@i30817 I mean this will be new option. So we can choice between "normal scan" of same folder, and this "rescan".

**Comment by i30817** [comment]
But why? If the objects created by the first scan include the version number of the row in the database, everything else that was not modified can be skipped on a single command.

**Comment by RobLoach** [comment]
You can re-scan the content directory recursively.
