### ISSUE TITLE
Immediate netplay desync in X-Men 2 for Sega Genesis

### ISSUE THREAD

**Issue by gnutechs** [libretro/RetroArch#3773]
As soon you start the game in netplay, unless you're lucky and both get the same characters, you will be desynced from the other player because of the game selecting random characters immediately.

Happens in both PicoDrive and Genesis Plus GX.

**Comment by hizzlekizzle** [comment]
are you using the latest nightly? I believe some of the work Yahweasel has been doing should push a savestate out from the server to the client, which would alleviate determinism-based desyncs like this one.

**Comment by gnutechs** [comment]
This is no longer an issue for me in the latest nightly.

**Comment by hizzlekizzle** [comment]
Sweet. Thanks for verifying :)
