### ISSUE TITLE
View full text without losing thumbnails.

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3775]
Feature Request: An option (or a solution/challenge) to view full text without losing `Thumbnails` option... and not having the texts over the thumbnails either (ugly).

Scrolling text is nice, naturally slow as intended, but gets annoying over time waiting on couple of lines to be finished before you find the one with certain region you want to play on.

There is also comfort in seeing full text everywhere. I like having everything out in the open and immediately know which content to select without waiting on each scrolling text. 
This may require a little playing around first to see if we can get best of both worlds.

![out4](https://cloud.githubusercontent.com/assets/852504/19259633/0864201c-8f49-11e6-8254-b604bb06cf29.png)

**Comment by lasers** [comment]
Possible bug: Under cheat options, the scrolling text is always toggled on... with or without the thumbnails. Having an option to toggle on full text would make it much easier to toggle on/off desirable cheats for this game and all games in the future.

![out5](https://cloud.githubusercontent.com/assets/852504/19262451/b158ea1e-8f5c-11e6-86d2-c38e6d983d3b.png)

**Comment by C-Fu** [comment]
I suggest we move the thumbnail a bit higher than the middle, and put the
full text/filename/title below the thumbnail. Possibly a full description -
year, rom id, description, etc
