### ISSUE TITLE
in game rgui dynamic wallpaper crossfades with game

### ISSUE THREAD

**Issue by farlsmagee** [libretro/RetroArch#3777]
First post here. gimme a break if it's not great.

I have an issue with the nightly build from 10/2. I have 
1. dynamic wallpaper turned on. 
2. main menu is branded retroarch background (out-of-the-box retroarch/assets/branding.retroarch_nologo_bg.png)
3. each console has custom png background (retroarch/wallpapers/hd controllers/...)

main menu with branded background
![main menu with branded background](https://cloud.githubusercontent.com/assets/22715568/19282827/c59bfd02-8fbd-11e6-9a75-1d7a73efc237.png)

normal pregame menu
![normal pregame background](https://cloud.githubusercontent.com/assets/22715568/19282835/d26a2afe-8fbd-11e6-900f-13e78cd94827.png)

normal in game snapshot
![normal in game snapshot](https://cloud.githubusercontent.com/assets/22715568/19282844/dcb89dd8-8fbd-11e6-8bb9-66cb572e6040.png)

after i launch a game, I invoke the RGUI (F1) and I get crossfade between the paused game in the background and the RGUI. Also, the console-specific dynamic wallpaper is gone and reverts to the main menu's branded background

![in game rgui invoked](https://cloud.githubusercontent.com/assets/22715568/19282856/e49d1ec0-8fbd-11e6-83d3-70f1d0ef3039.png)

when I close the game, the background remains as the branded background
![closed game](https://cloud.githubusercontent.com/assets/22715568/19282877/f0d62c90-8fbd-11e6-9df3-63a9b08729f6.png)

after I navigate away from the console and come back, the background comes back to the custom background
![normal pregame background](https://cloud.githubusercontent.com/assets/22715568/19282903/07881ba6-8fbe-11e6-8353-86d752590ae4.png)

the biggest issue here is that I can barely see the in-game RGUI because of the faded paused game behind it. In games where the paused game is a on a very light colored screen, I can't see the RGUI menu at all. 

![barely see](https://cloud.githubusercontent.com/assets/22715568/19283266/35baec14-8fbf-11e6-80a4-85d9d5623112.png)

**Comment by hizzlekizzle** [comment]
If you go to settings > menu, you should be able to play with the wallpaper opacity and menu alpha factor settings to get something that suits you better.

**Comment by farlsmagee** [comment]
menu opacity seems to only control the visibility of the RGUI menu options on top of the RGUI background/wallpaper. The real problem here is that the paused game that was launched through a core does not disappear entirely when accessing the RGUI.

**Comment by orbea** [comment]
@farlsmagee Is this still an issue?

**Comment by hizzlekizzle** [comment]
no action on this for 4 years. closing.
