### ISSUE TITLE
Turbo fire toggle

### ISSUE THREAD

**Issue by themystx2** [libretro/RetroArch#3782]
Currently, the only solution is to bind a button to turbo toggle, hold it down in order to enable turbo fire on a main key.

Would love for that toggle to be held down to enable turbo fire on a particular key which stays that way until its turned off the same way.

Or alternatively, offer a standalone turbo bind for any active in-game key. fceumm offers turbo A and B by default, for example.

**Comment by fr500** [comment]
there are not enough buttons on gamepads for anything more complex than a nes pad

**Comment by themystx2** [comment]
Hi fr500, 

I didn't mean a full-time turbo binding like fceumm, more along the lines of holding the turbo enabler hotkey, then pressing a button to enable turbo on that particular button.  

The current method is to hold down the turbo hotkey which will enable turbo on every button.  

As an example: say I mapped L as my turbo enabling bind, In Final Fight arcade I'd want to enable turbo on Y (attack button).

I'd hold down L, press Y, release L, and now Y will be turbo unless I turn it off using the same method.

Some arcade sticks have such functionality.    

I hope that makes some sense.
