### ISSUE TITLE
world driver championship rom causes catastrophic failure

### ISSUE THREAD

**Issue by farlsmagee** [libretro/RetroArch#3790]
every time I load world driver championship for n64 the entire application stops working immediately and closes in failure. 

rom - World Driver Championship (USA).n64
core - mupen 64

**Comment by lasers** [comment]
http://wiki.libretro.com/index.php?title=Nintendo_N64_Core_Compatibility#Mupen64Plus

**Comment by fr500** [comment]
Not the correct location for mupen bugs
