### ISSUE TITLE
Vita testing

### ISSUE THREAD

**Issue by pralima87** [libretro/RetroArch#3793]
20/01/2017 - Announcement:
I"m now reporting issues in separated reports.
Maybe this way it gets a bit more attention.
So I'll not update this report any longer.

---------------------------------------------------------------------------------------
Old report :
---------------------------------------------------------------------------------------
~~I'll be posting the vita issues found in my testings here.
When issue is fixed the main post will be updated.
If this is not the appropriate place for this report please let me know.~~

21/11/16 - System is now on TaiHenkaku.
18/01/17 - Retroarch on beta 1.40

General issues:
1-  ~~Saving state first shows text "loading state" (0-100%) them "saving state" (0-100%)
Started to happen some nightlys ago. Can't finda the exact one since only the last 5 are available.
(Improved a lot on 1.40 but is still noticible on PSX ReARMed)~~ **RA issue not related to the vita**

2- ~~Frame Trottle is disable/not working
It was working in the early nightlys (Maybe this one was intentionally disabled for stability)
(Still not working with 1.40)~~ **Fixed in 11/05/17**

3- ~~Scan directory cause the app to crash. (probably is not fully implemented yet)~~ -**Fixed 14/10/16**

4- ~~Performance while on menus dropped a bit. Folder scanning is also a lot slower.~~ -**Fixed 18/01/17**

5- ~~While running a game in the background is not possible to load another in the system scanned list.
The loaded game is always the first one.~~**Fixed in 11/05/17**

Per-Core issues
1 - GPSP - Random Stutter - Apparently this issues started after the Dynarec update.
(Problem persists in 1.40)

**Comment by frangarcj** [comment]
Scan directory should be fixed in nightly

**Comment by Superfasty** [comment]
Came to report that Fast Forward is not working in recent nightly (or any recent nightly). It did work before and I have to keep using earlier versions to use this function.

Also the menu in recent nightlies is definitely not as snappy to navigate. Not sure if this is anything to do with the fact that the XMB and menu fonts seems to be antialiased... or at least not 1:1 pixel anymore. Definitely not as crisp.

**Comment by Superfasty** [comment]
Ok, weirdly Fast Forward seems to work on PCSX but not on any other cores I've tried (Snes9x, quicknes and gpSP)

**Comment by Dochartaigh** [comment]
Kinda new to GitHub, but I guess this is where I should put my issues with RetroArch on Vita (using 1/16/2017 build)?

My biggest problems is scanning for ROMs. After HOURS I got NES, SNES, and Genesis to finally scan. MAME will NOT scan. I have ~100 MAME Roms, which have 1,830 files inside those 100x .ZIP files. Each individual file is taking about ~18 seconds to scan which is over 9 HOURS!!! to scan 100 ROMs. Kinda insane (more like bat sh_t crazy ;)  If people put an entire MAME romset on their device it would need to be running constantly for 30 days...something is broke here.

PSX takes about 30 minutes to scan 1 single .bin/.cue ROM (and the system goes to sleep after 30 minutes which cancels scanning). (all these roms I'm talking about are ReDump, No-Intro, Archive.org-style high quality - and what Retroarch themselves uses to base their checksums off of, FYI)

PCSX-ReArmed has a HUGE problem as well - on a portable device like the Vita it's normal and expected to put it to sleep all the time (especially if commuting to work on a bus/subway/etc.). When you put the Vita to sleep PSX emulation freezes (or will freeze very shortly after waking the system up). Only fix is to quit and re-start (and hope you saved your game before putting it to sleep).

**Comment by frangarcj** [comment]
I think 1,2 and 5 are fixed. Can you test it again @pralima87 ?

**Comment by pralima87** [comment]
mr.frangarcj! Will definitely test all using today nightly!!! lov u!

**Comment by pralima87** [comment]
1,2 and 5all fixed in the latest nighly ;)

**Comment by frangarcj** [comment]
I will close this. You can add an issue over the gpsp repo
