### ISSUE TITLE
OS X 10.12 compile broken

### ISSUE THREAD

**Issue by jeapostrophe** [libretro/RetroArch#3794]
`libretro-common/features/features_cpu.c` defines `clock_gettime` on platforms that don't have it like early versions of iOS and OS X.

OS X version 10.12 defines it (You can detect that you are in this version with `(__DARWIN_C_LEVEL >= 199309L)`)

Unfortunately, there's a crash that I can't debug when you actually use the system one. This patch fixes the issue in a different way: using a different name that doesn't conflict on OS X for the RetroArch-implemented version.

[clock_gettime.patch.txt](https://github.com/libretro/RetroArch/files/529599/clock_gettime.patch.txt)

**Comment by twinaphex** [comment]
Should be fixed now after merging the patch. Thanks!
