### ISSUE TITLE
M3U support only for mednafen core?

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#3809]
Hi. I was building a cmd line utility to create and regenerate automatically m3u files in a directory apart, and thought to myself: 'if this is needed for multidisc games, then surely i can extend this to other platforms, and include single disc games too' (i actually went ahead and created  m3u for every type of rom and cd and made the script recognize multiple cds and put them in one file).

However, once i tried to load these 'non-ps1' files from "load content -> select file and detect core", the core options are always only the two mednafen cores. I would expect this to not be so tightly associated with mednafen but that all cores would have m3u 'support' at least to the point retroarch reads the m3u file and detect the possible cores from there (i'm aware formats like 'iso' would default to have multiple platform cores).

Currently the script is only useful for psx games and i suppose if i install a mednafen saturn core for those too, but this of retroarch is very simplistic for a feature you need to change discs even on other platforms.

If you want to try the script, i placed it on a gist. It's a bit dumb on the detection (order those in the same dir, iterate finding largest common prefix, and check if it ends with cd or disc), but it seems to work on all my games:
https://gist.github.com/i30817/247be3195d023508818d1dcbdbfee4f6

**Comment by i30817** [comment]
Also as a aside, it would be nice if 'scan dir' worked with m3u files, resolving its contents. Currently it runs through all the m3u files and fails at checksumming the files pointed to or loading them as a item. 

On the endgame, i'd love it if i scan m3u files could replace scan of normal files (if the user is so inclined, by placing the m3u files in a dedicated dir). This idea is to prevent 'cd2, cd3' etc on the list.

**Comment by fr500** [comment]
Well... the support is in the core itself... so yeah only for mednafen. RetroArch doesn't parse M3U files at all.
Please don't use the development issue tracker for questions, there is a forum for that.

**Comment by i30817** [comment]
It was more of a suggestion, but all right. Considering that retroarch has the exact same needs as mednafen on other platforms (playing multidisk games on platforms where you might not necessarily be able to open a file chooser or you don't want to interrupt playing and prefer a shortcut), i'd think it would be wise to refactor out the m3u support into libretro as a general thing.

**Comment by fr500** [comment]
There is a disk interface. Handling file formats doesn't have anything to do in libretro.h.
Adding format parsing to the frontend would become messy over time. A kitchensink approach is not what we're after.

**Comment by i30817** [comment]
It's not much of a 'file format'. One line per content, seperated by \n with no metadata. You're going to have to do something like this eventually for all those other emulators who need disc changing (and that is of course the major code challenge).

**Comment by twinaphex** [comment]
With all due respect @i30817, but you don't really understand what we are talking about. Try to actually 'grasp' what we're trying to tell you, this is falling on deaf man's ears this way.

**Comment by twinaphex** [comment]
The whole thing here is that there is no such thing as m3u support for RetroArch, it's a core feature. It's also not possible to add it to libretro API support, since it has nothing to do with files of any kind and we try to abstract that way as much as possible.

So I simply don't understand what you are trying to propose here. I'll have to check if Mednafen Saturn supports M3U files first, I guess you are simply not looking at this through the proper lens and you are talking from an enduser-facing perspective.

**Comment by i30817** [comment]
I'm grasping fine, you seem to be under the understanding that parsing a m3u file to check if the contents end with 'iso' or 'sfc' and showing 'mednafen and pcsxr' for one and 'snex9x' for the other necessitates iso parsing. Naturally there will be false positives, like it happens already.

**Comment by i30817** [comment]
Although, you can keep this closed as 'this feature is only mednafen only for now, we'll open if when/if we extend multidisc changing to other emulators'. I'm just leaving the suggestion of a low hanging fruit.

**Comment by twinaphex** [comment]
Why would the current disc changing not be sufficient for Wii? I don't see why we'd need any more than the current functionality.

**Comment by i30817** [comment]
Its not persistent? (I checked this again on Xenogears now by loading disc 2 manually, selecting new game, closing retroarch, reloading). It also didn't actually let the game progress until i 'let it' see a while with the 'virtual drive' open but i guess thats another bug that has nothing to do with this.
