### ISSUE TITLE
Suggestion: make 'disc control -> disc image append' smarter

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#3812]
This idea doesn't automate the creation of a set of related game discs, but would make the interface smoother at no cost.

When selecting where to open the filebrowser to add a new game image to the set, instead of opening on the normal file dir, open it in the directory that the current game image is on, show the dir contents sorted and the cursor/selection over the current image.

The required game image should be right next to it, since game dumps with multiple cds name them with the same prefixes until the 'disc number' and the same suffix after that, and placed on the same dir 99% of the time. 

You can make this more complicated to gain a minimal gain of usability (make the file selection be 'over' the 'next' disc taking advantage of the characteristic above) but even only this would increase usability of this feature a lot when using the filebrowser.

**Comment by orbea** [comment]
@i30817 Is this still an issue?

**Comment by i30817** [comment]
It isn't anymore. Disc append shows the second cue in the same dir.

**Comment by fr500** [comment]
I didn't even know this was an issue I fixed it because it seemed like the smart thing to do, it would be rather uncommon to have multiple disks on different folders

**Comment by i30817** [comment]
You'd think so but i have to fix it manually after scanning cd roms with clrmamepro if i disable compression (and i do). They get put in directories with the 'game name' (good) but cds of the same game have different game names (possibly a bad default for this very reason, but oh well)
