### ISSUE TITLE
Saving core/game overrides in quick menu

### ISSUE THREAD

**Issue by JuanVCS** [libretro/RetroArch#3814]
Having these settings in the main menu enables the user to try them without a core or game loaded, prompting an error.
I think it makes sense to have these options in the quick menu, as it already has input remapping and shader overrides.

Made some changes [in this commit] (https://github.com/JuanVCS/RetroArch/commit/248205d4258c4f99c4fe4e0012147bef8001bd64), seems to work but it's a crappy copy-paste job.

**Comment by fr500** [comment]
Did you change something else since?
I think the change is welcome, you should send a PR

**Comment by twinaphex** [comment]
OK, send a PR and we will merge it.

**Comment by JuanVCS** [comment]
Done
