### ISSUE TITLE
heuripedes - font refactor on staging

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#3816]
@heuripedes 

It works now on Android.

Here is something that worries me though, the use of thread-local storage (TLS).

This is a huge portability issue for OSX and iOS, which doesn't traditionally support this. Read up on the details here - they propose falling back on pthread_getspecific() and some shenanigans instead.

http://lifecs.likai.org/2010/05/mac-os-x-thread-local-storage.html

My worry is that this will create a big portability issue for other RetroArch platform targets, let's say some esoteric game console with a lousy SDK/incomplete toolchain, etc. Are there really no better alternatives than just resorting to TLS?

**Comment by heuripedes** [comment]
I don't *have* to use TLS. I just needed a way to find out whether the function is running on the main thread or in the video thread. I'll try another method.

**Comment by twinaphex** [comment]
Merged into mainline now.
