### ISSUE TITLE
RetroAchievements Still Plagued

### ISSUE THREAD

**Issue by chewvodka** [libretro/RetroArch#3825]
There are a lot of improvements that still need to be made with RetroAchievements implementation. 

There seems to be communication glitches between RetroArch and the RetroAchievements server.  Sometimes an achievement won't pop because the server never receives the confirmation that the required task had been completed.  Specifically, I can be playing a game that has one achievement for completing each level.  I earn the first 2, then miss the 3rd, then get the 4th and 5th.  Apparently there was a communication glitch when I should have got the 3rd.  This has been reported and confirmed via logs on the RetroAchievements website.

Another issue is with NES achievements.  I just spent a few moments discussing an achievement that didn't pop for me that clearly should have.  Final Fantasy's first achievement "Victory" only has the requirement of winning your first battle.  Well, I battled and won MANY without this ever popping up for me.  The 2nd achievement you should earn is the one where you receive the gift from the princess after rescuing her.  Well, I got the gift, and never earned anything for it.  The common issue with these 2 achievements, is that they appear to be using a "Hit Point" triggering system, where a memory address is being triggered for watching, and a hit counter begins to tick, waiting for an appropriate time to pass before confirming you've done the task.  This was realized when I began mentioning in their chat room other games I've had trouble earning achievements on.  Metroid, for instance, has an achievement that is very simple to earn... Get the Morph Ball.  That's right at the beginning of the game, and super easy to achieve, yet the achievement never pops because once again, it is using this "Hit Point" style of registering.  According to the achievement developer I was talking to, a LOT of the NES games use this type of memory watching due largely to the fact of how the NES memory operates.  So, theoretically, any game that has achievements using this method will not work in RetroArch.  The opposite is true in fact.  The guy I was talking to said the game Bubble Bobble is one he knows specifically uses this method, and yet I have earned quite a number of them with no issues.  So RetroArch is buggy in that it doesn't always catch these things, when in fact the requirements are being made.

Another system that has just completely not worked for me at all is GBA.  It seems like every time I try to play a GBA game, I'm either not earning any achievements at all, or 4-5 of them pop as soon as the game starts.  Is it possible the GBA memory isn't being cleared when the core begins?  That could account for certain bits in the memory to already show the requirements for achievements.  Other than that, I have no clue and I'll leave it to you guys.  All I know for certain is that GBA in RetroArch is pretty much a bust if you're playing for achievements.

There is so much potential here, and new achievements are being developed daily.  I'd hate for this aspect of RetroArch to die out because nobody wants to futher investigate and solve these issues.  There are a LOT of people using this setup, and when something doesn't go right, it's usually because of RetroArch.  The staff at RetroAchievements are rightfully getting upset that their system is buggy, when it's really RetroArch's.  There system has worked fine for years, using their emulators, with no issues (for the most part) and it's only been here recently since RetroArch started developing a method to earn them that issues have began to show up.  For people to point fingers at the other guy doesn't solve anything.  The root of the problem is nobody wants to take a 2nd look at this and figure out what's really happening.  I fail to see how this implementation is anywhere near stable and successful enough to stop being worked on.

I offer my services as an end-user tester.  I have no prior experience in programming the kinds of complexities the RetroArch/LibRetro system is using.  My skills are limited to BASIC for the most part.  But, I've got a very successful track record as a beta tester for many programs.  If things are being implemented that need checked on to see if they work, please let me know!  I'm always willing to help bug test.

Thanks for your time!

**Comment by twinaphex** [comment]
@leiradel Can you take a look into this?

**Comment by leiradel** [comment]
@chewvodka can you send me the RetroArch verbose log filtered by __CHEEVOS__? Final Fantasy for NES doesn't have achievements for me:

```
$ ./retroarch -v -L cores/quicknes_libretro.dll /c/Users/andre/Desktop/RetroArch/downloads/Final\ Fantasy\ \(USA\).nes 2>&1 |grep CHEEVOS
RetroArch [INFO] :: CHEEVOS testing NES (discards VROM)
RetroArch [INFO] :: CHEEVOS getting game id for hash e7fc83ce8b6524f8e991a8af987fcfbc
RetroArch [INFO] :: CHEEVOS url to get the game's id: http://retroachievements.org/dorequest.php?r=gameid&m=e7fc83ce8b6524f8e991a8af987fcfbc
RetroArch [INFO] :: CHEEVOS got game id 0
RetroArch [INFO] :: CHEEVOS testing Generic (plain content)
RetroArch [INFO] :: CHEEVOS getting game id for hash 9b0f042cfdc5f9e8200b47104a4768a9
RetroArch [INFO] :: CHEEVOS url to get the game's id: http://retroachievements.org/dorequest.php?r=gameid&m=9b0f042cfdc5f9e8200b47104a4768a9
RetroArch [INFO] :: CHEEVOS got game id 0
RetroArch [INFO] :: CHEEVOS this game doesn't feature achievements
```

**Comment by chewvodka** [comment]
The only time I ever got that error "this game doesn't feature achievements" is when I'm playing on a core that doesn't support them.  I know there are achievements for NES, SNES, Mega Drive, and GBA.  The NES core I'm using is FCEUmm (SVN).  I noticed in your log you're using quicknes.  Could you try using FCEUmm?  I'm actually going to bed and won't be able to look at this again until tomorrow night.  But I think the core you're using is the problem as far as tracking where the issue comes from.  If you still need my logs, I'll get them when I next have a day off (Thursday).

**Comment by leiradel** [comment]
It seems that NES ROMs are only recognized if the core reads them from the file system. If RetroArch reads and hands them to the core, the hashes are wrong and the games are **not** recognized.

In addition to the log, could you send me the plain MD5 hash of your Final Fantasy ROM? Thanks.

**Comment by chewvodka** [comment]
How do I get the log?  And if you want, I can SEND you the ROM I'm using...

**Comment by leiradel** [comment]
```
./retroarch -v -L cores/quicknes_libretro.dll /c/Users/andre/Desktop/RetroArch/downloads/Final\ Fantasy\ \(USA\).nes 2>&1 |grep CHEEVOS
```

Or just post the ROM's MD5 hash here, I just really want to see if it's the same as mine.

**Comment by chewvodka** [comment]
:/ I'll have to edit that command for my situation... i'm on an RPI3.. but I get the gist..  give me a few minutes (like 30).  I just got home from work, doing dishes and checking email :)

**Comment by leiradel** [comment]
@chewvodka don't bother, I've fixed the code that identifies NES ROMs. Now both QuickNES and FCEUmm are able to identify my FF1 ROM.

**Comment by chewvodka** [comment]
Heh, here's the MD5 anyway:

9B0F042CFDC5F9E8200B47104A4768A9

**Comment by leiradel** [comment]
Thanks, it matches mine.

I've already debugged the code that parses achievements and it seems to be doing the right thing, tomorrow I'll take a look at the code that tests the achievements.

**Comment by chewvodka** [comment]
I tried to get a log that shows just the CHEEVOS entry like you had, but that "|grep CHEEVOS" bit didn't work for me.  So I created a --verbose log.txt file and uploaded it to my Dropbox.  Maybe it'll help?  This is my modified launch command I used for future reference:

/storage/.kodi/addons/script.gamestarter/resources/bin/retroarch -c /storage/.kodi/userdata/addon_data/script.gamestarter/retroarch/retroarch.cfg --menu --verbose >> log.txt 2>&1 |grep CHEEVOS

https://www.dropbox.com/s/atnu36qg95ysfa0/log.txt?dl=0

Also, I played through Final Fantasy with the log running, and went to do the first achievement.  I got in a fight and won, but no cheevo popped.

**Comment by chewvodka** [comment]
The strange thing is, I can earn achievements in other NES games just fine.  It's just some of them have this issue.  So something is different with these types of games that use this other method of testing.

**Comment by leiradel** [comment]
Can you name me an achievement that works and is easy to get?

**Comment by chewvodka** [comment]
Sure...

Super Mario Bros (http://retroachievements.org/Game/1446)
Shroooooms... (http://retroachievements.org/Achievement/3159)

That is soooo easy if you know Super Mario Brothers! :)

**Comment by leiradel** [comment]
Thanks, those will do it.

**Comment by leiradel** [comment]
@chewvodka are you able and willing to build RetroArch from source? I have some fixes to the cheevos subsystem in my fork that could use some tests:

https://github.com/leiradel/RetroArch

**Comment by chewvodka** [comment]
I would if I knew how.  I don't know anything about compiling.  My experience is "write this image to your SD card" then "run this program to install this" and finally "click here to run that".  LOL  I'm on a Raspberry Pi 3.  The first time I noticed this issue was from a strictly Kodi build, where I added the GameStarter addon to launch RetroArch.  My new project I'm working on now is running another Pi3 in an NES case, and it runs RetroPie.  I don't know if either system is capable of compiling, but I would give it a try if I could.  The RetroPie version has a lot more available options since it runs on Raspbian rather than Open/LibreELEC.  Is there a way to compile and test (like in Windows) in a separate folder that would be safe from affecting and being affected by the rest of the system?

**Comment by leiradel** [comment]
I'd rather not mess with your box. A Pi3 in a NES case sounds awesome.

**Comment by chewvodka** [comment]
Yeah it will be if I ever figure this stuff out.. This is all unknown territory.  Right now I'm trying to figure out why my USB Hub don't work lol.  But yea, if there is some way for me to help you troubleshoot, let me know.  In any case, maybe somebody else can?

**Comment by leiradel** [comment]
I've asked for help in #retroarch and in the Retro Achievements forums. If that doesn't result, I'll just push the changes and wait for complaints. You have to accept some issues if you go with nightly builds, right? :)

**Comment by chewvodka** [comment]
Yeah.  If something is "pushed", how do you actually get the update?  Would I have to wait until RetroArch releases a new update?

**Comment by leiradel** [comment]
No, the changes will appear in the next nightly build, but I don't know if it'll make it for tonight's build or tomorrow's.

**Comment by chewvodka** [comment]
I made a backup copy of my SD card to be safe, then did this...
RetroPie has a built in menu script system to let you control virtually all aspects of the build.  I went into the "Manage Packages" section, then "Manage Core Packages", then "retroarch (installed)".  From there, you have the option to "Update from binary" and "Update from source".  Since I don't know how to compile on my own, I had hoped this source option is what I needed.  So I launched that, and it took like 5 minutes to go through and scan my installation for things that have been updated, download them, compile a new version, and install it.  Once I ran the RetroArch system again, the build number stayed the same (might be because a new VERSION hasn't come out yet).  I tried to run one of the games I mentioned before that wasn't working (Metroid).  It still doesn't work for me.

**Comment by lasers** [comment]
Check Main Menu --> Information --> System Information --> Git version.

**Comment by chewvodka** [comment]
Now I'm having another problem.  Whenever I pull up the achievements list, it displayes their titles, but clicking into them all show the same description (whatever the 1st achievement on the list is for).  It does this on every game I've tried so far that has cheevos..

**Comment by fr500** [comment]
That is fixed already, it doesn't even show achievements when pressing A anymore.
It shows the achievements in sublabels.

**Comment by chewvodka** [comment]
I'm lost... so the code changed to just show the titles and no descriptions anymore?  Thats a pretty lame change.

**Comment by fr500** [comment]
Read again. It shows them in sublabels.
You're still using old code.

**Comment by chewvodka** [comment]
Ok, I realize I'm a heavy noob here.  I have no idea what you mean, and I dont know how to upgrade to make it work.  Some hand-holding would be nice.  :)  And I know, RetroPie and RetroArch are 2 different beasts.  I'm only just now getting familiar with RetroPie.  But I'm familiar enough with RetroArch now, I just don't know how to update stuff, and make sure it doesnt break something else.

**Comment by fr500** [comment]
I don't know how to update retropie or it's packages.

**Comment by chewvodka** [comment]
Ok, so RetroPie has an update, which requires you to run their setup scripts, giving you the option to update everything installed.  I chose that, and let it run.  RetroPie is now fully updated.  If I manually launch RetroArch and check the System Information, it reads "Build Date Nov 4 2016" and a Git version of "9a9f76d".  Now I dont know what good that information does me.. I still have an achivement list with titles, locked/unlocked, and non-working descriptions that just show the details of the 1st cheeve still to unlock, but for all of them..

**Comment by chewvodka** [comment]
I've got the Nov 9 2016 build running now.  I finally see what you meant by Sublabels.  That works just dandy!  Now all I have to do is figure out hwo to fix the controller's button combination to return to the game.  It works for entering RetroArch's menus, but fails to go back.  Not really a RetroArch issue though.  Looking forward to further testing this out.  :)

**Comment by leiradel** [comment]
@chewvodka i think this issue can be closed now?

**Comment by chewvodka** [comment]
I don't know.  I was originally complaining about not earning achievements in games when others do (like stage 1, stage 2, no stage 3, stage 4, etc).  There's also the issue with GBA achievements.  I guess I should have restricted the issue to just 1 particular thing.  But sure, if you feel the issue is closed...  I still feel like my original title is pretty clear: RetroAchievements **ARE** still Plagued..  Thanks though for all your efforts in possibly resolving the issues with the NES stuff.

**Comment by leiradel** [comment]
Yes, one issue per, hm, issue would have been better. Lets keep this one open until everything is solved. Your problems with NES are solved, right?

Which core are you using for GBA? Both mGBA and vba-next cores should work.

As for network glitches, RetroArch will keep trying to send commands to Retro Achievements until it succeeds, but if its closed the pending commands will be lost. I'm yet to decide how to fix this one.

**Comment by meleu** [comment]
@chewvodka We got some corrections/improvements on the cheevos feature recently. Do you think this issue could be closed now and report the issues one by one as they appear?

**Comment by chewvodka** [comment]
Certainly sounds good to me.  I think don't know if all of the bugs are completely worked out yet, but it's definitely better than it was before I started bringing it up.  :)  Thanks a lot guys!
