### ISSUE TITLE
(VITA-FBA-gpsp)Since build 18.10.2016 Crashes on Rom load

### ISSUE THREAD

**Issue by Traace** [libretro/RetroArch#3828]
When we load a Rom via fbalpha or gpsp core (maybe more, untested) on every build since 18.10.2016, it crashes with a dump
This happens every time.

Bios is placed in: UX0:/data/retroarch/system
Proper system path is set in Retroarch

Versions tested: 18.10.2016 Nightly and up
All under 18.10 don't suffer from this bug.

The dump is renamed to .zip to allow upload. Please rename it back to .psp2dmp
[psp2core-1476881151-0x00010e310f-fbalpha_libretro.self.zip](https://github.com/libretro/RetroArch/files/539148/psp2core-1476881151-0x00010e310f-fbalpha_libretro.self.zip)

**Comment by twinaphex** [comment]
Yes, it must have been the font refactor commits. @frangarcj and me will have to figure out which of the two commits was responsible, and then fix whatever the issue is.

**Comment by twinaphex** [comment]
Should hopefully be fixed now in the upcoming nightly.

**Comment by Traace** [comment]
Jup, seems like its fixed.
Tested build: 2016-10-20_RetroArch | Dirty install
Tested cores: fbalpha, gpsp, pcsx-rearmed

Thanks for your work, appreciated.

Closed
