### ISSUE TITLE
(Vita) FBA CPS1, CPS2 and NeoGeo NVRAM Save Files

### ISSUE THREAD

**Issue by Smoker1** [libretro/RetroArch#3833]
Under MAME2003, this Core Creates NVRAM Saves, but the FBA Cores do not. Which means any Settings that are changed, have to keep getting Changed every time you select a certain Game. 
Example:
HSF2
Go into System Menu and Select Free Play, Demo Sound On, Change Difficulty Settings, ect.

**Comment by fr500** [comment]
https://github.com/libretro/
You can find the various issue trackers for the cores there
