### ISSUE TITLE
Sega 32x roms not recognized by scan directory.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#3836]
I'm unsure if this is a extension issue or what (no-intro dat files rename them to extension .32x). I'm sure they're not on the genesis list after scanning their dir.

**Comment by ofry** [comment]
Can't confirm this. I downloaded full romset of Sega 32x, scanned this directory and got playlist.

Are you using latest nightly build?

**Comment by i30817** [comment]
Oct 16 buildate in the system information.

**Comment by ofry** [comment]
Yes, I have no-intro romset with many zipped roms, each archive has one rom with *.32x extension.

Build date: Oct 20, 2016.
Git version: 335c9ec

**Comment by i30817** [comment]
I have them uncompressed, can't you try one uncompressed? You'll have to delete the right playlist from the config folder of course.

**Comment by lasers** [comment]
I'm having problems with RetroArch scanning zipped archives. There are about  60 `.32x` in `Sega - 32X.dat` right now. You might have a broken scanner too.

**Comment by lasers** [comment]
I can't scan Compressed-Game.zip or Uncompressed-Game.32x here.

**Comment by sergiobenrocha2** [comment]
You have to download PicoDrive first, then it'll scan fine the .32x files

**Comment by lasers** [comment]
Thank you sergio! :+1:  I can't scan Compressed-Game.zip.
I can scan Uncompressed-Game.32x here.

**Comment by i30817** [comment]
Weird. What about genesis plus gx?

**Comment by RobLoach** [comment]
>  I can't scan Compressed-Game.zip.
I can scan Uncompressed-Game.32x here.

Does your RA build have zlib support? Can you load the PicoDrive core correctly?

**Comment by lasers** [comment]
```
chris@z420 ~ $ retroarch --feature | grep -A1 zlib
  zlib:
                .zip extraction support: yes
```
I can run the content on PicoDrive core just fine. It's definitely the scanner.

**Comment by RobLoach** [comment]
Worked well here. All .zip files...

![screenshot at 2016-10-25 08-36-56](https://cloud.githubusercontent.com/assets/25086/19686307/836ce848-9a8e-11e6-95ae-5222475efc15.png)

**Comment by lasers** [comment]
I mentioned about this zip issue two weeks ago https://github.com/libretro/RetroArch/issues/3763. If you keep playing around, you might be lucky enough to see this. When setting up for first time, I was able to scan the zipped archives, then compressed images... then it will stop working after few scans... maybe because of a restart or an unclean exit. I'm using linux if that helps.

Unzipped contents still can be added though. This really feel like a loading a timebomb core that only allows you to scan anything you want for a 4-hour trial period.

**Comment by bparker06** [comment]
@lasers As previously discussed in your issue, the current workaround for scanning zip content is that you must have a zip supported core installed such as MAME or FBA, and your core info files and databases up to date, then you should be able to scan zip content just fine.

**Comment by lasers** [comment]
@bparker06 Oh! Thank you...  It's finally scanning everything for me. I somehow missed your workaround on the first go.

**Comment by i30817** [comment]
The original bug here was caused by user error, the other bug discussed should have a open issue, i'm closing it as a round of spring  cleaning of my reported bugs.
