### ISSUE TITLE
PS VITA Handy core issue

### ISSUE THREAD

**Issue by themystx2** [libretro/RetroArch#3841]
Emulator immediately crashes upon loading new ROM with Handy core loaded.  10/20 AIO build.  

edit - The first ROM loaded is fine, its when you try to load a different ROM within same session it crashes.

**Comment by twinaphex** [comment]
It's a memory leak issue probably.

**Comment by meleu** [comment]
I was having this issue in december/2017. But currently I'm unable to reproduce this (RetroArch 7a99694 and https://github.com/libretro/libretro-handy/commit/a3d88fede0b2850a242da818d3392a637ce2355f on PS Vita).

@twinaphex IMO this issue should be closed.
