### ISSUE TITLE
Input issues

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3842]
4b807b482feeeff87775a472505307d43d3784c9 
- breaks input mapping, binding a hotkey to L/R will cause the cursor to move just after binding and binding to START will cause the binding to clear immediately

a564ac0701f7ee785458cd3bdae5f39d4017295d 
- causes autorepeat to stop working with pad or kbd in windows, holding down or up no longer scrolls
- breaks menu toggle combos
- breaks hotkey enable
- causes hotkeys to trigger action that are not mapped to the intended hotkey
- core input doesn't work at all seems hotkey enable is being triggered
- vsync keeps toggling itself on and off all the time, seems hotkey enable is being triggered and fast forward too

On a bright note, the turbo refactor didn't cause anything to break

**Comment by fr500** [comment]
335c9ec958d6da424f888db756c0c1da99ca4fd9 is good regarding all these issues

**Comment by twinaphex** [comment]
Reverted a564ac0, now going to look at undoing 4b807b4, in hindsight splitting the input code up into a separate function wasn't really so useful anyway.

**Comment by twinaphex** [comment]
Rolled back 4b807b4 too, hopefully that will fix all remaining issues now.
