### ISSUE TITLE
[Request] Access Remote Content? Builtin Webdav Support?

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#3848]
access content/roms from a http server that has webdav support enabled

(_WEBDAV_ Windows Example)
![Windows](http://i.imgur.com/3GRlAU0.png)

so this is great that I can access these from my U: drive however say I have retroarch on my android device which can not mount folders without root access.

having builtin support for accessing content remotely could solve this issue

other ideas are 
- SSH
- MS ONEDRIVE
- CIFS/SMB (SAMBA FILE SHARE) **SECURITY RISK OVER INTERNET ON TCP 445**

**Comment by CanadianJeff** [comment]
just a shameless bump for this

**Comment by RobLoach** [comment]
RetroArch usually tries to not re-implement OS-level stuff. I've mounted samba drives across the network on Linux. I'm sure you could do something similar in Windows.

Dropbox? SyncThing?

**Comment by CanadianJeff** [comment]
cant do that on android without root access

**Comment by CanadianJeff** [comment]
also mounting samba file shares over the internet is a bad idea unless you use a VPN/SSH tunnel

**Comment by fr500** [comment]
You can make it at least download content from a raw http server.
I use this myself, I have  a server with all my roms. It downloads them and then I load them from downloads.

You need to generate indexes with this:

> #!/bin/bash
> 
> curr=$PWD
> basedir=$1
> for dir in $(find "$basedir" -mindepth 1 -maxdepth 100 -type d); do
>    cd $dir
>    find . -maxdepth 1 -type f | cut --fields=2 --delimiter="/" | grep --invert-match .index | sort > .index
>    cd $curr
> done
> 
> curr=$PWD
> basedir=$1
> for dir in $(find "$basedir" -mindepth 1 -maxdepth 100 -type d); do
>    cd $dir
>    rm .index-temp
>    rm .index-dirs
>    rm .index-extended
> 
>    find . -maxdepth 1 -name "*.zip" -type f -exec bash -c "unzip -v {} | grep -v zip | grep libretro | tr -s ' ' | xargs | cut --fields=5,7,8 --delimiter=' '" \; > .index-temp
>    find . -maxdepth 1 -type d | cut --fields=2 --delimiter="/" | grep --invert-match "\." > .index-dirs
>    while read line
>    do
>        echo "${line}.zip" >> .index-extended
>    done <  .index-temp
>    rm .index-temp
>    cd $curr
> done
> 
> cd $curr
> 
> find ./ -type f -name .index-dirs -size 0 -delete
> 

And then make that your content downloader URL.

WebDAV is a horrible protocol. It actually blows on windows and isn't any more secure than CIFS unless you have the server SSL enabled.

**Comment by Ferk** [comment]
> cant do that on android without root access

You can use both dropbox and [syncthing](https://play.google.com/store/apps/details?id=com.nutomic.syncthingandroid&hl=en) without root access.

**Comment by UnluckyForSome** [comment]
@fr500, would you mind how you run this script with retroarch? I’m a complete noob but I need some way of picking a rom/iso from a remote share, then it being downloaded temporarily and run! (On Windows 10)

**Comment by RobLoach** [comment]
Closing this one as a duplicate of https://github.com/libretro/RetroArch/issues/2028 .
