### ISSUE TITLE
Black boxes for content tabs. 

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3858]
I have black boxes for content tabs... for about a week now. 
* content_history
* content_image_history
* content_music_history
* content_video_history

I got the latest assets and this line `assets_directory = "~/.config/retroarch/assets"` in the config. The icons works fine everywhere else. Anybody else got this problem too?

**Comment by fr500** [comment]
Please don't use the issue tracker as a forum.
If you want to ask about general issues or problems go to the actual forum
http://libretro.com/forums/

I have no such problem with the monochrome theme.

**Comment by lasers** [comment]
Will do. This is with the monochrome theme too. Tested with fresh config.

**Comment by lasers** [comment]
@fr500 Please open this. It's still an issue for me. 👍

**Comment by lasers** [comment]
I suspect the issues are related to custom paths. I use this.
```
# Keep all played content in the menu and from CLI directly for convenient quick loading.
# content_history_path = "~/.config/retroarch/playlists/content_history.lpl"
# content_music_history_path = "~/.config/retroarch/playlists/content_music_history.lpl"
# content_image_history_path = "~/.config/retroarch/playlists/content_image_history.lpl"
# content_video_history_path = "~/.config/retroarch/playlists/content_video_history.lpl"
```

**Comment by lasers** [comment]
pls reopen dis issue. thx.
