### ISSUE TITLE
Rewinding with Retro Achievements

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3860]
With Retro Achievements options toggled on, you cannot rewind.

That's not an issue though. When paused in the game, hitting "rewind" button will fast-forward the frames... An opposite and unwanted behavior.

The fast-forwarding feature also works under Retro Achievements.

* _This possibly could be considered cheating as one is speeding up through all their gameplays/grinding more than others to get same Retro Achievements._

Not a bad thing. Let people enjoy their games at faster paces, I suppose.

**Comment by leiradel** [comment]
A quick look at the code shows that rewinding is only disabled if cheevo's hardcore mode is enabled.

Could you check this is really the case?

**Comment by lasers** [comment]
http://retroachievements.org/faq.php#faq5

That FAQ does not mention that rewinding would be disabled. I simply signed up for RetroAchievement and simply toggled everything on in the retroarch.cfg.... including the hardmode.

I have turned that hardmode off because of inability to save/load gamestate... and I can can turn it back to test the new code. The expected behavior is to do nothing (not even a notification).

I use pause toggle often too... so maybe, hitting rewind... or paused, hitting rewind results in fast-forward. I can't recall the exact scenario. The game I played is from SuperGrafx system and is not supported... Maybe the code ought to do something about unsupported games... like disabling cheevo in first place?

**Comment by leiradel** [comment]
That FAQ is for the RetroAchievements emulators, RetroArch is not affiliated with them, for now we just have an agreement to use their webservices to add achievement capabilities to some of our cores.

Anyway, you bring good questions. We should be clear on how RetroArch should behave regarding fast-forward, rewind, pause and cheats when achievements are on, with and without hardcore mode.

@twinaphex we should discuss and come up with the expected behaviors.

**Comment by lasers** [comment]
(And slowmotion).

**Comment by lasers** [comment]
I also want to suggest if we should stop calling it hardcore mode because disabling non-game options does not make it hardcore mode. At most, everything is now more accurate. I would call it legitimate mode. People could refer it as legit mode too.

> To play and beat your games legitimately, you will not be able to use Retroarch's built-in options such as cheats, rewind, fast-forward, pause, slow motion, or any other options that may be added in the future.

The name itself likely came from games since majority of the games have difficulty options. Some of them are even named exactly same.  Should we try and avoid them?

--
> Did you beat Shadow of the Colossus on hardcore mode on hardcore mode?
> wat. yeah... I played it on hardcore mode.

-- 
> Did you play Sonic 3D Blast  hardcore on legit mode?  That game is really hard for me.
> Yeah, I legit beat it on hardcore. Got my achievements and everything. 

--
> Did you legitimately beat Super Paper Mario on hardcore mode?
> Nope. It was too hard for me. I beat it with cheats.

I'm just trying to avoid confusion if people are to going to start talking about how they beat games on hardcore mode (which hardcore mode was that again)... and you know, search engines will think they're same thing.

**Comment by dankcushions** [comment]
'hardcore mode' is retroachievements' term. take it up with them. http://retroachievements.org/faq.php#faq5

**Comment by lasers** [comment]
Thanks. Will do!

**Comment by fr500** [comment]
It's working as designed from what I can gather

**Comment by meleu** [comment]
Just a quick note about the fast-forward: The official RetroAchievements emulators has this feature even with hardcore mode enabled.
