### ISSUE TITLE
RetroArch fails to compile on Odroid C1+

### ISSUE THREAD

**Issue by xstrex** [libretro/RetroArch#3863]
I've been trying to get RetroPie working on an Odroid C1+ but have run into an issue when compiling retroarch. See forum post here: https://retropie.org.uk/forum/topic/4815/retroarch-fails-to-compile-on-odroid-c1

Following the instructions from an admin there, I've cloned the retroarch repo and have attempted to compile it on the Odroid, separate from the RetroPie installer, but i'm getting the same errors. 

Here's what I'm running: 
retro@odroid:~/RetroArch$ uname -a
Linux odroid 3.10.80-131 #1 SMP PREEMPT Thu Oct 15 19:53:29 BRT 2015 armv7l armv7l armv7l GNU/Linux

retro@odroid:~/RetroArch$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

retro@odroid:~/RetroArch$ cat /etc/os-release
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

Configure Line: ./configure --enable-opengles --enable-mali_fbdev
Configure completes successfully. 

Tail end of make, including errors (full output: http://pastebin.com/bDTw8zkN): 
```
CC input/connect/connect_wiiugca.c
CC input/drivers_joypad/parport_joypad.c
CC gfx/video_context_driver.c
CC gfx/drivers_context/gfx_null_ctx.c
CC gfx/video_state_tracker.c
CC libretro-common/gfx/math/vector_2.c
CC libretro-common/gfx/math/vector_3.c
CC libretro-common/gfx/math/vector_4.c
CC libretro-common/gfx/math/matrix_4x4.c
CC libretro-common/gfx/math/matrix_3x3.c
CC gfx/drivers_context/drm_ctx.c
CC gfx/drivers/gl.c
CC libretro-common/gfx/gl_capabilities.c
CC gfx/drivers/gl_renderchains/render_chain_gl_legacy.c
CC gfx/common/gl_common.c
CC gfx/drivers_font/gl_raster_font.c
CC libretro-common/glsym/rglgen.c
CC menu/drivers_display/menu_display_gl.c
CC gfx/drivers_context/mali_fbdev_ctx.c
gfx/drivers_context/mali_fbdev_ctx.c:48:30: error: field ‘native_window’ has incomplete type
    struct mali_native_window native_window;
                              ^
gfx/drivers_context/mali_fbdev_ctx.c: In function ‘gfx_ctx_mali_fbdev_destroy’:
gfx/drivers_context/mali_fbdev_ctx.c:68:8: warning: implicit declaration of function ‘free’ [-Wimplicit-function-declaration]
        free(mali);
        ^
gfx/drivers_context/mali_fbdev_ctx.c:68:8: warning: incompatible implicit declaration of built-in function ‘free’
gfx/drivers_context/mali_fbdev_ctx.c:78:4: warning: implicit declaration of function ‘system’ [-Wimplicit-function-declaration]
    system("setterm -cursor on");
    ^
make: *** [obj-unix/gfx/drivers_context/mali_fbdev_ctx.o] Error 1
```

Ran a make clean, reconfigured with: ./configure --enable-opengles --enable-mali_fbdev
Applied the patch suggested in the forum post above: sed -i 's|struct mali_native_window native_window|fbdev_window native_window|' gfx/drivers_context/mali_fbdev_ctx.c

Ran make again, here's the tail end of the make output (full output: http://pastebin.com/UgLA31hf): 
```
CC libretro-common/formats/bmp/rbmp.c
CC libretro-common/formats/bmp/rbmp_encode.c
CC libretro-common/formats/json/jsonsax.c
CC libretro-common/formats/image_transfer.c
CC camera/drivers/video4linux2.c
CC cores/libretro-video-processor/video_processor_v4l2.c
cores/libretro-video-processor/video_processor_v4l2.c: In function ‘libretro_videoprocessor_retro_set_environment’:
cores/libretro-video-processor/video_processor_v4l2.c:237:11: warning: missing braces around initializer [-Wmissing-braces]
    struct retro_variable envvars[3] = { NULL };
           ^
cores/libretro-video-processor/video_processor_v4l2.c:237:11: warning: (near initialization for ‘envvars[0]’) [-Wmissing-braces]
CC libretro-common/net/net_compat.c
CC libretro-common/net/net_http.c
CC libretro-common/net/net_socket.c
CC network/net_http_special.c
CC tasks/task_http.c
CC libretro-common/net/net_ifinfo.c
CC network/netplay/netplay_net.c
CC network/netplay/netplay_spectate.c
CC network/netplay/netplay_common.c
CC network/netplay/netplay.c
CC cheevos.c
CC libretro-common/utils/md5.c
CC input/input_remote.c
CC cores/libretro-net-retropad/net_retropad_core.c
CC record/drivers/record_ffmpeg.c
CC cores/libretro-ffmpeg/ffmpeg_core.c
CC tasks/task_decompress.c
LD retroarch
/usr/bin/ld.bfd.real: cannot find -lXv
/usr/bin/ld.bfd.real: cannot find -lva
/usr/bin/ld.bfd.real: cannot find -lSDL
/usr/bin/ld.bfd.real: cannot find -lXv
/usr/bin/ld.bfd.real: cannot find -lva
/usr/bin/ld.bfd.real: cannot find -lSDL
collect2: error: ld returned 1 exit status
make: *** [retroarch] Error 1
```

Thanks. I'm happy to provide more info, or logs if needed.

**Comment by Kivutar** [comment]
Apply this patch https://github.com/libretro/Lakka/blob/lakka/projects/OdroidC1/patches/retroarch/retroarch-02-fix-mali-fbdev.patch

Some platforms come with different mali headers.

**Comment by xstrex** [comment]
Thanks @Kivutar Applying now.

**Comment by joolswills** [comment]
The patch looks the same as produced by the sed change btw. The initial problem they had was fixed by your earlier commit @Kivutar afaik https://github.com/libretro/RetroArch/commit/07421c3cd4e45fdb13773d01c48381e0ec2afcbe

**Comment by joolswills** [comment]
(The initial problem they posted on the RetroPie forum)

**Comment by xstrex** [comment]
re-cloned repo, applied patch, configured with above config line, and ran make. Same errors. 
http://pastebin.com/6dhkgYFX

**Comment by joolswills** [comment]
Please see my reply on the forum - I meant for you to try again with the RetroPie-Setup script (which adds some additional configure options and makes sure the dependencies for them are installed).

**Comment by xstrex** [comment]
Will do, thank you.

**Comment by xstrex** [comment]
compilation has completed successfully via the retropie_setup.sh script. Thank you, both of you for your input.
