### ISSUE TITLE
FreeSync : irrelevant actual monitor frequency

### ISSUE THREAD

**Issue by bidinou** [libretro/RetroArch#3871]
Hi everyone ! 

After reading this thread : https://github.com/libretro/RetroArch/issues/1633, I tried to get FreeSync to work. 

My setup is the following : Linux (Lakka), Nuc i5 iris 440 and recent Freesync compatible "gamer" Iiyama monitor.

When freesync is disabled : I get "almost perfectly" smooth scrollings in all systems. Not pixel perfect though (I use integer scaling). There are some minor glitches. It's acceptable, but I was wondering if this could be improved. I'm from the Amiga scene so butter smooth scrollings are kinda part of me :-) Retroarch reports a vertical frequency of 60.002 (0.5% deviation after a while). My monitor is at 60 Hz.

So I tried to enable freesync on my monitor OSD. For some strange reasons, my monitor OSD reports  now a variable frequency around 70-75 Hz !! And Retroarch report a frequency around 55-59 Hz or so with a huge deviation (like 15%). Very unstable. Logically, games are clearly not smooth. It's not that terrible but far less smooth than in the case above. I tried to tweak the settings as indicated in the previous thread (audio sync, vsync, 1.0 run speed, delta 0.0) but it makes no significant difference. Apart from runspeed otherwise it's too fast with audio sync disabled.

I guess the issue is : why is my monitor vertical frequency set between 70 and 75 Hz to display 60 Hz games ? Also, strange thing : even if I disable Freesync I have to reboot Lakka otherwise my monitor gets stuck at this strange frequency. Not really a problem, the gfx stack must get confused if a monitor behaviour is altered.

Thanks a lot to everyone :-) Big retroarch / lakka fan !

Edit : of course, I tried many combinations of more common settings too (max swapchain 1 2 or 3, vsync on/off, I do use integer scaling, disabled shaders, etc etc.)

**Comment by twinaphex** [comment]
I don't have a Freesync/G-Sync monitor so I can't really comment on these other issues you are having. instead, I will invite @Themaister in this thread since he might be able to provide you with a clearer answer as to what kind of steps you could take to improve your situation.

As for higher than usual frame time deviations, are you able to test the Vulkan video drive there? GL drivers are kinda spotty there in general.

**Comment by bidinou** [comment]
Thanks for the reply ! I'm not sure Vulkan is available on Linux ATM ? Never really heard of it actually. I have no Windows box to make the comparison, unfortunately :-/

**Comment by hizzlekizzle** [comment]
You can use Vulkan in Linux with your Iris graphics.

**Comment by bidinou** [comment]
Hi ! I'm getting back to you as I'm completely clueless regarding this Vulkan gfx driver. I searched quite a lot and found no piece of information indicating its current state on Lakka, how to enable it, what is currently supported etc. Any pointer ? :-) There's no hurry, I can wait a couple of months or more for a Lakka version with Vulkan driver built-in if it's not mature.
Thanks :-)

**Comment by hizzlekizzle** [comment]
I haven't used it in Lakka, but as long as their Mesa libs are reasonably up-to-date, you should be able to go into settings > driver and change the video driver to vulkan and then just reboot. Note: libretro-gl cores like ppsspp and mupen/glupen won't work with vulkan.

**Comment by bidinou** [comment]
Hmm, apprently it's not in the current build. Only OpenGL driver (or "none") in Lakka / PC / x86-64. I'll wait :)

**Comment by hizzlekizzle** [comment]
@bidinou is this still a problem with the 'sync to exact content framerate' option and your refresh rate set to your monitor's max refresh?
