### ISSUE TITLE
Joypad not working on snes core (PSVITA)

### ISSUE THREAD

**Issue by cybermat80** [libretro/RetroArch#3876]
Hello,
i noted that in the latest nightly builds of Retroarch for Psvita (2016-10-27_RetroArch), the controller on Snes cores is not working anymore. I tried 2002,2005,2005+ and 2010 version with no luck.

Could you please help on this ?

Thanks

**Comment by cybermat80** [comment]
I don't want to have opened an useless thread, but this occurs just on the only one game i was playing (Super Mario World), after have selected the Mario's episode i want to play, Joypad stops working....but maybe it's rom related.

**Comment by fr500** [comment]
Ok that's different and know and it's in no way a RetroArch bug but a core bug.
http://libretro.com/forums/showthread.php?t=7032&p=49708&viewfull=1#post49708

Feel free to open this in the snes9x2002/2005 bug trackers as you see fit.
