### ISSUE TITLE
In-Game Menu does not cooperate well when paused.

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3882]
- [ ] Possible bug
* Load a game. Pause a game using RetroArch's builtin option. Visit In-Game Menu. This is when you might notice you're having troubles returning back to the game. You have to unpause few times first to kill the In-Game Menu.

**Comment by fr500** [comment]
a few times?
if you pause via hotkey, then go to the menu and then back to game you have to unpause once... 
I don't see the problem it's working as expected.

**Comment by lasers** [comment]
https://gfycat.com/ShowyMediocreCat

**Comment by lasers** [comment]
This problem is more noticeable when using ffmpeg to play a video.

Load a video. Gotta poop. Pause video. Come back. Bring up the menu. Look around. Bring down the menu. **Broken**. Ribbon freeze. Unpause to fix.

Load a video. Gotta poop. Pause video. Come back. Bring up the menu. Look around. Resume. **Broken**. Ribbon freeze. Unpause to fix.
