### ISSUE TITLE
[Android] GL cores are not working

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#3883]
GL cores are not working with last build

**Comment by twinaphex** [comment]
I think you only mean Mupen64plus and Glupen64, and it's likely that this is not a RetroArch issue at all but rather a change that was made to GLSM. I will be testing this later on at least for Mupen64plus.

**Comment by sergiobenrocha2** [comment]
PPSSPP is not working too.

**Comment by sergiobenrocha2** [comment]
It's working again, related to #3907 ?

**Comment by sergiobenrocha2** [comment]
Closing for now
