### ISSUE TITLE
Add WiiU compiling instructions to README.md

### ISSUE THREAD

**Issue by JaceCearK1** [libretro/RetroArch#3885]

**Comment by hizzlekizzle** [comment]
That's not a good place for it, as our readme would get out of hand pretty quickly if it contained compiling instructions for every platform. The wiki is a better spot.

However, there's nothing to see right now anyway, so unless you're wanting to contribute, you're better off waiting until we get it on the buildbot.

**Comment by JaceCearK1** [comment]
I understand that! Just thought since almost every platform is on there, WiiU should be added aswell...
Well, I'd definitely try to contribute, but it's a little difficult to do, if I can't get it to compile.
I assume, I'm missing a library, any hint where to find it/how to compile it?
The following undefined references are in dynamic.c:
![image](https://cloud.githubusercontent.com/assets/11230293/19828603/eb3a6dc6-9dca-11e6-9590-b12b022f6be2.png)

**Comment by hizzlekizzle** [comment]
The consoles statically link the cores against RetroArch, so make sure you compile a core first and then put the libretro.a file into your RetroArch source tree.

**Comment by JaceCearK1** [comment]
Alright!
Is it as simple as, for example, cloning the libretro/Nestopia repo, change the CC and CXX values to devkitpro's PPC compilers and just hit 'make core' on its root-directory or am I missing something?

**Comment by hizzlekizzle** [comment]
There's generally a makefile switch that will handle all of the details for you, e.g. platform=wii. In some repos--usually ones where the libretro-ization is adopted upstream--you have to dig around to find the right makefile (these will usually be named makefile.libretro).

**Comment by JaceCearK1** [comment]
Thank you, I'll look what I can find!
I guess, I can close this now since the instructions are gonna be on the wiki anyway?
