### ISSUE TITLE
Menu issues

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#3899]
Tested on Shield Tablet:
- [ ] There is no way to go down in unlimited values with touch only, it just keeps increasing

Tested on Windows 8.1 x64
Commit: 21c7f562f7a81d344bc14c65e866992c7c9cd630

OSK / Input Line
- [x] characters typed with the real keyboard don't show in the line being inputted (Windows only)
- [ ] pressing enter to close OSK also presses enter on the current menu item (Windows only)

Settings / Driver
- [x] all these entries wrap at last entry, none wrap at first entry (has been for a long time)
- [ ] none of these entries have defaults, I guess we should have defaults depending on platform

Settings / Video
- [x] Windowed Scale can't be increased, it can be decreased or reset but not increased. 
- [x] Picking a video filter returns you to the main settings menu instead of audio settings

Settings / Audio
- [x] Volume can't be incresed, only reset
- [x] Audio latency wraps up but doesn't wrap down
- [x] Audio timing skew can't be incresed, only reset
- [ ] Audio device shows an input dialog? not sure this is an issue but it should show a list I guess?
- [ ] Audio output rate is stuck
- [x] Picking an audio DSP returns you to the main settings menu instead of audio settings

Settings / Input
- [x] Max users wraps only up
- [x] Poll type behavior wraps only up
- [x] Menu toggle combo wraps only up
- [ ] Back as menu toggle doesn't have text (shows null)
- [x] Input axis threshold can't be increased, only reset

Settings / Input / Hotkey Binds
- [x] Binding full screen toggle results in fullscreen being toggled at binding time
- [x] Binding exit results in retroarch exiting (or asking for confirmation)
- There could be more of these, several won't have an effect because they are only triggereable in-game. Grab mouse should have the same issue if it was global but it doesn't so I don't really know what's going on

Settings / Input / User X Binds
- [x] User X Device Index doesn't print any values on the right screen. It should print the controller name
- [x] Gamepad: Re-binding Start to any other button results in start action being triggered thus defaulting to the original value
- [x] Gamepad: Re-binding any action to a button with another action results in the action being triggered (bind A to B for instance results in RA going one level up in the menu, or binding L to R results in menu scrolling up one page)
- [ ] When doing bind all, analogs often register in more than one entry
- basically I think we need a cooldown after each bind, could be 60 frames or whatever so no actions take place after the bind but before cooldown expires

Settings / Logging
- [x] Verbosity level doesn't wrap down

Settings / Throttle
- [x] Max run speed can only be decreased or reset, not increased
- [x] Slow motion ratio can only be decreased or reset, not increased

Settings / Recording
- [ ] selecting a recording config returns the user to top level settings instead to recording settings

Settings / Onscreen Display
- [ ] selecting a font config returns the user to top level settings instead to OSD settings
- [x] OSD size and position settings can't be increased, only decreased or reset
- [x] selecting an overlay or kbd overlay returns the user to top level settings instead to Onscreen Display / Overlay Settings
- [x] overlay opacity can't be increased, only decreased or reset
- [x] overlay scale  can't be increased, only decreased or reset

Settings / Menu
- [x] selecting a wallpaper returns the user to top level settings instead of menu settings
- [ ] selecting a menu font returns the user to top level settings instead of menu settings
- [ ] not wrapping down: menu icon theme, menu shader pipeline,  menu color theme, menu alpha factor, menu scale factor, 
- [x] wallpaper opacity might as well be an integer [0....100]

Settings / User 
- [ ] You can trigger the OSK in language but it doesn't actually do anything
- [x] Language doesn't wrap down but wraps up

Settings / Directory
- [x] After changing any dir returns you to global settings, not to directory settings

Online Updater
- [x] If you back down from the core updater it drops you at the main menu instead of at the Online Updater menu
- [x] If you back down from the content downloader it drops you at the main menu instead of at the Online Updater menu

**Comment by fr500** [comment]
Now testing stuff in-game:

- [ ] gamepad hotkey + actions are not triggering while in the menu (can't exit by gamepad hotkeys in menu nor return to game)
* hotkeys are working fine in-game

Quick Menu / Cheats
- [ ] resetting cheat passes to zero results in a floating gear icon in the menu

Quick Menu / Shaders
- [ ] resetting cheat passes to zero results in an "eye" icon in the menu on top of the shader passes icon

**Comment by fr500** [comment]
@bparker06 unchecked
gamepad hotkey + actions are not triggering while in the menu (can't exit by gamepad hotkeys in menu nor return to game)

the "combo" is not affected, but say you set the guide button to menu toggle, it doesn't trigger to go back to game while in-menu, same for exit.

I personally use GUIDE as hotkey modifier, and L3 as exit, R3 as menu toggle, those no longer work (ie: GUIDE + L3 triggers from menu to game but not the other way around. GUIDE + R3 exits in game but not in menu)

I could get used to this new "limitation" but it was better the way it used to be imho

**Comment by Monroe88** [comment]
Pressing the "search button" results in an instant crash/segfault with the RGUI menu driver on the Windows 64-bit build. XMB and GLUI drivers seem to be fine.

**Comment by Kivutar** [comment]
@Monroe88 certainly due to the new OSK. I need to check if the callback exists before I invoke it.

**Comment by Kivutar** [comment]
I just pushed a commit to fix this.

**Comment by Monroe88** [comment]
Yes, that fixed the crash, thanks.

**Comment by rlabrecque** [comment]
Going Online Updater -> Core Updater -> back (Z) takes you back to the main menu, expected back to the Online Updater menu.

**Comment by lasers** [comment]
Settings --> Recording --> Output File --> key:Escape --> (STUCK)
Settings --> Recording --> Output File --> key:l,o,l,Return --> (STILL STUCK)

**Comment by lasers** [comment]
Settings --> User --> Accounts --> Retro Achievements

S --> U --> A --> RA --> Username --> Key:Escape --> (STUCK)
S --> U --> A --> RA --> Username --> Key:l,a,s,e,r,s,Return --> (STILL STUCK)

S --> U --> A --> RA --> Password --> Key:Escape --> (STUCK)
S --> U --> A --> RA --> Password --> Key:s,t,a,r,f,i,s,h,Return --> (STILL STUCK)

S --> U --> Language --> Key:Escape --> (STUCK)
S --> U --> Language --> Key:L,a,t,i,n,Return --> (STILL STUCK)

**Comment by lasers** [comment]
- [ ] The Basic Menu Controls need to be updated too to reflect something like this.

>Enter = OK button (RetroPad A)
>Backspace = Cancel (RetroPad B)
>Shift = Info (Retropad Select)
>Spacebar = Defaults (Retropad Start)

- [ ] The prompt behavior need to be corrected too.

**Comment by fr500** [comment]
I assume this means
Settings / User / Achievements / RetroArchievements.  

Enter does accept correctly in windows, linux and android. Not getting stuck here at all.

**Comment by lasers** [comment]
Sorry about annoying you. It's getting stuck here under Arch 6ce6fc3. We need some more people to confirm the outcome in order to break this tie.

**Comment by rlabrecque** [comment]
Online Updater --> Core Updater --> Key:Escape --> (Main Menu, Expected: Online Updater Menu)

Can we please fix the input from KB/Mouse on Windows affecting retroarch in the background? I just downloaded extra cores, and changed settings while submitting this even though RetroArch wasn't in focus.

**Comment by fr500** [comment]
That doesn't happen for me in Windows 10. If I alt-tab no keyboard inputs are registered.
I don't have pause in the background enabled either.

I'll update the OP to reflect the new changes.

**Comment by rlabrecque** [comment]
The background issue stopped happening for me when you fixed focus locking up I think.

**Comment by dankcushions** [comment]
> @bparker06 unchecked
gamepad hotkey + actions are not triggering while in the menu (can't exit by gamepad hotkeys in menu nor return to game)
>
> the "combo" is not affected, but say you set the guide button to menu toggle, it doesn't trigger to go back to game while in-menu, same for exit.
>
> I personally use GUIDE as hotkey modifier, and L3 as exit, R3 as menu toggle, those no longer work (ie: GUIDE + L3 triggers from menu to game but not the other way around. GUIDE + R3 exits in game but not in menu)
>
> I could get used to this new "limitation" but it was better the way it used to be imho

just a 'me too' for this one. other retropie users aren't liking it either: https://retropie.org.uk/forum/topic/5030/4-1-update-breaks-fundamentals
(retropie 4.1 includes a retroarch build with this change)

retropie's default combos are as follows:
https://github.com/retropie/retropie-setup/wiki/retroarch-configuration#hotkeys
(no keyboard)

**Comment by sergiobenrocha2** [comment]
You can add #2506 in the in-game / quick menu

**Comment by sergiobenrocha2** [comment]
You should put #4019 to the mix

**Comment by sergiobenrocha2** [comment]
If it's to increase user experience over menu, is it possible to add Open Archive as Folder behavior too?

When you chose that to load a game, you have this:

Parent directory
Filter unknown extensions
the-game.bin (CFILE)

It's somewhat unfriendly, you have to go down every time, why the menu doesn't start in the game position? Btw, it's related to #2604, why do we have this Parent directory option in a zipped file?

**Comment by sergiobenrocha2** [comment]
The menu starting at Parent Directory instead < Scan This Directory > is pretty annoying too. Regarding all stuff you do related to directories, the menu is always that unfriendly starting at Parent Directory

**Comment by lasers** [comment]
`Filter unknown extensions` is annoying too... especially with looping directories where you have to go in/out to refresh changes... We could move it to Settings right under `Show Hidden Files or Folders` or `User Interface`.

Please note that there is no default setting for `Filter unknown extensions` right now.

**Comment by sergiobenrocha2** [comment]
this "Filter unknown extensions" should be hidden when "Show Advanced Settings" = OFF

**Comment by fr500** [comment]
How is starting at Parent Directory unfriendly?

**Comment by fr500** [comment]
The only things I would change about the directory listing:
- Filter should refresh immediately
- Parent directory sometimes is weird. In windows it doesn't get to the drives... ever. top level dir seems to be the retroarch dir for some reason
- Retropad B (or BACK) should be used only to exit the listing, not to go ..

**Comment by sergiobenrocha2** [comment]
```How is starting at Parent Directory unfriendly?```

Because it's an option you use less than navigating into your content.

**Comment by fr500** [comment]
The next action is 99% of the time gonna be press Up or press Down to navigate so it makes no difference whatsoever

**Comment by fr500** [comment]
Unless you name your favorite game 1myfavoritegame.zip so it's always first

**Comment by sergiobenrocha2** [comment]
Well, it's unfriendly at least inside a zipped file

**Comment by lasers** [comment]
Hi. Let's stop the fight between settings inside `Video`. Some of them might fare well inside `User Interface`. See Suspend Screensaver, Display Framerate, or Use Fullscreen Mode.

Also, it does not make sense to display <Scan This Directory> in an empty folder.

**Comment by Kivutar** [comment]
These threads with more than one issues are impossible to follow. It's an invitation to disgress.

**Comment by fr500** [comment]
>Also, it does not make sense to display <Scan This Directory> in an empty folder.

it makes all the sense in the world in an empty folder because it could be just that, a rom with an unsupported extension.

**Comment by fr500** [comment]
> These threads with more than one issues are impossible to follow. It's an invitation to disgress.
I opened this issue because there are lots of bugs that need to be addressed, and also as an example of what would happen whenever we do a Q&A run.

I can't really spend any more time testing that I do already.

**Comment by lasers** [comment]
An empty folder wouldn't have anything inside to begin with.
I get what you're trying to say though.

It shouldn't say `No items.` then. Go for `No items (3 hidden).` or something as I can't tell if I have filter on every time I'm navigating through some directories.

**Comment by meleu** [comment]
> gamepad hotkey + actions are not triggering while in the menu (can't exit by gamepad hotkeys in menu nor return to game)

I'm not sure if this is the best place to announce it, but here it go:
The `input_menu_toggle` recovered its previous behavior. It's a toggle again.
I don't know which commit fixed it, but I'm using the https://github.com/libretro/RetroArch/commit/ee7787dd52a9444f21d6feb69893e4ae369cce4e (built Dec 15 2016) and it's working like before. :-)

**Comment by BenMcLean** [comment]
This stuff is killin me on Android.

**Comment by orbea** [comment]
I marked a few checkmarks for entries that seem fixed.
```
Settings / Driver
~~all these entries wrap at last entry, none wrap at first entry (has been for a long time)~~

Settings / Audio
~~Audio latency wraps up but doesn't wrap down~~

Settings / Logging
~~Verbosity level doesn't wrap down~~

Settings / Onscreen Display
~~selecting an overlay or kbd overlay returns the user to top level settings instead to Onscreen Display / Overlay Settings~~

Settings / Menu
~~wallpaper opacity might as well be an integer [0....100]~~

Settings / User
~~Language doesn't wrap down but wraps up~~
```

**Comment by twinaphex** [comment]
Outdated information, needs to be redone again.
