### ISSUE TITLE
(ios9) Updates past couple days cause instant crashing, can't load RA

### ISSUE THREAD

**Issue by Cepheidsong** [libretro/RetroArch#3900]
Hallo, for the past 2 or 3 days, I've been unable to load Retroarch even in the slightest- it crashes instantly when turning on.

Getting it through cydia, the ios9 version for 9.3.3, and it's been working great up until then- been updating with nightlies every day.

I've tried completely uninstalling and deleting any trace of RA, but even a fresh install it gives the same crash.  It doesn't even generate an error report.  The new installs aren't even creating the basic folders.

A long time ago when I had this issue, I think the cause was the version being sent to cydia was not ios9 compatible.  I tried loading the non-9 version to test and it's having the exact same speedy crash.  If it's an issue other than that, I'm not sure what to check.

**Comment by twinaphex** [comment]
I got a null pointer dereference crash at startup, this fixed it for me - 

https://github.com/libretro/RetroArch/commit/bd684065c38d7456784d416d67d29f2437d5ec91

**Comment by Cepheidsong** [comment]
Seems to be working all good now, thanks!

**Comment by twinaphex** [comment]
OK, good to know.

**Comment by Cepheidsong** [comment]
@twinaphex I dunno if it's okay to post after it's closed, but the cydia version after updating today started crashing again :<  I think it reverted the fix
