### ISSUE TITLE
udev: RetroArch on Linux (including Lakka) gives the Vendor ID and Product ID of the Bluetooth dongle, not the Bluetooth gamepad!

### ISSUE THREAD

**Issue by paalfe** [libretro/RetroArch#3903]
"RetroArch on Linux (including Lakka) > Main Menu > Information > System Information > Port #? device VID/PID" and "RetroArch on Linux (including Lakka) > Settings > Input User ? Binds > User ? Save Autoconfig" gives the Vendor ID and Product ID of the Bluetooth dongle, not the Bluetooth gamepad!

"tail -f /var/log/syslog" and "dmesg" gives the correct Vendor ID and Product ID in HEX, that has to be converted to Decimal.

---

Example:

$ tail -f /var/log/syslog
kernel: [27290.888768] input: 8Bitdo SNES30 GamePad as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/bluetooth/hci0/hci0:256/0005:2820:0009.002D/input/input59
kernel: [27290.888998] hid-generic 0005:2820:0009.002D: input,hidraw3: BLUETOOTH HID v1.00 Gamepad [8Bitdo SNES30 GamePad] on 28:b2:bd:78:cb:42

$ dmesg
[27290.888768] input: 8Bitdo SNES30 GamePad as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/bluetooth/hci0/hci0:256/0005:2820:0009.002D/input/input59
[27290.888998] hid-generic 0005:2820:0009.002D: input,hidraw3: BLUETOOTH HID v1.00 Gamepad [8Bitdo SNES30 GamePad] on 28:b2:bd:78:cb:42

Hex vid:pid = 2820:0009 -> Decimal vid:pid = 10272:9

**Comment by Alex131089** [comment]
I can confirm that too.
https://gist.github.com/Alex131089/2d8418a27164e78b1cf5b5881680332c
Also, that makes https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Microsoft_X-Box_One_S_pad_v2.cfg invalid (Asus VID : http://www.the-sz.com/products/usbid/index.php?v=0x0B05).

**Comment by Alex131089** [comment]
This might be a solution: 
- https://lists.launchpad.net/multi-touch-dev/msg00348.html
- https://github.com/XQuartz/xorg-server/blob/master/config/udev.c#L148

I'd have made a PR myself, but I don't know udev very well (especially the parent part, not sure you want the parent for the BT input device, the correct product attribute seems on the input device itself) and I don't have the environment to make tests.

**Comment by orbea** [comment]
Closing in favor of the older issue. https://github.com/libretro/RetroArch/issues/2961
