### ISSUE TITLE
--enable-opengles won't compile

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#3907]
```
CC gfx/drivers_shader/shader_null.c
In file included from ./libretro-common/include/glsym/glsym.h:30:0,
                 from gfx/drivers_shader/../common/../drivers/gl_symlinks.h:24,
                 from gfx/drivers_shader/../common/gl_common.h:35,
                 from gfx/drivers_shader/shader_null.c:31:
./libretro-common/include/glsym/glsym_es2.h:27:23: error: conflicting types for ‘GLint64’
 typedef long long int GLint64;
                       ^~~~~~~
In file included from ./libretro-common/include/glsym/rglgen_headers.h:55:0,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from gfx/drivers_shader/../common/../drivers/gl_symlinks.h:24,
                 from gfx/drivers_shader/../common/gl_common.h:35,
                 from gfx/drivers_shader/shader_null.c:31:
/usr/include/GLES2/gl2.h:63:25: note: previous declaration of ‘GLint64’ was here
 typedef khronos_int64_t GLint64;
                         ^~~~~~~
In file included from ./libretro-common/include/glsym/glsym.h:30:0,
                 from gfx/drivers_shader/../common/../drivers/gl_symlinks.h:24,
                 from gfx/drivers_shader/../common/gl_common.h:35,
                 from gfx/drivers_shader/shader_null.c:31:
./libretro-common/include/glsym/glsym_es2.h:28:32: error: conflicting types for ‘GLuint64’
 typedef unsigned long long int GLuint64;
                                ^~~~~~~~
In file included from ./libretro-common/include/glsym/rglgen_headers.h:55:0,
                 from ./libretro-common/include/glsym/rglgen.h:32,
                 from ./libretro-common/include/glsym/glsym.h:26,
                 from gfx/drivers_shader/../common/../drivers/gl_symlinks.h:24,
                 from gfx/drivers_shader/../common/gl_common.h:35,
                 from gfx/drivers_shader/shader_null.c:31:
/usr/include/GLES2/gl2.h:64:26: note: previous declaration of ‘GLuint64’ was here
 typedef khronos_uint64_t GLuint64;
```

Also, GLupeN64 GLES3 no longer works on Android, it just doesn't load the core, no crash or anything, it used to work.

**Comment by twinaphex** [comment]
I think this is as a result of your earlier changes to glsym.

Also, GLupen64 no longer working and mupen64plus no longer working at the same time is too close for comfort. I already speculated that your last change to GLSM might be the result of this, try to see if it works if you revert the last change you made to it.

**Comment by twinaphex** [comment]
I'm talking about this commit to GLSM -

https://github.com/libretro/RetroArch/commit/5fab3e224649eb518d8522eb463acde125f188f8

**Comment by twinaphex** [comment]
Hmm, the change to glsym's header was done by @kivutar, not you, so I take that back.

https://github.com/libretro/RetroArch/commit/07421c3cd4e45fdb13773d01c48381e0ec2afcbe

**Comment by twinaphex** [comment]
We do have a very big problem with this stupid GL/Khronos typedef for unsigned/signed 64-bit integer, on some platforms it's available, on others it's not. Might just be best if we try to avoid it as much as possible since it's not exactly portable.

**Comment by loganmc10** [comment]
The GLES2 version of glupen still works on Android, just not gles3, and it won't even load the core without a game, so I doubt it's something to do with the glsm code since that doesn't get executed until the game starts.

I can track down why the GLES3 version stopped working once I can compile with --enable-opengles again

**Comment by twinaphex** [comment]
I'm not sure if reverting kivutar's change will break it again for him. So first in order to progress we need to come up with a solution for that.

I'll invite @kivutar to this thread.

**Comment by Kivutar** [comment]
OK we can do this test: you revert my commit, I will apply it as a buildtime patch in lakka. It was needed for wetek devices and gles2.
If it fixes something on mupen, then we can keep things like that. If it fixes nothing, you revert the revert.

**Comment by loganmc10** [comment]
Reverting https://github.com/libretro/RetroArch/commit/07421c3cd4e45fdb13773d01c48381e0ec2afcbe fixes the compile for me

**Comment by twinaphex** [comment]
@loganmc10 This made Mupen64plus work for me again -

https://github.com/libretro/RetroArch/commit/f707d39c54c5cfe8acfd1af192d64614112b7ea1

**Comment by loganmc10** [comment]
Ya I was just going to say, this broke GLupeN64 GLES3 for me:

e512065d7dd69f914d0cadce1ab686e6b29dd5ef

**Comment by twinaphex** [comment]
@loganmc10 - Try to see if this solves the issue -

https://github.com/libretro/RetroArch/commit/cb23aec500cb1f0a3e167f9b44838754903e1d2e

**Comment by loganmc10** [comment]
Yep fixed now thanks!
