### ISSUE TITLE
[Suggestion] Clrmamepro core

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3909]
![clrnamepro_logo](https://cloud.githubusercontent.com/assets/852504/19855992/7f82bb52-9f45-11e6-9575-114de0cb71be.png)

Hello. This is a suggestion about an idea to create a clrmamepro core. This would allow people to rebuild and keep their game collections updated accordingly. Some changes are already made in the database and there will be some more changes in the future. This also may prevent some people from unnecessarily downloading the whole set again.

After clicking `Update Databases` under `Online Updater`, one could load clrmamepro core to see several options including `Rebuild Game Files` to rename their game files according to the new database (if any).

* Profiler --> `$DATABASE_DIR` --> `$CORRECT_DAT`
* Scanner <--- Display wrong names, missing, case sensitive, size, etc
* Rebuilder <--- Rebuild game files -- Useful for NAS?
* Merger <--- I never played with this so I don't know.
* About <--- Respect and stuffs goes in here.

Clrmamepro does not work under OSX/linux without wine. There is also RomCenter for Windows. This would make clrmamepro available on all platforms. 

Link: http://mamedev.emulab.it/clrmamepro/

**Comment by dankcushions** [comment]
at this point full romsets for mame cores past and present are so readily available on archive.org (etc) that if people are rebuilding sets they've already taken a wrong turn.

**Comment by fr500** [comment]
uh... clrmamepro is not open source.

**Comment by lasers** [comment]
Ah crap. I had it installed. Looks like it came from aur. All this for nothing. 
It would have been nice to have that. You have a good day, mister!
