### ISSUE TITLE
[Request] Switch the video driver gracefully

### ISSUE THREAD

**Issue by rz5** [libretro/RetroArch#3927]
ParaLLEl and beetle-psx-hw require the vulkan and gl drivers to be loaded, respectively. If the wrong video driver is loaded, RetroArch becomes unresponsive or crashes.

@Alcaro has mentioned that cores can request certain video drivers. With that in mind, I'd would like to see RetroArch handle the video driver request and switch to it as the user loads some content so the above cores don't crash.

Ideally, as the user scrolls between the different video driver options, these drivers would get loaded up immediately so the user doesn't have to restart RA manually.

**Comment by tony971** [comment]
#3297 
libretro/mupen64plus-libretro#381

I feel like at least one of these should be closed.

**Comment by rz5** [comment]
I'll bump your issue and close this one.
