### ISSUE TITLE
Some thumbnails are not displaying

### ISSUE THREAD

**Issue by GameDragon2k** [libretro/RetroArch#3932]
Not sure if this is a RetroArch issue or a libretro-thumbnails, so forgive me if this is in the wrong place.

There are certain games on my playlist that do not display snapshot or title thumbnails, even after using the Thumbnail Updater and the respective files being present. 

I'm not sure exactly what the issue is, as I know the filepaths are correct. I tried switching the filename of a working snap thumbnail to one that was non-working and it displayed just fine. So there is something wrong with the images themselves that causes it not to display. Or at least it doesn't seem filepath related.

Here are some example NES games that do not display thumbnails from the updater:
Defender II (USA)
Elevator Action (USA)
Guardian Legend, The (USA)
Star Force (USA)
Star Soldier (USA)

**Comment by lasers** [comment]
The listed NES thumbnails are displaying for me. I am not exactly sure what issue the thumbnails in general had with us. Could it be a bad/poor cache? It seems like a fresh OS installation on a new hard drive would fix this one. Do you have lot of free space? Also, what are you on? I'm on Arch Linux with SSD hard drive. I don't know if this is an issue with RetroArch or libretro-thumbnails. Hopefully we can get more confirmations that the listed NES thumbnails are working for them too.

**Comment by GameDragon2k** [comment]
I'm running on Windows 10 running on the latest nightly build.

The HDD I'm currently running has about 70GB free space. I couldn't tell you for sure if it's an OS issue. If it's means anything, I tried a fresh RetroArch installation on a different drive, with only Guardian Legend, The (USA) in a playlist, and another fresh thumbnail update, and it gave the exact same issue.

Just to be clear, for this particular game, the boxart and title thumbnails show perfectly. It's just the game snapshot that isn't.

Screen cap for reference. This one is attempting to use Named_Snaps.
![image](https://cloud.githubusercontent.com/assets/3225327/20028292/f88851da-a303-11e6-8f0a-56be31b36691.png)

This one is using Named_Titles. Works just fine.
![image](https://cloud.githubusercontent.com/assets/3225327/20028298/14bae89a-a304-11e6-8b22-59d1ebab98e6.png)

**Comment by lasers** [comment]
Oh snap... Confirmed. I'm seeing the missing snaps thumbnails for the your NES games and some more not in the list.

**Comment by GameDragon2k** [comment]
Yes, there are quite a handful of ones I didn't list, but whatever the issue is, it's obviously similar. 

The ones I listed are example of some games that do **not display snapshot thumbnail**, but displays title thumbnail. 

However, there are also games that do **not display title thumbnail**, but displays the snap thumbnail. 
It's odd.

**Comment by lasers** [comment]
Yeah. I really can't find anything. You're probably right about png compression issue. @RobLoach @Kivutar @fr500

**Comment by Tatsuya79** [comment]
Guardian Legend, The (USA):
Box    24bits
Snap  4 colors indexed
Title   16 colors indexed

Some indexed palettes are not supported it seems.

**Comment by Tatsuya79** [comment]
I tried to make several "strange" indexed PNG with Photoshop but I can't reproduce the problem: they all work with Retroarch.
My guess is those snaps are made in a broken way with some voodoo tools.

**Comment by xTMODx** [comment]
i have came across some Nintendo - Family Computer Disk System snap shots and title shots that do not display correctly i can fix them all but maybe we should find the root of the problem why they are not showing

**Comment by xTMODx** [comment]
a good example would be this
this title screen is not showing in retro arch "Disk Hacker - Version 1.0 (Japan) (Unl).png"
https://github.com/libretro-thumbnails/Nintendo_-_Family_Computer_Disk_System/blob/master/Named_Titles/Disk%20Hacker%20-%20Version%201.0%20(Japan)%20(Unl).png

this title screen is showing in retro arch "Disk Hacker - Version 1.2 (Japan) (Unl).png"
https://github.com/libretro-thumbnails/Nintendo_-_Family_Computer_Disk_System/blob/master/Named_Titles/Disk%20Hacker%20-%20Version%201.2%20(Japan)%20(Unl).png

cant find any difference

**Comment by orbea** [comment]
@GameDragon2k, @Tatsuya79 and @xTMODx Is this still an issue?

**Comment by Tatsuya79** [comment]
Yes, same snap for guardian legend fails to show up in xmb while it is displaying fine in QT.

**Comment by orbea** [comment]
Thanks for the update, strange issue...

**Comment by medievil1** [comment]
found the issue for this... the image names have to be EXACTLY the same... case matters... for example.. Gex 3 - Deep Cover Gecko (usa).png does not math the detected game name Gex 3 - Deep cover Gecko .. Cover on the image is Capital C but not in the playlist.. so the image wouldn't show .. same for MediEvil .. playlist has it as Medievil, but image is MediEvil

**Comment by orbea** [comment]
That makes sense, file names are case sensitive on unix based operating systems and I suppose that extends to RetroArch.

**Comment by Tatsuya79** [comment]
That's not the problem here.

**Comment by GameDragon2k** [comment]
I'm fairly sure the issue isn't due to any case sensitivity. As I mentioned, replacing the _bugged images_ with another png with the same exact filename does correct the issue.

**Comment by GameDragon2k** [comment]
@medievil1 Guardian Legend works for me currently on Windows. In fact, **all of the games in my initial post are working**. I believe some games are still giving issues but just to be sure, I will update my thumbnail pack and check again.

**Comment by Tatsuya79** [comment]
The thumbnails have been changed in between.
This is a problematic original one:
![guardian legend the usa](https://user-images.githubusercontent.com/6266038/51446531-ad43da00-1d13-11e9-8e93-9316eae09790.png)

**Comment by RobLoach** [comment]
I believe this is fixed since last year.
