### ISSUE TITLE
x/y menu navigation

### ISSUE THREAD

**Issue by DarkSpartan7** [libretro/RetroArch#3934]
Hi, I have been using retroarch nightly for some time now, i was used to the x/y menu navigation, which was much easier on a keyboard. Since an update , It was disabled But  I was searching for a way to re-enable X/Y button menu navigation, but no use. Please re-enable X/y menu navigation.

**Comment by twinaphex** [comment]
No, people wanted Enter/Backspace to work as OK/Cancel, and we made that switch now.
