### ISSUE TITLE
iOS touchscreen major issues

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#3937]
@kivutar We need to get on top of this fast before it becomes a major regression for the next release.

All of the touch input is now misaligned. 

Also, going to the playlists tab and then back to any other tab makes all settings disappear.

**Comment by Fadi5555** [comment]
Nice work. Thank you for taking care of iOS version of this amazing project.
I really hope to support dynarec recompiler (pcsx) as well.
