### ISSUE TITLE
SD write permissions on Android

### ISSUE THREAD

**Issue by tazguy79** [libretro/RetroArch#3945]
It seems as though when an sd card is mounted as external storage RetroArch has no write permissions. Many other apps have to explicitly ask for them, but after they do they have free access. I am currently using a workaround, but would love native support.

**Comment by fr500** [comment]
I have been trying to add this but I'm no java dev, it's on the staging branch if anyone is interested in fixing.

**Comment by Aaahh** [comment]
@fr500 Mind pointing me to where the code is?
