### ISSUE TITLE
Show images for awarded achievements [$80]

### ISSUE THREAD

**Issue by leiradel** [libretro/RetroArch#3946]
Right now we use the OSD to show awarded achievements, but that doesn't support images. If we want to be on par with the Retro Achievements emulators with this respect, we must show the images.

Retro Achievements emulators show achievements like consoles do, with them scrolling into view and then going away, just like consoles do, it would be cool if we could do the same.

**Comment by meleu** [comment]
Indeed, it would be really cool!

In the investigations we were making a few days ago I noticed that all the cheevos badges for a specific game are downloaded when a logged user opens a ROM in the official emulator.

The image files are stored at `RACache\Badge\` subdirectory at the emulator's directory structure. The filenames have the following pattern:

```txt
cheevonumber.png
cheevonumber_lock.png
```

Example
```txt
03942.png
03492_lock.png
03943.png
03493_lock.png
```

The files persist after the emulator is finished.

If it helps, here is a ziped version of my `RANes\RACache\Badge\` with some images: 
[Badge.zip](https://github.com/libretro/RetroArch/files/598087/Badge.zip)

**Comment by RobLoach** [comment]
Would we need to use some sort of Overlay component for this?

**Comment by Kivutar** [comment]
Either that, either we use some code similar to the OSD code.

**Comment by leiradel** [comment]
I think the main issue is that the images will appear with different sizes depending on the game resolution, i.e. Stella vs. Parallel with a high resolution setting. I don't know how to solve this though. Maybe scale them according to the resolution.

**Comment by SuperMeatBro** [comment]
I'm pretty sure on Steam the box that appear when you get an achievement is bigger when you use a low resolution. I dont really see this as an issue,  except if it takes all the screen. Also, Isn't The overlay on retroarch is completely independant of the resolution of the game? My two cents about this.

**Comment by SuperMeatBro** [comment]
Maybe let the user customize the size of the badge showing on screen?

**Comment by Kivutar** [comment]
We can just make these images proportional to the screen height while conserving aspect ratio

**Comment by leiradel** [comment]
Retro Achievement badges are 64x64, but how they will show up in the screen depends on how RetroArch is setup. If you're using a windowed mode and scaling up content, the badge will appear smaller than with no scaling.

@Kivutar yes, making it proportional to the screen height would be the more consistent approach.

**Comment by pralima87** [comment]
This bounty is $60 right now.
Does the title auto-updates?

**Comment by lilbud** [comment]
Has there been any progress on this?

**Comment by fr500** [comment]
Hmmm well @GameDragon2k did the heavy lifting (the badges are downloaded and stored now), now someone needs to implement it in the OSD

**Comment by pralima87** [comment]
In bountysource this bounty is at $60 now could someone update the title?
And it doesing even shows in the bounties list :/
https://www.bountysource.com/teams/libretro/bounties

**Comment by mmadsen77** [comment]
Yeah, it's not gonna get done if bounty hunters can't see it, and this would be a really nice addition. Can this be addressed?

**Comment by Iraito** [comment]
I would like a simple but effective design like this one, the only thing is that the badges are too small (64x64), the one in this picture has been upscaled to 128x128, which to me seems like a perfect compromise. 
![tetsuyuki](https://user-images.githubusercontent.com/3323267/39420668-e50ea264-4c65-11e8-86c7-fbc461aacc32.jpg)

**Comment by fr500** [comment]
Kinda started working on this

https://media.discordapp.net/attachments/353363923333808128/478772378051280906/unknown.png?width=1568&height=908

**Comment by Iraito** [comment]
Thank you, it's pretty much the only major flaw regarding retroachievements in retroarch, what style will you use for the graphics ? the mockup i did should make possible even a pretty long description, i don't if it's feasible though.

**Comment by fr500** [comment]
I don't know about the style, I'm thinking rectangle with badge and title, that's all.
One think I need to know is that if it's ok for it to be GL only because I'm certainly not gonna do it for every video driver.

**Comment by Iraito** [comment]
Well GL is a pretty good standard API compatible with most hardware, i think it's fine, you can release this feature only GL compatible but in the future it can always be adapted to other APIs.

**Comment by leiradel** [comment]
> I don't know about the style, I'm thinking rectangle with badge and title

I think it's very good, I'd just add the description.

**Comment by GKontizas** [comment]
Do we have any updates?
If it's really happening soon I'm definitely going to contribute to the bounty, it's the only thing that was bothering me with retroarch. You are amazing @fr500

**Comment by LiveFastCyYoung** [comment]
> I don't know about the style, I'm thinking rectangle with badge and title, that's all.

What Iraito posted as a mockup earlier would be perfect.

**Comment by Iraito** [comment]
> What Iraito posted as a mockup earlier would be perfect.

Thank you, to be honest i would like to see that design being used too.

**Comment by fr500** [comment]
I don't have an ETA, I have other stuff to do IRL

**Comment by pralima87** [comment]
If you want to see this happen just make a contribution and stop asking for ETAs. 
This entitle behavior will just annoy the dude.
Also should he really stop all he is doing for 60 bucks??

**Comment by fr500** [comment]
It's no big deal I'm not like that. But yeah I'm busy with other things.

**Comment by TheJobs1** [comment]
In bountysource this bounty is at $80 now could someone update the title?

**Comment by alissongamer** [comment]
> 
> 
> Eu gostaria de um design simples, mas eficaz como este, a única coisa é que os crachás são muito pequenos (64x64), o da imagem foi ampliado para 128x128, o que para mim parece um compromisso perfeito.
> ![tetsuyuki](https://user-images.githubusercontent.com/3323267/39420668-e50ea264-4c65-11e8-86c7-fbc461aacc32.jpg)

I like this design.

**Comment by alissongamer** [comment]
> 
> 
> I would like a simple but effective design like this one, the only thing is that the badges are too small (64x64), the one in this picture has been upscaled to 128x128, which to me seems like a perfect compromise.
> ![tetsuyuki](https://user-images.githubusercontent.com/3323267/39420668-e50ea264-4c65-11e8-86c7-fbc461aacc32.jpg)

I Like.

**Comment by alissongamer** [comment]
Some Update for this?

**Comment by Keltron3030** [comment]
Added $10 as well.

**Comment by natinusala** [comment]
I just remembered the bounty and figured I would post an update here (so that people can see it on BountySource too)

The ground work for such notifications is done (in the form of menu widgets, see #8198), but it had unforeseen consequences that led us to remove it from RetroArch (is basically broke everything). 

Now everything is fixed and I'm working on introducing back every widget one by one. Once this is done, I will make an actual achievement notification, with badge, as a menu widget, which will directly solve this issue.

I'm currently sidetracked by adding thumbnails support to ozone though, so no ETA but we're getting there :)

**Comment by Jandalf81** [comment]
Hey natinusala, that's great to hear! Just wondering, will this be usable from outside of RetroArch?

I'm asking because I'm still looking for a better solution to create notifications for a script I created (see https://github.com/Jandalf81/rclone_script). This script is running on RetroPie and until now creates notifications via ImageMagick to be shown by PNGview. As you might imagine, this is quite clunky...

I suspect the system you are implementing will be usable only by RetroArch itself but asking never hurt anyone... ;-)

**Comment by natinusala** [comment]
No it's tied to RetroArch, it can be seen as an extension of the existing menu drivers

**Comment by Jandalf81** [comment]
That's what I tought... Thanks for answering and creating this notification system, though! I'm really looking forward to seeing this in action when it's ready. Take your time!

**Comment by natinusala** [comment]
Status update: the notification itself is pretty much done, I just need to add a queue to avoid breaking everything when multiple achievements unlock at the same time.

This is how it turned out: https://twitter.com/natinusala/status/1116365181205008386

It will be available for everyone once menu widgets are finished as a whole, and enabled by default. In the meantime, you can build from source and enable widgets with `./configure --enable-menu_widgets` to try it (PR submitted).

**Comment by TheJobs1** [comment]
Hey @natinusala, thanks for the update. I have a question if you don't mind. Is there any way to change place notification? Don't work well with overlay preset. Sorry for my bad english and thanks again.

**Comment by natinusala** [comment]
There is none currently but be assured that it's planned ;)

**Comment by natinusala** [comment]
What do you mean by "not working"?
