### ISSUE TITLE
(Windows) --enable-nuklear build error

### ISSUE THREAD

**Issue by Monroe88** [libretro/RetroArch#3947]
Trying to build with --enable-nuklear in MSYS2 (with Mingw-w64 5.3.0) results in a build error.

http://hastebin.com/raw/pumetoraye

**Comment by Alcaro** [comment]
> menu/drivers/nuklear/../../../deps/nuklear/nuklear.h:2745:15: warning: 'nk_to_upper' defined but not used [-Wunused-function]

shut up gcc

> menu/drivers/nuklear/nk_wnd_main.c:53:4: warning: implicit declaration of function 'strlcpy' [-Wimplicit-function-declaration]
> menu/drivers/nuklear.c:345:4: warning: implicit declaration of function 'menu_display_font_main_deinit' [-Wimplicit-function-declaration]

missing headers, needs fix

> gfx/drivers_font_renderer/stb_unicode.c:120:28: warning: 'y1' may be used uninitialized in this function [-Wmaybe-uninitialized]
> gfx/drivers_font_renderer/stb_unicode.c:119:31: warning: 'x0' may be used uninitialized in this function [-Wmaybe-uninitialized]
> input/drivers/dinput.c:478:13: warning: 'ret' may be used uninitialized in this function [-Wmaybe-uninitialized]

someone better take closer a look at those

i'd do it myself if it wasn't 2am

> gfx/include/d3d9types.h:26:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]

shouldn't those be behind an ifdef or two or 500

> gfx/common/../include/d3d9/d3dx9core.h:669:1: warning: multi-line comment [-Wcomment]

gcc bug, comment ending in \ should not warn if the next line starts with //

> D:\Msys2\home\Monroe88\libretro-super\retroarch/menu/drivers/nuklear/nk_common.c:50: undefined reference to `stbi_load'
> D:\Msys2\home\Monroe88\libretro-super\retroarch/menu/drivers/nuklear/nk_common.c:66: undefined reference to `stbi_image_free'

someone better #define STB_IMAGE_IMPLEMENTATION somewhere

or switch that entire thing to RPNG, I checked every single caller and they're all random hardcoded paths ending with png

**Comment by Alcaro** [comment]
on a mostly related note, why do both of those exist

https://github.com/libretro/RetroArch/blob/master/menu/drivers/nuklear.c#L250 
https://github.com/libretro/RetroArch/blob/master/menu/drivers/nuklear/nk_wnd_file_picker.c#L47

**Comment by twinaphex** [comment]
This commit should fix Nuklear again -

https://github.com/libretro/RetroArch/commit/14f56e15c924fe3f40b149b08b45f0f7f8535680

However, we really need somebody to be taking this somewhere, this menu driver isn't getting fleshed out by itself.

**Comment by fr500** [comment]
A big part of the problem is that none of us know how to design a GUI, and that it stopped rendering with CG again, I remember fixing that but it no longer works.

Then it stopped building altogether.

**Comment by Monroe88** [comment]
Closing this since --enable-nuklear build is working. I wanted to look at the code myself but it will be a long time before I can actually make anything.

**Comment by fr500** [comment]
I think we should take a different approach to this (design first)
I've been tinkering with it too
