### ISSUE TITLE
[Windows] \o/

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#3949]
Muh OCD

![1](http://i.imgur.com/CKu3i7E.png)

![2](http://i.imgur.com/YqGshmh.png)

![3](http://i.imgur.com/5nXSJ5U.png)

![4](http://i.imgur.com/wnk3IGx.png)

![5](http://i.imgur.com/JyeFlbj.png)

![6](http://i.imgur.com/mPwEyJk.png)

**Comment by lasers** [comment]
*cringes hard*

I think you can't do anything about it. Take it or leave it. Just stop looking in there.

**Comment by rlabrecque** [comment]
It shouldn't be hard to rewrite those with the platform specific separator when you combine the relative path with the base path. There's probably already platform separator code somewhere in libretro.

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/commit/896aaf530b22cae16678566965f45f784f444f21
