### ISSUE TITLE
[Windows] Not responding after focus loss

### ISSUE THREAD

**Issue by rlabrecque** [libretro/RetroArch#3950]
When RetroArch (latest nightly) loses focus on Windows you usually can't regain focus without it going `Not Responding`.

Simple repro:
- Launch retroarch.exe
- Minimize RetroArch
- Clicking RetroArch in the task bar will no longer bring it up

This did not happen in 1.3.6

The renderer and dinput threads are still going as the background keeps going and your input from outside windows is still acted upon. (Which is a completely separate undesirable issue)

**Comment by twinaphex** [comment]
Yeah this is a recent regression, @fr500 pointed it out to me yesterday.

He is going to try to do a bisect to see at which point it started to happen. It does not affect Linux/OSX, only Windows.

**Comment by retro-wertz** [comment]
this also happens to me(Windows) this started starting november release nightlies.

**Comment by twinaphex** [comment]
Use the latest nightlies, it should be fixed now.

**Comment by retro-wertz** [comment]
oh great thanks. it is fixed.

**Comment by rlabrecque** [comment]
Yep fixed for me too!
