### ISSUE TITLE
Save state issues

### ISSUE THREAD

**Issue by andres-asm** [libretro/RetroArch#3967]
Saving states is now a task.
Saving states can take a while (PPSSPP for example has ~90MB saves)

This is a problem, specially on android were storage speeds vary wildly. I just tried on a Shield ATV with a 40MB/s SD card and sometimes it's really quick, some other times it's a 1 minute operation.

I'm totally OK with it except for one problem. If you have save state on exit and close content there is no indication of RA being busy saving the state. 

The OSD doesn't show the status.

Also with such big savestates I noticed that it always does a load state first for some reason? (the Loading State message prints for a few frames before the Save State message appears)

**Comment by orbea** [comment]
@fr500 Is this still an issue? Do you have any clear ideas of what could be done to improve it further?

**Comment by fr500** [comment]
yeah still happens
No real way to fix it other than preventing RA from actually quitting while the savestate is still.. being saved

**Comment by orbea** [comment]
That sounds possible, not that I am sure how yet...

**Comment by sonninnos** [comment]
Autostatesaving is no longer a task, therefore closing time: https://github.com/libretro/RetroArch/pull/16061
