### ISSUE TITLE
Reincast not saving data/saves to ~/.config/retroarch?

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#3968]
Tried to load a cdi file manually on the reincast core since it wasn't recognized as a 'good dump' on the scan.

Got this, that probably doesn't have to do with the scan failing:
[reicast]: Got size: 640 x 480.
Creating dir: /media/i30817/Games/Sega Dreamcast/Record of Lodoss War//dc/data
mkdir(/media/i30817/Games/Sega Dreamcast/Record of Lodoss War//dc/data) error: No such file or directory.
context_reset.
Linux paging: 00001000 00001000 00000FFF
DEBUGBREAK!

"/media/i30817/Games/Sega Dreamcast/Record of Lodoss War" is the directory holding the CDI game. I have zero idea why it tried to create a directory with a empty name '//', but it probably aint good.

On another related matter, even if the name was legal, it wouldn't work, because the directory, and indeed the whole 'Games' mount on media is a read only compressed squash file, so it can't be written to. Normally i'm confident that retroarch redirects emulator cores attempts to write elsewhere than the retroarch directories, but the reincast core is new and it appears that some redirection is missing or flawed.

**Comment by fr500** [comment]
This is not the place to discuss reicast or it's problems
https://github.com/libretro/reicast-emulator

**Comment by i30817** [comment]
But i'm actually using your libretro core. I thought you are the people that patch cores so they don't save things in places outside of your directories.

**Comment by i30817** [comment]
opened there then.
