### ISSUE TITLE
RetroArch exits immediately on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [libretro/RetroArch#3969]
The process exits almost immediately with exit code 0. It prints 3 warnings.

```
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR
...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
...
RetroArch [WARN] :: [SDL]: Failed to initialize haptic device support: SDL not built with haptic (force feedback) support
...
RetroArch [INFO] :: [X11]: Saved monitor #0.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
<exits here>
```

1.3.6 on FreeBSD 11

**Comment by ehs03y3ol** [comment]
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.

Deactivate GLSL shaders on the system, could be you don't have support on FBSD for this?

**Comment by hizzlekizzle** [comment]
The things to try would be to open your retroarch.cfg in a text editor and try menu_driver = "rgui" and if that doesn't fix things, video_driver = "x11" or "sdl2"

**Comment by yurivict** [comment]
```menu_driver = "rgui"``` by default. 

Setting ```video_driver = "x11"``` prints:
```
RetroArch [ERROR] :: Couldn't find any video driver named "x11"
```
Do you know where it is not enabled?

Setting ```video_driver = "sdl2"``` works.

It looks like GLSL is btroken on FreeBSD, I am trying to figure out why.

**Comment by ehs03y3ol** [comment]
Probably some GLSL filters/engine are depending on OGL 3.3 support and up. Anyway they are performance hungry and i don't recommend to you unless do you have more than 600 GFlops GPU.

About "x11" driver, we don't have any software render for now, it's implemented on OGL or SDL directly.

**Comment by ehs03y3ol** [comment]
Might be ask here? https://github.com/libretro/common-shaders/issues

**Comment by yurivict** [comment]
I can't tell if GLSL is or isn't supported on FreeBSD, or this might just be some bug or version mismatch like you are saying. FreeBSD NVidia driver doesn't support some things, like CUDA. I am trying to figure this out with the driver maintainer and on forums. I am investigating this.

**Comment by yurivict** [comment]
Closing this here, since this is most certainly a FreeBSD problem. Thank you for your timely attention, and suggestions.
