### ISSUE TITLE
QuickNES crashes RetroArch on Android

### ISSUE THREAD

**Issue by meleu** [libretro/RetroArch#3973]
I tried to use QuickNES to get some cheevos on my Android phone after the latest RetroArch fixes. But when I load Metroid, RetroArch crash.
I'm using the RetroArch_GIT compiled in 6 November 2016.

This problem doesn't happen with FCEUmm (Android), but unfortunately some Metroid cheevos work on QuickNES only.
I tested Metroid with QuickNES on my Linux x86 and on my Raspberry Pi, and there's no problem. **It's happening on Android only.**

Testing Android/RetroArch/QuickNES with "G.I.Joe - A Real American Hero", the game freezes. I can invoke RGUI and everything, but the game freezes just after I start it.
Testing again with "Felix the Cat", RetroArch crashes...

Updated RetroArch_GIT getting a version compiled in 8 November 2016 and repeated the test. Same problem

EDIT: adding more info.

![screenshot_20161109-111143](https://cloud.githubusercontent.com/assets/8508804/20139501/9792bd4e-a66d-11e6-8fab-0392881dc4a2.png)

**Comment by ehs03y3ol** [comment]
No architecture, no SOC device no Android version, no compilation... 

Snapdragon A53 with Android 5.1.1: confirm last SVN from "update" just does show black screen, can confirm pre-update version was working fine. 

Looking at the sources at /QuickNES_Core/, some one made 2 days ago add changes to "Makefile". Might be that last changes broken something?

**Comment by ehs03y3ol** [comment]
```
# ARM
else ifneq (,$(findstring armv,$(platform)))
	TARGET := $(TARGET_NAME)_libretro.so
	fpic := -fPIC
	SHARED := -shared -Wl,-version-script=link.T -Wl,-no-undefined
	ifneq (,$(findstring cortexa5,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a5
	else ifneq (,$(findstring cortexa8,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a8
	else ifneq (,$(findstring cortexa9,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a9
	else ifneq (,$(findstring cortexa15a7,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a15.cortex-a7
	else
		PLATFORM_DEFINES += -marm
	endif
	ifneq (,$(findstring softfloat,$(platform)))
		PLATFORM_DEFINES += -mfloat-abi=softfp
	else ifneq (,$(findstring hardfloat,$(platform)))
		PLATFORM_DEFINES += -mfloat-abi=hard
	endif
	PLATFORM_DEFINES += -DARM
```
```
# ARM
else ifneq (,$(findstring armv,$(platform)))
	TARGET := $(TARGET_NAME)_libretro.so
	fpic := -fPIC
	SHARED := -shared -Wl,-version-script=link.T -Wl,-no-undefined
	ifneq (,$(findstring cortexa5,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a5
	else ifneq (,$(findstring cortexa8,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a8
	else ifneq (,$(findstring cortexa9,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a9
	else ifneq (,$(findstring cortexa15a7,$(platform)))
		PLATFORM_DEFINES += -marm -mcpu=cortex-a15.cortex-a7
	else
		PLATFORM_DEFINES += -marm
	endif
	ifneq (,$(findstring softfloat,$(platform)))
		PLATFORM_DEFINES += -mfloat-abi=softfp
	else ifneq (,$(findstring hardfloat,$(platform)))
		PLATFORM_DEFINES += -mfloat-abi=hard
	endif
	PLATFORM_DEFINES += -DARM
```

**Comment by meleu** [comment]
Sorry. Maybe this screenshot can give some info:

![screenshot_20161109-111143](https://cloud.githubusercontent.com/assets/8508804/20139501/9792bd4e-a66d-11e6-8fab-0392881dc4a2.png)

**Comment by ehs03y3ol** [comment]
Confirmed to be bad upload/compilator error:

There is no updates in source code
Working on rep https://buildbot.libretro.com/nightly/android/2016-11-07_cores/armeabi-v7a/

BUT, autoclosing in few seconds Rush n' Attack (U)

Might be buildbot is failing?

**Comment by ehs03y3ol** [comment]
Check it that Super Mario Bross (Rev 0A PAL) works now great for me. Rush n' Attack is not working by a bug of the core.  

Can we said this is magically fixed?

Please check if SMB Rev 0A PAL woks.
If it's a core issue address on https://github.com/libretro/QuickNES_Core

**Comment by fr500** [comment]
It's probably due the updated toolchain, gonna make that core build with r10e I guess.

**Comment by meleu** [comment]
I can't see the issue tracker on QuickNES_Core repository...

**Comment by ehs03y3ol** [comment]
Here:
https://github.com/kode54/QuickNES_Core/issues/6

**Comment by fr500** [comment]
@meleu can you try again?

**Comment by meleu** [comment]
@fr500 sure. Here is my feedback:

Using the same RetroArch I was using when I started this issue (build date 8-november), went to Online Updater -> Core Updater and donloaded QuickNES again.
Tested with Metroid, and QuickNES is still crashing RetroArch.

Then I used f-droid to update RetroArch. Now I'm using the RetroArch built on 14-November (today). Tested with Metroid, and QuickNES is still crashing RetroArch.

I see no changes on the QuickNES repositories (libretro and kode54) since I started this issue. Has something changed? Is it just the compilation method?

Thanks!

**Comment by fr500** [comment]
Quicknes works fine for me in my NVidia Shield Portable.

**Comment by fr500** [comment]
Actually it works with MM2 but it crashes with Metroid.
So it's likely a core issue.

**Comment by meleu** [comment]
I opened Mega Man 2 with QuickNES now. Uhmmm... good. No crash.
Started the game, chose Metal Man, cool! it's working!
Went to the right and got the Energy Tank **CRASH!** RetroArch stopped :-(

**Comment by ehs03y3ol** [comment]
Can tell you the same, crash when horizontal scroll starts

**Comment by fr500** [comment]
Enabled the bug tracker for the core, use that instead please.

**Comment by retro-wertz** [comment]
This should be working now in latest commit....
