### ISSUE TITLE
Unicode not working for file names on Windows

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#3975]
On win7 x64 I can display the menu items in Japanese with XMB and the default font.ttf but it's not displaying Japanese when browsing files named in that language.

I'd like to keep English for menu and see/use Japanese files too.

**Comment by bparker06** [comment]
So you can view Japanese filenames when RetroArch's language is set to Japanese, but not English?

**Comment by Tatsuya79** [comment]
No, I can't see Japanese filenames at all.

Only menu items work when language is Japanese.

**Comment by bparker06** [comment]
Ok, I can confirm this on Windows, works fine under Linux though.

**Comment by Alcaro** [comment]
Conclusion: Someone needs to rewrite libretro-common/file/retro_dirent.c (and maybe a few more places) to use the UTF-16 APIs.

Or install [WuTF](https://github.com/Alcaro/Arlib/tree/master/arlib/wutf); it makes FindFirstFile/etc use UTF-8 instead. <sup>Can't promise it won't steal your soul, though</sup>

**Comment by bparker06** [comment]
@Tatsuya79 This should be working in the current git master if you have a chance to try it out. If you're using nightly releases it may not be available until later today or tomorrow. Thanks

**Comment by Tatsuya79** [comment]
Thanks, but it's crashing at start on my compile version.
I'll test again with the nightly build.

**Comment by Tatsuya79** [comment]
It's working with today nightly! 
I can see my Japanese named videos and launched them in ffmpeg without problem.
I tried to compile it myself once again with MSYS and GCC 5.3 and that's now working perfectly after a git pull.
No clue what happened but everything is good now.

Thanks for your work. :)
