### ISSUE TITLE
Provide a default gamepad autoconfig

### ISSUE THREAD

**Issue by magwe** [libretro/RetroArch#3980]
I have a bunch of cheap gamepads from different vendors using different USB encoders. One thing they seem to have in common is that they all share the same button mapping that I believe is modeled after the button mapping of PlayStation DualShock USB gamepads. For gamepads with with fewer buttons the mapping is still the same for buttons that mach the physical layout such as a SNES gamead.

```
Button number: (0)  (1)  (2)  (3)  (4)  (5)  (6)  (7)  (8)  (9) (10) (11)
DualShock:     Tr    O    X   Sq   L1   R1   L2   R2   Se   St   L3   R3
SNES gamepad:   X    A    B    Y    L    R   __   __   Se   St   __   __ 
```

I think this should be the default mapping for any unrecognised gamepad that doesn't have a matching .cfg file. 

```
input_x_btn = "0"
input_a_btn = "1"
input_b_btn = "2"
input_y_btn = "3"
input_l_btn = "4"
input_r_btn = "5"
input_l2_btn = "6"
input_r2_btn = "7"
input_select_btn = "8"
input_start_btn = "9"
input_l3_btn = "10"
input_r3_btn = "11"

```

Then for the digital only game pads there is

```
input_left_axis = "-0"
input_right_axis = "+0"
input_up_axis = "-1"
input_down_axis = "+1"
```

and for "DualShock" gamepads

```
input_left_btn = "h0left"
input_right_btn = "h0right"
input_up_btn = "h0up"
input_down_btn = "h0down"
input_l_x_plus_axis = "+0"
input_l_x_minus_axis = "-0"
input_l_y_plus_axis = "+1"
input_l_y_minus_axis = "-1"
input_r_x_plus_axis = "+2"
input_r_x_minus_axis = "-2"
input_r_y_plus_axis = "+3"
input_r_y_minus_axis = "-3"
```

Those two sections do not redefine any mappings (one has input_left_axis = "-0" and on has input_left_btn = "h0left" and input_l_x_minus_axis = "-0") so maybe both could be defined at the same time?

**Comment by orbea** [comment]
This will just cause a lot of new users to complain that their gamepad is broken with RetroArch. Users should use the online updater to get joypad autoconfig. For missing configs they can be added or mapped manually.
