### ISSUE TITLE
Enable onscreen keyboard overlay (False Flag)

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#3982]
Using this option does not disable the onscreen keyboard overlay...
```
input_osk_overlay_enable = "false"
```
... and will break some prompt leaving you stuck. I reported "stuck inside prompt everywhere" issue several days ago too. Menu issues: https://github.com/libretro/RetroArch/issues/3899#issuecomment-258596853.

You can escape by holding down `Enter` for some seconds... just long enough to loop you out of the warfare. Arch64 e99b25a. (Latest)

**Comment by lasers** [comment]
I mentioned this days ago.
`- [ ] The prompt behavior need to be corrected too.`

The prompt behavior works correctly with `input_osk_overlay_enable = "false"`.
With `input_osk_overlay_enable = "true"`, it jumps ahead with whatever I typed in.

**Comment by lasers** [comment]
Commit b9c6fa5 fixed the `stuck inside prompt everywhere`. Thanks @bparker06 :-)
Commit b9c6fa5 fixed the `jumps ahead with whatever I typed in`. Thanks @bparker06 :-)

TODO: Disable the onscreen keyboard overlay if `input_osk_overlay_enable = "false"`.

**Comment by twinaphex** [comment]
input_osk_overlay_enable is removed now.

**Comment by lasers** [comment]
Thanks @twinaphex.  I'll close this.
Please check and see if this possible leftover settings should be removed too.
```
*input_osk_toggle = "f12"
*input_osk_toggle_btn = "nul"
*input_osk_toggle_axis = "nul"
```
