### ISSUE TITLE
Snes multitap

### ISSUE THREAD

**Issue by DarkKinof** [libretro/RetroArch#3983]
Hi, a first, thanks for your great work with retroarch/libretro.
This report is for SNES MULTITAP support.
I found closed issue about this problem, and check another time libretro cores (v1.3.6)

Today SNES9x core work without any problem with multitap games.
But Bsnes w/o mercury don´t work, games show multitap detection (bomberman, Tiny Toon Adventures - Wacky Sports Challenge, etc) like SNES9x core, but 3, 4 and 5 players don´t move.

I user same cfg file in both cases, only change core DLL into configuration file.
Regards.

**Comment by hizzlekizzle** [comment]
Cores handle extra peripherals like multitaps and lightguns differently. I think for bsnes, you have to set the second controller's device to 'multitap' and then configure the extra controllers after that...?

**Comment by DarkKinof** [comment]
Hi,
Thanks for your response. I recheck all pad, and this is the result (same in both cores)
Pad-1.   Snes Pad
Pad-2.   Multitap
Pad-3 and highers, Retro pad

Pad 3 and highers only admit Retro pad or None.

I think Snes9x and Bsnes share Pad configuration, but, while Snes9x work with out any problem, Bsnes don't send user inputs to Pads 3 and below.

**Comment by KyleMcCarley** [comment]
Seems like this is a dead thread now, but this is the only place I've found where somebody describes exactly the issue I'm having. I'm using bsnes mercury, I have input 1 set to SNES Pad, input 2 set to Multitap, and the only options I have for inputs 3 and 4 are RetroPad and None. Three Xbox One controllers and a 360 controller are all plugged in, they all work to navigate Retroarch menus, but whichever devices are set to inputs 3 and 4 don't register in any games. The games are recognizing the Multitap setting, but no amount of button mashing gets anything to happen for players 3 or 4. Does anybody have any pointers?

**Comment by retro-wertz** [comment]
probably post this in related cores sections as this is not a retroarch
issue.

**Comment by orbea** [comment]
This is not a RetroArch issue and the bsnes cores are not actively maintained. I would just suggest to use snes9x.

**Comment by DarkKinof** [comment]
Hi,
thanks for your help and your great work with the other cores.
Regards.

________________________________
De: orbea <notifications@github.com>
Enviado: jueves, 27 de diciembre de 2018 1:06
Para: libretro/RetroArch
Cc: DarkKinof; Author
Asunto: Re: [libretro/RetroArch] Snes multitap (#3983)


Closed #3983<https://github.com/libretro/RetroArch/issues/3983>.
