### ISSUE TITLE
Database error, Legend Of Legaia for PSX

### ISSUE THREAD

**Issue by OGWillikers** [libretro/RetroArch#4001]
Hello,
I have both the dumps of the demo and game.

Legend Of Legaia (USA) with serial SCUS-94366 loads the demo.
Legend Of Legaia (USA) (Demo) with serial SCUS-94254 loads the retail game.

**Comment by lasers** [comment]
I think RetroArch collect, convert, and merge databases from few sites. If there was a mistake, you might want to take it up with [Redump,](http://redump.org/) [Trurip,](http://trurip.org/) and/or [TOSEC](http://www.tosecdev.org/).

Here's the database.
```
name "Legend of Legaia (Europe)"
serial "SCES-01752"

name "Legend of Legaia (France)"
serial "SCES-01944"

name "Legend of Legaia (Germany)"
serial "SCES-01945"

name "Legend of Legaia (USA)"
serial "SCUS-94254"

name "Legend of Legaia (USA) (Demo)"
serial "SCUS-94366"
```
_└── From libretro-database/dat/Sony - PlayStation.dat_

I searched `SCUS-94254` and `SCUS-94366`. The entries in database seems to be in sync with the search results too. Is it possible that you mixed them up since you say you have both dumps? In any case, @RobLoach might be able to help you better.

**Comment by OGWillikers** [comment]
I just checked my playlist and it has the names swapped.  Not sure how that could happen.

Sony - PlayStation.lpl
/storage/roms/nas/psx/Legend of Legaia (USA) (Demo)/Legend of Legaia (USA) (Demo).cue
Legend of Legaia (USA)
/tmp/cores/pcsx_rearmed_libretro.so
PlayStation (PCSX ReARMed)
00000000|crc
Sony - PlayStation.lpl
/storage/roms/nas/psx/Legend of Legaia (USA)/Legend of Legaia (USA).cue
Legend of Legaia (USA) (Demo)
/tmp/cores/pcsx_rearmed_libretro.so
PlayStation (PCSX ReARMed)
00000000|crc

**Comment by OGWillikers** [comment]
Just scanned the demo directory after renaming my playlist to something else.  Same result as the above pictures.  Also noticed something else interesting.  The history shows I loaded the demo.

![img_20161117_122017](https://cloud.githubusercontent.com/assets/19647360/20401963/73def918-acc0-11e6-9c41-dcf18fb0c214.jpg)
![img_20161117_122039](https://cloud.githubusercontent.com/assets/19647360/20401971/79ea628e-acc0-11e6-9583-5904657cb035.jpg)

**Comment by retro-wertz** [comment]
mine seems fine. update your database maybe? 
![legend of legaia scus_94254 -161118-022046](https://cloud.githubusercontent.com/assets/23315382/20402203/b96d6fa2-ad36-11e6-8eef-4ccf869fffc5.png)
![legaia](https://cloud.githubusercontent.com/assets/23315382/20402287/0d2ed4e6-ad37-11e6-9c2b-e85c148ffcb4.jpg)

**Comment by OGWillikers** [comment]
Hmm.  Alright, I'm gonna go compare Lakka and RetroArch databases now from fresh downloads.  My pictures are from Lakka, but I assumed game databases would have absolutely no chance of being different.

**Comment by OGWillikers** [comment]
Alright, fresh packaged install of 1.3.6 shows this issue on my laptop.  After updating databases, it goes away.  There's no convenient menu option to do this on Lakka, so I've been barking up the wrong tree.

Apologies, and cheers.

**Comment by lasers** [comment]
Good to know. Also fixed on Aug 24. 😉 https://github.com/libretro/libretro-database/commit/375ca24f902ce3ee7fcc892d67bbcb7c6ef622aa
