### ISSUE TITLE
[CTR] Freeze when pressing X in menu.

### ISSUE THREAD

**Issue by mtjohnson47** [libretro/RetroArch#4009]
When X is pressed in the menu while a game is running (and probably while not running, though I didn't test), RA freezes.  Only recoverable by force power off the 3DS.

By X, I mean the button in the same spot as Y on a XBox controller or △ on the Playstation controller.  On top of the diamond buttons.

I'm using the Nov 13th nightly on a New 3DS.

**Comment by orbea** [comment]
@mtjohnson47 Is this still an issue with the current nightlies?

**Comment by mtjohnson47** [comment]
I don't know
