### ISSUE TITLE
Issue with joypad drivers (all but hid tested)

### ISSUE THREAD

**Issue by Sudospective** [libretro/RetroArch#4016]
Every joypad driver on Windows 10 hangs RA on startup, ROM load, and ROM unload. This may just be a problem with me, in which case, will not matter, as I use RA on Windows 10 to Netplay with my Lakka machine to record without a capture card. Currently, all drivers hang the application. However, "hid" may not, as I haven't tested it out yet. My solution for now was to set the input and joypad drivers to "null".

**Comment by fr500** [comment]
I don't have any lock ups with dinput

**Comment by orbea** [comment]
Given the lack of info or recent activity I am going to close this issue, please complain if its still a problem for you.
