### ISSUE TITLE
Integer scale not fully respected when using some cores

### ISSUE THREAD

**Issue by bidinou** [libretro/RetroArch#4018]
Hi ! 

Enabling integer scale is frequently advised when adding scanlines to the picture (crt-pi pixel shader for instance), otherwise unpleasant artifacts are visible on the picture (irregular horizontal lines).

However, when using some cores, even though integer scale is enabled and seems to be taken into account (the picture size on the screen seems to correspond : not full screen), such artifacts are still visible.

Example : regarding Genesis emulation, irregular horizontal lines are visible when using the Picodrive core (but not when using the Genesis Plus GX core). The issue is not present with the FBA or SNES9x cores but does occur with the Mednafen PCEngine core.

I tested using : Lakka : both latest stable and nightly version. Hardware : x86_64 PC with Intel HD Graphics, crt-pi shader. My personal combination is xbr level 2 scaled twice + crt-pi. (it's not visible with crt-lottes although it's visible with other shaders)

**Comment by Antiriad** [comment]
Hi, 
in Picodrive on Lakka (RPi, composite, 240p with the new firmware) I get horizontal lines on vertical scrolling sprites (text, characters etc.).
This does not happen with other cores, so I suppose it is related to this issue. In 240p these lines are extremely visible when there is vertical scrolling (e.g. first stage of Bare Knuckle II, when the level section goes down).
I really hope for a fix! Thanks

**Comment by Antiriad** [comment]
Here there are a couple of videos from Bare Knuckle III on Picodrive (Raspberry Pi 1, composite out, 240p).

VIDEO 1
Look at the text that rolls vertically, it is "cut off" by these horizontal lines that seem always in the same position:
https://1drv.ms/v/s!AgxFrlHsc5x409hjO8kbvGjjCdKmfw

VIDEO 2
Please look at the mouth of Axel (main character of the game):
https://1drv.ms/v/s!AgxFrlHsc5x409hiAfhH7kSQLhVBBQ

VIDEO 3
Now please take a look at his eye:
https://1drv.ms/v/s!AgxFrlHsc5x409hhBvVUn3r8oFmdkA

This only occurs in Picodrive core, not in other cores like FCEUMM.
Maybe someone could confirm whether it has the same issue?

Thank you very much!

**Comment by retro-wertz** [comment]
must a an "rpi" or generally a composite thing. does not seem to be the case for windows and linux versions. and btw, this game(BKIII) is running 320x224 unlike most cart that is 320x240, not that i am saying its relevant...

**Comment by danieljg** [comment]
I can confirm this issue also occurs both the 3ds and psp releases using Mednafen PCEngine Fast. It's not a rasberry pi or composite video issue (there's artifacts from that in the videos Antiriad posted, but that's not what he's reporting).

To reproduce, one could do the following:

1. Install retroarch mednafen pcengine fast in a 3ds/psp
2. Load up a game, I don't know if all games show the issue, but Taito's Chase HQ and Bonk's Adventures are confirmed to show the issue by myself
3. Turn integer scaling on and bilinear filter off

The result from that is that the image will not be 1:1, but will show some doubled/skipped pixel rows and/or columns that show up as 'lines'. This could have to do with incorrectly reported/interpreted overscan.

**Comment by fr500** [comment]
> Example : regarding Genesis emulation, irregular horizontal lines are visible when using the Picodrive core (but not when using the Genesis Plus GX core). The issue is not present with the FBA or SNES9x cores but does occur with the Mednafen PCEngine core.

The core is not reporting the correct resolution then,

**Comment by hizzlekizzle** [comment]
This is a core issue and should be reported at the respective core repos. closing.
