### ISSUE TITLE
Bugception: Looping through Directories

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#4019]
- [ ] Possible bug
* Go to `Database Manager`, `Cursor Manager`, `Load Configuration`, `Load Content --> Select File`, `Load Configuration`, or anything that requires you to select file / directory.

  Keep going with the `Parent Directory` or `/` and see how deep you are willing to go... and how far it will take to return you back to the reality level. Don't go too deep or you'll be in stuck in the limbo like Leo DiCaprio did. Thanks.

**Comment by sergiobenrocha2** [comment]
Related to #2604, it does not make sense to have Parent Directory inside a zip
