### ISSUE TITLE
Nonsensical PAR/DAR description

### ISSUE THREAD

**Issue by arromdee** [libretro/RetroArch#4027]
Start without a core.  Go into video, Aspect Ratio Index.  One of the options is "1:1 PAR (4:3 DAR)".  Since no core is loaded, there is no way for Retroarch to know that 1:1 PAR corresponds to 4:3 DAR and, in fact, this correspondence is not true for some cores.

It also does the same thing with a core, without checking to see if the core is one for which 1:1 PAR is 4:3 DAR (for instance, it is not true for Nestopia.)

**Comment by aliaspider** [comment]
retroarch starts with a dummy core that has a 320x240 frame, so I really fail to see what is nonsensical about it mapping 1:1 PAR to 4:3 DAR.
also I just started nestopia and it correctly mapped 1:1 PAR to 8:7 DAR.
what is the issue here exactly ?

**Comment by arromdee** [comment]
"retroarch starts with a dummy core that has a 320x240 frame,"

If there is no core, it should not show a DAR at all, or it should say something like "1:1 PAR: Unknown DAR".

"I just started nestopia and it correctly mapped 1:1 PAR to 8:7 DAR."

I am using the Linux version from a day or so ago.  I loaded Nestopia core and went back to the setting.  It still said 1:1 PAR is 4:3 DAR.  Integer scale and crop overscan (with a restart) made no difference.  Also, I tried the Vita version, starting up the Nestopia core bubble.  It still said 1:1 PAR is 4:3 DAR.

Both of them are version "1.3.6 - Nestopia 1.48-WIP 70f4405".

**Comment by hizzlekizzle** [comment]
Nestopia correctly reports the 1:1 PAR here for me in Windows.

I understand the confusion caused by the dummy core but this isn't really something we can fix easily and it's a pretty non-damaging issue.

**Comment by aliaspider** [comment]
ok let me make this clearer for you : 
when you have no content running (even is you have a core loaded but no content selected), the content frame dimensions are set to 320x240, which is where the 4:3 DAR comes from.
load a content in nestopia and it will correctly change to 8:7.
the DAR can only be known after loading a content.

**Comment by arromdee** [comment]
I would argue that if you have no content running, but the core only supports one aspect ratio, it should still show that.  But even if it doesn't, that just means it should show something like "1:1 PAR (unknown DAR)" or "1:1 PAR (DAR depends on content)", not falsely claim the DAR is known.

**Comment by hizzlekizzle** [comment]
When you load a core, RetroArch just "peeks" into it and doesn't actually initialize it until content is loaded. That is, when you load a core but no content, the dummy core is still in use, so it's the dummy core's DAR that is being reported unless/until some content is loaded and the other core is actually initialized.

Again, I understand your perspective and see how it can be confusing, but it's not something that's easily changed/fixed, so you'll just have to keep in mind: core-reported DAR isn't accurate until content is loaded.
