### ISSUE TITLE
How modify xbm theme?

### ISSUE THREAD

**Issue by Celes-Eternal** [libretro/RetroArch#4031]
Hello,

I'd like to know how I can change the xbm theme of retroarch.
I know that I can change the assets and the overlays when I run games.
But don't know how change the interface. Right now I just wanted to change the thumbnails size, because it's really too small (maybe because of sway). But the menu seems reduce the size.

If it's mean change the code, I think that will wait :)
Thanks
Have a great day

**Comment by lasers** [comment]
I might be a little off... To make everything a bit smaller...

Settings --> User Interface --> Menu --> Menu Scale Factor 70

**Comment by Kivutar** [comment]
For now changing the size and the placement of the thumbnails means changing the code

**Comment by Celes-Eternal** [comment]
Okay thanks for the answer :)
I'll go back on my work for now, but I'll keep an eye on RetroArch.
Thanks

Ps: I'm already at scale 100

**Comment by lasers** [comment]
Launching it on an empty workspace does not work?

You could try `xmb_scale_factor="200"` in your retroarch.cfg

**Comment by Celes-Eternal** [comment]
200 is too much, but this trick is not bad!
Thanks :)
