### ISSUE TITLE
Can't add .m3u in playlist ?

### ISSUE THREAD

**Issue by Celes-Eternal** [libretro/RetroArch#4048]
Hello,
I'm not able to add a .m3u with beetle_psx_libretro. I can launch it (even from the menu). 
But I can't see it in my psx playlist.
Is it possible right now or I'll have to use every disk?

**Comment by sergiobenrocha2** [comment]
There was already an issue about this #2292

**Comment by sergiobenrocha2** [comment]
Open your playlist and add it manually

**Comment by Celes-Eternal** [comment]
I researched .m3u and find nothing, thanks
