### ISSUE TITLE
Android Font and Menu shader issues

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4058]
Edit: actually seems it's not exclusive to the Shield ATV, I just tried on my phone (Xperia Z5) and the font alignment issue is present there too (but not the thin white lines). The ribbon looks correct though and snow works too.

1. Sublabels and fonts in general are presenting some artifacts (zoom in to understand)

Xperia Z5
![screenshot_20161123-112328](https://cloud.githubusercontent.com/assets/1721040/20569888/9f96c62c-b16f-11e6-9bae-a2f811f0e844.png)

Shield ATV
![retroarch_20161122_181527](https://cloud.githubusercontent.com/assets/1721040/20569006/899f9f9a-b16c-11e6-9092-968ded83c411.png)

Shield Portable
![screenshot_2016-11-23-10-54-37](https://cloud.githubusercontent.com/assets/1721040/20569014/92aaeaae-b16c-11e6-8411-e08fdbe13d61.png)

Shield Tablet
![screenshot_20161123-110308](https://cloud.githubusercontent.com/assets/1721040/20569147/0d5b0248-b16d-11e6-8a4e-3ac8d5ec73f3.png)

2. Ribbon goes crazy after a while on the Shield ATV, also looks quite different from the ribbon in the portable

Shield Portable
https://youtu.be/1DUh6abELQo

Shield ATV when just starting
https://youtu.be/pB-mq2f2zSU

Shield ATV after a while
https://www.youtube.com/watch?v=OZWBWNhA4Wo

3. Snow doesn't work at all on the shield ATV

**Comment by sergiobenrocha2** [comment]
I can confirm that.

Btw, I'll need a magnifier to see what's write in the sub label on my phone.

**Comment by fr500** [comment]
I managed to reproduce the font issue on PC, it's an issue with the font driver, so it's not android only. 
You can reproduce it on PC if you build with --disable-freetype

I think @heuripedes hooked up STB? maybe he would know?
