### ISSUE TITLE
Retroarch Android - Retroachievement is broken

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/RetroArch#4075]
Since version 2016-11-17/2016-11-20 retroachievement in retroarch is broken.
I tried all the nightly versions since 2016-11-21 and the list of achievments isn't showed and the games aren't saved in my gamelist on retroachievement's site.
Reverting to a older version, like 2016-11-17, and the SNES achievements are working. The achievements to Mega Drive are showed, the retroachievement site doesn't save the games in my gamelist.

**Comment by meleu** [comment]
I've updated my RetroArch on Android just now (2016-11-27), tested with SNES (Arkanoid: Doh it Again) and Mega Drive (Shadow Dancer). And everything seems to be working really fine.

The problem you described seems to be a network problem, and I noticed that (unfortunately) it's a commom problem with RetroAchievements.org (specially on weekends).

**Comment by ZacharyFoxx** [comment]
Hi,
I hadn't tried the version 2016-11-27. I just update and everything is all right, using the cores Snes9x2010 and Picodirve.
But there was a problem with retroachievement, between versions 2016-11-21 and 2016-11-26, because using the 2016-11-17 release the retroachievements worked flawless.
I'm going to open a issue report to core GensPlus-GX, because the retroachievements isn't been working with it.

**Comment by meleu** [comment]
If there's no problem currently, I think you can close this issue. ;-)
