### ISSUE TITLE
SIGSEGV in udev_input_state: null pointer dereference for udev->joypad

### ISSUE THREAD

**Issue by T-X** [libretro/RetroArch#4078]
I just built a recent RetroArch (b1531618f17e) and snes9x-2010 (74953d8d417) on an Odroid-W (basically the same ARMv6-based, single core, Broadcom chip as on a Raspberry Pi 1 or Pi Zero). This device currently runs a Debian Jessie based Raspbian. Unfortunately, when selecting an .sfc file things crash when udev_input_state() tries to dereference udev for udev->joypad because udev is still pointing to 0x0:

<pre>
$ gdb ./retroarch                                                                                                                            <\u2500(So,Nov27)\u2500\u2518
GNU gdb (Raspbian 7.7.1+dfsg-5+rpi1) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./retroarch...done.
(gdb) run
Starting program: /home/pi/dev/RetroArch/retroarch 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb604b3f0 (LWP 31166)]
[New Thread 0xb58253f0 (LWP 31167)]
[New Thread 0xb4eff3f0 (LWP 31168)]
[New Thread 0xb46ff3f0 (LWP 31169)]
[New Thread 0xb3eff3f0 (LWP 31170)]
[New Thread 0xaf3d63f0 (LWP 31195)]
[New Thread 0xae9ff3f0 (LWP 31212)]
Failed to open /home/pi/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
Failed to open /home/pi/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
^[[B^[[B^[[A^[[B^[[B^[[B^[[B^[[A^[[A^[[A^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[A^[[6~^[[6~^[[6~^[[6~^[[6~^[[6~^[[6~^[[B^[[B^[[B^[[B^[[B^[[B^[[A[Thread 0xae9ff3f0 (LWP 31212) exited]
[Thread 0xaf3d63f0 (LWP 31195) exited]
[Thread 0xb604b3f0 (LWP 31166) exited]
[New Thread 0xb604b3f0 (LWP 31356)]

Program received signal SIGSEGV, Segmentation fault.
0x000dabd0 in udev_input_state (data=0x0, binds=0xbefff300, port=0, device=1, idx=0, id=24) at input/drivers/udev_input.c:524
524	               input_joypad_pressed(udev->joypad, port, binds[port], id);
(gdb) bt
#0  0x000dabd0 in udev_input_state (data=0x0, binds=0xbefff300, port=0, device=1, idx=0, id=24) at input/drivers/udev_input.c:524
#1  0x00049684 in input_poll () at input/input_driver.c:406
#2  0x00022a58 in core_poll () at core_impl.c:336
#3  0x00038f20 in runloop_iterate (sleep_ms=0x1, sleep_ms@entry=0xbefff3d4) at runloop.c:1188
#4  0x00021d40 in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:127
#5  0xb66ec294 in __libc_start_main (main=0xbefff564, argc=-1233055744, argv=0xb66ec294 <__libc_start_main+276>, init=<optimized out>, 
    fini=0x115870 <__libc_csu_fini>, rtld_fini=0xb6fdf408 <_dl_fini>, stack_end=0xbefff564) at libc-start.c:287
#6  0x0001f618 in _start ()
(gdb) l udev_input.c:524
519	   switch (device)
520	   {
521	      case RETRO_DEVICE_JOYPAD:
522	         if (binds[port] && binds[port][id].valid)
523	            return udev_input_is_pressed(binds[port], id) ||
524	               input_joypad_pressed(udev->joypad, port, binds[port], id);
525	         break;
526	      case RETRO_DEVICE_ANALOG:
527	         ret = udev_analog_pressed(binds[port], idx, id);
528	         if (!ret && binds[port])
(gdb) print udev
$1 = (udev_input_t *) 0x0
(gdb) print *udev
Cannot access memory at address 0x0
(gdb)
</pre>

Let me know if you need any additional information. (just read about the genius idea and concept behind libretro and I'm kind of desperate to try it :D - keep up the good work, guys :-)! )

**Comment by fr500** [comment]
Still happening? reopen if so

**Comment by T-X** [comment]
Yaiy, thanks, works great now! :-) (tried 0b1a265675b031)
