### ISSUE TITLE
Suggestion: Option for bypass hash database for 'Add Content' in playlists

### ISSUE THREAD

**Issue by bryc** [libretro/RetroArch#4079]
Using **Add Content** I tried to import a fan translation of Seiken Densetsu 3 to the SNES playlist, but it didn't work. It also doesn't make it very clear that it didn't work (unless a message in the OSD flashes faster than I can read), and I have to check the playlist itself.

I suppose it is because the game database only contains clean, unpatched and headerless files. Further testing revealed that I had many SNES games with copier headers that were also being ignored. Interestingly enough, PSX games _don't have this issue_, and probably for good reason, since cue and bin files can vary wildly.

To force the translation in the playlist, I was able to modify the .lpl file and add this entry:

> R:\SNES\Seiken Densetsu 3.smc
> Seiken Densetsu 3
> C:\$\RetroArch\cores\snes9x_libretro.dll
> SNES / Super Famicom (Snes9x)
> 
> Nintendo - Super Nintendo Entertainment System.lpl

It worked fine, but I had to figure out what the format was.

I suggest an additional setting under **Playlists** that allows you to skip checking the database, and only go by extension, which is how games are filtered and run normally with 'Load Content' anyway. It could even make scanning a folder faster. Of course this would remove the benefit of having the ROM detected with additional info displayed, but I don't know a better way.

Also an option to add a game to a playlist from the Quick Menu would be great (or Current Game option in Add Content menu) - some users would rather only add games they want to play to a playlist, since the option of using the file browser is always there. Faster access to only the games you want to play, etc. Also a way to delete games you no longer want in a playlist would be nice.

Cheers
bryc

**Comment by hizzlekizzle** [comment]
This is now implemented with the 'manual scan' option. closing.

**Comment by mikepurvis** [comment]
@hizzlekizzle "Manual Scan" is 90% of the way there, but it would be nice if there was a way to associate your manually-scanned entries with the corresponding database item so that the proper title and artwork comes through.
