### ISSUE TITLE
Suggestion use these icons for core packages

### ISSUE THREAD

**Issue by cucholix** [libretro/RetroArch#4081]
http://gbatemp.net/threads/retroarch-wiiu-wip.447670/page-87#post-6881415

I will update that post at the time new cores are released. It's for the Wii U version of Retroarch
=)

Regards
-Cucholix

**Comment by aliaspider** [comment]
you can make a PR for that here : https://github.com/libretro/retroarch-assets/tree/master/pkg/wiiu.

make sure you use the correct file names, you can get the correct filenames by looking here for example : https://github.com/libretro/libretro-super/tree/master/dist/info and just replacing _libretro.info with .png
.
also, don't overwrite old files, just rename them (eg: rename the old 2048.png to 2048_1.png, etc)

**Comment by cucholix** [comment]
I get this message when trying to upload files to retroarch-assets/pkg/wiiu 

Uploads are disabled.
File uploads require push access to this repository.

**Comment by lasers** [comment]
Use "Fork" button on top-right in `retroArch-assets`. Make changes / Upload in your fork. Compare/make a pull request against `retroArch-assets`.

**Comment by cucholix** [comment]
I think I replaced the old ones :/
Can you check? It's my first time using github, totally noob about it, my bad...

**Comment by lasers** [comment]
I'm not that good with git myself. I gauge you did it wrong as I don't see any renaming... so you possibly did replace your old ones. :-) 

Also, you can swap everything and make one commit instead of doing one commit per file as it will be easier to parse through changes this way.

There might be some potential brand/copyright issues using logos like this whole set. I'll ask @Kivutar about that just in case.

**Comment by aliaspider** [comment]
yeah you replaced the old ones, easiest to just delete the old fork and do it again.
fork ```https://github.com/libretro/retroarch-assets``` to ```https://github.com/cucholix/retroarch-assets```
then
```git clone https://github.com/cucholix/retroarch-assets```
```cd retroarch-assets```
do this for all the files you want to replace : 
```git mv filename.png filename_1.png```
copy your new files to retroarch-assets\ then do this for each :
```git add filename.png```
finally
```git commit```
```git push```
navigate to ```https://github.com/cucholix/retroarch-assets``` which is now updated with your changes and click on ```New pull request``` .

**Comment by RobLoach** [comment]
@cucholix The [GitHub Desktop Client](https://desktop.github.com/) is another good option if you're just starting out in git too.
