### ISSUE TITLE
Onscreen Keyboard Improvements

### ISSUE THREAD

**Issue by diegoviola** [libretro/RetroArch#4082]
The Onscreen Keyboard is great for jumping between directories, e.g. type `/search [Enter]` allows for navigating between directories faster.

I think it would be a good idea to add default shortcuts like n (Repeat previous search) and N (Repeat previous search, but in the reverse direction.)

Maybe also add the ability to define custom shortcuts? Is any of this already possible?

Another idea: highlight the keys on the visual keyboard as the user types.

Thanks.

**Comment by fr500** [comment]
Actually I think we should "filter on search" that would achieve the former.
And if the user uses a real keyboard maybe don't show the OSK

**Comment by diegoviola** [comment]
@fr500 Yes, well. I'm using a physical keyboard so hiding the OSK is fine I guess, I'd like to have a way to jump between search matches quickly, back and forth. So I don't have to use the arrow keys much.

**Comment by diegoviola** [comment]
@fr500 I like that idea.

**Comment by lasers** [comment]
Duplicate improvements https://github.com/libretro/RetroArch/issues/4008

It might be not possible to hide the OSK now because of this comment "input_osk_overlay_enable is removed now." https://github.com/libretro/RetroArch/issues/3982
