### ISSUE TITLE
Cannot use arrow keys with mupen64plus core

### ISSUE THREAD

**Issue by diegoviola** [libretro/RetroArch#4083]
So I tried Wave Race 64 and Super Mario 64 and I cannot play it, because I don't have a gamepad and it turns out I cannot assign the controls to my arrow keys.

**Comment by diegoviola** [comment]
RetroArch git d6ebd2a
Arch Linux (x86-64)
Intel HD Graphics 5500

**Comment by diegoviola** [comment]
RetroArch git d6ebd2a
Arch Linux (x86_64)
Intel HD Graphics 5500

**Comment by bparker06** [comment]
What do you mean by 'cannot assign'? I just tried Mario64 on mupen and the controls work fine if I bind the analog axes to the keyboard keys. Those games do not support the regular d-pad if that was what you were trying.

**Comment by diegoviola** [comment]
@bparker06 How do you bind the analog axes to the keyboard keys? Is there a way to do this from RA itself?

> Those games do not support the regular d-pad if that was what you were trying.

That explains why I was confused here.

**Comment by diegoviola** [comment]
By 'cannot assign' I mean, I cannot get my arrow keys to work, and I was trying to bind movement controls to the arrow keys, but I cannot figure out how.

**Comment by bparker06** [comment]
Input -> Input User 1 Binds -> User 1 Left Analog X/Y

**Comment by orbea** [comment]
This works here, it didn't in the past. :)

**Comment by diegoviola** [comment]
@bparker06 Yes, that works. Thanks.
