### ISSUE TITLE
[Feature request] Please default to PulseAudio on systems that use it

### ISSUE THREAD

**Issue by diegoviola** [libretro/RetroArch#4085]
RetroArch in its current state will default to ALSA as the audio driver, even though my build has support for pulseaudio, I always have to change this in every new config which can get a bit tedious.

I think it would be nice from a usability perspective to default the config to pulse if the build has support for it, otherwise default to ALSA as it is right now.

Basically, if pulse is found in ./configure set audio_driver = "pulse", else set audio_driver = "alsa".

Thanks.

**Comment by loganmc10** [comment]
I'll +1 this for the simple fact that on my old Intel laptop I get audio crackling with mupen64plus-libretro or GLupeN64 with the ALSA driver, but no crackling with pulseaudio or alsathread.

**Comment by diegoviola** [comment]
https://github.com/libretro/RetroArch/commit/a1a70c63efd8a668bd3947293fa5e215a139cc78

**Comment by diegoviola** [comment]
Thanks @twinaphex :+1:
