### ISSUE TITLE
A way to manually install cores on Android

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#4086]

**Comment by hizzlekizzle** [comment]
If we could figure out why the core directory seems to be hardcoded in Android, this wouldn't be an issue, but barring that, I agree that being able to copy it from user-writeable storage is a good workaround.

**Comment by loganmc10** [comment]
@hizzlekizzle What do you mean? The core directory must be in Internal Storage (https://developer.android.com/guide/topics/data/data-storage.html)

> By default, files saved to the internal storage are private to your application and other applications cannot access them (nor can the user)

Android specifies that shared libraries (like libretro cores) can only be in Internal Storage, I assume to preserve the integrity of the app, whatever the reason, that is how Android works.

With a rooted phone you could write the core to wherever you want, but with a normal phone, RetroArch needs some method where the app itself copies the core from external storage to internal storage.

**Comment by fr500** [comment]
Oh ok so the restriction is still in place
Thanks for clearing that up

I agree we need a mechanism to sideload and maybe backup core, I'll try to figure it out by the weekend.

**Comment by Aaahh** [comment]
@loganmc10 I'm pretty positive that it's writable to anyone, but all my devices are userdebug so I can't test

**Comment by loganmc10** [comment]
I'm 100% positive that you need root access to write (or read) to that location

**Comment by Aaahh** [comment]
Lol ok then 
You can try change the path for the cores to external as it now has permission to read and write from that

**Comment by loganmc10** [comment]
Android doesn't allow shared libraries (like cores) to be executed from external storage

**Comment by fr500** [comment]
it doesn't need to be something too elaborated... just a way to have a zip in Downloads or whatever, say sideload.zip or cores.zip and an option to use that as a source for sideloading

**Comment by thailemon** [comment]
let my clarify that @Aaahh 

you cant adb push to /data/data/ on any Android device unless it's rooted.
