### ISSUE TITLE
XMB displaced list

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#4087]
Sometimes you get a displaced list in XMB, it's displaced to the right

![screenshot - 28112016 - 18 26 25](https://cloud.githubusercontent.com/assets/5431285/20687318/2ceff4d0-b5a3-11e6-9c48-cada58566c47.png)

![screenshot - 28112016 - 18 26 56](https://cloud.githubusercontent.com/assets/5431285/20687325/327667ea-b5a3-11e6-9e6f-a85710fbaceb.png)

@Kivutar is it a know issue? I can't find an opened issue about it.

**Comment by Kivutar** [comment]
This can happen when you go in the updater without a network connection, for example.
