### ISSUE TITLE
"Remove" option in the playlist should be related to "Show Advance Settings"

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#4088]
"Remove" option in the playlist should be related to "Show Advance Settings", i.e. when this setting OFF, there should be no remove option in the playlist. Think about kiosks and kids removing stuff

**Comment by retro-wertz** [comment]
was going to suggest this too-although probably remove that "Remove" option from playlist to something like a a separate management related feature. probably replace with "run with other core" or related.

**Comment by fr500** [comment]
there is a request for kiosk mode already.
@sergiobenrocha2's suggestion makes sense for kiosk mode indeed.

**Comment by sergiobenrocha2** [comment]
Well, it's not under "show advance settings", but ebded84 fixed it.
