### ISSUE TITLE
(Bug) Block all cores citing missing firmware as a reason

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#4091]
The likely commits (https://github.com/libretro/RetroArch/commit/9505602675172c7126687d8e695a984697d13844 - https://github.com/libretro/RetroArch/commit/8f4d6b8784853dbc88483bfdbd490ff77d0b4187) will block all cores from loading when it goes in effect.

**Comment by fr500** [comment]
Nope se long as you have the required firmware it works

**Comment by lasers** [comment]
What do I need for 2048?

**Comment by fr500** [comment]
Nothing. Not even content

**Comment by lasers** [comment]
Yeah. It is blocking all cores for me. Just a heads up.

**Comment by fr500** [comment]
It's not blocking anything here
It's impossible for it to block 2048 since that one doesn't gone thru load content

**Comment by fr500** [comment]
It's not a bug it's a feature.
Ok I see a possible problem.
Again you should include STEPS TO REPRODUCE instead of sending me in a guessing trip.

From now on issues without steps are gonna be ignored or closed.

**Comment by fr500** [comment]
869800dc0431b6214f74e4cabc4d3756147f4586

**Comment by lasers** [comment]
New changes blocks the content citing missing firmware as a reason. Core Overrides.

**Comment by fr500** [comment]
Stop wasting my time. Either give me complete steps to reproduce or don't
say anything.

If it's an override give me the contents of such override file.

**Comment by lasers** [comment]
```
# retroarch/config/Nestopia/Nestopia.cfg (file)
system_directory = "~/.config/retroarch/bios/Nintendo - Nintendo Entertainment System"
```
```
# retroarch/bios/Nintendo - Nintendo Entertainment System (dir)
NstDatabase.xml
disksys.rom
```
It's an oneliner per config. It has been used this way since for all other 15+~ systems too without no problems since I set up RetroArch for the first time last month.

If you need more, here's the thread where I tried Awakened0's suggestion to "use core overrides to set custom system directories for cores that need BIOS or other files" -- https://github.com/libretro/RetroArch/issues/3725

After setting it up, `Load Core` (Nestopia) and `Load Content` --> (any NES content).

**Comment by fr500** [comment]
See that's hugely different than... Reason: overrides.
It's actually understandable now. Not much I can do about it since there is no way for me to guess you're gonna change the dir in an override.

I think I may scrap this feature.

**Comment by lasers** [comment]
Suggestion: Keep the notification. Don't block anything. Problem solved.
Enhancement: Try sublabel "Missing Firmware File(s)..." under loaded core for pretty.

**Comment by fr500** [comment]
It can't be done. After loading the drivers are torn down and re-initialized. The message would just not show up.
It won't prevent cores that segfault when the bios is missing.

**Comment by lasers** [comment]
I don't see any other solution. This feature likely will prevent some people accessing their bios/configs from non-standard places like NAS, nfs, potentially dual card phone storage device, etc... and would prevent overrides from actually overriding. It's too hard to tell how people will set things up. I guess no blocking and/or filters.

Last question. "The message would just not show up." You're referring to notification, but what about sublabel? I asked this because if I load a core, I am able to view `Status: Missing, Required`. Can that be done to display sublabel or something similar along with the core? And to give users an option to turn them off like one would with `Display Core` or `Display date / time`?

**Comment by retro-wertz** [comment]
im not sure what is suppose this feature will do, but before 869800d this was how RA behaves:

test with picodrive with bios_CD_x.bin removed
-load US sega CD, FAIL(because no required bios_CD_U.bin understandably)
-exit RA. copy bios_CD_U.bin to <system>. run RA
-load US sega cd - SUCCESS..... but, exit game and run US sega cd FAILS because of missing or incomplete bios files(which is unrelated to content being played since you have the required bios already)

**Comment by fr500** [comment]
Why are you testing an old commit?

**Comment by fr500** [comment]
anyway check again, it should handle overrides and content in system directory properly
it should also work with detect code

**Comment by lasers** [comment]
New changes loads the content fine with core overrides. Tested with NES, PS1, and 3DO. :-)

`RetroArch [INFO] :: Updating firmware status for: (null) on /home/fr500/.config/retroarch/bios/Nintendo - Nintendo Entertainment System`

**Comment by fr500** [comment]
Glad to hear that.
Does it block if you don't have the firmware?

**Comment by lasers** [comment]
Yes. It blocks... but it's not working correctly at moment.
Also, 5 seconds notification still feels like a long time especially after you just got blocked expecting the game to start.

After getting blocked, fixing directories still block the archive from loading. Loading different archives will still be blocked.... I have to walk the dog now. I don't want to leave you hanging. I'll be back soon to analyze this weird behavior.

**Comment by fr500** [comment]
I tried this:
Removed my PSX bios. Tried to load, blocked.
Alt-tabbed without moving from the menu, copied the BIOS again, tried again, it worked

Tried this too:
Removed PSX bios, Tried to load, blocked.
Loaded SNES game, worked

The only problem I have is that it doesn't seem to reset the libretro_path after being blocked.. so say I load something that works, then I try to load something that doesn't. Close content will get blocked. 
I'll have to fix that

**Comment by lasers** [comment]
This line got merged somewhere in the process.

`RetroArch [INFO] :: One or more firmware files are missingRetroArch [INFO] :: Updating firmware status for: $HOME/.config/retroarch/cores/nestopia_libretro.so on $HOME/.config/retroarch/bios`

Everything looks to be in place and it's still blocking contents. I thought I might rename it back wrong, but that wasn't it. Maybe your fix will undo this odd behavior. Restarts does not fix it. I think it stopped loading overrides now.

**Comment by fr500** [comment]
I need steps to reproduce

**Comment by lasers** [comment]
Everything looks to be in place. Start. Load Nestopia. Load Content. Blocked.

**Comment by lasers** [comment]
Confirmed with Genesis too. Something I hadn't touched.

**Comment by fr500** [comment]
Ok then it doesn't work for overrides.

**Comment by retro-wertz** [comment]
-cannot close game because one or more files is missing....
![firmware check](https://cloud.githubusercontent.com/assets/23315382/20740442/fc680fc6-b6fd-11e6-9923-bede0001e33f.jpg)

-no onscreen bios missing message when loading a content that actually needs one

**Comment by lasers** [comment]
It worked... Then things went wrong after I renamed bios directory.

**Comment by fr500** [comment]
It most likely didn't or you loaded in a different manner. I just traced the codepath and it will never work.

**Comment by fr500** [comment]
@retro-wertz STEEEEEEEEEEEEEEEEEPS

**Comment by lasers** [comment]
@fr500 Good thing I commented https://github.com/libretro/RetroArch/issues/4091#issuecomment-263776338.

Now, it's always stuck on `$HOME/.config/retroarch/bios`. Like I said, weird behavior.

**Comment by fr500** [comment]
Most likely you loaded from a playlist too.

**Comment by retro-wertz** [comment]
-loaded from playlist or history
-using load content will show immediately "one or more files are missing" when loading a core that requires firmware

**Comment by fr500** [comment]
Yes that's what supposed to happen

**Comment by retro-wertz** [comment]
but im loading a genesis game, that does not need bios

**Comment by fr500** [comment]
It's for the core not for the subsystems. RA doesn't know about what is being emulated. It only knows that the bios X for the core Y is defined as required

**Comment by lasers** [comment]
https://wiki.libretro.com/index.php?title=PicoDrive

Your comment `Close content will get blocked.` Okay I see it now when I loaded it from a Playlist. I'm 99% sure I didn't mess with Playlist because I know you made it for "Load Core --> Load Content" workflow.

**Comment by fr500** [comment]
I'm 99% sure you did.

**Comment by retro-wertz** [comment]
ok.. thats a different approach... making it compulsory to have complete bios/firmware files?

**Comment by fr500** [comment]
No I already added a toggle and in the future it may show a dialog instead asking if you want to load anyway

**Comment by fr500** [comment]
I merged myself since the PR wasn't any more dangerous than the current state of things.
You should be able to close content now.
