### ISSUE TITLE
Crash n' Burn (3DO) - Game Intro Loops

### ISSUE THREAD

**Issue by Mortico** [libretro/RetroArch#4093]
When the game starts up, it plays a preview for another game.  If you try to skip, it just restarts.  If you wait until it finishes, it restarts.

**Comment by lasers** [comment]
Confirmed.
Known issue -- https://github.com/libretro/4do-libretro/issues/18
Update required -- https://wiki.libretro.com/index.php?title=3DO_Core_Compatibility

**Comment by fr500** [comment]
Wrong issue tracker
https://github.com/libretro/4do-libretro
