### ISSUE TITLE
Image stuttering w/o bilinear filtering

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/RetroArch#4112]
In some situations like scrolling while moving on stairs in Castlevania image appears stuttery if bilinear filtering is disabled. I've had this issue for months in some other games including Castlevania Chronicles and possibly Mega Man 1&2.

RetroArch v1.3.6 3f0a418
OS: Arch Linux

**Comment by hizzlekizzle** [comment]
If you mean the "wavy" look of pixels, it's a result of rounding behavior with nearest neighbor at non-integer scales. Does it go away if you set your aspect ratio index to 1:1 PAR?

**Comment by GeneralFailer** [comment]
Integer scaling is enabled though. For me it looks like a ton of small artifacts.
Yeah, that works.

**Comment by GeneralFailer** [comment]
The index's option description is missing from the skeleton config for some reason.

**Comment by GeneralFailer** [comment]
With this index the 480p picture seems to end up being too small for my CRT monitor to be able to stretch it horizontally to full screen.

**Comment by GeneralFailer** [comment]
Oops.

**Comment by hizzlekizzle** [comment]
Right, when integer scaling is enabled, it only applies to the Y-axis and the X-axis is determined by the aspect ratio setting. The X-axis stretching to create a 4:3 image out of 8:7 (for NES and SNES) is what causes the problem.

If you're running on a CRT, the best way to deal with it is to make a custom modeline that's "ultrawide," such as 1920x480 or preferably 3840x480 if you GPU will cooperate. Your CRT will accept this weird resolution just fine. Then, set your aspect ratio to 'custom' and set a custom viewport that takes up the entire horizontal area. Almost everything is integer-divisible into 1920 or 3840 and if something isn't, the fractional rounding is small enough to be invisible on a CRT.

**Comment by GeneralFailer** [comment]
I'm using KMS and I don't think this is possible there, as I've reported in #3195. Is there any workaround for this case?

**Comment by hizzlekizzle** [comment]
You would have to create a custom EDID that reports the resolution that you want:
http://filthypants.blogspot.com/2014/11/creating-custom-edid-for-arcade-monitor.html
You could also try using something like the pixellate shader or tvout-tweaks to interpolate along the X-axis while staying sharp on the Y-axis.

**Comment by GeneralFailer** [comment]
OK then, thanks for the help.
