### ISSUE TITLE
Stuff broken after unicode changes

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4127]
Surprisingly it's not the autoconf commits but something from the unicode commits by @bparker06 .

Last good commit is 53549646af2d86a4b19124cdb137ad5a71790654

The first bad commit could be any of:
8adafa924941af46ab0e60cd4c52259351e0bade
187e1fc71bd65ae95d5761e52a661e2f3aa8e45c
495deae31b7aeef3de6540c120c1b52a417a654e
cd9d09d1f306e4f2ec1da2db71fc00202eefd954
dc99713a9b9961b61dbfa70b9353ba7f88bc2c60
367dea6723b344cb897b6af00af78c07133d7b25

All of those don't even start, you can check them with:
https://github.com/libretro/RetroArch/commit/

**Problem:** 

Non-native xinput pads no longer map automatically. It doesn't even try.

Both xinput and dinput pads work fine under the "xinput" joypad driver. The only thing that varies is actual button bindings.

When I connect my XBOX360 pad it uses the autoconf file.
When I connect my DS3 (with xinput emulator) it uses the autoconf file
When I connect my DS4 with official sony drivers (recognized as "Wireless Gamepad") it does nothing
When I connect my Nes30 Pro does nothing

**Result:**

All the gamepads should map with their xinput autoconfs! they were working fine before.

**Comment by fr500** [comment]
It seems worse now. It appears xinput isn't working at all now
As I said, all the pads should work with joypad driver xinput, the only difference is the binding order and the number of available inputs. 

This is a log for an XBOX 360 controller and a NES30 Pro with the last good commit:

```
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Device #1 PID: {9000} VID:{2002}
RetroArch [INFO] :: Autodetect: 54 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: userdata\profiles\xinput\8Bitdo_Pro_NES30_USB.cfg
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: 54 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: userdata\profiles\xinput\XInput_Controller_User_1_Custom.cfg
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Device #1 PID: {9000} VID:{2002}
RetroArch [INFO] :: Autodetect: 54 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: userdata\profiles\xinput\8Bitdo_Pro_NES30_USB.cfg
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: 54 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: userdata\profiles\xinput\XInput_Controller_User_1_Custom.cfg
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Device #1 PID: {9000} VID:{2002}
RetroArch [INFO] :: Autodetect: 54 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: userdata\profiles\xinput\8Bitdo_Pro_NES30_USB.cfg
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: 54 profiles found.
RetroArch [INFO] :: Autodetect: selected configuration: userdata\profiles\xinput\XInput_Controller_User_1_Custom.cfg
RetroArch [INFO] :: Found joypad driver: "xinput".
```
At current master 041fb3653173e375b34b3a8bd81d5a58905bb32e

```
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Found joypad driver: "dinput".
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [WARN] :: [WGL]: wglSwapInterval() failed.
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Found joypad driver: "dinput".
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Device #1 PID: {9000} VID:{2002}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: no profiles found for 8Bitdo NES30 Pro (8194/36864).
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Device #1 PID: {9000} VID:{2002}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: no profiles found for 8Bitdo NES30 Pro (8194/36864).
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {028E} VID:{045E}
RetroArch [INFO] :: Device #1 PID: {9000} VID:{2002}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Autodetect: no profiles found for 8Bitdo NES30 Pro (8194/36864).
RetroArch [INFO] :: Found joypad driver: "xinput".
```

Also this is wrong too in the log now;

> RetroArch [INFO] :: Setting fullscreen to 3840x2160 @ 60Hz on device σ▒£σ░«ΣÑäσüôΣàîπàÖ.

**Comment by fr500** [comment]
Can't load shaders 
Doesn't load remaps automatically
Doesn't load overrides automatically
Can't load configurations
Can't load overlays
Can't load cores
Can't load content

**Comment by fr500** [comment]
Nope it's not that, it can't perform any kind of directory navigation operation, I can browse to C:\ when picking a dir and the nothing else

**Comment by fr500** [comment]
Related: https://libretro.com/forums/showthread.php?t=2305&page=6&p=51790&viewfull=1#post51790

**Comment by Tatsuya79** [comment]
I can confirm the shader issue. Some don't load at all, some partially.
A same shader sometimes load OK and apply on loading, then is disabled if I hit "Apply".

I can navigate folders and launch videos, roms, even if their filenames is Japanese.

**Comment by bparker06** [comment]
All the unicode changes have been reverted for now. We can revisit it later but we should do much more thorough testing on a separate branch to make sure everything works before merging it in. Unfortunately @Tatsuya79 that also means that Japanese filenames no longer work in Windows. Perhaps a stopgap may be to just enable the file browser to work with unicode and leave the rest as is for now, so that we don't introduce any more issues in the meantime.

**Comment by Tatsuya79** [comment]
Thanks for telling me, I noticed it trying the buildbot version.
I'm still on that unicode version though as it's not causing me as many problems as fr500. (I can load core, roms, videos at least.)
