### ISSUE TITLE
"Scan this directory" includes rom in subfolder

### ISSUE THREAD

**Issue by waitingmoon** [libretro/RetroArch#4129]
Hello.

How can I exclude roms in subfolders from scanning "scan this directory"?

I'm in trouble because a huge amount of prototype rom etc. saved in a subfolders has been added to the playlist.

I'm using Nightly version, and in previous versions, I think that only rom of "this directory" was being scanned.

**Comment by hizzlekizzle** [comment]
Recursive scanning is hardcoded right now. It may be configurable in a menu at some point but that's in the future.

**Comment by RobLoach** [comment]
As HizzleKizzleNizzle mentioend, recursive scanning was added. Suggest either...

1. Closing this issue as recursive scanning is by design
2. Reframing this issue as a new feature to be able to disable recursive scanning in the config

**Comment by twinaphex** [comment]
Following RobLoach's advice, closing this.
