### ISSUE TITLE
Web Player hangs when Dropbox backend is selected but Dropbox access is denied by the user

### ISSUE THREAD

**Issue by IamCarbonMan** [libretro/RetroArch#4133]
If the selected storage backend is Dropbox, but the user closes the Dropbox permissions page or denies access, the client simply hangs, waiting on Dropbox authorization. It should detect that Dropbox permissions were not granted and gracefully display an error or automatically switch to the LocalStorage backend.

**Comment by RobLoach** [comment]
The web player storage system could do with some updates. Let's talk about that over at https://github.com/libretro/RetroArch/issues/4134 . Thanks!

**Comment by fr500** [comment]
that dropbox api is now deprecated anyway and I won't upgrade it at least.
