### ISSUE TITLE
Move Configurations to Settings → Configuration

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#4143]
The Main Menu → Configurations page seems like a strange place for the Main Menu.

![screenshot at 2016-12-03 10-15-21](https://cloud.githubusercontent.com/assets/25086/20860245/693bc76a-b941-11e6-837f-af895ad6727d.png)

The active configuration saving/loading could likely move to the Settings → Configuration menu to help clean up the Main Menu...

![screenshot at 2016-12-03 10-15-59](https://cloud.githubusercontent.com/assets/25086/20860248/7f7bb6b6-b941-11e6-85b0-b0ca1cfa2102.png)

I propose moving Main Menu → Configurations to be in Settings → Configuration.

**Comment by fr500** [comment]
Settings are settings.
Saving the config is not a setting. It's an action.

I would put them in the main dir instead of grouping them under Configurations since people my expect settings to be in there.

**Comment by lasers** [comment]
A brief history... I tried this two weeks ago (the other way around). I only know minimal programming so I suck at doing things like this. There were lot of configuration* methods everywhere too. https://github.com/libretro/RetroArch/pull/4012

**Comment by fr500** [comment]
Moving it to settings --does-not-make-sense--

**Comment by RobLoach** [comment]
> Settings are settings.
Saving the config is not a setting. It's an action.

I see the distinction now, thanks, and see where the breakdown is... Seems like Configurations → *Load Configuration File* is a setting, while Configurations → *Save Current Configuration* is an Action relating to the config.

This could be compared to how Settings → Recording → *Load Recording Config* is an action, yet is in Settings.

**Comment by RobLoach** [comment]
Rename Main Menu → Configurations to Main Menu → Configuration Management? That would make sense to me. Agreed that we don't want clutter in the Main Menu.

**Comment by RobLoach** [comment]
Going to close for now.
