### ISSUE TITLE
Android - System Dir not writable

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#4150]
On Android, someone may put their ROMs on an external SD card. By default the system dir is the "content dir", and it seems that RetroArch can't write to that directory, see here for an example:

https://github.com/GLupeN64/GLupeN64/issues/127#issuecomment-264649500

Solution: Give the RetroArch the correct permissions to write to external SD cards. Alternatively you could have the "system dir" default to ```Android/data/com.retroarch/files/system```. This folder already seems to be created, but the "system dir" still defaults to "content dir"

**Comment by fr500** [comment]
I tried to do the runtime permissions stuff but I didn't really manage it. I'm not good with java.
We can't "force a default" without breaking the "stuff in content dir functions sadly"

I've been trying to life that limitation for a while but ultimately failed.
It shouldn't create that dir anymore btw. It was littering dirs all over the place :p I cleaned that up.

I'll try to figure something.

**Comment by Aaahh** [comment]
RetroArch has permission to write to external sd, what's the problem?

**Comment by fr500** [comment]
Since android 6 apps have to request dangerous permissions at runtime
https://developer.android.com/training/permissions/requesting.html
