### ISSUE TITLE
DInothawr: Error handling assets

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#4155]
![2016-12-04__02 23 27](https://cloud.githubusercontent.com/assets/852504/20864927/6f004918-b9c9-11e6-96fc-115224f200b5.png)

**Comment by Kivutar** [comment]
Need more informations

**Comment by lasers** [comment]
Hi. I'm not sure what else I can provide. Latest RetroArch on Arch64. The assets shows up fine under other emulators. I also tested it with Cave Story.

**Comment by RobLoach** [comment]
How did you make this happen?

**Comment by lasers** [comment]
Load Core & Load Content.... and from our new playlist too.

**Comment by RobLoach** [comment]
Assets don't disappear for me...

![screenshot at 2016-12-04 06-21-11](https://cloud.githubusercontent.com/assets/25086/20865795/df33a3c2-b9e9-11e6-917a-d70dbc598b65.png)

**Comment by lasers** [comment]
Fixed automagically. Many thanks for your help.

**Comment by lasers** [comment]
It came back. This bug is rather strange and I can't find anything out of ordinary.

I would like to keep this issue closed though since I'm the only one who experienced this. I'm also stuck on level 5-2 and can't find a walkthrough online. I aim to finish all levels.

**Comment by IAmBoring** [comment]
Problem I think was a multi-threading audio bug with some drivers. Dropping to menu would not pause core correctly and keep randomly corrupting things.
https://github.com/libretro/RetroArch/commit/e1b2cba7efb35cf95ee8d9accad8fd9d3771a450

Full solution guide.
https://github.com/Dinothawr-2013-Walkthrough/Solution
