### ISSUE TITLE
build fail with miniupnpc-1.9

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#4156]
Fail with the following error : 
`libretro-common/net/net_natt.c:55:14: error: too few arguments to function ‘upnpDiscover’ devlist = upnpDiscover(2000, NULL, NULL, 0, 0, &upnperror);`
Build successfully with miniupnpc-1.8

**Comment by twinaphex** [comment]
Its just great how nobody cares about ABI breaks anymore...

Anyway over to you @Yahweasel

**Comment by GregorR** [comment]
A bunch of distros pickd up MiniUPnP 1.9 at various phases of git development, so they're all a bit different @_@

What distro and what version does it claim? I think I'm going to drop support for all pre-2.0.
