### ISSUE TITLE
RA freeze trying to scan mame and fba

### ISSUE THREAD

**Issue by lollo78** [libretro/RetroArch#4162]
Hi, on Rpi I have a strage issue. If I try to scan a full romsets of mame2003 and fba, retroarch freeze instead to start scanning. 
For all the other platforms the scanning system works fine.
Could be an issue related on the number of files to scan?

**Comment by lollo78** [comment]
I leaved it in freezed state for some minutes and now finally fba scan is started. So seems that this freeze is only apparence. RA are trying to scan 43275 files (every single files inside the various .zip), than I suppose that you have changed the rdb and the scan system. 
So this could be a normal or known "issue" also for mame2003. If is it so, please close this issue. If not please investigate about this slow starting scan that looks like a scary freeze.

**Comment by RobLoach** [comment]
I believe the initial scanning to build the task queue is initially slow. May be good to get some feedback during that process.

@bparker06 would likely know more. :+1:

**Comment by bparker06** [comment]
Yes this is "normal" with large sets but ideally we should change this list buildup to be asynchronous so it does not block the GUI.

**Comment by lollo78** [comment]
It would be desirable. I really turned off several times my Rpi because I thought it was freezed. This could be create panic for a lot of users  :)

**Comment by cudencuden** [comment]
same behavior when scanning mapped shares.  you just need to wait

**Comment by lollo78** [comment]
Wait is not a problem, also 10 or more minutes: I scanned fba and mame full romsets on a mapped network drive...
The important is to reach the goal. But after 1 minute of total gui freeze, a normal usuer will quit from the system. there is no message that alerts users of this strange behavior. But honestly, see a freezed GUI is not beautiful.

**Comment by bparker06** [comment]
fixed in 5733d8e
