### ISSUE TITLE
Rotation not working properly with vulkan ?

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#4165]
Not sure this is the right place to ask this, sorry.

`environ_cb(RETRO_ENVIRONMENT_SET_ROTATION, &rotation);` in fbalpha's source code doesn't seem to work when i set video driver to vulkan. Setting rotation through retroarch's menu seems to work though. Any idea how i could solve this ?

**Comment by AlexFolland** [comment]
Do you have "Allow rotation" enabled in RA settings -> "Core" -> "Allow rotation"?  With this disabled, RETRO_ENVIRONMENT_SET_ROTATION is ignored by RA.

**Comment by barbudreadmon** [comment]
Didn't check that (and i'm not at home right now), but the fact is that it works when i switch back to the "gl" video driver, so that would mean this "Allow rotation" setting is ignored when using the "gl" video driver ? Seems fishy.
By the way, perhaps i should mention this, my gpu is a gtx 960 with proprietary drivers (375.20).

**Comment by AlexFolland** [comment]
In that case, there's definitely a bug here somewhere.  Whether it's in the usage of OpenGL or Vulkan is to be determined.

**Comment by barbudreadmon** [comment]
I don't know if it is related, but i get those message with vulkan : 

> RetroArch [INFO] :: [Vulkan]: VSync => on
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 2.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 3.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 0.
RetroArch [INFO] :: [Vulkan]: Creating swapchain with present mode: 2
RetroArch [INFO] :: [Vulkan]: Using swapchain size 720 x 960.
RetroArch [INFO] :: [Vulkan]: Recycled old swapchain.
RetroArch [INFO] :: [Vulkan]: Got 3 swapchain images.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.

**Comment by barbudreadmon** [comment]
Also i can confirm "Allow rotation" is on.

**Comment by barbudreadmon** [comment]
Steps to reproduce :
- Launch a game like "aearofgt" through fbalpha with gl video driver, make sure "Allow rotation" is on, the game will auto-rotate.
- Change to vulkan video driver, launch the same game, it won't auto-rotate.

Would be nice if someone could confirm having the same issue.

**Comment by barbudreadmon** [comment]
Seems i was wrong, the rotation feature works on vulkan, but it goes the wrong way : 
- setting RETRO_ENVIRONMENT_SET_ROTATION to 1 with gl video driver will rotate 45% counter-clockwise
- setting RETRO_ENVIRONMENT_SET_ROTATION to 1 with vulkan video driver will rotate 45% clockwise

I think only "1" and "3" values don't work properly.

**Comment by AlexFolland** [comment]
Do you mean 90° rather than 45%?

**Comment by barbudreadmon** [comment]
Yes, sorry i meant 90°.
I'm not totally sure but i think replacing 90 by 270 at line 1285 of gfx/drivers/vulkan.c would solve this issue (i've seen something similar with other video drivers). I'll do some test and send a pull request if it solve anything.

**Comment by barbudreadmon** [comment]
It sould be fixed, i close.
