### ISSUE TITLE
compile issues

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#4170]
cannot compile latest commit. i used to have these #pragma warnings but was still able to build and use them but todays commit, i cannot compile anymore.

>In file included from menu/drivers_display/../../gfx/include/d3d9/d3dx9.h:48:0,
                 from menu/drivers_display/../../gfx/include/d3d9/d3dx9math.h:10,
                 from menu/drivers_display/menu_display_d3d.cpp:33:
menu/drivers_display/../../gfx/include/d3d9/d3dx9core.h:669:1: warning: multi-line comment [-Wcomment]
 //   *\                *\
 ^
menu/drivers_display/menu_display_d3d.cpp: In function 'void menu_display_d3d_draw_pipeline(void*)':
menu/drivers_display/menu_display_d3d.cpp:208:12: error: 'VIDEO_SHADER_MENU_SEC' was not declared in this scope
       case VIDEO_SHADER_MENU_SEC:
            ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:151: obj-unix/menu/drivers_display/menu_display_d3d.o] Error 1

MEDIA@DESKTOP MINGW64 ~/retroarch
$

**Comment by bparker06** [comment]
should be fixed in 7a7a4f1

**Comment by retro-wertz** [comment]
thanks. it now compiles.
