### ISSUE TITLE
Can't switch drive in file browser with "Select File and Detect Core"

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#4173]
After browsing up a level repeatedly, the file browser ends up in the RetroArch directory instead of going to the drive selection.  I was unable to browse from my D: to my G:, so I had to go to settings -> directory to switch the file browser starting directory, then go back to "Open ROM and detect core", then go back and switch the setting back.

**Comment by fr500** [comment]
try to explain it better, add a video or a gif if possible

**Comment by retro-wertz** [comment]
probably what he means is if you are viewing for example root of your C:
driver, pressing Parent directory, the upper folder suppose then will
suppose to show your other drives like C: D: and E: but ends up in
retroarch folder instead.

**Comment by AlexFolland** [comment]
Why "explain it better"?  It's an obvious bug that anyone can reproduce simply by trying to navigate between drives in "Select File and Detect Core"

**Comment by fr500** [comment]
Not everyone here used Windows.  A visual explanation may help someone to
look at the problem even if he can't reproduce.

**Comment by AlexFolland** [comment]
How do I add the "windows" label?  You've edited the title to remove "[Windows]", but forgot to add the "windows" label.

**Comment by fr500** [comment]
Visual explanation:
https://www.youtube.com/watch?v=6L7WZMGb-bU

**Comment by fr500** [comment]
I already mentioned this to @twinaphex
