### ISSUE TITLE
Failed to open libretro core with latest GlupeN64

### ISSUE THREAD

**Issue by diegoviola** [libretro/RetroArch#4179]
**System:**

Arch Linux (x86_64)
RetroArch git 3600e29bbb968ebfc14d7901b66bdafb382f2932

**Problem:**

Using the latest glupen64 from buildbot results in a "Failed to open libretro core" when opening the core with a ROM.

If I build glupen64 myself, it works fine.

**Steps to reproduce:**

1. Load core -> Download core -> glupen64_libretro.so.zip
2. Load core -> glupen64_libretro.so
3. Load content -> Select File -> rom file

Should result in "Failed to open libretro core"

**Expected results:**

Game works fine with the core.

**Comment by orbea** [comment]
Do cores from @loganmc10 's build bot work?

http://loganbuildbot.s3-website-us-east-1.amazonaws.com/

**Comment by diegoviola** [comment]
@orbea Yes.

**Comment by fr500** [comment]
Build issue not a RetroArch issue.

**Comment by diegoviola** [comment]
@fr500 so will this be fixed in the latest build?

**Comment by diegoviola** [comment]
I tested it now and it's still broken, please fix the build.

**Comment by diegoviola** [comment]
This shouldn't have been closed, please reopen it. I know it's not a RA issue but the build is broken in the buildbot.

**Comment by fr500** [comment]
It's not a retroarch issue.  Doesn't belong here.

**Comment by diegoviola** [comment]
@fr500 The build in the buildbot is still broken.

Where do I report this then?

**Comment by fr500** [comment]
libretro-super I guess.
libretro-buildbot is private so you can't report it there

**Comment by diegoviola** [comment]
Done, thanks.
