### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by Alcaro** [libretro/RetroArch#4185]
I keep explaining this about once per week.

We need SSL support for some things, such as the Dropbox API.

I have a few SSL library wrappers [here](https://github.com/Alcaro/Arlib/tree/master/arlib/socket). They're C++, but that should be easy to strip out; they're in classes, and their interface contains even more classes, but the important parts should be C-compatible.

Do whatever you want with them, including relicensing and copying to libretro-common.

**Comment by orbea** [comment]
@Alcaro Not sure how much you care, but RetroArch now has working SSL support through mbedtls which can be used as either a baked in dependency or as a system library with `./configure --disable-builtinmbedtls`. As a result I am going to close this issue.
