### ISSUE TITLE
Latest Windows nightly from Buildbot does not contain any .exe

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#4186]
As verified by clicking on the following links:
(x86) http://buildbot.libretro.com/nightly/windows/x86/
(x64) http://buildbot.libretro.com/nightly/windows/x86_64/

The latest Nightly RA packages available on the official buildbot do not seem to contain any executable.

Similar to what happened with issue #3204.

**Comment by lasers** [comment]
Buildbot is a timed occurrence. Two bad commits were merged yesterday four hours before this post showed up. I'm guessing it was just a bad compilation now and then.
```
2016-12-07 02:07 (Commits merged ; Could not compile this due to error)
2016-12-07 04:45 (Timed compilation)
2016-12-07 06:06 (Your post)
```

**Comment by fr500** [comment]
@lasers I know you want to help but you don't have to chime in in every issue. 
This is particularly true when you don't know anything about what is being asked about.

@Ryunam it's been happening for a few weeks. I have no idea about what it is... it happens at random and I don't have time to fix it.

**Comment by lasers** [comment]
@fr500 Sorry. I'll leave it to you.

**Comment by Ryunam** [comment]
@fr500 Sorry to reopen this for the upteenth time, but the problem has resurfaced and the Buildbot for Windows appears to be malfunctioning again, resulting in no new compiled version appearing in the folder.
The latest available binaries for both RA and each individual core date back to December 14 for the x86 versions and December 16 for the x64 versions.

(x86) http://buildbot.libretro.com/nightly/windows/x86/
(x64) http://buildbot.libretro.com/nightly/windows/x86_64/

**Comment by twinaphex** [comment]
We are aware of the issue, it doesn't require further pointing out. We are still in the process of setting up the new Windows buildbot.
