### ISSUE TITLE
[Android] RA is not opening

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#4187]
I'm getting "RA has stopped" window with last commit. I can't get a trace right now

S4 mini GT-i9195, Android 4.4.2

**Comment by bparker06** [comment]
What exact device are you using? Are you able to post a list of supported OpenGL extensions on that device? There should be several available apps that can do it. I suspect it could be related to the GLES changes I made yesterday.

**Comment by lasers** [comment]
I'm getting the same thing under linux.

I think it's the "Replacing hardcoded "lpl" w/FILE_PATH_LPL_EXTENSION_NO_DOT commits"

**Comment by sergiobenrocha2** [comment]
Fixed
