### ISSUE TITLE
Android - Overlay / Button Presets

### ISSUE THREAD

**Issue by Talantyyr** [libretro/RetroArch#4196]
It would add greatly to usability, if there would be button presets for all cores on android.

Right now, if you start a core, like GameBoy for example, you get all the buttons available (A/B/X/Y, shoulder buttons and so on). If you rotate the device, everything's squeezed. 

If you could add default presets, with only the buttons used by the platform, it'd be much easier for new users (and save experienced users the hazzle of setting everything up again).

If we push this thought further, it'd be nice to have layout-presets, like default buttons, colored buttons, Handheld overlays and/or shaders pre-configured.

**Comment by sergiobenrocha2** [comment]
There is already something like this: https://libretro.com/forums/showthread.php?t=4066

Just copy the config pack from there to your config folder, and see if Settings tab --> Configuration --> Load Override Files Automatically = ON

There's a button in the overlays which switch between landscape and portrait:

![screenshot_2016-12-09-14-17-56](https://cloud.githubusercontent.com/assets/5431285/21055921/8c7b69dc-be1a-11e6-8410-522d0289c545.png)

**Comment by fr500** [comment]
As sergio said. There is no need to introduce more per-core stuff now with overrides
