### ISSUE TITLE
Config overide file, video driver option is ignored.

### ISSUE THREAD

**Issue by mac1202** [libretro/RetroArch#4198]
Hi I use a main retroarch config and override config for core specific option. My retroarch.cfg is set to use gl video driver, if I set my override config file to vulkan video driver ( for parallel and psx vulkan core) it doesnt work retroarch still use gl video driver. If I set video driver to vulkan in my retroarch.cfg it work as expected.

**Comment by hizzlekizzle** [comment]
IIRC, by the time overrides kick in, it's too late to change the video driver.

**Comment by tony971** [comment]
#3297

**Comment by fr500** [comment]
Duplicate as tony mentioned
