### ISSUE TITLE
games listed two times in the  "Load Content","Downloads" menu

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#4200]
Hello,

when I download games from retroarch "Online updater","Content downloader", the files are stored in the retroarch "Download" folder. Then when I launch them "Load Content","Downloads", retroarch unarchived downloaded games before to launch them. Next time I launch retroarch, "Load Content","Downloads", each game listed 2 times because retroarch found the original and the extracted archive game...it didn't erase the temporary extracted archive game...

Perrhaps it should use the official OS temporary folder. Or his own temporary folder that could be empty at each retroarch launch.

Thank you for your help.

LGDN.
This

**Comment by fr500** [comment]
I think it always extracts downloads

**Comment by RobLoach** [comment]
I believe this is fixed. I could be wrong though... Feel free to re-open or create a new issue if you find it still a problem.
