### ISSUE TITLE
Yahweasel: compilation PS3 fails because of netplay changes

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4202]
@GregorR - http://hastebin.com/eticofagak.vbs

**Comment by GregorR** [comment]
An SDK defining AF_INET6 but not defining any of the IPv6 structures is beyond "broken and incomplete", it's downright psychopathic. There's no way I can make IPv6 work anywhere at all if I can't detect where it's available and where it isn't. Is it reasonable to add a HAVE_IPV6_BROKEN define and just set that for PS3 (and any other platforms ludicrous enough to set AF_INET6 but not define struct sockaddr_in6 etc)?

**Comment by GregorR** [comment]
(I'm going to proceed under the assumption that the answer is "yes" and adjust if necessary)

**Comment by twinaphex** [comment]
Compiles again.
