### ISSUE TITLE
Second USB controller does not work on Windows

### ISSUE THREAD

**Issue by Nekmo** [libretro/RetroArch#4204]
I've been HOURS trying to run my second SNES controller on Windows with Retroarch, but the documentation is confusing, outdated and there are 65536 ways to configure the controls in Retroarch.

There are people who say that using xinput works, but it has not work me.
https://libretro.com/forums/archive/index.php?t-1919.html

Here it says to use Emulastation, which detects the 2 controllers and works GREAT but nothing changes in Retroarch.
https://github.com/retropie/retropie-setup/wiki/retroarch-configuration

Here it talks about using Retroarch-config, but it is no longer included with the Windows version.
https://github.com/libretro/RetroArch/wiki/RGUI
https://libretro.com/forums/showthread.php?t=1995

For all this, I just have to ask. Why?

**Comment by AlexFolland** [comment]
If it's the same type of device, there's a bug that makes both devices show the same number in XMB and/or RGUI.  For me, it shows "SNES (#0)" for both my SNES controllers, but switching between them works, even if I can't see the switch visually.  I believe this might be what you're experiencing, and if so, this is a bug with enumerating the controllers, and there's a workaround.  Try pressing the right arrowkey while "SNES (#0)" is highlighted.

**Comment by fr500** [comment]
When I added the #s it worked fine.
It must have broken on one of the refactors.

**Comment by fr500** [comment]
@Nekmo 
What kind of adapter or pad is this?

**Comment by AlexFolland** [comment]
It still shows "SNES (#0)" for both of my SNES controllers using RetroUSB adapters.

**Comment by fr500** [comment]
¯\_(ツ)_/¯
can't reproduce.

**Comment by AlexFolland** [comment]
Yes.  That's exactly what you said last time we had this conversation 1-2 years ago.  It's still a problem though.

**Comment by fr500** [comment]
Ok guess I can. You're not using autoconf apparently. The enumeration happens when autoconfiguring a pad. Someone would have to add it for static bindings.

**Comment by AlexFolland** [comment]
Autoconfiguration has never worked for any of the input devices I've used with RetroArch in any situation I've tried it, so I don't even know how to use it.

**Comment by fr500** [comment]
User 1 bind all
User 1 save autoconf
User 1 default all

That's all there is to it
Then default the bindings for user 2 too

**Comment by Nekmo** [comment]
@fr500 Thanks for your answer, It worked for me :D 

The gamepad is: https://es.aliexpress.com/item/1-x-Retro-Super-for-Nintendo-SNES-USB-Controller-for-PC-for-MAC-Controllers-SEALED/2051991309.html?detailNewVersion=&categoryId=200001103

@AlexFolland The same thing happened to me, but in my case "USB Gamepad (#0)".

Also it did not detect the type of controller well before. Now put "SNES joypad". The options before were RetroPad, RetroPad w/ Analog...

I could upload my configuration file, but I do not know if it would do anything because it now works. 

Although it works now for me, I do not close the thread because I think the problem still exists, and there may be more people suffering from this problem. I think it's a bug and it should be fixed.

**Comment by fr500** [comment]
Glad it does

**Comment by AlexFolland** [comment]
Why is this closed?  The issue still isn't resolved.  He posted that a workaround worked, but the issue shouldn't be closed.  Or should a new one be opened to describe the exact issue?

**Comment by fr500** [comment]
@danzel That issue is not really related, in windows it's only a display issue (the name displayed is identical for both pads)

**Comment by danzel** [comment]
Sorry thanks :+1:

**Comment by danzel** [comment]
I think I just found where the two controllers with `#0` naming comes from. (This happens on mac too)

`input_autoconfigure_joypad_reindex_devices` is the method that assigns numbers to names based on them being duplicates.
But it appears to only run if autoconfigure is successful (based on a very brief look through of this code).
> `input_autoconfigure_joypad_add` will return early if it doesn't find settings, before it would do the name index updating.

So if the controllers don't autoconfigure, they'll both get `#0` numbers!

Might look in to this more next week, but if someone else beats me to it please go ahead and fix :+1:
