### ISSUE TITLE
Issue navigating RGUI with keyboard configuration

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#4211]
platform RPI 3 with Raspbian Linux.

Cannot operate RGUI using configured player1 keys with config shown below - directions work, but buttons configured for `input_player1_a` and `input_player1_b` are ignored. Enter will quit RGUI even though it should only work in combination with the hotkey enable button. Was able to enter RGUI correctly by pressing "shift+s"

I believe menu input has been separated and there are some mentions of similar problems on other tickets, but didn't spot a ticket exactly for this particular issue. (One of the tickets also has multiple issues on it and has become a mess to follow).

```
/opt/retropie/emulators/retroarch/bin/retroarch --version
RetroArch: Frontend for libretro -- v1.3.6 -- 26fe408 --
Compiler: GCC (4.9.2) 32-bitBuilt: Dec 10 2016
```

`retroarch.cfg`

```
config_save_on_exit = "false"

input_joypad_driver = "udev"

input_player1_a = "z"
input_player1_b = "x"
input_player1_y = "a"
input_player1_x = "s"
input_player1_start = "enter"
input_player1_select = "shift"
input_player1_l = "q"
input_player1_r = "w"
input_player1_left = "left"
input_player1_right = "right"
input_player1_up = "up"
input_player1_down = "down"

input_enable_hotkey = "shift"
input_exit_emulator = "enter"
input_menu_toggle = "s"

menu_driver = "rgui"
```

**Comment by joolswills** [comment]
Can also reproduce this on my amd64 Ubuntu 16.10 desktop machine.

bisected to a9a2749af988781e3800ccf5e111f17124869ddf (in this commit no input works at all in RGUI, then a commit or two later, it's the behaviour as above)

```
a9a2749af988781e3800ccf5e111f17124869ddf is the first bad commit
commit a9a2749af988781e3800ccf5e111f17124869ddf
Author: twinaphex <libretro@gmail.com>
Date:   Thu Oct 27 00:13:29 2016 +0200

    Add input_menu_keys_pressed

:040000 040000 d77ebbd24f6524ae15e03dcc66117157c9f39990 070cae2ce5928f1f6a8af072a18efd88d9b14d98 M	input
:040000 040000 afee92165d182d44bdbe04acb6690feb9021ba40 6890e24b09d3346e71e8e67306a02c309f3449e2 M	menu
:100644 100644 ebfcfe7781d51d6b9aac9f359abe043b3619866f 491b23c66f016599ddebc891f1b99c62df3932f6 M	runloop.c
```

**Comment by fr500** [comment]
Do you still have issues?

**Comment by joolswills** [comment]
It can be closed as there is a configuration option to use the old behaviour. Thanks.
