### ISSUE TITLE
Vulkan snow XMB shaders don't work 

### ISSUE THREAD

**Issue by pepedopolous** [libretro/RetroArch#4218]
On Intel Skylake Skull Canyon NUC, Archlinux, latest mesa, vulkan, and retroarch from git. Snow shaders work for with OpenGL but for Vulkan there is just a plain background.

**Comment by twinaphex** [comment]
Vulkan snow shaders are simply not implemented. @Themaister could potentially convert them from GLSL GL.

**Comment by twinaphex** [comment]
I tried asking @hizzlekizzle to make a Vulkan port of the snow shader, but I couldn't get it to compile with glslc.

**Comment by AlexFolland** [comment]
This is a bug rather than an enhancement, considering that the snow options are available with Vulkan and selecting them does not show the intended visual effect, providing a false understanding of what the snow options are meant to display.

**Comment by twinaphex** [comment]
Well we have to wait for somebody who can do Vulkan shaders to get it to work. Code doesn't write itself. It's not important in the run-up to 1.4.0.

**Comment by AlexFolland** [comment]
I didn't claim it was especially important.  I just claimed that it was a bug, not an enhancement.

**Comment by pepedopolous** [comment]
Fixed today. Thanks!
