### ISSUE TITLE
Savestate screenshots should be not postprocessed

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4221]
Even if GPU screenshots are enabled.
Most people play with shaders. Taking a GPU screenshot takes more time, makes the screenshot bigger and it also makes the preview image ugly.

**Comment by twinaphex** [comment]
I just took a savestate with the new 'take raw screenshot 'behavior and it caused Mednafen/Beetle PSX and RetroArch to segfault. So I'm rolling this back until you can get this working reliably and stably.

**Comment by fr500** [comment]
Not sure how to fix that, but the issue stands. Right now my nestopia savestates are a few KB and my screenshots are several MB
