### ISSUE TITLE
Trapped Menu Controls

### ISSUE THREAD

**Issue by lasers** [libretro/RetroArch#4229]
Getting trapped under extended information everywhere after toggling...
Settings --> Input --> Unified Menu Controls --> ON

EDIT: It's not just that. Everything (partial controls) seems broken now.

**Comment by RobLoach** [comment]
The Unified Menu Controls changes the back button from Backspace (on the keyboard) to whatever you use in game for the B button (default is `Z` on the keyboard).

You're not trapped, you're just using the wrong key.
