### ISSUE TITLE
Core Information is missing if started from the commandline.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4232]
OS: `Slackware64-current`
`RetroArch-2016.12.05_fdac55e_master-x86_64-1_git`

In the main tab there is `Information > Core Information` which will only show up when a core is loaded and the info files are present. This works fine if the core is loaded from the RetroArch menu. However it will be missing if loaded from the command line. 

Example:

`retroarch -L /path/to/snes9x_libretro.so /path/to/game.sfc`

**Comment by RobLoach** [comment]
Confirmed...

1. Run game through command line
2. Visit the menu
3. Main Menu -> Information
4. Don't see Core Information
5. Load a Core through the menu
7. Visit Main Menu -> Information
8. Core Information appears

**Comment by orbea** [comment]
Starting games from the command line also fails to add games to the History tab.

**Comment by orbea** [comment]
The initial issue did not regress all at once. When started from a terminal `Core Information` failed to show starting in commit 6a9ae533cf7a5e8711822176ee4c399f51b42aa1. Before this when started from a terminal it would be present, but show `No core information available.` 
```
6a9ae533cf7a5e8711822176ee4c399f51b42aa1 is the first bad commit
commit 6a9ae533cf7a5e8711822176ee4c399f51b42aa1
Author: twinaphex <libretro@gmail.com>
Date:   Wed Nov 16 07:03:59 2016 +0100

    Core Information - hide

:040000 040000 ed829b657cd04ed5173e430aaf2ee46b568ebf0e ca198d61bc126bf348f93cd7c4ddd64e0c97d6f8 M	menu
```

**Comment by orbea** [comment]
This was broken in 1.3.6 too...

**Comment by orbea** [comment]
The core info issue was fixed here so I will close this issue and open a new one for the history issue.

https://github.com/libretro/RetroArch/commit/6cad8e3b7467e074f1ea1160340d342dd00b10c3
