### ISSUE TITLE
Game Lag when i pressed button using my 8bitdo zero controller

### ISSUE THREAD

**Issue by omegaRJ** [libretro/RetroArch#4236]
My device is iPad Pro iOS 9.3.3
My controller is 8bitdo zero

I play super mario world
When i pressed button A, B, X, all button even D-pad. The game become lag like paused for a split second.
Then i tried the on screen button, the game plays normally, no lag.
Why is this?

**Comment by omegaRJ** [comment]
Update
I tried playing using steelseries nimbus controller. It works fine. No lag.
The problem occurs when i played using 8bitdo zero controller.
Does the problem because 8bitdo zero buttons are keyboards?

**Comment by fr500** [comment]
Maybe, not sure, iOS is weird like that...

**Comment by danzel** [comment]
Do you have a bluetooth keyboard you could connect and try with @omegaRJ ?

**Comment by omegaRJ** [comment]
Update
I tried playing using bluetooth keyboard
The problem occurs the same when i used 8bitdo zero controller.
The lag happened. The game stop for a split second when i pressed any button on the keyboard that i set for input in retroarch
I think the problem is the keyboard input. Because 8bitdo zero controller is keyboard based. That makes the same input for bluetooth keyboard and 8bitdo zero. The nimbus controller works fine because the input is controller button (button 0, button 1, etc)

**Comment by omegaRJ** [comment]
Last Update
It appears the problem was in the ROM i run
I tried playing other ROM and its fine. No lag.
Sorry for confusing.
Thanks for the response btw.
