### ISSUE TITLE
XMB vertical navigation loop depends on list count

### ISSUE THREAD

**Issue by r4dius** [libretro/RetroArch#4238]
If you keep up or down pressed in a menu it will loop from bottom to top or vice versa as many times as the number of items in the list,
example : let's say I have a "nes" list with 4 games, I press bottom, the list will loop 4 times and stop at the bottom after the 4th loop,

By the way I think the list should always stop at the last / first item and only loop when you press again, actualy the navigation is so fast the automatic loop is quite unusuable.

**Comment by i30817** [comment]
Try not having some keys on the keyboard so you can go down. Not that i'm bitter my remapping menu keys issue got ignored or anything.

**Comment by Awakened0** [comment]
@i30817 there is an option to use the old menu control mapping method you can enable until someone implements custom menu controls. It was added a few days ago. Set menu_unified_controls = "true" in your config.

**Comment by i30817** [comment]
thanks man.

**Comment by sonninnos** [comment]
Has not been happening for a long time.
