### ISSUE TITLE
New Content Loader improvements

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4245]
The new menu looks great and I haven't found any glaring problems.
That said, I think the 3 bottom-most items should be at the top.

Maybe Favorites should be Games?
And if compiled with FFMPEG we could have a Videos dir and a Music dir

![image](https://cloud.githubusercontent.com/assets/1721040/21210647/bce249d6-c24a-11e6-962d-6657ea732164.png)

**Comment by bparker06** [comment]
The only thing I noticed was that you can't use "Parent directory" to get back to the drive listing, you have to use the back button instead.

**Comment by fr500** [comment]
Parent should always mean parent... If you do parent eventually you end up
in retroarch dir

**Comment by sergiobenrocha2** [comment]
I think Favorite and the others should be at the top too, with Favorite first. Directory --> File Browser and Favorite should match the name maybe?

**Comment by sergiobenrocha2** [comment]
why do we exactly have Collections there? Isn't it redundant, I mean, you can load the game with the xmb lists

**Comment by fr500** [comment]
this isn't XMB only
Also, I think the favorites name is baaaad

Favorites should be a vertical list with some games you pick as favorites on other lists

**Comment by sergiobenrocha2** [comment]
I'm pretty sure average android users will have no idea what to do here:

![screenshot_2016-12-17-13-27-09](https://cloud.githubusercontent.com/assets/5431285/21287901/cc3d6ff0-c45c-11e6-9bf1-9dbfe58c0cb3.png)

**Comment by ZacharyFoxx** [comment]
Two suggestions: 

1 - Rename "Favourite" to "ROMs"
2 - Creat a item "Browser" and when you choose this you will see the Retroarch's system directory. 

Why this:

1 - I think that the great majority of users put your ROM's directory in the option "File Browser";
2 - Don't make sense see this structure  with the Retroarch's directory, system root and "Favourite" and "Download".
