### ISSUE TITLE
Why not F-Droid?

### ISSUE THREAD

**Issue by Clonewayx** [libretro/RetroArch#4247]
Why RetroArch isn't in libre repositori for android [F-Droid](https://f-droid.org/about/)?

**Comment by Alcaro** [comment]
Many of our cores are under noncommercial licenses that F-Droid won't touch.

But I'm not completely sure why the GPL cores aren't there.

**Comment by bparker06** [comment]
I thought our local f-droid repo didn't include cores anyway? If that's something the user downloads later, do they still have a legitimate concern or is it just a "never too safe" thing?

**Comment by fr500** [comment]
I think it's more of an...  Ask them?  They would have to add it I think

**Comment by jcgruenhage** [comment]
They don't have it included right now, because the app won't build in their environment properly, the builds crash upon startup, as you can read here: https://gitlab.com/fdroid/fdroiddata/issues/304

If someone were to look into that, that would be great!

**Comment by fr500** [comment]
We have our own repo though... it's enough o a mantainance burden to have our own builds.

**Comment by jcgruenhage** [comment]
You do? I didn't know :D
I'll check if I can find that then :)

**Comment by jcgruenhage** [comment]
I just tried adding that to F-Droid, but it says that there was an error getting the index file..

**Comment by fr500** [comment]
I just tried on my phone and it worked

**Comment by jcgruenhage** [comment]
Strange. I've tried multiple different F-Droid apps now, but I get the same error ("Error getting index file") on each of them..

**Comment by twinaphex** [comment]
I keep getting this too.

This is a serious issue and it's honestly embarrassing that a year later nothing has been done to look at this.

I cannot even debug a serious issue on Android right now because of this.

**Comment by hpr** [comment]
@twinaphex, the correct repository is here: https://fdroid.libretro.com/

**Comment by twinaphex** [comment]
@hpr I know that already,  and that is the exact same repo that also doesn't work for me.

**Comment by hpr** [comment]
@twinaphex hm, I added it minutes ago and it worked. The [index.xml file is here](https://fdroid.libretro.com/index.xml), does clicking that link work for you on your phone? is there any error text you're getting?

**Comment by sjdrc** [comment]
I was experiencing this same error until I entered:
```
http://fdroid.libretro.com/
```
And it picked up everything after that.

**Comment by soredake** [comment]
@jcgruenhage same problem for me, changine https -> http fixed it

**Comment by jcgruenhage** [comment]
@soredake disabling security is never a solution though, I wouldn't even consider it being a workaround

**Comment by fr500** [comment]
Neither is a solution, the non SSL one is not updated anyhow, it's broken
and I don't have time to fix it now.

**Comment by soredake** [comment]
https://gitlab.com/fdroid/fdroidclient/issues/1505

**Comment by fr500** [comment]
It is not their problem it's ours, our setup is broken.
