### ISSUE TITLE
Issue with missing stdint on odroid-c2 / ubuntu 16.04 (gcc 5.4.0)

### ISSUE THREAD

**Issue by joolswills** [libretro/RetroArch#4248]
I know how to workaround the following issue, but need clarification on the correct route - 

```
CC libretro-common/glsym/glsym_es2.c

In file included from ./libretro-common/include/glsym/glsym.h:30:0,
                 from libretro-common/glsym/glsym_es2.c:1:
./libretro-common/include/glsym/glsym_es2.h:43:9: error: unknown type name ‘int64_t’
 typedef int64_t  GLint64;
         ^
./libretro-common/include/glsym/glsym_es2.h:47:9: error: unknown type name ‘uint64_t’
 typedef uint64_t GLuint64;
```

Either the `__STDC_VERSION__` comparison above needs to be changed, or we need to use `unsigned long long int / long long int` or include `<stdint.h>`

```
gcc -dM -E - < /dev/null | grep "__STDC_VERSION__"
#define __STDC_VERSION__ 201112L
```

which fix you prefer @twinaphex ?

**Comment by Kivutar** [comment]
Try this patch https://github.com/lakkatv/Lakka-LibreELEC/blob/master/packages/libretro/retroarch/patches/retroarch-09-fix-int64.patch

Or modify the if to force it to 1 or 0

It will certainly fix your problem.

**Comment by joolswills** [comment]
@Kivutar Thanks - that won't work - see above `#define __STDC_VERSION__ 201112L
`

I have a fix locally, but I am waiting to get a fix back into RetroArch and want to know which they prefer - either increasing the __STDC_VERSION__, not using stdint types or adding stdint header.

**Comment by joolswills** [comment]
My current patch is the same as yours but using a higher version.

```diff
diff --git a/libretro-common/include/glsym/glsym_es2.h b/libretro-common/include/glsym/glsym_es2.h
index 08aedbd..dba01fd 100644
--- a/libretro-common/include/glsym/glsym_es2.h
+++ b/libretro-common/include/glsym/glsym_es2.h
@@ -23,7 +23,7 @@ typedef void *GLeglImageOES;
 typedef GLint GLfixed;
 #endif
 
-#if (__STDC_VERSION__ <= 199409L) || (OSX && !MAC_OS_X_VERSION_10_7)
+#if (__STDC_VERSION__ <= 201112L) || (OSX && !MAC_OS_X_VERSION_10_7)
 #ifndef GLint64
 typedef long long int GLint64;
 #endif
```

but I don't know if this will affectother systems - I assume some systems don't need stdint included to use int64_t ?

**Comment by joolswills** [comment]
no longer needed as of https://github.com/libretro/RetroArch/commit/c81d54bd4654b4db80bb54f860e2bb97e6fa6bb8
