### ISSUE TITLE
RetroArch 12-14-16 No Core Found Wii U/Crash

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#4251]
Not sure if this has been brought to your guys' attention, recently compiled builds of RetroArch Wii U (as of December 14th and on), have been yielding "No Core Found" errors for each of the core apps, and having the console completely locking up, forcing a hard reboot.  Previous builds do not yield this error.

**Comment by twinaphex** [comment]
The load content refactors unfortunately caused this, and likely affects all statically linked RA versions.

I will have to first figure out how to compile statically linked RA again on PC before I can proceed in fixing this.

**Comment by roflcopter777** [comment]
Yikes, that sucks, do what you need to do

**Comment by r-type** [comment]
#4246

**Comment by twinaphex** [comment]
Is this fixed now @roflcopter777 ?

**Comment by roflcopter777** [comment]
Apologies, I've been busy all day today

Tested Snes9x mainline from the 12-23-16 19:26 nightly, and tested Star Fox (NTSC):
Result: Game boots without an issue, though it doesn't auto boot, and shows the core that it needs to load, despite loading the Snes9x core

However, subsequently loading a second ROM within the emulator results in a DSI exception. So, yeah, it works for the first ROM but loading a second ROM crashes the emulator >.> Damn.

**Comment by roflcopter777** [comment]
To reiterate, the cores don't automatically load the games in the respective core, i.e. Snes9x doesn't automatically load the game, but it shows the core that's about to load, then you choose the Snes9x core, and then it loads. Previous builds did not have this issue.

**Comment by twinaphex** [comment]
This is not an issue, if there is more than one choice, then it will allow you to choose a cure, and it will also show the 'Current core' at the top of that list. That is not an issue, that is the new behavior.

**Comment by roflcopter777** [comment]
Even though the Wii U apps only load one core at a time (as in, each core it it's own app)?  And loading a second ROM in succession results in a DSI exception?

**Comment by roflcopter777** [comment]
Addendum: Snes9x standalone app still shows a core to choose from, older builds didn't do that, it loaded the Snes ROM without issue. I'll record a video later.

**Comment by twinaphex** [comment]
That's a core issue and not a RetroArch issue, that's just a memory leak that happens somewhere.

Don't conflate RetroArch issues with core issues.

**Comment by twinaphex** [comment]
Anyway, regarding the current core/core selection stuff, this is how it currently works, and it's honestly not a really big deal. I think it's fine as is. Later on we might revisit it, right now it's not a priority.

**Comment by roflcopter777** [comment]
How was I supposed to know that? *headdesk* Sigh... What about loading two ROMs in a row causing the emulator/console to crash, surely, that's a problem, no?

**Comment by twinaphex** [comment]
that is a core problem to do with The snes9x core. Will be looked into
