### ISSUE TITLE
Play games from file streams

### ISSUE THREAD

**Issue by belldandu** [libretro/RetroArch#4253]
Not sure how feasible this is but if you could make it so that retroarch can connect to a server and play games via emu's using the files on the server (aka a filestream) then people would not have to worry about device storage especially on things like android.

**Comment by fr500** [comment]
If the VFS ever gets merged it would be possible I guess.
We already have a downloader and people could replicate the setup easily to play their own roms on their own hosting.

**Comment by orbea** [comment]
VFS support was done a while ago, please see this PR (And others) for more details.

https://github.com/libretro/RetroArch/pull/5664

If there are any specific issues with VFS support please bring them up in new issues.
