### ISSUE TITLE
Slow loading Rom Browser (WiiU)

### ISSUE THREAD

**Issue by Ploggy** [libretro/RetroArch#4259]
Loading folders with lots of roms in causes the file browser to lag terribly.
Mame is effected by this the worst obviously ;) It can take as long as 5 mins plus for the Rom list to show.

**Comment by twinaphex** [comment]
File I/O can be disastrously slow on game consoles. The Wii U is probably no exception.

I remember PS3 HDD disk I/O access being terrible too compared to PC.

I'd encourage you to not have too many files in one single folder.

**Comment by Ploggy** [comment]
IIRC this was an issue in the beginning with the original Wii but was fixed somehow?
I think I read on GBAtemp somewhere that the FS Nintendo uses is basically pants and Dimok has made a new FS for homebrew to use..
https://github.com/dimok789/libfat
https://github.com/dimok789/libiosuhax
He seems to think it would be faster than Nintendos and hopefully help with the lagging issue?

**Comment by roflcopter777** [comment]
What's weird is that the Genesis Plus, Nestopia and other cores load the ROM folder instantly, Snes9x 2010 and regular take upwards of 30 seconds to load a ROM folder irrespective of the no. of files in it. Libfat from Dimok would help methinks

**Comment by Ploggy** [comment]
Fix94 has added the new fs and File Browser speed is now lightning fast and USB support has been added as a bonus lol 

This can be closed now :)

Thanks.
