### ISSUE TITLE
Changing the Configuration and then loading a game with overrides loses changes made

### ISSUE THREAD

**Issue by airecajr** [libretro/RetroArch#4264]
Hi!, Doing some more testing on a previous overrides issue i noticed that if you make changes to the configuration and then loading a game that has game overrides reverts the changes made to its original value, these settings modified are not the same as the ones included in the override file.

Here are the steps to reproduce:
1 Open Retroarch and modify a setting (i tried with analog deadzone and audio on/off)
2 Load a game that has a Game Override config file
3 Open the menu and check the configuration, the changes made reverted to the value it had when Retroarch was opened

Please notice the values modified before opening the game are not in the override file.
I tested after using an empty Game Overrides config file and the same thing happens.
The same thing happens with a Core Overrides config.

Im using Windows 10 64bit, and Retroarch x86_64 from buildbot date 15 december, i used Mednafen and Bsnes cores.

**Comment by fr500** [comment]
It's not an issue. When you load a core/game with overrides the config is reloaded.
If you want those to stick to the game that will load do a save current config

**Comment by airecajr** [comment]
Thanks for the info again! whoa that was fast response

Checked and it work like you say
However i find it counterintuitive that the changes made are lost upon loading a game with overrides, because normally(at least for me) i would just load a game make some changes and close and expect them to save when closing.
Like maybe a warning saying that changes are going to be lost, or like an option to auto-save settings before loading a game.

**Comment by fr500** [comment]
Well, it's the way it works. It's a counter intuitive I agree but I made it like this on purpose. I didn't want global changes leaking into overrides and override changes leaking back into global.
