### ISSUE TITLE
Request: a way to save settings from anywhere

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#4276]
There should be something akin to a "Save Settings" hotkey so you can save settings from the menu without having to restart RA and without having to navigate to "Save Current Configuration".  Crashing causes RA to forget all settings changes.  Crashing happens extremely often still; surely not just to me and everyone I know who has tried RA in many different configurations.

I've found that RA crashes so often on so many different computers and circumstances that I have learned to close and reopen it after every few settings changes.  The other day, I configured an N64 controller at least 4 times in a row before the settings stuck.  It was embarrassing because I was trying to show my brother how good RA could be, but it ended up mainly highlighting how often it forgets all the settings changes due to crashing under unexpected circumstances.

Alternatively, I want an option that lets you save the settings every time a setting is changed.  This could save settings to a temporary config file so it doesn't overwrite your "working" settings if you encounter a crash.  This would also help to reproduce crashes.

Really, the preferable solution is to have RA never crash, but that is unrealistic considering how many different situations cause crashes.

Another alternative is to have RA save settings when it crashes, whether to a temporary config file or the main one.

**Comment by Monroe88** [comment]
Probably what should fix this is a config autosave interval similar to the existing SRAM autosave interval feature. Not sure if config saving can be done like that though, since it would need to be non-blocking.

**Comment by AlexFolland** [comment]
My brother wrote this after I linked him to this issue ticket:

[10:27 AM] Eric: @Lex "Alternatively, I want an option that lets you save the settings every time a setting is changed"  I would think this is all you need.  don't even need two sets of settings.  if people really want sets of settings, they can copy the config file to a backup
[10:28 AM] Eric: they're presenting a UI that's like PS3 or whatever, meaning it's supposed to be simple.  having to save settings doesn't line up with that design(edited)

I agree with him completely.  Since it is meant to be simple, it should just save immediately, and if you want a backup, you can save one manually.  There should be no reason for RA to ever forget your settings, considering its design direction.

**Comment by hizzlekizzle** [comment]
As discussed in IRC, I echo Monroe88 in voting for an autosave interval. This avoids having to track the state of the config (i.e., when an option has changed and needs saving), avoids I/O issues when cycling through option states and avoids broken configs if a bad/incompatible option is selected (assuming it crashes within the interval).

**Comment by fr500** [comment]
What about overrides? when overrides are active should we save the override automatically too?
Or should that be a manual process?

Should I still block from saving to the main config when overrides are active?
There's a lot of stuff to consider.

**Comment by hizzlekizzle** [comment]
RetroArch itself doesn't crash that often just cycling through options, so I'm assuming the issue happens like this: you change a bunch of options, fire up a core/content to test them, crash, you lose it all.

Assuming that workflow, perhaps the best thing would be to flush to file before trying to load content (i.e., the thing that's likely causing the crashes in the first place) and not worry about intervals or state-checking, etc.

In this case, I would assume the overlay-saving would still be manual and saving to the main config would still be blocked.

**Comment by AlexFolland** [comment]
Don't assume that.  You can change many settings while the core is still running.  In my case, that's when I change most settings, so I can test the changes immediately.

**Comment by fr500** [comment]
Tell me one setting that causes an immediate crash please (seriously, I
want to test)

**Comment by AlexFolland** [comment]
Have state thumbnails enabled and save state from the menu with the ParaLLEl N64 core, then go back into the menu and try to do anything.

**Comment by fr500** [comment]
That's not a setting though.

**Comment by AlexFolland** [comment]
It causes a crash though, and can happen after having changed settings while the core is running.  How is this relevant anyway?

**Comment by fr500** [comment]
Of course it's relevant, we're trying to determine a good moment to save settings.
You can't save before a crash (because a crash means something unexepected happend and the program doesn't know how to handle it, so you can't really do anything graceful before it bombs)

To save on every change would mean to go through every menu callback and add a few lines to trigger the save.

And again.. what about overrides? if overrides are loaded do we want to save on every change too?

And what if you're just trying out stuff, I reckon config save on exit is perfectly sensible for a fair amount of people.

**Comment by AlexFolland** [comment]
It would be if RA didn't crash all the time.

**Comment by fr500** [comment]
If it's crashing all the time your should then report all the instances that cause retroarch to crash, not just pile a hack on top of that.

I don't say saving more frequently is necessarily bad but what you're trying to do here is sidestepping the reality.

**Comment by AlexFolland** [comment]
This has been a problem for so many years and I've reported so many different crashes that it's obviously entirely unrealistic to expect every crash to be fixed.  New ones are added all the time.

**Comment by fr500** [comment]
Ok

**Comment by AlexFolland** [comment]
Regarding doing something before a crash obliterates data, I think you can.  That's what the try-finally statement is for in other languages like D.  Theoretically, you can simulate it in C too, or if using a Microsoft compiler, it is usable directly as an extension because C coders wanted it: https://msdn.microsoft.com/en-us/library/yb3kz605.aspx

I think in theory, try-finally (or its equivalent) can be used to guarantee that RA saves settings before the crash obliterates the settings changes.

I've used try-finally in D and it was quite useful for preventing crashes from ruining everything.  Of course the crashes aren't prevented so they still need to be fixed, but at least they wouldn't cause you to lose all your settings changes.

**Comment by sonninnos** [comment]
This would be a pointless band-aid regardless.

**Comment by AlexFolland** [comment]
It would obviously not be pointless.  The frequency at which RA settings get discarded is unlike any other tool in the modern desktop.  Everything else simply saves your session either immediately when changes are made, or periodically.  RA lets everything get thrown out unless you manually save it.  This is one of the only huge issues RA still has.
