### ISSUE TITLE
(Windows) Game Focus toggle can't be untoggled.

### ISSUE THREAD

**Issue by Monroe88** [libretro/RetroArch#4283]
Pressing Game Focus toggle hotkey (Scroll Lock) will successfully disable all hotkey and RetroPad keybinds, but pressing Scroll Lock again doesn't toggle Game Focus off to allow keyboard input to the frontend. This will lock you out of the menu if you only have a keyboard, requiring you to either use a gamepad to access the menu or press ALT+F4 to close RA.

Tested with Windows 7 x64 with both the dinput and sdl2 input drivers, using a 64-bit build of latest git master.

**Comment by twinaphex** [comment]
I cannot reproduce this issue on Linux.

**Comment by fr500** [comment]
@Monroe88 maybe you have a hotkey enable button set too?

**Comment by Monroe88** [comment]
I don't have any hotkeys defined in my config, so they are all default. "Enable Hotkey" is not set to anything. Mapping the enable hotkey to anything doesn't make a difference, the game focus hotkey does not toggle off even if you hold the enable hotkey while pressing scroll lock.

https://hastebin.com/uxehovegil.cfg

**Comment by Orangestar12** [comment]
This problem still affects Windows, at least it does for me on Windows 10 64 bit.

**Comment by Boviligg** [comment]
Same problem here. Win7 x64. RA 1.5.0 2017-03-29

**Comment by Gpinchon** [comment]
Same issue with latest version, once toogled Game Focus won't turn off because the emulator stops listening to hotkeys...

**Comment by hyarsan** [comment]
Yeah, it can't be toggled so I have to use task manager.

**Comment by bparker06** [comment]
Confirmed on Windows 10 here with 1.7.1

**Comment by fragmental** [comment]
confirmed 1.7.2 on windows 10

**Comment by pucechan** [comment]
This behaviour is still occurring on _RetroArch 1.7.3_ running on _Win10 x64_. Once toggled I'm unable to re-toggle Game Focus whether there is an Enable Hotkeys bind bound or not.

**Comment by twinaphex** [comment]
I think I fixed this now for Windows with the DirectInput and Winraw input drivers (only two input drivers for Windows) -

https://github.com/libretro/RetroArch/issues/6993
