### ISSUE TITLE
add an option to switch display automaticaly to 50hz refresh rate in Retroarch when running PAL games

### ISSUE THREAD

**Issue by bigboo3000** [libretro/RetroArch#4284]
Hi

Would it be possible to add an option to switch display to 50hz when running PAL games?

I tried some PAL games with genesis plus GX and snes9x, they run correctly at 50fps in the emulator but the refresh rate of my monitor is still at 60hz.

I have a pc with windows 10 and AMD video card with vulkan.

**Comment by hizzlekizzle** [comment]
I don't think this is going to happen automatically any time soon but you should be able to use config overrides with the video_refresh_rate option to force it as long as your monitor will accept a 50 hz rate (that is, RetroArch will not create modelines that don't already exist).

**Comment by shakkalakka** [comment]
such a feature would be great. playing "optimized" PAL-games without stuttering, glittches or speed-up would be a great thing for PAL-Users.

**Comment by fr500** [comment]
you could try this:
create a resolution in your control panel (nvidia or whatever) and reduce vertical res by 4, I had to do this for crysis 1 for some reason

So create a custom res, like 1920x1074 and specify 50hz refresh rate, if that works then it should be doable to set video_fullscreen_x and video_fullscreen_y to 1920x1080, it should switch automatically.

**Comment by eddlang** [comment]
This option would really be helpful.

**Comment by eugene-s-nesdev** [comment]
Can retroarch automatically change the refresh rate depending on NTSC/PAL region in 2021?

True reason of this topic/request - ability to smooth (no-tearing) scroll, which is avaliable ONLY
when physical refresh rate corresponding with emulator output.

When emulating NTSC 60Hz mode - preferred physical refresh rate = 60Hz or multiple value (e.g. 120Hz) 
When emulating PAL/Dendy 50Hz mode - preferred physical refresh rate = 50Hz or multiple value (e.g. 100Hz)
This settings + vsync gives true smooth scrolling.

Nestopia-win32 had "auto" refresh rate function in fullscreen depending of region.
For NTSC emulator try to set 60 or 120 Hz, prefer higher value if hardware supported it.
For PAL/Dendy emulator try to set 50 or 100 Hz, prefer higher value if hardware supported it:

https://user-images.githubusercontent.com/13199529/120906909-03f0ab00-c666-11eb-889c-491c34114e47.png

This feature was added to puNES/QT (linux and winD3D/OpenGL) in lastest commits:
[punesemu/puNES@7666b72](https://github.com/punesemu/puNES/commit/7666b7260732da3b3cc6158a343eb8b3e958e3ef)
[punesemu/puNES@232380e](https://github.com/punesemu/puNES/commit/232380ece1723497493d7be097a632b8616a5ca2)
[punesemu/puNES@4ee0839](https://github.com/punesemu/puNES/commit/4ee0839ac83630b4b4398199d4799fd2c1216a93)

It have "Adapt Refresh Rate to the Region" checkbox:
For NTSC emulator try to set 60 or 120 Hz, prefer lower value if hardware supported it.
For PAL/Dendy emulator try to set 50 or 100 Hz, prefer lower value if hardware supported it.

https://user-images.githubusercontent.com/13199529/128414383-d4f43489-107b-41db-92f2-d9dcd33de33b.png

Also, it was added to Mesen fork by mkwong98:
https://github.com/mkwong98/Mesen/commit/708a13b1c7c48b89dd4e89352f13894db6913f34

https://user-images.githubusercontent.com/13199529/128203180-f8c4b3a9-4f0a-4be0-ba99-bb89027b79cd.png

It works very well.

**This feature will be very useful for all systems, not for NES-only.**

**Comment by BFG1992** [comment]
Also would benefit WonderSwan emulation, this system has a 75 Hz screen.

As someone who is forced to use 3 shortcuts with 3 different RetroArch configs for each case (NTSC, PAL and WS) i would really appreciate if someone would implement such option.

**Comment by hizzlekizzle** [comment]
If the modeline already exists on your system, you should only need to add video_refresh_rate = "50.000000" (or 75.0 or whatever) to a game/core override (or content directory override if all of your PAL games are in their own dir), and it should snap to that modeline as long as you're in exclusive fullscreen, I think.
