### ISSUE TITLE
List installed cores first under "Load Core"

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#4287]
Right now the "Load Core" menu is:

* "Download Core..."
* "Start Remote RetroPad"
* "Start Video Processor"
* Installed cores...

I believe the installed cores should come first and the other 3 items should follow (with Download Core being first among those items). This would be more user friendly as the Remote RetroPad and Video Processor (and Download Core) options will be used less frequently than loading an already installed core.

**Comment by sergiobenrocha2** [comment]
RA tends to have less frequently used options in evidency like #4089 and #4245
