### ISSUE TITLE
Android: RA doesn't load zipped roms immediately.

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/RetroArch#4291]
I was using the build 2016-11-27 and everything was ok. Yesterday I updated RA and cores and when I try to load some zipped ROM like KoF96 (NeoGeo) or MSH (CPS2), the retroarch show me the options to "Open Archive as Folder" or "Load Archive With Core". Both FBA and MAME cores have the same problem. 

Reverting to version 2016-11-27 fix the problem, even if I update the cores to the newest versions.

**Comment by retro-wertz** [comment]
if its neogeo-you probably are missing the neogeo bios rom, if its a cps2
rom, then you probably have missing sets(specically missing .key file from
cps2 which was added on fba v0.2.97.39

**Comment by ZacharyFoxx** [comment]
No, the sets are correct, because the games are loaded and run flawless. The same sets, with the build 2016-11-27, are simply loaded. In build 2016-12-19 (and any other from 12/15 to 12/20), I need choose "Load Archive With Core".

I downloaded the rims

**Comment by ZacharyFoxx** [comment]
Sorry, correcting my last paragraph: 

I downloaded the roms from planetemu.

**Comment by twinaphex** [comment]
Not a bug. Some stuff changed in Load Content and this was the end result.

**Comment by daubsi** [comment]
@ZacharyFoxx: I have the problem that libretro complains about missing key files for quite many cps2 roms (e.g. msh, mshvsf, mvsc, xmvsf, ...) Where can I find info about this or more important: where can I obtain the missing key file(s) from? Ty!

**Comment by fr500** [comment]
Please get this talk over to the forum this isn't the proper channel for this kind of discussion.
