### ISSUE TITLE
You should not be able to update the same file more than once at a time.

### ISSUE THREAD

**Issue by AaronBPaden** [libretro/RetroArch#4293]
Occasionally I will accidentally hit the button twice on the retroarch updater, at which point retroarch will gladly download the same update multiple times concurrently.

**Comment by AlexFolland** [comment]
It should just perform a hash comparison before downloading.

**Comment by fr500** [comment]
He doesn't mean not updating something that's up-to-date he means queuing many downloads of the same file concurrently

GIT is not meant for binaries.
The buildbot already provides the information to only update when there are actual updates. It's up to RA to do anything with it.

Example:
https://bot.libretro.com/nightly/android/latest/armeabi-v7a/.index-extended

**Comment by AlexFolland** [comment]
So this bug is what I thought, and RA needs to perform the hash comparison I was talking about.

**Comment by zoltanvb** [comment]
This was implemented in 2019:
https://github.com/libretro/RetroArch/commit/695749f155b97b2aa1527d81337a86865d18069b
