### ISSUE TITLE
Incompatible with tablets?

### ISSUE THREAD

**Issue by belldandu** [libretro/RetroArch#4294]
I tried installing this on my tablet the other day but google play said it was incompatible even though my tablet came out after my phone and is more powerful.

So what's the exact reason i cant use retroarch on my Samsung Galaxy Tab S2 but can on my Samsung Galaxy Note 5?

**Comment by fr500** [comment]
It shouldn't be the case... not sure why it's not allowed.

**Comment by Aaahh** [comment]
Checked on LG v500, no incompatible message.
Based off the manifest, the only thing I see that may throw an issue is 
`    <uses-feature android:glEsVersion="0x00020000" />
`meaning that your tablet does not have OpenGL ES 2
or 
`        android:minSdkVersion="9"
`meaning that your tablet isn't on 2.3 or higher

but it's obvious that both don't apply here. Last thing I can think of is that on Google console, that tablet was added to the exclude list. Just grab the apk and install it

**Comment by bparker06** [comment]
@belldandu Have you tried installing RetroArch through F-Droid?
