### ISSUE TITLE
Load Content Menu: Doesn't loading automaticly zipped ROMs

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/RetroArch#4299]
Before open the issue [#4291](https://github.com/libretro/RetroArch/issues/4291), about the "strange behavior" after the updates since 2016-12-15, I posted about this on FBA repository.
There, nobody told me which was about a change in Load Content menu, everybody told which was about some error or lost file on my sets.

So, I opened the issue here and the best answer about it was that is a change on "Load Content" menu?

Simply doesn't make sense which Retroarch doesn't load automatically zipped ROMs of Mame and FBA. These ROMs should be zipped, so the retroarch should be capable of load them without ask if it should "Open Archive as Folder" or "Load Archive With Core".

Probably, nobody asked about this change because most of users stay using the stable releases.
Load Content to

**Comment by fr500** [comment]
It has been like this for more than a year so I dunno what's the fuss.
It can't know it's a mame or fba rom, it only knows it's a zip so it asks you about what to do. Just do Load Archive with core.

**Comment by ZacharyFoxx** [comment]
Sorry, but it hasn´t been like this for more than a year, not to FBA and Mame ROMs/cores.

In fact, cores like snes9x or Picodrive only support *.sfc, *md, *bin files and if you try to load a zipped ROM with them you´ll have to choose between those options.

If you give a look on the wiki, to the Mame and FBA cores, is told which these cores support zip formats.

Furthermore, I have the build 2016-11-27 and with it, when I choose FBA core, I don´t need tell to retroarch to open the file with the core, it simply loads the rom.

One of the complains about the retroarch is the lack of tests between the versions, and when there is someone telling you about something which changed, which nobody knows what changed, looks like nobody care about because there is a kludge.

**Comment by fr500** [comment]
Then you need to be clearer with the process you're following
It's now clear to me that you're doing "Load Core" then "Load Content".

Not just "Load Content". Yes I agree if the core supports zip directly it should skip that step.

**Comment by ZacharyFoxx** [comment]
fr500, I agree with you.

I should been clearer about the description of problem, but the retroarch's staff could be more curious about the problems like: "Is it happening when you choose a core and try to load a ROM or when you choose directly the "Load Content" option?" 

So, being clear, the problem happens in this order:

1 - I choose the core FBA or MAME in "Load Core" option, not matter the version or kind of core (2012, 2003, etc);
2 - After, I try to load a rom in "Load Content" option, but instead of load the ROM, the retroarch show me the options "Open Archive as Folder" or "Load Archive With Core".

Thank You

**Comment by twinaphex** [comment]
I think this would only sow confusion.

What if I selected a core, then went to Load Content, selected an FBA ROM, but say its a CPS1 rom, that requires switching to the CPS1 FBA core for Wii, ditto with CPS2, etc.

Point is, this kind of automagic preference of 'you load the core, then it will use that core for all the games you try to load with it', this isn't going to be user-intuitive at all, and it will just lead to more confusion.

Honestly, you'll just have to put up with one more button press. Later on there could maybe be 'file associations' so that we could associate certain cores to certain games in the file browser, but that time is not now. Let's not make a huge freakout over one more button press here in the meanwhile, all the things you propose instead would hardly be improvements.

**Comment by ZacharyFoxx** [comment]
Sorry twinaphex but I can't agree with you because what you call of "automagic preference" was already implemented!

I am using the android's version, but I tested in Linux.

What I told is which before and until the build 2016-11-27, if I choose the FBA core and try to load a ROM of this core, like KoF96.zip, the retroarch will simply loads it. But now, if I try to do the same steps, the retroarch show me the options, what doesn't make any sense. 

If I choose the snes9x core and try to load a sfc ROM, the retroarch loads it. The same thing happens with other cores like picodrive/genesis-plus-gx and MD files, mupen64plus and n64 files, etc.

If the user choose a core is supposed which he knows what ROM he should load.

**Comment by twinaphex** [comment]
What doesn't make sense?

It shows 'Current core: your core' at the top, it couldn't be more convenient.

I consider this a non-issue to be very honest with you.
