### ISSUE TITLE
avcodec-57 and avformat-57 not found

### ISSUE THREAD

**Issue by alondero** [libretro/RetroArch#4303]
Looks like the latest build requires an updated version of ffmpeg which isn't bundled in with the latest nightly at the moment.

**Comment by hizzlekizzle** [comment]
Yeah, we moved to another buildbot and it has an updated toolchain, so we'll need to product a matching set of redist libs. We hope to have that available tonight or tomorrow.

**Comment by AlexFolland** [comment]
For now, the workaround is to download a recent "shared" build of ffmpeg from Zeranoe's website: https://ffmpeg.zeranoe.com/builds/ .  It has the latest avcodec-57.dll and avformat-57.dll built for you.  Put those files directly beside RA.

**Comment by fr500** [comment]
Fixed, for 64 bits at least.
