### ISSUE TITLE
Windows Cursor Not Hidden in Fullscreen Sometimes

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#4305]
If you start in fullscreen, hit F to go into a window, then hit F again the cursor is not hidden. Sometimes the cursor shows up even when launched directly into content from command line or even XMB. You have to press F11 to manually grab the cursor to hide it.

This happens with both windowed and exclusive fullscreen modes. Tested on Win10.

**Comment by AlexFolland** [comment]
Confirmed.

**Comment by Awakened0** [comment]
I'm using GL.

**Comment by Awakened0** [comment]
46d3f7983d8606a273c01a62e903542d13b68920 fixed this. Thanks @twinaphex!
