### ISSUE TITLE
crashes when switching window scale

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#4310]
with nothing loaded(no cores or games-official nightly dec 25 release-default config) RA crashes when switching different window scales

![switching window size crash](https://cloud.githubusercontent.com/assets/23315382/21469046/80c7d31a-ca71-11e6-865f-e586d3825efd.jpg)

APPCRASH shows different result everytime but the procedure to make ra crash is the same-this is happening a few commits already since november.

**Comment by fr500** [comment]
it doesn't crash for me at least. I tried from 1x to 9x

**Comment by fr500** [comment]
You could try using dr. mingw to get some stack data
https://github.com/jrfonseca/drmingw

**Comment by retro-wertz** [comment]
delete retroarch.cfg, run retroarch. disable menu pipeline. exit retroarch.
run again RA, switch to different window scale (x1, x2, x3, x2, x1
back-and-forth) at least this is fastest way for me to make it crash.

btw, this is x86-64. will try to use drmingw.

**Comment by fr500** [comment]
I moved it up and down 200 times, no crashes here

**Comment by retro-wertz** [comment]
retroarch.exe - http://pastebin.com/gKnQm4Zm
retroarch_debug.exe http://pastebin.com/MCfFLNiK

**Comment by twinaphex** [comment]
I was able to trigger it a couple of times, but other times it doesn't happen at all.

I can't get a stack trace of this either, which is annoying.

**Comment by fr500** [comment]
is this still happening?

**Comment by retro-wertz** [comment]
i am not able to reproduce this, though i have since replaced my dx10 gpu to dx11 capable (onboard intel hd only)

**Comment by MarcoEstevez** [comment]
I can only reproduce it with vulkan And being under playlist with boxarts

**Comment by jpmac26** [comment]
I am having this issue on stable 1.6.9 (and the 2017-12-06 nightly build) for x86_64, using the Vulkan video driver, and I'm also sometimes getting a crash when toggling the "Integer Scale" video option or resizing the RetroArch window, however I cannot seem to reproduce them reliably; it seems to happen at random. None of these issues seem to occur on the "gl" driver, so I think it is possibly an issue with the Vulkan driver specifically.

**Comment by twinaphex** [comment]
@jpmac26 Which OS is this?

**Comment by jpmac26** [comment]
@twinaphex Windows 10 Pro 64-bit, latest updates. My GPU is a GTX 960 with the latest Nvidia drivers.
