### ISSUE TITLE
Wireless Xbox 360 controller not working in menu and games

### ISSUE THREAD

**Issue by tabnk** [libretro/RetroArch#4311]
Wireless Xbox controller not working in menu and games

Tested on build f0a04fd.

**Comment by fr500** [comment]
on.... windows? linux? osx? android?

**Comment by tabnk** [comment]
Windows 10 :)

**Comment by Ryunam** [comment]
I confirm I am experiencing the same issue with an Xbox One Elite Controller connected through the official wireless adapter on Windows 10. 
To be more specific, the controller does work once you manually assign the bindings. When you first start RA, a message appears stating that the controller is connected but not configured, so I think the problem has to do with the autoconfig.

**Comment by hizzlekizzle** [comment]
Can one of you create an autoconfig and paste it here (or just compare it with the existing one from https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/xinput/Xbox%20One%20Controller%20for%20Windows.cfg yourself) to see if something has changed?

**Comment by Kivutar** [comment]
Look like somebody removed the cfg from the repo?

**Comment by fr500** [comment]
XINPUT pads don't need a config at all... (in windows)
I just tried with my X360 pad, XBONE elite (wireless) my DS3 (SCP toolkit)
and all worked with no files.

**Comment by fr500** [comment]
@Ryunam ok I take that back, the XBOX One controllers need a profile in fact but there is one already. Most likely you need to update your autoconf profiles

I just sent a fix too https://github.com/libretro/RetroArch/pull/4318

**Comment by tabnk** [comment]
Nice, it fixed
