### ISSUE TITLE
A question about core (pcsx) and Jailbreak iOS 10.1.1

### ISSUE THREAD

**Issue by iOS4all** [libretro/RetroArch#4322]
I have an iPad air and when I want to select pcsx rearmed dynarec (not Interperter) it crashes immediately. So the latest jailbreak comes with a fully KPP bypass (looks like  the same way of TaiG jailbreak)
Anyway my question is. Can we use the dynarec version of Pcsx again without any crashes?
Because I remember whe i was on ios 8 it was two different kind of jailbreak. One from Pangu and other from TaiG. First I did jailbreak from TaiG but pcsx always crashes. Someone told me to restore it and jailbreak it again from TaiG to solve crash issue. And this is was a true when I done from jailbreaking from TaiG it never crashes anymore.
This is because of different kinds of jailbreaks Pangu always come with broken kernel unlike TaiG always patch kernel in order to could use JIT officially.

So my question is can we could use Pcsx rearmed with latest jailbreak after getting a full KPP bypass?
Thanks

**Comment by hizzlekizzle** [comment]
I think there's also a problem of some memory location stuff getting moved.

**Comment by Arnochocobo** [comment]
iOS 1.0 ? We are at iOS 10.2 now... You should update.

**Comment by iOS4all** [comment]
Oh sorry I edited the title. anyway I mean 10.1.1
If someone jailbroken his devices on iOS 10.1.1 should tell us if pcsx dynarec works or just crashes.
Because as I said this jailbreak is fully KPP bypass so I guess it should work functionality.
It's same jailbreak of TaiG (I mean it's patch the kernel in order to use JIT officially).

**Comment by Aaahh** [comment]
if it is crashing for you get a log, i'm unaware of how to get one without using cydia impactor and "watch device" under one of the menus

**Comment by iOS4all** [comment]
I have iPhone 7 plus iOS 10.1.1 jailbroken.
I can't play anything because recent version is disappear (I mean not showing in homescreen) and the version before that is showing but can't play anything because it's not detecting cores only download cores but not for select them in order to play.
Any help please?

**Comment by hizzlekizzle** [comment]
github issues shouldn't be used for tech support. Go to the forum and you'll find several threads about compiling/running on ios 10. The user 'incognit' is very helpful on ios issues.
