### ISSUE TITLE
[PLAYLISY]stuck at playlist > Information...

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#4330]
stuck at information page when going to playlist > information when using playlist(like custom playlists) that has the 6th line(the one that has the .lpl) points to a non-existing or no equivalent rdb file.
![untitled](https://cloud.githubusercontent.com/assets/23315382/21522274/10d1a682-cd3f-11e6-82f0-4fc6012a6471.jpg)

example playlist format:
> G:\EMULATORS\ConsoleISO\Psx\Final Fantasy Chronicles [Chrono Trigger Disc] [U] [SLUS-01363]\Final Fantasy Chronicles - Chrono Trigger Disc [SLUS-01363] [IOL.com].ccd
> Final Fantasy Chronicles - Chrono Trigger Disc [SLUS-01363]
> DETECT
> DETECT
> 00000000|crc
> BLANK.lpl

**Comment by Ryunam** [comment]
This only happens when the 6th line, indicating the respective playlist file, points to a non-existant .lpl file in the chosen path. 
If the line is left entirely blank, the UI doesn't hang and instead displays a "No playlist entries available" message upon selecting 'Information'.

**Comment by fr500** [comment]
is this fixed?

**Comment by Ryunam** [comment]
Yeah, it should not come up anymore. With PR #4343 I made it so that the "Information" option only shows up when that playlist entry points to an existing database.

**Comment by retro-wertz** [comment]
yes, this should be a problem anymore...
