### ISSUE TITLE
Allow a device to be both a Gamepad AND mouse (eg, Wiimote, PS4 DualShock 4)

### ISSUE THREAD

**Issue by dankcushions** [libretro/RetroArch#4333]
I'm not sure if this is a purely UDEV + linux issue, but currently there seems to be a limitation where a device cannot be both a gamepad AND a mouse. For example, a wiimote is able to function as a RETRO_DEVICE_JOYPAD, but RETRO_DEVICE_MOUSE (or _POINTER) will not be updated with information, despite it updating /dev/input/mouse0 correctly (and useable in other applications).

The same with DualShock 4 which has a trackpad.

My guess is that when enumerating devices, retroarch counts registers these as a RETRO_DEVICE_JOYPAD and then moves on to the next device, when perhaps it should loop over and register as many RETRO_DEVICE_'s as udev permits for that bit of hardware.

I guess a change would be needed somewhere in `/input/drivers/udev_input.c` - will experiment with my DS4 but if anyone has any suggestions/warnings then please let me know :)

**Comment by dankcushions** [comment]
I have to correct myself here: in the current latest kernel the dualshock 4 is only one device in linux. the trackpad is reported, but only as an axis of the controller. however, in future kernels (4.10) it WILL be a separate device: https://github.com/torvalds/linux/commits/7ae123edd37a47e178eb9a6631fe4a7108262c10/drivers/hid/hid-sony.c

What I really need is someone with a wiimote and sensorbar to confirm what happens in linux + RA (the various test cores are useful here), as apparently I can't fully recreate this issue at my end, and am relying on what users are telling me :(

I may just buy a secondhand wiimote!

**Comment by orbea** [comment]
I have linux, two wiimotes and a dolphinbar which works with dolphin-emu I can test with. Can you spell out what needs to be done to reproduce and test this?

**Comment by dankcushions** [comment]
@orbea perfect, thanks! i think for the initial test:
1. connect 1 wiimote and your dolphin bar
2. configure wiimote as a retroarch controller via the usual way (please use udev as your input driver
3. load up the libretro-test core (it's in https://github.com/libretro/libretro-samples/tree/master/tests/test  but don't seem to be on the buildbot anymore? hmm...)
4. turn on logging (settings > logging > logging verbosity ON, debug panel ON)
6. press the dpad whilst wiggling the wiimote
7. paste log here

I'm hoping it displays mouse (or pointer) data from the wiimote AND data from the joypad functions, but anecdotally apparently it only does the latter.

**Comment by orbea** [comment]
`RetroArch-2017.01.03_ef0b15f3f_master-x86_64-1_git`

One problem RetroArch doesn't recognize my wiimotes as gamepads in any of the modes, I am using udev for both the input and joypad drivers and confirmed that dolphin-emu still recognizes them. It does however let me use the wiimote to control the mouse cursor in the mouse modes...

**Comment by dankcushions** [comment]
@orbea. hmm, are you not even able to create a new autoconfig for them? i see there are a couple already here that might work, if the vid/hid matches: https://github.com/libretro/retroarch-joypad-autoconfig/tree/master/udev

**Comment by orbea** [comment]
Nope, RA might not work with the dolphinbar yet? Here is some usb information.
```
Bus 008 Device 022: ID 057e:0306 Nintendo Co., Ltd Wii Remote Controller RVL-00
```
```
T:  Bus=08 Lev=02 Prnt=02 Port=02 Cnt=03 Dev#= 22 Spd=12  MxCh= 0
D:  Ver= 2.00 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=057e ProdID=0306 Rev=01.00
S:  Manufacturer=HJZ
S:  Product=Mayflash Wiimote PC Adapter
C:  #Ifs= 4 Cfg#= 1 Atr=80 MxPwr=500mA
I:  If#= 0 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
I:  If#= 1 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
I:  If#= 2 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
I:  If#= 3 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbhid
```

**Comment by dankcushions** [comment]
retroarch should only need the hardware to be understood by linux/udev.

does it return anything in jstest? https://linux.die.net/man/1/jstest

**Comment by orbea** [comment]
Neither sdl1-jstest or sdl2-jstest lists it... I guess there must be something special about how dolphin implemented it?

**Comment by dankcushions** [comment]
There's some stuff here: https://github.com/libretro/RetroArch/issues/266

and then https://github.com/libretro/RetroArch/pull/838

and then the trail goes cold.

I'm not sure if wiimotes are supported in retroarch or what, but my original premise is almost certainly wrong :( Perhaps  https://github.com/libretro/RetroArch/issues/266 should be re-opened but I guess I should close this.
