### ISSUE TITLE
Add OSD Message Verbosity Option

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#4341]
This is something that was discussed on the forums here: https://libretro.com/forums/showthread.php?t=7888

I personally turn off the OSD entirely to hide them, but ideally I'd still like to see user triggered messages like "saved state". With the OSD completely off I get no feedback on stuff like that.

I don't think it'd be too hard to categorize the messages that appear at startup. I can think of: Controller Configured (when autoconfig is enabled), Overrides Loaded, and Remaps Loaded.

**Comment by fr500** [comment]
I'd prefer to add a setting to every single OSD string than the hack proposed on the forum.

**Comment by afiction** [comment]
I would love this feature!

**Comment by RobLoach** [comment]
The "right" way to do this would be to tweak the message verbosity levels to either show/hide depending on their importance.

Suggest closing it, as these have been changed quite a bit over the past year.

**Comment by Awakened0** [comment]
I don't see any options as of the latest nightly to change message verbosity. I still see "Configuration Override Loaded" for most cores at startup. Mesen shows the name of the game loaded at startup instead even though I have an override for that core. Maybe I should change the issue title to something like "Add OSD Message Verbosity Option" instead?

**Comment by Awakened0** [comment]
Now I can disable all the notifications I wanted to thanks to this: https://github.com/libretro/RetroArch/pull/11033

Thanks @jdgleaver !
