### ISSUE TITLE
RGB issue with assets and shaders borders

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#4344]
[Got the color inverted with handled borders.](http://postimg.org/image/l7041gazh/)
It's the same with cg or glsl.
Happening with nightly compiled just now on win7 x64 nvidia gtx 770.

Didn't happen on 12/21 nightly.

Perhaps related to @loganmc10 recent modifications?

**Comment by loganmc10** [comment]
You'll have to forgive me, what's wrong with that image? And what is the name of the shader you're having an issue with?

**Comment by Tatsuya79** [comment]
[It should be like this (RGB logo and blue button on the Game Gear).](http://postimg.org/image/hqhxpy57r/)

It's a shader located in shaders_*\handheld\console-border\gg-4x.*

I'm calling to you as I saw you tried to fix some RGB/BGR color problems.

**Comment by Ryunam** [comment]
I confirm I'm experiencing the same problem with the visualization of some visual assets, namely some icons in the XMB UI which currently exhibit inverted blue and red colors.

Before (build from 29/12 - proper colors for the Famicom icons): http://imgur.com/a/rgTgA
After (build from 31/12 - inverted colors): http://imgur.com/a/Ao4R4

**Comment by bparker06** [comment]
@Ryunam can you tell us what git version your build has? I'm not able to reproduce this with the latest code, at least on Linux,

**Comment by bparker06** [comment]
Apparently this is a Windows-specific issue, I am able to reproduce it there now with both Intel and NVIDIA GPUs.

**Comment by Ryunam** [comment]
Yes, I'm currently using the latest code on Windows 10 x64 with an NVIDIA GPU. I can try testing the same git version on Mac OS later.

**Comment by loganmc10** [comment]
K I someone able to bisect it? I don't have access to a Windows machine, could it also be this commit? https://github.com/libretro/RetroArch/commit/9657bbd99839d30933d24e400db129a1b2e2b56d

@Ryunam what git version on the 29th was working for you?

**Comment by loganmc10** [comment]
I don't think the commits I made on the 30th should have changed anything except the GLES code, shouldn't have affected Windows

**Comment by sergiobenrocha2** [comment]
It's happening in my Odroid U3 board too (GLES)

**Comment by bparker06** [comment]
@loganmc10 According to my bisect, 9657bbd99839d30933d24e400db129a1b2e2b56d is the first bad commit.

**Comment by loganmc10** [comment]
@twinaphex see @bparker06's comment

**Comment by twinaphex** [comment]
I'll need @bparker06 to properly refactor this, I haven't been able to reproduce this issue on my end.

**Comment by Ryunam** [comment]
With the latest code on my Windows 10 x64 build, colors appear to be rendered correctly with respect to UI assets.

**Comment by Tatsuya79** [comment]
No difference here (win7 x64).
Shaders and some assets are still inverted.
I think some assets aren't concerned, did you test the exact same ones?

**Comment by Ryunam** [comment]
Yes, I compiled the newest build about a hour ago and checked with the same assets (Famicom icons) that were previously used as a test. They were previously blue; now they are shown in their proper red color.

**Comment by Tatsuya79** [comment]
Indeed there's a difference with assets, I can see the wonderswan FlatUI icons are back to blue instead of orange now that I've compiled the latest exe.
[It's probably because of this commit.](https://github.com/libretro/RetroArch/commit/1fa08e327bff8c6b0e1fc5dbd11b8aea233a80ed)

Border shaders are still inverted.

**Comment by sergiobenrocha2** [comment]
The assets are working fine now on ARM

**Comment by Tatsuya79** [comment]
So, does windows needs some kind of flag to tell the driver it supports RGBA for textures in shaders?
(...if I word it right)

**Comment by Tatsuya79** [comment]
Thanks for fixing it! Working good here for shaders now.
