### ISSUE TITLE
Question about ppsspp core.

### ISSUE THREAD

**Issue by iOS4all** [libretro/RetroArch#4346]
Hi there. well I just want to ask you guys how to get ppsspp core on jailbroken iOS devices please?
Thanks.

**Comment by hizzlekizzle** [comment]
Looks like it doesn't build properly on iOS. I would try standalone instead.

**Comment by iOS4all** [comment]
@hizzlekizzle thank you for replying. The problem with the standalone is contained the ugliest issue.
The issue you'll notice a micro stutter every 3-4 seconds on all games whatever your device is.

**Comment by twinaphex** [comment]
Yeah, that's common with many standalone emulators, that's one of RetroArch's key features that it prevents this.

**Comment by iOS4all** [comment]
@twinaphex thank you for come here and reply. I'm really appreciated. I really like your project so much. Because as you the amazing feature for this project is (All in one) you can't imagine how ppsspp standalone is bad because of some issues in there.

Other thing: My device is iPhone 7 plus jailbroken on 10.1.1 and I tried to run retroarch but no luck always said no core. any idea please?

Finally I saw your tweet on Twitter and said you'll bring dolphin core to retroarch as well. But first you have to update retroarch to v1.4.0. If that's true it'll be amazing. Specially when it could be ported to mobile devices like iOS and android.

Again thank you so much for your hard work. We really appreciated a lot.

**Comment by fr500** [comment]
Close this please.
And this kind of discussion is better suited to the forum.

**Comment by iOS4all** [comment]
Ok my bro. It's my pleasure.
