### ISSUE TITLE
Issue with FBA & PS3 controller

### ISSUE THREAD

**Issue by RubbishSports** [libretro/RetroArch#4348]
Recently got a Raspberry Pi 3 and have installed Retropie 4.1.8.  

With most roms everything is working fine however when I try to run some roms in the pifba emulator my wireless PS3 controller appears to stop working and none of the buttons work so I have to restart the Pi by pulling the plug - which I'm sure can corrupt the SD Card :(

I was thinking this might have to do with the select/coin insert issue which I have read about in some other pages on this site - but not 100% sure.

Do I need to change the hotkey used on retropie like other pages suggest?  I was thinking of changing the hotkey button to my left bottom trigger - will that fix it?

I'm a bit of a noob so have confused myself :(

Which config file do I put the **input_enable_hotkey_btn = "8"** command?

That is if that is the issue and not something else!

**Comment by hizzlekizzle** [comment]
PiFBA isn't one of our projects. You'll probably have better luck asking on the Retropie forums.
