### ISSUE TITLE
(Regression) Save Autoconfig no longer saves the PID/VID.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4349]
OS: `Slackware64-current`
`RetroArch-2016.12.31_bcbb06c89_master-x86_64-1_git`

Save Autoconfig will no longer save the PID/VID to the `.cfg` file, this started with the below commit.
```
209305f9440b84ff9c30b97efdc5c4ad27890a0f is the first bad commit
commit 209305f9440b84ff9c30b97efdc5c4ad27890a0f
Author: twinaphex <libretro@gmail.com>
Date:   Fri Dec 16 14:02:11 2016 +0100

    Connect task now sets PID/VID too

:040000 040000 dc8a38f86dfd07201ba71b7bc423ef81c2d71a94 56ca12943f3e0984e5e083e115479aa3e917354f M	input
:040000 040000 33c45889d0618195e5fb8b6bb13622927e099819 a3bbda49d2e02e9d42ce6e43cf74deb54667660a M	tasks
```
209305f9440b84ff9c30b97efdc5c4ad27890a0f

**Comment by twinaphex** [comment]
I can't reproduce this. 

I select 'Save Autoconfig', and it saves this autoconfig file (Sony PLAYSTATION(R)3 Controller.cfg) with the following contents in it -

input_driver = "udev"
input_device = "Sony PLAYSTATION(R)3 Controller"
input_vendor_id = "1356"
input_product_id = "616"

**Comment by orbea** [comment]
With a fresh config I get.

`udev/.cfg`
```
input_driver = "udev"
input_device = ""
```
The correct device name is HORIPAD ONE.

So I tried this again with what I think is the same PS3 controller you are using and got the same result. I'm not sure why you can't reproduce it.

udev/.cfg
```
input_driver = "udev"
input_device = ""
```

**Comment by fr500** [comment]
@twinaphex are you certain that that file wasn't there already?
With that said, it saved correctly for me in windows.

**Comment by twinaphex** [comment]
No, the file wasn't already there. It was generated on the fly once I pressed 'Save Autoconfig'.

**Comment by fr500** [comment]
Actually the issue happens for me too with the dinput driver
No VID, No PID, no name, and no filename.

**Comment by fr500** [comment]
@orbea are you sure that is the first bad commit? I built c3a9ade0511c2043b2b680479ac613444491f7ac that's the parent of that one and the issue is there too

**Comment by fr500** [comment]
@twinaphex  @orbea  it only happens when a device fails to autoconfigure.
Another hint, the User 1 device index is NA when this started happening. It was the actual gamepad name before.

**Comment by orbea** [comment]
I tested the bisect manually before making this issue report, but I retested it again and found the same results. That was the commit that introduced the missing VID/PID issue for me with udev at least.

Commit 209305f94
```
input_driver = "udev"
input_device = ""
```
Commit c3a9ade05
```
input_driver = "udev"
input_device = ""
input_vendor_id = "3853"
input_product_id = "103"
```

**Comment by orbea** [comment]
@fr500 Yea, the missing device name happened earlier and that may be connected. I bisected that issue here.

https://github.com/libretro/RetroArch/issues/4345

**Comment by fr500** [comment]
we should combine these two instead since they are closely related.

**Comment by fr500** [comment]
Both things were fine before https://github.com/libretro/RetroArch/commit/d9def056e74a9830c1a9d934411467f275756a67

**Comment by fr500** [comment]
You're right, basically it started on d9def056e74a9830c1a9d934411467f275756a67 (name got f'ed up) and got worse in 209305f9440b84ff9c30b97efdc5c4ad27890a0f

**Comment by orbea** [comment]
I'm fine with combining them, I initially separated them because I was not sure if they were the same given different commits introduced the behavior.

Commit d9def05 has the VID/PID for me, but no device index as the bisect in the other issue shows.

**Comment by fr500** [comment]
as far as I can understand d9def056e74a9830c1a9d934411467f275756a67 is doing everything wrong. It's changing the name filling process to the autoconf task, when it does in fact need to get the name from the driver.

Same for 209305f9440b84ff9c30b97efdc5c4ad27890a0f, it's trying to fill the info from the wrong side of the process

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/commit/03818dc78057805ae60b2b9f30ca858ee255f9c4 fixes both issues for me

**Comment by orbea** [comment]
Same here, thanks! I will close this.
