### ISSUE TITLE
(Regression) OSD no longer reports if retropad is not configured.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4350]
OS: `Slackware64-current`
`RetroArch-2016.12.31_bcbb06c89_master-x86_64-1_git`

The RetroArch osd will no longer report if retropad is not configured, but it will still do so if retropad is configured. This started with the below commit.

```
d3470637ad7b89f0948b9a1eede7ccf3e3e5d2ae is the first bad commit
commit d3470637ad7b89f0948b9a1eede7ccf3e3e5d2ae
Author: twinaphex <libretro@gmail.com>
Date:   Sat Dec 31 07:54:38 2016 +0100

    Add max_users param to autoconfig_params_t

:040000 040000 96e2bfae412143e6f8832527f48f6efc6e6b51fc 314492add363131658eb0eafe594f0d9b095e3ff M	tasks
```
d3470637ad7b89f0948b9a1eede7ccf3e3e5d2ae

**Comment by fr500** [comment]
It will also only show message for one pad, not all of them.

**Comment by twinaphex** [comment]
I forgot to set this -

https://github.com/libretro/RetroArch/commit/824ba64daad2e02547d908e87fc0c343f5c5c76a

See if this fixes anything.

**Comment by orbea** [comment]
This one is fixed for me so I will close this issue, thanks!
