### ISSUE TITLE
(Android) Snes9x save states not loading MSU-1 playback state

### ISSUE THREAD

**Issue by qwertymodo** [libretro/RetroArch#4351]
On android, loading a new msu-1 game and immediately loading a save state results in no audio playback.

Steps to reproduce:
*Load MSU-1 game
*Save state
*Exit retroarch
*Open retroarch
*Load recent>(load game)
*Load state

**Comment by Alcaro** [comment]
[Dupe issue, wrong repo](https://github.com/libretro/snes9x/issues/30)
