### ISSUE TITLE
Accessibility suggestion

### ISSUE THREAD

**Issue by lonewolvf** [libretro/RetroArch#4352]
Is there a way to slow down game speed?  There are games that I would love to play but I am unable to because they're too fast paced (I'm disabled).  If you can slow down a game, could you add a percentage slider?  What would also be great to have is a keyboard hotkey that toggles between 2 speeds.  It wouldn't just be between normal and a slower speed, but also a slow and slower speed.

Thank you,
Michael

**Comment by fr500** [comment]
currently there is a hotkey but not a way to run slower altogether

**Comment by orbea** [comment]
visualboyadvance and the vbam standalone have a feature to decrease or increase the throttle by a percentage. Increasing the speed in some old and really slow games can be a lot of fun and it would also probably work for @lonewolvf . Maybe this could eventually be implemented in RetroArch / libretro?

**Comment by fr500** [comment]
This is valid, but a newer issue asks for the same, closing this one, I'll copy @lonewolvf's request to the thread so his reasons are not lost.
