### ISSUE TITLE
(Regression) OSD only reports one gamepad

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4353]
OS: `Slackware64-current`
`RetroArch-2017.01.02_824ba64da_master-x86_64-1_git`

The RetroArch OSD will only report one gamepad connected and not all of them. This was noticed in by @fr500 in issue https://github.com/libretro/RetroArch/issues/4350.

This behavior was introduced in between commits 711e4ea and fdac55e, but it can not be bisected easily because of many commits in between which had another now fixed issue where gamepads would be stuck at 0% when configuring.
```
$ git bisect bad
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
24a689c27459fbb71fc2ca13627766a0c02fb26e
2cc4bef3aa42e4f99851e420fedaaaf2ef56491e
82bea3ba9fb7fdd9d03b17bf87610b749642e074
22e1854b8c5e5de29b0181287aae2ec843b1ecad
3db866e5dc7886fa129e52307cab518774dfc08a
0d79bc754c8d1410518aa5cc0ad58f70ac8a2a14
5fdb5b4dcf5bf3e0172ad5aecfcf42ccb322b03a
4a894afc573781f173e2514715a05fa12344a8d5
5e758208806041c6ea06c858d76e74b55d5d95c6
230d7105fd1f631e7d137c81ec7df61461fc32d0
6a2df4615b60f52929297824861b023a2dc9ca77
02c0e8013b7fe252f9f555d2f404a1703ab2c38c
305b2becbd6d9caff1ff2a014dd6ffa18b1447d8
4c41c7a3d0bee74a6f419d33981612297d9048d9
We cannot bisect more!
```

**Comment by orbea** [comment]
Apparently that other issue only happened if a gamepad was not configured, so I redid the bisect and came up with this commit.
```
305b2becbd6d9caff1ff2a014dd6ffa18b1447d8 is the first bad commit
commit 305b2becbd6d9caff1ff2a014dd6ffa18b1447d8
Author: twinaphex <libretro@gmail.com>
Date:   Thu Dec 1 22:16:06 2016 +0100

    input_autoconfigure_connect - now a task

:040000 040000 223ad51a9851a43578637b2b974e168a94d5c7ad 10ce1b35e82f6299be838f2c85f2e4dda6bba11b M	tasks
```
305b2becbd6d9caff1ff2a014dd6ffa18b1447d8

**Comment by twinaphex** [comment]
I think this commit should resolve this -

https://github.com/libretro/RetroArch/commit/89dcc9bf5feb8cc0aa354a41092060035e05f8d4

**Comment by orbea** [comment]
This is solved here, with both configured and non-configured gamepads. Thanks!
