### ISSUE TITLE
[x86] Noise in arcade games

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#4359]
I can hear a noise when playing arcade games (tested cps-2 and neo geo so far), using MAME 2014 and FBA on Linux 32-bit only (xubuntu 14.04, running on VM, alsa or pulse drivers).

It does not happen with MAME 2010 and old FBA 2012 cores.

**Comment by sergiobenrocha2** [comment]
Weird, using goldnaxe, I can hear the noise in FBA, but not in MAME 2014

**Comment by fr500** [comment]
I don't see how this could be a RetroArch problem

**Comment by sergiobenrocha2** [comment]
Reverting this:

```
#define AUDIO_SAMPLERATE 48000
#define AUDIO_SEGMENT_LENGTH 801 // <-- Hardcoded value that corresponds well to 48kHz audio.
```

To this:

```
#define AUDIO_SAMPLERATE 32000
#define AUDIO_SEGMENT_LENGTH 534 // <-- Hardcoded value that corresponds well to 32kHz audio.
```

fix the issue in FB Alpha. @barbudreadmon any idea why does it happen only on i386 ?

**Comment by sergiobenrocha2** [comment]
It's not happening on xubuntu 16.04 (FBA or MAME 2014), only in 14.04. Made the tests using 14.04 in a real machine, same issue, so it's not related to VM. Maybe it's related to a system thing...?

**Comment by barbudreadmon** [comment]
There was a report a few months ago. It seems to depend on the system you use. Those values need to be converted to core options.

**Comment by retro-wertz** [comment]
since 48000hz seems to be max supported by retroarch, is it possible that this is some sort of headroom issue?

https://github.com/libretro/fbalpha/blob/master/src/burner/libretro/libretro.cpp#L1475

this should probably work too, with at least higher sampling rate and a bit of headroom.
#define AUDIO_SAMPLERATE 44100
#define AUDIO_SEGMENT_LENGTH 740// <-- Hardcoded value that corresponds well to 44.1kHz audio.

**Comment by sergiobenrocha2** [comment]
I tried that, same issue if you modify retroarch audio_out_rate from 48 to 44.1 kHz

**Comment by barbudreadmon** [comment]
Those changes followed a discussion with dink a few months ago, you can check the discussion there : http://neosource.1emulation.com/forums/index.php?topic=2487.msg22799#msg22799 , perhaps it will help.

**Comment by bparker06** [comment]
Just FYI I have been told that changing audio_out_rate away from 48khz is a "bad idea" and that it can cause strange problems.

**Comment by sergiobenrocha2** [comment]
Just a heads up, recalbox users are getting this issue too.
