### ISSUE TITLE
Where can I find retroarch support on jailbroken iOS 10 please?

### ISSUE THREAD

**Issue by iOS4all** [libretro/RetroArch#4361]
@twinaphex hi there. I just wondering how can I get iOS 10 version of retroarch the latest version in nightly botbuild is for iOS 9 and stop updating for a while. I downloaded the latest one and it not appeared on my homescreen as well as downloaded the version before this and it appears but when I select core and tries to select roms it said no core found.
Any idea please?

**Comment by fr500** [comment]
You need to copy the cores to /var/applications/RetroArch.app/modules or something like that.

**Comment by iOS4all** [comment]
I already did that but still said no core.

**Comment by fr500** [comment]
some guy on IRC has it working now like that.

**Comment by iOS4all** [comment]
Can you give please the link to download that version of retroarch or even the link that guys talking about it?

**Comment by fr500** [comment]
it was a conversation on IRC.
user dokihara at #retroarch in freenode

**Comment by iOS4all** [comment]
Wha does IRC mean please?

**Comment by iOS4all** [comment]
I guess it's kind of chatting room or something like that

**Comment by fr500** [comment]
http://lmgtfy.com/?q=IRC

**Comment by iOS4all** [comment]
Thank you for helping.
I guess I'll waiting for fix/release to support iOS 10 officially.
