### ISSUE TITLE
RetroArch Crashing when enabling overclock option in FCEUmm core!

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#4363]
On android 4.4 and 4.2.2, previous versions of the core did not crash retroarch, it crashes when you enable the option and resume the game.

**Comment by hizzlekizzle** [comment]
Confirmed in 64-bit Linux.

Backtrace:
http://pastie.org/10987964

**Comment by fr500** [comment]
Please report in the proper repo, you can search for all the libretro repos here:
https://github.com/libretro

**Comment by blackman91** [comment]
New issue here:
https://github.com/libretro/libretro-fceumm/issues/58
