### ISSUE TITLE
Autoconfig does not re-connect after an input goes to sleep

### ISSUE THREAD

**Issue by Reznnate** [libretro/RetroArch#4364]
On Android, Retroarch loses input with wireless controllers if they go into a sleep state.
Autoconfig doesn't re-detect when the connection is restored.
Input can be restored by hitting Android 'home' button, then re-launching Retroarch.

**Comment by hizzlekizzle** [comment]
I don't have this issue on my Shield. After my controller goes to sleep, I wake it up with the nvidia button and then press a button on the pad and it gets re-detected and autoconfigured immediately.

**Comment by Reznnate** [comment]
Perhaps you aren't waiting long enough for it to lose connection.   While it shows autoconfig message for device detection, no further input comes through to retroarch.      I've repro'd this across multiple cores, multiple versions of Retroarch, with both wifi-direct and bluetooth controllers, on multiple versions of Android.

**Comment by hizzlekizzle** [comment]
How long does it take?

**Comment by hugegreenbug** [comment]
I have this issue on my Shield. The controller needs to be inactive for a while. Around 5 -10 minutes.

**Comment by aymanbagabas** [comment]
I have the same issue with RetroPie 4.3 running RetroArch 1.6.4. I'm using Matricom g-pad bx. If I'm in the game and the controller goes into standby/sleep mode it doesn't reconnect unless I restart the emulator.

**Comment by orbea** [comment]
@Reznnate , @hugegreenbug and @aymanbagabas Is this still an issue?

**Comment by orbea** [comment]
Closing in favor of issue https://github.com/libretro/RetroArch/issues/8162 which followed the template.
