### ISSUE TITLE
MFi Controller (with CFA on iOS (9.3.3)) doesn't recognize the analogs

### ISSUE THREAD

**Issue by denisb411** [libretro/RetroArch#4366]
Hello,

I'm using iPega 9025 with Controllers for All on my iphone 9.3.3 and Retroarch can't recognize my analogs. I want to play n64 games and for this is a crucial issue.
Also, neither analogs nor R3/L3/multimedia buttons are working.

See the controller: http://image.made-in-china.com/44f3j00BtHTzungvaqy/Multi-Media-Wireless-Bluetooth-Ipega-Game-Controller-OX-9025-.jpg

Is this a knew bug from retroarch?

If the analogs issues is caused due an incomplete development from Retroarch side, can I even remaps the multimedia buttons from my iPega 9025? I really want them to save/load/fastforward during game.

Thanks and Regards.

**Comment by twinaphex** [comment]
It really is about time that Controller For All stuff gets opensourced, I'm no longer going to care much about spending time on getting that to work.

**Comment by denisb411** [comment]
I don't know why but my analogs started being recognized! 
Now I can map my X+/X-/Y+/Y- of both analogs and it works greatly on mupen64. The only buttons that still can't remap is the R3/L3 buttons and the select button. (when I press select opens a menu to disconnect the controller.... Is this right?)
Sadly CFA is "paid". Maybe it will never become opensource...

**Comment by fr500** [comment]
there is no L3/R3 or select on the MFi spec
