### ISSUE TITLE
menu input legend

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#4369]
I think it could be a good idea to have a legend in the corner of the screen that explains what some/all of the buttons do in the menu, e.g. retropad A = accept, retropad start = return to default, etc.

Building on that basic functionality, it would be better if the text changed to match the type of input being used. That is, if they hit a keyboard button, it switches from the above text to: Enter = accept, Spacebar = return to default, etc.

I think optimum would be to tap into the input descriptors to actually match the pad's buttons to the functions, such as: cross = cancel, triangle = search, etc. to avoid confusion between retropad enumeration and e.g., xbox pads.

**Comment by LibretroAdmin** [comment]
Ozone kinda implements this now.

**Comment by hizzlekizzle** [comment]
yeah, agreed. closing.
