### ISSUE TITLE
Black Boxes on Pixel menu icon theme.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#4371]
Using latest nightly On android xmb menu driver, updating assets does not fix the issue:
![screenshot_2017-01-05-16-31-15](https://cloud.githubusercontent.com/assets/6578180/21700225/04e59280-d365-11e6-95ba-5f2e89749d47.png)
![screenshot_2017-01-05-16-31-36](https://cloud.githubusercontent.com/assets/6578180/21700237/10de90fa-d365-11e6-98d3-08b8389e4151.png)

**Comment by orbea** [comment]
Is `Settings > Directory > Assets` configured correctly?

**Comment by blackman91** [comment]
Yes the assets directory is configured to data/data/com.retroarch/assets

**Comment by RobLoach** [comment]
Can close this in favour of this one: https://github.com/libretro/retroarch-assets/issues/87 ... Let's carry on discussion over there.
