### ISSUE TITLE
Please help.... Games all too fast and no sound.

### ISSUE THREAD

**Issue by lazzomares** [libretro/RetroArch#4375]
Hi. I am completely new a this. Even still I worked out everything according to your Forums and have been successful with all but two items before I can go ahead and enjoy retro gaming. 

1. There is no sound on any ROMS I DL.

2. Games are way too fast. All of them, No matter who I DL them from. 

I have read through many FAQ and FORUMS on this. Can't get it fixed. Any support would be appreciated.

**Comment by meepingsnesroms** [comment]
Need way more information.

What OS are you on?
What RetroArch build?
Games tested?
With what core?
Could you post your retroarch.cfg too so I can see all your config options?

**Comment by hizzlekizzle** [comment]
A verbose log would be helpful, too. The symptoms suggest broken vsync and disabled audio. Both could be driver-related or bad configuration.

**Comment by RobLoach** [comment]
You'll want to use the correct audio driver for your device. Are you using HDMI audio?
https://pirraste.wordpress.com/2014/02/28/retroarch-alsa-audio-over-hdmi-working/

**Comment by fr500** [comment]
No feedback, closing
