### ISSUE TITLE
Reicast 32-bit build

### ISSUE THREAD

**Issue by tabnk** [libretro/RetroArch#4376]
Is there a reicast 32-bit version for retroarch ?

At this https://github.com/libretro/reicast-emulator/commit/4467d7f1f16d9da8cf09f6790ac4f599f8288e2b look like can be compiled but not available at https://buildbot.libretro.com/nightly/windows/x86/latest/ ?

**Comment by orbea** [comment]
It should build, you could do it for yourself while you wait for the buildbot to provide it.

**Comment by Kivutar** [comment]
It builds in lakka but it was segfaulting for me

**Comment by meepingsnesroms** [comment]
This is an issue but it belongs at  libretro/reicast-emulator not under RetroArch.
