### ISSUE TITLE
[XMB] Retroarch crashing upon using the file browser (Windows 10 x64)

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#4379]
On Windows 10 x64, latest code produces a crash by selecting any option that lets you manually browse a content / shader preset. 
Among the cases I have experienced, I can confirm that the issue manifests itself upon clicking on 'Load Shader Preset', or selecting 'Load Content' and choosing either a hard drive letter or the 'Favorites' directory.

EDIT: It is also crashing when trying to change the Directories for anything under Settings->Directory.

A quick bisect indicates 9d9a5e7 as the first bad commit.

**Comment by fr500** [comment]
I got the crash ONCE, but I have been trying to get it to crash again and no dice.

**Comment by Ryunam** [comment]
I'm getting the crash consistently, every single time I use the file browser and click on a hard drive letter, or anytime I click on 'Load Shader Preset' from the Quick Menu. I've also tested this with the default configuration, no remaps or overrides or any customization, and the problem keeps cropping up.
Logs do not seem to indicate anything of relevance.

**Comment by retro-wertz** [comment]
confirm crash here using buildbot-release
https://github.com/libretro/RetroArch/commit/f6ebcebfea83894a6f3aff6e98e6da6a7d00b23d.
just want to do "Import Content" and immediate crash when choosing a drive
letter (x86_64)

**Comment by twinaphex** [comment]
Can you retry it again as of this commit?

https://github.com/libretro/RetroArch/commit/830c01476f7ebdd6b93521485a3eb0c985178646

**Comment by twinaphex** [comment]
Apparently I was told this was fixed. Reopen if this is not the case.
