### ISSUE TITLE
3DS nightly builds all messed up.

### ISSUE THREAD

**Issue by Zexceil** [libretro/RetroArch#4382]
Alot of cores have been removed and the XMB menu is all messed up along with missing fonts , etc
nothing really launches either

**Comment by stoz** [comment]
On the 2017-01-05 nightly I've been able to successfully run Gambattle and Nestopia though both XMB and rGUI on my original 3DS. At this stage it seems much easier to use rGUI though.

**Comment by fr500** [comment]
There is not enough information in this ticket to do anything about it. Please create a new one and be more speciffic.
