### ISSUE TITLE
RetroArch 1.3.6 not detecting Hat input on Mac OS

### ISSUE THREAD

**Issue by jprjr** [libretro/RetroArch#4383]
Hi there 

I have a RetroLink N64 Gamepad, its D-Pad is reported as a Hat Switch. I've confirmed it works with RetroArch on other platforms (Linux and Windows), but on Mac OS, RetroArch doesn't seem to detect the hat switch.

I've tried using the RetroArch GUI to configure binding the Hat switch (it acts like I didn't press anything), and I've tried editing the config file to use the hat switch - it still doesn't work.

Please let me know if there's anything else I can attach (some type of debug log, etc).

This is running on macOS 10.12.2

**Comment by hizzlekizzle** [comment]
We don't have any automated nightly builds for OSX right now, but if you can compile from source via XCode, you can see if the nightlies treat you any better/worse. Otherwise, we hope to have the automated nightly builds back up and running soon, so you can just wait for that, if necessary.

**Comment by hizzlekizzle** [comment]
Ok, thanks for confirming. Does the hatswitch work anywhere else in OSX?

**Comment by jprjr** [comment]
It does - it works with OpenEmu

On January 10, 2017 8:15:39 PM CST, hizzlekizzle <notifications@github.com> wrote:
>Ok, thanks for confirming. Does the hatswitch work anywhere else in
>OSX?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/libretro/RetroArch/issues/4383#issuecomment-271758756

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jprjr** [comment]
I think I might have found the culprit? https://github.com/libretro/RetroArch/blob/master/input/drivers_hid/iohidmanager_hid.c#L185

I *believe* this is the code that reads axes, buttons, etc. As far as I can tell, if the input is a hat switch it just skips it. My C skills aren't super-hot so I could be wrong
