### ISSUE TITLE
GLSL shader performance optimization

### ISSUE THREAD

**Issue by loganmc10** [libretro/RetroArch#4387]
Right now, when shaders are enabled, multiple calls to **glGetUniformLocation** happen each frame, see below (crt-pi shader):

![image](https://cloud.githubusercontent.com/assets/848146/21774246/1d22b7f0-d64f-11e6-846f-754969a7a360.png)

The location of the uniform is set once the program is linked, there should be no need to call glGetUniformLocation each frame, you get it once after the GLSL program is linked and you re-use it.

Generally glGet* calls are quite slow, since it requires asking the GPU for information and can cause some stalling, although the exact impact will likely differ from GPU to GPU.

I'm not super familiar with the GLSL shader code, and I've broken GL rendering stuff in the past, but the changes will need to take place in gfx/drivers_shader/shader_glsl.c

**Comment by hizzlekizzle** [comment]
My suspicion is that it's for the runtime parameters, so the shader doesn't need to be recompiled to take effect. Not sure, though.

**Comment by loganmc10** [comment]
That may be what the uniforms are for, but there is no need to query the location of the uniform each frame. Once the GLSL program is compiled and linked, those values never change.

There is a chance that the driver can tell this (aka, you've already asked for this information, here is what I told you last time), so it might not be much of a performance hit, but you can't count on that with every driver.

**Comment by loganmc10** [comment]
I believe the code in question is here:

https://github.com/libretro/RetroArch/blob/99421b42d51a1bf19f096a55652944f7e87e3d23/gfx/drivers_shader/shader_glsl.c#L1329-L1356

Basically that "location" variable needs to be cached instead of queried every time.

**Comment by hizzlekizzle** [comment]
well, if you want to give it a shot, you could make the change and then open up a GLSL shader with parameters and see if you can still change them on the fly without hitting 'apply shader changes'
