### ISSUE TITLE
PKGBUILD broken on AUR

### ISSUE THREAD

**Issue by nyayaya** [libretro/RetroArch#4388]
PKGBUILD from the AUR for retroarch-git is broken. Its referring to files in the audio/audio_filters directory which doesn't exist anymore in the repo. Heres the error while compiling:

make: *** audio/audio_filters: No such file or directory.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build retroarch-git.

And heres the part from PKGBUILD which (i believe) is causing this (line 85):

install -m 644 audio/audio_filters/*.{dsp,so} "${pkgdir}"/usr/lib/retroarch/filters/audio/

I don't know what to replace it with, so I didn't try compiling it with a modified PKGBUILD file.

**Comment by twinaphex** [comment]
You need to modify your PKGBUILD.

audio/audio_filters got changed now to libretro-common/audio/dsp_filters

**Comment by nyayaya** [comment]
Thanks! Compiling right now, will close this issue if that fixes it.

**Comment by nyayaya** [comment]
Yep, that worked. Edited the entries on lines 73 and 85 and it compiled fine. 
Cheers
