### ISSUE TITLE
[MUSL] Please add support for musl =(

### ISSUE THREAD

**Issue by LipkeGu** [libretro/RetroArch#4393]
It would be nice when we can compile retroarch on musl libc
```
--- a/interface_stream.h	2017-01-10 06:44:46.492415645 +0100
+++ b/interface_stream.h	2017-01-10 06:42:32.275922000 +0100
@@ -25,6 +25,7 @@
 
 #include <stdint.h>
 #include <stddef.h>
+#include <sys/types.h>
 #include <retro_common_api.h>
 #include <boolean.h>
 

```

**Comment by Alcaro** [comment]
#include <sys/types.h> was added to libretro-common/include/streams/interface_stream.h [five months ago](https://github.com/libretro/RetroArch/commit/d245bbf12e0fb12c6e0c75aec302aec356c1320d).

**Comment by LipkeGu** [comment]
i fixed it by myself

https://github.com/recalbox/recalbox-buildroot/pull/609/commits/03a0badf8576d436304c636bbda63bcdaeceaed2

**Comment by Alcaro** [comment]
You are using version [31bcb3d6f84b99c93844bde70251bcf3dec9ce7b](https://github.com/recalbox/recalbox-buildroot/blob/master/package/retroarch/retroarch.mk#L10).

That version is [almost six months old](https://github.com/libretro/RetroArch/commit/31bcb3d6f84b99c93844bde70251bcf3dec9ce7b).

We can't fix things that already work. Update your distro.
