### ISSUE TITLE
Direct3D support for XMB menu driver

### ISSUE THREAD

**Issue by Zanmato27** [libretro/RetroArch#4394]
Would it be possible for RetroArch to have Direct3D support for the XMB menu driver? As much as I like the customization and look of the the XMB menu driver, however, since I am running a Windows 10 computer, using the OpenGL and Vulkan video drivers has micro-stutters when playing on windowed mode as opposed to fullscreen as mentioned on [this article](https://github.com/libretro/RetroArch/wiki/Getting-optimal-vsync-performance). When I switch to Direct3D I don't see the stutters happening in windowed mode but I'm forced to use the RGUI menu drivers since the XMB menu driver shows a black screen with yellow text. Is there any possibility for the XMB menu driver to support Direct3D on Windows?

**Comment by fr500** [comment]
I have stutter in Vulkan but none in GL
Even if that was implemented it wouldn't allow GL cores to work though unless we had ANGLE or something like that.

**Comment by Alcaro** [comment]
This sounds like a job for WGL_NV_DX_interop; it allows, for example, rendering with OpenGL but presenting with Direct3D. [I wrote some code for that a few months ago](https://github.com/Alcaro/Arlib/tree/master/arlib/opengl), it's perfectly stutter-free on everything I've tried.

If the RetroArch guys want it, you may consider it GPLv3. (Offer not valid for other projects.)

**Comment by ItachiSan** [comment]
Would really like it.

**Comment by twinaphex** [comment]
I agree as well, we should have a fleshed out D3D menu display driver so that MaterialUI and XMB can work on it.

**Comment by prataczak** [comment]
Hello, there's two bounties that seem to be associated with this issue:
https://www.bountysource.com/issues/44606443-direct3d-create-a-direct3d-11-12-backend-for-the-d3d-driver

and

https://www.bountysource.com/issues/48032360-direct3d-menu-display-driver-implementation-so-that-materialui-and-xmb-work

Are these the same thing? Direct3d lets me take screenshots with the 'printscreen' key which is useful to me for reasons. :)

I'd like to contribute but I'm not sure whether I should post a bounty to one or the other or both. 

I'd personally drop $30 on this.

**Comment by twinaphex** [comment]
This issue is the same as the latter bounty yes.

**Comment by prataczak** [comment]
Bounty added. :)

Hope this gets fixed soon.

**Comment by twinaphex** [comment]
This should be implemented now.
