### ISSUE TITLE
rewind_enable causes some NGP games to crash

### ISSUE THREAD

**Issue by RetroUp** [libretro/RetroArch#4395]
Tested on Windows with latest from buildbot and 1.3.6.

Set rewind_enable = "true". Leave all other settings default.

Play Baseball Stars for SNK - Neo Geo Pocket. Game will crash on load.

If a SRAM file exist or if rewind is disabled then the game will load.

Happens with NGP games that support SRAM. Have not found any other cores with same problem.

**Comment by fr500** [comment]
It's a problem with NGP's serializer then, close this and open in the NGP repo
