### ISSUE TITLE
[probably vulkan only] Crash when choosing "close" in the quick menu (gdb backtrace included)

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#4398]
gdb backtrace:

http://lex.clansfx.co.uk/dump/65e7efdabb4c59e368e512d8a5430a04/000001C3.txt

This happened after playing a while.  When trying to reproduce it by starting a game with the same core and immediately closing it, it didn't crash.

**Comment by AlexFolland** [comment]
I reproduced it after playing a while again, this time with a different core.

gdb backtrace:

http://lex.clansfx.co.uk/dump/a0499423828ae30e1ccd7f02681ff266/000001C4.txt

**Comment by twinaphex** [comment]
Test if it happens too with the GL driver.

**Comment by AlexFolland** [comment]
I haven't seen it with the OpenGL driver yet.

Furthermore, I can't seem to run any cores with Vulkan now (crashes on attempting to run content); backtrace here: http://lex.clansfx.co.uk/dump/78737034c8c128329744ed744d891844/000001CA.txt ).  It may be due to the new Nvidia 376.66 beta driver downloadable from https://developer.nvidia.com/vulkan-driver which I have installed.  Someone else testing this would be helpful when they have time.

**Comment by fr500** [comment]
Is this on-going?

**Comment by AlexFolland** [comment]
Unless something about it has been addressed, yes.
