### ISSUE TITLE
Can't get lightgun support in any game

### ISSUE THREAD

**Issue by nobody37** [libretro/RetroArch#4400]
This is on Raspberry Pi 3 with RetroPie v4.1.8 installed on SD. 
I can't get lightgun input to work on any games I try of mine:

Missile Defense 3-D (SMS)
Safari Hunt (SMS)
The Adventures of Bayou Billy (NES)
Super Scope 6 (SNES)

I tried first with a regular mouse pointer, and also with an AR1100 Touchscreen. I can't get either to do anything in games for touchscreen.

**Comment by fr500** [comment]
In snes you have to set it to mouse in port #2 IIRC

**Comment by nobody37** [comment]
I tried that and it wouldn't work. Gun cursor doesn't move it stays stationary in the middle. It can fire, but doesn't move so it's unusable.

**Comment by nobody37** [comment]
It's every core by the way so I think it's a RetroArch issue and it does belong here, unless you can show me otherwise. How can I diagnose this issue and if my input devices are being properly detected?

**Comment by fr500** [comment]
If you can use them as a mouse in RetroArch then RetroArch is detecting them fine.

**Comment by nobody37** [comment]
I have no mouse support within the menus in RetroArch, should I?
If so, how do I enable that?

**Comment by nobody37** [comment]
I also already talked to ekeeke over at Genesis-Plus-GX and this is what he had to say, something about he needs it to use RETRO_DEVICE_POINTER instead of RETRO_DEVICE_LIGHTGUN.

https://github.com/ekeeke/Genesis-Plus-GX/issues/87

I really should not have had to have even that technical of a conversation, but maybe you can decipher what's going on.

The only thing I can think of is taking the input parts of the source here and trying to write some kind of command-line script based on it to diagnose what the mouse is actually doing under each driver, and since I'm a beginner at udev and all that, it may be a while as you can see, I'm sure it took you guys a heck of a long time to write it. That's a LOT for an end user to do just to figure out who it is I'm actually supposed to be talking to for help, but I'm willing to help if it means getting the issue resolved quickly. 

It sounds about like going over to the DPS office to get a new Drivers License. You spend an hour in the line you think you're supposed to be in, just to be told that you need to be in another line. Once you're in that line for another hour, the person at the front points you to a tiny sign saying it's cash only and you only have a credit card on you. Then you go back to the ATM and get cash after paying a service fee, just to get to the end of the second line and have them tell you that their machine is down and you'll have to wait at the first line. :-P

So if it's a core issue, great, but I've been to the core, and they're blaming you essentially. I don't care who is to blame, I just want to play some Missile Defense 3-D and Bayou Billy on RetroPie. All I'm looking for are the results I want.

Posted this also in RetroPie Help and Support, 40+ views and nobody seems to know anything over there either, just different technical things I've tried in order to help diagnose:
https://retropie.org.uk/forum/topic/7146/lightgun-pointer-configuration-ar1100-touchscreen

**Comment by twinaphex** [comment]
Dont try to start conflict between several devs and all sorts of talk regarding 'blame' being passed. I am warning you in advance that you already have my full and undivided attention for all the wrong reasons. 

Now, please, cut down on the attitude, and try again an attempt at civil discourse. Opensource projects live or die based on contributions, and the lead authors dont owe anything to you. be gladwe take time out of their daily schedule to even provide you with feedback and listen to complaints and try to help where possible, but DO NOT try to start drama or conflict between other authors, or youre out of here. Let that be very clear.

Dont start your jext post also with a bunch of passive aggressive stuff or youre out of here as well.

**Comment by nobody37** [comment]
Ok I'll start a new thread but just want to clear up a couple of things:

1) I'm a big supporter of the RetroArch architecture, much love to you guys, my sarcasm gets a little thick at times, it's just what I'm used to, sorry I'll tone it down. I can promise you it was not nearly as serious coming from me as it probably came across I'm sure (and I can assure you, NO ONE is ever sensitive with me, but I'm used to that), I'm more so focused on getting whatever potential issue there is resolved than anything. 

Just know, I'm here to get things going, even sharing RetroPie in my local community. I've built a sort of mobile kiosk I can take around with me and telling people about RetroPie in the DFW area. In case you're curious, here's RetroPie on the kiosk, running Galaga in my driveway. :-P (https://www.facebook.com/groups/dallasretrogamers/1205479962861020/?notif_t=like&notif_id=1484254729767166)

2) I've been getting bounced around on this particular issue for like a week now from different sources, I'm a little frustrated, didn't mean to take it out on you guys, but just want to get answers. I didn't even know there's a Lakka distro, should I be using that instead of RetroPie, or is it good to stay where I'm at?

3) I wasn't trying to start drama against you and the Genesis guy. Frankly I have too much going on in my daily life, I volunteer locally at a food pantry, volunteer as a GED tutor, work, do bodybuilding, occasionally do programming/gfx design/muzak (I'm a game and app dev). I wasn't aware there's stuff going on with people trying to create rifts between core authors and RetroArch. I'd kind of figure that's going to be a natural occurrence anytime you have different people managing different things, it's always this way in business. Anyway, that's a different discussion for another time, I'll post in a new thread.

**Comment by twinaphex** [comment]
Alright, I have had plenty of bad experiences with guys talking to other devs and then words get taken out of context and fights get started in that way, and in an already volatile scene, I am increasingly being forced out of necessity to have a zero tolerance policy towards users that engage in that kind of thing. I'll give you the benefit of the doubt and assume it is not that. So start the issue in the right designated area (Genesis Plus GX libretro repo) and we can go from there.

Like I mentioned though, RetroPie is configured differently from mainline RetroArch and our official distribution Lakka. We can't really provide support for it, we can help you to the best of our abilities though inso far as it is related to RetroArch.
