### ISSUE TITLE
Player 1 not consistent

### ISSUE THREAD

**Issue by prototypeshogun** [libretro/RetroArch#4403]
In the current build for android on the site you launch retroarch with controller A, menu wants controller B and then the actual game uses controller A.

**Comment by fr500** [comment]
Try resetting your device indexes if you fiddled with them.
It associates a controller to a port on button press. The only thing not working fine is changing the devices associated to a port.

**Comment by loganmc10** [comment]
There is also an option under input called "All Users Control Menu", which will allow any controller to work in the menu.

It's Off by default but should probably on On by default if you ask me

**Comment by prototypeshogun** [comment]
Oddly enough "All Users Control Menu" is missing from android on the current build. I remember seeing it on windows, mac and my pi, but not on android.

**Comment by loganmc10** [comment]
I see it there (nightly), I'm not sure about the current version on the Play Store

**Comment by fr500** [comment]
We're not giving support to 1.3.6 anymore even though we haven't released a new plat store version. Please update, retest and reopn if needed.

Also report your device and your gamepad model.
