### ISSUE TITLE
Gundam Seed Destiny rom ending bug

### ISSUE THREAD

**Issue by montiblanc** [libretro/RetroArch#4411]
At the end of main mode, at the credits, i'm supposed to press start & spam "A" for some graphical effects & bonus points; this does not work on retroarch.

**Comment by fr500** [comment]
This is not a RetroArch isssue. it's most likely a core issue. Please reopen it in the core bug tracker.

**Comment by montiblanc** [comment]
where is that? it was the mGBA

**Comment by ofry** [comment]
https://github.com/libretro/mgba/issues

**Comment by sergiobenrocha2** [comment]
Please report this kind of issue to upstream https://github.com/mgba-emu/mgba
