### ISSUE TITLE
Device index change doesn't produce the expected result

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4412]
**Symptom:**
Changing device index affects the menu controls correctly, but once you go in-game the default indexes are used.

By default RA uses the OS enumeration for the device index (controller 1 mapped to port 1, etc) this works fine. If you change controller 1 to port 2 and controller 2 to port 1 it seems to work correctly on the menu but when going in-game controller 1 is controlling port 1 and controller 2 is controlling port 2 again.

**Expected result:**
Swapping the indexes should affect in-game controls too, allowing the user to use controller 2 for port 1 or 3 or 4 or whatever. This was working fine a few weeks ago

@AlexFolland noticed this issue first

**Comment by twinaphex** [comment]
We need somebody to do a bisect on this.

**Comment by AlexFolland** [comment]
The first commit in which I see this issue is https://github.com/libretro/RetroArch/commit/6376f2af6873a8d067f3b33b4344185fb93cc3ba

The previous commit doesn't exhibit the issue.

**Comment by twinaphex** [comment]
This should be fixed as of this commit -

https://github.com/libretro/RetroArch/commit/77cf4f4e064172d8d53967756cda12f2140d6e7a

Reopen if things still don't work.
