### ISSUE TITLE
[CYGWIN x64] Retroarch build failed

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#4419]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Compilation via CygWin failed.
```

$ uname -a
CYGWIN_NT-6.3 games 2.6.1(0.305/5/3) 2016-12-16 11:55 x86_64 Cygwin
```

after configure, make...
.........
```
LD retroarch
obj-unix/gfx/common/egl_common.o: In function `egl_report_error':
/home/ofry/RetroArch/gfx/common/egl_common.c:39: undefined reference to `eglGetError'
/home/ofry/RetroArch/gfx/common/egl_common.c:39:(.text+0x5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglGetError'
obj-unix/gfx/common/egl_common.o: In function `egl_destroy':
/home/ofry/RetroArch/gfx/common/egl_common.c:122: undefined reference to `eglMakeCurrent'
/home/ofry/RetroArch/gfx/common/egl_common.c:122:(.text+0x15e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglMakeCurrent'
/home/ofry/RetroArch/gfx/common/egl_common.c:125: undefined reference to `eglDestroyContext'
/home/ofry/RetroArch/gfx/common/egl_common.c:125:(.text+0x16f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglDestroyContext'
/home/ofry/RetroArch/gfx/common/egl_common.c:128: undefined reference to `eglDestroyContext'
/home/ofry/RetroArch/gfx/common/egl_common.c:128:(.text+0x181): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglDestroyContext'
/home/ofry/RetroArch/gfx/common/egl_common.c:131: undefined reference to `eglDestroySurface'
/home/ofry/RetroArch/gfx/common/egl_common.c:131:(.text+0x193): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglDestroySurface'
/home/ofry/RetroArch/gfx/common/egl_common.c:132: undefined reference to `eglTerminate'
/home/ofry/RetroArch/gfx/common/egl_common.c:132:(.text+0x19c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglTerminate'
obj-unix/gfx/common/egl_common.o: In function `egl_set_swap_interval':
/home/ofry/RetroArch/gfx/common/egl_common.c:184: undefined reference to `eglGetCurrentContext'
/home/ofry/RetroArch/gfx/common/egl_common.c:184:(.text+0x266): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglGetCurrentContext'
/home/ofry/RetroArch/gfx/common/egl_common.c:188: undefined reference to `eglSwapInterval'
/home/ofry/RetroArch/gfx/common/egl_common.c:188:(.text+0x284): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglSwapInterval'
obj-unix/gfx/common/egl_common.o: In function `egl_report_error':
/home/ofry/RetroArch/gfx/common/egl_common.c:39: undefined reference to `eglGetError'
/home/ofry/RetroArch/gfx/common/egl_common.c:39:(.text+0x2a0): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglGetError'
obj-unix/gfx/common/egl_common.o: In function `egl_get_video_size':
/home/ofry/RetroArch/gfx/common/egl_common.c:204: undefined reference to `eglQuerySurface'
/home/ofry/RetroArch/gfx/common/egl_common.c:204:(.text+0x3eb): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `eglQuerySurface'
/home/ofry/RetroArch/gfx/common/egl_common.c:205: undefined reference to `eglQuerySurface'
/home/ofry/RetroArch/gfx/common/egl_common.c:205:(.text+0x403): additional relocation overflows omitted from the output
obj-unix/gfx/common/egl_common.o: In function `egl_init_context':
/home/ofry/RetroArch/gfx/common/egl_common.c:217: undefined reference to `eglGetDisplay'
/home/ofry/RetroArch/gfx/common/egl_common.c:224: undefined reference to `eglInitialize'
/home/ofry/RetroArch/gfx/common/egl_common.c:229: undefined reference to `eglChooseConfig'
obj-unix/gfx/common/egl_common.o: In function `egl_create_context':
/home/ofry/RetroArch/gfx/common/egl_common.c:240: undefined reference to `eglCreateContext'
/home/ofry/RetroArch/gfx/common/egl_common.c:249: undefined reference to `eglCreateContext'
obj-unix/gfx/common/egl_common.o: In function `egl_create_surface':
/home/ofry/RetroArch/gfx/common/egl_common.c:262: undefined reference to `eglCreateWindowSurface'
/home/ofry/RetroArch/gfx/common/egl_common.c:268: undefined reference to `eglMakeCurrent'
/home/ofry/RetroArch/gfx/common/egl_common.c:271: undefined reference to `eglGetCurrentContext'
obj-unix/gfx/common/egl_common.o: In function `egl_get_native_visual_id':
/home/ofry/RetroArch/gfx/common/egl_common.c:278: undefined reference to `eglGetConfigAttrib'
obj-unix/gfx/common/egl_common.o: In function `egl_get_proc_address':
/home/ofry/RetroArch/gfx/common/egl_common.c:105: undefined reference to `eglGetProcAddress'
obj-unix/gfx/common/egl_common.o: In function `egl_bind_hw_render':
/home/ofry/RetroArch/gfx/common/egl_common.c:158: undefined reference to `eglMakeCurrent'
obj-unix/gfx/common/egl_common.o: In function `egl_swap_buffers':
/home/ofry/RetroArch/gfx/common/egl_common.c:171: undefined reference to `eglSwapBuffers'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make: *** [Makefile:142: retroarch] Ошибка 1
```

- OS: Windows 8.1 x64, cygwin toolchain
- Compiler: [In case you are running local builds]

`$ ./configure
Checking operating system ... Cygwin
Checking for suitable working C compiler ... /usr/bin/gcc works
Checking for suitable working C++ compiler ... /usr/bin/g++ works
Checking for pkg-config ... /usr/bin/pkg-config
Checking for availability of switch -std=gnu99 in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-result in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-variable in /usr/bin/gcc ... yes
Checking function bcm_host_init in -lbcm_host ... no
Checking function sd_get_machine_names in -lsystemd ... no
Checking presence of package egl ... 12.0.4
Checking function ass_library_init in -lass ... yes
Checking function pthread_create in -lpthread ... yes
Checking function pthread_key_create in -lpthread ... yes
Checking function dlopen in -ldl ... yes
Checking function socket in -lc ... yes
Checking function getaddrinfo in -lc ... yes
Checking existence of -lminiupnpc ... no
Checking function fcntl in -lc ... yes
Checking function getopt_long in -lc ... yes
Checking presence of package alsa ... no
Checking presence of header file sys/soundcard.h ... yes
Checking presence of header file soundcard.h ... no
Checking existence of -lossaudio ... no
Checking function alcOpenDevice in -lopenal ... yes
Checking presence of package rsound >= 1.1 ... no
Checking presence of package libroar ... no
Checking presence of package jack >= 0.120.1 ... no
Checking presence of package libpulse ... 9.0
Checking presence of package sdl >= 1.2.10 ... 1.2.15
Checking presence of package sdl2 >= 2.0.0 ... 2.0.3
Notice: SDL drivers will be replaced by SDL2 ones.
Checking presence of package libusb-1.0 >= 1.0.16 ... 1.0.20
Checking presence of header file GL/gl.h ... yes
Checking existence of -lGL ... yes
Checking function cgCreateContext in -lCg ... no
Checking presence of package zlib ... 1.2.8
Checking presence of package libavcodec >= 54 ... no
Checking presence of package libavformat >= 54 ... no
Checking presence of package libavdevice ... no
Checking presence of package libswresample ... no
Checking presence of package libavresample ... no
Checking presence of package libavutil >= 51 ... no
Checking presence of package libswscale >= 2.1 ... no
Checking presence of header file libavutil/channel_layout.h ... no
Notice: FFmpeg built-in support disabled due to missing or unsuitable packages.
Checking function dlopen in -ldl ... yes
Checking presence of package gbm >= 9.0 ... no
Checking presence of package libdrm ... no
Checking presence of package libxml-2.0 ... 2.9.4
Checking presence of package vg ... no
Checking existence of -lOpenVG ... no
Checking presence of package libv4l2 ... no
Checking function glFramebufferTexture2D in -lGL ... yes
Checking presence of package freetype2 ... 18.5.12
Checking presence of package x11 ... 1.6.4
Checking presence of package xcb ... 1.12
Checking presence of package wayland-egl ... no
Checking presence of package wayland-cursor ... no
Checking presence of package xkbcommon >= 0.3.2 ... 0.6.1
Checking presence of package dbus-1 ... 1.10.12
Checking presence of package xext ... 1.3.3
Checking presence of package xxf86vm ... no
Checking presence of package xinerama ... 1.1.3
Notice: X11, Xext or xf86vm not present. Skipping X11 code paths.
Checking presence of package libudev ... no
Checking existence of -ludev ... no
Checking presence of header file linux/parport.h ... no
Checking function strlcpy in -lc ... yes
Checking function strcasestr in -lc ... yes
Checking function mmap in -lc ... yes
Checking function vkCreateInstance in -lvulkan ... no
Creating make config: config.mk
Creating config header: config.h
`

**Comment by Alcaro** [comment]
Multimedia apps, such as RetroArch, want direct access to the native platform APIs. Emulation layers, such as Wine, Cygwin or Windows10-Ubuntu, will yield inferior results.

We recommend MinGW via MSYS2.

But I agree that failing Cygwin via linker errors is a bug. Either Cygwin should work, or it should fail in ./configure.

**Comment by ofry** [comment]
This is just test case... I already have full Cygwin install (with all provided packages). So I tried start to bisect issue #4402 via compiling RA from Cygwin. And it failed.

So I create the issue.

**Comment by fr500** [comment]
Cygwin is not a target we care for.
https://bot.libretro.com/docs/compilation/windows/

**Comment by ofry** [comment]
yes, it's bad target... but it should compile at least?

**Comment by fr500** [comment]
We haven't targeted it so no.

**Comment by ofry** [comment]
And why it didn't targeted?

**Comment by fr500** [comment]
Because we are not infinite people with infinite time

**Comment by Alcaro** [comment]
>Multimedia apps, such as RetroArch, want direct access to the native platform APIs. Emulation layers, such as Wine, Cygwin or Windows10-Ubuntu, will yield inferior results.
