### ISSUE TITLE
SNES Boxart fails to download on multiple devices

### ISSUE THREAD

**Issue by kryptalivian** [libretro/RetroArch#4420]
Running Android version of Retroarch on a Nvidia Shield tv and LeEco Android TV. One is latest nightly, other is from google play store. Both fail when downloading boxart for snes. Goes 0.1.2.3.0.1.2.3 etc, then says failed to download Supernintendoentertainmentsystem.zip

**Comment by fr500** [comment]
We included an issue template for a reason.
We need to gather more information.

I just tried downloading locally and it works fine for me.

**Comment by kryptalivian** [comment]
Sorry about that fr500! Thats strange, wonder why two different devices are doing this? I have a rock solid connection(Google Fiber). I will do some research and try a few things then. Thanks for checking the issue on your end.

**Comment by fr500** [comment]
Reopen if it still doesn't work
