### ISSUE TITLE
1.4.0 Stable .3dsx format does not load any content. 

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#4423]
## Description

When loading content for both Snes9x 2010 and nestopia and gpsp, retroarch (.3dsx) freezes. The directory for choosing a game works fine, but upon selecting a game it freezes entirely. As this happened with those 3 cores, I assume it applies to all. Did not bother trying more as this has been an issue in the last couple of nightlies as well. 

Concerning to see this released as a stable. 

### Expected behavior

The game should actually load.

### Actual behavior

Retroarch is freezing and demands a hard reboot.

### Steps to reproduce the bug

1. Load content
2. Browse to SD card works fine
3. Selecting ROM results in freeze

### Version/Commit

- RetroArch: [3ds(.3dsx)/1.4.0 stable]

**Comment by Cruplezone** [comment]
I figured it out. On a fresh download from the buildbot of both the retroarch and .3dsx files, the directory for "Core Dir" is not set in settings -> directory. Odd...

**Comment by fr500** [comment]
Seems like an easy thing to fix but since it makes RA unusable on the platform, marking it as major

**Comment by twinaphex** [comment]
@meepingsnesroms says this can be closed now.
