### ISSUE TITLE
3ds (1.4.0 Stable .3dsx format) Selecting "File Browsing Directory" in Settings does not actually do anything when using "Load Content"

### ISSUE THREAD

**Issue by Cruplezone** [libretro/RetroArch#4424]
## Description

In Settings -> Directories there is an option to select File Browser Directory so that it is not required to navigate to your ROM folder everytime you select "Load Content". Selecting the Directory in settings works fine, but this does not change the behavior when you select "Load Content", it still starts navigation on the root.

### Expected behavior

When selecting Load Content that it starts file browsing at the defined directory in settings for "File Browser"

### Actual behavior

Starts file selection at root. 

### Steps to reproduce the bug

1. Go to directories in settings and select a directory for your roms
2. Go to load content
3. It will ignore your directory specification

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [3ds (.3dsx format)/1.4.0 Stable]

**Comment by fr500** [comment]
check "Favorites"

**Comment by Cruplezone** [comment]
@fr500 yes you're right it's n there. Is that what it's supposed to do?

**Comment by fr500** [comment]
It's new and not finalized
