### ISSUE TITLE
Spaces in text not displayed in Theme "Systematic"

### ISSUE THREAD

**Issue by CoalaJoe** [libretro/RetroArch#4428]
## Description

Spaces in text not displayed in Theme "Systematic"

### Actual behavior
![image](https://cloud.githubusercontent.com/assets/5689499/21965730/4251a100-db66-11e6-92ff-a82a47c30807.png)

### Steps to reproduce the bug

- RetroArch: [1.4.0/master-e4fa9f178c39b56e91fa1e23370b23f53e3134dd]

### Environment information

- OS: [Linux]

**Comment by fr500** [comment]
Uh I do see spaces in that image... the font is obviously narrow

**Comment by CoalaJoe** [comment]
What font is this?

**Comment by CoalaJoe** [comment]
After proper scaling it looks good.
