### ISSUE TITLE
(Wii U) DSI error after closing a game and launching another one / when scanning content

### ISSUE THREAD

**Issue by MeisterLLD** [libretro/RetroArch#4433]
## Description
- Most cores seem to do that, ending up in a DSI error that either requires a cord pull or a power off. FCEUmm does work well. I don't know if it's a problem in most cores or in RetroArch frontend and its communication with these.
- All cores result in a DSI error when scanning content.

### Version/Commit
1.4.0 Stable

### Environment information
- OS: Wii U

**Comment by roflcopter777** [comment]
Can confirm this as well. Snes9x mainline loaded one ROM and after loading a subsequent ROM, results in a system crash. Pro Controller works great though.

**Comment by twinaphex** [comment]
I think these are just reentrance issues with certain cores.

**Comment by cucholix** [comment]
I can confirm this issue with Mame 2003 core too.

**Comment by twinaphex** [comment]
Try to see if this fixes it - so test today's nightly I guess later today -

https://github.com/libretro/RetroArch/commit/ee7fd79fb2ca45378d1d5bef5e6b44cb554e31a9

**Comment by MeisterLLD** [comment]
Seems to work fine ! At least in snes9x mainline, couldn't test the others yet. Thanks a lot !

**Comment by roflcopter777** [comment]
Tested Genesis Plus, Nestopia Undead and Snes9x 1.53, all cores work 100% perfectly and loading multiple ROMs in succession. Thank you so much!

**Comment by twinaphex** [comment]
Great job @aliaspider! Guess we can close this now.
