### ISSUE TITLE
keyboard binding state continues after binding gamepad button

### ISSUE THREAD

**Issue by AlexFolland** [libretro/RetroArch#4434]
Steps to reproduce:
1. Navigate to: Settings -> Input -> Input User 1 Binds -> User 1 B button
2. Press Enter on the keyboard
3. Press a gamepad button
4. Press the "down" arrow key on the keyboard

The keyboard bind is set to "keypad2" upon pressing the "down" arrow key.

This happens for me in Windows with "input driver" set to "dinput" and "joypad driver" set to "xinput".

I haven't bisected.

**Comment by twinaphex** [comment]
I think this is fixed now. as of this commit - 

https://github.com/libretro/RetroArch/commit/0b1a204949278e63e61f82585a1917c9a39a1c22

Reopen if it still happens.

**Comment by AlexFolland** [comment]
Tested again; can't reproduce.  :)
