### ISSUE TITLE
Tales of Phantasia crash on open

### ISSUE THREAD

**Issue by montiblanc** [libretro/RetroArch#4435]
https://nicoblog.org/psx-iso/tales-of-phantasia-english-patched/

i have all the bios files in system & i cant find the mednafen_psx core github page; or is it the beetle psx page? so confusing.

**Comment by twinaphex** [comment]
Not a RetroArch issue, open this in the mednafen_psx github issue tracker.

**Comment by RobLoach** [comment]
https://github.com/libretro/beetle-psx-libretro
