### ISSUE TITLE
Missing upper cased umlaut in font

### ISSUE THREAD

**Issue by CoalaJoe** [libretro/RetroArch#4437]
## Description

I am working on translations and found out that the upper case ä is not beign displayed.

### Expected behavior

All umlauts should be rendered correctly.

![image](https://cloud.githubusercontent.com/assets/5689499/22011143/c46bfb9a-dc8d-11e6-85c7-17c07c5a51c3.png)
![image](https://cloud.githubusercontent.com/assets/5689499/22011138/b7ff5cbc-dc8d-11e6-8540-6a63cc91fde5.png)

![image](https://cloud.githubusercontent.com/assets/5689499/22011160/e37f7584-dc8d-11e6-8cf3-fc28ac09f227.png)
![image](https://cloud.githubusercontent.com/assets/5689499/22011172/f1261f58-dc8d-11e6-934b-fb17dec02374.png)

### Version/Commit

- RetroArch: [1.4]

### Environment information

- OS: MacOS

**Comment by Kivutar** [comment]
Can you try the font present in Monochrome the default theme please?

**Comment by CoalaJoe** [comment]
They all have the same problem.

**Comment by twinaphex** [comment]
@bparker06 Can you guess what the issue here would be?

**Comment by WeedyWeedSmoker** [comment]
You can close this...

Fixed by commit 43d217668d2414c118bf15c7e46cea797852cb17
