### ISSUE TITLE
Couldn't load files on Tyrquake 1.4.0.

### ISSUE THREAD

**Issue by cucholix** [libretro/RetroArch#4439]
When loading Tyrquake core 1.4.0 enter to the load content menu select either pak1.pak or pak0.pak it doesn't boot any of these just stay in that screen with a message 'no files found' (or something like that) , previous builds didn't have this problem.

**Comment by fr500** [comment]
"something like that" is not a valid way to convey the problem.
This seems like a core issue.

**Comment by fr500** [comment]
Please look for the corresponding repository in https://github.com/libretro and report it there
