### ISSUE TITLE
Start Core still displayed after closing 2048

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4446]
## Description

This is a minor issue where after closing a core like 2048 where there is no content the main tab in xmb will still display `Start Core`. Selecting this will instantly close RetroArch without crashing.

### Expected behavior

After the core (2048) closes it should not display `Start Core`.

### Steps to reproduce the bug

1. Start libretro-2048
2. Close core.
3. Select `Start Core` again.

### Version/Commit

`libretro-2048-2016.12.09_2334b50_master-x86_64-1_git`
`RetroArch-2017.01.17_c78991b6a_master-x86_64-1_git`

### Environment information

- OS: `Slackware64-current`

**Comment by twinaphex** [comment]
This is a known issue yes. Unfortunately it's also not easy to fix.

**Comment by orbea** [comment]
I did not realize, thanks for the info. Its a minor issue honestly though.

**Comment by orbea** [comment]
This issue is fixed in `1.7.0` and the git master so I will close this issue. I'm not sure when it was fixed.
