### ISSUE TITLE
Button layout per-core is not saved. Also the file browser directory is saved but not opened by default.

### ISSUE THREAD

**Issue by ShadowOne333** [libretro/RetroArch#4451]
Good day.
I have tried Jan 17 nightly of the Wii U cores, and they seem to work really except for two details:

1) Whenever I get into any core, for example mGBA, and go to the Quick menu to change the button mapping/layout to change, let's say, Button A in the GBA to button B in the Gamepad, quit RetroArch normally and then go back to the core, the button layour is not saved, instead it goes back to the default layout.

2) In Settings -> Directories, I changed the path of the default file browser to SD:/ROMs/.
The directory seems to be saved, as everytime I go back to any core and check the setting, the path is still there. However, when I go to Load Content, I still start directly from SD:/ instead of the specified SD:/ROMs/ in the Directories settings.

I believe this were the only two issues I encountered so far.
Thank you so much for the effort and time that you guys put into this project!

**Comment by MeisterLLD** [comment]
For your 1., did you try
Settings (not the quick menu) > Input > Player 1 bindings > ... > save remap file ?

**Comment by fr500** [comment]
1. Quick Menu / Controls are NEVER saved, you need to save a core or game remap in that same menu
2. Check favorites
