### ISSUE TITLE
Translating into spanish please

### ISSUE THREAD

**Issue by killer983** [libretro/RetroArch#4452]
Could you offer a translation into spanish

**Comment by RobLoach** [comment]
https://github.com/libretro/RetroArch/blob/master/intl/msg_hash_es.c

Could do with some updates. Help appreciated.

**Comment by killer983** [comment]
Thank you

**Comment by CoalaJoe** [comment]
Don't forget the https://github.com/libretro/RetroArch/blob/master/intl/msg_hash_es.h file. We will migrate the translations from the .c file to the .h file in the future.

**Comment by bparker06** [comment]
Hi @killer983, if you go into Settings -> User -> Language you should be able to switch it to Spanish, the translation @RobLoach linked to is already part of RetroArch.

**Comment by CoalaJoe** [comment]
Can this issue be closed, or is there anything else?
