### ISSUE TITLE
Is the VSync broken on Raspberrypi 3 ?

### ISSUE THREAD

**Issue by frranck** [libretro/RetroArch#4457]
## Description

If I run the advanced_tests_libretro 2B test, the animation is quite shaky on my raspberrypi 3, but If I run the same test core on my 2011 Mac, the movement is fluid.

### Expected behavior

Fluid animation

### Actual behavior

I suspect the VSync to be wrong on raspberrypi

### Steps to reproduce the bug

1. Compile advanced_tests_libretro
2. Move to the second tests with vertical scrolling black and white lines.
3. Observe flickering animation.

### Version/Commit

- RetroArch:  current master version 

### Environment information

- OS: Raspbian and Mac os x
- Compiler: gcc (Raspbian 4.9.2-10) 4.9.2

RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event2 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev]: Plugged pad: USB,2-axis 8-button gamepad   (1411:8288) on port #0.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event0) supports 0 force feedback effects.
RetroArch [INFO] :: Autodetect: 0 profiles found.
RetroArch [INFO] :: Autodetect: no profiles found for USB,2-axis 8-button gamepad   (1411/8288).
RetroArch [INFO] :: [udev]: Plugged pad: USB,2-axis 8-button gamepad   (1411:8288) on port #1.
RetroArch [INFO] :: [udev]: Pad #1 (/dev/input/event1) supports 0 force feedback effects.
RetroArch [INFO] :: Autodetect: 0 profiles found.
RetroArch [INFO] :: Autodetect: no profiles found for USB,2-axis 8-button gamepad   (1411/8288).
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 384 frames
RetroArch [INFO] :: ALSA: Buffer size: 1536 frames
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [/home/pi/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: Loading history file: [/home/pi/.config/retroarch/content_image_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)

**Comment by frranck** [comment]
Sorry I meant "1B"
here is the console output (runned from console only)

pi@raspberrypi:/media/usb/dev/libretro-samples $ ../RetroArch/retroarch -v -L ./tests/test_advanced/advanced_tests_libretro.so
RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Jan 16 2017
RetroArch [INFO] :: Version: 1.4.0
RetroArch [INFO] :: Git: 8aba35e
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Looking for config in: "/home/pi/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Incompatible shader for backend gl, clearing...
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Loading dynamic libretro core from: "/media/usb/dev/libretro-samples/tests/test_advanced/advanced_tests_libretro.so"
RetroArch [INFO] :: Environ SET_SUPPORT_NO_GAME: yes.
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [libretro DEBUG] :: 0123 testRetroArch [libretro DEBUG] :: 0123 testRetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: 0RGB1555.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 30694.40 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [WARN] :: 0RGB1555 pixel format is deprecated, and will be slower. For 15/16-bit, RGB565 format is preferred.
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0x1.
RetroArch [INFO] :: Found GL context: videocore
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
RetroArch [INFO] :: [GL]: Version: OpenGL ES 2.0.
RetroArch [INFO] :: GL: Using resolution 1920x1080
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event1 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev]: Plugged pad: USB,2-axis 8-button gamepad   (1411:8288) on port #0.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event0) supports 0 force feedback effects.
RetroArch [INFO] :: Autodetect: 0 profiles found.
RetroArch [INFO] :: Autodetect: no profiles found for USB,2-axis 8-button gamepad   (1411/8288).
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [INFO] :: ALSA: Using signed 16-bit format.
RetroArch [INFO] :: ALSA: Period size: 384 frames
RetroArch [INFO] :: ALSA: Buffer size: 1536 frames
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [/home/pi/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: Loading history file: [/home/pi/.config/retroarch/content_image_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: VSync => off
RetroArch [INFO] :: [EGL]: eglSwapInterval(0)
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)

**Comment by frranck** [comment]
if I try from X, this it looks as slow, here the X output:

RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Jan 16 2017
RetroArch [INFO] :: Version: 1.4.0
RetroArch [INFO] :: Git: 8aba35e
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Looking for config in: "/root/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Incompatible shader for backend gl, clearing...
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Loading dynamic libretro core from: "/media/usb/dev/libretro-samples/tests/test_advanced/advanced_tests_libretro.so"
RetroArch [INFO] :: Environ SET_SUPPORT_NO_GAME: yes.
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [libretro DEBUG] :: 0123 testRetroArch [libretro DEBUG] :: 0123 testRetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: 0RGB1555.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 30689.31 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [WARN] :: 0RGB1555 pixel format is deprecated, and will be slower. For 15/16-bit, RGB565 format is preferred.
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: [EGL]: Current context: 0x1.
RetroArch [INFO] :: Found GL context: videocore
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: Broadcom, Renderer: VideoCore IV HW.
RetroArch [INFO] :: [GL]: Version: OpenGL ES 2.0.
RetroArch [INFO] :: GL: Using resolution 1920x1080
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Shader log: Compiled
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Querying EGL extension: KHR_image => exists
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
RetroArch [INFO] :: [udev] Adding device /dev/input/event1 as type ID_INPUT_KEYBOARD.
RetroArch [INFO] :: [udev] Adding device /dev/input/event3 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev] Adding device /dev/input/mouse0 as type ID_INPUT_MOUSE.
RetroArch [INFO] :: [udev]: Plugged pad: USB,2-axis 8-button gamepad   (1411:8288) on port #0.
RetroArch [INFO] :: [udev]: Pad #0 (/dev/input/event0) supports 0 force feedback effects.
RetroArch [INFO] :: Autodetect: 0 profiles found.
RetroArch [INFO] :: Autodetect: no profiles found for USB,2-axis 8-button gamepad   (1411/8288).
RetroArch [INFO] :: Found joypad driver: "udev".
RetroArch [ERROR] :: Failed to initialize audio driver. Will continue without audio.
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [ERROR] :: Failed to create rendering backend: freetype.
Failed to open /root/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
RetroArch [ERROR] :: Failed to create rendering backend: stb.
RetroArch [INFO] :: Using font rendering backend: bitmap.
RetroArch [ERROR] :: Failed to create rendering backend: freetype.
Failed to open /root/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
RetroArch [ERROR] :: Failed to create rendering backend: stb.
RetroArch [INFO] :: Using font rendering backend: bitmap.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [/root/.config/retroarch/content_history.lpl].
RetroArch [INFO] :: Loading history file: [/root/.config/retroarch/content_image_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [EGL]: eglSwapInterval(1)
RetroArch [ERROR] :: failed_to_start_audio_driver
RetroArch [ERROR] :: failed_to_start_audio_driver
RetroArch [INFO] :: Saved new config to "/root/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Resetting undo buffers.
RetroArch [INFO] :: Trying to write to playlist file: /root/.config/retroarch/content_history.lpl
RetroArch [INFO] :: Trying to write to playlist file: /root/.config/retroarch/content_image_history.lpl
RetroArch [INFO] :: Average monitor Hz: 50.000000 Hz. (0.717 % frame time deviation, based on 2048 last samples).
RetroArch [INFO] :: Average monitor Hz: 50.000000 Hz. (0.717 % frame time deviation, based on 2048 last samples).

**Comment by bparker06** [comment]
That last log shows it is still using the EGL context and not X11, which is not compatible with X. Did you compile RA yourself? You might need to install X11 development headers and then recompile to enable the X11 context driver.

**Comment by frranck** [comment]
@bparker06 
I just installed "xorg-dev" and did a ./configure then make. but it still doesn't seem to use X, am I missing something ?

**Comment by bparker06** [comment]
Can you paste your configure output?

**Comment by frranck** [comment]
Checking operating system ... Linux 
Checking for suitable working C compiler ... /usr/bin/gcc works
Checking for suitable working C++ compiler ... /usr/bin/g++ works
Checking for pkg-config ... /usr/bin/pkg-config
Checking for availability of switch -std=gnu99 in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-result in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-variable in /usr/bin/gcc ... yes
Checking function bcm_host_init in -lbcm_host ... yes
Checking function sd_get_machine_names in -lsystemd ... no
Checking presence of package egl ... no
Checking existence of -lEGL -lEGL -lGLESv2 -lbcm_host -lvcos -lvchiq_arm ... yes
Checking function ass_library_init in -lass ... no
Checking function pthread_create in -lpthread ... yes
Checking function pthread_key_create in -lpthread ... yes
Checking function dlopen in -ldl ... yes
Checking function socket in -lc ... yes
Checking function getaddrinfo in -lc ... yes
Checking existence of -lminiupnpc ... no
Checking function fcntl in -lc ... yes
Checking function getopt_long in -lc ... yes
Checking presence of package alsa ... 1.0.28
Checking presence of header file sys/soundcard.h ... yes
Checking presence of header file soundcard.h ... no
Checking existence of -lossaudio ... no
Checking function alcOpenDevice in -lopenal ... no
Checking presence of package rsound >= 1.1 ... no
Checking presence of package libroar ... no
Checking presence of package jack >= 0.120.1 ... no
Checking presence of package libpulse ... 5.0
Checking presence of package sdl >= 1.2.10 ... 1.2.15
Checking presence of package sdl2 >= 2.0.0 ... 2.0.4
Notice: SDL drivers will be replaced by SDL2 ones.
Checking presence of package libusb-1.0 >= 1.0.16 ... 1.0.19
Checking presence of header file GL/gl.h ... yes
Checking existence of -lGL ... yes
Checking function cgCreateContext in -lCg ... no
Checking presence of package zlib ... 1.2.8
Checking presence of package libavcodec >= 54 ... no
Checking presence of package libavformat >= 54 ... no
Checking presence of package libavdevice ... no
Checking presence of package libswresample ... no
Checking presence of package libavresample ... no
Checking presence of package libavutil >= 51 ... no
Checking presence of package libswscale >= 2.1 ... no
Checking presence of header file libavutil/channel_layout.h ... no
Notice: FFmpeg built-in support disabled due to missing or unsuitable packages.
Checking function dlopen in -ldl ... yes
Checking presence of package gbm >= 9.0 ... no
Checking presence of package libdrm ... 2.4.71
Checking presence of package libxml-2.0 ... 2.9.1
Checking presence of package glesv2 ... no
Checking existence of -lGLESv2 -lEGL -lGLESv2 -lbcm_host -lvcos -lvchiq_arm ... yes
Checking presence of package vg ... no
Checking existence of -lOpenVG -lEGL -lGLESv2 -lbcm_host -lvcos -lvchiq_arm ... yes
Checking presence of package libv4l2 ... no
Checking presence of package freetype2 ... 18.0.12
Checking presence of package x11 ... 1.6.2
Checking presence of package xcb ... 1.10
Checking presence of package wayland-egl ... no
Checking presence of package wayland-cursor ... no
Checking presence of package xkbcommon >= 0.3.2 ... 0.4.3
Checking presence of package dbus-1 ... 1.8.20
Checking presence of package xext ... 1.3.3
Checking presence of package xxf86vm ... 1.1.3
Checking presence of package xinerama ... 1.1.3
Checking presence of package xv ... 1.0.10
Checking presence of package libudev ... 215
Checking presence of header file linux/parport.h ... yes
Checking presence of header file linux/ppdev.h ... yes
Checking function strlcpy in -lc ... no
Checking function strcasestr in -lc ... yes
Checking function mmap in -lc ... yes
Checking function vkCreateInstance in -lvulkan ... no
Creating make config: config.mk
Creating config header: config.h

**Comment by frranck** [comment]
if i change toin Setting Tab  > Driver > Video to xvideo,
I'm getting this error:

RetroArch [INFO] :: This is RetroArch version 1.4.1 (Git 8114ce7)
RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Feb 16 2017
RetroArch [INFO] :: Version: 1.4.1
RetroArch [INFO] :: Git: 8114ce7
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Looking for config in: "/root/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Loading dynamic libretro core from: "/media/usb/dev/libretro-samples/tests/test_advanced/advanced_tests_libretro.so"
RetroArch [INFO] :: Environ SET_SUPPORT_NO_GAME: yes.
RetroArch [INFO] :: Environ GET_LOG_INTERFACE.
RetroArch [libretro DEBUG] :: 0123 testRetroArch [libretro DEBUG] :: 0123 testRetroArch [INFO] :: Content loading skipped. Implementation will load it on its own.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: 0RGB1555.
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 30689.31 Hz.
RetroArch [INFO] :: Video @ 960x720
RetroArch [WARN] :: 0RGB1555 pixel format is deprecated, and will be slower. For 15/16-bit, RGB565 format is preferred.
RetroArch [ERROR] :: XVideo: Failed to find valid XvPort or format.
RetroArch [ERROR] :: Cannot open video driver ... Exiting ...
RetroArch [ERROR] :: Fatal error received in: "init_video()"
RetroArch [ERROR] :: This core requires a content file.

**Comment by frranck** [comment]
I could fix my problem, by changing these parameters in  /boot/config.txt

# uncomment to force a specific HDMI mode (this will force VGA)
hdmi_group=1
hdmi_mode=4

I used to get
pi@raspberrypi:~ $ fbset -s

mode "1280x720"
    geometry 1280 720 1280 720 16
    timings 0 0 0 0 0 0 0
    rgba 5/11,6/5,5/0,0/16
endmode

now i get 60hz and this:

fbset -s

mode "1280x720"
    geometry 1280 720 1280 720 16
    timings 0 0 0 0 0 0 0
    rgba 5/11,6/5,5/0,0/16
endmode
