### ISSUE TITLE
Support for ps4

### ISSUE THREAD

**Issue by killer983** [libretro/RetroArch#4458]
You could support ps4 for 1.4.0

**Comment by twinaphex** [comment]
What is this '1.4.0' you refer to?

**Comment by killer983** [comment]
The next update is not the 1.4.0 you could give support in ps4 to use the emulators

**Comment by Alcaro** [comment]
> The next update is not the 1.4.0

What do you know about our release schedule that we don't

**Comment by fr500** [comment]
I have my magic wand handy, not sure if that will make the port happen though

**Comment by killer983** [comment]
Thanks

**Comment by Alcaro** [comment]
can someone explain what exactly is going on in this issue

**Comment by fr500** [comment]
@killer983 porting to a platform is not trivial, it takes weeks of dedication, and that when the hardware is available and open.

Without a (hacked) PS4 and the toolset required it won't happen.

**Comment by russhdavid** [comment]
As of now July 2, 2018, there's an available hack for the PS4 in version 5.05 I know that porting takes a lot of work and dedication. But I will expect to see Retroarch as a homebrew for the PS4 in the future. Keep it up with the hard work guys. Thanks.

**Comment by Nube79** [comment]
this link can help
https://www.psxhax.com/threads/unity-ps4-hen-compilation-demo-by-retrogamer74.5184/page-5
