### ISSUE TITLE
UI issue - Saving state shows text "loading state" them "saving state"

### ISSUE THREAD

**Issue by pralima87** [libretro/RetroArch#4460]
Small annoying issue were saving first shows text "loading state" (0-100%) them "saving state" (0-100%).
Tested on 1.40.

**Comment by twinaphex** [comment]
This happens on every RetroArch version  right now, not just Vita. So yeah, it's a bug.

**Comment by fr500** [comment]
I think it's because the undo save states. It actually saves (to ram) but if it's for undo purposes maybe it should suppress the message.

**Comment by frangarcj** [comment]
It should be fixed

Could you check it @pralima87 ?

**Comment by pralima87** [comment]
Si!!!

**Comment by bparker06** [comment]
@frangarcj What commit supposedly changed this functionality?

**Comment by frangarcj** [comment]
Misread the issue. I thought it was related to vita io speed that was fixed recently. Sorry

**Comment by Tatsuya79** [comment]
Radius is right, it's about the undo savestate function.

[Removing the "if" content here](https://github.com/libretro/RetroArch/blob/master/tasks/task_save.c#L1148) to go directly to the "else" part makes the load message disappear when we're saving a state.

**Comment by rz5** [comment]
This was my fault as I implemented the feature. Thanks for the fix @Tatsuya79
