### ISSUE TITLE
[Vita] GPSP Core Random Stuttering

### ISSUE THREAD

**Issue by pralima87** [libretro/RetroArch#4462]
This issue started with the release of a dynarec update/patch for this core.
The core will stutter randomly causing audio and video lagging. 
Problem still persists in 1.40.

**Comment by retro-wertz** [comment]
> use the guidelines when submitting and issue---do not delete it...

**Comment by pralima87** [comment]
Sorry but I'm not sure I understand what do you mean by that mr.retro-wertz

**Comment by fr500** [comment]
When you clicked the new issue button, there were some instructions regarding reporting issues.
You just skipped them, removed and reported an issue anyway.
