### ISSUE TITLE
ios - apple:  Can't get a working version since 12-14

### ISSUE THREAD

**Issue by Cepheidsong** [libretro/RetroArch#4468]
Hello.  Using Retroarch on iphone 9.3.3 jailbreak

Since the cydia went down on 12-14 I haven't been able to get a working version past the stable one posted in July of '16 of 1.3.6.  That download works, but anything beyond that posted on the download section doesn't seem to work for me.  (I know there has been some good updates since then, that's why been trying to update)

The 1.3.6 version is a .deb which is probably why I got it working, the rest are all posted as .zip which unzip into retroarch.app folder.  I've tried putting any verison of the nightly, or the 1.4.0 in the applications but it just crashes instantly upon loading.

Am I missing some certain instructions how to do that properly, or is there a way to get a .deb file of any of the current updates posted in the downloads sections (since I had heard before the forums went down the cydia updater isn't working)

**Comment by Alex793** [comment]
Yep you are not alone, me and some other people. Test on two iPad jailbreaked on iOS 9.3.3. Checked permissions etc. but crash at launch...

Hope a fix.

**Comment by Cepheidsong** [comment]
So I found an alternate way to install the .app from the zip, and again only the last stable 1.3.6 works, none of the others posted from the nightly or the 1.4.0 works.  I know the version of the nightly posted before the one up there from 12-14-16 worked, but isn't available for download.

**Comment by Alex793** [comment]
Same boat my friend but still no fix, even on libretro forum no any reply...

**Comment by orbea** [comment]
Can someone use git to bisect this to see what commit broke this? Unless IOS users take the initiative in helping debug or solve this I doubt it will ever be fixed...
