### ISSUE TITLE
Can't exit to menu when using the 8bitdo n64 controller

### ISSUE THREAD

**Issue by CoalaJoe** [libretro/RetroArch#4469]
### Steps to reproduce the bug

1. Use that controller

### Version/Commit
 - RetroArch 1.4

### Environment information

- OS: Lakka

**Comment by fr500** [comment]
Solution: bind a button to home.

**Comment by CoalaJoe** [comment]
Well. But that is not plug and play for upcomming lakka gamers.

**Comment by fr500** [comment]
Are there any spare buttons?

**Comment by CoalaJoe** [comment]
No there are not.

**Comment by CoalaJoe** [comment]
Maybe a comnbination like. L + R + Start would work.

**Comment by bparker06** [comment]
@CoalaJoe You can choose a combination in Settings -> Input -> Menu Toggle Gamepad Combo.

**Comment by CoalaJoe** [comment]
@bpaker06 I know. None of them work because of the missing buttons.
![image](https://cloud.githubusercontent.com/assets/5689499/22278465/05d1afbc-e2c4-11e6-8a21-f2c77b43ab36.png)
There is no Y-Button

![image](https://cloud.githubusercontent.com/assets/5689499/22278476/12352248-e2c4-11e6-9bfd-c7d9cd3f1451.png)
There is no L3 nor R3.

![image](https://cloud.githubusercontent.com/assets/5689499/22278481/19b8a490-e2c4-11e6-94b1-fe35e269c896.png)
There is no Select.

![image](https://cloud.githubusercontent.com/assets/5689499/22278489/22bc325a-e2c4-11e6-8679-aa827aae74a9.png)
Still missing the Select-Button

**Comment by fr500** [comment]
There is no way to set the combo for an autoconf profile either.
Anyhow this is hardly a retroarch bug, the pad doesn't have enough buttons. 

I'd remove the first and make it L + R + Start.

**Comment by CoalaJoe** [comment]
That sound ok to me.

**Comment by gouchi** [comment]
@CoalaJoe This issue could be closed ?

Thank you.
