### ISSUE TITLE
Build error on Arch RBP3

### ISSUE THREAD

**Issue by martinstark** [libretro/RetroArch#4470]
## Expected behavior

RetroArch to build.

### Actual behavior

```
CC gfx/drivers/vg.c
gfx/drivers/vg.c: In function 'vg_calculate_quad':
gfx/drivers/vg.c:307:19: error: 'height' undeclared (first use in this function)
          vg->y2 = height;
                   ^~~~~~
gfx/drivers/vg.c:307:19: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:147: obj-unix/gfx/drivers/vg.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

==> ERROR: the build failed
  -> Status
	failed (1): retroarch-rbp-git
```

### Steps to reproduce the bug

1. Follow guide here: https://github.com/RetroPie/RetroPie-Setup/wiki/RetroPie-Arch-Linux-Flavor
2. get to _apacman -S retroarch-rbp-git_
3. run into error at _==> Starting build()..._

### Version/Commit
You can find this information under Information/System Information

- RetroArch: commit dd1fa96321a542591f4474f19a8c4acb276b7afb

### Environment information

- OS: Arch Linux ARM

**Comment by twinaphex** [comment]
Pushed buildfix.

https://github.com/libretro/RetroArch/commit/b97b40af75ca72425a76124d3366315d1a6feb57

**Comment by martinstark** [comment]
Fixed
