### ISSUE TITLE
No-content cores do not always save correctly

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4473]
## Description

RetroArch has problems saving no-content cores under the following conditions.

1. The save / system directory is read-only.
2. The option 'Sort Saves In Folders' is used (i.e. 2048 tried to save in the GLupeN64 directory)

This is especially problematic for any distros trying to package RetroArch where it is standard to install cores to a read-only directory (i.e. `/usr/lib/libretro/`).

### Expected behavior

I am unsure what the best behavior is, but here are some ideas.

1. If the save and system directories are read-only then fall back to directories that are writable, for example in `~/.config/retroarch/saves` and `~/.config/retroarch/system`.
2. Make sure all content-less cores use the system directory instead of save directory and allow anyone installing to a read only directory to set the system directory to `~/.config/retroarch/system` for example. (Can `/etc/retroarch.cfg` properly do this already?)

### Steps to reproduce the bug

1. Install 2048 to a read-only directory.
2. Run the core: `retroarch -L 2048_libretro.so`
3. It will not save unless the save directory is set and if `Sort Saves In Folders` is used it will do so in the wrong location.

### Bisect Results

This is an old problem, see https://github.com/libretro/libretro-2048/issues/4.

### Version/Commit

`RetroArch-2017.01.19_de4e3cc77_master-x86_64-1_git`

### Environment information

- OS: `Slackware64-current`

**Comment by orbea** [comment]
@fr500 As far as distros and 2048 is concerned this bug is not minor. I unfortunately will not be able to satisfactorily provide 2048 for slackware until it can save properly... I tried to work around it in the referenced PR, but I guess that idea was not that good anyways...

**Comment by fr500** [comment]
It's minor because it's not a crash or segfault.

**Comment by orbea** [comment]
Thanks to commit https://github.com/libretro/RetroArch/commit/ca926f0a50e5759380cdc89b8603224de944271c it will save correctly if the save dir is set, but it will still have problems if it tries to use the content dir while not having write permissions.

**Comment by fr500** [comment]
the problem is that there is no content dir on contentless cores...
we need to come up with a decent fallback but not sure what it would be

**Comment by orbea** [comment]
A fall back save dir in ~/.config/retroarch might be good enough?

**Comment by fr500** [comment]
that's not a thing for all platforms though

**Comment by orbea** [comment]
Good point...
