### ISSUE TITLE
Loading core with -L, core doesn't show up as "current core" in suggested cores

### ISSUE THREAD

**Issue by SedrynTyros** [libretro/RetroArch#4474]
## Description

When I use the -L switch, RetroArch loads the specified core at launch.  However, when I Load Content and select a ROM in doesn't show the loaded core as "Current core" at the Suggested Cores screen.  This is the latest RetroArch Windows x86_64 build.  I'm running RetroArch in Windows 10 Pro.

### Expected behavior

When the -L switch is used to load a core it should show up as the "Current core" in the Suggested Cores screen (and be selected by default) after you select a ROM.

### Actual behavior

Instead, it behaves as if there's no loaded core even though you can see the core as loaded in the lower left of the GUI.

### Steps to reproduce the bug

Launch RetroArch with -L and whatever you core you want.  Then try to load a ROM for that system.  When you get to the Suggested Cores screen you'll see that it behaves as if no core is loaded and you'll see nothing is selected as "Current core".

### Bisect Results

This is the first development build I've tried in over 6 months and the first time I've seen the Suggested Cores feature so I have no idea when this started happening.  It could be how it has worked since the Suggested Cores feature was added to Load Content.  

### Version/Commit

- RetroArch: Git version a7b26d8

### Environment information

- OS: Windows 10 Pro

**Comment by hizzlekizzle** [comment]
I was not able to reproduce in Linux 64-bit. It shows the currently loaded core when I try it.

**Comment by SedrynTyros** [comment]
Confirmed the bug is still present in RetroArch v1.4.1 Windows x86_64 released on February 2nd.

**Comment by AlexFolland** [comment]
@SedrynTyros  Please make sure that when you're testing, you're using the latest git commit available, or at the very least, the latest nightly.

**Comment by SedrynTyros** [comment]
@AlexFolland : okay, will do for the future.

Related question on this bug; are there any config options that affect this new Suggested Cores feature?

**Comment by SedrynTyros** [comment]
Confirmed this issue is still outstanding as of build bd0125

**Comment by SedrynTyros** [comment]
Well, I'm using RetroArch v1.6.0 and this issue is back again so I'm going to re-open for now and test with the last nightly when I get a chance

**Comment by orbea** [comment]
@SedrynTyros Can you try this again? I also can't reproduce it with the current master and linux.

**Comment by SedrynTyros** [comment]
Figured out the trick to getting Current Core in Suggested Cores to work is to load the core without path information (so it needs to be a core in the Cores folder). The trick to using custom configurations seems to be for the CFG files to be stored in the root of the RetroArch program folder rather than a subfolder so they too can be loaded from the commandline without additional path information.

I was doing some fancy things with shortcuts and what not and I think that's why I was having the problem.
