### ISSUE TITLE
4:3 window displaying through the XMB on 16:9 screen at startup

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#4478]
## Description

Upon startup in Exclusive Fullscreen (Windows 10) and setting a custom wallpaper, Retroarch shows an underlying lighter-colored picture with an aspect ratio of 4:3 through the XMB.

On 16:9 screens this creates the effect of having borders on the sides on the XMB, as if the Menu was called after pausing some 4:3 content.

### Expected behavior
http://imgur.com/a/7lTsN

### Actual behavior
http://imgur.com/a/YUEt0
(please disregard the faded color of the font here. Icons and text are displayed perfectly when actually running RA, but the borders on the side are there).

### Steps to reproduce the bug

On my Windows 10 x64 build:
1. Disable Shader Pipeline
2. Set a custom wallpaper with low opacity (mine is at 0.410)
3. Start Retroarch

The issue disappears entirely when toggling between Windowed and Fullscreen mode.

### Bisect Results
This started happening with today's commits, but I haven't yet attempted a bisect.

### Version/Commit
- RetroArch: 1.40/1ea3bea

### Environment information

- OS: Windows 10 x64
- Compiler: MINGW64

**Comment by Ryunam** [comment]
After bisecting and testing, it seems that this has started happening with d4b7edff4a39550da3529087f27762108c3be434.

**Comment by twinaphex** [comment]
This should fix the issue for GL and Vulkan I believe -

https://github.com/libretro/RetroArch/commit/8698525f867585e6d2e71ad57cbf5bdde2b321a6

**Comment by Ryunam** [comment]
I can confirm this is now fixed on my end with GL. Thanks a lot!

**Comment by twinaphex** [comment]
Should be fixed now hopefully with this - sorry for the inconvenience  -

https://github.com/libretro/RetroArch/commit/a104c737388542c806ebe5ec6cdeed9126f2e835
