### ISSUE TITLE
Request: Rotation of a shader for vertical games

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#448]
Vertical games in Mame have horizontal scanlines.
Perhaps Retroarch could rotate the shader effect when the Mame core uses a particular vertical screen ratio.

**Comment by GeneralFailer** [comment]
Sorry, but why was this closed? Even just a manual shader rotation option would be quite cool.

**Comment by dankcushions** [comment]
the crt-pi shader at least respects the orientation of the game. the scanlines are vertical in vertical games. there is shadow mask effect that is not rotated, but as far as i'm aware it's because it's too computationally expensive for the shader. but it's not a libretro problem...
