### ISSUE TITLE
Only Player 1 works in all cores

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#4487]
## Description

Player 2 does not work in any core

### Expected behavior

Player 2 should work just as Player 1 does

### Actual behavior

Player 2 controller is unresponsive. Player 2 also cannot exit the core with the configured key combination.

### Steps to reproduce the bug

2 controllers connected via usb to device. Launch retroarch with player 1, select core, select content. Player 2 will not work. Happens with "All users control menu" off and on.

### Bisect Results

If a button on Player 2 is pressed repeatedly during startup of core with content it will be responsive in the core. Do note, this sometimes causes Player 2 to be as Player 1 in the core. Issue persists in all cores tested.

### Version/Commit

- RetroArch: 1.4.0 from 1/16/17 - Android build

### Environment information

- OS: Amazon Fire TV
- Compiler: n/a

**Comment by fr500** [comment]
Seems exclusive to your device.
You didn't list which controllers

**Comment by orbea** [comment]
Given that the original user account has been deleted and that there hasn't been any recent activity I am going to close this issue. Someone please complain if this is still an issue.
