### ISSUE TITLE
update translation to spanish

### ISSUE THREAD

**Issue by killer983** [libretro/RetroArch#4488]
NetPlay - juego en Red
Start NetPlay host - iniciar el juego en red
Connect to NetPlay host - conectarse al juego en red
Disconnect to NetPlay host - desconectarse del juego en red
scan local network - escanear la Red local

**Comment by CoalaJoe** [comment]
Should NetPlay really be translated. It is it's own term.

**Comment by killer983** [comment]
Ok

**Comment by CoalaJoe** [comment]
@killer983 But "Start Netplay host", "Connect to NetPlay host", "Disconnect to NetPlay host" and "Scan local network" can be translated. You may need to keep the word "NetPlay".
