### ISSUE TITLE
New translation into Galician

### ISSUE THREAD

**Issue by killer983** [libretro/RetroArch#4489]
Load Core- cargar nucleo
load contento - cargar contenido
load recent - cargado recientemente 
online updater - actualizador online
NetPlay - xogo en rede
Start NetPlay host - iniciar conexión na rede
Connect to NetPlay host - conectarse a rede
Disconnect to NetPlay host - desconectarse da rede
scan local network - escanear red local
Information - información 
Configuration - configuración 
Help - axuda
Quit Retroarch - quitar RetroArch
scan directory -  escaneo de directorio
scan file - escanear archivo
driver - controladores
Video - video
audio - audio
Input - entrada
Core - nucleo
configuration - configuración 
saving - gardar
Logging - cargar
Frame thottle - fotogramas
User interfaces - interfaz de usuario
archievements - logros
network - red
Playlisy - lista de reproducion
user - usuario
Directory - directorio
Privacy - privacidade

**Comment by killer983** [comment]
Input driver - controlador de entrada
Joypad driver - contolador del joypad
video driver - contolador de video
audio driver - controlador de audio
audio resampler driver - controlador de audio ensamblado
camera driver - controlador de camera
Localitation driver - controlador de localización
Menu driver - controlador de menú
Record driver - controlador de grabacion
wifi driver - controlador de wifi
display framerate - visualizado de fotogramas
Monitor index - índice de monitor
vertical refresh rate - tiempo refresco vertical
estimado screen framerate - fotogramas estimados en pantalla

**Comment by CoalaJoe** [comment]
I don't think we should translate core into another language. It is a kind of special term.

**Comment by fr500** [comment]
That's no way to submit a translation though. 
Please send a pull request, this won't be added like this.

**Comment by CoalaJoe** [comment]
@killer983 If you can't get it to work. You can send the translations to me via email and I will add them in a Pull-Request.
