### ISSUE TITLE
[3DS] CPS2 not loading content 

### ISSUE THREAD

**Issue by Tonysinbox** [libretro/RetroArch#4491]
## Description

Conent dosen't load or crashes with the same error

### Expected behavior

To load into the game 

### Actual behavior

Doesn't load in 1.4 or crashes is using an older build like 1.3.1 RetroArch [INFO] :: Does not have enough samples for monitor refreshrate estimation. Required to run for at least 4096 frames 

- RetroArch: 1.4 and 1.3.1

**Comment by fr500** [comment]
If it's not a rom issue, it's most likely a FBA issue, look for the proper repo here:
https://github.com/libretro
