### ISSUE TITLE
RetroArch is not compiling right... (RetroPie)

### ISSUE THREAD

**Issue by PokeEngineer** [libretro/RetroArch#4495]
## Description

RetroArch is not compiling right on RPI 3 due to a issue with the file "obj-unix/gfx/drivers/dispmanx_gfx.c".
I suspect it has to do with [this commit](https://github.com/libretro/RetroArch/commit/0e542037d896848bfdd6443cbcd422010b00d77e).

### Expected behavior

To be able to fully compile.

### Actual behavior

[Here is the log on PasteBin](http://pastebin.com/YHPJ8qhe).

### Steps to reproduce the bug

Compile on RPI 3 using the following flags: --disable-x11 --enable-opengles --disable-ffmpeg --disable-sdl --enable-sdl2 --disable-oss --disable-pulse --disable-al --disable-jack --enable-dispmanx --enable-floathard --enable-neon

### Bisect Results

This started happening when I was compiling around 10:00PM EST from when this issue was posted. This just started happening today, as the last time I compiled RetroArch was yesterday...

### Version/Commit

- RetroArch: commit 793c894abb53a6f1154e089fa2284eca0b9c4180

### Environment information

- OS: Raspbian Jessie w/RetroPie
- Compiler: GCC

**Comment by loganmc10** [comment]
@twinaphex this is the actual error from the compile:

```
gfx/drivers/dispmanx_gfx.c: In function 'dispmanx_surface_update':
gfx/drivers/dispmanx_gfx.c:337:4: error: unknown type name 'settings_t'
    settings_t *settings = config_get_ptr();
    ^
gfx/drivers/dispmanx_gfx.c:337:4: warning: implicit declaration of function 'config_get_ptr' [-Wimplicit-function-declaration]
gfx/drivers/dispmanx_gfx.c:337:27: warning: initialization makes pointer from integer without a cast
    settings_t *settings = config_get_ptr();
```

**Comment by PokeEngineer** [comment]
Alright, it compiles now thanks to some new commits!
