### ISSUE TITLE
Loaded Remap file not applied

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#4499]
When you already have a core remap applied on start (ex. FB Alpha 2012.rmp) and you go into the menu to load another particular remap (SF2_style_pad.rmp) it is no applied.

If you reset (retropad start / kb space) "the load remap file" entry in Control Menu,
then load that remap, it works.

It shouldn't need this extra step.

win7 x64

**Comment by fr500** [comment]
what if you don't have an auto remap applied and try to load two different remaps in sucession?

**Comment by Tatsuya79** [comment]
The second one loaded is ignored.

**Comment by fr500** [comment]
Yep, confirmed

**Comment by Tatsuya79** [comment]
It's still happening, the 2nd one loaded isn't applied.
I'm on the most recent build with your new commits.

**Comment by fr500** [comment]
I tried loading two remaps one after another and it worked fine for me

**Comment by Tatsuya79** [comment]
Does not work for me, the 2nd one is ignored.
I tested with fbalpha, I load ["FB Alpha.rmp" 1st, then "sf2cejc.rmp"](https://mega.nz/#!N41EwBgZ!oPt0-8DQ26T88WzMobV2NfjTt0gYdUC1tbzr6cxrxQA) and that last one does not apply.

It works fine [if I change that line](https://github.com/libretro/RetroArch/blob/master/input/input_remapping.c#L51) into input_remapping_set_defaults(true);
