### ISSUE TITLE
Can't move left and right while on netplay rooms

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4501]
## Description

When browsing netplay rooms you can't move left and right unless you go back to the first entry

### Expected behavior

It should move left and right like on any other list

### Steps to reproduce the bug

1. Refresh rooms
2. Move down
3. Press left or right

### Version/Commit
You can find this information under Information/System Information

- RetroArch: master

**Comment by twinaphex** [comment]
https://github.com/libretro/RetroArch/commit/ba279ed7acfefed2f7a5281609d32b7df9019bdf

Should be fixed now.
