### ISSUE TITLE
Moving left or right while refreshing rooms causes issues

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4502]
## Description

Moving left or right while refreshing rooms causes issues the async entries to pop up in the wrong list

### Expected behavior

It shouldn't show anything unless it's under rooms

### Steps to reproduce the bug

1. Click refresh rooms
2. Press right immediatly
3. Wait

**Comment by twinaphex** [comment]
Should be fixed now -

https://github.com/libretro/RetroArch/commit/ba279ed7acfefed2f7a5281609d32b7df9019bdf
