### ISSUE TITLE
Wii U - Tyrquake 1.4.0 "no items" issue

### ISSUE THREAD

**Issue by cucholix** [libretro/RetroArch#4505]
It should load either pak0.pak or pak1.pak, but every time you try load them it says "no items". 

There's no crash, black screen, or code dump, you can navigate normally after that, this issue has been present there since stable 1.3.6 from there even nightlies have this issue.

I'm testing it on Wii U, Tyrquake 1.4.0

**Comment by roflcopter777** [comment]
Can you try to narrow the build where it stopped working?

**Comment by cucholix** [comment]
I have a working copy of Tyrquake, but I'm not sure what date it's from.

The core is:
1.3.6 - TyrQuake v0.62, according the file it was modified las time november 23 ‏‎7:24:24 it's working on my end. I attached it
