### ISSUE TITLE
Thumbnails with character "&" in the name doesn't show

### ISSUE THREAD

**Issue by spogghi** [libretro/RetroArch#4507]
## Description

Thumbnails with the character "&" in the name doesn't show up.

### Expected behavior

Having the thumbnail on the right side of the screen while I browse my games list.

### Actual behavior

No thumbnail is displayed.

### Steps to reproduce the bug

1. Add a game which contains the character "&" (like the NES game "Advanced Dungeons & Dragons - DragonStrike (USA)");
2. Put the right thumbnail in the folder;
3. No thumbnail is displayed.

### Version/Commit

- RetroArch: 1.4.0 Git Version: 2c97e33

### Environment information

- OS: Windows 10 x64

**Comment by bparker06** [comment]
Are you referring to the thumbnails displayed in the playlist? Because that is working for me:

https://s3.amazonaws.com/bparker/raf.png

**Comment by spogghi** [comment]
Precisely, except that it doesn't work for me. The names of the rom and of the thumbnail are exactely the same and the error just happens with files that have "&" in the name, i suppose it can't be a coincidence.

**Comment by retro-wertz** [comment]
this has been changed months ago. RA will read "_" from & character from
the playlist when reading from the thumbnails, so rename you thumbnail
files accordingly. check the repo for samples or get them there in stead.

**Comment by fr500** [comment]
So this is just a behavioral change?

**Comment by spogghi** [comment]
This behaviour appears with the thumbnails of the repo (maybe the thumbnails on the repo itself should be renamed?).

**Comment by RobLoach** [comment]
This is documented over at https://github.com/libretro/libretro-thumbnails#thumbnail-repository-layout ...

> The following characters in playlist titles must be replaced with _ in the corresponding thumbnail filename:
    ```
    &*/:`<>?\|
    ```

**Comment by RobLoach** [comment]
This could likely be closed.... Replace & with a _

**Comment by pralima87** [comment]
Really so I need to rename each ROM? This is very conter-intuitive ;(
