### ISSUE TITLE
--no-patch argument seems to be broken.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#4527]
I tested it on the snes9x and mgba cores, with a .ips and .bps files respectively. I *didn't* specify the --bps or --ips switches, they're loading from same named files as the rom files. RA version is

RetroArch: Frontend for libretro -- v1.4.0 -- e3d7018 --
Compiler: GCC (5.4.0) 64-bitBuilt: Jan 28 2017

This is from the unstable ppa.

both ignored the --no-patch argument and loaded the softpatches anyway. I *think* this worked recently with the argument in any position (i tried both before and after the rom).

**Comment by i30817** [comment]
I also found something pretty funky about the args parser. At least here:

`retroarch --no-` or `retroarch --no-p(atch)`

Will actually not present a parser error. But if you vary the match say:

`retroarch -no-w` or `retroarch -no`

The error is present again.

**Comment by orbea** [comment]
Closing this in favor of https://github.com/libretro/RetroArch/issues/5885, you seem to have opened this issue twice. :)
