### ISSUE TITLE
where to get the bios files for each different core

### ISSUE THREAD

**Issue by lilongyueexedream** [libretro/RetroArch#4529]
I am not sure that for each core we need different BIOS files?
Like for mame2003 mame2014  cores we need different bios files when play some of the games?
Where to get all these bios files for my android device?

**Comment by lilongyueexedream** [comment]
@maddox @diegoviola @diegoviola @igungor @notaz @RobLoach   ,can anyone help me ?

**Comment by twinaphex** [comment]
Wrong use of the issue tracker here
