### ISSUE TITLE
Menubar corrupted in window mode

### ISSUE THREAD

**Issue by waitingmoon** [libretro/RetroArch#4536]
![menubar](http://i.imgur.com/6mRtPqq.png)

Version RetroArch 1.4.0

OS: Windows 10 Pro 64bit

**Comment by bparker06** [comment]
Does your system have a Japanese locale set? If so this is a known issue with nightlies from the buildbot. If you compile RetroArch manually, the issue goes away. I haven't been successful in finding the cause yet.

**Comment by waitingmoon** [comment]
Oh, it is just Japanese. I do not have the skill to compile RetroArch by myself, so wait patiently for the issue to be resolved. If there is no problem, please close this issue.
