### ISSUE TITLE
(Docs) Add Emscripten Docs

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#4539]
## Description

We're missing some documentation on how to get up and running with Emscripten.

### Expected behavior

Should have a clear method in which to load and run emscripten locally.

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
- You compile the cores normally except that you use emmake
emmake make -f whatever -j8
- Copy the resulting bc files to the dist-scripts folder under retroarch's source tree
- Run emmake dist-cores.sh emscripten
- Copy the pkg/emscripten cores (js) and memory initialization modules (js.mem) to a folder
- Copy the rest of the stuff to the same folder
- publish with nginx or whatever... even file:/// might work

References:
https://github.com/libretro/libretro-super/blob/master/libretro-buildbot-recipe.sh#L1838
https://github.com/libretro/libretro-buildbot/blob/master/buildbot-emscripten#L63

**Comment by digdug82** [comment]
I'm trying to compile and getting this, any help would be aperciated.
C:\Emscripten\emscripten\1.35.0\crap\RetroArch>emmake make -f Makefile.emscripte
n -j8
The system cannot find the path specified.
CC frontend/frontend.c
CC frontend/frontend_driver.c
CC frontend/drivers/platform_null.c
CC ui/ui_companion_driver.c
CC ui/drivers/ui_null.c
CC ui/drivers/null/ui_null_window.c
CC ui/drivers/null/ui_null_browser_window.c
CC ui/drivers/null/ui_null_msg_window.c
CC ui/drivers/null/ui_null_application.c
CC core_impl.c
CC retroarch.c
CC dirs.c
CC paths.c
CC input/input_keyboard.c
CC command.c
CC msg_hash.c
CC intl/msg_hash_us.c
CC runloop.c
CC libretro-common/queues/task_queue.c
CC tasks/task_content.c
CC tasks/task_save.c
CC tasks/task_file_transfer.c
CC tasks/task_image.c
CC libretro-common/encodings/encoding_utf.c
CC libretro-common/encodings/encoding_crc32.c
CC libretro-common/lists/file_list.c
CC libretro-common/lists/dir_list.c
CC libretro-common/file/retro_dirent.c
CC libretro-common/streams/file_stream.c
CC libretro-common/streams/interface_stream.c
CC libretro-common/streams/memory_stream.c
CC libretro-common/file/retro_stat.c
CC libretro-common/lists/string_list.c
CC libretro-common/string/stdstring.c
CC libretro-common/memmap/memalign.c
CC setting_list.c
CC list_special.c
CC libretro-common/file/nbio/nbio_stdio.c
CC libretro-common/file/file_path.c
CC file_path_special.c
CC file_path_str.c
CC libretro-common/hash/rhash.c
CC audio/audio_driver.c
CC input/input_driver.c
CC gfx/video_coord_array.c
CC gfx/video_driver.c
CC camera/camera_driver.c
CC wifi/wifi_driver.c
CC location/location_driver.c
CC driver.c
CC configuration.c
CC libretro-common/dynamic/dylib.c
CC dynamic.c
CC cores/dynamic_dummy.c
CC libretro-common/queues/message_queue.c
CC managers/state_manager.c
CC gfx/drivers_font_renderer/bitmapfont.c
CC tasks/task_autodetect.c
CC input/input_autodetect_builtin.c
CC input/input_joypad_driver.c
CC input/input_config.c
CC input/input_keymaps.c
CC input/input_remapping.c
CC tasks/task_overlay.c
CC input/input_overlay.c
CC libretro-common/queues/fifo_queue.c
CC managers/core_option_manager.c
CC libretro-common/compat/compat_fnmatch.c
CC libretro-common/compat/compat_posix_string.c
CC managers/cheat_manager.c
CC core_info.c
CC libretro-common/file/config_file.c
CC libretro-common/file/config_file_userdata.c
CC tasks/task_screenshot.c
CC tasks/task_powerstate.c
CC libretro-common/gfx/scaler/scaler.c
CC gfx/drivers_shader/shader_null.c
CC gfx/video_shader_driver.c
CC gfx/video_shader_parse.c
CC libretro-common/gfx/scaler/pixconv.c
CC libretro-common/gfx/scaler/scaler_int.c
CC libretro-common/gfx/scaler/scaler_filter.c
CC gfx/font_driver.c
CC gfx/video_filter.c
CC libretro-common/audio/resampler/audio_resampler.c
CC libretro-common/audio/dsp_filter.c
CC libretro-common/audio/resampler/drivers/sinc_resampler.c
CC libretro-common/audio/resampler/drivers/nearest_resampler.c
CC libretro-common/audio/resampler/drivers/null_resampler.c
CC location/drivers/nulllocation.c
CC camera/drivers/nullcamera.c
CC wifi/drivers/nullwifi.c
CC gfx/drivers/nullgfx.c
CC audio/drivers/nullaudio.c
CC input/drivers/nullinput.c
CC input/drivers_hid/null_hid.c
CC input/drivers_joypad/null_joypad.c
CC playlist.c
CC movie.c
CC record/record_driver.c
CC record/drivers/record_null.c
CC libretro-common/features/features_cpu.c
CC performance_counters.c
CC verbosity.c
CC audio/drivers_resampler/cc_resampler.c
CC libretro-common/compat/compat_getopt.c
CC libretro-common/compat/compat_strcasestr.c
CC libretro-common/compat/compat_strl.c
CC libretro-common/formats/image_texture.c
CC libretro-db/bintree.c
CC libretro-db/libretrodb.c
CC libretro-db/query.c
CC libretro-db/rmsgpack.c
CC libretro-db/rmsgpack_dom.c
CC database_info.c
CC tasks/task_database.c
CC tasks/task_database_cue.c
CC frontend/drivers/platform_emscripten.c
CC input/drivers/rwebinput_input.c
CC audio/drivers/rwebaudio.c
CC camera/drivers/rwebcam.c
CC libretro-common/audio/conversion/s16_to_float.c
CC libretro-common/audio/conversion/float_to_s16.c
CC libretro-common/audio/audio_mix.c
CC libretro-common/formats/wav/rwav.c
CC menu/drivers/rgui.c
CC menu/drivers/materialui.c
CC menu/drivers/zarch.c
CC menu/drivers/xmb.c
CC menu/menu_driver.c
CC menu/menu_content.c
CC menu/menu_input.c
CC menu/menu_event.c
CC menu/menu_entries.c
CC menu/menu_navigation.c
CC menu/menu_setting.c
CC menu/menu_shader.c
CC menu/widgets/menu_filebrowser.c
CC menu/widgets/menu_dialog.c
CC menu/widgets/menu_input_dialog.c
CC menu/widgets/menu_input_bind_dialog.c
CC menu/widgets/menu_entry.c
CC menu/widgets/menu_list.c
CC menu/widgets/menu_osk.c
CC menu/menu_cbs.c
CC menu/cbs/menu_cbs_ok.c
CC menu/cbs/menu_cbs_cancel.c
CC menu/cbs/menu_cbs_select.c
CC menu/cbs/menu_cbs_start.c
CC menu/cbs/menu_cbs_info.c
CC menu/cbs/menu_cbs_refresh.c
CC menu/cbs/menu_cbs_left.c
CC menu/cbs/menu_cbs_right.c
CC menu/cbs/menu_cbs_deferred_push.c
CC menu/cbs/menu_cbs_scan.c
CC menu/cbs/menu_cbs_get_value.c
CC menu/cbs/menu_cbs_label.c
CC menu/cbs/menu_cbs_sublabel.c
CC menu/cbs/menu_cbs_title.c
CC menu/cbs/menu_cbs_up.c
CC menu/cbs/menu_cbs_down.c
CC menu/cbs/menu_cbs_contentlist_switch.c
CC menu/menu_display.c
CC menu/menu_displaylist.c
CC menu/menu_animation.c
CC menu/drivers_display/menu_display_null.c
CC menu/drivers/menu_generic.c
CC menu/drivers/null.c
CC gfx/video_context_driver.c
CC gfx/drivers_context/gfx_null_ctx.c
CC gfx/video_state_tracker.c
CC libretro-common/gfx/math/vector_2.c
CC libretro-common/gfx/math/vector_3.c
CC libretro-common/gfx/math/vector_4.c
CC libretro-common/gfx/math/matrix_4x4.c
CC libretro-common/gfx/math/matrix_3x3.c
CC gfx/drivers/gl.c
CC libretro-common/gfx/gl_capabilities.c
CC gfx/drivers/gl_renderchains/render_chain_gl_legacy.c
CC gfx/common/gl_common.c
CC gfx/drivers_font/gl_raster_font.c
CC libretro-common/glsym/rglgen.c
CC menu/drivers_display/menu_display_gl.c
CC gfx/drivers_context/emscriptenegl_ctx.c
CC libretro-common/glsym/glsym_es2.c
CC gfx/drivers_shader/shader_glsl.c
CC gfx/common/egl_common.c
CC gfx/drivers/sdl2_gfx.c
CC input/drivers/sdl_input.c
CC input/drivers_joypad/sdl_joypad.c
CC audio/drivers/sdl_audio.c
gfx/drivers_context/emscriptenegl_ctx.c:138:44: warning: expression which
      evaluates to zero treated as a null pointerCC gfx/drivers_context/sdl_gl_c
tx.c
 constant of type 'void *'
      [-Wnon-literal-null-conversion]
   if (!egl_init_context(&emscripten->egl, EGL_DEFAULT_DISPLAY,
                                           ^~~~~~~~~~~~~~~~~~~
C:\Emscripten\emscripten\1.35.0\system\include\EGL/egl.h:68:30: note: expanded
      from macro 'EGL_DEFAULT_DISPLAY'
#define EGL_DEFAULT_DISPLAY             ((EGLNativeDisplayType)0)
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
CC libretro-common/file/archive_file.c
CC libretro-common/streams/trans_stream.c
CC libretro-common/streams/trans_stream_pipe.c
CC libretro-common/file/archive_file_zlib.c
CC libretro-common/streams/trans_stream_zlib.c
CC libretro-common/formats/png/rpng.c
CC libretro-common/formats/png/rpng_encode.c
CC libretro-common/formats/bmp/rbmp_encode.c
CC libretro-common/formats/json/jsonsax.c
CC libretro-common/formats/image_transfer.c
CC tasks/task_decompress.c
CC gfx/video_filters/2xsai.c
CC gfx/video_filters/super2xsai.c
CC gfx/video_filters/supereagle.c
CC gfx/video_filters/2xbr.c
CC gfx/video_filters/darken.c
CC gfx/video_filters/epx.c
CC gfx/video_filters/scale2x.c
CC gfx/video_filters/blargg_ntsc_snes.c
CC gfx/video_filters/lq2x.c
CC gfx/video_filters/phosphor2x.c
CC libretro-common/audio/dsp_filters/echo.c
CC libretro-common/audio/dsp_filters/eq.c
CC libretro-common/audio/dsp_filters/chorus.c
CC libretro-common/audio/dsp_filters/iir.c
CC libretro-common/audio/dsp_filters/panning.c
CC libretro-common/audio/dsp_filters/phaser.c
CC libretro-common/audio/dsp_filters/reverb.c
CC libretro-common/audio/dsp_filters/wahwah.c
LD retroarch.js
ERROR:root:libretro_emscripten.bc: No such file or directory ("libretro_emscript
en.bc" was expected to be an input file, based on the commandline arguments prov
ided)
Makefile.emscripten:101: recipe for target 'retroarch.js' failed
mingw32-make: *** [retroarch.js] Error 1

C:\Emscripten\emscripten\1.35.0\crap\RetroArch>

**Comment by gwald** [comment]
Hi, 
Re the documenting of emscripten version,
I've read: https://github.com/libretro/RetroArch/blob/7d64fdabf959da91ec2574333cd7fd531f976959/pkg/emscripten/README.md

Just not sure how the configuration works? I have my ps1 project that I want to server on my site.
I've gotten the json file via XHRIndexer.coffee , just not sure what this means:
("--your-assets-index-file-name--", "--your-index-url--");

Any help would be great :D

**Comment by gwald** [comment]
thanks for the reply, i'm piecing through this..
browserfs.js didn't work for me using the official RetroArch emscripten build using apache (LAMPP)
I found https://github.com/r-type/r-type.github.io using a local copy and it worked for me also.

I found your post https://forums.libretro.com/t/host-retroarch-web-player/5837/5
"reading cue+bins is currently failing, and dosbox is failing too, the cores need major work to work there"

So, there's no chance of getting a ps1 game working on retroarch emscripten (single exe file)?

**Comment by fr500** [comment]
yes, single exe works

**Comment by gwald** [comment]
Cool :)
Any tips where I can look for info on configuring webplay to load it automatically?

**Comment by fr500** [comment]
webplay? netplay doesn't work on emscripten, there is no sockets support in the browser sandbox.
I guess you can tinker with the arguments in the js file to load automatically, I haven't done that but other people have.

**Comment by gwald** [comment]
Sorry for bugging you,  I meant the web player (emscripten)
Any tips on configuring it to launch into ps1 and run a exe?

**Comment by romanrehacek** [comment]
Hi @fr500 ,

what does it mean "whatever" in "emmake make -f whatever -j8"
Can you write me a full example of this command please?

Another question. It is possible to change .mem file directory or disable autoload this file after .js file loaded? I would like to load .mem file in my way with my custom url.

Where I can find some directory dependencies which I need to create with BrowserFS before emulator load (I would like to create my own loader)?

Thanks.

**Comment by RobLoach** [comment]
```
$ emmake make -f Makefile.emscripten -j8
make: *** No rule to make target 'libretro_emscripten.bc', needed by 'retroarch.js'.  Stop.
```

To build RetroArch is something else missing?

**Comment by j8r** [comment]
The minimal documentation is here, this can be closed.

There are still some issues:
I haven't figured out why `embed.html` and `index.html` are the same in https://buildbot.libretro.com/stable/1.7.6/emscripten/RetroArch.7z
I've searched in the Makefiles and dist-cores.sh.
That's too bad because there are a lot or emulators missing in `embed.html` compared to `index.html`

I have also noticed that `media/canvas.png` and `media/retroarch.ico` don't exist, but `canvas.png` and `retroarch.ico` do.
Notes also `analytics.js` produces a `404`, `touch analytics.js` solves the issue.

I can open a PR for this improvements, excluding the `index.html`/`embed.hml` issue.

**Comment by pixobit** [comment]
How do you execute commands? for example to have a html that instantly starts a game with a specific core

**Comment by LibretroAdmin** [comment]
> The minimal documentation is here, this can be closed.
> 
> There are still some issues: I haven't figured out why `embed.html` and `index.html` are the same in https://buildbot.libretro.com/stable/1.7.6/emscripten/RetroArch.7z I've searched in the Makefiles and dist-cores.sh. That's too bad because there are a lot or emulators missing in `embed.html` compared to `index.html`
> 
> I have also noticed that `media/canvas.png` and `media/retroarch.ico` don't exist, but `canvas.png` and `retroarch.ico` do. Notes also `analytics.js` produces a `404`, `touch analytics.js` solves the issue.
> 
> I can open a PR for this improvements, excluding the `index.html`/`embed.hml` issue.

If you're still there, sure, let's see your PR.
