### ISSUE TITLE
Sound is Garbage in Dinothawr on windows

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#4540]
Win7 x64, xaudio or dsound the music (ogg files) is bugged (slow and static noises).
Xaudio has the sfx working contrary to dsound.

This issue is not present on a 2017/01/08 nighlty while it is on one dated from 2017/01/27.

Tested with an old Dinothawr core from 2015 = same behaviour, doesn't seem to be the core in itself.

Doesn't happen on Linux (irc feedback).

**Comment by twinaphex** [comment]
Do a bisect of RetroArch and see if you can find the issue that way.

**Comment by retro-wertz** [comment]
let me help out.....

this commit broke background audio in Dinothawr - https://github.com/libretro/RetroArch/commit/b20c9d870bcaf1a0c95efc8e7b967e5dcc96472b

**Comment by twinaphex** [comment]
Works fine here on Linux.

Try to figure out how to fix it.

**Comment by retro-wertz** [comment]
this only happens when using xaudio2(vorbis playback is slow) and dsound(much more slower). using the SDL driver under win-retroarch does not have the issue and plays normal.

**Comment by retro-wertz** [comment]
**cause of the issue** - when Dinothawr runs, it does not pass correct latency value and is stuck at 8ms for xaudio, 5ms for dsound-windows does not seems to like latency below 32ms

PR should fixes this-at least under windows.

**Comment by Tatsuya79** [comment]
I can confirm it's working for xaudio and dsound now.
