### ISSUE TITLE
Directory/File Browser folder selection not working

### ISSUE THREAD

**Issue by elmachipsfoose** [libretro/RetroArch#4543]
## Description

When I set the "File Browser" directory to a specific folder and enter the "Load Content" option, the File Browser is not starting at the folder I defined. It starts at the default folder and so I have to keep going back over and over to the specific folder where my ROMs are stored.

### Expected behavior

I expect it to start in the folder I selected at the "Directory" menu when I enter the "Load Content" option.

### Actual behavior

It starts at a 'default' folder and so, I have to navigate through some folders to reach the one I want.

### Steps to reproduce the bug

1) Go to the "Directory" menu option and set the  "File Browser" folder to a specific one other than the default folder.
2) Enter the "Load Content" option to select and run a game. It should go straight to the folder you defined in the previous step.

### Bisect Results

The last version I tried which was working was installed back in november/2016 and it was a nightly build, but I don't know which version was that or in which version it started happening.

### Version/Commit
my current version is: e3842d4 built on Jan 24 2017

- RetroArch: [version/commit]
my current version is 1.4.4 or 1.4.0 (can't find this info, sorry).

### Environment information

- OS: [The operating system you're running]
Android O.S. - Tested with both lollipop 5.1 and KitKat 4.4.4, both presents the same results.

**Comment by bparker06** [comment]
The "File Browser" directory can be accessed by going to Load Content -> Favorites.

**Comment by retro-wertz** [comment]
choose the Favorites folder, it should be there. restart Retroarch if its
not.

**Comment by Tatsuya79** [comment]
Perhaps "File Browser" should be renamed "Favorites Folder" or something?

**Comment by elmachipsfoose** [comment]
I agree with tatsuya79, the "File Browser" item could be renamed to "Favorites" or even better, another entry could be created to go straight to a predefined folder (Ex. /ROMS) when entering Load Content. This wo second option would make the rom selection faster than going to the favorites folder.

**Comment by Tatsuya79** [comment]
"Favorites" has been renamed to "Start directory" in the current build and is 1st on the browsing list.

**Comment by elmachipsfoose** [comment]
Much better now, thanks a lot Tatsuya79!!!

**Comment by Tatsuya79** [comment]
Well, I've done nothing but inform you, but you're welcome! :)

**Comment by padremayi** [comment]
Hi all,
when I launch a libretro emulator I have always to set the directory. It works until we exit the emulator.

OS: Raspbian (RetroPie 4.1)
Hardware: Raspberry Pi 3
Emulator: PCSX-ReARMed r22
