### ISSUE TITLE
(Linux) Retroarch Standalone (KMS) Freezing System When Used With Nouveau

### ISSUE THREAD

**Issue by Saroufim** [libretro/RetroArch#4544]
## Description

When launching retroarch straight from a VT without any actual session running in the background, the system freezes and stops accepting input. 

System: Arch x86 
Driver: Nouveau

### Expected behavior

Retroarch was expected to run as it does in a window inside a Wayland compositor

### Actual behavior

Input, including sys reqs were not being accepted. System froze.

### Steps to reproduce the bug

1. Configure system to use nouveau and KMS then install retroarch
2. Reach graphical target and start retroarch using "retroarch" in a VT
3. Notice how retroarch starts and then the system freezes

### Version/Commit

- RetroArch: 1.3.6-1

### Environment information

- OS: Arch Linux x86
- Compiler: GCC6 (Retroarch was fetched from Arch's repositories)

Additional info:

I used Phoenix which is another frontend for libretro and it also had the same exact issue when it ran in full screen inside a gnome-sesison.

**Comment by bootsector** [comment]
Care to share any logs? Did you check your input device permissions?

**Comment by Saroufim** [comment]
That was exactly the issue. The user wasn't added to the 'input' group which was strange because a few weeks ago, it was working just fine. Something must have removed the user from the input group. Thanks for pointing that out and sorry for the erroneous report.
