### ISSUE TITLE
loading remote content

### ISSUE THREAD

**Issue by overdox** [libretro/RetroArch#4546]
### Actual behavior

Hi guys, sorry if this is the wrong place to put this.
I have been trying to get retroarch to load remote content. (via webdav or ftp). Without having to copy the file locally. So far without much luck.

results from running:
C:\emulator\retroarch_debug.exe -L "C:/emulator/cores/snes9x_libretro.dll" -f "ftps://username:password@ftp.com/Data/ROMs/game.zip" >> log.txt 2>&1

shows:
Failed to open ftps://username:password@ftp.com/Data/ROMs/game.zip: Invalid argument
RetroArch [INFO] :: Loading content file: ftps://username:password@ftp.com/Data/ROMs/game.zip.
Failed to open ftps://username:password@ftp.com/Data/ROMs/game.zip: Invalid argument
RetroArch [ERROR] :: Could not read content file "ftps://username:password@ftp.com/Data/ROMs/game.zip"

I guess retroarch expects the files to be stored locally or on the network and accessible via smb?
If so, is there any chance you will look into adding support for ftp or webdav?

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.4.0

### Environment information

- OS: Open SUSE and Windows clients. Debian Server

**Comment by fr500** [comment]
What made you think RA supported ftps or webdav?
Our stance on this currently is that the OS should handle the filesystems.

**Comment by overdox** [comment]
Haven't seen anywhere saying it doesn't support it. No harm in trying right?

**Comment by fr500** [comment]
I didn't mean to be rude or anything but yeah.. it's not supported so far.

**Comment by orbea** [comment]
The VFS changes have been merged, please test again with the nightlies and make new issues for any additional problems, thanks!
