### ISSUE TITLE
Hosted games are always posted to lobby server

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4552]
## Description

Whenever a user hosts a game  even if it's supposed to be a lan game it's posted to lobby

### Expected behavior

It should only post when using the entry under Netplay Rooms or maybe the "Start Netplay host" could have options (with left and right) it should toggle private and public with left/right and trigger the OK action with A/enter

**Comment by RobLoach** [comment]
"Announce Netplay Games" could be a toggle in the Network options, defaulted to `true`?

![screenshot at 2017-02-03 14-41-35](https://cloud.githubusercontent.com/assets/25086/22605694/0ae2c7ea-ea1f-11e6-86fe-b4e680517cfb.png)

**Comment by fr500** [comment]
it would be better it if was a runtime option when starting the room (ie,
left/right to enable or disable that and enter to start hosting)
