### ISSUE TITLE
Merge lan games and lobby games

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4553]
## Description

Currently the internet games on lobby.libretro.com and the LAN games advertised using miniupnp are listed in separate locations.

### Expected behavior

Both game types should be shown in the same list with differentiating icons or something.
The mechanism I built for internet games has a few advantages:
- Can connect using different ports, on the lan scanner ports need to match
- It can use "quick connect"

On the other hand Gregor's implementation is probably cleaner...
The whole `command_event(CMD_EVENT_NETPLAY_INIT_DIRECT_DEFERRED, state->hostname);` was implemented by me because I couldn't figure out how to use his functions properly, also state->hostname has the host and the port in this format: **192.168.1.23:55435**, it's altogether a hack.

It's later split in command.c

Mine just sets up a join for the next load.
Might be not to bad but it needs to be reviewed. Merging both mechanisms would be definitely desirable.

**Comment by bparker06** [comment]
I don't think net and LAN games should necessarily be always mixed together. Perhaps an option to toggle between which one (or both) to show?

**Comment by fr500** [comment]
Maybe a filter or something yeah but it would still help showing everything in one place and cut down some duplicate functionality
