### ISSUE TITLE
improve core and other updates

### ISSUE THREAD

**Issue by bigboo3000** [libretro/RetroArch#4558]
Currently core updates are not easy:
1. You must know what cores are installed on your system (not easy for beginners)
2. You have to guess if the core has been updated or not on libretro server

What would be simpler is a new "update all installed cores" option:
1. It would check for update only installed cores
2. It would check core version on the server, compare it to the local version  and then only update cores that really need it (so it would reduce server bandwidth usage)

This version check could also be used for other contents updates (like shaders etc.) so only changed files are really downloaded and updated (instead of downloading a big zip file each time)

**Comment by madig** [comment]
Bonus points for eliminating the "Update core info files" option and doing that automatically (if need be) when opening the core updater menu.

**Comment by LeCharlatan** [comment]
I came here to post a new idea about it, but seems that someone thought about before I do :dagger: 
I'd really like a new core update system too !
Updating all cores installed would be a great help for RetroArch users. That's a waste of time to update each cores... one by one

**Comment by RobLoach** [comment]
Update all cores button is in there now,.
