### ISSUE TITLE
Crash mrboom and minecraft core

### ISSUE THREAD

**Issue by killer983** [libretro/RetroArch#4561]
In my samsung galaxy a5 2016 will be crash the core minecraft and the mr.boom is in the latest version of software in version 1.4.1 of the play store

**Comment by RobLoach** [comment]
Post the logs?

**Comment by killer983** [comment]
How public records?

**Comment by killer983** [comment]
I send it now that I know how

**Comment by micechal** [comment]
These cores simply don't work on Android (yet).

**Comment by killer983** [comment]
In which systems do they go?

**Comment by micechal** [comment]
"Right now, this core works for Mac/Windows/Linux/ We are still working on Android support!" - from the blog post, though it only relates to the Mr. Boom core.

**Comment by killer983** [comment]
Ok
