### ISSUE TITLE
Retroarch should autodownload hosts core if missing.

### ISSUE THREAD

**Issue by silentq** [libretro/RetroArch#4566]
For ease of use and a smoother connection process it may be easier to have Retroarch automatically download the hosts core when it is not present for Netplay.

## Description

Currently when connecting with a host you need to have the same core which is totally understandable.  It seems like an unnecessary step though to have to look at what core the host is using and then make sure you have it, then if you don't go and download it.

### Expected behavior

When connecting with a host the client side would automatically detect if the core the host has is on the clients local machine, if not it would download it from the core directory.

### Actual behavior

When core is missing the missing content message is produced

### Steps to reproduce the bug

1. Open Retroarch
2. Attempt to Connect to a Host who is using a core you do not have on your local machine

### Version/Commit
You can find this information under Information/System Information
- RetroArch: [1.4.1/ba98ecd]

- OS: Windows

**Comment by fr500** [comment]
You can't do that.  It poses a security risk and cores from Windows won't
work on Android or LINUX

**Comment by Alcaro** [comment]
Could autodownload the same core from buildbot

**Comment by fr500** [comment]
There is no git version information on the buildbot though.
Not saying it couldn't be added of course.

There is already a bunch of info on the buildbot that is completely ignored by RA which could be used to mark cores that need an update

```
2017-02-01 360a5f4f mednafen_snes_libretro.dll.zip
2017-02-04 797bba4b bsnes_mercury_accuracy_libretro.dll.zip
```

**Comment by silentq** [comment]
As far as security it could perhaps be a toggle in the settings and be off by default?

**Comment by Alcaro** [comment]
Either that option would be off, in which case it doesn't solve anything, or on, in which case it doesn't solve the security issues. And the platform differences still remain.

Grabbing from buildbot solves both problems.

**Comment by orbea** [comment]
There is also the problem of when RetroArch is installed on a system where the cores are in read-only directories. Easiest is to just have it safely fail in those circumstances.

**Comment by RobLoach** [comment]
There's an UPDATE ALL option now, but overall, I think autodownloading all cores is a big risk. It should be handled by the packager instead.
