### ISSUE TITLE
Android TV: Can't navigate menu - no controllers supported

### ISSUE THREAD

**Issue by voltagex** [libretro/RetroArch#4569]
## Description
I get an "X is not configured" message in yellow when using any controller on a Mi Box 3 Android TV device. This happens with the Xiaomi Bluetooth Remote and a paired Xbox One S controller. Both devices work in e.g. Snes9x and the Android UI itself. Therefore I can't configure any controllers or navigate the menu/

### Expected behavior
At least be able to navigate the menu to set up controllers

### Actual behavior

Error message.

### Steps to reproduce the bug

1. Install RetroArch from the Play store
2. Attempt to use any controller and navigate menus

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Play Store version -  1.4.1  

### Environment information

- OS: Android 5.x (?) on Xiaomi Mi Box 3 
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
Try the next nightly build, I added an autoconf for the XBONE pad

**Comment by fr500** [comment]
Try this build
https://bot.libretro.com/nightly/android/2017-02-06-RetroArch_staging.apk

**Comment by voltagex** [comment]
Will try this ASAP. What would I need to do to add an autoconf for the Xiaomi Bluetooth Remote, at least for navigating the menus?

**Comment by voltagex** [comment]
Confirming that the Xbox One S pad works with that nightly build, at least with limited testing in the menus,

**Comment by fr500** [comment]
well it just maps the normal buttons, I did add the guide button to go back but maybe it isn't bound correctly
you can setup a combo to return under input settings.

**Comment by voltagex** [comment]
well it just maps the normal buttons, I did add the guide button to go back
but maybe it isn't bound correctly
you can setup a combo to return under input settings.


The guide button seems to always act as the Android home button.

If you tell me which file to modify, I'll set up a combo and send a pull
request.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libretro/RetroArch/issues/4569#issuecomment-277716643>,
or mute the thread

**Comment by fr500** [comment]
You can't add combos to autoconf so it's moot.
The problem here is the stock keylayout taking over the  guide button. We
can't disable that.

**Comment by stromrickard** [comment]
8 years later and this is still not fixed. Got a new TCL TV and can't set the ROM folder. ADB method doesn't work either as i'm not allow to push files to that folder (/sdcard/Android/data/com.swordfish.lemuroid/files/roms: Permission denied). As previously posted, why is the default folder not a common folder like "/sdcard/Android/media/*"??
