### ISSUE TITLE
Localization guidelines

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4573]
## Description

Many of the localization labels and information prompts have awful localization, even in English.

### Guidelines

I think we need someone who knows about technical writing to help us to come up with a sane localization standard. I started by asking in stackexchange. I thing a proper voice and tense would go a long way to convey the messages properly.

http://writers.stackexchange.com/questions/26514/whats-the-best-way-to-describe-what-an-option-does-in-a-program

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/4555

**Comment by micochops** [comment]
I'd like to help with this. I've had previous experience with technical writing in my job and have been writing for something for as long as I can remember (either via my campus/college newspaper or through more professional channels).

Hey @fr500, have you seen the proposals I made to change the English menu labels in issue #4555? What does the libretro team think about them? Thanks also for the input @pepedopolous!

**Comment by fr500** [comment]
I'm not against them but I actually want  some guidelines. That's what this project needs, some guidelines into contributing so stuff starts looking more professional.

btw: @everyone I really really hate the Close Application instead of just close menu entry, I just noticed it today

**Comment by fr500** [comment]
Adding a couple of screenshots for reference
Steam BP is a mess, but it gives me an idea.
Instead of sublabels it uses long explanations inside the submenus.

![screenshot 2017-02-05 23 10 39](https://cloud.githubusercontent.com/assets/1721040/22634512/77bddf1e-ebf8-11e6-98ac-1fdfa7228528.png)
![screenshot 2017-02-05 23 11 36](https://cloud.githubusercontent.com/assets/1721040/22634511/77bcc444-ebf8-11e6-87f1-5c7ea70aa24a.png)

**Comment by fr500** [comment]
Kodi on the other hand uses descriptions, actually long descriptions with subitems for categories

![image](https://cloud.githubusercontent.com/assets/1721040/22634556/e0418c84-ebf8-11e6-91e7-493cfe0967d0.png)

And for the actual settings it uses long descriptions akin to our sublabels. Actually it uses a ticker system similar to what we have.
![image](https://cloud.githubusercontent.com/assets/1721040/22634565/f665b530-ebf8-11e6-9cd6-717ad84ac977.png)

**Comment by twinaphex** [comment]
I like the current sublabels.  I'm not going to remove them if that is the suggestion.

**Comment by fr500** [comment]
It's a discussion to come up with proper standardized grammar for them. 
Nothing else.

**Comment by twinaphex** [comment]
Alright, just wanted to get that clear from the get go, since it sounded rather suspicious and I really don't like the sound of any sweeping changes to the XMB UI this late in the game.

So yeah, I'm fine with the discussion as-is and you guys can continue it. I do agree there is room for improvement there.

**Comment by micochops** [comment]
Hey @twinaphex! We are in agreement with having the sublabels. It helps out tremendously. My (our) issue is with the grammar, consistency, and clarity of said sublabels.

My bias is on the side of brevity. If we can convey to the users what each setting does without having to write a long paragraph for each one, the better.

For as they say, "brevity is the soul of wit."

**Comment by twinaphex** [comment]
On average, sublabels need to be short and concise, yeah. You won't find any disagreement there. In certain cases they need to be a bit more lengthy to explain certain stuff, but overall, I am fine with any suggestions made here (provided I see something I find majorly disagreeable, but I'll let you guys know when it comes to that).

**Comment by micochops** [comment]
@twinaphex, Have you taken a look at the suggested changes I proposed in #4555? Not being pushy, just wanted to have a feel of what I thought could make for better descriptions.

Sure, of course. For more complex settings, there's nothing wrong with having to more thoroughly explain what they do. Hence, longer sublabels for them.

@fr500, am all for having guidelines too! Let me know how I could be of help.

**Comment by twinaphex** [comment]
Have somebody create a PR for it. Most seems good to me on first glance.

**Comment by micochops** [comment]
On it. Thank you!
