### ISSUE TITLE
1.4.1 fails to build

### ISSUE THREAD

**Issue by yurivict** [libretro/RetroArch#4583]
On FreeBSD I am getting these errors:

```
gfx/drivers_tracker/video_state_python.c:111:4: error: use of undeclared identifier 'settings_t'
   settings_t *settings = config_get_ptr();
```
This is fixed by adding ```#include "ui/drivers/qt/wrapper/wrapper.h"```

Another error is:
```
gfx/drivers_tracker/video_state_python.c:127:50: error: too few arguments to function call, expected 7, have 6
            user - 1, RETRO_DEVICE_JOYPAD, 0, key);
                                                 ^
gfx/drivers_tracker/video_state_python.c:150:50: error: too few arguments to function call, expected 7, have 6
         user - 1, RETRO_DEVICE_ANALOG, index, id)
```

**Comment by twinaphex** [comment]
Are you sure this happens with the latest source? I remember patching this up post-1.4.1 release tag, you might want to try the latest trunk instead.

**Comment by yurivict** [comment]
happens with 1.4.1 source.

**Comment by AlexFolland** [comment]
While I am on Win7-64 and not FreeBSD, I can not reproduce this with the latest trunk using mingw64/mingw-w64-x86_64-gcc 6.3.0-1 (mingw-w64-x86_64-toolchain) from msys2's pacman.

**Comment by yurivict** [comment]
This was fixed after 1.4.1, the current revision doesn't have the problem.
Why don't you make a release without these problems?

**Comment by AlexFolland** [comment]
If the current commit doesn't have the problem, then there's no problem.  The commit history is there for diagnosing other problems.  A "release" is just an artificial label for a time when everything was thought to be good enough for a majority of users.  Clearly, there was a little mistake there, but it's not a big deal.  You can just use the latest commit and call that your release, if you know how to use it.  If you need a version number label, wait for the next one, use the previous one, or use the commit hash.

**Comment by orbea** [comment]
This was fixed, no? See issue https://github.com/libretro/RetroArch/issues/4563

Either grab a newer commit, patch 1.4.1 with the fix from the above issue or don't build with --enable-python.

**Comment by yurivict** [comment]
yes, the current commit doesn't have this problem.
