### ISSUE TITLE
Windows mouse pointer visible when running MESS or MAME cores (or all cores in exclusive mode)

### ISSUE THREAD

**Issue by Tasosgemah** [libretro/RetroArch#4586]
This problem started with recent versions or RetroArch. Older versions (like three months or older nightlies) didn't have this problem.

Basically, whenever a game launches via MESS or MAME cores, the mouse pointer appears in the middle of the screen. So you either have to move it away manually or press F11 to "ungrab" it. But everytime you load a new game, you have to ungrab it again. Also, when you go to the RetroArch menu during this, both the RA mouse pointer and the default mouse pointer appear on top of each other.

This is bothersome for someone who uses the program in a "couch-mode" or "big-box" living room friendly setup. Because you have to have your mouse or keyboard nearby to get rid of the mouse pointer. Is there a way to get rid of it permanently? Or make the F11 ungrab function the default one?

**Comment by elmachipsfoose** [comment]
Where did you find MESS cores? I thought RetroArch only supports MAME roms. How do you use MESS? I'm curious here...

**Comment by RobLoach** [comment]
"MAME absorbed the sister-project MESS (Multi Emulator Super System)" http://www.mame.net/

**Comment by elmachipsfoose** [comment]
Yes, I know that, but I don't know how to use it in Android cores...

**Comment by Tasosgemah** [comment]
I use a MESS core from 2015, before it was merged with MAME.

So what about the issue at hand?

**Comment by orbea** [comment]
This is not a windows problem, I have noticed it with linux using the tiling window manager spectrwm.

**Comment by Tasosgemah** [comment]
Seems like the problem doesn't only affect MESS or MAME. It affects all cores whenever i use exclusive full screen.

**Comment by orbea** [comment]
An easy way to reproduce this without any specific core.

1. Start a game with one of the more stable cores (i.e. snes9x).
2. Open the RetroArch menu and select a Video filter (`settings > Video > Video Filter`).
3. After the filter activates the hardware mouse cursor will overlay the full screen RetroArch until a context reset (Toggle full screen).

**Comment by Tatsuya79** [comment]
I see the mouse cursor when there is a "ChangeAV" call in the logging with Mame.
If a game just ask for "Set_Geometry" then it's not there (you don't see a "video signal re-init" happening too).

I'm using exclusive fullscreen too, win7 x64.
Which other core is it happening with?

**Comment by Tatsuya79** [comment]
Check if it's fixed for you too now.
For me it's good using Mame on win7.

**Comment by hyarsan** [comment]
I actually like  the visible cursor! :(

**Comment by Tatsuya79** [comment]
Well, you can push F11 to show it again, but default should be hidden in full screen.

**Comment by hyarsan** [comment]
I didn't know that, cool!

**Comment by orbea** [comment]
Reported as fixed by @Tatsuya79 so I am going to close this issue, please let us know if there are any more issues!

**Comment by Firefoxian** [comment]
input_overlay_show_mouse_cursor = "false"
