### ISSUE TITLE
XMB Battery and Clock Render Size

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#4587]
## Description

RetroArch's theme Battery and Clock icons are quite small compared to the image size:
- [Monochrome clock.png](https://github.com/libretro/retroarch-assets/blob/master/xmb/monochrome/png/clock.png)
- [Monochrome battery.png](https://github.com/libretro/retroarch-assets/blob/master/xmb/monochrome/png/battery-full.png)
- [Neoactive Clock.png](https://github.com/libretro/retroarch-assets/blob/master/xmb/neoactive/png/clock.png) (easy to demonstrate small size)
- [Systematic Clock.png](https://github.com/libretro/retroarch-assets/blob/master/xmb/systematic/png/clock.png) 

As a result, when using a theme outside of Monochrome that has standard sizes for the icons (like the [Material Design theme](https://github.com/RobLoach/retroarch-theme-materialdesign)), the icons end up looking rather large in RA:

![batclock](https://cloud.githubusercontent.com/assets/25086/22710127/2d64579c-ed4a-11e6-8d09-a1690f42f757.png)

### Expected behavior

RetroArch should render the icons smaller on the frontend, rather then expecting the theme to have battery.png and clock.png render small images.

Themes should be able to use a [full-sized version of a clock.png](https://github.com/RobLoach/retroarch-theme-materialdesign/blob/master/png/clock.png).

### Steps to reproduce the bug

1. Install the [Material Design theme](https://github.com/RobLoach/retroarch-theme-materialdesign)
2. Choose "Custom" Menu Font Theme
3. Enable clock and battery in the menu settings
4. Close and restart RA
5. See the icon and battery are larger than the text

### Version/Commit

- RetroArch: 1.4.1

## Proposed Solution

1. Go through all of [retroarch-assets](https://github.com/libretro/retroarch-assets) themes, resize the clock, battery-full and battery-charging icons so that they match the image sizes
2. Update RetroArch's XMB rendering of the battery and clock icons that that they're smaller to match the height of the text correctly.

**Comment by Alcaro** [comment]
I really hope that pic does not say 118% battery

**Comment by RobLoach** [comment]
> I really hope that pic does not say 118% battery

It really does say 118%.... Just ignore it, I'll update my kernel soon.

**Comment by Alcaro** [comment]
Yeah, your battery is at 214748364800% and everyone who disagrees is a Microsoft lackey.

**Comment by RobLoach** [comment]
The two PRs are now open over at https://github.com/libretro/RetroArch/issues/4616 and https://github.com/libretro/retroarch-assets/issues/122 . @Kivutar mentioned he'd be willing to test.

**Comment by RobLoach** [comment]
Going to close this, seems there's some mipmapping issues. That's beyond my knowledge.
