### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by inukaze** [libretro/RetroArch#4590]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
I would like to make a few suggestions. Which are the following

1) Torrent Downloads : Cores, Thumbnails, etc . i say this, because i have around 2 weeks trying to Download "Nintendo - Super Entertainment System Thumbnails" , and my internet connection is slow (i am from venezuela). i think can be good option putting for example for cores 1 torrent per core, but on thumbnails, put all content of specific console, on a torrent, for example "Super Nintendo Thumbnails" 1 torrent with all files in the right strecture of directories and files.

And with the populatiry of RetroArch, i think is better use torrents, because, the download can resume fine, and the torrents can preserve the integrity of files.

2 ) If the torrents are not possible, can add "Queue List" for put multiple downloads.
To place multiple downloads simultaneously but to be downloaded one by one.

Have you ever seen how erratic and slow it gets when trying to download several things simultaneously in a slow connection?

3) The bandwith Limitations, for not consume all if i dont want it or need it. for Download and Uploads ( Uploads in the case the torrents, for share content can be slow, but with all users sharing :D i hope )

4 ) Its possible to add "RetroAchievements" in the "Xbox Classic" (First Xbox) port ?

Thank you for readme :)

**Comment by hizzlekizzle** [comment]
1.) I think the thumbnails are still changing rapidly, so torrent files will quickly be obsoleted. However, once things settle down more, it's a good idea.

4.) The xbox classic port doesn't have network access, so it can't do anything that requires it, including core downloader, retro achievements, etc.

**Comment by retro-wertz** [comment]
why not just be able tp batch download what games you have on a playlist(assume here required name matches rdb)? that should be easier than to download an entire system only to stop middle.

**Comment by inukaze** [comment]
Yes retro-wertz that is a good idea :D

**Comment by fr500** [comment]
We had downloading on demand (ie the first time the box art is shown) but I think @twinaphex didn't like it because there was a second were the boxart wasn't visible. 

I thought it was better too but the decision was to use bundles.

**Comment by RobLoach** [comment]
git is a good option...

1. `https://github.com/libretro/libretro-thumbnails.git`
2. Update RetroArch to point to the directory

Periodically, run `git pull`.

**Comment by inukaze** [comment]
fr500 : i have a problem with that, i can't download directly an specific directory i must download the entire thumbnails directory, the problem is when my slow internet lost connection with git. and when i try to resume, git says "the directory is not empty" and don't resume download, i need delete entire folder, and try to download again. but ever fails.

**Comment by RobLoach** [comment]
Mount http://thumbnails.libretro.com/ with a [WebDEV HTTP Server](https://en.wikipedia.org/wiki/WebDAV)?

**Comment by fr500** [comment]
Nah that would be as slow as loading the thumbs in demand

**Comment by RobLoach** [comment]
Get teh fiber intronauts

**Comment by Ferk** [comment]
> BitTorrent Sync

Please not a proprietary protocol

**Comment by Ferk** [comment]
Maybe [rsync](https://github.com/librsync/librsync) would be a simpler alternative that could work as well.

**Comment by i30817** [comment]
Can't you just enable download resume on your server? If the problem is resuming that is.

**Comment by inukaze** [comment]
Someone can explain where is de default "bios" path under GNU/Linux x86_64 ???

Reading some guides, just tell "Add bios to system's retroarch path" (i dunno that mean to put in /usr/bin/bios_file)

Because i want to test my PlayStation 1 Backups games, but i dont find on internet where is the default path for BIOS. on every site i found, all specify a diferent path, i dont see absolute or relative path for bios files.

I ask for every bios can use retroarch, PSOne, Sega Saturn, PC-Engine, etc . . .

**Comment by fr500** [comment]
Go to settings / directories
Check the setting yourself

**Comment by inukaze** [comment]
Thanks to this guide -> http://butlerpc.net/blog/2015/07/guide-to-running-retroarch-playstation-emulator-on-ubuntu-14-04/ 

i manually add 2 new lines to my configuration file ( /home/inukaze/.config/retroarch/retroarch.cfg )

```
system_directory = "~/.config/retroarch/bios"
content_directory = "/media/Compartido/Videojuegos/Emuroms"
```

Still i searching why my bios files : 
```
dtlh3000.bin
dtlh3002.bin
scph101.bin
scph1001.bin
scph5000.bin
scph5500.bin
scph5502.bin
scph7000.bin
scph7001.bin
scph7003.bin
scph7502.bin
```

Are not found by "PCSXR ReARMed" with every game i test, dont matter if USA, JAPAN (NTSC/-J) , or Europe (PAL) , this core can't find the BIOS. ever shows a message "no BIOS found, expect BUGS" and in the CLI shows "note: running with HLE BIOS, expect compatibility problems"

**Comment by dankcushions** [comment]
for that core the file name and extension needs to be in upper case. e.g. SCPH1001.BIN.

**Comment by inukaze** [comment]
i have the files in lower case and upper case, and don't work neither

**Comment by inukaze** [comment]
Better i compile again retroarch with this cores (manual compile this cores too)

**Comment by micochops** [comment]
I am confirming this.

On OSX (i have El Capitan 10.11.6), RetroArch crashes when trying to load content.
I tried to load/run a couple of PSX games for testing purposes, of course made sure that the BIOS files are there (correct directory, matches md5, etc.)

then NOTHING. RetroArch just crashes, refusing to open the content.

This happens with the latest nightly.

Can anyone else try?

**Comment by RobLoach** [comment]
What are the CRC values? Check against what's in https://github.com/libretro/libretro-database/blob/master/dat/BIOS%20-%20Merged.dat ?
