### ISSUE TITLE
Suggestion: synchronize git revisions for core buildbots

### ISSUE THREAD

**Issue by jprjr** [libretro/RetroArch#4593]
Hi there -

Today I did a test run of NetPlay using the FCEUmm core, myself on a Mac, and my friend on a Windows box.

One hiccup - we both updated the FCEUmm core, but my Mac pulled down a core built against a newer git revision (about 3 commits ahead), and we were unable to start a NetPlay session (until I rebuilt my FCEUmm core to match his core's git revision).

I'm not sure where the buildbot configs are at, so apologies if this is the wrong spot. Is there some way to make sure that the daily core buildbots all build the same git commit across all platforms? Maybe there could be some prerequisite job to grab the latest git commit for each project and store it somewhere, then the core's buildbots can all reference it and get that specific commit.

**Comment by fr500** [comment]
It does, but that doesn't guarantee that every buildbot is building every revision successfully.
This isn't really a RetroArch problem, it's a problem with the buildbot.

We have been thinking about having "stable cores" for netplay but it's a lot of work. Not sure what to do, I'll keep the issue open even though it's invalid in this repo.

**Comment by LibretroAdmin** [comment]
Cthulthu implemented a mechanism now where both cores get updated before starting the netplay session (on HAVE_DYNAMIC-capable platforms). So I think that should resolve it.
