### ISSUE TITLE
RetrArch fails to find xmb/monochrome/font.ttf

### ISSUE THREAD

**Issue by yurivict** [libretro/RetroArch#4594]
This happens when the current revision a2141e6 starts without the pre-existing config directory ~/.config/retroarch . With the directory this doesn't happen for some reason.

```
$ retroarch
Failed to open xmb/monochrome/font.ttf: No such file or directory
Failed to open xmb/monochrome/font.ttf: No such file or directory
```

font.ttf isn't supplied in the project.

**Comment by RobLoach** [comment]
Online Updater -> Update Assets?

**Comment by yurivict** [comment]
It wants ```xmb/monochrome/font.ttf``` before UI even opens.

**Comment by yurivict** [comment]
This is a show-stopper, because it fails out of the box.

a2141e6

**Comment by RobLoach** [comment]
Did you compile from that hash? Do you have all needed packages installed?

**Comment by yurivict** [comment]
Compiled from that hash.

Here are all dependencies:
```
        openal-soft-1.17.2_1
        libXv-1.0.11,1
        ffmpeg-3.2.2_5,1
        libEGL-11.2.2
        libv4l-1.6.3_2
        libGL-11.2.2
        freetype2-2.6.3
        libXext-1.3.3_1,1
        miniupnpc-2.0.20161216
        libXinerama-1.1.3_3,1
        libxcb-1.12
        libX11-1.6.4,1
        libxkbcommon-0.7.0
        libXxf86vm-1.1.4_1
        python3-3_3
        gbm-11.2.2
        libdrm-2.4.66,1
        libass-0.13.4
        sdl2-2.0.5
        python35-3.5.2
        dbus-1.8.20
```

**Comment by RobLoach** [comment]
You'll likely either have to install retroarch-assets package, or check it out manually set and the dir in retroarch.cfg.

**Comment by retro-wertz** [comment]
you are missing the assets folder, or the assets folder installs to
somewhere that retroarch has no write-access to(or just run sudo
retroarch-for some reasons) this happens in Mint 17.3 wherein "make
install" by default will put assets in /usr/local/share//retroarch/assets
causing icons and font not to load, while it does work in ubuntu 16.10

**Comment by oblitum** [comment]
Just got the community package on ArchLinux updated and hit this issue. I have

```
community/retroarch 1.6.0-1 (libretro) [installed]
    Reference frontend for the libretro API
community/retroarch-assets-xmb 433-1 (libretro) [installed]
    XMB menu assets for RetroArch
community/retroarch-autoconfig-udev 1174-1 (libretro) [installed]
    udev joypad autoconfig for RetroArch
```
installed.

**Comment by orbea** [comment]
Can this be closed? I don't think there is anything RetroArch can do here it hasn't already?
