### ISSUE TITLE
Disable input when RA not in focus

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#4599]
## Description

Able to send input to retroarch even when other windows are in focus (chrome, firefox, explorer...)

### Steps to reproduce the bug

1. Start RA
2. Start a game
3. Alt Tab to something else and press buttons on gamepad

### Version/Commit

- RetroArch: [ba98ecd]

### Environment information

- OS: Windows 10 64bit

**Comment by fr500** [comment]
On linux it happens even if using keyboard with some drivers.

**Comment by orbea** [comment]
This was fixed a while ago and is currently working with the x and udev input drivers.
