### ISSUE TITLE
iOS - fba_libretro crashing when launching roms

### ISSUE THREAD

**Issue by DarrenBranford** [libretro/RetroArch#4601]
Hi.

I have been compiling Retroarch myself for several months, without issue. However, for the last few days, fba_libretro has been crashing when I launch roms. I have grabbed a screenshot of Xcode during the crash.

Devices:
iPad Air 2 16Gb - iOS 10.2.1
iPhone 7 256Gb - iOS 10.2.1

I recently updated both devices to the latest firmware, so I am not sure if that might be a contributing factor.

I have already raised an issue at the fba_libretro repo but was told to come here for advice.

Thanks in advance

![grab](https://cloud.githubusercontent.com/assets/5956037/22789147/0c4ef904-eeda-11e6-9562-608d0fcfbbe9.png)

**Comment by fr500** [comment]
Can you bisect?

**Comment by barbudreadmon** [comment]
Did you try using old releases/revision of retroarch/libretro-fbalpha (if they also crash, that means it's definitely related to the firmware update) ?

**Comment by orbea** [comment]
@DarrenBranford Is this still an issue with the current nightlies?
