### ISSUE TITLE
Empty "remaps" folder always created in default location

### ISSUE THREAD

**Issue by AnalShart** [libretro/RetroArch#4610]
## Description
When I change input_remapping_directory to something other than ":\config\remaps", the remaps folder is still created in the default location.

### Expected behavior
remaps folder is not created

### Actual behavior
remaps folder is created

### Steps to reproduce the bug
1. Change input_remapping_directory
2. Launch RetroArch

### Version/Commit
- RetroArch: 1.4.1 stable (2017-02-02)

### Environment information
- OS: Windows 7 Professional 64-bit

**Comment by fr500** [comment]
create a custom.ini in the retroarch folder and it will prevent RA from creating empty dirs.
