### ISSUE TITLE
[Minor Bug] Hide mouse when inside window

### ISSUE THREAD

**Issue by CanadianJeff** [libretro/RetroArch#4611]
when in windowed mode putting the mouse anywhere inside does not hide it

VLC media player by default hides the mouse

its not really a huge bug but more of a suggestion

**Comment by fr500** [comment]
It hides after a few seconds already and it has for a long time
You didn't provide any information on the environment (the guidelines when you open an issue are there for a reason) so closing it.

Feel free to reopen if you can confirm and add information of your environment.
