### ISSUE TITLE
Cheevos segfault with super mario kart

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4613]
## Description

@leiradel, actually this commit breaks snes9x with super mario kart for me
6b9ba1e2b1afccf19c66be953c23a1dcb5122bee

With achievements enabled of course

### Expected behavior

Game shouldn't crash

### Actual behavior

Game crashes

### Steps to reproduce the bug

1. Load game (with snes9x)
2. Weep

### Bisect Results

first bad commit: 6b9ba1e2b1afccf19c66be953c23a1dcb5122bee

### Environment information

- OS: Windows 10 x64
- Compiler: mingw/gcc 6.2

**Comment by leiradel** [comment]
The expression for the "Time Trial, Mario Circuit 1. 5 laps!" leaderboard has something that I don't know how to parse. I've asked in the Retro Achievements forum, but I'll make a PR disabling the leaderboards until it's more stable.

**Comment by leiradel** [comment]
Fixed in PR https://github.com/libretro/RetroArch/pull/4620

**Comment by leiradel** [comment]
Can we close this issue now?
