### ISSUE TITLE
DeSmuME mouse pointer works in RA 1.3.6 but not in 1.4.0 or 1.4.1

### ISSUE THREAD

**Issue by SigmaVirus** [libretro/RetroArch#4614]
## Description

Mouse pointer works perfectly fine in RetroArch 1.3.6 with latest DeSmuME core ([62786c5](https://github.com/libretro/desmume/commit/62786c58933b680e4ce211e92e4ea33f2caa2418)) but does not work in RetroArch 1.4.0 or 1.4.1

### Expected behavior

Use my mouse as a pointer/stylus to use in Nintendo DS games that strictly requires this.

### Actual behavior

No pointer shows up on screen on RetroArch 1.4.0 and 1.4.1

### Steps to reproduce the bug

1. Load RetroArch 1.4.0 or 1.4.1
2. Load the DeSmuME core
3. Load a game, any game that requires pointer/stylus etc.
4. No pointer

### Bisect Results

Something must have happened between 1.3.6 and the current releases of RetroArch

### Version/Commit
1.4.0 and 1.4.1

### Environment information

Windows 10 64-bit
i7 4790K at stock speeds
ASUS Nvidia 1060 6GB
16GB Corsair XMS3 DDR3 RAM

**Comment by sergiobenrocha2** [comment]
Working on Linux

**Comment by SigmaVirus** [comment]
It's great that it works on Linux, so maybe this is just Windows related like in the case of:
https://forums.libretro.com/t/is-there-a-game-boy-color-core-s-that-support-the-bios-boot/5859/ where the GB & GBC bootloader screens worked on Linux but not in Windows.

Anyway, I don't think this is DeSmuME related because I have used quite a few versions from October last year up til now and they all work perfectly fine with pointer in 1.3.6 but not 1.4.0 and 1.4.1

Boot up a game in 1.3.6 and the pointer works immediately, do the same for 1.4.0 and 1.4.1 and no pointer works.

**Comment by SigmaVirus** [comment]
@sergiobenrocha2 

Here's some proof of what I mean:
![pointer](https://cloud.githubusercontent.com/assets/14175085/22887818/c47aa54c-f203-11e6-89a0-5544ab1367bb.png)

![nopointer](https://cloud.githubusercontent.com/assets/14175085/22887839/d48b5378-f203-11e6-8a5d-2b09d6ef46e6.png)

**Comment by SigmaVirus** [comment]
Well I and a user called Awakened back at forums.libretro.com can confirm this much, the option "Pointer emulation" set to "l-stick" or "r-stick" in DeSmuME actually works in RetroArch 1.4.0 and 1.4.1
If however the option is reset and set to "none" then the mouse pointer doesn't work just like the picture above.

This has to be something to do with newer versions of RetroArch as it works on 1.3.6

**Comment by fr500** [comment]
I tried the latest build with Pointer set to none on Windows 10 x64 in my usual setup and in a clean setup in both windowed and fullscreen modes and it seems to be working correctly.

I also tested pointer emulation l/r and it works fine, mouse still works too.
I reckon it's something on your environment. If you can discover what it is feel free to reopen.

**Comment by SigmaVirus** [comment]
@fr500 
Why bother reopen when this clearly is all in my head and I'm imagining this...
Everybody apparently have working pointers except me and one more user so we must be hallucinating.

Now that I got that out of my system and if you really want to help out then PLEASE share your working RetroArch files and DeSmuME core so I can try it out.

**Comment by fr500** [comment]
Well awakened has it too so...
We just need someone else confirming.

I just get my stuff from the buildbot so sharing it would be pointless.

When stuff breaks like this I do the following:
- Backup cfg
- Open cfg in notepad++
- Sort alphabetically
- Remove chunks of the config until it works
- Find out which particular setting causes it

But I tried a clean config and it works so really I have no idea.

**Comment by SigmaVirus** [comment]
@fr500 
Well I'll keep trying more today, but clean config files is clean config files so I don't really know how to make them cleaner.
I'll write back if I find something.

**Comment by fr500** [comment]
I just unzipped, downloaded the core and loaded a game...

**Comment by SigmaVirus** [comment]
OK, well I haven't really tried that because I always configure RetroArch before loading a game.
If by some miracle this works then it has to be something setting wise in 1.4.0/1.4.1 causing it.

**Comment by SigmaVirus** [comment]
OK @fr500 your method worked so that means some setting is causing this because on my configured setup it stops working.

**Comment by SigmaVirus** [comment]
OK we now know what's causing this behavior in 1.4.0 and 1.4.1:
https://forums.libretro.com/t/desmume-mouse-pointer-works-in-ra-1-3-6-but-not-in-1-4-0-or-1-4-1/8990/10

Awakened said and I quote:
"Set input_max_users to at least 2. For some reason having it set to 1 is causing this."

And apparently it's not the first time this option have caused trouble.

So @fr500, reopen????
