### ISSUE TITLE
OSX: Netplay breaks joypad support when connecting to host

### ISSUE THREAD

**Issue by frranck** [libretro/RetroArch#4623]
## Description

Netplay breaks joypad support when client.

### Expected behavior

joypad support to work.

### Actual behavior

When I join a network game with MrBoom the pads stop working.

### Steps to reproduce the bug

1. Go to lobby, refresh
1. See a game beeing hosted
2. Load Mrboom
3. Start Mrboom
4. Go to menu, connect to server
5. Joypads support is broken

### Version/Commit

- RetroArch: 

commit 640dca71cf663f6409860aa690b2e01bbf1aee27
Date:   Sat Feb 11 21:03:43 2017 +0100

### Environment information

- OS: OS.X El Capitan
- Compiler: compiled with xcodebuild -target RetroArch -configuration Debug -project pkg/apple/RetroArch.xcodeproj

**Comment by fr500** [comment]
Can you test any other core?

**Comment by frranck** [comment]
@fr500 Yes, so i just tested with fceum and Contra (USA), my pad works fine when i'm alone and they stop working when I connect to the server. Then it starts working again if I disconnect.

**Comment by fr500** [comment]
Can you go to settings / network and enable netplay c2 controls p1? and re-test?

**Comment by frranck** [comment]
Netplay P2 Uses C1 ? It was enabled already.

**Comment by frranck** [comment]
Tested again with  P2 Uses C1 and it still behave like I described.

**Comment by LibretroAdmin** [comment]
Going to assume this is no longer an issue due to so many years having gone by. If it is still an issue, please reopen.
