### ISSUE TITLE
iOS Some Cores are broken with 1.4.0 => 1.6.1

### ISSUE THREAD

**Issue by Alex793** [libretro/RetroArch#4624]
Hi, 

tested with many configs, when launching a rom with some Cores on 1.4.0>1.6.1 builds (stable & nightlies) we have a black screen, only sound, no video.

The Cores concerned are : 

- 4DO (3DO)
- Nestopia (NES)
- Stella (ATARI 2600)
- Mednafen Lynx (ATARI LYNX)
- Virtual Jaguar (ATARI JAGUAR)
- Prosystem (ATARI 7800)
- Mednafen VBA-M (GBA)
- Beetle PSX (PSX)
- Beetle PC-FX (PC-FX)
- MelonDS (NDS)
- SameBoy (GB/GBC)

Input are ok because I can hear when starting a game by pushing start etc. so it's only a video issue.

All is ok with the exactly same cores on 1.3.6.

Tested on iOS 8.3, iOS 9.3.3, iOS 10.2, IPad Air 1, IPad Air 2, IPad Air Pro 9.7, all jailbreaked with pre-compiled builds and cores and personally compiled cores and builds.

**Comment by Alex793** [comment]
Updated with 2 cores added to the issue.

**Comment by fr500** [comment]
These are most likely core issues but since it seems widespread I'll leave it open..

**Comment by Alex793** [comment]
Added "4DO" core.

**Comment by iOS4all** [comment]
We really need a suitable solution for iOS port of RetroArch specially for jailbroken iOS 10. Where can we find deb file that works on it? It's been long time we didn't see any fix. But for other platforms the work is always continually. Even the official Cydia source of RetroArch is down for long time.
RetroArch is for all platforms. So help us please.

**Comment by Alex793** [comment]
Still issue on 1.5.0...

**Comment by Cepheidsong** [comment]
I ran into this problem too upgrading to 1.5.0.  The cores work just fine on versions previous to this retroarch.  Sound and input work, just no video/graphics/screen at all.

**Comment by Alex793** [comment]
Yep exactly that.

**Comment by Cepheidsong** [comment]
Tried the updated Nestopia core, still same problem.  Controlls work, audio works, but no video.  I wonder if retroarch changed something in the video options that isn't compatible, or maybe they're off-center off screen?  I tried messing with retroarch video options but nothing changed on anything.

**Comment by RomainQuidet** [comment]
check https://github.com/libretro/RetroArch/issues/4797

**Comment by Alex793** [comment]
Added Beetle PSX (PSX) core to the issue.

Still no video output on all these cores on last compiled builds of RetroArch, no probs on 1.4.0 and before.

Something has changed in RetroArch from 1.4.1 for this core but don't why.

For the moment if I want to use these cores I use RetroArch 1.4.0 and for other I use the last build, but hope for a fix.

**Comment by meepingsnesroms** [comment]
This is not invalid I have had this issue too and filed a report months ago:
https://github.com/libretro/RetroArch/issues/4797

**Comment by Alex793** [comment]
Yep I know, I open this issue in February but no fix. I looked and posted in your issue but don't know if it's the same because here it only happen fore some core I listed, no probs with other.

**Comment by Alex793** [comment]
Added "MelonDS (NDS)" and "SameBoy (GB/GBC)" cores to the issue.

This is a major issue, don't why set as invalid and why still no fix, cores are not the problem because why they are ok on 1.3.6 and before ? Something has changed since 1.4.0 and now we have this big issue on iOS.

**Comment by Alex793** [comment]
Thanks fr500 :-) (Are you French ? If yes me too)

**Comment by Kivutar** [comment]
Make sure that you are not using a shader during your tests. Some broken shaders can result in a black screen in combination with some cores.

**Comment by Alex793** [comment]
No shader used here, tested with a clean configuration.

**Comment by Cepheidsong** [comment]
Same issue as well still- I try every update and nightly that comes out with these cores to see if anything changes.  What I can't figure out is what was working in 1.3.6 that doesn't work beyond that.  Besides making sure no shaders, I played with turning on and off and changing all the graphical options on the cores, but nothing alters the blank screen.

**Comment by Alex793** [comment]
Yep, the only solution to play with problematics cores until a fix is :  

![img_1949](https://user-images.githubusercontent.com/428805/27316707-df7746d4-5581-11e7-91de-a47dc52601eb.PNG)

**Comment by Alex793** [comment]
Added "Beetle PC-FX (PC-FX)" to the issue.

**Comment by Alex793** [comment]
With the last nightly now RetroArch crash when starting a rom with all problematic cores.

**Comment by Alex793** [comment]
Issue is now fixed since https://github.com/libretro/RetroArch/commit/69c05cd7b469b4336f80f781745bd3a6c943c257

A big thanks to @yoshisuga @twinaphex and @bparker 👍
