### ISSUE TITLE
Shader preset not saved in D3D

### ISSUE THREAD

**Issue by Clevername02** [libretro/RetroArch#4625]
When in D3D driver mode I pick a shader and choose Save Core Preset or Save Game Preset then exit Retroarch.

When I reopen the game or core I would expect it to apply the shader I selected before, in opengl it works fine.

But in D3D it loads the game without the shader, the shader must be manually reapplied each time.

I'm using the psx mednafen core.

Build date: Feb 12 2017
Git version: e9cbde3
Windows 10

As a side note, I'm using D3D because windowed fullscreen doesn't work on OpenGL.  I don't think that is a RetroArch issue though, it seems to me that all OpenGL applications force exclusive fullscreen for some reason.

**Comment by fr500** [comment]
The D3D backend is largely unmantained, I tried this and it's true and several shaders fail to compile properly on the D3D backend...

Does the shader load if you try to load manually?

**Comment by fr500** [comment]
Assuming the shader loads manually, it should work when the PR is merged.

**Comment by Clevername02** [comment]
thanks! I don't know anything about programming but I chuckled a bit when I saw the fix was changing something from "d3d9" to "d3d"

**Comment by Clevername02** [comment]
Sorry to keep bugging you about this since I guess D3D isn't really a high priority, but I downloaded the latest nightly and the issue isn't fixed its actually worse.

Now I apply a shader in D3D then close RetroArch.  After that RetroArch will not start up.  The only way to get it to start up is to open retroarch.cfg and change the video driver from "d3d" back to "gl".  Then I can go into RetroArch and turn off the shader.  Once the shader is turned off the program works in d3d mode again.

The shader seems to work fine in d3d when loaded manually.  And to be clear I always restart RetroArch after switching video drivers.

I will add that I am not using the "save game preset" or "save core preset" options right now, just applying a shader at all is enough to cause this bug.

BTW I really wouldn't care about this if it was possible to use a borderless window with opengl.  I use my 2nd monitor a lot while using RetroArch on my main monitor and everytime I switch windows the screen flickers which is what always happens when a program is using exclusive fullscreen.   It also flickers if I drag a window from my 2nd monitor to the main monitor with RetroArch on it.  In D3D it doesn't happen, the windowed fullscreen mode works correctly under D3D.  I don't want to open an issue for it because PPSSPP and Dolphin both show the same behavior under opengl so it makes me think its an opengl issue and not a retroarch issue.

**Comment by fr500** [comment]
I don't see how can it make it worse.
What you describe sounds like it's now actually trying to load the shader (before it wasn't) and crashing.

Can you get a backtrace or at least a log?

**Comment by Nedo68** [comment]
hello, i have the same problem, using d3d driver i allways have to manually load the shader again
even i saved it. I have to use d3d because of the stuttering problem on dual monitor setup, only d3d works and is smooth.
read here at the bottom: https://emulation.miraheze.org/wiki/Using_RetroArch#Stuttering_on_multi-monitor_setups
