### ISSUE TITLE
(XMB) Volume Full/Low/Mute Icon

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#4633]
## Description

Add a Sound/Volume indicator icon beside the XMB Battery/Clock status indicators.

### Expected behavior

Be able to see a Volume status icon indicating three different statuses:

- High Volume
- Low Volume
- Muted

![Volume on YouTube](http://i.imgur.com/9oDHob7.gif)

**Comment by Kivutar** [comment]
Good idea

**Comment by LibretroAdmin** [comment]
Should fix this issue since we now have menu widgets -

https://github.com/libretro/RetroArch/commit/3bd36941a6785e524f16eb1672179bd3087370f0
