### ISSUE TITLE
Sony DualShock 3 and clones do not work over BT with 1.4.1 (git bisect done)

### ISSUE THREAD

**Issue by pedrib** [libretro/RetroArch#4636]
## Description

Sony DualShock 3 controllers, and a chinese ShanWan clone, do not work with 1.3.6, while they worked fine with 1.4.1.
This only happens when connecting over Bluetooth. Over USB they work fine.

### Expected behavior

Controller should be auto configured when starting ra.

### Actual behavior

Controller is not configured automatically.

### Steps to reproduce the bug

1. Build and install ra 1.4.1
2. Connect DS3 / DS3 clone over Bluetooth.
3. Start ra
3. Fail!

### Bisect Results

Bisect turned this out:
7d06e6c48f1d7de13106ba04a810b83b406a4706 is the first bad commit
commit 7d06e6c48f1d7de13106ba04a810b83b406a4706
Author: twinaphex <libretro@gmail.com>
Date:   Tue Oct 4 10:18:17 2016 +0200

    Use string_is_equal instead of strncmp

### Version/Commit

1.4.1 d8855caae
1.3.6 218d6f52620d6cbf76bf503f1d417644a83372a3

### Environment information

- OS: Debian Stable / Testing mix amd64
- Compiler: gcc version 6.3.0 20170205 (Debian 6.3.0-6)

**Comment by bparker06** [comment]
fixed in 6e969d0bc

**Comment by bparker06** [comment]
Nope, false alarm, I reverted that commit. I think the change from !strncmp to string_is_equal is not quite doing the same thing anymore, and that may be why this is happening.

**Comment by pedrib** [comment]
See PR #4637  for the fix.
