### ISSUE TITLE
please add platform and version to filename by buildbot

### ISSUE THREAD

**Issue by Jimmy-Z** [libretro/RetroArch#4638]
This most certainly not be the right place to fire this but I didn't find a buildbot repo, so...

**Comment by fr500** [comment]
I don't even understand what you want.

**Comment by Jimmy-Z** [comment]
https://buildbot.libretro.com/nightly/nintendo/wiiu/2017-02-16_RetroArch.7z
https://buildbot.libretro.com/nightly/windows/x86_64/2017-02-16_RetroArch.7z

in my download folder, they'll end up as 2017-02-16_RetroArch.7z and 2017-02-16_RetroArch (1).7z

**Comment by fr500** [comment]
Sorry I won't do that...

**Comment by fr500** [comment]
Sorry I won't do that...

**Comment by Jimmy-Z** [comment]
I see that you're struggling, may I know why you won't do that?

**Comment by fr500** [comment]
For one, I don't like working on the buildbot anymore
And for two, I like that all the folders have the same file name.
