### ISSUE TITLE
Shaders and menu pipeline

### ISSUE THREAD

**Issue by ryuuji89** [libretro/RetroArch#4641]
Retroarch 1.4.1 Windows 10
When using the shader crt-royale-tvout+image-adjustment the menu pipeline change to Ribbon (Simplified) and all the other pipelines does not show (ribbon/snow/bokeh...shows only the bg gradient).

**Comment by fr500** [comment]
Your shader is CG, the pipeline shaders are GLSL.
CG is deprecated.

**Comment by ryuuji89** [comment]
GLSL version of that does not work. I select it and it does not activate the shader

**Comment by fr500** [comment]
That is a shader problem though, not a RetroArch problem
Sadly not all the shaders have been converted properly
