### ISSUE TITLE
Retroachievements does not work if have upercase letters in username

### ISSUE THREAD

**Issue by NihilisticEevee** [libretro/RetroArch#4642]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I have a mixture of upper and lowercase letters in my username in retroachievements. My username is NihilisticEevee. It will not connect with my account. But after trying a new account with only lower case letters(nonekillertest) it succeeds.

### Expected behavior

retroachievements works with any case letters in username.

### Steps to reproduce the bug

1. have a mix of different case letters in username such as NihilisticEevee

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information
retroarch nightly 2/13/2017
- OS: windows 10 64 bit
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
@leiradel I think you fixed this for passwords?

**Comment by leiradel** [comment]
The username and password are taken from the configuration file and URL-encoded without any further processing.

@NihilisticEevee can you check your `retroarch.cfg` file and see what are the values of `cheevos_username` and `cheevos_password`? Please don't post them here, just check if they're ok there ;)

**Comment by NihilisticEevee** [comment]
everything seems to be order. They look to be the correct values.

**Comment by leiradel** [comment]
@NihilisticEevee do you know how to compile RetroArch from source? If yes, please edit `cheevos/cheevos.c` and change the `#undef`s of `CHEEVOS_LOG_URLS` and `CHEEVOS_LOG_PASSWORD` to `#define`, compile, and run.

On the log, check for `CHEEVOS url to login:`. Copy the URL and paste it into Firefox and report what you got back. Please take care not to disclose the URL, since it contains your username and password.

I'll create an account with uppercase letters and see if I can find something.

**Comment by NihilisticEevee** [comment]
i know how to compile and ill try it. what log are you talking about, retroarches log or a compile log of sorts?

**Comment by RobLoach** [comment]
I've been using [`RobLoach` on RetroAchievements](http://retroachievements.org/user/RobLoach) and it has worked for a while.

**Comment by NihilisticEevee** [comment]
i followed the url and it contains "{"Success":true,"User":"NihilisticEevee","Token":"psAVKVeLJ2nFIvp1","Score":0,"Messages":0}"

**Comment by leiradel** [comment]
It seems the login is working. Please change your password, the `Token` field above can be used to hijack your Retro Achievements account.

Please configure the log to be verbose and post the log after you attempt to play a game with achievements. Please roll back your changes to the `#undef`s before generating the log.

**Comment by NihilisticEevee** [comment]
I believe this will contain the relevant information, load it with FCEUmm core


RetroArch [libretro INFO] :: Loading C:\retroarch temp\Super Mario Bros. (World).nes...

RetroArch [libretro INFO] ::  PRG ROM:    2 x 16KiB
RetroArch [libretro INFO] ::  CHR ROM:    1 x  8KiB
RetroArch [libretro INFO] ::  ROM CRC32:  0xd445f698
RetroArch [libretro INFO] ::  ROM MD5:  0x8e3630186e35d477231bf8fd50e54cdd
RetroArch [libretro INFO] ::  Mapper #:  0
RetroArch [libretro INFO] ::  Mapper name: NROM
RetroArch [libretro INFO] ::  Mirroring: Vertical
RetroArch [libretro INFO] ::  Battery-backed: No
RetroArch [libretro INFO] ::  Trained: No
RetroArch [libretro INFO] ::
RetroArch [INFO] :: Environ GET_VARIABLE fceumm_palette:
RetroArch [INFO] ::     asqrealc
RetroArch [INFO] :: Environ GET_VARIABLE fceumm_nospritelimit:
RetroArch [INFO] ::     enabled
RetroArch [INFO] :: Environ GET_VARIABLE fceumm_overclocking:
RetroArch [INFO] ::     disabled
RetroArch [INFO] :: Environ GET_VARIABLE fceumm_overscan:
RetroArch [INFO] ::     enabled
RetroArch [INFO] :: Environ GET_VARIABLE fceumm_aspect:
RetroArch [INFO] ::     8:7 PAR
RetroArch [INFO] :: Environ SET_GEOMETRY.
RetroArch [INFO] :: SET_GEOMETRY: 240x224, aspect: 1.224.
RetroArch [INFO] :: CHEEVOS system RAM: 0000000070CC8AE0 2048
RetroArch [INFO] :: CHEEVOS save RAM:   0000000000000000 0
RetroArch [INFO] :: CHEEVOS video RAM:  0000000000000000 0
RetroArch [INFO] :: CHEEVOS RTC:        0000000000000000 0
RetroArch [INFO] :: CHEEVOS testing NES (discards VROM).
RetroArch [INFO] :: CHEEVOS getting game id for hash ff02b25112d3a3163db10e332841b02c
RetroArch [INFO] :: CHEEVOS got game id 1446.
RetroArch [INFO] :: CHEEVOS got achievements for game id 1446.
RetroArch [INFO] :: CHEEVOS deactivated unlocked achievements in softcore mode.
RetroArch [INFO] :: CHEEVOS deactivated unlocked achievements in hardcore mode.
RetroArch [INFO] :: Skipping SRAM load..
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1

**Comment by NihilisticEevee** [comment]
Well i just logged on to my account and it said i needed to verify it. I'm sure i did before, even have the email from when i did it. I guess when i verified it last time it didn't go throught or something. But its working now. Thanks and sorry for wasting your time.

**Comment by NihilisticEevee** [comment]
scratch that, i had retroarch signed in to my test account. The NihilisticEevee account still dosen't work.
but that log i posted is from when i was signed in to my non working account(NihilisticEevee).

**Comment by leiradel** [comment]
No problem, it happens. Cheers.
