### ISSUE TITLE
Android touchscreen mouse emulation tends to displace the cursor to the bottom-right corner

### ISSUE THREAD

**Issue by Ferk** [libretro/RetroArch#4652]
Related: #4640 

## Description

When moving the finger across the touchscreen very slowly it's noticeable a displacement of the mouse pointer to the bottom right corner of the screen.

I guess this might be caused by a rounding error (I see the patch uses ceiling for rounding).

It can be noticed very clearly by just leaving your finger over the touchscreen and slowly changing the inclination of the finger slightly without really displacing it.

It can also be seen that making a perfectly horizontal line with the finger will slightly move the cursor down, and a perfectly vertical movement will slightly move the cursor to the right.

### Expected behavior

The mouse cursors corresponds to the finger movements

### Actual behavior

Noticeable displacement of the cursor to the bottom/right corner

### Steps to reproduce the bug

1. Enable android overlay
1. Start Scummvm core with no content
2. put your finger over the touchscreen and perform slow micromovements.

### Version/Commit

- RetroArch: d0b29f3 (buildbot apk from 2017-02-15)

### Environment information

- OS: Android

**Comment by diablodiab** [comment]
This is most likely caused by the way the android input drivers handles a thread and copy state of the current input and then copied between them. I will look into this.

**Comment by twinaphex** [comment]
I think the state copying might no longer really be necessary, I don't think input is threaded at least for Android. So you might be able to cut out all the state copying and indirection going on, they are remnants from one of @Themaister 's old branches where he was trying threaded input for Android. I think it didn't really yield any big returns though.

**Comment by diablodiab** [comment]
Great, I'll look into removing the state copying as this will simplify the driver a bit.

**Comment by Ferk** [comment]
Works perfect now! thank you 👍
