### ISSUE TITLE
MiniUPNPc integration issues

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4661]
@GregorR 
1 - It should be able to intelligently handle when a router does not support UPNP, and if so, revert back to the way things worked without UPNP.
2 - This 1-second where the UI gets blocked should not happen. UI at no time should be blocked.
3 - It keeps crashing for me when trying to host a game, whether I am using the mupen64plus core or any other core. This happens ever since we are baking in miniupnpc. More testing here is required.

**Comment by fr500** [comment]
1. there is nothing to do there, it just fails to forward, I think the crashes might not be entirely related

FWIW, it works fine on windows, with upnp enabled or disabled in the router.

**Comment by GregorR** [comment]
To 1: It's supposed to, there's obviously some missing edge case I need to figure out.

2: Too bad. I didn't write MiniUPnPc, did I.

3: Presumably see (1).
