### ISSUE TITLE
Non-standard refresh rates/fps not being respected, even when vsync is off

### ISSUE THREAD

**Issue by dankcushions** [libretro/RetroArch#4662]
## Description

We believe we've discovered a RA issue when debugging a mame2003 issue: https://github.com/libretro/mame2003-libretro/issues/75

it seems games that run at irregular refresh rates (eg 57.41hz, 58hz) are stuck at 60hz regardless of whether vsync is set or not. it seems they run at the correct framerate in the menu, but not when in-game. there is a curious work-around:

> Ok, I just tested this with Caveman Ninja and it runs 58 fps when the menu is active but goes back to 60 fps outside of the menu. Disabling vsync and leaving audio sync should correct it but it's not working as expected. The solution is to go to settings > frame throttle and set 'maximum run speed' to 1.0. This means you can't fast-forward anymore but it will run at the the proper 58 fps.

however this workaround seems to cause audio skipping/static.

i don't believe this is a mame2003 issue as it is setting the correct framerate via retro_get_system_av_info() - https://github.com/libretro/mame2003-libretro/blob/01b1b35b958cf948b3a660362d05e429ae017324/src/libretro/libretro.c#L338

### Expected behavior

game should run at the non-standard frame rate, as long as vsync is not on.

### Actual behavior

game is incorrectly running at 60hz.

### Steps to reproduce the bug

(using GL driver)

1. load mame2003
2. load robocop.zip
3. active frame rate counter
4. turn vsync off, leave audio sync on
5. observe framerate in-game (should be 57.41)

### Bisect Results

was happening in 1.3 / 14-jan-2016 / https://github.com/libretro/RetroArch/commit/3d74e7bda9108fb371bcd8cc427a9e628f15e996
earlier release doesn't seem to want to load up in xcode.

### Version/Commit

- RetroArch: https://github.com/libretro/RetroArch/commit/e6ee2527e5710969264861fafb0de300a6f36bce / current master

### Environment information

- OS: OSX 10.12.3. Also occurs on linux (raspian)
- Compiler: LLVM 8.0 & gcc (Raspbian 4.9.2-10) 4.9.2

**Comment by Monroe88** [comment]
Have you tried this while setting `audio_max_timing_skew` to 0.0?

57.41Hz seems to be within the default maximum timing skew of 0.05, since 60.0 * 0.05 is 3 which means the game can refresh as low as 57.0Hz and still have its audio resampled to run at 60Hz.

From my testing, the audio timing skew feature is working correctly as long as cores accurately report their refresh rate and you have your PC monitor's refresh rate set accurately in `video_refresh_rate`.

**Comment by dankcushions** [comment]
@Monroe88 
> Have you tried this while setting audio_max_timing_skew to 0.0?

the UI doesn't allow 0.0 to be set, but i raised it to 0.5 and it made no difference here. still 57.x with menu showing, but 60.x in-game.

**Comment by hizzlekizzle** [comment]
I set mine to 0.02 via config and it ran the proper 57 fps regardless of max run speed setting. I didn't hear any sound crackling, but I didn't hear any with the max run speed method, either.

**Comment by Monroe88** [comment]
0.5 maximum timing skew would make it resample almost everything to 60Hz, within range of +/- 30Hz.

You can set 0.0 in the config file, but setting 0.01 in the UI should still make it only resample games  within+/- 0.6Hz for 60Hz. so a 57.41Hz game would not get resampled.

I ran robocop with MAME 2003 and MAME 2014 and both ran at 57Hz when 'audio_max_timing_skew' was 0.01 or lower.

[robocop-170218-193546](https://cloud.githubusercontent.com/assets/4119107/23098400/f77934f6-f611-11e6-96a4-06179bb8b7aa.png)

**Comment by dankcushions** [comment]
yes! setting audio_max_timing_skew to 0.01 fixes it. i was raising it before... wrong! it shows the correct frame rate now, even with v sync on (I guess in the latter case it just dupes the occasional frame?)

i guess i don't fully understand what this setting is for and why the default is 0.05. why would i want it to resample games in this way, and why does it affect the framerate?

**Comment by Monroe88** [comment]
The audio timing skew feature is intended for small adjustments like resampling NTSC console games that display at rates like 60.0988Hz to sync perfectly on PC monitors that run 60.0Hz. The default setting of 0.05 is likely too large, and a more conservative setting 0.02 would be more ideal.

**Comment by dankcushions** [comment]
cool! ok let me clarify that the users like it then i can propose a new default.

> RA only disables force disables Vsync when the timing difference is large and the game's refresh rate is greater than the monitor's refresh rate so it couldn't display without dropping frames.

i guess if the game's refresh rate is lower than the monitors it can keep vsync on by duping the occasional frame? in this case maybe you can see tiny hitches in scrolling games. but anyone who cares about these obscure rates will have vsync off i guess.

**Comment by dankcushions** [comment]
In retrospect, the default is probably sensible. The very subtle gameplay and audio difference doesn't seem worth the dropped frames. Thanks for your help!
