### ISSUE TITLE
Save slot display always zero on save/load

### ISSUE THREAD

**Issue by lookwhatisee** [libretro/RetroArch#4663]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

In retroarch 4.1.14 the on screen notification always says "saving/loading data from slot #0" no matter which save slot is actually selected.

I am able to iterate through the save slots.  I can save and load from any slot as expected.  However, even when loading a game from slot #2 the message incorrectly states slot #0 on screen.

### Expected behavior

I expect the slot # message to accurately reflect the slot that has been selected.  If I am saving to slot #2 I expect the message to say "saving to slot #2". 

If I am loading a game from slot #1 I expect it to say "loading game from slot #1"  or some approxomation.  The important part here is that the save slot increment should be correct.

### Actual behavior

No matter which save/load slot is selected the message on screen when loading/saving a state always says slot #0.

### Steps to reproduce the bug

1. Install/update retroarch on retropie to the latest version.  I believe it is 4.1.14.
2. Save a game in slot #1.  The message will say saving to slot #0.
3. Also try loading from slot#1.  Again the message will incorrectly state it is loading from slot #0.

### Bisect Results

I believe this started happening after updating retroarch on retropie last week.

### Version/Commit
I'll have to double check but another user on the retropie forum indicated the version is 4.1.14

- RetroArch: [version/commit]
4.1.14

### Environment information

- OS: [The operating system you're running]
Raspian with retropie.

- Compiler: [In case you are running local builds]

**Comment by RobotLimeLtd** [comment]
Same here after updating RetroPie today; regardless of the slot you choose:

- When saving, the notification first reads "Loaded state from slot #0" before it says "Saved state to slot #0"
- When loading, the notification always reads "Loaded state from slot #0"

However, I can confirm that the actual slot saving feature is working... it's just the notification that's wrong.

**Comment by fr500** [comment]
Confirmed
