### ISSUE TITLE
GLUI Bottom entries are out of screen

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#4668]
On a Galaxy S3 (1280x720 screen) using GLUI, going to load content and browsing a folder I start a search.
The result is about 10/15 lines below the section shown and out of screen, there is no selected item lightening color visible.

Current Android nightly, no change done in DPI/scaling settings.

**Comment by Tatsuya79** [comment]
Just browsing in the menu with a gamepad overlay you can't see the bottom of many lists.
Quickmenu or settings/Video bottom items can't be seen on screen.

**Comment by Tatsuya79** [comment]
Happens the same on my win7 x64 Retroarch nightly.
So that's not only an Android bug.

**Comment by Tatsuya79** [comment]
@Kivutar 
bisect points to https://github.com/libretro/RetroArch/commit/dc4140a00bff07e3b714538ceb43dbdd37c30879

**Comment by Kivutar** [comment]
I noticed it too. There is certainly something wrong in the code that computes the height of an entry. This bug happens only where there are sublabels. But on some lists it looks ok, on some others not.

**Comment by Tatsuya79** [comment]
It happens just browsing files.
Load content->Mame big folder-> happens at the bottom.

**Comment by heuripedes** [comment]
Seems to be related to scrolling: https://github.com/libretro/RetroArch/blob/master/menu/drivers/materialui.c#L1798 . `mui_get_scroll()` uses a fixed line height but GLUI has variable now. This function is called in `mui_navigation_set()` to start the scroll animation that updates `mui->scroll_y`.

**Comment by Tatsuya79** [comment]
This is on PC with standard dpi setting (200):
https://youtu.be/KUNffLjw3F4

On my android phone, Samsung Galaxy S3 1280x720 landscape, it already cuts the bottom of settings->video.

**Comment by Tatsuya79** [comment]
(To keep a trace of this) 
Kivutar fixed the settings going out of screen in 720p with:
https://hastebin.com/kajopokoni.diff

I had to change it with
unsigned sum = 0;
on its own to work here.

But it's not fixing playlists going out of screen, they get out faster now.

**Comment by Tatsuya79** [comment]
Just needed float precision for that sum calculation to be right in long playlists.
