### ISSUE TITLE
win32 frontend bugs 

### ISSUE THREAD

**Issue by zeromus** [libretro/RetroArch#4673]
Motivation: user came online saying his retroarch was crashing (sometimes) loading roms with mgba, and maybe other cores (but not all) and at any rate it was erratic. It brought down his msys session so he couldnt gdb it.

I decided to debug it in MSVC and ran into a host of issues which are _probably not his issues_. They mostly stem from the win32 file menu.

------------

1. when I load a file from the file menu (let's say, a GBA game):
it fails (due to point 2. at least)
RA then attempts to set the core to a dummy core. I dont think it succeeds. Retroarch is then seemingly in an inconsistent state, but it may be hard to perceive or understand (the previous core's name will still be displayed, but it isnt the previous core)

------------

2. **win32_browser fails to copy resulting file path into `filename`** (I think that's the idea, but the length of `filename` should be passed in). Therefore no content EVER loads through the OFD. This is a big bug (it renders the UI useless) but an easy fix. 

------------

3. Note: need to rename all function pointers named `free`, so we can heap-check efficiently in msvc. (i renamed to zfree, I may use rfree instead and submit a PR). Windows does some `#define free` yeah its dumb.

------------
4. 
There is a bug when loading content from file menu... 
gl.quitting is set by gl_alive, after gl is shut down
this seems to be because the gl driver re-enters itself on account of being responsible for doing the win32 message checks.

gl_alive --> video_context_driver_check_window --> win32 messages --> content_load --> video_driver_free

consequently, gl.c's gl_alive call of (video_context_driver_check_window(&size_data))
A. frees GL
B. sets gl->quitting to true (thus clobbering memory).

notably, in the meantime, content's been loaded, and config files have been loaded, thus potentially clobbering a lot of systems

This is a SERIOUS BUG and since it manifests as a ONE BYTE HEAP CORRUPTION (for now) so it's really sneaky to find.

The correct fix for this is to **re-engineer the video driver so that it can have a hook to poll OS windowing messages from the top level main run loop** -- which is the only place it can safely be done!!!

An incorrect fix for this, which is easier, and may fix all the actual issues for now (while leaving possibility for new issues in the future) will be for someone well versed in the code to **queue a content load operation for the menu driver to pick up instead of processing it on-the-spot from deep in the gl+windowing callstack**

------------

5a. At this time, I cant test loading roms from the roms directory, because none of the cores are loading properly (oops, I dont have libwinpthread.dll etc.)
5b. Since cores dont load properly, load_dynamic_core() calls retroarch_fail() which "sanely kills the program" (not) and then we proceed with crashing because we're half-initialized and runloop_check_state does not return RUNLOOP_STATE_SLEEP like it should (it thinks the core is loaded, I guess). this makes input get polled (but it didnt get initialized so it crashes). etc. etc.

**I suggest you return false instead of retroarch_fail() in dylib_load**, so that the extensive work that's been done in handling failing codepaths is employed, instead of bypassing 100% of it and proceeding as if nothing went wrong.

This is a serious bug, but probably not a common bug. I would suggest just doing what I said and hardly even studying it further--itll be better than what's done now.

**Comment by rootfather** [comment]
I was the one who reported this issue on IRC. Thanks a lot for your investigations, @zeromus.

Loading the mGBA core fails in about 90%. It seems that mgba triggers the bug a lot more often then other cores, I tried with gambatte too and gambatte is loading more reliable, but also failing in about 50% of all launches.

I also have the issue that RetroArch randomly crashes when I try to save a Core or a Game override, also with shutting down MSYS2 and GDB immediately. Could this be related to the same bug?

**Comment by rootfather** [comment]
The core loading bug seems to be a regression from 1.3.6.

retroarch master with current mgba core: affected
retroarch 1.4.1 with current mgba core: affected
retroarch 1.3.6 with current mgba core: I was able to run it 5 times in a row. Probably unaffected?

Well... a "git bisect" over nearly 6000 commits will take some time, but I'll try it.

**Comment by twinaphex** [comment]
Removed the 'retroarch_fail' call inside dynamic.c. Hopefully that addresses one part of the issues here.

**Comment by bparker06** [comment]
I added the win32_browser copy to filename and set it to use the right file filters for core/content.

4e1b4d05

**Comment by rootfather** [comment]
I bisected 1.3.6 (known good) and 1.4.1 (known bad). Here's the result for my core loading issues/crashes:

```
7d70fb3f4ade01d36bb7d95222446933472e772b is the first bad commit
commit 7d70fb3f4ade01d36bb7d95222446933472e772b
Author: aliaspider <aliaspider@gmail.com>
Date:   Thu Nov 17 20:16:50 2016 +0100

    (WIN32) don't reopen the stdout/stderr streams or close the console when
    attaching an existing one.

:040000 040000 91733cf13cc31883309c259f45b0f4f872e179ea 7935d2b04dddd51adf6a59fedafafb8d85ce0b68 M      frontend

```

@twinaphey, @bparker06 , I tried the current master (e9f1b25e5 at the time of writing), but my issues still persist. 

I confirmed that 7d70fb3f4ade01d36bb7d95222446933472e772b is the issue by checking out the latest master and then reverting 7d70fb3f4ade01d36bb7d95222446933472e772b locally. Core loading, returning back to the menu, loading a game again, and saving core/game overrides now works like a charm again.

**Comment by zeromus** [comment]
Stay tuned, we have more to say on the subject.

**Comment by zeromus** [comment]
PR mentioned above discusses issue and fixes it
