### ISSUE TITLE
Run a never-played-before game from the playlist, select a core, and you're back at the run/remove/info menu

### ISSUE THREAD

**Issue by madig** [libretro/RetroArch#4681]
### Steps to reproduce the bug

Select a game you've never played before from the playlist (read: that doesn't have a core set yet) and select a core.

### Expected behavior

The game should be run immediately after having selected a core.

### Actual behavior

You're back at the run/remove/info menu. When doing this while running another game, the RA overlay closes and you're thrown back to the current game. Opening the RA overlay again presents you with the run/remove/info screen.

### Version/Commit

git master

### Environment information

- OS: Fedora 25 x64
- Compiler: gcc 6.3.1.

**Comment by sergiobenrocha2** [comment]
Duplicate, see #1893
