### ISSUE TITLE
XMB-misplaced menu items

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#4685]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Menu items from previous menu tab does not reset list position.

### Expected behavior

when going back to previous menu tab, it should start from the within the limits of that menu listing

### Actual behavior

Menu items from  previous menu tab gets misplaced or moves all the way up in sync of where your last position from the next menu tab. example, if you are at Privacy in Settings, going back to Main Menu items will be on the very top.. happens with main tab entries, but not in playlists

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

Previous commits returns you to top menu item when going back to a previous tab 
1st bad commit https://github.com/libretro/RetroArch/commit/378a69aba9abb20aa26fe5b30a285deeb0f5bb66

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/e9f1b25e55608614dc6e599a1918051b170f246c

### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW 6.3.0

![xmb bug](https://cloud.githubusercontent.com/assets/23315382/23208392/c8768b42-f92f-11e6-9971-330028d3fa7b.png)

**Comment by twinaphex** [comment]
I reverted the commits. Test if it works properly now.

**Comment by retro-wertz** [comment]
it ok now. its back to previous behavior.
