### ISSUE TITLE
32-bit Windows build crashing when DeSmuME core attempts to load content

### ISSUE THREAD

**Issue by ElTipejoLoco** [libretro/RetroArch#4694]
### Description

Latest stable 32-bit Windows build of RetroArch 1.4.1 crashes when DeSmuME core (git [62786c5](/libretro/desmume/tree/62786c58933b680e4ce211e92e4ea33f2caa2418)) attempts to load Nintendo DS content. Latest stable 64-bit Windows build of RetroArch 1.4.1 does not exhibit this issue with purportedly the same core. Online Updater might need to be updated to omit listing the core for download if it turns out to be based on 64-bit version of emulator.

### Expected behavior

I expected RetroArch not to crash, or if its DeSmuME core alone crashed, for the 'dummy core' to kick in instead. I also expected the verbose log to display what triggers the crash, but to no avail.

### Actual behavior

Windows detects that RetroArch stopped responding. The log file does not show what the cause was. When double checking existing issues on the libretro gits, could not find anything that applied under any of the following repos: RetroArch, desmume, and desmume-libretro.

Pastebin of log [here](http://pastebin.com/h3L784AC).

### Steps to reproduce the bug

1. Download stable version of x86 RetroArch 1.4.1 from buildbot
2. Use built-in Online Updater to download Nintendo DS DeSmuME core
3. Attempt to load Nintendo DS content

### Bisect Results

Unfortunately, I'm a new user to RetroArch; I've no knowledge of a previous commit that worked. I'm also not certain that the problem doesn't lie solely with the desmume-librerto.dll pointed to by the Online Updater, so the issue might be in the wrong place ultimately. Sorry.

### Version/Commit

- RetroArch: [1.4.1/[ba98ecd](/libretro/RetroArch/tree/ba98ecd0815927028d24ea04c2341ac7ab0b64e5)]

### Environment information

- OS: Windows 10 Pro 1607 64-bit build 14393.693

**Comment by retro-wertz** [comment]
as general rule, you should have not use 32bit retroarch on your 64bit
windows pc, it shouldnt be a problem though but i think 32bit windows
builds have issues.

**Comment by sergiobenrocha2** [comment]
That was the right place to post it: https://github.com/libretro/desmume/issues

**Comment by ElTipejoLoco** [comment]
I thought that was only for when people were certain the core alone is the problem. Which I'm not, but I'll go ahead and write up the issue again on the current (?) DeSmuME core git sometime.

Is the "Load Dummy on Core Shutdown" option not meant to prevent RetroArch from crashing or closing when one of the cores does, though? That and the "32-bit build's Online Updater might be pointing at an incompatible core" thing still seem like RetroArch issues, unless they're behaving as intended.

**Comment by orbea** [comment]
@ElTipejoLoco Is this still a problem with the current nightlies and latest desmume core builds? If so can you please provide a backtrace?
