### ISSUE TITLE
tvout.glslp doesn't work

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/RetroArch#4697]
Since recent nightly it stopped working with `RetroArch [INFO] :: Shader log: 0:105(7): error: syntax error, unexpected VEC4, expecting ',' or ';'` error.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 2b1fbca31

### Environment information

- OS: Arch Linux

**Comment by fr500** [comment]
Are you sure only RA changed an not the shader itself?

**Comment by GeneralFailer** [comment]
Pretty sure.

**Comment by hizzlekizzle** [comment]
Can you bisect it, then, and pin down which commit caused it?

**Comment by GeneralFailer** [comment]
No, sorry.

**Comment by hizzlekizzle** [comment]
we'll have to wait and see if anyone can reproduce it, then.

**Comment by GeneralFailer** [comment]
Also affects 1.4.1, I probably hadn't updated in quite a while. Error message ends with:
`RetroArch [ERROR] :: Failed to compile vertex shader #0
RetroArch [ERROR] :: Failed to link program #0.
RetroArch [ERROR] :: Failed to create GL program #0.`

**Comment by hizzlekizzle** [comment]
whoops, my mistake, it actually is happening but it's just a problem with that shader. [I fixed it in my repo](https://github.com/hizzlekizzle/glsl-shaders/commit/873a30de707b8c7e55784ef09bcbd6ecd0e332f3), though, so it should make its way into the online updater in a few minutes/hours.

**Comment by GeneralFailer** [comment]
Should've thought that the shader, as opposed to the profile, did update.
