### ISSUE TITLE
[ps vita] content mount points broken

### ISSUE THREAD

**Issue by ireallydontexist** [libretro/RetroArch#4699]
## Description

In the last stable build 1.4.1, when selecting Load Content, the ps vita mount points (ux0, app0,...) were selectable. Now only the mount point / is proposed but cannot be used on the vita.

### Expected behavior

Possible to select vita mount points (especially ux0) from Load Content

### Actual behavior

Only a not working mount point "/" is proposed

### Steps to reproduce the bug

1. Select Load Content menu

### Version/Commit

- RetroArch: current master

### Environment information

- OS: ps vita
- Compiler: libretro nightly builds

**Comment by twinaphex** [comment]
@frangarcj Could you look into this?

**Comment by frangarcj** [comment]
@ireallydontexist psvita or pstv?

**Comment by ireallydontexist** [comment]
At least pstv

**Comment by frangarcj** [comment]
Can you install this and try again?

Remember to put roms on ux0:/data/

https://github.com/frangarcj/vita-fix-permissions/releases/tag/master-v3

**Comment by frangarcj** [comment]
@ireallydontexist have you tried that?

**Comment by ireallydontexist** [comment]
Hi, sorry I'm not at home this week so I'll test it when I'll be back this weekend.

**Comment by ireallydontexist** [comment]
Same issue. Only the / mount point is shown even after applying the patch on all data/ files

**Comment by frangarcj** [comment]
Can you delete data/retroarch folder?

**Comment by ireallydontexist** [comment]
Same result.
The thing I do to reproduce:
- delete data/retroarch
- Run a retroarch emulator: picodrive or mednafen pcs
- I go to options, directory, file browser
- Usually I can then select ux0 but now only /

In the last nightly, Pico drive crashed at this last step, pce just proposes /

-- in case of missed steaks, blame the phone

**Comment by frangarcj** [comment]
It should be fixed by now
