### ISSUE TITLE
retroarch.cfg can't be loaded

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#4700]
Today compiled retroarch.exe on win7 x64.
Retroarch starts with default settings and display "Failed saving config to <cfg_path>" OSD message.

It seems to be looking into the config folder instead of the main retroarch folder (was it changed on purpose?), log shows:
RetroArch [ERROR] :: Config: couldn't find config at path: "E:\Emulateurs\RetroArch64\config"

But moving the retroarch.cfg there or trying to load it directly doesn't work.

Log is also showing:
RetroArch [ERROR] :: Failed saving config to "E:\Emulateurs\RetroArch64\config".

Is the path not working at all?

Reverting https://github.com/libretro/RetroArch/commit/af971ea9be8ecf8c6cb5478c09d7c9e1ffee9c65 fix the issue.

**Comment by pepedopolous** [comment]
Same problem on Linux x64 with 2 different computers.

**Comment by hizzlekizzle** [comment]
Should be fixed now. Twinaphex wrapped that bit in an ifdef.
