### ISSUE TITLE
segfault when connecting to blank host server

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#4703]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Entering nothing(or just blank) in connect to netplay hose causes segfault.

### Expected behavior

should just return to netplay menu when server(or host address) is invalid or not available or similar.

### Actual behavior

segfault

### Steps to reproduce the bug

1. run RA, launch game
2. goto quick menu, goto Netplay
3. choose connect to netplay host
4. enter nothing, or leave it blank
5. press Enter on keyboard or button 1 in gamepad(whichever is set to OK)
6.segfault

### Bisect Results

bt https://hastebin.com/jivaxegevi.go

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.4.1 git 308aa46

### Environment information

- OS: Windows 10-x64 / Ubuntu 16.10
- Compiler: gcc 6.3.0 / gcc 6.2.0

**Comment by bparker06** [comment]
Should be fixed in 32a5c1a, can you confirm?

**Comment by retro-wertz** [comment]
this should be OK now.
