### ISSUE TITLE
Scan not recognizing No Intro set for Atari Lynx

### ISSUE THREAD

**Issue by Todann** [libretro/RetroArch#4710]
I am trying to add the official No Intro Rom set for Atari Lynx to a playlist on my Windows 10 PC, but the scan just runs through them without creating any playlist for Atari Lynx. I can manually load and play the games but not a single one is being detected by the scan. I have tried with both the "Beetle Handy" and "Handy" cores loaded, I also have the BIOS image lynxboot.img in the system folder. The files are individually zipped .lnx files, but I've tried with them unzipped as well. I'm also running the latest stable build and have a MAME core installed.

I've scanned many other sets without problem but I haven't been able to figure this out for a few days now. I don't know what else to try so any help would be greatly appreciated, thank you.

**Comment by RobLoach** [comment]
Worked for me. Have any CRCs of files that don't work?

**Comment by Todann** [comment]
That's strange I was thinking it must be for everyone since everything else is working so well.

A few I've got:
California Games (USA, Europe) 7F9651F0
Joust (USA, Europe) 8EDD2F51
Lemmings (USA, Europe) D73C8446

I've also tried a fresh download and install of RetroArch a few times. The Lynx core switched from "Beetle Handy" to "Mednafen Handy", some of the other names have been switching too I don't think that would have anything to do with it though.

**Comment by Todann** [comment]
So it seems some of my set are out of date, I didn't think that almost all the rest would be fine, except every single lynx game but I guess they are. Sorry about that I'm still learning all this I didn't even know to check the CRC.

**Comment by retro-wertz** [comment]
this should be in the libretro-database section. compare your roms crc to lynx dats there.

**Comment by Todann** [comment]
Yeah thanks for the tip, updated ROMs did the trick they're all scanned now, it's odd that only the Lynx were off. Is there a way to check CRC that doesn't require a program being installed?

**Comment by RobLoach** [comment]
Nicely done! Thank for investigating. Feel free to close this issue out. :+1:

**Comment by gingerbeardman** [comment]
@Todann if you're on Mac/Linux you can use a built in command to to CRC but not sure about Windows.

**Comment by Todann** [comment]
Oh ok, I found this program HashTab but was just wondering if RetroArch could show it somehow. Thanks again for the help though.

**Comment by alexb3d** [comment]
The same problem.
I have the set No-Intro [2018-03-24] updated and the Lynx playlists are not created.
