### ISSUE TITLE
Can't select a font file in XMB Menu

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#4711]
Have no font selected in settings->user interface->menu->menu font (if you have one already this bug does not happen).
Try to select one.
You don't see the ttf files and can't select them.

At the beginning of February when entering the file browser to select a font you had a "Filter unknown extensions ON or OFF" on top. You had to put it to OFF to see the ttf files.
It's not there anymore so I don't see a way to select them in the menu atm.

**Comment by Kivutar** [comment]
I confirm this bug.

**Comment by DeckardEdward** [comment]
Confirming this bug. For me, selecting a .fon file through the Menu Font dialogue resulted in RA attempting to launch the font file with ScummVM.

**Comment by RobertoReis** [comment]
OK, thanks for confirming that, it`s been a while since Retroarch can`t load font files, I remember it was OK back in 1.3 (not sure though).

**Comment by Tatsuya79** [comment]
This one has been fixed now with previous days changes.
