### ISSUE TITLE
[3DS] PCSX ReARMed missing from builds

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#4716]
## Description

PCSX missing from Nintendo 3DS builds.

It was in 1.3.6
It is missing from 1.4.0 and 1.4.1

The last nightly build I have with it is from 2016-12-04.

### Expected behavior

PCSX core should be present on 3DS

### Actual behavior

PCSX core is missing on 3DS

### Build log

Failing to build:
http://p.0bl.net/1981

**Comment by fr500** [comment]
Please don't post core reports here.
https://github.com/libretro/pcsx_rearmed/

**Comment by gingerbeardman** [comment]
OK, sorry, noted!
