### ISSUE TITLE
Feature Request: Clean exit signal from command line/script

### ISSUE THREAD

**Issue by Crono141** [libretro/RetroArch#4718]
Hey all.  Got a really specific feature request.  I would like to be able to shutdown retroarch cleanly (as if exited through the interface so SRAM saves correctly) from a parallel command line script.

Here's my use case.  [I have crammed a raspberry pi running retropie _inside_ an old TV](https://specterindustries.blogspot.com/).  The pi is powered on when the TV powers on, and I have a capacitor circuit installed to keep the pi alive after the TV is shut off so that the pi can cleanly shut down.  This is accomplished via a python script.

The problem I just realized with this is if you're in the middle of a retroarch session, and power gets cut, then retroarch is killed as part of the shutdown process.  This results in no saved SRAM for that session.  Obviously, I could use the sram save interval feature to work around this, but a more elegant solution would be to signal retroarch to cleanly exit before performing my shutdown from my python script. Is such a thing even possible?

**Comment by hizzlekizzle** [comment]
I'm not sure how well (or even if) this works, but it looks like it could do what you're seeking: https://github.com/merlink01/RetroArchPythonAPI

**Comment by Crono141** [comment]
Looks interesting.  But after perusing the code it looks like it'll only work if retroarch is started by the api. Its on the right track though.

**Comment by hizzlekizzle** [comment]
RetroArch also has a stdin/network "command interface" that I know nothing about other than its existence.

**Comment by aliaspider** [comment]
yeah as @hizzlekizzle already mentioned, there is a way to do this already with the network commands, check out settings-->network to enable/disable listening to network commands, or change the UDP port.

the commands can be sent by running
`./retroarch --verbose --command <command>`
so in your case you can just do
`./retroarch --verbose --command QUIT`
to list available commands , just pass in an invalid command, for example:
`./retroarch --verbose --command none`
you can also specify the ip and/or port to send to:
`./retroarch --verbose --command 'QUIT;localhost;55355'`
you can probably also use any other tool that allows you to sent raw UDP packets over network.

there is an issue currently with network/stdin commands though, it seems they are polled twice in a single iteration, so there is a big chance that a command will be lost before it is executed.
commenting out this line 
https://github.com/libretro/RetroArch/blob/master/runloop.c#L1120
does make network command work again, but I doubt that is the correct way to solve this.
you could also spam the QUIT command to work around this issue until it is fixed.

**Comment by Crono141** [comment]
Excellent.  Just tested and it works (though you need to quit retroarch after setting the network settings first before it works).  This is exactly what I was looking for.
