### ISSUE TITLE
[enhancement] add more NDS cores other than DeSmuME

### ISSUE THREAD

**Issue by belldandu** [libretro/RetroArch#4719]
I'm gonna be honest here. The Developer of DeSmuME is a dick. I've heard about and seen him do some really screwed up things to prevent certain games he doesn't like from working and having DeSmuME as the ONLY NDS core really just limits what can be played at this point. So please add some more cores (especially for the android version) for NDS games.

**Comment by fr500** [comment]
There aren't any other open source emulators that we can port atm, we have a melonds port but that isn't really mature.

Anyway, next time read the template text that shows up when you click the new issue button. It explains what this place is for.

For everything else we have a nice forum:
https://github.com/cpp3ds/gl3ds/blob/master/README.md
