### ISSUE TITLE
missing per core control settings with bnes

### ISSUE THREAD

**Issue by nco2k** [libretro/RetroArch#4722]
## Description

i was using the bnes core and wanted to change the per core control settings, but when i opened the quickmenu, the controls field was missing. no problems with other cores though.

### Version/Commit

RetroArch 1.4.1 / Feb. 02 - 2017

### Environment information

Windows 7 (64 Bit)

**Comment by Gyurn** [comment]
I downloaded a few bsnes cores to recreate your issue, but I could not.  I could access the controls on each core I tested.  Could you be more specific with your issue, i.e., which bsnes core specifically, how to recreate your issue?  Maybe RetroArch got corrupted down the line, have you tried reinstalling RetroArch and starting with your problem core?

**Comment by nco2k** [comment]
bnes not bsnes :D

**Comment by fr500** [comment]
This is not a RetroArch issue.

**Comment by hizzlekizzle** [comment]
Just to clarify, I think the remapping probably hasn't been added to the bnes core, which is waaaay out of date and probably shouldn't be considered for general use.

**Comment by nco2k** [comment]
@fr500
thanks for clarifying.

@hizzlekizzle
such a shame really. FCEUmm runs very choppy for some reason and i dont like the color palette from the other cores to be honest. thats why i choose bnes.
