### ISSUE TITLE
OSD verbosity

### ISSUE THREAD

**Issue by meleu** [libretro/RetroArch#4725]
In some other threads (#4217 , #4254 and #4237) we were discussing about how to implement the OSD verbosity. If it should be defined with only one setting or with different settings for each message.

Do we have a consensus on this?

I would like to know it to implement what I tried to in #4217 (useful messages to RetroAchievements user).

---

Just to remember the opinions (and check if those guys still have the same opinion):

@twinaphex and @leiradel seem to agree that only one setting to define the OSD verbosity is the way to go.

@twinaphex said in https://github.com/libretro/RetroArch/issues/4237#issuecomment-270173050

> Yet even more settings? As if we aren't getting criticized of having too many settings already.

@leiradel said in https://github.com/libretro/RetroArch/pull/4217#issuecomment-266299874

> RetroArch has too many options already. I'd go with a unique global setting to control the verboseness of everything though.

@fr500 and @Ryunam have the opinion that different types of message should have their own setting for verbosity.

@fr500 said in https://github.com/libretro/RetroArch/issues/4237#issuecomment-270279859

> obscuring many notifications behind one setting would be bad imho...

@Ryunam detailed his opinion and put some interesting points in https://github.com/libretro/RetroArch/pull/4354#issuecomment-270340738

**Comment by meleu** [comment]
I already got what I wanted: show useful OSD messages to cheevos users after launching a game. It was implemented in #5138

**Comment by danny6869** [comment]
A bit confusing, but was an option added to turn down (off) the verbose-ness?
