### ISSUE TITLE
Runtime permissions

### ISSUE THREAD

**Issue by belldandu** [libretro/RetroArch#4726]
## Description
Retroarch fails to allow games to save if the rom is located on an sd card (with the storage permission)

### Expected behavior
Rom is located on SD card. Load that rom and play for a bit then save via the in game save. Exit and look for an smt file with the same title as the rom in the same dir as rom or Restart rom and be able to load data where i left off.

### Actual behavior
Thanks to android 4.4+ SD card writing of any kind must go through extra steps so any progress you thought was saved never actually was saved. The file will either not be there (if it wasnt there before) or it will have the old progress since it was never updated.

### Steps to reproduce the bug

1. Load any rom on the SD card
2. Start new game
3. save using in game save
4. close the rom
5. Run the rom again (remember SD card only, this works fine via local storage aka `/storage/emulated/0`)
6. Attempt to load non-existant save

### Bisect Results
Android 4.4+

### Version

- RetroArch: 1.4.1

### Environment information

- OS: Android 6.0.1

**Comment by fr500** [comment]
Android permissions changed in 4.4, it's a known issue but it's actually google's fault. You need sdfix to fix this for 4.4 and 5.0 IIRC.
On android 6 there is a native fix but we need runtime permissions.

**Comment by belldandu** [comment]
There is also a way to do it without root using adb in the sdk tools but its limited to an old version of 4.4 and 5.0 and was patched in version 4.4.1+ and 5.0.1+

**Comment by fr500** [comment]
Yes, but as I said, this is a google problem. Not RA's.
I'm leaning towards invalid for this repot.

**Comment by belldandu** [comment]
Well its still relatively fixable in 6.0.1 And as you said requires runtime permissions. Although its google's fault its still possible to fix it in retro arch on newer versions of android (6+)

**Comment by belldandu** [comment]
In this case im sure many would prefer to receive a notification when loading roms from their SD cards that saving will fail, Or possibly make retroarch have ingame saves goto a dir other than the SD card on versions its not possible to fix without root (4.4+, 5+). Instead of outright learning that their saves are working after playing for hours ;0.

As for android 6.0 im sure many would rather be prompted to give write perms than unknowingly lose saves that came from hours of play ;0

This issues is mainly annoying to all users who store roms on their SD card (which will be many due to limited internal storage)

**Comment by belldandu** [comment]
@twinaphex any idea what version this might be fixed / remedied in?
