### ISSUE TITLE
iOS nightlies (iOS 8 and below) are missing CFBundleIdentifier in the Info.plist

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#4731]
Running iOS 7 on an iPad 3.

Pulled from here https://buildbot.libretro.com/nightly/apple/ios/2017-03-06_RetroArch.zip

Copied over to my /Applications folder. When I go to a terminal to run uicache I get this error

````
RetroArch.app missing CFBundleIdentifier
````
Last build I know personally was working was 2017-02-18

**Comment by parkerlreed** [comment]
I was able to copy just the Info.plist from the 02-18 build and this lets it work.

**Comment by iOS4all** [comment]
I hope we can use retroarch as well
Jailbroken iPad Air 2 iOS 10.2
Also I feel jealous of an iOS 8 user because they still able to use JIT on pcsx and n64 however we have JIT back functionality but no one is working on support it again.
We really miss retroarch on our devices

**Comment by ijoinit** [comment]
Year,iOS down scince Steve Jobs passed away,maybe I need an android device in my pocket, I really need an android device.

**Comment by parkerlreed** [comment]
I think this is cleared up. Using 1.9.4 on iOS 6 and it's working well.
