### ISSUE TITLE
F2 causes OSDs for both loading and saving states

### ISSUE THREAD

**Issue by tony971** [libretro/RetroArch#4734]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

If you use the save state hotkey, there will be an OSD for loading a state before an OSD for saving one.

### Expected behavior

Just an OSD for saving a state.

### Actual behavior

Two OSDs.

### Steps to reproduce the bug

1. Hit F2

### Version/Commit
You can find this information under Information/System Information

- RetroArch: ec14874

### Environment information

- OS: Windows 10 x64

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/3967

**Comment by tony971** [comment]
I take it this behavior is implicitly understood by those who know the workings of #3967? It's not mentioned specifically.

**Comment by fr500** [comment]
It is mentioned
