### ISSUE TITLE
Streaming Retroarch with Open Broadcaster Softwar

### ISSUE THREAD

**Issue by NelsonRosenberg** [libretro/RetroArch#4735]
## Description

Tried Game Capture and Windows Capture with retroarch set with GL video driver. Game Capture does not work (nothing appears in OBS), Window Capture stuck on first frame. Display Capture works. Other program work as intended.

### Expected behavior
Both Game and Window Capture to work with Retroarch

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.4.1/a624e61]

### Environment information

- OS: Windows 10 64b

**Comment by Tatsuya79** [comment]
Working fine in win7 x64.
I'm using "Game capture" where I select retroarch.exe, not the one with a Frame number written after it.

**Comment by NelsonRosenberg** [comment]
I only see the option of retroarch with the Core + Frame number for me. How do you see two options?

**Comment by NelsonRosenberg** [comment]
Retroarch was running in admin mode and OBS was not able to hook to it in Game Mode without it also being run in admin. So that was fixed. Window Mode is still a mistery, but Game Mode is prefered.

Thank you.
