### ISSUE TITLE
Android version file browser is completely broken in 1.5.0

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#4741]
Everything glitches and says directory not found.

This has todo with the change from double tap to single tap if you load a directory then load a different one the first will open.

**Comment by fr500** [comment]
Please try de

**Comment by roflcopter777** [comment]
I see that this report gets a reply but the broken Wii U report doesn't. Guess 1.5.0 will never be looked into.

**Comment by twinaphex** [comment]
@Kivutar did the single tap changes, he would need to look into this if there is indeed an issue here.

**Comment by ZenGuru** [comment]
Problem with file browser exits. I installed RetroArch today on Galaxy S7 (Android 7.0) and file browser is not working correctly. I am cloning project as i write this and will try to see what is going on...

**Comment by fr500** [comment]
Only with touch right?
I tried on the ATV and it seems fine there.

**Comment by parkerlreed** [comment]
Here's a video https://www.youtube.com/watch?v=PCe2oGq_Dvw

**Comment by parkerlreed** [comment]
Also this isn't limited to Android. 1.5.0 on an iPad 3 (7.1.2) shows the same behavior. Might be more touch related than platform.

**Comment by RobLoach** [comment]
Use the back button rather than Parent Directory..... Parent Directory is actually a sub-menu rather then going back a menu. Use the back button at the top left.

**Comment by parkerlreed** [comment]
I did. The one where I mentioned cycles I was tapping the back button. It seems to get in a little bit of a loop and then finally backs out to the main menu.

**Comment by parkerlreed** [comment]
Here's a video with show touches enabled. I couldn't replicate the cycle but I was able to finally select an entry but I'm not sure why. https://www.youtube.com/watch?v=ErAA6pCtI0I

**Comment by meepingsnesroms** [comment]
To navigate properly you have to go into the directory go back and then click it again, then you will be in the proper directory.(this must be repeated for every directory in the path)

**Comment by Zlatko1337** [comment]
Click event is not working and onClick wrong row is selected which ends with wrong folder being opened (as meepingsnesroms described).

**Comment by twinaphex** [comment]
@kivutar Please check this out

**Comment by twinaphex** [comment]
To all parties involved - please check if this solves the issue -

https://github.com/libretro/RetroArch/commit/f4103b40741d33ca6acddd2b8729311d40ec85e3

**Comment by meepingsnesroms** [comment]
Yes, that fixed it.
