### ISSUE TITLE
x-box one controller disconnects randomly and reconnects about 2 times an hour

### ISSUE THREAD

**Issue by budtz** [libretro/RetroArch#4743]
For a few months i have had this problem: x-box one controller disconnects randomly and reconnects about 2 times an hour. its random thou

what could it be? dosnt happen with anything other than retroarch

**Comment by bparker06** [comment]
What platform is this? And are you using Bluetooth?

**Comment by SuperMeatBro** [comment]
I'm having this problem to but i'm never really sure if it was me accidentaly unplugging it because it's connected with a a plug. I'm on windows 10.

**Comment by orbea** [comment]
Not nearly enough info to proceed so I am going to close this, please make a new issue and fill out the issue template if this is still a problem.
