### ISSUE TITLE
Add a way to get a native screenshot without status text ("Taking screenshot.")

### ISSUE THREAD

**Issue by CreamyCookie** [libretro/RetroArch#4751]
## Description
I'd love to have a way to get a screenshot that has the native resolution of the console, one that doesn't contain text like "Taking screenshot".  (`video_gpu_screenshot = true` seems to not do this, at least not for mGBA)

- OS: Ubuntu 16.04

**Comment by bparker06** [comment]
GPU Screenshot is the opposite of what you want. That setting reads from the GPU framebuffer, which may be scaled up and contain any shaders you have applied. If you previously tried with the setting off and it wasn't working, then that is a definitely a bug. From my understanding of how the non-GPU screenshots work, it shouldn't even be possible for the OSD text to show up, unless the core does something strange like not provide its own frame buffer or something.

**Comment by CreamyCookie** [comment]
Ah, that was the problem. Thank you!
