### ISSUE TITLE
Add cheevos/retroachivements to Vita port

### ISSUE THREAD

**Issue by deurk** [libretro/RetroArch#4752]
Could we please benefit from being able to connect to RetroAchievement on the Vita builds of RetroArch?

**Comment by meleu** [comment]
Hey @frangarcj , I saw in [a libretro.com post](https://www.libretro.com/index.php/retroarch-1-3-6-beta-release-for-playstation3-and-ps-vita-henkaku/) that you worked on the PS Vita port. I would like to see retroachievements feature working on the PSVita port, is there something that a "hobbyist-average-C-programmer" can do to help?
