### ISSUE TITLE
XMB Playlist detail view no longer shows the playlist entry/game title

### ISSUE THREAD

**Issue by jeapostrophe** [libretro/RetroArch#4754]
If I navigate to a game, the selected entry in the playlist will read "Tetris Battle Gaiden", if I then select it, the menu will display "Run" / "Remove" / "Information". There's no residue of what game it is that I am looking at.

Suggested locations:
- Above the choice menu (to the right of the playlist icon)
- Underneath playlist name on the top of the screen

**Comment by jeapostrophe** [comment]
pr's welcome

**Comment by Kivutar** [comment]
On the original design of XMB, we're supposed to display the game name at the title, on the top left corner.
