### ISSUE TITLE
Build Moonlight interface into menu

### ISSUE THREAD

**Issue by jeapostrophe** [libretro/RetroArch#4756]
Facilitates https://github.com/libretro/Lakka/issues/660

I imagine something to (1) manage the pairing process, (2) store the default resolution/frame-rate/etc settings, (3) store a list of games.

Perhaps the right way to think about this is with a moonlight core and the (1)/(2) steps being part of the core configuration.

**Comment by jeapostrophe** [comment]
pr's welcome

**Comment by fr500** [comment]
It should be a core instead yeah
