### ISSUE TITLE
Touch interface on android not reacting properly

### ISSUE THREAD

**Issue by belldandu** [libretro/RetroArch#4757]
## Description
When trying to goto a dir using touch it takes you to `dir/Parent directory` when in scan file, dir, or load content

### Expected behavior
Touch `/storage/3763-3761` and goto sd card dir

### Actual behavior
went to `/storage/Parent directory` because the highlight was still on `Parent directory` even though i didn't tap parent directory.

### Steps to reproduce the bug
1. Tap load content
2. tap `/storage`
3. tap any dir
4. Tap any dir in that dir if it hasnt changed to `/storage/Parent directory`

### Bisect Results
Started happening today on retroarch for android.

### Version/Commit
- RetroArch: 1.5.0

### Environment information
- OS: Android 6.0.1

![screenshot_20170314-150550](https://cloud.githubusercontent.com/assets/5639384/23918046/d5b4d35c-08c7-11e7-9cd1-5ca1931273da.png)
![screenshot_20170314-150733](https://cloud.githubusercontent.com/assets/5639384/23918118/0920ddd0-08c8-11e7-9da0-f4afcf18b1b8.png)
![screenshot_20170314-151149](https://cloud.githubusercontent.com/assets/5639384/23918251/9dccebb8-08c8-11e7-9f44-fe4830cf7fd3.png)
![screenshot_20170314-151157](https://cloud.githubusercontent.com/assets/5639384/23918258/a41b0234-08c8-11e7-9b7a-aa583dace869.png)

NOTE: tapping parent directory intentionally will actually take you to the parent directory and not the folder `Parent directory` which doesn't exist.

This is definetly a bug.

**Comment by belldandu** [comment]
https://youtu.be/7V_2-uoJUl0

**Comment by fr500** [comment]
Check the commit under information/system information

**Comment by bparker06** [comment]
possible duplicate of #4741

**Comment by belldandu** [comment]
![screenshot_20170314-161748](https://cloud.githubusercontent.com/assets/5639384/23920621/cfe996d8-08d1-11e7-8530-e8863281adf3.png)

**Comment by belldandu** [comment]
on a side note. Im usjng the google play version

**Comment by fr500** [comment]
Update, it was fixed already

**Comment by belldandu** [comment]
Kk
