### ISSUE TITLE
Make the ingame recording hotkey use ffmpeg

### ISSUE THREAD

**Issue by deurk** [libretro/RetroArch#4759]
It would be great if the ingame hotkey could trigger recording with ffmpeg, respecting the config file with recording settings. 

That would allow smaller video capture than the current ffmpeg-launch-core-with-recording-enabled-the-whole-time.

Thanks!

**Comment by orbea** [comment]
This seem to have been implemented.

See `Settings -> Input -> Input Hokey Binds -> Recording Toggle`.

I started content, pressed it and found it started to record, I pressed it again and found it stopped recording. I'm going to close this, but please let us know if there are still problems for you with the current nightlies.
