### ISSUE TITLE
Retroarch not working at all on New 3DS 11.2.0-35U HBL

### ISSUE THREAD

**Issue by sumbodyshero** [libretro/RetroArch#4764]
I have installed the correct bios and have tried every single emulator and cannot get them working. They either fail to load or fail to load on ROM (MANY different roms have been tried). They either freeze or give me a message about 4096 samples and the monitor hz.

I see many videos online of people just installed it to their SD card and they are good to go, but I have been trying nonstop for days with no luck. Someone please help!

**Comment by Margen67** [comment]
https://3ds.guide/

**Comment by sumbodyshero** [comment]
I have CFW now and I tried the libretro cia but it just freezes on boot with a black screen. I have the SNES 9x cia working perfectly, but not the libretro. I am now on a different 3DS (same firmware and model, just different color).

**Comment by sumbodyshero** [comment]
OK, so I deleted everything regarding to Retroarch and reinstalled the latest nightly build (I was using stable before). Now the retroarch cia doesn't boot to a black screen, but it says "the sd card was removed".

**Comment by FateForWindows** [comment]
Seems to be an issue with your SD card. Could you describe it a little? Storage size, allocation units, manufacturer, etc.

**Comment by gingerbeardman** [comment]
@sumbodyshero this error is misleading, basically it means that it cannot find some files in your `SD://retroarch/` folder. Did you copy that folder to the root of your SD?

**Comment by twinaphex** [comment]
@meepingsnesroms says this can be closed now.

**Comment by sumbodyshero** [comment]
Just hacked my Vita and never touched my 3DS again.
