### ISSUE TITLE
Writing to SD card [$25]

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#4769]
## Description

RetroArch can't write to external storage by default.
Different Android versions have different restrictions.

For 4.4 there is nothing really that we can do, the OS blocks apps from writing anywhere but a private folder in the SD card so people have to work around the issue themselves:

http://www.instructables.com/id/How-to-bypass-Android-44-KitKat-external-SD-write-/
https://play.google.com/store/apps/details?id=nextapp.sdfix&hl=es_419

In android 5 google changed their mind again, and now you can write but you need to get permissions for a specific folder by declaring this on installation. This could be solved

http://www.androidcentral.com/lollipop-brings-changes-way-your-sd-card-works-kind-youll

More importantly though, on 6.0 up there are two ways you can use external storage. 
- Get permissions via a runtime prompt
- Use adoptable storage

http://stackoverflow.com/questions/32129716/how-does-storage-access-change-on-android-6

The former calls for a solution on our side. The Later should just work

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/4726

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/4150

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/3945

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/pull/4598

**Comment by fr500** [comment]
So, I got the prompt now, I selected allow and I can browse the SD card, gonna test writing to it now

**Comment by fr500** [comment]
I can browse the folders now, but I still can't write.

**Comment by gofirst2220** [comment]
Actually on 6.0 and later, all apps have standard Storage permission, however, you must request permission to have both Read/Write Access for other things like to write to a different folder in Internal Storage or to a SDcard

**Comment by fr500** [comment]
You don't need permission to write in internal storage in any random location

**Comment by gofirst2220** [comment]
@fr500 Really? On my Phone, S6 considers stuff in different ways ``/`` in root, ``/sdcard`` (is same as ``/emulated/0`` IIRC) so sometimes you have to navigate ``/mnt/sdcard`` to get to your regular file directory that S6 opens at when using S6's File manager.

**Comment by bparker06** [comment]
After many hours of testing I'm still unable to write to the sdcard whether from Java or C, even after being granted the runtime read/write permissions, verified them with app manager, killed/restarted the process and the device, etc. etc.

**Comment by bparker06** [comment]
According to [this](https://possiblemobile.com/2014/03/android-external-storage/) page, which is the only documentation I can find that mentions what should or shouldn't be possible with *secondary external storage*, it says that it is not possible for non-system apps to write to arbitrary SD files, only to app-local ephemeral storage that is deleted when the app is uninstalled.

**Comment by fr500** [comment]
It seems there is not much that can be done for a NDK application in this regard. I guess we should add "shortcuts" to the external SD private folders that can be used at least.

IMHO this is by all intents fixed, what's possible has been done.
