### ISSUE TITLE
WASAPI audio driver [$35]

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4776]
Further to this thread on the libretro boards: http://libretro.com/forums/showthread.php?t=5206

I'm inquiring about the possible implementation of a WASAPI audio driver for Windows builds of Retroarch. This kind of solution is very popular in both audio playback and production and it would provide the following benefits:
- higher quality "bitperfect" audio, with the target application taking exclusive control of the audio, bypassing the Windows mixer stack and muting anything else;
- extremely low-latency response.

See original discussion here -

https://github.com/libretro/RetroArch/issues/2771

**Comment by twinaphex** [comment]
@casdevel has a PR which solves this issue for us. He will receive the bounty money.

**Comment by Ryunam** [comment]
Just a quick note highlighting that the driver in question does produce an output and thus works on a basic level, however in its current implementation it also has a few issues that should be taken into account and that have an impact on general use.
Please see the original discussion for more details on my observations: https://github.com/libretro/RetroArch/issues/2771
