### ISSUE TITLE
wayland window decorations

### ISSUE THREAD

**Issue by damopinn** [libretro/RetroArch#4778]
No window decorations when retroarch is compiled with wayland enabled and used in wayland plasma session.

When i compile with wayland disabled or log in an xsession it works as expected

i'm using Debian 9 and KDE desktop. and gcc (Debian 6.3.0-6) 6.3.0 20170205

**Comment by orbea** [comment]
I am going to close this issue in favor of https://github.com/libretro/RetroArch/issues/6278 which has more discussion.
