### ISSUE TITLE
[Feature request] Show essential information on core update screen [$50]

### ISSUE THREAD

**Issue by milesrotaru** [libretro/RetroArch#4781]
![photo_2017-03-25_15-25-34](https://cloud.githubusercontent.com/assets/1683975/24325678/573e5d12-1174-11e7-9993-e998598263d4.jpg)

Attached is a screenshot of the core updater screen from Android using the default theme. This screen along with the other update screens is so uninformative as to be pretty much useless.

The following information needs to be conveyed:

1. What is the full name of each core?
2. Which cores are already installed?
3. Which cores are out of date?
4. What versions do we currently have?

Problem #1 is that although many names are truncated, they do not scroll, and many core names are so badly truncated that they appear as duplicate entries so you can't even determine what to click if you already know the name of the core you want. They should be in a less ridiculously large font or scroll.

Problems #2 and #3 could easily be solved with colour coding. Uninstalled cores should be black, up-to-date ones could be green, and out-of-date ones could be red.

Lastly, #4, the current version number or build date should be displayed beside each core.

The menu above this that shows all the various updaters should indicate whether any currently installed items are out of date for each category, possibly with colour coding as mentioned earlier, and the menu further above that should indicate whether anything whatsoever is out of date, removing a lot of unnecessary menu traversal.

**Comment by milesrotaru** [comment]
$50 bounty posted because the state of the core updater interface is pathetic

**Comment by milesrotaru** [comment]
There's still $50 on this. If nobody cares then close the issue or transfer the bounty to a more appropriate issue.

**Comment by twinaphex** [comment]
@milesrotaru I think some are actually working on better version management for cores, it is just taking other people time to wrestle with the menu code. It is a matter of getting there first, our menu code and HTTP retrieval code is needing a lot of work for it to become a lot more flexible to work with it.
