### ISSUE TITLE
(Bounty) Mouse axis is limited [$20]

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4788]
See this issue for details -

https://github.com/libretro/RetroArch/issues/3408#issuecomment-289782705

**Comment by fr500** [comment]
So this is fixed? there should be a payout to @Tatsuya79 then

**Comment by Tatsuya79** [comment]
I could fix the problem on windows but I think it still affects Linux.
Try to look around with the mouse in Tyrquake or PrBoom.
