### ISSUE TITLE
Input mapping not blocking properly in Windows

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#4789]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When a user tries to use 'bind all' to bind buttons, the button is registered and then immediately inputs actions. This causes, for example, scrolling when mapping L/R or (worse yet) unmappable Y, since it maps and then immediately unmaps itself.

### Expected behavior

When you map a button, it shouldn't accept inputs temporarily, at least from the button that was mapped.

### Actual behavior

It's immediately accepting input from the just-mapped button

### Steps to reproduce the bug

Go to settings > input > p1 input binds > bind all > try to map retropad Y to something and it will immediately unmap itself.

### Bisect Results

unknown

### Version/Commit

RetroArch 1.5.0

Windows 10 64-bit

EDIT: assigning radius, or resident Windows (and input) expert, to see if he can reproduce the behavior.

**Comment by prataczak** [comment]
'Unified Menu Controls' has to be set to 'on' in order to reproduce this bug.

**Comment by fr500** [comment]
It seems an input latching issue... again

**Comment by orbea** [comment]
@hizzlekizzle Do you know if this issue is still valid?

**Comment by hizzlekizzle** [comment]
I don't think this is an issue anymore. Closing.
