### ISSUE TITLE
Find ways to optimize XMB horizontal list scrolling [$10]

### ISSUE THREAD

**Issue by inactive123** [libretro/RetroArch#4792]
See this issue for more details -

https://github.com/libretro/RetroArch/issues/4517

**Comment by RobLoach** [comment]
@Tatsuya79 did some work on this over at #4517 . I created a PR with the option to enable/disable it: https://github.com/libretro/RetroArch/pull/5172

**Comment by CenTdemeern1** [comment]
What about only processing the parts of the playlist file that are currently on screen?
As in, the playlist config file is stored in memory, and is scanned quickly for element count and position.
Then, when the position in the playlist is scrolled on screen, actually process the required part of the config file and load related data.
That would also greatly decrease memory usage, not having all UI elements loaded at once.

I'd like everyone to keep in mind that I don't really know if something like this already exists, or how everything is implemented. I'm just saying what's on my mind.
Please don't judge me for this if this is the new worst idea known to mankind.
