### ISSUE TITLE
Mayflash GameCube adapter crashes upon D-Pad input or using any port that isn't Port 1 (tested on Mac OS X)

### ISSUE THREAD

**Issue by PF2M** [libretro/RetroArch#4793]
## Description

When using a [Mayflash GameCube Adapter for Wii U and PC](https://www.amazon.com/Mayflash-GameCube-Controller-Adapter-Port/dp/B00RSXRLUE) while set to PC mode, RetroArch crashes immediately upon pressing or releasing any of the presses on the D-Pad. It also crashes if it detects that a controller is plugged into any port other than Port 1 on the adapter, at launch or elsewhere. I'm only able to test it on OS X with this particular controller adapter, I'm using official Nintendo GameCube controllers.

### Expected behavior

The application should accept inputs from the USB adapter normally.

### Actual behavior

The application freezes for about a second, then immediately gives [an OS X error](https://dl.dropboxusercontent.com/s/ik9a7nogj6j1xel/crash.png) stating that "RetroArch quit unexpectedly" and providing a crash log, which can be found [here](https://pastebin.com/scNX9MEr). (Ignore the seperate bundle identifier, the name change is completely unrelated and I have since set it back to libretro.RetroArch without it affecting anything)

### Steps to reproduce the bug

1. Open RetroArch and plug in the adapter if it's not plugged in already. Plug in the controller if necessary.
2. If testing ports other than Port 1, the application crashes immediately after launch or as soon as a controller is plugged in. If a GameCube controller is plugged into Port 1, then pressing or releasing any direction on the D-Pad of the controller causes a crash.

### Bisect Results

This has happened whenever I've tried to use it, both on 1.5.0 and on the latest nightly (03/31/2017). This is not a controller/adapter/device error, as I have been able to use the D-Pad and all four ports using the OS X program [Enjoy2](https://github.com/fyhuang/enjoy2) and the Windows version of the program [antimicro](https://github.com/AntiMicro/antimicro) without any issues.

### Version/Commit

This happens on 1.5.0 and on the latest nightly, the crash log I provided above is from 1.5.0.

### Environment information

- OS: Mac OS X 10.10.5
- Compiler: Not applicable, I downloaded both builds from buildbot.libretro.com.
More info can be found in the crash log, I will provide anything else if necessary.

**Comment by golanklinger** [comment]
I am experiencing a similar situation with the Mayflash Wireless Wii U Pro Controller to PC USB Adapter. As soon as I press a key, RetroArch crashes.

**Comment by prototypeshogun** [comment]
Still happening. Wish I had found this thread before I bought this adapter.

**Comment by aschain** [comment]
I just put in a [pull request](https://github.com/libretro/RetroArch/pull/10545) (that was incorporated) that fixed a similar problem I had with my Mayflash N64 adapter (crash on DPAD keypress). Maybe someone can test these other controllers?

**Comment by ComradeEcho** [comment]
I just tested this on on macOS 11.5.1 using a mayflash gamecube controller adapter.
This appears to be fixed as of fb28c79e13e303eaa9aec593391a8baa2bc733d0
