### ISSUE TITLE
Fast forward or rewind not work while using analog stick

### ISSUE THREAD

**Issue by iowbeoibewio** [libretro/RetroArch#4798]
In Android 6.0.1

While using analog stick, you can't active fast forward or rewind.
Fast forward work perfectly with D-Pad, but not rewind.

problem appear in PCSXR + FCEUmm
Not tested in other cores

noticed problem in 1.3.6 and later, not sure for below 1.3.6

**Comment by fr500** [comment]
fast forward works fine for me...
