### ISSUE TITLE
[Vita] Mega Drive II roms only shown if 7zipped

### ISSUE THREAD

**Issue by NHellFire** [libretro/RetroArch#4799]
On my Vita, RetroArch is only showing 7zipped Mega Drive II roms. Zipped and plain are ignored.
I've tried RetroArch 1.5.0 and nightly 2017-04-04, same result. 1.5.0 on Windows shows all formats.
See attached screenshots of RetroArch and VitaShell.
![vitashell](https://cloud.githubusercontent.com/assets/1146987/24678911/58a67884-1984-11e7-9ad4-668df4619f72.jpg)
![retroarch](https://cloud.githubusercontent.com/assets/1146987/24678910/58a63946-1984-11e7-961e-a655b5fdf9eb.jpg)

**Comment by frangarcj** [comment]
Try next working nightly. It should be fixed

**Comment by frangarcj** [comment]
@NHellFire Should I close this?

**Comment by NHellFire** [comment]
I've not had a chance to try again. Hopefully I'll be able to in the next
few days

**Comment by NHellFire** [comment]
Yep, fixed. This can be closed now
Thanks!
