### ISSUE TITLE
Question: How are zip/7z files processed?

### ISSUE THREAD

**Issue by NHellFire** [libretro/RetroArch#4800]
On my Vita, scanning them seems quite slow, so I'm wondering if they're unpacked to a temp directory to check the hash?
Checking the CRC doesn't require unpacking, it can be read from the archive headers.

**Comment by bparker06** [comment]
No they are not unpacked, and the CRC for both formats is checked directly from the headers. The only slowdown I know of with scanning right now is the initial list building process when you have a lot of archives. The process consists of opening every archive and getting a file listing for it, creating a full path to each file within the archive, e.g. /path/to/archive.zip#somefileinside.rom. Then after the list is built, it iterates through the archives again to grab the CRCs from the metadata and compare that against the databases. It also causes a freeze of the main UI as the list building is not done as a separate task/thread like it could be. This is something we'd like to improve but so far I'm not aware of anyone working on it at the moment.

**Comment by fr500** [comment]
IMHO, The problem with the current approach is that it uses a LOT of RAM on big collections.

**Comment by NHellFire** [comment]
Thanks. I'm guessing it's the database lookup being slow on my Vita then.

**Comment by twinaphex** [comment]
File I/O should probably be receiving a boost now thanks to @frangarcj's patches.
