### ISSUE TITLE
When game is Paused("P"), cannot go back into game from quickmenu

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#4802]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When a game is paused using the "P" key(not the emulator/core' pause), when you enter quick menu you cannot go back into the game.

### Expected behavior

when pressing Menu Hotkey, it should bring you back into the game(still paused

### Actual behavior

you get stuck at menu entries and pressing quickmenu hotkey(F1, Guide button on 360, Menu Toggle Hotney) will just loop you back into menu.

### Steps to reproduce the bug

1. run game
2. press "P" or whatever is Pause hotkey( not the game's Pause or Start to pause)
3. press quick menu and wonder around if you will :D
4. press quick menu to go back into game(but you cant now and will look back into menu)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Windows 10 x64
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
@retro-wertz I tested this with the master and the current behavior is that toggling the menu works, but it will also unpause the game...

**Comment by retro-wertz** [comment]
i cant remember anyways what exactly the issue i had with these but at the moment, pausing the game with P then quick menu, then going back to the game seems to without but its unpaused, which is not that big of an issue now. you can close this for now and ill just update this when i get windows setup properly

**Comment by orbea** [comment]
I bisected this to where the behavior changed.
```
66b1ad99d42b37b46912b08dc055aa3f07a6027d is the first bad commit
commit 66b1ad99d42b37b46912b08dc055aa3f07a6027d
Author: twinaphex <libretro@gmail.com>
Date:   Sun May 21 12:59:36 2017 +0200

    Rewrite RARCH_PAUSE_TOGGLE

:100644 100644 749946d85c112880b3f4ee2fee63e31272df3eb9 05437fb8b47251fc3d9d1f30838cf3540ed8e763 M	retroarch.c
```
66b1ad99d42b37b46912b08dc055aa3f07a6027d
