### ISSUE TITLE
Menu item inconsistency

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#4805]
"Save State" and "Load State" close the menu along with there "Undo" options but "Restart" does not.

This was one of the issues with my rebootemu hack for pcsx_rearmed:
https://github.com/libretro/pcsx_rearmed/commit/53e4a7e5cb46ad8589825ec95e15b56614cc54d9

There pushing restart then load state would break the load state, but only one menu option should be possible at once.

**Comment by orbea** [comment]
@meepingsnesroms I submitted a PR to fix this, can you test it?
https://github.com/libretro/RetroArch/pull/5579
