### ISSUE TITLE
MOD support for audio mixer system (libretro-common) [$10]

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4810]
Add MOD support for the audio mixer contained inside Libretro-common.

Prerequisites for fulfilling the bounty:
- It needs to work with random .MOD files.
- The code should be licensed MIT so that it can be included inside libretro-common.
- The code should be in C.

**Comment by jonmcclay** [comment]
I'm considering a bounty. If it isn't completed after x days, can you get your money back?

**Comment by larrykoubiak** [comment]
If a BSD clause-3 license is OK, i think micromod could do the job nicely, it's a one-filer written in C : https://github.com/martincameron/micromod/tree/master/micromod-c (the other file are just IO and resampling which is already in libretro-common)

**Comment by rtissera** [comment]
Can anyone confirm bsd license is okay? I am experimenting on an implementation based on ibxm (part of micromod repository).

**Comment by twinaphex** [comment]
libretro-common (which I think would be where this code is going to belong to) is MIT-licensed. If that is BSD-compatible, then sure.

**Comment by twinaphex** [comment]
I'm fine with it personally. Not sure if that is enough for you to want to move forward with it, but I basically don't see a huge issue.

**Comment by rtissera** [comment]
Double checking here makes me confident on the legal side. 

http://janelia-flyem.github.io/licenses.html

**Comment by twinaphex** [comment]
Sure, I think instead of licensing, the main issue is more how big the code is going to be, if there are any dependencies, etc. Usually in libretro-common we prefer things to be as modular as possible and with as few dependencies as possible. From that perspective, libchdr was very much aligned with those goals (well, it adds a FLAC dependency but that is inavoidable anyways). Libretro-common also is exclusively C code.

**Comment by larrykoubiak** [comment]
The reason i suggested micromod/ibxm is that it's totally self-contained, and a one filer. For some reason though, the ibxm code is made to output a wave file and contains no replay code, but that shouldn't be too much of an issue.
Apologies for not having worked on this btw, got caught up with work these past few months, so i'm adding to the bounty as i think it's a useful feature

**Comment by rtissera** [comment]
PR pushed here : https://github.com/libretro/RetroArch/pull/5244
Needs some ironing out, I'm a bit lost in GUI code.

**Comment by rtissera** [comment]
New PR pushed to properly mix MOD and core generated audio.

**Comment by rtissera** [comment]
Is this one considered okay ?

**Comment by twinaphex** [comment]
Yes, I tested it and the mixing is performed correctly.

**Comment by twinaphex** [comment]
Let me close the issue so the bounty checkout can proceed.

**Comment by larrykoubiak** [comment]
Just fyi, and to amend what i wrote on bountysource, the mixing in core works, but you can't "run" it because ffmpeg isn't happy with it for some reason. Like i said, awesome work :1st_place_medal:
