### ISSUE TITLE
Any way to add Hack Roms to RetroArch on android?

### ISSUE THREAD

**Issue by miimiics** [libretro/RetroArch#4811]
So, I got an android tv box dedicated to RetroArch, I got most of the things I want working, only problem is if I try to add a Hack rom (like a Pokemon Hacked ROM) it will not add it to my library, though i can select it manually and it will work, anyways after reading more on it I guess it has to be an official game on their games list or something to work? Is there any way I can add this game to the GBA library?

**Comment by miimiics** [comment]
Just read that this isnt a help thread i guess, sorry for putting this here but i dont know where else to post :/

**Comment by hizzlekizzle** [comment]
Hey, yeah, this isn't a good place for support, but no big deal. There are many threads about this on the libretro forums.

**Comment by miimiics** [comment]
Do you know if this is possible? ive been looking for days now and I dont see any way to do it on android :(

**Comment by hizzlekizzle** [comment]
Yes, there's a utility on the forum called 'playlist buddy' that can make playlists that sidestep RetroArch's own scanner.
