### ISSUE TITLE
Cannot subscribe to RSS because of Cloudflare

### ISSUE THREAD

**Issue by gsantner** [libretro/RetroArch#4812]
Hi there,
I tried to subscribe to libretro RSS feed (<https://www.libretro.com/index.php/feed/>) and I keep getting 403 errors because of Cloudflare. Of course, a RSS feed client is not a human..

As I didn't found any contact adress, or any other section to ask about the website, I'am asking here:

Please turn off Cloudflare for RSS path. Really nice this project is open source and so, but restricted access to e.g. the project homepage is bad.

![grafik](https://cloud.githubusercontent.com/assets/6735650/24831824/1c3ef512-1ca2-11e7-98d8-c5013e63e7cb.png)

**Comment by meepingsnesroms** [comment]
We should not be using cloudflare at all, I use tor because the retarded US government just removed all privacy laws for isps and have to do a captcha every time I want to check the forums because I cant be "verified" by cloudflare.

**Comment by fr500** [comment]
Bandwidth is not free.
Cloudflare is.

**Comment by meepingsnesroms** [comment]
Cloudflare does not give you extra bandwidth though.

It intercepts all your web traffic and blocks what it thinks could be a ddos attack.

Has this project been ddosed before?

**Comment by fr500** [comment]
Of course it does.
It gives you extra bandwidth because it functions as a reverse proxy caching static content.
At least 70% of buildbot bandwidth is served directly by CF.

**Comment by gsantner** [comment]
This issue is not in general about/against/for cloudflare. It is, that this project is serving RSS/ATOM feeds. This is content that is made for bots and machine, not for humans; Humans usually don't retrieve these. A bot can't/shouldn't answer those "security checks". In this case CF breaks a feature of the site, and I am asking to deactivate it on this specific case.

**Comment by fr500** [comment]
I don't have more page rules, we would have to move to a paid for plan.

**Comment by meepingsnesroms** [comment]
I was not aware of that, I will try to just find a way to hack the captcha then.

**Comment by fr500** [comment]
@gsantner well not sure about your aggregator but I use feedly and both forum and blog RSS feeds work fine for me
