### ISSUE TITLE
Android] Back button not recognized

### ISSUE THREAD

**Issue by gsantner** [libretro/RetroArch#4814]
## Description
While browsing the RetroArch menu I tried multiple times to go 
back in menu with pressing the system back button.
I also tried to assign the back button to e.g. "B" in Inputs, buz its not   recognized.

### Expected
That android back button actually does go back. If going back is not available (e.g. while playing a game) thr retroarch menu should come up. 

#### Actual
See above.

### Steps to reproduce the bug

1. Press back
2. Wait for something to happen
3. Nothing happens...

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
1.5.0

### Environment information

- OS: Android 7

**Comment by mustang5point0** [comment]
I can verify this problem also occurs on my Galaxy S4 (Android 4.3). I have gotten stuck in specific screens (eg.. Help - It loads a blank white overlay and eventually Help notes show up after touching the screen many times. Cannot BACK out of the Help screen as the Back button does nothing. Anytime I try to load any Overlays, it loads it, but then gets stuck and can't exit that screen at all without pressing Home button and then killing it with a task manager. Same goes for if you are in a game and you do either of these 2 things...... 1.You press FF/Slow-mo and.... 2.You accidently close the onscreen controls. Once you do either of those, you are completely SOL and have to kill it with a task manager.).

**Comment by sm-code-ro** [comment]
👍  Same on `GPD XD` running LegacyRom (Android 4.4), back does nothing.

**Comment by Jeppesen-io** [comment]
👍 
Same thing on my device - back does nothing.
`GPD XD` on `Android 4.4`

**Comment by gsantner** [comment]
I see this bug is still present for the third year, can be closed right as anyway nobody cares ?

**Comment by hizzlekizzle** [comment]
As I understand it, it's not that no one cares, but that this is intended behavior. That is, many controllers (such as xbox pads) map 'select' to the 'back' button, so if we support the back button in Android, it means any time someone connects such a pad to their Android device, they have to bind 'select' to some other button because that button is dedicated to the 'back' task instead.

I don't recall what other programs do the same, but it's not entirely unusual.

**Comment by gsantner** [comment]
The bug is now open since 2017. Not looks like it will lead anywhere. Closing.
