### ISSUE TITLE
Analog up/down recognized, but not working as expected

### ISSUE THREAD

**Issue by gsantner** [libretro/RetroArch#4815]
## Description
I assigned both, analog left up/down, and they are both correctly recognized from my gamepad. But the input settings I set are not applied somehow. Doesn't matter if I set `User 1 Left analog Y+ (down)` to axis +1 or -1 ;; or`User 1 Left analog Y- (up)` to +1 or -1, real anlog up does always move down, real anlog down always moves up. I want RetroArch to use input as setted, I don't know why it doesnt apply those settings. As said above, the inputs are correctly recognized. This is also no inverse up/down related stuff, as I already tried to do this manually by setting down up, and up down.

See screenshots:
![screenshot_20170409-160740](https://cloud.githubusercontent.com/assets/6735650/24837966/bb3ea322-1d3f-11e7-8720-e9fab8b8f3cd.png)
![screenshot_20170409-160731](https://cloud.githubusercontent.com/assets/6735650/24837965/bb3e3964-1d3f-11e7-82ef-ee64503ca998.png)

### Expected behavior
When I press analog up, I expect up if I assigned it to up.
When I press analog down, I expect down if I assigned it to down.

### Actual behavior
See above.

### Steps to reproduce the bug
See above.

### Version/Commit
- RetroArch:  1.5.0

### Environment information

- OS: Android 7

**Comment by orbea** [comment]
@gsantner Is this issue still present with the nightlies?
