### ISSUE TITLE
GUI Corruption

### ISSUE THREAD

**Issue by razorache** [libretro/RetroArch#4823]
![0415170129](https://cloud.githubusercontent.com/assets/19499190/25061089/325d40a4-217c-11e7-8a04-c03f57f97335.jpg)

Random Icon and text corruption. Happens in both Vulkan and GL drivers

**Comment by fr500** [comment]
Bug submission guidelines are there for a reason, please read the guidelines that appear when you attempt to create an issue and repost accordingly
