### ISSUE TITLE
(Launchbox) Unable to save any input settings

### ISSUE THREAD

**Issue by raccoonmario3** [libretro/RetroArch#4825]
Whenever I make changes to input settings, such as controller mappings, or even changing keyboard mappings, they fail to stick after I quit and relaunch. I verified that all of my directories were correct. I am running Retroarch on Windows 10 through Launchbox. Other settings save fine, such as when I change core specific settings, or driver settings. Only input settings fail to save no matter what. They always revert back to whatever they were before when I relaunch. 

The strangest thing is that I used to be able to save these settings, but now, after countless hours of messing around with the configurations in order to get an NES controller working with an adapter, it doesn't work, even with my PS3 controller, which used to work perfectly, but now I can't make any changes to the mappings. 

The only way in which I am able to get controls in some cores to work is to map the controller buttons to the keyboard using software like Pinnacle Game Profiler. The problem with that is that it relies upon Retroarch having default keyboard controls already set up, which is not the case with players 2, 3, 4, etc. This means that games like Raiders of the Lost Ark on Atari 2600, a single player game that require two controllers, won't work, unless I configure the controller each time I start the emulator up.

Also, I am using the latest version of Retroarch, 1.5.0, with the latest versions of all the cores.

**Comment by fr500** [comment]
Well, try without launchbox, who knows what it might be doing.
Inputs do not save in overrides btw. So maybe it's using those.

**Comment by fr500** [comment]
Closing because no feedback
