### ISSUE TITLE
Error while compiling on  Debian 8.7 jessie 3.16.39-1+deb8u2 x86_64 

### ISSUE THREAD

**Issue by kaedwood** [libretro/RetroArch#4830]
This is the output of the compiler:
debian@kaed:~/libretro-super/retroarch $  make DESTDIR=~/ra install
CC input/drivers/linuxraw_input.c
CC input/common/linux_common.c
CC input/common/epoll_common.c
CC input/drivers_joypad/linuxraw_joypad.c
CC frontend/drivers/platform_linux.c
CC version_git.c
CC frontend/frontend.c
CC frontend/frontend_driver.c
CC frontend/drivers/platform_null.c
CC ui/ui_companion_driver.c
CC ui/drivers/ui_null.c
CC ui/drivers/null/ui_null_window.c
CC ui/drivers/null/ui_null_browser_window.c
CC ui/drivers/null/ui_null_msg_window.c
CC ui/drivers/null/ui_null_application.c
CC core_impl.c
CC retroarch.c
CC dirs.c
CC paths.c
CC input/input_keyboard.c
CC command.c
CC msg_hash.c
CC intl/msg_hash_us.c
CC runloop.c
CC libretro-common/queues/task_queue.c
CC tasks/task_content.c
CC tasks/task_save.c
CC tasks/task_file_transfer.c
CC tasks/task_image.c
CC libretro-common/encodings/encoding_utf.c
CC libretro-common/encodings/encoding_crc32.c
CC libretro-common/lists/file_list.c
CC libretro-common/lists/dir_list.c
CC libretro-common/file/retro_dirent.c
CC libretro-common/streams/file_stream.c
CC libretro-common/streams/interface_stream.c
CC libretro-common/streams/memory_stream.c
CC libretro-common/file/retro_stat.c
CC libretro-common/lists/string_list.c
CC libretro-common/string/stdstring.c
CC libretro-common/memmap/memalign.c
CC setting_list.c
CC list_special.c
CC libretro-common/file/nbio/nbio_stdio.c
CC libretro-common/file/file_path.c
CC file_path_special.c
CC file_path_str.c
CC libretro-common/hash/rhash.c
CC audio/audio_driver.c
CC libretro-common/audio/audio_mixer.c
CC input/input_driver.c
CC gfx/video_coord_array.c
CC gfx/video_driver.c
CC camera/camera_driver.c
CC wifi/wifi_driver.c
CC location/location_driver.c
CC driver.c
CC configuration.c
CC libretro-common/dynamic/dylib.c
CC dynamic.c
CC cores/dynamic_dummy.c
CC libretro-common/queues/message_queue.c
CC managers/core_manager.c
CC managers/state_manager.c
CC gfx/drivers_font_renderer/bitmapfont.c
CC tasks/task_autodetect.c
CC input/input_autodetect_builtin.c
CC input/input_joypad_driver.c
CC input/input_config.c
CC input/input_keymaps.c
CC input/input_remapping.c
CC tasks/task_overlay.c
CC input/input_overlay.c
CC libretro-common/queues/fifo_queue.c
CC managers/core_option_manager.c
CC libretro-common/compat/compat_fnmatch.c
CC libretro-common/compat/compat_posix_string.c
CC managers/cheat_manager.c
CC core_info.c
CC libretro-common/file/config_file.c
CC libretro-common/file/config_file_userdata.c
CC tasks/task_screenshot.c
CC tasks/task_powerstate.c
CC libretro-common/gfx/scaler/scaler.c
CC gfx/drivers_shader/shader_null.c
CC gfx/video_shader_driver.c
CC gfx/video_shader_parse.c
CC libretro-common/gfx/scaler/pixconv.c
CC libretro-common/gfx/scaler/scaler_int.c
CC libretro-common/gfx/scaler/scaler_filter.c
libretro-common/gfx/scaler/scaler_filter.c: In function ‘scaler_gen_filter’:
libretro-common/gfx/scaler/scaler_filter.c:219:89: warning: ‘sinc_size’ may be used uninitialized in this function [-Wmaybe-uninitialized]
          x_pos  = (1 << 15) * ctx->in_width / ctx->out_width   - (1 << 15) - (sinc_size << 15);
                                                                                         ^
CC gfx/font_driver.c
CC gfx/video_filter.c
CC libretro-common/audio/resampler/audio_resampler.c
CC libretro-common/audio/dsp_filter.c
CC libretro-common/audio/resampler/drivers/sinc_resampler.c
CC libretro-common/audio/resampler/drivers/nearest_resampler.c
CC libretro-common/audio/resampler/drivers/null_resampler.c
CC location/drivers/nulllocation.c
CC camera/drivers/nullcamera.c
CC wifi/drivers/nullwifi.c
CC gfx/drivers/nullgfx.c
CC audio/drivers/nullaudio.c
CC input/drivers/nullinput.c
CC input/drivers_hid/null_hid.c
CC input/drivers_joypad/null_joypad.c
CC playlist.c
CC movie.c
CC record/record_driver.c
CC record/drivers/record_null.c
CC libretro-common/features/features_cpu.c
CC performance_counters.c
CC verbosity.c
CC audio/drivers_resampler/cc_resampler.c
CC intl/msg_hash_de.c
CC intl/msg_hash_eo.c
CC intl/msg_hash_es.c
CC intl/msg_hash_fr.c
CC intl/msg_hash_it.c
CC intl/msg_hash_ja.c
CC intl/msg_hash_ko.c
CC intl/msg_hash_nl.c
CC intl/msg_hash_pl.c
CC intl/msg_hash_pt_br.c
CC intl/msg_hash_pt_pt.c
CC intl/msg_hash_ru.c
CC intl/msg_hash_vn.c
CC intl/msg_hash_chs.c
CC libretro-common/compat/compat_strl.c
CC libretro-common/formats/image_texture.c
CC cores/libretro-imageviewer/image_core.c
CC libretro-db/bintree.c
CC libretro-db/libretrodb.c
CC libretro-db/query.c
CC libretro-db/rmsgpack.c
CC libretro-db/rmsgpack_dom.c
CC database_info.c
CC tasks/task_database.c
CC tasks/task_database_cue.c
CC audio/drivers/oss.c
CC audio/drivers/alsa.c
CC audio/drivers/alsathread.c
CC audio/drivers/openal.c
CC audio/drivers/jack.c
CC audio/drivers/pulse.c
CC libretro-common/audio/conversion/s16_to_float.c
CC libretro-common/audio/conversion/float_to_s16.c
CC libretro-common/audio/audio_mix.c
CC libretro-common/formats/wav/rwav.c
CC menu/drivers/rgui.c
CC menu/drivers/materialui.c
CC menu/drivers/xmb.c
CC menu/menu_driver.c
CC menu/menu_content.c
CC menu/menu_input.c
CC menu/menu_event.c
CC menu/menu_entries.c
CC menu/menu_navigation.c
CC menu/menu_setting.c
CC menu/menu_shader.c
CC menu/widgets/menu_filebrowser.c
CC menu/widgets/menu_dialog.c
CC menu/widgets/menu_input_dialog.c
CC menu/widgets/menu_input_bind_dialog.c
CC menu/widgets/menu_entry.c
CC menu/widgets/menu_list.c
CC menu/widgets/menu_osk.c
CC menu/menu_cbs.c
CC menu/cbs/menu_cbs_ok.c
CC menu/cbs/menu_cbs_cancel.c
CC menu/cbs/menu_cbs_select.c
CC menu/cbs/menu_cbs_start.c
CC menu/cbs/menu_cbs_info.c
CC menu/cbs/menu_cbs_refresh.c
CC menu/cbs/menu_cbs_left.c
CC menu/cbs/menu_cbs_right.c
CC menu/cbs/menu_cbs_deferred_push.c
CC menu/cbs/menu_cbs_scan.c
CC menu/cbs/menu_cbs_get_value.c
CC menu/cbs/menu_cbs_label.c
CC menu/cbs/menu_cbs_sublabel.c
CC menu/cbs/menu_cbs_title.c
CC menu/cbs/menu_cbs_up.c
CC menu/cbs/menu_cbs_down.c
CC menu/cbs/menu_cbs_contentlist_switch.c
CC menu/menu_display.c
CC menu/menu_displaylist.c
CC menu/menu_animation.c
CC menu/drivers_display/menu_display_null.c
CC menu/drivers/menu_generic.c
CC menu/drivers/null.c
CC gfx/drivers_font_renderer/stb.c
CC gfx/drivers_font_renderer/stb_unicode.c
CC gfx/drivers_font_renderer/freetype.c
CC libretro-common/rthreads/rthreads.c
CC libretro-common/rthreads/rsemaphore.c
CC gfx/video_thread_wrapper.c
CC audio/audio_thread_wrapper.c
CC gfx/drivers_context/wayland_ctx.c
gfx/drivers_context/wayland_ctx.c: In function ‘gfx_ctx_wl_init’:
gfx/drivers_context/wayland_ctx.c:903:19: error: ‘EGL_PLATFORM_WAYLAND_KHR’ undeclared (first use in this function)
                   EGL_PLATFORM_WAYLAND_KHR,
                   ^
gfx/drivers_context/wayland_ctx.c:903:19: note: each undeclared identifier is reported only once for each function it appears in
Makefile:155: recipe for target 'obj-unix/gfx/drivers_context/wayland_ctx.o' failed
make: *** [obj-unix/gfx/drivers_context/wayland_ctx.o] Error 1

**Comment by sergiobenrocha2** [comment]
Build with  --disable-wayland --disable-egl  for now, see: https://github.com/libretro/RetroArch/pull/4826#discussion_r111792631

**Comment by twinaphex** [comment]
Should be fixed now as of this PR -

https://github.com/libretro/RetroArch/pull/4833

**Comment by sergiobenrocha2** [comment]
It's building now, kms working again on ubuntu 14.04

**Comment by kaedwood** [comment]
Works fine!
./configure  --disable-wayland --disable-egl --disable-ffmpeg

Thanks

**Comment by sergiobenrocha2** [comment]
Uh, you don't need --disable-wayland --disable-egl anymore...

**Comment by kaedwood** [comment]
Ok, after building with the parameters an error occurred!
Makefile:155: recipe for target 'obj-unix/cores/libretro-ffmpeg/ffmpeg_core.o' failed make: *** [obj-unix/cores/libretro-ffmpeg/ffmpeg_core.o] Error 1

./configure --disable-wayland --disable-egl --disable-ffmpeg

works perfectly

**Comment by sergiobenrocha2** [comment]
Just use --disable-ffmpeg as pointed in the error

**Comment by twinaphex** [comment]
Why won't it compile without --disable-ffmpeg?

**Comment by sergiobenrocha2** [comment]
Old libs I guess. I can only build with ffmpeg support in 16.04 and later
