### ISSUE TITLE
No Sound suddenly - Gnome Ubuntu 17.04

### ISSUE THREAD

**Issue by neosquid** [libretro/RetroArch#4834]
Build Date Apr 19 2017 

I've been running Retroarch for the past few days - everything seemed great until today, suddenly there is no sound output. All other applications in Gnome run with sound.

I deleted the retroarch.cfg and restarted to reset the config file - still no luck.

**Comment by retro-wertz** [comment]
works fine here, latest retroarch but im  still on ubuntu 16.04-based.

**Comment by SuperMeatBro** [comment]
The today's nightly is fine, but yesterday i was having this sound issue.

**Comment by neosquid** [comment]
Seems to have resolved itself this morning, initially, no sound. I restarted Retroarch and the sound magically started functioning.
