### ISSUE TITLE
Save files not written on forced close or crashes

### ISSUE THREAD

**Issue by rrooij** [libretro/RetroArch#4837]
## Description

When a computer crashes or RetroArch is forced to close in another way in which it can't handle the SIGTERM signal, it will not write save files. This can be pretty annoying when you're far in a game but lose progress because of a computer crash, empty laptop battery or unresponsive OS. You name it.

I had this problem on the snes9x core, but I tested it with other cores (in this case bsnes-mercury too) and the same thing happens.

This problem is worse on Android, since force closing the app will also discard the save games. It is pretty common practice on Android by people to close their apps with this method:

https://www.youtube.com/watch?v=lg7rX4MrkME

Skip to 0:23. It won't trigger the save function this way. Someone I know lost a lot of Pokemon progress this way.

### Expected behavior

I expect the SRAM to be written the exact moment I save in a game.

### Actual behavior

The SRAM is written on close, but this is not always reliable since computers tend to crash sometimes.

### Steps to reproduce the bug

1. Start a game
2. Save somewhere
3. Try killing RetroArch by using `kill -9 [retroarch's process id]`
4. Your save is gone

### Bisect Results

As far as I know, this has always been the case in RetroArch.

### Version/Commit
You can find this information under Information/System Information

```
RetroArch: Frontend for libretro -- v1.5.0 -- dd1da5154 --
```

### Environment information

- OS: Debian Stretch
- Compiler: GCC (6.3.0) 64-bitBuilt: Apr 21 2017

### Proposed solutions

Do the following by default or let the user set it in the options: 
1. Write to the SRAM file when SRAM gets written. The downside is that it can cause more disk I/O than needed in most cases. However, this can be explained in the option entry.
2. Set a timer which writes to SRAM periodically. The user can configure the timer which it sees as necessary.

**Comment by hizzlekizzle** [comment]
This is working as intended.

solution 1 isn't doable because some cores use SRAM for actual scratch RAM and write to it constantly.

solution 2 already exists. Settings > saving > SRAM autosave interval.

**Comment by rrooij** [comment]
How did I miss this? I'm sorry for my bug report. Thanks for the great feature.

**Comment by mlfarrell** [comment]
ARE YOU MOTHER FUCKING KIDDING ME??! I JUST LOST TWO HOURS OF PROGRESS BECAUSE YOU DON’T KNOW HOW TO FUCKING PROGRAM. THIS EMULATOR IS A PIECE OF FUCKING SHIT!!
