### ISSUE TITLE
Load Bsnes "game folders" like roms, not folders

### ISSUE THREAD

**Issue by DukeJP** [libretro/RetroArch#4838]
First of all, i have al my roms in Higan (Bsnes) format, with folders like, example:
"Mario Kart.sfc"  and inside this folder "program.rom" "saveram" etc.
In Higan, when i double clic the folder "Mario Kart.sfc", launch the game.
But when i select "Mario Kart.sfc" in the Retroarch gui, the folder opens. I must select "program.rom" or "manifest.bml" to lauch the game.
I have no problem with that, but in the "history" list, i get a bunch of "program" list with no clue about what game belongs.

**Comment by fr500** [comment]
In any case this is a issue with the bsnes-libretro core not with RetroArch.
Just rename manifest.bml to Mario Kart.bml

**Comment by DukeJP** [comment]
Yes, you are right. This folder system is a PITA, but i cant back from this system to te old zip format... 
Thanks for your solution.
