### ISSUE TITLE
Can see any hidden folders on linux

### ISSUE THREAD

**Issue by damopinn** [libretro/RetroArch#4845]
Can see any hidden folders on Debian 9.

When setting folder i should be able to browse to .config folder when you have enabled show hidden files.

even with show hidden files is enabled you cant see them

This problem wasnt there when i built and installed about 1 month ago or in version 1.5

gcc (Debian 6.3.0-14)

**Comment by RobLoach** [comment]
Believe this is fixed.

**Comment by twinaphex** [comment]
I will close it then. If the issue persists, he can open this again.
