### ISSUE TITLE
Audio driver start function doesn't get called in some cases

### ISSUE THREAD

**Issue by casdevel** [libretro/RetroArch#4847]
When "Pause when menu active" option is set to off, audio driver start function never gets called.
Init and write functions are called, but between them there is no call to start. This also happens when toggling fullscreen.
Now, if audio driver is expected to start immediately upon initialization this is not a bug, but I don't know that right now.

This is also true for audio driver set nonblock state. Since this is related to the previous issue I didn't wanted to open another one.

RetroArch v1.5.0 (26 April 2017), Windows10 x64, GCC 6.3.0 (MSYS2).

**Comment by casdevel** [comment]
@twinaphex Since this problem is solved within WASAPI driver code, maybe I should close this issue?

**Comment by twinaphex** [comment]
Sure, if there are no remaining issues, then go ahead.
