### ISSUE TITLE
[Direct3D] Create a Direct3D 11/12 backend for the D3D driver [$160]

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4854]
Right now, our current Direct3D driver has a couple of limitations:

1 - It is Direct3D 9 only, and requires the Cg toolkit in order to work.
2 - It only works with the RGUI menu driver. There does exist a menu_display_driver_d3d file, but it's unfinished, and right now it only renders text in XMB.

For the purposes of this bounty, we are looking for somebody who can achieve the following:

1 - Write a Direct3D 11/12 driver. The exact implementation we leave up to you, but it would be best if there is still the possibility to use the old Direct3D 9 codepath for systems that don't support Direct3D11.
2 - Finish up the Direct3D menu display driver so that it can properly render a menu driver like XMB and MaterialUI.

**Implementation details/advice**

Some further advice if you decide to take this bounty on - some of the most important files to look into would be -

https://github.com/libretro/RetroArch/blob/master/gfx/common/d3d_common.cpp

We don't make straight Direct3D calls inside gfx/drivers/direct3d.cpp. Instead, we make wrapper functions that call the Direct3D functions instead. We would prefer that you add the Direct3D 11 functions to this file and use 'defines' like HAVE_D3D11 / HAVE_D3D12.

Second file of interest -

https://github.com/libretro/RetroArch/blob/master/gfx/drivers_renderchain/d3d9_cg_renderchain.cpp

This is the Direct3D 9 Cg renderchain right now. For the Direct 3D 11/12 codepath, you'd make a new renderchain file for each and implement the necessary functions.

Third file of interest -

https://github.com/libretro/RetroArch/blob/master/gfx/drivers/d3d.cpp

This is the main Direct3D driver. It mainly talks to the renderchain driver and it calls functions from d3d_common.cpp

Fourth file of interest -

https://github.com/libretro/RetroArch/blob/master/menu/drivers_display/menu_display_d3d.cpp

This is the Direct3D menu display driver. This is responsible for drawing hardware accelerated menu drivers like MaterialUI and XMB. Right now, this implementation is incomplete; textures and vertices are not rendered so the only thing that appears when you are using the XMB with Direct3D right now is text being rendered, and only yellow text at that because the Direct3D font driver is very unsophisticated right now.

We are going to start out with an initial $25 and add some more money to it shortly.

**Comment by fidelis1** [comment]
@twinaphex prataczak added another $30 on Bountysource, so the bounty is at $115 now.

**Comment by aliaspider** [comment]
anything else that still needs to be done here ?

**Comment by twinaphex** [comment]
I think everything is fulfilled here pretty much. Maybe there might still be some minor details that we might not be aware of, but that can be sorted out later on, and the bounty itself could be considered to be finished.

**Comment by twinaphex** [comment]
Hi there @prataczak, could you please go to Bountysource and accept the solution so that this bounty is finalized?

**Comment by prataczak** [comment]
Done.

**Comment by twinaphex** [comment]
Awesome. Thanks @aliaspider and everybody involved for successfully seeing this through.
