### ISSUE TITLE
Option for "no screenshot" in library?

### ISSUE THREAD

**Issue by DeckardEdward** [libretro/RetroArch#4870]
I've been toying with Retroarch for a while now, and whenever I scroll through my library I keep noticing that long game titles wind up with text cutoff whenever the boxart/screenshot is being displayed. With large text settings, even average-length game titles can wind up being cut off by this.

Another thing that keeps catching my eye about the boxart/screenshot setup is that not all games have all three pictures provided; some are missing boxarts, some are missing action screens, and some are missing title screens. It seems odd to me when the changing images on the right of the screen occasionally disappear while I'm scrolling through my library.

As a quick and easy alternative to investing a bunch of unnecessary effort reworking the entire UI to make these anomalies seem more natural, I propose simply inserting a fourth option into the screenshot display order: "no screenshot". That way, all titles have more room to play their text out, all entries are made visually equal, and the option to preview what a given game is all about is still available to the user as they scroll through.

**Comment by bparker06** [comment]
The menu setting for which thumbnail to show already has an "off" option, so I'm not sure what you are suggesting.

**Comment by DeckardEdward** [comment]
I'm suggesting the ability to cycle to "off" from within the library by pushing Y.

**Comment by bparker06** [comment]
Ah ok. I just added this in a568782.

**Comment by bparker06** [comment]
@DeckardEdward Can you confirm this issue is resolved for you now?

**Comment by DeckardEdward** [comment]
The issue's resolved for me. I can now cycle the screenshot off from within the library.
