### ISSUE TITLE
GUI  shutdown options

### ISSUE THREAD

**Issue by cmcginty** [libretro/RetroArch#4875]
It would be nice if there were more options in the menu to halt and suspend in addition to the quit 
command. Something like Kodi comes to mind, where "power" brings up a dialog of multiple options.

For now is there any way to add a custom command to the menu, or modify "quit" to shutdown?

I'm running version c045732 stable from the APT repo btw.

**Comment by RobLoach** [comment]
Lakka has split this into multiple options right on the menu.... Restart, Quit RetroArch, etc.

**Comment by kascesar** [comment]
can you already execute scripts from the retroarch interface or not?
i need this functionality for execute external games, like SF IV or KOF XIV.
Thanks you  alot for your good work!

**Comment by RobLoach** [comment]
rszasz forked the Lutris Lutro Launcher over to be just for files.... https://github.com/rszasz/lutro-launcher

Use Lutro to launch it.
