### ISSUE TITLE
Alpha/Transparency in Thumbails

### ISSUE THREAD

**Issue by idemiq** [libretro/RetroArch#4878]
## Description

_When using any image filetype (eg PNG) as a Thumbnail, alpha channels aren't rendered as such in the User Interface and so Transparency is rendered a solid color (or pattern if the alpha is dirty)._

### Expected behavior

_Thumbnail image file alphas to be rendered transparent._

### Actual behavior

_With PNG-8 (indexed) transparent areas are white, in non-indexed PNG-8 (rgb) they're black and so on. This is specifically on Android (ShieldTV). and RetroArch 1.5.0, and with or without Menu Shader Pipelines and Shadows on._

### Steps to reproduce the bug

_1. Load up RetroArch 1.5.0 on Android (ShieldTV).
2. Use a PNG with Alphas as a Playlist item Thumbnail._

### Bisect Results

_Unsure._

### Version/Commit

_137f8df_

### Environment information

_OS: Android 7.0
Compiler: Clang/LLVM (3.8.256229) 32-bit_

**Comment by RobLoach** [comment]
This is fixed. The alpha-channel is considered.
