### ISSUE TITLE
Scanning individual game doesn't add it to playlist, but instead begins playing the game

### ISSUE THREAD

**Issue by FalloutFan** [libretro/RetroArch#4882]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Under "Import Content", pressing "Scan File" that has the description of "scans a compatible file and adds it to the collection" 

### Expected behavior

For it to scan a game into the collection

### Actual behavior

Instead the game is initialized and not added to the collection

### Steps to reproduce the bug

1. Go to Import Content
2. Press "Scan File"
3. Find individual game

### Bisect Results

Found on clean install

### Version/Commit
You can find this information under Information/System Information

- RetroArch: latest version

### Environment information

- OS: Windows 10
- Compiler: [In case you are running local builds]

**Comment by Elmazz37** [comment]
Bump? Can i do such things here? I dont want to create an another post and this seems like to have slipped through.

**Comment by bparker06** [comment]
Have you tested the latest nightly? If that still doesn't work, can you bisect it to find the offending commit that broke it?

**Comment by Elmazz37** [comment]
Ok, ill try.

**Comment by Elmazz37** [comment]
Cough

**Comment by Elmazz37** [comment]
I dunno, I switched to Launchbox for the front-end.

**Comment by RobLoach** [comment]
Feel free to post an issue over at [libretro-database](https://github.com/libretro/libretro-database) if it persists. It will only add scanned files to a playlist if the file matches the CRC in the database. There's also been some discussion about having an [Alternative Scanning Method](https://github.com/libretro/RetroArch/issues/2033), and the Qt interface also allows creating a playlist manually.
