### ISSUE TITLE
Still audio mixer issues

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#4891]
@leiradel - It still doesn't work, and it still crashes.

See the latest diff file now - 

https://github.com/libretro/RetroArch/blob/master/audiomixer-test.diff

And a coredump -

https://gist.github.com/twinaphex/249b4e5c673827ab7526820aa7ef898d

I think it might be best that since you now are starting to learn how the task system works, that you add a task so that we can add audio files to the mixer on demand. That way, you would also be able to test for all these random segfaults that seem to be occurring.

**Comment by leiradel** [comment]
Sorry, my bad. Add this line in the appropriate place to initialize the mixer:

```
audio_mixer_init(48000);
```

I've used 48000 because I don't know how to get the actual sample rate.

> I think it might be best that since you now are starting to learn how the task system works, that you add a task so that we can add audio files to the mixer on demand.

I'll change the mixer to accept data in memory, so it'll be just a matter of using a task to load the file contents and calling the appropriate mixer function to load the data. Both WAV and OGG loading are fast.

**Comment by twinaphex** [comment]
OK, I will add that line then.

**Comment by twinaphex** [comment]
It still doesn't work?

https://github.com/libretro/RetroArch/blob/master/audiomixer-test.diff

Can you test this yourself? Test it with this audio file and just change the hardcoded path -

http://docpiper.com/tests/audio/music/SumertimeBlues.ogg

**Comment by twinaphex** [comment]
Hmm, actually, it doesn't make sense how I should use audio_mixer_load_ogg at this point. It returns an audio_mixer_sound_t - so I guess I need to bookkeep this somewhere? 

This entire thing seems to be ill-designed at this point. We have s_voices inside the audio mixer file, but then we should also bookkeep external state outside of the file. Which is it?

**Comment by twinaphex** [comment]
EDIT: Looks like I need to run audio_mixer_play after audio_mixer_load_ function and use the pointer that I received from the 'load' function. However, I can't free the object after calling audio_mixer_play. So when should I free the pointer that gets returned to me after a successful call of audio_mixer_load_* ?

**Comment by leiradel** [comment]
1. Initialize the mixer with `audio_mixer_init`
1. Load audio resources with `audio_mixer_load` and keep the returned `audio_mixer_sound_t*` around
1. Play audio resources when needed with `audio_mixer_play`, you don't need to save the returned `audio_mixer_voice_t*` unless you need to call `audio_mixer_stop` to stop the sound before it's finished playing
1. When quitting, call `audio_mixer_done` so you can safely free all your `audio_mixer_sound_t*` with calls to `audio_mixer_destroy`

> I guess I need to bookkeep this somewhere if I want to play it again?

Yes, you don't want to keep loading the same resource over and over, load it once, use it many times, destroy it when not needed anymore.

> Where is audio_mixer_play even called?

It's up to you when you want to play a sound, i.e. when a button is pressed.

> So when should I free the pointer that gets returned to me after a successful call of audio_mixer_load_* ?

It's also up to you, free it when you don't intend to use it any further.

**Comment by twinaphex** [comment]
OK. Try to look at my TODO/FIXME notes to see if we can use the audio conversion functions that are already in libretro-common.
