### ISSUE TITLE
Problems with compiling the code for windows pcs using visual studio for Xbox one UWP

### ISSUE THREAD

**Issue by MysteriousHercules** [libretro/RetroArch#4893]
# First and foremost consider this:
- I am not able to compile the code using visual studio

## Description

I need help with how to open retroarch with visual studio. My intent is helping convert retroarch into UWP. So that it will be very easy to port it to xbox one (all you need is 20 dollars dev mode account and that is it). And considering that Xbox one is the only console that allows homebrew without having to hack your system. I feel this is a very good opportunity. I decided to make this my first challenge as a developer who is researching UWP apps. If I am doing this incorrectly, I apologize in advance. I have never worked with retroarch before

### Expected behavior

I expect some sort of solution or some sort of explanation of how to compile retroarch using visual studio

### Actual behavior

I couldn't find anything like that, I looked up google and youtube with no results.

### Steps to reproduce the bug

1. Download the master code from Github
2.  Search for instructions for how compile code with visual studio

### Environment information

- OS: Windows 10 with anniversary update
- Compiler: Visual Studio 2017

**Comment by bparker06** [comment]
We have a VS2015 solution here: https://github.com/libretro/RetroArch/blob/master/pkg/msvc/RetroArch-msvc2015.sln

Should be able to convert it to 2017 automatically and get it running.

**Comment by orbea** [comment]
I guess this is fixed, see PR https://github.com/libretro/RetroArch/pull/7834.
