### ISSUE TITLE
snes9x_next won't load Kirby's Dreamland 3

### ISSUE THREAD

**Issue by webodan** [libretro/RetroArch#4894]
Whenever I run the ROM i get a message saying: 

> Please Note: If you are using a mouse, superscope, or multiplayer adapter, then switch to controller. Thanks!.

 I searched through the input options to make sure whether there was any of those controllers set instead of SNES Joypad but I didn't see any mentions of them in any of the settings. 

The game does run in other cores but the transparency for the trees in certain stages is not well implemented and I can't see what i'm doing, so I wanted to try this one core since it's the most accurate, but I can't because of this screen I can't get out of. I'm sorry if this doesn't belong but I just don't know where to report this. 

I hope someone can help me.

**Comment by sergiobenrocha2** [comment]
This is the right place to post the issue: https://github.com/libretro/snes9x2010/issues

**Comment by webodan** [comment]
thank you i will post there, sorry for bothering

**Comment by meepingsnesroms** [comment]
The author has already moved this to the right place.
