### ISSUE TITLE
Mega Man X SNES retro achievements 

### ISSUE THREAD

**Issue by LumbyMcGumby** [libretro/RetroArch#4895]
RetroArch 1.5.0 on Raspberry Pi 3 RetroPie

I was playing Mega Man X for snes and the USA Rom worked on "Last played 2017-04-23 05:22:38."  But now every version and rom I try to use on snes9x2010 doesn't load the retro achievements for Mega Man X (USA) or Mega Man X (U) (V1.1)

**Comment by retro-wertz** [comment]
use the template to submit retroarch issues...

**Comment by meepingsnesroms** [comment]
This should be reported here [https://github.com/libretro/snes9x2010/issues](url)
