### ISSUE TITLE
[Vulkan] RetroArch does not use the right GPU and does not launch

### ISSUE THREAD

**Issue by DrCat7** [libretro/RetroArch#4900]
## Description

When Vulkan is chosen as the video driver, RetroArch attempts to use the integrated GPU instead of the dedicated one and gets stuck.
When manually disabling the iGPU, RA works as intended.
I have also attempted to use a fresh install of RetroArch 1.5.0 but this did not solve the issue.

This makes the problem twofold:
-RA should be using the dGPU by default
-Assuming I was purposedly trying to use the iGPU, RA should not get stuck.

### Log when trying to launch RetroArch
C:\Emulateurs\RetroArch 1.5.0>RetroArch [INFO] :: This is RetroArch version 1.5.0 (Git 51581e1)
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Mar  9 2017
RetroArch [INFO] :: Version: 1.5.0
RetroArch [INFO] :: Git: 51581e1
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "C:\Emulateurs\RetroArch 1.5.0\saves\.srm".
RetroArch [INFO] :: Redirecting savestate to "C:\Emulateurs\RetroArch 1.5.0\states\.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29981.41 Hz.
RetroArch [INFO] :: Video @ 1280x960
RetroArch [INFO] :: Vulkan dynamic library loaded.
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [Vulkan]: Using GPU: Intel(R) HD Graphics 530
RetroArch [INFO] :: [Vulkan]: Queue family 0 supports 1 sub-queues.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 0.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 2.
RetroArch [INFO] :: [Vulkan]: Creating swapchain with present mode: 2
RetroArch [INFO] :: [Vulkan]: Using swapchain size 1280 x 960.
RetroArch [INFO] :: [Vulkan]: Got 0 swapchain images.

### Log when launching RetroArch with the integrated GPU disabled (works as intended)
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "C:\Emulateurs\RetroArch 1.5.0\saves\.srm".
RetroArch [INFO] :: Redirecting savestate to "C:\Emulateurs\RetroArch 1.5.0\states\.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29981.41 Hz.
RetroArch [INFO] :: Video @ 1280x960
RetroArch [INFO] :: Vulkan dynamic library loaded.
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [Vulkan]: Using GPU: AMD Radeon (TM) R9 390 Series
RetroArch [INFO] :: [Vulkan]: Queue family 0 supports 1 sub-queues.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 0.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 2.
RetroArch [INFO] :: [Vulkan]: Creating swapchain with present mode: 2
RetroArch [INFO] :: [Vulkan]: Using swapchain size 1280 x 960.
RetroArch [INFO] :: [Vulkan]: Got 2 swapchain images.
RetroArch [INFO] :: Vulkan: Using resolution 1280x960
RetroArch [INFO] :: [Vulkan]: Using RGB565 format.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: Loading stock shader.
RetroArch [INFO] :: [slang]: Building pass #0 (N/A)
RetroArch [INFO] :: [slang]: Reflection
RetroArch [INFO] :: [slang]:   Textures:
RetroArch [INFO] :: [slang]:      Source (#0)
RetroArch [INFO] :: [slang]:
RetroArch [INFO] :: [slang]:   Uniforms (Vertex: yes, Fragment: no):
RetroArch [INFO] :: [slang]:   Push Constants (Vertex: no, Fragment: no):
RetroArch [INFO] :: [slang]:      MVP (Offset: 0)
RetroArch [INFO] :: [slang]:
RetroArch [INFO] :: [slang]:   Parameters:
RetroArch [INFO] :: [Vulkan filter chain]: Not using frame history.
RetroArch [INFO] :: [Vulkan filter chain]: Not using framebuffer feedback.
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {02FF} VID:{045E}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: RetroArch [INFO] :: Found joypad driver: "xinput".
Autodetect: 40 profiles found.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: XAudio2: Requesting 64 ms latency, using 64 ms latency.
RetroArch [INFO] :: Found menu display driver: "menu_display_vulkan".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [WARN] :: Input device ID 513 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
RetroArch [INFO] :: Disconnecting device from port 2.
RetroArch [INFO] :: Disconnecting device from port 3.
RetroArch [INFO] :: Disconnecting device from port 4.
RetroArch [INFO] :: Disconnecting device from port 5.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_music_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_video_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_image_history.lpl].
RetroArch [INFO] :: [Vulkan]: VSync => on
RetroArch [INFO] :: [Vulkan]: VSync => on
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 0.
RetroArch [INFO] :: [Vulkan]: Swapchain supports present mode: 2.
RetroArch [INFO] :: [Vulkan]: Creating swapchain with present mode: 2
RetroArch [INFO] :: [Vulkan]: Using swapchain size 1280 x 960.
RetroArch [INFO] :: [Vulkan]: Recycled old swapchain.
RetroArch [INFO] :: [Vulkan]: Got 2 swapchain images.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [Vulkan]: GPU supports linear images as textures, but not DEVICE_LOCAL. Falling back to copy path.
RetroArch [INFO] :: [slang]: Building pass #0 (N/A)
RetroArch [INFO] :: [slang]: Reflection
RetroArch [INFO] :: [slang]:   Textures:
RetroArch [INFO] :: [slang]:      Source (#0)
RetroArch [INFO] :: [slang]:
RetroArch [INFO] :: [slang]:   Uniforms (Vertex: yes, Fragment: no):
RetroArch [INFO] :: [slang]:   Push Constants (Vertex: no, Fragment: no):
RetroArch [INFO] :: [slang]:      MVP (Offset: 0)
RetroArch [INFO] :: [slang]:
RetroArch [INFO] :: [slang]:   Parameters:
RetroArch [INFO] :: [Vulkan filter chain]: Not using frame history.
RetroArch [INFO] :: [Vulkan filter chain]: Not using framebuffer feedback.

### Log when launching RetroArch with the integrated GPU enabled and "gl" as the video driver (works as intended)
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "C:\Emulateurs\RetroArch 1.5.0\saves\.srm".
RetroArch [INFO] :: Redirecting savestate to "C:\Emulateurs\RetroArch 1.5.0\states\.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29981.41 Hz.
RetroArch [INFO] :: Video @ 1280x960
RetroArch [INFO] :: Found GL context: wgl
RetroArch [INFO] :: Detecting screen resolution 1920x1080.
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [INFO] :: [GL]: Vendor: ATI Technologies Inc., Renderer: AMD Radeon (TM) R9 390 Series.
RetroArch [INFO] :: [GL]: Version: 4.5.13474 Compatibility Profile Context 22.19.157.3.
RetroArch [INFO] :: GL: Using resolution 1280x960
RetroArch [INFO] :: [GL]: Default shader backend found: glsl.
RetroArch [INFO] :: [Shader driver]: Using GLSL shader backend.
RetroArch [INFO] :: Checking GLSL shader support ...
RetroArch [WARN] :: [GL]: Stock GLSL shaders will be used.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: Found GLSL vertex shader.
RetroArch [INFO] :: Found GLSL fragment shader.
RetroArch [INFO] :: Linking GLSL program.
RetroArch [INFO] :: [GL]: Using 4 textures.
RetroArch [INFO] :: [GL]: Loaded 1 program(s).
RetroArch [INFO] :: Found XInput v1.4.
RetroArch [INFO] :: Found XInput controller, user #0
RetroArch [INFO] :: Enumerating DInput joypads ...
RetroArch [INFO] :: Device #0 PID: {02FF} VID:{045E}
RetroArch [INFO] :: Done enumerating DInput joypads ...
RetroArch [INFO] :: Found joypad driver: "xinput".
RetroArch [INFO] :: Autodetect: 40 profiles found.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: XAudio2: Requesting 64 ms latency, using 64 ms latency.
RetroArch [INFO] :: Found menu display driver: "menu_display_gl".
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [INFO] :: Using font rendering backend: freetype.
RetroArch [WARN] :: Input device ID 513 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
RetroArch [INFO] :: Disconnecting device from port 2.
RetroArch [INFO] :: Disconnecting device from port 3.
RetroArch [INFO] :: Disconnecting device from port 4.
RetroArch [INFO] :: Disconnecting device from port 5.
RetroArch [INFO] :: SRAM will not be saved.
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_music_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_video_history.lpl].
RetroArch [INFO] :: Loading history file: [C:\Emulateurs\RetroArch 1.5.0\content_image_history.lpl].
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)
RetroArch [INFO] :: [GL]: VSync => on
RetroArch [INFO] :: [WGL]: wglSwapInterval(1)

### Environment information

- OS: Windows 10 64bit

**Comment by jvook** [comment]
I don't know if anything changed but I had issues with Vulkan several weeks ago that seem to be fixed now.  Maybe see if the nightly has improved the error?

**Comment by DrCat7** [comment]
Just tried again with the nightly dated May 26 (aka today) and the log shows the exact same messages.

**Comment by DrCat7** [comment]
The issue seems to have been fixed thanks to AMD's latest driver (17.7.2).
