### ISSUE TITLE
[Vulkan] Bad caracter encoding in Vulkan for french caracters

### ISSUE THREAD

**Issue by Tromzy** [libretro/RetroArch#4912]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
I use Retroarch in french, so it displays french special caracters like "é", "à", "ô", "ï", etc. The special caracters are correctly displayed when the renderer is set to OpenGL, but on Vulkan, they are not. I made a screenshot of the problem.

### Expected behavior
Caracters with accents should be displayed correctly.

### Actual behavior

See screenshot : [http://reho.st/view/self/909e5ffce807d1e5b96447579f985f7357ca310d.png](http://reho.st/view/self/909e5ffce807d1e5b96447579f985f7357ca310d.png)

### Steps to reproduce the bug

1. Set Retroarch to french
2. Set the renderer to Vulkan
3. Restart Retroarch

### Bisect Results

I think it has always been since Vulkan can be chosen as renderer.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: nightlies
### Environment information

- OS: Windows 10 (but happens on Linux too)
- Compiler: [In case you are running local builds]

**Comment by rootfather** [comment]
This also happens when you select German as GUI language.

**Comment by bparker06** [comment]
The vulkan font renderer does not currently have unicode support, so any language besides English will have display issues.
