### ISSUE TITLE
Retroarch latest nightly Windows x64 stops responding immediately

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#4918]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch 2017-05-15 (Windows x64) just stops responding immediately after launch.

GDB log:
[retroarch-15.05.2017.txt](https://github.com/libretro/RetroArch/files/1001546/retroarch-15.05.2017.txt)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Windows 8.1 x64
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
Can you try setting video_shader_enable to "false" in your retroarch.cfg?

**Comment by ofry** [comment]
Set it to "false"

Same behavior.

**Comment by ofry** [comment]
On 

`video_driver = "d3d"`

Segfault.

[retroarch-15.05.2017-d3d.txt](https://github.com/libretro/RetroArch/files/1001782/retroarch-15.05.2017-d3d.txt)

**Comment by ofry** [comment]
Now (2017-05-17 nightly build) it starts, but stops responding after 254 frames.

**Comment by hizzlekizzle** [comment]
So, if you revert back a couple of days, everything works fine? What if you move you retroarch.cfg somewhere else and let it generate a new one?

**Comment by ofry** [comment]
Yes. If I "revert back" executable files retroarch.exe and retroarch_debug.exe to nightly version of May, 12th; all work fine.

**Comment by ofry** [comment]
If I just delete retroarch.cfg,

then it launches, but after 3-10 seconds window of Retroarch turns totally black.

**Comment by hizzlekizzle** [comment]
Okay, so 5/12 works, 5/13 doesn't? I'm just trying to pin down the exact day that it started misbehaving for you.

I'm not able to reproduce this, btw. What kind of GPU do you have?

**Comment by bparker06** [comment]
His gdb log says R7 360

**Comment by ofry** [comment]
> Okay, so 5/12 works, 5/13 doesn't?

Yes. I have GPU AMD Radeon R7 360

**Comment by ofry** [comment]
I will try to bisect it, I have toolchain for compile RA.

**Comment by ofry** [comment]
I will try to bisect it, I have toolchain for compile RA.

**Comment by ofry** [comment]
Last good commit:

45a648b042f5605b8c9dad51739acdfa2721d070

First bad commit:

f6c8aba119d4addc0894e67b2ce3e84a0cac52eb

**Comment by ofry** [comment]
It's for
`video_driver = "gl"`

**Comment by twinaphex** [comment]
See if this solves the issue -

https://github.com/libretro/RetroArch/commit/86ee08b7a708284777d49fe6867fd4da6b8b4010

**Comment by ofry** [comment]
Yes, this issue has FIXED! Big thank you!
