### ISSUE TITLE
RetroArch crashing on any menu movement on htc incredible

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#4922]
This is using glui but since it is default and you cant pick rgui or xmb without it you are stuck with a crash on touching the screen after every launch.(I dont know if rgui or xmb are any better)

If this is an open gl issue(which it most likely is) using rgui as default on anything less than android 4 should fix it.

Android Version: 2.3.7(cm7)(android 2.3 and up is supported)
RetroArch Version:1.5.0 nightly (May 15 2017)
Device: htc droid incredible
Crash log:[droidinc.txt](https://github.com/libretro/RetroArch/files/1002853/droidinc.txt)

**Comment by fr500** [comment]
does it "look" correct?
if that's the case then maybe it's a touch issue instead

**Comment by meepingsnesroms** [comment]
Yes it renders fine, and I just tested with rgui and overlay using a text editor and it still crashes.

**Comment by meepingsnesroms** [comment]
It seems to be touch based, the screen will redraw fine when rotated.

**Comment by twinaphex** [comment]
I have only tested a version as old as Android 2.3 on an Xperia Play device, and I did not get crashes there. So you are kinda in uncharted territory here. I think you will be the only one to fix it given your outdated hardware and OS combination.

**Comment by Josephvb10** [comment]
Yeah, you should update your OS / just buy a better phone. Devs just won't make an effort to support a 7 year old phone.

**Comment by twinaphex** [comment]
I am fine with merging any PR you submit though that could improve things.  But it will just be a basic fact of life that we don't own your phone, so you will be the only one able to debug this and send the necessary PR.

**Comment by meepingsnesroms** [comment]
I updated it to an experimental 4.2.2 build and it works without this issue.
So I will not be able to fix this since I no longer have the OS to test it.
Just gonna close it, sorry for the wasted time.
