### ISSUE TITLE
We need a "lite" version, a normal install takes > 150mb

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#4924]
On android a fresh RetroArch install takes 229mb, some old phones only have 512mb for apps and a separate sd card partition.

This was the only app I installed on my htc droid incredible and I got the low memory warning.

On a phone this old I would use "rgui" so all the "glui" and "xmb" assets.

Since these are included in the apk and are duplicated on first launch, there is no way to reduce the size.

I am suggesting a "lite" version for android with "rgui" as the default menu and no assets installed other than overlays and core info files.

**Comment by twinaphex** [comment]
A light version is fine but RGUI is useless on mobile, so it would need to have MaterialUI just like the default version.

**Comment by meepingsnesroms** [comment]
rgui works with overlays enabled.(On all my modern handheld devices I use xmb with onscreen overlays and sometimes a bluetooth controller)

So could we just have overlays in menu start as on?

**Comment by aliaspider** [comment]
MaterialUI assets are 200kb at most.

**Comment by meepingsnesroms** [comment]
MaterialUI is fine, I haven't checked the size of every element in the assets folder so I did not know that MaterialUI was so small.

I will look now to see what could be removed and what has to stay.

**Comment by meepingsnesroms** [comment]
We could remove:
*/assets/database - it can be downloaded after installation
*/assets/shaders   - devices that need a "lite" version cant use shaders at full speed(or at all)
*/assets/xmb         - 30mb, xmb is also too gpu heavy for these devices

**Comment by sergiobenrocha2** [comment]
/assets/xmb/monochrome is only 1 MB

> xmb is also too gpu heavy for these devices

Are you assuming that everyone are using glui in the phones?

**Comment by meepingsnesroms** [comment]
For 1ghz 512mb ram, xmb seems too heavy.(still armv7 though)
Anyway if you want xmb it will still be there, you just have to install its icon pack first if you dont want black squares.
