### ISSUE TITLE
Error compiling with Clang

### ISSUE THREAD

**Issue by enderleseb** [libretro/RetroArch#4925]
Actually when I try to compile RetroArch with Clang I get this error:

`configuration.c:1336:98: error: use of undeclared identifier 'menu_shader_pipeline'
   SETTING_UINT("menu_shader_pipeline",         &settings->uints.menu_xmb_shader_pipeline, true, menu_shader_pipeline, false);`

I am using openSUSE Leap 42.2 with (as mentioned above) Clang(++)

**Comment by twinaphex** [comment]
This should hopefully no longer make this an issue -

https://github.com/libretro/RetroArch/commit/dd9034248bece6a6e342e224b0018c1fa908a5cc

**Comment by enderleseb** [comment]
Compiling works now without problems and the program itself works, too. Thanks!
