### ISSUE TITLE
[Android] Back button to go from playing to Retroarch menu

### ISSUE THREAD

**Issue by molul** [libretro/RetroArch#4933]
## Description

I play Retroarch with an 8bitdo controller, so I hide the touch overlay. But if I do it, there's no way to bring menus up unless I switch to another app and then switch back to Retroarch.

### Expected behavior

While playing, I'd expect the Back button to bring Retroarch menu up, so I can save state, change a shader, change the game...

### Actual behavior

When I press Back while playing, nothing happens. 

### Steps to reproduce the bug

1. Play a game
2. Press Back
3. Nothing happens

### Version/Commit
Retroarch 1.5.0 (latest Android version)

### Environment information

- OS: Android Nougat

**Comment by molul** [comment]
I just discovered the "go to menu" shortcut. I'm using Select+Start. Closing the issue.

**Comment by cawoodm** [comment]
It's not quite the same though is it? Most people want to exit a game and go back to retroarch. However retroarch offers only 2 different things:
1) Esc will completely close the game and retroarch (crazy IMO)
2) The "Toggle Quick Menu" which pops up a menu allowing you to choose "Close Content" and return to retroarch.

So I think there is definitely a need for a "Close Game" function.
