### ISSUE TITLE
[Android] Resuming game results in accidentally pressing a button in the game

### ISSUE THREAD

**Issue by molul** [libretro/RetroArch#4939]
## Description

While playing, if I go to Retroarch menu to save game and then resume game, that button is pressed in the game. I mean,  imagine I'm playing Sonic the hedgehog for Genesis. I go to the menu, save state, press "resume" and the moment the game is resumed, Sonic jumps. 

### Expected behavior

I'd rather all pressed keys were not taken into account when resuming. The emulator should wait for any pressed button to be released before it can be detected for the game. 

### Actual behavior

Explained above. 

### Steps to reproduce the bug

1. Play a game. 
2. Go to retroarch menu and save state.
3. Resume game. The button used for resuming is pressed in the game. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: latest android version (1.5.0)

### Environment information

- OS: Android

**Comment by jvook** [comment]
Might be better implemented as auto-rewind 1 second after entering RA menu.
