### ISSUE TITLE
[Feature request] [Android] A touch button to show/hide the virtual gamepad on xmb Menu Driver

### ISSUE THREAD

**Issue by molul** [libretro/RetroArch#4941]
Yesterday I started using the xmb Menu Driver. Much cooler, but unusable unless you have virtual gamepad enabled or a physical gamepad connected.

I disabled the virtual gamepad and I'm fine with using a physical controller when I launch Retroarch.

However, currently I can only use Retroarch if I have a controller. That is, I can't test a feature in the street and stuff. As I cannot navigate the menu without my physical controller, I can't enable the virtual gamepad.

It would be great having a button at the top of the xmb Menu that enables/disables the virtual gamepad.

**Comment by hizzlekizzle** [comment]
Most of the gamepad overlays should have a button that cycles through some menus and/or hides the buttons.

If you regularly use a physical gamepad, you might also be interested in the 'immerse' overlay, which is invisible until you touch the screen, at which point it pops up some common in-game options, like savestate, fast-forward, rewind, etc.

**Comment by molul** [comment]
Interesting. However, that wouldn't address the exposed problem, would it?

**Comment by hizzlekizzle** [comment]
Which exposed problem? If I were you, I would keep the gamepad overlay enabled at all times and if I connect a physical pad, just tap the gear icon a few times until it hides itself.

**Comment by molul** [comment]
Oh, I didn't know the gear icon could be tapped several times to hide the whole virtual gamepad. I'll try that. Thanks!
