### ISSUE TITLE
A lot of cores are not detected.

### ISSUE THREAD

**Issue by MysteriousHercules** [libretro/RetroArch#4949]
## Description

I am able to download a lot of cores and extract them correctly, but when I try to load them, they are not detected. It still says "no cores" on the bottom left. All of the ps1 emulator cores (with the exception of pcsx-r) are not being loaded. All the n64 emulator cores are not loading, Dosbox core is not loading, and Mame and Mess are not being loaded either.

### Expected behavior

After a core is downloaded, once loaded it should say at the bottom left the name of the core, and it should be able to run the formats related to each emulator file type

### Actual behavior

It just says "no core" for most cores, and when I try to load a file related to the emulator, he just says "the folder is empty"

### Steps to reproduce the bug

1. Download any of the cores mentioned above.
2. After extracting them, try to load them using "load core"

### Bisect Results

I have only been into retroarch source code scene recently, but This problem happens 100 percent of the time I have been testing retroarch.

### Version/Commit
Latest version as of today. I just tested it again today before raising the issue

### Environment information

- OS: Windows 10 Nvidia GeForce 940M
- Compiler: Visual studio 2017, and Visual Studio 2015 (I tried both).

**Comment by retro-wertz** [comment]
missing core info files.

**Comment by bparker06** [comment]
@retro-wertz Core info files are not required to load cores.

@MysteriousHercules It looks like you're using Visual Studio 2015/2017, and to my knowledge these solutions are largely untested. We normally use the msys2/mingw environment for Windows builds, and this is what the cores are compiled with on the buildbot.

It's possible the cores you are downloading are simply not compatible with RetroArch when built with a newer VC runtime, as suggested by answers like [this](http://stackoverflow.com/questions/1600399/are-c-libs-created-with-different-versions-of-visual-studio-compatible-with-ea). I would suggest trying the [mingw](http://bot.libretro.com/nightly/windows/x86_64/RetroArch.7z) build first, and if that works, then your newer compiler is likely the issue, you could also check the verbose output log from RetroArch for hints on exactly why it is failing, but my guess is this may be an unavoidable issue.

If you are dead set on using a newer compiler, then you will likely have to figure out how to get your desired core(s) to compile yourself within that same environment.

**Comment by RobLoach** [comment]
This still an issue?

**Comment by orbea** [comment]
> Core info files are not required to load cores.

Yes they are unless you use the commandline, see issue https://github.com/libretro/RetroArch/issues/6256.

Given the lack of responses indicating if the info files are even present and the existing issue for this problem I am going to close this, please let us know if you have the info files and this is still a problem!
