### ISSUE TITLE
Linux build failure in file_stream.c

### ISSUE THREAD

**Issue by BPaden** [libretro/RetroArch#4961]
This is on gcc 7.1.1 and glibc 2.25. I'm using the aur pkgbuild, the package is built like this:

```
./configure \
  --prefix='/usr' \
  --disable-jack \
  --disable-oss
make clean
make
make -C gfx/video_filters
```

This is the error.

```
In file included from /usr/include/fcntl.h:313:0,
                 from libretro-common/streams/file_stream.c:61:
In function ‘open’,
    inlined from ‘filestream_open’ at libretro-common/streams/file_stream.c:238:20:
/usr/include/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
    __open_missing_mode ();
    ^~~~~~~~~~~~~~~~~~~~~~
```

I looked at the code myself but there's a lot of ifdefs. I don't want to touch it. But from the open manual, you need an additional mode_t argument in open when creating files. The sys_stat.h manual has a table with possible mode_t values.

**Comment by twinaphex** [comment]
Does this fix it ?

https://github.com/libretro/RetroArch/pull/4972

**Comment by BPaden** [comment]
Yup I was able to build as normal! 👍
