### ISSUE TITLE
Bounty to Add Missing Cores For WiiU.

### ISSUE THREAD

**Issue by Ploggy** [libretro/RetroArch#4970]
So. I want to create a Bounty for someone to compile the missing Cores for the WiiU (obviously not the Core's that would require a Dynarec or would need ALOT of work) ;P

These are the Prioritised Core list:
1.Dosbox
2.Commodore 64
3.Amiga
4.Amstrad
5.Hatari
6.MSX/fMSX
7.Stella
8.Game and Watch

But if your feeling kind :)  
Commodore 16 
Vectrex)
Atari 7800 (Prosystem)
Odyssey
(or any other that I may missed) ;)

Consider the Bounty filled when the prioritised Cores are Compiled, tested and working and added to the WiiU Buildbot. :)

Thank You :)

**Comment by carnage702** [comment]
its already worth 30$

**Comment by Ploggy** [comment]
It just shows there is interest in the other cores :)

**Comment by carnage702** [comment]
35 now xD

**Comment by twinaphex** [comment]
All of those cores at once might be a bit too much. Can we reduce this to a somewhat more manageable size maybe so that there would be more takers?

**Comment by Ploggy** [comment]
Well, I'm hoping they will all make their way over to the WiiU eventually.. But I guess the list is abit bloated. ;)
I'll ask on the thread and see if I can narrow it down some. :)

**Comment by ShadowOne333** [comment]
Usually the most requested ones are DosBox, Atari (2600/5200/7800), MSX and Commodore 64.
But I would dare to say that indeed DosBox is the top 1 for sure.

**Comment by Ploggy** [comment]
I think it's ready... That's the final revision :)

**Comment by carnage702** [comment]
is there even a retroarch core that plays 5200? i dont think so tbh, i heard pleople saying you have to use a moded MESS core to play 5200.

**Comment by QuarkTheAwesome** [comment]
I think this is complete at this point? Marked myself as "stopped" since lots of work was done by @r-type and I haven't touched it for a while.

**Comment by twinaphex** [comment]
Can somebody link me to the associated bountysource link, or was one never created?

**Comment by Ploggy** [comment]
https://www.bountysource.com/issues/45538888-bounty-to-add-missing-cores-for-wiiu
I agree 100% with quark. Granted he did some work in getting mew cores added to the buildbot (thanks for that btw) but R-type has really put the work in and added many new cores. So Im more than happy for @r-type  to claim the bounty.

**Comment by r-type** [comment]
hi @Ploggy ,
Thank you but I'm not interested in the reward,
You can give it to @QuarkTheAwesome  or maybe if it's possible add the reward to another wii U bounty .

**Comment by Ploggy** [comment]
Well i guess the balls in @Quarktheawesome court :) Do you want it or shall I pass it to another WiiU Bounty?

**Comment by QuarkTheAwesome** [comment]
I'll take it or leave it; I think I largely depends on whether you actually can transfer money about (I know you can't revoke it, at least)

**Comment by Ploggy** [comment]
Its yours if you want it. I'm not sure who this works tbh but I think you have to click "cash out" in your profile? and go from there?

**Comment by ShadowOne333** [comment]
Well what you can do if you want to transfer it, is perhaps claim it and then put it into another as soon as you get it?
I'm not sure if the money is put directly into your bank account or if it goes to PayPal or something similar, if it's the latter then you could indeed claim it and put it back into another.
The Phantom Transfer.

**Comment by QuarkTheAwesome** [comment]
![bounty] (https://i.imgur.com/N7RS6cs_d.jpg)

If we're putting this back into the Wii U, I think one of the PSX dynarec bounites may be a good idea?

**Comment by twinaphex** [comment]
OK, you want me to close this issue now so that you can claim the bounty?

**Comment by QuarkTheAwesome** [comment]
Sure.
