### ISSUE TITLE
3840x240 hdmi timings on RPi cause segmentation fault

### ISSUE THREAD

**Issue by kevinfishburne** [libretro/RetroArch#4978]
Lakka 2.0, RPi 3 Model B, RetroTINK hat
hdmi_timings=3840 1 109 343 343 240 1 5 3 14 0 0 0 60 0 72925291 1

Using these timings Retroarch segfaults, showing only the Lakka logo. I can still ssh in to it to see what's happening, so it seems like LibreELEC is still working fine. I've also filed a bug report with Lakka: https://github.com/libretro/Lakka-LibreELEC/issues/135

```
kevinfishburne@codex ~ $ ssh root@192.168.0.56
root@192.168.0.56's password: 
###########################################
# Lakka - The DIY retro emulation console #
# ...... visit http://www.lakka.tv/ ...... #
###########################################

Lakka (community) Version: 2.0
Lakka:~ # systemctl stop retroarch.service ; retroarch -v
RetroArch [INFO] :: This is RetroArch version 1.5.0 (Git 2a13af5)
RetroArch [INFO] :: === Build =======================================
Capabilities: NEON VFPv3 VFPv4 
Built: Apr 24 2017
RetroArch [INFO] :: Version: 1.5.0
RetroArch [INFO] :: Git: 2a13af5
RetroArch [INFO] :: =================================================
RetroArch [INFO] :: Loading default config.
RetroArch [INFO] :: Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [INFO] :: Redirecting save file to "/storage/savefiles/.srm".
RetroArch [INFO] :: Redirecting savestate to "/storage/savestates/.state".
RetroArch [INFO] :: Version of libretro API: 1
RetroArch [INFO] :: Compiled against API: 1
RetroArch [INFO] :: Set audio input rate to: 29970.03 Hz.
RetroArch [INFO] :: Found shader "/tmp/shaders/bilinear.glslp"
RetroArch [INFO] :: Found shader "/tmp/shaders/nearest.glslp"
RetroArch [INFO] :: Found shader "/tmp/shaders/stock.glsl"
RetroArch [INFO] :: Video @ fullscreen
RetroArch [INFO] :: [EGL]: EGL version: 1.4
RetroArch [INFO] :: Found GL context: null
RetroArch [INFO] :: Detecting screen resolution 320x240.
RetroArch [INFO] :: [GL]: Vendor: (null), Renderer: (null).
RetroArch [INFO] :: [GL]: Version: (null).
Segmentation fault
Lakka:~ #
```
A 3840x240 mode is the holy grail of integer-scaled retro emulation, as the vast majority of home console and arcade boards' horizontal resolutions divide evenly into 3840. This crash has also been confirmed by Mike Chi.

[config.txt](https://github.com/libretro/RetroArch/files/1034803/config.txt)

**Comment by hizzlekizzle** [comment]
I use the simpler hdmi_cvt setting to get 1920x240, which works great, but 3840 width refuses to load. I haven't checked the log to see if it's the same as yours, but it wouldn't surprise me.

I would say the RPi3 GPU just isn't up to it, but I've heard that people have gotten 3840x2160 (i.e., 4K) resolution working, whatever that's worth.

**Comment by orbea** [comment]
@kevinfishburne Is this still an issue? Can you provide a backtrace with debugging symbols if it is?
