### ISSUE TITLE
Mouse polling wrong in core instance

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#4979]
Running a core with mouse control support, the mouse movement is really jerky as if the polling is only taken twice in a second.

bisect points to https://github.com/libretro/RetroArch/commit/e02cfe8cb01f256f6716ed94eb4f148e3e91b15d as the 1st bad commit.

Win7 x64.

**Comment by twinaphex** [comment]
Figure out a way to fix it by polling only once per frame. We cannot have multiple core_poll calls going on, one should be enough.

**Comment by Tatsuya79** [comment]
I tried some things but I don't understand the code.

Isn't it about the mouse needing a bigger polling rate than once a frame? 
(as there doesn't seem to be any issue with gamepads)

**Comment by retro-wertz** [comment]
tyrquake was suppose to be working, as far as mouse movements was a concern. it now almost unable to move. mouse can also be used in px68k, pointer is not smooth anymore and skipping frames.

**Comment by twinaphex** [comment]
So first thing we need to figure out is how the polling should work then for mouse so that it's smooth enough. The previous polling situation was a mess where core_poll was being littered about the place, so if we are going to fix the mouse, we should do this in a way so that it doesn't become a mess again.

**Comment by twinaphex** [comment]
Maybe it's the core's responsibility to poll twice if 'smooth' mouse input is desired? That way, the frontend won't get bogged down with multiple poll calls when it isn't necessary, since it seems only the mouse requires this level of precision.

**Comment by fr500** [comment]
@Tatsuya79 try reading all the core_poll() lines and then remove them one by one until the problem resurfaces.

**Comment by Tatsuya79** [comment]
I can remove all core_poll(); on [CASE lines after 2720](https://github.com/libretro/RetroArch/commit/e02cfe8cb01f256f6716ed94eb4f148e3e91b15d#diff-d5821156b896ba100e8b06d2be59a508L2721) without problem.

The problem appears when I move the core_poll(); from[ "static enum runloop_state runloop_check_state" ](https://github.com/libretro/RetroArch/commit/e02cfe8cb01f256f6716ed94eb4f148e3e91b15d#diff-d5821156b896ba100e8b06d2be59a508L2337)to ["int runloop_iterate"](https://github.com/libretro/RetroArch/commit/e02cfe8cb01f256f6716ed94eb4f148e3e91b15d#diff-d5821156b896ba100e8b06d2be59a508R2667).

**Comment by Tatsuya79** [comment]
Got the mouse good again by putting retro_ctx.poll_cb(); back into "static enum runloop_state runloop_check_state".

Moving [from here](https://github.com/libretro/RetroArch/blob/master/retroarch.c#L2972) to [here after this line.](https://github.com/libretro/RetroArch/blob/master/retroarch.c#L2486)

**Comment by Tatsuya79** [comment]
fixed https://github.com/libretro/RetroArch/commit/1cdd0e47cba51bf3990fb1ae33cf01b55e77a38f
