### ISSUE TITLE
Problems settings more than one cheat

### ISSUE THREAD

**Issue by VisitntX** [libretro/RetroArch#4981]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When you select more than one cheat to activate it just one of them (the last active) is passed to the game leaving the others without any effect. If you return, select again another one, apply and return to the game after some seconds that one will be active and the previously working cheat will be disabled (the effect, still on on the cheat list). This was tested on Game Boy and Game Boy Color.

### Expected behavior

Select multiple cheats at once.

### Actual behavior

Just one is working, the last one selected.

### Steps to reproduce the bug

1. Load Game Boy or Game Boy Color cheat
2. Select more than one cheat
3. Apply them

### Bisect Results

Since i tested it for first time a year ago, I can't remember the version by then, just the one tested recently.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.50 (also 1.60, the beta).

### Environment information

- OS: Windows 7 SP1 64 bits and Debian Stretch
- Compiler: not compiled by me.

**Comment by twinaphex** [comment]
Isn't this merely a core issue? As in - the problem is with the core you're using instead of RetroArch?

**Comment by VisitntX** [comment]
You're right. I will test it with another core to see if it replicates and then I'll update the info.

**Comment by VisitntX** [comment]
Indeed, it's a Gambatte core issue, my bad, sorry about it.

**Comment by twinaphex** [comment]
Maybe you can report it on our Gambatte core repo though, I think there is somebody in there actually who might be able to resolve the issue.

**Comment by VisitntX** [comment]
Alright, I'll post it there. Thanks a lot.

**Comment by VisitntX** [comment]
Sorry, but I can't move this one to the Gambatte core repo and I can't open an issue there either.

**Comment by twinaphex** [comment]
Opened an issues section for you there.

**Comment by VisitntX** [comment]
Much appreciated. Thank you very much.
