### ISSUE TITLE
build error: settings_t has no member named input

### ISSUE THREAD

**Issue by lucianposton** [libretro/RetroArch#4986]
## Description

Compilation fails with error

```
gfx/drivers_tracker/video_state_python.c: In function ‘py_read_input’:          
gfx/drivers_tracker/video_state_python.c:127:37: error: ‘settings_t {aka struct settings}’ has no member named ‘input
```

https://github.com/libretro/RetroArch/blob/master/gfx/drivers_tracker/video_state_python.c#L127 fails the compilation. From looking at https://github.com/libretro/RetroArch/blob/master/configuration.h#L267 , perhaps this line should be settings->input_joypad_map instead of settings->input.joypad_map ?

### Expected behavior

compilation success

### Actual behavior

compilation failure

### Steps to reproduce the bug

1. configure and compile source

### Bisect Results

n/a

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 46806e7204be0b9e99d3a191c5951503c5d54f55

### Environment information

- OS: linux 4.4.52
- Compiler: gcc 5.4.0

**Comment by twinaphex** [comment]
Should be fixed now with the most recent commit.

**Comment by lucianposton** [comment]
works now
