### ISSUE TITLE
Can you add the option for a portable installation?

### ISSUE THREAD

**Issue by wardrich** [libretro/RetroArch#4996]
I'd like to push most of the resources and configs over to my SD card.  It has more expendable memory, and it would allow a more portable experience (I could restore my preferences and configurations after flashing my phone).

It would be best if you could mirror the Retrospect tree on SD, then have the app pull all of the configs, overlays, etc. from there.  It would also be cool if there could be a way to install the base files to a location on SD.

**Comment by fr500** [comment]
Non system apps cannot write to the sdcard without going thru SAF
It's not gonna happen.

https://github.com/libretro/RetroArch/issues/5086
