### ISSUE TITLE
[Feature Request] Vibration/Force Feedback for DInput control devices

### ISSUE THREAD

**Issue by Watkinsjo2** [libretro/RetroArch#4998]
There are a sizeable amount of players who use dinput controllers in PSX titles, along with later console generations, I myself use a DualShock 1 controller for a more accurate experience while I play games such as Silent Hill 1, which make use of vibration as an indicator when your health has reached a certain point. It's quite handy for speedrunning for the game's 10-star ranking as it saves time from having to continuously open the menu and monitor your health. This feature would simply bring dinput controllers to the same level as xinput devices.

**Comment by spikeyxx** [comment]
Plus one. I am a stickler for using first party controllers with the appropriate systems and it is sad not having the vibration work for n64, dual shock etc.

**Comment by chewvodka** [comment]
If testing is required, I have a DualShock 2 controller as well as this adapter I am trying to make work:
https://www.amazon.com/dp/B00081AL50

**Comment by hizzlekizzle** [comment]
I hear motioninjoy will let your dinput devices masquerade as xinput devices, vibration and all:
http://ngemu.com/threads/how-to-fool-windows-into-thinking-a-normal-gamepad-is-xinput-one.171425/

**Comment by fr500** [comment]
MiJ is practically malware though

**Comment by chewvodka** [comment]
Except there needs to be a Linux solution for mer to work with.

**Comment by hizzlekizzle** [comment]
In linux, one of the drivers has rumble already, but I don't recall whether it's udev or linuxraw. You also need to be sure that your adapter actually supports rumble, as not all of them do. That is, PSX pads' rumble requires additional power (7-9v vs the standard USB's 5v) that may not be hooked up in the adapter at all.

**Comment by casdevel** [comment]
@Watkinsjo2 is this about adding rumble support to the 'dinput' joypad driver?

**Comment by Watkinsjo2** [comment]
@casdevel That's exactly it.

**Comment by casdevel** [comment]
Then, I should be able to help with this.

Also, I would like to see the FFB capabilities of various joypads (from direct input perspective). This will help me decide whether new menu option(s) are necessary or not. For this purpose I'll write one app that can output relevant joypad info from all available joypads. When I'm done with that I'll upload the app and we'll take it from there.

**Comment by Watkinsjo2** [comment]
Awesome, I've been trying to find a workaround for this that didn't involve using Steam's controller support. 

If you need me to test out any builds or something along the way I'd be happy to try!

**Comment by casdevel** [comment]
OK, test app can be downloaded from [https://github.com/casdevel/ffb-info/releases](https://github.com/casdevel/ffb-info/releases). Just run it and upload generated report somewhere. Report file (ffb-info.txt) will be saved in the current directory.

**Comment by Watkinsjo2** [comment]
Heres the file: https://www.dropbox.com/s/100yywqqlxaxz1k/ffb-info.txt?dl=0

**Comment by casdevel** [comment]
@Watkinsjo2 I started working on this. When I have something for testing I'll let you know.

**Comment by casdevel** [comment]
@Watkinsjo2 source is at [https://github.com/casdevel/RetroArch/tree/dinput](https://github.com/casdevel/RetroArch/tree/dinput) and binaries can be downloaded from [https://github.com/casdevel/RetroArch/releases/tag/v1.7.3-dinput-rumble](https://github.com/casdevel/RetroArch/releases/tag/v1.7.3-dinput-rumble).

Binary release contains one test core (FFB Test). Keyboard keys 1 trough 9 should activate rumble effect (hold shift key for the stronger motor). If device has only one motor then (without shift key) rumble will be unavailable.

**Comment by Watkinsjo2** [comment]
Sorry I took so long to get back with you. Tested out the build and keys 1-9 worked as intended. The Shift key motor didn't work so I'm going to assume this pad only has one motor then.

**Comment by casdevel** [comment]
@Watkinsjo2 

> Also, I'm not sure it if matters but keys 6-9 can be held down for a consistent rumble, 2-5 can only be pressed one at a time, and key 1 produces no rumble reagrdless

That is expected behavior. Key 9 is for the strongest effect and, as you go down, strength should go down and, at some point, motor can't spin constantly no more.

Report that you posted suggest that yours device should have two motors. Report of the device that I tested has almost the same report as yours and both motors responded as expected. I'm going to test this again with different device.

You didn't mentioned whether you tried some game? Also can you post few games/cores (preferably less CPU "hungry") that should support rumble so I can check this on my machine?

**Comment by Watkinsjo2** [comment]
@casdevel 

I just tested out the Beetle PSX core with Silent Hill, Dino Crisis 2, and Resident Evil 2/3. Rumble was working as intended in all 3 titles. 

Dino Crisis 2 is probably the best game out of the 3 to use as a test as the vibration activates whenever you move the character and has the strongest effects.

**Comment by Watkinsjo2** [comment]
@casdevel Just wanted to say thanks again for tackling this. Tested out the nightly build and everything has been smooth sailing. The vibration is also very strong which is awesome!

**Comment by casdevel** [comment]
OK, if there is nothing more, just close the issue since there is bounty for this on the Bountysource and I can't claim it while issue is open.

**Comment by Watkinsjo2** [comment]
@casdevel Any chance you could take a look at his in your spare time? Issue # 7168 is indeed true :(

**Comment by casdevel** [comment]
I'm aware of this problem. It's caused by device manufacturers not fallowing single standard. Device that I used during development was Logitech-s controller (don't remember exact model) that I borrowed from a friend and everything was working as expected.

Only solution to this issue is adding more settings which will allow user to select which FFB axis and effect will be used for rumble effects. Gain and maybe some other option(s) may be useful too.

If someone is willing to write menu and config code just let me know and I'll take a look at direct input API to see exactly which settings should be added and than I'll expand the driver code to take advantage of the new settings. I'm being a bit selfish here, but I really want to avoid RetroArch-s menu and configuration coding. Driver code, on the other hand, is not a problem.

**Comment by orbea** [comment]
@Watkinsjo2 Is this issue any different than the newer https://github.com/libretro/RetroArch/issues/7168? Do we need both open?

**Comment by Watkinsjo2** [comment]
@orbea I suppose not, so I guess I can close this one out.

**Comment by daFourch** [comment]
I'm confused. Does Vibration work with a DInput gamepad on RetroArch? I installed PlayStation Now on PC, so my Dualshock 3 is instantly working on RA, with no SCPToolKit or DS4Windows. But unfortunately, rumble feature is not working.

**Comment by nagrizolich** [comment]
> I'm confused. Does Vibration work with a DInput gamepad on RetroArch? I installed PlayStation Now on PC, so my Dualshock 3 is instantly working on RA, with no SCPToolKit or DS4Windows. But unfortunately, rumble feature is not working.
@daFourch 
As far as I'm aware official Sony drivers for DualShock 3 do not feature vibration support. You need to use 3rd party drivers like ScpToolkit or VigEm.
