### ISSUE TITLE
Unicode characters in filenames not recognized

### ISSUE THREAD

**Issue by xunkar** [libretro/RetroArch#5019]
When scanning a folder, games with unicode characters in their filenames or in any parent folder name will not be imported, nor can they be opened manually. Trying to do so will result in a "failed to load content" error. Renaming the file and the folders without unicode characters fixes this behavior. Filenames are also garbled when displayed inside RetroArch.

RetroArch 1.6
Windows 10 x64

**Comment by bparker06** [comment]
This is a known issue on Windows, Linux is not affected.

**Comment by xunkar** [comment]
I'd like to add that for some reasons not every character seem to provoke that bug, for example using the en dash U+2013 (–) does not prevent the game from being loaded (even though the character isn't displayed properly in the game) while accented letters of any kind do.
