### ISSUE TITLE
[1.6.0] RetroArch breaks internet browser's Flash player

### ISSUE THREAD

**Issue by Zanmato27** [libretro/RetroArch#5020]
I was using the latest stable build of RetroArch, 1.6.0., and I wanted to watch a video while I was playing a game in RetroArch, however there is a problem where RetroArch causes the video I'm watching on YouTube to suddenly stop playing in the background. I went to the tab that I had the video playing and refreshed the page, but after refreshing the page the video plays but the audio on the YouTube video is muted without touching the mute button on the video or muting the tab itself. I never ran into this problem with the previous 1.5.0. versions or older, so I'm not sure if this is an issue with RetroArch on how it handles sound or my Flash player is outdated. I have tested this bug on Mozilla Firefox and Google Chrome and both browsers had this issue occurring with the video. I even used different audio drivers with RetroArch (DSound and WASAPI) and both drivers breaks audio from the Internet Browser. The only way for the audio to come back to the video was to close RetroArch and refresh the page afterwards.

Steps to reproduce:
1. Play a video on YouTube
2. Run RetroArch 1.6.0. and leave it running
3.  Attempt to refresh the page after it freezes the video
4. Attempt to get audio into the video after refreshing the page

Version: RetroArch 1.6.0. (Stable) 64-bit

OS: Windows 10 Home 64-bit

**Comment by ofry** [comment]
First update your Flash player:

https://get.adobe.com/flashplayer/

**Comment by Zanmato27** [comment]
I just my Flash player updated to its latest version and I still get this problem with RetroArch breaking Flash-based videos.

**Comment by twinaphex** [comment]
What do you expect us to do about this?

There is zero we can do about it, and Flash is a closed-source binary blob.

**Comment by fr500** [comment]
It's most likely a gpu driver issue, flash uses GPU acceleration.

**Comment by ofry** [comment]
Please give me which GPU you have?

**Comment by Zanmato27** [comment]
My GPU is Nvidia GeForce GTX 750.  I'm not sure if how to use the HTML5 player but I think that might be what I'm mistaking my issue with if YouTube uses a HTML5 player by default now.

**Comment by ofry** [comment]
Then which version of NVidia GPU driver you have?

I found latest is 382.33.

**Comment by Zanmato27** [comment]
I just installed 382.53, the most recent driver for my 750, and this problem still persists.

**Comment by bparker06** [comment]
This sounds more like an audio driver problem to me. If you disable the audio in RetroArch (setting a null audio driver is probably the best way), does the youtube video's sound play correctly? The driver may have some kind of "exclusive mode" issue, or perhaps maybe you or something else has [accidentally set it to be that way](http://i.imgur.com/khmdNz5.png).

**Comment by Zanmato27** [comment]
I have tried Null driver before and it still continued to happen. However, after disabling "exclusive mode" on my audio output devices, the issue with Flash player breaking went away. Somehow it was on by default by turning it off fixed the problem. Thank you, @bparker06.
