### ISSUE TITLE
32-bit RetroArch is downloading 64-bit cores (libs)

### ISSUE THREAD

**Issue by BetaLeaf** [libretro/RetroArch#5023]
## Description

When I updated to 1.6.0, from 1.5.0, none of my cores work anymore, even after deleting the core folder and redownloading each core.

### Expected behavior

Game should launch with the presaved core.

### Actual behavior

It says "Failed to open libretro core" and my debug log says 
```
RetroArch [ERROR] :: Failed to open libretro core: "D:\OneDrive\PortableApps\RetroArchPortable\App\RetroArch\cores\gambatte_libretro.dll"
RetroArch [ERROR] :: Error(s): %1 is not a valid Win32 application.
```

### Steps to reproduce the bug

Not sure.

### Bisect Results

This started happening after updating from 1.5.0 to 1.6.0.

### Version/Commit

- RetroArch: 1.6.0

### Environment information

- OS: Version	10.0.15063 Build 15063
- Compiler: N/A; Downloaded from official website.

**Comment by BetaLeaf** [comment]
@fr500? help?

**Comment by hizzlekizzle** [comment]
Are you trying to run 32-bit libs with a 64-bit RetroArch?

Also, the '%1 is not a valid Win32 application' seems weird. Are you launching from a launcher/script?

**Comment by BetaLeaf** [comment]
Sorry for the late response. I am using a Launcher, specifically one made for PortableApps.com. Even if I don't use the launcher, I still have this issue, even on a clean install.

**Comment by hizzlekizzle** [comment]
so, what about the 32-bit vs 64-bit thing? Are you sure you're using libs that match the bitness of the executable?

**Comment by BetaLeaf** [comment]
I narrowed it down a bit. @hizzlekizzle you are correct. However, even if I run a 32-bit RetroArch and have it download the latest libs, it still won't load them. I have to use 64-bit libs. What is going on here? Why am I unable to download 32-bit libs?

**Comment by BetaLeaf** [comment]
Good timing hahaha. I was just replying.

**Comment by hizzlekizzle** [comment]
If you're having to use 32-bit libs it means you're using a 32-bit RetroArch build. It will only work with libs that are compiled for the same architecture as the executable.

**Comment by BetaLeaf** [comment]
Let me clarify. I want to use 32-bit RetroArch, but 32-bit RetroArch keeps downloading 64-bit libs. What can I do to fix this?

**Comment by hizzlekizzle** [comment]
I just had someone check and they weren't able to reproduce. Can you try moving your config to another place (that is, so RetroArch creates a new one) and see if the problem persists?

**Comment by BetaLeaf** [comment]
Alright I will

**Comment by BetaLeaf** [comment]
Weird its working now. I extracted to a new directory.

**Comment by BetaLeaf** [comment]
I've figured it out. Since I was sharing the config file for both versions in my launcher, it was not able to handle the core_updater_buildbot_url properly. I have fixed this issue.
