### ISSUE TITLE
[1.6.0] Beetle PSX system not detected when scanning content

### ISSUE THREAD

**Issue by cdxemu** [libretro/RetroArch#5029]
## Description

A PlayStation playlist is not created when scanning .cue/.bin files (redump CRC-verified) with latest Beetle PSX core. Scanning works for these same files with previous RetroArch versions.

With logging enabled (where [PATH] is the directory and filename):

>RetroArch [INFO] :: Parsing CUE file '[PATH].cue'...
>RetroArch [INFO] :: Found first data track on file '[PATH].bin+0'
>RetroArch [INFO] :: Reading first data track...
>RetroArch [INFO] :: Comparing with known magic numbers...
>RetroArch [INFO] :: Could not find compatible system.

### Expected behavior

PlayStation playlist would be generated by scanning content.

### Actual behavior

PlayStation playlist was not generated.

### Steps to reproduce the bug

1. Install RetroArch to a fresh directory.
2. Download the PlayStation (Beetle PSX) core with the Online Updater/Core Updater.
3. On Import Content tab: Scan directory containing the PSX .cue and .bin files.
4. Check if PlayStation playlist appears.

### Bisect Results

Can reproduce consistently in 1.6.0 (stable).
Could not reproduce in 1.3.6 or 1.5.0 (stable).

### Version/Commit
You can find this information under Information/System Information

- Git version: a4358de

### Environment information

- OS: Windows 7 64-bit

**Comment by retro-wertz** [comment]
there is some truth to this that scanning psx images does not add to playlist anymore. using latest commit of RA, updated rdb and info files.

log - https://hastebin.com/iyoxoninik.sql

**Comment by twinaphex** [comment]
Maybe because @RobLoach and others maybe updated to DAT files which no longer contain the game's serial names which our scanning system depends on as to not make the scanning process godawfully slow? 

BTW, the same will apply for other systems like the PSP. Upstream committers to libretro-database really need to start taking this into consideration when pushing updates.

**Comment by retro-wertz** [comment]
first bad commit - https://github.com/libretro/RetroArch/commit/cf2f8f6489c3300309cff662513975a76e6e20f4
PSX scanning is affected and scanning any will not add to playlist. 
ISO PSP works fine, and probably others.
full log of psx scanning with last 3 items are psp iso from this commit.
https://hastebin.com/figocasuwu.sql

all previous commits works fine scanning psx cue sheets.

**Comment by twinaphex** [comment]
See if this fixes it -

https://github.com/libretro/RetroArch/commit/3d54afdc1bd6f1269358e22c6fd8746faee6283b

**Comment by retro-wertz** [comment]
no. still getting "RetroArch [INFO] :: Could not find compatible system."

**Comment by twinaphex** [comment]
Check if it's fixed now.

If not, try to make some changes to task_database_cue.c similar to the changes you saw in the commit that broke it; see if you can devise a fix that way.

**Comment by retro-wertz** [comment]
hi. reverting this part only should be enough 
https://hastebin.com/omapajequr.cpp

**Comment by twinaphex** [comment]
Check if this fixes it -

https://github.com/libretro/RetroArch/commit/6c81007eb913a4ab5d691358d3d6e38e7e45f60a

**Comment by retro-wertz** [comment]
yes, psx scanning should be working now.
