### ISSUE TITLE
[iOS] 'process_sinc_neon_asm' is invalid on arm64 compile

### ISSUE THREAD

**Issue by EriolGaurhoth** [libretro/RetroArch#5032]
## Description
When I compile RetroArch for iOS on the standard armv7, it works compiles and runs fine, but when I switch to arm64 (in anticipation of iOS 11 killing all 32-bit apps), I get the following error:

"Implicit declaration of function 'process_sinc_neon_asm' is invalid in C99"
in sinc_resampler.c

I'm trying to compile the latest version.

**Comment by RobLoach** [comment]
Ran into this over at https://github.com/libretro/libretro-chailove/issues/322 ......

@mudlord Have you seen this before?

**Comment by twinaphex** [comment]
This should no longer be an issue I believe.
