### ISSUE TITLE
some keypad buttons don't work on GNU/Linux

### ISSUE THREAD

**Issue by shizeeg** [libretro/RetroArch#5034]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

on my GNU/Linux I can't remap any RetroPad button to keypad0, keypad1, keypad2, keypad3

keypad4, keypad5, keypad6, keypad7, keypad8, keypad9 work wine, though.

on Windows every button works fine.

### Expected behavior

working kp_1 to kp_3 and kp_0 buttons on keypad.
show us lefties some love. :)

### Actual behavior

when I try to bind any button to keypad1, keypad2 or keypad3 it doesn't work.

### Steps to reproduce the bug

1. Boot into GNU/Linux (Arch Linux x64 in my case)
2. Press Num Lock to enable numpad
3. Run RetroArch 1.6.0 or any previous version (1.5.x has the exact same behavior)
4. Enter "Input user 1 binds" in RetroArch menu
5. Try to bind any button to keypad1, keypad2 or keypad3
### Bisect Results

[Try to bisect and tell us when this started happening]

I think I've found the cause of my issues in this file:

https://github.com/libretro/RetroArch/blob/master/input/input_keymaps.c#L935-L938
`XK_KP_Down` must be equal to `XK_KP_2` not `XK_KP_1`, etc.

- RetroArch: 1.6.0 or 1.5.3 (the 2 I've tried)

### Environment information

- OS: Arch Linux x64 (Linux 4.10.11-1-ARCH x86_64)
- Compiler: GCC (7.1.1) 64-bit

**Comment by RobLoach** [comment]
Being discussed over at https://github.com/libretro/RetroArch/issues/5033 and https://github.com/libretro/RetroArch/issues/5016 .

Suggest closing this one.

**Comment by shizeeg** [comment]
@RobLoach yeah, I have those too, but only with the latest HEAD. With version 1.6.0 only KP0, KP1, KP2 & KP3 don't work I fix this myself there https://github.com/libretro/RetroArch/pull/5039

**Comment by RobLoach** [comment]
@shizeeg If you switch to `udev` input driver, are things working? Are you using `x`?

**Comment by shizeeg** [comment]
@RobLoach I've tried with every input driver available (sdl2, udev, x, linuxraw) behavior still the same. I can't understand why, still investigating. :)
