### ISSUE TITLE
Slow Scan Directory with 1.6.0 on Android

### ISSUE THREAD

**Issue by PalebloodSky** [libretro/RetroArch#5041]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch 1.4.1 improved directory scanning performance tremendously. 1.5.0 was very fast. Now with clean install of RetoArch 1.6.0, directory scanning is slow again like before 1.4.1 days. Very very slow and even not detecting roms.

### Expected behavior

Scan Directory is fast and detects all my roms.

### Actual behavior

Scan Directory is slow and doesn't detect all my roms.

### Steps to reproduce the bug

1. Clear cache/settings
2. Configure initial settings and auto updating all packages
3. From XMB > + > Scan Directory > chose directory to scan

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.0

### Environment information

- Device: Mi Box 4K (US version)
- OS: Android 7.0
- Compiler: Clang/LLVM (3.8.256229) 32-bit
- RetroRating level: -1
- Memory in megabytes: 732/1722 MB

**Comment by RobLoach** [comment]
What are some CRCs of files you have?

**Comment by PalebloodSky** [comment]
I haven't changed any of the files, they are all No-Intro rom set and they all scanned quickly and were detected. Each rom is in a separate ZIP. Example CRC:  BE3808FA

**Comment by PalebloodSky** [comment]
Ok looks like I was wrong. It doesn't look like a regression with 1.6.0. It looks like RetoArch is no longer finding any roms as of even 1.5.0. Previously it would scan and find quickly all of my roms. I haven't changed a single thing with my no-intro collection only upgraded RetroArch but now it scans extremely slow and finds nothing. It would seem scanning/database is broken.

**Comment by twinaphex** [comment]
Maybe the RDB files have simply grown too big with all the extra romsets and romhacks added to them? Maybe that is what is slowing everything down?

**Comment by PalebloodSky** [comment]
Nothing has grown in size. I've kept the exact same no-intro romset for years and only keep 150 top roms for each Core zipped in separate folders. Literately no changes. It suddenly stopped being able scan/detect any of them as of 1.6.0.

**Comment by RobLoach** [comment]
Been a few changes since 1.4.1 that @bparker06 and @Kivutar brought in to improve scanning:

- Better indexing through the task queue
- Will index the files in the zip before processing
- Recursive scanning
- Some updates in serial detection

In addition to that, there have been updates to No-Intro since. It is possible that the roms have had patches applied to them. We don't carry old CRC data. I can't find reference to `BE3808FA` anywhere in libretro-database or No-Intro itself. What game is that?

**Comment by PalebloodSky** [comment]
Apologize I did take it of the zip file, see below. From the "No-Intro-Collection_2016-01-03_Fixed" I've used these roms for over a year and not had an issue with RetoArch scanning. Yea scanning greatly sped up with 1.4.1 as you described above, and suddenly with 1.6.0 they aren't detecting anymore.  I've made no changes to the roms just did a clean 1.6.0 install then updated all the package/database/etc..

_CRC check examples using RapidCRC 0.6.1:_
Legend of Zelda, The - Link's Awakening DX (USA, Europe) (Rev B) (SGB Enhanced).gbc
06887A34

Chrono Trigger (USA).sfc
2D206BF7

Thanks a lot for your help.

**Comment by RobLoach** [comment]
Scanned correctly here. Could Android not have .zip support? That would make no sense. Here's a screenshot of ChronoTrigger with the same CRC after scanning.
![screenshot at 2017-06-09 16-09-17](https://user-images.githubusercontent.com/25086/26992774-257bdfb6-4d2e-11e7-87c5-8e95a5d5f034.png)

**Comment by fr500** [comment]
not sure on the latest but scanning zips worked fine in 1.5.0

**Comment by bparker06** [comment]
@PalebloodSky Try going to online updater -> update core info files and update databases, then scan again.

**Comment by PalebloodSky** [comment]
Yes, I've tried those suggestions... thanks. The problem is perhaps not a RetroArch issue but something on my end. Maybe the Android 7.0 upgrade a few months ago, performed a clean wipe and set everything back up but the scanning issue persists :(

Perhaps something to do with RetroArch scanning the /storage/emulated/0/... paths in Nougat, I've used other mount posts like /sdcard/... in the past as well.

Guess this can be closed, must be on my end or maybe Android 7.0 related.

**Comment by bparker06** [comment]
We do test with Android 7 on nvidia shield TV so I'm not sure why you're still having issues. Reading from the emulated/0 path should most definitely work even if you denied the permissions request for storage.

**Comment by fr500** [comment]
@PalebloodSky try this, clean data, start retroarch, grant permissions and exit
Then use a file manager, go to Android/data/com.retroarch/files/

remove retroarch.cfg
try again.

**Comment by PalebloodSky** [comment]
@fr500 - progress! Followed your steps, then used online updater etc., and scanned rom folders. It found all roms again! Oddly the scan is extremely slow, similar to pre-1.4.1 days, but at least it's finding them now. Maybe it's a storage regression in the Mi Box build of Android 7.0, although everything else on the box is very fast. Not sure why the scanning speed is extremely slow, but thank you, it's finding roms!

**Comment by PalebloodSky** [comment]
Took 7 minutes to scan a 200 snes rom folder :)  Took about 20 seconds last wipe I did for 1.5.0. But Android 7.0 update was also in between so might be that. Again thanks for help not sure about the speed though! 👍

**Comment by bparker06** [comment]
@PalebloodSky The latest android build should have the path issue fixed to where you don't have to delete retroarch.cfg anymore.

**Comment by jvook** [comment]
Are these the same issue?

https://www.reddit.com/r/RetroArch/comments/6jkuo3/nvidia_shield_tv_android_not_scanning/?st=j4eas9ox&sh=e5b1b1e9
https://www.reddit.com/r/RetroArch/comments/6garza/retroarch_directories_for_nvidia_shield_scanning/?st=j4easruy&sh=58c3b7e7
https://www.reddit.com/r/RetroArch/comments/6fgybu/scan_for_content_on_android/?st=j4eat50b&sh=ff37dc5b
https://www.reddit.com/r/RetroArch/comments/6i6hmo/wont_add_to_collection_after_update/?st=j4eatchp&sh=5ff538e2

Solution is to update to nightly?

**Comment by PalebloodSky** [comment]
Yes it looks like those are all the same issue best I can tell... It appears to be resolved in the nightly. I look forward to the next release.

**Comment by qphoria** [comment]
Seeing the same with 1.6.4. Scanning my nes folder of 678 roms.. it keeps updating xxx/12562: Scanning storage/external_sd/blah/blah and xxx number appears to be the current scanned count which updates about once every 7 secs.  So it's been running about 12 hours and its only at 4166/12562
1. Not sure where it gets 12562 files in a folder of 678
2. Why so slow?

**Comment by aarononeal** [comment]
I was seeing extremely slow scans too. PR #5407 fixes it for me.

**Comment by RobLoach** [comment]
This issue should be resolved. 👍

**Comment by PalebloodSky** [comment]
Yes it's resolved.

**Comment by edneyhelene** [comment]
I have same problem.
