### ISSUE TITLE
The procedure entry point "_ZNKSt7__cxx1112basic_stringlcSt..." could not be located in the dynamic link library

### ISSUE THREAD

**Issue by firewater2** [libretro/RetroArch#5043]
Error prompted when launching any game, on any core, on latest RA x64 version, with OpenGL.

**Comment by meepingsnesroms** [comment]
What system?
Linux, mac, and windows all fall under "x64 opengl".

**Comment by firewater2** [comment]
Yes, sorry - Windows 8.

**Comment by firewater2** [comment]
Probably a matter of a corrupted install as it was a mix of the latest .exe + a backup of an older version. I went back to just the backup  an it runs fine. It's also possible it's related to the latest RA version, but I don't feel like testing it out right now.

**Comment by bparker06** [comment]
Most likely it was a mismatch of the libstdc++6.dll from the previous version.
