### ISSUE TITLE
Savegame does not get saved unless retroarch is quit using quit button 

### ISSUE THREAD

**Issue by LinAGKar** [libretro/RetroArch#5046]
## Description

When saving the game in mGBA (tested in Spyro: season of ice), the savegame only seems to get saved if you then quit RetroArch using the "quit RetroArch" button. If you restart RetroArch the normal way (by dragging the window off the screen in the recent apps list), all saved progress during that session gets lost. 

### Version/Commit

- RetroArch: 1.6.0

### Environment information

- OS: Android 7.1

**Comment by fr500** [comment]
There is SRAM autosave interval for that.
Killing the app of course doesn't save, you're killing it.
