### ISSUE TITLE
Autoconfig hotplug broken

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#5048]
## Description

Autoconfig is not working anymore when plugging a joypad while RetroArch is already running.

### Expected behavior

Launch RetroArch, plug a joypad, being able to use it.

### Actual behavior

When I plug the joypad, the pipeline get stuck, and the keyboard also stops working.

### Steps to reproduce the bug

Launch RetroArch
Plug a joypad (I tested with a DualShock 4)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: cea6dbbb6a4d639299dd11297513124be406336f

### Environment information

- OS: Arch Linux
- Compiler: GCC

**Comment by twinaphex** [comment]
Tell me which input driver this is with.

Also try to see if you can do a bisect. 

I can't reproduce this issue at all.

**Comment by twinaphex** [comment]
I indeed accidentally caused a regression.

https://github.com/libretro/RetroArch/commit/c70526b7af04a844928d5582f6c087e919017b87

See if this makes things work properly again.

**Comment by Kivutar** [comment]
Fixed thanks
