### ISSUE TITLE
Keyboard typing not working in KMS

### ISSUE THREAD

**Issue by Kivutar** [libretro/RetroArch#5052]
## Description

On Linux, when launching RetroArch from the console, in DRM/KMS mode, the keyboard is working, but we can't type anything in the input area like the search dialog. This is a regression.

### Expected behavior

I expect to be able to inut characters from the keyboard.

### Actual behavior

When I try to type, nothing happens and I am stuck in the UI. The only way to escape this is to reboot my laptop

### Steps to reproduce the bug

1. Launch RA in DRM/KMS
2. Hit / to trigger the search box
3. Try to type

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 612cb54cfed66008c8a7d1e4e2d834e23067e806

### Environment information

- OS: Arch Linux and Lakka
- Compiler: GCC

**Comment by twinaphex** [comment]
The keyboard still works for gamepad operations yeah but not when inputting text in the search bar.

Can you try doing a bisect?

**Comment by Kivutar** [comment]
I remember that it was due to the refactoring in the input driver where libxkbd was not used anymore in udev input driver.

There is a discussion there about this issue https://github.com/libretro/RetroArch/issues/4775

**Comment by twinaphex** [comment]
This solves the issue for me on my end -

https://github.com/libretro/RetroArch/commit/1598042e8e9bb9610f3449b0f4061aeff55649c8

**Comment by Kivutar** [comment]
Soved for me too. Thanks.
