### ISSUE TITLE
How do I autoload a rom and core with the Web Player

### ISSUE THREAD

**Issue by davideo7** [libretro/RetroArch#5057]
I can't seem to figure out how to get the RetroArch Web Player to automatically start playing a core with a rom.  Is this possible?  If not, how hard would it be to get this added?  Thanks.

**Comment by orbea** [comment]
This is not a support forum, you are much more likely to get help at the forum, discord or irc. If you still have any questions please ask there. If you have any issues please make a new issue. Thanks!
