### ISSUE TITLE
about wonderswan rotation

### ISSUE THREAD

**Issue by adolfobenjaminv** [libretro/RetroArch#5058]
Hello everyone, im starting with this beautiful multiemulator, and god, its amazing!
Every emulator works great, but i have some questions about wonderswan

There are some wonderswan games that uses the screen rotated in portrait mode, ej: judgment silversord, tetris, gumpei ex, and im wondering if it would be possible to add and easy option to play them

I was wondering something like this:

Two layouts, one for portrait mode, and one for landscape mode, so when you press a button (ex: select)
The screen autorotates and use the layout A or layout B.

Someone thinks this would be possible? maybe as a core option

Thanks for your hard work

**Comment by fr500** [comment]
This is about RetroArch, not a core issue tracker. Closing.
Feel free to reopen on the proper repo or libretro meta

https://github.com/libretro/beetle-wswan-libretro/issues/
