### ISSUE TITLE
Custom Viewport is no longer overridable per-core or per-game

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#5060]
## Description

Custom viewport no longer saves in config overrides

### Expected behavior

Custom viewport would save normally in the override file

### Actual behavior

It's being reset since it's not populating the parameters in a settings_t instance but a custom_vp structure declared inside the populate_settings_uint function:

    struct video_viewport *custom_vp = video_viewport_get_custom();

### Bisect Results

Git Blame: 
https://github.com/libretro/RetroArch/blame/master/configuration.c#L1341
Commit:
https://github.com/libretro/RetroArch/commit/79c76276512e04f394679405b756c8cdd5ad062e

**Comment by twinaphex** [comment]
Blind commit here to see if this resolves the issue -

https://github.com/libretro/RetroArch/commit/e0cc113689aae8cd8dcf659c8f271290e9acd5fc

**Comment by danieljg** [comment]
I'm not sure this was actually fixed. On a first attempt, with clean config folder, I was able to save a core override. Subsequent attempts to overwrite the core override were unsuccessful.
