### ISSUE TITLE
Nuklear does not compile

### ISSUE THREAD

**Issue by allanin** [libretro/RetroArch#5065]
Compiling current version of Retroarch with enabled nuklear does not work.

`
CC menu/drivers/materialui.c

CC menu/drivers/nuklear/nk_common.c
CC menu/drivers/nuklear/nk_menu.c
CC menu/drivers/nuklear/nk_wnd_main.c
menu/drivers/nuklear/nk_wnd_main.c: In function 'nk_wnd_main':
menu/drivers/nuklear/nk_wnd_main.c:87:39: error: 'settings_t {aka struct settings}' has no member named 'directory'
          picker_startup_dir = settings->directory.libretro;
                                       ^
menu/drivers/nuklear/nk_wnd_main.c:99:39: error: 'settings_t {aka struct settings}' has no member named 'directory'
          picker_startup_dir = settings->directory.menu_content;
                                       ^
make: *** [Makefile:157: obj-unix/menu/drivers/nuklear/nk_wnd_main.o] Error 1
make: *** Waiting for unfinished jobs....
`

OS is Linux (Gentoo).

**Comment by fr500** [comment]
It's not even closed to functional.
