### ISSUE TITLE
Distribute RetroArch as an AppImage

### ISSUE THREAD

**Issue by probonopd** [libretro/RetroArch#5069]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

I have made some RetroArch AppImages for testing:
https://bintray.com/probono/AppImages/RetroArch#files

They have been generated using:
https://github.com/AppImage/AppImages/blob/master/recipes/retroarch/Recipe

To build your own, run on any deb-based system:

```
wget -c https://raw.githubusercontent.com/AppImage/AppImages/master/recipes/retroarch/Recipe
bash -ex Recipe
```

Unfortunately since RetroArch with all optional parts has become bigger over the past months, it no longer fits into the 250 MB Bintray filesize limit so I can't offer more recent ones there.

Alternatively the Open Build Service could be used to generate AppImages.

I think my recipe for the AppImage is "solid and working", the only question is who would run the script regularly and where would it be hosted.

Alternatively we could now use the [Open Build Service](https://build.opensuse.org/) to produce and host the AppImages:
https://git.io/obs-ai

**Comment by probonopd** [comment]
In this video, RetroArch binary delta updates are demonstrated:

[![](http://img.youtube.com/vi/FqVAtHdK1N0/0.jpg)](https://www.youtube.com/watch?v=FqVAtHdK1N0)

https://www.youtube.com/watch?v=FqVAtHdK1N0

Discussion in the forum:
https://forums.libretro.com/t/linux-retroarch-runtime-for-every-modern-distro-with-appimage/4965/13

**Comment by hizzlekizzle** [comment]
I've been looking at AppImage/FlatPak/Snap over the past few days and it seems like a fair hassle to get each one set up with working recipes, but since that's already been done here, I see no reason not to work toward "official-izing" it.

**Comment by probonopd** [comment]
@hizzlekizzle happy to help. Just let me know what you need. Also, AppImage devs usually hang out in #AppImage on irc.freenode.net.

**Comment by fr500** [comment]
We don't really want bundled cores for various reasons.

**Comment by RobLoach** [comment]
With fr500 on this. I imagine it would ship....

- libretro-database
- retroarch-assets
- libretro-core-info

**Comment by RobLoach** [comment]
https://github.com/robloach/retroarch-flatpak ..... Submitted it to [Flathub](http://flathub.org).

**Comment by probonopd** [comment]
That does not help the subject of this issue @RobLoach as it does not give many of the advantages stated above.

**Comment by RobLoach** [comment]
@probonopd Agreed, it's not AppImage, but is related. Don't mean to derail the issue, just add it in here for those that are interested. Continue on!

**Comment by RobLoach** [comment]
1. Deleted ~/.config/retroarch
2. Ran RetroArch-1.6.1.glibc2.17-x86_64.AppImage
3. Loaded up correctly, with assets in tact
4. Was unable to download any Core

![screenshot at 2017-06-30 21-29-06](https://user-images.githubusercontent.com/25086/27758116-583d3176-5ddb-11e7-931a-a7f57da89d80.png)

**Comment by bparker06** [comment]
@probonopd 

```
$ ./RetroArch-1.6.1.glibc2.17-x86_64.AppImage
/tmp/.mount_RetroAooUe3V/usr/bin/retroarch: relocation error: /tmp/.mount_RetroAooUe3V/usr/bin/retroarch: symbol _ZNSt13runtime_errorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
```

on Ubuntu 14.04

**Comment by probonopd** [comment]
@bparker06 strange. Can you try on Ubunu 14.10 or later?

**Comment by hizzlekizzle** [comment]
@RobLoach 
In your ~/.config/retroarch/retroarch.cfg, is your libretro_directory still set to /usr/lib/x86_64-whatever/libretro? If so, change it to somewhere user-writeable and try again.

@probonopd 
FYI, those reports are both referring to an AppImage built with a modified Recipe that uses the core updater rather than bundling the cores inside the package:
https://pastebin.com/buwanQyW
If we were to make a retroarch.cfg that lives in the AppImage bundle, is there any way to directly mess with it after the fact? That is, if someone needs to open it with a text editor?

**Comment by probonopd** [comment]
> If we were to make a retroarch.cfg that lives in the AppImage bundle, is there any way to directly mess with it after the fact? That is, if someone needs to open it with a text editor?

No, since AppImages are read-only. But a well-behaved application should, upon the first launch, write its config file to `~/.config/`, where it could be edited subsequently by the user.

This is not so different from a traditional installation to `/usr`, where the user also has no write rights.

**Comment by RobLoach** [comment]
@hizzlekizzle Yes, after changing the Core directory, I was able to properly download and use a Core.

**Comment by LeCharlatan** [comment]
AppImage is just wonderful !

I downloaded some AppImage of older versions and I've to admit it's a real advantage on Linux !

Including Cores inside AppImage isn't a bad idea at all for people that wants to play as soon as possible or not online. Well, same for people that has poor or bad network, they can play quickly on others computers, Linux Distro... ;)
Since you can change core path and download them using AppImage by changing options if you want latest cores or play online (it could download cores to .config/RetroArch/cores/ for example), it makes nothing harder.

So, please, include Cores inside the AppImage build, this is really helpfull on Linux world :D

**Comment by LeCharlatan** [comment]
Hi
@probonopd @hizzlekizzle 
Any news about AppImage of RetroArch or is abandonned ?

**Comment by hizzlekizzle** [comment]
It's definitely still a thing. We haven't gotten it on our buildbot, but gouchi got it on the OpenSUSE build service, I think.

I also modified the script a little and put it on our buildbot to anticipate our own builds, but something broke with it at some point and I need to revisit it.

I personally like it better than the other universal packages, though I actually use the snap package just because its sandbox is so weird it really needed someone to use it full-time for bug-detection/fixing.

**Comment by LeCharlatan** [comment]
Hi hizzlekizzle,

> I personally like it better than the other universal packages

I like AppImage more than other universal packages too. It's really easy to use for end-users :smiley: 
Then I'll wait for news since it's still on its way

Thanks for news about AppImages, I can't wait it :smile:

**Comment by Ferk** [comment]
The only disadvantage I see with AppImage is that you cannot know exactly what libraries and versions will be available in the host computer so you might need to bundle all of it, even basic things like libc itself, unless you are willing to take the risk of it not really working everywhere. This also means that you end up with huge binaries with so many libraries bundled that it will require active maintenance from the packagers to keep up to date when a vulnerability requires updating the dependencies.

Flatpak does solve those issues 
with shared runtimes. As long as you have a distro with flatpak installed it works (the good news is that most of the popular distros are on board with it and are bringing it preinstalled). It actually is a worthy replacement for package managers when it comes to desktop apps.

**Comment by hizzlekizzle** [comment]
We've had problems with incompatibility with older distros with the flatpak, actually.

**Comment by LeCharlatan** [comment]
Hi @Ferk

Flatpak needs something to install and network, AppImage doesn't plus it couldn't be easier to use so of course it needs to add all libs. But when I use Krita / RPCS3 or any others AppImages, it works just like a charm. I think this is a false problem.

About the security, when create AppImage, you'll get (normally) latest security libs on the Distro it's done. I'm not sure it needs so much active maintenance. Maybe it needs to be clarified by @probonopd

**Comment by probonopd** [comment]
> About the security, when create AppImage, you'll get (normally) latest security libs on the Distro it's done. I'm not sure it needs so much active maintenance. Maybe it needs to be clarified by @probonopd

Libraries that come with all distributions in the default installation are assumed to be handled by the base system (= distribution) and do not need to be bundled inside the AppImage. Security updates will be handled by the operating system. Example: glibc.

Libraries that do not come with all distributions in the default installation are supposed to be bundled inside the AppImage. In case a security vulnerability in one of those libraries is detected, then the author of the AppImage should release a new AppImage with the updated library.

**Comment by LeCharlatan** [comment]
@Ferk : I completly understand your point about security, I just want to point that AppImage is just easy for everyone, even for those not good at using computer :) Last time I would try to install a FlatPak, I found the way little annoying.
Anyway, you're right it's not a topic about differences between AppImage and FlatPak.

@probonopd : Thanks for clarifying the libraries and security points. Keep the good work about AppImage, I really like it :D

**Comment by Wowfunhappy** [comment]
> but gouchi got it on the OpenSUSE build service, I think.

I think you're referring to: https://build.opensuse.org/package/show/home:gouchi:branches:OBS:AppImage:Templates/RetroArch

Is it possible to actually download this? I'm trying to obtain an at least semi-recent version of RetroArch as an App Image. I need to be able to install to a 100% offline computer, and that's still relatively difficult with FlatPak.

**Comment by hizzlekizzle** [comment]
Yeah, that's the one. @gouchi , can you go here and mark the "publish flag" for 'all'?
https://build.opensuse.org/repositories/home:gouchi:branches:OBS:AppImage:Templates/RetroArch

**Comment by Wowfunhappy** [comment]
> But you can also download them from another device and copy them manually if you don't have connection in the PC.

Not to get too off topic, but no, you can't. At least, not from the repositories most stuff seems to be hosted on (Flathub).

You can _create_ offline-installable bundles with `flatpak build-bundle ~/.local/share/flatpak/repo/ [output].flatpak [identifier]  stable`, but that requires you to be on a Linux machine that already has the flatpak application installed. Ie, I can't just download a FlatPak on my Mac and then transfer it to an offline linux machine—I need to install the app to an online linux machine, create an app bundle, and then transfer that bundle to my offline machine.

If anyone is aware of places distributing prebuilt, offline-installable flatpak bundles (including RetroArch), please point me there.

> There aren't many runtimes, so you won't normally need to copy over the runtime, often it'll be just the flatpak because your PC is likely to already have the appropriate flatpak runtime. Of course manually copying them is not as convenient as downloading them from the flatpak repos, but having a computer with no network never is.

You can also create offline installable versions of the runtimes with `flatpak build-bundle --runtime ~/.local/share/flatpak/repo/ [output].flatpak [runtime identifier] [runtime version]` Do that for each of the versions of each of the runtimes, and you'll be able to install any bundles offline.

**Comment by gouchi** [comment]
@hizzlekizzle I will have to continue to work on it as we are missing some files (cores, retroarch-assets, retroarch-autoconfig, retroarch-database, retroarch-info, retroarch-shaders).

**Comment by RobLoach** [comment]
[RetroArch on Flatpak](https://flathub.org/apps/details/org.libretro.RetroArch) ships the following modules...

- `retroarch`
- `retroarch-assets`
- `libretro-database`
- `libretro-core-info`
- `retroarch-joypad-autoconfig`
- `common-shaders`
- `slang-shaders`
- `glsl-shaders`
- [`retroarch-filters-video`](https://github.com/libretro/RetroArch/tree/master/gfx/video_filters)
- [`retroarch-filters-audio`](https://github.com/libretro/RetroArch/tree/master/libretro-common/audio/dsp_filters)

I'd consider the shaders and filters less critical, but the info files, databases and assets would be very nice to have shipped as part of the AppImage.

RetroArch will read config defaults in `$GLOBAL_CONFIG_DIR/retroarch.cfg`, which is handy to override its default paths. [flatpak/retroarch.cfg](https://github.com/flathub/org.libretro.RetroArch/blob/master/retroarch.cfg) shows how these are used to reference the Flatpak mounted locations. You've likely figured out something for the AppImage too :+1:

**Comment by hizzlekizzle** [comment]
This can be closed, as we now have a very nice AppImage.

**Comment by probonopd** [comment]
Indeed! :100: 

https://appimage.github.io/RetroArch/
