### ISSUE TITLE
Black background on quick menu

### ISSUE THREAD

**Issue by JuanVCS** [libretro/RetroArch#5072]
## Description

When entering the quick menu, my background image doesn't show, instead having a black background. On closing content the image is shown again.

### Expected behavior

Background image to be shown in all instances.

### Actual behavior

The quick menu has a plain black background.

### Steps to reproduce the bug

1. Have a background image set with full opacity (in my case dynamic backgrounds).
2. Load some content.
3. Enter the quick menu and notice the black background.
4. Close content to have the image back.

### Bisect Results

Started here https://github.com/libretro/RetroArch/commit/364440813fb64fc83e95033eb2ddfbfef5898f5c

### Version/Commit

Any version after the commit above.

### Environment information

- OS: Arch Linux x86_64
- Compiler: gcc (GCC) 7.1.1 20170528

**Comment by JuanVCS** [comment]
Similar to https://github.com/libretro/RetroArch/commit/57503051ea33c619a92d9f795708e710897a338b#commitcomment-22338305

**Comment by psyke83** [comment]
JuanVCS,

This was a pre-existing bug prior to my change, but only when menu_pause_libretro was set to false. I'll take a closer look soon to try and sort it out properly.

**Comment by psyke83** [comment]
Can you try this patch (against master)? https://gist.github.com/psyke83/645fde1b92a90bb99ff1fcf3555b4aed

It seems to solve the issue but needs more eyeballs to make sure nothing else is impacted negatively.

**Comment by JuanVCS** [comment]
It does indeed solve the issue.
