### ISSUE TITLE
RetroArch Lite

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5083]
## Description

Allow building a slimmed down version of RetroArch with just the essentials to run a core and its content.

### Expected behavior

Be able to disable the following features during compilation:

- [x] Menu
  - [x] `HAVE_MENU=0`
  - [x] `HAVE_MENU_COMMON=0`
  - [x] `HAVE_RGUI=0`
  - [x] `HAVE_MATERIALUI=0`
  - [x] `HAVE_NUKLEAR=0`
  - [x] `HAVE_ZARCH=0`
  - [x] `HAVE_XMB=0`
- [x] `HAVE_OVERLAY=0`
- [ ] `HAVE_NETWORKING=0`
  - [ ] `HAVE_NETLOGGER=0`
  - [ ] `HAVE_CHEEVOS=0`
  - [ ] `HAVE_NETWORKGAMEPAD=0`
  - [ ] `HAVE_MINIUPNPC=0`
  - [ ] `WANT_IFADDRS=0`
  - [ ] `HAVE_SOCKET_LEGACY=0`
- [ ] `HAVE_LANGEXTRA=0`
- [ ] `HAVE_LIBRETRODB=0`
- [ ] Add more support for disabling RA features!

```
make HAVE_LIBRETRODB=0 HAVE_MENU=0 HAVE_EMSCRIPTEN=0 HAVE_LAKKA=0 HAVE_RGUI=0 HAVE_NUKLEAR=0 HAVE_XMB=0 HAVE_MATERIALUI=0 HAVE_ZARCH=0 HAVE_MENU_COMMON=0 HAVE_OVERLAY=0 HAVE_NETLOGGER=0 HAVE_NETWORKING=0 HAVE_LANGEXTRA=0 HAVE_CHEEVOS=0 HAVE_NETWORKGAMEPAD=0 HAVE_MINIUPNPC=0 WANT_IFADDRS=0 HAVE_SOCKET_LEGACY=0
```

### Actual behavior

Some of the above tasks error out with a bunch of errors....

```
obj-unix/core_impl.o: In function `core_set_netplay_callbacks':
core_impl.c:189: undefined reference to `video_frame_net'
core_impl.c:190: undefined reference to `audio_sample_net'
core_impl.c:191: undefined reference to `audio_sample_batch_net'
core_impl.c:192: undefined reference to `input_state_net'
```

```
obj-unix/msg_hash.o: In function `menu_hash_get_help_enum':
msg_hash.c:73: undefined reference to `menu_hash_get_help_vn_enum'
msg_hash.c:67: undefined reference to `menu_hash_get_help_jp_enum'
msg_hash.c:40: undefined reference to `menu_hash_get_help_fr_enum'
```

### Steps to reproduce the bug

1. Run the above `make`
2. See the errors occure.

### Bisect Results

None.

**Comment by RobLoach** [comment]
Fixed one of the input compilation issues over at https://github.com/libretro/RetroArch/pull/5082 .

**Comment by meepingsnesroms** [comment]
This will be great for my leftover android phones from 7 years ago, I could install RetroArch on all of them and use them as handheld SNESes for people to play with.

**Comment by meleu** [comment]
Hey @RobLoach is there a list with the available flags I can use to build a custom lite version? I'm noticing that RetroArch is starting to be a little laggy on my raspi1...

**Comment by RobLoach** [comment]
```
./configure --disable-cheevos --disable-langextra --disable-libretrodb --disable-materialui --disable-networking --disable-nuklear --disable-update_assets --disable-xmb --disable-ffmpeg
make HAVE_MENU=0
```
