### ISSUE TITLE
Interesting idea shamelessly stolen: create a reverse game option

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5089]
The idea is to mirror horizontally outputs (image and stereo sound) and inputs (controller or mouse... microphone is always non directional... i think, there might be some strange games on the DS).

Pretty funky right? Would allow some novelty to old favorites. And since RA abstracts all of these, it's a somewhat unique opportunity to do it without duplication everywhere.

A Y flip is also possible but wouldn't look good at all in most games in most times (GUI comes to mind), while a X flip is always 'logical' except - unfortunately - text and directions. Still, it might be just as fun to exercise our inner Leonardo/Zatanna as exploring reversed maps.

**Comment by hizzlekizzle** [comment]
Heh, that's a weird idea, but I'm not against it.

**Comment by i30817** [comment]
Reverse or mirror are better names and i'm OCD.

**Comment by i30817** [comment]
Well, one of the reasons it 'needs' to be a option and not just a shader dumped into the shader dir for the adventurous is to not interfere with the actual Retroarch gui.

**Comment by hizzlekizzle** [comment]
>Another is that to be complete, it kind of needs stereo channel reversing

This is pretty easy to accomplish, as well! If you go to your RetroArch directory (assuming Windows) and go to filters/audio and open Panning.dsp in a text editor, you can comment lines 7 and 8 and uncomment lines 17 and 18.

Fire up RetroArch and go to settings > audio > audio dsp plugin and then select the modified Panning.dsp. Viola, swapped L and R channels. :)

>But yes, i expect ingame text instantly turns into nonsense, for a while at least.

It's not the text that's throwing me, really, it's a combination of reversed expectations and misleading muscle memory.

**Comment by i30817** [comment]
So no chance of this appearing as a standard option?

**Comment by hizzlekizzle** [comment]
I don't think as a standard option, no. It's a neat idea but I think it's a bit niche. Anyone who wants to do it can do the steps I mentioned, but it's not something I foresee enough demand for it to be a one-click option.
