### ISSUE TITLE
[Segfault] doing Settings > Saving on arch

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#5091]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

segfault when doing Settings -> Saving

### Expected behavior

[What you expected to happen]

### Actual behavior

Segfaults when doing steps below. but if you run retroarch in "sudo" mode, it should work.

### Steps to reproduce the bug

1. launch RA
2. goto Settings 
3. choose Saving and it should segfault/

### Bisect Results

https://pastebin.com/SD2MBXBL

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Antergos Arch - Linux 4.11
- Compiler: gcc version 7.1.1 20170516 (GCC)

**Comment by bparker06** [comment]
I cannot reproduce this on the latest commit. Can you retry and report back?

**Comment by retro-wertz** [comment]
no, still the same here. if Show Advanced Settings is OFF, Saving menu does not crash..

if Show Advanced Settings is ON, Saving crashes

**Comment by Awakened0** [comment]
This happens for me in Windows if Show Advanced Settings is enabled. It doesn't happen with the debug exe, curiously.

**Comment by fr500** [comment]
Hmmm, I can't find MENU_ENUM_LABEL_SAVESTATE_THUMBNAIL_ENABLE in msg_hash_lbl.h
