### ISSUE TITLE
Saving with multidisc PBPs in Beetle-PSX HD "ejects" discs forever

### ISSUE THREAD

**Issue by Derducken** [libretro/RetroArch#5094]
I really hope this is not a "core problem" and I am, indeed, reporting on a bug for RA itself. So...

While playing Metal Gear Solid on the Beetle-PSX core, from a PBP file where both the games discs are included in the same file, if you make a savestate with the first disc loaded everything works ok. If you open the tray, swap discs and close it, THEN create a savestate, when you later re-load it, there are no discs in the disc index. None. The only solution is to go swap, manually, to the first disc, create a savestate and then swap back to the second disc.

This could be a core problem, but since it appears while using the "disc swapping with hotkeys" method in RA's interface, I don't know who's the culprit. Sorry if it's not a problem with RA.

PS: This happened using the nightly from 5-6 days ago. I don't have access to the computer where it happened, but if you can't replicate the problem I can give more details at a later time.

**Comment by orbea** [comment]
I asked on irc for you and this is a core problem and that chd files should work correctly.

Can you please test the latest beetle-psx builds and if its still a problem can you make a core issue report?

https://github.com/libretro/beetle-psx-libretro/issues

Thanks!
