### ISSUE TITLE
Enter key not working with 1.6.1

### ISSUE THREAD

**Issue by ApostolosB** [libretro/RetroArch#5096]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Hitting Enter key doesn't work. Ie. you select load core with the arrows and hitting enter doesn't get you in the menu

### Expected behavior

To enter the menu you have selected with the arrows

### Actual behavior

Nothing Happens

### Steps to reproduce the bug

Update to 1.6.1
Start retroarch 
Select something with the arrows and hit enter

### Bisect Results

Works on 1.6.0 doesn't on 1.6.1

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.1

### Environment information

- OS: Arch linux, wayland,
- Compiler: Whatever Arch uses. The package is from the repos.

**Comment by RobLoach** [comment]
What input driver are you on?

**Comment by ApostolosB** [comment]
How can i check?

**Comment by RobLoach** [comment]
Have a look at your retroarch.cfg. Should be `input_driver`.

**Comment by ApostolosB** [comment]
udev

**Comment by RobLoach** [comment]
There's been some discussion on udev over at https://github.com/libretro/RetroArch/issues/5033 , along with some other channels. A workaround for now is to change it from udev to `x`.

**Comment by twinaphex** [comment]
I had to revert a PR in order to get the enter key to work again. Hopefully the guy who submitted the PR can send us an improved PR which can still retain usage of the enter key.

**Comment by ApostolosB** [comment]
Changing it to X probably won't cut it cause i am on wayland. Anyway. Since twinaphex found the problem its just a matter of waiting for 1.6.2 or whatever release fixes the problem.

**Comment by maxlefou** [comment]
Same problem. Arch based (Manjaro), GNOME with Wayland. Used to work perfectly on 1.5.0 ans 1.6.0. 

Though, this problem doesn't only affect the Enter key. ALL the keys of the keyboard are affected. So, i can't use savestates or even access RetroArch's menu.

@RobLoach 's trick of using `x` instead of `udev` for `input_driver` in `retroarch.cfg` fixed it though. Thanks for the trick.

**Comment by chungy** [comment]
Similar, GNOME with X.Org this time though. No input without `x` instead of `udev`

**Comment by RobLoach** [comment]
This should be fixed.

**Comment by ApostolosB** [comment]
yes
