### ISSUE TITLE
No command line output in Windows 10 console

### ISSUE THREAD

**Issue by anetanel** [libretro/RetroArch#5097]
Commands such as '--help' and '--features' does not show on the Windows 10 console.

Steps to reproduce:
1. Start a windows console (cmd.exe)
2. run retroarch.exe --help

Version: Retroarch x64 -1.5, 1.6 and latest (22/6) nightly.
OS: Window 10 Pro 64-bit

Changing the console settings to legacy did not help.
Running an elevated command line did not help.
A powershell console exhibits the same behavior.

Oddly enough, when running from a windows bash console (I use it for git) it outputs fine.

![r1](https://user-images.githubusercontent.com/13014516/27473047-5586a640-5806-11e7-8819-c6ba021f18e5.png)

**Comment by orbea** [comment]
Is this still an issue?
This issue report was similar. https://github.com/libretro/RetroArch/issues/4577

**Comment by fr500** [comment]
Yup, by the time we allocate a console it's too late..

**Comment by anetanel** [comment]
As a workaround, I found that redirecting the output to file, or to another command works.
So you can do something like "retroarch.exe --help | more", to get the text displayed, or "retroarch.exe --help > file.txt" to have the output in a file (named file.txt).

**Comment by LibretroAdmin** [comment]
Seems to work fine here.
