### ISSUE TITLE
Core Updater downloads wrong version on RaspberryPi3

### ISSUE THREAD

**Issue by utdrmac** [libretro/RetroArch#5098]
## Description
Running RetroArch 1.5.0 on RaspberryPi3. Navigate to Online Updater -> Core Updater -> Arcade (MAME). Resulting download is wrong binary class. 

Error message in debug log:

    RetroArch [ERROR] :: Error(s): /storage/.kodi/addons/script.gamestarter/resources/bin/libretro-cores/mame_libretro.so: wrong ELF class: ELFCLASS64

### Expected behavior

I expected the proper ELF class to be downloaded for my hardware.

### Actual behavior

The wrong ELF class is being downloaded

### Steps to reproduce the bug

See description

### Bisect Results

First time user. Just installed RetroArch not 1 hour ago.

### Version/Commit

Build date: Mar 10 2017

- RetroArch: 51581e1

### Environment information

- OS: LibreELEC8 / RaspberryPi3
- Compiler: N/A

**Comment by fr500** [comment]
if other cores work then it means that core didn't build properly.

**Comment by utdrmac** [comment]
@fr500 Is that something I have to fix? or is this an issue with your CI/commit-build process?

I didn't do anything custom for this. I simply installed LibreELEC, then Gamestarter Add-On (which launches RetroArch), Online Updater -> Download several cores for the ROMS I have. This is indeed the only one showing an issue like this.

**Comment by r-type** [comment]
Seem it's a build for X64 instead ARM32.
does the one provide here works on pi ?
http://buildbot.libretro.com/nightly/linux/armhf/latest/

**Comment by orbea** [comment]
@utdrmac Is this still an issue?

**Comment by utdrmac** [comment]
Dono. Haven't played RetroArch in a long time. Will close if I ever have time to play again :D

**Comment by SuperFromND** [comment]
I can confirm that this issue is still present; tried to download `mame_libretro.so` from the menu on a Raspberry Pi 3, and it ended up reporting a `wrong ELF class: ELFCLASS64`.  The mame_libretro.so file provided by [the link r-type posted](http://buildbot.libretro.com/nightly/linux/armhf/latest/mame_libretro.so.zip) does not work on the Pi either; it also reports a `wrong ELF class: ELFCLASS64`.

**Comment by orbea** [comment]
@SuperFromND I think this is either a buildbot or core issue and it should be taken up in one of those repos instead.

https://github.com/libretro/mame
https://github.com/libretro/libretro-super
