### ISSUE TITLE
Incorrect mapper detected for "StarTropics" and "Zoda's Revenge: StarTropics II"

### ISSUE THREAD

**Issue by anderbubble** [libretro/RetroArch#5101]
## Description

Incorrect mapper detected for "StarTropics" and "Zoda's Revenge: StarTropics II". See https://github.com/rdanbrook/nestopia/issues/144. I suspect (though I'm not a libretro developer, so I could be wrong) that retroarch does its own mapper detection outside the core and is misdetecting the StarTropics mappers as MMC3 in stead of MMC6B.

### Expected behavior

Sound in StarTropics games, ability to register name and play the game.

### Actual behavior

No sound, unable to register name. (Name is entered, but does not display on resultant list of registered names for selection.)

### Steps to reproduce the bug

1. Start RetroArch 1.6.0 for Windows x86_64
2. Download / update any NES core (tested with Nestopia UE, bnes, FCEUmm)
3. Load any StarTropics rom
4. Attempt to register name

### Version/Commit

- RetroArch: 1.6.0 (updated from 1.5.0, which was also exhibiting this behavior)

### Environment information

- OS: Windows 10 x86_64
- ROM CRCs:
  - StarTropics (USA).nes (889129CB)
  - Zoda's Revenge - StarTropics II (USA).nes (D054FFB0)

Headers verified with [inestool](https://github.com/dsedivec/inestool)

**Comment by retro-wertz** [comment]
both games run fine. Select to move cursor, Start to select option.

also this is not a retroarch issue.


​

**Comment by hizzlekizzle** [comment]
Yeah, I worked with him some last night. He needed NstDatabase.xml for Nestopia. FCEUmm worked on its own.

closing.

**Comment by anderbubble** [comment]
As discovered via irc, nestopia wasn't working because I was missing
NsDatabase.xml, bnes wasn't working because "our bnes is really old" and
apparently I was wrong about having verified the same behavior with fceumm,
as I can now see it work with that or with or without the DB.

Sorry for the spam.

**Comment by numbskill** [comment]
Actually, I’m having this exact same problem and I can’t find any documentation on how to fix this. Both cores have the same issue with not being able to register a name after selecting END and pushing start. It just returns to the first selection screen with nothing registered. I updated databases through retroarch and also tried to find Nsdatabase.xml to manually update but only found NstDatabase.xml ¿is that the same thing?

**Comment by retro-wertz** [comment]
i dont know how thats a problem in your end. the game registers name fine
and able to start, at least for FCEUmm.

and this is a core-related issue and should not be here...
