### ISSUE TITLE
[Feature Request] [CrocoDS] Add option to change keyboard layout on emulator settings

### ISSUE THREAD

**Issue by WedgeSparda** [libretro/RetroArch#5108]
Hi, following the suggestion [here](https://forums.libretro.com/t/crocods-keyboard-layout-issue-with-amstrad-cpc-games/10828), I would like to ask for an option on the emulator settings for CrocoDS to change the keyboard layout without recompiling the core after changing the config file.

Is it something that can be done?

Thanks

**Comment by hizzlekizzle** [comment]
Sorry, I should have been more clear. This request needs to be made at the core's repo, where the author (r-type, I think?) will see it:
https://github.com/libretro/libretro-crocods

**Comment by r-type** [comment]
it's redbug26 for this core ( i'm only on cap32 for cpc stuff)
