### ISSUE TITLE
(Win64) Trying to load a game with Mupen64Plus after switching configs crashes RetroArch

### ISSUE THREAD

**Issue by GPDP2** [libretro/RetroArch#511]
This is another weird issue with configurations. Basically, if you are using the default retroarch.cfg and load any core and any game, there appears to be no issue. Everything works as it should, including the Mupen64Plus core. Upon enabling core-specific configs, I now have a couple of them, including one for Mupen64Plus. However, if I switch from retroarch.cfg to the newly created mupen64plus_libretro.dll.cfg, and then try to load an N64 game, RetroArch crashes. This does not appear to happen with any other core.

This appears to be a recent issue, as I did not have this problem with the builds I was using around a month ago. However, more recent builds cause this crash for some reason. The error log gives me nothing.

**Comment by lzugabriel** [comment]
hey i have the same issue, but when i paste the content of the  Config Folder inside the  Roaming folder and launch Retroarch it doesn't work :/

**Comment by fr500** [comment]
What roaming folder? we've never had this as far as I know, it has always looked in working dir for configuration files for me
