### ISSUE TITLE
Missing no-intro ROM in scan

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5111]
I noticed this on the wonderswan color scan, which i have a small dir with 3 translated games (just to be clear, these are softpatches, not hardpatches, and their crc exists on the database and the files were not changed in anyway).
Dicing Knight. (Japan)/Dicing Knight. (Japan).wsc
Makai Toushi Sa-Ga (Japan)/Makai Toushi Sa-Ga (Japan).wsc
Mr. Driller (Japan)/Mr. Driller (Japan).wsc

Only Makai Toushi Sa-Ga is shown. I suspect this is because of the extra '.' either in the names, or in the parent dir. The database has the correct name and CRC, of for example Mr. Driller, but it still won't show.

'.' is a valid character both in path and filenames, so if something is going wrong here many other ROMs aren't being picked up. 

database mr.driller data:
{"serial": "53574A2D4E4D43433031", "sha1": "209232F1E91C05140529D466C0EF6B7AD3386DE1", "md5": "9D600BFE28196609FBE4FB5B89486CBC", "crc": "5555D95C", "publisher": "Namco", "developer": "Namco", "franchise": "Mr. Driller", "releaseyear": 2001, "releasemonth": 4, "size": 2097152, "rom_name": "Mr. Driller (Japan).wsc", "description": "Mr. Driller (Japan)", "name": "Mr. Driller (Japan)"}

Bandai - WonderSwan Color.lpl contents after scan (only one game so the error is doing scan, not playlist reading):
/media/i30817/backup/Documents/Games/Bandai WonderSwan Color/Makai Toushi Sa-Ga (Japan)/Makai Toushi Sa-Ga (Japan).wsc
Makai Toushi Sa-Ga (Japan)
DETECT
DETECT
1B6F5F30|crc
Bandai - WonderSwan Color.lpl

**Comment by RobLoach** [comment]
Mind moving this to https://github.com/libretro/libretro-database ?

Translated or modded roms are not in the DAT. Feel free to submit a PR to libretro-database, or move the issue over. Thanks!

**Comment by i30817** [comment]
Ah but these are softpatches, sorry if it wasn't immediately obvious. And when you say 'mind moving' is it for me to open a new report with this content there or for a admin to move the bug ?

**Comment by i30817** [comment]
I'm opening a new bug with the same content there and will leave it to admins to close the 'wrong one' then.

**Comment by RobLoach** [comment]
Thanks! :+1:

**Comment by i30817** [comment]
I'm pretty sure this is a defect in the scanner not on the database now. If you read the other bug, i've noticed that this bug happens if:

1. you have a dot '.' in a dir name that is in the 'downstream' path of a filesystem tree to be scanned. The dot doesn't interfere if the file browser enders the dir with a dot (if the dotted dir is a ancestor). But it will prune the scan if it's a successor.


As such a workaround is to enter all the way down to where the rom you want to scan is and scan there. If you do this, the rom is added to the playlist with correct paths.

So this makes me think the directory recusion/visitor on the scanning is screwing up.

**Comment by bparker06** [comment]
@i30817 When you experience this issue, do you have the "show hidden files" setting turned on in Load Content -> Settings?

**Comment by i30817** [comment]
Doesn't appear to matter. Can't you test it? It's fairly easy to reproduce.
