### ISSUE TITLE
Virtual Jaguar has aspect ratio problems

### ISSUE THREAD

**Issue by firewater2** [libretro/RetroArch#5116]
Happens with various games. Could be a problem with the original emulator, but I'm not sure.

![retroarch-0627-010415](https://user-images.githubusercontent.com/11010067/27571626-fd29f78c-5ad4-11e7-9084-e045c99668e9.png)

**Comment by hizzlekizzle** [comment]
Yeah, if you can reproduce it in standalone, there may not be any reasonable way for us to fix it. If it's only in the libretro-ized version, we should be able to track it down more easily.

**Comment by firewater2** [comment]
I'll close it for now because this Doom copy actually crashes standalone virtual jaguar and I don't know the name of the other games with the issue to try them out. I'm supposing there are more because I read about someone complaining about this happening on RA and not standalone some days ago.

**Comment by hizzlekizzle** [comment]
ok, sounds good. Feel free to reopen it if you happen upon any of the others and can't reproduce it in standalone.

**Comment by r-type** [comment]
You have to enable doom res hack option in core option.

**Comment by firewater2** [comment]
Oh wow, I didn't know about that, thanks!
