### ISSUE TITLE
Retroarch consistently 'Not Responding' every 10 seconds

### ISSUE THREAD

**Issue by Rangdazzlah** [libretro/RetroArch#5118]
## Description

Retroarch consistently 'Not Responding' every 10 seconds

[Log File.zip](https://github.com/libretro/RetroArch/files/1106267/Log.File.zip)

Apologies for long log file, new to this process

### Expected behavior

I cannot navigate the menu

### Actual behavior

Program freezes for 15-20 seconds every 10 seconds

### Steps to reproduce the bug

1. Start the program
2. Freeze
3. Wait it out
4. Use retroarch menu for 10 seconds
5. Repeat step 2-4

### Version/Commit
Version 1.4.1 - 1.6.0

### Environment information

- OS: Windows 10 64
- i7 7700k
- MSI GTX 1080
- 144hz Monitor

**Comment by meepingsnesroms** [comment]
Can you upload your retroarch.cfg file?
It could be your video driver settings.

**Comment by Rangdazzlah** [comment]
[retroarch.zip](https://github.com/libretro/RetroArch/files/1106585/retroarch.zip)

**Comment by RobLoach** [comment]
If you resize your window, does it refresh the video?

**Comment by Rangdazzlah** [comment]
The issue seems to have resolved itself.
