### ISSUE TITLE
[Feature Request] Hotkey for Clearing Save State Slot

### ISSUE THREAD

**Issue by capeman29** [libretro/RetroArch#5119]
Currently, the retroarch save state function offers the following options for hotkeys:
```
input_save_state =
input_load_state =
input_state_slot_increase =
input_state_slot_decrease =
```

I would like to request the addition of the following function:
```
input_clear_state =
```

This function would erase the .state file for the selected slot. The reasoning is to make it easier to manually avoid the conflicts that can happen when using emulator save states in conjunction with games that use battery saves. 

Example: You use a save state to beat a boss in an RPG, then you continue playing the game using the battery save. A few days, and multiple hours of progress later, you mistakenly hit the 'load state' hot key, loading the state before the boss, and suddenly hours of progress is lost (we've all done this at least once). 

Users like me, currently go into the roms folder and delete states manually to avoid these conflicts when we feel the need to cheat, but making the function as easy as a hotkey would make it much easier to continue a battery saved game without risk or worry about rogue save states ruining your game.

Of course this would be off by default, but the option to enable it would be a welcome addition.

And as aways, I appreciate the effort the retroarch team has put into this project, it's amazing!

**Comment by fr500** [comment]
Enable the "Don't overwrite SRAM on load state" option.

**Comment by capeman29** [comment]
Thanks for mentioning that, I'm aware if that function, but I've had it cause bugs in games that auto save srm data like Kirby's adventure and F-zero. Having the option to manually delete by hotkey would be convenient for players who like to have a bit more control.

**Comment by fr500** [comment]
Savestate management might be nice but I think a hotkey is the wrong approach here.
BTW you can undo load states now.

**Comment by hizzlekizzle** [comment]
Based on being able to undo load states, I think we can close this, either for being solved or "wontfix", depending on one's perspective.
