### ISSUE TITLE
Linux: Keyboard non-responsive with udev input driver (Regression)

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#5120]
## Description

When using the `udev` input driver the keyboard is non-responsive. The gamepad will still work correctly with `udev` joypad driver as does the keyboard work with the `linuxraw` input driver.

### Expected behavior

The keyboard should work with the `udev` input driver.

### Actual behavior

The keyboard is non-responsive with the `udev` input driver.

### Steps to reproduce the bug

1. Start RetroArch.
2. Select the `udev` input driver and restart if needed.
3. Test the keyboard in the menu.

### Bisect Results

```
2056ebc80378fabf1f96883de3c7c930c809d101 is the first bad commit
commit 2056ebc80378fabf1f96883de3c7c930c809d101
Author: Zoran Vuckovic <casdevel@gmail.com>
Date:   Fri Jun 2 01:08:28 2017 +0200

    Allow udev input to be used with X11 context

:040000 040000 73351e8a90dbd19dc573b1ae9e57304fda761f98 162cbac6462954d191373fbf0ba14ad0456cb1d8 M	gfx
```
2056ebc80378fabf1f96883de3c7c930c809d101

### Version/Commit

- `RetroArch-2017.06.27_ba71dda1b_master-x86_64-1_git`
- `eudev-3.2.2-x86_64-2`

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-7.1.0`

**Comment by orbea** [comment]
@casdevel Can you take a look at this?

**Comment by orbea** [comment]
The log prints this.
```
RetroArch [WARN] :: [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?
```
Related issues.
https://github.com/libretro/RetroArch/issues/5033
https://github.com/libretro/RetroArch/issues/5096

**Comment by retro-wertz** [comment]
this has been discussed again and again, and said(somehow) this was suppose
to be how udev behaves with keyboard input, regardless if your the host
system(or something) not sure of the technicals about that but there should
be posted issues similar to this.. mine was ps2 keyboard not working with
udev.

**Comment by orbea** [comment]
Yea, I have been reading the past discussions.

I created `/etc/udev/rules.d/99-evdev.rules`:
```
KERNEL=="event*", NAME="input/%k", MODE="666"
```
Now everything, except the enter button works correctly. The enter button remains non-responsive...

**Comment by orbea** [comment]
I applied the following commit as a patch to `RetroArch-1.6.1` and now the `enter` key works again.
https://github.com/libretro/RetroArch/commit/5c5c5ecbdfb05f78215ca6d4666b9ca20bd07805

**Comment by orbea** [comment]
Instead of the udev rule, I can better solve the problem by adding my user to the input group.
