### ISSUE TITLE
DS4: PS Button won't map & how to accept multiple keybinds

### ISSUE THREAD

**Issue by firewater2** [libretro/RetroArch#5128]
These are two problems, more or less related to the same thing:

1. The PS button on my DS4 won't be detected when trying to map it - is this normal behaviour? Maybe I could force it by writing it directly on the retroarch.cfg file, but I don't know how it's called.

2. Can I map multiple inputs to do one action? For example: R1 + L1 = take a screenshot.

**Comment by pralima87** [comment]
I use DS4Windows that allow me to really unlock the power of the DS4 ;)
https://github.com/Ryochan7/DS4Windows is the lastest and most improved version

**Comment by firewater2** [comment]
I do too! I use it for most PC games, but I'm not sure how to implement it with RA for the things I mentioned above.

**Comment by pralima87** [comment]
In Retroarch go to the inputs menu and hotkeys.
Set the hotkeys to any keyboard key.

Them in the DS4Windows you can create a profile and 
Assign the same keyboard keys to customs commands/macros/modifiers as you see fit.
There is even the special actions like double tap/hold that works really well.

**Comment by fr500** [comment]
There is a hotkey modifier too, as long as modifier is pressed you can have secondary actions for all buttons. I use that with my DS3, modifier is the PS button and I do all kinds of actions with my pad

**Comment by firewater2** [comment]
Thanks guys. Where is that hotkey modifier located? On DS4Windows, you mean? I wonder both for this instance, and for the future were I plan to move on to macOS, were DS4Windows is not a thing and therefore I believe there'd be no way to do this.

**Comment by fr500** [comment]
This is really not a retroarch issue and would be better served on the forum.
Using the official adapter on windows the button maps just as any other button, and using DS4windows in xinput mode it just works.

This is a developer oriented site, not a support forum.
https://forums.libretro.com/

**Comment by firewater2** [comment]
Isn't it considered a request then? As I understand, you're saying there's no way to do this -which is quite an important option to have- without relying on external software, yeah?
