### ISSUE TITLE
[Feature Request] Delete Core action item in Core Information menu

### ISSUE THREAD

**Issue by FineWolf** [libretro/RetroArch#5132]
On Android, there is currently no way to remove a downloaded core without clearing the application data if your device is not rooted. This can be a source of frustration if you have to reconfigure everything every single time an unwanted core is installed. Since you cannot change the cores path to be outside the /data folder (due to Android's sandboxing), it really is the only option left to the user.

Adding a simple option in the Core Information menu would allow a user to easily remove an unwanted core.

**Comment by hizzlekizzle** [comment]
Yes, I agree that this is something we need. We've talked about it literally for years, it's just never been tackled. It's probably a good candidate for a bounty.

**Comment by FineWolf** [comment]
I've already put 15$ on the issue over at BountySource.

**Comment by dorkster** [comment]
@FineWolf Hopefully, [my commit](https://github.com/dorkster/RetroArch/commit/150bc81ee179d18c7acc40f29dfdcda82ab6d264) does the trick. I only tested on desktop Linux, but it should technically work the same on Android.

**Comment by dorkster** [comment]
Version 1.6.4, which includes the fix for this, is on the Play Store now. I've tested it on my phone and everything works as intended. This issue can be closed now.

**Comment by FineWolf** [comment]
Closing this issue then. It has been merged!

**Comment by chasetec** [comment]
Adding a comment for anyone else having trouble figuring out how to remove a core on 1.6.4 or higher (tested on 1.7.5).

Load the core you want to delete, go to the home menu, Information, Core Information, and scroll to the bottom to find the Delete core option.
