### ISSUE TITLE
support for multiple mice in linux via the udev input driver

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#5135]
This issue started in [the Multiple Mice issue/bounty.](https://github.com/libretro/RetroArch/issues/4775)

@casdevel requested that a new issue be opened dealing with the specifics of the udev input driver. @mediamoshpit has been testing the udev implementation on a RetroPie installation where it doesn't seem to be working.

mediamoshpit's log file is below:
https://pastebin.com/nvFZ2xNA

**Comment by casdevel** [comment]
@mediamoshpit set user 2 mouse index to 2 and try some MAME 2003 game. Let me know if that make a difference.

**Comment by retro-wertz** [comment]
only on udev?

**Comment by mediamoshpit** [comment]
It had been suggested that I also test with raw, but the results were the same. I plan on testing the above suggestion as early as this evening.

**Comment by telanus** [comment]
Hi

Was asked to report here

I tried this evening with 2 mice on Ubuntu Mate 16.04. 

Original report: 

>  First tried just as is, and RA crashes when I press 2 (for a 2-player game), then tried and made ubuntu setup both as mice separately, and didn't get a crash, but pressing the second mouse button (on the calibration screen) pauses the emulation

tried @casdevel's idea of setting user 2 mouse to index 2 and still no joy.

Log file: https://pastebin.com/MDAkqJSQ 
attached my cfg file
[retroarch.cfg.zip](https://github.com/libretro/RetroArch/files/1125815/retroarch.cfg.zip)

**Comment by casdevel** [comment]
@telanus You are using x input driver. Multiple mice support is available with udev input driver only (and raw input driver on Windows). Before changing input driver to udev visit [https://github.com/libretro/RetroArch/wiki/Input-drivers-in-Linux-without-Xorg](https://github.com/libretro/RetroArch/wiki/Input-drivers-in-Linux-without-Xorg).

**Comment by telanus** [comment]
@casdevel did what the wiki said and still won't work :(

https://pastebin.com/BwppvadV < current log

**Comment by casdevel** [comment]
Log looks OK, mice should be at index 0 and 1. Maybe there are some issues with Terminator 2 game.
Can you try Area 51 game?

**Comment by mediamoshpit** [comment]
I've tried 'Area 51' before and it's a bit more than the Pi3 can handle running with the RetroArch overhead. However, I'll see if I can't at least get it into a gun calibration mode. Aside from 'Terminator 2', I have also tested the multiple mice option with 'Revolution X' and the results were the same.

**Comment by telanus** [comment]
I got it to work with Jurrasic Park, Alien3: The Gun & Point Blank (but it suffers from disjointed aiming system, where the aim and the location of the shot is two different place)

**Comment by mediamoshpit** [comment]
While still slow, 'Area 51' ran well enough to test, but it gave the same results. I can get the two mice to react independently, but they never work together. It's likely to read the same, but my verbose log for this test is linked below.

https://pastebin.com/SSUzGVMY

**Comment by mediamoshpit** [comment]
I hadn't rebuilt Retroarch or Mame2003 since I last tested all this, so I decided to rebuild from the latest nightlies and all is working well now. 'Terminator 2', 'Revolution X' and 'Area 51' all recognize both mice at the same time.

**Comment by markwkidd** [comment]
@telanus can you make sure you have the latest nightly of RetroArch and the latest buildbot core for MAME 2003? I ask because of @mediamoshpit 's update: https://github.com/libretro/RetroArch/issues/5135#issuecomment-313565069

**Comment by casdevel** [comment]
@telanus try swapping "P1 Button 1" and "P2 Button 1" mapping in MAME2003 settings.

**Comment by telanus** [comment]
@mediamoshpit I'm on Ubuntu (and on a desktop)

@casdevel tried that and aiming is still horrible on pblank, the other are fine

**Comment by casdevel** [comment]
@telanus on my machine Alien 3 works fine with multiple mice. If on your machine other games work fine with multiple mice then this isn't input driver issue.
