### ISSUE TITLE
Issue with scanned PS1 .bins/cues being added to the playlist.

### ISSUE THREAD

**Issue by MitsuriZX** [libretro/RetroArch#5137]
I would like to report an issue about PS1 .bins/cues and the scan feature.

>Description

I have some PS1 .bins/cues that I wish to use with Retroarch, so I proceed to scan the folder that contains them so that they will be added to a playlist for ease of use.

>Expected behavior

I expected the games to be added to the PS1 playlist after the scan.

>Actual behavior

It seems for a moment that Retroarch is scanning the .bins/cues without problems, as each .bin/cue takes a while to be scanned, which is normal considering the size of the files, but after the scanning finishes, none of the games are added to the PS1 playlist.

>Steps to reproduce the bug

1. Open Retroarch.exe.
2. Go to Import Content tab.
3. Select Scan Directory.
4. Go to where the .bin/cues are located.
5. Select Scan This Directory.

>Bisect Results

This is an issue that is present only in version 1.6.0 from what I have seen, as in all previous versions of Retroarch in which I have tried to do so (1.3.2, 1.3.4, 1.4.0, 1.5.0), the .bins/cues were scanned successfully and added to a playlist for PS1 titles as playable games. Generating the playlist in previous versions and then moving the playlist from it to 1.6.0 is working for me as a temporary solution.

>Version/Commit

My Retroarch is:
Version 1.6.0
Build Date: Jun 1 2017
Git version: a4358de

>Environment information

Operational System: Windows 10 Pro 64-bit
CPU is AMD FX 8100 Eight-Core Processor 8 GB of RAM.

Thanks in advance.

**Comment by retro-wertz** [comment]
update RA

**Comment by MitsuriZX** [comment]
Is Retroarch 1.6.0 not already the latest stable version? Should I get a Nightly?
