### ISSUE TITLE
(Suggestion) Could carry these emulators rpcs3 (ps3) and xenia (xbox 360) ...

### ISSUE THREAD

**Issue by killer983** [libretro/RetroArch#5142]
Could carry these emulators:
Rpcs3 (ps3): this is pretty advanced and already runs quite a few games
Here the link: https://github.com/RPCS3/rpcs3
Xenia (xbox 360): Allows to run some games
Here the link: https://github.com/benvanik/xenia
Rpcx2 (ps2): Runs most games
Here the link: http://pcsx2.net/download/releases/source-code/summary/6-source/121-pcsx2-1-4-0-source.html
Xqemu (xbox): Should run most games
Here the link: https://github.com/espes/xqemu
Decaf-emu (wii u): Some games are still under development
Here the link: https://github.com/decaf-emu/decaf-emu

**Comment by fr500** [comment]
This is about RetroArch, not a request board. Closing.
