### ISSUE TITLE
OSX: "User x bind all" screen broken 

### ISSUE THREAD

**Issue by frranck** [libretro/RetroArch#5143]
## Description

"User x bind all" screen broken on OS X. 

### Actual behavior

When I try "User x bind all" them I get this unreadable screen:

https://pasteboard.co/Gz4mOPA.png

### Steps to reproduce the bug

As explained in https://github.com/libretro/RetroArch/issues/3415
1. select "input"
2. select "Input user 1 Binds"
3. select "user 1 bind all"

### Version/Commit

- RetroArch: current master

### Environment information

- OS: El Captain.

**Comment by orbea** [comment]
@frranck Is this still an issue?

**Comment by frranck** [comment]
@orbea No, it's readable and seems to work now. 👍
