### ISSUE TITLE
RetroArch and lakka crash with same error 

### ISSUE THREAD

**Issue by ravarage** [libretro/RetroArch#5159]
## Description
when I try to play PS1 games on my laptop When I load the content and the retroarch and lakka both disappear without any error message I try all three cores of ps1 same result ,however I test with same setting on my gaming rig it work just fine

sony vaio VPCEB series 
i5 M460
4 gb ddr3 10600 
intel hd graghic (i5 m460)

### Expected behavior

load sony logo sound and start playing

### Actual behavior

exit like nothing were open

### Steps to reproduce the bug

load the core load the content and crashes

### Bisect Results

out of the box

### Version/Commit
1.60 , 1.50 and latest nightlies with both x86 and x64

- RetroArch: [version/commit]

### Environment information

- OS: Windows 7 64 bit home premium , lakka no os need 
- Compiler: stable and latest nightly with installer

**Comment by cudencuden** [comment]
http://www.lakka.tv/doc/BIOSes/  ?

**Comment by ravarage** [comment]
No as I said I play on other device just fine but one thing I change video driver to gdi it play the game but the menu background become blank and weird color but it does play the game , its hardware issue I can play games now but just weirf color on xmb

**Comment by orbea** [comment]
@ravarage Is this still an issue with the nightlies?
