### ISSUE TITLE
Don't put stuff in inaccessible private app folders on Android

### ISSUE THREAD

**Issue by milesrotaru** [libretro/RetroArch#5165]
You're fucked if you install a core you don't want anymore, or save a per-game shader preset you didn't mean to. Same goes for cursors, overlays, filters, etc. It's impossible to remove any of that without completely wiping the app's storage. Setting a custom folder doesn't seem to work for some things such as the core folder. It gets reverted at next startup.

**Comment by fr500** [comment]
Please use the search function.
Cores can't be installed anywhere else because android doesn't allow loading dylibs from anywhere else.

The rest can be changed just fine from the settings/directories menu.

**Comment by milesrotaru** [comment]
I made this a separate issue because the other ones I could find only asked to be able to delete cores. I submit that plenty of other things need to be user accessible by default in addition to the cores, and

**Comment by milesrotaru** [comment]
To be more specific, it was the shader folder that frustrated me enough to submit this issue. I had to scrap my setup after realizing that my shader presets were locked away in there permanently. So after making some game specific presets I would have to manually adjust every one of them if I wanted them to match the global preset again, and repeat that every time I decided to change my global shader settings.

**Comment by milesrotaru** [comment]
I should also note that although the directories can be changed later, it's still going to dump a bunch of stuff in the default locations on first launch. So I have two redundant shader folders for example. One where I actually want them to be and another I can't get rid of. Plus all the other ones.

**Comment by orbea** [comment]
I am going to close this issue in favor of https://github.com/libretro/RetroArch/issues/6749 which has more discussion.
