### ISSUE TITLE
[Vulkan] Instant crash on startup

### ISSUE THREAD

**Issue by Elmazz37** [libretro/RetroArch#5169]
## Description

So i researched quite a bit about this issue and nothing helped. In the information section of retroarch it states that my device supports vulkan. I tried using menu driver rgui, sdl, glui or what have you, nothing worked. The closest thing i have seen to the reason why this is happening was this article:
https://forums.geforce.com/default/topic/1016337/geforce-drivers/vulkan-broken-on-windows-10-fall-creators-update-insider-preview-/

Although, i'm using an integrated intel gpu "Intel HD Graphics 4400" with the latest driver that support vulkan.
Just wanted to know if anyone else is having any issues with vulkan.

### Version/Commit

- RetroArch: 1.6.1 nightly build 07-13 (was using a stable, official 1.6.0 build, still the same result)

### Environment information

- OS: Windows 10

**Comment by Passingby1** [comment]
Retroarch 1.6.3 latest nightly as of this writing. 

Exactly the same result, instant crash on launch, using a GTX 1070 and Nvidia's latest drivers.

**Comment by RhythmLunatic** [comment]
Also get this.

Log file: https://pastebin.com/YgEG3fY7

**Comment by twinaphex** [comment]
Does this still happen?

**Comment by Passingby1** [comment]
Retroarch 1.7.5 stable.
GTX 1080ti
Drivers 416.16
Windows 10 1809

No crashes on launch where experienced when using the Vulkan driver.

**Comment by twinaphex** [comment]
Great, so this problem resolved itself. Closing then.
