### ISSUE TITLE
enable XMB "Menu Color Theme" to work when menu shaders are disabled

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#5174]
This is a request that the "Menu Color Theme" be enhanced so that it can change the colors when the menu shaders are offline.

When you are setting up a low-power device or one without good video driver support, it is often necessary to disable the menu shaders for performance reasons. Once you turn off the shaders, the Menu Color Theme option no longer works -- the only color scheme is White text on an Orange/Red background.

It would be great to have multiple color themes to choose from regardless of whether there is a ribbon, snow effect, etc.

**Comment by alfrix** [comment]
this is currently possible, this can be closed
