### ISSUE TITLE
7z crashing issues

### ISSUE THREAD

**Issue by crapnicki** [libretro/RetroArch#5177]
Running RetroArch on Windows 10 to test out things for my Lakka build.

```
RetroArch [INFO] :: === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Jun  1 2017
RetroArch [INFO] :: Version: 1.6.0
RetroArch [INFO] :: Git: a4358de
RetroArch [INFO] :: =================================================
```

In my testing, it appears that 7z extraction will crash during processing of 7z archives.  When trying to load a PSX game in `Beetle PSX HW`, RetroArch will load the archive and look to be launching the ROM, but it will crash RetroArch with an error.

The debug window will look something like this:

```
RetroArch [libretro INFO] :: Loading D:\test\CD (Disc 1).cue...
RetroArch [libretro ERROR] :: Error opening file:
D:\test\CD (Disc 1).bin
No such file or directory
terminate called after throwing an instance of 'MDFN_Error'
```

`debug.log` shows:

```
Attempt to read LBA 16, >= LBA 0
CDIF Raw Read error
```

In the directory, the .cue file will be there, but not the .bin file.

Doing some quick tests, as I thought, initially, it might be because of special characters in the file name:

- Renamed 7z archive from `CD (Disc 1).7z` to `CD Disc 1.7z` (removed parentheses): **doesn't work**
- Renamed 7z archive from `CD (Disc 1).7z` to `CD(Disc1).7z` (removed spaces): **doesn't work**
- Renamed 7z archive from `CD (Disc 1).7z` to `CDD1.7z` (removed both): **doesn't work**
-  Extracted the .cue and .bin files first, before loading 7z the archive: **works**
- Extracted the 7z archive and repackaged as a zip with the same name (original file name): **works**

So, it looks like to me that RetroArch's 7z lib is barfing on 7z archives for some reason.

**Comment by RobLoach** [comment]
`.bin` and `.iso` disc content has always been an issue in archives. It's recommended to keep them extracted in different folders instead. Somewhat related issue about [Extract  whole archives in some cases #4331](https://github.com/libretro/RetroArch/issues/4331).

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/issues/4331
