### ISSUE TITLE
"Show Hidden Files and Folders" is not functional

### ISSUE THREAD

**Issue by Elmazz37** [libretro/RetroArch#5180]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The option, which can be set to on/off in the "Load Content" settings is not functional. It shows hidden files either way. I dunno if it takes the "filter" setting after it and therefore neglecting it in the long run or its just a bug.

### Expected behavior

Being able to keep the hidden files hidden in the retroarch's file browser.

### Actual behavior

Hidden files can still be seen even if the option is turned to off (or on, doesnt matter)

### Steps to reproduce the bug

1. Make a file hidden.
2. Look into the dir using retroarch.

### Bisect Results

Probably ever since the feature came out (just like the "scan file" bug i'd assume).

### Version/Commit

Latest nightly build as of this hour. 1.6.1 07-16 22:02

### Environment information

- OS: Windows 10

**Comment by Elmazz37** [comment]
Not really the issue i care of as of now, since i started making playlists, but i just figured i'd report it.

**Comment by RobLoach** [comment]
It hides files that start with a `.`, like `.gitignore`. How are you making the files hidden?

**Comment by Elmazz37** [comment]
Oh... I thought it detects if the file is hidden via file explorer (windows). Ok, closed, thank you for the info.
