### ISSUE TITLE
[iOS] Video not rendering (black screen) but emulation is executing (XRGB8888 Pixel Format?)

### ISSUE THREAD

**Issue by yoshisuga** [libretro/RetroArch#5181]
## Description

I've seen this happening for the following cores:

- mednafen_psx (beetle)
- nestopia

The video is not being rendered on the screen (black screen), but emulation is running as sound can be heard and the controls are responsive.

Had some help from radius and bparker on the retroarch discord, and we found out that the problem is very likely with RetroArch and not the cores themselves.

I was able to take a screenshot in both mednafen_psx and nestopia (with GPU screenshot disabled) and I do see the screenshots, so something appears to be wrong with the rendering in the retroarch video driver for OpenGL in iOS maybe?

Edit: radius mentioned that the problem is that the cores use the XRGB8888 pixel format, and thats not being rendered in RetroArch.

### Expected behavior

Video being rendered.

### Actual behavior

Video not being rendered, sound can be heard, controls are responsive. Taking a screenshot works and shows the screen that should be shown.

### Steps to reproduce the bug

1. Run the iOS build of RetroArch (1.6.0), with the mednafen_psx core and/or nestopia cores
2 Install the psx bios files in Documents/RetroArch/system 
3. Run a disk image for psx

### Bisect Results

This was reproduced on 1.5.0 as well.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: d2cdc97e8f4737e7c9a509e172af69e6e7f03931

### Environment information

- OS: iOS
- Compiler: iOS 10.3 SDK

**Comment by Alex793** [comment]
https://github.com/libretro/RetroArch/issues/4624

**Comment by Alex793** [comment]
Hi yoshusuga, this is the complete list of the core with this issue : 

- 4DO (3DO)
- Nestopia (NES)
- Stella (ATARI 2600)
- Mednafen Lynx (ATARI LYNX)
- Virtual Jaguar (ATARI JAGUAR)
- Prosystem (ATARI 7800)
- Mednafen VBA-M (GBA)
- Beetle PSX (PSX)
- Beetle PC-FX (PC-FX)
- MelonDS (NDS)
- SameBoy (GB/GBC)

If you find the issue and need some test let me know.

**Comment by yoshisuga** [comment]
Thanks for that list @Alex793 ! That's really good to know!

I did some testing on some commit hashes and was able to narrow down to the commit where this issue happened:
https://github.com/libretro/RetroArch/commit/8cd2566128d4fc14f82bd163708ff7beb25d8067

@twinaphex and bparker helped me isolate the fix to this opengl texture storage capability that needed to be disabled for iOS, and that seems to have fixed the issue:
https://github.com/libretro/RetroArch/commit/69c05cd7b469b4336f80f781745bd3a6c943c257

This should be working now, if you can just try out those cores and see if they work, that'd be great :)

**Comment by Alex793** [comment]
Very very good news ! I let you know as soon as possible. A big thanks 🙏

**Comment by Alex793** [comment]
Many many thanks, all cores are now OK.

This big issue since 1.4.1 is now fixed !

Thanks again 👍

**Comment by iOS4all** [comment]
Please give me the link to download it to my jailbroken iPad Air 2 iOS 10.2
