### ISSUE TITLE
the dot / period character (.) in a RDB database name truncates playlist filename

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#5182]
## Description
When a dot character (.) appears in the name of a RetroArch RDB database, the playlist filename truncates at that point.

### Expected behavior
A playlist called `MAME 0.78.lpl`

### Actual behavior
A playlist called  `MAME 0.lpl`

### Steps to reproduce the bug

1. Scan ROMs matching a database with a dot in the filename

### Bisect Results

This has happened across several Windows x64 and x86 nightlies over the last two weeks. It's unclear to me that there has ever been a database with a dot in the name before, so it may be that this bug has existed since the beginning of the playlist scanner.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

-Git: 5636b0f
- OS: Windows 10 x64
- Compiler: [In case you are running local builds]

**Comment by markwkidd** [comment]
This began over in libretro-super: https://github.com/libretro/libretro-super/issues/480

**Comment by RobLoach** [comment]
Perhaps we fix the version numbers? Remove the dot? Use an underscore?

**Comment by markwkidd** [comment]
I don't have any particular need for the dot :)

Workarounds:

* Use core-name-style: MAME 0.78 -> MAME 2003
* Underscore the dot: MAME 0.78 -> MAME 0_78 (kind of ugly)
* Omit the dot: MAME 0.78 -> MAME 078

Of the workarounds I think I like MAME 2003.rdb most, on aesthetic grounds.

**Comment by retro-wertz** [comment]
just make it simple. MAME 078 should be fine

**Comment by retro-wertz** [comment]
ok just realized, RDB should follow the core name intended (078 is
mame2003) to avoid confusion.

**Comment by RobLoach** [comment]
PRs up for "MAME 2003" style.
