### ISSUE TITLE
New user, Retroarch xmb not showing

### ISSUE THREAD

**Issue by SoonerDave24** [libretro/RetroArch#5190]
Was working fine but now XMB not displaying, just background. Are there hot keys for resetting defaults or something? I have no menus.

**Comment by bparker06** [comment]
Can you post a screenshot?

**Comment by SoonerDave24** [comment]
[IMG]http://i67.tinypic.com/t8vwqf.jpg[/IMG]

**Comment by bparker06** [comment]
Wow that is quite strange. Can you post a log? We have no idea what kind of system this is or what platform you're running on.

**Comment by RobLoach** [comment]
What's in your retroarch.cfg? I've accidentally set the menu font scale to 0 before.

**Comment by SoonerDave24** [comment]
I installed this on a laptop  x86 with no OS.

**Comment by SoonerDave24** [comment]
Can u access the .cfg with any hotkeys?

**Comment by bparker06** [comment]
You installed what exactly? And no.

**Comment by SoonerDave24** [comment]
Lakka w/ Retroarch. Sorry still new to all this. I could just reinstall it I guess. Haven't done too much with it yet

**Comment by RobLoach** [comment]
You can get at the configs through the network share: http://www.lakka.tv/doc/Accessing-Lakka-filesystem/
