### ISSUE TITLE
[MAME] Immediate desync after connecting to host

### ISSUE THREAD

**Issue by phen0menal** [libretro/RetroArch#5193]
It's simple to reproduce, MAME 2000, 2014 and MAME cores have been tested for this. RetroArch's verbose output constantly spits out "Network is stalling at frame number, count of number of number". I'm not sure if anyone else is having this issue but I'm running two windows 10 devices on the same LAN testing this and MAME doesn't seem to be synchronized at all.

**Comment by hizzlekizzle** [comment]
I don't know that netplay works with MAME cores at all. Have you tried FBA? At least some of its cores are known to work well, including CPS1/2/3 and Neogeo.

**Comment by phen0menal** [comment]
I'll report back with updated information tonight, thanks for the heads up.

**Comment by retro-wertz** [comment]
i do not remember mame to be netplay-capable

**Comment by fr500** [comment]
2014+ are certainly not, they don't have serialization.
It should "work" as in pass inputs between sessions, but that's it.

**Comment by fr500** [comment]
The issue template is there for a reason.
Core issue. Closing.
