### ISSUE TITLE
Retroarch menu in nes mini not working

### ISSUE THREAD

**Issue by falcocerr** [libretro/RetroArch#5198]
just downloaded RetroArch, no issues installing it but when I enter any game in my nes mini, press start+select the menu appears but it freezes, I can't do anything and after a few seconds the game is reset and I'm send back to the game selection screen, happens for every game, menu appears but I can't move or select anything and then it resets

**Comment by twinaphex** [comment]
@bparker06 I think is the only one who has a NES Mini (Famicom Mini IIRC).

**Comment by bparker06** [comment]
@falcocerr NES Mini environments are highly modified so I don't think we'd be able to help with this. The menu toggle function in RA works properly on the platforms we officially support, so it's probably best to reach out to someone like @ClusterM or @madmonkey1907 instead.

**Comment by orbea** [comment]
As indicated in the previous comment we probably can't help and given the lack of any replies I am going to close this.
