### ISSUE TITLE
android Menu issue

### ISSUE THREAD

**Issue by just-yassin** [libretro/RetroArch#5205]
the nightly got a problem when trying to configure the app in settings tab
touching on most items doesn't work
sometimes where ever you touch in the whole screen the only thing that changes is the first option
this problem happens only in the setting tab, the others are fine

**Comment by icebal** [comment]
I also have this issue with the latest google play version, as well as the downloadable version. To further expand on this, you can select menu folder options, like Input Settings, but when selecting an option to configure, it only toggles/selects the first option (the highlighted one)

**Comment by jasonbrandt42** [comment]
I have this same issue on android as described by op.

Can we revert until fix is in place?

**Comment by Kivutar** [comment]
I'm foinf to fix it

**Comment by jasonbrandt42** [comment]
Thanks!  I will keep an eye out for the fix post, cheers!

**Comment by icebal** [comment]
Play update just hit, fixed and works great

**Comment by jasonbrandt42** [comment]
I can verify the fix i updated from google play worked for me too.  cheers!
