### ISSUE TITLE
[Request] Display controller input via Onscreen Overlay [BOUNTY] [$80]

### ISSUE THREAD

**Issue by HeyItsLollie** [libretro/RetroArch#5214]
The premise for this bounty is fairly straight-forward: If the player has an Onscreen Controller Overlay enabled and is using a physical controller, allow RetroArch to listen to the user's input binds, and display them through the Onscreen Controller Overlay.

I see this being primarily useful for recording/streaming and speedrunning, where controller input is more useful for an audience. That said, this could also make it easier to test the visual side of Onscreen Controller Overlays on PC environments.

Given that RetroArch's overlays already provide visual feedback for touch-input (buttons light up, joysticks move around) and custom overlays can be made fairly easily, it seems like the perfect fit for controller input display. I hope it'd give onscreen controller overlays more purpose on PC/Mac/Linux.

---

There is a [$80 bounty](https://www.bountysource.com/issues/47676395-request-display-controller-input-via-onscreen-overlay) on this request.

**Comment by Ryunam** [comment]
This has been talked about in the past and I fully agree that it would be an amazing feature. First of all, it would provide a practical - and not purely aesthetical - use to overlays for non-touchscreen users. Secondly, like you said speedrunners would benefit immensely from a real-time display of inputs while playing. 

Implementing a listening mode through overlays seems like the ideal choice simply because that way you could customize your view for each system, create a border / frame with only the inputs you want to monitor and have them react to your controller in real time. I tried to look into creating an option like this myself, but admittedly I would need more directions and I am not nearly competent enough to do it.

**Comment by Ryunam** [comment]
See also https://github.com/libretro/RetroArch/issues/3314 about this.

**Comment by HeyItsLollie** [comment]
> See also # 3314 about this.
I saw that issue — the use-case seemed to be far more specific, so I decided not to revive it. I wasn't sure if unixunion was talking about displaying gamepad input, or displaying a prepared info-graphic as a _border_ overlay. (If it was the latter, a new Hotkey Bind to toggle overlays on/off would serve their purpose.)

Still, I'm glad to see that others have brought this up in the past! I know it's a pretty niche feature, but I hope that people would find it useful enough to consider implementing.
(also- updating my original post with what I wrote on the forums, better description)

**Comment by Ryunam** [comment]
I would suggest editing the title of this issue here by including a reference to your $50 bounty, in order to hopefully increase its visibility and attract potential contributors.

**Comment by twinaphex** [comment]
Added it to the title for him.

**Comment by Ryunam** [comment]
Just reporting that I have added €25 towards this request. It'd be cool to update the title and hopefully some contributors can chime in the not-so-distant future!

**Comment by twinaphex** [comment]
Updated the title!

**Comment by HeyItsLollie** [comment]
I'm not sure how Bountysource shares updates, but I'd just like to state here that @Denu8thell has started working on this bounty! https://github.com/Denu8thell/RetroArch/tree/overlay_controller_response

**Comment by Ryunam** [comment]
Hi, @Denu8thell! I am currently testing your code that was just merged. All buttons appear to light up properly and react to controller inputs as intended. The only aspect I am having some issues with is the D-Pad.

On the vast majority of the overlays that are distributed through the libretro servers (the ones you can update through Retroarch itself) D-Pad directions do not seem to light up, save for the PS1-styled variants. I am actually wondering if it's more of a quirk with the overlays themselves, such as the Nintendo-styled D-Pads that come with these overlays possibly not being programmed to detect individual directions.

**Comment by Denu8thell** [comment]
@Ryunam Yeah, a lot of the overlays are set up so the D-pad is just a big button. The flat variants work well, I think the overlays just need to be set up so that each d-pad direction is it's own image.

**Comment by HeyItsLollie** [comment]
I'm happy to report that the solution for this bounty seems to be working just fine on my end. Thank you for working on this! I've been building a couple overlays designed for input display - here's one based on the Dualshock controller, everything should light up correctly.
[input-display-ps1.zip](https://github.com/libretro/RetroArch/files/1212281/input-display-ps1.zip)

The easiest way to ensure that certain parts of an overlay _don't_ light up, is to have the following lines in the overlay's config:
overlay0_alpha_mod = 2.0
This controls the alpha modifier for all elements in the overlay. value can be any amount.

overlay0_desc#_alpha_mod = 1.0
Ensures that the element's alpha is multiplied by 1, effectively doing nothing. Use it for any element that shouldn't light up.

Overlays do need to be specifically designed for light-up action, but I found that gamepads\dual-shock\dual-shock.cfg does it out of the box. I'm going to be working over a few new overlays for input display, see if I can't fill this new void up a little.

**Comment by HeyItsLollie** [comment]
Development-wise, is there anything that still needs to be worked on? As far as I can tell, input display seems to be totally functional - it just requires overlays that can actually take full advantage of the feature. I'd be more than happy to see @Denu8thell claim the bounty.

**Comment by Denu8thell** [comment]
As soon as this issue is closed, I'll be able to put in a claim. If everyone is satisfied, then the issue just needs to be closed!

**Comment by HeyItsLollie** [comment]
I was waiting in case @Ryunam or @twinaphex had anything else to say on the matter — felt a bit presumptuous for me to close the issue, not being part of the RetroArch team and all. But if everyone's happy/has nothing else to add, I'll close the issue this evening!

**Comment by Ryunam** [comment]
As far as I am concerned, I would more than glad to award the bounty to @Denu8thell. The work done for this request is absolutely satisfying and the explanation provided about the D-Pads on the Nintendo-style overlays is perfectly clear. Thanks a lot for contributing so quickly to this!

**Comment by twinaphex** [comment]
Alright, I'll close the issue then.

**Comment by HeyItsLollie** [comment]
Weird, displaying all given inputs (for a single controller) at any moment is how the feature is supposed to work. I've just updated to the latest nightly to check, and the feature has seemingly been busted in RetroArch 1.7.1.

Show Inputs In Overlay was last working correctly in the Stable 1.7.0 release.
1.7.0 can be found here: https://buildbot.libretro.com/stable/1.7.0/

**Comment by hizzlekizzle** [comment]
@HeyItsLollie 
Aha! So it used to work properly? I hadn't used it during that time, so I assumed it was always this way. I'll try to bisect it.

**Comment by menamortarte666-creator** [comment]
Hi.

JuanMena / MENAMORARTE here.

I'm making these in case anyone is still interested: https://retrogametalk.com/threads/im-working-on-retroarch-animated-overlays.10656/
