### ISSUE TITLE
[Android] DS4 share button broken

### ISSUE THREAD

**Issue by Guttural** [libretro/RetroArch#5220]
## Description

DualShock 4 controller's share button won't register whatever key it is mapped to, not working in any core/game I've tried, this issue is exclusive to RetroArch as the button works fine in other apps, I am using the older style DS4 paired wirelessly to my Xperia phone

### Expected behavior

All buttons to work as intended after automatic input configuration

### Actual behavior

Unable to use the share button

### Steps to reproduce the bug

1. Play a game using DS4 with auto configured mappings

### Bisect Results

After install

### Version/Commit

- RetroArch: v1.6.3
(Also experienced this issue on previous version)

### Environment information

- OS: Android 7.1.1
- Compiler: N/A

**Comment by fr500** [comment]
It's most likely set to android back on your keylayout files.
Nothing we can do about it.
