### ISSUE TITLE
Linux : Zipped roms fail on read only drive

### ISSUE THREAD

**Issue by 7oxicshadow** [libretro/RetroArch#5227]
## Description

My roms are stored on a NAS and recently I have started mounting the drives as read only. Any games that are not .zip or .7z load or work fine but compressed files cause the cores to hang or not load. Fceumm just refuses to load and Bsnes loads to a black screen.

Looking at the command prompt yields no information as to why it has failed.

I am making an assumption that the zip file is extracted to the same directory as this zip file itself, loaded into ram and then deleted? I have to admit I am not sure of the best solution of this. As a minimum it would be beneficial to test if the drive is writeable and if not fail with an error message informing the user.

I can confirm that if I mount the drive as writable all compressed roms work as expected.

### Expected behavior

Zip will be extracted and core will boot

### Actual behavior

Command line log appears to show the zip being loaded but the core hangs

### Steps to reproduce the bug

1. Mount a drive containing a zipped rom as read only
2. Attempt to load the zipped rom (Tested fceux and bsnes) from the command line (no gui involvement)

### Bisect Results

I suspect this has always happened since release as my scenario is quite unique. As a minimal step, consider checking for a read only state and exit gracefully with an appropriate message to warn the user.

### Version/Commit
Any

### Environment information
Fedora 25 (64 bit)
i7 6700k @ 4.5GHz
16GB ram
GTX1070 (prop 384.59)

**Comment by bparker06** [comment]
Your assumption is correct. You can change the directory it extracts to by going to Settings -> Directories -> Cache. Also make sure your savefile/savestate/screenshot/etc. folders are not set to "<Content Dir>" or the same thing will happen with those.

**Comment by 7oxicshadow** [comment]
Thanks for the tip regarding the "cache" directory. It appears to work as you described.
Thankfully any other directories are located on a writeable drive so they don't suffer the same problems.

**Comment by hizzlekizzle** [comment]
Ok, closing this now, then. Feel free to open it back up if needed.
