### ISSUE TITLE
The width of the text of sublabels in Russian

### ISSUE THREAD

**Issue by btimofeev** [libretro/RetroArch#5233]
## Description

The width of the text of all sublabels in Russian is 2 times less than in English. As a result the text of the sublabels overlaps the next heading.

### Expected behavior

![2017-08-01-133254_471x161_scrot](https://user-images.githubusercontent.com/1546407/28821815-9a9faa88-76bf-11e7-9a06-2728a4ceb7b5.png)

### Actual behavior

![2017-08-01-133214_462x147_scrot](https://user-images.githubusercontent.com/1546407/28821826-a5c1f13c-76bf-11e7-9a05-ac46b094a4e1.png)

### Steps to reproduce the bug

1. Change language to Russian (Settings tab > User > Language > Russian)

### Version/Commit

- RetroArch: 1.6.3 and git 572f7bea2

### Environment information

- OS: Linux
- Compiler: GCC (7.1.1) 64-bit

**Comment by bparker06** [comment]
Hi @btimofeev,

I've made a change in 6b36977 that should fix this issue, please let me know if it solves your problem.

Thanks

**Comment by btimofeev** [comment]
@bparker06, yes, your fix has solved the problem, thanks.
