### ISSUE TITLE
Some ROMs not added to XMB after Directory Scan

### ISSUE THREAD

**Issue by RobotLimeLtd** [libretro/RetroArch#5236]
## Description

Several game ROMs are not added to the relevant XMB menu after a directory scan, but can be launched and played by choosing "Scan File".

So far, this has only affected some Master System titles, for which I'm using Picodrive.

I would appreciate any help in diagnosing this further myself (i.e. log file locations) so I can nail down the difference between the ROMs that are playing ball, and those that are not.

### Expected behavior

After running Scan Directory, games not previously listed under the relevant system's XMB menu should appear.

### Actual behavior

After running Scan Directory, many games are missing.

### Steps to reproduce the bug

Tricky, as this issue is only affecting specific ROMs (and currently only Master System ones) but here's what I'm doing:

1. Add ROM to a directory (e.g. using ES File Explorer Pro
2. In RetroArch, Import Content > Scan Directory
3. Navigate to folder containing roms to scan
4. Choose "Scan This Directory"

### Bisect Results

Since upgrade to 1.6.3; I'm pretty sure it's limited to MasterSystem ROMs at the moment, and only certain roms.  

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.3 / adae065 (Build Date Jul 28 2017).

### Environment information

- OS: Android 4.4 (running on GPD-XD device)

**Comment by RobLoach** [comment]
1. What game won't scan?
2. What is the CRC of the file?

You could likely do a search for it in https://github.com/libretro/libretro-database to see.

**Comment by RobotLimeLtd** [comment]
Ah, ok... simple as that then.  The "faulty" ROMs don't match the CRC32 in libretro-database.

**Comment by RobLoach** [comment]
If you put together a GoodTools set for SMS, we could add it in. Feel free to close this and open up an issue over at  https://github.com/libretro/libretro-database :+1:

**Comment by orbea** [comment]
As this is a database issue I am going to close it, please feel free to open a new issue or PR for libretro-database if this is still an issue, thanks!

https://github.com/libretro/libretro-database
