### ISSUE TITLE
Thumbnails not displayed after Directory Scan

### ISSUE THREAD

**Issue by RobotLimeLtd** [libretro/RetroArch#5237]
## Description

After a directory scan, game thumbnails are no longer displayed in the XMB.  Quitting RetroArch and relaunching brings the thumbnails back.

### Expected behavior

Thumbnails should always be displayed in the XMB

### Actual behavior

Thumbnails disappear after directory scan.

### Steps to reproduce the bug

1. Import Content > Scan Directory
2. Navigate to directory to scan
3. Scan Directory
4. Quit back to the XMB and browse any of the game system menus 

### Bisect Results

Happening since 1.6.3 (however, I upgraded to this from 1.3.x)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: RetroArch: 1.6.3 / adae065 (Build Date Jul 28 2017).

### Environment information

- OS: Android 4.4 (running on GPD-XD device)

**Comment by RobLoach** [comment]
Where are your thumbnails? What is your thumbnails directory set to? What thumbnail files are there? What's displayed in your menu playlist?

**Comment by RobotLimeLtd** [comment]
Thumbnails directory is set to /storage/emulated/0/RetroArch/thumbnails (i.e. the default for Android).

Directory contains all Thumbnails downloaded via OnlineUpdater > Thumbnails Updater

The playlists for each system are set to display "Boxarts".

**Comment by RobotLimeLtd** [comment]
I've just spotted... this is a duplicate of https://github.com/libretro/RetroArch/issues/5185

**Comment by orbea** [comment]
I am going to close this issue in favor of https://github.com/libretro/RetroArch/issues/5185.
