### ISSUE TITLE
Windows 10 64bit - Retroarch doesn't recognize wireless controller post-launch

### ISSUE THREAD

**Issue by tapperp** [libretro/RetroArch#5242]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Using Retroarch 64bit on Windows 10. Love it!

I often use a wireless Xbox Elite controller via an official wireless adapter.  I have noticed that if I turn on my controller after launching Retroarch, it will not be recognized, even though it is recognized by Windows. I do not have this problem with any other apps or games that I've seen.

It works fine if I remember to turn on the controller before launching Retroarch. However, if my controller goes to sleep (it will auto-off after some minutes of non-use to save battery life) then Retroarch will not recognize it once it's powered on again.

I have found that if I press "F" twice on the keyboard to switch Retroarch from fullscreen to Window and back again, then Retroarch will then recognize the controller.

### Expected behavior

Retroarch should ideally recognize when a controller is turned on and initialized by Windows. 
Note, I also use Retroarch on a Shield TV, and that version properly recognizes its wireless controller at any time.

### Actual behavior

Retroarch is not recognizing wireless controllers (Xbox One Elite using official MS wireless adapter) post-launch.

### Steps to reproduce the bug

1. Launch Retroarch without wireless controller turned on.
2. Turn on wireless controller, and Retroarch will not see it even though Windows and other apps/games do.
3. Pressing "F" to switch Retroarch between fullscreen and window will force it to see the controller and then it works.

### Bisect Results

Has been this way since I first bought the wireless adapter a few weeks ago.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
d78ea9c (latest build)

### Environment information

- Win 10 64bit, with all latest updates etc.
- using downloaded builds from buildbot

Thanks for reading my report.

**Comment by sonninnos** [comment]
This seems to happen only with `raw` input driver, but not with `dinput`.
