### ISSUE TITLE
[Vita] glui scrolling

### ISSUE THREAD

**Issue by damteenagers** [libretro/RetroArch#5249]
When using the glui menu driver navigating through large lists of roms/folders (300+) can cause the selected item to move off the screen, this happens when either scrolling up or down too fast. This has been a problem for a while (since glui was made available to the vita?), and still occurs in both latest stable and nightly releases.

**Comment by damteenagers** [comment]
Oh yeah, for the love of god add batch/bat script execution on the dosbox core.

**Comment by Tatsuya79** [comment]
Same as https://github.com/libretro/RetroArch/issues/4668

**Comment by orbea** [comment]
Seems to be a duplicate of a fixed issue so I am going to close this, please let us know if you still have problems.
