### ISSUE TITLE
RetroArch 1.6.3 "Disk Image Append" restarts core Windows 10

### ISSUE THREAD

**Issue by mangopipeline** [libretro/RetroArch#5254]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented
## Description
When using the Disk Image Append in the XMB menu
when i select the new image to append, RetroArch Reloads the Core

### Description of the bug
I'm testing a multi cd sega 32x game.
when prompt to insert a different disk i run the following steps
1)press f1
2)go to core disk options
3)run Disk Cycle Tray Status
4)Resume emulation
5)press f1 again
6)try to change Disk Index (message list 1/1 images)
7)press Disk Image Append and browse to .cue file
8)when a double click on the new image

retro arch restarts the core from the beginning.

### Expected behavior
after step 7 retroArch would allow me to change the Disk Image Index Close the try and resume emulation.

### Actual behavior
Retro Arch Start From the begining...

### Steps to reproduce the bug

1)press f1
2)go to core disk options
3)run Disk Cycle Tray Status
4)Resume emulation
5)press f1 again
6)try to change Disk Index (message list 1/1 images)
7)press Disk Image Append and browse to .cue file
8)when a double click on the new image

### Environment information

- OS:  Windows 10
- Compiler: [In case you are running local builds]
- using PicoDrive 1.91

**Comment by mangopipeline** [comment]
I went back and tested a few different retro arch versions....
seems like 1.3.6 64 bit works like a charm....

**Comment by RobLoach** [comment]
Perhaps https://github.com/libretro/RetroArch/commit/366c73f429bf093fb0b7e876b3ea529709d1cdce ?

**Comment by mangopipeline** [comment]
this seems to fix in 1.6.7 thanks!
