### ISSUE TITLE
Potential issue with RA input_libretro_device_px defaulting to "0" / None

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#5257]
I am currently experiencing a strange issue resulting in any in-game input not being detected at all in some of the cores. This happens with my Xbox One Elite Controller in both wired and wireless mode.
All key shortcuts pertaining to RA features such as Fast-forward, Slowdown or Screenshot do function perfectly, but anything in-game just refuses to be recognised.

The interesting thing is that it only happens in some cores: I noticed the problem in bsnes-mercury-balanced, but Nestopia appears to be working perfectly as usual. I am using the latest cores and Retroarch updated to the latest commit.

- OS: Windows 10 x64
- Compiler: mingw64

**Comment by Ryunam** [comment]
Okay, I found out what was causing this problem. 
For some reason, the parameter "User 1 Device Type" was set to "0" / None by default. This produced the aforementioned behavior as a consequence (hotkeys working perfectly, while in-game buttons not being detected).

I don't know if that's an intended result, but what I am noticing is that RA is now setting that parameter to 0 by default even upon startup, with no cores loaded, while it would typically default to Retropad in the past. I had to manually change this in my bsnes-mercury-balanced remap and indicate that I'm using a "SNES Joypad".

**Comment by fr500** [comment]
Did you have a remap for that core in the first place?

**Comment by Ryunam** [comment]
No, I had no remaps in place for that particular core (bsnes-mercury-balanced). In fact, I had to create a remap for it and set the Libretro device to SNES Joypad to make this setting stick and prevent it from defaulting to 0.

**Comment by fr500** [comment]
ok you're right, it might be because of the new stuff going on with remaps, I'm saving the emulated device, I'll look for fix it later today

**Comment by fr500** [comment]
Please let me know if it's fixed and if anything else pops up regarding this issue

**Comment by retro-wertz** [comment]
just finished reinstalling arch here. compiled retroarch and psx_hw. controller still defaults to None.

**Comment by fr500** [comment]
do you have overrides enabled?

**Comment by retro-wertz** [comment]
i dont think so. its a clean os and retroarch install and not input stuff other than to swap buttons in fceumm

**Comment by fr500** [comment]
I just tried on an empty config and I get PS1 joypad

**Comment by retro-wertz** [comment]
ok scratch that.. for some reasons, controllers are now not set to None...

**Comment by fr500** [comment]
I'll keep this open just in case more issues arise, I think the change is for the better and I'll elaborate on that on the blog post.

**Comment by retro-wertz** [comment]
this seems random. i havent played or updated ra yet since the last time i chatted about it in irc. though it was kinda working but fceumm defaults to None now, although game controls are working. i did have remap on fceumm though.

**Comment by fr500** [comment]
If you have a remap that's normal,  the old remap doesn't have a device
saved so it's reading nul from the file, save it again

**Comment by fr500** [comment]
so, any conclussions?

**Comment by Ryunam** [comment]
Hi @fr500, it's working well now on my end! Cores are now defaulting to libretro_device 1 (or whatever was set in retroarch.cfg in the first place) and looks like it is not resetting to 0 anymore.
