### ISSUE TITLE
[Android] Mupen64Plus crashes when loading any content. 

### ISSUE THREAD

**Issue by MJaoune** [libretro/RetroArch#5260]
Hi, 
Mupen64Plus (Not GLES3 version) crashes when loading any N64 ROM, in both video drivers: GL and Vulkan.
Sony Xperia X with Android 7.1

_Sent from my Sony F5122 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fr500** [comment]
The issue template is there for a reason.
Core issue. Closing.
