### ISSUE TITLE
[Android] Mupen64Plus GLES3 text not visible in Harvest Moon 64.

### ISSUE THREAD

**Issue by MJaoune** [libretro/RetroArch#5262]
Not any text in the menu is visible in Harvest Moon 64, neither the keyboard for entering name. 
Video driver: GL
OS: Android 7.1
Phone: Sony Xperia X

https://s2.postimg.org/y8ozv32o9/Screenshot_20170807-132344.png

**Comment by orbea** [comment]
Your issues are better suited for the specific core repos, for example.
https://github.com/libretro/mupen64plus-libretro

**Comment by fr500** [comment]
The issue template is there for a reason.
Core issue. Closing.
