### ISSUE TITLE
(Direct3D) Menu display driver implementation (so that MaterialUI and XMB work) [$33]

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#5266]
https://github.com/libretro/RetroArch/blob/master/menu/drivers_display/menu_display_d3d.cpp

Our current menu display driver isn't really properly fleshed out.

* It fails to render MaterialUI properly.
* It fails to render XMB properly.

Once properly implemented, XMB and MaterialUI should render properly and it should look about the same as how it looks like with the OpenGL driver.

Currently only text is rendered with the XMB menu driver. We are still missing vertices and textures.

**Comment by fidelis1** [comment]
@twinaphex The bounty is now at $43.

**Comment by twinaphex** [comment]
Closing this so that I can approve the solution on Bountysource.
