### ISSUE TITLE
[Menu] Add a "Horizontal Animation" sublabel

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5271]
## Description

There's currently no sublabel for the Horizontal Animation in the menu.

### Expected behavior

There should be a sublabel for the Horizontal Animation menu entry, describing what it does and why.

Possibly just the following:

> Turning the horizontal menu animations off can result in a performance boost.

### Steps to reproduce the bug

1. Run RetroArch
2. Enable  Settings -> User Interface -> Advanced Settings in the menu
3. Visit  Settings -> User Interface -> Menu
4. Look for a sublabel under the Horizontal Animation entry

### Bisect Results

https://github.com/libretro/RetroArch/pull/5172

**Comment by Tatsuya79** [comment]
I was thinking, now that's the animation has been optimized:
"Make switching between playlists faster on slow devices."
and also 
"Disable dynamic wallpapers." if that's the case.

**Comment by RobLoach** [comment]
Make switching between playlists faster **for** slow devices.

?

**Comment by Tatsuya79** [comment]
Yes, feel free to correct my bad English! 😸

**Comment by orbea** [comment]
@RobLoach I made a PR to add a sublabel, can you please review when you a chance!

https://github.com/libretro/RetroArch/pull/7875

**Comment by RobLoach** [comment]
Thanks a lot! :+1:
