### ISSUE TITLE
[Wii U] Ogg vorbis code causing emulator lockups

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#5274]
**Description:**

Changing from core to core, as well as loading
ROMs in succession three to four times, results in a DSI error. Some suspect it being related to ogg vorbis. 

DSI: Instr at 010493AC bad read from unmapped memory at 0038004A
r1 00000000     r1 10965F88
r5 10D36500    r6 00000004
r10 00000000  r11 0002000
r15 10610000 etc
r20 108BC6D4 etc
etc 
etc
010493AC (3024939F): coreint.rpl|CoreInitDefaultHeap
etc

![dfbnyvf](https://user-images.githubusercontent.com/15101626/29102546-23ad2050-7c77-11e7-9232-9eaa4aefd489.jpg)

User QuarkTheAwesome described it as something pertaining to the Ogg Vorbis code and how it is handled, and that there is a invalid address being freed up. And that this shouldn't be occurring. Would it be feasible to have a test branch/version without the ogg code to test to see how it behaves? 

**Expected behavior:**
RetroArch should be able to change from ROM to ROM, and core to
core without complete system lockup/DSI error. 

**What should happen:** 

For the RA app to seamless and stably change cores. 

**Steps to reproduce the bug:**

1. Open up RetroArch 1.6.4
2. Load the Snes9x mainline core, play a few ROMs
3. Change from Snes9x to Genesis Plus GX core

**Bisect Results:**

Error has has been occurring, reported from various users who have been using 1.6.0 vanilla. 

**Environment information:**

- OS: Wii U version 5.5.1

Screenshots taken by Temp user Ploggy

![20170805_081302](https://user-images.githubusercontent.com/15101626/29102616-a9dc335a-7c77-11e7-94f2-ec42cee5819f.jpg)
![20170805_054049](https://user-images.githubusercontent.com/15101626/29102615-a9d943e8-7c77-11e7-9c3d-cf3f4af5cb6e.jpg)

**Comment by QuarkTheAwesome** [comment]
The third one (mentioning wiiu_input_poll) possibly fixed in ca80f13? The ogg problem has turned out to be specific to Genesis Plus GX, talking about that in libretro/Genesis-Plus-GX#94.

**Comment by Ploggy** [comment]
Reallly!? that's brilliant if it's fixed, any news on the second?

**Comment by roflcopter777** [comment]
Do we know anything about  libretro/Genesis-Plus-GX#94.?

**Comment by WiisleyU** [comment]
I am having this error now when I quit Retroarch even with the content closed.
Using .rpx version with Retroarch Launcher.elf on Homebrew Launcher
Using Snes9x2010, mGBA and Genesis cores.

**Comment by orbea** [comment]
@roflcopter777, @QuarkTheAwesome and @WiisleyU Is this still a problem?

**Comment by QuarkTheAwesome** [comment]
From what I remember this was a genplusgx thing that got fixed at the time. I haven't heard any report of it still happening for a good while, so it should be okay?

On 27 December 2018 5:10:42 pm AEDT, orbea <notifications@github.com> wrote:
>@roflcopter777, @QuarkTheAwesome and @WiisleyU Is this still a problem?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/libretro/RetroArch/issues/5274#issuecomment-450082998

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by orbea** [comment]
Okay, thanks for the update, if anyone can still reproduce this please let us know!
