### ISSUE TITLE
Latest update broke savestates on android 

### ISSUE THREAD

**Issue by jasonbrandt42** [libretro/RetroArch#5275]
The latest update no long loads any save states on android devices.  (i am testing on nexus 6) 

retroarch will give the percent indicator that a savestate was loaded, but nothing happens.    

changing save state directories does not help either.   

previously i had save states set to individual game folders, and the states are still there.  

But no state will load.

**Comment by fr500** [comment]
it's working fine for me here.
Does it work if you make a new save state and try to load it?

If you were using "content dir" read the announcement on the blog for the explanation and solution.

**Comment by fr500** [comment]
Saving Stuff on Content Dir

The new behavior is to always provide a sane default directory for Saves, Savestates, System Files, and Screenshots. Windows and Android have been historically problematic in this regard since the content directory may not be writable at all times.
The old behavior relied on the setting strings being empty, now we provide a default value for these dirs on both Android and Windows which means the string will never be empty. Other platforms should follow this convention shortly.

So if you want to use content dir after 1.6.3 do the following:

    Navigate to Settings / User Interface
    Enable Show Advanced Settings
    Navigate to Settings / Saving
    Enabled the respective settings for the stuff you want to reside with your content

We apologize for any inconvenience this may cause to existing users but we need to make some changes to make progress.

**Comment by jasonbrandt42** [comment]
I actually had already tried that earlier, my poorly worded "changing save state directories" was meant to represent my attempt to say I did the process you suggested above. 

I created a new save state and that save state  Did load.  

however= 
- even though the system is set to sort savestates in folders = it did not.

- i attempted again to load one of the old save states and it did not load (thinking that once a new save state was created, possibly the dir for looking at where to load states from was set, but in this case, it is not finding or properly loading the old savesates) = it just shows 100% and nothing happens...

**Comment by fr500** [comment]
Ok, I need more info
Do your savestates reside with your roms or are there in a discrete dir?

**Comment by jasonbrandt42** [comment]
They are in the same file folder as the roms

**Comment by fr500** [comment]
Then you have to follow the procedure I just highlighted, enable all those. The sorting options don't work when this is enabled.

**Comment by jasonbrandt42** [comment]
OK, let me make sure I am doing this right... 

I have done all of the following, here are my results...

Trial 1
- Settings -> Saving -> Enable "Sort Savestates In Folders" -> attempt to load rom and game savestate = fails(nothing happens)

Trial 2 
- Settings -> Saving -> Enable "Sort Savestates In Folders" -> also Enable "Sort Saves In Folders" -> attempt to load rom and game savestate = fails(nothing happens)

Trail 3 
- Settings -> Saving -> Disable "Sort Savestates In Folders" -> also Disable "Sort Saves In Folders" -> attempt to load rom and game savestate = fails(nothing happens)

Notes: (just as an 
- When i created the new savestate today; a new .SRM file was created today when the Sort Savestates In Folders was enabled is saved in the retroarch 'saves' folder under that emulator name.  And the savestate was saved under "states" under that rom name folder. 

When I tried to copy the old save states to that states folder, and I copied the .srm file to the saves folder  the old saves loaded fine (with the Sort Save States enabled) 

So it seems the only time it does not work is when the Sort Save States is Disabled, in which case moving the files and enabled sort save states works...

**Comment by fr500** [comment]
No that's not the setting you need to enable.
With your saves in the original location look for the last 4 options

**Comment by jasonbrandt42** [comment]
Yes, ok.   

The third to last setting, "Write Savestates to Content Dir"  enabled  works for me when leaving savestates in content directory.  

(on a side note, if i enable "System Files in Content Dir" then the core cant find the rom files.  I don't enable that and everything works fine)

**Comment by jasonbrandt42** [comment]
this issue can be closed then.  Thanks!

**Comment by fr500** [comment]
system files means bios files, so if you enable that you need your psx bios or whatever on that location
thanks for the patience.

Gotta break some eggs to make an omelette
