### ISSUE TITLE
Which file stores the data for game time played for a ROM?

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#5276]
## Description

Would like to investigate enhancements to the game logging information, i.e. time played on a ROM, other associated metadata that might be scraped from another source regarding game rating, or a leaderboard etc. 

I believe retroarch logs time played on a ROM, but would like to know where I can go to find this file and begin looking further.

### Expected behavior

Someone provides me the file path

### Actual behavior

Everything is fine

**Comment by RobLoach** [comment]
Know where the content file is? This may be get a better response on the forum, perhaps?

**Comment by bparker06** [comment]
Pretty sure we don't log that.

**Comment by Ryunam** [comment]
I don't think that kind of information is currently logged by Retroarch. In fact, I had suggested such a feature some time ago as an extension of the playlist interface, as outlined in issue #3527 (now also a bounty).

**Comment by futurepr0n** [comment]
Thanks! Will have a look at original issue/bounty.
