### ISSUE TITLE
Branding?

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#5278]
I think we should work a bit more on the image of the application.
A good first step is the icon.

I updated the icon following material design guidelines but I think it's a bit too dark, the drop shadow doesn't look right so I have two other alternatives

![canvas 1](https://user-images.githubusercontent.com/1721040/29145659-a3038400-7d23-11e7-8cf4-02a20ee4d59d.png)
![canvas 2](https://user-images.githubusercontent.com/1721040/29145661-a3c5eb9e-7d23-11e7-9b90-916d1e11dc11.png)

Or maybe something more colorful?
![canvas 3](https://user-images.githubusercontent.com/1721040/29145803-24ee84d8-7d24-11e7-9d1a-ec73bfff32c4.png)

We have very little in branding / identity, it may be good to consider this as a serious issue moving forward.

**Comment by RobLoach** [comment]
Really like the colour. Always thought the black and white was a bit bland. We could make it match the default colours presented in XMB's default theme.

**Comment by twinaphex** [comment]
I like the middle one.

**Comment by Ploggy** [comment]
Maybe something like this.... But you know... Good.

![naff](https://user-images.githubusercontent.com/1160255/29170324-f17e5bee-7dcf-11e7-8e3e-2bfd41bc4512.png)

**Comment by twinaphex** [comment]
Nah. I think so far from what I have seen, the middle one (the black one with hues) looks best.

**Comment by Ploggy** [comment]
tbh I like the other styles too, just though an icon with some sort of lettering. :)

**Comment by RobLoach** [comment]
@Ploggy While I'm not a designer, I'd still suggest watching the [TEDTalk on city flag design](https://www.youtube.com/watch?v=pnv5iKB2hl4). Touches on why letters on a logo are a bad idea :wink: .

**Comment by MarcoEstevez** [comment]
I Like the middle one too.

**Comment by danieljg** [comment]
I think the middle one is pretty cool, but perhaps it would nicer with the dark-grey and light-grey colors inverted, while keeping the alien white.

**Comment by cucholix** [comment]
What's the official current logo?
https://www.libretro.com/index.php/retroarch-2/

I read somewhere that RetroArch logo/font was dropped beacuse copyright issues, is that true?

**Comment by twinaphex** [comment]
Don't know what you're talking about, we just dropped it because it looked too generic and Agnes Heyer made a new one from scratch.

**Comment by cucholix** [comment]
Gotcha, so RetroArch name is the official one. 
I'm working on an app forwarder for the Wii U menu, so I wanted to be sure to use the correct branding.

I understand that the ufo logo is official (the one radius posted) does the RetroArch name has a special typography?

**Comment by twinaphex** [comment]
Hi there, you're going to help us fix this issue with it crashing at startup or whatever they are talking about on gbatemp? That'd be cool. This is going to be through that forwarder?

I'd say just use the logo for now that is just the invader, no text.
