### ISSUE TITLE
Can't bind backspace key

### ISSUE THREAD

**Issue by Vip3rNZ** [libretro/RetroArch#5282]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I'm setting up the key bindings for my game pad and for some reason I can't bnd the backspace key (the key i use to return to submenu) meaning i can't navigate the menu without ahving to use the keyboard to go back to previous menu

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
If you don't want to use your keyboard for navigation, go to settings > input > unified menu controls ON. This goes back to RetroArch's old behavior of controlling everything through the retropad controls.

**Comment by zoltanvb** [comment]
Very old bug, but binding the backspace is possible nowadays (just tested) without changing to unified menu controls.

**Comment by hizzlekizzle** [comment]
So this can be closed? If so, and OP is still around, would you mind doing the honors?
