### ISSUE TITLE
(Menu) Grab Mouse Toggle Unbindable

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5291]
## Description

The Grab Mouse Toggle key is hardcoded as F11. If you rebind it in the settings, it's still set as F11.

### Expected behavior

You should be able to re-bind the Grab Mouse Toggle button.

### Actual behavior

After re-binding the Grab Mouse Toggle button, it still uses F11 as the Grab Mouse button.

### Steps to reproduce the bug

1. Goto the Input settings
2. Rebind Grab Mouse Button from F11 to "]" rightbracket
3. Try pressing ] to grab mouse.... Fail
4. Try with F11, see if grabs the mouse

### Bisect Results

You'll find [in menu_event.c](https://github.com/libretro/RetroArch/blob/master/menu/menu_event.c#L311-L315), it's hardcoded to F11:

```
   if (menu_event_kb_is_set(RETROK_F11))
   {
      command_event(CMD_EVENT_GRAB_MOUSE_TOGGLE, NULL);
      menu_event_kb_set_internal(RETROK_F11, 0);
   }
```

**Comment by Ferk** [comment]
Personally, I think it should rather be a ``core -> controls`` option. And have the mouse grabbed only while the core is playing (ie. automatically ungrab while on the menu)

**Comment by orbea** [comment]
I can still reproduce this, the problem is currently here.

https://github.com/libretro/RetroArch/blob/ab2010c4940db91278ae2f0ca88c13e55e3f2065/menu/menu_input.c#L337

**Comment by RobLoach** [comment]
@ToadKing Thanks for fixing this up in https://github.com/libretro/RetroArch/pull/10027 ! :+1:
