### ISSUE TITLE
1.6.4 PS Vita - Online Updater - Thumbnails Updater fails

### ISSUE THREAD

**Issue by futurepr0n** [libretro/RetroArch#5293]
## Description
Using Retroarch 1.6.4 for PS Vita, Thumbnails Updater fails. 

### Expected behavior

Thumbnails Updater should download and extract selected thumbnails to directory 

### Actual behavior

Thumbnails download will get to about 50%, than restart itself - showing text indicating 0% before finally failing with 'Task Failed'.

Tested with Mega Drive, Nintendo - Nintendo Entertainment System, Super Nintendo, Master System..

### Steps to reproduce the bug

1. Navigate to Online Updater
2. Select Thumbnails Updater - and any thumbnails pack
3. Task will fail.

### Version/Commit
Latest

- RetroArch: [version/commit]

### Environment information

- OS: [PSVita ]
- Compiler: [Precompiled Buildbot]

**Comment by RobLoach** [comment]
How big is your drive?

**Comment by futurepr0n** [comment]
I am using a 32GB memory card, that has approx 3GB free. I manually downloaded the thumbs for Genesis on my PC version of Retroarch, and ftp'd them into the thumbnails dir on the vita - they loaded up fine after retroarch launched, but the downloading failed no matter what pack I selected.

Is there a requirement for a specific amount of free disk? also I looked around but couldnt find any sort of log. Is there a way I can enable one from the UI and then provide it or analyze it myself to see whether I can contribute to a fix?

I believe I saw someone else having this issue on a subreddit, so its possible im not alone.

**Comment by bparker06** [comment]
The downloader has been very slow for people lately, so it's not uncommon for it to fail/timeout halfway. It may be easier to download it from a PC first, with something that can resume a failed download, in order to get it successfully.

**Comment by futurepr0n** [comment]
cool - I noticed the SNES covers took forever to dowload (on my pc) but the other genesis, master system, they were fine/fast. So im not sure, but it might be different then just a timeout issue. As mentioned, the Downloads start, goes up to about 50% (and not slow), then appears to restart to 0% and all a sudden fail as "task failed".

I have the capacity to support download and extracting of the zip. So I wonder whats up... is there a timeout written into the function? Something I could try changing , recompiling and testing?

**Comment by futurepr0n** [comment]
Someone on Reddit believes this might be related to a memory limitation on vita - but I think they are on the wrong track with everything else - https://www.reddit.com/r/vitahacks/comments/6trqjr/might_make_a_retroarch_playlist_generator_if_one/ - it looks like they are aiming to try and modify a playlist builder that doesn't use the same rom check as the standard one. Thats a whole nother story -- but could the vita memory be a limitation for how it downloads/caches and extracts the thumbnails?

Again - I know you guys are super busy, so any sort of leads you can direct me towards, I'll happily explore on my own to see whether or not I can help to fix the issue. 

thanks!

**Comment by Calistex** [comment]
Tested this on 1.10.3, seems working fine
