### ISSUE TITLE
Stop distributing retroarch.cfg with retroarch

### ISSUE THREAD

**Issue by dafzor** [libretro/RetroArch#5299]
Retroarch setup is not the simplest and users can take quite some time to get it to a state they're happy with.

However by including retroarch.cfg in the distributed package it makes it way too easy to lose all that work by simply overwriting the user settings, it also means any users updating will always need to be aware not to extract retroarch.cfg when updating.

So Retroarch should no longer include retroarch.cfg in any package it distributes. For the case of a new install Retroarch should simply use the included retroarch.default.cfg to create a new retroarch.cfg

**Comment by fr500** [comment]
It's actually no longer needed, I just haven't had the time to remove it from the buildbot script.

We don't bundle the cfg on nightlies nowadays though, just in the full pack
The platform driver now provides the adequate defaults since https://github.com/libretro/RetroArch/pull/5250

**Comment by orbea** [comment]
This is useful for distros to set global defaults, but I suppose there could be better solutions to be able to overwrite default settings while still allowing users to later overwrite them again.

**Comment by RobLoach** [comment]
I just see `retroarch.default.cfg` in there now. Feel free to re-open this if I'm wrong.

**Comment by dafzor** [comment]
Ye it's been fixed for a while, thanks for closing the bug totally forgot.
