### ISSUE TITLE
RetroArch latest nightly bug.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#5300]
In Android latest nightly you can not change the overlay preset for some reason, when you select one nothing changes, tested on 2 different android devices with jellybean and android 7.

**Comment by twinaphex** [comment]
My bad, it was a regression.

Should be fixed with this commit - 

https://github.com/libretro/RetroArch/commit/950264e89e88bfb96b2f5af88219876b5a87b4f9

**Comment by blackman91** [comment]
Confirmed fixed in latest nightly, great job guys as always.
