### ISSUE TITLE
Retroarch > User Interface > Views

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#5302]
- [ ] #

 First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

**Main Menu tabs not hiding properly when toggled.**

### Expected behavior

**Admittedly new to retroarch but unless I am misunderstanding the function, toggling off a setting such as "Show Image Tab" should remove the Image tab from the main menu/interface entirely.**

### Actual behavior

**Regardless of which ones I toggle, or whether I close/re-open the emulator.  They stay on the main menu.  This is with a brand new fresh 1.6.4**

### Steps to reproduce the bug

**1. Navigate to User Interface > Views > Show Image/Music/Video Tab
2. Toggle from the default On to Off.
3. Use backspace or corresponding key to return to Main menu and tabs are still present.**

### Bisect Results

**Since I installed it and began sifting through/configuring.**

### Version/Commit
You can find this information under Information/System Information

- RetroArch: **1.6.4**

### Environment information

- OS: **Windows 10 Pro x64**
- Compiler: **N/A**

**Comment by RobLoach** [comment]
It doesn't refresh automatically. You'll have to close RetroArch, and re-open.

**Comment by klepp0906** [comment]
Yes I did that with no luck.  Let me try restarting the pc I suppose :p

Thanks for the reply!

**Comment by RobLoach** [comment]
What's in your retroarch.cfg?

**Comment by klepp0906** [comment]
thank you again for the reply(ies)!  It seems restarting the pc for whatever reason did the trick.  No idea why that was necessary but i'll take it :P
