### ISSUE TITLE
[Wii U] RPX/ELF loader does not clear BSS segment, causing crash

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#5304]
**Description**
Changing cores, whether via the auto detect core method, or  manually choosing a core in the menu in rapid succession, will cause the emulator to completely crash with a DSI exception error, forcing the user to hard reboot.  Main Genesis Plus programmer Ekeeke confirmed this to be an error in how
the BSS segment is not being cleared in the RPX/ELF loading. 

Posted about 72 hours ago: 
https://github.com/libretro/Genesis-Plus-GX/issues/94 (his comment is towards the bottom of the page). 

**Expected behavior**
What should occur is being able to change the cores, ROMs, etc in rapid succession without any the DSI error lockups. 

**Actual behavior**
Loading the RetroArch RPX via homebrew launcher, loading up the main app works fine. But loading a core to another, or multiple cores in rapid succession (spam-loading them back to back) causes this at random. 

**Steps to reproduce the bug**
1. Load main app via HBL.
2. Load any core, and then swap cores manually or automatically in rapid succession
3. At some point after spam-loading cores, you should encounter one of these or similar

Follow these steps from user Ploggy:
"I managed to get through Amstrad, Atari 2600, Atari ST, WonderSwan, C64, C16, then got my first new DSI Error with FBA....
After a restart it went from FBA, mame, TurboGrafx, then got a 160 - 2203 Memory error loading GBA...
After a restart loaded GBA, GBC, GB, NES, SNES Memory error loading a second SNES rom.
After a restart loaded SNES, Master System, NEOGEO Pocket and Gens (which worked)!"

Load a core, then two games, load another core, repeat. 

errors. 
![34543534sdf324](https://user-images.githubusercontent.com/15101626/29327057-0ab3c390-81ab-11e7-92b9-f65895678f4c.jpg)
![29102615-a9d943e8-7c77-11e7-9c3d-cf3f4af5cb6e](https://user-images.githubusercontent.com/15101626/29327062-0f224906-81ab-11e7-82b1-c4034d2f29b0.jpg)

**Bisect Results**
Since version 1.6.4 official, this has been occurring. 

**Version/Commit**
- RetroArch: 1.6.4

**Environment information**
- OS: Wii U system 5.5.1
- Loaded with Haxchi + CFW/sigpatches enabled (for the sake of USB support and for faster SD read/write times).

**Comment by QuarkTheAwesome** [comment]
I'm actually not sure about the merits of the whole .bss thing. The issues in GenPlusGX later turned out to be a result of using the wrong malloc, while the DSIs screencapped here haven't been linked to .bss yet, and could be completely unrelated errors. HBL elves actually do get their .bss segments cleared (by SD_loader) and I think it's pretty safe to assume that Nintendo's RPX loader does the same. It just doesn't happen inside the application.
A caveat to this is whatever goes on inside hbl.c. I really can't make sense of it, and while it doesn't seem to have a full ELF loader; how it works is still a mystery to me. There could be something I'm overlooking in there.

**Comment by roflcopter777** [comment]
So this report was in vain, perhaps? Should I record a video of me loading up RetroArch and spam loading the cores until I get an error? I'm not sure what more I can do. Ugh.  :(

**Comment by Ploggy** [comment]
I can only go by observations and the fact the crash doesn't occur when I use Brienj's Channel, from what I remember it used ELF/RPX Code? not 100% sure though.
The Bss stuff maybe a false lead.. :(

I'll have to see if I can trigger the crash again..

**Comment by cucholix** [comment]
I extracted the rpx file from brienj channel
[retroarch_launcher.zip](https://github.com/libretro/RetroArch/files/1226967/retroarch_launcher.zip)

It would be interesting test the rpx under HBL and see if it has problems or not.

**Comment by roflcopter777** [comment]
Where do we go from here though, is what I want know. Like, these DSI codes I know are tricky to debug and found out the route cause for. I do feel a bit, how you say, silly, for reporting on this "bug".
