### ISSUE TITLE
[iOS] Crash during the core choice for a Playlist Game

### ISSUE THREAD

**Issue by Alex793** [libretro/RetroArch#5309]
Hello guys, I don't know which build exactly is, but something added between the iOS stable compiled 1.6.4 build from the 8th August* and the 11th August iOS compiled build introduced a big issue.

*The 1.6.4 stable compiled build is OK

The issue is still here on last 1.6.5 nightlies.

## Description

When using the XMB driver RetroArch simply crash 99% of the time when we choose the core for a game we never launched in the Playlist.

When we relaunch RetroArch the core for this new launched game is well added, but it's not a big deal when we launch for the first time an other game from the playlist, it's 99% a crash.

For the crash, it's just after the moment we chose the core for a game we never launched, sometime we have the time to see then next screen (Run, Informations etc.) then instant crash...

### Expected behavior

Just chose the core for a game we launch for the first time without a crash when using XMB.

### Steps to reproduce the bug

0. Use the XMB driver
1. Add some new games in the Playlist
2. Chose a game you never launched
3. Now you have the screen with the core choice
4. Chose a core
5. Crash*
6. *If no crash, do it again and it will happen

### Bisect Results

Between the iOS stable compiled 1.6.4 build from the 08th August* and the 11th August iOS compiled build.

*The Stable 1.6.4 release is OK no crash.

### Environment information

- OS: iOS 9 and 10
- Tested with my config and also a blank config
- Jailbreaked

PS : Sorry I'm French so my English is not perfect to well describe an issue.

**Comment by twinaphex** [comment]
@yoshisuga Could you help us here?

**Comment by Alex793** [comment]
If it can help I'll try to post a debug screen from Xcode when the crash occurs.

**Comment by twinaphex** [comment]
Go ahead.

**Comment by Alex793** [comment]
Sorry a big correction, it happen only when using the XMB driver, no problem with NULL driver.

**Comment by twinaphex** [comment]
Try to do a git pull from the latest source - @heuripedes pushed a bugfix for a crash - this might be what you were running into.

**Comment by Alex793** [comment]
My last pull was this night at 2.30am GMT+1.

**Comment by Alex793** [comment]
You're right ! It's fixed with @heuripedes fix.

Arf if pulled 30 minutes later lol

I have this issue since few days and the day I pull bam a fix 30 minutes later lol

Thanks @twinaphex and @heuripedes for the fix.

**Comment by twinaphex** [comment]
No problem.
