### ISSUE TITLE
[Feature Request] "Recently played games" option in main menu

### ISSUE THREAD

**Issue by molul** [libretro/RetroArch#5313]
I'm not sure if I can post feature requests here, so my apologies if it's not the case.

I've been using Retroarch for a few months and there are a few issues regarding the interface that I think could be improved. One of them is adding a "Recently played games" option in the main menu, so I don't have to go through the "Load content"->(Search for the game either in the Collections or browsing my Android tablet's directories) process. Just go to "Recent games", then click on the game I was playing in my last session.

Thanks in advance :)

**Comment by hizzlekizzle** [comment]
The built-in 'history' playlist does exactly this.

**Comment by molul** [comment]
Oh, I didn't notice that. Thank you! And sorry too ^_^U

El 16 ago. 2017 3:08 p. m., "hizzlekizzle" <notifications@github.com>
escribió:

The built-in 'history' playlist does exactly this.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/libretro/RetroArch/issues/5313#issuecomment-322765028>,
or mute the thread
