### ISSUE TITLE
Stuttering on nes games -psvita

### ISSUE THREAD

**Issue by four20spud** [libretro/RetroArch#5317]
Using retroarch on the psvita, Have check to make sure its not a core issue but one to do with retroarch by testing all the cores and the problem persists. 
retroarch git version:47cf178
Compiler:(6.2.0) 32-bit 

[Description of the bug]
When playing Pal games on the NES there is a persistent  stuttering and graphical glitch when the screen is scrolling fast and there is a few sprites on screen, while this happens the sound also has a stutter.
while this happens the fps stays consistent witch makes me think its a refresh rate issue.
I have tried to use the in built menu to change this like turning of vsync ect, but no matter what option int he quick menu or video menu I use will change this.
Because the PAL version of the NES run at 50Hz i tried a NTSC version of the same rom and it worked alot better witch makes me think I was right with it being a refresh rate issue.

[Steps to reproduce the bug}

1. run super mario on the nes retroarch for ps vita
2. in world 2-1 after the first pipe run along the ? blocks as fast as you can and shoot fire until the next pipe

this happens alot throughout the game but that is the only spot I can reproduce the issue consistently.

**Comment by fr500** [comment]
Well the VITA screen is 60hz and you're playing PAL games, it's only normal that this happens.

**Comment by four20spud** [comment]
the ntsc version does it a little bit not no where near as bad. is there no way to resolve any of these issues? liek this doesnt happen when playing nes games on my computer and its screen is running a 60HZ

**Comment by fr500** [comment]
I don't see how, this will always happen even if you're running one frame below vsync it will happen.
It's not really stutter, more like judder and really apparent in panning sections.

It happens in everything from games to movies to sports. If you run at a different framerate you have to compensate at some point.

One really noticeable example, try watching batman begins, the scene were he's dropped by the mountains at 60hz, there is ugly noticeable judder. Unless your screen supports 24p you'll get the same effect no matter what.
