### ISSUE TITLE
Regression: Scan Directory doesn't work

### ISSUE THREAD

**Issue by FayneAldan** [libretro/RetroArch#5319]
## Description

Scan Directory has broken in the latest update (version below).

### Expected behavior

Scan Directory should work, as it did in the previous version. 

### Actual behavior

Directory scanning immediately finishes, regardless of the directory's content, and doesn't add any content to the playlists. 

### Steps to reproduce the bug

1. Scan a directory
2. Observe

### Bisect Results

This started happening in the latest update (below).

### Version/Commit

- RetroArch: 1.6.6/e3818d5

### Environment information

- OS: Both Windows 10 and Android 7.0

**Comment by retro-wertz** [comment]
i thought it was just me...

**Comment by RobLoach** [comment]
What are you scanning? Have some CRCs of files you're going through?

**Comment by FayneAldan** [comment]
I tried scanning both Cave Story from the Content Downloader and 17 different PSX ROMs. Normally PSX ROMs take quite a while to scan, considering their size, but as I said: Scanning finishes instantly with no results.

**Comment by bparker06** [comment]
Scanning is 100% broken for me as well, but it doesn't "immediately finish", it just acts like I never pressed enter on the "scan this directory" entry, so nothing happens.

**Comment by FayneAldan** [comment]
I noticed the doing nothing behavior on mobile, but the instantly finishing behavior on PC.

**Comment by bparker06** [comment]
Interesting, I'm on a Linux PC here.

**Comment by RobLoach** [comment]
@bparker06 Same result here. Hit "<Scan Directory>", nothing happens. Confirmed with @retro-wertz on https://github.com/libretro/RetroArch/commit/887364062a857c9052d7ce8a2616dcb67ba5f001 .....

## https://github.com/libretro/RetroArch/commit/d1f0f19824a056acae93c4ebea0dcf9140157e95
```
git checkout d1f0f19824a056acae93c4ebea0dcf9140157e95
make clean
make
```
Works.

## https://github.com/libretro/RetroArch/commit/887364062a857c9052d7ce8a2616dcb67ba5f001
```
git checkout 887364062a857c9052d7ce8a2616dcb67ba5f001
make clean
make
```
Does not work.

**Comment by RobLoach** [comment]
Fixed in https://github.com/libretro/RetroArch/commit/33a2d58891b21ecf5758e4d16ecbfb56a238e28f .

**Comment by twinaphex** [comment]
I will be pushing 1.6.7 later today.
