### ISSUE TITLE
[Android] Picodrive core can't be loaded, and can't also delete it

### ISSUE THREAD

**Issue by molul** [libretro/RetroArch#5323]
On 1.6.4 and 1.6.6, Picodrive core has stopped working. I try loading it and I get an error. Any other core works perfectly.

I thought of removing and reinstalling (updating and downloading didn't help), but I can only delete a core if I load it.

I know this issue tracker is not meant for cores but I don't know if this is a core or Retroarch's problem.

**Comment by bparker06** [comment]
I believe Picodrive does not currently load on Android 6.0 or newer due to [this issue](https://issuetracker.google.com/issues/37067983), it is not technically a RetroArch problem.

**Comment by molul** [comment]
Oh, I see. Thank you very much. I guess this can be closed now :)
