### ISSUE TITLE
[Feature Request] Optional background color for status messages

### ISSUE THREAD

**Issue by milesrotaru** [libretro/RetroArch#5328]
I didn't have any problem with the way status messages look until I started using achievements. They can be pretty illegible or easy to miss against certain game scenes. A dark background for them would be great.

**Comment by milesrotaru** [comment]
By the way I put $15 on this.

**Comment by ofry** [comment]
I think it should be part of #4867

**Comment by ofry** [comment]
or this?

#3946

**Comment by milesrotaru** [comment]
That would make sense but I figure this is easy enough to be the first step, or even just a temporary fix.

**Comment by meleu** [comment]
a dark background with a touch of transparency would be really neat! :)

**Comment by FayneAldan** [comment]
I was actually thinking that the Onscreen Notifications (or at least achievements) could get some more attention, like how Xbox does it. Notifications could be accompanied by a sound and a small animation, along with icons. Maybe we could model them after Steam's big picture overlay notifications. I was also thinking that downloads should appear as actual progress bars in the corner, especially considering that the Onscreen Notifications start "freaking out" if you download multiple files at once.

**Comment by FayneAldan** [comment]
I honestly feel like this might be worth a higher bounty if expanded upon how I explained.

**Comment by milesrotaru** [comment]
Bounty increased to $30.

**Comment by bparker06** [comment]
What are the actual requirements for this bounty? If I'm not mistaken, this would have to be implemented separately for each font renderer. Are there certain ones that it must work on?

**Comment by milesrotaru** [comment]
To collect the increased bounty I'll be satisfied with:

1. Just add a background to the text for legibility improvement, as per the original request

2. Any one or more of the ideas suggested by FayneAldan, but I'll let that go if none of them are reasonably doable without overhauling something.

Really all I want is to not miss achievements when they appear. Anything toward that goal is much appreciated.

**Comment by bparker06** [comment]
@milesrotaru For which font drivers must this be added to?

**Comment by milesrotaru** [comment]
@bparker06 Are you asking about menu drivers or video drivers?

**Comment by bparker06** [comment]
I'm asking about the font drivers here:

https://github.com/libretro/RetroArch/tree/master/gfx/drivers_font

Each one implements rendering of the OSD text separately, so they'd all have to be changed, unless you have a minimum requirement for a smaller number of them to be implemented in order to satisfy the bounty (I doubt you'd ever get a single person to do even most of them anyways).

**Comment by milesrotaru** [comment]
@bparker06

I see. I'm guessing gl_raster_font is the most commonly used one after d3d_w32. Is that correct? If you were only up for one or two of them which do you think would be best to work on?

**Comment by bparker06** [comment]
I think GL would be the most common.

**Comment by milesrotaru** [comment]
@bparker06 Alright I'm starting to see what this will involve. Forget Fayne's suggestions for now. Do you think adding the optional background color to the two most commonly used font renderers is a reasonable goal for the bounty?

**Comment by bparker06** [comment]
I don't think it's reasonable to require d3d too, it's also only very rarely used instead of GL, and the number of people around here familiar enough with d3d is much smaller as well.

**Comment by milesrotaru** [comment]
Ok. GL would be a good start. I'm not gonna be too picky about the bounty.

**Comment by alexsandervs** [comment]
Hi guys,
I would like to share my setup for screen notifications o retroarch. I use collegiate font.ttf and I got great results on mesages

![img_20170913_022348](https://user-images.githubusercontent.com/19491930/30360884-6605aea8-982a-11e7-8e5a-670e718f470a.jpg)

**Comment by meleu** [comment]
@alexsandervs not exactly solve the issue, but it's a nice workaround! Thanks for sharing. :-)

**Comment by bparker06** [comment]
@milesrotaru Just FYI I've been working on this, and I think I have something usable now:

Plain background:

![100](https://i.imgur.com/hb3F5sB.png)

50% transparency:

![50](https://i.imgur.com/N9sw0vD.png)

If this is acceptable, all that I have left to do is hook it up to the menu settings.

**Comment by meleu** [comment]
I liked it. Are the background  color and transparency configuerable?

**Comment by bparker06** [comment]
@meleu Yes they are. I just opened a PR for this.
