### ISSUE TITLE
No psx roms found after scanning

### ISSUE THREAD

**Issue by RaydenX93** [libretro/RetroArch#5329]
## Description

After choosing the directory in which my roms are found, I press "Scan directory" and immediately after the message "Scanning of directory finised" but nothing is found. It looks like it doesn't even start scanning,

### Expected behavior

Roms should be found.

### Actual behavior

Nothing is found.

### Steps to reproduce the bug

1. "Import COntent" -> "Scan Directory" -> Go to my rom directory -> "<Scan this directory>"

### Bisect Results

There were no problem with RA 1.6.4. After updating to 1.6.6 this happened.

### Version/Commit

- RetroArch: 1.6.6 e3818d5

### Environment information

- OS: Windows 10 Pro x64

**Comment by hizzlekizzle** [comment]
It's a known issue that's fixed in the nightlies. We'll be pushing out a 1.6.7 bugfix release in the next day or two to address it, but in the meantime, just fetch a nightly build from buildbot.libretro.com and overwrite the executable from the 1.6.6 release with the nightly build.

**Comment by twinaphex** [comment]
If I could actually get the buildbot to churn out releases instead of these continuous issues, this would already have ceased being an issue yesterday.

**Comment by RaydenX93** [comment]
Fixed in 1.6.7
