### ISSUE TITLE
missing 50% cores into retroarch 1.6.7

### ISSUE THREAD

**Issue by Bighitti** [libretro/RetroArch#5335]
i downloaded new version but when i go to download cores,it miss 50% cores to dowload i have tried to uninstall it e reinstall 5 times but has the same issue.

**Comment by bparker06** [comment]
Please don't remove the default text on new issues, it specifically asks for all the proper info we need, none of which you have provided.

**Comment by JesterIOS** [comment]
PS VITA, RetroArch 1.6.7 > Load core (Available only 6 core's)
![2017-08-19-221233](https://user-images.githubusercontent.com/30769120/29487957-5e0c4de8-850a-11e7-9f48-8810ca0d8fb7.png)

**Comment by meleu** [comment]
@twinaphex I think this issue can be closed. It's known that Vita port doesn't accept installing cores via Core Updater.
