### ISSUE TITLE
3DS: Recently played list not working

### ISSUE THREAD

**Issue by Clydefrosch22** [libretro/RetroArch#5337]
The list worked back during 1.4 but since I updated to 1.6, 1.6.6 and 1.6.7 it doesn't update anymore.
It just remains empty.

**Comment by RobLoach** [comment]
What SD card are you using? Where's the playlist directory set to?

**Comment by Clydefrosch22** [comment]
It's a class 10 sandisk micro sd card.
The playlist directory according to the Directory menu is sdmc://retroarch/cores/playlists

Going into the Load Recent option after loading games displays an empty list saying 'No playlist entries available'.

It definitely worked in the past, on 1.3.6 and versions of 1.4, I can't pinpoint when it actually stopped working though.

**Comment by Ferk** [comment]
I had this problem with 1.6.1, I recently completely deleted the retroarch folder and CIA and reinstalled 1.6.7 and then it started working for me.

Also back then I was unable to scan and add content to the playlists from retroarch.

**Comment by Clydefrosch22** [comment]
I usually do that for every new version. i copy the savefiles, savestates and system folder (for bios files), then delete everything, copy the new retroarch folder to sd and then copy the three saved folders back into the cores folder.

i just deleted the playlists folder, but it was quickly created again

you're right, I didn't notice until now, but upon loading a game, on the lower screen, it does say 
[ERROR] cannot push NULL or empty core name into the playlist.

**Comment by Ferk** [comment]
When you go to "Load Core" do you get the list of cores?

Back when I was having the same problem, instead of the list of cores loaded I got a file-selection interface, and I couldn't load any core from it. 

After the reinstall that fixed my problem I can see the list of installed cores. I'm assuming you always launch the cores using their specific CIA and cannot load them using the Retroarch.cia, for me this was also fixed after the reinstallation I did. I'm not sure what did I do to get it fixed, honestly.

**Comment by E-Block** [comment]
I'm having the same issue w/ 1.6.7, but I didn't have this problem with 1.6. Like Ferk said, I get the file-browsing interface when trying to select a core in addition to not being able to create playlists. I tried reinstalling but it didn't work.

**Comment by Clydefrosch22** [comment]
Ok, that seems to have fixed that.
The path before was simply 'none'.

However, it took a while for the config to be saved and remain applied for some reason, i had to set the path 5 times, save config and quit retroarch over and over before it would finally stick

**Comment by gingerbeardman** [comment]
This can be closed as it is resolved.

**Comment by orbea** [comment]
As explained in the previous comments this is resolved so I am going to close this and seems to have been a configuration issue with the core directory path setting.
