### ISSUE TITLE
[XMB Request] Retain Playlist Cursor Position

### ISSUE THREAD

**Issue by brianblakely** [libretro/RetroArch#5344]
## Description

Collection playlists can contain hundreds or thousands of items.  When scrolling through one, pressing left or right by accident can be common.  This resets the playlist to the top.

### Expected behavior

Playlist position should never reset until RetroArch is quit.

### Actual behavior

Playlist position resets whenever you browse away from it.

### Steps to reproduce the bug

1. Navigate to any playlist (such as a collection).
2. Scroll a few pages down.
3. Navigate left or right.
4. Return to playlist.
5. The playlist position is reset to top.

### Bisect Results

To my knowledge, this has always been the case in XMB.

### Version/Commit

- RetroArch: 1.6.7 / Git 2ff6bee

### Environment information

- OS: Windows 10

**Comment by Kivutar** [comment]
I'd like to do this yes. We need to store the position somewhere. We could save it in the playlist struct, but then it wouldn't work on settings. We could save it in the menu_list struct, but it's cleared all the time and the position would be lost.

**Comment by brianblakely** [comment]
FWIW, this is only a debilitating issue in playlists.  The list of top-level settings is very small, and inner-level settings lists only page-up/down when left and right are pressed, so the issue is not present.

**Comment by heuripedes** [comment]
This is related to #5342

**Comment by markwkidd** [comment]
This would be such an improvement. I have gotten pretty used to not bumping left or right, but guests unfamiliar with RetroArch/xmb still make the mistake of hitting left or right frequently. Very frustrating on a long playlist, like MAME.
