### ISSUE TITLE
(Achievements) Allow using RetroAchievements without an account

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#5363]
Playing with achievements but not syncing them online or having an account should be an option.

**Comment by menelkir** [comment]
I think this is a retroachievements.org requirement.

**Comment by fr500** [comment]
Where would you get the achievement list from?

**Comment by menelkir** [comment]
Retroarch connects to retroachievements.org site using the API (from the
site itself).

**Comment by fr500** [comment]
I mean to use it without an account

**Comment by retro-wertz** [comment]
how would it connect without an account?

**Comment by menelkir** [comment]
Retroachievements.org doesn't permit that, the requirement is inside his
API. Retroarch doesn't administrate the achievements.
This is probably an issue to be addressed to the site instead of retroarch,
unless retroarch decides to not use this API anymore.

**Comment by meepingsnesroms** [comment]
We could still use there achievement list, only one person with an account needs to login and download them to export a .dat with all the achievements.

I will also look at the achievements API and see if I can separate the login from the data download.

**Comment by meepingsnesroms** [comment]
Well the login is sent to a php program and it returns the data or `{"Success":false,"Error":"Credentials invalid (0)"}`
So a login is required, but a public account should work as long as they cant reset the password.

The password should be safe even if it is public since it wont be linked to any users email address and you usually have to click a link in an email to reset a password.

**Comment by bparker06** [comment]
Has anyone read their TOS to see if this is allowed? Distributing the cheevos data without going through the API that is?

**Comment by meleu** [comment]
I can't see any benefit with such feature.

**Comment by meleu** [comment]
In order to play with RetroAchievements content, you need to be logged in.

Closing this issue.
