### ISSUE TITLE
[Request] Include screen shot with save state

### ISSUE THREAD

**Issue by mrsilver76** [libretro/RetroArch#5368]
When you save a state, it would be really nice if retroarch also saves a screen shot at that moment in time. 

When browsing save states, that screen shot should also be displayed to help you understand the context of the state.

**Comment by RobLoach** [comment]
Savestate Thumbnails is already in there. Just need to enable it.

![screenshot at 2017-08-23 09-17-05](https://user-images.githubusercontent.com/25086/29617734-daa4f554-87e3-11e7-9969-e1aedf4af5dc.png)

**Comment by mrsilver76** [comment]
Fantastic, I must have missed that when I was hunting through the settings. Thank you!
