### ISSUE TITLE
RetroArch flickers black on arm mali gpus

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#5378]
When scrolling downward and loading new entrys in XMB menu the screen flickers black on mali gpus.
https://youtu.be/GM_Ur6egT8E

I also have a cheap chinese klu tablet that also does this, it also has a mali gpu.

RetroArch v1.6.7 nightly Aug 26 2017
Android 5.1.1, LineageOS 12.1
Kindle fire 5th gen

**Comment by bparker06** [comment]
My android device with a Mali GPU does not exhibit this issue, but I have noticed it on a Famicom Mini when using XMB. This is the first time I've seen a report in the wild about it though... perhaps it is a bug in a certain version of the Mali driver or something.

**Comment by sergiobenrocha2** [comment]
I have that too, Odroid U3

**Comment by ensra** [comment]
Are you all running Android? There's flickering on Linux with mali-fbdev but only when using keyboard input since the input also goes to the console which then tries to draw on the screen.

**Comment by ensra** [comment]
On Linux there's a similar? problem when using mali-fbdev with keyboard input. Key presses also go to the console which then tries to draw an input line on the screen causing RetroArch to flicker.

**Comment by sergiobenrocha2** [comment]
It's running on top of Xorg (Mate desktop), happens with keyboard & joystick

**Comment by bparker06** [comment]
@ensra on NES Mini there is no keyboard or X, just gamepad with mali-fbdev and it still flickers, but only with XMB; rgui is not affected.

**Comment by meepingsnesroms** [comment]
@bparker06 You are right, I switched to rgui on the Amazon Fire for now and it works fine.

**Comment by twinaphex** [comment]
Hopefully the commit we just pushed should fix this.

**Comment by meepingsnesroms** [comment]
Its fixed on my device.

**Comment by twinaphex** [comment]
Ah, that's great news to hear!
