### ISSUE TITLE
support to CIFS volumes.

### ISSUE THREAD

**Issue by ricardo85x** [libretro/RetroArch#538]
Today it very hard to have a device with cifs support on kernel.
But many file managers support CIFS. 

So it would be a great PLUS to have support to run your roms from a CIFS volume(NAS).

**Comment by frankzzz** [comment]
Using Retroarch on an Android TV device (shield) right now, and this would be a very useful feature.  There is no way to do this without rooting or manually syncing files back and forth right now.

To draw another analogy, if Kodi couldnt mount samba volumes, it would be useless on most of the devices I run it on (android/ios devices, specifically).

**Comment by fr500** [comment]
hmmm I can't mount cifs on kodi android...

**Comment by fr500** [comment]
Anyway we'd need a portable, open source, complete cifs library written in C to even get started

**Comment by deviant-studio** [comment]
I'm suffering with Android TV Box too. 
Almost all modern android video players support samba protocol. Kodi, VLC, also bunch of file managers like X-Plorer, CX File Explorer etc.
I don't see any reason why similar feature can't be implemented at least as pluggable module.
It's not a problem to mount samba resource on the desktop OS like Windows or Ubuntu. But it is real pain in the ass to create mount point in Android. Now i forced to copy/paste whole ROMs set into tvbox local storage. This is the only local content i have. Everything else (movies, photos, music) is stored in the NAS.
