### ISSUE TITLE
No audio Retroarch live PC Build

### ISSUE THREAD

**Issue by ejsymonds** [libretro/RetroArch#5380]
Hi everyone,

I'm unable to get any audio output. I'm completely new to Retroarch so please bear with me...

I've installed Lakka/Retroarch on a a PC as a live version, no other OS. It is the newest stable build: Date April 24 17, Git version 2a13af5.

Video output is VGA and there are no HDMI ports on this system so it's not that. Using a standard 3.5mm jack for output. I've tried the following audio drivers: alsa, alsathread, oss. No luck on any of them. I've tried changing the audio device in SSH and get "not found" for every device I try. 

Anyone have any ideas on how to fix this?

LOG:

Lakka:~ # aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=NVidia
    HDA NVidia, ALC1200 Analog
    Default Audio Device
sysdefault:CARD=NVidia
    HDA NVidia, ALC1200 Analog
    Default Audio Device
front:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Analog
    Front speakers
surround21:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=NVidia,DEV=0
    HDA NVidia, ALC1200 Digital
    IEC958 (S/PDIF) Digital Audio Output

**Comment by gouchi** [comment]
Please try to check if you reproduce your issue with [Lakka 2.1 rc4 ](http://le.builds.lakka.tv/Generic.x86_64/Lakka-Generic.x86_64-2.1-rc4.img.gz)and you [can switch audio from the gui](http://www.lakka.tv/doc/Audio-settings/#switching-audio-device-from-the-gui).

**Comment by ejsymonds** [comment]
That's the version I'm already running. When I attempt to switch the audio I get the "not found" error

**Comment by ejsymonds** [comment]
Nevermind, Solved. 

Had to change the sample rate to 44100, switched the driver to "hw0,0" (read from below thread) and problem solved. 

https://pirraste.wordpress.com/2014/02/28/retroarch-alsa-audio-over-hdmi-working/
