### ISSUE TITLE
Audio DSP Plugin issue

### ISSUE THREAD

**Issue by MitsuriZX** [libretro/RetroArch#5389]
## Description

While using RetroArch 1.6.7, Audio DSP Plugins are not selectable.

### Expected behavior

Selecting the Audio DSP Plugin option in the Audio settings of RetroArch and then selecting a DSP Plugin should showcase that plugin as selected to the right of Audio DSP Plugin, and all games should be affected by that plugin.

### Actual behavior

Selecting the Audio DSP Plugin yields no results, nothing changes, the field to the right of Audio DSP Plugin stays empty. The audio of every game does not change.

### Steps to reproduce the bug

1. Open RetroArch.exe
2. Navigate to the Audio options.
3. Select Audio DSP Plugins.
4. Select any plugin.

### Bisect Results

This started happening after I updated from RetroArch 1.6.5 to RetroArch 1.6.7. Also of note is, even if I manually insert the desired plugin into the RetroArch.cfg in the proper field, despite the fact that the plugin shows in the Audio DSP Plugin field and despite the fact that there are no errors, the game audio is not changed.

### Version/Commit

- RetroArch 1.6.7
- Build Date is Aug 12 2017
- Git Version is a235c0b

### Environment information

- OS: Windows 10 Pro, 64-bits.

**Comment by retro-wertz** [comment]
i can confim this with RA 1.6.5 and 1.6.7 on Windows. already recompiled retroarch with latest commits (c7d7c5c) , also recompile dsp_filters(ra/libretro-common/audio/dsp_filters) still not working. as stated, selecting a dsp filter does not apply and will entry will still be empty(blank)

**Comment by retro-wertz** [comment]
PR sent. interesting issue....

**Comment by bravestk** [comment]
My question is where are the audio plugins located? When I select audio dsp plugins nothing appears and it wants me to set a directory.. so.. where are they...

**Comment by hizzlekizzle** [comment]
That's a support question, which belongs on the forum rather than the repo, which is for development/bug reports.

That said, they're in settings > audio > audio dsp plugin. The effects themselves should be included with your RetroArch installation, depending on your platform.

**Comment by retro-wertz** [comment]
Btw, this should already be working with latest commit, unless somebody says otherwise.

**Comment by MitsuriZX** [comment]
I have confirmed that Audio DSP Plugins are working as intended with the latest commit. Guess the problem's solved. I will be closing this issue, then.
