### ISSUE TITLE
Implement slang shader specification for GLSL and Cg.

### ISSUE THREAD

**Issue by Themaister** [libretro/RetroArch#5392]
The current Vulkan shader implementation should also have a backend for GLSL and Cg. It currently only works on Vulkan, which is a bit annoying.

Requirements for bounty completion:
- Uses SPIRV-Cross to convert SPIR-V to the appropriate GLSL and Cg (HLSL) target.
- Can run all existing shaders from https://github.com/libretro/slang-shaders (every shader that currently works in Vulkan at least)
- The pull request is reviewed and signed off by me.

NOTE:
- If issues arise with SPIRV-Cross during development, support will be provided on https://github.com/KhronosGroup/SPIRV-Cross issue tracker.

**Comment by denim2x** [comment]
@Themaister To clarify:
 - some relevant files: `spirv_cross.cpp`, `spirv_glsl.cpp`, `shader_vulkan.cpp`, `shader_vulkan.h`
 - ...and functions: `Pass::set_shader()`, `Pass::build()`;

what other modules are related to this?

**Comment by aliaspider** [comment]
not exactly what you had in mind, but #6204.
the new d3d11 driver didn't have shader support at all so it was a much more exciting target for this.

I was quite impressed by how well spirv-cross works already, most shaders should work, except those that rely on unimplemented features ( like the infinite history option :P )

**Comment by Themaister** [comment]
This is merged.
