### ISSUE TITLE
UI Crash if button remap to index -1

### ISSUE THREAD

**Issue by BubsFr** [libretro/RetroArch#5404]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When trying to unbind a Button using remaps files, -1 make the UI crash when loading that parameter

### Expected behavior

No Crash, with button unbinded

### Actual behavior

Button is unbinded, but UI crash on parameter loading

### Steps to reproduce the bug

1. Edit a remaps file (/config/SYSTEM/SYSTEM.rmp)
2. Add a remap to a button "-1"
3. Load the Controls Menu for that button

### Version/Commit
1.6.4

### Environment information

- OS: Win 10 x64 Anniv Update

**Comment by fr500** [comment]
Well,  that's undefined behavior you're making up a value.

If such value was possible it would be among the options

**Comment by BubsFr** [comment]
Fair. Should I rename to [Feature Request] ?

**Comment by fr500** [comment]
Not gonna happen, not like this at least.

**Comment by orbea** [comment]
I made a test remap file on linux and found no crashes, I suppose this is fixed?
```
input_libretro_device_p1 = "1"
input_libretro_device_p2 = "1"
input_player1_analog_dpad_mode = "0"
input_player1_btn_b = "-1"
input_player1_btn_y = "0"
input_player2_analog_dpad_mode = "0"
```
Please let me know if its still crashing for you.
