### ISSUE TITLE
video_driver override do not work with --appendconfig

### ISSUE THREAD

**Issue by obenguerah** [libretro/RetroArch#5405]
## Description

when video_driver is both set in main retroarch.cfg and an apprend retroarch-append.cfg, the append value do not override the main value. Override only happen if main value remain unset.

Note: Save config on exit is set to off.

RetroArch.cfg:
video_driver="gl"

retroarch-append.cfg:
video_driver="vulkan"

[Description of the bug]

values in main .cfg should be overrid by append values, even if set explicitly

### Steps to reproduce the bug

1. Set main config with video_driver="gl"
2. Create a append config with video_driver="vulkan"
3. run retroarch.exe with --appendconfig xxxx

### Version/Commit
1.6.4

### Environment information

- OS: Win 10 x64 Anniv Update

**Comment by fr500** [comment]
Related: https://github.com/libretro/RetroArch/issues/4804

**Comment by zoltanvb** [comment]
This one seems to work nowadays, tested with current build (post-1.17.0). Video driver was changed to vulkan if it was specified in appendconfig file, even if glcore was set in main config file.
