### ISSUE TITLE
Medafen psx hw rendering issues with certain games.

### ISSUE THREAD

**Issue by kenshen112** [libretro/RetroArch#5410]
Namely Metal Gear Solid, CastleVania symphony of the night.

CastleVania:
In CastleVania text isn't cleared out of the text buffer meaning what text that appears next is rendered / appeared over the previous lines.

Metal Gear Solid: the first cutscenes are fu*** up and are a blurry mess the sub is visible albeit blurred. The water backgrounds look broken as well.

I'll update post with screen shots when I can access me computer.

**Comment by fr500** [comment]
The template is there for a reason. The first line tells you that it's only for RetroArch bugs.

Not a RetroArch issue, this is clearly a Beetle PSX issue.

Reopen the bug there
https://github.com/libretro/beetle-psx-libretro
