### ISSUE TITLE
Boxart/Tilescreen/Screenshot are missing in the favorites menu

### ISSUE THREAD

**Issue by neuromancer** [libretro/RetroArch#5411]
### Steps to reproduce the bug

1. Enable Boxart, Tilescreens or Screenshots. 
2. Add any game showing one of these to favorites. 
3. Go to favorites menu.

### Expected behavior

I expect to see the corresponding Boxart/Tilescreen/Screenshot in the favorites

### Actual behavior

No Boxart/Tilescreens/Screenshots.

### Version/Commit

I tested with last revision (1cc4239e2b922046a73c28b6aa4f01bc38f2575c).

**Comment by RobLoach** [comment]
Favorites also use the entry's filename rather than the playlist title.

**Comment by Elmazz37** [comment]
Same with history

**Comment by capitaineflam25** [comment]
I would love having those images too on favorites/history.

Those 2 specific gamelists could be very usefull but the lack of full game name and images make it less useable.

**Comment by capitaineflam25** [comment]
> 
> 
> Favorites also use the entry's filename rather than the playlist title.

Right, i've referenced an issue for that #7531

**Comment by neuromancer** [comment]
I tried the latest revision (c38ed7f843752dd0ae443f16cb04ae9254baa68b) and Favorites are showing boxart/tilescreen/screenshot and the playlist name (instead of the filename). I don't know who or when it was fixed, but great job guys!
