### ISSUE TITLE
X-less Vulkan context (Nvidia) : exits unless only one game specified

### ISSUE THREAD

**Issue by bidinou** [libretro/RetroArch#5414]
## Description

When I start RetroArch from the terminal (without the X server), in Vulkan mode, the menu does appear properly but I get an error (failed to create Vulkan context) when I start any emulation core.

However, if I specify the core & game on the command line it does work, until I choose another game in the menu.

It seems a resource is not properly freed.

### Expected behavior

I should be able to start any core from the menu, go back to the menu, and choose another one.

### Actual behavior

I get the following error in the terminal
[INFO] Vulkan dynamic library loaded. [ERROR] [Vulkan]: Could not find instance extensions. Will attempt without them. [ERROR] Failed to create Vulkan instance. [ERROR] [Vulkan]: Failed to create Vulkan context. [INFO] [Vulkan]: Detecting screen resolution 320x240. [INFO] [Vulkan]: Using resolution 320x240 [INFO] [Vulkan]: Using RGB565 format.
Full log here : https://framabin.org/?50e0dbaa3bdfbbed#MZ7IUTYQnow9HaMjd3h5EtzP38DVLfYGWDGoz14kpt0=

### Steps to reproduce the bug

Start RA under X and choose Vulkan and evdev in drivers.
Switch to the console.
Stop the X server.
Start RA.
Start any game.

### Bisect Results

As it's a new feature, I guess it always happened ?

### Version/Commit
You can find this information under Information/System Information

- RetroArch: latest stable ubuntu PPA
- nvidia proprietary drivers ; latest

### Environment information

KDE Neon, 64 bits, nvidia proprietary, 1050 GTX
Build from the stable PPA.

NOTE : when starting the MAME core emu, from X, I also get an error that might be related (unavailable resource). This is random and only occurs with this single core.

**Comment by bidinou** [comment]
I double checked and got the same behaviour under Arch.

**Comment by bidinou** [comment]
Hi ! I've been wondering : is actually anyone using RetroArch in Vulkan X-free context ? Does it supposedly give any benefit over Vulkan/X ?  Anyway, it *almost* works !

**Comment by mlnlbrt** [comment]
Hi @bidinou,

I think you need to have xserver running anyway for this scenario. 
Without xserver running I am getting the same error as you, but with xserver up I am having the following:

```
[INFO] RetroArch 1.7.4 (Git 1155e11)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES 
Built: Dec 19 2018
[INFO] Version: 1.7.4
[INFO] Git: 1155e11
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] Vulkan dynamic library loaded.
[INFO] [Vulkan]: Detecting screen resolution 0x0.
[INFO] [Vulkan]: Using GPU: GeForce GT 1030
[INFO] [Vulkan]: Queue family 0 supports 16 sub-queues.
[INFO] [Vulkan]: Swapchain supports present mode: 2.
[INFO] [Vulkan]: Swapchain supports present mode: 0.
[INFO] [Vulkan]: Creating swapchain with present mode: 2
[INFO] [Vulkan]: Using swapchain size 1920 x 1080.
[ERROR] [Vulkan]: Failed to create swapchain.
[ERROR] [Vulkan]: Failed to create KHR_display surface.
[ERROR] [Vulkan]: Failed to set video mode.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
```

So it looks it is almost there but still something is wrong.

I use Linux with 410.78 nvidia binary drivers and vulkan-loader 1.1.96. Here is vulkan-related part of my retroarch.cfg:

```
video_context_driver = "khr_display"
video_driver = "vulkan"
```

@twinaphex, @Themaister have you ever get khr_display video context working with Linux and nvidia binary drivers? Or should we consider this work-in-progress?

Thanks

**Comment by orbea** [comment]
So you are starting RetroArch from a tty with a KMS context? I was under the impression that this did not work with the nvidia proprietary drivers at all, does it work with opengl instead?

**Comment by mlnlbrt** [comment]
@bidinou I have got retroarch working with nvidia 390.42 drivers (newer will probably work too) and no X Server running.

All you need to do is to change `library_path` in ICD JSON file to `libEGL_nvidia.so` and make sure you have the following set in your retroarch.cfg:

```
video_context_driver = "khr_display"
video_driver = "vulkan"
```
