### ISSUE TITLE
Cfg Overrides ignored with RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#5415]
For cores that use RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME, cfg overrides are ignored when:
-you start the core without content
-you use "load content"

Starting from a playlist is using overrides fine.

I tried removing the call to RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME from libretro.c, it made overrides work in every cases, but also remove the possibility to start the core without content.

Tested with NP2Kai and DosBox.
Win7 x64 Retroarch 1.6.7

**Comment by fr500** [comment]
@Tatsuya79 does it work if you load content without selecting a core, and pick the core just at the end?

**Comment by Tatsuya79** [comment]
Nope, override is ignored just the same.

**Comment by Tatsuya79** [comment]
Fixed with https://github.com/libretro/RetroArch/pull/5789

Thank you! 👍
