### ISSUE TITLE
Favorites: please add the console (or other machine/computer) name

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#5423]
## Description

When I add a game in the Favorites menu, I have only the name of the game. But I don't know on wich machine/computer/console it runs.

### Expected behavior

When I add a game in the Favorites menu, I think it's an important information to know the platform name  the game was developped for.
For example:
Super Bomberman 3 - Super Nintendo Entertainment System
or if you prefer to class your favorites by machine/computer/console name:
Super Nintendo Entertainment System - Super Bomberman 3

Thank you for the interest you gave to this feature request.

**Comment by orbea** [comment]
This seems to have been implemented so I am going to close this issue.
