### ISSUE TITLE
[BUG] retro_input_descriptor not accepting RETRO_DEVICE_SUBCLASS as device

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#5439]
## Description

In fbalpha-libretro, after redefining the device type for a player, i'm generating new input descriptors to refresh the ones i provide to the front-end, and i set the device of those desciptor to the RETRO_DEVICE_SUBCLASS selected

### Expected behavior

All descriptors should be refreshed.

### Actual behavior

All descriptors where the device is equal to a RETRO_DEVICE_SUBCLASS are ignored.
Also, the new list won't be displayed if i don't close/open the ui

### Steps to reproduce the bug

The issue will appear every time you try setting device type to a RETRO_DEVICE_SUBCLASS

### Bisect Results

Since i moved pad layout selection from core options to controls

**Comment by barbudreadmon** [comment]
If there is no plan to add support for device subclass in retro_input_descriptor, perhaps having a macro to determine parent class of a subclass would be a good idea. The way i'm refactoring my code at the moment, device could end up being a subclass of various devices, so having something to get parent class, without having to store correspondence in an array or whatever, would be convenient.

**Comment by fr500** [comment]
Are you sure this is still happening?
There was on issue, RA wasn't setting descriptors for RETRO_DEVICE_JOYPAD I fixed that, and it broke the ones that had RETRO_DEVICE_SUBCLASS

Or are you doing something like this:

```
    struct retro_input_descriptor desc_emulated_mouse[] = {
        { 0, RETRO_DEVICE_SUBCLASS, RETRO_DEVICE_INDEX_ANALOG_RIGHT, RETRO_DEVICE_ID_ANALOG_X, "Emulated Mouse X Axis" },
        { 0, RETRO_DEVICE_SUBCLASS, RETRO_DEVICE_INDEX_ANALOG_RIGHT, RETRO_DEVICE_ID_ANALOG_Y, "Emulated Mouse Y Axis" },
        { 0, RETRO_DEVICE_SUBCLASS, 0, RETRO_DEVICE_ID_JOYPAD_R2, "Emulated Mouse Left Click" },
        { 0, RETRO_DEVICE_SUBCLASS0, RETRO_DEVICE_ID_JOYPAD_L2, "Emulated Mouse Right Click" },
        { 255, 255, 255, 255, "" },
};
```

I think that's not supported, I think the descriptors always use the original device inputs.

**Comment by barbudreadmon** [comment]
Yes, that's what i was doing, and i was also using those subclasses for polling. I'll remove them all (i thought i did that in my latest commit but it seems there are some remaining)

**Comment by orbea** [comment]
@barbudreadmon Is this still an issue?

**Comment by barbudreadmon** [comment]
@orbea I don't remember if i changed something in fba code since then, but it's acting as expected now.

One last related issue perhaps, while i declare only those device types : 
> 	static const struct retro_controller_description controller_description[] = {
		{ "Classic", RETROPAD_CLASSIC },
		{ "Modern", RETROPAD_MODERN },
		{ "Mouse (ball only)", RETROMOUSE_BALL },
		{ "Mouse (full)", RETROMOUSE_FULL }
	};

The device type "Retropad" still appears and is set by default, hopefully my logic consider it to be the same as "Classic".

**Comment by retro-wertz** [comment]
as a workaround for the labels, i had the 1st entry to be at least of a RETRO_DEVICE_JOYPAD type (fceumm),  but true, labels should be based on the descriptors.

**Comment by orbea** [comment]
I'm not sure how to solve it, but the relevant code is here.

https://github.com/libretro/RetroArch/blob/374384128c8b29c041b31ac8c11fd087c1eda1b0/menu/menu_setting.c#L1733

**Comment by orbea** [comment]
These two functions are also relevant.

https://github.com/libretro/RetroArch/blob/374384128c8b29c041b31ac8c11fd087c1eda1b0/menu/menu_setting.c#L973

https://github.com/libretro/RetroArch/blob/374384128c8b29c041b31ac8c11fd087c1eda1b0/menu/menu_setting.c#L2410

**Comment by orbea** [comment]
@barbudreadmon It seems there is a dedicated issue for the remaining problem so I am going to close this issue so the discussion can continue there.

See https://github.com/libretro/RetroArch/issues/6966.

Please let me know if I missed anything!
