### ISSUE TITLE
Trying to scan a directory with (high?) file count fails

### ISSUE THREAD

**Issue by Ghosthree3** [libretro/RetroArch#5441]
### Expected behavior

All files in the directory are to be scanned and added to a playlist if applicable.

### Actual behavior

After "Preparing for content scan" the scan quickly ends, spamming "Failed to open <file>: Too many open files" for every file in the directory to the terminal. After this the program "bugs out" and directories, including the ones navigated through to scan said directory, now only contain the entry "Directory not found.", returning to the menu and scrolling across to existing playlists (console icons) now only contain "No playlist entries available." as well.
Quitting RetroArch afterwards results in the GUI closing but "[ERROR] Failed saving config to <location>." to appear in the terminal and for the process to remain open in the background using up 50-100% of the CPU requiring it to be forcibly killed.

### Steps to reproduce the bug

1. Launch retroarch with -v and --menu
2. Scan a highly populated directory, 6804 files in my case, all zips <-- may be important
3. Experience the above

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.7/ca6a7578e
I'm aware there's newer commits but it's only six days old and they caused a different (additional) issue so I rolled back.

### Environment information

- OS: Linux - Arch
- Compiler: GCC

**Comment by retro-wertz** [comment]
just finished importing Goodnes set which had 22,094 files(all zipped) and theres no problem here.

![goodnes](https://user-images.githubusercontent.com/23315382/30435459-626f67f2-999c-11e7-85fd-a8faaae51477.png)

**Comment by Ghosthree3** [comment]
Ok so this was instead caused by the directory I've been trying to scan containing many 0KB zip files, after removing them it scans in correctly. A rare and not really significant issue, but perhaps the recursive scan feature should be changed to just ignore any empty files like that.
