### ISSUE TITLE
BSNES Mercury cores (Balanced and Performance tested) crash on various games when pressing volume up or down on Android device.

### ISSUE THREAD

**Issue by gannon345** [libretro/RetroArch#5444]
## Description

BSNES Mercury cores (Balanced and Performance tested) crash on various games when pressing volume up or down on Android device. Tested on a Nvidia Shield K1 tablet.

Issue is specific to BSNES cores. Does not occur in SNES9x core.

### Expected behavior

Volume turns up or down.
### Actual behavior

Retroarch crashes with an unexpected error

### Steps to reproduce the bug

Launch a SNES game with the BSNES Mercury Performance or Balanced core. Press volume up or volume down hardware keys on Android phone or tablet.

I tested the problem on a Shield k1 tablet and confirmed it across multiple games. Tested 1.0 and 1.1 known good dumps of Mega Man X, as well as F-Zero, Legend of Zelda: Link to the Past, and Starfox.

All games not impacted. Tested Super Baseball 2020 and volume controls work.

### Bisect Results

Unsure when issue started occurring, only encountered it today (9/16/2017) on RA 1.6.7.

### Version/Commit

Google Play Store current version (1.6.7)

- RetroArch: 1.6.7

### Environment information

- OS: Android 7 on Shield K1 tablet.
- Compiler: Unknown

**Comment by sergiobenrocha2** [comment]
This is the right place to report: https://github.com/libretro/bsnes-mercury/issues

**Comment by gannon345** [comment]
Thanks, copy/pasted this into a new issue over there.
