### ISSUE TITLE
[New 3DS] RetroArch Snes9x 2005/plus audio stutter and frame drops

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#5453]
**Description**
Many games drop to 45-50 fps on New 3DS/2DS XL hardware (both use the 804 MHz CPU),
games such as Final Fantasy VI and Donkey Kong Country, none of which use extra
microprocessors, struggle to maintain 60 fps on what should be more powerful hardware
than the O3DS. Special chip games run at an even lower framerate, often down to 35-40 fps. 

**Expected behavior**
I've tried Snes9x 2002, and it runs fine, but it's also ancient, not to mention the audio core runs the SPC700 at an octave higher than later Snes9x S-SMP cores. 

**Actual behavior**
Normal non-microprocessor games are running much slower, even on an older core like Snes9x 2005 and 2005 plus (which has 1.52's audio core AFAIK). Snes9x 2010 performs much slower than this, and people need to refrain from using it.  What's baffling is Snes9x 3DS runs full speed, but lacks Blargg's sound core. 

**Steps to reproduce the bug**

1. Load Snes9x 2005/plus
2. Load any non-chip game
3. Run around in a level until frame/audio drops occur and crackling begins

I have tried adjusting vsync, audio sync, latency, frameskip, etc but to  no avail.
Will the N3DS see any potential performance tweaks for this particular core in the near future?
Genesis Plus GX, Nestopia, and Gambatte all run at full speed from my tests, no frame drops 
or audio stuttering occurred in my testing. 

**Bisect Results**
Since 1.6.7 I believe

**Version/Commit**
- RetroArch: 1.6.7 official, no nightly builds used

**Environment information**

- OS: New 3DS/2DS XL 11.5 Luma CFW installed
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
This sounds very similar to #5251, you're sure that this is 1.6.7? The issue wasn't fixed until that specific release I think.

**Comment by roflcopter777** [comment]
@bparker06  should I try a nightly build to see if it's fixed? I'm fairly confident it is 1.6.7 vanilla, I'll take a screenshot and or record a video with the framerate counter enabled, using my camera to record it. I've no way to directly record footage, unfortunately, I'll record/screenshot it and get back to you. So the issue has been resolved? Hmm, well, if it has, Snes9x 2005 plus and Snes9x 2010 run awfully slow on N3DS hardware..hmm.

**Comment by roflcopter777** [comment]
@bparker06  Yup, definitely on 1.6.7, and I tried the nightly build of 1.6.7 from September 19th, Yoshi's Island actually performed pretty badly, Donkey Kong Country 2 ran as low as 48-51.5 fps on Topsail Trouble, a level that's not demanding. 

Video link of 1.6.7 regular:
https://www.dropbox.com/s/h1cfchavi0dosxo/DSCN9580.MOV?dl=0

And 

Video of 1.6.7 9/19/17 nightly:
https://www.dropbox.com/s/d7f3u7fieq0sta0/DSCN9581.MOV?dl=0

Not sure why performance is degraded on the latest build =/ This shouldn't be happening; I know for super FX sure, but DKC2?

**Comment by roflcopter777** [comment]
@bparker06 Well, did more testing, results are not good.

Here's the results of my testing your suggestions,

Core used:
Snes9x 2005 Plus (Snes9x 1.43 with 1.52 audio)

N3DS info:
System version: 11.5
CFW: Luma 3DS
Method of app: CIA installation

Settings I changed:
Changed audio resample from sinc to CC
Changed audio driver to CSND
Changed sync audio to "off"
Changed audio latency to 200 ms (overkill, but for the sake of it)

Games tested:
Final Fantasy VI runs at 51 fps during the opening scene
Donkey Kong Country 2 runs at 48 fps on the second level in first world
Aladdin ran at full speed during the first level
Chrono Trigger ran at 52-55 fps during the opening scene

This is rather confusing, because, in my opinion, this accentuates the fact the N3DS was simply never meant to being able to run Blargg's S-SMP audio core, performance is affected to adversely. On the other hand, the games that do run via Snes VC injection, run almost perfectly (60 fps, highly accurate audio). Downside is there's only support for the Cx4 and DSP1 co-processors.

Conclusion:
I propose that Snes9x 2005 Plus and Snes9x 2010 be removed from the repository/build bot.
I see the reason due to Snes emulation having current issues in performance in conjunction with 1.52 code. So yes, I'm conflicted, it can run well via official emulators.

I'm at a loss, if more optimizing can be done, great. But I can't make that judgment, and I can't suggest that the Blargg S-SMP cores be removed, but I personally don't see any other option. Where do we go from here? Maybe there's a bottleneck or the CPU is being throttled when loaded as a CIA app, but not as a 3DSX app.

**Comment by bparker06** [comment]
I thought you said blargsnes was just as slow? This would lead me to believe that RA nor its core is doing anything worse than anyone else.

**Comment by roflcopter777** [comment]
Blargsnes is slower than it should be, but not nearly as bad, but can't even get 60 fps on Blargsnes. Snes9x 2002 and 2005 and snes9x 3DS are the only options N3DS users have, if that ever changes, great. But again, not gonna hold my breath. 

Snes9x 2005 Plus is actually slower than BlargSnes, by about -10 fps.  Either way, I've 100% given up. Developers don't seem to be bothered by it, why should I?

**Comment by fr500** [comment]
If 2005 is full speed and 2005+ is not it's pretty obvious the bottleneck
is the sound core.
I don't see this as a valid reason to remove the cores, just don't the slow
cores.

What's this stuff about 3dsx vs cia?
Which is supposed to be faster?, and more importantly why don't you try the
3dsx app too to verify?

**Comment by roflcopter777** [comment]
Well, damn. Then what are we supposed to do about the bottleneck? Are you saying Blargg's S-SMP core will never be optimized in a way to run faster on the N3DS? Sure sounds like it to me. I don't know, I haven't tried the 3DSX app version because I don't have the HBC installed yet. So yeah, sounds like to me Snes emulation with accurate sound's never gonna be possible. Well that's a downer. Snes VC does it (its sound core is superior to Snes9x 2002), I don't see why RA doesn't.  Time for me to just forget I asked.

**Comment by fr500** [comment]
RA doesn't have anything to do with this.
Nintendo has put money in those emulators. We're all just volunteers here and no-one is a SNES expert as you can see.

If the blarg apu was fast enough it would be included in snes9x 3ds. It seems it simply isn't.

**Comment by roflcopter777** [comment]
Then what're we supposed to do then?  You know what? I give up, there's no point in reporting this issue or even pursuing this.  *Sigh*.

**Comment by bparker06** [comment]
That attitude will certainly get you nowhere fast. Please consider starting a bounty or otherwise politely searching around for experts in this area of expertise and talking to them about it. Whining about it here will only turn people off to looking into it in the first place.

**Comment by roflcopter777** [comment]
Sorry, and you're right. I did think about bountysource for something to that effect. I'll need a job so I can donate a starting amount (joblessness has gotten the better of me), but I really want to make it's even achievable for the CPU to handle accurate sound emulation on Snes. I can make a bounty, just need to think of what amount to set it for.

**Comment by bparker06** [comment]
You can always start an issue for it and state that you plan to place a bounty on it. Maybe in the meantime someone else might come along and add some money before you're able to.

**Comment by roflcopter777** [comment]
I'll think about it, I need to tread carefully, because I don't want to end up wasting any more time than I've already wasted. Not sure if I need to with Snes9x 2005 plus or 2010, probably 2005 as the latter is way too much for N3DS.

**Comment by LibretroAdmin** [comment]
These are more like core performance issues, not really bugs. Should just be moved to the respective libretro repos and the issue tracker there if still need be.
