### ISSUE TITLE
no virtual keys in xmb interface when running on ios9

### ISSUE THREAD

**Issue by fancyang** [libretro/RetroArch#5455]
## Description

There are no virtual keys in xmb interface when running on ios9

### Actual behavior

I would like to use the virtual button under the xmb interface, but no matter how I set up overlays it do not work

### Version/Commit
You can find this information under Information/System Information

- RetroArch:1.6.7

### Environment information

- OS: iOS9.3.2
- Compiler: xcode8

**Comment by fr500** [comment]
This has to be configured:
settings / display / overlays / hide overlay on menu -> off

**Comment by orbea** [comment]
Seems like the above comment would resolve this and given the lack of activity I am going to close this. Please let us know if you still have a problem, thanks!
