### ISSUE TITLE
Crashes immediately with Vulkan driver

### ISSUE THREAD

**Issue by daninthemix** [libretro/RetroArch#5462]
Not sure when exactly this began, but now whenever I try to run Retroarch with the Vulkan driver, it immediately crashes. Here's [what I get if I run with the verbose switch](https://forums.libretro.com/uploads/default/original/2X/0/08d6ad9d6eddbef4d4ee4f9b2c3ebda0e80fe51f.png).

System details:
Windows 10 Anniversary
GTX1080 (driver 384.94)

Have tried Retroarch 1.6 and 1.67, and have tried removing my retroarch.cfg, to no avail.

**Comment by fr500** [comment]
I tried to reproduce this, I can't...
But I haven't updated my nvidia driver so I think the issue may be there.

**Comment by daninthemix** [comment]
It's definitely nothing to do with my RA config, as I downloaded the latest version and ran it vanilla from that folder, changed to Vulkan, restarted and crash.

Also, I have a G-sync monitor. Not sure if relevant.

**Comment by Tomk3n** [comment]
I had the same problem.
Turning off IGPU-MultiMonitor in the Bios fixed it.

**Comment by daninthemix** [comment]
Thanks so much - there's no way I would have figured this out!

**Comment by oxysoft** [comment]
Same problem. I'm on a laptop and I have a monitor plugged using HDMI. However, I discovered that it works properly if I disconnect the monitor and play on my laptop's screen, quite obnoxious since I don't want to play on my external monitor... As for what was suggested above, I don't have "IGPU-MultiMonitor" in my BIOS.

**Comment by Tomk3n** [comment]
IGPU-MultiMonitor wouldn't make sense on a laptop.
What you could try is forcing the used gpu in the bios. if that doesn't work you probably need to wait until this bug is fixed.

**Comment by JamesIV4** [comment]
I’m having this issue too with a GTX 780 on Windows 10. Crashes immediately.

**Comment by orbea** [comment]
This is probably a variety of configuration and driver bugs...if anyone can still reproduce crashes with vulkan please make a new issue with a backtrace so the developers can hopefully help. If anyone needs help doing that please ask the forum, discord or irc so someone can help explain the process.
