### ISSUE TITLE
Graphical issues in OSX PPC port.

### ISSUE THREAD

**Issue by snigel** [libretro/RetroArch#5463]
I built version 1.6.7 from source, it looks like textures are black squares. In full screen the mouse pointer is also a black square.

Screenshots:
https://imgur.com/a/cPM36

Details:
OSX 10.5 & Xcode 3.1.4
ibook G4, 1.33GHz, 1.5GB, Radeon 9550

**Comment by twinaphex** [comment]
You are missing the default assets. Not a bug. Go to Online Updater -> Update Assets.

For general release builds we make sure the assets are packaged in the .app archive.

**Comment by retro-wertz** [comment]
missing assets. use the Online Updater and then Update Assets.

**Comment by snigel** [comment]
Thank you, it worked fine.

Maybe this step can be included in the build instructions?
https://buildbot.libretro.com/docs/compilation/osxppc/

The reason I built is that the ppc build gives a 404.
https://buildbot.libretro.com/stable/1.6.7/apple/osx/ppc/RetroArch.zip

**Comment by fr500** [comment]
Not missing anything, there are none

**Comment by snigel** [comment]
@fr500 is there a reason for that? I've started compiling cores myself, approx half of them compiles.
Haven't started testing which works and which doesn't.

**Comment by fr500** [comment]
We don't have a PPC mac

**Comment by snigel** [comment]
@fr500 can I help out with my machine?

**Comment by bparker06** [comment]
@snigel We are using Xcode 8.2.1.

**Comment by snigel** [comment]
@bparker06 That was meant as a reply to "We don't have a PPC mac". 
If it was about not having ppc hardware, I thought it could be worth mentioning that older Intel macs can do cross compiles out of the box, on older versions of Xcode.

Anyway, I'd be glad to help out if I can.

**Comment by bparker06** [comment]
@snigel Yes, and Xcode 3/4 will not run on Sierra, that is why I mentioned which OS we're running.

**Comment by snigel** [comment]
Can I upload my builds to the RetroArch site?
I've managed to compile RetroArch 1.6.7 and the following cores this far:
```
2048_libretro.dylib
4do_libretro.dylib
81_libretro.dylib
bluemsx_libretro.dylib
bnes_libretro.dylib
dosbox_libretro.dylib
fceumm_libretro.dylib
fmsx_libretro.dylib
fuse_libretro.dylib
gambatte_libretro.dylib
gw_libretro.dylib
handy_libretro.dylib
lutro_libretro.dylib
mame2003_libretro.dylib
mednafen_lynx_libretro.dylib
mednafen_ngp_libretro.dylib
mednafen_pce_fast_libretro.dylib
mednafen_pcfx_libretro.dylib
mednafen_supergrafx_libretro.dylib
mednafen_vb_libretro.dylib
mednafen_wswan_libretro.dylib
nestopia_libretro.dylib
o2em_libretro.dylib
pcsx_rearmed_libretro.dylib
prboom_libretro.dylib
prosystem_libretro.dylib
quicknes_libretro.dylib
scummvm_libretro.dylib
snes9x2005_libretro.dylib
stella_libretro.dylib
tyrquake_libretro.dylib
vecx_libretro.dylib
virtualjaguar_libretro.dylib
```
Working on fixing the builds for as many as possible, but a few is not possible on the platform.
For example desmuse relies on x86 asm. Dinothawr and stonesoup requires c++11 libc++, which cannot be built for this platform.

**Comment by twinaphex** [comment]
Hi there.

Yeah we'd love to have some solution on our buildbot, the problem is though that on our buildbot we rely heavily on automated builds, and we haven't yet found a way to automate PowerPC builds. Could you help us maybe with this? I'm sure @bparker06 would like to know as well if there are any solutions available to us.

**Comment by bparker06** [comment]
It might be possible to run early versions of OSX ppc with qemu, but I don't think the buildbot could take the CPU spike.

**Comment by snigel** [comment]
@twinaphex Sure, I'd be happy to try. What is failing with automating on ppc in particular? 
Are there any tickets I can look at or something I could test to setup?

**Comment by bparker06** [comment]
@snigel We don't currently have a way to emulate it on an Intel CPU, and we don't have PPC hardware available for buildbot use.

**Comment by twinaphex** [comment]
@snigel We could still require help here.

**Comment by snigel** [comment]
@twinaphex you want to run buildbot on my PPC machine? Or how can I help out?

**Comment by Traace** [comment]
@snigel you still have that ibook G4, 1.33GHz, 1.5GB, Radeon 9550 ? 👍 

@twinaphex I could assist building for powerpc with a some PowerMac G5 dual cpu 8GB Ram.
Something else open except missing of a build machine that prevents a 1.7.6 release for osx_ppc?

**Comment by snigel** [comment]
@Traace yes I do.
