### ISSUE TITLE
(Android ARM) Mupen64Plus core can't load games

### ISSUE THREAD

**Issue by KagerouShinobi** [libretro/RetroArch#547]
Upon loading the Mupen core and attempting to load an N64 ROM, it will go into a black screen that says it is loading the file in a yellow font (as it should), but after a couple seconds it kicks me back out to the main menu of Retroarch. Tested with several files (Mario Tennis, Mario 64, Mega Man 64, Banjo Kazooie, Smash Bros...)

Tried using the Core Detection as well, no dice, same problem. Does not happen with either the PCSX ReArmed, PicoDrive or MAME cores, nor does it happen with Mupen64Plus or SuperN64 with the exact same ROM file placed in the exact same directory.

Tried uninstalling and reinstalling both to Retroarch 1.0.0.0 r28 and Retroarch 1.0.0.1 r30, all configurations are default and untouched.

Device is JXD S7800B using Android 4.2.2.

**Comment by Kivutar** [comment]
I had a similar bug on Cubieboard2 a few days ago, with mali400 too. The stacktrace was saying something about the EGL lib distributed as blob.
