### ISSUE TITLE
[Feature Request] add Prescaling option.

### ISSUE THREAD

**Issue by whatwwkd4496** [libretro/RetroArch#5470]
can you add prescale option before aspect ratio?
I have a windows and generic tv connected via component cable, since I never cant get 240p mode working forever, a prescale option before aspect ratio might help scanline shaders to appear correctly, since NTSC tv's has 720x480 interlaced resolution, a 240p source filtered with scanlines will scaled to 640x480 but because its interlaced, instead having scanlines we'll have interleaved blacks and image flickering, because image and scalines are 1 pixel tall, it needs to 2 pixels tall, but resulting 4x image don't fit 720x480 display, I intended to prescale 240p source half its original size then apply scanline filter to 4x, this will make source image fit display dimension and avoid flickering with its 2 pixel tall scanlines. it's a compromise but it might be worthy.

**Comment by RobLoach** [comment]
Missing issue description.  Add it in, please.
