### ISSUE TITLE
Windows raw input driver doesn't communicate with FCEUmm or Nestopia

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#5472]
- Operating System: Windows 7 x64
- RA version: 1.6.7 stable
- Cores: FCEUmm and Nestopia (others may be affected)

The windows `raw` driver does not seem to be sending mouse input to either of those cores regardless of what kind of mouse device I use. Both cores do work as expected with the `dinput` driver although as mentioned it only supports one mouse/light gun.

Because this affects more than one core in the same way, I created the issue in the RetroArch tracker rather than the trackers for the affected cores.

This issue began as a discussion in the forums: https://forums.libretro.com/t/how-to-configure-mouse-as-light-gun-and-light-gun-as-mouse/8970/63

**Comment by casdevel** [comment]
Windows raw input currently don't support light-gun and pointer devices, only mouse. 

If those cores don't support mouse device, than this will wait for that support to be implemented in Windows raw input driver.

If cores do support mouse device and still, with mouse as input device, don't work with Windows raw input driver than it's a input driver issue.

**Comment by markwkidd** [comment]
@casdevel after your recent work on the windows raw driver, it supports my Wiimote/Dolphinbar light gun. 

Now that Windows raw works with the Dolphinbar, the raw driver should support light guns in general, correct?

**Comment by markwkidd** [comment]
This issue is for relative/standard mice, separate from any light gun or pointer issues. :)

@casdevel I think this situation is what you say: "If cores do support mouse device and still, with mouse as input device, don't work with Windows raw input driver than it's a input driver issue."

Nestopia and FCEUmm cores do support the mouse device when used with other input drivers, only configured with the raw input driver do they have this problem. I think this does mean there is an issue with the Windows raw input driver.

**Comment by casdevel** [comment]
@markwkidd 

> Nestopia and FCEUmm cores do support the mouse device when used with other input drivers, only configured with the raw input driver do they have this problem. I think this does mean there is an issue with the Windows raw input driver.

Not necessarily. 

Core can be set-up to use light-gun or pointer as input device, and input driver can use regular mouse data, convert that to light-gun or pointer data and than supply that converted data to the core. In this case core don't need to support mouse device, and still be able to receive input from regular mouse device (core will think that is using light-gun or pointer).

If core options don't reveal whether core can work with regular mice, source code will.

**Comment by markwkidd** [comment]
@casdevel the Nestopia and FCEUmm cores do work with the same mouse if I use a different input driver, for example `dinput`

**Comment by casdevel** [comment]
Nestopia core supports only light-gun device, FCEUmm core supports mouse only in 'zapper' mode (otherwise it uses pointer device). This is based on sources (I'm not familiar with either cores).
In theory, FCEUmm (if it's in 'zapper' mode) should work with Windows raw input driver.

Basically both cores and input driver have missing functionality. I'm planning to address input driver "part" sometime in the future...

Issues for cores can also be opened, maybe someone will fix core(s) before I fix input driver.

**Comment by retro-wertz** [comment]
i made the code for zapper in fceumm, or at least on the front end part.
its uses 2 mode which uses RETRO_DEVICE_MOUSE and RETRO_DEVICE_POINTER.

when using RAW driver, RETRO_DEVICE_POINTER does not work, while this works
with other drives.

**Comment by casdevel** [comment]
@retro-wertz 

> when using RAW driver, RETRO_DEVICE_POINTER does not work, while this works
with other drives.

Windows raw input driver currently don't support RETRO_DEVICE_POINTER and RETRO_DEVICE_LIGHTGUN.

**Comment by casdevel** [comment]
@markwkidd PR #5515 should fix Nestopia related issues.

**Comment by markwkidd** [comment]
That is great, thank you @casdevel . Do you think the FCEUmm problem is caused by something unrelated?

**Comment by markwkidd** [comment]
Also I want to mention that these input updates are generating some very happy buzz over in the RetroPie forums this week. People are starting to test out multi-mouse and several have gotten it working with their arcade cabinet + rpi setups 8-)

**Comment by orbea** [comment]
@markwkidd Do you know if this works with fceumm yet?

**Comment by markwkidd** [comment]
Here are my findings with the latest nightly of RA and the current FCEUmm buildbot build.

The following is true for both `dinput` and `raw` input drivers. I navigate to the RA `Controls` menu with "Chiller" loaded and change `User 1 Device Type` from `auto` to `Zapper`. At this point a crosshair appears that accurately tracks my mouse cursor.

With neither of those input drivers do I seem to have mouse clicks being emulated as firing the Zapper, however. Does that seem like a separate issue or should I leave this one open?

**Comment by orbea** [comment]
And in nestopia mouse clicks do fire the zapper?

It sounds like a related different issue, but I am not sure if its in the core or frontend. I'm fine with either leaving this issue open or closing it and making a new one. The latter might get more people to see it though?

**Comment by orbea** [comment]
Thanks for the explanation, if you recall where that issue is I'll close this one.

**Comment by markwkidd** [comment]
Yes I can see that there is no default lightgun trigger mapping for the mouse with a lightgun. That does indeed seem like something that can be fixed, and also something that's unrelated to my original issue.

I don't see an issue on the tracker for adding default gun mappings although I only did a couple of simple searches just now

**Comment by markwkidd** [comment]
I created an issue regarding default mouse->trigger mappings so we can close this one: https://github.com/libretro/RetroArch/issues/7904

If that turns out to be a duplicate I will gladly close it as well.
