### ISSUE TITLE
[Wii U] RetroArch 1.6.7 main RPX crashes Wii U in HBL

### ISSUE THREAD

**Issue by roflcopter777** [libretro/RetroArch#5482]
**Description**
Using the main retroarch.rpx app results in an immediate black screen when loaded
in the Homebrew Launcher, used in conjunction with Haxchi + CFW or CBHC/sigpatches. 
However, a workaround for this is to use another standalone RPX app such as Snes9x or mGBA, from there, you can operate RetroArch normally, however, this may be seen as an inconvenience. 

**Expected behavior**
Loading retroarch.rpx normally would load up the XMB menu without issue. 

**Actual behavior**
Black screen, no code dump or system memory issue. Hard reboot required. 

**Steps to reproduce the bug**
1. Download latest nightly build of version 1.6.7 
2. Load whatever CFW+sigpatches you have*
3. Load up the Homebrew Launcher

*CFW is used to speed up read/write times and to load the HBL channel.

**Bisect results**
Began in 1.6.7 vanilla. 

**Version/Commit**
09-28_RetroArch_rpx 
 
**Environment information**
-Wii U system 5.5.1
- Homebrew Launcher 2.1 channel/RPX

**Comment by twinaphex** [comment]
Unfortunately, I know nothing about this.

We need external help on this.

**Comment by roflcopter777** [comment]
What would that entail, exactly? Who could be contacted?

**Comment by twinaphex** [comment]
If I knew who to contact, I wouldn't post or ask for help on gbatemp to begin with. As for bisecting, maybe somebody else can explain you how to do it, maybe @bparker06 or @fr500.

**Comment by roflcopter777** [comment]
Maybe I just suck at explaining: 

Load up Haxchi + CFW if you have that or CBHC installed
Then load up the Homebrew Launcher
Then load up RetroArch 1.6.7.

All I get is a black screen. People who'll help will need to have some way of loading custom firmware and signature patches to load the HBL channel. 

Damn..

**Comment by Dramoor** [comment]
I think it has been around for awhile. I don't have old .RPX to test but. It did used to give a memory error at one point I think too but that was intially after the GUI was udpated. But I think the solution to that was editing something in the initial configuration....But maybe that is the same issue or similar?

**Comment by roflcopter777** [comment]
Is it the core paths?  I don't know what it could be, but this sounds serious. I wish I had a Wii U I could donate.

**Comment by twinaphex** [comment]
You could maybe ask @FIX94 if he'd like to help. Unfortunately with WiiU, a lot of the SDK/homebrew stuff is very experimental and so it's really outside of my comfort zone.

**Comment by Dramoor** [comment]
Id love to get into coding. But my knowledge is not very good. lol Last thing I coded for was crappy C# junk scripts to auto run my ultima online game to earn free gold. haha.

**Comment by roflcopter777** [comment]
I don't know, he seems like he's pretty busy. I had a feeling reporting this was a less than ideal suggestion.

**Comment by bparker06** [comment]
@roflcopter777 Just FYI retroarch.elf seems to load fine, just not the .rpx one.

**Comment by roflcopter777** [comment]
@bparker06  Hmmm.. I'd rather not have to switch back and forth to different app formats, I've been using RPX for some time without issue, I mean, technically, it shouldn't be an issue, but I wouldn't even know if or how to fix the issue. I feel rather foolish for bringing up the bug report in the first place.

**Comment by bparker06** [comment]
At this point I cannot find anything wrong with the code, as evidenced by the fact that the .elf file works. The rpx is converted directly from the elf binary itself with the "elf2rpl" tool, so maybe something in that process is actually the culprit.

**Comment by roflcopter777** [comment]
I don't know, does the ELF file still work with the RPX cores? Or do I need to use the ELF files with ELF cores? If so, MAME, FBA, won't work due to size constraints.  I don't know what else to do, this bug was hardly worth reporting.

**Comment by bparker06** [comment]
Yes, the elf file can load rpx cores.

**Comment by roflcopter777** [comment]
Good to know, shouldn't be an issue for for the HBL 2.1 channel or RetroArch launcher.  The devs have bigger bugs to neutralize anyways, the RPX issue is very low priority. I may as well close this.
