### ISSUE TITLE
Application changes don't save unless exiting cleanly.

### ISSUE THREAD

**Issue by Simplexletalis** [libretro/RetroArch#5484]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch does not auto save changes to configurations unless exiting the application cleanly, which can cause frustration when config changes are made on the fly.

### Expected behavior

Config changes should stay in place after editing them and then continuing to a game and force closing the app, or when the app crashes.

### Actual behavior

Changes are not saved and instead need to be re-applied.

### Steps to reproduce the bug

1. Install the app
2. Make config change
3. App crash or not exit cleanly leads to no config changes being saved.

### Bisect Results

Inherit to the applications initial configuration on install.

### Proposed fix

Have integral config saving turned on by default, or make the application save config settings on change.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.7

### Environment information

- OS: Android TV
- Compiler: None

**Comment by RobLoach** [comment]
What crash did you run into? Fixing the crash would fix this problem.

**Comment by kirksteele** [comment]
Typically during ppsspp emulation, but from what I understand that needs to be rebuitl.

**Comment by orbea** [comment]
I'm pretty sure this is a won't fix, a crash handler will complicate debugging and the crashes should just be fixed. This was discussed in another issue (Somewhere) and rejected there by @twinaphex.

If you have any specific crashes to report, please do so. For core crashes they should be reported to the core's repo.
