### ISSUE TITLE
[Request/Suggestion] Add forward (together with the actual rewind)

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#5487]
With the launch of the new Mini console I saw videos of the rewind feature.

It is less accesible that RetroArch rewind, that works more than Braid or car games, while Mini console gives you at the start of the buffer and then you select where you want to be.

But is cool have the possibility of go again forward after rewind (of course, if you didn't played nothing). So I thought that will be cool have the possibility to rewind, like now but you can go again forward in the save states buffer.

With this feature you can be more precise: Imagine that you do rewind and you want to let the most famous Hedgehog just in the mid platform, but you fail and rewind more, you can forward again to the exact point!

The other thing is forward is executed at emulatio speed it can be used as replay feature.

This will imply that release rewind button will not resume the game in that poing, or you will need to add other action (rewind_and_pause) and it will not drop the states from the save state buffer, so you can do forward. When you resume the game the future buffer will be dropped (from the current state to the end of the save state buffer).

So you can have a action that works like now: rewind and when you release it automatically resumes, and other that rewind but when you release it doesn't resume, so you can do forward (and more rewind), and when you want you can "Resume"

**Comment by RobLoach** [comment]
Rewind brings back to a previous state... You can't play a bit and come up with a new state that doesn't exist.

There is the fast-forward button, however.
