### ISSUE TITLE
`gl` video driver Steam compatibility has failed

### ISSUE THREAD

**Issue by brianblakely** [libretro/RetroArch#5488]
## Description

Launching RetroArch from Steam now no longer works with the `gl` video driver

### Expected behavior

* Steam Overlay works
* Steam Input works

### Actual behavior

RetroArch launches, but Steam cannot hook into it

### Steps to reproduce the bug

1. Add RetroArch executable to Steam
2. Launch it from Steam
3. Make sure you're using `gl` video driver

### Bisect Results

Version 1.6.7, previous versions still work

### Version/Commit

- RetroArch: 1.6.7

### Environment information

- OS: Windows 10

**Comment by fr500** [comment]
![image](https://user-images.githubusercontent.com/1721040/31049905-5e24f22a-a603-11e7-988a-c41fee9542de.png)

Today's build

**Comment by fr500** [comment]
Marking it as invalid until it can be reproduced

**Comment by brianblakely** [comment]
I learned elsewhere just now that the nightly build has already fixed this, and the issue is temporal to only 1.6.7 stable.

Thanks for addressing this ticket so swiftly.
