### ISSUE TITLE
SNES games crash with Fatal signal 7 (SIGBUS)

### ISSUE THREAD

**Issue by jenom** [libretro/RetroArch#5493]
## Description

SNES games crash with all available cores after a short while running fine. N64 works without problems. Tried all kinds of different settings. Also tried the nightly Oct 02 with the same result as well as reinstall/delete of configs.

### Expected behavior

Retroarch continues to emulate.

### Actual behavior

Hard crash. See attached logcat.

### Steps to reproduce the bug

1. Start SNES rom with any core.
2. Play for a short while.
3. Crashes

### Version/Commit

- RetroArch: 1.6.7 (Aug 21 2017) and nightly Oct 02

### Environment information

- OS:  Android 7.0 on Samsung tab S2 (NEON, Mali)

I think this is the relevant part of the log:
[logcat.txt](https://github.com/libretro/RetroArch/files/1347710/logcat.txt)

**Comment by bparker06** [comment]
Looks like a memory alignment issue related to audio. I tried the same core (bsnes performance) on an Android 6.0 device with RA 1.6.7 stable (aug 21) and it worked fine for me though, could be a hardware-specific issue.

Can you try muting the audio within RA? If that doesn't work, try a different audio driver or disable it altogether (use null as the driver and/or turn off 'audio enable' in settings).

**Comment by jenom** [comment]
Thanks a lot for the reply. I tried disabling the sound driver (to null) so it lasted a little bit longer but in the end it had the same result. Muting and different audio driver did not change the effect in any way. I can provoke the crash immediately by changing the volume on the tablet. I might try older versions and see how that changes the outcome.

**Comment by bparker06** [comment]
Very strange... does this issue happen with any other apps on the system? Have you tried any standalone emulators?

**Comment by jenom** [comment]
So far this is the only occurrence and this does not happen with the N64 cores. The Snes9x EX+ emulator from the playstore works without problems. The tablet uses Samsung's own Exynos 7 Octa 5433 with a Mali-T760 MP6 GPU. A short search did not pop up any huge differences with regard to memory alignment...

**Comment by bparker06** [comment]
Can you list the exact cores that you've tried that are all problematic? Usually when we hear people say "all" they really mean like 1 or 2... so I just want to be 100% sure what we're dealing with.

**Comment by meepingsnesroms** [comment]
This crash occurred in libc and began with other OS librarys, try installing a different OS or updating your existing one.
ArmV7 allows unaligned access so you can also try just a different kernel because yours may be disabling unaligned access in the MMU.

This is not something RetroArch can fix, it is an OS bug or hardware defect.

**Comment by fr500** [comment]
Just so you know, you can't randomly update kernels in every android device without rooting / unlocking the bootloader.

**Comment by jenom** [comment]
yes I know. I had this same problem on my sony z5 compact. So it seems to be somewhat related to android 7 because the two do not share the same cpu make.
