### ISSUE TITLE
Load Content -> Collections -> Playlist, stopped working.

### ISSUE THREAD

**Issue by James-F2** [libretro/RetroArch#5495]
As of 2nd October 2017 build.
Using RGUI driver loading content from a playlist stopped working.
It doesn't enter into the selected playlist but jumps back to "Scan Directory" while trying to select a playlist in the Collections tab.

**Comment by Ryunam** [comment]
I can confirm this happens with other Menu Drivers as well, including XMB. The steps to reproduce this problem are as follows:

1) Have an existing Playlist;
2) Select "Load Content" -> "Collections" -> scroll down towards the Playlist in question and select it;
3) As opposed to letting you choose an entry in the playlist, you are warped back to the previous menu.

I am going to try a bisect later to accurately pinpoint where this began.

**Comment by James-F2** [comment]
Thanks for looking it up Ryunam.
The problem is it is the only way to play games from a playlist in RGUI which I use with a CRT, unlike XBR where the console playlists already part of the home screen.

Hope it will be fixed quickly,
Thanks!

**Comment by twinaphex** [comment]
https://github.com/libretro/RetroArch/commit/bb6ca3e4ffe5fe24f467afcedf07f3ed45de5a5c

This should hopefully fix these issues.

**Comment by orbea** [comment]
Given this should of been fixed in the commit mentioned in the previous commit, that I can not reproduce it and the lack of recent activity I am going to close this issue. Please let us know if anyone can still reproduce it.
