### ISSUE TITLE
STRING_REP_INT64/etc

### ISSUE THREAD

**Issue by Alcaro** [libretro/RetroArch#5497]
libretro-common/include/retro_common_api.h
```
#ifdef _WIN32
#define STRING_REP_INT64  "%I64u"
#define STRING_REP_UINT64 "%I64u"
#define STRING_REP_USIZE  "%Iu"
#elif defined(__STDC_VERSION__) && __STDC_VERSION__>=199901L && !defined(VITA) && !defined(WIIU)
#define STRING_REP_INT64  "%llu"
#define STRING_REP_UINT64 "%llu"
#define STRING_REP_USIZE  "%zu"
#else
#define STRING_REP_INT64  "%llu"
#define STRING_REP_UINT64 "%llu"
#define STRING_REP_USIZE  "%lu"
#endif
```

- This throws warnings all across the codebase on Linux64, where uint64_t is unsigned long, not ULL.
- It reinvents the standard library; the correct name for these is PRId64, PRIu64 and PRIuPTR, respectively, from <limits.h> (or, for the scanfs in frontend/drivers/platform_unix.c, SCNd64/etc).
- --INT64-is-unsigned.-seriously,-what.-it's-not-even-used-anywhere.-- edit: ignore this, I'll fix it. I need it elsewhere.

I could fix this myself, but network/httpserver/httpserver.c uses both PRIxPTR and STRING_REP_UINT64, presumably because inttypes blows up on some obscure platform. I don't know which platform this is, so I'd have to test on every single one, which I can't; as such, I'm not confident fixing this one myself.

Roadmap:
- [ ] Find which platforms have a functional inttypes.h
- [ ] For the others, find what the relevant PRIwhatevers should be, and which macros detect them
- [ ] Create our own inttypes.h, like libretro-common/include/compat/msvc/stdint.h, which includes the real one when it works, otherwise defines its own macros
- [ ] Switch to using that

I'm willing to do steps 3 and 4, but 1-2 requires access to hardware and software I don't have.

 

Alternative fixes:
- Shove the warnings under the rug with a ifdef _LP64 define UINT64 %lu. Let's not do this; we have too much messy code already, let's clean up at least some of it.
- Remove all 64bit ints, then use %u everywhere. There's 965 instances of uint64_t across the repo, I suspect this is more effort than it's worth.

**Comment by bparker06** [comment]
After researching the toolchains used on the buildbot, here are the ones I have found that have an inttypes.h (they all define PRIwhatevers):

Android
Blackberry
Cell SDK (PS3)
devkitPPC (Gamecube/Wii/WiiU)
devkitPSP (PSP)
devkitARM (3DS)
gcc (Linux)
clang (OSX)
MSVC2013 (Windows)
Win10 SDK (Windows)
djgpp (DOS)
mingw-w64 (Windows)

And ones without an inttypes.h at all:

Win2003/7/8.1 SDK (Windows)
MSVC6/2003/2005/2010/2012/2015/2017 (Windows)
Xbox/Xbox360

If I need to dig deeper and look at how each one defines certain keywords, just let me know exactly what I need to look for and I can paste it here.

**Comment by Alcaro** [comment]
That's better than I expected, Twinaphex made it sound like it's missing on most of the consoles. iOS and PS4 seem missing from that list, but it's safe to assume iOS does the same as Clang/OSX, and that PS4 supports every C standard header PS3 does.

That leaves a bunch of MSVCs. Detecting SDK version sounds pretty annoying, but we could just always use our own on MSVC, or pick some arbitrary cutoff version (libFLAC seems to assume inttypes is present on _MSC_VER >= 1800 aka >= 2013).

The next step would be would be dropping [this one](https://github.com/chemeris/msinttypes/blob/master/inttypes.h) [here](https://github.com/libretro/RetroArch/tree/master/libretro-common/include/compat/msvc).

I suspect that directory is not on the include path on all MSVCs (otherwise the #include in the stdint would recurse), so let's tell retro_common_api.h to include the appropriate one. The final step would be replacing all those STRING_REPs with PRIu64.

Advantages of doing this:
- Less reinvention of libc, yielding cleaner code
- Fixes approximately 37 gcc warnings on Linux64
- Fixes the same warnings on MinGW, if building with the replacement printf that supports %llu
- Fixes libui on old MSVCs, it uses inttypes already with no ifdef (okay, I'm not sure if libui is used anywhere where old MSVCs are relevant, but I suspect it will be at some point)

Disadvantages:
- Takes a bit of effort - not your problem
- inttypes.h needs __STDC_FORMAT_MACROS defined under C++ - not your problem, I'll deal with that (note to self: toss in a #error if someone included inttypes without defining that, to make clear what the fix is)
- Breaks if a platform ships an incomplete or broken inttypes - extremely implausible, someone would've caught that long ago and removed (or fixed) the header; even if it does happen, we can detect it and add something suitable to retro_common_api.h

@twinaphex, does this sound reasonable? If yes, I'll push it on sunday.

**Comment by bparker06** [comment]
I forgot to check iOS, and I don't think we have a PS4 SDK so I didn't get to check there. MS's docs website also assumes that VCs since 2013 include inttypes.h, but my research shows otherwise. After searching installation folders of all MSVCs and related SDKs, *only* 2013 itself contained that header, and only the Win10 SDK, and *nothing* else... no idea why.

**Comment by bparker06** [comment]
Just looked on the OSX buildbot and iOS/AppleTV SDKs have inttypes.h.
