### ISSUE TITLE
Beetle PSX PS1 Joypad Thumbstick acts like shoulder button

### ISSUE THREAD

**Issue by SryForWastingYourTime** [libretro/RetroArch#5499]
I'm sure I've done something wrong because I don't understand GitHub but anyway:

in the 09-28 version of retroarch when I'm using Beetle PSX and I set the controller to PS1 the thumbsticks on my controller act like they are shoulder buttons which doesn't make sense since the PS1 joystick doesn't have thumbsticks at all.  So pressing the thumbsticks shouldn't do anything.  I'm trying to map save state and other features to the thumbs sticks but I can't do that if pressing the thumbsticks causes actions in the game like dialogue advancing and such.

That is all.  Sorry for taking up your time.  I really hate to bring this up at all it just is really frustrating me but I'm sure you have more important issues to work on.

**Comment by retro-wertz** [comment]
templates are there for a reason, follow template when posting a new issue...

**Comment by orbea** [comment]
For support please try the forum, discord or irc. If you have an actual issue to report please repost while following the issue template to the best of your ability, thanks!
