### ISSUE TITLE
Unable to compile with --disable-netplay

### ISSUE THREAD

**Issue by Jalle19** [libretro/RetroArch#55]
It seems like it's not possible to compile Retroarch with the --disable-netplay switch. Essentially it fails at:

command.c:131:10: error: ‘rarch_cmd_t’ has no member named ‘net_fd’

Full compilation output can be found here: http://pastebin.com/PW7uspPa

**Comment by Loekasjenko** [comment]
Hi Jalle19 and Themaister,

I had this error. Fixed how?

Kind regards,
Lukas

**Comment by bootsector** [comment]
For now I've commented out line 685 in dynamic.c on retroarch:

      case RETRO_ENVIRONMENT_SHUTDOWN:
         RARCH_LOG("Environ SHUTDOWN.\n");
         //runloop_ctl(RUNLOOP_CTL_SET_SHUTDOWN,      NULL);
         runloop_ctl(RUNLOOP_CTL_SET_CORE_SHUTDOWN, NULL);
         break;

I'm clueless about possible side effects of this, but it seems to fix this issues for me! I will keep using this hack until you guys more fluent with RetroArch runloop innards figure a proper fix!
