### ISSUE TITLE
Referencing an unavailable axis freezes all input

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#5509]
## Description

In an autoconfig profile (only tested udev), if you reference an unavailable axis all input (including keyboard) is ignored.

### Expected behavior

At least allow keyboard to work so the setting can be diagnosed.

### Actual behavior

All input is ignored.

### Steps to reproduce the bug

1. Go to any (udev) autoconfig profile and change an axis to one that the controller does not have
2. With controller plugged in launch RetroArch
3. Input frozen

### Version/Commit

- RetroArch: [1.6.7/970c35056]
- RetroArch: [1.6.7/stable]

### Environment information

- OS: Arch Linux x86_64

I tested this on my Sony DS4 over Bluetooth. What led to discovering this is that DS4 and Bluetooth on a new enough kernel (4.10+) remapped the controller. When loading RA with up to date joypad profiles it matched against the older *Bluez* autoconfig profile and I hit the freeze. If I remove the *Bluez* profile, it matches against *Bluetooth* and the controller mapping/input works as expected.

https://www.diffchecker.com/ck82z9z2

To really confirm this I changed a single axis in the *Bluetooth* config and it reintroduced the error.

**Comment by orbea** [comment]
Closing in favor of the older and more general issue. https://github.com/libretro/RetroArch/issues/3914

**Comment by parkerlreed** [comment]
That's good anyways since it seems the freeze is no longer an issue. I set an axis to a crazy number and all input still worked fine.
