### ISSUE TITLE
3DS/CTR building fails with error

### ISSUE THREAD

**Issue by Dimensional** [libretro/RetroArch#5510]
## Description

Unable to compile the 3DS/CTR from git. Haven't been able to for about a month now, been getting this through the libretro-super. I compiled all the static linked cores, and when attempting to compile retroarch, it errors when attempting to read from ctr_gfx.c. Happens no matter what core I use, and how new all my libraries are. Using latest git of libctru, makerom, bannertools, armips, etc, and latest release of devkitARM.

### Expected behavior

No errors, successful compilation.

### Actual behavior
 The following is a the log of what happens every time I try to compile retroarch.

/opt/devkitpro/devkitARM/bin/arm-none-eabi-gcc -c -o griffin/griffin.o griffin/griffin.c -mword-relocations -fomit-frame-pointer -ffast-math -Werror=implicit-function-declaration -march=armv6k -mtune=mpcore -mfloat-abi=hard -marm -mfpu=vfp -mtp=soft -DARM11 -D_3DS -O3 -DLIBCTRU_NO_DEPRECATION -I. -Ideps/libz -Ideps/7zip -Ilibretro-common/include -DRARCH_INTERNAL -DRARCH_CONSOLE -DSINC_LOWEST_QUALITY -DHAVE_FILTERS_BUILTIN  -DHAVE_GRIFFIN=1 -DHAVE_MENU -DHAVE_RGUI -DHAVE_XMB -DHAVE_MATERIALUI -DHAVE_LIBRETRODB -DHAVE_CC_RESAMPLER -DHAVE_ZLIB -DHAVE_RPNG -DHAVE_RJPEG -DHAVE_RBMP -DHAVE_RTGA -DWANT_ZLIB -std=gnu99 -ffast-math -I/opt/devkitpro/libctru/include
In file included from griffin/griffin.c:395:0:
griffin/../gfx/drivers/ctr_gfx.c: In function 'ctr_lcd_aptHook':
griffin/../gfx/drivers/ctr_gfx.c:241:7: error: implicit declaration of function 'GPUCMD_Finalize'; did you mean APT_Finalize'? [-Werror=implicit-function-declaration]
         GPUCMD_Finalize();
         ^~~~~~~~~~~~~~~
         APT_Finalize
^CMakefile.ctr:217: recipe for target 'griffin/griffin.o' failed
make: *** [griffin/griffin.o] Interrupt

### Steps to reproduce the bug

1. Compile a core. Doesn't matter which one, as long as it can be compiled.
2. Copy the core into the retroarch folder as libretro_ctr.a, then attempt to compile retroarch ctr.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: git 032109512aaa3a50ee72240790c73ff0b3e5615c

### Environment information

- OS: Bash on Windows 10.
- Compiler: gcc

**Comment by Dimensional** [comment]
Is there really nothing happening? I keep updating my copy from git and it still keeps failing on the exact same place.

**Comment by meepingsnesroms** [comment]
You have to use the custom toolchain from [Here](https://github.com/libretro/libretro-toolchains).

This happened to me at first too, the regular toolchain is too new and RetroArch uses deprecated library functions.
