### ISSUE TITLE
Keyboard does not work with the udev input driver

### ISSUE THREAD

**Issue by nijoakim** [libretro/RetroArch#5521]
## Description

Using the udev input driver, RetroArch stops reacting to keyboard presses.

### Expected behavior

Keyboard should work with the udev input driver.

### Actual behavior

Keyboard does not work with the udev input driver.

### Steps to reproduce the bug

1. Go to "settings/driver".
2. Change "input driver" to "udev".
3. Restart RetroArch.
4. Try to use the keyboard.

### Bisect Results

2056ebc80378fabf1f96883de3c7c930c809d101 is the first bad commit.
"Allow udev input to be used with X11 context"

### Version/Commit

- RetroArch: [1.6.0/2056ebc80378fabf1f96883de3c7c930c809d101]

### Environment information

- OS: Debian testing (Buster)
- Compiler: gcc (Debian 7.2.0-8) 7.2.0

**Comment by casdevel** [comment]
Did you set-up user permissions? If not, see [https://github.com/libretro/docs/blob/master/docs/guides/input-joypad-drivers.md#setting-up-udev-permissions](https://github.com/libretro/docs/blob/master/docs/guides/input-joypad-drivers.md#setting-up-udev-permissions).

**Comment by orbea** [comment]
Add your user to the input group, log out and then log back in.

**Comment by nijoakim** [comment]
Yes, this solves the problem. Thanks!

Strange though, that it isn't a problem in the earlier revisions.

**Comment by markwkidd** [comment]
@nijoakim until recently there was a bug that affected some systems. For those affected, `Input Driver` would display `udev`, but there was actually another input driver in use. It sounds like you may have been affected.

**Comment by orbea** [comment]
Please close this issue if its resolved.

**Comment by nijoakim** [comment]
@markwkidd: Okay! I doubt that has been affecting me since it was resolved by adding my user to the input group. I could also change freely between all the input drivers.

**Comment by orbea** [comment]
@nijoakim Yes that problem was affecting you. Before when you selected the udev input driver it was using the x input driver which is the new default. Now it actually uses the udev input driver, but you need the correct permissions for it to work. Adding your user to the input group gave you the correct permissions.

**Comment by nijoakim** [comment]
Aha! Thank you for clearing that up.

**Comment by ashifthekkupuram** [comment]
i have changed input driver to udev. now both my mouse and keyboard not working : |
