### ISSUE TITLE
[Web Player] Menu Toggle is Broken

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#5523]
## Description

Another serious bug with the Web Player. Woop-dee-doo.

Bug is self-explanatory. Menu Toggle, well, *doesn't* toggle the Menu. Nothing shows up. On a side note, the "VSync = on" message copies itself whenever you press the button.

### Expected behavior

The RetroArch menu should appear

### Actual behavior

It, uh, doesn't

### Steps to reproduce the bug

1. Start any core
2. Press the button/keyboard combo
3. ???
4. Profit(?)

### Bisect Results

It's been happening for a couple months now, but after testing it today I found the keyboard combo didn't work either.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Git version: affd56f

### Environment information

- OS: Windows 10
- Compiler: ???

**Comment by casdevel** [comment]
> It's been happening for a couple months now, but after testing it today I found the keyboard combo didn't work either.

You can edit Version/Commit section since this commit is less than a day old, and has nothing to do with keyboard.

**Comment by RobLoach** [comment]
What web browser?

**Comment by DeckOfNoobs** [comment]
Google Chrome

**Comment by bparker06** [comment]
Where are you running this from? http://web.libretro.com/ refuses to load a core at all for me, because browserfs is out of date. (ping @fr500)

However when running it locally since the fix I added in 1.6.7, the menu toggle does work for me but just not consistently 100% of the time, sometimes it takes 2 or 3 tries for it to appear, and so far I have no idea why.

**Comment by DeckOfNoobs** [comment]
Running it through https://buildbot.libretro.com/web/

**Comment by bparker06** [comment]
Hmm indeed that one seems to load the core, while the other one does not. Strange.

**Comment by bparker06** [comment]
If you press the menu toggle several times, does it eventually work for you?

**Comment by RobLoach** [comment]
It could be the Browser trying to make use of the F1 help screen. We may need to change the default Menu toggle key.

**Comment by bparker06** [comment]
It's not that, the menu toggle button on the page itself has the same issue.

**Comment by fr500** [comment]
that just sends F1 tho
IIRC...

Setting a toggle combo works tho

**Comment by bparker06** [comment]
Hmm yea that is true. If I set it to send some other key, it never fails.
