### ISSUE TITLE
XInput buttons not working on latest nightlies

### ISSUE THREAD

**Issue by emoose** [libretro/RetroArch#5526]
## Description

On the latest x86 nightlies none of the face buttons (ABXY) on my X360 controller seem to do anything, using a slightly older build (July 7th 2017) they all work as expected, copying the config from that older build to the newer build does nothing to fix it, and vice-versa has no effect on the older build.

D-pad and analogs seem to work fine though, and strangely the back/start buttons also still work fine. 

When mapping the bindings with "Bind All" (that detects the button pressed and assigns it etc), it works fine for detecting the analogs (+ analog R3/L3), dpad, triggers and start/back buttons, but ABXY and bumpers aren't detected at all.

Oddly enough the latest x64 nightly seems to work fine with the controller. I was wrestling with the idea that maybe it's something on my end that's causing it (like maybe the x86 XInput stuff is being interfered with somehow), but since that July 2017 build (which is also x86) seems to work fine I figured I should probably make an issue about it.

### Expected behavior

Auto-mapped controller should let the analog/dpad navigate menus, with ABXY buttons mapped to allow selections.

### Actual behavior

Controller gets auto-mapped and analog/dpad work fine for navigating, but ABXY have no effect, back button also still works to show info about the selected item.

### Steps to reproduce the bug

1. Clear config files
2. Plug in XInput-based controller
3. Run RetroArch and allow controller to be auto-mapped
4. Analog/dpad should work to navigate, but making selections with ABXY doesn't work.

### Bisect Results

Don't have a RA build environment or anything setup, but an older July 2017 build I have works with the controller fine, seems that something between then and now must have changed for it to stop working.

### Version/Commit

- RetroArch: Oct 8th 2017 x86 nightly (from https://buildbot.libretro.com/nightly/windows-msvc2010/x86/RetroArch.7z)

### Environment information

- OS: Windows 10 x64

**Comment by RobLoach** [comment]
What input driver are you on?

**Comment by emoose** [comment]
Using dinput input driver on both latest and the July build.

**Comment by milesrotaru** [comment]
Same problem here, regardless of input/joypad drivers on current 64-bit Windows build.

**Comment by twinaphex** [comment]
Is this issue still going on for the participants involved?

**Comment by pellet** [comment]
This bug is in the latest release, is it worth using the plain-windows build as the stable release for download instead?
