### ISSUE TITLE
Feature request: custom colors for onscreen notifications

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#5528]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I want to set custom color for onscreen notifications.

### Actual behavior

Now onscreen notifications can be only yellow color.

**Comment by bparker06** [comment]
You can set it with `video_message_color` in retroarch.cfg.

**Comment by ofry** [comment]
OK. But could you expose it on GUI?

**Comment by bparker06** [comment]
Just created a PR for this.
