### ISSUE TITLE
Feature request: opt-in show FPS only (without frame counter)

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#5529]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I want opt-in setting to show only FPS, without frame counter.

### Actual behavior

Now I can see only combo (FPS: ... | Frames ...)

**Comment by retro-wertz** [comment]
can i add also that FPS is also shown in title bar instead of frames count?

thanks.
