### ISSUE TITLE
[XMB] Resizing the window fails to refresh background

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5534]
## Description

Resizing the window beyond what it started out as results in an undesirable background rendering. See the below screenshot:

![screenshot at 2017-10-11 20-57-39](https://user-images.githubusercontent.com/25086/31474197-3a54c998-aec7-11e7-82f6-81eb396b1c36.png)

1. Launch RetroArch with a fresh config
2. It's using the OpenGL display driver and XMB menu driver
3. Resize the Window

### Expected behavior

When resizing the window, it should fix the background so that it renders correctly across the whole screen.

### Actual behavior

When resizing the window, it doesn't render the whole background. See the above screenshot.

### Steps to reproduce the bug

1. Launch RetroArch with a fresh config
2. See that it's using the OpenGL driver and XMB
3. Resize the window
4. See that the background doesn't extend correctly

### Bisect Results

- [c68db611](https://github.com/libretro/RetroArch/commit/c68db611880bc2f4c91a79f5ed49b01a4c9cfdbe) affected
- [59cabfe](https://github.com/libretro/RetroArch/commit/59cabfe) affected
- [8b7b85a](https://github.com/libretro/RetroArch/commit/8b7b85a) affected
- [5ccdc88](https://github.com/libretro/RetroArch/commit/5ccdc88) affected
- [eb3d8c8](https://github.com/libretro/RetroArch/commit/eb3d8c8) okay
- [576583c](https://github.com/libretro/RetroArch/commit/576583c) okay
- [c7da6e1](https://github.com/libretro/RetroArch/commit/c7da6e1) okay

It's [GL_SCISSOR_TEST change in 5ccdc88](https://github.com/libretro/RetroArch/commit/5ccdc88#diff-4f199fc34f40ba23e5ef31a4a77e47a3). Fix is over at https://github.com/libretro/RetroArch/pull/5535 .

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `c68db611880bc2f4c91a79f5ed49b01a4c9cfdbe`

### Environment information

- OS: Ubuntu 16.04
- Compiler: gcc

**Comment by fr500** [comment]
Ok fixed
Sorry about it
https://github.com/libretro/RetroArch/pull/5536
