### ISSUE TITLE
Retroarch 3DS completely broken.

### ISSUE THREAD

**Issue by ValiantBlade** [libretro/RetroArch#5543]
Retroarch 3DS is completely broken on my n3DS. I installed the stable off TitleDB, and I installed Stable 1.6.7 and 1.6.0, just to see if it was the particular version I was using. I get a black screen on boot, and any button reboots the entire 3DS, to the point where I am seeing my Luma splash. I am using Luma 8.1, the CIA versions (I copied over the Retroarch folder to the SD root as well, for each version. I used the 1.6.7 folder with the TitleDB version). My 3DS firmware version is 11.6.0-39U (I installed CFW on 11.3 then updated because Samus Returns). I am also using B9S 1.3. Removing the config file didn't change anything. Without the retroarch folder, the system just crashes, and goes unresponsive on opening the retroarch program.

Steps to reproduce: 
1. Install the current stable on a n3DS with the same firmware, and B9S and Luma versions, then run it.
2. Press any button after it's open.

**Comment by bparker06** [comment]
My n3ds is still on 1.6.0 but it works perfectly for me.

**Comment by GentlemanGamer94** [comment]
Am having the same problem problem; I have a N3DS with firmware 11.6.0-39U, the latest Luma3DS (as far as I know) have the Retroarch folder on the root of my SD and all the CIAs installed, yet anytime I load ANY of the Retroarch apps- Retroarch, GPSP and SNES 2010 are the ones I've tried so far- it crashes after several seconds or my going to the rightmost tab, saying that 'an exception has occurred'. Maybe it's something I'm doing wrong, but this feels like a glitch/issue.

**Comment by ValiantBlade** [comment]
My cores are working individually, if I open, Gambatte, for instance, it is the same as the time I accidentally opened the Gambatte core trying to select the GUI application. I mean, they're useless without the GUI application working because I cannot load any ROMs, however, at least I know the cores aren't at fault.

**Comment by snan** [comment]
Retroarch with Gambatte works for me (I have some small bugs, will report separately). Am on 11.6.0-39E with Luma.

**Comment by FateForWindows** [comment]
This is a known issue with current nightlies. Set the menu driver to rgui and the sound driver to DSP for now and it won't crash.

**Comment by gingerbeardman** [comment]
@FateForWindows I don't see any N3DS nightlies? 😕

**Comment by FateForWindows** [comment]
Yeah, they're not there because the others have automatically been deleted since they're a few days old. I have no idea why there haven't been new nightlies. Hope this gets fixed soon.

**Comment by ValiantBlade** [comment]
FateForWindows, thank you, your solution fixed my problem. Apparently the cores and GUI were both affected by this problem, and, snan, I genuinely didn't know you could do anything inside the core itself after it loaded, so thanks for helping me accidentally discover that. I thought it needed the GUI application to forward it to it and that launching the core just made a bunch of text as it tries to run with no ROM. If this is a known issue elsewhere, I see no problem in closing this specific issue.

**Comment by Jaffacakelover** [comment]
Considering that this is still an issue (3DSX 1.7.5), for me at least, maybe the downloadable package should have its config set with the above fix by default?

**Comment by twinaphex** [comment]
@jdgleaver Since you push many commits for 3DS, do you know what this is about and whether there is still an ongoing issue here? Thanks in advance.

**Comment by jdgleaver** [comment]
Hmm... I know that the default config of using csnd and xmb is highly suboptimal: many homebrew apps have issues with csnd in general, and xmb is too laggy and glitchy for general use. xmb will indeed lock up the system now and then - I haven't yet investigated why, since rgui is so well suited to the 3DS that anything else doesn't seem worth using.

I would agree that changing the defaults to dsp and rgui would be a very good idea (although some kind of graceful exit/error message if the user hasn't dumped their dsp may be required). With these settings, RetroArch on the 3DS is absolutely rock solid stable. Would you like me to look at doing this?

I also question whether the retroarch_3ds.cia is relevant. Since we have to install the individual cores anyway (and they each show up on the homescreen as separate entities), I think it just creates confusion for the end users.

**Comment by Jaffacakelover** [comment]
I've just been testing for the past hour, so here's some more info...
A fresh install of Retroarch 1.7.5, with the 3DSX package, won't launch. Retroarch folder into SD root, 3dsx folder into SD root.
On the lower screen, it stops after this line:
`[INFO] [Audio]: Set audio input rate to: 29917.00 Hz.[INFO] [autoconf]: No profiles found.`

retroarch.cfg is generated on first launch, and only manages to add 1 line:
`libretro_path = "sdmc:/retroarch/cores/2048_libretro.3dsx"`

It's suggested in the above posts to add these 2 lines to retroarch.cfg (which has to be done in a text editor) to get it to launch:
'audio_driver = "dsp"'
'menu_driver = "rgui"'

But if I add just the audio_driver line, with `dsp`, `csnd` or `null`, it still doesn't launch. Same error.
(the error shows up on my lower screen like this: there's some sort of screen tearing going on)
`[INFO] [Audio]: Set audio input rate to:`
` 29917.00 Hz. 		    oconf]: No profi`
` 29917.00 Hz.[INFO] [aut`
`les found.`

When I set it to `"xaudio"` instead, RetroArch sets the audio driver itself (pausing on the below lines for about 10 seconds), then boot carries on and XMB successfully loads!
`[ERROR] Couldn't find any audio driver named "xaudio"`
`[INFO] Available audio drivers are:`
`[INFO]    csnd`
`[INFO]    dsp`
`[INFO]    null`
`[WARN] Going to default to first audio driver...`
I can load content, and audio works (with the same pauses in the log as above), but not sure what audio driver i'm actually on. According to the cfg file generated after this, It's:
`audio_driver = "xaudio"`
`audio_dsp_plugin = ""`
...so am I missing a DSP driver now?

**Comment by twinaphex** [comment]
> I would agree that changing the defaults to dsp and rgui would be a very good idea (although some kind of graceful exit/error message if the user hasn't dumped their dsp may be required). With these settings, RetroArch on the 3DS is absolutely rock solid stable. Would you like me to look at doing this?

Yeah, let's do that then. I think you use the 3DS port more than us so you are probably in a better position to be able to make the decisions on what should be default for this port and what not.

**Comment by jdgleaver** [comment]
> Yeah, let's do that then. I think you use the 3DS port more than us so you are probably in a better position to be able to make the decisions on what should be default for this port and what not. So by all means, you have free reign to do whatever is necessary for that platform port to improve it.

OK, I'll try and get this done next week!

@Jaffacakelover: Those are some strange errors. Do you get the same with the cia build? (as an aside, you're probably using the csnd driver, since xaudio is invalid and csnd is the first fallback... don't worry about the 'audio_dsp_plugin' setting, though - that refers to something else entirely)

...although there do seem to be other reports about the autoconf issue online: https://www.reddit.com/r/RetroArch/comments/a1r04i/3ds_no_profiles_found_crash/

I'm still building my own cores using the RetroArch repo from Nov 14, so it's possible there's been a regression somewhere. I have to leave my computer now - I'll investigate later...

**Comment by gingerbeardman** [comment]
> whether the retroarch_3ds.cia is relevant 

@jdgleaver I use this on my home screen and keep all the separate cores in a folder. It's the quickest way to get into RGUI and it defaults to loading the last used core. Then I load my recent game, or another core or different content from there.

**Comment by jdgleaver** [comment]
@gingerbeardman I stand corrected! No worries, I will never remove functionality. I was only thinking out loud. (It's just that users install the shortcut cia and think they're good to go - and then complain about long load times etc., or forget they need a retroarch folder. Probably should look at updating the docs at some point, although hardly anyone reads them!)

@Jaffacakelover: I've not had time to test anything, but here's a copy of the 'known good' setup that I use on my 3DS (minus bios files and playlists): [retroarch.zip](https://github.com/libretro/RetroArch/files/2636092/retroarch.zip)

Try deleting your existing files then copy the retroarch folder to your sdcard and install (but don't delete) one or more of the cias in the cores folder. If they work, then you could try copying over and installing one of the cias from the latest nightlies, and see if you still get autoconf or audio errors

**Comment by gingerbeardman** [comment]
Maybe the RetroArch core could check for correct config and advise the user? 

Maybe a few bullet pints that get ticked off as they are met: 

[x] RetroArch core
[ ] Other cores
[ ] RetroArch folder
[ ] BIOS files

**Comment by jdgleaver** [comment]
A small update: just posted PR #7711, which sets the default drivers to dsp/rgui.

**Comment by kalmathrax** [comment]
I'm sorry dudes, but I'm here for the same problem as listed before, the famous "[autoconfig]: No profiles found" ...
and as said FateForWindows : This is a known issue with current nightlies. Set the menu driver to rgui and the sound driver to DSP for now and it won't crash.

But my problem is that I'm a pure newbie, and I don't know how to set them... please someone can help me? (I installed the newest version after some researches... and nothing changed, still this message and retroarch won't load)

Thanks !

**Comment by gingerbeardman** [comment]
@kalmathrax 
Settings > Driver > Menu 
Settings > Driver > Sound

https://docs.libretro.com/guides/rgui/

**Comment by kalmathrax** [comment]
Thanks a lot @gingerbeardman ! I can access it with the version published by @jdgleaver 
but with the latest version (1.7.5) , I can't even access the menu... it boots and stops on  "[autoconfig]: No profiles found" 
Anyway, if there is no solution for the moment, I'll wait for a stable version :)

**Comment by FateForWindows** [comment]
The crashing issues I was talking about were fixed over a year ago. You need to install all of the core CIAs, just the retroarch CIA won't suffice.

**Comment by kalmathrax** [comment]
That works perfectly fine :D ! Thanks a lot !

**Comment by raekuul** [comment]
> The crashing issues I was talking about were fixed over a year ago. You need to install all of the core CIAs, just the retroarch CIA won't suffice. Latest nightly will install them automatically.

So I have to install a number of cores that I'm never going to use?
