### ISSUE TITLE
No longer compiles in linux due to removal of definition for 'xshm_gfx_has_windowed' with --enable-xshm

### ISSUE THREAD

**Issue by wyatt8740** [libretro/RetroArch#5551]
## Description

Game fails to compile due to commit https://github.com/libretro/RetroArch/commit/d4756f83e55a58d1df322f6a6e9b39b5c9bdc0f6 when configured with `--enable-xshm`

### Expected behavior
Retroarch compiles

### Actual behavior
Undefined function causes compilation to terminate.

Note that re-defining the function makes compilation successful.

    static bool xshm_gfx_has_windowed(void *data)
    {
       return true;
    }

### Steps to reproduce the bug
1. `./configure --enable-xshm`
2. `make clean; make`

### Bisect Results

https://github.com/libretro/RetroArch/commit/d4756f83e55a58d1df322f6a6e9b39b5c9bdc0f6

### Version/Commit

- RetroArch: 84ac64275

### Environment information

- OS: Debian Sid
- Compiler: gcc version 7.1.0 (Debian 7.1.0-13) 64-bit

**Comment by wyatt8740** [comment]
Also, I just compiled it with that dummy function put back in and it runs with no noticeable problems.

**Comment by orbea** [comment]
I can reproduce this.
```
gfx/drivers/xshm_gfx.c:222:4: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    xshm_poke_set_osd_msg,
    ^~~~~~~~~~~~~~~~~~~~~
gfx/drivers/xshm_gfx.c:222:4: note: (near initialization for ‘xshm_video_poke_interface.set_osd_msg’)
gfx/drivers/xshm_gfx.c:258:4: error: ‘xshm_gfx_has_windowed’ undeclared here (not in a function); did you mean ‘xshm_gfx_set_shader’?
    xshm_gfx_has_windowed,
    ^~~~~~~~~~~~~~~~~~~~~
    xshm_gfx_set_shader
make: *** [Makefile:157: obj-unix/gfx/drivers/xshm_gfx.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by orbea** [comment]
@wyatt8740 Can you please test the fix in https://github.com/libretro/RetroArch/pull/5560?

**Comment by wyatt8740** [comment]
I can't make the xshm driver work, either, but it does fix compilation.
    [ERROR] Currently active window is not an X11 window. Cannot use this driver.
    [ERROR] [Video]: Cannot initialize input driver. Exiting ...
    [ERROR] Fatal error received in: "video_driver_init_input()"
    [ERROR] This core requires a content file.

This happened with my previous build, too, actually. I stupidly forgot to set retroarch to use the xshm driver.
But yeah, it compiles.

**Comment by wyatt8740** [comment]
Not working still.
Configured with `./configure --enable-sdl --enable-xshm --enable-libusb --enable-dbus --enable-udev --enable-threads --enable-ffmpeg --enable-ssa --enable-networking --enable-x11 --enable-opengl --enable-zlib --enable-fbo --enable-alsa --enable-xvideo --enable-freetype --enable-osmesa`.
```
CC gfx/drivers/xshm_gfx.c
gfx/drivers/xshm_gfx.c:222:4: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
    xshm_poke_set_osd_msg,
    ^~~~~~~~~~~~~~~~~~~~~
gfx/drivers/xshm_gfx.c:222:4: note: (near initialization for ‘xshm_video_poke_interface.set_osd_msg’)
gfx/drivers/xshm_gfx.c:258:4: error: ‘xshm_gfx_has_windowed’ undeclared here (not in a function); did you mean ‘xshm_gfx_set_shader’?
    xshm_gfx_has_windowed,
    ^~~~~~~~~~~~~~~~~~~~~
    xshm_gfx_set_shader
Makefile:155: recipe for target 'obj-unix/gfx/drivers/xshm_gfx.o' failed
make: *** [obj-unix/gfx/drivers/xshm_gfx.o] Error 1
```

**Comment by orbea** [comment]
Did the xshm driver ever work for you? I tried checking out commit f6c8aba119d4addc0894e67b2ce3e84a0cac52eb and all I get is `Aborted` when I set the video driver to xshm. Am I missing something?

**Comment by orbea** [comment]
Alright, I get a segmentation fault with that commit now that I turned fullscreen off.

**Comment by orbea** [comment]
I suggest making a new issue for the other xshm driver problems.
