### ISSUE TITLE
When launching content from the CLI, the menu doesn't show the running content tab

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#5554]
## Description

After launching a game from the menu, pressing the menu button shows up the running content tab (with reset, save state, config etc etc). When launching from the CLI (with -L), opening the menu shows the first tab (the home tab).

### Expected behavior

When pressing the MENU key after launching content from the CLI, the menu should open the currently running content tab

### Actual behavior

It opens the default tab

### Steps to reproduce the bug

1. Load content from CLI
2. Press the menu toggle key
3. See that it's the default tab

### Bisect Results

Since the game isn't launched from the menu, I guess it doesn't register it and just doesn't show the correct tab

### Version/Commit

- RetroArch: commit 28397b3

### Environment information

- OS: Lakka on a RPi3B
- Compiler: GCC

**Comment by orbea** [comment]
@natinusala I submitted a PR that attempts a fix, can you try it?
https://github.com/libretro/RetroArch/pull/5583

**Comment by natinusala** [comment]
It worked for me !

**Comment by orbea** [comment]
Good to hear, thanks for trying it!
