### ISSUE TITLE
[Wii U] One controller controls two players at the same time

### ISSUE THREAD

**Issue by lordelan** [libretro/RetroArch#5556]
I described the issue here in detail:
https://gbatemp.net/threads/retroarch-wiiu-wip.447670/page-418#post-7637379

However here is the short version:
I have bought two controllers of the same type from the same manufacturer.
They show up in the input options as **HID 0810/E501 (#01)** and **HID 0810/E501 (#02)**.
I can map the keys for each just fine.

I did the following mapping:

- Player 1 -> Wii U Gamepad
- Player 2 -> USB Controller 1
- Player 3 -> USB Controller 2

But whenever I launch a game which supports up to 4 players (no matter which core/rom) it's always the case that USB Controller 1 is moving player 2 and 3 around at the same time while USB Controller 2 does nothing.

Since I'm using RetroArch for Wii U I'm limited to "wiiu" as the input_driver (just in case someone was going to recommend "udev" as the input_driver to fix that issue).

**Comment by retro-wertz** [comment]
Not saying which cores and rom is being used for the test makes it harder
to replicate the issue and finding a quicker solution...

**Comment by lordelan** [comment]
For example Turtles in Time 4 Players (World) [FB Alpha] and Super Bomberman 2 [SNES].
All controllers are "RetroPad" except player 2 being "MultiTap" (or was it "MultiPad"?).

**Comment by Maschell** [comment]
Thanks for the reporting, PR #5559 should fix the problem

**Comment by lordelan** [comment]
Tested yesterday's nightly with Maschell's fixes and it's working perfectly.
Thanks Maschell! :)
