### ISSUE TITLE
New cores added in 1.6.3 and later all have the same "APP_UNIQUE_ID" on N3DS so overwrite each other

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#5565]
there is an issue with cores added to 3DS in 1.6.3 and later

81 (1.6.3 and later) https://github.com/libretro/81-libretro/issues/4
fuse (1.6.3 and later) https://github.com/libretro/fuse-libretro/issues/43
np2kai (post 1.6.7 nightly only) https://github.com/libretro/libretro-meowPC98/issues/24

I install them using FBI but they don't show in titles or as icons on the home screen.

It seems they all have the same unique id 0xBAC00 (which is the same as the retroarch_3ds config stub, so installing any of the above emulators overwrites that)

**Comment by FateForWindows** [comment]
Has this been fixed on 1.6.9?

**Comment by gingerbeardman** [comment]
@FateForWindows no

**Comment by meepingsnesroms** [comment]
This should be fixed, I just added the banners and icons for those cores and gave them ids.

Wait a day then download the nightlys and test.

**Comment by meepingsnesroms** [comment]
This is solved, the buildbot is not working for 3ds right now for other reasons so I compiled these myself.
This is 81, fuse and np2kai you can install the .cia version and copy the .core files into sdmc:/retroarch/cores or just run the .3dsx
[3ds_cores.zip](https://github.com/libretro/RetroArch/files/1504581/3ds_cores.zip)

**Comment by gingerbeardman** [comment]
Super work. Thanks!
