### ISSUE TITLE
Retroarch Android UI settings issues

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#5569]
## Description
Just a small UI issues. Icons and toggles are missing in Settings.

### Expected behavior
They should appear as it should without any UI glitches

### Actual behavior
The icons are missing in Settings and the toggles are missing in Video settings. They will appear if you scroll down to the bottom

### Steps to reproduce the bug
(reset rRetroarch if needed)
1. Open Retroarch
2. Go to settings
3. Scroll down and up. You will see the bug
4. Go to video settings
5. Scroll down and up. You will see the bug

### Bisect Results
Unknown

### Version/Commit
You can find this information under Information/System Information
- RetroArch: 1.6.7
- Git version: a235c0b

### Environment information
- OS: Android 5.1.1 ARMv7
- Compiler: Clang/LL VM (3.8.256229) 32-bit

### Screenshots

![screenshot_2017-10-20-21-25-23](https://user-images.githubusercontent.com/8687585/31839122-ffbf83b6-b5df-11e7-87a0-87e87ee588b8.png)
![screenshot_2017-10-20-21-25-19](https://user-images.githubusercontent.com/8687585/31839118-fc82233e-b5df-11e7-855b-5612372c3fe8.png)

![screenshot_2017-10-20-21-25-01](https://user-images.githubusercontent.com/8687585/31839112-f96a0c98-b5df-11e7-8910-43d99afd30db.png)
![screenshot_2017-10-20-21-24-55](https://user-images.githubusercontent.com/8687585/31839105-f58025e0-b5df-11e7-9a8f-873baffdd16f.png)

**Comment by orbea** [comment]
No issues here on linux, the OP's account has been deleted so can anyone else reproduce this issue on android?
