### ISSUE TITLE
Weird XMB menu shifting bug

### ISSUE THREAD

**Issue by anyputer** [libretro/RetroArch#5572]
## Description

Move from category while pressing up or down…
the list shifts over to the left a little! This also seems to happen in the Online Updater for some reason!

### Expected behavior

![5c30e95f241a570b86152db47e97fdf0f8b80678](https://user-images.githubusercontent.com/32988993/31855689-929c50b2-b6b0-11e7-9e53-2540ef746c5f.png)

### Actual behavior

![973cf9e73f83407e7e6b7befbbee319003f451ee_1_666x500](https://user-images.githubusercontent.com/32988993/31855693-af6b6250-b6b0-11e7-86b6-31e6221b3a6f.png)

### Bisect Results

This bug isn't actually that old, I'm pretty sure this started happening when they made it so that only the things that are on screen get rendered.

### Version/Commit

- RetroArch: 1.6.7

### Environment information

- OS: Windows 10 64-bit
- Compiler: Just the stable RetroArch that you can get on the website / the buildbot.

**Comment by retro-wertz** [comment]
do not skip entries in template when reporting, especially the section how
to reproduce this:

Steps to reproduce:
1. Move between the items using up+left or up+right or down+right,
down+left.

doesn't seem to happen when moving normally with left, right, up, down.

**Comment by hyarsan** [comment]
Oh, I'm new to GitHub.

**Comment by hyarsan** [comment]
Is anyone going to consider fixing this annoying bug?

**Comment by alfrix** [comment]
i can confirm this happens. 1.6.7

**Comment by hyarsan** [comment]
Anyone else? It still happens!

**Comment by bparker06** [comment]
Paging @heuripedes

**Comment by heuripedes** [comment]
I'm not able to work on this at the moment.

**Comment by bparker06** [comment]
Paging @kivutar

**Comment by sonninnos** [comment]
Yes there is a tiny issue with the animation if navigating too quickly while animating, but at least it is no longer possible to navigate horizontally and vertically at the same time.
