### ISSUE TITLE
Extremely low 3D performance with GL driver on current Nvidia driver + Fall Creator's update

### ISSUE THREAD

**Issue by daninthemix** [libretro/RetroArch#5585]
I just updated Windows to the Fall Creator's update, and my GPU driver to the latest (387.92).

Now the two 3D cores I've tried - Mupen64Plus and Beetle HW in GL mode - are incredibly slow, probably around 10fps (on a GTX1080) when running the GL driver.

I tried the Vulkan driver on Beetle HW and that was running quickly, so this is an issue with OpenGL on either the latest Nvidia driver, or the latest Windows update.

**Comment by fr500** [comment]
So everything was fine before Fall Creator's update?
Tell the one who broke it to fix it :p

**Comment by daninthemix** [comment]
Not sure if relevant but Task Manager shows very high GPU usage when Retroarch is running, even without any content loaded:

![untitled](https://user-images.githubusercontent.com/1974239/31875988-588072f0-b7c8-11e7-82a0-4596640a0f99.png)

**Comment by bparker06** [comment]
I just tested mupen on 376.33 driver (750Ti) with Server 2012r2 (Win8.1), and even with a couple shaders, I get a solid 60fps and 25% GPU load.

**Comment by daninthemix** [comment]
@bparker06 how is that relevant to this discussion? Clealy the issue is either with Windows 10 Fall Creator's Update (most likely), or with Nvidia driver 387.92, as per the title.

**Comment by bparker06** [comment]
Sorry for trying to help.

**Comment by Awakened0** [comment]
I'm on fall creator's with the 387.92 drivers and get around 25% GPU usage in task manager using the GL driver idling at XMB (with Bokeh effect :P) in a window. It's actually lower in game when XMB isn't active; closer to 15% running Kirby 64 with the old Glupen core. If I hit space to unlock the frame rate it goes up to around 30%, spiking to 35% sometimes. This is on an i5 2500k + 970 machine.

**Comment by daninthemix** [comment]
@Awakened0 thanks for posting this - it made me troubleshoot deeper and clearly the issue is with my cfg, as a fresh cfg shows low CPU usage. I have no idea what setting is causing this, or why it started after the FCU was applied.

**Comment by orbea** [comment]
A specific config option could still be broken, do you still have the older config? Can compare it with a fresh config and see if there is any option that reproduces this behavior?

**Comment by daninthemix** [comment]
I did as you said, and it was video_shader_enable = "true".

Well, this turned out to be an extremely obscure issue that probably applies only to me - it's if I have shaders enabled, and my specific shader that I use all the time (Lottes NTSC). Even now, if I set that as the shader, Retroarch uses 100% GPU, even without content loaded, next time it runs. However, thankfully, Lottes Multipass NTSC is fine (~15% usage). What a weird issue.

**Comment by daninthemix** [comment]
I somewhat spoke too soon - it seems that when Retroarch is running without content, but after you've selected a shader, it spikes GPU usage. Clearly the shader isn't applied to the RetroArch menu, but it's as if its in the rendering pipeline somewhere now, jamming things up (yeah, mister technical I know).

**Comment by orbea** [comment]
So I suppose there is a bug in either your video driver that is triggered by that shader and/or that shader could be optimized.
