### ISSUE TITLE
Pixel theme still missing assets.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#5589]
Using latest RetroArch nightly with assets updated:
![screenshot_2017-10-22-15-24-06](https://user-images.githubusercontent.com/6578180/31865975-77429262-b73d-11e7-99fd-664e92a42c04.png)

**Comment by hyarsan** [comment]
I'll give the favorite assets a try.

**Comment by hyarsan** [comment]
there. It works like an charm for me! :)
https://github.com/libretro/retroarch-assets/pull/161

**Comment by blackman91** [comment]
You rock man! Nice job.

**Comment by blackman91** [comment]
It works perfectly now just a little one missing:
![screenshot_2017-10-27-02-00-18](https://user-images.githubusercontent.com/6578180/32091724-feb5c36a-baba-11e7-8705-829bdcdcca24.png)

**Comment by orbea** [comment]
I can confirm this is fixed, also its the wrong repo. Please report missing assets here instead.

https://github.com/libretro/retroarch-assets/issues
