### ISSUE TITLE
Closing content from the quick menu defaults to 'Remove' instead of 'Run'.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#5594]
## Description

When closing content from the quick menu with `Close Content` it will default to the last item on the list which is `Remove` instead of the first item which is `Run`.

This might be related to this in `menu/cbs/menu_cbs_ok.c`.
```
int action_ok_close_content(const char *path, const char *label, unsigned type, size_t idx, size_t entry_idx)
{                                                                                                            
   /* This line resets the navigation pointer so the active entry will be "Run" */
   menu_navigation_set_selection(0);
   return generic_action_ok_command(CMD_EVENT_UNLOAD_CORE);
}
```
https://github.com/libretro/RetroArch/blob/master/menu/cbs/menu_cbs_ok.c

### Expected behavior

When closing content it should default to the first item on the list which is `Run`.

### Actual behavior

When closing content it defaults to the last item on the list which is `Remove`.

### Steps to reproduce the bug

1. Start a core and content from the menu.
2. Open the quick menu with `F1` or the `menu` key/button.
3. Select `Close Content`.
4. It should default to the `Run`, but defaults to `Remove` instead.

### Bisect Results

This appears to have always happened.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 0731bbb81cfb6d2a5bcc4726d993ed61496bd8b8

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-7.2.0`

**Comment by orbea** [comment]
Related issues.
https://github.com/libretro/RetroArch/issues/5595 https://github.com/libretro/RetroArch/issues/5596

**Comment by gouchi** [comment]
This has been fixed by [this commit](https://github.com/libretro/RetroArch/commit/63ba8be2967e3ec3f3fac90a12362204b39b8097).

**Comment by bparker06** [comment]
@gouchi

Load the 2048 core and then Start Core. Now when you close it, it still highlights Remove for me.

**Comment by Kivutar** [comment]
So we have to call menu_navigation_set_selection(0); from somewhere else too.

**Comment by orbea** [comment]
Actually this one looks solved now. Contentless cores can't be tested yet because of issue. https://github.com/libretro/RetroArch/issues/5596

I'm going to close this until it can be reproduced again.
