### ISSUE TITLE
Opening the quick menu with contentless cores defaults to 'Restart' instead of 'Resume'.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#5595]
## Description

When loading a contentless core and then opening the quick menu, it will default to the second item on the list which is `Restart` instead of the first item which is `Resume`.

### Expected behavior

When opening the quick menu it should default to `Resume`.

### Actual behavior

When opening the quick menu it defaults to `Restart` with contentless cores.

### Steps to reproduce the bug

1. Start a contentless core such as `2048`.
2. Open the quick menu with `F1` or your `menu` key/button.
3. It should default to `Resume`, but instead it defaults to `Restart`.

### Bisect Results

```
342bcebc591510248bbfe9ed074e06397aad7e24 is the first bad commit
commit 342bcebc591510248bbfe9ed074e06397aad7e24
Author: twinaphex <libretro@gmail.com>
Date:   Tue Jun 28 07:51:49 2016 +0200

    Set current core type almost immediately after loading new core

:040000 040000 962dbd8c954fe4dedfa8b79a4b854d05cf77eac0 453c1a2c04bf46a2f0f7851f906b2f28c26300db M	tasks
```
342bcebc591510248bbfe9ed074e06397aad7e24

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 0731bbb81cfb6d2a5bcc4726d993ed61496bd8b8

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-7.2.0`

**Comment by bparker06** [comment]
Just to clarify, it seems to only happen if the core is actually started first... just loading the core and then going to the quick menu, it highlights "Resume" correctly.

**Comment by orbea** [comment]
Yes, that is true, but it should also be noted that `Resume` does not work in that scenario since the core is not loaded and probably should be hidden until the core is loaded or alternatively should load the core.

**Comment by orbea** [comment]
Related issues.
https://github.com/libretro/RetroArch/issues/5594
https://github.com/libretro/RetroArch/issues/5596
