### ISSUE TITLE
Xbox one controllers working in menu of Retroarch but not in any game.

### ISSUE THREAD

**Issue by tspoon6** [libretro/RetroArch#5597]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
I'm using windows 10, and two Xbox One controllers wirelessly, however I have tried it wired with same results.

Everything works fine in the menu for both controllers, i've rebinded both controllers countless times, the first controller has "Xbox one controller (user 1) (#1)" as its device index

2nd controller has "Xinput controller (user 2) (#1) as its device index

I've tried updating the joypad profiles but that has not seemed to help

when I start Retroarch I get these messages that flash quickly below

 "100%: xinput controller (user2) configured in port #1"
"100% xbox one controller (user 1) configured in port #0"
"100%: xinput controller (user 2) configured in port #1"

### Expected behavior

both controllers to be able to be used while rom is running

### Actual behavior

Both controllers can move the menu around and be mapped, but does not work when game is loaded, only the first controller works.

### Steps to reproduce the bug
fresh install of retroarch on windows 10 then try to use two wireless xbox one controllers

### Version/Commit

- RetroArch:  https://imgur.com/a/Xje1k

### Environment information

- OS: Windows 10 (fully updated)
- Compiler: Not sure what this is, I apologize for my lack of knowledge on this

**Comment by fr500** [comment]
I just have one but I can't reproduce it at all...

**Comment by fr500** [comment]
while in-game (F1)
Go to quick menu, controls and make sure the input device is retropad

**Comment by tspoon6** [comment]
Thanks for trying and giving advice anyways with one controller.

I got into the F1 menu and changed the input device to retropad and that did not work, I also tried evrey other option in input device just incase and still only had the first controller being able to do anything in the game its self.  (as per before the 2nd controller works fine when I press F1 and am in the menu)

**Comment by fr500** [comment]
Well, does it work with just one connected?

**Comment by tspoon6** [comment]
Oh yeah works exactly how it should, no issues, both controllers work fine when they are the "first" controller

**Comment by fr500** [comment]
I still think you may have hosed your device indexes somehow, I tried with 2 x360 pads at least and it's working properly...

**Comment by tspoon6** [comment]
Hey, well at least we confirmed its on me and not something else, what can I do to reset things

**Comment by fr500** [comment]
remove retroarch.cfg I guess
you don't need to bind anything for xinput pads.

**Comment by tspoon6** [comment]
Did that and same issue as before(switched them to retropad as well), I understand if you can't really keep helping me with this issue as i'm more so asking for help rather than developing something.

I just ended up trying out Dolphin to get these gamecube games working and that has both wireless Xbox one controllers working fine with it.

**Comment by tspoon6** [comment]
*sorry accidently closed the issue, I reopened it
Deleted that file, and I have the same issue, changed them to retropad as well and had no luck

I understand if you can't keep helping me with this issue as im more so asking for help rather then developing something.

I ended up installing Dolphin and that has these gamecube games working just fine with two controllers, however it's too bad as the gui of REtroArch is way nicer.

**Comment by tspoon6** [comment]
*sorry accidently closed this, I reopened it

**Comment by fr500** [comment]
Wait, does it happen with cores other than dolphin?

**Comment by tspoon6** [comment]
Sorry, I have a background in tech support but i'm fairly new to rom/emulators 

The core im using in Retroarch is "gamecube / wii (Dolphin)"   I don't think I had any other options as when I go to the online updater that is the only thing that says gamecube in the title.

What I downloaded and installed that worked with two controllers is Dolphin 5.0 from https://dolphin-emu.org/download/

**Comment by orbea** [comment]
Do other cores have this issue?

**Comment by tspoon6** [comment]
Just tried a core for n64 and a game for that, both controllers worked fine

**Comment by orbea** [comment]
So this is an issue specific to the libretro dolphin-emu core and not other cores or upstream.
https://github.com/libretro/dolphin

The core tracker might be a better place for this. :)

**Comment by tspoon6** [comment]
Totally, REtroArch is not the issue for sure, i'll close this, thanks evreyone.
