### ISSUE TITLE
[Serious] Retroarch 3ds nightly build version disappeared

### ISSUE THREAD

**Issue by zwq939681378** [libretro/RetroArch#5618]
It has became this for quite a few days and only 3ds version disappeared.
![1](https://user-images.githubusercontent.com/29000846/32134108-5c820a90-bc18-11e7-88a1-36ee82362e6c.png)

**Comment by bparker06** [comment]
PSP is also missing and PS3 appears to be several weeks out of date.

**Comment by torin555** [comment]
From what I can see every nightly build folder is empty except for /nightly/windows-msvc2017-desktop/x64/latest/

**Comment by twinaphex** [comment]
notaz broke the psp picodrive version with his merge.

**Comment by fr500** [comment]
fixed 3ds at least.

**Comment by gingerbeardman** [comment]
This can be closed
