### ISSUE TITLE
Retroarch opens to a black screen/stops responding

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#5627]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

After updating several times beginning yesterday afternoon, all nightly releases have caused retroarch.exe to open to a black screen and stop responding.  CPU usage also jumps to ~30% due to retroarch and stays there until force closed. 

### Expected behavior

I expect retroarch to open and function like it did with all previous nightlies (which is all I ever use/d)

### Actual behavior

Isnt this the same as the Bug description? ;p  FWIW after force closing i tried the debug.exe which also produces the same behavior.  I began by loading a default config (same behavior as well) which had me stumped.  I downloaded a new exe to a new folder and that worked so i dropped said exe in my retroarch folder and it was fine.   Updated to the nightly, and it broke again.  So at current im rolled back. 

### Steps to reproduce the bug

1. Double click retroarch.exe or retroarch_debug.exe
2. watch spinning blue circle over black screen where retroarch used to open
3. click for windows generic stops responding window
4. close via task manager
5. delete retroarch.exe and replace with non nightly exe and it works.

### Bisect Results

I dont update daily but i do probably weekly'ish.  I have never had a problem with retroarch or its nightlies (nightlies are all i use ala an updater to make life easier).  However upon midafternoon yesterday when I updated - that was all she wrote.  A relatively recent change for certain is the culprit.

### Version/Commit

Unfortunately I cant open retroarch to find the version.  If i look at the details of the exe it was modified at 10/30/2017 @ 12:15am which still presents the black screen.   I had suspected the exe was the potential source of the problem and had updated through several commits last night which still opened to black screen as well though.

### Environment information
Windows 10 pro x 64

Thanks for all your hard work guys, retroarch is life for me nostaligically and for my kids :)

**Comment by Ryunam** [comment]
Confirmed, this is happening here too on Windows 10 x64. Retroarch crashes immediately upon startup, regardless of the cfg used, and uses the CPU up to 30% until you force-quit it.

**Comment by ofry** [comment]
Now Retroarch latest nightly is running fine.

I think this bug has resolved.

@klepp0906  Please close bug report, if you confirm this.
