### ISSUE TITLE
vulkan: retroarch crashes if video driver is set to vulkan

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#5631]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
retroarch crashes at start if video driver is set to vulkan

### Steps to reproduce the bug

1. go to settings, driver menu
2. choose vulkan as video driver
3. close Retroarch, launch retroarch, it crashes

I can reproduce this bug on 2 different computer, one with an Intel GPU and another with a Nvidia

### Bisect Results

?

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 7ba279703

### Environment information

- OS: Ubuntu 17.10
- GPU: Nvidia drivers 384.90
- Compiler: 

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)

**Comment by ofry** [comment]
Could you provide a log of RA?

**Comment by Zer0one** [comment]
Happen to me too...

**Comment by ofry** [comment]
Can't reproduce it on Windows 8.1 x64., Retroarch x64 d1278306

**Comment by ofry** [comment]
so need output logs of Retroarch.

**Comment by Zer0one** [comment]
Update: doesn't crash on Ubuntu 17.04 with nvidia-387 driver

**Comment by legluondunet** [comment]
my log:

./retroarch
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirection de la sauvegarde vers "/home/legluondunet/Autres_applications/Jeux/Emulateurs/RetroArch/Lien vers retroarch config/savefiles/.srm".
[INFO] Redirection de la savestate vers "/home/legluondunet/Autres_applications/Jeux/Emulateurs/RetroArch/Lien vers retroarch config/savestates/.state".
[INFO] Version de l'API libretro: 1
[INFO] Compilé depuis l'API: 1
[INFO] [Audio]: Set audio input rate to: 29975.00 Hz.
[INFO] [Video]: Video @ fullscreen
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] Vulkan dynamic library loaded.
[ERROR] [Vulkan]: Could not find instance extensions. Will attempt without them.
[ERROR] Failed to create Vulkan instance.
[WARN] Failed to bind API (#6, version 1.0) on context driver "x-egl".
[WARN] Failed to bind API (#6, version 1.0) on context driver "kms".
[WARN] Failed to bind API (#6, version 1.0) on context driver "sdl_gl".
[INFO] Vulkan dynamic library loaded.
[ERROR] [Vulkan]: Could not find instance extensions. Will attempt without them.
[ERROR] Failed to create Vulkan instance.
[ERROR] [Vulkan]: Failed to create Vulkan context.
[INFO] [Vulkan]: Detecting screen resolution 320x240.
[INFO] [Vulkan]: Using resolution 320x240
[INFO] [Vulkan]: Using RGB565 format.
Erreur de segmentation (core dumped)

**Comment by legluondunet** [comment]
it seems to be an ubuntu 17.10 bug: 
$ vulkaninfo 
===========
VULKAN INFO
===========

Vulkan API Version: 1.0.61

INFO: [loader] Code 0 : Found manifest file /usr/share//vulkan/explicit_layer.d/VkLayer_standard_validation.json, version "1.1.1"
INFO: [loader] Code 0 : Encountered meta-layer VK_LAYER_LUNARG_standard_validation
INFO: [loader] Code 0 : Found manifest file /usr/share//vulkan/explicit_layer.d/VkLayer_core_validation.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share//vulkan/explicit_layer.d/VkLayer_unique_objects.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share//vulkan/explicit_layer.d/VkLayer_object_tracker.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share//vulkan/explicit_layer.d/VkLayer_threading.json, version "1.1.0"
INFO: [loader] Code 0 : Found manifest file /usr/share//vulkan/explicit_layer.d/VkLayer_parameter_validation.json, version "1.1.0"
INFO: [loader] Code 0 : Meta-layer VK_LAYER_LUNARG_standard_validation all 5 component layers appear to be valid.
INFO: [loader] Code 0 : Found ICD manifest file /usr/share//vulkan/icd.d/nvidia_icd.json, version "1.0.0"
ERROR: [loader] Code 0 : loader_scanned_icd_add: Attempt to retrieve either 'vkGetInstanceProcAddr' or 'vk_icdGetInstanceProcAddr' from ICD libGL.so.1 failed.
Cannot create Vulkan instance.
/build/vulkan-L06RNr/vulkan-1.0.61.1+dfsg1/demos/vulkaninfo.c:704: failed with VK_ERROR_INCOMPATIBLE_DRIVER

**Comment by legluondunet** [comment]
it's an Ubuntu  bug.

Like explained here:
 https://askubuntu.com/questions/967335/vulkan-does-not-work/967910#967910
I replaced "library_path": "libGL.so.1" by "library_path":  "libGLX_nvidia.so.0" in the file /usr/share/vulkan/icd.d/nvidia_icd.json  and now Vulkan is active and I can launch retroarch no more crash.

It's not a retroarch bug, I close this issue.
