### ISSUE TITLE
[feature request] RW_RAW subtype support in CHDs

### ISSUE THREAD

**Issue by tomgar** [libretro/RetroArch#5632]
I did a convoluted process to convert some ISOs to CHD, involving cdemu (for loading the ISO into a virtual cdrom), cdrdao (to dump the virtual cdrom) and sdlMAME's chdman (0.191).

Here's the cdrdao command which I used with the hopes of preserving everything from the original ISO file:
cdrdao read-cd --read-raw --read-subchan rw_raw --datafile "dump.dao" --device /dev/yourcdromdevice "dump.toc"

The chdman command:
chdman createcd -i "dump.toc" -o "dump.chd"

But I guess I got it wrong, at least for having retroarch compatibility, because it crashes with:
[libretro ERROR] chd_parse track subtype RW_RAW unsupported
[libretro INFO] chd_read_toc: finished
[libretro ERROR] TOC first(99)/last(0) track numbers bad.
Attempt to read LBA 16, >= LBA 0
CDIF Raw Read error
terminate called after throwing an instance of 'MDFN_Error'
[1]    32360 abort (core dumped)  retroarch

Just in case, from the chdman info command, you can see this in each track:
TRACK:1 TYPE:MODE2_RAW SUBTYPE:RW_RAW

I guess it's all reduced to support the RW_RAW subtype.

Thanks.

**Comment by fr500** [comment]
RetroArch doesn't have any kind of CHD support itslef, pleae reopen this in the mednafen psx libretro repo

**Comment by fr500** [comment]
https://github.com/libretro/beetle-psx-libretro
