### ISSUE TITLE
Hard freeze on Raspberry Pi 3 related to V3D_DOUBLE_BUFFER env variable.

### ISSUE THREAD

**Issue by psyke83** [libretro/RetroArch#5633]
## Description

On a Raspberry Pi 3, when video_max_swapchain_images = "2" and a core + content is running, toggling the "bilinear filtering" option in Video settings causes RetroArch to hard freeze.

Toggling bilinear filtering causes no issues when video_max_swapchain_images = "3".

### Expected behavior

Bilinear filtering will de/activate without any issue

### Actual behavior

Once bilinear filtering is toggled, all animation in the menu will freeze. SSH can still function, but it's impossible to terminate the retroarch process. Unfortunately, the verbose RetroArch log does not print any warnings or errors when the freeze occurs. Finally, rebooting via SSH will not complete successfully (with the frozen RetroArch menu remaining onscreen) unless REISUB is issued via a connected keyboard.

### Steps to reproduce the bug

1. Ensure that video_max_swapchain_images is set to 2.
2. Launch RetroArch and start a core + content.
3. Enter the video menu and toggle Bilinear Filtering.

### Bisect Results

I'm 99% certain this is the culprit: https://github.com/libretro/RetroArch/commit/65ef37706cf562e1296bc86b5292175595204523

### Version/Commit
You can find this information under Information/System Information

- RetroArch: latest master, commit d1278306c75495352e50129fd9b09bcf2b883368

### Environment information

- OS: Raspberry Pi 3 running Raspbian stretch
- Compiler: gcc version 6.3.0 20170516 (Raspbian 6.3.0-18+rpi1)

**Comment by psyke83** [comment]
pinging @vanfanel, you might want to take a look at this.

**Comment by vanfanel** [comment]
I can reproduce it, but RA does not currently build on the Pi. I would like to fix this as fast as possible, but I need this solved first:
https://github.com/libretro/RetroArch/issues/5636

**Comment by vanfanel** [comment]
@psyke83 : It's now fixed and merged.
If it works there (it works here), close the issue. Thanks!

**Comment by psyke83** [comment]
Can confirm it's fixed on latest master. Many thanks.
