### ISSUE TITLE
Retroach crashs randomly when using with GeForce Experience Overlay

### ISSUE THREAD

**Issue by NelsonRosenberg** [libretro/RetroArch#5641]
## Description

When the Nvidia GeForce Experience Overlay is on, Retroarch will crash randomly when opening a favorite game or almost always when Closing an opened content from the quick menu. Disabling the overlay makes everything better.

### Expected behavior

I expected it to work normally with the overlay enabled, even if it is not used.

### Steps to reproduce the bug

1. Turn on the overlay
2. Enter a game
3. Press F1 to quick menu, select and click "Close Content"

### Bisect Results

Not sure how to Bisect.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.7 (stable)

### Environment information

- OS: Windos 10

**Comment by orbea** [comment]
@NelsonRosenberg Is this still a problem with the current nightlies? Honestly I would suspect the video driver and / or the OS before RetroArch here.

**Comment by NelsonRosenberg** [comment]
Hi @orbea , thanks for the reply. I have since disabled the shield and didn't test it again with later versions. I can do a quick test if it still happens but I'm not sure how to debug if it does. There is no error in Retroarch itself so it might be some nvidia incompatibility. Do you want me to do anything in particular?

**Comment by fr500** [comment]
GFE overlay works fine here.
It could be video driver dependent. I know the discord overlay causes RA to
crash in D3D10.

**Comment by orbea** [comment]
>  I can do a quick test if it still happens but I'm not sure how to debug if it does

It would be helpful to know if it still happens, a driver or OS update could have also resolved the issues. That said I also am not sure how to debug it further...

**Comment by NelsonRosenberg** [comment]
Well, could not reproduce it anymore, so yay I guess? Must have been an update on the OS or driver then. Cool! This can be closed.

**Comment by orbea** [comment]
Thanks for testing!
