### ISSUE TITLE
[RGUI] broken texts when korean language.

### ISSUE THREAD

**Issue by hong620** [libretro/RetroArch#5643]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When Korean Language setted, change the UI from GLUI or XMB to RGUI
it makes forced to RGUI output the korean text(hangul).
so same problem as overlay system message broken when CJK language, are the whole rgui's texts are totally broken, and can't repair or fix until wipeout app itself and install again.
because there's no proper hangul font for RGUI output yet.

### Expected behavior

until use spesific hangul font(like 80~90's age) for those RGUI's Tiny fixed text sizes, either modern hangul font or without hangul font, both way RGUI must broken on korean texts.
so **until** codes full **ready on** hangul font implant, _at least RGUI have to use english language texts instead korean language texts._

example hangul font for optimized on smaller pixel size text.

둥근모꼴+Fixedsys (fork of 둥근모꼴, same public domain as 둥근모꼴)
[http://cactus.tistory.com/193](http://cactus.tistory.com/193)

OTF file
[둥근모꼴 OTF.zip](https://github.com/libretro/RetroArch/files/1440708/OTF.zip)

WebFont file
[DungGeunMo Webfont.zip](https://github.com/libretro/RetroArch/files/1440709/DungGeunMo.Webfont.zip)

### Actual behavior

![screenshot_2017-11-03-18-50-11](https://user-images.githubusercontent.com/12625315/32369209-b833f134-c0cb-11e7-8a26-d63f260fb6c9.png)
T_T)

### Steps to reproduce the bug

1. set lang to korean
2. change ui to rgui
3. restart app

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.6.7/nigthly but can't check percise build number because all texts are broken]

### Environment information

- OS: armv7a android 4.4.x
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
Since RGUI cannot support non-Latin alphabets currently, maybe we should just force it to always show in English.

**Comment by orbea** [comment]
Also happens with Russian https://github.com/libretro/RetroArch/issues/8267.

**Comment by guoyunhe** [comment]
But even if the UI language is English, when users browse file system, they can still see characters in other languages. They may not able to find the game rom they want to load...

**Comment by msikma** [comment]
I'm having [a problem with Japanese](https://i.imgur.com/PGO5iXY.png) which might be the same as this? This is running on an old 3DS, NTSC-J.

How can I set the UI to always be English despite the default system language being Japanese?

**Comment by guoyunhe** [comment]
I am working on a fix. Please subscribe to this thread. https://github.com/libretro/retroarch-assets/pull/338

**Comment by rtomasa** [comment]
@orbea sorry to bother you. I'd like to use my own bitmap font using the vanilla one as a template. Make command is not aware about any change in the bitmap file, so I'm wondering how can I instruct to the compiler to use my modified bitmap file.
