### ISSUE TITLE
Compilation error since commit 674dbfed1934a8b2511f616f7b92be8df4b3ff81

### ISSUE THREAD

**Issue by allanin** [libretro/RetroArch#5647]
## Description

[Description of the bug / error]

Linux-Distribution: Gentoo / x86_64
Compiler: gcc 5.4

./configure --prefix=/usr --enable-7zip --enable-alsa --disable-floathard --disable-cheevos --disable-cg --enable-sse --disable-dispmanx --enable-egl --disable-fbo --disable-ffmpeg --disable-opengles --disable-opengles3 --disable-jack --enable-kms --disable-ssa --enable-libusb --disable-materialui --disable-miniupnpc --enable-networking --disable-neon --disable-al --enable-opengl --disable-osmesa --disable-oss --disable-pulse --disable-python --disable-sdl --disable-sdl2 --enable-threads --enable-freetype --enable-udev --disable-v4l2 --enable-vulkan --disable-wayland --disable-x11 --disable-xinerama --enable-xmb --enable-libxml2 --disable-xvideo --enable-zlib --enable-dynamic --disable-vg

make

Compilation error

CC deps/miniupnpc/miniwget.c
CC deps/miniupnpc/miniupnpc.c
CC deps/miniupnpc/minixml.c
CC deps/miniupnpc/minisoap.c
CC tasks/task_decompress.c
LD retroarch
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x0): undefined reference to `gl2_renderchain_init'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x8): undefined reference to `gl2_renderchain_init_hw_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x10): undefined reference to `gl2_renderchain_free'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x18): undefined reference to `gl2_renderchain_deinit_hw_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x20): undefined reference to `gl2_renderchain_start_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x28): undefined reference to `gl2_renderchain_check_fbo_dimensions'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x30): undefined reference to `gl2_renderchain_recompute_pass_sizes'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x38): undefined reference to `gl2_renderchain_render'
collect2: error: ld returned 1 exit status
make: *** [Makefile:148: retroarch] Error 1

[What you expected to happen]

Working compilation like with last working commit bde5a6dc19ef60b95a2d04456ea184ea8178cede

**Comment by orbea** [comment]
Just making a clickable link.... 674dbfed1934a8b2511f616f7b92be8df4b3ff81

**Comment by orbea** [comment]
This is caused by `--disable-vbo` and can be reproduced with.
1. `./configure --disable-fbo`
2. `make`
```
LD retroarch
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:/home/orbea/gittings/installed/RetroArch/gfx/drivers_renderchain/gl2_renderchain.c:1112: undefined reference to `gl2_renderchain_init'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x8): undefined reference to `gl2_renderchain_init_hw_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x10): undefined reference to `gl2_renderchain_free'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x18): undefined reference to `gl2_renderchain_deinit_hw_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x20): undefined reference to `gl2_renderchain_start_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x28): undefined reference to `gl2_renderchain_check_fbo_dimensions'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x30): undefined reference to `gl2_renderchain_recompute_pass_sizes'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x38): undefined reference to `gl2_renderchain_render'
collect2: error: ld returned 1 exit status
make: *** [Makefile:148: retroarch] Error 1
```

**Comment by orbea** [comment]
Thisi is caused by `--disable-fbo` and can be reproduced with.
1. `./configure --disable-fbo`
2. `make`
```
LD retroarch
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:/home/orbea/gittings/installed/RetroArch/gfx/drivers_renderchain/gl2_renderchain.c:1112: undefined reference to `gl2_renderchain_init'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x8): undefined reference to `gl2_renderchain_init_hw_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x10): undefined reference to `gl2_renderchain_free'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x18): undefined reference to `gl2_renderchain_deinit_hw_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x20): undefined reference to `gl2_renderchain_start_render'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x28): undefined reference to `gl2_renderchain_check_fbo_dimensions'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x30): undefined reference to `gl2_renderchain_recompute_pass_sizes'
obj-unix/gfx/drivers_renderchain/gl2_renderchain.o:(.data+0x38): undefined reference to `gl2_renderchain_render'
collect2: error: ld returned 1 exit status
make: *** [Makefile:148: retroarch] Error 1
```
