### ISSUE TITLE
Fast forward key should show status message

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#5667]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The fast forward key ( L by default ) should display an status message that says "Fast forward." just like how E ( The default slowmotion key ) shows "Slow motion."

### Expected behavior

Fast forward key ( L by default ) should show status message "Fast forward."

### Actual behavior

No status message.

### Steps to reproduce the bug

1. Fast forward using the L key
2. Look at the status message

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: RetroArch Oct 31 2017
### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW

**Comment by RobLoach** [comment]
In the yellow OSD text at the bottom of the screen?

**Comment by hyarsan** [comment]
Yes the yellow text! "Slow motion." would need to be changed to ⏪ because of consistency though.

**Comment by RobLoach** [comment]
Tried UTF8 character and it looked like this:

![slow](https://user-images.githubusercontent.com/25086/32815080-228d9af0-c980-11e7-85f1-4f8c03ac79df.png)

Guess we'll have to stick with "Fast forward."

**Comment by hyarsan** [comment]
Consistency is key :D
