### ISSUE TITLE
[Android/TV] Regression on Sony Bravia on remote and joypads 

### ISSUE THREAD

**Issue by frranck** [libretro/RetroArch#5668]
## Description

No input work anymore in main menu. (remote control or joypads) 

### Expected behavior

Input to work

### Actual behavior

Blocked in menu

### Steps to reproduce the bug

1. run retroarch 
2. blocked in menu

### Bisect Results

It was working 6 months ago. (before the layout of the menu was improved.)

### Version/Commit

current android play store version.

### Environment information

Sony Bravia
Device name: KD-65XD7505
Version: 7
Android security patch level 1 August 2017
Kernel version 3.10.79

**Comment by twinaphex** [comment]
I can test this on a Bravia 2015 TV if it helps.

**Comment by Oibaf66** [comment]
It works for me (Android Bravia 2015, Lollipop, KDL-W808C model).

**Comment by frranck** [comment]
It's working now. It prob was a controller issue. Sorry about that.
