### ISSUE TITLE
Core Info Names issue

### ISSUE THREAD

**Issue by Alex793** [libretro/RetroArch#5672]
Hi, long time since I didn't update my nightly on iOS, so tested the last nightly and have a little issue.

Core infos names don't work and in the core update section, all is blank.

With this bug, impossible to launch a rom by "load content".

Tested with the exact same config and also with a fresh config with latest infos files etc. The latest infos files are not the problem because they works on my September 1.6.7 build.

**Before (1.6.7 from September) :** 

Load Core
![img_3664](https://user-images.githubusercontent.com/428805/32763094-ddadb12c-c8fd-11e7-96de-1c95977c33e1.PNG)
 
Core Updater
![img_3665](https://user-images.githubusercontent.com/428805/32763100-ecc991bc-c8fd-11e7-8321-61808da1f602.PNG)

**Last Nightly :** 

Core Updater
![img_3666](https://user-images.githubusercontent.com/428805/32763108-fb80da8a-c8fd-11e7-924e-4e8045698fae.PNG)

Load Core
![img_3667](https://user-images.githubusercontent.com/428805/32763109-fba0b6a2-c8fd-11e7-976b-f510c9cf85d3.PNG)

Load Content
![img_3668](https://user-images.githubusercontent.com/428805/32763110-fbc6e20a-c8fd-11e7-82ea-f931dd31d8f1.PNG)

**Comment by SpiralCut** [comment]
I can verify I have the same issue using a build from 11/13 and the glui interface.  The problem is that RetroArch does NOT seem to be finding the core info files no matter what directory you set info too and download the files.  This issue has been around since at least 11/6 which was my most recent build since 1.6.6

**Comment by fr500** [comment]
is this still happening?

**Comment by Alex793** [comment]
Hi fr500, nope sorry I forgot, it's ok since few last builds.

You can close it.

Thanks for your work :-)
