### ISSUE TITLE
Use a new OSD font that has UTF-8 Glyphs

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5678]
## Description

Have the ability to display UTF-8 characters, like [⏩ or `⏩` Fast Forward character](http://www.fileformat.info/info/unicode/char/23e9/index.htm) in the on-screen display messages. This was found as part of #5667 .

### Expected behavior

When using `⏩` in the OSD messages, expected behavior is to have it display the UTF-8 character correctly.

### Actual behavior

It displays a block instead of the UTF-8, as shown below:

![aaaa](https://user-images.githubusercontent.com/25086/32817283-d762967e-c98a-11e7-9711-3865c696f808.png)

### Steps to reproduce the bug

1. Do a search and replace for "Slow motion." to `⏩`
2. Recompile
3. Run a game
4. Hold the Slow Motion key (default is e)
5. See the block appear, and not the UTF-8 `⏩` character

### Bisect Results

None.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: `b50a667335082dbfa24eefa60fbfc4e1768c7daf`

### Environment information

- OS: Linux
- Compiler: gcc

**Comment by fr500** [comment]
You mean like this?

![image](https://user-images.githubusercontent.com/1721040/32856519-0de249be-ca13-11e7-8dc4-1d3cbd8db1c3.png)

<3 nuklear

**Comment by bparker06** [comment]
@RobLoach It already supports UTF-8 in XMB, you just need to set a proper font that has the characters you want. By default the OSD does not use the XMB menu font even, it uses [generic system fonts](https://github.com/libretro/RetroArch/blob/12ae59a197faebd870968189aa7371859a976748/gfx/drivers_font_renderer/freetype.c#L269) that (actually, neither of which) probably support those glyphs.

**Comment by RobLoach** [comment]
Perhaps we could compile in a new (public domain?) OSD font that has those glyphs.

**Comment by alfrix** [comment]
The only font that i think it would cover these needs it's [unifont](http://unifoundry.com/unifont.html) (GPLv2)

⏩ Fast forward
⏪ Rewind
⏵ Resume
⏯ Slow Motion
⏸ Pause
⏮ Skip back
⏭ Skip forward

BLACK RIGHT-POINTING DOUBLE TRIANGLE (U+23E9)
BLACK LEFT-POINTING DOUBLE TRIANGLE (U+23EA)
BLACK MEDIUM RIGHT-POINTING TRIANGLE (U+23F5)
BLACK RIGHT-POINTING TRIANGLE WITH DOUBLE VERTICAL BAR (U+23EF)
DOUBLE VERTICAL BAR (U+23F8)
BLACK LEFT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR (U+23EE)
BLACK RIGHT-POINTING DOUBLE TRIANGLE WITH VERTICAL BAR (U+23ED)

**Comment by alfrix** [comment]
IMHO a better solution would be to draw an image before the text, assets for playback speed, and a generic one with an "i" of information would need to be created, but opens the possibilities for retroachievements logos...

**Comment by RobLoach** [comment]
Unifont worked well....

![screenshot at 2017-11-17 02-31-09](https://user-images.githubusercontent.com/25086/32935744-6a976ffe-cb3f-11e7-8d83-1dc585ba25c6.png)

Rather large for a TTF font, however. Here's the patch that I used to test: [osd-font.patch](https://github.com/libretro/RetroArch/files/1481392/osd-font.txt) ... Need to place unifont.tff at osd-font.ttf.

**Comment by RobLoach** [comment]
We could add [UniFont](http://unifoundry.com/unifont.html) to [retroarch-assets](https://github.com/libretro/retroarch-assets/), and then add `retroarch-assets/fonts/osd-font.ttf` to the font discovery array.

Do any of the [below fonts](https://github.com/libretro/RetroArch/blob/master/gfx/drivers_font_renderer/stb.c#L184-L218) not have the glyphs we want?

``` c
static const char *font_renderer_stb_get_default_font(void)
{
   static const char *paths[] = {
#if defined(_WIN32)
      "C:\\Windows\\Fonts\\consola.ttf",
      "C:\\Windows\\Fonts\\verdana.ttf",
#elif defined(__APPLE__)
      "/Library/Fonts/Microsoft/Candara.ttf",
      "/Library/Fonts/Verdana.ttf",
      "/Library/Fonts/Tahoma.ttf",
      "/Library/Fonts/Andale Mono.ttf",
      "/Library/Fonts/Courier New.ttf",
#elif defined(__ANDROID_API__)
      "/system/fonts/DroidSansMono.ttf",
      "/system/fonts/CutiveMono.ttf",
      "/system/fonts/DroidSans.ttf",
#elif defined(VITA)
      "vs0:data/external/font/pvf/c041056ts.ttf",
      "vs0:data/external/font/pvf/d013013ds.ttf",
      "vs0:data/external/font/pvf/e046323ms.ttf",
      "vs0:data/external/font/pvf/e046323ts.ttf",
      "vs0:data/external/font/pvf/k006004ds.ttf",
      "vs0:data/external/font/pvf/n023055ms.ttf",
      "vs0:data/external/font/pvf/n023055ts.ttf",
#else
      "/usr/share/fonts/TTF/DejaVuSansMono.ttf",
      "/usr/share/fonts/TTF/DejaVuSans.ttf",
      "/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansMono.ttf",
      "/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf",
      "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
      "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
#endif
      "osd-font.ttf",
      NULL
   };
```

I've confirmed `DejaVuSansMono-Bold.ttf` doesn't have them.

**Comment by alfrix** [comment]
checked fileformat.info for support and apart from unifont this ones support them too:

EversonMono 
EversonMono-Bold 
EversonMono-BoldOblique 
EversonMono-Oblique 
Quivira 
Segoe UI Emoji 
Segoe UI Symbol 
Symbola 

But those fonts have licensing issues.

**Comment by alfrix** [comment]
I have modded DejaVuSans Condensed to have those glyphs and one extra:
🏆⏮⏪⏵⏯⏸⏩⏭ 
[DejaVuSansCondensed_retroarch.zip](https://github.com/libretro/RetroArch/files/1484852/DejaVuSansCondensed_retroarch.zip)

**Comment by RobLoach** [comment]
Could you stick a ` around those so that the characters show rather than the emoji?

**Comment by alfrix** [comment]
they won't unless you install the font and configure the browser to use it, here is something better a screenshot:
![captura](https://user-images.githubusercontent.com/1247237/32983390-62715d2e-cc72-11e7-96db-a77106081562.PNG)

**Comment by RobLoach** [comment]
@alfrix Submitted https://github.com/libretro/RetroArch/pull/5710 to allow loading fonts/osd-font.ttf from retroarch-assets.

**Comment by RobLoach** [comment]
While this is nice, I'm not sure this is actually the right approach. Having the icon appear as part of the message hash seems wrong.

May want to split the icon into its own part of the message queue. The icon is not translatable, it's an icon.

**Comment by gingerbeardman** [comment]
If the goal is to have icons then you could create your own font containing just those, or simply subset Unifont. 

If the goal is to have icons and "perfect" Unicode support then using the full 57,000+ character Unifont seems worthwhile regardless of its large 12MB size. Approximately one third kid all characters (20,000) are for Chinese, Japanese and Korean support. 

That said, Unifont exists in formats other than TTF. The source is a file that contains one line per character with rows of pixels encoded as hex. You could use that data but you'd have to write your own parser and renderer.

**Comment by RobLoach** [comment]
Going to close this one. Unsure using Glyphs for icons may not be the right way around this. Preferably we'd likely want to have the OSD display graphic icons provided by the theme.

We could use a similar system for when getting an Achievement. Display the badge alongside the OSD message.
