### ISSUE TITLE
Thumbnail Boxart Doesn't Show for Gameboy Color Games With (GB Compatible) in The Title

### ISSUE THREAD

**Issue by BParks21** [libretro/RetroArch#5683]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
None of my gbc roms display thumbnails with (GB Compatible) in the title of their name. Example my Pokemon Silver rom is Titled "Pokemon - Silver (USA, Europe) (SGB Enhanced) (GB Compatible.)

### Expected behavior
For thumbnails to be displayed.

### Actual behavior
No thumbnails are displayed.

### Steps to reproduce the bug

1. Open Retroarch.
2. Scan a sgb enhanced and gb compatible game.
3. Check for a displayed thumbnail.

### Bisect Results
I don't remember if this was working correctly at one point or not?

### Version/Commit

- RetroArch: [version/commit]
1.6.7 - 814f18b7
### Environment information

- OS: Windows 10 64bit (Latest)
- Compiler: NA
![screenshot 3](https://user-images.githubusercontent.com/12180630/32895580-87d911bc-caae-11e7-8ec4-83416f95221f.png)

**Comment by alfrix** [comment]
Go to retroarch folder (usually %appdata%\retroarch)> thumbnails > Nintendo - Game Boy Color > Named_Boxarts
and check if the image name has the exact same name, if it doesn't change it

**Comment by WizLizard** [comment]
I would like to say that it is simply any game with (GB Compatible) in the name. Yes i already new this and it works. However (GB Compatible) is part of the proper naming of the ROM so why make it so we have to go and change this for every single ROM with this in the title? RetroArch is listing the proper title in the GUI this includes any game with (GB Compatible) so why not make the boxarts match? There are literally hundreds or GBC ROM's with (GB Compatible) in the title.

**Comment by Axiphel** [comment]
It looks like RetroArch is still using an old `version 20160201-045247` dat file, which has no '(GB Compatible)' rom names, instead of the newer `version 20170908-093052` dat. So the (GB Compatible) boxarts aren't being sent out even though they [exist](https://github.com/libretro-thumbnails/Nintendo_-_Game_Boy_Color/blob/49ae8b45513a6b4417a5ff027285b604ebd4f13f/Named_Boxarts/Pokemon%20-%20Silver%20Version%20(USA,%20Europe)%20(SGB%20Enhanced)%20(GB%20Compatible).png).

**Comment by alfrix** [comment]
try online-updater > update databases 
and update your thumbnails

**Comment by WizLizard** [comment]
@Axiphel How can i get it to use the updated dat file?

**Comment by WizLizard** [comment]
@Axiphel How can i get it to use the updated dat file? I'll just manually download them for now. Didn't know i could do that.

**Comment by WizLizard** [comment]
@Axiphel I tested the new thumbnails. They're much better but it seems some are still incorrectly named missing the (GB Compatible) but much better! Many less are missing boxarts.

**Comment by alfrix** [comment]
seems that gameboy color is only at 55.84% completion (https://github.com/RobLoach/libretro-thumbnails-check)
if you want to contribute, here is the corresponding repository:
https://github.com/libretro-thumbnails/libretro-thumbnails
any help would be apreciated

**Comment by orbea** [comment]
As explained in the previous comment, this should be fixed in the libretro-thumbnails repo. Please make an issue or PR for that repo if you still are missing any thumbnails, thanks!
