### ISSUE TITLE
Not Being able to see cores in Core Updater

### ISSUE THREAD

**Issue by Danver2618** [libretro/RetroArch#5686]
#Description
I am using RetroArch on Android running the lastest nightly i.e. 2017-11-16-RetroArch.apk and having the problem of the name of the cores not appearing in the core updater

#Expected behavior
I am assuming that there should be the system name followed by the core name in alphabetical order

#Actual behavior
There are no names and the cores are arranged in random order

#Steps to reproduce the bug
1. Go to online updater
2. Go to core updater

#Version/Commit
- Build date: Nov 16 2017
- Git version: 360e2e5
- CPU Features: NEON VFPv3 VFPv4 ASIMD
- CPU Architecture: ARMv8
- CPU Cores: 8
- RetroArch: 2017-11-16-RetroArch nightly

#Environment information
- OS: Android
- Compiler: Clang/LLVM(3.8.256229 ) 32-bit

**Comment by bparker06** [comment]
Attaching your screenshot from Discord for reference:

![img](https://media.discordapp.net/attachments/184109094070779904/380652485771264002/Screenshot_2017-11-16-15-05-14.jpg?width=1000&height=563)

**Comment by LootusMaximus** [comment]
This happens to me too. Last working nightly i tried was at the end of october. The core updater text is invisible and not in order. Cores i already have show file name. And tend to crash. Nightly apks are unusable for me

**Comment by bparker06** [comment]
What devices do you guys have exactly?

**Comment by LootusMaximus** [comment]
content://media/external/file/15821

**Comment by LootusMaximus** [comment]
I have LG tribute 2 LGLS665

**Comment by LootusMaximus** [comment]
Another thing about the android nightly. If i try to load content with no core the core show invisible text and then crashes when i click it. If i load core first then content it actually shows its real name (FCEUmm) and works when i click

**Comment by bparker06** [comment]
@Danver2618 what device are you using?

**Comment by Danver2618** [comment]
I am using Asus Zenfone 2 laser @bparker06

**Comment by bparker06** [comment]
should be fixed in 07f39198, can you confirm with the latest nighty?

**Comment by Danver2618** [comment]
It's fixed in latest nightly. Thank you.

**Comment by Danver2618** [comment]
It's fixed in latest nightly. Thank you.
