### ISSUE TITLE
Unable to map mouse buttons to User inputs

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro/RetroArch#5687]
## Description

It is not possible to map physical mouse buttons (specifically 'side' buttons 4/5) to user inputs.

This is necessary to accurately replicate the Sega Saturn mouse peripheral, due to its three primary buttons and additional start button.

### Expected behavior

When binding a user input I'd like to be able to press a mouse button and have that mapped as an input.

### Actual behavior

Mouse buttons are completely ignored when prompted to enter a binding input (only joypad and keyboard are monitored)

### Steps to reproduce the bug

1. Got to Settings > Input > Input User 1 Binds
2. Highlight and select "User 1 Start button" (or any other control)
3. At the prompt, press any mouse button
4. Observe no response from RetroArch as timeout expires.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.7 - No Core
- Build Aug 21 2017
- Git version: a235c0b
- Compiler: MinGW (6.3.0) 64-bit

### Environment information

- OS: Windows 10 (all platforms?)
- Compiler: Official download, not a custom build.

**Comment by fr500** [comment]
Hmmm, no not really, I think increasing the number of buttons in the API would be way to go for this.

**Comment by hiddenasbestos** [comment]
OK - I submitted a change to libretro-arb (although it looks kind of quiet). Thanks for your quick reply.
