### ISSUE TITLE
shader menu - remember my position

### ISSUE THREAD

**Issue by Thrakk** [libretro/RetroArch#5688]
kind of like a bug

When testing shaders:
Everytime I switch from a game to the menu it remembers where I left off... except if I left off while applying shaders in the 'Load Shader Preset' file browser. Meaning I have to click that button again and navigate though many libretro shader folders to get back to the folder with the shader I last loaded. 

It would be much quicker testing out shader presets if the menu screen had the option to remember where I last was in the shader folders.

**Comment by fr500** [comment]
Please use the issue template when reporting problems.
