### ISSUE TITLE
Enable Discord's Rich Presence in RetroArch

### ISSUE THREAD

**Issue by vpontin** [libretro/RetroArch#5690]
## Description
Well, yesterday [Discord](https://discordapp.com/) messenger launched its brand new Rich Presence API which allows users to send more detailed data about what they're playing (instead of the very simple MSN-like "Playing [game name]" used before) plus some naughty things like embedded/connected netplay, spectate and other data transmissions.

![image](https://user-images.githubusercontent.com/3485505/33106976-1b98690e-cf1c-11e7-9f98-ec8006e718b6.png)

The game would be detected in a way like how retroachivements detect what game is running and set up its proper achivements.

### More about Rich Presence

The full features possible with rich presence API are described [here](https://discordapp.com/rich-presence) and [here](https://github.com/discordapp/discord-rpc) (thanks @RobLoach for the link).

**EDIT:** [Here](https://discordapp.com/developers/docs/topics/rich-presence) is a more detailed documentation, for developers. And a guide for users/players is [here](https://support.discordapp.com/hc/en-us/articles/115001557452-Game-Invites-and-Detailed-Status).

It would be awesome if retroarch could have support of this! Thanks in advance

**Comment by fr500** [comment]
I would certainly like this.

**Comment by Aerzzy** [comment]
I agree, this could be something that is very nice to have. If you were to add it, **1** could be the icon of RetroArch. **2** could be the icon of the emulator you are using. **3** could display the name of the ROM you are using. And **5, 6, 7, 8 and 9** could display Netplay stats. I don't know how this could be worked into RetroArch and it's just and idea for something that could be cool.

**Comment by rogueyoshi** [comment]
Rich Presence also allows you to host and join matches for games that have the integration. If someone were to implement this into Retroarch, it would be pretty revolutionary.

**Comment by RobLoach** [comment]
The [Rich Presence Discord API](https://github.com/discordapp/discord-rpc) looks great. There's an example of using it in C asyncronously:
https://github.com/discordapp/discord-rpc/blob/master/examples/send-presence/send-presence.c

**Comment by lilbud** [comment]
Has this been worked on?

**Comment by vpontin** [comment]
Good question! Discord itself added support for some games (and non-games software like Spotify); and the ones still without (like Minecraft) already have some mod to add RP too.

**Comment by fr500** [comment]
The API includes a ton of deps we can't merge.
Also it's a bit idiotic in that it doesn't actually use the web services.

It talks with a discord client via RPC which means it would only work on PC platforms.

**Comment by RobLoach** [comment]
@fr500 Think we could have it as `HAVE_DISCORD`, and bring in the dependencies during the build process? We should avoid having it on Buildbot, at least until its proven. Could even run it on a fork WIP.

**Comment by fr500** [comment]
Seems leaner than I remember but still, serialization.cpp can't be used, it would need to be reimplemented with the json serializer we already have.

**Comment by fr500** [comment]
And it includes pre-compiled discord dependencies in the source tree

**Comment by fr500** [comment]
https://github.com/discordapp/discord-rpc/issues/70
We can't have badges per-game FYI, adding the issue for tracking

**Comment by lilbud** [comment]
Dolphin recently had Rich Presence support officially merged.
https://dolphin-emu.org/download/dev/2cfdf89898c4689884fbffb1c693ec24a7083f66/?nocr=true

**Comment by FM1337** [comment]
Is this still being worked on or nah?

**Comment by twinaphex** [comment]
We need somebody pushing it forward.

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/pull/7043

**Comment by FM1337** [comment]
Was that the final piece needed, or is there a bit more needed?

**Comment by bparker06** [comment]
Closing this since it has been merged already
