### ISSUE TITLE
Downloads fail if too long (Content & updates)

### ISSUE THREAD

**Issue by macmpi** [libretro/RetroArch#5692]
Issue on Pi 2.1RC6 (even 2.0), initially reported through [Lakka](https://github.com/libretro/Lakka-LibreELEC/issues/281) but likely pertains to RetroArch code, as confirmed by other impacted users in orginal report.

Content download such as thumbnails fails to complete even-though I have sufficient disk space. Download % increases, and then resets to 0.
[`Task Failed`](https://github.com/libretro/RetroArch/blob/master/libretro-common/queues/task_queue.c#L90) message appears on screen after few tries.
Actually I could not find any interim download file anywhere even during download process...
Same for Lakka updates (download % gets to about 10-15% max and then restarts)

For smaller thumbnails archives (like Atari 2600, Coleco thumbnails), there is no problem: file is downloaded and extracted fine into final place.
MAME, N64, SMS thumbnail archives all fail for instance.

This has has also been reported on ["pure" Retroarch](https://github.com/libretro/Lakka-LibreELEC/issues/281#issuecomment-344213612).

It could be related to timeout issue denoted in http download code (assuming too long download tasks may be killed somewhere):
[`/* FIXME: This wouldn't be needed if we could wait for a timeout */`](https://github.com/libretro/RetroArch/blob/master/tasks/task_http.c#L121)
Maybe @twinaphex & al. may have ideas on this apparently well-known and longstanding issue?

Thanks for feedback and confirmation.

**Comment by RobLoach** [comment]
No more thumbnail packs.

**Comment by macmpi** [comment]
Thanks for feedback: unsure it is definitely closed for good at this point though.
Indeed the issue was **not limited to thumbnail packs**... was same for all type of downloads, including updates & al, [affecting Lakka for instance](https://github.com/libretro/Lakka-LibreELEC/issues/281).

@fr500 seems to imply [the download part may be indeed fixed](https://github.com/libretro/RetroArch/issues/7278#issuecomment-496031029) (unclear when), but @AshleyPikachu reports in that same issue, unzipping may still be a problem lately?

**Comment by RobLoach** [comment]
What content outside of thumbnail packs would this apply to? I've been able to download the MAME and Assets on RPi without issue.

**Comment by macmpi** [comment]
Would be nice to confirm with [built-in Lakka updater](https://github.com/libretro/Lakka-LibreELEC/issues/281#issuecomment-344131010) on Pi, which leverages same download infrastructure.
Tracking-down that original problem led me to open this issue related to content which share the same download method...
Unfortunately I can't test myself for now.
