### ISSUE TITLE
Some questions about retroarch on Nintendo switch

### ISSUE THREAD

**Issue by iOS4all** [libretro/RetroArch#5698]
Hi there. We all know the switch is already hacked on 3.0.0 I saw days ago a vote about getting retroarch on xbox one or Nintendo switch. And the switch is winning on that vote. So when we can see a port of retroarch on switch please?
Also can dolphin and posspp cores work on switch?

The switch and nvidia shield tv are sharing many things. And it supports vulkan as well.
Also can we get JIT dynarec without kernel or it's required to work? However the hackers getting full kernel access on switch.

This all my questions about retroarch on switch.
Thanks

**Comment by hizzlekizzle** [comment]
I don't think any of that is fully known yet. The poll was just to determine which hardware to purchase.

**Comment by iOS4all** [comment]
Thanks for your answer.

**Comment by RobLoach** [comment]
May get some good answers over at [the forums](https://forums.libretro.com).
