### ISSUE TITLE
Load content with IPS patch in RetroArch

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#5705]
One feature that I think would be really neat is if you can load content with an IPS patch without manually doing it yourself first.

**Comment by hizzlekizzle** [comment]
if you mean softpatching, it already happens as long as you have the patch in the same directory with the same name. For example foo.sfc and foo.ips.

**Comment by hyarsan** [comment]
Whoa, that's really cool! But what if you don't want to constantly keep renaming your roms?

**Comment by orbea** [comment]
What kind of usecase would require renaming your roms all the time? You might have to come up with a script to find any patch files and rename them at the same time.

**Comment by ofry** [comment]
And core must be "need_fullpath = false". So Genesis games out of luck with this, for example.
