### ISSUE TITLE
[Feature Request] _NET_WM_PID support

### ISSUE THREAD

**Issue by Q3CPMA** [libretro/RetroArch#5726]
Hello,

## Description

There doesn't seem to be any _NET_WM_PID support. This is useful when using signals to hide/show mesa's Gallium HUD.

### Expected behavior

_NET_WM_PID is set.

### Actual behavior

_NET_WM_PID isn't set. Checked via `xprop | grep -iF pid` and `xdo pid`.
[What is actually happening]

### Steps to reproduce the bug

1) Launch retroarch.
2) `xprop | grep -iF pid`

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 8e8bdaaab (oct 21)
### Environment information

- OS: Gentoo GNU/Linux
- Compiler: gcc 5.4.0

**Comment by orbea** [comment]
> This is useful when using signals to hide/show mesa's Gallium HUD.

Would you mind explaining how this would be done? :) I am familiar with the Gallium HUD so you can skip the basics.

**Comment by Q3CPMA** [comment]
With the environment variable `GALLIUM_HUD_TOGGLE_SIGNAL`. Set it to 10 for USR1, for example.

**Comment by orbea** [comment]
That is pretty handy, thanks!

I also found this.
https://manerosss.wordpress.com/2017/07/13/howto-gallium-hud/

**Comment by orbea** [comment]
I confirmed this works for RetroArch.

For example, RetroArch can be started with.
```
GALLIUM_HUD_TOGGLE_SIGNAL=10 GALLIUM_HUD=fps ./retroarch
````
And then this command will toggle the gallium fps HUD.
```
kill -10 $(pidof retroarch)
```
However this will only work for people using gallium HUD which is only in mesa with nouveau, amd and the llvmpipe. Intel uses something else and does not have an equivalent function.

**Comment by Q3CPMA** [comment]
I suggest `kill -USR1 $(xdo pid)`, so multiple retroarch instances don't pose any problem. The only thing lacking in gallium HUD is the possibility of displaying a value without a graph, for me.
