### ISSUE TITLE
Custom lobby/mtim addresses

### ISSUE THREAD

**Issue by mariogalmonte** [libretro/RetroArch#5732]
Libretro mitm/lobby server used as "relay" is too far from many countries. E.g. Chile, South Africa, New Zealand...
http://newlobby.libretro.com/add/
and http://newlobby.libretro.com/list/ default lobby addresses are actually hard-coded.
Turning it to menu options could let the users to choose a custom lobby/mitm server.

Basic documentation to install new relay / lobby servers could be convenient, too.

**Comment by fr500** [comment]
We have discussed about this, adding a way to register your own mitm so it talks to the main lobby server but I don't think we reached any conclusions

@bparker06

**Comment by orbea** [comment]
Closing in favor of the more detailed and newer issue https://github.com/libretro/RetroArch/issues/8124.
