### ISSUE TITLE
Pushing down button in menu cause exception

### ISSUE THREAD

**Issue by rapiertg** [libretro/RetroArch#5739]
## Description

In some situations pushing down button cause retroarch to crash.

### Expected behavior

Not to crash :)

### Actual behavior

An exception occured screen

### Steps to reproduce the bug

1. Open RetroArch
2. Push 2 times right to Favourites
3. Push down while Favourites are empty

The same is for other menus that are empty and at the end of each console menu. Happened to me once or two times when going left in main menu too.

### Version/Commit

- RetroArch: 1.6.8
- Previous stable too.

### Environment information

- OS: Luma 8.1.1

**Comment by meepingsnesroms** [comment]
"rgui"(Green DOS style menu) works fine.

If you cant get to the driver selection just run RetroArch once to generate a config and change menu_driver = "xmb" to "rgui" in a text editor.

**Comment by hyarsan** [comment]
I was already using rgui: https://github.com/libretro/RetroArch/issues/5873

**Comment by hyarsan** [comment]
Yeah, but this was only one of the crashes but tbh, it is so annoying to keep opening RetroArch after each crash. I would love to have this fixed though so I will do my best.

**Comment by twinaphex** [comment]
@meepingsnesroms says this can be closed now.
