### ISSUE TITLE
Bad compilation of asstes for PSV (on 1.6.8-1.6.9)

### ISSUE THREAD

**Issue by JesterIOS** [libretro/RetroArch#5745]
## Description
(Sorry for my bad English)
In 1.6.8-1.6.9 changed VPK file (138mb -->> 92.7mb after #5676), which allows you to install much faster, then were in 1.6.6 and older. But datas were moved to a separate .zip file and were lost some asstes files

### Expected behavior

A compleate app,

### Actual behavior

We have missing beatiful fonts (with unicode symbols and support of international languages) and low quality text input window

![2017-11-22-141953](https://user-images.githubusercontent.com/30769120/33115253-f996ee3a-cf92-11e7-9de8-159b45eb2550.jpg)
![2017-11-22-145529](https://user-images.githubusercontent.com/30769120/33115936-64e37cd8-cf95-11e7-8295-c09447407062.jpg)

### Steps to reproduce the bug

1. Download and install .VPK file
2. Unzip RetroArch_data.zip (Vita buildbot foulder) to ux0:data
3. Start the app

### Version/Commit

- RetroArch: [1.6.8-1.6.9/after #5676 commit]

**Comment by twinaphex** [comment]
@frangarcj - Is he simply forgetting to put the data files in the proper place or is something else going on?

**Comment by frangarcj** [comment]
His retroarch.cfg is linked to app0

**Comment by fr500** [comment]
Well, I guess for the next release we should explain the users how to update.
For now all that he has to do is go to directories, and press start in all the dirs, that's all.

**Comment by rsn8887** [comment]
I got the official stable Vita release 1.6.9 here:
Where is that data file that goes with the official "stable" Vita release?

**Comment by fr500** [comment]
This is more likely not an issue anymore (besides the fact that users need an explanation)

**Comment by meleu** [comment]
I agree with @fr500 . I have a Vita and looks like this issue is just about a confused user. I believe it can be closed.
@twinaphex
