### ISSUE TITLE
Menu remembering shader browser position

### ISSUE THREAD

**Issue by Thrakk** [libretro/RetroArch#5746]
[Describe The Bug]
Every time I switch from a game to the menu, the menu remembers where I left off... except if I left off while applying shaders in the 'Load Shader Preset' file browser. 

[Expected Behavior]
Remember shader menu folder position (maybe also an on/off option). Would make loading/testing shaders a lot quicker. The shader folder is pretty huge and I switch shaders quickly. Switching games, using the load content file browser, is not something that requires quickness.

[Actual Behavior]
Retroarch is not remembering Load Shader Preset file browser folder position when switching from game to menu.

[Steps to reproduce the bug]
N/A

[Bisect Results]
N/A

[Version/Commit]
RetroArch: 1.6.7 
Build Date:  Aug 21, 2017
Git Version: a235c0b

[Environment information]
- OS: Win 10 10.0
- Compiler: MinGw (6.3.0) 64-bit

**Comment by sonninnos** [comment]
This already exists.
