### ISSUE TITLE
Toolchain with locale support required

### ISSUE THREAD

**Issue by deltabeard** [libretro/RetroArch#5753]
## Description

Functions that require locale support were added in commit 1b1d5c468d7325468a3db3a692046a546416e483. When using a toolchain that does not support locale functions like mbstowcs(), Retroarch will fail to compile because of the file ./libretro-common/encodings/encoding_utf.c which contains these functions.

### Expected behavior

Support for locale should be disabled or enabled on configuration either using parameters like `--disable-locale` or it could be automatically enabled if locale support is detected. This should allow Retroarch to continue compiling whether locale support is available or not.

Locale support should not be assumed.

### Actual behavior

Retroarch will not compile when using a toolchain with no locale support. My toolchain uses uclibc-ng with `UCLIBC_HAS_LOCALE` turned off.

### Steps to reproduce the bug

1. Create a toolchain with crosstool-ng that uses uclibc-ng with locale support excluded.
2. Compile Retroarch using the toolchain (I'm using buildroot to do this).

### Bisect Results

Issue started with commit 1b1d5c468d7325468a3db3a692046a546416e483. The following patch reverts the file ./libretro-common/encodings/encoding_utf.c to commit ac3b7bc4cc2384567fa3de127f6bffc018aad356 in order for Retroarch to compile with a toolchain with no locale support.

[revert_locale.zip](https://github.com/libretro/RetroArch/files/1498644/revert_locale.zip)

### Version/Commit

- RetroArch: 1.6.9

### Environment information

- OS: Archlinux
- Compiler: GCC, using Buildroot and Crosstool-ng.

**Comment by twinaphex** [comment]
Hi there @bparker06, you might want to look into this.

**Comment by deltabeard** [comment]
Old systems like DOS and NT 3.51 have support for mbstowcs. If anyone wants to make a well written pull request that makes it a configurable option, feel free.

I've decided to enable support for it in my uclibc-ng toolchain considering ancient systems had support for it.
