### ISSUE TITLE
(OSD) Add glyphs to on-screen messages

### ISSUE THREAD

**Issue by alfrix** [libretro/RetroArch#5755]
Beware that your browser may be using emoji, to display this characters copy the table to a text editor or spreadsheet and select an apropiate font.

Code | Glyph | Description | Code | Glyph | Code | Glyph
-- | -- | -- | -- | -- | -- | --
23E9 | ``⏩`` | Fast Forward |   |   |   |  
23EA | ``⏪`` | Rewind |   |   |   |  
23EE | ``⏮`` | End of rewind buffer |   |   |   |  
23EF | ``⏯`` | Slow Motion | 29D0 | ``⧐`` |   |  
23F4 | ``⏴`` | Slow Motion Rewind | 29CF | ``⧏`` |   |  
23F5 | ``⏵`` | Resume |   |   |   |  
23F8 | ``⏸`` | Pause |   |   |   |  
23F9 | ``⏹`` | Stop | 25A0 | ``■`` |   |  
23FA | ``⏺`` | Record | 25CF | ``●`` |   |  
2715 | ``✕`` | Failed | 2716 | ``✖`` |   |  
23CF | ``⏏`` | Eject |   |   |   |  
21BB | ``↻`` | Reset | 2B6E | ``⭮`` |   |  
2B73 | ``⭳`` | Downloading | 23EC | ``⏬`` |   |  
2713 | ``✓`` | Ok | 2714 | ``✔`` |   |  
1F3AE | ``🎮`` | Controller connected |   |   |   |  
1F3C6 | ``🏆`` | Achievement |   |   |   |  

Not currently supported in the patched font:

Code | Glyph | Description | Code | Glyph | Code | Glyph
-- | -- | -- | -- | -- | -- | --
1F5A7 | ``🖧`` | Netplay |   |   |   |  
1F5AB | ``🖫`` | Saved | 1F4BE | ``💾`` | 1F5AC | ``🖬``
1F3A5 | ``🎥`` | Starting movie playback |   |   |   |  

If #5710 and [#177](https://github.com/libretro/retroarch-assets/pull/177) get implemented

**Comment by RobLoach** [comment]
If you add a column and stick the character wrapped with `s, it'll show appropriately. Example: `🏆`

**Comment by alfrix** [comment]
Closing in favor of menu-widgets
