### ISSUE TITLE
Separate controller arch types

### ISSUE THREAD

**Issue by kenshen112** [libretro/RetroArch#5758]
I'm posting this to get a bounty going. Basically I'm requesting in RetroArch the ability to configure multiple controller archtypes to let RetroArch /games know what general shape my controller is how many buttons it has and particular features like motion control that it might include. From my Reddit comment on this

 "I think part of the reasoning is whilst the cores can be "remapped" there's still a weirdness that especially appears in the retroarch menu where the controls at least to me anyways the control's will somehow reverse themselves with O / B ending up as the okay button. I personally wish we didn't have to remap the cores for each controller each time as that feels awful and repetitive. to be frank though I just wish the controller support would be more like the steam re mapper than what we have now. also this would help with wiimote support for dolphin's core."

**Comment by fr500** [comment]
This would mean rewriting the whole thing....

Sorry but I don't see the problem.
With correct core descriptors and controller descriptors the middleman (retropad buttons) never even appears.

If the core has a sane default map it should "just work"
