### ISSUE TITLE
RetroArch not starting with Vulkan video driver

### ISSUE THREAD

**Issue by Shoegzer** [libretro/RetroArch#5776]
## Description

When I switch the video driver from gl to vulkan and exit, retroarch will fail to start again.  If I run retroarch with --verbose, the following is thrown to console:

[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ 960x720
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] Vulkan dynamic library loaded.
[INFO] [Vulkan]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
WARNING: Haswell Vulkan support is incomplete
wsi_mir_init_wsi()
[INFO] [Vulkan]: Using GPU: Intel(R) Haswell Mobile
[ERROR] [Vulkan]: Did not find suitable graphics queue.
wsi_mir_finish_wsi()
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 2.
[INFO] [XINERAMA]: Saved monitor #0.
[ERROR] [Vulkan]: Failed to set video mode.
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
[ERROR] This core requires a content file.

Note than I am using X, not Mir or Wayland.  
This behavior is observed even with a new configuration file.

### Version/Commit

- RetroArch: 1.6.9/c056726

### Environment information

- OS: Linux Mint 18.2 x64, kernel 4.11
- Compiler: Built locally using GCC 6.3.0 x64
- HW: Intel Haswell 4710MQ / Nvidia 860M and 384.90 drivers

**Comment by retro-wertz** [comment]
can you try to put up a link to full log?

**Comment by Shoegzer** [comment]
Above is nearly the entire contents of the --verbose log, what else were you looking for?

**Comment by retro-wertz** [comment]
well im looking for something not in the log...

**Comment by Shoegzer** [comment]
Sorry for my confusion but what do you mean "not in the log".  Do you need me to post some other log?  If so, just let me know and I'm happy to provide.

**Comment by orbea** [comment]
Does vulkan work with other programs? Dolphin, ppsspp upstream, various vulkan demos?

**Comment by Shoegzer** [comment]
Ah, good question.  Yes it works just fine with Dolphin etc.

**Comment by orbea** [comment]
Next question, do past versions or commits work? I would test all the way back to the initial vulkan commit, but I don't have vulkan here so I can't test anything myself.

**Comment by Shoegzer** [comment]
As far as I know it's never worked.  I know that at least six months ago I tried it then, and I got the same result.  I just hadn't run a --verbose until now.

**Comment by retro-wertz** [comment]
this might not be a similar case since I am using an intel gpu, but using
Linux Mint, i had to set DRI to "3" in xorg.conf.d/20-intel.conf for vulkan
to work.  might go check this setting for your gpu(which i believe is using
the Intel gpu instead of nvidia one).

another one to try is disabling one of the gpu in bios and see if this
works.

**Comment by orbea** [comment]
I talked to Shoezer in irc and it seems the problem is that RetroArch is insisting on using intel instead of the nvidia blob driver. His xorg logs and glxinfo indicate it should nvidia should be used, but RA seems to not know that for some reason.

**Comment by Shoegzer** [comment]
Thanks for your help.  The closest I have to what you're saying is 50-nvidia-drm-outputclass.conf but there's no such setting as "DRI" in there.  As orbea said, all indications are that my nvidia card is being used.  Finally, sadly there's no option in my bios to disable the Intel GPU, as great an idea as that is!

**Comment by orbea** [comment]
How about if blacklist i965 so it can't be used at all?

I don't know how to configure DRI3 for the nvidia blob, but with intel and nouveau something like this will work. With intel modesetting is probably preferred over xf86-video-intel, but with nouveau it depends on who you ask so I suggest using w/e you find works better.
`/etc/X11/xorg.conf.d/nouveau-dri3.conf`
```
Section "Device"
   Identifier  "Your_card_identifier"
   Driver      "modesetting"
   Option      "DRI" "3"
EndSection
```
To confirm it works this command will tell you.
```
$ LIBGL_DEBUG=verbose glxinfo | grep -i dri
```
For example.
```
libGL: pci id for fd 4: 10de:100a, driver nouveau
libGL: OpenDriver: trying /usr/lib64/xorg/modules/dri/tls/nouveau_dri.so
libGL: OpenDriver: trying /usr/lib64/xorg/modules/dri/nouveau_dri.so
libGL: Using DRI3 for screen 0
```
Your xorg logs could potentially disagree, but it apparently does not matter if `LIBGL_DEBUG=verbose` says you are using DRI3.

Ofc if you want vulkan, you will need the nvidia blob and maybe it might work with intel. Try talking to #intel-gfx and / or #dri-devel @ freenode about your intel issues.

**Comment by Shoegzer** [comment]
Thanks.  I tried blacklisting by adding "blacklist i915" through /etc/modprobe.d/blacklist.conf, rebooted, but i still get the same i915 settings as shown through lsmod.

I'm not sure how to configure DRI3 on this system either, I don't have that file/directory in Mint.  My best guess is to edit /usr/share/X11/xorg.conf.d/50-nvidia-drm-outputclass.conf/nvidia-drm-outputclass.conf and put the Option "DRI" "3" line as you have it above, though I"m not certain that wouldn't mess up the system.

Also: when I run "LIBGL_DEBUG=verbose glxinfo | grep -i dri" I get nothing returned.

**Comment by twinaphex** [comment]
@Shoegzer Is this issue fixed for you now?

**Comment by Shoegzer** [comment]
It's fixed so I'll close this issue. Thanks for the reminder.
