### ISSUE TITLE
(Cheevos)Warnings with Cheevos when compiling with CXX_BUILD

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#5795]
@leiradel for reference ,here is what happens when I compile RetroArch with CXX_BUILD=1 defined -

https://hastebin.com/apefiwogoq.pas

The aim should be to get rid of all the warnings.

**Comment by leiradel** [comment]
The warnings about gotos and stuff should be disregarded, it's just the compiler thinking we don't know how to write code.
