### ISSUE TITLE
[Localisation] New strings added (mouse/lightgun)

### ISSUE THREAD

**Issue by hiddenasbestos** [libretro/RetroArch#5804]
I added the following new strings, but they are in English and require localisation to other languages.

5 mouse buttons:
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_LEFT        (Mouse 1)
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_RIGHT        (Mouse 2)
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_MIDDLE       (3)
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_BUTTON4       (4)
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_BUTTON5        (5)

4 mouse wheel directions:
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_WHEEL_UP
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_WHEEL_DOWN
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_HORIZ_WHEEL_UP (left?)
MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_HORIZ_WHEEL_DOWN (right?)

11 lightgun buttons:
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_TRIGGER (Gun Trigger)
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_RELOAD (Gun Reload)
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_A
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_B
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_AUX_C
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_START
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_SELECT
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_UP
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_DOWN
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_LEFT
MENU_ENUM_LABEL_VALUE_INPUT_LIGHTGUN_DPAD_RIGH

**Comment by gouchi** [comment]
Please go to the [internationalization directory](https://github.com/libretro/RetroArch/tree/master/intl) then edit the header file (*.h) from your language.

Translate the text for the new strings aforementioned.

For example the text to translate for `MENU_ENUM_LABEL_VALUE_INPUT_MOUSE_WHEEL_UP` is "Wheel up".
