### ISSUE TITLE
Wii and WiiU not building due to extra unneeded bracket

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#5814]
`return (RARCH_INPUT_STATE_BIT_GET(buttons, joykey)) != 0);`
[Compile Log](https://travis-ci.org/libretro/fuse-libretro/jobs/308720366)

**Comment by hiddenasbestos** [comment]
Thanks - I've fixed that in #5817

**Comment by meepingsnesroms** [comment]
So there's 3 pull requests one merged, one canceled and one closed.
Is this issue fixed?

**Comment by hiddenasbestos** [comment]
Yeah I think so.

**Comment by meepingsnesroms** [comment]
Ok
