### ISSUE TITLE
 Custom input controls

### ISSUE THREAD

**Issue by sept-en** [libretro/RetroArch#5818]
Hello, guys!

I'm just trying to create a new control for RetroArch. E.g. directional pad that will appear everytime at the place where user touches the screen and then disappear. I want to add also some possibilities to change overlay of it in config files like it's done now for all other input controls.

I've been researching source code for some time but still can't get what's the best way to do it.
I'm trying to make it work for Android.

I would be very grateful if you can give me some tips how to implement it.

Thanks in advance.

Best regards,
Kirill.

**Comment by RobLoach** [comment]
https://docs.libretro.com/guides/controller-autoconfiguration/
