### ISSUE TITLE
Slow motion doesn't work anymore it looks like

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#5820]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When you press the slow motion key, it just shows the text but does nothing else.

### Expected behavior

It should actually slow the motion! :>)

### Actual behavior

Just the slow motion text...

### Steps to reproduce the bug

1. Press the slow-motion key
2. :(

### Bisect Results

This started happening in a pretty recent nightly build.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Nov 28 2017

### Environment information

- OS: Windows 10 64-bit
- Compiler: Build-bot, MinGW 64-bit

**Comment by orbea** [comment]
Can you bisect this?

**Comment by hiddenasbestos** [comment]
I can confirm this is the case for me in the latest build.

/me pre-emptively apologising for this being my fault probably...

**Comment by retro-wertz** [comment]
on a similar note, the fast forward hotkey is not working anymore either,
might be related.. anyone confirm?

**Comment by hizzlekizzle** [comment]
I could not reproduce this in linux 64-bit (self-compiled). Rewind, slow-motion and fast-forward all worked as expected.

**Comment by fr500** [comment]
It's not slowing down the game either on windows.

**Comment by milesrotaru** [comment]
I could have done it myself and forgotten about it but I noticed the slow motion ratio was set to 1 when I tried the latest build today. That could explain why the text appears but nothing happens.

**Comment by hyarsan** [comment]
It turns out Maximum Run Speed is set to 0.0x by default huh.

**Comment by retro-wertz** [comment]
ok looks like someone messed up the default config then. when starting
retroarch without an existing retroarch.cfg, it creates one and sets
Slow-Motion ratio to 1.0x.... interestingly if you press spacebar the
default should have been 3.0x

**Comment by hyarsan** [comment]
Somehow it just fixed itself and now every time I reset the config it works normal? 0_0

**Comment by hiddenasbestos** [comment]
That sounds a bit like an uninitialised variable to me.

**Comment by hyarsan** [comment]
So, Slow-Motion Ratio changes to 1.0x every time you open RetroArch. So that's the issue. I guess I caused confusion?
