### ISSUE TITLE
Can't toggle menu with overlay button

### ISSUE THREAD

**Issue by milesrotaru** [libretro/RetroArch#5837]
Using RetroArch 1.6.9 GIT 2017-11-30 on Android 7.1. Overlay buttons that should toggle the RetroArch menu don't do anything. Other overlay buttons work. Tested on multiple overlays that formerly worked, such as gba-grey and default retropad.

**Comment by hiddenasbestos** [comment]
This may now be fixed - try a build with  #5925 merged into it - on or about the 18th Dec 2017

**Comment by milesrotaru** [comment]
Just tested 2017-12-18 nightly and menu toggle is now working as expected. Closing issue.
