### ISSUE TITLE
Compilation errors when building for Windows through MSYS2/mingw64

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#5848]
## Description

When compiling Retroarch for Windows x64 through MSYS2/mingw64 (as per the guidelines in the official documentation), the process is abruptly stopped by a long string of errors that appear to come from tasks/autodetect.c.

A sample of the errors:

`In file included from tasks/task_autodetect.c:41:0:`
`P:/MSYS2/mingw64/x86_64-w64-mingw32/include/ks.h:38:1: error: unknown type name 'CDECL'`
` DEFINE_GUIDSTRUCT("00000000-0000-0000-0000-000000000000",GUID_NULL);`
 `^`
`P:/MSYS2/mingw64/x86_64-w64-mingw32/include/ks.h:38:1: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'GUID_NULL'` 
(it goes on for many lines after)

### Environment information

- OS: Windows 10 x64
- Compiler: Mingw64

**Comment by hiddenasbestos** [comment]
This is what is currently breaking #5847

**Comment by Ryunam** [comment]
A quick bisect shows that @bparker06's commit b9394846dc506ebe1785e2ee4b70fc5bb96faf5c is where the compilation errors started appearing for tasks/task_autodetect.c.

**Comment by bparker06** [comment]
I'm not able to reproduce this either on my own system or our buildbot. Maybe some package is missing or need to update msys2?

**Comment by hiddenasbestos** [comment]
This doesn't happen on my local msys2, but on the buildbot report for this pr you see it - https://github.com/libretro/RetroArch/pull/5847

**Comment by bparker06** [comment]
Yea that uses Travis-CI which cross-compiles from Linux. If I try doing the same thing then I'm able to reproduce it, just not under a real msys2 environment. Working on it now.

**Comment by Ryunam** [comment]
I have actually tried updating my MSYS2 environment already, but even after going through this procedure the errors still pop up when trying to compile RA.

**Comment by bparker06** [comment]
Should be fixed in 4efc845.

**Comment by Ryunam** [comment]
This is working now on my end. Thanks a lot of quickly addressing the issue!
