### ISSUE TITLE
Illegal Operation Error on Windows 98

### ISSUE THREAD

**Issue by nutcase84** [libretro/RetroArch#5849]
## Description

RetroArch gives an error when run on Windows 98.

### Expected behavior

RetroArch should launch.

### Actual behavior

An illegal operation error is given.

### Steps to reproduce the bug

1. Launch RetroArch on 98
2. ???
3. Profit

I've tried creating a retroarch.cfg file to change the video driver to gdi/rgui, but that results in the same error.

### Screenshot

![retroarcherror](https://user-images.githubusercontent.com/3430575/33518851-2ff32532-d76a-11e7-8315-c0caaa779bd7.png)

### Version/Commit

- RetroArch: December 2nd Nightly
Also happens on the nightly from the 29th.

### Environment information

- OS: Windows 98SE
- CPU: Pentium 4 2.8GHz
- GPU: ATI Radeon 9000 LE
- RAM: 512MB

**Comment by twinaphex** [comment]
Assinging bparker06 to this.

Also, which MSVC solution file are you using for your own compiled build of RetroArch for Win98?

**Comment by nutcase84** [comment]
I'm sorry I'm not sure I understand. I didn't compile anything. I used the prebuilt images.

**Comment by bparker06** [comment]
Hi @nutcase84,

Can you verify that DirectSound is working properly on your system? When I run a debug version of RetroArch on my 98 machine, it specifically tells me the crash happens in DirectSound (dsound.dll). On this system, DirectSound happens to not work correctly. Even trying to run dxdiag crashes for me and I'm not sure why.

**Comment by bparker06** [comment]
I've found another issue that appeared after working around the DirectSound crash, I hope to have a fix for that soon.

**Comment by bparker06** [comment]
Fixed in 49d02998086d0e154f22385d627710835ebb536c, it is working for me now on 98.

**Comment by nutcase84** [comment]
@bparker06 It's working for me as well, thanks.
