### ISSUE TITLE
Retroarch isn't loading the file passed to it

### ISSUE THREAD

**Issue by adawalli** [libretro/RetroArch#5869]
## Description

Retroarch is passed a valid filename (a file that exists). However, it is removing a space from the filename and trying to load a file that does in fact not exist.

the file is called as follows

Note the TWO spaces after "Wars"
![image](https://user-images.githubusercontent.com/14079121/33636290-849d57f2-d9e9-11e7-9048-c920773092c5.png)
(sorry for pictures instead of text, but markdown keeps messing with the spacing)

Please see a log included at the end to see the way it was called vs how it was interpreted. You can see that ONE space has been stripped by retroarch so that when it tries to find the file, no file exists by that name

### Expected behavior

To call the file as requested

### Actual behavior

Retroarch is munging the filename.

### Steps to reproduce the bug

call retroarch as follows and it removes a space

`/opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-mgba/mgba_libretro.so --config /opt/retropie/configs/gba/retroarch.cfg "/home/pi/RetroPie/roms/gba/Advanced Wars  # GBA.GBA"`

### Version/Commit
You can find this information under Information/System Information

[INFO] RetroArch 1.6.9 (Git e8b10d3)

### Environment information
Linux retropie 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

[gba_log.txt](https://github.com/libretro/RetroArch/files/1533315/gba_log.txt)

**Comment by bparker06** [comment]
File paths cannot have `#` characters in them because we use these internally to denote that 1. the file is a compressed archive, and 2. the string after it is the name of the file inside the archive to extract.

**Comment by adawalli** [comment]
ok, thanks. Tons of my files have #'s in them and work fine - but I will rename. I appreciate the courteous and helpful response.
