### ISSUE TITLE
External Raspberry Pi Bluetooth dongle resulting in controller order being reversed 

### ISSUE THREAD

**Issue by sonicsheppard** [libretro/RetroArch#5875]
## Description

Please note that this issue was originally reported on "https://github.com/pyhammond/retropie_wiimote_lights", a script for lighting WiiU Pro Controller LEDs with the Raspberry Pi RetroPie system. The issue only occurred on RetroArch cores so it was recommended I open the issue with RetroArch. Do please close this if this is not the correct repository to open this issue.

When using the script https://github.com/pyhammond/retropie_wiimote_lights in conjunction with a RetroPie setup with RetroArch on a Raspberry Pi, I have noticed that the order WiiU Pro controllers connect is reversed when using an External Bluetooth dongle.

For example, if I connect 4 WiiU Pro Controllers to the Raspberry Pi (LEDs light up according to connection order), and then I launch a RetroArch core (e.g. lr-Snes9x2010), the controller with 1 LED is actually Player 4, the controller with 2 LEDs is Player 3 etc etc.

This only occurs when using an External Bluetooth dongle and RetroArch cores.

It does not occur on either Non-RetroArch cores, or when using the Internal Raspberry Pi Bluetooth connection.  

### Expected behavior

The order the controllers connects to the Raspberry Pi device is accurately reflected in RetroArch cores when using an External Bluetooth dongle. For example, controller which connects first and has 1 LED is Player 1 when launching a RetroArch core.

### Actual behavior

The order the controllers connect to a Raspberry Pi using an External Bluetooth dongle is reversed when using a RetroArch core. 

### Steps to reproduce the bug

1. Boot the latest version of the RetroPie image with a Raspberry Pi device - including RetroArch cores (1.6.9).
2. Disable the onboard Bluetooth and use an External Bluetooth USB dongle to connect 4 WiiU Pro Bluetooth controllers.
3. Install the script https://github.com/pyhammond/retropie_wiimote_lights which will light up the WiiU Pro LEDs according to the order they are connected.
4. Launch a RetroArch core and observe the behaviour of the controllers. Controller with 4 LEDs will be Player 1 (with access to RetroArch menus), Controller with 3 LEDs will be Player 2 etc.

### Environment information

- OS: RetroPie - Linux using Raspberry Pi.

**Comment by pyhammond** [comment]
This was just fixed by commit [b14598657c4b813c555b6cc6c6e81ec0830621c4](https://github.com/libretro/RetroArch/commit/b14598657c4b813c555b6cc6c6e81ec0830621c4#diff-e24ecc035fba173802aca096d7675071).
[See my comments here for more detail](https://github.com/pyhammond/retropie_wiimote_lights/issues/1).
Have a great holiday !!
