### ISSUE TITLE
[Regression 3DS] Big neogeo rom files don't load anymore (> 60Mb)

### ISSUE THREAD

**Issue by fraf** [libretro/RetroArch#5883]
Was working in 1.6.7.
1.6.9 could not load those big roms (kof99 until kof2003, svc, garou, ms3, etc.)

**Comment by fraf** [comment]
The problem occurs with both : final burn alpha and final burn alpha neogeo.
I talk about cia 3ds version.

**Comment by blackman91** [comment]
It is probably a romset issue, just find the correct romset for the fba version you are using.

**Comment by fraf** [comment]
Wrong.
Thé romset works with 1.6.7
From 1.6.8 and more the game don't load anymore.
You Can try.

**Comment by blackman91** [comment]
Check the fba core version, you need the correct romset for that version.

**Comment by fraf** [comment]
I tested with all possible version of the roms/romset (kof2k3 for example).
Always crash when loading.

About template, nothing particular. I tested under luma3DS under boostrap9 latest version.

**Comment by fr500** [comment]
Core issue

**Comment by fraf** [comment]
Hello,

Bug reappeared since retroarch 1.8.5 to 1.7.8 (all versions) and probably even before.
"Big roms" doesn't load anymore (ex.KOF2000).
Maybe since 1.6.7 there is another way to play neogeo roms on 3ds or it is a very big issue ?

Regards.
