### ISSUE TITLE
Fatal error received in (IPS).

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5884]
All of the softpatches i have report this _even if the patch applies and runs_. This is for softpatching where the 'same name, different extension' method is applied to load them automatically, not the '--ips' switch

Basically makes it impossible to tell if the patch is applied or not without going to its changelog and checking that a modification happens ingame.

**Comment by fr500** [comment]
Confirmed.

Fill the issue next time please.

**Comment by orbea** [comment]
I suppose this is fixed then so I'll close it.
