### ISSUE TITLE
--no-patch switch doesn't work

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5885]
This switch is broken. If you try to load a rom from the console with the same name as a ips file and also specify '--no-patch' right after, the ips file is applied (even if it says "[INFO] Fatal error received in (IPS). ", that's another bug).

**Comment by orbea** [comment]
@i308717 Can you please fill out the issue template? Also can you please git bisect this?

**Comment by orbea** [comment]
@i30817 Can you please fill out the issue template? Also can you please git bisect this?

**Comment by i30817** [comment]
1) i could, but i found it ridiculous to do so to such a easily confirmed bug

2) it's not my responsibility to bisect things, especially when i don't compile the code. This bug is so obvious and so obviously tested that saving you some debugging work to see what's wrong to get it to fix it, is almost demeaning.

**Comment by hizzlekizzle** [comment]
It's a simple question. *Someone* has to bisect it, so orbea asked if that could be you.

You could answer "no, I don't know how," or "no, I don't have a build environment set up," and those would be perfectly acceptable answers. Instead, you've gone with [paraphrasing] "no, you should do it instead."

Ok then. Thanks for the report.

**Comment by fr500** [comment]
The issue template is vital.
Otherwise we have to do tons of followup questions all the time.

We should enforce it and make no exceptions.

**Comment by orbea** [comment]
I can confirm this issue, it broke between `v1.3.6` and `v1.4.1`.

Here is the first bad commit.
```
d28c138d09922f5458c8ee86a049aa3a961d0262 is the first bad commit
commit d28c138d09922f5458c8ee86a049aa3a961d0262
Author: twinaphex <libretro@gmail.com>
Date:   Mon Jan 23 21:03:12 2017 +0100

    (task_content.c) Cleanups

:040000 040000 7d366d2f5ae041cba62590c1c23c0b4df1bf7925 6c25e80d6d8178dd76c3b5d3876cf35ab7fce31a M	tasks
```
d28c138d09922f5458c8ee86a049aa3a961d0262

**Comment by orbea** [comment]
Reverting this specific change allows it to work again.
```
diff --git a/tasks/task_content.c b/tasks/task_content.c
index af23201538..ac30ba2449 100644
--- a/tasks/task_content.c
+++ b/tasks/task_content.c
@@ -350,7 +350,7 @@ static bool load_content_into_memory(
           * CRC checking, etc. */
 
          /* Attempt to apply a patch. */
-         if (!content_ctx->patch_is_blocked)
+         if (!rarch_ctl(RARCH_CTL_IS_PATCH_BLOCKED, NULL))
             patch_content(
                   content_ctx->is_ips_pref,
                   content_ctx->is_bps_pref,
```

**Comment by orbea** [comment]
@i30817 I had a chance to look at this and I think I found a solution, if possible can you please test it when you have time?

**Comment by i30817** [comment]
Yes it works. Tested by fetching and merging the pr and testing with both ips and bps patches on a core which softpatches (snes9x).

**Comment by orbea** [comment]
I'm going to reopen this until the PR is actually merged. :)
