### ISSUE TITLE
This weird nightmare fuel sometimes happens when I start Citra

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#5886]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

First of all, I am not sure where to post this issue. But this seems more of an RetroArch problem.
It only shows white text, no graphics.

https://1drv.ms/i/s!AvB-c2zUfIalpjKSgOrM0k-m6J7u

It also crashes when I try to exit or full screen. But if you fullscreen it beforehand, it does work.

### Expected behavior

Not this weird nightmare fuel. Just a normal XMB menu with no missing textures or anything.

### Actual behavior

Weird dark shiz. It also shows "This core requires a content file." but the game loaded perfectly fine?

### Steps to reproduce the bug

1. Launch Citra
2. Good luck on somehow reproducing this.
3. Ask me for the RetroArch folder if you really want, I would not be suprised if you wanted it.
EDIT: After looking at the log, it turns out it has something to do with sound. When I connected my bluetooth headphones, it worked again. But when turned off, it returns.

### Bisect Results

Log: https://pastebin.com/ugeHLUxD

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Dec 4 2017
but I remember this happening a while back.

### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW 64-bit from the buildbot

**Comment by fr500** [comment]
Core issue

**Comment by Alcaro** [comment]
Looks like multiple issues at once, of which one is 'you forgot installing the assets'.

Being affected by headphones is definitely not a core issue, but there could be a core issue running around too.

**Comment by hyarsan** [comment]
This isn't a core issue, I later found out it happens on all cores as well. The assets are perfectly installed too! Please un-close this, thanks.

**Comment by orbea** [comment]
@hyarsan Is this still an issue?
