### ISSUE TITLE
File Directory Issues on Windows 98

### ISSUE THREAD

**Issue by nutcase84** [libretro/RetroArch#5887]
## Description

Directories are not working correctly at all on Windows 98. Does not seem to be GUI related, as both rgui and xmb have this issue. 

When selecting C:\ in Load Content, it says directory not found. Selecting parent directory shows the RetroArch install folder where the .exe is located. Tried putting some roms in the "downloads" folder where RetroArch is located, and it does show up in the GUI. However it crashes RetroArch when selected with the message "Failed to open C:\WINDOWS\APPLICATION DATA\RETROARCH\saves\*ROM*.srm: No such file or directory"

## Screenshots

![image](https://user-images.githubusercontent.com/3430575/33783624-8c034594-dc2b-11e7-8297-8d368f69942e.png)

![image](https://user-images.githubusercontent.com/3430575/33783570-54ad9644-dc2b-11e7-83c6-9340306b01d3.png)

![image](https://user-images.githubusercontent.com/3430575/33783411-a89008d8-dc2a-11e7-8ed0-4c02ada4c77f.png)

### Version/Commit

- RetroArch: December 8th Nightly

### Environment information

- OS: Windows 98SE
- CPU: Pentium 4 2.4GHz
- GPU: Radeon 9000 LE

**Comment by bparker06** [comment]
The issue seems to be that 95/98 doesn't like having extra slashes in file paths. It tries to get the contents of `C:\\*` instead of `C:\*` and that's why it fails. Tried on Win2000 and no issues there, probably an NT feature. Fix will be in soon.
