### ISSUE TITLE
Opening menu causes crash on windows

### ISSUE THREAD

**Issue by MADJIHADx** [libretro/RetroArch#5888]
## Description
Opening menu causes RA to crash with Genesis Plus GX on windows.
Doesn't happen on linux or other cores.
Happens on default configuration.

### Steps to reproduce the bug
1. Run a game using Genesis Plus GX core
2. Press F1

### Version/Commit
- RetroArch: [1.6.7/a235c0b]

### Environment information
- OS: Win7 64

**Comment by ofry** [comment]
Try to update: retroarch and Genesis Plus GX core to latest nightly version.

**Comment by MADJIHADx** [comment]
Can confirm crash does not happen on nightly version.
