### ISSUE TITLE
[Win10 - GL] Delayed reaction time when pressing keyboard hotkey

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#5891]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Running on Windows using opengl drivers, retroarch reaction time when switching from window to fullscreen or vice versa, loading rom or closing a core there is a delayed reaction of about 5 secs. Switching to rgui still behaves the same.

Switching to d3d and rgui reaction time is fast if not instantaneous. Linux is fast too.

### Expected behavior

Reaction should be fast.

### Actual behavior

Delays about 4-5 secs consistently.

### Steps to reproduce the bug

1. Load retroarch without launching any core.
2. switch to fullscreen and or back to window mode using "f" hotkey.
3. there should be slight delays between reaction. compare this to using d3d.

### Bisect Results

Freshly installed Windows 10 with bare necessities. no antivirus or such other than what comes with windows.
Retroarch freshly compiled (commit 620dad1) with assets, autoconfig, database etc updated.
Intel Ivy Bridge using builtin intel hd graphics(yeah its old but should be enough to run most cores that i cared about).

1st bad commit - https://github.com/libretro/RetroArch/commit/3ccce249ea3e4fd7f67881d3893818009b0c02e5
This commit is the 1st commit that add delays when pressing "f" hotkey to switch from window to fullscreen and vice versa. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.6.9/620dad1]

### Environment information

- OS: Windows 10
- Compiler: gcc 6.3.0

Thanks.

**Comment by Ryunam** [comment]
@retro-wertz, are you testing this on the nightly builds from the buildbot? 
Based on your bisect I think the problem comes from MSVC compilation, since it is not happening on the latest code I have compiled through MinGW.

**Comment by retro-wertz** [comment]
what gcc version u use.

**Comment by retro-wertz** [comment]
UPDATE:

this doesn't to happen now since i upgraded msys2's runtime and using gcc 7.2. probably this only happens with gcc 6.3x

**Comment by fr500** [comment]
Hmm, I'm still on 6.3.0 (since the buildbot uses that)
And I don't seem to be able to reproduce..

**Comment by retro-wertz** [comment]
there were no system changes from the last test other than updating msys2/gcc since i normally dont use windows. sadly there seems to be no way do downgrade back to 6.3.0 so i can do a re-retest.

**Comment by fr500** [comment]
You can test a buildbot build :)

Those use an older GCC
