### ISSUE TITLE
Move fill_pathname_expand_special to libretro-common

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#5897]
[`fill_pathname_expand_special()`](https://github.com/libretro/RetroArch/blob/3fa035ba2a64a9567edcd4a6280aad4f374666d9/file_path_special.c#L59) and [`fill_pathname_abbreviate_special()`](https://github.com/libretro/RetroArch/blob/3fa035ba2a64a9567edcd4a6280aad4f374666d9/file_path_special.c#L109) are defined in RetroArch, but used in libretro-common. We should clean up the dependency tree by moving `fill_pathname_expand_special()` and `fill_pathname_abbreviate_special()` to libretro-common.

This will allow applications to use the functions from outside RetroArch.

**Comment by fr500** [comment]
I guess it's up to @twinaphex 
Also I think that code is GPL and libretro-common uses more permissive licenses.

**Comment by orbea** [comment]
Fixed in commit https://github.com/libretro/RetroArch/pull/6093/commits/26b9cb3c7826f7f9806181044edd3b984f7ddda9, but it seems this was never closed so I'll do that now.

**Comment by bparker06** [comment]
We've come full circle now: https://github.com/libretro/RetroArch/commit/18ce5f73bee0290ec7dd8eac7d4c931fa3893465

**Comment by orbea** [comment]
I suppose this became a problem after that commit?
```
$ grep -r fill_pathname_expand_special libretro-common/
libretro-common/file/config_file.c:      fill_pathname_expand_special(buf, entry->value, size);
libretro-common/file/file_path.c:void fill_pathname_expand_special(char *out_path,
libretro-common/include/file/file_path.h:void fill_pathname_expand_special(char *out_path,

$ grep -r fill_pathname_abbreviate_special libretro-common/
libretro-common/dynamic/dylib.c:   fill_pathname_abbreviate_special(relative_path_abbrev, path, PATH_MAX_LENGTH * sizeof(char));
libretro-common/file/config_file.c:   fill_pathname_abbreviate_special(buf, val, sizeof(buf));
libretro-common/file/file_path.c:void fill_pathname_abbreviate_special(char *out_path,
libretro-common/include/file/file_path.h:void fill_pathname_abbreviate_special(char *out_path,
```

**Comment by twinaphex** [comment]
Ugh, there really should NOT have been a dependency on file_path_special.c (a RetroArch file) inside libretro-common.

@krzys-h Can you fix this? This is a pretty serious issue right now.

**Comment by twinaphex** [comment]
Hmm, maybe I misread it, but what is the issue here? Looks like it's already a part of libretro-common anyway. So what is the issue here?

**Comment by orbea** [comment]
I don't think there are any problems currently, just it was part of libretro-common, it was moved out of libretro-common and then moved back. :)
