### ISSUE TITLE
entries not added to library

### ISSUE THREAD

**Issue by DoubleIntegral** [libretro/RetroArch#5900]
Linux Manjaro x64, RetroArch 1.6.9 (Git Version f3q58f4ff3 - current master)

Scanning a folder with iso amd rom files doesn't add them to game library (tested on snes, psx and psp cores/files). Entries still show up in history and play just fine through "Load Content" option.

**Comment by RobLoach** [comment]
What games? Give some CRC values.

**Comment by DoubleIntegral** [comment]
@RobLoach 

320847074 Super Mario World (U).smc
4033086002 Final Fantasy 7 [CD3].img

**Comment by bparker06** [comment]
@DoubleIntegral I checked the CRC you gave for SMW, (131fbce2 in hex) and it does not appear for either No-Intro or GoodSNES, so this is why it is not being scanned. Please use a rom that matches what's in our database if you want to be able to scan it.
