### ISSUE TITLE
[Feature Request] Add option for opacity to the RetroArch window

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#5901]
Just like the command prompt, I feel that there should be an option to change the opacity of the RetroArch window, at least for Windowed mode. I know for a fact that Windows has it, maybe Linux as well.

![opacity](https://user-images.githubusercontent.com/32988993/33844730-77e275f8-dea1-11e7-90ff-4613a6295ebf.png)

Mockup:
![gameboy neat](https://user-images.githubusercontent.com/32988993/33845911-3c4bd7b0-dea5-11e7-80e9-265db9f67e76.png)

Just imagining such a thing with Gameboy gives me chills! Well, of course I had to get rid of the title bar by changing the driver to sdl2 to make it look nicer but you get the point. I will make an issue for that later.

**Comment by bparker06** [comment]
Coming soon...

![img](https://i.imgur.com/t1dwmty.png)

**Comment by twinaphex** [comment]
Pretty cool!

**Comment by hyarsan** [comment]
WOW, that's so cool! It also looks better than I imagined! :D For what platforms is it going to be?
( are you talking about Gearboy being on the core updater now in the background lol )

**Comment by bparker06** [comment]
Gearboy is already on the updater for Windows and Linux.

First the transparency will be available for Windows (regardless of video driver) and then we can add other platforms later.

**Comment by hyarsan** [comment]
I know, it's pretty cool. How will full screen work with the opacity?

**Comment by hyarsan** [comment]
Nice!

**Comment by RobLoach** [comment]
Various Linux desktops have this. Used it in Compiz all the time. Not sure of the use case here, but cool.

**Comment by hyarsan** [comment]
Yeah, I thought I remember seeing an translucent bash.

**Comment by hyarsan** [comment]
I am not sure if this is the cause, but d3d displays a black screen? And sdl2 doesn't work with opacity.

**Comment by bparker06** [comment]
I couldn't tell you why sdl2 doesn't work with the opacity... but I know that almost nobody uses that driver, especially on Windows. And as for the fullscreen thing, we don't do anything different with the drivers, they are not even aware of the opacity, so it would likely just be a limitation of the underlying subsystem within Windows.
