### ISSUE TITLE
PS3 1.6.9 is missing MAME2003 core

### ISSUE THREAD

**Issue by ertay** [libretro/RetroArch#5910]
## Description

Both CEX and DEX versions of the latest stable 1.6.9 build are missing the MAME2003 core. I installed the 1.6.7 nightly from September, and the MAME2003 core is there.

### Expected behavior

MAME2003 should be included in the cores list.

### Actual behavior

Missing MAME2003 core.

### Steps to reproduce the bug

1. Install latest stable 1.6.9 CEX or DEX
2. Load core
3. Only MAME2000 is there, no MAME2003.
### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.9

### Environment information

- OS: PS3 CEX/DEX

**Comment by retro-wertz** [comment]
this should be posted under related core issues page:

https://github.com/libretro/mame2003-libretro/issues

**Comment by ertay** [comment]
Issue posted in the correct place:

https://github.com/libretro/mame2003-libretro/issues/240
