### ISSUE TITLE
Touch menu button not working on nightly.apk

### ISSUE THREAD

**Issue by LootusMaximus** [libretro/RetroArch#5911]
The menu button is not working on gamepad overlays on the android nightlys. Works fine on stable. Im using android 5.1. I cant think of any additional info needed. Its a straight forward issue. Touch menu button is not working on android nightly

**Comment by blackman91** [comment]
Yep can confim I have this too, the menu button is not working in all touch gamepad Overlays, tested using latest nightly on Android 7.

**Comment by fr500** [comment]
It's not just the overlay, the gamepad menu toggle doesn't work either

**Comment by hyarsan** [comment]
Yeah same for me, I thought that it was me only!

**Comment by blackman91** [comment]
Only menu toggle gamepad toggle is working, that's weird.

**Comment by milesrotaru** [comment]
Sounds like #5837.

**Comment by hiddenasbestos** [comment]
Please try this #5925

**Comment by blackman91** [comment]
Tested the latest nightly now menu button works, thanks a lot guys you rock.
