### ISSUE TITLE
Wii and DS games not being recognized by collections.

### ISSUE THREAD

**Issue by legoboy0109** [libretro/RetroArch#5912]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The option to search a folder for games to add as a collection for a console does not recognize wii or ds games. I think the wii issue might have something to do with the fact that dolphin emulates 2 consoles. 

### Expected behavior

They should show up in my collections

### Actual behavior

Nothing is showing up when I search my wii roms folder

### Steps to reproduce the bug

Go to collections, search a folder with wii games. They will not be recognized.

### Bisect Results
Ever since I installed retroarch on my computer I've had this problem.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: e8b10d342

### Environment information

- OS: Windows 10
- Compiler: MinGW 6.3.0 64 bit

**Comment by RobLoach** [comment]
Have some CRC values of one of your games?

**Comment by ofry** [comment]
DS??? Or, maybe, GameCube (GC)?

**Comment by orbea** [comment]
I can not reproduce this problem and given the lack of activity I am going to close this issue.

If your problems persist please confirm that they are part of the database files.

https://github.com/libretro/libretro-database/tree/master/dat

And then report or fix it if you can in the correct repo.

https://github.com/libretro/libretro-database/issues

Thanks!
