### ISSUE TITLE
Flatpak RetroArch unable to open cores

### ISSUE THREAD

**Issue by DoubleIntegral** [libretro/RetroArch#5913]
## Description
When trying to load core RetroArch gives 
```
[ERROR] Failed to open libretro core: .../.var/app/org.libretro.RetroArch/config/retroarch/cores/ppsspp_libretro.so"
[ERROR] Error(s): libsnappy.so.1: cannot open shared object file: No such file or directory
```
Of course snappy package is installed and libsnappy.so.1 is there

### Steps to reproduce the bug

1. Install RetroArch with flatpak
2. Download ppsspp core
3. Try to run any game with ppsspp core

### Version/Commit

- RetroArch: 1.6.9 e8b10d3 on Manjaro x64

**Comment by RobLoach** [comment]
Mind creating an issue over at https://github.com/flathub/org.libretro.RetroArch ?

You're unable to open the PPSSPP core. We'll need to add libsnappy to the FlatHub install.

**Comment by orbea** [comment]
Here is a better solution.
```
git clone https://github.com/libretro/RetroArch/
cd RetroArch
./configure && make && ./retroarch
```

**Comment by RobLoach** [comment]
Made an issue over at https://github.com/flathub/org.libretro.RetroArch/issues/32 .... Feel free to close this one.

**Comment by alexb3d** [comment]
The FFmpeg core does not load either.
