### ISSUE TITLE
Add slowmotion toggle switch

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#5915]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Add slowmotion toggle switch.

### Expected behavior

I want option "Slowmotion toggle" (On/Off), default is "Off".
When it ON, should be constantly slowmotion.

### Actual behavior

If I press slowmotion hotkey, while it pressed - I got slowmotion. After unpress it's return to fullspeed.

**Comment by hyarsan** [comment]
Yes please! I would recommend tab or left shift by default.

**Comment by RobLoach** [comment]
![https://user-images.githubusercontent.com/25086/37246478-6d1a87ca-2477-11e8-9fba-fd2ad2c4857b.png](https://user-images.githubusercontent.com/25086/37246478-6d1a87ca-2477-11e8-9fba-fd2ad2c4857b.png)
