### ISSUE TITLE
Shader presets (.cgp) in "Windows (CR LF)" EOL format crashing Retroarch.

### ISSUE THREAD

**Issue by James-F2** [libretro/RetroArch#5920]
Loading previously created CGP presets crashing Retroarch with latest builds.
Changing them to Unix (LF) with Notepad++ fixes that.
This means windows users can't edit the .cpg files without special software like Notepad++.

Windows7 64bit, Retroarch PC 64bit.

**Comment by twinaphex** [comment]
@Alcaro Could this be related to the changes we made in gfx/video_shader_parse.c when we changed it from RFILE_MODE_TEXT to the equivalent of RFILE_MODE_READ ?

**Comment by Alcaro** [comment]
The fgets rewrite seems more suspicious to me.

But no part of that region looks like it should crash. We need a stack trace to get anywhere with this one.

**Comment by twinaphex** [comment]
@James-F2 Can you post a preset file with which I could reproduce this issue on my end?

**Comment by James-F2** [comment]
[Stock 5x.zip](https://github.com/libretro/RetroArch/files/1565333/Stock.5x.zip)

All you have to do is change the EOL format to Windows and retroarch crashes:
![eol format](https://user-images.githubusercontent.com/31185814/34076761-51c11c1a-e2f9-11e7-9854-e4e960ced8ca.png)

**Comment by Ryunam** [comment]
I can confirm this is happening on my end as well. RA crashes whenever any .cgp shader previously created in Windows is loaded at startup.

**Comment by twinaphex** [comment]
Yeah, it must definitely be the reimplementation of filestream_gets as @Alcaro indicated. Unfortunately I really do need a reimplementation of that function, I cannot just call fgets and the VFS API does not have any 'gets' or 'getc' functions individually either, so the filestream_gets function should call filestream_getc which in turn will call filestream_seek, which in turn will call the VFS layer.

@Alcaro - can you help me making this function more robust so these errors can no longer happen?

**Comment by Alcaro** [comment]
While gets is my top suspect, we've done a lot of funny stuff recently, it could be something else. I need a stack trace before I can do anything useful.

**Comment by twinaphex** [comment]
I cannot reproduce this. I am re-saving the shader presets with Notepad ++ and changing it from Unix (LF) to Windows (CR LF), and yet it still works. Tried this with both Cg and GLSL shader presets, I use Load Shader Preset in order to load them.

**Comment by Alcaro** [comment]
https://github.com/libretro/RetroArch/commit/bfeb9ff5c24f78062be1b1397589edbacf48e8d4

This may or may not fix it. I have absolutely no idea why it'd cause THIS kind of issues, but memory corruption tends to show up in 'funny' ways...

**Comment by Alcaro** [comment]
https://github.com/libretro/RetroArch/commit/b2d5fad4f5c3f7800c6565389bcfd348ed1d41ba

This should fix it a bit more. Probably breaks something too, but ¯\\\_(ツ)\_/¯

**Comment by Alcaro** [comment]
it did indeed break something

https://github.com/libretro/RetroArch/commit/b7249525d4489f5385551ecdc9a8b988064b034e

**Comment by James-F2** [comment]
Fixed.
Thank you!
