### ISSUE TITLE
Gambatte 3ds sound crackling

### ISSUE THREAD

**Issue by fraf** [libretro/RetroArch#5927]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Gambatta sound IS crackling

### Expected behavior
Sound IS ok

### Actual behavior

Sound IS crackling

### Steps to reproduce the bug

1. Installer retroarch 1.6.7 or more 1.6.9
2. Load a gbc rom, link awakening for instance
3. Sound is bad

### Bisect Results

Was working on 1.3.x retroarch gambatte. From 1.6.7 (and maybe before it is broken)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: n3ds luma3ds + bs9 latest version.

**Comment by fr500** [comment]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs

**Comment by fr500** [comment]
Please report in the gambatte issue tracker
