### ISSUE TITLE
(D3D) It takes screenshots of the menu, not the game.

### ISSUE THREAD

**Issue by anyputer** [libretro/RetroArch#5928]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When you take screenshots using the Direct3D video driver, it takes a screenshot of the menu. It most likely happens because of the fact that it shows the game for a frame which is not long enough.

### Expected behavior

It take a screenshot of the game.

### Actual behavior

It takes a screenshot of the menu.

### Steps to reproduce the bug

1. Load content.
2. Go to the quick menu.
3. Scroll until you are at "Take Screenshot" and take a screenshot that way.

### Bisect Results

I don't remember when it did work, actually.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.6.9

### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW 64-bit from the buildbot

**Comment by bparker06** [comment]
Is there a reason you're using the d3d driver? It is very incomplete.

**Comment by hyarsan** [comment]
SDL2 and D3D runs a TON smoother than all of the other video drivers. I made an topic on the Libretro forums specifically for this but... no-one was able to help and no-one believed me. Quotes:

> 
> You must be the most unluckiest guy on earth then, that or you're jinxed and haunted.
> 
> RetroArch should be pretty straightforward to use and if I have a problem a fresh RetroArch installation usually fixes things in a jiffy.
> 
> It appears that nothing seems to help you, maybe you should try to re-install Windows altogether and start completely from fresh.
> 
> You're on Windows 10 Home, maybe a Windows Update caused this mess? But that would have affected standalone emulators too probably so I don't know.
> 
> It's anyone's guess at this point really.

-SigmaVirus on https://forums.libretro.com/t/libretro-cores-are-choppy-while-their-standalone-versions-are-not/12052/38

or

> Assuming it doesn't work (it should)...Why? it's a fallback driver for occassions when GL doesn't work properly I don't think anyone will sink serious time into it.

-radius ( yes, fr500 ) from https://forums.libretro.com/t/add-fast-forward-to-the-sdl2-video-driver/12252

or

https://github.com/libretro/RetroArch/issues/5628 -orbea

I mean, I don't want to seem "disrespectful" ( sorry fr500 I guess ) 
> Sorry that all the hours we put into this project as volunteers (for free) don't fulfill your expectations.
-fr500 from https://github.com/libretro/melonDS/issues/14

but just claiming that I don't appreciate the work of the devs ( twice but the proof is gone sadly, it was in
discord ) and ignoring these big issues just saddens me. I might've said something wrong here and there but... **goes to sleep**

**Comment by twinaphex** [comment]
I do agree we should try to fix this, the D3D driver should become important at a certain point.

**Comment by hyarsan** [comment]
What about the SDL2 driver? Is it going to keep being left out? I thought D3D wasn't for Linux? Lakka is choppy on PC.

**Comment by bparker06** [comment]
@hyarsan I read through your threads and it seems you never mentioned your GPU. What do you have?

Have you tried the gdi video driver? If that driver still shows performance issues with cores, then I have to admit it's highly likely there's some gremlin in your system, either hardware or software.

Can you also post a screenshot of the first page of "Information -> System Information" from the latest nightly please?

**Comment by hyarsan** [comment]
The GPU of this desktop that also has the choppyness ( I also have a laptop with the issue ) is
NVIDIA GeForce GTX 1050. Oh and here are the specs of this desktop:
![desktopspecs](https://user-images.githubusercontent.com/32988993/34136686-665935ee-e467-11e7-8eec-b8084ec08ebd.png)
If you want, I can also give you the specs of the laptop later that has this issue ( The threads were actually about the laptop, this desktop is new but it is equally as choppy. ) Or I can try to record it.
The gdi driver is even worse. Oh, and it's awesome that you are willing to research this :D

**Comment by fr500** [comment]
I don't see how the melonDS issue is related to this at all. Quoting it seems to stir shit for no reason.

You shouldn't have any perf issues with GL. But without being able to see it for ourselves it's hard to understand what choppiness is. Maybe take a video?

I have a PC running an i5-760 and a GTX760i and it's perfectly smooth. (I use the MMX3 intro to check for "choppyness" since it has a fast scrolling scene)

You should try the usual suspects, clean driver installation, remove any overlays (steam / discord / reshade / GFE)

Set the performance profile to max performance
![image](https://user-images.githubusercontent.com/1721040/34140707-801fb1aa-e44a-11e7-8ab8-3ecd768c94bc.png)

**Comment by hyarsan** [comment]
I tried to set the performance profile to max performance and recorded it but the result is not accurate at all. I used ShareX, anyone recommend other video recording software?

**Comment by fr500** [comment]
A phone with a camera

**Comment by bparker06** [comment]
I second the phone camera, not really an easier way to get something semi-accurate. Since GDI doesn't work right either, I'm 90% certain it's something not related to RA. I would look into possible DPC issues http://www.resplendence.com/latencymon.

**Comment by bparker06** [comment]
>I don't see how the melonDS issue is related to this at all. Quoting it seems to stir drama for no reason whatsoever.

@fr500 Would you rather he start a new issue? I'm fine with that as long as nobody brings any drama into it. I just want to help the guy... I'd be pretty frustrated too if I had this issue across different hardware when nobody else did. You know how I seem to be cursed as well.

**Comment by fr500** [comment]
No it's fine imho to keep going here

**Comment by hyarsan** [comment]
Nah, I didn't mean to start drama. I just wanted to make clear that I respect you and the other's work :D ❤️
I did not mean to be selfish or anything like that. I just wondered why after a month there is no response to the melonDS issue?
I am not sure if the phone camera is going to work but... I'll try.

**Comment by bparker06** [comment]
Also @hyarsan since you are on the Fall Creators Update, there is a good chance this is the biggest cause of your problems. See here:

https://github.com/libretro/RetroArch/issues/5607

**Comment by hyarsan** [comment]
But then how come Lakka was really choppy for me ( On another laptop ) ? And why was it choppy before the update too? ( On another laptop... ) And I thought I said it was 60 fps? ( Full speed )
...maybe that's one of the reasons? I use full screen most of the time too. You know what? Forget what I just said.

I guess that #5607 is the issue here! No weird choppyness when I use full screen! :) Is #5607 talking about the frame rate? If not, then that's the real issue! I dunno, first that needs to be fixed. That core i7 laptop has really bad frame rates ( Probably because it has a ton of shiz installed ) Not sure about Lakka though.

**Comment by bparker06** [comment]
I have no idea. But we do need some video proof to understand just what "choppy" means. We're all scratching our heads over here.

**Comment by hyarsan** [comment]
I feel like #5607 is more important first. So far it seems to have fixed it, at least on this device... in full screen of course.

**Comment by retro-wertz** [comment]
https://forums.libretro.com/t/libretro-cores-are-choppy-while-their-standalone-versions-are-not/12052

The same guy?

**Comment by hyarsan** [comment]
Yeah, Flooder is me.

**Comment by sonninnos** [comment]
Closing since it does not seem to be happening anymore.
