### ISSUE TITLE
Polish font and translation 

### ISSUE THREAD

**Issue by DEX357** [libretro/RetroArch#5934]
No working font for the ps3 retroarch version, Add polish translation, mixed Polish translation with English

**Comment by alfrix** [comment]
@DEX357 the translation it's done, there should not be any more english, it was merged the 18 December, so you can check it out in the last nightly, please download the last version at
https://buildbot.libretro.com/nightly/playstation/ps3/
The ps3 version may have a font problem please put a screenshot up after installing the latest nightly build.

@bparker06 this may be similar to #4765 in regards of missing glyphs for some languages, but i don't know what font does the ps3 version uses by default

**Comment by DEX357** [comment]
Translation is good. but PL glyphs still looks like (?)
I try to change font to Roboto... and other, still dont work.
https://ibb.co/e3QF26

**Comment by DEX357** [comment]
Something went wrong, games do not turn on after turning on the core, Retroarch goes back to XBM, after that you can not turn on the retroarch automatically turns off

**Comment by bparker06** [comment]
@alfrix It appears that there is no Unicode-enabled font renderer being built for PS3, this is what's needed to fix the glyph issue. On PC the Polish translation appears fine with the default built-in font.

Both freetype and stb-unicode are undefined for PS3 builds so it currently has no Unicode font support. @twinaphex Is it possible to use one of those two for PS3 or is there some build issue holding it back?

**Comment by bparker06** [comment]
@DEX357 @alfrix I pushed a change that enable the stb-unicode font renderer for PS3, it should be available in the next nightly. Hopefully you should have no problem displaying Polish text now.

**Comment by DEX357** [comment]
Nice its work :)

**Comment by DEX357** [comment]
PL translation broke Sega core, I changed it for an older one and it works but witch out new translation change.

**Comment by bparker06** [comment]
"PL translation" can't break a core, please file that as a separate issue.

**Comment by fr500** [comment]
Please fill up the issue template when reporting problems
