### ISSUE TITLE
Crash On Android.

### ISSUE THREAD

**Issue by omerrahmann** [libretro/RetroArch#5939]
-RetroArch closes by it self after coming out of a game. Any game.
-RetroArch sometimes Freezes the phone on its UI ,the phone stops responding and have to force restart to get the phone to work bcuz the phone wont respond to the touches.

**Comment by fr500** [comment]
You didn't fill the template.

**Comment by omerrahmann** [comment]
what template?

**Comment by fr500** [comment]
When you click new issue it gives you a template of stuff to fill. You deleted everything.
Those are the issue posting guidelines. There is nothing in this report that can help us pinpoint the problem.
