### ISSUE TITLE
genesis_plus_gx_libretro_ps3

### ISSUE THREAD

**Issue by DEX357** [libretro/RetroArch#5949]
genesis_plus_gx_libretro_ps3 freez in black screen after launch game, after that the console must be hard turned off

**Comment by ofry** [comment]
Are work other cores?

**Comment by DEX357** [comment]
Yes I test all other cores and only this permanently freezes consoles that you can not do anything but turn it off

**Comment by ofry** [comment]
Then you need to create issue there. https://github.com/libretro/Genesis-Plus-GX/issues

because it's core issue, not RA itself.

**Comment by DEX357** [comment]
I found a problem, I used the old core, the Polish translation apparently something that causes the Sega core to hang
