### ISSUE TITLE
Core options quick toggle

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#5952]
Something that would be useful is if you could set a key / button for toggling a core option. For example, you could set the letter K to toggle the "Screen layout positioning" core option in Citra Libretro.

**Comment by nileplumb** [comment]
Yup just started using the citra core, being able to flip the active screen would be very useful

**Comment by RobLoach** [comment]
This could/should likely be handled by the core itself... Mind making an issue in the libretro citra core issue queue?
