### ISSUE TITLE
Not looking in /usr/local

### ISSUE THREAD

**Issue by dariusc93** [libretro/RetroArch#5958]
Not exactly a bug, but on FreeBSD while running `./configure --enable-opengl`, it doesnt detect GL/gl.h, however, retroarch is not is not taking /usr/local into account when looking for headers and libraries. There should be checks in place so retroarch could build with not just opengl, but any other library installed in that path for FreeBSD. Currently running FreeBSD 11.1-RELEASE, but I cannot speak for NetBSD if this is a issue or not. 

For reference

```
./configure --enable-opengl
Checking operating system ... BSD 
Checking for suitable working C compiler ... /usr/bin/cc works
Checking for suitable working C++ compiler ... /usr/bin/c++ works
Checking for pkg-config ... /usr/local/bin/pkgconf
Checking for availability of switch -std=gnu99 in /usr/bin/cc ... yes
Checking for availability of switch -Wno-unused-result in /usr/bin/cc ... yes
Checking for availability of switch -Wno-unused-variable in /usr/bin/cc ... yes
Checking function sd_get_machine_names in -lsystemd ... no
Checking presence of package bcm_host ... no
Checking function bcm_host_init in -lbcm_host ... no
Checking presence of package egl ... 17.1.10
Checking function ass_library_init in -lass ... no
Checking function pthread_create in -lpthread ... yes
Checking function pthread_key_create in -lpthread ... yes
Checking function dlopen in -lc ... yes
Checking function socket in -lc ... yes
Checking function getaddrinfo in -lc ... yes
Checking function fcntl in -lc ... yes
Checking function getopt_long in -lc ... yes
Checking presence of package alsa ... 1.1.2
Checking presence of header file sys/soundcard.h ... yes
Checking presence of header file soundcard.h ... no
Checking existence of -lossaudio ... no
Checking function alcOpenDevice in -lopenal ... no
Checking presence of package rsound >= 1.1 ... no
Checking presence of package libroar ... no
Checking presence of package jack >= 0.120.1 ... 0.125.0rc1
Checking presence of package libpulse ... 11.0
Checking presence of package sdl >= 1.2.10 ... 1.2.15
Checking presence of package sdl2 >= 2.0.0 ... 2.0.7
Notice: SDL drivers will be replaced by SDL2 ones.
Checking presence of package libusb-1.0 >= 1.0.13 ... 1.0.13
Checking presence of header file GL/gl.h ... no
Build assumed that GL/gl.h exists, but cannot locate. Exiting ...
```

Proof of GL/gl.h existance in /usr/local/include
```
$ ls /usr/include/GL
ls: /usr/include/GL: No such file or directory

$ ls -ln /usr/local/include/GL | grep gl.h
-rw-r--r--  1 0  0    80615 Dec 14 02:13 gl.h
```

**Comment by orbea** [comment]
What RetroArch version are you using? I tried this on freebsd with the git master and it worked for me.
```
Checking presence of header file GL/gl.h ... yes
Checking existence of -lGL ... yes
```
```
$ ls /usr/include/GL/gl.h
ls: /usr/include/GL/gl.h: No such file or directory

$ ls /usr/local/include/GL/gl.h
/usr/local/include/GL/gl.h
```
```
$ ./configure --enable-opengl
Checking operating system ... BSD 
Checking for suitable working C compiler ... /usr/local/bin/gcc works
Checking for suitable working C++ compiler ... /usr/local/bin/g++ works
Checking for pkg-config ... /usr/local/bin/pkgconf
Checking for availability of switch -std=gnu99 in /usr/local/bin/gcc ... yes
Checking for availability of switch -Wno-unused-result in /usr/local/bin/gcc ... yes
Checking for availability of switch -Wno-unused-variable in /usr/local/bin/gcc ... yes
Checking function sd_get_machine_names in -lsystemd ... no
Checking presence of package bcm_host ... no
Checking function bcm_host_init in -lbcm_host ... no
Checking presence of package egl ... 17.1.0
Checking function ass_library_init in -lass ... no
Checking function pthread_create in -lpthread ... yes
Checking function pthread_key_create in -lpthread ... yes
Checking function dlopen in -lc ... yes
Checking function socket in -lc ... yes
Checking function getaddrinfo in -lc ... yes
Checking function fcntl in -lc ... yes
Checking function getopt_long in -lc ... yes
Checking presence of package alsa ... no
Checking presence of header file sys/soundcard.h ... yes
Checking presence of header file soundcard.h ... no
Checking existence of -lossaudio ... no
Checking function alcOpenDevice in -lopenal ... no
Checking presence of package rsound >= 1.1 ... no
Checking presence of package libroar ... no
Checking presence of package jack >= 0.120.1 ... no
Checking presence of package libpulse ... no
Checking presence of package sdl >= 1.2.10 ... no
Checking presence of package sdl2 >= 2.0.0 ... no
Checking presence of package libusb-1.0 >= 1.0.13 ... no
Checking presence of header file GL/gl.h ... yes
Checking existence of -lGL ... yes
Checking function cgCreateContext in -lCg -lCgGL ... no
Checking presence of package zlib ... 1.2.8
Checking presence of package libavcodec >= 54 ... no
Checking presence of package libavformat >= 54 ... no
Checking presence of package libavdevice ... no
Checking presence of package libswresample ... no
Checking presence of package libavresample ... no
Checking presence of package libavutil >= 51 ... no
Checking presence of package libswscale >= 2.1 ... no
Checking presence of header file libavutil/channel_layout.h ... no
Notice: FFmpeg built-in support disabled due to missing or unsuitable packages.
Checking function dlopen in -lc ... yes
Checking presence of package gbm >= 9.0 ... 17.1.0
Checking presence of package libdrm ... 2.4.80
Checking presence of package libxml-2.0 ... 2.9.4
Checking presence of package vg ... no
Checking existence of -lOpenVG ... no
Checking presence of package libv4l2 ... no
Checking presence of package freetype2 ... 20.0.14
Checking presence of package x11 ... 1.6.5
Checking presence of package xcb ... 1.12
Checking presence of package wayland-egl ... no
Checking presence of package wayland-cursor ... no
Checking presence of package xkbcommon >= 0.3.2 ... no
Checking presence of package xext ... 1.3.3
Checking presence of package xxf86vm ... 1.1.4
Checking presence of package xinerama ... 1.1.3
Checking presence of package xv ... no
Checking presence of package libudev ... no
Checking existence of -ludev ... no
Checking presence of header file linux/parport.h ... no
Checking function strlcpy in -lc ... yes
Checking function strcasestr in -lc ... yes
Checking function mmap in -lc ... yes
Checking function vkCreateInstance in -lvulkan ... no
Creating make config: config.mk
Creating config header: config.h
```

**Comment by dariusc93** [comment]
Im using the one from the master branch as well.

**Comment by orbea** [comment]
Then, what's the difference? I'm not very familiar with freebsd and only have a remote server to test on, maybe you can help me understand?

Basically it will use the `check_header` function in `qb/qb.libs.sh` which will create this `.tmp.c` and use your compiler to build it. If it builds it considers that you have `GL/gl.h`.
```
#include <GL/gl.h>
int main(void) { return 0; }
```
So I presume `/usr/local/include` is not part of your default include path?

This is with.
```
$ freebsd-version -ku
10.3-RELEASE-p20
10.3-RELEASE-p21
```

**Comment by orbea** [comment]
What is your `$PATH` variable? For me its.
```
$ echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/home/orbea/bin
```
Now if I export this new `$PATH` without `/usr/local/bin` it fails.
```
export PATH='/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/home/orbea/bin'
```
```
Checking presence of header file GL/gl.h ... no
Build assumed that GL/gl.h exists, but cannot locate. Exiting ...
```
Is `/usr/local/bin` missing from your `$PATH`? If so I'm not sure what can be done besides fixing your `$PATH. :)

**Comment by dariusc93** [comment]
I am aware of the small snippet of code being used and as far as I can tell, `/usr/local/include` isnt apart of my default include path. I do see that the compiler is looking at `/usr/include` (as it should) but in many of my projects, I usually define the paths manually, so I guess it never caught on until now while building retroarch. 

Also here is my path

```
$ echo $PATH
/home/darius/.cargo/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/darius/bin
```

So that path does exist there. The only difference I see is that youre using 10.3-RELEASE, though that shouldnt really matter.

**Comment by orbea** [comment]
Well, this is puzzling. A work around would to add /usr/local/include to the include path if `OS=BSD`, but I would like to know why its currently working for others?

**Comment by dariusc93** [comment]
Thats what I am trying to figure out as well. Does `GL/gl.h` exist in `/usr/local/include` or `/usr/include` for you?

**Comment by orbea** [comment]
Its in `/usr/local/include/GL/gl.h` for me.

Sharing the contents of `config.log`, `config.h` and `config.mk` which are automatically generated by `./configure` might help also.

**Comment by orbea** [comment]
Does this work around it for you?
```
export C_INCLUDE_PATH=/usr/local/include
./configure --enable-opengl
```

**Comment by dariusc93** [comment]
I did check those earlier and they looked fine to me 

config.log 
```
/usr/bin/ld: cannot find -lsystemd
cc: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld: cannot find -lvcos
cc: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld: cannot find -lass
cc: error: linker command failed with exit code 1 (use -v to see invocation)
.tmp.c:1:10: fatal error: 'soundcard.h' file not found
#include <soundcard.h>
         ^~~~~~~~~~~~~
1 error generated.
/usr/bin/ld: cannot find -lossaudio
cc: error: linker command failed with exit code 1 (use -v to see invocation)
/usr/bin/ld: cannot find -lopenal
cc: error: linker command failed with exit code 1 (use -v to see invocation)
.tmp.c:1:10: fatal error: 'GL/gl.h' file not found
#include <GL/gl.h>
         ^~~~~~~~~
1 error generated.
```

config.mk
```
CC = /usr/bin/cc
CFLAGS = 
WINDRES = 
ASFLAGS = 
LDFLAGS = 
INCLUDE_DIRS = -I./deps/7zip
LIBRARY_DIRS = 
PACKAGE_NAME = retroarch
BUILD = 
PREFIX = /usr/local
HAVE_7ZIP = 1
HAVE_AL = 0
ifneq ($(C89_BUILD),1)
HAVE_ALSA = 1
endif
ALSA_CFLAGS = -I/usr/local/include -I/usr/local/include/alsa
ALSA_LIBS = -L/usr/local/lib -lasound
HAVE_AVCODEC = 1
AVCODEC_CFLAGS = -I/usr/local/include
AVCODEC_LIBS = -L/usr/local/lib -lavcodec
HAVE_AVDEVICE = 1
AVDEVICE_CFLAGS = -I/usr/local/include
AVDEVICE_LIBS = -L/usr/local/lib -lavdevice
HAVE_AVFORMAT = 1
AVFORMAT_CFLAGS = -I/usr/local/include
AVFORMAT_LIBS = -L/usr/local/lib -lavformat
HAVE_AVRESAMPLE = 1
AVRESAMPLE_CFLAGS = -I/usr/local/include
AVRESAMPLE_LIBS = -L/usr/local/lib -lavresample
HAVE_AVUTIL = 1
AVUTIL_CFLAGS = -I/usr/local/include
AVUTIL_LIBS = -L/usr/local/lib -lavutil
HAVE_AV_CHANNEL_LAYOUT = 0
ifneq ($(C89_BUILD),1)
HAVE_BUILTINMINIUPNPC = 1
endif
HAVE_BUILTINZLIB = 0
HAVE_C99 = 1
HAVE_CACA = 0
HAVE_CG = 0
HAVE_CHEEVOS = 1
HAVE_COMMAND = 1
HAVE_D3D9 = 0
HAVE_DBUS = 0
HAVE_DISPMANX = 0
HAVE_DRM = 1
DRM_CFLAGS = -I/usr/local/include -I/usr/local/include/libdrm
DRM_LIBS = -L/usr/local/lib -ldrm
HAVE_DYLIB = 1
DYLIB_LIBS = -lc
HAVE_DYNAMIC = 1
DYNAMIC_LIBS = -lc
HAVE_EGL = 1
EGL_CFLAGS = -I/usr/local/include -I/usr/local/include/libdrm -D_THREAD_SAFE -pthread
EGL_LIBS = -L/usr/local/lib -lEGL
HAVE_EXYNOS = 0
ifneq ($(C89_BUILD),1)
HAVE_FFMPEG = 1
endif
ifneq ($(C89_BUILD),1)
HAVE_FLAC = 1
endif
HAVE_FLOATHARD = 0
HAVE_FLOATSOFTFP = 0
HAVE_FREETYPE = 1
FREETYPE_CFLAGS = -I/usr/local/include/freetype2
FREETYPE_LIBS = -L/usr/local/lib -lfreetype
HAVE_GBM = 1
GBM_CFLAGS = -I/usr/local/include
GBM_LIBS = -L/usr/local/lib -lgbm
HAVE_GETADDRINFO = 1
GETADDRINFO_LIBS = -lc
HAVE_GETOPT_LONG = 1
GETOPT_LONG_LIBS = -lc
HAVE_HID = 1
HAVE_IBXM = 1
HAVE_IMAGEVIEWER = 1
HAVE_JACK = 1
JACK_CFLAGS = -I/usr/local/include
JACK_LIBS = -L/usr/local/lib -ljack -pthread
HAVE_KEYMAPPER = 1
HAVE_KMS = 1
HAVE_LANGEXTRA = 1
HAVE_LIBRETRODB = 1
ifneq ($(C89_BUILD),1)
HAVE_LIBUSB = 1
endif
LIBUSB_LIBS = -lusb
HAVE_LIBXML2 = 1
LIBXML2_CFLAGS = -I/usr/local/include/libxml2
LIBXML2_LIBS = -L/usr/local/lib -lxml2
HAVE_MALI_FBDEV = 0
HAVE_MATERIALUI = 0
HAVE_MINIUPNPC = 1
HAVE_MMAP = 1
MMAP_LIBS = -lc
HAVE_NEON = 0
ifneq ($(C89_BUILD),1)
HAVE_NETWORKGAMEPAD = 1
endif
HAVE_NETWORKING = 1
NETWORKING_LIBS = -lc
HAVE_NETWORK_CMD = 1
HAVE_NOUNUSED = 1
HAVE_NOUNUSED_VARIABLE = 1
HAVE_NUKLEAR = 0
HAVE_OMAP = 0
HAVE_OPENDINGUX_FBDEV = 0
HAVE_OPENGL = 0
HAVE_OPENGLES = 0
HAVE_OPENGLES3 = 0
HAVE_OSMESA = 0
HAVE_OSS = 1
HAVE_OSS_BSD = 0
HAVE_OSS_LIB = 0
HAVE_PARPORT = 0
HAVE_PLAIN_DRM = 0
HAVE_PRESERVE_DYLIB = 0
ifneq ($(C89_BUILD),1)
HAVE_PULSE = 1
endif
PULSE_CFLAGS = -I/usr/local/include -D_REENTRANT
PULSE_LIBS = -L/usr/local/lib -lpulse -lpthread
HAVE_PYTHON = 0
HAVE_QT = 0
HAVE_QT_WRAPPER = 0
HAVE_RBMP = 1
HAVE_RGUI = 1
HAVE_RJPEG = 1
HAVE_ROAR = 0
HAVE_RPNG = 1
HAVE_RSOUND = 0
HAVE_RTGA = 1
HAVE_SDL = 0
SDL_CFLAGS = -I/usr/local/include/SDL -I/usr/local/include -D_REENTRANT -D_THREAD_SAFE
SDL_LIBS = -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL -pthread
ifneq ($(C89_BUILD),1)
HAVE_SDL2 = 1
endif
SDL2_CFLAGS = -I/usr/local/include/SDL2 -I/usr/local/include -D_REENTRANT -D_THREAD_SAFE
SDL2_LIBS = -L/usr/local/lib -lSDL2
ifneq ($(C89_BUILD),1)
HAVE_SHADERPIPELINE = 1
endif
HAVE_SOCKET_LEGACY = 0
HAVE_SSA = 0
HAVE_SSE = 0
HAVE_STB_FONT = 1
HAVE_STB_IMAGE = 1
HAVE_STB_VORBIS = 1
HAVE_STDIN_CMD = 1
STDIN_CMD_LIBS = -lc
HAVE_STRCASESTR = 1
STRCASESTR_LIBS = -lc
HAVE_STRL = 1
STRL_LIBS = -lc
HAVE_SUNXI = 0
HAVE_SWRESAMPLE = 1
SWRESAMPLE_CFLAGS = -I/usr/local/include
SWRESAMPLE_LIBS = -L/usr/local/lib -lswresample
HAVE_SWSCALE = 1
SWSCALE_CFLAGS = -I/usr/local/include
SWSCALE_LIBS = -L/usr/local/lib -lswscale
HAVE_SYSTEMD = 0
HAVE_THREADS = 1
THREADS_LIBS = -lpthread
HAVE_THREAD_STORAGE = 1
THREAD_STORAGE_LIBS = -lpthread
HAVE_UDEV = 0
HAVE_UPDATE_ASSETS = 1
HAVE_V4L2 = 1
V4L2_CFLAGS = -I/usr/local/include
V4L2_LIBS = -L/usr/local/lib -lv4l2
HAVE_VC_TEST = 0
HAVE_VG = 0
HAVE_VIDEOCORE = 0
HAVE_VIDEO_PROCESSOR = 1
HAVE_VIVANTE_FBDEV = 0
HAVE_VULKAN = 0
HAVE_VULKAN_DISPLAY = 1
HAVE_WAYLAND = 0
HAVE_WAYLAND_CURSOR = 0
HAVE_X11 = 1
X11_CFLAGS = -I/usr/local/include -D_THREAD_SAFE -pthread
X11_LIBS = -L/usr/local/lib -lX11
HAVE_XCB = 1
XCB_CFLAGS = -I/usr/local/include -pthread
XCB_LIBS = -L/usr/local/lib -lxcb
HAVE_XEXT = 1
XEXT_CFLAGS = -I/usr/local/include -D_THREAD_SAFE -pthread
XEXT_LIBS = -L/usr/local/lib -lXext
HAVE_XF86VM = 1
XF86VM_CFLAGS = -I/usr/local/include -D_THREAD_SAFE -pthread
XF86VM_LIBS = -L/usr/local/lib -lXxf86vm
HAVE_XINERAMA = 1
XINERAMA_CFLAGS = -I/usr/local/include -D_THREAD_SAFE -pthread
XINERAMA_LIBS = -L/usr/local/lib -lXinerama
HAVE_XKBCOMMON = 1
XKBCOMMON_CFLAGS = -I/usr/local/include
XKBCOMMON_LIBS = -L/usr/local/lib -lxkbcommon
HAVE_XMB = 0
HAVE_XSHM = 0
HAVE_XVIDEO = 1
XVIDEO_CFLAGS = -I/usr/local/include -D_THREAD_SAFE -pthread
XVIDEO_LIBS = -L/usr/local/lib -lXv
HAVE_ZARCH = 0
HAVE_ZLIB = 1
ZLIB_LIBS = -lz
NOUNUSED = yes
NOUNUSED_VARIABLE = yes
DYLIB_LIB = -lc
ASSETS_DIR = /usr/local/share
BIN_DIR = /usr/local/bin
MAN_DIR = /usr/local/share/man
OS = BSD
GLOBAL_CONFIG_DIR = /etc
```

and that works for detecting the headers but not the library itself as it would give an 
```
Checking existence of -lGL ... no
Forced to build with library -lGL, but cannot locate. Exiting ...
```

**Comment by orbea** [comment]
This is not an explanation and not really a solution, but does this diff work around the issue for you?
```
diff --git a/qb/config.libs.sh b/qb/config.libs.sh
index 615c36853..b7d79eae4 100644
--- a/qb/config.libs.sh
+++ b/qb/config.libs.sh
@@ -290,8 +290,8 @@ if [ "$HAVE_OPENGL" != 'no' ] && [ "$HAVE_OPENGLES" != 'yes' ]; then
       check_header OPENGL "GL/gl.h"
       check_lib '' OPENGL -lopengl32
    else
-      check_header OPENGL "GL/gl.h"
-      check_lib '' OPENGL -lGL
+      check_pkgconf OPENGL gl
+      check_val '' OPENGL -lGL
    fi
 
    if [ "$HAVE_OPENGL" = 'yes' ]; then
```

**Comment by dariusc93** [comment]
That does work, though its abit odd

**Comment by dariusc93** [comment]
Yep. I can confirm it works and it does build.

**Comment by orbea** [comment]
Seems for some reason your system does not know to look in `/usr/local/include` and the `check_header` function does not work. However `pkgconf` is smart enough to not have this issue and maybe it did not need `check_header` in the first place where `check_lib` would have been enough? `check_val` pretty much does that, but is used as a fallback if there is no installed pkg-config implementation.

**Comment by orbea** [comment]
Seems the `check_header` function is useful. If I temporarily move `gl.h` out of the way `check_lib` will still pass, but the actual build will of course fail.

**Comment by dariusc93** [comment]
Hmm still kind of interesting though. I am going to test on another system to see if it is my system or if its something dealing with freebsd itself. Sadly, on that system im going to test with, I cannot use 10.x or 11.x due to it being newer hardware, but I still believe the results will remain the same.

**Comment by orbea** [comment]
It would be worth seeing how widespread this issue is. My freebsd environment is just a remote server a friend lets me use so I don't really have any control of what is installed. I do know @bparker06 uses freebsd too and it likely works for him?

**Comment by dariusc93** [comment]
Yep, on 12-CURRENT, it does the same thing, with it being a fresh install. Quiet annoying but I am going to load up 10.3-RELEASE (and while at it, 10.4-RELEASE) and see if it happens on there, but honestly based on what I am seeing, it should work right out of the box.

**Comment by bparker06** [comment]
Hi,

I'm on FreeBSD 11.1, using gcc 6.4.0 via the ports package (installed the binary package via `pkg install gcc-6`), and at least with that compiler, /usr/local/include is included and GL is found. The default system compiler may not include /usr/local though, and I know for a fact that NetBSD requires `pkg-config` in order to find e.g. /usr/local/lib for certain libraries and probably includes too, their port IIRC adds a patch for this.

**Comment by orbea** [comment]
Thanks for the info, with this information I think this diff should be a proper fix for `check_header`. @dariusc93 can you test it? :)
```
diff --git a/qb/config.libs.sh b/qb/config.libs.sh
index 54d1706f05..05b0e8ce0f 100644
--- a/qb/config.libs.sh
+++ b/qb/config.libs.sh
@@ -23,6 +23,7 @@ SOCKETLIB=-lc
 SOCKETHEADER=
 
 if [ "$OS" = 'BSD' ]; then
+   [ -d /usr/local/include ] && add_dirs INCLUDE /usr/local/include
    DYLIB=-lc;
 elif [ "$OS" = 'Haiku' ]; then
    DYLIB=""
```

**Comment by bparker06** [comment]
I don't agree with hardcoding /usr/local/include, the user's compiler could be looking anywhere. `pkg-config` would be a better solution IMO.

**Comment by orbea** [comment]
I don't think `pkg-config` is a good choice here. While `gl.pc` does exist, it contains no references to `gl.h` and `pkgconf --exists gl` will return true even when `gl.h` does not exist. This will will result in a broken build where `#  include <GL/gl.h>` fails. However you are right about the issues with my solution...

To be honest, the best fix would be for people to actually include `GL/gl.h` by default, but I guess that is too much to ask for from freebsd and others...

**Comment by bparker06** [comment]
`pkgconf` doesn't return true for me (assuming you mean 1 to be true):

```[bp@fbsd ~]$ pkgconf --exists gl
[bp@fbsd ~]$ echo $?
0
```

But I meant using pkg-config to get the proper include/lib dirs for GL, which it would not provide if it wasn't available:

```
[bp@fbsd ~]$ pkg-config --cflags gl
-I/usr/local/include -I/usr/local/include/libdrm -D_THREAD_SAFE -pthread
[bp@fbsd ~]$ pkg-config --libs gl
-L/usr/local/lib -lGL
```

If you used those cflags/libs commands during configure, and the build failed, then that's acceptable, it will just disable GL as it should. If the build succeeds, then it should also use those commands to add onto the includes/libs when building. Does that make sense?

**Comment by orbea** [comment]
It does return true, `echo $?` returns the error code where `0` is true and any other number is false.
```
$ pkgconf --exists gl
$ echo $?
0
$ pkgconf --exists fooo
$ echo $?
1
```
The problem with that two fold, `GL/gl.h` is not in `/usr/local/include/libdrm` and not all systems have pkgconf which will require a fallback, see the `check_val` function.

**Comment by orbea** [comment]
Also `qb/config.libs.sh` already does hardcode include paths for distros like raspian.
```
if [ "$HAVE_VIDEOCORE" = 'yes' ]; then
   HAVE_OPENGLES='auto'
   VC_PREFIX="brcm"

   # use fallback if pkgconfig is not available
   if [ ! "$VC_TEST_LIBS" ]; then
      [ -d /opt/vc/include ] && add_dirs INCLUDE /opt/vc/include
      [ -d /opt/vc/include/interface/vcos/pthreads ] && add_dirs INCLUDE /opt/vc/include/interface/vcos/pthreads
      [ -d /opt/vc/include/interface/vmcs_host/linux ] && add_dirs INCLUDE /opt/vc/include/interface/vmcs_host/linux
      EXTRA_GL_LIBS="-lbrcmEGL -lbrcmGLESv2 -lbcm_host -lvcos -lvchiq_arm"
   fi
fi
```
However that is a better scenario because pkgconf does work (when installed) while here it just misses the important `GL/gl.h`...

**Comment by bparker06** [comment]
I don't understand how any of that matters with what I said about using `pkg-config` (not `pkgconf`).

**Comment by dariusc93** [comment]
Correct me if im wrong but I recall `pkgconf` and `pkg-config` being the same on freebsd. NetBSD may only have `pkg-config`

**Comment by orbea** [comment]
@bparker06 My understanding that `pkg-config` will not be able to test that `gl.h` specifically exists and even if it will detect `gl.pc` or `-lGL` correctly and set the `--cflags` and `--libs` accordingly the RetroArch build will still fail if `gl.h` is missing which it specifically requires.

In short I think we need to make sure `gl.h` specifically exists for `--enable-opengl` or we may run into unexpected build failures.

Consider this earlier diff I posted which will use `check_pkgconf` (And `check_lib` via `check_val` if pkg-config is not installed.) After applying the diff try this test.
```
sudo mv /usr/include/GL/gl.h /tmp # or w/e your gl.h is
./configure --enable-opengl # passes because gl.pc or -lGL exists
make # Fails because it specifically requires gl.h which is no longer tested for.
```
```
diff --git a/qb/config.libs.sh b/qb/config.libs.sh
index 615c36853..b7d79eae4 100644
--- a/qb/config.libs.sh
+++ b/qb/config.libs.sh
@@ -290,8 +290,8 @@ if [ "$HAVE_OPENGL" != 'no' ] && [ "$HAVE_OPENGLES" != 'yes' ]; then
       check_header OPENGL "GL/gl.h"
       check_lib '' OPENGL -lopengl32
    else
-      check_header OPENGL "GL/gl.h"
-      check_lib '' OPENGL -lGL
+      check_pkgconf OPENGL gl
+      check_val '' OPENGL -lGL
    fi
 
    if [ "$HAVE_OPENGL" = 'yes' ]; then
```
@dariusc93 Yes, `pkg-config` is the older implementation by freedesktop.org and `pkgconf` is a newer implementation by devs from alpine, freebsd and some others made because of frustration with `pkg-config's` legacy/buggy behavior.  There are also other `pkg-config` implementations like one made with perl for openbsd, but since you are using freebsd you have `pkgconf` and `pkg-config is a symlink.
```
$ ls -l /usr/local/bin/pkg-config 
lrwxr-xr-x  1 root  wheel  7 May 31  2017 /usr/local/bin/pkg-config -> pkgconf
```
As far as the RetroArch configure script is considered both `pkgconf` and `pkg-config` are supported, but it will check if `pkgconf` exists first.

**Comment by dariusc93** [comment]
I do see what you mean @orbea by it not checking the headers, but however pkgconf (and/or pkg-config) may still be a useful option in this because the chances of the libraries existing but not the headers are extremely low.

**Comment by orbea** [comment]
Personally I prefer a fail safer approach and not make assumptions that such a scenario will not happen. I don't control what operating systems maintainers do, otherwise freebsd would actually sanely include this header by default...

What could go wrong with hard coding `/usr/local/include` for *bsd? Seems its a requirement already for RetroArch. We could also test for specific directories in `/usr/local/include` and only include those (If found)?

**Comment by dariusc93** [comment]
I dont see anything really going wrong for it to be hard coded honestly. Might be a good idea to also test for directories (though including /usr/local should just be enough).

**Comment by bparker06** [comment]
@orbea I still don't think you get what I'm saying. If pkg-config or pkgconf or whatever is used in order to *compile the ./configure test program*, then the subsequent build can't fail, because if gl.h was unavailable, the configure test would silently fail and *disable GL* from being built. Then if the configure test *does* succeed, you can add the output of pkgconf to the include/libs as needed.

**Comment by orbea** [comment]
@bparker06 I don't think you understand.  The `check_pkgconf` function already adds the results of include/libs from pkgconf, but pkgconf doesn't add the ones RetroArch actually needs for opengl support which is why its currently checking for the explicit `gl.h` header and that `-lGL` works. Pkgconf can only tell us what `gl.pc` knows and `gl.pc` doesn't know we need `gl.h`.

**Comment by orbea** [comment]
@dariusc93 I made a PR given that the choices seem to be.

1. Leave it broken (Not a good choice).
2. Include /usr/local/include if it exists for *bsd.
3. Use an incomplete and potentially error prone solution with pkgconf.

Can you confirm it works for you?

**Comment by dariusc93** [comment]
@orbea With your pr, it sees the header but not the library.


```
Checking presence of header file GL/gl.h ... yes
Checking existence of -lGL ... no
```

Adding the following fixes it

```
[ -d /usr/local/lib ] && add_dirs LIBRARY /usr/local/lib
```

**Comment by orbea** [comment]
Done, thanks.
