### ISSUE TITLE
UI broken since 1.6.9 in a path with special characters on Windows 10

### ISSUE THREAD

**Issue by t1254362** [libretro/RetroArch#5959]
## Description
Since RetroArch 1.6.9 (and continue happening on 1.7) UI is broken when I have RetroArch in a path with special chars on Windows 10.

I had RetroArch on this path: D:/Emulación/RetroArch
And since 1.6.9 it shows liike this:
![Broken interface](https://i.imgur.com/nJwlFkr.png)

But if I move RetroArch to D:/ it works OK (see Expected behavior), so it seems that something happen between 1.6.7 and 1.6.9 that broke this.

### Expected behavior
Show the correct interface in any folder
![Correct interface](https://i.imgur.com/Yv2fhK2.png)

### Actual behavior
Display black squares when RetroArch is in D:/Emulación/RetroArch
![Broken interface](https://i.imgur.com/nJwlFkr.png)

### Steps to reproduce the bug
Put RetroArch in a path with special chars, for example D:/Emulación/RetroArch

### Version/Commit
Since 1.6.9 release, it occurs in the actual 1.7

### Environment information

- OS: Windows 10

**Comment by orbea** [comment]
Can you bisect this?

**Comment by fr500** [comment]
@bparker06 do you have any ideas regarding this?

**Comment by t1254362** [comment]
I can't tell you the exact commit because I use your official releases. I can say that 1.6.7 doesn't have this problem, but 1.6.9 yes (and 1.7 too).

**Comment by t1254362** [comment]
I supose that this will be some problem loading paths with new code to handle unicode.

https://www.libretro.com/index.php/retroarch-1-6-9-released/

– WINDOWS: Support Unicode file I/O (can now display CJK characters in file browser for example).

Can be a candidate to check.

**Comment by orbea** [comment]
It would really help to determine what caused this regression and fix it sooner if someone with a windows environment could use git to bisect the issue. Here are some basic instructions on how to bisect this since you already know a good and bad commit.
```
git clone https://github.com/libretro/RetroArch/
cd RetroArch
git bisect start
git bisect bad v1.6.9
git bisect good v1.6.7
```
Now it will give you a commit and you can build it with.
```
./configure && make
```
Now you should test it, if the issue still occurs.
```
git bisect bad
```
If it works.
```
git bisect good
```
If it fails to build you can skip that commit.
```
git bisect skip
```
After this it will give you a new commit and you repeat the process until it tells you what the first bad commit was. Hopefully someone else can offer any corrections for windows users if need be?

**Comment by bparker06** [comment]
Can you paste your retroarch.cfg somewhere we can look at it? Also what is your UI language set to in Windows? Is it in English or ES/PT/something else?

**Comment by orbea** [comment]
Also in between builds you should use `make clean`.

**Comment by t1254362** [comment]
Hi,

I downloaded RetroArch, unzipped and executed it. As I expected it works OK because my Download dir path doesn't have any special char. I removed the folder, extracted again (to avoid some cfg file) and renamed the folder from "RetroArch" to "RetroArchón" and executed again. Now it have the problem, but I noticed more things: it can't create the config and show a error message:

![Broken interface](https://i.imgur.com/NFKZtB2.png)

And the default config is not created.

My windows is in spanish.

**Comment by bparker06** [comment]
Should be fixed in a3a5f6e.

**Comment by t1254362** [comment]
Is there any nightly build that I can test?

And I supsoe that you tested that this problem doesn't happen on other platforms (linux, for example).

**Comment by bparker06** [comment]
Yes you can use those nightlies. And yes the issue only happened on Windows, other platforms assume paths are always utf8 which is what we use internally, so Linux/etc. work fine with special characters.

**Comment by t1254362** [comment]
It's working!

**Comment by t1254362** [comment]
I reported a simmilar problem with "Browser archive" for 7z files: https://github.com/libretro/RetroArch/issues/6026
