### ISSUE TITLE
Issues with analog sticks on dinput joypad driver (Generic Gamepad)

### ISSUE THREAD

**Issue by vpontin** [libretro/RetroArch#5966]
## Description

Hi! I have a Multilaser generic Xbox 360-like gamepad (which uses [USB Network Joystick](https://archive.org/details/USBNetworkJoystickDriver3.70a) as driver) and i tried to use with retroarch in Windows 10 using `dinput` as the Joypad driver.

Althrough i can map the analog axis correct (the menu shows the appropriate axis mapped), in `dinput` mode the Left Analog `left` X-axis operate as the `down`, and both proper `down` Y-axis and `right` X-axis doesnt respond to any command.

Reverting to `xinput` using the same mapping and the axis just work fine (up Y goes up, left X goes left, down Y goes down and right X goes right)

My suspect is something related to how `dinput` interpret the, since `up & down` and `left & right` uses each the same axis, so it couldn't be recognizing as separated directions.

### Steps to reproduce the bug

1. Open a fresh retroarch instance (no cfg present already);
2. Configure the refered generic gamepad using xinput as joypad driver
3. Switch to dinput and the Left Analog will stop working.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: both 1.7.0 and 2017-12-26 `windows` nightly build.

### Environment information

- OS: Windows 10 Home b1709 x64
- Gamepad Driver: https://archive.org/details/USBNetworkJoystickDriver3.70a

**Comment by fr500** [comment]
Well, configure the pad in dinput mode then.
It's a different driver that proccesses inputs differently

**Comment by vpontin** [comment]
I mean i got erros in dinput mode, and in xinput it work fine.
Since its a generic gamepad i will get rumble support on xinput mode?

**Comment by orbea** [comment]
@vpontin As explained, your gamepad will need to be configured for each different input driver. If the config does not already exist in the online updater autoconfig profiles then you will have to create it or configure your gamepad manually.

Given that this is not a bug and the lack of activity I am going to close this issue. If you need any help configuring your gamepad please ask on the forum, discord or on irc.
