### ISSUE TITLE
[Feature Request] [Windows] Add an option to toggle the menu bar, in the menu's

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#5974]
There should be an option to toggle if the menu bar is there on Windows, not so sure about Mac or Linux though.

**Comment by Awakened0** [comment]
You can do this by setting ui_menubar_enable to false in retroarch.cfg. Not sure if that's available to change in the GUI somewhere.

**Comment by hyarsan** [comment]
I haven't seen it in the menus yet.
