### ISSUE TITLE
Controller disconnect while loading game

### ISSUE THREAD

**Issue by dariusc93** [libretro/RetroArch#5977]
While loading a game in retroarch, the controller, or more specifically, SDL2, would disconnect the controller but would not reconnect. Not even unplugging and plugging the usb controller would allow it to be detected and I would have to exit the application and relaunch it for it to see the controller again. At random though, it would allow the controller to be used when loading a game, but only at random and it would work until I disconnect the controller, or until for whatever reason it decides to disconnect then its back to square one. Doesnt matter what core is used. but I tested with snes9x2010 and psx cores.

OS: FreeBSD 11.1-RELEASE-p4. 
Verbose log: https://ghostbin.com/paste/5dftv
Retroarch is built from master.
Gamepad: PS4 controller (but also tried PS3 controller and a generic gamepad and does the same thing). 

EDIT: After a reboot and relaunching retroarch, it appears to work now, but it disconnected from /dev/uhid3 then reconnect to /dev/uhid6 . Verbose https://ghostbin.com/paste/4zkw3 (though its not much useful it seem)

**Comment by dariusc93** [comment]
Going to close this as I am believing it is something else.

**Comment by soredake** [comment]
I have similar problem with linux+sdl2+x11
![Screenshot_20210209_203208](https://user-images.githubusercontent.com/5204968/107410373-e4150480-6b15-11eb-8c71-2ef29c98c3e4.png)
