### ISSUE TITLE
RetroArch reports there is only 1 CPU on 3DS when there is 4(Old) or 6(New)

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#5980]
The New 3DS has 6, 4 usable by RetroArch the Old 3DS has 4, 2 usable.

There is 1 arm7, 1 arm9, 2 arm11 and the new 3DS adds 2 more arm11.

Since we can only use the arm11 CPUs saying 2 or 4 would be acceptable but it seems that we only use 1 arm11 CPU which puts an unnecessary constraint on emulated games.

Summary: RetroArch should be using all the devices arm11 CPUs, its only using 1.

**Comment by bparker06** [comment]
It's just a hardcoded number:

https://github.com/libretro/RetroArch/blob/709c7de40fdcab0d968d454e6aa2c2614bd5799e/libretro-common/features/features_cpu.c#L476-L477

But even if it weren't, what kind of multi-threading (besides tasks like scanning/networking) are you expecting RA to be able to do?

**Comment by meepingsnesroms** [comment]
I am adding networking right now, sound/video/input processing and some emulators support threads(dosbox).

**Comment by meepingsnesroms** [comment]
Fixed
