### ISSUE TITLE
A question about the Nintendo switch port of retroarch

### ISSUE THREAD

**Issue by iOS4all** [libretro/RetroArch#5987]
@twinaphex hi there.
I'm just wondering. can we get JIT on switch in order to enhance retroarch cores like (pcsx, ppsspp , dolphin)?
Also one of the major hackers called Plutoo was found JIT on v4.0.0
![img_0613](https://user-images.githubusercontent.com/24762554/34436983-854f249e-ecab-11e7-89c8-3c3f153afbdb.PNG)

So what else is required to run these cores besides JIT?
The switch is supported vulkan api as well.

Thanks a lot and keep going.

**Comment by hizzlekizzle** [comment]
Dunno. It's too early to say.

**Comment by fr500** [comment]
Please do not treat te issue tracker as twitter or a forum, this is for dev purposes only
