### ISSUE TITLE
[Linux] [flatpak] Keyboard controls aren't working properly

### ISSUE THREAD

**Issue by matpower64** [libretro/RetroArch#5988]
## Description

Keyboard input doesn't work in the interface properly, while certain keys such as arrow keys, enter and ESC are working, pressing any other input key (such as 'X', which is mapped to 'a') seems to be ineffective. This makes the menus impossible to navigate properly, since you can't go back after selecting an option with ENTER. Using a controller and manually mapping it works perfectly.

### Expected behavior

Being able to select an option using a keyboard-mapped key such as 'X' or 'Z'.

### Actual behavior

Unable to select anything using a keyboard-mapped key, basic navigation (enter, arrow keys) works fine, a controller is fully working.

### Steps to reproduce the bug

1. Install flatpak.
2. Install RetroArch from [flathub](https://flathub.org/).
3. Run RetroArch and try to use a "default" key.

### Bisect Results

After a fresh 1.6.9 install (later updated to 1.7.0), input does work fine on a core such as Nestopia UE, so it is likely a issue with RetroArch itself, manually mapping it to a controller also works fine and it seems to receive input on "Input User 1 Bind" when you map it to keyboard again, but it doesn't work inside the RetroArch UI.
Running it with --verbose on flatpak throws normal output even when loading it:
```[matheus@HarpNote ~]$ flatpak run --verbose org.libretro.RetroArch 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening user flatpak installation at path /home/matheus/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/matheus/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Allowing host-fs access
F: Allowing x11 access
F: Allowing wayland access
F: Allowing pulseaudio access```

### Version/Commit

- RetroArch: [1.7.0/0a2b442]

### Environment information

- OS: [Fedora 27]
- Flatpak version: [0.10.2.1]

**Comment by matpower64** [comment]
As an additional note, I also found this bug on Debian 9 + flatpak, using the outdated version from its repository seems to be working, so it might be caused by flatpak or it is a RetroArch regression, I might end up trying to compile RetroArch directly if needed.

**Comment by i30817** [comment]
turn on unified controls on the cfg file (maybe it's on the menu too).

I was also triggered by this a while ago, where they made the menu shortcuts different from in-game shortcuts without a way to reconfigure menu shortcuts (i have some broken keys on the portable). This was done because they didn't want for their 'unified' controls to interfere with text input on the RA menus.

**Comment by i30817** [comment]
Also don't forget to turn on / use 'game_focus' toggle key. It will save you a lot of head-aches if you're going to use a keyboard.

**Comment by matpower64** [comment]
Woah, you are indeed right, toggling unified controls on did the trick, I was going crazy thinking it was some weird bug with it interacting through flatpak since it was working fine on Windows and an old version on Debian.
Thanks for the advice with keyboard mapping, I don't use the keyboard (RetroArch is best suited for a controller after all) that often but it is really nice for some quick 2/3-button controller platforms (NES, Genesis, GBx, etc) when I can't be bothered to get a controller.
