### ISSUE TITLE
Can't load genesis roms from samba share

### ISSUE THREAD

**Issue by t-chab** [libretro/RetroArch#599]
Hi. I've a problem with retroarch, every time I try to load a genesis or snes rom from a samba share on my NAS, it failed with the following error :

```
RetroArch [ERROR] :: ZIP extraction failed at line: 222.
RetroArch [ERROR] :: Didn't find any ROMS that matched valid extensions for libretro implementation.
RetroArch [ERROR] :: ZIP extraction failed at line: 383.
RetroArch [ERROR] :: Failed to extract ROM from zipped file: /media/nas/emu/genesis/Sonic The Hedgehog (W) (REV01) [!].zip.
RetroArch [ERROR] :: rarch_main_init_wrap() failed.
```

It's not a ROM file problem, because if I copy zip file to a local directory, it works well.

I'm using retroarch on ArchLinux x64. retroarch version is aur package retroarch-git available here : https://aur.archlinux.org/packages/retroarch-git/

Is there a workaround for this problem ?

**Comment by oxavelar** [comment]
I cannot get "extract_directory" to work on /tmp. My actual setting is:

```
# If set to a directory, Content which is temporarily extracted
# will be extracted to this directory.
 extraction_directory = "/tmp/"
```

And it does not work with the latest compiled version that I tried from the GitHub repo. I could not find the source of the bug but this was one of the first replies in Google search regarding information of this feature.
