### ISSUE TITLE
A way to solve computer cores text input woes

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#5992]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Several computer cores, and many engines (scummvm for instance) can't have a well defined set of keys to have sensible defaults that don't interfere with Retroarch shortcuts. Therefore, i'd like to propose a default toggle key, that is not any longer widely used in IBM-PC keyboards that would, allow the user to turn on and off RA core keyboard shortcuts (or even all of them).
Candidates are keys like insert, break, pause, scroll lock etc, but the key should still be user configurable.

### Expected behavior
That this shortcut already existed, given how useful it is for text input games to be bearable in RA.

### Actual behavior
Pressing 'f' will defullscreen RA etc...

**Comment by fr500** [comment]
Already implemented, it's called game focus, think it's scroll lock by default.

**Comment by i30817** [comment]
Does it work only on the 'core running' part of RA? I forgot to write that it should only affect shortcuts while not on RA menus.

**Comment by fr500** [comment]
Try it I guess, I unmapped all my hotkeys from the kbd a long time ago

**Comment by i30817** [comment]
Thanks. Seems to work ok. With the controller option to have a open menu combo seems ideal.
