### ISSUE TITLE
On platforms with core updater disabled selecting it while a game is running will resume the game, other core updater issues

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#6004]
"Core Updater" and "Show Core Updater" in "User Interface -> Views" should not even be shown since they do nothing.
RetroArch 3DS 1.7.0 [custom debug build]

I am referring to this option.
#if defined(HAVE_LAKKA) || defined(VITA) || defined(_3DS)
static bool menu_show_core_updater       = false;
#else
static bool menu_show_core_updater       = true;
#endif

Platforms that are statically linked and cant be updated with the updater(3DS, VITA, WIIU, WII, ...) should not show any of these options.

**Comment by orbea** [comment]
@meepingsnesroms What platforms is this still a problem with?

**Comment by meepingsnesroms** [comment]
Seems to be fixed on 3DS, will test Wii later.

**Comment by meepingsnesroms** [comment]
Fixed on 3DS and Wii, safe to assume it is on the others too.
