### ISSUE TITLE
RetroArch needs an emulator only mode

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#6005]
Users have been complaining about this ever since we added media options.

This option would disable:
Favorites
Image
Music
Video

It would also make RetroArch load into "Start Directory" automatically when opening a core or selecting "Load Content"

**Comment by RobLoach** [comment]
Just disable them in the User Interface -> Views?

**Comment by meepingsnesroms** [comment]
![options](https://user-images.githubusercontent.com/1220805/34457838-b7f6a7ce-ed72-11e7-9f55-228536fd108c.png)
You cant, at least in rgui(which me and many others are stuck with).

**Comment by hizzlekizzle** [comment]
I see a few more options than you, but still none to hide those options.
[img]https://i.imgur.com/TftwmCR.png[/img]
However, what about just moving the 'start directory' entry up to the top?

**Comment by meepingsnesroms** [comment]
Thats what I might do, along with fixing the missing switches.

**Comment by meepingsnesroms** [comment]
This is fixed, I removed those entrys completely since they are just a duplicate of the ones in "Collections".
