### ISSUE TITLE
Very long delay in configuration I/O on WiiU

### ISSUE THREAD

**Issue by gblues** [libretro/RetroArch#6013]
## Description
Any time the config file is touched, there's a gigantic delay. Like 15-30 seconds. This delay occurs:

* At intitial startup
* At game load (twice -- once when exiting the GUI and again when loading the core)
* At game unload (using "close content" in quick menu)
* At shutdown time

### Expected behavior

RetroArch should load very quickly. A few seconds at most.

### Actual behavior

There's a significant pause (about 30s) when the config file loads.

### Steps to reproduce the bug

1. Compile retroarch with `PC_DEVELOPMENT_IP_ADDRESS` and `PC_DEVELOPMENT_TCP_PORT` set.
2. Start the net_listen.sh script
3. Start RetroArch and watch the log output, and take note of the signfiicant pause when loading the configuration file.

### Bisect Results

The behavior was added among 4 commits; I can't isolate any further because the commits generate bad builds:

* 5eb6c5d
* 2f422a4
* 7c73930
* 46bffb8

### Version/Commit
see above

- RetroArch: [version/commit]

### Environment information

WiiU is running OS, 5.5.2, using Haxxchi and no other CFW.

**Comment by twinaphex** [comment]
Hi there @gblues,

my first thought is that the baked-in libfat might be making things slower. 

Can you test this theory by editing Makefile.wiiu and removing the line WANT_LIBFAT = 1 ? It should default then to the system-provided libfat that is a part of your wiiu homebrew toolchain.

**Comment by gblues** [comment]
Yep, can do.

I am suspicious that this issue and the deadlock we discussed in #6001 have a common root cause. Therefore I am considering the HID work blocked by this issue until I can prove otherwise.

So, that is to say, I will be shifting my attention to this issue, at least for as long as it takes to confirm my suspicions. :)

**Comment by gblues** [comment]
Removing `WANT_LIBFAT` did not change anything. I tried removing `WANT_IOSUHAX` too, and the delay persists.

**Comment by gblues** [comment]
Reverting `libretro-common/file/config_file.c` back to 6904101c4430b8cd213453fbfb0480838ccc958e and adding a proper function prototype for `config_file_dump` solved the performance issue.

**Comment by twinaphex** [comment]
OK, I reverted the two commits. Let me know if things are fixed now on latest master.

Happy new year BTW.

**Comment by gblues** [comment]
Woot! Happy New Year to you too.

After the revert, both the slow config file read and whatever was causing the HIDRead block are both resolved.

**Comment by twinaphex** [comment]
Awesome, keep me in the loop in case there are any more crashes and/or other severe issues happening to you with the WiiU port. Hopefully things are stable now.
