### ISSUE TITLE
Compilation error - Lakka ARM devices

### ISSUE THREAD

**Issue by ToKe79** [libretro/RetroArch#6016]
## Description
Compilation for ARM devices for Lakka (JEOS for RetroArch) fails with error:
http://dpaste.com/1GCG0FM
This happens for all ARM devices Lakka is build for (RPi, WeTek, Odroid, ...), compilation for x86_64 and i386 is OK.

### Expected behavior
Compiles without error.

### Actual behavior
Compilation fails.

### Bisect Results
Last working compilation for ARM devices was with commit `7e61f08`.

### Version/Commit
Broke with commit [`0389bc6`](https://github.com/libretro/RetroArch/commit/0389bc64fe7d211a7b8d5637a978d688f6d2fd00) / PR #5997.

### Environment information
- OS: Debian 9.3, OpenVZ Kernel 3.16.6-042stab125.5
- Compiler: Lakka toolchain
```
/home/vudiq/src/Lakka/build.Lakka-S905.arm/toolchain/bin/armv8a-libreelec-linux-gnueabi-gcc --version
armv8a-libreelec-linux-gnueabi-gcc-6.2.0 (GCC) 6.2.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I was told to mention @gblues.

**Comment by gblues** [comment]
You will find the swap_if_big16() macro in `libretro-common/include/retro_endianness.h`

When you connect a HID device to a big-endian system, the VID/PID are in Intel byte order and need to be swapped. The goal here is to do the swap at initialize time instead of runtime.
