### ISSUE TITLE
Console ROMs not detected inside MAME zip split files

### ISSUE THREAD

**Issue by zensurette** [libretro/RetroArch#6023]
## Description

Console ROMs are not detected when they are inside MAME (split) zip files. The problem is, probably, that they have non-standard file extensions. For instance, the GameBoy zip file `tetris.zip` contains a single file named `dmg-tra-1.u1`.

Renaming the file to `dmg-tra-1.gb` makes the ROM detectable.

The detection procedure should just check the checksum of the files against the known ROM databases. PR #5663 may help/be related.

## Steps to reproduce the bug

1. Copy the compressed ROM `tetris.zip` (containing the file `dmg-tra-1.u1`) from a MAME ROM split archive to `~/roms/gb`.
2. Scan for roms.

## Expected behavior

* The ROM is detected and "Tetris (World) (Rev A)" should appear in the list of available Game Boy games.

## Actual behavior

* The ROM is not detected and no Tetris game appears in the list of available GB games.

### Version/Commit

- RetroArch: 1.6.9 (inside Lakka 2.1)

**Comment by retro-wertz** [comment]
ont think mame softlists are supported for playlist import since we have
separate cores for those anyways.you can still play them though manually(as
soon as you figure out how to setup each though).

**Comment by fr500** [comment]
The roms don't have extensions, we detect the types via the extension.
I'm inclined to say... won't fix

**Comment by zensurette** [comment]
Is checking every really that problematic? What is scanned is a directory called `roms`. With high chances what you are going to find are ROMs :)

From the UX point of view it would be a great thing if MESS/MAME ROMs were recognized without any user intervention. Just drop them in a directory and press scan. MESS/MAME ROMs collections are widely available and often of high quality.

What is the point in the code where extensions (inside a zip file) are checked?

One last point: all GB roms in https://github.com/mamedev/mame/blob/master/hash/gameboy.xml have either extesion `u1` or `bin`. Could you add these two extensions to the accepted ones?

**Comment by i30817** [comment]
Well size is already a 'good' filter. And a way control if extension matters or not in a manual scan would be better (on the scan menu).

You should ask for that instead, a toggle/knob on the main scanner page for 'extension matters' if you want to support the mame dumps on other cores.

**Comment by orbea** [comment]
> The roms don't have extensions, we detect the types via the extension.
I'm inclined to say... won't fix

I suppose we could try to determine what the file is automagically like `file(1)`, but that would require a lot of time, effort and debugging. Not to mention it could be noticeably slower.  So unless someone really wants to implement that I am inclined to agree that this is a won't fix.

The far more practical solution is to either just rename the files or if the unknown extension is prevalent enough than add it to the list. So I am going to close this issue unless someone really wants to put forth the effort.
