### ISSUE TITLE
"Browse Archive" with 7z files in a path with special characters is broken on Windows 10

### ISSUE THREAD

**Issue by t1254362** [libretro/RetroArch#6026]
## Description
When I have a 7z file in a path with special characters (D:/Emulación) and i click "Browse Archive" it say "No items", but if I move this file to a non-special character path, it works fine (D:/).

The problem does not happen with .zip files.

I reported a config-reading related problem some days ago, and it was resolved: https://github.com/libretro/RetroArch/issues/5959

### Expected behavior
WHen I open D:/Emulación/test.7zp with "Browse Archive" it should show the files in the 7z.

### Actual behavior
It says "No items."

### Steps to reproduce the bug
Put a .7z in a path with special characters: D:/Emulación/test.7z or directly D:/tést.7z and it will say "No items", move the file to another path (D:/test.7z) and it will work.

### Version/Commit
1.7: 80f946e0a / Jan 1 2018

### Environment information
- Windows 10

**Comment by bparker06** [comment]
Fixed in 54e7ec8e79.

**Comment by t1254362** [comment]
I confirm that is working (2nd verification, I supose that you tested before)
