### ISSUE TITLE
Stuck on flower screen, maybe libGL problems

### ISSUE THREAD

**Issue by retroalfred** [libretro/RetroArch#6035]
Hi,
I am trying to run Lakka-Generic.x86_64-2.1 in live mode on a PC media player (cisco IEC 4610 intel based).
My problem is that it hangs on the flower screen.
I read the forum and tried also changing the following parameter without success:
menu_shader_pipeline = "0"
menu_driver = "rgui"

In attach you can find my logs
Thank you in advanced
Regards
Al
[log-audio.txt](https://github.com/libretro/RetroArch/files/1600937/log-audio.txt)
[log-dmesg.txt](https://github.com/libretro/RetroArch/files/1600938/log-dmesg.txt)
[log-lusb.txt](https://github.com/libretro/RetroArch/files/1600939/log-lusb.txt)
[log-retroarch.txt](https://github.com/libretro/RetroArch/files/1600940/log-retroarch.txt)
[log-vga.txt](https://github.com/libretro/RetroArch/files/1600941/log-vga.txt)

**Comment by ofry** [comment]
Create issue there:

https://github.com/libretro/Lakka-LibreELEC/issues
