### ISSUE TITLE
[Enhancement] RETROPAD's mapping to saturn and sega genesis controllers.

### ISSUE THREAD

**Issue by ZacharyFoxx** [libretro/RetroArch#6041]
The current retropad's mapping to Saturn or Sega 6 buttons controllers is a bit annoying because we have the L and R buttons assigned to X and Z buttons. 
If you try to play a SNES, PS1, NEOGEO or CAPCOM game you need to change the layout.

For example: Any street fighter game, If you play with SNES os PSOne controller, even the arcade versions, we have this: 

-------------------------------
| Y/SQR |   X/TRIANGLE |  L/L1|
-------------------------------
|   LP     |  MP                | SP   |
-------------------------------
-------------------------------
| B/X     |   A/CIRCLE     |  R/R1|
-------------------------------
|LK       |  MK                | SK   |
-------------------------------

LEGEND:
L = Light
M = Medium
S = Strong
P = Punch
K = Kick

But if using SATURN or SEGA GENESIS 6 buttons, we have this:

----------------
| X    |  Y    |   Z|
----------------
|SP   | MP  | SK|
----------------
----------------
| A   |  B    |   C|
----------------
|LP  | LK   | MK|
----------------

This layout is completing strange and the player needs to change the layout of the system.

But, Changin the retropad's mapping of saturn and sega controllers to:

----------------
| X    |   Y   |  Z  |
----------------
| Y   |    X   |  L  |
----------------
----------------
| A  |    B   |  C  |
----------------
| B  |    A   |  R  |
----------------

It will avoid that the player needs to change the buttons's layout.

**Comment by hizzlekizzle** [comment]
You mean physical Saturn pads? If so, you can put in a PR at the [retroarch-joypad-autoconfig](https://github.com/libretro/retroarch-joypad-autoconfig) repo to change those mappings. Will that make it weird for 3-button Sega Genesis pads?

**Comment by t1254362** [comment]
He is saying that the general mapping should to be changed.

But I don't think so. When I saw RetroPad (that is likely a typical layout from SNES, or more simmilar, to a DualShock from PSX), buttons are configured with the obvious spatial distribucion:

![RetroPad](https://wiki.libretro.com/images/6/68/Retropad_360pad.png)

![Genesis Pad](https://segaretro.org/images/3/30/Pad_MD_Gen3.jpg)

For me here is obvious that Genesis/MegaDrive A B C should be mapped to RetroPad Y B A
We now have one button left in the 4 principal from RetroPad (X) so is obvious use L1 (for Sega X) and R1 (for Sega Z), and finally we can use this left button (retropad X) to the last button from Sega pad (Y), but we can disccus that Sega Y can be better in L2 or R2, but for me, use RetroPad X is not bad.

**Comment by ZacharyFoxx** [comment]
t1254362, I can see what you think but it is wrong because you are considering only the sega genesis 3 buttons controller.

Look this pictures:

![233796_detail_01](https://user-images.githubusercontent.com/23250218/34590839-822d5700-f1a0-11e7-9fdb-5c5d48a3e24f.png)

![hori-fighting-commander-for-xbox-one--66044128 zoom](https://user-images.githubusercontent.com/23250218/34590849-8cb9708c-f1a0-11e7-809b-8ae66ab6fdc6.jpg)

![pa 24131 002](https://user-images.githubusercontent.com/23250218/34590853-93d72ada-f1a0-11e7-9823-41a4b71132d4.jpg)

In both, they just put the shoulder buttons in line.

When the SEGA created the 6 button controller to Street Fighter games, the simple and best way was just adding another queue of buttons (XYZ), making the layout very similar to the arcades.

But the proof that the current layout is strange is just try to play SF2Plus or SSF2 of genesis using a SNES or PS2 controller. You will have this:

Y = LK
B = MK
A = SK
L = LP
X = MP
R = SP

Now, compare with the original layout of Street Fighter in SNES:

![81338-super-street-fighter-ii-snes-screenshot-options](https://user-images.githubusercontent.com/23250218/34591172-d08c3f72-f1a2-11e7-97d5-03e9716fb0a5.png)

Can you see?

And changing the layout of retropad to Sega Saturn and Sega Genesis 6 buttons controller will be a enhancement to the owners of SNES and PS1 controllers too. Currently we have:

Y=A
B=B
A=C

Naturally we can do the combo A+B and B+C, but it is uncomfortable to do A+C. You are forcing the players to assign the combo to another button like X, L or R.

With the layout below:

B=A
A=B
R=C

Naturally we can do the combo A+B, B+C AND A+C without any kind of extra configuration..

**Comment by fr500** [comment]
This doesn't belong here anyway.
The internal wiring is up to any of the cores, no matter how much you change RetroArch it will forward retropad buttons to the core.

If you want to propose alternate layouts for some gamepads on some cores those belong in the respective core repos.

Also, the remapping menu allows you to change this already, as long as your gamepad autoconf has the labels there should be no confusion while remapping.

We cater to the majority with the RetroPad layout, if we start moving stuff over at this point of time we'll end up with more problems than solutions.

Edit:

Here's what I'm talking about:

![image](https://user-images.githubusercontent.com/1721040/34592950-af099528-f195-11e7-92d5-1b60f83b22b1.png)

My DS3 autoconf has proper labels, so everything from column A corresponds exactly to column B.
Of course it won't happen with these 6 button pads but if the labels are correct you have to remap exactly once for the core and call it a day.

**Comment by ZacharyFoxx** [comment]
Hi fr500, sorry but what you say do not make sense, because the problem is not in a core but in the layout of retropad virtual mapping.

If is the retropad who define which ABC-XYZ buttons of Sega Saturn and Sega Genesis 6 buttons will be assign to YBA-LXR buttons in all controllers, how could the problem be in the cores? And even if I do what you said, the problem will persist: Changing the mapping in FBA, SNES or other cores to
a best fit to sega saturn/sega genesis controllers will break the mapping to SNES/PS1/XBOX style controllers, unless which the change be done on the retropad' s layout.

Like I said: Try to play a SF game of genesis or any sega saturn game and you will see: You need to change the buttons layout of your DS3.

The question is not propose alternate layouts for some gamepads on some cores, but a better layout to two types of gamepads, just this.

Ok to the Sega Genesis 3 buttons controller, the current layout is perfect but about Sega Saturn and Sega Genesis 6 buttons controller is not.

You said "We cater to the majority with the RetroPad layout" but changing the layout, just to sega saturn and sega genesis 6 buttons controller, will not break anything. You will make the user's experience more friendly.

Is it so difficult to see this, even after showing pictures of real controllers?

**Comment by retro-wertz** [comment]
retropad layout is based on snes' layout + analog stick and button layout
of playstation. depending if your controller has autoconfig, the correct
labels should show for your gamepad.

its up to the core how to assigned these as only the cores know if its
designed for use in 6-button layout, 2button or no button...

**Comment by orbea** [comment]
As already explained its up to the core to set the mappings and these can then be reconfigured to each users liking. If anyone doesn't find this satisfactory please recreate the issue for the specific core issue tracker, thanks!
