### ISSUE TITLE
Some cores can't load content from paths with special characters in current versions on Windows 10

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#6051]
## Description
In latest versions of RetroArch and libretro cores, some cores (seems that the cores that doesn't use libretro filestream https://github.com/libretro/fbalpha2012_neogeo/issues/18#issuecomment-355388760) can't load content from path with special chars (for example D:/Emulación).

They say "Failed to load content".

I saw this behavior on:
- PicoDrive
- blueMSX
- FB Alpha 2012 Neo-Geo (note: FB-Alpha core works fine)

In the case of FB Alpha 2012 Neo-Geo I tested to upzip my 1.6.7 and load a rom, it worked. But then, I updated the core (online updater -> core updater -> FB Alpha 2012 Neo-Geo), and at this moment the core can't load the rom in the path (I need to move the rom to other path).

I tested to take the old core and copy it on RetroArch 1.7, but it say "Failed to load content" too. 

In previous versions of RetroArch, and with cores downloaded months ago, they work fine. Some core seem that was not updated (looking the github) so (to me) seems that something in RetroArch changed (and some cores need to be adapted). And I suppose that call fopen(), independent from RetroArch, will be the same in 1.6.7 that in 1.7, but in my copy they work and if I update the core (or update retroarch and use the old core) they stop working.

### Expected behavior
That cores can load content from path with special chars: D:/Emulación/...
Like in my 1.6.7 backup.

### Actual behavior
When I have a rom in some cores in D:/Emulación/...
![Error](https://i.imgur.com/6v3l1je.png)

### Steps to reproduce the bug
1. Enter in Load Conent
2. Search for content in some of the cores that I said, for example one for blueMSX, but the rom need to be in a path with special characters: D:/Emulación/theMSXrom.zip (for example)
3. Click on Load Archive
4. Select the core to check, in this example, blueMSX
5. It will load the core but fail to load the content.

### Version/Commit
I have one situation where it works fine:
A backup of 1.6.7 with cores from the day that I did this backup. My cores has date 16/12/2017, but i'm not sure if this is the last time that I updated the cores.

I tested to update in this backuped installation the FB Alpha 2012 Neo-Geo and it stop working (Failed to load content).

I tested this backuped core of FB Alpha 2012 Neo-Geo to an actual 1.7.0 and it doesn't work (Failed to load content).

An actual system (nightly RetroArch, nightly core) doesn't work too (Failed to load content)

### Environment information
- OS: Windows 10

**Comment by bparker06** [comment]
Yes, on Windows, cores that do not use our filestream interface likely will not support Unicode paths properly. This is a separate issue that would need addressing within each core, but RetroArch does support Unicode paths now.

**Comment by orbea** [comment]
As explained in the previous comment if this is broken anywhere please file an issue in the specific core issue, thanks!
