### ISSUE TITLE
Segmentation fault on Debian 9 with Nvidia Vulkan driver

### ISSUE THREAD

**Issue by Sunderland93** [libretro/RetroArch#6062]
## Description

After select Vulkan video driver in RetroArch settings, it doesn't started. Running in terminal give a segmentation fault error

### Expected behavior

RetroArch should started and working.

### Actual behavior

RetroArch failed to start

### Steps to reproduce the bug

1. Select Vulkan video driver in RetroArch settings
2. Close RetroArch and try to run it again

### Version/Commit
- RetroArch: [1.7.0]

### Environment information

- OS: Debian 9, KDE Plasma 5.8.6, kernel 4.9.65-3+deb9u1, Nvidia 384.98

**Comment by Sunderland93** [comment]
@orbea sorry, I don't have Nvidia hardware anymore, unfortunately

**Comment by orbea** [comment]
No worries, given the lack of activity for nearly a year and that no one else has confirmed your issue I think its best to close this. Of course if anyone can reproduce this again in the future please say so or make a new issue.
