### ISSUE TITLE
Support for choosing a different relay server (netplay)

### ISSUE THREAD

**Issue by furiadeoso** [libretro/RetroArch#6068]
Here in Europe it is almost impossible for some people to use netplay due to the constraints or difficulties of internet providers. Using the actual Relay server (New York) is not a good solution for most of us because of the distance it is located.

First step, as @bparker06 have said in Discord channels, would be support in RA for choosing a different relay server.

After that, I could contribute trying to involve a hosting company commited to the retro scene. I think they could help RA project with a VPS to be the first node for all europe netplay users.

**Comment by fr500** [comment]
+1

**Comment by bparker06** [comment]
For reference this was merged in #6225.
