### ISSUE TITLE
GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT on Raspberry Pi

### ISSUE THREAD

**Issue by deltabeard** [libretro/RetroArch#6078]
## Description

"Failed to create HW render FBO #0, error: 0x36054." error when loading libretro-mpv and possibly other cores.

### Actual behavior

[out.txt](https://github.com/libretro/RetroArch/files/1616930/out.txt)

### Steps to reproduce the bug

Attempting to start libretro-mpv on the Raspberry PI causes this issue. Instructions [here](https://github.com/libretro/libretro-mpv#compiling).

### Bisect Results

I cannot get 1.6.9 working for other unrelated reasons, so bisecting is difficult.

### Version/Commit

- RetroArch: 1.7.0

### Environment information

- OS: Linux 4.9
- Compiler: gcc uclibc-ng

Additionally, the error code is not in hexadecimal despite the "0x" in the printf [here](https://github.com/libretro/RetroArch/blob/709c7de40fdcab0d968d454e6aa2c2614bd5799e/gfx/drivers_renderchain/gl2_renderchain.c#L1041).

**Comment by orbea** [comment]
Can you test other cores? I think this could be specific to mpv/mpv-libretro.

**Comment by deltabeard** [comment]
I've tested [gambatte](https://github.com/libretro/RetroArch/files/1619718/tetris.txt), [genesis-gx](https://github.com/libretro/RetroArch/files/1619719/sonic.txt) and snes9x (no log). None of these cores have this issue. However, I still do believe the issue is not with mpv-libretro.

The error code is provided by Retroarch, and none of the mpv specific code in mpv-libretro seems to be executed.

I also tried using the `dispmanx` video driver (as opposed to `gl` used above) but that just displays a blue gradient and does nothing else. [mpv_dispmanx.txt](https://github.com/libretro/RetroArch/files/1619717/mpv_dispmanx.txt)

Other logs when using `gl` video driver:
[mpv.txt](https://github.com/libretro/RetroArch/files/1619720/mpv.txt)
[retro.txt](https://github.com/libretro/RetroArch/files/1619721/retro.txt)

These issues occur with both uclibc-ng and glibc toolchains. The build with uclibc-ng toolchain required the `mmal` library to be linked to retroarch to stop `mmal_log_category` linking errors on runtime.

**Comment by deltabeard** [comment]
Apparently this is an ongoing issue with Retroarch running GL cores.

**Comment by orbea** [comment]
What other GL cores are affected by this? I should of said to try GL cores too. Cores that you could try are mupen64plus, parallel-n64 and beetle-psx-hw. I don't have a raspi so I'm not sure how well they do or do not work...

**Comment by deltabeard** [comment]
According to @twinaphex all GL cores are affected.

**Comment by deltabeard** [comment]
[git bisect results](https://github.com/libretro/RetroArch/files/1629870/git-bisect-view-ra.txt)

**Comment by twinaphex** [comment]
Hi @deltabeard , on an unrelated note, I had no idea you were demoted, seems like this was done to a few members, some kind of switch was made where a new category called 'Members' was created and instead of Contributor you were moved to that. Anyway, still trying to figure out what happened but regardless - I moved you back to 'Contributor', so all is well again. I don't think the move was done out of malice or whatever by whomever did this, but it was perhaps not really well thought out and risked upsetting people for no real reason.

**Comment by deltabeard** [comment]
No worries. :)

**Comment by deltabeard** [comment]
Tested not working with [testgl_libretro](https://github.com/libretro/libretro-samples/tree/master/video/opengl/libretro_test_gl_shaders), so it isn't just libretro-mpv.

**Comment by deltabeard** [comment]
The testgl_libretro core did however show the issue on 1.6.3, whereas libretro-mpv did not have that same issue. So I'm going to do a git-bisect once more.

**Comment by deltabeard** [comment]
Parallel-n64 doesn't work either. Exits with the same message. Tested on git master.

**Comment by deltabeard** [comment]
The issue has to be in gl2_renderchain_init_hw_render(). I'm going to try downgrading rpi-userland first before trying out some OpenGL stuff.

**Comment by deltabeard** [comment]
The issue is between commit da233c89c9a6a3f9ea016fbb05bfcc7987a8fe80 and 241df59771d5b9d1048162b15c7c53fdd38a48f8. The git-bisect continues, albeit very slowly as each revision requires patches to be backported to fix compile errors.

**Comment by deltabeard** [comment]
git bisect completed. 48c3a509320031a91a7de1bec2a358f972b9e33d breaks OpenGL ES 2.

**Comment by deltabeard** [comment]
Fixed fb257eb21e2cb0393e2d0f68402d8070b06fa8c7
