### ISSUE TITLE
Segmentation fault when using Vulkan and KMS with AMD OSS drivers.

### ISSUE THREAD

**Issue by Vaporeon** [libretro/RetroArch#6085]
## Description

RetroArch segfaults on startup when running with KMS and the Vulkan driver.

### Expected behavior

RetroArch to start normally

### Actual behavior

Segmentation fault
backtrace: https://cdn.discordapp.com/attachments/399635803443036160/401200500948729876/backtrace.log

### Steps to reproduce the bug

Compile with Vulkan and KMS enabled and then try to run it.

### Version/Commit
7cbe4ba9a8

### Environment information

- OS: Arch Linux x86_64, GPU is a AMD RX 580 using amdgpu and radv.
- Compiler:GCC 7.2.1

**Comment by orbea** [comment]
Possibly a related issue. https://github.com/libretro/RetroArch/issues/5040
