### ISSUE TITLE
Add input_libretro_device and input_analog_dpad_mode to autoconf

### ISSUE THREAD

**Issue by gizmo98** [libretro/RetroArch#609]
Is it possible to add these settings to a autoconf file? Seems to be only buttons and axis will be recognized.

**Comment by michaelkleinhenz** [comment]
Same issue here. Adding input_player1_analog_dpad_mode="1" disables the dpad on an snes controller. Please reopen this issue.

**Comment by fr500** [comment]
why would you use dpad analog mode on a controller with NO ANALOGS?

**Comment by duckspunches** [comment]
Having exactly the same issue with a wired Xbox controller, the same SNES USB adapter and controller and a NES USB adapter and controller. input_player1_analog_dpad_mode="1" disables the dpad on both the SNES and NES controllers, it would be great to be able to control this (and also hotkeys) at the autoconfig level.

**Comment by michaelkleinhenz** [comment]
@fr500 because I want to hotplug XBox- and other controllers (that's what the whole autoconfig feature is about). But because this bug, I can either have analog mapped to dpad on XBox controllers OR can use snes controllers - not both.
I think those stuff should be moved to autoconfig.

**Comment by michaelkleinhenz** [comment]
@duckspunches hotkeys can be configured in autoconfig. At least I was able to configure exit_emulator to different key combinations on XBox and snes controller:

snes controller (iBuffalo snes style USB controller):
input_enable_hotkey_btn = "6"
input_exit_emulator_btn = "7"
input_menu_toggle_btn = "2"

XBox controller:
input_enable_hotkey_btn = "8"
input_exit_emulator_btn = "9"
input_menu_toggle_btn = "10"

(code 10 is the silver XBox home button, so pressing "back" and the Xbox button opens the retroarch menu).

**Comment by fr500** [comment]
If we add that to the hotkey files then cores that use both the analog AND
the dpad will have problems later on.
I think this is too specific to a particular use case

On Sun, Jun 14, 2015 at 8:36 AM, Michael Kleinhenz <notifications@github.com

**Comment by michaelkleinhenz** [comment]
What about adding a hotkey for enabling/disabling the analog mapping? Something like:

input_enable_hotkey_btn = "x"
input_toggle_analog_dpad_mode_btn = "y"

Pressing x and y should then toggle the behaviour...

**Comment by fr500** [comment]
not really possible since hotkeys are only there for P1

**Comment by duckspunches** [comment]
If it can't be moved to autoconfig then it'd be great if the issue #1780  of analog_dpad_mode disabling dpads could be looked at because I imagine there are more users wanting to use both Xbox and SNES/NES USB adapters without making things core specific or changing settings each time.
