### ISSUE TITLE
[WiiU] Retroarch Launcher Crash on latest build

### ISSUE THREAD

**Issue by Cruplezone** [libretro/RetroArch#6091]
## Description

Used the online updater to update my cores this morning, on retroarch re-launch presented with the following error: 
![image](https://user-images.githubusercontent.com/17866415/34886396-dfa19a72-f790-11e7-988f-31ade205c48f.png)

### Steps to reproduce the bug

1. Use the retroarch menu launcher, then use online updater to update to latest core
2. Relaunch retroarch
3. Black screen

### Environment information

- OS: WiiU 5.5.2 - Haxchi FW

**Comment by gblues** [comment]
Oh good, this wasn't just me. ;) The latest code does not have this problem. So if the current nightlies (as of 10AM PDT 1/13/2018) are still broke, then the next nightly build should do the trick.

Assuming it doesn't get re-broken between now and then. ;)

**Comment by mastermanson** [comment]
here i got the same problem on 1.7.0 and with 1.7.1

**Comment by cucholix** [comment]
It's working fine on my end 
![img_20180131_122932460](https://user-images.githubusercontent.com/16081693/35631432-a64f86fc-0682-11e8-8e91-93500d86115e.jpg)

**Comment by Cruplezone** [comment]
The issue has long been resolved.
