### ISSUE TITLE
No line "video_monitor_index"on retroarch.cfg

### ISSUE THREAD

**Issue by Alexandre-PAYET** [libretro/RetroArch#6095]
Hi, I would want to install Lakka on an old PC for my friend.
The pc has an intel celeron 2,8 Ghz, 512 Mo DDR2, and only the graphic card is new into. It's a Gt710 by Nvidia.
So I download Lakka and make it on a USB key.

First boot for install, I did'nt press TAB, and black screen, i didn't see nothing...
So I Try to use the boot prompt with : "installer live nomodeset", and the installer works fine. 
I Unpluged the usb and restart on HDD. And black screen...

On IRC, I've requested help, and I try to get the log : 

`[INFO] RetroArch 1.6.9 (Git c056726)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3
Built: Nov 21 2017
[INFO] Version: 1.6.9
[INFO] Git: c056726
[INFO] =================================================
[INFO] [Config]: Loading default config.
[INFO] [Config]: loading config from: (null).
[INFO] Looking for config in: "/storage/.config/retroarch/retroarch.cfg".
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/storage/savefiles/.srm".
[INFO] Redirecting savestate to "/storage/savestates/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] Found shader "/tmp/shaders/slang-conversion-template.glsl"
[INFO] Found shader "/tmp/shaders/stock.glsl"
[INFO] [Video]: Video @ fullscreen
[INFO] [Video]: Starting threaded video driver ...
[INFO] [DRM]: Found 3 connectors.
[INFO] [DRM]: Connector 0 connected: no
[INFO] [DRM]: Connector 0 has 0 modes.
[INFO] [DRM]: Connector 1 connected: no
[INFO] [DRM]: Connector 1 has 0 modes.
[INFO] [DRM]: Connector 2 connected: yes
[INFO] [DRM]: Connector 2 has 10 modes.
[INFO] [DRM]: Connector 2 assigned to monitor index: #1.
[INFO] [DRM]: Mode 0: (1280x1024) 1280 x 1024, 60 Hz
[INFO] [DRM]: Mode 1: (1280x1024) 1280 x 1024, 75 Hz
[INFO] [DRM]: Mode 2: (1024x768) 1024 x 768, 75 Hz
[INFO] [DRM]: Mode 3: (1024x768) 1024 x 768, 70 Hz
[INFO] [DRM]: Mode 4: (1024x768) 1024 x 768, 60 Hz
[INFO] [DRM]: Mode 5: (800x600) 800 x 600, 75 Hz
[INFO] [DRM]: Mode 6: (800x600) 800 x 600, 60 Hz
[INFO] [DRM]: Mode 7: (640x480) 640 x 480, 75 Hz
[INFO] [DRM]: Mode 8: (640x480) 640 x 480, 60 Hz
[INFO] [DRM]: Mode 9: (720x400) 720 x 400, 70 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1280x1024.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0xb4631c58.
[INFO] [KMS]: New FB: 1280x1024 (stride: 5120).`

and for my graphics log : 
`lspci -nnk | grep -A  2 VGA
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GK208 [GeForce GT 710B] [10de:128b] (rev a1)
    Subsystem: Micro-Star International Co., Ltd. [MSI] GK208 [GeForce GT 710B] [1462:8c93]
    Kernel driver in use: nouveau`

And after some help in the irc : I was shearch the video_monitor_index for set to "1" but the line doesn't exist ??
I tried to add it but my screen show me now "no signal". 

So I'm on the starting point.

**Comment by gouchi** [comment]
Why do you need `nomodeset` ? Because it will disable kms and we are using drm/kms with Lakka for generic platform. Try to boot with `live ssh`

**Comment by orbea** [comment]
It seems this was fixed as my `retroarch.cfg` has.
```
video_monitor_index = "0"
```
So I am going to close this, but please let us know if you have any further issues!
