### ISSUE TITLE
Add to Favorites game list broken

### ISSUE THREAD

**Issue by lanciaux** [libretro/RetroArch#6098]
## Description

When selecting a game in any playlist generated by scan directory/file and choosing to make it favorite :

1. nothing appears in list
2. Those that could accidentally appear cannot be removed from favorite list

**Comment by RobLoach** [comment]
Need to play the game first, and then add to favorites afterwards. Bug. Related issue and discussion over at https://github.com/libretro/RetroArch/issues/5807 .

**Comment by lanciaux** [comment]
Apologies I didn't found this other entry before.  I can close so.
