### ISSUE TITLE
[Feature request] Allow hiding default playlists on Android

### ISSUE THREAD

**Issue by ClockworkTomato** [libretro/RetroArch#6101]
In the latest stable Android release of Retroarch the playlist menu looks like this:

![screenshot_20180114-151353](https://user-images.githubusercontent.com/24359833/34918356-abafa0f2-f951-11e7-8ad4-5759fa0e2722.png)

As you can see, most of the space is occupied by the "Favorites", "Music", "Images", and "Scan" playlists; currently there's no way to remove these from the Android GUI (whereas they can be hidden from the XMB).

Would it be possible to add a setting to do so?

**Comment by Ferk** [comment]
Maybe it would be good if also at least the Scan options were at the bottom of the list instead of at the very top. You won't be using those options that much after you have already built your more-or-less definitive playlists.

**Comment by meepingsnesroms** [comment]
This is already fixed, use the latest nightly and go to settings -> user interface -> views and you can disable all non rom media options as well as favorites, you cant remove the add content though because that could break things.
