### ISSUE TITLE
Linking fails when Pulse is enabled under Solaris 11

### ISSUE THREAD

**Issue by kwyxz** [libretro/RetroArch#6111]
## Description

Building RetroArch under Solaris 11 fails at linking when `HAVE_PULSE` is not set to "no" or `--disable-pulse` is not used when invoking `configure`. 

### Expected behavior

Linking should succeed

### Actual behavior

```
LD retroarch
Undefined			first referenced
 symbol  			    in file
MIN                                 obj-unix/audio/drivers/pulse.o
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
gmake: *** [retroarch] Error 1
```

### Steps to reproduce the bug

Assuming you're running Solaris 11:
1. comment `HAVE_PULSE` in `qb/config.libs.sh` on line 47
2. run `./configure`
3. run `gmake`

### Version/Commit

Issue still present in RetroArch: 27caf46616a01b954618a3fc99b9ab1bd3e72bb1
Probably has been there for a long time but nobody tried building under Solaris :D

### Environment information

- OS: Solaris 11
- Compiler: gcc 4.8.2

### Attached files

[config.log](https://github.com/libretro/RetroArch/files/1630374/config.log)

[config.h.txt](https://github.com/libretro/RetroArch/files/1630375/config.h.txt)

[config.mk.txt](https://github.com/libretro/RetroArch/files/1630376/config.mk.txt)

**Comment by orbea** [comment]
Thanks for the logs. What I take from them is that pkg-config is correctly detecting libpulse.pc and that this does not seem to be an issue with the configure script. The main difference I see with my linux install here is the addition of `-pthread` in `$PYTHON_LIBS`. I'd guess that is probably not the issue?

That said I do not see why `MIN` would be undefined...

**Comment by orbea** [comment]
Maybe this is a difference between pulseaudio on linux and solaris?

**Comment by kwyxz** [comment]
It's very possible. I am still planning on investigating this sometime in the near future, even though as I said in the original PR my C is a bit rusty, but I'll try my best.

**Comment by orbea** [comment]
One guess is that #include `libretro-common/include/retro_math.h` is never included. This is not really a solution, but can you try putting `#include <retro_math.h>` somewhere at the top of `audio/drivers/pulse.c`?

**Comment by bparker06** [comment]
Why is that not a solution?

**Comment by twinaphex** [comment]
I added #include <retro_miscellaneous.h> to the file, which has MIN/MAX macros.

**Comment by kwyxz** [comment]
The latest commit by @twinaphex fixes the issue. Thank you all!

**Comment by orbea** [comment]
I made a PR to enable pulse audio detection for SunOS again, I assume this is okay now? :)

**Comment by kwyxz** [comment]
Sure thing
