### ISSUE TITLE
Vulkan support for raspberry pi3 + retroarch? please add it!

### ISSUE THREAD

**Issue by edneyhelene** [libretro/RetroArch#6122]
Im looking foward to see vulkan implemented on libretro retroarch for raspberry pi3 and similars!

im sure that all emus will run faster and better with vulkan instead of GL

Can you guys please implement it? its a must.  thank you

**Comment by hizzlekizzle** [comment]
RPi's GPU doesn't support Vulkan.

We shouldn't have to do anything to make Vulkan work on any given devboard if said devboard's GPU/drivers support it.
