### ISSUE TITLE
Windows XP SP3 32-bit, RetroArch and 'The Parameter Is Incorrect'

### ISSUE THREAD

**Issue by ScarletWavez** [libretro/RetroArch#6123]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Windows XP SP3 32-bit seemingly throws an error when loading RetroArch with 'The parameter is incorrect' and cannot continue. This is a critical error.
### Expected behavior

I expected it to launch and create the default configuration files.

### Actual behavior

What is explained above, basically.

### Steps to reproduce the bug

1. Download XP stable buiild of RA 1.7.0 from the website
2. Install as usual, DX stuff is already installed on my machine in this case before install
3. Launch RA and get the error

### Bisect Results

According to my research this has been happening since 1.2.x and hasn't been fixed since.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0 stable MSVC2010

### Environment information

- OS: Windows XP SP3 32-bit
- Compiler: I'm using the installer

### Other info

I'm going to try the Win98SE/2K/ME version and report back how it goes.

**Comment by ScarletWavez** [comment]
Tried the 98SE/2K/ME version, even with compatibility modes on it results in the 'retroarch.exe has encountered a problem' issue.

**Comment by ScarletWavez** [comment]
It appears there is a missing retroarch.exe.manifest and said manifest for later versions aren't floating anywhere on the internet, only some ancient version...

**Comment by bparker06** [comment]
Hi @ScarletWavez,

The msvc2010 version should work fine on XP as long as you have the manifest... unfortunately I haven't been able to figure out why it's not being included in the releases, but here it is:

http://bot.libretro.com/.bp/retroarch.exe.manifest

Please let me know if you have any more problems.

**Comment by ScarletWavez** [comment]
I am getting error in -v mode:

'GLSL shaders are not supported by your OpenGL driver'

I am using Intel GMA 945

**Comment by bparker06** [comment]
Intel 945 is indeed quite old and only supports OpenGL 1.5, while shaders were added in 2.0. You would need to change your video driver to something else, like `gdi` or perhaps `d3d`. In your `retroarch.cfg` the variable is named `video_driver`... if it's not there you can create it.

**Comment by twinaphex** [comment]
If we can ever get our GL1 renderchain to work, that would be a possible
solution. Unfortunately, the only people on such old hardware happen to not
be developers themselves, so it's hard to test.

**Comment by ScarletWavez** [comment]
@bparker06 GDI works, I managed to get to the menus. D3D resulted in a glitchy mess. Thanks for solving the issue I had! ~Swavez

**Comment by hippie68** [comment]
I have the same problem right now. Windows XP SP3 x64, current RetroArch XP release just downloaded. The manifest file linked here so far does not change the error message. "The parameter is incorrect."
So, the official XP version of RetroArch doesn't run under XP as of May 24, 2020.

**Comment by hippie68** [comment]
@bparker06 the manifest file doesn't work for the current RetroArch version

**Comment by cetinajero** [comment]
The link for `retroarch.exe.manifest` isn't working anymore (http://bot.libretro.com/.bp/retroarch.exe.manifest).

I found it in another location and upload it to: https://gist.github.com/cetinajero/98f22d646698cd1ef74e896d8f7f7a9c

**Comment by ncflagg** [comment]
In case anyone else lands here searching for a _itoa_s error, the MSVC2010 build (RetroArch-msvc2010-x86-setup.exe as of today) is the version that works in Windows XP and NOT RetroArch-x86-setup.exe, which works in Win7 32-bit. Researched this extensively yesterday until a nice Reddit user finally clued me in.
