### ISSUE TITLE
1.7.0 on PS Vita takes many time to start to accept input

### ISSUE THREAD

**Issue by meleu** [libretro/RetroArch#6127]
## Description

I'm noticing a weird behavior when the cheevos feature is enabled on RetroArch 1.7.0 (stable and the 10-Jan-2018 nightly): when I launch a game RetroArch take many time to start accepting input (didn't timed, but maybe 1 minute). The game runs normally, but RetroArch doesnt accept any input for a long while (not even invoking the menu).

Also, the achievements list doesn't load at all. Not even after waiting all the time until RetroArch starts to accept input and more.

Somebody may suspect that it's related with the badges new feature but I tested it with it disabled and the problem persists.

I also tested with Leaderboards disabled, same issue.

If cheevos feature is disabled, no issue. Everything runs as expected.

**Notes**
- This issue doesn't happen when the cheevos feature is disabled.
- This issue doesn't happen on 1.6.9.

### Expected behavior

1. RetroArch accepting input right after loading the game.
2. RetroArch loading the achievements.

### Actual behavior

1. RetroArch takes many time until starting to accept input (although the game runs normally while RetroArch isn't accepting input)
2. RetroArch doesn't load the achievements no matter how much time I wait.

### Steps to reproduce the bug

1. launch RetroArch 1.7.0 on a PS Vita
2. enable achievements
3. launch a game
4. wait for about 1 minute for RetroArch starting to accept input
5. note that achievements won't load

### Bisect Results

Eh... I think I already did this on the Description above.

### Version/Commit

- Build date: Dec 26 2017
- Git version: 5e0f78e

### Environment information

- OS: PS Vita
- Compiler: NA

**Comment by nileplumb** [comment]
I confirm, still present in nightlies too, everything works fine in 1.6.9 thanks for helping me discover the bug!

**Comment by pralima87** [comment]
I can confirm this bug too.

**Comment by meleu** [comment]
@pralima87 
> Updating cores and downloading files is not working in 1.7.0.

AFAIK "Core updater" doesn't work on Vita. Any version. I think it's not a RetroArch fault but a limitation of the Vita system.

**Comment by frangarcj** [comment]
I'm going to try bisect it on the next couple of days. You can confirm 1.6.9 is the latest working version?

**Comment by meleu** [comment]
Summing up:
- 1.6.9: working just fine
- 1.7.0: has the issue I describe in the OP
- 1.7.1: didn't test myself but I got some reports with the same issue.

@frangarcj please let me know if you want a tester. I'm looking forward to get some cheevos related features implemented post 1.6.9...

**Comment by frangarcj** [comment]
@meleu you have sdk setup? If so you can go to discord channel and I will guide you to do a bisect.
