### ISSUE TITLE
[3DS] Shader Preference Not Saved With Per Core Overrides

### ISSUE THREAD

**Issue by saphiresurf** [libretro/RetroArch#6135]
## Description

The type of shader you use in a core if any at all isn't saved/applied with a core override.

### Expected behavior

A core override should include what shader you're using

### Actual behavior

The shader will never change based on core overrides

### Steps to reproduce the bug

1. Open Snes9x 2005
2. Launch a game
3. Save core overrides before setting up any shaders
4. Go into Gambette
5. Launch a game
6. Change the video shader to Scale2x
7. Save core overrides
8. Open Snes9x
9. Launch a game

### Bisect Results

This has happened since I started messing around with this

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0

### Environment information

- Device: New 3DS XL
- CFW: Luma
- Firmware #: 11.6.0-39U

**Comment by Saphiresurf** [comment]
This becomes a huge problem mostly because there's cores that don't perform well with SNES9x while there's ones that do like with Gambette. It's also a little serious, too, because the most accurate NES emulator available for the platform, Nestopia, actually completely crashes if there's any shaders enabled at all, so it would be nice to be able to disable shaders for Nestopia and SNES9x while having a Scale2x shader on Gambette.

**Comment by hizzlekizzle** [comment]
Instead of storing the shaders in core overrides, you should save a core preset from the shader menu. To save an override with *no* shaders (e.g., for nestopia), you should save a single pass of the stock shader instead, just FYI.

**Comment by Saphiresurf** [comment]
@hizzlekizzle Not sure if it's possible to save a core preset from the shader menu on the 3DS. You go to Settings > Video > Video Filter then select a shader from a directory there. There's no option to save a core preset that I'm seeing. Also which shader is the stock shader? Not sure if that option is available on the 3DS either...

**Comment by hizzlekizzle** [comment]
ohhh, those are the CPU filters, not the GPU shaders. I'm surprised the filters aren't being picked up by the overrides, then :/

@radius is that an intentional skip?

**Comment by orbea** [comment]
fwiw I can reproduce this on linux with CPU filters.

**Comment by fr500** [comment]
@hunterk not International,  overrides only work with members of the
settings struct and for some arcane reason some stuff loads directly to the
video driver

**Comment by fr500** [comment]
That said...
3DS doesn't support shaders... this issue name at least is invalid.

I told @twinaphex about the non-settings config members and he said he didn't want "excessive pointer grabbing from the drivers"

So, won't fix

**Comment by twinaphex** [comment]
I agree in hindsight the code in gfx/video_driver.c related to the video settings are messy and we are probably best off redesigning those parts. I will try revisiting this.
