### ISSUE TITLE
game saves don't sync across devices

### ISSUE THREAD

**Issue by l3iggs** [libretro/RetroArch#614]
Retro Arch is so great because it supports many different platforms. It's a bummer that it's so hard to migrate my saved games between platforms and devices.

I think it would be cool to see save game/state synchronization implemented using the [dropbox api](https://www.dropbox.com/developers) built into RetroArch.

**Comment by leoperbo** [comment]
I'm using Syncthing and successfully have synced states between Android and Ubuntu (had to configure a custom "Savestate Directory" in path options). The problem is that states generated on Android failed to be loaded in Ubuntu and viceversa.

**Comment by fr500** [comment]
Of course! savestates are not always portable between platforms.
Savefiles usually are

**Comment by leoperbo** [comment]
I got it! I had to ensure that the cores used on Ubuntu were the same cores used on Android. 

0) Using Syncthing i'm syncing my customized savestates directories between Android and Ubuntu (Syncthing must be running on both devices).

1) Uninstall the RetroArch Android stable version (1.0.0.2).

2) Download and install [this nightly RetroArch Android version](http://buildbot.libretro.com/nightly/android/2015-06-26_RetroArch.apk).

3) Open RetroArch in Android and use the "Manage cores" menu entry.

4) Slide right to the "Downloadable Cores" tab, wait a few seconds and touch the cores to install them.

5) Go back to the initial menu and touch "Settings" (configured Input tab selecting an input overlay configuration, configure Paths tab selecting my custom directories).

6) Go back to the initial menu and touch "Load RetroArch".

7) Use the overlay buttons to navigate the menu and load content.

8) Play a game, use the overlay buttons to load RetroArch's menu and save a state, close RetroArch on Android device (wait some seconds for let Syncthing  make his magic).

9) Load the same game in Ubuntu (using RetroArch) and load the same state that were saved in Android and synced to Ubuntu... Enjoy!

**Comment by DetectiveJo** [comment]
Hi, I know this issue is awhile ago, but I'm facing a similar issue. I wanna sync my save state from my Mint PC to my miyoo mini by running a script which copies the save state over to the SD card. I have checked, both are using the same core. But if I try to run the game on the miyoo mini its in a freeze state and the game doesnt run. Does the retroarch version need to be the same aswell? And does it matter if its 32bit on one device and 64bit on the other?
FIY Im trying to run Final Fantasy 7

> I got it! I had to ensure that the cores used on Ubuntu ([official stable version from libretro's PPA](https://www.google.com.mx/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CB0QFjAA&url=https%3A%2F%2Flaunchpad.net%2F~libretro%2F%2Barchive%2Fubuntu%2Fstable&ei=suSOVfzeC9jfoAS1kJqACA&usg=AFQjCNFdOu9ytE7AegxSyjm1PoSYzgd5KQ&sig2=GtjDXw3z2lDRA2OUM7nk4A&bvm=bv.96783405,d.cGU)) were the same cores used on Android:
> 
> 0) Using Syncthing I'm syncing my customized savestates directories between Android and Ubuntu (Syncthing must be running on both devices).
> 
> 1) Uninstall the RetroArch Android stable version (1.0.0.2).
> 
> 2) Download and install [this nightly RetroArch Android version](http://buildbot.libretro.com/nightly/android/2015-06-26_RetroArch.apk).
> 
> 3) Open RetroArch in Android and use the "Manage cores" menu entry.
> 
> 4) Slide right to the "Downloadable Cores" tab, wait a few seconds and touch the cores to install them.
> 
> 5) Go back to the initial menu and touch "Settings" (configure Input tab selecting an input overlay configuration, configure Paths tab selecting my custom directories).
> 
> 6) Go back to the initial menu and touch "Load RetroArch". Note that direct touching on "Load content" from Android's GUI won't detect the core and games won't be loaded. Must use "Load RetroArch" and then load content from the native RetroArch menu.
> 
> 7) Use the overlay buttons to navigate the menu and load content.
> 
> 8) Play a game, use the overlay buttons to load RetroArch's menu and save a state, close RetroArch on Android device (wait some seconds for let Syncthing  make his magic).
> 
> 9) Load the same game in Ubuntu (using RetroArch) and load the same state that were saved in Android and synced to Ubuntu... Enjoy!
>

**Comment by hizzlekizzle** [comment]
lol yeah, an issue that's been closed for >10 yrs...

In any event, savestates are extremely volatile and can break compatibility for all sorts of reasons. Some cores' states are portable across architectures and some aren't.

In-game/battery-backed saves should be fairly safe, though.
