### ISSUE TITLE
RetroArch freezes up on the game when the controller is unplugged

### ISSUE THREAD

**Issue by firelad97** [libretro/RetroArch#6141]
## Description

This has happened for a week and changing input drivers change nothing. I was playing a game and suddenly when my DS4 controller was accidentally unplugged a little from a USB port (this sometimes happen, it's a little loose but it works just fine) as how RetroArch sees it, and it freezes up in the middle of game.

At first I didn't notice this and I had thought that full screen mode was the cause but after a while I figured that the controller unplugging was causing the issues. I even tested it out myself.

### Expected behavior

Unplugging controller should just simply make RetroArch pop up the notification that it has been unplugged.

### Actual behavior

In the middle of game, RetroArch freezes with controller unplugged. On the menu (not with a game suspended), it works just fine.

### Steps to reproduce the bug

1. Plug in the controller and start RetroArch
2. Start any games
3. Unplug controller
4. RetroArch freezes

### Version/Commit
You can find this information under Information/System Information

- RetroArch: git 4b68a21a7, build Dec 25 2017

### Environment information

- OS: Windows 10 with Fall Creators Update (1709)
- Compiler: MinGW (6.3.0) 64-bit

**Comment by twinaphex** [comment]
I can't reproduce a freeze here. I used both the dinput and rawinput input drivers.

I let the DS4 be plugged in from the start. I then unplug it, and RetroArch still responds. Tested this with the FBAlpha core too.

I am on Windows 10 version 1709 too.

Maybe try a newer build? You said you are testing a version dated December 25, 2017. It might no longer happen on the most recent sources.

@fr500 Any ideas? Can you reproduce any issue here?

**Comment by firelad97** [comment]
@twinaphex No. I got that under Information / System on RetroArch. I actually installed 1.7.0 version, using the installer from the website.

**Comment by firelad97** [comment]
Bump. Still getting problems.

I will try updating RetroArch to non-stable version from 1.7.0 version.

**Comment by bparker06** [comment]
I have heard that if you have Steam running or another program that supports gamepads, this can happen. I made a change after 1.7.0 that tries to help with it, you could try the latest nightly to see if it works any better. Otherwise I would say make sure that no other gamepad-supporting application is running before or during the startup/running of RetroArch and see if that helps.

**Comment by firelad97** [comment]
Oh, I never had other programs running when I play games besides Discord. So I don't see why it's happening.

**Comment by bparker06** [comment]
Still, can you try with the latest nightly please?

**Comment by firelad97** [comment]
Sorry for the delayed response. Here's the result when using the latest nightly:

Build Date: Jan 31 2018
Git Version: ed9e82d90
Compiler: MinGW (6.3.0) 64-bit

RetroArch still freezes up during the gameplay when the DS4 controller is unplugged. No other programs/applications are running.

**Comment by firelad97** [comment]
Bump

**Comment by fr500** [comment]
Is this with the official dongle?
the official dongle forces audio to go thru the DS4, when you unplug the audio device dies, that could be the reason.

I don't have this problem with any other gamepad.

**Comment by firelad97** [comment]
Official dongle? You mean connected to the computer wirelessly? No, it's connected to my PC wired.

**Comment by unferth** [comment]
I had this problem also with the latest version, works fine with my DS3 but my friend's DS4 had a loose connection and RA would freeze/crash everytime the controller wiggled loose.

**Comment by ifernandez** [comment]
Same here. If I remove the cable with Retroarch UI nothing happens (just notification). If I do it while playing a game, Retroarch crashes. I am on MacOS X, and here is the report:

```
Process:               RetroArch [59219]
Path:                  /Applications/RetroArch.app/Contents/MacOS/RetroArch
Identifier:            libretro.RetroArch
Version:               1.7.5 (1.7.5)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RetroArch [59219]
User ID:               501

Date/Time:             2019-07-28 12:09:58.707 +0200
OS Version:            Mac OS X 10.14.5 (18F132)
Report Version:        12
Anonymous UUID:        C375785E-CE47-5B9C-231E-EF6023241F9E


Time Awake Since Boot: 590000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000020a800000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [59219]

VM Regions Near 0x20a800000000:
    MALLOC_LARGE           00000001200f2000-000000012246b000 [ 35.5M] rw-/rwx SM=PRV  
--> 
    MALLOC_NANO            0000600000000000-0000600008000000 [128.0M] rw-/rwx SM=ALI  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x00007fff3122146b CFSetRemoveValue + 18
1   com.apple.framework.IOKit     	0x00007fff33b40a73 __IOHIDManagerDeviceRemoved + 79
2   com.apple.framework.IOKit     	0x00007fff33b3d6d2 __IOHIDDeviceNotification + 194
3   com.apple.framework.IOKit     	0x00007fff33b1077a IODispatchCalloutFromCFMessage + 323
4   com.apple.CoreFoundation      	0x00007fff312236bd __CFMachPortPerform + 282
5   com.apple.CoreFoundation      	0x00007fff31223597 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
6   com.apple.CoreFoundation      	0x00007fff312234f5 __CFRunLoopDoSource1 + 527
7   com.apple.CoreFoundation      	0x00007fff3120b4ec __CFRunLoopRun + 2524
8   com.apple.CoreFoundation      	0x00007fff3120a8be CFRunLoopRunSpecific + 455
9   libretro.RetroArch            	0x0000000106298f6c -[RetroArch_OSX rarch_main] + 145
10  com.apple.Foundation          	0x00007fff335027f2 __NSThreadPerformPerform + 328
11  com.apple.CoreFoundation      	0x00007fff31228083 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
12  com.apple.CoreFoundation      	0x00007fff31228029 __CFRunLoopDoSource0 + 108
13  com.apple.CoreFoundation      	0x00007fff3120ba43 __CFRunLoopDoSources0 + 283
14  com.apple.CoreFoundation      	0x00007fff3120afb5 __CFRunLoopRun + 1189
15  com.apple.CoreFoundation      	0x00007fff3120a8be CFRunLoopRunSpecific + 455
16  com.apple.HIToolbox           	0x00007fff304f696b RunCurrentEventLoopInMode + 292
17  com.apple.HIToolbox           	0x00007fff304f65ad ReceiveNextEventCommon + 355
18  com.apple.HIToolbox           	0x00007fff304f6436 _BlockUntilNextEventMatchingListInModeWithFilter + 64
19  com.apple.AppKit              	0x00007fff2e890987 _DPSNextEvent + 965
20  com.apple.AppKit              	0x00007fff2e88f71f -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
21  com.apple.AppKit              	0x00007fff2e88983c -[NSApplication run] + 699
22  com.apple.AppKit              	0x00007fff2e878d7c NSApplicationMain + 777
23  libdyld.dylib                 	0x00007fff5d1353d5 start + 1
```

**Comment by gouchi** [comment]
I can't reproduce this issue with current version. @firelad97 are you using [xinput wrapper](http://ds4windows.com) ?

@ifernandez  it will be better if you open another issue as you are running different OS. Also please try with the [latest version available](https://buildbot.libretro.com/stable/1.7.7/apple/osx/x86_64/RetroArch.dmg) if you reproduce your issue.

Thank you.

**Comment by firelad97** [comment]
This is a year old, and the latest issue actually fixed my issue. This issue can be closed if desired.
