### ISSUE TITLE
[Feature Request] Bluetooth NetPlay

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#6145]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

It would be really cool if there was Bluetooth "net"play for RetroArch.

### Expected behavior

A feature where you can connect a Bluetooth device with RetroArch, and then play games like that :p

### Actual behavior

No Bluetooth netplay :p

### Steps to reproduce the bug

1. This isn't a bug
2. No really, this isn't a bug
3. Check the RetroArch issue tracker for actual bugs :p https://github.com/libretro/RetroArch/issues
4. Your welcome :p

### Bisect Results

This isn't a bug :p

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0

### Environment information

- OS: Windows 64-bit, Android
- Compiler: MinGW 64-bit from the build-bot, not like you would care :p

**Comment by hizzlekizzle** [comment]
Bluetooth doesn't have enough bandwidth for a netplay session.

**Comment by fr500** [comment]
And RetroArch has lan P2P support already no reason for this to happen.
The only thing I'd add on top of that is the ability to create a WiFi direct session from withing RA
