### ISSUE TITLE
Save files (.srm) not loaded if filename contains spaces

### ISSUE THREAD

**Issue by agmezr** [libretro/RetroArch#6146]
## Description

Save file are not loaded if the filename contains spaces in Windows 
### Expected behavior

When saving in game (not savestate) data should be saved

### Actual behavior

Everytime you load a game there are no savefiles of the game

### Steps to reproduce the bug

1. Load a ROM with spaces in file name (example: F-Zero X)
2. Create a new save on the game
3. Exit game, load again

### Bisect Results

The srm file is created on the specified directory as noted on output
```
[INFO] Redirecting save file to "G:\SteamLibrary\emulators\RetroArch\saves\F-Zero X.srm".
[INFO] Redirecting savestate to "G:\SteamLibrary\emulators\RetroArch\states\F-Zero X.state".
```
but the file is not loaded, when loading the ROM you will see as if a new game. Removing the name of the ROM and the .srm file will fix this (example F-Zero_X)

Tried this with Muper64Plus and Snes9X cores

### Version/Commit
Version 1.7.0

### Environment information

- OS: Windows 10

**Comment by t1254362** [comment]
Hi. I tested what you say in a very recent nightly.
I have my save folder (and save states and screenshots) moved to a specific folder (and using "sort by core"), but I opened a game, created a in game save, closed retroarch, opened again and the in game save is detected and loaded.
