### ISSUE TITLE
PS3 controller D-pad issues on Android

### ISSUE THREAD

**Issue by mjfrancis** [libretro/RetroArch#615]
The D-pad of PS3 controllers connected through USB doesn't appear to function correctly

Retroarch 1.0.0.2
2013 Nexus 7, stock Android 4.4.2 (not rooted)

The left button works correctly. Input debugging shows:
(press left)
Pad 0: 21, ac=0,  src=1281
(release left)
Pad 0: 21, ac=1,  src=1281

The up/down/right buttons only work after pressing for a second or so. Input debugging shows:
(press right)
Pad 0: x 0.07, y:0.00, z:-0.00, rz:-0.04, src=12777332.
(... after continuing to press for a second)
Pad 0: 22, ac=0,  src=1281

This occurs with both an original Japanese SIXAXIS (CECHZC1J) and a DUALSHOCK3 (CECHZC2J) that work without issue in other applications

The triangle/square/circle/X buttons also appear to be mapped oddly under PS1 emulation, although this is likely a separate issue

Please let me know if I can provide any further information

**Comment by 3miliooo** [comment]
Same issue on Galaxy S4 stock 4.3 using OTG cable, affects all emulators and all my ROMs.

**Comment by 3miliooo** [comment]
Don't suppose I can beg the 0.9.9.6 r22 APK off anybody if that works, pleeze? :(

**Comment by TheBeefiest** [comment]
So was this fixed?
The version on the android store is dated march 9 2014.

My ps3 controller (connected via usb) can dpad and select apps in the android operating system, but trying to set up anything in the input settings inside RetroArch doesn't work, and then the keyboard input stops working too so there is no way to get out of the menu that is trying to set input buttons.

**Comment by GPDP2** [comment]
I remember having loads of issues with my DS3 on RetroArch as well, which put me off on the Android port for some time. I tried a recent nightly not too long ago, however, and it immediately picked it up and everything more or less just worked. So maybe the issue you had is gone now.

**Comment by 3miliooo** [comment]
Thanks but still no luck, even on the nightly from Feb 19th. 
Seems to be an issue on pre-KitKat builds, Radius and hunterk have been looking at it, as per this discussion on the RA forums which I've been contributing to: 
http://libretro.com/forums/threads/1961-USB-SNES-Controller-Input-Problem-(D-Pad)/page3 
Might help them if you could chime in and maybe advise what version of Android you were on at the time of your issues / are on now?

**Comment by 3miliooo** [comment]
FIXED! :D
 
https/github.com/libretro/RetroArch/issues/1423 

Nightly build 26.02.15 working on my JB S4.
