### ISSUE TITLE
[Wii U] Wiimote sideways not recognized

### ISSUE THREAD

**Issue by cucholix** [libretro/RetroArch#6152]
## Description

Wiimote without any attachment couldn't be recognized as a controller, RA doesn't display the message in yellow text about the controller unlike Wii U Pro Controller, or GamePad.

### Expected behavior

Wiimote to be recognized in order to navigate the menu and play games with it.

### Actual behavior

The Wiimote without any attachment (sideways NES style) is not recognized as the other Wii U controllers, strange enough if you attach a Classic Controller into it, RA recognize the device and assign an user for it, however the "b" button gets mapped as "up" and the "a" button as "down" make it impossible navigate the menu. 

The ONLY way that the Wiimote can be recognized is by attaching a Classic Controller first, then unplug it, even then the button map is messed up.

### Steps to reproduce the bug

1. Start RA
2. Press a button in the Wiimote
3. The Wiimote light indicates it successfully sync with the console
4. RA doesn't recognize the Wiimote, you can't do anything with it

### Version/Commit
Git version c5ffd06

- RetroArch: [version/commit]
1.7.0

### Environment information
- Wii U 5.5.2
- Nintendo official controllers

**Comment by cucholix** [comment]
@gblues @QuarkTheAwesome

**Comment by gblues** [comment]
Sigh. This is probably me again.

The relevant code will be in `wiiu/input/kpad_driver.c` and I will look over it when I get home.
