### ISSUE TITLE
RetroArch freezing on the menu when using XMB

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#6154]
## Description

RetroArch freezes when moving across the horizontal entries

### Expected behavior

It shouldn't freeze 

### Actual behavior

It freezes after a few entries, only happens if thumbnails are enabled (they are by default)

### Steps to reproduce the bug

1. Load RetroArch
2. Set menu driver to XMB
3. Scroll right a few times

### Version/Commit
You can find this information under Information/System Information

- RetroArch: seems the hash is not embedded in 3ds buids..., it reads Jan 20 2018

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment]
I've found that I need to resize the window sometimes to unfreeze it. This is on Linux, however. Not 3DS.

**Comment by fr500** [comment]
It seems It's basically building the path on top of the path on top of the path without resetting it.

For instance on PS3 I get this on the log after a few loops

```
E {PPU[0x1000000] Thread (main_thread) [0x00181738]} Stat: 'sys_fs_open' failed with 0x80010006 : CELL_ENOENT, “Named_Boxarts.png/Named_Boxarts.png/Named_Boxarts/Driver.png/Named_Boxarts/No playlist entries available..png/Named_Boxarts/Super Mario Bros. (World) (FCEUmm).png/Named_Boxarts/No playlist entries available..png/Named_Boxarts/Start netplay host.png/Named_Boxarts/Scan Directory.png/Named_Boxarts/Quick Menu.png/Named_Boxarts/Driver.png/Named_Boxarts/No playlist entries available..png/Named_Boxarts/Super Mario Bros. (World) (FCEUmm).png/Named_Boxarts/No playlist entries available..png/Named_Boxarts/Start netplay host.png/Named_Boxarts/Scan Directory.png/Named_Boxarts/Quick Menu.png/Named_Boxarts/Driver.png/Named_Boxarts/No playlist entries available..png/Named_Boxarts/Super Mario Bros. (World) (FCEUmm).png/Named_Boxarts/No playlist entries available..png/Named_Boxarts/Start netplay host.png/Named_Boxarts/Scan Directory.png/Named_Boxarts/Quick Menu.png/Named_Boxarts/Driver.png/Named_Boxarts/No playlist entries available..png/Named_Boxarts/Super Mario Bros. (World) (FCEUmm).png/Named_Boxarts/No playlist entries a” [x14]
```
