### ISSUE TITLE
[Feature Request] Watch shader files for changes

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#6156]
## Description

I spoke with @bparker06 about this the other day on discord. Currently, I spend a lot of time going back and forth from my text editor to RetroArch just to hit 'apply shader changes' when working on shaders.

### Expected behavior

It would be a great timesaver for me if I could tell RetroArch to watch the shader files for changes and have it automatically recompile the shader(s) whenever it sees a change.

### Environment information

- OS: Mostly concerned with Linux but Windows would be nice,

**Comment by bparker06** [comment]
Implemented in #6184
