### ISSUE TITLE
[Wii U] Shader saving issues

### ISSUE THREAD

**Issue by cucholix** [libretro/RetroArch#6164]
## Description

It's not possible save shader parameters under "shader menu". 
It's not possible save a due shader as core or game preset.

### Expected behavior

To be able to edit parameters in shader menu and then save as preset. 
To be able to auto load a due shader when you start a core/game.

### Actual behavior

Shader Menu doesn't allow save parameters, the only way to tweak a shader is through Shader Preview. Even if you edit the parameters under Shader Preview you CAN'T press Apply Shader because it reverts all the changes.

You can't assign a due shader through Core Save feature, neither Game Save.

### Steps to reproduce the bug

1. Start RA
2. Select a game from playlist
3. Quick menu > Shader > Select Preset Shader
4. Under Shader Menu change any parameter
5. Apply 
6. There's not change

### Bisect Results

Since the shader feature was included on Wii U.

**Comment by cucholix** [comment]
@aliaspider @gblues @QuarkTheAwesome

**Comment by aliaspider** [comment]
are you sure that this is wiiu specific ?

**Comment by cucholix** [comment]
yes, confirmed with @fr500 and @hunterk that PC version stores shader settings

**Comment by aliaspider** [comment]
ok I might know where to look. can you confirm if the parameters are stored in the .slangp files ? even they they aren't being used.

**Comment by cucholix** [comment]
yes, the parameters are stored in slangp files; as test I edited the slangp manually from a text editor, the new values that I set were visible on Menu Shader, however the shader completely ignored those changes and keep using the original values.

**Comment by cucholix** [comment]
This issue has been fixed
