### ISSUE TITLE
Installing games

### ISSUE THREAD

**Issue by clmrules** [libretro/RetroArch#617]
Whenever I try to install a Nintendo ds game it will never work and I try to install a N64 game it won't work. I am doing this through the ipad without a computer if anyone can tell me how to install games onto the ipad and make them work that would be great. Thank you

**Comment by joujoubox** [comment]
One websites like http://www.loveroms.com you find the rom you want, press download, then WAIT. It' salt about patience. Once the download is complete, press, open with, then retroarch

**Comment by fr500** [comment]
please do not link to rom sites.
