### ISSUE TITLE
Illegal usage of your software by a french company, NESPi ?

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#6182]
According to that website, this French company sells Raspberry PI cases with Retropie software included with emulators from you and RetroPie ( and SD cards that have games included too ?! )

So this company violates the licences of RetroPie and Libretro by selling their products. My twin brother has warned me of this. Having an account on Github we wish to warn you.

Here is informations about the French company if you want to contact them about that violation of the licences :  

-> Official page of the product : https://boutique-retrogaming.com/

-> Products : https://boutique-retrogaming.com/categorie-produit/console-de-jeu-retro-nespi-case/

-> Products that violate the licence for instance : 
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/console-nespi-16go-innext/
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/console-nespi-16go/
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/nespi-case-32go/
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/console-nespi-128go/
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/console-nespi-32go-2-manettes-xbox/
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/console-nespi-32go-4-manettes/
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/console-nespi-128go-xbox/
=> https://boutique-retrogaming.com/boutique/jeux-retro/nintendo/console-nespi-128go-4-manettes/

![products](https://user-images.githubusercontent.com/6382343/35438365-892e52b4-0296-11e8-89e9-7d97e0b20154.png)

-> Facebook Page : https://www.facebook.com/Boutique-Retrogaming-1860673187510896/
Conversation in French language saved on PDF file between the company and my twin brother : the company "Boutique Retrogaming" refuses to stop the sale of the products concerned.
[Conversation.pdf](https://github.com/libretro/RetroArch/files/1667659/Conversation.pdf)

-> Company  : 
Name : Boutique Retrogaming
Address : 15 rue des pêcheurs, 59240 Dunkerque - France
Phone number ( France ) : 06 34 67 76 04
Email address : contact@boutique-retrogaming.com

The Website https://www.boutique-retrogaming.com is edited by DK BADGES, an auto-company registered with the RCS of Dunkerque under the number 477 777 858, whose head office is located in 15 rue des pêcheurs, 59240 Dunkerque - France.

The legal representative of the company DK BADGES is Julien Naëls.
The Director of the publication of the Site is Julien Naëls.

![company-legal-notice](https://user-images.githubusercontent.com/6382343/35438120-9c486192-0295-11e8-9542-2a27530bc9cb.png)

You can download on the ticket the PDF documents from the company that we found about their products : 
[NESPi_Liste_Jeux_128GB.pdf](https://github.com/libretro/RetroArch/files/1665274/NESPi_Liste_Jeux_128GB.pdf)
[NESPi_Notice_Utilisateur.pdf](https://github.com/libretro/RetroArch/files/1665275/NESPi_Notice_Utilisateur.pdf)
[NESPi_Liste_Jeux_32GB.pdf](https://github.com/libretro/RetroArch/files/1665276/NESPi_Liste_Jeux_32GB.pdf)
[NESPi_Liste_Jeux_16GB.pdf](https://github.com/libretro/RetroArch/files/1665277/NESPi_Liste_Jeux_16GB.pdf)

Note : This ticket will be written for RetroArch and RetroPie, both are concerned by this issue.

**Comment by RobLoach** [comment]
Likely could be taken up with the RetroPie peeps too?
https://retropie.org.uk/about/legal/

**Comment by JackoboLeChocobo** [comment]
Already done in the same time for RetroPie Team : https://github.com/RetroPie/RetroPie-Setup/issues/2269

**Comment by JackoboLeChocobo** [comment]
Updated informations about the company if needed

**Comment by twinaphex** [comment]
Does it come out of the box with all those games on it that are listed in the PDF? If so, report it to the ESA or a similar body, that would be highly illegal, and it could get taken down without us even having to get involved.

If that isn't the case, a few remaining options remain:
- He is using either RetroPie or Lakka, both are non-commercial
- Snes9x and other non-commercially licensed cores are being used, if he is selling them, that is a violation of their license.

Anyway, the problem is enforcing this. With other examples we have gone to Amazon and let them deal with it.

Also, this isn't really a code issue. Perhaps we need a separate section for this in one way or another.

**Comment by JackoboLeChocobo** [comment]
I don't find sections to publish this. So I prefer to inform about that here. My twin brother apparently has contacted already the publishers of the games (SEGA, Nintendo, Capcom, ... ) and the FSF about this issue. But because there are too a licence issue about your software, I prefer to inform you too.

**Comment by twinaphex** [comment]
@JackoboLeChocobo So, just to confirm, are they shipping games on this as well as part of the purchase? That is highly illegal yeah, and we do not wish to have our software be associated to infringers like this.

If he is indeed selling these games on this device as part of the purchase, and he is living in France, an EU country, then it isn't long before any videogame publisher starts taking action against him.

**Comment by JackoboLeChocobo** [comment]
Apparently yes about the games

**Comment by twinaphex** [comment]
OK, that should be enough to kill off his 'product' here.

**Comment by JackoboLeChocobo** [comment]
Agree with you twinaphex, works of all people on the emulators deservers better than to be tainted by this Illegitimacy.

**Comment by JackoboLeChocobo** [comment]
Even with proofs, nothing in France want help to stop the sell of these products. Solution in France : paid between 1000 and 2000 $ a lawyer. I suggest you to see solutions in your side about the illegal use of your software.

**Comment by twinaphex** [comment]
We don't need to spend that money. This seller is selling the copyrighted works of plenty of videogame companies. If they want to protect their trademarks and copyright, they will see to it that the seller gets dealt with. This should be very easy for them to do since there are multiple afflicted parties.

**Comment by MikaXII** [comment]
I speak as a team member of Recalbox and we already try to speak with this guy in the past, and now he completly doesn't care about copyright : 
![20180204_004332](https://user-images.githubusercontent.com/5852233/35795287-fb0c9fde-0a58-11e8-8572-21c1ac07bfda.jpg)
Quick translation : 
- Boutique Retro : 'For people who want, a game list is available on our website on direct download'
- Thomas PSZ : 'But it was illegal, did you paid the licenses ?'
- Boutique Retro : 'File a complain and we will see it in a court, "asshole"'
The last message Thomas just say he will report us this thead.

And the second picture, Thomas was threaten him and is daughter by the seller of boutique retrogaming  : 
![20180204_053258](https://user-images.githubusercontent.com/5852233/35795708-4da0e380-0a5a-11e8-9c02-b6e3188e6737.jpg)
![20180204_053323](https://user-images.githubusercontent.com/5852233/35795729-5baacac2-0a5a-11e8-9e40-dfe2dd64b9ed.jpg)

I think we are all agree to say this guy is a fucking joke... And sorry I know my english sucks ^^.
If you want a translation for the 2nd picture I'll do it later :)

**Comment by JackoboLeChocobo** [comment]
I think it's time to do something, really....

**Comment by MikaXII** [comment]
I don't if the french autority are really efficient, or aware about this kind of problem...
The best solution agree me its to report that at Nintendo fr, there doesn't really joking about resselling their old product ^^.
But currently I didn't find where I can download games on their website
