### ISSUE TITLE
Slackware64 14.2 - I can't compile from SlackBuild (sbo)

### ISSUE THREAD

**Issue by inukaze** [libretro/RetroArch#6185]
Hi there i am trying to build RetroArch 1.7.0 (Lastest Version) but ever show me this message

```
Checking operating system ... Linux 
Checking for suitable working C compiler ... /usr/bin/clang does not work
Error: Cannot proceed without a working C compiler.
Total build time for package RetroArch : 42.53 Sec
```

clang is working normally. is just a symbolic link to clang-3.8 in the same folder.

**Comment by bparker06** [comment]
Paging @orbea

**Comment by twinaphex** [comment]
@orbea Can you look into this?

**Comment by orbea** [comment]
@inukaze Sorry for the delay in noticing this issue. I tried to reproduce this in my clean Slackware64 14.2 chroot with `CC=clang CXX=clang++ ./RetroArch.SlackBuild` and was not able to reproduce it. How are you building the SlackBuild? By default Slackware will use gcc so I assume you set `CC` and `CXX` somewhere?

The configure script will create the test c file below and then use the compiler to try compiling it, if it fails it will print the error you found. I think the only way this can happen is if there is something wrong with your llvm package. 

Can try creating this `test.c` and try building it with the following command?

test.c
```
#include <stdio.h>
int main(void) { puts("Hai world!"); return 0; }
```
Now build it.
```
/usr/bin/clang -o test.o test.c
```
The return code should be `0` (No error).
```
$ echo $?
0
```
In the future I would suggest reporting issues for SlackBuilds at the slackbuilds.org mailing list, the slackware linux questions forum, mailing the maintainer listed in `$PRGNAM.info` and/or at the #slackbuilds @ freenode irc channel.

Personally I am easiest to reach via irc.

**Comment by orbea** [comment]
@inukaze The SBo version was updated to `1.7.1`. Can you still reproduce this?

**Comment by inukaze** [comment]
With SBo Package, this error don't happen. works fine

Screenshot
[![Slack_Retro_Arch.png](https://s25.postimg.org/4apdisggf/Slack_Retro_Arch.png)](https://postimg.org/image/gpc5j47yj/)

**Comment by orbea** [comment]
Cool, good to hear! Maybe this issue can be closed then since it seems resolved?
