### ISSUE TITLE
Emscripten build not running on server?

### ISSUE THREAD

**Issue by Rogerjwilkinson** [libretro/RetroArch#6188]
Hi I'm trying to host a version of the emscripten retroarch on my centos 6, but something seems way off. Either the directions are very old and unusable or I am missing something very obvious?

"If you want a self hosted version you need

A web server, nginx/apache will do, unzip a nightly here: https://buildbot.libretro.com/nightly/emscripten/
Move the template files from the embed folder to the top level dir, the other templates are for specific sites"

I download, I extract, I open index.html or embed.html, and it's broken everywhere, the script sources don't point to anything. There is also no embed folder, or what I can see to be template files? Is there instructions missing or am I missing steps? Can somebody explain this to me please?

Thanks.

**Comment by RobLoach** [comment]
Check the template, may be referencing files that don't exist. Try updating the paths.

**Comment by Rogerjwilkinson** [comment]
I'm working my way through it trying to make sense, but I think the build is either broken or missing dependencies I'm quite sure.

First thing I did was point the CDNs to the right https:// links and confirmed they were all still up, then removed my CSP to minimize potential issues, and nadda.

anayltics.js = google analytics? Or is that a necessary script? Either way, it's not included in the build but supposed to be provided to the template. Small things like this make it very confusing.

<a class="dropdown-item" href="." data-core="genesis_plus_gx">Genesis Plus GX</a>
<a class="dropdown-item" href="https://libretro.itch.io/retroarch" data-core="nestopia">Nestopia (NES)</a>

Huh? I don't even see a preventdefault or anchor rewrite for these hyperlinks in libretro.js, or anywhere else? I'll dig through the js a lot more later tonight, but from what I've seen and seeing at the moment, this emscripten build is not even close to in a "drop in and play" state like the readme says? Oh and that also reminds me, the coffee script for setting up paths on the server also doesn't exist anymore, the git completely closed down...

I'd love to be proven wrong on all this though.

**Comment by Rogerjwilkinson** [comment]
2 days of hair-pulling has gotten me to here.

"WEBPLAYER: error: Error: ENOENT: No such file or directory., '/' falling back to in-memory filesystem
libretro.js:55:19
uncaught exception: Error: undefined: XHR error."

which seems to run into a deadend. Do I need to "install" or configure browserfs on my vps somehow? Or edit libretro.js to not call on it if I don't want it or something? Would appreciate any help on this matter ty.

**Comment by RobLoach** [comment]
You may need to download the emscripten build from  uildbot and copy and past the xhr file file in.

**Comment by jribal** [comment]
Hi, exact same issue here.


I guess I used the same tutorial as @Rogerjwilkinson.
 [https://github.com/libretro/RetroArch/blob/7d64fdabf959da91ec2574333cd7fd531f976959/pkg/emscripten/README.md](url)
I would say the build are not correct and untested or the documentation is not correct.

I found all buttons to be disabled, after I they get enabled I can see black squares instead of images on firefox. On chrome I have :
`exception thrown: TypeError: Cannot read property 'getError' of undefined,TypeError: Cannot read property 'getError' of undefined
    at _glGetError (<anonymous>:1:230577)
    at wasm-function[2662]:713
    at wasm-function[909]:1970
    at wasm-function[992]:272
    at wasm-function[5049]:13
    at Object.Module.dynCall_vi (<anonymous>:1:290454)
    at invoke_vi (<anonymous>:1:259636)
    at wasm-function[412]:19089
    at wasm-function[500]:880
    at wasm-function[506]:360
    at wasm-function[352]:98
    at wasm-function[1347]:69
    at Object.Module._main (<anonymous>:1:284037)
    at Object.callMain (<anonymous>:1:293605)
    at startRetroArch (http://domain:1929/libretro.js:141:22)
    at HTMLButtonElement.onclick (http://domain:1929/:38:114)`

Vba next links to this site which does not work well [https://libretro.itch.io/retroarch](url)  
The result is far from what I see here : [https://buildbot.libretro.com ](url)

Someone knows how to make it work the same ?
Is there an up to date documentation to host this or someone willing to share his ?

**Comment by jribal** [comment]
I tried the stable version [https://buildbot.libretro.com/stable/1.7.0/emscripten/RetroArch.7z](url).
It mostly works ok once "disabled" is removed from run button using browser dev tools.

I unzip all on a directory and used nginx to serve the directory. That's all.
Tested on chromium and firefox.

Many cores does not work at all or can't run games.
Game boy systems are functional except small sound issues.
Some cores are selectable but not bundled in the zip like glupen64.

I would recommend to stick to the stable for self hosting.
Is there a document to recap the state of the webplayer (roadmap, known issues...) ?

**Comment by Rogerjwilkinson** [comment]
@jribal Good work my man! With your assurance that it worked I was able to push through and get that version you linked working. Only tested snes9x and gambatte so far, but good stuff from what I saw. I'm digging through the embed.js at the moment to try and see if there's a way to load locally stored roms and/or auto-play them on load. Last posts I could find on the matter retroarch say they don't like the idea, which is a shame it's just about ease of use for my visitors, but I'll look into it.

Let me know how it is working for you my friend!

**Comment by Rogerjwilkinson** [comment]
var Module = 
{
  noInitialRun: true,
  arguments: ["-v", "--menu"],
  preRun: [],
  postRun: [],
  print: (function() 
  {

I'm pretty some extra arguments have to be passed through to here (core and rom?, maybe in preRun?), I guess along with either passing startRetroarch(), or possibly even bypassing that and triggering Module['callMain'](Module['arguments']);
   document.getElementById('canvas').focus(); on body load?

I'm a bit in over my head here though. Could anyone guide me in the right direction by chance?

**Comment by jribal** [comment]
@Rogerjwilkinson Hi, sorry I am only trying to make this work cleanly for my server.

Do you have to force removing the "disabled run" button too ?

This guy tried to do what you are looking for without success. [https://forums.libretro.com/t/web-player-to-support-automatic-rom-and-core-loading/11061](url)

It should be possible to make it with enough javascript knowledge plus retroarch knowledge. If I wanted to do the same I would start by learning how I can do the same with a regular retroarch then try to do the same from javascript. Good luck.

**Comment by Rogerjwilkinson** [comment]
@jribal No I didn't have to remove the disabled run button. 

                     ```
 <button class="btn btn-warning disabled" id="btnRun" onclick="startRetroArch()" disabled>
                         <span class="fa fa-spinner fa-spin" id="icnRun"></span> Run
                      </button>
```

Thst is still in my index.html file and it is working fine. If you removed the Run button how do you start the games at the moment? What issue was it causing? Looking at it, it shouldn't do anything until the page is loaded and the jquery kicks in - Was it crashing loading the page included, or hte button just didn't work? Do you definitely have jquery loaded? I had to change my jquery src from code.jquery to ajax.googlesapis fwiw.


That sounds like good advice. I will look into doing it that way. It looks like the arguments section is just the standard commandline arguments so at first glance it sounds like a really really good idea to do it that way. But I'm not convinced it will be that easy - I don't undersatnd browserfs at all, and I'm not sure how hard (or easy) it will be to tell retroarch to ignore browserfs and instead load a roam from the server. Sounds tricky.

Keep in touch!

**Comment by Rogerjwilkinson** [comment]
ugh I'm just mad now. I had it working just fine but now everything errors out on launch with

SyntaxError: expected expression, got '<'
[Learn More]
retroarch:1
p
https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:516
globalEval
https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:2581
text script
https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:17034
Qb
https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:10192
A
https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:13719
c/<
https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:4:16323


I don't understand at all. Can't make that error go away no matter what I do.

**Comment by Rogerjwilkinson** [comment]
Hmm I tried passing the -L commandline (with and without --menu) like you would with any other version of retroarch with

""-L snes9x_libretro.js /path/to/rom.smc"" and after pressing run  it spat this out at me

===================================================================
 -- 5e0f78e --
Compiler: Clang/LLVM (3.9.0 ) 32-bitBuilt: Dec 26 2017
===================================================================
Usage: ./this.program [OPTIONS]... [FILE]
  -h, --help            Show this help message.
  -v, --verbose         Verbose logging.
      --log-file FILE   Log messages to FILE.
      --version         Show version.
      --features        Prints available features compiled into program.
      --menu            Do not require content or libretro core to be loaded,
                        starts directly in menu. If no arguments are passed to
                        the program, it is equivalent to using --menu as only argument.
  -s, --save=PATH       Path for save files (*.srm).
  -S, --savestate=PATH  Path for the save state files (*.state).
  -f, --fullscreen      Start the program in fullscreen regardless of config settings.
  -c, --config=FILE     Path for config file.
		By default looks for config in $XDG_CONFIG_HOME/retroarch/retroarch.cfg,
		$HOME/.config/retroarch/retroarch.cfg,
		and $HOME/.retroarch.cfg.
		If a default config is not found, the program will attempt to create one based on the 
		skeleton config (/etc/retroarch.cfg). 

      --appendconfig=FILE
                        Extra config files are loaded in, and take priority over
                        config selected in -c (or default). Multiple configs are
                        delimited by '|'.
      --subsystem=NAME  Use a subsystem of the libretro core. Multiple content
                        files are loaded as multiple arguments. If a content
                        file is skipped, use a blank ("") command line argument.
                        Content must be loaded in an order which depends on the
                        particular subsystem used. See verbose log output to learn
                        how a particular subsystem wants content to be loaded.

  -N, --nodevice=PORT
                        Disconnects controller device connected to PORT (1 to 16).
  -A, --dualanalog=PORT
                        Connect a DualAnalog controller to PORT (1 to 16).
  -d, --device=PORT:ID
                        Connect a generic device into PORT of the device (1 to 16).
                        Format is PORT:ID, where ID is a number corresponding to the particular device.
  -P, --bsvplay=FILE    Playback a BSV movie file.
  -R, --bsvrecord=FILE  Start recording a BSV movie file from the beginning.
      --eof-exit        Exit upon reaching the end of the BSV movie file.
  -M, --sram-mode=MODE  SRAM handling mode. MODE can be 'noload-nosave',
                        'noload-save', 'load-nosave' or 'load-save'.
                        Note: 'noload-save' implies that save files *WILL BE OVERWRITTEN*.
      --nick=NICK       Picks a username (for use with netplay). Not mandatory.
  -r, --record=FILE     Path to record video file.
        Using .mkv extension is recommended.
      --recordconfig    Path to settings used during recording.
      --size=WIDTHxHEIGHT
                        Overrides output video size when recording.
  -U, --ups=FILE        Specifies path for UPS patch that will be applied to content.
      --bps=FILE        Specifies path for BPS patch that will be applied to content.
      --ips=FILE        Specifies path for IPS patch that will be applied to content.
      --no-patch        Disables all forms of content patching.
  -D, --detach          Detach program from the running console. Not relevant for all platforms.
      --max-frames=NUMBER
                        Runs for the specified number of frames, then exits.


with a relevant error I think


RetroArch: Frontend for libretro -- v1.7.0[ERROR] Fatal error received in: "retroarch_parse_input()"
[ERROR] This core requires a content file.

So I'm not sure what to make of that. On one hand it looks like -l has been removed from the available CLI parameters (though that post you links to asserts what I said about it should be as easy as passing the parameter) but on the other, it didn't error out on me? I'm not sure. I suspect, maybe, it recognizes the parameter but can't load the file due to the browserfs implementation?

**Comment by jribal** [comment]
@Rogerjwilkinson 
I had to remove the disabled part in html to access the run button. Awkward issue if I'm the only one, I'll try remove start again from zero, I'm actually trying to use it in a docker container, I'll try to dig my error.

`bot.libretro.com/.web/:1 Uncaught SyntaxError: Unexpected token <`

`embed.js:117 Uncaught TypeError: Cannot read property 'FileSystem' of undefined
    at idbfsInit (embed.js:117)
    at Object.success (embed.js:389)
    at i (jquery-3.1.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.1.0.min.js:2)
    at A (jquery-3.1.0.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-3.1.0.min.js:4)`

**Comment by Rogerjwilkinson** [comment]
"bot.libretro.com/.web/:1 Uncaught SyntaxError: Unexpected token <"

This error 99/100 means (in my experiences) it tried to find a .js file but couldn't ,and either tried sending up a page you've redirected to with a RewriteRule, or it tries to to send the index.html of the page you're already on. So for example, you should be to recreate the SyntaxError at least by trying to load GlupeN64 - It tries to attach glupen64_libretro.js, can't find it, attaches the index of either a 404 page or the index.html page, and you'll be able to see in either your SSL_Error_Log or Error_log if you're on apache and not using an SSL certificate, that it failed to find '/var/www/html/Retroarch/filename.js'

Your error goes a bit deeper than that though - Are you positive you haven't tried enabling assets (like overlays and stuff)?  In your embed.js ensure the lines at function setupFileSystem(backend) for xfs1 and xfs2 are still commented out. I'm testing with mine at the moment so yours will look slightly different, but they're something like this.

  mfs.mount('/home/web_user/retroarch/bundle', xfs1);
   mfs.mount('/home/web_user/retroarch/userdata/content/', xfs2);

and

* create an XmlHttpRequest filesystem for the bundled data 
      uncomment this section if you want XMB assets, Overlays, Shaders, etc.
   var xfs1 =  new BrowserFS.FileSystem.XmlHttpRequest
      ("--your-assets-index-file-name--", "--your-index-url--");*/
   /* create an XmlHttpRequest filesystem for content
      uncomment this section if you want to serve content*/

Ensure all of those lines are still commented out correctly (refer to the default index.html to see correct syntax on commenting those lines out). It almost looks like those events are firing before the page has loaded correctly, you could try (but I'm just shooting in the dark here) moving the jquery and possibly even browserfs libraries up to the header from the footer? This isn't recommended practice but it's sorted strange script loading issues for me before.

That's about the most I can do with just the logs you've provided. Your error logs for the server will give you more information about the exact js (or json, possible, or w/e else) file it's failing to retrieve properly.

**Comment by fr500** [comment]
wow this has been going for a while.
let me take a look this weekend and I'll come back to you with a solution.

**Comment by fr500** [comment]
for starters you need to replace

```<script src="//web.libretro.com/browserfs.min.js"></script>```
with 
<script src="//wzrd.in/standalone/browserfs@0.6.1"></script>```

**Comment by fr500** [comment]
Ok nvm, seems the one from the CDN is bad.

![image](https://user-images.githubusercontent.com/1721040/35896251-5910cd72-0b89-11e8-8c0e-e291ac066f30.png)

Took me a couple of minutes, but you'all are right there's no way you could have figured this out, I'll add the missing files and correct the bundle.

**Comment by Rogerjwilkinson** [comment]
Hey man, awesome! Thanks for getting back to us, looking forward to sussing out the missing files - But, afaik, most things are working pretty okay with what's missing. I'm hosting browserfs locally, and I think jacked the browserfs.mem file with wget, probably why it's working a bit nicer for me. I know you've said before you don't like the question, so I hope you don't see this is as disrespectful - How would you go about serving up one (1) rom when and autoplaying it when the page is loaded? I've currently got it so that it picks a core and launches it by itself, but I'm stuck here with the game loading.

mfs.mount('/home/web_user/retroarch/userdata/content/', new BrowserFS.FileSystem.XmlHttpRequest('../path/index.json', 'path'));

This is the closest thing I've gotten to working. This will serve up every file in a directory (so downloads 300MB at load instead of 3MB). But I can't get it to serve up one (let alone load the rom it serves up yet). I created the index.json file from bash, and then edited to only include one file, but it seems to just overwrite it.

Again, thanks so much for taking the time to look at this for us!

**Comment by fr500** [comment]
That PR has the instructions, really didn't test them, and I dunno about serving up one rom and autoplaying, I just fixed the bundle so it includes the tools for you to be able to launch an instance exactly like ours.

**Comment by fr500** [comment]
I didn't test the instructions nor the bundle since the PR is not merged, assuming the buildbot is doing everything correctly when it's merged the bundle should be correct.

**Comment by Rogerjwilkinson** [comment]
Alright awesome thanks for that. I'll try and work this out on my own, maybe StackOverflow will be able to lend a hand.

One last thing: Are these guys just using a closed-source ad-littered version of retroarch? https://neptunjs.xyz   I'm almost at the point I'm just going to use that to auto-serve the roms, but want to be sure about the software I'm supporting on my website before creating 100's of pages using it hehe. If they're just using the retroarch web player anyway, I'll take the time to suss this out for myself.

**Comment by fr500** [comment]
That didn't load for me.
You shouldn't use this to auto serve content that has copyright... it's bad for our name.

RA is free to use, we can just hope you do the right thing.

**Comment by Rogerjwilkinson** [comment]
I'd suggest trying now (I changed the link to http)

**Comment by fr500** [comment]
Dunno if that's RA.

**Comment by Rogerjwilkinson** [comment]
Okay thanks a heap for your time mate. What is "PR"?

**Comment by fr500** [comment]
Pull request, it was merged already

**Comment by Rogerjwilkinson** [comment]
Well this is as close as I can get. Without help, I don't think I can get any further, 2 and a half days of my head in this code has come to here - The core is pre-selected and loaded in retroarch, the file is automatically mounted to a directory, on launch:

"[INFO] Loading content file: home/web_user/retroarch/userdata/file.smc.
Failed to open home/web_user/retroarch/userdata/file.smc: No such file or directory
[ERROR] Could not read content file "home/web_user/retroarch/userdata/file.smc"."

This is 100% the path of the mounted file, but I think, it doesn't initialize until you actually navigate to the path in RA? idk...

And this is the only error,  none in web console, js console or apache error logs. I'd love some help on this, I've come some close (for me anyway).

**Comment by fr500** [comment]
what if you follow the instructions I outlined, 
https://github.com/libretro/RetroArch/tree/master/pkg/emscripten

Then add the roms in the web server directly in $PATH/assets/cores.

And then you try to use
```/home/web_user/retroarch/userdata/content/downloads/filename.ext```

**Comment by Rogerjwilkinson** [comment]
That's what I'm saying though, I did exactly that. The coffee script doesn't exist anymore, so I installed browserfs in npm and created an index the new way, and then called the XMLHttpRequest to xhr1, mounted it alongside afs (will put full code at the bottom, though it's pretty much word for word from the original), and no go, it just gives me that retroarch error. No other errors in any logs tells me it's very very close, I think. I don't know though, I suspect that it can't load it because the file hasn't been initialized and downloaded yet? There's a small stutter when you enter the mounted directory for the first tiem (retrieving maybe?), and then the asset/overlay/game/whatever doesn't actually download into the user's filesystem until they launch the game? I just don't know. Everytime I get close, it comes back to that RA error unfortunately.

```
//This is the mount. I couldn't find anyway to get the xhr index files anymore, but this "works" neatly.
```
var mfs =  new BrowserFS.FileSystem.MountableFileSystem();
/*var xfs1 =  new BrowserFS.FileSystem.XmlHttpRequest
      ("index.json", "../path/to/");
 mfs.mount('/home/web_user/retroarch/userdata', afs);
mfs.mount('/home/web_user/retroarch/userdata/content/', xfs1);

///I've also tried here "-l snes9x2005 /home/web_user/retroarch/userdata/content/filename.ext" and MANY MANY variations. They ALL seem to the return the same error above (probably 'cos I've got it forced to load snes9x2005 atm?)  -- This example below was the specific one that returned the error, even though it was 100% pointed to the right location of the mounted binary file.

```
  noInitialRun: false,
  arguments: ["-v", "/home/web_user/retroarch/userdata/content/filename.ext"],
  preRun: [],
  postRun: [],
  print: (function()
```

I'll play around with the paths a little more, line them up a bit more exactly with what you've outlined above, but I can't be certain. Will be an hour or two before I'm home and have access to fileserver to test.

Thank you again for your time mate.

**Comment by fr500** [comment]
the coffee script is included in the new bundle...

**Comment by jribal** [comment]
@fr500 I could not find coffee inside the bundle
 ./assets/frontend/.index-xhr needs to be ./assets/frontend/bundle/.index-xhr

[Here](https://gist.github.com/jribal/8e73ff1e41aa54a9032f965d82706bf3) is how I install using docker nginx(ubuntu). It's mostly messy.
Could you point me how you use the coffee script inside so I can make the script simpler.

**Comment by Rogerjwilkinson** [comment]
The coffee script instructions are either untested and wrong, or the coffeescript isn't behaving for us as expected, either way, here's what I did to get it working (this step is also semi-optional, you can point to an index.json instead like my code above and it will generate the necessary index file on the fly and put it in a file called index.json when you launch the app, but I digress):

Ensure cofeescript is installed: "npm install -g coffeescript" (important to remember to ditch the hyphen)

And then, move the indexer script INTO the folder you want to index. If you do it exactly as the instructions state, it will index the retroarch folder giving you a big index of your libretro cores (not desired). So move the indexer script into whatever folder you want to be come /assets/frontend/build, and just run the script like so (keep in mind the script automatically includes subdirectories recursively), I'll change it to fit your exact user case:

npm install -g coffeescript
cd /usr/share/nginx/html
cp indexer assets/frontend
chmod +x indexer
./indexer. / > ./.index-xhr
mv indexer ../cores
cd ../cores
./indexer. / > ./.index-xhr
rm -f indexer

And voila, this should create an .index-xhr of all the files and subfolders in assets/front, and then assets/cores, which you can use for the mounting  instructions above. It then also becomes very very easy to remove files from the listing, or add them after the fact (just open the .index-xhr file in your notepad++, add or remove the "file.ext",null: as necessary, and reupload it!

Let us know if something doesn't work out for you.

**Comment by fr500** [comment]
well I have a helper for the indexer
but yeah I guess it doesn't work without it but you don't need to move the script.

```just cd into the dir and ../../indexer > .index-xhr```

**Comment by Rogerjwilkinson** [comment]
> just cd into the dir and ../../indexer > .index-xhr

...................................................

So that makes a lot of sense LOL

**Comment by Rogerjwilkinson** [comment]
Alrighty, last thing I'm trying to do and then I'm pretty much good to rock-n-rolla!

I'm trying to "fix" the escape quitting the emulator. It's an awesome feature on the desktop (I was hesitant at first but have come to love it upon getting used to it) - but for the webplayer it's far from ideal behaviour, compounded by the fact there's no warning or anything.

I've spent the last 2 and a half days trying to do this. First things first, the -c and --appendconfig parameters get exactly ignored. It says "setting config to /path/to/retroarch.cfg" then 4 lines down always ignores this directive no matter what and loads from the default of "/home/web_user/retroarch/userdata/content". No matter what I do, I can't mount a config file into this directory (due to /content being a relative directory created by the emscripten mount), trying to do so causes a MOUNT BUSY error.

I tried Symlink, and Writefile directives, but I don't think I was using them correctly.

After a lot of time, I "almost" had a breakthrough, by loading a core config (in this case, Snes9x 2005.cfg), but there's still a problem in the "order" of events. Order from log goes like this (omitting useless stuff) >

dkc3.js:110 [INFO] [Config]: loading config from: /home/web_user/retroarch/userdata/retroarch.cfg.
dkc3.js:110 [ERROR] [Config]: couldn't find config at path: "/home/web_user/retroarch/userdata/retroarch.cfg"

[INFO] [overrides] core-specific overrides found at /home/web_user/retroarch/userdata/config/Snes9x 2005/Snes9x 2005.cfg.

[INFO] Loading content file: /home/web_user/retroarch/userdata/config/Snes9x 2005/content.ext

[INFO] [Config]: Saved new config to "/home/web_user/retroarch/userdata/retroarch.cfg".        <-- WAT


I can't find a core config load log, so I assume it's read and loaded when it's found, and then gets promptly overwritten by a default config. I've tried just about every last "hack" at attempt of doing this I can think of and am just stumped now.

Any ideas?

**Comment by jribal** [comment]
@Rogerjwilkinson  
../../indexer worked. Everything works out of the box without a single modification.
[https://gist.github.com/jribal/8e73ff1e41aa54a9032f965d82706bf3](https://gist.github.com/jribal/8e73ff1e41aa54a9032f965d82706bf3)

@fr500 
Sorry I misunderstood the coffeescript issue, the indexer made is coffeescript is packed inside.
I still have one warning about browserfs.js.min.map not found. I guess it is not a real issue.

It can be fix in the same dir as browserfs.js with :
`wget https://github.com/jvilk/BrowserFS/releases/download/v1.4.3/browserfs.min.js.map`

The documentation is still not correct, do you plan to fix it ?

**Comment by jribal** [comment]
I did some test.

When I hit the retroarch logo in the middle quickly after page load I have an error and I need to reload the page.
Firefox : Module.asm.__GLOBAL__sub_I_libretro_cpp is undefined
Chromium :Uncaught TypeError: Cannot read property 'apply' of undefined
    at Module.__GLOBAL__sub_I_sound_cpp (<anonymous>:1:282494)
    at func (<anonymous>:1:22834)
    at callRuntimeCallbacks (<anonymous>:1:14808)
    at ensureInitRuntime (<anonymous>:1:15308)
    at Object.callMain (<anonymous>:1:292228)
    at startRetroArch (libretro.js:141)
    at HTMLButtonElement.onclick ((index):38)
> 

When I click on menu toggle I have null, firefox or chromium only on my hosted version. The official website works fine ?

**Comment by Rogerjwilkinson** [comment]
At this point it's hard to compare my notes with others since I've hacked away at the code so damn much now, but that error shouldn't cause you to need to reload the browser, not in my experiences anyway. The error is just telling you asm.js isn't ready yet - OR I should say, for ME, that error was just telling me asm.js wasn't ready yet.

The sound crackling can be solved (or, again, FOR ME, I was able to solve the sound crackling) by increasing the audio_latency from 64 to 96 - All remaining instances of crackling was solved by using a better core (for example, one game crackled on snes9x2005 even with 96 audio_latency, but it doesn't happen on snes9x2010)

But yes, it works very very well! Especially for what seems like such an afterthought port, it's remarkable how well it runs! I got a buddy far far smarter than I looking over the source for mupen64 atm seeing why it's being such an ahole with emscripten, hopefully he doesn't get too bored too fast and we'll have mupen64 working shortly!!

**Comment by jribal** [comment]
I did test more the official website and I found the bug again.
During load : click on the logo while it blinks.
It's dead for me, waiting does not change a thing and the run button stays disabled.

In retroarch settings audio latency is at 128 by default.
Where do you set your audio latency ?

I hope he can find why it fails to run, mupen64 is one I would really like to see.

**Comment by Rogerjwilkinson** [comment]
Okay I am able to see the bug on the official webplayer page. That is a particularly annoying one. I've "fixed" it in my version by modifying the interface and using a little bit of extra javascript to make it so the end-user can't actually press on anything until the emulator is ready. There's many many ways you could skin that cat, so I won't give you a step-by-step (best to work out how you want the interfact to look for you), but I will share this tip: in the core js files (snes9x2010_libretro.js, just as an example), scroll almost all the way to bottom, and find this line

if(Module["onRuntimeInitialized"])Module["onRuntimeInitialized"]();if(Module["_main"]&&shouldRunNow)Module["callMain"](args);

You can place javascript DIRECTLY after that line, and this is your "initialization" portion. ie: javascript placed directly after that line won't run until the asm is completely ready. ;-)

Huh, I could've sworn it was 64 latency by default? At either rate, 96 seemed to be the 'magic number' for me. Try this - Under the function startRetroArch() in embed.js place the following line exactly above "Module['callMain'](Module['arguments']);"

FS.writeFile('/home/web_user/retroarch/userdata/retroarch.cfg', 'audio_latency = "96"');

Clear your cache and give it a go.

**Comment by RobLoach** [comment]
This can likely be closed. There's been a lot of updates since this issue was created.
