### ISSUE TITLE
Disable pause in menu when in NetPlay session

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#6190]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When in an netplay session, it would be really useful if the game was still running when in the menu. This should be a netplay setting.

### Expected behavior

I expected to not have to deal with the hassle of constantly turning off the pause in menu setting whenever I want to change a shader or change controls and stuff like that. So it should turn the option off whenever you are in a netplay session.

### Actual behavior

It behaves like it usually does, meaning it pauses the game when the setting is enabled causing confusion.

### Steps to reproduce the bug

1. Make sure the option for pausing in menu is on
2. Go into a netplay session
3. Go to the menu and expect the game to stop against your and the other's will.

### Bisect Results

This is partially a feature request but at the same time, this **bug**s me. ( Bug pun )

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0

### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW 64-bit from the buildbot

**Comment by fr500** [comment]
Not everyone can run the menu at full speed while in game

**Comment by hyarsan** [comment]
Maybe have it turn off the menu shaders?

**Comment by hyarsan** [comment]
Closed? Why though...

**Comment by fr500** [comment]
Because it makes no sense.

We shouldn't force user to not use pause because one user doesn't like it pausing.
