### ISSUE TITLE
D3D 11 Bugs

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#6208]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Bug 1:
![subtextbug](https://user-images.githubusercontent.com/32988993/35651054-9437bc44-06de-11e8-9088-6bf613b81fae.png)
A similar bug happens with Vulkan, just hold up or down and press the full screen toggle for one.

Bug 2:
![infooo](https://user-images.githubusercontent.com/32988993/35651117-cb466168-06de-11e8-9a68-8bc50957ee4f.png)
~~Information shows up stretched~~ Fixed!

Bug 3:
![icon_sizes](https://user-images.githubusercontent.com/32988993/35651904-a5659b28-06e1-11e8-87ed-d243b33cd66f.png)
Icons are inconsistent in size in MaterialUI

Bug 4: When using the full screen toggle, the aspect ratio changes to stretched.

### Expected behavior

The same behavior as OpenGL

### Actual behavior

See description

### Steps to reproduce the bug

See description

### Bisect Results

D3D11 driver is still pretty new, so these bugs should be expected.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Jan 31 2018

### Environment information

- OS: Windows 10 64-bit
- Compiler: Windows 64-bit from build-bot

**Comment by twinaphex** [comment]
These issues should be fixed by now.
