### ISSUE TITLE
Not possible to select content without restarting core

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#6210]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Many emulators require changing disks/content etc. without restart. But the Retroarch GUI always asks for a core, and then restarts the core when I select content. Typically, this happens when one needs to change disks in computer cores such as Dosbox, Vice, etc.

### Expected behavior

After selecting content, there should be an option to open the content in the current core without restarting the core, e.g. inserting the media without reset.

### Actual behavior

Every core is restarted when selecting it after selecting content.

### Steps to reproduce the bug

1. Select content
2. In the menu that follows, there's no option to "open in core without reset" or "insert into disk drive" etc.

### Bisect Results

This never worked.

### Version/Commit

1.7.0 nightly 01/30/2018

### Environment information

- OS: Rpi, Vita, Windows 10

**Comment by bparker06** [comment]
Isn't there a hotkey for changing disks? I know people are successfully playing multi-disc games already.

**Comment by fr500** [comment]
Cores that implement the disk API are working properly

**Comment by rsn8887** [comment]
Maybe I just didn't see the option? If disk changes are supported, how would I make them? I mostly with Vice core, maybe it is only a problem with that core?

**Comment by fr500** [comment]
My bad, turns out the disk image append interface is broken...

**Comment by rsn8887** [comment]
This is working now
