### ISSUE TITLE
Disk Image Append doesn't work

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#6255]
## Description

The disk image append available on select cores can no longer work by adding disk at runtime, whenever you try to add a disk the core is completely reinitialized.

### Expected behavior

Add a disk, and then you should be able to change to that disk by ejecting the tray, increasing the index and closing the tray

### Actual behavior

As soon as you add a disk the core is reinitialized

### Bisect Results

It's been like this for like a year, can't bisect that long

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
Do you have an easy test case? I don't have saves for any games in places that require a disk change...

**Comment by fr500** [comment]
You don't need a save just happens an image and you'll see a reset

**Comment by orbea** [comment]
I can reproduce this now. There is also another very recent issue where the file browser gets stuck in retroarch's git directory after selecting file append. I bisected this.
```
aa0f553a25d9af806c4d774707bca73bb3cf5e7c is the first bad commit
commit aa0f553a25d9af806c4d774707bca73bb3cf5e7c
Author: twinaphex <libretro@gmail.com>
Date:   Wed Feb 7 22:52:45 2018 +0100

    Remove label_hash  some more

:040000 040000 9260e174d6955eff8874fbca4dbc3ac4a6ae9811 c1f94ea77b0ee0e57aee79b4b2107898b1b6f00b M	menu
```
aa0f553a25d9af806c4d774707bca73bb3cf5e7c

I also bisected the initial issue causing the core to restart with disk append. It started between `v1.6.6` and `v1.6.7`.
```
366c73f429bf093fb0b7e876b3ea529709d1cdce is the first bad commit
commit 366c73f429bf093fb0b7e876b3ea529709d1cdce
Author: twinaphex <libretro@gmail.com>
Date:   Thu Aug 17 19:07:38 2017 +0200

    Fix 'Append Disk Image'

:040000 040000 48046531a5c9b390ca7f03e65210d01c44bca878 736c2bfb54bed452897699b417d935adf757bba3 M	menu
```
366c73f429bf093fb0b7e876b3ea529709d1cdce

**Comment by twinaphex** [comment]
Thanks for bisecting this. This should make it easier to fix.
