### ISSUE TITLE
Apply Changes not working on RetroArch Shaders option.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#6272]
On Android N using the latest RetroArch nightly selecting the shader passes manually and then using the apply changes option doesn't apply the shaders the only thing that works is loading a shader preset but changing it manually like the shader filter or scale and then applying doesn't work. GLSL shaders updated to latest using online updater too.

**Comment by fr500** [comment]
Please fill the bug report template

**Comment by fr500** [comment]
I actually tested this because I made plenty of changes to the shader preset code and it's working fine for me as evidenced here:

https://files.andressm.org/f/d3b6c58291bc466fa259/

**Comment by blackman91** [comment]
Are you on Android? I recorded a short video showing the bug here:
https://drive.google.com/file/d/1CoB23QBRe443NhdJzxO-pP4MOCALx5xT/view?usp=drivesdk

As you can see in the video I tried manually selecting the pixellate shader and apply the changes but it didn't work, used then the option to load shader preset and loaded the same pixellate shader and it worked but changing the filter and scale value didn't work.

BTW Template not showing for me on mobile will try desktop version of the site.

**Comment by fr500** [comment]
Yes I am on android.

What's your build version? (commit)

**Comment by blackman91** [comment]
I am using the latest nightly:

![screenshot_20180209-172123](https://user-images.githubusercontent.com/6578180/36054807-f5535c8c-0dbd-11e8-85bc-a1e794010295.png)

**Comment by fr500** [comment]
I'm on the same commit and it's fine here

**Comment by blackman91** [comment]
Weird I am using a motog5 plus, btw fixed video link here:
https://drive.google.com/file/d/1CoB23QBRe443NhdJzxO-pP4MOCALx5xT/view?usp=drivesdk

**Comment by fr500** [comment]
try a shader that has a more noticeable result?

**Comment by fr500** [comment]
ok I managed to repro on my phone.
Seems to only happen on a clean installation.

Can you try these steps:

Load a Preset
Hit Apply
Quit RetroArch

And confirm if it works normally afterwards??

**Comment by blackman91** [comment]
Wow that worked! You are awesome man, what caused the bug?

**Comment by fr500** [comment]
the fact that we don't have a video_shader toggle in the menu for some reason and it's toggled only via some arcane method...

**Comment by fr500** [comment]
Ok, seems this issue has been here for a while...

**Comment by fr500** [comment]
@blackman91 I know it's a stretch, but if you can test tomorrow's build after cleaning app data I'd appreciate it

**Comment by blackman91** [comment]
I will test it, btw I found I can reproduce the issue again if I just do this again:
Set shader passes to 0
Hit apply
Exit RetroArch using the option Quit RetroArch.

Now Try to load manually a shader pass again and hit apply and it won't work.

**Comment by fr500** [comment]
It should be covered by the fix too

**Comment by blackman91** [comment]
Is the fix on this build?
![screenshot_20180210-171538](https://user-images.githubusercontent.com/6578180/36067663-19f96ce2-0e87-11e8-8ef7-d5b8efa9ebce.png)

Is not working for me on latest nightly.

**Comment by fr500** [comment]
Nope, update again.

**Comment by blackman91** [comment]
Alright, it is working correctly on latest nightly! Great work.
