### ISSUE TITLE
[Wayland] No window border

### ISSUE THREAD

**Issue by Inglebard** [libretro/RetroArch#6278]
Hi,
on windowed mode, there is no border. So no possibility to reduce/move/maximize/minimize/close.
The issue appear on archlinux on gnome 3 with wayland. The issue not appear on Xorg. 

### Expected behavior

Have the posibility to reduce/move/maximize/minimize/close on windowed mode.

### Version/Commit
- RetroArch: v1.7.0Compiler: GCC (7.2.1) 64-bitBuilt: Dec 31 2017

### Environment information
- OS: Archlinux

**Comment by hizzlekizzle** [comment]
Does this also make it so you click through the window to whatever is behind it?

**Comment by orbea** [comment]
Shouldn't window decorations be handled by either gnome3 or wayland?

**Comment by hizzlekizzle** [comment]
I have this problem with my self-compiles but the snap package works fine.

**Comment by Inglebard** [comment]
@hizzlekizzle 

> Does this also make it so you click through the window to whatever is behind it?
No seems to works properly like a normal window.

**Comment by Sunderland93** [comment]
Probably, Retroarch need to support KDE's Server-Decoration protocol, whch already supported by GTK, KDE, Sway and MPV https://github.com/KDE/kwayland/blob/master/src/client/protocols/server-decoration.xml

**Comment by orbea** [comment]
Could you help explain what KDE Server-Decorations have to do with gnome3 and wayland?

**Comment by fagoatse** [comment]
@orbea read this - https://blog.martin-graesslin.com/blog/2018/01/server-side-decorations-and-wayland/

**Comment by bparker06** [comment]
duplicate of #4778

**Comment by orbea** [comment]
I am going to close this one in favor of issue https://github.com/libretro/RetroArch/issues/6606 which has more discussion.
