### ISSUE TITLE
When "video_window_show_decorations" and "ui_menubar_enable" are both set to false, a black margin is added to the right and top

### ISSUE THREAD

**Issue by saftle** [libretro/RetroArch#6284]
## Description

When "video_window_show_decorations" and "ui_menubar_enable" are both set to false, a black margin is added to the right and top of the window:

![unknown](https://user-images.githubusercontent.com/852777/36076491-13c41a9e-0f5d-11e8-937e-c92468bbfe34.png)

### Expected behavior

The black margin shouldn't exist, like when the "ui_menubar_enable" setting is set to true.

### Actual behavior

Black margin is added.

### Steps to reproduce the bug

1. Set "video_window_show_decorations" and "ui_menubar_enable" to false.
2. Start RetroArch

### Bisect Results

It started happening after committing https://github.com/libretro/RetroArch/pull/6281

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0 Nightly
- Git version: 4d1090dc53

### Environment information

- OS: Win 8.1
- Compiler: Buildbot

**Comment by orbea** [comment]
@saftle Is this still an issue? I can't reproduce it in linux, but I suppose my environment is too different.

**Comment by spoopa** [comment]
This is still an issue. Can anyone please fix it? I like playing games with relaxing wallpapers in the background and this makes the game's scale smaller. I'm using Windows 7 and RetroArch 1.7.7. Sorry if I posted in the wrong place, my first time using this site.
![blackbars](https://user-images.githubusercontent.com/51311497/58779664-ed2aa000-85d6-11e9-9471-707d58677c62.png)

**Comment by orbea** [comment]
Sorry, someone that uses windows should look at this issue.

**Comment by patrickmetz** [comment]
Ran into that issue today, too. On Retroarch 1.9.0 (Windows x86_64).

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/9570231/107073998-63d66280-67e8-11eb-893b-2dd7ace3a301.PNG">

**Comment by andersstorhaug** [comment]
Was playing with this the other day, and if I use SWRE to remove borders it produces the same result.
Not sure if that's helpful, maybe I'll find some time to look into this myself (as an uninitiated non-contributor).
