### ISSUE TITLE
UPNP is not working in netplay

### ISSUE THREAD

**Issue by furiadeoso** [libretro/RetroArch#6286]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

@GregorR 
 UPNP is not working. A host now must open ports manually or activate DMZ.

### Expected behavior

When a host open a new netplay game and have UPNP activated in the router (and is not behind CGNAT) ports must be open automatically.

### Actual behavior

When a client over internet try to join a host in direct connection got "Failed to initialize netplay"

### Steps to reproduce the bug

1. Be sure not to have 55435 ports or DMZ activated. Only UPNP
2. Open a netplay game as host in direct mode
3. A client over internet using exactly same version and core, roms... try to connect via lobby. He/she get "Failed to initialize netplay" and can not do netplay.
4. Host open ports manually or activate DMZ.
5. Client try to join again, and voila! All is ok.

### Bisect Results

Tested in 1.6.9 and it open ports via UPNP properly. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0 nightly windows 64 git version 1f3e1baeb6

### Environment information

- OS: Windows 10 64bits
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
I suppose this is related? https://github.com/libretro/RetroArch/pull/6292
