### ISSUE TITLE
New client joins prompt is not showing properly in the host side in netplay

### ISSUE THREAD

**Issue by furiadeoso** [libretro/RetroArch#6288]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

@GregorR 
Sometimes, when a client joins to a netplay game (in direct o relay mode, both), the messages that can see the host is:

$.*1$ has joined as player $u

### Expected behavior

The host must see something as:
alfrednick has joined as player 3

### Actual behavior
![image](https://user-images.githubusercontent.com/34688502/36077789-494009d2-0f6f-11e8-9b0e-b88626960a77.png)

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.0 nightly windows 64 git version 1f3e1ba

### Environment information

- OS: Windows 10 64 bits
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
Is this resolved now?

**Comment by furiadeoso** [comment]
Yes it is, @bparker06
