### ISSUE TITLE
Log is not dumping on windows

### ISSUE THREAD

**Issue by alfrix** [libretro/RetroArch#6304]
Log is not dumped
`retroarch_debug.exe --verbose >> log.txt`

### Expected behavior

Log dumped to log.txt

### Actual behavior

Output is not dumped stays on the terminal

maybe related, RA doesn't seem to close, it just stays in this state
![captura](https://user-images.githubusercontent.com/1247237/36252832-afa1f19c-1224-11e8-9d3b-1780b3ee717c.PNG)

Win10x64 Fall Creators update
Retroarch lastest nightly

**Comment by ofry** [comment]
yes. same behavior on Windows 8.1.

same in cmd.exe shell, or MSYS bash shell, or cygwin shell.

**Comment by fr500** [comment]
--log-file log.txt -v

**Comment by ofry** [comment]
yes... but I think Retroarch should respect pipe redirecting commands, as other console programs.

**Comment by alfrix** [comment]
@fr500 that works but [the docs don't exhibit that](https://docs.libretro.com/guides/generating-retroarch-logs/) and regardless RA should respect the pipe redirection

I could have known that using --help but
retroarch.exe --help or -h doesn't work (no output)
retroarch.exe --version  doesn't work (no output)
retroarch.exe --features doesn't work (no output)

**Comment by fr500** [comment]
I know they don't, people were complaining incesantly that the console window was impossible to get rid of.
So now we compile with mwindows. No more default console window, now we allocate the console window but it's a bit too late for --help or --version.
You can still use redirection like this:

retroarch >> log.txt 2>&1

**Comment by markwkidd** [comment]
Could someone (@alfrix ?) file an issue at http://github.com/libretro/libretro-docs so that the Generating Log can get corrected.

The logs doc is new (and it seems like already it's a good idea to have since it is being referred to!)

I sourced it from what seemed to be the best material but if it's not accurate then I'll help fix

**Comment by retro-wertz** [comment]
i have been since using retroarch --verbose 2>&1 >> retroarch.log

**Comment by markwkidd** [comment]
OK I've submitted a PR for the logs doc that fixes the windows instructions. Please someone let me know if Linux or OS X instructions also need to be fixed. I'll leave this issue in peace for now.

**Comment by alfrix** [comment]
`retroarch --verbose 2>&1 >> retroarch.log` results in blank file and often misbehaves in powershell

@markwkidd i'll update the doc using `--log-file log.txt -v` among other things i'll tag you on the PR

I'll close this, but for anyone encountering this issue use:
`.\retroarch.exe --log-file .\retroarch-log.txt -v`
Or
`.\retroarch_debug.exe --log-file .\retroarch-log.txt -v`

**Comment by markwkidd** [comment]
Thanks @alfrix I'll keep an eye out for your PR
