### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by alfrix** [libretro/RetroArch#6305]
Retroarch spams this:

```[INFO] [GL debug (Low, API, Performance)]: API_ID_REDUNDANT_FBO performance warning has been generated. Redundant state change in glBindFramebuffer API call, FBO 0, "", already bound.```

And is all you can see in the terminal since #6304 is happening:

![captura2](https://user-images.githubusercontent.com/1247237/36253253-c16992c6-1225-11e8-93a7-188d549debdb.PNG)

Win10x64 Fall Creators update
Retroarch lastest nightly
Running Dolphin core

**Comment by alfrix** [comment]
The last lines are there because i closed RA, but if you grab the scrollbar all you see is that warning from top to bottom.

**Comment by Ferk** [comment]
Do you have a shader enabled? Sometimes with some shaders I get a lot of noisy warnings.

**Comment by twinaphex** [comment]
This should only happen with debug builds.

**Comment by alfrix** [comment]
Nope

**Comment by twinaphex** [comment]
With the debug build it will log all GL errors and warnings yeah.

**Comment by alfrix** [comment]
[I tested the Dolphin core which crashed on me, because i choose a gamecube rom without closing the playing wii game, and the log it's hilarious, not only does not have any useful info, it has 51 thousand lines spammed](https://gist.github.com/alfrix/6e95ecc603b90dda8b5441a06d772056)

**Comment by RobLoach** [comment]
As mentioned before, debugging verbosity will output EVERYTHING. Visit your settings and update it to match the following...

![screenshot at 2018-02-17 15-46-03](https://user-images.githubusercontent.com/25086/36345502-c3be2e26-13f9-11e8-9792-8ebc05885633.png)

**Comment by fr500** [comment]
That's just the core logs though, RA logs have no configurable levels.

**Comment by orbea** [comment]
@alfrix Is this still an issue?
