### ISSUE TITLE
где скачать игры ?!!!

### ISSUE THREAD

**Issue by aaza0000** [libretro/RetroArch#6310]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by hyarsan** [comment]
Either dump your own games or get it from the Content Downloader. Online Updater - > Content Downloader. Also, Github is not for asking help about RetroArch. There is a reason why you have to fill in the issue template. Downloading free paid games is **illegal**, don't do that. RetroArch is 100% legal but sadly we have to deal with such criminals.

**Comment by ofry** [comment]
Google, DuckDuckGo, Yandex and other search engines are best friends in your case. Sorry, we can't link to pirate sites there.
