### ISSUE TITLE
1.7.1 doesn't compile under Linux

### ISSUE THREAD

**Issue by KAMiKAZOW** [libretro/RetroArch#6317]
Something related to video_state_python:

`[   63s] CC gfx/drivers_tracker/video_state_python.c`
`[   64s] CC audio/drivers/oss.c`
`[   64s] gfx/drivers_tracker/video_state_python.c: In function 'py_read_input':`
`[   64s] gfx/drivers_tracker/video_state_python.c:131:13: error: 'current_input' undeclared (first use in this function); did you mean 'py_read_input'?`
`[   64s]        res = current_input->input_state(current_input_data, joypad_info,`
`[   64s]              ^~~~~~~~~~~~~`
`[   64s]              py_read_input`
`[   64s] gfx/drivers_tracker/video_state_python.c:131:13: note: each undeclared identifier is reported only once for each function it appears in`
`[   64s] gfx/drivers_tracker/video_state_python.c:131:40: error: 'current_input_data' undeclared (first use in this function); did you mean 'current_input'?`
`[   64s]        res = current_input->input_state(current_input_data, joypad_info,`
`[   64s]                                         ^~~~~~~~~~~~~~~~~~`
`[   64s]                                         current_input`
`[   64s] gfx/drivers_tracker/video_state_python.c: In function 'py_read_analog':`
`[   64s] gfx/drivers_tracker/video_state_python.c:159:10: error: 'current_input' undeclared (first use in this function); did you mean 'py_read_input'?`
`[   64s]     res = current_input->input_state(current_input_data,`
`[   64s]           ^~~~~~~~~~~~~`
`[   64s]           py_read_input`
`[   64s] gfx/drivers_tracker/video_state_python.c:159:37: error: 'current_input_data' undeclared (first use in this function); did you mean 'current_input'?`
`[   64s]     res = current_input->input_state(current_input_data,`
`[   64s]                                      ^~~~~~~~~~~~~~~~~~`
`[   64s]                                      current_input`
`[   64s] CC audio/drivers/alsa.c`
`[   64s] make: *** [Makefile:171: obj-unix/release/gfx/drivers_tracker/video_state_python.o] Error 1`

**Comment by hizzlekizzle** [comment]
No problem here. I guess you could try to --disable-python when you configure.

**Comment by KAMiKAZOW** [comment]
I did not change anything compared to 1.7.0 where Python was also enabled. Four different targets are equally affected: https://build.opensuse.org/package/show/home:KAMiKAZOW:Emulators/retroarch

**Comment by bparker06** [comment]
I've never seen the python support actually used (it never detects it for me anyway), I think it is safe to disable it.

**Comment by twinaphex** [comment]
This should hopefully fix it -

https://github.com/libretro/RetroArch/commit/5139241e87c5b11d852c573fbb951374d13a55f5

**Comment by KAMiKAZOW** [comment]
Works fine. Thx.
