### ISSUE TITLE
Incorrect playlist file being generated when scanning a directory

### ISSUE THREAD

**Issue by eyelasers** [libretro/RetroArch#6321]
When scanning a directory containing SNES ROMs, Nintendo\ -\ Super\ Nintendo\ Entertainment\ System\ Hacks.lpl is created, not Nintendo\ -\ Super\ Nintendo\ Entertainment\ System.lpl. This leaves a black box where the system and cartridge icons should be in the GUI. All of the ROMs in the playlist are also their original file names, and not the cleaned up names from the database. This is the only system this seems to happen for.

![snes-retroarch](https://user-images.githubusercontent.com/34557235/36450771-d5224d0e-1643-11e8-9ed9-6eae45463d9f.png)

I have bsnes v094 (Balanced) aea144e core and the most recent databases from the online updater.

This must have happened as of the last update, it wasn't happening in the previous stable build I got from the Ubuntu PPA last week. I reinstalled Ubuntu 17.10 last night and set up a fresh install of Retroarch and discovered the issue.

Git version: 6fc6bfb

Ubuntu 17.10

I am relatively new to Linux, so you may have to bear with me for follow up information.

**Comment by RobLoach** [comment]
Thanks for bringing this up. We had moved GoodTools entries over to the Hacks database to reduce the SNES database size. GoodTools includes pretty much everything (hacks, old versions, etc), while No-Intro is clean.

@twinaphex I think we could do a few things...

1. Rename the "Hacks" suffix to "Extras"
2. Make sure the image is in there for the assets

What do you think?

**Comment by eyelasers** [comment]
Sure thing. Looking at my files I've just realized that these ROMs are actually from a No-Intro source, so I'm not sure why they should be displayed as having GoodTools file names.

Thanks for looking into this!

**Comment by RobLoach** [comment]
Ah, perhaps they appear in both sources, finds it in Hacks, and then uses that.... Try deleting the Hacks rdb?

**Comment by jyggen** [comment]
I'm having the same issue, and deleting the Hacks rdb and rescanning does indeed create a "normal" SNES playlist with the roms.

**Comment by RobLoach** [comment]
Removing GoodSNES could be a thing:
https://github.com/libretro/libretro-database/pull/580

**Comment by eyelasers** [comment]
Deleting the hacks rdb did the trick, thank you!

**Comment by twinaphex** [comment]
Renaming Hacks to Extras could be a good solution, yes.

**Comment by RobLoach** [comment]
Just removed GoodSNES entirely. All it causes is issues.

**Comment by trumad** [comment]
Whereabouts can I find the rdb file? I'm running retroarch on FireStick.

**Comment by RobLoach** [comment]
You can run the Update Databases to retrieve the latest .rdb files.

**Comment by Indefiance** [comment]
On Firestick. Got to settings>directory>databases. Change the default directory to a location you have access to. Then go back to online updater and update databases. Quit retroarch to save settings. Start up and rescan your files.  Yo may have to delete your snes hacks playlist files under Esfile explore ( sdcard/Retroarch/playlist/)

**Comment by Pearate** [comment]
Deleting the "Nintendo - Super Nintendo Entertainment System Hacks.rdb" fixe the problem. But now,  how to delete the SNES Hacks Icon (Empty list) in the menu ? I just want to have the SNES icon.

**Comment by orbea** [comment]
This seems to be a fixed issue and if anyone has lingering issues they should remove the bad databases, playlists and then rescan the content.

If anyone still has any issues please let us know!
