### ISSUE TITLE
[HELP] Achievement!!

### ISSUE THREAD

**Issue by Carpierprogrammatore** [libretro/RetroArch#6326]
Hi guys
This is my first post here.
I'm a universary student and I'm trying to personalize the user interface of retroarch.
I want to remove/hide/disable the achievements voice of setting menu
I'm trying to remove it by file retroarch.cfg but I can't find it...

Someone have an idea? 

I use Lakka and the last Retroarch version.

**Comment by RobLoach** [comment]
achievements voice?

**Comment by Carpierprogrammatore** [comment]
in setting tab there is and entry about achievements... I want to remove that

**Comment by RobLoach** [comment]
If you compile with `HAVE_CHEEVOS=0`, it should remove it. Otherwise, it's part of the Settings menu. You could also just disable the settings menu entirely.

**Comment by Carpierprogrammatore** [comment]
I don't want to hide menu setting... when I'll try it see you if it is right
Do you know also to hide entry of user interface?

**Comment by Carpierprogrammatore** [comment]
I'm sad... HAVE_CHEEVOS doesn't work...
I tried to compile it in retroarch.cfg but it doesn't work...

**Comment by RobLoach** [comment]
You won't be able to remove the Achievements without recompiling RetroArch.

```
git clone https://github.com/libretro/RetroArch.git
cd RetroArch
./configure --disable-cheevos
make
```

**Comment by Carpierprogrammatore** [comment]
sorry Rob... I want to hide it, not to disable... I don't want to see it in the settings menu

**Comment by Ferk** [comment]
Disabled from the compilation means it would be removed completely.

Are you aware that compiling means basically rebuilding the program from its source code?

You cannot do this with the retroarch program you downloaded, you need to build your own from the source code in this repo. There is no option to remove options.

**Comment by fr500** [comment]
You can either have it, or not, we can't go catering for every single obscure usecase sorry.

**Comment by RobLoach** [comment]
Suggest going the hide password route instead. Disabling the menu seems like you're solving the wrong problem.

**Comment by hyarsan** [comment]
Here's another idea, maybe you need to enter a password in order to enter the menu?

**Comment by Carpierprogrammatore** [comment]
I don't want to disabe menu because I want to see WI-FI settings ands another likes input or audio...

**Comment by Ferk** [comment]
But what is the point of hiding that option? is it bad that it exists?

If your problem is that the password is shown then #6149 would be the right way, it stores the token rather than the password. Otherwise anyone checking your retroarch.cfg can see the password anyway, no matter if you hide it from the menu.

**Comment by Carpierprogrammatore** [comment]
It's a universary project. I have to create a retroconsole games by
retroarch and when it will be over it bust be "salable"
somthing like that

2018-02-26 19:04 GMT+01:00 Fernando Carmona Varo <notifications@github.com>:

**Comment by Ferk** [comment]
For it to be "saleable", you should remove all the cores that have non-commercial license.

On the other hand the retroachievements option does not make it non-"saleable". But if it really is a university project it would have more value if you actually spend the time and effort into recompiling and rebuilding from source code, like suggested above.

**Comment by Carpierprogrammatore** [comment]
where is the source code?


2018-02-26 19:51 GMT+01:00 Fernando Carmona Varo <notifications@github.com>:

**Comment by hyarsan** [comment]
Go over to the code tab on Github...

**Comment by Carpierprogrammatore** [comment]
what's the correctly repository?


2018-02-26 21:07 GMT+01:00 Yarsan Hoessain <notifications@github.com>:

**Comment by hyarsan** [comment]
This one is correct

**Comment by Carpierprogrammatore** [comment]
what?

**Comment by hyarsan** [comment]
What is so hard about it? https://github.com/libretro/RetroArch

**Comment by Carpierprogrammatore** [comment]
where is the correctly fly :(

**Comment by hyarsan** [comment]
This is the correct source code.

**Comment by Carpierprogrammatore** [comment]
oh... okay :)


2018-02-27 0:24 GMT+01:00 Yarsan Hoessain <notifications@github.com>:

**Comment by fr500** [comment]
We don't want to deal with anyone selling or producing commercial products with RetroArch even if it's for homework.
