### ISSUE TITLE
can you make citra core compatible with ps vita

### ISSUE THREAD

**Issue by greggameplayer** [libretro/RetroArch#6330]
Hello, is it possible to make citra core compatible with ps vita because it's would be so great to be able to run some 3ds games on ps vita

**Comment by hizzlekizzle** [comment]
No, Vita doesn't have OpenGL, which is a requirement for Citra.

**Comment by rsn8887** [comment]
https://github.com/Rinnegatamante/vitaGL

**Comment by hizzlekizzle** [comment]
Yeah, it's not nearly fast enough.

**Comment by greggameplayer** [comment]
yeah but i think it can work nice with base 3ds resolution
