### ISSUE TITLE
can you make a ps2 core like pcx2 compatible with ps vita

### ISSUE THREAD

**Issue by greggameplayer** [libretro/RetroArch#6331]
Hello, is it possible to make a ps2 core like pcsx2 compatible with psvita. The ps vita has the required power in order to run it.

**Comment by hizzlekizzle** [comment]
We don't have a PS2 core at all. If we did, I don't suspect Vitas would be strong enough to run it.

Both of the cores you've mentioned barely run on top-of-the-line desktop PCs, so there's no way they would run on a Vita.
