### ISSUE TITLE
Zelda - Majora's Mask Random Freezes

### ISSUE THREAD

**Issue by just2mad** [libretro/RetroArch#6342]
## Description

Playing Zelda - Majora's Mask in Lakka.tv or Batocera with Retroarch + Parallel-N64 + Glide64 has random freezes. The game suddenly stucks and I have to connect through ssh and kill the retroarch process. I can not reproduce the issue, as it happens irregularly. I use the standard config coming with lakka.tv and tested with HP Elitebook 820 G1 and a Mac Book Air.

**Comment by fr500** [comment]
Please read the template, next time.

This is a core issue you should have reported it in the correct issue tracker.

**Comment by fr500** [comment]
You can find the mupen repo here:
https://github.com/libretro/mupen64plus-libretro
