### ISSUE TITLE
Broken dependency - menu_list.h needed

### ISSUE THREAD

**Issue by felinben** [libretro/RetroArch#6343]
## Description

Make stops because of a missing library menu_list.h

### Expected behavior

Complete compiling

### Actual behavior

Compiling fails:
 make: *** No rule to make target `frontend/drivers/../../menu/widgets/menu_list.h', needed by `obj-unix/release/frontend/drivers/platform_unix.o'. Stop.

### Steps to reproduce the bug

./configure --prefix=/path/to/my/binaries
make

### Bisect Results

((bisect/bad~1)|BISECTING) $ git bisect visualize --stat
commit 8d9fbf4a62fac8c7e81787c1f82317d99c1cdc40
Author: twinaphex <libretro@gmail.com>
Date:   Sun Feb 25 00:50:01 2018 +0100

    Cleanups

 menu/menu_event.c | 23 ++++++++++++++---------
 1 file changed, 14 insertions(+), 9 deletions(-)

commit 36f9d359c2a39cc9db8ad0fcb9977d2a82ae6d6e
Author: twinaphex <libretro@gmail.com>
Date:   Sun Feb 25 00:39:20 2018 +0100

    Combine menu_list and menu_entries

 Makefile.common           |   1 -
 griffin/griffin.c         |   1 -
 menu/cbs/menu_cbs_left.c  |   3 +-
 menu/cbs/menu_cbs_right.c |   3 +-
 menu/drivers/xmb.c        |   2 +-
 menu/menu_displaylist.c   |   4 +-
 menu/menu_driver.c        |   2 +-
 menu/menu_entries.c       | 193 +++++++++++++++++++++++++++++++++++++++++-
 menu/menu_entries.h       |  27 +++++-
 menu/menu_networking.c    |   1 -
 menu/widgets/menu_list.c  | 212 -----------------------------------------------
 menu/widgets/menu_list.h  |  75 -----------------
 12 files changed, 223 insertions(+), 301 deletions(-)

### Version/Commit

- RetroArch: 36f9d359c2a39cc9db8ad0fcb9977d2a82ae6d6e

### Environment information

- OS: Ubuntu 14.04.5 LTS
- Compiler: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4

**Comment by twinaphex** [comment]
Should be fixed already.

**Comment by felinben** [comment]
commit 33f0009a1186755c5acaad8f293e33e3de99a04c fixed it
Cheers!
