### ISSUE TITLE
Duplicate keys problem

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#6344]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Duplicate key events are sent on some cores if retropad keys are mapped to the keyboard and the core/game uses those keys.

### Expected behavior
Retropad key presses by default 'consume' the event and don't allow sending the other, because by configuring the retropad to that key the user is signalling those keys are acceptable sacrifices.

If you want to allow the press of keys configured on retropad, the user can always set the retropad to 'None'. Another alternative would be that this filtering behavior only occurs during 'game focus mode', but i'm actually slightly against this idea because 'game focus mode' is often used as a way to *prevent* RA bindings to interfere with the keyboard, not the opposite.

### Actual behavior
Something like this https://github.com/AZO234/NP2kai/issues/31 happens in some games and cores.

### Steps to reproduce the bug
In the link.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by dankcushions** [comment]
Yes, we have this problem in mame2003 also. If you have an IPAC type device that maps an arcade stick to a keyboard interface, hitting 'right' on the stick will count as a press of 'keyboard_right' and 'dpad_right', and other such behaviour. it messes up input in some games.

**Comment by Tatsuya79** [comment]
The default keyboard keys that control the retropad are in retroarch.cfg.
You can change input_player1_up = "up" to input_player1_up = "nul" if you want to disable that.
You can also make a np2kai core override with all those binding disabled or changed.

**Comment by dankcushions** [comment]
yes this has been the workaround, that retropie/IPAC users use, but I'm in two minds as to whether the current behaviour should happen. if a core is listening out for keyboard and retropad abstraction, and a user presses a key that is bound to a retropad abstraction, should retroarch send both to the core? should the core work out which to use?

i'm not sure if sending both would ever be useful, but that's what the default .cfg has for the arrow keys, for example; they are bound to retropad dpad, and also as regular keyboard keys: https://github.com/libretro/RetroArch/blob/master/retroarch.cfg#L476

**Comment by i30817** [comment]
But i *don't* want to disable the retropad. The retropad keyboard bindings i choose are fine to me, the problem is the duplicate, which the game/apps interpret when I actually want them ignored.

**Comment by JabberwockPL** [comment]
This behavior messes up Atari800 emulation as well on my device which has only keyboard inputs. For example arrow keys are sent both as a joystick input and as keys. But a game like Bruce Lee has hardcoded pause on ANY keyboard input...

The additional problem with that core is that if it detects key input, it ignores the RetroPad one, but that is incorrect on their side (but of course this problem would be solved if Retroarch swallowed key inputs assigned to RetroPad).
