### ISSUE TITLE
Menu input code completely broken

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#6346]
## Description

Menu input is completely screwed up in the latest builds, moving left-right doesn't work (tested on XMB) until loading content, after loading content it seems to work fine again

### Expected behavior

Moving left / right should move left / right

### Actual behavior

left is doing the same action as L1, right is doing the same action as R1

### Bisect Results

haven't bisected but it was all good at b2c3a2c

### Version/Commit

- RetroArch: 1.7.1 head

### Environment information

- OS: Android
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
I can reproduce this bug. Can't say for sure yet what causes it. Must be something hashes-related again, although it's annoying how this only happens on Android without us knowing WHY.

**Comment by twinaphex** [comment]
OK so here is another weird thing -

* go into Core Updater
* back out again to the Main Menu

now you will find you can move left/right again.

Also, I see no assets being configured on first install, so I just see black icons in XMB. This happens to you too?

**Comment by twinaphex** [comment]
This should be fixed as of this commit -

https://github.com/libretro/RetroArch/commit/8b8b08aefdbed57f3aa975bde227a35c22752773
