### ISSUE TITLE
Network Information info is blank until first network operation

### ISSUE THREAD

**Issue by celerizer** [libretro/RetroArch#6352]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

https://i.gyazo.com/ae509f0f84d9fe75078fb8a4c0b70198.png

**Main Menu > Information > Network Information** is not initialized until at least one network operation has been made. This apparently causes crashes when attempting to join LAN netplay lobbies.

Using an option that utilizes network automatically, this doesn't happen (Network Gamepad fixes the issue, logging into RetroAchievements fixes the issue once content is loaded).

### Expected behavior

The info should be retrieved on startup and visible from the menu.

### Actual behavior

The friendly name of each adapter is shown but its info is not.

### Steps to reproduce the bug

1. Navigate to **Main Menu > Information > Network Information**, see blank info
2. Enter Core Updater
3. Return to Network Information, info is populated

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.1 stable, and compiled from master

### Environment information

- OS: Windows 7 (radius confirmed with 10)
- Compiler: MinGW, as well as MSVC stable downloaded from the site

**Comment by fr500** [comment]
This happens because network is never initialized by default. It should be initialized as a part of the startup process

**Comment by twinaphex** [comment]
This longstanding issue should finally be addressed by this - 

https://github.com/libretro/RetroArch/commit/3d731aec1943d2deca03d68077629e42491068cc

Sorry for keeping everybody waiting for so long before addressing this.
