### ISSUE TITLE
[Android] XMB doesn't scale properly

### ISSUE THREAD

**Issue by ClockworkTomato** [libretro/RetroArch#6367]
When Retroarch is launched from portrait orientation the menu is not scaled properly, and everything is too tiny. From landscape everything is scaled properly.

[Here's the topic I created on the Libretro forum about this issue](https://forums.libretro.com/t/issue-with-ui-scaling-when-using-retroarch-in-portrait-mode/14981) (I won't post the whole thing here as it contains a number of pictures and I'd clutter the page).

My uneducated guess is that the XMB scales depending on the horizontal size of the screen (i.e. it tries to fit a certain amount of columns on the screen), which makes everything too tiny when that dimension is the smaller one.
If my guess is correct, then scaling the menu depending always on the bigger size (between vertical and horizontal) rather than on the horizontal size would fix the issue on landscape without affecting any other kind of display.

**Comment by Tatsuya79** [comment]
I think xmb needs to refresh its height and width values on orientation change.
But I'm not sure it can recalculate all the scaling without a reboot.

**Comment by ClockworkTomato** [comment]
Not really, take a look [at the picture in the link](https://forums.libretro.com/t/issue-with-ui-scaling-when-using-retroarch-in-portrait-mode/14981/2): the landscape scaling is perfect even if afterwards you rotate the screen to portrait; instead, the portrait scaling is too small even on portrait.

My suggestion would be using the landscape scaling regardless of how the phone is oriented, as it fits both orientations perfectly (at least on a 16:9 phone).

**Comment by Tatsuya79** [comment]
It's not perfect: just open the video settings and your right column will be out of the screen.

**Comment by ClockworkTomato** [comment]
Ok, maybe not perfect, but the current portrait scaling is way to small to be comfortable to use on a 5 inches device.

**Comment by Tatsuya79** [comment]
It's designed for 16:9 landscape and can't scale better than that in portrait I'm afraid.
GLUI/Material UI is the one designed with phones in mind.

**Comment by sonninnos** [comment]
There has been some scaling adjustments which most likely sorted these issues out.
