### ISSUE TITLE
Native 15khz CRT Support in Retroarch

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#6368]
I'm creating this issue so folks can pledge new bounties for this project: https://forums.libretro.com/t/retroarch-native-15khz-crt-support-bounty-suggestion-50/10124

Because the prior github issue was closed the bounty system doesn't seem to be working.

**Comment by alphanu1** [comment]
I have created the PR. ALL is done.

**Comment by markwkidd** [comment]
@alphanu1 Nice! Once I get the word from libretro dev that your work has been accepted I'll close this issue and you can begin the claim process for your bounty.

**Comment by markwkidd** [comment]
The Linux version was just submitted via this PR: https://github.com/libretro/RetroArch/pull/6655

In my opinion that more than meets the criteria of the bounty, so I'm closing this issue in order to allow @alphanu1 to begin the claim process.
