### ISSUE TITLE
Remove RetroPad w/ Analog

### ISSUE THREAD

**Issue by Hedonium** [libretro/RetroArch#6369]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

![retroarch_debug_2018-03-07_19-21-35](https://user-images.githubusercontent.com/34848002/37125967-e1da6216-223c-11e8-81a2-0f03179f82d1.png)

The RetroPad w/ Analog device type doesn't seem to do anything useful and or different from the RetroPad device type.

Let's remove it to reduce end-user confusion.

https://github.com/libretro/RetroArch/blob/master/menu/menu_setting.c#L530

**Comment by markwkidd** [comment]
Is there any reason to ever not set this on "RetroPad w/Analog"?
