### ISSUE TITLE
Buffer underflow in audio_driver_sample_batch_rewind

### ISSUE THREAD

**Issue by LIJI32** [libretro/RetroArch#6382]
`audio_driver_sample_batch_rewind` can corrupt memory if  `audio_driver_rewind_ptr` underflows, potentially crashing RetroArch or corrupting core data while rewinding. (See LIJI32/SameBoy#42)

**Comment by twinaphex** [comment]
Check if this is a potential fix - 
https://gist.github.com/twinaphex/d2465ebefcc50f0572dfb1b32f98ab5b

**Comment by LIJI32** [comment]
Mmm, I didn't realize you were waiting for me for this bug. I'll try testing it tomorrow, I don't have a RetroArch repo ready-to-compile right now.

**Comment by xTMODx** [comment]
@LIJI32 any testing done yet?

**Comment by twinaphex** [comment]
Yeah, I'd very much appreciate a confirmation whether or not this is fixed now. if not, maybe you could give me a diff patch that solves it instead?

**Comment by LIJI32** [comment]
After adding this patch this crash no longer occurs. (Tested on macOS with `libgmalloc`)

Without the patch, `libgmalloc` causes RetroArch to crash instantly as soon as the rewind button is hit.

**Comment by xTMODx** [comment]
is it solved now @LIJI32 @twinaphex ? i would like to see it done :) so it wont crash anymore

**Comment by LIJI32** [comment]
Yes, apply the patch and it should do it. :)

**Comment by twinaphex** [comment]
Applied this diff -

https://github.com/libretro/RetroArch/commit/726de8e447d9a688751b8e8373c7a91078e824a8

I guess we can close it now. Let me know if it still occurs @LIJI32 if necessary on Discord, I can reopen this issue then.
