### ISSUE TITLE
RetroArch Nightlies crashes

### ISSUE THREAD

**Issue by torben656** [libretro/RetroArch#6383]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When I run the retroarch nightlies downloaded from the buildbot. It crashes

### Version/Commit
You can find this information under Information/System Information

- RetroArch: latest nightly 2018-03-11

### Environment information

- OS: [The operating system you're running]
Windows 10 AMD A4-6300 APU with Radeon Graphics 2GB RAM 32-Bit Operating System

**Comment by hizzlekizzle** [comment]
Did you update your redist libs? We updated the buildbot recently, so some of the dependencies updated, as well.

**Comment by torben656** [comment]
it works now, thanks!
