### ISSUE TITLE
Leaderboards (Raspberry Pi) 

### ISSUE THREAD

**Issue by enzyme-1** [libretro/RetroArch#6384]
[_**Reposted from RASuite:**_](https://github.com/leiradel/RASuite/issues/28) This issue is in regards to the leaderboard for [Batman](http://retroachievements.org/Game/1458) and it's inability to follow the '**_cancel_**' command when activated in RetroArch/RPi. The cancel command was changed to the current input when the score was found to multiply or add after resetting the game without losing a life. The new condition works and resolved the score adding on the RANes, but I am now getting reports that this is still happening in RetroArch.

This also tells me that the command line for cancel may be being ignored for all leaderboards on RetroArch, but maybe only NES titles? I didn't have time this week to find a solution to resolve this, but I was looking around for anything related to this and decided to post here as an official troubleshooter (could be applied to all leaderboards concerning RPi). I will continue to post to this topic and edit this lead post as a reserved post if I find anything, but if anyone has any idea what is happening with RetroArch and leaderboards, feel free to add any helpful tips.

**Comment by meleu** [comment]
Maybe @celerizer would be interested on this issue...

**Comment by enzyme-1** [comment]
It seems like leaderboards can't be supported in RetroArch if this problem persists. Without using cancel, we can't tell the leaderboard to stop adding the score if a player changes the difficulty of the game, resets it, or enters in a password. Now we have everyone using it just to play Atari 2600 and Arcade, so we have to go about this differently.

**Comment by enzyme-1** [comment]
The guy who reported it originally is saying when he plays the game in RPi, it's leaderboard does not reboot along with the game (it just adds to it's score), I think there were other leaderboards which have been reported with the same issue. The current condition in it's cancel command is supposed to be triggering upon the title screen.
