### ISSUE TITLE
Xbox One Controller - Hotplug issue 

### ISSUE THREAD

**Issue by LasagnaPie** [libretro/RetroArch#6402]
When my Xbox One Controllers are turned off then on again,  they no longer work in Retroarch,   so unable to continue the current game i am playing and i don't have access to Mouse/Keyboard.

I am using the latest Retroarch Nighty Build that i launch through Steam's Big Picture interface on Windows 10.

**Comment by RobLoach** [comment]
There have also been some updates in the autoconfig for Xbox One. Mind re-testing, and submitting with the issue template, as fr500 requested? Closing this one for now.
