### ISSUE TITLE
Vulkan + X11 corrupts emulator core memory

### ISSUE THREAD

**Issue by bearoso** [libretro/RetroArch#6406]
It looks like the vulkan driver is writing to the wrong memory or overflowing a buffer somewhere. Don't have Wayland, but from what the other bugs say this is only related to the X11 platform.

Issue 4575 reports this occurring in the mednafen PSX core, and I've reproduced that. From the post history it looks like speculation was that it was a core bug, but I've discovered that to be incorrect.

I've also now seen it with the Desmume core, where when loading it with the Vulkan driver, the battery RAM is corrupted and unable to load.

So it seems to be reproducible where it corrupts specific areas of the core memory, so I'm presuming an offset is wrong somewhere, or it's reusing a core pointer for the wrong purpose and overflowing that.

This is with RetroArch 1.7.1, compiled by myself in both gcc 7.3 and clang 5.0.1, which both produce the issue, and X11/Vulkan. From what I can see, Windows' vulkan driver is unaffected.

**Comment by bearoso** [comment]
Yep, this XWindowAttributes struct looks correct, doesn't it? Wait a sec...

`$2 = {x = -867996884, y = 32767, width = 1465093920, height = 21845, 
  border_width = -8144, depth = 32767, visual = 0x7fffca2b5395
     <_MMU_ARM9_write16(unsigned int, unsigned short)+5621>, 
  root = 140737488347184, class = -903151616, bit_gravity = 67113068, 
  win_gravity = 1370423076, backing_store = 564304489, 
  backing_planes = 288248432194224132, backing_pixel = 2413790589486834705, 
  save_under = -1, colormap = 43946105372672, map_installed = 1443260192, 
  map_state = 21845, all_event_masks = 140737488347232, 
  your_event_mask = 93824994301419, do_not_propagate_mask = 140737488347536, 
  override_redirect = 1452274432, screen = 0x45}`

**Comment by hizzlekizzle** [comment]
> <_MMU_ARM9_write16(unsigned int, unsigned short)+5621>

Seems legit. Srsly, though, thanks for digging into this. As you noticed, it's a longstanding issue but nobody actually knew what was up.

**Comment by bearoso** [comment]
What I've discovered at the moment is that, after a certain point, everything seems to be getting a file descriptor number 0 (stdin) when open is called. This affects X opening displays, shared memory contexts, etc, and any time something tries to use a file it clobbers something else.

**Comment by bearoso** [comment]
Found it. See pull request #6414.

**Comment by twinaphex** [comment]
Very cool that you managed to track this down. I know of some other cores that were affected by this, such as Beetle PSX HW.

Would this also fix the same Vulkan corruption issues when only X11 is used instead of Wayland?

**Comment by bearoso** [comment]
> Would this also fix the same Vulkan corruption issues when only X11 is used instead of Wayland?
If the Wayland driver is compiled out, no. Doing that would also have fixed this. But since Wayland Vulkan support came before X11 Vulkan I doubt many have done that. 

I'm not aware of any other Vulkan X11-only corruption issues unless you point them out to me.
