### ISSUE TITLE
'fast forward.' message is not show.

### ISSUE THREAD

**Issue by gozz6270** [libretro/RetroArch#6408]
(I'm not good at english, I want you to understand my odd sentence. sorry.)

I use sx09re ver 1.6.4.
when I push fast forward button, 'fast forward.' message is not show.

I found issues same it. and read solution.
but I don't understand how to do it.

how to revise retroarch.c and intl/msg_hahs.ko.h ??
Does it need linux or coding program??
 I just window user, and not programmer.

**Comment by fr500** [comment]
Sorry but...
What is sx09re ver 1.6.4?

There is an issue template there for a reason, please fill it up next time.

**Comment by gozz6270** [comment]
I'm sorry about not using template. I will do it next time.

I just want to know how to compile relating 
https://github.com/libretro/RetroArch/pull/5677
