### ISSUE TITLE
Overlay stacking

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#641]
I was discussing with @twinaphex the possibility of having separate overlay layers, for example on some platforms overlays are being used successfully for borders or for scanlines.

It would be good if it could be possible to separate "general purpose" overlays from input overlays. General purpose overlays could be used to show retropad mapping for an specific core, borders, etc.

**Comment by twinaphex** [comment]
I don't think this is a realistic request, we can only pile on so much on top of the current overlay system. So I'm closing this, and there might be better ways of doing this now besides.
