### ISSUE TITLE
[Android] Not being able to change playlist entries' names

### ISSUE THREAD

**Issue by Danver2618** [libretro/RetroArch#6420]
### Description
When I try to rename a playlist entry, the name doesn't get changed but stays what it was before. For instance, if an entry is named Super Mario World (USA), and if I try to change it to name Super Banzai World, it does not change and remains the same.

### Expected behavior
It should change to the new name.

### Actual behaviour
The name does not change but stays what it was before.

### Steps to reproduce the bug
1. Go to a playlist and select an entry
2. Choose rename
3. Try to rename it
4. Confirm

### Version/Commit
- Git version: 1e37cd7
- RetroArch: 2018-03-18-RetroArch_staging.apk
Build Date: Mar 18 2018

### Environment information
- OS: Android
- Compiler: Clang/LLVM (3.8.256229) 32-bit

**Comment by Papermanzero** [comment]
Why not changing the name directly in the playlist?

**Comment by Danver2618** [comment]
I didn't changed it outside of RetroArch. Maybe I wasn't clear enough. If a file gets scanned as Super Mario World (USA) like some ROM hacks which are not in the database, I try to rename it (directly in the playlist) Super Banzai World but it stays Super Mario World (USA)
