### ISSUE TITLE
[Windows] GPU screenshot option broken using D3D

### ISSUE THREAD

**Issue by trostboot** [libretro/RetroArch#6427]
## Description

Taking screenshots is broken when using D3D video drivers while having the GPU screenshot option enabled.

Taking a GPU screenshot using D3D9 results in RetroArch crashing.
D3D11 doesn't crash, but only produces a black image.
Cannot test D3D12 as that crashes on startup.

Works as expected using Vulkan.

### Version/Commit

- RetroArch: Git version d51048b0df (Mar 4 2018)

### Environment information

- OS: Win10 Pro 16299 
- GPU: GTX 1080 (driver 391.01)

**Comment by gouchi** [comment]
It will be nice to have this feature so that AI translation can work with hardware accelerated core.
