### ISSUE TITLE
Pop_OS! retroarch is freezed from startup

### ISSUE THREAD

**Issue by keiem** [libretro/RetroArch#6432]
I installed retroarch + cores from the official ubuntu PPA.
When I launch retroarch from the terminal, it starts up without errors, but I can't do anything, it doesn't respond on keyboard or mouse input.  

System: acer aspire P3 with intel core i3 and intel graphics.

**Comment by RobLoach** [comment]
Could you try running it from the command line, and posting the results here?

```
retroarch --verbose
```

**Comment by bparker06** [comment]
Make sure your user account is part of the `input` group so that you can access udev for keyboard/mouse/joypad support.

**Comment by keiem** [comment]
You are right, it has something to do with permissions and udev. retroarch --verbose revealed:

[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?

although adding my user to the input group didn't help.

**Comment by keiem** [comment]
thanks to the --verbose flag i discovered this:

[WARN] [udev]: Couldn't open any keyboard, mouse or touchpad. Are permissions set correctly for /dev/input/event*?

although adding my user to the input group didn't help.
