### ISSUE TITLE
D3D11/12 slang shaders are upside down

### ISSUE THREAD

**Issue by hyarsan** [libretro/RetroArch#6434]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

In the D3D11 or 12 video drivers, the shaders cause the video to be upside down
![upsidedownd3dgeom](https://user-images.githubusercontent.com/32988993/37735469-73ac68e4-2d4e-11e8-841a-7d1512b136b1.png)

### Expected behavior

Slang shaders looking like they are supposed to, without being upside down

### Actual behavior
Slang shaders make the video look upside down

### Steps to reproduce the bug

1. Turn on D3D11 or D3D12 video drivers
2. Load core with content
3. Turn on any shader ( this seems to happen with all ) Examples include crt-geom, pixellate...

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- Latest Nightly ( 21st of March 2018 )

### Environment information

- OS: Windows 10 64-bit
- Compiler: MinGW 64-bit from the buildbot

**Comment by trostboot** [comment]
I had noticed similar issues (although it was only affecting some shaders and not others). I'd venture a guess that either bb972a6dab0b6fe382acd9335df51486f4b5eb5b or ff6d24cbefa3e3e100bed434b3efb9bf6d2facec are the culprits here.
It's not happening on the build I'm using currently (d51048b0df812592869ecb62ac25aaf15134c34a, Mar 4th), but is happening on builds shortly after that date.

**Comment by twinaphex** [comment]
Pushed a commit which hopefully should address this issue - this of course will mean that all the Shadertoy shaders are now upside down but oh well...

@hunterk @aliaspider I will really need some help here in fixing a lot of these Shadertoy shaders. I think as soon as one general fix is found, I could do the remainder of all the shaders in terms of fixing them. I just need it fixed in one shader as an example.

**Comment by hizzlekizzle** [comment]
@twinaphex I think for the upside down part, you just need to replace:
```
  vec2 FragCoord = vTexCoord.xy*global.OutputSize.xy;
  FragCoord.y = -FragCoord.y;
```
with:
`vec2 FragCoord = vec2(vTexCoord.x, vTexCoord.y)*global.OutputSize.xy;`

**Comment by trostboot** [comment]
Can confirm, back in working order again.
