### ISSUE TITLE
Retroarch doesnt apply in game settings to game in FBA Arcade game

### ISSUE THREAD

**Issue by cecilmax** [libretro/RetroArch#6440]
I use retroarch 1.7.1 on Wii with FBA core to play gaia crusaders. I set the key to enter into diagnostic mode inside the game. When I go into game options in retroarch to change dip switch like number of lives, set continue on/off it keep settings in retroarch but when I check in the game the settings are still on default. Only free game play working...

I checked on Windows with FBA with the same game rom and when I change settings dip switch, it work for all settings.. it is like retroarch doesnt "apply" the changes to the game settings.

**Comment by fr500** [comment]
Report it on the FBA issue tracker. 
First line of the issue guidelines reads:

`- Only RetroArch bugs should be filed here. Not core bugs or game bugs`

The issue tracker is here:
https://github.com/libretro/fbalpha/
