### ISSUE TITLE
WiiU Netplay not working

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#6443]
## Description

WiiU Netplay fails to initialize, basically it prints "Waiting for client" "Failed to initialize netplay".

### Expected behavior

Netplay should work normally

### Steps to reproduce the bug

1. Start a game
2. Start netplay

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
@GregorR 

I looked at changes that could affect this, even tried rolling them back to no avail.
What I found is that it fails here:

https://github.com/fr500/RetroArch/commit/13f23016e0d0537b1e915f16a4fcade5a71ddb55#diff-e4176a14082452fd742a6969c6b9c5a7R460

Any idea of what could be wrong?

**Comment by GregorR** [comment]
Erm... I'm not sure how I'm supposed to get a "here" out of that commit...

**Comment by GregorR** [comment]
OH, I understand now, it's highlighting a line!

But init_socket hasn't changed.

**Comment by fr500** [comment]
Yeah I dunno...
It worked "fine" a few months back, as in it would connect and disconnect properly.

I added more logs now, I'm about to run it again.

**Comment by fr500** [comment]
This line
https://github.com/fr500/RetroArch/blob/master/network/netplay/netplay_init.c#L136
Is returning 8 `EAI_NONAME`

**Comment by twinaphex** [comment]
Does this still happen or has this been resolved?

**Comment by ReiOsumi** [comment]
The bug is still not fixed :c

**Comment by fr500** [comment]
Indeed it hasn't been fixed

**Comment by twinaphex** [comment]
@aliaspider Any ideas here?

**Comment by aliaspider** [comment]
I wasn't aware that it worked before. it always failed with those errors last I checked.

**Comment by morpheousx** [comment]
which version did netplay work on?  fr500 stated it once worked...

**Comment by twinaphex** [comment]
It really sucks this no longer works. @aliaspider could you and ohters maybe get together to see if we can get this working? Radius was able to get this to work on WiiU quite easily months ago, there must be a way to get this to work again.

**Comment by twinaphex** [comment]
I think we can close this now fortunately.
