### ISSUE TITLE
[Android] F-Droid builds problem

### ISSUE THREAD

**Issue by xTMODx** [libretro/RetroArch#6446]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I can't update the libretro repository in F-Droid.

### Expected behavior

F-Droid can update the repository so i can download the nightlies.

### Actual behavior

I get this error message

![screenshot_20180323-235704](https://user-images.githubusercontent.com/19918301/37856682-0bdfef98-2ef6-11e8-88b8-beb2523fbf03.jpg)

### Steps to reproduce the bug

1. [First step]
add this to F-Droid repositories
http://fdroid.libretro.com/
2. [Second step]
update F-Droid repositories

### Bisect Results

My last update was 03.03.2018 i try to update every few days so it could have started a few days after.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.7.1_GIT/59dae25]

### Environment information

- OS: [Android 7.1]

**Comment by ItachiSan** [comment]
I have the same issue.

**Comment by twinaphex** [comment]
I don't know how to fix this. Any suggestions/recommendations?

**Comment by BenMcLean** [comment]
I have the same issue.

**Comment by ItachiSan** [comment]
@twinaphex I believe it is a signature mismatch between certificates...
Although I have many doubts about this.

The first googled thing is: https://f-droid.org/en/docs/Signing_Process/
Which, with a quick look, says that the certificate for signing the repository file and the APK should match.

It was a quick search and have by far more experience with Linux packaging than Android one, but I suppose the issue is similar (package and repo file with different signature).

**Comment by xTMODx** [comment]
What if you try to remove the app from f-droid and add it again?

**Comment by BenMcLean** [comment]
The problem isn't with the RetroArch app: it's with the RetroArch F-Droid repository.

**Comment by twinaphex** [comment]
And we need help with it to fix it again.

**Comment by ItachiSan** [comment]
@twinaphex @hizzlekizzle where should I contact you? :smile:

**Comment by hizzlekizzle** [comment]
@ItachiSan probably easiest to come to discord or IRC. We have the libretro discord or #retroarch on Freenode IRC.

**Comment by xTMODx** [comment]
Thanks @ItachiSan for fixing it, now updates with F-Droid are working fine here.

**Comment by BenMcLean** [comment]
Works for me too. Thanks!
