### ISSUE TITLE
I have MGS discs 1 and 2 as version 1.0 but retroarch says version 1.1?

### ISSUE THREAD

**Issue by voorhees1331** [libretro/RetroArch#6459]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Which one is right here, and does it matter what version it is? Am I missing anything with 1.0 that I would be getting with 1.1? Just weird that it says Metal Gear Solid (U) version 1.0 as the .bin/.cue name but then retroarch has it as version 1.1
### Expected behavior

for it to say Metal Gear Solid (U) Version 1.0 

### Actual behavior

It says version 1.1

### Steps to reproduce the bug

N/A? Not sure if it's a bug
### Bisect Results

Yesterday

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Version 1.6.7
### Environment information

- OS: Windows 10
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
I don't think this qualifies as an issue.
