### ISSUE TITLE
Segfault in Linux KMS mode with latest Nightly build

### ISSUE THREAD

**Issue by TylerLoch** [libretro/RetroArch#6465]
## Description

With the latest nightly from the Ubuntu official libretro PPA, RetroArch immediately segfaults on launch before the UI is displayed in KMS mode from the commandline.
Launching via X still works fine.

### Expected behavior

RetroArch to display its UI (rgui, xmb, etc) upon launching from a basic text commandline.

### Actual behavior

[INFO] RetroArch 1.7.2 (Git aa5525f)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Mar 25 2018
[INFO] Version: 1.7.2
[INFO] Git: aa5525f
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ fullscreen
error: XDG_RUNTIME_DIR not set in the environment.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[WARN] Failed to bind API (#1, version 0.0) on context driver "ÄH¿É‡˛É¿
√".
error: XDG_RUNTIME_DIR not set in the environment.
[WARN] [SDL_GL]: Failed to initialize SDL gfx context driver: No available video device
[WARN] Failed to bind API (#1, version 0.0) on context driver "khr_display".
[INFO] [GL]: Found GL context: null
[INFO] [GL]: Detecting screen resolution 320x240.
[INFO] [GL]: Vendor: (null), Renderer: (null).
[INFO] [GL]: Version: (null).

### Steps to reproduce the bug

1. Ubuntu 17.10, up to date
2. Install ppa:libretro/testing
3. Ctrl-Alt-F2 to get a new terminal
4. Sign in, sudo -s
5. Launch retroarch

### Bisect Results

First noticed with yesterday's nightly build (March 24), though origin date of the issue is unknown to me, continuing into today's build. I most likely last updated my system's packages within the last month.
The stable libretro PPA functions properly on the same system.

### Version/Commit
RetroArch 1.7.2 (Git aa5525f)

### Environment information

Ubuntu 17.10, up to date
Mid-2012 MacBook Air (Ivy Bridge, Intel HD 3000)
Internal display

### Notes

I apologize if this is not enough information. If needed, I can look into self-compiling RetroArch, though I have not done so on Linux before.

Log of functional run from 1.7.1 stable:

[INFO] RetroArch 1.7.1 (Git 6fc6bfb)
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES 
Built: Feb 20 2018
[INFO] Version: 1.7.1
[INFO] Git: 6fc6bfb
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ fullscreen
error: XDG_RUNTIME_DIR not set in the environment.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [DRM]: Found 6 connectors.
[INFO] [DRM]: Connector 0 connected: yes
[INFO] [DRM]: Connector 0 has 1 modes.
[INFO] [DRM]: Connector 0 assigned to monitor index: #1.
[INFO] [DRM]: Connector 1 connected: no
[INFO] [DRM]: Connector 1 has 0 modes.
[INFO] [DRM]: Connector 2 connected: no
[INFO] [DRM]: Connector 2 has 0 modes.
[INFO] [DRM]: Connector 3 connected: no
[INFO] [DRM]: Connector 3 has 0 modes.
[INFO] [DRM]: Connector 4 connected: no
[INFO] [DRM]: Connector 4 has 0 modes.
[INFO] [DRM]: Connector 5 connected: no
[INFO] [DRM]: Connector 5 has 0 modes.
[INFO] [DRM]: Mode 0: (1440x900) 1440 x 900, 60 Hz
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1440x900.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x555a27877200.
[INFO] [KMS]: New FB: 1440x900 (stride: 6144).
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Ivybridge Mobile .
[INFO] [GL]: Version: 3.0 Mesa 17.2.8.
[INFO] [GL]: Using resolution 1440x900
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] Shader log: 0:3(311): warning: `atime' used uninitialized

[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [udev]: Keyboard #0 (/dev/input/event11).
[INFO] [udev]: Mouse #0 (/dev/input/event6).
[ERROR] [udev] Failed to open device: /dev/input/mouse0 (Inappropriate ioctl for device).
[INFO] [udev]: Plugged pad: USB,2-axis 8-button gamepad   (1411:8288) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event12) supports 0 force feedback effects.
[INFO] [Autoconf]: 0 profiles found.
[INFO] [Autoconf]: no profiles found for USB,2-axis 8-button gamepad   (1411/8288).
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: null
Home directory not accessible: Permission denied
[INFO] [ALSA]: Using signed 16-bit format.
[INFO] [ALSA]: Period size: 1024 frames
[INFO] [ALSA]: Buffer size: 3072 frames
[INFO] [ALSA]: Can pause: no.
Home directory not accessible: Permission denied
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x555a252d6520
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/config/retroarch/content_history.lpl].
[INFO] Loading history file: [/config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/config/retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [GL]: VSync => on
[INFO] [KMS]: New FB: 1440x900 (stride: 6144).
[INFO] [GL]: VSync => on
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.

**Comment by i30817** [comment]
What, you mean trying to load RA from a tty? That segfaults for me right away.

**Comment by TylerLoch** [comment]
@i30817 is that not the proper way to launch RetroArch for KMS mode? The docs mention "running straight in the virtual terminal": https://docs.libretro.com/guides/kms-mode/

And to reiterate, I've been using this method successfully for the past year, up through 1.7.1 stable, and only encountered trouble in the latest nightlies.

**Comment by i30817** [comment]
Ahhh, i wasn't aware it was possible. I guess i should have searched the docs before complaints.

Though the segfault would be a bug anyway.

**Comment by autofire372** [comment]
I would just like to note that it's not just Ubuntu; I've been having this exact problem on recent Lakka builds.

**Comment by gouchi** [comment]
According to git bisect, the first bad commit is [16c1bd7](https://github.com/libretro/RetroArch/commit/16c1bd7a0355003ec257276fd22d9fb9dcc30a13).

**Comment by twinaphex** [comment]
Should be hopefully fixed now as of this commit - https://github.com/libretro/RetroArch/commit/923ab3b6f4cf34e055f18b0d159270831db8935b

Tested it real quick on a 2012 Linux laptop on which I had always ran DRM and it works fine there.

**Comment by gouchi** [comment]
Thank you it fixed the issue !

**Comment by i30817** [comment]
Could load the scummvm core but couldn't use the keyboard or mouse. Is this a bug or was it only supposed to support controllers?

 (had to initiate a shutdown from the hardware shutdown button). Still pretty cool to get rid of X overhead.

**Comment by orbea** [comment]
fwiw kms works with the latest master here including mouse + keyboard in scummvm.

**Comment by TylerLoch** [comment]
I can also confirm the issue is gone with the latest Nightly. Everything is back to normal.
Thank you very much!
