### ISSUE TITLE
[D3D11/12] Crash when attempting to load/display very small savestate preview images

### ISSUE THREAD

**Issue by trostboot** [libretro/RetroArch#6473]
### Description

RetroArch crashes when attempting to display a savestate preview that is very small (for instance, from savestates made during screen transitions, as they will be solidly black). This only occurs with D3D11 and 12 video drivers.
By contrast, D3D9, OpenGL and Vulkan don't crash, but don't display the image, either.

Larger black images (such as created by #6427 ) don't result in a crash and are also displayed properly.
Images created with a 4x internal resolution in beetle-psx (1280x960 at ~3,6kb file size in this case) will still result in a crash.
1600x1200 (~6kb) and above will not result in a crash.
After further testing with manually created images, seems to roughly apply to images under 4kb in size.

### Steps to reproduce the bug

1. Select either D3D11 or D3D12 as video drivers
2. Disable GPU screenshot option if enabled
3. Use a core/core options with low internal resolutions
4. Create a savestate when a game is transitioning between screens and is displaying nothing
5. Open the quick menu again and set the savestate slot to the one you just made (if it isn't already)
6. Observe crash

### Version/Commit

- RetroArch: 1.7.2 a32d7d974c

### Environment information

- OS: Windows 10 x64 16299
- GPU: nvidia GTX1080 (driver 391.01)

**Comment by i30817** [comment]
[Maybe something as dumb as this?](http://www.rpgcodex.net/forums/index.php?threads/unofficial-patches-for-thief-and-other-pc-games.90431/page-13#post-5141500)

**Comment by twinaphex** [comment]
Check if this commit solves this issue -

https://github.com/libretro/RetroArch/commit/008900e73d2541cfe2fa0cb2488d829549f2b7ac

**Comment by trostboot** [comment]
Crash is fixed now. It now just displays nothing, bringing it in line with the other video drivers.
