### ISSUE TITLE
[Android] Audio hangs after toggling menu

### ISSUE THREAD

**Issue by alegru** [libretro/RetroArch#6476]
## Description

Using audio driver OpenSL, toggling menu ingame disables audio output after a few seconds.

### Expected behavior

Audio plays normally

### Actual behavior

Audio hangs a few seconds after menu button is pressed

### Steps to reproduce the bug

1. Start a game
2. Enter RetroArch menu (overlay / hotkey does not matter)
3. Resume Game
4. After a few seconds, audio bugs out

### Bisect Results

Somewhere between 1.7.1 and master
2018-03-24-RetroArch_aarch64.apk was buggy
I suspect issues with commit 54708a944a59d565bb38d4df03f0617e188219f8

### Version/Commit
RetroArch: 1.7.2

### Environment information

Tested on different devices
- OS: Android 7.1.2 + Android 8.1, same result
- Compiler: -

**Comment by twinaphex** [comment]
Yeah, there were bound to be issues with that patch. I will revert it for now.

**Comment by twinaphex** [comment]
Let me know if this resolves the issue -

https://github.com/libretro/RetroArch/commit/5a7c37b81968e18e868a0b6db14e69b8b79e8654

**Comment by alegru** [comment]
Yeah, that did the trick.
