### ISSUE TITLE
Renaming games in Retroarch changes the path line in the .lpl file instead of the actual name

### ISSUE THREAD

**Issue by King-Troller** [libretro/RetroArch#6486]
**[Description of the bug]**
When selecting a ROM/ISO in retroarch and choosing to rename it the name seems to stay the same, but retroarch can no longer find the game. After some digging through files I found that the path to the file is overwritten instead of the name in the .lpl file that holds playlist info.

**[What you expected to happen]**

I expected the name of the game in the menu to simply change

**[What is actually happening]**

It's overwriting the path making retroarch unable to find the games.

Donkey Kong Country <--This is where the path to the file is supposed to be. It got replaced
Donkey Kong Country (U) (V1.0) [!]  <-- This is what was supposed to be overwritten
DETECT
DETECT
C946DCA0|crc

To reproduce you just attempt to rename any file in the retroarch interface

I thought it might just be a problem on my end at first, but after completely removing retroarch and reinstalling it I was still having this problem. I also tested that it happens on the android version.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.1 | 6fc6bfbb24 | Feb. 19 2018

### Environment information

- OS: Windows 10 Home v1709 | Android v7.0
- Compiler: [In case you are running local builds]

**Comment by retro-wertz** [comment]
update to latest nightly. were already at 1.7.2
