### ISSUE TITLE
[Lakka] Some roms won't load from playlist, but will run from Load Content

### ISSUE THREAD

**Issue by Frankenburger** [libretro/RetroArch#6489]
I'm having an issue where some roms (transltated Bahamut Lagoon and translated Dragon Ball Z Super Butouden 3) won't load from my playlist. However, when selecting the roms from Load Content, they load and play without issue. This is regardless if I'm using SNES9x or Banes-Mercury Balanced for the playlist. Both SNES9x and Banes-Mercury works on a manual load.

**Comment by i30817** [comment]
I have a strange issue where '.' in a directory will cause a scan not to pick up a valid rom (probably because of a terrible way to distinguish files from directories) but not that.

**Comment by RobLoach** [comment]
What's listed in the playlist?

**Comment by Frankenburger** [comment]
So, funny story. It slipped my mind of just how case sensitive Linux is. 

I was pointing the playlist to Bahamut Lagoon (ENG).smc, when the actual file is Bahamut Lagoon (ENG).**SMC**

Fixed the case sensitivity on the affected ROMS and they all work now.

**Comment by i30817** [comment]
I have a PR to fix the '.' in dir names to open.
