### ISSUE TITLE
shaders rendering issue with GameGear core only

### ISSUE THREAD

**Issue by eadmaster** [libretro/RetroArch#65]
already reported here: https://github.com/ekeeke/Genesis-Plus-GX/issues/8

I'm getting this with shaders enabled:
http://eadmaster.altervista.org/tmp/RetroArch-Genesis-Plus-GX-shaderbug.png

the same did not happen with SSNES...

**Comment by twinaphex** [comment]
@p1pkin So please tell me that, in light of this,

https://github.com/libretro/RetroArch/issues/65
https://github.com/libretro/RetroArch/issues/95

Seems you were previously a 'fan' that I even tried helping here in this thread, yet years later you treat us wrongly for no apparent reason.

Care to explain yourself? You should stop biting the hand that feeds you and show some respect when people help you.

I never did you wrong until you started lashing out for no apparent reason.
