### ISSUE TITLE
[RetroArch FAQ] Collecting frequently asked questions

### ISSUE THREAD

**Issue by 777sha** [libretro/RetroArch#6505]
### This is what It looks like so far:
---
**Make sure to check the [RetroArch troubleshooting guide](https://docs.libretro.com/guides/troubleshooting-retroarch/)**
<p>

**Other discussion spaces for Libretro and RetroArch:**
[Forums](https://forums.libretro.com/)
[IRC](https://www.irccloud.com/invite?channel=%23retroarch&hostname=irc.freenode.net&port=6667)

**Q: What information should I give when asking for help ?**
A: Ideally your platform, OS version, RetroArch version, CPU / GPU and the core / game you have an issue with. Describe your problem clearly. Check this FAQ before posting. Be patient or post later if no one answers your question.

**Q: Where can I download (some ROM) ?**
A: It is forbidden to link to copyrighted ROMs and content here since RetroArch doesn't encourage piracy.

**Q: I can't see the ROMs I've scanned in RetroArch**
A: RetroArch checks that your ROMs checksums match certain databases (No-intro, Redump etc.) in order to add them to playlists  - You can learn more about it [here](https://docs.libretro.com/guides/roms-playlists-thumbnails/#retroarch-playlist-scanner).

Also make sure:
- To have updated the core info files and databases
- That your ROMs format are supported by the core you are using.

**Q: What is a checksum ?**
A: It's essentially an unique hexadecimal identifier for files.

**Q: Which core is the best to emulate (some console / game) ?**
A: There is no best core, each has a different use case (accuracy, speed...).

**Q: I can't load / the core crashes on startup with (some game)**
A: It's either because
- you are missing a required file like the BIOS or the name is not exact 
(you can check it under main menu -> load core -> information -> core information)
- the core doesn't support your game
- your ROM is a bad dump
- the core doesn't support the video driver you are using
- If you are using a disc-based game (bin + cue archive) you need to unzip it

**Q: When I try to load a core on RetroArch for Windows it says "No Core"**
A: It's either because
- You need to download MSCV Runtime
- You need to update RetroArch

**Q: My ROM doesn't work with MAME**
A: Make sure you ROMs are [compatible with the version of MAME you are using.](https://github.com/RetroPie/RetroPie-Setup/wiki/MAME)

**Q: I can't see (some core) in the download list**
A: If you're on Windows maybe you have accidentally downloaded the Win XP build, which is not compatible with all cores.

If you are on another platform like 3ds, Wii U etc., some cores may not be available because they aren't compatible or too demanding.

**Q: Why does some core / game run slowly ?**
A: It is likely because your system is too slow.

**Q: Why doesn't fast-forward work ?**
A: It's likely because the core doesn't run fast enough on your system.

**Q: How do I know if my system will run a certain game/system/core ?**
A: Depending on what you are trying to run you should either research it or try it yourself.

**Q: How do I create an error log ?**
A: https://docs.libretro.com/guides/generating-retroarch-logs/

**Q: How do I get a backtrace ?**
A: https://docs.libretro.com/tech/debugging/

**Q: I have issues / questions about netplay**
A: https://docs.libretro.com/guides/netplay-faq/

**Q: I have issues with the Dolphin core (Gamecube / Wii)**
A: Currently the dolphin core hasn't been updated since march 2017. It doesn't have all the features of the standalone emulator (like ubershaders and multi-disc support) and has some bugs.

**Q: I have issues with Amiga emulation**
A: The P-UAE core has not been updated since 2014.

**Q: Is RetroArch available for (some platform) ?**
A: https://docs.libretro.com/#which-platforms-are-retroarch-available-for

**Q: When will the next version of RetroArch be released ?**
A: There is no ETA. You can [try the nightly builds to get the latest features](https://buildbot.libretro.com/nightly/)

**Q: How do I delete a core ?**
A: Under load core -> Information -> core information -> delete core

**Q: How do I delete a playlist ?**
A: You have to delete the corresponding .lpl file under retroarch/playlists.

**Q: How do I reset my settings ?**
A: You can delete retroarch.cfg to reset RetroArch settings and retroarch-core-options.cfg for core settings.

**Q: How do I enable thumbnails ?**
A: You need to
- be using the XMB menu
- enable thumbnails under settings -> user Interface -> appearance -> thumbnails
- download the thumbnails you want under main menu -> online updater -> thumbnail updater

**Q: How does RetroAchievements support work ?**
A: https://docs.libretro.com/guides/retroachievements/

**Q: RetroArch for Windows crashes on startup**
A: Your GPU or OS might lack OpenGL 2.0 support. To fix this you can open retroarch -> retroarch.cfg and change "video_driver" to either "d3d" or "gdi".

**Q: I saved in game but it didn't work / RetroArch crashed and I lost my save**
A: RetroArch doesn't save in real time, SRAM is saved when you hit "close content". In some cases it's possible that closing RetroArch without closing the core first loses the saves from the current session (especially on Windows).

**Q: How do I install RetroArch on IOS ?**
A:

To fix this you can enable the "Saveram autosave interval" option under settings > saving. Be aware that it might corrupt your save if you close RetroArch while the game is saving, especially in games that heavily use the SRAM and with a low autosave interval. Another option is to use save states.

If you're on Android, make sure your save folder isn't located on an external SD card, it won't work.

**Q: How do I change the core that is launches games from a certain playlist ?**
A: You can set it under settings -> playlist

**Q: I can't update cores on Linux**
A:  It's likely because your distro disabled the online updater, you need to give write permissions to your RetroArch folder.

**Q: Why is Super Mario 64 blurry in Mupen64Plus ?**
A: Turn "crop mode" off in the core options.

**Q: "Failed to load content" error with some games in Higan**
A: Check the [Higan libretro documentation](https://docs.libretro.com/library/higan_accuracy/)

**Q: How do I launch games from the command-line?**
A: https://docs.libretro.com/guides/cli-intro/

**Q: Why is (some core) running too fast ?**
A: It's likely because you have VSync and / or audio disabled.

**Q: Which video renderer should I use ? (Vulkan, OpenGL...)**
A: 

**Q: How do I type inside a core with a keyboard without triggering RetroArch hotkeys ?**
A:

**Q: How do I record / stream video?**
A: 

**Q: When I use multiple controllers only player 1 works**
A:

**Q: How do I swap discs in a multi-disc game ?**
A: Refer to the "Swapping discs" section for the core you are using in the [docs](https://docs.libretro.com/)

**Q: How do I report a bug ?**
A: You need to open a [github issue](https://github.com/libretro) in the right repository. Check if a similar issue isn't already open. Give details and steps to reproduce it.

**Q: How can I donate?**
A: You can support the libretro project on [Patreon](https://www.patreon.com/libretro)

</p>

**Comment by bparker06** [comment]
Hi @777sha,

Thanks for starting this. I don't have time to prune out the duplicates from my own notes right now, but here's what I had saved up to put into this issue if you want to aggregate them (feel free to modify as necessary):

Why won't my/some games scan? (must match checksums in our databases, refer to docs page on scanning)

Why does RetroArch on Windows crash when I try to start it? (usually means your GPU/OS lacks OpenGL 2.0 support, try d3d or gdi)

Why does RetroArch crash when I load a game? (could be missing BIOS or unsupported game)

When I try to load a core on Windows, it still says "No Core". Why? (usually outdated redist, missing DLLs, or need MSVC runtime)

Why does core/game X run slowly? (usually their system is just too slow)

What's the best core for X system?

What's the best core for X game?

How does RetroAchievements support work?

Why don't my games save properly on Android? (probably changed saves folder to external SD card, which doesn't work)

How do I know if my system will run a certain game/system/core?

What information is useful when asking for help? (platform, OS version, RA version, which core/game, what CPU/GPU)

Why is my game/save screen in PPSSPP just a black screen? (missing/outdated assets)

Why does Mednafen PSX crash when I start a game? (missing/wrong BIOS, and many people spell the files wrong)

Why does Mednafen PSX HW crash randomly in-game? (the HW core is just buggy)

Why can't my friend connect to my netplay game? (see netplay faq, most likely port forward not working, can also try MITM)

Why doesn't fast-forward work? (core too slow on their system)

How do I update cores on Linux? (distro disabled Online Updater, must either use their packages or set core folder to a writeable directory and enable the updater)

Why are so many cores missing on Windows? (they downloaded the XP version by mistake)

Why is Super Mario 64 blurry in Mupen64Plus? (turn crop mode off in core options)

Why doesn't my gamepad work? (probably no autoconfig, refer to docs on creating one)

How do I get thumbnails for my games to appear in XMB? (need to download thumbnails for that system from the updater and set Settings -> User Interface -> Appearance -> Thumbnails)

Why is my game running at lightning speed? (probably vsync and/or audio is disabled)

How do I get a log from RetroArch on Windows?

How do I add support for my gamepad? (refer to autoconfig docs?)

Why doesn't the Content Downloader show anything? (wait a few minutes and try again)

How do I change the core that is launched for games in a certain playlist? (Settings -> Playlist)

How do I launch games from the command-line?

What is a checksum?

What is/how do I get a backtrace?

How do I type inside a core with a keyboard without triggering RetroArch hotkeys? (use game focus toggle or a hotkey enable)

Where can I get help? (discord, irc, forums, twitter, etc)

How can I donate? (link to patreon)

How do I report a bug?

Why does MAME crash when I try to load a game? (usually wrong romset version for that mame core)

How do I record/stream video?

How do I delete a core? (Load Core, then Information -> Core Information -> Delete Core)

Can I netplay N64/PSX games?

Do link cable games like Gameboy work through netplay?

Can I trade Pokemon with netplay?

Why does my disc-based game fail to load? (probably using a zipped bin/cue archive, it must be unzipped)

How do I swap discs in a multi-disc game?

RetroArch crashed and my game did not save. Why? (we only save on exit unless auto sram save interval is set)

**Comment by SapphireTactician** [comment]
>Why does my disc-based game fail to load? (probably using a zipped bin/cue archive, it must be unzipped)

This should be rephrased to include the fact that multi-track disc based games fail to play music if they're not unzipped as well.

**Comment by twinaphex** [comment]
I'm reopening this and making a FAQ page on retroarch.com.

**Comment by twinaphex** [comment]
here is the beginning of the FAQs page

https://retroarch.com/index.php?page=faq

RetroArch

we can add core-specific FAQ questions to this too for all I care

the github page for it is here

https://github.com/libretro/www.retroarch.com/blob/master/faq.php

anybody editing though needs to ensure not to break the HTML coding in it though
add a new question with <h3></h3> tags
then make a div block for it
with class
row platforms
then close it
and so on
also there need to be anchors placed at the beginning of every ' category'
so we can add links to the categories in the Table of Contents

**Comment by FeRcHuLeS** [comment]
Hi just a question: 
Where the files like cores, thumbnails and so on are unzipped?, 

I think is "c:/windows/temp", Not sure since I downloaded the thumbnails for Sega Genesis and Saturn and in middle of that, my internet connection was interrupted and the C drive is almost full now. So where is the location so that I can delete those thumbnails that weren't properly downloaded.
Thanks

**Comment by hizzlekizzle** [comment]
@FeRcHuLeS you can use a storage visualizer, like WinDirStat, to track them down:
https://windirstat.net/

**Comment by FeRcHuLeS** [comment]
I've just downloaded, Can you explain me know how to find those corrupted thumbnails?
