### ISSUE TITLE
[WIIU] DSI on wad launch with PrBoom

### ISSUE THREAD

**Issue by Cruplezone** [libretro/RetroArch#6506]
doom.wad
![image](https://user-images.githubusercontent.com/17866415/38173365-7076a0fa-358b-11e8-9ee5-a6bad42929ab.png)

doom2.wad
![image](https://user-images.githubusercontent.com/17866415/38173404-2d187bca-358c-11e8-9752-c374604f6348.png)

doomu.wad
![image](https://user-images.githubusercontent.com/17866415/38173447-e0a27ad8-358c-11e8-97eb-360575689b8a.png)

The following DSI errors are examples of what come up when trying to launch anything via PrBoom on the latest nightlies. Have never gotten a .wad to successfully load. Reproducible.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: PrBoom v2.5.0 494885c

### Environment information

- OS: 5.5.2 MochaCFW

**Comment by twinaphex** [comment]
Sucks that this is happening yet again.

**Comment by twinaphex** [comment]
@Ferk apparently there are regressions yet again with the WiiU port. It won't start up any WADs apparently. This is a major recurring issue that we need to fix once and for all. It cannot happen over and over again.

**Comment by QuarkTheAwesome** [comment]
Looks like a bad descriptor being passed into fclose? That or it's the usual heap corruption. The addresses look like ASCII, which is a very similar symptom to the HID issues we had for a while.

My money's on either heap corruption or a double close, though I haven't actually looked at the code to confirm this.

**Comment by ShadowOne333** [comment]
Have you guys tried out the latest nightly?
It's working fine on my side, just downloaded 10 mins ago (April 5th, 2018 one).

I find it odd that he ishaving DSI errors, since PrBoom hasn't had any commit since February when the IWAD/PWAD loading was fixed for good.

I tried loading the following wads:

- Doom
- Doom 2
- WolfenDoom: Nocturnal Missions
- WolfenDoom: Original Missions
- Doom: Plutonia Experiment

I loaded the all side to side through playlists, and none of them failed on them, they played just fine.
So perhaps the issue here is an old CFG of some sort or maybe it's not a clean install of RA.

**Comment by Cruplezone** [comment]
Yeah the fact that it was due to my setup would be true. As it turns out something happened to my system folder, leading it to be not present. Sorry for the 'false' issue.

I guess there's no error catching in place to detect if a given bios/sample/system item isn't present? Is DSI-ing the expected behaviour?

**Comment by ShadowOne333** [comment]
I think this issue can be closed since it was confirmed to be user-error instead of a PrBoom error.

> I guess there's no error catching in place to detect if a given bios/sample/system item isn't present? Is DSI-ing the expected behaviour? I will note I launched this via playlist. If it is expected to DSI with no bios found then I'll close the issue.

I believe this is how RetroArch works when it doesn't detect the proper files.
If it doesn't have the bios or the core, it tends to DSI error sometimes, that is expected.

**Comment by Cruplezone** [comment]
@ShadowOne333 just tried on another platform with a similar setup. The client returns: 'Failed to load content' instead of crashing. I believe the issue still stands.

**Comment by Cruplezone** [comment]
@ShadowOne333 No, I am aware. I'm saying that other platforms have appropriate error catching place to recognize when a given BIOS file is not present and therefore displays 'Failed to load content' when loading a given content from a playlist. The wiiu on the other hand crashes, and something is therefore going wrong with that catching. This is the issue.

**Comment by ShadowOne333** [comment]
Ah I get what you mean now.
I remember having that kind of behaviour sometimes (not always) with certain cores when the bios is not found in the Wii U version. Can't tell for other versions, but it happens at times with the Wii U one. 
But out of that, if you have the bios in the correct folder no DSI error should occur.
