### ISSUE TITLE
[Android] [Picodrive] [SMS] [Core-provided aspect ratios are mislabeled]

### ISSUE THREAD

**Issue by King211** [libretro/RetroArch#6511]
When loading a sms(sega master system) rom on picodrive, the core provided aspect ratios are mislabeled.
Quick Menu - Options - Core provided aspect ratio
PAR=4:3
4:3=PAR(almost widescreen)

### Expected behavior
PAR=PAR
4:3=4:3
### Actual behavior
PAR=4:3
4:3=PAR (almost widescreen)
### Steps to reproduce the bug

1. load sms rom
2. change the default core provided aspect ratio from PAR to 4:3
3. rom looks almost widescreen when its suppose to be 4:3

### Version/Commit

- RetroArch: Feb 19 2018
- Git version: 6fc6bfb

- OS: Android

**Comment by retro-wertz** [comment]
looks like the core is always assuming the height is always 224, but most
SMS games are 192 height.
in anycase, this does not belong here. this should posted in related core's
issue page.

**Comment by orbea** [comment]
I would suggest posting this upstream too.

https://github.com/notaz/picodrive
