### ISSUE TITLE
Core shader presets not "unloading"

### ISSUE THREAD

**Issue by 777sha** [libretro/RetroArch#6516]
## Description

Ok this has been happening to me for a while now. 
Some shaders load when they are not supposed to.

I can tell it happens with SameBoy and Desmume.
 **MGBA is the only other core I use shaders with but it doesn't seem to cause the same issues after some testing.**

I am using CG shaders and the XMB menu.

"retroarch.cgp" and "stock.glsl" are empty.

### Expected behavior

Shaders should "unload" completely after closing a core.

### Actual behavior

Core shader presets "load" in retroarch.cfg -> "video_shader".

### Steps to reproduce the bug

1. Load a core with a shader preset (like Sameboy with a Game Boy border)
2. close the core
3. retroarch.cfg now reads "video_shader = ":\shaders\presets\something.cgp"
4. The XMB background animation is now forced to simple ribbon.
5. loading a core with no shader preset will force the previously used shader

### Version/Commit

I am using the 04-02 nightly build but I think it's happening since 1.7.1.

### Environment information

Windows 10 x64
i3 6100 - Radeon RX 480

**Comment by hizzlekizzle** [comment]
This has been the behavior forever, AFAIK. I think you can point that "video_shader" line in your main retroarch.cfg at one of the basic "bilinear" or "nearest" presets and it should default back that...?

**Comment by 777sha** [comment]
Following your reasoning and after a few tries I put "video_shader = ":shaders/stock.glsl" in retroarch.cfg. Everything seems fine now thanks.
