### ISSUE TITLE
Double tap touch input is processed when opening the RetroArch menu from in-game overlay

### ISSUE THREAD

**Issue by singularity098** [libretro/RetroArch#6518]
## Description

When opening the RetroArch menu from the in-game overlay, a double input tap is processed.  In other words when you press down on the RetroArch icon from the in-game overlay, the menu appears ... but then as you release your finger, _another_ tap is registered on the menu inside of the Android RetroArch app menu... selecting whichever option your finger happened to be on when the menu loaded.

### Expected behavior

Expected that one button press loads the menu, and nothing additional.

### Actual behavior

Menu is loaded on press finger down, but an unwanted menu option is selected on finger release.

### Steps to reproduce the bug

1. Load up RetroArch on Android or other touch device, with GLUI and touch support enabled, and onscreen overlay.
2. Load game content.
3. Press the RetroArch button to pull up menu.
4. Menu comes up, but as button is released, another menu option is pressed.
5. Workaround would be to press button, then drag finger slightly before releasing.

### Bisect Results

Has existed all along to my knowledge.

### Version/Commit

- RetroArch: v1.7.1

### Environment information

- OS: Android on OnePlus 3T
- Compiler: N/A

**Comment by b2jammer** [comment]
Still happens in v1.16.0.

**Comment by sonninnos** [comment]
Pretty sure does not happen anymore.
