### ISSUE TITLE
[3DS] Enabling threaded video crashes RetroArch 

### ISSUE THREAD

**Issue by luigicool09** [libretro/RetroArch#6526]
Description

Enabling threaded video gives an arm11 error on old 2ds 

Expected behavior
Threaded video activating so I could move on
 Actual behavior

Runs process but then after finishing gives an error crashing old 2ds

Steps to reproduce the bug

1. Go to video settings
2. Try to enable Threaded video 

### Bisect Results
 This started happening when I first tried to enable threaded video

 Version/Commit

- RetroArch: 04-02-18 nightly build

 Environment information

- OS: 2ds old 11.6-39U Luma3DS

**Comment by twinaphex** [comment]
Probably an indication that the threading support in RetroArch 3DS is still not up to par. Either that or the current 3DS video driver is not thread-safe.

I would highly recommend not using threaded video on 3DS regardless.
