### ISSUE TITLE
[3DS] Enable 800x240 output for top screen

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#6529]
## Description

Nintendo 3DS has a top screen that can run at 800x240.

Enabling RetroArch (and cores) to run in this mode would enable the user to play the game with higher resolution graphics.

### Table of data

I just wanted to make some notes about scaling with specific reference to Nintendo 3DS and the X68k core, which sparked this idea:

- 800×240 top screen (400×240 in 3D mode)
- 320×200 bottom screen

The interesting thing here is that we can double the horizontal resolution and have some graphics modes be displayable in higher fidelity than otherwise.

Correct X68k aspect ratio means horizontal stretch of 1.375 to get corrected resolution AFAIK.

| Sharp X68k res | Aspect corrected | 3DS scaling factor | Scaled resolution | 3DS output | Notes |
|---|---|---|---|---|---|
| 256×240 | 352×240 | 1.0×1.0 | 352×240 | 352×240 | — |
| 256×256 | 352×256 | 1.0×1.0 | 352×256 | 352×*240* | V-crop |
| 512×240 | 704×240 | 1.0×1.0 | 704×240 | 704×240 | — |
| 512×256 | 704×256 | 1.0×1.0 | 704×256 | 704×*240* | V-crop |
| 512×512 | 704×512 | 0.5×0.5 | 352×256 | 352×*240* | V-crop |
| 640×480 | 880×480 | 0.5×0.5 | 440×240 | *400*×240 | H-crop |
| 768×512 | 1056×512 | 0.5×0.5 | 528×256 | 400×*240* | V-crop |
| 1024×1024 | 1408×1024  | 0.25×0.25 | 352×256 | 352×*240* | V-crop |

**Comment by danieljg** [comment]
Afaik, the o3ds can already do this (though I haven't tried) but it is unknown how to turn the parallax barrier off on the n3ds.  This info  comes from quite a while back, though.

**Comment by gingerbeardman** [comment]
interesting. I'll look into that

**Comment by gingerbeardman** [comment]
@danieljg do you have a link or hint where the info was you are remembering?

**Comment by danieljg** [comment]
@gingerbeardman There's a comment by vaguerant here:

https://github.com/libretro/RetroArch/pull/5054

As well as some references to the code that handles this in the o3ds here:

https://github.com/libretro/RetroArch/search?utf8=%E2%9C%93&q=parallax&type=

**Comment by gingerbeardman** [comment]
Awesome, closing this issue in favour of that one.
