### ISSUE TITLE
Loading a game starts with a black screen + Paused on the lower-left side.

### ISSUE THREAD

**Issue by torben656** [libretro/RetroArch#6533]
Using the current nightly, I don't know how to fix this. The only thing I changed in my config is Video>Fullscreen at start on and Vsync off

**Comment by 777sha** [comment]
Which OS ? Which cores have you tried ? do you have shaders on ? Which video driver are you using ? Can you post a log ?

**Comment by Kurtmass** [comment]
having this issue now.  .  All games were working fine and I think I changed a video driver to try to get contra to work and now nothing loads.  Only a black screen with "paused." in the lower left corner.
