### ISSUE TITLE
PPSSPP core can't load any game

### ISSUE THREAD

**Issue by arthurmv** [libretro/RetroArch#6537]
## Description

Retroarch crash when I attempt to load a PSP game. [Asset files](https://docs.libretro.com/library/ppsspp/#bios) are already in System/PPSSPP folder.

### Environment information

- Windows 10 Pro v1709
- Retroarch 1.7.1

**Comment by hizzlekizzle** [comment]
If you can load games with other cores, this issue belongs on the core's tracker. However, it's probably even better-suited to the forums, where we can provide technical support. The issue tracker is for development and bug reporting/tracking only.
