### ISSUE TITLE
[Wii U] RetroArch will not read Neo-Geo Pocket ROMs.

### ISSUE THREAD

**Issue by nanashi89** [libretro/RetroArch#6540]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Loading Neo-Geo Pocket ROMs through an SD card only shows Neo-Geo Pocket Color ROMs.

### Expected behavior

List is supposed to show ALL Neo-Geo Pocket ROMs, not just Neo-Geo Pocket Color ROMs.

### Actual behavior

Shows only Neo-Geo Pocket ROMs.

### Steps to reproduce the bug

1. Extract contents of https://buildbot.libretro.com/stable/1.7.1/nintendo/wiiu/RetroArch_rpx.7z to the SD card.
2. Delete all cores except for the Beetle NeoPop core.
3. Extract the romset to a folder in the root of the SD card.
4. Take the card out, load it onto Wii U.
5. Launch Retroarch from the launcher on the Wii U System Menu.
6. Go to Load Core, and load Beetle NeoPop.
7. Go to Load Content and the folder of ROMs.
8. Only NGC ROMs are present, no BIN ROMs

### Bisect Results

Last night

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://buildbot.libretro.com/stable/1.7.1/nintendo/wiiu/RetroArch_rpx.7z

### Environment information

- OS: [Wii U]
- Compiler: [Don't know]

**Comment by fr500** [comment]
Supported extensions are:
`supported_extensions = "ngp|ngc|ngpc"`

https://github.com/libretro/libretro-super/blob/master/dist/info/mednafen_ngp_libretro.info#L3
