### ISSUE TITLE
Pick generic icons if playlist does not match any icon name

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#6552]
RetroArch should pick generic icons if playlist name does not match any icon name from assets, otherwise you'll get the black squares all over the interface.

I like to make custom playlists, for example:

```
Arcade - Capcom - CPS-1
Arcade - Capcom - CPS-2
Arcade - SNK - Neo Geo
```

See:

![screenshot_20180410-010917](https://user-images.githubusercontent.com/5431285/38535874-419488ec-3c5c-11e8-8a3e-c89e3ade590c.png)

It should be nice if RA pick "Libretro - Pad.png" for the platform and maybe "file.png" or other icon for content. Example:

![screenshot_20180410-013140](https://user-images.githubusercontent.com/5431285/38536308-f0285634-3c5e-11e8-97d3-b365dce2bb0c.png)

**Comment by viniciusccarvalho** [comment]
+1

**Comment by orbea** [comment]
This seems to have been implemented in the master. I removed the asset images for one of the playlists and it showed me an generic icon instead. Additionally it will no longer share black boxes if the assets are missing.

I think its safe to close this.

**Comment by jeffmadriaga** [comment]
Could anyone elaborate on this? Are default icons just mapped 'automagically' in the latest build?

**Comment by ner00** [comment]
If you add a new playlist manually, which is not recognized by RetroaArch (not having own icon/assets), it will by default add a playlist icon and content icon with default.png asset (currently rocket icon): https://raw.githubusercontent.com/libretro/retroarch-assets/master/ozone/png/icons/default.png
