### ISSUE TITLE
menu code broken by commit

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#6557]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Seems like a regression. After a scan, it's possible for the menu to crash or present a empty list of rom playlists (on debug). At first i thought it was my fuck up from the 'dot in dir' fix but regression test shows:

fbf03df8be22b40a1d44908ebfe0163a0ebb4bef is the first bad commit
commit fbf03df8be22b40a1d44908ebfe0163a0ebb4bef
Author: twinaphex <libretro@gmail.com>
Date:   Tue Apr 10 19:57:33 2018 +0200

    Less pointer grabbbing - reduce usage of RARCH_MENU_CTL_DRIVER_DATA_GET

:040000 040000 9bbf85d05690c15f2db6d96b54a7b9511bc29aac 2fed5285386aa19b83e1e9d63ead34fe0c437605 M	menu

### Expected behavior

Adding to playlist

### Actual behavior

Crash in xmb or removal of all playlists depending on debug build (i think, could also be that if the playlist already exists).

### Steps to reproduce the bug

1. Scan a dir or file which will create or add to a playlist

### Bisect Results

fbf03df8be22b40a1d44908ebfe0163a0ebb4bef

### Version/Commit
You can find this information under Information/System Information

- RetroArch: ba96aac2da7074c19f027fb687f48752ab6fee47

### Environment information

- OS: linux x86-64
- Compiler: gcc

**Comment by twinaphex** [comment]
Reverted the commits for now.

**Comment by i30817** [comment]
that fixed it.
