### ISSUE TITLE
[WiiU] FBAlpha DSI on ROM close/switch

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#6572]
## Description

This DSI error appears on the close or switch of any game (I assume only if supported by hi scores) with FBAlpha when hiscore.dat (https://github.com/libretro/fbalpha/blob/master/metadata/hiscore.dat) is placed within /SYSTEM_DIRECTORY/fba/

Reproducible with multiple ROMs (same errors).

This DSI does not occur without the presence of the hiscore.dat file.  

![image](https://user-images.githubusercontent.com/17866415/38742600-06b63bc4-3f0b-11e8-918b-a34f90ab42d7.png)

### Steps to reproduce the bug

1. Place hiscore.dat within SYSTEM/fba/
2. Launch a ROM with FBAlpha
3. Close, reset, or switch the ROM and experience DSI crash.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Latest FBA, WiiU Mocha CFW

**Comment by maroonsp1rit** [comment]
![image](https://user-images.githubusercontent.com/38431231/38813387-ccb4836e-415c-11e8-9ebc-7e0d261d1549.png)

Tested with the version line added.
