### ISSUE TITLE
Discord invitation on Retroarch.com is expired

### ISSUE THREAD

**Issue by Stevoisiak** [libretro/RetroArch#6579]
## Description

On the [Retroarch homepage](http://www.retroarch.com), the invitation link to join the RetroArch Discord channel has expired.

### Expected behavior

Clicking the Discord button should open the RetroArch Discord channel.

### Actual behavior

Clicking the Discord link opens a notice that [the invite is invalid or expired](https://discord.gg/mrGzVrT).

### Steps to reproduce the bug

1. Open http://www.retroarch.com
2. Click the *Discord* button on the top of the page.

**Comment by gouchi** [comment]
It is fixed with [this commit](https://github.com/libretro/www.retroarch.com/commit/63cf31de41912a8dabae0a79d5bb9a9adaf0b41f).
