### ISSUE TITLE
Lost on the command-line

### ISSUE THREAD

**Issue by Earnestly** [libretro/RetroArch#6598]
This might end up being a long report.  I'll attempt to keep it short but this is the culmination of several years of on and off attempts to try recover my lost configurations and the past glory of retroarch, long before it grew a GUI.

So to start I should explain that my primary (and really, only) usecase for retroarch is the consolidation of configuration of many emulation systems.

It was on this basis that I recommended it to many people who shared similar desires.  At the time it was a constant battle of inconsistent configuration formats, configuration systems, missing features and the myriad of toolkits, some of which were custom (e.g. zsnes) which all got in the way and provided no credible scripting ability.

retroarch was incredible, it solved all of these problems while still being true to a kind of unix appreciation of clear configuration files, good (roff) manuals and a simple command-line interface.

The separation of roles was also seen in a tool called `retroarch-joypad` (if I remember correctly) that allowed one to configure a controller and print the resulting configuration to standard out.  It was perfect for me.

This is all gone now.  In order to configure the keybinds I start retroarch using `-c` with a sacrifical configuration file, configure the keybinds as I'd like them, then exit it out and try to recover the changes from the config before removing it.

My primary aim right now is to try and regain control over the retroarch.cfg. The current approach involves using `retroarch -c /dev/null` to prevent its generation from being saved anywhere while using `--appendconfig` to include organised configuration files as requirements dictate.

For example I will provide a `base.cfg` which contains the usual driver selections and other items I wish to change from the defaults.  Then I would like to include additional configurations for system specific cores such as Blargg's ntsc shaders (maybe there are glsl equivalents of these now).

The management of cores, roms and the command-line will be outside of retroarch as I use my own system for launching all sorts of other things.

The main issues are that this doesn't appear to work and I have no idea when it stopped working.  The `--appendconfig` option seems to register with `--verbose` and in some cases it changes the values it defines.  In some cases it does nothing, particularly when it comes to input.

For example:

* When just using `retroarch -c /dev/null` the default keybinds appear to work.

* When using `retroarch -c /dev/null --appendconfig input` where `input` contains
```
input_down = "nul"
```
or
```
input_player1_down = "nul"
```
the `down` key is still perfectly functional, as if the defaults are being used and the configuration is being ignored.

* What's more surprising is when it contains the following:
```
input_player1_down = "up"
```
This will result in the down key still working as a down key which further cemetes the idea that `--appendconfig input` is being ignored somehow.

Then there's issues with the documentation.  At one point I managed to get my control binds working with `--appendconfig` (I don't remember what I did unfortuantely) but the analog sticks would always not respond, even though they did during the configuration process.  From `/etc/retroarch.cfg` I read the following:

```sh
# Joypad w/ Analog (RetroPad + Analog sticks): 5
```

But when using `input_libretro_device_p1 = "5"` I get the following warning:

```
[WARN] Input device ID 5 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
```

What does this mean?  Also probably related, but why does retroarch tell me that the controller isn't configured?  I'm not sure what I am supposed to do in light of that message.

But here come the other problems.  Because some (if not most) are more philosophical I'm a little apprehensive even reporting them here as they don't tend to be well recieved on IRC due most likely to my poor communication.

Here goes anyway.

There are several things retroarch does which are completely unexpected and surprising to me which it never used to (before the rgui was added):

* Starting retroarch with `-c /dev/null` still creates dozens of unwanted directories.
* The generated retroarch.cfg contains 2858 lines as of writing, of which 2396 are "nul".
* Modifying the generated retroarch.cfg to remove the default "nul" keys causes it to be repopulated when next retroarch is run.
* Sometimes the order of the keys in the configuration file matter, such as `menu_driver` needs to come before `video_driver` as otherwise the `menu_driver` setting is ignored.

To me, these are serious breeches of "good software behaviour".  Tools should not at any point modify a user's configuration without at least being explicitly requested.  Configurations should never generate and write out default values (not only as a kindness, but this also interferes with upgrade paths).  The configuration file should be left to the user who bares sole responsibility for it.  It is completely unreasonable to have configuration files almost 3000 lines long.

I can however understand the otherside of this argument which is more about user-friendliness and while that is reasonable I always considered retroarch to be a more user-centric tool.

It has been very frustrating and I haven't managed to get any further forward with retroarch.  I'm not intending this to sound demanding and I don't want to demand anything but I would like to know what's going to happen to the command-line interface and where retroarch is headed in relation to my primary use-case.

Sorry for the wall of text, there's more but it's getting a bit much already.  Thanks if you managed this far.

**Comment by hizzlekizzle** [comment]
You can get rid of a ton of the useless "nul" input lines by changing the max players to "2".

The idea these days is: instead of juggling a bunch of config files, you map your pad to the retropad exactly once (or not even once if there's an autoconfig profile for it) and then you use remap files (that are automatically loaded based on core or content) to shuffle around the core's buttons on the retropad.

So, instead of passing CLI switches, you use directory structure to guide the automatic loading. You can set it up through the GUI or you can create the files/structures manually.

**Comment by Earnestly** [comment]
I don't personally want to use retroarch like that.

**Comment by Earnestly** [comment]
> we've opened the functionality up to more users.

I don't have anything against this, but does it have to come at the cost of the command-line use case?

**Comment by Ferk** [comment]
Following your instructions works for me. Though the input changes only have an effect in-game, not when moving around in the GUI.

To me, the biggest improvement for the command-line interface would be #746

I'd say that having Retroarch read input configuration from the directories set for that purpose actually makes using it from the command-line more comfortable than having to add a lot of parameters or wrapping the whole thing in a script.

**Comment by Earnestly** [comment]
That makes it quite tricky to test, but I'll keep that in mind when I try this again.

**Comment by Earnestly** [comment]
@Ferk That appears to work although `--appendconfig` appears to be broken insofar as it doesn't accept multiple configurations.

From the manual it states:
```
Multiple config files are delimited by ','.  Every config file will be appended
in order where the key-value pairs of the next config file takes priority over
the old ones.
```

But when using `retroarch -L ... -c /dev/null --appendconfig paths.cfg,input.cfg ...` I don't seem to get either the paths I want or the input.  It only works if `input.cfg` is exclusively used.

My basic `paths.cfg` looks like:

```ini
savefile_directory = "~/local/cfg/retroarch/saves"
savestate_directory = "~/local/cfg/retroarch/states"
```

However even with these defined, save states and saves still appear to end up in the same directory as the rom.

Additionaly I noticed via strace that retroarch is attempting to open files like:

```
openat(AT_FDCWD, "/dev/retroarch-core-options.cfg", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/dev/content_history.lpl", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
```

Which I assume it's attempting to use the dirname of `-c /dev/null` for some reason.

Not only all of this but retroarch still continues to create all sorts of unused directories under `XDG_CONFIG_HOME/retroarch` and I can't seem to prevent this.

**Comment by sonninnos** [comment]
`--help` has been saying this for ages:

>       --appendconfig=FILE        Extra config files are loaded in, and take priority over
>                                   config selected in -c (or default). Multiple configs are
>                                   delimited by '|'.

And it works fine here.
