### ISSUE TITLE
Travis CI builds failing on mingw since April 17th

### ISSUE THREAD

**Issue by stevoisiak** [libretro/RetroArch#6608]
## Description

All pull requests made since April 17th have [failed to build on Travis CI](https://travis-ci.org/libretro/RetroArch/builds) when compiling on `mingw-x64` and `mingw-x86`.

The last successful build was [#12346](https://travis-ci.org/libretro/RetroArch/builds/367417052) on April 16th.

The first build to fail was [#12347](https://travis-ci.org/libretro/RetroArch/builds/367417146), which links to commit https://github.com/libretro/RetroArch/commit/029019b75787812cf3eb7815c9dc43b78f95c7f5. (Merge #6586)

### Expected behavior

Pull requests should build successfully.

### Actual behavior

All pull requests are reporting a build status of failure.

### Steps to reproduce the bug

1. Make a pull request on GitHub.
2. Wait for Travis CI to finish building.
3. [Check build status](https://travis-ci.org/libretro/RetroArch/builds).

---

![Failing Travis CI builds](https://user-images.githubusercontent.com/1330770/39130721-d2e4654a-46db-11e8-83a5-873238860717.png)

**Comment by RobLoach** [comment]
```

CC frontend/drivers/platform_win32.c
gfx/common/win32_common.c: In function ‘win32_get_refresh_rate’:
gfx/common/win32_common.c:1288:4: warning: implicit declaration of function ‘GetDisplayConfigBufferSizes’ [-Wimplicit-function-declaration]
    result = GetDisplayConfigBufferSizes(QDC_DATABASE_CURRENT,
    ^
gfx/common/win32_common.c:1300:4: warning: implicit declaration of function ‘QueryDisplayConfig’ [-Wimplicit-function-declaration]
    result = QueryDisplayConfig(QDC_DATABASE_CURRENT,
    ^
CC gfx/drivers/gdi_gfx.c
CC gfx/drivers_context/gdi_ctx.c
CC gfx/drivers_font/gdi_font.c
CC gfx/display_servers/dispserv_win32.c
CC menu/drivers_display/menu_display_gdi.c
CC tasks/task_decompress.c
LD retroarch
obj-unix/release/gfx/common/win32_common.o:win32_common.c:(.text+0x1c66): undefined reference to `GetDisplayConfigBufferSizes'
obj-unix/release/gfx/common/win32_common.o:win32_common.c:(.text+0x1cd6): undefined reference to `QueryDisplayConfig'
/usr/bin/x86_64-w64-mingw32-ld: obj-unix/release/gfx/common/win32_common.o: bad reloc address 0x0 in section `.pdata'
collect2: error: ld returned 1 exit status
make: *** [retroarch] Error 1
```

Looks like we're missing a link to [GetDisplayConfigBufferSizes](https://msdn.microsoft.com/en-us/library/windows/hardware/ff566772(v=vs.85).aspx) in User32?

**Comment by Ryunam** [comment]
I think it’s related to https://github.com/libretro/RetroArch/pull/6586 based on @bearoso’s comments there.

**Comment by twinaphex** [comment]
@bparker06 could you add what @bearoso recommends to .travis.yml? Been getting spammed heavily over the mail with this.

**Comment by RobLoach** [comment]
> Been getting spammed heavily over the mail with this.

Unrelated, but made a PR to disable the notifications in your email box over at https://github.com/libretro/RetroArch/pull/6609 

Certainly would be good to clean up the Win32 build.

**Comment by orbea** [comment]
Travis is currently passing so I am going to close this issue.
