### ISSUE TITLE
RetroArch crashing on startup

### ISSUE THREAD

**Issue by PhoneboxCorgi** [libretro/RetroArch#6617]
I click the shortcut, and it crashes. 
I was having trouble earlier with it crashing when I tried to launch it through LaunchBox, but now it just plain crashes when I try to launch.
I start it up, and it goes gray screen without ever loading it's ACTUAL screen, and then I get "retroarch.exe has stopped working".
This is a fresh install of Windows and of RetroArch.

**Comment by orbea** [comment]
Do you have any stale retroarch.cfg files? Can you get a log with the debug executable? You will need to pass --verbose as an argument when launching it.

**Comment by twinaphex** [comment]
Too vague of a description to do anything with. Hopefully you can repost this with a better description of what is going wrong.

**Comment by RobLoach** [comment]
Going to close this. Feel free to re-open if you get the logs and .cfg. The issue template is helpful. Thanks!
