### ISSUE TITLE
[hid] 1.7.2 USB Controller Hotplug not working

### ISSUE THREAD

**Issue by tsoliman** [libretro/RetroArch#6640]
## Description

Retroarch 1.7.2 doesn't notice that controllers are plugged in after it has already started (on macOS 10.13.4). It does notice controller that were already plugged in when it started.

### Expected behavior

It should have a status message that the controller was plugged in and the controller should function. It should also do the same when a controller is unplugged while it is running.

### Actual behavior

No status message. The controller doesn't function. The controller isn't selectable in the user input screen.

### Steps to reproduce the bug

1. Start Retroarch 1.7.2
2. Plug in a controller (it isn't recognized)
3. Restart Retroarch while controller is plugged in
4. Controller is recognized

### Bisect Results

`v1.7.1` is good
`v1.7.2` is bad
82e2cc7c73a1f8b0693cdfec59e04665e99375c4 is the first bad commit

### Version/Commit

- RetroArch: 1.7.2

### Environment information

- OS: macOS 10.13.4
- Compiler: xcodebuild (Xcode 9.3)

**Comment by twinaphex** [comment]
Hi there, 

I fixed it for now by reverting this PR -

https://github.com/libretro/RetroArch/commit/82e2cc7c73a1f8b0693cdfec59e04665e99375c4#diff-a39a1d51f6fb455e21c7eb9d452db83a

I hope that this PR can still be submitted but this time with the add device callback still working.

**Comment by orbea** [comment]
This seems to have been fixed by the revert and then followup PR which has been merged a while ago so I am going to close this issue, please let us know if there are any other problems!
