### ISSUE TITLE
Analog inputs as digital does not function properly

### ISSUE THREAD

**Issue by prataczak** [libretro/RetroArch#6644]
## Description

Had a chance to test out the new remap options in the quick menu today. Tested with Castlevania and Mega Man 4 for Nintendo Entertainment System with the Mesen core. In Castlevania, I tried unassigning all D-Pad inputs, and mapping them to the right analog stick instead. Character on screen would keep walking even when analog is released - it seems that on/off switches are not working properly.

For Mega Man 4, I tried unassigning the B button, and remapping it to Right Analog X-. Normally when held, the B Button acts as a 'charge' shot in this game - but currently does not work properly. Pressing the right analog stick left makes him fire a single quick shot (unexpected behavior), then charge a shot as expected, but when released, the character keeps charging the shot, instead of releasing it.

### Expected behavior

Expected behavior is for the analog to function as a digital input, but it seems there's a few issues to work out.

### Version/Commit

- RetroArch: 1.7.2

### Environment information

- OS: Windows

**Comment by fr500** [comment]
Can't test right now but try this
Set this in your config `input_axis_threshold = "1000"`

And apply this diff:

```
diff --git a/input/input_mapper.c b/input/input_mapper.c
index 253ffcf112..6794fb85cb 100644
--- a/input/input_mapper.c
+++ b/input/input_mapper.c
@@ -191,7 +191,7 @@ void input_mapper_poll(input_mapper_t *handle)
                   settings->uints.input_remap_ids[i][k];

                if (
-                     (current_axis_value != 0) &&
+                     (abs(current_axis_value) > *input_driver_get_float(INPUT_ACTION_AXIS_THRESHOLD)) &&
                      (k != remap_axis)         &&
                      (remap_axis != RARCH_UNMAPPED)
```

**Comment by RobLoach** [comment]
Also, what input driver are you using?

**Comment by prataczak** [comment]
X Input.

Forgive my ignorance @fr500 but I do not know how to apply the diff, if you can point me in the right direction I will try it.

**Comment by fr500** [comment]
@RobLoach he's talking about remaps tho, it's completely independent of the driver
@prataczak  find the line with the minus sign in input_mapper.c, replace it with the line with the plus

**Comment by fr500** [comment]
I tested this and it works, feel free to integrate it tho I don't have my git key on this laptop

**Comment by fr500** [comment]
You don't need to make input_axis_threshold 1000 anymore, I didn't understand it was a porcentual value, I changed it so the default 0.5 should work fine
