### ISSUE TITLE
Achievements pop-up!

### ISSUE THREAD

**Issue by metspo** [libretro/RetroArch#6645]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Achievements wont "pop-up" when fps counter is shown, works if fps counter is disabled.]

### Expected behavior

[Achievement to "pop-up"]

### Actual behavior

[Nothing]

### Steps to reproduce the bug

1. [Complete an achievement]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.7.2/stable]

### Environment information

- OS: [Win 10 Pro N x64]
- Compiler: [In case you are running local builds]

**Comment by metspo** [comment]
Neither does anything else get thru, like "100%: save state slotx" this also works if fps counter is hidden.

**Comment by RobLoach** [comment]
By design... At the request from twinaphex, FPS/Frames counter has the highest priority of messages.
