### ISSUE TITLE
(Port) Nintendo Switch Build

### ISSUE THREAD

**Issue by iOS4all** [libretro/RetroArch#6660]
@twinaphex hi there.
Many people and I are waiting and really want to see the switch version of this amazing app ever.
As you see LibNX (wish is hombrew launcher on Nintendo switch) is officially supported JIT. So if we you can at least put it on the nightly build we'll be very grateful.
Thanks a lot for your efforts.

**Comment by iOS4all** [comment]
Any answer please?

**Comment by hizzlekizzle** [comment]
When we're ready to show something, you'll know it.
