### ISSUE TITLE
RA currently not building on Windows through MSYS2/Mingw64

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#6675]
Current code doesn't seem to be building with Mingw64 on my system. 
When trying to compile the latest code after doing a git pull from master, the system reports that config.mk is outdated or non-existing. However, when attempting to generate it again through ./configure it just stops and exits while checking for moc. 
Here's a log of what happens specifically:

$ ./configure
Checking operating system ... Win32
Checking for suitable working C compiler ... /mingw64/bin/gcc works
Checking for suitable working C++ compiler ... /mingw64/bin/g++ works
Checking for windres ... /mingw64/bin/windres
Checking for moc ... Not found. Exiting.

**Comment by Ryunam** [comment]
Just did a bisect and the first bad commit appears to be 791aaa00e19866a27fb965b03332fb718c4ec337. That's also when Travis builds started failing.

**Comment by bparker06** [comment]
@Ryunam Looks like moc is being checked for all the time, so if you don't have the qt package installed, configure will exit. Not sure how best to fix that while still being able to check for moc if you DO want it.

**Comment by Ryunam** [comment]
If the qt package is now required for building on Mingw, what would be the suggested way to install it? 
I have been following the official documentation to compile RA and I saw you updated the docs with a reference to Qt when packaging the software, but there's no mention of the package itself for the configuration phase, which is the issue I'm facing.

**Comment by bparker06** [comment]
For 64-bit the package needed is `mingw-w64-x86_64-qt5`. I guess we would need to decide if the qt package should be added to the docs somehow as well... it's quite large so not everyone may want to download it if they don't want to use the Qt GUI. @twinaphex thoughts?

**Comment by bparker06** [comment]
For now I simply changed it to not exit if moc isn't found. If later in the configure process the Qt libs are found, then it will try to build Qt in (and need to use moc, hoping it exists), but if they're not found, then moc won't be used and Qt won't be built. It's not perfect but it works for now.

**Comment by orbea** [comment]
This should be fixed now?

**Comment by retro-wertz** [comment]
it should be...

**Comment by Ryunam** [comment]
Yes, I confirm that this issue has been solved with the above-mentioned commit. Thanks!
