### ISSUE TITLE
Retroarch not opening: couldn't find or load Qt platform plugin "Windows in ""

### ISSUE THREAD

**Issue by altiereslima** [libretro/RetroArch#6676]
I tried launching the Retroarch in Windown 10 and got the following error:

"This application failed to start because it could not find or load the Qt
platform plugin "windows in "".

Reinstalling the application may fix this problem."

**Comment by JHorbach** [comment]
Same.

**Comment by dvessel** [comment]
Delete all the old .dll files before updating. I had the same problem but I think I fixed it by deleting any stale .dll files that weren't being overwritten when I extract redist within my install directory.

**Comment by JHorbach** [comment]
> Delete all the old .dll files before updating. I had the same problem but I think I fixed it by deleting any stale .dll files that weren't being overwritten when I extract redist within my install directory.

Edit: Actually, I'm not sure what fixed it. I downloaded the large portable 7zip file and installed all the new files after deleting my existing .dll's;
> 
Don't worked for me :(
