### ISSUE TITLE
crt-pi.glslp doesn't work on last version

### ISSUE THREAD

**Issue by lodgerz** [libretro/RetroArch#6682]
## Description
Hi,
video shader "/crt/crt-pi.glslp" doesn't work on 1.7.2 git version (black screen). On 1.7.1 it works.
i use ArchLinux 64-bit.

**Comment by hizzlekizzle** [comment]
Works fine here in Ubuntu 64-bit.

**Comment by orbea** [comment]
Works here too, if this is still a problem please post a new issue and follow the issue template, thanks!
