### ISSUE TITLE
Missing options in CRT Super Resolution.

### ISSUE THREAD

**Issue by alphanu1** [libretro/RetroArch#6698]
There are 4 available options for this. These are 0, 1920, 2560 and 3840 could these be implemented please.

# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by alphanu1** [comment]
@twinaphex it possible to implement these options? Currently the only way to set it is by editing the retroarch.cfg.

**Comment by orbea** [comment]
This seems to have been implemented, I see `Native`, `1920`, `2560` and `3840`. I'm going to close this, but please let us know if there is any further issues!
