### ISSUE TITLE
Cheevos: Leaderboard condition changes to RAIntegration.dll

### ISSUE THREAD

**Issue by Jamiras** [libretro/RetroArch#6705]
## Description

A few months ago, we noticed an inconsistency in how RAIntegration deserialized the leaderboard cancel condition. This has recently been corrected in the RAIntregration project. 

Examining the RetroArch cheevos implementation, I believe RetroArch is not correctly handling the alternate serialization format, so fixing RAIntegration should make RetroArch more compatible without any changes to RetroArch.

However, in the new implementation, we've added a shorthand notation that RetroArch does not currently support. The main point of this issue is to add support for that shorthand.

#### The inconsistency:
A leaderboard may be defined as follows:
* `STA:0x1234=8_0x5678=9::CAN:0x1234=6_0x5678=0::SUB:0x1234=9_0x5678=4`
This says:
* start if $1234 is 8 _and_ $5678 is 9.
* cancel if $1234 is 6 _or_ $5678 is 0.
* submit if $1234 is 9 _and_ $5678 is 4.

Note that start and submit use `_` for AND, and cancel uses `_` for OR.

The recent changes to RAIntegration make cancel also use `_` for AND. 'S' is used for OR, which is consistent with start and submit formats, and more importantly, consistent with achievement formats.

The next RAIntegration release will translate the existing cancel string "0x1234=6_0x5678=0" to "1=1S0x1234=6S0x5678=0", which will still parse as "$1234 is 6 or $5678 is 0". Once it's deployed, we'll manually update all existing leaderboard cancel conditions to use the corrected format and remove the translation layer from RAIntegration. Once the database is updated, RetroArch should start processing the cancel conditions correctly with its existing code.

#### Impact to RetroArch:
The changes mentioned above hint at, but don't actually mention that leaderboard conditions now fully support the same lexicon as achievements. Leaderboards can be written with both AND and ORs, as well as AddSource, SubSource, ResetIf, PauseIf, and HitCounts (though the last three don't really make any sense in the context of leaderboards). More importantly, this means that all condition processing uses the same functions so future additions to the lexicon are automatically available in all uses. 

Additionally, as the first change to the lexicon, a serialized condition starting with "S" is assumed to have an empty core group that evaluates to true. "S0x1234=6S0x5678=0" is the same as "1=1S0x1234=6S0x5678=0". To maintain the highest level of compatibility with RetroArch, existing cancel conditions that are manually modified will have the "1=1" core group. It is not required for future conditions, and because the lexicon is now shared, the same functionality will be available to achievements.

### Expected behavior

"S0x1234=6S0x5678=0" serialized condition set should evaluate to "$1234 is 6 or $5678 is 0"

### Actual behavior

"S" is not a valid first character in the serialized condition and the related achievement/leaderboard is ignored.

### Steps to reproduce the bug

Unfortunately, as this is new functionality that is not yet publicly available, the only way to reproduce this is to manually inject the string into memory.

**Comment by Jamiras** [comment]
Tagging @celerizer as requested.

**Comment by twinaphex** [comment]
@celerizer @leiradel Any input on this?

**Comment by Jamiras** [comment]
No. That's what we're going to do manually to the existing leaderboards for backwards compatibility. 

The only change that you should need to do is handle the case where a conditions starts with 'S':
`S0x1234=6S0x5678=0` is two alt conditions with an _empty_ core.

**Comment by Jamiras** [comment]
I believe the rest of the changes are already supported, but you should probably verify:
* `_` now means AND in the Cancel trigger (previously it was supposed to mean OR)
* Start/Submit/Cancel triggers now support the full condition lexicon, particularly:
  * AND (`_`)
  * OR (`S`)
  * ResetIf (`R:`)
  * PauseIf (`P:`)
  * AddSource (`A:`)
  * SubSource (`B:`)
  * HitCounts

**Comment by leiradel** [comment]
> The only change that you should need to do is handle the case where a conditions starts with 'S'

Ok, will do.

> _ now means AND in the Cancel trigger (previously it was supposed to mean OR)

RetroArch has always parsed Start, Submit, and Cancel the same way, which was a bug as I can see now.

> Start/Submit/Cancel triggers now support the full condition lexicon, particularly

RetroArch has always parsed these triggers the same way as cheevos triggers.

**Comment by Jamiras** [comment]
Shorthand notation is handled by the integrated rcheevos code.
