### ISSUE TITLE
Bounty: 31 khz CRT Support for Windows and Linux

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#6722]
Alphanu's 15 khz CRT support is complete and successful and he [expressed interest in fulfilling a bounty for 31 khz support](https://forums.libretro.com/t/retroarch-native-15khz-crt-support-bounty-suggestion-50/10124/264?u=hunterk), as well.

This issue is to get that ball rolling.

**Comment by twinaphex** [comment]
@hizzlekizzle Has this bounty been fulfilled?

**Comment by hizzlekizzle** [comment]
Yeah, I think so. I haven't gotten to test it, but I believe it's working and other people have tested it. However, I'm not sure if it's submitted yet.

@alphanu1 Is this already done in upstream? if so, you can collect on it whenever you like.

**Comment by alphanu1** [comment]
In all fairness I forget this was here lol

It is complete and working well.

**Comment by twinaphex** [comment]
Hi there @alphanu1,

you can claim this bounty now. Just submit a solution and I'll approve of it.

BTW - since I felt that it wouldn't be right letting you walk out with only $15, I added an extra on top. Thanks a lot for the great work!

**Comment by alphanu1** [comment]
Thanks @twinaphex

The solution should be on bountysource. Let me know if theres issues.

**Comment by alphanu1** [comment]
@hunterk @twinaphex Can we close this issue off now? This has been fully implemented into RetroArch.
