### ISSUE TITLE
[QT] SIGABRT when launched after already loading some content

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#6726]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

QT browser thing crashes when it is launched after already have launched some content.

### Expected behavior

should safely swith in or out of qt regardless of when invoked.

### Actual behavior

crash

### Steps to reproduce the bug

1. open retroarch (do not launch or switch to QT browser (F5)).
2. open any content (was using NES and nestopia for example). let it run a few secs. then close content.
3. launch QT (using F5, dunno if theres anyther way) and run a content (using "Run" at bottom left)
4. this should crash all the time.

alternate method
1. run retroarch
2. run content (NES was what i tested)
3. press F5 or launch QT
4. close content
5. crash!

### Bisect Results

https://hastebin.com/epodolamab.py

https://github.com/libretro/RetroArch/commit/e3712182bdabfbb0d693ed55ceeec8bb4216b8ca

Version/Commit

You can find this information under Information/System Information

    RetroArch: 1.7.3 commit 2771f8c

Environment information

    OS: linux arch
    Compiler: gcc version 7.3.1 20180312 (GCC)

**Comment by orbea** [comment]
No backtrace?

**Comment by orbea** [comment]
Maybe related, but I can open the Qt ui while content is running fine, but if I then close that content RetroArch closes immediately with.
```
$ retroarch
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_setspecific': Invalid argument.  Aborting.
Aborted
```

**Comment by retro-wertz** [comment]
thats basically what happens in alternate method i posted... i may have not posted it or emphasize it clearly though.

**Comment by orbea** [comment]
Ah, I was expecting a segfault when I read this issue.

That said there is a segfault when closing RA that seems related to Qt, but it only happens when I'm not expecting it so I haven't been unable to try debugging it yet...

**Comment by retro-wertz** [comment]
here's where the problem starts....

big thanks for tracing this....

**Comment by orbea** [comment]
That doesn't really make much sense, that touches only Qt code? Can you check if the problem also exists with `./configure --disable-qt`?

**Comment by orbea** [comment]
Sorry, I thought I was replying to a different issue...

Why did you close this, was it resolved?

**Comment by retro-wertz** [comment]
no, its not resolved

**Comment by bparker06** [comment]
Confirmed here with archlinux also, on latest commit.

**Comment by bparker06** [comment]
Probably related to this:

```
bool QCoreApplication::hasPendingEvents()
Note: this function is not thread-safe. It may only be called in the main thread and only if there are no other threads running in the application (including threads Qt starts for its own purposes).
```

In my own backtrace (yours did not include all threads), I can see there is a QThread running, so that may be related.

**Comment by bparker06** [comment]
c2ad8d47d3 fixes this for me.

**Comment by orbea** [comment]
This is fixed here too.

**Comment by orbea** [comment]
@retro-wertz When you have some time can you check if this is fixed for you too? :)

**Comment by retro-wertz** [comment]
done
