### ISSUE TITLE
(Menu) WIMP GUI Recommendations

### ISSUE THREAD

**Issue by brandleesee** [libretro/RetroArch#6734]
![Missing F?](https://i.imgur.com/v9DqmQB.png)
- Second bullet has the F number missing.

![Layers](https://i.imgur.com/QBuafXn.png)
- F1 does not bring the Big Picture Menu. However, closing the WIMP GUI window brings forth the back layer, which is effectively the BPM.

![Different Icon](https://i.imgur.com/00ArH1P.png)
- Third _window_ in taskbar (which is the WIMP GUI) has different icon.

**Comment by fr500** [comment]
> Second bullet has the F number missing.

No.. it's F
as in F not Fsomething

**Comment by brandleesee** [comment]
> No.. it's F
as in F not Fsomething

Well understood, thank you.
