### ISSUE TITLE
No function on F5

### ISSUE THREAD

**Issue by TheDonAlex** [libretro/RetroArch#6739]
Ive installed RetroArch 1.7.3 without any backups on my Windows 10. If i press F5 nothing happens, where is the problem, how can I oben WIMP?

**Comment by orbea** [comment]
Where did you install RetroArch from?

If you run RetroArch from a terminal with `retroarch --features` does it show that Qt support is enabled? For example here it will show.
```
retroarch --features
...
  Qt:
		Qt UI companion support: yes
...
```

**Comment by TheDonAlex** [comment]
From here, http://www.retroarch.com/?page=platforms

The Windows Installer. 
(I don't even know, what a terminal is)

**Comment by bparker06** [comment]
Only the mingw (Windows 7/8/10) version supports the WIMP UI, not any of the msvc builds... maybe you grabbed the XP version by mistake?

**Comment by TheDonAlex** [comment]
I do... silly me...
Thank you very much for your help!
Solved.
