### ISSUE TITLE
(Menu) Add rewind_buffer_size =  setting to rewind setting by default

### ISSUE THREAD

**Issue by prataczak** [libretro/RetroArch#6743]
## Description
Apologies if this is not the appropriate place to put this. I consider it a bit of an oversight that this setting is not in the menu by default. When I play a playstation game, by default, I can rewind for about .5 seconds, because the default rewind buffer is too small. I had to go to the forum and find a thread buried deep to even find out about the rewind_buffer_size = line that you can manually add to your RetroArch config. This setting should exist in the menu by default in the rewind settings.

### Expected behavior
Ability to increase the rewind buffer size, as your own personal setup allows

### Actual behavior

No setting, have to manually add the line to the config file.

### Environment information

Windows 10, Retroarch 1.7.3

**Comment by RobLoach** [comment]
"Rewind Granularity"?

**Comment by prataczak** [comment]
Rewind granularity if I'm not mistaken affects how many frames you can rewind per second. The issue here is that the buffer is too small. If you have a gaming PC with a lot of RAM, it would be useful to increase the rewind buffer substantially from the menu.

**Comment by RetroSven** [comment]
@prataczak this was actually implemented a little while ago

**Comment by RobLoach** [comment]
Going to close this one for now. Feel free to update to master, and test it out... Open up the issue again if it doesn't meet your needs. Thanks!
