### ISSUE TITLE
Vulkan Issues

### ISSUE THREAD

**Issue by KristopherTadlock** [libretro/RetroArch#6748]
Windows 10 x64 bit
Nvidia GTX 1080 driver v. 197.55
Haswell Quad Core CPU

Test on Retoarch v 1.6.4, 1.7.1, and latest nightly build

On the latest nightly build and v 1.7.1, the vulkan driver crashes immediately. 

On RA 1.6.4 Parrellel64 will load a black screen. I can alt tab into the game, but vysnc is not working. Resizing the window, changing the aspect ratio, or otherwise doing anything to modify the display causes an immediate crash. Forcing vsycn in the display driver has no effect. I also tested with Mednafen PSX with the hardware render. 

As of this writing, my version of windows 10 is completely up to date. Feature update 1803.

I tried several nvidia driver versions including 182.53, 187.11, 197.31, and 197.55. 

I tried the Vulkan Threaded Fish demo and it ran fine. I also tried DOOM 2016 in vulkan mode and it ran fine.

**Comment by hizzlekizzle** [comment]
If you're testing with N64, the Windows builds have dropped the Vulkan-native renderer for threaded Angrylion (a software renderer), but you have to enable it *before* you switch to Vulkan or it will keep trying to use the default GL renderer and insta-crash.

Beetle-PSX-HW should use either Vulkan or GL automatically, whichever you have selected as your video driver.

**Comment by hizzlekizzle** [comment]
Yes. Assuming you're using Vulkan right now. Open RetroArch but don't load any content yet. Then, go to settings > driver and change to the GL video driver. Close RetroArch. Reopen it. Load a game with ParaLLEl-N64. Go into the quick menu > options. Change the gfx plugin to Angrylion and the RSP plugin to cxd4/LLE. Close content. Load another N64 game (can be the same one if you want). It should now be running in native resolution and probably using a *lot* of CPU. If so, congratulations, you're using Angrylion RDP.

Now, close RetroArch. Reopen it. Go to settings > driver and change the video driver to Vulkan. Close RetroArch. Reopen it. Try to load another N64 game (can be the same one if you want). It shouldn't crash.

Note: all of the "close RetroArch; reopen it" steps are to force writing configs and ensure that no overrides are loading and conflicting and/or stopping config writes.

**Comment by KristopherTadlock** [comment]
Thanks hizzlekizzle. I had no idea angrylion worked in openGL. It didn't use to be selectable in anything but vulkan. 

I have to withdraw my bug claims then. Using the nightly build of retroarch and configuring everything properly, vulkan is working great.

**Comment by hizzlekizzle** [comment]
np! Angrylion is a software renderer, so it works with any video driver. We switched over to it for Windows builds instead of using the similar-but-Vulkan-only ParaLLEl renderer because it works with all of the different video drivers and is still relatively fast (in Windows; it's a lot slower in Linux for some reason, so we still use ParaLLEl there).
