### ISSUE TITLE
Cannot switch onscreen overlays while in-content when using the vulkan video driver (android)

### ISSUE THREAD

**Issue by johanbcn** [libretro/RetroArch#6753]
## Description

On android, using the vulkan video driver and the default onscreen overlay, pressing any button that switches the overlay (rotate button, dpad-to-analog button, resize buttons...) removes the overlay completely.

Works fine if the video driver is gl.

### Expected behavior

The onscreen overlay should switch to another onscreen overlay configuration. 

### Actual behavior

The onscreen overlay disappears.

### Steps to reproduce the bug

1. Start with a fresh install from the play store (ensure that the Retroarch directory is gone from the user storage)
2. Configure the video driver to vulkan, download any core, and quit to save the configuration.
3. Start Retroarch again, load some content and try any of the overlay buttons that switch the overlay while in-game (d-pad to analog, screen rotation, ...).
4. The overlay should be gone.

### Bisect Results

Started to use RetroArch on android since at least version 1.7.1 and this bug has always been there.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.3/91744d9

### Environment information

- OS: Android 8.1
- Compiler: Clang/LLVM (3.8.256229 ) 32-bit (version from Google Play Store)

**Comment by hizzlekizzle** [comment]
confirmed.

**Comment by twinaphex** [comment]
Confirmed, and identical to this - https://github.com/libretro/RetroArch/issues/7228

I'm closing this issue so that all attention can go towards the other issue. You can post there as well with your findings.
