### ISSUE TITLE
Retroarch segfault after upgrade to 18.04

### ISSUE THREAD

**Issue by cmcginty** [libretro/RetroArch#6762]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Segfault after upgrade to 18.04

### Actual behavior

```
[  170.005001] retroarch[4152]: segfault at 1 ip 000055ff552df936 sp 00007ffcc7ce2d00 error 4 in retroarch[55ff5518d000+6a9000]
```

### Steps to reproduce the bug

1. retroarch

- RetroArch: [version/commit]
1.7.1-r201804250003-d65b387-74~ubuntu18.04.1

### Environment information

- OS: Ubuntu 18.04

**Comment by cmcginty** [comment]
First off I think the ubuntu version is incorrect:

```
retroarch --version
RetroArch: Frontend for libretro -- v1.7.2 -- d65b387 --
```

I removed my 1.7.0 config file and it is able to start. I guess there is something that changed between 1.7.0 and 1.7.2 that is not being handled at startup. Are there any known issues around config segfaults?

**Comment by i30817** [comment]
Your best bet is to debug it on a retroarch you built yourself wiith that defective config file.

**Comment by cmcginty** [comment]
Figure it out, the bad line was:

    xmb_scale_factor = "2"

I removed the line and it came back as:

    xmb_scale_factor = "100"

**Comment by RobLoach** [comment]
Glad it worked! It can be fun to set the scale to `"2"` and play FIND THE UI.
