### ISSUE TITLE
Wayland and retroarch KMS don't play together well because retroarch doesn't use either systemd-logind or setuid to acquire drm priviledges

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#6763]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Basically the same issue as https://github.com/libretro/RetroArch/issues/2248 but in a new environment.
Lakka avoids this by always being root (ugh) and not having a desktop.
Users *can* start retroarch in KMS mode in normal linux if they move out to a tty before login (in the gdm3 screen), but the games can start failing after the first emulator launch occasionally (i don't know the exact reason but it's not every time after it fails once which suggests a race condition). But more importantly after doing this they can't open the gdm3 screen again. Which is bad.

### Expected behavior

Retroarch should just depend on systemd-logind and use it as appropriate. Like gdm3 does iirc. It doesn't require the whole systemd package either. The alternatives are:
1. setuuid for the whole of retroarch... yeah, no, because you're supposed to drop this when you don't need it anymore and retroarch needs it for all cores and its gui, which makes it the same thing as running in root all the time? Not sure about this and not sure if systemd-logind is equivalent.
2. just keep on crashing randomly.

### Actual behavior

Mysterious code crashes at runtime, `wl_drm@10: error 0: authenicate failed` (sic) when starting retroarch, possible gdm3 hang, no cores actually starting if you manage to open retroarch when wayland is running (this is possible because apparently `wl_drm@10: error 0: authenicate failed` is not fatal to retroarch).

### Steps to reproduce the bug

Just start retroarch from a tty on ubuntu 18.04 while not being root (or on lakka), on two cases, before starting wayland (from switching to a tty from gdm3) and after. Try out a few games and cores on case 1 and you'll eventually find one that crashes reliably (idk why they don't crash always) and gdm3 is impossible to return to (even after retroarch is closed or segfaults), and on case 2 you won't be able to start any game.

Figure out this is probably caused by this: https://stackoverflow.com/questions/29708596/drmdropmaster-requires-root-privileges

and probably the root cause of a 2015 bug:
https://github.com/libretro/RetroArch/issues/2248

Something to watch out for is that the user needs to be part of the input group to avoid a softlock that needs a hardware reset if you open the retroarch search menu in KMS which is another bug i opened.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: ubuntu 18.04 bionic x86-64

**Comment by i30817** [comment]
Ok, obviously if you switch out of gdm3 before login to wayland, it drops its drm master status, and retroarch implicitly gains it by opening the right file descriptor through the opengl api.

This is fine, but what's intriguing me is that some games run and some crash in this situation. Maybe some code paths try to close and reacquire the FD by re-initializing opengl, which works out badly when the 'implicit master' never dropped his privileges, even if it's the same process ?.

Some cores are of course, sub-processes, but i thought that most RA cores being .so files were actually not subprocesses.

**Comment by i30817** [comment]
Edit: actually it's probably because those games try to change resolution and thus change the video mode as per info here:
https://github.com/libretro/RetroArch/issues/2248#issuecomment-148966309

**Comment by orbea** [comment]
I'm going to close this in favor of the more general issue https://github.com/libretro/RetroArch/issues/6763 which when solved should also resolve this issue.
