### ISSUE TITLE
Bounty - Amiga CD32 core with support for 2 player gaming (Support for Android as a minimum)

### ISSUE THREAD

**Issue by Gazdaman** [libretro/RetroArch#6766]
Description
Amiga CD32 core for RetroArch:
I am taking the initiative to get this bounty kicked off. 
I have pledged $10 to start it off and will try to add to my pledge once I have more funds available. I hope others will support this bounty.

Feature requests: 
CD32 Support
2 Controller Support for 2 player gaming 
Support for Android platform as a minimum
WHDLoad support would be good.
Support of uae configuration files if possible
Save game support

Bounty hunter can choose the best / most appropriate emulator to port.
They can either use an existing core and add in these features or select a new emulator to build the platform.

Bounty Source Link:
https://www.bountysource.com/issues/58221940-bounty-amiga-cd32-core-with-support-for-2-player-gaming-support-for-android-and-rpi3-as-a-minimum

Forum link to the initial discussion:
https://forums.libretro.com/t/amiga-cd32-a-console-based-on-the-amiga-1200-only-core-for-rpi3/12669

### Expected behavior
[What you expected to happen]
To be able to play games as 2 player on Amiga & Amiga CD32 at acceptable speeds

**Comment by i30817** [comment]
related: https://github.com/FrodeSolheim/fs-uae-launcher/issues/61

**Comment by qclart** [comment]
There's a WIP libretro version of FS-UAE, arguably the best Amiga emulator out there that supports CD32, at https://github.com/libretro/libretro-fsuae
It hasn't seen any activity since Feb 2017 but was worked on by the maintainer of FS-UAE @FrodeSolheim.  The best bet is to try to motivate him or someone else to pick this up and get it into a healthy state.

I am currently using libretro P-UAE which is the most complete of all the UAE ports and works well enough but is far behind all the commits and fixes that have gone into FS-UAE.  It generally works well although buggy but is missing essential features such as 2-player, keyboard mappings, CD32 support, and is very clunky to get set-up.  Furthering this core is also another option but P-UAE appears to be abandoned so the actively maintained FS-UAE would serve as the better base.

**Comment by i30817** [comment]
> There's a WIP libretro version of FS-UAE, arguably the best Amiga emulator out there that supports CD32, at https://github.com/libretro/libretro-fsuae
> It hasn't seen any activity since Feb 2017 but was worked on by the maintainer of FS-UAE @FrodeSolheim. The best bet is to try to motivate him or someone else to pick this up and get it into a healthy state.
> 
> I am currently using libretro P-UAE which is the most complete of all the UAE ports and works well enough but is far behind all the commits and fixes that have gone into FS-UAE. Libretro P-UAE generally works well although buggy but is missing essential features such as 2-player, keyboard mappings, CD32 support, and is very clunky to get set-up. Furthering this core is also another option but P-UAE appears to be abandoned so the actively maintained FS-UAE would serve as the better base.

The reason fs-uae works so well, is not the emulator itself, but the launcher, which uses a online database to setup the games configs and allows to boot whdloads directly into the game as if they were a hard drive (it creates a cache and maintains it ofc).

Without that functionality it's simply just another uae port.

**Comment by Gazdaman** [comment]
Threw another $10 in to the pot for this.
Hopefully someone picks this up and develops a core.

**Comment by Gazdaman** [comment]
Another $10 into the pot

**Comment by Gazdaman** [comment]
$20 more into the pot.
Are you interested @FrodeSolheim

**Comment by sonninnos** [comment]
This should take care of this: https://github.com/libretro/libretro-uae/pull/187

**Comment by rsn8887** [comment]
I think @sonninnos should be awarded this bounty. I am not sure how this is done or who is in charge, but you should give him this bounty for getting CD32 to work. I tested it on OSX and Switch, and it has been tested on Android, too, I think.

**Comment by twinaphex** [comment]
Hi there, I'm willing to close the issue so @sonninnos can submit a solution to Bountysource. From that point on, all bounty backers have to agree to the solution.

Can any of the backers let me know if they feel fine with this?

**Comment by Gazdaman** [comment]
Hi,
I am the bounty creator and main contributor to the bounty funds.
I'm happy for this to be closed and for the bounty to be claimed if it is confirmed to work with 2 player controls.

Sorry but I have not been able to test it at the moment.
If it all works as requested, great work :)

**Comment by sonninnos** [comment]
Yes, the core has supported 4 player controls for a while now. CD32 pads only works on ports 1+2 though.

**Comment by twinaphex** [comment]
Alright, closing this then.
