### ISSUE TITLE
left icon in playlist

### ISSUE THREAD

**Issue by PowaBanga** [libretro/RetroArch#6767]
Hi all,

There is a black square at the left of my game's name in playlist

I found how to set the main icon for a playlist, but i really don't found how to set the second icon who is left to the game name.

Somebody can help me ? :)

**Comment by RobLoach** [comment]
Which database? What's the name above the black square.

**Comment by PowaBanga** [comment]
Ok I was wrong, it was because I used `Game-content` icon at the place of `Game` simply

Thank you for your answer :)
