### ISSUE TITLE
Screensaver/dimming functionality

### ISSUE THREAD

**Issue by SCheeseman** [libretro/RetroArch#6771]
I've been preparing to setup Lakka for an OLED TV, but the potential of burn-in, particularly in menus, concerns me. Much like Kodi has built in screensaver and dimming functionality, Retroarch should probably have the similar functionality for displays with a potential for image persistence problems, including CRTs. A simple fade after X seconds, black after Y seconds would work well enough. Could possibly also do neat things with the cover art assets and screenshots.

**Comment by RobLoach** [comment]
You might want to move this over to https://github.com/libretro/Lakka-LibreELEC .

**Comment by orbea** [comment]
This is an OS issue and not something that can be fixed in RetroArch. If this is still a problem for you please re-post the issue here.

https://github.com/libretro/Lakka-LibreELEC/issues
