### ISSUE TITLE
Slow motion broken in RetroArch 1.7.3

### ISSUE THREAD

**Issue by prataczak** [libretro/RetroArch#6773]
## Description

Slow motion was working in RetroArch 1.7.1, but in 1.7.3, neither the toggle or the hold key seems to do anything.

### Expected behavior

You map a slow motion toggle or hold key in settings/input/input hotkey binds, and you press the key in a commonly used core like Mesen or BSNES, and slow motion occurs.

### Actual behavior

Nothing happens.

- RetroArch: [version/commit]

The most recent stable version of RetroArch 1.7.3 for Windows 10, 64 bit.

**Comment by prataczak** [comment]
I don't have hardcore achievements enabled by default. Are you on windows 10?

**Comment by fr500** [comment]
Yes, and I'm on the latest commit, it's working fine if I disable achievements.

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/pull/6669/files it was fixed post 1.7.3, please close this issue

**Comment by prataczak** [comment]
Ok, I have to turn off achievements altogether, then it works. That wasn't the behavior in the previous versions of RetroArch.

It makes sense for that to be disabled for hardcore mode, but for normal mode, you should still be able to use slow mo (since rewind works without issue, and that's the bigger potential cheat).

**Comment by fr500** [comment]
That is fixed already

**Comment by prataczak** [comment]
Are you sure? I downloaded the latest nightly earlier, and it had the same behavior.

**Comment by prataczak** [comment]
It looks like someone intentionally made it so that if cheevos are enabled *at all,* slow mo gets turned off (I'm guessing). It should only be that way for hardcore mode.

**Comment by fr500** [comment]
hmmm then maybe it needs this to be merged
https://github.com/libretro/RetroArch/pull/6667/files

I don't feel like wrapping it up right now though

**Comment by fr500** [comment]
PR is merged gitve it a shot

**Comment by fr500** [comment]
Fixed

**Comment by prataczak** [comment]
I just updated to the latest nightly, and it is indeed fixed. Closing the issue. :)
