### ISSUE TITLE
FBA WiiU broken

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#6777]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Loading any game on FBA causes a crash

### Expected behavior

It should work normally. More info here https://github.com/libretro/fbalpha/issues/202

### Actual behavior

[What is actually happening]

### Bisect Results

![image](https://user-images.githubusercontent.com/1721040/39972397-3ebc6ec2-56d4-11e8-9800-b0ebcc67f6d5.png)

6929db9fb6bdbe741b33e9cfbd3db1399cd92ac6 is broken, 9532a77b4f2701982e79c8f022c1c265e8c89a25 works and the commits in the middle are just D3D stuff

This is as far as we were able to bisect, it makes no sense

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

@cucholix helped me bisecting

**Comment by fr500** [comment]
You can find the compiled cores at each step here: https://files.andressm.org/d/b7c7e2960c024b05970b/

**Comment by barbudreadmon** [comment]
Any news about this ? I saw there was a bunch of commit by @twinaphex  to the fbalpha repo for this.

**Comment by fr500** [comment]
We built all the commits after build fix (skipped the merge PR commit)
here:
https://files.andressm.org/#common/lib/23c20bbd-f8b5-48f8-bdcc-f62c2717c2ba/Downloads/

It breaks at 9f2b56a
Which makes absolutely no sense

¯\_(ツ)_/¯

**Comment by fr500** [comment]
@gblues @QuarkTheAwesome

**Comment by gblues** [comment]
I'm testing a theory.

**Comment by fr500** [comment]
Cool! because nothing in that commit changes anything on WiiU front so I'm stumped

**Comment by gblues** [comment]
@fr500 I tagged you on a branch I created on my RA fork. Can you test against that fork and see if it crashes?

I think it has to do with the fact that the enums are changed by inserting a new value in the middle, which causes the "Wii U" enums to shift by 1. So maybe there's something somewhere using the raw enum value (8) instead of the mnemonic `MENU_VIDEO_DRIVER_WIIU` or `FONT_DRIVER_RENDER_WIIU`, in a code path only FBA is hitting? 🤷‍♂️

**Comment by fr500** [comment]
Ah yeah I thought that could be the case maybe it's refered to by index,
sounds plausible! I'll build and test in the morning with @cucholix

**Comment by cucholix** [comment]
![gblues_fba_build](https://user-images.githubusercontent.com/16081693/40276074-7af76e4c-5bce-11e8-9648-7b1c9c91971b.jpg)
I just tested @gblues build 6f12152

**Comment by barbudreadmon** [comment]
Hmmm could it be related to the size of the executable or something ? Did you try building it against a fbalpha core stripped of some drivers (`NO_MD=1 NO_PCE=1`) ?

**Comment by gblues** [comment]
Nah, it's not. We had a bad build. I gave @cucholix my build and it worked for him too.

Next step is seeing if it's one enum or the other, hopefullly not both.

**Comment by barbudreadmon** [comment]
Ok, that's good news ! The fact it only affects the fba core is weird though.

**Comment by gblues** [comment]
or not. Builds from master *also* work.

I tested with the 1.7.3 release and got a black screen, no DSI error. I then tested with the newest nightly, and it works.

Can anyone having this trouble please re-test with the latest nightly RPX? Because it's working on my system with mslug1.

**Comment by cucholix** [comment]
It's working with latest nightly, even CPS3, no idea what happened

**Comment by fr500** [comment]
ugh... I find the fact that it's working more worrying than the previous problem...

**Comment by barbudreadmon** [comment]
I think you can, while having other issues (speed and big endian), fbalpha doesn't crash anymore on Wii U.
