### ISSUE TITLE
(Linux) No DOSBox Core in Ubuntu PPA

### ISSUE THREAD

**Issue by stoz** [libretro/RetroArch#6780]
## Description

There is no DOSBox core in the Ubuntu PPA

### Expected behavior

`apt-cache search libretro dos` should show a DOSBox package

### Actual behavior

No package found

### Steps to reproduce the bug

`apt-cache search libretro dos`

### Version/Commit

- RetroArch: 1.7.3

### Environment information

- OS: Ubuntu 18.04 LTS 64-Bit Desktop

**Comment by hizzlekizzle** [comment]
Looks like there are packages in the testing PPA:
https://launchpad.net/~libretro/+archive/ubuntu/testing/+packages?field.name_filter=dos&field.status_filter=published&field.series_filter=

**Comment by stoz** [comment]
Thanks I'll give that a try. I should have read the "there are more Libretro Cores here" on the downloads page referring to the testing PPA.

**Comment by i30817** [comment]
not the only core broken in either ppa. Currently citra doesn't build 


```
CMake Error at externals/CMakeLists.txt:70 (add_subdirectory):
  The source directory

    /<<PKGBUILDDIR>>/externals/libressl

  does not contain a CMakeLists.txt file.


CMake Error at externals/CMakeLists.txt:71 (target_include_directories):
  Cannot specify include directories for target "ssl" which is not built by
  this project.
```

**Comment by gouchi** [comment]
ping @sergiobenrocha2

**Comment by hizzlekizzle** [comment]
sergio mentioned being busy IRL right now. In the short term, they should just change their core directory to the one in ~/.config/retroarch and use the cores from the online updater.

**Comment by i30817** [comment]
Yeah.... @hizzlekizzle i don't know if you actually use the ppa, but you can't actually download cores from that version of retroarch and everything is managed by apt-get/the ppa.

Which means that even if that setting existed ( i can't actually find it in this version ) people would still have no clue how to download the latest cores.

**Comment by hizzlekizzle** [comment]
@i30817 settings > user interface > views > show core updater

**Comment by i30817** [comment]
That view simply does not work on the ppa (because the 'core directory' is a read only part of the system) and is exactly the reason the setting was hidden by default.

Let's be clear: 'normal people' that try to install retroarch from a ppa in linux get less cores and the way to work around that is not only manual but bypasses entirely the upstream mechanism because it's not prepared to fallback on the core directory or the extraction core directory (if for some reason you don't want to support two alternative core directories and the priority problems that gives).

**Comment by orbea** [comment]
To be honest these issues are with the packaging at ubuntu and should be brought up with ubuntu maintainers. This is the wrong issue tracker.

**Comment by orbea** [comment]
We don't directly support distros here and I don't think anyone here can fix the PPA, as explained in the previous comment any issues with the PPA should be brought up with the PPA maintainers so the right people can see and address the issues.

If there is any issues with RetroArch or libretro cores then we can hopefully help.

I am going to close this as its not our issue.
