### ISSUE TITLE
Compilation error on Windows 7 64 bit for Wii U

### ISSUE THREAD

**Issue by cecilmax** [libretro/RetroArch#6781]
I try to follow the instructions to compile on wii u but I have this error:
https://docs.libretro.com/compilation/wiiu/

Any idea why ?

dynamic.c:(.text.init_libretro_sym+0x21a): undefined reference to `retro_serialize'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x222): undefined reference to `retro_unserialize'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x226): undefined reference to `retro_unserialize'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x22e): undefined reference to `retro_cheat_reset'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x232): undefined reference to `retro_cheat_reset'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x23a): undefined reference to `retro_cheat_set'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x23e): undefined reference to `retro_cheat_set'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x246): undefined reference to `retro_load_game'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x24a): undefined reference to `retro_load_game'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x252): undefined reference to `retro_load_game_special'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x256): undefined reference to `retro_load_game_special'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x25e): undefined reference to `retro_unload_game'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x262): undefined reference to `retro_unload_game'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x26a): undefined reference to `retro_get_region'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x26e): undefined reference to `retro_get_region'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x276): undefined reference to `retro_get_memory_data'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x27a): undefined reference to `retro_get_memory_data'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x282): undefined reference to `retro_get_memory_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
dynamic.c:(.text.init_libretro_sym+0x286): undefined reference to `retro_get_memory_size'
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: BFD (GNU Binutils) 2.27 assertion fail ../../../binutils-2.27/bfd/elf32-ppc.c:8812
collect2.exe: error: ld returned 1 exit status
make: *** [objs/wiiu/retroarch_wiiu.rpx.elf] Error 1

**Comment by fr500** [comment]
Seems you didn't read the note

**Comment by cecilmax** [comment]
what note ?

**Comment by fr500** [comment]
The first note in the doc you linked.

**Comment by cecilmax** [comment]
This ??
You need the DevkitPPC(r29) toolchain installed and the DEVKITPRO and DEVKITPPC environment variables set to the respective folders.

**Comment by fr500** [comment]
Uh... no

![image](https://user-images.githubusercontent.com/1721040/40070157-e5deff4e-5832-11e8-98a0-33f8150e40fd.png)

**Comment by cecilmax** [comment]
Ok, that is what ive done before change my devkitppc folder, I put the .a in the retroarch directory.. and I got the errors from my 1st post..

**Comment by cecilmax** [comment]
Hmmm ok, I have copied the .a in the retroarch folder, what could I do wrong then ?

**Comment by fr500** [comment]
`what are you running?, where are you running it?`

**Comment by fr500** [comment]
easiest route: copy the core (with the original name) to dist-scripts
run 

./wiiu-cores.sh

It should compile the core you copied into an rpx file.

**Comment by cecilmax** [comment]
Ok, how I have this error when I run the wiiu-coress.sh script..

CC wiiu/main.c
CC wiiu/system/memory.c
CC wiiu/system/atomic.c
wiiu/main.c:21:17: fatal error: fat.h: No such file or directory
 #include <fat.h>
                 ^
compilation terminated.
make: *** [objs/wiiu-salamander/wiiu/main.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by cecilmax** [comment]
I have copied the missing .h files into the wii uu dirrectory, almost there, but now I out of ideas, I have this error: 


make: *** [wiiu/wut/elf2rpl/elf2rpl.exe] Error 2
make: *** Waiting for unfinished jobs....
LD objs/wiiu-salamander/retroarch_wiiu_salamander.rpx.elf
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: cannot find -lfat
c:/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/6.3.0/../../../../powerpc-eabi/bin/ld.exe: cannot find -liosuhax
collect2.exe: error: ld returned 1 exit status
make: *** [objs/wiiu-salamander/retroarch_wiiu_salamander.rpx.elf] Error 1

**Comment by cecilmax** [comment]
I think I just dont have the correct version of libfat but I dont know which one to get :)

**Comment by Roet-Ivar** [comment]
@cecilmax did you ever solve your problem? I'm experiencing similar issues as you.

**Comment by cecilmax** [comment]
No :/

Sent from my iPhone
514-835-2335

On Apr 28, 2020, at 7:39 AM, Roet-Ivar <notifications@github.com> wrote:

@cecilmax did you ever solve your problem? I'm experiencing similar issues as you.

**Comment by QuarkTheAwesome** [comment]
This happens because you need to manually compile a core (like [snes9x](https://github.com/libretro/snes9x)) and copy it to `libretro_wiiu.a` during linking. I'm not sure what the exact issue OP had here was - could be a bug in the cores script?
Might be a good idea to adapt the wiiu makefile to provide a more descriptive warning in a missing-core situation.
