### ISSUE TITLE
[Request] Save-state Screenshot Quality

### ISSUE THREAD

**Issue by Quest79** [libretro/RetroArch#6783]
For save state screenshots, can we get the ability to change resolution and quality levels? 10MB per image starts adding up on 4k.

**Comment by Tatsuya79** [comment]
You can go into Settings->Video and put "GPU Screenshot Enable" to OFF to take internal resolution snaps.

**Comment by Quest79** [comment]
Hey Tatsuya, thanks. I've been having to use that.. It would be nice to be able to use a screenshot of what I actively see through and just have that scaled down to 25% and an option of jpg. I enjoy seeing that overlays and shaders I worked hard to perfect in the preview, but at 10MB per save over 1000s potentially it is too much! :(

**Comment by orbea** [comment]
I agree, at the very least a quality toggle similar to exporting images in gimp would be nice.

**Comment by sonninnos** [comment]
State thumbnails already prefer raw image data if possible.
