### ISSUE TITLE
[Request/Suggestion] Smarter File Tree Location in Files/Configs

### ISSUE THREAD

**Issue by Quest79** [libretro/RetroArch#6787]
So this is what we have currently. Example is a custom shader, but this happens in other areas.

```
noise1 = "E:\! Game\!! Emulation\RetroArch\shaders\shaders_glsl\film\resources/film_noise1.png"
noise1_linear = "true"
noise1_wrap_mode = "clamp_to_border"
noise1_mipmap = "false"
```

Now when you move your retroarch folder, or have it on a shared cloud drive its going to get very confused. I recently moved RA to another location and a lot of things that have the full address now break. Ideally when an address is recorded, it is best practice to use only the direct folders if dir paths are used in the way. So instead of

`noise1 = "E:\! Game\!! Emulation\RetroArch\shaders\shaders_glsl\film\resources/film_noise1.png"`

we get

`noise1 = "shaders_glsl\film\resources/film_noise1.png"`

And this will not break unless the file with the above dir is moved. So this is based on where the initial file lives and assumes from there to go down directories. 

There is another method that dynamically changes the dir records every-time a files moves, but that takes more code (like how shortcuts work even if you move where its pointing to to another hard drive). 

However this method will still break less and be far more portable than what we currently have. Thanks.

**Comment by fr500** [comment]
duplicate

https://github.com/libretro/RetroArch/issues/1326

**Comment by i30817** [comment]
I agree with this unsurprisingly. I also know the pain of preparing a otherwise unprepared program to have truly portable paths.

You need to take the base exec/config/caches paths *once* and make all of the other settings be a children of it. This is pretty invasive setting out. XDG helps if you're targeting linux only because it clearly lays out separation of concerns.

**Comment by RobLoach** [comment]
Closed ala fr500 in https://github.com/libretro/RetroArch/issues/1326 .
