### ISSUE TITLE
Bliss-Box Controller Names not Found in Linux, but Working in Windows

### ISSUE THREAD

**Issue by MizterB** [libretro/RetroArch#6789]
## Description

When connecting a Bliss-Box 4-play device to a Ubuntu host running the default configuration of RetroArch, RA recognizes the device, but does not recognize the pad type (NES, SNES, N64, etc.) and does not append that type to the device name.

### Expected behavior

RA should identify the type of controller attached to the 4-play, and update the internal device name so that controller autoconf profiles can be generated for each individual controller.

### Actual behavior

After the 4-play is detected, the following error is thrown:
[ERROR] [Autoconf]: Could not find or open libusb device 5840:3333.

The 4-play device name contains the port number, but not the connected controller name
[INFO] [Autoconf]: 0 profiles found.
[INFO] [Autoconf]: no profiles found for BLISS-BOX 4-PLAY PORT.1 (5840/3332).

The output should be something like this:
[INFO] [Autoconf]: no profiles found for Bliss-Box 4-Play SNES (5840/3332).

### Steps to reproduce the bug

1. Install default Desktop image of Ubuntu 16.04 or 18.04 Desktop
2. Compile RA 1.7.0 (first release supporting 4-Play) from source with all build dependencies, or precompiled 1.7.3 from the official PPA.
3. Start RA from the command line w/ verbose flag
[log.txt](https://github.com/libretro/RetroArch/files/2013312/log.txt)

4. Connect 4-play with controllers attached
5. See results in log file and UI
6. Behavior exists even when 4-play ports are reset.

### Bisect Results

Using the same RA versions and out-of-the-box configurations, this functionality works correctly on a Windows 10 system.  

Unclear if this same functionality is intended to work in Linux as well, and if so, are there non-default setting required to enable it?

### Version/Commit

- RetroArch: 1.7.0 (from source) & 1.7.3 (from PPA)

### Environment information

- OS: Ubuntu 16.04 & 18.04 Desktop fresh installs
- 4-Play: Latest firmware (v2.225, 5/6/2018)
- Host: Physical host and VMWare image

**Comment by MizterB** [comment]
I enabled libusb debugging on top of RA (`LIBUSB_DEBUG=4 retroarch --verbose`), and discovered that this was due to a permission issue.  Either libusb or RetroArch was requesting write access to the 4-Play USB device, and by default, that permission is only available to the root user & group.

The attached udev rule will resolve the issue (drop in /etc/udev/rules.d).  However, I'm not sure if the write attempt that is creating the problem can be modified somehow to prevent the issue in the first place. Is a write truly necessary, or can the device be opened just with a read?
[99-blissbox4play.rules.zip](https://github.com/libretro/RetroArch/files/2017189/99-blissbox4play.rules.zip)

Detailed debug log is also attached.
[libusb_debug.txt](https://github.com/libretro/RetroArch/files/2017180/libusb_debug.txt)

**Comment by MizterB** [comment]
Closing for now...the udev autoconf profiles I have provided mention the rules requirement if it is needed.

**Comment by bparker06** [comment]
Hi @MizterB,

Yes the write is necessary in order to request the specific pad type that is plugged in, this is used to override the default HID name provided by the Bliss-Box itself, so that RA is able to have different autoconfigs for each type of pad that is plugged in.

However, the udev rules you provided only works for one of the ports on the 4-play. This file I have been providing to people has all four ports in it:

http://0bl.net/99-blissbox.rules

**Comment by MizterB** [comment]
Makes sense - thanks for the update.  However, I do believe my rules file works...it's matching just based on the VID, and not specifying the PIDs for the different ports as yours does.  So it's a little bit cleaner - 1 line covering anything 'Bliss-Box', regardless of port.

**Comment by bparker06** [comment]
Ah my apologies, I must have read it wrong. Thanks
