### ISSUE TITLE
Savestates nonfunctional for GBC using Gambatte core on 3ds

### ISSUE THREAD

**Issue by bluesuitriot** [libretro/RetroArch#6795]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When using Retroarch 1,7,3 and Gambatte 0.5.0 with GBC games on a Nintendo 3DS, loading state crashes the console.

### Expected behavior

The state would load.

### Actual behavior

It attempts to load the savestate but consistently fails at 96%. the 3ds version uses the bottom screen to display a log and the last items are:

[INFO] Loading State: "sdmc/retroarch/cores/savestates/<gamename>.state
[INFO] State size: 59446 bytes.
[INFO] Saving state: "RAM"
[INFO] State size: 59446 bytes.

I think this may be related to the saved state used to undo the loaded state.

### Steps to reproduce the bug

1. Load a Game Boy Color ROM
2. Save state
3. Load State

### Bisect Results

I went back 3 versions of retroarch and they all were affected by the issue.

### Version/Commit

Retroarch 1,7,3 and Gambatte 0.5.0 
Build date May 4 2018
Compiler GCC (7.1.0)

- RetroArch: [version/commit]

### Environment information

- OS: New 3ds XL 11.6 (Luma 3ds)
- Compiler: GCC (71.10)

**Comment by fr500** [comment]
```
First and foremost consider this:

   - Only RetroArch bugs should be filed here. Not core bugs or game bugs
   - This is not a forum or a help section, this is strictly developer
   oriented

```

**Comment by bluesuitriot** [comment]
Isnt retroarch what handles the savestates and not the core?

**Comment by fr500** [comment]
Are other cores exhibiting the same problem?

**Comment by bluesuitriot** [comment]
They are not. It only seems to be the gambatte core.

**Comment by bluesuitriot** [comment]
I will post this in Gambatte-libretro repo. Thank you.

**Comment by orbea** [comment]
Closing this in favor of the issue in the correct repo which may be fixed?

https://github.com/libretro/gambatte-libretro/issues/103
