### ISSUE TITLE
[vita] Buttons referred to as A/B/X/Y in settings

### ISSUE THREAD

**Issue by Felthry** [libretro/RetroArch#6804]
## Description

The RetroArch settings in the Vita version still refer to the system buttons as A/B/X/Y.

### Expected behavior

Buttons are called ⬜/○/Ｘ/△

### Actual behavior

Buttons are called A/B/X/Y

### Bisect Results

(i have no idea what bisect means here)

### Version/Commit
You can find this information under Information/System Information

- Build date: May 4 2018
- Git version: b2ceb50

### Environment information

- OS: PS Vita firmware 3.60 with Henkaku Ensō

**Comment by fr500** [comment]
Try a nightly this is fixed.

**Comment by Felthry** [comment]
Seems to be mostly fixed, yes, thank you. I do see that there's still a "down+L1+R1+Y" option in the menu toggle gamepad combo settings.

**Comment by fr500** [comment]
That can't be "localized"
