### ISSUE TITLE
[Request/Suggestion] Show Configuration Override options

### ISSUE THREAD

**Issue by Alex9534** [libretro/RetroArch#6814]
## Description

An option (on/off) Show Configuration Override options in View->Quick Menu would be nice to able to hide it.

### Expected behavior

New option in My View->Quick Menu options:

https://www.subeimagenes.com/img/1-1882773.png

### Actual behavior

https://www.subeimagenes.com/img/4a-1880668.png
https://www.subeimagenes.com/img/4b-1880669.png

### Steps to reproduce the bug

1. Use Retroarch 1.7.3
2. Load a game
3. Press F1

### Version/Commit

Retroarch 1.7.3

### Environment information

- OS: Windows 7

**Comment by Brunnis** [comment]
This has already been fixed. See https://github.com/libretro/RetroArch/pull/6719

When you disable both game and core overrides, the "Configuration Override options" item is hidden from the Quick Menu.

**Comment by hizzlekizzle** [comment]
closing this. Feel free to reopen if we misunderstood the issue.
