### ISSUE TITLE
Cheevos: support for HitCount on ResetIf/PauseIf conditions

### ISSUE THREAD

**Issue by Jamiras** [libretro/RetroArch#6817]
## Description

The next version of the RAIntegration.dll is going to support `HitCount` behavior for `ResetIf` and `PauseIf` conditions. This behavior should also be supported by RetroArch.

_Note_:
There are a number of existing achievements that currently have `ResetIf HitCount(>1)` or `PauseIf HitCount(>0)`. These will be audited and corrected before releasing the next version of RAIntegration.dll.

### Expected behavior

* An achievement with a `ResetIf(3)` condition should only reset if the condition is true for three frames. 
* An achievement group with a `PauseIf(3)` condition should only pause if the condition is true for three frames. 
  * Note that a `PauseIf` with a `HitCount` does not unpause itself. It can only be unpaused by a `ResetIf` in a different group. A `PauseIf` without a `HitCount` should continue to unpause itself.
* `HitCount`s on these conditions should be reset normally by any `ResetIf` condition that is true.

_Note_:
These changes also support `AddSource`, `SubSource`, and `AddHits` for the `ResetIf` and `PauseIf` conditions. Feel free to contact me if you have any questions on the functionality.

### Actual behavior

Both `ResetIf` and `PauseIf` trigger on the first frame where the condition is true, regardless of the `HitCount` value.

**Comment by Jamiras** [comment]
Tagging @celerizer

**Comment by fr500** [comment]
also @leiradel
