### ISSUE TITLE
[LINUX] Dualshock 3 Bad Input

### ISSUE THREAD

**Issue by Joechim94** [libretro/RetroArch#6818]
## Description

Plugging in a DualShock 3 (PS3 Controller) on Linux results in garbage input and locks the keyboard in Retroarch.

### Expected behavior

Previous versions (before Linux 4.13) worked as expected. Install Ubuntu 16.04 for an example of working behavior. 

### Actual behavior

On Linux kernel versions 4.13 and higher (such as Ubuntu 17.04+), the dualshock3 does not work correctly at all. The issue affects other distributions, such as Arch Linux, as well.

I have attempted multiple controllers of this model.

### Steps to reproduce the bug

1. Run the latest Retroarch on a recent kernel
2. Update autoconfig profiles
3. Plug in Dualshock3

### Bisect Results

Attempting to switch the input drive to SDL2, or the joypad driver to SDL2, or any combination of udev and SDL2 results in no input from the controller.
This is strange as the DualShock3 continues to function correctly in Steam Big Picture and Steam games.

### Version/Commit
Observed in versions 1.7.1 - 1.7.3
Months later, the controller remains non-functional despite multiple releases of the kernel and the RetroArch software.

- RetroArch: 1.7.3

### Environment information

- OS: Ubuntu 17.10 - 18.04, Arch Linux

**Comment by hizzlekizzle** [comment]
I just merged an autoconfig profile that should work for newer kernels. Can you try to update your autoconfig profiles via the online updater (once they trickle down to the buildbot, presumably in a few minutes/hours) and see if it treats you any better?

**Comment by Joechim94** [comment]
That fixed it right up!

Thank you so much. I should have reported this a lot earlier but I didn't want to burden the issues system with something that might have gotten fixed.

Thanks for help, cheers!

**Comment by hizzlekizzle** [comment]
No problem. Thanks for confirming that it's working properly now :)

We've had the fix ready to go for a few months now, but I wanted to wait to merge it until the newer kernel trickled down to more distros. Now that Ubuntu 18.04 is out, I figured it's a good time.
