### ISSUE TITLE
[WiiU] Online Updater downloads not extracting.

### ISSUE THREAD

**Issue by meunierd** [libretro/RetroArch#6823]
## Description

Every icon looks like a sprite sheet of all icons.

UPDATE:

After following @uejji 's suggestion I noticed that assets.zip does download, but fails to extract. Manually extracting the file leads to behaviour that works as expected.

### Expected behavior

Individual icons like chevrons for directories and gears for settings etc.

### Actual behavior

Every single icon renders the same, as a sprite sheet of all icons.

### Steps to reproduce the bug

Open Retroarch from Homebrew Launcher 2.1

### Bisect Results

Present since 1.7.1 at least. Still present in 1.7.3. I'll keep looking back to see when it started.

**Comment by uejji** [comment]
You have to update the assets, either by manually copying them onto your SD card or by using the asset updater in RetroArch.

**Comment by meunierd** [comment]
Updating assets seems to have no effect.

**Comment by uejji** [comment]
Check your assets directory in RetroArch and compare it to the directory on your actual device (USB or SD).  The folder that RetroArch points to should contain the "xmb" folder, among others.  If not, either move the directory or change the setting within RetroArch.

You can also download the assets zip manually ( https://github.com/libretro/retroarch-assets/archive/master.zip ) and extract it yourself into RetroArch's assets directory.

**Comment by meunierd** [comment]
So it looks like assets.zip is there but the Online Updater doesn't extract
it. Manually extracting works though. I assume this is also why directory
scanning isn't working?

**Comment by uejji** [comment]
Hey.  Glad it worked.  I got directory scanning working by manually creating the playlists folder and manually copying the database folder from another system.  I'm not entirely sure if the former was necessary.

You might try manually creating the database folder before running the Database Update and see if that does the trick.

(By the way, I'm just another user like yourself)

**Comment by meunierd** [comment]
Thanks, I appreciate the help! The workaround does work, but I do think there's still an issue present with extracting files from Online Updater for Wii U.

**Comment by Littlemac123** [comment]
downloading more in 1 thing like 3 or 5 dues crash the wii u

**Comment by thirdeyechai** [comment]
> 
> 
> Check your assets directory in RetroArch and compare it to the directory on your actual device (USB or SD). The folder that RetroArch points to should contain the "xmb" folder, among others. If not, either move the directory or change the setting within RetroArch.
> 
> You can also download the assets zip manually ( https://github.com/libretro/retroarch-assets/archive/master.zip ) and extract it yourself into RetroArch's assets directory.

Where exactly is RetroArch's assets folder located? All my icons are garbled mess at the moment and the online updater isn't working.

**Comment by Clockwork-Creep** [comment]
Your retroarch.cfg file should have the path to your assets folder, by default it’s SD:/retroarch/media and the part that is likely tripping you up, is that you need to place the contents of the assets folder in media....so there will be no “assets” folder.
