### ISSUE TITLE
Latest Beetle PSX HW does not Load

### ISSUE THREAD

**Issue by TradeDraft** [libretro/RetroArch#6825]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When I load a Game Up it just comes up White and just makes the Sound of the PS1 Loading Up and then Nothing Happens

Using Stable 1.7.3 Windows 64 Bit Version

### Expected behavior

Load up the Game as Usual and Comes up to Play

### Actual behavior

Get White Screen and Sound of PS1 Bios Loading Up then can't do anything from there no sound and no picture

### Steps to reproduce the bug

1. Load up RetroArch 1.7.3
2. Load Up Game in to the Latest Beetle PSX HW 
3. Then Game Comes up and Says what I said
### Bisect Results

From the Last Beetle PSX HW Core I download. Nothing before That

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Windows 10 Home
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
Sorry, but this needs to be reported at the core's repo:
https://github.com/libretro/beetle-psx-libretro
