### ISSUE TITLE
[Linux] Some Systems don't produce Playlists

### ISSUE THREAD

**Issue by Joechim94** [libretro/RetroArch#6833]
## Description

For some systems, no playlist (collections) is generated on Linux but work fine on Windows.

### Expected Behavior

There should be no difference in playlist generation.

### Known Systems Affected

* Famicom Disk System
* MSX
* DOS
* NEC PC-ENGINE

### Steps to reproduce the bug

1. Take a working rom set from Windows for a known affected system
2. Scan directory for the files on a GNU/Linux System
3. Observe that no playlist is generated.

### Version/Commit
You can find this information under Information/System Information

- RetroArch 1.7.3

**Comment by RobLoach** [comment]
Did you update the databases on Linux? Are they found? Visit the Information menu?

**Comment by Joechim94** [comment]
Yes, the problem occurs on up-to-date databases.

**Comment by orbea** [comment]
There are some reasons scanning can fail.

* Missing database files.
* Missing info files.
* Content doesn't match the databases.
* Content missing from the databases.

There are not enough details to determine which one is true here, but if this is still a problem please make a new issue with more details like what content is not being scanned in the correct repo, thanks!

https://github.com/libretro/libretro-database/issues
