### ISSUE TITLE
[3DS] Dosbox Key Mapping

### ISSUE THREAD

**Issue by fr4j4** [libretro/RetroArch#6839]
Hi everyone, I just want to play some old DOS games on my 3DS.
I've remaped keys from the "input" menu but I can't move or interact in game (playing commander keen 4). 
Do i need to set up another thing to Dosbox recognize my buttons?

Greetings!

**Comment by RobLoach** [comment]
Dosbox uses the native keyboard controls, unsure how a keyboard maps on 3DS though. Mind making an issue over at https://github.com/libretro/dosbox-libretro , and closing this one?

**Comment by fr500** [comment]
Just go to controls, set input device to keyboard, change the inputs 

![image](https://user-images.githubusercontent.com/1721040/40696745-b2b6dd16-638c-11e8-83e5-c2bc130bc152.png)
![image](https://user-images.githubusercontent.com/1721040/40696757-bf0c40b0-638c-11e8-95b7-37ec0ddc63db.png)

As long as it's 1.7.2+ it should work

@fr4j4 also, please read and fill the issue template next time

**Comment by fr4j4** [comment]
Thx for answers! and sorry @fr500 next time i'll use the template.
