### ISSUE TITLE
(Menu) RGUI controls menu doesn't have user # labels

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#6843]
When using `Quick Menu -> Controls` to generate a new game or core mapping, RGUI don't have an indication of which user's controls are within the visible area:

![screenshot 2018-05-29 16 53 14](https://user-images.githubusercontent.com/19554678/40688155-b13b509a-6362-11e8-835d-9deb3f95f0a7.png)

This is as opposed to XMB which lists the user number below the RetroPad mapping:

![screenshot 2018-05-29 16 55 37](https://user-images.githubusercontent.com/19554678/40688180-c4fc1b78-6362-11e8-82a6-7122da4e741b.png)

**Comment by markwkidd** [comment]
@jdgleaver is there any chance this is an issue you'd be interested in looking at due to your work with RGUI?

**Comment by jdgleaver** [comment]
@markwkidd Sure, I guess. I don't mind taking a look at this. It won't be for a few weeks, though - I'm already working on something else, and then there's Christmas to contend with... :slightly_smiling_face:

**Comment by markwkidd** [comment]
That is only fair! :D Happy holidays

**Comment by jdgleaver** [comment]
@markwkidd Well, I found a few minutes to check up on this, and it turned out to be trivial. The issue should be closed by PR #7770.

**Comment by markwkidd** [comment]
Nice! Thank you

**Comment by orbea** [comment]
I can confirm the above PR by @jdgleaver fixed this, thanks!
