### ISSUE TITLE
Crash when using vulkan and minimizing

### ISSUE THREAD

**Issue by FirionHope** [libretro/RetroArch#6856]
## Description

When having Vulkan minimizing the window in any way will cause retroarch to instantly crash, also deletes all saves made since the last time you opened retroarch

### Expected behavior

The program to minimize

### Actual behavior

It crashes

### Steps to reproduce the bug

1. Set Vulkan as video driver
2. Restart Retroarch so it takes effect
3. Minimize

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.73, also happens on latest nightly

### Environment information

- OS: Windows 10 64 bit 1709

**Comment by twinaphex** [comment]
This should be fixed now in the most recent nightlies. 1.7.4 will fix this as a stable release.
