### ISSUE TITLE
(Netplay) Wii U Netplay not working

### ISSUE THREAD

**Issue by ReiOsumi** [libretro/RetroArch#6864]
## Description

Wii U Netplay fails to initialize, basically it prints "Waiting for client" "Failed to initialize netplay"

### Expected behavior

Netplay should work fine

### Steps to reproduce the bug

1. Start a game
2. Go to Netplay Rooms menu
3. Start netplay host

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.3 05/06/2018 build

### Environment information

- OS: Nintendo Wii U 5.5.2

**Comment by RobLoach** [comment]
You may need to ensure your router is forwarding the ports:
https://portforward.com/

It does depend on whether or not your network allows RetroArch doing it for you, however.

**Comment by ReiOsumi** [comment]
@RobLoach But in my pc works fine

**Comment by fr500** [comment]
It doesn't work yeah,  it fails initializing sockets in hosting mode

Errno returns 8

**Comment by ReiOsumi** [comment]
@RobLoach  I already did the port forwarding and it still does not work, I also put my ip public, in my pc works fine but in my wii u not 😞

**Comment by ReiOsumi** [comment]
Hello?

**Comment by RobLoach** [comment]
Hello. Guess the WiiU will need some netplay updates.

**Comment by twinaphex** [comment]
I think this finally works now.
