### ISSUE TITLE
Remote Retropad Core Config: /r/assholedesign

### ISSUE THREAD

**Issue by daviddavo** [libretro/RetroArch#6873]
Hello, the other day I was trying to configure the retropad retrocore on android. After I clicked more than 192+168+0+140 = 500 times, when I tried to save the config I didn't have enough permissions.
The thing is, why did you use such a system to config the IP address?
Shouldn't it be better to use something like a text entry, and then sanitize the output like when you try to connect to a netplay host?

File related:
https://github.com/libretro/RetroArch/blob/b11620e1ebbc19937d675a48bdefc04c1b0b7421/cores/libretro-net-retropad/net_retropad_core.c#L267-L278

**Comment by ICHx** [comment]
i like your title lol
Thanks all

**Comment by fr500** [comment]
There is no other way to do it, the core options API is extremely limiting.
