### ISSUE TITLE
Issue concerning specific faulty cheat for specific game

### ISSUE THREAD

**Issue by maslowk** [libretro/RetroArch#6879]
## Description

The "infinite lives" cheat included in "/cheats/Mega Man X6 (USA, Europe) (GameShark).cht" is faulty; it prevents you from selecting a specific character in the game.

### Expected behavior

Have infinite lives in Megaman X6

### Actual behavior

You get infinite lives, *and* selecting a specific character loads you into the stage with a different character.

### Steps to reproduce the bug

1. Load game file
2. Enable included "Infinite Lives" cheat and select "apply"
3. Go back to game, select "Zero" from character selection screen before entering a stage

### Bisect Results

Specifically happens with aforementioned cheat enabled, resolves itself after disabling cheat. 

### Proposed Solution

In the "Mega Man X6 (USA, Europe) (GameShark).cht" next to "Infinite Lives", replacing the current code
"800CCF08+0900" with "300CCF09+0009" completely resolves the issue, granting infinite lives with no additional effects.

### Version/Commit

- RetroArch: 1.7.2

### Environment information

- OS: Windows 10 Build 1803

**Comment by bparker06** [comment]
Can you just create a PR in libretro-database to fix this cheat? This isn't really the correct repo to report in.

**Comment by RobLoach** [comment]
As bparker06 mentioned, submit an issue over at https://github.com/libretro/libretro-database .
