### ISSUE TITLE
(PS3) Core Remap Overwrite Fail

### ISSUE THREAD

**Issue by MajinKaan** [libretro/RetroArch#6884]
Trying to create remap files in the PS3 version doesn’t work and gives an error message. This is pretty annoying, because having to manually change the button configuration every time I load a core is just tedious.

**Comment by fr500** [comment]
Well...
What's the error message?

You didn't fill the issue template, it's there for a reason.

**Comment by RobLoach** [comment]
Mind posing the logs?

**Comment by MajinKaan** [comment]
Idk where they’re located in the PS3 build and I did look through the retroarch folder. Also just delete this ticket as I posted a different ticket where I also mention this issue, but didn’t accidentally delete the issue template.

**Comment by RobLoach** [comment]
Recommend resetting your configs to default and seeing if it can write the remaps again.
