### ISSUE TITLE
(Core) Request for new core on 3ds/new3ds

### ISSUE THREAD

**Issue by tomjfmu3** [libretro/RetroArch#6886]
I have been using retro-arch gbsp core on the new3ds and it is extremely unstable. It always crashes on a lot of games bringing arm11 errors and prefetch abort. I was wondering If they could make a core for mGBA. mGBA is already an emulator on the 3ds, and I think it should be a core. mGBA is compatible with every form of gameboy: original, color, and advance. mGBA is much more stable than the gbSP core. gbSP always crashes on roms I liked to play and I was wondering if they could make a version of mGBA as a core. The original mGBA homebrew app for the 3ds is really stable, however it doesn't have any savestates, cheats, screen size options. If the core is brought to retroarch in the next release then it will have those options. Also if mGBA is added then it should have the 3ds/new3ds screen size, since mGBA has the original gameboy advance and sp resolutions which are a lot smaller. Please add the mGBA core to 3ds/new3ds. Thanks

**Comment by RobLoach** [comment]
Mind creating an issue for this over at https://github.com/libretro/mgba ?
