### ISSUE TITLE
Retroarch installed with snap don't open in linux with nvidia driver, libgl error

### ISSUE THREAD

**Issue by Nutriz** [libretro/RetroArch#6896]
### Expected behavior
Launch RetroArch :)

### Actual behavior
RetroArch don't open, I only see a little window for a half second

### Steps to reproduce the bug
1. install retroarch with `sudo apt install retroarch`
2. try to launch retroarch with desktop icon or bash
```
bungie:~$ LIBGL_DEBUG=verbose retroarch 
libGL: screen 0 does not appear to be DRI2 capable
libGL: OpenDriver: trying /snap/retroarch/118/usr/lib/x86_64-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /snap/retroarch/118/usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
libGL: Can't open configuration file /home/nutriz/snap/retroarch/118/.drirc: No such file or directory.
libGL: Can't open configuration file /home/nutriz/snap/retroarch/118/.drirc: No such file or directory.
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libEGL warning: DRI2: failed to authenticate
libGL: Can't open configuration file /home/nutriz/snap/retroarch/118/.drirc: No such file or directory.
libGL: Can't open configuration file /home/nutriz/snap/retroarch/118/.drirc: No such file or directory.
Segmentation fault (core dumped)

```
### Version/Commit
- RetroArch: 1.7.3

### Environment information
- OS: Linux ubuntu-bungie 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hizzlekizzle** [comment]
This appears to be a problem with the snap package, which is important info to include.

What kind of GPU do you have, and which driver are you using with it (i.e., open source or proprietary driver, etc.)

**Comment by Nutriz** [comment]
I have an nvidia 980 and i have tried both with nvidia 390 driver, and the open source proposed, same error.

**Comment by hizzlekizzle** [comment]
Looking around on the internets it seems to be a conflict between snap and nvidia's drivers. Other people suggest that switching to nouveau should fix it.

**Comment by i30817** [comment]
use the ppa.

**Comment by RobLoach** [comment]
Try clearing your retroarch.cfg to use defaults? What's in there currently?

**Comment by Nutriz** [comment]
Well, you are right @bparker06, I remember now, I installed it with the software app wich use snap.

Step by step investigation :
- I removed retroarch from the software app
- Installed retroarch with `apt install retroarch` (version 1.4.1): launch worked
- Removed retroarch with `apt purge retroarch`
- Tried to reinstall with snap: launch failed
- Removed retroarch with snap
- Installed with the recommended cmd `sudo add-apt-repository ppa:libretro/stable && sudo apt-get - update && sudo apt-get install retroarch libretro-*` : (version 1.7.3) launch worked

So my issue is solved but it seems to have a bug with the snap installation and nvidia drivers.

**Comment by gouchi** [comment]
It would have been better if you opened the issue to the [dedicated repository](https://github.com/libretro/retroarch-snap).

Anyway, can you try to update the core snap to beta or edge branch as it is seems [nvidia gl access is currently broken on 18.04 ](https://forum.snapcraft.io/t/nvidia-gl-libs-access-broken-on-ubuntu-18-04/)

```
sudo snap refresh --beta core
sudo snap refresh --edge core
```

If it still does not work, we may have to update the  [wrapper](https://github.com/libretro/retroarch-snap/blob/master/retroarch.wrapper).

Thank you.

**Comment by Nutriz** [comment]
Ho sorry, i didn't see the snap repo.

How do I use this edge branch ?

Step by step investigation :
- Removed retroarch from apt installation `sudo apt purge retroarch`
- `sudo apt autoremove`
- `sudo snap refresh --edge core`
- `sudo snap install retroarch`
- `sudo snap refresh --edge core`

still the same error 
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libEGL warning: DRI2: failed to authenticate
Segmentation fault (core dumped)
```

**Comment by gouchi** [comment]
Can you try also with the beta branch to be sure 

`sudo snap refresh --beta core`

Thank you.

**Comment by Nutriz** [comment]
Still the same error after `sudo snap refresh --beta core`

**Comment by gouchi** [comment]
What the output of `LD_DEBUG=all retroarch` ?

Thank you.

**Comment by gouchi** [comment]
[Issue](https://github.com/libretro/retroarch-snap/issues/13) has been opened on the dedicated repository.
