### ISSUE TITLE
(Audio) Linux MIDI Driver Bounty

### ISSUE THREAD

**Issue by anothername99** [libretro/RetroArch#6897]
This is a continuation on a previous bounty (https://github.com/libretro/RetroArch/issues/4851).

I would love it if this will work out of the box on Lakka.

Bountysource link: https://www.bountysource.com/issues/59840444-bounty-for-linux-midi-driver

**Comment by w4st3d** [comment]
Note: https://github.com/thestk/rtmidi

**Comment by anothername99** [comment]
RtMidi supports OS X, but not Haiku. I'll leave it up to the bounty hunter to decide whether to use RtMidi or not.

**Comment by casdevel** [comment]
@anothername99 I wrote ALSA MIDI driver which should work on majority of Linux distros. As far I can tell it should work on Lakka, but Haiku will need it's own driver. Code is at [https://github.com/casdevel/RetroArch/tree/midi](https://github.com/casdevel/RetroArch/tree/midi).

**Comment by anothername99** [comment]
@casdevel I compiled your branch and set up the MIDI Out device in RetroArch's settings, then i tested Dosbox and Dosbox SVN with Descent and Day of the Tentacle. None of my devices react at all.

I did a quick test with Domino MIDI sequencer through Wine to see whether it's my system that is messing up, but it worked fine.

My distro is Solus.

**Comment by casdevel** [comment]
Try midi-test core from [https://github.com/casdevel/midi-test-libretro](https://github.com/casdevel/midi-test-libretro).
Keyboard keys: 1 = Metronome test, 2 = Loopback test, 3 = Keyboard test (Z..M) and 0 = Test off.

**Comment by anothername99** [comment]
I tried the midi-test core and I couldn't get a reaction.

**Comment by anothername99** [comment]
Oh yeah. @casdevel which distro are you on? I could try the distro you're using and see if it works there for me if it has a live mode.

**Comment by gouchi** [comment]
I tried using [FluidSynth](http://www.fluidsynth.org) with the midi-test core and I got the Metronome test working. Here is my RA cfg file for the midi options

```
midi_driver = "alsa"
midi_input = "Off"
midi_output = "FluidSynth"
midi_volume = "100"

```

**Comment by casdevel** [comment]
@anothername99 if your devices are listed in the menu then ALSA is available in that particular distro. Try midi-test core again and upload log somewhere. Regarding my distro, it's Kubuntu 16.04, tested with FluidSynth and USB MIDI keyboard.

**Comment by anothername99** [comment]
I got a log here: https://pastebin.com/raw/WRBu2ENC

ALSA is available, but maybe my distro has set it up badly, I don't know. Thanks, I'll test it in Kubuntu as soon as I can.

**Comment by anothername99** [comment]
No reaction on Kubuntu either: https://pastebin.com/raw/3LKDZUBz

However, because you mentioned Fluidsynth, I tried using that (with Qsynth GUI), and it seemed to work. So it seems like software synths are fine but not hardware synths.

**Comment by casdevel** [comment]
@anothername99 try [https://github.com/casdevel/RetroArch/tree/midi2](https://github.com/casdevel/RetroArch/tree/midi2).
If this doesn't help I'll order some MIDI output device and than try to solve the issue.

**Comment by anothername99** [comment]
@casdevel Now the test core works and games work as well, with hardware. Thank you!

**Comment by casdevel** [comment]
OK, I created a pull request.

**Comment by anothername99** [comment]
Thank you. Feel free to make a bounty claim.

**Comment by casdevel** [comment]
@anothername99 bounty can't be claimed while issue is open.

**Comment by anothername99** [comment]
Sorry! I closed it now.

**Comment by casdevel** [comment]
No worries.
