### ISSUE TITLE
(Menu) Recording settings have to be entered manually every time 

### ISSUE THREAD

**Issue by zedee** [libretro/RetroArch#6900]
## Description

Recording Settings seem not to be taken from config file and have to be entered manually each time you run RetroArch.

### Expected behavior

Record Settings should be taken from config file and visible in the Settings > Recording menu.

### Actual behavior

Record settings are not taken from the config file nor saved, and they don't appear on the Settings > Recording menu. You must enter them manually each time you want to record.

### Steps to reproduce the bug

1. Go to Settings > Recording menu
2. Put your settings
3. Open your game.
4. Recording works fine.
5. Exit RetroArch.
6. Open RetroArch again.
7. If you go to Settings > Recording, the old settings are wiped out and must be entered manually again. In the logs you can observe the following lines if you don't put them in manually:

```
[INFO] Recording to  @ 1024x576. (FB size: 2048x576 pix_fmt: 0)
[ERROR] Failed to start recording.
```

If you put settings manually on `.cfg` file, they're not honored.

### Version/Commit

- RetroArch: 1.7.3 (Git b2ceb50897)

### Environment information

- OS: Windows 10.0.17134 (x64)

**Comment by Sanaki** [comment]
I found this issue while looking for something else, but I believe this issue has been resolved at some point. Can you confirm?
