### ISSUE TITLE
(Menu) Make "Add to Favorites" not need a loaded core

### ISSUE THREAD

**Issue by kimdba** [libretro/RetroArch#6909]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

"Add to favorites" button is not working. 

### Expected behavior

"Add to favorites" should add that entry to favorite playlist.

### Actual behavior

Nothing happens. favorite file lpl file is not being updated at all.

### Steps to reproduce the bug

1. Choose any game
2. Select "Add to favorites"
3. See favorite list

### Bisect Results

From the beginning. I have never been able to add any new entry to favorites.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.7.3]

### Environment information

- OS: [OSX MacBook Pro]
- Compiler: N/A

**Comment by RobLoach** [comment]
I confirm that the core needs to be loaded, before you can add it to the favorites tab.

**Comment by Wellvergton** [comment]
Same problem on Ubuntu 16.04, only adds if a core is loaded. In the case of the MAME, if only the core is loaded the favorites entry is made with the rom file name, if the game is loaded in the core the database name is put in the list.

**Comment by orbea** [comment]
Fixed in https://github.com/libretro/RetroArch/pull/8393.
