### ISSUE TITLE
Crash When Selecting New Game in Silent Hill: Origins

### ISSUE THREAD

**Issue by BadWrongFun** [libretro/RetroArch#6911]
## Description

Silent Hill: Origins (NA) crashes when you start a new game.

Other games such as Mega Man Powered Up and Persona 3 Portable work like they should. Double checking on Dat-O-Matic confirmed the iso was perfectly fine. After the first crash, I realized I didn't put in the proper PSP assets. However, adding them in made no difference when I tried again.

I included a log of the crash.

[retroarch.log](https://github.com/libretro/RetroArch/files/2129886/retroarch.log)

Also, it appears that somebody else had this exact problem 4 months ago.
https://www.reddit.com/r/RetroArch/comments/7wufkl/silent_hill_origins_crashes_retroarch_when/

### Expected behavior

I can start a New Game in Silent Hill: Origins with no issue when using the Regular Linux version of PPSSPP, and so I expected to be able to be able to start up a New Game and just play the game as normal while using Retroarch.

### Actual behavior

Game crashes when I select a New Game.

### Steps to reproduce the bug

1. Load Silent Hill: Origins (NA)
2. Press Down twice to highlight New Game
3. Press X to select New Game

### Version/Commit

- RetroArch:  1.7.3 / b2ceb50

### Environment information

- OS: Ubuntu Mate 18.04
- Compiler: GCC (7.3.0) 64-bit

**Comment by BadWrongFun** [comment]
This issue was moved to libretro/ppsspp#17

**Comment by fr500** [comment]
This tracker is only for retroarch issues.  Not core issues.

**Comment by BadWrongFun** [comment]
I was alerted of that earlier elsewhere and had already closed and moved it to the core section before you commented.

**Comment by BadWrongFun** [comment]
@fr500 I was already alerted of that and had already closed and moved this to the PPSSPP core section before you commented.

**Comment by funregis** [comment]
Hi, I have the same problem on reto arch pspp o' switch.
