### ISSUE TITLE
Once autoconfig recognizes my gamepad it won't allow unbind of button

### ISSUE THREAD

**Issue by dynbabaul** [libretro/RetroArch#6942]
When RetroArch 1.7.1 starts up it finds the autoconfig for my gamepad and sets up the buttons. However there are ones I'd like to remap for a certain core only. When going into the input settings it says 

Auto:5 (N/A),(Key: q)

If i press delete it will delete only the key part & leave the Auto:5.  It will not allow the unbind of the autoconfig setting so I can then bind button 5 to another setting.

I've tried saving a core override then editing that file with the settings I want for the buttons just like they are defined in the autoconfig file & retroarch.cfg file.  The autoconfig settings always take precedence & the core override doesn't work.

How can I remap a button that the autoconfig sets without tampering with the autoconfig?  It needs to stay as is for other cores but needs to be able to change also.

- RetroArch: 1.7.1
- OS: Win7

**Comment by hizzlekizzle** [comment]
Typically, you don't want to use overrides for input stuff. The way to do it would be to use an input remap, which you can create from the quick menu's "controls" submenu. That menu lets you move the core's buttons around on the retropad abstraction and then save that arrangement on a per-game or per-core basis.

**Comment by orbea** [comment]
Using core remaps I was able to unbind the `B` button and then rebind it to `Fast Forward`. I think this is working correctly and solved.

Please let us know if you have any further issues.
