### ISSUE TITLE
Offensive string in code

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#6955]
https://github.com/libretro/RetroArch/blob/974aa3c8ac1c29bc3af5f9f1016cfdac325332b4/retroarch.c#L197

Is this really necessary?

BTW Microsoft used this string as recently as 2012 in their Azure Cloud (see e.g.  https://lkml.org/lkml/2012/7/18/625 , and https://www.wired.com/2012/07/b16b00b5/ ) but that doesn't make it any better.

**Comment by RobLoach** [comment]
https://en.wikipedia.org/wiki/Hexspeak

> `0xB16B00B5` | 2976579765 | ("big boobs") was required by Microsoft's Hyper-V hypervisor to be used by Linux guests as their "guest signature".[5] One proposal suggested changing it to 0x0DEFACED ("defaced").[6] Actually, it was initially changed to decimal and then replaced entirely.[7]
-- | -- | --


Perhaps we follow suit and change it to `0x0DEFACED`.
