### ISSUE TITLE
[RADV (R9 380) - Mesa 18.1.3] Vulkan + RGUI instantly crashes

### ISSUE THREAD

**Issue by syboxez** [libretro/RetroArch#6970]
Logfile: 
[rgui-vulkan.txt](https://github.com/libretro/RetroArch/files/2183038/rgui-vulkan.txt)

## Description

OS: Debian Sid
GPU: AMD R9 380
Driver: RADV through Mesa 18.1.3 (Mesa 18.2 also tested with the same result)

When setting video and menu drivers to Vulkan and RGUI, then restarting RetroArch for the changes to take effect, it will immediately SegFault before RGUI loads.

### Expected behavior

I expected RGUI to appear as normal

### Actual behavior

Segmentation Fault.

Vulkan + Other menus work just fine.
GL + RGUI works just fine.

### Steps to reproduce the bug

1. Have an AMD Tonga GPU with RADV drivers
2. Set drivers in RetroArch to Vulkan and RGUI
3. Restart RetroArch

### Bisect Results

It has always happened (about 3 months since I got this GPU and tested for the first time).

### Version/Commit
You can find this information under Information/System Information

- RetroArch: fd86140514

### Environment information

- OS: Debian Sid
- Compiler: GCC 7.3.0

**Comment by twinaphex** [comment]
@Themaister Are you able to reproduce this?

**Comment by twinaphex** [comment]
I think this has been fixed now and this can be closed.
