### ISSUE TITLE
Keyboard callback doesn't take into account keyboard layout (Windows only)

### ISSUE THREAD

**Issue by Zlika** [libretro/RetroArch#6971]
- RetroArch: 1.7.3

Hi!

I use libretro’s keyboard callback to manage the keyboard on my core. This callback gives access to the keycode of the pressed key.

**Under Linux this works ok**: I have an AZERTY keyboard and my operating system is configured with a french keyboard. When I press the ‘A’ key, the keyboard callback is called with the keycode of the ‘A’ letter. If I switch the configuration of the operating system to use an english keyboard then when I press the ‘A’ letter the keyboard callback is called with the keycode of the ‘Q’ letter => **that’s the behavior I was expecting.**

However, **under Windows**, whatever the keyboard configuration of the operating system is, when I press the ‘A’ key of my keyboard the keyboard callback is called with the keycode of the ‘Q’ letter, **as if I had a QWERTY keyboard!**

I tried to change some Retroarch’s options, in particular the input driver, but I wasn’t able to fix this problem.

I posted a message on the libretro forum about this (https://forums.libretro.com/t/keyboard-callback-doesnt-take-into-account-keyboard-layout-windows/16924) and a moderator answered me to open an issue here because he also noticed the problem.

Regards

**Comment by twinaphex** [comment]
@bparker06 Any thoughts here?

**Comment by DSkywalk** [comment]
Is a core problem, please check issue #8303 and #8042 
 https://github.com/libretro/RetroArch/issues/8303#issuecomment-464472759

Thanks

**Comment by Zlika** [comment]
The main problem here was that RA was not working the same on Windows and Linux. In this situation, the core cannot do anything to work correctly and consistently under all platforms.

**Comment by DSkywalk** [comment]
Sorry again @Zlika isn't it correct. Dosbox in windows using dinput:

![imagen](https://user-images.githubusercontent.com/560310/52917504-9d0c2400-32ec-11e9-96c6-43f83ad67eb4.png)
and Linux+X11:
![imagen](https://user-images.githubusercontent.com/560310/52917521-c1680080-32ec-11e9-93ec-d918d4bc9445.png)

Pressing keys...
![imagen](https://user-images.githubusercontent.com/560310/52917487-751cc080-32ec-11e9-8253-f37b92487fd8.png)

As I talked before if you load your layout on dosbox (automatically on windows and manually on linux) you get your keyboard correctly emulated and working the same on Windows and Linux.
![imagen](https://user-images.githubusercontent.com/560310/52917546-11df5e00-32ed-11e9-95e5-28c638484f8f.png)

Thanks!

**Comment by Zlika** [comment]
At the time I wrote this issue, the behavior was not consistent between Linux and Windows, as on Linux the keyboard callback was using keysyms whereas it was using scancodes on Windows.
As you changed the Linux behavior with 347519a4d8f3befb719f11eeb0121c736ce64dee, I propose to close this issue.
