### ISSUE TITLE
video_threaded true causing RA to be "busy" unresponsive (nightly)

### ISSUE THREAD

**Issue by IceLancerSR** [libretro/RetroArch#6976]
tracked down the bug to be retroarch doing.
Fresh retroarch. start once to generate configs, close it, open retroarch.cfg change video_threaded to true (or change in RA ),start retroarch and mice(mouse) busy will hover over retroarch causing problems ,RA will have "busy" mice(mouse) icon hovering over menu and if clicked RA will crash.

Stumbled it upon by finding out why bezels werent working and this is the cause
original topic where i at first thought it was bug in rockelauncher.
http://www.rlauncher.com/forum/showthread.php?5697-BUG-Bezels-are-broken-in-latest-retroarch-1-73

win10 x64 (all updates)
intel 2500k
16gb ram
nvidia 1060gtx
affecting all nightly builds 12-07-2018 11-07-2018 and 08-07-2018

**Comment by orbea** [comment]
This doesn't seem to be a problem for me in Linux, I suppose it might windows only.

**Comment by twinaphex** [comment]
I can't reproduce this issue.

**Comment by IceLancerSR** [comment]
should i make the video? i mean how hard can it be on clean retroarch?

**Comment by IceLancerSR** [comment]
https://youtu.be/aIB6KwQp8IY
here is video. its clearly a bug

**Comment by twinaphex** [comment]
OK, I can reproduce it.

**Comment by twinaphex** [comment]
@Dwedit Could this be related to the commits you recently pushed? It certainly looks like an issue that would happen if/when the message pump is no longer being processed.

**Comment by twinaphex** [comment]
@Dwedit I think I confirmed it's this commit - 

https://github.com/libretro/RetroArch/commit/838dcc8a5a3b57f7d9e737ba264428422d336c99

Reverted it for now. @IceLancerSR please test out either the upcoming nightly build or compile from source to see if the issues are gone for you now. During my brief tests they are.

@Dwedit I will await a PR that reimplements this while testing this edge case to make sure this issue doesn't happen.

**Comment by twinaphex** [comment]
Had to revert the revert again because it caused yet even more issues when toggling fullscreen. @Dwedit will just have to fix it I guess.

**Comment by twinaphex** [comment]
I see some issues with regards to the Freetype font renderer implementation - somebody added a get_default_font function there and it seems to be referencing the settings pointer, which gets allocated on the main thread. This is not thread-safe, and this is why we should not be casually referencing the settings pointer from within drivers.

**Comment by IceLancerSR** [comment]
@twinaphex i am not sure if ur commits are built. I don't believe so,build marked 21:49 hours  still suffers from this issue

**Comment by Dwedit** [comment]
Threaded video is a total mess on Win32.  The Window gets created on the secondary thread instead of the main thread.  There is no safe way to execute commands from the win32 menu if Threaded Video is used.  Any command that destroys the context will end up in an infinite wait loop.

What benefits does Threaded Video even have on Win32?  Why does it even exist?  Was it for weak dual-core machines that need to offload the video update to a secondary thread?

**Comment by twinaphex** [comment]
We cannot sacrifice threaded video for specific platforms, that would be a huge betrayal of our intention to have nearly every feature be non-platform specific. 

Threaded video was made by @Themaister for scenarios where you cannot get an accurate lock on the estimated screen refresh rate. In any case, I am unwilling to sacrifice this feature. People simply need to make it work with whatever features they have planned.

**Comment by Dwedit** [comment]
Sent in a pull request to get the relocated Win32 message loop working, and also have threaded video working.  #6989

**Comment by IceLancerSR** [comment]
Yes! tested and its fixed. Problem is gone! Well done!
