### ISSUE TITLE
Different menu options called "Configuration" and "Configurations," really?

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#6992]
I don't think the template is needed:
- Main Menu has an option called "Configurations"
- Settings has an option called "Configuration"

Both have completely different entries.

I think this speaks for itself.

**Comment by fr500** [comment]
Yes
Main menu one is for ACTIONS
The one under settings is for tweaks regarding configurations

It's not perfect (not even remotely so) but I don't know how to reorganize this

**Comment by hizzlekizzle** [comment]
I always think of it as everything in the 'settings' menu has an implicit word 'settings' after. Video settings, configuration settings, user interface settings, etc.

**Comment by RobLoach** [comment]
Open to new verbiage, feel free to re-open the issue with proposed change. Closing this one in the mean time. Thanks!
