### ISSUE TITLE
RA failing to start on android Tegra devices

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#6995]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

What the title says

### Expected behavior

It should start

### Actual behavior

It's closing immediately

### Bisect Results

https://github.com/libretro/RetroArch/commit/63a071b85af72fd882759a6e9385b9c666b1c735 works
That's as far as I have been able to test

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
https://github.com/libretro/RetroArch/commit/a0b1937584aa45e131257ccc138a17007f7be700
works

**Comment by twinaphex** [comment]
This has been fixed now right?

**Comment by twinaphex** [comment]
Going to close this in case it has been fixed. If not, don't hesitate to create a new issue about it.
