### ISSUE TITLE
RetroArch Crashes when selecting XMB UI driver.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#7000]
## Description

Selecting xmb ui driver on Android then exiting RetroArch cleanly and opening it again crashes the app on start up on RetroArch recent and latest nightlies, it works fine on stable from the playstore.

### Expected behavior

It should not crash.

### Actual behavior

RetroArch crashes

### Steps to reproduce the bug

1. In RetroArch driver settings select menu driver xmb.
2. Exit RetroArch cleanly using the quit RetroArch menu option.
3. Open Retroarch again.

### Bisect Results

Sometime in one of this month nightlies that made changes to xmb I would think.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

1.7.3_GIT (1531718954)

- OS: [The operating system you're running]

Android 7 motog5 plus

**Comment by blackman91** [comment]
Log:
![screenshot_20180716-203040](https://user-images.githubusercontent.com/6578180/42792114-7c7aba60-8939-11e8-9c36-a387d6a78b89.png)
![screenshot_20180716-203000](https://user-images.githubusercontent.com/6578180/42792121-817033d8-8939-11e8-86ef-d98f873f004d.png)

**Comment by twinaphex** [comment]
I pushed a commit which hopefully fixes this -

https://github.com/libretro/RetroArch/commit/9c0ed0f2c4182f3df543a54881e68bb12cf2ed68

**Comment by blackman91** [comment]
Nice job! It seems to be working now on newest nightly.
