### ISSUE TITLE
(OSX) Mac version of RetroArch 1.7.3 identifies itself as version 1.7.2

### ISSUE THREAD

**Issue by core-code** [libretro/RetroArch#7004]
mac version of RetroArch 1.7.3 identifies itself as version 1.7.2 when selecting it in the Finder and using the "Get Info" command

**Comment by core-code** [comment]
thanks a lot for fixing this issue in version 1.7.4

however, i'm encountering a new problem here. 

in 1.7.4 suddenly the 'bundle identifier' i.e. the CFBundleIdentifier entry in the Info.plist file is missing.

the bundle identifier hadn't been missing previously and had always been set to 'libretro.RetroArch', now its gone.

preferences, caching and several other things are probably broken for apps without bundle-identifier, as Apple requires that every app has a (unique) bundle identifier.

i am not sure where the problem originates from, since the key is still present in 
https://github.com/libretro/RetroArch/blob/master/pkg/apple/OSX/Info.plist
but it surely is gone from the build here
https://buildbot.libretro.com/stable/1.7.4/apple/osx/x86_64/RetroArch.dmg

**Comment by twinaphex** [comment]
Not sure why.

@bparker06 you happen to know anything about this?

We honestly need more dedicated Apple developers to deal with all these issues.
