### ISSUE TITLE
(WIMP) Improvements to the WIMP UI

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#7006]
Some features that are still highly requested by users:

- Manual playlist creation/editing
- A shader parameters dialog screen that makes it possible to modify shader parameters on the fly. This will be similar to the old WIMP Win32 shader dialog window that used to exist before.
- When rightclicking a playlist in the WIMP UI, there should be a 'Download thumbnails' option. When clicking on this, it should download the 'giant' thumbnail pack for this playlist based on the system name. If no matching thumbnail pack can be found, have it do nothign.
- There should be an option called 'Download missing thumbnails on-demand' that, if enabled, should download and install missing thumbnails. We should make this work for both WIMP and non-WIMP UIs.

This is so far what I can think of off the top of my head. There might be more things that pop up later that would need looking into.

**Some basic directions so far:**
so basically - as for playlist creation
it should use pretty much the same interface as it currently does
the only difference will be
the user will right click somewhere
there should be an option like 'New Playlist'
and from there - it starts off with a blank playlist
then you can 'add' a new line
or edit existing ones
the existing playlists should also be similarly editable
it should work similar to say editing an Excel spreadsheet
just doubleclick on it and you will be able to modify its contents
and then changes will be saved after you hit Enter
as for the shader dialogs
There was previously a Win32 UI dialog for it
that we had to disable later on since it was not thread safe
but this would be the perfect opportunity to redo it in Qt
and have it be crossplatform
it will show every parameter that Quick Menu -> shaders -> Shader Parameters would also show
it will have a slider per shader parameter
where to the far left is the 'min ' value' and to the far right is a 'max' value
and you can just drag the slider to the value you want

**Comment by bparker06** [comment]
>the user will right click somewhere
there should be an option like 'New Playlist'
and from there - it starts off with a blank playlist

Would this be in a new window? It would probably be best if it was.

>then you can 'add' a new line

How should this be done? Manually typing in the name and path of a file? Browsing to it with a file picker? Drag & drop? Or what?

>or edit existing ones

Same question for this one.

**Comment by twinaphex** [comment]
> Would this be in a new window? It would probably be best if it was.

![image](https://user-images.githubusercontent.com/1075274/43049954-f8d32856-8e00-11e8-9a20-201d11fd96c0.png)

I would just envision this except there being no entries yet - maybe have the first entry be completely blank.

> How should this be done? Manually typing in the name and path of a file? Browsing to it with a file picker? Drag & drop? Or what?

Good question. The problem is that we don't have multiple columns right now in the playlists - they only show the title without showing any more information. @Tatsuya79 got any ideas here

**Comment by twinaphex** [comment]
@bparker06 For now, just leave it at manually typing in the name. As we use it in practice a bit more, we might hit upon better ways to do it and/or expand the options.

**Comment by bparker06** [comment]
We could add a second column just while editing the playlist, but how would we determine when we are editing or not to be able to do that? That is one of the reasons for having a separate window... plus you would be able to work on playlists without disabling the rest of the UI until you were done.

>manually typing in the name

Ok, but what about the content path? And the core name/path? How would those associations be made?

**Comment by Tatsuya79** [comment]
I was thinking about starting a playlist creation directly from the file browser, right clicking a file/group of files/folder and selecting "create a playlist" or "add to playlist".

Alternatively but not excluding the method above, a way to start a playlist creation similar to a script where you point to a folder and enter the extension(s) of files to add to a (new) playlist.
I described that in the google doc we used.

For editing, in the playlist browser mode you could right click a playlist member to have options like "rename", "remove", "associate to a core"...

**Comment by twinaphex** [comment]
> Or have an option for either?

An option for either would be best so we cover both cases.

> Since the second column thing may be tricky while keeping everything in the same window, maybe for now we just show the current path as a tooltip? And then have a right-click option to change the path for that item or something.

OK, let's go with that. Hopefully it will still be intuitive enough.

**Comment by Tatsuya79** [comment]
I'm all for bypassing it completely if we want to.
Then we can have a checkbox when launching an advanced scan that adds a crc check or try to find a match in databases.
Also a general option that will decide that for the drag&drop / right click ways.

**Comment by Tatsuya79** [comment]
Additional columns for paths, associated cores would be great (as long as you can show/hide them as you want).

Tooltips seem worse imo.
Or rather an info dock you can put where you want like the core info one (we can detach them too).

**Comment by bparker06** [comment]
Well my thinking behind the tooltip idea was that the window size may not always be big enough to show full paths, and right now we don't even show them anywhere anyway (whether Qt or XMB), so tooltips appearing briefly on top of everything would solve both of the screen real estate issues IMO. It wouldn't have to take up so much space all the time and most people probably don't care to see them that often anyway. An extra column also would be incompatible with the grid view but tooltips wouldn't. Or in that case, maybe revisit the original idea of a separate window, which would always have a table widget.

I'm open to suggestions either way.

**Comment by Tatsuya79** [comment]
Grid view is a bit of a minimalist mode just for show, perhaps it could have a right click info with the path there and for detail view too.
But detail view hasa lot of free space if you display the window in full screen.
It's just like any OS detail mode view, it's great when you want every infos visible to do some classification and things like that.

**Comment by bparker06** [comment]
@twinaphex 

>just doubleclick on it and you will be able to modify its contents

This conflicts with the current behavior of doubleclick to launch the game.

**Comment by twinaphex** [comment]
OK, then right click on an entry, it brings up a context menu from which you could select ' Edit 'then.

**Comment by bparker06** [comment]
For those following this thread, manual playlist creation/editing has been merged into master now.

**Comment by bparker06** [comment]
Due to the lack of on-by-default SSL/TLS support in RA and the inability to follow HTTP redirects (both are needed to properly talk to github to download files), I'll be focusing on a Qt-only implementation of the thumbnail downloading for now.

**Comment by bparker06** [comment]
Can we discuss the "on-demand" thumbnail downloading and come to an agreement on how exactly that should work?

**Comment by Tatsuya79** [comment]
For something simple I would do it by right clicking on a playlist "get thumbnails".
It would leave a choice of what you want (with something like checkboxes for cover/snaps/titles) and then it would check the playlist name to find the repo, get thumbs by name matching the entries.

Same kind of thing could happen for a right click on an entry directly to get just 1 set.

**Comment by bparker06** [comment]
A right-click option on content items has been added to download individual thumbnails.
