### ISSUE TITLE
(Video) [X11] xfwm now has NET_WM_BYPASS_COMPOSITOR

### ISSUE THREAD

**Issue by marcosfrm** [libretro/RetroArch#7016]
xfwm 4.13 development branch:

https://git.xfce.org/xfce/xfwm4/commit/?id=642275e9d795e9f2cba78df7e3e92485955638a6

This code may need changes in the future:

https://github.com/libretro/RetroArch/blob/v1.7.3/gfx/drivers_context/x_ctx.c#L696-L707

@bearoso

**Comment by bearoso** [comment]
Based on that commit, I think the existing code will still work fine. We'd still need to check the window manager name for older versions.

**Comment by gouchi** [comment]
@marcosfrm @bearoso is still an issue now that the [code has evolved](https://github.com/libretro/RetroArch/blob/v1.19.1/gfx/drivers_context/x_ctx.c#L516-L542) ?

Thank  you.

**Comment by bearoso** [comment]
It's been 6 years since xfwm lacked the bypass conpositor window flag, so no, the special case and this bug aren't relevant any more.

**Comment by gouchi** [comment]
@bearoso Thank you for the feedback.

@marcosfrm Please close this issue. Thank you.

**Comment by marcosfrm** [comment]
Done. Thanks.
