### ISSUE TITLE
Crash on gnome3 wayland (with bisect)

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#7035]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

A recent crash on just starting retroarch on weston/wayland gnome3 crashes with:

```
i30817@AIVAS:~$ retroarch 
listener function for opcode 5 of wl_keyboard is NULL
Aborted
```

### Bisect Results
```
i30817@AIVAS:/media/i30817/Huggin/Documents/projects/RetroArch$ git bisect bad
5f35249216ff741373d337a5546d222e8e40079c is the first bad commit
commit 5f35249216ff741373d337a5546d222e8e40079c
Author: Sven <40953353+RetroSven@users.noreply.github.com>
Date:   Wed Jul 25 19:19:14 2018 -0400

    Implement robust cheat searching interface with rumble features

:100644 100644 7b6b682336a07a984fc3218d0f8d29f42350b518 928833b882c36b6f544684cfb2018df71a100e5b M	command.c
:040000 040000 fa628b330f3b9dee0b8e94448601a7eca240ca4c d8ce099c96fb8802a3677c0aa46e48a72137c066 M	gfx
:040000 040000 80a29f87253848155b5b48d91924bfc97f0f651d 64966cd5592323b069d8163d7cedf3cba8e73743 M	intl
:040000 040000 8a5a3f0dddd578bb0f023883fbfdb1a8bc33ae86 df8de81ac7582f838b7157d6ce47b8b7e5a6937c M	libretro-common
:040000 040000 e8107c7600a3ba323eb5d5e976cdcbbe7c942134 8ae8982eab54d0fd7903e060e4e3707cb302f2d1 M	managers
:040000 040000 84fc131f5483e8a5e203bbd433d2f2dcc7a103c3 b1ab0da47384bebd1294896299febdda6b2154c7 M	menu
:100644 100644 41dfbb57dcc96a842efca9379ad9d40740b91b27 14970333657cea144a513fc7ad6656810d1c5384 M	msg_hash.h
:100644 100644 69836ee9435b9d3d8dc3ad2ccb6a13cd8200943e 4d03731be656fec55bb14e705840527db3494d98 M	retroarch.c
:100644 100644 1635c83de8a6a03fccc891e0b2651b694f964928 7dd318bcd7dbdad9380c4a816bbca61ae181b25e M	retroarch.h
:100644 100644 319917906080cd33be77bd1423b6468a53da1027 8448c53f9d32ceeebbdaaea8780b59570207211f M	setting_list.c
:100644 100644 01bf89d37bf7e40263abb0fe44b3d7c7f9a14095 13e4ca451e3d792d94fca4ba02ec0a0d857ef33f M	setting_list.h
:040000 040000 5dd26cc164ea288c1596c595b81931a61e8924a1 0d9215d229272c503c4afd82e812335b76bd79f0 M	tasks
```

### Version/Commit
You can find this information under Information/System Information

(this is the local version installed from the ppa not my built one)

- RetroArch: 
RetroArch: Frontend for libretro -- v1.7.3 -- 50381a0 --
Compiler: GCC (7.3.0) 64-bitBuilt: Jul 30 2018

### Environment information

- OS: Linux AIVAS 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Compiler: gcc (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**Comment by twinaphex** [comment]
@RetroSven do you have any way to debug this or do you not run Linux with Wayland?

**Comment by i30817** [comment]
For what it's worth i verified the bisect is correct by compiling both it and the previous commit. I did have to skip a unbuildable revision on the bisect so i thought this might be necessary to be 100% certain (most certainly not but i'm paranoid).

**Comment by twinaphex** [comment]
I can reproduce the issue with Weston yeah.

**Comment by twinaphex** [comment]
OK, I think this fixes it -

https://github.com/libretro/RetroArch/commit/aec7ed40dad049754cc74d003f6a49da46df71d1

@RetroSven Was there a reason for commenting out this function callback? I think we were running into a null pointer indirection when that function callback was being called by it not being bound.

**Comment by twinaphex** [comment]
@i30817 Can you test again? This should be fixed now I believe.

**Comment by i30817** [comment]
I'm waiting for the ppa to build, it should be ready tomorrow.

**Comment by i30817** [comment]
It's fixed (though the ppa i386 build is failing for some reason, whatever).
