### ISSUE TITLE
Failure in PPSSPP options

### ISSUE THREAD

**Issue by Renetrox** [libretro/RetroArch#7036]
I downloaded version 2.1 of development and ppsspp still has failures. One of them has to do with the option of "frameskip", it is unusable, when setting it, the game disappears, only the sound is heard, when using the option "non buffered" the screen is flipped. I placed the PPSSPP folder in System, but that does not change anything.
Lakka 2.1 nigthlty
hw: Raspberry pi 3b

**Comment by orbea** [comment]
This is a core issue? Maybe this should be discussed in the core repository? https://github.com/hrydgard/ppsspp/issues

**Comment by Renetrox** [comment]
I understood that the lakka version is different, I'm going to post the error at https://github.com/hrydgard/ppsspp/issues, even so, in case it's something of the operating system itself, it's been a long time since except me ppsspp does not work properly for me

**Comment by orbea** [comment]
Ah, I did not consider that lakka could be using a different version. You could try the lakka issue tracker then?

**Comment by Renetrox** [comment]
sorry for so many laps, I just wanted to help reporting the error, maybe I erroneously issued here the report when it is a lakka issue.

**Comment by orbea** [comment]
No worries, I am just trying to make sure the people most likely able to help see the issue. :)
