### ISSUE TITLE
Analog deadzone Configuration

### ISSUE THREAD

**Issue by frthery** [libretro/RetroArch#704]
Hi, i would like to know if there is an option to ajust deadzone of analog stick ?
If this option isn't available, is it hard to implement ? many emulators offer this setting.

Thanks guys for your hard work, retroarch is awesome!

**Comment by rsn8887** [comment]
Why was this closed? A true analog deadzone is still missing. All we have is a misleading option that is called "deadzone" but it is an analog to digital conversion threshold instead (and correctly labeled so inside the source code).
