### ISSUE TITLE
[Buildbot] wrong architecture core

### ISSUE THREAD

**Issue by qarlosh** [libretro/RetroArch#7044]
(It is related to buildbot, not sure if this is the place to open this issue)

Just downloaded the fmsx core build for armhf from https://buildbot.libretro.com/nightly/linux/armhf/latest/fmsx_libretro.so.zip, but it contains a x86-64 library:
```
$ file fmsx_libretro.so 
fmsx_libretro.so: ELF 64-bit LSB pie executable x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=67dc928958e7db19cb787fd65edea0ca034edeb9, not stripped
```
It should be something like:
```
$ file fmsx_libretro.so 
fmsx_libretro.so: ELF 32-bit LSB pie executable ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=8fe78d05171cb1f7a3e13cba27e11bdc9f72cbb7, stripped
```

**Comment by gouchi** [comment]
Maybe better to move it to [libretro-super](https://github.com/libretro/libretro-super) tracker issue ?

**Comment by qarlosh** [comment]
Done, moved to libretro-super project
