### ISSUE TITLE
Autosave not working with Higan Accuracy Core

### ISSUE THREAD

**Issue by ichee** [libretro/RetroArch#7054]
Setting an autosave interval of 1 or greater does not write sram to disk after saving in game and set interval passes. The sram will still properly write once the core has been closed.
Issue does not occur in any of the other SNES cores.

Tested with stable 1.7.3 and the latest nightly as of today.

OS: Windows 10 64-bit

**Comment by fr500** [comment]
It's not a RA issue because as I said the core doesn't use the memory API.
It should flush right away but I haven't tested personally

**Comment by ichee** [comment]
Then would the issue be with the Higan Accuracy libretro core port or with Higan itself?

**Comment by orbea** [comment]
This is a core problem and it should be dicussed with hex-usr who is he most likely candidate to maintain this core correctly.

His repo is here.

https://gitlab.com/hex-usr/higan-libretro

Alternatively you might be able to contact him here.

https://helmet.kafuka.org/bboard/
