### ISSUE TITLE
Can no more download Handled games directly from Retroarch interface

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#7055]
Hello, I can no more download Handled games directly from Retroarch interface, is it a known issue?

Config: 
Retroarch 1.7.3 compiled from Git
Ubutnu 18.4

**Comment by parkerlreed** [comment]
See #7056

Any entry with a space is erroring out

**Comment by RobLoach** [comment]
Confirmed. Let's move over to the other issue. Thanks!
