### ISSUE TITLE
(Menu) Content Downloader cannot load any directories with spaces

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#7056]
## Description

Going into any of the Content Downloader entries that have a space result in "No entries to display"

### Expected behavior

Entries should display

### Actual behavior

Entries do not display

### Steps to reproduce the bug

1. Open RetroArch
2. Online Updater
3. Content Downloader
4. Select any entry with space

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.7.3 -- 50b23d6572

### Environment information

- OS: Arch Linux
- Compiler: GCC

**Comment by fr500** [comment]
Weird...
It must be a problem with the crawling script because my own "rom server" has the full no-intro set spaces and all and I can use it just fine

**Comment by parkerlreed** [comment]
Could this be some update to the buildbot breaking it? I've been git biseting this and even pretty far back I'm hitting the same issue.

**Comment by parkerlreed** [comment]
Any update on this? Still an issue on 1.7.5.

**Comment by fr500** [comment]
It's a weird one, I have my own "rom server" and mine works just fine with
spaces

**Comment by y4my4my4m** [comment]
This is still not fixed on linux86_64

Any idea what causes this?

**Comment by RobLoach** [comment]
I believe it's something with the web server. lighthttpd does something weird with the requests, which breaks RA. I'll remove the spaces from some of the directories for now.

**Comment by parkerlreed** [comment]
@RobLoach Thanks! That does indeed work for now.
