### ISSUE TITLE
bug: lightgun runahead

### ISSUE THREAD

**Issue by ramtrooper** [libretro/RetroArch#7057]
Retroarch 1.7.3, windows

This seems to affect all cores that use lightguns (mouse).

1. turn on runahead 6 frames, secondary off
2. start any lightgun game (ex. Snes - Yoshi's Safari)
3. move mouse cursor around
- note how hard it is to move the cursor
- always seems to move in 5-6 pixel intervals

Problem is we can't accurately aim.

**Comment by fr500** [comment]
Disable runahead?
As simple as that :P

**Comment by ramtrooper** [comment]
YI has high amount of built-in shooting lag and using runahead cuts down on that tremendously.

**Comment by danieljg** [comment]
I suspect this is inherent in the way the game tracks the pointer, as in, it seems the game loop takes several frames to track the current position of the pointer, and runahead messes up with this big time. If the game does some sort of interpolation, then the current implementation of runahead would certainly be affected.

What would be *really* cool would be to set runahead to 0 (or perhaps 1), plug a real super scope into a parallel port of a pc, set the input polling timer to 500 Hz or 1 kHz, get the beamracing per-scanline rendering working, use the crt switchres feature, and see what happens...

**Comment by ramtrooper** [comment]
Found out that different cores can affect this - some work, some don't with same console.

Notably Genesis Plus GX lightgun works perfect all the time (SMS or MD) @ latency 0-6. Never cursor motion lag or accuracy problems.

Tatsuya79 mentioned some snes9x core I've never heard of and the lightgun cursor moves perfectly over there even at latency 10!

So it's definitely not frontend. Thanks everyone!
