### ISSUE TITLE
(Menu) When "Save Configuration on Exit" is OFF, the config is still saved

### ISSUE THREAD

**Issue by bootsector** [libretro/RetroArch#7059]
RA built from master. Save config on exit OFF. Make some changes, i.e. assign some hotkeys. Exit RA. retroarch.cfg is now full of unwanted stuff.

**Comment by grimpunch** [comment]
@bootsector , can you give anymore information about what platform you were using when this error occurred?

**Comment by grimpunch** [comment]
Investigated this and it doesn't seem like this is reproduce-able on win64, I did see that `CMD_EVENT_SHUTDOWN` and `CMD_EVENT_REBOOT` in command.c make a command_event call to save the current config without any checks for `settings->bools.config_save_on_exit`. So perhaps, if the platform was linux based then a shutdown command could have saved the config without permission upon closing at that point. I will need to investigate further in a linux based dev env.

**Comment by bootsector** [comment]
https://i.imgur.com/IuhU11D.jpg
Ubuntu 18.04 x64

**Comment by orbea** [comment]
@grimpunch It does work here, but maybe too well. If I disable `Save Configuration on Exit` in the ui it will be enabled again next time I start RetroArch. Likewise all other settings I changed in the initial session will be restored.

However I can set `config_save_on_exit = "false"` in `retroarch.cfg` and it will work as expected including turning it on again in the ui.
