### ISSUE TITLE
[Feature Request] Wayland: Support for xdg-shell

### ISSUE THREAD

**Issue by benutzer193** [libretro/RetroArch#7064]
_Update:_ WIP PR to implement xdg-shell support: #7607

---

## Description

[wl_shell](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_shell) is deprecated in favor of [xdg-shell](https://cgit.freedesktop.org/wayland/wayland-protocols/tree/stable/xdg-shell):

```
Note! This protocol is deprecated and not intended for production use.
For desktop-style user interfaces, use xdg_shell.

- Source: Appendix A. Wayland Protocol Specification
```

In e.g. sway 1.0 (currently in [beta](https://github.com/swaywm/sway/issues/1735#issuecomment-431621738)) support for wl_shell has already been [removed](https://github.com/swaywm/sway/pull/1871) and therefore running RA in wayland context fails:
```
[INFO] [Wayland]: Seat name: seat0.
[INFO] [Wayland]: Physical width: 345 mm x 194 mm.
[INFO] [Wayland]: Video mode: 1920 x 1080 @ 59.9750 Hz.
[INFO] [Wayland]: Setting buffer scale factor to 1.
[ERROR] [Wayland]: Failed to create shell.
```

To be future-proof for wayland please add support for the successor xdg-shell.

**Comment by i30817** [comment]
Would this fix the input problems in https://github.com/libretro/RetroArch/issues/7020

What about the GPU permission problems?

**Comment by benutzer193** [comment]
I don't think the two issues are connected,
as you are talking about RA on DRM/KMS and this is about support for a wayland protocol.

**Comment by i30817** [comment]
The input problem (at least) is caused by KMS not using a wayland surface and thus not pulling in libinput (which is used by wayland).
