### ISSUE TITLE
Core Information not working on latest nightly.

### ISSUE THREAD

**Issue by blackman91** [libretro/RetroArch#7075]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

On Android latest nightly loading a core then selecting information no longer shows the core information option so you can't delete individual cores on Android and you can't see the cores requirements.

### Expected behavior

Loading a core then selecting information should show an option called core information.

### Actual behavior

Core information option is no longer showing.

### Steps to reproduce the bug

1. Load any core
2. Select the option information
3. Core information not showing

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [135000a]

### Environment information

- OS: [Android 7]
- Compiler: [In case you are running local builds]

**Comment by Tatsuya79** [comment]
Happened with https://github.com/libretro/RetroArch/commit/73f271021a8c8a67adb8dfe7e3e3672c1ff86116

**Comment by bparker06** [comment]
Fixed in 9f60a6d17c8188f11651573fc360033bb2e29525

**Comment by blackman91** [comment]
Fixed, thanks a lot.
