### ISSUE TITLE
(Input) Keyboard and gamepad input_axis_threshold sometimes inactive

### ISSUE THREAD

**Issue by legluondunet** [libretro/RetroArch#7101]
Hello,

sometimes when I launch Retroarch, I can no more navigate on Retroarch menu with keyboard or gamepad, only mouse is active.

If I compare my Retroarch config files with an older one, I found a changed value:
new RA config file: input_axis_threshold = "0.000000" 
old RA config file: input_axis_threshold = "0.500000"

If I change this option to input_axis_threshold = "0.500000", I can again navigate with keyboard and gamepad in Retroarch.

I don't know why this option sometimes change or why I have to correct it.

I prefer to open an issue for people that have the same issue as me and to indicate them the workaround.

Thank you for your help.

COnfig:
Ubuntu 18.04
Nvidia
Xbox360 gamepad clone

**Comment by RobLoach** [comment]
The default is 0.5:
https://github.com/libretro/RetroArch/blob/91a5b0962726afdf33e7dc8d76770b72040a4dbe/config.def.h#L659-L661

Strange.

**Comment by legluondunet** [comment]
I never changed anything in the Retroarch config file, I didn't understand why and how this value could change.

**Comment by orbea** [comment]
Its possible you simply set it accidentally why scrolling the options without realizing. You can confirm this by moving your configuration directory out of the way temporarily and then starting RetroArch so it regenerates. The setting should be correct in this new directory.

**Comment by legluondunet** [comment]
Ok, I close this issue.
