### ISSUE TITLE
(WIMP) Select starting point, faster boot

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#7103]
Current starting point is "All Playlists" which is the most CPU intensive way to launch the program, wasting several seconds depending of how many playlists you have (can be much longer on slow machines).

I suggest starting on "History" by default and then having an option to select the starting point if you wish, like an internet browser start page.
You could select any playlist, your "Start Directory" or a folder if you prefer starting from the file browser.

This would replace the option "Remember last content browser tab"

**Comment by bparker06** [comment]
Added the UI option in 9638005.
