### ISSUE TITLE
(Menu) Add "Automatic" as selectable as a Menu Icon

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#7115]
## Description

The [Automatic RetroArch Menu Icon theme](https://github.com/libretro/retroarch-assets/tree/master/xmb/automatic) is part of retroarch-assets, but cannot be selected in the menu. Add it to the menu selection for XMB.

Fixes libretro/retroarch-assets#224

### Expected behavior

Be able to select "Automatic" as a menu icon theme.

### Actual behavior

Cannot currently select "Automatic" as a menu icon theme.

**Comment by alfrix** [comment]
See #7117
