### ISSUE TITLE
RetroArch main menu entry for 3ds no longer functional

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7132]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Hey, I had RA 1.7.0 in my 3ds and I had a RetroArch main menu entry that would chainload the cores.
It's no longer included? and the one I have no longer works.

It just crashes back to the 3ds main menu

### Expected behavior

RetroArch should open

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: August 26 2018 (no git version apparently)

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
Paging @meepingsnesroms.

**Comment by meepingsnesroms** [comment]
Try a fresh install(or at least delete retroarch.cfg), the RetroArch loader is in /3dsx/3ds or /cia in the .7z

**Comment by gingerbeardman** [comment]
Works for me in 1.7.5 and latest nightlies

**Comment by orbea** [comment]
I'd like to hear from @fr500 to be sure since he is pretty responsive, but I think you are right that it probably works just fine now.

**Comment by gingerbeardman** [comment]
I read the OP as fr500 reporting an issue sent to him by somebody else, but hopefully he can confirm either way

**Comment by fr500** [comment]
Not likely to test anytime soon...
Can't find my sd card reader.

If he says it's fixed then let's assume fixed

**Comment by orbea** [comment]
Okay, sounds good to me, if you can reproduce it again in the future we can reopen the issue or make a new one.
