### ISSUE TITLE
(Support) Build issue for VITA

### ISSUE THREAD

**Issue by quyen194** [libretro/RetroArch#7141]
I follow below guide to build
https://docs.libretro.com/compilation/psvita/
But not success!!!

after following step:
make -f Makefile.vita.salamander
make -f Makefile.griffin platform=vita
cd dist-scripts
./dist-cores.sh vita
==> compile issue: cannot find -lretro_vita

I try the following step:
pre step: copy "libretro-super/dist/vita/quicknes_libretro_vita.a" to "libretro-super/retroarch/libretro_vita.a"
make -f Makefile.vita.salamander
make -f Makefile.griffin platform=vita
make -f Makefile.vita
==> compile success with output "retroarch_vita.vpk"
BUT inside package "retroarch_vita.vpk" only have two files: "eboot.bin" and "sce_sys/param.sfo"

please tell me how to build full package like "RetroArch_v1.73.vpk" from http://buildbot.libretro.com/

NOTE: I build on ubuntu (virtual machine)

**Comment by bparker06** [comment]
I would suggest using the same script that the buildbot uses, it's automated and much easier:

From the root of the libretro-super repo:

`SINGLE_CORE=quicknes FORCE=YES NOCLEAN=1 EXIT_ON_ERROR=1 ./libretro-buildbot-recipe.sh recipes/playstation/vita`

This should build the core as well as RA and link them together, and produce the final vpk output.

The paths to the SDK are set in recipes/playstation/vita.conf if you need to modify them.

**Comment by quyen194** [comment]
thanks for your trick!!!

btw after I cleanup libretro-super repo then run your command from the root of the libretro-super repo:

SINGLE_CORE=quicknes FORCE=YES NOCLEAN=1 EXIT_ON_ERROR=1 ./libretro-buildbot-recipe.sh recipes/playstation/vita

content of recipes/playstation/vita.conf :
// ==================
PATH /home/buildbot   => I don't know what it is, so i mkdir /home/buildbot before compiling
platform vita
PLATFORM vita
VITASDK /usr/local/vitasdk    => this is $VITASDK
RA YES
JOBS 4
CORE_JOB YES
MAKE make
// ==================

the results I got after build:
libretro-super/dist/vita/quicknes_libretro_vita.a
libretro-super/retroarch/dist-scripts/quicknes_libretro_vita.a
libretro-super/retroarch/libretro_vita.a
libretro-super/retroarch/retroarch_vita.vpk

and some log from terminal (I think its show that there is no error)
// ==================
...
convert -background none /home/knight/libretro-super/retroarch/media/assets/xmb/systematic/png/wifi.png -resize 64x64! /home/knight/libretro-super/retroarch/pkg/vita/retroarch/assets/xmb/systematic/png/wifi.png
convert -background none /home/knight/libretro-super/retroarch/media/assets/xmb/systematic/png/zip.png -resize 64x64! /home/knight/libretro-super/retroarch/pkg/vita/retroarch/assets/xmb/systematic/png/zip.png
knight@ubuntu:~/libretro-super$ 
// ==================

BUT retroarch_vita.vpk has only two file (same as before): "eboot.bin" and "sce_sys/param.sfo"

**Comment by bparker06** [comment]
Check the `pkg/vita` folder inside the `retroarch` folder of the libretro-super repo.

**Comment by quyen194** [comment]
I saw folder: retroarch.vpk/vpk
It include somefile that I think its trully package. Do I need zip that folder's contents to make vpk installer?

**Comment by quyen194** [comment]
@bparker06 is there anyway to decrease build time?
It's alway rebuild and consume more than 10 minutes to build :((
I only changed one line code and need to wait more than 10 minutes
