### ISSUE TITLE
[Desktop Menu] Return Key in XMB acts differently

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#7142]
## Description

Doing a search in XMB activates the resulting entry instead of just moving the selection to it.
**Does not happen ~~if QT isn’t baked in~~ if "Show desktop menu on startup" is turned off.** 
Input driver on dinput or raw act the same.
Only on windows?

### Expected behavior

Just moving the selection after a search without activating the result.

### Steps to reproduce the bug

In XMB on a playlist or in the core updater, hit “!” to start a search, enter a word, 
hit **keyboard Return (not enter or start)**, the result will be activated just like if a 2nd activation happened. 
(it downloads the search matching core directly in the updater)

### Version/Commit

- RetroArch: current git

### Environment information

- OS: win7 x64
- Compiler: MSYS2 gcc 7.3

**Comment by bparker06** [comment]
Are you on an AZERTY keyboard? Because the search button for me is `/`.

**Comment by Tatsuya79** [comment]
Yes azerty.

**Comment by bparker06** [comment]
Hmm that's quite an interesting issue. Just turning off "Show desktop menu on startup" seems to solve it as well.

**Comment by Tatsuya79** [comment]
Indeed disabling it in the settings seem to be enough now...
It's an old issue I reported in the google doc some time ago and you had to compile without QT back then for that bug to disappear... strange.

**Comment by Tatsuya79** [comment]
The "double return" is happening when the result of the search is on screen in glui.
If the result is outside and we scroll to it, then it's just selected without being activated.

**Comment by Tatsuya79** [comment]
fixed with #10131
