### ISSUE TITLE
[Desktop Menu] Search problems in Icons view

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#7143]
## Description

In "Icons" view some results aren’t shown at all or disappear when an additional letter is entered.

The results aren’t displayed properly following lines and columns: empty spaces of different sizes.

### Steps to reproduce the bug

Search the NEC - PC Engine collection, you should have 2 Nekketsu games.
Input "ne", you see the 2 games alongside some other ones.
Input "nek", only 1 nekketsu game is visible now.

(you can do the same test for the 2 Download/Download alt1 version)

### Version/Commit

- RetroArch: current git

### Environment information

- OS: win7 x64
- Compiler: MSYS2 gcc 7.3

**Comment by bparker06** [comment]
I made a new playlist with just the two Nekketsu games and a few other ones, and the filter worked fine then. Seems it only happens when there are at least a certain number of entries... after a few minutes of adding more and more it finally started doing it.

**Comment by Tatsuya79** [comment]
Fixed with Cozmop playlist handling rewrite.
