### ISSUE TITLE
[Desktop Menu] "Add folder" extension filtering

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#7144]
The "add folder" option (when right clicking into a playlist entries area) could have an additional box where the user would input the extensions of the files he wants to see added into the playlist.

Something like:

Extensions to add (separate multiple with ; ):    [ cue;zip  ]

It would still do "every extensions" by default.

That "add folder" to a playlist command could be added to the file browser too, when right clicking on a folder.
It would need an entry to select the targetted playlist then.

**Comment by bparker06** [comment]
What if the file is an archive?

**Comment by Tatsuya79** [comment]
Just add it as it is, this works:

```
E:\Roms\NEC - PC Engine SuperGrafx\Madou King Granzort (Japan).zip
Madou King Granzort (Japan)
DETECT
DETECT
-
NEC - PC Engine SuperGrafx.lpl
```

**Comment by bparker06** [comment]
So the extensions inside the archive should not be considered?

**Comment by Tatsuya79** [comment]
Ok I see the problem. 
Perhaps it needs a check box to do something like:
```
Add archives directly without filtering the content.
```
