### ISSUE TITLE
(Video) Full screen refresh rate mode switching based on inaccurate frequency measures

### ISSUE THREAD

**Issue by rzumer** [libretro/RetroArch#7146]
## Description

In full screen exclusive mode, RetroArch will switch to the display mode most closely matching the configured full screen resolution and refresh rate. However, the frequency information retrieved from the available display modes appears to be rounded to an integer value.

When two display modes have equal resolutions and their frequencies round to the same nearest integer (e.g. 59.940 and 60.000), the furthest one (59.940) may instead be rounded up or down to an integer value that is not the nearest one (59) in the display mode lines, and RetroArch will always switch to the other display mode (60) when finding the mode closest to the specified refresh rate (59.940).

### Expected behavior

RetroArch switches to the display mode at the frequency that matches the `video_refresh_rate` parameter.

### Actual behavior

RetroArch switches to the display mode associated with the integer value that is closest to the `video_refresh_rate` parameter, which may not be the correct one.

### Steps to reproduce the bug

1. Using [CRU](https://www.monitortests.com/forum/Thread-Custom-Resolution-Utility-CRU) or a similar application, set two display modes of equal resolution with frequencies rounding to the same integer value (e.g. an NTSC multiple and a multiple of 60.000Hz, which both round to a multiple of 60.000Hz).
2. Set the configuration as follows:
`video_windowed_fullscreen = "false"`
`video_fullscreen_x = "<display mode horizontal resolution>"`
`video_fullscreen_y = "<display mode vertical resolution>"`
`video_refresh_rate = "<the frequency that is the furthest from the integer it rounds to, e.g. the NTSC multiple>"`
3. Launch RetroArch and wait for the video frequency to stabilize

You may enable `video_windowed_fullscreen` and switch to the correct display mode manually in order to validate that it works as intended.

You may set `video_refresh_rate` to a value that rounds to the other integer boundary of the target refresh rate (e.g. 59 in the NTSC case) in order to validate that RetroArch is aware of the display mode.

### Environment information

- OS: Windows 10
- Refresh rates tested: 59.940 and 60.000

**Comment by mudlord** [comment]
There is ways in Vista and up to get the exact refresh rate. Using the DWM API you can get the exact refresh rate, including down to decimal points.
