### ISSUE TITLE
Scrolling black lines on nvidia+Windows+vulkan+4K

### ISSUE THREAD

**Issue by hizzlekizzle** [libretro/RetroArch#7151]
## Description

Users with Nvidia GPUs who use the Vulkan driver in Windows with a 4K monitor report rolling/scrolling black horizontal lines in menus and in-game. Could be related to this:
https://forums.geforce.com/default/topic/1028246/geforce-1000-series/screen-glithes-when-using-vulkan-4k-60hz/post/5239426/#5239426

Here's a thread with one of the reports (not super-useful beyond the initial description; thread gets derailed pretty quickly): https://forums.libretro.com/t/edit-vulkan-causing-black-bands-that-roll-down-the-screen/16567

### Expected behavior

Clean image

### Actual behavior

Rolling black lines

### Steps to reproduce the bug

1. Have an Nvidia GPU using recent drivers
2. Use exclusive fullscreen on a 4K monitor in Windows
Note: setting video_fullscreen_x/y to 1920x1080 resolves the issue, so that's currently the suggested workaround. It is ONLY at 4K resolution.

### Bisect Results

Has existed forever, AFAICT. It's related to a recent driver change on Nvidia's part.

### Environment information

- OS: Windows (specifically Win10, I think)
- Compiler: mingw buildbot builds

**Comment by bparker06** [comment]
Just FYI I got a report from a user that said this issue is now happening for them with GL as well, but only on a newer driver version than what they had. I asked them to comment here with more info but so far they have not.

**Comment by Awakened0** [comment]
Not sure if it's the same type of issue, but I've seen reports of it with the 416.34 drivers with GL. Here's one reddit post where they posted a screenshot of the problem and said rolling back the driver fixed it: https://www.reddit.com/r/RetroArch/comments/9na4rs/failed_to_load_content_on_certain_cores_with/e7mcv9g/?context=3

**Comment by BParks21** [comment]
This is fixed!

**Comment by hizzlekizzle** [comment]
I believe this is resolved now with driver updates. Closing.
