### ISSUE TITLE
MSVC2010 version: video_driver in retroarch.cfg does nothing

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#7154]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Read the title. Basically got the retroarch for XP on a GMA950-based netbook and it refuses to load even after getting the manifest file (which is pointlessly removed in MSVC2010 builds), set the video driver to 'sdl' in retroarch.default.cfg and ugh, it doesn't want to load! When running retroarch_debug -v it says GLSL shaders are not supported, despite the fact I'm not set it to OpenGL.

### Expected behavior

For it to load

### Actual behavior

When running retroarch_debug -v it says GLSL shaders are not supported, despite the fact I'm not set it to OpenGL.

### Steps to reproduce the bug

1) set video_driver to sdl
2) launch on XP with GMA950 or similar

### Bisect Results

what does this mean?

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.3

### Environment information

- OS: Windows XP SP3 x86
- Compiler: MSVC2010

**Comment by bparker06** [comment]
The sdl video driver should not be used (and by default I think only sdl2 is available anyway). Try d3d9, d3d10, d3d11 or gdi.

**Comment by MomijiR** [comment]
I forgot to mention: GDI doesn't work, it produces the same error.
And I tried 'd3d' and that also did produced the same error. I'll try 'd3d9' to make sure.

**Comment by bparker06** [comment]
You haven't actually said what "doesn't load" means. Do you get an error message? Does it show anything at all? What happens exactly?

It should be impossible for GDI not to work, your system would already be unusable if that were the case.

Perhaps your manifest is invalid? Try this one:

http://0bl.net/retroarch.exe.manifest

If that doesn't work then I'd need to see a log.

**Comment by zoltanvb** [comment]
This is an old bug, with all commenting users now gone, so can be probably closed.
But just for the record and future searches: 
- even in version 1.17.0, a quite similar error as #14830 can occur on a fresh install (or, alternatively, a crash)
- changing video_driver to d3d8 in the config file enables startup (i.e. I can confirm it can be changed in the file)
- after a full startup, driver can be changed back to gl1
- audio driver also needs to be changed from the default
- GDI and D3D9 video drivers are not included in the build
So, WinXP experience is far from flawless, but still manageable.
