### ISSUE TITLE
Acheivment list can crash mobile retroarch

### ISSUE THREAD

**Issue by kcin2001** [libretro/RetroArch#7158]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

if you tap an achievement in the achievement list retroarch will crash immediately

### Expected behavior

to be able to not worry about retroarch crashing as i scroll through the cheevos

### Actual behavior

if i accidentally tap a cheevo and retroarch crashes 

### Steps to reproduce the bug

1. open a game
2. go to achievments
3. tap on a cheevo entry

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: b1643f9

### Environment information

- OS: Android
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment]
What game did you run?

**Comment by kcin2001** [comment]
For the frog the bell tolls on ganebatte, i could test with other games (mostly pokemon though)

**Comment by kcin2001** [comment]
Also got it to crash on crystal and pokemon pinball (gen 3)

**Comment by RobLoach** [comment]
Coudl you get the log if avaialble?

**Comment by kcin2001** [comment]
Is that available on mobile?

**Comment by kcin2001** [comment]
I dont know if i can do that easily
