### ISSUE TITLE
[Request] Add Beetle PSX to Wii U's buildbot

### ISSUE THREAD

**Issue by ShadowOne333** [libretro/RetroArch#7161]
## Description

The Mednafen Beetle PSX core is not being compiled in the nightlies nor stable builds of the buildbot since 2017. Last known build compiled is from August 16th, 2017.

### Expected behavior

Have the Beetle PSX appearing in both stable and nightly builds for the Wii U.

### Actual behavior

Every other core, except Beetle PSX, is compiled by the buildbot

### Steps to reproduce the bug

1. Access the buildbot builds
2. Browse to Wii U's builds
3. Mednafen Beetle PSX is not present in Wii U cores

### Bisect Results

As previously mentioned in the starting description, the last known build of Mednafen Beetle PSX for Wii U was made in August 16th, 2017. After that date, no more builds have been added into the buildbot, nor is the core present in the nightlies since then.
Here's the link to the 08-16 build:
http://buildbot.libretro.com/nightly/nintendo/wiiu/latest/mednafen_psx_libretro.rpx.zip

**Comment by hizzlekizzle** [comment]
Pretty sure that's because it's nowhere near fullspeed and it just causes problems and questions when people try to run it. We'll revisit the issue if a PPC dynarec is ever written for it.
