### ISSUE TITLE
RetroArch 1.7.4 closing out after playing N64 or making adjustments

### ISSUE THREAD

**Issue by Worsel5** [libretro/RetroArch#7177]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I was told to report this issue here via Twitter. When I launch a N64 game using the Mupen64Plus core it will run fine for one time only.  If any adjustments are made to the resolution, graphical settings, etc, RetroArch will close out.  If I exit the game and relaunch it, RetroArch closes.  If I exit RetroArch and relaunch it and try to load any N64 game, RetroArch closes.

### Expected behavior

The games to play and to be able to return to them if making any adjustments or relaunching at a later time.

### Actual behavior

RetroArch goes to a black screen and closes out.

### Steps to reproduce the bug

1. Launch RetroArch
2. Navigate to N64 games
3. Select any N64 game
4. Run
5. Select Mupen64Plus as the core
6. RetroArch goes to a black screen and closes.
7. Unless a different core is selected the only way to resolve is to uninstall/reinstall RetroArch

I have also made a video showing exactly what I have been doing: https://www.youtube.com/watch?v=2RU31lp4GpY

### Bisect Results

This issue has been ongoing for me since version 1.7.1 but has gotten slightly better with the current 1.7.4 build.  In previous builds if RetroArch crashed from doing the methods described above it would refuse to load any game from any platform or core and instantly close out. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: b1643f9275

### Environment information

- OS: Windows 10 x64 Build 17134.254 (v10.0)

**Comment by RobLoach** [comment]
If you find the logs, it may tell you what is missing.

**Comment by RobLoach** [comment]
https://docs.libretro.com/guides/generating-retroarch-logs/#generating-logs-in-windows

**Comment by Worsel5** [comment]
Right, that was done but I don't know exactly what I am looking for in the log it generates.  From what I can tell it shows all the paths, controller configurations, and more.

Is there something I should be looking for or should I post the entire thing into here?

**Comment by orbea** [comment]
Yes, please post the entire log here. Preferably wrapped in code tags to make it easier to read.

**Comment by Worsel5** [comment]
The log after I launched RetroArch and tried to load GoldenEye 007.

[INFO] RetroArch 1.7.4 (Git b1643f9275)
[INFO] === Build =======================================
[INFO] Version: 1.7.4
[INFO] Git: b1643f9275
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "C:\Users\worse\AppData\Roaming\RetroArch\saves\.srm".
[INFO] Redirecting savestate to "C:\Users\worse\AppData\Roaming\RetroArch\states\.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 960/PCIe/SSE2.
[INFO] [GL]: Version: 4.6.0 NVIDIA 399.07.
[INFO] [GL]: Using resolution 960x720
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ... 
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [XInput]: Found XInput v1.4.
[INFO] [XInput]: Found controller, user #0
[INFO] [XInput]: Pads connected: 1
[INFO] [DINPUT]: Enumerating joypads ...
[INFO] [DINPUT]: Device #0 PID: {028E} VID:{045E}
[INFO] [DINPUT]: Done enumerating joypads ...
[INFO] [XInput]: Attempting autoconf for "XInput Controller (User 1)", user #0
[INFO] [DINPUT]: Found XInput pad at index 0 (DINPUT index 0)
[INFO] [XInput]: Found VID/PID (045E/028E) from DINPUT index 0 for "XInput Controller (User 1)", user #0
[INFO] [XInput]: Attempting autoconf for user #1
[INFO] [XInput]: Attempting autoconf for user #2
[INFO] [XInput]: Attempting autoconf for user #3
[INFO] [XInput]: Attempting autoconf for user #4
[INFO] [XInput]: Attempting autoconf for user #5
[INFO] [XInput]: Attempting autoconf for user #6
[INFO] [XInput]: Attempting autoconf for user #7
[INFO] [XInput]: Attempting autoconf for user #8
[INFO] [XInput]: Attempting autoconf for user #9
[INFO] [XInput]: Attempting autoconf for user #10
[INFO] [XInput]: Attempting autoconf for user #11
[INFO] [XInput]: Attempting autoconf for user #12
[INFO] [XInput]: Attempting autoconf for user #13
[INFO] [XInput]: Attempting autoconf for user #14
[INFO] [XInput]: Attempting autoconf for user #15
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: 111 profiles found.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] XAudio2: Requesting 64 ms latency, using 64 ms latency.
[INFO] [autoconf]: selected configuration: C:\Users\worse\AppData\Roaming\RetroArch\autoconfig\xinput\XInput_Controller_User_1.cfg
[INFO] [Menu]: Found menu display driver: "menu_display_gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 00000000009F6760
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "winmm" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_history.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_favorites.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_music_history.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_video_history.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[INFO] Using content: E:\Games\Emulation\N64\ROMS\ROMs - Nintendo - Nintendo 64\007 - GoldenEye (USA).z64.
[INFO] arg #0: retroarch
[INFO] arg #1: E:\Games\Emulation\N64\ROMS\ROMs - Nintendo - Nintendo 64\007 - GoldenEye (USA).z64
[INFO] arg #2: -s
[INFO] arg #3: C:\Users\worse\AppData\Roaming\RetroArch\saves
[INFO] arg #4: -S
[INFO] arg #5: C:\Users\worse\AppData\Roaming\RetroArch\states
[INFO] arg #6: -c
[INFO] arg #7: C:\Users\worse\AppData\Roaming\RetroArch\retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: C:\Users\worse\AppData\Roaming\RetroArch\cores\mupen64plus_libretro.dll
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : C:\Users\worse\AppData\Roaming\RetroArch\retroarch.cfg
[INFO] RetroArch 1.7.4 (Git b1643f9275)
[INFO] Redirecting save file to "C:\Users\worse\AppData\Roaming\RetroArch\saves\007 - GoldenEye (USA).srm".
[INFO] Redirecting savestate to "C:\Users\worse\AppData\Roaming\RetroArch\states\007 - GoldenEye (USA).state".
[INFO] === Build =======================================
[INFO] Version: 1.7.4
[INFO] Git: b1643f9275
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "C:\Users\worse\AppData\Roaming\RetroArch\cores\mupen64plus_libretro.dll"
[INFO] [overrides] no core-specific overrides found at C:\Users\worse\AppData\Roaming\RetroArch\config\Mupen64Plus OpenGL\Mupen64Plus OpenGL.cfg.
[INFO] [overrides] no content-dir-specific overrides found at C:\Users\worse\AppData\Roaming\RetroArch\config\Mupen64Plus OpenGL\ROMs - Nintendo - Nintendo 64.cfg.
[INFO] [overrides] no game-specific overrides found at C:\Users\worse\AppData\Roaming\RetroArch\config\Mupen64Plus OpenGL\007 - GoldenEye (USA).cfg.
[INFO] Shaders: preset directory: C:\Users\worse\AppData\Roaming\RetroArch\shaders\presets
[INFO] Shaders: no game-specific preset found at C:\Users\worse\AppData\Roaming\RetroArch\shaders\presets\Mupen64Plus OpenGL\007 - GoldenEye (USA).cgp.
[INFO] Shaders: no game-specific preset found at C:\Users\worse\AppData\Roaming\RetroArch\shaders\presets\Mupen64Plus OpenGL\007 - GoldenEye (USA).glslp.
[INFO] Shaders: no content-dir-specific preset found at C:\Users\worse\AppData\Roaming\RetroArch\shaders\presets\Mupen64Plus OpenGL\ROMs - Nintendo - Nintendo 64.cgp.
[INFO] Shaders: no content-dir-specific preset found at C:\Users\worse\AppData\Roaming\RetroArch\shaders\presets\Mupen64Plus OpenGL\ROMs - Nintendo - Nintendo 64.glslp.
[INFO] Shaders: no core-specific preset found at C:\Users\worse\AppData\Roaming\RetroArch\shaders\presets\Mupen64Plus OpenGL\Mupen64Plus OpenGL.cgp.
[INFO] Shaders: no core-specific preset found at C:\Users\worse\AppData\Roaming\RetroArch\shaders\presets\Mupen64Plus OpenGL\Mupen64Plus OpenGL.glslp.
[INFO] Environ SET_VARIABLES.
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Controller port: 2
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Controller port: 3
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Controller port: 4
[INFO]    Controller (ID: 1)
[INFO]    RetroPad (ID: 1)
[INFO] Remaps: remap directory: C:\Users\worse\AppData\Roaming\RetroArch\config\remaps
[INFO] Remaps: no game-specific remap found at C:\Users\worse\AppData\Roaming\RetroArch\config\remaps\Mupen64Plus OpenGL\007 - GoldenEye (USA).rmp.
[INFO] Remaps: no content-dir-specific remap found at C:\Users\worse\AppData\Roaming\RetroArch\config\remaps\Mupen64Plus OpenGL\ROMs - Nintendo - Nintendo 64.rmp.
[INFO] Remaps: no core-specific remap found at C:\Users\worse\AppData\Roaming\RetroArch\config\remaps\Mupen64Plus OpenGL\Mupen64Plus OpenGL.rmp.
[INFO] Redirecting save file to "C:\Users\worse\AppData\Roaming\RetroArch\saves\007 - GoldenEye (USA).srm".
[INFO] Redirecting savestate to "C:\Users\worse\AppData\Roaming\RetroArch\states\007 - GoldenEye (USA).state".
[INFO] Environ SYSTEM_DIRECTORY: "C:\Users\worse\AppData\Roaming\RetroArch\system".
[INFO] Environ SYSTEM_DIRECTORY: "C:\Users\worse\AppData\Roaming\RetroArch\system".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ GET_PERF_INTERFACE.
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[INFO] Environ GET_RUMBLE_INTERFACE.
[INFO] Loading content file: E:\Games\Emulation\N64\ROMS\ROMs - Nintendo - Nintendo 64\007 - GoldenEye (USA).z64.
[INFO] Did not find a valid content patch.
[INFO] CRC32: 0xb6330846 .
[INFO] Environ GET_VARIABLE mupen64plus-rspmode:
[INFO] 	HLE
[INFO] Environ GET_VARIABLE mupen64plus-BilinearMode:
[INFO] 	standard
[INFO] Environ GET_VARIABLE mupen64plus-MultiSampling:
[INFO] 	0
[INFO] Environ GET_VARIABLE mupen64plus-EnableFBEmulation:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-EnableCopyColorToRDRAM:
[INFO] 	Async
[INFO] Environ GET_VARIABLE mupen64plus-EnableCopyDepthToRDRAM:
[INFO] 	Software
[INFO] Environ GET_VARIABLE mupen64plus-EnableHWLighting:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-CorrectTexrectCoords:
[INFO] 	Off
[INFO] Environ GET_VARIABLE mupen64plus-EnableNativeResTexrects:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-txFilterMode:
[INFO] 	None
[INFO] Environ GET_VARIABLE mupen64plus-txEnhancementMode:
[INFO] 	None
[INFO] Environ GET_VARIABLE mupen64plus-txFilterIgnoreBG:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-txHiresEnable:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-txHiresFullAlphaChannel:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-EnableLegacyBlending:
[INFO] 	False
[INFO] Environ GET_VARIABLE mupen64plus-EnableFragmentDepthWrite:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-EnableShadersStorage:
[INFO] 	True
[INFO] Environ GET_VARIABLE mupen64plus-CropMode:
[INFO] 	Auto
[INFO] Environ GET_VARIABLE mupen64plus-cpucore:
[INFO] 	dynamic_recompiler
[INFO] Environ GET_VARIABLE mupen64plus-aspect:
[INFO] 	4:3
[INFO] Environ GET_VARIABLE mupen64plus-43screensize:
[INFO] 	320x240
[INFO] Environ GET_VARIABLE mupen64plus-astick-deadzone:
[INFO] 	15
[INFO] Environ GET_VARIABLE mupen64plus-astick-sensitivity:
[INFO] 	100
[INFO] Environ GET_VARIABLE mupen64plus-CountPerOp:
[INFO] 	0
[INFO] Environ GET_VARIABLE mupen64plus-r-cbutton:
[INFO] 	C1
[INFO] Environ GET_VARIABLE mupen64plus-l-cbutton:
[INFO] 	C2
[INFO] Environ GET_VARIABLE mupen64plus-d-cbutton:
[INFO] 	C3
[INFO] Environ GET_VARIABLE mupen64plus-u-cbutton:
[INFO] 	C4
[INFO] Environ GET_VARIABLE mupen64plus-pak1:
[INFO] 	memory
[INFO] Environ GET_VARIABLE mupen64plus-pak2:
[INFO] 	none
[INFO] Environ GET_VARIABLE mupen64plus-pak3:
[INFO] 	none
[INFO] Environ GET_VARIABLE mupen64plus-pak4:
[INFO] 	none
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting OpenGL context.
[INFO] Environ SYSTEM_DIRECTORY: "C:\Users\worse\AppData\Roaming\RetroArch\system".
[libretro INFO] EmuThread: M64CMD_ROM_OPEN
[libretro INFO] mupen64plus: Goodname: GoldenEye 007 (U) [!]
[libretro INFO] mupen64plus: Name: GOLDENEYE           
[libretro INFO] mupen64plus: MD5: 70C525880240C1E838B8B1BE35666C3B
[libretro INFO] mupen64plus: CRC: DCBC50D1 09FD1AA3
[libretro INFO] mupen64plus: Imagetype: .z64 (native)
[libretro INFO] mupen64plus: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
[libretro INFO] mupen64plus: ClockRate = F
[libretro INFO] mupen64plus: Version: 1447
[libretro INFO] mupen64plus: Manufacturer: Nintendo
[libretro INFO] mupen64plus: Cartridge_ID: 4547
[libretro INFO] mupen64plus: Country: USA
[libretro INFO] mupen64plus: PC = 80000400
[libretro INFO] mupen64plus: Save type: 0
[libretro INFO] EmuThread: M64CMD_ROM_GET_HEADER
[INFO] Skipping SRAM load..
[INFO] Found auto savestate in: C:\Users\worse\AppData\Roaming\RetroArch\states\007 - GoldenEye (USA).state.auto
[INFO] Auto-loading savestate from "C:\Users\worse\AppData\Roaming\RetroArch\states\007 - GoldenEye (USA).state.auto" succeeded.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44055.95 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [GL]: Found GL context: wgl
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [WGL]: wglSwapInterval(1)
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: GeForce GTX 960/PCIe/SSE2.
[INFO] [GL]: Version: 4.6.0 NVIDIA 399.07.
[INFO] [GL]: Using resolution 960x720
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Resetting shader to defaults ... 
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (512 x 512).
[INFO] [GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [XInput]: Found XInput v1.4.
[INFO] [XInput]: Found controller, user #0
[INFO] [XInput]: Pads connected: 1
[INFO] [DINPUT]: Enumerating joypads ...
[INFO] [DINPUT]: Device #0 PID: {028E} VID:{045E}
[INFO] [DINPUT]: Done enumerating joypads ...
[INFO] [XInput]: Attempting autoconf for "XInput Controller (User 1)", user #0
[INFO] [DINPUT]: Found XInput pad at index 0 (DINPUT index 0)
[INFO] [XInput]: Found VID/PID (045E/028E) from DINPUT index 0 for "XInput Controller (User 1)", user #0
[INFO] [XInput]: Attempting autoconf for user #1
[INFO] [XInput]: Attempting autoconf for user #2
[INFO] [XInput]: Attempting autoconf for user #3
[INFO] [XInput]: Attempting autoconf for user #4
[INFO] [XInput]: Attempting autoconf for user #5
[INFO] [XInput]: Attempting autoconf for user #6
[INFO] [XInput]: Attempting autoconf for user #7
[INFO] [XInput]: Attempting autoconf for user #8
[INFO] [XInput]: Attempting autoconf for user #9
[INFO] [XInput]: Attempting autoconf for user #10
[INFO] [XInput]: Attempting autoconf for user #11
[INFO] [XInput]: Attempting autoconf for user #12
[INFO] [XInput]: Attempting autoconf for user #13
[INFO] [XInput]: Attempting autoconf for user #14
[INFO] [XInput]: Attempting autoconf for user #15
[INFO] [Joypad]: Found joypad driver: "xinput".
[INFO] [Autoconf]: 111 profiles found.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] Environ SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, User 1, Button "B (bottom)" => "A Button (C3)"
[INFO] 	RetroPad, User 1, Button "Y (left)" => "B Button (C2)"
[INFO] 	RetroPad, User 1, Button "Start" => "START Button"
[INFO] 	RetroPad, User 1, Button "D-Pad Up" => "Up (digital)"
[INFO] 	RetroPad, User 1, Button "D-Pad Down" => "Down (digital)"
[INFO] 	RetroPad, User 1, Button "D-Pad Left" => "Left (digital)"
[INFO] 	RetroPad, User 1, Button "D-Pad Right" => "Right (digital)"
[INFO] 	RetroPad, User 1, Button "A (right)" => "(C1)"
[INFO] 	RetroPad, User 1, Button "X (up)" => "(C4)"
[INFO] 	RetroPad, User 1, Button "L" => "L-Trigger"
[INFO] 	RetroPad, User 1, Button "R" => "R-Trigger"
[INFO] 	RetroPad, User 1, Button "L2" => "Z-Trigger"
[INFO] 	RetroPad, User 1, Button "R2" => "C Buttons Mode"
[INFO] 	RetroPad, User 2, Button "B (bottom)" => "A Button (C3)"
[INFO] 	RetroPad, User 2, Button "Y (left)" => "B Button (C2)"
[INFO] 	RetroPad, User 2, Button "Start" => "START Button"
[INFO] 	RetroPad, User 2, Button "D-Pad Up" => "Up (digital)"
[INFO] 	RetroPad, User 2, Button "D-Pad Down" => "Down (digital)"
[INFO] 	RetroPad, User 2, Button "D-Pad Left" => "Left (digital)"
[INFO] 	RetroPad, User 2, Button "D-Pad Right" => "Right (digital)"
[INFO] 	RetroPad, User 2, Button "A (right)" => "(C1)"
[INFO] 	RetroPad, User 2, Button "X (up)" => "(C4)"
[INFO] 	RetroPad, User 2, Button "L" => "L-Trigger"
[INFO] 	RetroPad, User 2, Button "R" => "R-Trigger"
[INFO] 	RetroPad, User 2, Button "L2" => "Z-Trigger"
[INFO] 	RetroPad, User 2, Button "R2" => "C Buttons Mode"
[INFO] 	RetroPad, User 3, Button "B (bottom)" => "A Button (C3)"
[INFO] 	RetroPad, User 3, Button "Y (left)" => "B Button (C2)"
[INFO] 	RetroPad, User 3, Button "Start" => "START Button"
[INFO] 	RetroPad, User 3, Button "D-Pad Up" => "Up (digital)"
[INFO] 	RetroPad, User 3, Button "D-Pad Down" => "Down (digital)"
[INFO] 	RetroPad, User 3, Button "D-Pad Left" => "Left (digital)"
[INFO] 	RetroPad, User 3, Button "D-Pad Right" => "Right (digital)"
[INFO] 	RetroPad, User 3, Button "A (right)" => "(C1)"
[INFO] 	RetroPad, User 3, Button "X (up)" => "(C4)"
[INFO] 	RetroPad, User 3, Button "L" => "L-Trigger"
[INFO] 	RetroPad, User 3, Button "R" => "R-Trigger"
[INFO] 	RetroPad, User 3, Button "L2" => "Z-Trigger"
[INFO] 	RetroPad, User 3, Button "R2" => "C Buttons Mode"
[INFO] 	RetroPad, User 4, Button "B (bottom)" => "A Button (C3)"
[INFO] 	RetroPad, User 4, Button "Y (left)" => "B Button (C2)"
[INFO] 	RetroPad, User 4, Button "Start" => "START Button"
[INFO] 	RetroPad, User 4, Button "D-Pad Up" => "Up (digital)"
[INFO] 	RetroPad, User 4, Button "D-Pad Down" => "Down (digital)"
[INFO] 	RetroPad, User 4, Button "D-Pad Left" => "Left (digital)"
[INFO] 	RetroPad, User 4, Button "D-Pad Right" => "Right (digital)"
[INFO] 	RetroPad, User 4, Button "A (right)" => "(C1)"
[INFO] 	RetroPad, User 4, Button "X (up)" => "(C4)"
[INFO] 	RetroPad, User 4, Button "L" => "L-Trigger"
[INFO] 	RetroPad, User 4, Button "R" => "R-Trigger"
[INFO] 	RetroPad, User 4, Button "L2" => "Z-Trigger"
[INFO] 	RetroPad, User 4, Button "R2" => "C Buttons Mode"
[INFO] XAudio2: Requesting 64 ms latency, using 64 ms latency.
[INFO] [autoconf]: selected configuration: C:\Users\worse\AppData\Roaming\RetroArch\autoconfig\xinput\XInput_Controller_User_1.cfg
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 00000000009F6760
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "winmm" driver.
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_history.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_favorites.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_music_history.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_video_history.lpl].
[INFO] Loading history file: [C:\Users\worse\AppData\Roaming\RetroArch\content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[WARN] [WGL]: wglSwapInterval() failed.
[libretro INFO] EmuThread: M64CMD_EXECUTE. 
[INFO] Environ SYSTEM_DIRECTORY: "C:\Users\worse\AppData\Roaming\RetroArch\system".
[INFO] Environ SYSTEM_DIRECTORY: "C:\Users\worse\AppData\Roaming\RetroArch\system".
[INFO] Environ SYSTEM_DIRECTORY: "C:\Users\worse\AppData\Roaming\RetroArch\system".
[libretro INFO] mupen64plus: Memory initialized
[libretro INFO] mupen64plus: Starting R4300 emulator: Dynamic Recompiler
[libretro INFO] mupen64plus: R4300: starting 64-bit dynamic recompiler at: 000000001CF628F0
[INFO] Loading state: "C:\Users\worse\AppData\Roaming\RetroArch\states\007 - GoldenEye (USA).state.auto".
[INFO] State size: 16789316 bytes.
[INFO] Saving state: "RAM".
[INFO] State size: 16789316 bytes.

**Comment by bparker06** [comment]
What does "closes out" mean? Is there a crash? Any error message? Does the program just disappear? We need a lot more information as nobody else seems to be having this problem.

**Comment by Worsel5** [comment]
There is a video in the "Steps to reproduce the bug" section.

**Comment by bparker06** [comment]
It looks like you've changed other settings besides the defaults (I can see you have auto-load state on at least). Can you please try deleting/renaming retroarch.cfg and retroarch-core-options.cfg and try it again, both without changing any settings at all, and only changing the settings that you are having issues with?

**Comment by Worsel5** [comment]
Excellent, that seems to have corrected the issue.  I can exit the game and relaunch it without issue as well as make graphical changes and have it launch again.  So in the future don't turn on auto-load state.  Thank you for your time on this problem, it's greatly appreciated.
