### ISSUE TITLE
GPD XD Plus - Input binding is not accepted since 1.7.4 (fine with 1.7.3 and bellow)

### ISSUE THREAD

**Issue by farfenkugell** [libretro/RetroArch#7180]
## Description
I have GPD XD Plus, an Android 7 based device with build in controller.
 I have been using android version of retroarch since 1.7.1,     1.7.2    1.7.3 and had no issues.
Since the version 1.7.4 (both bit versions) were released input binding no longer works for build in controller, it does work in other menus of the device.
PS: plugging in the external controller via otg or Bluetooth still works

### Expected behavior
While in Settings - Input - Input User 1 Binds - "User 1 Bind All"
You should be able to bind controls to build in GPD XD Plus controller

### Actual behavior
While in Settings - Input - Input User 1 Binds - "User 1 Bind All"
You get an option to input a key for a bind, but instead of accepting it, 5s counter resets and you are asked to input key for the same bind again which causes an endless loop of binding which does not save.
### Steps to reproduce the bug
Install any version below 1.7.4 try to bind input, it will work.
Update to 1.7.4 try to bind keys again, it will not accept them.
### Bisect Results
1.7.3 (works) 
1.7.4 (does not work)

### Environment information
Android 7

###Extra
I did the factory reset of the device.
It comes with retroarch 1.7.1, updated it via .apk files found in your repository.
1.7.1 binding works
1.7.2. binding works
1.7.3 binding works
1.7.4 binding no longer works, tried both bit versions

**Comment by fr500** [comment]
Hmm, you're not reading the prompt, it's now a press and hold.
It's done to prevent touch or motion events from registering.

I guess we should make it configurable, but regardless, it's not a problem I just verified.

**Comment by farfenkugell** [comment]
That might be the case, yet I did not see any release notes for that, and after using retropie for years that text automatically for some reason meant hold to skip. Will have to re-check later once back home.

**Comment by farfenkugell** [comment]
Yup, you are correct.
