### ISSUE TITLE
Overlays on Vulkan driver bug

### ISSUE THREAD

**Issue by VoSed** [libretro/RetroArch#7181]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The gamepad overlays do not completely work when using the Vulkan driver on Android. If you tap on ↺ button, overlay disappears.

### Expected behavior

↺ button must change overlay mode to portrait

### Actual behavior

↺ button hides overlay

### Steps to reproduce the bug

1. Change driver from gl to vulkan
2. Tap to ↺ button on gamepad overlay

### Bisect Results

This started happening when I started use vulkan driver

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.x

### Environment information

- OS: Android 8.1

**Comment by QuaiGoner** [comment]
Same Problem Device: Xiaomi Redmi Note 4X
OpenGL is Fine

**Comment by hizzlekizzle** [comment]
This happens on all platforms with vulkan drivers, not just Android, apparently: https://github.com/libretro/RetroArch/issues/7228

**Comment by twinaphex** [comment]
Yes, confirmed. @Themaister This happens even with the base overlay (retropad.cfg). Any thoughts?

**Comment by twinaphex** [comment]
This is finally fixed now as of this commit -

https://github.com/libretro/RetroArch/commit/66e7c73193219122de20fcd77bd459948c93aa5d
