### ISSUE TITLE
Configs on Mednafen VB and Wonderswan Crashes

### ISSUE THREAD

**Issue by james1222312334** [libretro/RetroArch#7195]
# First and foremost consider this:
When I try to make a Config for Mednafen VB and Mednafen Wonderswan it just crashes.

## Description

I managed to make a Config for Mednafen VB and it just crashed.

### Expected behavior

Make a Mapping for my games

### Actual behavior

It crashed

### Steps to reproduce the bug

1. Create a Custom mapping

### Bisect Results

I've been using my Switch Pro Controller all the time.

### Version/Commit

- RetroArch: [1.7.4/NeoCD Core]

### Environment information

- OS: Windows 10
- Compiler: N/A

**Comment by bparker06** [comment]
Please use the issue template that you deleted when making a new issue.

**Comment by james1222312334** [comment]
shut up bparker I know what to do.

**Comment by twinaphex** [comment]
@james1222312334 Never disrespect our core team members like this again. If I see you doing this one more time, I will report your abusive comment to Github.
