### ISSUE TITLE
PAL PAR is broken in latest Android update (Aug 30 2018/b1643f9)

### ISSUE THREAD

**Issue by turboboy215** [libretro/RetroArch#7196]
## Description

I have been using RetroArch for Android since late 2017. I have installed several cores, Nestopia UE, Gambatte and more, and they have all worked very well. That is, until the last update, which occurred a week or so ago.
### Expected behavior

With NES and MegaDrive and Master System games using their respective emulators, the PAL PAR option is what I always used. It looked like they were running on a real TV.

### Actual behavior

However, the option no longer works properly and seems to break several emulators; with Nestopia UE, it is stuck at the NTSC PAR, and with Genesis Plus GX the PAR is horribly squashed - as in it doesn't even fit the vertical resolution of the phone's screen as it did before.

[What is actually happening]

### Steps to reproduce the bug

1. Download any core that has an option for PAL PAR, such as the two that I mentioned
2. Select the PAL PAR option
3. It either is just stuck at the NTSC PAR or looks horribly squashed.
### Bisect Results

This didn't happen until the latest update.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Aug 30 2018/b1643f9

### Environment information

OS: Android (v8.0) (Nexus 5x)

**Comment by bparker06** [comment]
Double check your aspect ratio within RA under Settings -> Video as the indexes have recently changed. You probably want it to be on "Core provided".
