### ISSUE TITLE
[Request] 3x Internal Resolution option for Beetle PSX HW

### ISSUE THREAD

**Issue by BassyBunny** [libretro/RetroArch#7202]
Currently Beetle PSX HW only has increments in the power of two for internal resolution.  (1x, 2x, 4x, 8x, 16x and 32x)

It would be nice to see an option added for 3x internal resolution, as currently increasing internal resolution extremely taxing on Beetle PSX HW and causes a huge performance hit, having an option that looks better than 2x but isn't as big of a performance hit as 4x would be brilliant, if this is possible.

**Comment by bparker06** [comment]
Please use the core's issue tracker for this:

https://github.com/libretro/beetle-psx-libretro/issues
