### ISSUE TITLE
Black Frame Insertion 120hz - Dimming

### ISSUE THREAD

**Issue by JHorbach** [libretro/RetroArch#7213]
Hello! I have my monitor set to 120hz, and Retroarch configured with 60hz refresh rate and Black Frame Insertion actived (as the Black Frame Insertion option especifies), the game runs smoothly, no flicker, no drops nothing, but the colors become darker, as if there is a shadow mask. If I set the retroarch refresh rate to 120hz it stays the same way. Just to report my monitor native frequence is 144hz (ASUS MG248QR), but I manually set it to 120hz, is there something I can do to prevent this from happening (dimming)? Playing the games with 120hz and Vsync Swap Interval 2 doesn't seems so smooth as with Black frame insertion. I don't know if this is a Bug or something. English isn't my native language, but I think you can understand what I'm saiying.

**Comment by hizzlekizzle** [comment]
Not a bug. Black frame insertion puts a frame of black in between each frame of content, so the average brightness over time is halved. You can try compensating by increasing the brightness of your display, but that can be a hassle to do every time you want to play a game.

**Comment by bparker06** [comment]
For me, playing 60fps games with RA set to 120hz and swap interval=2 is just as smooth as BFI *or* G-Sync.

**Comment by westonlast** [comment]
Why do you get burn-in from Black Frame Insertion?  I would think it would be more like anti-burn-in?

**Comment by mdrejhon** [comment]
There is also a solution to BFI image retention + screendoor effect:
http://forum.arcadecontrols.com/index.php/topic,162926.msg1715890.html

(Scroll down to "**Burn-In Fix For Software BFI**")
