### ISSUE TITLE
[Vulkan] Second overlay doesn't show

### ISSUE THREAD

**Issue by GyoMan** [libretro/RetroArch#7228]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I have setup MEDNAFEN PSX HW core to use VULKAN. I have defined two overlays so i can switch between them with a keyboard shortcut.

When the core loads the first overlay is displayed correctly as it should, but when i press the shortcut to change to the second layout it doesn’t display at all (and the first overlay disappears).

If i set the driver to use GL the overlays work and change fine. I suspect it is a problem with the VULKAN driver.

### Expected behavior

Display second overlay

### Actual behavior

When the core loads the first overlay is displayed correctly as it should, but when i press the shortcut to change to the second layout it doesn’t display at all (and the first overlay disappears).

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.74

### Environment information

- OS: Win7/64
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
Can confirm. It's been happening for a very long time (forever?). It happens with overlay_next actions in an overlay.

**Comment by twinaphex** [comment]
@Themaister I have noticed this issue only happens with Vulkan. It doesn't happen with D3D10/D3D11/D3D12, or GL.

To test -

![image](https://user-images.githubusercontent.com/1075274/47064204-b6864d80-d1de-11e8-84d0-5ff2836d165c.png)

Click on the arrow down in the overlay. Typically this would bring you to the next overlay. With Vulkan instead, it just stops displaying any overlays whatsoever.

**Comment by twinaphex** [comment]
This is finally fixed now as of this commit -

https://github.com/libretro/RetroArch/commit/66e7c73193219122de20fcd77bd459948c93aa5d
