### ISSUE TITLE
(iOS 9 to 11) Broken since the METAL add for OS X from June. A little FIX here to run the last build on iOS.

### ISSUE THREAD

**Issue by Alex793** [libretro/RetroArch#7256]
Hello Guys, since the METAL add for the OS X version ( commit cd174c8 of the 21th June version 1.7.3 ), the iOS build is completely broken ( for iOS 9-10-11 ).

Compilation is OK but the APP simply CRASH at launch as some also reported on the libretro forum ( don't know why they don't post here ).

The commit cd174c8 changed many files whit the METAL add, and the problematic file for the iOS version is this one : **/gfx/drivers_context/macos_ctx.m** ( https://github.com/libretro/RetroArch/commit/cd174c899afcd3a9544ae7a0d021e0637545cb00#diff-7a7cc9c6c664828955c44d38e0a0a633 )

The iOS build use this file as the OS X version, and after some research (I'm not an expert lol) I found a little fix.

The problem are these new lines from the commit cd174c8 ( https://github.com/libretro/RetroArch/commit/cd174c899afcd3a9544ae7a0d021e0637545cb00#diff-7a7cc9c6c664828955c44d38e0a0a633 ) :

![fix 1 7 5 2](https://user-images.githubusercontent.com/428805/45789969-ddef0680-bc82-11e8-97b7-93bec4e4f3b1.jpg)

I removed them and tada the build (include the last from the git) is now OK on iOS 9-10-11, no more crash at launch.

Example for the last build on the git, in file **/gfx/drivers_context/macos_ctx.m** remove these lines : 

![fix ra 1 7 5](https://user-images.githubusercontent.com/428805/45790111-8ef5a100-bc83-11e8-89f8-6f5acc6c94dd.jpg)

Compile, Run and it's OK for iOS 9-10-11.

I can't tell you what is the exact problem because I'm not an expert, and maybe this affect the OS X build too, so if anyone with better skill than me can check for a better fix it will be perfect.

This is my simple iOS FIX and with this we can now run the latest builds on iOS 9-10-11, I think there is a better solution but as I said I'm not an expert... I help as I can.

**Comment by twinaphex** [comment]
Paging @stuartcarnie.

We indeed need to come up with a solution for this soon.

**Comment by yoshisuga** [comment]
I put in a PR for this - I think a stop-gap solution that fixes the iOS build by commenting out the line of code is probably sufficient here, at least until this platform unification/metal support work is complete.

**Comment by yoshisuga** [comment]
This is no longer occurring and can be closed.
