### ISSUE TITLE
[Translation] Missing hash

### ISSUE THREAD

**Issue by waitingmoon** [libretro/RetroArch#7264]
intl/msg_hash_us.h, msg_hash_es.h, and some others has about 7500 lines. but Japanese one has only 3500 lines. why is it so different? also, I've noticed some hashes were missing. there is no way to translate.

e.g.
- MENU_ENUM_SUBLABEL_ADD_TO_FAVORITES
- MENU_ENUM_SUBLABEL_SAVE_CURRENT_CONFIG_OVERRIDE_CONTENT_DIR

**Comment by bparker06** [comment]
If a translation file does not have a corresponding hash, it just uses the English one from msg_hash_us.h. Feel free to add any missing hashes into msg_hash_ja.h and provide a translation for them, it should start to work automatically.

I also wrote a script that finds missing enums from translation files, here is the output for Japanese:

https://www.hastebin.com/sayapojuqe.cpp

And the script itself:

https://www.hastebin.com/avekovopis.py

Hope this helps.

**Comment by waitingmoon** [comment]
I thought that each hashes were automatically generated from the English file. Thank you for writing a script and useful information. if there is no problem, please close this issue.

**Comment by bparker06** [comment]
Nope, all the hashes are defined in an enum in msg_hash.h, and the UI code just checks for an entry for the current language first, and if there isn't one, then it uses the English one.
