### ISSUE TITLE
Getting "Hardcore" Achievements when using savestates

### ISSUE THREAD

**Issue by ChestWellPiped** [libretro/RetroArch#7269]
## Description
I got a "hardcore" achievement after re-enabling achievement and using A LOT of save states

### Expected behavior
Get Normal Achievement

### Actual behavior
Got "Hardcore" Achievement instead

### Steps to reproduce the bug
1-disable Achievement in retroarch settings
2-get to a hard-to-get point in a game using savestate
3-enable Achievement in retroarch settings
4-get to the point in the level where the Achievement triggers
5-get "Hardcore" Achievement instead of a normal one

### Version/Commit
RetroArch Build date = Aug 30 2018

### Environment information
OS = Windows7

**Comment by meleu** [comment]
Whoops!

It should reset the game after re-enabling achievements, just like [this logic](https://github.com/libretro/RetroArch/blob/48e7f7b7fb5f324c72328d98fb3f20b25d97c69a/cheevos/cheevos.c#L2260) does for when toggling hardcore mode.

I can try something (if @fr500 don't beat me to it).

**Comment by meleu** [comment]
@twinaphex @fr500 since PR #7268 was merged, this issue here can be closed.

**Comment by orbea** [comment]
Also see PR https://github.com/libretro/RetroArch/pull/7804.

This is fixed so I am going to close it.
