### ISSUE TITLE
3DS - Any And All Neogeo Games except Art Of fighting Crash when attempting to load on both fba and mame cores

### ISSUE THREAD

**Issue by AlexS2412** [libretro/RetroArch#7273]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Crashes when loading any rom except art of fighting]

### Expected behavior

[game to load on STABLE retroarch 1.7.4]

### Actual behavior

[crashes upon hitting button to load]

### Steps to reproduce the bug

1. [Launch Game]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.7.4]

### Environment information

- OS: [3DS]
- Compiler: [In case you are running local builds]

Image of Issue: https://imgur.com/a/WFataRi

**Comment by RobLoach** [comment]
- Correct BIOS?
- What is one game that crashes when loading? What files are you loading?
- Have the logs?

**Comment by fr500** [comment]
Core issue, please file into the correct repository

**Comment by RobLoach** [comment]
Yes, need more info, and sounds like you should file it against the core. Thanks radius!
