### ISSUE TITLE
help with transfering saves on IOS

### ISSUE THREAD

**Issue by ineedhelpwithretroarchforios** [libretro/RetroArch#7275]
hello, i am using retroarch for ios, build 1.7.3. the app recently got revoked, and i redownloaded. HOWEVER, when i transferred all my games AND THE RETROARCH FOLDER FROM THE PREVIOUS DOWNLOAD it wont load the saves. i'm trying to find out how to fix this using mario world, as ive spent many hours into that save, and i would REALLY like it back. so if anyone finds this before i say i solved it, PLEASE leave a comment explaining how to fix this problem thanks in advance!

-someone who posted on the internet that you dont know anything about and probably wont want to meet him in chicago at the MSI at 4 PM on 9/25/18 in front of the entrance playing something on his phone with a snes controller.

-edit: i know i sound like a 12 year old with the capital letters, please just ignore that because i was panicing. thank you yoshisuga for fixing the problem!

**Comment by yoshisuga** [comment]
You need to go into settings - Directory - Savefile or Save state, and choose the directory you used. 

The reason why you need to select it again is because the app id changes when you reinstall the app and the file paths are absolute and end up pointing to the old location. 

I was trying to come up with a way to deal with this, but haven’t gotten around to it yet.

**Comment by ineedhelpwithretroarchforios** [comment]
thank you yoshisuga! this worked, although im not entirely sure why... i did that exact same thing, but it did not work, so when i tried it again, it did. but i think i've got it for when the new lisence inevitably gets revoked again. have a good day, thank you for fixing the problem, and play tf2 because its a good game.


Thanks!!!

**Comment by orbea** [comment]
This issue seems resolved in the above comments so I am going to close this, please let me know if this is wrong.
