### ISSUE TITLE
XMB Menu controls not working

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#7276]
## Description

With the latest code, it seems there is an issue with controlling the XMB Menu, either with a keyboard or a controller. When you scroll down on the Menu it will:

- freeze completely once you scroll past Load Content. It will unfreeze only once you move left or right to another sub-category (ie Settings, Playlists, etc.)
- when pressing the 'confirm' button on any option of the Main section, it will always redirect you to the Core buildbot downloader.

### Bisect Results

If needed I will try a bisect in a few hours and edit this post.

### Version/Commit

- RetroArch: 1.7.5, with the latest commit as of this message (4ae2f00)

### Environment information

- OS: Windows 10 x64 build 1709
- Compiler: mingw64

**Comment by alfrix** [comment]
it is #7271
`git revert -m 1 4ae2f00d451d0dc7ec9796dfe4f1f462eb3fc52f`
