### ISSUE TITLE
Downloader saves the full zip before extracting files

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7281]
## Description

Why does the downloader write the full zip before extracting it instead of extracting it from memory (it's already stored on memory)

It increases writes, and it trashes performance quite a while on platforms with slow I/O

### Expected behavior

It should just extract the zip from RAM, it's already there loaded and complete isn't it?

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
It is non-trivial to undo an extraction that fails half-way due to network problems, and people are more likely to exit RA before it would even have a chance to undo everything.

**Comment by fr500** [comment]
I didn't mean it like that, I assume once a file is completely downloaded then it's flushed to disk, and then extracted.

I haven't seen any temp files created **while** downloading.
So I think it should not flush, just extract directly from the memory blob.

**Comment by bparker06** [comment]
Ah I misread your description, sorry.

I think we shouldn't even be keeping it in memory as it causes problems with many users on low-end systems (e.g. a 512MB ram rpi cannot download a 1GB thumbnail pack).

**Comment by twinaphex** [comment]
> It increases writes, and it trashes performance quite a while on platforms with slow I/O

Well, those are definite valid concerns.

However, as @bparker06 points out, those platform with slow I/O also typically happen to not have a lot of RAM, such as the Wii, or PSP, or whatever. So keeping them in memory is also not an option since then you are sacrificing RAM that you could have used for loading bigger games, etc.

**Comment by fr500** [comment]
But we do have ways to query for available memory...
Anyway, I guess it's a won't fix
