### ISSUE TITLE
Neogeo as standalone platform

### ISSUE THREAD

**Issue by zensurette** [libretro/RetroArch#7287]
Neogeo games discovered by RetroArch are shown in XMB under the FB Alpha icon instead of under a Neogeo icon.

Could you add an option to consider systems like Neogeo as separate gaming console and not part of a generic arcade core?

I'm using Neogeo MAME's ROMs.

**Comment by RobLoach** [comment]
We don't have a "Neo Geo" database. Just an FB Alpha one.

**Comment by RobLoach** [comment]
Mind making an issue over at [libretro-database](https://github.com/libretro/libretro-database) about this? Thanks.
