### ISSUE TITLE
Retroachievements Leaderboard bug concerning "V" function

### ISSUE THREAD

**Issue by Keltron3030** [libretro/RetroArch#7288]
An unexpected result occurs when using `V-#` to subtract a number from the Value condition of a leaderboard.

In my case I used `0xh29*1_0xh2a*240_v-180`

The `v-180` was intended to remove 180 frames(3 seconds) from the value condition in Rad Racer (NES) to start the timer exactly when the race starts.

I created a test leaderboard to showcase the issue.
 
http://retroachievements.org/leaderboardinfo.php?i=4310

The erroneous result given for time at the end of a race is 596523:14.11, over 414 days!?!

To submit your own faulty time to the lb simply complete the first race using retroarch to see the same erroneous time regardless of actual race finish time.

The leaderboard works as intended when using RANes 0.014

I've gotten the same erroneous result using retroarch v1.7.4 on my Android pixel 2 phone as well as raspberry pi 3B+

@meleu

**Comment by Keltron3030** [comment]
My workaround in the meantime was to find a stable address and multiply by a negative value to acheive the same result, i.e. adding a negative 180 value to avoid using the `v-180` function.

`0xh75c*-1` where 8-bit address 0x00075c provides a stable hexadecimal value of b4 in this application which equals 180 in decimal.

**Comment by meleu** [comment]
hey @Keltron3030 can you please test this the leaderboard with the `v-180` using the RAIntegration provided by @Jamiras on our Discord server (#developer-news channel)?

If it works as expected with that Integration, then it will soon work fine on RetroArch (thanks to the @leiradel's [rcheevos](https://github.com/RetroAchievements/rcheevos)).

**Comment by Keltron3030** [comment]
Working results were achieved with the new integration so this should be resolved with the next retroarch update. Thanks
