### ISSUE TITLE
Static/corruption and stuttering when using Vulkan

### ISSUE THREAD

**Issue by t3rminus** [libretro/RetroArch#7294]
## Description
When using the Vulkan driver, extreme stuttering and graphical corruption/static occurs. The issue is not present on the same hardware when using the GL driver, or in other applications using either Vulkan or GL.

Video of issue, Vulkan driver: https://www.dropbox.com/s/mpg32xuwdosfcvw/retroarch_vulkan.mp4?dl=0
Same cores/games, GL driver:  https://www.dropbox.com/s/bgk3oah449o0dh5/retroarch_gl.mp4?dl=0

(These were recorded using capture hardware on a separate machine to not impact performance or rendering... slight audio desync is due to capture hardware.)

Output of `vulkan-info`
[vulkaninfo.txt](https://github.com/libretro/RetroArch/files/2409237/vulkaninfo.txt)

Stand-alone Dolphin emulator using Vulkan does not suffer the same issues. Other GL applications also run fine. This is specific to RetroArch.

### Expected behavior
Expected the same performance (or better) as the GL driver.

### Actual behavior
Stuttering and static/corruption make games unplayable.

### Steps to reproduce the bug
1. Switch to Vulkan video driver.

### Version/Commit
- RetroArch:  1.7.5/06d7f71

### Environment information
- OS: Ubuntu 18.04/Elementary OS, Kernel 4.15.0-34
- Compiler: N/A
- GPU: Intel Graphics HD 520

**Comment by t3rminus** [comment]
Hm. Was able to cause flickering/issues in stand-alone Dolphin as well, but only running full-screen. Similarly, running RetroArch windowed caused the issue to disappear. Might be due to the compositor. Closing issue for now.

**Comment by cam1170** [comment]
I may be having the same issue as t3rminus. Using Ubuntu 18.04, Intel HD Graphics 620, mesa-vulkan-driver. Using xmb, it's fine for 10 or 20 seconds but then starting minorly at the top, it increases for a bit, going up to half way down the screen and then it stops and repeats the cycle. This occurs in vulkan but not gl. Haven't tried Dolphin yet. Also I'm new to GitHub if this is in the wrong place.

**Comment by t3rminus** [comment]
@cam1170 This issue ended up being a bug in Intel's Vulkan drivers, which has since been fixed. https://bugs.freedesktop.org/show_bug.cgi?id=99507

It likely hasn't made its way into the Ubuntu repos, yet, but with some googling you can find some PPAs with more up-to-date libdrm and mesa packages to install easily. (I can't remember which version is required, unfortunately)

**Comment by cam1170** [comment]
Fixed, I was stuck on 18.2.2, went away on 18.3.3
