### ISSUE TITLE
"Don't override SaveRAM on loading savestate" on RA settings is either broken or not working.

### ISSUE THREAD

**Issue by CsoiretgeFsM** [libretro/RetroArch#7320]
## Description

"Don't override SaveRAM on loading savestate" is set to **ON** in **MAIN RetroArch** settings, but is either broken or not working properly. I’m having this exact issue verbatim:

https://github.com/libretro/beetle-psx-libretro/issues/190

### Expected behavior

I'm using beetle PSX so I expect my "Memory Card" game saves from any/all of my games to not be affected/change depending on what savestate I load from the last game I played, and I expect them to all be inside "mednafen_psx_libretro_shared.0.mcr" simultaneously, as stated in https://docs.libretro.com/library/beetle_psx/ & https://docs.libretro.com/library/beetle_psx_hw/.

### Actual behavior

I tried veiwing the contents of the Memory Card slot 1 file (mednafen_psx_libretro_shared.0.mcr), via Memcard Rex and loading memory card saves via the game itself, and it’s content changes depending on what savestate I load and what game I loaded last despite having "Don't override SaveRAM on loading savestate" set to **ON**. Even in the libretro docs it says it shouldn't be doing that. Here's a verbatim quote from the https://docs.libretro.com/library/beetle_psx/ & https://docs.libretro.com/library/beetle_psx_hw/ pages:

/!\ **Warning**
“Keep in mind that save states also include the state of the memory card; carelessly loading an old save state will OVEWRITE the memory card, potentially resulting in lost saved games. **You can set the ‘Don’t overwrite SaveRAM on loading savestate’ option in RetroArch’s Saving settings to ON to prevent this.**”

I did exactly what that warning said and no it does prevent that.

### Steps to reproduce the bug

1. Set "Don't override SaveRAM on loading savestate" to **ON** in Main RetroArch Settings under _SAVING_
2. Load up any PSX game where you can easily quit to main menu in-game without having to reset via retroarch/core reset and set Beetle PSX / Beetle PSX HW core options “Memcard 0 method” to **mednafen** & "shared memcards" to **enabled**
3. Play a little til you can save someplace then save your game in Memory Card Slot 1.
4. Create a **savestate** to state _0_ near the save spot or any place you just saved in step 1.
5. Keep playing some more, or find somewhere else you can save that was different from where you did step 3 & 4. After you do, save your game again via Memory Card Slot 1, then create another savestate in state _1_ this time.
6. Do an in-game soft reset to test your saves and you'll see it changes depending on what savestate you  load. It says on the libretro docs that it shouldn't be doing that if your main RetroArch Saving Settings has "Don't override SaveRAM on loading savestate" set to ON. So why?

### Bisect Results

I started realizing this when I attempted to find a way to conver my PSP PSX save to a .mcr save recently, but since the only other result I found of this exact problem was posted a year ago by someone else, then it most likely started happening a year ago or before that.

### Version/Commit
Happens on both:
- RA Ver.: 1.7.3, Build date: May 4, 2018, Git version: b2ceb50897
- RA Ver.: 1.7.4, Build date: Sept. 5, 2018, Git version: c60fdf0

### Environment information

- OS: Windows 8.1 Pro 64-Bit

**Comment by fr500** [comment]
It can't work with memcard.method mednafen

**Comment by CsoiretgeFsM** [comment]
Yeah... just got confirmation via hunterk on discord. Sorry about all the hassle, I'll move on to the beetle psx repository and see if they can do anything about this. Thank you anyway.
