### ISSUE TITLE
Assets in media/

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/RetroArch#7340]
Hi!

I'm updating the debian packaging to 1.7.4, and I noticed that the tarball has media/assets/ now

Will all tarball from now on have extra files in media/ now? I'll update the packages, it'll be easier btw (well, if it does not change in the future)

I'm opening this issue for reference for others Linux packagers (and to not get stuff lost in IRC)

**Comment by fr500** [comment]
hey, I didn't know we had working tarballs, where are you getting those from lol

**Comment by orbea** [comment]
New tarballs should be uploaded now.

**Comment by fr500** [comment]
so what about this, I can make it build nightly tarballs and stable tarballs (it builds RA already)
I can make it clone everything is media as we do for other platforms and just tar the whole thing.

I think I offered to do this before.
Is that desirable at all?

**Comment by orbea** [comment]
The current script only makes tarballs for release tags in both `.tar.xz` and `.zip` (`.tar.gz` is too big here).

https://github.com/libretro/libretro-super/blob/master/retroarch-release.sh

They are then uploaded to the release page along with a SHA256SUMS.asc and SHA512SUMS.asc files signed using `gpg --clearsign`.

https://github.com/libretro/RetroArch/releases/tag/v1.7.5

The problem with nightly tarballs is that github only hosts them when associated with tagged releases and they would take up a lot of hard drive space quickly making them hard to host ourselves. Personally I wouldn't have much use for them when I can just clone myself.

This command should take care of the cloning  without much effort.
```
./libretro-fetch.sh retroarch
```

**Comment by orbea** [comment]
I think this should be fixed now, please let me know if I'm mistaken.
