### ISSUE TITLE
RetroAchievements issues with the new implementation

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7341]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch has been crashing with achievements enabled since... this weekend

### Expected behavior

Should work normally

### Actual behavior

Crashes right after logging in

### Steps to reproduce the bug

https://github.com/RetroAchievements/rcheevos/issues/3

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
Close content locks up on android AARCH64
https://github.com/RetroAchievements/rcheevos/issues/7

**Comment by twinaphex** [comment]
@leiradel These are pretty serious issues, I really hope you can fix them soon (as in either today or tomorrow), otherwise it would set back the release of 1.7.5 severely. If you can't fix it either today or tomorrow, I might have to go back to the old code for now.

**Comment by twinaphex** [comment]
Actually, let me just go ahead and do that - going back to the old code for 1.7.5. I will rename the new code as 'cheevos-new' or something, that way you can fix the bugs in it and we can consider it for a 1.7.6 release candidate.

**Comment by leiradel** [comment]
@twinaphex agreed, I'll fix those but it's better to leave the changes to 1.7.6.

**Comment by twinaphex** [comment]
Alright, with this commit, I hope that it uses the old cheevos again.

@fr500 @leiradel For development purposes, you should define HAVE_CHEEVOS and HAVE_NEW_CHEEVOS and then it would be able to use the new cheevos code.

**Comment by leiradel** [comment]
Isn't it possible to roll back the merge?

**Comment by twinaphex** [comment]
I think that would be counterproductive. At least this way, you can make a branch in the current RetroArch repo, and just continue on with your work with the new cheevos code. 

Only thing I want somebody to do now is to test if old cheevos work as expected again, and then at least we have a suitable 1.7.5 release candidate. This release has already suffered many setbacks so I just want to err on the safe side here.

**Comment by rzumer** [comment]
#7333 has nothing to do with `rcheevos`, so it should be safe to merge without the fixes needed for the new implementation.

It was tested already, but if you want to defer retesting and merging it, I don't mind as long as I don't have to rebase it again.

**Comment by twinaphex** [comment]
The release has been done now.

@leiradel Are you going to look into making the new code work now without the regressions that were pointed out before?

**Comment by leiradel** [comment]
It's not easy for me to debug Android builds, but I'll eventually look into it. Until then, the current implementation is 100% compatible and we have no rush in changing it, even taking into account the RetroAchievements roadmap.

**Comment by rzumer** [comment]
As noted by @Jamiras a crash occurs on the new implementation when trying to access an address that is not mapped.

> old cheevos just ignores the null pointer and assumes the value of the memory to be 0: https://github.com/libretro/RetroArch/blob/master/cheevos/var.c#L347-L351
> cheevos-new tries to read the null pointer and crashes: https://github.com/libretro/RetroArch/blob/master/cheevos-new/cheevos.c#L526-L535
> the switch statement should be wrapped in an `if (data) {` check

**Comment by meleu** [comment]
this issue can be closed.
