### ISSUE TITLE
[Request] Choose thumbnail type per system

### ISSUE THREAD

**Issue by lambolighting** [libretro/RetroArch#7351]
I would like to request an option to choose different thumbnail type (Boxarts, Title Screens, Screenshots) per system.
I noticed while setting up my RetroArch installation and while using Title Screens when i imported GameCube games the only title screen was for Mario Sunshine. I would like to be able to choose what type i want per system first of all due to inconsistencies that may come up like this and second of all due to customization options.

I believe it could work like having a global option as it is right now and then an override for each system if we want to.

**Comment by RobLoach** [comment]
Mario Sunshine is the only title screen we have:
https://github.com/libretro-thumbnails/Nintendo_-_GameCube/tree/master/Named_Titles

Having them change per-playlist to just make up for the lack of images seems silly. I recommend two things...

1. Add new titles over at https://github.com/libretro-thumbnails/Nintendo_-_GameCube 
2. Rename "Named_Boxarts" to "Named_Titles" in your thumbnails folder, and use those.
