### ISSUE TITLE
(BSD) Add assets to NetBSD package

### ISSUE THREAD

**Issue by ensra** [libretro/RetroArch#7353]

**Comment by bparker06** [comment]
We have never provided any .tar.xz files.

**Comment by ensra** [comment]
@bparker06 https://github.com/libretro/RetroArch/releases/download/v1.7.4/RetroArch-1.7.4.tar.xz

**Comment by RobLoach** [comment]
Get it through the official channels instead:
https://retroarch.com/?page=platforms

The GitHub releases are not guaranteed to have everything.

**Comment by ensra** [comment]
@RobLoach I was using the tar.xz release to package RetroArch for NetBSD.

My problem is that there's otherwise no tagged release of the RA assets. If there's no bundled release of source and assets, I have to get the assets from the Windows release, and that includes a lot of stuff in the download that honestly isn't useful for my purposes.

**Comment by Melon-Bread** [comment]
The assets can be found here
https://github.com/libretro/retroarch-assets

**Comment by ensra** [comment]
> Where's the NetBSD package put together? Would be great to fix that.

You mean this? https://github.com/NetBSD/pkgsrc/tree/trunk/emulators/retroarch

**Comment by orbea** [comment]
New tarballs should be uploaded now.

**Comment by orbea** [comment]
I think this should be fixed now, please let me know if I'm mistaken.
