### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [libretro/RetroArch#7354]
Will this be done, or can I submit a PR?

**Comment by orbea** [comment]
If you can submit a working PR that is probably the quickest way of seeing this implemented, thanks!

**Comment by ThatNerdyPikachu** [comment]
Sure thing!

**Comment by RobLoach** [comment]
Could live on docs.libretro.com :+1: https://github.com/libretro/docs/issues/154

Thanks a lot.
