### ISSUE TITLE
"Reset to Default Setting" Menu Feature

### ISSUE THREAD

**Issue by brianblakely** [libretro/RetroArch#7358]
## Description

Once a setting is changed, it is not possible (via the menu) to reset that setting to its default value if, perchance, you have forgotten it.

### Expected behavior

Some means to reset any setting to its default value.

### Version/Commit

- RetroArch: 1.7.5

### Environment information

- OS: Windows 10

**Comment by fr500** [comment]
Sure you can press start (or space)

**Comment by brianblakely** [comment]
Sorry

**Comment by brianblakely** [comment]
And thank you!
