### ISSUE TITLE
Gearboy not load/save states android

### ISSUE THREAD

**Issue by Mordehcai** [libretro/RetroArch#7362]
Save state not working in android version 1.7.5

Working in Windows 10 version 1.7.5 and retroarch x64 android

**Comment by Mordehcai** [comment]
I see that it has not worked since version 1.7.3
Works in nightly version

**Comment by fr500** [comment]
Core issue, please file into the correct repository

**Comment by RobLoach** [comment]
An issue might exist for this already tooooo https://github.com/drhelius/Gearboy/issues
