### ISSUE TITLE
Mame2000 - RetroArch: 1.7.5

### ISSUE THREAD

**Issue by Vanch70** [libretro/RetroArch#7364]
I suspect this maybe a development piece 

When I open a mame game that requires Mame2000 I hit R2 and am given a menu, however the "cheats" option is missing (not enabled).

It works fine with Mame2003 and Mame2003Plus just not with Mame2000 there is no configuration file into order to turn\enable cheat menu and suspect this is enbeded in the core. 

### Expected behavior

I expect to see a cheat menu option amongst other dip switch options etc..

### Actual behavior

Menu option appears dip switch, etc.. just no option for cheats.

Version

- RetroArch: 1.7.5

**Comment by fr500** [comment]
Core issue, please file into the correct repository
