### ISSUE TITLE
Loading Pac-Mania crashes Mame2003 core (at least on Switch)

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#7369]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Mame2003 crashes when loading Pac-Mania

### Expected behavior

Pac-Mania should load and run without crashing

### Actual behavior

Pac-Mania crashes with the Switch OS error screen when selecting to load it in the playlist

### Steps to reproduce the bug

1. Scan MAME roms (might not be needed)
2. Select Pac-Mania in Mame2003 game list
3. Select Run
4. Select Mame2003 core
5. Observe Switch OS crash screen (need to reboot) 

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.5 nightly from oct.1

### Environment information

- OS: Switch OS 5.1.0

**Comment by fr500** [comment]
First and foremost consider this:

    Only RetroArch bugs should be filed here. Not core bugs or game bugs
    This is not a forum or a help section, this is strictly developer oriented


Core issue, please file in the correct place...
