### ISSUE TITLE
(Switch) Failed to Load Content File until Restart Retroarch selected

### ISSUE THREAD

**Issue by adamnock** [libretro/RetroArch#7370]
## Description

When attempting to load ANY content file for the PCSX-Rearmed core the error 'Cannot load content file <file>' is displayed. 
Selecting the Restart Retroarch menu option first then selecting content loads the content correctly.

(I cannot test other similar cores as its the only one available, and I cannot say this is a core specific issue as the workaround is retroarch specific)

### Expected behavior

User should not have to restart retroarch immediately to be able to load content

### Actual behavior

Content fails to load until retroarch is restarted via menu option

### Steps to reproduce the bug

1. Install RetroArch on Switch as per standard instructions (this tested using build 826c77d)
2. Copy a valid bios to /retroarch/cores/system (scph5502.bin used)
3. Copy a valid PSX Content file (cue/bin and img tested) to a valid location on the SD (multiple locations tested)
4. Load retroarch. Attempt to load content. Observe error.
5. Select Restart Retroarch menu option. Load content. Working as intended.

Note: Tested against both Fat32 and exFAT on two SD cards to rule out SD issues.

### Version/Commit

- RetroArch: [826c77d]

### Environment information

- Switch via ReiNX. Confirmed using Atmosphere as well. Does not appear to be CFW related.

**Comment by m4xw** [comment]
This is a Core problem, https://github.com/libretro/pcsx_rearmed_switch/

**Comment by adamnock** [comment]
Was there any more info you can give on that statement I can pass on in a core issue?

So they don’t just point the finger back :)

**Comment by m4xw** [comment]
Well your bug isnt accurate to begin with because I can not reproduce such behaviour.
exfat?

**Comment by adamnock** [comment]
My bug has all the info I can give. No logs means I’m a little limited

And both filesystems, I put that in the report

**Comment by m4xw** [comment]
Use nxlink to get logs.
Also you seem to be the only one having this Issue. I didn't meet that problem in over a few thousand launches.
Check your setup

**Comment by adamnock** [comment]
Can you point me at the nxlink instructions.
I searched for switch logs and the official statement was there was none
available.

I get it’s not happening for some people. Bugs don’t have to affect
everyone you know? Also only a small number of users may report.

If the stance is this is a non issue that’s fine, close away

**Comment by m4xw** [comment]
Did you have core Info?
It sounds to me your pcsx core didn't get associated with the core infos, if that happens you need to load the core first before you start a game.
"Restart RetroArch" will start the last executed core.
Check /retroarch/info

**Comment by adamnock** [comment]
I’ll have a look, thanks :)

**Comment by m4xw** [comment]
So?

**Comment by adamnock** [comment]
So I’ve been on a business trip and landed back in Perth 10 minutes ago.
I’ll try it this weekend

**Comment by adamnock** [comment]
So for whatever reason, ive been unable to reproduce the issue again. Given it was happening prior to a trip away and wasnt immediately after with no changes....im stumped. 

Phase of the moon maybe?
