### ISSUE TITLE
[Wii U] Broken XMB Icons in 1.7.5 Stable

### ISSUE THREAD

**Issue by emkultra64** [libretro/RetroArch#7380]
XMB icons do not load correctly in 1.7.5 on Wii U. Instead, a font bitmap loads in place of the icons.
See image below. 
![img_20181007_190113](https://user-images.githubusercontent.com/22283068/46588064-fcffdd80-ca63-11e8-8551-d3926330eae8.jpg)

**Comment by SBanya** [comment]
I have this same issue, and downloading assets through "Online Updater" did not work either.

What bothers me more is that I placed roms in a folder:

SD root -> retroarch -> roms

I then scanned the directory, and none of the roms were placed into specific system directories, i.e., the Super Nintendo roms I placed in that directory to test didn't show up in a Super Nintendo specific directory in Retroarch.

This should work on the normal version of Retroarch, so I'm wondering if this is a bug with the recent nightly release for the Wii U version of Retroarch.

**Comment by dmooney** [comment]
Uncompressing the downloaded assets worked for me.

Workaround:

1. Update assets
2. Take the SD card and use a computer to unzip assets.zip in the media directory. Delete assets.zip.
3. Return the SD card to the Wii U and restart retroarch.

**Comment by RobLoach** [comment]
Is the assets bundle too large for RA/WiiU to handle?

**Comment by fr500** [comment]
Kinda, the whole downloader is broken in 32bit, it always loops and
restarts, sometimes it works, sometimes it doesn't
on WiiU it's just... more broken.

**Comment by pmdci** [comment]
Can we download the assets.zip manually from somewhere?

**Comment by RobLoach** [comment]
> https://github.com/libretro/retroarch-assets

The Download button at the top right. You can also git clone it to where your assets directory is set too...

```
rm -rf ~/.config/retroarch/assets
git clone ~/.config/retroarch/assets
```

**Comment by realoliver9912** [comment]
Put it into ./retroarch/media instead of those two. I tryed one of those and after doing it in media it worked for me

**Comment by HarveyB02** [comment]
For anyone stuck on this still, I extracted the contents of the zip to ./retroarch/media/assets and changed the assets directory to that path within retroarch and it's working perfectly
