### ISSUE TITLE
(Switch) Split Joy-Con Bug in Switch Version

### ISSUE THREAD

**Issue by zacly** [libretro/RetroArch#7384]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Every time a rom is loaded or upon exit the split Joy-con settings revert to off. Even if the config setting is saved, This feature was working perfectly in retroNX. All you had to do was disconnect the joycon from the system and RetroNX would automatically set the controls to split-joycon.

### Expected behavior

Have split joycon controls active once you pull the joycon off the system (if settings are set to on). Also save the split joycon settings upon exit, 

### Actual behavior

Every time a rom is loaded or upon exit the split Joy-con settings revert to off. Only way around this is to go to the menu/options once a Rom is loaded and activate from there.

### Steps to reproduce the bug

Set your split joycon to on, start a game or exit. You will see the settings don't take effect.

### Bisect Results

since release

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

Latest (switch)

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by m4xw** [comment]
Its not a bug. Its a design choice we made.
We will make it save tho, as it doesn't play well with salamander.

**Comment by zacly** [comment]
Yes sorry. We were talking in the forums. You told me you were going to make it save. I made that post before we had chatted.

Thanks for doing that by the way.

Keep up the awesome work buddy!

Zac



Sent from myMail for iOS


Tuesday, October 9, 2018, 8:32 PM -0400 from notifications@github.com <notifications@github.com>:

Its not a bug. Its a design choice we made.
We will make it save tho, as it doesn't play well with salamander.

**Comment by zacly** [comment]
Works great. The only thing is when you boot up retroarch the joy con setting states that they are set to off. Once I boot up a game (any system) the setting is set to on. It's perfectly fine to me since I wanted saved to on at all times, but I could see people getting confused. If that's how you guys intended to have it then it is all good. Thanks for making this change. I even have hot keyed the menu to the left thumbstick so I can get back into the menu while in split mode. Love it!

**Comment by m4xw** [comment]
Thats probably because you don't have a updated loader.

**Comment by zacly** [comment]
So update the nsp?



Sent from myMail for iOS


Friday, October 19, 2018, 9:28 PM -0400 from notifications@github.com <notifications@github.com>:

Thats probably because you don't have a updated loader.

**Comment by m4xw** [comment]
Make sure u unistall the NSP before installing the update.
If you dont use the NSP u need to grab the /switch nro from the nightly package

**Comment by zacly** [comment]
Will do! Thanks man



Sent from myMail for iOS


Friday, October 19, 2018, 9:33 PM -0400 from notifications@github.com <notifications@github.com>:

Make sure u unistall the NSP before installing the update.
If you dont use the NSP u need to grab the /switch nro from the nightly package
