### ISSUE TITLE
Rumble in linux/udev cuts off 60 seconds after launching RA

### ISSUE THREAD

**Issue by Shoegzer** [libretro/RetroArch#7426]
As @mickski56 discovered while fixing [this](https://github.com/libretro/RetroArch/issues/6920) issue, there are issues with rumble.  Specifically, rumble cuts off exactly 60 seconds after launching RA (I've clocked it).  This can be fixed in one of three ways:

1. Editing retroarch.cfg and setting the following:

`video_context_driver = "sdl_gl"`

This has one major side-effect: the dolphin core crashes for some reason.  (**update May 13 2019**: RetroArch now fails to start if the video driver is "gl" with this option.  It will start if the video driver is "vulkan" but then the above solution doesn't work)

2. Changing the video driver from “gl” to “sdl2”.  This is suboptimal because some cores such as mupen64plus need gl.

3. Running RA as root.  This is suboptimal of course because RA should never be run as root

I'm not sure why these fixes work, but they do.  Clearly though, this should not happen.  A long time ago enygmata indicated to me that it could be a bug in the glx backend.

Other details about the test system:

* Using "sdl2" as the input driver, and "udev" as the joypad driver (when I set the former to "udev" I can't navigate menus at all for some reason - probably a separate issue). 

* Linux Mint 19.1, kernel 4.18 and Nvidia GTX 1070 at nvidia-driver-390.  Using a DS4 pad, but I've also encountered this issue with an XB360 pad years ago.

**Comment by orbea** [comment]
I have.
```
video_context_driver = ""
```
And rumble works well here with my dualshock 3 gamepad and udev.

With SDL2 it seems I lose rumble when toggling the menu.

**Comment by Shoegzer** [comment]
Thanks, @orbea. I'm not entirely sure why it doesn't work after 60 seconds.  I've updated the summary with a few more details in case they help.

That said, the fact @mickski56 and you are also seeing similar rumble issues such as loss in sdl2 when toggling menus are further indications not all is well with the rumble code.  Hope we can get this nailed down as it's fairly important, and I'm happy to test any attempts to fix.

**Comment by orbea** [comment]
Your issues with udev could be upstream kernel driver issues, I had a lot of issues when I used rumble with xpad which vanished when I stopped using xpad.

As for SDL2, I think its just an immature input driver. I have no such issues with other SDL2 programs.

**Comment by Shoegzer** [comment]
Hmm, not sure about that.  Rumble works without any issues on all other emulators/games running on that system.  That includes Dolphin standalone.  It's got to be something with RA somewhere.

**Comment by Shoegzer** [comment]
Just checking in on this one and I've updated the issue summary as the best solution is no longer valid - RA must now either be run as root or using the SDL2 video driver.  This is of course a major issue for anyone who uses rumble with linux (I'm guessing Ubuntu variants).

@twinaphex any chance you could take a look at this one, or do you know of anyone who might be willing to work with me to help get this long-standing issue fixed?

**Comment by Shoegzer** [comment]
**Update:** I just discovered the source of the problem: Going into Video > Suspend Screensaver and turning this to "Off" permits rumble to continue indefinitely.  But why would this be the case?

**Comment by orbea** [comment]
> I just discovered the source of the problem: Going into Video > Suspend Screensaver and turning this to "Off" permits rumble to continue indefinitely. But why would this be the case?

Interesting, I certainly have never experienced this in linux...I'm at a loss why not being root or suspend screensaver would cause issues.

Can you try recompiling with `--enable-dbus`? I suspect you are running into an OS issue which only happens with some distro configurations.

**Comment by Shoegzer** [comment]
Interesting - thanks @orbea!  So to test, I compiled with` --enable-dbus`, turned back on "Suspend Screensaver", and tested rumble again.  Sure enough, that works too - rumble continues after 60 seconds.

Normally I use the buildbot script to compile RA for this test platform, which again is Linux Mint 19.1 Cinnamon (Debian/Ubuntu downstream).  So I imagine anyone with those distros would run into this issue.  

Questions:

- Is there any specific reason enabling the dbus fixes the issue?

- Shouldn't `--enable-dbus` be the default configuration with the buildbot RA script?  Are there any real downsides to using the unified software bus?  
 
- In the event the default configuration cannot/should not be changed, which would you suppose is the better route - compiling RA without dbus support and turning "Suspend Screensaver" off, or compiling with dbus support and leaving it on?

**Comment by orbea** [comment]
> Is there any specific reason enabling the dbus fixes the issue?

I'm not sure, its using a different code path for screen suspension than `xdg-screensaver`. What DE or wm are you using? What gamepad? (What kernel driver?) I suspect the `xdg-screensaver` support in your OS is buggy... You may want to investigate why its not working correctly in your distro as this seems to be the root cause.

> Shouldn't --enable-dbus be the default configuration with the buildbot RA script? Are there any real downsides to using the unified software bus?

It used to be, but it turns out it works for some people and doesn't for others. You are one of the former and I am one of the latter...unfortunately the people were involved in added dbus support haven't done much to help figure out these issues and it ended up disabled by default. I also think there are split opinions on if using dbus with RetroArch is a good idea or not.

> I compiled using the buildbot script by changing libretro-buildbot-recipe.sh, modifying the configure line to read: ${CONFIGURE} ${ARGS} --enable-dbus, and then running ./libretro-buildbot-recipe.sh recipes/linux/retroarch-linux-x64. Is there a better/easier way to modify the buildbot script's compile-time options?

I can't answer that, I personally use my own build-scripts with the options I want or build by hand from the git repo (Mostly while testing).

**Comment by Shoegzer** [comment]
> I'm not sure, its using a different code path for screen suspension than xdg-screensaver. What DE or wm are you using? What gamepad? (What kernel driver?) I suspect the xdg-screensaver support in your OS is buggy... You may want to investigate why its not working correctly in your distro as this seems to be the root cause.

Again using Linux Mint 19.1 x64 as the DE with Cinnamon WM.  Gamepad is the Sony DS4 with kernel driver, under kernel 4.18.0-18-generic.

Also I'm using xdg-screensaver as part of xdg-utils, which has the installed version of 1.1.2-1ubuntu2.3.

Again since this seems to be a Ubuntu issue, this issue should be quite widespread/observed by many RA users running linux with rumble and just not reported.

> It used to be, but it turns out it works for some people and doesn't for others. You are one of the former and I am one of the latter...unfortunately the people who were involved in added dbus support haven't done much to help figure out these issues and it ended up disabled by default. I also think there are split opinions on if using dbus with RetroArch is a good idea or not.

Do you recall what didn't work for you?  Mine seems to work for rumble, but then I wonder if I'd encounter the same issues you've seen in other areas.  Quite a shame the issues could never be resolved.

> I can't answer that, I personally use my own build-scripts with the options I want or build by hand from the git repo (Mostly while testing).

I gotcha.  From the ${ARGS} in that line, shouldn't the .sh script expect arguments passed from the commandline?  It would be much easier to pass arguments that way than manually adding them to the .sh script itself.  However, when I try `./libretro-buildbot-recipe.sh recipes/linux/retroarch-linux-x64 --enable-dbus` this doesn't work.

**Comment by orbea** [comment]
> Do you recall what didn't work for you? Mine seems to work for rumble, but then I wonder if I'd encounter the same issues you've seen in other areas. Quite a shame the issues could never be resolved.

The dbus integration just failed to disable the screensaver.

> Again since this seems to be a Ubuntu issue, this issue should be quite widespread/observed by many RA users running linux with rumble and just not reported.

Perhaps, it might be specific to certain software versions and configurations. The choices for you are to use dbus or we try to figure out what about your system doesn't work and fix it. We could also consider enabling dbus by default again, but last time I asked this in another issue report somewhere no one replied. The default can be changed in `qb/config.params.sh` by setting the dbus line from `no` to `auto`. Please help get more opinions if you want to investigate this route.

> However, when I try ./libretro-buildbot-recipe.sh recipes/linux/retroarch-linux-x64 --enable-dbus this doesn't work.

Honestly that script is not really setup for this and it may be the wrong tool for the job, but I can't suggest a better one off hand. Improving/adding scripts for users to build different parts of the project is probably worth doing.

**Comment by Shoegzer** [comment]
> The dbus integration just failed to disable the screensaver.

Ah, you said "these issues" above so I figured it was more than just one issue.  Got it now.

> Please help get more opinions if you want to investigate this route.

@twinaphex @hunterk @bparker06 can you help us with any thoughts you may have here, and/or feel free to bring in anyone else who might help?

> Honestly that script is not really setup for this and it may be the wrong tool for the job, but I can't suggest a better one off hand. Improving/adding scripts for users to build different parts of the project is probably worth doing.

Yeah, I had thought what I tried should have worked given that it seemed like correct syntax but maybe it's just the .sh script itself not reading my ARGS from commandline properly.  Very odd, it should have worked.

**Comment by Shoegzer** [comment]
After testing with more recent RA builds and an updated distro, I've discovered the above issue no longer occurs - i.e. rumble continues regardless of video driver setting and whether screensaver is disabled.  RA was compiled from the buildbot script which still does not appear to specify `--enable-dbus`, so that shouldn't have made a difference here.  So, this issue should be resolved.  Closing.
