### ISSUE TITLE
(DB) Detect Dolphin .gcz files

### ISSUE THREAD

**Issue by Gooberpatrol66** [libretro/RetroArch#7428]
### Expected behavior
[What you expected to happen]
.gcz files should be added to the library, as dolphin is able to play them

### Actual behavior
[What is actually happening]
.gcz files are not added to the library

### Steps to reproduce the bug
load content > collections > scan directory

### Version/Commit
You can find this information under Information/System Information
- RetroArch: [version/commit]
1.6.7

### Environment information
- OS: [The operating system you're running]
gentoo
- Compiler: [In case you are running local builds]
gcc-7.3.0

**Comment by Sanaki** [comment]
Confirmed still valid on 1.7.8 using a gcz generated by the Dolphin standalone emulator. This complicates matters for me, since I was in the process of ripping all my GC games and expected to be able to limit the amount of space consumed by them.

**Comment by RobLoach** [comment]
Do you know of a publicly available database of .gcz files? Similar to redump.org ?

**Comment by Sanaki** [comment]
While I don't personally, I'm not sure that would help with this particular case. Assuming I understand correctly, it matches GC and Wii based on filename (seemingly hardcoded to .iso). There's no CRC32 or other checksum involved. It lists serial, but I'm not actually sure it checks that currently. Presumably just fixing the serial check would solve the problem if that's the case, assuming that's viable. That would bring it in line with how other formats, such as Playstation disc images, are handled.

**Comment by xTMODx** [comment]
@RobLoach here are the custom DATs for gcz and others https://dats.site/custom_system_datslist.php

**Comment by RobLoach** [comment]
Unsure scanning within archives works, but am interested in this.

**Comment by Sanaki** [comment]
Hmm... none of mine match that nkit gcz dat.

**Comment by RobLoach** [comment]
Don't think that `.gcz` files would kick the serial detection.

**Comment by xTMODx** [comment]
@Sanaki i think those were created from redump sources.

**Comment by Sanaki** [comment]
I'll have to look into it when I have more time. As I understand it, nkit has different options available in compression that may alter the final result. Mine are nkit scrubbed and then converted to gcz using dolphin standalone.
