### ISSUE TITLE
[Feature Request] Word-wrap/scroll method for CJK languages

### ISSUE THREAD

**Issue by waitingmoon** [libretro/RetroArch#7439]
by current design, the sentences for sublabel behind a space will be automatically/forcibly placed in new line if it has over 50 letters. The design has a problem in specific-language, such as chinese, japanese, korean, especially japanese - non-spaced language.

![overflowed](https://user-images.githubusercontent.com/16256443/46925853-31c5f300-d069-11e8-94db-a5553da5e8c5.png)

its a image how displaying a long-string on glui. you can see some letters overflowed from viewport. you can't even see it. also, I wonder why auto-clipping/scrolling for main lavel is disabled in multi-byte language. to resolve overlapping is important too.

![wasteofthescreen](https://user-images.githubusercontent.com/16256443/46926024-f11aa980-d069-11e8-8840-bfbf32e7ffeb.png)

I manually insert a new line code to resolve it, but this method will cause another problem. as you can see a image above, it causes that its waste of viewport area when rotate a device (landscape mode). 

no problem on english:
![wasteofthescreen2](https://user-images.githubusercontent.com/16256443/46926159-96358200-d06a-11e8-9f76-b08e796b85c9.png)

is it possible to change word-wrap method by language?

Thanks

**Comment by bparker06** [comment]
The problem is that the `word_wrap()` function modifies the existing string to replace spaces with a newline, but when a string doesn't have any spaces, it cannot do that. Modifying it to work that way would be extremely difficult and require changes to all the places that use that function too.

The easiest solution for now would be to insert (half-width) spaces after any punctuation mark like periods and commas, and then the wrapping should work like it does for English. As long as there is at least one space in a string, it will replace it with a newline if the text is too long.

Is this an acceptable solution for now?

**Comment by toshixm** [comment]
@waitingmoon I have fixed the issue at #12445.
Could you confirm it if you can try to built from git or to use nightly build?

**Comment by waitingmoon** [comment]
Git Version: e40f0d3

![retroarchcjkinput](https://user-images.githubusercontent.com/16256443/120900736-6dc28200-c671-11eb-95b9-a3bbfced7b6a.jpg)
![retroarchcjkinput2](https://user-images.githubusercontent.com/16256443/120900737-6f8c4580-c671-11eb-8fab-1652b6569c66.jpg)
![retroarchcjkinput3](https://user-images.githubusercontent.com/16256443/120900847-356f7380-c672-11eb-8c43-3b0f3f1806c8.jpg)

I'm not sure what the current specifications because I haven't touched RetroArch for a long time.  What I can confirm is that the word wrap seem to work correctly in xmb and glui, but not in ozone.

**Comment by toshixm** [comment]
@waitingmoon Thank you for reporting.
As for the behavior when using ozone, I think you changed the language from English to Japanese and took the screenshot without restarting RetroArch.
It is need to restart RetroArch after changing language at the present implementation. (I apoligize that it is undocumented now)
Could you confirm whether my guess is right?

**Comment by waitingmoon** [comment]
Ah, That's exactly right. The word wrap works perfectly after restart!

**Comment by toshixm** [comment]
Thank you. Could you closed the issue if there are not any other problems?
