### ISSUE TITLE
[Switch] [Minor] Default Main Menu Key-Combo Causes Help Menu Description to Popup

### ISSUE THREAD

**Issue by jordansinn1994** [libretro/RetroArch#7450]
## Description

Device: Nintendo Switch

Help menu entry is displayed when trying to access retroarch main menu from in game using default of holding start and select.

### Expected behavior

Hold start and select for retroarch main menu to open.

### Actual behavior

Menu opens but a help popup, usually "No information is availible.", comes up because it's bound to the select and there doesn't seem to be a way to change or disable this.

### Steps to reproduce the bug

1. Launch game
2. Hold - and +.
3. Forced to press A or B button to get rid of the help description popup.

**Comment by m4xw** [comment]
I guess this only happens if u keep holding them? (its the behaviour of pressing "+" again IIRC)
