### ISSUE TITLE
net_http with SSL seems broken

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7451]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

SSL enabled downloads are no longer working

Given this code:

```C
static void test()
{
   static char url[PATH_MAX_LENGTH];
   static char url_encoded[PATH_MAX_LENGTH];

   snprintf(url, sizeof(url), "https://bot.libretro.com/assets/frontend/bundle/assets/xmb/pixel/png/clock.png");
   net_http_urlencode_full(url_encoded, url, sizeof(url_encoded));

   file_transfer_t *transf = NULL;
   transf           = (file_transfer_t*)calloc(1, sizeof(*transf));
   transf->enum_idx = MENU_ENUM_LABEL_CB_TEST_ENUM;
   strlcpy(transf->path, request->avatar, sizeof(transf->path));

   task_push_http_transfer(url_encoded, true, NULL, cb_generic_download, transf);
}
```

It fails with Download Failed.
It used to work before.

If I replace the url with http then it works normally.

### Expected behavior

It should work, it's required for any kind of service integration

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Windows 10 x64
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
Or you can simply change the buildbot url to https and test

**Comment by fr500** [comment]
Seems to work on linux

**Comment by ofry** [comment]
Found some clues...

https://github.com/libretro/RetroArch/blob/master/libretro-common/net/net_socket_ssl.c

There's NOT checking presence of openssl library...

**Comment by bparker06** [comment]
That's because it doesn't use openssl.

**Comment by ofry** [comment]
Found bit more clues... In file https://github.com/libretro/RetroArch/blob/master/libretro-common/net/net_http.c

function net_http_new()

Second (!) call of function net_http_send_str() gives error... First call was fine.
