### ISSUE TITLE
[Menu] Dropdown lists resets position when going back

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#7456]
## Description

When opening a dropdown list and going back, the cursor is reset to the first position.

### Steps to reproduce the bug

0. Use XMB (or Ozone :D)
1. Go to Settings > Driver > Video Driver
2. Go back to Driver
3. Notice that the cursor is now on Input Driver while it should have stayed on Video Driver

**Comment by orbea** [comment]
Related issue to https://github.com/libretro/RetroArch/issues/2506.

**Comment by orbea** [comment]
I bisected this and found it started when the feature was introduced.
```
1f864e379bc0e70693fab760f7e16f65291358c0 is the first bad commit
commit 1f864e379bc0e70693fab760f7e16f65291358c0
Author: twinaphex <libretro@gmail.com>
Date:   Sun Sep 23 17:13:45 2018 +0200

    Add dropdown lists for driver settings

:040000 040000 6ca8803c58395abc096431bbb5d66f11b2fe6575 84ad5d62a4d39b62cc8c38029d6f0811c865698f M	menu
```
1f864e379bc0e70693fab760f7e16f65291358c0

**Comment by sonninnos** [comment]
Pretty sure this hasn't been an issue for a long time.

**Comment by gouchi** [comment]
@natinusala This issue should be closed ;)
