### ISSUE TITLE
Battle Hunter (PSX) freezes Retroarch (PCSXReArmed)

### ISSUE THREAD

**Issue by OTFree** [libretro/RetroArch#7465]
Hello! Running RetroArch 1.7.5 on my Switch (via SXOS + NSP), and am VERY surprised at how well most PSX games run already! However, I tried running "Battle Hunter (US)", only for the game to consistently freeze Retroarch once I press start at the title screen. 

I tried running the game with and without threaded video, but no difference. I have several PSX bios in my core/system folder, but it still results in a crash. The button combination I have set ('+' and '-' to pause) becomes unresponsive upon pressing start at the title screen.

The only way to quit Retroarch is to use the home button and close the application manually. I've yet to see this happen with any other game or core I've tried, and I checked, the ISO/BIN I'm using isn't bad.

Thanks for your help!

**Comment by m4xw** [comment]
First of all, please don't report SX OS Issues.
We can not debug Issues in a Blackbox.
Don't post Core bugs here. This is only for RetroArch bugs.
Also I bet its 5+ bins?

**Comment by m4xw** [comment]
@twinaphex Can we close this?

**Comment by orbea** [comment]
@m4xw I don't understand, why should this issue be closed? Please note I don't have a switch so I am rather uninformed on the subject.

**Comment by m4xw** [comment]
@orbea He used a unsupported firmware that is prone to constantly have Issues.
Then it's also a 5-bin Game, https://github.com/libretro/pcsx_rearmed_switch/issues/1
Also this is a core Issue and should not be on the RA Issue tracker, we have a Switch Meta Issue for these.

**Comment by orbea** [comment]
Okay, thanks for the quick explanation! I'm going to close this in favor of https://github.com/libretro/pcsx_rearmed/issues/199 which I understand to be the meta issue?

**Comment by m4xw** [comment]
@orbea Actually it's this one https://github.com/libretro/RetroArch/issues/7360
