### ISSUE TITLE
Suggest Mednafen NeoPop create a folder in save directory.

### ISSUE THREAD

**Issue by leoxxx** [libretro/RetroArch#7481]
ATT.
http://buildbot.libretro.com/nightly/android/latest/armeabi-v7a/mednafen_ngp_libretro_android.so.zip
Use this core.
The .ngf file  can be used with NGP.EMU. It also can be used with NeoPop-Win32.

**Comment by fr500** [comment]
What is a ngf file?

**Comment by leoxxx** [comment]
It's the NGP save file.

**Comment by leoxxx** [comment]
It create a .flash file.
.flash = .ngf.
So rename .ngf to .flash.

**Comment by orbea** [comment]
@leoxxx This is the wrong issue tracker, please make an issue in the correct issue tracker here.

https://github.com/libretro/beetle-ngp-libretro/issues

Thanks!
