### ISSUE TITLE
Suggestion: Use USE_* instead of HAVE_NO_*

### ISSUE THREAD

**Issue by noisybe** [libretro/RetroArch#7482]
Using USE_* instead of HAVE_NO_* to explain a feature that was intentionally enabled/disabled is more intuitive.

Right now config.h defined HAVE_* and HAVE_NO_* which is like defining 0, 1, !0, !1 when taking #ifdef and #ifndef into regard.

bparker06 was so kind to clarify what HAVE_NO_* actually is supposed to mean which would have been obvious if USE_* had been used.

**Comment by orbea** [comment]
This is a duplicate of https://github.com/libretro/RetroArch/issues/7479.

I am going to defer to @bparker06 with this.
