### ISSUE TITLE
[Switch, Buildbot] Add nightly retroarch.nsp files to buildbot

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#7484]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

As far as I know, the official Retroarch.nsp file is only available for stable versions, so it is outdated compared to the code in Retroarch.nro that is found in nightly builds.

### Expected behavior

A nightly build of Retroarch.nsp should be made available, maybe inside the Buildbot .7z archives.

- OS: Switch

**Comment by m4xw** [comment]
This is not right. In fact the NSP is based on a Nightly build, not a stable.
I currently update it whenever it's needed.
It's only the loader and has no functionality other than loading NRO's.
This only becomes a Issue if it changes with the cfg's.
Tho I agree we should add it to the bot later on, that was what I was planning anyway.

**Comment by rsn8887** [comment]
Ah thanks for the clarification. I thought it had the Retroarch executable code. If it is really just a loader, then it is not so pressing.

**Comment by m4xw** [comment]
The loader _itself_ is embedded, but any core is basically a functional retroarch build by itself thats loaded going on from there.

**Comment by capitaineflam25** [comment]
Having the possibility to update the loader (with a nightly NSP) or a manual operation would be interesting.

I'm facing a playlist issue that has been fixed with recent nighlties, the only way to get the fix is to manually load a nightly core after startup, or launch the retroarch NRO as a homebrew.
