### ISSUE TITLE
[libnx] Hang when switching ozone theme with threaded video

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#7498]
Calling `ozone_reset_theme_textures` outside of context reset with threaded video hangs the homebrew. `menu_display_reset_textures_list` is called but never returns. 

It prevents switching theme on the fly when threaded video is enabled.

**Comment by fr500** [comment]
I just had a similar issue, I was calling context_reset within xmb.c 
had to scrap the changes here

**Comment by twinaphex** [comment]
Is this still an issue or can it be closed?

**Comment by natinusala** [comment]
We have a workaround, that's good enough for now
