### ISSUE TITLE
Timezone incorrect on switch

### ISSUE THREAD

**Issue by fennectech** [libretro/RetroArch#7503]
On switch  we dont use the users current timezone but UTC As such for anyone not on UTC the time is incorrect.

**Comment by m4xw** [comment]
You should update your build.

**Comment by m4xw** [comment]
This can be closed.

**Comment by p-sam** [comment]
duplicate of #7391

**Comment by fennectech** [comment]
How do i update my build?

**Comment by fennectech** [comment]
Never mind.
