### ISSUE TITLE
RetroArch cannot write to a SD Card in Android 8 (Oreo)

### ISSUE THREAD

**Issue by vpontin** [libretro/RetroArch#7510]
Seems like RetroArch still cannot write anything on external storage on Android Oreo. I dont know if not working around this restriction is intended, but several other Android apps circumvent this by showing the OS open dialog and requesting users to select the root of the SD Card.

This is what i'm talking about (screenshot from Android 5.0 but seems like its still the way apps are doing on 8.0, [source](https://www.photosync-app.com/support/android/android/how-to-use-the-external-sd-card-on-android-5-0-or-higher.html)):

![image](https://user-images.githubusercontent.com/3485505/47702198-f693fa00-dbfa-11e8-8ce7-38b99ee965f0.png)
![image](https://user-images.githubusercontent.com/3485505/47702205-f8f65400-dbfa-11e8-813b-26c7c488534d.png)

Is there any chance of seeing this feature possible in future? It would be a relief for low-internal storage users.

**Comment by zerojay** [comment]
Ironically, while the same dialog box is popped up on the Nvidia Shield, there appears to be no way to actually select the SD card root in the UI short of hooking up a mouse.

**Comment by bparker06** [comment]
I think there is currently no intention of adding support for the Storage Access Framework which you're referring to, because it would require that 1. all I/O be funneled through JNI and done via Java, and 2. that cores cannot do their own I/O, which a lot of them do. Unfortunately the Android NDK does not support SAF, only via Java to my knowledge.

**Comment by vpontin** [comment]
Sad. A lot of mobile users (at least in my country) have issues due to low internal space available in their devices.

I know ROM reading is fine, but placing the configs/saves etc on SD Card would be essential not only for this questions but also to facilitate kind of portability of settings/saves between devices.

**Comment by vpontin** [comment]
Yeah, lack of support for adoptable storage is infuriating as well. Only a shady chinese phone i've imported for a relative support it. The all other domestic devices i had doesnt have any way to do that.

Anyway closing since it seems not to be libretro team fault. Sorry.
