### ISSUE TITLE
[Core request] DOSBox DYNAREC version (Switch)

### ISSUE THREAD

**Issue by dotmick** [libretro/RetroArch#7515]
## Description

I would like to suggest the addition of a new core for DOSBox based on the DYNAREC version https://github.com/fr500/dosbox-svn/tree/libretro by @fr500 

### Expected behavior

Improved performances

### Actual behavior

DOSBox runs pretty well but some games are still a bit slow.

### Version/Commit

- RetroArch: 1.7.5 (NSP version)

### Environment information

- OS: any CFW

Thanks! 🙏

**Comment by m4xw** [comment]
This was attempted before by @lifajucejo but he encountered some Issues.

**Comment by fr500** [comment]
You'd need sdl1.2 support.
An easier bet would be to backport the AARCH64 emitter to tenood dosbox
core.

**Comment by dotmick** [comment]
I've seen there's a port of SDL1.2 for Switch but might not be final. Or porting DOSBox to SDL2.0?

(I'm not familiar with the AARCH64 emitter)

**Comment by i30817** [comment]
Dosbox has a sdl2 patch

**Comment by fr500** [comment]
It's not upstream nor trivial to rebase

**Comment by i30817** [comment]
Just for the record: https://www.vogons.org/viewtopic.php?f=41&t=34770&start=120

**Comment by fr500** [comment]
I am keeping my core (https://github.com/fr500/dosbox-svn) in lockstep with upstream.
Whatever anyone else wants to do in their fork is fine but I'm not changing mine. I'm not introducing random non properly versioned patches.

I was able to help @dotmick to build it but it doesn't work on switch. The dynarec crashes the whole thing and without dynarec it gets no input. Maybe it doesn't like the threads implementation on switch or something. Sadly that's not something I can fix.

**Comment by fr500** [comment]
@dotmick I didn't keep up, care to show the diff of the changes we made?

**Comment by dotmick** [comment]
Sure!

```diff
diff --git a/libretro/Makefile.common b/libretro/Makefile.common
index 6f71e933..e87ed536 100644
--- a/libretro/Makefile.common
+++ b/libretro/Makefile.common
@@ -10,7 +10,8 @@ INCFLAGS += \
        -I$(CORE_DIR)/libretro \
        -I$(LIBRETRO_COMM_DIR)/include \
        -I$(CORE_DIR)/include \
-       -I$(CORE_DIR)/src/midi/munt
+       -I$(CORE_DIR)/src/midi/munt \
+       -I/opt/devkitpro/portlibs/switch/include/

 # common files
 SOURCES_CXX := \
diff --git a/libretro/Makefile.libretro b/libretro/Makefile.libretro
index 7c038fcc..db3521e6 100644
--- a/libretro/Makefile.libretro
+++ b/libretro/Makefile.libretro
@@ -165,7 +165,7 @@ else ifeq ($(platform), libnx)
        CXXFLAGS := $(ASFLAGS) $(CFLAGS) -std=gnu++11
        CFLAGS += -std=gnu11
        LDFLAGS += `sdl-config --static-libs` -lSDL_net
-       WITH_DYNAREC = arm64
+       WITH_DYNAREC =
        STATIC_LINKING = 1
 else ifeq ($(platform), emscripten)
        TARGET := $(TARGET_NAME)_libretro_$(platform).bc
diff --git a/src/dos/cdrom_image.cpp b/src/dos/cdrom_image.cpp
index 0e81a83d..d6076ff4 100644
--- a/src/dos/cdrom_image.cpp
+++ b/src/dos/cdrom_image.cpp
@@ -421,8 +421,8 @@ bool CDROM_Interface_Image::CanReadPVD(TrackFile *file, int sectorSize, bool mod
                        (pvd[8] == 1 && !strncmp((char*)(&pvd[9]), "CDROM", 5) && pvd[14] == 1));
 }

-#if defined(WIN32)
-static string dirname(char * file) {
+#if defined(WIN32) || defined(__SWITCH__)
+static string FAKEdirname(char * file) {
        char * sep = strrchr(file, '\\');
        if (sep == NULL)
                sep = strrchr(file, '/');
@@ -435,6 +435,7 @@ static string dirname(char * file) {
                return tmp;
        }
 }
+#define dirname FAKEdirname
 #endif

 bool CDROM_Interface_Image::LoadCueSheet(char *cuefile)
diff --git a/src/ints/bios.cpp b/src/ints/bios.cpp
index cd3e5622..fb1ff754 100644
--- a/src/ints/bios.cpp
+++ b/src/ints/bios.cpp
```

**Comment by fr500** [comment]
Ok, I'll backport the changes

**Comment by m4xw** [comment]
@fr500 It wouldnt work like on unix.
https://github.com/switchbrew/libnx/blob/master/nx/source/kernel/jit.c

**Comment by dotmick** [comment]
Is this what you've mentioned the other day @natinusala ?

**Comment by natinusala** [comment]
Absolutely :) It will continue to crash due to the same error (PC in non executable region) until you use this

**Comment by dotmick** [comment]
I thought so :) I'd love to do it but this is beyond my knowledge I'm afraid. If someone can pick that up, perhaps?

It feels that with a "_few_" modifications we could have the core running in RA.

**Comment by fr500** [comment]
@m4xw I know, I only made it build, but I don't know how to fix the dynarec

**Comment by natinusala** [comment]
I will repeat what I said on Discord the other day for others to see

We need to find where are the dynarec blocks allocated in the core and replace this allocation with a libnx JIT block allocation.

We might then need to translate the block to writable, write to it then translate it back to executable before continuing (this apparently isn't needed for 4.0.0-4.1.0 but is needed for 5.0+).

**Comment by dotmick** [comment]
I had a look at the JIT example: https://github.com/switchbrew/switch-examples/blob/master/jit/source/main.c

So far I think I understand how it works (not sure about what it does or why we need it tho) but I really don't know how to apply it to dosbox-svn.

The last time on Discord @grant2258 and @natinusala pointed out a few possible locations for the "buffer" (in https://github.com/fr500/dosbox-svn/blob/master/src/cpu/core_dynrec/cache.h).

**Comment by grant2258** [comment]
@dotmick if Nintendo are still using arm on the switch compile with -fsigned-char on the cflag/C++  flags

**Comment by dotmick** [comment]
> @dotmick if Nintendo are still using arm on the switch compile with -fsigned-char on the cflag/C++ flags

I know that arm devices have char unsigned by default but (and sorry to ask that) what does it have to do with the current discussion?
