### ISSUE TITLE
[Nintendo Switch] When suspending Retroarch and resuming, audio crackles when using switch_thread driver

### ISSUE THREAD

**Issue by marco-calautti** [libretro/RetroArch#7519]
## Description

Retroarch is run via the hbmenu loaded via the new hb loader 2.0.0, by injection on a donor title (Pokémon Quest).
When pressing the home button during emulation, to suspend retroarch and then going back to it, the audio crackles and slows down. This only happens when using the switch_threaded audio driver.
If using the switch driver, everything works.

### Expected behavior
Emulation to be restored with audio functioning.

### Actual behavior
Audio is slow and crackles

### Steps to reproduce the bug
1. Configure your loader.ini to redirect hbmenu.nro to some donor title. In my case, Pokémon Quest.
2. Run hbmenu by launching Pokémon Quest
3. Run Retroarch and set "switch_thread" as the audio driver.
4. Run any content with any core
5. Press the home button.
6. Press the home button again.

### Version/Commit
Only used official 1.7.5. Don't know about previous versions.

### Environment information

- OS: OFW 6.1.0 with Atmosphere 0.7.3, launched via Fuseé.

**Comment by m4xw** [comment]
Does this happen without atmosphere too?
Are you sure this is a RetroArch Issue?

**Comment by marco-calautti** [comment]
Well, I don't know in what other way I can use hbl.nsp otherwise. As far as I know, booting Hekate with the right kips is essentially the same as running atmosphere. And as I said, the problem disappears when using the switch (non threaded) driver.

**Comment by vrcsix** [comment]
I'm experiencing the same issue.

Environment:
SX OS 2.3
Horizon 6.1.0
RetroArch nightly 2018-11-30 (via NSP)

**Comment by m4xw** [comment]
@natinusala didn't hook up the pause?

**Comment by vrcsix** [comment]
Yes. Regardless of whether "Don't Run in Background" is set to on or off, the game audio continues to play on the home screen (this is also the case with the "switch" driver) and the audio slowdown issue is present.

**Comment by m4xw** [comment]
@vrcsix You know you need to restart RA after changing the driver

**Comment by natinusala** [comment]
What ? `Don't Run in Background` to ON should pause the emulator when pressing HOME... this is wierd, I will have a look at it

**Comment by vrcsix** [comment]
Here's a video that hopefully shows everything, including the audio slowdown:

https://youtu.be/xUuGdQl_GEI

I'm using the 1.7.5 NSP that was linked from the GBAtemp release thread. I'm unable to transfer anything over to the Switch right now, but if you'd like me to test a different NSP, I can do it when I'm back home tomorrow.

**Comment by vrcsix** [comment]
Can confirm that `Don't Run in Background` indeed works when launching the NRO via https://gbatemp.net/threads/homebrew-menu-loader-legal-nsp.518433/. This also appears to fix the audio slowdown after sleep!

Tried disabling `Don't Run in Background` while launching this way, and the audio slowdown issue is present once again.

**Comment by natinusala** [comment]
@m4xw could it be that HOS throttles the process when qlaunch is opened, screwing up threaded audio ? That would explain the audio stutter even when the process isn't suspended anymore

**Comment by rsn8887** [comment]
Is there a trick to making suspend/resume work in general in Switch homebrew, some way to prevent the slow-down after resume?

I have the same problem in UAE4All2, regardless how I launch it. I think most other Switch homebrew also exhibits this problem with suspend/resume.

I would be very interested in a way to make suspend/resume work without slowdown in general.

**Comment by rsn8887** [comment]
I get it, thanks for pointing me to the code. What should I do once I know I lost focus? Of course I would pause audio etc. But what command can I use to minimize resources while out-of-focus? Some kind of nxsleep command or something?
