### ISSUE TITLE
dist-scripts: can't find *_libnx.a

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [libretro/RetroArch#7522]
When running ``dist-cores.sh libnx``, RA compiles successfully (retroarch_switch.nro and such are present), but the script complains about missing ``*_libnx.a``

**Comment by fr500** [comment]
This is **not** an issue....
Or well, maybe a documentation issue.

The way these are built is:

1. build the core
2. copy the cores to dist-scripts
3. run dist-cores.sh

Consoles and emscripten are linked statically to the cores, so you do need an a file to build RA.
You can't build RetroArch without the cores (well you can, but you wouldn't be able to play anything)

**Comment by ThatNerdyPikachu** [comment]
There is no simple way to build all cores for libnx (the only one is for the outdated switch target)

**Comment by fr500** [comment]
Of course there is. The buildbot does it every day every single day
You use libretro-super. The libretro-buildbot-recipe script
