### ISSUE TITLE
(macOS) Input loss on Metal build

### ISSUE THREAD

**Issue by CatGreen90** [libretro/RetroArch#7524]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

On the Metal build, input will occasionally be lost after closing the menu. This occurs on both the Metal and GL drivers

### Expected behavior

Input to be received after closing menu.

### Actual behavior

Input is sometimes lost after closing the menu.

### Steps to reproduce the bug

1. Open menu with F1
2. Tweak shaders? (not sure if this is related, but more information can't hurt)
3. Close menu
4. Input may or may not be working (last time, I managed to open and close the menu twice before losing input)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Nov 4 2018 (a25ec04)

### Environment information

- OS: macOS 10.13.6
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
I can reproduce this with the GL driver using the Metal build.

**Comment by stuartcarnie** [comment]
@twinaphex can you reproduce this with the `metal` driver?

**Comment by christ776** [comment]
Hi, I think this is the same issue I've opened on #7486

**Comment by CatGreen90** [comment]
This issue appears to be fixed.

**Comment by CatGreen90** [comment]
Never mind, it is in fact still happening.

**Comment by CatGreen90** [comment]
Appears to be fixed by #7750/#7771.

**Comment by CatGreen90** [comment]
Nope, this is *still* happening.
Log: https://pastebin.com/dqYFZLik

**Comment by twinaphex** [comment]
We need help here, we don't know how to fix this on our own.

**Comment by CatGreen90** [comment]
More info: the input loss in cores seems to be associated with single inputs registering multiple times in the menu, as seen here:
![](https://media.giphy.com/media/UopnVQHUGZIppSM9QG/giphy.gif)

**Comment by LibretroAdmin** [comment]
This seems to finally fix these longstanding issues thankfully.

https://github.com/libretro/RetroArch/pull/14805#event-8157853900
