### ISSUE TITLE
[Menu] Dropdown list choice is not applied immediately in some cases

### ISSUE THREAD

**Issue by rz5** [libretro/RetroArch#7528]
## Description

When changing "Settings > Audio > Audio Volume Level (dB)" via its dropdown list of options,
the change is not immediately made.
Only after re-entering the dropdown list is the change made.

### Expected behavior

The same behavior as if the user presses left/right to change the highlighted option (immediate change in most cases).

### Actual behavior

After selecting the new audio level, it is correctly displayed on the right of the option name, but
the audio level stays the same. 

### Steps to reproduce the bug

1. Load a core with content, have it be playing sound;
2. Highlight the option in Setttings > Audio >Audio Volume Level (dB);
3. Change the value via its dropdown list to e.g. -80;
4. Exit the menu and into the content;
5. Sound level is still the same (this is the bug);

6. Call the menu back up;
7. Highlight the same option and enter its dropdown list;
8. Exit the menu again;
9. Sound level has changed (this is a workaround).

### Bisect Results

This was never working, nothing to bisect.

### Version/Commit

RetroArch: 1.7.5/183da9f83a

### Environment information

- OS: Windows 10/10.0.17134 Build 17134
- Compiler: MinGW (8.2.0) 64-bit

**Comment by orbea** [comment]
May be related to issue https://github.com/libretro/RetroArch/issues/7560.

**Comment by orbea** [comment]
@rz5 , @retro-wertz and @Betonar was this fixed in commit https://github.com/libretro/RetroArch/commit/0e66da393078579f656f886b1adb9075ecef19bc?

**Comment by rz5** [comment]
@orbea - Seems like it was fixed. I cannot reproduce the bug anymore with the latest commit.

**Comment by orbea** [comment]
Thanks for testing, I'm going to close this then unless someone else can reproduce it. :)
