### ISSUE TITLE
[Nintendo Switch] Time offset on clock

### ISSUE THREAD

**Issue by capitaineflam25** [libretro/RetroArch#7532]
It seems that this is the UTC time that is displayed, not the local time.

![image](https://user-images.githubusercontent.com/985702/47987341-89430600-e0df-11e8-99b9-5baf7c8d6975.png)

Capture from Retroarch 1.7.5 (launched from NSP) on Nintendo Switch (6.0.1 firmware)

**Comment by m4xw** [comment]
Duplicate of https://github.com/libretro/RetroArch/issues/7503
https://github.com/libretro/RetroArch/issues/7391
Use updated builds

**Comment by m4xw** [comment]
Please close

**Comment by capitaineflam25** [comment]
Thanks for the answer and sorry for the duplicate
