### ISSUE TITLE
[Nintendo Switch] Quit RetroArch has no effect

### ISSUE THREAD

**Issue by capitaineflam25** [libretro/RetroArch#7533]
Maybe it's linked to the "retroarch.nsp" launcher use : when you use "Quit Retroarch" it has the same effect as "Restart RetroArch" but it is never closed.

![image](https://user-images.githubusercontent.com/985702/47987608-3c136400-e0e0-11e8-9362-1043f31f4d46.png)

Capture from Retroarch 1.7.5 (launched from NSP) on Nintendo Switch (6.0.1 firmware)

**Comment by m4xw** [comment]
Its not a Bug, it's a feature.
Also Restart RetroArch starts the last used core, Quit RetroArch starts the static dummy core.
This is outside the scope of RA, this is nx hbloader behaviour.
@twinaphex Please close.

**Comment by capitaineflam25** [comment]
Ok thanks for your answer

**Comment by m4xw** [comment]
For the record: We could change the behavior in the future, but right now it's intended.
Updated versions will run the "exit retroarch" routines on force close.
