### ISSUE TITLE
Turning on "All users control menu" cases menu button to not toggle

### ISSUE THREAD

**Issue by alfrix** [libretro/RetroArch#7538]
Expected behaviour:
Pressing the the xbox (Xbox logo) button toggle the menu as F1 (bring up and hide)

Actual behaviour:
Works in the default config but, If you turn on "All users control menu" the button brings up the menu but does not hide it.

1. Start RA content (any)
2. Press the Xbox button 2 times, it should show the menu and then hide it
3. Turn on "All users control menu"
4. Press the Xbox button 2 times, it shows the menu but doesn't hide it, (F1 still works)

Tested on Windows Current Master, i don't know for how long this has been happening, it was like this since the first time i tested, but i always forget to make the issue 

@bparker06

**Comment by orbea** [comment]
I think this is a duplicate issue of https://github.com/libretro/RetroArch/issues/5127.

I'm going to close this, but please complain if I am not understanding.
