### ISSUE TITLE
resize is undefined in this function...

### ISSUE THREAD

**Issue by DickerDackel** [libretro/RetroArch#7542]
https://github.com/libretro/RetroArch/blob/c9cccfbd30e0e1db5df5d51e174f7125f618ed93/gfx/drivers/vg.c#L451

Compiles with the added declaration of resize as stolen from the other functions from this commit.  Sorry, dunno how the github pull request stuff works, so here's the context diff:

```
diff --git a/gfx/drivers/vg.c b/gfx/drivers/vg.c
index 28db6bdde7..4bb682b0e5 100644
--- a/gfx/drivers/vg.c
+++ b/gfx/drivers/vg.c
@@ -442,6 +442,7 @@ static bool vg_frame(void *data, const void *frame,
 static bool vg_alive(void *data)
 {
    bool quit            = false;
+   bool resize         = false;
    unsigned temp_width  = 0;
    unsigned temp_height = 0;
    vg_t            *vg  = (vg_t*)data;
```

**Comment by twinaphex** [comment]
Pushed a buildfix, thanks for letting me know.

https://github.com/libretro/RetroArch/commit/f271ea789dec080c3b54bfe4e36f74e473a5be5f

**Comment by orbea** [comment]
Since this was pushed I'm going to close this issue.
