### ISSUE TITLE
FFmpg does not work, loading .mp3 crashes RetroArch

### ISSUE THREAD

**Issue by Vipes** [libretro/RetroArch#7559]
## Description

FFmpg does not work, loading .mp3 crashes RetroArch

### Expected behavior

Play music.

### Actual behavior

Program crash.

### Steps to reproduce the bug

1. Install FFmpg Core
2. Try to play a .MP3 file

### Version/Commit
You can find this information under Information/System Information

- RetroArch: dc0fdd7c68

### Environment information

- OS: Windows 10

**Comment by fr500** [comment]
Works fine here

![image](https://user-images.githubusercontent.com/1721040/48172160-c8827a00-e2cc-11e8-9811-01e65136c728.png)

You don't need to install ffmpeg, just use the built-in core instead it's newer and baked into retroarch

**Comment by orbea** [comment]
@Vipes Any updates?

**Comment by orbea** [comment]
Still works here so please reply if this is still a problem, I'm going to close this until then.

**Comment by alexb3d** [comment]
Hi, I have RetroArch (Flatpak) in Ubuntu 18.04 and I can not load the FFmpeg kernel.

**Comment by orbea** [comment]
What is the ffmpeg kernel?

**Comment by alexb3d** [comment]
The version I have installed "3.4.4-0ubuntu0.18.04.1". In RetroArch I can not see what version I have.
Is that the kernel?

**Comment by orbea** [comment]
The ffmpeg libretro core is built into RetroArch when built against the system version of ffmpeg. There should be no need to install any external libretro core. Try loading the content directly with RetroArch and no core.

I'm still not sure what you mean by kernel...

**Comment by alexb3d** [comment]
> The ffmpeg libretro core is built into RetroArch when built against the system version of ffmpeg. There should be no need to install any external libretro core. Try loading the content directly with RetroArch and no core.

When trying to load the content directly it does not show the option to select core. It remains on [this screen](https://drive.google.com/open?id=17hp11XOXbgrOD0GmkRGPrz4wgEAV3tmu). 

> I'm still not sure what you mean by kernel...

Ops! It's google translator that changes the word "Core" to "Kernel"

**Comment by orbea** [comment]
In the menu can you check `Information -> System Information -> FFmpeg support`? It should say `FFmpeg support: yes`.

My understanding is that the standalone ffmpeg core has not received all the fixes in the builtin core which is preferred.

**Comment by alexb3d** [comment]
> In the menu can you check Information -> System Information -> FFmpeg support? It should say FFmpeg support: yes.

If it supports it, "FFmpeg support: Yes"

...So, for now we will not have a core.

**Comment by orbea** [comment]
Also can you use another site for the picture? Google images doesn't work here.

**Comment by Elmapul** [comment]
the ffmpeg from the snap version dont work on ubuntu 18.04
i couldnt install neither the flatpak nor the version from the ppa
