### ISSUE TITLE
libretro-db `dat_converter` has error in msys2

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#7586]
UPDATE: I have submitted a PR which fixes the Makefile error but there is still an error on executing `dat_converter`: `./dat_converter: line 4: ./lua_converter: No such file or directory`

I have an msys2 installation set up according to the Compiling Retroarch docs.

1. `git clone http://github.com/libretro/retroarch/` (with the Makefile patch)
2. `cd retroarch && ./configure`
3. `cd libretro-db`
4. `make`
5. `$ ./dat_converter "MAME 2003-Plus.rdb" "MAME 2003-Plus.dat"`

**Error**: `./dat_converter: line 4: ./lua_converter: No such file or directory`

**Comment by ofry** [comment]
Maybe it's related:

https://github.com/libretro/libretro-super/issues/905

**Comment by grant2258** [comment]
just the make file that needs  fixed a diff was shown in discord #programming

**Comment by ofry** [comment]
What do you mean? My issue still exist now.

**Comment by grant2258** [comment]
yes it still exists the makefile in for libretro-db in retroarch needs fixed is all. There is a diff here that will fix it that was shared in discord '#programming

https://hakchi.net/retroarch/rdb/

just applly the diff to the Makefile

**Comment by markwkidd** [comment]
I've submitted a PR to apply that diff to the Makefile https://github.com/libretro/RetroArch/pull/7594

**Comment by markwkidd** [comment]
Minor update: When using the `build_databases` script from libretro-super to build all of the RDB files, this error does not occur so I'll assume there is something in that script which needs to be added to the instructions for compiling a single RDB.

**Comment by retro-wertz** [comment]
libretro-database-build uses c_converter "rdb" "dat", not dat_converter which uses lua (i dont remember using this before to create rdb)

**Comment by markwkidd** [comment]
Thanks @retro-wertz that is quite useful to know.

Once this is sorted out there should definitely be an update to the libretro-db README: https://github.com/libretro/RetroArch/tree/master/libretro-db#dat-file-converter

I'll be glad to write the update -- just wanted to post in the instructions I was following for reference
