### ISSUE TITLE
cant get cia info on 3ds

### ISSUE THREAD

**Issue by TheAutisticGamer** [libretro/RetroArch#7599]
## Description
Hiya! I came over and installed the retroarch cia on FBI with a side of godmode9 and Luma3ds. But whenever I load it up on my OLD 3ds. I get the error "Cant get CIA file info." I just boot it up and it just happens

### Expected behavior

I expect retroarch to boot up.

### Actual behavior

I get an error message the second I launch it

### Steps to reproduce the bug

1. Power up the 3ds and head to retroarch
2. Launch retroarch
3. Throw the 3ds out the window because you just did it

### Bisect Results

This started happening when I first installed it

### Version/Commit
You can find this information under Information/System Information

- RetroArch: The Lastest version that's not nightly

### Environment information

- OS: Old 3ds.
- Compiler: WHAT THE CRAP IS A SONIC?! (Does that count?)

**Comment by FateForWindows** [comment]
You need to install the core .cia files present in the "cores" directory inside the Retroarch folder, which should be extracted to the root of your SD card.

**Comment by gingerbeardman** [comment]
Is it correct that the cia files need to remain in that folder for things to work correctly? If I delete them no cores are found in the plain retroarch app

**Comment by FateForWindows** [comment]
> Is it correct that the cia files need to remain in that folder for things to work correctly? If I delete them no cores are found in the plain retroarch app

Yep, discovered that when I was using the last stable version of RA.

**Comment by orbea** [comment]
It seems @FateForWindows has explained how to resolve this so I am going to close this issue, please let us know if there is any other problems.

**Comment by FateForWindows** [comment]
Updated my comment as well, specifying not to delete the cias.

**Comment by Axelitos4tB** [comment]
i have the same problem but i have all necesary things
