### ISSUE TITLE
IOS version cannot be Chinese

### ISSUE THREAD

**Issue by qwer1120550606** [libretro/RetroArch#7600]
IOS can not display Chinese after replacing font.ttf with packaged version. How do I solve this problem?

**Comment by orbea** [comment]
What version are you using?

**Comment by qwer1120550606** [comment]
Package version 1.75. Ios cannot be a Chinese language


iphone

**Comment by qwer1120550606** [comment]
Iphone jailbreaker runs the packaged RetroArch 1.75 version of the ipa package. Cannot replace Chinese after installation. Replacing some tutorials font.ttf still does not have a Chinese language interface. Is there a way to solve it? Or provide a Chinese ipa installation package. It is best to have a solution.

**Comment by qwer1120550606** [comment]
> 您使用的是什么IOS和RetroArch版本？

Iphone jailbreaker runs the packaged RetroArch 1.75 version of the ipa package. Cannot replace Chinese after installation. Replacing some tutorials font.ttf still does not have a Chinese language interface. Is there a way to solve it? Or provide a Chinese ipa installation package. It is best to have a solution.

**Comment by qwer1120550606** [comment]
> What IOS and RetroArch versions are you using?
Package version 1.75. Ios cannot be a Chinese language

iphone

**Comment by qwer1120550606** [comment]
> What IOS and RetroArch versions are you using?

Iphone jailbreaker runs the packaged RetroArch 1.75 version of the ipa package. Cannot replace Chinese after installation. Replacing some tutorials font.ttf still does not have a Chinese language interface. Is there a way to solve it? Or provide a Chinese ipa installation package. It is best to have a solutio

**Comment by orbea** [comment]
I'm sorry, but I don't have any IOS experience and can not help. Also I am not sure many people are maintaining IOS, you might have a better mobile RetroArch experience with android.

Someone else might able to help with more with IOS.

**Comment by qwer1120550606** [comment]
> I'm sorry, but I don't have any IOS experience and can not help. Also I am not sure many people are maintaining IOS, you might have a better mobile RetroArch experience with android.
> 
> Someone else might able to help more with IOS.

Thank you, extending the iOS Chinese question, I hope you and the developer to comment.

**Comment by orbea** [comment]
I suppose this is a font issue?

See https://github.com/libretro/RetroArch/issues/7822#issuecomment-450018514.

**Comment by WeedyWeedSmoker** [comment]
You can close this...

Fixed by commit 43d217668d2414c118bf15c7e46cea797852cb17
