### ISSUE TITLE
macOS can't change interface to Chinese.

### ISSUE THREAD

**Issue by specter119** [libretro/RetroArch#7602]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Even after I change the font to a ttf support chinese, but the Chinese item in User/Language is still ????.

### Version/Commit

- RetroArch: 1.75 release

### Environment information

- OS: macOS Mojave 10.14.1

**Comment by orbea** [comment]
Maybe related to issue https://github.com/libretro/RetroArch/issues/7600.

**Comment by orbea** [comment]
I suppose this is a font issue?

See https://github.com/libretro/RetroArch/issues/7822#issuecomment-450018514.

**Comment by CatGreen90** [comment]
It's definitely not a font issue; it even happens with Unifont, which has covers the entire Unicode Basic Multilingual Plane.
<img width="966" alt="image" src="https://user-images.githubusercontent.com/44750311/51041374-c87e4f00-1587-11e9-8d32-df2823401ad0.png">
It's like RetroArch is somehow using MacRoman encoding on Mac instead of Unicode or something.

**Comment by 1900forever** [comment]
Same problem here.
I even used a custom font file but no good.
![screen shot 2019-01-13 at 12 04 38](https://user-images.githubusercontent.com/3516677/51081488-724a1100-172b-11e9-84ae-75f47238d6eb.jpg)

**Comment by twinaphex** [comment]
Actually I believe the CoreText driver doesn't have Unicode support implemented.

We are in need of a skilled coder who can add it -

https://github.com/libretro/RetroArch/blob/master/gfx/drivers_font_renderer/coretext.c

@jdgleaver You might be interested to learn this.

**Comment by jdgleaver** [comment]
Thanks for the info - it's nice to know that the feature isn't 'broken' per se (just not implemented).

I don't own any Apple devices (and probably never will), so I can't really help with this...

It has fairly significant implications for the discussions in PR #8291 though - if we're unlikely to get full UTF-8 support across the board any time soon, then maybe devs should be careful about using any kind of 'hard coded' UTF-8 strings (or at least, without appropriate `#ifdef` wrappers...)

**Comment by WeedyWeedSmoker** [comment]
You can close this...

Fixed by commit 43d217668d2414c118bf15c7e46cea797852cb17
