### ISSUE TITLE
Gamepad/Controller should just work

### ISSUE THREAD

**Issue by cawoodm** [libretro/RetroArch#7605]
I could imagine the following is not a bug or defect with retroarch it's just a really painful user experience when installing retroarch on ubuntu which should be remedied. Basically, although the controller works and is recognized by the OS, it cannot be used in retroarch at all. This should "just work" as it does in Android etc.

So, my NES30 Bluetooth controller is paired with Linux, recognized in jstest and works on http://html5gamepad.com/ but not in RetroArch. But I cannot control the menu with the gamepad even though it's recognized and displayed under "Input User 1 Binds". When I start a game some yellow text appears for a split second "gamepad not configured" at the bottom. Turns out I have to map all the buttons manually.

To reproduce: Fresh Ubuntu 18.10 installation and tried both "Retroarch" packages in the Ubuntu App Store to no avail. Currently 1.7.3.

Changing input drivers to linuxraw does not help. Restarting retroarch does not work. input_autodetect_enable is = "true". Copying autoconfigs to ~/.config/retroarch/autoconfig (which was empty) and restarting retroarch does not help.

**Comment by orbea** [comment]
Like explained in the previous comment this is not really something we can fix, please contact the ubuntu maintainers or make sure your autoconfig profiles is set to a user writable directory and use the online updater.
