### ISSUE TITLE
Wii-U: Retroarch 1.7.5 XMB Icons Not Working, And ROMs Not Placed Into Proper Directories

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#7613]
## Description
XMB icons are not being displayed properly in Wii U version of RetroArch with latest nightly release (11-18-2018), and roms are not being placed into console specific directories.

### Expected behavior

XMB icons should be displayed correctly, and roms should be placed into system specific directories.

### Actual behavior

XMB icons appear distorted, and I have to manually enter each rom to load it, when the roms present should be detected based on their system.

### Steps to reproduce the bug

1. Loaded RetroArch through Wii U Homebrew Launcher

2. Notice weird menu icons.

3. Download latest assets through "Online Updater" with no visual change present.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by SBanya** [comment]
Also, for picture references for my issue, this is the same issue I'm having as this bug, but the suggested solution did not work:

https://github.com/libretro/RetroArch/issues/7380

**Comment by alfrix** [comment]
The downloader/updater have issues on wiiu, this is not a problem of xmb, download and place the assets manually

**Comment by SBanya** [comment]
What I don't get is that it downloads a zip through obviously linux based tools. Why can't a simple unzipping program be included, and ran inside the same folder? This step seems so unnecessary, since it totally seems possible to do so.

Thanks for the heads up about the assets zip itself, because yes, unzipping it definitely works. Though I think as the end user, I really find that annoying since the PC version just unzips itself just fine.

**Comment by SBanya** [comment]
That is not the point. I think as a user I assumed Retroarch did this but what I really mean to say is that the "playlist" function isn't working.

**Comment by fr500** [comment]
No.
Playlists doesn't move your files around and I like it better like that.

RA is not itunes.
