### ISSUE TITLE
RetroArch crashes when entering a netplay password

### ISSUE THREAD

**Issue by meepingsnesroms** [libretro/RetroArch#7614]
When connecting to a password protected netplay host RetroArch will crash when you push enter.

I have not thoroughly tested this, I plan to soon.
I entered the password correctly, I dont know if this happens if you enter it wrong.

RetroArch: 1.7.5
Mac OS: 10.14.1 Mojave
Core: Snes9x(no year) 1.56.2 96818d6

**Comment by RobLoach** [comment]
Did anything come through on the logs?

**Comment by fr500** [comment]
This is the callback that handles the entered password: 

```C
#ifdef HAVE_MENU
static void handshake_password(void *ignore, const char *line)
{
   struct password_buf_s password_buf;
   char password[8+NETPLAY_PASS_LEN]; /* 8 for salt, 128 for password */
   netplay_t *netplay = handshake_password_netplay;
   struct netplay_connection *connection = &netplay->connections[0];

   snprintf(password, sizeof(password), "%08X", connection->salt);
   strlcpy(password + 8, line, sizeof(password)-8);

   password_buf.cmd[0] = htonl(NETPLAY_CMD_PASSWORD);
   password_buf.cmd[1] = htonl(sizeof(password_buf.password));
   sha256_hash(password_buf.password, (uint8_t *) password, strlen(password));

   /* We have no way to handle an error here, so we'll let the next function error out */
   if (netplay_send(&connection->send_packet_buffer, connection->fd, &password_buf, sizeof(password_buf)))
      netplay_send_flush(&connection->send_packet_buffer, connection->fd, false);

#ifdef HAVE_MENU
   menu_input_dialog_end();
   rarch_menu_running_finished();
#endif
}
#endif
```

It doesn't check if line is null, solve that and it will be fixed.

**Comment by RobLoach** [comment]
The password at the time when we tested was `cuttlefish`.

**Comment by meepingsnesroms** [comment]
This should be fixed, but I am waiting to test to close it:
https://github.com/libretro/RetroArch/pull/7635

**Comment by fr500** [comment]
I think you should use

```
!string_is_empty(line)
```

**Comment by RobLoach** [comment]
The latest update on this is over at https://github.com/libretro/RetroArch/pull/7637 by @GregorR.
