### ISSUE TITLE
The "Audio Volume Level (dB)" on Android TV (testing on a Shield TV) doesn't work properly with at least the Genesis console (not the core, the console)

### ISSUE THREAD

**Issue by JoelStickney** [libretro/RetroArch#7624]
## Description

The "Audio Volume Level (dB)" on Android TV (testing on a Shield TV) doesn't work PROPERLY. It appears to work at first (I have hotkeys that turn up and down the volume on my controller), but give it a 1000 frames and it slowly creeps back up to 0dB, then realizes it's "supposed" to be at -32dB all of the sudden and then IMMEDIATELY gets quieter again, and the process repeats nonstop. The only reason I switched to Retroarch on my Shield was because of the volume feature which, ironically, doesn't work. So I'm pretty invested in fixing it if someone could point me in the right direction.

I tested this same feature on macOS version and it worked perfectly so I've nailed it down to the audio driver, "opensl.c" which I'm currently looking into (seeing if I can't learn to compile it for Android).

Sidenote: It APPEARS that this LOOPING dB behavior only adds (slowly over ~1000 frames) around 32 dB before it "snaps back" to what it's supposed to be. Also, I don't think it goes above 0dB also, so it may just be a weird way that Retroarch slowly (accidentally) increments the value to it's default of 0 dB until the buffer ends.

Tested via Shield TV (8.0 Oreo):
• 32-bit
• 64-bit
Both versions exhibited the same behavior.

### Expected behavior

Consistent level decibels (dB), honoring the setting in the system.

### Actual behavior

Constantly lowering dB levels until (supposedly) the buffer starts over and then continuous to loop.

### Steps to reproduce the bug

1. Play any game on Android (both 32-bit and 64-bit, both exhibit the same behavior).
2. Use the XMB or use the hotkey to lower the "Audio Volume Level (dB)" to lower than -32dB
3. Wait for about 60 seconds (you can use fast forward to speed this up) and you'll hear the volume level constantly lowering in a loop.

### Bisect Results

I believe that there is an equation that is minus-ing the dB setting in opensl.c (which I believe @twinaphex wrote?) slowly until it's buffer ends and it resets to the CORRECT value. 

### Version/Commit
You can find this information under Information/System Information

- Android 8.0 - RetroArch: [Official Version: 1.7.5 | Build Date: Oct 2 2018 | Git version: c9c6c5a]
- Android 8.0 - RetroArch64: [Official Version: 1.7.5 | Build Date: Oct 3 2018 Git version: 826c777]
- macOS 10.14.1 - RetroArch: [Official Version: 1.7.5 | Build Date: Oct 22 2018]

### Environment information

- OS: Android 8.0 Oreo (Hardware: Shield TV, Version 7.1), MacOS 10.14.1
- Compiler: [N / A]

**Comment by JoelStickney** [comment]
Wanted to note that it's also not the Audio Resampler Driver as the macOS version I tested with (also 1.7.5) used Sinc, as does the Android (TV) version.

**Comment by fr500** [comment]
I haven't seen this on my SATV at all.

**Comment by JoelStickney** [comment]
Update: This does not happen with 32X games interestingly enough DESPITE using the SAME CORE (PicoDrive) meaning I'm next to positive this is console, though not core specific (and Android specific since it works on macOS just fine using the same cores and consoles). I think consoles like the genesis use a specific type of MIDI instrument and maybe they are causing issues (?). I have to keep testing all consoles but it also didn't happen didn't happen at all with Snes9x core (or SNES games) nor PCSX-Rearmed (PSX Games).

**Comment by JoelStickney** [comment]
Update: Game Gear games (using PicoDrive or GenesisPlus GX) ALSO don't exhibit the same behavior as Genesis games. This literally may be ONLY genesis specific, but certainly not core specific. Which makes me wonder where the fault really lies:

• In the way ALL cores that support Genesis handle Genesis-specific sound on Android specifically? Meaning I should submit individual tickets to each core creator.
OR
• In the way Retroarch handles the specific values that Genesis games tend to send to the Audio Driver. Maybe it uses unique enough values that mess up the audio driver. My only theory about this is because Genesis Games on macOS using either PicoDrive of GenesisPlus GX work just fine with this feature.

**Comment by fr500** [comment]
I don't have this problem..

**Comment by JoelStickney** [comment]
It ended up being a TV "Volume Leveling" setting that was accidentally left on my TV. 🤦‍♂️  Closing this.
