### ISSUE TITLE
[Feature Request] Core Updater list 

### ISSUE THREAD

**Issue by QuaiGoner** [libretro/RetroArch#7626]
I think that would be helpfull if Core Updater was listing cores that you have on your system dowloaded on first or only those cores that downloaded. In current state updater works as core downloader. Sorry if this is no place to write that, but your forum looks pretty dead. Thanks.

**Comment by hizzlekizzle** [comment]
>Sorry if this is no place to write that, but your forum looks pretty dead
This is a fine place to request it, but there's a ton of activity at the forum...
