### ISSUE TITLE
(XMB) text in core information does not scroll

### ISSUE THREAD

**Issue by CatKasha** [libretro/RetroArch#7631]
## Description

When use XMB menu driver, text in core information does not scroll, if text doesn't fit on the screen

### Expected behavior

Text that does not fit on the screen should scroll

### Actual behavior

Text that does not fit on the screen does not scroll

![default](https://user-images.githubusercontent.com/19823797/48894497-f41c6d00-ee53-11e8-8af5-a01311fb34ce.png)

![default](https://user-images.githubusercontent.com/19823797/48894269-5e80dd80-ee53-11e8-8e3c-cf87343f039f.png)

### Version/Commit
- RetroArch: stable 1.7.5
- RetroArch: nightly 2018-11-21 | b3d38c4

### Environment information
- PS Vita 3.60 Henkaku

**Comment by orbea** [comment]
I can't reproduce this on Linux, I am assuming this is only on vita?

**Comment by rsn8887** [comment]
This ones not fix the issue, but note that you can improve the text display on Vita a whole lot! 

Just go to ‘Settings->User Interface->Appearance->Menu Font’ and select ‘ux0:/data/Retroarch/assets/glui/font.ttf’

**Comment by CatKasha** [comment]
@orbea i did not check on other platforms, only on Vita
@rsn8887 thanks for the information about fonts

**Comment by CatKasha** [comment]
Text in core information now scrolls, checked on version 1.8.1 (stable), thanks!
