### ISSUE TITLE
Feature request: Allow building with shared mbedtls

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#7639]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Allow building with shared mbedtls instead of baked-in (for debugging purposes)

### Expected behavior

Now retroarch can use only baked-in mbedtls.

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
I've considered doing this, but mbedtls doesn't ship anything handy like a pkgconfig file. I'll give it a try if you are willing to test it.

**Comment by ofry** [comment]
At least, windows mingw has this packages.

```
$ pacman -Ss mbedtls
mingw32/mingw-w64-i686-mbedtls 2.13.0-1 [установлен]
    mbed TLS is an open source and commercial SSL library licensed by ARM Limited. (mingw-w64)
mingw64/mingw-w64-x86_64-mbedtls 2.13.0-1 [установлен]
    mbed TLS is an open source and commercial SSL library licensed by ARM Limited. (mingw-w64)
dkp-libs/3ds-mbedtls 2.8.0-2 [установлен]
    Deflate compression method library (for Nintendo 3DS homebrew development)

```

**Comment by orbea** [comment]
Yes, but no `mbedtls.pc` file?

**Comment by orbea** [comment]
Yes, see https://github.com/ARMmbed/mbedtls/pull/2006 and https://github.com/ARMmbed/mbedtls/pull/1753

**Comment by fr500** [comment]
This is coming from this issue:
https://github.com/libretro/RetroArch/issues/7451

Do we know for sure this is the problem? or are we making changes just in
case that solves the issue?

**Comment by ofry** [comment]
It compiles it runs fine, but HTTPS bug still exist... I will try to give you more info bit later.

**Comment by orbea** [comment]
Well, at least we know the https bug is reproducible with the upstream mbedtls too, thanks for testing.

**Comment by ofry** [comment]
https://github.com/libretro/RetroArch/issues/7451#issuecomment-447540405

**Comment by ofry** [comment]
Please merge your branch to upstream :)

**Comment by orbea** [comment]
I'll submit a PR in a bit, It was too late last night. :)
