### ISSUE TITLE
[Feature Request]Separate control setting for WSC core two srceen modes

### ISSUE THREAD

**Issue by leoxxx** [libretro/RetroArch#7642]
WSC has two sreen mode:landscape and portrait. Please separate control setting for them. Reference Matsu WSC Emulator. 
In Hunter X Hunter - Sorezore no Ketsui, normal is landscape. But when you push the Y↓ in area selection, it change to portrait. Then you have to rotate left your controller. You have to push the left stick and axis. It's so hard to controll.
One setting for landscape and another for portrait. Custom the key what you want. They are independent.

**Comment by fr500** [comment]
please read the issue guidelines next time...

**Comment by leoxxx** [comment]
> 
> 
> please read the issue guidelines next time...

I'm editing the commented.
I have updated commented.

**Comment by fr500** [comment]
The first part of the guidelines indicate that you should only issue this tracker for RetroArch issues.
This is not a retroarch issue, but a core feature request.

**Comment by leoxxx** [comment]
Can't find wsc core project page for libretro. So I commit here.

**Comment by fr500** [comment]
That's still not correct

**Comment by orbea** [comment]
The wonderswan issue tracker is here.

https://github.com/libretro/beetle-wswan-libretro/issues

If this is still a problem please report the issue in the correct repo, thanks!
