### ISSUE TITLE
Latest Nightlies Cores Black Screen on Switch 

### ISSUE THREAD

**Issue by OTFree** [libretro/RetroArch#7646]
Switch is on firmware 6.10
Using SXOS v2.3, Retroarch 1.7.5 (latest NSP)

So I used the online updater built into Retroarch, but all of the cores that were updated now hang on a black screen when attempting to load it. Of note, this only applies to cores that were updated, the other cores still run just fine. 

Does anyone know why this happens? My switch doesn't soft lock, but I do have to exit via the home menu and close the application manually. I get the "the software was closed because an error occured" message afterwards.

Should I just re-download the older, more stable cores in the meantime?

**Comment by RobLoach** [comment]
This is fixed. Update all the things, and it should be working.
