### ISSUE TITLE
(CLI) Using --appendconfig to load a core with a different video driver is crashing RetroArch

### ISSUE THREAD

**Issue by brianblakely** [libretro/RetroArch#7652]
## Description

Using this command causes RetroArch to open and then crash:
```bash
./retroarch --verbose -L cores/mednafen_psx_hw_libretro.dll --appendconfig retroarch.vulkan.cfg "/path/to/game.cue"
```
retroarch.vulkan.cfg contains the following:
```properties
video_driver = "vulkan"
```

### Expected behavior

RetroArch should start, then launch core and content with the specified settings.

### Actual behavior

RetroArch starts up, but kills itself before ever launching the core.

Log:
```
[INFO] RetroArch 1.7.5 (Git c02536af08)
[INFO] Redirecting save file to "/path/to/file.srm".
[INFO] Redirecting savestate to "/path/to/file.state".
[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
Built: Oct  9 2018
[INFO] Version: 1.7.5
[INFO] Git: c02536af08
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/path/to/cores/mednafen_psx_hw_libretro.dll"
[INFO] [overrides] core-specific overrides found at /path/to/config/Beetle PSX HW/Beetle PSX HW.cfg.
[INFO] [overrides] no content-dir-specific overrides found at /path/to/config/Beetle PSX HW/game.cfg.
[INFO] [overrides] no game-specific overrides found at /path/to/config/Beetle PSX HW/game.cfg.
[INFO] Config: appending config "/path/to/config/Beetle PSX HW/Beetle PSX HW.cfg"
```

### Steps to reproduce the bug

1. Use these config files (retroarch.debug.cfg to replace retroarch.cfg)
[retroarch.debug.zip](https://github.com/libretro/RetroArch/files/2613942/retroarch.debug.zip)
2. Run the shell command above in the RetroArch install directory

### Bisect Results

This worked before the stable release of RetroArch 1.7.5

### Version/Commit

- RetroArch: 1.7.5 / c02536af08

### Environment information

- OS: Windows 10

**Comment by RobLoach** [comment]
Does Vulkan work on your system? Without the config change, are you able to apply Vulkan and use it?

**Comment by brianblakely** [comment]
Hi @RobLoach - as it happens, I tested this yesterday before reading your comment and found, to my surprise, that I experienced the same crash when loading games via the GUI in Beetle with the Vulkan driver already set in my universal config.

Now I believe that this is unrelated to the CLI, but what could it be?

**Comment by brianblakely** [comment]
I did a deep dive on this and found that Beetle PSX HW crashes when Vulkan and runahead are both enabled. Previously, runahead only affected performance, but now it appears to cause a crash for me.
