### ISSUE TITLE
default setting is different on RetroAarch and RetroArch x64

### ISSUE THREAD

**Issue by xTMODx** [libretro/RetroArch#7658]
default setting in XMB menu for Settings > User Interface > Appearance > Icon Shadows Enable = ON / OFF is different on RetroArch and RetroArch x64
It is OFF by default on RetroArch and ON by default on RetroArch x64

- RetroArch: e13efbd
- OS: Android 8.0

**Comment by twinaphex** [comment]
I guess we figure that GPUs in SoCs have improved immeasurably over the years. Icon shadows can lead to subpar performance on older GPUs on Android. We make the calculated assumption that on 64bit android devices, there wont be anoticeable difference in performance with it turned on.

**Comment by xTMODx** [comment]
Ahh so it was intended, then it is ok.

**Comment by orbea** [comment]
It looks like this is not an issue and the behavior is explained so I am going to close this issue, please let us know if there is anything else?
