### ISSUE TITLE
andoid problem with more than one - in a filename or folder

### ISSUE THREAD

**Issue by grant2258** [libretro/RetroArch#7661]
We came across  a user that that was having issues with mame2003-plus here

https://github.com/libretro/mame2003-plus-libretro/issues/493

then we done an attempted fix here.

https://github.com/libretro/mame2003-plus-libretro/pull/498

So I just want to make you guys aware of an android bug

in com.retroarch
is saving retroarch-core-
instead of retroarch-core-options.cfg

its also messing up on mame2003-  instead of mame2003-plus
in save and system folders.

i have no idea if this is out core doing this or a RA bug looks like a RA bug because mame2003 is saving too  retroarch-core- as well it seems something is not liking a double - in the folder or filename for some reason.

**Comment by grant2258** [comment]
could be related is in the same timeframe between the 20 and 21st 

https://github.com/libretro/RetroArch/issues/7628

**Comment by RobLoach** [comment]
Which version of RetroArch? Could you provide any logs you find? What's in your .cfg?

**Comment by grant2258** [comment]
Im not too familiar working on android so im not 100% sure what i need on windows to get logs. I get a feeling it will be easier on linux. The config im using is default from install which i will include in this post. 

https://pastebin.com/TKCsgVMT

retroarch  commit is c9c65a

**Comment by grant2258** [comment]
i just tested with the nightly 2018-11-23-RetroArch.apk seems to be saving properly here again. It might be a good idea to update the playstore Retroarch

**Comment by grant2258** [comment]
android playstore version will be getting updated soon so i will close this issue
