### ISSUE TITLE
(OSX) NetPlay crashes RetroArch on Core load

### ISSUE THREAD

**Issue by vampiricwulf** [libretro/RetroArch#767]
Netplay options:

```
Enable ON
Mode SERVER
Spectator OFF
IP <Nothing>
Port 55435
Delay 0
Nickname VampiricWulf
```

Core: SNES9x
Game: Super Mario World
I built from the latest commit, OSX (not PPC). 9fc10a3d9ae97a8a437844833114db527411cd32

**Comment by frdrck** [comment]
I'm having the same problem, what was the solution?
