### ISSUE TITLE
window size settings is completely broken

### ISSUE THREAD

**Issue by waitingmoon** [libretro/RetroArch#7670]
As a title says, window size setting is completely broken on latest nightly.

Remember Window Positions is OFF:
Window width/height settings will be ignored and the window size is permanently fixed to 960x720.

Remember Window Positions is ON:
if the windows size is set to 1280x960, the value will be changed 1280x980 after restart retroarch. and retroarch adds 20 to the height every restart ( like 960, 980, 1000, 1020 ). 

@bparker06 
more info (its not my post)
https://egg.5ch.net/test/read.cgi/software/1528891875/698

OS: Windows 10 64bit 1803
Version: Lastest nightly

**Comment by fr500** [comment]
The first part is ok, it's 3x 320x240 which is the default framebuffer size.

As for the second part, the adding 20 stuff is really weird 🤣

**Comment by fr500** [comment]
Only height not width?
The only code that writes to the variable is:
https://github.com/libretro/RetroArch/blob/0b50328c6f67e1c8b2586f63c68569ec186efdc6/gfx/common/win32_common.c#L659

@twinaphex have you seen this happening? 
 
https://github.com/libretro/RetroArch/search?q=window_position_height&unscoped_q=window_position_height

**Comment by waitingmoon** [comment]
ok I understand... but The name of the option is "Remember Window Positions". Even if there is the description, I think this option should save only the window position. it is strange that the window size will be fixed at 960 x 720 and can't enable custom window size unless turn on the option.

yes, only height.

**Comment by fr500** [comment]
Well, we renamed to position and size now. It could be separated I guess.

Yeah I just figured that out myself, it only grows when the menubar is enabled

@twinaphex the window grows by menubar height on every start if the menu bar is enabled. I figure it's reading the value before the menubar is created and then it grows again or something.

No idea how to fix this properly.

**Comment by waitingmoon** [comment]
Update
The actual window size and the set size doesn't match.

![rawidthheight](https://user-images.githubusercontent.com/16256443/49235027-7ac8df80-f43c-11e8-80d3-c52b86721584.jpg)
Set size : 1280x960
Actual size：1266x953 ( includes window borders width/height, so viewport is more smaller )

**Comment by metchebe** [comment]
So, I see it probably has to do with this commit:

[only apply fixed window size when the setting is enabled](https://github.com/libretro/RetroArch/commit/aab6a86633c7d06b58010ce54ba6377afb3ee3f1)

I will test later. I did not notice a reference to this in the GUI tips/notes.

**Comment by fr500** [comment]
No, when @twinaphex added this new sizing method, he changed how the whole thing worked and now it needs to be implemented properly per-display-server.

So now it only works on windows so far.

**Comment by orbea** [comment]
I suppose an issue for the linux side was made here so I am going to close this.

https://github.com/libretro/RetroArch/issues/7677

**Comment by metchebe** [comment]
@orbea @waitingmoon now on Windows 7 32-bit, latest nightly (c8c23ffcfc), I get the exact **opposite**. Now `video_windowed_position_height` _decreases_ by 20px every RetroArch restart or loading/unloading of a game.

**Comment by metchebe** [comment]
Sorry but I've only just returned to using the Windows 7 PC (32 bit) where this happens. It's still happening on the 19-Feb build (59febcdb9c).

As a sidenote, there is no strange resizing in Linux/Ubuntu. Maybe it's only Windows 7 specific? I don't have Windows 10 to test. The old stable 1.7.5 works OK in Windows 7, so it seems whatever was needed to fix resizing in Windows 10 broke resizing in Windows 7.

Also pardon me but I don't know how to bisect. I can assume that the issue has to to with  this commit: e050ca89c7c9c06eded2cacb3c50a301883f8435 (I'm not a programmer so this is only a hunch).

**Comment by fr500** [comment]
@orbea I don't have a windows 7 system to check sadly but I don't see how this could happen I'm using the metrics the OS exposes.

**Comment by fr500** [comment]
@metchebe try with a clean config please. If that works then it's something in your settings.

**Comment by metchebe** [comment]
@fr500 a clean config works. I traced the issue to using threaded video 'on'. In fact, switching repeatedly between threaded video on and off also makes the window shrink as described.

**Comment by fr500** [comment]
That's.... weird

**Comment by fr500** [comment]
ok the problem seems to be that menubar doesn't work with video_threaded, and the calculation doesn't take this into account.

```C
static void win32_save_position(void)
{
   RECT rect;
   WINDOWPLACEMENT placement;
   int border_thickness     = GetSystemMetrics(SM_CXSIZEFRAME);
   int title_bar_height     = GetSystemMetrics(SM_CYCAPTION);
   int menu_bar_height      = GetSystemMetrics(SM_CYMENU);
   settings_t *settings     = config_get_ptr();

   memset(&placement, 0, sizeof(placement));

   placement.length         = sizeof(placement);

   GetWindowPlacement(main_window.hwnd, &placement);

   g_win32_pos_x = placement.rcNormalPosition.left;
   g_win32_pos_y = placement.rcNormalPosition.top;

   if (GetWindowRect(main_window.hwnd, &rect))
   {
      g_win32_pos_width  = rect.right  - rect.left;
      g_win32_pos_height = rect.bottom - rect.top;
   }
   if (settings && settings->bools.video_window_save_positions)
   {
      if (!settings->bools.video_fullscreen && !retroarch_is_forced_fullscreen() && !retroarch_is_switching_display_mode())
      {
         settings->uints.window_position_x      = g_win32_pos_x;
         settings->uints.window_position_y      = g_win32_pos_y;
         settings->uints.window_position_width  = g_win32_pos_width - border_thickness * 2;
         settings->uints.window_position_height = g_win32_pos_height - border_thickness * 2 - title_bar_height - (settings->bools.ui_menubar_enable ? menu_bar_height : 0);
      }
   }
}
```

```C
void win32_set_window(unsigned *width, unsigned *height,
      bool fullscreen, bool windowed_full, void *rect_data)
{
#if !defined(_XBOX)
   RECT *rect            = (RECT*)rect_data;

   if (!fullscreen || windowed_full)
   {
      settings_t *settings      = config_get_ptr();
      const ui_window_t *window = ui_companion_driver_get_window_ptr();

      if (!fullscreen && settings->bools.ui_menubar_enable && !video_driver_is_threaded())
      {
         RECT rc_temp;
         rc_temp.left   = 0;
         rc_temp.top    = 0;
         rc_temp.right  = (LONG)*height;
         rc_temp.bottom = 0x7FFF;

         SetMenu(main_window.hwnd,
               LoadMenu(GetModuleHandle(NULL),MAKEINTRESOURCE(IDR_MENU)));
         SendMessage(main_window.hwnd, WM_NCCALCSIZE, FALSE, (LPARAM)&rc_temp);
         g_win32_resize_height = *height += rc_temp.top + rect->top;
         SetWindowPos(main_window.hwnd, NULL, 0, 0, *width, *height, SWP_NOMOVE);
      }

      ShowWindow(main_window.hwnd, SW_RESTORE);
      UpdateWindow(main_window.hwnd);
      SetForegroundWindow(main_window.hwnd);

      if (window)
         window->set_focused(&main_window);
   }

   win32_show_cursor(!fullscreen);
#endif
}
```

So we can hack it (include video_is_threaded) in the size calculation...
or fix the menubar with threaded video

Thoughts @twinaphex ?

**Comment by fr500** [comment]
ok pushed a "fix"

Threaded on run 1:
![image](https://user-images.githubusercontent.com/1721040/53186723-940ea180-35cf-11e9-9796-57ad6c8f4ec8.png)

Threaded on run 2:
![image](https://user-images.githubusercontent.com/1721040/53186752-9e30a000-35cf-11e9-900e-da057787e907.png)

Non threaded run1 (notice that menubar does work in this case):
![image](https://user-images.githubusercontent.com/1721040/53186826-c7513080-35cf-11e9-9388-76cdf94fd797.png)

Non threaded run 2:
![image](https://user-images.githubusercontent.com/1721040/53186847-d59f4c80-35cf-11e9-9605-0612d10f3035.png)
