### ISSUE TITLE
Wii U Retroarch Cannot Disable Frame Counter

### ISSUE THREAD

**Issue by SBanya** [libretro/RetroArch#7687]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

"Frames" counter is on by default and cannot be disabled in any menu options and just counts the amount of frames shown.

### Expected behavior

This shouldn't even be shown by default, super unnecessary and annoying. Looks like a bug. Fix this.

### Actual behavior

Frames field keeps counting frames drawn on screen.

### Steps to reproduce the bug

1. Open Retroarch on Wii U (latest nightly build (11-30
2. Notice crazy frame counter

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by RobLoach** [comment]
I think this is fixed now.... Mind re-testing?

**Comment by 5schatten** [comment]
This commit fixed it for me https://github.com/libretro/RetroArch/commit/a617f0d43691e75d3ffd67e0049eee622f870486

**Comment by orbea** [comment]
Reported as fixed in the above commit so I am going to close this, please complain if its not actually fixed.
