### ISSUE TITLE
RetroArch meets segmentation fault when loading DOSbox games on 32bits PC

### ISSUE THREAD

**Issue by xuqingkuang** [libretro/RetroArch#7692]
## Description

I'm using RetroArch with in Lakka Linux running on a generic 32bits PC(Lenovo Q110 - Intel ATOM 230 + Nvidia ION), when try to load the DOS game `Theme Hospital` but RetroArch crash with segmentation fault.

In fact I tried another DOS game but all the same.

### Expected behavior

The game load normally.

### Actual behavior

RetroArch crashed.

### Steps to reproduce the bug

1. Downloada the game from https://gamesnostalgia.com/en/game/theme-hospital The game is wrapped with DOSBox. (I was download the Mac version) 
2. Extract the DOS game resources from the app, then copy to Lakka Linux.
3. Create the Dosbox config file - [dosbox.conf.txt](https://github.com/libretro/Lakka-LibreELEC/files/2636473/dosbox.conf.txt)
4. Create the playlist file - [DOS.lpl.txt](https://github.com/libretro/Lakka-LibreELEC/files/2636471/DOS.lpl.txt)
5. Start the game.
6. But RetroArch crashed and output the log - [retroarch-log.txt](https://github.com/libretro/Lakka-LibreELEC/files/2636470/retroarch-log.txt)

### Version/Commit

- RetroArch: [1.7.3/2a2e73]

### Environment information

- OS: Lakka Linux 2.2.1
- Compiler: *Sorry I will append the info later*

**Comment by RobLoach** [comment]
If you try it on DOSBox-SVN, does the same thing happen?

**Comment by xuqingkuang** [comment]
> If you try it on DOSBox-SVN, does the same thing happen?

How to switch to DOSBox-SVN in RetroArch ?!

**Comment by RobLoach** [comment]
Download Dosbox-svg from the core updater, and reset the core selection when choosing the item.

**Comment by orbea** [comment]
Can you provide a backtrace with debugging symbols both the core and retroarch?

**Comment by xuqingkuang** [comment]
@RobLoach @orbea

Sorry I just switch to the 64bits of Lakka linux and the Dosbox startup normally.

I hope that you can continue to tracking the issue, but for me it's gone.

Thanks a lot for your help.

**Comment by Qiyamah** [comment]
It continues.... nobody solved this problem....
