### ISSUE TITLE
Dynamic wallpapers not working with menu_horizontal_animation set to "false"

### ISSUE THREAD

**Issue by dfranusic** [libretro/RetroArch#7693]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Dynamic wallpapers not working with menu_horizontal_animation set to "false" 

### Expected behavior
Dynamic wallpapers should work as expected

### Actual behavior
Wallpapers are not changing, **bg.png** from the current theme is used for every playlist.

### Steps to reproduce the bug

1. Enable and setup dynamic wallpapers
2. Disable Horizontal animation in Settings/User Interface or by editing **retroarch.cfg** and setting **menu_horizontal_animation** to **"false"**.

### Bisect Results
Upon fresh install of Lakka 2.1.1

### Version/Commit
RetroArch: Frontend for libretro -- v1.7.3 -- 2a2e732 
Compiler: GCC (7.3.0) 32-bitBuilt: Jun 23 2018

### Environment information
- OS: Lakka (community): 2.1.1 (RPi2.arm)

**Comment by Tatsuya79** [comment]
It's known.
That's the same part of the code that does a deep copy which handles the animation effect, the dynamic wallpaper change, and also the playlist entry cartridge icon when you validate them once just before launching.

If someone wants to make them independent (I sure can't do that):
https://github.com/libretro/RetroArch/blob/master/menu/drivers/xmb.c#L1846
https://github.com/libretro/RetroArch/blob/master/menu/drivers/xmb.c#L1633
https://github.com/libretro/RetroArch/blob/master/menu/drivers/xmb.c#L5212

**Comment by orbea** [comment]
I have never used dynamic wallpapers before, can someone elaborate on step 1?

> Enable and setup dynamic wallpapers

I'm not sure I can fix this, but I'll at least give it a try.

**Comment by sonninnos** [comment]
Seems to be working just fine here already, so looks like closing time.
