### ISSUE TITLE
Eeprom in game save fails to load

### ISSUE THREAD

**Issue by eerie-king** [libretro/RetroArch#7702]
[failed to load .srm file example.zip](https://github.com/libretro/RetroArch/files/2651279/failed.to.load.srm.file.example.zip)
## Description

Emulation of eeprom save game (Boktai in this specific case) plays, is able to save, etc. but if you exit the game and return, you are unable to load the save and returns you to a wiped load screen. If exited to title screen, and load screen re-entered, save is still present, but has same result of failed load.

Issue encountered first with mGBA, but encountered with other GBA cores as well. Attempted to use Retroarch 1.7.3 and game save/load works normally, but if old core is moved to current build of retroarch 1.7.5 the failed load result remains.

Included .srm file used.

### Expected behavior

Expected behavior would be for the eeprom save to be able to load while in retroarch normally to resume play.

### Actual behavior

eeprom save fails to load when selected and then appears to wipe data, only for it to remain if load screen re-entered.

### Steps to reproduce the bug

1. Save game in eeprom save game (Boktai as example)
2. exit game fully.
3. restart core/game.
4. attempt to load saved game

### Version/Commit

- RetroArch: 1.7.5
- Git version: 826c77d523
- Build date: Oct 2 2018

### Environment information

- OS: Windows 10 Pro - 64 bit

**Comment by fr500** [comment]
Read the:

First and foremost consider this section of the report template.

**Comment by eerie-king** [comment]
If I've posted in the incorrect area I do apologize and would have to admit ignorance. My understanding of the issue lead me to believe it was an issue with RetroArch as I'd encountered the issue regardless of the core used. I found that the issue is not present in a previous version of RetroArch as well. 

Should I still post the issue elsewhere? If so, the direction would be very much appreciated. Sorry for any misunderstanding of course!

**Comment by eerie-king** [comment]
In discussing issue with others, the possibility of the RTC not being enabled in RA came up. Not certain of the possibility but wanted to include.

**Comment by fr500** [comment]
well it's posted already.
Do you have the issue with other games?

Because I have played several GBA games to completion in mgba libretro and I don't have this issue.

**Comment by eerie-king** [comment]
I have not had the issue with any other games that I've currently been running (about 5 total games on GBA). I generally only use mgba libretro as well. I'd not had any issues with it until I upgraded RA to 1.7.5, as previously i was using the 1.7.3 version. It's only this game that I've encountered the issue with, and I know it has eeprom saving though. Of course not certain if that is the issue.

**Comment by eerie-king** [comment]
and the saves load in the 1.7.3 version to clarify further.

**Comment by fr500** [comment]
on what platform are you running RetroArch.
the RetroArch version hardly ever has anything to do with the core saves.

**Comment by eerie-king** [comment]
Yes the same core. Encountered first with the current mGBA core (mGBA 0.7-b1 6db8583) and and also tried with the older core from 1.7.3 (mGBA 0.7 - wip d98de4a) with RA 1.7.5 and encountered the same issue. Tried both cores in both versions of RA i currently have. Only encountered issue in 1.7.5

**Comment by retro-wertz** [comment]
this seems like a core issue, or specifically how save data and size are passed to libretro.
for this game at least, its suppose to be using 8192  bytes eeprom, but mgba seems to be initializing a 512 bytes save for it hence some bytes are not written when you exit the game (even though after exiting the size becomes 8192 bytes)

from experience, libretro has to already know the size of save ram to use before the first retro_run() call, but that hasn't been the case here.

**Comment by orbea** [comment]
@eerie-king Can you use git to bisect between the `v1.7.3` and `v1.7.5` git tags? Build them both first to make sure you can reproduce the good and bad commits.

**Comment by orbea** [comment]
The git bisect will fail in that case, I think its worth making sure.

**Comment by eerie-king** [comment]
I'm more than happy to do so, though I would need a quick explanation on how to doso, or just a point in the right direction.

**Comment by orbea** [comment]
Sure, I can help explain how to accomplish this, but I do not know much about how to set up git or a build environment on windows, can you do this much already?

Assuming yes, first clone RetroArch.
```
git clone https://github.com/libretro/RetroArch
```
Now inside the new RetroArch directory, build the master and make sure its still broken.
```
./configure
make
```
Assuming its broken, try the `v1.7.5` tag next.
```
# first clean the repo
git clean -xdf

# now checkout the tag
git checkout v1.7.5

# and build it
./configure
make
```
I'll assume its still broken with this version, now repeat the above with `v1.7.3` to make sure it now works again.
```
# first clean the repo
git clean -xdf

# now checkout the tag
git checkout v1.7.3

# and build it
./configure
make
```
Assuming this works you can also try `v1.7.4` to see if that is a bad or good commit.

Please let me know when you are this far and ask if anything is unclear.

**Comment by eerie-king** [comment]
I took a look at git, and I sorry to say its a bit beyond me just in terms of understanding what it is actually if I'm being honest. Like I said i'm happy to do the bisect, but my lack of understanding of it might hold me back. I'm basically coming from position 0. I understand that I'd use git but beyond that not clear.

@retro-wertz i believe you had said off site that you'd been able to replicate the error in v1.7.5 correct? I don't know if you are able/willing to do the bisect on your end, and certainly wouldn't ask to put you out.

Again I'm happy to do it, but from looking at the info I'd really need a step by step "idiots guide." Which is frustrating as I do want to assist with remedying the issue.

**Comment by orbea** [comment]
I unfortunately lack the knowledge on windows to help you get it set up, once its set up it should be easier to guide you through it.

Basically, step one is to build RetroArch yourself from the source code, you want to check the current master to make sure its not yet fixed, `1.7.3` to make sure that still works and then `1.7.4`/`1.7.5` to confirm those are still broken.

Using precompiled builds may not give us clear results of where and when the issue first started.

**Comment by eerie-king** [comment]
Issue now fixed with current mgba core. Saves working correctly!

**Comment by retro-wertz** [comment]
actually there are still games having save related issue awhile back in discord for games using flash either that would be fixed from upstream (add probably database for these rare sized games) or libretro itself would allow to re-initialize the save ram if size changes occurs (which is suppose to be possible already by changing the autosave time and then resaving the game) but that should happen realtime.
