### ISSUE TITLE
How to disable frame count?

### ISSUE THREAD

**Issue by Sunderland93** [libretro/RetroArch#7706]
## Description

Frame count shows after start RetroArch

![2018-12-06 17-43-39](https://user-images.githubusercontent.com/11344982/49587900-b0128780-f97e-11e8-8981-01432b961547.png)

How to disable it?

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.5 master

### Environment information

- OS: Debian Sid]
- Compiler: GCC 8.2

**Comment by rsn8887** [comment]
Settings->Onscreen Display->Onscreen Notifications->Display Frame Count->OFF

**Comment by Sunderland93** [comment]
Thanks!

**Comment by reda-benhemmouche** [comment]
This option should be disabled by default!

**Comment by hmslima** [comment]
> This option should be disabled by default!

I absolutely agree!

**Comment by madmax2** [comment]
@rsn8887

This setting is not available in v1.9.0
Settings->Onscreen Display->Onscreen Notifications->Display Frame Count->OFF

Where can i find it now?

**Comment by alastajj** [comment]
This option is missing, where is it now? Thanks

**Comment by madmax2** [comment]
@alastajj this is like looking for a needle in a haystack, 
there is too many settings that are buried deep in many layers.

Anyway I finally found the location

**Settings > On-Screen Display>On-Screen Notifications > Notification Visibility>Display Frame Count [Toggle OFF]**
