### ISSUE TITLE
Certain keyboard assignments not flowing to retropad

### ISSUE THREAD

**Issue by rwebb616** [libretro/RetroArch#7709]
## Description

When setting certain keyboard controls in retroarch.cfg they do not get assigned in the retropad based on looking in the RGUI settings / input menu

### Expected behavior

I expect that when a control is assigned in retroarch.cfg that the control will flow over to the virtual retropad.

### Actual behavior

This is an example - when input_player1_a is set to "lctrl" it shows as "---" in rgui under player 1 binds.  This causes issues with menu_unified_controls="true" because without the a button you cannot navigate the RGUI menu.  If you set it to just "ctrl" or "alt" it will assign properly.   It appears to only happen with the discrete left and right ctrl/alt/shift button assignments

### Steps to reproduce the bug

1. edit retroarch.cfg and change input_player1_a to "lctrl"
2. launch a game and activate the menu and go under settings / input / player 1 binds
3. button 1 will show "---" indicating no assignment

### Version/Commit

Retroarch Build Date 10/9/2018
Git version: c9c6c5a
Retroarch Version: 1.7.5

### Environment information

- OS: Retropie 4.4 under Raspbian Stretch
- Compiler: n/a

**Comment by hizzlekizzle** [comment]
That's because there is no "lctrl", only "[ctrl](https://github.com/libretro/RetroArch/blob/4d12eaf6855b57172349196b25554eb0653328e7/input/input_keymaps.c#L184)" and "[rctrl](https://github.com/libretro/RetroArch/blob/4d12eaf6855b57172349196b25554eb0653328e7/input/input_keymaps.c#L250)"

RetroArch can only respond to keynames it understands.

**Comment by rwebb616** [comment]
Maybe then it shouldn't be listed in the retroarch.cfg file as a valid key...
