### ISSUE TITLE
In RGUI items 'Scan directory' and 'Scan file' are always visible in the Collections menu

### ISSUE THREAD

**Issue by JabberwockPL** [libretro/RetroArch#7713]
## Description

There seems to be no way to hide the items 'Scan directory' and 'Scan file' from the Collections menu in RGUI.

### Expected behavior

When the option Show Import content Tab in the User Interface > Views is set to OFF, the relevant items in the Collections menu (Scan directory/file) should also be hidden for uncluttered, playlist-only interface.

### Actual behavior

In Collections menu in RGUI 'Scan directory' and 'Scan file' are always visible and always at the top of the menu.

### Steps to reproduce the bug

1. Select Load Content in RGUI.
2. Select Collections

### Version/Commit

1.7.3

### Environment information

- Angstrom Linux 2.6

**Comment by markwkidd** [comment]
I see this behavior in Windows x64.

1. Go to the `Views` menu, and I disable `Show Import content Tab`
2. Return to the top level of the RGUI menu: the content scanner **does** disappear from this level of the menu, as expected
3. Enter the `Load content` menu, then enter the `Collections` menu.
4. **The content scanner is still accessible here**

The logical behavior would be to have the scanner disappear from both places where it is accessible when the user chooses to hide it.

**Comment by markwkidd** [comment]
Awesome, that does indeed look like it would do the trick

**Comment by markwkidd** [comment]
This patch has made it into the latest buildbot nightly where I can confirm it works as described. Thanks @jdgleaver !

**Comment by hizzlekizzle** [comment]
Ok, if this has been resolved, I'll close the issue but feel free to reopen if there's still any remaining problems.

**Comment by JabberwockPL** [comment]
Thanks for the patch, @jdgleaver !
