### ISSUE TITLE
Save States Did Not Carry Over After Installing Latest Nightly Build Of Retroarch (Wii U)

### ISSUE THREAD

**Issue by SBanya** [libretro/RetroArch#7719]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Save states not carrying over into latest nightly build.

### Expected behavior

Save states should carry over since its part of my ROMs directory that never changed.

### Actual behavior

I only updated the Retroarch cores for the latest nightly builds, so I'm not sure why my save states are not being recognized.

### Steps to reproduce the bug
1. Replace my Wii U folder and Retroarch folder with newest nightly build files, but keep ROMs folder in the same location.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
It does, nothing related to states has changed.
Most likely you don't have a dir set properly.

**Comment by SBanya** [comment]
Please help though, since I have kept the Chrono Trigger U [!].smc and Chrono Trigger U [!].srm in my roms folder.

What can I do in my case? Do I have to rescan a directory or something related to saves?

I ask because I just copied and pasted all of my Chrono Trigger roms just in case from the same SD card, and tried to maybe instead use the PC version of Retroarch, but it didn't detect the default battery save at all :0

My issue is that the game in question, Chrono Trigger, was saved in game like a normal SNES cartridge, so this isn't a matter really of save states but of RetroArch failing to load the battery save itself.

I stress that this is important since my girlfriend was playing this game and has saved it in Retroarch directly within the game itself without save states, so if the default battery saves don't work, I'm not sure what to do.

**Comment by SBanya** [comment]
Unless, the save states are stored in the cores themselves though. In that case, I had replaced the cores with the new nightly build :0

**Comment by fr500** [comment]
Where are the states?
Are the states still there?

You don't need to copy anything.
You just need to have the states/saves in the folders that are defined under `settings/directories`.

**Comment by SBanya** [comment]
Luckily (for any future reader of this issue), there was a trash folder on my SD card. Thank God there was the folder that was overwritten (though I'm not sure this would have shown up in Windows since I'm using Lubuntu).

That being said, you're right, its in its own directory, but unfortunately it was in the cores related folder, so I had copied and pasted the entire new core with its own EMPTY save state folders. Now I know to just literally pay attention, and backup save data as well.

**Comment by orbea** [comment]
I suppose the solution is to not blindly copy files over? I'm not sure this is enabled on wiiu, but on Linux you should be able to set the save and save state directories to different directories to reduce this risk.

As this seems resolved I am going to close this, please let me know if I'm mistaken.
