### ISSUE TITLE
Add Show/Hide Options for Start Streaming and Recording

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#7739]
In the latest nightly there is no option to show/hide Start Streaming or Start Recording from the Quick Menu under Settings, User Interface, Views, Quick Menu.

**Comment by orbea** [comment]
I added a PR to address this which works here, but please let me know if I missed anything.

https://github.com/libretro/RetroArch/pull/7740

The options `Stop Recording` and `Stop Streaming` are intentionally not hidden so users are not silently recording or streaming without realizing.

**Comment by Awakened0** [comment]
Looks good to me!
