### ISSUE TITLE
Ozone Disappeared from Menu Driver

### ISSUE THREAD

**Issue by 6alileo** [libretro/RetroArch#7741]
## Description

Ozone is no longer on the list of menu drivers after updating to most recent source (bd2fb04)

### Expected behavior

Ozone to appear

### Actual behavior

The GL menu driver is being used by default.

### Steps to reproduce the bug

1. Recompile RetroArch
2. Launch a game
3. Invoke Quick Menu via Hotkey

### Version/Commit
You can find this information under Information/System Information

- RetroArch: bd2fb04

**Comment by 6alileo** [comment]
Ubuntu 16.04.3 LTS (GNU/Linux 3.10.105-141 armv7l) running RetroPie

config.mk -> https://hastebin.com/foficavogo.makefile

**Comment by orbea** [comment]
Well, I'm not sure. From what I can read in the code you should be building ozone and you should be able to toggle it.

Can you confirm a few things?

* Can you see files in `menu/drivers/ozone/` in the compile output?
* Can you test with a fresh config?
* If the above doesn't work can you try bisecting with git?

**Comment by 6alileo** [comment]
That path isn't generated -> http://oi63.tinypic.com/2dmclf5.jpg

Fresh config has the same issue. I know when I compiled on 12/02/2018, Ozone worked but there has been a lot of commits after that.

I'm not sure if its filtering based on device.

**Comment by 6alileo** [comment]
OK I think I figured it out. The main package is pointing to the v1.7.5 branch. I need to compile the master branch.

**Comment by orbea** [comment]
Yes, it seems you were on the wrong version. With the git repo you can use these steps to make sure you are on the current master if something goes wrong.

```
# Check that your remote repos are correct.
git remote -v

# Assuming origin points to https://github.com/libretro/RetroArch

# First fetch any new changes
git fetch origin

# Now clean the repo of untracked files
git clean -xdf

# Now reset it to the current master 
git reset --hard origin/master
```
