### ISSUE TITLE
Slowdown snes9x 1.57

### ISSUE THREAD

**Issue by marleyap** [libretro/RetroArch#7744]
Hello users Retroarch , wanted to do a little information about a drop of frames in snes9x 1.57 in the game Megaman X2, more precisely in the DEEP SEA BASE stage, in the part where I left that big robot fish, this fall of frames happens in TV box amilogic s905x 1.5 GHz, this drop is in the range of 2 fps less than full speed, now I do not know if it is due to lack of hardware of my tv box or lack of core optimization snes9x in tv box s905x, I wonder if programmers could solve this problem , even because the FX games run smoothly, without dropping frames ... Thank you all!

**Comment by marleyap** [comment]
I'm having the core updates snes9x 1.57 in the download options nightly Linux ARMHF, I use the Lakka OS 2.1.1 version for TV android box with AMILOGIC S905X processors, 1.51 GHZ AND with 1 GB RAM, I tested on two TV box models, the two present slowndonw in the certain bubble crab phase of the game Megaman X2, in the part when it appears that when Big robot fish the game has fall in up to 58 fps, and also tested with old standard SNES9X core that comes in the LAKKA OS in the case of Snes9x 1.54 .1 frame crashes are worse, reaching up to 54 fps, now my doubt is if this happens for lack of optimization of the updated snes9x core for TV box s905x or lack of TV box hardware that I use. Stranger than games with Fx chips that are much heavier to emulate than Megaman X2's Cx4 chips and without the use of the video threading option run like a feather without gagging anything at all.

**Comment by RobLoach** [comment]
Could you make an issue in the snes9x issue queue? Thanks!

**Comment by orbea** [comment]
The upstream repo and issue tracker is here.

https://github.com/snes9xgit/snes9x

**Comment by marleyap** [comment]
aparelho...

( atualização ) acabei de testar a atualização snes9x libretro,na qual já é a versão 1.58, o slowndonw diminuiu levemente, agora está em tornos de 1.2 fps a menos da velocidade total, tento quedas até 58,8 fps, ainda dar pra sentir uma leve ruído e lentidão no áudio no jogo e parte do jogo que citei anteriormente no meu TV box. espero que corrigem logo isso creio q é uma pequena falta de optimização do núcleo para o processador do meu aparelho...
(update) I just tested the update snes9x libretro, which is already version 1.58, slowndonw has decreased slightly, now it is in 1.2 fps less than full speed, I try to drop up to 58.8 fps, still give a feeling slight noise and slowness in the audio in the game and part of the game I quoted earlier in my TV box. I hope they correct it soon I think it is a small lack of optimization of the core for the processor of my device ...

**Comment by orbea** [comment]
Thanks, I think this issue is core specific so I am going to close this issue. Lets continue the discussion in your other issue.

https://github.com/snes9xgit/snes9x/issues/461
