### ISSUE TITLE
Gamepad "overlay" does not scale properly/automatically with screen rotations in Android

### ISSUE THREAD

**Issue by singularity098** [libretro/RetroArch#7746]
## Description

The gamepad touch overlay does not scale properly when the screen is rotated in Android.  Fortunately there is a rotate icon in the overlay to change the scaling to match the screen rotation, but this should happen automatically.  It's a small issue but things like this can drive users away from RetroArch very quickly.

It is likely this exists on iPhone as well, but I do not own one so cannot test this.

### Expected behavior

When screen is rotated in Android, the touch overlay should change its scaling layout to match the screen orientation.

### Actual behavior

Screen overlay is stretched and misshaped when screen is rotated.

### Steps to reproduce the bug

1. Enable gamepad touch overlay.
2. Load game.
3. Rotate screen... note the gamepad will be squished and misshapen.
4. Press rotate icon in overlay to workaround the issue.

### Bisect Results

Has been an issue as long as I remember.

### Version/Commit

- RetroArch: v1.7.5

### Environment information

- OS:  Android Oreo

**Comment by illando** [comment]
I can confirm it happens the same on iOS.

**Comment by hizzlekizzle** [comment]
@singularity098 or @LibretroAdmin I think this can be closed now, since we have the automagic overlay switching on rotation.
