### ISSUE TITLE
RetroArch Web - DOSBox Core - RuntimeError on launch

### ISSUE THREAD

**Issue by lrusso** [libretro/RetroArch#7757]
Tested Firefox (version 64.0 in 64 bits) in MacOS High Sierra (version 10.13.6). RuntimeError when starting DOSBox core.

![screenshot](https://user-images.githubusercontent.com/11498901/50058234-16a05e00-0154-11e9-9d02-93ede67ba7cd.png)

**Comment by fr500** [comment]
This is... a won't fix, threading support in emscripten is limited and I don{t have the skill to rewrite dosbox without libco.

Also core issue, please close (dthe core should be removed from the buildbot)
