### ISSUE TITLE
[XMB] missing mame2003-plus Icon

### ISSUE THREAD

**Issue by 5schatten** [libretro/RetroArch#7764]
## Description

It looks like mame2003-plus is still missing a propriate icon in the XMB menu of Retroarch? It looks like a generic placeholder/rocket.

https://github.com/libretro/mame2003-plus-libretro/issues/543
@markwkidd 

### Expected behavior

The icon should look like a small mame logo with release year like mame2010 has.

### Actual behavior

The icon looks like a rocket.

### Steps to reproduce the bug

Scrape/scan some games that are covered by the mame2003-plus db & you'll see a rocket icon for mame2003-plus.

### Version/Commit

https://github.com/libretro/RetroArch/commit/af0bf7a99200c8bfcf30b286aa3d0e454fbea163

**Comment by orbea** [comment]
I think the correct repo to report this is https://github.com/libretro/retroarch-assets.

**Comment by 5schatten** [comment]
@orbea well if someone could point me to the final repo... that would be great ;-)

**Comment by orbea** [comment]
Here. https://github.com/libretro/retroarch-assets/issues

**Comment by 5schatten** [comment]
Okay I've created an issue at the assets repo.

**Comment by orbea** [comment]
For reference the new issue is here https://github.com/libretro/retroarch-assets/issues/263.
