### ISSUE TITLE
(Win64) Blargg NTSC filter weirdness on SNES pseudo-hires screens

### ISSUE THREAD

**Issue by GPDP2** [libretro/RetroArch#777]
So I am honestly not sure if the issue lies with the filter, the new filter API, or the Snes9x core, but just to be safe, I am posting the issue here.

Basically, I was testing out the Blargg NTSC filter on the Snes9x core (which, by the way, does not seem to softlock anymore, which is good), and everything was fine. Then I remembered on the previous implementation of the filter, screens that used pseudo-hires for transparency and such were blended together, much like the snes-hires-blend shader does, so I decided to try it out again. However, upon trying Kirby's Dreamland 3, which runs in pseudo-hires on some screens, the result is that the screen gets squished onto the left side of the display (although transparency does get blended). The right hand of the screen, meanwhile, shows a glitched status bar. I then tested Secret of Mana, which also sometimes displays in pseudo-hires, and likewise, the screen is squished onto the left side, though without anything showing on the right side.

If I recall correctly, the previous filter implementation did not have these issues. You could load Blargg's filter on either bsnes or Snes9x, and no such squishing occurred.

**Comment by twinaphex** [comment]
Can you re-test this? If it happens again, make a new issue. Until then, closing this since it's quite an old issue.
