### ISSUE TITLE
Cannot set different directories for Screenshots and Recordings

### ISSUE THREAD

**Issue by vpontin** [libretro/RetroArch#7776]
## Description

Basically, seems like RetroArch 1.7.5 for Windows - although have two different entries on config file to store screenshots (`screenshot_directory`) and recordings/captures (`recording_output_directory`) in diferent paths - cannot persist different paths for screenshots and recordings output when setting the directory using the GUI. 

![image](https://user-images.githubusercontent.com/3485505/50259434-369d7f00-03eb-11e9-915d-52bc440c3b47.png)

### Expected behavior

The user be able to set each directories independently.

### Actual behavior

When setting one, the other is affected automatically (and vice-versa).

### Steps to reproduce the bug

1. Open retroarch in the standard UI mode;
2. Go to `Options > Input`
3. Try to set OR screenshots OR recordings directory; when you change one the other automatically changes to the same value too, even having separate entries both in UI and in `retroarch.cfg`.

### Version/Commit
- RetroArch: 1.7.5 for Windows x86_64

### Environment information

- OS: Windows 10 1803 x64
- Compiler: Downloaded from retroarch.com

**Comment by orbea** [comment]
Can you confirm if this happens with the nightlies?

**Comment by orbea** [comment]
I can reproduce this actually.

**Comment by orbea** [comment]
I submitted a PR to fix this, it works correctly here, but please let me know if I missed anything.

**Comment by fr500** [comment]
I kinda did it like this on purpose :P
I'm lazy you know :P

**Comment by orbea** [comment]
Lol, if you have a better suggestion I am all for it, but I think this might of been the reason why my screenshots where sometimes ending up in the wrong location...

**Comment by fr500** [comment]
I use the same directory so it may be a mistake after all
As long as both dirs are working properly now, all good.

**Comment by orbea** [comment]
It seems to be working, the only question I have left is what is the difference between `MENU_ENUM_LABEL_VALUE_DIRECTORY_CONTENT` and `MENU_ENUM_LABEL_VALUE_DIRECTORY_DEFAULT`? I left that alone for now, but should it be changed to `MENU_ENUM_LABEL_VALUE_DIRECTORY_DEFAULT` like the other use of `MENU_ENUM_LABEL_RECORDING_OUTPUT_DIRECTORY`? Or is it fine to leave it as is?

**Comment by fr500** [comment]
Hmmm MENU_ENUM_LABEL_VALUE_DIRECTORY_CONTENT should be for the content dir so that may be wrong.

I don't really know about the enums, I did fix recording but I am as clueless as anyone else on the menu :P

**Comment by vpontin** [comment]
Thanks! Where can i find the latest builds (for Win x86_64) for testing?

**Comment by orbea** [comment]
You can find download links here. http://www.retroarch.com/?page=platforms

@fr500 I'll try to grep around and see if I can make sense of it better, but it doesn't seem to be causing problems that I can see at least.

**Comment by orbea** [comment]
@fr500 So I kind of figured it out, when the config setting is unset it will show either `<Content dir>` or `<Default>` accordingly. However in practice the mkv file ends up in the current directory I started RetroArch in either way...
