### ISSUE TITLE
Ubuntu nightly PPA way out of sync with buildbot

### ISSUE THREAD

**Issue by Nine-H** [libretro/RetroArch#7777]
## Description

When I update my system with the libretro/nightly I get versions of cores that are sometimes months out of date, there's no way to download the cores with the online updater, which is this bug #6919 and I don't want to have to write a script that pulls them off the buildbot (because I've been doing that manually and it's a pain and they're not signed).

### Expected behavior

I update my system on nightly and I have nightly or something close to it (I understand the limits of crontabs)

### Actual behavior

I update my system and many cores are months out of date

### Steps to reproduce the bug

use retroarch from PPA on ubuntu.

### Environment information

- OS: Ubuntu 16.04 and 18.04
- Compiler: N/A, it's a remote packagebuild issue.

**Comment by orbea** [comment]
Please bring this up with the PPA maintainer, we don't directly support distro packages here. Given this is not our bug I am going to close this.

If you want to work around this, please follow these steps.
```
git clone https://github.com/libretro/RetroArch/
./configure
make
./retroarch
```
