### ISSUE TITLE
MXQ PRO 4k S905x p212 - have various bugs for me

### ISSUE THREAD

**Issue by kryspus** [libretro/RetroArch#7778]
I have installed sugested by lakka rom for s905 devices. I dont swap the dtb file for "x" vesrion s905, becouse after i tryed the oryginal one its runned up to RetroArch (GUI interface), so i asume its not needed.
And here is it few bugs i have and i can't fix it by myself.
1. Cant connect to wi-fi, in GUI interface when i navigate to into Wi-FI setup its showing only WiFi icon with "[]" (a space), when i click "ok" there is showing Phaseprasse to enter. 
Wired connection work fine, so I instaled PuTTy and tryed the solution from FAQ, and stuck at this:
```
connmanctl
Error getting VPN connections: The name net.connman.vpn was not provided by any connmanctl> agent on
Agent registered
```
2. The bluetooth conection don't work. I have connected my PS3 controler and its showed up "conected to port #0)" 
```
Lakka:~ # bluetoothctl
[bluetooth]# agent on [WORK]
[bluetooth]# default-agent [WORK]
[bluetooth]# power on
No default controller available [<-- [Problem]
[bluetooth]# discoverable on
No default controller available
[bluetooth]# pairable on
No default controller available
[bluetooth]# scan on
No default controller available
```
3. I have placed my commodore games in ROMs folders, and perform scaning, after it finally finished there is no new tabs, but i could bypass this by Loading Core (PS1 games case) and Load Content manually.

4. Games start but there is no controller who works in the game. L3+R3 work fine for the RetroArch menu, but in game work nothing, i just see the loaded first screen.
In Playstation 1 case i runed Colin and i was able to move in the menu (not tested further)

Due a lot of (fundamental) function is not working for me i wonder do i do it all right and maybe its some other version for my device i should try, or i doing some main thnig wrong? http://le.builds.lakka.tv/S905.arm/?C=M&O=D 

Device:
MXQ PRO 4k S905x p212
System information:
Build date: Jun 23 2018
Git: 2a2e732
GCC (7.3.0) 32-bit
NEON VFPv3 VFPv4 ASIMD
ARMv8
unix
Lakka: S905.arm-2.1.1
Linux (v3.14)
RetroRating level : -1
Video content driver: mali-fbdev
...

Sorry for my english, and forgive me if i don't do research i should before writing here.

**Comment by gouchi** [comment]
This issue is more related Lakka, please open an [issue](https://github.com/libretro/Lakka-LibreELEC/issues) to the dedicated repository.

Thank you.

**Comment by orbea** [comment]
Given that this is a lakka issue and the new issue has already been made I am going to close this.

Please discuss this further here. https://github.com/libretro/Lakka-LibreELEC/issues/578
