### ISSUE TITLE
RGUI White Screen in GL and Crashing in D3D

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#779]
By some reason my RGUI do not working

In opengl is just a white screen,in d3d the window appears,later the white of not responsive and then crashed

i using the retroarch 1.0.0.2 with the megapack,everything for x64

my pc is a windows 7 ultimate x64,with Intel 82945G Express Chipset Family,with Intel Pentinum Dual of 4GHz,with 3,00GB of RAM,with DirectX 11.

**Comment by tallpr24** [comment]
Hey guys,
new to mame here.
I'm using mame0.816ui. My Xbox 360 controller wireless keeps losing the config in Mame.  I thought it was happening when I launched mame without my controller turned on but tried it again today and lost the config again even though the controller was on.  

any suggestions?

**Comment by hizzlekizzle** [comment]
@tallpr24 
This isn't the right issue to ask such a question in. In fact, a better place for your question would be the libretro forums. If you don't mind registering over there, we'll try to get you fixed up.

**Comment by tallpr24** [comment]
Thanks, can you provide url for that tread?
