### ISSUE TITLE
[Usability Improvement] Android "glui" menu driver should respond to the system's "back" button

### ISSUE THREAD

**Issue by singularity098** [libretro/RetroArch#7791]
## Description

The glui menu driver on Android does not respond to the system's "back" button.  Instead it behaves more like an iPhone where the user does not have a back button and the button is drawn somewhere else on the screen.  This makes the app feel extremely awkward to use, when every other application on your phone has a standardized behavior which RetroArch violates.

### Expected behavior

1. Whenever a back button appears in the menu, the system's back button being pressed should produce an identical action and "go back".
2. When the user is at the front/main menu and presses the button, the back button should minimize (but not "quit") the application.

These above two changes should make the application feel more like a native Android app... and likely prevent people from getting confused and then turning around to spend $1.99 on some other app that is running the same copied backend as RetroArch.

### Actual behavior

Back button does nothing.

### Version/Commit

- RetroArch:  v1.7.5

### Environment information

- OS:  Android

**Comment by orbea** [comment]
It turns out there is a previous issue for this, so I am going to close this in favor of issue https://github.com/libretro/RetroArch/issues/7791.
