### ISSUE TITLE
Games can be saved to the history list with the incorrect title

### ISSUE THREAD

**Issue by singularity098** [libretro/RetroArch#7792]
## Description

It is possible to save games to the history list with the incorrect title.

### Steps to reproduce the bug

1. Load up some game via an already existing playlist.
2. Now open up the menu and then load a second game, NOT through a playlist this time, but instead via "Load Content" menu.
3. The second game which was loaded will be saved to the history playlist with the title of the first game.  Something must be going wrong with the logic when the first game has a defined title from the playlist, but the second game does not have any defined title because it was loaded directly from the file picker.

### Version/Commit
You can find this information under Information/System Information

- RetroArch:  v1.7.5

### Environment information

- OS:  Ubuntu Linux v18.10

**Comment by retro-wertz** [comment]
duplicate : https://github.com/libretro/RetroArch/issues/6913

**Comment by orbea** [comment]
I'm going to close this in favor of issue https://github.com/libretro/RetroArch/issues/6913.

@retro-wertz Thanks for pointing out the duplicate issue.
