### ISSUE TITLE
Parent directory of a top level directory on a mount-point is RetroArch dir

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#7803]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The parent dir of a top-level directory seems to be borked.
Example:

[x] C:\roms\snes -> parent directory
[x] C:\roms -> parent directory
[x] C:\ -> parent directory
[ ] path:\to\retroarch\ ?????

![image](https://user-images.githubusercontent.com/1721040/50385543-5233ae80-06a5-11e9-992e-16873ba2813d.png)

![image](https://user-images.githubusercontent.com/1721040/50385544-54960880-06a5-11e9-9f0c-04ad6f9f5a07.png)

### Expected behavior

It should go to a list of mount points or drives so you can navigate to another one
This makes it impossible to load shaders, remaps, overlays, append disks, etc on another drive.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
Seems to work fine with Linux.
![linux1](https://i.imgur.com/DpzeurA.png)
![linux2](https://i.imgur.com/KhIAyL8.png)

**Comment by fr500** [comment]
Thanks for testing, so windows only issue (darn)

**Comment by krzys-h** [comment]
Tried to bisect this since it bothers me when working on the UWP storage but it looks like the oldest version I could download (1.6.7) still has this bug, and what seems to be relevant code in file_path.c hasn't changed since it was introduced in https://github.com/libretro/libretro-common/commit/e3d635f24c3d59867493b4b3c1fe41c41e679915 so I assume it existed for a long time

**Comment by fr500** [comment]
Thank you @krzys-h
