### ISSUE TITLE
[Ozone] Crashes when enabling 'menu_use_preferred_system_color_theme'.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#7805]
## Description

RetroArch crashes on my system when using the `ozone` menu driver and then enabling `menu_use_preferred_system_color_theme`.

### Expected behavior

For RetroArch to not crash.

### Actual behavior

```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
ozone_restart_cursor_animation (ozone=0x13db900)
    at menu/drivers/ozone/ozone_display.c:94
94     memcpy(ozone->theme_dynamic.cursor_border, ozone->theme->cursor_border_0, sizeof(ozone->theme_dynamic.cursor_border));
(gdb) bt
#0  ozone_restart_cursor_animation (ozone=0x13db900)
    at menu/drivers/ozone/ozone_display.c:94
#1  0x00000000005cc2d5 in ozone_context_reset (data=0x13db900, is_threaded=false)
    at menu/drivers/ozone/ozone.c:412
#2  0x00000000005db11d in menu_driver_context_reset (video_is_threaded=false)
    at menu/menu_driver.c:2098
#3  0x00000000005db150 in menu_driver_init (video_is_threaded=false)
    at menu/menu_driver.c:2106
#4  0x000000000047dc07 in drivers_init (flags=1023) at driver.c:386
#5  0x00000000004162ba in retroarch_main_init (argc=1, argv=0x7fffffffe208)
    at retroarch.c:1390
#6  0x000000000042ff17 in content_load (info=0x7fffffffe0d0)
    at tasks/task_content.c:281
#7  0x0000000000431178 in task_load_content (content_info=0x7fffffffe0d0,
    content_ctx=0x7fffffffdfe0, launched_from_menu=true, launched_from_cli=true,
    error_string=0x7fffffffdfd8) at tasks/task_content.c:889
#8  0x00000000004325f6 in task_load_content_callback (
    content_info=0x7fffffffe0d0, loading_from_menu=true, loading_from_cli=true)
    at tasks/task_content.c:1571
#9  0x00000000004327a1 in task_push_load_content_from_cli (core_path=0x0,
    fullpath=0x0, content_info=0x7fffffffe0d0, type=CORE_TYPE_PLAIN, cb=0x0,
    user_data=0x0) at tasks/task_content.c:1639
#10 0x0000000000412881 in rarch_main (argc=1, argv=0x7fffffffe208, data=0x0)
    at frontend/frontend.c:125
#11 0x0000000000412904 in main (argc=1, argv=0x7fffffffe208)
    at frontend/frontend.c:169
```
Full GDB log - https://pastebin.com/KV3usSWU

### Steps to reproduce the bug

1. Enable the `ozone` menu driver.
2. Set `menu_use_preferred_system_color_theme = "true"` in `retroarch.cfg`.
3. Try starting retroarch.

### Bisect Results

N/A

It also crashes in commit c00d3e809aa7f9ac085906f31aa8c01581426405 which is the first commit that will build after this feature was added in commit 689e612af83ebd92d25f2e813dec993188d09a60. However this earlier crash was in a different part of the code.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/0d7cb7edc22f37c2805a6dadf3b72d9050cb0362

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.2.0`

**Comment by fr500** [comment]
That should be switch only actually, it refers to the switch OS theme

**Comment by orbea** [comment]
I guess we can hide the option behind an ifdef?

**Comment by fr500** [comment]
Unless you can find a way to query the system theme for windows, kde,
gnome, etc :P

**Comment by orbea** [comment]
That could be nice, but I see your point that it would not be easy...
