### ISSUE TITLE
[intl] Arabic renders as boxes

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#7822]
## Description

When selecting languages Arabic appears as only boxes.

### Expected behavior

Arabic should be rendered.

### Actual behavior

![arabic](https://i.imgur.com/9NutuEe.png)

### Steps to reproduce the bug

1. Go to `Settings -> User -> Language` and then scroll through all languages until boxes appear.

### Bisect Results

This never worked, I bisected this and found it started when Arabic support was merged.
```
commit 45580cb9a8f0fcd0a87f00eadf26d87f05289485
Author: aliaspider <aliaspider@gmail.com>
Date:   Mon Feb 5 20:54:55 2018 +0100

    add basic support for arabic.

:100644 100644 fcf90a92d9c0db4cc8bb44528f4df26512bab609 498be0f8889dc4ecfb78649bb324aea573074477 M	Makefile.common
:040000 040000 8acbd24ccbb7a7e1c50ce8a08f412ca9349076e2 5baf5404bf531d536145dc9da1868c8dd7083512 M	gfx
:040000 040000 e59db4e8ad19e17801a80813bb50a25a8b296449 1aac59f0f6d36935482ec17ffd9289cb00af3f1b M	griffin
:040000 040000 a82bd80dba3c3edb5beb17706925bd713d09c28c c0d1ec0a714af68e7cb59d41b0402a9d75a12c5a M	intl
:040000 040000 ced06bef085d83db752894e810585bb45d5c2fe4 1e0684e6b37c82845e7171dc82fd76c4d2de21fc M	libretro-common
:040000 040000 83faddb6bc1242a1beee542323e1ba9ecb49d7d1 7ff985531043d3dc44af0fadc7dfce35be598887 M	menu
:100644 100644 1ce3f6bc33f15cd92985e1855320676c822a4bc9 37a871b2228fe27f3f8ac8387e16ab7a5e3fff77 M	msg_hash.c
:100644 100644 91673d48f35e23a1721dc88c367f0eef7e9ef0e3 db3bbb9125bfd37c99611b4c61bfb2dcd1b745f2 M	msg_hash.h
```
45580cb9a8f0fcd0a87f00eadf26d87f05289485

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/fcf75fda170ede591cb37361f8a41a8f25f37404

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.2.0`

**Comment by orbea** [comment]
@aliaspider Can you please look at this?

**Comment by alfrix** [comment]
The monochrome font doesn't have support for arabic characters, you need to provide your own font
Retrosystem theme uses Dejavu Sans, which does have them (but doesn't have japanese unlike the default)
![captura](https://user-images.githubusercontent.com/1247237/50446264-f65e6500-08f2-11e9-86ed-7ce5d9e57922.JPG)

**Comment by orbea** [comment]
Thanks for the information, but since all the other languages are supported by the default font maybe there is something that be done here to improve this?

**Comment by bparker06** [comment]
@orbea The monochrome font doesn't support Chinese either... you only get glyphs that happen to be unified with Japanese.

**Comment by orbea** [comment]
Good point, I didn't notice that one.

**Comment by orbea** [comment]
Maybe Greek too? https://github.com/libretro/RetroArch/issues/7429

**Comment by alfrix** [comment]
Test font with arabic [font.zip](https://github.com/libretro/RetroArch/files/2716599/font.zip)
merged m+ 1p regular + DejaVu Sans Condensed
imho we should choose a font with full CJK support, and then add others if necessary
unless someone can provide a very similar font to m+ that isn't noticeable when mixed

**Comment by orbea** [comment]
It looks good to me, but someone who actually speaks Arabic would probably be able to judge better.
![1](https://i.imgur.com/tfnBdZE.png)

However this new font has one big regression, it now shows boxes for Korean instead.
