### ISSUE TITLE
kiosk mode should hide "reset core association"

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#7824]
When Kiosk Mode is enabled, "Reset Core Association" is still accessible via the playlist entry in XMB.

I would expect this feature to be hidden in kiosk mode because resetting the core association would disrupt a kiosk-style deployment of RetroArch.

**Comment by orbea** [comment]
I made a PR to resolve this.

https://github.com/libretro/RetroArch/pull/7827
