### ISSUE TITLE
kiosk mode should hide "start recording" and "start streaming"

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#7825]
I would like to suggest that when Kisok Mode is enabled, that the "Start Streaming" and "Start Recording" commands be hidden from the Quick Menu.

If the RA installation is being used as a Kiosk, these feature can lead to problems (for example starting a recording that fills up the drive of the kiosk).

Edit: From here on is out of date

---

It might also be nice to be able to toggle these commands via the Views menu, however I don't see that as much as a bug but as an enhancement.

**Comment by markwkidd** [comment]
Edited the OP, thank you

**Comment by orbea** [comment]
I made a PR to resolve this.

https://github.com/libretro/RetroArch/pull/7827
