### ISSUE TITLE
The wasapi audio driver does not work when built on MSVC2017, Windows 10

### ISSUE THREAD

**Issue by krzys-h** [libretro/RetroArch#7861]
## Description

I tried to run the wasapi audio driver to test my patches for #7849 and it turns out, it doesn't work at all on latest master when built on MSVC 2017, Windows 10. The latest release build downloaded from the website works fine.

### Expected behavior

The audio driver to run

### Actual behavior

```
[INFO] [WASAPI]: Initializing default device..
[ERROR] [WASAPI]: CoCreateInstance failed with error 0x80040154.
[ERROR] [WASAPI]: Failed to initialize device.
```
(0x80040154 is "class not registered", so I expect the GUIDs in wasapi.c to be wrong)

### Steps to reproduce the bug

1. Build the project on MSVC2017
2. Select the wasapi driver
3. Restart

### Bisect Results

I may try to bisect later, but I expect it to have never worked and the patch to be updating the GUIDs to a newer version. They do seem to differ from the ones in mmdeviceapi.h in the Windows 10 API. Is there any reason they are hardcoded instead of taking the compiler-defined ones anyway?

### Version/Commit

- RetroArch: 556bcc18e41cd5694e62b575f16c0c4da88f7b36

### Environment information

- OS: Windows 10 (but the system information in RetroArch reports it as Windows 8 for some reason?!)
- Compiler: MSVC 2017 (v1916)

**Comment by gouchi** [comment]
ping @casdevel

**Comment by twinaphex** [comment]
Hopefully @casdevel will be able to help.

**Comment by casdevel** [comment]
@krzys-h try [https://github.com/casdevel/RetroArch/tree/i7861](https://github.com/casdevel/RetroArch/tree/i7861).

**Comment by krzys-h** [comment]
@casdevel that does indeed seem to fix it for me!

**Comment by casdevel** [comment]
OK, I made a pull request.
