### ISSUE TITLE
UWP?  Second player game pad is unusable

### ISSUE THREAD

**Issue by DavidRieman** [libretro/RetroArch#7870]
## Description
Additional game pads are detected, but cannot be used.  The default configuration has one game pad controlling multiple players.  I don't know if this is specific to UWP yet.

### Expected behavior
Default game pad bindings should be:
* While one game pad is connected, it controls just player (port) 1.
* While two game pads are connected, the first one controls player (port) 1, and the second one controls player (port) 2.
Regardless of defaults, we should be able to reconfigure to have both game pads control separate game ports to successfully play any typical two player game.

### Actual behavior
When a second game pad is connected, we get the yellow `XInput Controller (User 1) configured in port #X`. messaging for a bunch of ports in a row.  In a two-player game, the one game pad controls both players by default.  Upon navigating into the "Input" settings, I see User 2 Device Index is bound to `XInput Controller (User 1) (#2)` even when only one game pad is connected.  I can scroll through the `(#2)` part up to `(#16)` but I don't know what this means.  With the second game pad connected, we still cannot scroll to any entry containing anything like `(User 2)`

### Steps to reproduce the bug
1. Launch RetroArch UWP on Windows or Xbox One.
2. Connect / activate a second game pad.
3. Try to play a two player game.

### Bisect Results
Did not attempt to bisect, because the new UWP version is the only version that has ever successfully built for me.  The 1.7.5 (non-UWP) Windows version from installer does not exhibit this problem though; the second player's controller shows as an entry like "XInput Controller (User 2)" without the (#X) part.

### Version/Commit
541dc13d64f6d12697431196e00760a52edd141b and a sync from yesterday also exhibited the problem.

### Environment information
- OS: Windows 10 and Xbox One
- Compiler: VS2017 defaults

**Comment by krzys-h** [comment]
This should be fixed now
