### ISSUE TITLE
`bind hold` setting is disregarded

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#7871]
According to RetroArch's UI, the function of the `Bind Hold` setting is to change the "amount of seconds to hold an input to bind it". The default value for `Bind Hold` is `2`. However, to my knowledge in Windows and in Lakka/Linux this setting has always worked as if the value is `0`.

**Steps to reproduce:**
  1. Go to `Settings` -> `Input` and change the `Bind Hold` to `2` (if it is not already set to `2`)
  2. Go to `Input User 1 Binds` and bind any control.

**Comment by orbea** [comment]
While I can't reproduce the problem where input binding is instant, changing the `Bind Hold` doesn't seem to have any effect, whether its `0`, `1` or `2` its always 4 seconds.

**Comment by markwkidd** [comment]
Thanks for the confirmation @orbea . Based on your report I have changed the title to try to make it more precise.

**Comment by grant2258** [comment]
from my understanding of this this has nothing to do with the 4 seconds (this time countdown is to do with bind timeout setting) 

the setting mark is talking is the amount of time you need to hold the button down before it registers as a bind.

**Comment by orbea** [comment]
Actually I can just reproduce it as you said, its instant. I was just confusing `Bind Timeout` and `Bind Hold`... It seems the latter is newer.

**Comment by orbea** [comment]
The feature was added in commit 8a2b23de34d30eaa5a97eb1168afd1e0fc9581f3.

It doesn't seem to have ever worked.

**Comment by orbea** [comment]
@fr500 and @hiddenasbestos Any ideas on this?

**Comment by markwkidd** [comment]
fr500 said on discord that this feature is only working on on Android

**Comment by grant2258** [comment]
strange i didnt notice anything specific on that commit posted to make the code functional on android. Ill test it out on android a bit later and let you know if its working for me on android.

**Comment by hiddenasbestos** [comment]
I agree, this setting was* only relevant to Android, the hold-to-bind feature wasn't (when I wrote the patch) intended for use on desktop operating systems - it could be used on there, but the scope of the work was to fix an Android bug.

(* I have no idea if this has changed since last April)

**Comment by grant2258** [comment]
Well I would say that clears the issue up maybe just hide the menu for everything accept android for this setting if that is a doable thing.

**Comment by markwkidd** [comment]
Hiding this setting on non-Android platforms would be fine with me as a solution if it turns out that no one else was trying to make it work for all.

**Comment by orbea** [comment]
> this setting was* only relevant to Android,

I'm not sure if I fully understand the use case on android, but I think it might be useful on other platforms. For example when using `Autoconfig Bind All` and the `L2` or `R2` triggers on a DS3 gamepad it binds it too fast and ends up setting it more than once.

**Comment by hiddenasbestos** [comment]
By all means roll it out to other platforms, consistency might be useful.

The problem with Android was to do with the virtual mouse (touch screen -> mouse button input) was registering as a bind, but this was in conflict with tapping on an on-screen keyboard (touch screen -> keyboard input)

The input binding still has issues - the fix above is dependent on keyboard presses having priority over delay binding by ignoring the delay binding process and operating on an edge trigger basis.

**Comment by fr500** [comment]
It works fine on PC by removing the conditionals here

https://github.com/libretro/RetroArch/blob/master/menu/widgets/menu_input_bind_dialog.c#L588

**Comment by markwkidd** [comment]
That being the case I went ahead and made a PR enabling Bind Hold for other platforms: https://github.com/libretro/RetroArch/pull/7874
