### ISSUE TITLE
[PS2] 9000X slim modchipped console black screen

### ISSUE THREAD

**Issue by ven2rez** [libretro/RetroArch#7894]
## Description

My PS2 console is 90008 with ModBo 4.0 modchip (FMCB non-compatible). I set uLaunchELF to autostart DEV1 mode (mc0:/BOOT/BOOT.ELF with ule) on my console. Gets black screen trying to run retroarch

Retroarch works, if i run it using a recorded DVD disc with uLE, but did not starts using modchip DEV1 method.

**Comment by fjtrujy** [comment]
Try to update the uLaunchELF version.

Thanks!

**Comment by AKuHAK** [comment]
@LibretroAdmin I think this can be closed now.
