### ISSUE TITLE
Add additional granularity in selecting udev controller autoconfig

### ISSUE THREAD

**Issue by andshrew** [libretro/RetroArch#7920]
## Description

In some instances there appears to be an issue in that depending on which driver the system is using for a controller it alters the button numbers (or IDs) that are then used by that controller.

An example of this with the udev joypad driver is the Sony DUALSHOCK 4 revision 2 controller. On one system which has an older build of the Linux kernal the inputs on this controller report differently to what they report as on a system running a newer build of the Linux kernal - but the PID/VID/Device Name are identical on each meaning it is not possible to create autoconfigs which are selected correctly depending on the system being used. 

### Expected behavior

An additional level of granularity is required in how RetroArch selects a controllers auto configuration. It should be possible to have two autoconfigs in udev which correctly map for both of these circumstances with the application able to correctly select the appropriate one. 

### Actual behavior

RetroArch will currently select the same config on both systems, meaning one is correctly mapped and one is not. The only way to correct this is to manually manage the autoconfig files on the non-working system to ensure only the autoconfig that is compatible with that system remains.

### Bisect Results

I believe this is due to the older system selecting the `hid-generic` driver vs the newer system selecting the `sony` driver, and this results the buttons reporting on different IDs.

Logs from system using `hid-generic`:
dmesg
```
[ 6446.497107] .(0)[21454:kworker/0:2]input: Sony Interactive Entertainment Wireless Controller as /devices/platform/soc/11190000.usb/musbfsh-hdrc.0/usb2/2-1/2-1.1/2-1.1:1.3/0003:054C:09CC.0010/input/input16
[ 6446.554778] .(0)[21454:kworker/0:2]hid-generic 0003:054C:09CC.0010: input,hidraw0: USB HID v1.11 Gamepad [Sony Interactive Entertainment Wireless Controller] on usb-musbfsh-hdrc.0-1.1/input3
```
retroarch
```
[INFO] [udev]: Plugged pad: Sony Interactive Entertainment Wireless Controller (1356:2508) on port #1.
[INFO] [udev]: Pad #1 (/dev/input/event2) supports 0 force feedback effects.
[INFO] [Autoconf]: 262 profiles found.
[INFO] [autoconf]: selected configuration: /gaadata/RetroArch/.config/retroarch/autoconfig/Sony-PlayStation4-DualShock4v2-Wired-Crystal-Controller.cfg
```

Logs from system using `sony` driver:
dmesg
```
[ 4072.640923] input: Sony Interactive Entertainment Wireless Controller as /devices/pci0000:00/0000:00:11.0/0000:02:00.0/usb2/2-2/2-2.1/2-2.1:1.3/0003:054C:09CC.0004/input/input12
[ 4072.641027] sony 0003:054C:09CC.0004: input,hidraw1: USB HID v81.11 Gamepad [Sony Interactive Entertainment Wireless Controller] on usb-0000:02:00.0-2.1/input3
```

retroarch
```
[INFO] [udev]: Plugged pad: Sony Interactive Entertainment Wireless Controller (1356:2508) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event7) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event7) supports 16 force feedback effects.
[INFO] [Autoconf]: 260 profiles found.
[INFO] [autoconf]: selected configuration: /home/andrew/.config/retroarch/autoconfig/udev/Sony-PlayStation4-DualShock4v2-Wired-Crystal-Controller.cfg
```

You can see in both instances autoconfig selects `Sony-PlayStation4-DualShock4v2-Wired-Crystal-Controller.cfg`, both systems see a device with the same VID/PID and name - but it results in the controller only having a correct mapping on the system with the `sony` driver.

### Environment information

System 1: selecting `hid-generic` PlayStation Classic
System 2: selecting `sony` Ubuntu 18.04.1 LTS

**Comment by orbea** [comment]
I think the solution is to just update your kernel so you have the same config on both systems.

**Comment by i30817** [comment]
Sometimes you can't update. Isn't there a way to get the driver you're using for the device from edev? 

Ie: 
1. retroarch gets driver name (hid-generic) and device name
2. retroarch tries to find the controller cfg with filename 'Sony-PlayStation4-DualShock4v2-Wired-Crystal-Controller-hid-generic.cfg'
3. if found use it, if not try to find 'Sony-PlayStation4-DualShock4v2-Wired-Crystal-Controller.cfg' and use it.

**Comment by orbea** [comment]
You can almost always update unless you are running such old hardware that you couldn't run RetroArch in the first place.

Just grab a kernel from upstream and build it yourself.

https://www.kernel.org/

Alternatively just overwrite the config file on your system for older kernel and use that until you do update.

**Comment by andshrew** [comment]
In this example the system is a PlayStation Classic so updating the kernel isn't as straight forward - I don't know how many other examples of similar systems there are but my thoughts were that if it were reasonably trivial to pull the device driver name it would be nice to be able to use that as an additional criteria in the process for selecting the autoconfig to load.

**Comment by orbea** [comment]
I didn't even know you could run linux on a Playstation Classic...

It might be possible for someone more experienced to make this change, but it would be a bit of effort to find out what exact kernel versions this changed, what gamepads are affected and what the correct autoconfig profiles for each gamepad. Note that the developers may not even have these gamepads.

Not to mention the usefulness of this is just going to keep decreasing over time as the kernel ages.

If updating the kernel is not possible, you can always make your own autoconfig for that one system in the input settings.

**Comment by andshrew** [comment]
It looks like support for the revision 2 controller was added to `hid-sony.c` in [this commit](https://github.com/torvalds/linux/commit/cf1015d65d7c8a5504a4c03afb60fb86bff0f032#diff-ea8a58a0802dc8df05d5caf91e2c7934) ~October 2016.

The autoconfigs for this controller are already a bit of a mess (probably in part due to the confusion over this as there are currently 4 for udev) but:
`Sony-PlayStation4-DualShock4v2-Wired-Crystal-Controller.cfg` is the correct mapping for a device using the `sony` driver.
`Sony-PlayStation4-DualShock4v2-Controller.cfg` is the correct mapping for `hid-generic`.

**Comment by orbea** [comment]
Closing in favor of the older and more general issue. https://github.com/libretro/RetroArch/issues/3914
