### ISSUE TITLE
8Bitdo RB8 (Nintendo 64) BT controller A/B not mapped correctly in ParaLLEl 64

### ISSUE THREAD

**Issue by sondregronas** [libretro/RetroArch#7921]
## Description

Sorry if this has already been answered, I couldn't find any other instances of this whilst searching.

In the ParaLLEl 64 emulator my controller seems to be incorrectly mapped by default, with the B button acting as the A button, and the A button not doing anything.

If I remap the core itself it changes the A/B button for my other controllers aswell which I don't like.

As a temporary workaround I changed the "Retro-Bit_8Bitdo_RB8-64*.cfg" files where I swapped input_a_btn and input_b_btn, aswell as remapping A to A, and B to B in ParaLLEl. This seems to work for N64 core, but swaps the A/B button for every other core

Is it possible to change the button layout for controllers on a core to core basis?

### Expected behavior

The A and B button to work as expected in the N64 core ParaLLEl (works with workaround, but affects every other core)

### Actual behavior

A/B Buttons are swapped in ParaLLEl, with A not mapped correctly.
However it works in every other core (afaik)
With workaround the A/B buttons are swapped in every other core for the RB8 controller.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 02 October 2018, git 826c77d523

### Environment information

- OS: Windows 10 Home 64-bit

**Comment by RobLoach** [comment]
You can export a new config and then see what the differences are...

1. Set the new controller mappings
2. Export new auto config
3. Copy the contents of the new file to the config over at https://github.com/libretro/retroarch-joypad-autoconfig
4. Submit a Pull Request with the new updates
5. If things look good, it'll be merged, and you'll never have to update your configs again

**Comment by sondregronas** [comment]
The config appears to be correct as it is, the issue seems limited to the Nintendo 64 cores (both Mupen64 and ParaLLEl). Where would I be able to modify the controller mappings only on specific cores?

**Comment by sondregronas** [comment]
Sorry if I misunderstand but - when I changed controls on my 8Bitdo pad under Controls it does work as expected, but the changes affected my Xbox one controller scheme for that core aswell. Is it not supposed to do this? I did not restart Retroarch before swapping controllers like I usually do.
