### ISSUE TITLE
Save states much slower when HAVE_MENU is not defined.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#7933]
## Description

After `--disable-rgui` was fixed and `--disable-menu` was added it exposed a hidden bug where loading save states are much slower when `HAVE_MENU` is not defined.

I suspect the issue is related to one of these `HAVE_MENU` instances found by grep.

~~https://pastebin.com/ZxMTvAkY~~
https://pastebin.com/Z5MrqH9f

### Expected behavior

Save states should load just as fast as when `HAVE_MENU` is defined.

### Actual behavior

When RetroArch is built with `HAVE_MENU` not defined loading save states takes a few seconds where they are instant with `HAVE_MENU` defined.

### Steps to reproduce the bug

1. Build RetroArch with: `./configure --disable-menu`
2. Start RetroArch from the command line: `./retroarch -L /path/to/core.so /path/to/content`
3. Load a save state with a keybind.
4. Its really slow.

### Bisect Results

N/A

This bug was hidden behind a broken build path for presumably a long time.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/3e5237ed720a391a413a3b4eb6fe6a4e090b2706

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.2.0`

**Comment by orbea** [comment]
The problem is in `configuration.c`, see the referenced PR.

For the record I narrowed this down by doing this until I found the relevant file.
```
sed -i 's/#ifdef HAVE_MENU/#if 0/' configuration.c
```

**Comment by i30817** [comment]
What happens if you try to enable QT?

**Comment by orbea** [comment]
The Qt frontend no longer depends on `HAVE_MENU` and the issue was the same whether loading from the command line or companion ui when `HAVE_MENU` is not defined.
