### ISSUE TITLE
[Packaging/Releases] F-Droid releases should not be nightly only

### ISSUE THREAD

**Issue by charlydelta** [libretro/RetroArch#7940]
The official F-Droid repo of RetroArch appears to be a nightly channel, since I get two updates each day. The indicated version on F-Droid is 1.75_GIT.

I don't want to be *that* bleeding edge, but downgrading to 1.75 would basically disable all notifications from F-Droid if another stable version is released.

I therefore suggest you to make the default F-Droid releases stable only, and offer a nightly channel separately, as they are for development purposes only anyway. You could basically just add an entry to the repo called "RetroArch Beta" or similar.

**Comment by twinaphex** [comment]
I prefer it to be nightlies. If you want stables, you can download the stable either from the Play Store or you can download it from our buildbot server (go to retroarch, go to Downloads, scroll down to the Android section, you can download the APK there).

**Comment by charlydelta** [comment]
My suggestion would hurt neither of us.

Like I said, I would still like to be notified on updates (which would not be the case with the apks). I also don't use Google Play store by the way.

**Comment by orbea** [comment]
I agree that it would be nice if fdroid offered both stable and nightly releases, that way everyone is happy.
