### ISSUE TITLE
Discord avatar filename error

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#7944]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Can't download discord avatar...

### Expected behavior

Discord avatar should be successfully downloaded.

### Actual behavior

```
[INFO] [Discord] connected to user: ofry#9231 - avatar id: 340016162010169344
[INFO] [Discord] downloading avatar from: https://cdn.discordapp.com/avatars/340016162010169344/.png
[ERROR] [http] Could not create new HTTP session handle.
[ERROR] Download of '.png' failed: Internal error.
```

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: c2047c8c04 (from buildbot)

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
Do you have an avatar set? IIRC  you have the empty yellow discord avatar.

**Comment by orbea** [comment]
@ofry Is this resolved?

**Comment by fr500** [comment]
It's a won't fix, he doesn't have an avatar so nothing is downloaded.

**Comment by orbea** [comment]
Given the PR I will just close this.
