### ISSUE TITLE
Switch Bugs 

### ISSUE THREAD

**Issue by Klauserus** [libretro/RetroArch#7949]
Hi

I am not shure, but i think that is a RetroArch Bug

## Description

First Graphic glitches (see Pictures)

<a href="https://ibb.co/ckM2Cyc"><img src="https://i.ibb.co/ckM2Cyc/Grandia-1.jpg" alt="Grandia-1" border="0"></a>

<a href="https://ibb.co/93nrkdX"><img src="https://i.ibb.co/93nrkdX/Grandia-2.jpg" alt="Grandia-2" border="0"></a>

Second and my Big Problem

Video: //sendvid.com/embed/3piqdvbn

You can see, that the FPS are stable at 50 FPS, but it stuttering. This is in all of my Games. Mainly PSX but i am not shure that this is at SNES, too

### Infos
Grandia Disc 1 English (not shure PAL or NTSC)
RetroArch 1.7.5 official
PSX ReArmed Core r22
PSX Bios are md5 hash confirmed (no message BIOS missing)
Switch 5.1 with Atmosphere 8.2

Thx a lot, for your Work. It´s soo cool to play my old Games portable :)

**Comment by bparker06** [comment]
The stuttering is expected, there is no 64-bit dynarec in pcsx so you're going to have performance problems on Switch.

Please try with a 8 or 16-bit core such as fceumm or snes9x and see if it happens there too.

**Comment by Klauserus** [comment]
Ok. i test it with 16 bit games. Can i do something against the glitches?

about 64 ARM....mhh well, i hope and wait for a dynarec

**Comment by Klauserus** [comment]
I belive with Version 1.76 its gone, i think. can closed
