### ISSUE TITLE
Wayland is broken in current master

### ISSUE THREAD

**Issue by Sunderland93** [libretro/RetroArch#7953]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Failed to start RetroArch with Wayland context on GNOME and Weston. On Weston it gives an error
![wayland-screenshot-2019-01-09_21-28-49](https://user-images.githubusercontent.com/11344982/50919735-0f235a80-145d-11e9-8d71-891f3c928fd8.png)

### Expected behavior

Wayland context should work

### Actual behavior

Failed to X context
### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: master

### Environment information

- OS: Debian Sid
- Compiler: GCC 8.2

**Comment by myfreeweb** [comment]
"Cannot open video driver", "0xffffff... PCI ID", that doesn't look RetroArch specific at all, do any OpenGL applications work? Do you have permissions on /dev/dri/ devices?

**Comment by Sunderland93** [comment]
@myfreeweb RetroArch 1.7.5 run's well. Permissions on /dev/dri/:

```
drwxr-xr-x  2 root root        80 янв 10 17:30 by-path
crw-rw----+ 1 root video 226,   0 янв 10 17:30 card0
crw-rw----+ 1 root video 226, 128 янв 10 17:30 renderD128
```

**Comment by myfreeweb** [comment]
oh wait, the log is showing that it's trying to use KMS, not Wayland! What's above the "EGL version…" line?

**Comment by Sunderland93** [comment]
![wayland-screenshot-2019-01-11_20-47-17](https://user-images.githubusercontent.com/11344982/51047529-23449480-15e2-11e9-84f8-db51b602cc70.png)

**Comment by Sunderland93** [comment]
If building with Wayland only:

```
sunderland93@Debian-Gnome:~/master/RetroArch$ ./retroarch
[INFO] [recording] twitch streaming key empty
[INFO] RetroArch 1.7.5 (Git 24ce1aee21)
[INFO] === Build =======================================
Возможности: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 
Built: Jan 11 2019
[INFO] Version: 1.7.5
[INFO] Git: 24ce1aee21
[INFO] =================================================
[ERROR] Couldn't find any input driver named "x"
[INFO] Available input drivers are:
[INFO] 	udev
[INFO] 	linuxraw
[INFO] 	null
[WARN] Going to default to first input driver...
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Версия API libretro: 1
[INFO] Скомпилирован против API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 1024x600
[INFO] [Wayland]: Physical width: 510 mm x 290 mm.
[INFO] [Wayland]: Video mode: 1920 x 1080 @ 60.0000 Hz.
[INFO] [Wayland]: Display scale factor 1.
[INFO] [Wayland]: Seat name: seat0.
[WARN] [Wayland]: Compositor doesn't support zwp_idle_inhibit_manager_v1 protocol!
[WARN] [Wayland]: Compositor doesn't support zxdg_decoration_manager_v1 protocol!
[INFO] [EGL] Found EGL client version >= 1.5, trying eglGetPlatformDisplay
[INFO] [EGL]: EGL version: 1.4
[INFO] [GL]: Found GL context: null
[INFO] [GL]: Detecting screen resolution 320x240.
Ошибка сегментирования
```

**Comment by myfreeweb** [comment]
oh, something right after the EGL context initialization fails.

Here's a patch for some extra logging:

```
diff --git c/gfx/common/egl_common.c i/gfx/common/egl_common.c
index 80e0697e50..6364d024cd 100644
--- c/gfx/common/egl_common.c
+++ i/gfx/common/egl_common.c
@@ -360,8 +360,10 @@ bool egl_init_context(egl_ctx_data_t *egl,
    }
 
    configs = malloc(count * sizeof(*configs));
-   if (!configs)
+   if (!configs) {
+      RARCH_ERR("[EGL]: failed to malloc %d configs.\n", count);
       return false;
+   }
 
    if (!eglChooseConfig(egl->dpy, attrib_ptr,
             configs, count, &matched) || !matched)
diff --git c/gfx/drivers_context/wayland_ctx.c i/gfx/drivers_context/wayland_ctx.c
index d83b5667ee..07930418ad 100644
--- c/gfx/drivers_context/wayland_ctx.c
+++ i/gfx/drivers_context/wayland_ctx.c
@@ -1354,10 +1354,12 @@ static void *gfx_ctx_wl_init(video_frame_info_t *video_info, void *video_driver)
                   &major, &minor, &n, attrib_ptr,
                   egl_default_accept_config_cb))
          {
+            RARCH_WARN("[Wayland]: egl_init_context failed\n");
             egl_report_error();
             goto error;
          }
 
+         RARCH_WARN("[Wayland]: n=%d has_config=%d!\n", n, egl_has_config(&wl->egl));
          if (n == 0 || !egl_has_config(&wl->egl))
             goto error;
 #endif
```

But I think I know what's failing. It'll probably say `n=0` for you :)

`n` is an uninitialized variable that's passed by pointer to `egl_init_context` which doesn't do anything at all to it…

**Comment by Sunderland93** [comment]
![wayland-screenshot-2019-01-11_21-42-44](https://user-images.githubusercontent.com/11344982/51050337-dc5a9d00-15e9-11e9-978b-2fc1d1f2ad94.png)

**Comment by myfreeweb** [comment]
aaaand yeah. That was it. Now try #7984 :)

So this whole thing only worked because everyone's systems would initialize `n` with random garbage, but somehow your system initialized `n` with zero and uncovered the issue.

**Comment by Sunderland93** [comment]
It works! Thanks a lot!
