### ISSUE TITLE
[Xbox One] Rewind function causing games to freeze then crash back to the Dev Mode Menu

### ISSUE THREAD

**Issue by Ploggy** [libretro/RetroArch#7955]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Using the Rewind function causes the game to freeze then crash back to the Dev Mode Menu

### Expected behavior

Game not to freeze and crash and Rewind to function as normal.

### Actual behavior

Game locks up and crashes Retroarch back to Dev Mode Menu

### Steps to reproduce the bug

1. Load Rom for whatever Core
2. Try to Rewind Gameplay

### Bisect Results

As far as I know this has always happened on Xbox One?

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.5 msvc2017

### Environment information

- OS: Xbox One
- Compiler: [In case you are running local builds]

**Comment by krzys-h** [comment]
Confirmed - also happens on regular Windows MSVC build, possibly other platforms as well

**Comment by krzys-h** [comment]
Latest nightly from the buildbot works, so I guess this is something specific to the MSVC compiler

**Comment by dominater01** [comment]
@Ploggy is this still an issue on the non merged version?

**Comment by Ploggy** [comment]
Yes it still happens, on Xbox at least. Haven't tried on PC.

**Comment by anthonyx64** [comment]
This is fixed on latest build, therefore, I think this could be close. What do you think @dominater01 ?

**Comment by dominater01** [comment]
yep this is no longer a problem
