### ISSUE TITLE
Gamepad Dualshock xbox recognized as 8bitdo causing weird behavior /malfunction

### ISSUE THREAD

**Issue by IceLancerSR** [libretro/RetroArch#7958]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Hey, i just updated from 4th january to 9th january latest build and gamepad is acting very weird.
Its being recognized as 8bitdo
https://i.imgur.com/84fYGdb.jpg
and as result some controls are not functioning.
That is Dualshock 4 v2 gamepad using ds4windows.
If i turn off ds4windows , i cant even use gamepad and keyboard starts acting very fast (like turbo skipping is on). So fast in menus of retroarch that i cannot control or even open anything.

- RetroArch: [version/commit]
9th january 14:55 build

### Environment information

- OS: windows 10

**Comment by orbea** [comment]
Can you make an autoconfig profile for your gamepad?

See https://github.com/libretro/retroarch-joypad-autoconfig/commit/eb12de5d01717741f1ea68fd76421606efcb6818.

**Comment by IceLancerSR** [comment]
> 
> 
> Can you make an autoconfig profile for your gamepad?
> 
> See [libretro/retroarch-joypad-autoconfig@eb12de5](https://github.com/libretro/retroarch-joypad-autoconfig/commit/eb12de5d01717741f1ea68fd76421606efcb6818).

If i delete config it returns to normal function, i am comparing files right now adding diff by diff trying to determine what is the cause.. will post result

**Comment by IceLancerSR** [comment]
Ok, i managed to restore behavior to normal , but main issue is still there, usually gamepad would be recognized properly and playstation logo button would be "auto" assigned to open retroarch menu, this is no longer happening , because gamepad is recognized as something else entirely and some controls are behaving differently. Reverting to older retroarch gamepad is shown properly as xbox gamepad.

**Comment by orbea** [comment]
I think you can solve this by making a autoconfig profile which matches your gamepad, please post it here when you do we can compare with the existing autoconfig profiles.

You can do this by going into the input settings and configuring your gamepad in `Input User 1 Binds`, when you are finished you should use `User 1 Save Autoconfig` to create the profile.

**Comment by IceLancerSR** [comment]
all game remap configs has gone to hell as well. its triggering game slow motion when i press "guide" button auto map assigned

**Comment by IceLancerSR** [comment]
u see here?
automap from old version
https://i.imgur.com/63TAfDb.jpg
automap on new version
https://i.imgur.com/KSIlW4r.jpg

if i load old core overrides, controls became totally unresponsive and keyboard starts nascar racing

**Comment by IceLancerSR** [comment]
Alright i guess ill open new issue , this one is invalid now
