### ISSUE TITLE
Dualshock 4 with ds4windows recognized as 8Bitdo breaking functions (rumble , guide button..)

### ISSUE THREAD

**Issue by IceLancerSR** [libretro/RetroArch#7960]
**Hey!
edited , since culprit has been recognized. 
8Bitdo_GBros_BT
has same ID as dualshock 4 (v2) using ds4windows
as result retroarch is getting wii gamepad instead of xbox , so rumble, guide button ,touchpad, no longer function in cores that uses them. Playstation 1, playstation 2

input_vendor_id = "1118"
input_product_id = "736"**

old RA
https://i.imgur.com/63TAfDb.jpg

new RA 
https://i.imgur.com/KSIlW4r.jpg

Basically its no longer recognizing dualshock (xbox) gamepad with ds4windows as such , but as xinput 8bitdo
https://i.imgur.com/84fYGdb.jpg

and as result some controls from automap and controls is self are behaving oddly
"Guide" button has to be assigned manually with new RA, because gamepad is recognized as something else. And if mapped to menu open it will also cause emulator "slow" to trigger, and cant be unmaped.
This can also potentially cause future issues with other emulators that uses xbox/dualshock functions (PS2 rumble?)

**Comment by IceLancerSR** [comment]
> 
> 
> I told you in your other issue, you need to make an autoconfig profile...
> 
> #7958

Sorry, thanks for patience, if i do what u said, i get new file xinpu/XInput Controller (User 1).cfg
but only this inside
input_driver = "xinput"
input_device = "XInput Controller (User 1)"
input_vendor_id = "1118"
input_product_id = "654"
and then after restarting RA, gamepad no longer functions

**Comment by IceLancerSR** [comment]
Its not really that i have problem with "user binds" its hotkey binds that are the issue, "guide" button is no longer autoasigned "button10" i assume because that new wii profile doesnt have that button. binding that button or not , it will cause emulator "slow" function to trigger

**Comment by orbea** [comment]
You need to bind the gamepad before saving the autoconfig, but now that I see `input_vendor_id` and `input_product_id` numbers I see the 8bitdo gamepad unfortunately match your gamepad which explains the incorrect bindings.

**Comment by IceLancerSR** [comment]
I did changed and binded button 10 to do the job but it didnt saved it.
That is dualshock 4 gamepad using ds4windows.

I figured out that temporary? fix is to copy all data from XInput_Controller_User_1 except input vendor and procuct into new file XInput Controller (User 1)
guide button gets assigned properly, i guess it overrides wii controller?

**Comment by orbea** [comment]
The home button doesn't save for some reason (Someone should fix that...), you will need to add it into the autoconfig manually. See the other autoconfig profiles for examples and the input settings for the correct button.

**Comment by IceLancerSR** [comment]
Its all good now, i copied controls from above to user controls , i am just not sure how will some cores handle custom profile when it comes to functions that this gamepads provide and are non existent in wii since id matches wii..

**Comment by IceLancerSR** [comment]
Yeah.......Rumble doesnt work any more... playstation 1, playstation 2..wii doesnt have rumble?

**Comment by orbea** [comment]
If its outright broken can you make a new issue and follow the issue template so it hopefully gets the attention it deserves? I don't have a wii so I can't help here...
