### ISSUE TITLE
[Feature request] Feral gamemode support, possibly on a per core basis

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#7977]
For laptop users, some cores can be hampered by being in a low power CPU state. I've noticed this personally in Beetle on an i7-7500U. 

Feral Gamemode is an ld preload that can automatically switch to the performance governor when called. 

https://github.com/FeralInteractive/gamemode

This would be a great implementation if could be called on a per core basis. Some cores don't need full power, while others benefit greatly. 

Linux desktops would also see improvement since the default governor is powersave across the board. 

### Environment information

- OS: Linux

**Comment by i30817** [comment]
Not only no, but fuck no. My computer overheats when put in 'performance' mode, and this is the reason i'm intimately familiar with this 'slowdown' phenomenon.

BTW, it's not all cores. Beetle HW and mupen64 slow down true, but dolphin, beetle and parell64 don't, go figure. It may be worth it to experiment with the nice setting.

**Comment by orbea** [comment]
Honestly I think this should be fixed by the system admin rather than the app.

**Comment by parkerlreed** [comment]
Agreed. Easy enough to setup. Did so here and that's what led me to making the feature request.

**Comment by i30817** [comment]
I've read some more and it appears this won't do anything if you didn't install the deamon, so i retract my objection.

**Comment by parkerlreed** [comment]
Thanks for closing this out! I had no idea it was added around last December. Sweet!
