### ISSUE TITLE
ps classic retroarch language shows question mark

### ISSUE THREAD

**Issue by cashimi001** [libretro/RetroArch#7978]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
PS CLASSIC RETROARCH can not change the language to chinese

### Expected behavior

in user change language ,chinase japannese shows question mark

### Actual behavior

seting-user-language

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.75C]

### Environment information

- OS: [ps classic]
- Compiler: [ps classic]

**Comment by cashimi001** [comment]
@orbea i tryed 20+ chinese ttf and10+ japnease ttf but not working ,i think it is not ttf issue ,it is all non latin characters shows ????  question mark , i think it is coding issue, thank you so much

**Comment by orbea** [comment]
Then maybe its platform specific, I'm not sure as I have never used a PS classic.

**Comment by andshrew** [comment]
This has been fixed in the next ModMyClassic RetroArch release for the PS Classic.
