### ISSUE TITLE
IOS and IOS 9 DOWNLOAD ERROR

### ISSUE THREAD

**Issue by Flavis** [libretro/RetroArch#7981]
repo link is broken, both versions help

**Comment by orbea** [comment]
Follow the issue template...

The links apparently are.

https://buildbot.libretro.com/stable/1.7.5/apple/ios/RetroArch.zip
https://buildbot.libretro.com/stable/1.7.5/apple/ios9/RetroArch.zip

**Comment by Flavis** [comment]
sorry im brazilian, im my english is so bad :/

**Comment by orbea** [comment]
As long as we can understand perfect English is not required.

Though I am not sure what is wrong with the IOS downloads, maybe someone else will? You will probably have a better mobile RetroArch experience with android though.

**Comment by Flavis** [comment]
yes i know IOS sucks, but this perfectly works on ios 11 retroarch download by buildstore, but i use ios 9 and the only way to download is via official website but is offline ios downloads

**Comment by bparker06** [comment]
The ios builds are currently broken as we lack a maintainer willing to fix it.
