### ISSUE TITLE
Error parse an empty playlist file

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#8015]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Error parse an empty playlist file.

### Expected behavior

All playlists should load fine.

### Actual behavior

```
[INFO] Loading history file: [content_history.lpl].
[INFO] Loading history file: [C:\retroarch\content_favorites.lpl].
[INFO] Loading history file: [content_music_history.lpl].
[INFO] Loading history file: [content_video_history.lpl].
[ERROR] Could not detect playlist format.
[WARN] Error parsing JSON.
[WARN] Error: Invalid JSON at line 1, column 1 (input byte 0) - the input ends when more tokens are expected.
```

content_video_history.lpl - just empty file.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 874a5258c5

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
I can reproduce this here.
```
[INFO] Loading history file: [/home/orbea/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/orbea/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/home/orbea/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/orbea/.config/retroarch/content_video_history.lpl].
[ERROR] Could not detect playlist format.
[WARN] Error parsing JSON.
[WARN] Error: Invalid JSON at line 1, column 1 (input byte 0) - the input ends when more tokens are expected.
[INFO] Loading history file: [/home/orbea/.config/retroarch/content_image_history.lpl].
```
There are two bugs here.

1. It should not fail to parse empty files.
2. Automatically updating old playlists to the new format is potentially disruptive and annoying for bisecting.

**Comment by orbea** [comment]
I guess this is related to PR https://github.com/libretro/RetroArch/pull/7959.

@bparker06 ping.
