### ISSUE TITLE
Add support for menu audio

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#8016]
Throwing ideas here for an optional menu audio feature (clicking menu sounds + background music / ambience). 

We would need to :

1. Find public domains sounds
2. Make sure that the audio driver is running while in menu
3. Add at least one sound format to libretro-common 
4. Add a sound pool to the menu driver (loaded in context reset ? should it still be in RAM while content is running, or reloaded on toggle ?)
5. Allow menu drivers to play audio from the pool with proper mixing (content can be running while the menu is open)
5. Actually play the sounds on menu actions
6. Rename the current `Enable menu audio` setting, which is misleading, and add the new system to the settings

**Comment by orbea** [comment]
This is already done? What is wrong with `Enable menu audio`? It plays audio in the menu...

**Comment by natinusala** [comment]
I meant menu sounds such as clicking when going up/down or selecting stuff

**Comment by orbea** [comment]
Ah, I didn't understand from the OP post, but this issue already exists so I am going to close this for the older issue.

https://github.com/libretro/RetroArch/issues/2612
