### ISSUE TITLE
Vulkan Crash

### ISSUE THREAD

**Issue by Ashurek85** [libretro/RetroArch#8058]
## Description

Retroarch crash if video_driver = "vulkan". In other video modes it works fine.

### Expected behavior

It should work

### Actual behavior

Application crash. 

If i execute _.\retroarch.exe --log-file .\retroarch-log.txt --verbose_ the log output is:

[INFO] RetroArch 1.7.5 (Git 826c77d523)
[INFO] === Build =======================================
[INFO] Version: 1.7.5
[INFO] Git: 826c77d523
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "D:\Emuladores\RetroArch\saves\.srm".
[INFO] Redirecting savestate to "D:\Emuladores\RetroArch\states\.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29999.40 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] Vulkan dynamic library loaded.

No more text was displayed.

### Steps to reproduce the bug

1. Set video_driver = "vulkan"
2. Run RetroArch

### Version/Commit

- RetroArch: 1.7.5

![image](https://user-images.githubusercontent.com/45046196/51494622-89d36a80-1db9-11e9-95d9-16f85f4c6f8e.png)

### Environment information

- OS: Windows 10 x64
- Hardware: 8700k + 16GB DDR4 + Nvidia 1060 6GB (Drivers 417.71)

**Comment by orbea** [comment]
Can you try a nightly version?

**Comment by Ashurek85** [comment]
The situation continue. The log output is:

[INFO] RetroArch 1.7.5 (Git 26ea9d9f0c)
[INFO] === Build =======================================
[INFO] Version: 1.7.5
[INFO] Git: 26ea9d9f0c
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "C:\Users\fran_\Downloads\RetroArch\saves\.srm".
[INFO] Redirecting savestate to "C:\Users\fran_\Downloads\RetroArch\states\.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 29970.03 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] Vulkan dynamic library loaded.

![image](https://user-images.githubusercontent.com/45046196/51556727-45a89e80-1e7b-11e9-8e4c-dfe1ab32c48d.png)

**Comment by orbea** [comment]
Can you provide a backtrace made with the debug build?

**Comment by Ashurek85** [comment]
I execute retroarch_debug.exe with the same situation. I think that the problem is Nvidia driver; all applications that use vulkan were crashed. 

What do you think about this?

**Comment by orbea** [comment]
What other programs have you tried with vulkan? If every program crashes this is not a RetroArch issue.

Possible ideas are that you don't actually have a vulkan capable card / driver or your nvidia driver is just buggy in which case upgrading or downgrading the driver may help.

**Comment by Ashurek85** [comment]
I try another programs:

- Basemark GPU (benchmark)
- Demo in nvidia web: Vulkan Choppers

All applications were crashed. Nvidia 1060 is vulkan capable but it does not work. I have the lastest driver version; i will try old driver.

Thanks for help. You can close this ticket.

**Comment by orbea** [comment]
Yea, I don't think there is anything we can do if vulkan is broken in general.

Since nvidia is proprietary software the only recourse is to try different driver versions until it works or report it to nvidia and hope they can help.

**Comment by Ashurek85** [comment]
This thread resolved the issue:

https://forums.geforce.com/default/topic/1095700/geforce-drivers/driver-417-71-vulkan-doesn-t-work/?offset=5#5971784
