### ISSUE TITLE
Conflicting autoconfig inconsistencies? (Dualshock 4 Controller with DS4Windows gives 2 input devices chosen at random, 1 works)

### ISSUE THREAD

**Issue by sondregronas** [libretro/RetroArch#8064]
## Description

I'm using a Sony Dualshock 4 Controller with DS4Windows, and it gives me both a Dualshock 4 Controller (Wireless Controller) input device and an XInput device in slot 1. I am on XInput Joypad drivers. From what I can tell it chooses either input device randomly. Only the XInput device works out of the two, is there a way to give XInput priority over a Dualshock 4 Controller, always?

I've tried to modify/remove the autoconfig (xinput/DUALSHOCK_4.cfg) but didn't manage to do anything. Any workarounds for this? I'm mostly playing over Moonlight streaming so hopping into the menus everytime it happens is not always an option.

### Expected behavior

XInput to take priority over Dualshock 4 Controller, or atleast bypass Dualshock 4 Controller config alltogether - as they are the same controller but only XInput gives valid keys.

Or alternatively the native Dualshock 4 Controller not to be recognized as a XInput device

### Actual behavior

Retroarch either defaults the Dualshock 4 Controller input device or the XInput device for the same controller

### Steps to reproduce the bug

1. Start DS4Windows, Connect DS4 controller, boot into any game (I'm booting with commandline)
2. See if controls work, Input Device will either be Sony Dualshock 4 or XInput
3. Disconnect controller, exit DS4Windows & repeat

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 826c77d523

### Environment information

- OS: Windows 10 Home 64Bit

**Comment by fr500** [comment]
This is not a RA issue.
Also this is not a questions and answers forum. This venue is for
developers.

That said. Windows device enumeration is random like that. DS4windowd has
(had?) An option to hide the real device. Use that. RA will use the devices
the OS exposes.

Your tool of choice is responsible for hiding the other device.

**Comment by sondregronas** [comment]
My apologies.

And yes you're absolutely right - I've been blinded, the option was right there. Thank you
