### ISSUE TITLE
PSX HW controller can't vibrate on Win10

### ISSUE THREAD

**Issue by g112** [libretro/RetroArch#8067]
Hollow everyone

I uses DS4+DS4windows to play ps1 games on PSX HW, but only fews games can vibrate.

And I try  same games  on other emu( like mednafen and ePSXe) and they can vibrate.

How can I fix it??

Games list I try can vibrate : FF8, FF9, Chrono Cross, Chocobo Racing

Games list I try can't vibrate: Tales of Phantasia , Tales of Eternia, Super Robot Taisen Alpha

Thanks.

**Comment by orbea** [comment]
If its game specific this is a core issue.

Can you open your issue in the core tracker?

https://github.com/libretro/beetle-psx-libretro/issues

**Comment by orbea** [comment]
Also when are Tales of Phantasia or Tales of Eternia supposed to rumble? I can test those later.

**Comment by g112** [comment]
Both of them suppose to rumble. They work normally by mednafen.

**Comment by orbea** [comment]
When do they rumble? During battles?

Can you reopen this issue report for the core?

**Comment by g112** [comment]
ok. I report for the core. Thanks

**Comment by orbea** [comment]
Thanks!

Closing in favor of the core issue https://github.com/libretro/beetle-psx-libretro/issues/484.
