### ISSUE TITLE
[Feature request] Enable logging of cheevos status: stub out cheevos_log() function

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#8068]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Enable logging of cheevos status.

### Expected behavior

Enable logging of cheevos status (for example, auth attempt was success or not, is loaded content presented in RetroAchievements DB etc).

So function cheevos_log() in cheevos/cheevos.c should be stubbed out.

```
void cheevos_log(const char *fmt, ...)
{
   (void)fmt;
}
```

### Actual behavior

No cheevos-related logs now.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 26ea9d9f0c

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
I believe logging does exist but it was disabled due to not being thread-safe (and hence conflicted with the logging in Qt), and then was never fixed.

**Comment by meleu** [comment]
@leiradel says in his PR #6623:
> Logging for Qt has been properly fixed, and logging from multiple threads has been around for ages and has never been a problem, so I don't know why this is needed...

I agree that the logging is very important to debug cheevos stuff. It would be really useful to get it back.

**Comment by ofry** [comment]
I can't see anyhow, is cheevos working at all now!, because no logs, no on-screen notifications, etc. For example, I can't see is login to RetroAchievements account are succeeded or failed, is exist loaded game in Retroachievements database or not, etc.

**Comment by meleu** [comment]
Cheevos on-screen notifications work fine for me.

Try `cheevos_verbose_enable = true`.

**Comment by leiradel** [comment]
`tasks/task_database.c` has logging in its tasks, so I don't really understand why logging had to be removed from cheevos other people once again blaming cheevos for random bugs in the codebase. If logging is ok in one task, it should be ok in any other task.

**Comment by ofry** [comment]
@meleu It already was set to true, but no luck :(

**Comment by meleu** [comment]
(I feel like it's going kinda off-topic, but let's go...)

Do you ever see on-screen notifications? I mean, when taking screenshots, loading/saving states, etc.

If not, you have to enable OSD messages (`video_font_enable = true`) and set a reasonable size for the font (like `video_font_size = 32`).

**Comment by ofry** [comment]
@meleu Yes, I see frame counter, downloading status, etc...

**Comment by ofry** [comment]
Any objections preventing to print cheevos logs via call
```
log_cb()
```

in body of 

```
cheevos_log()
```
function?

**Comment by ofry** [comment]
@meleu @Jamiras Could you do this little request for easier cheevos debugging?

**Comment by ofry** [comment]
This issue has solved now.
