### ISSUE TITLE
[RGUI] [GLUI] Subsystem not supported

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#8070]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Subsystem doesn't supported with RGUI and GLUI menu drivers.

### Expected behavior

Subsystem should be supported as in XMB and OZONE

### Actual behavior

Subsystem doesn't supported

### Steps to reproduce the bug

1. Load Sameboy Core
2. And see: menu entry "Load 2 Player Game Boy Link" is absent.
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 49fa097903

### Environment information

- OS: Windows 8.1 Enterprise x64
- Compiler: gcc

**Comment by orbea** [comment]
This is a related issue which will be exposed if this is fixed. https://github.com/libretro/RetroArch/issues/7997

**Comment by jdgleaver** [comment]
Thanks for the heads-up @orbea. That's actually quite nasty - especially for RGUI, which can run on hardware (i.e. consoles) where segfaults are troublesome to recover from (you often have to hard shutdown the system, which risks corrupting flash storage). Not sure that I want to meddle with this while such a large underlying problem exists...

**Comment by fr500** [comment]
It's actually not a problem in consoles.
Load core results in a complete reinitialization on consoles.

**Comment by jdgleaver** [comment]
Okay, PR  #8194 adds subsystem support to RGUI. I guess I'll probably end up doing GLUI as well (it's pretty trivial), but I want to work on some other stuff first...

**Comment by jdgleaver** [comment]
...and PR #8224 adds subsystem support to GLUI. I guess this can be closed once it's merged...?

**Comment by orbea** [comment]
Thanks! I guess this can be closed now, please let us know if there any further issues.
