### ISSUE TITLE
File browser clears action list to default when browsing to system root directory

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#8071]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

File browser clears action list to default when browsing to system root directory.

System root directory means drive list "directory" on Windows, "directory" with one item "/" on Linux etc.

There already present issue about this bug: https://github.com/libretro/RetroArch/issues/7365
But this description is much more clear.

### Expected behavior

File browser should work properly.

### Actual behavior

File browser clears action list to default when browsing to system root directory.

### Steps to reproduce the bug (on Windows systems)

1. Make sure "File Browser" directory settings is set to default value
2. Load sameboy core
3. Load a rom via subsystem
4. It will launch this rom instead of allowing to add another rom.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 49fa097903

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
Huh, strange, I can reproduce this too, but it works correctly if the `File Browser` is actually set to something.

@fr500 Any ideas?

**Comment by fr500** [comment]
It's the same as the disk control interface issue.

**Comment by orbea** [comment]
This is also reproducible if the `File Browser` is set and the user navigates to the root directory (`/`) before loading a rom.

**Comment by orbea** [comment]
Navigating to the root directory somehow sends it here instead.

https://github.com/libretro/RetroArch/blob/7ba6ffdfbef827b432d676db5dfd2d273b8f1ad4/menu/menu_displaylist.c#L4963

**Comment by orbea** [comment]
And as soon as the user presses accept on the root directory `menu_label` changes from `subsystem_add` to `favorites`.

https://github.com/libretro/RetroArch/blob/7ba6ffdfbef827b432d676db5dfd2d273b8f1ad4/menu/menu_cbs.c#L220

**Comment by orbea** [comment]
Here the value of `label` seems to return several things at once.

https://github.com/libretro/RetroArch/blob/7ba6ffdfbef827b432d676db5dfd2d273b8f1ad4/libretro-common/lists/file_list.c#L414

When starting RetroArch.
```
label = main_menu
label = main_menu
label = load_core
label = main_menu
label = load_core
label = main_menu
label = load_core
label = main_menu
label = load_content
label = main_menu
label = online_updater
label = main_menu
label = information_list
label = main_menu
label = configurations_list
```
After selecting to load subsystem content.
```
label = subsystem_add
label = quick_menu
label = subsystem_add
label = load_core
label = subsystem_add
label = load_content
label = subsystem_add
label = subsystem_add
label = subsystem_add
label = online_updater
label = subsystem_add
label = information_list
label = subsystem_add
label = configurations_list
label = subsystem_add
label = help_list
label = subsystem_add
label = /home/orbea/games/roms
label = subsystem_add
label = 
label = subsystem_add
label = 
label = subsystem_add
label = 
label = subsystem_add
label = 
label = subsystem_add
label = subsystem_add
label = /home/orbea/games/roms
label = subsystem_add
label = /home/orbea/games/roms
```
After navigating to the root directory.
```
label = subsystem_add
label = /
label = subsystem_add
label = (null)
label = subsystem_add
label = (null)
label = subsystem_add
label = (null)
label = subsystem_add
label = (null)
label = subsystem_add
label = detect_core_list_push_dir
label = subsystem_add
label = subsystem_add
label = detect_core_list_push_dir
label = subsystem_add
label = detect_core_list_push_dir
```
And after pressing the accept button on the root directory.
```
label = favorites
label = /
label = favorites
label = 
label = favorites
label = 
label = favorites
label = 
label = favorites
label = 
label = favorites
label = favorites
label = /
label = favorites
label = /
label = favorites
label = detect_core_list_push_dir
```
I'm not really sure where to take it from here...

**Comment by ofry** [comment]
Thanks, it works on Windows too. Could you make PR?

**Comment by orbea** [comment]
That patch has unfortunate regressions, I think this one should be better.
```
diff --git a/menu/menu_displaylist.c b/menu/menu_displaylist.c
index 118e8cbde5..867aa5695b 100644
--- a/menu/menu_displaylist.c
+++ b/menu/menu_displaylist.c
@@ -8140,6 +8140,7 @@ bool menu_displaylist_ctl(enum menu_displaylist_ctl_state type, menu_displaylist
          break;
       case DISPLAYLIST_DEFAULT:
          menu_entries_ctl(MENU_ENTRIES_CTL_CLEAR, info->list);
+         load_content    = false;
          use_filebrowser = true;
          break;
       case DISPLAYLIST_CORES_DETECTED:
```
Also its less platform specific, can you try this one too?

**Comment by ofry** [comment]
@orbea This patch works too :)

**Comment by orbea** [comment]
Seems to work for the disk control issue too and I haven't found any issues when loading content so I think its good now. :) Thanks for testing!

I did however find an unrelated and preexisting segfault where appending an image will segfault if the path contains a symlink...

**Comment by orbea** [comment]
@twinaphex Yes, seems like it was the same bug. :)

**Comment by orbea** [comment]
Also there is still a preexisting related issue with archived content. https://github.com/libretro/RetroArch/issues/8086

**Comment by orbea** [comment]
The segfault seems much easier to fix. https://github.com/libretro/RetroArch/pull/8087
