### ISSUE TITLE
There is no option to disable the linear filter in RGUI with the Vulkan driver

### ISSUE THREAD

**Issue by aboutafter** [libretro/RetroArch#8073]
## Description

Using the OpenGL driver you can remove the blurriness of the menu disabling "Menu Linear Filter". This option doesn't exist while using Vulkan. 

GL![OpenGL](https://i.imgur.com/lKNONBF.png)
Vulkan![Vulkan](https://i.imgur.com/L0m4Jnm.png)

### Expected behavior

Having the same option as with the OpenGL driver. 

### Actual behavior

The "Menu Linear Filter" option is not there with Vulkan. 

### Version/Commit

- RetroArch: [1.7.5] Compiled by me. 

### Environment information

- OS: [Manjaro GNU/Linux]
- Compiler: [GCC 8.2.1] 64bit

**Comment by jdgleaver** [comment]
Well, that was so easy to fix that it almost feels like I'm missing something (i.e. why wasn't this enabled before?).

I'll make a PR and ask for someone more knowledgeable to review it.

**Comment by RobLoach** [comment]
Bilinear Filtering is the devil. Thanks for fixing this in RGUI :+1:

**Comment by orbea** [comment]
The related PR was merged so I am going to close this, please let us know if there are any further issues.
