### ISSUE TITLE
2 Android cores not latest versions on buildbot (hatari, caprice32)

### ISSUE THREAD

**Issue by 2xtime** [libretro/RetroArch#8102]
Apologies if this is the wrong place, I got asked to report it here. Using Android 4.4.4, the Hatari core from the buildbot http://buildbot.libretro.com/nightly/android/latest/armeabi-v7a/ is dated 13-Nov-2018 https://github.com/libretro/hatari/commit/de5e7434836478bd29c180102c4acb9fa1ed0535 and crashes when running. There have been 6 commits since then.

Caprice32, although the buildbot has built recently, there is no version commit hash at the bottom of the screen (the Windows Retroarch version does) and when running the core it crashes when trying to run a game.

**Comment by orbea** [comment]
These are all core issues.

Closing in favor of issues https://github.com/libretro/hatari/issues/34 and https://github.com/libretro/libretro-cap32/issues/45.
