### ISSUE TITLE
Passwords are not hidden

### ISSUE THREAD

**Issue by Pysis868** [libretro/RetroArch#8103]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

UI does not conceal stored password(s), at least for the achievement system (Cheevos?) setting.

### Expected behavior

Entering password, shows stars.
Complete, value entry in UI shows stars.
Achievements work as expected.

### Actual behavior

Entering password, shows actual characters.
Complete, value entry in UI shows characters.
Achievements work as expected. (Untested)

### Steps to reproduce the bug

1. Open RetroArch via HBMenu 
2. Navigate to Settings > Achievements in default XMB theme.
3. Enable Acheivements
4. Enter Username
5. Enter Password

### Bisect Results

Right when I installed the program, opened, during loading content, going through various menu options viewing most and configuring some.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.5 (Oct 3 2018) (826c77d)

### Environment information

- System: Nintendo Switch
- OS: Horizon OS (v5.0)
- CFW: Atmosphere 0.8.2
- Compiler: GCC (8.2.0) 64-bit
- Architecture: ARMv8
- CPU: 4 core
- Loader: HBMenu 3.0.1

**Comment by Pysis868** [comment]
Don't know why I couldn't find the other issue(s) before.  Probably a duplicate now...

 - #3154
 - #193

**Comment by orbea** [comment]
I agree, but since you filled out the template and explained the issue well lets keep this one instead.

**Comment by fr500** [comment]
the password is blanked after a reload (because it's no longer needed, a token is used instead)

**Comment by orbea** [comment]
So this is a non-issue? I haven't used retroachievements before.

**Comment by fr500** [comment]
it's minor in any case, after you have logged in once it will be hidden

**Comment by natinusala** [comment]
It's an very easy fix. I can have a shot at it.

**Comment by orbea** [comment]
The referenced PR was merged so I am going to close this, please let us know if there are any further issues!

**Comment by Pysis868** [comment]
Great!  I can't do much with C, so it's nice to see this response!
