### ISSUE TITLE
Latest Nightly - Black boxes covering right half & bottom/top left corners of screen upon startup

### ISSUE THREAD

**Issue by TheGershon** [libretro/RetroArch#8109]
![untitled](https://user-images.githubusercontent.com/6880780/51806594-8401dd00-2230-11e9-9f04-2525c447d49f.png)

Upon starting RA, and continuing into launching a core, there are black boxes obscuring the screen as shown above. What I find interesting is that the right one is clearly behind the menu, yet the ones on the left are above. They persist upon loading content, and changing the aspect ratio does nothing.

I should note that I haven't changed any settings since the last time I used RA and this didn't happen. The only thing that has changed is that I have updated to the latest nightly using Stellar.

### Expected behavior

The boxes would not be there, and the content would not be obscured.

### Actual behavior

Black boxes cover parts of the screen, seemingly for no reason

### Steps to reproduce the bug

1. Launch RA
2. Bam

### Bisect Results

Upon updating to the latest nightly

### Version/Commit

- RetroArch: 556b7b19de

### Environment information

- OS: Windows 10, 64bit
- Compiler: MinGW (7.3.0) 64-bit

**Comment by TheGershon** [comment]
I should mention that this happens while using d3d11 and 10, but not gl.

**Comment by orbea** [comment]
Would you be able of bisecting this and finding the first bad commit? What video card do you have?

**Comment by bparker06** [comment]
This is most likely due to the scissor test I added in 29a0789... but I did not experience this issue myself. Can you give us exact steps to reproduce the problem?

**Comment by TheGershon** [comment]
Sorry for the late reply. I'll get on bisecting this right now.

**Comment by TheGershon** [comment]
It was happening on my laptop with a Radeon HD 8210, but it also happens on my desktop with a 5770.

Tested, it happens on the build from 1/27 and 1/26, but not on 1/25 .
