### ISSUE TITLE
D3D12 video driver will not start

### ISSUE THREAD

**Issue by bparker06** [libretro/RetroArch#8110]
## Description

RetroArch crashes with a null pointer dereference when attempting to start using `d3d12` as the video driver:

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x0000000000706546 in DXGIGetCurrentBackBufferIndex (swap_chain=0x0)
    at gfx/common/dxgi_common.h:761
761        return swap_chain->lpVtbl->GetCurrentBackBufferIndex(swap_chain);
```

### Expected behavior

No crash

### Actual behavior

Crash

### Steps to reproduce the bug

1. Set video_driver to d3d12
2. Restart RA
3. crash

### Bisect Results

N/A

### Version/Commit
You can find this information under Information/System Information

- RetroArch: d2edf39 Jan 27 2019

### Environment information

- OS: Windows 10 x64 v1809
- Compiler: gcc 8.2.1

**Comment by bparker06** [comment]
Paging @krzys-h

**Comment by twinaphex** [comment]
This should be fixed now as of @krzys-h's PR.
