### ISSUE TITLE
[Feature request] PipeWire driver

### ISSUE THREAD

**Issue by Sunderland93** [libretro/RetroArch#8158]
See https://github.com/PipeWire/pipewire

**Comment by gouchi** [comment]
There is a [video presentation](https://gstconf.ubicast.tv/videos/pipewire-wants-to-be-your-audio-server-too) also slides deck seem almost the same from [yesterday presentation in Fosdem 2019](https://fosdem.org/2019/schedule/event/pipewire/).

**Comment by hizzlekizzle** [comment]
From what I've seen, PulseAudio and JACK programs are supposed to work with it transparently, right? If this is the case, do we even need an explicit PipeWire driver or can we just rely on the existing Pulse/JACK drivers?

**Comment by Sunderland93** [comment]
> From what I've seen, PulseAudio and JACK programs are supposed to work with it transparently, right?

Yes, just like ALSA apps that don't have Pulseaudio support. But PipeWire is being developed as a replacement for Pulseaudio and JACK in future, just combining their functionality (low latency audio and sound streams).

**Comment by jason-oliveira** [comment]
Now that Pipewire is the default sound daemon for a rather substantial amount of distros now (including Fedora and Calculate Linux), it might be a good time to revisit this issue 2 years later. 

While RA has both pulseaudio and alsa compatability, on a pipewire system these are now routed through pipewire-pulse and pipewire-alsa, respectively. This still technically works, but is a little ridiculous for the JACK side of things, as all the extra functionality provided (including better labelling for output channels, volume control) is not handled. 

It would be really nice to adjust RA's volume using pipewire's tools.

**Comment by cout** [comment]
Is the pipewire API ready for use by applications?

From the FAQ (https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#what-audio-api-do-you-recommend-to-use):

> **What Audio API Do You Recommend To Use?**
> 
> The situation is a bit like GUI toolkits. There are many, each with different use cases. Nobody uses the native display server protocols directly (X11, Wayland) but always through an abstraction layer (GTK, Qt, etc). We recommend that you continue to use PulseAudio, JACK and ALSA API's for now.

**Comment by jason-oliveira** [comment]
considering that it's now being deployed live in multiple distros as the default sound daemon, and apps like Brave Browser have already implemented support based off the current API, it looks like the current API is the defacto API, and we're not going to have the luxury of waiting for a 1.0 release.

**Comment by keithbowes** [comment]
I'd love for there to be a native PipeWire driver (instead of using a compatibility layer), but the big problem I see is that the .pc file is versioned.  mpv goes ahead and checks libpipewire-0.3 and I suppose RetroArch could too, but it would needlessly stop finding it upon the release of 0.4, even if there aren't any API incompatibilities (unless PipeWire decided to keep the name libpipewire-0.3).

Anyway, looking at the documentation, it seems fairly easy to create a PipeWire driver (finding the headers notwithstanding):
1. Create a threaded loop.
2. Get a buffer.
3. Put data into the buffer.
4. Send the buffer through a stream.

**Comment by keithbowes** [comment]
Pipewire 1.0 has been released, so there shouldn't be any worries about stability.  Another thing you can do is in your retroarch.cfg:
```
audio_device = "pipewire"
audio_driver = "alsa"
```

I've been doing that with PulseAudio for years. In my experience, that tends to work better than `audio_driver = "pulse"`.  However, I for one won't be testing out a PipeWire driver.  I got PipeWire/WirePlumber/pipewire-pulse up and running and one day later, my speakers blew up.  It's back to PulseAudio for me for the foreseeable future, as I've never had a speaker blow up with PulseAudio.

**Comment by gouchi** [comment]
@Sunderland93 Please close this issue as PipeWire audio driver has been merged.

Thank you.

**Comment by Sunderland93** [comment]
Thanks!
