### ISSUE TITLE
Version 1.7.6 - Emscripten version - Bug - MacOS - Command key is 'null' and also acts like turbo

### ISSUE THREAD

**Issue by lrusso** [libretro/RetroArch#8167]
Tested in Firefox in MacOS. When you press the Command key, a 'null' message appears and acts like the turbo button, even if the turbo button is not set. It happens in every available core in the Web version.

![screenshot](https://user-images.githubusercontent.com/11498901/52202297-e40a0c00-284c-11e9-9a2d-1a0da1bf0c07.png)

**Comment by orbea** [comment]
Do you know if this is only on firefox or even only on macos?

**Comment by lrusso** [comment]
Also tested and present the bug in Chrome in MacOS. This bug doesn't exists in Windows (tested with Firefox and Chrome), it only happens in MacOS with the Command key.

**Comment by lrusso** [comment]
I tried to bind the turbo button to another key and still when I press the Command key it shows the 'null' message and acts like the turbo button.

**Comment by lrusso** [comment]
Hello, I would like to mention that this bug is still present in the latest version of RetroArch (1.8.2) using Chrome or Firefox in Mac OS.
