### ISSUE TITLE
Broken configure script

### ISSUE THREAD

**Issue by natinusala** [libretro/RetroArch#8168]
`./configure` fails because of the following error:

```
natinusala@natinusala-GP73-Leopard-8RD:~/Documents/RetroArch$ ./configure
Checking operating system ... Linux (Ubuntu 18.04.1 LTS 18.04)
Checking for suitable working C compiler ... /usr/bin/gcc works
Checking for suitable working C++ compiler ... /usr/bin/g++ works
Checking for pkg-config ... /usr/bin/pkg-config
: not found: 3: qb/qb.libs.sh:
: not found: 6: qb/qb.libs.sh:
./configure: 151: qb/qb.libs.sh: Syntax error: word unexpected (expecting "do")
```

Relevant line: https://github.com/libretro/RetroArch/blob/master/qb/qb.libs.sh#L151

**Comment by orbea** [comment]
What shell and shell version are you using? I don't understand why that would fail...

Can you stick this above the `eval` on line 150 and share the output?
```
echo "1 = $1"
echo "2 = $2"
echo "3 = $3"
```

**Comment by natinusala** [comment]
The shell is dash 0.5.8-2.10.

Adding the echo lines doesn't change anything to the output

**Comment by orbea** [comment]
It should give me more information to debug this so I know where in `config.libs.sh` its failing. So please try this and share the output.
```
diff --git a/qb/qb.libs.sh b/qb/qb.libs.sh
index b453541670..a43274719b 100644
--- a/qb/qb.libs.sh
+++ b/qb/qb.libs.sh
@@ -147,6 +147,9 @@ check_pkgconf()
        answer='no'
        version='no'
 
+echo "1 = $1"
+echo "2 = $2"
+echo "3 = $3"
        eval "set -- ${3:-0.0}"
        for ver do
                if $PKG_CONF_PATH --atleast-version="$ver" "$pkg"; then
```

It works here with `dash-0.5.10.2`.

Fwiw the shells I test configure changes against are ash, dash, bash, ksh, loksh, mksh, pdksh, posh, yash, and zsh which all work here...

**Comment by natinusala** [comment]
The issue was the line endings. For some reason, the files had CRLF line endings - `git status` wouldn't detect them, and `git reset --hard upstream/master` kept them in, probably because of the autocrlf config.

What a mess, sorry for the useless issue. I'm never pushing anything from Windows ever again.
