### ISSUE TITLE
Can i compile Retroarch for run in LibreELEC with wayland?

### ISSUE THREAD

**Issue by psyapathy** [libretro/RetroArch#8171]
Hello all!

Can you help me please?

I have a LibreELEC system on my Orange Pi Win Plus and i want to run Retroarch.
Is it possible?
Can i compile Retroarch for run in LibreELEC with wayland?

**Comment by RobLoach** [comment]
Mind creating an issue over at https://github.com/libretro/lakka-libreelec ? That's where all the LibreELEC work goes. Thanks!
