### ISSUE TITLE
N64 Core for PlayStation 

### ISSUE THREAD

**Issue by Mulder97** [libretro/RetroArch#8172]
Hello, do you add the N64 Core for the Playstation in the future? thank you for answer Mulder

**Comment by hizzlekizzle** [comment]
We will put any core that is capable of running on a platform on that platform. If a core isn't available on a given platform, you can rest assured that there is a technical reason that prevents it.

**Comment by Mulder97** [comment]
Thank you for answer. I understand and it's a pity when it was on the old PSP
