### ISSUE TITLE
Retroarch 1.7.6 installed via snap without audio

### ISSUE THREAD

**Issue by Wellvergton** [libretro/RetroArch#8174]
## Description

Retroarch without audio in every core, no matter the configuration.

### Expected behavior

Play the audio.

### Actual behavior

Every core runs without audio, the configuration is correct but there is no sound. As I installed this through snap I reverted to the previous version and the audio is fine. Returning to the current version and running through terminal in verbose mode shows the following messages:

shm_open() failed: No such file or directory
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Protocol error
[ERROR] [SDL audio]: Failed to open SDL audio: ALSA: Couldn't open audio device: Connection refused
[ERROR] Failed to initialize audio driver. Will continue without audio.

### Steps to reproduce the bug

1. Open the retroarch
2. Run some game

### Version/Commit

- RetroArch: 1.7.6/315d962

### Environment information

- OS: Ubuntu 16.04.5

**Comment by orbea** [comment]
Try different audio drivers.

**Comment by orbea** [comment]
Also wrong issue tracker, please reopen here instead.

https://github.com/libretro/retroarch-snap/issues

**Comment by Wellvergton** [comment]
All right. But just for the records, I tried all the audio drivers and configs.

**Comment by Vailure** [comment]
I am having this exact issue, no matter the config/core no audio whatsoever.

**Comment by orbea** [comment]
The issue was reopened here, thanks!

https://github.com/libretro/retroarch-snap/issues/20
