### ISSUE TITLE
How build RetroArch for framebuffer (fbdev)?

### ISSUE THREAD

**Issue by arpsyapathy** [libretro/RetroArch#8177]
Hello!

How build RetroArch for framebuffer (fbdev)? For Mali 400
Need configure with some args?

May you show me example how this build?

**Comment by psyapathy** [comment]
@gouchi
Thank you!
Do you know how build Retroarch for Wayland too?

./configure --enable-opengles --disable-kms --disable-x11 --enable-wayland

?

**Comment by orbea** [comment]
@psyapathy wayland should be enabled automatically if found by the configure script.

Try this.
```
./configure --enable-wayland
make
```
It should error during configure if wayland libraries are not found. Please share the whole configure log if you have any issues.

**Comment by orbea** [comment]
@psyapathy Is this still an issue?

**Comment by crocket** [comment]
In my case, compiling sdl2 with kmsdrm and retroarch with kms enables retroarch to display on framebuffer. But, as soon as it enters libretro-ppsspp, it crashes with SIGSEGV.
