### ISSUE TITLE
JSON Playlist Format Detection

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#8178]
Seen a couple reports where users use the new playlist format, but the menu lists the playlist as the old playlist format....

![4jfplkk8wqe21](https://user-images.githubusercontent.com/25086/52279412-8696bd80-2927-11e9-96c2-5c4229c6c695.jpg)

Source: https://www.reddit.com/r/RetroArch/comments/andpko/ive_been_having_issues_with_retroarch_for_switch/

May need to ease the detection of the new JSON playlist detection.

**Comment by orbea** [comment]
Same issue as https://github.com/libretro/RetroArch/issues/8077?

**Comment by RobLoach** [comment]
Thanks for the link! Marking as Dup. :+1:
