### ISSUE TITLE
Xbox One Controller - Left Analog doesn't work in XMB (It used to work)

### ISSUE THREAD

**Issue by JHorbach** [libretro/RetroArch#8192]
## Description

I can't use my left analog  Xbox One Controller with the XMB (didn't test the others), I can't even remap any button in the Input menu (autoconfig is working though), when I load a game they work just fine.

### Expected behavior

They used the work in the menu.

### Actual behavior

Analog doesn't move between menu options.

### Steps to reproduce the bug

The Xbox One Controller is connected through Wired Cable, Retroarch finds it, and it works perfectly in games, even my hotkeys works, but the analog doens't move the menu options as it used to do, I tried to change the option th Retropad/analog, Left Analog D-PAD, no help.

### Version/Commit
I'm using the Commit 11b02125dc (I can't remember when it started, but it was the since last week)

### OS/ Input Driver
Windows 10 1803 x64
Input Driver - dinput
Joypad - xinput

**Comment by orbea** [comment]
Not enough info to proceed...

If you want someone to actually help figure this out then please correctly fill out the issue template.

Especially important details that are missing is when it broke (Please bisect this) and what OS / input driver are you using?

**Comment by JHorbach** [comment]
I update my info with the commit, OS version, input and joypad drivers, and a little more info about what is happening.

**Comment by orbea** [comment]
> EDIT: I delete my config, and it's working again. Don't know what messed it up.

You must of set something from the default which broke it, try driver or input settings?

**Comment by JHorbach** [comment]
I consider myself pretty experienced in Retroarch, my settings are configured a long time ago, I didn't change anything after that.

**Comment by orbea** [comment]
Maybe the setting only started breaking the feature after you set it or there is something else going on with the configuration file?

What I'm trying to say is I'm not sure we can help more without knowing what setting caused this behavior. :)

**Comment by JHorbach** [comment]
I really don't know, maybe something broke with the update, it's the only thing I can think off, I do update every day with stellar.

**Comment by Awakened0** [comment]
Something I found out about awhile ago; if you disable autoconfig and use manual binds, the left analog doesn't work in RA menus for some reason.

**Comment by JHorbach** [comment]
Interesting, maybe it was the case back then.
