### ISSUE TITLE
[MacOS] hard crash (reboot needed) when applying shader

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#8207]
1.7.6 stable & nightly 

Not tried metal or CG builds as there currently broken.

**Comment by cold-brewed** [comment]
Metal nightly should be fixed now. Could you grab the latest and see if it is any better? 

You may need to wipe out your config file first - I sometimes have issues going back and forth between the different macOS versions otherwise.

**Comment by gingerbeardman** [comment]
Fixed in the last 6 hours? If so I'll try it later tonight

**Comment by cold-brewed** [comment]
Sorry, I was referring to the building and packaging of the metal dmg file, that was broken until a few days ago. 

I last built metal locally a few days ago and it was fine. I just rebuilt from master and while it builds, there are some display issues that I believe are related to some merges (menu widgets perhaps?) in the past few days.

**Comment by gingerbeardman** [comment]
OK yes this is no longer an issue on the latest couple of Metal nighties. 

Can be closed.

**Comment by cold-brewed** [comment]
If you can build locally and are just looking to get playing, building ceb439c should at least get you going until the other issues are addressed.

**Comment by gingerbeardman** [comment]
thanks for that!

**Comment by cold-brewed** [comment]
Metal nightly build should be fine now (as of 2019-02-08). Can you give that a try (and make sure the metal driver is selected)?

I haven't tested the non-metal or CG build, but if your system is capable the metal version is the way to go.

**Comment by gingerbeardman** [comment]
will try asap tomorrow

**Comment by gingerbeardman** [comment]
this now works for me with 2019-02-10 nightly, cheers!
