### ISSUE TITLE
Switch Retroarch

### ISSUE THREAD

**Issue by TH3GOD88** [libretro/RetroArch#8239]
Retroarch crashing

Okay, every time I try to load a game on Mupen64 core it crashes Retroarch.
Super Nintendo games work fine

I expected it to work.

### Actual behavior
Blank screen and then crash with an error. A lot of times it is error 2168-0001 and 2168-0002

### Steps to reproduce the bug

1. Load Retroarch
2. Load Core
3. Launch N64 game

### Bisect Results

Installed Retroarch through HB app store and then nightly build.
Also tried the NSP
- RetroArch: 
Retroarch 1.7.6
Ive tried from 12/28/18 to the most recent 2/8/19 version

- OS: Atomsphere and SX OS

**Comment by orbea** [comment]
Sounds like a core issue, what n64 core are you using?

**Comment by TH3GOD88** [comment]
I've tried Mupen and Mupen Next

**Comment by TH3GOD88** [comment]
If you need any additional info, please do not hesitate to ask and tell me where to find it.

**Comment by orbea** [comment]
Could you try any other GL core?

**Comment by TH3GOD88** [comment]
I would, could you tell me a little more on what you mean? I've tried Snes9x and Snes9x 2010 and they load games just fine. So if there is another thing you want me to try I will.

**Comment by orbea** [comment]
On second thought I don't see any other GL cores...

https://github.com/libretro/libretro-super/blob/master/recipes/nintendo/libnx

I'm just not sure if this is a RetroArch issue or a core issue which would belong on the core trackers...

https://github.com/libretro/mupen64plus-libretro/issues
https://github.com/libretro/mupen64plus-libretro-nx/issues

**Comment by TH3GOD88** [comment]
A lot of other people are able to run N64 games. I've only seen a few people not be able to.

**Comment by TH3GOD88** [comment]
Well I posted it onto the other one, so I will see if I can get some light from either one.

**Comment by TH3GOD88** [comment]
https://github.com/libretro/mupen64plus-libretro/issues/93#issuecomment-462096881
