### ISSUE TITLE
reicast on android (firetv) doesn't work

### ISSUE THREAD

**Issue by DieterLasers** [libretro/RetroArch#8240]
– starting games crashes RetroArch
– when RetroArch doesn't crash the games start but are not playable due to choppy video and sound
– for comparison: reicast downloaded from the google play store and installed on the FireTV works okay

**Comment by DieterLasers** [comment]
– Disabling DSP helps with the game film sequences but not in the game
– switching from per-triangle to per-strip alpha sorting makes it even worse

i also tried:
– Enable Div Matching
– Decrease resolution
– threaded rendering ON
– synchronous rendering ON
– framerate normal

in the quickmenue. but the games are still not playable

**Comment by orbea** [comment]
Is this only with reicast?

If yes, please use the correct issue tracker, thanks!

https://github.com/libretro/reicast-emulator/issues

**Comment by DieterLasers** [comment]
oh sorry, i didn't know that. thanks!

**Comment by DieterLasers** [comment]
oh sorry, i didn't know that. thanks!

**Comment by orbea** [comment]
Thanks for making the issue for the correct repo!

https://github.com/libretro/reicast-emulator/issues/482
