### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#8248]
### Description

Attempting to compile retroarch without a menu doesn’t work.

### Expected behavior

Retroarch should have no menus whatsoever and still be able to run games via command-line

### Actual behavior

Retroarch compiles, but it has a menu

### Steps to reproduce the bug

1. Download source code for retroarch
2. Attempt to compile with the no menu flag
3. Open your built retroarch and see it still has a menu and be disappointed 

### Bisect Results

I attempted to compile recently without a menu and it failed

### Version/Commit

Latest?

### Environment information

- OS: Windows 10 Professional
- Compiler: msys2

**Comment by orbea** [comment]
What do you mean exactly that it has a menu? 

Can you show what configure arguments you are using exactly and a full build log?

Fwiw `./configure --disable-menu && make` still works fine on Linux with the master.

**Comment by hhromic** [comment]
On my Windows 7 x64 machine using MSYS2, `./configure --disable-menu && make` produced a RetroArch binary that doesn't have any menu. I can launch it with `retroarch -f` and will get a fullscreen RA, if I press the F1 key, nothing happens (no menu). I was not disappointed.

    $ ./retroarch --features
    (...)
      SDL2:
                SDL2 input/audio/video drivers: yes
      Vulkan:
                Vulkan video driver: yes
      OpenGL:
                OpenGL   video driver support: yes
    (...)

The generated `retroarch.cfg` file doesn't even have the related `input_menu_toggle` option available.

**Comment by orbea** [comment]
You should also be able to use `./retroarch --menu` to get the dummy core and pressing `F5` should enable the Qt companion ui if its enabled even without a menu. Or you can load content directly from the command-line with `./retroarch -L /path/to/core /path/to/content`.

Thanks for testing, I'm still not sure I understand @Fatty69420's issue?

**Comment by Fatty69420** [comment]
I mean absolutely no way of using the executable other then from the command-line

**Comment by Fatty69420** [comment]
For example, it opens then should close instead. But with the command line it runs your game

**Comment by orbea** [comment]
@Fatty69420 I am not sure I understand? With `--disable-menu` there is no menu and its mostly useful for running from the commandline. If you want a menu you should not use that configure argument.

**Comment by Fatty69420** [comment]
i tried that and i got this
```
gfx/drivers_font/../common/d3d_common.h:60:4: error: unknown type name ‘INT32’
    INT32 pool;
```

**Comment by orbea** [comment]
Can you show us the full command line you used and the build log?

**Comment by twinaphex** [comment]
I pushed this commit -

https://github.com/libretro/RetroArch/commit/691462e3d6984187cfe899f6dc116ac9996fcfe9

Let's see if it compiles with that. We indeed should not be using these frivolous Win32 typedefs inside a header like that if we can help it.
