### ISSUE TITLE
Retroarch Crashes When Load Any Shader MAC OSX

### ISSUE THREAD

**Issue by dragonstory** [libretro/RetroArch#8249]
Hello
Lastest version of Retroarch 1.7.6 ( stable and nightly build ) crashes when you try to load any of Shaders. GLSL or GL both of are crashes. It was ok with 1.7.5

System: Mac OSX High Sierra

**Comment by ofry** [comment]
Is it related? https://github.com/libretro/RetroArch/issues/8207

**Comment by cold-brewed** [comment]
Could you try the latest metal [nightly](https://buildbot.libretro.com/nightly/apple/osx/x86_64/)?

**Comment by dragonstory** [comment]
Thanks for your answer. Yeah metal version is working without problem now. Thanks...

**Comment by cold-brewed** [comment]
Thanks. @orbea this can be closed.
