### ISSUE TITLE
(Windows) Performance lost in 1.7.6

### ISSUE THREAD

**Issue by Liviki980** [libretro/RetroArch#8251]
## Description

Upon updating to 1.7.6, the performance has worsened, framerate shows up at 20 fps regardless if anything is running in the background, even upon a fresh install with no original configuration. The 1.7.5 version had ran perfectly fine prior but 1.7.6 causes my system to slow down, sometimes followed by a crash.

### Expected behavior

Stable frame rate on the menus

### Actual behavior

Stuttering frame rate of 20 at the maximum, followed by a crash.

### Steps to reproduce the bug

1. Loading the Retroarch 1.7.6 executable from the buildbot stable repository via the portable zip files.

### Bisect Results

This started happening after downloading 1.7.6 from the buildbot, the portable versions, but doing so made by system lock up and require a force restart, further testing with an isolated download, seperated from the config files still show a 20 fps frame rate and high crash rate, adjusting video and audio drivers to DSound, Null, GL, none of those change anything. Switching back to 1.7.5 via a backup of files shows none of these issues.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Version 1.7.6 Stable Release

### Environment information

- OS: Windows 10 Home !803 x86 (32-Bit)
- System Specs: Card: Intel Atom x5 Z8350, RAM: 2 GB, Hardware: NuVision Laptop

**Comment by bparker06** [comment]
Since we cannot reproduce the problem ourselves, we would need you to perform a bisect to figure out exactly what code caused this to start happening.

**Comment by stellarporter** [comment]
@Liviki980
Does it happen in windowed mode and fullscreen? Could you try a few test builds?

https://github.com/libretro/RetroArch/commit/80f89479bfc35bc19f517dd1bd90eb033b08a14b https://ci.appveyor.com/project/stellarporter/retroarch/builds/23479108/artifacts
https://github.com/libretro/RetroArch/commit/c9bb537cdd33736c800a4c9ed30f8ead33bf4369 https://ci.appveyor.com/project/stellarporter/retroarch/builds/23479026/artifacts
https://github.com/libretro/RetroArch/commit/006a002f195a5493645bde00f50b995adbc43704 https://ci.appveyor.com/project/stellarporter/retroarch/builds/23469818/artifacts
https://github.com/libretro/RetroArch/commit/0486979bc9fb87ba72c734e228fead018e3fb72f https://ci.appveyor.com/project/stellarporter/retroarch/builds/23469954/artifacts

I'm wondering if it's related to this one: "[Font]: Using font rendering backend: stb-unicode."

**Comment by Soschu1** [comment]
Hi there,

i have the same problems like Liviki1980.

1.75 works well, 1.76 and 1.77 causes slowdowns, followed by a crash. 
Build 1.76 needs a lot more memory than 1.75.
Slowdowns only with xmb, ozone works fast and without problems.

OS: Windows 8.1 (32-bit)
System Specs: Intel Atom Z3736F, RAM: 2 GB 

I have tried the 4 test builds
80f8947 works well
c9bb537 slowdown and crash
006a002 works well
0486979 slowdown and crash

**Comment by bparker06** [comment]
2GB is not enough memory to really even use Windows 8, I have no idea why devices are sold with so little RAM. As soon as it boots up there is already 80% memory used if not more.

**Comment by Soschu1** [comment]
It is a cheap HTPC for Kodi and Retroarch, no more and no less.

Maybe i have do something wrong, because before 1.76 it worked without problems for years, despite only 2GB memory.

**Comment by twinaphex** [comment]
Honestly, the information you posted so far is far too vague for anybody to realistically do anything with.

I'd try seeing if the Direct3D 11 driver performs better for you in the menu instead of OpenGL. Try things like that. It might just be a config setting or your GPU just having terrible performance with OpenGL. Maybe the issue is even outside of RetroArch and it's just a Windows update that regressed performance. There are a ton of variables here.

**Comment by twinaphex** [comment]
Alternatively, try disabling menu widgets, disable 'Icon Shadows' (Settings -> User Interface -> Appearance).

Otherwise, try running another menu driver like Ozone or MaterialUI.
