### ISSUE TITLE
Commit 769612c274b1bce97acb11e651c3cf462cdf7af3 broke compilation on Amlogic

### ISSUE THREAD

**Issue by shantigilbert** [libretro/RetroArch#8274]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch fails to build on Amlogic

### Expected behavior

compile 

### Actual behavior
Gives an error that glesv2 is not found

### Steps to reproduce the bug

1. Try to cross compile for Amlogic (e.g in Lakka)
 it will give this error

```
Checking presence of package glesv2 ... no
Forced to build with package glesv2, but cannot locate. Exiting ...
```
and before it gave this message
```
Checking presence of package glesv2 ... no
Checking existence of -lGLESv2 ... yes
```

### Bisect Results

It started happening after commit 769612c274b1bce97acb11e651c3cf462cdf7af3

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 769612c274b1bce97acb11e651c3cf462cdf7af3

### Environment information

- OS: Ubuntu 18

**Comment by bparker06** [comment]
paging @orbea

**Comment by orbea** [comment]
That commit almost certainly did not break it....I changed the configure output only, not the logic. If anything broke there it would be the output and not the the configure checks.

@shantigilbert What configure arguments are you using?

**Comment by shantigilbert** [comment]
It was that commit as the one right before that one, which is a82cc31 compiles and works fine.

you can see the package I am using here. 
https://github.com/shantigilbert/CoreELEC/blob/Sx05RE/packages/sx05re/libretro/retroarch/package.mk

and these are the configure options

```
--enable-opengles --disable-kms --disable-x11 --enable-mali_fbdev --disable-qt --enable-neon --disable-vg --disable-sdl --disable-ssl --enable-zlib --enable-freetype --disable-discord
```

which worked fine before that commit

**Comment by orbea** [comment]
It still doesn't make sense why that commit broke it, but given your configure arguments and the change in behavior I would strongly suspect PR https://github.com/libretro/RetroArch/pull/8247 instead.

The relevant configure checks weren't ideal anyways and its one of the parts of the script that is hard for me to test due to not having an arm linux device to test.

@shantigilbert I think this will work, can you test it on your side to be sure?
```
diff --git a/qb/config.libs.sh b/qb/config.libs.sh
index 1a698f4c45..e2cf64781f 100644
--- a/qb/config.libs.sh
+++ b/qb/config.libs.sh
@@ -409,11 +409,8 @@ if [ "$HAVE_EGL" = "yes" ]; then
          add_define MAKEFILE OPENGLES_LIBS "$OPENGLES_LIBS"
          add_define MAKEFILE OPENGLES_CFLAGS "$OPENGLES_CFLAGS"
       else
-         HAVE_OPENGLES=auto; check_pkgconf OPENGLES "$VC_PREFIX"glesv2
-         if [ "$HAVE_OPENGLES" = "no" ]; then
-            HAVE_OPENGLES=auto; check_lib '' OPENGLES "-l${VC_PREFIX}GLESv2 $EXTRA_GL_LIBS"
-            add_define MAKEFILE OPENGLES_LIBS "-l${VC_PREFIX}GLESv2 $EXTRA_GL_LIBS"
-         fi
+         HAVE_OPENGLES=auto
+         check_val '' OPENGLES "-l${VC_PREFIX}GLESv2 $EXTRA_GL_LIBS" '' "${VC_PREFIX}glesv2" '' '' true
       fi
    fi
    check_val '' VG "-l${VC_PREFIX}OpenVG $EXTRA_GL_LIBS" '' "${VC_PREFIX}vg" '' '' false
```

**Comment by shantigilbert** [comment]
Not sure why that commit would break it, but I tested all the commit from the last one I knew was working and it breaks on that commit exactly. 

Using the patch you provided I get the same error

```
Checking presence of package glesv2 ... no
Forced to build with package glesv2, but cannot locate. Exiting ...

```

**Comment by orbea** [comment]
I changed it from checking if `HAVE_OPENGLES=yes` before failing when its not found to checking `USER_OPENGLES=yes` which resulted in better behavior elsewhere. The script is explicitly setting `HAVE_OPENGLES=auto` before checking the pc file so using `--enable-opengles` didn't correctly fail and you got the "correct" behavior...

@shantigilbert Can you try this instead?
```
diff --git a/qb/config.libs.sh b/qb/config.libs.sh
index 1a698f4c45..a4a1406363 100644
--- a/qb/config.libs.sh
+++ b/qb/config.libs.sh
@@ -409,11 +409,7 @@ if [ "$HAVE_EGL" = "yes" ]; then
          add_define MAKEFILE OPENGLES_LIBS "$OPENGLES_LIBS"
          add_define MAKEFILE OPENGLES_CFLAGS "$OPENGLES_CFLAGS"
       else
-         HAVE_OPENGLES=auto; check_pkgconf OPENGLES "$VC_PREFIX"glesv2
-         if [ "$HAVE_OPENGLES" = "no" ]; then
-            HAVE_OPENGLES=auto; check_lib '' OPENGLES "-l${VC_PREFIX}GLESv2 $EXTRA_GL_LIBS"
-            add_define MAKEFILE OPENGLES_LIBS "-l${VC_PREFIX}GLESv2 $EXTRA_GL_LIBS"
-         fi
+         check_val '' OPENGLES "-l${VC_PREFIX}GLESv2 $EXTRA_GL_LIBS" '' "${VC_PREFIX}glesv2" '' '' true
       fi
    fi
    check_val '' VG "-l${VC_PREFIX}OpenVG $EXTRA_GL_LIBS" '' "${VC_PREFIX}vg" '' '' false
diff --git a/qb/qb.libs.sh b/qb/qb.libs.sh
index 4391372983..aec2e927e6 100644
--- a/qb/qb.libs.sh
+++ b/qb/qb.libs.sh
@@ -152,6 +152,7 @@ check_lib()
 # $2 = package ['package' or 'package package1 package2', $1 = name]
 # $3 = version [checked only if non-empty]
 # $4 = critical error message [checked only if non-empty]
+# $5 = force check_lib when true [checked only if non-empty, set by check_val]
 check_pkgconf()
 {      tmpval="$(eval "printf %s \"\$HAVE_$1\"")"
        eval "TMP_$1=\$tmpval"
@@ -197,6 +198,7 @@ check_pkgconf()
        eval "HAVE_$val=\"$answer\""
 
        if [ "$answer" = 'no' ]; then
+               [ "${5:-}" != 'true' ] || return 0
                [ "$err" ] && die 1 "$err"
                setval="$(eval "printf %s \"\$USER_$val\"")"
                if [ "$setval" = 'yes' ]; then
@@ -301,13 +303,13 @@ check_switch()
 # $7 = critical error message [checked only if non-empty]
 # $8 = force check_lib when true [checked only if non-empty]
 check_val()
-{      check_pkgconf "$2" "$5" "${6:-}" "${7:-}"
+{      check_pkgconf "$2" "$5" "${6:-}" "${7:-}" "${8:-}"
        [ "$PKG_CONF_PATH" = "none" ] || [ "${8:-}" = true ] || return 0
        tmpval="$(eval "printf %s \"\$HAVE_$2\"")"
        oldval="$(eval "printf %s \"\$TMP_$2\"")"
        if [ "$tmpval" = 'no' ] && [ "$oldval" != 'no' ]; then
                eval "HAVE_$2=auto"
-               check_lib "$1" "$2" "$3" '' '' '' "$4" ''
+               check_lib "$1" "$2" "$3" '' '' '' "${4:-}" "${7:-}"
        fi
 }
 
```

**Comment by shantigilbert** [comment]
What version do you have as this patch fails with the current commit (3b131ee) and the one that started the problem (769612c)

```
APPLY PATCH (common)      packages/sx05re/libretro/retroarch/patches/retroarch-99-temp.patch
patching file qb/config.libs.sh
patching file qb/qb.libs.sh
Hunk #1 succeeded at 154 with fuzz 2 (offset 2 lines).
Hunk #2 FAILED at 198.
Hunk #3 FAILED at 302.
2 out of 3 hunks FAILED -- saving rejects to file qb/qb.libs.sh.rej

```

**Comment by orbea** [comment]
Sorry, I'm must of pasted it wrong or something...

How about this diff? https://github.com/orbea/RetroArch/commit/13bc4153a6c6f352615fb4e31ec89fcd5d66ee9e.diff

**Comment by shantigilbert** [comment]
This one works
```
    APPLY PATCH (common)      packages/sx05re/libretro/retroarch/patches/retroarch-99-temp.patch
patching file qb/config.libs.sh
patching file qb/qb.libs.sh
```

but still the same error:

```
Checking presence of package glesv2 ... no
Forced to build with package glesv2, but cannot locate. Exiting ...
```

**Comment by orbea** [comment]
Sorry, that was a stupid mistake... Please try one more time.

https://github.com/orbea/RetroArch/commit/b6fd6feceb68b2cb546a7eef4ad8064eacf4b963.diff

**Comment by shantigilbert** [comment]
That one worked :)

```
Checking presence of package glesv2 ... no
Checking existence of -lGLESv2 ... yes
```

Thanks for your quick help!

**Comment by orbea** [comment]
Thanks for testing, it was very helpful!

I made a PR here. https://github.com/libretro/RetroArch/pull/8278
