### ISSUE TITLE
Dolphin_libretro.dll GFX FIFO with one game

### ISSUE THREAD

**Issue by Kappa1982** [libretro/RetroArch#8277]
Launching Gamecube Resident Evil 1 (Europe Version GBIP08) with 
-Retroarch (different version) and dolphin_libretro.dll 
-Dolphin 5
-Launchbox (launching Retroarch or Dolphin)
gives always GFX FIFO error and close the program.

The md5 of the game is correct.
The game works only with old versions of Dolphin (4.2,4.1,etc) but in this case the steam controller (that works with launchbox, retroarch and other GameCube games) doesn't work.

**Comment by orbea** [comment]
This is the wrong repo, can you please open the issue for the correct issue tracker?

If this works with upstream and not the libretro core try this tracker.

https://github.com/libretro/dolphin/issues

If its broken upstream too please try.

https://bugs.dolphin-emu.org/projects/emulator/issues?set_filter=1&tracker_id=1

Thanks!

**Comment by RobLoach** [comment]
Regarding the Steam Controller, feel free to remap your controls, and then submit an update to https://github.com/libretro/retroarch-joypad-autoconfig .

Thanks! Going to close this one for now. Link the dolphin issue when you open it, if you'd like.
