### ISSUE TITLE
Memory details not shown in OSD with gl

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#8279]
## Description

Settings>Onscreen display>Onscreen notifications>Include memory details
isn't working at all here on win7 x64 latest nightly.

### Expected behavior

It's supposed to show the memory usage after the FPS/framecount OSD message.

### Actual behavior

No change at all with it on or off.

Perhaps it stopped working when FPS and frame count got separated into 2 independent messages?

Memory display code is [here](https://github.com/libretro/RetroArch/blob/master/gfx/common/dxgi_common.c#L310)

Other fps messages code is [here](https://github.com/libretro/RetroArch/blob/master/gfx/video_driver.c#L2428)

And some potential issues:
-no video_info->memory_show in video_driver.c
-fps_show used several times in menu_setting.c
-no statistics_show in config.def.h

**Comment by Tatsuya79** [comment]
As I was just told, it's working with d3d11. 
It seems to be working only with d3d drivers atm.

**Comment by Tatsuya79** [comment]
So it's not really a bug as it was designed like that, can be turned into a feature request I guess.

I tried to fix the other issues here:
https://github.com/libretro/RetroArch/pull/8282

**Comment by bparker06** [comment]
I suggest moving the memory code to a platform-agnostic location and using `frontend_driver_get_used_memory()` instead so we can support more platforms easily.

**Comment by bparker06** [comment]
I did this and added the memory display for a bunch of other drivers, in 5e177c7.

**Comment by Tatsuya79** [comment]
Good work, Guess I can close this.

**Comment by Ferk** [comment]
The fix was Windows-specific, right? it's not showing in Linux
