### ISSUE TITLE
[macOS] 1.7.6 Metal2 version dmg is not full package

### ISSUE THREAD

**Issue by wrldwzrd89** [libretro/RetroArch#8290]
This is exactly the same issue as #7359, but for 1.7.6, rather than 1.7.5.

**Comment by orbea** [comment]
@wrldwzrd89 I think this is fixed in the nightlies, can you try a more recent version?

**Comment by cold-brewed** [comment]
Yes this is fixed in the nightlies. Please download the latest nightly and you should be all set.

**Comment by wrldwzrd89** [comment]
That fixed it! Thanks!
