### ISSUE TITLE
Xinput: having more than 4 wireless Xbox One gamepads connected at once

### ISSUE THREAD

**Issue by Gagert** [libretro/RetroArch#8304]
## Description

I have in total 8 wireless Xbox One gamepads for my PC. Some days ago I tried running any of the Super Bomberman games on the SNES (using the snes9x2010_libretro.dll) with 5 of the controllers connected wireless with xinput as the Joypad driver, but only the first 4 controllers responded after selecting a 5 player match in Super Bomberman 1-5 . The same happened with Columns 3 for the Sega Genesis using the Genesis Plus GX core; only 4 of the 5 controllers worked after selecting a 5 player matchup. 

I strongly suspect that there's an issue with the xinput API in general meaning that the API itself still carries over the old limit of max 4 controllers at once  (since I have to switch to dinput on some modern games if there is more than 4 players with Xbox One wireless gamepads connected to the PC using the Xbox One Wireless Adapter).

I tried some of the other Joypad drivers for a short time; neither dinput or HID auto-detected the Xbox One gamepads, and the sdl2 input driver also seemed to support a limit of 4 Xbox One Wireless controllers using the Xbox One Wireless Adapter.

If the issue is the xinput API itself, it would be nice if it was possible to switch to either HID or dinput (even though dinput is ancient) and having the Xbox One gamepads being auto-detected, or increase the controller limit on the sdl2 input driver (if that's technically possible).

Keep in mind that I'm not using the most recent build of RetroArch yet, I'm still on the at the time previous version RetroArch 1.7.5

### Expected behavior

Since the Xbox Wireless Adapter supports 8 Xbox One gamepads at once, I was a little surprised that it seems that the old limit of max 4 players on the xinput API is still there. I might be wrong, but I suspect the xinput API is the issue here (I've sent a feedback report to Microsoft regarding the suspected xinput wireless gamepad limit).

### Actual behavior

Only the first 4 Xbox One wireless controllers seems to be initialized after booting a game rom in RetroArch, starting from controller 0, 1, 2 and 3. Even though I have selected Max Users in the input section as 5.

### Steps to reproduce the bug

Xbox One Wireless Adapter + more than 4 Xbox One Wireless gamepads, starting any of the Super Bomberman roms with the Snes9x 2010 core or starting Columns 3 with the Genesis Plus GX core.

### Bisect Results

I suppose this always have been an issue, but I suppose not many people are equipped with more than 4 wireless Xbox One gamepads + Xbox One Wireless Adapter.

### Version/Commit

RetroArch 1.7.5

### Environment information

Windows 10 Home 64-bit
i7-4790K, 16gb ram, GeForce GTX 1080

**Comment by krzys-h** [comment]
Xinput API does indeed have a limit to 4 devices and there is no way around it. Dinput has other limitations iirc - no vibration feedback and left and right triggers are treated as one button. SDL2 probably just uses dinput and/or xinput internally and probably only works properly when used with sdl2 video. I have no idea about HID.

The modern WinRT Gamepads API probably supports more if it was implemented, but it is available on Windows 10 only... I wonder if there are any other APIs which support that many controllers

**Comment by bparker06** [comment]
dinput most certainly supports force feedback, even better than xinput IIRC

**Comment by fr500** [comment]
He's referring to xinput rumble only not actual force feedback.

**Comment by Gagert** [comment]
I didn't know about the newer Gamepad API for Windows 10. I supposed this will be a successor to xinput; my initial thoughts was that xinput was going to be the only current- and supported controller API from Microsoft to be used with Xbox One/Xbox 360 gamepads on PC.

I did not find that much info regarding the Gamepad API from Microsoft on the web (in terms of YouTube videos and even a Wikipedia page as with both directinput and xinput).

Maybe RetroArch/libretro could get support for the Microsoft Gamepad API in the future, if this API removes the xinput limit of only 4 wireless Xbox One gamepads connected at once?

**Comment by Gagert** [comment]
With the current version of RetroArch, 1.8.1, there's no longer an issue with dinput not recognizing Xbox gamepads. Now I'm able to just switch from xinput to dinput on games that support more than 4 players, and I then make a separate game override for those particular games & they work without issues with more than 4 Xbox gamepads.

I suppose I can close this issue then, as it currently seems like xinput never is going to breach the old legacy limit of max 4 gamepads connected. Let's just hope that for Windows 10 users that the new Microsoft Gamepad API will replace the xinput api in the long run, so we won't have to switch between xinput and the old and deprecated dinput api for games that support more than 4 players in the future.

**Comment by Nemirtingas** [comment]
> 
> 
> Xinput API does indeed have a limit to 4 devices and there is no way around it. Dinput has other limitations iirc - no vibration feedback and left and right triggers are treated as one button. SDL2 probably just uses dinput and/or xinput internally and probably only works properly when used with sdl2 video. I have no idea about HID.
> 
> The modern WinRT Gamepads API probably supports more if it was implemented, but it is available on Windows 10 only... I wonder if there are any other APIs which support that many controllers

Hi,

I'm working on an open-source XInput library. Looks like the underlying xbox driver does support more than 4 controllers, the limitation is in the XInput.dll.

Here's my project page: https://gitlab.com/Nemirtingas/open_xinput, maybe it can help you to break the 4 controllers limitation ?
I successfully plugged 6 controllers and got their states & vibration.

**Comment by Gagert** [comment]
This sounds very interesting, but I can't seem to compile the open-source Xinput library because of a missing xinput header file (xinput.h). I'm not much into programming and compiling, but if you could provide a compiled xinput.dll file for the open-source variant (if it's legal), I would be very happy to check this out and do my testing.

When the xinput.dll file is compiled, is it possible to just place the file in the selected application/game folder to make the application/game use this modified xinput-file instead of the default one provided by Microsoft?

**Comment by Nemirtingas** [comment]
> 
> 
> This sounds very interesting, but I can't seem to compile the open-source Xinput library because of a missing xinput header file (xinput.h). I'm not much into programming and compiling, but if you could provide a compiled xinput.dll file for the open-source variant (if it's legal), I would be very happy to check this out and do my testing.
> 
> When the xinput.dll file is compiled, is it possible to just place the file in the selected application/game folder to make the application/game use this modified xinput-file instead of the default one provided by Microsoft?

I've made a zip with my xinput1_3 & xinput1_4: http://www.mediafire.com/file/8rcennwyen0dqs9/xinput.zip

It should work with a simple dropin the game folder, at least on games that I tested it does.

But you will need to make retroarch use more than 4 xinput controllers. This xinput implementation can handle 8 controllers.

In this file https://github.com/libretro/RetroArch/blob/master/input/drivers_joypad/xinput_joypad.c, you will have to add 4 more controllers in the configuration at least, I didn't look in the full source so maybe there are other places where to modify the XInput device count ?

**Comment by AlanRibas** [comment]
> I've made a zip with my xinput1_3 & xinput1_4: http://www.mediafire.com/file/8rcennwyen0dqs9/xinput.zip

Could you tell me if everything you said about these files would work in a video game emulator?
I have some video game emulators on my computer and I can't get the 5th joystick to work.
If I put these .dll files in the respective folder of the emulator's executable, would that make the 5th joystick become enabled for use?

**Comment by Nemirtingas** [comment]
I would say that my xinput implementation allows any game to use more than 4 controllers if they are actually aware that there can be more than 4. As Microsoft hardcoded a limit of 4 controllers, I would say that anything built against the original library won't work with more than 4.
Project like RetroArch could support more than 4 as they can modify the max controller limit.
If your video game emulator supports more than 4 xinput controllers, then yes, just copying the xinput.dll will allow it to use more than 4.

**Comment by AlanRibas** [comment]
Thank you so much for your answer. Could you just ask me one more question?

About that part that said

  "As Microsoft hardcoded a limit of 4 controllers, I would say that anything built against the original library won't work with more than 4."

I cannot understand the following. If microsoft really limited the use of xinput to just 4 joysticks, why did it develop a wirelles receiver that supports 8 joysticks (I have one of these receivers and I have already tested it with 8 joysticks. All are identified by windows 10 and work normally)?

I don't understand how the 8 joysticks are identified by windows 10, but the game / emulator cannot see it.

ps.....This seems to be something that bothers people a lot. Is microsoft not interested in solving this problem?

**Comment by Nemirtingas** [comment]
Controllers are detected by Windows, and its not limited to 4. Its the XInput library that is.
Before XInput you would use DirectInput and even before that RawInput/HID.
With XInput, there is a standardised usb protocol, its easier to get controller mapping without having to build a new configuration for every type of controller like you would do with directinput.
XInput button 1 is controller's button 1.
On directinput, button 1 could be button 3 on controller 1 and button 1 on controller 2, so you have to configure that.
XInput was designed for XBox and then ported to Windows.
Microsoft is developping new ways to access controllers that supports more than 4 controllers but it will not support more than 4 controllers with XInput.

**Comment by AlanRibas** [comment]
I understand. Many thanks for the reply.
