### ISSUE TITLE
Add settings to force screen orientation on Android

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#8330]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
It would be good to have a setting (possibly under video) to force (or maybe remember the last used) screen orientation.

This would allow users to unlock orientation lock once, enter retroarch, save the setting and keep using it in the last used orientation.
I mention this because I have my phone on portrait at all times and I have to unlock orientation lock just to get it into landscape.

I figure this should be a setting, and maybe a "Quick menu" orientation switch entry (but one/either would be enough)

**SIDENOTE:** figure on closing RA it should restore the original orientation, at least on desktop, on android this doesn't seem to important.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
Related:
https://github.com/libretro/RetroArch/issues/4464
https://github.com/libretro/RetroArch/issues/1972

**Comment by bparker06** [comment]
What happens if the user leaves their device on auto-rotate and wants RA to work that way too? With the setting the way it's described, wouldn't it only be able to force a particular setting?

**Comment by fr500** [comment]
hmmm then maybe it should be:
Rotation: auto|portrait|landscape

Auto would follow the device setting I guess.
And forget about the remember last rotation.

**Comment by fr500** [comment]
@bparker06 it works, except for default setting, default always allows rotation, so on my shield portable for example it still rotates if I tilt the console a bit (and no rotation lock on the os).

Other than that all good here.

**Comment by bparker06** [comment]
What should the "default" setting be called? Because it's not necessarily "auto", i.e. we're not forcing auto-rotate on if the user previously had it off... we're just not changing the user setting from whatever it is.

**Comment by fr500** [comment]
hmmm something like "follow OS setting"

**Comment by fr500** [comment]
Updated OP with a sidenote on restoring original mode

**Comment by bparker06** [comment]
Will do, initial implementation is in f5f492845f3aee0f2cf9ecc9e010ef4bf0b511cc.

**Comment by bparker06** [comment]
Original mode restore added in 97b7512420.

**Comment by fr500** [comment]
Thanks @bparker06
