### ISSUE TITLE
(RGUI) Load Content settings are misaligned.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#8354]
## Description

When using the `rgui` menu driver the the root directory under `Load Content` is misaligned.

### Expected behavior

The settings should be aligned.

### Actual behavior

![1](https://i.imgur.com/p6uNIsk.png)

### Steps to reproduce the bug

1. Start RetroArch with the `rgui` menu driver.
2. Select `Load Content`.
3. Observer the `/` root directory setting.

### Bisect Results

This started between `v1.5.0` and `v1.6.0`.
```
ecadf864c56be9c497a7cdaff8ad178796b1eeb1 is the first bad commit
commit ecadf864c56be9c497a7cdaff8ad178796b1eeb1
Author: twinaphex <libretro@gmail.com>
Date:   Fri May 26 15:57:18 2017 +0200

    Fixed font selection

:040000 040000 aa738927cc809fb62f872065cf215d389fcce174 7877209c02b05545169a5f9a68427a106644d673 M	frontend
:040000 040000 10004f83ceb874ae526f096749be51b292e6938f 5a81ee3d9693e1a443c89fd4b291efea4e662ef2 M	menu
```
ecadf864c56be9c497a7cdaff8ad178796b1eeb1

### Version/Commit
You can find this information under Information/System Information

- RetroArch: d2f73e3f33f93f8606bcf7e60d09cfc74a73d304

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.2.0`

**Comment by orbea** [comment]
@jdgleaver Maybe you might know how to fix this easily? Additionally I am noticing there is still a lot of wasted space to the right in a lot of menus.

**Comment by jdgleaver** [comment]
There are valid technical reasons for this discrepancy, but yeah - the current menu layout is somewhat suboptimal...

Okay - let's fix this. I've spent some time considering the options, and here's what I'm going to do:

(For reference, each entry has a 'label' string on the left and a 'value' string on the right)

- Make label and value field widths dependent upon the value string length (i.e. expand the label field as much a possible)

- Right align the value strings

- Increase the label/value spacing by one character

This will ensure consistency across the board, and make full use of all available screen space (it'll end up looking more like the ozone menu driver). I'll try to knock up a PR tomorrow afternoon.

**Comment by jdgleaver** [comment]
PR  #8364 should sort this out :slightly_smiling_face:
