### ISSUE TITLE
improve libretro.com "Contribute" webpage content

### ISSUE THREAD

**Issue by markwkidd** [libretro/RetroArch#8359]
I would like to suggest that the existing "Contribute" page be updated in order to make it even easier for people to contribute. This is the page I'm referring to: https://www.libretro.com/index.php/contributions/

I have converted the existing page to Markdown and updated it in order to make it simpler post my suggested updates here on github. My suggested updated version follows:

---

# Contribute to Libretro

## Contribute code or volunteer time

The libretro project [publishes all code on GitHub](http://github.com/libretro). We welcome new contributors and volunteers of all backgrounds.

There are a wide variety of ways to get involved, including:

  * [Contributing code to libretro cores and frontends](https://docs.libretro.com/development/libretro-overview/)
  * Writing and editing [documentation](http://github.com/libretro/docs)
  * Providing support to other users and developers [in the forums](http://forums.libretro.com/) or [on discord](https://discord.gg/C4amCeV)

## Financial contributions

Financial contributions are also essential for Libretro and its subprojects.

  * [Make regular donations with Patreon](https://www.patreon.com/libretro)
  * [Create or add to **open source bounties** for fixes and new features](https://docs.libretro.com/development/bounties/)

## Hardware request lists
Another way to support Libretro is to send hardware donations to particular members that are interested in providing integration on certain devices.

  * [Lakka hardware requests](http://www.lakka.tv/doc/Wishlist/)

**Comment by orbea** [comment]
Where is the source for libretro.com?

**Comment by markwkidd** [comment]
It runs on Wordpress so I don't imagine there's an easy way to expose the source via github.

**Comment by orbea** [comment]
Maybe this would help?

https://github.com/mAAdhaTTah/wordpress-github-sync

**Comment by markwkidd** [comment]
That looks pretty neat! I think that would be worth posting its own issue

**Comment by RobLoach** [comment]
I have a log in, and can make the changes above. Can add a user account for you if you write a blog post or get more involved on the web side :wink: 

Syncronyzing git/wordpress adds a layer of complexity that doesn't need to be there.

**Comment by RobLoach** [comment]
Changes are up at:
https://www.libretro.com/index.php/contributions/

Kept the old content in HTML comments below just in case we want to keep them.

**Comment by markwkidd** [comment]
Thank you @RobLoach !

**Comment by fr500** [comment]
Please replace wordpress with something else
kthxbai

**Comment by orbea** [comment]
> Syncronyzing git/wordpress adds a layer of complexity that doesn't need to be there.

There are several good reasons to do this.

1. Greater transparency.
2. Easier to reproduce.
3. Easier for most people to contribute.
4. Good backup measure in case some vital piece of hardware breaks.

Of course I don't know much about the proposed tool, wordpress or am involved in the web development so the decision is yours. :)

**Comment by fr500** [comment]
There are plenty of blogging platforms that can work of git.
That wordpress installation is outdated, unmantained, and I'm pretty sure it got hacked at least once.

Also has thousands of users in the DB because someone thought syncing with forums would be nice and the forums were quite vulnerable at the time.

If it was my call I'd nuke it with extreme prejudice.

**Comment by orbea** [comment]
I have no preference which web platform is used, but those sound like very good reasons to nuke it.

**Comment by fr500** [comment]
Something like mkdocs would be best, at first it was difficult, but I figure people understand markdown a lot better nowadays and it resulted in a far better platform than the wiki we had, anyone can contribute and it follows the same (non-existent 🤣) review process we're used to.

https://github.com/andyoakley/mkdocs-blog

**Comment by RobLoach** [comment]
> @orbea There are several good reasons to do this.

I understand the benefits, but for the reasons @fr500 mentioned, we'd get a lot more benefit out of getting off of Wordpress :wink:
