### ISSUE TITLE
[Request] Playlist/History etc: remove core association from games listings

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#8370]
Not a bug but a request to clean up the playlist entry in XMB. Currently, playlists and history are listing game titles and the core currently associated like so:

![screenshot_2019-02-26_06-06-57](https://user-images.githubusercontent.com/23315382/53372104-fd563200-398c-11e9-8c06-0b13afe82142.png)

This makes the titles longer than is should be and considering that normally, the playlists is created by system, its a bit redundant to associate a core name to the game list, which can be replaced anyways from its submenu's remove core association or overriden entirely using the QTUI (its not overriding the full playlist, only the ones that have not run or no association yet which i think is also a bug). There is a sub-menu each time the game is launch which has or lists list management, information and even a reset core option. This should well fitted here than an additional " | < insert core name here >" text on the titles since you will always run to this submenu anyways.
The title can also get under thumbnails and such when they are enabled.

**Comment by hizzlekizzle** [comment]
I have seen at least one person on r/retroarch suggesting the core be hidden behind an option, though I think @retro-wertz's idea is better, as it doesn't require implementing (and subsequently fiddling with) yet another option and still keeps that useful information easily accessible.

There's not really anything to be gained by seeing all of the entries' core listed, so nothing is lost by moving it to the entry-specific secondary screen.

**Comment by RobLoach** [comment]
I'd prefer to not list the core in the playlist entries at all. It's somewhat implied by the Playlist name.

Side note, how did the `[BIOS]` entry get in there? Was your Lynx playlist scanned a while ago?

**Comment by retro-wertz** [comment]
i created my own lynx dat, based on handy-lynx headered roms. the same that i pmed you... a while ago...

**Comment by RobLoach** [comment]
Did we get that in there? Or did it disappear?

**Comment by hizzlekizzle** [comment]
I think having the core *somewhere* is useful for troubleshooting. I have personally supported a number of people who didn't realize a core had been assigned to a playlist entry, causing it to use the same (incompatible) core over and over, even after they had used 'load core' to try another one.

**Comment by fr500** [comment]
![image](https://user-images.githubusercontent.com/1721040/53388284-79825280-3958-11e9-9a16-e4cd6e806308.png)

Sublabels > long ass strings 🤣

**Comment by jdgleaver** [comment]
As @fr500 says, sublabels FTW.

Also, @retro-wertz: I'm not sure why you're seeing this extra noise on normal content playlists. It's only shown if you go to `Settings > Playlists` and turn on `Always show associated cores in playlists`. By default it should be off, so you only get automatic core display on history/favourites.

**Comment by retro-wertz** [comment]
it was ON already when i updated. is that documented somewhere? no one else seems to know about that when somebody posted this for an on/off in reddit or when i asked on discord. even if its still in history or favorites only, i think this is better placed under its submenu.

feel free to close this is its invalid then...

**Comment by jdgleaver** [comment]
Oh, sorry - I know what's happened...

`Always show associated cores in playlists` was an RGUI-specific option when I first added it 9 days ago (PR #8307). At that point it defaulted to on (to preserve the traditional RGUI appearance).

It then became a 'global' option in PR #8347 4 days ago, with a default setting of off. So unfortunately, anyone who updated during that 5 day window now has it set to on...

Apologies for the inconvenience... (but then again, people who use nightlies are always living on the edge...)

**Comment by RobLoach** [comment]
Ah, I see the option now. Thanks a lot for the clarification, @jdgleaver!

![screenshot at 2019-02-26 09-49-31](https://user-images.githubusercontent.com/25086/53421562-dce9a000-39ab-11e9-94ca-5bbd860740d8.png)

This can now be closed.

> people who use nightlies are always [living on the edge](https://www.youtube.com/watch?v=7nqcL0mjMjw)

**Comment by retro-wertz** [comment]
uh history? favorites?

**Comment by jdgleaver** [comment]
Well, history and favourites need to show core names, otherwise you have no idea which system each item is associated with. If you want 'clean' entries, just turn on playlist sublabels (works with all menu drivers)

**Comment by retro-wertz** [comment]
ugh its just making core name smaller and placed on 2nd line. its still there.. but nxm...

**Comment by jdgleaver** [comment]
:disappointed: 

I guess we could make the setting an enum:

`Show associated cores in playlists`: `Always`, `Never`, `History & Favourites`

But does this overcomplicate things...?

(Also, bear in mind that core names have *always* shown up on history and favourites, and no one has ever complained before...)
