### ISSUE TITLE
[Core request] BeebEm Core

### ISSUE THREAD

**Issue by Sterophonick** [libretro/RetroArch#8380]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Request: BeebEm core

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
This is not a bug and "Request: BeebEm core" is not much to go on...

**Comment by ofry** [comment]
Link to Wikipedia: https://en.wikipedia.org/wiki/BeebEm

**Comment by grant2258** [comment]
https://github.com/stardot/beebem
