### ISSUE TITLE
double "/" (root) prompt when configuring Directories

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#8385]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When configuring directories using Settings > Directories, browsing to the "/" root folder re-opens or prompts you with another / folder before able to see actual root contents

### Expected behavior

browse root "/" and then see files/folders

### Actual behavior

browse / folder, it prompts you into another "/" folders

### Steps to reproduce the bug

1.  goto Settings > Directories
2. select any option/entry
3. browse to the "/" folder, this should show another root folder

### Bisect Results

(long standing issue i cant remember when)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.6 5cc51ed

### Environment information

- OS: Arch (fresh installed), latest updates
- Compiler: gcc version 8.2.1 20181127 (GCC)

**Comment by orbea** [comment]
> (long standing issue i cant remember when)

This started between `v1.7.5` and `v1.7.6`, but I see you didn't even try.

**Comment by orbea** [comment]
This is my fault, unfortunately the issues I fixed were worse than this new one so reverting it is not desirable...
```
5fcedc86195c9b1b8a79c7b5f9e59f9c5c46012b is the first bad commit
commit 5fcedc86195c9b1b8a79c7b5f9e59f9c5c46012b
Author: orbea <orbea@fredslev.dk>
Date:   Wed Jan 23 17:54:54 2019 -0800

    Fix disk control and subsystems when navigating to the root directory.
    
    Fixes https://github.com/libretro/RetroArch/issues/5642
    Fixes https://github.com/libretro/RetroArch/issues/8071

:040000 040000 a36a91ad43dabe47d4c2569d104e3ff42f561429 076aabea5c0f2b7b30d8a51912300077f89f1c7c M	menu
```
5fcedc86195c9b1b8a79c7b5f9e59f9c5c46012b

**Comment by orbea** [comment]
Just for the record I believe this to be a cosmetic issue, a double `/` should be entirely harmless.

**Comment by orbea** [comment]
I think this is because `cbs->enum_idx = MSG_UNKNOWN`, but I haven't been able to narrow it down more...

**Comment by orbea** [comment]
I made a PR to hopefully fix this correctly.

https://github.com/libretro/RetroArch/pull/8390
