### ISSUE TITLE
N64 Cores not working at all in web player

### ISSUE THREAD

**Issue by NovaKatsu** [libretro/RetroArch#8387]
Mupen64 and Glupe64 dont work at all. They dont even load up... please help. o-O

**Comment by orbea** [comment]
There is an issue template for a reason....

**Comment by NovaKatsu** [comment]
right, sorry.

**Comment by orbea** [comment]
I guess I will close this as a duplicate of the newer https://github.com/libretro/RetroArch/issues/8392.
