### ISSUE TITLE
Dont work input on TVbox

### ISSUE THREAD

**Issue by darkdef7** [libretro/RetroArch#8388]
## Description

Can do nothing, buttons dont work...

### Steps to reproduce the bug

open app and i can do nothing

### Version/Commit
1.7.6

- OS: TV box x96 max  Android 8.1

**Comment by grant2258** [comment]
I has this problem on a beelink tv box only way I could get it partially working was to flash a custom image. It still wasnt usable so i gave up on using the tvbox

**Comment by darkdef7** [comment]
I dont want give up :)
May be any one else know how to fix this...

**Comment by RobLoach** [comment]
Try another input device, plug in a USB controller or something. Then once in the user inputs, configure your remote control, and send the autoconfig file up.
