### ISSUE TITLE
msys2 build issue

### ISSUE THREAD

**Issue by grant2258** [libretro/RetroArch#8391]
configured with instructions provided here

https://docs.libretro.com/compilation/windows/

build error only appears when you add the qt packages

```
CXX ui/drivers/ui_qt.cpp
In file included from C:/msys64/mingw64/include/QtCore/qcborstream.h:45,
                 from C:/msys64/mingw64/include/QtCore/QtCore:40,
                 from C:/msys64/mingw64/include/QtWidgets/QtWidgetsDepends:3,
                 from C:/msys64/mingw64/include/QtWidgets/QtWidgets:3,
                 from ui/drivers/ui_qt.cpp:44:
C:/msys64/mingw64/include/QtCore/qfloat16.h:79:54: internal compiler error: in make_rtl_for_nonlocal_decl, at cp/decl.c:6590
     Q_CORE_EXPORT static const quint32 mantissatable[];
```

I even do a reinstall of msys2 the same issue persists

**Comment by bparker06** [comment]
What version is your compiler? Please paste an output of `qtdiag` also.

**Comment by bparker06** [comment]
Just FYI this post seems to suggest it may be a gcc 8.2.x regression: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1667395.html

**Comment by bparker06** [comment]
I'm unable to reproduce with this compiler:
```
Name            : mingw-w64-x86_64-gcc
Version         : 8.2.0-1
```
And this Qt:
```
Name            : mingw-w64-x86_64-qt5
Version         : 5.11.1-1
```
```
$ qtdiag
Qt 5.11.1 (x86_64-little_endian-llp64 shared (dynamic) release build; by GCC 7.3.0) on "windows"
OS: Windows 8.1 (6.3) [winnt version 6.3.9600]
```

**Comment by grant2258** [comment]
Thread model: posix
gcc version 8.3.0 (Rev1, Built by MSYS2 project)

I guess they updated the gcc in msys2 ill try an earlier version. It does make sense I just did an update

**Comment by grant2258** [comment]
```
Qt 5.12.1 (x86_64-little_endian-llp64 shared (dynamic) release build; by GCC 8.2.1 20181214) on "windows"
```
```
mingw-w64-x86_64-gcc 8.3.0-1
mingw-w64-x86_64-qt5 5.12.1-5
mingw-w64-x86_64-qtbinpatcher 2.2.0-3
```

**Comment by grant2258** [comment]
ill just compile with  ./configure --disable-qt for now maybe gcc will get a patch doesnt look like msys supports multiple gcc versions

**Comment by bparker06** [comment]
You can get older packages here: http://repo.msys2.org/mingw/x86_64/

**Comment by grant2258** [comment]
you need to match the libs as well as everything else related to it you cant just replace the bin for gcc.

**Comment by bparker06** [comment]
Here is the upstream gcc bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88568
