### ISSUE TITLE
Warning: Missins assets, use the Online updater / 1.7.6 - No core

### ISSUE THREAD

**Issue by CamJRP** [libretro/RetroArch#8395]
## Description

The latest version of Retroarch is giving me the next error:
Warning: Missins assets, use the Online Updater, despide the assets are properly installed.
Also, it does not recognized the installed cores: "1.7.6 - No core".
The output of the terminal is as follow:
camilo@camilo-S400CA:~$ retroarch
Failed to open /home/camilo/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
Failed to open /home/camilo/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
Failed to open /home/camilo/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
Failed to open /home/camilo/.config/retroarch/assets/xmb/monochrome/font.ttf: No such file or directory
org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

### Expected behavior

I expect retroarch to recognize the installed cores and assets

### Actual behavior

Not recognizing cores and assets

### Bisect Results

After upgrading stable retroarch to unstable version

- RetroArch: 1.7.6

### Environment information

- OS: Xubuntu 18.10 Cosmic Cuttlefish
![screenshot_2019-03-02_17-48-07](https://user-images.githubusercontent.com/47904712/53687517-2facba00-3d14-11e9-8849-a56a2d4bd4bf.png)

**Comment by grant2258** [comment]
goto online updater

update assets 
update core info files

also update any cores you need job done

**Comment by orbea** [comment]
Not an issue, as @grant2258 said you need to update the assets or otherwise point the assets directory to the correct location in `Settings -> Directories`. I would suggest using the forum, discord or irc for support and please make new issues for any bugs, thanks!

**Comment by helveciovinicius** [comment]
what is the default folder for assets? I changed mine but forgot

**Comment by RobLoach** [comment]
You can usually reset to default by pressing START... Or delete the entry in your retroarch.cfg, or just delete retroarch.cfg entirely.

**Comment by Unounited** [comment]
Hi 

When I went to update assets, it said task failed, I might be because I need internet on retroarch, but i'm posting this to make sure if I'm supposed to.
