### ISSUE TITLE
[QT] Incorrect path when loading in File Browser (FBA and MAME)

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#8403]
## Description

Slashes in paths aren't corrected in windows when trying to load a rom from the File Browser in QT for Mame or FBA.
Loading fails.

### Expected behavior

Path should be like E:\Roms\Arcade - MAME\88games.zip.

### Actual behavior

In my log I get:
[INFO] Using content: E:/Roms/Arcade - MAME/88games.zip.

### Steps to reproduce the bug

1. From QT desktop menu go into File Browser.
2. Select a valid rom for mame or fba.
3. Start with the relevant core.

### Bisect Results

I remember that issue being fixed at some point for FBA that wasn't correcting the path on windows.
So that issue came back probably with @CozmoP rewrites.

### Version/Commit

- RetroArch: 2ab333e00f win x64

### Environment information

- OS: win7 x64
- Compiler: MingW64 GCC 7.3 (buildbot)

**Comment by orbea** [comment]
Can you bisect this? Maybe it can be fixed again then?

**Comment by Tatsuya79** [comment]
Thank you! :)
