### ISSUE TITLE
RetroArch Does not support Extended Gamepad from iOS 12 update R3 L3 Support

### ISSUE THREAD

**Issue by Kiaos** [libretro/RetroArch#8408]
## Description

The R3 and L3 on the Controller Rotor Riot is not implemented in RetroArch and can not be bound in RetroArch.

### Expected behavior

When using the Rotor Riot Game controller with RetroArch you should be able to bind R3 and L3 using the player binds in RetroArch

### Actual behavior

When Trying to bind R3 and L3 nothing happens when you press the R3 and L3 button using Rotor Riot Controller 
### Steps to reproduce the bug

1. [First step] Buy an Rotor Riot Mfi controller 
2. [Second step] Download and install Ludu Mapp app on iOS
3. [and so on...] plug in Rotor Riot into Lighting USB 
4. [and so on...] Ludu Mapp will give you a prompt hit allow 
5. [and so on...] Update Firmware in Ludu Mapp in settings for Rotor Riot Controller settings.
6. [and so on...] Go into RetroArch and Bind R3 and L3

### Bisect Results

When you try to bind R3 and L3 with a Rotor Riot Controller

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit] 1.7.6 

### Environment information

- OS: [The operating system you're running] iOS 12.1.2
- Compiler: [In case you are running local builds]

Recently a new Controller Called Rotor Riot now supports R3 and L3 on iOS 12 using Mfi Extended Gamepad Support starting in iOS 12.1. Another app for iOS that is open source has implemented this support and it is linked here https://github.com/moonlight-stream/moonlight-ios/commit/39b04d46a4e6f76b11fd5ef1c48a8948e566b197 It would be nice if RetroArch supported the new extended Gamepad Support for R3 and L3. Good Luck and thank you for looking at this issue.

**Comment by FinixFighter** [comment]
I noticed it too

**Comment by Kiaos** [comment]
> I noticed it too on a friend's computer

This is for iOS not pc for iphones

**Comment by chucksmith** [comment]
Looking at input/include/GameController/GCExtendedGamepad.h, it seems that RetroArch doesn't support L3 or R3 on any platform. So, if I understand correctly, this would involve changing input in general in RetroArch and not just iOS-specific, right?

**Comment by chucksmith** [comment]
Today playing RetroArch on my Wii U, I saw there are bindings for L3 and R3. Will have to look into this further...
