### ISSUE TITLE
Playtime logging not working

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#8417]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Playtime logging doesn't seem to work on android, it does absolutely nothing

### Expected behavior

I expect it to log

### Actual behavior

Nothing

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/334cc943cbfd3ab989c0b230120e7edd6d0ae33a

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
@jdgleaver is there any logging involved so I can find out if it's failing for some reason?

**Comment by fr500** [comment]
I found it created a dir at least:
`/storage/emulated/0/RetroArch/userdata/playlists/android/shield x1/logs`

But no files are created

**Comment by fr500** [comment]
Hmmm ok this is so weird...
My snes playlist doesn't log

But my GBA playlist does.

Here is how my snes playlist looks:
![image](https://user-images.githubusercontent.com/1721040/53842990-0e93d580-3f6f-11e9-8011-5d34342a2526.png)

So I load any of those games... and nothing is logged.
I added some logging to my build and it looks correct:

```
03-05 17:49:35.929  4696  4714 I RetroArch: [runtime] Logging playtime to: /storage/emulated/0/RetroArch/userdata/playlists/android/shield x1/logs/Snes9x/Legend of Zelda, The - A Link to the Past (USA).lrtl.
03-05 17:49:35.930  4696  4714 I RetroArch: [runtime] Logging playtime to: /storage/emulated/0/RetroArch/userdata/playlists/android/shield x1/logs/Snes9x/Super Punch-Out!! (USA).lrtl.
```

I run the game for a few minutes... and close.
Nothing is added.

![image](https://user-images.githubusercontent.com/1721040/53843070-4ac73600-3f6f-11e9-9325-acb1a2ea87d9.png)

**Comment by fr500** [comment]
Now on my GBA playlist, things aren't working so well either. It logged on the first run:

![image](https://user-images.githubusercontent.com/1721040/53843256-cc1ec880-3f6f-11e9-8ba1-d9017b3ec714.png)

But now it's not logging anything again.
The path to log files looks correct yet again but something is preventing the logs from updating

Also even though I have playtime for mgba / MMZ3 in the GBA playlist, it doesn't show in history:

![image](https://user-images.githubusercontent.com/1721040/53843326-ff615780-3f6f-11e9-9d29-69dbb28d41fb.png)

But the proper playtime is shown on history
![image](https://user-images.githubusercontent.com/1721040/53843339-0a1bec80-3f70-11e9-8554-5bb89715f2fa.png)

**Comment by fr500** [comment]
And now it logged again on mgba and it logged the time of the game I was running... previously. Not the actual game I was running.

**Comment by fr500** [comment]
To elaborate:

it's logging all out of whack
sometimes it adds to the correct one
sometimes to the next one :stuck_out_tongue:

Say I'm playing kirby, playtime looks like this:

![image](https://user-images.githubusercontent.com/1721040/53843748-8531d280-3f71-11e9-98e1-b0cfd8df391a.png)

Let it idle a bit, then without closing content I switch to dragonball:

![image](https://user-images.githubusercontent.com/1721040/53843780-95e24880-3f71-11e9-9dea-2c3f12d2b2a2.png)

Let it idle a few minutes and now I load Mega Man

https://media.discordapp.net/attachments/434759979095031840/552627997912334337/unknown.png

It's clearly logging the time to the wrong entry.

**Comment by fr500** [comment]
By doing this I managed to make SNES log:

![image](https://user-images.githubusercontent.com/1721040/53843840-c1653300-3f71-11e9-8473-4651d8e747d9.png)

Still no idea of why history is not logged at all

**Comment by fr500** [comment]
I started over and now it doesn't show playtimes in favorites either, guess I'll have to upload my playlists and playtime files.
That said I'm quite certain logging is affecting the wrong entry.

**Comment by orbea** [comment]
Is this with the current master? There were some PRs merged today that fixed some playlist issues, but maybe this is something else? Could new vs old playlist formats be relevant?

**Comment by fr500** [comment]
hmmm the commit I first tried I'm not sure, then I added some logging in my fork not noticing it was behind.
Let me rebase and try again.

All playlists are new so shouldn't be the playlists.

**Comment by orbea** [comment]
> All playlists are new so shouldn't be the playlists.

It still might be worth recreating one playlist to see if it can be reproduced or not.

**Comment by fr500** [comment]
I retried now with the latest master.
Issues persist, playtime logging goes to the next game not the current game.

For some reason it can't parse my history nor my favorites.

[content_history.txt](https://github.com/libretro/RetroArch/files/2934206/content_history.txt)
[content_favorites.txt](https://github.com/libretro/RetroArch/files/2934207/content_favorites.txt)

**Comment by fr500** [comment]
Maybe it's due to crc32 being empty on history entries (those were generated with load content)
Also another interesting thing I noticed is that even though both are from the same device, bran new and the cores were always the same, the core_path was resolved differently in the history entries compared to the other playlist entries

snes playlist
`"core_path": "/data/user/0/com.retroarch/cores/snes9x_libretro_android.so",`

history playlist
`"core_path": "/data/data/com.retroarch/cores/snes9x_libretro_android.so",`

Both paths are valid and pretty much identical, but something internally is resolving a different path for each case (history was created via load content)

**Comment by fr500** [comment]
I just tested latest master on my PC and I can confirm 100% the same behavior (times set incorrectly).
Example:

I manufactured a baseline, punchout 30 sec, mario kart 10 minutes

![image](https://user-images.githubusercontent.com/1721040/53854725-9a6e2780-3f98-11e9-8f9c-3c9b29c166e1.png)

Load Mario Kart, idle for a few sec and close:

![image](https://user-images.githubusercontent.com/1721040/53854767-beca0400-3f98-11e9-97fe-4c3a57535e02.png)

![image](https://user-images.githubusercontent.com/1721040/53854775-c5f11200-3f98-11e9-9cb9-8bb84527c998.png)

**WORKS FINE**

Now again, Load kart, idle for a few but this time switch directly to punch out:

![image](https://user-images.githubusercontent.com/1721040/53854811-f0db6600-3f98-11e9-95de-f2faa0b5dbb4.png)

kart time didn't change but punch out did right after loading.

**Comment by fr500** [comment]
The behavior on android is different. There are two issues:

1. playtime not being assigned to the correct content
This has two sub-cases:
1.1 Close content before loading another one
[x] pc: playtime is added to the correct entry
[] android: nothing happens
1.2 load content and then load another content without closing the first one it gets added to the second one
[] pc: playtime is added to the second entry
[] android: playtime is added to the second entry

2. The other thing is history list not working the same as regular playlists on android.
This is due to the fact that the dirs added to the history playlist are different than the dirs from other playlists.

Example:

On my shield ATV with adoptable storage we have these:

retroarch.cfg
`libretro_directory = "/data/user/0/com.retroarch/cores/"`

history:
```json
    {
      "path": "/storage/emulated/0/RetroArch/content/Kirby & the Amazing Mirror (USA).zip#Kirby & the Amazing Mirror (USA).gba",
      "label": "Kirby & The Amazing Mirror (USA)",
      "core_path": "/data/data/com.retroarch/cores/mgba_libretro_android.so",
      "core_name": "mGBA",
      "crc32": "",
      "db_name": ""
    },
```

playlist
```json
    {
      "path": "/storage/emulated/0/RetroArch/content/Dragon Ball - Advanced Adventure (Europe) (En,Fr,De,Es,It).zip#Dragon Ball - Advanced Adventure (Europe) (En,Fr,De,Es,It).gba",
      "label": "Dragon Ball - Advanced Adventure (Europe) (En,Fr,De,Es,It)",
      "core_path": "/data/user/0/com.retroarch/cores/mgba_libretro_android.so",
      "core_name": "mGBA",
      "crc32": "6C135820|crc",
      "db_name": "Nintendo - Game Boy Advance.lpl"
    },
````

Thing is, when content is added to a playlist from history **the path is populated differently for some reason**. The core was loaded so I assume it's resolving the path from the core file itself and the OS is returning a different value.

Since that core file doesn't have a core info entry it can't show the proper pretty name nor playtime in the history.

![image](https://user-images.githubusercontent.com/1721040/53855665-a1973480-3f9c-11e9-8192-eb64232b758a.png)

![image](https://user-images.githubusercontent.com/1721040/53855677-afe55080-3f9c-11e9-8af7-f42cf5a40c07.png)

This seems like a completely different problem, and to be honest not sure how to solve, the OS returns that directory for some reason. The other one is probably a symlink or something.

**Comment by orbea** [comment]
@jdgleaver I'd think you would have the best idea what is wrong here. :)

**Comment by jdgleaver** [comment]
@fr500 Thanks for the detailed analysis!

So yes, there are two issues here - let's look at them in turn:

## 1. playtime not being assigned to the correct content

The logging occurs during core deinit (or unload core). These couple of lines of code (the actual trigger) are the only bit that I didn't create, and I assumed it worked - guess I was wrong... :slightly_smiling_face: 

I never considered the action of opening new content without closing the old one first (I would never think of doing this!). I need to double check what's happening in this case, but I think it should be relatively straight forward to fix. I'll tackle this right away.

## 2. The other thing is history list not working the same as regular playlists on android.

This is absolutely a symlink issue - and it stinks, because the OS should be handling this, not RetroArch.

As you've seen. depending upon how the playlist is filled (auto detect core vs history), the core path is set to either the 'real' path or the symlink version. All `core_info` operations require the 'real ' path - use anything else and they fail completely. This has more important consequences than just affecting runtime logging. Any playlist with symlink core paths is fundamentally broken, and turns RetroArch into a house of cards...

You should be able to fix this by going to `Settings > Directory`, and changing the `Core` directory to the 'real' path (which seems to be `/data/user/0/com.retroarch/cores`). But of course, this is not retroactive, so you'll then have to manually reset core associations on any playlist that has the wrong symlink paths.

I really don't know how to fix this 'properly', without manual intervention...

- We can probably work in a hack to ensure that the 'real' path is always resolved when generating core paths - but this won't solve issues with any existing 'broken' playlists.

- We could edit `core_info` to automatically create a duplicate entry when a symlink path is detected (so we can use either real or symlink for searching), but this would have obvious performance implications.

Can anyone think of a better way...?

**Comment by jdgleaver** [comment]
Okay, PR #8420 fixes issue 1.

Still need to look at symlinks...

**Comment by orbea** [comment]
Can you detect the symlinks and then resolve them before they are used? I'm not sure how this would look in c code, but the equivalent shell is trivial...
```
  if [ -h "$f" ]; then
    in="$(readlink -- "$f")"
  else
    in="$f"
  fi
```

**Comment by jdgleaver** [comment]
Already been doing this for the last couple of hours... :slightly_smiling_face: 

There are several places where this needs to be done, so it requires some careful checking...

Also, we can't really fix existing 'broken' playlists - the performance impact of realpath()ing every entry is too great - but we can at least ensure consistency for all new core associations.

**Comment by orbea** [comment]
Is there is nothing like `test -h` in c so you would only realpath entries which are actually symlinks?

**Comment by jdgleaver** [comment]
Well, under Linux we have lstat(), but I don't know of a cross platform solution.

Also, it would still require disk access every time we parse every entry of every playlist, which is a pretty nasty performance hit to force on every user. (Especially since only a small percentage of users have to deal with symlinks: probably only a few linux users with highly custom setups, and a fraction of Android users - and I wonder if on Android it's just an adoptable storage issue? Everything works as expected on my older Android devices)

**Comment by fr500** [comment]
Yes it's due to adoptable storage
I think an easier solution would be to change how core info works so it
matches only the core basename instead of the fullpath

Mgba is mgba no matter what folder it's in.

**Comment by jdgleaver** [comment]
@fr500 I considered that, but thought it would be cheating!

But sure - it increases performance requirements fractionally, but it's a nice clean solution.

Okay, why not - I'll go ahead and do it as you say :slightly_smiling_face:

**Comment by jdgleaver** [comment]
...and PR #8423 fixes issue 2.

(Ended up taking ages, because I accidentally borked my retroarch.cfg while messing about with `playlist_cores`, and thought it was a bug in the code...)

@fr500 Could you please test once it's merged?

**Comment by fr500** [comment]
I'll test tonight.

**Comment by fr500** [comment]
Everything seems to be alright now, I'll test more and reopen if things go wrong

**Comment by jdgleaver** [comment]
Excellent - thanks for your help in squashing these bugs!
