### ISSUE TITLE
Cannot Change Disk Index in Android Menu

### ISSUE THREAD

**Issue by RyanBram** [libretro/RetroArch#8430]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

In Android, user cannot change disk index in menu using touch input when using multidisk playstation game

### Expected behavior

Retroarch should allow user to change game disk in Android menu using touch input

### Actual behavior
Retroarch doesn't respond to user input when changing game disk in Android menu using touch input. It will respond if user use overlay gamepad for changing the index (eg. from 1 to 2)

### Steps to reproduce the bug

1. Open multidisk Playstation .pbp game
2. Open disk changing in Quick Menu
3. Eject the disk by touching the menu
4. Click the index (number 1) by touching the menu to change from 1 to other number
5. Nothing happen

### Version/Commit
c9c6c5a

- RetroArch: 1.7.5

### Environment information

- OS: Android Oreo in Xiaomi Mi Note 3 MIUI 10
- Compiler: Clang/LLVM 3.8.

**Comment by orbea** [comment]
Try the current nightly please, this might be fixed.

**Comment by RyanBram** [comment]
Hi.
I've downloaded the latest Android 32 bit build and installed it on my system, but the Disk Control - Quick Menu, still doesn't response when I change the Disk Index by touching the option.
It only responses when I change it using hardware controller or on screen overlay controller by pressing left or right direction button.

**Comment by orbea** [comment]
Ah, so its a ui / input problem and not a problem with the disc control interface?

**Comment by RyanBram** [comment]
Yes. I think it is the UI or touch input problem in Android GLUI menu.
