### ISSUE TITLE
Idea: Standalone UI library?

### ISSUE THREAD

**Issue by mick-p1982** [libretro/RetroArch#8432]
Hi (I tried to use the forums to ask this but did not get so far) I was just thinking RA seems like a juggernaut project that is basically one big UI front-end. Has anyone ever thought about abstracting it into a UI library for other open-source efforts to utilize? Like, I'm working with projects to support Sony peripherals around VR, for example the PSMoveService project, and they could use a drop-in UI to make things simple, and RA already has a UI that emulates PS3. I could use a configurator myself, including PlayStation peripherals, but with game/platform specific settings. I think games should not have system settings inside of the game, and so it makes more sense (thematically better) to change system settings by stepping out of the game setting, kind of like saving your game on the PS3, or accessing the manual in the PS Classics games on PSN.

I think it would be helpful to make a general purpose UI system available to other software. And for some things like peripherals, it might make integration into RA easier, like to set up PlayStation VR peripherals with RA, and support advanced features of controllers.

RA is so big that it would better be separated into multiple UI modules, so software could chose the ones that make sense. I think whenever so much work and code has been poured into something like RA that it's very good to take a step back and ask what other, unexpected benefits could come of it. I'm just curious if anyone's ever thought of this, or entertained it.

**Comment by hizzlekizzle** [comment]
I think the biggest hurdle is that the menu code is among the most confusing and unwieldy in the entire project. When people want a GUI library, they usually want it to be easy and straightfoward to add and configure elements, which is a far cry from what we have, unfortunately.

**Comment by mick-p1982** [comment]
Maybe an initiative to better organize RA could help it too? It seems like it has a lot of good UI functionality. The "Xross" UI is actually much simpler than a traditional overlapping boxes UI. I think that's why Sony went for it. I mean, from an implementation perspective. I think it would be a useful thing to have a library that just provides a simpe/emulated UI (pick from a menu of devices like the PlayStation's) and some generic/modular input/sound functionality.

Maybe RA is really just a glorified UI coraling project at the end of the day :)

**Comment by fr500** [comment]
Honestly it's not a good GUI foundation.
Rolling out your own with an immediate mode framework is far more viable in
my opinion.

**Comment by mick-p1982** [comment]
RE "Closed this as completed" So is there a "completed" standalone UI library now? Thanks if so, and please reply with a relevant link if you can.

**Comment by LibretroAdmin** [comment]
It's a nice idea but we are already swamped with work, and the UI API as it stands right now would be too unwieldy to be usable much from standalone users. We would just get endless complaints how it is too unintuitive, how it should be easier to use, etc. I.E. too much technical debt, when we already have tons of it and need to reduce it.
