### ISSUE TITLE
[$30 Bounty] [Feature Request] Hotkey for Start/Stop Netplay

### ISSUE THREAD

**Issue by furiadeoso** [libretro/RetroArch#8433]
## Description

Having a hotkey to START/STOP netplay could be a great improvement in netplay usability. 

For netplayers it would be much more agile to start or change the game, without having to enter and go through the menus.

I know that there are currently people worried about the usability of netplay, but the hassle of adding the hotkey to the menu discourages devs. So I thought about opening this bounty as a small incentive for this tedious work.

### Expected behavior

To close this issue it is expected that there is the possibility of defining a hotkey at "INPUT - HOTKEY BINDS" menu for START-STOP NETPLAY.

The key, used in the menu or during the game, should work in the same way as using Netplay Rooms / Start / stop netplay action. That is, if the netplay is stopped and the hotkey is pressed, it must START netplay (host) and if netplay is started, it must STOP it.

### Actual behavior

There is no hotkey for start/stop netplay.

**Comment by furiadeoso** [comment]
https://www.bountysource.com/issues/71133237-feature-request-hotkey-for-start-stop-netplay

**Comment by bparker06** [comment]
I have created PR #8438 for this bounty.

**Comment by furiadeoso** [comment]
It seems to work well. Thank you! I suppose I must close this when merge is done, right?

**Comment by bparker06** [comment]
Yes although it should close automatically since I mentioned the issue number that the PR fixes in the summary of the PR itself.
