### ISSUE TITLE
[RGUI] Better support widescreen displays.

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#8436]
## Description

The rgui aspect ratio can't be made full screen without adjusting the core's aspect ratio.

### Expected behavior

rgui should work with widescreen monitors without requiring black bars.

### Actual behavior

I have a `16:10` aspect ratio, when I use the `core provided` aspect ratio.

![1](https://i.imgur.com/T1Ke9bG.png)

I can then change the aspect ratio to `16:10` in the video settings which looks better except that the text is needlessly stretched and has the problem of changing the aspect ratio for the core too.

![2](https://i.imgur.com/ilRLG6n.png)

### Steps to reproduce the bug

1. Navigate to `Settings -> Video -> Aspect Ratio` and select `Core provided`.
2. Next try your native monitor aspect ratio, in my case this is `16:10`.

This requires a wide screen monitor to observe.

### Bisect Results

This is a long existing issue.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/c7213c81e38a5e626f9f067a3b9a142e3cb695df

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.3.0`

**Comment by orbea** [comment]
@jdgleaver Is this something you know how to fix given your prior experience with rgui?

**Comment by jdgleaver** [comment]
Well, RGUI has a fixed framebuffer size of 320x240, so stretching it to a widescreen aspect ratio is like stretching a SNES game - pretty yucky.

I guess we could make the framebuffer size adjustable, but oh boy - that's a heck of a lot of work. Maybe it's something I'll take a look at, but I have quite a few other things to do first...

**Comment by orbea** [comment]
That is understandable and thanks for the detailed reasoning.

**Comment by orbea** [comment]
Fixed in PR https://github.com/libretro/RetroArch/pull/8496 thanks to @jdgleaver.
