### ISSUE TITLE
Loading Old Save States Will Delete Newer Save Files

### ISSUE THREAD

**Issue by HarryTheTurtle** [libretro/RetroArch#8440]
While playing Digimon World 3 I noticed that loading a save state that was saved before a save file will revert the save file to the currently known save file with that save state.

This is the save I made to test the reverted save file. I made this save before I went to the shop to purchase something to show I had spent money and to increase the play clock by a noticeable amount.
![Digimon World 3 (USA)-190310-141558](https://user-images.githubusercontent.com/47069190/54090303-b9760c00-4340-11e9-8bee-cd3f59cce9d6.png)

After I purchased something from the shop I created a save state. I then went and saved the game with my changes.
[Digimon World 3 (USA).state.auto.zip](https://github.com/libretro/RetroArch/files/2949954/Digimon.World.3.USA.state.auto.zip)
![Digimon World 3 (USA)-190310-141637](https://user-images.githubusercontent.com/47069190/54090331-1e316680-4341-11e9-9014-57122b7d52fa.png)

If I now reload the save state before this save it will delete any save files made after the save state and revert it back to this save file that is current with the save state potentially losing hours of game play. (Which I did) Restarting the content will show the reverted save file so there is no going back after the file is reverted.
![Digimon World 3 (USA)-190310-141558](https://user-images.githubusercontent.com/47069190/54090346-47ea8d80-4341-11e9-8ff0-eb22595852b5.png)

I have not tested this on other games but it seems to be an issue with save states to prevent data corruption maybe? It seems that save states must always be ahead of the save file. Is there a way to prevent older save states from reverting newer save files by adding a fail safe feature?

**Comment by hizzlekizzle** [comment]
This is functioning as intended. SRAM is part of the state, so when you load a state, you load the SRAM from that time, as well.

There is an option in settings > saving to not load SRAM when you load a savestate, but it can cause strange, unexpected behavior in games that use the SRAM as regular RAM (more common in older systems, like NES).

**Comment by HarryTheTurtle** [comment]
Hmmmm alright. Guess Ill need to be a little more aware of my save states then. Thanks for the quick respond. Ill close the issue.
