### ISSUE TITLE
[Ozone] Issues with sidebar implementation for thumbnail and playtime viewing

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#8447]
## Description

I have written here a list of issues that I am experiencing on Ozone, after the implementation of the right sidebar for thumbnail and playtime viewing by @natinusala.

1) If you set "Second Thumbnail" to anything other than OFF under User Interface -> Appearance, it will replace playtime information with the Screenshot / Boxart / Title Screen in the bottom-right corner, right under the first picture. 
This could be a deliberate choice, however the issue is that if you have "Thumbnails" OFF and "Second Thumbnail" ON the sidebar will instead show the "No thumbnail available" message in the top-right corner and only the playtime related to the first entry of any list will be visible (I don't think this should happen). Also, when you press Y to change the thumbnail type, the Screenshot / Boxart / Title Screen will now replace the playtime information.

2) Thumbnails do not seem to show up at all in the History submenu. The sidebar still shows the "No thumbnail available" error message even for content that you have the respective boxart / title screen / screenshot for (the same content displays its thumbnails perfectly within a normal playlist).

3) The sidebar is opening up and showing the "No thumbnail available" message even for the "Netplay rooms" and "Import content" tabs, where supposedly no thumbnail would ever be used.

4) I created an entirely new playlist by scanning a file from within RetroArch, assigning a core to it and then running it for a few minutes. Playtime information is being created and logged properly, however the sidebar is not appearing at all for this playlist. In fact, the Menu bar does not even collapse. If need be, I can provide the playlist file itself but upon a quick glance I don't see anything exceptional with it, so I'm clueless about this one.

**Comment by natinusala** [comment]
I will be looking at that tomorrow, thanks for the report. Problem 2. is also present in XMB if I'm not mistaken.

Could you send me a screenshot of your sidebar please? To see what options you have enabled

**Comment by Ryunam** [comment]
Here is a screenshot of the sidebar as it is displayed on my system: https://imgur.com/a/oJQQj2X
The playlist where the sidebar does not appear / collapse at all is the GameBoy one.

**Comment by natinusala** [comment]
But all others collapse fine ?

**Comment by Ryunam** [comment]
Exactly, all the others collapse perfectly. That one neither collapses, nor does it display the sidebar (and all the related content such as playtime information) at all.

**Comment by jdgleaver** [comment]
@Ryunam Just to expand on issue 2, no menu driver has *ever* been able to show thumbnails on history (or favourites) playlists. But this will be fixed soon! (although you'll need history/favourites playlists generated after PR #8434, otherwise you'll have to fill in `db_name` fields yourself...)

@natinusala I'm currently pulling out the thumbnail path construction code into a reusable header. This will automatically handle mixed content playlists. Should be plug and play once I've finished.

**Comment by natinusala** [comment]
@Ryunam I have a local fix, can you hop on Discord to see if you can try it before I submit a PR?

@jdgleaver nice!

**Comment by Ryunam** [comment]
@jdgleaver, yeah, in fact I noticed that going back to the XMB driver the History tab wouldn't display thumbnails either and the same goes for the Favourites category. I was not using thumbnails at all before this new implementation so I missed that aspect before, but I will be looking forward to your fix.

@natinusala Definitely, I'll be there in a minute.

**Comment by Ryunam** [comment]
PR https://github.com/libretro/RetroArch/pull/8452 fixes all of the above, however I have noticed another slight issue in the meantime. 

If you set "Collapse the sidebar" to ON under User Interface -> Appearance, when you either toggle between Fullscreen and Windowed with F or open the Desktop Menu with F5, the menu will extend the left sidebar anyway with missing text. 
As soon as you press the back button in the RetroArch menu, it goes back to its collapsed state as normal.

Here is a screenshot right after toggling Fullscreen / Windowed mode: https://imgur.com/a/7GUXP1G

**Comment by natinusala** [comment]
Oops, looks like wrong state reset when resetting context. Will fix it as part of #8452 if it's not merged in the meantime

**Comment by natinusala** [comment]
Fix: https://github.com/libretro/RetroArch/pull/8452/commits/3a9a9df2188cead2fb00dae94eb21f64d2844768

**Comment by Ryunam** [comment]
Sorry for the late comment, I had time just now to test this. With the latest code everything seems to be working properly and the menu stays collapsed when toggling between Fullscreen and Windowed as well.
Thank you @natinusala as usual for your impressive work!
