### ISSUE TITLE
After Commit 031bcf8 Retroarch no longer compiles on Amlogic devices

### ISSUE THREAD

**Issue by shantigilbert** [libretro/RetroArch#8448]
## Description
After Commit 031bcf8cbcb963a2416a5fa0b5f329ac1b334958 Retroarch no longer compiles on Amlogic devices

Using the following params 

``` 
HAVE_NETWORKING=1
HAVE_LAKKA=1
HAVE_ZARCH=0
HAVE_QT=0
HAVE_OPENGL1=0

```

Configure options: 

``` 
--disable-vg \
--disable-sdl \
--disable-ssl \
 --enable-opengles \
 --disable-kms \
 --disable-x11 \
 --enable-mali_fbdev \
--disable-qt \
--enable-neon \
 --enable-zlib \
--enable-freetype \
 --disable-discord"
```
compilation fails with the following errors: 

``` 
LD retroarch
obj-unix/release/gfx/video_driver.o:video_driver.c:function video_driver_find_driver: error: undefined reference to 'video_gl_core'
obj-unix/release/gfx/video_driver.o:video_driver.c:function video_driver_find_driver: error: undefined reference to 'video_gl_core'
obj-unix/release/gfx/video_driver.o:video_driver.c:function video_driver_find_driver: error: undefined reference to 'video_gl_core'
obj-unix/release/gfx/video_driver.o:video_driver.c:function video_driver_find_driver: error: undefined reference to 'video_gl_core'
obj-unix/release/gfx/video_driver.o:video_driver.c:video_drivers: error: undefined reference to 'video_gl1'
obj-unix/release/gfx/font_driver.o:font_driver.c:function font_init_first: error: undefined reference to 'gl_core_raster_font'
obj-unix/release/gfx/font_driver.o:font_driver.c:function font_init_first: error: undefined reference to 'gl_core_raster_font'
obj-unix/release/gfx/font_driver.o:font_driver.c:function font_init_first: error: undefined reference to 'gl1_raster_font'
obj-unix/release/gfx/font_driver.o:font_driver.c:function font_init_first: error: undefined reference to 'gl1_raster_font'
obj-unix/release/menu/menu_driver.o:menu_driver.c:menu_display_ctx_drivers: error: undefined reference to 'menu_display_ctx_gl1'
obj-unix/release/menu/menu_driver.o:menu_driver.c:menu_display_ctx_drivers: error: undefined reference to 'menu_display_ctx_gl_core'
collect2: error: ld returned 1 exit status
make: *** [Makefile:196: retroarch] Error 1
```

I also tried passing HAVE_OPENGL_CORE=0 with the same result.

### Expected behavior
Compile

### Actual behavior
Fails
### Steps to reproduce the bug

1. Try to compile using mali_fbdev on amlogic

### Bisect Results

This started after commit https://github.com/libretro/RetroArch/commit/031bcf8cbcb963a2416a5fa0b5f329ac1b334958

Commit 0ff2832e83b43476cb9196ccae3d0b2456e1e817 compiles and works fine. 

### Environment information

- OS: CoreELEC

**Comment by orbea** [comment]
Probably broke here. https://github.com/libretro/RetroArch/commit/e961dadc9473f2130e26368785cf2a37d421b068

Try `./configure --disable-opengl1`

**Comment by shantigilbert** [comment]
@orbea Thanks, that along with ``` --disable-opengl_core ```  worked.

I guess HAVE_OPENGL1=0 and HAVE_OPENGL_CORE=0 has no effect. 

Will close this issue.

**Comment by orbea** [comment]
You can use `./configure --help` to see all of the supported configure arguments, its usually preferred to use these instead of make arguments.

Ideally it should work on arm without those arguments, but I haven't had a chance to try to improve the build process for the gl drivers yet.

**Comment by shantigilbert** [comment]
Thanks, I knew about the --help but to be honest for some reason I thought that the make arguments were the same :(

**Comment by orbea** [comment]
In this case the make arguments were being overridden by `config.mk` which is created by configure so they didn't work.

**Comment by shantigilbert** [comment]
Ahh makes sense now that you explain it!
