### ISSUE TITLE
Missing makefile for Playstation Classic

### ISSUE THREAD

**Issue by missionfloyd** [libretro/RetroArch#8449]
There doesn't seem to be a makefile here for PSC, as there is for S/NESC. How do we go about compiling?

There's no official binaries either. Are we supposed to rely on ModMyClassic for all of this?

**Comment by missionfloyd** [comment]
Okay, apparently they have a makefile over here: https://github.com/CompCom/RetroArch/tree/ps-classic, but haven't ~~shared with the class~~ submitted a pull request.

**Comment by twinaphex** [comment]
OK so can you tell us the Makefile that is missing then?

**Comment by orbea** [comment]
@twinaphex They seem to have 4 unique commits as of now.

https://github.com/CompCom/RetroArch/commit/9c1ed7ba8582ed304b5da9572fbf5c8d5a9f80e9
https://github.com/CompCom/RetroArch/commit/bbc773e643584c155e5042b394f5d771338b4b37
https://github.com/CompCom/RetroArch/commit/b6e91f7818dc42f7067f346d0fa802a328daee2b
https://github.com/CompCom/RetroArch/commit/6925cdf34ee2b9cfce25d465a4b5a853ad517c01

Not sure how much of this we want or can test.

**Comment by missionfloyd** [comment]
Sorry, I guess I could've been clearer about that.

What orbea said. The first one would be the makefile i"m talking about. 3 seems important too. 2 is just a theme, and 4 seems to be resizing screenshots to 160x128. You probably don't want that one.

**Comment by swingflip** [comment]
This make is wrong above and is incomplete. We are currently working on a local branch separate from origin and will be pushing a PR when it’s fully ready to mainline.

We aren’t going to make a PR to the main repo with the stuff half complete and with things missing. There are also some glaring issues with SONY’s wayland implementation which is also causing hefty issues with RA. 

We are currently going through all the cores and testing the psc build offering before doing ~90 PR requests which will take precedence

@twinaphex is fully aware of all this and we have spoken about this is in detail and laid out a proper deployment plan.

As of now, I am currently on vacation so I won’t be picking any of this at least till next week
