### ISSUE TITLE
[Android] Audio Mixer/Media Player not working

### ISSUE THREAD

**Issue by Danver2618** [libretro/RetroArch#8451]
## Description

Not being able to use the in built media player or audio mixer for playing music. Tried extensions: FLAC, WAV, MP3, M4A. If I disable Filter unknown extensions option and enable use built in media player and go to add a new audio file to mixer or play it, I see no options to do so and if a press A, it crashes/gets stuck.

### Expected behavior
I should get multiple options like
Add to mixer
Add to mixer and play
Run

### Actual behavior
I get no options to do anything if I choose the audio file and choose the only option, it crashes retroarch(vulkan) or it gets stuck at that screen(gl)

### Steps to reproduce the bug
1. Enable inbuilt media player
2. Disable Filter unknown extensions
3. Go to and choose to audio file
4. You will get an option with no text in front of it
5. Choose it

### Version/Commit
- RetroArch:2019-03-12-RetroArch.apk

### Environment information

- OS: Android
- Git version: 75102a4
- Compiler: Clang/LLVM (3.8.256229) 32 bit
- CPU: ARMv7 8 cores

**Comment by bparker06** [comment]
The "built in media player" is technically ffmpeg which isn't supported on Android, but the mixer uses specific decoders for the formats it supports and doesn't rely on ffmpeg... *however* the logic in load content that gives the options like "add to mixer and play" (regardless of the filter extensions setting) erroneously depends on ffmpeg support to be able to resolve certain audio extensions as being supported.

I've mentioned this bug a couple of times in the past but at the time nobody seemed interested in fixing it.

**Comment by bparker06** [comment]
A workaround for now might be to generate a music playlist from a PC, modify the paths to fit the location of the files on Android, and then choose the files via the playlist itself instead of Load Content, since the "add to mixer" options show up properly there even without ffmpeg support.
