### ISSUE TITLE
Please enable retroarch64 for x64 in play store

### ISSUE THREAD

**Issue by phcoder** [libretro/RetroArch#8462]
app-ra64-debug.apk contains both aarach64 and x64
$ unzip -l ./app/build/outputs/apk/ra64/debug/app-ra64-debug.apk|grep lib/
 16845408  1980-00-00 00:00   lib/arm64-v8a/libretroarch-activity.so
 16702648  1980-00-00 00:00   lib/x86_64/libretroarch-activity.so

Yet it looks like Retroarch64 is not available for 64-bit devices like e.g. Pixelbook through android subsystem

**Comment by bparker06** [comment]
@twinaphex is the one with the play store account so he would need to do it.

**Comment by bparker06** [comment]
duplicate of #7587
