### ISSUE TITLE
Quickmenu Controls remapping issues (dropdown not working, etc.)

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#8497]
## Description

When I start Retroarch, download the Dosbox core, load the Dosbox core (I doubt this is core-specific), start the core, go to quickmenu->controls, I see a bunch of problems:

### Problem 1)
a) I change `User 1 Device Type` from `Gamepad` to `Keyboard + Mouse`
b) I try to change the mapping of `B button` or any button
c) I cannot change it, it remains blank
d) I leave the submenu and re-enter
e) Now the remapping works
f) Changing back from `Keyboard + Mouse` to `Gamepad`
g) The remapping is still stuck on keyboard key choices until I leave the submenu and re-enter again.

### Problem 2)
On menu choices `User X Device Type` and button remapping choices, the drop-down menu doesn't appear when pressing OK.

However, on menu choices `User X Analog To Digital Type` the drop-down menu does appear.

The drop-down menu would be most useful on the `Button B` etc. remapping options, but there it doesn't work. So the user has to cycle through hundreds of choices one at a time.

### Problem 3)
I tested this problem with Caprice32 core, not Dosbox core, but shouldn't be core specific.

In `Quickmenu->Controls`, on `User 1 Device Type`, I have to choose *either* e.g. `Retropad`, `Amstrad Keyboard`, or `Amstrad Joystick`.

But I want to map my `DPAD` and `X` to `Amstrad Joystick Directions` and `Amstrad Joystick Fire`, and I want to map my `Y` to `Amstrad Keyboard Space` for smart bombs. This should be possible, but it seems that it isn't. I think the use case is very common with computer emulation, and most emulators support such mapping choices. The reason is old computer joysticks only had one fire button. So many games used space for smart bombs and other keys for additional controls.

As a side note, I don't understand that I have the choice `Retropad` here. `Retropad` is a *host* device. The Amstrad computers never supported `Retropad`.

### Expected behavior

See above.

### Actual behavior

See above.

### Steps to reproduce the bug

See above

### Bisect Results

This never worked AFAIK

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Nightly, Build date: Mar 19 2019
- Dosbox core 0.74 7216efe (not sure the core matters)

### Environment information

- OS: MacOS
- Compiler: N.A.

**Comment by fr500** [comment]
I wrote the remapping part, and most of this menu, and while I agree these
are important issues...
Those problems are more like general RA gui problems and I don't know how
to deal with them.

**Comment by orbea** [comment]
> As a side note, I don't understand that I have the choice Retropad here. Retropad is a host device. The Amstrad computers never supported Retropad.

There is an issue report for this one.

https://github.com/libretro/RetroArch/issues/6966

**Comment by sonninnos** [comment]
Problems 1 and 2 have been sorted for a while now, and 3 is not likely happening, so this can be closed.
