### ISSUE TITLE
Scanning creates no playlist in Archlinux

### ISSUE THREAD

**Issue by rapsaGnauJ** [libretro/RetroArch#8507]
## Description

Scanning files or directories on a freshly installed RetroArch instance doesn't work in Archlinux. The scan procceds but no playlist is created or atleas visible to the user in the menu.

### Expected behavior

Playlist should be created with their respective contents.

### Actual behavior

No playlist is created or visible.

### Steps to reproduce the bug

1. Open RetroArch on Archlinux.
2. Do a scan of a file or directory.
3. Check that there isn't any playlist in the video.

### Bisect Results

This issue happened to me on all 3 different Arch machines that I own. It exists since I use RetroArch (about 1.7.2).

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.6/9750719074

### Environment information

- OS: Archlinux.
- Compiler: obtained from pacman official repositories.

**Comment by orbea** [comment]
Please answer these questions.

1. Do you have the core info files?
2. Do you have the database files?
3. Does your content match content found in the database files?

**Comment by rapsaGnauJ** [comment]
I have cores for all the titles. The scan is succesfull on my Android and Windows setups with the same content, so I assume that the titles are on the database.

About having the database file, I'm not really sure. I've downloaded it with the online updater and I have a bunch of .rdb files on ~/.config/retroarch/database/rdb.

**Comment by orbea** [comment]
How about the core info files? I don't mean the core files such as `snes9x_libretro.so`, but the info files like `snes9x_libretro.info`.

https://github.com/libretro/libretro-super/tree/master/dist/info

I am not sure if arch provides them, but they are available through the online updater. You will need a writable directory to download them.

**Comment by gouchi** [comment]
@rapsaGnauJ Can you check that you have the package [libretro-core-info](https://www.archlinux.org/packages/community/any/libretro-core-info/) installed ?

**Comment by rapsaGnauJ** [comment]
I've just downloaded the package and everything seems to work correctly. Thanks for the help.

**Comment by orbea** [comment]
Great! I'll close this then, please let us know if you have any more issues.
