### ISSUE TITLE
KMS Mode: User can be stuck with unresponsive system

### ISSUE THREAD

**Issue by pinumbernumber** [libretro/RetroArch#851]
If RA is started in KMS and is unable to access /dev/input/event* (IE, it isn't running as root and the permissions don't allow unprivileged access), and there are no other input devices (joypad) accessible, there is no way to interact and no way to exit. Ctrl+alt+F[n] will not operate in this state. Only SysRq+REISUB or a hard power off will suffice (or maybe SSHing in).

This is the default state in Ubuntu and most users will not think to run RA as root.

Proposed solution: Simply exit with an error if /dev/input/event* are inaccessible? An error message telling what the problem is is already printed but it will never be seen unless you can exit RA in some other way.

**Comment by neagix** [comment]
just been affected by this one. no plans to restore the error on no inputs detected?
