### ISSUE TITLE
[Wii] Save Glitch

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#8512]
I was playing Pokemon Silver today on the mGBA core, and when I tried to save state, it crashed. If anyone can help with this, it would be much appreciated.

**Comment by RobLoach** [comment]
Need logs.

**Comment by YoderComixinc** [comment]
What is a log? i am new to github

**Comment by YoderComixinc** [comment]
or, does it have something to do with retroarch??

**Comment by RobLoach** [comment]
https://docs.libretro.com/guides/generating-retroarch-logs/

**Comment by YoderComixinc** [comment]
So, I need to record some data... well I will try to get more specific later, but now i will describe it as detailed as possible. So, there I was, playing Pokemon Silver on my Wii using Retroarch. I had beat the first gym in violet city. Also, my cyndaquil had evolved into quilava. I opened the menu-thingie by pressing the home button. I went over to "Save State" and clicked it. Everything was going as usual as the game began to save. But then, BAM! A message that said something about DSi's and stack dumps appeared. Plus my TV was making a very annoying buzzing noise. When I reloaded the system my save data was gone. I was devastated.  ):

**Comment by YoderComixinc** [comment]
This is why I have changed into a sad frog.

**Comment by YoderComixinc** [comment]
Ummmm..... Lets keep this on Github. 😨🤔

**Comment by YoderComixinc** [comment]
Hello?? Are you there??

**Comment by RobLoach** [comment]
Yes, sounds like the file failed to save? Would be good to check that the directories exist and your Wii can write to them.

Other than that, having the logs would really help in determining what went wrong. Thanks!

**Comment by YoderComixinc** [comment]
OK..... I have played many other games on retroarch, and they all save fine. I am wondering if it has something to do with the ROM.

**Comment by YoderComixinc** [comment]
Also, according to your website, there is no way to record logs on Nintendo consoles other that the switch.

**Comment by YoderComixinc** [comment]
This doesn't have anything to do with the issue. but, does retroarch wii have a n64 core?

**Comment by YoderComixinc** [comment]
Alright. Here is what it says:

:Exception (I:SI) occurred!
*bunch of numbers*

Stack Dump:
*bunch of numbers*

Reloading in 18 seconds;

Reload;

**Comment by YoderComixinc** [comment]
Also note that it wouldn't allow me to reload

**Comment by YoderComixinc** [comment]
This also happens when I try to load a game on the wrong core.

**Comment by YoderComixinc** [comment]
Sometimes it also has:

Core Dump:
*bunch of numbers*

**Comment by YoderComixinc** [comment]
Either you got fired or you're ignoring me.

**Comment by RobLoach** [comment]
I am unable to help you without seeing the entire logs. Does it load and save properly on another device?

**Comment by YoderComixinc** [comment]
Check out the 12th comment R.O.B (hehe) . And I only have retroarch on my Wii.
