### ISSUE TITLE
[Menu] No way to erase binding without a keyboard 

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#8515]
## Description

No way to erase a binding without a keyboard

### Expected behavior

There should be a retropad key to erase a binding in the menu. For example “hold start for 2 seconds to un-bind”. There’s a button to reset a binding to default. That’s start. But there’s no button to erase a binding (set to empty). On a keyboard this can be done by pressing DEL. But some platforms don’t have a physical keyboard, making this functionality inaccessible.

### Actual behavior

See above

### Steps to reproduce the bug

1. Go to settings input user 1 binds
2. Try to erase a binding using controller
3. Realize that can only be done by pressing DEL on a physical keyboard.

### Bisect Results

Always been a problem AFAIK

### Version/Commit
You can find this information under Information/System Information

- RetroArch: MARCH 21 2019 nightly 

### Environment information

- OS: Switch libnx
- Compiler: [In case you are running local builds]

**Comment by fr500** [comment]
It's true, you can't unbind.
That said it's not really something required unless you're actually hooking up a keyboard.

Only then this becomes a problem, and then you can unbind just fine.

**Comment by orbea** [comment]
What button on a gamepad would you propose should delete keybinds?

**Comment by rsn8887** [comment]
Not sure, maybe hold start for a long time (2 seconds or so)? Short press of start is already "reset to default".

**Comment by rsn8887** [comment]
And select is already reserved for context help.

**Comment by fr500** [comment]
there is no help in that entry so it could be used all the same

**Comment by huwpascoe** [comment]
Thinking either:
* Have a countdown timer after selecting "bind" where if the user doesn't press anything, it unbinds whatever was there
* Pressing what has already been bound, unbinds it. If a button is bound to 'Z', selecting "bind" and then pressing 'Z' again, will unbind it.

**Comment by orbea** [comment]
> Have a countdown timer after selecting "bind" where if the user doesn't press anything, it unbinds whatever was there

This could be annoying if the option is selected accidentally or the user wants to only set a few of the binds.

> Pressing what has already been bound, unbinds it. If a button is bound to 'Z', selecting "bind" and then pressing 'Z' again, will unbind it.

What if the `Z` key is missing or otherwise broken?

> Not sure, maybe hold start for a long time (2 seconds or so)? Short press of start is already "reset to default".

This might be workable and `select` might be fine too as fr500 said.

**Comment by rsn8887** [comment]
I feel like select might be best, since it is 
a) Logical. Since start is reset to default, so it makes sense that select also does something
b) Discoverable. People will probably try select if they are looking for this option. They will never try holding start for 2 seconds.
c) Available, I think almost all controllers that have a start button also have a select button

**Comment by sonninnos** [comment]
This can be closed, since RetroPad Y does the erasing: https://docs.libretro.com/guides/input-and-controls/#hotkeys
