### ISSUE TITLE
Playlist Issues

### ISSUE THREAD

**Issue by HarryTheTurtle** [libretro/RetroArch#8518]
I'm having trouble with adding some games to the playlist. Some games will not scan in the directory they are currently stored in but will properly be added to the playlist if I scan the parent directory the games are in. Scanning the parent directory takes forever because it has to scan every game again.

Some games will not add to the playlist no matter how I scan them like Digimon World Championship, Radiant Historia, and Might & Magic - Clash of Heroes.

All four of those games are Nintendo DS (USA) .NDS files.

OS - Windows 10

**Comment by orbea** [comment]
> Some games will not add to the playlist no matter how I scan them like Digimon World Championship, Radiant Historia, and Might & Magic - Clash of Heroes.

They may not match the content in the database files.

I'm not sure about the other issue.

**Comment by HarryTheTurtle** [comment]
I can see that these games are in the RDB files but I'm not sure what data is conflicting with the ROMS I have that is causing them to not appear in my playlists.

**Comment by RobLoach** [comment]
The files you're scanning likely don't have the same CRC value as what's in the database. You'll either need to...

- Apply a patch to the file so that it matches what's in No-Intro
- Add them in manually, or
- Build the playlist using a playlist generator like https://www.marcrobledo.com/retroarch-playlist-editor/

**Comment by HarryTheTurtle** [comment]
Thanks Rob. I see what I need to do now to match the No-Intro database although it is a complicated, frustrating, and confusing process to patch the files. But that is my problem.

Thanks for telling me about the Marcobledo. I used it to create my playlist but unfortunately creating a playlist this way does not display thumbnails.

I understand what the problem is now and how to fix it. Thanks a lot guys.
