### ISSUE TITLE
Unable to edit "Bind Hold" Option with touch, mouse or drop down menus.

### ISSUE THREAD

**Issue by pigsonthewing12** [libretro/RetroArch#8528]
## Description 

Cannot edit "Bind Hold" option

### Expected behavior

When I touch "Bind Hold" to change the default value, a menu should pop up with an option to change the default value of "2" to "another number"

### Actual behavior

When I touch "Bind Hold" to change the default value, the background of the field turns light blue to indicate it has been clicked, but nothing happens. I am unable to alter the field.

### Steps to reproduce the bug

1. Enable "Show Advanced Settings" in "User Interface" menu
2. open "Input" Menu
3. try and touch "Bind Hold"

### Version/Commit

I'm running retroarch 1.7.5 (latest release)

### Environment information

The latest version of Android on my pixel 2.

**Comment by markwkidd** [comment]
RetroArch 1.7.6 was released on February 4. Could you update your installation and see if the problem still exists?

**Comment by pigsonthewing12** [comment]
Hey.

Id be happy to as soon as I see the update on the store. I just checked but
it still says 1.7.5 and doesn't let me update it.

See the screenshot attached

**Comment by pigsonthewing12** [comment]
Hey. So I just realized you said Feb 4th. Since I don't see it on the store, I manually downloaded and installed the apk. Unfortunately, the problem still persists for me on version 1.7.6

**Comment by markwkidd** [comment]
I can't see anything out of the ordinary in that part of the source code, but the relevant section isn't really the bind hold code rather than the settings code I would imagine. Hopefully someone else with the relevant experience will be able to help.

Just to confirm: can you change the value of other settings in the same menu as the Bind Hold values?

**Comment by pigsonthewing12** [comment]
Some of them I can and some of them I can't.

I can edit:
Max Users
Unified Menu Controls
Poll Type Behavior
Menu Toggle Gamepad Combo
Menu Swap OK & Cancel Buttons
All Users Control Menu
Remap Binds Enable
Autoconfig Enable
Analog Stick Deadzone
Input Hotkey Binds
Input User Binds (1, 2, 3, 4, 5)

Cannot Edit:
Bind Timeout
Bind Hold
Turbo Period
Duty Cycle

**Comment by fr500** [comment]
That means those don't have touch/mouse callbacks set

**Comment by pigsonthewing12** [comment]
That makes sense. How do we get that fixed?

**Comment by orbea** [comment]
The drop down menus are also missing for these.

**Comment by pigsonthewing12** [comment]
Hey, checking in. Whats the latest on this issue?

**Comment by sonninnos** [comment]
Fixed ages ago.
