### ISSUE TITLE
Pressing delete key does not remove menu configurations

### ISSUE THREAD

**Issue by micsthepick** [libretro/RetroArch#8531]
## Description

Pressing delete will clear input bindings, but it does not clear configurations such as "audio device". Pressing retro-pad buttons does not appear to work either, unless they are pressed from a physical controller and not a keyboard

### Expected behavior

Pressing delete should clear (or default) the menu items.

### Steps to reproduce the bug

1. Use latest Windows executable
2. Set a value for "Audio Device"
3. Press "del", or the keyboard binding for retropad start or retropad select or retropad x or retropad y, pressing start on a controller seems to be the only thing that works

## what version?
Suspect any version, tested in 1.7.5 and 1.7.6

**Comment by fr500** [comment]
Space is default.
Delete is just for a few things.

**Comment by micsthepick** [comment]
that works, but I reckon delete should also work.

**Comment by orbea** [comment]
Delete removes the key which is not applicable for all settings and space resets to the default which is again not applicable for all settings.

This is working as intended, but its true that there doesn't seem to be a way to remove the binds with a gamepad. See: https://github.com/libretro/RetroArch/issues/8515
