### ISSUE TITLE
Retroarch farwarder NSP

### ISSUE THREAD

**Issue by fennectech** [libretro/RetroArch#8539]
This retroarch NSP simply launches the nro at /switch/retroarch_switch.nro meaning we no longer have to update the NSP on the site if we use that.   It also eliminates the problem of having an outdated NSP and lauches as if it were launched by title takeover from hbmenu.
https://www.reddit.com/r/SwitchHacks/comments/b7mc9e/retroarch_forwarder_any_version_nsp/

**Comment by m4xw** [comment]
@fennectech Just stop it.
It was not dropped because of that.
