### ISSUE TITLE
[Linux] Retroarch should ignore keys that are pressed as system shortcuts.

### ISSUE THREAD

**Issue by Blast-City** [libretro/RetroArch#8545]
elementary OS Juno (Ubuntu 18.04).
Retroarch from the stable repository. Fully updated.

1- Open Retroarch
2- Press Super+Right Arrow to switch to another workspace

**Result:** The workspace changes, but Retroarch's menu also changes.

Is this the normal behaviour? Shouldn't Retroarch ignore the arrow keys when it's pressed as a system keyboard shortcut?

On Firefox as soon as i press the Super key, keyboard inputs are disabled. The same happens on Steam main window or in the terminal. Steam video player also have a similar problem as Retroarch.

**Comment by orbea** [comment]
This is not a good idea, these keys are going to differ from system to system and the only way to "solve" it is to ignore all keys which is just not going to happen.

**Comment by Blast-City** [comment]
> This is not a good idea, these keys are going to differ from system to system and the only way to "solve" it is to ignore all keys which is just not going to happen.

Hi.

Maybe I'm not understanding what you're saying, but I was just talking about when the Super key is pressed.

If i press Super right now on firefox i can't write any more letters on this box. So Firefox seems to be aware of which keys are system shortcuts.

Thanks.

**Comment by orbea** [comment]
What if the user doesn't use the windows key and uses `alt` instead? What if they are using another arbitrary key like `w`? I guess this might even be a key combination...

**Comment by orbea** [comment]
Also, fwiw I can't reproduce this at all. RetroArch and firefox both correctly recognize that I am pressing `mod+arrow key` instead of `mod` and the `arrow key`.

**Comment by Blast-City** [comment]
> Also, fwiw I can't reproduce this at all. RetroArch and firefox both correctly recognize that I am pressing `mod+arrow key` instead of `mod` and the `arrow key`.

Hi.

When you click on the address bar of Firefox and press the Super key what happens? Can you input any letters while pressing the super key?

On my computer as soon you press Super you can't press any key. It's like it is on a lock state.

**Comment by orbea** [comment]
Firefox is not blocking the key, its recognizing its a key combo and not a single key being pressed where firefox doesn't use any such key combos by default and hence does nothing. This should be the same in RetroArch and I can't reproduce otherwise.

What RetroArch version are you using? What input driver are you using in RetroArch? Do you have any conflicting non-default keybinds in your RetroArch configuration?

**Comment by Blast-City** [comment]
> Firefox is not blocking the key, its recognizing its a key combo and not a single key being pressed where firefox doesn't use any such key combos by default and hence does nothing. This should be the same in RetroArch and I can't reproduce otherwise.
> 
> What RetroArch version are you using? What input driver are you using in RetroArch? Do you have any conflicting non-default keybinds in your RetroArch configuration?

Latest version on the stable repo. Default configuration.

If i go to Youtube on Firefox and I play a video, using the arrow keys makes the videos fast-forward or go backward, but if i press Super+Arrow keys (workspace switch shortcut) the video continues to play normally (arrow keys ignored) and the workspace switches to another one.

If i do the same on Retroarch main menu, the arrow keys are accepted, so the menu changes at the same time as the workspace switch. I think this behaviour shouldn't be happening because when you go back to the retroarch workspace what is on the screen is not the same as it was when you switched workspaces.

Maybe ignore key presses if the window looses focus, but the input would probably reach Retroarch before the lost of focus.

**Comment by orbea** [comment]
> Latest version on the stable repo. Default configuration.

Which is what version?

**Comment by Blast-City** [comment]
> > Latest version on the stable repo. Default configuration.
> 
> Which is what version?

https://launchpadlibrarian.net/410056719/retroarch_1.7.6-r201902062228-9750719-83~ubuntu18.04.1_source.changes

**Comment by orbea** [comment]
So `1.7.6`...

> If i do the same on Retroarch main menu, the arrow keys are accepted, so the menu changes at the same time as the workspace switch. I think this behaviour shouldn't be happening because when you go back to the retroarch workspace what is on the screen is not the same as it was when you switched workspaces.

This shouldn't happen, what input driver are you using? Is with with x or wayland?

@hunterk Can you reproduce this?

**Comment by orbea** [comment]
Okay, I can kind of reproduce this...

I am getting stray key input when switching to the workspace with RetroArch, but not when switching away. This also clearly affects a KMS context, but that is not really a problem.

**Comment by orbea** [comment]
Given how confusing this issue is and the how the issue template was ignored I made a new issue that is hopefully easier to understand. I hope this works for you?

https://github.com/libretro/RetroArch/issues/8550

**Comment by Blast-City** [comment]
> So `1.7.6`...
> 
> > If i do the same on Retroarch main menu, the arrow keys are accepted, so the menu changes at the same time as the workspace switch. I think this behaviour shouldn't be happening because when you go back to the retroarch workspace what is on the screen is not the same as it was when you switched workspaces.
> 
> This shouldn't happen, what input driver are you using? Is with with x or wayland?
> 
> @hunterk Can you reproduce this?

I'm using X (elementary OS Juno)
