### ISSUE TITLE
retroarch freezes when display input port is switched

### ISSUE THREAD

**Issue by asavah** [libretro/RetroArch#8553]
## Description
When working on a monitor with several inputs (DP,HDMI1,HDMI2) if you switch the input to another channel retroarch will freeze. When you change the input back to the port where PC running retroarch was you'll see the menu but the gui will not respond to any inputs, if you switch from X to for example vt1 and back to X you'll get a black screen.
Same behavior if you start retroarch via ssh (with DISPLAY=:0 ofcourse) but with monitor using another input port.
Nothing interesting at the logs or dmesg.

### Expected behavior
When you switch back to the input where retroarch machine is connected it should just work.

### Actual behavior
It hangs, retroarch needs to be killed and started again.

### Steps to reproduce the bug
1. Run retroarch.
2. Switch monitor input to another port.
3. Wait around a minute.
4. Switch monitor input back to retroarch machine.

### Version/Commit
master built grom git @ 9579804

### Environment information

- OS: own project, Gnu/Linux x86_64, on amd 2400G , kernel 5.0.7, mesa 19.0.1/llvm 8.0, Xorg + openbox, using DisplayPort
- Compiler: gcc 8.3.0, binutils 2.32, glibc 2.29

### Side note
Kodi perfectly survives such input switches on the very same machine.
Happens on both gl and glcore drivers, with both vsync on and off (have to have it off because of reicast issues)

Can provide logs and quickly test patches if necessary.

**Comment by fr500** [comment]
try with audio driver null, I have a feeling it's the audio driver

**Comment by asavah** [comment]
Your feeling is indeed correct.
It does not occur with null.
Both waiting after switching input and starting via ssh while display is on another input work fine.

I use pulseaudio driver, pulseaudio runs as system daemon (I know it's not recommended by pa devs). and it has no alsa mappings, outputs only to bluetooth headphones.

**Comment by fr500** [comment]
It happens on windows too (even unplugging my headphones results in a
lockup)

**Comment by asavah** [comment]
Another observation:
it does NOT happen if you load a core, a game and open RA menu.

**Comment by orbea** [comment]
I could not reproduce this in Linux, but maybe I need something to actually use the other monitor ports? I am using the alsa audio driver and do not have pulseaudio installed.

**Comment by asavah** [comment]
I have the following setup:
Samsung U28H75X display with DP and 2 hdmi ports.

DP - amd 2400G box with my pet linux and retroarch
hdmi1 - ubuntu box
hdmi2 - windows box

Audio is going through pulseaudio -> bluez -> bluetooth headphones (headphones remain connected)
Alsa is present but pulseaudio is configured to ignore alsa.

Retroarch is configured to start in Fullscreen (not windowed)

The way I stumbled into the issue:
- Play a bit on retroarch.
- Switch to windoze box to do some stuff for like 15 mins
- Switch back to RA box
- Find RA frozen and not responding to input, retroarch process keeps running, no crash, nothing weird in dmesg or journalctl.

To simplify the repro this is how it freezes for me all the time:

- Use the hdmi2 input on monitor (windoze box)
- Connect to RA box via ssh, run `DISPLAY=:0 retroarch` with pulse sound driver
- wait like 30 seconds
- switch to DP input
- frozen and irresponsive RA

----------------------------------
I've done some more tests to try and narrow it down.

Fullscreen + pulse => freeze
Fullscreen + null   => good
Fullscreen + alsa => good

Windowed fullscreen + pulse => freeze
Windowed + pulse => good

So this narrows it down to fullscreen + pulseaudio in my case.
