### ISSUE TITLE
setting analog deazone in RA stops L2/R2 analog triggers working

### ISSUE THREAD

**Issue by grant2258** [libretro/RetroArch#8554]
## Description

[Description of the bug]
setting analog deazone in RA stops L2/R2 analog triggers working
### Expected behavior
expected the deadzone to to work with the radius increased for the button 
[What you expected to happen]
expected the deadzone to to work with the radius increased for the button 
### Actual behavior
analog button returns 0
[What is actually happening]
analog button returns 0
### Steps to reproduce the bug

. goto settings input -> Analog deadzone set it to anything other than 0.0

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
[INFO] RetroArch 1.7.6 (Git ffad99d886)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AES
[INFO] Built: Apr  7 2019
[INFO] Version: 1.7.6
[INFO] Git: ffad99d886

### Environment information

- OS: Windows10 64 bit
- Compiler: gcc version 8.3.0 (Rev2, Built by MSYS2 project)

New issue opened as requested. Should a deadzone even be applied to the analog buttons as well ?

**Comment by orbea** [comment]
> Should a deadzone even be applied to the analog buttons as well ?

Probably not, is there any good reason to do this? I personally would expect deadzone to only apply to the analog sticks. @bparker06 would you mind looking into this?

**Comment by grant2258** [comment]
Ok just some information to show whats going on some cores if the analog fails it falls back and reads the digital and returns 32768 if digital is pressed. I personally just read the port and print the values being printed. 

To reproduce this problem on current mame so show its not working 

this setting works
1) set deadzone to 0.0
2) start outrun press f2 to get into service mode
3) press left and right until you get to input test 
4) press the l/r triggers  the value is variable

now to show it not working go to the menu  set the deadzone to anything accept 0.0
press the l/r triggers they return digital fallback mode

**Comment by grant2258** [comment]
just tested this in linux (debian stretch x64 same commit) xbox one controller only one analog button reports the values with the deadzone being set remains at 0 for analog values

**Comment by bparker06** [comment]
Should be fixed in e0b59f13e2.

Also, analog buttons were not part of the original libretro v1 spec, someone has added them without bumping the version number, and now (at least one) core is using it (beetle psx IIRC), breaking backwards compatibility with older frontends.

**Comment by grant2258** [comment]
Well i tested on windows the fix is working thanks ill close this off ill test in linux when i get the chance cant see there being any issue though.
