### ISSUE TITLE
Run Ahead - Hiscores not working FBA core

### ISSUE THREAD

**Issue by kikeminchas** [libretro/RetroArch#8556]
## Description

When using run Ahead the Hiscores functionality does not work. It works fine when the core is started without using run Ahead.

### Expected behavior
Hiscores working as expected with run Ahead.

### Actual behavior

Hiscores not being saved, even if the game supports it 

### Steps to reproduce the bug
Use FBA, load a game that supports Hiscores (i used street fighter 2' hyper fighting. Hiscores.dat is placed in system folder. Hiscore option active in core options. Without run ahead, hiscores are saved as expected. With run ahead on, they are not.

### Bisect Results

NA

### Version/Commit
Retroarch 1.7.5 (Android 32 bits)
Retroarch 1.7.6 (Android 64 bits)

### Environment information

- OS: Android TV 8.0 / Android 9.0

**Comment by fr500** [comment]
This is a core issue, please report in the proper repo.

**Comment by kikeminchas** [comment]
Done.
https://github.com/libretro/fbalpha/issues/209

Closing this one.
