### ISSUE TITLE
Feature Request: CLI use 'known good' Core w/o forcing in CLI

### ISSUE THREAD

**Issue by Ltek** [libretro/RetroArch#8557]
Since RetroArch 'remembers' the last used Core with all ROMs AND RA automatically sorts them into Playlists for each given Core... there should be No Reason to require a CLI to tell it what to Core to use with a given ROM.

I'm new to RA and want to use LaunchBox as front-end (since RA is not kid or guest friendly) and having to manually set LB for EVERY ROM to a given Core sux. 

PLEASE add this, it cant be difficult since the app already does this!

**Comment by bparker06** [comment]
What makes RA kid/guest unfriendly?

**Comment by hizzlekizzle** [comment]
We don't provide support for Launchbox here, but there's no reason you would need to set specific launch lines for each game. At worst, you need to do it for each system.

**Comment by RobLoach** [comment]
> there's no reason you would need to set specific launch lines for each game

If there was no reason for the -L option, I wouldn't be there. There's an issue open to auto detect a core... https://github.com/libretro/RetroArch/issues/746

**Comment by orbea** [comment]
I'm going to close this in favor of the issue @RobLoach linked which is pretty much a duplicate.
