### ISSUE TITLE
(D3D10/11/12) Menu widgets - wrong clipping of widgets

### ISSUE THREAD

**Issue by inactive123** [libretro/RetroArch#8570]
Problem:

When menu widgets are enabled (configure --enable-menu_widgets), the D3D10/11/12 drivers have problems displaying the menu widgets properly in fullscreen mode when using the Ozone menu driver.

Example illustrating the problem:

![image](https://user-images.githubusercontent.com/1075274/55843543-285da500-5b39-11e9-86ea-0521c18277e9.png)

(How it looks like in windowed mode)

![image](https://user-images.githubusercontent.com/1075274/55843554-33b0d080-5b39-11e9-954c-942856326058.png)

(How it looks like in fullscreen mode)

I can confirm that it has something to do with the scissor_begin implementation in menu display driver (for D3D01/11/12). NOTE: Only the Ozone menu driver uses scissoring. XMB and MaterialUI don't, so this wrong clipping of menu widgets is not happening there.

There is a weird way of working around this bug:

* Start in windowed mode
* toggle fullscreen
* toggle fullscreen again to go to windowed
* go to fullscreen again
* the widgets are displayed properly now and there are no more clipping issues

You can also do this the other way around - starting in fullscreen mode
* Start in fullscreen mode
* toggle fullscreen to go to windowed
* toggle fullscreen to go back to fullscreen again
* the widgets are displayed properly now and there are no more clipping issues

Another big issue:
* Widgets don't work at all when we are ingame and there is no menu active.

NOTE: This happens on all menu drivers right now, MaterialUI/XMB/Ozone. This issue does not seem to be scissoring-related.

**Comment by bparker06** [comment]
should be fixed in 7648da1413d8718ca29bb7eecff61c5ab677ef5a

**Comment by twinaphex** [comment]
OK, everything is fixed in this issue except for this one (and it's still a rather big issue on its own) -

Widgets don't work at all when we are ingame and there is no menu active.
NOTE: This happens on all menu drivers right now, MaterialUI/XMB/Ozone. This issue does not seem to be scissoring-related.

**Comment by twinaphex** [comment]
Should be fixed with this -

https://github.com/libretro/RetroArch/commit/702c889cd19121a4e244339559fb16cb592bd704

**Comment by furiadeoso** [comment]
Sorry, perhaps this is unrelated. Menu widgets are covered by Overlays. Must I open a new issue or showing widgets over overlays is in the roadmap?

**Comment by ToniBC** [comment]
The same thing I wanted to put, when you activate the overlays or bezels, the notifications and messages come out behind and cover the overlay.

**Comment by SerjTargarien** [comment]
I was testing the achievement widgets and the kick ass, but yeah, there should definetly be a way to show them over overlays. Opening a new issue about it.
