### ISSUE TITLE
Translation test

### ISSUE THREAD

**Issue by fpscan** [libretro/RetroArch#8572]
## Description

Hi everyone, I use RA everyday and mostly every platform( pc, switch, 3ds, psc) and I recommend everyone I know, recently I wanted to translate my native language which is not translated before. I did some research and find few things but it wasn’t clear for me, those posts says that it can be done with GitHub. So I followed this steps; https://webcache.googleusercontent.com/search?q=cache:xyq_RE8XVO4J:https://docs.libretro.com/tech/new-translations/+&cd=1&hl=tr&ct=clnk&gl=tr

And you can find my translations in here https://github.com/fpscan/RetroArch/tree/master/intl > msg_hash_tr.c && msg_hash_tr.h 

So my questions are, how can I see my translations live, I mean anychance I see how its fitted into RA menu and what should I do when I done translation whole text? I use GitHub Desktop and SublimeText for editing. I am really new for GitHub so every suggestions, tips and tricks would be great!

- OS: Windows 10

**Comment by orbea** [comment]
This is not a support forum, I would suggest asking on the forum, discord or irc instead for help.

Basically you edit `msg_hash_tr.h` with your changes using `msg_hash_us.h` as a template and then you build RetroArch with `./configure && make` and test your translations.
