### ISSUE TITLE
LGTM builds are failed on all PR's

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#8581]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

LGTM builds are failed on all PR's.

### Expected behavior

LGTM should function without errors.

### Actual behavior

LGTM is unusable now.

Actual error. for example, from https://lgtm.com/projects/g/libretro/RetroArch/logs/rev/pr-c4a495c87d7f466667fd41ad40a2eb92fe662b3e/lang:cpp/stage:Build%20merge_c43bc3a3a024a0ab4a61d772301c648234dbcae4

```
[2019-04-12 17:15:47] [build] In file included from /usr/include/libroar/libroar.h:173,
[2019-04-12 17:15:47] [build] from /usr/include/roaraudio.h:133,
[2019-04-12 17:15:47] [build] from audio/drivers/roar.c:22:
[2019-04-12 17:15:47] [build] /usr/include/libroar/vio_stdio.h:50:46: error: unknown type name ‘_IO_off64_t’; did you mean ‘__off64_t’?
[2019-04-12 17:15:47] [build] int roar_vio_to_stdio_lseek (void *__cookie, _IO_off64_t *__pos, int __w); 
[2019-04-12 17:15:47] [build] ^~~~~~~~~~~ 
[2019-04-12 17:15:47] [build] __off64_t
[2019-04-12 17:15:48] [build] make: *** [Makefile:201: obj-unix/release/audio/drivers/roar.o] Error 1
```

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
@bparker06 You might want to look into this one.

**Comment by bparker06** [comment]
Possibly an upstream bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915345

**Comment by orbea** [comment]
Its not available for Slackware either, I'll try to see how far I can get in reproducing this.

**Comment by orbea** [comment]
I downloaded, built and installed `roaraudio-1.0beta12`. I next found that RetroArch successfully detected libroar and I was able to build it without issues.
```
$ ldd retroarch | grep -i roar
	libroar.so.2 => /usr/lib64/libroar.so.2 (0x00007fd883988000)
```
I then tried to change the audio driver to `roar` and tried to play a game, but I had no sound. I don't know anything about roaraudio so maybe I am missing something?

**Comment by orbea** [comment]
I can reproduce very similar errors building `roaraudio-1.0beta11`.
```
make[1]: Entering directory '/tmp/SBo/roaraudio-1.0beta11/libroar'
/usr/local/bin/gcc -O2 -fPIC -g -Wall -O2  -I../include -I../include/libroar   -fPIC   -c -o libroar.o libroar.c
In file included from ../include/libroar/libroar.h:173,
                 from libroar.c:40:
../include/libroar/vio_stdio.h:50:46: error: unknown type name ‘_IO_off64_t’; did you mean ‘__off64_t’?
 int roar_vio_to_stdio_lseek (void *__cookie, _IO_off64_t *__pos, int __w);
                                              ^~~~~~~~~~~
                                              __off64_t
make[1]: *** [<builtin>: libroar.o] Error 1
make[1]: Leaving directory '/tmp/SBo/roaraudio-1.0beta11/libroar'
make: *** [Makefile:23: all] Error 2
```
I think the solution is to update roaraudio on the LGTM build environment. Otherwise roaraudio could be removed so its not detected or `--disable-roar` can be used to disable building it.

@bparker06 Would you know how to implement one of these fixes for LGTM?

**Comment by bparker06** [comment]
According to that bug report it says:
```
Found in version roaraudio/1.0~beta11-11
Fixed in version roaraudio/1.0~beta12-1
```
So that's probably why it works for you.

**Comment by orbea** [comment]
Maybe you missed my second comment where I also found this to be true? I'm not sure how or where to change anything for LGTM so I think you will need to work on that.

**Comment by orbea** [comment]
@Themaister I see you added roaraudio support a long time ago, what do you currently think about supporting it in RetroArch?

I think the current choices are:

1. Leave it be in its current mostly unmaintained state, I bet most people aren't even trying to use it.
2. Update it to work, it seems only debian carries it and I'm not sure it has any benefits over something like jackd?
3. Remove it.

**Comment by ofry** [comment]
Could we add version constraint to qb scripts? So if libroar isn't recent enough, we will skip roaraudio sound driver?

**Comment by orbea** [comment]
Okay, lets try that. I opened a draft pull request to see if LGTM passes.

**Comment by orbea** [comment]
Good news, that seems to work.

Bad news, the xcode travis is broken again...
