### ISSUE TITLE
Cannot set OSD font (Nintendo Switch)

### ISSUE THREAD

**Issue by newget** [libretro/RetroArch#8593]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Cannot display .ttf files in OSD font setting page

### Expected behavior

display .ttf files

### Actual behavior

'No items' appears

### Steps to reproduce the bug

1. Go to Onscreen Display - Onscreen Notifications - Notification Font
2. Go to the folder that has ttf files
3. It says 'No items'

### Bisect Results

Stable 1.7.6 doens't have this issue. Only nightly has.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: latest retroarch nightly for nintendo switch
I tried this one. 2019-04-17 01:39

### Environment information

- OS: Nintendo Switch
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
@orbea
Bisect results:

ad7cb35d31d65a31e1289e84671eb6b5d0d21a47 is the first bad commit
commit ad7cb35d31d65a31e1289e84671eb6b5d0d21a47
Author: orbea <orbea@riseup.net>
Date:   Fri Mar 1 11:07:06 2019 -0800

    Fix double root directory.
    
    Fixes https://github.com/libretro/RetroArch/issues/8385
    
    Regression after https://github.com/libretro/RetroArch/commit/5fcedc86195c9b1b8a79c7b5f9e59f9c5c46012b

:040000 040000 caa0d657fa156a824b0db846ca79d40831b15c65 6275fd36d1638fd6d70390e156d200927327be7b M	menu

**Comment by orbea** [comment]
I can reproduce this, I'll take a look.

**Comment by orbea** [comment]
I submitted a PR which fixes this here, the menu font was also affected.
