### ISSUE TITLE
Travis CI builds with XCode 10.1 failing

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#8603]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Travis CI builds with XCode 10.1 failing

### Expected behavior

Travis builds should compile without any errors.

### Actual behavior

Link to log: https://travis-ci.org/libretro/RetroArch/jobs/522001298

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: e61c3316564f186d47ab0b55c887cd361b643026

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
Seems @twinaphex fixed it here. :)

https://github.com/libretro/RetroArch/commit/1fb1b1bdb7855d86672b8e0f8673ee84fac0b12d

**Comment by twinaphex** [comment]
At last, glad to hear that nailed it.
