### ISSUE TITLE
SNES content frameskips whilst in fullscreen, but not in windowed

### ISSUE THREAD

**Issue by Sonickyle27** [libretro/RetroArch#8604]
## Description

When running SNES content with any SNES cores (like higan, bsnes(-mercury), Snes9x) in fullscreen, the content is presented with frameskipping. Other content cores like MAME, FB Alpha, and Genesis Plus GX do not show this issue.
The menu is not affected by this, and the "Display Framerate" option displays the framerate as 60.0 while in fullscreen.

### Expected behavior

The content should be presented at the same framerate that it is in windowed mode.

### Actual behavior

The content is presented at a reduced framerate while in fullscreen. RivaTuner says it is running around 30fps with uneven framepacing.

### Steps to reproduce the bug

1. Open RetroArch and load up an SNES game in an SNES core.
2. Put RetroArch into fullscreen if it isn't.
3. The content is presented in 30fps.
4. Put RetroArch in windowed mode, and the content is presented in 60fps.

### Bisect Results

I unfortunately do not know when this started happening. I believe it also happened in 1.7.5, but I'm not sure.

### Version/Commit

- RetroArch: 1.7.6

### Environment information

- OS: Windows 10 Pro version 1803

### Log and config

[retroarch-log.txt](https://github.com/libretro/RetroArch/files/3097906/retroarch-log.txt)
[retroarch.cfg.txt](https://github.com/libretro/RetroArch/files/3097910/retroarch.cfg.txt)

**Comment by hizzlekizzle** [comment]
works fine here. In fact, this line suggests that you're running windowed all the time:
`video_windowed_fullscreen = "true"`
Try setting that to false and see if it treats you any better.

**Comment by Sonickyle27** [comment]
I thought the windowed fullscreen setting made no difference with vulkan? I'll try it anyway when I'm am my latop again tomorrow.

Is there anything else that could suggest why SNES cores specifically are causing this issue for me and not any of the other cores? I don't have any overrides set up for any SNES games that affect video settings.

**Comment by Sonickyle27** [comment]
@hizzlekizzle I tried changing it to false but it has made no difference.

**Comment by hizzlekizzle** [comment]
Ok, can you temporarily move your retroarch.cfg to another location and let it create a fresh one for you? If the problem persists, it's probably not fixable within RetroArch. My guess would be something external monkeying with vsync. A driver utility, perhaps?

**Comment by Sonickyle27** [comment]
I just tried that and the issue went away. After some mucking around with the video driver setting in RetroArch, it appears that the issue only happens with vulkan. With gl which is the default, the issue does not happen. d3d9, d3d10, d3d11 and d3d12 don't show this issue either.

Regarding if anything external could be affecting it, I can't think of anything that I have installed that could interfere with it... I've attached a dxdiag with my hardware details if that helps.

[DxDiag.txt](https://github.com/libretro/RetroArch/files/3100656/DxDiag.txt)

**Comment by hizzlekizzle** [comment]
This person had the same symptoms and said it was an issue with having 'sync to exact content framerate' enabled:
https://www.reddit.com/r/RetroArch/comments/an91ym/when_using_the_vulkan_driver_at_fullscreen_the/
You don't have that enabled, by chance, do you?

**Comment by Sonickyle27** [comment]
Oh yeah, that's a lot smoother now after turning that setting off. Thanks! Looks like I'm going to have to set up a core override for that then.

I find it odd though that it only happens with SNES cores though... Perhaps there's something with the refresh rate of SNES games that is conflicting with the vulkan driver or something idk. Would it be worth filing a separate issue reporting this?

**Comment by hizzlekizzle** [comment]
Most consoles have a refresh rate <60 Hz, while SNES' refresh rate is just slightly above 60 Hz. If your monitor is capped at 60 Hz, it won't be able to keep up.

However, that option is only intended for use with variable refresh-rate (VRR) monitors (i.e.g, g-sync/freesync). If you're using regular fixed refresh rates, that option will prevent RetroArch from using its normal syncing processes.

**Comment by Sonickyle27** [comment]
My monitor built into my laptop is a FreeSync monitor at 40Hz-60Hz.

**Comment by hizzlekizzle** [comment]
Ok, yeah, a core override to disable the 'sync to exact content framerate' is a good solution in that case. Shall we close this issue?

**Comment by Sonickyle27** [comment]
Yeah I'll close it. I feel that this issue w
