### ISSUE TITLE
[WiiU] Control Config lf support please

### ISSUE THREAD

**Issue by Vikijaka** [libretro/RetroArch#8605]
Hi there,

i am using RetroArch on my Wii U and i want to ask how do i need to config the controlsettings, which allow me to control the menu with WiiU Gamepad, but the Game itself with an other Controller like WiiMote or the Classic one.

Background to this: I want to control the menu, core change for example, while my Family is allowed to play Core specific Games.

Thank you for your attention

If this is the wrong place to ask something like this, please give me a hint where i should ask this

**Comment by orbea** [comment]
Try the forum, discord or even irc.
