### ISSUE TITLE
mGBA core doesn't save in Duel Masters - Kaijudo Showdown

### ISSUE THREAD

**Issue by torben656** [libretro/RetroArch#8615]
The VBA-M core saves the game, but the mGBA core doesn't. Tested on nightly and stable.

**Comment by orbea** [comment]
Does it work with the standalone mgba? This sounds like a core issue, please make an issue for the mgba repo.

**Comment by torben656** [comment]
It works on the standalone mGBA.

**Comment by RobLoach** [comment]
What platform? How to reproduce? You seem to have removed the issue template that asked these questions.

**Comment by orbea** [comment]
> It works on the standalone mGBA.

If its broken with the libretro core and works with standalone I think this is the correct issue tracker.

https://github.com/libretro/mgba/issues

I see the repo doesn't appear to be currently up to date, could it be fixed if it was updated?

@endrift Might know more about this specific issue?
