### ISSUE TITLE
MAME Core No Run-Ahead Support

### ISSUE THREAD

**Issue by MarkMSX** [libretro/RetroArch#8620]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Currently the MAME core of retroarch has no run-ahead support, unlike FBA and many other cores. This issue is relevant because the MAME core is laggy compared to original hardware (about two extra frames). This is also the only core that is able to play certain releases (such as the later CAVE shmups) and having run ahead support would help make these games much more playable and accessible. 

### Expected behavior

That Run-ahead will function in the MAME core similar to the FBA core. 

### Actual behavior

Run-ahead is not currently supported.

### Steps to reproduce the bug

If you try and activate run ahead or create a save state in a game like Mushihimesama, RetroArch will crash. 

### Bisect Results

I believe this has been an issue since Run-ahead was introduced. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.7.6]

### Environment information

- OS: Windows 10 and Windows 7

**Comment by grant2258** [comment]
this is core issue not a RA issue
