### ISSUE TITLE
Retroarch crashing soon after game launch

### ISSUE THREAD

**Issue by TheFlyingDonut** [libretro/RetroArch#8627]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

When I try to play any dreamcast game with the reicast core, the dreamcast logo/bios runs fine and the game itself launches thereafter, however the touch screen controls become unresponsive a few seconds after the game launches and it eventually throws up the 'Retroarch is not responding' error. 

The log file is as follows:

https://pastebin.com/9ZzfCnj2

### Expected behavior

[What you expected to happen]

For Retroarch not to crash. 

### Actual behavior

Retroarch crashes.

[What is actually happening]

### Steps to reproduce the bug

1. Launch game
2. Wait for crash

### Version/Commit

I have tried various versions of retroarch, tried it from the playstore, gave the nightlys a go, tried both the standard and 64 bit versions, same thing keeps happening. 

### Environment information

- OS: Android Pie and Android Oreo (error occurred on both a phone and tablet respecrively).

**Comment by orbea** [comment]
Is this only with reicast?

**Comment by TheFlyingDonut** [comment]
Hi,

I've only tried one other rom (snes) and that seems to work ok, I've picked out the errors from the log file:

04-21 22:58:46.358 E/com.retroarch(13581): Not starting debugger since process cannot load the jdwp agent.

04-21 22:58:47.070 E/WindowManager(3866): win=Window{f220882 u0 Splash Screen com.retroarch EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5365 com.android.server.wm.WindowStateAnimator.onAnimationFinished:319 com.android.server.wm.WindowState.onAnimationFinished:5787 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 com.android.server.wm.SurfaceAnimator.lambda$getFinishedCallback$0:92 

04-21 22:58:47.254 E/WindowManager(3866): win=Window{db5122 u0 Splash Screen com.retroarch EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5365 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2403 com.android.server.wm.-$$Lambda$yVRF8YoeNdTa8GR1wDStVsHu8xM.run:2 

04-21 22:58:51.194 E/BufferQueueProducer(3376): [com.retroarch/com.retroarch.browser.retroactivity.RetroActivityFuture[13581]#0] disconnect: not connected (req=1)

**Comment by fr500** [comment]
That's not including the actual crash

**Comment by TheFlyingDonut** [comment]
Hmm that's strange, out of the whole log file those were the only errors...

**Comment by orbea** [comment]
If other cores work then this sounds like a reicast issue, it would probably be better to make an issue here instead.

https://github.com/libretro/reicast-emulator/issues

**Comment by TheFlyingDonut** [comment]
Alright will do many thanks!
