### ISSUE TITLE
Bug with history/playlist setting aggregate vs per core

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8633]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
(I think) Purely aesthetic bug with the subtext choice under history/playlist settings

[Description of the bug]
The default setting is "per core" yet when you click to expand/alter it shows aggregate as being checked, meanwhile the text outside the menu indicates its on per core.  If you select "aggregate" then the checkbox disappears however the text then indicates its on aggregate.   If you change back to per core, behavior repeats.  Text says Per core, however checkbox displays on aggregate.
Seems to be a bug with the checkmark properly displaying on the proper selected option.

### Expected behavior
The external text regarding current selection option to match the checkmark internally when selecting said option.

### Steps to reproduce the bug

1. Settings > Playlist > Playlist sublabel runtime
2. note "Per Core" as being indicated
3. after expanding tree (so to speak) note that it displays aggregate as being selected

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
build date apr 24 2019

- RetroArch: [version/commit]
1.7.6 a60844897f

- OS: [The operating system you're running]
windows 10 pro

**Comment by jdgleaver** [comment]
Hmm... From a quick glance at the code, this seems to be caused by commit f3a31ffd8d6822fe9fe9ecf7651b0ccba642f8fa.

I would have a go at fixing this, but I won't have access to a computer until Monday...

**Comment by twinaphex** [comment]
Hi there,

hopefully this fixes the issues -

https://github.com/libretro/RetroArch/commit/1c2cbe596cbd0f5c897b14aef816b625a99534b6

Sorry for inadvertently causing this regression.

**Comment by twinaphex** [comment]
Is this fixed now for you?

**Comment by klepp0906** [comment]
will update now and take a look

**Comment by klepp0906** [comment]
Yep, looks good!  Thank you.  Will close up shop :)
