### ISSUE TITLE
[feature request] new time layout/option

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8634]
Apologies if this is the wrong place.  Several medium's for this and ive found feature requests in all of them.

I noticed in the past several formats for the time in the upper right corner have been added.  However my preferred (and i imagine most americans preferred) has seemingly been missed.

We have an option for month/date/time  but its month/date/military time(24hr) time.

I'd like month/date/12hr time (Hour/Minutes)

I imagine this would be a relatively easy addition, however I also imagine you guys have a "to-do" list that wraps around the block.

Just wanted to get this out there.

Thank you for all your hard work and time!

**Comment by gouchi** [comment]
- [Code pointer](https://github.com/libretro/RetroArch/pull/7332/files)

**Comment by klepp0906** [comment]
hi gouchi, excuse the ignorance >.<  

are those the lines i'd need to add locally to add this?  Or is that for a developer when he or she gets around to it?  

or neither? :p  

in sake of keeping posts to a minimum (operating under the assumption its the former) would updating RA through something like Stellar require me to re-add it every time?

Thanks!

**Comment by gouchi** [comment]
It is an example to show how date time settings were added.

**Comment by klepp0906** [comment]
gotcha, thank you :)

**Comment by gouchi** [comment]
@klepp0906 It seems there is an [option](https://github.com/libretro/RetroArch/blob/master/menu/menu_driver.c#L420-#L439) to have 12hours time (HH:MM:SS).

**Comment by gouchi** [comment]
@klepp0906 It seems there already is an [option](https://github.com/libretro/RetroArch/blob/master/menu/menu_driver.c#L420-#L439) to have 12hours time (HH:MM:SS).

**Comment by klepp0906** [comment]
Yes, correct.  

I’m looking to have it preceded by the date in the United States format as well. (Month before day)

There’s an option for day before month and 24hr but no option for month before day and 12hr as best I c an tell. 

Identical to the one retro arch ships with, but in the United States format, if that makes sense?
