### ISSUE TITLE
Shaders not working on iOS

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [libretro/RetroArch#8636]
Commit b347b26d61ac6144e72d120896042f4ae06f4421 breaks shaders on iOS 11 & 12...

Reverted this commit by hand and now shaders work fine again !

Sadly, this commit is definitely a regression...

**Comment by orbea** [comment]
How are shaders broken for you?

**Comment by WeedyWeedSmoker** [comment]
The shaders option just doesn't appear in the app menu since this commit, and appear fine after removing it

**Comment by orbea** [comment]
@twinaphex Can you please look at this?

**Comment by twinaphex** [comment]
Sure, I can take a look.

**Comment by twinaphex** [comment]
@WeedyWeedSmoker 

See if this fixes it -

https://github.com/libretro/RetroArch/commit/1f53eea4ee980cc26a8cef385944521ab2052e82

**Comment by WeedyWeedSmoker** [comment]
Wow, that was quick !

It fixes it beautifully, @twinaphex, thanks !

_BTW, as an unrelated note, the "Release" configuration for the iOS 10 and iOS 11 pbxproj doesn't include "../../deps/rcheevos/include", which makes it fail at compilation time... The iOS 10 and iOS 11 static seem to be missing way more files..._

**Comment by orbea** [comment]
It might be worth adding iOS to travis to catch these problems. I think it should be possible, but as I don't know much about the iOS build process it might be better if someone who used that platform helped there. :)

Could you make a new issue for this at least?

**Comment by WeedyWeedSmoker** [comment]
@orbea Ok ! I'll close this issue then...

**Comment by twinaphex** [comment]
@orbea Good idea about adding iOS targets for Travis.
