### ISSUE TITLE
[Switch] “failed to write retroarch/retroarch.cfg” error

### ISSUE THREAD

**Issue by cucholix** [libretro/RetroArch#8652]
Using latest nightly as April 28, RA crashes when trying to restart RA, this is the stack dump:
![F487D3CB-4BDF-4EA6-86BE-8593485A3514](https://user-images.githubusercontent.com/16081693/56872397-8ffb6780-69f6-11e9-97b7-8514b0992efa.jpeg)

Alternatively generating a fresh install will fail to create retroarch.cfg, and resetting will kick you back to HBL.

It’s not possible to create a new Configuration File through “Save New Configuration”, same error message appears “failed to write”

When quitting RA the system doesn’t crash, but still doesn’t save any changes, I have it set to save changes at exit.

**Comment by fr500** [comment]
seems there have been a few changes to config_file and I/O stuff in libretro common

**Comment by cucholix** [comment]
It’s fixed in the april 29 build
