### ISSUE TITLE
[Feature Request] PAL/NTSC refresh rate switching for KMS video context

### ISSUE THREAD

**Issue by escalade** [libretro/RetroArch#8663]
Cores like uae or vice run best in 50Hz or gamespeed will be wrong, as most content is PAL.

On my XU4 I can use modetest to switch into a PAL mode like so:

`# modetest -M exynos -s 42:720x576-50@XR24`

Unfortunately, this is simply a test program and won't allow me to permanently set the mode.

https://github.com/grate-driver/libdrm/blob/master/tests/modetest/modetest.c

Being able to set a complete mode isn't necessary, just a 50Hz/60Hz switch would be nice. If someone could set up a bounty, I'd be more than willing to chip in.

**Comment by zoltanvb** [comment]
This one could actually be closed, refresh rate switching should work with KMS since #15301 . The issue in #16613 is valid, and I am looking into it, but only occurs when RA was started earlier in a windowed state (i.e. not in KMS), which is rare.

**Comment by gouchi** [comment]
@escalade Please close this issue.

Thank you.
