### ISSUE TITLE
[Switch]Pro Controller/joycons doesnt work anymore

### ISSUE THREAD

**Issue by 2g4y1** [libretro/RetroArch#8665]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

nintendo pro controller doesn´t work anymore afte click select core.

### Expected behavior

I cant eplained what happend. I pressed select core in the main menu and then my controller doesnt work anymore inside retroarch.

### Actual behavior

I cant eplained what happend. I pressed select core in the main menu and then my controller doesnt work anymore inside retroarch. Only homebuton works. can go back to switch title menu, but cant do anything inside retroarch.

### Steps to reproduce the bug

1. not sure if reproduceable. Switched tumbnails from boxart to tilte screen or something similar.
2. set boxart on left side to boxart.
3. switched retroarch theme to clgui(?), restarted retroarch. changed theme back to ozone restarted retroarch
3. selected "select core"
4. controller doesnt work anymore, controller is first controller on switch and works on switch

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
Retroarch 1.7.6 on atmosphere 0.8.9 on switch 6.2.0

added my config so you have more details about it
[retroarch.zip](https://github.com/libretro/RetroArch/files/3132909/retroarch.zip)

edit: joycons doesnt work too

**Comment by m4xw** [comment]
You disabled the input driver `input_driver = "null"`

**Comment by twinaphex** [comment]
@m4xw requested me to close the issue, so I will.

**Comment by m4xw** [comment]
@2g4y1 If it wasn't clear, you can just delete that line from your cfg and it should work again!

**Comment by 2g4y1** [comment]
thanks @m4xw 
it works again
