### ISSUE TITLE
[Feature Request] Navigation sound added to mixer/toggle

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8675]
Back with another mundane request.  

we have toggles for every sound available for the RA menu EXCEPT navigation sounds.   Proooobably because we dont have navigation sounds :)

What those might be?  You guys are the professionals :P  Simply add the same clicks as the confirm/back clicks, or a unique sound similar to steam navigation or shield tv or ... pick your poison.

Some kind of sound effect for navigation with included toggle would be nice to round out that side of things.   Actually "feels" like its missing and should be there :P

**Comment by sonninnos** [comment]
This can be closed, because: https://github.com/libretro/RetroArch/pull/14770

**Comment by zoltanvb** [comment]
^^^
