### ISSUE TITLE
[SWITCH/OZONE] Thumbnails not displaying until loading a core

### ISSUE THREAD

**Issue by andiandi13** [libretro/RetroArch#8679]
Tested on retroarch 1.7.6 - Nintendo Switch.

When I'm on Ozone menu driver, I have to launch a core to have the sliding panel with covers.

**Comment by andiandi13** [comment]
@orbea EDIT : Its when I load a core that thumbnails appears, not a game.

**Comment by andiandi13** [comment]
Fixed on 1.7.7 !

**Comment by m4xw** [comment]
Sounds like u never updated the /switch loader when it was implemented.

**Comment by andiandi13** [comment]
@m4xw Sorry, what's the Switch loader ?

Actually I downloaded RA 1.7.6 on Switch and updated all cores, assets etc... from the homebrew

**Comment by m4xw** [comment]
I don't think 1.7.6 had that feature (only on nightly).
The "loader" is the nro in "/switch" that you use via the hbmenu to start RA
We have a extra download for that (its also in every bundle), but can't be updated via the core updater or content downloader yet

**Comment by andiandi13** [comment]
Oh so you mean I can update the nro from the last nightlt without waiting the update ?

Is there a link ?

**Comment by m4xw** [comment]
https://buildbot.libretro.com/nightly/nintendo/switch/libnx/RetroArch_loader_update.zip
^That is always the loader of the last nightly bundle

**Comment by andiandi13** [comment]
Great ! Thank you
