### ISSUE TITLE
Scanner FBA generate same titles

### ISSUE THREAD

**Issue by ezar** [libretro/RetroArch#8683]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Scanner FBA generate same titles.

### Expected behavior
Generates correct titles.

### Actual behavior
Duplicate same game title. 
Attach a sample... this label:  "800 Fathoms", is repeated more than 100 times...
>     {
>       "path": "/media/RETROARCH/roms/fba/3wondersha.zip",
>       "label": "800 Fathoms",
>       "core_path": "DETECT",
>       "core_name": "DETECT",
>       "crc32": "94945F99|crc",
>       "db_name": "FB Alpha - Arcade Games.lpl"
>     },
>     {
>       "path": "/media/RETROARCH/roms/fba/3wonders.zip",
>       "label": "800 Fathoms",
>       "core_path": "DETECT",
>       "core_name": "DETECT",
>       "crc32": "94945F99|crc",
>       "db_name": "FB Alpha - Arcade Games.lpl"
>     },
>     {
>       "path": "/media/RETROARCH/roms/fba/3in1semi.zip",
>       "label": "800 Fathoms",
>       "core_path": "DETECT",
>       "core_name": "DETECT",
>       "crc32": "94945F99|crc",
>       "db_name": "FB Alpha - Arcade Games.lpl"
>     },
>     {
>       "path": "/media/RETROARCH/roms/fba/zaxxon.zip",
>       "label": "800 Fathoms",
>       "core_path": "DETECT",
>       "core_name": "DETECT",
>       "crc32": "94945F99|crc",
>       "db_name": "FB Alpha - Arcade Games.lpl"
>     },

### Version/Commit
- RetroArch: 1.7.6

### Environment information
- OS: RPI 3b

**Comment by i30817** [comment]
Should have been fixed by https://github.com/libretro/RetroArch/pull/8333

Are you using the latest buildbot version?

**Comment by ezar** [comment]
Works using latest version, 1.7.7.
Regards
