### ISSUE TITLE
CRT Switchres has broken in the last few commits

### ISSUE THREAD

**Issue by atylmo** [libretro/RetroArch#8684]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

It seems like CRT Switchres has stopped switching resolutions as of the commits from maybe about a week ago. My pull request fork has this problem, and I thought it was me, but I just cloned the newest code in a separate directory and it still happens.

### Expected behavior
Mode switching occurs with the monitor changing into the resolution of the core, such as to 240p.

### Actual behavior

When you try to switch modes, the resolution doesn't change, but the aspect ratio and refresh rate do.

### Steps to reproduce the bug

1. Turn on CRT SwitchRes under video options (using a CRT monitor).
2. Change the resolution
3. Observe that the monitor doesn't update correctly. It is reporting a new refresh rate, and the menu gets squashed, but the resolution does not change.

### Version/Commit
You can find this information under Information/System Information

- The version that works is e61c331.
- The version that doesn't is 64918ca.

### Environment information

- OS: Ubuntu 19.04
- Compiler:GCC 8.3.0

**Comment by atylmo** [comment]
Well, huh. The version I have installed with the unstable PPA (e61c331) works, but if I checkout the same revision manually it doesn't work. I tried a `git bisect`t but none of them worked.

**Comment by twinaphex** [comment]
@alphanu1 Can you comment and see if this is true? We are on the cusp of releasing 1.7.7 so we'd rather there is no big regression in this department if we can help it.

**Comment by atylmo** [comment]
Never mind. Apparently I deleted the build dependencies the other day. I remember doing that (accidentally) but I forgot I did  :upside_down_face:. I didn't catch it because it still usually compiled.  Then I got an error about `xrandr` trying to build the 1.7.6 release, which I knew should have compiled, so I checked the dependencies.

A quick `apt-get build-dep retroarch` fixed it right up.
