### ISSUE TITLE
OSX PowerPC build can't download anything

### ISSUE THREAD

**Issue by requeijaum** [libretro/RetroArch#8697]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Since there are no core files (and related) in libretro's buildbot nighly folders: [the official v1.7.5 build](http://buildbot.libretro.com/stable/1.7.5/apple/osx/ppc/) can't download anything. I can try building the cores, though - but seems unpractical for users that have a PPC Mac.

### Expected behavior

Core updater working.

### Actual behavior

Core updater can't download it's index nor any related files.

### Steps to reproduce the bug

Simple as 123.

### Bisect Results

...

### Version/Commit
You can find this information under Information/System Information

- RetroArch: v1.7.5

### Environment information

- OS: Mac OS X Leopard - 10.5.8

**Comment by bparker06** [comment]
The core updater is not supported for OSX PPC builds.

**Comment by twinaphex** [comment]
We don't know of an easy way to build cores for PowerPC on modern macOS, and we don't have the luxury of an OSX PowerPC CPU being added to our buildbot farm.

If you know of any solutions there, by all means share them - we'd be happy to add OSX PPC cores to the buildbot, if we could find a way to do it.

**Comment by requeijaum** [comment]
How does the buildbot works? Since modern macOS deprecated Mac OS X Leopard Xcode and Frameworks... it's pretty dead. You will need a dedicated PPC Mac just for running this job... or a virtualized one (slow unoptimized resource hog).

I'm fetching libretro-super to get my hands on building some cores.

**Comment by requeijaum** [comment]
Oops. A quick Google search revealed that modern QEMU can virtualize a G4 PPC running 10.5 Leopard. I still have my Xcode copy for Leopard... do you guys think that is worth testing out?

I'm in the middle of my custom core builds... still running libretro-super/libretro-fetch.sh.

**Comment by bparker06** [comment]
I think it would be painfully unusably slow. I tried OS9 on the latest qemu-ppc and it takes forever just to boot (see http://bot.libretro.com/.bp/os9.mp4)

**Comment by twinaphex** [comment]
Wontfix for now. Too much effort for now and our buildbot is already slow enough as is and continually running out of space. We can revisit this at a later time and date when we have most issues under control.
