### ISSUE TITLE
Enter key on keypad/number-pad maps incorrectly.

### ISSUE THREAD

**Issue by Europia79** [libretro/RetroArch#8701]
## Description
The `Enter` key on the keypad maps to the `Enter` key on the keyboard, NOT the number-pad.  Is there a possible manual override for this in any of the configuration files ?  Like maybe `num_enter` or whatever RetroArch calls this particular key ?

### Expected behavior
I expect that a key that I press on the keyboard during configuration gets mapped to that key correctly, not some other key:  In this case, I try to map the `Start` button to the `Enter` key on the numeric keypad, but it doesn't:  It maps to the `Enter` key on the keyboard.

### Actual behavior
The `Enter` key on the keypad maps to the `Enter` key on the keyboard.

### Steps to reproduce the bug
1. Configure input.
2. When asked for the `Start` button, press `Enter` on the keypad.
3. Tested on several cores.

### Version/Commit
- Git version:  `826c77d523`
- Build date:  `Oct 2 2018`
- Compiler:  `MinGW (7.3.0) 64-bit`

### Environment information
- OS:  `Windows 7 x64 Build 7601 Service Pack 1 (v6.1) Professional`

**Comment by bparker06** [comment]
Can't reproduce, please try with the latest nightly version, the issue was likely fixed since the version you're using (which isn't even the latest stable).

**Comment by Europia79** [comment]
Fixed in Git version `9750719074` with build date `Feb 3 2019`
