### ISSUE TITLE
[QT] Add thumbnails for special playlists (history, favourites...)

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#8702]
Thumbnails support was added into XMB (and other menu drivers?) for history and favourites in the following PR:
https://github.com/libretro/RetroArch/pull/8467
https://github.com/libretro/RetroArch/pull/8678

It would be great to have something like this in QT.

**Comment by Tatsuya79** [comment]
@bparker06 or @CozmoP if you're bored at some point...

**Comment by Tatsuya79** [comment]
I think the parts that need some changes to write the database name into the history playlists are there:
https://github.com/libretro/RetroArch/blob/81ab6d575a773941a77661a759d37030f7bbd216/ui/drivers/qt/ui_qt_window.cpp#L1854
and
https://github.com/libretro/RetroArch/blob/81ab6d575a773941a77661a759d37030f7bbd216/tasks/task_content.c#L2060

@jdgleaver can you be bothered with this if it's easy enough? :persevere:

**Comment by jdgleaver** [comment]
@Tatsuya79 Sure, why not  :)

I'll add it to the end of my 'immediate' TODO list:

1. Add option to hide navigation bar in glui
2. Fix vertical line ticker speed
3. Add option to filter content by DAT file in manual content scan
4. PUAE save state + logging improvements
5. Qt thumbnail fix

...I estimate that I'll get around to number 5 in about a weeks' time

**Comment by Tatsuya79** [comment]
Awesome. :+1: 

I spent so much time on that. I did a hack job at the thumbnail path level but that's really bad in many aspects.
