### ISSUE TITLE
[1.7.7-SWITCH] Retroarch crashes when opening video settings

### ISSUE THREAD

**Issue by andiandi13** [libretro/RetroArch#8711]
Since the last update, as soon as I enter Settings>Video, the app closes (nsp or nro).

Is there because I merged my old RA folder from 1.7.6 with the folder of 1.7.7 ?

Is there because of the new OpenGL thing ?

**Comment by twinaphex** [comment]
This will be fixed in the ninja-fixed version 2 of v1.7.7.
