### ISSUE TITLE
Neo Geo CD FBA Core. CD-DA Audio Explodes

### ISSUE THREAD

**Issue by Panderner** [libretro/RetroArch#8713]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[The Neo Geo CD. CD-DA Audio Explodes]

### Expected behavior

[When I play Neo Geo CD Game on FBA. the CD-DA Sound Explodes]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [Pick FBA]
2. [Load Neo Geo CD Game]
3. [Press any Button to Load Menu And Press Any Number in Number key]

### Bisect Results

[The CD-DA Audio Explodes when I play number in number key and in-game]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.7.7]

### Environment information

- OS: [Android 5.1.1]
- Compiler: [Stable Build]

**Comment by fr500** [comment]
How is this a RetroArch issue?

[image: image.png]

**Comment by hizzlekizzle** [comment]
Yes, this should go to the FBA repo, but I think there is already an issue open for it.
