### ISSUE TITLE
New notifications don't honor on/off switch.

### ISSUE THREAD

**Issue by Firehawke** [libretro/RetroArch#8714]
## Description

The new notifications system in 1.7.6 doesn't seem to honor the on/off switch for onscreen notifications. Turning it off does not affect the notifications at all; they still appear.

### Environment information

- OS: Windows 10, OpenGL renderer

[2019-05-06 23-52-02.zip](https://github.com/libretro/RetroArch/files/3151169/2019-05-06.23-52-02.zip)

Enclosed is a recording (via OBS) demonstrating the issue.

**Comment by hizzlekizzle** [comment]
There's a new setting that controls the new notifications: settings > user interface > menu widgets. Disabling them should fall back to the old notifications.

**Comment by orbea** [comment]
@natinusala I am not sure this is an issue, but maybe some of these notification settings could be more general so that both menu widgets and the old OSD could benefit from them? Issue https://github.com/libretro/RetroArch/issues/8721 is kind of related.
