### ISSUE TITLE
RetroArch fails to start with glcore and gcc9

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#8716]
## Description

I recently upgraded from `gcc-8.3.0` to `gcc-9.1.0` and now RetroArch fails on an assert when starting with the glcore video driver.

I have confirmed that an old build with `gcc-8.3.0` works while builds with `gcc-9.1.0` using the same commit do not. I have also confirmed that builds using `clang-8.0.0` using the same commit do work. Disabling optimizations with `gcc9` does not help.

Edit: I also have experienced no issues with vulkan.

### Expected behavior

RetroArch should start and work with the `glcore` video driver when built with `gcc9`.

### Actual behavior

```
$ ./retroarch
retroarch: deps/SPIRV-Cross/spirv_glsl.cpp:265: const char* vector_swizzle(int, int): Assertion `swizzle[vecsize - 1][index]' failed.
Aborted
```

### Steps to reproduce the bug

1. Obtain `gcc-9.1.0` or maybe another `gcc9` release.
2. Build RetroArch with the new gcc.
3. Start RetroArch.

### Bisect Results

N/A (I'm reluctant to bisect gcc)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/ba3f164bdd06b4e00b4712e0d5c1aed5a5aac51e

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-9.1.0`

**Comment by orbea** [comment]
@Themaister Would you mind taking a look at this?

**Comment by orbea** [comment]
This may be relevant.

https://gcc.gnu.org/gcc-9/porting_to.html

I also wonder if updating `deps/SPIRV-Cross` in RetroArch could help, but it doesn't seem very straight forward.

This is their latest release.

https://github.com/KhronosGroup/SPIRV-Cross/releases/tag/2019-04-26

And for glslang.

https://github.com/KhronosGroup/glslang/releases/tag/7.11.3188

**Comment by orbea** [comment]
With help from @fr500 I was able to test the `SPIRV-Cross` master (https://github.com/KhronosGroup/SPIRV-Cross/commit/fce83b7e8b0f6599efd4481992b2eb30f69f21de) and found this issue still occurs.

This patch was used to compile RetroArch with newer `SPIRV-Cross`.
```
diff --git a/Makefile.common b/Makefile.common
index 91e5db5aba..d2b56ac5f5 100644
--- a/Makefile.common
+++ b/Makefile.common
@@ -1489,6 +1489,9 @@ ifeq ($(HAVE_SPIRV_CROSS), 1)
    OBJ += $(DEPS_DIR)/SPIRV-Cross/spirv_glsl.o
    OBJ += $(DEPS_DIR)/SPIRV-Cross/spirv_hlsl.o
    OBJ += $(DEPS_DIR)/SPIRV-Cross/spirv_msl.o
+   OBJ += $(DEPS_DIR)/SPIRV-Cross/spirv_parser.o
+   OBJ += $(DEPS_DIR)/SPIRV-Cross/spirv_cross_util.o
+   OBJ += $(DEPS_DIR)/SPIRV-Cross/spirv_cross_parsed_ir.o
 endif
 
 ifeq ($(WANT_WGL), 1)
diff --git a/gfx/drivers_shader/slang_process.cpp b/gfx/drivers_shader/slang_process.cpp
index a09485162c..4b1705a627 100644
--- a/gfx/drivers_shader/slang_process.cpp
+++ b/gfx/drivers_shader/slang_process.cpp
@@ -477,7 +477,7 @@ bool slang_process(
          }
 
          vs_code = vs->compile();
-         ps_code = ps->compile(ps_attrib_remap);
+         ps_code = ps->compile();
       }
       else
 #endif
diff --git a/gfx/drivers_shader/slang_reflection.cpp b/gfx/drivers_shader/slang_reflection.cpp
index 90022f6dc3..f5f0a67820 100644
--- a/gfx/drivers_shader/slang_reflection.cpp
+++ b/gfx/drivers_shader/slang_reflection.cpp
@@ -326,7 +326,7 @@ static bool add_active_buffer_ranges(
 {
    unsigned i;
    /* Get which uniforms are actually in use by this shader. */
-   std::vector<spirv_cross::BufferRange> ranges = 
+   spirv_cross::SmallVector<spirv_cross::BufferRange> ranges =
       compiler.get_active_buffer_ranges(resource.id);
 
    for (i = 0; i < ranges.size(); i++)
```

**Comment by escalade** [comment]
Same issue here.

**Comment by twinaphex** [comment]
It's a GCC 9.1 compiler bug, not a SPIRV Cross or RetroArch bug.

@Themaister is working on a workaround. After that, we can rebase. I'm also talking to him to make sure some of our other patches get pushed to the repo so that we don't have to continually rebase (some changes are needed for Griffin builds and some other portability changes).

**Comment by orbea** [comment]
This appears fixed in the master.
