### ISSUE TITLE
Version 1.7.7 - video_font_enable doesn't work anymore

### ISSUE THREAD

**Issue by lrusso** [libretro/RetroArch#8723]
In the version 1.7.7, the value video_font_enable doesn't work anymore no matter what you set in the cfg file. This didn't happened in 1.7.6. Im using the emscripten version.

**Comment by orbea** [comment]
I'm closing this as a duplicate of issue https://github.com/libretro/RetroArch/issues/8714.

These settings are currently only for the old OSD and not the new menu widgets.
