### ISSUE TITLE
OSX not saving shader preset

### ISSUE THREAD

**Issue by lazycommentator** [libretro/RetroArch#8728]
## Description

Selecting any slang shader preset works as expected for the duration of a game session. However closing and restarting a core resets the shader choice, despite attempts to save the preset for either the game, the directory or the core. 

Tested whilst running bsnes and Mesen cores.

### Expected behavior

I expect the choice of shader to persist after saving the preset choice and closing a game, or closing Retroarch.

### Actual behavior

No shader preset choice is saved. 

### Steps to reproduce the bug

1. Start any ROM
2. Once started, open the in-game Retroarch quick menu and select the 'shaders' option.
3. Pick any slang shader and apply
4. Save shader choice 
5. Close and restart ROM or retroarch. Shader choice has been lost.

### Bisect Results

1.7.5 - shaders work as expected.
1.7.6 - shaders crash Retroarch
1.7.7 - shaders work, but do not save.

### Version/Commit

- RetroArch: 1.7.7 (build date: May 6 2019)

### Environment information

- OS: macOS Mojave 10.14
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
Would you be able to bisect this issue at all? It would help to see when and where this started.

**Comment by lazycommentator** [comment]
I apologise, I am new to Git and I'm not sure where to begin identifying the point where this failed. This is also complicated by the fact that for the previous full release, 1.7.6; shaders didn't work at all. I assume this was to do with the transition from opengl.

**Comment by LazyBumHorse** [comment]
Can you test if this is still happening in a recent [nightly version](https://buildbot.libretro.com/nightly/apple/osx/)?

Because this sounds like something that should be fixed by #8910 and #9001, although I'm not quite sure why exactly this would fail before, so maybe there's something else going on.
