### ISSUE TITLE
Crash after Switch fullscreen

### ISSUE THREAD

**Issue by andercard0** [libretro/RetroArch#8737]
Retroarch closing after switch between fullscreen and windowed

### Description

I've noticed that yesterday while I was scannning games. My retroarch was in fullscreen mode then when try to back windowed it simply closes, only happens while scanning games. 

I expected retroarch not closing right in front of my face. 

### Steps to reproduce the bug

1. Go to Import content
2. It starts to scan the folder
3. Then press F to return into windowed mode, it closes
4. Only happens while scanning or importing things to the playlist (games)

I've noticed that yesterday with new version 1.7.7

- OS: Linux, not tested on Windows.

**Comment by bparker06** [comment]
Not able to reproduce with your instructions on the latest code. The menu widget notification about scanning goes away when switching to windowed mode, but RA does not close (no idea if it's still really scanning or not).

**Comment by natinusala** [comment]
Does it happen with this code? https://github.com/libretro/RetroArch/pull/8732

**Comment by bparker06** [comment]
The scanner notification seems to stay in place with that PR.

**Comment by natinusala** [comment]
Yup, that's what that fixed, but does it still crash for @andercard0 ?

**Comment by andercard0** [comment]
Do you guys need more details about it, just le me know.. crash happened twice while I was trying to import FB Alpha stuff, more or less 5.663 roms...on Ubuntu 18.04.2 LTS, I dont even know if this is relevant or not but there it is. 

Is there any log I could send you ?

**Comment by andercard0** [comment]
[Update] Just tested on windows and the issue happens too. In this case, instead of  scanning some games, I was scraping PSx cover games: Online Updater > Thumbnails updater > choosed Psx thumbs, pressed F to go back in Windowed mode.. it hangs then crash.
