### ISSUE TITLE
Incorrect language at first installation

### ISSUE THREAD

**Issue by andercard0** [libretro/RetroArch#8741]
## Description

Retroarch in a clean install, starts in Italian

When I made a clean install it starts in Italian. My native language is Brazilian Portuguese, my prefered language is English my Operational System is in Portuguese. In my case Windows 10.

### Expected behavior

Open in English as it was use to be or even (in this new version) at least respect my standard native windows language which is Portuguese.

### Actual behavior

Retroarch booting in Italian

### Steps to reproduce the bug

1. At retroarch download page choose Windows platform, as well as this version: Download (64bit) of the download

2. After it finish, unzip it on my prefered path folder, then execute for the very first time the program.

3. After it boots and recognizes my controllers the whole thing is in Italian

### Bisect Results

Only happens in this new version 1.7.7

### Version/Commit
V.1.7.7

### Environment information

- OS: Miscrosoft Windows 10

**Comment by andercard0** [comment]
Update: A friend told me that his RA opens first time in French; So, it's not happen only with me and I'm not crazy :D

As a work around I provide him my RA configs in order to save his time with this stupid bug!

**Comment by altiereslima** [comment]
Comigo abre em Italiano também, achei até estranho.

**Comment by bparker06** [comment]
Can you paste the output of `Get-Culture` from a PowerShell prompt here? It should look similar to this:

![img](https://i.imgur.com/PyrhzSV.png)

**Comment by altiereslima** [comment]
![image](https://user-images.githubusercontent.com/18044879/57871997-15e22580-77e1-11e9-96d3-32c5e81c52c2.png)

**Comment by bparker06** [comment]
Thanks, should be fixed in 37e2cb4ecc.
