### ISSUE TITLE
Overlay notification customization's are not applying whatsoever

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8746]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Attempt to change position or color of overlay or its background does nothing. 

### Expected behavior

changing the color, or background color to do so.  The x/y position also should shift the overlay into position but does not.   (also shouldnt these settings be seperated for the pop-up notifications relative to the static FPS/memory indicator, i noticed the size changes size for both, so i assume the color is going to as well?)

### Actual behavior

nothing? lol.  I did get the size to change after a restart of RA.  but no such luck with the others. 

### Steps to reproduce the bug

1. Navigate to onscreen display > onscreen notifications
2. choose your notification x or y position or your background color, or color (presume for font)
3. note that nothing changed(s)

### Bisect Results

cant say, I'm just now trying to address it as I cant see the notifications at all when playing on the tv :)  

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.77 89461bba08

### Environment information

- OS: Win10

**Comment by hizzlekizzle** [comment]
customization of the new menu widget notifications isn't implemented yet.

**Comment by klepp0906** [comment]
ok, i was beginning to figure as much.   thanks for the confirm/heads up.  can know not to fret about it for the time being anyhow :)  (im as ocd as they come)

**Comment by orbea** [comment]
I'm going to close this in favor of issue https://github.com/libretro/RetroArch/issues/8721 which was made first. :)
