### ISSUE TITLE
MAME core giving 0 refresh rate with CRT Switchres

### ISSUE THREAD

**Issue by atylmo** [libretro/RetroArch#8753]
I know there's a separate section for core-specific bugs but I'm not sure if this is specific to MAME or not. I don't know if MAME isn't sending the right resolution or if RetroArch isn't picking it up.

## Description
When you run a MAME game that's not 240p (say, Virtua Racing at 496x384), the refresh rate reported by `xrandr` is 0. Because of that, it fails to switch to the right resolution and reports `Configure crtc 0 failed`. It happens on LCDs as well as CRTs.

### Expected behavior

The resolution and refresh rate should switch.

### Actual behavior

It tries to switch refresh rates, and the notification pop-up says it did, but it's actually showing (what I believe to be) the last resolution used, which for me is usually 240p.

### Steps to reproduce the bug

1. Load the MAME core.
2. Turn on CRT Switchres and set it to Native (although I think other settings produce the same result).
3. Load a game that's a higher resolution than 240p, like Virtua Racing or Daytona USA.
4. When it loads, tab out of it, open a terminal and type `xrandr`. You should see that one of the resolutions added by Switchres is listed, but with a 0 refresh rate.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7 / 1a3f16ded1

### Environment information

- OS: Ubuntu 19.04
- Compiler: GCC 8.3.0

Here's an example of `xrandr --verbose` showing the non-working modeline:
```
CRT2_496x384_115.05 (0x236)  0.000MHz -HSync -VSync Interlace
        h: width   496 start  523 end  557 total  656 skew    0 clock   0.00KHz
        v: height  384 start  176 end  182 total    0           clock   0.00Hz

```

**Comment by orbea** [comment]
Does it work with other cores? If yes then I think you want this issue tracker.

https://github.com/libretro/mame/issues

**Comment by atylmo** [comment]
It does. It works in MAME if I delete the modeline created by RA and make the same one (with the same name) manually. Maybe there's some funky math somewhere.

It's very specifically _only_ 384 res. Higher is fine, lower is fine (I think...had some problems with vertical games getting squished).

I'll open an issue there, thanks :)
