### ISSUE TITLE
Rotation still not supported on 3DS.

### ISSUE THREAD

**Issue by vaguerant** [libretro/RetroArch#8754]
## Description

Note: Likely a dupe of #2838, but perhaps newly relevant thanks to 1.7.7.

RetroArch 1.7.7 includes the following new feature: 
> – LIBRETRO: Allow non-accelerated video to rotate the display.

However, the 3DS still does not rotate the image correctly.

### Expected behavior

Rotation should work as it does on other platforms, especially for platforms which rely heavily on rotation like arcade and WonderSwan.

### Actual behavior

When rotation is used on 3DS, the image does not rotate but does begin displaying incorrectly, seemingly with the aspect ratio as if the screen had been rotated but without the image actually changing.

### Steps to reproduce the bug

1. Open your preferred GUI on a 3DS
2. Enter Settings -> Video -> Video Rotation and switch from Normal to any other value.
3. Observe the image crunching but not rotating.

### Bisect Results

This feature has never worked on 3DS in my experience.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7 stable (hotfix version)

### Environment information

- OS: New 3DS firmware 11.9, Luma3DS 9.1 CFW

**Comment by jdgleaver** [comment]
Hmm... Interesting. I've never tried anything with a rotated screen, but from a quick look at the code I can see why this doesn't work. Fixing it would appear to be quite difficult, however.

I can't promise anything, but I'll add this to my TODO list (it's a nice feature). I have a couple of big projects to do first, however.
