### ISSUE TITLE
Wii: Menu corruption when changing resolution

### ISSUE THREAD

**Issue by Wiimpathy** [libretro/RetroArch#8759]
## Description

When the screen resolution is changed, rgui menu is crashing, all menu is corrupted. Only default 640*480 is working.

### Steps to reproduce the bug
In main menu, go to Settings->Video and change Screen Resolution.

### Bisect Results
No precise commit but 1.7.6 Wii Stable is working correctly.

Well, in fact in 1.7.6, random black screens when launching games in neogeo core. Maybe unrelated. It doesn't seem to happen anymore in the current version.

### Version/Commit
I've tested stable 1.7.7 and the nightly builds with the same results.

**Comment by orbea** [comment]
Bisecting this would help a lot, I know its easier said than done.

**Comment by twinaphex** [comment]
The resolution code should be reimplemented for Wii. If it's reimplemented the correct way, it could work like the Windows version, where we get a nice dropdown list that the user can choose a resolution from, instead of hackishly having to continue pressing left/right like before.

**Comment by Wiimpathy** [comment]
Ok, I've just tested. The menu is broken since this commit : b301e4d4443470ec9dc4a4838da5c8fb60a548a6

**Comment by twinaphex** [comment]
What do you mean by the menu being broken?

**Comment by Wiimpathy** [comment]
Here's a crappy screenshot:
![Rgui_crash](https://user-images.githubusercontent.com/39578591/58112749-6946e000-7bf4-11e9-9344-189d3ac5c214.png)

It happens when you change to any resolution different from 640x480. It doesn't seem related to the switchres feature after all.

**Comment by twinaphex** [comment]
Hi there @jdgleaver, this seems like a very serious issue that should be resolved as soon as possible.

**Comment by jdgleaver** [comment]
@Wiimpathy Sorry for breaking this! It's fixed by PR #8833.

(At least I now have a Wii for testing...)
