### ISSUE TITLE
[macOS] non-Metal builds crash when using Ozone driver (since 1.7.7)

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#8761]
## Description

non-Metal macOS builds of 1.7.7 crash when using Ozone driver

### Expected behavior

* should be able to run using Ozone

### Actual behavior

* Crashes on launch

https://gist.githubusercontent.com/gingerbeardman/925658ce10619f99ba37ff4f613a5f49/raw/e6bace7250cc489d7059ef11573a01f440967050/retroarch

### Steps to reproduce the bug

1. Download 1.7.7 stable macOS _RetroArch.dmg_ or _RetroArch_CG.dmg_ http://buildbot.libretro.com/stable/1.7.7/apple/osx/x86_64/
2. Switch to _Ozone_ menu driver 
3. Restart RetroArch

### Bisect Results

- stable 1.7.6 non-Metal builds run Ozone just fine

### Version/Commit

1.7.7 stable

### Environment information

- OS: macOS 10.13.6

**Comment by orbea** [comment]
Can you bisect this please?

**Comment by gingerbeardman** [comment]
I have edited my OP with bisect

**Comment by orbea** [comment]
There are many commits between 1.7.6 and 1.7.7, any chance this can be narrowed down more?

**Comment by gingerbeardman** [comment]
I'll try to narrow it down asap

**Comment by orbea** [comment]
Thank you! Hopefully that will help us know where and how this can be fixed.

**Comment by gingerbeardman** [comment]
I aim to download a few versions from the nightly folder. Is there a quicker/better way?

**Comment by gingerbeardman** [comment]
The oldest nightly, 2019-04-28_RetroArch.dmg, does not work with Ozone.

https://gist.githubusercontent.com/gingerbeardman/6cd61dda1e7f7728df8445a6da534854/raw/0a8a181bb3b9029bf4595f81106a96b266b62acf/2019-04-28_RetroArch

**Comment by orbea** [comment]
The quickest way is to use `git bisect`.

First you need an environment where you can build RetroArch and have git installed.

Here is some documentation to get you started, please ask if you need help understanding something.

https://git-scm.com/docs/git-bisect
http://webchick.net/node/99

**Comment by gingerbeardman** [comment]
Sadly I do not have the time to build my own RetroArch (just had a baby)

**Comment by orbea** [comment]
Understandable, hopefully someone else with the right hardware can help investigate. :)

**Comment by twinaphex** [comment]
This should fix that problem -

https://github.com/libretro/RetroArch/commit/d6fe0ce

**Comment by orbea** [comment]
@gingerbeardman Would you please confirm that the above commit helped fix this?

**Comment by gingerbeardman** [comment]
Confirmed working in latest nightly! Thanks @twinaphex
