### ISSUE TITLE
SSE2 path of conv_argb8888_bgr24 glitches output

### ISSUE THREAD

**Issue by BarryJRowe** [libretro/RetroArch#8764]
## Description
The SSE2 path of conv_argb8888_bgr24 causes horizontal based mismatches in the output.

### Expected behavior
It should produce the same output as the non-SSE2 path, which is the correct pixel conversion.

Example expected image: 
https://pasteboard.co/IefdtMv.png

### Actual behavior
The output looks to be glitched horizontally.

Example actual image:
https://pasteboard.co/IeeCT1c.png

### Steps to reproduce the bug

1. Load a core that uses X8888 pixel format (eg: 2048)
2. Take a *raw* screenshot (not viewport, that one is fine)
3. Alternatively, using OCR feature will also show the problem on X8888 cores.

### Bisect Results, Version/Commit
No changes have been made to this path since it was added in this commit:

https://github.com/libretro/RetroArch/commit/3b9ad729fb09e0a434b4b6610eff9b1a0bb1c539

### Environment information
- OS: Windows, Linux, both with SSE2

**Comment by BarryJRowe** [comment]
I went ahead and added a $20 bounty, since this converter will be used a lot for OCRing on X8888 cores.

Bounty source link: https://www.bountysource.com/issues/74021798-sse2-path-of-conv_argb8888_bgr24-glitches-output

**Comment by bparker06** [comment]
When did this start happening?

**Comment by bparker06** [comment]
How are you taking a raw screenshot?

**Comment by BarryJRowe** [comment]
@bparker06 I only noticed it while I was working on the OCR issue, but the code path it is in came from the commit listed in the issue and that code has not been modified since.  That commit added that path so the SSE2 code for that converter probably has never worked (though the non-SSE2 path is ok).

To reproduce with the raw_screenshot approach, comment out the video_driver_supports_viewport_read() check in the take_screenshot_choice() function of task_screenshot.c and take a screenshot on an 8888 core.  Make sure that __SSE2__ is defined in your build.  If you still can’t reproduce it, then I can message you on discord about the OCR way of reproducing it.

**Comment by bparker06** [comment]
Should be fixed now.
