### ISSUE TITLE
Graphical/Aesthetic bug with Save slot number relative to checkmark

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8773]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When selecting save slot within a core, the UI will show your save slot (example:0) but if you delve into the option, it will display the checkmark on a slot your not currently on (seems to be 2 down, in this case, selecting slot 0 will show a checkmark on 2, and selecting 2 will show 2 in the interface, but a checkmark on 4 etc)

### Expected behavior

the selected save slot shown numerically in the UI to correspond with the checkmark in the selection tree.

### Actual behavior

They show different slot numbers as being selected which while seems to be entirely aesthetic at this point, will undoubtedly cause confusion. 

### Steps to reproduce the bug

1. load content (in my case genesis plus gx in case (unlikely) its core specific)
2. choose a save state slot and note the display which numerically indicates the slot your using.
3. re enter the slot selection tree, and note that the check mark is on a different slot than selected

### Bisect Results

As usual, i unfortunately cant say.  I update almost nightly and run across things randomly :(

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.77 948c242922

### Environment information

- OS: Win10

**Comment by orbea** [comment]
I confirmed this, the drop-down menu's probably should default to the currently selected item.

**Comment by klepp0906** [comment]
also, if you go under recording > stream quality.  no text shows up for what quality you have selected NOR does any checkmark show up for what you have selected ;p

**Comment by klepp0906** [comment]
and same with the "recording threads" option.  It will show the correct check mark if you enter it, but no declaration of setting in the root of recording settings.

Seems some of the UI stuff is in bad shape! eeep!

**Comment by johanbcn** [comment]
I have tried to reproduce this on version 1.8.5 both on ozone and xmb UI drivers on linux, and seems to work fine. I think it may have been fixed already.

**Comment by klepp0906** [comment]
its possible, a lot of ui work has been done recently.  that or its limited to windows.

I'll save this in my inbox and take a look at my earliest convenience.   Since the quarantining my freetime has been hammered contrary to what one would think.   Two kids around the clock will be the death of me :P

**Comment by klepp0906** [comment]
just looked at real quick.  

While loading content and opening the save slot it does now show the checkmark on the currently used slot.

If you change the slot, it also does change within the UI and within the tree with the checkmark.

The problem now seems to be that the setting doesnt retain.

Ive changed the slot closed and reopened the content and it reset to 0.  If changed the slot, closed retroarch, re opened and it reset to 0.

seems that the fix may have broken the retention of the setting.   That or it never saved to begin with.

**Comment by johanbcn** [comment]
For me it retains the state, unless I play content with a content configuration override file. That might be the issue.

**Comment by klepp0906** [comment]
Ah. I do have a configuration override for content directory. It doesn’t indicate save slot anywhere though so it shouldn’t be changing over overwriting/overriding the choice made no? 

Would assume that’s saved in the core config or something as that’s not able to be accessed until content is loaded afaik

**Comment by johanbcn** [comment]
Yes, that's it; once a configuration override takes place, the savestate index (or any other configuration change) is not stored on closing the content or quitting RetroArch.

And it makes sense, because by default RetroArch has enabled an option to store configuration changes on exit, but that only applies to the default configuration. Once you start content that triggers a configuration override, that option is ignored and you are expected to save these configuration changes manually by using the configuration override options.

**Comment by klepp0906** [comment]
yea, that makes sense.  I guess the confusion comes from the fact that core options all change/save properly outside of requiring their own override.   I guess i would have imagined the save state slot to be lumped in with that.

its sketchy because if you change slots on the fly for whatever reason, and save to a different slot, the next time you play you could end up on a different slot and screw something up.

I dont know that i like it functioning in that way, but without being specifically untethered and saved independently, i understand why it does.

**Comment by klepp0906** [comment]
I imagine this should be closed now then.  Someone must have solved it inadvertently and not known, or just forgot to chime in.
