### ISSUE TITLE
Feature Request - Search functionality in "console" UI

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8775]
Back yet again, with more requests cause im a bad person >.<

I have to assume this has been requested, yet im not seeing it.

The means to search playlists within RA (not in the desktop menu).  Scrolling down a playlist of 1000+ games is insane, coupled with no intros sometimes obnoxious naming conventions make finding some things without one terrible.

Also (while im here instead of opening another issue, i guess?) make the desktop toggle (f5 by default) work both ways?  Return from the desktop menu to the console menu would be ideal.

This way one could potentially bind a single toggle to switch back and forth if needed.   Unsure if the functionality is already present in some capacity (ala seperate binds?) still, the aforementioned would be superior regardless.

I'm fairly new to RA and diving in headfirst so i promise the influx of issues, bugs, and feature requests from me will slow down lol ;p

**Comment by orbea** [comment]
This is implemented and works here, on my ps3 gamepad its the `triangle` button while browsing a playlist.

**Comment by klepp0906** [comment]
huh, any idea what it would be on a keyboard?  Googling came across someone on reddit mentioning it used to be "S" but the feature was removed and no longer worked.

So i tried S and no bueno.  I guess if its actually in, will just have to find out what the hotkey is and bind it.

while I'm here, operating under the assumption i can find the bind and set it on my steam controller, I assume the text is able to be entered ala gamepad?  (aka theres a highlight on the on screen keyboard you can move with the dpad?)

**Comment by orbea** [comment]
I don't, I fear it may have not been hooked up to the keyboard yet...

**Comment by jdgleaver** [comment]
When using a keyboard, you can press `/` to start a search (this is identical to pressing RetroPad X on a gamepad - i.e. the top face button). The on-screen keyboard is of course usable with a gamepad :)

(Also, remember that L1/R1 can be used to jump by letters of the alphabet when scrolling through playlists)

**Comment by klepp0906** [comment]
excellent, thank you very much for the info.   Very good to know!  tested and of course correct :)

Any hope to get the F5 (show desktop menu) bind working as a toggle?  To go between desktop and fullscreen/console mode?

going one way, just to desktop mode isnt nearly as helpful ;p
