### ISSUE TITLE
Unable to Build RetroArch in Haiku

### ISSUE THREAD

**Issue by fpscan** [libretro/RetroArch#8777]
## Description

Unable to build in Haiku OS

### Expected behavior

Build Successfully

### Actual behavior

Build Failed

### Steps to reproduce the bug

1. Installed required Softwares
2. Fetched from Github 
`./configure --prefix=~/config/non-packaged/ --datarootdir=~/config/non-packaged/data/ --with-man_dir=~/config/non-packaged/documentation/man/ &amp;&amp; make
`
3. 
```
`/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/deps/discord-rpc/src/rpc_connection.o: in function `RpcConnection::Create(char const*)':
rpc_connection.cpp:(.text+0xd): undefined reference to `BaseConnection::Create()'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/deps/discord-rpc/src/rpc_connection.o: in function `RpcConnection::Close()':
rpc_connection.cpp:(.text+0x9d): undefined reference to `BaseConnection::Close()'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/deps/discord-rpc/src/rpc_connection.o: in function `RpcConnection::Destroy(RpcConnection*&)':
rpc_connection.cpp:(.text+0xc8): undefined reference to `BaseConnection::Destroy(BaseConnection*&)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/deps/discord-rpc/src/rpc_connection.o: in function `RpcConnection::Write(void const*, unsigned long)':
rpc_connection.cpp:(.text+0x11b): undefined reference to `BaseConnection::Write(void const*, unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/deps/discord-rpc/src/rpc_connection.o: in function `RpcConnection::Read(JsonDocument&) [clone .part.53]':
rpc_connection.cpp:(.text+0x172): undefined reference to `BaseConnection::Read(void*, unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: rpc_connection.cpp:(.text+0x227): undefined reference to `BaseConnection::Read(void*, unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: rpc_connection.cpp:(.text+0x305): undefined reference to `BaseConnection::Write(void const*, unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/deps/discord-rpc/src/rpc_connection.o: in function `RpcConnection::Open()':
rpc_connection.cpp:(.text+0xc87): undefined reference to `BaseConnection::Write(void const*, unsigned long)'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: rpc_connection.cpp:(.text+0xcb4): undefined reference to `BaseConnection::Open()'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/deps/discord-rpc/src/discord_rpc.o: in function `Discord_Initialize':
discord_rpc.cpp:(.text+0x93): undefined reference to `Discord_Register'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: discord_rpc.cpp:(.text+0x98): undefined reference to `GetProcessId()'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: discord_rpc.cpp:(.text+0x227): undefined reference to `Discord_RegisterSteamGame'
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/discord/discord.o: in function `discord_init':
discord.c:(.text+0xf44): undefined reference to `Discord_Register'
collect2: error: ld returned 1 exit status
Makefile:195: recipe for target 'retroarch' failed
make: *** [retroarch] Error 1`
```

- RetroArch: 1.7.7

### Environment information

- OS: Haiku nightly
- Compiler: GCC

**Comment by orbea** [comment]
Try with `--disable-discord` as a configure argument.

**Comment by fpscan** [comment]
> Try with `--disable-discord` as a configure argument. Also I edited your comment to make it easier to read the build log, I hope you don't mind.

Hi, no worries at all, its my mistake that I didn't make it that way in first place. Actually I worked with that already but I thought this bug and let you know

**Comment by bparker06** [comment]
@kwyxz Shouldn't we just disable Discord integration on Haiku? Since there's no standalone app there anyway.

**Comment by kwyxz** [comment]
It's disabled in the haikuports package, I can look into disabling it directly in the configure script but it implies patching upstream.

**Comment by bparker06** [comment]
If you need help with the configure scripts @orbea can probably help you out there.

**Comment by kwyxz** [comment]
OP, you can also install RA 1.7.7 directly through the package system since this was merged a few hours ago https://github.com/haikuports/haikuports/pull/3850

**Comment by kwyxz** [comment]
@bparker06 thanks, I'll look into it asap.

**Comment by fpscan** [comment]
> @fpscan you can also install RA 1.7.7 directly through the package system since this was merged a few hours ago [haikuports/haikuports#3850](https://github.com/haikuports/haikuports/pull/3850)

Actually, I was making "tutorial for Haiku" then I realized this, added quick fix but if its going to remove in script near future I can remove this part from my video.
![image](https://user-images.githubusercontent.com/4651944/57656337-c503de80-75e0-11e9-9bbb-7226c8b511be.png)

Also you may realize that already but https://docs.libretro.com/development/retroarch/compilation/haiku/#building-retroarch if you check the end of the column you see `... &amp;&amp; make` instead `.. && make` so its just typo but I didn't know where to report it.

**Comment by bparker06** [comment]
Docs issues should be reported [here](https://github.com/libretro/docs/issues).

**Comment by fpscan** [comment]
> Docs issues should be reported [here](https://github.com/libretro/docs/issues).

I did, thank you.

**Comment by orbea** [comment]
@kwyxz and @bparker06 I made a PR to handle issues like this.

https://github.com/libretro/RetroArch/pull/8781

Please test it if you can, thanks!
