### ISSUE TITLE
Twitch streaming broken in current build

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8782]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Twitch streaming is non functional.  As a bonus issue, selecting "stream quality" in the recording options displays no checkmark, nor text indicator regarding which setting if any your currently using.  (probably not related to twitch not streaming, considering youtube does irrespective of that)

### Expected behavior

Twitch streaming to function via the same mechanism as youtube streaming.

### Actual behavior

Selecting "youtube" displays your youtube streaming key in the retroarch.cfg as well as in the UI - and as such, streams to youtube properly.   Selecting Twitch as your destination in the RA UI, still shows your youtube key in the RA UI and does not stream to twitch.   Any attempt to enter your twitch_stream_key = "" in the retroarch.cfg alongisde the youtube_stream_key entry, results in the entry being removed automatically from the cfg upon reload. 

### Steps to reproduce the bug

1. enter your twitch stream key - either in streaming url or in the cfg file.
2. ensure your UI is set to stream to twitch in recordings options.
3. start content and via the quick menu, select start streaming.
4. note it will "start" streaming as the button becomes "stop" after the fact - but nothing streams whereas youtube does properly.

### Bisect Results

no idea, just now getting around to setting this up. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.77 ea6f818784

### Environment information

- OS: Win10

**Comment by twinaphex** [comment]
@fr500 Any ideas?

**Comment by klepp0906** [comment]
ok, so i have it working.   its just a mess at the moment.  It doesnt store your twitch server url nor your streaming key like it does for youtube.

so  A) if we can get it functioning the same way as the youtube option, where you can switch between them without having to go fetch your server url and key that'd be great.   It writes the youtube key to the retroarch.cfg at the bottom.  The url (i dont know that youtube offers more than one?) but its automatically entered when you select Youtube as your stream.

Twitch requires selecting twitch.  Finding a server url (they have several to choose) and adding that + your stream key to the video stream url line.   You go back to youtube, its all lost - go fetch it all and re enter it all again.

Seems like the twitch side of it just got completely busted as far as saving and entering goes, or wasnt finished relative to the youtube side.

Also as i mentioned earlier i believe
1) Recording > Stream Quality shows nothing.  no idea whats selected.  text nor checkmark.

2) Recording > Recording Threads shows nothing. no idea whats selected unless you enter the option, you can see the checkmark at least.

3) Recording > Title of Stream  this also doesnt save (unsure if its supposed to) 

and finally, an issue of my own, while im here since Im curious and the discord hasnt been the most helpful.  "Use GPU Recording" I'm trying to get this set up in an attempt to capture the shaders as well, thing is - even without any shaders selected at all, it lags something fierce.  Like unplayable.   Im hoping someone can help me understand what is causing it and/or why so i can address it.   

as always, thank you guys.  tremendously.

**Comment by fr500** [comment]
Fixed:
https://git.retromods.org/radius/RetroArch/commit/4222a0be19b679d00f5e2dec076302c390b399af

**Comment by twinaphex** [comment]
The Recording -> Stream Quality issue should be fixed with this commit -

https://github.com/libretro/RetroArch/commit/9b31c91165fae4514c31141f32b085a6e53db48e

**Comment by gouchi** [comment]
> Tried to add facebook live too but it didn't work.

Just for [information](https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/) RTMP is deprecated, RTMPS is needed now for the Live API.

**Comment by klepp0906** [comment]
> > Tried to add facebook live too but it didn't work.
> 
> Just for [information](https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/) RTMP is deprecated, RTMPS is needed now for the Live API.

aww facebook live woulda been cool :) thanks for trying though.  Thought never crossed my mind.



> Fixed:
> https://git.retromods.org/radius/RetroArch/commit/4222a0be19b679d00f5e2dec076302c390b399af
> 
> Tried to add facebook live too but it didn't work.
> About the comment here: right/left on streaming quality works fine.
> 
> The "drop downs" set incorrect values for some reason, that's something only @twinaphex knows how it works.

Thank you very much.  I assume it will function in much the same way that the youtube option does now?  Automatically enter the url upon switching and save your key to the cfg file? 



> The Recording -> Stream Quality issue should be fixed with this commit -
> 
> [9b31c91](https://github.com/libretro/RetroArch/commit/9b31c91165fae4514c31141f32b085a6e53db48e)

aaaaand thank you too lol.  Did you also address the Recording threads display issue?  

Eager to give it a run once its all pushed.  I just updated now but evidently not there just yet.  Appreciate you guys buttoning it up.  I'm sure you all take pride in your work - and personally, im ocd as hell about things being bugged or broken lol.  To a fault as im sure you can see by my near endless issue reports :p

**Comment by fr500** [comment]
@gouchi yeah that's the issue, ffmpeg doesn't like rtmps ( or at least the build we use for windows)

**Comment by klepp0906** [comment]
yep, you guys nailed it.  seems buttoned up <3  Thank you very much for that.

**Comment by Johnsterkai** [comment]
Does anyone know how to walk a newbie through fixing this?

**Comment by klepp0906** [comment]
you just go to the twitch client/dashboard and get your streaming url/key and add  that under Recording>Streaming URL and off you go more or less.

Been a long while since I set it up, but after the team fixed it, thats all it took.
