### ISSUE TITLE
[Feature request] Show core information when using the online updater

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#8785]
The idea would be to show the informations about the core prior to downloading it, maybe by using info files, or maybe something fancier with some screenshot, nice description, changelog, whatever, kinda like how an online store would display stuff before buying/downloading it. 

What's REALLY important for me would be to show the license, at least the type, on this screen, it would solve some unrest about license information from the emulator not being shown explicitly when downloading a core through the online updater.

**Comment by orbea** [comment]
I agree, besides the license would you mind elaborating on what information you would expect? I can make sure the buildbot provides the information, but I am not sure about hooking it up to the online updater.

**Comment by barbudreadmon** [comment]
Best case scenario, being able to display something similar to this in the online updater would be amazing : https://i3.itch.io/stonebond . But simply having license information would already be great.

**Comment by Tatsuya79** [comment]
I think r5 is working on that (on discord, not sure how to notify him here).

**Comment by i30817** [comment]
The only thing i want here is a update all.

**Comment by twinaphex** [comment]
It should now show licenses if it can find license information inside a corresponding core info file.

https://github.com/libretro/RetroArch/commit/0fedbe837c2ef427cf72e6e9aba178a47cf194c8
