### ISSUE TITLE
Default keybinds for lightgun are missing

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#8790]
## Description

The zapper is broken in RetroArch as experienced in cores like `fceumm` and `nestopia` and the game `Duck Hunt`. Basically RetroArch does not register any clicks from the mouse and the zapper never fires. This affects all input drivers and other cores and games are possibly affected.

Also see this related core issue: https://github.com/libretro/nestopia/issues/49

And these issues may be related? 

https://github.com/libretro/RetroArch/issues/8324
https://github.com/libretro/RetroArch/issues/7697

### Expected behavior

Mouse clicks should be registered by the zapper.

### Actual behavior

RetroArch does not register any mouse clicks when using the zapper.

### Steps to reproduce the bug

1. Start `nestopia` and the game `Duck Hunt` with a mouse connected.
2. Observe that the mouse can control the crosshair, but mouse clicks do nothing and the zapper is rendered unplayable.

### Bisect Results

This broke in PR https://github.com/libretro/RetroArch/pull/5847.
```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
cbfdd7bbd95456958baca345cc198b2664108977
3dc35344983421ef8b6cc190a493a41373c41869
6f116b2edfc841643f42b136c320fca8dde62476
4e79ef9f61eb872d96a8d67d03478df14037baba
c453675d386606871a32fb04af7b1ea3822ebc93
c76545bf6ce87e3b131cf0e406655b1918b5c9de
We cannot bisect more!
```
https://github.com/libretro/RetroArch/commit/cbfdd7bbd95456958baca345cc198b2664108977
https://github.com/libretro/RetroArch/commit/3dc35344983421ef8b6cc190a493a41373c41869
https://github.com/libretro/RetroArch/commit/6f116b2edfc841643f42b136c320fca8dde62476
https://github.com/libretro/RetroArch/commit/4e79ef9f61eb872d96a8d67d03478df14037baba
https://github.com/libretro/RetroArch/commit/c453675d386606871a32fb04af7b1ea3822ebc93
https://github.com/libretro/RetroArch/commit/c76545bf6ce87e3b131cf0e406655b1918b5c9de

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/3df7e616ca1d28b375333cde567f9d785a76a9ca

### Environment information

- OS: `Slackware64-current`
- Compiler: `clang-8.0.0`

**Comment by orbea** [comment]
@hiddenasbestos Can you please take a look at this issue?

**Comment by orbea** [comment]
This affects snes9x too, the super scope works in standalone nestopia and standalone bsnes.

**Comment by orbea** [comment]
It broke in another commit for the `x` input driver.
```
7dfcc169de9016eb3db440c20351963c43c83071 is the first bad commit
commit 7dfcc169de9016eb3db440c20351963c43c83071
Author: David Walters <contact@davidwaltersdevelopment.com>
Date:   Wed Nov 29 18:32:58 2017 +0000

    Add new lighgun/mouse-bind features to X11 driver

:040000 040000 5b7bba6b67b0e28207e3f1266e2c1ea5f9ecc9f1 3e85dc82a7a1877686a23385cf1842b2c6739a21 M	input
```

**Comment by orbea** [comment]
Okay I see the problem now, before these were hardcoded and now they are not. However no one actually gave these sane defaults and expected the users to bind them by default.

RetroArch really should have default bindings which match the previous hardcoded bindings.

**Comment by OctopusButtons** [comment]
https://github.com/libretro/RetroArch/issues/10168

I assume that’s related, because in Mac OS X Retroarch there’s no mouse activity whatsoever in-game regardless of core or settings (at least all the many settings I could find and which I read about in the documentation).  The mouse/trackpad works fine in the user interface and the binds to Mouse 1 and Mouse 2 appear to work in the user interface, but no mouse button or input or movement works in-game.

**Comment by markwkidd** [comment]
Is this the same issue? https://github.com/libretro/RetroArch/issues/7904

**Comment by orbea** [comment]
Closing as a duplicate of #7904.
