### ISSUE TITLE
[Android][Vulkan] Changing screen orientation doesn't refresh layout

### ISSUE THREAD

**Issue by SuperSamus** [libretro/RetroArch#8806]
## Description
(My device is a Xiaomi Mi A2, an Android One device, running 9.0 Pie. Didn't test on any other device)
Rotating the device while Retroarch is open will switch the app from portrait to landscape or viceversa, but the layout won't change, leading to a terribly stretched interface and messed up button hitboxes. To force a layout refresh you have to leave the app (no need to close it) and returning to it while staying on the new orientation.
This happens everywhere in the app. Screenshots here: https://photos.app.goo.gl/DyjUgxXD7NNnUkK7A

### Expected behavior
Retroarch would refresh the layout when rotating the device, just like OpenGL would do.

### Actual behavior
Rotating the device doesn't change the layout, the interface becomes horribly stretched with messed up hitboxes.
Returning to the "original" orientation (the one you started/refreshed the app with) will make everything normal (example: you start portrait, you rotate to landscape and the interface messes up, you return to portait again and the interface returns back to normal).

### Steps to reproduce the bug
1. Go to Settings>Drivers>Video and select Vulkan.
2. Close the app from the main menu to save the settings and open it again.
3. While the app is open, rotate the device (auto-rotation must be active on Android settings)

### Bisect Results
Bug present on both Retroarch 1.7.5 and 1.7.7. Never used Retroarch before 1.7.5 nor on any other device, so I always had this bug.

### Version/Commit
- RetroArch: Retroarch 1.7.7 stable (Play Store) AArch64, commit 3853d89
- Compiler: Clang/LLVM 3.8.256229 (64 bit)

### Environment information
- OS: Android 9.0 Pie, Xiaomi Mi A2

**Comment by RaduNastase** [comment]
I have the exact same issue with Vulkan renderer.

**Comment by shlomi-toren-sp** [comment]
Likewise, but It doesn't matter what backend you use. I think this is an RA bug.

**Comment by RaduNastase** [comment]
The only fix is to start Retroarch with the intended orientation.

**Comment by shlomi-toren-sp** [comment]
@RaduNastase actually, there is another way that works for me: just switch to a different app (or the home menu) when you're in the wanted orientation, then go back to RA.

**Comment by SuperSamus** [comment]
RetroArch 1.8.2 fixed the issue.
Closing.
