### ISSUE TITLE
[Windows x64] Latest code crashing immediately when selecting 'Load Core' from Main Menu

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#8812]
## Description

With the latest code on Windows x64, RetroArch is crashing whenever selecting the "Load Core" option from the Main Menu. I am experiencing this crash with all menu drivers.

The following error message appears through Dr.Mingw:
_retroarch.exe caused an Unknown [0xC0000374] Exception at location 00007FFC59F4843B in module ntdll.dll._

### Bisect Results

I have taken the time to do a bisect and 269a95b0bff9e352be55c98e6b0825353c9659db appears to be the first bad commit.

### Version/Commit

- RetroArch: 1.7.7 / d0707437c90155aa16f8eae20aaa019a09c0e178

### Environment information

- OS: Windows 10 x64
- Compiler: mingw64

**Comment by twinaphex** [comment]
I can't reproduce this.

**Comment by Ryunam** [comment]
f6f9d8e9d43324a147bf8ecbdd3d58737c44669d fixes this. Thanks again, @twinaphex.
