### ISSUE TITLE
Shader's "Save Content Directory Presets" fails if the shaders directory is not writable

### ISSUE THREAD

**Issue by johanbcn** [libretro/RetroArch#8814]
## Description
On ArchLinux, the "Save Content Directory Preset" option found on the shader section of the quick menu doesn't work with the default configuration options.

### Expected behavior

To be able to use the "Save Content Directory Preset" option on ArchLinux :)

### Actual behavior

It fails with the message "Error saving shader preset".

### Steps to reproduce the bug

1. Install the retroarch package
2. Install the libretro-shaders-slang package
3. Start retroarch and load any game
4. Load a shader preset from the quick menu
5. Choose the "Save Content Directory Preset" option

### Bisect Results

Enabling the logs and using the "Save Content Directory Preset" option outputs this:
```
[INFO] Failed writing shader preset to /usr/share/libretro/shaders/presets/Gambatte/gb.slangp.
[ERROR] Failed to save shader preset. Make sure config directory and/or shader dir are writable.
```

Then I tried the "Save Shader Preset As" option, and the logs output this:
```
[INFO] Failed writing shader preset to /usr/share/libretro/shaders/foobar.slangp.
[INFO] Saved shader preset to /home/johanbcn/.config/retroarch/config/foobar.slangp.
```

So, "Save Shader Preset As" first tries to save the preset on the shader directory, and on failure falls back to the config directory.

Yet, "Save Content Directory Preset" just tries to save on the shader directory.

Using the same option from the "Overrides" section of the quick menu outputs this:
```
[INFO] [Overrides] looking for changed settings... 
[INFO]    original: video_fullscreen=1
[INFO]    override: video_fullscreen=0
[INFO] [Overrides] path /home/johanbcn/.config/retroarch/config/Gambatte/gb.cfg
[INFO] [config] [overrides] Overrides saved successfully.
```

So, in my opinion, I think that the "save content override" option for the shaders menu should mimic the "save shader preset as" option and fall back to the config directory; in my case: /home/johanbcn/.config/retroarch/config/Gambatter/gb.slangp

### Version/Commit

- RetroArch: 1.7.7/62da78ca3d

### Environment information

- OS: ArchLinux
- Compiler: N/A

**Comment by orbea** [comment]
This is a arch issue, there is nothing we can do here. Tell the package maintainer not install those files and let users get them from the online updater or manually by downloading the source. They need to be in user writable directories.

**Comment by johanbcn** [comment]
Yes, it's an issue on this use case, but I still feel it's kind of inconsistent that the "Save shader as" option uses the conf directory yet the core overrides uses the shader directory.

**Comment by orbea** [comment]
That sounds like a different issue and should have its own issue report.

**Comment by johanbcn** [comment]
Alright, I might have given too much unrelated information. I'll try to rephrase it more especifically on a new issue. Thanks!
