### ISSUE TITLE
(Video) RETRO_ENVIRONMENT_SET_ROTATION not working properly with glcore

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/RetroArch#8821]
## Description

On hardware accelerated core (reicast), setting "glcore" as video driver will result in an upside down display when compared to the "gl" video driver when calling RETRO_ENVIRONMENT_SET_ROTATION with a value of 3.

### Expected behavior

When launching a game like ikaruga on naomi (vertical game, reicast implements naomi per-game auto-rotation), the display should be the same whatever the video driver.

### Actual behavior

When launching ikaruga on naomi, the display won't be the same between "gl" and "glcore", the later reverse it.

### Additional information

Non hardware accelerated cores (ex. fbneo) don't seem to have this issue when using the same functionality. I think the important difference here is the direct usage of GL in the core.

**Comment by orbea** [comment]
What OS are you running?

**Comment by barbudreadmon** [comment]
Linux x64, nvidia proprietary drivers

**Comment by orbea** [comment]
Thanks. Can you spell out how to reproduce this issue? Is it only with reicast or are other cores affected too?

**Comment by barbudreadmon** [comment]
Not sure which cores use RETRO_ENVIRONMENT_SET_ROTATION for vertical arcade games apart from reicast and FBNeo, afaik MAME cores use software rotation. FBNeo is working properly unlike reicast, that's why i think the issue is related to hardware accelerated cores.

To reproduce the issue, set your video_driver to glcore, and start a vertical naomi game in reicast (ex. ikaruga).

**Comment by orbea** [comment]
Thanks for explaining, I suspect not many people have tried naomi games with glcore making this easy to miss.

**Comment by barbudreadmon** [comment]
Solved in https://github.com/libretro/RetroArch/commit/1cc307a87964614a2c182208f42b1dde524c7c14
A regression in desmume was fixed in https://github.com/libretro/RetroArch/commit/3b31dafa7e17657995fcda7b8d1c16ea83af371e
Closing
