### ISSUE TITLE
Content specific overrides/core overrides save blank.

### ISSUE THREAD

**Issue by libretroissuethrowaway** [libretro/RetroArch#8828]
## Description

Saving a content specific override only creates a blank file, no settings are added. This also applies to core overrides.

### Expected behavior

My current settings to be saved to one of these files.
### Actual behavior

A blank file is saved.
### Steps to reproduce the bug

1. Open any game or core.
2. Save a content or core override.
3. Check the file under config in your retroarch folder, see that its blank.
### Bisect Results

Ever since ver 1.7.7

### Version/Commit

- RetroArch: 1.7.7/52dd39f98a

### Environment information

- OS: Windows 10 Home

**Comment by fr500** [comment]
Overrides only save the changes from the main config. Not the whole thing.

**Comment by libretroissuethrowaway** [comment]
It doesn't even save that, they come 100% blank.

**Comment by fr500** [comment]
Works fine for me
just tried
```
custom_viewport_height = "882"
custom_viewport_width = "1041"
input_menu_toggle_gamepad_combo = "3"
video_hard_sync = "true"
video_scale = "4.000000"
video_scale_integer = "true"
```

**Comment by libretroissuethrowaway** [comment]
They just come out 100% blank for me, I have no idea whats wrong.

**Comment by libretroissuethrowaway** [comment]
Copying a old override then saving over it wipes the file as well.

**Comment by libretroissuethrowaway** [comment]
So after some testing, I backed up and removed all my old configs, I noticed some things, options like auto load overrides vanished, those being gone also applied to a new copy of retroarch.

**Comment by libretroissuethrowaway** [comment]
A reset of my config files has fixed the issue, no idea what was wrong with them.
