### ISSUE TITLE
[Android] Downloading Beetle PSX HW gives you PSX HW 0.9.44.1

### ISSUE THREAD

**Issue by shlomi-toren-sp** [libretro/RetroArch#8836]
## Description

When you go to update cores, and choose Beetle PSX HW, it downloads regularly.
Then, when you run the core, it's title is "PSX HW 0.9.44.1 5359198", same as the regular core.
Save states and such go to the same folders, and the configurations are the same, so I assume it's the same core.

### Steps to reproduce the bug

Just download the core on android x64.
I would assume it's an issue with the buildbot. The PC port downloads the regular version.

Thanks!

**Comment by orbea** [comment]
Wrong issue tracker, this one is more relevant.

https://github.com/libretro/beetle-psx-libretro/issues

**Comment by shlomi-toren-sp** [comment]
@orbea  I opened an issue there as well, I just wasn't certain who's responsible for maintaining the buildbot. If it's absolutely irrelevant, I can close this issue here.

**Comment by orbea** [comment]
Its easier a core issue or a buildbot issue, the buildbot repo is here.

https://github.com/libretro/libretro-super/issues

**Comment by shlomi-toren-sp** [comment]
@orbea  thank you, I'll open it there as well.

**Comment by orbea** [comment]
I'll link the related issues here.

https://github.com/libretro/libretro-super/issues/1050
https://github.com/libretro/beetle-psx-libretro/issues/507
