### ISSUE TITLE
[input] retro_keyboard_callback spawns thousands of release events

### ISSUE THREAD

**Issue by DSkywalk** [libretro/RetroArch#8838]
# retro_keyboard_callback spawns thousands of release events if RETRO_DEVICE_KEYBOARD is used
 _Tested on latest cap32 core using ra1.7.6_ [Windows/Linux/ARM]

## Description

In caprice we used RETRO_DEVICE_KEYBOARD for users could remap controls using computer-emulated keys. Ex: bind key [SHIFT] to [joystick_button_1]

If RETRO_DEVICE_KEYBOARD is used then thousands of remapped-release-events are spawned in the keyboard callback without pressing any button.

DEBUG LOG:
```
Down: no, Code: 49, Char: 0, Mod: 0.
Down: no, Code: 110, Char: 0, Mod: 0.
Down: no, Code: 304, Char: 0, Mod: 0.
Down: no, Code: 121, Char: 0, Mod: 0.
Down: no, Code: 49, Char: 0, Mod: 0.
Down: no, Code: 110, Char: 0, Mod: 0.
...
```

### Expected behavior

Only when you press a button, a key event spawns :+1: 
Like normal behaivor when use a real keyboard.

### Actual behavior

key events spawns since you change control to RETRO_DEVICE_AMSTRAD_KEYBOARD.
and generate problems like: https://github.com/libretro/libretro-cap32/issues/62

### Steps to reproduce the bug

My init code in cap32/retro_events.c:
```
   struct retro_keyboard_callback cb = { keyboard_cb };
   environ_cb(RETRO_ENVIRONMENT_SET_KEYBOARD_CALLBACK, &cb);
```

Debug code:
```
static void keyboard_cb(bool down, unsigned keycode, uint32_t character, uint16_t mod)
{

   printf( "Down: %s, Code: %d, Char: %u, Mod: %u.\n",
          down ? "yes" : "no", keycode, character, mod);
}
```
1. Controls/User 1/Amstrad Keyboard
![imagen](https://user-images.githubusercontent.com/560310/58266519-18fd8880-7d82-11e9-98d4-ac6805e88d46.png)

2. Remap some keys
![imagen](https://user-images.githubusercontent.com/560310/58266579-3af70b00-7d82-11e9-9a05-5ac2bd1f8945.png)

3. Back to caprice core and...

### Bisect Results

I need some help to bisec this, thanks.

### Version/Commit
I patched temporarily caprice:
https://github.com/libretro/libretro-cap32/commit/4e7a1a48b046a0a463a44d41fd584760381dcf58

But the problem is really anoying and I think we need to solve here.

### Environment information

- OS: WIN/LIN/RASP

**Comment by DSkywalk** [comment]
After some dissect I found that the problem is here: https://github.com/libretro/RetroArch/commit/c3f3ac3dc19086bf6b160879ffdf98ce1126fcaa#diff-4dd6e477da06a009ecb1c94f3eb145e8655b78879bc1a47d349183ca02092a2cR24585
_Near a part of the code that @sonninnos has recently been improving._ 

The problem is that the handler clears at the beginning of the loop and as long as the button is not pressed it will continue and generate the release event, when this is not actually happening. And it forces the cores to not trust the events that come to us from the callback.

Is it really necessary to clean the handler at the beginning of the loop? 
```
      memset(handle->keys, 0, sizeof(handle->keys)); 
```

Could we use another structure to handle the actual release event?

Sorry @twinaphex (or whoever is leading the input system). I would need to know if it is something intentional because it is giving me several problems in caprice32 core and if I can not trust the events that come to me from the callback then I could do the checks in the core. No problem :+1: 

Really thanks and Merry Christmas Team!! :star2:  :santa:

**Comment by twinaphex** [comment]
Hi there @DSkywalk , I will try seeing if @sonninnos would like to join this conversation and if he could potentially find a solution to this. Thanks.

**Comment by sonninnos** [comment]
Took a while to get both the useless spamming to stop **and** to be able to have the duplicate key mappings as targeted by the PR. Maybe it could/should be more elegant, as in without that static variable for duplicate flagging, but it seems to do what it is supposed to:

```diff
diff --git a/retroarch.c b/retroarch.c
index 3574c1a252..ff13c9582e 100644
--- a/retroarch.c
+++ b/retroarch.c
@@ -21750,8 +21750,6 @@ static void input_driver_poll(void)
       const input_device_driver_t *joypad_driver 
                                        = p_rarch->joypad;
 
-      memset(handle->keys, 0, sizeof(handle->keys));
-
       for (i = 0; i < max_users; i++)
       {
          input_bits_t current_inputs;
@@ -21832,12 +21830,12 @@ static void input_driver_poll(void)
             case RETRO_DEVICE_KEYBOARD:
                for (j = 0; j < RARCH_CUSTOM_BIND_LIST_END; j++)
                {
+                  static unsigned remap_key_used[RETROK_LAST] = {0};
                   unsigned current_button_value;
-                  unsigned remap_button            =
+                  unsigned remap_key               =
                      settings->uints.input_keymapper_ids[i][j];
                   bool remap_valid                 =
-                     remap_button != RETROK_UNKNOWN &&
-                     !MAPPER_GET_KEY(handle, remap_button);
+                     remap_key != RETROK_UNKNOWN;
 
                   if (!remap_valid)
                      continue;
@@ -21857,21 +21855,28 @@ static void input_driver_poll(void)
                            BIT256_GET(ol_state->buttons, j);
                   }
 #endif
+
                   if ((current_button_value == 1)
-                        && (j != remap_button))
+                        && !MAPPER_GET_KEY(handle, remap_key))
                   {
-                     MAPPER_SET_KEY (handle,
-                           remap_button);
+                     remap_key_used[remap_key] = j;
+                     MAPPER_SET_KEY(handle,
+                           remap_key);
                      input_keyboard_event(true,
-                           remap_button,
+                           remap_key,
+                           0, 0, RETRO_DEVICE_KEYBOARD);
+                  }
+                  else if ((current_button_value == 0)
+                        && MAPPER_GET_KEY(handle, remap_key)
+                        && remap_key_used[remap_key] == j)
+                  {
+                     remap_key_used[remap_key] = 0;
+                     MAPPER_UNSET_KEY(handle,
+                           remap_key);
+                     input_keyboard_event(false,
+                           remap_key,
                            0, 0, RETRO_DEVICE_KEYBOARD);
-                     continue;
                   }
-
-                  /* Release keyboard event*/
-                  input_keyboard_event(false,
-                        remap_button,
-                        0, 0, RETRO_DEVICE_KEYBOARD);
                }
                break;
 
diff --git a/retroarch_data.h b/retroarch_data.h
index d6bd295788..9bb52ad80a 100644
--- a/retroarch_data.h
+++ b/retroarch_data.h
@@ -274,6 +274,7 @@
 
 #define MAPPER_GET_KEY(state, key) (((state)->keys[(key) / 32] >> ((key) % 32)) & 1)
 #define MAPPER_SET_KEY(state, key) (state)->keys[(key) / 32] |= 1 << ((key) % 32)
+#define MAPPER_UNSET_KEY(state, key) (state)->keys[(key) / 32] &= ~1 << ((key) % 32)
 
 
 #ifdef HAVE_MENU
```

Any issues with this approach? I tried to keep it as simple as possible.

**Comment by DSkywalk** [comment]
@sonninnos now is working like a charm, really thanks! :grinning:

**Comment by sonninnos** [comment]
Excellent! I made a bit cleaner version without the static variable. I'll PR it soonish after some more testing.
