### ISSUE TITLE
RETRO_ENVIRONMENT_SET_MESSAGE no longer remove message

### ISSUE THREAD

**Issue by Zlika** [libretro/RetroArch#8850]
## Description

RETRO_ENVIRONMENT_SET_MESSAGE no longer removes message after the specified number of frames.

### Expected behavior

The message should disappear after the specified number of frames.

### Actual behavior

The message stays forever on the screen.

### Steps to reproduce the bug

Exemple of code:
```
struct retro_message msg;
msg.msg = "Test message";
msg.frames = 50;
environ_cb(RETRO_ENVIRONMENT_SET_MESSAGE, &msg);
```

### Bisect Results

```
c83b86b7c24f0d2f1e21f96d478f1341df426b4b is the first bad commit
commit c83b86b7c24f0d2f1e21f96d478f1341df426b4b
Author: natinusala <natinusala@gmail.com>
Date:   Sat May 11 17:24:00 2019 +0200

    menu_widgets: add libretro message widget, have RETRO_ENVIRONMENT_SET_MESSAGE use it

:100644 100644 210bbf28641b2b459e5f465a4fdb9642d8347f0d 77b45ee3336ae2aa1d93adb8d41044b424ab0ac2 M	dynamic.c
:040000 040000 6227c73b6265fef9d6d703a3f5481cac1ab2abaa c814219c3493664a86ac81bb74ab2751515f4f09 M	menu
```

### Environment information

- OS: GNU/Linux Debian 9
- Compiler: gcc 6.3.0

**Comment by bparker06** [comment]
Paging @natinusala

**Comment by natinusala** [comment]
How can I try to this, can you give me a core to reproduce this issue?

**Comment by Zlika** [comment]
I found this issue using my core theodore (Thomson MO/TO). Just start the core (without any content) and press X or Y. It is supposed to print the current key of the core's "virtual keyboard" for 1s, but now it stays forever.

**Comment by natinusala** [comment]
I will have a look at it tomorrow
