### ISSUE TITLE
WiiU RGUI broken

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#8852]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RGUI is completely broken on WiiU (black screen)

### Expected behavior

For it to work, it's the only driver that can look fine in both the gamepad and the TV at the same time

### Actual behavior

When you change to RGUI and reset you are greeted by a black screen, you can press UP->A to quit so it's not hanging, just not rendering

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7 20aff2a05aabfe1423b89682f44859e957080a77

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by orbea** [comment]
@jdgleaver Do you know the current status of this?

**Comment by fr500** [comment]
According to
https://gbatemp.net/threads/retroarch-wiiu-wip.447670/page-562#post-8662864
it should be fixed

**Comment by jdgleaver** [comment]
Yeah - QuarkTheAwesome fixed it with this: https://github.com/libretro/RetroArch/pull/8908

There are still some transparency issues to resolve, however.

(I don't have a WiiU, so can't test this myself!)

**Comment by orbea** [comment]
Thanks for the info! @QuarkTheAwesome Do you want to track the transparency issues here or should this issue be closed now?

**Comment by QuarkTheAwesome** [comment]
nah, I'll probably file a seperate issue for that. It doesn't quite deserve bug:major ;D

**Comment by orbea** [comment]
Good point, I'll close this one then, thanks for the fix!
