### ISSUE TITLE
Screenshots distorted

### ISSUE THREAD

**Issue by Bezier89** [libretro/RetroArch#8854]
## Description

When taking a screenshot (either using the "Take Screenshot" functionality directly or when creating a save state), the imagine is distorted. This reproduces with both the glcore and vulkan backends. It does NOT reproduce in Retroarch 1.7.6, only 1.7.7.

### Expected behavior

Screenshot should not be distorted.

### Actual behavior

See attached image: 
![Super Mario Bros  3 (USA) (Rev A) nes-190526-194636](https://user-images.githubusercontent.com/6324883/58388696-04262c80-7ff0-11e9-88ff-5677a91c6f8b.png)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7 (52dd39f98a)

### Environment information

- OS: Windows 10

**Comment by twinaphex** [comment]
Please tell us which cores you are using, it's important while determining what could be going on.

**Comment by Bezier89** [comment]
@twinaphex This is Nestopia UE. I just tried a couple other cores and they don't exhibit this issue.

**Comment by Bezier89** [comment]
@twinaphex Just confirmed this also happens with the Mesen core. However, it does not happen with the FCEUmm core. So something about the way Nestopia and Mesen handle screenshots does not play nicely with RetroArch 1.7.7.

**Comment by twinaphex** [comment]
@Bezier89 Probably because those cores use XRGB8888 as the color format instead of RGB565 like FCEUmm does.

**Comment by bparker06** [comment]
Have you tried with the regular `gl` core? Also please try the latest nightly if possible.

**Comment by Bezier89** [comment]
It does also happen with the `gl` driver, yes. Haven't tried the latest nightly yet but I will when I get a chance (probably later today).

**Comment by BarryJRowe** [comment]
There’s a good chance this is related to the glitched SSE2 path of one of the pixel converters.  It might have been fixed with: 

https://github.com/libretro/RetroArch/commit/a672cc13a94b74bd8c8b90f20f0e678283e44d01

It might already be fixed in the more recent nightly builds.

**Comment by Bezier89** [comment]
@BarryJRowe @bparker06 @twinaphex Yep, this works correctly in the latest nightly. Thanks for the help, will close out this issue.
