### ISSUE TITLE
[Switch] nightly is missing files since 2019-05-27

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#8867]
## Description

Switch nightly is missing files since 2019-05-27

### Expected behavior

nightly should contain everything required

### Actual behavior

nightly is missing files: 
- /retroarch/cores/*
- /switch/*

### Steps to reproduce the bug

1. compare size and contents of recent nightlies https://buildbot.libretro.com/nightly/nintendo/switch/libnx/

### Bisect Results

- 2019-05-26 = 180MB = all OK
- 2019-05-27 = 105MB = stuff missing 
- 2019-05-28 = 105MB = stuff missing
etc

**Comment by twinaphex** [comment]
The latest dated version, 2019-05-31, seems to be back at 180MB. So I assume it's all good now?

**Comment by gingerbeardman** [comment]
Let's assume so, I can't install the latest nightly any time soon. 

Thanks!
