### ISSUE TITLE
C compiler not found on Alpine Linux

### ISSUE THREAD

**Issue by oxr463** [libretro/RetroArch#8868]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

C compiler not found on Alpine Linux.

### Expected behavior

Expected configure to complete without any issues.

### Actual behavior

Configure complains about missing compiler and fails.

### Steps to reproduce the bug

1. Install gcc, `apk add gcc`
2. Run configure

```terminal
apk update && apk add \
      autoconf \
      gcc \
      gdb \
      git \
      libdrm-dev \
      libepoxy-dev \
      make \
      mesa-dev \
      strace

git clone https://github.com/libretro/retroarch.git && \
cd retroarch && ./configure && make && make install

Cloning into 'retroarch'...
Checking out files:  82% (6529/7940)   
Checking out files:  83% (6591/7940)   
Checking out files:  84% (6670/7940)   
Checking out files:  85% (6749/7940)   
Checking out files:  86% (6829/7940)   
Checking out files:  87% (6908/7940)   
Checking out files:  88% (6988/7940)   
Checking out files:  89% (7067/7940)   
Checking out files:  90% (7146/7940)   
Checking out files:  91% (7226/7940)   
Checking out files:  92% (7305/7940)   
Checking out files:  93% (7385/7940)   
Checking out files:  94% (7464/7940)   
Checking out files:  95% (7543/7940)   
Checking out files:  96% (7623/7940)   
Checking out files:  97% (7702/7940)   
Checking out files:  98% (7782/7940)   
Checking out files:  99% (7861/7940)   
Checking out files: 100% (7940/7940)   
Checking out files: 100% (7940/7940), done.
Checking operating system ... Linux 
Checking for suitable working C compiler ...  not found
Error: Cannot proceed without a working C compiler.
The command '/bin/sh -c git clone https://github.com/libretro/retroarch.git &&     cd retroarch && ./configure && make && make install' returned a non-zero code: 1
```

I can even manually set `CC=gcc`, and it still fails.

```terminal
CC=/usr/bin/gcc ./configure
Checking operating system ... Linux
Checking for suitable working C compiler ... /usr/bin/gcc does not work
Error: Cannot proceed without a working C compiler.
```

### Version/Commit
You can find this information under Information/System Information

- RetroArch: master

### Environment information

- OS: Alpine Linux 3.9
- Compiler: gcc version 8.3.0

**Comment by oxr463** [comment]
# Solution

```terminal
apk add g++
```

**Comment by orbea** [comment]
@oxr463 The first error can only happen if configure does not find `gcc`, `cc`, or `clang` in the `$PATH` meaning either `$PATH` is not set correctly or you do not have a compiler installed.

The second error means either `/usr/bin/gcc` does not exist or does not work. I would guess it also installed `gcc` when you installed `g++`. I would be surprised if alpine's `gcc` package did not work without `g++`.

**Comment by oxr463** [comment]
@orbea, thanks for the feedback!

The `$PATH` is fine, and `gcc` was already installed, (see the `apk add gcc ...` line above).

Also, Alpine's `gcc` works fine without `g++`; most programs I work on are c-only, (no c++), so I never install `g++`.

It wasn't until I poked around in [`qb/qb.comp.sh`](https://github.com/libretro/RetroArch/blob/master/qb/qb.comp.sh); then I realized the need for the c++ compiler.

**Comment by orbea** [comment]
If the `$PATH` was correct then you certainly did not have a compiler installed. You do not need a c++ compiler for building RetroArch and it will automatically disable the few c++ features if a c++ compiler is not found. For example try building RetroArch with `CXX=false ./configure`.

**Comment by oxr463** [comment]
I certainly did indeed have gcc installed. Feel free to run the provided commands yourself. Perhaps that information can be added to the documentation.

**Comment by orbea** [comment]
Its either a broken or missing C compiler, from your error you can see.
```
Checking for suitable working C compiler ...  not found
Error: Cannot proceed without a working C compiler.
```
The script will loop through `gcc`, `cc` and `clang` in that order and attempt to build a simple C file. This can only fail if there are no executable files found in the user's `$PATH` or if none of those compilers could successfully build the file (Broken compiler). I'm not very familiar with alpine, but it seems strange to me that installing `g++` would fix this if `gcc` was already installed unless `gcc` was automatically installed with `g++` or otherwise depends on `g++`.
