### ISSUE TITLE
Request: Adding xattr support for the scanner.

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#8873]
## Description

I'd like to add xattr (extended attributes) support to the scanner as a alternative to reading the crc from a zip file header, or calculating the crc (both in the scanner).

Then i could modify my tool rhdndat to add as switch:
```
  -s              in posix filesystems, store calculated user.rhdndat.md5, 
                  user.rhdndat.crc32, user.rhdndat.sha1 as extended attributes
                  if softpatching these values will refer to the 'patched' file
                  checksum not the file. Rhdndat doesn't use these as a 
                  replacement for re-calculating the checksums because patch
                  files could be deleted or changed outside of the tool, but
                  this option is still useful for applications reading them if
                  the user knows nothing changed 
```

Run it once on my collection to add the checksums to roms and never worry about the scanner being 'slow' again.

As a bonus, files which are patched at runtime (ie: softpatching) would have the 'correct' final hack checksum, because rhdndat is a tool to check patches and create libretro-database dat files and already does that work. Could you please add the option? I'm very willing to name the property `user.retroarch.crc32` or something - some subtilities about these names is that they have to start with `user.` because of linux namespaces and they probably shouldn't be named just `user.crc32` or `user.checksum.crc32` because part of the idea is to support softpatching so that would be false advertisement for other applications. I could also add a `user.retroarch.softpatch` flag to distinguish both cases if desired, but i can't think of a reason (except if a core doesn't support softpatching and you try to use the entry on it and you get the original game... but in that case, why softpatch?).

The catch: xattr is posix only. Just ignore it behind a ifndef in windows i guess.

**Comment by twinaphex** [comment]
Do you have experience with Extended Attributes on Windows?

https://stackoverflow.com/questions/46458355/windows-cli-equivalent-of-mac-xattr

Would you be able to code this as an additional codepath for Windows in the case we greenlight this? Also, I assume xattr would be available to Mac as well?

**Comment by i30817** [comment]
Xattributes are supported in mac, but i have near zero experience with coding. rhdndat is python and i was planning to use this pypy module: https://github.com/xattr/xattr

**Comment by i30817** [comment]
Also i forgot another advantage if you don't care about emulators changing 'roms' (which aren't 'roms') like floppy images. The xattr scan would present to 'original' checksum. I won't use it like this, because i have easy access to a copy-on-write filesystem though.

**Comment by twinaphex** [comment]
As for OSX, we only support OSX from 10.5 to the latest. So 10.4 cutoff point should serve us well for now, same with the Linux 2.6 kernel requirement.

**Comment by i30817** [comment]
I'm planning to encode the bytes on the properties stored in rhdndat on ascii, is that good for you to read? It seems the most compatible c string bytes encoding for checksums.

Anyway, you want the extended attributes to be named `user.retroarch.crc32` etc in order for this to be accepted so it can be documented on your manual? Or do you have a better suggestion for a more neutral name that doesn't give false expectations?

**Comment by i30817** [comment]
Ok i added the feature to rhdndat and 'optimistically said in the readme that retroarch 'supports the extended attributes' the option sets.

https://github.com/i30817/rhdndat

you can test it out by `pip3 install --user rhdndat` and then going to a rom dir (or parent of rom dirs) and using `rhdndatr rom_path rom_extension -x` and it'll set the sha1, crc32 and md5 on user.rom.sha1, user.rom.crc32 and user.rom.md5 respectively, including if the rom is to be softpatched.

**Comment by i30817** [comment]
While investigating how this could work again, i found something that sabotages the usefulness of the idea: hardlinks and extended attributes can't be used together. 

So i'm closing this issue, and i'll probably open a much simpler 'after playlist construction allow to use `"crc32"` as metadata key if it's not `"crc32": "00000000|crc"` to override the 'label' being used as metadata key.
