### ISSUE TITLE
[Menu] Remember vertical position on each playlist

### ISSUE THREAD

**Issue by skywind3000** [libretro/RetroArch#8874]
## Description

Can't emember the cursor position in ROM list (PSV).

I am using RetroArch 1.7.6 on my PSV and I got hundred roms for each emulator, every time I press `LEFT` / `RIGHT` to switch from one emulator from another, RetroArch lost the last visited cursor position in the ROM list and I have to navigate roms from very beginning.

And it is very hard to choose roms if you got hundred of them.

For example, the ROM list in `GBA` emulator contains 100 games: 

```
gba-001
gba-002
...
gba-100
```

Presume that the cursor is on `gba-050` , now press `RIGHT` to switch to `Super Nintendo` emulator and then press `LEFT` switch back to `GBA`. I found the cursor rewind to `gba-001`.

This is alright if you have less than 100 ROMs, but what if you have 1000 Roms ?? You have to select a  ROM from beginning every time .

### Expected behavior

Remember last cursor position in the rom list when switching emulators, when I switch back to `gba` the cursor should stay on `gba-050` .

### Actual behavior

The cursor resets to the first rom `gba-001` and I have to press `DOWN` for a long time to get back to the last position I visited (`gba-050`).

Due to this, I have to reduce ROM numbers to avoid wasting my time in navigation.

### Environment information

- OS: PSVITA
- Version: RetroArch 1.7.6
- Compiler: Unknow

**Comment by RobLoach** [comment]
I don't believe that pattern is applied on the oirignal PS3 menu. May be confusing when you don't expect it. I'd actually recommend trying out Ozone if XMB isn't working well for you.

Also remember that the Favourites menu is there too, which can be helpful when the playlists are large.

**Comment by sonninnos** [comment]
This can be closed.
