### ISSUE TITLE
90 and 270 Degree Rotations Cause Uneven slang Shader Scaling

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#8876]
## Description

A core like FBNeo has incorrect 1:1 PAR for auto rotated vertical games. That should be corrected by switching the height/width reported, but doing that causes issues with integer scaling.

Also, shaders like crt-guest-dr-venom have alignment/scaling issues with rotated vertical games in FBNeo. @barbudreadmon mentioned that would also probably fixed by switching the reported height/width, but again, that messes with integer scaling.

I originally reported these issues on the FBNeo repo:
https://github.com/libretro/FBNeo/issues/25
https://github.com/libretro/FBNeo/issues/32

And there was another issue thread that brought up some of the problems with rotation, but it got too off the rails: https://github.com/libretro/RetroArch/issues/8551

### Expected behavior

A game like Dimahoo should look like this in FBNeo when using 1:1 PAR:
![image](https://user-images.githubusercontent.com/4565863/58540308-1e663300-81c7-11e9-8aab-2dba3cb5537d.png)

crt-guest-dr-venom should look nicely aligned/scaled with FBNeo's rotation.

### Actual behavior

Dimahoo in FBNeo looks like this with 1:1 PAR:
![image](https://user-images.githubusercontent.com/4565863/58540374-3f2e8880-81c7-11e9-9cb1-d8dd55aa70a5.png)

crt-guest-dr-venom has bad alignment/scaling when used on a rotated vertical game in FBNeo. Here's how it compares to MAME's software rotation with the shader's TATE mode enabled: http://screenshotcomparison.com/comparison/701

### Steps to reproduce the bug

1. Load a vertical game like Dimahoo in the FBNeo core.
2. In video settings, switch the aspect ratio to 1:1 PAR and/or load a CRT shader.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 948c242922

### Environment information

- OS: Win10 Using the Vulkan driver.

**Comment by barbudreadmon** [comment]
Yeah, basically there is a number of issues when you switch width/height (https://github.com/libretro/RetroArch/issues/8551) and a number of other issues when you don't (https://github.com/libretro/FBNeo/issues/25 & https://github.com/libretro/FBNeo/issues/32).

I expect the current behavior (sending width/height prior to rotation + the rotation) to be the right behavior (that's also what is done in beetle-DC), imho what's missing is awareness at the shader & custom ratio level.

**Comment by Awakened0** [comment]
I was just messing around with this in SNES9x using the default Core Provided aspect:

No Rotation:
![Mega Man X (USA) (Rev 1)-190621-215353](https://user-images.githubusercontent.com/4565863/59958122-72cf9c00-946f-11e9-9325-66b0ca067767.png)

90 Degree Rotation in XnviewMP:
![ROTATEandresize](https://user-images.githubusercontent.com/4565863/59958179-54b66b80-9470-11e9-9931-ac8d52f471d4.png)

90 Degree Rotation in RetroArch:
![Mega Man X (USA) (Rev 1)-190621-215407](https://user-images.githubusercontent.com/4565863/59958123-80852180-946f-11e9-9387-a2bcee4f2f51.png)

Would a better title of this issue be that 90 or 270 degree rotations don't also rotate the aspect ratio as they should?

**Comment by Awakened0** [comment]
I normally use Vulkan, but I tested with gl and glcore with pretty much the same results. The shader seems to have slightly different alignment between them though: http://www.framecompare.com/image-compare/screenshotcomparison/P77LNNNX

**Comment by Awakened0** [comment]
A workaround for FB Neo I found is to turn on Vertical mode in it's core options, then set Screen Orientation to 270. crt-guest-dr-venom looks about the same as it does with MAME with TATE mode enabled and both PAR and DAR aspects work as expected. Though that also makes the GUI sideways :P

**Comment by Awakened0** [comment]
Made comparisons with how it looks normally and with the workaround: http://www.framecompare.com/image-compare/screenshotcomparison/PKD7NNNX

So with FB Neo vertical mode off and normal screen orientation, I get a 1080x1440 screenshot. Vertical mode on and orientation 270 gives me a sideways screenshot with 1440x1080 res. But I guess the orientation option rotates the whole OS, since the game is properly vertical when I'm playing at 270. I rotated the second comparison image manually in XnviewMP to show how it actually looks. There must be some difference in how screen orientation scales the image versus the frontend's rotation option that causes the difference in how the shader looks...

**Comment by Awakened0** [comment]
@Themaister and @twinaphex gave me this rotation patch to try out:
```
diff --git a/retroarch.c b/retroarch.c
index 906bb61c0e..8ae785e9ee 100644
--- a/retroarch.c
+++ b/retroarch.c
@@ -9916,6 +9916,14 @@ void video_viewport_get_scaled_integer(struct video_viewport *vp,
        * system->av_info.base_height. */
       base_width = (unsigned)roundf(base_height * aspect_ratio);

+      /* Get rotation parameter from somewhere. */
+      if (settings->uints.video_rotation & 1) /* 90 degrees */
+      {
+         unsigned tmp = base_width;
+         base_width   = base_height;
+         base_height  = tmp;
+      }
+
       /* Make sure that we don't get 0x scale ... */
       if (width >= base_width && height >= base_height)
       {
```
It rotates the aspect ratio, but only if integer scaling is enabled. And even with integer on, the uneven shader scaling when rotated is not fixed.

**Comment by Aethyrion** [comment]
Fixed issues (both for Core API rotation and menu rotation):
- Shaders are now working properly (only in OpenGL).
- 1:1 PAR is now correct.
- When using Custom Aspect Ratio, Integer Scaling is now working properly (correct multiples of internal resolution). Even when Integer Scaling is not activated, the Custom AR width / height are now correctly labeled using (1x), (2x), ... suffixes.
- For all other Aspect Ratio options, Integer Scaling and rotation are now working properly together (correct multiples of internal resolution).

I'll try to fix other video drivers later.

**Comment by Awakened0** [comment]
Excellent, thanks!

I do primarily use Vulkan, but in the meantime I might override my vertical games to use gl.

**Comment by barbudreadmon** [comment]
Nice, thanks for this !

**Comment by guestrr** [comment]
I would just like to mention that i added a new rotation / TATE mode with the recent SLANG update of the crt-guest-sm shader. It sortoff rotates and switches x/y original resolutions before processing, so an after rotation done by the core isn't needed or doesn't smear masks/scanlines.

![TATE-SM](https://user-images.githubusercontent.com/19492138/74949396-02ae5700-53fe-11ea-8948-35617d782714.png)

![batsugun-200220-162108](https://user-images.githubusercontent.com/19492138/74949471-19ed4480-53fe-11ea-9f4a-a442a4b5eb91.png)

First picture shows how it looks with "Allow Rotation" disabled in general core options and the second with "Vertical mode" enabled in FBNeo core options.

**Comment by barbudreadmon** [comment]
should be fixed by https://github.com/libretro/RetroArch/pull/11942
