### ISSUE TITLE
[Android] RetroArch crashing instantly when run

### ISSUE THREAD

**Issue by SaucySarah** [libretro/RetroArch#8878]

**Comment by SaucySarah** [comment]
Has anyone managed to have a look at these logs yet ?

I generated some logs on my other device (GPDXD Handheld, Android 4.4.4, Mali T-764). Now Retroarch won't start. It crashes instantly!

 Please help.

[retroarch__2019_05_30__15_01_42.log](https://github.com/libretro/RetroArch/files/3237376/retroarch__2019_05_30__15_01_42.log)
[retroarch__2019_05_30__15_08_05.log](https://github.com/libretro/RetroArch/files/3237377/retroarch__2019_05_30__15_08_05.log)
[retroarch__2019_05_30__15_09_20.log](https://github.com/libretro/RetroArch/files/3237378/retroarch__2019_05_30__15_09_20.log)
Last two logs are crashing instantly.

**Comment by twinaphex** [comment]
I don't have your hardware, but I could test it on other 4.x like devices (like a Samsung Galaxy S4).

**Comment by SaucySarah** [comment]
Thanks, i'd appreciate it. Considering the same crash happens on two different devices but both are using Android Kitkat. Hope my logs can give you insight.

**Comment by fr500** [comment]
A log doesn't have the required info in crash events.
You need the logcat trace.

Someone recently pushed some fixes for mali so I figure that's related

**Comment by SaucySarah** [comment]
Some adb logs.

When I ran Retroarch this time I got a black screen.
[Retroarch Black Screen.txt](https://github.com/libretro/RetroArch/files/3241033/Retroarch.Black.Screen.txt)

I then deleted the retroarch.cfg to see if it would start again, but no.
I cleared the cache and updated to Nightly 2019-05-31. Got a crash on the first game that I ran.
[log1.txt](https://github.com/libretro/RetroArch/files/3241036/log1.txt)

I reopened Retroarch and tried running the same game but it said there was no core !? Redownloaded the core again and it crashed on loading a game.
[log2.txt](https://github.com/libretro/RetroArch/files/3241043/log2.txt)

**Comment by bparker06** [comment]
It looks like you might have run out of RAM.

**Comment by twinaphex** [comment]
Yeah, it does seem to point in that direction. Do you have any dormant apps running that saps a lot of RAM?

**Comment by SaucySarah** [comment]
I turned the device off and on but still crashes on the first game I run. v1.7.6 works fine so does v1.7.7 Stable onwards require more RAM ? My GPDXD Handheld has 2GB DDR3 and my other device Vega Tegra Note 7 has 1GB DDR3L-1600. A memory leak ?

**Comment by SaucySarah** [comment]
Here are a couple of adb logs from my Tegra device. It doesn't crash as quickly as the GPDXD. I kept running games then going back to the menu until it crashes (about 4 or 5 games). I'm hoping that you haven't given up on this ! Otherwise i'll have to go back to v1.7.6 and never update it.

[tegra log1.txt](https://github.com/libretro/RetroArch/files/3242599/tegra.log1.txt)
[tegra log2.txt](https://github.com/libretro/RetroArch/files/3242601/tegra.log2.txt)

**Comment by twinaphex** [comment]
We just have to be able to reproduce it first

**Comment by SaucySarah** [comment]
Did you manage to find your Kitkat device to try and confirm it ? I must have bad luck to get the same crashing on two different devices (although they are both running Kitkat). Are my logs from the Tegra device any more helpful than the others ?

**Comment by twinaphex** [comment]
Please be a bit more patient. This might take a weekend, a week, or so. I'll try to get to it as soon as I am also unoccupied with other development duties (like overseeing several bounties/etc).

**Comment by SaucySarah** [comment]
@twinaphex Sorry to disturb you, have you had any time to even confirm this issue (Kitkat ?). I can't use anything beyond 1.7.6 Stable and GooglePlay keeps trying to update it.

**Comment by askotx** [comment]
This happens too on Android 5.0 samsung grand prime with 1gb ram free 384mb, running a game -a snes game was enough- then call menu, after that a message pop up: retroach has stopped working.

**Comment by twinaphex** [comment]
I tested the F-Droid version on a Samsung Galaxy S4 running Android 4.4.2 and experienced no issues running Doom for about 5 minutes with Prboom, going in and out of the menu ,leaving it idle, and playing around.

Can you test the F-Droid version?

**Comment by askotx** [comment]
I think I can do it, let me check and test again.

**Comment by askotx** [comment]
Tested on F-droid apk version 1.7.7 git e011a07, bit I think it's another issue, anyway here it go: Run a game, then pause, go to load content but from another core let's say from snes to gba, then boom: retroarch stopped working

**Comment by twinaphex** [comment]
I got it to sometimes crash when loading cores in and out on the old Galaxy S4, but other times when I deliberately want to force it to crash, I can't succeed in getting it to crash. So that is weird. I can't seem to reproduce a consistent pattern.

Please be very specific in your instructions. Tell me exactly step 1, 2, 3, 4, 5, so there can be no confusion and I can completely reproduce it.

On the S10 I have no issues whatsoever with this so far.

**Comment by askotx** [comment]
You're right there is no pattern: I got different crashes: 
1. Load a game fron Load Content, like dkc 2 on snes9x-2005
2.- Start game
3.- Call menu.
4.- Load Content now dkc 2 mgba core, then sometimes crashes if not then..
5.- Call menu, then Close content, sometimes it crashes, if not then...
6.-Load content dkc 2 snes9x 2005 core
7-Load content dkc2.gba mgba core sometimes it crashes other doesn't.

**Comment by twinaphex** [comment]
Is it maybe an issue with those two cores in specific? Do you have better luck with other cores?

**Comment by askotx** [comment]
Maybe, I also tested fceumm, no crashes, gambatte, no crashes, genesis plus same fate, just mgba, snes9x-2005 and snes9x-2010 crashed. If there is no crashes, suddenly if you are moving through menu options and/or save the app crashes annyway, I don't know, perhaps it's a leak or something like that, I'm no expert. Sorry, no more info to give, I really would like to help more.

**Comment by SaucySarah** [comment]
My crashes that I reported in the first posts happened when using Mame2003plus and Fuse but I'm pretty sure it crashes when using any core. I even had a crash after updating to the latest Nightly, ran RetroArch and it crashed while it was unpacking the Retroarch-1 assets.

**Comment by 2xtime** [comment]
I'm also experiencing this on Android Kitkat. I didn't even change the core. I loaded a game, then went back to the GUI to change some custom controls, back to game. Went back to the GUI to apply a cheat and it crashed, 'Retroarch has stopped working'. Really annoying. I tried v176 that @SaucySarah stated and it doesn't crash. So does that mean the final version for Android Kitkat is 176 ? How do we stop Goggle from updating it ?

**Comment by twinaphex** [comment]
No need for panic, I will try looking into it when I find the space and time.

**Comment by SaucySarah** [comment]
@twinaphex Will this ever be fixed ? Could you (or any RetroArch member) devote half hour of your time to fix this ? Someone of your skill set would probably have it fixed in minutes. It's not like i'm asking for a feature request, it's a Retroarch crash. A new version will be out soon and I still won't be able to use it. Sorry if I sound desperate, but I am. Everytime I do googleplay updates I have to make sure it doesn't update Retroarch. Do you need any more logs from me ? From what people are saying it's memory related, so is it a memory leak ?

Pretty please :-)

**Comment by SaucySarah** [comment]
https://github.com/libretro/RetroArch/issues/9066

**Comment by SaucySarah** [comment]
@twinaphex Still nothing ? Can @orbea fix this ?

**Comment by orbea** [comment]
Sorry, android issues are out of my comfort zone.

**Comment by SaucySarah** [comment]
@orbea Thanks for replying at least. It looks like v176 is the final working version for Android Kitkat. Maybe this should be highlighted in the Docs or the Libretro website.

**Comment by twinaphex** [comment]
Maybe you should instead be more patient and stop badgering developers?

I know there is an issue, and I'm trying to ask around. So far there are no takers for who wants to and CAN fix this issue.
