### ISSUE TITLE
[Directory listing] Segfault when trying any type of directory listing

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#8888]
## Description

When using the ozone driver, attempting to go into any directory listing instantly segfaults. 

* Load Content > Select a directory
* Settings > Directory > Select a path to change

Trying in other menu drivers, the directory listings are completely blank

![image](https://user-images.githubusercontent.com/841440/58669705-e49e4500-830a-11e9-8b4c-1ed751a48a93.png)

![image](https://user-images.githubusercontent.com/841440/58669739-ff70b980-830a-11e9-82cb-0259e217cd7d.png)

### Expected behavior

Directory listing to work.

### Actual behavior

Either is completely blank or crashes based on the menu driver.

### Steps to reproduce the bug

1. Switch to ozone menu driver 
2. Reload RetroArch
3. Open any directory listing

### Version/Commit

- RetroArch: 1.7.7.r272.07d8daf048

### Environment information

- OS: Arch Linux
- Compiler: gcc 8.3.0-1

Coredump and backtrace attached.

[gdb.txt](https://github.com/libretro/RetroArch/files/3238994/gdb.txt)
[coredump.txt](https://github.com/libretro/RetroArch/files/3238995/coredump.txt)

**Comment by parkerlreed** [comment]
Seems weird as I went back to the previous commit I was on and its still failing. I may have just not done any directory listing on that version (I'm not aware of anything else changing system side to cause this)

**Comment by parkerlreed** [comment]
```
87452b2eac2ff1f5d472814daf452f39ec36794a is the first bad commit
commit 87452b2eac2ff1f5d472814daf452f39ec36794a
Author: radius <andres.430@gmail.com>
Date:   Mon May 27 21:39:51 2019 -0500

    fixup layout path on android, add some comments, move the order of the user directories

:040000 040000 9406ae8b3e58b638b83e1f871627f6a006b364b1 40195750c8b3601a1894a41c669036daf65e1a82 M      frontend
:040000 040000 8060a64b126c8a87bd420412e98fc38bf39c2755 efa757af03f1565152ba50902c94f76469bb43b9 M      pkg
```

**Comment by fr500** [comment]
Highly unlikely to be the culprit

**Comment by parkerlreed** [comment]
That's where bisect got me. Works on the previous commit (maybe off by one?)

**Comment by parkerlreed** [comment]
Just tested on another computer (same setup)

Works here f164b4be3dee175f5bed160c85d213bf54eebd27 

Breaks on the next commit 87452b2eac2ff1f5d472814daf452f39ec36794a

**Comment by parkerlreed** [comment]
Transplanted the "working" platform_unix.c into master and it works https://raw.githubusercontent.com/libretro/RetroArch/f164b4be3dee175f5bed160c85d213bf54eebd27/frontend/drivers/platform_unix.c

![image](https://user-images.githubusercontent.com/841440/58676560-b595cc80-8326-11e9-83b8-d57c3c746e61.png)

So something in that file, even though only Android was modified, is messing with the loading on regular Linux.

**Comment by twinaphex** [comment]
Make these changes in platform_unix locally one line at a time until you find the exact culprit. That way we dont have to revert this but can just fix the line in question.

**Comment by parkerlreed** [comment]
Will do. Will let you know.

**Comment by parkerlreed** [comment]
Very last edit in platform_unix https://github.com/libretro/RetroArch/commit/87452b2eac2ff1f5d472814daf452f39ec36794a#diff-d3bf64bfb5fb730f4fe4e72994c07615L2129

Everything before then compiled and worked.

After inserting that block and new endif, I get the directory crashes.

**Comment by twinaphex** [comment]
Yeah that looks wrong to me - that way, Linux would get no drive list whatsoever.

Try and see if this fixes the issue -

https://github.com/libretro/RetroArch/commit/4862368b02b8b5eec9ca0277a4d3d3e4fea50fe3

**Comment by parkerlreed** [comment]
:+1: worked. Everything is back to being happy. Thanks.
