### ISSUE TITLE
TVOs  can't compile Retroarch TVOs - rcheevos missing

### ISSUE THREAD

**Issue by s-areal** [libretro/RetroArch#8899]
I'm not a developer and this is a strange place for me so... please be gentle...

I didn't´find any IPA for Retroarch Apple TV so I tried this guide over here:
https://docs.libretro.com/guides/install-ios/#apple-tv

I'm using Xcode 10.2 and after setting this to build for Apple TV, i got a lot of yellow error(i believe this is more or less ok) but i also get this red error that doesn't allow me to finish the build.

RetroArch/deps/rcheevos/src/rcheevos/internal.h:5:10: 'rcheevos.h' file not found

Can anyone help please.
Simao

Version/Commit 1 1.7.7
- OS: 10.14.5
- Compiler: Xcode 10.2

**Comment by orbea** [comment]
Can you edit `pkg/apple/RetroArch_iOS11.xcodeproj/project.pbxproj` and add this line between line 895 and 896.
```
../../deps/rcheevos/include,
```
So it looks like this.
```
				HEADER_SEARCH_PATHS = (
					../../,
					"../../libretro-common/include",
					../../deps/stb,
					../../deps/rcheevos/include,
					../../deps/libz,
					../../deps,
);
```

https://github.com/libretro/RetroArch/blob/ebaa5b9941d0d65d59617b00f8906dd805a14aeb/pkg/apple/RetroArch_iOS11.xcodeproj/project.pbxproj#L895

Does that work?

**Comment by CoderTonyChan** [comment]
> Can you edit `pkg/apple/RetroArch_iOS11.xcodeproj/project.pbxproj` and add this line between line 895 and 896.
> 
> ```
> ../../deps/rcheevos/include,
> ```
> 
> So it looks like this.
> 
> ```
> 				HEADER_SEARCH_PATHS = (
> 					../../,
> 					"../../libretro-common/include",
> 					../../deps/stb,
> 					../../deps/rcheevos/include,
> 					../../deps/libz,
> 					../../deps,
> );
> ```
> 
> https://github.com/libretro/RetroArch/blob/ebaa5b9941d0d65d59617b00f8906dd805a14aeb/pkg/apple/RetroArch_iOS11.xcodeproj/project.pbxproj#L895
> 
> Does that work?

It's ok now

**Comment by orbea** [comment]
So yes, that change allowed you to build RetroArch?

**Comment by s-areal** [comment]
Hey, sorry for the delay.
And yes, it worked. As a matter a fact, i could not complete the build because my provisioning was revoked by apple, i guess i have to get a new one!
I would also like to ask, why ist´t available the ipa file? If I´could get the ipa, i think i could sign it using the appdb service the i already have. Could anyone provide the ipa for download?

Thanks

**Comment by orbea** [comment]
> I would also like to ask, why ist´t the ipa file available? I think this could be useful for many people like me not much Xcode oriented. Would´n be easier to make that available instead of having such the work writing a tutorial for that? (just asking)

I have no idea, but could you make a new issue for this? I suspect more people might who may know will see it then.

**Comment by s-areal** [comment]
yes, i will try that. Thanks
