### ISSUE TITLE
"Save Content Directory Preset" shader option does not fall back to the config directory

### ISSUE THREAD

**Issue by johanbcn** [libretro/RetroArch#8901]
## Description

The "Save Content Directory Preset" option from the "Shaders" quick menu option fails if the shaders directory is not writable, yet the "Save Shader Preset As" option succeeds.

### Expected behavior

"Save Content Directory Preset" should behave the same way as the "Save Shader Preset As" option, which falls back to the config directory if it cannot write to the shader directory.

### Actual behavior

Fails with the message "Error saving shader preset".
The logs output something like this:

```
[INFO] Failed writing shader preset to /usr/share/libretro/shaders/presets/Gambatte/gb.slangp.
[ERROR] Failed to save shader preset. Make sure config directory and/or shader dir are writable.
```

### Steps to reproduce the bug

1. Set the shaders directory as read-only
2. Start retroarch and load any game
3. Load a shader preset from the quick menu
4. Choose the "Save Content Directory Preset" option

### Bisect Results

The "Save Shader Preset As" shaders quick menu option succeds because it falls back to the config directory, as stated by the following log messages:
```
[INFO] Failed writing shader preset to /usr/share/libretro/shaders/foobar.slangp.
[INFO] Saved shader preset to /home/johanbcn/.config/retroarch/config/foobar.slangp.
```

And the "Save Content Directory Preset" logs hint that it should behave the same way, yet it doesn't:
```
[ERROR] Failed to save shader preset. Make sure config directory and/or shader dir are writable.
```

So I feel that both options should behave the same way for consistency.

### Version/Commit

- RetroArch: 1.7.7/62da78ca3d

### Environment information

- OS: Linux/Android
- Compiler: N/A

**Comment by johanbcn** [comment]
Moreover, I think that the shaders directory should not be used for user overrides. For example, on Android by default the shaders directory is not reachable by the user without root access.

**Comment by orbea** [comment]
> Moreover, I think that the shaders directory should not be used for user overrides or user content. For example, on Android by default the shaders directory is not reachable by the user without root access.

Sounds like a good idea to me.

**Comment by x6fan** [comment]
Issue #7551 has the same root cause as this Android issue: read-only shader directories. Using the `config` directory for core/content directory/content specific shader configuration would fix both issues. It would also make shader configuration consistent with other RetroArch configuration systems such as configuration overrides and input remapping, all of which use the `config` directory.
