### ISSUE TITLE
Android - defaults to XMB menu

### ISSUE THREAD

**Issue by foolishgrunt** [libretro/RetroArch#8906]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

After install of Retroarch, on start the app displays the desktop menu (XMB) rather than the Android menu (MaterialUI). The screenshot does not reflect this, but it is very small on the screen of my phone, and difficult to make out the text.

Compounding the problem is the fact that whatever overlay buttons are supposed to be used to navigate are completely invisible. By randomly tapping on different portions of the screen I have been able to accidentally move between options, but I have not been able to successfully navigate into any of the configuration options to be able to change the default menu.

![Screenshot_20190602-222259](https://user-images.githubusercontent.com/1423934/58778925-26d4ba00-8589-11e9-9080-7f425ccc8afb.png)

### Expected behavior

See the MaterialUI menu

### Actual behavior

See the XMB menu

### Steps to reproduce the bug

1. Install RetroArch
2. Open RetroArch
3. See wrong menu

### Bisect Results

This became an issue for me late last month when I re-flashed my build of LineageOS. Prior to this my installation of RetroArch was working flawlessly - I believe I originally installed 1.7.6, then upgraded to 1.7.7 after its release (with no issues). After flashing, I reinstalled RetroArch 1.7.7 from scratch, which is when I first experienced this troublesome behavior.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

-Device:  Moto G4 Play
-OS:  LineageOS 14.1-20190210-NIGHTLY-harpia (Android 7.1.2)

**Comment by foolishgrunt** [comment]
You're right that I forgot to mention the device. Updated to reflect that it's a Moto G4 Play.

I can assure you that this is definitely a phone. Are there any log files I can provide that would help isolate why it's not being identifies as such?

More immediately, is there a workaround I can use to actually navigate, so that I can select a different interface?

**Comment by fr500** [comment]
you could use a gamepad temporarily.

**Comment by fr500** [comment]
Problem is this line:
https://github.com/libretro/RetroArch/blob/master/frontend/drivers/platform_unix.c#L574

**Comment by twinaphex** [comment]
OK, so it's unintentionally identifying 'Play' (as a substring) and then defaulting it to XMB. Guess we need a special exception for this device then.

**Comment by foolishgrunt** [comment]
> OK, so it's unintentionally identifying 'Play' (as a substring) and then defaulting it to XMB. Guess we need a special exception for this device then.

There are a good handful of Motorola devices that carry the name 'Play':
https://en.wikipedia.org/wiki/Motorola_Moto

**Comment by LiveLM** [comment]
I also have a G4 Play (running Android 9 though) and the issue also happens here.
I was able to workaround it by using a file explorer and navigating to `Internal Storage > Android > data > com.retroarch > files > retroarch.cfg` and changing `menu_driver` to `glui`

**Comment by foolishgrunt** [comment]
> I was able to workaround it by using a file explorer and navigating to `Internal Storage > Android > data > com.retroarch > files > retroarch.cfg` and changing `menu_driver` to `glui`

I had this idea as well, but hadn't taken the time yet to figure out which line item needed editing.

Anyway, confirmed that this solution works.

**Comment by twinaphex** [comment]
I'll takeout that line 'Play' then, since Xperia Play is already identified by the prior two strings anyway.

**Comment by twinaphex** [comment]
Done. The next nightly should have these changes.

**Comment by twinaphex** [comment]
@foolishgrunt Can you confirm if the recent nightlies fixed this for you?

**Comment by foolishgrunt** [comment]
I cleared data, uninstalled, and reinstalled 1.7.8_git from Google Play. The issue is fixed for me.
