### ISSUE TITLE
Bluetooth Driver Bounty

### ISSUE THREAD

**Issue by Luraktinus** [libretro/RetroArch#8916]
Please add a Bluetooth driver
- Auto pair
- Device discovery
- Etc

Having to go to ssh all the time is pure pain

---
https://www.bountysource.com/issues/75063854-bluetooth-driver-bounty

**Comment by natinusala** [comment]
So the idea would be to have a "bluetooth driver" feature for RA, similar to the current WiFi driver (connmanctl).

The driver would be able to discover, browse and pair to new devices and automatically connect to known devices. Automatic pairing and connection to visible controllers / keyboards could be another interesting feature.

I suppose menu integration is part of the bounty otherwise there's no point in making such a driver. I also suppose the target platform to be Linux (dbus or bluetoothctl could be used), since Lakka is mentioned in the OP.

**Comment by Luraktinus** [comment]
In any case, I think this is unacceptable
![Screenshot_20190604-205131](https://user-images.githubusercontent.com/33608674/58905830-fc126f00-870a-11e9-9457-71675638f622.png)

Doing this every time I reconnect is pain

**Comment by twinaphex** [comment]
A native Bluetooth input driver would certainly be cool. Would probably be a big undertaking though.

**Comment by bullghost** [comment]
iam using ubuntu 18.04lts,
the bluetooth from it already have auto binding, only need to register for the first time.
i use ps3 dualshock , xbox one s, chinese android bluetooth joystick  all works fine

**Comment by Luraktinus** [comment]
...good for you I guess

**Comment by fr500** [comment]
native BT input would be pointless in my opinion.
I did some work with btstack on windows back then, got as far as listing the discoverable devices but had no assistance from the RA devs so I never got anywhere.

That said that required winusb/libusb drivers.

The correct approach for this would be similar to what lakka uses to connect to a wifi network. Not a fully fleshed driver but some pairing GUI and let the OS and HID handle input normally

**Comment by natinusala** [comment]
Well the goal is certainly not native Bluetooth input but just a frontend to discover and pair devices from RA

**Comment by bullghost** [comment]
> ...good for you I guess

i just realize you are using retroarch on android,
in your case might not get same version of bluez tool with ubuntu 18.04lts.
anyway maybe you can try  RamonGilabert bluetooth.sh scripting for temporary solution.
its also use bluez console for scripting.

**Comment by Luraktinus** [comment]
i really only care for lakka

**Comment by gouchi** [comment]
- [Feature request](https://github.com/libretro/Lakka-LibreELEC/issues/807) in Lakka issue tracker.

**Comment by dirthurts** [comment]
I'm just hoping for a GUI addition for Retroarch/Lakka so you can pair and use the controller all on the same device. Even access to terminal would be start. SSH from another computer to pair a device in Lakka isn't user friendly and likely turns a lot of users away to other platforms. I contributed to the bounty, perhaps others will do the same.

**Comment by nuwonda** [comment]
one of the reasons I went with batocera instead. don't want to ssh to lakka just to pair a controller.

**Comment by Mored4u** [comment]
Hot To Connect Xbox Wireless Controller On Lakka
================================================

1. Connect to Lakka through SHH then Create a new file using nano...
`nano /etc/modprobe.d/bluetooth.conf`

2. Add a single line to the new file...
`options bluetooth disable\_ertm=Y
`
3. Exit nano, saving the file in the process.

4. Now connect the controller
```
bluetoothctl
scan on
scan off
devices

trust EC:83:50:EF:30:D1     #depend on the device name (EC:83:50:EF:30:D1)
pair EC:83:50:EF:30:D1
connect EC:83:50:EF:30:D1   #do this code many time if not happen from first time

trust EC:83:50:BB:B1:3A	    #for second player (second Xbox wireless controller)
pair EC:83:50:BB:B1:3A
connect EC:83:50:BB:B1:3A

quit
reboot
```

5. To check about devices (you must see the connected device names)
`bluetoothctl`


![image](https://user-images.githubusercontent.com/5413459/81921725-baa96580-95e3-11ea-87eb-5fc34230f9e3.png)
