### ISSUE TITLE
where can I download new core for ios/tvos?

### ISSUE THREAD

**Issue by CoderTonyChan** [libretro/RetroArch#8924]
I download the core from nightly ios9.
But All of this is useless.

http://buildbot.libretro.com/nightly/apple/ios9/latest/

**Comment by yoshisuga** [comment]
There’s a link to download precompiled cores here:
http://docs.libretro.com/guides/install-ios/

**Comment by CoderTonyChan** [comment]
> There’s a link to download precompiled cores here: http://docs.libretro.com/guides/install-ios/
> […](#)

But I want to try some new core like desmume / ppsspp / crita / fbneo / parallel_n64

**Comment by orbea** [comment]
Do any of those build for ios9?

**Comment by CoderTonyChan** [comment]
> Do any of those build for ios9?

I can find desmume / fbneo / n64 in http://buildbot.libretro.com/nightly/apple/ios9/latest/

But it did not work.

**Comment by orbea** [comment]
How did it not work? You should try the core specific issue trackers for those issues.

For example the desmume tracker is here.

https://github.com/libretro/desmume/issues

**Comment by CoderTonyChan** [comment]
Now I download desmume core from here. http://johan.margueritte.free.fr/buildbot/ios-arm64/.
It's OK.
