### ISSUE TITLE
(Linux-specific) ROMs refuse to appear, period

### ISSUE THREAD

**Issue by SaikoHaven** [libretro/RetroArch#8925]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

On Debian 9 using build instructions from the docs, RetroArch will not discover or show ROMs. For the record, they are .nes files that are recognized on Android and Windows. So it's Linux-specific.

### Expected behavior

ROM files are shown in Load Content and are discovered in playlist

### Actual behavior

ROM files are not shown in Load Content without turning on hidden files, and are not discovered in playlist.

### Steps to reproduce the bug

1. Install a fresh install of Debian 9
2. Build using instructions found in http://docs.libretro.com/development/retroarch/compilation/ubuntu/
3. Run Retroarch
4. Download a core
5. Observe

### Bisect Results

Not really big on this developer stuff, so I can't help with this one. Sorrryyyyyyy.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

- OS: Debian 9
- Compiler: gcc (I think, whatever was in the Makefile)

**Comment by orbea** [comment]
Do you have the core info files? Do you have the database files?

**Comment by SaikoHaven** [comment]
One of the first things downloaded so yes.

**Comment by orbea** [comment]
> ROM files are not shown in Load Content without turning on hidden files

I missed this on my first read of the issue, can you confirm that the path for your info files matches where the info files actually are? You can find the path by looking in `~/retroarch.cfg` and checking the set value of `libretro_info_path`.

I think that should only happen if the `info` files are missing.

**Comment by SaikoHaven** [comment]
Ah, yes I will check that, hold on

**Comment by SaikoHaven** [comment]
Where exactly is this in the config? I can't seem to find it.
Should I redownload the database/core info?

**Comment by orbea** [comment]
err, sorry, I typo'd the config path...

Its at `~/.config/retroarch/retroarch.cfg`.

**Comment by SaikoHaven** [comment]
It's set as `~/.config/retroarch/cores`
I can not nor will not explain why it's in cores

**Comment by orbea** [comment]
I'll assume the info files are not actually there? I would try changing it to a path where the info files actually exist. You can also confirm that `content_database_path` is correct and then try to scan the nes files again.

You may want to check `/etc/retroarch.cfg` too. If RetroArch starts and `~/.config/retroarch/retroarch.cfg` does not exist that file will be sourced to create a new file. Possibly that is how it got set?

**Comment by SaikoHaven** [comment]
/etc/retroarch.cfg is non-existent

**Comment by SaikoHaven** [comment]
I have fixed it by myself, something fucked up at build time. Sorry all
