### ISSUE TITLE
Double widget popup notifications for controllers

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#8930]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Controller connected/configured popup notifications are doubling up.  (widgets i believe theyre called?).  This happens predominantly in the GenesisGX core.  I assumed it was core specific, since that is where it happens, however after posting the issue report on the core github, I was told that notifications are retroarchs doing and thus have nothing to do with the core.  

When/if using DS4Windows, you already get 2 notifications (DS4 controller configured, and Xinput configured simultaneously), this "bug" leads to 4 stacked up widgets in that scenario lol. 

Here is an image
https://www.dropbox.com/s/00cc37rr8m7avro/2019-06-06_16-44-26.png?dl=0

### Expected behavior

A single popup indicating a controller has been configured, uniform with everywhere else within the UI. 

### Actual behavior

It is stacking/doubling up 2 of these notifications, for some reason with only the genesis core it seems.

### Steps to reproduce the bug

1. connect a controller.  (any should work, i thought it was related to being a steam controller, but ive since closed steam and tried with an xbox controller with the same result)
2. start retroarch and note the controller popup indicating its configured and the port
3. load a rom from most any playlist, and notice the same popup (one).
4. load a genesis rom using the genplusgx core, and you/I am receiving 2 of these widgets.

### Bisect Results

Best I can recall, it began with the new widget system.  May have been before but that certainly aided in my noticing. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.77 faf612098f

### Environment information

- OS: Windows 10

**Comment by fr500** [comment]
I only get one
![image](https://user-images.githubusercontent.com/1721040/59066199-1156dd00-8874-11e9-8d35-32bf371c497d.png)

**Comment by klepp0906** [comment]
I was half hoping that would be the case.   What then would cause me to get 2, but only with that core?  Not controller specific, thats all i can tell on my end.  and I have no remaps, or overrides or anything for that core.

**Comment by fr500** [comment]
Sound like ds4windows causing it imho.

**Comment by klepp0906** [comment]
yea but, ds4windows isnt running, and its a xbox one controller not ps controller. 

also tried with a untouched copy sequestered off and it didnt happen.   (i should have done that first tbh)

so it is something within RA, I just dont know enough regarding how RA functions to zero in on what it could be. 

Unfortunately that leaves me turning to the professionals :(

**Comment by fr500** [comment]
Remove chunks of your config and start retroarch like that and kill it till you can narrow it down

**Comment by klepp0906** [comment]
roar.  so i removed the retroarch.cfg.   Still does it, only with genesisplusgx core.  Put that back and tried removing entire autoconfig folder.   Still does it, only with genesisplusgx core.

tested with barren 1.77 nightly, 1.77 stable, 1.76 stable.  All fine with all cores.

What on gods green earth still holds sway config wise over the genesis core that wouldnt be reset by removing either of the aforementioned files/directories?

**Comment by klepp0906** [comment]
we have a winner.

Interlaced mode 2 output.  Whatever that is (sounds something visual to me) got toggled on.  

Turn it off.  Voila, one controller being detected/widgeted/displayed etc.

Closing this guy as to help keep home base clean for you poor guys >.<
