### ISSUE TITLE
retroarch wont load any cores HELP

### ISSUE THREAD

**Issue by link334** [libretro/RetroArch#8934]
retroarch isint loading any cores i can download them but they dont work im on linux when i select the load core option in retroarch and select a core it goes back to the menu or if i go on load content and load a core that way it says failed to load core

**Comment by bparker06** [comment]
Please fill out the issue template instead of deleting it. We need that information.

**Comment by orbea** [comment]
Please reopen this issue after filling out the template if anyone can reproduce this. There is not anything we can do without more information.
