### ISSUE TITLE
[Feature request] - Vulkan GPU card selection

### ISSUE THREAD

**Issue by aqxa1** [libretro/RetroArch#8937]
## Description
The ability to select the GPU used for rendering when using the Vulkan driver (or generally) would be a nice feature to have, since there is no support for card selection at the driver level (at least on Linux) without patching the GPU driver. There is planned support for this at the API level (see [here](https://github.com/KhronosGroup/Vulkan-Ecosystem/issues/30)), but it would be useful if Retroarch supported it natively as this could be a long way off.

Why? On multi-gpu systems, It's not uncommon for the weaker secondary card to be used, which means worse performance, but with AMD cards also breaks Freesync entirely, and requires forcing TearFree driver option on to get any tearing prevention.

### Expected behavior
The ability to choose the GPU used for rendering from the GUI or at least as a config option.

### Actual behavior
The feature does not exist.

### Version/Commit
- RetroArch: 1.7.7

### Environment information

- OS: Gentoo AMD64, Mesa RADV
- Compiler: 8.2.0

**Comment by orbea** [comment]
I think this should be solved at the OS level.

**Comment by bparker06** [comment]
I'm not opposed to having an option for this (for all supported drivers that can do it), I think it's a good idea as many other apps and games support it as well, and I'd be happy to add the feature. But the main issue is if it's even possible. You say Vulkan doesn't have an API to select the GPU, so how is RA supposed to do it? I only know of a way to select GPUs for modern Direct3D, I don't know of a universal in-app way to do it for any other graphics API.

EDIT: The link you gave mentions using `vkEnumeratePhysicalDevices`... is this not enough? Seems like that can be used to select the GPU. The libretro vulkan spec even states that a core is allowed to do its own GPU selection.

**Comment by bparker06** [comment]
@orbea That will prevent people from overriding the GPU based on the driver/core/content.

**Comment by aqxa1** [comment]
> You say Vulkan doesn't have an API to select the GPU, so how is RA supposed to do it?

@bparker I should have been clearer. The linked issue would likely result in a change to the Vulkan specification to allow for device selection at the driver side, in the future. But, it is indeed pretty simple to implement this on the application side, such as in Retroarch.

**Comment by rdanbrook** [comment]
You can query the available GPUs on the system and select the "best" one for your purposes based on their capabilities. If you're doing multi-GPU rendering this becomes less relevant, but if you're forcing all operations on a single GPU then there should be some routine to select what is "best" based on the criteria you specify, within the application itself.

**Comment by bparker06** [comment]
@aqxa1 Can you verify the new feature works for you?

**Comment by aqxa1** [comment]
@aqxa1 I can confirm that the frontend and most cores work, but beetle-psx-libretro looks to be doing it's own device selection when using the hardware renderer (which ends up selecting the wrong card).

**Comment by bparker06** [comment]
@Themaister Do you know if the order of `vkEnumeratePhysicalDevices()` is guaranteed stable across different calls? What about DirectX? And also @twinaphex Should we add an extension to the libretro API to pass along a desired GPU to use for hardware cores?

**Comment by bparker06** [comment]
Closing this since the requested feature seems to work.

**Comment by xzn** [comment]
Currently for beetle-psx-libretro you could use `GRANITE_VULKAN_DEVICE_INDEX` environment variable to select vulkan device. Until there's a better method.
