### ISSUE TITLE
PS3 dualshock controller sdl2 key id mapping issue

### ISSUE THREAD

**Issue by bullghost** [libretro/RetroArch#8939]
Hi dev,
i found out there is issue on PS3 dualshock key mapping 
when the input joypad driver set to sdl2, 
where only in retroarch is produce different value then others,
like emulationstation and sdl-jstest from Grumbel github and compile the sdl2-jstest 

### The Issue:
here is the retroarch i use bindAll after i set the input joypad driver to sdl2 :
`input_player1_l_axis = "nul"
input_player1_l_btn = "9"
input_player1_l_mbtn = "nul"
input_player1_l_x_minus = "nul"
input_player1_l_x_minus_axis = "-0"
input_player1_l_x_minus_btn = "nul"
input_player1_l_x_minus_mbtn = "nul"
input_player1_l_x_plus = "nul"
input_player1_l_x_plus_axis = "+0"
input_player1_l_x_plus_btn = "nul"
input_player1_l_x_plus_mbtn = "nul"
input_player1_l_y_minus = "nul"
input_player1_l_y_minus_axis = "-1"
input_player1_l_y_minus_btn = "nul"
input_player1_l_y_minus_mbtn = "nul"
input_player1_l_y_plus = "nul"
input_player1_l_y_plus_axis = "+1"
input_player1_l_y_plus_btn = "nul"
input_player1_l_y_plus_mbtn = "nul"
input_player1_left = "left"
input_player1_left_axis = "nul"
input_player1_left_btn = "13"
input_player1_left_mbtn = "nul"
input_player1_mouse_index = "0"
input_player1_r = "w"
input_player1_r2 = "nul"
input_player1_r2_axis = "+5"
input_player1_r2_btn = "nul"
input_player1_r2_mbtn = "nul"
input_player1_r3 = "nul"
input_player1_r3_axis = "nul"
input_player1_r3_btn = "8"
input_player1_r3_mbtn = "nul"
input_player1_r_axis = "nul"
input_player1_r_btn = "10"
input_player1_r_mbtn = "nul"
input_player1_r_x_minus = "nul"
input_player1_r_x_minus_axis = "-2"
input_player1_r_x_minus_btn = "nul"
input_player1_r_x_minus_mbtn = "nul"
input_player1_r_x_plus = "nul"
input_player1_r_x_plus_axis = "+2"
input_player1_r_x_plus_btn = "nul"
input_player1_r_x_plus_mbtn = "nul"
input_player1_r_y_minus = "nul"
input_player1_r_y_minus_axis = "-3"
input_player1_r_y_minus_btn = "nul"
input_player1_r_y_minus_mbtn = "nul"
input_player1_r_y_plus = "nul"
input_player1_r_y_plus_axis = "+3"
input_player1_r_y_plus_btn = "nul"
input_player1_r_y_plus_mbtn = "nul"
input_player1_right = "right"
input_player1_right_axis = "nul"
input_player1_right_btn = "14"
input_player1_right_mbtn = "nul"
input_player1_select = "rshift"
input_player1_select_axis = "nul"
input_player1_select_btn = "4"
input_player1_select_mbtn = "nul"
input_player1_start = "enter"
input_player1_start_axis = "nul"
input_player1_start_btn = "6"
input_player1_start_mbtn = "nul"
input_player1_turbo = "nul"
input_player1_turbo_axis = "nul"
input_player1_turbo_btn = "nul"
input_player1_turbo_mbtn = "nul"
input_player1_up = "up"
input_player1_up_axis = "nul"
input_player1_up_btn = "11"
input_player1_up_mbtn = "nul"
input_player1_x = "s"
input_player1_x_axis = "nul"
input_player1_x_btn = "2"
input_player1_x_mbtn = "nul"
input_player1_y = "a"
input_player1_y_axis = "nul"
input_player1_y_btn = "3"
input_player1_y_mbtn = "nul"
`

### emulationstation :
`	<inputConfig type="joystick" deviceName="Sony PLAYSTATION(R)3 Controller" deviceGUID="050000004c0500006802000000800000">
		<input name="a" type="button" id="0" value="1" />
		<input name="b" type="button" id="1" value="1" />
		<input name="down" type="button" id="14" value="1" />
		<input name="hotkey" type="button" id="8" value="1" />
		<input name="joystick1left" type="axis" id="0" value="-1" />
		<input name="joystick1up" type="axis" id="1" value="-1" />
		<input name="joystick2left" type="axis" id="3" value="-1" />
		<input name="joystick2up" type="axis" id="4" value="-1" />
		<input name="l2" type="button" id="6" value="1" />
		<input name="l3" type="button" id="11" value="1" />
		<input name="left" type="button" id="15" value="1" />
		<input name="pagedown" type="button" id="5" value="1" />
		<input name="pageup" type="button" id="4" value="1" />
		<input name="r2" type="button" id="7" value="1" />
		<input name="r3" type="button" id="12" value="1" />
		<input name="right" type="button" id="16" value="1" />
		<input name="select" type="button" id="8" value="1" />
		<input name="start" type="button" id="9" value="1" />
		<input name="up" type="button" id="13" value="1" />
		<input name="x" type="button" id="3" value="1" />
		<input name="y" type="button" id="2" value="1" />
	</inputConfig>
`

### retroarch config file:
`https://pastebin.com/kWYgzyKn`

### emulationstation config file :
`https://pastebin.com/rCgGYRxp`

### Version
RetroArch: from master branch

### Environment information
- OS: ubuntu 18.04

please help, 

thanks.

**Comment by orbea** [comment]
First I would suggest to not use the `sdl` input driver unless the others do not work. I would suggest using either the `x` or `udev` input drivers instead. For the `udev` input driver you will need your user to be in the input user group.

I don't know anything about emulationstation so I can't help with that, but RetroArch has its own input config files. There is a chance it has already been made and you can install it with the online updater (Make sure your autoconfig directory is writable).

Otherwise here are the steps to create a input config:

1. Change to the desired input driver.
2. Config your gamepad in the input settings (Don't forget the home button in the Hotkey binds).
3. Save your autoconfig.
4. Reset your gamepad to the defaults in the input settings and it should now use your new autoconfig profile. You might have to add the home button manually?
5. See this repo about submitting new configs. https://github.com/libretro/retroarch-joypad-autoconfig

**Comment by bullghost** [comment]
> First I would suggest to not use the `sdl` input driver unless the others do not work. I would suggest using either the `x` or `udev` input drivers instead. For the `udev` input driver you will need your user to be in the input user group.
> 
> I don't know anything about emulationstation so I can't help with that, but RetroArch has its own input config files. There is a chance it has already been made and you can install it with the online updater (Make sure your autoconfig directory is writable).
> 
> Otherwise here are the steps to create a input config:
> 
> 1. Change to the desired input driver.
> 2. Config your gamepad in the input settings (Don't forget the home button in the Hotkey binds).
> 3. Save your autoconfig.
> 4. Reset your gamepad to the defaults in the input settings and it should now use your new autoconfig profile. You might have to add the home button manually?
> 5. See this repo about submitting new configs. https://github.com/libretro/retroarch-joypad-autoconfig

hi for way i choose sdl over udev its because my other joypad only work with sdl, went i set as udev retroarch fail to detect the device. but js-test able to identify and test the device. so for both joypad work in retroarch i must set to input joypad driver to sdl.

my other device is beboncool an android bluetooth joypad.

thanks for the idea , it seem to be temporary idea, i will try it.
but its better if there a fix of the retroarch on pickup different value then others when driver is using sdl.

Thanks.

**Comment by orbea** [comment]
> hi for why i choose sdl over udev its because my other joypad only work with sdl, went i set as udev retroarch fail to detect the device. but js-test able to identify and test the device. so for both joypad work in retroarch i must set to input joypad driver to sdl.

You might just missing a autoconfig file for udev.

> thanks for the idea , it seem to be temporary idea, i will try it.
but its better if there a fix of the retroarch on pickup different value then others when driver is using sdl.

I'm not sure I understand, this is just how autoconfig profiles work in RetroArch.

**Comment by bullghost** [comment]
> > hi for why i choose sdl over udev its because my other joypad only work with sdl, went i set as udev retroarch fail to detect the device. but js-test able to identify and test the device. so for both joypad work in retroarch i must set to input joypad driver to sdl.
> 
> You might just missing a autoconfig file for udev.
> 
> > thanks for the idea , it seem to be temporary idea, i will try it.
> > but its better if there a fix of the retroarch on pickup different value then others when driver is using sdl.
> 
> I'm not sure I understand, this is just how autoconfig profiles work in RetroArch.

hi orbea ,
thanks, your solution is working great. 

i want to confirm this issue about different mapping key value retroarch compare with other is false alarm.
i have retest it again found out joypad ordering in emulationstation was different with retroarch that make my python script wrongly map the key from emulationstation to retroarch.

admin please kindly close this issue.
thanks.
