### ISSUE TITLE
[Usability Request] know what's missing in MAME/FBA/FBN roms

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/RetroArch#8947]
## Description

Something along the lines of 'Missing [name of rom]' should do it, useful for those that don't want to use something like ClrMAMEPro.

### Expected behavior

'Failed to load content, missing [name of rom]'

### Actual behavior

Failed to load content.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.77

### Environment information

- OS: [Windows 8.1]

**Comment by hizzlekizzle** [comment]
Isn't this already available from a verbose log?

**Comment by arnoldsecret** [comment]
it's for the non-technical users, might lessen spam for why some roms don't work

**Comment by fr500** [comment]
RA would have to audit the roms itself....
I don't think this is gonna happen

**Comment by i30817** [comment]
> it's for the non-technical users, might lessen spam for why some roms don't work

Non technical users should learn to be technical instead of asking for features to spam a horrible interface for auditing (no copy paste for one, the fact that RA notifications only exist for few seconds for another).

**Comment by arnoldsecret** [comment]
closed, refer to @fr500's comment.
