### ISSUE TITLE
[ozone] Resizing windowed ozone does not redraw boundaries

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#8953]
## Description

Starting ozone in windowed mode and then resizing window/going fullscreen causes it to not redraw to fit the screen

![image](https://user-images.githubusercontent.com/841440/59218036-4c675200-8b8d-11e9-9a4c-ac471d3ec380.png)

### Expected behavior

Rescales to window

### Actual behavior

Does not rescale to window

### Steps to reproduce the bug

1. Select ozone menu driver
2. Start windowed
3. Reszie window or go fullscreen

### Version/Commit

- RetroArch: v1.7.7 -- 99a466fd7d

### Environment information

- OS: Arch
- Compiler: GCC (8.3.0)

https://www.youtube.com/watch?v=KFfL40kgCEw

**Comment by orbea** [comment]
I can't reproduce this, what video driver are you using? What GPU are you using?

**Comment by parkerlreed** [comment]
Mesa 19.20. Both Intel and AMD with the gl video driver.

**Comment by orbea** [comment]
I still can't reproduce it with gl, glcore or vulkan using AMD and a recent mesa commit (` Mesa 19.2.0-devel (git-a8588f512b)`).

**Comment by parkerlreed** [comment]
RX 560 and RX 480 (two separate machines). 

Oddly enough it's also doing it in Vulkan for me. 

Are you starting windowed? Starting fullscreen and toggling does work (showed in the video)

Other than that, I'm not sure what could be different. I'll keep digging here and see if anything weird in configuration/assets is causing it.

**Comment by parkerlreed** [comment]
Something between the initial comment and today has fixed the issue O.o (Just did a fresh master compile)

Very possibly could have been https://github.com/libretro/RetroArch/commit/7c17cd9213660a3e1eadb5cc656538853ec63b37
