### ISSUE TITLE
Loading State is Broken During Video Record

### ISSUE THREAD

**Issue by Mario253** [libretro/RetroArch#8964]
## Description

Loading a state from any save slot while recording in mGBA does not work.

### Expected behavior

Save with F2 or in Quick Menu, start recording with O, load with F4/Quick Menu to work as expected (save a point, load that point later on)

### Actual behavior

The state saves properly, but pressing F4 does nothing (not even a message). Going into the Quick Menu and selecting Load State just sends you back to the game.

### Steps to reproduce the bug:

1.) Save a state.
2.) Start a recording.
3.) Attempt to load a state.

OR

1.) Start a recording.
2.) Save a state.
3.) Attempt to load a state.

### Bisect Results

[Will possibly insert later when I have time]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.4.1/d8855ca

### Environment information

- OS: Ubuntu 18.04 (under [crouton](https://github.com/dnschneid/crouton/), Chrome OS version 74.0.3729.159)
- Compiler: gcc/g++ (GNU C/C++ compilers)

**Comment by fr500** [comment]
*one point four point one.*
That was released on February 2017.

No point even trying to reproduce this. Try with a recent version.

**Comment by Mario253** [comment]
Closing this issue as I just learned that I was recording into a bsv file, which is just keystrokes. Oops...
