### ISSUE TITLE
Dreamcast emulators not working  Linux OS

### ISSUE THREAD

**Issue by Gitlab1111** [libretro/RetroArch#8970]
Feren OS
cinnamon version 4.0.10
Linux Kernel 4.18.0-21-generic
Intel© Core™ i5-4670 CPU @ 3.40GHz × 4

Retroarch 1.7.7

When using Reicast, Flycast and the other Flycast WinCE I end up with a frozen screen on the Dreamcast boot logo resulting in Retroarch freezing as well.  I ended up deleting the cores and re-downloading them at a later date but and it still has Flycast and Flycast WinCE resulting in the same freezing error
![Dreamcast Reicast 0 1 4a020d4](https://user-images.githubusercontent.com/41243135/59516669-ae1e0980-8e76-11e9-9c85-686d470b75f6.png)

**Comment by keithbowes** [comment]
That sounds like an issue with the cores (though, maybe Retroarch should be able to handle nonfunctional cores more gracefully), which you're not supposed to file here, especially if the standalone emulators work.  You should try it in verbose mode (`retroarch -v`).  I know that's helped me figure out what's wrong in the past.

**Comment by bparker06** [comment]
What game are you trying? Some require explicitly setting the correct region/language to boot properly. Others may not like the video setting (e.g. VGA vs RGB).

**Comment by hizzlekizzle** [comment]
It'd also be useful to know how you installed RetroArch. That is, self-compiled, distro packages, PPA, universal package, something else?

**Comment by Gitlab1111** [comment]
I have been testing out USA reigon rom's such as Power Stone 2 and Dino Crisis 1.  I installed Retroarch through the  Feren Os software store. Feren OS is based on Linux Mint.  There's also a separate issue of cores not downloading from it's default settings and directories so I had to make my own folder for cores under my documents folder in order to do so.  As for Video, i have the default settings left on in drivers and the core. 
![RA drivers video](https://user-images.githubusercontent.com/41243135/59548552-f5071000-8f05-11e9-87b9-f423a245d649.png)

**Comment by Gitlab1111** [comment]
[INFO] RetroArch 1.7.7 (Git 62da78c)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES 
[INFO] Built: May 17 2019
[INFO] Version: 1.7.7
[INFO] Git: 62da78c
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/home/linux/Documents/retroarch saves/.srm".
[INFO] Redirecting savestate to "/home/linux/Documents/retroarch saves/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 960x720
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: Window manager is Mutter (Muffin).
[INFO] [GLX]: X = 0, Y = 0, W = 960, H = 720.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Haswell Desktop .
[INFO] [GL]: Version: 3.0 Mesa 18.2.8.
[INFO] [GL]: Using resolution 960x720
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [udev]: Plugged pad: Logitech Gamepad F310 (1133:49693) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event15) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event15) supports 16 force feedback effects.
[INFO] [Autoconf]: 274 profiles found.
[INFO] [Autoconf]: selected configuration: /home/linux/Documents/retroarch/autoconfig/udev/Logitech_Gamepad_F310.cfg
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "gl".
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/ozone/regular.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/ozone/bold.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] [Menu]: Found menu display driver: "gl".
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-80.png
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-60.png
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-40.png
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-20.png
[INFO] [LED]: LED driver = 'null' 0x55f87444c0a0
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[WARN] Input device ID 5 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/linux/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [PulseAudio]: Pausing.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] Using content: /media/linux/SSD Games/Roms/Dreamcast/Dino Crisis/Dino Crisis (USA).gdi.
[INFO] arg #0: retroarch
[INFO] arg #1: /media/linux/SSD Games/Roms/Dreamcast/Dino Crisis/Dino Crisis (USA).gdi
[INFO] arg #2: -s
[INFO] arg #3: /home/linux/Documents/retroarch saves
[INFO] arg #4: -S
[INFO] arg #5: /home/linux/Documents/retroarch saves
[INFO] arg #6: -c
[INFO] arg #7: /home/linux/.config/retroarch/retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: /home/linux/Documents/retroarch/cores/flycast_libretro.so
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : /home/linux/.config/retroarch/retroarch.cfg
[INFO] RetroArch 1.7.7 (Git 62da78c)
[INFO] Redirecting save file to "/home/linux/Documents/retroarch saves/Dino Crisis (USA).srm".
[INFO] Redirecting savestate to "/home/linux/Documents/retroarch saves/Dino Crisis (USA).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-4670 CPU @ 3.40GHz
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES 
[INFO] Built: May 17 2019
[INFO] Version: 1.7.7
[INFO] Git: 62da78c
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/home/linux/Documents/retroarch/cores/flycast_libretro.so"
[INFO] [Overrides] no core-specific overrides found at /home/linux/Documents/retroarch/config/Reicast/Reicast.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /home/linux/Documents/retroarch/config/Reicast/Dino Crisis.cfg.
[INFO] [Overrides] no game-specific overrides found at /home/linux/Documents/retroarch/config/Reicast/Dino Crisis (USA).cfg.
[INFO] [Shaders]: preset directory: /home/linux/Documents/retroarch/shaders/presets
[INFO] Environ SET_VARIABLES.
[INFO] Environ SET_CONTROLLER_INFO.
[INFO] [Remaps]: remap directory: /home/linux/Documents/retroarch/config/remaps
[INFO] [Remaps]: no game-specific remap found at /home/linux/Documents/retroarch/config/remaps/Reicast/Dino Crisis (USA).rmp.
[INFO] [Remaps]: no content-dir-specific remap found at /home/linux/Documents/retroarch/config/remaps/Reicast/Dino Crisis.rmp.
[INFO] [Remaps]: no core-specific remap found at /home/linux/Documents/retroarch/config/remaps/Reicast/Reicast.rmp.
[INFO] Redirecting save file to "/home/linux/Documents/retroarch saves/Dino Crisis (USA).srm".
[INFO] Redirecting savestate to "/home/linux/Documents/retroarch saves/Dino Crisis (USA).state".
[INFO] Environ GET_LOG_INTERFACE.
[INFO] Environ GET_PERF_INTERFACE.
[INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
[INFO] Environ SET_KEYBOARD_CALLBACK.
[INFO] Content loading skipped. Implementation will load it on its own.
[INFO] CRC32: 0x9fbe5c3a .
[INFO] Environ GET_RUMBLE_INTERFACE.
[libretro INFO] Rumble interface supported!
[INFO] Environ SYSTEM_DIRECTORY: "/home/linux/Documents/retroarch/system".
[reicast]: Got size: 1280 x 960.
[INFO] Environ SET_SAVE_STATE_IN_BACKGROUND: yes.
[libretro INFO] File extension is: .gdi
Creating dir: /home/linux/Documents/retroarch/system/dc/data
[INFO] Environ SET_HW_RENDER.
[INFO] Requesting core OpenGL context (3.0).
Linux paging: 00001000 00001000 00000FFF
MAP 00800000 w/ 25165824
MAP 20000000 w/ 25165824
MAP 04000000 w/ 16777216
MAP 06000000 w/ 16777216
MAP 0C000000 w/ 0
A8
vmem reserve: base: 0x7fe5e4700000, aram: 0x7fe604700000, vram: 0x7fe5e8700000, ram: 0x7fe5f0700000
Resetting mem
Loaded /home/linux/Documents/retroarch/system/dc/dc_boot.bin as bootrom

Loaded /home/linux/Documents/retroarch/system/dc/dc_nvmem.bin as nvram

[libretro INFO] Using Recompiler
Sh4 Reset
recSh4 Init
Freeing fpcb

GDI : 3 tracks
file[1] "Dino Crisis (USA) (Track 1).bin": FAD:0, CTRL:4, SSIZE:2352, OFFSET:0
file[2] "Dino Crisis (USA) (Track 2).bin": FAD:450, CTRL:0, SSIZE:2352, OFFSET:0
file[3] "Dino Crisis (USA) (Track 3).bin": FAD:45000, CTRL:4, SSIZE:2352, OFFSET:0
gdrom: Opened image "/media/linux/SSD Games/Roms/Dreamcast/Dino Crisis/Dino Crisis (USA).gdi"
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Sh4 Reset
reios: IP.bin is 'SEGA SEGAKATANA SEGA ENTERPRISES1E1B GD-ROM1/1   U      0799A00 T1217N    V1.00020000927        1ST_READ.BIN    SEGA LC-T-12    DINO CRISIS                                                                                                                     ����'
reios: Hardware ID is: SEGA SEGAKATANA 
reios: Maker ID is:    SEGA ENTERPRISES
reios: Device info is: 1E1B GD-ROM1/1  
reios: Area symbols is:  U      
reios: Peripherals is: 0799A00 
reios: Product number is: T1217N    
reios: Product version is: V1.000
reios: Release date is: 20000927        
reios: Boot filename is: 1ST_READ.BIN    
reios: Software company is: SEGA LC-T-12    
reios: Software name is: DINO CRISIS                                                                                                                     
reios: loading ip.bin from FAD: 45150
reios: bootfile is '1ST_READ.BIN    '
reios: iso9660 PVD found
reios: iso9660 root_directory, FAD: 45170, len: 14336
Found 1ST_READ.BIN at 000065
filename len: 14
file LBA: 548152
file LEN: 1736356
[libretro INFO] [LUT]: Product number: T1217N    .
[INFO] Environ SET_ROTATION: 0
[INFO] Environ SET_DISK_CONTROL_INTERFACE.
[INFO] Skipping SRAM load..
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [RCHEEVOS]: Load task finished
[INFO] [Audio]: Set audio input rate to: 44055.94 Hz.
[INFO] [Video]: Video @ 3840x2880
[INFO] [Video]: Using HW render, OpenGL driver forced.
[INFO] [Video]: Using configured "gl" driver for GL HW render.
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GLX]: GLX_OML_sync_control and GLX_MESA_swap_control supported, using better swap control method...
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1920x1080.
[INFO] [GLX]: Window manager is Mutter (Muffin).
[INFO] [GLX]: X = 0, Y = 0, W = 3840, H = 2880.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [GL]: Vendor: Intel Open Source Technology Center, Renderer: Mesa DRI Intel(R) Haswell Desktop .
[INFO] [GL]: Version: 3.0 Mesa 18.2.8.
[INFO] [GL]: Using Core GL context, setting up VAO...
[INFO] [GL]: Using resolution 1920x1010
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Using GLSL version 130.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 1 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Initializing HW render (2048 x 2048).
[INFO] [GL]: Max texture size: 16384 px, renderbuffer size: 16384 px.
[INFO] [GL]: Supports FBO (render-to-texture).
[INFO] [udev]: Plugged pad: Logitech Gamepad F310 (1133:49693) on port #0.
[INFO] [udev]: Pad #0 (/dev/input/event15) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event15) supports 16 force feedback effects.
[INFO] [Autoconf]: 274 profiles found.
[INFO] [Autoconf]: selected configuration: /home/linux/Documents/retroarch/autoconfig/udev/Logitech_Gamepad_F310.cfg
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
context_reset.
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "gl".
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/ozone/regular.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/ozone/bold.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-80.png
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-60.png
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-40.png
[WARN] [XMB] Asset missing: /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/png/battery-20.png
[INFO] [LED]: LED driver = 'null' 0x55f87444c0a0
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[WARN] Input device ID 5 is unknown to this libretro implementation. Using RETRO_DEVICE_JOYPAD.
[INFO] Loading history file: [/home/linux/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/linux/.config/retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] Written to playlist file: /home/linux/.config/retroarch/content_history.lpl
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[ERROR] Failed to create rendering backend: freetype.
Failed to open /home/linux/Documents/retroarch/libretro/assets/xmb/monochrome/font.ttf: No such file or directory
[ERROR] Failed to create rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: bitmap.
[INFO] Environ SET_INPUT_DESCRIPTORS:
Freeing fpcb
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
MODEM Reset
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Initializing VMU data...
Invalid GD-DMA start, SB_GDEN=0.Ingoring it.
new tactx
new tactx
Creating per-triangle/strip renderer

**Comment by bparker06** [comment]
Your GPU/driver is too old, it only supports OpenGL 3.0:

`[INFO] [GL]: Version: 3.0 Mesa 18.2.8.`

Flycast requires higher than that, but I'm not exactly sure what version is the minimum (maybe 3.3?).

Also it looks like your assets are missing, so you likely still have a permissions issue as well or just haven't updated them properly.

**Comment by RobLoach** [comment]
Closing this for now. Feel free to re-open an issue in the flycast queue if you update the GPU/driver and it still persists.
