### ISSUE TITLE
Retroarch constantly blinking in full-screen mode on 1440x2560 resolution with NVIDIA latest driver

### ISSUE THREAD

**Issue by xsyn1cx** [libretro/RetroArch#8976]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When trying to run Retroarch in Full Screen on a 1440 x 2560 resolution (tate), it constantly blinks/flickers very quickly. This behavior continues if you take it out of full screen, then enter into a game. This happened after updating to Nvidia's latest video driver, 

### Bisect Results

After updating to NVIDIA's latest video driver 430.86 (NVIDIA GeForce 1080 mobile video card)

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
I've tried this on 1.7.7

### Environment information

- OS: Windows 10 (latest update)

**Comment by orbea** [comment]
Since this worked with the previous nvidia driver and does not work with the newest driver I would report this to nvidia instead. Since their drivers are proprietary there is nothing we can do to help fix it...

**Comment by bparker06** [comment]
Have you tried this workaround to see if it might apply for your issue as well?

https://twitter.com/libretro/status/1078310859091398656

**Comment by xsyn1cx** [comment]
@bparker06  sorry in my delayed response. That fixed the issue. Thank you!
