### ISSUE TITLE
What is happening?

### ISSUE THREAD

**Issue by fr500** [libretro/RetroArch#8980]
Sorry to meddle but what is going on?
Why is the whole architecture of the program changing?

I'm far from an expert or even a proficient dev, and not part of the "team" but I still have some WIP things going on and these latest changes seem very concerning.

Is there any rationale or long term goals of rolling everything into retroarch.c?

**Comment by LazyBumHorse** [comment]
Here's an official answer: https://github.com/libretro/RetroArch/pull/8910#issuecomment-502708016

**Comment by fr500** [comment]
Thank you for responding.

In my opinion it's awful but like someone told me recently "not my circus, not my monkeys"
I'll stick to the current codebase until things stabilize.

**Comment by twinaphex** [comment]
It's how the original SSNES/RetroArch was like, with most of the code that was split into separate driver files inside one big runloop file. 

This allows for better restructuring of the codebase by getting most global state in one central place, and less passing around of state everywhere.

Anyway, it's an iterative process, and it's done to make the program last and become more maintainable in the long run. We cannot get there with all these separate files in their current form with all sorts of global state all across the place.

**Comment by fr500** [comment]
> We cannot get there with all these separate files in their current form with all sorts of global state all across the place

Of course you can, you use a branch, do it piecemeal until you are done.

Anyway, as I said, I'm no expert.
On the few programming classes I had this was the complete opposite of what I was taught.
Tasks are fine for certain things but are a huge headache when you thing things to run in order.

I'm sticking for the 1.7.7 codebase for the stuff I'm implementing.

**Comment by twinaphex** [comment]
Branches are a non-issue, the refactors are already done piecemeal. Anyway, I'm the leader of this project, and I am making this decision to do it this way.

> Tasks are fine for certain things but are a huge headache when you need things to run in order.

Of course they are a headache, but it eventually has to happen anyway. CPUs are only getting more cores instead of faster clock speeds, the main UI cannot block, many of these tasks on the main thread do block, which is bad. It's bad for Android, iOS, it's bad for the A/V synchronization timer, etc. It's bad for platforms like UWP where synchronous file I/O is very heavily penalized. It's a simple case of dealing with the headache because this is the way forward.

**Comment by twinaphex** [comment]
It was also an opportunity of getting rid of all these ctl functions (camera_driver_ctl, location_driver_ctl, audio_driver_ctl, etc). The ones that haven't already been gotten rid of, will be soon. There should be only one such function for all the driver stuff in retroarch.c, and that should be rarch_ctl. It was a bad design decision I made a few years ago to go for that approach, and themaister didn't like it either. So this is a way to correct that mistake.

**Comment by fr500** [comment]
It's just making it even harder for contributors to work in the codebase.
As I said before it's your call. I don't have any stake into this. 

Just my opinion.

**Comment by twinaphex** [comment]
I think keeping it the way it is actually does that. Sure, a near-500Kb file is not ideal and things are a lot bigger than they were in the SSNES days, but I'm sure the total code size can be made far smaller. And all this state passing around was not helping performance either for certain. You might even notice a speedup or two.

Anyway, it's part of a longer-term redesign. It will pan out well.

**Comment by LazyBumHorse** [comment]
If it's in the name of performance, multithreading and also reducing code, it can't be that bad, all that global state had it coming anyways.

The maintainability might suffer a bit, but speaking as someone who just started contributing a few weeks ago, getting into it requires lots of debugging know-how anyways.
There's no easy "reading into it" (if you try starting with configuration.c, you will go bonkers), no "it's about this, so it's probably there" (for example: guess where the core init is called... retroarch.c? Nah, command.c), you basically only find stuff by starting with a log message and backtracking (good ol' printf debugging).
So in practical terms, putting more code in 1 place doesn't change much.

What I'm saying is: stay positive, if it turns out bad, it's not like we are now stuck with it forever but it'll give an idea of how to do it even better, and if it doesn't turn out bad, well, great!

Personally I think what's much more upsetting than the actual code changes are all these small commits, almost a whole page of them! Please aphex, squash more! :smile:

**Comment by twinaphex** [comment]
Thank you for the upbeat attitude @LazyBumHorse . And yeah you're right, the sourcecode is already not readable as is it being splintered across so many files. It can only be improved really.

**Comment by fr500** [comment]
You should make sure to at least list all the contributors of the original
files you're wiping.

**Comment by twinaphex** [comment]
I don't really like the implication you're sending out there as if I'm supposedly forming some evil scheme to rob contributors of their copyright.

Let me warn you real quick - if you are going to use Github now as your new means of badgering/harrassing me, please don't. I really don't want to block you off the organization as well but if you persist in this malignant behavior, you might just leave me with no choice in the matter. Make one more comment like that again and you're out of here as well.

I really don't understand what the matter with you is.

**Comment by fr500** [comment]
You are in fact removing the files that have the authorship info. It's a
perfectly normal request.
Think whatever you want I don't care if you ban me. You should still list
the contributors.

**Comment by twinaphex** [comment]
Show me which names I'm omitting from which files. Stop being vague and list it.

> If you have a problem with such a simple request then you have bigger problems in your head.

If I wanted to be petty, I could have banned you already for such a straight forward insult. But I'm used to this kind of behavior from you by now.

**Comment by fr500** [comment]
Just to clear up, I left classic gaming on my own.
I don't care for places were moderation is more important than allowing people to discuss. If I was banned, then good riddance.

This is not harassment, and commenting on a tweet isn't either.
You may be the "project leader" but RetroArch is not "yours"; there is a difference. I'm a concerned party.

https://github.com/libretro/RetroArch/commit/7bbd927946a0806bf0c028538cbad5c313c97739#diff-f55ebca71e5c2e925e6d0259485bf3ebL4

https://github.com/libretro/RetroArch/commit/b9c33713b40011c46e93afabc856c967ffbea2d6#diff-7797ae0e7813aded66f109c460a562daL4

This whole file is @casdevel I think?
https://github.com/libretro/RetroArch/commit/491283cea1553d17e7731bf0dec8082c494d1e66#diff-3e686f2cccd2fec41c2dcc2b6f29e464

Those are just a few of the ones who bothered adding copyright.

**Comment by twinaphex** [comment]
You didn't leave of your own accord, I saw you being banned by a moderator on there. I did not ban you either for the record; it's clear others also were tired of this belligerent behavior you're showing.

You are still creating a narrative that I am doing hostile things with the project; probably something you want to spread again to others in your demonization/slander campaign.

All that you needed to do was cite the names. I will add them now. You don't have anything to be 'concerned about', I'm a honest broker.

I'll add the names. Casdevel didn't add his name so I will ask him later if he wants to be identified by either a nick or real name, it seems he just put in The RetroArch Team so it might not be even necessary. I don't want to be accused of anything like this again by you. This is your last warning. Come in with a belligerent attitude like this again and you will be banned. Next time, list the names which are missing and leave it strictly business.

@fr500 , one last time. Stop interfering with the project's daily going ons in a negative and subvertive manner. Stop following me around and harrassing me. There are a million other ways you can express that something is missing. You don't come out all guns blazing implying I am scrubbing copyright notices, I already saw this on your 'fork' already the stupid insinuation.

**Comment by fr500** [comment]
I left before they banned me, I know this for a fact.
I'm not creating any narrative. You are creating the narrative. I'm asking you to add back the names you removed when you removed the files.

You are the one who is implying that I'm implying something.

**Comment by twinaphex** [comment]
I added the names which you said were missing. At no point was I trying to scrub anybody of any copyright notices. You might have implied this or not, I reject that accusation. It was simply me forgetting to copy this. All you could have said was 'these names are missing; add them'.

https://github.com/libretro/RetroArch/commit/da1d03bcb0cdc9622bfa7005c75b544145ea44a0

> You know fully well that if I wanted to damage the project I could do far worse than pester you.

I'm going to respectfully ask that you stop doing this if you are doing it deliberately. I don't do this to you either. We have incompatible characters and they might never mix at this point, let's stay out of each others way on a personal level and let's keep our interactions on Github limited to development. I expect that you will be reasonable here unlike your other interactions so far.

> And before you ask, no this is not a threat. I could wipe the buildbot or the web servers immediately if I wanted to because you don't really manage your project. But I don't I don't care for that and it would harm good devs and more importantly the userbase.

You say it's not a threat, then you dish it out there. You might be saying this merely as an example but it sure sounds like something you are holding over my head.

**Comment by fr500** [comment]
It's not a threat.
