### ISSUE TITLE
RetroArch does not load proper commands from ArcBrowser when already open

### ISSUE THREAD

**Issue by thekiefs** [libretro/RetroArch#8981]
## Description
RetroArch cannot receive (or does not act) when commands from another application are sent if RetroArch is already opened

### Expected behavior
If RetroArch is already opened and another app calls RetroArch functions, I expect RetroArch to do those functions regardless of whether RetroArch is already open or not 

### Actual behavior
RetroArch loads on another app's call, but it does nothing and simply sits at the main menu

### Steps to reproduce the bug
1) Open RetroArch
2) Switch to ArcBrowser (without closing RetroArch)
3) Open and launch a game from ArcBrowser
4) Expect the game to be launched in RetroArch
5) The main menu of RetroArch appears but nothing happens
6) Completely closing out of RetroArch and retrying the launch from ArcBrowser fixes the problem

### Bisect Results
This has been going on for a while. It's documented here as well:
https://www.reddit.com/r/gpdxd/comments/82s74a/arc_browser_retroarch_not_loading/
https://forums.geforce.com/default/topic/874247/shield-tv/arc-browser-official-support-now-available/127/

### Version/Commit
- RetroArch: 8 May 2019
Git version: 8c17f12

### Environment information
- OS: Android (v8.0) SHIELD Android TV

**Comment by hizzlekizzle** [comment]
ArcBrowser interacts with RetroArch through the "intents" system, which is sort of like launching from a command line. So, this behavior is normal and to be expected, as the program is already launched. RetroArch does have a command interface that another program could potentially use, but ArcBrowser doesn't do it and it's not something we can implement on our end.
