### ISSUE TITLE
Protocol Error after update

### ISSUE THREAD

**Issue by gnollhide** [libretro/RetroArch#8986]
## Description

Program fails to launch after most recent update (Version 1.7.7-r201906171946-7bbd927-88~ubuntu18.04.1)

### Expected behavior

Expected to launch retroarch to main GUI.

### Actual behavior

On launch, a blank window is made then immediately crashes. Recent terminal output is 

`Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 16.
Segmentation fault (core dumped)`

Launching with --verbose is as follows
`[INFO] RetroArch 1.7.7 (Git 7bbd927)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Athlon(tm) II X3 455 Processor
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 
[INFO] Built: Jun 17 2019
[INFO] Version: 1.7.7
[INFO] Git: 7bbd927
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 1360x720
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GLX]: GLX_EXT_swap_control_tear supported.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1360x768.
[INFO] [GLX]: Window manager is Xfwm4.
[INFO] [GLX]: X = 0, Y = 0, W = 1360, H = 720.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapIntervalEXT(0)
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: Quadro K1200/PCIe/SSE2.
[INFO] [GL]: Version: 4.6.0 NVIDIA 390.116.
[INFO] [GL]: Using resolution 1360x719
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [udev]: Plugged pad: Generic X-Box pad (9414:64252) on port #0.
[INFO] [Autoconf]: 274 profiles found.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event6) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Autoconf]: selected configuration: /home/user/.config/retroarch/autoconfig/udev/Generic_X-Box_pad.cfg
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 18432.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 16.
[INFO] [Menu]: Found menu display driver: "gl".
Segmentation fault (core dumped)
`
Deleting the retroarch configuration and auto-generating a new one does not fix the issue, and gives the same error. Switching video driver to sdl2 via config does not fix it.

### Steps to reproduce the bug

1. Install most recent retroarch from ubuntu universe repo.
2. Attempt to start

### Bisect Results

This only started after I updated my system this morning and retroarch was one of the updates on the default "sudo apt update" list. I think the 18.04 branch just got broken with this update, I can provide checksums to make sure I'm not using a build that got corrupted in transit.

### Version/Commit

- RetroArch: Frontend for libretro -- v1.7.7 -- 7bbd927 --
Compiler: GCC (7.4.0) 64-bit
Built: Jun 17 2019

### Environment information

- OS: Ubuntu 18.04 Generic

**Comment by dssouza-ti** [comment]
I have the exact same problem. When I run "dmesg", that's what I get in my system related to retroarch:

[ 1188.678144] retroarch[11664]: segfault at ffffffffcd4c215b ip 00007f590a0b35a1 sp 00007ffe337e3fd8 error 5 in libc-2.27.so[7f5909f25000+1e7000]
[ 1308.801961] retroarch[11741]: segfault at ffffffffcc66015b ip 00007f359da705a1 sp 00007ffde5787138 error 5 in libc-2.27.so[7f359d8e2000+1e7000]

**Comment by gnollhide** [comment]
Just an update, after the update the program gives the same error, but actually launches the GUI. Using version 1.7.7-r201906201935-ef0cedd-88~ubuntu18.04.1, normal terminal output lists
`Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 16.
`
and launching with --verbose says
`[INFO] RetroArch 1.7.7 (Git ef0cedd)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Athlon(tm) II X3 455 Processor
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 
[INFO] Built: Jun 20 2019
[INFO] Version: 1.7.7
[INFO] Git: ef0cedd
[INFO] =================================================
[INFO] Environ SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 1360x720
[ERROR] [Wayland]: Failed to connect to Wayland server.
[INFO] [GLX]: GLX_EXT_swap_control_tear supported.
[INFO] [GL]: Found GL context: x
[INFO] [GL]: Detecting screen resolution 1360x768.
[INFO] [GLX]: Window manager is Xfwm4.
[INFO] [GLX]: X = 0, Y = 0, W = 1360, H = 720.
[INFO] [GLX]: Found swap function: glXSwapIntervalEXT.
[INFO] [GLX]: glXSwapIntervalEXT(0)
[INFO] [GL]: Vendor: NVIDIA Corporation, Renderer: Quadro K1200/PCIe/SSE2.
[INFO] [GL]: Version: 4.6.0 NVIDIA 390.116.
[INFO] [GL]: Using resolution 1360x719
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] Setting up menu pipeline shaders for XMB ... 
[INFO] [GLSL]: Compiling ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling simple ribbon shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling modern snow shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling bokeh shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Compiling snowflake shader..
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [GL]: Using GL_RGB565 for texture uploads.
[INFO] [udev]: Plugged pad: Generic X-Box pad (9414:64252) on port #0.
[INFO] [Autoconf]: 274 profiles found.
[INFO] [udev]: Pad #0 (/dev/input/event15) supports force feedback.
[INFO] [udev]: Pad #0 (/dev/input/event15) supports 16 force feedback effects.
[INFO] [Joypad]: Found joypad driver: "udev".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Autoconf]: selected configuration: /home/user/.config/retroarch/autoconfig/udev/Generic_X-Box_pad.cfg
[INFO] [X11]: Suspending screensaver (X11, xdg-screensaver).
[INFO] [Video]: Found display server: x11
[INFO] [PulseAudio]: Requested 24576 bytes buffer, got 34152.
[INFO] [Menu]: Found menu display driver: "gl".
Protocol error: bad 3 (Window); Sequence Number 11
 Opcode (20, 0) = GetProperty
 Bad resource 0 (0x0)
 at -e line 16.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [LED]: LED driver = 'null' 0x5639165e9600
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "alsa" driver.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/home/user/.config/retroarch/content_history.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_favorites.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_music_history.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_video_history.lpl].
[INFO] Loading history file: [/home/user/.config/retroarch/content_image_history.lpl].
[INFO] [GL]: VSync => off
[INFO] [GLX]: glXSwapIntervalEXT(0)
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [PulseAudio]: Pausing.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [PulseAudio]: Unpausing.
[INFO] [GL]: VSync => on
[INFO] [GLX]: glXSwapIntervalEXT(1)
[INFO] [PulseAudio]: Pausing.
[INFO] [PulseAudio]: Unpausing.
[INFO] [config] Saved new config to "/home/user/.config/retroarch/retroarch.cfg".
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] [PulseAudio]: Pausing.
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [XINERAMA]: Xinerama version: 1.1.
[INFO] [XINERAMA]: Xinerama screens: 1.
[INFO] [XINERAMA]: Saved monitor #0.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
`
and works as normally. I'll leave this open just in case someone else has the same error and has an updated take on it, but if not feel free to close this issue.
