### ISSUE TITLE
Retroarch downloaded thumbnail folders don't appear on PC, but they do on the phone's file manager

### ISSUE THREAD

**Issue by Daethic** [libretro/RetroArch#8987]
## Description

Folders that are downloaded from the RetroArch thumbnail updater don't appear on PC, and they do on the phone file manager. Also, if you create a folder of the same name on PC, it will duplicate the one on the file manager but still not display the files inside the duplicated folder.

### Expected behavior

Thumbnails to appear on both the phone's file manager and the PC's.

### Actual behavior

Thumbnails appear only on the phone's file manager, and not the PC's.

### Steps to reproduce the bug

1. Download thumbnail from Retroarch.
2. Check phone storage
3. Check PC storage in the same folder.

### Version/Commit

- RetroArch: Retroarch 64
                    Jun.18.2019
                    Version:b62476d

### Environment information

- OS: [Android]
- Compiler: N/A

https://cdn.discordapp.com/attachments/469974542299955210/590810410958192650/Screenshot_20190619-084908.png

https://cdn.discordapp.com/attachments/469974542299955210/590810466658549762/unknown.png

https://cdn.discordapp.com/attachments/469974542299955210/590811192705024001/unknown.png

**Comment by bparker06** [comment]
How is this an RA issue?

**Comment by Daethic** [comment]
> 
> 
> How is this an RA issue?

How is it NOT an RA issue? Unless you can prove that it's a phone/computer issue and nothing to do with RA?

**Comment by bparker06** [comment]
It's possible it's an MTP-related issue: https://android.stackexchange.com/questions/46315/not-all-files-are-visible-over-mtp

All I was saying is that if RetroArch can see the files, and your phone's file manager can see the files, I am doubtful that RA can somehow willfully cause its own files to not appear somewhere else.

**Comment by Daethic** [comment]
> 
> 
> It's possible it's an MTP-related issue: https://android.stackexchange.com/questions/46315/not-all-files-are-visible-over-mtp
> 
> All I was saying is that if RetroArch can see the files, and your phone's file manager can see the files, I am doubtful that RA can somehow willfully cause its own files to not appear somewhere else.
