### ISSUE TITLE
Shader Issue. Mac OsX High Sierra

### ISSUE THREAD

**Issue by dragonstory** [libretro/RetroArch#8988]
Hello

Retroarch 1.7.7
Any core always crashes when i try to load any shader.
Mac OSX High Sierra.
Normal Version not Metal version.
It has crashes with lastest nightly version 19.06.2019

This is from the Retroarc --verbose
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
Segmentation fault: 11

Process: RetroArch [38557]
Path: /Applications/RetroArch.app/Contents/MacOS/RetroArch
Identifier: libretro.RetroArch
Version: 1.7.6 (1.7.6)
Code Type: X86-64 (Native)
Parent Process: ??? [1]
Responsible: RetroArch [38557]
User ID: 501

Date/Time: 2019-05-12 14:05:04.224 +0300
OS Version: Mac OS X 10.13.6 (17G6030)
Report Version: 12
Anonymous UUID: A9B417FE-B7A8-A918-0D6E-DDADC002BEEF

Sleep/Wake UUID: 861F4E72-3D66-4E51-8555-61CC75652FCF

Time Awake Since Boot: 140000 seconds
Time Since Wake: 630 seconds

System Integrity Protection: enabled

Crashed Thread: 0 Dispatch queue: com.apple.main-thread

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_PROTECTION_FAILURE at 0x00007ffee86acf0f
Exception Note: EXC_CORPSE_NOTIFY

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [0]

VM Regions Near 0x7ffee86acf0f:
MALLOC_TINY 00007fa166800000-00007fa166900000 [ 1024K] rw-/rwx SM=PRV
--> STACK GUARD 00007ffee4ead000-00007ffee86ad000 [ 56.0M] ---/rwx SM=NUL stack guard for thread 0
Stack 00007ffee86ad000-00007ffee8ead000 [ 8192K] rw-/rwx SM=PRV thread 0

**Comment by twinaphex** [comment]
OK, I can confirm this and this is quite serious. Will try to fix this if I find out why it happens.

**Comment by twinaphex** [comment]
I think this patch fixed the issue for me -

https://github.com/libretro/RetroArch/commit/0c2c6781bfeee2eec73607a1fd43bb93ca3abd03

Let me know how it is on your end.

**Comment by dragonstory** [comment]
> I think this patch fixed the issue for me -
> 
> [0c2c678](https://github.com/libretro/RetroArch/commit/0c2c6781bfeee2eec73607a1fd43bb93ca3abd03)
> 
> Let me know how it is on your end.

I have tried the lastest tetrarch . 21.06.2019
it doesnt crash now when i apply the video shaders. But it is going to black screen. I can hear the sound but screen is all black.

**Comment by dragonstory** [comment]
2019-06-27_RetroArch
with this version; there is no crash but GLSL shaders does not activate. When i click the "Apply Shader" it doesnt activate.
