### ISSUE TITLE
Erratic framerate & distorted sound with newer kernels on RPi 3 B+

### ISSUE THREAD

**Issue by edrozenberg** [libretro/RetroArch#9036]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Hardware:
Raspberry Pi 3 B+ 1GB RAM, 128MB gpu_mem configuration

Software:
Slackware ARM 14.2+ (-current) (hard float)
RetroArch-1.7.7 built from source with flags:
-mtune=cortex-a53 -mcpu=cortex-a53 -mfloat-abi=hard -mfpu=neon-fp-armv8 -mneon-for-64bits
Libretro cores - 2019-06-29 (http://buildbot.libretro.com/nightly/linux/armv7-neon-hf/latest/)

No problems when running with kernel/modules 4.19.34-v7-arm and older boot firmware/overlays

Problems with low framerate/distorted sound (for ex. GameBoy Advance games via mGBA) after upgrading to 4.19.50-v7-arm or 4.19.56-v7-arm kernel/modules and a newer boot firmware/overlays package (http://sarpi.fatdog.eu/index.php?p=rpi3getcurrent)

With both old and new kernel/modules the CPU freq looks normal (`vcgencmd measure_clock arm`) - mostly at 1.2 GHz, dipping to .6 GHz very briefly (the idle freq). No apparent problems there. The RPi 3 is powered by the official power supply, no low voltage issues at all.

This may not be a RetroArch issue, but if there are any suggestions on steps to take to further troubleshoot I'll give anything a try. For now I downgraded and will stay on the older kernel/modules package versions.

### Expected behavior

Steady framerate of 59.x - 60.0. Normal audio output.

### Actual behavior

Low framerate (dips to the 40's at times), sometimes upper 50's. Distorted sound output. Sometimes after "a while" the framerate goes up to the normal 59.x - 60.0 and stays there, and sound returns to normal. Restarting RetroArch will often cause the problem to begin again.

### Steps to reproduce the bug

1. Upgrade the described kernel/modules/boot firmware from 4.19.34 to 4.19.50 or 4.19.56
2. Run RetroArch
3. Launch a GameBoy Advance game via mGBA

### Bisect Results

Not Applicable - the same RetroArch version 1.7.7 works fine with older kernel/modules/boot firmware, and has issues with newer kernel/modules/boot firmware

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

- OS: Slackware ARM 14.2+ (-current) (hard float)
- Compiler: gcc (GCC) 9.1.0

**Comment by pyrho** [comment]
Same issue on Raspberry Pi 4b (4gb, 512 gpu_mem).
Compiled with `CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --disable-opengl1 --enable-neon --enable-opengles3 --enable-opengles --disable-videocore && platform=rpi4 make -j3`.

Tried with 1.7.7, 1.7.9 and HEAD, I also noticed an improvement after like 15 minutes idling it will run at 60fps and the sound is fine.

The FPS does get higher if I disable Audio Synchronisation, but the sound is still distorted.

@edrozenberg did you find a workaround?

**Comment by edrozenberg** [comment]
@pyrho I didn't find any workaround and saw the same issues with various kernels including 4.19.69 and retroarch releases 1.7.8 vX, 1.7.9 v1.

Saw issues on SNES core, mGBA etc.

Rate returns to normal (60 ish) usually after 30 seconds - 2-3 minutes in the few games I tried.

Too bad to hear the same issue is there on RPi 4. Must be something other than CPU limitations that's causing the issue.

**Comment by edrozenberg** [comment]
Issue solved via a pulse audio scheduler setting:

Edit `/etc/pulse/default.pa` and change the following line:

`load-module module-udev-detect`

to:

`load-module module-udev-detect tsched=0`

**Reboot** then run the following command and verify `tsched` is set to off:

`pactl list | grep tsched`

I take no credit from the fix. Completely by accident came across this post on fixing sound stutter in Steam on RPi: https://steamcommunity.com/app/353380/discussions/6/1642042464753800526/

I posted here in more detail about this issue:
https://www.linuxquestions.org/questions/slackware-arm-108/rpi3-sarpi-retroarch-stuttering-sound-%2Afinally%2A-fixed-via-pulse-audio-tsched-setting-4175671360/
