### ISSUE TITLE
[overylay/touch] Touch events take precedence over overlay buttons

### ISSUE THREAD

**Issue by parkerlreed** [libretro/RetroArch#9043]
## Description

Whenever the on-screen overlay overlaps a core that uses touch input, the core touch is intercepted when pressing an overlay button. This isn't an issue for all cores, but some emulate hardware and this presents bugs.
 
### Expected behavior

The overlay should block events, because whether touch, button or both take precedence is emulator dependent

### Actual behavior

Touch input is interpreted even when pressing an overlay button

https://www.youtube.com/watch?v=wOoF6BiaBWA

(In this case Palm OS is emulated so well it exhibits the behavior of blocking button presses when the graffiti area is interacted with)

### Steps to reproduce the bug

1. Load up any core that uses touch input
2. Make sure overlay and the touch area are overlapping
3. Test the overlay buttons that overlap

### Version/Commit

- RetroArch: 1.7.7 and git builds

### Environment information

- OS: Multiple. Have confirmed behavior on Arch Linux, Android, and iOS

**Comment by markwkidd** [comment]
@mahoneyt944 is there any chance this is complicating some of our recent testing for MAME 2003-Plus?

**Comment by mahoneyt944** [comment]
Well... Yes and no. If you are using a touch screen as a virtual retropad then you wouldn't want to us it as a lightgun, mouse or pointer at the same time.  Because you would get this issue. That's why it's important to allow the user to disable the polling for these devices in the core options for our purposes anyhow.
