### ISSUE TITLE
[Feature request] Use Sokol to unify d3d/opengl/metal video drivers

### ISSUE THREAD

**Issue by albertofustinoni** [libretro/RetroArch#9048]
# Description

There is a project called [Sokol](https://github.com/floooh/sokol) that implements a low level wrapper around some of the most common graphics APIs in use today (GLES2/WebGL, GLES3/WebGL2, GL3.3, D3D11 and Metal).

This could be used to unify the code bases for the D3D11, OpenGL and Metal video drivers in RetroArch.

Sokol seems uniquely suited for use in RetroArch since:
- It is a very thin wrapper around the graphics API (so thin, in fact, it does not even handle hardware initialization - i.e. getting a context)
- As such it imposes no constraints on game loop/execution model of the application that uses it
- It is implemented in pure C, as a headers library, which makes for easier integration in Libretro's build architecture
- It is licensed under the zlib license, which should be compatible with RetroArch's
- The project has been running for two years at this point, [with activity throughout](https://github.com/floooh/sokol/graphs/code-frequency).
- Sokol by itself does not try to bridge between different shader languages, [but the authors are working on that too](https://github.com/floooh/sokol-tools/blob/master/docs/sokol-shdc.md). Even if shaders had to be kept separate, unifying drawing calls would still be a net gain

And the work would be valuable for several reasons:

- Having a single video driver code base targeting the most common graphics APIs would be more easily maintainable and have more consistent behavior across those platforms
- It could be a test to see suitability of Sokol as a way to bring more cores that need 3D acceleration cross platform. Right now a most cores for modern systems are unavailable outside of Linux (or Windows IF your GPU manufacturer bothers with decent OpenGL support). No Mac/iOS, no Xbox, no Windows on ARM.

**Comment by orbea** [comment]
One of the benefits of the RetroArch video drivers is that they do not depend on any dependencies like sokal and work with the actual OS. Sure some of these drivers could be improved more and maintenance could be reduced with more common code, but I don't think this is a good direction.

**Comment by RobLoach** [comment]
Would be pretty cool to implement a Sokol graphics driver. While I'm going to close this issue, don't feel like that should stop anyone for investigating its implementation. I'm curious about its use in two different places:

1. Sokol libretro core
2. Sokol libretro frontend

Feel free to comment if you've done a bit of research here!
