### ISSUE TITLE
[macOS] No cores seem to be able to run games

### ISSUE THREAD

**Issue by firelad97** [libretro/RetroArch#9065]
## Description

No matter what core or a ROM file I use, nothing had successfully ran. Tried both stable & nightly versions. When trying to load a ROM file, it either crashes or freezes RetroArch completely, or display a black screen with the option to return to RetroArch (Quick Menu). Some cores respond with "Missing files" error messages. Some of them I do not understand however. I haven't tested all cores yet, and will update this post when I do.

BIO files are in the place, updated cores, and even double-checked all directories RetroArch is in, plus the settings.

### Expected behavior

Able to load the core properly and run the game.

### Actual behavior

Attempted loading PSX/PSP core & an ISO file (PCSX ReARMed & PPSSPP):
https://i.imgur.com/dY7UJjj.png

Attempted loading SNES core & a ROM file (Snes9x):
https://i.imgur.com/mmRHPRP.png

Even sometimes a core will crash RetroArch.

### Steps to reproduce the bug

1. Download any cores.
2. Load a core and then load a ROM file (or load a ROM file directly).
3. An error message pops up or a black screen appears.

### Bisect Results

This is a clean fresh install, used stable version yesterday and tried nightly version today.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7, nightly 2019-07-06
(Git version is still showing "GIT_VERISON" on both versions for some reason)

### Environment information

- OS: macOS Catalina (beta 19A501i)
- Compiler: Clang/LLVM (10.0.0 (clang-1000.11.45.5)) 64-bit

**Comment by twinaphex** [comment]
You might have to compile the cores yourself for this particular beta version of macOS. Knowing Apple, a ton of internal changes got made probably that screw up backwards compatibility.

**Comment by firelad97** [comment]
I will try to downgrade back to Mojave first and try this again. I did tested this before upgrading to Catalina, and issues still occur there. A downgrade might fix this, no idea yet but I'll update you on that later.

**Comment by firelad97** [comment]
OS: macOS Mojave 10.14.5 with Metal
RetroArch: 1.7.7, stable 2019-05-06 & nightly 2019-07-08

Issues are still present for both versions. Also, I do not know how to compile cores myself, as I am still new to this kind of scene. Unless there's some kind of guide out there that I can use?

I've tested:

- PCSX ReARMed and Beetle PSX cores, they will not load ISO files (or EBOOT files).
- PPSSPP core will crash/freeze RetroArch when loading ISO files.
- Snes9x core seem to be able to load a ROM file just fine now.
- The new core, Play!, also crash/freeze RetroArch when loading ISO files. (Might because that it runs only on Windows, Linux, and Android for now)

**Comment by twinaphex** [comment]
The Play core doesnt work yet on Mac.

**Comment by CatGreen90** [comment]
Make sure you're using the interpreter version of PCSX ReARMed; the dynarec is ARM-only. Also, the Metal build no longer includes a GL driver, so PPSSPP, Play!, and the HW version of Beetle PSX won't work on it.

**Comment by firelad97** [comment]
Using standalone versions of PPSSPP, Play!, and PCSX-R works pretty well on my MacBook, even if I'm on Metal build. It seem to still have OpenGL drivers, although Catalina do not. Like how Mojave is the last OS to allow 32-bit applications, it might be also the one to allow OpenGL drivers as well.

I might be completely wrong about drivers, although standalone versions of PPSSPP and PCSX-R are showing "OpenGL" in the backend/graphic options. Yet they work on Mojave and not on Catalina.

**Comment by zlib** [comment]
I have the same experience as @firelad97 with Metal version of RetroArch on iMac 2015 under macOS 10.14.5.
I tried interpreter version of PCSX ReARMed as well. The result is RetroArch freezes.

**Comment by cold-brewed** [comment]
The issue isn't that the OS doesn't have OpenGL - the RetroArch Metal version doesn't have a GL driver included. If you try to open a core that requires GL it will likely freeze or crash.

In order to run a GL core you'll need to run the non-Metal version of RetroArch. That being said, I was able to open a PSX game with PCSX ReARMed and Beetle PSX (non-HW) using the Metal version.

**Comment by CatGreen90** [comment]
Missing/incorrect BIOS or bad dumps are more likely to be the cause. The only core I know of that doesn't work with Mojave is Mesen, which only works with Sierra (or earlier, presumably) for some reason.

**Comment by firelad97** [comment]
Another update.

I switched to intel version of RetroArch, most cores seems to be working, although it seems to be almost opposite from metal version. PCSX ReARMed interpreter core does not work anymore, with or without bios files. PPSSPP cores still do not work. ParaLLEI N64 is the only available n64 core for macOS for some reason, and does not work either.

Another thing. This is very confusing, as when I did some research on some of libretro cores, some of them seem to be not available for macOS or iOS, mostly only for Windows, Linux, and Android. With lack of cores for macOS/iOS, this needs to be brought to the light. Especially PSP, PS1, N64 and probably a few other emulations. Seriously.

The only real workaround to is use standalone versions that already exist on macOS.

**Comment by CatGreen90** [comment]
"intel version"? Do you mean the GL version? Also, try this:
Go to ~/Library/Application Support/RetroArch, open retroarch.cfg in the text editor of your choice (I use BBEdit), and, if you see `video_shader = ":/Contents/Resources/shaders/retroarch.slangp"`, delete everything inside the quotation marks.

**Comment by firelad97** [comment]
<img width="564" alt="Screen Shot 2019-07-19 at 5 39 30 PM" src="https://user-images.githubusercontent.com/10987201/61567038-31b9b000-aa4c-11e9-95ff-ffea28f07a3e.png">
Not “GL”, but “Intel” version as it is shown on RetroArch download page.

My retroarch.cfg only shows `video_shader = “”`.

**Comment by CatGreen90** [comment]
That's the GL version, which (like the Metal version) is for Macs with Intel processors; older Macs (from 2005 and earlier) had PowerPC processors.

**Comment by cold-brewed** [comment]
When you say that some cores are not available for macOS, could you explain that? Do you mean they are not available though the online updater, or they do not run, or something else?

MacOS is particularly challenging with the GL cores. Apple has deprecated GL support (it still technically works, but is running an old version) which makes for some difficulties in getting GL and Metal working in the same bundle. That's why there are two different macOS releases (Metal and GL). Unfortunately our hands are a bit tied here due to the old GL versions included with macOS and the lack of support from Apple due to the deprecation of GL.

This is further made difficult with the aforementioned GL-only cores because they won't work with the Metal bundle, which doesn't include the GL driver, which is required by the GL-only cores.

**Comment by firelad97** [comment]
> When you say that some cores are not available for macOS, could you explain that? Do you mean they are not available though the online updater, or they do not run, or something else?

I’m saying that there are posts posted by RetroArch on their blog, for example:
Play! core is only available for Windows and Linux. (Someone here even mentioned that it does not work on macOS yet.)

In other words, yes they’re always available through the online updater, and yet they don’t work. You are correct about Apple deprecating GL support, although OpenGL 4.1 *should* work with GL-only cores. And yet they don’t. :) Yes, my Mac has OpenGL 4.1.
