### ISSUE TITLE
[Android] RetroArch crashes when trying to access Quick Menu

### ISSUE THREAD

**Issue by extrem9** [libretro/RetroArch#9066]
## Description

RetroArch crashes when trying to access Quick Menu while gaming. Sometimes RetroArch crashes at start-up.

### Expected behavior

Access to Quick Menu to Save\Load, manage Core Options, enable Shaders, etc.

### Actual behavior

RetroArch crashes with "Error" message to default Android menu.

### Steps to reproduce the bug

1. Launch RetroArch (sometimes crashes at launch).
2. Load any content with any core.
3. Play for some seconds.
4. Press "Quick Menu" hotkey.
5. RetroArch crashes.

### Bisect Results

Fresh install after deleting previous RetroArch version (1.7.6). Previous versions worked fine.

### Version/Commit

- RetroArch: 1.7.7 (Git 89461bb)

### Environment information
- Device: JXD S7800B
- OS: Android 4.4.4

[retroarch__2019_05_21__16_15_32.log](https://github.com/libretro/RetroArch/files/3364592/retroarch__2019_05_21__16_15_32.log)

**Comment by SaucySarah** [comment]
This looks like the same problem that I reported about 5 weeks ago https://github.com/libretro/RetroArch/issues/8878 . Unfortunately they still haven't looked into it.

**Comment by SaucySarah** [comment]
I just tried the latest nightly 32-bit version `2019-07-07-RetroArch_ra32.apk` and it won't even run. It crashes when pressing the icon.

Nvidia Tegra Note 7
Android 4.4.2
armabi-v7a

[log.txt](https://github.com/libretro/RetroArch/files/3365802/log.txt)

**Comment by twinaphex** [comment]
This is due to us having to make internal changes so that RetroArch is ready for 32bit/64bit publishing that will be required soon.

Anyway, we hope this PR will fix it -

https://github.com/libretro/RetroArch/pull/9075

**Comment by SaucySarah** [comment]
It runs now but still crashes when entering/exiting the Quick Menu.

**Comment by extrem9** [comment]
Tested latest available nightly build RetroArch 1.7.7 (Git 12bf049) - same problem.
Attached zipped _logcat.txt_ and _retroarch__2019_07_10__17_01_34.log_ .
[logcat.zip](https://github.com/libretro/RetroArch/files/3377331/logcat.zip)
[retroarch__2019_07_10__17_01_34.zip](https://github.com/libretro/RetroArch/files/3377332/retroarch__2019_07_10__17_01_34.zip)

**Comment by MajorWilly** [comment]
I think this may be fixed now. I tried the latest Nightly Build (30th July), tried several cores and roms and haven't had any crashes yet ! @twinaphex Can you confirm that you did some work for this bug or has it automagically been fixed from a different commit ?

**Comment by twinaphex** [comment]
Yes, I ran older Android devices through a debugger and found a few instances that could lead to a crash, so I fixed them.

**Comment by MajorWilly** [comment]
@twinaphex Thankyou !

**Comment by extrem9** [comment]
RetroArch 1.7.8 works fine. Thank you very much!
