### ISSUE TITLE
3ds: proposal to update the assets of the 3ds port.

### ISSUE THREAD

**Issue by SpardaXV** [libretro/RetroArch#9068]
Sorry to put this here, but I did not know how to propose the change of assets in the RetroArch / pkg / ctr / assets / address and be able to offer a view of the new ones.

Since the performance of retroarch I liked so much in version 1.7.7, I have encouraged to make some new banners and icons for the cores that work best. In 3ds, due to its low power, the xmb menu doesn't work well and therefore you can not use the assets to give a better finish to the user experience with Retroarch. So, I have created these new banners that give a more "nostalgic" touch, also, I have made new icons for the consoles, I think the complete controllers are more recognizable than the buttons.

All the banners and icons are made with a mix of assets from the themes of the xmb menu, so the most difficult work to reproduce the consoles in pixels is from the community, thanks to all of them.

Next I upload the files, if you see them well, I would like them to upload 3ds assets replacing the existing, however, I put it to debate, if you don't like the banners, icons, or both, it is left as they are .

(DELETED)

**Comment by twinaphex** [comment]
I'll let @jdgleaver be the judge here.

**Comment by jdgleaver** [comment]
Hmm...

I agree that the current 3DS banner artwork is a bit of an inconsistent jumble, and we should probably try to unify it.

Personally, I favour banners with clear libretro branding, and the core name in an appropriate font - sort of like this:

![pokemini_banner](https://user-images.githubusercontent.com/38211560/60798789-c0cfe980-a169-11e9-88b5-15640d9c437a.png)
![prboom_banner](https://user-images.githubusercontent.com/38211560/60798811-cc231500-a169-11e9-9e0b-0a771ad05e05.png)

...but I'm really not fussy about it, and those new banners are very nice. So I would have no objection at all to adding @SpardaXV's banner images to the repo. The only question is - do we want to go ahead and make *all* the banners follow this pattern? And should we do it in one go? Or do we add these for now, and hope that someone fixes the others later...?  :)

As for the new icons... Having a complete controller image is fine, but I don't like the current presentation - it's mostly the thick vivid border that looks off to me. @SpardaXV would you be willing to have a go at redoing your icons, maybe using the same kind of backgrounds that you have in the banner images? (Maybe with a lower brightness, so the controller stands out?) I think that would unify things quite nicely.

**Comment by SpardaXV** [comment]
You're right, @jdgleaver, the icons did not finish convincing me.

I changed them and I made some new banners. In the case that we continue with this, I can do them all. I think that the visualization of the system is very graphic and useful for the banner, however, I can add the logo of "libRetro", I haven't put it for not saturating the screen with logos. Here we go again:

![genesis_plus_gx](https://user-images.githubusercontent.com/47571088/60827965-a3bf0900-a1b1-11e9-8ef3-c3991cc6cb5e.png)
![genesis_plus_gx_banner](https://user-images.githubusercontent.com/47571088/60827966-a4579f80-a1b1-11e9-879b-8771ac937df1.png)
![gpsp](https://user-images.githubusercontent.com/47571088/60827967-a4579f80-a1b1-11e9-8f5a-6296726dc376.png)
![gpsp_banner](https://user-images.githubusercontent.com/47571088/60827968-a4579f80-a1b1-11e9-9795-aa7f75679cda.png)
![mame2000_banner](https://user-images.githubusercontent.com/47571088/60827969-a4579f80-a1b1-11e9-8d08-fba489ee0c8f.png)
![mame2003_banner](https://user-images.githubusercontent.com/47571088/60827970-a4f03600-a1b1-11e9-97fe-2c6355f5f377.png)
![nestopia](https://user-images.githubusercontent.com/47571088/60827971-a4f03600-a1b1-11e9-9514-b1e98e5109ac.png)
![nestopia_banner](https://user-images.githubusercontent.com/47571088/60827973-a4f03600-a1b1-11e9-9582-887595017a64.png)
![picodrive](https://user-images.githubusercontent.com/47571088/60827974-a588cc80-a1b1-11e9-832d-fc7a45676583.png)
![picodrive_banner](https://user-images.githubusercontent.com/47571088/60827975-a588cc80-a1b1-11e9-9a37-4350c5173a1d.png)
![pokemini](https://user-images.githubusercontent.com/47571088/60827976-a6216300-a1b1-11e9-8d57-094b35b17b95.png)
![pokemini_banner](https://user-images.githubusercontent.com/47571088/60827978-a6216300-a1b1-11e9-842e-2f7adc7d854d.png)
![prBOOM](https://user-images.githubusercontent.com/47571088/60827979-a6216300-a1b1-11e9-92e7-f9176114cc1e.png)
![prBOOM_banner](https://user-images.githubusercontent.com/47571088/60827980-a6b9f980-a1b1-11e9-9312-36753439562c.png)
![snes9x2002](https://user-images.githubusercontent.com/47571088/60827981-a6b9f980-a1b1-11e9-87fa-a1417791c979.png)
![snes9x2002_banner](https://user-images.githubusercontent.com/47571088/60827982-a6b9f980-a1b1-11e9-921e-606b5bd51e8f.png)
![snes9x2005](https://user-images.githubusercontent.com/47571088/60827983-a7529000-a1b1-11e9-9e23-f4d9096f23dd.png)
![snes9x2005_banner](https://user-images.githubusercontent.com/47571088/60827984-a7eb2680-a1b1-11e9-8f43-d94ea3c41008.png)
![fbalpha2012_cps1_banner](https://user-images.githubusercontent.com/47571088/60827986-a7eb2680-a1b1-11e9-9e09-883d804f3c77.png)
![fbalpha2012_cps2_banner](https://user-images.githubusercontent.com/47571088/60827988-a883bd00-a1b1-11e9-95d8-d13808ad7413.png)
![fbalpha2012_neogeo](https://user-images.githubusercontent.com/47571088/60827990-a883bd00-a1b1-11e9-8248-af11ebf09fbb.png)
![fbalpha2012_neogeo_banner](https://user-images.githubusercontent.com/47571088/60827991-a883bd00-a1b1-11e9-99d9-f5cc8745f5a6.png)
![fceumm](https://user-images.githubusercontent.com/47571088/60827992-a91c5380-a1b1-11e9-82e3-83996d2fdf1f.png)
![fceumm_banner](https://user-images.githubusercontent.com/47571088/60827994-a91c5380-a1b1-11e9-99ea-3bfc1ebf1b7c.png)
![gambatte](https://user-images.githubusercontent.com/47571088/60827995-a91c5380-a1b1-11e9-8af6-248858423ef9.png)
![gambatte_banner](https://user-images.githubusercontent.com/47571088/60827996-a9b4ea00-a1b1-11e9-8496-1a690a715bc7.png)

All of them are open to any suggestion

**Comment by SpardaXV** [comment]
The semi-transparent gradient doesntt work well on the icons when the background is dark, I will try to achieve the same result with an opaque gradient

**Comment by SpardaXV** [comment]
I have taken a while to fix the ones I went up before, now, complete pack with icon arrangements and more accurate color:

![fbalpha2012_cps1_banner](https://user-images.githubusercontent.com/47571088/60843005-bf3c0b00-a1d5-11e9-817a-0050d0b02990.png)
![fbalpha2012_cps2_banner](https://user-images.githubusercontent.com/47571088/60843007-bf3c0b00-a1d5-11e9-8813-97358e228b02.png)
![fbalpha2012_neogeo](https://user-images.githubusercontent.com/47571088/60843009-bf3c0b00-a1d5-11e9-8506-6de7aa872b23.png)
![fbalpha2012_neogeo_banner](https://user-images.githubusercontent.com/47571088/60843010-bf3c0b00-a1d5-11e9-8ba3-f2ba2e60c8c1.png)
![fceumm](https://user-images.githubusercontent.com/47571088/60843012-bfd4a180-a1d5-11e9-861f-eceff859bc3f.png)
![fceumm_banner](https://user-images.githubusercontent.com/47571088/60843014-c06d3800-a1d5-11e9-9e52-31017a45f3d7.png)
![gambatte](https://user-images.githubusercontent.com/47571088/60843016-c06d3800-a1d5-11e9-889e-aaacd6449810.png)
![gambatte_banner](https://user-images.githubusercontent.com/47571088/60843017-c06d3800-a1d5-11e9-9d45-3dc5dabc7220.png)
![genesis_plus_gx](https://user-images.githubusercontent.com/47571088/60843019-c105ce80-a1d5-11e9-84cb-4b715787374e.png)
![genesis_plus_gx_banner](https://user-images.githubusercontent.com/47571088/60843020-c105ce80-a1d5-11e9-9581-1a2c1e064db0.png)
![gpsp](https://user-images.githubusercontent.com/47571088/60843021-c105ce80-a1d5-11e9-8a2d-f3d9106361e5.png)
![gpsp_banner](https://user-images.githubusercontent.com/47571088/60843022-c19e6500-a1d5-11e9-8b43-552a6480e835.png)
![mame2000_banner](https://user-images.githubusercontent.com/47571088/60843024-c19e6500-a1d5-11e9-8a71-aeef6eb8d6c5.png)
![mame2003_banner](https://user-images.githubusercontent.com/47571088/60843025-c236fb80-a1d5-11e9-8aa3-0edd6bc36d42.png)
![nestopia](https://user-images.githubusercontent.com/47571088/60843026-c236fb80-a1d5-11e9-818d-5e1840391c65.png)
![nestopia_banner](https://user-images.githubusercontent.com/47571088/60843027-c2cf9200-a1d5-11e9-8758-bd86a53225bc.png)
![picodrive](https://user-images.githubusercontent.com/47571088/60843028-c2cf9200-a1d5-11e9-90a1-d1b89f250758.png)
![picodrive_banner](https://user-images.githubusercontent.com/47571088/60843030-c2cf9200-a1d5-11e9-88de-74ca6ae99c12.png)
![pokemini](https://user-images.githubusercontent.com/47571088/60843031-c3682880-a1d5-11e9-980e-a10e9426dd60.png)
![pokemini_banner](https://user-images.githubusercontent.com/47571088/60843032-c3682880-a1d5-11e9-848f-bb0f0c2c09e6.png)
![prBOOM](https://user-images.githubusercontent.com/47571088/60843033-c3682880-a1d5-11e9-9a0a-a2e1321f09f5.png)
![prBOOM_banner](https://user-images.githubusercontent.com/47571088/60843034-c400bf00-a1d5-11e9-8fe6-4b86a7084a52.png)
![snes9x2002](https://user-images.githubusercontent.com/47571088/60843036-c400bf00-a1d5-11e9-92a3-f88cfaae3888.png)
![snes9x2002_banner](https://user-images.githubusercontent.com/47571088/60843037-c400bf00-a1d5-11e9-89c0-604dc232afad.png)
![snes9x2005](https://user-images.githubusercontent.com/47571088/60843039-c4995580-a1d5-11e9-9ee7-9686ac974768.png)
![snes9x2005_banner](https://user-images.githubusercontent.com/47571088/60843041-c4995580-a1d5-11e9-9b6b-3b195e716954.png)

**Comment by jdgleaver** [comment]
@SpardaXV Hey, nice work! These are great - I think we can certainly move ahead with making this the official artwork. Thank you also for offering to tackle the complete set of cores - we've needed this sort of unification for quite a while now.

I agree with you regarding the icons - I think they should indeed occupy the full 48x48 area without transparency. I'll look forward to the update.

Also, could you just confirm that none of the source images have usage restrictions? Everything that you've taken from the existing RetroArch repos is of course fine, as is anything you're made yourself - but we just need to make sure we're not distributing anything that could trigger a copyright takedown.

Anyway, once you're happy with the first batch of images, could you please post them in a zip file? I'll then submit them as a PR (unless you want to do this yourself...?). We can then continue to update the rest as and when you find time/motivation  :)

**Comment by SpardaXV** [comment]
Well, last preview.

On the subject of copyright, the only ones that could give problems are the "doomguy" and the "pokeball", the "doomguy" in principle on the web said it is free to use (but I do not know if the art of doom can belong to ID software ...), and about the "pokeball", I had my doubts, so I drew a new one that I think is not bad.

I'll be adding more every day (or almost, I'll try)

Here the previews and first pack in .zip:

[3dsAssets1Pack.zip](https://github.com/libretro/RetroArch/files/3375262/3dsAssets1Pack.zip)
![fbalpha2012_banner](https://user-images.githubusercontent.com/47571088/60931724-123bbe00-a2bb-11e9-8b7a-88f5c5bd5b95.png)
![fbalpha2012_cps1_banner](https://user-images.githubusercontent.com/47571088/60931725-123bbe00-a2bb-11e9-828f-568b704b5f18.png)
![fbalpha2012_cps2_banner](https://user-images.githubusercontent.com/47571088/60931726-12d45480-a2bb-11e9-962f-bb97d28b0971.png)
![fbalpha2012_cps3_banner](https://user-images.githubusercontent.com/47571088/60931727-12d45480-a2bb-11e9-9841-d78b669dcc63.png)
![fbalpha2012_neogeo](https://user-images.githubusercontent.com/47571088/60931728-12d45480-a2bb-11e9-84f2-8e05fad8e8ef.png)
![fbalpha2012_neogeo_banner](https://user-images.githubusercontent.com/47571088/60931729-12d45480-a2bb-11e9-8a69-a48c88bb4fc6.png)
![fceumm](https://user-images.githubusercontent.com/47571088/60931730-136ceb00-a2bb-11e9-8c47-b7c867a5fe83.png)
![fceumm_banner](https://user-images.githubusercontent.com/47571088/60931735-14058180-a2bb-11e9-9dcd-1c5cffaf15e6.png)
![gambatte](https://user-images.githubusercontent.com/47571088/60931736-149e1800-a2bb-11e9-9fbc-32ba687e0dce.png)
![gambatte_banner](https://user-images.githubusercontent.com/47571088/60931737-149e1800-a2bb-11e9-94df-c124371e3d66.png)
![genesis_plus_gx](https://user-images.githubusercontent.com/47571088/60931738-1536ae80-a2bb-11e9-8ea9-706b376c2515.png)
![genesis_plus_gx_banner](https://user-images.githubusercontent.com/47571088/60931740-1536ae80-a2bb-11e9-996c-32b0a5ce3c5b.png)
![gpsp](https://user-images.githubusercontent.com/47571088/60931741-1536ae80-a2bb-11e9-9eeb-b8bb9ea5f252.png)
![gpsp_banner](https://user-images.githubusercontent.com/47571088/60931743-15cf4500-a2bb-11e9-8dff-cff097edb9b3.png)
![mame2000_banner](https://user-images.githubusercontent.com/47571088/60931744-1667db80-a2bb-11e9-82b5-f9f809d5ac64.png)
![mame2003_banner](https://user-images.githubusercontent.com/47571088/60931745-1667db80-a2bb-11e9-9ae8-533d0a7e8ddb.png)
![mame2003_plus_banner](https://user-images.githubusercontent.com/47571088/60931746-1667db80-a2bb-11e9-9927-47a97ae196f0.png)
![mednafen_wswan](https://user-images.githubusercontent.com/47571088/60931747-1667db80-a2bb-11e9-9b04-3307b5675636.png)
![mednafen_wswan_banner](https://user-images.githubusercontent.com/47571088/60931748-17007200-a2bb-11e9-8d53-e1e29ee8c2bd.png)
![nestopia](https://user-images.githubusercontent.com/47571088/60931749-17007200-a2bb-11e9-8a1f-b9c459bb8857.png)
![nestopia_banner](https://user-images.githubusercontent.com/47571088/60931750-17007200-a2bb-11e9-8c08-c009ec1c2c93.png)
![picodrive](https://user-images.githubusercontent.com/47571088/60931751-17990880-a2bb-11e9-84f2-185d2b9720ec.png)
![picodrive_banner](https://user-images.githubusercontent.com/47571088/60931752-17990880-a2bb-11e9-8d99-6fa569348946.png)
![pokemini](https://user-images.githubusercontent.com/47571088/60931753-17990880-a2bb-11e9-9dac-b99e5af14a80.png)
![pokemini_banner](https://user-images.githubusercontent.com/47571088/60931754-18319f00-a2bb-11e9-825b-9d3342c669d1.png)
![prBOOM](https://user-images.githubusercontent.com/47571088/60931755-18319f00-a2bb-11e9-86d4-2da2f0afb84f.png)
![prBOOM_banner](https://user-images.githubusercontent.com/47571088/60931756-18319f00-a2bb-11e9-84f3-8acc22fcd977.png)
![quicknes](https://user-images.githubusercontent.com/47571088/60931757-18ca3580-a2bb-11e9-988c-3f0d598bc9b1.png)
![quicknes_banner](https://user-images.githubusercontent.com/47571088/60931758-18ca3580-a2bb-11e9-8b76-a0c265a654bb.png)
![snes9x2002](https://user-images.githubusercontent.com/47571088/60931759-18ca3580-a2bb-11e9-9048-78f9d75b7e85.png)
![snes9x2002_banner](https://user-images.githubusercontent.com/47571088/60931760-1962cc00-a2bb-11e9-81e8-cbb10fe6834f.png)
![snes9x2005](https://user-images.githubusercontent.com/47571088/60931763-1962cc00-a2bb-11e9-9d92-58b901cd9124.png)
![snes9x2005_banner](https://user-images.githubusercontent.com/47571088/60931764-1962cc00-a2bb-11e9-937c-a1aa60bdda97.png)
![snes9x2010](https://user-images.githubusercontent.com/47571088/60931765-19fb6280-a2bb-11e9-873c-56b9bc7ed3c3.png)
![snes9x2010_banner](https://user-images.githubusercontent.com/47571088/60931723-11a32780-a2bb-11e9-8568-49b902fb4d5e.png)

**Comment by jdgleaver** [comment]
@SpardaXV Awesome. Thanks for redoing the pokeball, and I think you're correct regarding the doomguy (we already have that face image in the shader previews repo)

The more I look at these images, the more I like them  :)

I'll go ahead and put this first batch into a PR.

**Comment by SpardaXV** [comment]
Well, this message will be edited every day to put in preview what is finished, so you can make suggestions about the new thing that I am adding. In principle with a few more I will do a the pack2 (there are some corrections of the first pack), and my intention is that the third pack is small and finalizes the collection. Right now there must already be 2/3 of the total.

![4do](https://user-images.githubusercontent.com/47571088/61013325-8725fb00-a382-11e9-8d42-ede7623259ae.png)
![4do_banner](https://user-images.githubusercontent.com/47571088/61013327-8725fb00-a382-11e9-8ded-3d23d8ce076a.png)
![2048_banner](https://user-images.githubusercontent.com/47571088/61013328-87be9180-a382-11e9-8cbd-e12532c673e8.png)
![gw](https://user-images.githubusercontent.com/47571088/61013329-87be9180-a382-11e9-8d89-c5b8d7ab4695.png)
![gw_banner](https://user-images.githubusercontent.com/47571088/61013330-87be9180-a382-11e9-9345-aa51994f2c9f.png)
![handy](https://user-images.githubusercontent.com/47571088/61013331-88572800-a382-11e9-881c-67a85260c694.png)
![handy_banner](https://user-images.githubusercontent.com/47571088/61013333-88572800-a382-11e9-8db8-9bc25c48ab6b.png)
![mednafen_ngp](https://user-images.githubusercontent.com/47571088/61013334-88572800-a382-11e9-92d0-348d6bd8d03f.png)
![mednafen_ngp_banner](https://user-images.githubusercontent.com/47571088/61013335-88efbe80-a382-11e9-8b1f-57930765bb2c.png)
![mednafen_pce_fast](https://user-images.githubusercontent.com/47571088/61013336-88efbe80-a382-11e9-91c1-8657fc593584.png)
![mednafen_pce_fast_banner](https://user-images.githubusercontent.com/47571088/61013337-88efbe80-a382-11e9-8c4c-b28aa4872409.png)
![mednafen_vb](https://user-images.githubusercontent.com/47571088/61013338-89885500-a382-11e9-95f5-8d4e3a719623.png)
![mednafen_vb_banner](https://user-images.githubusercontent.com/47571088/61013339-89885500-a382-11e9-84c5-5a5aca85b9f6.png)
![mednafen_wswan_banner](https://user-images.githubusercontent.com/47571088/61013340-89885500-a382-11e9-9863-1bad8d471e58.png)
![mgba](https://user-images.githubusercontent.com/47571088/61013341-8a20eb80-a382-11e9-88d8-3848ccbc3b32.png)
![mgba_banner](https://user-images.githubusercontent.com/47571088/61013343-8a20eb80-a382-11e9-89d8-e9fbb90174de.png)
![nekop2](https://user-images.githubusercontent.com/47571088/61013344-8ab98200-a382-11e9-80be-355db81097a8.png)
![nekop2_banner](https://user-images.githubusercontent.com/47571088/61013345-8ab98200-a382-11e9-8832-197e31c7e0c7.png)
![np2kai](https://user-images.githubusercontent.com/47571088/61013346-8b521880-a382-11e9-9d13-84f32f87b390.png)
![np2kai_banner](https://user-images.githubusercontent.com/47571088/61013347-8b521880-a382-11e9-9d41-dc885c94c348.png)
![nxengine_banner](https://user-images.githubusercontent.com/47571088/61013349-8b521880-a382-11e9-81fd-141c652e4445.png)
![o2em](https://user-images.githubusercontent.com/47571088/61013350-8beaaf00-a382-11e9-9da4-c1c769cb80cd.png)
![o2em_banner](https://user-images.githubusercontent.com/47571088/61013351-8beaaf00-a382-11e9-8570-ead1a8027d5b.png)
![pcsx_rearmed](https://user-images.githubusercontent.com/47571088/61013352-8beaaf00-a382-11e9-94e1-3d43933ea5e1.png)
![pcsx_rearmed_banner](https://user-images.githubusercontent.com/47571088/61013353-8c834580-a382-11e9-9da4-f8e9ef9c020c.png)
![snes9x2005_plus](https://user-images.githubusercontent.com/47571088/61013355-8c834580-a382-11e9-86ef-98e380e72978.png)
![snes9x2005_plus_banner](https://user-images.githubusercontent.com/47571088/61013356-8c834580-a382-11e9-8b51-eab5ba612e1f.png)

**Comment by jdgleaver** [comment]
@SpardaXV These keep getting better! Excellent work  :)

**Comment by SpardaXV** [comment]
Thanks @jdgleaver, for me it is a pleasure to be able to collaborate even if it is with little.

Finally, it won't take a pack3, they are all finished, it hasn't been so difficult. The icons of the Arcade and some specific core I have not changed them because I look good. I leave the second pack, which completes the total, and also the preview in case someone wants to say something.

[3dsAssets2Pack.zip](https://github.com/libretro/RetroArch/files/3383892/3dsAssets2Pack.zip)
![4do](https://user-images.githubusercontent.com/47571088/61084459-58fdf500-a42e-11e9-9514-da187f8ee6d4.png)
![4do_banner](https://user-images.githubusercontent.com/47571088/61084461-58fdf500-a42e-11e9-8d24-f7fd5602e971.png)
![81](https://user-images.githubusercontent.com/47571088/61084462-58fdf500-a42e-11e9-9e49-e9e981a1b107.png)
![81_banner](https://user-images.githubusercontent.com/47571088/61084463-59968b80-a42e-11e9-971b-874f4064b61c.png)
![2048_banner](https://user-images.githubusercontent.com/47571088/61084465-5a2f2200-a42e-11e9-97f1-6b30b52c01dc.png)
![atari800](https://user-images.githubusercontent.com/47571088/61084466-5a2f2200-a42e-11e9-8d59-fa352c65198b.png)
![atari800_banner](https://user-images.githubusercontent.com/47571088/61084467-5a2f2200-a42e-11e9-8477-fa869f1cdb14.png)
![dosbox_banner](https://user-images.githubusercontent.com/47571088/61084468-5ac7b880-a42e-11e9-924b-f68b1ecbddb3.png)
![fmsx](https://user-images.githubusercontent.com/47571088/61084469-5ac7b880-a42e-11e9-8a59-e77d47ef38c7.png)
![fmsx_banner](https://user-images.githubusercontent.com/47571088/61084470-5b604f00-a42e-11e9-9934-58f5b8a7a959.png)
![freeintv](https://user-images.githubusercontent.com/47571088/61084471-5b604f00-a42e-11e9-90a9-e3883315f963.png)
![freeintv_banner](https://user-images.githubusercontent.com/47571088/61084472-5bf8e580-a42e-11e9-9f0f-0da0dc06f51a.png)
![fuse](https://user-images.githubusercontent.com/47571088/61084474-5c917c00-a42e-11e9-8090-8c952ee6f7e8.png)
![fuse_banner](https://user-images.githubusercontent.com/47571088/61084475-5c917c00-a42e-11e9-8f42-223ac4ec5154.png)
![gw](https://user-images.githubusercontent.com/47571088/61084476-5d2a1280-a42e-11e9-805f-009c01830164.png)
![gw_banner](https://user-images.githubusercontent.com/47571088/61084477-5d2a1280-a42e-11e9-874a-05d73b6ea2d5.png)
![handy](https://user-images.githubusercontent.com/47571088/61084479-5d2a1280-a42e-11e9-82c1-a6e5d4c61bed.png)
![handy_banner](https://user-images.githubusercontent.com/47571088/61084480-5dc2a900-a42e-11e9-984f-352a619e99fb.png)
![mednafen_ngp](https://user-images.githubusercontent.com/47571088/61084481-5dc2a900-a42e-11e9-80f4-512d15d6729b.png)
![mednafen_ngp_banner](https://user-images.githubusercontent.com/47571088/61084482-5dc2a900-a42e-11e9-82e1-e163d3e59643.png)
![mednafen_pce_fast](https://user-images.githubusercontent.com/47571088/61084483-5e5b3f80-a42e-11e9-9bc1-461b10842693.png)
![mednafen_pce_fast_banner](https://user-images.githubusercontent.com/47571088/61084484-5e5b3f80-a42e-11e9-8361-ddcec0ab766c.png)
![mednafen_vb](https://user-images.githubusercontent.com/47571088/61084485-5e5b3f80-a42e-11e9-8a78-83aa8a25c06c.png)
![mednafen_vb_banner](https://user-images.githubusercontent.com/47571088/61084486-5e5b3f80-a42e-11e9-850e-7079edddae0f.png)
![mednafen_wswan_banner](https://user-images.githubusercontent.com/47571088/61084487-5ef3d600-a42e-11e9-999f-9cf534a475ad.png)
![mgba](https://user-images.githubusercontent.com/47571088/61084488-5ef3d600-a42e-11e9-9801-6df21bfed79d.png)
![mgba_banner](https://user-images.githubusercontent.com/47571088/61084490-5f8c6c80-a42e-11e9-80bb-cf60bc1ef052.png)
![nekop2](https://user-images.githubusercontent.com/47571088/61084491-5f8c6c80-a42e-11e9-9a37-a8de89fc86b9.png)
![nekop2_banner](https://user-images.githubusercontent.com/47571088/61084492-5f8c6c80-a42e-11e9-9ce5-4ce4d701725b.png)
![np2kai](https://user-images.githubusercontent.com/47571088/61084493-60250300-a42e-11e9-8cde-ba064b2cdf79.png)
![np2kai_banner](https://user-images.githubusercontent.com/47571088/61084494-60250300-a42e-11e9-8433-92d491518b74.png)
![nxengine_banner](https://user-images.githubusercontent.com/47571088/61084495-60250300-a42e-11e9-82b9-5c48eedb20bd.png)
![o2em](https://user-images.githubusercontent.com/47571088/61084496-60bd9980-a42e-11e9-8320-e866e57387cf.png)
![o2em_banner](https://user-images.githubusercontent.com/47571088/61084498-60bd9980-a42e-11e9-95bd-693c3ef975da.png)
![pcsx_rearmed](https://user-images.githubusercontent.com/47571088/61084500-61563000-a42e-11e9-8377-7a32d921f142.png)
![pcsx_rearmed_banner](https://user-images.githubusercontent.com/47571088/61084501-61563000-a42e-11e9-9bf0-bc8a66ba3679.png)
![prosystem](https://user-images.githubusercontent.com/47571088/61084502-61563000-a42e-11e9-8a5a-04f04dd319a1.png)
![prosystem_banner](https://user-images.githubusercontent.com/47571088/61084503-61eec680-a42e-11e9-8d1b-42408fef19f8.png)
![snes9x2005_plus](https://user-images.githubusercontent.com/47571088/61084505-61eec680-a42e-11e9-846d-e6d61959bbfb.png)
![snes9x2005_plus_banner](https://user-images.githubusercontent.com/47571088/61084506-61eec680-a42e-11e9-9f77-0f0d46b42389.png)
![stella](https://user-images.githubusercontent.com/47571088/61084507-62875d00-a42e-11e9-80a5-b0b8000a2b39.png)
![stella_banner](https://user-images.githubusercontent.com/47571088/61084508-62875d00-a42e-11e9-9057-1fcbeb541b14.png)
![vecx](https://user-images.githubusercontent.com/47571088/61084510-62875d00-a42e-11e9-9103-34c911a2ae8c.png)
![vecx_banner](https://user-images.githubusercontent.com/47571088/61084512-631ff380-a42e-11e9-8883-4ceea87afbc8.png)
![virtualjaguar](https://user-images.githubusercontent.com/47571088/61084513-631ff380-a42e-11e9-9336-a6d104e28b58.png)
![virtualjaguar_banner](https://user-images.githubusercontent.com/47571088/61084515-631ff380-a42e-11e9-9e21-ebb3ed6e6f1c.png)
![yabause](https://user-images.githubusercontent.com/47571088/61084517-63b88a00-a42e-11e9-84e3-68d1e40a8b03.png)
![yabause_banner](https://user-images.githubusercontent.com/47571088/61084518-63b88a00-a42e-11e9-9177-e57a9243cd60.png)

**Comment by jdgleaver** [comment]
@SpardaXV Thank you so much for these. We really appreciate your work! The 3DS port has needed this kind of polishing for a long time now - you've added a real touch of class :)

I'll make a PR with these new images right away.

Would it be okay to make requests for other cores in the future? I have plans to try and get at least a couple more working on 3DS (eventually...) - it would be great to maintain this high quality standard of artwork.

**Comment by SpardaXV** [comment]
Thanks @jdgleaver, I truly believe that this project deserves it, for me, retroarch is a must in my 3ds, and it is all thanks to the great work that all the developers do in this project.

Of course, you can count on me for the creation of new cores, whenever it is called I will appear, sooner or later depending on whether I have more or less work, but I will appear, I am becoming "addicted" to observe the retroarch github. Likewise, when users try the new nightlies, I will be attentive in case something should be changed.

Well, mission accomplished, for the moment we can close this.

**Comment by gingerbeardman** [comment]
Nice work on this!

I think there's still some inconsistencies but what we have now is the best it has ever been. And I say that as somebody who created a lot of the previous icons.

**Comment by gingerbeardman** [comment]
Currently missing icons:

- cap32
- FinalBurn Neo
- Mu
- QUASI88
- squirreljme
- Theodore

**Comment by SpardaXV** [comment]
@ About the authorship of the consoles images, in the first message I made it clear, it has always been my intention to be honest about it. All the artistic reproductions of the consoles have been a selection of the assets of the menu xmb in its different themes (neoactive, retrosystem etc). I did it before and I reiterate it now, thanks to the community and those who made them, they are great and represent the most complex work, so most of the merit that these banners and icons look good belongs to the community.

Precisely, the intention of all this is that the xmb menu may never work smoothly in 3ds due to the limitations of the device, so with these bannes and icons I try that the users of 3ds can enjoy the magnificent assets that retroarch contains (in fact, the launchers of each core are unnecessary, since in each one or in the main one of retroarch the rest can be loaded as well as the playlists of each system ... So it is only an aesthetic question for those who like to see the image of each console linked to its corresponding emulator).

Yesterday I took a while at night and made the banners that you indicate are missing, I leave them below. Now I am quite busy with work and I don't know if I will have made a mistake because they are systems that I barely know, so feel free to modify them or take from them what you need until they satisfy you. I didn't do these cores at the time because they weren't in the 3ds assets folder, so it will be necessary to modify the Makefile of each core to use the new images.


![Caprice32](https://user-images.githubusercontent.com/47571088/65468855-b1f1fc80-de65-11e9-99b6-deab248ac27f.png)
![Caprice32_banner](https://user-images.githubusercontent.com/47571088/65468856-b28a9300-de65-11e9-961c-a4bab921b160.png)
![FBNEO](https://user-images.githubusercontent.com/47571088/65468857-b28a9300-de65-11e9-8001-a4ed28200536.png)
![FBNEO_banner](https://user-images.githubusercontent.com/47571088/65468858-b28a9300-de65-11e9-9147-3dfbc12400f3.png)
![MU](https://user-images.githubusercontent.com/47571088/65468859-b28a9300-de65-11e9-81ad-3058fc545a05.png)
![MU_banner](https://user-images.githubusercontent.com/47571088/65468860-b3232980-de65-11e9-9c75-7373e74d828e.png)
![quasi88](https://user-images.githubusercontent.com/47571088/65468861-b3232980-de65-11e9-9e58-de6394aff8df.png)
![quasi88_banner](https://user-images.githubusercontent.com/47571088/65468862-b3232980-de65-11e9-96ad-fc560beca5fd.png)
![SquirrelJME](https://user-images.githubusercontent.com/47571088/65468863-b3232980-de65-11e9-9794-cb642956776d.png)
![SquirrelJME_banner](https://user-images.githubusercontent.com/47571088/65468864-b3bbc000-de65-11e9-9f7e-c4ed72821641.png)
![ThomsonMOTO](https://user-images.githubusercontent.com/47571088/65468865-b3bbc000-de65-11e9-8299-7b834053151d.png)
![ThomsonMOTO_banner](https://user-images.githubusercontent.com/47571088/65468866-b3bbc000-de65-11e9-8373-48e1336aad5d.png)

**Comment by gingerbeardman** [comment]
All looking good! Thanks for the explanation of the pixel art. Great work!
