### ISSUE TITLE
no input on ps2 controller that isnt the default controller (ps2 version of retroarch 1.7.7)

### ISSUE THREAD

**Issue by alfredox123** [libretro/RetroArch#9077]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

theres no input (neither in retroarch menu or in game) when using my Street Fighter 15th Anniversary PS2 Controller on ps2 retroarch, only works with default ps2 controller

### Expected behavior

my Street Fighter 15th Anniversary PS2 Controller should do the inputs either in retroarch menu or in game

### Actual behavior

no input at all with my Street Fighter 15th Anniversary PS2 Controller

### Steps to reproduce the bug

using my Street Fighter 15th Anniversary PS2 Controller makes no input, i think i could happen on other controllers that are not the ps2 default controllers

### Bisect Results

i just try it today and didnt work

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

- OS: PS2

**Comment by twinaphex** [comment]
Just to confirm, this only happens for non-standard PS2 controllers, right? So a regular second playre PS2 gamepad would work fine?

@fjtrujy Not sure if you have any such custom controllers.

**Comment by alfredox123** [comment]
right now i dont have another standard ps2 controller (maybe i could test in a few days with a friend ps2 controller), i only have 1 standard and 2 Street Fighter 15th Anniversary PS2 Controller.

- tested both Street Fighter 15th Anniversary PS2 Controller and neither worked (p1, p2)
- tested standard (p1) and Street Fighter 15th Anniversary PS2 Controller (p2) and only worked the standard one in retroarch menu and ingame
-tested Street Fighter 15th Anniversary PS2 Controller (p1) and standard (p2) and standard worked in game but not in retroarch menu (have to swap first to select game in retroarch menu then swap again in game to put standard on p2 slot)

**Comment by alfredox123** [comment]
today i test it with 2 standard controllers and they work as they should (both in game and menu), so the problem is with non standard ps2 controllers?

**Comment by alfredox123** [comment]
tested with 1.7.8 update and this problem still persist

**Comment by AKuHAK** [comment]
> tested with 1.7.8 update and this problem still persist

Could you test the latest nightly build? The problem should be solved now.

**Comment by AKuHAK** [comment]
@LibretroAdmin I think this can be closed now as support for digital pads were added times ago.
