### ISSUE TITLE
Dolphin core fails to load - libudev.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by realnc** [libretro/RetroArch#9085]
## Description

Trying to load the Dolphin code fails with the following error:

[ERROR] Failed to open libretro core: "/home/realnc/.var/app/org.libretro.RetroArch/config/retroarch/cores/dolphin_libretro.so"
[ERROR] Error(s): libudev.so.1: cannot open shared object file: No such file or directory
### Steps to reproduce the bug

1. Download the Dolphin core.
2. Try to load the core (Main Menu -> Load Core) or try to start a GameCube/Wii game.

### Version/Commit

Installed through flatpak (official flathub build.)

- RetroArch: 62da78c

### Environment information

- OS: Gentoo Linux 64-bit

**Comment by orbea** [comment]
The flatpak is missing udev. The easiest solution is to compile it yourself and don't use the flatpak.

Also wrong repo, try here instead.

https://github.com/libretro/dolphin/issues

**Comment by hizzlekizzle** [comment]
I think it's actually more appropriate to put the issue at the RetroArch flatpak packaging repo, but it seems someone has already done it:
https://github.com/flathub/org.libretro.RetroArch/issues/115
