### ISSUE TITLE
Autoconfig is required to use Left Analog stick to navigate the menu

### ISSUE THREAD

**Issue by OllieLollie1** [libretro/RetroArch#9089]
## Description

If autoconfig is turned off the left analog stick cannot be used to navigate the menu. In my case I was using a Dualshock 3 and turned autoconfig off and bound everything manually.

### Expected behavior

While autoconfig is off it is expected with everything bound that the left analog stick should behave like the dpad and allow you to navigate the RA menu.

### Actual behavior

Input on the left analog stick does nothing 

### Steps to reproduce the bug

1. Connect Dualshock 3 with autoconfig turned on
2. Turn autoconfig off
3. Bind everything manually
4. Left stick does nothing

### Bisect Results

[This was after I noticed the right dpad button was triggering the quick menu even with the quick menu trigger set to L3 + R3. So I turned autoconfig off and rebound everything and everything was working properly except the navigation of the RA menu using the Left Analog stick

@Awakened on the libretro discord mentioned in #retroarch that 
"There's a bug where if Input, Autoconfig is off, left stick doesn't work in the menu"
and I found that if I enabled it and rebooted that the behaviour of the stick was as expected.

After doing this it did only break one game that I noticed. Crash Bandicoot (USA) now doesn't accept any inputs. While the github says no Core / Game issues this may be relevant.

### Version/Commit

- RetroArch: 
[INFO] Version: 1.7.6
[INFO] Git: ed5bd80

### Environment information

- OS: Lakka
- Device: Odroid XU4

**Comment by Awakened0** [comment]
Similar (same?) issue: https://github.com/libretro/RetroArch/issues/8192

**Comment by orbea** [comment]
Can you try RetroArch 1.7.7?

Can you bisect this issue?

**Comment by OllieLollie1** [comment]
Until Lakka has access to RetroArch 1.7.7 I can't test it and I don't understand what you mean by bisect this issue with git.

**Comment by orbea** [comment]
https://git-scm.com/docs/git-bisect
