### ISSUE TITLE
[Linux] Build broken on Fedora / RHEL

### ISSUE THREAD

**Issue by s3gfaultx** [libretro/RetroArch#9096]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When compiling on Fedora / RHEL -- build fails with the following:
CC libretro-common/cdrom/cdrom.c
libretro-common/cdrom/cdrom.c:50:10: fatal error: stropts.h: No such file or directory

### Expected behavior

Build to succeed on Linux.

### Actual behavior

Build is failing due to missing header files on Linux OS.

### Steps to reproduce the bug

Just try to build current master on Fedora / RHEL.

### Bisect Results

Added in commit 08cd3a9: initial cdrom reading work
https://github.com/libretro/RetroArch/blob/08cd3a90f232cc8bde8ca755958ee77736345d90/libretro-common/cdrom/cdrom.c

### Version/Commit
You can find this information under Information/System Information

- RetroArch: commit 31992c22

### Environment information

- OS: Fedora 30
- Compiler: GCC

**Comment by hizzlekizzle** [comment]
related info: https://bugzilla.redhat.com/show_bug.cgi?id=656245

**Comment by orbea** [comment]
I submitted a PR to add a configure check to at least prevent the build failures, but CD-ROM support will not be available unless these headers exist.

**Comment by s3gfaultx** [comment]
It appears that only ioctl is being used, it might be possible to just replace stropts.h include with sys/ioctl.h header -- that's what some other software is doing. I've replaced the header in my local copy and the build was successful, but I don't have the hardware to test if it still worked (no cdrom).
