### ISSUE TITLE
PPSSPP causing retroarch to crash

### ISSUE THREAD

**Issue by devnoot** [libretro/RetroArch#9106]
## Description

PPSSPP core causing retroarch to crash to on MacOS 10.14.5

[Description of the bug]

On a new install of RetroArch, downloading the PPSSPP core, then attempting to open it with a PSP game results in a crash.

### Expected behavior

Expected the game to start.

### Actual behavior

PPSSPP crashes, taking retroarch with it.

### Steps to reproduce the bug

1. Install RetroArch
2. Download ppsspp core
3. Update ppsspp assets per libretro docs
4. Attempt to run game with ppsspp

### Version/Commit

- RetroArch: https://buildbot.libretro.com/stable/1.7.7/apple/osx/x86_64/RetroArch_Metal.dmg

### Environment information

- OS: MacOS 10.14.5

Crash log:

```
[libretro INFO] [HLE] Replaced memcpy at 0880c700 with hash 9e6ce11f9d49f954
[libretro INFO] [HLE] Replaced memmove at 0880c840 with hash bfe07e305abc4cd1
[libretro INFO] [HLE] Replaced memset at 0880cb80 with hash fe5dd338ab862291
[libretro INFO] [LOADER] Exporting ent 0 named fftpsp, 2 funcs, 4 vars, resident 08a4b84c
[libretro INFO] [LOADER] Exporting ent 1 named fftpsp, 2 funcs, 4 vars, resident 08a4b898
[libretro INFO] [LOADER] Exporting ent 2 named fftpsp, 0 funcs, 0 vars, resident 08a4b8c8
[libretro INFO] [LOADER] Module entry: 08814b00
[libretro ERROR] [SYSTEM] Error...

  Line: 63
  File: ../GPU/GPU.cpp

Ignore and continue?
[libretro ERROR] [SYSTEM] Critical: *** Assertion ***

E: MsgHandler.cpp:72: *** Assertion ***
```

**Comment by orbea** [comment]
Wrong issue tracker, please repost it here.

https://github.com/hrydgard/ppsspp/issues
