### ISSUE TITLE
[feature request] Add JSON format shader preset

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#9115]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Add JSON format shader preset (as already done for playlists).

Maybe, it's related to https://github.com/libretro/RetroArch/issues/8289
(maybe "on/off" = "change certain shader pass to stock shader pass with same options before compiling shader stack" will be simpler then)

### Expected behavior

This shader format should be supported.

### Actual behavior

No this feature now.

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
We'd rather not add even more technical debt unless absolutely necessary.
