### ISSUE TITLE
[REQUEST?] mgba core for (n)3ds

### ISSUE THREAD

**Issue by Ty-Dye** [libretro/RetroArch#9124]
mgba runs great on the n3ds and its available for the system to however it is not in retroarch and I think it would greatly improve the 3ds port if it was added

it is worth noting that in the 3ds recipe mgba is included however no make file for 3ds exist in the mgba fork used by retroarch

**Comment by RobLoach** [comment]
You'll want to create an issue in the MGBA queue:
https://github.com/libretro/mgba

**Comment by orbea** [comment]
Wrong repo and this issue already exists upstream.

https://github.com/mgba-emu/mgba/issues/1033
