### ISSUE TITLE
[Windows] Provide Vista Builds?

### ISSUE THREAD

**Issue by hereinthebubble** [libretro/RetroArch#9129]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Not really a bug but the forums are just annoying to use (couldnt figure how to make a thread without waiting ages or w/e) and I feel like it fits here too as its more targeted at devs than users: Vista IMO should have its own build target or something, rather than simply using the XP one. Things like DX10 support would be neat for a Vista specific build as well as anything else that can be taken advantage of. I remember Vista breaking without realisation on RA's normal target and it had to be moved to msvc2010 some time ago which has led to the detriment of functionality but I feel like this is holding it back

### Environment information

- OS: Vista SP2 x64 (fully updated to April 2017)
- Compiler: Not sure what we could use for targeting. Maybe msvc2013 or 2015 which supports vista still

**Comment by RobLoach** [comment]
Does the XP version work? What does it miss that would be provided by a Vista build?

**Comment by bparker06** [comment]
I think it might be possible to enable DX10 on the XP (vc2010) build since (I believe) it is only loaded at runtime when you set the video driver to d3d10 (so it shouldn't break XP).

However you will probably get more features with a newer MSVC build. We have project files for 2012-2017, have you tried any of those? They all should support running on Vista.

**Comment by hereinthebubble** [comment]
@RobLoach The MSVC2010 build works fine.

@bparker06 I know nothing about Windows compilation in any way, but I’ll try to do something tomorrow and I’ll feed back on it here. Currently not going to be able to do anything for the time being though :p

It is known from a previous issue made some time ago, that Vista was mostly dropped from the mainline release due to some sort of dependency update breaking things (rather than something in the actual libretro code) as well as the compiler breaking Vista compatibility silently.

**Comment by twinaphex** [comment]
Compiling D3D10 itself for MSVC 2010 is not the issue. The issue is that all the shader code is reliant on HAVE_SPIRV_CROSS and HAVE_GLSLANG, and both of these require C++11. MSVC 2010 has very preliminary and premature C++11 support and these portions simply wouldn't compile.

**Comment by hereinthebubble** [comment]
@twinaphex Why not just mark that DX10 shaders aren’t supported on MSVC2010 build in that case perhaps if it’s to be considered to compile it in the binaries provided?

Personally I’m not bothered about prettification so... heh (and also it’s worth mentioning Vista can do DX11 if IE9 is installed thanks to the Platform Update being one of IE9’s dependencies)

**Comment by bparker06** [comment]
Shaders are required for DX10 to work at all. Someone would have to write an HLSL renderchain that doesn't use SPIRV/slang to make it work with vc2010.

**Comment by hereinthebubble** [comment]
Actually this isn’t worth the effort come to think about it because Vista is unlikely to be at all easy to test. Just tell people stuck on Vista to upgrade to 7 or throw their PC out.

**Comment by RobLoach** [comment]
Or install Linux!!!! Linux Mint feels kinda Windows-y.
