### ISSUE TITLE
SNES thumbnail pack zip file broken (linux archive manager exits with error: "null")

### ISSUE THREAD

**Issue by Makman2** [libretro/RetroArch#9138]
Hi :)

I hope this is the right place to file an issue like this regarding downloadable content for RetroArch.

## Description

The current thumbnail pack for the SNES `Nintendo - Super Nintendo Entertainment System.zip` appears to be broken (http://thumbnailpacks.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.zip). Manually downloading the file and trying to extract it yields no detailed error (really, literally it's `null`) - using the standard Archive Manager for linux (`file-roller`).

However, there was even no error message in RetroArch - neither in the frontend itself nor in the logs (which I consider really not good - the logs are supposed to tell me such problems :sweat_smile: )

### Expected behavior

1. The thumbnail pack zip archive should be properly extractable :)
2. And in the case it does not extract due to any error: Log an error for verbose mode and if makes sense (imo it does), add a notification that extraction failed due to an (unknown) error.

### Actual behavior

1. The zip is broken.
2. No error message at all visible - neither in logs nor in the frontend.

### Steps to reproduce the bug

1. Start RetroArch (without SNES thumbnails installed)
2. Go to *Online Updater*
3. Select *Thumbnails Updater*
4. Select *Nintendo - Super Nintendo Entertainment System.zip*
5. See the download finishing
6. :boom: no thumbnails being installed and no error message :exclamation: 

### Bisect Results

I didn't bisect.

### Version/Commit

- RetroArch: v1.7.7 - commit 62da78c - build date May 8th 2019 - installed via flathub

### Environment information

- OS: Fedora 30 Workstation

**Comment by RobLoach** [comment]
There is a CDN caching something somewhere.... Try this one:

http://thumbnailpacks.libretro.com/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System.zip?NoCachesPlz

**Comment by Makman2** [comment]
That one did the trick :+1: Thanks :) In any case, the normal version should work as well :P

**Comment by RobLoach** [comment]
Thanks for testing! I'll connect with peeps to see if there's something we can do with the CDN.
