### ISSUE TITLE
PSX Gokujou Parodius Da! Deluxe Pack cannot be identified by database

### ISSUE THREAD

**Issue by DevCeN** [libretro/RetroArch#9139]
## Description

Gokujou Parodius Da! Deluxe Pack (crc: 9c787b3f) cannot be identified by the database. Not that the serial is wrong (SLPS-00002), looking at the source code of task_database_cue.c, it is looking for a string "boot", but this iso does not have that.

### Expected behavior

The clean dump is identified in the psx database.

### Actual behavior

Not listed in playlist.

### Steps to reproduce the bug

1. Prepare clean dump crc 9c787b3f
2. Prepare Sony Playstation database
3. Use scan file or scan directory
4. Check if it shows on the list [FAILED]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

- OS: Windows 10

**Comment by orbea** [comment]
Looks like its not in the rdb file and only in the date file.

Try this issue tracker instead.

https://github.com/libretro/libretro-database/issues

**Comment by RobLoach** [comment]
Moved over here https://github.com/libretro/libretro-database/issues/905 .... Thanks!

**Comment by DevCeN** [comment]
Hi @orbea, @RobLoach its in the rdb. I believe this is an issue of the id scanner not able to locate the game id within the iso, thats why I created the issue here instead of the database.

**Comment by orbea** [comment]
So I looked again and this is what I see.

```
$ grep --exclude-dir=.git -r SLPS-00002
dat/Sony - PlayStation.dat:	serial "SLPS-00002"
dat/Sony - PlayStation.dat:		serial "SLPS-00002"
dat/ps1.idlst:SLPS-00002 "Gokujou Parodius Deluxe Pack"
Binary file rdb/Sony - PlayStation.rdb matches
```
In `dat/Sony - PlayStation.dat`.
```
game (
        name "Gokujou Parodius Da! Deluxe Pack (Japan)"
        serial "SLPS-00002"
        description "This compilation collects the first two arcade incarnations of Konami's shoot'em'up parody series on one disc: Parodius Da! and Gokujyou Parodius."
        developer "Konami Computer Entertainment Tokyo, Inc"
        publisher "Konami"
        releaseyear "1994"
        releasemonth "12"
        releaseday "3"
        users "2"
        genre "Shooter"
        rom (
                serial "SLPS-00002"
                image "Gokujou Parodius Da! Deluxe Pack (Japan).cue"
        )
)
```
In `rdb/Sony - PlayStation.rdb`.
```
SLPS-00002<A6>serial<C4>
SLPS-00002<8A><A4>name<B7>Goiken Muyou II (Japan)<AB>descriptionٗGoiken Muyou 2 is a 3d fighting game that features 10 characters (male & female ones) and different game modes (story mode, arcade, vs, tag team, etc).<A5>genre<A8>Fighting<A5>users<CC>^B<AC>releasemonth<CC>
```
```
$ grep -r 'Gokujou Parodius Da! Deluxe Pack' rdb/
Binary file rdb/Sega - Saturn.rdb matches
Binary file rdb/Sony - PlayStation.rdb matches
```
```
SLPM-87329<A6>serial<C4>
SLPM-87329<8A><A4>name<D9>(Gokujou Parodius Da! Deluxe Pack (Japan)<AB>descriptionْThis compilation collects the first two arcade incarnations of Konami's shoot'em'up parody series on one disc: Parodius Da! and Gokujyou Parodius.<A5>genre<A7>Shooter<A5>users<CC>^B<AC>releasemonth<CC>^L<AB>releaseyear<CD>^Gʩdeveloper<D9>(Konami Computer Entertainment Tokyo, Inc<A9>publisher<A6>Konami<A6>serial<C4>
```
I think `SLPS-00002` is associated with the wrong game and this is a database issue.
