### ISSUE TITLE
"Save Shader Preset As" dialog will immediately pop up again when using keyboard

### ISSUE THREAD

**Issue by LazyBumHorse** [libretro/RetroArch#9141]
## Description

Pressing enter in the "Save Shader Preset As" dialog will immediately open the dialog again (most of the time?)
This does not happen when using a Controller

### Steps to reproduce the bug

1. Start a game
2. Load a shader
3. Press Save Shader Preset As
4. Enter a name and press enter

### Bisect Results

I'm pretty sure this didn't happen a few week ago, this might be related to the changes in window message parsing (`PeekMessage` etc) again.
It probably reads a double enter press or something.

### Version/Commit

- RetroArch: https://github.com/libretro/RetroArch/commit/f9d963b2586fc6a06e6dd9baed352d8fd5671eb1
- OS: Windows 7

**Comment by twinaphex** [comment]
Yeah I have noticed something similar with keyboard search.

**Comment by LazyBumHorse** [comment]
It is this commit again https://github.com/libretro/RetroArch/commit/e02ff9c40ceb683d60ff22d45006a0e32f9a7e03, the one that broke threaded video.
Let's see...

**Comment by LazyBumHorse** [comment]
https://github.com/libretro/RetroArch/blob/ba40af1dde2b20c6ae7058614c349e8adc94cec2/retroarch.c#L2026-L2028
Removing this in master fixes it, that is as far as I'm gonna go today.

**Comment by twinaphex** [comment]
Should be fixed now in master.

**Comment by LazyBumHorse** [comment]
This seems to happen under Linux (running through VirtualBox) as well, so maybe we just treated a symptom.
