### ISSUE TITLE
from commit bcb9762 it no longer compiles on ARM (Amlogic)

### ISSUE THREAD

**Issue by shantigilbert** [libretro/RetroArch#9160]
## Description

From commit bcb9762 RA no longer compiles, it fails at the linking stage

The commit before 7fe0662918c50f8fa8c5549e5ca5edcbd5238edf compiles and links fine

### Expected behavior

Compile and work

### Actual behavior

Gives all these errors: https://pastebin.com/DSiDR2yP

### Steps to reproduce the bug

my flags and command are as follows: 
--disable-vg \
                           --disable-sdl \
                           --enable-opengles \
                           --disable-kms \
                           --disable-x11 \
                           --enable-mali_fbdev \
                           --disable-qt \
                           --enable-neon \
                           --enable-zlib \
                           --enable-freetype \
			               --disable-discord \
			               --disable-opengl1 \
			               --disable-opengl_core \
			               --enable-alsa

make HAVE_UPDATE_ASSETS=1 HAVE_LIBRETRODB=1 HAVE_NETWORKING=1 HAVE_LAKKA=1 HAVE_ZARCH=1 HAVE_QT=0 HAVE_LANGEXTRA=1

### Bisect Results

Commit bcb9762

**Comment by orbea** [comment]
Can you please provide a full configure and make log? Also please share the contents of the `config.mk` file after `../configure`.

Can you also test if adding `--disable-slang --disable-glslang --disable-spriv_cross` helps?

**Comment by orbea** [comment]
@shantigilbert 

Can you please try PR https://github.com/libretro/RetroArch/pull/9161?

**Comment by shantigilbert** [comment]
@orbea Thanks for the fast response! That PR works!

**Comment by orbea** [comment]
Thanks for testing, I will close this issue since it works for you and was merged. :)
