### ISSUE TITLE
Selecting an achievement from list can cause crash

### ISSUE THREAD

**Issue by retro-wertz** [libretro/RetroArch#9183]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Selecting an achievement can cause crash.

### Expected behavior

As previous behavior, trying to select or pressing OK/Enter on an achievement does nothing. You can only browse on whats available. Pressing SELECT on it does show the description though.

### Actual behavior

When trying to select (enter/ok) or open an achievement it can either open to core options values selection instead and causes crash eventually: (in the screenshot, whats shown is values are from the core option **RAM power up state**)
![Screenshot_2019-07-24_11-08-19](https://user-images.githubusercontent.com/23315382/61768851-2800c580-ae1b-11e9-873b-f76e96722f9b.png)

Opens to an empty menu and gets stuck there (cant return to previous menu or access any):
![Screenshot_2019-07-24_11-03-47](https://user-images.githubusercontent.com/23315382/61768488-31d5f900-ae1a-11e9-94ee-3671572bfd77.png)

Or entirely crash retroarch (as discussed by wambulance in discord)

### Steps to reproduce the bug

1. Open a game with achievements (i used FCEUmm on 1942 above, quicknes too was used to test)
2. After cheevos finish loading the achievemen, Open quick menu > Achievements
3. Select any achievement on list.
4. This would then do any of the three problems above:

### Bisect Results

last good commit https://github.com/libretro/RetroArch/commit/38173958037120893215d12ea5b11a0dd9b05758

first bad commit https://github.com/libretro/RetroArch/commit/143b45eca7c431e7b043e84d3856749e85517da2

### Version/Commit
You can find this information under Information/System Information

- RetroArch:  1.7.7 - ba79947e

### Environment information

- OS:  Linux arch 4.19.60-1-lts #1 SMP Sun Jul 21 11:30:21 CEST 2019 x86_64 GNU/Linux
- Compiler: gcc version 9.1.0 (GCC)

@twinaphex

**Comment by retro-wertz** [comment]
for me looks like this should not be solely a "cheevos" thing based on whats found during bisect. imho.

**Comment by twinaphex** [comment]
Hi there,

looks like this was a PR by @jdgleaver and we should get him involved in this.

**Comment by jdgleaver** [comment]
Well that sucks...

There's some fragile code here: in one place there's a *very* dubious switch statement that mixes a bunch of different enums and constants, and some of these 'binds' with range checks are none too clever.

This will be trivial to fix, but it'll take some time to find the line where things are going wrong. I'll get it sorted as soon as possible.

**Comment by jdgleaver** [comment]
Okay, should be fixed by #9193

@retro-wertz Thanks for reporting this! I don't use cheevos, and so would never have noticed otherwise.

**Comment by retro-wertz** [comment]
@jdgleaver  thanks for the fix. works for me now. ill tag wambulance in discord and see if he can test as well since he was the one who had the crash problem.
