### ISSUE TITLE
video_driver "gl" is slow on Raspberry Pi 4 even in menus

### ISSUE THREAD

**Issue by bobbybudnick** [libretro/RetroArch#9198]
## Description

I am interested only in using the "gl" driver as it is the only one that supports overlays.   "gl1" and "sdl2" are faster.  Results are the same with or without the vc4 driver.

Configure 1
--disable-x11
Result: no working gl driver

Configure 2
CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --disable-opengl1 --enable-udev --enable-floathard --enable-opengles3 --enable-opengles --disable-videocore --disable-pulse --disable-oss
Result: slow gl driver

Configure 3
CFLAGS="-mfpu=neon" ./configure --enable-alsa --enable-udev --enable-neon --disable-videocore --disable-opengl1
Result: slow gl driver

Configure 4
CFLAGS="-mfpu=neon" ./configure --enable-alsa --enable-udev --enable-neon --disable-videocore --enable-opengles --enable-opengles3 --disable-opengl1 --enable-x11
Result: slow gl driver

### Expected behavior

The "gl" driver should run with acceptable speed.

### Actual behavior

The driver can only maintain about 5 FPS in menus.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 5047d6e

### Environment information

- OS: Devuan Jessie 32 bit.
- Compiler: GCC 4.9.2 32 bit

**Comment by twinaphex** [comment]
What menu shader effect do you have running? If it is the modern ribbon, turn it off. It can tend to be a performance hog and is heavily GPU bound.

Also disable icon shadows.

**Comment by bobbybudnick** [comment]
I have set xmb to rgui and menu_shader_pipeline to 0 already if that is what you mean.  The interface is still fairly slow.  Games though run a little faster than I expected.  Super Mario World is almost playable even with the slow interface.

I also found out that gl1 shows overlays when you have the right configure options passed during compilation.

The primary problem I am having is with overlay interaction but I will open a new bug for that.

**Comment by amigagamer** [comment]
I'm seeing 60fps in windowed mode under X11, and around 43fps in fullscreen/window x11with the GL driver (ribbon menu- compiled with videocore disabled). Granted its not as fast/smooth as running without X using dispmanx on a Pi3, but its still better performance than your seeing . Im compiling on gcc 8.3.0 under the official raspbian/buster image. Possible you have an outdated driver/build environment running Devaun Jessie?

**Comment by gouchi** [comment]
You may also try our [beta image](https://twitter.com/lakkatv/status/1155201136720302080) if you want to test ;-)

Thank you.

**Comment by dankcushions** [comment]
are you running on a 4k display? i believe by default that will cause the menu to display at 4k also... which is a lot. you'll want to set retroarch to run at 1080p.

**Comment by twinaphex** [comment]
Closing this in case it's just the user setting this at 4K which is a resolution the Pi 4 is not capable running at fullspeed. Reopen this if it's still too slow even at 1080p.
