### ISSUE TITLE
Content scanner hangs on zip containing only empty .ipf file

### ISSUE THREAD

**Issue by HunterZ** [libretro/RetroArch#9202]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

While using "scan directory" on a game collection, the scanner has been stuck overnight on what turned out to be a zero-byte Amiga .ipf file inside of a .zip archive.

### Expected behavior

Scanner should skip over the file and/or log an error.

### Actual behavior

Scanner gets stuck forever.

### Steps to reproduce the bug

1. Make an empty file with a .ipf extension
2. Make a .zip archive containing the .ipf file
3. Tell RetroArch to run a content scan on the directory containing the .zip file

### Bisect Results

N/A

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 8c17f12, May 8, 2019 (official Android release)

### Environment information

- OS: FireOS (Android 5.1)
- Compiler: N/A (official release, reports Clang/LLVM 3.8.256229)

**Comment by HunterZ** [comment]
FYI, I submitted debug info via the in-app GUI, and it gave me code 18225.

**Comment by bparker06** [comment]
Should be fixed in f3faecdb2753b0afd4dd3c3fe78e930e4aac7fa1
