### ISSUE TITLE
shader presets saved with absolute paths

### ISSUE THREAD

**Issue by Kallin** [libretro/RetroArch#9207]
When I save core presets after applying a shader selection from shader quick-menu, I noticed that the settings weren't portable across machines. IE when I move my external HD to another system most things work well, but the shader presets were lost.  It looks like in the core shader .glslp files, the shader file reference is stored with an absolute path. I manually changed these to relative paths and now it works as expected.

1.77 retroarch, windows 10 64 bit.

**Comment by orbea** [comment]
@jdgleaver Do you happen to know anything about this issue?

**Comment by jdgleaver** [comment]
@orbea I've never looked at this code, but there have been a couple of PRs related to this recently:

#8933
#9140

I think @LazyBumHorse is the person to ask about this :)

**Comment by LazyBumHorse** [comment]
Yeah, that has been implemented and should work on all platforms, simply update to nightly or wait for 1.7.8.

**Comment by orbea** [comment]
@Kallin Please try a nightly version.
