### ISSUE TITLE
Awarding achievment seems to crash RetroArch on MacOS High Sierra

### ISSUE THREAD

**Issue by devnoot** [libretro/RetroArch#9210]
## Description of the Bug

It doesn't matter what core I am running, RetroArch seems to crash once I am awarded an achievement. If I select achievments from the menu whilst in any core/game that supports it, RetroArch will crash.

### Steps to reproduce the bug

1. Open a game
2. Get an achievements (confirmed via log)
3. Watch RetroArch crash

I'm not sure it's the same bug, but this can also be reproduced by

1. Open a game
2. Open the RetroArch menu with the game still running
3. Select Achievements from the core menu

Here is the crash log for crashing when being awarded an achievement:

```
[INFO] [RCHEEVOS]: awarding cheevo 19049: Shoooooms... - The Lost Levels (Find and Collect a Super Mushroom)
[INFO] [Metal]: readViewport is_idle = NO
-[MTLIGAccelTexture getBytes:bytesPerRow:bytesPerImage:fromRegion:mipmapLevel:slice:]:895: failed assertion `Cannot getBytes on framebuferOnly texture.'
zsh: abort      sudo ./RetroArch --verbose
```

Furthermore, here is the crash log for crashing when selecting the Achievments option of the core menu (which doesn't seem to have anything useful):

```
[INFO] [RCHEEVOS]: got game id 1462
[INFO] [RCHEEVOS]: got achievements for game id 1462
[INFO] [RCHEEVOS]: cheevo 31806 deactivated: Belmont Excavator II (Vampire Killer 2)
[INFO] [RCHEEVOS]: cheevo 31809 deactivated: Belmont Excavator IV (Vampire Killer 4)
[INFO] [RCHEEVOS]: cheevo 31845 deactivated: Vampire Hunter Arsenal
[INFO] [RCHEEVOS]: cheevo 53385 deactivated: Vir Fortis Integellus I (The Bat)
[INFO] [RCHEEVOS]: cheevo 53390 deactivated: Vir Fortis Integellus II (Medusa)
[INFO] [RCHEEVOS]: cheevo 53394 deactivated: Vir Fortis Integellus III (The Mummies)
[INFO] [RCHEEVOS]: cheevo 53398 deactivated: Mighty Crusader I (Vampire Killer)
[INFO] [RCHEEVOS]: cheevo 53399 deactivated: Mighty Crusader II (Stalker)
[INFO] [RCHEEVOS]: posted playing activity
[INFO] [RCHEEVOS]: posted playing activity
zsh: abort      ./RetroArch --verbose
```

I also have the MacOS generated problem report and can post it if you find it useful.

### Version/Commit
```
[INFO] RetroArch 1.7.7 (Git GIT_VERSION)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
[INFO] Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
[INFO] Built: May  6 2019
[INFO] Version: 1.7.7
[INFO] Git: GIT_VERSION
```
### Environment information
- OS: MacOS High Sierra 10.14.5 (18F132)

**Comment by orbea** [comment]
> [INFO] RetroArch 1.7.7 (Git GIT_VERSION)

Why is the `GIT_VERSION` broken on osx?

Are you using the `1.7.7` stable or a nightly? There was a recent fixed issue which might be the same as this.

https://github.com/libretro/RetroArch/issues/9183

**Comment by devnoot** [comment]
I'm using the build located here https://buildbot.libretro.com/stable/1.7.7/apple/osx/x86_64/RetroArch_Metal.dmg

Which is linked from the website itself: https://www.retroarch.com/?page=platforms

Could it be that the website just hasn't posted the 1.7.7 build yet?

**Comment by orbea** [comment]
Can you try this one?

https://buildbot.libretro.com/nightly/apple/osx/x86_64/2019-07-27_RetroArch_Metal.dmg

**Comment by devnoot** [comment]
Hey, I actually got this to work by reinstalling RetroArch via HomeBrew, not really sure what the issue was because doing so seemed to just overwrite RetroArch.app with the same version.
