### ISSUE TITLE
(Menu) Ozone TIC-80 playlist truncated

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#9234]
TIC-80 becomes `0`

Probably because we were removing Atari et al.

![Screenshot at 2019-08-01 04-01-16](https://user-images.githubusercontent.com/25086/62275974-08682f00-b411-11e9-8560-e665b2238788.png)

**Comment by natinusala** [comment]
Does that happen on XMB as well?

**Comment by RobLoach** [comment]
Does not happen on XMB. This is likely because of the `-` truncating. May need to check explicitly for it.

![Screenshot at 2019-08-01 13-14-14](https://user-images.githubusercontent.com/25086/62313291-64a57000-b45e-11e9-88c5-88ffef5502a7.png)

**Comment by natinusala** [comment]
Right, I should be checking for ` - ` and not `-`
