### ISSUE TITLE
New playlist sanitize feature skipping history/favorites

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9235]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

The new feature to sanitize entries in the playlist is working a treat, except for its omitting history/favorites.

### Expected behavior

To have an option to have those names cleaned to correspond with the playlists setting(s).

### Actual behavior

All names are properly cleaned to correspond with how its set in playlist management, but the history (and i presume) favorites is left out.  Likely more of a feature request than a bug persay.  To add those in. 

### Steps to reproduce the bug

1. navigate to playlist management and turn on the option to omit () and []
2. run a game that includes either of the above tags
3. check history after the fact, and note the tags are still present in that list

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.77 58286367d7

### Environment information

- OS: Windows 10

**Comment by klepp0906** [comment]
@jdgleaver

**Comment by jdgleaver** [comment]
Yes, we need to add history/favourites to the Playlist Management menu (this will be useful for resetting associated cores on those playlists, too)

I'll try to get around to this sometime next week  :)
