### ISSUE TITLE
[Switch/Vita] Retroarch often crashes when loading content/playlist entry 

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#9236]
## Description

Retroarch often crashes when loading content when a core is already loaded on Switch/Vita. The crashes are much less frequent if "Close Content" is first selected before loading new content, but still even then sometimes it crashes.

It probably has to do with the fact that these are static builds.

### Expected behavior

Loading content/playlist entries should never crash the emulator.

Load Content should not behave different than Close Content followed by Load Content. I mean clearly it has to close content before it can load new content anyways. But somehow Retroarch does something different in the two cases. 

### Actual behavior

Often, when loading content/playlist entry while a core is already loaded, Retroarch crashes on Vita/Switch. The crashes seem to happen less if "Close Content" is first selected, before loading new content, but still even then sometimes it crashes. The same crashes happen when loading via playlist. Either way they happen.

### Steps to reproduce the bug

1. Load a core, any core on Vita/Switch
2. Select Load Content and load some content to start the core with it
3. Go to menu, Load Content again
4. Observe crashing sometimes, if not crashing, load different content until it crashes
5. Load a core
6. Load content
7. Close content
8. Load content again
9. Observe less frequent crashing on load content. But still sometimes crashes.

### Bisect Results

Always been an issue on Vita/Switch

### Version/Commit

Latest Nightly, August 1 2019

### Environment information

- OS: Switch and Vita

**Comment by m4xw** [comment]
As far as I am concerned, it's not a frontend Issue.
Many cores have Issues with static linking, so such issues never come to light since the core is always unloaded.
Also it doesn't happen with every core.
The established solution is to use salamander / paylists, these will force a core reload / nro forking.
I doubt u encounter this Issue when actually using playlist.

**Comment by m4xw** [comment]
> Load Content should not behave different than Close Content followed by Load Content. I mean clearly it has to close content before it can load new content anyways. But somehow Retroarch does something different in the two cases.

It does not. What you are witnessing is probably some awkward races.

**Comment by rsn8887** [comment]
Hmm I In my testing with playlists only using latest nightly, there's no crashes, but the widget sometimes says "Core Set: XXX" (XXX is Picodrive or whatever), but the core and game don't change.

**Comment by rsn8887** [comment]
yes this is a core issue.

**Comment by Itay080** [comment]
I know this issue is closed but the Vita version of Retroarch crashes when scanning for NES games, viewing the NES playlist or viewing the recents tab with NES games in it. I've tried all 3 cores so I don't think this is a core issue. Perhaps it's worth reopening the issue?
