### ISSUE TITLE
RetroArch (log to file) fails

### ISSUE THREAD

**Issue by eat-sleep-code** [libretro/RetroArch#9251]
## Description

I am having an issue playing any N64 ROMs on a 1.7.7 install on Windows 10.   I attempted to execute the "RetroArch (log to file)" shortcut but it fails.    Executing retroarch from command line seems to indicate that --log-file is not a valid parameter.   I am unable to generate logs to find out what the issue is.

### Expected behavior

Expect that the "Retroarch (log to file)" shortcut to actually work.

### Actual behavior

See above.

### Steps to reproduce the bug

Go to menu, click "Retroarch (log to file)" in 1.7.7 on Windows 10

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7

### Environment information

- OS: Windows 10 fully patched

**Comment by bparker06** [comment]
This was fixed already, if you use a nightly build it should be working.

**Comment by eat-sleep-code** [comment]
@bparker06  So I just need: http://buildbot.libretro.com/nightly/windows/x86_64/RetroArch-2019-08-04-x64-setup.exe   ??

**Comment by RobLoach** [comment]
Yes, grab that and test it out. If it works, feel free to report here and close :+1: 

Thanks for testing!

**Comment by eat-sleep-code** [comment]
Logging now works.
