### ISSUE TITLE
Audio Delay with Super Mario 64 while Recording

### ISSUE THREAD

**Issue by Sanic1239** [libretro/RetroArch#9253]
### Description

Okay so, I know this isn't a place for game bugs but I can't find where else to put this. I have been trying out RetroArch's internal recording functionality, and it works great for the most part! But for some reason, N64 games give the built in recorder a lot of problems.

I tried Super Mario 64 for my first game, while I was playing the game it was working fine, no issues at all (at least as close to no issues as you can get with emulation).

But when I previewed the recorded clip I made, something was WAY off, the audio latency. The audio was at least 2 seconds or more out of sync with the images on my monitor!

But what's even weirder, I did a test. I put myself in the game before recording (skipping the menu entirelt). And for some reason, the gameplay wasn't effected at all then! But.. when I went into Bob-Omb Battlefield, the audio synced out horribly again!

So the out of sync seems to occur when entering a new area, like leaving the title screen and entering the main game. Or starting the game then entering a level. 

But then I tried Ocarina of Time, for some reason, the audio was almost flawless! So is this just a audio bug with SM64, that Mupen64Plus doesn't like with the built in recorder?

Before-Game-Begins (Horrible Sync Issues): https://bit.ly/2Kt9UYd

After-First-Stage-Begins (Not As Bad Sync Issues): https://bit.ly/2KgqRX1

### Expected behavior

I expected the audio to at least be partially in sync with the recording, but it wasn't a great experience at all.

### Actual behavior

The audio isn't caught up with the game at all, resulting in very delayed audio. But it only seems to happen when entering a loading zone.

### Steps to reproduce the bug

1. Enable "Use GPU Recording" (for some reason I can't record at all without enabling it).
2. Use Mupen64Plus core with OpenGL driver, and any of the audio drivers (I tried most but not all).
3. Disable V-Sync (Or it produces horrendous lag (I feel I am doing something wrong though, feel free to shame me)).
4. Start recording the game till you get into a stage (SM64) then review recording when done.
5. For 2nd recording, re-hit the record button while in a stage and the sync issues should be resolved (until exiting the stage, then the sync gets worse).

### Bisect Results

It only happens while watching the recording, but during gameplay it is perfect! And I have tried lots of different systems (except the 3D era ones), but N64 is the only one giving trouble as far as I know of.

### Version/Commit

- RetroArch: 1.7.7

### Environment information

- OS: Windows 7 Home Pro
- CPU: i7 870
- GPU: GT 710
- Audio: PC Internal Speakers or Speakers connected with green AUX jack (I mostly use internal).

(And sorry this is my first GitHub post)

**Comment by Sanic1239** [comment]
Nevermind, I decided to just use OBS as I have used too until the recording is implemented a bit better (or I get a bit smarter XD, I am probably causing the problem somehow).

**Comment by twinaphex** [comment]
I'd prefer you leave this open until the issue is actually properly resolved.

**Comment by hizzlekizzle** [comment]
I believe it's a core issue, rather than a RetroArch issue. I've spent a lot of time trying fine-tune the timing but it didn't seem to help.

**Comment by Sanic1239** [comment]
Sorry, I closed it because I thought I was asking a dumb question, but I'll open it again!

**Comment by Sanic1239** [comment]
> I believe it's a core issue, rather than a RetroArch issue. I've spent a lot of time trying fine-tune the timing but it didn't seem to help.

So you are having the same issue I am?

**Comment by Sanic1239** [comment]
> I believe it's a core issue, rather than a RetroArch issue. I've spent a lot of time trying fine-tune the timing but it didn't seem to help.

So does that mean I have to wait till (or if) the developers fix the timing issues? It's fine if it does as I have other ways to record, but it would be more convinent to record inside the emulator along with all the features (such as not accidentally recording the RetroArch menu, or recording misc. Desktop noises, and when you fast forward it shows the footage in realtime and not in fast motion)!
