### ISSUE TITLE
1.7.7 and 2019-08-04 nightly - Mupen64Plus causes complete exit of RetroArch (Windows 10)

### ISSUE THREAD

**Issue by eat-sleep-code** [libretro/RetroArch#9256]
# First and foremost consider this:
Using Windows 10 (fully patched) and RetroArch 1.7.7 or the nightly build from 2019-08-04.   I can not launch any N64 ROMs with Mupen64plus.    

## Description

After selecting a ROM, the screen flashes back to desktop and then a blank screen loads.  After a few seconds RetroArch exits completely.   The log does not appear to show any errors.

### Expected behavior

Load ROMs without crash.

### Actual behavior

ROM crashes

### Steps to reproduce the bug

1. Select a N64 ROM from N64 ROM list
2. If prompted for a core, select MuPen64Plus
3. Select Run

**Logs:** 
[retroarch-log.txt](https://github.com/libretro/RetroArch/files/3474445/retroarch-log.txt)
[debug_info.txt](https://github.com/libretro/RetroArch/files/3474446/debug_info.txt)

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
-- RetroArch: 1.7.7 and 2019-08-04 nightly build
-- mupen64plus_next_libretro.dll  (CRC64: 11E6882B33C0B7E3)

### Environment information

- OS: Windows 10 (fully patched)

**Comment by twinaphex** [comment]
Works just fine here. You need to provide way more information on this issue than what you're currently giving us. An entire log would help to begin with.

**Comment by eat-sleep-code** [comment]
@twinaphex  The logs are attached?

**Comment by twinaphex** [comment]
Alright, my bad.

Anyway, I have looked at the logs now and can't see much wrong. The only thing that sticks out is you're using a Quadro (business line of NV cards) vs. what most of us are probably using (Titans/Geforce).

@m4xw Maybe you can help debug this issue?

**Comment by m4xw** [comment]
Try interpreter, might be a x64 dynarec issue

**Comment by bparker06** [comment]
```
[libretro INFO] mupen64plus: Name: MORTAL KOMBAT 4     
[libretro INFO] mupen64plus: MD5: C70B91430866300CE38B49098019EF9D
[libretro INFO] mupen64plus: CRC: 417DD4F4 1B482FE2
[libretro INFO] mupen64plus: Imagetype: .v64 (byteswapped)
```

I wonder why mupen thinks the rom is byteswapped... according to no-intro, this md5 corresponds to a big-endian (.n64) dump.

Your debug info does not say that you have any known problematic settings on, such as auto load state, rewind or runahead, but maybe you have an override that's turning one of these things on? 

That's all I can think of right now. Does parallel work instead?

**Comment by eat-sleep-code** [comment]
Sorry, was traveling and not looking at GitHub.   I got Parallel working instead.   So, definitely seems to be Mupen64Plus specific.   Is there a benefit to Mupen over Parallel?

**Comment by eat-sleep-code** [comment]
I tried downloading the latest Nightly install and running it using mupen, still same behavior.  👎

**Comment by m4xw** [comment]
https://github.com/libretro/RetroArch/issues/9256#issuecomment-519022138

**Comment by eat-sleep-code** [comment]
> [#9256 (comment)](https://github.com/libretro/RetroArch/issues/9256#issuecomment-519022138)

Where does one set the interpreter?   And what should it be set to?
