### ISSUE TITLE
[feature request] Auto rotate overlay switching between portrait and landscape on mobile devices (iOS and Android)

### ISSUE THREAD

**Issue by illando** [libretro/RetroArch#9257]
As in the Overlay archive there are a lot of configurations based on two different .cfg files (one for landscape and one for portrait usually named after it) would be awesome to add a feature that can automatically select the correct overlay based on the actual orientation of the device, making the process automatic, instead of tapping on the “rotation” icon every time  you see the overlay stretched. 
This option should work only if there are 2 files of the same configuration. It could be a way to maintain compatibility with the actual archive.

**Comment by tmtvl** [comment]
I have bad experiences with the gyro in my Xperia phone, so if this feature were to be included, I'd like it to be configurable whether or not the overlays auto-turn.

**Comment by illando** [comment]
Maybe a better idea should be to add a secondary (and only for portrait) overlay preset here in settings:

![image](https://user-images.githubusercontent.com/11694410/63218152-e7b01100-c154-11e9-84e8-1dd0db7ab938.png)

So the main overlay could remain the actual default, and retroarch will switch to the new one only when the device is landscape oriented and if the user choose a secondary one.
That would also create the possibility to have 2 different kind of overlay:
- semi-trasparent basic for landscape (like the default one)
- textured and complex for portrait (the kind based on a Game Boy mockup for example).

I'm sure people will love it!

**Comment by SuperSamus** [comment]
They added it, the issue should be closed now.
