### ISSUE TITLE
(Menu) Menu doesn't hide when using Quick Menu > Resume

### ISSUE THREAD

**Issue by paradadf** [libretro/RetroArch#9272]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

After opening retroarch's menu and playing while playing on any core, when I try to resume the game, it resumes in background.

### Expected behavior

Menu should hide after resuming the gameplay.

### Actual behavior

Menu blocks the view and game plays in the background.
![menu_on_top_while_running](https://user-images.githubusercontent.com/15956550/62964277-aa542800-bdd0-11e9-949f-448203c4bcf1.jpg)

### Steps to reproduce the bug

1. Launch a game
2. Open retroarch's menu
3. Resume the game

### Bisect Results
Issue appeared here: 
4d860c4d16c09cc6b7e06966089abd92d0bcc1e5
Last commit without the issue:
6482a81ef5e294d282b38eea63de19425b0fe836

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 7c9de7ec0f40128f27586167506e2872051633fc

The bug must have been introduced today (9th august), can't tell the exact commit.

**UPDATE:**  
I've tested da1ff54ddde8f01181abe03accc3faefd8825f3d from the day before (8th august) which doesn't have this problem.

### Environment information

- OS: I'm on a development branch of recalbox, compiling for the rpi3.
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
Please explain yourself more clearly what is going on here, preferably by a video demonstration.

**Comment by RobLoach** [comment]
Do you have Settings > User Interface > "Pauuse when menu activated" enabled?

**Comment by paradadf** [comment]
@RobLoach yes, it is enabled.
![8B78DDD1-88AA-4CE1-9262-99A0F0730594](https://user-images.githubusercontent.com/15956550/62821353-7adbbc00-bb41-11e9-9e49-430521034da3.jpeg)

I‘ll upload the video asap.

**Comment by paradadf** [comment]
@twinaphex please find the video here:
https://xfl.jp/ebN4h7

**Comment by paradadf** [comment]
Uselessly bisect the commit because the current master no longer presents this problem. Closing...
