### ISSUE TITLE
(MacOs) Can't find "Playlist Thumbnails Updater" in the menu

### ISSUE THREAD

**Issue by illando** [libretro/RetroArch#9276]
The "Playlist Thumbnails Updater" seems not to be present on the MacOs version like in iOS or Lakka.
The only option on MacOs seems to be the legacy "Thumbnails Updater" function download entire directories of thumbnails per consolle. It could be great to have the chance to download only the thumbnails of the games in my playlists.

MacOS:
![Screenshot 2019-08-10 at 14 00 43](https://user-images.githubusercontent.com/11694410/62822367-8c918380-bb82-11e9-9004-21b69f606506.jpg)

iOS:
![IMG_2729](https://user-images.githubusercontent.com/11694410/62822369-9adf9f80-bb82-11e9-82e2-ef18562abcdd.PNG)

Lakka:
![Screenshot 2019-08-10 at 14 56 55](https://user-images.githubusercontent.com/11694410/62822372-a4690780-bb82-11e9-8535-351768295c09.jpg)

**Comment by illando** [comment]
I'm sorry guys. It's included in the last nightly release. My bad.

**Comment by bparker06** [comment]
Are you using a nightly build? The option is not there yet in the current stable version (1.7.7).
