### ISSUE TITLE
Linux : Netplay controls stop working on some cores?

### ISSUE THREAD

**Issue by 7oxicshadow** [libretro/RetroArch#9281]
I am not really sure if this is a bug or more just an incompatibility with certain cores. I have read some of the previous bugs with similar issues but they just seemed to rectify themselves over time with no clear cause.

Both myself (host) and my friend (client) are using Retroarch on Linux.
We both build from source and try to build identical clients from the same commit.

We can play games on Snes9x and Picodrive cores with no issues and have played for hours on each but if we try either genesis_plus_gx or mupen64-next cores we can connect to each other but all the controls stop working apart from one button on each controller.

If I start a 2 player game before creating the host, upon joining we can both press the working button on our respective controllers and the game will respond accordingly (for streets of rage the characters punch and for diddy kong racing the characters accelerate).

Given that netplay works fine on some cores, can we rule out setup issues?
Does a core have to support netplay or should all work in theory?
Would it matter at a core level if we had different input drivers selected (SDL/UDEV etc..)?

Build Date : Aug 11 2019
Git Version : f5a8a934ac

**Comment by 7oxicshadow** [comment]
I have done some testing today and it appears that all you have to do to trigger this problem is start a netplay session as a host (a second player [client] is not required).

If you go in-game after starting a netplay session the controls will not work anymore (the menu/gui still works with the controller). Even more interesting is that it looks like this is a linux only issue as I have tried with an android phone using the genesis_gx_core and starting a netplay session on that does not create any problems with controls.

Ending the netplay session causes the controls to work again.

If any windows users read this, could you quickly test the following and report back:

1. Open Retroarch
2. Load the genesis_gx_core
3. Load any genesis game (my testing was with streets_of_rage_w)
4. Start the game to the point that you can control the character
5. Start a netplay session as a host
6. Return to the game and see if your controls still work.

This seems like the same problem as first reported in bug #6517

**Comment by 7oxicshadow** [comment]
Just tried this on windows 10 virtual machine. Controls work fine when hosting a netplay session so this is a Linux only issue.

**Comment by 7oxicshadow** [comment]
I have found a workaround for this problem. If I rebuild the problem cores (gens gx and mupen64-next) and force the "libretro_supports_bitmasks" checks to false in libretro.c netplay seems to function fine.

I haven't worked out why yet but the current theory is that netplay on linux is messing up the bit order for inputs causing bitmasking support to fail.

**Comment by twinaphex** [comment]
Oh, this is unfortunate to hear. I wonder if other cores with netplay are similarly affected that are using the 'bitmask' callback. Perhaps we should disable it for netplay?

Try this - 

instead of recompiling the cores, leave the cores as-is.

instead, make a custom compiled version of retroarch, go to retroarch.c -
https://github.com/libretro/RetroArch/blob/master/retroarch.c#L7500

Enter a new line at line 7051:

return false;

Let me know what happens then. If so, I'll have to talk with some people as to what the potential problem could be.

**Comment by 7oxicshadow** [comment]
@twinaphex thanks for responding. I have not tried your change yet as my source is a mess and I want to to test it on a clean build so I will get back to you asap. Could either yourself or someone familiar with netplay validate the following comment please :)

I can now explain why the problem goes away if I disable "libretro_supports_bitmasks".

I will use genesis-plus-GX for this example.

When genesis-plus-GX attempts to get the input state it does the following call:

    static void osd_input_update_internal_bitmasks(void)
    {
       int i, player = 0;
       unsigned int temp;
       int16_t ret = input_state_cb(player, RETRO_DEVICE_JOYPAD, 0, RETRO_DEVICE_ID_JOYPAD_MASK);

If you notice at the end it passes and id of RETRO_DEVICE_ID_JOYPAD_MASK (256)

In libretro.h there is the following comment:

> you can pass RETRO_DEVICE_ID_JOYPAD_MASK as 'id'
>                                             * to retro_input_state_t (make sure 'device' is set to RETRO_DEVICE_JOYPAD).
>                                             * It will return a bitmask of all the digital buttons

The key here being that it returns a bitmask of **ALL** digital buttons

This is confirmed in retroarch.c around line 11153

      if (  (device == RETRO_DEVICE_JOYPAD) &&
            (id == RETRO_DEVICE_ID_JOYPAD_MASK))
      {
         unsigned i;

         {
            for (i = 0; i < RARCH_FIRST_CUSTOM_BIND; i++)
               if (input_state_device(ret, port, device, idx, i, true))
                  result |= (1 << i);
         }
      }

Now if we look at the input handler for netplay ( function : netplay_input_state) it does the following

    switch (device)
    {
       case RETRO_DEVICE_JOYPAD:
          return ((1 << id) & curr_input_state[0]) ? 1 : 0;

It doesn't have a special handler for the id = 256 case. Changing it to the following makes gens-gx work:

    switch (device)
    { 
 
       case RETRO_DEVICE_JOYPAD:
          if(id == RETRO_DEVICE_ID_JOYPAD_MASK)
              return curr_input_state[0];
          else
              return ((1 << id) & curr_input_state[0]) ? 1 : 0;

I believe this is a small oversight but would like someone more knowledgeable with the netplay code to confirm.

**Comment by twinaphex** [comment]
Yeah I believe this was an oversight on my end.

If you can confirm that the other cores that exhibited problems with input before will work with this change too, then I'd say that we commit it, since when I implemented the bitmask feature, I did not make any changes to input on the netplay side. So I believe this was simply an oversight on my end.

**Comment by 7oxicshadow** [comment]
@twinaphex I happy for the fix to be committed as it fixes the cores that use digital inputs.

There is another issue that I am looking into with N64 core (unrelated to the fix above). The digital buttons work fine BUT the analogue controls do not work.

The following code seems to completely skip any RETRO_DEVICE_ANALOG requests but I am not sure why yet....

    /* If the port doesn't seem to correspond to the device, "correct" it. This
     * is common with devices that typically only have one instance, such as
     * keyboards, mice and lightguns. */
    if (device != RETRO_DEVICE_JOYPAD &&
        (netplay->config_devices[port]&RETRO_DEVICE_MASK) != device)
    {
       for (port = 0; port < MAX_INPUT_DEVICES; port++)
       {
          if ((netplay->config_devices[port]&RETRO_DEVICE_MASK) == device)
             break;
       }
       if (port == MAX_INPUT_DEVICES)
          return 0;
    }

I will keep digging to see if I can get a better understanding.

**Comment by twinaphex** [comment]
Hi there,

analog controls was simply never implemented for netplay. So if you can do so, that'd be awesome.

**Comment by twinaphex** [comment]
@7oxicshadow pushed the commit BTW -

https://github.com/libretro/RetroArch/commit/091c5f6092b82a691bd90f43043ed9656ca4b8ef

**Comment by 7oxicshadow** [comment]
@twinaphex Thanks for the commit. Just rebuilt from a clean source and it works fine :)

As for the analogue inputs, I didn't realise I had not been implemented. Is there any documentation around the netplay controller interfaces?

**Comment by twinaphex** [comment]
I believe this is the most extensive documentation we have -
https://docs.libretro.com/development/retroarch/netplay/
you could also ask @GregorR if you have pointed questions later on.

**Comment by 7oxicshadow** [comment]
@twinaphex Just so you know, analog controls work fine in netplay. It turns out that netplay chooses which controller to emulate from the retroarch.cfg file.

    if (netplay->is_server)
    {
       /* Clients get device info from the server */
       unsigned i;
       for (i = 0; i < MAX_INPUT_DEVICES; i++)
       {
          uint32_t dtype = input_config_get_device(i);
          netplay->config_devices[i] = dtype;
          if ((dtype&RETRO_DEVICE_MASK) == RETRO_DEVICE_KEYBOARD)
          {
             netplay->have_updown_device = true;
             netplay_key_hton_init();
          }
          if (dtype != RETRO_DEVICE_NONE && !netplay_expected_input_size(netplay, 1<<i))
             RARCH_WARN("Netplay does not support input device %u\n", i+1);
       }
    } 

Someone must have added support for them in the past.

Launching Retroarch in the following way enables analog support in netplay:

    ./retroarch -d1:5 -d2:5 -d3:5 -d4:5 -L <core> <rom> 

I have confirmed this by testing N64 cores and Playstation cores with analog controls. Seems to work well. The only thing I observed is that there are momentary pauses when large amounts of data are transmitted.

As an aside, I am wondering if there is any reason why netplay shouldn't force controller type 5? Given that all the digital data is transmitted in bits 0:15 and the analog is transmitted in bits 16:31 i assume that all cores that do not use analog will still function normally anyway.

I will close this issue as I am happy that it is resolved.
