### ISSUE TITLE
Framerate OSD should be more accurate

### ISSUE THREAD

**Issue by TylerLoch** [libretro/RetroArch#9284]
## Description

When viewing framerate using the Onscreen Display, the value is rounded to a single decimal place. For example, "59.9" and "60.1".
Most target framerates are commonly known by at least two decimal places. ("59.94", "60.09", etc)
This rounding (truncation?), coupled with the slow refresh and roaming of the value, makes it tough to accurately monitor performance.
As a point of comparison, the Video Settings section displays frame rate control values to **three** decimal places.

### Steps to reproduce the bug

1. Settings->Onscreen Display->Onscreen Notifications->Display Frame Count->ON
2. Watch displayed FPS, expected to appear at (for example) 60.00 or 59.94, appear as simply "59.9", or worse, inexplicably roam +-0.5FPS around the expected value.

### Environment information

- OS: Design choice. Appears on all OSes. (tested macOS, Windows, Lakka)
![Screen Shot 2019-08-11 at 8 00 01 PM](https://user-images.githubusercontent.com/26755087/62841899-dbb6e180-bc72-11e9-8cf5-0be87dff96eb.png)

**Comment by twinaphex** [comment]
Hopefully this addresses your request -

https://github.com/libretro/RetroArch/commit/54be49d88ed2dbbeb21322845e14479b84e5d706

**Comment by TylerLoch** [comment]
That's perfect! Sorry, I should've checked how trivial it was and submitted a Pull Request myself.

Related, I have submitted a pull request (#9302) to make the FPS readout more responsive as well, updating once every 120 frames rather than once every 256 frames.

Thanks!
