### ISSUE TITLE
Latest code unable to resume gameplay after pressing the P hotkey to pause

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#9287]
## Description

With the latest code, pressing the "P" hotkey (or whichever key was chosen for the same function) to pause RetroArch makes it impossible to:

- resume the gameplay by pressing "P" again;
- advance by a frame by pressing the "K" hotkey;
- bring up the Menu by using the "F1" hotkey;
- or exiting RA by pressing ESC.
(Basically all hotkeys stop responding).

The system apparently hangs entirely with no way to resume gameplay, unless (at least on Windows) one either Alt-tabs or Win-tabs out of the application. When selecting it again from the Alt-tab panel RetroArch resumes its operation normally.

### Bisect Results

I have performed a bisect and 15513c77525a0296323b30b91f7f0080c10df083 appears to be the commit causing this.

### Version/Commit

- RetroArch: 1.7.7 / 69a195fc5ca8755f250624e06dc2844401f1f403

### Environment information

- OS: Windows 10 x64
- Compiler: Mingw64

**Comment by twinaphex** [comment]
Thanks for pointing this out. Looks like the pause/fastforwarding/step by frame functionality relies on being able to call the input poll callback function more than once per frame.

I'll revert the bad commit then.

**Comment by Ryunam** [comment]
I can confirm commit cf812b2e802b84698e9c1c172c0caf0ba9f82cef fixes this. Thanks!
