### ISSUE TITLE
Double free in autosave_thread

### ISSUE THREAD

**Issue by HarukaMa** [libretro/RetroArch#9289]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When trying to save game, RetroArch crashes in `autosave_thread`, reporting double free on `file` pointer.

I have only tried one GBA game using mGBA core but considering the location of the crash I think it should also apply to other situations.

### Expected behavior

RetroArch not crashing.

### Actual behavior

RetroArch crashes.

### Steps to reproduce the bug

1. Save in (any?) game
2. RetroArch crashes after a little while (duration seems pretty random)

### Bisect Results

f5a8a934ace02dbc3087f3b012009d7507784e88 is the first bad commit

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 7c78e0ad1e

### Environment information

- OS: 10.15 Beta（19A526h）
- Compiler: Apple clang version 11.0.0 (clang-1100.0.32.5)

**Comment by negativeExponent** [comment]
i've lost my ps1 save because of this bug (tcache2 something). i've updated using the latest commit and saving seems to work, but now the Sync message is not showing anymore from the log window...

**Comment by twinaphex** [comment]
@negativeExponent Not sure where you left that comment where you asked for the log message to be brought back, but there are a couple of issues with that:

1 - RARCH_LOG is being called from a thread, and RARCH_LOG is not really thread-safe.
2 - The user doesn't get to see this message anyway without a log window open, so there's a questionable benefit to this log in the first place.
3 - Logging adds significant overhead and is normally not something that you just want to happen during live gameplay.

I think for all those reasons it's best there is no log message. The fact that the user never got to see this onscreen anyway means only power users that have a log window open could ever see it.

**Comment by asavah** [comment]
I think this was fixed in #9288

**Comment by twinaphex** [comment]
Yeah it should, I just wanted to address something that @negativeExponent brought up.
