### ISSUE TITLE
Nintendo Switch analog sticks only map to multiple buttons on every core

### ISSUE THREAD

**Issue by jeffreydvp** [libretro/RetroArch#9293]
Odd behavior here on my Nintendo Switch. Originally it seemed that any direction I press on either analog stick it would press button Y instead.

After playing Mortal Kombat on the SNES I discovered that I was able to throw a special ability while only pressing the directions of the analog stick.

This appears to mean that both directions, as well as the Y button, are being pressed simultaneously. This also happens whether I am using both joycons paired as one, or used separately

I have built Retroarch on my machine and I am trying to tweak the code to see if I can fix it, but I cannot seem to figure out where this logic lives.

I have been messing with both these files.

`input/drivers/switch_input.c`
`input/drivers/joypad/switch_joypad.c`

Does anyone have any idea which file I should be looking in?

The interesting thing is that the analog sticks work just fine in the Retroarch menu, it only has this behavior while playing games on every core.

**Comment by twinaphex** [comment]
You'd really need to bisect this so that we get a clearer picture of when this issue started to happen.

**Comment by jeffreydvp** [comment]
Fixed it with this PR

https://github.com/libretro/RetroArch/pull/9295

**Comment by twinaphex** [comment]
Oh my bad. I hadn't seen that PR.

Thanks a lot for being able to fix the issue, much appreciated! And my bad for that oversight.
