### ISSUE TITLE
Plugging a 2nd controller replaces the one already in port #0, previously plugged controller moves to port #1.

### ISSUE THREAD

**Issue by bslenul** [libretro/RetroArch#9296]
## Description

Let say I only have my DualShock 4 plugged, I'll have this:

- Port 0: DS4
- Port 1: disabled

Perfectly normal, now if I plug my 8bitdo N30 Pro, the new one "replaces" my DS4 and the DS4 moves to port 1:

- Port 0: N30Pro
- Port 1: DS4

**PLEASE NOTE:**

- Idk if it's important or not but this is when using USB ports, I don't have a bluetooth receiver to test wireless.
- It seems to be only happening when xinput and dinput is selected as joypad driver, no issue with sdl2 driver.
- No issue on my Linux VM (udev driver) and on my Android phone (android driver).

Video of the issue: https://youtu.be/76lMqzjdj6Q

I read about this issue yesterday on Discord and wanted to try, I didn't see any issue about it poping up so here we go.

### Expected behavior

1st controller stays as player 1 when a new one is plugged.

### Actual behavior

2nd plugged controller becomes player 1 and previously plugged controller switches to player 2.

### Steps to reproduce the bug

1. Start RA with a single controller plugged and make sure joypad driver is set to x/dinput.
2. Plug a 2nd controller.
3. Check in Settings > Input the position of the controllers.

### Bisect Results

Doesnt seem to be a new thing, I went back up to 1.6.7 (the oldest I could get from the buildbot) and it's already acting like that.

### Version/Commit

- RetroArch: 1.6.7 stable -> latest 1.7.7 nightly (becfff597b when typing this)

### Environment information

- OS: Windows 10
- It doesn't happen on my Linux VM neither with my Android phone, the N30 Pro is plugged to port 1 when plugged/paired.

**Comment by gouchi** [comment]
Some information on [this comment](https://github.com/libretro/RetroArch/issues/6707#issuecomment-386612906).

**Comment by bslenul** [comment]
Thanks for the link! I like the idea of having to press a button to add a controller just like on Android.

**Comment by bparker06** [comment]
Ditto, something similar to this would be great I think.

![img](https://i.imgur.com/QLYjXcY.png)

**Comment by bslenul** [comment]
Closing, thanks to #16647 ❤️
