### ISSUE TITLE
Cores that support contentless starting can never autosave state

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#9300]
## Description

Any core that allows being started without content cannot autosave states. Even if content is loaded into the core, the autosave state functionality still doesn't work.

I think this is related to the "wrong" use of `contentless` here:
https://github.com/libretro/RetroArch/blob/36ed0ca34fd5d797034ffb81e0807b6c27b034e1/retroarch.c#L3230

The code is written as if `contentless` would mean that there is no content loaded, but it only means `core_does_not_need_content`. Just because a core doesn't need content doesn't mean that it doesn't have content loaded at the moment.

See here: https://github.com/libretro/RetroArch/blob/3432f3b8528e73e94ab8bf1177682833cdff455a/tasks/task_content.c#L2259

where `*contentless = core_does_not_need_content;` is set.

### Expected behavior

Autosave should work as long as I load some content into the core. It should only be disabled if the core is started without content.

### Actual behavior

Just having a core that allows being started without content disables all auto save state functionality for that core.

### Steps to reproduce the bug

1. Load a core that supports contentless starting
2. Load content
3. Enable Auto save state and Auto load state
4. Observe no autosaving ever occurs 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: latest nightly August 13

### Environment information

- OS: any

**Comment by stewbasic** [comment]
It would be useful if auto saving of states worked without content too. A core might use no content if it is self contained (ie doesn't need external assets). It might use auto save to persist data while delegating the details of disk IO to the frontend. These decisions seem orthogonal to me. I didn't see any mention that they are related in the documentation. Should I open a new issue for this?
