### ISSUE TITLE
AI Service bind seems to be non-functioning?

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9316]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I've spent the better half of this morning trying all "routes-of-administration" so to speak, in regards to getting the AI service functioning.  I began with the VGTranslate local server, and tried all 3 of the potential configs.  Google cloud api, ztranslate, and the google/tesseract hybrid.

None of the above functioned on any level with hitting my bind,  evidenced by 0 activity on my google cloud account and my calls queue on ztranslate staying full.

Theres no notification on screen, no text translated/pops up, and no pausing of the screen to capture.

retroarch.cfg is set up as per the docs. 

I changed over to the non-local ztranslate only url within the retroarch.cfg - this failed as well.  So ultimately i realized it likely wasnt an issue with my set up/config or use of the vgtranslate local server, but retroarch never passing anything along regardless of medium.

I'm not sure if the newspage/docs are in preparation and this is something that isnt fully implemented yet or im flubbing somewhere.  Only one way to make sure unfortunately - harass you guys. 

I was concerned that trying an english rom simply would pick up that its an english rom and due zilch, so tried japan only roms as well.  Same result. 

### Expected behavior

The AI service to engage, pause, screencapture, translate when the assigned hotkey for AI service is set.

### Actual behavior

Absolutely nothing happens.   Like ive pressed nothing at all. 

### Steps to reproduce the bug

1. in my current specific case/config - add 
ai_service_url = "http://ztranslate.net/service?output=image&target_lang=En&source_lang=Ja&mode=Fast&api_key=<yourztranslatekey>"
to your retroarch config and set ai_service_enable= "true"
2. Assign a hotkey to the AI Service under hotkeys (in my case v)
3. Start a rom and mash the key.   
4. Be sad.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.7 140d0e180d

### Environment information

- OS: Windows 10

**Comment by BarryJRowe** [comment]
I spoke with klepp, and it seems like the issue is resolved now.
