### ISSUE TITLE
[feature request] Include neocd core in the buildbot :P

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9321]
Figured id get this in.  Bparker said make a stink for inclusion here - so thats what im doing.

As per my other issue report, the subsystem stuff ala playlist is incomplete and broken.   Having this core in circumvents that issue entirely.    Plus more options are a win.

https://github.com/libretro/neocd_libretro

for now i built it myself which caused issues with dependencies which left me having to build retroarch myself which leaves me without the ability to serial-update via stellar like I usually do..  SO youd be doing me a great personal service allowing me to return to regular updating with stellar and doing everyone else a service by having a core available that has no issues caused by subsystem AND chd support.

/lobby

**Comment by gouchi** [comment]
Hi,

It should be better to open an issue to the [libretro-super repository](https://github.com/libretro/libretro-super).

Thank you.

**Comment by klepp0906** [comment]
gotcha, thank you
