### ISSUE TITLE
Underhanded actions of developers/moderators

### ISSUE THREAD

**Issue by dag420** [libretro/RetroArch#9349]
Description
I personally donated approx $300 to retroarch project, most of it was mailing a ps4 1.72 fw to a developer in a foreign country. I was a patreon for a brief time (3 months). Today I rejoin the discord and am banned within 2 minutes. My previous discord account got deleted so I re-introduced myself. 
### Expected behavior
To have my re-introduction either ignored or accepted. 
### Actual behavior
A moderator banned me from the discord permanently. They accused me of breaking rule #4 but I was describing how my discord account was deleted. Rule #4 was not broken in any way. 
### Steps to reproduce the bug
1. Donate hundreds of dollars
2. Get banned
3. ????????
4. Profit
### Bisect Results
I once bisected a frog in middle school.
### Version/Commit
I cant commit to donations when I get banned. Sorry. It feels like I was deleted from the community. 
### Environment information
Colder, maybe 62F? 
- OS: Windows
- Compiler: paypal and ups

**Comment by twinaphex** [comment]
Talk to me on Discord. My account name is Autechre.

**Comment by dag420** [comment]
Good sir, I need the tail or I cant dm. As I am banned from the discord. After giving me the tail #1234 or whatever please close this as this is not a developer issue. It is a personel problem.

**Comment by twinaphex** [comment]
Autechre#6315
