### ISSUE TITLE
(Windows) Non uniform keyboard handling

### ISSUE THREAD

**Issue by heuripedes** [libretro/RetroArch#935]
On Windows, RetroArch seems to use two different ways of handling keyboard, the first is through DirectInput, where it correctly queries the current keyboard state but doesn't support proper polling of key events. The second way is through WndProc-based key event handling, which calls `win32_handle_keyboard_event()` and eventually `input_keyboard_event()` upon WM_KEY\* and WM_SYSKEY\* messages arrivals.

The issues I noticed are:
1. WndProc-based keyboard handling code paths, which live in `d3d_ctx.c` and `wgl_ctx.c`, are never toggled off when you pick a different input driver. This causes some situations where input_keyboard_event() is called twice when you press a key.
2. The `dinput` driver does not call `input_keyboard_event()`. This makes the user unable to change the keybinds if he decides to use a non win32 video driver like sdl/sdl2 or if the wgl context creation fails.
3. For some reason the scancodes returned by the WM_KEY_/WM_SYSKEY_ messages do not match the DirectInput ones specified in `rarch_key_map_dinput`, e.g. if you press the right arrow you get `DIK_NUMPAD6` instead of `DIK_RIGHT` which results in wrong key bindings when the user tries to change them from RGUI.

~~From what I've read and with my almost absent Win32/DirectX knowledge, I think that the Windows port might benefit from using [PeekMessage()](http://msdn.microsoft.com/en-us/library/windows/desktop/ms644943%28v=vs.85%29.aspx) instead of a WndProc()-based message loop.~~

**Comment by Oggom** [comment]
@twinaphex 
Issue 3 is still present on my end, the arrow keys cannot be mapped through RGUI.
Pressing them always results in the numpad keys being registered instead.

**Comment by twinaphex** [comment]
Regarding issue 1 - I took care of that now, both the Direct3D and WGL codepaths should now reuse the same common code for that.

Regarding 2 and 3 - we should still look into that.

**Comment by saftle** [comment]
This was reproducible for me on Win 8.1 with SDL2 as my input driver.

**Comment by berserkingyadis** [comment]
Same prob, Windows 10, SDL2 and dinput driver (arrow keys -> numpad)
