### ISSUE TITLE
Playlist Matching thumbnails to Line 2 "Rom Name" suggesting to use File Name in Line 1 instead

### ISSUE THREAD

**Issue by amartens79** [libretro/RetroArch#9357]
RetroArch 1.7.7
OS PS Vita (seems to be relevant to all OS)

Only affects MAME or FBA.  All other systems eg SNES, Game name and File name is the same

When creating playlists, for MAME or FBA, an XML file is required to ensure the Playlist displays the actual game name.
Eg:
Line 1 - ux0:/roms/Mame - 2003/dkong.zip
Line 2 - Donkey Kong (USA)

It is impossible to match a zip (dkong .zip) file name to an XML game name (Donkey Kong (USA) with any File Matching software, I am not aware of any such software.

Suggestion is to use the Game name in Line 1 ux0:/roms/Mame - 2003/**[dkong.zip]** for the purpose of matching Arcade and FBA Thumbnails.  This will work for for all other systems eg Mega Drive, SNES as well, etc

This is also the format used by many other front ends whereby artwork/thumbnails are matched to the rom file name.

Many thanks and would to see this implemented

**Comment by RobLoach** [comment]
Dup https://github.com/libretro/RetroArch/issues/9359
