### ISSUE TITLE
(Windows) Add Raw Input driver

### ISSUE THREAD

**Issue by heuripedes** [libretro/RetroArch#936]
Windows' [Raw Input](http://msdn.microsoft.com/en-us/library/windows/desktop/ms645536%28v=vs.85%29.aspx) interface (`WM_INPUT` messages) provides lower level access to the input devices and should also provide better latency than DirectInput in general since DirectInput is basically a Raw Input wrapper/translator running in a separate thread and hooks WndProc(). Raw Input also supports [higher resolution](http://msdn.microsoft.com/en-us/library/windows/desktop/ee418864%28v=vs.85%29.aspx) of mouse movements and doesn't implement mouse acceleration.

**Comment by twinaphex** [comment]
This has since been added.
