### ISSUE TITLE
Building on Android: are the Libretro Docs instructions still up to date? If not, I can write an update.

### ISSUE THREAD

**Issue by thebunnyrules** [libretro/RetroArch#9362]
I noticed that the build instructions for android (given at: http://buildbot.libretro.com/assets/frontend/assets.zip) seem to be out of date. 

For example:
```

android update project --path .
android update project --path libs/googleplay/
android update project --path libs/appcompat/ # this doesn't seem to exist anymore

```
"android update project" can't be used anymore in new versions of the "android" executables. 

Also, instructions are for an ant build. Although phoenix-legacy folder still has build.xml file in it, the phoenix folder uses gradle. 

Am I safe to assume, the gradle version is the one being built now or is it the ant one?

In either case, I was unable to build project with ant but was able to build it with gradle. Problem is that it wasn't very stable.

I have a few questions:

(1) Was I wrong in assuming the gradle folder is the currently supported one? Is the gradle build experimental and should I be putting more energy into getting the ant build to work? If I should use ant: what NDK, SDK and Platform Tools version should I use? What version of JAVA? 

(2) If gradle is what you're now using as the main build platform: what NDK, SDK and Platform Tools version should I use? 

(3) Are the assets mentioned in the Libretor Docs instruction (cores, info and overlays), the only assets I should put in the phoenix/assets folder? I'm asking this because my build had no front-end assets (like fonts, icons etc...). Furthermore, the cores I included were not detected.

If the tutorial, is out of date, it would make more than happy to write you a new one for gradlew, once I figure out what I'm doing wrong and make a stable build.

**Comment by twinaphex** [comment]
Yes, an update would be very much appreciated.

**Comment by thebunnyrules** [comment]
No problem. I would be more than happy to do it, once I get it to build properly. Which is the more stable to build? gradle or ant? what NDK and SDK versions should I use?

**Comment by twinaphex** [comment]
Ant is not even available any more in any current NDK build. Just use the latest.

If need be, backup the current docs for Android and just add it as a separate page, but the main page should be for the NDK/SDK that people can actually download.

**Comment by thebunnyrules** [comment]
I can write instructions based on what I've done so far but, although I have succeeded in building RetroArch with gradle many times, the builds are not stable and are missing the assets I've added to them. At best, my instructions now, would be incomplete at this point.

Stability Wise:
I'm getting crashes whenever I make a drag gesture. Any ideas what could cause this? Some of the cores didn't compile in libretro-super? Is it possible that I am missing so vital cores in phoenix/assets/cores? 

Assets Wise:
None of the cores I compiled or the frontend assets I've added to phoenix/assets ended up being used by the apk. They've gotten packed into the apk (I can tell by looking at file size) but it's as if RetroArch doesn't know they're there. So the app doesn't see the cores, fonts and icons are missing. Here is the directory structures of phoenix/assets:

assets/cores
assets/info
assets/overlays
assets/<all the contents of assets.zip: glui, menu_widgets etc...> (downloaded from http://buildbot.libretro.com/assets/frontend/assets.zip)

I guess I'm going to keep trying things until it works but if you have any ideas what I'm doing wrong, I'd appreciate any pointers.

**Comment by thebunnyrules** [comment]
Well, Stability issue was resolved. I'm going to write the instructions (even though assets issue has not been resolved).

**Comment by thebunnyrules** [comment]
> Ant is not even available any more in any current NDK build. Just use the latest.
> 
> If need be, backup the current docs for Android and just add it as a separate page, but the main page should be for the NDK/SDK that people can actually download.

I've committed the new build instructions. Check them out.

**Comment by rsn8887** [comment]
Awesome, thanks! I am very interested in the new docs but am too blind to find them. Could you give a link?

If not done already could you include docs on how to build cores for Android? It took me forever to find out that cores are now just build by
installing latest official ndk, and simply typing ```cd jni
ndk-build``` since the cores all have a jni directory now.

**Comment by thebunnyrules** [comment]
oh wow, thanks. I'll update the docs as soon as I test this.

Here is the commit, I made it in a for of libretro/docs. I think I need to do a pull request for it to get merged but I'm not too sure how to go about it (I'm new on github).

https://github.com/libretro/docs/commit/5cb0739349ea0c03e95928a05e507693b8f188c7#diff-b867c84402602d2ac31a98eb993d4565

**Comment by rsn8887** [comment]
The procedure to get it merged is to make a pull request :)

**Comment by thebunnyrules** [comment]
Thanks. I kind guessed as much but the pull request keeps telling me there is no difference between my fork and the main. I'll figure it out. ;) Hey I just remembered. Check out the instructions. You don't actually need to go to each core's /jni folder to do the build. Libretro supplied a script that does it all for you.
-------- Original message --------From: rsn8887 <notifications@github.com> Date: 2019-08-30  8:56 a.m.  (GMT-05:00) To: libretro/RetroArch <RetroArch@noreply.github.com> Cc: thebunnyrules <mo.mashi69@gmail.com>, Author <author@noreply.github.com> Subject: Re: [libretro/RetroArch] Building on Android: are the Libretro Docs instructions still up to date? If not, I can write an update. (#9362) The procedure to get it merged is to make a pull request :)

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/libretro/RetroArch/issues/9362?email_source=notifications\u0026email_token=ADD5NZCAKZ4WYEX66MH2DN3QHEKJHA5CNFSM4IPN47EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5RSLVA#issuecomment-526591444",
"url": "https://github.com/libretro/RetroArch/issues/9362?email_source=notifications\u0026email_token=ADD5NZCAKZ4WYEX66MH2DN3QHEKJHA5CNFSM4IPN47EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD5RSLVA#issuecomment-526591444",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by thebunnyrules** [comment]
Ok, I made a pull request.

**Comment by thebunnyrules** [comment]
Ok. I finished the new docs. The pull request here:

https://github.com/libretro/docs/compare/master...thebunnyrules:master
