### ISSUE TITLE
[QT] Show desktop menu on startup does not launch qt-ui

### ISSUE THREAD

**Issue by negativeExponent** [libretro/RetroArch#9368]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

QT UI does not launch at startup when option "Show desktop menu at startup" is enabled.

### Expected behavior

Enabling "Show desktop menu at startup" option should launch the qt-ui at startup as indicated

### Actual behavior

no qt-ui is launched. launching it manually with F5 runs it normally so it not that the ui is broken on my end.

### Steps to reproduce the bug

1. launch retroarch.
2. goto settings > user interface and enable "Show desktup UI at startup"
3. close retroarch and reopen

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit] 1.7.8 - 2cad33ba9e

### Environment information

- OS: [The operating system you're running] arch
- Compiler: [In case you are running local builds] gcc 9.1.0

**Comment by Tatsuya79** [comment]
It's working fine here on win7 x64.
Do you have settings like this in "user interface"?
![Untitled-1](https://user-images.githubusercontent.com/6266038/63756686-1185d800-c8b9-11e9-85fd-99944d74b561.png)

**Comment by axredneck** [comment]
Same issue for me. Arch Linux. Retroarch 1.7.8 has this issue but 1.7.7 doesn't.
[My retroarch.cfg](https://github.com/libretro/RetroArch/files/3546897/retroarch.cfg.zip)

**Comment by negativeExponent** [comment]
> Same issue for me. Arch Linux. Retroarch 1.7.8 has this issue but 1.7.7 doesn't.
> [My retroarch.cfg](https://github.com/libretro/RetroArch/files/3546897/retroarch.cfg.zip)

there is a cheevos token in your config, not sure if its a security risk to share that.

**Comment by axredneck** [comment]
2f7050edefcac71aa1d37c20cc8ed4b90cb3348b is the first bad commit
commit 2f7050edefcac71aa1d37c20cc8ed4b90cb3348b
Author: twinaphex <libretro@gmail.com>
Date:   Mon Jul 15 21:06:48 2019 +0200

    Remove ui companion null

**Comment by n1ghttrap** [comment]
Seconding this.  Latest nightlies and redist downloads are failing to load the Desktop Menu

**Comment by negativeExponent** [comment]
fixed. thanks
