### ISSUE TITLE
Assertion failed when using d3d12

### ISSUE THREAD

**Issue by azumukupoe** [libretro/RetroArch#9372]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

This prompt shows up when exiting full screen
```
---------------------------
MinGW Runtime Assertion
---------------------------
Assertion failed!

Program: C:\Users\azumu\AppData\Roaming\RetroArch\retroarch.exe
File: gfx/common/d3d12_common.c, Line 376

Expression: 0
---------------------------
中止(A)   再試行(R)   無視(I)   
---------------------------

```

### Expected behavior

Exit full screen

### Actual behavior

RetroArch crashes

### Steps to reproduce the bug

1. Exit full screen by pressing F or F5
2. The prompt shows up
3. RetroArch crashes after interacting with the prompt
### Bisect Results

It happened after changing the video driver to d3d12.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.8

### Environment information

- OS: Windows 10
- Compiler: [In case you are running local builds]

**Comment by ggdrt** [comment]
Can confirm that d3d12 is working again from changes reverted in https://github.com/libretro/RetroArch/commit/718d65d95d4eab60f332d16e003cf36f8544a310. @twinaphex
