### ISSUE TITLE
Menu in window mode is in system lamguage

### ISSUE THREAD

**Issue by azumukupoe** [libretro/RetroArch#9373]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Language is set to English but menu in window mode is in Japanese

### Expected behavior

English menu

### Actual behavior

Japanese menu
### Steps to reproduce the bug

1. Set language to English
2. Restart
3. Menu is still in system language

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.8

### Environment information

- OS: Windows 10
- Compiler: [In case you are running local builds]

**Comment by bparker06** [comment]
Should be fixed in 4e9cd6ff3e.
