### ISSUE TITLE
[glcore] [regression] shaders don't work

### ISSUE THREAD

**Issue by axredneck** [libretro/RetroArch#9376]
## Description

Applying shaders does nothing to picture when glcore is used.

### Expected behavior

Loading shader preset should affect picture

### Actual behavior

No shaders, just bilinear filtering.

### Steps to reproduce the bug

1. Enable glcore (i also tried vulkan and it's not affected)
2. Load game/core
3. Load your favorite shader preset
3. Suck a paw

### Bisect Results

Maybe i'll try later if i will have time...
At least Retroarch 1.7.7 is good and 1.7.8 is bad.

### Version/Commit

Retroarch Git version 25170f3615 (retroarch-git from AUR)

### Environment information

- OS: Arch Linux
- Compiler: GCC 9.1.0
- Nvidia Geforce GTX 1050, driver v430.40

[My retroarch.cfg](https://github.com/libretro/RetroArch/files/3546967/retroarch.cfg.zip)
[retroarch.log](https://github.com/libretro/RetroArch/files/3546970/retroarch.log)

**Comment by axredneck** [comment]
p.s.
For some reason Retroarch 1.7.8, unlike 1.7.7, doesn't open .slangp shaders with glcore enabled, only .glslp ones.

**Comment by axredneck** [comment]
Can i somehow bisect without recursively git-cloning all this "libretro-super" behemoth ?

**Comment by LazyBumHorse** [comment]
Hm... the log says
> [INFO] [GLCore]: Found GL context: x

so it should be using x_ctx.c and that only sets GLSL when `video_driver_get_ident()` isn't "glcore"
https://github.com/libretro/RetroArch/blob/ed8189bb913b5e5432d74e518f24044e5738a1ae/gfx/drivers_context/x_ctx.c#L1295
But how could that be?

Can you try turning off threaded video just to check if there's some funky business going on?

> Can i somehow bisect without recursively git-cloning all this "libretro-super" behemoth ?

You can clone this repo and if you have all the dependencies:
```
./configure
make clean
make -j4
```

**Comment by axredneck** [comment]
I disabled threaded video and now shaders work.

**Comment by LazyBumHorse** [comment]
So it's funky business indeed, I'm pretty sure this is what happens:

If threaded video is on, video_thread_wrapper.c is used and it calls the video driver `init`:
https://github.com/libretro/RetroArch/blob/ed8189bb913b5e5432d74e518f24044e5738a1ae/gfx/video_thread_wrapper.c#L338-L344
and that tries to set the context driver
https://github.com/libretro/RetroArch/blob/ed8189bb913b5e5432d74e518f24044e5738a1ae/gfx/drivers/gl_core.c#L968-L973
But `video_context_driver_set` tries to set a variable on another thread and this is where this seemingly impossible scenario stems from... probably.

**Comment by axredneck** [comment]
```
719555bae156f24201026537f2e710f148a63c93 is the first bad commit
commit 719555bae156f24201026537f2e710f148a63c93
Author: LazyBumHorse <CirilCatington@gmail.com>
Date:   Tue Jul 2 14:05:47 2019 +0200

    Overhaul shader loading logic, add --set-shader CLI option
```

**Comment by LazyBumHorse** [comment]
I was able to reproduce and I found the issue!
It's that `video_driver_get_ident()` returns "Thread wrapper", not "glcore" inside the context driver.
I also checked: this was a problem before my commit.

This string is hardcoded in the video driver - like all of them:
https://github.com/libretro/RetroArch/blob/ed8189bb913b5e5432d74e518f24044e5738a1ae/gfx/video_thread_wrapper.c#L1306
But there does exist `video_thread_get_ident`:
https://github.com/libretro/RetroArch/blob/ed8189bb913b5e5432d74e518f24044e5738a1ae/gfx/video_thread_wrapper.c#L1405-L1413
So all that's needed is to call it instead.

It's still not thread-safe, but this does fix the main issue at hand (already tested).
