### ISSUE TITLE
(iOS) Scanning Music

### ISSUE THREAD

**Issue by jet082** [libretro/RetroArch#9378]
## Description

Scanning music does not add any .flacs to the music list on iOS, even though ffmpeg does work and the files do play if loaded directly. This means you cannot use the audio mixer, however.

### Expected behavior

Scanning music should add music files to music list.

### Actual behavior

Scanning directories or scanning individual files does not add them to the music list.

### Steps to reproduce the bug

1. Scan File/Scan Directory
2. Select file/directory
3. File is scanned or directory shows nothing in it
4. No files are added to the music list

Alternatively:

1) Select "Load Content"
2) Select the .flac file
3) It plays successfully with the ffmpeg core, but is not added to the Music list, even if "Automatically add content to playlists" is enabled

### Bisect Results

????

### Version/Commit

- RetroArch: 1.7.8 (github)

### Environment information

- OS: iOS 12.4
- Compiler: CLANG/LLVM

**Comment by twinaphex** [comment]
Flsc support is probably not builtin for RetroArch iOS. This could be done however.
