### ISSUE TITLE
Crash on 1.7.8 when soft-patching

### ISSUE THREAD

**Issue by khanson679** [libretro/RetroArch#9381]
## Description

After upgrading to 1.7.8, games with an IPS file stored alongside for soft-patching fail to load. Instead, Retroarch crashes immediately. Based on terminal output, this happens during soft-patching. Also, games that are not soft-patched are unaffected.

I tested several NES and SNES games, with both cases for each console. I'm using Nestopia and bsnes-mercury-performance, for what it's worth. Zipped or unzipped ROM makes no difference.

### Steps to reproduce the bug

1. Store IPS patch with name matching ROM or zip file.
2. Load game by any method
3. Crash

### Version/Commit

- RetroArch: 1.7.8, Git hash 84281d3 (according to terminal)

### Environment information

- OS: Ubuntu 19.04, PPA

**Comment by twinaphex** [comment]
@brenodantas10 Can you check if some regression occurred here?
