### ISSUE TITLE
Need 1.7.8 release tarballs or advice on creating my own

### ISSUE THREAD

**Issue by edrozenberg** [libretro/RetroArch#9387]
Unlike previous releases (1.7.7 etc), the 1.7.8 release does not currently include the full .xz, .zip tarballs among the release assets.

After some digging around I attempted to use `retroarch-release.sh` and `libretro-fetch.sh` to create my own but no luck so far. It deleted the full git checkout I had already downloaded, and then `libretro_fetch` cr*pped out with `libretro_fetch:No URL set to fetch retroarch via git.`. I'm sure I could eventually figure out it after digging into these scripts for a few or a lot more hours - but any quick hints would be very welcome and I'm sure many others would appreciate it as well.

**Comment by hizzlekizzle** [comment]
https://github.com/libretro/RetroArch/archive/v1.7.8.tar.gz

how's that?

**Comment by RobLoach** [comment]
Unsure what you're looking for, but the URL that hizzlekizzle provided is the full .zip, along with https://github.com/libretro/retroarch-assets, and all the other assets.
```
./libretro-fetch.sh retroarch
```
if you really wanna use the script.

**Comment by edrozenberg** [comment]
Thanks, what I was referring to is a full download for 1.7.8 similar to https://github.com/libretro/RetroArch/releases/download/v1.7.7/RetroArch-1.7.7.tar.xz

The 1.7.8 release currently has only 2 Assets, where previous releases provide 6 assets.

I'll eventually figure it out, or maybe RetroArch will later add the other 4 assets they normally provide.

**Comment by RobLoach** [comment]
Which assets?

**Comment by edrozenberg** [comment]
Specifically 1.7.7 has `RetroArch-1.7.7.tar.xz (211 MB)` and there is no such similar asset for 1.7.8, only the source code tarball which is 27 MB and is missing all the UI icons, fonts and probably other things as well. 

From https://github.com/libretro/RetroArch/releases :

**v1.7.7**
Assets:
RetroArch-1.7.7.tar.xz 211 MB
RetroArch-1.7.7.zip 304 MB
Source code (zip) - v1.7.7.zip 33 MB
Source code (tar.gz) - v1.7.7.tar.gz 29 MB

**v1.7.8**
Source code (zip) 32 MB
Source code (tar.gz) 27 MB

**Comment by twinaphex** [comment]
Take this up with @hizzlekizzle , I don't know what you expect me to do here.

**Comment by RobLoach** [comment]
Didn't know we actively use GitHub release assets. I'd recommend using the buildbot ones for now:
http://buildbot.libretro.com/stable/1.7.8/

**Comment by edrozenberg** [comment]
None of those locations provide the asset previously available with 1.7.7, 1.7.6, and older. Since my current Linux package build process uses that asset type previously available with older versions I'll keep using 1.7.7. There's nothing I really need from 1.7.8 for the moment. Thanks.

**Comment by RobLoach** [comment]
Which assets? What do you expect to be there that is not there? Which files? Literally everything that was in the release you're refering to in 1.7.7 is available in repositories in http://github.com/libretro

**Comment by edrozenberg** [comment]
Maybe I'm using the word asset wrong, and I'm also not enough of a RetroArch insider to know how to assemble the xz archive I was looking for.

I use a SlackBuild from https://slackbuilds.org/repository/14.2/games/RetroArch/. I know nobody uses Slackware, RetroArch doesn't support Slackware, etc. I'm not asking for help with any of this.

This Slackbuild works with a download from the following url: https://github.com/libretro/RetroArch/releases/download/v1.7.7/RetroArch-1.7.7.tar.xz

I tied changing the 1.7.7 to 1.7.8. and this doesn't work. Because there is no RetroArch-1.7.8.tar.xz currently available at this URL. I don't know why it's not available, and that's fine, I'll keep using 1.7.7 until some future time when I have the hours to invest to figure out how to create this 200+ MB xz RetroArch archive from the various GitHub project locations. Thanks again.

**Comment by edrozenberg** [comment]
I compared the contents of https://github.com/libretro/RetroArch/releases/download/v1.7.7/RetroArch-1.7.7.tar.xz with the contents of the 1.7.8 source and I created my own RetroArch-1.7.8.tar.xz (245 MB) by adding a bunch of GitHub projects to the `media` directory:

Instructions for others who might need to do the same:

Download the zip files for each of these projects:
- https://github.com/libretro/common-overlays
- https://github.com/libretro/common-shaders
- https://github.com/libretro/libretro-database
- https://github.com/libretro/retroarch-assets
- https://github.com/libretro/retroarch-joypad-autoconfig

Copy contents of each of the zip downloads to the `media` directory inside the 1.7.8 source as follows:
- Contents of `common-overlays` to `media/overlays`
- Contents of `common-shaders` to `media/shaders_cg`
- Contents of `libretro-database` to `media/libretrodb`
- Contents of `retroarch-assets` to `media/assets`
- Contents of `retroarch-joypad-autoconfig` to `media/autoconfig`
