### ISSUE TITLE
(Linux) Can not configure for EGL + GLES2 on ARM/Linux

### ISSUE THREAD

**Issue by vanfanel** [libretro/RetroArch#9396]
Hi there,

As always, I am building latest RetroArch release on GNU/Linux Debian ARM64 (aarch64).

The first problem I am finding is with EGL headers location. I configure with:
`
CFLAGS="-O3 -march=armv8-a+crc -mtune=cortex-a53" CXXFLAGS="-O3 -march=armv8-a+crc -mtune=cortex-a53" ./configure --disable-ibxm --disable-vg --disable-x11 --disable-wayland --disable-sdl2 --disable-al --disable-cheevos --disable-ffmpeg --disable-networking --disable-libretrodb --enable-udev --disable-sdl --disable-pulse --disable-oss --disable-freetype --disable-7zip --disable-imageviewer --disable-rjpeg --disable-rbmp --disable-rtga --enable-egl --enable-opengles --disable-flac --disable-qt --disable-materialui --disable-xmb --enable-rgui --disable-ozone --disable-menu_widgets --disable-easteregg --disable-cdrom`

And I get:
```
Checking operating system ... Linux 
Checking for suitable working C compiler ... /usr/bin/gcc works
Checking for suitable working C++ compiler ... /usr/bin/g++ works
Checking for pkg-config ... /usr/bin/pkg-config
Checking for availability of switch -std=gnu99 in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-result in /usr/bin/gcc ... yes
Checking for availability of switch -Wno-unused-variable in /usr/bin/gcc ... yes
Checking function sd_get_machine_names in -lsystemd ... no
Checking presence of package bcm_host ... no
Checking function bcm_host_init in -lbcm_host ... no
Checking presence of header file EGL/eglext.h ... no
Build assumed that EGL/egl.h exists, but cannot locate. Exiting ...
```

I use MESA 19.1.3 for my GLES implementation (Rpi3b+, vc4 MESA driver), and other libs and games using GLES/EGL build fine, like libSDL2, etc.
Both egl.h and eglext.h DO exists in my syste, of course:
```

pi@raspi:~/src/RetroArch-1.7.8$ ls /usr/include/EGL/   
egl.h  eglext.h  eglextchromium.h  eglmesaext.h  eglplatform.h
```

So its RetroArch that is unable to find them on standard locations.

**Comment by vanfanel** [comment]
I have tried to build RetroArch release 1.7.8 v3 on ARM/Linux, and still I can not build it because if fails to locate EGL libs as previous 1.7.8 versions.
Is GNU/Linux a minor target now? What is going on?

**Comment by vanfanel** [comment]
Ah, found the problem. Since some other people will find similar issues with recent MESA in the future if you built MESA manually without GLX suppot (and hence without EGL on X11 support), you simply have to pass `-DMESA_EGL_NO_X11_HEADERS` to the configure CFLAGS. And RetroArch will configure finding the EGL headers in a working state.
Closing the issue, this has nothing to do with RetroArch...

**Comment by Langerz82** [comment]
Also had this problem with EmuELEC building Retroarch following line in file: package.mk in function pre_configure_target()
```
export CFLAGS="$CFLAGS -O3 -fno-tree-vectorize -DMESA_EGL_NO_X11_HEADERS"
```
@vanfanel thanks heaps mate for the solution.
