### ISSUE TITLE
iPega 9083 on iOS

### ISSUE THREAD

**Issue by Loader23** [libretro/RetroArch#9403]
Hi,

I bought an iPega 9083 to play with my non-jailbroken iPad but I can not assign any buttons. Pressing any of the D-Pad Buttons makes the selection jump to some point in the menu but not how it should work.
Any help is greatly appreciated.

**Comment by yoshisuga** [comment]
Go to Settings -> Input and make sure "Keyboard Gamepad Mapping" is enabled, and try the "iPega PG-9017" option for the "Keyboard Gamepad Mapping Type".

If that doesn't work, you might be out of luck. I don't think that device is supported. It doesn't look like it has iCade-like support (which is what the Keyboard Gamepad Mapping is). It's best to invest in an mfi controller, or a Xbox One/PS4 controller when iOS 13 is released. If you're iPad is old and can't run iOS 13, then your best bet is an mfi controller.

**Comment by Loader23** [comment]
Those Options are enabled. I have also testet it with iOS 13 but no luck.
But thanks for your help.

**Comment by jbarros35** [comment]
Same here, iPhone 6s. That's just awful, I can't really believe that does not work.
Ipega is a major brand... how can it be not supported what's the problem at all? Its paired, IOS recognised it, how can it not work and be mapped? What's missing?
Using xbox controller its just not an option, these controllers are much more portable and better than the other options. They allow the device to be taken anywhere we want to.

**Comment by Kung-Foo-Kamel** [comment]
The 9083 and 9083S only support touch screen simulation mode on iOS and iPadOS, it does support MFI mode or standard gamepad mode like and XBOX or PS controller, you will need to setup touchscreen buttons, take a screen shot, then load that into  the shootingGame app and configure it.

These game pads suck, they have a nasty deadzone issue, no MFI support, and they wont work at all after you upgrade past ios 13.4, also the joysticks are above the buttons, making them dam awful for any real gaming.
