### ISSUE TITLE
FBNeo importing content only works when Scan Without Core Match: ON 

### ISSUE THREAD

**Issue by rsn8887** [libretro/RetroArch#9407]
## Description

When scanning any FBNEo rom via `Import Content`, e.g. my crc32-verified rom 1941.zip, it doesn't show up in the FBNeo playlist. I have the core installed, everything updated etc.

When I turn ON `Settings->Playlists->Scan without core match`, then it works.

### Expected behavior

The rom should appear in the FBNeo playlist also with `Settings->Playlists->Scan without core match` OFF as long as I have the core installed.

### Actual behavior

See above

### Steps to reproduce the bug

1. Import Content
2. Import Single File
3. Select a FBNeo rom, e.g. 1941.zip
4. Observe it is not added to playlist
5. Repeat after Settings->Playlists->Scan without core match:ON
6. Observe working

### Bisect Results

Never worked.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: Latest Nightly 08/30/2019

### Environment information

- OS: Switch

**Comment by rsn8887** [comment]
I am not sure if the seemingly wrong system_id here is the problem:
https://github.com/libretro/libretro-super/blob/d554e87f6b4d537beefce6997277d4ee0a471672/dist/info/fbneo_libretro.info#L8

**Comment by RobLoach** [comment]
Mind moving this issue over to https://github.com/libretro/libretro-database ? We could compare CRC values and stuff over there.
