### ISSUE TITLE
Minor issue - repo needs xinput Xbox_One_Controller.cfg autoconfig PID update

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9410]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

So after speaking with wambulance on the RA discord, turns out some of the cfgs were submitted long ago and out of date.  My xbox one controller is being detected as plain jane xinput and not xbox one due to an incorrect PID listing.   Of course ive already updated it manually, but not updating it on your end prevents me from being able to use the online updater.

This is definitely minor, as it functions and maps properly with the xinput label just fine.  By that same token, I imagine fixing it will take a matter of seconds so might as well right? :)

The new PID is 736 whereas its set as 767.  I'm not sure how long ago it changed, but theres a thread from december on the steam forums referencing the new PID here https://steamcommunity.com/app/13540/discussions/0/1693795812298434171/#c1744480967016572070

### Expected behavior

A popup to tell me i have an xbox one controller connected and not an xinput one :)  (nevermind the potential mapping repercussions)

### Actual behavior

It displays and maps as Xinput user 1 on port 0.

### Steps to reproduce the bug

1. pair your xbox one controller to your pc via BT
2. fire up RA
3. note your notification displays as xinput controller rather than xbox controller.

### Bisect Results

A loooooooooong time.  So long that I assumed this was the intended behavior.  Until I noted the DS4 being recognized as a DS4, coupled with speaking with wambulance - I realized it is not. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.78 e4fb5587f7

### Environment information

- OS: win10

**Comment by hizzlekizzle** [comment]
Alright, I changed the wired PID to 736. If that gets you fixed up, just close this issue. If not, let me know.

**Comment by klepp0906** [comment]
wired still worked.  It worked even if all the xbox one cfgs were deleted.  I believe wambulance said he had hard coded a fall back for things like the xbox one controller.

When it wasnt working it was when connected wirelessly via bluetooth.  Changing the PID in autoconfig/xinput/Xbox_One_Controller.cfg or Xbox_One_Controller_Wireless_Adapter.cfg both fix the issue, but I "think" the one we want to change is the former and that is the one I changed.

I think the "Wireless_Adapter" variant applies to the non bluetooth enabled Xbox One controllers that need the microsoft dongle to work.

Hopefully you changed the correct one.  I'll check if it made it through the buildbot tonight and let ya know.  Ty for taking care of it :)

**Comment by klepp0906** [comment]
Yep, already made it through.  Thank you again <3
