### ISSUE TITLE
(RGUI) Small menu with rgui + glcore + motionblur shaders

### ISSUE THREAD

**Issue by negativeExponent** [libretro/RetroArch#9420]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When using a combination of rgui + glcore driver + motionblur shaders the menu becomes very small

![unknown](https://user-images.githubusercontent.com/54053706/64134416-573e2580-ce10-11e9-81a3-914605f67e0a.png)

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. launch RA using rgui and glcore driver
2. load a game (mgba and gb game in this example)
3. apply motionblur slang shaders
4. watch the menu become tiny

### Bisect Results

i have not extensively tested any other combination as stated, though using xmb with glcore + motionblur works, so it cant be the shaders or system compatibility with glcore.

this was verified by over at the #programming_shaders channel in discord

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]  1.7.8 a52130e36

### Environment information

- OS: [The operating system you're running] arch
- Compiler: [In case you are running local builds] gcc 9.1.0

**Comment by RobLoach** [comment]
@jdgleaver Have you run into this before?

**Comment by LazyBumHorse** [comment]
It seems every slang shader which uses `OriginalHistory1` is broken in glcore + rgui in this way.
rgui uses a small frame buffer which could explain why the menu gets so tiny, maybe glcore doesn't properly translate the frame's size or something?

**Comment by jdgleaver** [comment]
Yes, what a peculiar issue!

It can be fixed with the following diff:

```diff
diff --git a/gfx/drivers/gl_core.c b/gfx/drivers/gl_core.c
index 5cf6eb55db..76acada37f 100644
--- a/gfx/drivers/gl_core.c
+++ b/gfx/drivers/gl_core.c
@@ -1593,6 +1593,8 @@ static void gl_core_draw_menu_texture(gl_core_t *gl, video_frame_info_t *video_i
 
    if (gl->menu_texture_full_screen)
       glViewport(0, 0, video_info->width, video_info->height);
+   else
+      glViewport(gl->vp.x, gl->vp.y, gl->vp.width, gl->vp.height);
 
    glActiveTexture(GL_TEXTURE0 + 1);
    glBindTexture(GL_TEXTURE_2D, gl->menu_texture);
```

...but since I don't know much about the gfx drivers, I'm not entirely sure that this is correct.

@LazyBumHorse I think you probably know more about this stuff than me :)
Does the fix look okay to you...?

**Comment by LazyBumHorse** [comment]
@jdgleaver I don't know any more than you, but I did some testing and this works just fine!

What I'm getting from this is that `glViewport(gl->vp.x, gl->vp.y, gl->vp.width, gl->vp.height);` fits the output in the window, respecting aspect ratio, e.g. I'm getting dimensions 1440:1080 aka 4:3 instead of 1920:1080, which is what `glViewport(0, 0, video_info->width, video_info->height);` would stretch it to (if `gl->menu_texture_full_screen` is enabled, which by default it isn't).

**Comment by jdgleaver** [comment]
Thanks for testing!

Yeah, the `glViewport(gl->vp.x, gl->vp.y, gl->vp.width, gl->vp.height);` just applies the current viewport settings - which are configured by RGUI itself while the menu is open (so it ensures RGUI is correctly positioned/scaled).

The `glViewport(0, 0, video_info->width, video_info->height);` is odd - `gl->menu_texture_full_screen` is never, ever true, so I'm not sure what the intended use of it was. (and blindly stretching the texture to the display resolution seems pointless to me)

The `gl` driver seems to handle this differently. I assume this:

https://github.com/libretro/RetroArch/blob/97d91a895c90bfb2e59a45acb3cd70f2aa6c55a8/gfx/drivers/gl.c#L2450-L2456

...means it's applying a different shader before drawing the menu texture (so any shader-related texture history issues are irrelevant)?

Anyway, I don't think the extra `glViewport()` call in the fix can do any harm - so if there are no objections, I'll make a PR  :)

**Comment by LazyBumHorse** [comment]
> The `glViewport(0, 0, video_info->width, video_info->height);` is odd - `gl->menu_texture_full_screen` is never, ever true, so I'm not sure what the intended use of it was. (and blindly stretching the texture to the display resolution seems pointless to me)

Maybe rgui was once intended to always use the whole window like all the other menu drivers do, but it was disabled due to the ugly streching and never considered since then again?
If `menu_texture_full_screen` is never true, we should probably just remove it.

**Comment by LazyBumHorse** [comment]
Hm... `gl_core_set_texture_enable`, or `set_texture_enable` in general (which is called by `video_driver_set_texture_enable`) does set `menu_texture_full_screen`, it's just that it's never called with a `true` value.

It also seems that `set_texture_frame` can set an arbitrary "menu" texture to be used, so better just leave it.

**Comment by jdgleaver** [comment]
Yeah - that's what I meant: it *can* be set true, but never is. I think the `bool full_screen` argument of the `set_texture_enable()` functions could be safely removed, but as you say, who knows what someone might want to do with arbitrary menu textures in the future...

Okay, thanks for the input :)

Time to make that PR...
