### ISSUE TITLE
[Feature Request] Add Automatic Aspect Ratio Adjustment to RGUI

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#9424]
## Description
Currently, RGUI's aspect ratio is either stretched/squished to conform to the running content or display/window size or forced to a fixed aspect which also forces a fixed aspect on the content when the menu is active.

### Expected behavior

RGUI's aspect is changed dynamically based on the display dimensions in fullscreen, or the window dimensions in windowed mode. The aspect ratio of content running behind the menu isn't changed while the menu is active. Like how the ozone menu driver works.

### Actual behavior

With the default lock aspect ratio setting off, the menu is squished or stretched to match the content running, or if no content is running it defaults to 4:3. Even if the aspect is set to something different like 16:9, it is squished to 4:3 or content aspect unless lock aspect ratio is set to fit screen or integer scale.

Locking the menu aspect ratio has it's own problems. ~~If you set it to 16:9 and use either fit or integer lock in fullscreen mode on a 16:9 display, when you enter windowed mode this happens:~~

![going windowed](https://user-images.githubusercontent.com/4565863/64217245-a45edd80-ce8a-11e9-954a-7719ea908005.png)
~~To fix that, you have to toggle the aspect lock option to something else and back so it sizes itself properly for the window. The same type of thing happens when you go from windowed to fullscreen. Also, if you go into the Video section of Settings, the aspect is forced to 4:3 until you toggle the menu aspect ratio lock setting again.~~ Fixed!

The other problem with locking the menu aspect ratio is that it forces content to that aspect while the menu is active:

![content](https://user-images.githubusercontent.com/4565863/64217518-bd1bc300-ce8b-11e9-9e2c-ac4ebe94105d.png)

![contentrgui](https://user-images.githubusercontent.com/4565863/64217533-c4db6780-ce8b-11e9-8968-d41ada560d1c.png)

It's a little jarring to have the content snap between aspect ratios when you open and close the menu.

**Comment by jdgleaver** [comment]
@Awakened0 Yeah - these are valid complaints, and they've bugged me for a while now.

Due to the way the whole system is put together, dealing with this 'correctly' is far more difficult than one might expect (which is why I've left the current hack-ish implementation in place for so long). But after sorting out issue #9420. I *think* I might have a workable solution.

I'll see what I can do  :)

**Comment by jdgleaver** [comment]
Ugh... I take it back. I thought I could use a higher-level viewport trick, but I can't. The actual frame rendering is buried too deep in the gfx driver code.

Basically, to prevent background content from being stretched while the menu is open, we need to modify every single gfx driver. Each of them handles RGUI rendering differently, most of them I don't understand, and most of them I cannot test. So I'm afraid it's just not practical.

I can however fix RGUI not being resized when toggling full screen (or changing the window size). I guess that's something...

**Comment by Awakened0** [comment]
Bummer, that's the thing that bothers me the most. Guess I could use an opaque background to hide it, but I really like seeing the content behind the menu (DOS emulator nostalgia :D). But I'm happy to have some of the other issues addressed, thanks!

**Comment by Ferk** [comment]
> I can however fix RGUI not being resized when toggling full screen (or changing the window size). I guess that's something...

That's definitely something. I was having some problems with RGUI when using a tiling window manager (sway in particular), only when I changed back and forth the aspect ratio option did it look right. I think the change you just made is gonna fix that.

**Comment by jdgleaver** [comment]
@Awakened0 Yeah, it's a shame. I still kinda hope to get the background content aspect ratio fixed at some point (it also affects screenshots taken via the quick menu), but it needs a concerted effort from all the various port maintainers. There are so many other things to work on at the moment - maybe I can ask around if things ever quieten down...  ;)

@Ferk Ah, that's lovely - I'm glad it fixed your issue!
