### ISSUE TITLE
Onscreen Display > Onscreen Notifications setting bug

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9427]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

So as per my recent onslaught of posts - I've apparently deemed it time to go through the settings again.  Check out some new ones, be more thorough with those ive skipped in the past - etc.  Plus with the additional new "modern" notifications I wanted to see what I could potentially do about coloring/sizing/positioning etc.

I ran into the "Include Memory Details" toggle.  Whether it references GPU memory, or system memory - I wouldnt know, as turning it on or off does nothing.  The framerate and Frame count both work properly - but Memory details does not. 

### Expected behavior

Toggling this setting on should display relevant memory information alongside the rest of the information presented when using associated toggles. 

### Actual behavior

Nada!

### Steps to reproduce the bug

1. Simply navigate to Settings > Onscreen Display > Onscreen Notifications
2. Toggle on "Include Memory Details"  (which I assume requires framerate/framecount to be on as well considering the phrasing "include"
3. Note, no memory information is present in menu or with a game loaded.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.78 97d91a895c

### Environment information

- OS: Windows 10

**Comment by LibretroAdmin** [comment]
Should be working by now
