### ISSUE TITLE
[Feature request] Non-generic content icons in the history playlist

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9429]
This may also apply to the "favorites" list, which I dont use personally so im unsure, but should I ever, or for anyone else that does - it should probably be included.

The playlists all use playlist-content.png or some such, to show the proper media icons next to the games in their respective playlists.   This is great.   Unfortunately in the history (and presumably favorites) playlist(s) it shows a generic icon irrespective of what playlist the entry is from.

It would be great to have this updated to display the proper corresponding media icon.

**Comment by jdgleaver** [comment]
Some bad news on this one...

I've checked it over, and the playlist entry icons are implemented in a manner that I didn't expect at all... Basically, the performance overheads of adding per-content icons would be ridiculous, to the point of complete impracticality. It would require some major rewrites to even begin to get this working in an extensible fashion, so I fear this will linger for some time at the bottom of the TODO list  :(

**Comment by klepp0906** [comment]
LOL its okay.  Shame, but totally understandable.  I appreciate you diving into it regardless.   Makes displaying the associated core as per my other report all the more important now though :D (at least for me!)

sounds like lots of things were implemented in a fashion that lacked foresight or are a bit old or without realization of how RA would grow which is understandable.   I know bparker looked into the fact you cant actually hide hidden files or folders in the directory browser (i made a report about it) and said that was going to take a rewrite as well.

#shrug, we're all blessed to have guys like you guys with a talent for code, and as altruistic as you are.

**Comment by sonninnos** [comment]
This has been sorted already.
