### ISSUE TITLE
Launching new ra32 version from command line issues

### ISSUE THREAD

**Issue by BanditTech** [libretro/RetroArch#9430]
## Description

Using hyperspin to launch the RetroArch process using this line:
exe=com.retroarch.ra32/com.retroarch.browser.retroactivity.RetroActivityFuture
will cause Retroarch to open in a seemingly new instance of retroarch.
No settings or configuration files will load, and no controllers will work.
Also only the very first menu options show up, there is nothing beyond the first column.
and the font looks really basic and pixely

If I downgrade back to the 1.7.7 version it works just as normal, but that is launching normally:
exe=com.retroarch/com.retroarch.browser.retroactivity.RetroActivityFuture

### Expected behavior

Adding the .ra32 portion to the launch would open the 32 bit version with its configuration loaded. 

### Actual behavior

Launcher is opening a buggy version of RA that doesnt load the configuration, or allow controller use so it can be configured

### Steps to reproduce the bug

1. Install the ra32 version from the buildbot
2. change the hyperspin launch path for the emulator to exe=com.retroarch.ra32/com.retroarch.browser.retroactivity.RetroActivityFuture
from 
exe=com.retroarch/com.retroarch.browser.retroactivity.RetroActivityFuture
3. Open a game from the list.

### Bisect Results

This is clearly an issue from the deployment to 64bit in the main core between 1.7.7 and 1.7.8 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [1.7.8/nightly ra32]
2019-09-04

### Environment information

- OS: [android]
- Compiler: [BuildBot]

**Comment by BanditTech** [comment]
I am having no luck in modifying the code in hyperspin, it just assumes that retroarch would know where the config files are located :( I have tried all sorts of combinations of the ADB line you posted, this is really a bummer. This change to retroarch completely eviscerated my hyperspin build which was relying on Mame 2010 for all the arcade games.

**Comment by mrfomt** [comment]
@BanditTech Did you figure this out? I have the same problem with ra32.

**Comment by BanditTech** [comment]
unfortunately this seems to be hardcoded into the code of the APK. you would need to decompile the apk and modify the code to point to the proper locations.

**Comment by zach-morris** [comment]
You might be able to trick it by changing the config directory in ra32 to:
```
data/user/0/com.retroarch
```
According to [this](https://hyperspin-fe.com/forums/topic/27358-retroarch-dual-config-trick/), that is where hyperspin assumes the config file is located.  But I'm guessing you need root access to create that folder location.

**Comment by McFarTech** [comment]
Hello. So is there any solution to this yet? As stated v1.7.7 works perfect but anything after that just breaks?

**Comment by mrfomt** [comment]
Its working fine with Retroarch in playstore, but it is missing some cores, mame2010 for example, thats why I want to use ra32.

Tried to change to  data/user/0/com.retroarch but cant access that folder, so cant browse for it in retroarch so cant set it as config folder.

**Comment by McFarTech** [comment]
Its all a bit crappy really. Surely someone can fix this?

**Comment by BanditTech** [comment]
Yes, that someone would be the developer of whatever too is launching retroarch . For Hyperion apk that means this kills any build using ra32 cores. This is why I no longer use ra for those systems

**Comment by McFarTech** [comment]
I only really use RA for the overlays. be great to find an all in one setup that could replace it if this is the case with the current setup

**Comment by mrfomt** [comment]
Tried to decompile the apk and make some changes to the source code, then compiled it again, but the app is broken, it installs but doesnt start at all, so I am doing something wrong. Have googled a lot, but I think I give up. Hope someone with more programming knowledge will fix this :)

**Comment by BanditTech** [comment]
There is still hope with active development of the LaunchBox for android releases. The app is currently working well enough to use, but no where as feature rich as the Hyperspin menus and animations. They plan to continue working on the project, and have made comments as late as last month with hints that they are still working on new features for the app to make it easier to use and have a nicer layout.

**Comment by drmore** [comment]
Found a fix to use ra32.  Download the ra32 .apk and open it in APK editor studio.  Open AndroidManifest.xml in the root folder.  On the first line change package="com.retroarch.ra32" to package="com.retroarch".  Save and close.  Remove any retroarch install from your box, reboot and install the edited apk.   It will now install in the default folder and hyperspin can call it correctly.

**Comment by McFarTech** [comment]
You sir might just go down as an internet hero. Made the change and installed it. Just doing some testing but looking good. Thanks for posting the finding.

**Comment by BanditTech** [comment]
> Found a fix to use ra32. Download the ra32 .apk and open it in APK editor studio. Open AndroidManifest.xml in the root folder. On the first line change package="com.retroarch.ra32" to package="com.retroarch". Save and close. Remove any retroarch install from your box, reboot and install the edited apk. It will now install in the default folder and hyperspin can call it correctly.

This works brilliantly! I had been unable to find any other way of fixing this, and this is so simple! Big thank you for sharing this information.

**Comment by Honosuseri** [comment]
> I am having no luck in modifying the code in hyperspin, it just assumes that retroarch would know where the config files are located :( I have tried all sorts of combinations of the ADB line you posted, this is really a bummer. This change to retroarch completely eviscerated my hyperspin build which was relying on Mame 2010 for all the arcade games.

I have modified the Hyperspin.apk to solely use RetroArch_ra32. You will need to adjust your .ini files in the "settings_Android" folder, it's easy enough to do though.

https://hyperspin-fe.com/forums/topic/42173-hyperspin-modified-for-retroarch-32bit-aka-retroarch_ra32/

**Comment by flatmapthatshit** [comment]
Inspired by Honosuseri, I've modified a version of HyperSpin that can launch all RetroArch releases: Google Play Store, ra_32, aarch64 and even custom builds (as long as their package name starts with com.retroarch).

https://hyperspin-fe.com/forums/topic/42774-modified-hyperspin-apk-for-retroarch-works-with-all-modern-versions/

**Comment by 04mating** [comment]
Hi, 

I am using the Bandit No Clutter Collection on my shield but the Reicast core no longer exists in retroarch, how would I go about modifying the settings to point towards the flycast core instead?

**Comment by flatmapthatshit** [comment]
@04mating , you should ask this in the HyperSpin forums. 

@BanditTech, I think that this issue can be closed right?
