### ISSUE TITLE
Retroarch Lr-Genesis-Plus-GX keep 60 fps but screen scroll is not smooth

### ISSUE THREAD

**Issue by dewenhsu** [libretro/RetroArch#9437]
In RetroPie for Pi3B and The Retro Arena for Odroid XU4, the lr-genesis-plus-gx runs normal without jerky scroll.

But in Odroid N2, the fast scroll ( for example, Thunder Force initial demo screen with big title letter horizontal scroll ) will jerky and not smooth, however the fps keep 60 no drop.
If change to lr-picodrive, there will be no jerky.

I remember long time a go in windows PC I have the same problem and then it was fixed, Is there any method to fix it ? 

Running Retroarch 1.7.8, The Retro Arena. Odroid N2. 

Thank you.

**Comment by hizzlekizzle** [comment]
Try turning off audio sync so that it uses only vsync for throttling.

**Comment by dewenhsu** [comment]
Thanks for the suggestion. I tuen off audio sync, then the speed is too fast  ( 80 fps ) but still jerky scrolling.
The scroll is not smooth but you need to watch carefully to note, but if you play some shmup game with fast scrolling such as MUSHA Aleste, it will be very obeviously.
I take a video of Genesis-Plus-Ex and PicoDrive run the same game to compare.

Genesis-Plus-Gx core . the scroll has minor jerky, you can also test with 007, it is vertical scroll at the beginning. It is smooth at Odroid XU4 and Pi3B, but not in Odroid N2. 
https://youtu.be/yoCzQsbgzC0

PicoDrive core, the scroll is smooth. 
https://youtu.be/v8Rpv_dtHAQ

**Comment by mrjschulte** [comment]
( The 240p test suite has a great bunch of tests that can show scrolling problems quite clearly. )

**Comment by alivesay** [comment]
I can confirm this.  Pi4, Raspbian Buster, vga666.

None of the typical timing/vsync/audio sync/threaded/etc settings make any difference.  Other cores scroll smoothly.

Confirmed in random games as well as 240P Suite scroll test.

Definitely not screen tearing, it's more of a jerky shutter where the screen seems to jump back a few pixels every 1 to 4 seconds.

Visible with both vertical and horizontal scrolling.
