### ISSUE TITLE
Framerate displays N/A when enabled when threaded video is on

### ISSUE THREAD

**Issue by RisingHopperZeroOne** [libretro/RetroArch#9445]
## Description

Framerate only displays N/A when enabled with threaded video turned on, it should show the current fps of the menu and game.

### Expected behavior

Enabling framerate should display the current fps of the menu and game.

### Actual behavior

Framerate only displays N/A when enabled with threaded video turned on.

### Steps to reproduce the bug

0. Enable "threaded video" in settings > video > threaded video
1. Go to "Onscreen Display"
2. Then "Onscreen Notification"
3. Then "Display Framerate"

### Bisect Results

Did a fresh install of the 2019-09-06 nightly and it wasn't working.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: b875a69

### Environment information

- OS: Horizon (Nintendo Switch)
- Compiler: GCC (8.3.0) 64-bit

**Comment by hizzlekizzle** [comment]
Does it start working if you disable threaded video in settings > video?

**Comment by RisingHopperZeroOne** [comment]
Yes, it works when threaded video is disabled.
