### ISSUE TITLE
[Feature Request] (Cheevos) Achievement Transitions/Stacking

### ISSUE THREAD

**Issue by Zenjir0** [libretro/RetroArch#9450]
## Description

As of Retroarch 1.7.8 v2 I have noticed that in edge cases where 2 or more achievements trigger at the same time, one or more of the widgets displaying the achievement will mask the other, and makes it seem that only one achievement was triggered.

My personal experience seeing this in action was during "Banjo-Kazooie" for the N64 using Mupen64plus-Next. After I got the last Jiggy it looked like only one triggered when in reality both did triggered.

### Expected behavior

It would be nice if the achievement widget would either
- Stack horizontally or vertically when 2 or more achievements are triggered
- Transition in a timely fashion, as in the first achieve drops down, waits 2-3sec then the next drops down.

**Comment by wilhitewarrior** [comment]
I've noticed this too

**Comment by meleu** [comment]
solved in #10175
