### ISSUE TITLE
Vulcan prevents starting RetroArch.

### ISSUE THREAD

**Issue by alexb3d** [libretro/RetroArch#9453]
Start RetroArch.
I change the video driver from GL to Vulcan.
RetroArch closure.
It never opens again.

To open it I have to delete the configuration folder~/.var/app/org.libretro.RetroArch

It also happens that I open retroArch, change the video driver to Vulcan, open a game and RetroArch closes.

I have RetroArch 1.7.8, Ubuntu 18.04.3, Nvidia 390 driver (GeForce GT 620).

**Comment by hizzlekizzle** [comment]
I don't think the flatpak (that's what you're using, right?) supports vulkan currently. The snap package does not, either.

**Comment by alexb3d** [comment]
Yes, I am using Flatpak 1.4.2 and RetroArch 1.7.8. Vulcan works perfect with Flatpak.

**Comment by hizzlekizzle** [comment]
Flatpak in general does, but I believe it has to be set up on a package-by-package basis, which hasn't been done for RetroArch, to my knowledge. @robloach is the guy who does the flatpak, though, so maybe he has more info.

**Comment by alexb3d** [comment]
It works perfect. I was using Flatpak RetroArch with Vulcan for a long time. After this last update gives the error.

**Comment by gouchi** [comment]
It is maybe better to open the [issue in the dedicated repository](https://github.com/flathub/org.libretro.RetroArch).

Thank you.

**Comment by alexb3d** [comment]
**Updated:** It seems to me that it is not a problem of Flatpak. I installed the Stable PPA and Testing, Vulcan does not work on any.

**Comment by alexb3d** [comment]
> It is maybe better to open the [issue in the dedicated repository](https://github.com/flathub/org.libretro.RetroArch).
> 
> Thank you.

FlatHub!! .-.
I have so much time without reporting anything that I had forgotten.
It would be nice to have only one communication channel. This from flatpak, falhub, the forum, the PPA, etc. What it does is confuse.

**Comment by gouchi** [comment]
What it the output from `vulkaninfo` from [vulkan-utils](https://packages.ubuntu.com/bionic/vulkan-utils) ?

I am not sure your [Nvidia graphic card](https://developer.nvidia.com/vulkan-driver) supports Vulkan ?

**Comment by alexb3d** [comment]
I used Vulcan in version 1.7.7 and it ran better than GL.

```
lex@home:~$ vulkaninfo
===========
VULKAN INFO
===========
Vulkan Instance Version: 1.1.70
/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED
```

**Comment by gouchi** [comment]
According to the output Vulkan is not correctly installed as Vulkan can't be initialized.

**Comment by alexb3d** [comment]
It seems to me that I have become obsolete.
The 620 does not support Vulkan, the 630 does.
It's funny that it worked before.

**Comment by twinaphex** [comment]
Is there anything that can be read about this deprecation?

I wonder if something similar happened with Ivy Bridge iGPUs. Back in 2016 there were preliminary drivers implementing parts of Vulkan but there were some big issues left remaining still.

**Comment by gouchi** [comment]
[Nvidia forum thread](https://devtalk.nvidia.com/default/topic/917161/vulkan/fermi-support-) about Fermi Vulkan support.
