### ISSUE TITLE
Retroarch NPE crash upon mouse movement

### ISSUE THREAD

**Issue by philcali** [libretro/RetroArch#9454]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RetroArch experiences a hard crash upon mouse movement (device or touch).

### Expected behavior

RetroArch should not crash with mouse movement.

### Actual behavior

Once a mouse event is captured by RetroArch, it crashes with a null pointer dereference. I'm able to reproduce it 100% of the time, and the app is now completely unusable for me at this time.

### Steps to reproduce the bug

1. Open RetroArch
2. Move mouse / scroll with touch
3. Experience crash.

### Bisect Results

I've looked at the system logs going outbound to Google, and it looks like there's a null dereference event triggered by the mouse event. I've taken a couple of screenshots. I'll try to attach.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.8_GIT

### Environment information

- OS: Chromebook Pixel Slate
- Compiler: None

**Comment by philcali** [comment]
![Screenshot 2019-09-09 at 11 24 16 AM](https://user-images.githubusercontent.com/105208/64519498-86630400-d2f4-11e9-8058-948ebb360ace.png)

![Screenshot 2019-09-09 at 11 23 23 AM](https://user-images.githubusercontent.com/105208/64519509-8cf17b80-d2f4-11e9-8150-c67e60e27704.png)

**Comment by philcali** [comment]
Also noticed that the paired bluetooth device is not being recognized either: Moga Pro 2 HID. It's showing up as "ChromeOS Game Pad". While the device can connect, it's unable to recognized half of the potential buttons. The same controller using the same version of RetroArch on my OnePlus 6 T phone works great.

**Comment by jermafenser** [comment]
I am experiencing the same issue on a Pixelbook running ChromeOS 76.  If I touch the touchpad or use the stylus, the application immediately crashes.  I also used the Send Debug info feature, id: 29831

![Screenshot 2019-09-14 at 9 06 05 PM](https://user-images.githubusercontent.com/37477328/64915410-1ad5c800-d734-11e9-83ba-ee02f17dd843.png)

**Comment by jermafenser** [comment]
This also occurs on a HP Chromebook x2 runing ChromeOS 75

**Comment by philcali** [comment]
I've updated to 1.8.0, and this is still happening, but the error is different.

__System crash__

![Screenshot 2019-10-28 at 7 11 20 PM](https://user-images.githubusercontent.com/105208/67724949-18af8c00-f9b7-11e9-8db4-0e50df467b51.png)

__Error log__

![Screenshot 2019-10-28 at 7 10 53 PM](https://user-images.githubusercontent.com/105208/67724972-1fd69a00-f9b7-11e9-9391-6b90dc7fe288.png)

__System log__

![Screenshot 2019-10-28 at 7 09 49 PM](https://user-images.githubusercontent.com/105208/67724976-2402b780-f9b7-11e9-98e5-64989e34c5a6.png)

**Comment by thbell** [comment]
I am experiencing this issue as well on my HP Chromebook x360 14.using Chrome OS 77 stable.  Both this and the controller mapping issue are making using the Android version of Retroarch on Chromebooks a very bad experience.  Since this seems to have been an issue for a while, I will fork this and attempt to fix both of these issues within the next month or so.  

I would do this sooner, but we can't side-load APK's on Chromebooks without putting them in dev mode, and I would rather just by a cheap one in order to do that.

**Comment by twinaphex** [comment]
We really need a programmer with Chromebook on hand, or somebody from the community to step up to the plate and start helping us out here. I believe these issues started happening after @jdgleaver's MaterialUI changes to do with reworking the mouse/pointer code. Everything runs fine on normal Android devices but not these Chromebook thingies it seems.

**Comment by thbell** [comment]
@twinaphex thanks for that info.  If one doesn't already exists, I will open a separate issue to track and fix the gamepad mapping issue.

**Comment by phcoder** [comment]
For gamepad issue I already have a patch in review. Some changes are requested for it and I didn't get to verify the updated patch yet due to traveling.

**Comment by phcoder** [comment]
I have this issue on Pixelbook but on on my HP chromebook that I have put into developper mode for purpose of testing this. My guess is that the difference comes from pixelbook having touchscreen and HP doesn't but ChromeOS version might also be a factor

**Comment by Warzinak** [comment]
I have the same issue on my Lenovo e500.
It was a big reason I wanted to buy the chromebook in the first place :(
Hope it gets fixed

**Comment by phcoder** [comment]
https://github.com/libretro/RetroArch/pull/10076

**Comment by phcoder** [comment]
This can be closed now

**Comment by philcali** [comment]
I confirmed that the latest 1.8.5 Android release fixed my issue on the pixelslate. Thanks everyone!
