### ISSUE TITLE
bsnes HD don't save and don't load an existant save. 

### ISSUE THREAD

**Issue by Pearate** [libretro/RetroArch#9455]
This is about bsnes HD core, but not sure if it is the core or RetroArch who has an issue.
## Description
I use the "save in game directory" option and bsnes HD don't make a save at all, and don't load an existent save neither. 

Git Version 2179c16f60
RetroArch: 1.7.8 (v3)
Windows 10

Thanks for fixing that.

**Comment by fr500** [comment]
probably a mismatched library name

**Comment by Pearate** [comment]
The save bug was fixed in a 1.7.8 Nightly update and of course the 1.7.9 version.
Only remains the fact that Cheevos don't work with Bsnes HD...
