### ISSUE TITLE
(Thumbnails) Have Download Thumbnails skip files that already exist

### ISSUE THREAD

**Issue by sebolio** [libretro/RetroArch#9463]
When using the Download Thumbnails option in the Desktop Window, it downloads everything again even if I already have a lot of pictures already downloaded

[Description of the bug]
It happens by just clicking the option

### Expected behavior
Skip files that already exist

[What you expected to happen]
Skip files that already exist

### Actual behavior
Downloads everything

[What is actually happening]
Downloads everything

### Steps to reproduce the bug
1. Open Desktop Window
2. Right click on a playlist
3. Click download thumbnails
4: Profit

### Bisect Results
Same always

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.8

### Environment information

- OS: Windows 10 1903

**Comment by i30817** [comment]
As long as the download process of a new image only moves them to the 'correct' place once they're completely downloaded this is ok (though i'd prefer only skip 'same size' images, though i imagine devs don't want to complicate the protocol to support this efficiently).
