### ISSUE TITLE
[Feature Request] Option for non-scrolling metadata in Ozone side panel

### ISSUE THREAD

**Issue by Ryunam** [libretro/RetroArch#9471]
### Description

On latest master and with menu driver set to Ozone, if the information displayed in the sublabel of a playlist entry (such as playtime log or the core name) reaches a certain length, the text starts scrolling, either by bouncing left and right or by moving in a certain direction.

_**Current behavior:**_

![scroll2](https://user-images.githubusercontent.com/17614150/64920753-3f28b780-d7bb-11e9-919f-23305c66e0b4.png)

Previously this type of sublabel information was displayed statically with word-wrap, which I believe looked better and cleaner for Ozone's side panel and made things much more readable at a glance.

_**Old behavior:**_

![scroll1](https://user-images.githubusercontent.com/17614150/64920832-27056800-d7bc-11e9-89f5-59113c268e66.png)

It would be great to have this type of visualization back, or maybe have a toggle option to customize it.

### Bisect Results

I think the scrolling text in Ozone's sidebar information was introduced with @jdgleaver's PR https://github.com/libretro/RetroArch/pull/9459, with Ozone now using tickers for sidebar metadata.

### Version/Commit

- RetroArch: 1.7.8 / e1a7b82b2ee08f85b1683c7240aeb64cb8862827

### Environment information

- OS: Windows 10 x64
- Compiler: Mingw64

**Comment by jdgleaver** [comment]
Heh - okay, fair enough!

I'm behind with some other things at the moment, but I'll add a toggle later in the week.

**Comment by jdgleaver** [comment]
@Ryunam A small (pointless) update, just so you know I haven't forgotten this! I fully intended to get it done this week, but got totally sidetracked with a rewrite of the mouse/touchscreen input code.

I've made the required changes to Ozone, but just ran out of time to add the new menu option (this is always very tedious stuff). I'll definitely finish it off on Monday.  :)

**Comment by Ryunam** [comment]
Thank you @jdgleaver! I’ll just add that I really appreciate your feedback which is always kind and professional, your dedication towards the project as whole, as well as your considerable patience with more specific issues like this one. Take your time, definitely no sort of pressure on my part!

**Comment by jdgleaver** [comment]
@Ryunam Thank you so much for the kind words! Your appreciation means a great deal to me. This kind of feedback really motivates me to keep forging ahead with the project!  :)

**Comment by jdgleaver** [comment]
Fixed by PR #9505 :)
