### ISSUE TITLE
[Feature Request] SMB Support to access files stored in the local network (e.g. files on a NAS)

### ISSUE THREAD

**Issue by Isias83** [libretro/RetroArch#9472]
### What i would wish to see

An option to specify an smb/nfs folder for roms / cores / assets etc. via the Retroarch GUI for people running more then 1 installation of Retroarch (e.g. Desktop PC and Laptop) in the same house and do have a NAS or a Server etc.

### Version/Commit

- RetroArch: 1.7.7

### Environment information

- OS: Windows 10 Professional and 3 Ubuntu 18.04 LTS

**Comment by RaddedMC** [comment]
Closed and old but I +1 this. Just bought a new chromecast with google TV and don't really want to root it.
I'm gonna try installing retroarch on my PC and using Steam Link instead.
