### ISSUE TITLE
Retroarch Switch shows "No items" after Close Content

### ISSUE THREAD

**Issue by TomCat666** [libretro/RetroArch#9476]
## Description

When you close any content on any core a "No items" screen is shown and you are not returned to the "Run - start content" menu as on other retroarch builds (windows) and you are not able to return to the same position in the playlist with the back button.

### Expected behavior

When closing the content you should be returned to the "Run" menu where you can run the same content again or go back to the playlist on the same position as you were before.

### Actual behavior

When closing any content via Quick menu you go to "No items" list.

### Steps to reproduce the bug

1. Run any game on any core from any of the playlists
2. Press the button to go into Quick menu
3. Choose Close content
4. You will be in "No items" display

### Version/Commit
You can find this information under Information/System Information

- RetroArch: git version: 7dc2ca4
- Frontend name: Ninetndo Switch

### Environment information

- OS: Horizon OS (v8.1) - Switch

**Comment by sonninnos** [comment]
This should not be happening anymore.
