### ISSUE TITLE
Can I limit the number of retroarc slots?

### ISSUE THREAD

**Issue by ajtend32** [libretro/RetroArch#9478]
Other emulsions are state 10 -> state 1
Back on the way back, the retroarch increased by an unlimited number,
But you can't do it like any other emulsions?

**Comment by gouchi** [comment]
> This is not a forum or a help section, this is strictly developer oriented

Please post on our [forum](https://forums.libretro.com) instead.

Thank you.

[Source](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by RobLoach** [comment]
You can't limit it right now, unless someone implements that feature.
