### ISSUE TITLE
No longer compiles for Gamecube

### ISSUE THREAD

**Issue by twinaphex** [libretro/RetroArch#9480]
@Wiimpathy Could you fix the Gamecube (non-Wii) build? You can center it around HW_DOL being defined instead of HW_RVL.

We're getting orders like this -

http://paste.libretro.com/161876

it might need to be all stubbed out for Gamecube.

**Comment by Wiimpathy** [comment]
@twinaphex 
Yes, I forgot GC most of the time when adding Wii code.
It's fixed now in https://github.com/libretro/RetroArch/pull/9484
