### ISSUE TITLE
Back to menu 2nd time

### ISSUE THREAD

**Issue by tonilsz** [libretro/RetroArch#9481]
Hi,

this is related with user experience, I noticed that when have a core open and display the menu (press L3+R3) if you navigate f.e. change some settings and then go back. Since here all is fine, but if you then want to close the core you (press L3+R3) again, then the xmb is pointing the las place you where ( in this case settings) you have to find runnig core and rom to finish, in some cases there are about 30 cores and handreds of games and in some cases with the same name(different versions).

Nothing is wrong and maybe I'm missing why you take this decision but I think that the lower level user will be greatfull.

I'm running lakka 2.3 on a pi 3b+

Thanks again.

**Comment by RobLoach** [comment]
This issue is very similar: https://github.com/libretro/RetroArch/issues/9492 ... Good discussion over there.
