### ISSUE TITLE
(3DS) fuse core hard crash since at least 1.7.1

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/RetroArch#9491]
## Description

Hard crash.

### Steps to reproduce the bug

Try to launch game using FUSE Spectrum core.

See here for crash logs: https://github.com/libretro/fuse-libretro/issues/51

### Bisect Results

happens in

1.7.1 - fuse 1.1.1 58ec13f
1.7.8 - fuse 1.1.1 8184756

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.8 stable

### Environment information

- N3DS System = 11.11.0-43E
- Luma = 10.0.1-c913de1
- B9S = 1.3 (6 Sep 2017)

**Comment by RobLoach** [comment]
"Broken"?

**Comment by gingerbeardman** [comment]
Have clarified my wording, thanks for pulling me up on it! 

I must have been in a rush filing this one.
