### ISSUE TITLE
(Menu) XMB 'forgets' place when navigating backwards in menus

### ISSUE THREAD

**Issue by DJScias** [libretro/RetroArch#9492]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Prompted by reading the changes in this line, I checked if this was also fixed in XMB as it also suffers from this:
```
MENU/MATERIALUI: MaterialUI no longer 'forgets' its place when navigating backwards in menus, and navigation in general is 'cleaner'.
```

It wasn't, and I'm not sure if it's been reported yet. If it is, I apologize (feel free to close and all) but I tried to search for it under `XMB`, `Menu`, `Forget` and `Reset` and couldn't find it.

### Expected behavior

You go back to the previous menu while remaining at the option you just went deeper into.

### Actual behavior

It goes back to the first option of the previous menu, which can make first-setups for cores extremely tedious as you always have to scroll back down to the last position you were at.

### Steps to reproduce the bug

1. Go to Settings > Drivers.
2. Scroll down to `Video` and go deeper to see all the options.
3. Back out of this menu, notice you're back at the top with `Input`.

### Bisect Results

I.. Honestly don't know, I'm sorry. I haven't watched all the XMB changes enough for this.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 2892abf

### Environment information

- OS: Windows 10 Education 64-bit
- Compiler: MinGW (7.3.0) 64-bit (downloaded from buildbot)

**Comment by jdgleaver** [comment]
Hmm! I've never really noticed this before, but now I have, it's really annoying.

I've got a huge TODO list at the moment, but this is definitely something I'd like to fix. I'll check the code when I get a chance, and keep you posted.

**Comment by i30817** [comment]
I always thought it was on purpose, keeping state and invalidating it correctly being complex enough in C not to bother.

**Comment by DJScias** [comment]
> Hmm! I've never really noticed this before, but now I have, it's really annoying.
> 
> I've got a huge TODO list at the moment, but this is definitely something I'd like to fix. I'll check the code when I get a chance, and keep you posted.

Thanks for checking, I appreciate it.

I agree it's honestly just annoying once you notice it. But of course it's minor considered to many issues. Take your time. If anything it's a QoL for when you have to do many changes (like a first-time setup of a core/installation of retroarch) but after that it's less of a real "hindrance".

**Comment by jdgleaver** [comment]
Okay... PR #9510 addresses this for core options, but it turns out that doing this for *all* drop-down lists is a whole other thing - the code is a nightmare. So we'll have to leave it for now, but I'll try to come back to it later...

**Comment by i30817** [comment]
A pity, this is really annoying in the playlists when you select one by accident on a complete collection.

**Comment by RobLoach** [comment]
Thanks for having a hack at this! It has been a pet peeve that I've ignored for years :upside_down_face:
