### ISSUE TITLE
[Cheevos] Some PlayStation games do not link to their set correctly through .m3u files

### ISSUE THREAD

**Issue by LordArchantos** [libretro/RetroArch#9493]
## Description

When launched using an .m3u file, some PlayStation games do not link to the game on RetroAchievements (as if the checksum doesn't match), while the same image works when launched directly from its cue file. Culprits I've ran into so far include Spyro the Dragon (1st game), MediEvil 1, and MediEvil 2.

Note that while the games I've ran into this problem with are single disc games, there are many such that don't exhibit this issue; e.g. Spyro 2, Tomba, and Castlevania - Symphony of the Night. All my .m3u files are UTF-8 with CR+LF line breaks.

### Expected behavior

A game to get connected to it's cheevo set.

### Actual behavior

Some games do not get connected to their cheevo set, as if the checksum does not match.

### Steps to reproduce the bug

1. Use an .m3u file to start e.g. Spyro the Dragon, and notice that cheevos are not found.
2. Start the game from the .cue file instead, and notice that cheevos now show up.

### Bisect Results

Problem has existed since disc content hashing for PSX cheevo support was added (#9405 ).

### Version/Commit

- RetroArch: 1.7.8 99a3aa8ee1

### Environment information

- OS: Windows 10 Pro x64 1809

**Comment by LordArchantos** [comment]
Found the cause. It seems for some reason, at least in Beetle PSX, some .m3u files need to have a line break at the end of the file for it to work as expected. Not sure why only some don't work without it though. Shall I close this or would this "line break" problem still be considered an issue in need of addressing?

**Comment by Jamiras** [comment]
I am able to reproduce this and will provide a fix. Thanks for reporting.
