### ISSUE TITLE
Save Game Preset (Shaders) Failed

### ISSUE THREAD

**Issue by ToniBC** [libretro/RetroArch#9498]
In Retroarch nightly for Windows (September 21) when you try to save the shaders for a particular game it says "Failed to applied shader presset: xxxx.slangp" and resets the shader values to their default state. The file is created, but then it is not loaded with the game, you see the shader values in the options, but they do not apply. If you give the option to apply the shader it gives an error, you have to load the shader again and it does work there. But still giving error when saving the setting for the particular game.

With Retroarch 1.7.8v4 that error does not occur and saves the shader correctly and loads it with the game without problems.

Thank you.

**Comment by hizzlekizzle** [comment]
@LazyBumHorse got any ideas?

**Comment by LordArchantos** [comment]
Came to report this too. On my system, comparing a new messed up preset to an existing good one, the relative paths to the shader files only go up one level before "entering" their path.

Old, working file:
shader0 = "../../shaders_cg/crt/shaders/tvout-tweaks.cg"

Same file after saving an override in the latest nightly:
shader0 = "../shaders_cg/crt/shaders/tvout-tweaks.cg"

**Comment by LazyBumHorse** [comment]
Migt be because of the recent optimization commits, I'll bisect it.

**Comment by LazyBumHorse** [comment]
Yeah, this is it: https://github.com/libretro/RetroArch/commit/f4c6b06b494fb9ee97a9abced2649481a630af97

**Comment by LazyBumHorse** [comment]
It was terminating the string after just one `../`
