### ISSUE TITLE
(XMB) Time & Date not displayed

### ISSUE THREAD

**Issue by LordArchantos** [libretro/RetroArch#9503]
## Description

Time and date in the menu are not displayed, only the clock icon is visible. Tried each menu driver as well. All tests were done on clean installs. Nothing available on the buildbot after 1.7.6 stable works. In case it could be related, some people also apparently have had the battery level display stop working along with date and time.

### Expected behavior

Time and date to be displayed according to the selected format.

### Actual behavior

No time or date are displayed.

### Steps to reproduce the bug

1. Set time & date to be visible, in any format, and only the clock icon is displayed.

### Bisect Results

1.7.6 stable displays time and date as set, starting from 1.7.7 stable (don't have access to builds between them) no time or date is displayed.

### Version/Commit

- RetroArch: 1.7.8 5f87fa1aca

### Environment information

- OS: Windows 10 Pro x64 1809

**Comment by LordArchantos** [comment]
![RAmenu](https://user-images.githubusercontent.com/45307447/65408706-a1526f80-ddee-11e9-9af6-5b23d7b9447f.jpg)

**Comment by LordArchantos** [comment]
And today after Windows installed a few recent updates, date and time are back working as normal.

**Comment by WandeingLagomorph793** [comment]
Can confirm this happens to me as well, rebooting the whole system fixes it temporarily but it eventually comes back after a while, regardless of system or setup and tested with the same setups as above.

**Comment by tapperp** [comment]
Same problem for me. Oddly, 1.76 works normally, but 1.77 and 1.78 do not.

Windows 10, fully updated. 17 6700k @4.4Ghz, nvidia 1080, 16GB RAM etc. Using an Alienware ultrawide monitor 3440 x 1440.

Here are images of what I see. Each is running from a fresh install folder, no changes to cfg or anything:

1) 1.76 - time and date are normal
https://forums.libretro.com/uploads/default/optimized/2X/c/c008890ec5c53b91b1cf0a0b6abe367cbd45026f_2_934x750.png

2) 1.77 - time and date do not display
https://forums.libretro.com/uploads/default/optimized/2X/5/55d862363bc797541fe55be7cb3fa1f19f377870_2_934x750.png

3) 1.78 (9/25 nightly) - time and date do not display
https://forums.libretro.com/uploads/default/optimized/2X/e/ef776f9ed65fc75c918be48fcc6d144ad1022587_2_934x750.png

**Comment by WandeingLagomorph793** [comment]
https://i.imgur.com/l9iA2dh.png

I can confirm that even with the current 1.8.0 version this issue still occurs.

**Comment by WandeingLagomorph793** [comment]
https://imgur.com/I8iopi6

This is still present even in the current 1.8.4 builds, I don't have a timeframe as to how often it happen, It seems to happen every so often, regardless of system, at least on Windows, and the only immediete fix is rebooting the system, which won't fully fix the issue since it'll always happen again eventually.

**Comment by LordArchantos** [comment]
Shoot, completely forgot to report on this. At least for me it's fixed, I realised it wasn't happening on my system anymore somewhere around 1.9.0.
