### ISSUE TITLE
Clock display not showing since 1.76

### ISSUE THREAD

**Issue by tapperp** [libretro/RetroArch#9519]
Time and date are not showing in the upper right hand, only the clock icon.

I have tested using clean installs of Win x64 1.76, 1.77 and the recent nightly 1.78 (9/25).

Others are not having this issue, and so far I can't determine the variable. I wish I could. It's the same whether using windowed or fullscreen.

Windows 10, fully updated. 17 6700k @4.4Ghz, nvidia 1080, 16GB RAM etc. Using an Alienware ultrawide monitor 3440 x 1440.

Here are images of what I mean. Each is running from a fresh install folder, no changes to cfg or anything:

https://forums.libretro.com/uploads/default/optimized/2X/c/c008890ec5c53b91b1cf0a0b6abe367cbd45026f_2_934x750.png

https://forums.libretro.com/uploads/default/optimized/2X/5/55d862363bc797541fe55be7cb3fa1f19f377870_2_934x750.png

https://forums.libretro.com/uploads/default/optimized/2X/e/ef776f9ed65fc75c918be48fcc6d144ad1022587_2_934x750.png

**Comment by Awakened0** [comment]
Duplicate of https://github.com/libretro/RetroArch/issues/9503

**Comment by tapperp** [comment]
I will close this since the issue has been previously posted.
