### ISSUE TITLE
Left Trigger and Right Trigger bug

### ISSUE THREAD

**Issue by MasterCubo** [libretro/RetroArch#9523]
## Description

This might be an integrated feature somehow, but when I press LT the screen repeatedly flashes. It might be some malfunctioning frameskip.

### Expected behavior

Enable a cheat of sorts.

### Actual behavior

screen flashes white for a second returns to the game and you can move but only for a second before it flashes white again. In the menu, the buttons are also buggy. If you press down, it will skip plenty of the things as if it is going fast. Pressing LT will temporarily stop the skipping. It also resulted in the cheat to not work.

### Steps to reproduce the bug

1. Hold down LT
2. see it happen
3. if you hold it down while in either 'mode'(the white screen or real game) then it'll stay in that mode

### Bisect Results

It started right as I started the game and held the buttons

- RetroArch: 1.78

### Environment information

- OS: MacOS Sierra (10.12)

**Comment by MasterCubo** [comment]
I can show a screen recording of it happening if you'd like.

**Comment by RobLoach** [comment]
Do you have anything funky set to LT? Is that set to slow motion or fast motion? Using video sync? What core? I'm unable to reproduce.

**Comment by MasterCubo** [comment]
Sorry for the *very* late reply, but I just redownloaded RetroArch and it
worked. And yes, I'm pretty sure I had it mapped to something like that.
