### ISSUE TITLE
[Feature Request] Option to delete playlists

### ISSUE THREAD

**Issue by floppyD** [libretro/RetroArch#9525]
Currently there's no way to delete playlists using the GUI - if there is, excuse me but I can't find it. I think the most intuitive location for such option would be under Settings -> Playlists -> Playlist Management.

**Comment by bslenul** [comment]
Globally that would be really nice to be able to delete more stuff from the UI directly, you can already remove remap files and shaders presets for example and that's super useful.

Being able to delete playlists, overrides, game-options files, states, etc. would be awesome.

**Comment by FreeShippingParty** [comment]
Fixed in 999887bda5002660c1d0f31520d6bbb12ca8d5bc
