### ISSUE TITLE
(Cheevos) Achievement Triggers cause Retroarch to Crash [Semi-resolved]

### ISSUE THREAD

**Issue by Zenjir0** [libretro/RetroArch#9533]
## Description

When an achievement is triggered, retroarch will freeze and crash. See following video for example: https://www.dropbox.com/s/6q3jh7w998x4gnj/2019-09-30%2001-18-28.mkv?dl=0

### Expected behavior

Retroarch should not crash after an achievement is triggered.

### Actual behavior

I have tested on both Retroarch 1.7.8v4 (f45a1d797e) and on 1.7.7 and the issue persists. The odd thing is it has not always crashed in the past. It only recently surfaced. 

### Steps to reproduce the bug

Trigger any achievement, with widgets and badge images enabled.
Retroarch-Log: https://pastebin.com/gdLnPVvn
Retroarch-Config: https://pastebin.com/mfURy1x6

### Bisect Results

As I was creating this ticket, I was able to semi fix the issue. I cleared out all the image files in ...\retroarch\thumbnails\cheevos\badges and let retroarch re-download the images, and  triggering achievements no longer causes retroarch to crash after clearing out that directory.

Before I performed the above steps I repeatedly tried different scenarios, such as turning off widgets, auto-screenshot, runahead, etc to see if any of those features was causing the issue somehow. Even with widgets turned off and using just the yellow text notifications, retroarch would still crash like in the video above.

I am now creating this ticket in the likelihood that I might have found an edge case, where rendering the .png file within the aforementioned cheevos badge directory causes some sort of unhandled-exception. 

### Version/Commit

- RetroArch: 1.7.8v4 - Git f45a1d797e

### Environment information

- OS: Windows 7 x64

**Comment by Zenjir0** [comment]
Windows Eventviewer shows the following error:

Faulting application name: retroarch.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: retroarch.exe, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000094
Fault offset: 0x0000000000620b02
Faulting process id: 0x1228
Faulting application start time: 0x01d5774a5b58d010
Report Id: d2ea6e40-e33d-11e9-a03d-4ccc6a88074a

And a quick google search shows 0xc0000094 as an "integer division by zero" error.

**Comment by Jamiras** [comment]
I tried to recreate the issue by deleting the image before triggering the achievement, replacing the image with a 0-byte file, replacing the image with an HTML file, and truncating the image so it was an incomplete file. In all cases, the popup widget simply did not show an image, but the achievement was correctly unlocked and the application did not crash.

The provided video shows the widget appearing without an image, and the provided config has `cheevos_auto_screenshot` set to false (though the user indicates he was playing with that setting trying to correct the issue, and it did not change the behavior). I'm not sure what else would be attempting to use the files in the thumbnails directory, or what would be causing the divide by zero error.

Tested with x64 build on Windows 10.

**Comment by Zenjir0** [comment]
@Jamiras To help clarify, I did have cheevos_auto_screenshot set to true at first, and in my testing I thought maybe it was the source of the issue, so I turned it off. But it was not, what was causing the crash. I still don't fully know what was causing retroarch to crash, just that it was. 

Also I don't know why it is not displaying correctly either in the video, as the image downloaded is correct, and other achievements trigger correctly as you would expect. So that might be a different issue, or a symptom of one.

**Comment by Zenjir0** [comment]
I just wanted to report that I have not had this particular issue trigger in recent weeks, and this issue could probably be closed.

**Comment by SingingCoyote13** [comment]
i posted something very similar to this;

https://github.com/libretro/RetroArch/issues/10797

having crashes (actually system hookup) on multiple different systems with retroachievements.
retropie on a raspberry pi 3B and a desktop pc with linux, and on batocera.
cannot find any solution tried everything, also note that this suddenly started to happen, before a few months everything was fine...

**Comment by meleu** [comment]
as this issue was solved and @SingingCoyote13 opened a new one, I'm closing this.
