### ISSUE TITLE
bsnes-HD core logging vs saves/config discrepancy

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9537]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

When attemping to migrate settings from the old snes core I used (mercury-accuracy) to the new (bsnes HD) I simply renamed the folders to match the new core.  I took my naming for my saves/states/config/shader from the logs folder by chance.   

When none of my overrides worked, it was the first thing I checked.  Seems it logs as "bsnes HD" as one would expect, however everywhere else - files go into a folder plainly labled "bsnes"

This is obviously going to be messy and confusing. What its named in the end, i could care less (though to differentiate from the plain jane bsnes core it should probably have the HD suffix), its more about having them all the same name. 

### Expected behavior

The name for all specific core related folders to match. 

### Actual behavior

They dont. 

### Steps to reproduce the bug

1. create a core over ride, shader preset, or save file using the bsnes hd core.
2. enable per core runtime logging.
3. note the difference between folder naming

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.9 0a123e8215

### Environment information

- OS: Windows 10

**Comment by negativeExponent** [comment]
this is better posted in the related core in question. folder naming is based on what is labeled in library_name, which in this case is still "bsnes"

https://github.com/libretro/bsnes/blob/master/bsnes/target-libretro/libretro.cpp#L441

**Comment by klepp0906** [comment]
gotcha, i admit - i wondered while posting.   In the end, assumed it was handled by RA though.

Ill post over there now.

**Comment by negativeExponent** [comment]
this should be safe to close now.
