### ISSUE TITLE
Run ahead + SMS Bios

### ISSUE THREAD

**Issue by profalexetec2019** [libretro/RetroArch#9559]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Load a content with SMS Bios and run ahead feature, it cause some glitches skipping SEGA logo and load the ROM with several glitches

### Expected behavior

No glitches at all

### Actual behavior

Some glitches occur when a content is loaded, reset content resolve Bios' glitch, but you get a message about an error to load cartdige (using SMS Bios with Genesis Plus GX)

### Steps to reproduce the bug

1. Download and load Genesis Plus GX core
2. Turn on run ahead feature (2 frames)
3. Download SMS Bios and put on correctly directory (smspower - I used v 2.4, you must rename the .sms file to bios_E, bios_J or bios_U or triplacete the file with each sufix)
4. Download a SMS Rom and put somewhere you could remember for step 5 (try Alex Kidd in Miracle World)
5. Load that ROM from step 4
6. Open the menu and go to  Core Options
7. Turn on System Boot ROM option and restart the application
8. Load the same core and content
9. SEGA logo annimation will be skipped
10. The content will be loaded with several glitches
11. Try to reset the content
12. SEGA logo will appear and error message too

### Bisect Results
It's a very specifc issue, please do not worry, I'm just telling that combination sounds well but does not work correctly as a real console with run ahead improvement

### Version/Commit

- RetroArch: 1.7.8

### Environment information

- OS: Windows 10 Education
- Compiler: I used a installer version from official website

**Comment by Awakened0** [comment]
This was fixed in upstream GPGX with this commit: https://github.com/ekeeke/Genesis-Plus-GX/commit/e819af455344b998669cfd4a8489d29470b77da7

For some reason it was never merged into the libretro repo to be included in buildbot builds of the core. I've brought that up to @twinaphex , so it should be merged when he has a moment to look at it.

**Comment by Awakened0** [comment]
The next buildbot build should have the fix. I built from the latest source from the libretro repo and both the SMS BIOS and the GG TMSS work properly with runahead enabled.
