### ISSUE TITLE
iOS- RA Menu crash upon first run of Core

### ISSUE THREAD

**Issue by mrjschulte** [libretro/RetroArch#9562]
Looks like the menu handler in RA on iOS crashes when loading content for the first time.

The core loads fine and the content runs as expected but it takes a few extra seconds the first time.

notify_list_pushed: old size should not be larger
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication delegate]
PID: 4865, TID: 2692549, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   RetroArch                           0x0000000102243298 +[RetroArch_iOS get] + 56
5   RetroArch                           0x0000000102242498 -[RAMainMenu willReloadData] + 684
6   RetroArch                           0x0000000102241cd4 -[RAMenuBase reloadData] + 28
7   RetroArch                           0x0000000102243dac -[RetroArch_iOS mainMenuRefresh] + 48
8   RetroArch                           0x000000010234799c task_database_handler + 968
9   RetroArch                           0x00000001023ca38c threaded_worker + 112
10  RetroArch                           0x0000000102336adc thread_wrap + 28
11  libsystem_pthread.dylib             0x00000001e2157908 <redacted> + 132
12  libsystem_pthread.dylib             0x00000001e2157864 _pthread_start + 48
13  libsystem_pthread.dylib             0x00000001e215fdcc thread_start + 4
2019-10-06 10:36:29.753353-0700 RetroArch[4865:2692549] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication delegate]
PID: 4865, TID: 2692549, Thread name: (none), Queue name: com.apple.root.default-qos.overcommit, QoS: 0
Backtrace:
4   RetroArch                           0x0000000102243298 +[RetroArch_iOS get] + 56
5   RetroArch                           0x0000000102242498 -[RAMainMenu willReloadData] + 684
6   RetroArch                           0x0000000102241cd4 -[RAMenuBase reloadData] + 28
7   RetroArch                           0x0000000102243dac -[RetroArch_iOS mainMenuRefresh] + 48
8   RetroArch                           0x000000010234799c task_database_handler + 968
9   RetroArch                           0x00000001023ca38c threaded_worker + 112
10  RetroArch                           0x0000000102336adc thread_wrap + 28
11  libsystem_pthread.dylib             0x00000001e2157908 <redacted> + 132
12  libsystem_pthread.dylib             0x00000001e2157864 _pthread_start + 48
13  libsystem_pthread.dylib             0x00000001e215fdcc thread_start + 4
2019-10-06 10:36:37.465888-0700 RetroArch[4865:2692549] [Assert] Cannot be called with asCopy = NO on non-main thread.

**Comment by twinaphex** [comment]
Hi,

does this happen if you disable threaded video? Is this enabled by default on iOS?

And yes, we are having some huge threading errors right now on iOS - the issue is that NSView and friends are being called from threads other than the main thread - and this is not allowed by either OSX or iOS.

We need an experienced Mac coder that can help fix this for us. So far no takers.

**Comment by twinaphex** [comment]
Hi there @mrjschulte , has this issue been fixed now since yoshisuga's PR?

**Comment by mrjschulte** [comment]
I’ll have to do a fresh pull to confirm. Will do so tonight.

**Comment by mrjschulte** [comment]
Yup, this now works. Case closed.
