### ISSUE TITLE
Rotation doesnt work properly on 3DS

### ISSUE THREAD

**Issue by Cee123** [libretro/RetroArch#9567]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

In games such as 1942, raiden etc, these are displayed horizontal on the 3DS screen. But when you try to rotate through the menu, it will only flip the display 180 degrees despite selecting 90 degrees and so forth. It's a real pain in the ass and makes the games mostly unplayable.

### Expected behavior

The expected behaviour is that it rotates 90 to display vertical so that you don't have to hold the 3DS sideways.

### Actual behavior

It just flips it but is still horizontal.

### Steps to reproduce the bug

Happens with every one of these types of games. It's a real pain.

### Bisect Results

Things I've tried
- Changing the aspect ratio
- Configuring the aspect ratio
- Turning allow rotation on
- Turning allow rotation off
- Changing the display from horizontal to vertical under the game options
- Rotating 90, 180 etc degrees using different settings.
- Trying a combination of these different settings
- Changing allow rotation in the .cfg file
- Eventually gave up and resigned to the fact they will only display horizontally.

### Version/Commit
You can find this information under Information/System Information

- All retroarch versions, all retroarch 3DS cores.

### Environment information
- New Nintendo 3DS XL
- Luma 3DS
- 11.3 Emunand

**Comment by ToniBC** [comment]
The same thing happens in Dingux (RG350), the screen rotates but only 90, it doesn't matter if you put 180 or 270, it is always the same rotation and of course, when rotating to the opposite side of the stick and buttons you cannot play.

**Comment by Cee123** [comment]
> The same thing happens in Dingux (RG350), the screen rotates but only 90, it doesn't matter if you put 180 or 270, it is always the same rotation and of course, when rotating to the opposite side of the stick and buttons you cannot play.

Yeah it's kind of annoying. Makes vertical shooting games like 1942, 1943, Raiden, Dodonpachi etc harder to play.

**Comment by LibretroAdmin** [comment]
@MrHuu Is this still an ongoing issue? If so, can it be looked at?

**Comment by MrHuu** [comment]
```Settings -> Video -> Output -> Video Rotation``` is fully functional on the latest builds.

The rotation option does have the advanced settings flag; ```SD_FLAG_ADVANCED``` set, so it's hidden by default.
```Show Advance Settings``` must be enabled for the option to show.

https://github.com/libretro/RetroArch/blob/master/menu/menu_setting.c#L12357-L12373

Other than that, consider this issue solved.
