### ISSUE TITLE
RA v1.7.9 freezes when left idle on XB1

### ISSUE THREAD

**Issue by norskkriger** [libretro/RetroArch#9569]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

RA freezes when left idle.

### Expected behavior

Not to freeze when left idle.

### Actual behavior

Froze after 1hr and 25mins.

### Steps to reproduce the bug

Simply load RA and leave it be.

### Bisect Results

Happened right after installation. No changes made. Simply left idle. 

### Version/Commit
You can find this information under Information/System Information

v1.7.9

### Environment information

OS: 10.0.18999.1205 (XBOX ONE November 2019 Update)

Newest RA (1.7.9) build for Xbox One freezes when left running idle. Not sure what else I can say. This error occurs "out of the box" with no changes made to the settings.

**Comment by norskkriger** [comment]
Froze after 1hr and 25min.

**Comment by twinaphex** [comment]
This only happens when you leave it idle in the menu for 1 hour and 25 minutes? By leaving it idle, do you mean no user interaction or do you mean by 'idle' just continuing to play on it for longer than 1 hour and 25 minutes?

**Comment by norskkriger** [comment]
Yes, left idle with no user interaction in the menu. Last time I replicated the error, I loaded the app and left it be, paying attention to the time in the top-right corner. It was froze after 1hr and 25mins. I'll see if I can get some logs to help identify what's causing the freeze.

**Comment by norskkriger** [comment]
Don't have time and no longer interested in running RA on XB1
