### ISSUE TITLE
PS3 : RA freezes on thumbnail directory select

### ISSUE THREAD

**Issue by tanaduda** [libretro/RetroArch#9572]
## Description

RA freezes on thumbnail directory select

### Expected behavior

Define thumbnails folder

### Actual 

Freezes

- RetroArch: [version/commit]
1.7.9

### Environment information

- OS: PS3

**Comment by HunterZ** [comment]
Similar issue on Android Oct 7 2019 build from Google Play Store. The app closes itself if you tap the thumbnails directory to try to change it.

**Comment by speuj** [comment]
Having a similar issue on Oct 15 build as well as the latest Stable on Fire TV Stick 4k.  Retroarch closes itself when attempting to change the thumbnail director.

**Comment by twinaphex** [comment]
This should be fixed now. Reopen if this is still an issue.
