### ISSUE TITLE
PS3: menu shader pipeline freezes whole system

### ISSUE THREAD

**Issue by tanaduda** [libretro/RetroArch#9574]
# First and foremost

## Description

Change menu shader pipeline freezes the system. 

### Expected behavior
Change shader pipeline 

### Actual behavior

Freezes the whole system

### Steps to reproduce the bug

Settings/ appearance / menu shader pipeline

### Version/Commit

- RetroArch: 1.7.9

### Environment information

- OS: PS3

**Comment by twinaphex** [comment]
Likely a wontfix for now until somebody goes through the effort of porting all the shader pipelines to Cg format.

**Comment by twinaphex** [comment]
To meet you halfway, I can probably ensure it will no longer crash after you change it.
