### ISSUE TITLE
[Vita] XMB font's(font.ttf) are missing in data.7z

### ISSUE THREAD

**Issue by pettiagalla** [libretro/RetroArch#9577]
## Description

XMB font's(font.ttf) are missing in RetroArch_data.7z.
(/retroarch/assets/xmb/(theme name)/font.ttf)
This is a issue because Vita's default menu is XMB.
English font is jagged and some languages ​​(such as Japanese) are not displayed.
Up to 1.7.8, jagged English fonts were displayed by default.
but, in v1.7.9 added "system language detection", users who use Japanese, Chinese, etc. are in trouble.

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.9/4dcd7a0

### Environment information

- OS: PS Vita 3.60

**Comment by twinaphex** [comment]
@frangarcj @Rinnegatamante what could we do about this?

**Comment by Rinnegatamante** [comment]
I guess that's an issue of the buildbot that creates the data files for Vita (?)

**Comment by frangarcj** [comment]
I'll take a look at the script
