### ISSUE TITLE
PS1 cores not appearing when trying to launch a game. 

### ISSUE THREAD

**Issue by JojocGR** [libretro/RetroArch#9578]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

I'm trying to launch PS1 games but the core option doesn't appear even though core(s) are downloaded. 
[Description of the bug]

### Expected behavior
Select a game from the PS1 category, select a core, play the game. 
[What you expected to happen]

### Actual behavior
Select a game from the PS1 category, PS1 cores are missing, game cannot be launched. (tried multiple games) 
[What is actually happening]

### Steps to reproduce the bug

1. [First step] Go to the PS1 category 
2. [Second step] Select a game
3. [and so on...] Try to select a core to run it with

### Bisect Results

[Try to bisect and tell us when this started happening]

No clue, but at least the past two versions. 

### Version/Commit
You can find this information under Information/System Information
1.7.9-GIT (downloaded normally from play store) 
- RetroArch: [version/commit]
1.7.9-GIT (downloaded normally from play store) 
### Environment information

- OS: [The operating system you're running] Android 9.0
- Compiler: [In case you are running local builds] Not applicable 

![Screenshot_2019-10-09-01-36-11-154_com retroarch](https://user-images.githubusercontent.com/26846133/66438732-421f6c80-ea36-11e9-8fad-20e630a56880.png)

![Screenshot_2019-10-09-01-36-19-159_com retroarch](https://user-images.githubusercontent.com/26846133/66438761-59f6f080-ea36-11e9-86cb-53fce1b54668.png)

![Screenshot_2019-10-09-01-36-38-196_com retroarch](https://user-images.githubusercontent.com/26846133/66438774-611dfe80-ea36-11e9-82fd-7a578a616ed5.png)

![Screenshot_2019-10-09-01-37-00-604_com retroarch](https://user-images.githubusercontent.com/26846133/66438782-667b4900-ea36-11e9-9e05-06e47e18e51a.png)

**Comment by bslenul** [comment]
Seeing the cores RA is listing for you, my guess is that you're trying to load a .iso file, Beetle PSX and PCSX ReARMed don't support .iso.

Try to find the game in .bin/.cue format or convert it.

**Comment by JojocGR** [comment]
Good to know, will try it once I got some time and close the issue if that resolves it. 
By the by, is there somewhere where I can see which file types are supported by which emulator?

**Comment by JojocGR** [comment]
So, I tried the suggestion above, but unfortunately it did not work. 
Weird thing is that when I went to the open content category, one emulator appears and runs the file fine.

**Comment by bslenul** [comment]
If "Load Content" works after renaming that's great.

Now remove the old entry from your playlist and create a .cue file for the game (using this website for example: http://nielsbuus.dk/pg/psx_cue_maker/) and save it in the same folder as your .bin, then scan that .cue file to re-add the game in your playlist.

**Comment by JojocGR** [comment]
That did the trick, I'll have to convert the games to bin/cue format then. 
Thanks for the assistance, my bad, closing the issue.
