### ISSUE TITLE
Compile with HAVE_NETWORKING = 0 directive doesnt work 

### ISSUE THREAD

**Issue by apison** [libretro/RetroArch#9580]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

I'm trying to compile new retroarch 1.7.9.2 with compiler directive HAVE_NETWORKING = 0 with this option with the older version (1.7.7 and above) all the code regarding the network are not compiled and all works fine. Since version 1.7.8 the conditional compilation doesnt work anymore and compiler trying to compile networking code. Please could someone help me with this issue?  

[Description of the bug]

Even setting the precompile variable HAVE_NETWORKING = 0 the networking code is compiled.
With the 1.7.7 version and lower there was not the problem and the networking code  was not compiled when HAVE_NETWORKING = 0 was setted

[What you expected to happen]

with HAVE_NETWORKING = 0 setted the code regrding the network should not be compiled.

[What is actually happening]

The networking code is compiled even when   HAVE_NETWORKING = 0 is setted.

**Comment by apison** [comment]
For what i've seen, the logic has been implemented in reverse, if  i put 

HAVE_NO_NETWORKING = 0
HAVE_NETWORKING = 1

the networking portion of the code is not compiled.

**Comment by orbea** [comment]
What OS are you running? How are you setting `HAVE_NETWORKING = 0`?

**Comment by apison** [comment]
I'm running retroarch on linux jessie for an arm board, I used to configure the compilation with these command :

./configure --enable-mali_fbdev --disable-x11 --disable-sdl2 --enable-floathard --disable-ffmpeg --disable-udev --enable-sdl --disable-pulse --disable-oss --disable-freetype --disable-libxml2 --host=arm-linux-gnueabihf --disable-networking --enable-opengles --disable-al

Until version 1.7.7 this configuration works correctly, from version 1.7.8 it didnt work anymore.

To make it works again, I changed in the file config.mk that was generated launching ./configure with the above options putting manually HAVE_NO_NETWORKING = 0,HAVE_NETWORKING = 1 this fixed the problem.

**Comment by orbea** [comment]
Please provide a full build log with your including configure output and also share the output of `config.mk` after configure.

**Comment by orbea** [comment]
I was able to reproduce it actually. https://github.com/libretro/RetroArch/pull/9595

**Comment by apison** [comment]
Problem is fixed now Thank you
