### ISSUE TITLE
Title icons not showing in WiiU Retroarch

### ISSUE THREAD

**Issue by YraelTheEighth** [libretro/RetroArch#9581]
![IMG20191009223019](https://user-images.githubusercontent.com/56348513/66481494-6f2a5880-eae4-11e9-9e89-f6bcc3a34d5f.jpg)
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

On loading my roms into retroarch I noticed that the game title icons were showing as distorted images. 

### Expected behavior

Normally, on retroarch windows, there are small icons of cartridges of the relevant console. 

### Steps to reproduce the bug

I first created playlists on my computer using the roms I had stored there, making sure to change the directories in the .lpl's with notepad++ so that they were correct with where I was putting my roms. 
I loaded my SD card with roms, installed retroarch and some recommended cores, and loaded retroarch through the mgba core. 
I saw that the icons were messed up so I redownloaded assets and rebooted. They stayed the same. 
I've since reinstalled retroarch and the cores, and created new playlists. No fix yet. 

### Bisect Results

As soon as I used retroarch on the Wii U. On my windows retroarch installation it works fine. 

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 60574f0

### Environment information

- OS: Wii U

**Comment by twinaphex** [comment]
Hi @gblues and/or @QuarkTheAwesome , can any of you guys reproduce this issue? Thanks in advance.

**Comment by SuperSamus** [comment]
I don't have this bug on my Wii U.
However I didn't download the assets from Wii U's RetroArch, but I copy-pasted them from the PC version of RetroArch. If I remember correctly Wii U's default assets directory is "media", while PC's is simply "assets". Could you try that?
