### ISSUE TITLE
Build failed on rpi4, error making gfx/drivers_context/vc_egl_ctx.o

### ISSUE THREAD

**Issue by Vax50** [libretro/RetroArch#9585]
## Description
I've tried to build RetroArch on my rpi4 and getting this error:
```
CC libretro-common/glsym/glsym_gl.c
gfx/drivers_context/vc_egl_ctx.c:68:4: error: unknown type name ‘EGL_DISPMANX_WINDOW_T’
   68 |    EGL_DISPMANX_WINDOW_T native_window;
      |    ^~~~~~~~~~~~~~~~~~~~~
gfx/drivers_context/vc_egl_ctx.c:73:4: error: unknown type name ‘EGLImageKHR’
   73 |    EGLImageKHR eglBuffer[MAX_EGLIMAGE_TEXTURES];
      |    ^~~~~~~~~~~
gfx/drivers_context/vc_egl_ctx.c:74:4: error: unknown type name ‘EGLContext’
   74 |    EGLContext eglimage_ctx;
      |    ^~~~~~~~~~
...

gfx/drivers_context/vc_egl_ctx.c: In function ‘gfx_ctx_vc_has_focus’:
gfx/drivers_context/vc_egl_ctx.c:501:1: warning: control reaches end of non-void function [-Wreturn-type]
  501 | }
      | ^
make: *** [Makefile:209: obj-unix/release/gfx/drivers_context/vc_egl_ctx.o] Error 1
 ```
### Version/Commit

- RetroArch: v1.7.9.2 4dcd7a02475b38ac98096ceb60b7cc7a779e227b

### Environment information

- OS: Gentoo rpi4 64bit
- Compiler: gcc, g++

**Comment by cmitu** [comment]
How did you `configure` the build ? 

The Raspberry PI4 model has no support for the BRCM (legacy) GLES driver, so you should disable it during configure  (`--disable-dispmanx`) and use the MESA GL libraries if you intend to use the GL video driver.

**Comment by gouchi** [comment]
Try with
`--disable-videocore --disable-opengl1 --enable-kms --disable-x11 --enable-opengles --enable-opengles3 --enable-opengl_core`

**Comment by Vax50** [comment]
Thanks for the fast answers! I have successfully build retroarch with the suggestion of gouchi. it's possible to start retroarch, but only with sdl2 video driver.
```
[INFO] [GL]: Found GL context: kms
[INFO] [GL]: Detecting screen resolution 1366x768.
[INFO] [EGL] Found EGL_EXT_platform_base, trying eglGetPlatformDisplayEXT
[INFO] [EGL]: EGL version: 1.4
[INFO] [EGL]: Current context: 0x558e83ffe0.
[INFO] [KMS]: New FB: 1366x768 (stride: 5464).
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fataler Fehler in: "init_video()"
```

**Comment by gouchi** [comment]
Did you try to launch it in console mode (without Xorg) ?

**Comment by Vax50** [comment]
I've tried to start it through xterm on openbox, i think Xorg working correctly.

**Comment by cmitu** [comment]
In this case, don't add ` --disable-x11` to the configure stage.
