### ISSUE TITLE
(OSX Catalina) Wired USB XBOX 360 Controller not responding (not working)

### ISSUE THREAD

**Issue by LostAccount** [libretro/RetroArch#9590]
## Description

USB Wired XBOX 360 Controller not responding in Mac OS Catalina
![Screenshot 2019-10-12 at 22 24 09](https://user-images.githubusercontent.com/2214319/66707330-0b4f9c00-ed3f-11e9-8211-db474ff1c908.png)

### Bisect Results

Issue began after upgrading to Catalina

### Version/Commit

- RetroArch: 1.7.9

### Environment information

- OS: Mac OS Catalina version 10.15

**Comment by gouchi** [comment]
- First we should wait that the [xbox 360 driver works in Catalina](https://github.com/360Controller/360Controller/issues/942).

**Comment by LostAccount** [comment]
Thank you, I had replied in that thread as a 'me too'. I didn't know RetroArch relied on that, I assumed the driver was independent to that repo. Thanks for the reply.

**Comment by LostAccount** [comment]
Thanks @RobLoach

**Comment by LostAccount** [comment]
The issue is now resolved.
Please see https://github.com/360Controller/360Controller/issues/942 for more details.
