### ISSUE TITLE
Black screen on LCD connected via DisplayPort over USB3

### ISSUE THREAD

**Issue by davidkudera** [libretro/RetroArch#9592]
## Description

I have my LCDs connected to an HP docking station (https://support.hp.com/au-en/document/c05639574) with DisplayPort cables. That docking station is connected to my laptop with USB3 cable. RetroArch starts and runs fine on the laptop's display, but not on the external displays. Instead, the window is just black. I tried both windowed and fullscreen modes. When I start it on the laptop's display and try to move the window to external LCD the RetroArch freezes. I run on an integrated Intel GPU (https://ark.intel.com/content/www/us/en/ark/products/122589/intel-core-i7-8550u-processor-8m-cache-up-to-4-00-ghz.html).

### Expected behavior

Seeing a pretty blue menu (RetroArch) on an external monitor.

### Actual behavior

Seeing a black window.

### Steps to reproduce the bug

1. Install Ubuntu 18.04.3 LTS
2. Install RetroArch from the official flathub repository
3. Run on external LCD connected via DisplayPort over USB3

### Bisect Results

///

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.7.9/4dcd7a0

### Environment information

- OS: Ubuntu 18.04.3 LTS
- Compiler: GCC (8.3.0) 64-bit

**Comment by gouchi** [comment]
Did you try to change [video_monitor_index](https://github.com/libretro/RetroArch/blob/master/retroarch.cfg#L135) in the configuration file ?

May try to you provide some [log](http://docs.libretro.com/guides/generating-retroarch-logs/#retroarch-logs) ?

Thank you.

**Comment by davidkudera** [comment]
Sorry for the delayed answer.

Here is the log: [retroarch.log](https://github.com/libretro/RetroArch/files/4147691/retroarch.log)

I tried to change the monitor index, but there was no difference. Still a black screen. Also, the logs remain the same.

**Comment by davidkudera** [comment]
I'm now on a different system and OS and to be honest I didn't try to run RetroArch again since my last comment. Only the docking station is still the same.

* OS: KDE neon 6.0
* KDE Plasma version: 6.1.3
* CPU & GPU: [AMD Ryzen 9 PRO 7940HS](https://www.amd.com/en/products/processors/laptop/ryzen/7000-series/amd-ryzen-9-7940hs.html)

I use Wayland by default but that gives me an error when I try to run the Appimage (I haven't tried to fix that yet):

```
/tmp/.mount_RetroA5JAyMV/AppRun.wrapped: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags
```

But RetroArch starts without any problem when I switch to X11 so this issue seems to be resolved.

**Comment by gouchi** [comment]
@davidkudera Thank you for your feedback.

It seems that is known issue for the [Appimage and KDE Neon](https://github.com/libretro/RetroArch/issues/15570).

So you may try if possible with the [stable PPA](https://www.retroarch.com/index.php?page=linux-instructions)  to test on Wayland.

Thank you.

**Comment by davidkudera** [comment]
@gouchi Nice, thanks for linking that issue for me.
