### ISSUE TITLE
Android show squares in Chinese

### ISSUE THREAD

**Issue by guoyunhe** [libretro/RetroArch#9613]
### Expected behavior

Chinese characters should be rendered correctly

### Actual behavior

Some Chinese characters are rendered as squares

### Steps to reproduce the bug

1. Change Android system language to Chinese
2. Install RetroArch on Android
3. Open RetroArch

### Version/Commit

- RetroArch: 1.7.9 GIT

### Environment information

- OS: Android Pie

![photo_2019-10-18_22-20-49](https://user-images.githubusercontent.com/5836790/67123488-1bf98980-f1f9-11e9-94a6-723a143ebd19.jpg)

**Comment by FreeShippingParty** [comment]
Set your user interface font to one that supports more Chinese glyphs.

**Comment by guoyunhe** [comment]
> Set your user interface font to one that supports more Chinese glyphs.

It is a Chinese font. All other apps works fine with this font.

**Comment by Antecer** [comment]
Why not delete the embedded fonts in the APP and use the system default fonts instead?

**Comment by guoyunhe** [comment]
The system's default font might not be supported by RetroArch. The only font that is for sure working is Droid Sans Fallback. Replacing all `font.ttf` in retroarch-assets with Droid Sans Fallback can solve the issue.

**Comment by Antecer** [comment]
I think Microsoft Yahei will be ok

**Comment by guoyunhe** [comment]
MS Yahei is not free to use in other software. That means, you cannot bundle it with RetroArch.

**Comment by guoyunhe** [comment]
From my testing, RetroArch never uses system fonts if you have retroarch-assets installed.

**Comment by Antecer** [comment]
```
https://github.com/adobe-fonts/source-han-sans
https://github.com/adobe-fonts/source-han-serif
https://github.com/adobe-fonts/source-han-mono
```
Open source fonts should be the best solution.
`source-han-serif` It even contains some rare and rare words.

**Comment by guoyunhe** [comment]
It is not supported by the font render module of RetroArch. You can try if you are able to manually set the font to Source Han Sans or Noto Sans CJK.

**Comment by Antecer** [comment]
Yes, i can load it:

https://github.com/junmer/source-han-serif-ttf/tree/master/SubsetTTF/CN

**Comment by NewUserHa** [comment]
+1
android 9 default with chinese SG(simplifiled chinese) also show mojibake like in the first comment.
traditional chinese works fine.

please fix. did you use any special fonts for traditional chinese? otherwise, this is impossible because of CJK.

thanks!

**Comment by guoyunhe** [comment]
I am working on a fix. You can watch this thread. https://github.com/libretro/retroarch-assets/pull/338
