### ISSUE TITLE
Missing release tarballs

### ISSUE THREAD

**Issue by bentley** [libretro/RetroArch#9620]
Since 1.7.7, the releases page no longer contains any files beyond GitHub’s autogenerated tarballs.

The versioned `.tar.xz` and `.zip` files that used to be [attached to each release](https://github.com/libretro/RetroArch/releases/tag/v1.7.7) contained additional assets that aren’t present in either the main RetroArch repo or in the autogenerated tarballs. I use the `.tar.xz` files to build [the OpenBSD package](https://cvsweb.openbsd.org/ports/emulators/retroarch/).

As far as I can tell, the `.tar.xz` files aren’t present on buildbot.libretro.com either. The GitHub releases page is the only place I know how to find them.

Please generate these assets as was done through 1.7.7. (Or is not providing them anymore intentional?)

**Comment by RobLoach** [comment]
Download through the downloads page or through buildbot:
https://retroarch.com/?page=platforms
http://buildbot.libretro.com/

Unsure the github releases are actively supported.

Alternatively, you could get through assets, overlays and joypad autoconfig through their respective git repos:
https://github.com/libretro/retroarch-assets

**Comment by orbea** [comment]
> Unsure the github releases are actively supported.

https://github.com/libretro/libretro-super/blob/master/retroarch-release.sh

**Comment by RobLoach** [comment]
While this does package a .tar.xz and .zip file, I don't see a step that pushes the packages files to https://github.com/libretro/RetroArch/releases

**Comment by orbea** [comment]
It has to be uploaded manually to the releases page, I'm not sure a way to automate that part.
