### ISSUE TITLE
Retroarch savestates became extremely slow

### ISSUE THREAD

**Issue by i30817** [libretro/RetroArch#9622]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Very slow savestate operation.

### Expected behavior

Not expecting 16mb (beetle) savestates to take more than 2 minutes to complete.

### Actual behavior

That happens. It's not limited to beetle either, even snes9x is slower (not to the same extent, appears to 'scale' with the save size).

### Steps to reproduce the bug

1. Install (on linux) bpftrace
2. run (replace /usr/bin by where-ever your local RA is, i used a local build)
`$ sudo bpftrace -e 'uprobe:/usr/bin/retroarch:task_push_save_state { @start=nsecs;}  uprobe:/usr/bin/retroarch:task_save_handler { @probe = count(); } uprobe:/usr/bin/retroarch:task_save_handler_finished { printf("elapsed ms %d:\n", (nsecs -@start) / 1000000); exit(); } '`
3. start retroarch, load a beetle core and a game, savestate and wait...
4. My 'results', which indicate 163 seconds of 'save' plus 4096 invocations of 'task_save_handler' (probably the cause of the 163 seconds):
```
Attaching 3 probes...
elapsed ms 162985:
@probe: 4096
@start: 188718398406248
```

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: `Linux AIVAS 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Compiler: `gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1)`

**Comment by i30817** [comment]
I suspect that this may be caused by a attempt to make the savestate banner 'appear' for more than a millisecond.

If that's true, I'd request that savestates get written _all at once_ and the banner be another task posted on task_save_handler_finished instead of what's happening.

**Comment by twinaphex** [comment]
That's not good.

So your suspicion is that menu widgets here is to blame? Can you turn menu widgets off and see if it affects the performance then in a beneficial way?

**Comment by i30817** [comment]
My suspicion is that the division of work of `task_save_handler` (that was *probably* related to the widget, to make it display) is slowing down the file I/O). I haven't found where that division is done or how to affect the granularity. Some help please?

**Comment by i30817** [comment]
Ah, it's supposed to read 4096 bytes at a time, but it's done by:

```
   if (!state->data)
      state->data  = get_serialized_data(state->path, state->size);

   remaining       = MIN(state->size - state->written, SAVE_STATE_CHUNK);

   if (state->data)
      written      = (int)intfstream_write(state->file,
         (uint8_t*)state->data + state->written, remaining);
   else
      written      = 0;

   state->written += written;

   task_set_progress(task, (state->written / (float)state->size) * 100);
```

in `task_save_handler`.

So it appears the problem is not the chunk per-se, but that the 'state->written' is minuscule? Or maybe the 'else' is being taken a lot.

It would sort of make sense if the filesystem didn't finish writing the '4096' bytes before this is called again and some different 'write' is posted... though that sounds ridiculous and possibly dangerous (factorial write?)

**Comment by i30817** [comment]
There is this curious define on top of the file:

```
#ifdef HAVE_LIBNX
#define SAVE_STATE_CHUNK 4096 * 10
#else
#define SAVE_STATE_CHUNK 4096
#endif
```

So it seems this was already a recognized problem on the Switch. Apparently all retroarch devs have advanced enough computers that they weren't noticing this slow down but the console porters did.

**Comment by RobLoach** [comment]
> Apparently all retroarch devs have advanced enough computers that they weren't noticing this slow down but the console porters did.

I'm not able to reproduce this issue on my RPi Zero. What Beetle core are you loading? What game?

**Comment by i30817** [comment]
In order: I'm using the normal core from the online updater, any game, retroarch.cfg is pointless [but sure](https://gist.github.com/i30817/0715791d9a25459fbed774b0be14beac), logs don't show anything interesting [but sure](https://gist.github.com/i30817/1314399d5c1cc661d9c8a29c8b9c3d9d).

The bpftrace i showed above shows all the important information i think, can you please try it on your PI to see the number of iterations and the time elapsed? This kind of trace doesn't need recompilation.

**Comment by i30817** [comment]
Another way to adjust this would be to make `SAVE_STATE_CHUNK` variable.

If it depends on the size of the save, such as that the number of iterations will always tend to around 100 or less (1%+ increments) the animation will play but the slowness will be more limited that 'increments of 100/4096' like in beetle (and i imagine it's even worse for ppsspp and dolphin though i haven't tested it).

**Comment by i30817** [comment]
I also tried the `--disable-menu_widgets configure option now. It's 'faster' but not that fast:
```

Attaching 3 probes...
elapsed ms 51867
@probe: 4096
@start: 253575404592667
```
(still on beetle, forgot the game i used so it's probably different but shouldn't make any difference because all the savestates are 16mb).

**Comment by LordArchantos** [comment]
I have the same issue on Windows x64, Beetle PSX state saving **and loading** are very slow, the same with Mame (git) core, regardless of the game. Both saving and loading are also affected by fast forward, i.e. triple game speed, triple state save/load speed.

**Comment by i30817** [comment]
> > Apparently all retroarch devs have advanced enough computers that they weren't noticing this slow down but the console porters did.
> 
> I'm not able to reproduce this issue on my RPi Zero.

@RobLoach i found the reason for this. Simply told this is a problem that 'shows up' when you're either on a platform without threads _or_ you have `threaded_data_runloop_enable = "false"` on the retroarch.cfg.

It's still a real problem and a gotcha, and it can be made 'tolerable' on those platforms by making `SAVE_STATE_CHUNK` proportional to the size of the savestate to write or read.

@LordArchantos , try setting `threaded_data_runloop_enable = "true"` (on the GUI on options->UI->threaded tasks) or the cfg file.

**Comment by LordArchantos** [comment]
@i30817 , thanks, that worked, instant actions now.

**Comment by i30817** [comment]
> @i30817 , thanks, that worked, instant actions now.

They're not instant, they're just not delaying the main emulation thread with IO. All things considered, i still believe that if progress bar percentages are going to potentially hamper I/O, they should do in a predictable number of iterations; even if it's not a issue outside of certain platforms or if you don't disable that.

Consider the scenarios:
1) you have a multicore computer and savestate saving is 'instant', such that the progress bar doesn't appear or zips through in another thread.
2) you don't, and the progress bar delays the main emulation thread.

In the first, people with super computers don't even notice that there was a progress bar often. In the second they're hit with this variable (and awful) delay because `SAVE_STATE_CHUNK` is a constant that is independent of the savestate size, thus creating more delay the larger the savestate, already being all but intolerable in even the SNES, much less ps1 up.

**Comment by orbea** [comment]
I don't think its a bug that savestates are much slower when not threaded, that is just expected.

**Comment by i30817** [comment]
It's a bug that they take 2.5 minutes for a simple 16mb save to me. This can all be avoided by making the segmentation of savestate io coarser, so it increases the bar (the only reason it can even be slow) by 2% instead of 0.1% per iteration.

**Comment by Rangnarok123** [comment]
I am just here reporting to have this same problem as well.
The option: threaded_data_runloop_enable = "true" is already enabled in the cfg file.

I have had this in older versions too, but still have this in latest PC retroarch for Win 64x. 
My PC is quite fast, so it's not a problem of the PC being slow (I am on 4570K, 970GTX, 16GB ram)
Save state on older emulator like ePSXe is still very fast.

**Comment by i30817** [comment]
Sounds like there is something weird happening. It's a pity it manifests on windows, because windows can't use bpfprobe to narrow it down without a dev compiling the code.

**Comment by Rangnarok123** [comment]
> 
> 
> Sounds like there is something-other weird happening. It's a pity it manifests on windows, because windows can't use bpfprobe to narrow it down without a dev compiling the code. Linux gets all the good debugging toys.
> 
> Please check if your 'retroarch-core-options.cfg' doesn't disable the setting again (or check it's on in 'user interface->threaded tasks' after turning on the advanced options in the setting there if you can't find it).

I did all of those, and good news, Savestate works instantly now. Same for loading ss. Not sure exactly which one made it work, but I did the "threaded tasks" before checking the threaded_data_runloop_enable in the cfg. Thank you for your suggestions.

**Comment by i30817** [comment]
They're supposed to be one and the same, just the gui vs the cfg. Maybe you're not using the same cfg as you think you are? Just a thought, you can check by enabling logging and starting RA from a command line and seeing what file the command line shows as the config file. Remember to turn logging off after because it has a small performance impact.

**Comment by Rangnarok123** [comment]
> 
> 
> They're supposed to be one and the same, just the gui vs the cfg. Maybe you're not using the same cfg as you think you are? Just a thought.

Gotcha. I remember I did a restart yesterday after I change it in the GUI, but it didn't work. Today I was notified by my kids that the savestates worked instantly and they were so happy. I am not sure what happened, but it must be to do with that option.

**Comment by i30817** [comment]
Is this actually completed?

**Comment by i30817** [comment]
According to the source, no it is not. Please reopen this, it's a major major slowdown in any platform without threading support and it's completely unnecessary.

**Comment by i30817** [comment]
Fine, i'll simply reopen this with a video so you can see the extreme foolishness of not fixing this.

**Comment by LibretroAdmin** [comment]
We will certainly appreciate that video. We are simply trying to work through an extensive backlog of issues and we definitely want to focus on buffering vs. Adding big new features right now. So definitely keep reports coming.

It's simply hard to tell what is still relevant from years ago vs what isn't. Sorry that we made the wrong call here.
