### ISSUE TITLE
Switch, 1.7.9, "don't run in background" not working

### ISSUE THREAD

**Issue by Stuntaneous** [libretro/RetroArch#9623]
### Description

"Don't run in background" has no effect. The game continues on, and sound from it can be heard outside of Retroarch. It previously worked in 1.7.7 (in 8.1.0 / 0.9.3) for me.

### Environment information

Switch 9.0.1, Atmosphere 0.9.4

**Comment by m4xw** [comment]
Invalid Issue.
Stop using NSP's.
This is not supported.
