### ISSUE TITLE
Ps Vita : Translation file.

### ISSUE THREAD

**Issue by Youpi-38** [libretro/RetroArch#9624]
Hello,
I'm French and I use Retroach on PS VITA (Thanks for that ;-)).
I would like to change a few words (Just for me) for the menu displayed on the screen but I can not find the file.
Can you tell me what is its location?
Thank you very much.

**Comment by Rinnegatamante** [comment]
You can't edit words "just for you" unless you plan to re-compile RetroArch manually with every single core.

**Comment by Youpi-38** [comment]
Hello and thank you for your answer.  
I thought there was a file that could be edited easily.  
The most problem for the French translation is that the word "Core" is that it is displayed "C?re".  And for my part I would have translated into French by "Emulateur".  
;-)
