### ISSUE TITLE
[glui] Hide Playlist Icon When "Show Playlist Tabs" Disabled

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#9627]
## Description

When the "Show Playlist Tabs" Appearance/Views option is disabled, the playlist icon at the bottom of the glui menu driver is still displayed.

### Expected behavior

The playlist icon should be hidden when "Show Playlist Tabs" is disabled.

**Comment by jdgleaver** [comment]
I plan to rewrite the navigation bar code pretty soon - I'll try to address this issue :)

**Comment by Awakened0** [comment]
Looking forward to it :D
