### ISSUE TITLE
[glui] [Feature Request] Layout Width Option

### ISSUE THREAD

**Issue by Awakened0** [libretro/RetroArch#9628]
## Description

rgui has an option called "Use Full-Width Layout". When disabled, it puts settings variables closer to the name of the setting. This makes it easier to see what your settings are set to on large monitors, since your eyes don't have to move to see the right edge of the screen. glui could use an option like this to improve readability on such displays.

**Comment by jdgleaver** [comment]
@Awakened0 I had a play with this, but using a non-full-width RGUI-style layout looked really bad...

So I've added a new `Optimize Landscape Layout` option instead, which can be used to reduce the effective width of the screen (there are screenshots at the end of the PR comment): https://github.com/libretro/RetroArch/pull/9630

I know it's not exactly what you wanted, but I think it works quite well...

**Comment by Awakened0** [comment]
Actually that looks quite good to me. Thanks!
