### ISSUE TITLE
[Bounty $20] Runahead - Cheats aren't applied to the second instance

### ISSUE THREAD

**Issue by SourMesen** [libretro/RetroArch#9639]
When using runahead with "use second instance" enabled, it looks like cheats are not getting applied to the secondary core. I've searched through RetroArch's code, but the cheats only appear to be set in `core_set_cheat` and `core_reset_cheat`, which only apply the cheats to the main core.

And as far as I can tell (by running RetroArch in a debugger), the core's retro_set_cheat function is only called once if a single cheat is active (whereas I would expect it to be called twice when use second instance is enabled) 

A detailed description of what this causes (in Mesen-S) is given in this post by cubatilles: https://forums.libretro.com/t/bsnes-hd-input-delay/24422/33

They said the cheats work in snes9x with the `use second instance` option, but I'm assuming this is because snes9x most likely applies cheats by modifying the contents of RAM permanently (which means the save states shared between both core instances will share the cheats as well), whereas Mesen-S doesn't actually alter the content of memory when cheats are enabled.

I've reproduced the issue locally on 1.7.5 (and cubatilles was using 1.7.9), so this doesn't appear to be a new issue, either.

**Comment by cubatilles** [comment]
Hi @SourMesen ,

I've created a bounty for this:
https://www.bountysource.com/issues/82648241-runahead-cheats-aren-t-applied-to-the-second-instance

Could you edit this subject to add the tag? Thanks!

**Comment by SourMesen** [comment]
@cubatilles I've added it to the title

**Comment by Tatsuya79** [comment]
I noticed that issue with fceumm as well.

**Comment by jdgleaver** [comment]
This should be fixed by #12931

**Comment by cubatilles** [comment]
Hi @jdgleaver ,

Thank you very much for your work. There was a bounty for this that I've created time ago. Please go and claim it:

https://www.bountysource.com/issues/82648241-bounty-20-runahead-cheats-aren-t-applied-to-the-second-instance

Greetings.

**Comment by jdgleaver** [comment]
@cubatilles You are very welcome - I am happy to help!

Thank you for the bounty :)
