### ISSUE TITLE
GLUI rotation issues

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/RetroArch#9641]
@jdgleaver 

Galaxy S3 android 4.1.2, RA 32bits 45deb2c

Starting RA in portrait:

![Screenshot_2019-10-26-23-09-27](https://user-images.githubusercontent.com/6266038/67626053-84261c00-f846-11e9-9db7-e4f1d2bba9c4.png)

then rotating into landscape:

![Screenshot_2019-10-26-23-09-39](https://user-images.githubusercontent.com/6266038/67626055-8e481a80-f846-11e9-8a43-bd33efcfc68c.png)

Lost the navigation bar, scrollbar, battery icon.
(if nav bar is set to stay on bottom, it's still visible but loses the last 2 icons; "settings" and "resume").

Now starting in landscape:

![Screenshot_2019-10-26-23-10-02](https://user-images.githubusercontent.com/6266038/67626076-c94a4e00-f846-11e9-9336-82e7befccfd1.png)

Looks fine, rotating into portrait:

![Screenshot_2019-10-26-23-10-14](https://user-images.githubusercontent.com/6266038/67626078-de26e180-f846-11e9-8d7a-f1d9440efc9f.png)

We lost the top icons and the battery. Scrolling down the list icons keep disappearing:

![Screenshot_2019-10-26-23-10-21](https://user-images.githubusercontent.com/6266038/67626088-01ea2780-f847-11e9-8d05-34930c1a76af.png)

**Comment by jdgleaver** [comment]
@Tatsuya79 That is absolutely baffling...

It's like your device is completely messing up the context reset event - it's not reloading the icons correctly, and the reported width/height is going haywire... But more than that: the quads behind the menu title and navigation bar are getting lost - but in the case of the title bar at least, the text location is correct, so it's not even a case of the x/y position going wrong...

There's no way I can reproduce this. I'm going to need some debug logging from your device to even begin to understand what's going on here...

If I post a debug build, would you mind testing & sending me a log file? (I know this is a bit annoying - Android has a habit of not wanting to sideload self-built APKs for apps that are already installed, and I had to mess about quite a bit when testing the glui updates on my tablet...)

I'll try to post something later today, or tomorrow (if I run out of time...). And maybe we can continue this on Discord...
