### ISSUE TITLE
PS3's and PSP's RetroArch annoying problems

### ISSUE THREAD

**Issue by Windows10User2** [libretro/RetroArch#9643]
After setting PS3's RetroArch's 1.8.0's Aspect Ratio setting to "Custom" for each one of the cores I use and save its configuration I have to set it again in some cores' case because the Aspect Ratio setting is blank so I'll have a black screen in these cases when running games if I don't set the Aspect Ratio to "Custom" (or other setting), which is annoying. Is this normal? I've been having this problem for a long time.

Also, when will PSP's RetroArch be updated and have no problems playing GBA ROMs?

**Comment by bmaupin** [comment]
> Also, when will PSP's RetroArch be updated and have no problems playing GBA ROMs?

Aside from the fact that this should be in its own issue, it really depends what you mean by "no problems" :)

As best as I'm aware, the PSP isn't powerful enough to play GBA games at native speed. None of the emulators I found were able to do so without some hacks, most notably frame skipping. You can see my results of testing several games on 4 separate emulators as well as RetroArch here to get an idea: https://gist.github.com/bmaupin/dac967cd0c527cab028a3bb5c2c11762

When it comes to playing GBA games on the PSP using RetroArch, you have two options, both based on existing emulators: gpSP and TempGBA. gpSP is slightly faster whereas TempGBA has better compatibility with some games. For both of these cores, the audio will stutter for many games unless you enable frame skipping.

Frame skipping for gpSP was only recently added, so you may need to wait until the next release of RetroArch. Or I can compile it for you if it really interests you.

Hope that helps!

**Comment by Windows10User2** [comment]
> > Also, when will PSP's RetroArch be updated and have no problems playing GBA ROMs?
> 
> Aside from the fact that this should be in its own issue, it really depends what you mean by "no problems" :)
> 
> As best as I'm aware, the PSP isn't powerful enough to play GBA games at native speed. None of the emulators I found were able to do so without some hacks, most notably frame skipping. You can see my results of testing several games on 4 separate emulators as well as RetroArch here to get an idea: https://gist.github.com/bmaupin/dac967cd0c527cab028a3bb5c2c11762
> 
> When it comes to playing GBA games on the PSP using RetroArch, you have two options, both based on existing emulators: gpSP and TempGBA. gpSP is slightly faster whereas TempGBA has better compatibility with some games. For both of these cores, the audio will stutter for many games unless you enable frame skipping.
> 
> Frame skipping for gpSP was only recently added, so you may need to wait until the next release of RetroArch. Or I can compile it for you if it really interests you. (Edit: Here you go:
> [gpsp_libretro.PBP.zip](https://github.com/libretro/RetroArch/files/4314162/gpsp_libretro.PBP.zip))
> 
> Hope that helps!

Thanks for answering!

Sorry, but where should I have posted this question and could you answer my first one?

I usually don't play PSP games with sound enabled but I don't think I have ever had any problem with its sound using gpSP (I never used in on RetroArch and I don't even recall seeing it there) but I don't know if I had frame skipping enabled. Well, the things is, I'm getting used to play GBA ROMs with mGBA in the PS3's RetroArch so I wanted to have it on the PSP too but I guess I can try that. Could you tell me the advantages and disadvantages of enabling/disabling frame skipping?

Thanks and sorry for my english (t isn't my native language)!

**Comment by bmaupin** [comment]
> Sorry, but where should I have posted this question

This is the right place, but since you're asking about two separate things, in general it's best to create them as two separate issues.

> and could you answer my first one?

This is a perfect example, because I don't know anything about PS3, so I can't help. Sorry!

> I'm getting used to play GBA ROMs with mGBA in the PS3's RetroArch so I wanted to have it on the PSP too

The PSP has an mGBA core but from my experience it's too slow to be playable. That's why I recommended gpSP or TempGBA.

> Could you tell me the advantages and disadvantages of enabling/disabling frame skipping?

You mentioned having "problems," so it really depends what your problems are. In general, frame skipping is a last resort when a system or a core simply isn't fast enough to play a certain game. It may make a game playable but it skips frames, so the video won't be as smooth.

**Comment by Windows10User2** [comment]
> > Sorry, but where should I have posted this question
> 
> This is the right place, but since you're asking about two separate things, in general it's best to create them as two separate issues.
> 
> > and could you answer my first one?
> 
> This is a perfect example, because I don't know anything about PS3, so I can't help. Sorry!
> 
> > I'm getting used to play GBA ROMs with mGBA in the PS3's RetroArch so I wanted to have it on the PSP too
> 
> The PSP has an mGBA core but from my experience it's too slow to be playable. That's why I recommended gpSP or TempGBA.
> 
> > Could you tell me the advantages and disadvantages of enabling/disabling frame skipping?
> 
> You mentioned having "problems," so it really depends what your problems are. In general, frame skipping is a last resort when a system or a core simply isn't fast enough to play a certain game. It may make a game playable but it skips frames, so the video won't be as smooth.

Ok, thanks, I didn't know that but it's strange being unable to download the PS3 version for some time since it disappeared from the site.

Thanks for the explanation!

**Comment by Windows10User2** [comment]
> > Sorry, but where should I have posted this question
> 
> This is the right place, but since you're asking about two separate things, in general it's best to create them as two separate issues.
> 
> > and could you answer my first one?
> 
> This is a perfect example, because I don't know anything about PS3, so I can't help. Sorry!
> 
> > I'm getting used to play GBA ROMs with mGBA in the PS3's RetroArch so I wanted to have it on the PSP too
> 
> The PSP has an mGBA core but from my experience it's too slow to be playable. That's why I recommended gpSP or TempGBA.
> 
> > Could you tell me the advantages and disadvantages of enabling/disabling frame skipping?
> 
> You mentioned having "problems," so it really depends what your problems are. In general, frame skipping is a last resort when a system or a core simply isn't fast enough to play a certain game. It may make a game playable but it skips frames, so the video won't be as smooth.

So does that mean there's no perfect solution for the slowdowns?

**Comment by Windows10User2** [comment]
> Just use gpSP core on PSP. PSP is slow outdated hardware, you cannot really expect much beyond gpSP, and gpSP should frankly be good enough on that hardware.
> 
> The gpsp core also made TempGBA completely obsolete BTW (it was just a gpsp fork), so no reason to use that anymore.

What's the difference between UO gpSP Kai 3.4 Test 4 Build 230 (slim) and PSP's RetroArch's gpSP?

**Comment by bmaupin** [comment]
I don't have a PSP any more, but in my experience, the original gpSP was the fastest at GBA emulation on the PSP, and even it couldn't run play most games at full speed. There are a multitude of forks of gpSP and most of them fixed various game compatibility but sometimes at a small performance hit. As far as I know the RetroArch gpSP core is the only fork of gpSP that's still maintained, so it's the only one that's seen any improvement in years.

It's been a couple years since I've touched any of this, but off the top of my head, here are your options with RetroArch gpSP:

1. Keep frame skipping off (the default). You will not get full speed in many (most?) games, which will cause audio crackling and possibly visible slowdowns
2. Set automatic frame skipping. This would allow games that run at full speed to run at full speed and others to skip frames as necessary. However, games that don't run at full speed won't skip frames at a constant rate so it may feel a little bit jittery. But at least it would prevent audio crackling
3. Use manual frame skipping. This was my choice back in the day. You could set it to set it to 1 (to skip every other frame), for example, to get a constant 30 fps

**Comment by Windows10User2** [comment]
> I don't have a PSP any more, but in my experience, the original gpSP was the fastest at GBA emulation on the PSP, and even it couldn't run play most games at full speed. There are a multitude of forks of gpSP and most of them fixed various game compatibility but sometimes at a small performance hit. As far as I know the RetroArch gpSP core is the only fork of gpSP that's still maintained, so it's the only one that's seen any improvement in years.
> 
> It's been a couple years since I've touched any of this, but off the top of my head, here are your options with RetroArch gpSP:
> 
> 1. Keep frame skipping off (the default). You will not get full speed in many (most?) games, which will cause audio crackling and possibly visible slowdowns
> 2. Set automatic frame skipping. This would allow games that run at full speed to run at full speed and others to skip frames as necessary. However, games that don't run at full speed won't skip frames at a constant rate so it may feel a little bit jittery. But at least it would prevent audio crackling
> 3. Use manual frame skipping. This was my choice back in the day. You could set it to set it to 1 (to skip every other frame), for example, to get a constant 30 fps

So, do you recommend me to use TempGBA, RetroArch's TempGBA, UO gpSP Kai 3.4 Test 4 Build 230 (slim) or RetroArch's gpSP? Are there different TempGBA and gpSP game compatibility issues? What about RetroArch's mGBA?

Also, what GBA emulator should I use in the PS Vita? UO gpSP Kai 3.4 Test 4 Build 230 (slim), mGBA, TempGBA, PS Vita's RetroArch's gpSP/mGBA/TempGBA?

**Comment by LibretroAdmin** [comment]
No they are not better, and RetroArch gpsp is the only one actively developed Also, our Github issues are not to be misused  for standalone vs. RetroArch comparisons, please do not do this again in the future.

Closing.
