### ISSUE TITLE
(Menu) List of core games

### ISSUE THREAD

**Issue by guoyunhe** [libretro/RetroArch#9655]
Here are some core games: 2048, Craft are my favorites. To run the game, the steps are:

1. Enter "Load Core".
2. Select "Craft" core.
3. Enter "Run Core".

It is easy but not very straightforward. 

1. Games are mixed with emulators. It is harder to find them. If the number of core games grow even bigger, the list will be hard to use for daily gaming.
2. Here isn't thumbnails for game cores.
3. Other emulator games have their lists, you choose a game and run it. But for core games, the menu entry is "Run Core".

My suggestion is to have a list called "Core Games" which list all installed game cores. Users can navigate to the list, browsing games and run them.

**Comment by zoltanvb** [comment]
I believe this can be closed nowadays as it is available, current name for this function is "Contentless cores".
