### ISSUE TITLE
Good morning gentlemen, Is there any way to disable the device request menu when a player 2 or 3 enters a netplay section? Because here in Brazil, there are a lot of dumb people who are entering the online gaming sections just to end the game. They even enter even if there is a password in the open room. I assume that this feature of being able to fully enter and dominate a game is a minor system flaw, as anyone who enters a netplay section has the potential to end the game. And this has happened

### ISSUE THREAD

**Issue by Suenildo** [libretro/RetroArch#9665]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
Please put this in your subject next time. The message even cuts off.

**Comment by cxtal** [comment]
Related #10151
