### ISSUE TITLE
Default shader is not saved

### ISSUE THREAD

**Issue by valrak** [libretro/RetroArch#9674]
## Description
Default shader is not saved when exiting Retroarch (with save config on exit), nor loaded if configured manually.

### Expected behavior
Retroarch saves current shader default and load it on core start.

### Actual behavior
Default shader is not saved when exiting Retroarch (with save config on exit), nor loaded if configured manually.

### Steps to reproduce the bug

1. Run any core.
2. In quick menu -> shaders load any shader
3. Exit Retroarch
4. Start Retroarch and any core

### Version/Commit
- RetroArch: 1.8.0

### Environment information

- OS: Raspbian on RPI4
- Compiler: GCC 8.3.0 32-bit
- Compiler parameters: CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --enable-alsa --enable-udev --enable-neon --disable-videocore --enable-opengles --enable-opengles3 --disable-opengl1 --enable-x11

**Comment by bslenul** [comment]
You have to save it as a "global preset" now, go to `Quick Menu > Shaders`, load shaders/presets then (still in shaders menu): `Save > Save Global Preset`.

**Comment by valrak** [comment]
I must have missed it in the release notes, thanks.
