### ISSUE TITLE
XPERIA Play Android 6.0 Input Issue

### ISSUE THREAD

**Issue by andrewkendall** [libretro/RetroArch#9686]
I've upgraded my XPERIA Play to Android 6.0, which is working surprisingly well.

I know that RetroArch does some magic to join the two controllers on the device into one:

https://github.com/libretro/RetroArch/blob/c260b196400de29339c06fd8b62c976cd7276121/input/drivers/android_input.c

```
    /* XPERIA Play
    * This device is composed of two hid devices
    * We make it look like one device
    */
   else if(
            (
               strstr(device_model, "R800x") ||
               strstr(device_model, "R800at") ||
               strstr(device_model, "R800i") ||
               strstr(device_model, "R800a") ||
               strstr(device_model, "R800") ||
               strstr(device_model, "Xperia Play") ||
               strstr(device_model, "Play") ||
               strstr(device_model, "SO-01D")
            ) && (
               strstr(device_name, "keypad-game-zeus") ||
               strstr(device_name, "keypad-zeus") ||
               strstr(device_name, "Android Gamepad")
            )
         )
```

Under Android 6.0 the device_name appears to be different, so the inputs show up as two devices.

Here is RetroArch showing the detected input names: https://imgur.com/a/f6nzAGA (gpio-keypad and pm8xxx-keypad)

Would I be correct in assuming if the new device_names were also included the newer Android version would also work as before?

**Comment by fr500** [comment]
It should, yes assuming the device model is one of those too
