### ISSUE TITLE
Network connection error

### ISSUE THREAD

**Issue by DerpyXD** [libretro/RetroArch#9691]
I'm trying to download the emulator cores, but it gives the "Task Failed" error. I want to connect to my network to download the cores, has anyone ever had this same problem, helps me to fix? Thanks

Platform: Linux
OS: Deepin
Version: 1.8.1
Installation method: using Snap

**Comment by gouchi** [comment]
Please open first this [issue to dedicated  repository](https://github.com/libretro/retroarch-snap/issues).

Thank you.

**Comment by RobLoach** [comment]
Running Retroarch from the command line and posting the logs would be good too.
