### ISSUE TITLE
RetroArch fails to start under Weston (XU4 hardware)

### ISSUE THREAD

**Issue by escalade** [libretro/RetroArch#9696]
## Description

RetroArch fails to start under Weston.

### Expected behavior

I expect it to work :)

### Actual behavior

This is the last output before RetroArch freezes:

```
[INFO] [GLCore]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
[INFO] [GLCore]: VSync => on
[INFO] [EGL]: eglSwapInterval(1)
```
- RetroArch: [4d6555d]
- Weston: [ccf2407]
- Wayland: [d5055ad]
- Linux: [5.2.21]
- libmali: [r12p0-04rel0]

### Environment information

- OS: My own LibreELEC fork (https://github.com/escalade/RetroELEC)
- Compiler: GCC 9.2

Building for x86_64 using the same tree works great, I can run RetroArch under Weston. This is somehow specific to either libmali or I suppose the kernel version or config that I use for the XU4.

I can run weston-simple-egl fine, also KMS works great.

### Logs

RetroArch: http://ix.io/20Zc
retroarch.cfg: http://ix.io/20Zg
Weston: http://ix.io/20Zd
dmesg: http://ix.io/20Ze

Configure flags:  $ ./configure --host=armv7ve-libreelec-linux-gnueabi --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --libdir=/usr/lib --libexecdir=/usr/lib --localstatedir=/var --disable-static --enable-shared --disable-vg --disable-sdl --disable-sdl2 --disable-qt --enable-opengles --enable-pulse --enable-wayland --disable-x11 --enable-opengles3 --enable-opengl_core --enable-neon --disable-builtinflac --disable-builtinzlib --disable-xinerama --enable-freetype

**Comment by natinusala** [comment]
Can you try forcing the fullscreen resolution in the RetroArch config and see if it solves the issue?

**Comment by escalade** [comment]
This turned out to be a libmali issue, symlinking libwayland-egl.so to libmali.so solved it.

**Comment by natinusala** [comment]
Indeed the libmali repository has a .pc for wayland-egl that links -lMali instead of -lwayland-egl

Glad to see it's solved
