### ISSUE TITLE
[vita] PCSX-ReArmed stutters/lags after resume from sleep mode

### ISSUE THREAD

**Issue by fish47** [libretro/RetroArch#9699]
### Steps to reproduce the bug
1. load PCSX-ReArmed core
2. load PS1 game
3. put Vita into sleep by pushing the power button
4. push the power button again and resume Vita
5. graphics / sound lag unless reload the game

### Environment information
vita 3.60 enso
retroarch 1.8.1

### What I have tried
1. pausing Retroarch by PS-key gives the same result
2. changing menu driver doesn't help
3. games confirmed: <Resident Evil 2> <Jackie Chan Stuntmaster>

### Related threads / issues
https://github.com/libretro/RetroArch/issues/3793#issuecomment-273492157
https://forums.libretro.com/t/problem-with-pcsx-rearmed-on-vita/11585
https://gbatemp.net/threads/retroarch-libretro-thread-ps-vita-edition-nightlies-included.437034/page-69#post-6712670

**Comment by fish47** [comment]
install [repatch](https://github.com/dots-tb/rePatch-reDux0/releases) plugin seem to fix.

https://github.com/libretro/RetroArch/issues/9617
https://www.reddit.com/r/vitahacks/comments/9llg93/freezes_on_retroarchpcsxrearmed_core_20180918/e77z81v/?context=3

**Comment by fish47** [comment]
maybe we should add this special requirement for vita users ?

**Comment by Rinnegatamante** [comment]
This is a bug in Henkaku but who's in charge of it (Molecule Team) doesn't care of fixing it. (Proposed a fix with connected PR like an year ago and still this is unsolved). Most likely will never be addressed so rePatch will be required.
