### ISSUE TITLE
about retroarch on 3ds

### ISSUE THREAD

**Issue by Johngew** [libretro/RetroArch#9702]
I have run retroarch on N3DS LL and I always clock 803+L2.

I found out there is save states/Load states on PS1 emulators and I just WOW.
I have a idea is there a way to run NDS cart or .NDS file on retroarch ?
purpose is save/load states.

**Comment by Rinnegatamante** [comment]
RetroArch can't access specific "submodes" of some platforms (namingly: DS mode on 3DS, GBA mode on DS, PSP mode on PSVITA, PSX mode on PSP).

You could run probably a DS emulator on 3DS via RetroArch if someone will ever port a DS core to this target platform however performances would be atrocious (for the motivation i've said before).

So, long story shoty, nope.
