### ISSUE TITLE
Retroarch 1.7.2/1.8.1 Vita - Mame2003 Rewind Problem 

### ISSUE THREAD

**Issue by Nube79** [libretro/RetroArch#9705]
## Description

Rewind don't Work.

### Expected behavior

Rewind the game

### Actual behavior

Shows error: Incompatible save file
![image](https://user-images.githubusercontent.com/38857477/68536704-50271c80-0357-11ea-8f77-8624f7fdac8d.png)

### Steps to reproduce the bug

1. Enable rewind
2. Set a button to rewind
3. Press rewind button in game

### Bisect Results

in Retroarch 1.7.2 and above

### Version/Commit

- RetroArch: From 1.7.2 to Current 1.8,1

### Environment information

- OS: Playstation Vita 3.65
- Compiler: Releases

**Comment by fr500** [comment]
bad savestates = bad rewind

**Comment by Nube79** [comment]
The NegoGeo Roms with Mame2003 works great.
