### ISSUE TITLE
Can't set "User 2 Device Type" to a 4axis gamepad in dosbox svn because of a bug in RetroArch.

### ISSUE THREAD

**Issue by Gagert** [libretro/RetroArch#9716]
### Description

Can't set "User 2 Device Type" to a 4axis gamepad in dosbox svn because of a bug in RetroArch, or set "User 3 Device Type" or higher numbered device types as a 2axis gamepad in the same libretro core. This is referencing [Issue 11](https://github.com/libretro/dosbox-svn/issues/11) in the dosbox svn libretro core issue tracker.

### Expected behavior

I originally created the thread linked to above, because I assumed it was an issue with the dosbox svn libretro core itself. However, I'm being told by one of the authors of this libretro port of dosbox svn that this issue might be a frontend issue, thereby a bug in RetroArch itself when it comes to input handling.

Long story short; ms-dos has a special kind of way of handling gamepads, two gamepads connected gives you 2axis on each gamepad (2 action buttons and four directional buttons), but if you want to use a 4axis gamepad (4 action buttons and four directional buttons), only one gamepad can be connected to the ms-dos PC.

Games like Tyrian2k has 4axis support and uses all the 4 action buttons on a supported joystick. In 2 player mode, one player uses the Keyboard while the other uses Joystick (or mouse).

While using a dosbox libretro core in RetroArch, RA can trick the core itself to think that the two controller devices in games like Tyrian2k in 2 player mode is Keyboard and Joystick, while in reality it's configured to output to two Xbox One gamepads instead.

That's all good and all, but there is an issue here caused by RA that makes it impossible to choose "User 1 Device Type" as "Keyboard" and User 2 Device Type" as 4axix "Joystick" (Gamepad/Joystick, with support for all 4 action buttons).

### Actual behavior

If "User 1 Device Type" is set as Keyboard, "User 2 Device Type" can only be set as 2axix "Gamepad" or "Joystick". If I switch around however, and make the first device Gamepad and second device Keyboard, I get full 4axis support for the "User 1 Device Type".

I would rather prefer to have "User 1 Device Type" as Keyboads because then I can navigate the menus in games like Tyrian2k with my Xbox One gamepad (perfect for a couch HTPC setup, menus not navigable with a joystick device type in this game).

I created the linked issue thread above to cover this bug, but was told that RetroArch itself is the issue there and not the input handling of the dosbox svn libretro core itself.

Thereby by selecting "Keyboard" in "User 1 Device Type" in the dosbox svn core, the gamepad option is still active under "User 1 Device Type" even by selecting "Keyboard" as the preferred device. Because of that, selecting Gamepad/Joystick under "User 2 Device Type" afterwards limits the player 2 device to a 2axis Gamepad/Joystick (only 2 action buttons).

If I want to use two 2axis gamepads/joystick in the ms-dos environment in the dosbox svn core, I'm forced to then make both "User 1 Device Type" and "User 2 Device Type" gamepad/joystick, thereby if I rather would make "User 1 Device Type" as a Keyboard device,  only "User 2 Device Type" can be selected as a 2axis gamepad/joystick, while "User 3 Device Type" can't be selected as a 2axis gamepad/joystick at all because of this bug in RetroArch. In other words I can't skip the first port for gamepads, and make either a 4axis gamepad in the second port or two 2axis gamepads in port 2 & port 3 because of this issue.

### Version/Commit

- RetroArch: 1.8.1

### Environment information

- OS: Windows 10 64-bit

**Comment by fr500** [comment]
The problem is that `retro_set_controller_port_device()` is called for all ports regardless of the setting, and forwarded to the core as joypad

**Comment by Gagert** [comment]
It seems like the new libretro core named DOSBox-core finally fixed this issue, so I suppose I can close this thread now.
