### ISSUE TITLE
iOS - Online updater removed?

### ISSUE THREAD

**Issue by mrjschulte** [libretro/RetroArch#9717]
I suspect we lost the Online Updater functionality on iOS after the core updater code commit. @yoshisuga @Autechre64 

https://github.com/libretro/RetroArch/commit/cf586b72732335a984b5c94f7fe2aebdefa6bcfe

**Comment by jet082** [comment]
I can confirm this bug.

**Comment by twinaphex** [comment]
I'll ask @yoshisuga if he experiences this as well.

**Comment by twinaphex** [comment]
I think this will fix it -

https://github.com/libretro/RetroArch/commit/4736bef77b2ab790398de474da8db72faa93daf5

**Comment by mrjschulte** [comment]
Whilst that *may* have fixed it, the current iOS Xcode build is broken due to other changes that seem to have affected the build since your commit.

**Comment by mrjschulte** [comment]
I just submitted a new patch to quickly hack around the @ statement conflict in the new apple_platform.h from last nights commit.

This then allows a build of iOS with the Online Updater restored.

Thanks all!

**Comment by mrjschulte** [comment]
All good now! Thanks @Autechre64 !
