### ISSUE TITLE
Associating ROM file extensions with Retroarch in Windows + automatic core selection

### ISSUE THREAD

**Issue by n1ghttrap** [libretro/RetroArch#9726]
For years I've had to contend with using an app called Default Programs Editor 
 with strings such as "E:\Emulation\Emulators\RetroArch-Win64\retroarch.exe" -L "E:\Emulation\Emulators\RetroArch-Win64\cores\bsnes_accuracy_libretro.dll" "%1" to run ROMs straight from whatever folder they're in and have Retroarch load up the right core.

Could auto-core functionality be added whenever a ROM is directed to retroarch.exe without -L please?  Or if there's more than one core capable, a selection prompt?  I prefer to use Retroarch for its emulation functionality, enhancement features, and lag mitigation over its ability to browse ROMs. File indexing + Start Search can do this job far better, and I can use a context menu random file selection script from within folders too.  Having to futz with this on every installation is a bit of a pain.  Thanks in advance.

**Comment by RobLoach** [comment]
Dup https://github.com/libretro/RetroArch/issues/9718
