### ISSUE TITLE
[GLUI] Improper word wrap on non-latin characters

### ISSUE THREAD

**Issue by sinusinu** [libretro/RetroArch#9731]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

On displaying text with non-latin characters, GLUI does not wrap text correctly and draw text outside of the intended space.

### Expected behavior

Text should wrap properly like this:
![e](https://user-images.githubusercontent.com/1446561/68993295-c4af0d80-08b9-11ea-82ae-a83a73f7bea4.PNG)
![el](https://user-images.githubusercontent.com/1446561/68993297-c8db2b00-08b9-11ea-9736-2748fe82852c.PNG)

### Actual behavior

Korean
![k](https://user-images.githubusercontent.com/1446561/68993301-dd1f2800-08b9-11ea-9e79-bb5de4323751.PNG)
![kl](https://user-images.githubusercontent.com/1446561/68993302-df818200-08b9-11ea-958a-306bba455f32.PNG)

Japanese
![j](https://user-images.githubusercontent.com/1446561/68993306-ead4ad80-08b9-11ea-993b-86f8e65d782e.PNG)
![jl](https://user-images.githubusercontent.com/1446561/68993314-faec8d00-08b9-11ea-9ed5-022f01968916.PNG)

### Steps to reproduce the bug

1. Change language
2. There it is :p

### Version/Commit
- RetroArch: Latest nightly (1.8.1) / 0d284c4

### Environment information
- OS: Windows 10 Build 18362

**Comment by jdgleaver** [comment]
Yes, this is an annoying issue that affects XMB and Ozone as well.

Unfortunately, word wrapping non-Latin languages is rather difficult, and RetroArch currently has no facility for doing so (the existing word wrap function just counts characters and breaks at the last possible space - this doesn't work at all for Japanese, Korean, etc.)

A have a bunch of other things to do first, but I would like to have a go at adding a more robust word wrapping implementation at some point...

**Comment by sinusinu** [comment]
Just checked Ozone and I think you're right about that.
I didn't noticed that until now on the other menu drivers...probably because they didn't utilized like whole width of the screen for text?

It's just an annoying issue and not a crashing bug or something, so take your time! I guess I can live with this lol

**Comment by toshixm** [comment]
@sinusinu I have fixed the issue at #12445.
Could you confirm it if you can try to built from git or to use nightly build?
Please let me know if there are any problems.

**Comment by sinusinu** [comment]
@toshixm Tested using build from git, and it looks great!
I think I can close this issue with that. Thank you!
