### ISSUE TITLE
All nightly builds past the 16th break controls once a game is started

### ISSUE THREAD

**Issue by klepp0906** [libretro/RetroArch#9753]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Controls are no longer working once a rom is started for every nightly past the 16th.  (tried 17th, 18th, 19th) 

### Expected behavior

Controls to continue working as they always have.

### Actual behavior

I started the evening out updating and opening launchbox.  When I couldnt enter the RA menu or load my save state via my controller, I immediately tested with another emulator where controls worked fine.  That eliminated it as being an LB problem or controller problem so i started RA on its own.

At that point I could navigate the menu fine, but once a game was started - I had no controls.  Keyboard or controller.   To eliminate it being core related I tried another core and the problem persisted.  

I had just updated to the 19th so i began rolling back day by day.  The first to start working again was the build from the 16th.

### Steps to reproduce the bug

1. Start Retroarch with a new (17th+ nightly) build. 
2. Start a game with nestopia or beetle psx hw (just in case my luck was that bad core-wise)
3. Note that F1 wont bring up the menu, esc wont exit RA.  Controller buttons do nil etc.
4. Roll back to the 16th build and play games!

### Bisect Results

After 9b192dc3c1 Before 80e49531b1

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.81 79c336b6fd

### Environment information

- OS: Windows 10

**Comment by autofire372** [comment]
What joypad driver are you using? I can reproduce this by setting the joypad drvier to HID.

Additionally, the Xinput joypad driver is broken on windows, effectively disabling controller input. It doesn't break keyboard input, though.

Both these problems can be worked around (for me, at least) by setting the joypad driver to SDL2 and restarting.

**Comment by twinaphex** [comment]
The xinput joypad driver is not broken at all. I'd advise against spreading misinformation like that and qualify it instead by saying it doesn't work for you, because it certainly does for us. It might just be a specific issue you're having with one specific gamepad.

**Comment by klepp0906** [comment]
sorry gentleman.  I'm old and go down early :P

Up now, ill update to the latest nightly and try a different joypad driver.  Id prefer to use xinput of course, and its never failed me before - but until the crux of the issue is identified at least that'll give a better idea of where the problem lay.

does the joypad driver effect KB as well? as my KB also loses functionality once a game is launched in any post 16th builds.

**Comment by klepp0906** [comment]
SDL2 changes nothing.  Still no input.

the only difference is, instead of 1 popup notification saying controller configured in port 0 when i start RA, i get a double notification for some reason.

and when i start a game, i also get a double notification except the upper most one now says device disconnected from port 0 (sdl2)

so perhaps that gives a clue as to where this is stemming from as the 2nd notification isnt there in xinput but appears the controller is being disconnected under the hood for some reason.

**Comment by klepp0906** [comment]
tried bluetooth and wired.... for posterity.  As dolphin has some crazy behavior with the xbox controller when connected via bluetooth so i thought something may have worked its way into everything else.

alas. no difference.

**Comment by klepp0906** [comment]
just tried a DS4.  same difference except for DS4 wont navigate the menu either.   Stuck exiting the menu with the keyboard, or if i start a game - stuck exiting via closing the process ala task manager or right click/close the icon in the taskbar.

**Comment by Awakened0** [comment]
80e4953 changes stuff with polling type, so check if you have it set to the default Late setting under Input, Polling Type Behavior. Maybe Early and/or Normal are causing an issue. I have a Win64 nightly from the 18th that works fine with a wired Xbox One controller using Xinput with polling set to Late.

**Comment by klepp0906** [comment]
it is set to late.. should i try the others?   Would polling changes potentially affect keyboard as well?  (as after the 16th build i lose keyboard as well)

Was gonna ask what changed controls wise with that build, but you saved me the trouble ^^

**Comment by Awakened0** [comment]
If it's not working with Late, then it's probably something else. Always worth backing up your current config and trying a fresh one. Then if that works, compare them and start testing each of your non-default settings to see which one is causing the issue.

**Comment by klepp0906** [comment]
well, the config thing - always a solid troubleshooting step.  but im not sure how it would change anything when all im doing is swapping an exe back and forth.

still - you DID hit the nail on the head.   Oddest behavior ever.

going back to the cfg file.

if i load a build from the 16th or before, my polling shows as late as it always has.  (thats where i checked just now).

if i load a build from beyond that point, it clears it.  It shows nothing there.   I never checked as I didnt expect it to be able to change itself (since it simply reads it from the same cfg as anything else).

low and behold.  I press select/space or change it manually to late, and everything is back in working order.

worst - feeling - ever when something so dumb is the cause.   That being said, no freaking idea why changing builds would clear the setting to blank (but thats above my paygrade ;p)
