### ISSUE TITLE
Crashes with Mesen .98 Super Chinese 3 (Japan)

### ISSUE THREAD

**Issue by mcabel** [libretro/RetroArch#9760]
There is a crash with Mesen .98 Super Chinese 3 (Japan) just when pressing start on the first screen.
### Expected behavior
No crash. There is not crash with fceu nes emulator, but performance is not as good as mesen.

### Actual behavior
A white/blue screen and crash-like noise.
 
### Steps to reproduce the bug

1. Load the game
2. Press start

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.81

### Environment information

- OS: Windows 8.1

**Comment by SourMesen** [comment]
@hizzlekizzle This can be closed, the problem was unrelated to retroarch (and was fixed.)
