### ISSUE TITLE
buildbot.libretro.com security flaw

### ISSUE THREAD

**Issue by enesaltinkaya** [libretro/RetroArch#9766]
Hi,
I can go to this url and create delete files without any authentication.

I created a folder named "1_security_issue" to demonstrate the issue here,
http://buildbot.libretro.com//files.php#nightly%2Flinux%2Fx86_64%2F2019-11-21_cores

**Comment by hizzlekizzle** [comment]
Ok, thanks very much for this report! I edited your post so more people don't see it, but as soon as someone with access to that webserver is around, we'll get that locked down (or just kill it altogether).

Thanks again.

**Comment by hizzlekizzle** [comment]
ok, this should be fixed now. Thanks again for reporting it.
