### ISSUE TITLE
[VITA] Build fails because of networking.

### ISSUE THREAD

**Issue by ThePhxRises** [libretro/RetroArch#9770]
Using the buildbot recipe in libretro-super using the command 

`FORCE=YES NOCLEAN=1 EXIT_ON_ERROR=1 ./libretro-buildbot-recipe.sh recipes/playstation/vita`

This is the place where it exits

```
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: ./libretro_vita.a(net_udp.o): in function `UDP_Init':
net_udp.c:(.text+0x2b2): undefined reference to `gethostname'
/usr/local/vitasdk/bin/../lib/gcc/arm-vita-eabi/9.1.0/../../../../arm-vita-eabi/bin/ld: ./libretro_vita.a(net_udp.o): in function `UDP_GetNameFromAddr':
net_udp.c:(.text+0x4aa): undefined reference to `gethostbyaddr'
collect2: error: ld returned 1 exit status
```

This build method was working less than a week ago.

**Comment by twinaphex** [comment]
This is just the tyrquake core I think.

**Comment by ThePhxRises** [comment]
That would make sense, my terminal history didn't go far back enough for me to check, and I thought I was in the last stage of building. I'll try disabling it when I build tonight.

**Comment by ThePhxRises** [comment]
Yep, that was it, thanks!
