### ISSUE TITLE
[PS Vita] Ozone Menu Driver Not Working.

### ISSUE THREAD

**Issue by nlordell** [libretro/RetroArch#9782]
## Description

On a fresh install of RetroArch on my PS Vita, the ozone menu driver doesn't work correctly. More specifically it looks like the "glowing square box" that should indicate selection of a menu item is not around the selected menu item but instead fills up the entire screen. Additionally things like fonts seem to be rendered correctly so I don't think it is because of missing data.

### Expected behavior

The ozone menu to work as expected.

### Actual behavior

A blurry glowing rectangle box appears around the entire screen and no box around the selected menu item.

### Steps to reproduce the bug

1. HENkaku (Enso) on PS Vita with firmware 3.60
2. Download RetroArch_data.7z and RetroArch.vpk for version 1.8.1
3. Extract RetroArch data to ux0:/data/retroarch
4. Install RetroArch vpk
5. Select Settings > Drivers > menu > ozone
6. Restart RetroArch

### Bisect Results

Just started using PS Vita with RetroArch.

### Version/Commit

- RetroArch: 1.8.1

### Environment information

- System: PS Vita
- Firmware Version: 3.60
- HENkaku Release: 11
- Enzo Version: 1.1
- taiHEN Plugins: None

**Comment by Rinnegatamante** [comment]
Can you check your video driver? It seems new installation of RetroArch errnoeously set gl1 as video driver. If so, switch to vita2d and see if the issue persists.

**Comment by nlordell** [comment]
It is set to `vita2d`. I will check if when I change to `ozone` it gets reset to `gl1`, but under `xmb` menu driver it is definitely `vita2d` and everything seems to work flawlessly.

Would it be useful to share a screenshot (somehow) or was the explanation clear enough?

**Comment by frangarcj** [comment]
Sorry for the inconvenient. Ozone won't work on vita2d until I made an update on the gxm driver. I'll do it this weekend.

**Comment by nlordell** [comment]
@frangarcj No need to apologize! You guys are doing amazing work, just wanted to help out by submitting a minor issue I found.
Thanks! If you need something from me (testing, etc.) just let me know.

PS: I'm also excited to try your gpSP performance fixes :rocket:
