### ISSUE TITLE
[Suggestion] Please use the unifont as the default font for all UI

### ISSUE THREAD

**Issue by leoxxx** [libretro/RetroArch#9792]
https://savannah.gnu.org/projects/unifont
It's rough, but can display more characters.
![TIM截图20191127215135](https://user-images.githubusercontent.com/5364709/69730646-69a3d300-1163-11ea-85f8-11c0f7e61637.png)
![TIM截图20191127215154](https://user-images.githubusercontent.com/5364709/69731011-0fefd880-1164-11ea-9994-b9679363dd88.png)

**Comment by driver1998** [comment]
I am thinking about Source Sans, not sure how big that would be to support both Chinese and Japanese...

**Comment by driver1998** [comment]
Hmmm Noto Sans/Source Sans uses OTF formats that can't be loaded by RetroArch.

[Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) works great on RetroArch but that is a 20MB font for each language (Simplified Chinese, Traditional Chinese, Japanese, Korean), and no Arabic support.

![QQ截图20191207201609](https://user-images.githubusercontent.com/22699485/70374539-6ca27e80-192e-11ea-8f48-1eea8170a276.png)

We might just use unifont as a "good enough" default.

**Comment by guoyunhe** [comment]
please check #10699

**Comment by leoxxx** [comment]
> 
> 
> please check #10699

I‘ll test in next release. THX, first.

**Comment by leoxxx** [comment]
https://github.com/libretro/retroarch-assets/pull/366#issuecomment-647412227
