### ISSUE TITLE
Feature request: Manually edit playlists via UI

### ISSUE THREAD

**Issue by desperateCoder** [libretro/RetroArch#9809]
Hey guys!

As a developer i'm familiar to JSON and text-based data structures, but my best friend and gaming enthusiast isn't.

Editing the playlist files or generating them via tools isn't impossible, but i think the majority of the people would love an easy way to edit the playlists via the lakka UI.

We can already remove games from the playlists, but i didn't find a way to manually add an unrecognized game (not in DB) to a specific tab other than "Favourites", nor add a new gaming platform tab.

I asked the lakka guys first, they pointed straight at you :stuck_out_tongue_closed_eyes: 
https://github.com/libretro/Lakka-LibreELEC/issues/852

What are your thoughts about that?

**Comment by FreeShippingParty** [comment]
I think you're looking for [this](https://github.com/libretro/RetroArch/pull/9795) feature which was just added yesterday.

**Comment by desperateCoder** [comment]
@FreeShippingParty holy moly. Yep. That's it. Never mind, I guess? Thanks for pointing out! And thanks @all for your awesome work! 

I'll close this as a duplicate then...
