### ISSUE TITLE
[Suggestion] Add RetroAchievements Rich Presence Support to Retroarch

### ISSUE THREAD

**Issue by wilhitewarrior** [libretro/RetroArch#9814]
I'd like to see Retroarch support RetroAchievements' rich presence. For anyone unfamiliar this is a feature that, when programmed by the achievement developers, can broadcast to the player and online where the player is and what they're doing on a game. 

It's a neat feature imo, sometimes can even tell the player information that isn't explicitly told to you by the game. For example, on Resident Evil 2, I designed the rich presence to keep track of the number of zombies that had been killed by the player.

This feature already exists on Retroachievements standalone emulators like ralibretro but if someone could implement it into retroarch that would be awesome

![Rich Presence](https://user-images.githubusercontent.com/25572417/70043718-f816bb00-158e-11ea-9675-196996dc01cc.png)

Posting a bounty for this on bountysource as well.

**Comment by twinaphex** [comment]
OK, going to proceed to closing this. @Celerizer can then submit his solution on Bountysource.
