### ISSUE TITLE
Default ROM folder

### ISSUE THREAD

**Issue by amirrammari** [libretro/RetroArch#9829]
Hello.
What's the Default ROM folder?
![image](https://user-images.githubusercontent.com/23485114/70366785-3a057100-18af-11ea-857c-31894cb0f595.png)

**Comment by hizzlekizzle** [comment]
There is no default ROM location. We assume you already have those somewhere and then point your 'file browser' location to it.

**Comment by amirrammari** [comment]
What is the purpose of the download folder?
Can I put ROMs in the download folder?
cc: @twinaphex @Themaister @fr500 @bparker06 @kivutar

**Comment by twinaphex** [comment]
It's up to you whether to put them there or not. We don't set a default dir for content on Windows.

**Comment by hizzlekizzle** [comment]
The main purpose of the 'download' folder is that stuff RetroArch downloads (such as from the built-in content downloader) will go there.
