### ISSUE TITLE
Retroarch distortion when rotating the phone in vulkan api

### ISSUE THREAD

**Issue by Deivmsr** [libretro/RetroArch#9846]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Retroarch presents the problem of menu distortion when using the vulkan api. 

### Expected behavior

[What you expected to happen]

Now that Flycast has api vulkan support, I think it would be comfortable for the Android user to use the emulator without this problem which is unpleasant when you want to enjoy the emulator and comes across this distortion every time you rotate your phone for some reason. .

[What is actually happening]
This happens depending on how you enter the app and rotate the phone, that is, if I open and the app is in portrait mode and turning the phone to landscape mode mine is distorted. If I open the app in landscape mode and rotate the phone to portrait mode, the app as a whole is distorted. This also affects the virtual buttons according to the attached screenshots.

### Steps to reproduce the bug

1. On Android, open Retroarch
2. Go to "Driver" and change to "Vulkan"
3. Restart the app
4.Rotate your phone screen and you will notice image distortion.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit

You can find this information under Information/System Information

- RetroArch: [version/commit]
Retroarch 12/12/2019 commit 1f866db

### Environment information

- OS: Android (Galaxy Note 9, SD 845)
Distortion images:
![Screenshot_20191205-233320](https://user-images.githubusercontent.com/40547165/70710902-9bb24a80-1cb6-11ea-808c-6402e777d80c.jpg)
![Screenshot_20191205-233349](https://user-images.githubusercontent.com/40547165/70710903-9bb24a80-1cb6-11ea-897f-4421cff4b1a6.jpg)
![Screenshot_20191212-051935](https://user-images.githubusercontent.com/40547165/70710904-9c4ae100-1cb6-11ea-84c1-709df8b2ace3.jpg)
![Screenshot_20191212-052627](https://user-images.githubusercontent.com/40547165/70710906-9c4ae100-1cb6-11ea-9d83-ef05b4a0c488.jpg)

**Comment by twinaphex** [comment]
Yes, this is a known issue. No fix yet for it.

**Comment by flyinghead** [comment]
Should be fixed by https://github.com/libretro/RetroArch/pull/9860/commits/15ffffa835f343aae640bd12319a904ffac07c19

**Comment by Deivmsr** [comment]
Fixed this issue. Confirmed at nightly compilation with commit e9a2642. Thank you all. It will now be possible to make better use of cores that support vulkan.
