### ISSUE TITLE
ROM Crashes when trying to load

### ISSUE THREAD

**Issue by Phoenix1991-lab** [libretro/RetroArch#9865]
I am having an issue loading a ROM. When I go to load it, the program crashes. I have tried changing my drivers to no avail. What else can I do to prevent the program from crashing when trying to load a ROM? This happens on every single core I have. I am running the latest version if Windows 10 and the latest nightly build of Retroarch. Please respond ASAP! Thank you!

**Comment by RobLoach** [comment]
Log can help. The issue template also comes with a few details that are missing...
```
### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]
```

**Comment by Phoenix1991-lab** [comment]
Here are the steps I take to reproduce the bug.
Step 1. From the Main Menu, select load core.
Step 2. Select your desired core. In my case, it was Mupen64Plus Next.
Step 3. Back in the main menu, select Load Content.
Step 4. Choose your ROM.
Step 5. From the quick menu that appears, select Run.
From there, the program crashes and does not give me any log. What do I need to do to fix this. My boyfriend got it to work just fine on his computer. Please respond ASAP! Thank you!

**Comment by Phoenix1991-lab** [comment]
Sorry for the double posting, but if I am missing something that needs to be installed on my computer, I need to know what it is.

**Comment by devinprater** [comment]
Which ROM are you having a problem with?

**Comment by Phoenix1991-lab** [comment]
I am trying to load Super Smash Bros. N64 on Mupen64Plus Next. Note
that I have tried the perilel N64 core to no avail. I have even tried
changing the drivers to no avail. Am I missing a dependency?

**Comment by RobLoach** [comment]
Logs will tell you if you're missing something. `retroarch --verbose` or use the log file.

Another option could be to try a different core. Parallel is a good one if you have the hardware for it.
