### ISSUE TITLE
Setting frontend log level higher than core log level causes core logs to not appear

### ISSUE THREAD

**Issue by negativeExponent** [libretro/RetroArch#9872]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Setting frontend log level higher than core log level will hide core level logs as well.

### Expected behavior

i expected that frontend log level would only affect frontend logs (usually seen as [INFO], [WARN], etc).
while core log level would only affect core logs (usually seen as [libretro INFO], [libretro WARN] etc)

### Actual behavior

Setting frontend log level higher affects core log levels.

### Steps to reproduce the bug

Set frontend level to 2 [Warning], set core log level to 1 [Info].
Launch a core that has lots of [libretro INFO] in them. (most cores are using INFO anyways)
you wont be able to see core logs.

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: 1.8.1-master

### Environment information

- OS: i use arch btw!
- Compiler: 9.2.0

**Comment by negativeExponent** [comment]
no response either...

**Comment by twinaphex** [comment]
Perhaps nobody knows and they're waiting for anybody to send a PR to fix it?

I'm going to reopen this just so that it can be on somebody's radar, but I don't think it's reasonable to expect that we are aware of every single Github issue here or that we are even able to solve all of this ourselves. Just more contributors other than the main team need to chip in and do their thing to resolve some of these issues.

**Comment by negativeExponent** [comment]
can put tag/label at least so it does not get buried at least?

**Comment by LibretroAdmin** [comment]
Does this still happen? Could attempt to finally look into this if so. Better late than never right?

**Comment by negativeExponent** [comment]
This seems to be working good with latest commit, too bad though that cores barely has any usable logs anymore though...
