### ISSUE TITLE
how to update RetroArch 1.7.9 to 1.8.1  stable? for windows

### ISSUE THREAD

**Issue by candrapersada** [libretro/RetroArch#9882]
how to update RetroArch 1.7.9 to 1.8.1  stable? for windows from online updater

**Comment by IronYoshi64** [comment]
> 
> 
> how to update RetroArch 1.7.9 to 1.8.1 stable? for windows from online updater

You can't update the RetroArch stable version directly from the interface. Go here to always get the latest version: https://www.retroarch.com/index.php?page=platforms

Download the version of your choice, then extract all the files to where you have RetroArch installed. Replace the newer files over the old files.

**Comment by candrapersada** [comment]
whether in the future there will be an update menu?
and why https://www.retroarch.com/index.php?page=platforms there is no minimum package download like this?
![game](https://user-images.githubusercontent.com/36833664/71335104-b5d01080-2573-11ea-8dca-cfcea2e61c67.PNG)
![zip](https://user-images.githubusercontent.com/36833664/71335403-3cd1b880-2575-11ea-9434-4bb343270c4a.PNG)

**Comment by IronYoshi64** [comment]
@candrapersada You can also go here to get the various download options as well: http://buildbot.libretro.com/stable/

**Comment by candrapersada** [comment]
add menu
![update](https://user-images.githubusercontent.com/36833664/71351874-6572a600-25a7-11ea-8bb4-b364dc7f43fe.PNG)
 check for version update from RetroArch and
add 
![game](https://user-images.githubusercontent.com/36833664/71351517-74a52400-25a6-11ea-8395-7575829744da.PNG)
to web page https://www.retroarch.com/index.php?page=platforms

**Comment by gouchi** [comment]
Hi,

Please try to respect [issue template](https://github.com/libretro/RetroArch/blob/master/.github/ISSUE_TEMPLATE.md).

    Only RetroArch bugs should be filed here. Not core bugs or game bugs
    This is not a forum or a help section, this is strictly developer oriented

On the forum, you may have found this tool called [Stellar](https://forums.libretro.com/t/i-made-a-nightly-updater-program/5617). You can configure it to use stable version.

Thank you.

**Comment by RobLoach** [comment]
Desktop UI has an updater too:
https://www.youtube.com/watch?v=l_n9pU-bfFs

**Comment by freecodecampster** [comment]
> Desktop UI has an updater too:
> https://www.youtube.com/watch?v=l_n9pU-bfFs

![Screenshot 2021-03-31 155940](https://user-images.githubusercontent.com/28160999/113166162-68dcee80-923a-11eb-803d-f0e9d63b82a0.jpg)

I don't see the tools menu item on the desktop menu with RetroArch v1.9.1 on Windows 10 Win64.

**Comment by hizzlekizzle** [comment]
Desktop UI's updater has been removed, as it broke awhile back. A new updater (that won't be dependent on the Qt stuff) is in the works.

**Comment by candrapersada** [comment]
when will there be an option to update?
