### ISSUE TITLE
1.8.2 Xbox One Controller - Guide Button Odd Mapping Behavior

### ISSUE THREAD

**Issue by televandalist** [libretro/RetroArch#9891]
## Description

The guide button (the big X button in the middle) on my Xbox One controller seems to be automatically assigning itself to unassigned hotkeys.

### Expected behavior

Before the update, I would use the guide button to simply open and close the RetroArch menu while running a game. 

### Actual behavior

It started with the guide button triggering netplay features and activating mode switch and slow motion in the PCE core, It took a while to notice, but all these features were unmapped in my hotkey binds. 

### Steps to reproduce the bug

1. Fresh install of RetroArch 1.8.2
2. Turn on Xbox One controller
3. Use the guide button and watch the world turn upside down

### Bisect Results

After a fresh install of Windows 10 and RetroArch 1.8.2

### Version

- RetroArch: 1.8.2

### Environment information

- OS: Windows 10

**Comment by twinaphex** [comment]
How do I reproduce this issue? I've connected a wired Xbox One pad to it and I don't experience this issue.

Do you have the Game Bar toggle disabled?

**Comment by televandalist** [comment]
I recently upgraded my hard drive and reinstalled Windows 10 - I don't think Game Bar is even a thing anymore? It got switched over to an Xbox Accessories app that needs to be downloaded from the Microsoft Store. 

All I did was install RetroArch 1.8.2 + nightly + Redist. 

I got it to a point where the only issue I was still having was that the guide button was still toggling 2 and 6-button mode for pad 5 in Beetle PCE Fast. I restarted RetroArch and it made everything BUT the guide button stop working, but the guide button was mapped to the up key.

**Comment by hizzlekizzle** [comment]
This sounds similar to a problem that people have had with some outside programs--including Launchbox and Steam--triggering various functions within RetroArch. For Launchbox, at least, it seems to be related to the Windows key event API.

**Comment by televandalist** [comment]
Yeah, I had that issue before with Steam, so that was the first thing I took care of here. I had to start from scratch today after not messing with input mapping for over a year :sweat: 

So my only really issue now is the 2/6-button mode switch for pad 5 in Beetle PCE Fast being toggled with the guide button.

**Comment by negativeExponent** [comment]
> Yeah, I had that issue before with Steam, so that was the first thing I took care of here. I had to start from scratch today after not messing with input mapping for over a year sweat
> 
> So my only real issue now is the 2/6-button mode switch for pad 5 in Beetle PCE Fast being toggled with the guide button.

if you are actually quoting PCE Fast (not other pce core) for pad 5 having issue, then its a possible core issue since only 2 pads are initialized for libretro' use. https://github.com/libretro/beetle-pce-fast-libretro/blob/master/libretro.cpp#L1699

try if the same issue is the same on pce (no fast) or supergrafx core

**Comment by televandalist** [comment]
Seems like I had a lot of odd stuff on my end. Did another fresh install of everything and I'm no longer experiencing any of these issues. Sorry!

Closing the  issue.
