### ISSUE TITLE
[PSVITA]1.8.2 crashed

### ISSUE THREAD

**Issue by EllenZhao** [libretro/RetroArch#9899]
PSVITA 1.82 crashed when retroarch launch.It has error with code c2-12828-1

**Comment by Sanaki** [comment]
According to Katlamos (discord), this issue began with the December 15th nightly, and wasn't present on the 14th.

**Comment by twinaphex** [comment]
Requesting comment by @frangarcj.

**Comment by EllenZhao** [comment]
I uninstalled it and deleted all the data of retroarch, then i reinstall it, it seems worked. I copying the data files now

**Comment by twinaphex** [comment]
Hmm, that seems to be a common occurrence for a lot of people. Wonder what is causing old retroarch.cfg files of prior versions to be so problematic on Vita.

**Comment by EllenZhao** [comment]
Is online updater removed on psvita?

**Comment by twinaphex** [comment]
That wasn't intentional at least as far as I know. Perhaps we forgot to add the new defines. I'll try adding them. Perhaps we can rebuild the 1.8.2 stable for Vita then.

**Comment by Youpi-38** [comment]
Hello, I just installed it and it also crashes on startup. 
Here is the message: (C2-12828-1) Saved Core File Succeeded. ux0: data / psp2core- 1577436105- 0x00002f209b-fbalpha2012_neogeo_libreto. self.psp2dmp
;-)

**Comment by EllenZhao** [comment]
> Hello, I just installed it and it also crashes on startup.
> Here is the message: (C2-12828-1) Saved Core File Succeeded. ux0: data / psp2core- 1577436105- 0x00002f209b-fbalpha2012_neogeo_libreto. self.psp2dmp
> ;-)

Try to delete ux0:data/retroarch/retroarch.cfg

**Comment by Youpi-38** [comment]
> > Hello, I just installed it and it also crashes on startup.
> > Here is the message: (C2-12828-1) Saved Core File Succeeded. ux0: data / psp2core- 1577436105- 0x00002f209b-fbalpha2012_neogeo_libreto. self.psp2dmp
> > ;-)
> 
> Try to delete ux0:data/retroarch/retroarch.cfg

OK, that's good, it starts.
But I obviously lost my settings ;-)

**Comment by EllenZhao** [comment]
psvita seems still can't start netplay as server

**Comment by falken1975** [comment]
I have observed that in the recent version 1.8.2 a systematic crash occurs in RetroArch whenever new widgets are deactivated.

**Comment by Katlamos** [comment]
I can say (I'm Katlamos mentioned earlier) that after doing a clean install on my Vitas, I was able to get the recent stable build running on both my Vitas.

**Comment by mattgoldspink** [comment]
> Is online updater removed on psvita?

I'm also seeing it missing. Let me know if you'd like me to open it as a separate ticket.

**Comment by twinaphex** [comment]
@frangarcj Can you look into this?

**Comment by frangarcj** [comment]
I'll take a look

**Comment by frangarcj** [comment]
Online updater re-added

**Comment by EllenZhao** [comment]
> Online updater re-added

download nightly?

**Comment by twinaphex** [comment]
@frangarcj Is there no Core Updater on Vita?

**Comment by frangarcj** [comment]
The directory is not writable so no core updater

**Comment by mattgoldspink** [comment]
Thanks @frangarcj - Just tested nightly and it loaded without a hitch. I can see the online updater now too!
