### ISSUE TITLE
Cheevos: Error in leaderboard causes Segfault when resetting core

### ISSUE THREAD

**Issue by negativeExponent** [libretro/RetroArch#9903]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

Segfault when resetting core with cheevos enabled and an error in leaderboard.
```
[INFO] [Autoconf]: selected configuration: /home/negative/.config/retroarch/autoconfig/udev/Microsoft X-Box 360 pad.cfg
[INFO] [RCHEEVOS]: got game id 12895
[INFO] [RCHEEVOS]: got achievements for game id 12895
[ERROR] [RCHEEVOS]: Error in leaderboard 4642 "tele-test": Invalid memory operand mem: STA:0xh0133=0_0xh0153=0_0xh014c=1::CAN:0xh011b=1_0xh011d=1_0xh023a=0::SUB:0xh0133=0_0xh0153=1::VAL:b0xh027c*10000_b0h027b*100
[INFO] [RCHEEVOS]: cheevo 67851 deactivated (softcore): N'ice' to meet you
[INFO] [RCHEEVOS]: posted playing activity
[INFO] [RCHEEVOS]: Load task finished
[INFO] Reset.
Segmentation fault (core dumped)
[negative@arch retroarch]$ 
```

### Expected behavior

safely can ignore error or no crash

### Actual behavior

segfaults

### Steps to reproduce the bug

Note: i only tested with these combination but possbile an error in leaderboard can cause problems to others as well:

Core used: Mednafen NGP (or the unofficial Race NGPC with cheevos support)
1. load the game Rockman - Battle & Fighters (i guess any rom with cheevos would do) 
2. After achievements are loaded, reset the game
3. segfault

### Bisect Results

backtrace log: https://hastebin.com/icoqiqotoq.cs
it did not matter whether leaderboards was on or off

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit] 1.8.1 a01e99aa63

### Environment information

- OS: [The operating system you're running] Linux - Arch x64
- Compiler: [In case you are running local builds]  gcc 9.2.0

**Comment by twinaphex** [comment]
@Jamiras Is this something you'd like to look into?

**Comment by Jamiras** [comment]
Will do.

**Comment by negativeExponent** [comment]
thanks for the fast update. but i can't config this just incase a test is needed. there doesn't seem to be a leaderboard enabled for the game or system atm

**Comment by Jamiras** [comment]
When I reported the invalid leaderboard to the developer they indicated that the desired resolution was to eliminate the leaderboard, so it was deleted.

If you do want to test this, you just need to find some game with a leaderboard, and hardcore an error state here: https://github.com/libretro/RetroArch/blob/410e94aa89d0a102718e1cb2d42a385c9e039d2e/cheevos-new/cheevos.c#L480

`RC_INVALID_MEMORY_OPERAND` was being reported in your log file.

**Comment by negativeExponent** [comment]
nah, i trust your judgement :D ill reopen the case when i find the same issue again.

@twinaphex PR should be safe to merge Thanks all
