### ISSUE TITLE
Shader Presets are not loading automatically since RA v1.7.7

### ISSUE THREAD

**Issue by SwiftMove** [libretro/RetroArch#9904]
## Description
Shader presets are not loading automatically. This happens with several cores I tested, Mesen, higan, Mupen64Plus, and on two different platforms, Windows & Nintendo Switch.

### Expected behavior
Load a ROM and have the shader preset be applied automatically.

### Actual behavior
Load ROM and shader preset is not being applied automatically.

### Steps to reproduce the bug
RetroArch v1.7.8-v1.8.2
1. Load ROM
2. Toggle to Quick Menu
3. Shaders > Video Shaders (On) > Load Shader Preset > shaders_glsl > hqx > hq3x.glslp
4. Exit RA and check "retroarch.cfg"
   - video_shader = "" (This line doesn't get generated)
   - video_shader_enable = "true" (This gets changed from "false" to "true" just as it should)

RetroArch v1.7.7
1. Load ROM
2. Toggle to Quick Menu
3. Shaders > Video Shaders (On) > Load Shader Preset > shaders_glsl > hqx > hq3x.glslp
4. Exit RA and check "retroarch.cfg"
   - video_shader = ":\shaders\shaders_glsl\hqx\hq3x.glslp"
   - video_shader_enable = "true"

As you can see, v1.7.7 correctly generates the necessary lines in the config file, where v1.7.8-1.8.2 does not. And just to be clear, creating these lines "manually" still doesn't cause RA to load the presets automatically like it should. So it would seem that RA v1.7.8-v1.8.2 are ignoring the 
video_shader = ":\shaders\shaders_glsl\hqx\hq3x.glslp" line completely.

### Bisect Results
The last version of RA that I have saved in my Backups that works correctly is "Nightly v1.7.7 2019-05-23". The oldest version of RA that I have saved in my Backups that isn't working correctly is "Nightly v1.7.8 2019-08-28". So I'm thinking that something changed somewhere in v1.7.8 that caused this issue.

This doesn't seem to be a "core" issue as I was able to reproduce this issue using only the main RetroArch files. Changing to different core versions didn't have any effect on the issue.

I was also able to reproduce this on Windows and Nintendo Switch platforms using the same RA versions.

### Version/Commit
- RetroArch: 1.7.7/cec5f95da0/2019-05-23 - Oldest backup of RA that I have saved where this issue ISN'T occurring.

- RetroArch: 1.7.8/d3632ea/2019-08-28 - Oldest backup of RA that I have saved where this issue IS occurring.

This issue is also occurring in the lastest 1.8.2 version of RA as well.

### Environment information
- OS: Windows 8.1 64-bit/Windows 10 64-bit/Nintendo Switch

**Comment by cmitu** [comment]
The `video_shader` configuration options was removed in 1.7.8 - see https://www.libretro.com/index.php/retroarch-1-7-8-released - you should save a preset after you apply/load a shader in order for it to be persistent.

**Comment by SwiftMove** [comment]
> 
> 
> The `video_shader` configuration option was removed in 1.7.8 - see https://www.libretro.com/index.php/retroarch-1-7-8-released - you should save a preset after you apply/load a shader in order for it to be persistent.

I had a feeling it was going to be something dumb. I was thinking to myself, how could this issue be overlooked 4 stable releases later! lol

But yes, loading a shader preset, and then selecting "Save" from the Shaders menu, and choosing one of the options did resolve my issue. Thanks for the FYI! =)
