### ISSUE TITLE
[Linux/ARM64] Can not build 1.8.2 release

### ISSUE THREAD

**Issue by vanfanel** [libretro/RetroArch#9907]
Hi guys.

I can not build 1.8.2 release because I am getting an error that was not previously there:

```
retroarch.c: In function 'accessibility_speak_linux':
retroarch.c:29393:23: error: 'SIGTERM' undeclared (first use in this function); did you mean 'SILVER'?
       kill(speak_pid, SIGTERM);
                       ^~~~~~~
                       SILVER

```

Also, is there a way to disable accesibility for personal builds with a configure option? It makes not much sense to bake in so much code for most of personal builds.

**Comment by vanfanel** [comment]
I was able to build 1.8.2 release by adding 

`#include <signal.h>`

to the includes section of retroarch.c

By anyway, all that accesibility code should be optional I believe, same as networking is optional, etc

**Comment by RobLoach** [comment]
Mind pushing up a pull request with your change? Along with which options you used when attempted to compile?

**Comment by vanfanel** [comment]
@RobLoach Done! I hope the accesibility code can be made optional too (thats the code that is causing this to start with).

**Comment by gouchi** [comment]
This issue should be closed.
