### ISSUE TITLE
[SWITCH] 1.8.2 Unable to to input user/pass for retro achievements (or: keyboard input broken)

### ISSUE THREAD

**Issue by mtoensing** [libretro/RetroArch#9909]
## Description
When I try to input the username or password the keyboard does not disappear and the input is not entered. 

### Expected behavior
Keyboard should disappear after input is recognized and entered. 

### Actual behavior
Keyboard does not disappear and the input is not entered. Keyboard is always reappearing. 

### Steps to reproduce the bug

1. Open retroarch
2. Go to settings
3. Go to achievements
4. Switch "Achievements" on
5. Enter either username or password.

### Bisect Results
After the update to 1.8.2 

### Version/Commit
1.8.2 Switch

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by Ploggy** [comment]
Same for me^^  happens in all instances where the Switch Keyboard is accessed in Retroarch.. Initially appears correctly but after you enter your desired text and press enter, the Switch Keyboard keeps popping up causing me to hard close Retroarch (home button and X button)

**Comment by liamrwilkins** [comment]
I have the exact same issue. I have tried everything from Deleting everything on my SD card and reinstalling homebrew from scratch, to download Retroarch from the hb app store, to downloading it directly from Github. No luck:

Each time the switch keyboard is accessed, for any reason, it will not close and I am forced to hard close Retroarch. This is especially frustrating since it corrupts my save states.

**Comment by m4xw** [comment]
Crash report or it didn't happen.

**Comment by mtoensing** [comment]
Where are the logs located?

**Comment by m4xw** [comment]
/atmosphere/crash_reports

**Comment by mtoensing** [comment]
I just realized that it does not crash. You just can’t exit the keyboard screen and the input is not transferred into the settings fields. I’ll make a video. Hold my beer

**Comment by m4xw** [comment]
You need to press "+"

**Comment by mtoensing** [comment]
https://www.youtube.com/watch?v=7L9MNs4uKE8

**Comment by mtoensing** [comment]
"+" or "OK" does not work as you can see in the video

**Comment by m4xw** [comment]
@mtoensing What if you hit return? Theres a check for new line

**Comment by mtoensing** [comment]
nope. A new line does not change anything.

**Comment by mtoensing** [comment]
It seems like the keyboard does not send anything to retroarch. Therefore it validates an empty string.

**Comment by m4xw** [comment]
It got refactored, smth was probably broken.
We will investigate, dunno if we make it for the next stable, just got back into the office after vacation.

**Comment by mtoensing** [comment]
Workaround for the achievements or „cheevos“ as they are called in retroarch: edit the retroarch.cfg in the retroarch folder and fill in the user and password for cheevos.
