### ISSUE TITLE
Useless core info properties for multi systems cores

### ISSUE THREAD

**Issue by pasnox** [libretro/RetroArch#9913]
## Description

Cores info files are useless for multi systems cores.
By example there is no reliable way to distinguish system_id, supported_extensions for each system.

### Expected behavior

Able to parse per system properties for system id, supported extensions.

### Actual behavior

For example in the bluemsx_libretro.info:
Useless entries like:
```
systemname = "MSX/SVI/ColecoVision/SG-1000"
systemid = "msx"
database = "Microsoft - MSX|Microsoft - MSX2|Coleco - ColecoVision|Sega - SG-1000"
supported_extensions = "rom|ri|mx1|mx2|col|dsk|cas|sg|sc|m3u"
```

- RetroArch: [v1.8.1 / bfdc8e6]

### Environment information

- OS: Linux / Flatpak x86_64

### Ideas:

For such multi systems cores, we could decide:
- system separator like |
- system multi value separator like ;
- exact same number of entries for properties that matter (systemid and systemname by examples)
- extension sorted by order of declared systems
- system section unknown should be set empty (not skipped)

So for the reported properties, they could become instead:
```
systemname = "MSX|MSX2|SVI|ColecoVision|SG-1000"
systemid = "msx|msx2|svi|colecovision|sg_1000"
database = "Microsoft - MSX|Microsoft - MSX2|SVI - SVI|Coleco - ColecoVision|Sega - SG-1000"
supported_extensions = "mx1|mx2|dsk;cas|col|sg"
```

**Comment by i30817** [comment]
I know certain devs think brevity is a virtue, but my limit to that is in data files. I'd rather there was a less confusing deduplexing than a separator and array indexing analogies

Something like:
 
```
systemname = "MSX"
systemid = "msx"
database = "Microsoft - MSX"
supported_extensions = "mx1"
systemname = "MSX2"
systemid = "msx2"
database = "Microsoft - MSX2"
supported_extensions = "mx2"
systemname = "MSX2"
systemid = "msx2"
database = "Microsoft - MSX2"
supported_extensions = "mx2"
systemname = "SVI"
systemid = "svi"
database = "SVI - SVI"
supported_extensions = "dsk;cas"
... etc
```

Basically just turn the respective parser code into a loop and change the callers to potentially handle multiple returns.

**Comment by i30817** [comment]
Thinking about this the above suggestion maybe bad because of the repeating same named left side means it's not really a 'normal cfg parser' ready suggestion, so using that particular scheme for code reuse might be a bad move in itself. Meh.

**Comment by fr500** [comment]
it's rather simple.
RA supports **JSON**.  JSON is a perfect notation for things like this (see how much more playlists can do now by adopting JSON over the dumb format it was before

**Comment by hizzlekizzle** [comment]
As I mentioned to @pasnox on IRC, I think jdgleaver is planning to do some work on the online updater soon (which is the main consumer of core info files, AFAIK), and I'm slowly working on updating the info files with better organization and to include supported libretro features, such as savestate capabilities, cheat descriptors, etc. My hope is that frontends could use this information to tailor the user experience a little better.

**Comment by i30817** [comment]
That's cool. Speaking of playlists, any possibility to associate a core config file to a playlist instead of a 'core'?

**Comment by RobLoach** [comment]
The .info files are just metadata that RetroArch uses in various ways. A few notes on what has been suggested...

```
systemname = "MSX|MSX2|SVI|ColecoVision|SG-1000"
```

The System Name is a single string, and used for human readable core lists. You could have it as above, it would just look funky in the UI. Try changing it yourself, and see what you find works!

```
systemid = "msx|msx2|svi|colecovision|sg_1000"
```

The System ID is used for the Discord icon. Having multiple here doesn't make sense.

```
database = "Microsoft - MSX|Microsoft - MSX2|SVI - SVI|Coleco - ColecoVision|Sega - SG-1000"
```
This is already possible, but the names must match those in a database over at:
https://github.com/libretro/libretro-database/tree/master/rdb

```
supported_extensions = "mx1|mx2|dsk;cas|col|sg"
```
I see a combination of `|` and `;`.... This confuses me, and I want to go home.

Overall, I enjoy some of the suggested improvements. We're always looking to clean up the metadata. There has been some movement to clean up the .info files, and I'd love to see more of that happen. You'll find all the .info files over at:
https://github.com/libretro/libretro-super/tree/master/dist/info

**Comment by pasnox** [comment]
So, concretely, what are we doing for those *bad* info files, let them as is or have a specific task (this one ?) to track / remember we have to clean them ?
I could eventually make a move to json PR, but there was ongoing effort in the info as said earlier ?
So i'm a bit lost of the result of closing this task.
