### ISSUE TITLE
Whenever I go on RetroArch, all it shows is a black screen

### ISSUE THREAD

**Issue by ooferscooper** [libretro/RetroArch#9917]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description

[Description of the bug]

### Expected behavior

[What you expected to happen]

### Actual behavior

[What is actually happening]

### Steps to reproduce the bug

1. [First step]
2. [Second step]
3. [and so on...]

### Bisect Results

[Try to bisect and tell us when this started happening]

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: [The operating system you're running]
- Compiler: [In case you are running local builds]

**Comment by hizzlekizzle** [comment]
This isn't enough information to help you, and this isn't a good place to provide this sort of support, either. Can you come to the libretro forum, discord server or IRC channel?

**Comment by RobLoach** [comment]
This issue is missing logs, or any information requested. Follow hizzlekizzle to https://forums.libretro.com , or add details. Thanks!
