### ISSUE TITLE
Keyboard crashes app on Switch

### ISSUE THREAD

**Issue by smrtg** [libretro/RetroArch#9922]
On the Switch app, when the keyboard opens it cannot be closed (trying to exit it will result in it opening again, over and over) the only way to get out of this keyboard is to go to the home menu and close the app, which will make the Switch display the app crash message (application was closed due to an unexpected error)

Steps to reproduce the bug

1. Open the in-app keyboard at any time
2. Done

- RetroArch: [b6a4564]

- OS: Nintendo Switch 9.1.0/AMS 0.10.1

**Comment by newkind** [comment]
Can confirm the issue on the same setup - Switch 9.1.0 + AMS 0.10.1

**Comment by lordelan** [comment]
I can confirm this as well.
Switch 9.1.0 + AMS 0.10.1 + RetroArch 1.8.2

Can't login to my Retrochievements account this way unfortunately.

**Comment by Yoshideking** [comment]
I got three more guys on GBAtemp, myself included. We all on Kosmos 15.

**Comment by twinaphex** [comment]
We will have to wait on some of the Switch coders to get back from their holiday to look into this I'm afraid.

**Comment by mtoensing** [comment]
Already reported In #9909
