### ISSUE TITLE
"Download Core" option in the Online Updater not showing up

### ISSUE THREAD

**Issue by amirrammari** [libretro/RetroArch#9923]
Hello,
I using RetroArch UWP v1.8.2
How I can download a core?
I can't find the "core updater" option.

`menu_show_core_updater=1`

![C5768577-C7B6-487E-A164-686EBFB7D078](https://user-images.githubusercontent.com/23485114/71648500-33391500-2d1a-11ea-965e-5dd3406aa5ee.GIF)

**Comment by amirrammari** [comment]
I download cores manually but don't show on RetroArch:
![image](https://user-images.githubusercontent.com/23485114/71648721-22d66980-2d1d-11ea-8d02-da663ff6e0ea.png)

**Comment by hizzlekizzle** [comment]
Can you go to settings > user interface > views and make sure it's not hidden there?

**Comment by amirrammari** [comment]
@hizzlekizzle It's not hidden...
![image](https://user-images.githubusercontent.com/23485114/71648837-ab093e80-2d1e-11ea-85b5-e3bbb121e237.png)

**Comment by amirrammari** [comment]
cc: @twinaphex @Themaister @fr500 @bparker06 @kivutar

**Comment by twinaphex** [comment]
No pinging spam about this please. Also, issue has been addressed in chat.

**Comment by dominater01** [comment]
core updater wont work on xbox one as it has been disabled because the xbox one can only read in the core directory not write

**Comment by hizzlekizzle** [comment]
Alright, I'm going to close this issue, then, as it's working as expected.

**Comment by ehmry** [comment]
This is not "working as expected", there is no indication that something is wrong.

**Comment by wviana** [comment]
Hi there. Having this same issue on Xbox One. Already check item visibility, everything looks fine. Any tips for fixing this?

**Comment by dominater01** [comment]
> Hi there. Having this same issue on Xbox One. Already check item visibility, everything looks fine. Any tips for fixing this?
> 
> Update: Looks like I have all cores downloaded. Maybe it has something about it.
> 
> Is there a way to delete cores from RetroArch?

only on dev mode you can delete cores

**Comment by wviana** [comment]
@dominater01 
> only on dev mode you can delete cores
Do you mean RetroArch dev mode?
How do I get into it?

**Comment by dominater01** [comment]
> @dominater01
> 
> > only on dev mode you can delete cores
> 
> Do you mean RetroArch dev mode? How do I get into it?

you gotta pay the 20$ for a dev account for xbox so you can access it then sideload retroarch and then you'll get core access otherwise on retail you are not able too get to that location because ms blocked it

**Comment by wviana** [comment]
> > @dominater01
> > > only on dev mode you can delete cores
> > 
> > 
> > Do you mean RetroArch dev mode? How do I get into it?
> 
> you gotta pay the 20$ for a dev account for xbox so you can access it then sideload retroarch and then you'll get core access otherwise on retail you are not able too get to that location because ms blocked it

I do have Xbox dev account. As far as I know it's the only way to install RetroArch on it. 
So you mean I should explore RetroArch directories and delete cores from Xbox SO. is that it?

**Comment by dominater01** [comment]
> > > @dominater01
> > > > only on dev mode you can delete cores
> > > 
> > > 
> > > Do you mean RetroArch dev mode? How do I get into it?
> > 
> > 
> > you gotta pay the 20$ for a dev account for xbox so you can access it then sideload retroarch and then you'll get core access otherwise on retail you are not able too get to that location because ms blocked it
> 
> I do have Xbox dev account. As far as I know it's the only way to install RetroArch on it. So you mean I should explore RetroArch directories and delete cores from Xbox SO. is that it?

its not the only way

https://www.youtube.com/watch?v=4VCKYJ7Iqm8

on dev mode you can find the cores by ftping into your xbox with durangoftp
or you can do it this way https://youtu.be/a0EmpbRR_W8?t=127
