### ISSUE TITLE
retroarch emscripten bugs

### ISSUE THREAD

**Issue by mini536** [libretro/RetroArch#9924]
# First and foremost consider this:
- Only RetroArch bugs should be filed here. Not core bugs or game bugs
- This is not a forum or a help section, this is strictly developer oriented

## Description
Open Retroarch emscripten ,it says missing assets.

### Expected behavior
It should running normally when I start a core

### Actual behavior

It says missing assets

### Steps to reproduce the bug

1. [First step]Visit web.libretro.com
2. [Second step]choose a core such as VBA next
3. [and so on...]Click run,it says missing assets

### Bisect Results

[Try to bisect and tell us when this started happening]
since 1.8.2
### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]1.8.2

### Environment information
Chromium browser 78
- OS: [The operating system you're running]windows 7
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
@ToadKing will be investigating this issue within the next few days.
