### ISSUE TITLE
Manually installing cores is broken on Android since 1.8.2 / 2019-12-02

### ISSUE THREAD

**Issue by DerKoun** [libretro/RetroArch#9937]
Using "install or Restore a Core" on Android (ARM, smartphone) always shows the downloads folder as empty. When allowing unknown file extensions the core files are listed but tapping one crashes the app.

This broke between 1.8.1 and 1.8.2 or, more precisely, between the nightlies of 2019-12-01 and 2019-12-02 (#9795 maybe?)

**Comment by twinaphex** [comment]
Hi @jdgleaver , could you investigate this? it seems to be related to the custom scanner perhaps?
