### ISSUE TITLE
Retroarch startup fail xbox one

### ISSUE THREAD

**Issue by Brizzman1509** [libretro/RetroArch#9953]
Did a fresh install of retroarch 1.8.2 on the xbox one X yesterday. Tried to load up today and sends me right back to dev mode screen.

Tried multiple times since release of 1.8.2. Attempted uninstalling and reinstalling thinking may have been bad install but still happening crashes back to dev mode screen. 

- RetroArch: 1.8.2

- OS: Xbox one X

**Comment by RobLoach** [comment]
https://docs.libretro.com/guides/generating-retroarch-logs/

**Comment by retrojohnny** [comment]
Same thing for me is happening I have to reinstal the app every time I restart xbox one system or shut it down .
