### ISSUE TITLE
(Menu) Clean Playlists

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#9965]
## Description

If you add a bunch of games to your playlists, and then remove some individual games from the file system, you'll end up with outdated playlists. There will be games that are listed in the playlist, but the file is no longer there.

It would be great if there was a "Clean Playlists" option in `Settings > Playlists > Playlist Management` that would go through each entry in each playlist, and remove entries whose files are no longer there.

This is similar to Kodi's Clean Library feature, which will remove entries from your media library that are no longer there.

![Settings_media_library_video_library](https://user-images.githubusercontent.com/25086/71966330-5870cc00-31cf-11ea-8e37-9d1a0946bf9b.jpg)

### Expected behavior

1. Add games to a playlist
2. Remove some games from the file system
3. Use the Settings > Playlists > Playlist Management > "Clean Playlists" option
4. See that the files that you removed no longer appear in the playlist

### Actual behavior

1. Add games to a playlist
2. Remove some games from the file system
3. Try to play a game that you had removed from the filesystem
4. See that RetroArch complains that the game no longer exists

### Steps to reproduce the bug

1. Add games to a playlist
2. Remove the files from the file system
3. Try to play a game that you had removed from the filesystem
4. RetroArch complains that the game no longer exists

**Comment by jdgleaver** [comment]
Ah, I've been meaning to do this for ages!

I have a few other things to take care of first - I'll try to get it done next week   :)

**Comment by jdgleaver** [comment]
@RobLoach This should do the trick: https://github.com/libretro/RetroArch/pull/10013

**Comment by RobLoach** [comment]
Whoa! Nice work! Scanned to create a playlist, deleted a file, used "Clean Playlist", and the entry was removed. Very slick :cat: :tophat:
