### ISSUE TITLE
RetroArch wont launch on xbox one after system restart

### ISSUE THREAD

**Issue by retrojohnny** [libretro/RetroArch#9974]
# First and foremost consider this:
- Only RetroArch bugs 

## Description
Description of the bug]
I Installed retro arch for xbox one on dev mode. It works great untill I shut down the system and put it back on. At that point when I go to start retroarch app it shows icon then after 45 secs goes back to dev home screen on xbox. Only way to fix is I have to uninstall and reinstall everything when I want to play anytime I shut the system off this bug happens. Please help me to understand what is happening. I don't have any apps on the xbox system other then retroarch at this time.

### Steps to reproduce the bug

1. Install RetroArch on xbox one 
2. Play some games if you wish
3. Shut down system and turn it back on 
4. Go to launch RetroArch 
5. RetroArch icon shows up then it goes back to dev mode home screen  instead of opening app.

[Try to bisect and tell us when this started happening]

This has happened every time since I first installed RetroArch I can play and update everything in app but when system is shut done if I stay in dev mode or not when the system is turned back on it wont launch the app as mentioned.

### Version/Commit
Most current 

- RetroArch: [version/commit]
Most current for Jan. 2020 
### Environment information

- OS: [The operating system you're running]
 Xbox one 
Os version 
10.0.18363.8124

Thank you

**Comment by RobLoach** [comment]
Looks like a dup https://github.com/libretro/RetroArch/issues/9953

**Comment by retrojohnny** [comment]
> Looks like a dup #9953

Yes sorry and thanks rob I'm new to this and noticed but also noticed nothing more on this issues and found a few more dubs... was a solution every found yet or explanation.

**Comment by cnktknX** [comment]
Any news so far ?
