### ISSUE TITLE
Make menu navigation feel more like the PSP's XMB (Issue #1)

### ISSUE THREAD

**Issue by jayare5** [libretro/RetroArch#9980]
### Expected behavior

If you press and hold up, down, left or right, the cursor should take 1 step, quick pause, and then continue running through the rest of the list at a faster, but fixed speed. (I suggest using a PSP to get the expected feel of this on a menu with a lot of options. Maybe a PS3 would do, but I don't own one to confirm, I own a PSP.)
![RetroArch 1 Vertical cursor movement B](https://user-images.githubusercontent.com/26237704/73170870-7abe8100-40cd-11ea-950f-5de38ca67d04.gif)

### Actual behavior

The cursor currently starts slow, then gains speed to the point it skips too many entries per step.
![RetroArch 1 Vertical cursor movement A](https://user-images.githubusercontent.com/26237704/73170831-5fec0c80-40cd-11ea-9e3f-bbf518b887fd.gif)

**Comment by Ferk** [comment]
Having confirmations for everything can quickly become annoying.
Has there ever been a game platform that asked confirmation for taking a screenshot?
Maybe for some of the actions it might make sense, but not for everything.
Abusing confirmations for actions you take frequently (like save/load if you are savescumming) will just make your brain start automatically accepting any confirmation by reflex, making it useless.

**Comment by jayare5** [comment]
You know, I was gonna add that it can be optional to ask for alerts :P
Some users might also need to even take hundreds of screenshots too if they're in some kinda serious project to study a game at every frame or something, in that case it can be most painful yeah. (I have done that)

However, the reasons for adding alert for screenshots screenshots might be in part because of the other issues, like the cursor movement accidentally landing on that option and me pressing the button quickly because I thought it was gonna press something else. (Screenshot is next to Close content, and very close to savestate). When you use an emulator on PC though, you usually have a mouse, and it's actually not as easy to accidentally go into File / Take screenshot because you have to be very precise to do it. Some emus have the screenshot option inside a capture menu, or arent close to options you'd use a lot.

![snes9x screenshot](https://user-images.githubusercontent.com/26237704/72178730-844ba780-33b1-11ea-8473-f168fa851e68.png)

Another reason for this is that, on a PC it might be unnecessary since you can just go to the folder and delete. But on something like a Raspberry Pi, that screenshot will be there in the system forever unless you take the MicroSD out and put it on the PC just to clean those folders.

**Comment by jayare5** [comment]
I have updated the issue to address only 1 thing at a time, I will be re-posting the other issues later.

**Comment by RobLoach** [comment]
Isn't this how RetroArch's XMB functions currently? When you press Down, it goes down one entry, and if you continue to hold, it'll gradually scroll faster.

**Comment by jayare5** [comment]
> Isn't this how RetroArch's XMB functions currently? When you press Down, it goes down one entry, and if you continue to hold, it'll gradually scroll faster.

Ah yes, it currently does the gradually faster scrolling. This bounty is to remove that and make it only have a fixed fast speed so it doesn't increase beyond usability. The PSP's XMB is like that, it only has 1 fixed speed when it scrolls fast. It wont gradually increase.

In fact, the RetroArch's XMB does it correctly when you scroll to the menus on the sides! That one has a fixed fast speed, but not when you scroll vertically through menu entries..

**Comment by jayare5** [comment]
Just wanted to say, I am really happy with this change!!!!
This even fixed other obscure issues I was going to post about, but it won't be needed anymore.
I will be posting other issues I had planned :)
