### ISSUE TITLE
Extreme Rubberbanding Netplay

### ISSUE THREAD

**Issue by AtomicRaven** [libretro/RetroArch#9982]
## Whenever I use netplay I get extreme rubberbanding.  

Please see video:  https://youtu.be/caPjwPrDMy8

### Steps to reproduce the bug

Exact Retroarch Package is available here:  http://nhl94online.com/downloads/Retroarch-1.7.9-32.zip

Load Core: Sega Genesis PLus GX
Load Rom: nhl94.bin

1. Start Game and connect to someone online using relay or direct connection (port forward TCP 55435)
2. Play a game

### Bisect Results

It has always happened on my machine which is:

- Windows 7 Pro (wiped 1st build.  This is 2nd build, very lean, with same exact result)
- NVidia 1050 ti video card
- Asus z97 Pro 4 motherboard (using onboard audio)

The game works perfectly when I am not using NetPlay.

My config file:
https://nhl94rocks.com/media/retroarch.cfg

### Version/Commit

- RetroArch: 1.7.9 
Build Date: Oct 5 2019
Git Version: 908974dfe4

### Environment information

- OS: Windows 7 Professional service Pack 2
- Compiler: N/A

### Additional Notes/ Troubleshooting: 

I have been using Gens to play online with Kaillera for several years.  There is lag, but nothing like this.  My internet connection was DSL, and is now Gigabit fibre with different Routers.  Same result.

TCP vs UDP issue?

**Comment by AtomicRaven** [comment]
Anyone?

**Comment by twinaphex** [comment]
@hasenbanck Is this something that piques your interest to look into?

**Comment by hasenbanck** [comment]
@twinaphex Negative. No time for that in the moment.

**Comment by hizzlekizzle** [comment]
@AtomicRaven have you tried any other cores? genplusgx doesn't have deterministic savestates, AFAIK. Picodrive usually plays better with netplay and runahead.

**Comment by AtomicRaven** [comment]
I have not tried PicoDrive - I'm part of an online league that is using this build (now on 1.8.5 and same issue)

FYI everything works on a windows 10 laptop connected to same network, so can rule network out. My main Gaming CPU above still does not work...

**Comment by LibretroAdmin** [comment]
@Cthulhu-throwaway Pinging you in case there is anything interesting to learn from this old issue.
