### ISSUE TITLE
RetroArch 1.8.3 fails to load cores due to a Symbol error

### ISSUE THREAD

**Issue by Deinsti** [libretro/RetroArch#9989]
## Description

Upon updating to RetroArch 1.8.3 from the Snap store, cores fail to load due to a symbol error, the same error effects multiple cores from a variety of developers so assuming it's a RetroArch bug - upon testing this is independent of Linux Kernel and Distribution and only effects Version 1.8.3 (Git b9a6165)

### Expected behavior

Upon choosing a ROM, ISO etc and choosing the appropriate Core for example Mupen64 Next, the emulator should start and load the game as normal.

### Actual behavior

Transitions to a black screen and then goes back to the main menu with error message "Failed to load libretro core", in the log - the core outputs an error of:
[ERROR] Error(s): /home/user/snap/retroarch/360/.config/retroarch/cores/mupen64plus_next_libretro.so: symbol _ZTINSt6thread6_StateE, version GLIBCXX_3.4.22 not defined in file libstdc++.so.6 with link time reference. For the full log see below

This error is not exclusive to Mupen and the exact same error occurs on other heavier cores as well, such as: Mupen64 Next, Play!, Dolphin etc; though it should be noted that this error does not occur on lighter cores like PrBoom, DOSBox, Vice (C64) etc

### Steps to reproduce the bug

1. Load RetroArch
2. Download a heavy core
3. Load content and attempt to load the core
4. Should fail to load core with error shown in error log below:
[retroarch.log](https://github.com/libretro/RetroArch/files/4049477/retroarch.log)

### Bisect Results

This happened with the update to 1.8.3 and no such issues occured on 1.8.2 and lower

### Version/Commit

- RetroArch: 1.8.3 (Git b9a6165)

### Environment information

- OS: Tested on Lubuntu 19.04, Xubuntu 19.10 and Debian 10 [All AMD64]
- Compiler: N/A

PS: If I missed any information then please inform me; i'll add it if I can

**Comment by gouchi** [comment]
As it is related to snap package, please open it on the [dedicated repository](https://github.com/libretro/retroarch-snap/issues).

Thank you.
