### ISSUE TITLE
v1.8.3 crashes when home button is pressed (android) 

### ISSUE THREAD

**Issue by vicoutorama** [libretro/RetroArch#9991]
![IMG_20200111_175450](https://user-images.githubusercontent.com/46327531/72210671-b33f4780-349d-11ea-8fac-8f4476c95d5f.jpg)

## Description

Whenever I press the Home button and minimize the app, or scroll down the notification bar, Retroarch will crash (if a game was previously loaded). 

### Expected behavior

Game should be paused on background until the app is resumed. 

### Actual behavior

Retroarch crashes. 

### Steps to reproduce the bug

1. Open Retroarch 1.8.3 for android
2. Load a core
3. Load a game
4. Minimize the app (alternatively, scroll down the notification bar) 
5. When returning to the app, it crashes

### Bisect Results

Started imediately after updating to 1.8.3 on Play Store. 

### Version/Commit

- RetroArch: 1.8.3

### Environment information

- OS: Android 9 (with MIUI 11.0.4 on a Xiaomi Redmi Note 7)

Edit1: spelling
Edit2: attaching Crash Report

**Comment by telanus** [comment]
I've also ran into this problem. 

OS: Android 6

**Comment by MajorWilly** [comment]
Me too, Android KitKat.

**Comment by demodanza** [comment]
Happens to me too, my devices are Xiaomi MIPAD 4 (MIUI 10, android 8, snapdragon 660), Huawei Mediapad M5 lite (EMUI 8, android 8, kirin 659), Huawei Honour 5x (custom rom, android 7). Happens both in gl and vulkan.

**Comment by twinaphex** [comment]
I believe this should fix it -

https://github.com/libretro/RetroArch/commit/e4ef930b4791ae5289ddc983b4368569b585171f

We will probably push an updated stable version if we get more reports from guys like @jdgleaver confirming that it indeed worked - it worked for me but I always would like to get a secondary confirmation first.

**Comment by neronomy** [comment]
I can confirm this error. I'm on a OnePlus T6 Pro; Android Pie with Oxygen OS 9.17. I've screen recorded the error too that if that helps.

**Comment by komuta** [comment]
I can confirm also on both Note 10+ (Exynos) and Galaxy Tab S6 (S855). I got the same entrypoint in the backtrace at `2da080 / libretroarch-activity.so`. @twinaphex if you have a packaged version, I can check if your fix is working.

**Comment by twinaphex** [comment]
Just download the nightlies either later today or tomorrow.

**Comment by Sherazzie** [comment]
Same here galaxy j7 prime ,android oreo 8.1

**Comment by twinaphex** [comment]
Try the latest nightly build on our buildbot - for me it fixes the issue -

http://buildbot.libretro.com/nightly/android/RetroArch.apk

**Comment by komuta** [comment]
@twinaphex tested with nightly 2020-01-14, fixes the issue for me. Thanks for the quick fix!

**Comment by vicoutorama** [comment]
Nightly build fixed it for me too! Should I close the issue or we wait for more confirmations?

**Comment by jdgleaver** [comment]
Just for the record, I also confirm that the issue is fixed  :)

**Comment by demodanza** [comment]
Fixed on my end, thanks!

**Comment by telanus** [comment]
fixed for me toooooo

**Comment by EnRicoNasty** [comment]
Fixed for me only if i not lock the screen, after i lock the screen it crashes again, xiaomi mi 9.
