### ISSUE TITLE
Windows 10: Enabling the "Disable Desktop Composition" option leaves my PC speachless?

### ISSUE THREAD

**Issue by IngwiePhoenix** [libretro/RetroArch#9999]
## Description
When flipping the switch on "Disable Desktop Composition", none of my programs seems to be able to paly sound. As a matter of fact, when I turned the option on, Spotify just went silent and reported that it couldn't play the song, and Youtube, through Opera GX, reported that there was an issue playing back audio.

Actually, what is this feature meant to do? The little sub-label doesn't give that much information about what it is good for anyway.

### Expected behavior
Since I have no exact idea of what this feature is supposed to do, there was no expectation. From the name though, I was guessing that it would automatically foreground games running at the moment or take some kind of control over the overall desktop.

### Actual behavior
Spotify, Youtube (through Opera GX) and even Telegram and Discord were not playing any sound whatsoever.

### Steps to reproduce the bug
Enable the "Disable Desktop composition" option.

### Bisect Results
I am not aware of how this behaved on previous releases, sorry.

### Version/Commit
See pictures below.

### Environment information
See pictures below.

![image](https://user-images.githubusercontent.com/2893716/72277602-79ec1080-3632-11ea-8cf8-9a641244a018.png)
![image](https://user-images.githubusercontent.com/2893716/72277620-840e0f00-3632-11ea-8573-b9c143b74bea.png)
![image](https://user-images.githubusercontent.com/2893716/72277643-8cfee080-3632-11ea-8c72-ac446627c564.png)
![image](https://user-images.githubusercontent.com/2893716/72277657-95571b80-3632-11ea-9b48-c37e5f6a63f0.png)
![image](https://user-images.githubusercontent.com/2893716/72277672-9ee08380-3632-11ea-9f7e-7d6f04feef6d.png)

![image](https://user-images.githubusercontent.com/2893716/72277702-adc73600-3632-11ea-9759-570d9f54cb21.png)
This shows the error message on Youtube.

![image](https://user-images.githubusercontent.com/2893716/72277744-c59eba00-3632-11ea-96c6-1d3ceae89f06.png)
This is the error message Spotify shows.

Since it was not seen in the information screen, the GPU in use is a 2080 TI with the drivers updated yesterday. The audio device is a SteelSeries Arctis Wireless Pro, which uses a USB interface and the controller is a Razer Raiju Ultimate via Bluetooth.

**Comment by IngwiePhoenix** [comment]
Turns out having WASAPI enabled for the audio driver was what caused the issue O.o I decided to make doubly sure once again and check all my settings and, yes, my sound setting was changed. I must've accidentially hit it at some point and never really noticed... Anyway, that explains quite a lot.

Thanks for the amazing software!

**Comment by twinaphex** [comment]
I think this could happen if WASAPI is setup to run audio in exclusive mode. Exclusive mode means that all other programs on your computer get denied sound access so that only the app requesting exclusive mode (in this case RetroArch) gets to do sound. This is purportedly a more optimal way of doing sound. If you do not want this, you could turn off the Exclusive mode setting, it would then fall back to shared mode - in this mode, all other apps can still do sound at the same time as RetroArch.
